### ISSUE TITLE
[Bug-BE] [Workflow-define] The workflow saves a python task with special characters, and the save failure condition occurs

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#10009]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1、Create a special name for python task, such as "python-💥打印 "
![image](https://user-images.githubusercontent.com/59044203/168006060-c2602cfb-515f-4477-9a9e-cc3aecd8b57d.png)

### What you expected to happen

2 kinds of suggestions: 
1, special characters to give hints are not supported. 
2. Special symbols are compatibility with the prompt for successful processing

I recommend the one option.

### How to reproduce

1. create  "python-💥打印 " for task name

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/97265214/168006756-072a7a69-ca3f-4e84-b532-2f4d56ed1a88.png">
This seems to be a backend bug.

**Comment by SbloodyS** [comment]
The default charset is ```utf8```. emoji is not allowed in ```utf8```. And I think the emoji should not be allowed in ```workflow name``` and ```task name```.
