### ISSUE TITLE
[Feature][doc] Add a guide to nominate new committer

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#10006]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

we could learning from https://seatunnel.apache.org/community/contribution_guide/committer#project-management-committee

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
But should add after nominate should change doc in https://dolphinscheduler.apache.org/en-us/community/team.html and send nominate mail to `dev@dolphinscheduler.org`

**Comment by TyrantLucifer** [comment]
How's the progress of this pr? Can I do this work?

**Comment by zhongjiajie** [comment]
Looking forward your contribution
