### ISSUE TITLE
[Bug-BE] [log] After the Flink task fails, the corresponding log cannot be found

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#10010]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After the Flink task fails, the corresponding log cannot be found
![image](https://user-images.githubusercontent.com/59044203/168006732-507db5ef-9580-4004-b01e-76ce07b0dad7.png)

### What you expected to happen

The logs should be saved in the corresponding directory, such as: /opt/release/0511/worker-server/logs/20220512

### How to reproduce

Let the Flink task fail

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
It seems like your worker's log pattern was not the default setting of ```dev``` branch. Did you customize it? @welsh-wen

**Comment by welsh-wen** [comment]
How to set dev mode, please tell me.
