### ISSUE TITLE
[Bug] [Module Name] Bug title 

### ISSUE THREAD

**Issue by hwfbest** [apache/dolphinscheduler#10018]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![error](https://user-images.githubusercontent.com/16427578/168085758-9ed0a6f2-d078-4d33-91df-7b262681275c.jpg)
任务执行出现错误，这个错误原因不清楚，操作中发现任务一直在运行中，结束任务，再次运行还是这个情况；通过把任务导出，修改文件中任务的id，再导入进来，生成另一个任务，可以正常运行，但是后台日志一直不断输出错误日志

### What you expected to happen

1、任务几分钟一直在执行中，实际几秒钟执行完毕，于是结束了任务，但是再次执行还是无法运行；
2、后台master日志一直打印，expected one but found 2，这个错误无法理解，希望能对这个问题做修复处理，感谢！！

### How to reproduce

部署的为单节点，单台数据库，使用的为pgsql数据库作为元数据

### Anything else

刚开始部署使用，目前部署5个任务，发现2次同类问题

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
You should modify the title.

**Comment by hwfbest** [comment]
![image](https://user-images.githubusercontent.com/16427578/168639155-dfd1bd52-afb7-4735-a2e4-db43565df88e.png)
发现这个表中数据产生了重复，导致上面的bug问题，希望这个能帮助社区定位问题

**Comment by caishunfeng** [comment]
Please use the right title and describe in English, which can make more developers understand.
BTW, you should use screenshot or paste the error log stack, which can show your issue more clearly. Thanks.
