### ISSUE TITLE
[Bug] [Master] data quality task command: null

### ISSUE THREAD

**Issue by duspring** [apache/dolphinscheduler#10021]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/35389283/168205502-12e40c97-551e-4ce3-94ab-6cf4bfea9ae5.png)
![image](https://user-images.githubusercontent.com/35389283/168205502-12e40c97-551e-4ce3-94ab-6cf4bfea9ae5.png)
![image](https://user-images.githubusercontent.com/35389283/168205522-12e30c90-2888-4f33-a53c-3ba49548368b.png)

When verifying data quality rules, you must enter global variables or local variables. If you do not enter them, data quality task command: null will be reported.

### What you expected to happen

When verifying data quality rules, it can be verified normally without entering global variables or local variables, instead of having to write

### How to reproduce

Found when running the task flow to view the logs when validating the data quality rules

### Anything else

[LOG-PATH]: /opt/module/ds300/worker-server/logs/20220513/5501567964736_2-122-147.log, [HOST]:  Host{address='172.22.224.113:1234', ip='172.22.224.113', port=1234}
[INFO] 2022-05-13 03:22:54.375 [taskAppId=TASK-20220513-5501567964736_2-122-147] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.dq.DataQualityTask:[81] - data quality task params {"localParams":[],"resourceList":[],"ruleId":10,"ruleInputParameter":{"check_type":"1","comparison_type":7,"failure_strategy":"0","operator":"3","src_connector_type":0,"src_datasource_id":1,"src_field":null,"src_table":"testa","threshold":"0"},"sparkParameters":{"deployMode":"cluster","driverCores":1,"driverMemory":"512M","executorCores":2,"executorMemory":"2G","numExecutors":2,"others":"--conf spark.yarn.maxAppAttempts=1"}}
[INFO] 2022-05-13 03:22:54.400 [taskAppId=TASK-20220513-5501567964736_2-122-147] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.dq.DataQualityTask:[176] - data quality task command: null

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This issue will be fixed in #9974
