### ISSUE TITLE
[Bug] [docker image] dolphinscheduler-standalone-server render empty html

### ISSUE THREAD

**Issue by neillee1991** [apache/dolphinscheduler#10020]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

i'm using dolphinscheduler-standalone-server:3.0 image, it render an empty login page with console error below:

vendor.b9a93d45.js:1 
       Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

index.d6660488.js:1 
       Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

### What you expected to happen

some image problem 

### How to reproduce

just run image on docker

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Related issue: #9863 
I will close this issue.

**Comment by zhongjiajie** [comment]
FYI @SbloodyS , better to add duplicate label if you find som duplicate isue

**Comment by SbloodyS** [comment]
> FYI @SbloodyS , better to add duplicate label if you find som duplicate isue

Thanks.
