### ISSUE TITLE
[Bug] [dolphinscheduler-python] Command execution failed. Process exited with an error: 1 (Exit value: 1)

### ISSUE THREAD

**Issue by zheng-zy** [apache/dolphinscheduler#10046]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

ds-2.0.5下载源码包尝试本地编译打包过程中，出现如下错误：

### What you expected to happen

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (python-api-prepare) on project dolphinscheduler-python: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
具体如下图所示：
![image](https://user-images.githubusercontent.com/13825054/168565851-d7563b98-c05c-4749-86e1-3cb236677070.png)

### How to reproduce

查看了issue上类似问题，比如：[8820](https://github.com/apache/dolphinscheduler/issues/8820)，我确认我当前的python3环境正常，请问我该如何处理？
当前环境：
win10
jdk1.8
ds2.0.5（git上下载的tag版本）
python3.7.8
![image](https://user-images.githubusercontent.com/13825054/168565137-3985228b-3e51-4aa5-8fc8-1b103ec47276.png)

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zheng-zy** [comment]
@zhongjiajie help

**Comment by zhongjiajie** [comment]
@zheng-zy you should ru-run the command and with `-X` flag and see the output

**Comment by zhongjiajie** [comment]
there must have the detail error log

**Comment by zheng-zy** [comment]
detail error log:
[INFO] dolphinscheduler-server ............................ SUCCESS [ 26.444 s]
[INFO] dolphinscheduler-api ............................... SUCCESS [ 33.557 s]
[INFO] dolphinscheduler-python ............................ FAILURE [ 31.529 s]
[INFO] dolphinscheduler-standalone-server ................. SKIPPED
[INFO] dolphinscheduler-dist .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:08 min
[INFO] Finished at: 2022-05-17T09:41:40+08:00
[INFO] Final Memory: 234M/873M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (p
ython-api-prepare) on project dolphinscheduler-python: Command execution failed.
 Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
rg.codehaus.mojo:exec-maven-plugin:3.0.0:exec (python-api-prepare) on project do
lphinscheduler-python: Command execution failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Command execution fai
led.
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:478)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:207)
        ... 20 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an erro
r: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecut
or.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:
166)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:982)

        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:929)

        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:457)
        ... 22 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :dolphinscheduler-python



![image](https://user-images.githubusercontent.com/13825054/168710838-aa4c3fb1-44c9-4716-8bca-d8c3839e3a08.png)
![image](https://user-images.githubusercontent.com/13825054/168710956-96975aee-830f-4e03-9e22-06aef1fd7cf9.png)

> there must have the detail error log

**Comment by zhongjiajie** [comment]
@zheng-zy could you show me the detail log before

```log
[INFO] dolphinscheduler-server ............................ SUCCESS [ 26.444 s]
[INFO] dolphinscheduler-api ............................... SUCCESS [ 33.557 s]
[INFO] dolphinscheduler-python ............................ FAILURE [ 31.529 s]
[INFO] dolphinscheduler-standalone-server ................. SKIPPED
[INFO] dolphinscheduler-dist .............................. SKIPPED
```

There have some detail error log

**Comment by zhongjiajie** [comment]
And maybe you could try to comment the profiles in https://github.com/apache/dolphinscheduler/blob/2.0.5-release/dolphinscheduler-python/pom.xml#L61-L122 and then try again

**Comment by zheng-zy** [comment]
> ok,i will try it.
detail log before:
![image](https://user-images.githubusercontent.com/13825054/168723877-a26cda7a-d80c-4ba5-b634-50cf24c7df26.png)


> And maybe you could try to comment the profiles in https://github.com/apache/dolphinscheduler/blob/2.0.5-release/dolphinscheduler-python/pom.xml#L61-L122 and then try again

**Comment by zheng-zy** [comment]
> And maybe you could try to comment the profiles in https://github.com/apache/dolphinscheduler/blob/2.0.5-release/dolphinscheduler-python/pom.xml#L61-L122 and then try again

this pom.xml is the same as before，i try it has the same problem.

**Comment by zheng-zy** [comment]
@zhongjiajie this look like python proprem，dolphinschduler notsupport win10？

**Comment by zhongjiajie** [comment]
> 

dolphinscheduler could start in win, and could use APIserver  to CRUD object, but if you want to run workflow you have to make some change. and I do not know what change it is.

**Comment by zhongjiajie** [comment]
> > And maybe you could try to comment the profiles in https://github.com/apache/dolphinscheduler/blob/2.0.5-release/dolphinscheduler-python/pom.xml#L61-L122 and then try again
> 
> this pom.xml is the same as before，i try it has the same problem.

I mean, you should totally delete the those line code, and then try again

**Comment by zheng-zy** [comment]
> > > And maybe you could try to comment the profiles in https://github.com/apache/dolphinscheduler/blob/2.0.5-release/dolphinscheduler-python/pom.xml#L61-L122 and then try again
> > 
> > 
> > this pom.xml is the same as before，i try it has the same problem.
> 
> I mean, you should totally delete the those line code, and then try again

这个意思是把<profile>标签的内容注释掉吗？
![image](https://user-images.githubusercontent.com/13825054/169440194-5ee7818f-fc87-4fb8-b8cc-7ae937988582.png)

**Comment by zhongjiajie** [comment]
@zheng-zy Please also remove the tag `<profiles>` and then try to re-run it

**Comment by zhongjiajie** [comment]
and then it will skip the `python` build

**Comment by jianye0227** [comment]
@zhongjiajie 
After remove the tag <profiles>,but I get other new problem,like this:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.0:single (python) on project dolphinscheduler-dist: Failed to create assembly: Error creating assembly archive python-api: archi
ve cannot be empty -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :dolphinscheduler-dist

**Comment by jianye0227** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.0:single (python) on project dolphinscheduler-dist: Failed to create assembly: Error creating assembly archive python-api: archi
ve cannot be empty -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :dolphinscheduler-dist
