### ISSUE TITLE
[Feature][UI] The Failed to retry description should change to Recovery Failed

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#10047]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![](https://vip2.loli.io/2022/05/16/AT8NkL7d9bBrpHc.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by labbomb** [comment]
i will fix it

**Comment by songjianet** [comment]
Cherry-pick to 300b1 when done @labbomb
