### ISSUE TITLE
[Feature] [Http Task] HTTP parameter passing problem

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [apache/dolphinscheduler#10044]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

How are the results returned by HTTP task types given as parameters to the next node

### Use case

How are the results returned by HTTP task types given as parameters to the next node

### Related issues

How are the results returned by HTTP task types given as parameters to the next node

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This is not currently supported. You can write your own script to support it.

**Comment by ITBOX-ITBOY** [comment]
> This is not currently supported. You can write your own script to support it.

Now that I've developed this feature, how do I submit it

**Comment by SbloodyS** [comment]
> > This is not currently supported. You can write your own script to support it.
> 
> Now that I've developed this feature, how do I submit it

Develop your feature based on ```dev``` branch. And then open a pull request target to ```dev``` branch and link your issue to this 
 PR.

**Comment by ITBOX-ITBOY** [comment]
# http任务类型向下传递参数功能介绍


第一步：拖一个http类型的任务，在自定义参数中KEY的位置填写body ,在IN/OUT的部分选择OUT,在输出数据类型部分选择VARCHAR，一定要选择VARCHAR，不要选择别的哈。

![1-1](https://user-images.githubusercontent.com/15922437/170007418-e374be8d-9a86-4267-b09e-4fa9859462aa.png)


第二步：在添加一个http任务类型的节点，接收上游传递来的参数。这一次只需要在【请求参数】部分进行添加就可以了，

参数名可以任务的，可以body也可以是别的，类型选择parameter,value部分一定要写成${body}

![1-2](https://user-images.githubusercontent.com/15922437/170007447-e848bea5-4122-4ad1-bc50-135402327c2a.png)



配置好后的效果

![1-4](https://user-images.githubusercontent.com/15922437/170007489-8eca9c46-051e-4885-8a38-c244f3c051a2.png)



第三步，这一步你可以自己写一个测试接口，在接收上游参数的这个节点上调用这个接口来进行测试，测试一个上游的参数是否过来了
![1-3](https://user-images.githubusercontent.com/15922437/170007519-db6c6356-2e83-4e86-9de3-ba0a571bbe04.png)
