### ISSUE TITLE
[BUG] [Plugin] Conditions Task branch flow failed 

### ISSUE THREAD

**Issue by Dannila** [apache/dolphinscheduler#10049]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Condition is a condition node that decides which downstream task should run based on the condition of the upstream task. When the upstream task runs successfully, run the success branch. When the upstream task fails to run, run the failure branch. But now no matter whether the upstream task runs successfully or fails, only the tasks of the successful branch will be run.

### What you expected to happen

The Condition task should decide which downstream task should run based on the conditions of the upstream task.

### How to reproduce

Create a Condition task, determine the successful or failed branch task and run it。
![88b146a52756eca53062464932ce43ee83419c55aea5a79790e7b10f03a58656QzpcVXNlcnNcQWRtaW5pc3RyYXRvclxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcMjQ5MjQ4MDk3Ml92MlxJbWFnZUZpbGVzXDE2NTI2NzE4NDY0MjJfNkY4NkVDRTItM0RGMy00YTBkLTlBODctQkQzQ0M3RDJEMjQxLnBuZw==](https://user-images.githubusercontent.com/94423827/168713638-e0224f37-6974-4596-b0a9-ac9f6085c6aa.png)

When the upstream task runs successfully, Conditions select the successful branch task and run it.
![f8299c96165ba1ffcb11dbf8594d774f451f56f75a2ee249d7efef113123b647QzpcVXNlcnNcQWRtaW5pc3RyYXRvclxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcMjQ5MjQ4MDk3Ml92MlxJbWFnZUZpbGVzXDE2NTI2NzIzNzYzMTRfNEQwMEFFODItMkM0Mi00MzQ5LUEwQjItNjg3RTNGRkRBREU2LnBuZw==](https://user-images.githubusercontent.com/94423827/168713859-347362dd-9362-4372-afeb-dcbb97a94c3b.png)

But when the upstream task fails to run, Conditions still select the successful branch task and run it.
![7c0b8fa87da3b1ed1640c8c7cab9d8d1e5e6a32fd69df209fe46ef541c803686QzpcVXNlcnNcQWRtaW5pc3RyYXRvclxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcMjQ5MjQ4MDk3Ml92MlxJbWFnZUZpbGVzXDE2NTI2NzIyMDAwOTJfODJFRkMyRDgtRjdENC00OTE5LUIyNTEtREE2MUEyNjJCMDVFLnBuZw==](https://user-images.githubusercontent.com/94423827/168713942-d779fded-717f-41c6-af8e-d46b66de8a79.png)

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I will fix it.

**Comment by huangchenguang123** [comment]
> I will fix it.

Conditions should use previousNodes result, and now only use dependency result? I find add Custom Parameters can make it trigger fail Node....May be #10077 should use previousNodes and/or Custom Parameters? This is my doubt, don't mind if I'm wrong.

**Comment by SbloodyS** [comment]
> > I will fix it.
> 
> Conditions should use previousNodes result, and now only use dependency result? I find add Custom Parameters can make it trigger fail Node....May be #10077 should use previousNodes and/or Custom Parameters? This is my doubt, don't mind if I'm wrong.

Yes. In this PR, I change the detection logic to use previousNodes to check condition instead of use dependency result. 

However, I don't think the success or failure of task nodes should be related to user-defined parameters.

**Comment by huangchenguang123** [comment]
> > > I will fix it.
> > 
> > 
> > Conditions should use previousNodes result, and now only use dependency result? I find add Custom Parameters can make it trigger fail Node....May be #10077 should use previousNodes and/or Custom Parameters? This is my doubt, don't mind if I'm wrong.
> 
> Yes. In this PR, I change the detection logic to use previousNodes to check condition instead of use dependency result.
> 
> However, I don't think the success or failure of task nodes should be related to user-defined parameters.


The Condition's Custom Parameters is different from other task, it's has and/or relation with pre node in ui(it's also only has success  and failure), and when i run the task, these Custom Parameters will be used in dependencyList, this is why i think they should be calculate together.
<img width="579" alt="image" src="https://user-images.githubusercontent.com/37766284/168872602-cb2232b5-84a7-4c05-90fb-81b3daae6502.png">

**Comment by SbloodyS** [comment]
@huangchenguang123 This is the dependent task node. Not condition task node.

**Comment by huangchenguang123** [comment]
> @huangchenguang123 This is the dependent task node. Not condition task node.

This is condition task node. May be you can try?

**Comment by SbloodyS** [comment]
> > @huangchenguang123 This is the dependent task node. Not condition task node.
> 
> This is condition task node. May be you can try?

I take a deep look into UI. There are indeed some misleading description of UI. I'll fix it too. Thanks.

**Comment by huangchenguang123** [comment]
The ui that confuses me is one of the problems. Another problems is Custom Parameters' effect. If you only use previousNodes result, where does the custom parameter take effect? I think they will be skip in #10077 because of they be remove from runTask.And If custom parameter will effect, how does it relate to the previousNodes result?This is how task nodes differ from other nodes, because task node need know previousNodes result, and other task's previousNodes only decide when to run next node.

**Comment by SbloodyS** [comment]
> The ui that confuses me is one of the problems. Another problems is Custom Parameters' effect. If you only use previousNodes result, where does the custom parameter take effect? I think they will be skip in #10077 because of they be remove from runTask.And If custom parameter will effect, how does it relate to the previousNodes result?This is how task nodes differ from other nodes, because task node need know previousNodes result, and other task's previousNodes only decide when to run next node.

You can retry the condition task node after #10077 is merged.

**Comment by fhygh** [comment]
@SbloodyS  i tried in 3.0.0 beta version, which merged the code of [https://github.com/apache/dolphinscheduler/pull/10077](url), but condition task plugin is still not work fine.

**Comment by SbloodyS** [comment]
![](https://vip2.loli.io/2022/06/09/twRA1BJKPoqkYSZ.png)

I've tried condition tasks in the latest dev branch. It works fine. @fhygh

**Comment by fhygh** [comment]
@SbloodyS  oh, i see, need add pre task, thank you.
