### ISSUE TITLE
[Bug] [Api] After the task instance is forced to succeed, the downstream task instance is not triggered to execute.

### ISSUE THREAD

**Issue by huangchenguang123** [apache/dolphinscheduler#10043]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I force success a task instance that need fault tolerance, the downstream task instance is not triggered to execute.
Because org.apache.dolphinscheduler.api.controller.TaskInstanceController#forceTaskSuccess only modify table t_ds_task_instance, but in master, the task instance'state is 
`key: null type: TASK_STATE_CHANGE executeStatus: RUNNING_EXECUTION task instance id: 101 process instance id: 38 context: null`,
so org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread#stateEventHandler can't execute the next task.

### What you expected to happen

After force success, the next task will be execute.

### How to reproduce

1.create a workflow.
2.create a dependent process that never success.
3.create a process that depend step 2 process.
4.run workflow and force dependent process success.
5.you can see the next process never run.

### Anything else

I don't know this is a bug or a feature?But I think it's a common problem in data development.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You can manually restart the workflow instance using ```restart from failed node``` after force successed the task instance.

**Comment by huangchenguang123** [comment]
> You can manually restart the workflow instance using `restart from failed node` after force successed the task instance.
I want to skip this node, and execute the next node.if i restart the workflow, the node is always fail.
For example, if i depend 3 table, but one table is fail today(may be have data skew or have not enough resource to execute), so i have to skip the depend, i think this is a common quastion in daliy scheduler. Is this as expected in current version?

**Comment by huangchenguang123** [comment]
> You can manually restart the workflow instance using `restart from failed node` after force successed the task instance.

I want to skip this node, and execute the next node.if i restart the workflow, the node is always fail.
For example, if i depend 3 table, but one table is fail today(may be have data skew or have not enough resource to execute), so i have to skip the depend, i think this is a common quastion in daliy scheduler. Is this as expected in current version?

**Comment by SbloodyS** [comment]
![](https://vip2.loli.io/2022/05/16/HfK8nskXqoijLJA.png)

There is a function named ```Recovery Failed``` in workflow instance page which could skip the force suceess  task node and restart from the next task node.

**Comment by huangchenguang123** [comment]
> ![](https://camo.githubusercontent.com/cfe1574c880d38fd11af12082d24a758a9d879f1cbcee345197a4ee4ea632a9b/68747470733a2f2f766970322e6c6f6c692e696f2f323032322f30352f31362f48664b386e736b58716f696a4c4a412e706e67)
> 
> There is a function named `Recovery Failed` in workflow instance page which could skip the force suceess task node and restart from the next task node.

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/37766284/168560685-f5b3e17d-930c-43aa-8df8-9271684fa303.png">
The version is dev? I can't find the Recovery Failed?

**Comment by SbloodyS** [comment]
![](https://vip1.loli.io/2022/05/16/5M9PoR7efIcSJzp.png)

**Comment by huangchenguang123** [comment]
> ![](https://camo.githubusercontent.com/28a7c926458f123c06299acfdafca51d5e75ea887b00459548c2836e0c51089a/68747470733a2f2f766970312e6c6f6c692e696f2f323032322f30352f31362f354d39506f523765664963534a7a702e706e67)

In my picture,  the second workflow Instanceis is unusual, the workflow Instanceis always running, because executeStatus is RUNNING_EXECUTION and never finished, but Task Instance is forced success, and no active task is running. when the workflow Instance is running, i can't use Recovery Failed.This is reproducible.

**Comment by JensonZou** [comment]
I have the same problem, I think the downstream task should be triggered when I click the button for force success, if not, what's the point of force success.

**Comment by zhaolupingnick** [comment]
I have the same problem and hope to fix it as soon as possible.
