### ISSUE TITLE
[Bug] [Api] token expire when different timezone between server and database

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#10076]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Token expire when different timezone between server and database, and I found the sql use database timestamp.
```
<select id="queryUserByToken" resultType="org.apache.dolphinscheduler.dao.entity.User">
      select
      <include refid="baseSqlV2">
          <property name="alias" value="u"/>
      </include>
      from t_ds_user u ,t_ds_access_token t
      where u.id = t.user_id and token=#{token} and t.expire_time > NOW()
  </select>
```
It's better to use server timestamp.

### What you expected to happen

The token is normal when the expiration time has not expired

### How to reproduce

1. database use default timezone like CST
2. ds api server timezone use Asia/Shanghai
3. then create a token, just hour + 1 than current time.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by seedscoder** [comment]
Has anyone begun to deal with it? I want to try

**Comment by caishunfeng** [comment]
> Has anyone begun to deal with it? I want to try

@seedscoder OK, I had assigned to you.

**Comment by seedscoder** [comment]
> > Has anyone begun to deal with it? I want to try
> 
> @seedscoder OK, I had assigned to you.

Are others interested? I may not have time to do it recently @caishunfeng

**Comment by longtb976** [comment]
I want to try

**Comment by SbloodyS** [comment]
> I want to try

I've assigned it to you.
