### ISSUE TITLE
[Bug] [API] Create process definition with task group and task group priority cannot be save into db 

### ISSUE THREAD

**Issue by hstdream** [apache/dolphinscheduler#10079]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Create process definition with task group and task group priority cannot be save into db 

### What you expected to happen

Create process definition with task group and task group priority cannot be save into db 

### How to reproduce

1.create process definition,edit task group priority is 5
![企业微信截图_16527933147334](https://user-images.githubusercontent.com/33045461/168819651-94eec722-1b13-457d-92ef-18ebe6ae445d.png)

2.save process definition
3.Re edit process definition, task group priority is 0
![企业微信截图_16527933801074](https://user-images.githubusercontent.com/33045461/168819848-edab5431-753e-41d6-b091-5bbf2ca9e72c.png)

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
TGQ is the new feature in 3.0.0, so it's not the issue in 2.0.5.
