### ISSUE TITLE
[Bug] [API]When the created tenant name is too long, an error message will be prompted

### ISSUE THREAD

**Issue by hstdream** [apache/dolphinscheduler#10080]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When the created tenant name is too long, an error message will be prompted

### What you expected to happen

When the created tenant name is too long, an error message will be prompted

### How to reproduce

created tenant name is too long
![企业微信截图_16527944742120](https://user-images.githubusercontent.com/33045461/168823465-4031b706-d422-4db4-91a4-dec98e0721fb.png)

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Is this a 205 problem or a dev problem. @hstdream

**Comment by zhongjiajie** [comment]
> Is this a 205 problem or a dev problem. @hstdream

I think both of them have this issue

**Comment by zhongjiajie** [comment]
3.0.0-beta-1 is already fixed with #10081, so I add milestone to 2.0.6

**Comment by zhongjiajie** [comment]
remove stale

**Comment by brave-lee** [comment]
@zhongjiajie Can you cherry pick this pr to 2.0.7 ?

**Comment by zhongjiajie** [comment]
close by fb68147c25480d8ae75c1ea8de4edfd24ef79e6f
