### ISSUE TITLE
[Bug] [API] Resource username is null and udf function manager add a username

### ISSUE THREAD

**Issue by hstdream** [apache/dolphinscheduler#10082]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

File manage module username is null and udf function is not username

### What you expected to happen

You can look up resource's username 

### How to reproduce

![企业微信截图_16527967249352](https://user-images.githubusercontent.com/33045461/168832027-b2d439d8-cd9e-477b-995a-bfb8b02aba36.png)

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This issue has been fixed in #10073. I'll close this issue.
