### ISSUE TITLE
[Bug] [deploy on k8s]   SPRING_DATASOURCE_DRIVER_CLASS_NAME need add in  templates/_helpers.tpl

### ISSUE THREAD

**Issue by zwZjut** [apache/dolphinscheduler#10103]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[Bug] [deploy on k8s]   SPRING_DATASOURCE_DRIVER_CLASS_NAME need add in  templates/_helpers.tpl

### What you expected to happen

[Bug] [deploy on k8s]   SPRING_DATASOURCE_DRIVER_CLASS_NAME need add in  templates/_helpers.tpl

### How to reproduce

[Bug] [deploy on k8s]   SPRING_DATASOURCE_DRIVER_CLASS_NAME need add in  templates/_helpers.tpl

### Anything else

[Bug] [deploy on k8s]   SPRING_DATASOURCE_DRIVER_CLASS_NAME need add in  templates/_helpers.tpl

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zwZjut** [comment]
add in values.yaml;
postgresql:
  driver: org.postgresql.Driver

add  in templates/_helpers.tpl ; 

- name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
  {{- if .Values.postgresql.enabled }}
  value: {{ .Values.postgresql.driver }}
  {{- else }}
  value: {{ .Values.externalDatabase.driver }}
  {{- end }}

**Comment by qingwli** [comment]
Hi @zwZjut, I don't think we need to ```SPRING_DATASOURCE_DRIVER_CLASS_NAME```. 

Here is the reason.

You can see [this](https://github.com/apache/dolphinscheduler/blob/3.0.0-alpha-release/deploy/kubernetes/dolphinscheduler/templates/_helpers.tpl#L123) define the ```DATABASE```

And when you build the Docker image, will run the ```./bin/start.sh``` on Api || Matset || Worker || Alert-Server.

The  ```./bin/start.sh``` will source ```$DOLPHINSCHEDULER_HOME/conf/dolphinscheduler_env.sh```

And ```dolphinscheduler_env.sh``` will set the ```SPRING_PROFILES_ACTIVE``` , you can see the code [here](https://github.com/apache/dolphinscheduler/blob/3.0.0-alpha-release/script/env/dolphinscheduler_env.sh#L32)

Then you can see the ```driver-class-name``` will be chosen from the different data sources.  [postgresql](https://github.com/apache/dolphinscheduler/blob/3.0.0-alpha-release/dolphinscheduler-api/src/main/resources/application.yaml#L45) and [mysql](https://github.com/apache/dolphinscheduler/blob/3.0.0-alpha-release/dolphinscheduler-api/src/main/resources/application.yaml#L139)

**Comment by qingwli** [comment]
I have checked the yaml about Api || Matset || Worker || Alert-Server || tools, and they are two bugs.

- tools module changes the [this](https://github.com/apache/dolphinscheduler/commit/baf654cb47d60a753dd6372698ebb9230fca4859#diff-eed87c5c23a714652182ddde16029973958176002fea3b59fb8ec4d359a33893R28) but not changed the yaml.

When you change the data source to ```Mysql``` but will still use data source ```postgresql```

- Woker module yaml does not contains ```Mysql``` config

**Comment by qingwli** [comment]
And I have another question about running the Docker image.

```
$ docker run -d --name dolphinscheduler-tools \
    -e DATABASE="postgresql" \
    # Use "com.mysql.cj.jdbc.driver" if you use MySQL
    -e SPRING_DATASOURCE_DRIVER_CLASS_NAME="org.postgresql.Driver" \
    -e SPRING_DATASOURCE_URL="jdbc:postgresql://localhost:5432/<DATABASE>" \
    -e SPRING_DATASOURCE_USERNAME="<USER>" \
    -e SPRING_DATASOURCE_PASSWORD="<PASSWORD>" \
    --net host \
    apache/dolphinscheduler-tools:"${DOLPHINSCHEDULER_VERSION}" tools/bin/upgrade-schema.sh 
```

Do we need to config ```-e SPRING_DATASOURCE_DRIVER_CLASS_NAME="org.postgresql.Driver" \``` ?

The reason please look commented above

WDYT @SbloodyS @caishunfeng

**Comment by SbloodyS** [comment]
> And I have another question about running the Docker image.
> 
> ```
> $ docker run -d --name dolphinscheduler-tools \
>     -e DATABASE="postgresql" \
>     # Use "com.mysql.cj.jdbc.driver" if you use MySQL
>     -e SPRING_DATASOURCE_DRIVER_CLASS_NAME="org.postgresql.Driver" \
>     -e SPRING_DATASOURCE_URL="jdbc:postgresql://localhost:5432/<DATABASE>" \
>     -e SPRING_DATASOURCE_USERNAME="<USER>" \
>     -e SPRING_DATASOURCE_PASSWORD="<PASSWORD>" \
>     --net host \
>     apache/dolphinscheduler-tools:"${DOLPHINSCHEDULER_VERSION}" tools/bin/upgrade-schema.sh 
> ```
> 
> Do we need to config `-e SPRING_DATASOURCE_DRIVER_CLASS_NAME="org.postgresql.Driver" \` ?
> 
> The reason please look commented above
> 
> WDYT @SbloodyS @caishunfeng

Yes. It's needed.

**Comment by kezhenxu94** [comment]
> And I have another question about running the Docker image.
> 
> ```
> $ docker run -d --name dolphinscheduler-tools \
>     -e DATABASE="postgresql" \
>     # Use "com.mysql.cj.jdbc.driver" if you use MySQL
>     -e SPRING_DATASOURCE_DRIVER_CLASS_NAME="org.postgresql.Driver" \
>     -e SPRING_DATASOURCE_URL="jdbc:postgresql://localhost:5432/<DATABASE>" \
>     -e SPRING_DATASOURCE_USERNAME="<USER>" \
>     -e SPRING_DATASOURCE_PASSWORD="<PASSWORD>" \
>     --net host \
>     apache/dolphinscheduler-tools:"${DOLPHINSCHEDULER_VERSION}" tools/bin/upgrade-schema.sh 
> ```
> 
> Do we need to config `-e SPRING_DATASOURCE_DRIVER_CLASS_NAME="org.postgresql.Driver" \` ?

`SPRING_DATASOURCE_DRIVER_CLASS_NAME` shouldn't be specified, `DATABASE` is aimed at configuring the database related info, when users set `DATABASE=postgresql` the driver should be set automatically

**Comment by kezhenxu94** [comment]
@liqingwang please add a profile `postgresql` here and set correct driver in the yaml https://github.com/apache/dolphinscheduler/blob/e2fac213991c30f0a7460e3576fa3bbb5e6e6d42/dolphinscheduler-tools/src/main/resources/application.yaml#L39-L46


```yaml
 --- 
 spring: 
   config: 
     activate: 
       on-profile: postgresql 
   datasource: 
     driver-class-name: org.postgresql.Driver

**Comment by qingwli** [comment]
I agree.

If we don't need to specify the ```SPRING_DATASOURCE_DRIVER_CLASS_NAME```, then we don't need this field when you start at Docker mode or K8s mode?

So this [code](https://github.com/apache/dolphinscheduler/pull/10128/commits/38db6c9939cef62373326146feff149f4448d6c8#diff-380f881407a9a838ea3a04c76326ef0899eb023bd612ca52a2762beafb2bd2d9R129-R134) doesn't need?  @kezhenxu94

**Comment by kezhenxu94** [comment]
> I agree.
> 
> If we don't need to specify the `SPRING_DATASOURCE_DRIVER_CLASS_NAME`, then we don't need this field when you start at Docker mode or K8s mode?
> 
> So this [code](https://github.com/apache/dolphinscheduler/pull/10128/commits/38db6c9939cef62373326146feff149f4448d6c8#diff-380f881407a9a838ea3a04c76326ef0899eb023bd612ca52a2762beafb2bd2d9R129-R134) doesn't need? @kezhenxu94

Yes, we'd better keep the configurations minimal whenever they can be specified automatically, so users won't be overwhelming by so many configurations.

**Comment by qingwli** [comment]
And we can't delete ``` source "$DOLPHINSCHEDULER_HOME/conf/dolphinscheduler_env.sh"``` in docker mode, this sh will export SPRING field, am I correct?

**Comment by qingwli** [comment]
Is my understanding of the driver set automatically correct? https://github.com/apache/dolphinscheduler/issues/10103#issuecomment-1131238019

**Comment by kezhenxu94** [comment]
> Is my understanding of the driver set automatically correct? [#10103 (comment)](https://github.com/apache/dolphinscheduler/issues/10103#issuecomment-1131238019)

This is right

**Comment by kezhenxu94** [comment]
> And we can't delete `source "$DOLPHINSCHEDULER_HOME/conf/dolphinscheduler_env.sh"` in docker mode, this sh will export SPRING field, am I correct?

Hi @liqingwang , you don't need to delete `source "$DOLPHINSCHEDULER_HOME/conf/dolphinscheduler_env.sh"`, if you set any env var in Kubernetes, it will override `dolphinscheduler_env.sh`, did you find anything different?

**Comment by qingwli** [comment]
Yes, but only one difference, we don't define SPRING_DATASOURCE_DRIVER_CLASS_NAME in Kubernetes config file, but I define the database.

And ```source "$DOLPHINSCHEDULER_HOME/conf/dolphinscheduler_env.sh``` will ```export SPRING_PROFILES_ACTIVE=${DATABASE}``` , this will change the database driver, so we need this sh

**Comment by kezhenxu94** [comment]
> Yes, but only one difference, we don't define SPRING_DATASOURCE_DRIVER_CLASS_NAME in Kubernetes config file, but I define the database.
> 
> And `source "$DOLPHINSCHEDULER_HOME/conf/dolphinscheduler_env.sh` will `export SPRING_PROFILES_ACTIVE=${DATABASE}` , this will change the database driver, so we need this sh

right

**Comment by qingwli** [comment]
I will follow the previous design pattern to change the code.

So here is another question. Pls see this https://github.com/apache/dolphinscheduler/pull/10128#issuecomment-1131474052 , the active profile is to choose the database config, when we define the active profiles, and tools module can't change driver automatically. This is a bug. @SbloodyS

**Comment by SbloodyS** [comment]
> I will follow the previous design pattern to change the code.
> 
> So here is another question. Pls see this [#10128 (comment)](https://github.com/apache/dolphinscheduler/pull/10128#issuecomment-1131474052) , the active profile is to choose the database config, when we define the active profiles, and tools module can't change driver automatically. This is a bug. @SbloodyS

Yes.

**Comment by kezhenxu94** [comment]
> I will follow the previous design pattern to change the code.
> 
> So here is another question. Pls see this [#10128 (comment)](https://github.com/apache/dolphinscheduler/pull/10128#issuecomment-1131474052) , the active profile is to choose the database config, when we define the active profiles, and tools module can't change driver automatically. This is a bug. @SbloodyS

As I said here https://github.com/apache/dolphinscheduler/issues/10103#issuecomment-1132669903, can you update this in #10128 and see whether that satisfy your requirement?

**Comment by qingwli** [comment]
I'll have a try, thx @kezhenxu94

**Comment by qingwli** [comment]
I am not sure If I use ```java -Dspring.profiles.active=upgrade``` to define the profile java used, and then ```export SPRING_PROFILES_ACTIVE=mysql```, Spring will use both of them, or MySQL will overwritten upgrade

**Comment by kezhenxu94** [comment]
> I am not sure If I use ```java -Dspring.profiles.active=upgrade``` to define the profile java used, and then ```export SPRING_PROFILES_ACTIVE=mysql```, Spring will use both of them, or MySQL will overwritten upgrade

It will be overridden

**Comment by qingwli** [comment]
I used ```-Dspring.profiles.active=upgrade,${DATABASE}``` to use two profiles and the driver will be set automatically
