### ISSUE TITLE
[Bug] [Workflow Definition] Start multiple workflow tasks: A walkthrough wait occurs

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#10106]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/169050147-e82af240-1b2d-4672-bfec-1b5da509f697.png)
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/59044203/169050359-13aa0ac2-3455-489f-940d-9e96a67da28e.png">

### What you expected to happen

Tasks can be executed

### How to reproduce

Start multiple tasks and run with serial waiting

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
will be solve in 300-beta-2, it is not enough time to fix this in 300-beta-1
