### ISSUE TITLE
[Bug] [Api] Task Group Queue Query Error

### ISSUE THREAD

**Issue by qingwli** [apache/dolphinscheduler#10102]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Run DS dev and login and click task-group-queue module, and the query fails.

<img width="2378" alt="WeChat4005f5436461c4fabc2f4df9315d0817" src="https://user-images.githubusercontent.com/20885366/169011924-3b652d1d-21e5-431f-82d8-b55df7fc8662.png">

### What you expected to happen

Query success.

### How to reproduce

⬆️

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qingwli** [comment]
- I don't konw what's this, but not show normal
<img width="3420" alt="WeChat2d222a8009fc84a62f86a7ff78e92099" src="https://user-images.githubusercontent.com/20885366/169222722-ac32c99b-be27-4ed5-90e2-cbedf0309ba1.png">

- dolphinscheduler/task-group/query-list-by-group-id?pageSize=10&pageNo=1&taskInstanceName=&processInstanceName=
Request Method: GET 

Miss ```group id ``` params

<img width="2200" alt="WeChat0cec194b40f2f3618f12ca18cf53cbb5" src="https://user-images.githubusercontent.com/20885366/169222873-4a1314bf-b853-43a7-97b7-4e119d8b19b2.png">
<img width="1347" alt="WeChatc875a3fc10e5c2344b9e61945ea0b71f" src="https://user-images.githubusercontent.com/20885366/169222744-1a73e43b-dac0-4b6c-bc90-8fe528a5c3c8.png">

**Comment by zhongjiajie** [comment]
it is indeed has a bug here

**Comment by zhongjiajie** [comment]
It seems @devosend have frontend change for this issue, so I reopen it

**Comment by devosend** [comment]
I will fix it.

**Comment by woshiwuxiaofei** [comment]
this bug was fixed by #10237 and #10243? @zhongjiajie
