### ISSUE TITLE
[Bug] [doc] conditions.md'image cannot be previewed by markdown

### ISSUE THREAD

**Issue by huangchenguang123** [apache/dolphinscheduler#10126]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[Bug] [doc] conditions.md'image cannot be previewed by markdown

### What you expected to happen

fix it

### How to reproduce

none

### Anything else

none

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
duplicateh to #9426
