### ISSUE TITLE
[Bug] [dolphinscheduler-master] When the process execution type is serial wait, the program will report an error and cannot run

### ISSUE THREAD

**Issue by redamancydec** [apache/dolphinscheduler#10131]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When the process execution type is serial wait, the program will report an error and cannot run

### What you expected to happen

![串行等待](https://user-images.githubusercontent.com/87895252/169261240-3bee11d4-ef05-42e9-981a-d484301a3029.png)

![error](https://user-images.githubusercontent.com/87895252/169261334-08fd2e45-7ab6-49b1-b867-8587976dd052.png)

### How to reproduce

串行等待的执行任务流

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by redamancydec** [comment]
This is caused by missing pass parameters

**Comment by zhongjiajie** [comment]
@iamliangdi Hi, we will release 300-beta-1 in the next week, and we still have lots of work to do to release 300b1, so we plan to fix it it 300-beta-2

**Comment by redamancydec** [comment]
> @iamliangdi Hi, we will release 300-beta-1 in the next week, and we still have lots of work to do to release 300b1, so we plan to fix it it 300-beta-2

Yes, that's right, but I've seen on the dev branch that the bug has been repaired by others. I don't need to submit PR again.
Or should I not request merging branches to dev?

**Comment by zhongjiajie** [comment]
> > @iamliangdi Hi, we will release 300-beta-1 in the next week, and we still have lots of work to do to release 300b1, so we plan to fix it it 300-beta-2
> 
> Yes, that's right, but I've seen on the dev branch that the bug has been repaired by others. I don't need to submit PR again. Or should I not request merging branches to dev?

yeah, if this bug already fix by others, you should not submit PR for any remote branch

**Comment by zhongjiajie** [comment]
remove stale

**Comment by zhongjiajie** [comment]
@caishunfeng

**Comment by qiangliliu** [comment]
串行等待的任务全部在等待，没有正在执行的任务。怎么处理？
![串行等待](https://github.com/apache/dolphinscheduler/assets/17610987/4bef2ac3-3ca8-4a87-85f5-d85ae7cd3a75)
