### ISSUE TITLE
[Bug] [Workflow Definition]  The execution of the UDF function corresponding to hive failed

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#10137]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.create hive worker flow task
2.run hive task
![image](https://user-images.githubusercontent.com/59044203/169315101-b807e9b1-9372-4edf-aeb0-f11a82ef9347.png)

### What you expected to happen

hive task ran successfully.

### How to reproduce

1.create hive worker flow task
2.run hive task

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
I think it is because your host starting server can not connect to your HDFS resource center

**Comment by zhongjiajie** [comment]
> I think it is because your host starting server can not connect to your HDFS resource center

close it because
