### ISSUE TITLE
[Bug] [workflows] Data_quality workflows in Chinese mode are not translated into Chinese

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#10138]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/169317270-20184f0d-44c4-4275-b7b7-268a9df9b574.png)

### What you expected to happen

In Chinese mode, it should be displayed as a Chinese

### How to reproduce

None.

### Anything else

None.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it
