### ISSUE TITLE
[Bug] [Workflow Definition] In workflow scheduling management, edit: Saturday, Sunday there will be a front-end error: Nan

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#10139]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/169318145-5d47a2e1-3d69-4a9b-b490-6fb2cad8bfe4.png)

### What you expected to happen

Front-end error: Nan does not appear

### How to reproduce

1.Go to cron mange
![image](https://user-images.githubusercontent.com/59044203/169318727-57657cbb-52f7-4287-b5c7-aacfca4222b4.png)

2.edit 
![image](https://user-images.githubusercontent.com/59044203/169318889-a2ad17f9-190c-4eea-a7b4-82552c872947.png)

3.Specific day of the week(multiple)
![image](https://user-images.githubusercontent.com/59044203/169319313-0a306efc-efd0-4ac1-beb2-43ea04de8225.png)

4.comfirm
![image](https://user-images.githubusercontent.com/59044203/169319507-445b8300-4345-4908-b304-ae571c49a072.png)

5.edit again
![image](https://user-images.githubusercontent.com/59044203/169319665-7c8d8384-6485-41f8-b31d-664f2c173d5c.png)

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
