### ISSUE TITLE
[Bug] [Task group option] On the task group configuration page, specific prompts should be given if the capacity input is not numeric

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#10148]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/169325046-bf3de142-2ca6-4f8a-af0a-2f0d207f1d22.png)

### What you expected to happen

specific prompts should be given if the capacity input is not numeric

### How to reproduce

1. Enter special characters , such as: -10.1a 

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it

**Comment by zhongjiajie** [comment]
It seems that the backend code already have `groupSize` verify. cc @songjianet
