### ISSUE TITLE
[Bug] [Translation] Translation issue: The failure policy under timing management is not translated into Chinese

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#10140]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/169320690-05b35898-bb14-4c4f-abf0-512d4852b9bd.png)

### What you expected to happen

None.

### How to reproduce

None.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it
