### ISSUE TITLE
[Bug] [Module Name] Some folder naming methods under resource management will have a front-end exception uncaught(in promise) Error, for example: f1/f2/f3

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#10147]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/169324542-a4833a79-b90c-4247-be46-fb83f59ad13c.png)

### What you expected to happen

The front end does not report errors

### How to reproduce

1. Create a special folder, such sa: f1/f2/f3

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
already fix in #10094
