### ISSUE TITLE
[Bug] [Workflow Instance] There is a problem with the host filter condition on the workflow instance page, for example, the condition fails when you enter 1

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#10145]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/169323696-8d4f4131-fa43-41c4-8c1c-0cab6eeb6ee6.png)
![image](https://user-images.githubusercontent.com/59044203/169323790-1f994332-e080-4b63-85fb-ae02d5e859b5.png)

### What you expected to happen

1. Enter 1 here in the host input box, Displays empty data

### How to reproduce

None.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
I find out it works correctly, it will use fuzzy matching when you enter any text in `host`

**Comment by zhongjiajie** [comment]
> 

close it because of this
