### ISSUE TITLE
[Bug] [Workflow Definition] There is a problem with the workflow tree structure function, and the actual tree view is inconsistent with the preview diagram

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#10143]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/169322423-f09cb2fc-e3bd-41fb-9324-7d529cc76360.png)
![image](https://user-images.githubusercontent.com/59044203/169322515-154a36c1-e8e3-42cb-b17f-e781bcddba94.png)

### What you expected to happen

Demonstrate a complete workflow.

### How to reproduce

None.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it

**Comment by zhongjiajie** [comment]
It is a bug here, seem our tree view have the max depth
![bug-workflow-treeview](https://user-images.githubusercontent.com/15820530/169971681-a48b2a22-ea63-4fa7-91a2-8d454ce14447.gif)
