### ISSUE TITLE
[Bug] [Workflow Definition] The network layout of the workflow is unusable, and the front end reports an error: h is not function, and the checked is: Full workflow

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#10144]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/169323045-3178a969-dcef-422b-b44f-5b0a98af0ddc.png)

### What you expected to happen

The network layout works normally

### How to reproduce

1.Go to the workflow network layout
2.Enter a row 1, Enter the column 1
3.Click OK

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it

**Comment by caishunfeng** [comment]
Hi @welsh-wen Please add module name for title, thanks.

**Comment by songjianet** [comment]
I have not reproduced this problem locally. @welsh-wen

**Comment by zhongjiajie** [comment]
@songjianet  It is seem it still exists in 3.0.0-beta-prepare branch
![bug-workflow-format](https://user-images.githubusercontent.com/15820530/169968249-53f5dfc0-3038-400d-98a5-ce57f8043ac5.gif)

**Comment by songjianet** [comment]
> 
I can't reproduce it here, the dev branch.

**Comment by zhongjiajie** [comment]
> > 
> 
> I can't reproduce it here, the dev branch.

Will check in dev branch later when in finish the `3.0.0-beta-1` check today

**Comment by zhongjiajie** [comment]
we change milestone to `3.0.0-bate-2`

**Comment by zhongjiajie** [comment]
remove stale

**Comment by caishunfeng** [comment]
![image](https://user-images.githubusercontent.com/11962619/179889737-ca96cc58-dfbe-45a2-a1f4-9fdc43e8a47d.png)
I check in dev and it's error.  PTAL @songjianet

**Comment by zhongjiajie** [comment]
It is seem is a certain bug here @songjianet
