### ISSUE TITLE
[Improvement] [Project] Enviroment and waring gorup should be change when saving workflow

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#10142]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/169321684-84f544d6-7ed9-4e34-bb36-63b56ae91de8.png)
![image](https://user-images.githubusercontent.com/59044203/169321814-b03b879c-3e8b-4bf8-97b3-b0c03463a6b5.png)

### What you expected to happen

Configure retention

### How to reproduce

None.

### Anything else

None.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.

**Comment by songjianet** [comment]
This problem requires the assistance of the back-end partners. @zhongjiajie @caishunfeng 
![image](https://user-images.githubusercontent.com/19239641/170061334-3a5b59b7-1b93-40b7-816d-fafcdbbee9bf.png)
![image](https://user-images.githubusercontent.com/19239641/170061633-84d8e0ef-4f1f-4f13-818f-ab55cb5dd4c3.png)

**Comment by zhongjiajie** [comment]
will take a look today

**Comment by zhongjiajie** [comment]
It is expected behavior, just like temporarily overwriting the parameter with use in. But we should and `env` and `wariming group` when we save our workflow, so I change it from bug into improve here

**Comment by zhongjiajie** [comment]
![f-workflow-env-warm](https://user-images.githubusercontent.com/15820530/170197657-5dcda0b8-f2a4-423a-bc4f-4f14d5bff303.gif)

**Comment by zhongjiajie** [comment]
remove stale
