### ISSUE TITLE
[Bug] [Module Name] does not support copied task type [SWITCH]

### ISSUE THREAD

**Issue by hanfengcan** [apache/dolphinscheduler#10156]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

如图
![7678361188267d20c0ff2cadb45b06e](https://user-images.githubusercontent.com/4559753/169444840-71e8eb9d-ccd4-48f0-a1ee-db9155a73e7b.png)

### What you expected to happen

可以复制工作流

### How to reproduce

增加一个 switch 到工作流。另外， shell节点也不支持复制

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
Virtual nodes do not support replication, otherwise tasks will be repeated

**Comment by hanfengcan** [comment]
which are Virtual nodes, except switch and shell @JinyLeeChina

**Comment by dawsongzhao** [comment]
Is this issue fixed？
