### ISSUE TITLE
[Feature][HealthCheck] Modules like api,master,worker,alert etc , need add customer defined health check logic instead of default check

### ISSUE THREAD

**Issue by zwZjut** [apache/dolphinscheduler#10157]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

[Feature][health check] modules like api,master,worker,alert etc , need add customer defined health check logic instead of default check

for example : 

now api-server use curl -s http://localhost:12345/dolphinscheduler/actuator/health/liveness  to check health, and it shows 
 UP when process started, it is always healthy while it is not healthy  actually

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zwZjut** [comment]
issue like this: https://github.com/apache/dolphinscheduler/issues/10053   deploy api on k8s and quickly login , 404 found forever

**Comment by stalary** [comment]
If no one is working on it right now, I'm happy to give it a try.

**Comment by davidzollo** [comment]
good suggestion, and has assigned to you @stalary
