### ISSUE TITLE
[Improvement][task sql] Improve creating function query

### ISSUE THREAD

**Issue by zhaohehuhu** [apache/dolphinscheduler#10168]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

enhance creating temp function query

### Use case

Current creating function query fail to handle all cases. For example,  Kyuubi was taken as a datasource  in DS,  it's more likely to get a problem when setting the share level of Kyuubi engine to user.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Is this optimized based on version 3.x or optimized based on version 2.x. @luoyedeyi

**Comment by zhaohehuhu** [comment]
Both
