### ISSUE TITLE
Uncaught ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by bobofueeeee** [apache/dolphinscheduler#10164]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![Uploading befaf8c77821eb4dcc3721db6ece3b0.jpg…]()

### What you expected to happen

![Uploading befaf8c77821eb4dcc3721db6ece3b0.jpg…]()

### How to reproduce

![Uploading befaf8c77821eb4dcc3721db6ece3b0.jpg…]()

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bobofueeeee** [comment]
q

**Comment by songjianet** [comment]
Please add pictures again. @bobofueeeee

**Comment by songjianet** [comment]
Thank you for your feedback. I'll close this question with an unclear description, and you can resubmit a detailed description later. @bobofueeeee
