### ISSUE TITLE
[Bug] [UI] DataQuality icon in workflow is the same as SeaTunnel icon

### ISSUE THREAD

**Issue by rockfang** [apache/dolphinscheduler#10171]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/16065427/169496374-3ff937fd-5c92-429c-87c1-c7f42affe4cb.png)

### What you expected to happen

Data_Quality icon is same to SeaTunnel icon. hope to replace `data_quality.png`  and `data_quality_hover.png`

### How to reproduce

come in Workflow Definition page

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.
