### ISSUE TITLE
[Feature][API] Call the api to execute the workflow and return the workflow instance

### ISSUE THREAD

**Issue by headhard** [apache/dolphinscheduler#10180]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

**start-process-instance api only returns success without returning an instance ID，Unable to monitor task status**
**执行工作流只能返回成功运行而没有返回工作流实例ID无法监控运行状态**

### Use case

**Hope to call the api to execute the workflow and return the workflow instance ID**

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ahahaooo** [comment]
i also meet to this question,when i execute a workflow by api,then return data is null,i cannot get the id to monitor the status of workflow instance. if can return the record id of processDefinition,its also ok.

**Comment by Ishani-Gupta** [comment]
@SbloodyS  can you point me to the fix for above?

**Comment by SbloodyS** [comment]
> @SbloodyS can you point me to the fix for above?

You can get the execution result by polling the workflow instance list api for now. We have reconstructed and implemented this logic in the `dev` branch. And it will be released in the version 3.3.0.
