### ISSUE TITLE
[Bug] [Workflow/Workflow Definition] After deleting messages in batches, the error message is repeated

### ISSUE THREAD

**Issue by SnowMoon-Dev** [apache/dolphinscheduler#10199]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After deleting messages in batches, the error message is repeated

### What you expected to happen

remove duplicate prompts

### How to reproduce

1. Multiple users share the same project
2. Create one workflow per user
3. A user deletes a workflow created by another user

### Anything else

![Kapture 2022-05-23 at 16 22 52](https://user-images.githubusercontent.com/42627702/169778518-414e3460-3916-4743-9dcc-45ff7b10cb7e.gif)

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
It seems that the error tips was from backend.

**Comment by SnowMoon-Dev** [comment]
> 

yes，it is backend bug
