### ISSUE TITLE
[Feature][TaskLog] Log viewing is inconvenient

### ISSUE THREAD

**Issue by retime123** [apache/dolphinscheduler#10191]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

查看日志不方便：希望是点开日志直接显示最新的并且滑柱是在下面，鼠标向下滑动在继续拉取最新的，向上滑动到没有数据在拉取之前的部分日志
（View the log is not convenient: I want to open the log directly to display the latest and the slider is below, slide the mouse down to continue to pull the latest, slide up to the part of the log without data before pulling ）

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by retime123** [comment]
It is expected to be updated in 2.0.6

**Comment by retime123** [comment]
hope update in version 2.0.6

**Comment by songjianet** [comment]
> hope update in version 2.0.6

There will be no functional changes for the 2.x version. I'm tentatively slated to release it as version 3.1.0-alpha.

**Comment by songjianet** [comment]
This problem needs to be confirmed whether it is a front-end implementation or a back-end implementation. The back-end implementation may need to check back, and the front-end implementation may cause the problem that the data requested for multiple times is not displayed, resulting in a waste of resources. @caishunfeng @zhongjiajie

**Comment by retime123** [comment]
@songjianet   the 2.x version  new features are not added? or Only bug fixes?

**Comment by SbloodyS** [comment]
> @songjianet the 2.x version new features are not added? or Only bug fixes?

Only bug fixed will be added in 2.0.X version.
