### ISSUE TITLE
[Bug] [Worker server] I started two worker-server，but The page shows one

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#10204]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I started two worker-server，but The page shows one

<img width="1735" alt="image" src="https://user-images.githubusercontent.com/76080484/169802044-f06c7477-95f7-41e2-b127-de68cbdbe54d.png">

<img width="1893" alt="image" src="https://user-images.githubusercontent.com/76080484/169802207-82cb4ca0-d058-4a21-84ed-538b82b2685b.png">

![image](https://user-images.githubusercontent.com/19239641/169803517-47b5e9d3-a238-46b1-b56c-5eb9b028acc8.png)

### What you expected to happen

show all services

### How to reproduce

I started two worker-server，but The page shows one

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
I think you just simply copy from the original one, in you start the same server in one single host, you should change the server port and delete the pid that exists
