### ISSUE TITLE
[Bug] [Workflow Instance] A normally started worker service should not show fault tolerance

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#10205]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

A normally started worker service should not show fault tolerance

<img width="1903" alt="image" src="https://user-images.githubusercontent.com/76080484/169803134-bcdcc722-1e01-4134-a8a9-362a57fa496b.png">

<img width="1909" alt="image" src="https://user-images.githubusercontent.com/76080484/169803570-2d0e039d-0b56-4c43-a8bd-f189b4fac426.png">

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/76080484/169803757-2835227e-fba2-4deb-818d-9830e5eb61f7.png">

### What you expected to happen

Start two sets of master and worker services, run the workflow, and stop one of them

### How to reproduce

The fault tolerance test is in progress, the worker service I stopped is port 1254

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
@XuXuClassMate can you provide your dag context into `How to reproduce`?

**Comment by XuXuClassMate** [comment]
I first started two worker service ports on 1234 and 1254, and forcibly stopped the worker service on port 1254. The component assigned to port 1234 showed fault tolerance.

**Comment by zhongjiajie** [comment]
do you have time to check this issue @caishunfeng ?
