### ISSUE TITLE
[Bug] [Create Alarm Instance] When you enter the alarm instance management, the "Alarm Instance Component is Empty" error appears on the front end, and clicking "Create Alarm Instance" is always loading

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#10207]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/169825352-5acae9f0-00cc-4381-8874-bf7af5ab6bb3.png)
![image](https://user-images.githubusercontent.com/59044203/169825438-67e2587f-d4bc-4e7b-b973-ac022815438a.png)

### What you expected to happen

You can create an alarm instance

### How to reproduce

None.

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SnowMoon-Dev** [comment]
@songjianet https://github.com/apache/dolphinscheduler/pull/9924 This PR can solve this bug，This bug is caused by the fact that the alert component is not started, the plugin is not registered, and the front-end does not handle the interface exception.
