### ISSUE TITLE
[Feature][Registry] Support registry nacos

### ISSUE THREAD

**Issue by stalary** [apache/dolphinscheduler#10212]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Support registry nacos as a new registry plugin.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by complone** [comment]
t looks very interesting. I am the tutor of this spring-cloud-alibaba ASoc. I have a certain understanding of nacos and want to try to develop this plugin.

**Comment by kaori-seasons** [comment]
After preliminary research,, I found that JGit, as a Git client, has a heavy logic and it is not very friendly to manually build a repository locally based on Git commands, so I found another way to upload and download files based on  [REST-API](https:// github.com/GerritCodeReview/gerrit)

doc: https://gerrit-review.googlesource.com/Documentation/rest-api-projects.html

**Comment by ruanwenjun** [comment]
Is there any progress update?

**Comment by stalary** [comment]
> Is there any progress update?

Sorry, I have too much work to do recently. I haven't started yet.

**Comment by ruanwenjun** [comment]
> > Is there any progress update?
> 
> Sorry, I have too much work to do recently. I haven't started yet.

OK, don't worry.

**Comment by stalary** [comment]
I will start working on this, and I will refer to zooKeeper-plugin for implementation.

**Comment by caishunfeng** [comment]
I reopen it and put into 3.2.0 milestone.

**Comment by rwrwd7** [comment]
mark

**Comment by RickyLoveFreedom** [comment]
mark

**Comment by wangwenyao** [comment]
How is the progress

**Comment by viosay** [comment]
How is the progress to date ?

**Comment by zhangxn8** [comment]
Has this problem been solved?

**Comment by ruanwenjun** [comment]
> Has this problem been solved?

There is no update on this issue.

**Comment by fw19940314** [comment]
How is it going?
