### ISSUE TITLE
[Feature][doc] Add how to use resource in shell task

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#10222]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/task/shell.html we just tell the user how to use variable in shell task, we should also add some examples about how to use resource file in shell task

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by QuakeWang** [comment]
I think this issue should be about the use of the resource center. And there are already cases of using resource files in shell tasks at [file-manage](https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/resource/file-manage.html).

**Comment by zhongjiajie** [comment]
> I think this issue should be about the use of the resource center. And there are already cases of using resource files in shell tasks at [file-manage](https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/resource/file-manage.html).

In this case, I think we should add some hyperlink from shell task to resource center to tell users how to use resource in shell task, WDYT?

**Comment by QuakeWang** [comment]
> > I think this issue should be about the use of the resource center. And there are already cases of using resource files in shell tasks at [file-manage](https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/resource/file-manage.html).
> 
> In this case, I think we should add some hyperlink from shell task to resource center to tell users how to use resource in shell task, WDYT?

Great! I will do this task. Please assign it to me : )

**Comment by zhongjiajie** [comment]
Looking forward your contribution
