### ISSUE TITLE
[Feature][doc] Add an example about how to use pre_sql post_sql in SQL task

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#10233]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/task/sql.html 

we should add an example about how to use presql and postsql in sql task, some users will use some select sql in pre/post sql and cause error

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
If no one is working on it right now, I'm happy to give it a try.

**Comment by zhongjiajie** [comment]
> If no one is working on it right now, I'm happy to give it a try.

Sound great, I assigned to you and looking forward your contribution

**Comment by stalary** [comment]
I forgot the issue, now I will deal with it.
