### ISSUE TITLE
[Feature][Discard old instances] can set to delete unwanted instances and logs

### ISSUE THREAD

**Issue by retime123** [apache/dolphinscheduler#10254]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description
![image](https://user-images.githubusercontent.com/29012717/170464458-9000827f-9a43-43fc-8eba-dc02b9d9909b.png)

![image](https://user-images.githubusercontent.com/29012717/170449852-cfc7a949-4ecd-4b9f-a6ce-e2f90271d078.png)
希望能添加自动删除实例以及日志（展开有以下选项，不展开无此功能）：
  1.可以选择“保留最大个数”和“天数”（默认“保留最大个数”）；
  2.可以选择“所有实例”和“保留失败”（默认“所有实例”，“保留失败”不作为依据）；
  3.数量。

前端我写好了，后端没有时间研究，希望你们能添加这个功能。

You want to be able to add auto-delete instances and logs (open with the following options, open without this feature) :  
1. You can select Maximum Number of days and Maximum number of reserved days (the default value is Maximum number of reserved days).  
2. You can select All Instances and Failed To Retain. The default value is All Instances and Failed to retain is not used as a basis.    
3. Number.  
I have written the front end, there is no time to study the back end, I hope you can add this function.  

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
We do not recommand delete user's data. It's a dangerous operation. For more information you can see the discussion in #8408.

**Comment by retime123** [comment]
或者代码层面应该在哪个模块添加此功能？  
Or which module should you add this functionality to at the code level?

**Comment by retime123** [comment]
> We do not recommand delete user's data. It's a dangerous operation. For more information you can see the discussion in #8408.

For my own use, If so, under which module should it be changed?

**Comment by SbloodyS** [comment]
> > We do not recommand delete user's data. It's a dangerous operation. For more information you can see the discussion in #8408.
> 
> For my own use, If so, under which module should it be changed?

It depends on what you want to achieve.

**Comment by retime123** [comment]
工作流实例：实例运行的时候，判断有没有相应的参数来删除不需要的实例以及日志
Workflow instance: When the instance is running, determine whether there are parameters to remove unwanted instances and logs

**Comment by retime123** [comment]
> 工作流实例：实例运行的时候，判断有没有相应的参数来删除不需要的实例以及日志
> Workflow instance: When the instance is running, determine whether there are parameters to remove unwanted instances and logs

工作流实例：实例运行的时候，判断有没有相应的参数来删除不需要的实例以及日志

**Comment by retime123** [comment]
> 工作流实例：实例运行的时候，判断有没有相应的参数来删除不需要的实例以及日志
> Workflow instance: When the instance is running, determine whether there are parameters to remove unwanted instances and logs

工作流实例：实例运行的时候，判断有没有相应的参数来删除不需要的实例以及日志

**Comment by retime123** [comment]
> > > We do not recommand delete user's data. It's a dangerous operation. For more information you can see the discussion in #8408.
> > 
> > 
> > For my own use, If so, under which module should it be changed?
> 
> It depends on what you want to achieve.

工作流实例：实例运行的时候，判断有没有相应的参数来删除不需要的实例以及日志
Workflow instance: When the instance is running, determine whether there are parameters to remove unwanted instances and logs

**Comment by SbloodyS** [comment]
How to judge unnecessary instances and logs?

**Comment by retime123** [comment]
比如：比较旧的运行成功的实例，我就可以认为不需要。
总得保留最新的几个实例，作为其他使用。
For example, older successful instances can be considered unnecessary.  
Always keep the latest few instances for other use.

**Comment by retime123** [comment]
你们认为是a dangerous operation，那我自己改自己使用吧
然后就是想知道在哪个模块哪个文件下可以操作此功能？
You think it is a dangerous operation, then I will use it myself  
Then you want to know which module and which file can operate this function?

**Comment by retime123** [comment]
对了，还有一点，我觉得删不删除，是通过用户决定的，这个不是必填项
By the way, there is another point, I think whether to delete or not is decided by the user, this is not mandatory

**Comment by SbloodyS** [comment]
Please describe in English, which can make more developers understand.

**Comment by retime123** [comment]
> Please describe in English, which can make more developers understand.

好，我用中英文对照
Ok, I'll use both Chinese and English

**Comment by SbloodyS** [comment]
Here is an example that may be useful to you:

1. Query the unnecessary workflow instances id from the database.
2. Call ```deleteProcessInstanceById``` api by yourself.

**Comment by retime123** [comment]
> Here is an example that may be useful to you:
> 
> 1. Query the unnecessary workflow instances id from the database.
> 2. Call `deleteProcessInstanceById` api by yourself.

那我要在哪个地方触发这个api？
So where do I trigger this API?

**Comment by SbloodyS** [comment]
> > Here is an example that may be useful to you:
> > 
> > 1. Query the unnecessary workflow instances id from the database.
> > 2. Call `deleteProcessInstanceById` api by yourself.
> 
> 那我要在哪个地方触发这个api？ So where do I trigger this API?

Through the code you developed.

**Comment by retime123** [comment]
我的意思是源码里面，每个实例的启动都走哪个方法？
是这个吗？版本2.0.5
I mean in the source code, which method is used to start each instance?  
Is that it?  Version at 2.0.5
![image](https://user-images.githubusercontent.com/29012717/170477950-f966ec36-e21d-44db-9b19-80266e99faa8.png)

**Comment by jmorcar** [comment]
What is the state of this suggestion ? 

Or, any alternative to determine how to remove old task instances ? in webui Form in workflow/task creation could be good , but as well with a global parameter in config could be an alternative.
