### ISSUE TITLE
[Feature][Doc] Instructions on LDAP authentication setup needed

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#10250]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* It seems DS has supported `LDAP` authentication for a long time, but there are no instructions on how to set up LDAP authentication for DS.
* related: #3743

### Use case

* Already described above.

### Related issues

* Already described above.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
This issue has been fixed.

**Comment by zui01** [comment]
where can i find the doc?thank

**Comment by EricGao888** [comment]
> where can i find the doc?thank

https://dolphinscheduler.apache.org/en-us/docs/3.1.3/architecture/configuration
