### ISSUE TITLE
[Bug] [LDAP] DS LDAP authenticator needs improvements

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#10274]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

* Currently, DS LDAP authenticator is not very easy to use. In some situations, it may not work.

### What you expected to happen

* First, current DS LDAP authenticator needs LDAP `administrator credentials`, and then searches the accurate DN of the login user. This is unnecessary and inconvenient for DS users, sometimes making users confused. Users should provide accurate DN and DS LDAP authenticator will verify the `LDAP user` directly. https://github.com/apache/dolphinscheduler/blob/62b85b9cb3110290519966743c40d0f40ce6af3b/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/impl/ldap/LdapService.java#L45-L64
*  DS LDAP authenticator relies on `LDAP email attribute` to verify `LDAP user`. But sometimes there is no such attribute on LDAP side. https://github.com/apache/dolphinscheduler/blob/62b85b9cb3110290519966743c40d0f40ce6af3b/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/impl/ldap/LdapService.java#L92-L112
* `InitialLDAPContext` is not closed and will take unnecessary resources.

### How to reproduce

* Already described above.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
Here is an example for two kinds of LDAP configurations which `Apache Airflow` is using: 
![image](https://user-images.githubusercontent.com/34905992/170866316-998fa4b5-4a5f-4f59-b978-a6c2e6cd202b.png)
Click [here](https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-ldap) for more information.

**Comment by EricGao888** [comment]
For the approach which does not need `administrator` password and username, you could try this command to test the authentication `ldapsearch -v -h ip:port -D uid=xxx,ou=xxxx,o=xxx -w login_user_passoword -x -b ou=xxx,o=xxx` @liqingwang

**Comment by EricGao888** [comment]
No stale, I'm coming for ya!🤣

**Comment by huage1994** [comment]
Hi @EricGao888 , I'd like to submit a PR.

**Comment by EricGao888** [comment]
> Hi @EricGao888 , I'd like to submit a PR.

@huage1994 Sure, thx for helping out~
