### ISSUE TITLE
cannot find name for group ID

### ISSUE THREAD

**Issue by harkowl** [apache/dolphinscheduler#10271]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After executing the workflow, the status of the task instance is failed
How to solve ?  
Thanks

[INFO] 2022-05-27 17:38:37.688 org.apache.dolphinscheduler.server.worker.plugin.TaskPluginManager:[73] - Registering task plugin: PYTHON
[INFO] 2022-05-27 17:38:37.690 org.apache.dolphinscheduler.server.worker.plugin.TaskPluginManager:[81] - Registered task plugin: PYTHON
[INFO] 2022-05-27 17:54:51.015 org.apache.dolphinscheduler.server.worker.processor.TaskExecuteProcessor:[119] - received command : TaskExecuteRequestCommand{taskExecutionContext='{"taskInstanceId":1,"taskName":"aaa","firstSubmitTime":null,"startTime":null,"taskType":"SQL","host":null,"executePath":null,"logPath":null,"taskJson":null,"processId":0,"processDefineCode":5659504793696,"processDefineVersion":1,"appIds":null,"processInstanceId":1,"scheduleTime":null,"globalParams":null,"executorId":1,"cmdTypeIfComplement":0,"tenantCode":"user_01","queue":"default","projectCode":5659478977376,"taskParams":"{\"type\":\"MYSQL\",\"datasource\":1,\"sql\":\"select 'a' as test\",\"udfs\":\"\",\"sqlType\":\"0\",\"sendEmail\":false,\"displayRows\":10,\"title\":\"\",\"groupId\":null,\"localParams\":[{\"prop\":\"test\",\"direct\":\"OUT\",\"type\":\"VARCHAR\",\"value\":\"\"}],\"connParams\":\"\",\"preStatements\":[],\"postStatements\":[],\"dependence\":{},\"conditionResult\":{\"successNode\":[],\"failedNode\":[]},\"waitStartTimeout\":{},\"switchResult\":{}}","envFile":null,"environmentConfig":null,"definedParams":null,"taskAppId":null,"taskTimeoutStrategy":null,"taskTimeout":2147483647,"workerGroup":"default","delayTime":0,"currentExecutionStatus":null,"resources":{},"sqlTaskExecutionContext":{"warningGroupId":0,"connectionParams":"{\"user\":\"hlht_country_platform_rw\",\"password\":\"TliNYGvA83KW\",\"address\":\"jdbc:mysql://pc-2ze09zi74x95skc07.rwlb.rds.aliyuncs.com:3306\",\"database\":\"hlht_country_platform\",\"jdbcUrl\":\"jdbc:mysql://pc-2ze09zi74x95skc07.rwlb.rds.aliyuncs.com:3306/hlht_country_platform\",\"driverClassName\":\"com.mysql.cj.jdbc.Driver\",\"validationQuery\":\"select 1\"}","udfFuncTenantCodeMap":null,"defaultFS":"file:///"},"dataxTaskExecutionContext":{"dataSourceId":0,"sourcetype":0,"sourceConnectionParams":null,"dataTargetId":0,"targetType":0,"targetConnectionParams":null},"dependenceTaskExecutionContext":null,"sqoopTaskExecutionContext":{"dataSourceId":0,"sourcetype":0,"sourceConnectionParams":null,"dataTargetId":0,"targetType":0,"targetConnectionParams":null},"varPool":null,"dryRun":0,"paramsMap":null,"procedureTaskExecutionContext":{"connectionParams":null}}'}
[INFO] 2022-05-27 17:54:51.094 org.apache.dolphinscheduler.server.worker.processor.TaskExecuteProcessor:[142] - task instance local execute path : /tmp/dolphinscheduler/exec/process/5659478977376/5659504793696_1/1/1
[INFO] 2022-05-27 17:54:51.099 org.apache.dolphinscheduler.common.utils.FileUtils:[121] - create dir success /tmp/dolphinscheduler/exec/process/5659478977376/5659504793696_1/1/1
[ERROR] 2022-05-27 17:54:51.116 org.apache.dolphinscheduler.common.utils.OSUtils:[269] - groups: cannot find name for group ID 1337

org.apache.dolphinscheduler.common.shell.AbstractShell$ExitCodeException: groups: cannot find name for group ID 1337

        at org.apache.dolphinscheduler.common.shell.AbstractShell.runCommand(AbstractShell.java:209)
        at org.apache.dolphinscheduler.common.shell.AbstractShell.run(AbstractShell.java:124)
        at org.apache.dolphinscheduler.common.shell.ShellExecutor.execute(ShellExecutor.java:127)
        at org.apache.dolphinscheduler.common.shell.ShellExecutor.execCommand(ShellExecutor.java:104)
        at org.apache.dolphinscheduler.common.shell.ShellExecutor.execCommand(ShellExecutor.java:87)
        at org.apache.dolphinscheduler.common.utils.OSUtils.exeShell(OSUtils.java:393)
        at org.apache.dolphinscheduler.common.utils.OSUtils.exeCmd(OSUtils.java:382)
        at org.apache.dolphinscheduler.common.utils.OSUtils.getGroup(OSUtils.java:345)
        at org.apache.dolphinscheduler.common.utils.OSUtils.createUser(OSUtils.java:254)
        at org.apache.dolphinscheduler.common.utils.OSUtils.createUserIfAbsent(OSUtils.java:241)
        at org.apache.dolphinscheduler.server.worker.processor.TaskExecuteProcessor.process(TaskExecuteProcessor.java:148)
        at org.apache.dolphinscheduler.remote.handler.NettyServerHandler.lambda$processReceived$0(NettyServerHandler.java:129)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[INFO] 2022-05-27 17:54:51.116 org.apache.dolphinscheduler.common.utils.OSUtils:[242] - create user user_01 fail
[INFO] 2022-05-27 17:54:51.133 org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread:[129] - script path : /tmp/dolphinscheduler/exec/process/5659478977376/5659504793696_1/1/1
[ERROR] 2022-05-27 17:54:51.133 org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread:[133] - tenantCode: user_01 does not exist
[INFO] 2022-05-27 17:54:51.135 org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread:[229] - develop mode is: false
[INFO] 2022-05-27 17:54:51.137 org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread:[247] - exec local path: /tmp/dolphinscheduler/exec/process/5659478977376/5659504793696_1/1/1 cleared.
17:55:30.416 [NettyServerWorkerThread_1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
17:55:30.416 [NettyServerWorkerThread_1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
17:55:30.416 [NettyServerWorkerThread_1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
17:55:30.416 [NettyServerWorkerThread_1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
17:55:30.416 [NettyServerWorkerThread_1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.delayedQueue.ratio: 8
17:55:30.424 [NettyServerWorkerThread_1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
17:55:30.424 [NettyServerWorkerThread_1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
17:55:30.425 [NettyServerWorkerThread_1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@6c39ecf1
17:55:30.785 [pool-2-thread-1] INFO org.apache.dolphinscheduler.server.log.LoggerRequestProcessor - received command : Command [type=ROLL_VIEW_LOG_REQUEST, opaque=24, bodyLen=107]
17:55:30.795 [pool-2-thread-1] INFO org.apache.dolphinscheduler.server.log.LoggerRequestProcessor - file path: /opt/apache-dolphinscheduler-2.0.5-bin/logs/5659504793696_1/1/1.log not exists

### What you expected to happen

I don't know

### How to reproduce

MySQL引擎部署

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
It seems group ID 1337 did not exists in your worker's machine. @harkowl

**Comment by harkowl** [comment]
> It seems group ID 1337 did not exists in your worker's machine. @harkowl

Is it necessary to authorize the directory
I don't know ...
