### ISSUE TITLE
[Bug] [Task instance  log] Can't show instance log detail when  upgrade version 1.3.5 to 2.0.5

### ISSUE THREAD

**Issue by syncwt** [apache/dolphinscheduler#10285]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I  run task on  version 1.3.5. The  instance's log is  full  detail.  
![image](https://user-images.githubusercontent.com/24603463/170909896-4c9153db-d394-4018-9bbd-b13f47f45cde.png)
But now  I   upgraded to v2.0.5. The  log  only   show   log directory. I'm not  sure what's  wrong  about  my  config ?
![image](https://user-images.githubusercontent.com/24603463/170910043-27ae4f93-4867-4a5c-beb5-7e93c823a4ea.png)

### What you expected to happen

Show log detail like  v1.3.5

### How to reproduce

Run  any task   at v2.0.5 include dataX , hive ,spark  task.

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lordk911** [comment]
@syncwt go to host: 10.10.100.25 dose the [LOG-PATH] point file exist ？ 
I'm using 2.0.5 too , and meet this issue more and more. It's only show the [LOG-PATH] line , but can't find log file on the host.

**Comment by syncwt** [comment]
It would be more possible reasons. And you can find more details from worker logs.

**Comment by brave-lee** [comment]
The job running history does not support upgrading. Please clear the job running history when upgrading
