### ISSUE TITLE
[DSIP-19][Feature] Add connection center feature for DS

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#10283]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Add `Connection Center` feature for Dolphin Scheduler so that plugins will be able to achieve connection information such as host, endpoint, credentials to external system and switch them easily without restarting DS.

### Use case

* For more information of this feature, we could refer to [Apache Airflow Connections Management](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html)

![image](https://user-images.githubusercontent.com/34905992/170879292-79c46e12-40d2-433b-85aa-8e26f00ec812.png)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
Could anyone please help add the `discussion` label to this issue? I think we need some discussions for the design of this feature : )

**Comment by davidzollo** [comment]
good idea

**Comment by EricGao888** [comment]
This feature would be something like extended `datasource` feature which we already have. The difference is that all task plugins besides SQL related ones could gain access to it.

**Comment by EricGao888** [comment]
BTW, as discussed, we need some kind of `data masking` mechanism to hide sensitive data. Should we open another issue for `data masking`?

**Comment by EricGao888** [comment]
> BTW, as discussed, we need some kind of `data masking` mechanism to hide sensitive data. Should we open another issue for `data masking`?

Added here: #10498

**Comment by SbloodyS** [comment]
It seems that this is more like a configuration center in ds. WDYT? @EricGao888

**Comment by EricGao888** [comment]
> It seems that this is more like a configuration center in ds. WDYT? @EricGao888

@SbloodyS Exactly.

**Comment by EricGao888** [comment]
Seems there would be two kinds of configurations if we implement this feature on the basis of current `data center`.

1. Connection related configurations for datasource, task plugins, etc.
2. Some common configurations which are in `common.properties` at present.

BTW, we may still keep less-frequently-changed and high-risky configurations in `common.properties`.

**Comment by EricGao888** [comment]
Could you please help add a `discussion` label for this issue? Thx @SbloodyS

**Comment by SbloodyS** [comment]
> Could you please help add a `discussion` label for this issue? Thx @SbloodyS

Sure.

**Comment by SbloodyS** [comment]
> Seems there would be two kinds of configurations if we implement this feature on the basis of current `data center`.
> 
> 1. Connection related configurations for datasource, task plugins, etc.
> 2. Some common configurations which are in `common.properties` at present.
> 
> BTW, we may still keep less-frequently-changed and high-risky configurations in `common.properties`.

Yes. I think the data source center should be part of the configuration center.

**Comment by EricGao888** [comment]
Some ideas about user experience:

* We will have each task plugin bound with default connection, which corresponds to task types. 
* We set default values in default connections so that new users to Dolphin Scheduler will not need to spend time figuring out what this `configuration center` does if they just try some basic stuff.
* Users will be able to see default example values in connection related configurations to help them understand how to manage connections.

**Comment by EricGao888** [comment]
Rules for configuration update should be established at the very beginning to avoid confusion.

**Comment by EricGao888** [comment]
I will give a design later this month. For the first stage, we will focus on task plugin connections part.

**Comment by qingwli** [comment]
Hi @EricGao888 , Could you help realize multiple resource centers?

**Comment by EricGao888** [comment]
> Hi @EricGao888 , Could you help realize multiple resource centers?

We have already removed singleton design for storage operators in backend. Therefore, it is possible to support multiple remote resource storages in resource center. But we need a good design for UI interactions.
