### ISSUE TITLE
[Bug] [Monitor] Audit Log not working

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#10295]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

* Dolphin Scheduler `Audit Log` in `Monitor` section does not work.
* There is no record in `t_ds_audit_log`.

![image](https://user-images.githubusercontent.com/34905992/170971390-286646f9-0d6d-450b-9b67-dc83266be9a9.png)

![image](https://user-images.githubusercontent.com/34905992/170971469-ac38dd43-e91a-43f2-8bfc-15074f5db5e5.png)

### What you expected to happen

* `Audit Log` feature should function properly.

### How to reproduce

* Already described above.

### Anything else

* Already described above.

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Thank @EricGao888 to bring this up, I add milestone `3.0.0-beta-2` and label `help wanted` to find someone interested of this issue

**Comment by huangchenguang123** [comment]
org.apache.dolphinscheduler.api.service.AuditService#addAudit is not used anywhere.

**Comment by ruanwenjun** [comment]
> org.apache.dolphinscheduler.api.service.AuditService#addAudit is not used anywhere.

Yes, this feature is bring at SOC2021, the audit data ingest has not been implementation, are you interested to finish this? @EricGao888

**Comment by EricGao888** [comment]
> > org.apache.dolphinscheduler.api.service.AuditService#addAudit is not used anywhere.
> 
> Yes, this feature is bring at SOC2021, the audit data ingest has not been implementation, are you interested to finish this? @EricGao888

Thx for the information. Recently I have several other DS issues WIP, therefore, I will be appreciated if someone else could help with this issue. IMHO, this issue is kind of urgent because users can access `audit` in `monitor` section and if they find it not working, they probably get confused.

**Comment by EricGao888** [comment]
Seems no one else has started to work on this. Currently I'm working on the auditing feature of another project. Therefore, I would like to take a look on this issue. Could anyone please assign this to me? Thx~

**Comment by ruanwenjun** [comment]
cc @caishunfeng Is there anyone working on this?

**Comment by WangJPLeo** [comment]
> Seems no one else has started to work on this. Currently I'm working on the auditing feature of another project. Therefore, I would like to take a look on this issue. Could anyone please assign this to me? Thx~

We have extended the audit outside DS, using the Around aspect to collect the interactive data information of the API. But it is not based on the 't_ds_audit_log' in DS. @EricGao888

**Comment by EricGao888** [comment]
Hello @WangJPLeo , may I ask whether there is any progress on this issue? Thanks

**Comment by WangJPLeo** [comment]
> Hello @WangJPLeo , may I ask whether there is any progress on this issue? Thanks

Sorry for replying so late. Currently, all types of API operation records can be supported, and the operation details have been saved to the database, including all available information such as requests and responses. Data as follows：

display: 
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/103574007/192273300-135fa592-27fb-4b7c-b9e0-6ef1a85c9f5a.png">
detail in db: 
![image](https://user-images.githubusercontent.com/103574007/192273332-c1e70e7c-3eaf-4103-9799-22f50c59169c.png)

Next, I will improve the content display of resource names and operations, and submit a PR this Thursday or Friday, more design content will be described in the first pr. Finally, a working release is expected by mid-October.

**Comment by EricGao888** [comment]
> > Hello @WangJPLeo , may I ask whether there is any progress on this issue? Thanks
> 
> Sorry for replying so late. Currently, all types of API operation records can be supported, and the operation details have been saved to the database, including all available information such as requests and responses. Data as follows：
> 
> display: <img alt="image" width="1107" src="https://user-images.githubusercontent.com/103574007/192273300-135fa592-27fb-4b7c-b9e0-6ef1a85c9f5a.png"> detail in db: ![image](https://user-images.githubusercontent.com/103574007/192273332-c1e70e7c-3eaf-4103-9799-22f50c59169c.png)
> 
> Next, I will improve the content display of resource names and operations, and submit a PR this Thursday or Friday, more design content will be described in the first pr. Finally, a working release is expected by mid-October.

@WangJPLeo That's pretty cool! Thanks for the detailed reply : )

**Comment by xbyang18** [comment]
yes,org.apache.dolphinscheduler.api.service.AuditService#addAudit is not used anywhere.
I use latest v3.1.0 
I dont understand why has the feature with UI, we release every version must examine ,so it is apache product

**Comment by rainhan99** [comment]
I use v3.1.3 deploy. but also can't find audit logs. so about this problem is resolved?
