### ISSUE TITLE
[Bug] [Workflow Relationships] Dependencies between workflows are not displayed properly

### ISSUE THREAD

**Issue by mrhaoqi** [apache/dolphinscheduler#10291]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![8edeb97956780fcdcef382782cc0250](https://user-images.githubusercontent.com/18070116/170937355-00c82cc3-309d-4fa8-86df-896d0f88945a.png)

### What you expected to happen

-

### How to reproduce

-

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
remove stale

**Comment by EricGao888** [comment]
@mrhaoqi May I ask whether there are any updates for this issue?
