### ISSUE TITLE
[Bug] [Api-Server] Improve exception handling when admin user uploads file in resource center

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#10293]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

* If user logs in with admin role and does not set tenant, there will be `null pointer exception` when he / she tries to upload files in `resource center`.

![image](https://user-images.githubusercontent.com/34905992/170941904-0838298f-c29f-4364-ac11-4be4b1980097.png)

### What you expected to happen

* We need some exception handling here and provide users with instructive error message: https://github.com/apache/dolphinscheduler/blob/8d26d4fe72aa81437103716b22f52ef6dc515a14/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java#L653-L656

* We need to remind users that tenant should be set before playing with `resource center` if they log in with `admin` role.

### How to reproduce

* Already described above.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
It should be noticed when user execute workflow without assigned tenant too
