### ISSUE TITLE
[Bug] [Task] Constant definitions are repeated

### ISSUE THREAD

**Issue by guodongym** [apache/dolphinscheduler#10305]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The constants of the following configuration items have repeated definitions

```
aws.access.key.id
aws.secret.access.key
aws.region
```

Respectively in

org.apache.dolphinscheduler.plugin.task.api.TaskConstants
org.apache.dolphinscheduler.common.Constants

### What you expected to happen

Is it necessary to duplicate definitions? Is it possible to use one set?

### How to reproduce

Respectively in

org.apache.dolphinscheduler.plugin.task.api.TaskConstants
org.apache.dolphinscheduler.common.Constants

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
@guodongym I suggest that we can remove these three constant in `org.apache.dolphinscheduler.common.Constants ` and keep in `org.apache.dolphinscheduler.plugin.task.api.TaskConstants `.

**Comment by guodongym** [comment]
> @guodongym I suggest that we can remove these three constant in and keep in .`org.apache.dolphinscheduler.common.Constants ``org.apache.dolphinscheduler.plugin.task.api.TaskConstants `

@ruanwenjun   I think the opposite, Can keep in `org.apache.dolphinscheduler.common.Constants` , remove that from `org.apache.dolphinscheduler.plugin.task.api.TaskConstants` , Because these parameters should be global as more AWS components are supported
-----------
我认为恰恰相反，因为随着后续支持更多的AWS组件，这三个参数应该是全局通用的，不应该保持在task的常量里面

**Comment by guodongym** [comment]
> @guodongym I suggest that we can remove these three constant in `org.apache.dolphinscheduler.common.Constants ` and keep in `org.apache.dolphinscheduler.plugin.task.api.TaskConstants `.

@ruanwenjun  I guess you're right. I see that Common references the DolphinScheduler-task-API module, but the tasks plugin doesn't reference common so it should be keep in `org.apache.dolphinscheduler.plugin.task.api.TaskConstants`

**Comment by ruanwenjun** [comment]
> > @guodongym I suggest that we can remove these three constant in and keep in .`` org.apache.dolphinscheduler.common.Constants ``org.apache.dolphinscheduler.plugin.task.api.TaskConstants  ``
> 
> ## @ruanwenjun I think the opposite, Can keep in `org.apache.dolphinscheduler.common.Constants` , remove that from `org.apache.dolphinscheduler.plugin.task.api.TaskConstants` , Because these parameters should be global as more AWS components are supported
> 我认为恰恰相反，因为随着后续支持更多的AWS组件，这三个参数应该是全局通用的，不应该保持在task的常量里面

In my knowledge, AWS is just a choosable plugin, it should not be a necessary dependency. Put the module-specific 
 parameters into specific modules will be more cohesive. 

BTW, `dolphinscheduler-common` rely on `task-api`.
