### ISSUE TITLE
[Feature][Task Plugin] Enable users to switch and install conda env in jupyter task

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#10302]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Currently users need to manually create conda env and install all libs on workers when using `jupyter task plugin`, which is not convenient with multiple workers. If workers do not have public ips, it will be more torturing.

* By adding this feature, we could enable users to switch conda envs in jupyter task, something like switching interpreters in `PyCharm`. Users will upload their packed conda envs to `resource center`, and choose the one needed when setting up jupyter task.

![image](https://user-images.githubusercontent.com/34905992/171004364-5c9e7855-7906-4c3e-a656-74a64811c461.png)

### Use case

* Already described above.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
May I ask is there any best practice about how to download resources from `resource center` in `task plugin`?

**Comment by EricGao888** [comment]
I was planning to enable users to download packed conda environment from `resource center` at the beginning of jupyter task. However, packed conda env could be large, like 200MB. If downloading every time before executing jupyter task, it may cause network issue, especially when resources are stored in remote object storage like `s3`.
I'm not sure whether there is something like cache we could use in this scenario. 

Otherwise, we might find a workaround, such as creating a new task type called `python-virtual-env task`, giving users ability to set up their python env in several different ways (they can choose the one they like) on target worker once for all.

@zhongjiajie @SbloodyS @caishunfeng WDYT

**Comment by EricGao888** [comment]
If we choose the `python-virtual-env task` approach, we could establish some interaction between this new task and other python related task. For example, after running `python-virtual-env task`, DS will append the path of the new env into a file called `virtual_env_paths.txt`.  `Python` or `Jupyter` task will automatically read this file, and users will be able to choose the env they want from `UI`.

**Comment by EricGao888** [comment]
Of course, we could take both of them and users could choose the one they like...

**Comment by EricGao888** [comment]
FYI, there is a `PythonVirtualenvOperator` in `Apache Airflow` designed in another way. It will automatically created and destroyed virtual env according to the `requirement.txt` provided by users. However, this method seems to require workers to bind public ips.

https://github.com/apache/airflow/blob/main/airflow/operators/python.py

https://registry.astronomer.io/providers/apache-airflow/modules/pythonvirtualenvoperator

**Comment by jieguangzhou** [comment]
> FYI, there is a `PythonVirtualenvOperator` in `Apache Airflow` designed in another way. It will automatically created and destroyed virtual env according to the `requirement.txt` provided by users. However, this method seems to require workers to bind public ips.
> 
> https://github.com/apache/airflow/blob/main/airflow/operators/python.py
> 
> https://registry.astronomer.io/providers/apache-airflow/modules/pythonvirtualenvoperator

Workers that run jupyter tasks maybe always can bing public IPs.
In the future maybe we can create a new environment by passing `requirements.txt` and `python version` in

**Comment by EricGao888** [comment]
> > FYI, there is a `PythonVirtualenvOperator` in `Apache Airflow` designed in another way. It will automatically created and destroyed virtual env according to the `requirement.txt` provided by users. However, this method seems to require workers to bind public ips.
> > https://github.com/apache/airflow/blob/main/airflow/operators/python.py
> > https://registry.astronomer.io/providers/apache-airflow/modules/pythonvirtualenvoperator
> 
> Workers that run jupyter tasks maybe always can bing public IPs. In the future maybe we can create a new environment by passing `requirements.txt` and `python version` in

I plan to add the feature of enabling users to pass requirements.txt to python related task. No matter users choose to bind public ips to their workers or not, what we could do is to provide users with one more choice to manage python environment. `DS` should have the same or even better user experience when it come to python related task environment management.

**Comment by SbloodyS** [comment]
> > > FYI, there is a `PythonVirtualenvOperator` in `Apache Airflow` designed in another way. It will automatically created and destroyed virtual env according to the `requirement.txt` provided by users. However, this method seems to require workers to bind public ips.
> > > https://github.com/apache/airflow/blob/main/airflow/operators/python.py
> > > https://registry.astronomer.io/providers/apache-airflow/modules/pythonvirtualenvoperator
> > 
> > 
> > Workers that run jupyter tasks maybe always can bing public IPs. In the future maybe we can create a new environment by passing `requirements.txt` and `python version` in
> 
> I plan to add the feature of enabling users to pass requirements.txt to python related task. No matter users choose to bind public ips to their workers or not, what we could do is to provide users with one more choice to manage python environment. `DS` should have the same or even better user experience when it come to python related task environment management.

I agreed. It is good to give users a more convenient option.

**Comment by zhongjiajie** [comment]
> If workers do not have public ips, it will be more torturing.

Maybe we should not imagine what users' environment is, it will increase our cost. If users machine without public IP, how could they install python package? maybe they have whl package in their local, they could install by `pip install --no-index -f ./pkg_path pkg name`. maybe the have python package index in they network locally. maye the others balabala thing they could do. But I think the most general way is install according to `requirements.txt`. So maybe we should use `requirements.txt` first, and then think about other edge case like public IP, others package manager, multiple python version supported

**Comment by SbloodyS** [comment]
> If workers do not have public ips, it will be more torturing.

Yes. So I suggest giving a switch to the user to choose it.

**Comment by zhongjiajie** [comment]
> > If workers do not have public ips, it will be more torturing.
> 
> Yes. So I suggest giving a switch to the user to choose it.

Sorry, I do not finish my comment above 😄
