### ISSUE TITLE
[Bug] [TestCase]  TelegramSenderTest  Network timeout retry

### ISSUE THREAD

**Issue by guodongym** [apache/dolphinscheduler#10315]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

run test case  `org.apache.dolphinscheduler.plugin.alert.telegram.TelegramSenderTest`  There is an error

```
信息: I/O exception (java.net.NoRouteToHostException) caught when processing request to {s}->https://api.telegram.org:443: No route to host (Host unreachable)
五月 31, 2022 6:26:20 下午 org.apache.http.impl.execchain.RetryExec execute
信息: Retrying request to {s}->https://api.telegram.org:443
``` 

### What you expected to happen

run test case success

### How to reproduce

run test case  `org.apache.dolphinscheduler.plugin.alert.telegram.TelegramSenderTest`  On the MAC

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @guodongym , please check if your network can login to the telegram normally.

**Comment by guodongym** [comment]
> Hi @guodongym , please check if your network can login to the telegram normally.

can access it only when the network proxy is enabled

**Comment by SbloodyS** [comment]
> > Hi @guodongym , please check if your network can login to the telegram normally.
> 
> can access it only when the network proxy is enabled

So that ```TelegramSenderTest``` can be executed normally when the network proxy is enabled.

**Comment by guodongym** [comment]
> > > Hi @guodongym , please check if your network can login to the telegram normally.
> > 
> > 
> > can access it only when the network proxy is enabled
> 
> So that `TelegramSenderTest` can be executed normally when the network proxy is enabled.

Thank you. I'll try again
