### ISSUE TITLE
[Bug] [LOG] An instance is retried multiple times and then deleted, removing only one log  

### ISSUE THREAD

**Issue by retime123** [apache/dolphinscheduler#10316]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/29012717/171174961-afe452dc-f5c5-4762-9396-b3bd75f86bc2.png)
![image](https://user-images.githubusercontent.com/29012717/171175067-eb945d23-c111-4199-82fb-06cb13452d63.png)
这两个都在/data1_1T/dolphinscheduler/logs/5655920567360_5/71480/下
（Both in/data1_1T/dolphinscheduler/logs/5655920567360_5/71480/ ）
![image](https://user-images.githubusercontent.com/29012717/171175400-80d97356-c67a-4ce2-97e9-d76169017942.png)
然后我执行删除操作：
（Then I delete:）
![image](https://user-images.githubusercontent.com/29012717/171175639-187d9ec8-321d-4733-8931-8c03fad7056c.png)
结果是：只删除了一个日志！
（Result: only one log was deleted!）
![image](https://user-images.githubusercontent.com/29012717/171175904-0a057a72-7049-4486-a0af-0c3351a0ccd1.png)
显示是正常的（记录没了）：
（The display is normal (the record is gone) :）
![image](https://user-images.githubusercontent.com/29012717/171176024-270ae68e-ec99-4248-8606-f306c0a1c5cc.png)

我用的版本是2.0.5（I'm using version 2.0.5）

### What you expected to happen

![image](https://user-images.githubusercontent.com/29012717/171176913-c4913653-0213-4c45-8420-d4d97b1b9b64.png)
删除日志逻辑有bug
（The log deletion logic is buggy）
希望早日解决
Hope for an early settlement

### How to reproduce

一个实例重试几次，然后删除，在机器上查看日志情况
An instance is retried several times and then deleted to view the logs on the machine  

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
This has been solved in #10541
