### ISSUE TITLE
[Feature][Doc] Provide users with clear guidance on jdk versions

### ISSUE THREAD

**Issue by 106umao** [apache/dolphinscheduler#10324]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The official [product usage documentation](https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/about/introduction.html) and [developer documentation](https://dolphinscheduler.apache.org/zh-cn/development/development-environment-setup.html) before this are prompted to support jdk1.8+, then like me this fool is using jdk11 for development, the results of the problem everywhere, after some communication with the community brothers found that does not support the version of 1.8+. when I went back to the website today, the [developer documentation](https://dolphinscheduler.apache.org/zh-cn/development/development-environment-setup.html) has been corrected, but the [product usage documentation](https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/about/introduction.html) has not been changed, so I will mention a pr to correct these documents.

### Related issues

#10232 
#10320 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
@106umao Hi, please clarify which problem you meet with jdk11. I also use jdk11, and it can compile/run successfully.

**Comment by 106umao** [comment]
> @106umao Hi, please clarify which problem you meet with jdk11. I also use jdk11, and it can compile/run successfully.

Did you forget to use` mvn clean`, or did you skip the compilation of some modules?
