### ISSUE TITLE
Can our scheduling increase the mutual arrangement of ETL task types?(咱们的调度是否可以增加ETL任务类型之间的相互编排)

### ISSUE THREAD

**Issue by sancong** [apache/dolphinscheduler#1033]
咱们的调度是否可以增加ETL任务类型之间的相互编排？ 比如不同的抽取方式提供不同的任务节点类型，不同的转换方式提供不同任务节点类型，不同的加载方式也提供有不同的任务节点类型，所有的节点之间可以相互的编排。

Can our scheduling increase the mutual arrangement of ETL task types? For example, different extraction methods provide different task node types, different conversion methods provide different task node types, different loading methods also provide different task node types, and all nodes can be arranged mutually.

**Comment by dailidong** [comment]
I'm sorry, I can't understand you said,  could you give some examples?
