### ISSUE TITLE
[Improvement][dolphinscheduler-api] Add a switch for Swagger

### ISSUE THREAD

**Issue by kangyuanjia** [apache/dolphinscheduler#10332]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description
#10332 
Swagger has unauthorized access, exposing too much sensitive information

### Use case

Add a switch for Swagger
Swagger has unauthorized access, exposing too much sensitive information

### Related issues

None

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
- #10333 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Adding switch for swagger is reasonable for me, but I don't agree swagger will expose sensitive information.

**Comment by kangyuanjia** [comment]
@ruanwenjun Colleagues in information security suggest authorizing access or closing pages using swagger information.
![1654100395481_92DD33F5-09D7-4f9b-83DA-387B0B2CB324](https://user-images.githubusercontent.com/19955209/171454124-447ba6c2-6d54-4766-8bcd-990976a61a9e.png)

**Comment by ruanwenjun** [comment]
> @ruanwenjun Colleagues in information security suggest authorizing access or closing pages using swagger information. ![1654100395481_92DD33F5-09D7-4f9b-83DA-387B0B2CB324](https://user-images.githubusercontent.com/19955209/171454124-447ba6c2-6d54-4766-8bcd-990976a61a9e.png)

This is just an API-docs :).

**Comment by caishunfeng** [comment]
I will close this issue due to longtime no update, feel free to reopen it.
