### ISSUE TITLE
[Bug] [API] Task parameter check error

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#10349]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I start the `dolphinscheduler-api`, `dolphinscheduler-master`, `dolphinscheduler-worker`. And create a task, I get an error.
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/22415594/171610402-b4d2dc21-138e-4ed5-9852-5e8fbabbce48.png">

This is caused by we remove the task plugin dependencies in `dolphinscheduler-api` module, but we rely the task plugin module to do the parameter check.

### What you expected to happen

xx

### How to reproduce

Create a task in cluster mode.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Maybe we need to change the dependency 
https://github.com/apache/dolphinscheduler/blob/6134e0a628edc9890adc6f7677a5d122dd5c1a93/dolphinscheduler-api/pom.xml#L54-L57
to 
```xml
<dependency>
        <groupId>org.apache.dolphinscheduler</groupId>
        <artifactId>dolphinscheduler-task-all</artifactId>
</dependency>
```
This will increase the size of api module. cc @kezhenxu94

**Comment by kezhenxu94** [comment]
> Maybe we need to change the dependency 
> 
> https://github.com/apache/dolphinscheduler/blob/6134e0a628edc9890adc6f7677a5d122dd5c1a93/dolphinscheduler-api/pom.xml#L54-L57
> 
> to 
> 
> ```xml
> 
> <dependency>
> 
>         <groupId>org.apache.dolphinscheduler</groupId>
> 
>         <artifactId>dolphinscheduler-task-all</artifactId>
> 
> </dependency>
> 
> ```
> 
> This will increase the size of api module. cc @kezhenxu94 
> 
> 

Thanks for the information. I can help to verify when you open a pull request.
