### ISSUE TITLE
[Bug] [dolphinscheduler-api] HDFS failed to upload large file

### ISSUE THREAD

**Issue by github-keep** [apache/dolphinscheduler#10340]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

在配置HDFS之后使用资源中心上传过大的文件（90MB）失败，小文件可以。猜想：不能上传超过HDFS数据块大小（64MB）的文件，查看日志错误信息：没有合适的分解器。
![image](https://user-images.githubusercontent.com/34233672/171570072-3bb4a43f-0ab3-4474-bb07-bf63fe8bcf40.png)

### What you expected to happen

在之前版本（2.0.5）中，该功能正常可以使用，升级版本3.0.0-alpha，3.0.0-beta-1均不能正常使用。

### How to reproduce

集群部署完成后，配置HDFS，使用的Hadoop 集群 NameNode 配置了 HA ，完成之后上传一个128MB（超过HDFS数据块）以上的文件

### Anything else

问题每次都出现，相关的日志再安装目录下面的api-server/logs下的最新文件中

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
I encountered this error, too. May I ask is there any update or potential solutions to this issue?

**Comment by fhygh** [comment]
i upload 200+M file is ok, 3.0.0 beta-1 version
![image](https://user-images.githubusercontent.com/25889738/172842068-4da61396-9849-44fa-a6d4-95f6bd6fe013.png)

**Comment by GodWon** [comment]
> 我上传 200+M 文件没问题，3.0.0 beta-1 版本 ![图片](https://user-images.githubusercontent.com/25889738/172842068-4da61396-9849-44fa-a6d4-95f6bd6fe013.png)

我300M也没报错 传900M的报错了

**Comment by SunHeng98** [comment]
> I encountered this error, too. May I ask is there any update or potential solutions to this issue?

你好，请问解决了吗？我也遇到这个问题了，好像是上传时间超过15秒就会自动取消。

**Comment by yaowj2** [comment]
从debug springboot报的实际异常是org.eclipse.jetty.io.EofException: Early EOF。原因在前端用axios 提交时设置了超时时间为15s，导致在上传过程中前端超时提前中断了， 见下面在ui service.ts的代码片段部分，修改加大timeout时间后上传大文件通过 
`const baseRequestConfig: AxiosRequestConfig = {
  baseURL:
    import.meta.env.MODE === 'development'
      ? '/dolphinscheduler'
      : import.meta.env.VITE_APP_PROD_WEB_URL + '/dolphinscheduler',
  timeout: 15000,`

**Comment by CriysHot** [comment]
> 从debug springboot报的实际异常是org.eclipse.jetty.io.EofException: Early EOF。原因在前端用axios 提交时设置了超时时间为15s，导致在上传过程中前端超时提前中断了， 见下面在ui service.ts的代码片段部分，修改加大timeout时间后上传大文件通过
> `const baseRequestConfig: AxiosRequestConfig = { baseURL: import.meta.env.MODE === 'development' ? '/dolphinscheduler' : import.meta.env.VITE_APP_PROD_WEB_URL + '/dolphinscheduler', timeout: 15000,`
Excuse me,i wanna know how to change the conf conveniently？should I compile the code？

**Comment by EricGao888** [comment]
related: #10509

**Comment by yangjf2019** [comment]
I'm having the same problem, what specific file configuration needs to be changed, please? The service.ts file was not found. @CriysHot @yaowj2 

The file url is https://github.com/apache/dolphinscheduler/blob/dev/dolphinscheduler-ui/src/service/service.ts.

**Comment by yangjf2019** [comment]
Solved, the following 4 files need to be modified.
```
/api-server/ui/assets/service.766f4632.js
/api-server/ui/assets/service.766f4632.js.gz

/ui/assets/service.766f4632.js
/ui/assets/service.766f4632.js.gz
```
and find the following configuration `baseURL:"/dolphinscheduler",timeout:15e3`,then modify 15e3 to 15e5 or greater.

**Comment by EricGao888** [comment]
> Solved, the following 4 files need to be modified.
> 
> ```
> /api-server/ui/assets/service.766f4632.js
> /api-server/ui/assets/service.766f4632.js.gz
> 
> /ui/assets/service.766f4632.js
> /ui/assets/service.766f4632.js.gz
> ```
> 
> and find the following configuration `baseURL:"/dolphinscheduler",timeout:15e3`,then modify 15e3 to 15e5 or greater.

@yangjf2019 Great job! Would you like to submit a PR to fix this?

**Comment by yangjf2019** [comment]
> 

Thanks, I can try.

**Comment by yangjf2019** [comment]
Hi, @EricGao888 is it possible to increase the value of this parameter so that it becomes 30 minutes?

**Comment by yangjf2019** [comment]
In general, and frankly, it's not recommended to use dolphinscheduler to upload files that are too big!

**Comment by EricGao888** [comment]
> Hi, @EricGao888 is it possible to increase the value of this parameter so that it becomes 30 minutes?

May I ask whether it is possible to make it configurable for users?

**Comment by yangjf2019** [comment]
Yes, I think it should be done too, please let me take another look, thanks.

**Comment by zhongjiajie** [comment]
> Thanks, I can try.

Do you still want to submit pull request to fix this? @yangjf2019

**Comment by xpf-demo** [comment]
我改了那四个js文件，，为啥还是不行啊，有大佬有相同的情况吗

**Comment by github-keep** [comment]
> 我改了那四个js文件，，为啥还是不行啊，有大佬有相同的情况吗

The larger the file, the longer the upload time. It is recommended to set the time value larger

**Comment by xpf-demo** [comment]
> > 我改了那四个js文件，，为啥还是不行啊，有大佬有同样的情况吗
> 
> 文件越大，上传时间越长。建议将时间值设置得大一些

问题已经解决了，我怀疑是前端浏览器缓存的问题，，后面我把服务重启之后，然后清除了下缓存就可以了

**Comment by xpf-demo** [comment]
> > 我改了那四个js文件，，为啥还是不行啊，有大佬有同样的情况吗
> 
> 文件越大，上传时间越长。建议将时间值设置得大一些

谢谢，我的问题已经解决了。我后面修改了js文件之后，清空了下浏览器的缓存之后，就能正常上传了，后台也没有报错了

**Comment by EricGao888** [comment]
> Yes, I think it should be done too, please let me take another look, thanks.

Hello @yangjf2019, may I ask whether you are still working on this issue? We have received feedback from many users that they get blocked by this issue. IMHO we could have a hot-fix for it at the first step, simply increasing the threshold. Then we could move it further and make it configurable for users. Thanks.

**Comment by EricGao888** [comment]
> > Yes, I think it should be done too, please let me take another look, thanks.
> 
> Hello @yangjf2019, may I ask whether you are still working on this issue? We have received feedback from many users that they get blocked by this issue. IMHO we could have a hot-fix for it at the first step, simply increasing the threshold. Then we could move it further and make it configurable for users. Thanks.

Hot fix #11694

**Comment by TCGOGOGO** [comment]
How about make this configurable? modify code seems tricky

**Comment by TheWindIsRising** [comment]
我也遇到了这个错误。请问这个问题是否有任何更新或潜在的解决方案？

你好，请问解决了吗？我也遇到这个问题了，好像是上传时间超过15秒就会自动取消。

![image](https://user-images.githubusercontent.com/124865830/219828722-aaf53436-ad95-4ea1-b612-21ed77c4bc1b.png)
我的版本是3.1.2
存储位置是MinIO 
部署方式是K8s使用heml部署的，请问您是怎么解决的

**Comment by TheWindIsRising** [comment]
> 我也遇到了这个错误。请问这个问题是否有任何更新或潜在的解决方案？
> 
> 你好，请问解决了吗？我也遇到这个问题了，好像是上传时间超过15秒就会自动取消。
> 
> ![image](https://user-images.githubusercontent.com/124865830/219828722-aaf53436-ad95-4ea1-b612-21ed77c4bc1b.png) 我的版本是3.1.2 存储位置是MinIO 部署方式是K8s使用heml部署的，请问您是怎么解决的

我是上传一个超过200多M的时候发现的问题

**Comment by TheWindIsRising** [comment]
我的版本是3.1.2请问这个问题前端是否解决？

**Comment by TheWindIsRising** [comment]
> > 解决了，需要修改以下4个文件。
> > ```
> > /api-server/ui/assets/service.766f4632.js
> > /api-server/ui/assets/service.766f4632.js.gz
> > 
> > /ui/assets/service.766f4632.js
> > /ui/assets/service.766f4632.js.gz
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 并找到以下配置，然后将 15e3 修改为 15e5 或更高版本。`baseURL:"/dolphinscheduler",timeout:15e3`
> 
> @yangjf2019干得好！您想提交 PR 来解决此问题吗？

可否留个联系方式

**Comment by TheWindIsRising** [comment]
> /api-server/ui/assets/service.766f4632.js

请问这个文件在哪/api-server/ui/assets/service.766f4632.js
由于我是k8s部署的ds，/ui/assets/service.766f4632.js这个文件我在api的pod里面的ui找到了，但是上面那个不知道在哪

**Comment by Jacky-YC** [comment]
![image](https://user-images.githubusercontent.com/42370375/233751384-4177e80d-24c9-4b59-a9d8-01bd83782e78.png)

my version `3.1.5`

From the results, more than 15 seconds of requests will be canceled

**Comment by dalaopo** [comment]
> > /api-server/ui/assets/service.766f4632.js
> 
> 请问这个文件在哪/api-server/ui/assets/service.766f4632.js 由于我是k8s部署的ds，/ui/assets/service.766f4632.js这个文件我在api的pod里面的ui找到了，但上面那个不知道在哪

docker没有 ui/assets/下文件，忽略
