### ISSUE TITLE
[Bug] [File Manage] Can't upload a file to a granted file directory

### ISSUE THREAD

**Issue by codyyang0** [apache/dolphinscheduler#10369]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Admin granted a file directory to a normal user. Granted user can't upload a file to that file directory, the reported error is "The current user does not have permission to operate".

### What you expected to happen

Normal user can upload a file to a file directory that have been granted permission.

### How to reproduce

1. Admin create a file directory on resource manage
2. Admin create a normal user 
3. Admin grant the created file directory permission to the normal user
4. Normal user upload a file to the file directory

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
@codyyang0 Has PR been submitted for this issue ?

**Comment by lordk911** [comment]
![image](https://user-images.githubusercontent.com/19989300/192431050-e9593a56-3d15-4289-b94b-c5b6a5b9fe8c.png)

I use admin create a file directory on resource manager , but I can't  grant the created file directory permission to the normal user , the checkbox can't be select.

**Comment by brave-lee** [comment]
Yes, authorized folders are not supported

**Comment by codyyang0** [comment]
I have not receive submits from PR @JinyLeeChina

**Comment by brave-lee** [comment]
Can you submit  PR ？

**Comment by codyyang0** [comment]
I have not submitted PR.  I will try to solve the bug and submit the PR.

**Comment by lordk911** [comment]
> Yes, authorized folders are not supported

if authorized folders are not supported, how can this issue happen?  I'm puzzled.

**Comment by brave-lee** [comment]
Hi @codyyang0 ,I think not support authorized folders is not bug, and you can submit a improvement pr to dev
