### ISSUE TITLE
[BUG-FE][Page Turning Component] Quick Click Pages Not Responding

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#10366]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Quick Click Pages Not Responding

<img width="1899" alt="image" src="https://user-images.githubusercontent.com/76080484/172092163-94a06335-469d-4330-82bb-f1aff1086166.png">

### What you expected to happen

Display the content of the fourth page

### How to reproduce

Click page 5, quickly click page 4 before it doesn't respond

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
@songjianet Hi, what's the progress of this issue?

**Comment by songjianet** [comment]
This problem will not affect the normal use of users for the time being, so the priority is low.
