### ISSUE TITLE
[Bug] [db] Database upgrade from version 2.0.5 to 3.0.0b1 error

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#10377]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

upgrade dolphinschelduler version from 2.0.5 to 3.0.0-beta-1 will cause error, according to the upgrade doc https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/upgrade.html

### What you expected to happen

ATT

### How to reproduce

install version 2.0.5 and them upgrade to 3.0.0-beta-1

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
This task need a lot of work, I think it can be provided in the official version of 3.0.

**Comment by zhongjiajie** [comment]
> This task need a lot of work, I think it can be provided in the official version of 3.0.

I do not think so, if our upgrade script can not upgrade from 2.0.5 to 3.0.0-bate-2, we will lose some of the users who interesting in version 3.0 but still use 2.0.5. what do you think @devosend , our 300b2 release manager

**Comment by zhongjiajie** [comment]
close by https://github.com/apache/dolphinscheduler/commit/dd34a1da67f8fbbb89bedde655f6257a3b523050 and https://github.com/apache/dolphinscheduler/commit/3915c4f40a1e533645483dbf51e9ffbb0c460d46
