### ISSUE TITLE
[Bug] [3.0bata version installation error]

### ISSUE THREAD

**Issue by yang227** [apache/dolphinscheduler#10389]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When the 3.0bata version is installed according to the official website installation tutorial, if the MySQL metadata is configured, a driver error will be reported, and the MySQL driver jar package needs to be placed in all master servers. Worker, API, and the following lib can solve the problem

![Uploading WechatIMG906.png…]()

### What you expected to happen

It is hoped that the driver can be installed normally by copying it directly to the tool/lib directory. This problem should be caused by the fact that the files in the tool/lib directory are not copied to each service

### How to reproduce

This problem occurs when you install the official website tutorial

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You can find the reason in https://dolphinscheduler.apache.org/en-us/docs/release/faq.html. I'll close this issue. Feel free to open it if you have any further questions.
