### ISSUE TITLE
[Bug] [Doc] The faq.md file is not updated in time

### ISSUE THREAD

**Issue by liubo1990** [apache/dolphinscheduler#10384]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I browsed the faq.md file, I found that the alert.properties mentioned in it does not exist in the dolphinscheduler-alter module.

### What you expected to happen

I want to try to configure the alert mailbox.

### How to reproduce

In idea, first switch to the 3.0.0-beta-1-release branch, and then open the faq.md and configuration.md files:
![image](https://user-images.githubusercontent.com/10627684/172795581-ff1ff6ab-f8d8-49a7-ac7a-664663d27a28.png)
![image](https://user-images.githubusercontent.com/10627684/172795345-dd4b9df3-1351-4b4b-b211-562679ed9371.png)
![image](https://user-images.githubusercontent.com/10627684/172795423-07be28e0-aed1-445f-a2a2-9aa49c1f2853.png)

enter the dolphinscheduler-alter module:
![image](https://user-images.githubusercontent.com/10627684/172796914-a8fa6b85-300f-4109-959b-5d3f220e4b0b.png)

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @liubo1990 , would you like to submit a pr to fix this?

**Comment by liubo1990** [comment]
> Hi @liubo1990 , would you like to submit a pr to fix this?

Hi @SbloodyS，of course I can, but I haven't submitted pr yet, I need to be familiar with how to submit a pr and use dolphinscheduler

**Comment by SbloodyS** [comment]
> > Hi @liubo1990 , would you like to submit a pr to fix this?
> 
> Hi @SbloodyS，of course I can, but I haven't submitted pr yet, I need to be familiar with how to submit a pr and use dolphinscheduler

1. Fork dolphinscheduler's repository.
2. Checkout a new branch according to the latest ```dev``` branch of dolphinscheduler.
3. Add your change to this new branch and push it to your fork's dolphinscheduler's repository.
4. Open a pull request to dolphinscheduler's repository's ```dev``` branch from github web ui.

**Comment by liubo1990** [comment]
> > > Hi @liubo1990 , would you like to submit a pr to fix this?
> > 
> > 
> > Hi @SbloodyS，of course I can, but I haven't submitted pr yet, I need to be familiar with how to submit a pr and use dolphinscheduler
> 
> 1. Fork dolphinscheduler's repository.
> 2. Checkout a new branch according to the latest `dev` branch of dolphinscheduler.
> 3. Add your change to this new branch and push it to your fork's dolphinscheduler's repository.
> 4. Open a pull request to dolphinscheduler's repository's `dev` branch from github web ui.

Hi @SbloodyS ，I have submitted  a pr to fix this #10401
