### ISSUE TITLE
In version 2.0.5, when the front-end defines the workflow, connects a line, and then deletes the line and reconnects, the generated json may have duplicate downstream tasks.

### ISSUE THREAD

**Issue by baoyingcong** [apache/dolphinscheduler#10382]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

2.0.5版本，前端当定义工作流，连上了一条线，再删掉这条线重新连的时候，生成的json可能会出现下游任务重复

### What you expected to happen

前端生成的任务，json里面的task是不应该重复出现的，不然保存到后台就会报错

### How to reproduce

前端处理去重

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This issue has been fixed in #8989. I'll close this issue.
