### ISSUE TITLE
[Bug] [SQL] SQL Task Node Custom Parameters run failed

### ISSUE THREAD

**Issue by fhygh** [apache/dolphinscheduler#10392]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when i using Custom Parameters of SQL Task Node with OUT type, sql query result is more than one row, in downstream sql using the parameters failed, if upstream sql result is one row, it work fine.
failed work flow:
![image](https://user-images.githubusercontent.com/25889738/172971291-7840b455-7325-4c98-805b-a6b5f8b9ad75.png)

work flow success
![image](https://user-images.githubusercontent.com/25889738/172971336-5ac1bc60-2fb7-4ef5-b996-cbb03f1653d8.png)

### What you expected to happen

SQL Task Custom parameters work fine

### How to reproduce

add two sql task node, in first node query select and add custom parameter OUT type, in donwstream sql using the parameters 

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fhygh** [comment]
here is the log:

[LOG-PATH]: /data/apache-dolphinscheduler-3.0.0-beta-1-bin/worker-server/logs/20220610/5803827748480_10-155-217.log, [HOST]:  Host{address='xxxx:1234', ip='xxxx', port=1234}
[INFO] 2022-06-10 08:46:55.800 +0800 [taskAppId=TASK-20220610-5803827748480_10-155-217] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.sql.SqlTask:[120] - Full sql parameters: SqlParameters{type='MYSQL', datasource=1, sql='select name from test.userinfo1 where name in (${name})', sqlType=0, sendEmail=null, displayRows=10, limit=0, segmentSeparator=, udfs='null', showType='null', connParams='null', groupId='0', title='null', preStatements=[], postStatements=[]}
[INFO] 2022-06-10 08:46:55.801 +0800 [taskAppId=TASK-20220610-5803827748480_10-155-217] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.sql.SqlTask:[121] - sql type : MYSQL, datasource : 1, sql : select name from test.userinfo1 where name in (${name}) , localParams : [],udfs : null,showType : null,connParams : null,varPool : [Property{prop='name', direct=IN, type=LIST, value='["lisi","zhangsan"]'}] ,query max result limit  0
[INFO] 2022-06-10 08:46:55.802 +0800 [taskAppId=TASK-20220610-5803827748480_10-155-217] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.sql.SqlTask:[91] - setSqlParamsMap: Property with paramName: name put in sqlParamsMap of content 
select name from test.userinfo1 where name in (${name}) successfully.
[INFO] 2022-06-10 08:46:55.802 +0800 [taskAppId=TASK-20220610-5803827748480_10-155-217] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.sql.SqlTask:[387] - after replace sql , preparing : 
select name from test.userinfo1 where name in (?)
[INFO] 2022-06-10 08:46:55.802 +0800 [taskAppId=TASK-20220610-5803827748480_10-155-217] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.sql.SqlTask:[396] - Sql Params are replaced sql , parameters:["lisi","zhangsan"](LIST)
[INFO] 2022-06-10 08:46:55.802 +0800 [taskAppId=TASK-20220610-5803827748480_10-155-217] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.sql.SqlTask:[465] - can't find udf function resource
[INFO] 2022-06-10 08:46:55.804 +0800 [taskAppId=TASK-20220610-5803827748480_10-155-217] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.sql.SqlTask:[369] - prepare statement replace sql : HikariProxyPreparedStatement@1139720980 wrapping com.mysql.cj.jdbc.ClientPreparedStatement: 
select name from test.userinfo1 where name in (** NOT SPECIFIED **) 
[INFO] 2022-06-10 08:46:55.805 +0800 [taskAppId=TASK-20220610-5803827748480_10-155-217] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.sql.SqlTask:[297] - main statement execute query, for sql: 
select name from test.userinfo1 where name in (?)
[ERROR] 2022-06-10 08:46:55.805 +0800 [taskAppId=TASK-20220610-5803827748480_10-155-217] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.sql.SqlTask:[213] - execute sql error: No value specified for parameter 1
[ERROR] 2022-06-10 08:46:55.805 +0800 [taskAppId=TASK-20220610-5803827748480_10-155-217] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.sql.SqlTask:[164] - sql task error: java.sql.SQLException: No value specified for parameter 1

**Comment by stalary** [comment]
I can try to solve the problem.

**Comment by caishunfeng** [comment]
> I can try to solve the problem.

Hi @stalary sorry for reply late, I had assigned to you.

**Comment by zhongjiajie** [comment]
Are you still work on this issue? @stalary

**Comment by stalary** [comment]
> Are you still work on this issue? @stalary

I'm still doing it. You can do it first if you're in a hurry.

**Comment by liu-lewis** [comment]
It looks like that SqlTask missed of processing parameters with type DataType.LIST
could we resolve this issue together？@stalary @zhongjiajie

**Comment by zhongjiajie** [comment]
> It looks like that SqlTask missed of processing parameters with type DataType.LIST
> could we resolve this issue together？@stalary @zhongjiajie

You can do with @stalary if he do not mind

**Comment by zhongjiajie** [comment]
> > Are you still work on this issue? @stalary
> 
> I'm still doing it. You can do it first if you're in a hurry.

If you still doing with this, please go ahead, we may consider releases in version 3.0.1, WDTY @caishunfeng

**Comment by stalary** [comment]
> It looks like that SqlTask missed of processing parameters with type DataType.LIST could we resolve this issue together？@stalary @zhongjiajie

Do you have any ideas now that I'm still in debug

**Comment by stalary** [comment]
Sql Params are replaced sql , parameters:["x1","x2"](LIST), I think we should replace [] to ()

**Comment by stalary** [comment]
I will modify ParameterUtils.setInParameter.

**Comment by liu-lewis** [comment]
> > It looks like that SqlTask missed of processing parameters with type DataType.LIST could we resolve this issue together？@stalary @zhongjiajie
> 
> Do you have any ideas now that I'm still in debug

1. Transform parameter of type LIST to VARCHAR；
2. Format sql statement with condition IN.

**Comment by stalary** [comment]
> > > It looks like that SqlTask missed of processing parameters with type DataType.LIST could we resolve this issue together？@stalary @zhongjiajie
> > 
> > 
> > Do you have any ideas now that I'm still in debug
> 
> 1. Transform parameter of type LIST to VARCHAR；
> 2. Format sql statement with condition IN.

I have submitted the code, you can help review it~
https://github.com/apache/dolphinscheduler/pull/11285
