### ISSUE TITLE
[Bug] [workflow definition] the request of http is time out 

### ISSUE THREAD

**Issue by wangchuang07** [apache/dolphinscheduler#10393]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

工作流定义中，调用http任务节点时，运行1分钟后，如下错误：
connection failed：java.net.SocketTimeoutException: Read timed out
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)

### What you expected to happen

如何重新配置max_connection_milliseconds 这个参数

### How to reproduce

调用 http 任务节点，get请求方式，超过1分钟就报错

### Version

1.3.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Currently version 1.3.8 was not in the maitaining list. You can try upgrade to the latest stable version to see if this problem still exists.
