### ISSUE TITLE
[Bug-Backend] [Update Possword] Change password shows error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#10394]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Change password shows error

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/76080484/172974838-9886e306-66ad-43d3-bbf6-7be742e4ce91.png">

<img width="1522" alt="image" src="https://user-images.githubusercontent.com/76080484/172974906-9d33f9b3-b64e-447f-9127-95548ec0c0c8.png">

### What you expected to happen

Successfully modified

Back-end verification, as long as the old and new passwords are not equal

### How to reproduce

change Password
Before modification: dolphinscheduler123
Modified: dolphinscheduler123456

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by syyangs799** [comment]
Hello, I looked at the back-end source code and found that the password length is limited to 20 , but the length of ‘dolphinscheduler123456’ has exceeded the limit, so it cannot be modified. You can limit the length of the front end or modify the back end. If the back end needs to be modified, I can submit  @davidzollo 

![uTools_1654843538892](https://user-images.githubusercontent.com/55483518/173008348-a11888da-ef32-47c9-a2cc-93fd6a80acb1.png)

org.apache.dolphinscheduler.api.utils.CheckUtils -> checkPassword()

**Comment by HomminLee** [comment]
Maybe should print the not valid reason to error msg, like tenantCode:

```
if(StringUtils.length(tenantCode) > TENANT_FULL_NAME_MAX_LENGTH){
    putMsg(result, Status.TENANT_FULL_NAME_TOO_LONG_ERROR);
    return result;
}
```
