### ISSUE TITLE
[Bug] [ui-seatunneltask] The UI of setunnel has not been adapted, and an error is reported when saving the task

### ISSUE THREAD

**Issue by syyangs799** [apache/dolphinscheduler#10402]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Now I want to finish it [https://github.com/apache/dolphinscheduler/issues/8031#issue-1102724937](url) 
However, I found that the seatunnel task of the dev branch could not be created successfully,
![uTools_1654846774840](https://user-images.githubusercontent.com/55483518/173020160-477ae3f7-000b-4422-adf3-b4feba5baddf.png)

![ScreenShot_20220610_160732366](https://user-images.githubusercontent.com/55483518/173020897-33dc422f-eba7-4bb7-bffd-e2030ae5273c.png)
You can see the passed taskdefinitionjson parameter in the log. The rawscript is empty
![ScreenShot_20220610_154857035](https://user-images.githubusercontent.com/55483518/173019817-36b916c8-6a99-427c-b2b5-5b9b112f007d.png)
Looking at the source code, I found that the parameters of seatunnelparameters require rawscript not to be empty or null, but I can't configure the value for it on the webui .So I guess the seatunnel task needs to be adapted，If my operation is wrong, please let me know 

### What you expected to happen

seatunnel task can be  created successfully and executed

### How to reproduce

1.Drag a seatunnel icon and add configuration parameters
![uTools_1654847819001](https://user-images.githubusercontent.com/55483518/173019085-ec7ec432-ce36-4f11-984f-12110a4ffa27.png)
2.Click save in the upper right corner and add task parameters,
![uTools_1654847910921](https://user-images.githubusercontent.com/55483518/173019215-4498526d-0a7e-42df-aa9e-ade98920d3dc.png)
3.Click OK
![uTools_1654847977744](https://user-images.githubusercontent.com/55483518/173019395-d4f182b5-f6f8-404c-be39-f4a6c418bcc0.png)

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
@songjianet @caishunfeng There has two diametrically opposed designs in seatunnel task node.I'm not familiar about the original design idea. Can you guys take a look?

**Comment by songjianet** [comment]
> @songjianet @caishunfeng There has two diametrically opposed designs in seatunnel task node.I'm not familiar about the original design idea. Can you guys take a look?

I'm not very clear about this either.

**Comment by zhuangchong** [comment]
This will be fixed in #10422
