### ISSUE TITLE
[Bug] [checkstyle] some checkstyle not work correctly

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#10415]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Some checkstyle not work correctly, such as

* `import *` can be pass the checksytle
* multiple identify statement can without `,`, eg `int intVar,String strVar` should be `int intVar,String strVar`

### What you expected to happen

ATT

### How to reproduce

Change code and submit a new PR, it will pass checkstyle

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I'll fix it.
