### ISSUE TITLE
[Bug] [Master] If an exception occurs during startup, the log will be flushed in an infinite loop

### ISSUE THREAD

**Issue by guodongym** [apache/dolphinscheduler#10413]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

If an exception occurs during startup, the log will be flushed in an infinite loop, Hundreds of megabytes of logs are generated instantly

![image](https://user-images.githubusercontent.com/20675095/173209845-c64c9255-3dbd-4a0f-ab75-5a73c9b82af4.png)

![image](https://user-images.githubusercontent.com/20675095/173211004-81661eda-7caf-42cb-8156-5b4764abd628.png)

### What you expected to happen

Start abnormal interrupt procedures, easy to troubleshoot problems

### How to reproduce

An exception is thrown when the load bean is started

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
@guodongym Could you please provide more detail? Which version? And what exception, right now in dev branch, if the master cannot connect to zookeeper or database in startup, it will stop.

But if the database connect failed in running, this does happen, do you have any good idea, I think we can sleep here if we check the exception generated is too faster in the loop.

We need to add specific exception and  metrics about the exception.

**Comment by guodongym** [comment]
> @guodongym Could you please provide more detail? Which version? And what exception, right now in dev branch, if the master cannot connect to zookeeper or database in startup, it will stop.
> 
> But if the database connect failed in running, this does happen, do you have any good idea, I think we can sleep here if we check the exception generated is too faster in the loop.
> 
> We need to add specific exception and metrics about the exception.

The problem I found was that the constructor threw an exception during the initialization phase of the bean, so that the data source connection would not be initialized, so that the real exception would not be seen. I was wondering if I could catch some unrecoverable exceptions to break the loop

我发现的问题现象是启动初始化bean的阶段，构造方法抛出异常，导致数据源连接还没初始化，就会一直刷报错日志，导致真正的异常也被刷掉看不到了，我在想是不是可以捕捉某些不可恢复的异常让循环中断

![WX20220618-224343](https://user-images.githubusercontent.com/20675095/174443568-e9253e6d-c870-47ec-8042-e234de57227c.png)

**Comment by ruanwenjun** [comment]
@guodongym OK, in my knowledge, if the bean initialize failed, the spring server will close, unless there is an undeamon thread is alive, cloud you please find out if there is any undeamon block the server? 

And I think if we find we need to stop the server, we can directly use Stopper.stop() method or trigger `MasterServer.close()` in some way rather than throw exception, if we hope to check by exception type, we need to do this judge in everywhere we catch an exception.

**Comment by guodongym** [comment]
@ruanwenjun   I have tried to do this, but  @SbloodyS  don't think it is a good way to deal with it. We can discuss together what is better,   There are some problems with this approach, which can only solve problems that are known to need to be thrown, but cannot be handled if an unknown exception occurs during startup

我曾经尝试这样做，但是 SbloodyS 认为这样不是一个好的处理方式，我们可以一起再讨论一下怎么处理才更好；这种处理方式也确实存在一些问题，只能解决一些已知需要抛出异常的问题，但是假如启动过程发生了未知异常还是没办法处理

#10433 

![image](https://user-images.githubusercontent.com/20675095/174445906-1b3583ae-1de8-4a30-ae4c-9d3b063b32b6.png)

**Comment by ruanwenjun** [comment]
@guodongym 
Yes, it just an example.

You need to find out if there is an undeamon thread is alive, the server hang when startup failure is due to the undeamon thread.

**Comment by ruanwenjun** [comment]
I submit #10500 to solve this.
