### ISSUE TITLE
[Bug] [API] Remove workflow bugs

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [apache/dolphinscheduler#10417]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Deleting a workflow does not delete its associated task information data

### What you expected to happen

When deleting a workflow instance, delete its associated task instance information data

### How to reproduce

Create a workflow, then add a task to save and delete the workflow instance at that time

### Anything else

At 2.0.5 version

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by guodongym** [comment]
I am not sure if this is the original feature design or if it is a bug, if it is a bug I can fix it, the dev branch still has this problem

**Comment by davidzollo** [comment]
it's a bug

**Comment by ITBOX-ITBOY** [comment]
> it's a bug

@Goodongym, you can fix it, but who should I ask to confirm this problem

**Comment by guodongym** [comment]
> > it's a bug
> 
> @Goodongym, you can fix it, but who should I ask to confirm this problem

I'm not sure what you need to confirm, can you make it clear

**Comment by ITBOX-ITBOY** [comment]
> > > it's a bug
> > 
> > 
> > @Goodongym, you can fix it, but who should I ask to confirm this problem
> 
> I'm not sure what you need to confirm, can you make it clear

Determine what the original design is and whether the current situation is a bug
