### ISSUE TITLE
[Bug] [Master & Worker] task can submit successfully but cannot execute

### ISSUE THREAD

**Issue by shangeyao** [apache/dolphinscheduler#10418]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/42203474/173232796-87105370-a1c3-4f0f-88a6-d0de1e1ec51a.png)

### What you expected to happen

Task can run completely.

### How to reproduce

Run multiple tasks at the same time, about hundreds, and a few tasks will fail to run normally.

But the master server does not have an error level log.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rookieuncle** [comment]
Hello, I have the same problem. Can you tell me how to solve it?

**Comment by rookieuncle** [comment]
> 你好，我也有同样的问题。你能告诉我如何解决吗？

I think I got it，if the workgroup port is not the default, it needs to be configured in accordance with the one specified when running the task
