### ISSUE TITLE
[Improvement][LDAP] LDAP bug fix && Improvements

### ISSUE THREAD

**Issue by qingwli** [apache/dolphinscheduler#10425]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Recently, We have tried to enable LDAP on DS and found some questions.
- 1. ~~version 2.0.5 User disabled and can't log in, and `dev` has the same bug, see #10386~~ Fixed by #10508 
- 2. ~~Due to the above question,  we need to add a unit test to cover the LDAP user login case.~~ Fixed by #10426  
- 3. ~~When you log in with LDAP and are not a ds user, it will create a new user automatedly. But in my option, LDAP login is the same as user-password log-in, if you are not a ds user, your login will be denied. I think we can add a new config field, user can choose if they log in with LDAP and are not a ds user, which will create a new user or be denied.~~ Fixed by #10451 
- 4. ds config `security.authentication.type` only can be `password` or `LDAP` log in. And do we need the mixed login same as Jenkins or Rancher? Need to discuss
- 5. ~~When you log in with LDAP. And there are still change password pages. But LDAP users have no password config. I think hiding this page when you log in with LDAP is better.~~ Waiting front-support #10507 
- 6. ~~dev branch has no LDAP config in the YAML file. Due to https://github.com/apache/dolphinscheduler/commit/4114cb07f64950f88ffb4aa8a4ecc4815f32d76b#diff-f2f54230647b5ed6920efc032cd61c4dc2acd8f728ad0f43aef1e8fd3f9793ed , I'll fix this and make LDAP to a switch,not a comments config.~~ Fixed by #10429 
- 7. ~~And some contributor says LDAP needs some improvements, I'll fix this. See #10274~~ Part fixed by #10532 , and the other parts will be fixed by @EricGao888 
- 8. ~~The last one, LDAP miss document, And I'll fix this too. See #10250~~ Fixed by #10429  
- 9. LDAP SSL supports&& Add LDAP K8s configuration #14348

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
It seem that @EricGao888 is also working on some LDAP feature

**Comment by qingwli** [comment]
Yes, I already talk to @EricGao888 and we make a deal and I'll handle with LDAP part.

**Comment by EricGao888** [comment]
> It seem that @EricGao888 is also working on some LDAP feature

@liqingwang Looks cool to me. Just a kindly reminder, there could be some differences between `Microsoft AD` and `a typical OpenLDAP`. Both of them are supposed to be taken into consideration, as described here: https://github.com/apache/dolphinscheduler/issues/10274#issuecomment-1140431540

**Comment by qingwli** [comment]
@EricGao888  Sure, Thanks for your reminder.

**Comment by qingwli** [comment]
- #10274 Will be fixed by @EricGao888 Thx

**Comment by EricGao888** [comment]
> * [[Bug] [LDAP] DS LDAP authenticator needs improvements #10274](https://github.com/apache/dolphinscheduler/issues/10274) Will be fixed by @EricGao888 Thx

Sure, I will finish the remaining work. Thx @liqingwang for the contributions!
