### ISSUE TITLE
[Bug] [Python] Python-gate can't support setting the same task name in the same project for different process

### ISSUE THREAD

**Issue by hiSandog** [apache/dolphinscheduler#10431]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I set tasks with the same name in different process of the same project through python-gate.
The system treats these two tasks as one. 
Instead of inserting a new piece of data to table t_ds_task_definition, the system adds one to the original version of the data.
Although the correct task was found in the t_ds_task_definition_log table by version when the task was executed, this still has implications.
So when a task is created, it should be treated as a new task.

### What you expected to happen

When I set tasks with the same name in different process of the same project through python-gate,it should be treated as a new task.

### How to reproduce

Set tasks with the same name in different process of the same project through python-gate

### Version

2.0.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
good catch
