### ISSUE TITLE
[Bug] [Module Name] Bug title 

### ISSUE THREAD

**Issue by lizhongshuai** [apache/dolphinscheduler#10439]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

按照官方文档部署并不能成功部署dolpinscheduler

### What you expected to happen

按照官方文档可以成功部署dolpinscheduler并使用

### How to reproduce

改正官方文档

### Anything else

无

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lizhongshuai** [comment]
没有图片和详细信息&nbsp;就是官方文档过于草率&nbsp; 按照官方文档并不能成功部署软件并且使用




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月14日(星期二) 中午11:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/dolphinscheduler] [Bug] [Module Name] Bug title  (Issue #10439)





 
感谢您的反馈，我们已经收到您的问题，请耐心等待回复。
  
为了让我们尽快了解您的要求，请提供详细信息、版本或图片。
 
如果长时间没有收到回复，可以加入我们的行列并将您的问题发送到频道#troubleshooting
  
—
直接回复此邮件，在GitHub上查看，或者取消订阅.
你收到这封邮件是因为你写了这个帖子。Message ID: ***@***.***&gt;

**Comment by SbloodyS** [comment]
Please describe in english. I'll close this issue. Feel free to reopen it when correct it to english.
