### ISSUE TITLE
[Bug] [DataSource] edit an exist hive datasource connection, don't show principal and keytab

### ISSUE THREAD

**Issue by fhygh** [apache/dolphinscheduler#10436]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when create hive datasource connection, have principal and keytab input item,but if we edit the hive datasource connection, it can't show pirncipal and keytab. One more thing, if we click create hive datasource first, then click edit exist hive datasource, it will show principal.
![image](https://user-images.githubusercontent.com/25889738/173472970-a71cfb84-9b62-4a68-a8dc-8c09b7e76fd8.png)

![image](https://user-images.githubusercontent.com/25889738/173473158-2ece9695-c5d0-4d93-9dbb-b1466883bb50.png)

### What you expected to happen

it can show principal and keytab when edit hive datasource connection.

### How to reproduce

1、create an hive datasource connection(if you have one, skip this)
2、click other like Home tabs, then click datasource tabs again
3、edit the hive datasource connection created in step 1.
4、you will find it don't show principal and keytab

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
please take a look at this issue @devosend thanks

**Comment by devosend** [comment]
I will fix it

**Comment by xinge-1** [comment]
> ### 询问前先搜索
> * [x] 我在[问题](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue)中搜索过，没有发现类似的问题。
> 
> ### 发生了什么
> 创建 hive 数据源连接时，有 principal 和 keytab 输入项，但是如果我们编辑 hive 数据源连接，它不能显示 pirncipal 和 keytab。还有一件事，如果我们先点击create hive datasource，然后点击edit exist hive datasource，就会显示principal。 ![图片](https://user-images.githubusercontent.com/25889738/173472970-a71cfb84-9b62-4a68-a8dc-8c09b7e76fd8.png)
> 
> ![图片](https://user-images.githubusercontent.com/25889738/173473158-2ece9695-c5d0-4d93-9dbb-b1466883bb50.png)
> 
> ### 你期望发生的事情
> 编辑配置单元数据源连接时，它可以显示主体和密钥表。
> 
> ### 如何重现
> 1、创建一个hive数据源连接（如果有，跳过这个） 2、点击其他like Home选项卡，然后再次点击数据源选项卡 3、编辑步骤1中创建的hive数据源连接。 4、你会发现它没有显示主体和密钥表
> 
> ### 还要别的吗
> _没有反应_
> 
> ### 版本
> 3.0.0-beta-1
> 
> ### 你愿意提交PR吗？
> * [ ] 是的，我愿意提交 PR！
> 
> ### 行为守则
> * [x] 我同意遵守该项目的[行为准则](https://www.apache.org/foundation/policies/conduct)

Is this a commercial version? Why can't I see the principal configuration on the UI interface when I open source version 3.0.0

**Comment by zhongjiajie** [comment]
@xinge-1  all issue in this repo in open source version, and all features is in dolphinshceduler, if you do not find the form like issue screenshots, please make sure you use the related version, in this cases, issue target to version 3.0.0-beta-1

**Comment by yeyhuan** [comment]
![image](https://github.com/user-attachments/assets/3d738409-ebc1-4610-a103-d0f627b5c1b9)
我在版本3.1.9的界面上也看不到principal的配置
