### ISSUE TITLE
[Bug] [Master] The subtask has actually been completed,but the parent workflow still wait for the subtask to complete all the time

### ISSUE THREAD

**Issue by wanghaizhou** [apache/dolphinscheduler#10446]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Occasionally, the workflow is stuck by subtasks all the time. 
The subtask has actually been completed,but the parent workflow still wait for the subtask to complete all the time as you see in the image below.
In fact,the sub workflow has been completed ,but the interface data state found by the API is still being "**RUNNING_EXECUTION**". 
![image](https://user-images.githubusercontent.com/8066695/173731566-49779fb6-f9c5-4a6b-b02f-772a4c91c78a.png)
![image](https://user-images.githubusercontent.com/8066695/173731597-4208cba9-e502-46df-b0f3-925b98382d70.png)

### What you expected to happen

When the subtask complete,the parent workflow was supposed to be over, instead of being stucked.

### How to reproduce

I haven't found an accurate recurrence rule yet.

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qinxiang01** [comment]
It also appeared in version 2.0.5. Some tasks of the subprocess are submitted at the same time and fail almost at the same time.
![image](https://user-images.githubusercontent.com/23122196/175266654-2f3e7101-a9c9-46c6-b4ec-efad89c73b9a.png)

**Comment by ShawshankLin** [comment]
![企业微信截图_16590616367504](https://user-images.githubusercontent.com/16248686/181676892-ad864c56-2185-4b35-9bc5-fe512dd191ce.png)
When executing python-c scripts，The node status displayed here is successful, but the time is inconsistent with the log, and the time is even earlier

@SbloodyS @davidzollo

**Comment by ShawshankLin** [comment]
![image](https://user-images.githubusercontent.com/16248686/182107729-3675087a-f887-4a22-9111-634390f28a0f.png)
![image](https://user-images.githubusercontent.com/16248686/182107754-0ff7f171-238f-43e7-8dd4-109cdbb86f7d.png)
![image](https://user-images.githubusercontent.com/16248686/182107780-a4cbb287-304d-48e2-a567-416d1c0aca97.png)
cd '${file_path}'
 python -c "import test1;test1.get_task_instances('${project_code}','','','')" 

test1.py

`import sys,os
import requests
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    

def get_task_instances(project_code,process_Instance_Id="",task_name="",state_type=""):
    token = 'ac87b6898942649eca6008addb153ac4'
    addr = "127.0.0.1:12345"
    process_instances_url='http://{addr}/dolphinscheduler/projects/{projectCode}/task-instances'
    headers = {
        "token": token,
        "accept": "application/json; charset=utf-8"
        }
    params={
        "projectCode":project_code, \
        "processInstanceId":process_Instance_Id, \
        "taskName":task_name,\
        "stateType":state_type,
        "pageNo":1, "pageSize":1000000}
    url = process_instances_url.format(addr=addr,projectCode=project_code)
    res= requests.get(url,params=params,headers=headers)
    result = res.json()
    print('任务实例get_task_instance_by_id',len(result))
    if result['code']==0 and result['data']:
        return result['data']['totalList']
    else:
        raise ValueError('查询工作流实例失败')

`

![image](https://user-images.githubusercontent.com/16248686/182107850-b1e5426e-1079-4568-ad07-ab47923d11e4.png)
sleep 10
echo '1111'

**Comment by luoxiqiang** [comment]
This situation will occur when multiple master nodes are deployed, but will not occur when a single Master node is deployed

**Comment by ShawshankLin** [comment]
But this is a single machine, deployment mode is pseudo cluster

**Comment by luoxiqiang** [comment]
**Description Error logs in the master server**
![image](https://user-images.githubusercontent.com/32994527/182838405-6f138ab7-538d-4652-949c-22c9197987a6.png)
**Sometimes the subprocess stays in execution and sometimes it stays in a successful commit state**
![image](https://user-images.githubusercontent.com/32994527/182839201-255387aa-5296-47b9-94f5-daf8a0bd9617.png)
**However, the tasks of each subprocess have already been executed**
![image](https://user-images.githubusercontent.com/32994527/182839595-d8c8221e-37b1-486b-850d-bed0a2821572.png)
**The data host column in the task instance is empty while the subprocess remains in the committed success state**
![image](https://user-images.githubusercontent.com/32994527/182840027-1d85ced2-3694-481f-9570-022ec376e5a8.png)

**The operating environment is a multi-Master node**

**Comment by ShawshankLin** [comment]
Is this a bug？

**Comment by ShawshankLin** [comment]
![企业微信截图_16597785811144](https://user-images.githubusercontent.com/16248686/183243501-cc9d7554-87c9-487a-b07f-4a015051bc92.png)

**Comment by luoxiqiang** [comment]
Your problem may be caused by an event handling exception that causes the event queue to block and the subprocess status check event to go unprocessed, which is what happened in mine, so far I've solved and suggested optimization to the community
https://github.com/apache/dolphinscheduler/issues/11388#issue-1334131095
