### ISSUE TITLE
[Bug] [ui] 3.0.0-beta version ui-data source editing-test connection

### ISSUE THREAD

**Issue by 274574162** [apache/dolphinscheduler#10441]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

创建数据源为表单参数测试连接
修改数据源测试连接应该传数据源id测试,后端已提供接口,但并未使用

### What you expected to happen

修改数据源-连接不上

### How to reproduce

编辑数据源-测试连接

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please describe in english. I'll close this issue. Feel free to reopen it when correct it to english.
