### ISSUE TITLE
[Improvement][UI] Rearrange the columns in workflow definition page

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#10465]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* `Schedule Publish Status` is a very import attribute for a workflow. However, users need to scroll to the rightest to see this column. Maybe we could put it right next to `Status` column.

![image](https://user-images.githubusercontent.com/34905992/173829562-7c694589-5110-4113-9921-3d9bf47560e1.png)
![image](https://user-images.githubusercontent.com/34905992/173829602-721a6047-d292-415b-8ea3-c5e88728e8c1.png)

### Use case

* Already described above.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
It would be better if we make this be configurable.

**Comment by EricGao888** [comment]
> It would be better if we make this be configurable.

Sounds pretty cool.
