### ISSUE TITLE
[Feature]Shared resource files are expected to support FTP storage, and HDFS is rarely used for small-scale deployment

### ISSUE THREAD

**Issue by shaowei3384** [apache/dolphinscheduler#1046]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dailidong** [comment]
please update/add title in english! thx!

**Comment by dailidong** [comment]
@Baoqi please answer this issue!

**Comment by Baoqi** [comment]
Currently, we don't support FTP as a storage. For single machine deployment, you can use local file system.  For multiple node setup, you can try https://github.com/minio/minio ,  those 2 storage are supported.

**Comment by chengshiwen** [comment]
Close since no updates for long time
