### ISSUE TITLE
[Improvement][API] Refactor TenantController

### ISSUE THREAD

**Issue by seedscoder** [apache/dolphinscheduler#10467]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- createTenant
- queryTenantlistPaging
- queryTenantlist
- updateTenant
- deleteTenantById
- verifyTenantCode

### Related issues

#10257

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @seedscoder ,Do you want to participate in API refactoring?

**Comment by ruanwenjun** [comment]
@SbloodyS Do we need to add this issue to the subtask of #10257?

**Comment by seedscoder** [comment]
> 

@SbloodyS Yes

**Comment by SbloodyS** [comment]
> @SbloodyS Do we need to add this issue to the subtask of #10257?

Sure. I'll add it.

**Comment by SbloodyS** [comment]
@seedscoder I've assingned to you. Looking forward to your contribution.
