### ISSUE TITLE
When pre-tasks are completed, the downstream task instance is not triggered to execute, and master throw a NullPointException

### ISSUE THREAD

**Issue by wanghaizhou** [apache/dolphinscheduler#10474]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When pre-tasks are completed, the downstream task instance is not triggered to execute, and master throw a NullPointException.
This is an accidental phenomenon，when I restart the failed pre-task.
![image](https://user-images.githubusercontent.com/8066695/174022691-d711d9b1-1ad9-4522-b83f-f02de013e776.png)
![image](https://user-images.githubusercontent.com/8066695/174022736-25a1b751-a189-4be7-b17c-484443b13922.png)
![image](https://user-images.githubusercontent.com/8066695/174023076-82d2ebb5-1035-439c-9ff8-ed0e1ef1c6db.png)

### What you expected to happen

When pre-tasks are completed, the downstream task should execute.

### How to reproduce

When the pre-task fail, I restart the task. 
When the task was completed successfully, the downstream task instance is not triggered to execute.
This is an accidental phenomenon.

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @wanghaizhou , could you describe the steps to create the workflow's task? I can't reproduce this problem.

**Comment by wanghaizhou** [comment]
I found the trigger condition!The subtask has two Pre task, one for forbidden task and one for failed task. when we restart the failed task, the subtask do not run after the failed task complete, and the workflow stuck.
We can resolve the problem by remove the forbidden task from the subtask's Pre tasks.
![image](https://user-images.githubusercontent.com/8066695/174220041-7c6f55a8-4de1-44c3-a385-4d3609f44fda.png)

![image](https://user-images.githubusercontent.com/8066695/174219922-e9427b2f-a102-4ec9-ae81-da7c01607234.png)


> Hi @wanghaizhou , could you describe the steps to create the workflow's task? I can't reproduce this problem.

**Comment by wanghaizhou** [comment]
This is workflow's json file,you can reproduce this problem by  Importing this workflow‘s json file :

[{"processDefinition":{"id":178,"code":5859724125824,"name":"补数中途失败任务","version":13,"releaseState":"ONLINE","projectCode":4886418501504,"description":"","globalParams":"[]","globalParamList":[],"globalParamMap":{},"createTime":"2022-06-14 12:24:54","updateTime":"2022-06-17 02:41:37","flag":"YES","userId":1,"userName":null,"projectName":null,"locations":"[{\"taskCode\":5859705409792,\"x\":330,\"y\":260},{\"taskCode\":5888265830272,\"x\":679,\"y\":260},{\"taskCode\":5888273259392,\"x\":320,\"y\":60},{\"taskCode\":5888295530496,\"x\":987,\"y\":260},{\"taskCode\":5888279559808,\"x\":330,\"y\":-59}]","scheduleReleaseState":null,"timeout":0,"tenantId":2,"tenantCode":null,"modifyBy":null,"warningGroupId":0,"executionType":"PARALLEL"},"processTaskRelationList":[{"id":4691,"name":"","processDefinitionVersion":13,"projectCode":4886418501504,"processDefinitionCode":5859724125824,"preTaskCode":0,"preTaskVersion":0,"postTaskCode":5859705409792,"postTaskVersion":2,"conditionType":"NONE","conditionParams":{},"createTime":"2022-06-17 02:41:37","updateTime":"2022-06-17 02:41:37","operator":1,"operateTime":"2022-06-17 02:41:37"},{"id":4692,"name":"","processDefinitionVersion":13,"projectCode":4886418501504,"processDefinitionCode":5859724125824,"preTaskCode":0,"preTaskVersion":0,"postTaskCode":5888273259392,"postTaskVersion":1,"conditionType":"NONE","conditionParams":{},"createTime":"2022-06-17 02:41:37","updateTime":"2022-06-17 02:41:37","operator":1,"operateTime":"2022-06-17 02:41:37"},{"id":4693,"name":"","processDefinitionVersion":13,"projectCode":4886418501504,"processDefinitionCode":5859724125824,"preTaskCode":0,"preTaskVersion":0,"postTaskCode":5888279559808,"postTaskVersion":2,"conditionType":"NONE","conditionParams":{},"createTime":"2022-06-17 02:41:37","updateTime":"2022-06-17 02:41:37","operator":1,"operateTime":"2022-06-17 02:41:37"},{"id":4694,"name":"","processDefinitionVersion":13,"projectCode":4886418501504,"processDefinitionCode":5859724125824,"preTaskCode":5888265830272,"preTaskVersion":1,"postTaskCode":5888295530496,"postTaskVersion":1,"conditionType":"NONE","conditionParams":{},"createTime":"2022-06-17 02:41:37","updateTime":"2022-06-17 02:41:37","operator":1,"operateTime":"2022-06-17 02:41:37"},{"id":4695,"name":"","processDefinitionVersion":13,"projectCode":4886418501504,"processDefinitionCode":5859724125824,"preTaskCode":5859705409792,"preTaskVersion":2,"postTaskCode":5888265830272,"postTaskVersion":1,"conditionType":"NONE","conditionParams":{},"createTime":"2022-06-17 02:41:37","updateTime":"2022-06-17 02:41:37","operator":1,"operateTime":"2022-06-17 02:41:37"},{"id":4696,"name":"","processDefinitionVersion":13,"projectCode":4886418501504,"processDefinitionCode":5859724125824,"preTaskCode":5888279559808,"preTaskVersion":2,"postTaskCode":5888265830272,"postTaskVersion":1,"conditionType":"NONE","conditionParams":{},"createTime":"2022-06-17 02:41:37","updateTime":"2022-06-17 02:41:37","operator":1,"operateTime":"2022-06-17 02:41:37"},{"id":4697,"name":"","processDefinitionVersion":13,"projectCode":4886418501504,"processDefinitionCode":5859724125824,"preTaskCode":5888273259392,"preTaskVersion":1,"postTaskCode":5888265830272,"postTaskVersion":1,"conditionType":"NONE","conditionParams":{},"createTime":"2022-06-17 02:41:37","updateTime":"2022-06-17 02:41:37","operator":1,"operateTime":"2022-06-17 02:41:37"}],"taskDefinitionList":[{"id":1346,"code":5859705409792,"name":"测试1","version":2,"description":"","projectCode":4886418501504,"userId":1,"taskType":"PYTHON","taskParams":{"localParams":[],"rawScript":"print('1')\r\nif '2022-06-13' == '$[yyyy-MM-dd]':\r\n    raise Exception(\"Invalid level!\")\r\nelse:\r\n     print(\"=======$[yyyy-MM-dd]\")   ","resourceList":[]},"taskParamList":[],"taskParamMap":null,"flag":"YES","taskPriority":"MEDIUM","userName":null,"projectName":null,"workerGroup":"default","environmentCode":4997587042048,"failRetryTimes":0,"failRetryInterval":1,"timeoutFlag":"CLOSE","timeoutNotifyStrategy":null,"timeout":0,"delayTime":0,"resourceIds":"","createTime":"2022-06-14 12:24:54","updateTime":"2022-06-14 12:51:01","modifyBy":null,"taskGroupId":0,"taskGroupPriority":0,"operator":1,"operateTime":"2022-06-14 12:51:01"},{"id":1359,"code":5888265830272,"name":"test1","version":1,"description":"","projectCode":4886418501504,"userId":1,"taskType":"SUB_PROCESS","taskParams":{"localParams":[],"resourceList":[],"processDefinitionCode":5803335679744},"taskParamList":[],"taskParamMap":null,"flag":"YES","taskPriority":"MEDIUM","userName":null,"projectName":null,"workerGroup":"default","environmentCode":4997587042048,"failRetryTimes":0,"failRetryInterval":1,"timeoutFlag":"CLOSE","timeoutNotifyStrategy":null,"timeout":0,"delayTime":0,"resourceIds":"","createTime":"2022-06-17 02:23:50","updateTime":"2022-06-17 02:23:50","modifyBy":null,"taskGroupId":0,"taskGroupPriority":0,"operator":1,"operateTime":"2022-06-17 02:23:50"},{"id":1360,"code":5888273259392,"name":"test2","version":1,"description":"","projectCode":4886418501504,"userId":1,"taskType":"SHELL","taskParams":{"localParams":[],"rawScript":"echo '1'","resourceList":[]},"taskParamList":[],"taskParamMap":null,"flag":"NO","taskPriority":"MEDIUM","userName":null,"projectName":null,"workerGroup":"default","environmentCode":-1,"failRetryTimes":0,"failRetryInterval":1,"timeoutFlag":"CLOSE","timeoutNotifyStrategy":null,"timeout":0,"delayTime":0,"resourceIds":"","createTime":"2022-06-17 02:23:50","updateTime":"2022-06-17 02:23:50","modifyBy":null,"taskGroupId":0,"taskGroupPriority":0,"operator":1,"operateTime":"2022-06-17 02:23:50"},{"id":1363,"code":5888295530496,"name":"test1_2nm","version":1,"description":"","projectCode":4886418501504,"userId":1,"taskType":"SUB_PROCESS","taskParams":{"localParams":[],"resourceList":[],"processDefinitionCode":5803335679744},"taskParamList":[],"taskParamMap":null,"flag":"YES","taskPriority":"MEDIUM","userName":null,"projectName":null,"workerGroup":"default","environmentCode":4997587042048,"failRetryTimes":0,"failRetryInterval":1,"timeoutFlag":"CLOSE","timeoutNotifyStrategy":null,"timeout":0,"delayTime":0,"resourceIds":"","createTime":"2022-06-17 02:26:05","updateTime":"2022-06-17 02:26:05","modifyBy":null,"taskGroupId":0,"taskGroupPriority":0,"operator":1,"operateTime":"2022-06-17 02:26:05"},{"id":1365,"code":5888279559808,"name":"test3","version":2,"description":"","projectCode":4886418501504,"userId":1,"taskType":"PYTHON","taskParams":{"localParams":[],"rawScript":"print('1')","resourceList":[]},"taskParamList":[],"taskParamMap":null,"flag":"YES","taskPriority":"MEDIUM","userName":null,"projectName":null,"workerGroup":"default","environmentCode":4997587042048,"failRetryTimes":0,"failRetryInterval":1,"timeoutFlag":"CLOSE","timeoutNotifyStrategy":null,"timeout":0,"delayTime":0,"resourceIds":"","createTime":"2022-06-17 02:23:50","updateTime":"2022-06-17 02:36:22","modifyBy":null,"taskGroupId":0,"taskGroupPriority":0,"operator":1,"operateTime":"2022-06-17 02:36:22"}],"schedule":null}]

**Comment by SbloodyS** [comment]
I'll take a look at this today or tomorrow. Thanks. @wanghaizhou

**Comment by SbloodyS** [comment]
This have been fixed in dev branch. Could you try to find out if the dev branch still has this problem? @wanghaizhou 

![](https://vip2.loli.io/2022/06/17/dFDL8pAV14zytoY.png)

**Comment by wanghaizhou** [comment]
Thanks, the problem is solved in 3.0.0-beta-2.
