### ISSUE TITLE
Flink component version selection problem

### ISSUE THREAD

**Issue by Achilles1996** [apache/dolphinscheduler#10485]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![搜狗截图20220617110352](https://user-images.githubusercontent.com/51429792/174216590-2682e20b-dafa-4965-90c6-d616add07ef4.png)

Repeat back to version <1.10 when reopening  When going online or offline

### What you expected to happen

change it

### How to reproduce

Repeat back to version <1.10 when reopening  When going online or offline

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
@Amy0104 @songjianet Could you please take a look at this issue?

**Comment by Amy0104** [comment]
I will fix it.

**Comment by Amy0104** [comment]
It is not reproduced on branch 3.0.0-beta-1-release. Could you provide more details on the operation? @Achilles1996
