### ISSUE TITLE
[Feature][alert] Get notification of task/job/workflow changes

### ISSUE THREAD

**Issue by ghost** [apache/dolphinscheduler#10482]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Report job/ Task/Workflow changes to DingTalk and Teams in time. The key point：change time、change content、updated user、project/workflow/job name  And other key information。

### Use case

Monitoring alarm ，Notifications of changes can be obtained uniformly

### Related issues

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
I can support this pr, but this is my first time to dolphinscheduler and it would be nice to have some guidance.

**Comment by ghost** [comment]
Thanks, if need something in  Ideas  ,u can connect me 。not good at  coding in DS。

**Comment by stalary** [comment]
I can't find how the alter server is invoked, can you give me an example？

**Comment by fuchanghai** [comment]
@yahuili1128  什么时候触发告警呢？workflow 有17个状态呢。每个状态变更都需要吗？

**Comment by fuchanghai** [comment]
@yahuili1128 When will the alert be triggered? The workflow has 17 states. Is every state change required?

**Comment by yan-yunfeng** [comment]
Was this issue closed？
if not ,i am glade to make my first contribution
and if someone is willing to guide me, it will help me a lot

**Comment by EricGao888** [comment]
This is an interesting feature. However, as we need to notify users on state change, we need to add some code into core modules to support it. If we handle this inappropriately, it could be really hard to maintain and cause potential critical bugs. Therefore, I do not suggest we do this unless we have a good design.
