### ISSUE TITLE
[Discuss][Master] Add workflow status change log

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#10496]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When I do troubleshooting in master, I read the master's log, I find it is diffiicult to find out the whole log related to a specific workflowInstance or taskInstance. 

This is due to the process to execute a workflow is complex, and we didn't use a standard log format. In somewhere, we don't log the workflowInstanceId and does log the correct message.

I have two idea to collect the log:
1. Add prefix in master to collect the log of each workflow.
We can add the WorkflowInstanceId and taskInstanceId(If present) in the log event begin, so that we can find the log belong to one specific WorkflowInstance.
```
[INFO] 2022-06-18 13:09:30.683 +0800 org.apache.xx:[100] WorkflowInstanceId-123-taskInstanceId-1: WorkflowInstance submit thread pool success.
```
2. Generate workflow instance log for each WorkflowInstance, just like task log, we can generate log file to store the workflow instance's running log. 

Or is there a better way to connect the log?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I'm in favor of the first plan.
