### ISSUE TITLE
[Improvement] [API] Resource center API Optimization

### ISSUE THREAD

**Issue by EricPyZhou** [apache/dolphinscheduler#10495]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This optimization will be applied to the resource center API and is also part of the [OSPP event](https://summer-ospp.ac.cn/#/org/prodetail/222290456). At the end of the event, the resource center API will mostly depend on the third-party API. relations about tasks and resources will be the only information stored in t_ds_resources.

Future work on refactoring will be considered upon completion of this issue.

### Related issues

[Resource center optimization](https://github.com/apache/dolphinscheduler/discussions/9723#discussioncomment-2637061)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
does we will totally remove table `t_ds_resource` in the end?

**Comment by EricPyZhou** [comment]
> does we will totally remove table `t_ds_resource` in the end?

In the end, yes. But for now, we will keep it for backward compatibility. A new table `t_ds_relation_resources_task` is dedicated to storing resources used by tasks in online workflows.
