### ISSUE TITLE
UI error occurs during deployment and access

### ISSUE THREAD

**Issue by faith1112** [apache/dolphinscheduler#10497]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

DolphinScheduler deployment document: "index.2b31b589.js:1 Uncaught TypeError: S. replaceAll is not a function" error, page blank

![image](https://user-images.githubusercontent.com/38829476/174428449-65d38b19-aae5-48f1-9d11-2f409dd8f4b1.png)

![image](https://user-images.githubusercontent.com/38829476/174428463-5b59a7a2-dd6a-4763-9a30-87dc3bf6a6dc.png)

### What you expected to happen

Deployment Normal Access

### How to reproduce

https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/guide/installation/pseudo-cluster.html

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
This is because your browser version does not support it. You can use the last version of chrome.
