### ISSUE TITLE
[Feature][Security] Add data masking feature

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#10498]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Currently we don't have `data masking` mechanism in `DS` to hide sensitive data, such as AK for users.

### Use case

* Add `data masking` for sensitive data / parameters in `task plugin` or `datasource`.
* Users will not be able to explicitly print sensitive data in logs.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good suggestion
