### ISSUE TITLE
[Improvement][Server] Refactor HeartBeatTask and HeartBeat

### ISSUE THREAD

**Issue by guoshupei** [apache/dolphinscheduler#10506]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- Add parameter of  `workerWaitingTaskCount` to constractor of `HeartBeat`

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
I hope we can split the `HeartBeatTask` into `MasterHeartBeatTask` and `WorkerHeartBeatTask`, we may have more heart beat info will be added into HeartBeat.

**Comment by guoshupei** [comment]
> 



> I hope we can split the `HeartBeatTask` into `MasterHeartBeatTask` and `WorkerHeartBeatTask`, we may have more heart beat info will be added into HeartBeat.

Okay, then I won't change it for now and not submit PR.

**Comment by guoshupei** [comment]
@ruanwenjun  the dev branch, `workerWaitingTaskCount` of `HeartBeatTask` cannot be changed, it is a bug
![image](https://user-images.githubusercontent.com/29919212/174535244-23fcdf0c-32e6-4153-925e-d7fa1d56efdd.png)

**Comment by ruanwenjun** [comment]
> > 
> 
> > I hope we can split the `HeartBeatTask` into `MasterHeartBeatTask` and `WorkerHeartBeatTask`, we may have more heart beat info will be added into HeartBeat.
> 
> Okay, then I won't change it for now and not submit PR.

You can submit PR to fix this, I just hope you can split the HeartBeatTask together.

**Comment by guoshupei** [comment]
got it

**Comment by guoshupei** [comment]
Hi @ruanwenjun ,I think add `MasterHeartBeat` and `WorkerHeartBeat` to extends `HeartBeat` is better, the `HeartBeatTask` is only responsible for executing different `HeartBeat`.  what do you think?

**Comment by ruanwenjun** [comment]
> Hi @ruanwenjun ,I think add `MasterHeartBeat` and `WorkerHeartBeat` to extends `HeartBeat` is better, the `HeartBeatTask` is only responsible for executing different `HeartBeat`. what do you think?

Yes, LGTM.
