### ISSUE TITLE
[Feature][Test Case] Shell type test cases

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#10512]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

#### English template
| Level 1 module | Level 2 module | Test the scenario | Data / Steps | expected | level | automation|
| --- | --- | --- | --- |--- |--- |--- |
| Task-related | Main process | Successfully created normal task | Script: echo 123 Other parameters: Default |The run was successful The log shows echo 123 |P0| Yes |
| Task-related | Node name | Failed to create name, example: super long | Name: 68 Chinese characters (upper limit is varchar(200) / 3=67 Chinese characters), other parameters: default |Setup failed, prompted |P0| Yes |

#### Chinese template
| 1级模块 | 2级模块 | 测试场景 | 数据/步骤 | 期望 | 级别 | 是否需自动化 |
| --- | --- | --- | --- |--- |--- |--- |
1级模块|2级模块|测试场景 |数据 / 步骤 |预期|级别|自动化|
任务相关|主流程验证|成功 创建普通任务|脚本：echo 123, 其他参数：默认|运行成功,日志展示 echo 123|P0|是|
任务相关|节点名称|失败创建名称，例：超长|名称：存放68个汉字 （上限是varchar(200) / 3=67汉字），其他参数：默认|设置失败，给出提示|P2|否|
任务相关|节点名称|失败创建名称，例：重复|名称：wen （wen已经存在），其他参数：默认|设置失败，给出提示|P2|否|
任务相关|节点名称|失败创建名称，例：空|名称：，其他参数：默认|设置失败，给出提示|P2|否|
任务相关|节点名称|成功创建名称，例：task任务|名称：task任务，其他参数：默认|设置成功|P2|否|
任务相关|节点名称|成功设置节点名称，例：极限值|名称：存放67个汉字，其他参数：默认|设置成功|P2|否|
任务相关|节点名称|成功设置节点名称，例：常规值|名称：test节点，其他参数：默认|设置成功|P0|是|
任务相关|节点名称|创建成功的名称不可被修改|创建名称：wen2（原值：wen），其他参数：默认|wen不能被修改|P1|否|
任务相关|运行标志|成功创建「启用」shell 任务，且运行成功|名称：启用shell，脚本：echo 123，标志：启用，其他参数：默认|创建成功、运行成功|P0|是|
任务相关|运行标志|成功创建「禁用」shell 任务|名称：禁用shell,,脚本：echo 123,,标志：启用,,其他参数：默认,|创建成功|P0|是|
|||||||
||||运行失败|||
任务相关|运行标志|成功「启用」修改「禁用」任务|名称：修改shell1,,脚本：echo 123,,标志：禁用（原值：启用）,,其他参数：默认|修改成功|P1|否|
|||||||
||||运行失败|||
任务相关|运行标志|成功「禁用」修改「启用」任务|名称：修改shell2,,脚本：echo 123,,标志：启用（原值：禁用）,,其他参数：默认|修改成功|P1|否|
|||||||
||||运行成功|||
任务相关|描述|成功描述增加，例：描述123|名称：shell,,描述：描述123,,其他参数：默认|创建成功|P2|否|
任务相关|描述|成功修改描述，例：描述123修改成 描述456|名称：shell,,描述：描述456（原：描述123）,,其他参数：默认|修改成功|P2|否|
任务相关|描述|成功描述增加，例：空|名称：shell,,描述：,,其他参数：默认|创建成功|P0|是|
任务相关|描述|成功描述增加，例：临界值|名称：shell,,描述：21844汉字（上限是text类型，65535）,,其他参数：默认|创建成功|P2|否|
任务相关|描述|失败描述增加，例：超长|名称：shell,,描述：21845汉字（上限是text类型，65535）,,其他参数：默认|创建失败，给出提示：超长|P2|否|
任务相关|任务优先级|成功创建每种优先级|名称：shell, 优先级：依次创建 highest / high / medium / low /lowest, 其他参数：默认|均创建成功|P1|否|
任务相关|任务优先级|5个任务，其中1个Highest 优先被执行|名称：shell1-5（说明：创建shell1-5）,优先级：1-5（说明：对应优先级highest 到 lowest）, 执行顺序：并行执行, 其他条件：master 线程数不足为1时|shell1优先被执行|P0|是|
任务相关|任务优先级|5个任务，其中1个Lowest 最后被执行|名称：shell1-5（说明：创建shell1-5）,优先级：1-5（说明：对应优先级highest 到 lowest）,执行顺序：并行执行, 其他条件：master 线程数不足为1时|shell5最后被执行|P1|否|
任务相关|任务优先级|5个任务，1个Highest+4个medium，Highest改成Lowest，被最后执行|名称：shell1-5（说明：创建shell1-5）, 优先级：1-5（说明：1个highest改成lowest,4个medium）, 执行顺序：并行执行, 其他条件：master 线程数不足为1时|shell1最后被执行|P1|否|
任务相关|worker分组|默认worker组且任务运行成功|名称：shell, worker分组：default (对应ip：10.10.10.1), 其他参数：默认|worker在10.10.10.1上执行|P0|是|
任务相关|worker分组|创建worker1组且任务运行成功|名称：shell, worker分组：worker1 (对应ip：10.10.10.2), 其他参数：默认|worker在10.10.10.2上执行|P1|否|
任务相关|worker分组|默认worker组修改成worker1，且任务运行成功|名称：shell , worker分组：worker2 (原值：worker1，现值worker2 对衣应ip 10.10.10.3), 其他参数：默认|修改成功,worker在10.10.10.3上执行|P1|否|
任务相关|环境名称|创建「环境名称」且生效，例：java_evn|名称：shell, 环境名称：java_evn, 环境脚本：echo "java evn", 其他参数：默认|运行成功,运行日志有 java evn|P0|是|
任务相关|环境名称|替换「环境名称」且生效，例：java_evn 换 python_evn|名称：shell, 环境名称：python_evn（原值: java_evn）, 环境脚本：echo "python evn", 其他参数：默认|运行成功, 运行日志有 python evn|P1|否|
任务相关|任务组名称|失败设置优先级，例：01|名称：shell, 任务组名称：wen（wen提前创建）, 组内优先级：01, 其他参数：默认|创建失败，提示：优先级必须是正整数|P2|否|
任务相关|任务组名称|失败设置优先级，例：0.1|名称：shell, 任务组名称：wen, 组内优先级：0.1, 其他参数：默认|创建失败，提示：优先级必须是正整数|P2|否|
任务相关|任务组名称|失败设置优先级，例：0|名称：shell, 任务组名称：wen, 组内优先级：0, 其他参数：默认|创建失败，提示：优先级必须是正整数|P2|否|
任务相关|任务组名称|失败设置优先级，例：-1|名称：shell, 任务组名称：wen, 组内优先级：-0, 其他参数：默认|创建失败，提示：优先级必须是正整数|P2|否|
任务相关|任务组名称|验证任务组优先级|名称：shell1-5（创建5个任务：shell1-shell5）, 任务组名称：wen1-5（创建5个组：wen1-wen5）, 组内优先级：1-5（对应5个优先级：1-5）, 其他参数：默认|运行该工作流下5个任务，shell1优先被执行|P0|是|
任务相关|任务组名称|验证修改任务功能|名称：shell1-5（创建5个任务：shell1-shell5）, 任务组名称：wen1-5（创建5个组：wen1-wen5）, 组内优先级：1-5（其中shell3与shell1优先级互换）, 其他参数：默认|运行该工作流下5个任务，shell3优先被执行|P1|否|
任务相关|任务组名称|通1个任务组不能拥有相同优先级|名称：shell1-2（创建2个任务：shell1、shell2）, 任务组名称：wen, 组内优先级：1, 其他参数：默认|创建失败，1个组内不能有相同优先级|P0|是|
任务相关|失败重试|失败设置，例：负数|失败重试次数：-1, 失败重试间隔：-1, 其他参数：默认|失败设置，提示：必须填写正整数|P2|否|
任务相关|失败重试|失败设置，例：非整数|失败重试次数：0.1, 失败重试间隔：1, 其他参数：默认|失败设置，提示：必须填写正整数|P2|否|
任务相关|失败重试|失败设置，例：字母|失败重试次数：a, 失败重试间隔：1, 其他参数：默认|失败设置，提示：必须填写正整数|P2|否|
任务相关|失败重试|失败设置，例：特殊字符|失败重试次数：@#¥%, 失败重试间隔：@#¥%, 其他参数：默认|失败设置，提示：必须填写正整数|P2|否|
任务相关|失败重试|失败设置，例：空|失败重试次数：, 失败重试间隔：, 其他参数：默认|失败设置，提示：必须填写正整数|P2|否|
任务相关|失败重试|失败设置，例：超长|失败重试次数：123456789012 (即：int(11)), 失败重试间隔：123456789012 (即：int(11)), 其他参数：默认|失败设置，提示：必须填写11区间内正整数|P2|否|
任务相关|失败重试|成功设置，例：边界值|失败重试次数：99999999999 (即：int(11)）, 失败重试间隔：99999999999 (即：int(11)）, 其他参数：默认|成功设置|P1|否|
任务相关|失败重试|成功设置，例：非整数，且任务运行重试生效|失败重试次数：1, 失败重试间隔：0.1, 其他参数：默认|成功设置，且重试按配置运行成功|P1|否|
任务相关|失败重试|成功设置，且任务运行重试生效|失败重试次数：1, 失败重试间隔：1, shell脚本：sleep -1, 其他参数：默认|成功设置，且重试按配置运行成功|P0|是|
任务相关|失败重试|成功累加，且任务运行重试生效|失败重试次数：1 累加成 2, 失败重试间隔：1 累加成 2, shell脚本：sleep -1, 其他参数：默认|成功设置，且重试按配置运行成功|P1|否|
任务相关|延迟执行时间|失败设置「时间」，例：负数|延迟执行时间：-1, 其他参数：默认|失败设置，提示：必须正数|P2|否|
任务相关|延迟执行时间|失败设置「时间」，例：字母|延迟执行时间：-1, 其他参数：默认|失败设置，提示：必须正数|P2|否|
任务相关|延迟执行时间|失败设置「时间」，例：空|延迟执行时间：, 其他参数：默认|失败设置，提示：必须正数|P2|否|
任务相关|延迟执行时间|失败设置「时间」，例：特殊字|延迟执行时间：@#¥%！, 其他参数：默认|失败设置，提示：必须正数|P2|否|
任务相关|延迟执行时间|失败设置「时间」，例：超长|延迟执行时间：99999999999 (即：int(11)）, 其他参数：默认|失败设置，提示：必须11位以内正数|P2|否|
任务相关|延迟执行时间|成功设置「时间」，例：临界值|延迟执行时间：9999999999 (即：int(11)）, 其他参数：默认|成功设置|P1|否|
任务相关|延迟执行时间|成功设置「时间」，例：常规值|延迟执行时间：3 , 其他参数：默认|成功设置,且延迟3分钟执行|P0|是|
任务相关|超时告警|成功开启告警，例：超时告警|任务A、B在1个DAG内, 任务A, 超时策略：超时告警, 超时时长：1, 脚本：sleep 120, 任务B, 前置任务：任务A, 超时策略：关闭,脚本：echo 123|任务A被执行，且发送告警, 任务B被执行, 收到告警|P0|是|
任务相关|超时告警|成功开启告警，例：超时失败|任务A、B在1个DAG内, 任务A, 超时策略：超时失败, 超时时长：1, 脚本：sleep 120, 任务B, 前置任务：任务A, 超时策略：关, 脚本：echo 123|任务A执行失败, 任务B不被执行,收到告警|P1|否|
任务相关|超时告警|成功关闭告警|任务A、B在1个DAG内, 任务A, 超时策略：关闭（原值：开启）, 脚本：sleep 120, 任务B, 前置任务：任务A, 超时策略：关闭, 脚本：echo 123|任务A执行失败, 任务B被执行|P1|否|
任务相关|超时告警|失败开启告警|任务C, 超时策略：超时告警、超时失败 同时勾选, 脚本：sleep 120|保存失败，不能同时勾选|P1|否|
任务相关|脚本|成功运行脚本，例：常规值|脚本：echo "常规值123", 其他参数：默认|运行成功，日志输出：常规值123|P0|是|
任务相关|脚本|成功运行脚本，例：极限值|脚本：输入4294967294字符（longtext类型 4294967295, 其他参数：默认|运行成功|P1|否|
任务相关|脚本|成功运行脚本，例：任意值|脚本：大小写字母 / 中文 / 数字 / 特殊符号 / 全角 / 半角, /Javascript函数 / null / 空格的转义字符, 其他参数：默认|运行成功，以上输入值被处理|P2|否|
任务相关|脚本|失败运行脚本，例：超长|脚本：输入4294967295字符, 其他参数：默认|保存失败，提示：超长|P2|否|
任务相关|脚本|失败运行脚本，例：空|脚本：, 其他参数：默认|保存失败，提示：请输入脚本|P2|否|
任务相关|脚本-参数传递|成功设置内置参数|脚本：echo ${data},,echo ${curdate},,echo ${datetime},,自定义参数：,,data in varchar ${system.biz.date},,curdate in varchar ${system.biz.curdate},,datetime in varchar ${system.datetime},,其他参数：默认|输出：echo 20220523，date为昨天时间, 输出 echo 20220524，curdate为今天时,输出 echo  20220524054256，datetime为今天时间|P0|是|
任务相关|脚本-参数传递|成功设置自定义参数，例：常规值-正数|脚本：,,echo ${p1},,...,,echo ${p10},,自定义参数：,,p1 in varchar abc,,p2 in integer 123,,p3 in long 123,,p4 in float 123.33,,P5 in double 123.33,,P6 in date 2022-06-18,,P7 in time 2022-06-18 23:59:59,,P8 in timestamp 1655538892,,P9 in boolean true,,P10 in list [1,2,3],,其他参数：默认|设置成功，运作生效|P0|是|
任务相关|脚本-参数传递|成功设置自定义参数，例：常规值-负数|脚本：,,echo ${p1},,...,,echo ${p10},,自定义参数：,,p1 in varchar abc,,p2 in integer -123,,p3 in long -123,,p4 in float -123.33,,P5 in double -123.33,,P6 in date 2022-06-18,,P7 in time 2022-06-18 23:59:59,,P8 in timestamp 1655538892,,P9 in boolean true,,P10 in list [1,2,3],,其他参数：默认|设置成功，运作生效|P0|是|
任务相关|脚本-参数传递|成功设置自定义参数，例：极限值|脚本：,,echo ${p1},,...,,echo ${p10},,自定义参数：,,p1 in varchar 0 到 65535字符,,p2 in integer -+2147483647,,p3 in long -+9223372036854775808L,,p4 in float -3.4E+38F,,P5 in double +/-1.8E+308,,P6 in date 1000-01-01 到 9999-12-31,,P7 in time 1000-01-01 00:00:00 到 9999-12-31 23:59:59,,P8 in timestamp 19700101080001 到 20380119111407,,P9 in boolean 0，-0，null，false，NaN，undefined,,P10 in list [] ,,其他参数：默认|设置成功，运作生效|P1|否|
任务相关|脚本-参数传递|失败设置自定义参数，例：非匹配类型|脚本：,,echo ${p1},,...,,echo ${p10},,自定义参数：,,p1 in varchar  65536字符,,p2 in integer abc,,p3 in long abc,,p4 in float abc,,P5 in double abc,,P6 in date 2022//02//02,,P7 in time 2022//02//02 00//00//00,,P8 in timestamp abc,,P9 in boolean 123,,P10 in list [123,,其他参数：默认|设置失败，给出提示|P1|否|
任务相关|脚本-参数传递优先级|脚本内自定义参数只能设1次|脚本：,,echo ${p1},,自定义参数：,,p1 in varchar  abc,,p1 in varchar  efg |设置失败，给出提示: p1只能设置1个参数|P1|否|
任务相关|脚本-参数传递优先级|「脚本局部参数」高于「全局参数」优先级|脚本：echo ${p1},,自定义参数：p1 in varchar  abc,,全局变量：p1 in varchar  efg|p1输出值为abc|P1|否|
任务相关|脚本-参数传递优先级|「脚本局部参数」为空时「全局参数」生效|脚本：echo ${p1},,自定义参数：空,,全局变量：p1 in varchar  efg|p1输出值为efg|P1|否|
任务相关|资源|成功调用txt 后缀资源|脚本：cat test.txt, 资源：test.txt|运行成功，输出：echo 123|P1|否|
任务相关|资源|成功调用log 后缀资源|脚本：cat test.log, 资源：test.log|运行成功，输出：echo 123|P1|否|
任务相关|资源|成功调用sh 后缀资源|脚本：cat test.sh, 资源：test.sh|运行成功，输出：echo 123|P0|是|
任务相关|资源|成功调用conf 后缀资源|脚本：cat test.conf, 资源：test.conf|运行成功，输出：echo 123|P1|否|
任务相关|资源|成功调用py 后缀资源|脚本：cat test.py, 资源：test.py|运行成功，输出：echo 123|P1|否|
任务相关|资源|成功调用jar 后缀资源|脚本：cat test.jar, 资源：test.jar|运行成功，输出：echo 123|P0|是|
任务相关|资源|成功调用2个资源|脚本：cat test.jar; cat test.py, 资源：test.jar / test.py|运行成功，输出：echo 123 2次|P1|否|
任务相关|资源|失败调用非标准资源|脚本：cat test.123, 资源：test.123|运行失败，输出：非标准资源|P2|否|
任务相关|前置任务|任务A作为任务B前置任务|任务A,,脚本: echo 123,,任务B,,脚本: echo 456|运行成功，依次输出：123 456|P0|是|
任务相关|前置任务|任务A作为任务B、任务C前置任务|任务A,,脚本: echo 123,,任务B,,脚本: echo 456,, 任务C,,脚本: echo 789|运行成功，依次输出：123 先被输出，456、789随机输出|P1|否|
DAG页面配置|搜索|成功精准搜索1个任务，例：task1|搜索：task1|搜索成功，聚焦task1|P1|否|
DAG页面配置|搜索|成功取消搜索，例：空|搜索：|取消搜索成功，展现task1、task2、task3|P1|否|
DAG页面配置|下载工作流图片|成功下载DAG图片|下载|下载成功png格式的图片，能正常打开|P1|否|
DAG页面配置|删除|删除2条线||删除成功|P2|否|
DAG页面配置|删除|删除3个节点||删除成功|P2|否|
DAG页面配置|删除|删除3条线+2个节点||删除成功|P1|否|
DAG页面配置|格式化|全屏||全屏成功|P2|否|
DAG页面配置|格式化|格式化||格式化成功|P2|否|
DAG页面配置|版本|DAG内切换version5|共有10个版本, DAG内切换 version5|切换成功, DAG内下当前版本是：version5, 工作流下当前版本是：version5|P0|是|
DAG页面配置|版本|工作流内切换version3|共有10个版本, 工作流切换 version3|切换成功, DAG内下当前版本是：version3, 工作流下当前版本是：version3|P1|否|
DAG页面配置|版本|DAG内删除 version6|共有10个版本, DAG内删除 version6|删除成功, DAG内下：无version6, 工作流下：无version6|P0|是|
DAG页面配置|版本|工作流下删除 version4|共有10个版本, 工作流内删除 version4|删除成功, DAG内下：无version4, 工作流下：无version4|P1|否|
DAG页面配置|关闭|关闭|新增1个shell任务, 关闭|shell不会被保存|P1|否|
工作流保存|工作流名称|成功创建名称，例：常规值|工作流：workflow1|创建成功|P0|是|
工作流保存|工作流名称|成功创建名称，例：极限值|工作流：255 个字符|创建成功|P2|否|
工作流保存|工作流名称|失败创建名称，例：空|工作流：|创建失败，提示：必填|P2|否|
工作流保存|工作流名称|失败创建名称，例：超长|工作流：256个 字符|创建失败，提示：超长|P2|否|
工作流保存|工作流名称|失败创建名称，例：重复|工作流：workflow1（workflow1已经存在）|创建失败，提示：重复|P1|否|
工作流保存|工作流名称|失败创建名称，例：特殊字符|工作流：！@#¥%……&&*（）|创建失败，提示：特殊字符|P2|否|
工作流保存|描述|成功填写名称，例：描述123|描述：描述123|创建成功|P1|否|
工作流保存|描述|成功填写名称，例：极限值|描述：21844汉字（上限是text类型，65535）|创建成功|P2|否|
工作流保存|描述|成功填写名称，例：空|描述：|创建成功，描述可以为空|P2|否|
工作流保存|描述|失败填写名称，例：超长|描述：21845汉字（上限是text类型，65535）|创建失败，提示：超长|P2|否|
工作流保存|租户|成功使用 default租户|租户：default, 登录用户：admin, 登录用户对应租户：root|任务运行成功, 任务运行用户是root用户|P0|是|
工作流保存|租户|成功使用 user1租户|租户：user1 , user1对应租户：user1|任务运行成功, 任务运行用户是user1用户|P1|否|
工作流保存|租户|default租户修改成user2|租户：user2（原值：default）, user2对应租户：user2|任务运行成功, 任务运行用户是user2用户|P1|否|
工作流保存|超时告警|成功输入告警值，例：常规值|超时告警：2|创建成功, 2分钟内发生告警|P0|是|
工作流保存|超时告警|成功输入告警值，例：极限值|超时告警：99999999999（int11）|创建成功|P2|否|
工作流保存|超时告警|失败输入告警值，例：超长|超时告警：999999999999（int11）|创建失败，给出提示：超长|P2|否|
工作流保存|超时告警|失败输入告警值，例：负数|超时告警：-2|创建失败，给出提示：必须正整数|P2|否|
工作流保存|超时告警|失败输入告警值，例：非整数|超时告警：0.1|创建失败，给出提示：必须正整数|P2|否|
工作流保存|超时告警|失败输入告警值，例：空|超时告警：|创建失败，给出提示：必须正整数|P2|否|
工作流保存|超时告警|失败输入告警值，例：字母|超时告警：abc|创建失败，给出提示：必须正整数|P2|否|
工作流保存|超时告警|「脚本局部参数」高于「全局参数」优先级|任务中告警：2分钟, 保存时告警：1分钟|最终工作流2分钟发生告警|P1|否|
工作流保存|超时告警|「脚本局部参数」为空时「全局参数」生效|任务中告警：空, 保存时告警：1分钟|最终工作流1分钟发生告警|P1|否|
工作流保存|执行策略|多任务并行验证|1个工作流中包含10个shell任务，且无依赖任务, 执行策略：并行|10个任务并行执行|P0|是|
工作流保存|执行策略|多任务串行等待？|1个工作流中包含10个shell任务，且无依赖任务, 执行策略：串行等待|10个任务依次被执行|P0|是|
工作流保存|执行策略|多任务串行优先？|1个工作流中包含10个shell任务，且无依赖任务, 执行策略：串行优先|10个任务依次被执行|P0|是|

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
This is too complicated and I think we are not supposed to test almost everything in shell task plugin.
