### ISSUE TITLE
[Bug] [pseudo-cluster installation] Cannot load driver class: com.mysql.cj.jdbc.Driver

### ISSUE THREAD

**Issue by Chris-playground** [apache/dolphinscheduler#10513]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I followed the instruction strictly to perform a pseudo-cluster installation, and I added a `mysql-connector-java-8.0.16.jar` into the `tools/libs` directory and change the owner also.
However, I found that the installation program didn't dispatch the mysql-connector to all servers, and I try to add jar to each server manally, it worked.

Snapshots are attached below, thanks.
### mysql-connector
![image](https://user-images.githubusercontent.com/48941586/174560224-4b54e219-49ce-481b-8b90-d9397e5490c5.png)
### configuration
![image](https://user-images.githubusercontent.com/48941586/174560676-90f9cf87-d6e0-46b0-ba9f-ac883fcc2d36.png)
### logs
![image](https://user-images.githubusercontent.com/48941586/174561200-025b0644-94bc-4414-840b-bc027b3edb2d.png)
### master-server libs
![image](https://user-images.githubusercontent.com/48941586/174561297-9eab9a48-17a8-4a23-8493-11a2fd769a03.png)

### What you expected to happen

I think the installation program should dispatch the mysql-connector file to all the servers needed, but it didn't work.

### How to reproduce

As I described above.

### Anything else

Nil

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
It seems the tools dir is only used for `dolphinscheduler-tools` module? And we don't add the tools/lib into classpath when we start master/worker/api/xx. @SbloodyS

**Comment by SbloodyS** [comment]
> It seems the tools dir is only used for `dolphinscheduler-tools` module? And we don't add the tools/lib into classpath when we start master/worker/api/xx. @SbloodyS

Yes. Each module's lib is independent. We should optimize the document to tell users this. I'll fix it.

**Comment by wangzijian121** [comment]
Great, I also encountered this problem today, the version is 3.0.1, I just want to submit an issue, it seems that I just need to modify the document: first copy the jar to tools/libs, and then install~

**Comment by Chris-playground** [comment]
> Great, I also encountered this problem today, the version is 3.0.1, I just want to submit an issue, it seems that I just need to modify the document: first copy the jar to tools/libs, and then install~

that's correct, and remember each module's lib is independent, add according libs to each module when you need.

**Comment by SbloodyS** [comment]
> Great, I also encountered this problem today, the version is 3.0.1, I just want to submit an issue, it seems that I just need to modify the document: first copy the jar to tools/libs, and then install~

You are right. Would you like to submit a pr to fix the docs? :)

**Comment by wangzijian121** [comment]
> > Great, I also encountered this problem today, the version is 3.0.1, I just want to submit an issue, it seems that I just need to modify the document: first copy the jar to tools/libs, and then install~
> 
> You are right. Would you like to submit a pr to fix the docs? :)

I am willing to submit pr, but it seems that this submission has been [773e79,](https://github.com/apache/dolphinscheduler/commit/773ebc9e523d1190dcc31ce63878071d3d2847c1) which is exactly what I want to modify. Ha ha, I will continue to pay attention to the dolphinscheduler issue, thank you~
