### ISSUE TITLE
[Bug] [2.0.5] Some important bugs in version 2.0.5

### ISSUE THREAD

**Issue by brave-lee** [apache/dolphinscheduler#10517]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. Mac M1 starting master/worker is not supported
2. Deleting upstream dependency of task results in duplicate data in workflow task relation table
3. When there are multiple workers, the master distribution task will cause the worker task to accumulate
4. Master frequently prints logs
5. Worker frequently prints logs
6. When a workflow is stopped, child workflows and dependent nodes cannot be killed
7. When a task is not running, the dependent nodes that depend on the task are always running and waiting
8. When a failover occurs, the task retry not working
9. When deleting a task and workflow relationship, it is possible to trigger the problem of deleting other tasks and workflow relationships
10. Occasionally unable to get task status
11. The task in the occasionally issued sub workflow has been completed, and the sub workflow has been stuck

### What you expected to happen

No bugs

### How to reproduce

Already appears

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good job, and please one PR solves one issue, it will be easy for cherrying pick the PR

**Comment by lordk911** [comment]
also , when a task is running with a long time about more than one hour, the dependent nodes that depend on the task are always running and waiting
