### ISSUE TITLE
[Improvement] [docs] Complement add docs

### ISSUE THREAD

**Issue by hstdream** [apache/dolphinscheduler#10520]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Complement add docs

### What you expected to happen

Complement docs is need update

### How to reproduce

Update  complement docs

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
close #https://github.com/apache/dolphinscheduler/pull/10521
