### ISSUE TITLE
[Feature][Module Name] Feature titleThe amount of historical data is too large, including running logs, database data, historical task data, etc. Hope to support data cleaning or archiving before the time node

### ISSUE THREAD

**Issue by JVincerW** [apache/dolphinscheduler#10528]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
good idea!

**Comment by EricGao888** [comment]
@JVincerW Sounds cool. BTW, you could use [logrotate](https://www.baeldung.com/linux/rotating-logs-logrotate#:~:text=logrotate%20is%20a%20log%20managing,manage%20the%20matching%20log%20files.) to rotate logs in `Linux`.
