### ISSUE TITLE
依赖节点执行成功后可触发下级节点执行

### ISSUE THREAD

**Issue by liuping027** [apache/dolphinscheduler#1053]
使用场景：
B任务依赖A任务，A任务设定定时执行，当A任务定时执行成功后，自动触发B任务执行（只在定时执行状态能自动触发，手动执行可选择只执行当前任务或按依赖关系全部执行）

目的：
当任务间依赖复杂时，不需要根据先后顺序设置工作流的定时执行时间，方便开发及维护

**Comment by dailidong** [comment]
add title and description in english , thx

**Comment by wangsvip** [comment]
是的,这个问题很好,一个用户下可以建立多个项目,但是项目间是有依赖关系的,如果不能做依赖关系,只在同一个项目下工作,那分建不同的项目意义不大!
