### ISSUE TITLE
[Bug] [ui] bytesToSize 

### ISSUE THREAD

**Issue by xiaolannuoyi** [apache/dolphinscheduler#10543]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

bytesToSize(1) //  1 B
bytesToSize(1000) // 1 B   ???

### What you expected to happen

bytesToSize(1000) 
1000 B

### How to reproduce

bytesToSize(1000) 

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @xiaolannuoyi , could you describe it more clearly?

**Comment by xiaolannuoyi** [comment]
@SbloodyS  
 file in https://github.com/apache/dolphinscheduler/blob/dev/dolphinscheduler-ui/src/common/common.ts
<img width="1067" alt="截屏2022-06-22 19 44 48" src="https://user-images.githubusercontent.com/21079721/175021449-5e17789a-245c-4091-96f4-fee2b69289e0.png">

<img width="903" alt="截屏2022-06-22 19 47 39" src="https://user-images.githubusercontent.com/21079721/175021952-efc6e83e-47e8-4a9c-b4a7-a8d8eec1dd71.png">

**Comment by Amy0104** [comment]
Since the calculated data is rounded down, entering 1 or 1000 will give the same value.

**Comment by SbloodyS** [comment]
Would you like to submit a pr to fix this? @xiaolannuoyi

**Comment by xiaolannuoyi** [comment]
@SbloodyS 
look at this  
https://stackoverflow.com/questions/15900485/correct-way-to-convert-size-in-bytes-to-kb-mb-gb-in-javascript/18650828#18650828

**Comment by Amy0104** [comment]
Thx, I will fix it.
