### ISSUE TITLE
[Feature] Show sub-process task info in workflow definition page.

### ISSUE THREAD

**Issue by stalary** [apache/dolphinscheduler#10546]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I have defined several sub-workflows in Workflow, but their tasks are not displayed, so they have to jump to see them. Can we support direct expansion, so that we can see the situation of workflow intuitively. I can support this feature if it can do.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I've assigned to you. Looking forward to your contribution. @stalary

**Comment by stalary** [comment]
> I've assigned to you. Looking forward to your contribution. @stalary
I need a little help, How do I get the id of the sub-process from the parent project~

**Comment by stalary** [comment]
> I've assigned to you. Looking forward to your contribution. @stalary

I need a little help, How do I get the id of the sub-process from the parent project.

**Comment by SbloodyS** [comment]
> I need a little help, How do I get the id of the sub-process from the parent project.

I think you just want to display the sub-workflow's task in the workflow definition page. Is that correct?

**Comment by stalary** [comment]
parent-test
![截屏2022-06-22 下午10 12 23](https://user-images.githubusercontent.com/24592373/175051035-a96712a3-ae39-41a0-897c-cca7c0b13848.png)

child-test
![截屏2022-06-22 下午10 12 29](https://user-images.githubusercontent.com/24592373/175051020-25332179-468e-4c4b-a781-7c30317d8677.png)

I want to show test1, test2 in parent-test.

**Comment by stalary** [comment]
> I think you just want to display the sub-workflow's task in the workflow definition page. Is that correct?

yes.

**Comment by stalary** [comment]
I find sub-process processDefinitionCode in taskParams, I can use it?

**Comment by SbloodyS** [comment]
I think you just need to modify the front end.

1. You can get the `processDefinitionCode` of the sub workflow when you create the sub-process task.
2. Querying the sub workflow's detail throught `projects/{projectCode}/process-definition/{processDefinitionCode}`. Which is the api to open the workflow definition page.

**Comment by stalary** [comment]
> 2\. projects/{projectCode}/process-definition/{processDefinitionCode}

I found that currently DAG information is obtained through `projects/{projectCode}/process-definition/{processDefinitionCode}`. Do you mean that I need to traverse the task in the front end, judge the type and then call the backend interface in turn to obtain the sub-process information?

**Comment by stalary** [comment]
I see. Do you want the frontend to click and expand to show the details of the subtask?

**Comment by SbloodyS** [comment]
> I found that currently DAG information is obtained through `projects/{projectCode}/process-definition/{processDefinitionCode}`. Do you mean that I need to traverse the task in the front end, judge the type and then call the backend interface in turn to obtain the sub-process information?

What I think is to display the details of the sub workflows when configuring it. And it will disappear after configuration. 

If a DAG contains many sub process task and needs to show its details, this page will not hold all the contents.

If you have a better idea, you are welcome to put it forward.

**Comment by stalary** [comment]
Oh, my starting point is a little different from yours. For example, I currently have a base task with a number of sub-process tasks mounted downstream, and I want to see all the details of the downstream tasks clearly in the base task. The dolphinscheduler currently lacks a overall DAG of dependent tasks.

So it looks like this.
base task -> sub-task1 -> sub-task1-info1
                 -> sub-task2 -> sub-task2-info1

**Comment by stalary** [comment]
> > I found that currently DAG information is obtained through `projects/{projectCode}/process-definition/{processDefinitionCode}`. Do you mean that I need to traverse the task in the front end, judge the type and then call the backend interface in turn to obtain the sub-process information?
> 
> What I think is to display the details of the sub workflows when configuring it. And it will disappear after configuration.
> 
> If a DAG contains many sub process task and needs to show its details, this page will not hold all the contents.
> 
> If you have a better idea, you are welcome to put it forward.

At present, we need to click `enter this child node` to see the details of subtasks, but sometimes we need to see the information of multiple subtasks DAG intuitively.

**Comment by SbloodyS** [comment]
> Oh, my starting point is a little different from yours. For example, I currently have a base task with a number of sub-process tasks mounted downstream, and I want to see all the details of the downstream tasks clearly in the base task. The dolphinscheduler currently lacks a overall DAG of dependent tasks.
> 
> So it looks like this. base task -> sub-task1 -> sub-task1-info1 -> sub-task2 -> sub-task2-info1

Maybe what you need is just the sub process task containing in the workflow relationship page?(Currently only dependent nodes are included)
![](https://vip2.loli.io/2022/06/22/apTqInzG6KiD4rF.png)

**Comment by stalary** [comment]
> > Oh, my starting point is a little different from yours. For example, I currently have a base task with a number of sub-process tasks mounted downstream, and I want to see all the details of the downstream tasks clearly in the base task. The dolphinscheduler currently lacks a overall DAG of dependent tasks.
> > So it looks like this. base task -> sub-task1 -> sub-task1-info1 -> sub-task2 -> sub-task2-info1
> 
> Maybe what you need is just the sub process task containing in the workflow relationship page?(Currently only dependent nodes are included) ![](https://camo.githubusercontent.com/4d00447b48aaaedd5d1f6d9e55d96b4c5f20efd2dd9e614f73fbb86780c498e5/68747470733a2f2f766970322e6c6f6c692e696f2f323032322f30362f32322f61705471496e7a47364b69443472462e706e67)

![截屏2022-06-22 下午10 43 18](https://user-images.githubusercontent.com/24592373/175058123-4a426ab0-1181-4c0f-8841-d33f09fa9ced.png)
I want to do this, test1 and test2 actually belong to child-test.

**Comment by SbloodyS** [comment]
I got your point. This seems very good, but it needs a special logo to distinguish it from ordinary downstream tasks. And we need to provide an option for the user to configure whether to display in this way when there are many subtasks, the DAG will be very large, resulting in slow page response.

**Comment by stalary** [comment]
Yes, I think I could show that with an option whether or not to expand sub-process tasks, but I'm just focusing on the backend, and the frontend might need a little help. I can determine whether to return the subtask data based on the parameters.

**Comment by SbloodyS** [comment]
> Yes, I think I could show that with an option whether or not to expand sub-process tasks, but I'm just focusing on the backend, and the frontend might need a little help. I can determine whether to return the subtask data based on the parameters.

Sure. After you finish the back-end part, you can ask the front-end partners of the community to assist in the front-end part.

**Comment by stalary** [comment]
> > Yes, I think I could show that with an option whether or not to expand sub-process tasks, but I'm just focusing on the backend, and the frontend might need a little help. I can determine whether to return the subtask data based on the parameters.
> 
> Sure. After you finish the back-end part, you can ask the front-end partners of the community to assist in the front-end part.

Ok, I'll finish it as soon as possible.
