### ISSUE TITLE
[Feature][Api]  Create user and system logins using insecure algorithms.

### ISSUE THREAD

**Issue by chaozwn** [apache/dolphinscheduler#10544]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Network Security Level Protection ("MLPS")
Hello, the reason for this is this. Since the company's datahub system has been launched recently, the entire system needs to be certified by MLPS. In the process of dolphin certification, I found some inappropriate security. I hope to synchronize my changes to the latest version of the community, in terms of future projects or other problems encountered in MLPS.
The main problem is on logging in and creating users.

If you guys think it's ok, I can submit a pr to fix the issue.

![image](https://user-images.githubusercontent.com/51357674/174957696-0e02cfe3-6005-4c73-bc41-35803cf722c4.png)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good job

**Comment by SbloodyS** [comment]
Feel free to fix it. Thanks. @chaozwn
