### ISSUE TITLE
[Feature] Dependent logic need optimize

### ISSUE THREAD

**Issue by stalary** [apache/dolphinscheduler#10548]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When a dependent task is used, the downstream can be automatically executed when the dependent task is rerouted or executed.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @stalary , what do you mean `when the dependent task is rerouted`?

**Comment by stalary** [comment]
> what do you mean `when the dependent task is rerouted`

depent task rerun, downstream also run.

**Comment by SbloodyS** [comment]
This has been implement in #8497.

**Comment by stalary** [comment]
> This has been implement in #8497.

Great, in which version will this feature be implemented? I didn't see it in 3.0.0-beat-1.

**Comment by SbloodyS** [comment]
> > This has been implement in #8497.
> 
> Great, in which version will this feature be implemented? I didn't see it in 3.0.0-beat-1.

It has been implemented in 3.0.0-beta-1.

**Comment by SbloodyS** [comment]
![](https://vip2.loli.io/2022/06/22/gi6JckT9GhMl2Uy.png)

**Comment by stalary** [comment]
> ![](https://camo.githubusercontent.com/7dcbae830e9adb6e50e74018216a2a76a4ef3668f4ec787576fbdd8ceb348511/68747470733a2f2f766970322e6c6f6c692e696f2f323032322f30362f32322f6769364a636b543947684d6c3255792e706e67)

Ok, I found him. I think the document could be improved.

**Comment by SbloodyS** [comment]
Yes. I'll add it to the docs. Thanks.
