### ISSUE TITLE
[Question] workflow instance is running all the time

### ISSUE THREAD

**Issue by Flutemr** [apache/dolphinscheduler#10559]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The workflow instance is running all the time, but the task instance has stopped after reporting an error. Then I click stop workflow instance, which is always stopping.
![1655946440(1)](https://user-images.githubusercontent.com/30035663/175186931-d619c466-2219-42ec-be49-ce79c4b64fd8.jpg)
task instance has stopped after reporting an error
![1655946489(1)](https://user-images.githubusercontent.com/30035663/175186934-a9c1b569-0a7c-4d1c-887a-dd955502e476.jpg)
Then I click stop workflow instance, which is always stopping.

### What you expected to happen

我看到的都是1.2.1以下版本有这个问题，我现在2.0.5还会有这个问题，是zk版本不兼容吗，我的zk版本是3.4.14
What I see is that the version below 1.2.1 has this problem. I still have this problem with 2.0.5. Is the ZK version incompatible? My ZK version is 3.4.14

### How to reproduce

no

### Anything else

no

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
@Flutemr Is there any error logs?

**Comment by Flutemr** [comment]
> @Flutemr Is there any error logs?

![1655949541](https://user-images.githubusercontent.com/30035663/175191153-f653f181-f5e8-4b42-9771-2bf3e9eca8e5.jpg)

**Comment by SbloodyS** [comment]
This is the Duplicate key error. You can find the soluctioin in the faq.
`https://dolphinscheduler.apache.org/en-us/docs/release/faq.html`

**Comment by Flutemr** [comment]
> > @Flutemr Is there any error logs?
> 
> ![1655949541](https://user-images.githubusercontent.com/30035663/175191153-f653f181-f5e8-4b42-9771-2bf3e9eca8e5.jpg)



> This is the Duplicate key error. You can find the soluctioin in the faq. `https://dolphinscheduler.apache.org/en-us/docs/release/faq.html`

ok,think you! and there have other error:
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 2

**Comment by SbloodyS** [comment]
This is the same problem.

**Comment by mextb1860** [comment]
> This is the same problem.

Are you ready to fix the problem? I also have frequent errors selectone()
