### ISSUE TITLE
[Bug] [dolphinscheduler-server]The master starts scanning packets incorrectly

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [apache/dolphinscheduler#10558]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When the master started, THE API module was scanned. I used the OpenFeign function in the API module, so the master could not start. The error message was that the Interface of OpenFeign did not have beans

### What you expected to happen

When the master starts, the API module is not scanned and the master service starts normally

### How to reproduce

In the API module, add the openfeign function, create an openfeign interface, and use @autoware for automatic injection. For example, @autoware private openfeignuserservice openfeignuserservice. When you start the master, you will report that the bean of openfeignuserservice cannot be found

### Anything else

No

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Could you describe why did you want to introduce `openfeign` module?

**Comment by ITBOX-ITBOY** [comment]
> 
In one case, I don't want to use our scheduled user information. I have my own user information interface. I want to call it through openfeign

**Comment by SbloodyS** [comment]
It sounds like custom development, not general development. We suggest providing users with more general solutions.

**Comment by ITBOX-ITBOY** [comment]
> 这听起来像是定制开发，而不是一般开发。我们建议为用户提供更通用的解决方案。



> It sounds like custom development, not general development. We suggest providing users with more general solutions.

Should the master service itself not scan API modules
