### ISSUE TITLE
[Improvement][dolphinscheduler-task-api] Support for multi-level environment variables

### ISSUE THREAD

**Issue by CFlyGoo** [apache/dolphinscheduler#10562]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I am trying to set some basic environment variables through **dolphinscheduler_env.sh**, and at the same time set some project-specific and volatile environment variables through the **Environment manage** feature.

 However, under the existing logic, this idea does not work. I can only make a copy of the basic environment variables in the **Environment manage** to take effect. 

I think it might be possible to improve this experience by setting and overriding multiple levels of environment variables

### Use case

E.g

In a Python task, I can `export PYTHONPATH=xxx` in **dolphinscheduler_env.sh** to make all projects reference some base packages without having to go through **Environment manage** or **Resources** authorization to set them one by one.

In the project-specific **Environment manage** or  **Resources** authorization, only the specific part of the project is concerned. Such as `export PYTHONPATH=yyy:$PYTHONPATH`.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
The variables in `dolphinscheduler_env.sh` is a global parameter. And the variables in the `Environment manage` is a local variable and will only take effect in the tasks used.

It seems to have met your requirements.

**Comment by CFlyGoo** [comment]
Then this seems to be a bug. I tried it on our project. When there is a value in my `Environment manage`, the settings in `dolphinscheduler_env.sh` did not take effect.

![image](https://user-images.githubusercontent.com/40393883/175202901-d5e40cba-893c-485a-8147-57d1201a6454.png)

I found the following code in `org.apache.dolphinscheduler.plugin.task.api.ShellCommandExecutor#createCommandFileIfNotExists`.

![image](https://user-images.githubusercontent.com/40393883/175201979-c4ead74d-fc58-4998-afab-076a7a906b70.png)

It seems that `dolphinscheudler_env.sh` will only take effect if there is no value in `Environment manage`.

**Comment by SbloodyS** [comment]
I can't reproduce your problems in my environment. Which version you are using?  Can you provide steps for accurate reproduction?

**Comment by stalary** [comment]
> I can't reproduce your problems in my environment. Which version you are using? Can you provide steps for accurate reproduction?

Same thing I said yesterday about python_home

**Comment by SbloodyS** [comment]
I have replied in #10533 yesterday. @stalary

**Comment by stalary** [comment]
> I have replied in #10533 yesterday. @stalary

This issue and me facing the same problem, need global environment merge environment manager.

**Comment by stalary** [comment]
> I have replied in #10533 yesterday. @stalary

I think we can have a detailed communication on wechat, my wechat is 17853149599.

**Comment by CFlyGoo** [comment]
> I can't reproduce your problems in my environment. Which version you are using? Can you provide steps for accurate reproduction?

The version I am using is 2.0.5

Perhaps, you can reproduce with the following steps:
1. Set the environment variable `PYTHONPATH` in `/opt/dolphinscheduler/conf/env/dolphinscheduler_env.sh`. Such as `export PYTHONPATH=/opt/env_test`
2. In the `/opt/env_test` directory, create a new file, such as `env_test.py` 
3. Set up some values in` Environment manage` to create an environment `test`, such as `export TEST_ENV=xxx`

![image](https://user-images.githubusercontent.com/40393883/175227255-7c80e1fe-818a-4a10-8d8a-92121d8fd981.png)

4. Create a new `Python task` and set the `Environment Name` to `test` in `Current Node Settings`, and the task content is `import env_test`

![image](https://user-images.githubusercontent.com/40393883/175226750-6b55d030-8a4c-4a74-8b53-c794a709609e.png)

5. Start the above tasks through the test Environment start

![image](https://user-images.githubusercontent.com/40393883/175226947-22483300-0a18-4d00-bd90-348bb8abe71e.png)

You will get exception `ModuleNotFoundError: No module named 'env_test'`

![image](https://user-images.githubusercontent.com/40393883/175227184-f1eee285-4c9b-4090-a90a-cd8c66d98bc2.png)

**Comment by SbloodyS** [comment]
I'm not quite familar about `PYTHONPATH`. PTAL @zhongjiajie

**Comment by CFlyGoo** [comment]
> I'm not quite familar about `PYTHONPATH`. PTAL @zhongjiajie

`PYTHONPATH` is similar to java's `CLASSPATH`, both specify dependencies search paths.

**Comment by zhongjiajie** [comment]
@CFlyGoo Yeah, currently that the behavior, and your requests make sense to me, you want to have some like `global env` and `local env`, priority is `local > global` but if the env missing in `local` you want to get them in the global default(if they have). Do you have time to create a PR and correct it?
