### ISSUE TITLE
[Bug] [Doc] Configuration doc is quite outdated and needs update

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#10571]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

* Configuration doc is quite outdated and needs update.
* https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/architecture/configuration.html

### What you expected to happen

* Already described above.

### How to reproduce

* Already described above.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rickchengx** [comment]
Hi, @EricGao888 , I am interested in this issue.

**Comment by EricGao888** [comment]
> Hi, @EricGao888 , I am interested in this issue.

@rickchengx Sure, I've assigned it to u. Thx
