### ISSUE TITLE
[Bug] [Process Definition] Duplicate records in TaskDefinitionLog

### ISSUE THREAD

**Issue by zhaohehuhu** [apache/dolphinscheduler#10572]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

There are some duplicate records for a process with same the value of code and version  in the table(t_ds_process_definition_log). This problem causes tons of error logs (org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 3), when master servers query  the table(t_ds_process_definition_log).

### What you expected to happen

The TooManyResultsException should be resolved.

### How to reproduce

Not sure

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Dupliated issue #8790. I'll close this.
