### ISSUE TITLE
[Bug] [Module Name] Data quality - custom sql execution failed

### ISSUE THREAD

**Issue by yandong001** [apache/dolphinscheduler#10578]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/37573052/175254720-807629f1-a43f-4b84-8ccc-fe188243782b.png)
表不存在，明明没问题啊

### What you expected to happen

数据质量模块

### How to reproduce

能不能来个数据质量的教学，咋使啊这个

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This has been fixed in #10549.

**Comment by yandong001** [comment]
您好
&nbsp; &nbsp; &nbsp; 好像并没有解决，我直接在3.0版本上照着#10549的git修改记录改完之后打包部署，运行3.0的时候还是报相同的错误，是不是改动的地方不止一处呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月23日(星期四) 下午4:59
***@***.***&gt;;
抄送:&nbsp;"笗 *^_^* ***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] [Bug] [Module Name] Data quality - custom sql execution failed (Issue #10578)





 
This has been fixed in #10549.

**Comment by yandong001** [comment]
> This has been fixed in #10549.

好像并没有解决，我直接在3.0版本上照着#10549的git修改记录改完之后打包部署，运行3.0的时候还是报相同的错误，是不是改动的地方不止一处呢

**Comment by feixiameiruhua** [comment]
> > This has been fixed in #10549.
> 
> 好像并没有解决，我直接在3.0版本上照着#10549的git修改记录改完之后打包部署，运行3.0的时候还是报相同的错误，是不是改动的地方不止一处呢

改完之后需要自己打包数据质量模块的jar（dolphinscheduler-data-quality-3.0.1-alpha-SNAPSHOT.jar）,然后上传上去给数据质量模块使用。同时将 hive-site.xml 文件放在spark-2.4.0的conf目录下即可。有问题我们可以一起看下。
