### ISSUE TITLE
[Feature][Docs] Give users easier access to metrics demo

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#10582]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* As mentioned in https://github.com/apache/dolphinscheduler/issues/9324#issuecomment-1164219892, we need to provide users with easier access to metrics demo.

### Use case

 - [x] Seems there are no links in https://github.com/apache/dolphinscheduler/blob/dev/docs/configs/docsdev.js for metrics docs , we should add the links.
 - [ ] At present, [metrics demo](https://github.com/apache/dolphinscheduler/tree/dev/dolphinscheduler-meter/src/main/resources) is only accessible to developers, we need to find a way to provide them for users. For example, we could add a download link someplace in Dolphin official website for users to download `grafana-demo package`.

### Related issues

related: #9324

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
May I ask whether there is some kind of storage we could use to store the demo package and provide a link on the official website?

**Comment by SbloodyS** [comment]
> May I ask whether there is some kind of storage we could use to store the demo package and provide a link on the official website?

It seems not.

**Comment by EricGao888** [comment]
> > May I ask whether there is some kind of storage we could use to store the demo package and provide a link on the official website?
> 
> It seems not.

@SbloodyS What about finding a way to include the demo in the build target tar? Users will see the demo folder once they  uncompress the release package.

**Comment by EricGao888** [comment]
> > > May I ask whether there is some kind of storage we could use to store the demo package and provide a link on the official website?
> > 
> > 
> > It seems not.
> 
> @SbloodyS What about finding a way to include the demo in the build target tar? Users will see the demo folder once they uncompress the release package.

With the demo folder we could not only put grafana-demo into it but also other demos in the future.

**Comment by EricGao888** [comment]
@zhongjiajie @SbloodyS @caishunfeng WDYT for the second point in `Use case`? I haven't figured out a good way for users to access these demo dashboards easily. Any ideas will be appreciated : )

**Comment by zhongjiajie** [comment]
> @zhongjiajie @SbloodyS @caishunfeng WDYT for the second point in `Use case`? I haven't figured out a good way for users to access these demo dashboards easily. Any ideas will be appreciated : )

maybe we can using github container registrrey(ghcr) to store docker images of this demo, and write a `docker-compose.yml` file just like https://github.com/apache/dolphinscheduler/blob/dev/deploy/docker/docker-compose.yml, and we only need to deploy our demo docker image to ghcr, users could fetch the  `docker-compose.yml` and run the latest container from ghcr

**Comment by zhongjiajie** [comment]
there is a exsits issue to desc the work of ghcr https://github.com/apache/dolphinscheduler/issues/10024

**Comment by EricGao888** [comment]
> > @zhongjiajie @SbloodyS @caishunfeng WDYT for the second point in `Use case`? I haven't figured out a good way for users to access these demo dashboards easily. Any ideas will be appreciated : )
> 
> maybe we can using github container registrrey(ghcr) to store docker images of this demo, and write a `docker-compose.yml` file just like https://github.com/apache/dolphinscheduler/blob/dev/deploy/docker/docker-compose.yml, and we only need to deploy our demo docker image to ghcr, users could fetch the `docker-compose.yml` and run the latest container from ghcr

Sounds pretty cool! I will take a look at `ghcr`. Thx for the suggestions! @zhongjiajie
