### ISSUE TITLE
[Bug] [Api] Dependent Node Only View Projects Created By Self

### ISSUE THREAD

**Issue by shangeyao** [apache/dolphinscheduler#10595]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Only display project code.

### What you expected to happen

correct it.

### How to reproduce

None

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Does this mean that dependent node can only select tasks under the current project? But cross-project dependent are a common scenario. For example, there are some common projects.
