### ISSUE TITLE
[Feature] [UI] Data Quality Result Display Optimize

### ISSUE THREAD

**Issue by shangeyao** [apache/dolphinscheduler#10594]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Such as State, Alert Type and so on.

### What you expected to happen

UI optimize

### How to reproduce

None

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @shangeyao what's the progress of this issue?
