### ISSUE TITLE
[BUG-BE][Statistics Module] The number of failed commands is incorrectly counted 

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#10602]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The number of failed commands is incorrectly counted 

### What you expected to happen

The number of failed commands is counted correctly

### How to reproduce

<img width="342" alt="image" src="https://user-images.githubusercontent.com/76080484/175545063-c661061c-a428-47d6-bb74-39334249040b.png">

<img width="462" alt="image" src="https://user-images.githubusercontent.com/76080484/175545131-a5e3c3d6-a142-498e-b932-ba55e4f2f522.png">

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by syyangs799** [comment]
#10603 #10602
This display module calls two back-end interfaces, one is /dolphin scheduler/projects/analysis/queue-count, and the other is /dolphin scheduler/projects/analysis/command-state-count.
![uTools_1656301694278](https://user-images.githubusercontent.com/55483518/175856416-63799440-5fbc-4dba-ad10-aee673b1d114.png)
![uTools_1656301797764](https://user-images.githubusercontent.com/55483518/175856502-5f25a8f1-ad38-4884-936f-60649e2aff1a.png)

The previous one is currently used, but it is false data in the code
![uTools_1656301715174](https://user-images.githubusercontent.com/55483518/175856417-b7760acd-d50c-4a2a-ba52-deefd876154c.png)

The latter can display more statistics, but the UI has not been adapted, so you may need to know how it is designed. If the backend needs to be modified, I can do it for you

**Comment by syyangs799** [comment]
> 

soryy，I changed the data of the interface  /dolphin scheduler/projects/analysis/queue-count, and I found that it may use the interface displayed later  /dolphin scheduler/projects/analysis/command-state-count
