### ISSUE TITLE
[BUG-BE][Statistics Module] The number of commands to be executed shows an error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#10603]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The number of commands to be executed shows an error

### What you expected to happen

The number of commands to be executed is displayed correctly

### How to reproduce

update t_ds_command set process_definition_code='0'

![image](https://user-images.githubusercontent.com/76080484/175546607-2bb86089-613d-48f6-93a4-6727539504ad.png)

![image](https://user-images.githubusercontent.com/76080484/175546627-28e00436-3813-4641-ac27-2b45e4c0e82e.png)

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HomminLee** [comment]
Is there such a possibility：Some processes represented by these missing commands were not created by the loggin user?
