### ISSUE TITLE
[Improvement][Master] Remove the extra check of slot

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#10617]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We have a many places to check the slot of master.

This is not needed, since this will not gurantee the command to be executed by only one master.
We already have the database transaction to deal with this case. When we transform the command to processInstance, we will delete the command at one transaction, if the delete failed, the generate of processInstance will also failed.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @ruanwenjun I have a different point, although  we already have the database transaction to gurantee the command just be consumed once, but it's not a lightweight operations and will increase the database pressure, so I think the slot check, as the pre-check,  is still necessary. WDYT?

**Comment by ruanwenjun** [comment]
> I have a different point, although we already have the database transaction to gurantee the command just be consumed once, but it's not a lightweight operations and will increase the database pressure, so I think the slot check, as the pre-check, is still necessary. WDYT

We will check the slot when query from the database, so in most of the time, there will no database rollback. My concern is that if we use the `slotCheck` here, some user may think this method can guarantee the command be consumed safe by one master. So if we really don't want to remove these, we still need to add a comment to tell this method is not safe.

**Comment by caishunfeng** [comment]
> > I have a different point, although we already have the database transaction to gurantee the command just be consumed once, but it's not a lightweight operations and will increase the database pressure, so I think the slot check, as the pre-check, is still necessary. WDYT
> 
> We will check the slot when query from the database, so in most of the time, there will not database rollback. My concern is that is we use the `slotCheck` here, some user may think this method can guarantee the command be consumed safe by one master. So if we really don't want to remove these, we still need to add a comment to tell this method is not safe.

Yes, agree with you, we should add some comments for it.

**Comment by ruanwenjun** [comment]
> > > I have a different point, although we already have the database transaction to gurantee the command just be consumed once, but it's not a lightweight operations and will increase the database pressure, so I think the slot check, as the pre-check, is still necessary. WDYT
> > 
> > 
> > We will check the slot when query from the database, so in most of the time, there will not database rollback. My concern is that is we use the `slotCheck` here, some user may think this method can guarantee the command be consumed safe by one master. So if we really don't want to remove these, we still need to add a comment to tell this method is not safe.
> 
> Yes, agree with you, we should add some comments for it.

Ok, I will keep the slot check in our code, and just add some comment to tell this.
