### ISSUE TITLE
[Improvement] [Master] MDC Logging causing OutOfMemory with TaskRecallProcessor [TaskRecallProcessor#process(Channel channel, Command command)]

### ISSUE THREAD

**Issue by pinkhello** [apache/dolphinscheduler#10619]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In the process method of the TaskRecallProcessor, add WorkflowInstanceId 、TaskInstanceId to MDC Context, but only remove WorkflowInstanceId

`
         try {
            LoggerUtils.setWorkflowAndTaskInstanceIDMDC(cmd.getProcessInstanceId(),cmd.getTaskInstanceId());
            //........       
        } finally {
            LoggerUtils.removeWorkflowInstanceIdMDC();
        }
`

### Use case

No response

### Related issues

No response

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Duplicated with #9860.
