### ISSUE TITLE
[Question] [config] During deployment, I want to modify the default port 12345 of API server. Where can I modify it

### ISSUE THREAD

**Issue by waywtdcc** [apache/dolphinscheduler#10643]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

During deployment, I want to modify the default port 12345 of API server. Where can I modify it? It seems that the configuration of version 3.0 has changed a lot

### What you expected to happen

During deployment, I want to modify the default port 12345 of API server. Where can I modify it? It seems that the configuration of version 3.0 has changed a lot

### How to reproduce

During deployment, I want to modify the default port 12345 of API server. Where can I modify it? It seems that the configuration of version 3.0 has changed a lot

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
You can modify the server port defined at `api-server/conf/application.yaml`, and if you change the backend port, you may also need to change the port at front-end.

**Comment by waywtdcc** [comment]
> You can modify the server port defined at `api-server/conf/application.yaml`, and if you change the backend port, you may also need to change the port at front-end.

Is this change made before installing?

**Comment by ruanwenjun** [comment]
> > You can modify the server port defined at `api-server/conf/application.yaml`, and if you change the backend port, you may also need to change the port at front-end.
> 
> Is this change made before installing?

Yes, when you change this, you need to restart your api service.
