### ISSUE TITLE
[Bug] [Data Quality] Data Quality-Rule-Multi-Table Accuracy could not be loaded

### ISSUE THREAD

**Issue by yandong001** [apache/dolphinscheduler#10654]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/37573052/176152420-a3070b2e-25c4-423a-b367-585a22e95da4.png)

### What you expected to happen

加载模板

### How to reproduce

创建工作流，选取数据质量，选择规则

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
![1](https://user-images.githubusercontent.com/97265214/176162831-7d7c5cf4-8c7f-4af6-a7ab-1f1472e91d94.gif)
It did not been reproduced. Could you check the http response?

**Comment by yandong001** [comment]
没响应，其他规则没问题，只有这个存在问题，然这个卡住后其他也不行了










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月28日(星期二) 晚上6:59
***@***.***&gt;;
抄送:&nbsp;"笗 *^_^* ***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] [Bug] [Data Quality] Data Quality-Rule-Multi-Table Accuracy could not be loaded (Issue #10654)





 

 It did not been reproduced. Could you check the http response?

**Comment by Amy0104** [comment]
> 没响应，其他规则没问题，只有这个存在问题，然这个卡住后其他也不行了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apache/dolphinscheduler" ***@***.***&gt;; 发送时间:&nbsp;2022年6月28日(星期二) 晚上6:59 ***@***.***&gt;; 抄送:&nbsp;"笗 *^_^* ***@***.******@***.***&gt;; 主题:&nbsp;Re: [apache/dolphinscheduler] [Bug] [Data Quality] Data Quality-Rule-Multi-Table Accuracy could not be loaded (Issue #10654) It did not been reproduced. Could you check the http response? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

What is the rule? MulTableAccuracy?

**Comment by yandong001** [comment]
规则：多表准确性&nbsp; &nbsp; &nbsp; &nbsp;我看有新的3.0-beat-2发版，准备试试这个，看是否存在问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月29日(星期三) 上午8:50
***@***.***&gt;;
抄送:&nbsp;"笗 *^_^* ***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] [Bug] [Data Quality] Data Quality-Rule-Multi-Table Accuracy could not be loaded (Issue #10654)





  
没响应，其他规则没问题，只有这个存在问题，然这个卡住后其他也不行了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apache/dolphinscheduler" @.&gt;; 发送时间:&nbsp;2022年6月28日(星期二) 晚上6:59 @.&gt;; 抄送:&nbsp;"笗 ^_^ @.@.&gt;; 主题:&nbsp;Re: [apache/dolphinscheduler] [Bug] [Data Quality] Data Quality-Rule-Multi-Table Accuracy could not be loaded (Issue #10654) It did not been reproduced. Could you check the http response? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
What is the rule? MulTableAccuracy?

**Comment by Amy0104** [comment]
But it works for me.So are you on branch dev? Could you check the console if it reported an error?

**Comment by yandong001** [comment]
没有，我用的是3.0-beta-1







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月29日(星期三) 上午10:26
***@***.***&gt;;
抄送:&nbsp;"笗 *^_^* ***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] [Bug] [Data Quality] Data Quality-Rule-Multi-Table Accuracy could not be loaded (Issue #10654)





 
But it works for me.So are you on branch dev? Could you check the console if it reported an error?

**Comment by Amy0104** [comment]
Got it. This bug has been resolved on 3.0-beta-2. And the 3.0-beta-2 will been released today or tomorrow.
