### ISSUE TITLE
[Bug] [ProcessService] ProcessService.findTaskDefinition(code,version) retun TooManyResultException：selectOne(), but found :2

### ISSUE THREAD

**Issue by wq557520** [apache/dolphinscheduler#10651]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 执行任务的时候，有任务流实例，但是任务实例一直不运行，查看后台日志发现错误：
![image](https://user-images.githubusercontent.com/34291309/176126416-9f0faf05-6f4a-4119-9a39-78d83b9dac2d.png)

### What you expected to happen

希望可以正常调度

### How to reproduce

偶发

### Anything else

我加了一个唯一索引解决：
ALTER TABLE `t_ds_task_definition_log` DROP INDEX `idx_code_version`, ADD UNIQUE `idx_code_version` (`code`, `version`) COMMENT '';

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Dupliated with #9058.

**Comment by ygq010718** [comment]
selectOne异常在3.2.0出现了，但是是因为别的原因，你有遇到过吗

**Comment by zzc69** [comment]
I have the same Problem,  I use Dolphinscheduler on K8S, version 3.2.1。

**Comment by zzc69** [comment]
I have the same Problem, I use Dolphinscheduler on K8S, version 3.2.1。

**Comment by zzc69** [comment]
I have the same Problem, I use Dolphinscheduler on K8S, version 3.2.1。
master.exception.WorkflowCreateException: Create workflowExcuteRunnable faile...
sql query table t_ds_trigger_relation, find result not only one
sql find in TriggerRelationMapper.xml which called queryByTypeAndJobId

this happened when i run some job. and then I create another new job,but miss the same issue, so I can't run any job after this issue
after truncate all talbe ,and init database , the server com to normal , pass some time,the problem happend again
