### ISSUE TITLE
[Bug] [Resource Center] When the local cache causes a multi-tab page to create a file, the obtained value is abnormal

### ISSUE THREAD

**Issue by juanfu1997** [apache/dolphinscheduler#10661]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

环境：window10
容器：chrome 103.0.5060.53
由于dss缓存信息时是使用localstorage实现，导致多个标签页面同时进行一些涉及获取缓存信息新建文件时，会导致关联的信息与实际信息不符合。

### What you expected to happen

由于当前获取文件信息都是从缓存中获取，多tab页面切换时，获取的值不一定与当前标签页的路径一致，希望能解决这个问题

### How to reproduce

eg：
dolphinScheduler模块的【资源中心】根目录下存在A与B子目录，
当用tabA页面打开A目录时，点击创建文件按钮，填写a-1文件信息，暂不保存。
切换tabB页面打开B目录，点击创建文件按钮，填写b-1文件信息，点击保存，此时b-1文件信息正常。
再返回tabA页面，点击保存，此时a-1文件的fullName保存的是B目录的路径，导致后续在【项目管理】-工作流里的资源出现异常。

### Version

1.3.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
May be you can try version 2.0.5.

**Comment by juanfu1997** [comment]
> 你可以试试2.0.5版。


Thank you for your suggestion, but I have seen that the version 2.05+ generation still uses the localstorage cache information as the parameter for creating new files. This problem still exists

**Comment by juanfu1997** [comment]
> May be you can try version 2.0.5.


Thank you for your suggestion, but I have seen that the version 2.05+ generation still uses the localstorage cache information as the parameter for creating new files. This problem still exists
