### ISSUE TITLE
[Bug] [Worker]  Tasks with S3 resource files failed incorrectly

### ISSUE THREAD

**Issue by sketchmind** [apache/dolphinscheduler#10665]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The following error is thrown while executing a task, Failed to download S3(MINIO) resource causing task failed
![image](https://user-images.githubusercontent.com/39169452/176363954-4f4265d2-7d52-48ac-b35f-6c934c98041a.png)

![image](https://user-images.githubusercontent.com/39169452/176349495-b4e80c1b-ef60-4023-93dc-147236ea8083.png)

### What you expected to happen

1.The error is because the folder in the resource path is not created
2.The ambiguity of the error log makes it possible to interpret the file as a file on S3, but it is actually the destination file

### How to reproduce

Set the resource type to S3 and select a file on S3 in the shell script task

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I don't quite understand your problems. Could you describe it more clearly? @sketchmind

**Comment by sketchmind** [comment]
> I don't quite understand your problems. Could you describe it more clearly? @sketchmind

Just like the shell node in the screenshot above, when the task is executed, the task will first download the dependent file getActiveNN.sh from the S3 file system, but for the resource file path with folders like '/common'  above,  since the directory '/common' is not created locally in advance, will cause the fail to download.
The temp dir /tmp/dolphinscheduler/exec/process/4262137237344/5999535520736_6/758/4133 created success, but 'common' not in it.

**Comment by SbloodyS** [comment]
> > I don't quite understand your problems. Could you describe it more clearly? @sketchmind
> 
> Just like the shell node in the screenshot above, when the task is executed, the task will first download the dependent file getActiveNN.sh from the S3 file system, but for the resource file path with folders like '/common' above, since the directory '/common' is not created locally in advance, will cause the download to fail. The temp dir /tmp/dolphinscheduler/exec/process/4262137237344/5999535520736_6/758/4133 created success,but 'common' not in it.

I got it. Do you have time to take a look at this? @guodongym

**Comment by guodongym** [comment]
> 

Ok, I will take a look
