### ISSUE TITLE
[Bug] [Server] Workflow recovery bug with failed tasks

### ISSUE THREAD

**Issue by brave-lee** [apache/dolphinscheduler#10673]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The workflow with failed tasks is running. Click stop to resume running. The workflow will succeed directly after the stopped task runs successfully

### What you expected to happen

The workflow with failed tasks is running. Click stop to resume running. The workflow should be fail after the stopped task runs successfully

### How to reproduce

The workflow with failed tasks is running. Click stop to resume running. 

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by KEN-LJQ** [comment]
@JinyLeeChina Hello, I kind of confuse about this pr commit, here is the situation
If process has task instance failure or stoped, and we resume it successfully. Then we will get two task instasnce, one success and on failed. But this commit will find all task instance include the failed one, which make process instance judge as failed although all task instance had success
