### ISSUE TITLE
[Feature][Api] Suggest support recommend timing configurations to users

### ISSUE THREAD

**Issue by zhuxt2015** [apache/dolphinscheduler#10690]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When the user configuration completes the timing configuration, according to the timing configuration of all the workflows that have been online, estimate  the number of tasks that will be started in minutes,  if the task number threshold is exceeded, it is recommended that the user modify the timing configuration of the current workflow.

当用户配置完成定时配置时, 根据当前已经上线的所有工作流的定时配置, 计算出已经上线的工作流每分钟会被启动的task数量, 如果超出阈值, 则建议用户修改当前工作流的定时配置。

### Use case

Users often configure a large number of workflow' timing config at the same point in time, resulting in too concentrated task execute, high worker server load, which will lead worker server downtime

用户经常在同一时间点配置大量任务, 导致任务运行过于集中, 服务器负载过高, 出现服务器宕机问题

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
Sounds pretty cool to me. If DS could provide users with suggestions on scheduled workflows / tasks number, it would definitely help. 

May I ask how to calculate the potential workload of all scheduled tasks to make the suggestions? Since the workload caused by different kinds of tasks could vary a lot.

**Comment by zhuxt2015** [comment]
> Sounds pretty cool to me. If DS could provide users with suggestions on scheduled workflows / tasks number, it would definitely help.
> 
> May I ask how to calculate the potential workload of all scheduled tasks to make the suggestions? Since the workload caused by different kinds of tasks could vary a lot.

 only calculate the number of tasks, can not calculate workload of the task will be started

**Comment by EricGao888** [comment]
> > Sounds pretty cool to me. If DS could provide users with suggestions on scheduled workflows / tasks number, it would definitely help.
> > May I ask how to calculate the potential workload of all scheduled tasks to make the suggestions? Since the workload caused by different kinds of tasks could vary a lot.
> 
> only calculate the number of tasks, can not calculate workload of the task will be started

For example, if DS could only handle 10 tasks at the same time and some user schedules 15 tasks, most of which take up few resources, it seems okay for the user to do so. How could we calculate the number to trade off between avoiding crashing the system and making the most use of it?

**Comment by EricGao888** [comment]
I think there are two sub-features in this issue:

- Firstly, calculate the number of tasks scheduled at the same time and show the statistics. This could be a good reminder for users.
- Secondly, give suggestions. This part could be a little bit complicated and need further discussions.

WDYT?@zhuxt2015

**Comment by zhuxt2015** [comment]
> > > Sounds pretty cool to me. If DS could provide users with suggestions on scheduled workflows / tasks number, it would definitely help.
> > > May I ask how to calculate the potential workload of all scheduled tasks to make the suggestions? Since the workload caused by different kinds of tasks could vary a lot.
> > 
> > 
> > only calculate the number of tasks, can not calculate workload of the task will be started
> 
> For example, if DS could only handle 10 tasks at the same time and some user schedules 15 tasks, most of which take up few resources, it seems okay for the user to do so. How could we calculate the number to trade off between avoiding crashing the system and making the most use of it?

This can configure a weight for each type of task, then compare total task weight with the configured threshold

**Comment by zhuxt2015** [comment]
> I think there are two sub-features in this issue:
> 
> * Firstly, calculate the number of tasks scheduled at the same time and show the statistics. This could be a good reminder for users.
> * Secondly, give suggestions. This part could be a little bit complicated and need further discussions.
> 
> WDYT?@zhuxt2015

Based on the task weight, I think the second one is also well solved
