### ISSUE TITLE
[Question] Adding a MySQL data source to the application page reports an error

### ISSUE THREAD

**Issue by beepupa** [apache/dolphinscheduler#10728]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

在应用页面添加MySQL数据源报错，使用默认的docker-compose.yml文件，并在文件添加了MySQL驱动到work和API的libs里面
![image](https://user-images.githubusercontent.com/36186038/176852798-a822e469-35cc-4601-a542-444936bfae79.png)
配置如下
![Uploading image.png…]()

### What you expected to happen

我不知道是哪里配置出错了

### How to reproduce

直接按我的配置项即可出现

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Could you provide the error logs?

**Comment by beepupa** [comment]
> 你能提供错误日志吗？
![image](https://user-images.githubusercontent.com/36186038/176861164-c4f4a288-8e4b-45e2-96c3-61ec88fc9baa.png)

**Comment by SbloodyS** [comment]
This is not an error in MySQL.

**Comment by beepupa** [comment]
> 这不是 MySQL 中的错误。

![image](https://user-images.githubusercontent.com/36186038/176861714-0324fc6c-1e86-41f7-9386-2fdaaed9fd57.png)

**Comment by beepupa** [comment]
> 这不是 MySQL 中的错误。

感谢您的回答
这两个问题是因为我的配置方式不对导致的吗

**Comment by SbloodyS** [comment]
In order to make everyone understand. Please use English to describe it.

**Comment by SbloodyS** [comment]
Could you provide the api-server's docker-compose.yaml?

**Comment by beepupa** [comment]
> 你能提供 api-server 的 docker-compose.yaml 吗？

![image](https://user-images.githubusercontent.com/36186038/176863001-af8d26a7-599e-4df6-a2c2-d2062f8d38d1.png)

**Comment by SbloodyS** [comment]
@EricGao888 @liqingwang Do you guys have time to take a look at this?

**Comment by qingwli** [comment]
Hi @beepupa , do you add Mysql lib in the dolphinscheduler-master image?

**Comment by beepupa** [comment]
> 

![image](https://user-images.githubusercontent.com/36186038/176866261-0d552e66-f284-4124-8026-aee960cde755.png)
yes

**Comment by qingwli** [comment]
Ok, I'll build a 3.0.0-beta1 env and test try to add a MySQL data source

**Comment by beepupa** [comment]
> 
Thank you very much

**Comment by beepupa** [comment]
I'm using the default docker-compose.YML file, just adding the MySQL JAR in the Work API Master Alert

**Comment by qingwli** [comment]
HI @beepupa , I have a test locally. And I think you have altered the wrong file. It would be right if you changed the `docker-compose.yml`.

The image URL like `${HUB}/dolphinscheduler-xxx:${TAG}` in `docker-compose.yml` is right. 
The image URL like `apache/dolphinscheduler-xxx` in `docker-stack.yml` is wrong. 

I saw your screenshot and your changes to `Worker` are correct and your changes to `Api` are wrong. You only need to change these two places and the master doesn't need to change anymore.

Can you try them in the correct file locally again?

**Comment by beepupa** [comment]
> HI @beepupa , I have a test locally. And I think you have altered the wrong file. It would be right if you changed the `docker-compose.yml`.
> 
> The image URL like `${HUB}/dolphinscheduler-xxx:${TAG}` in `docker-compose.yml` is right. The image URL like `apache/dolphinscheduler-xxx` in `docker-stack.yml` is wrong.
> 
> I saw your screenshot and your changes to `Worker` are correct and your changes to `Api` are wrong. You only need to change these two places and the master doesn't need to change anymore.
> 
> Can you try them in the correct file locally again?
Thank you, I tried your suggestion, re-downloaded the new YML file, only added MySQL JAR, but it still reported errors ,This error is reported by the ZooKeeper node, I don't know why, I see some people say that you can try to expand the memory, but when I run, I don't limit the memory. My server configuration is 16C32GB ,
![image](https://user-images.githubusercontent.com/36186038/177097698-56783049-ae06-4a92-afea-597356134e3c.png)
![image](https://user-images.githubusercontent.com/36186038/177098124-7894edd2-dd7e-4601-af39-ec98262900dc.png)

**Comment by qingwli** [comment]
Is your laptop Macbook M1? The reason why the zookeeper has an error log is the default zookeeper and PostgreSQL from bitnami only have an amd64 arch.

And I have this error log too, but it works. 

You could access DolphinScheduler web UI by click http://localhost:12345/dolphinscheduler/ui and use admin and dolphinscheduler123 as default username and password in the login page.

**Comment by beepupa** [comment]
> 你的笔记本电脑是 Macbook M1 吗？zookeeper 有错误日志的原因是默认的 zookeeper，而 bitnami 的 PostgreSQL 只有 amd64 架构。
> 
> 我也有这个错误日志，但它有效。
> 
> [您可以通过单击http://localhost:12345/dolphinscheduler/ui](http://localhost:12345/dolphinscheduler/ui)访问 DolphinScheduler Web UI，并在登录页面中使用 admin 和 dolphinscheduler123 作为默认用户名和密码。

Thank you, the application is accessible, but there is always an error when adding MySQL data source 
![image](https://user-images.githubusercontent.com/36186038/177104809-c05d8b4b-0bee-413e-9772-be4411d293da.png)

**Comment by qingwli** [comment]
Can you share the docker inspect info like below?
![2541656920738_ pic](https://user-images.githubusercontent.com/20885366/177107119-920052e3-f2e1-4898-9899-0a3e4cc9736e.jpg)
![2551656920767_ pic](https://user-images.githubusercontent.com/20885366/177107138-02e0dea1-a643-40ec-9319-ad1cccc6378f.jpg)
![2561656920767_ pic](https://user-images.githubusercontent.com/20885366/177107145-e0f06efa-beda-4b6c-94ad-660f7451ca84.jpg)
![2571656920789_ pic](https://user-images.githubusercontent.com/20885366/177107158-3d24957c-7371-4531-8f51-8485910a8556.jpg)

**Comment by beepupa** [comment]
> Can you share the docker inspect info like below? ![2541656920738_ pic](https://user-images.githubusercontent.com/20885366/177107119-920052e3-f2e1-4898-9899-0a3e4cc9736e.jpg) ![2551656920767_ pic](https://user-images.githubusercontent.com/20885366/177107138-02e0dea1-a643-40ec-9319-ad1cccc6378f.jpg) ![2561656920767_ pic](https://user-images.githubusercontent.com/20885366/177107145-e0f06efa-beda-4b6c-94ad-660f7451ca84.jpg) ![2571656920789_ pic](https://user-images.githubusercontent.com/20885366/177107158-3d24957c-7371-4531-8f51-8485910a8556.jpg)

work
![image](https://user-images.githubusercontent.com/36186038/177108431-6063160b-3986-449e-b5ef-b8e1108faa3e.png)
api 
![image](https://user-images.githubusercontent.com/36186038/177108625-f7b64e8f-55f4-4433-9539-a07a627ad4b1.png)

**Comment by qingwli** [comment]
Can you enter the docker image and see if exist the MySQL jar in libs or not.

**Comment by beepupa** [comment]
> Can you enter the docker image and see if exist the MySQL jar in libs or not.
Yes, the file is here.
work
![image](https://user-images.githubusercontent.com/36186038/177110995-d6278278-72fa-49c3-af99-9d6c2caf9c20.png)
api
![image](https://user-images.githubusercontent.com/36186038/177111256-feb951e5-dc07-4df9-a24c-f3cb9718ee61.png)

**Comment by qingwli** [comment]
That's weird. Can you post the content about docker-compose.yml? No picture, in words. And I'll try locally. By the way, do you download the source code at https://dolphinscheduler.apache.org/zh-cn/download/download.html or run it with IDE on 3.0.0-beta-1-release branch?

**Comment by beepupa** [comment]
> That's weird. Can you post the content about docker-compose.yml? No picture, in words. And I'll try locally. By the way, do you download the source code at https://dolphinscheduler.apache.org/zh-cn/download/download.html or run it with IDE on 3.0.0-beta-1-release branch?

Thank you very much, is it not ok if DB is Mariadb?

**Comment by qingwli** [comment]
Yes, looks like we do not support MariaDB now. If you are interested about support Mariadb and contributing to the community, you can follow [this](https://dolphinscheduler.apache.org/zh-cn/development/backend/spi/datasource.html)
