### ISSUE TITLE
[Bug] The request's url given by the test case looks different from the controller layer

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#10729]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/33984497/176857042-61d7a1fd-f81a-4858-8ccf-a1e40c7ff733.png)
![image](https://user-images.githubusercontent.com/33984497/176857243-eef2f144-53e6-4d79-8696-6a78e61e1615.png)

### What you expected to happen

The request's url given by the test case which become right

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @fuchanghai , would you like to submit a PR to fix this?

**Comment by fuchanghai** [comment]
yes，i want.and I found some mistakes not only URL in test unit



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 1, 2022 16:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/dolphinscheduler] [Bug] The request's url given by thetest case looks different from the controller layer (Issue #10729)




 
Hi @fuchanghai , would you like to submit a PR to fix this?

**Comment by fuchanghai** [comment]
@SbloodyS  would you please give me the permission as a contributor ?

**Comment by SbloodyS** [comment]
> @SbloodyS would you please give me the permission as a contributor ?

When your first PR is merged, you will automatically become a contributor.

**Comment by fuchanghai** [comment]
@SbloodyS i only fix the class DataSourceControllerTest, I'm not sure if the unit method annotated with org.junit.Ignore  in other classes will work. So should this question be closed? (only one of methods which annotated by org.junit.Ignore work well in class DataSourceControllerTest )
