### ISSUE TITLE
[Bug] [UI] Workflow Definition. default `environment name` showed wrong when changing `worker group`

### ISSUE THREAD

**Issue by rockfang** [apache/dolphinscheduler#10730]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

in the workflow definition. the default `environment name` showed wrong when changing `worker group`
![wrong-env](https://user-images.githubusercontent.com/16065427/176857044-3bba1141-37be-4eb2-9e0a-8e9ab2a99a3e.jpg)

### What you expected to happen

default `worker group` correctly changed when  `environment name` changed
![expect](https://user-images.githubusercontent.com/16065427/176857532-29265b6a-a0a5-44da-8746-1c3181372f24.png)

### How to reproduce

1. drag a node in the workflow definition
2. change worker group

### Anything else

it happened when 2 worker groups have the same length environment options.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
This is a good issue. Do you still want to fix this issue? If you have any problem, you can concat me. I will try to help you. @rockfang

**Comment by rockfang** [comment]
> This is a good issue. Do you still want to fix this issue? If you have any problem, you can concat me. I will try to help you. @rockfang
Actually, I didn't find an elegant way to solve it.
here is my logic:
1. When selecting the workGroup just empty the environmentCode.
2. Delete the environmentCode operation in `use-environment-name.ts`. So just pure trigger from workGroup can change the default environmentCode.
3. The `environmentCode ` will not has default. it's ok for me...
@Amy0104

**Comment by Amy0104** [comment]
> 

There are three situations. 
Firstly, have already created a task with workGroup and environment. WorkGroup and environment should be displayed after data back. For this, we can't set workGroup and environment manually, that is why I use isCreate.
Secondly, just want to create a task, then we need to set the default value for workGroup and environment after getting the environmentList.
Thirdly, change the work group and set the default value for environment. For this, I agree with you, it can be handled by using watch, but it should be effect after the component mounted.
@rockfang

**Comment by rockfang** [comment]
Situation A : 
manually changed the workGroup selection
> need to set the default environment (null or the default only one)

Situation B:
1. I choose a workGroup like `W`
2. I choose  an environment like `W-env`
3. click `save` in this modal. (temp save not submit till now)
4. double click this node to reEdit it (need to redisplay my last choose `W-env)`

What puzzled me is both situation A&B will trigger `watch( () => model.workerGroup...` . 
But I can't resolve them 
@Amy0104

**Comment by Amy0104** [comment]
I try to fix it. pls check later. @rockfang

**Comment by rockfang** [comment]
@Amy0104  good!
I read the code and it works well for me

**Comment by Amy0104** [comment]
> @Amy0104 good! I read the code and it works well for me

Thanks for your feedback. @rockfang
