### ISSUE TITLE
[Bug] [Server] DS will constantly generate tasks when complement data in 3.0.0-beta-2

### ISSUE THREAD

**Issue by wangbowen1024** [apache/dolphinscheduler#10732]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

DS has some problem when when complement data.
1. this is my shell task only `echo "hello"`
![image](https://user-images.githubusercontent.com/48642743/176871902-de5e1bb4-7855-46a5-ab21-d83fdcf66523.png)
2. There are several cases when complement data with Different Process execute type(执行策略):
*  parallel（并行）（result：OK）
![image](https://user-images.githubusercontent.com/48642743/176870071-1c6e5ce7-3614-485a-b751-7ff7fc83f252.png)
* Serial priority（串行优先）（result：Cannot stop or succeed）
![image](https://user-images.githubusercontent.com/48642743/176870256-529dc701-303e-47e9-9a5f-451d3837fcbd.png)
* Serial discard （串行抛弃）（result：STOP）
![image](https://user-images.githubusercontent.com/48642743/176871319-8a4d68e5-7384-4778-bea7-59b0f75abe71.png)
* Serial wait（串行等待）（result：Keep building tasks without stopping）
![image](https://user-images.githubusercontent.com/48642743/176871562-2754328c-4985-4934-8397-92a1ab1dbf32.png)

### What you expected to happen

just excute right

### How to reproduce

just complement data all the time

### Anything else

Version is 3.0.0-beta-2

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zerosyn** [comment]
We have a similar problem to this one in 3.0.0-beta-1.

Workflow A have multiple tasks irrelevant, Process execute type: parallel（并行）.
Complement data on this workflow is running perfect.

Workflow B have multiple tasks depend sequentially, Process execute type: Serial wait（串行等待）.
Complement data on this workflow will continually generate new workflow instance after previous finished, can't stop unless edit instance state in database.
