### ISSUE TITLE
t_ds_schedules start_time/end_time  with the ui start_time/end_time  different

### ISSUE THREAD

**Issue by Flutemr** [apache/dolphinscheduler#10733]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I found that the task was not automatically scheduled. Go to The start time and end time in the t_ ds_ Schedules table are different from those in the UI。
this my  t_ ds_ Schedules table data:
![111](https://user-images.githubusercontent.com/30035663/176981269-6736a103-ec27-429c-abc1-a8c8962e7ba5.jpg)

this my web-UI：
![222](https://user-images.githubusercontent.com/30035663/176981369-2b056ed7-f0cc-481c-bded-b6f68fe2ca5a.jpg)

this my worker time:
![333](https://user-images.githubusercontent.com/30035663/176981381-abe5d17e-5bd0-4c0a-b19c-9c59f92eaf0a.jpg)

### What you expected to happen

I adjusted the scheduling time yesterday ，today  some process instance dont' schedule 。

### How to reproduce

no

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Flutemr** [comment]
all process instance the  star_time and end_time   One day late

**Comment by SbloodyS** [comment]
It seems that the database time zone is inconsistent with the UI time zone.

**Comment by Flutemr** [comment]
> It seems that the database time zone is inconsistent with the UI time zone.

my database time  is now time，so database time zone   no problem

**Comment by github-keep** [comment]
![1657360935569](https://user-images.githubusercontent.com/34233672/178101051-97c20e88-615a-4d3d-828d-c09fe94f1f78.jpg)
You need to add a time zone to the JDBC connection
