### ISSUE TITLE
[Bug] [UI] Cannot back from cron manager in safari

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#10747]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I click the cron manager, then I cannot go back to other page.
<img width="1724" alt="image" src="https://user-images.githubusercontent.com/22415594/177040098-79e2cd32-e7f3-425f-bc6c-dd2f6030302e.png">

I use safari.
My system is Mac os Monterey with M1 pro.
node version is v16.13.0

### What you expected to happen

xx

### How to reproduce

1. Create a workflow
2. Click the Timing  
3. Click the corn manager.

Then you will find you cannot go to other page.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vivostar** [comment]
hi, @ruanwenjun , I find your picture shows that you are in the "**Project**" Dashboard, but actually the "**Task Result**" and "**Rule Management**" under the "**Data Quality**" Dashboard.

**Comment by ruanwenjun** [comment]
> hi, @ruanwenjun , I find your picture shows that you are in the "**Project**" Dashboard, but actually the "**Task Result**" and "**Rule Management**" under the "**Data Quality**" Dashboard.

Yes, but you can see the right window is still in corn manager.

**Comment by Amy0104** [comment]
I didn't not reproduce. Could you provide more details?
![1](https://user-images.githubusercontent.com/97265214/177122760-511d077d-34cf-42f9-8dda-e2626f0a14df.gif)

**Comment by ruanwenjun** [comment]
@Amy0104 Thanks for your reply, you can try to click Timing first and then click cron manager.

Here is the console:
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/22415594/177125754-7e61376f-dff8-4fd0-960d-ff6b997f1f8b.png">

**Comment by ruanwenjun** [comment]
I checked in chrome, it can work well, it seems this bug just occurred in safari. I will close the issue hope someone can fix it.
