### ISSUE TITLE
[Feature] [UI] SQL and Python Editor Highlight not Work 

### ISSUE THREAD

**Issue by vivostar** [apache/dolphinscheduler#10752]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When you create a sql node, the sql editor highlight is not work. However, shell editor highlight is work.
![image](https://user-images.githubusercontent.com/49220700/177054450-bf5b4940-57d3-4595-bffd-3278f8ecaa39.png)

So it is when you create a python node
![image](https://user-images.githubusercontent.com/49220700/177054338-42a0ba83-6b60-41ff-9ca2-d70e1e262c5e.png)

### What you expected to happen

make sql and python highlight work. like following
```sql
select name, score
from students
where score < 10
```
```python
print("Hello World")
```

### How to reproduce

1. download source code, and checkout dev branch
```shell
git clone https://github.com/apache/dolphinscheduler.git
cd dolphinscheduler
git checkout dev
```
2. start standalone-server, so you can create a development env
3. start the dolphinscheduler-ui （you should install node and pnpm before you do this）
```shell
cd dolphinscheduler-ui
pnpm install
pnpm dev
```
4. you can create a dolphin project, and then you will reproduce the problem

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
This can actually be considered an optimization point, because we didn't have to deal with more language highlighting support in a hurry. @vivostar
