### ISSUE TITLE
[Improvement][Master] Remove the spring annotation in un-spring bean.

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#10758]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I find we have use spring annotation in some class which is not a spring bean.
https://github.com/apache/dolphinscheduler/blob/423cc5b9be678a3ea30afadad2667bf7d6330324/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/LowerWeightHostManager.java#L47-L75

I hope we can optimize these.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by guodongym** [comment]
@ruanwenjun 
I noticed that after the instantiation of a class, use the AutowireCapableBeanFactory. AutowireBean bean of injection, AutowireCapableBeanFactory is on the basis of the BeanFactory realize the management of the existing examples

![image](https://user-images.githubusercontent.com/20675095/178111566-27b8e2ee-ba6d-40fd-88cb-5f39e709373f.png)

**Comment by ruanwenjun** [comment]
@guodongym In my knowledge, directly return is enough, there is no need to set to the beanFactory?
