### ISSUE TITLE
[Feature][Master] Failover workflow  instance in priority

### ISSUE THREAD

**Issue by zhuxt2015** [apache/dolphinscheduler#10750]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When failing over a workflow instance, it should be based on the priority of the instance

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Yes, right now, when we do failover we will not set the `process_instance_priority` into command, this can be improved.
