### ISSUE TITLE
[Feature][dolphinscheduler-api] Some variables are redundant

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#10760]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Subclasses that inherit BaseServiceImpl and have the resourcePermissionCheckService attribute should remove this attribute in the subclass. Because this attribute already exists in the BaseServiceImpl  class  (eg:DataSourceServiceImpl ,ProjectServiceImpl)

### Use case

remove   the resourcePermissionCheckService attribute

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
PTAL @WangJPLeo

**Comment by WangJPLeo** [comment]
> PTAL @WangJPLeo

Yes, there are methods userOwnedResourceIdsAcquisition and functionDisabled directly used in subclasses. These should be used uniformly in BaseServiceImpl. This is a very standardized transformation, one thing to note is the use of the Logger parameter in the corresponding ut. @caishunfeng @fuchanghai

**Comment by fuchanghai** [comment]
@caishunfeng I still see the discussion tag. I will change it first and wait for you to confirm before PR

**Comment by fuchanghai** [comment]
@SbloodyS There is some checkstyle warning in the involved subclasses, can I handle it?

![image](https://user-images.githubusercontent.com/33984497/180748290-ca98d8f4-3f4c-4bd7-a667-8a2ef03debd1.png)
