### ISSUE TITLE
[Question] Error calling python script

### ISSUE THREAD

**Issue by mpmiles** [apache/dolphinscheduler#10777]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

我用ds调服务器上的python程序，一直报错，python_home也配置了，打印的日志也是使用的python_home的路径，但是就是报错，麻烦帮忙看看，谢谢
![8bd9f80f32dcc2b25be57d6931409ab](https://user-images.githubusercontent.com/91513893/177185254-4edacc86-43fe-4a8a-a62c-5a48439f1617.png)

### What you expected to happen

调用python脚本报错

### How to reproduce

调用python脚本报错

### Version

1.3.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Version 1.3.8 is no longer in the maintaining list. You can try the latest version.
