### ISSUE TITLE
[Bug] [Project] The language package for 'MB' and '%' are not matched.

### ISSUE THREAD

**Issue by Amy0104** [apache/dolphinscheduler#10770]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when I open the workflow definition detail page, I got those warnings.
<img width="534" alt="image" src="https://user-images.githubusercontent.com/97265214/177132416-11568436-6067-4a2e-9b61-6c5bf14d6c86.png">

### What you expected to happen

Fix those warnings.

### How to reproduce

Open the workflow definition detail page.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by XuXuClassMate** [comment]
I will fix
