### ISSUE TITLE
[Bug] [UI] The selection of multi table accuracy in data quality is unsuccessful

### ISSUE THREAD

**Issue by github-keep** [apache/dolphinscheduler#10781]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

在使用【DATA_QUALITY】工具时，【规则名称】选择【多表准确性】时，页面加载失败，JavaScript报错。
![image](https://user-images.githubusercontent.com/34233672/177237776-668e3336-ea3a-4c74-b8fd-779fb9a020e0.png)

### What you expected to happen

与官网文档示例不一样

### How to reproduce

data_quality-->规则名称-->多表准确性

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by github-keep** [comment]
version 3.0.0-beta-1

**Comment by songjianet** [comment]
Please provide the name and version of the browser below. @github-keep

**Comment by github-keep** [comment]
> 请在下方提供浏览器的名称和版本。@github-keep

Google Chrome 103.0.5060.114（正式版本）（32 位）and Microsoft Edge 103.0.1264.49 (正式版本) (64 位)

**Comment by github-keep** [comment]
Upgrade to 3.0.0-beta-2 and it can be used normally
