### ISSUE TITLE
[Bug] [Script] Remove UseFastAccessorMethods in remove-zk-node.sh

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#10787]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

* When deployed in `pseudo-cluster` mode on `macOS Catalina`, `remove-zk-node.sh` throws `Unrecognized VM option 'UseFastAccessorMethods'` and causes failure to remove zk node.
* After removing `-XX:UseFastAccessorMethods`, things worked.

### What you expected to happen

* We may remove `-XX:UseFastAccessorMethods` in https://github.com/apache/dolphinscheduler/blob/7d79a2165ee5f0bf1aa7c949c852da179d6c0cc9/script/remove-zk-node.sh#L42

### How to reproduce

* Already described above.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
(base) ➜  bin java -version
java version "11.0.15" 2022-04-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.15+8-LTS-149, mixed mode)

**Comment by ruanwenjun** [comment]
Seems UseFastAccessorMethods has been deprecated

**Comment by EricGao888** [comment]
> Seems UseFastAccessorMethods has been deprecated

For `UseFastAccessorMethods` has been deprecated since JDK 9 and may cause trouble, what about simply removing it from the script?

**Comment by ruanwenjun** [comment]
> > Seems UseFastAccessorMethods has been deprecated
> 
> For `UseFastAccessorMethods` has been deprecated since JDK 9 and may cause trouble, what about simply removing it from the script?

I think we can remove it, it seems this is a optional args to optimize the set/get method.

**Comment by EricGao888** [comment]
> > > Seems UseFastAccessorMethods has been deprecated
> > 
> > 
> > For `UseFastAccessorMethods` has been deprecated since JDK 9 and may cause trouble, what about simply removing it from the script?
> 
> I think we can remove it, it seems this is a optional args to optimize the set/get method.

Sure, I will fix it.
