### ISSUE TITLE
[Improvement] [Alert Server] Datasource url inconsistency in alert server application.yaml

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#10788]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

* There is no default value for datasource `url` in the application.yaml file of alert server. 
* However, in the application.yaml files of other DS components (master, worker, api server), there is a default value.
* This inconsistency leads to deployment issue of DS when deployed in `pseudo-cluster` or `cluster` mode and causes alert server startup failure. 
https://github.com/apache/dolphinscheduler/blob/7d79a2165ee5f0bf1aa7c949c852da179d6c0cc9/dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/resources/application.yaml#L72-L78

### What you expected to happen

* Add default value for datasource url in the application.yaml file of alert server. 

### How to reproduce

* Already described above.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Good catch, this should be an improvement, not a bug.

**Comment by EricGao888** [comment]
> Good catch, this should be an improvement, not a bug.

Thx for the reply. BTW, seems we have the same situation in release-beta-2, not sure whether it may cause confusion to users.

https://github.com/apache/dolphinscheduler/blob/7ddaa2f47d90e9302c9ad3400bab31baf424f37a/dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/resources/application.yaml#L61-L69

**Comment by ruanwenjun** [comment]
> > Good catch, this should be an improvement, not a bug.
> 
> Thx for the reply. BTW, seems we have the same situation in release-beta-2, not sure whether it may cause confusion to users.
> 
> https://github.com/apache/dolphinscheduler/blob/7ddaa2f47d90e9302c9ad3400bab31baf424f37a/dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/resources/application.yaml#L61-L69

Don't worry, this is not a serious problem
