### ISSUE TITLE
Run task bug

### ISSUE THREAD

**Issue by he4462069** [apache/dolphinscheduler#10780]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After the flink batch task is submitted, the task fails to run, but the workflow instance page shows success.

### What you expected to happen

none

### How to reproduce

none

### Anything else

none

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @he4462069 , Is your Flink running in Yarn mode?

**Comment by he4462069** [comment]
> 

Flink run in local cluster
