### ISSUE TITLE
[Improvement][Module Name] executes a single task node in the workflow

### ISSUE THREAD

**Issue by markflows** [apache/dolphinscheduler#10782]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://user-images.githubusercontent.com/108707879/177238973-f5f69293-0f0c-4393-986f-d674c62e6585.png)
如图片所示,现在点击任务流中的单个节点会执行当前节点以及下游节点,希望可以增加只执行当前节点的功能,这个功能在2.X版本是支持的,不知为何在3.X版本不再支持

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jackfanwan** [comment]
I want to finish it
