### ISSUE TITLE
[Bug] [Flink] Bug Flink on Yarn resource scheduler is still running, can't stop

### ISSUE THREAD

**Issue by yyunlei** [apache/dolphinscheduler#10809]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

使用最新的版本发布Flink on yarn 任务，启动和重启都没问题。就是停止在ds 界面是停止状态，而Yarn 资源调度器中还是running 状态，停不掉，不知道这个算是bug吗？Flink 使用的1.13.6 版本

### What you expected to happen

DS中可以管理Flink On Yarn 任务，启动和停止都可以。DS中停止Flink On Yarn 的时候, yarn资源管理器中也可以停止

### How to reproduce

发布Flink on yarn 任务，启动和重启都没问题。就是停止在ds 界面是停止状态，而Yarn 资源调度器中还是running 状态，停不掉.

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yyunlei** [comment]
![image](https://user-images.githubusercontent.com/7547693/177684184-45595d9b-06db-4aa3-ab15-88a03dc77efd.png)
![image](https://user-images.githubusercontent.com/7547693/177684262-a850dfba-ab49-4764-96b7-9499e66414a0.png)
上图正常重跑，没问题
![image](https://user-images.githubusercontent.com/7547693/177684423-8aa5a4ae-4a59-4646-b3b4-95b5054f3d2c.png)
![image](https://user-images.githubusercontent.com/7547693/177684464-de963b05-4a1d-40d5-9754-b764be3789ff.png)
DS中任务已经停止了，可是在Yarn 资源调度器中还是Running 状态。没有停止

**Comment by yyunlei** [comment]
![image](https://user-images.githubusercontent.com/7547693/177685095-80bcb57b-d1e5-48e0-aa54-78d0165d20b3.png)
Flink 任务作业中的版本选择大于1.10，保存成功。但是在打开修改的时候 还是显示小于1.10.这个是bug
![image](https://user-images.githubusercontent.com/7547693/177685249-e50a49ce-166e-473e-82b6-f1d5968d118d.png)

**Comment by caishunfeng** [comment]
> ![image](https://user-images.githubusercontent.com/7547693/177685095-80bcb57b-d1e5-48e0-aa54-78d0165d20b3.png) Flink 任务作业中的版本选择大于1.10，保存成功。但是在打开修改的时候 还是显示小于1.10.这个是bug ![image](https://user-images.githubusercontent.com/7547693/177685249-e50a49ce-166e-473e-82b6-f1d5968d118d.png)

Hi @yyunlei please use English on description, which can make more developers understand, thanks.
Are you interested in fixing this bug?

**Comment by caishunfeng** [comment]
> ![image](https://user-images.githubusercontent.com/7547693/177684184-45595d9b-06db-4aa3-ab15-88a03dc77efd.png) ![image](https://user-images.githubusercontent.com/7547693/177684262-a850dfba-ab49-4764-96b7-9499e66414a0.png) 上图正常重跑，没问题 ![image](https://user-images.githubusercontent.com/7547693/177684423-8aa5a4ae-4a59-4646-b3b4-95b5054f3d2c.png) ![image](https://user-images.githubusercontent.com/7547693/177684464-de963b05-4a1d-40d5-9754-b764be3789ff.png) DS中任务已经停止了，可是在Yarn 资源调度器中还是Running 状态。没有停止

When user stop the processInstance in ui, it will try to kill yarn job, can you find some error log about it?

**Comment by yyunlei** [comment]
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/7547693/179126639-302aea6d-7f6b-41e6-8982-b319f9b0e32d.png">


必须手动kill 或者yarn里边停止掉才可以
日志中发现yarn application -kill application_1655173184123_0031 没有用。但是单独手动执行就可以。

**Comment by yyunlei** [comment]
![image](https://user-images.githubusercontent.com/7547693/179127046-2f834dd6-fba4-4dad-a0e6-18e6bf1378cf.png)

**Comment by yyunlei** [comment]
<img width="976" alt="image" src="https://user-images.githubusercontent.com/7547693/179128473-78118751-e616-45a1-bdfc-3a61690db2ac.png">
启动的时候，发现t_ds_task_instance 表中app_link 没有把 yarn运行的PID和applicationID存储进去，只有在执行停止的时候才会
进行写入，不知道是否与这个有关。

**Comment by caishunfeng** [comment]
> <img alt="image" width="976" src="https://user-images.githubusercontent.com/7547693/179128473-78118751-e616-45a1-bdfc-3a61690db2ac.png">
> 
> 启动的时候，发现t_ds_task_instance 表中app_link 没有把 yarn运行的PID和applicationID存储进去，只有在执行停止的时候才会 进行写入，不知道是否与这个有关。

Yes, the taskInstance application id will be updated when task finish, so it will dothing to kill yarn job if application id is empty.
Maybe it should be improved to get process id or application id early.

**Comment by yyunlei** [comment]
不知道什么时候可以解决掉 ds 停止flink on  yarn 任务停不掉的bug呢？这样就可以上生产环境了。

**Comment by caishunfeng** [comment]
> > <img alt="image" width="976" src="https://user-images.githubusercontent.com/7547693/179128473-78118751-e616-45a1-bdfc-3a61690db2ac.png">
> > 启动的时候，发现t_ds_task_instance 表中app_link 没有把 yarn运行的PID和applicationID存储进去，只有在执行停止的时候才会 进行写入，不知道是否与这个有关。
> 
> Yes, the taskInstance application id will be updated when task finish, so it will dothing to kill yarn job if application id is empty. Maybe it should be improved to get process id or application id early.

Sorry, I found that when kill or failover, it will try to get appId from task log, you can see the `TaskKillProcessor` of kill detail.

**Comment by hstdream** [comment]
Hello, is your yarn cluster ha? @yyunlei

**Comment by yyunlei** [comment]
> 你好，你的纱线集群哈？@yyunlei

是Flink  on  yarn 集群模式

**Comment by pony712** [comment]
请问这个问题解决了吗，或者有没有可用的补丁呢？

**Comment by caishunfeng** [comment]
@yyunlei @pony712 can you check for dev branch? Because I had fix kill flink task in #11350, hope it can help you.

![image](https://user-images.githubusercontent.com/11962619/189836329-3177b2ef-ae02-4efc-8a36-0ee2407ec2b3.png)

![image](https://user-images.githubusercontent.com/11962619/189836486-a1b3cb56-3262-4555-bca9-ae5f720aa8ef.png)

**Comment by yyunlei** [comment]
请问下载那个版本修复修复上述问题呢？

**Comment by EricGao888** [comment]
@caishunfeng May I ask whether we should cherry-pick #11350 for 3.0.2? Thx : )

**Comment by wangkaiyu13** [comment]
3.14 The current bug is not fixed temporarily

**Comment by LiuCanWu** [comment]
请问官方的社区人员这个问题解决了吗 现在只能手动停止yarn任务
