### ISSUE TITLE
[Bug] [FlinkSql] flinksql execute error

### ISSUE THREAD

**Issue by lizhongshuai** [apache/dolphinscheduler#10808]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

使用海豚调度器调度flinksql，建表语句可以正常执行，插入语句会报错
错误信息：
TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.flink.FlinkTask:[63] -  -> [31;1m[ERROR] Could not execute SQL statement. Reason:
 java.lang.IllegalStateException: No Executor found. Please make sure to export the HADOOP_CLASSPATH environment variable or have hadoop in your classpath. For more information refer to the "Deployment" section of the official Apache Flink documentation.[0m
 
 Shutting down the session...
 done.

### What you expected to happen

写一个比较详细的flinksql调度过程  包括flink的版本 和所需要的环境

### How to reproduce

在MySQL中创建三张表  字段一致  其中两张表中插入数据 然后写flinksql  同样是创建三张一样的表 关联到mysql的表 然后查询有数据的两张表插入到第三张没有数据的表   这样的flinksql写完之后放到海豚调度器上进行调度

### Anything else

无

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
>Please make sure to export the HADOOP_CLASSPATH environment variable or have hadoop in your classpath

Hi @lizhongshuai Please check the env config in `dolphinscheduler_env.sh`

**Comment by caishunfeng** [comment]
BTW, please add the sql detail of `how to reproduce`

**Comment by hstdream** [comment]
There are two ways to solve this problem:

1. add export HADOOP_CLASSPATH=`hadoop classpath` 

2. In flink/lib add flink-shaded-hadoop-2-uber.jar

**Comment by lizhongshuai** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月6日(星期三) 下午5:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] [Bug] [Module Name] Bug title  (Issue #10808)





 
Thank you for your feedback, we have received your issue, Please wait patiently for a reply.
  
In order for us to understand your request as soon as possible, please provide detailed information、version or pictures.
 
If you haven't received a reply for a long time, you can join our slack and send your question to channel #troubleshooting

**Comment by EricGao888** [comment]
Solved by https://github.com/apache/dolphinscheduler/issues/10808#issuecomment-1198755028
