### ISSUE TITLE
Scheduling error with flink that does not rely on hadoop

### ISSUE THREAD

**Issue by lizhongshuai** [apache/dolphinscheduler#10818]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

使用海豚调度器调度flinksql，建表语句可以正常执行，插入语句会报错
错误信息：
TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.flink.FlinkTask:[63] -  -> [31;1m[ERROR] Could not execute SQL statement. Reason:
 java.lang.IllegalStateException: No Executor found. Please make sure to export the HADOOP_CLASSPATH environment variable or have hadoop in your classpath. For more information refer to the "Deployment" section of the official Apache Flink documentation.[0m
 
 Shutting down the session...
 done.

### What you expected to happen

写一个比较详细的flinksql调度过程  包括flink的版本 和所需要的环境

### How to reproduce

在MySQL中创建三张表  字段一致  其中两张表中插入数据 然后写flinksql  同样是创建三张一样的表 关联到mysql的表 然后查询有数据的两张表插入到第三张没有数据的表   这样的flinksql写完之后放到海豚调度器上进行调度

### Anything else

海豚调度flink是只支持on yarn部署的flink吗 kubernetes部署的是否支持调度 

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Dupliated with #10808.
