### ISSUE TITLE
About scheduling flink deployed by Kubernetes

### ISSUE THREAD

**Issue by lizhongshuai** [apache/dolphinscheduler#10828]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

请加快上线调度Kubernetes部署flink的功能

### Use case

请加快上线调度Kubernetes部署flink的功能

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Same issue #10904
So I will close this one.
