### ISSUE TITLE
[Bug][Doc] Change the start or install script command sh in the document to bash

### ISSUE THREAD

**Issue by lukeyan2023** [apache/dolphinscheduler#10830]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In Ubuntu 20.04, using sh to execute the startup and installation scripts under the bin directory reports an error, because Ubuntu uses dash instead of bash by default. In order to be compatible with different types of operating systems, can bash be used to replace sh. The following screenshot is a test of the Ubuntu system:
![image](https://user-images.githubusercontent.com/108530647/177721767-d1d5d864-24f1-4781-a88f-1237c810ef09.png)

### Documentation Links

https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/guide/installation/standalone.html

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Using `bash` instead of `sh` can resolve this problem. Welcome to correct the document.
