### ISSUE TITLE
[Doc][Resource Center] Remind users not to operate resources directly through storage systems

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#10841]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* When users manage their resource files in resource center, data related to resources is recorded in database. If they delete / rename the resources directly through the storage system (like HDFS, S3) instead of resource center, there will be inconsistency. In that case, they have to modify the database to fix things.
* Add notice in docs to remind users not to operate DS related resources directly through the storage system.

### Documentation Links

https://dolphinscheduler.apache.org/en-us/docs/dev/user_doc/guide/resource/file-manage.html

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
The reason is that DS and third-party storage system are two different metadata. At present, there is an optimization process in #10495. This problem will no longer exist after the implementation of this feature is done. @EricGao888

**Comment by EricGao888** [comment]
> The reason is that DS and third-party storage system are two different metadata. At present, there is an optimization process in #10495. This problem will no longer exist after the implementation of this feature is done. @EricGao888

Cool! Thx for the info @SbloodyS

**Comment by EricGao888** [comment]
I will close this issue as soon as #10495 resolved.

**Comment by zhongjiajie** [comment]
I think this issue can be close now, WDYT? @SbloodyS @EricGao888

**Comment by SbloodyS** [comment]
> I think this issue can be close now, WDYT? @SbloodyS @EricGao888

Yes. I'll close it.
