### ISSUE TITLE
[Improvement][alert] 'Fault tolerance warning' can be specified to send to special group

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#10840]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I try to kill one dolphin mater node to test the alert plugin, I don't know the rule : who will this kind of 'Fault tolerance warning' to be send . I think this kind of message need to send to specified group or at leat to the admin, but it not and there is no way to config it !

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Currently the fault tolerance warning will send to the default warning group. Which is the id=1 alert group.

**Comment by hezean** [comment]
![Screen Shot 2022-07-09 at 00 47 50](https://user-images.githubusercontent.com/49837965/178035650-292aeb63-e798-48cb-8a17-ebf30945b836.png)

Wish I could help. I think we can work around here ⬆️, if possible, plz point me out where could be proper for users to set it? or just give me some time to think about it.

**Comment by SbloodyS** [comment]
@HeZean I think we can provide a button on the configuration page of alert-group-manage to allow users to configure whether this group is a fault-tolerant alarm group.
