### ISSUE TITLE
[Feature][Master] Add http interface to query workflow instance state queue or some other meta

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#10871]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Right now, there are some meta we didn't persist them.

e.g. If I want to query a workflow instance's state queue or how many channel it has connect to worker or some other details.

I have no way to query these info.

It's necessary to expose these info by http or some other way, http is easy.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Good idea, I will do it.
