### ISSUE TITLE
[Bug] SQL task prepareStatementAndBind error

### ISSUE THREAD

**Issue by Flutemr** [apache/dolphinscheduler#10889]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

some task have thie error ，the logs ：
![1657588032(1)](https://user-images.githubusercontent.com/30035663/178387309-9c677067-7a35-48bc-bea2-683ba5ecefdb.jpg)
![1](https://user-images.githubusercontent.com/30035663/178941380-95b61dcf-1a85-4437-a56c-5efa3a12ccdf.jpg)
![2](https://user-images.githubusercontent.com/30035663/178941400-4838bf59-c014-460f-94ff-f1bf4eebdc78.jpg)

### What you expected to happen

no

### How to reproduce

no

### Version

2.0.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please check whether hiveserver2 can be connected.

**Comment by Flutemr** [comment]
> Please check whether hiveserver2 can be connected.

yes, I increased the values of  "hive.server2.thrift.max.worker.threads"  and  "hive.metastore.client.socket.timeout"。
I will continue to observe tomorrow。thx。

**Comment by Flutemr** [comment]
> Please check whether hiveserver2 can be connected. 

I add a other hiveserver2 at  yesterday,now you can close this issues。

**Comment by zhaoxiaoge** [comment]
How appropriate are these two parameters? We currently set the maximum number of threads to 1000 and the timeout to 10 minutes @Flutemr

**Comment by Flutemr** [comment]
> How appropriate are these two parameters

yes,you can add anohter  hiveserver2  and  hive matestor , use  hive Ha 。
