### ISSUE TITLE
[Bug] [Process] When I save process without modifying it, t_ds_task_definition keeps growing

### ISSUE THREAD

**Issue by hsnotebook** [apache/dolphinscheduler#10883]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. Open a process
2. add a node
3. save process
4. save process again, the new node will be inserted into t_ds_task_definition again with the same `code`.
5. refresh the page
6. save process, `Duplicate key TaskDefinition` appears
7. delete duplicate the records, it becomes ok.

### What you expected to happen

What happened should not happen.

### How to reproduce

It is described in the "What happened" section.

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
It has been fixed in 2.0.6
