### ISSUE TITLE
[Bug] [DATAX] datax target data source echo failed

### ISSUE THREAD

**Issue by gongzh021** [apache/dolphinscheduler#10885]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

datax目标数据源回显失败
![image](https://user-images.githubusercontent.com/96610911/178251260-d8e33c2e-0d15-4db3-aefb-8c6febd52e0f.png)

### What you expected to happen

1

### How to reproduce

1

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it

**Comment by devosend** [comment]
<img width="584" alt="image" src="https://user-images.githubusercontent.com/8847400/178972719-84bef850-ccfa-4b11-9a22-d711ee13033d.png">
I didn't reproduce your question. Can you provide a more detailed description?

**Comment by simsicon** [comment]
> <img alt="image" width="584" src="https://user-images.githubusercontent.com/8847400/178972719-84bef850-ccfa-4b11-9a22-d711ee13033d.png">
> 
> I didn't reproduce your question. Can you provide a more detailed description?

you can try to save the task, then reopen it, the data source will be empty.

**Comment by simsicon** [comment]
And it's seems a bug respect to datax tasks, I can not reproduce it in sql task.
