### ISSUE TITLE
[Bug] [Timing policy] Time policy setting bug

### ISSUE THREAD

**Issue by gongzh021** [apache/dolphinscheduler#10887]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/96610911/178260264-c20abb5d-3abb-4234-98e5-bfba8e187f69.png)

### What you expected to happen

1

### How to reproduce

1

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pinkhello** [comment]
#10833

**Comment by pinkhello** [comment]
click “执行时间“ button

**Comment by gongzh021** [comment]
> click “执行时间“ button

The result after clicking "执行时间" does not match the time zone.

**Comment by pinkhello** [comment]
> > click “执行时间“ button
> 
> 
> 
> The result after clicking "执行时间" does not match the time zone.

this issue is like #10833
