### ISSUE TITLE
[Bug] [dependent task] dependent task failed when the process to be dependent on that have forbidden to run task

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#10899]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

a process PA contain any forbidden to run task , when process PB have task TB dependent on PA, then TB will fail.
But in dolphin2.0.5 this scenario will work.

### What you expected to happen

work as before

### How to reproduce

a process PA contain any forbidden to run task , when process PB have task TB dependent on PA, then TB will fail.

### Version

2.0.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lordk911** [comment]
If there are forbidden tasks in workflow A and tasks in workflow B depend on the entire workflow A, then workflow B will fail, even if WORKFLOW A succeeds

如果工作流A里有禁止运行的任务，工作流B里的任务依赖整个工作流A，那么工作流B会失败，即使A成功了

**Comment by lordk911** [comment]
Is there any new progress?

**Comment by lordk911** [comment]
@JinyLeeChina please take a look at this issue

**Comment by brave-lee** [comment]
#10952
