### ISSUE TITLE
[Bug] [SWITCH-PLUGIN] Switch task plugin wrong class name and no param validation

### ISSUE THREAD

**Issue by Tianqi-Dotes** [apache/dolphinscheduler#10893]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

the code use switch task plugin names subprocess which goes wrong.
there is no validation to the default next node, so you can create a switch task without default next node. when conditions not triggered, the switch task fails

### What you expected to happen

1. change the subprocess class code name to switch
2. add validations to default next node existence
3. add validations to conditions to check when there is condition there must have next node

### How to reproduce

create new switch task and not fill the default next node, when no condition triggers the task instance fails.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
add frontend next node  validation

**Comment by Amy0104** [comment]
> 

Got it.
