### ISSUE TITLE
[Bug] [api] admin can't see dependent task's dependent on process name but only code

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#10901]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

admin can't see dependent task's dependent on process name but only code , if I use a normal user , all is ok.  
both in version 2.0.5\2.0.6

![aa](https://user-images.githubusercontent.com/19989300/178459370-44535ac4-cd97-477c-89ab-ad8473238393.png)

### What you expected to happen

admin can see dependent task's dependent on process name 

### How to reproduce

use admin user to see a project's process which not belong to admin

### Version

2.0.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This has been fixed in version 3.0.0. #8922
