### ISSUE TITLE
[Bug] [LoggerServer] dependent task can't see log

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#10906]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

dependent task run on master node , but LoggerServer start with worker node , if the host only have a master node , so there is no LoggerServer , then when dependent task fail , I can't see the detail. if I start LoggerServer on master node by hand, then I can see the log detail

### What you expected to happen

LoggerServer start on master by default 

### How to reproduce

dependent task run on master node , but LoggerServer start with worker node , if the host only have a master node , so there is no LoggerServer , then when dependent task fail , I can't see the detail. if I start LoggerServer on master node by hand, then I can see the log detail

### Version

2.0.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
LoggerServer has been optimized and embedded into masterServer and workerServer in version 3.0.0.
