### ISSUE TITLE
[DSIP-13][Feature][Python] Adding a resource file loading plugin to the DolphinScheduler Python API	

### ISSUE THREAD

**Issue by xdu-chenrj** [apache/dolphinscheduler#10911]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* [x] Decorator implementation
  * [x] A simple Resource plugin that supports local files
  * [x] Local Resource Plugin Refinement
* [x] GitHub Resource Plugin
  * [x] Private Repository Authentication
  * [x] File Reading
    * [x] Shared Repository File Reading
    * [x] Private Repository File Reading
* [x] GitLab Resource Plugin
  * [x] Private Authentication
  * [x] File Reading
* [x] Amazon S3 Resource Plugin
  * [x] Private Authentication
  * [x] File Reading
* [x] AliCloud OSS Resource Plugin
  * [x] Private Authentication
  * [x] File Reading
* [x] Other special file reads for different plugins

 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Same TIPs from https://github.com/apache/dolphinscheduler/issues/10905#issuecomment-1181596546

**Comment by zhongjiajie** [comment]
tests and documents not included in your tasks, it is ok not exists in tasks but I hope you will submit both tests and documents in each task's PR, Specifically how a developer develops a new plugin

**Comment by xdu-chenrj** [comment]
> tests and documents not included in your tasks, it is ok not exists in tasks but I hope you will submit both tests and documents in each task's PR, Specifically how a developer develops a new plugin

ok

**Comment by EricGao888** [comment]
@xdu-chenrj I could help with the `AliCloud OSS Resource Plugin` if you don't mind : )

**Comment by EricGao888** [comment]
> * rivate Authentication
>         
>       
>   
>       Create an issue with the title Private Authentication. Press Enter to convert to an issue instantly. Press Option-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> * [ ]  File Reading

related: #11683

**Comment by EricGao888** [comment]
> @xdu-chenrj I could help with the `AliCloud OSS Resource Plugin` if you don't mind : )

related: #11683

**Comment by zhongjiajie** [comment]
maybe we should better follow the [DSIP](https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/DSIP.html) process and introduce this feature to our community

**Comment by zhongjiajie** [comment]
already done

**Comment by Capricorn0010** [comment]
have a test sample yaml file？
