### ISSUE TITLE
[Bug] [DataSource] MySQL Connection number increasing 

### ISSUE THREAD

**Issue by fhygh** [apache/dolphinscheduler#10918]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

in dolphin worker-server, mysql connection number increasing always, which lead mysql server cannot work.
![image](https://user-images.githubusercontent.com/25889738/178624684-ca6fa8eb-73e5-4dde-b0f2-d45a73208ca5.png)

while the mysql connection like below:
![image](https://user-images.githubusercontent.com/25889738/178625005-caf48f0d-b3d4-434f-8fca-3c4073a654ff.png)

### What you expected to happen

mysql connection number keep in normal number, 

### How to reproduce

use MySQL DataSource to perform frequent operations, such as query and create table/delete table/update table.

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
I just see the latest code, we didn't use connection pool in SQL task, so the hikari pool config isn't used for SQL task.

Right now, for each task we will create a new connection and will close this connection after finished. I am not clear if we need to use connection pool in SQL task.

cc @caishunfeng @SbloodyS

**Comment by SbloodyS** [comment]
> I just see the latest code, we didn't use connection pool in SQL task, so the hikari pool config isn't used for SQL task.
> 
> Right now, for each task we will create a new connection and will close this connection after finished. I am not clear if we need to use connection pool in SQL task.
> 
> cc @caishunfeng @SbloodyS

I think we can provide an configure option of whether use connection pool to users in the data source center.

But I think using connection pooling in SQL task may cause task blocking since ds is a distributed big data scheduling system. It is common to execute hundreds of tasks in parallel. The maximum number of connection supported in the database of my current production environment is 10000.

As a result, it's better to expand the database or decrease the SQL task's parallelism. @fhygh

**Comment by caishunfeng** [comment]
> I just see the latest code, we didn't use connection pool in SQL task, so the hikari pool config isn't used for SQL task.
> 
> Right now, for each task we will create a new connection and will close this connection after finished. I am not clear if we need to use connection pool in SQL task.
> 
> cc @caishunfeng @SbloodyS

Another point is that ds has many datasource type, I'm not sure we can use a connection pool to support all the datasource type.

**Comment by fhygh** [comment]
@SbloodyS  in dolphin 1.3.5, no this problem.
![image](https://user-images.githubusercontent.com/25889738/178927567-5dee3433-0494-4fd2-99e2-fe70be61690a.png)

all mysql connection is created by DriverManager and closed in finally

**Comment by fhygh** [comment]
> I just see the latest code, we didn't use connection pool in SQL task, so the hikari pool config isn't used for SQL task.
> 
> Right now, for each task we will create a new connection and will close this connection after finished. I am not clear if we need to use connection pool in SQL task.
> 
> cc @caishunfeng @SbloodyS

@ruanwenjun  hello, we create HikariDataSource pool indeed, and you can test on SQL task with mysql datasource connection, you will see log "Creating HikariDataSource pool for maxActive" in worker-server log which is present in JDBCDataSourceProvider.java file.

**Comment by hwb1992** [comment]
This is a bug.When guava cache remove datasource,it needs to invoke close functin,which is never call in current version. I use 3.0.0-beta2-release.
I add a removeListiner in guava cache to invoke close function, and in CommonDataSourceClient class, i call dataSource.close function in close method to release db pool. Now the connection will release..
I hope community can fix this problem.

**Comment by ruanwenjun** [comment]
> > I just see the latest code, we didn't use connection pool in SQL task, so the hikari pool config isn't used for SQL task.
> > Right now, for each task we will create a new connection and will close this connection after finished. I am not clear if we need to use connection pool in SQL task.
> > cc @caishunfeng @SbloodyS
> 
> @ruanwenjun hello, we create HikariDataSource pool indeed, and you can test on SQL task with mysql datasource connection, you will see log "Creating HikariDataSource pool for maxActive" in worker-server log which is present in JDBCDataSourceProvider.java file.

OK, I see the latest code, we will create a HikariDataSource for each datasource, it will use the `BaseConnectionParam` to create HikariDataSource, it will use `spring.datasource.maxActive` to set the max pool size, but in application.yml we use `maximum-pool-size` :).
```java
dataSource.setMaximumPoolSize(PropertyUtils.getInt(Constants.SPRING_DATASOURCE_MAX_ACTIVE, 50));
```
cc @caishunfeng

**Comment by ruanwenjun** [comment]
> This is a bug.When guava cache remove datasource,it needs to invoke close functin,which is never call in current version. I use 3.0.0-beta2-release.
> I add a removeListiner in guava cache to invoke close function, and in CommonDataSourceClient class, i call dataSource.close function in close method to release db pool. Now the connection will release..
> I hope community can fix this problem.

Good catch, are you willing to submit a PR to fix?

**Comment by ruanwenjun** [comment]
I submit #11120 to fix this.

**Comment by hwb1992** [comment]
Nice try bro.

**Comment by hwb1992** [comment]
> 
Nice try bro

**Comment by hwb1992** [comment]
> I submit #11120 to fix this.

Nice try bro

**Comment by fhygh** [comment]
@ruanwenjun  great job, thank you .

**Comment by ruanwenjun** [comment]
> @ruanwenjun great job, thank you .

You are welcome.
