### ISSUE TITLE
[Feature][API-SERVER] subprocess instance can be query out from web

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#10928]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

now subprocess instance can't be query out from web, this is hard to debug in some situation

### Use case

I don't know why dolphinscheduler design subprocess instance can't be query out from web side , some times I can only see subprocess task keep running and can't stop it , because I could not find the process instance

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You can find subprocess in the workflow instance page.
