### ISSUE TITLE
[Question] worker does not work

### ISSUE THREAD

**Issue by 704237006** [apache/dolphinscheduler#10924]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After the task is executed, it is always in the state of submit success, and the worker has no new log. In the past, it's good to restart the worker. This time, it's still abnormal. There are no logs in the worker. Why?

任务执行后一直处于 submit success状态，worker一直没有新的日志。以前这种情况重启worker就好了，这次重启后还是不正常，worker 里面没有日志，这是为什么呢？
master log
![c939ee0ee168f17fcee18fde6cbf565](https://user-images.githubusercontent.com/42430068/178647023-689e04dd-a094-4137-b557-ec8e5c33fcf4.png)
worker log
![image](https://user-images.githubusercontent.com/42430068/178647256-d873f792-a509-476f-a3a3-66eb11b381e7.png)

### What you expected to happen

The worker can receive the communication from the master and execute it.

worker能接收到master的通信，执行下去。

### How to reproduce

I don't know how to reproduce it

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Has the task dispatched to worker?

**Comment by 704237006** [comment]
> 

From the first picture, it is distributed, and the table t_ ds_ task_ Instance has a new row.

**Comment by 704237006** [comment]
> Has the task dispatched to worker?


From the first picture, it is dispatched , and the table t_ ds_ task_ Instance has a new row.

**Comment by ruanwenjun** [comment]
> > Has the task dispatched to worker?
> 
> From the first picture, it is dispatched , and the table t_ ds_ task_ Instance has a new row.

In fact, the task will first submit to db and then really dispatch to worker, I guess, the task hadn't been dispatched to worker, you may need to provide more logs.
