### ISSUE TITLE
[Bug] The downstream task instance is not triggered to execute when I click the button for force success

### ISSUE THREAD

**Issue by JensonZou** [apache/dolphinscheduler#10920]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When the task retries the maximum number of times and failed, and I click the button for force success, the downstream task instance is not triggered to execute.

### What you expected to happen

I think the downstream task should be triggered when I click the button for force success, if not, what's the point of force success.

### How to reproduce

The problem will reproduce when you force a task successed that the task retries the maximum number of times and failed

### Version

2.0.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
@JensonZou Hi, you can try to `Recovery Failed` the workflow after force success the task.

**Comment by JensonZou** [comment]
> @JensonZou Hi, you can try to `Recovery Failed` the workflow after force success the task.

Thank you for your reply. I think it's a way, but this requires the whole process to end

**Comment by SbloodyS** [comment]
> > @JensonZou Hi, you can try to `Recovery Failed` the workflow after force success the task.
> 
> Thank you for your reply. I think it's a way, but this requires the whole process to end

If you want to bypass the whole workflow you can use dry run.
