### ISSUE TITLE
[Feature][Trigger]The downstream task instance can be triggered to execute when I click the button for force success

### ISSUE THREAD

**Issue by JensonZou** [apache/dolphinscheduler#10934]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When the task retries the maximum number of times and failed, and I click the button for force success, the downstream task is not triggered to execute. I want it to be triggered. It will be a nice feature for dolphinscheduler.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aikuyun** [comment]
+1

**Comment by bwin90** [comment]
+1
