### ISSUE TITLE
[Bug] [task-plugin] There is an error in the logic of judge depend item finished in the dependent node

### ISSUE THREAD

**Issue by Tandoy** [apache/dolphinscheduler#10936]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.a workflow exists manual run and schedule run
2.the scheduled execution end time is later than the manual execution time
3.dependent node detection failed

![微信图片_20220713093652](https://user-images.githubusercontent.com/56899730/178693956-99f09c96-2a7b-48f3-bade-b99a71c0a6c0.png)

![微信图片_20220713093657](https://user-images.githubusercontent.com/56899730/178694055-0551cc52-dd7a-4268-9444-ef1b61978a8c.png)

### What you expected to happen

dependent node detection success

### How to reproduce

I found that the dependent node adopts the end time of process instance when taking the last process instance. Shouldn't it be the start time of the process instance?

[https://github.com/apache/dolphinscheduler/blob/dev/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/utils/DependentExecute.java](url)

![企业微信截图_20220713170623](https://user-images.githubusercontent.com/56899730/178695911-38ccefd3-1e5d-480e-9e6e-8405512aa84c.png)

### Anything else

If this is a bug, I will try to fix it.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Please describe your problem clearly, and AFAIK, we use endTime in dependent node to judge if the dependent node finished is our expected. cc @caishunfeng

**Comment by Tandoy** [comment]
> Please describe your problem clearly, and AFAIK, we use endTime in dependent node to judge if the dependent node finished is our expected. cc @caishunfeng

IMO If there are multiple run records in the workflow, it should not be through the start time to obtain the last and latest workflow instance. As I described in what happened. cc @caishunfeng

**Comment by ruanwenjun** [comment]
> > Please describe your problem clearly, and AFAIK, we use endTime in dependent node to judge if the dependent node finished is our expected. cc @caishunfeng
> 
> IMO If there are multiple run records in the workflow, it should not be through the start time to obtain the last and latest workflow instance. As I described in what happened. cc @caishunfeng

OK, I understand, I agree with we need to use endTime rather than startTime.

**Comment by Tandoy** [comment]
> > > Please describe your problem clearly, and AFAIK, we use endTime in dependent node to judge if the dependent node finished is our expected. cc @caishunfeng
> > 
> > 
> > IMO If there are multiple run records in the workflow, it should not be through the start time to obtain the last and latest workflow instance. As I described in what happened. cc @caishunfeng
> 
> OK, I understand, I agree with we need to use endTime rather than startTime.

If there are schedule run and manual run in a workflow during the interval, shouldn't we get the latest run status to judge, not the last? This is my doubt. I look forward to your answer. Thank you

**Comment by caishunfeng** [comment]
I think use startTime or endTime is ok, since manual is only executed when schedule error or long time running. If schedule one is running for a long time, it will usually be killed first.

**Comment by Tandoy** [comment]
> I think use startTime or endTime is ok, since manual is only executed when schedule error or long time running. If schedule one is running for a long time, it will usually be killed first.

yes,manual is only executed when schedule error or long time running.However, the scheduled execution end time may be later than the manual execution time due to resources or network reasons.In this case, if we use the end time to judge, we will not get the latest process instance status.As I described in what happened.
