### ISSUE TITLE
can't use python3

### ISSUE THREAD

**Issue by weile321** [apache/dolphinscheduler#10939]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

version: 2.0.5
In the **Environment managemen**t, I had set  **PYTHON_HOME=/usr/bin/python3** . But when I exec the python scripts, it still used the **default python2.7**

### What you expected to happen

I want to use python3

### How to reproduce

It still exists.

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
2.0.5 doesn't support set PYTHON_HOME, you need to link your `python3` to `python`
