### ISSUE TITLE
2.0.6 can't run

### ISSUE THREAD

**Issue by weile321** [apache/dolphinscheduler#10944]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

test@ub18-test-dolphinscheduler:~/apache-dolphinscheduler-2.0.6-src/docker/docker-swarm$ clear
test@ub18-test-dolphinscheduler:~/apache-dolphinscheduler-2.0.6-src/docker/docker-swarm$ sudo docker pull dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler:latest
latest: Pulling from apache/dolphinscheduler
Digest: sha256:e1303513da517f594132a03d772dc29465a83d0e5fbc0297f97c1752c2e16a09
Status: Image is up to date for dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler:latest
dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler:latest
test@ub18-test-dolphinscheduler:~/apache-dolphinscheduler-2.0.6-src/docker/docker-swarm$ **sudo docker-compose up -d**
Pulling dolphinscheduler-api (apache/dolphinscheduler:2.0.6)...
**ERROR: manifest for apache/dolphinscheduler:2.0.6 not found: manifest unknown: manifest unknown**

### What you expected to happen

$:   **sudo docker-compose up -d**
$:  Pulling dolphinscheduler-api (apache/dolphinscheduler:2.0.6)...
    **ERROR: manifest for apache/dolphinscheduler:2.0.6 not found: manifest unknown: manifest unknown**

### How to reproduce

always

### Version

2.0.6

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by weile321** [comment]
ERROR: manifest for apache/dolphinscheduler:2.0.6 not found: manifest unknown: manifest unknown

**Comment by SbloodyS** [comment]
Duplicated with #10956.
