### ISSUE TITLE
[Improvement][UI][Dependent Task Plugin] The workflow or task name is too long and results in incomplete display

### ISSUE THREAD

**Issue by shangeyao** [apache/dolphinscheduler#10942]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The workflow or task name is too long and results in incomplete display

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
Hi @shangeyao, thanks for submitting this issue. May I ask how you want to improve this? Any specific ideas?
