### ISSUE TITLE
2.0.6 on docker development, can't run

### ISSUE THREAD

**Issue by weile321** [apache/dolphinscheduler#10956]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

step1: docker pull dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler:latest  --it'ok

step2: docker-compose up -d
           -- Pulling dolphinscheduler-api (apache/dolphinscheduler:2.0.6)...
               **ERROR: manifest for apache/dolphinscheduler:2.0.6 not found: manifest unknown: manifest unknown**

### What you expected to happen

I want to use 2.0.6

### How to reproduce

flow me step:

step1:    tar -zxvf apache-dolphinscheduler-2.0.2-src.tar.gz
step2:    cd apache-dolphinscheduler-2.0.6-src/docker/docker-swarm
step3:    docker pull dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler:latest
sterp4:   docker-compose up -d
              -- then the error occurs:  
                                            Pulling dolphinscheduler-api (apache/dolphinscheduler:2.0.6)...
                                           **ERROR: manifest for apache/dolphinscheduler:2.0.6 not found: manifest unknown: manifest 
                                             unknown**

### Version

2.0.6

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
@weile321 Sometimes, docker images will be pushed to dockerhub a few days later than the binary release. and the good new is, now version 2.0.6  is available in docker hub now https://hub.docker.com/repository/docker/apache/dolphinscheduler/tags?page=1&ordering=last_updated

**Comment by weile321** [comment]
@zhongjiajie hi, does 2.0.6 support python3 ? thx

**Comment by zhongjiajie** [comment]
> @zhongjiajie hi, does 2.0.6 support python3 ? thx

It suppport only if your machine running  worker server have python3 in env and you config it to dolphinscheudler `PYTHON_HOME`
