### ISSUE TITLE
[bug] [master] task can't use [out] type param

### ISSUE THREAD

**Issue by huangchenguang123** [apache/dolphinscheduler#10962]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

task can't use [out] type param.
![image](https://user-images.githubusercontent.com/37766284/178894470-795336f9-acfc-4cae-b71f-f7c67030f03a.png)

sqlTask use prepareParamsMap to replace param.
![image](https://user-images.githubusercontent.com/37766284/178909266-329e0c67-3955-452c-900e-7be3c74ec239.png)

prepareParamsMap uses varPool of parameters.
![image](https://user-images.githubusercontent.com/37766284/178909396-a04b55e6-a07f-405d-9a0f-4affaaeb4c9d.png)

parameters's varPool uses taskInstance.taskParams
![image](https://user-images.githubusercontent.com/37766284/178909832-74519f7b-a0b0-4225-8e1d-f06f7255847b.png)

BUT prepareParamsMap is created earlier than assignment of taskInstance.taskParams.varpool.
![image](https://user-images.githubusercontent.com/37766284/178910179-96612f94-8565-447a-8859-1fa9677d5cac.png)

So taskInstance.taskParams..varpool is always null when prepareParamsMap is created.

### What you expected to happen

task can use [out] type param

### How to reproduce

1.create a task with [out] type task
2.create a sql use it.

### Anything else

none.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @huangchenguang123  #11053 had fixed the out param pass, you can check it again in dev.

**Comment by huangchenguang123** [comment]
> Hi @huangchenguang123 #11053 had fixed the out param pass, you can check it again in dev.

Thanks, this is also a way to solve the issue. I will close my issue and pr.

**Comment by huangchenguang123** [comment]
close by #11053
