### ISSUE TITLE
[Bug] [TaskGroupOption] Create a task group to bypass the project name

### ISSUE THREAD

**Issue by SnowMoon-Dev** [apache/dolphinscheduler#10965]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Create a task group to bypass the project name

### What you expected to happen

Some required fields are required to successfully create the project

### How to reproduce

1. crate task group option
2. no select project
3. click confirm

### Anything else

<img width="1814" alt="image" src="https://user-images.githubusercontent.com/42627702/178912576-946cbd77-1882-4381-9da4-123b2439aa9e.png">

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
I think it's not a bug because TaskGroup can use to controll all the workflows, so the project is not the required field.
