### ISSUE TITLE
[Bug] [alert service] email alert failed

### ISSUE THREAD

**Issue by abluson** [apache/dolphinscheduler#10961]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The alert service is running.
![企业微信截图_16577684619245](https://user-images.githubusercontent.com/109258081/178890328-be13c1d4-8830-4407-97bc-6f6471491abc.png)
When running a work flow, see the alert-server log.
![企业微信截图_16577684067877](https://user-images.githubusercontent.com/109258081/178890481-f985564c-e606-4a5f-ac68-1986a1508af4.png)

### What you expected to happen

I have installed CDH 6.3.2.Enviroment is healthy.

### How to reproduce

Restart dolphinscheduler, run a new work flow to check this problem.

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @abluson , Could you describe the steps to reproduce this problem?

**Comment by abluson** [comment]
I created a alarm instance named "alarm_instance1", and created a alarm group named "alarm_group1", then created a work flow named "test_flow1" and used alarm_group1 and runned this work flow.
![企业微信截图_1657776928378](https://user-images.githubusercontent.com/109258081/178908193-51d61b91-614e-465e-8aac-f617c490744f.png)
![企业微信截图_16577769721281](https://user-images.githubusercontent.com/109258081/178908212-020c7928-5aba-4436-9dde-b9078be6f6e3.png)
![企业微信截图_16577712205795](https://user-images.githubusercontent.com/109258081/178908222-f2b93088-35f5-4112-b08c-721973397301.png)

**Comment by caishunfeng** [comment]
Hi @abluson can you add the description of the content and the alert type?

**Comment by Tianqi-Dotes** [comment]
hi, when you send an email alert, I think it is necessary to fill in the username & password.
select `Auth` yes
STARTTLS yes
SSL yes
if necessary.
and will check out why this error happens.

**Comment by Tianqi-Dotes** [comment]
hi,i cannot reproduce this, I got no username warnings. and the configuration is 
![image](https://user-images.githubusercontent.com/36755957/182065451-1ed13d9c-d0a6-4ded-bfea-5edceb59ed44.png)
![image](https://user-images.githubusercontent.com/36755957/182065501-664b921a-d2a1-4ad5-81b5-5bca08958e0d.png)
I suggest to fill the configs 
I think it is necessary to fill in the username & password.
select Auth yes
STARTTLS yes
SSL yes
if necessary.
