### ISSUE TITLE
[Feature][style] Replace checkstyle plugin with spotless to automatically fix formatting errors

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#10963]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Currently, DS CI checks formatting errors. However, it will be much more conveniently if we could find those style errors and automatically fix them before pushing the code.
* We could introduce `spotless` plugin into DS and use it to automatically fix the style.
* https://github.com/diffplug/spotless
* https://github.com/diffplug/spotless/tree/main/plugin-maven

### Use case

* At present, DS uses `checkstyle` plugin. However, there are tons of legacy formatting errors in the project every time we build the project. Thus, in practice, some developers tend to use `-Dcheckstyle.skip` flag when building the project and this make the `style check` a little bit awkward. 
* Huge advantage of using `Spotless` over `CheckStyle` is in addition to check the formatting of the code it also has `apply` goal that fixes all the style and formatting. With `Spotless`, we could fix the legacy formatting errors once for all and developers could fix new format errors with a single line of command `mvn spotless:apply`.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuxt2015** [comment]
I agree to replace CheckStyle with Spotless. Resolve  format problem of the code as soon as possible

**Comment by EricGao888** [comment]
BTW, we could fix the formatting and style errors incrementally, together with unit tests. See: #10573 
One convenient way is when refactoring some UTs, we fix the formatting and style errors of both the testing and tested part. WDYT @ruanwenjun @zhongjiajie @zhuxt2015

**Comment by EricGao888** [comment]
Some updates, see: https://github.com/apache/dolphinscheduler/pull/11272#issuecomment-1203511210

**Comment by zhongjiajie** [comment]
@ruanwenjun have other oppoin
