### ISSUE TITLE
[Improvement][UT] Upgrade junit to 5.+

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#10976]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Right now, we still use junit 4.+ in our repo, I hope we can upgrade to [Junit 5.+](https://junit.org/junit5/docs/current/user-guide/#writing-tests), then we can easy to write the UT, JUnit 5 provide some useful feature, e.g. `assertThrow`, `assertTimeout `...

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
cc #10573

**Comment by EricGao888** [comment]
What about using `TestNG`?

**Comment by ruanwenjun** [comment]
> What about using `TestNG`?

This may need to refactor all test code, if we want to use `TestNG` to replace Junit

**Comment by EricGao888** [comment]
> > What about using `TestNG`?
> 
> This may need to refactor all test code, if we want to use `TestNG` to replace Junit

@ruanwenjun  Yes. At this moment, I think we have about 4 people, me and my colleagues who will work on the UT refactoring. It is possible for us to refactor all test code and fix all related style / formatting issues. The question lying between choosing `TestNG` and `jUnit` is whether it is necessary to replace one with another. So far, I've found some advantages of `TestNG` over `jUnit`:

* `TestNG` supports running UT in parallelism.
* `TestNG` supports `testing group`.
* `TestNG` supports an easier way to pass data into testing method using `Data Provider`.
* `TestNG` supports `Dependency Test`.
* `TestNG` supports `Parameterization` through `xml` configuration.

Some related materials:
* https://www.youtube.com/watch?v=OWXWQE4pL_0
* https://www.guru99.com/junit-vs-testng.html

Although `TestNG` is more powerful, it seems that it is not a `must` to switch `jUnit` to `TestNG` 🤣 

WDYT?

**Comment by EricGao888** [comment]
> > > What about using `TestNG`?
> > 
> > 
> > This may need to refactor all test code, if we want to use `TestNG` to replace Junit
> 
> @ruanwenjun Yes. At this moment, I think we have about 4 people, me and my colleagues who will work on the UT refactoring. It is possible for us to refactor all test code and fix all related style / formatting issues. The question lying between choosing `TestNG` and `jUnit` is whether it is necessary to replace one with another. So far, I've found some advantages of `TestNG` over `jUnit`:
> 
> * `TestNG` supports running UT in parallelism.
> * `TestNG` supports `testing group`.
> * `TestNG` supports an easier way to pass data into testing method using `Data Provider`.
> * `TestNG` supports `Dependency Test`.
> * `TestNG` supports `Parameterization` through `xml` configuration.
> 
> Some related materials:
> 
> * https://www.youtube.com/watch?v=OWXWQE4pL_0
> * https://www.guru99.com/junit-vs-testng.html
> 
> Although `TestNG` is more powerful, it seems that it is not a `must` to switch `jUnit` to `TestNG` 🤣
> 
> WDYT?

If we choose not to switch `jUnit` to `TestNG`, I support upgrading `jUnit` to `5.+`

**Comment by ruanwenjun** [comment]
> > > What about using `TestNG`?
> > 
> > 
> > This may need to refactor all test code, if we want to use `TestNG` to replace Junit
> 
> @ruanwenjun Yes. At this moment, I think we have about 4 people, me and my colleagues who will work on the UT refactoring. It is possible for us to refactor all test code and fix all related style / formatting issues. The question lying between choosing `TestNG` and `jUnit` is whether it is necessary to replace one with another. So far, I've found some advantages of `TestNG` over `jUnit`:
> 
> * `TestNG` supports running UT in parallelism.
> * `TestNG` supports `testing group`.
> * `TestNG` supports an easier way to pass data into testing method using `Data Provider`.
> * `TestNG` supports `Dependency Test`.
> * `TestNG` supports `Parameterization` through `xml` configuration.
> 
> Some related materials:
> 
> * https://www.youtube.com/watch?v=OWXWQE4pL_0
> * https://www.guru99.com/junit-vs-testng.html
> 
> Although `TestNG` is more powerful, it seems that it is not a `must` to switch `jUnit` to `TestNG` 🤣
> 
> WDYT?

AFAIK, Junit5+ can support these features.

**Comment by EricGao888** [comment]
> > > > What about using `TestNG`?
> > > 
> > > 
> > > This may need to refactor all test code, if we want to use `TestNG` to replace Junit
> > 
> > 
> > @ruanwenjun Yes. At this moment, I think we have about 4 people, me and my colleagues who will work on the UT refactoring. It is possible for us to refactor all test code and fix all related style / formatting issues. The question lying between choosing `TestNG` and `jUnit` is whether it is necessary to replace one with another. So far, I've found some advantages of `TestNG` over `jUnit`:
> > 
> > * `TestNG` supports running UT in parallelism.
> > * `TestNG` supports `testing group`.
> > * `TestNG` supports an easier way to pass data into testing method using `Data Provider`.
> > * `TestNG` supports `Dependency Test`.
> > * `TestNG` supports `Parameterization` through `xml` configuration.
> > 
> > Some related materials:
> > 
> > * https://www.youtube.com/watch?v=OWXWQE4pL_0
> > * https://www.guru99.com/junit-vs-testng.html
> > 
> > Although `TestNG` is more powerful, it seems that it is not a `must` to switch `jUnit` to `TestNG` 🤣
> > WDYT?
> 
> AFAIK, Junit5+ can support these features.

@ruanwenjun Sounds good to me. I will take this issue.

I found a post about differences between `jUnit4` and `jUnit5`, as well as how to migrate: https://blogs.oracle.com/javamagazine/post/migrating-from-junit-4-to-junit-5-important-differences-and-benefits

**Comment by caishunfeng** [comment]
Great! It seems use Junit5+ can achieve the same with less change.

**Comment by EricGao888** [comment]
I'm working on this, will submit a PR tomorrow or next week.

**Comment by EricGao888** [comment]
In DolphinScheduler, we sometimes use `Powermock` for UTs. However, it seems `Powermock` does not and will not support jUnit 5. https://github.com/powermock/powermock/issues/929

**Comment by ruanwenjun** [comment]
> In DolphinScheduler, we sometimes use `Powermock` for UTs. However, it seems `Powermock` does not and will not support jUnit 5. [powermock/powermock#929](https://github.com/powermock/powermock/issues/929)


Can we use Mokito to replace powermock?

**Comment by EricGao888** [comment]
> > In DolphinScheduler, we sometimes use `Powermock` for UTs. However, it seems `Powermock` does not and will not support jUnit 5. [powermock/powermock#929](https://github.com/powermock/powermock/issues/929)
> 
> Can we use Mokito to replace powermock?

Seems `powermock` helps mock the `static`, `private` and `final` methods more easily. Anyway I will look into it and see whether there is a way to use `mockito` to replace `powermock`.

**Comment by zhongjiajie** [comment]
> > > In DolphinScheduler, we sometimes use `Powermock` for UTs. However, it seems `Powermock` does not and will not support jUnit 5. [powermock/powermock#929](https://github.com/powermock/powermock/issues/929)
> > 
> > 
> > Can we use Mokito to replace powermock?
> 
> Seems `powermock` helps mock the `static`, `private` and `final` methods more easily. Anyway I will look into it and see whether there is a way to use `mockito` to replace `powermock`.

If we can find the alternative or the method to do it, we can get rid of it
