### ISSUE TITLE
[Improvement][API] Reconstruct JSON defined by workflow's api

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#10971]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Reconstruct JSON defined by workflow's api

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
it is improvement so I move to 3.1.0

**Comment by SbloodyS** [comment]
> it is improvement so I move to 3.1.0

Sure.
