### ISSUE TITLE
[Feature][Api] Refactor org.apache.dolphinscheduler.api.controller.ResourcesController

### ISSUE THREAD

**Issue by liguotian** [apache/dolphinscheduler#10983]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

#10257 Suggest refactor the backend api 
Refactor  org.apache.dolphinscheduler.api.controller.ResourcesController

### Use case

* rename ResourcesController to ResourcesV2Controller ,requestmap to /v2/xxxxx
* replace The input and output parameters if map or json to POJO
* define explicit error info or message
* supplement Api doc if have enumeration ,sample data is required for each parameter

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liguotian** [comment]
@SbloodyS  I see some  ` TODO`  feature like 
```
//todo verify the directory name
```
Do we already have some request param verification frameworks like  hibernate validator。Or we need to develop a Specialized  for dolphinscheduler ？

**Comment by SbloodyS** [comment]
Currently, there is no framework. And it is judged in the service layer. @liguotian

**Comment by Zzih** [comment]
I see that there are many functions inside the taskinstancecontroller,If I participate in the TaskInstanceController task, do I only need to modify the queryTaskListPaging forceTaskSuccess functions in TaskInstanceV2Controller?
