### ISSUE TITLE
[Feature][python] Combine gateway.entry_point call in python api side

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#10988]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We use `gateway.entry_point` anywhere when we need to cal some function from pythonGateway service now in our python api. it is may our code ugly and hard to maintain. such as https://github.com/apache/dolphinscheduler/blob/ec4ce2b57313b2a38f4a36efac40a281a4f05f4e/dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/side/tenant.py#L44 and https://github.com/apache/dolphinscheduler/blob/ec4ce2b57313b2a38f4a36efac40a281a4f05f4e/dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/side/queue.py#L41

we should better add a new class to hold all those method call, to maintain or test is easier.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hiSandog** [comment]
I'm going to try to do this optimization

**Comment by zhongjiajie** [comment]
It is a Far-reaching influence change, and maybe we should discussion it first. I have two way out of my mind

1. we are already have https://github.com/apache/dolphinscheduler/blob/bf5f7a88c5a7ef1c7772c6b9c5830fd72dc599ec/dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/java_gateway.py#L30-L47, I think we should covert file into module(or keep file), and migrate all `gateway.entry_point.createTenant` call into this file or modules,

```py
def create_tenant(name, description, queue_name):
    # we may also add some parameter verify before call
    return gateway.entry_point.createTenant(name, description, queue_name)
```

and we only need to call function `create_tenant` when we need.

2. we have `models` module in path https://github.com/apache/dolphinscheduler/tree/dev/dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/models, and the `models` in python usually mean connection to data store system, we can take for all java gateway service is Python API DAO layer, and we migrate all `gateway.entry_point` call into module `modules`(create them if not exists)

**Comment by hiSandog** [comment]
> It is a Far-reaching influence change, and maybe we should discussion it first. I have two way out of my mind
> 
> 1. we are already have https://github.com/apache/dolphinscheduler/blob/bf5f7a88c5a7ef1c7772c6b9c5830fd72dc599ec/dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/java_gateway.py#L30-L47
>    , I think we should covert file into module(or keep file), and migrate all `gateway.entry_point.createTenant` call into this file or modules,
> 
> ```python
> def create_tenant(name, description, queue_name):
>     # we may also add some parameter verify before call
>     return gateway.entry_point.createTenant(name, description, queue_name)
> ```
> 
> and we only need to call function `create_tenant` when we need.
> 
> 2. we have `models` module in path https://github.com/apache/dolphinscheduler/tree/dev/dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/models, and the `models` in python usually mean connection to data store system, we can take for all java gateway service is Python API DAO layer, and we migrate all `gateway.entry_point` call into module `modules`(create them if not exists)

I think the first plan is better.
In the first plan, the code for API calls is more concentrated.
API calls may have multiple methods that are not easily grouped into a single module, so the second plan may not be well implemented.

**Comment by zhongjiajie** [comment]
close by #11330
