### ISSUE TITLE
DS for long-run/ daemon task

### ISSUE THREAD

**Issue by xiashiwendao** [apache/dolphinscheduler#10985]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I have a long-run task, just like daemon task; which listen a port and handle message received.

I try to manage it by DS, feel a little hard, for I can't quick postion the task(it hide in so many schedule task in the "process Instance" list)

Dose DS have the function(for display and other operatin) I can use for long-run task?

Thanks very much

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuxt2015** [comment]
Please search task name in task instance

**Comment by EricGao888** [comment]
> Please search task name in task instance

+1, I think you could search for it in `task instance` or `workflow instance` page. I will close this issue for now. If you have further questions, you are welcome to join the slack channel: https://join.slack.com/t/asf-dolphinscheduler/shared_invite/zt-1cjrb7im9-Pb8jtuGBLhNrK_GiDRIEbA
@xiashiwendao
