### ISSUE TITLE
[Improvement][Master] Improve task dispatch to batch dispatch

### ISSUE THREAD

**Issue by zhuxt2015** [apache/dolphinscheduler#10996]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

## 目前的task分发逻辑问题
1、分配时只考虑线程池队列空闲情况, 没有考虑worker的负载过高和可用内存较少的因素
2、一次只分发一个task给worker

## 优化
1、批量分配task
2、超过负载的worker暂时不分发task
3、分发task的数量参考当前worker可用的内存大小

## 流程图
![task批量分发](https://user-images.githubusercontent.com/13765310/179180003-fedcb135-c728-462b-a305-01798b798b3a.jpg)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jieguangzhou** [comment]
I think we can treat it as a [knapsack problem](https://en.wikipedia.org/wiki/Knapsack_problem), and use the Hungarian algorithm to solve it.

1. Worker available memory as backpack capacity
2. Task memory is used as item weight
3. Task priority as item value (Or other reference values as values)

But there is an assumption:
1. We know the task memory usage

I don't know if that complicates the problem.

**Comment by caishunfeng** [comment]
Now ds has a `LowerWeightRoundRobin` selector, it will filter the busy and abnormal worker, you can see the logic of `HeartbeatTask`.

**Comment by zhuxt2015** [comment]
@caishunfeng 
Yes, but `LowerWeightRoundRobin` only select lowest weight host,  not consider worker overload and low available memory.What if the lowest weight worker node is overload?

**Comment by zhuxt2015** [comment]
> I think we can treat it as a [knapsack problem](https://en.wikipedia.org/wiki/Knapsack_problem), and use the Hungarian algorithm to solve it.
> 
> 1. Worker available memory as backpack capacity
> 2. Task memory is used as item weight
> 3. Task priority as item value (Or other reference values as values)
> 
> But there is an assumption:
> 
> 1. We know the task memory usage
> 
> I don't know if that complicates the problem.

@jieguangzhou We can not exactly get task memory usage before execute task,  Can only be estimated.

**Comment by zhuxt2015** [comment]
> I think we can treat it as a [knapsack problem](https://en.wikipedia.org/wiki/Knapsack_problem), and use the Hungarian algorithm to solve it.
> 
> 1. Worker available memory as backpack capacity
> 2. Task memory is used as item weight
> 3. Task priority as item value (Or other reference values as values)
> 
> But there is an assumption:
> 
> 1. We know the task memory usage
> 
> I don't know if that complicates the problem.

I learned about the backpack algorithm, I think this issue does not fall into the category of backpack algorithms, but is bin packing problem.

**Comment by jieguangzhou** [comment]
> > I think we can treat it as a [knapsack problem](https://en.wikipedia.org/wiki/Knapsack_problem), and use the Hungarian algorithm to solve it.
> > 
> > 1. Worker available memory as backpack capacity
> > 2. Task memory is used as item weight
> > 3. Task priority as item value (Or other reference values as values)
> > 
> > But there is an assumption:
> > 
> > 1. We know the task memory usage
> > 
> > I don't know if that complicates the problem.
> 
> I learned about the backpack algorithm, I think this issue does not fall into the category of backpack algorithms, but is bin packing problem.

I'm sorry I got it wrong, it's more of a generalized assignment problem. 
But on second thought, our scenario might not be so complicated that it might be harder to maintain the project. I think your approach is fine
