### ISSUE TITLE
[Improvement][Task] Improve seatunnel task command log

### ISSUE THREAD

**Issue by tracehh** [apache/dolphinscheduler#11026]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

 Improve seatunnel task command log

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
It has been merged into the 3.1.0 branch.
