### ISSUE TITLE
[Bug] [UI] View variable display problems

### ISSUE THREAD

**Issue by ShawshankLin** [apache/dolphinscheduler#11037]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

View variable display incomplete

### What you expected to happen

Reduce the width of the display

### How to reproduce

Setting multiple variables

### Anything else

![image](https://user-images.githubusercontent.com/16248686/179665064-9abda63d-30a4-4446-a4ce-a639223475d0.png)

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
