### ISSUE TITLE
[Feature][Worker] Add cache mechanism in worker for resources

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#11046]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- Currently in DS, a worker executing tasks downloads related resources to local and cleans them up when tasks completed. We could improve the performance by caching frequently-used resources.

https://github.com/apache/dolphinscheduler/blob/ff34393333c076da74ef029cb4c60cf551f76b37/dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/TaskExecuteThread.java#L170-L182

https://github.com/apache/dolphinscheduler/blob/ff34393333c076da74ef029cb4c60cf551f76b37/dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/TaskExecuteThread.java#L241-L273

### Use case

* If some resources such as jars / tarballs are frequently used, they could be cached on workers and won't be downloaded every time when executing related tasks.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@ruanwenjun @zhongjiajie @caishunfeng @SbloodyS WDYT? May I ask what potential risks we may face if implementing such feature?

**Comment by SbloodyS** [comment]
> @ruanwenjun @zhongjiajie @caishunfeng @SbloodyS WDYT? May I ask what potential risks we may face if implementing such feature?

If the user modifies the content in different tasks, the cache will cause abnormal task execution.

**Comment by ruanwenjun** [comment]
> > @ruanwenjun @zhongjiajie @caishunfeng @SbloodyS WDYT? May I ask what potential risks we may face if implementing such feature?
> 
> If the user modifies the content in different tasks, the cache will cause abnormal task execution.

Yes, it's not a good idea to do this cache, we need to make the data consistent with the source.

**Comment by EricGao888** [comment]
> > > @ruanwenjun @zhongjiajie @caishunfeng @SbloodyS WDYT? May I ask what potential risks we may face if implementing such feature?
> > 
> > 
> > If the user modifies the content in different tasks, the cache will cause abnormal task execution.
> 
> Yes, it's not a good idea to do this cache, we need to make the data consistent with the source.

@SbloodyS @ruanwenjun What about we add a button / checkbox to each resource in resource center to let users choose to enable cache or not?

**Comment by zhongjiajie** [comment]
> @SbloodyS @ruanwenjun What about we add a button / checkbox to each resource in resource center to let users choose to enable cache or not?

In this case, we just throw the potential error to users, of cause we can show some hint when user try to change those resource with cache. But as I know @SbloodyS 's soc topic is to remove `t_da_resource` table and fetch resource list directly from storage system. After we remove the table, we can not add addition for resource file.
I personally do not think it is a good idea to cache some resource in dolphinscheduler, it will add some raise and is it not the main function of task scheduling system should consider

**Comment by EricGao888** [comment]
> > @SbloodyS @ruanwenjun What about we add a button / checkbox to each resource in resource center to let users choose to enable cache or not?
> 
> In this case, we just throw the potential error to users, of cause we can show some hint when user try to change those resource with cache. But as I know @SbloodyS 's soc topic is to remove `t_da_resource` table and fetch resource list directly from storage system. After we remove the table, we can not add addition for resource file. I personally do not think it is a good idea to cache some resource in dolphinscheduler, it will add some raise and is it not the main function of task scheduling system should consider

Ok, this makes sense to me.
