### ISSUE TITLE
[Bug] [flink sql client] ds flink sql client stream job has been aborted, yarn job is not stopped

### ISSUE THREAD

**Issue by ShawshankLin** [apache/dolphinscheduler#11043]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

ds flink sql client job  has been aborted, but yarn job is not stopped.
The yarn.application.status.address configuration also does not take effect

### What you expected to happen

yarn job stop

### How to reproduce

run ds flink sql client stream job

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ShawshankLin** [comment]
@Dannila

**Comment by hstdream** [comment]
Is the yarn cluster ha?

**Comment by Dannila** [comment]
I just ran a test on flink sql realtime. When I stop the Flink SQL task, the yanr job also stops and my SQL statement executes without problems.

![image](https://user-images.githubusercontent.com/94423827/181697634-a544a634-135a-48fc-91d4-7d92a8ee0327.png)

![image](https://user-images.githubusercontent.com/94423827/181697712-a6fd6d48-d29f-4589-9d76-b13bba1c5f07.png)

**Comment by wangkaiyu13** [comment]
flink和flink_Stream  在dolphinscheduler停止任务  yarn上依旧运行 无法真实停止任务

**Comment by misszhangss** [comment]
@Dannila [@Radeity 
您好，我尝试在dolphinscheduler 3.17上运行一个flink Streaming任务
![image](https://github.com/apache/dolphinscheduler/assets/84503545/8daee608-dc9c-49b2-a1c6-8efd00a16082)
任务跑起来了 我点击停止按钮没有任何反应
![image](https://github.com/apache/dolphinscheduler/assets/84503545/057b1d68-6e3d-4e1e-9ea1-2ce80309b21b)
运行一会后就自动停止了，即使我不点停止按钮，他也会在数据同步后自动停止
![1694683207628](https://github.com/apache/dolphinscheduler/assets/84503545/c84337fa-f9ff-456b-9f58-d7183c9b8226)
查询hadoop发现对应的application并没有停止
![image](https://github.com/apache/dolphinscheduler/assets/84503545/2bcc1a53-dbe2-403a-9ca1-555221733c2a)
上图中的kill都是我自己手动kill的  点击stop  并不会真正的停止application

主要存在两个问题：
1、为什么flink stream任务在同步完数据的时候会停止，且停止的时候对应的application并没有停止
2、为什么stop按钮并没有真正的停下任务

 期待您的回复，感谢!

这是我任务的一些参数
![image](https://github.com/apache/dolphinscheduler/assets/84503545/afea0247-be7b-43df-8aaa-12a049c89b62)

![image](https://github.com/apache/dolphinscheduler/assets/84503545/9f996380-2c9f-4234-888f-e6811fbd751c)
sql脚本：
CREATE TABLE ddd_code_detail_history ( id bigint NOT NULL , code_detail_id bigint , content string, funNames varchar(255) , properties string, version varchar(255) ,
 updater varchar(255) , comments varchar(255), PRIMARY KEY (id) NOT ENFORCED ) with ( 'connector' = 'mysql-cdc', 'hostname' = '172.16.198.248', 'port' = '3306',
 'username' = 'root', 'password' = 'DataBlau@1', 'database-name' = 'ddd_db_dev', 'table-name' = 'ddd_code_detail_history' );
 
CREATE TABLE ddd_code_detail_history_demo ( id bigint NOT NULL , code_detail_id bigint  , content string, funNames varchar(255) ,
 properties string, version varchar(255) , updater varchar(255) , comments varchar(255), PRIMARY KEY (id) NOT ENFORCED ) 
 with ( 'connector' = 'upsert-kafka', 'topic' = 'flink-cdc-kafka','properties.bootstrap.servers' = '172.16.198.248:9092','properties.group.id' = 'flink-cdc-kafka-group',
 'key.format' = 'json', 'value.format' = 'json'  );
 
insert into ddd_code_detail_history_demo select * from ddd_code_detail_history;

**Comment by misszhangss** [comment]
@ShawshankLin 您好  现在有好的解决方案吗，如果有好的方案，希望您可以分享一下，谢谢

**Comment by Japson0** [comment]
Because it is essentially Kill -9, it is the submitted process that has been killed, essentially too late to notify Flink
