### ISSUE TITLE
[Bug] [UI] Modifying the copied task node's parameters will affect the original task node 

### ISSUE THREAD

**Issue by simon824** [apache/dolphinscheduler#11055]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I define a sql task `testsql` with custom parameters, and copy this task node to generate another task `testsql_5iv`. At this time, I modify the custom parameters of `testsql_5iv`, and `testsql` will be modified too.

This problem only occurs before the workflow is saved.

1. 
![image](https://user-images.githubusercontent.com/18065113/179875131-78dfc4b5-2e32-46e7-a6d5-333167626459.png)

2. 
![image](https://user-images.githubusercontent.com/18065113/179875242-559c698a-7749-49a9-8c2a-1ae6226689ba.png)

3. 
![image](https://user-images.githubusercontent.com/18065113/179875348-4d00ae1c-6f71-4bd5-8284-6d809196d0ee.png)

### What you expected to happen

Modifying the copied task node's parameters won't affect the original task node 

### How to reproduce

I define a sql task `testsql` with custom parameters, and copy this task node to generate another task `testsql_5iv`. At this time, I modify the custom parameters of `testsql_5iv`, and `testsql` will be modified too.

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuxt2015** [comment]
This should be a mistake on the canvas of frontend, @songjianet @Amy0104  PTAL

**Comment by simon824** [comment]
Has been fixed by #10611
