### ISSUE TITLE
[Feature][Api Server] Enable DS to use resource center without s3fs file system

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#11068]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* We got some feedback from users to support a new feature - enable DS to use resource center without s3fs file system. In that case, workers could retrieve resources through api-server and there will be no need to setup s3fs system.
* However, there are risks if we implement this feature. Further discussions needed.

### Use case

* Already described above.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
<img width="735" alt="IMG_1330" src="https://user-images.githubusercontent.com/34905992/179915487-f7ebbf24-7b0e-433d-b1a9-119d549fb82c.PNG">



Here is a design contributed by @zhzhenqin

**Comment by ruanwenjun** [comment]
> <img alt="IMG_1330" width="735" src="https://user-images.githubusercontent.com/34905992/179915487-f7ebbf24-7b0e-433d-b1a9-119d549fb82c.PNG">
> 
> Here is a design contributed by @zhzhenqin

According to this picture, I think you just want to implement a facade, right? If so, we already have `StorageOperate` to do this. 
If this issue is want to discuss implementing a distributed file system in DS. I am -1 to this.

**Comment by EricGao888** [comment]
Currently it seems there is no proper reason for us to implement this feature, therefore, I'm closing it. Thanks.
