### ISSUE TITLE
[Bug] [DataQuality] When save "multi-table accuracy" rule, mapping_columns value not saved to db

### ISSUE THREAD

**Issue by zixi0825** [apache/dolphinscheduler#11070]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When choose "多表准确性" rule， on condition value was not saved to db，
![image](https://user-images.githubusercontent.com/10829956/179947717-6df6c45c-5ce3-4457-93f7-f42302e7c231.png)

when open it again，
![image](https://user-images.githubusercontent.com/10829956/179948329-c2e77bd5-2558-4465-93a2-65cacf55b9fd.png)

### What you expected to happen

choos "多表准确性" rule, add on condtion, save task ,reopen it, can show on condition

### How to reproduce

choos "多表准确性" rule, add on condtion, save task ,reopen it

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zixi0825** [comment]
@songjianet

**Comment by hezean** [comment]
Wish I could help, but I have trouble reproducing this in either 3.0.0-beta2 or master. Can you please verify again?
