### ISSUE TITLE
[Doc][Development] Add tips about how to use lombok

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#11074]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Add some tips in docs about how to use `lombok`:

1. Use `lombok` for `setters`, `getters` and `toString` methods in data objects to keep code neat.
2. Avoid using `@Data` annotation because it will generate some code we may not need, cause the test coverage to decrease and make the `Sonar Analysis` fail for it.
3. We'd better add a CI check to avoid `@Data`.

See: https://stackoverflow.com/questions/45569085/sonarqube-bad-coverage-because-of-lombok-data and https://projectlombok.org/features/Data 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
Anyone interested in this issue are welcome to comment here to take it. If no one picks it up in 2 weeks, I will take this. Thx : )

**Comment by EricGao888** [comment]
Here is an example: https://github.com/apache/dolphinscheduler/pull/11045

**Comment by rickchengx** [comment]
Hi, @EricGao888 , I'm interested in this issue.

**Comment by EricGao888** [comment]
We might need some discussions here. Currently there are two potential methods to avoid `sonar` failing for UT coverage decrease caused by `@Data`:

1. Use the method described in this issue.
2. Keep `@Data` and fix `sonar` instead to exclude code generated by `lombok`

See: https://github.com/apache/dolphinscheduler/pull/11133#issuecomment-1195168073

related: #11133

**Comment by EricGao888** [comment]
> We might need some discussions here. Currently there are two potential methods to avoid `sonar` failing for UT coverage decrease caused by `@Data`:
> 
> 1. Use the method described in this issue.
> 2. Keep `@Data` and fix `sonar` instead to exclude code generated by `lombok`
> 
> See: [#11133 (comment)](https://github.com/apache/dolphinscheduler/pull/11133#issuecomment-1195168073)
> 
> related: #11133

I don't have strong opinions here about which method to take, as long as we stick to one of them to keep consistency. If we agree on taking the second one, we need to fix `sonar` in this issue instead of adding docs and changing CI. WDYT @SbloodyS @kezhenxu94 @rickchengx

**Comment by SbloodyS** [comment]
I think the second option is more friendly for contributors. So it's better to me.

**Comment by kezhenxu94** [comment]
Excluding generated codes in coverage should be possible and that's what we should do, i prefer the 2nd way

**Comment by EricGao888** [comment]
Sure, seems we have reached a consensus here, then we will take the second one @rickchengx

**Comment by rickchengx** [comment]
Hi, @kezhenxu94 @SbloodyS @EricGao888 
So we need to exclude the `Lombok` generated code during the coverage tests and make the code coverage results of `Sonar` more meaningful.
One possible solution is to create a `lombok.config` file in the root of the project and add the config below:
```
lombok.addLombokGeneratedAnnotation = true
```
which makes Lombok to add @lombok.Generated annotation to all generated methods so that Jacoco will automatically ignore the lombok auto generated code.

Ref:
https://community.sonarsource.com/t/getting-meaningful-coverage-results-in-sonarqube-when-using-jacoco-and-lombok/13821
https://projectlombok.org/features/configuration

WDYT

**Comment by EricGao888** [comment]
> Hi, @kezhenxu94 @SbloodyS @EricGao888 So we need to exclude the `Lombok` generated code during the coverage tests and make the code coverage results of `Sonar` more meaningful. One possible solution is to create a `lombok.config` file in the root of the project and add the config below:
> 
> ```
> lombok.addLombokGeneratedAnnotation = true
> ```
> 
> which makes Lombok to add @lombok.Generated annotation to all generated methods so that Jacoco will automatically ignore the lombok auto generated code.
> 
> Ref: https://community.sonarsource.com/t/getting-meaningful-coverage-results-in-sonarqube-when-using-jacoco-and-lombok/13821 https://projectlombok.org/features/configuration
> 
> WDYT

This method sounds good to me.

**Comment by kezhenxu94** [comment]
> One possible solution is to create a `lombok.config` file in the root of the project and add the config below:
> 
> ```
> 
> lombok.addLombokGeneratedAnnotation = true
> 
> ```
> 

This is what I expected. Refer to this file and the related changes if needed https://github.com/apache/skywalking/blob/master/lombok.config

**Comment by rickchengx** [comment]
> Ref:
> https://community.sonarsource.com/t/getting-meaningful-coverage-results-in-sonarqube-when-using-jacoco-and-lombok/13821
> https://projectlombok.org/features/configuration

Thanks a lot.

**Comment by EricGao888** [comment]
closed by: #11212

**Comment by EricGao888** [comment]
Hi @rickchengx , next time you submit a pull request, you could add `This PR closes: #xxxxx` so that the related issue will close automatically when PR merged.
