### ISSUE TITLE
[Bug-FE] [Workflow Definition] Operation list display questions

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#11075]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The 27 inch display cannot display the complete operation

<img width="1912" alt="image" src="https://user-images.githubusercontent.com/76080484/180121258-6243a307-f49c-4d73-a4a8-3495a8d0dea2.png">

### What you expected to happen

Operation list display interval reduced

### How to reproduce

Program start

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.
