### ISSUE TITLE
[Bug-BE] [Alarm Group Manage ] Dirty data returned from the back end of the alarm group

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#11080]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Dirty data returned from the back end of the alarm group

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/76080484/180141773-c2b2329a-4cf4-4cea-8046-99327a469e1d.png">

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/76080484/180141532-cc403699-4672-4f9a-b593-c8aca7c05898.png">

### What you expected to happen

Delete dirty data

### How to reproduce

Deploy for the first time, initialize the database

default admin warning group Dirty data returned from the back end of the alarm group

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
I try to set the default alert_plugin_ids to null, but UI error for split, because it's a required field.
![image](https://user-images.githubusercontent.com/11962619/180359228-25c2e650-61d9-49b0-a9b8-4c9e7fd95133.png)

**Comment by zhongjiajie** [comment]
stale issue
