### ISSUE TITLE
[Bug] [Data Source] Can not create oracle data source.

### ISSUE THREAD

**Issue by xyzhh** [apache/dolphinscheduler#11087]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

"Failed to load driver class oracle.jdbc.OracleDriver in either of HikariConfig class loader or Thread context classloader" is prompted when I build a oracle data source  connection. I have already copyed ojdbc6.jar or ojdbc8.jar file to all libs directories，and restarted servers .The jdbc file worked well in version 1.x.
(By the way ,there is no oracle datasource description in lastest DOC?)
### What you expected to happen

create oracle data source properly

### How to reproduce

Just create oracle data source. 

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Currently, one task instance of hive data source uses one connection. The maximum number of concurrent connections is equal to the number of worker threads. It's recommended to improve the configuration of hiveserver2 or reduce the concurrency.

**Comment by SbloodyS** [comment]
Due to incompatible license of Oracle. We can only introduce Oracle in a similar way to MySQL. I'll add this to the document.

**Comment by xyzhh** [comment]
> We can only introduce Oracle in a similar way to MySQL. I'll add this to the

I can access mysql datasource by copying jdbc driver to libs directories,but can not access oracle datasource in same way.

**Comment by SbloodyS** [comment]
> > We can only introduce Oracle in a similar way to MySQL. I'll add this to the
> 
> I can access mysql datasource by copying jdbc driver to libs directories,but can not access oracle datasource in same way.

Yes. It has been fixed in #11095.

**Comment by xyzhh** [comment]
And I tried ojdbc6.jar and ojdbc8.jar

**Comment by xyzhh** [comment]
> 

Thank you for replying .But I dont care about the DOC. I just want  Oracle datasource is available.
