### ISSUE TITLE
[BUG] [UI] [DataQuality] fieldLengthcheck logic Operator  selection unsuccessful 

### ISSUE THREAD

**Issue by github-keep** [apache/dolphinscheduler#11085]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When using the data quality node to verify the field length, the logical operator selection fails. When entering the editing page again after confirming the submission, the logical operators are=
![image](https://user-images.githubusercontent.com/34233672/180158901-b2cd7f30-dc6f-49af-b280-c0c80ef8174e.png)
reenter
![image](https://user-images.githubusercontent.com/34233672/180158541-04488d7b-a13a-4e09-a93b-895f9b130424.png)

### What you expected to happen

Logical operators can be used correctly

### How to reproduce

Data quality node -- > field length verification -- > the logical operator is not selected as =, and then enter after saving. The logical operator is =, which is not the originally selected logical operator

### Anything else

every time

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Hi @github-keep do you still work on this issue, we currently want to release version 3.0.0, if you finish before 3th Aug, maybe we can release including the bug fix

**Comment by XiaoZhiSnow** [comment]
how does this issue? is it ok now?
