### ISSUE TITLE
[Bug-FE] [File Manage Module] Create file name input in file details for verification

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#11091]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Create file name input in file details for verification

<img width="1917" alt="image" src="https://user-images.githubusercontent.com/76080484/180163496-da3f1906-1240-4094-be03-4d316492bdc1.png">

<img width="1913" alt="image" src="https://user-images.githubusercontent.com/76080484/180163639-7ee63475-89b6-4f71-b902-fcc46d97c30b.png">

### What you expected to happen

Check the input of the file name field to avoid duplicate suffixes

### How to reproduce

Create file name input in file details for verification

But it does not affect the normal execution of workflow shell tasks

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
