### ISSUE TITLE
[Question] [Worker] Too many hiveserver2 connctions

### ISSUE THREAD

**Issue by simon824** [apache/dolphinscheduler#11093]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened
I configured hive datasource and executed hive sql task.
And then here are a large number of such logs in my worker logs, generated every few seconds, which eventually leads to too many connections to hiveserver2. And i have no idea what happen.

```
[INFO] 2022-07-21 09:58:15.435 +0800 org.apache.hive.jdbc.Utils:[285] - Supplied authorities: hive.url:20000
[INFO] 2022-07-21 09:58:15.435 +0800 org.apache.hive.jdbc.Utils:[372] - Resolved authority: hive.url:20000
[INFO] 2022-07-21 09:58:15.435 +0800 org.apache.hive.jdbc.HiveConnection:[189] - Will try to open client transport with JDBC Uri: jdbc:hive2://hive.url:20000/default
[INFO] 2022-07-21 09:58:19.262 +0800 org.apache.hive.jdbc.Utils:[285] - Supplied authorities: hive.url:20000
[INFO] 2022-07-21 09:58:19.262 +0800 org.apache.hive.jdbc.Utils:[372] - Resolved authority: hive.url:20000
[INFO] 2022-07-21 09:58:19.262 +0800 org.apache.hive.jdbc.HiveConnection:[189] - Will try to open client transport with JDBC Uri: jdbc:hive2://hive.url:20000/default

........
```

### What you expected to happen

.

### How to reproduce

.

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
The current maximum number of concurrent connections is equal to the number of worker threads. It's recommended to improve the configuration of hiveserver2 or reduce the concurrency.

**Comment by TangTangGrit** [comment]
Which database does hive metadata exist in
> 当前最大并发连接数等于工作线程数。建议改进 hiveserver2 的配置或降低并发。

**Comment by bajiaolong** [comment]
It seems that configuring this parameter 'support.hive.oneSession=ture' is effective. If the worker is a cluster, each worker will create a container for hive operations. Of course, if it has been created and it is easy to not expire, it can continue to run in the current container, no new containers will be created
`sed -i 's/support.hive.oneSession=false/support.hive.oneSession=true/g' $DS_HOME/worker-server/conf/common.properties`

**Comment by forest455** [comment]
I found same problem.  I found no workflow running, but why worker keep printing hive connecting logs. 
![Uploading IMG_20220928_194714_edit_273430840399422.jpg…]()

**Comment by conorzhao** [comment]
I also encountered a problem with the number of connections, and after changing the configuration according to the answer, it did not work.

**Comment by simon824** [comment]
refer to #11533
