### ISSUE TITLE
[Bug-FE] [File Manage Modul] There is no space check for folder creation

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#11092]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

There is no space check for folder creation, which leads to shell task running error. Reason: the file cannot be found

<img width="1917" alt="image" src="https://user-images.githubusercontent.com/76080484/180165440-1041acb0-7547-4498-94e9-d9ab02bc6f8e.png">

### What you expected to happen

New file name space check

### How to reproduce

When creating a new file, there is a space in the middle of the file name

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it

**Comment by litiliu** [comment]
I wonder if it's necessary to check available space for folder creation. But i think it's necessary to check the available space before file uploading.
