### ISSUE TITLE
[Bug-BE] [Master Server] Master server reports an error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#11101]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Error caused by a large number of complement execution

<img width="1736" alt="image" src="https://user-images.githubusercontent.com/76080484/180342547-ed4923d9-b478-4290-86cc-ca570ba6ce22.png">

### What you expected to happen

The master service is running normally

### How to reproduce

Error caused by a large number of complement execution

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
I will fix it.
