### ISSUE TITLE
[Bug-BE] [worker server] The worker server reported an error without corresponding degradation mechanism, resulting in service crash

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#11104]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The worker server reported an error without corresponding degradation mechanism, resulting in service crash

<img width="1739" alt="image" src="https://user-images.githubusercontent.com/76080484/180371845-38d0ca8a-58e5-47e2-b354-ae20650be02e.png">

### What you expected to happen

When the worker service occupies the system memory to the limit, there should be a service degradation strategy

### How to reproduce

Multiple complement operations result in a command number of waiting for running of 1300

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
Closed due to inactivity. Will reopen it if there are updates. Thx : )
