### ISSUE TITLE
[Bug] [Task Plugin] Parameter values disappear in UI when editing Zeppelin task

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#11102]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/34905992/180350164-816a3b1b-7813-4bab-85e0-cf6163b30162.png)

* If you define a zeppelin task then edit it again later, values disappear in UI.

### What you expected to happen

* The values of zeppelin task parameters such as `noteId`, `paragraphId` shouldn't disappear when editing if you have filled it previously.
* There is probably a bug in the front-end but I couldn't find it, hope someone familiar with the front-end could help.

### How to reproduce

* Create a zeppelin task, save it and edit it again.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it

**Comment by EricGao888** [comment]
> I will fix it

@devosend Thx for help!
