### ISSUE TITLE
[Bug] [UI] Changed the background color of the task priority drop-down box to overwrite the font

### ISSUE THREAD

**Issue by TangTangGrit** [apache/dolphinscheduler#11114]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/77315486/180468336-5a098309-6f26-48e7-a11a-f7bd05ca8147.png)
The value is obscured by the dangling background color of the dropdown box

### What you expected to happen

Clash of styles

### How to reproduce

.n-base-select-option--pending::before{
  background-color: rgba(0,0,0,0.1) !important;
}
.n-base-select-option--pending::before{
  background-color: rgba(0,0,0,0.1) !important;
}

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TangTangGrit** [comment]
PR address #11116

**Comment by zhongjiajie** [comment]
@TangTangGrit do you still want to take this issue, I find out Amy give some suggestion in your PR?
