### ISSUE TITLE
[Bug-BE] [SQL component] Non admin users do not have database permissions, but the workflow can run successfully when it is online

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#11111]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Non admin users do not have database permissions, but the workflow can run successfully when it is online

<img width="1901" alt="image" src="https://user-images.githubusercontent.com/76080484/180408611-62831c7b-7370-4cb5-bcdf-d2bedc01642c.png">

<img width="1880" alt="image" src="https://user-images.githubusercontent.com/76080484/180408651-ffd1d7ae-bdde-4294-9717-2048f00a34cf.png">

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/76080484/180408860-7b4033d5-c583-426b-8dcf-365b38dd3055.png">

### What you expected to happen

SQL components without Data permission should not be executed successfully

### How to reproduce

Non admin users do not have database permissions, but the workflow can run successfully when it is online

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
@XuXuClassMate If you don't select the database you can't save it, how did you do it? can you tell me？

**Comment by EricGao888** [comment]
Closed due to inactivity. Will reopen it if there are follow-ups.
