### ISSUE TITLE
[Bug] [Data Quality] Data Quality Oracle can't find driver class

### ISSUE THREAD

**Issue by Chris-playground** [apache/dolphinscheduler#11110]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

At the begining, we put `ojdbc6-11.2.0.1.0.jar` into the api-server and worker-server's libs, and the data quality workflow can't find the tables in oracle, errors as below
#### website error
![image](https://user-images.githubusercontent.com/48941586/180392613-f802f7d2-a484-4087-ba63-0b8f341e9a9e.png)
#### console error
![image](https://user-images.githubusercontent.com/48941586/180393082-11b7b936-1330-4e8b-95af-d2cc33399be1.png)

then we found that it is because the driver's version is too low, oracle drivers below ojdbc8 doesn't have the `getSchema()` method.
After we changed the dirver to `ojdbc8-19.7.0.0` this problem solved.

However, another problem arised when we actually run the data quality workflow, it couldn't find the oracle driver class, errors as below
#### couldn't find driver class
![image](https://user-images.githubusercontent.com/48941586/180394152-c1975771-65c9-42ab-a4da-ff7c9c58df84.png)

we are sure that worker servers have oracle driver.

Thanks for your kindly help!

### What you expected to happen

the workflow could run properly

### How to reproduce

as I describled

### Anything else

nil

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hstdream** [comment]
Here, you need to put 'ojdbc6-11.2.0.1.0.jar' under spark/jars.

**Comment by hstdream** [comment]
Here, you need to put 'ojdbc8-19.7.0.0' under spark/jars.

**Comment by Chris-playground** [comment]
> Here, you need to put 'ojdbc8-19.7.0.0' under spark/jars.

It works, thanks!
