### ISSUE TITLE
[Bug-FE] [Gantt chart] The Gantt chart does not show the execution status of all components

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#11112]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The Gantt chart does not show the execution status of all components

<img width="1901" alt="image" src="https://user-images.githubusercontent.com/76080484/180415039-b6329abb-50a5-472a-87f9-ab46ff9d3f95.png">

### What you expected to happen

Normal display of component execution status

### How to reproduce

Execute workflow definition and view Gantt chart

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TangTangGrit** [comment]
@XuXuClassMate

**Comment by TangTangGrit** [comment]
@XuXuClassMate Hello, please describe exactly what happened to you to create this problem.

**Comment by devosend** [comment]
I will fix it
