### ISSUE TITLE
[Bug] [LOG] A large number of useless logs cause the hard disk to overflow

### ISSUE THREAD

**Issue by ShawshankLin** [apache/dolphinscheduler#11125]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/16248686/180638363-0f2c9425-1344-4ceb-8dd0-cc09a2051327.png)

### What you expected to happen

Generating Reasonable Logs

### How to reproduce

Perform a normal workflow task

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
Did you try to change the log level of the master server? you can try to change to warn, I think

**Comment by ShawshankLin** [comment]
> Did you try to change the log level of the master server? you can try to change to warn, I think

The problem is triggered when the current Woker group no longer exists. The task has been reconfigured and resolved
