### ISSUE TITLE
[Bug] [k8s deploy] configmap-dolphinscheduler-common.yaml does not work

### ISSUE THREAD

**Issue by edwardhuanghz** [apache/dolphinscheduler#11123]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

kubectl exec -it dolphinscheduler-worker-0 -n jufund bash
root@dolphinscheduler-worker-0:/opt/dolphinscheduler/conf# ls -atl
_**common.properties configure files not update in the k8s container**_

### What you expected to happen

configure common.properties in the path /opt/dolphinscheduler/conf update correctly

### How to reproduce

k8s fixed bug

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Is it k8s image reuse the docker image we build? @caishunfeng

**Comment by caishunfeng** [comment]
I try at local and it seems the common config in values.yaml does not work.

**Comment by zhongjiajie** [comment]
> I try at local and it seems the common config in values.yaml does not work.

@caishunfeng  So should we close it or should we fix it?

**Comment by caishunfeng** [comment]
> > I try at local and it seems the common config in values.yaml does not work.
> 
> @caishunfeng So should we close it or should we fix it?

Yes, I think we should fix it in the next version.

**Comment by caishunfeng** [comment]
close by #11441
