### ISSUE TITLE
[Bug] [Mysql] Mysql CPU usage is very high

### ISSUE THREAD

**Issue by ShawshankLin** [apache/dolphinscheduler#11126]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![Uploading 微信图片_20220724162435.jpg…]()

### What you expected to happen

The mysql CPU usage should be normal

### How to reproduce

Perform a normal Datax task

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Could you describe the steps to reproduce this problem?

**Comment by davidzollo** [comment]
> Could you describe the steps to reproduce this problem?

yes, I can't see the picture, please describe the question more clearly

**Comment by ShawshankLin** [comment]
> Could you describe the steps to reproduce this problem?

The problem is triggered when the current Woker group no longer exists. The task has been reconfigured and resolved
