### ISSUE TITLE
[Bug] [dolphinscheduler-api] Upload file  failed  because the file over 50M  

### ISSUE THREAD

**Issue by taoshengyijiua** [apache/dolphinscheduler#11132]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

我在测试3.0.0-beta-2这个版本的时候，上传jar包，超过50M报错，但配置上传大小100M;

When I was testing version 3.0.0-beta-2, I uploaded the jar package and reported an error when it exceeded 50m, but the upload size was configured to be 100m

### What you expected to happen

It should upload normally and successfully

### How to reproduce

使用3.0.0-beta2版本，正常部署成功后，通过资源中心上传超过50M的文件

Using version 3.0.0-beta2, upload files over 50m through the resource center after normal deployment

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by taoshengyijiua** [comment]
> Thank you for your feedback, we have received your issue, Please wait patiently for a reply.
> 
> * In order for us to understand your request as soon as possible, please provide detailed information、version or pictures.
> * If you haven't received a reply for a long time, you can [join our slack](https://s.apache.org/dolphinscheduler-slack) and send your question to channel `#troubleshooting`

![ef2bd8673bb1800f0ead124995ca6b1](https://user-images.githubusercontent.com/45588521/180706624-a0bf6681-887d-4008-83d7-7091330691da.jpg)

![df8015c1a2ed0d91fccbf0d7a5d9834](https://user-images.githubusercontent.com/45588521/180706634-f71884b8-d01d-4415-801f-9af4711aa5c3.jpg)

version :3.0.0-beta2
Upload jar file failed  when it exceeded 50M.  See the above picture for the error log

**Comment by yangjf2019** [comment]
Hi @taoshengyijiua, Please  close this issue, since duplicated with [10340](https://github.com/apache/dolphinscheduler/issues/10340)

**Comment by zhongjiajie** [comment]
> Hi @taoshengyijiua, Please close this issue, since duplicated with [10340](https://github.com/apache/dolphinscheduler/issues/10340)

close due to this
