### ISSUE TITLE
[Feature]db-layer-suggestion: one-db-is-metadata,annother-is-execution-result-db

### ISSUE THREAD

**Issue by coding-now** [apache/dolphinscheduler#1114]
it is recommend that database include 2 parts: metadata-db,excution-db.
db层建议分库：
1、Metadata-db,as metadata ,basis database,mainly include user,project,datasource,process-definition,etc. Data volumn is small and is high stability.
基础库，作为元数据进行管理：包括用户，项目，数据源、附件，流程定义等。
        基础数据库，相对稳定数据量小。
2、execution db,as a execuitioin-result database, include task-instance,log,process-instance.
Data volumn increased frequently.Need more patient for volumn ,stability and history data clean logic. 
执行库：
     任务拆分表，调度执行的结果表，这部分数据会大量增加，后续数据库优化，调整的重点在这里,历史数据如何清理归档等。
3、source-code-layer, many JOIN SQL is not recommended.
码层面，尽量少用join.

**Comment by dailidong** [comment]
good idea！ thx！
