### ISSUE TITLE
[Improvement][worker server] add JAVA task type

### ISSUE THREAD

**Issue by liyangyang-12138** [apache/dolphinscheduler#11143]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Java tasks are often used in the process of using DS,but now DS can only configure Java tasks in shell mode, which is neither intuitive nor convenient, So I want to add a task configuration of Java type

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I think it duplicated with #10689.
