### ISSUE TITLE
[Feature][Task] Enrich the `dry run` mode

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#11149]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We support dry-run mode to mock the execution of the workflow.

When we select dry-run, the task will not be executed really, the task parameter even will not be initialized.

So the `dry-run` is meaning less, I hope we can enrich the dry-run mode, when we select dry-run, we just mock the execution step, but we will still initialize the task and check the parameter.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
That's good!

**Comment by caishunfeng** [comment]
Hi @ruanwenjun  do you mean put the dry run mode into task, and then workflow can dry run some tasks but not all tasks?

**Comment by ruanwenjun** [comment]
> Hi @ruanwenjun do you mean put the dry run mode into task, and then workflow can dry run some tasks but not all tasks?

Yes, but this may make the task complex, each task need to provide a dry-run method. Now I hope we can deserialize the task params and execute init method, just mock the handle method. This is a discussion, I don't have a solution.
