### ISSUE TITLE
[Question] The feature of dependence relationship for flows can be add

### ISSUE THREAD

**Issue by FY7** [apache/dolphinscheduler#11150]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When we are working on a large project, there are often hundreds or thousands of scripts, which are usually divided into multiple workflows for the convenience of management, and the dependencies between streams are also better handled and maintained. Both shcedulis and azkaban support dependencies between streams , Does dolphinscheduler have a similar function?

当我们做一个大型项目的时候，往往有几百上千个脚本，通常为了管理方便划分成多个工作流，流之间依赖关系也更好处理和维护，shcedulis和azkaban都支持流之间依赖，dolphinscheduler是否有类似的功能呢？

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You can take a look at the dependent task.
`https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/task/dependent.html`
