### ISSUE TITLE
[Bug] [Task] When a workflow is deleted or a task is deleted in a workflow, the task is not deleted.

### ISSUE THREAD

**Issue by stalary** [apache/dolphinscheduler#11158]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When a workflow is deleted or a task is deleted in a workflow, the task is not deleted. You can still see it in the task definition.

### What you expected to happen

Delete task success.

### How to reproduce

Create workflow for many task and delete it.

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Duplicated with #9029.
