### ISSUE TITLE
[Bug] [resource center] There is not reupload button in resource page.

### ISSUE THREAD

**Issue by CriysHot** [apache/dolphinscheduler#11151]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

There is not reupload button in resource page.

### What you expected to happen

I want to reupload my file.

### How to reproduce

As the title.

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Please update the issue title and give a detail description about `reupload` otherwise I will close this issue, and why this is a BUG?
