### ISSUE TITLE
ds on k8s Front-end page not accessible

### ISSUE THREAD

**Issue by ocean-zhc** [apache/dolphinscheduler#11160]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I searched in related issues and no related issues,

The microservice starts as shown in the figure below:
ds version：3.0.0-beat-2

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/46189785/181140465-74a8e8db-6fae-438b-b721-4e2e12e7e9aa.png">

Microservice health status：
api-server：
<img width="710" alt="image" src="https://user-images.githubusercontent.com/46189785/181140583-a5ba75d7-7947-40fa-86c8-b75038485b37.png">
alert-server：
<img width="611" alt="image" src="https://user-images.githubusercontent.com/46189785/181140618-950f1f24-5236-4e20-ad5d-d96c80754827.png">
master-server:
<img width="664" alt="image" src="https://user-images.githubusercontent.com/46189785/181140648-a9679dc2-d097-4003-bc7a-3b167cb7848a.png">
worker-server:
<img width="619" alt="image" src="https://user-images.githubusercontent.com/46189785/181140687-bbc4e0a4-9cf5-4569-b895-68ac6d5da862.png">
problems：
<img width="730" alt="image" src="https://user-images.githubusercontent.com/46189785/181140816-ccc629e1-13d7-486c-88de-0cd0a999c1d0.png">

Interface documentation can be accessed normally：
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/46189785/181140938-6e4064fa-802c-448f-86a9-057e16c96357.png">

Expected effect: normal access.

Looking forward to reply, thanks！

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please update the issue title. And this is not an improvement.

**Comment by caishunfeng** [comment]
@ocean-zhc you can try the url like http://localhost:12345/dolphinscheduler/ui/login

**Comment by ocean-zhc** [comment]
@caishunfeng I tried it, unfortunately it didn't work
<img width="795" alt="image" src="https://user-images.githubusercontent.com/46189785/181167887-adc31739-c663-4009-a882-f3e6f1e80d07.png">

**Comment by zhongjiajie** [comment]
@ocean-zhc  Please add server port `:12345` after `dev.com` and try again

**Comment by SbloodyS** [comment]
Could you try to access through `api-server's ip address:12345/dolphinscheduler/ui` to check whether it is the proxy's problem?

**Comment by ocean-zhc** [comment]
> @ocean-zhc Please add server port `:12345` after `dev.com` and try again

Thank you for your reply, I deployed it in knative mode, the default port number is 8080
<img width="2071" alt="image" src="https://user-images.githubusercontent.com/46189785/181433159-7d79e380-1789-46e3-82b2-ac5814989dec.png">

**Comment by ocean-zhc** [comment]
> Could you try to access through `api-server's ip address:12345/dolphinscheduler/ui` to check whether it is the proxy's problem?

Thank you for your reply,The ip inside the container cannot be accessed from outside.

**Comment by zhongjiajie** [comment]
@ocean-zhc  So I think it work for port 12345, and I will close this issue, if you have further question, we can left a new message and we will reopen it

**Comment by ocean-zhc** [comment]
@zhongjiajie

**Comment by ocean-zhc** [comment]
I solved it
