### ISSUE TITLE
[Doc][script] how to set zookeeper namespace

### ISSUE THREAD

**Issue by weipengffk** [apache/dolphinscheduler#11171]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I have  two ds  in same ecs,how to set zookeeper namespace

---- 中文 
环境：apache-dolphinscheduler-3.0.0-beta-2-bin.tar.gz 
描述：
    请问一下？海豚三如何设置zookeeper的namespace，我两套海豚共用zookeeper,可能冲突了。
    我们公司pro环境使用的是海豚dolphinsceduler-1.3.6. 
    我找运维新申请了一台服务器部署海豚三。
    测试 hello world shell脚本，发现很诡异的问题，十次有一次成功，其它时候执行无反应，
    我看了下安全中心，worker分组把海豚一的work节点加进来了。
    我采用伪集群部署apache-dolphinscheduler-3.0.0-beta-2-bin.tar.gz,产生问题后，
    我去官网对应版本没有找到zookeeper的设置入口？
    根据旧的配置信息，搜索源码zookeeper.dolphinscheduler.root，只找到配置说明，代码里面没有看到相关属性设置。
    搜索微信聊天记录，找注册中心配置文件，也没找到。
    是不是符合  REGISTRY_ZOOKEEPER_属性 就行 ？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
@weipengffk 
![image](https://user-images.githubusercontent.com/33984497/181207343-9fcdc5fe-1405-4b9e-98c5-08be6ba9551e.png)
不是这个么？

**Comment by weipengffk** [comment]
> 
是这个，但是根据  https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/guide/installation/pseudo-cluster.html 这个配置，没有看到对应的信息。
dolphinscheduler_env.sh  只配置了两个zookeeper属性 
export REGISTRY_TYPE=${REGISTRY_TYPE:-zookeeper}
export REGISTRY_ZOOKEEPER_CONNECT_STRING=${REGISTRY_ZOOKEEPER_CONNECT_STRING:-localhost:2181}

其它属性是不是参照你图片的模式配置？ 文档应该补充详细一点

**Comment by fuchanghai** [comment]
The document will only write the deployment of a single cluster. Yours is the deployment of multiple clusters. I think the modification of the namespace is in application.yml. You need to modify the zookeeper namesapce of dolophinscheduler-master, dolophinscheduler-worker, and dolophinscheduler-api respectively。These are just my personal thoughts

**Comment by fuchanghai** [comment]
@SbloodyS Do we need to put the zookeeper's namespace in the dolphinscheduler_env.sh file so that multiple clusters can be associated with a zookeeper's different namespace?

**Comment by SbloodyS** [comment]
> @SbloodyS Do we need to put the zookeeper's namespace in the dolphinscheduler_env.sh file so that multiple clusters can be associated with a zookeeper's different namespace?

I think so. Would you like to submit a pr to fix it?

**Comment by weipengffk** [comment]
i have test,it is work.
dolphinscheduler_env.sh  add
export export REGISTRY_ZOOKEEPER_NAMESPACE="dolphinscheduler_3_wp"

-- 中文
我在dolphinscheduler_env.sh 新增如下属性
export export REGISTRY_ZOOKEEPER_NAMESPACE="dolphinscheduler_3_wp"
重新安装后，启动运行正常。 查看 zookeeper的命名空间，存在。

**Comment by fuchanghai** [comment]
@weipengffk if it's ok ,please submit a pr to fix it.i'm not good at k8s and docker

**Comment by weipengffk** [comment]
> @weipengffk if it's ok ,please submit a pr to fix it.i'm not good at k8s and docker
me two,so ··
---- 中文
我也对 docker 和 k8s 不太熟悉，还是等其它人来处理。
等我觉得掌握的差不多了，再来贡献社区
