### ISSUE TITLE
[Bug] [script] dolphinscheduler-daemon.sh Status error

### ISSUE THREAD

**Issue by TangTangGrit** [apache/dolphinscheduler#11176]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/77315486/181219900-0acb1fb1-4c65-4588-8eb1-f2a0e7d28dd3.png)
Query health status is always running.The task process has been queried and is not actually running

### What you expected to happen

CLASS is not defined in the script, but it is used. I added

### How to reproduce

I added the name corresponding to CLASS

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Could you describe your problems more specifically? I'm not quite understand it.

**Comment by TangTangGrit** [comment]
> 你能更具体地描述你的问题吗？我不太明白。
./bin/status-all.sh   have been in the state of running all the time. However, I have not started, and I have tried to execute ./stop-all.sh ，or so
