### ISSUE TITLE
[Improvement][UI] Unified local parameters UI

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#11186]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Now ds has defferent local params UI for defferent task type.
Such as shell、sql、procedure, the local params UI has direct and type, because they support params pass:
![image](https://user-images.githubusercontent.com/11962619/181412174-4d0f25e9-7ba5-4045-9008-bc416f90ef68.png)

and some task like flink、k8s, just has key and value, but the hidden logic is direct `IN` and type `VARCHAR`:
![image](https://user-images.githubusercontent.com/11962619/181412558-3c24bcbd-4cce-498f-ba7e-9373a980f548.png)

So it is better to unify the local parameters in the UI, and the tasks that do not support the params pass keep the unselectable direct `IN` and type `VARCHAR`, so that users can understand that this is not a bug, but that they do not support direct output.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hezean** [comment]
Hi, may I work on it?

**Comment by caishunfeng** [comment]
> Hi, may I work on it?

@HeZean Of course. I assign to you.

**Comment by caishunfeng** [comment]
related issue: #11071
