### ISSUE TITLE
[Bug] [Server] Worker rejected bug

### ISSUE THREAD

**Issue by brave-lee** [apache/dolphinscheduler#11196]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Because the machine load of the worker node is high, the ACK is slower than the bug caused by rejection again

### What you expected to happen

It can be executed normally

### How to reproduce

the machine load of the worker node is high，submit many tasks at the same time

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@JinyLeeChina Hi, may I ask whether you are going to do this in 3.0.2? If not, I will put it into 3.0.3. Thanks : )

**Comment by brave-lee** [comment]
OK, let me check
