### ISSUE TITLE
[Improvement][swagger] Now the interface document returns only the generic template

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#11208]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

<img width="1440" alt="截屏2022-07-29 18 10 33" src="https://user-images.githubusercontent.com/33984497/181737439-1ce4ce2a-a1d1-4265-8d3c-f821b7caf84c.png">
If the developer is a front end, he wants to see the data structure in 'data'

If the response attribute of the annotation @ApiOperation is used, the interface document can see the data structure of data, but cannot see the general return template. Can you give some advice? Need a discussion tag?
@SbloodyS @EricGao888 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This is one of the reasons why we refactor the API in #10257. Currently, you can debug by opening F12 in the page to view the format of specific parameters.

**Comment by fuchanghai** [comment]
@SbloodyS Although after your modification, I can only see the unified return structure。
```json

{
	"code": 0,
	"data": {},
	"failed": true,
	"msg": "",
	"success": true
}
```
 i mean as a ui,even if some default values ​​of f12 are null, the front end cannot judge the type of the parameter, nor does it know the meaning of each attribute of the object in 'data'.so why i open this issue

**Comment by SbloodyS** [comment]
You can find the data structure through swagger ui after refactor to v2 api. For more detail you can take a look at #10301.

**Comment by fuchanghai** [comment]
@SbloodyS  you are so smart,thx
