### ISSUE TITLE
[Feature][Registry] Support consul as registry

### ISSUE THREAD

**Issue by MichaelDeSteven** [apache/dolphinscheduler#11202]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Consul as one of the most popular registry center. We can support it maybe.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
It's a big feature. PTAL @EricGao888 @caishunfeng @zhongjiajie @ruanwenjun

**Comment by caishunfeng** [comment]
> It's a big feature. PTAL @EricGao888 @caishunfeng @zhongjiajie @ruanwenjun

@MichaelDeSteven It's a good idea, looking forward to your pr.
