### ISSUE TITLE
[Question] [log module] Why is the host of the log module 192.168.18.1 and the port 1234, and where can I modify this configuration item.

### ISSUE THREAD

**Issue by kiwi-field** [apache/dolphinscheduler#11218]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I want to output the log of the workflow instance to my mysql database through the interface, so I use the f12 of the page to see where the log data comes from. Through the code, I see that NettyRemotingClient is used, but I don't know logClient Where do the host and port of .rollViewLog(host, port, skipLineNum, limit) come from and can they be modified?
![image](https://user-images.githubusercontent.com/30741355/182022124-e17cf527-20c0-42d7-bd22-7a5b390741da.png)
![image](https://user-images.githubusercontent.com/30741355/182022142-c92dd11e-3f68-44bd-bafe-5762ed75b2d3.png)

### Use case

I would like to know where the logs of the workflow instance are stored and how should I synchronize the logs to our mysql database

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
@kiwi-field 
maybe host from taskInstance, and taskINstance‘s host from masterConfig
<img width="767" alt="image" src="https://user-images.githubusercontent.com/33984497/182058789-495fbde1-d63f-4aad-9195-6daf0a1954cb.png">


<img width="677" alt="image" src="https://user-images.githubusercontent.com/33984497/182058753-ebf03806-1568-4765-8fdf-6447f94501e5.png">

**Comment by lyn916** [comment]
![1665116426060](https://user-images.githubusercontent.com/39552917/194467229-d12efc22-81ad-4fea-960c-2f19e5a901fd.jpg)
你修改了logback日志配置
不要让我写英文，初中英语水平，不会

**Comment by lyn916** [comment]
org.apache.dolphinscheduler.server.log.LoggerRequestProcessor#checkPathSecurity

private boolean checkPathSecurity(String path) {
        String dsHome = System.getProperty("DOLPHINSCHEDULER_WORKER_HOME");
        if (StringUtils.isBlank(dsHome)) {
            dsHome = System.getProperty("user.dir");
        }
        if (StringUtils.isBlank(path)) {
            logger.warn("path is null");
            return false;
        } else {
            return path.startsWith(dsHome) && !path.contains("../") && path.endsWith(".log");
        }
    }

不知道谁代码写死，path.startsWith(dsHome)  
所以你 logback-spring.xml 配置文件里 log.base value写成绝对路径，还不是home目录下，就会报java.lang.IllegalArgumentException: Illegal path

反手就删掉这个  path.startsWith(dsHome) ，不知道有没有后果 ，部署目录固态盘空间不够，每天spark那么多日志，还不让我改数据盘，必须把dolphins部署在数据盘？
