### ISSUE TITLE
[Improvement][all] Improvement checksyle

### ISSUE THREAD

**Issue by MichaelDeSteven** [apache/dolphinscheduler#11211]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

IMO, DS is not good enough in `checksytle` part. 

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/51652084/181905075-e1c5ba9e-4ae9-407d-a86f-f33aff59158c.png">

When I want to compile or execute mvn command, I need to append `- Dcheckstyle.skip`. This is unfriendly for someone who is green hand and want to involved in this project.
I can improve this problem to make `checkstyle` pass in local environment.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
The current checkstyle detection is incremental detection, and full detection is not required to avoid many PR code conflicts caused by large-scale modifications.

**Comment by MichaelDeSteven** [comment]
> The current checkstyle detection is incremental detection, and full detection is not required to avoid many PR code conflicts caused by large-scale modifications.

Or we can just simply appending a note that `To start server when you execute mvn command, you may need to append - Dcheckstyle.skip` in `developer guide docs`?

**Comment by fuchanghai** [comment]
@MichaelDeSteven  @SbloodyS  I suggest that when we modify a class, we do a code format check by the way。do we need to make a list like #10257 ?

**Comment by SbloodyS** [comment]
> > The current checkstyle detection is incremental detection, and full detection is not required to avoid many PR code conflicts caused by large-scale modifications.
> 
> Or we can just simply appending a note that `To start server when you execute mvn command, you may need to append - Dcheckstyle.skip` in `developer guide docs`?

That sounds good to me. cc @EricGao888 @zhongjiajie

**Comment by SbloodyS** [comment]
> @MichaelDeSteven @SbloodyS I suggest that when we modify a class, we do a code format check by the way。do we need to make a list like #10257 ?

Currently, our CI detection is incremental.

**Comment by EricGao888** [comment]
> > > The current checkstyle detection is incremental detection, and full detection is not required to avoid many PR code conflicts caused by large-scale modifications.
> > 
> > 
> > Or we can just simply appending a note that `To start server when you execute mvn command, you may need to append - Dcheckstyle.skip` in `developer guide docs`?
> 
> That sounds good to me. cc @EricGao888 @zhongjiajie

+1, before we fix all the style errors as planned in https://github.com/apache/dolphinscheduler/issues/10573 , I think instructing developers to use `-Dcheckstyle.skip` is a good idea. Thx.
