### ISSUE TITLE
[Improvement][master] WorkflowRunnableStatus

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#11219]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

<img width="954" alt="image" src="https://user-images.githubusercontent.com/33984497/182031159-a6bd8948-f1a5-4fa4-b4ee-b92c640609d7.png">

after buildFlowDag give status of INITIALIZE_DAG, after initTaskQueue give the status of INITIALIZE_QUEUE. I think the status should be something in progress, not what was done before

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
cc @caishunfeng @ruanwenjun

**Comment by ruanwenjun** [comment]
Is there any advantage to using the status `in progress` rather than `done before`? I don't think it goes against some principle.

**Comment by fuchanghai** [comment]
@ruanwenjun Maybe a personal opinion. Because the states I used before represent the current situation, such as the state of the Thread class。imagine such a situation, if the current code reports an error. I'm going to print the error reported at that stage. When the code runs to the initTaskQueue method, I will print INITIALIZE_DAG, this seems a bit strange. The above is just my personal opinion

**Comment by fuchanghai** [comment]
@ruanwenjun Maybe a personal opinion. Because the states I used before represent the current situation, such as the state of the Thread class。imagine such a situation, if the current code reports an error. I'm going to print the error reported at that stage. When the code runs to the initTaskQueue method, I will print INITIALIZE_DAG, this seems a bit strange. The above is just my personal opinion

**Comment by ruanwenjun** [comment]
> @ruanwenjun Maybe a personal opinion. Because the states I used before represent the current situation, such as the state of the Thread class。imagine such a situation, if the current code reports an error. I'm going to print the error reported at that stage. When the code runs to the initTaskQueue method, I will print INITIALIZE_DAG, this seems a bit strange. The above is just my personal opinion

Ok, this is an advantage, but I don't think this change is needed now, since this class may be refactored later.

**Comment by fuchanghai** [comment]
@ruanwenjun ok i'll close this
