### ISSUE TITLE
[Feature][Stream] Support stream task

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#11223]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This feature issue is about supporting stream task:

- stream task definition
![image](https://user-images.githubusercontent.com/11962619/182062108-118ddbe8-bcdb-4cc8-964d-e39c7dae4f32.png)

- stream task instance
![image](https://user-images.githubusercontent.com/11962619/182062611-7a42ea3e-2355-4d48-a7f2-4fdf4f311ea5.png)

- stream task in DAG
![image](https://user-images.githubusercontent.com/11962619/182064073-502e2e48-9a53-4bbb-b362-7380417baf1c.png)
Create real-time tasks (such as: flink-stream) through workflows. When real-time tasks appear in DAG, the connections before and after the tasks are displayed as dotted lines (this node will not actually run in the workflow, and the real-time tasks will run alone)

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SteNicholas** [comment]
@caishunfeng, IMO, the streaming task support needs to introduce event based scheduling mechanism in scheduler. Current scheduling mechanism depends on the status of the task, but streaming task is long running.
cc @davidzollo ,@EricGao888

**Comment by EricGao888** [comment]
> @caishunfeng, IMO, the streaming task support needs to introduce event based scheduling mechanism in scheduler. Current scheduling mechanism depends on the status of the task, but streaming task is long running. cc @davidzollo ,@EricGao888

@SteNicholas Sounds pretty cool to me. Since this is a big feature, would you like to bring it up in the bi-weekly community conference for further discussion and send a proposal to the community dev mail list? Thx~ cc @davidzollo @caishunfeng

**Comment by caishunfeng** [comment]
> @caishunfeng, IMO, the streaming task support needs to introduce event based scheduling mechanism in scheduler. Current scheduling mechanism depends on the status of the task, but streaming task is long running. cc @davidzollo ,@EricGao888

@SteNicholas  Thanks your reply, I'm agree with you, and I think it's a big feature too. In this feature,  stream task will do nothing when workflow running, so maybe they don't conflict, we can follow up to  introduce event based scheduling, WDYT?

**Comment by SteNicholas** [comment]
@EricGao888 @caishunfeng, I would like to make a proposal to the community dev mail list. Go ahead to discuss this scheduling feature on the weekly meeting.
