### ISSUE TITLE
[Improvement][dolphinscheduler-service] ProcessService

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#11228]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/33984497/182085051-3ac56d3c-9b8f-4ba2-ae9e-21124f32580b.png">
Some methods such as querying datasource or UdfFunc based on id should not be placed here. It is inconvenient to maintain later

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Good suggestion. What do you want to do?

**Comment by fuchanghai** [comment]
> Good suggestion. What do you want to do?

For example, for the connection related to dataSouce, I have changed it to use dataSourceService to query, and delete the corresponding interface in processService。do you have any other suggestions？
