### ISSUE TITLE
Welcome to leave your article link(欢迎留下关于DolphinScheduler的文章链接)

### ISSUE THREAD

**Issue by dailidong** [apache/dolphinscheduler#1123]
We will publish on official website([https://dolphinscheduler.apache.org](https://dolphinscheduler.apache.org)) if suitable. 

---
欢迎大家留下关于小海豚调度文章的链接，后续会整理整理放在官网上

**Comment by Yeleights** [comment]
标题：Dolphin Scheduler 1.1.0 部署文档(CDH5.16.2)
链接：https://www.yuque.com/docs/share/f27cbf41-44a8-453d-8117-26286a1c27d7#

**Comment by gary0416** [comment]
Dolphin Scheduler 1.1.0 on Ambari 2.6.3

[https://gary0416.github.io/2019/10/30/DolphinScheduler/](https://gary0416.github.io/2019/10/30/DolphinScheduler/)

**Comment by buildupchao** [comment]
标题：Why cannot timed-tasks be scheduled to execute after EasyScheduler upgrades v1.1.0？（为何EasyScheduler升级v1.1.0后定时任务不调度执行？）
链接：https://segmentfault.com/a/1190000020770605

**Comment by JinyLeeChina** [comment]
> 标题：Why cannot timed-tasks be scheduled to execute after EasyScheduler upgrades v1.1.0？（为何EasyScheduler升级v1.1.0后定时任务不调度执行？）
> 链接：https://segmentfault.com/a/1190000020770605

操作步骤：
第一步：
update t_escheduler_schedules set release_state=0;
第二步：
delete from QRTZ_CRON_TRIGGERS;
delete from QRTZ_JOB_DETAILS;
delete from QRTZ_TRIGGERS;
第三步：
升级后在界面操作上线

**Comment by francis-du** [comment]
[Apache Airflow & Apache Dolphin Scheduler对比分析](https://www.francisdu.com/articles/Apache%20Airflow%20&%20Apache%20Dolphin%20Scheduler%E5%AF%B9%E6%AF%94%E5%88%86%E6%9E%90.html#more)

**Comment by Yeleights** [comment]
Apache Dolphin Scheduler 1.2.0 部署文档(CDH5.16.2)
https://www.yuque.com/docs/share/70463e56-2e4d-4876-a2e4-784bdcf960ab?#

**Comment by Yeleights** [comment]
如何将Dolphin Scheduler1.1.0升级到1.2.0
https://www.yuque.com/docs/share/6d2b49ba-4e52-4b12-bd89-72a1e7ec47a5?#

**Comment by gabrywu** [comment]
[DolphinScheduler源码分析](https://www.cnblogs.com/gabry/p/12162272.html)

**Comment by gabrywu** [comment]
[DolphinScheduler源码分析之任务日志](https://www.cnblogs.com/gabry/p/12217966.html)

**Comment by lizu18xz** [comment]
https://www.imooc.com/article/300193 学习

**Comment by DHC2016** [comment]
https://blog.csdn.net/github_39577257/article/details/102783298

**Comment by samz406** [comment]
api 调用 https://blog.csdn.net/samz5906/article/details/106825655
调度使用常见问题  https://blog.csdn.net/samz5906/article/details/106434430
