### ISSUE TITLE
[Improvement][UI] custom template switch button in chunjun component module is no need any more

### ISSUE THREAD

**Issue by jkhhuse** [apache/dolphinscheduler#11233]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In this PR ：[dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-chunjun.ts](https://github.com/apache/dolphinscheduler/pull/10937/files/f99b85a518c7389183e0328808976bccc40827ff#diff-a511c17bea1f93d089ef6f97f75dfbf59ceae6429c1e635575789179e1e864a8). 
We discussed this custom template switch button's function, It is only used to identify that the template is the default behavior.
and we thought it could be removed.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wxing89** [comment]
Some problem occured after this PR, configuration `customConfig`  changed to '0' while it should be defalut value '1'. The value 0 which will lead to create chunjun node failed.

Following is taskDefinitionJson example, the customConfig is '0'

taskDefinitionJson: [{"code":6433449457952,"delayTime":"0","description":"","environmentCode":-1,"failRetryInterval":"1","failRetryTimes":"0","flag":"YES","name":"xxxx","taskParams":{"localParams":[],"resourceList":[],**"customConfig":0**,"json":"{}"},"taskPriority":"MEDIUM","taskType":"CHUNJUN","timeout":0,"timeoutFlag":"CLOSE","timeoutNotifyStrategy":"","workerGroup":"default","cpuQuota":-1,"memoryMax":-1}]
