### ISSUE TITLE
[Bug] [api&datasource-plugin] When creating a Presto data source, the catalog/database (schema) format is not supported. Tables with the same name under different databases will be displayed on the Create Data Quality Task page

### ISSUE THREAD

**Issue by hyjunhyj** [apache/dolphinscheduler#11237]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. When creating Presto data source, catalog/database (schema) format is not supported in the "Database Name" input box
2. When filling in the real database name in the "Database Name" input box, and then on the Create Data Quality Task page, there is no data in the source data table selection box
3. When filling in the real catalog in the "Database name" input box, and then on the Create Data Quality task page, the source data table selection box will display tables with the same name in different databases. After selecting the table with the same name, the columns of the table and the table with the same name will be displayed in the source table column selection box

### What you expected to happen

1. Support catalog/database (schema) when creating presto data source
2. Avoid situations 2 and 3 in "What happened"

### How to reproduce

1. Case 1
![create_presto](https://user-images.githubusercontent.com/110226627/182129608-196fff30-c497-4c1e-bd2f-fc4af4035e83.jpg)
2. Case 2
![create_presto3](https://user-images.githubusercontent.com/110226627/182129708-31116678-29df-4f1d-b3f1-7c21c9840c4b.jpg)
![dq1](https://user-images.githubusercontent.com/110226627/182129877-585ddb0a-94b1-4fc4-b158-a129ea400f74.jpg)
3. Case 3
![create_presto2](https://user-images.githubusercontent.com/110226627/182130083-c3db6d38-3a40-409f-8b7b-3fa9b6679df2.jpg)
![dq2](https://user-images.githubusercontent.com/110226627/182130117-e65405ae-49c6-4e7d-b7ba-4087ed0d9a53.jpg)

### Anything else

In my local, in order to solve this problem without affecting other data sources, I made some small changes：
1. Override the checkDatasourcePatter method of PrestoDataSourceProcessor to allow the catalog/database (schema) format to pass the check
2. Modify the getTableColumns method in dolphinScheduler-api. To avoid duplicate columns in tables with the same name, pass in the schema parameter when querying

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good job，please paste pictures in English environment next time, thx

**Comment by hyjunhyj** [comment]
> good job，please paste pictures in English environment next time, thx

ok, thanks for reminding
