### ISSUE TITLE
[Bug] [UI] The Grid format cannot work

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#11245]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I create a workflow with 6 tasks, and use the grid format. It doesn't work.
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/22415594/182284776-ccf91422-9203-4b72-9169-5a3078644efe.png">

I click the button, nothing happen in ui.
<img width="1681" alt="image" src="https://user-images.githubusercontent.com/22415594/182284855-c4b18e91-08d5-4442-96b5-16da3e28e626.png">

### What you expected to happen

The Grid format can work well.

### How to reproduce

1. Create a workflow with 6 tasks.
2. Click format, use Grid
3. Input Rows=2, Cols=3
4. Click confirm.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
It has been fixed. ref #11200

**Comment by ruanwenjun** [comment]
> It has been fixed. ref #11200

OK, I will check again.

**Comment by ruanwenjun** [comment]
After reinstall the node_modules it can work well.
