### ISSUE TITLE
[Feature][Authenticator] Support OAuth as an authenticator 

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#11242]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* `OAuth` is widely used for WEB authentication without explicit password. 
* We could support `OAuth` as an authenticator in Dolphin Scheduler.
* More about `OAuth`, see: https://en.wikipedia.org/wiki/OAuth

### Use case

* Already described above.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
WIP, 2 providers of OAuth 2.0:
1. Google
2. GitHub

**Comment by zhongjiajie** [comment]
close by #8706
