### ISSUE TITLE
[Feature][database] Test database metadata equal in CI

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#11243]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Find some way to compare database ddl/dml from lastst to upgrade and auto run in CI

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@zhongjiajie May I ask whether we are going to do this in 3.0.2? What about putting it to 3.0.3?
