### ISSUE TITLE
[Bug] [API] Cannot view task log

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#11246]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I execute a task, and want to view the task log. I find the log can not display well and the front-end is always sending request to back-end.
<img width="1714" alt="image" src="https://user-images.githubusercontent.com/22415594/182287907-ee206248-bfd8-48fc-801b-a760c4ff4c2d.png">

### What you expected to happen

xx

### How to reproduce

1. Create a workflow with one task
2. Execute the workflow
3. View taskinstance log.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
I had cherry-pick https://github.com/apache/dolphinscheduler/commit/1b0f8c04d3e419320e30254393a8592ed52065a4 to 3.0.0-prepare, PTAL @zhongjiajie

**Comment by devosend** [comment]
I will fix it
