### ISSUE TITLE
[Bug] [UI] TaskGroup cannot save unless write desc

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#11244]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I create a new TaskGroup, I cannot confirm, unless I write the `Task group desc `, but this parameter is just a choosable parameter?
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/22415594/182284232-3a706873-1958-492f-a8f2-c17848ec1939.png">

### What you expected to happen

Can save task group without desc.

### How to reproduce

1. Click Resources -> Task Group Option
2. Create task group

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
