### ISSUE TITLE
[Bug] [Task Plugin] Seatunnel task run error

### ISSUE THREAD

**Issue by shangeyao** [apache/dolphinscheduler#11252]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/42203474/182319067-cb003428-18cd-4893-bd11-b50dce37c693.png)
![image](https://user-images.githubusercontent.com/42203474/182319134-3994be43-7088-4a40-994f-c6f052fe3e24.png)

### What you expected to happen

The seatunnel task can run successfully.

### How to reproduce

Create a seatunnel process and run it.

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This has been fixed in #10422.
