### ISSUE TITLE
[Feature][Task Plugin] Support hive cli task type

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#11261]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Currently DS only supports running hive sql through jdbc. We could add hive cli task plugin to enable users to run hive sql in client mode for stability in prod environment.
* In some companies, pure `shell` tasks are banned for security reasons. It will be better to provide such a `hive Cli` task.

### Use case

* Already described above.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Is it better to support both hive cli and beeline cli?

**Comment by EricGao888** [comment]
> Is it better to support both hive cli and beeline cli?

@SbloodyS Of course, that's a good suggestion. Thx for the comment!

**Comment by EricGao888** [comment]
WIP. I will submit a PR later today.
