### ISSUE TITLE
2.0.5 Scheduling flink task cannot find path

### ISSUE THREAD

**Issue by Mile-Z** [apache/dolphinscheduler#11273]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Scheduling flink task cannot find path，The environment variables have been configured, and the execution can be successful once ten times. Submit it with the shell command.
![image](https://user-images.githubusercontent.com/91326053/182530225-46c82387-7dc6-4eff-ad7f-31575f4ae363.png)
![image](https://user-images.githubusercontent.com/91326053/182530231-c63c81c8-acae-4aa1-9506-eb856e9d25e5.png)

### What you expected to happen

Scheduling flink task cannot find path，The environment variables have been configured, and the execution can be successful once ten times. Submit it with the shell command.

### How to reproduce

Scheduling flink task cannot find path，The environment variables have been configured, and the execution can be successful once ten times. Submit it with the shell command.

### Anything else

Scheduling flink task cannot find path，The environment variables have been configured, and the execution can be successful once ten times. Submit it with the shell command.

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @Mile-Z , please check whether this directory exists and whether the corresponding user has permission.
