### ISSUE TITLE
[Improvement][API] Change the way exceptions are handled in the API

### ISSUE THREAD

**Issue by ly1ex** [apache/dolphinscheduler#11278]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Now we put the exception into the Result class and parse it.
This is not an elegant approach, so we would like to change the original
```java
this.putMsg(result, Status.XXX, XXX);
return result;
```
to
```java
throw new ServiceException(String.format("xxx %s doesn't valid", xxx));
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I think `putMsg` and `Exception` are two different behaviors. We use `putMsg` to return valid error messages through API, while exceptions will not be returned through API.

**Comment by ly1ex** [comment]
> I think `putMsg` and `Exception` are two different behaviors. We use `putMsg` to return valid error messages through API, while exceptions will not be returned through API.

@zhongjiajie Hi Jiajie, What's your opinion about this issue?

**Comment by zhongjiajie** [comment]
> I think `putMsg` and `Exception` are two different behaviors. We use `putMsg` to return valid error messages through API, while exceptions will not be returned through API.

I have discuss with @caishunfeng , we think `putMsg` it is redundant and we should throw exception directly in serviceImpl, So we add a new `ExceptionHandler` in https://github.com/apache/dolphinscheduler/blob/ae6aa53f963d2ea02ab435db1e5548da23e3f882/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/exceptions/ApiExceptionHandler.java#L39-L43 from api side, which will covert the `ServiceException` to `Result` object, and return in `controller`. And we already have some existing code in https://github.com/apache/dolphinscheduler/blob/ae6aa53f963d2ea02ab435db1e5548da23e3f882/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TenantServiceImpl.java#L94-L105

And @SbloodyS do you think it is a good idea about this change? @SbloodyS

**Comment by SbloodyS** [comment]
That make sense to me. And it's a big project to modify it. I suggest mark it as a `DSIP` and make a todo list just as we do in #10257. WDYT? @zhongjiajie

**Comment by CalvinKirs** [comment]
> > I think `putMsg` and `Exception` are two different behaviors. We use `putMsg` to return valid error messages through API, while exceptions will not be returned through API.
> 
> I have discuss with @caishunfeng , we think `putMsg` it is redundant and we should throw exception directly in serviceImpl, So we add a new `ExceptionHandler` in
> 
> https://github.com/apache/dolphinscheduler/blob/ae6aa53f963d2ea02ab435db1e5548da23e3f882/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/exceptions/ApiExceptionHandler.java#L39-L43
> 
> from api side, which will covert the `ServiceException` to `Result` object, and return in `controller`. And we already have some existing code in
> https://github.com/apache/dolphinscheduler/blob/ae6aa53f963d2ea02ab435db1e5548da23e3f882/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TenantServiceImpl.java#L94-L105
> 
> And @SbloodyS do you think it is a good idea about this change? @SbloodyS

+1， make sense to me, `Result` is usually only used as a standard data format for external system interaction.
