### ISSUE TITLE
[Bug] [Module Name] Bug title You cannot use empty passwords for ClickHouse data source additions

### ISSUE THREAD

**Issue by hrtyf** [apache/dolphinscheduler#11280]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

You cannot use empty passwords for ClickHouse data source additions,If no value is transmitted when you enter the password, the password is changed to 123456 by default.
Version 2.0.6

### What you expected to happen

It might be in the source code,Change the null value passed to 123456

### How to reproduce

When adding the ClickHouse data source,Do not enter the password, pass a blank value,Viewing API Logs,The null value is found to be 123456 by default.

### Anything else

Clickhouse does not have a password by default,This issue causes the user to have to set a password for Clickhouse,This will involve a lot of associated configuration changes,It brings a lot of inconvenience to users.
1.3.9 version Null values will not default to 123456,You can add Clickhouse without a password.

### Version

2.0.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Duplicated with #11279.
