### ISSUE TITLE
[Feature][database] Find better way to upgrade database instead of bare sql script

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#11286]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

currently we using bare sql script to init or upgrade our databases which we can see in https://github.com/apache/dolphinscheduler/tree/dev/dolphinscheduler-dao/src/main/resources/sql/upgrade

and it is face some issue

* have to write multiple database type and multiple place
  * multiple database type: to adopt different database: currently we support postgres, mysql, h2
  * multiple place: we have to change multiple sql script files when we need to upgrade it, and have consistency issues
* do not support downgrade: if user just want to test the latest versions, we should better have downgrade command
* can not rerun: for ddl we can use store process to fix it(complex), but dml like insert may have error(duplicate key), or insert some record without uk.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lushaorong** [comment]
Maybe Liquibase is a good way？

**Comment by zhongjiajie** [comment]
> Maybe Liquibase is a good way？

sound good, will take a look, or maybe we can use https://atlasgo.io/declarative/diff to detect the diff to make sure the change it is correct
