### ISSUE TITLE
[Improvement][Master] master select host，zookeeper get node info get node status ABNORMAL_NODE_STATUS， clear workerNodeInfo

### ISSUE THREAD

**Issue by caoes** [apache/dolphinscheduler#11296]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When the master assigns a worker，Obtain node heartbeat information through ZK to obtain node unhealthy status. select host return null，ds unable to run workflow ；

`Host host = hostManager.select(context);`
`public Host select(ExecutionContext context) {
        Set<HostWeight> workerHostWeights = getWorkerHostWeights(context.getWorkerGroup());
        if (CollectionUtils.isNotEmpty(workerHostWeights)) {
            return selector.select(workerHostWeights).getHost();
        }
        return new Host();
    }`
`serverMap.putIfAbsent(host, get(path + SINGLE_SLASH + server));`
`public String get(String key) {
        try {
            return new String(client.getData().forPath(key), StandardCharsets.UTF_8);
        } catch (Exception e) {
            throw new RegistryException("zookeeper get data error", e);
        }
    }`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @caoes , which version you are using?

**Comment by caoes** [comment]
> Hi @caoes , which version you are using?

2.0.5
