### ISSUE TITLE
flink sql    mode

### ISSUE THREAD

**Issue by dashuai2020** [apache/dolphinscheduler#11300]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Under the current workflow definition module, when the flick component is selected and the program type is SQL, the SQL script parameter is the cluster yarn per job mode to submit the task. When the processing is completed, the yarn resource is not closed and released. It depends on the source code using SQL client SH script. Is there a good way to close the yarn session task?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Duplicated with #11299.
