### ISSUE TITLE
It is recommended to add functions related to data lineage, metadata management and data quality.(建议加上数据血缘、元数据管理、数据质量方面的功能)[Feature]

### ISSUE THREAD

**Issue by liumingning** [apache/dolphinscheduler#1130]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xiaot502** [comment]
数据质量管理加起来就比较强大了。据我了解易观公司自己是有个数据处理平台的。把这个项目做成综合平台的概率可能不大。

**Comment by dailidong** [comment]
first I want to say what features to achieve are determined by community attention.
by the way, DolphinScheduler is already an Apache community project. At present, there are more than a dozen companies that have contributed to it. we hope that more contributors or companies are needed to participate in the project, which is fully community-based and led by multiple companies.

I think the feature of data quality may be integrated with Apache GriFFin，if you have idea, please leave message!

last， please update/add comment in English, thx

**Comment by yh2388** [comment]
I want to implement feature of data lineage, what recommend open source tool?

**Comment by dailidong** [comment]
> I want to implement feature of data lineage, what recommend open source tool?

do you have some ideas? or you can add my wechat:510570367

**Comment by liumingning** [comment]
The DAG graph of tasks solves the dependency between tasks, and the data lineage solves the dependency between data, perfect! During the execution of the task DAG graph, you can record the metadata of each table, and then record the relationship between the table and the table, so as to preliminarily implement the data lineage!

**Comment by liumingning** [comment]
> I want to implement feature of data lineage, what recommend open source tool?

赞
