### ISSUE TITLE
[Bug] [Master] Lots of wrong tasks「 failedDispatchTasks 」put 「taskPriorityQueue」，cause normal tasks cannot be distributed

### ISSUE THREAD

**Issue by Quan-HS** [apache/dolphinscheduler#11302]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

in this file 「TaskPriorityQueueConsumer」，there are lots of wrong tasks when task dispatch failed,if  let those task「 failedDispatchTasks 」put「taskPriorityQueue」，cause normal tasks cannot be distributed.

### What you expected to happen

1. It doesn't matter what the priority of the task is, 「the task is tens of thousands of times larger」, it will happen
2. This is not valid，use level , fail count or Set a larger retry interval，Because the failed task will do a lot of invalid computations in the case of a large number of tasks，normal tasks are still not being distributed, It still creates a backlog

![image](https://user-images.githubusercontent.com/4489535/182837436-5c4466a6-11d0-486d-a410-5a2b04ddc8fe.png)

### How to reproduce

maybe we need handle the failed task separately, new queue, new thread.Retry the forced stop multiple times and wait for user confirmation

<img width="652" alt="wecom-temp-104085-1117bcc9f628a54a1797d8e9e8080111" src="https://user-images.githubusercontent.com/4489535/182837499-f3b94fdb-602d-497d-8762-38dc51c6aa9d.png">

### Anything else

You are the best.

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
cc @caishunfeng @ruanwenjun
