### ISSUE TITLE
[Bug] [Module Name] Bug title 

### ISSUE THREAD

**Issue by DubsLiu** [apache/dolphinscheduler#11316]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

创建流程后，对流程进行修改保存时报错 net::ERR_CONNECTION_RESET

index.d4eb824.js?2c795c7549663bb4f947:2          PUT http://192.168.1.117:12345/dolphinscheduler/projects/6432843259712/process-definition/6432848548288 net::ERR_CONNECTION_RESET

### What you expected to happen

请问怎么解决这个问题

### How to reproduce

新建工作流->保存工作流->在工作流列表点击编辑->在编辑页面点击保存

或者

新建工作流->保存工作流->在工作流列表点击删除

这两种操作都会报一样的错

### Version

2.0.6

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
I will close this issue due to the wrong title.
BTW, please use English description, which can make more developers understand, thanks.
