### ISSUE TITLE
[Improvement][Flink] flink sql mode 

### ISSUE THREAD

**Issue by dashuai2020** [apache/dolphinscheduler#11310]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When creating a flinksql task, when the task is submitted to yarn, the task is regarded as successful, rather than waiting for the task execution on yarn to complete, which will affect the offline task scheduling

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please use a clear description in the title.

**Comment by dashuai2020** [comment]
When creating a Flink SQL task and executing a Flink SQL task, the current program running logic is that the dolphin scheduler submits the task to YARN and starts the next task, instead of waiting for the task to execute successfully in YARN, returning it to the dolphin scheduler, and then changing the task status to success

**Comment by dashuai2020** [comment]
I have resovled   SET table.dml-sync = true;
