### ISSUE TITLE
[Improvement][UI] Mouse sliding optimization

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#11328]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

<img width="601" alt="image" src="https://user-images.githubusercontent.com/33984497/183230708-c5e59048-5602-4296-b21a-5ae9ffc2b4d7.png">
When I hover over "SQL语句" the mouse scroll down doesn't work. Maybe the mouse scroll is only for the "SQL语句" module.
## except
I would like to modify it to, when the mouse scrolls to the bottom or top of the "SQL 语句" module, then slide over its upper module

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hezean** [comment]
I'm working on it.
