### ISSUE TITLE
[Bug] [UI] create workflow contains chunjun node failed

### ISSUE THREAD

**Issue by wxing89** [apache/dolphinscheduler#11321]
Some problem occured after this PR, configuration `customConfig`  changed to '0' while it should be defalut value '1'. The value 0 will lead to create chunjun node failed.

Following is taskDefinitionJson example, the customConfig is default as '0'

taskDefinitionJson: [{"code":6433449457952,"delayTime":"0","description":"","environmentCode":-1,"failRetryInterval":"1","failRetryTimes":"0","flag":"YES","name":"xxxx","taskParams":{"localParams":[],"resourceList":[],**"customConfig":0**,"json":"{}"},"taskPriority":"MEDIUM","taskType":"CHUNJUN","timeout":0,"timeoutFlag":"CLOSE","timeoutNotifyStrategy":"","workerGroup":"default","cpuQuota":-1,"memoryMax":-1}]

_Originally posted by @wxing89 in https://github.com/apache/dolphinscheduler/pull/11234#issuecomment-1206284719_

**Comment by gzusgw** [comment]
![image](https://user-images.githubusercontent.com/37568108/189070330-dea5559d-af58-4c0a-b428-7607f5f036f3.png)
customConfig=0走入在plugin.task.chunjun.ChunJunParameterscheckParameters()方法if的逻辑，返回为false

**Comment by zhongjiajie** [comment]
@tracehh do you have time to take a look at this issue?

**Comment by tracehh** [comment]
Currently only support customConfig=1，custome json format

**Comment by gzusgw** [comment]
> Currently only support customConfig=1，custome json format

But when creating a chunjun task on the Web, customConfig default value is '0'

**Comment by tracehh** [comment]
I review the code again

**Comment by jkhhuse** [comment]
For the current version, the customConfig value should be set as the default true value.
I can propose a PR to solve this problem.

**Comment by jkhhuse** [comment]
because of check can not paased, i will recommit again to make check passed.
