### ISSUE TITLE
[Bug] [UI] dbType error in datax task definition

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#11327]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

dsType is Mysql. dtType is clickhouse.  edit after saved ,can't show clickhouse instance name , i think because of take error dtType,because of  got two requests for MySQL type
@EricGao888 maybe hit a tag of good for first time contributor and posted in Contribution Seeds
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/33984497/183230495-3f5b79e8-aeb0-49dc-891e-30184e93686e.png">

### What you expected to happen

be right

### How to reproduce

none

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
This bug has been fixed by #11222
