### ISSUE TITLE
[Feature][Development] Add doc checks in CI

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#11347]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

#### Docs Checks in CI
* We need some checks for docs in CI, including spelling checks, punctuation checks and formatting checks.

#### Pre-commit Hook
* Currently we need developers to copy example `pre-commit hook` script into their `.git/hooks` directory. For convenience, we could do this for developers by triggering a script to copy the hook during first-time compilation of the project. 
* We could add doc checks in `pre-commit hook` to make sure updated docs are cool before developers pushing them and triggering the remote CI.

### Use case

* Already described above.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
IMHO, by performing some easy checks in `pre-commit hook`, we could reduce the stress of remote CI a bit.

**Comment by zhongjiajie** [comment]
Maybe you can see the pre-commit project https://pre-commit.com. But I have had some bad experiences with it, such as:
* Slow: Obviously, because we have to check locally
* Update: when `pre-commit-config` file change, development have to update the pre-commit hook, otherwise they will failed in the github action. Also developer have to update both github action and `pre-commit-config` when then change the check rule

**Comment by zhongjiajie** [comment]
you can see it here https://github.com/apache/airflow/blob/a562cc396212e4d21484088ac5f363ade9ac2b8d/.pre-commit-config.yaml#L300-L308 about how to run local script into pre-commit

**Comment by EricGao888** [comment]
> Maybe you can see the pre-commit project https://pre-commit.com. But I have had some bad experiences with it, such as:
> 
> * Slow: Obviously, because we have to check locally
> * Update: when `pre-commit-config` file change, development have to update the pre-commit hook, otherwise they will failed in the github action. Also developer have to update both github action and `pre-commit-config` when then change the check rule

Thanks for the information. I agree that we should not have too many checks in `pre-commit hook` to avoid it getting too slow. Currently our `pre-commit hook` takes about 1 minute in total to run `mvn spotless:apply` and I think it's fine.

**Comment by zhongjiajie** [comment]
And in module `dolphinscheudler-python` we also have https://github.com/apache/dolphinscheduler/blob/cfb5918e7492b209db118d528878663ff808ca8e/dolphinscheduler-python/pydolphinscheduler/.pre-commit-config.yaml#L25-L35 but in barely use it. One reason is that I have tox for better choices https://github.com/apache/dolphinscheduler/blob/cfb5918e7492b209db118d528878663ff808ca8e/dolphinscheduler-python/pydolphinscheduler/tox.ini#L24-L29.

But I do not find some tool in Java, so maybe we can use pre-commit for a shot
