### ISSUE TITLE
[Bug] [Official website] Get an error with code 404 when access contribute guide

### ISSUE THREAD

**Issue by liu-lewis** [apache/dolphinscheduler#11358]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Get an error when access site: https://dolphinscheduler.apache.org/en-us/community/development/contribute.html
Error message on page:
Not Found
The requested URL was not found on this server.

### What you expected to happen

Website upgrade caused this error

### How to reproduce

1. Open official website: https://dolphinscheduler.apache.org/
2. Go to moudle COMMUNITY
3. Click hyperlink [Contributing Guides](https://dolphinscheduler.apache.org/en-us/community/development/contribute.html)

### Version

2.0.6

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Duplicated with #11351.
