### ISSUE TITLE
[Doc][Development] Contributing Guides  page not accessible(Not Found error)

### ISSUE THREAD

**Issue by fangyinc** [apache/dolphinscheduler#11351]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

[Contributing Guides](https://dolphinscheduler.apache.org/en-us/community/development/contribute.html) is not found

![image](https://user-images.githubusercontent.com/22972572/183392667-a290683f-9ea2-4c00-aa04-44b778ec43f0.png)

And chinese documentation, [贡献者指南](https://dolphinscheduler.apache.org/zh-cn/community/development/contribute.html) is also not found

![image](https://user-images.githubusercontent.com/22972572/183393227-ff8c1638-debe-461e-a887-a69c271b6c31.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Hi @staneyffer thanks for the feedback, we were migrated all development doc to https://dolphinscheduler.apache.org/en-us/docs/dev/user_doc/contribute/join/security.html, you can see the latest docs in that link, related PR is #11313 .

And BTW, after we release the version 3.0.0, we will and those docs to `Docs` tabs

**Comment by fangyinc** [comment]
@zhongjiajie ,  Thank you for your reply, i got it~
