### ISSUE TITLE
[Fix][UI] Workflow instance should not support right-click running

### ISSUE THREAD

**Issue by sketchmind** [apache/dolphinscheduler#11366]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description
Workflow instance cannot support right-click running because it will change the parameters of the initial operation of the workflow.

_Originally posted by @lenboo in https://github.com/apache/dolphinscheduler/issues/9978#issuecomment-1208941206_

### Use case
menu should like this, the start button should be greyed out and not clickable
![image](https://user-images.githubusercontent.com/39169452/183585795-5c9e0f55-d42e-4307-893e-cb9ca813229c.png)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
The start action is not supported in workflow instance detail page but it is better to remove it not disable it.

**Comment by sketchmind** [comment]
> The start action is not supported in workflow instance detail page but it is better to remove it not disable it.


Well, I think what you said makes sense, I have made relevant changes
