### ISSUE TITLE
[Bug] [S3] minio Related bugs

### ISSUE THREAD

**Issue by ocean-zhc** [apache/dolphinscheduler#11370]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

minio：
It can be uploaded and created, but the simplest task of the shell cannot read the prompt the file isn`t exists.
<img width="2462" alt="image" src="https://user-images.githubusercontent.com/46189785/183606334-6b83de83-a028-4b21-bcb6-3396a2521cb1.png">
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/46189785/183606375-d4f527d3-5d30-46a1-92ef-7fc5668e92c4.png">
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/46189785/183606493-3f052b39-0720-4c1b-a312-87f2901786cb.png">

### What you expected to happen

shell task can get files in resource center.

### How to reproduce

Specific reproduction reference：[https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/guide/resource/file-manage.html](url)

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sketchmind** [comment]
Looks like isn't 3.0.0 release version, may be fixed by #10675

**Comment by ocean-zhc** [comment]
> Looks like isn't 3.0.0 release version, may be fixed by #10675

tks！I have resolved.

**Comment by caishunfeng** [comment]
> > Looks like isn't 3.0.0 release version, may be fixed by #10675
> 
> tks！I have resolved.

Thanks, I will close this issue.
