### ISSUE TITLE
[Bug] [kubernetes] helm dependency update: read: operation timed out

### ISSUE THREAD

**Issue by WholeWorld-Timothy** [apache/dolphinscheduler#11381]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

run helm dependency update .
get:...Unable to get an update from the "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami" chart repository:
        Get "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami/index.yaml": read tcp 192.168.12.93:58483->185.199.108.133:443: read: operation timed out
...Unable to get an update from the "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami" chart repository:
        stream error: stream ID 1; PROTOCOL_ERROR

### What you expected to happen

get:Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading postgresql from repo https://charts.bitnami.com/bitnami
Downloading zookeeper from repo https://charts.bitnami.com/bitnami
Deleting outdated charts

### How to reproduce

$ tar -zxvf apache-dolphinscheduler-3.0.0-src.tar.gz
$ cd apache-dolphinscheduler-3.0.0-src/deploy/kubernetes/dolphinscheduler
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm dependency update .

### Anything else

Can I modify deploy/kubernetes/dolphinscheduler/Chart.yaml like:
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.x.x
- condition: zookeeper.enabled
  name: zookeeper
  repository: https://charts.bitnami.com/bitnami
  version: 9.x.x

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @WholeWorld-Timothy It seems the problem of your network setting.

**Comment by EricGao888** [comment]
Seems not related to ds.
