### ISSUE TITLE
[Improvement][Doc] Fix typos, tense, formatting, letter case, etc. errors in docs

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#11385]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently our English doc quality is not so good: 

- We have tons of tense, formatting, punctuation, etc. errors and inconsistency of letter case usage in docs.
- Some sentences are ambiguous, misleading or hard to understand.
- We need to avoid passive voice in doc writing.
- Markdown docs are badly formatted.

Since @zhongjiajie has already migrated all docs from website repo to main repo, and we have `spotless` to help with the markdown formatting #11384, it's high time that we refactored the docs.

Besides, we need a guideline for DS English docs writing, see: #11161 

related: #6535

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
> We have tons of tense, formatting, punctuation, etc. errors and inconsistency of letter case usage in docs.

I think we better find some way to auto-fix those issues, 

> Markdown docs are badly formatted

I am not sure how spotless auto-fix this, but I am sure there are some of the docs can not be auto fix, like we have HTML style IMG format, beside the auto-fix tool, maybe we also need a checker for our markdown doc and other CI which I already mention in #6535

**Comment by EricGao888** [comment]
> > We have tons of tense, formatting, punctuation, etc. errors and inconsistency of letter case usage in docs.
> 
> I think we better find some way to auto-fix those issues,
> 
> > Markdown docs are badly formatted
> 
> I am not sure how spotless auto-fix this, but I am sure there are some of the docs can not be auto fix, like we have HTML style IMG format, beside the auto-fix tool, maybe we also need a checker for our markdown doc and other CI which I already mention in #6535

@zhongjiajie Thanks for the information, I will take a look at the `doc checker` you mentioned above : )

**Comment by EricGao888** [comment]
> > We have tons of tense, formatting, punctuation, etc. errors and inconsistency of letter case usage in docs.
> 
> I think we better find some way to auto-fix those issues,
> 
> > Markdown docs are badly formatted
> 
> I am not sure how spotless auto-fix this, but I am sure there are some of the docs can not be auto fix, like we have HTML style IMG format, beside the auto-fix tool, maybe we also need a checker for our markdown doc and other CI which I already mention in #6535

BTW, `spotless` fixes `markdown` using `Flexmark`.

![image](https://user-images.githubusercontent.com/34905992/183812883-1e896a11-895b-4445-b3fa-5c4f9fc94f17.png)

**Comment by zhongjiajie** [comment]
I like this feature, like the auto-fix behavior, but I think we should find out all bad case formats too. I think the second is even more important

**Comment by EricGao888** [comment]
> I like this feature, like the auto-fix behavior, but I think we should find out all bad case formats too. I think the second is even more important

Agree, it would be better if those embedded stuff in markdown such as `html` code fragments could be fixed or at least get checked.

**Comment by EricGao888** [comment]
> I like this feature, like the auto-fix behavior, but I think we should find out all bad case formats too. I think the second is even more important

@zhongjiajie Just for clarification, for `tense, formatting, punctuation, etc. errors and inconsistency of letter case usage`, I will fix them manually, there is no way for fixing those stuff automatically. Only use `spotless` for markdown formatting.

**Comment by zhongjiajie** [comment]
> > I like this feature, like the auto-fix behavior, but I think we should find out all bad case formats too. I think the second is even more important
> 
> @zhongjiajie Just for clarification, for `tense, formatting, punctuation, etc. errors and inconsistency of letter case usage`, I will fix them manually, there is no way for fixing those stuff automatically. Only use `spotless` for markdown formatting.

Yeah, Of cause , but other things like a blank line, HTML syntax img, max cols in each line should be auto-fix if it can
