### ISSUE TITLE
[Improvement][Master] Events to improve

### ISSUE THREAD

**Issue by luoxiqiang** [apache/dolphinscheduler#11388]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

**I think we should check to see if there are identical events that are unique in the queue before adding events. In some cases, repeating a completed event may raise an exception**
**WorkflowExecuteRunnable.java**
![image](https://user-images.githubusercontent.com/32994527/183825929-33b1cbe3-0cb9-4d8c-bab7-511a565ffdb3.png)
**In addition, I think we should use poll() instead of peek() for fetch events, and add exception events to the end of the queue if they need to be processed repeatedly, otherwise they will always block processing of other events in the queue**
**WorkflowExecuteRunnable.java**
![image](https://user-images.githubusercontent.com/32994527/183827871-6af8d879-c6e5-44ab-a896-cb0b2cf0d0b2.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Can you provide the steps to reproduce this issue? @luoxiqiang

**Comment by ruanwenjun** [comment]
Could you please provide the exception and event detail?

**Comment by luoxiqiang** [comment]
The StateWheelExecuteThread::checkTask4State method pushes events through the event queue and continues to push events when the same event has not been processed.   For example, TaskStateEvent, The following exception is thrown if the task has completed but multiple identical TaskStateEvent events have not yet been handled
![image](https://user-images.githubusercontent.com/32994527/186830269-86a808b8-c17d-445f-be08-d67218718afe.png)
Earlier, here is the exception thrown StateEventHandleException, thus blocking the queue event handling, but now modified into StateEventHandleError discarded directly after the incident, although exceptions will be thrown also, but not influence the results, the optimization Suggestions can be ignored
