### ISSUE TITLE
[Improvement][UI] Concise the logic available for task action buttons on workflow definition detail page.

### ISSUE THREAD

**Issue by Amy0104** [apache/dolphinscheduler#11386]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

It's better to remove the unavailable task action buttons.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
@sketchmind Would you like to improve this?

**Comment by sketchmind** [comment]
> @sketchmind Would you like to improve this?

I’d like to do

**Comment by sketchmind** [comment]
> @sketchmind Would you like to improve this?

@Amy0104 But I think this needs to be discussed,for example, the start button of the workflow definition details page, gray can give the user a hint that the action is there, and it can only be used after going online.Also, if there is only one button, it will be a little harder to find the button position

**Comment by Amy0104** [comment]
> > @sketchmind Would you like to improve this?
> 
> @Amy0104 But I think this needs to be discussed,for example, the start button of the workflow definition details page, gray can give the user a hint that the action is there, and it can only be used after going online.Also, if there is only one button, it will be a little harder to find the button position

This is a context menu different from the list page, and similar to the system. A context menu offers a limited set of choices that are available in the current state. You can check out the explanation from wiki.

**Comment by sketchmind** [comment]
> > > @sketchmind Would you like to improve this?
> > 
> > 
> > @Amy0104 But I think this needs to be discussed,for example, the start button of the workflow definition details page, gray can give the user a hint that the action is there, and it can only be used after going online.Also, if there is only one button, it will be a little harder to find the button position
> 
> This is a context menu different from the list page, and similar to the system. A context menu offers a limited set of choices that are available in the current state. You can check out the explanation from wiki.

Haha ok, let me have a look
