### ISSUE TITLE
[Bug] [master] When I Complement Data by Parallel execution, some schedule date task do not excute. 

### ISSUE THREAD

**Issue by wanghaizhou** [apache/dolphinscheduler#11397]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/8066695/183866484-04684d74-b34c-494f-91b4-881fe95a0004.png)
![企业微信截图_16601218705397(1)](https://user-images.githubusercontent.com/8066695/183866606-6580ec2f-67f7-4974-ada3-32e45744f22f.png)
The tasks that schedule date is 2022-08-01 and 2022-08-04 were not created.

### What you expected to happen

All the schedule date task should be created.

### How to reproduce

![image](https://user-images.githubusercontent.com/8066695/183866484-04684d74-b34c-494f-91b4-881fe95a0004.png)

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wanghaizhou** [comment]
The task is a simple shell 
![image](https://user-images.githubusercontent.com/8066695/183871349-f7549edc-3a0d-4bef-82dc-522bb470634d.png)

**Comment by SbloodyS** [comment]
This issue only occurs in 3.0.0-release. And there is no problem in dev.

**Comment by Tianqi-Dotes** [comment]
![3efb87e7352a06b0c1c895c05ef804e](https://user-images.githubusercontent.com/36755957/190639855-b9f17e27-922c-481e-a5d9-56a949800691.jpg)
![bf42ae9284403480b214019d68b65a7](https://user-images.githubusercontent.com/36755957/190639870-6c19b79e-4499-470e-9545-28f9aead0859.jpg)
![image](https://user-images.githubusercontent.com/36755957/190639937-4a18b07e-0e0d-4e55-bd50-e46abe614986.png)
i tested many times and cannot reproduce，version  3.0.0-release

**Comment by EricGao888** [comment]
Closed due to comments above.
