### ISSUE TITLE
[Bug] [master] when task is configed by task group,the workflow Instance may be stuck frequently.

### ISSUE THREAD

**Issue by wanghaizhou** [apache/dolphinscheduler#11399]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The task node's status is Success, but workflow Instance's status is still RUNNING,and the workflow Instance is stuck.
When task is configed by task group, the error may occur frequently.
![image](https://user-images.githubusercontent.com/8066695/183877648-50ec8c32-b015-4358-91a1-1796ef64a710.png)
![image](https://user-images.githubusercontent.com/8066695/183877963-dafe1c3c-938e-44d4-9646-4cc1bd337ba9.png)

like this
#10446 

### What you expected to happen

The workflow Instance finished when the task node is all Success.

### How to reproduce

task is configed by task group

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
@wanghaizhou How to reproduce?

**Comment by EricGao888** [comment]
Closed due to inactivity.

**Comment by EricGao888** [comment]
Will reopen it if there are follow-ups / updates.
