### ISSUE TITLE
[Bug-FE] [workflow instance] The alarm group in the workflow instance is empty

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#11428]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The alarm group in the workflow instance is empty

<img width="995" alt="image" src="https://user-images.githubusercontent.com/76080484/184112833-525437a1-b8ae-4f5b-836b-bc288a5b26f6.png">

### What you expected to happen

Normal display

### How to reproduce

Select alarm group when running workflow

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
