### ISSUE TITLE
[Bug] Pre-tasks cannot be obtained from the task definition page of ds3.0

### ISSUE THREAD

**Issue by yangliang1111** [apache/dolphinscheduler#11425]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

任务定义页面中创建任务选择工作流之后最下面的前置任务不展示任何数据，在工作流定义中一切正常， 如下图：
![image](https://user-images.githubusercontent.com/20570824/184100592-933611e6-8b37-4a33-8cdc-6911e8a2082e.png)

![image](https://user-images.githubusercontent.com/20570824/184100153-f9364128-45c5-4a01-8e9e-1778ed47ea0f.png)

### What you expected to happen

任务定义页面中创建任务选择工作流之后最下面的前置任务不展示任何数据，在工作流定义中一切正常

### How to reproduce

任务定义页面中创建任务选择工作流之后最下面的前置任务不展示任何数据，在工作流定义中一切正常

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
