### ISSUE TITLE
[Question] Is it possible to use a stand-alone installation that does not participate in the cluster as a WORKER node? 

### ISSUE THREAD

**Issue by Arturo-Penas-Rial** [apache/dolphinscheduler#11436]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Is it possible to use a stand-alone installation that does not participate in the cluster as a WORKER node? 

### Use case

That is to say, independent computers that can execute the tasks from DolphinScheduler. If so, is it possible that the operating system of these independent nodes is WINDOWS?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
1. Standalone is a separate cluster and cannot be used as a worker node.
2. Running in windows is not supported currently.
