### ISSUE TITLE
[Bug] [Python]  change python doc link in readme.md

### ISSUE THREAD

**Issue by 106umao** [apache/dolphinscheduler#11430]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

ci failed

### What you expected to happen

ci pass

### How to reproduce

run github action

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
I will close this issue because it had fixed.
