### ISSUE TITLE
[Doc][Official website errors] Official website documentation bug report&fix or improvement 

### ISSUE THREAD

**Issue by debrachena** [apache/dolphinscheduler#11448]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We are participating the WeOpen-Star project, and this is one of task waiting for help, everyone can gain 10 scores for per error report&fix or improvement.

1. Text/grammar errors: 10 points for 10 errors found and corrected;

​2. Document errors: 10 points for each discovery and correction;

3. Document optimization: The document is reasonably optimized, with 10 points for per optimization.

If you find any documentation or page editing errors, please report&fix it.

**Submit:** Pull Request in the repo this issue belongs to for review, with issue ID copied in the PR description.

Related link: WeOpen-Star project: https://github.com/weopenprojects/WeOpen-Star/issues/30

**Note: ** 
1. Please remark your PR with【WeOpen-Star】
2. Leave a comment [WeOpen Star]I would like to help, meaning the task is claimed successful. 

### Documentation Links

https://github.com/weopenprojects/WeOpen-Star/issues/30

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by guanboo** [comment]
i would like to help
