### ISSUE TITLE
[Feature][Flink Stream] Use flink SDK replace the shell cli

### ISSUE THREAD

**Issue by shangeyao** [apache/dolphinscheduler#11440]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I want to participate in it.
relate to #11352 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Could you please provide a detailed design?

**Comment by shangeyao** [comment]
1.Use flink-client to submit tasks instead of the current shell cli
2.Distinguish submission methods and parameters in three environments（Standalone Yarn K8S）
3.Use the job ID to cancel and save point

For details, please refer to the following doc:
https://nightlies.apache.org/flink/flink-docs-release-1.15/api/java/org/apache/flink/client/program/ClusterClient.html

**Comment by shangeyao** [comment]
Expected flink SDK version：1.15.1
