### ISSUE TITLE
[Bug] [3.0.0] process-definition has to be started a second time every time

### ISSUE THREAD

**Issue by bdxmq** [apache/dolphinscheduler#11450]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The process is invalid the first time it is started, and it has to be started a second time every time.
The first startup shows success, but the instance is not running, the second startup is fine.

### What you expected to happen

Hope it gets resolved

### How to reproduce

1

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Could you describe it more specifically? @bdxmq

**Comment by bdxmq** [comment]
--process-definition--
The first time I click run, it shows success, but there are no workflows and tasks running in the view instance. The second time I click run, the workflow and tasks can run normally

**Comment by SbloodyS** [comment]
> --process-definition-- The first time I click run, it shows success, but there are no workflows and tasks running in the view instance. The second time I click run, the workflow and tasks can run normally

Could you check if there is any valid information in the logs?

**Comment by bdxmq** [comment]
Now it's ok. I found that my colleagues installed the old version according to the installation method, and did not change the configuration of the service, including application.yaml and common.properties. The old version does not need to be changed after it is configured in install. Now that the configuration is changed, there is no problem. Sorry, our problem.

**Comment by SbloodyS** [comment]
Glad to here that. I'll close this issue.
