### ISSUE TITLE
[Bug] [Logger Server] Incorrect password regular expression

### ISSUE THREAD

**Issue by bdxmq** [apache/dolphinscheduler#11452]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

SensitiveDataConverter passwordHandler
/**
     * dataSource sensitive param
     */
    public static final String DATASOURCE_PASSWORD_REGEX = "(?<=((?i)password((\\\\\":\\\\\")|(=')))).*?(?=((\\\\\")|(')))";

The log password printed at runtime is not replaced with * sign

### What you expected to happen

"password":"view1"
can replace to
"password":"****"

### How to reproduce

the old pattern is ok.
DATASOURCE_PASSWORD_REGEX = "(?<=(\"password\":\")).*?(?=(\"))"

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bdxmq** [comment]
version:3.0.0
shell task
![image](https://user-images.githubusercontent.com/21127891/184328255-9ae6ae85-7f4e-4be6-91a9-811d98c9547d.png)

**Comment by bdxmq** [comment]
version:3.0.0
shell task
echo "password":"abcdefg"
![image](https://user-images.githubusercontent.com/21127891/184328643-b1d24547-39e1-4610-88f2-2b1eaa234e88.png)

**Comment by ruanwenjun** [comment]
Could you please with the latest regex in dev `(?<=((?i)password((\\\\\":\\\\\")|(=')))).*?(?=((\\\\\")|(')))`

**Comment by bdxmq** [comment]
dev is the same as the parttern of 3.0.0
