### ISSUE TITLE
[Bug][Master] Serial first blocking

### ISSUE THREAD

**Issue by WangJPLeo** [apache/dolphinscheduler#11465]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Serial first blocking

### What you expected to happen

Normal

### How to reproduce

Execute multiple instances under the serial-first execution strategy

### Anything else

No

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@WangJPLeo May I ask whether we are going to add this patch in 3.0.2? If not, I will update the milestone to 3.0.3. Thanks
