### ISSUE TITLE
[Bug] [Workflow] Failed to submit the workflow instance

### ISSUE THREAD

**Issue by stalary** [apache/dolphinscheduler#11476]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Master-server down, Failed to submit the workflow instance, will resend the workflow start event

[ERROR] 2022-08-15 10:04:08.181 +0800 org.apache.dolphinscheduler.server.master.event.WorkflowStartEventHandler:[74] - [WorkflowInstance-0][TaskInstance-0] - Failed to submit the workflow instance, will resend the workflow start event: WorkflowEvent(workflowEventType=START_WORKFLOW, workflowInstanceId=1193)
[INFO] 2022-08-15 10:04:08.181 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowEventLooper:[79] - [WorkflowInstance-1193][TaskInstance-0] - Workflow event looper receive a workflow event: WorkflowEvent(workflowEventType=START_WORKFLOW, workflowInstanceId=1193), will handle this
[INFO] 2022-08-15 10:04:08.181 +0800 org.apache.dolphinscheduler.server.master.event.WorkflowEventQueue:[38] - [WorkflowInstance-0][TaskInstance-0] - Added workflow event to workflowEvent queue, event: WorkflowEvent(workflowEventType=START_WORKFLOW, workflowInstanceId=1193)
[INFO] 2022-08-15 10:04:08.181 +0800 org.apache.dolphinscheduler.server.master.event.WorkflowStartEventHandler:[54] - [WorkflowInstance-1193][TaskInstance-0] - Handle workflow start event, begin to start a workflow, event: WorkflowEvent(workflowEventType=START_WORKFLOW, workflowInstanceId=1193)
[ERROR] 2022-08-15 10:04:08.181 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[688] - [WorkflowInstance-1194][TaskInstance-0] - Start workflow error
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.dao.utils.DagHelper.parsePostNodes(DagHelper.java:301)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitPostNode(WorkflowExecuteRunnable.java:1257)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.call(WorkflowExecuteRunnable.java:682)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### What you expected to happen

Normal run.

### How to reproduce
Use 3.0.0-beta1 create a process and start it, remove it and upgrade 3.0.0, The tasks that have been deleted are scheduled again

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
This is caused by a NPE, could you please check if the data is right in `DagHelper.parsePostNodes`?

**Comment by stalary** [comment]
Like the dependent node problem, the deleted task depends on the upstream task, and when deleted, the upstream completes the complement operation.

**Comment by stalary** [comment]
A bit like the dependency node problem, the deleted task depends on the upstream task, and when deleted, the upstream completes the complement operation.

**Comment by Leijingwen** [comment]
我也遇到了相同的情况,一直疯狂写日志,有解决的方案了吗?

**Comment by JaayYoung** [comment]
这个问题还没得到解决嘛 ？
