### ISSUE TITLE
[Feature][S3 bucket config] Feature title

### ISSUE THREAD

**Issue by BradyYue** [apache/dolphinscheduler#11486]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

s3 存储支持功能：
配置中FS_S3A_ENDPOINT 的设置ip 方式在aws 会动态变化.

![image](https://user-images.githubusercontent.com/21214368/184614256-d27b2649-ae76-4362-8927-b20a123510a4.png)

### Use case

是否可以采用域名的方式，去访问aws s3 bucket

### Related issues

ds 使用s3 做为存储, 官方文档 建议FS_S3A_ENDPOINT 配成ip 的方式，
但对于这个 ip 在aws 上是会动态变化的，
咨询下目前ds 这块是如何来做的，或者使用上有什么建议

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @BradyYue , please change to the correct title.

**Comment by BradyYue** [comment]
> 嗨@BradyYue，请更改为正确的标题。

正确的标题应该是？我理解这个是功能里 s3存储配置的一项， 如果需要修改，可以提供下需要改为的title ，谢谢
