### ISSUE TITLE
[Feature][datax] Hopefully Datax can submit to YARN

### ISSUE THREAD

**Issue by duhanmin** [apache/dolphinscheduler#11488]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I made the Data on Yarn plugin. Dolphinscheduler can be added to this function?

```
https://github.com/duhanmin/datax-on-yarn
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Is there anything we can check in advance to see if it is allowed? Such as licenses. PTAL @kezhenxu94 @zhongjiajie

**Comment by duhanmin** [comment]
If I could, I'd start writing code

**Comment by kezhenxu94** [comment]
@duhanmin how do you plan to use https://github.com/duhanmin/datax-on-yarn ? Importing by maven module or import the codes from that repository?

**Comment by duhanmin** [comment]
@kezhenxu94 Jar is configured in environment variables,With the shell startup,Pom import Hadoop dependencies are easily conflicted

```
/usr/bin/yarn jar /mnt/dss/211/datax-on-yarn-1.0.0.jar com.on.yarn.Client \
  -jar_path /mnt/dss/211/datax-on-yarn-1.0.0.jar \
  -appname DemoApp \
  -master_memory 1024 \
  -queue default \
  -proxy_user  hanmin.du \
  -datax_job /mnt/dss/datax/job/t2.json \
  -datax_home_hdfs /tmp/linkis/hadoop/datax.tar.gz
```

**Comment by zhongjiajie** [comment]
> @kezhenxu94 Jar is configured in environment variables,With the shell startup,Pom import Hadoop dependencies are easily conflicted
> 
> ```
> /usr/bin/yarn jar /mnt/dss/211/datax-on-yarn-1.0.0.jar com.on.yarn.Client \
>   -jar_path /mnt/dss/211/datax-on-yarn-1.0.0.jar \
>   -appname DemoApp \
>   -master_memory 1024 \
>   -queue default \
>   -proxy_user  hanmin.du \
>   -datax_job /mnt/dss/datax/job/t2.json \
>   -datax_home_hdfs /tmp/linkis/hadoop/datax.tar.gz
> ```

So you call `datax-on-yarn` by shell? if in this case, we can ignore the license issue because we never add this dependent in our source code base. User should download/build the dist jar by themself and put it into worker server

**Comment by duhanmin** [comment]
@zhongjiajie yes

**Comment by kezhenxu94** [comment]
@duhanmin if so, it can be added without license concerns
