### ISSUE TITLE
[Bug] [Task Definition] 3.0 can not select pre tasks  

### ISSUE THREAD

**Issue by rusonding** [apache/dolphinscheduler#11499]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. can not select pre tasks 

![image](https://user-images.githubusercontent.com/21210508/184796043-5e243ab0-6a90-44c2-a347-4429a2def33b.png)

2.  dag save error

![image](https://user-images.githubusercontent.com/21210508/184796228-ad31da26-02fb-4984-9c36-33ff07b3cb1e.png)

### What you expected to happen

can create task in Task Definition

### How to reproduce

 create new task in   [Task->Task Definition]

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
For the second:
The front end has inputed the workflow code when saving a task, but the workflow code turned to 0 with the simple list interface.

**Comment by Amy0104** [comment]
For the first:
The front end has inputed the upstream task code when saving a task, but got an error.
