### ISSUE TITLE
Using a pseudo-cluster to build, when adding dependencies to the workflow, the project cannot be searched

### ISSUE THREAD

**Issue by A2Data** [apache/dolphinscheduler#11506]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

3.0.0 版本，创建项目之后，使用工作流依赖项，并不能搜索到项目。
正常来说 我都创建项目了，还能进去 测试。 在依赖项却不能找到 很奇怪

![image](https://user-images.githubusercontent.com/39373008/184844254-1fbd003f-d72c-4489-a787-6621af3d1dfc.png)

![image](https://user-images.githubusercontent.com/39373008/184844600-fe6f858a-9d43-4de2-9a7b-cd215c445cef.png)

### What you expected to happen

正确应该是可以搜到依赖项目才对的

### How to reproduce

有线上环境在使用 可以提供测试

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please use english to describe.
