### ISSUE TITLE
[Improvement][User] Query all users filter un enabled.

### ISSUE THREAD

**Issue by WangJPLeo** [apache/dolphinscheduler#11503]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Query all users filter un enabled.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
closed by #11504
