### ISSUE TITLE
[Bug][Resource] Error using sql conf type file in resource

### ISSUE THREAD

**Issue by chenhaonan313** [apache/dolphinscheduler#11515]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

aa.sql flumea.conf In the Resource Center
Shell Command：sudo -u hdfs hive -f aa.sql
error: aa.sql(No such file or directory)

Shell  Command：sudo -u hdfs /usr/hdp/flume/bin/flume-ng agent --name a1 --conf conf --conf-file flumea.conf -Dflume.hdfs.logger=INFO,consol
ERRO：the specified configuration file does not exist:/tmp/hsperfdate_hdfs/flumea.conf

Why is the file preceded by /tmp/hsperfdata_hdfs address

sql file not found

But I can bash the shell file

### What you expected to happen

The file in the resource center is not available, you can view the contents of the file using the cat command, but using the file shows that it cannot be found

### How to reproduce

I'm configuring standalone to test that flume conf is executable, paired with a cluster error

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chenhaonan313** [comment]
The file in the resource center is not available, I can view the contents of the file using the cat command, but using the file shows that it cannot be found

**Comment by caishunfeng** [comment]
> The file in the resource center is not available, I can view the contents of the file using the cat command, but using the file shows that it cannot be found

@chenhaonan313 can you check the table `t_ds_resources`?

**Comment by EricGao888** [comment]
@chenhaonan313 `The file in the resource center is not available, you can view the contents of the file using the cat command, but using the file shows that it cannot be found` If you could `cat` the file, probably the file is there. Maybe caused by some kind of file permission error. We've implemented `hive cli task plugin` based on shell executor and it has been released in 3.1.0, maybe u could try it : )
