### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by l838224553** [apache/dolphinscheduler#11526]
It is my problem, this issue can be deleted

**Comment by kaori-seasons** [comment]
I would like to try to track down the relevant details

**Comment by l838224553** [comment]
> 

I configured the email alarm instance, and the send email is turned on, but I didn't get the email.
I have tried the 2.0.6 version and can receive the email.
But I can receive email alarms. Example: start process failed or fault tolerance warning.

**Comment by l838224553** [comment]
> I would like to try to track down the relevant details

I described it in What Happen

**Comment by kaori-seasons** [comment]
https://dolphinscheduler.apache.org/zh-cn/docs/1.3.9/user_doc/system-manual.html

Are recipients set up correctly as described in the documentation?

![work-1](https://user-images.githubusercontent.com/20021404/185284864-6b62c471-92bd-401c-a00a-25b51ace36a7.png)



> > 我想尝试追踪相关细节
> 
> 我在“发生了什么”中描述了它

**Comment by l838224553** [comment]
> Are recipients set up correctly as described in the documentation?

Yours is version 1.3.9, I wrote version 3.0.0 in the title, The interface is what I took a screenshot of, I just need to select the alarm group, and I can receive the alert email, but I can't receive the sql query result email
![image](https://user-images.githubusercontent.com/36987867/185314454-339f0cd6-fc90-4cca-abd6-fd41250cbc5e.png)

**Comment by l838224553** [comment]
> https://dolphinscheduler.apache.org/zh-cn/docs/1.3.9/user_doc/system-manual.html
> 
> Are recipients set up correctly as described in the documentation?
> 
> ![work-1](https://user-images.githubusercontent.com/20021404/185284864-6b62c471-92bd-401c-a00a-25b51ace36a7.png)
> 
> > > 我想尝试追踪相关细节
> > 
> > 
> > 我在“发生了什么”中描述了它

I tried the single-machine deployment and can receive the SQL query result email, but the cluster deployment cannot. 
I configured it according to the official documentation, I don't know what went wrong

**Comment by l838224553** [comment]
> https://dolphinscheduler.apache.org/zh-cn/docs/1.3.9/user_doc/system-manual.html
> 
> Are recipients set up correctly as described in the documentation?
> 
> ![work-1](https://user-images.githubusercontent.com/20021404/185284864-6b62c471-92bd-401c-a00a-25b51ace36a7.png)
> 
> > > 我想尝试追踪相关细节
> > 
> > 
> > 我在“发生了什么”中描述了它

I tried the single-machine deployment and can receive the SQL query result email, but the cluster deployment cannot. 
I configured it according to the official documentation, I don't know what went wrong
