### ISSUE TITLE
[Improvement][dolpscheduler-ui] some datasourceType which backend can't support ,but show in frontend

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#11524]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://user-images.githubusercontent.com/33984497/185054369-e9c9a9aa-76fb-4a7f-9fb3-1db30590aceb.png)

![image](https://user-images.githubusercontent.com/33984497/185054013-9d33f0c6-120d-4c55-8b95-458f22e4969e.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
Is this only for the datax task? @fuchanghai
