### ISSUE TITLE
[Feature][Master] Display the workflowInstance/taskInstance failed reason

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#11530]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

If a workflow instance/ task instance is failed, we need to query the log and find out why it failed.

Can we save the failed reason to db as metadata, and display on the ui? 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
I may not feel good if it just saves the error message. Because many times the error message has to be seen against the context of the program. If the context is also stored together, the larger context will cause oom，personal opinion only

**Comment by ruanwenjun** [comment]
> I may not feel good if it just saves the error message. Because many times the error message has to be seen against the context of the program. If the context is also stored together, the larger context will cause oom，personal opinion only

The `error message` is not exception stack, it is defined in master/worker, e.g `dispatch failed`, `server error`, `workflow definition doesn't exist` ...

**Comment by fuchanghai** [comment]
@ruanwenjun Can I understand it this way, our previous logs are just the output produced by the task execution. But before execution, he may also report an error, but the user cannot view it on the front end, and can only find this error in the log file afterwards. so we should do this

**Comment by ruanwenjun** [comment]
> @ruanwenjun Can I understand it this way, our previous logs are just the output produced by the task execution. But before execution, he may also report an error, but the user cannot view it on the front end, and can only find this error in the log file afterwards. so we should do this

Yes, and the workflow may execute failed due to some other reason, we didn't display workflow log on the ui.

**Comment by fuchanghai** [comment]
> > @ruanwenjun Can I understand it this way, our previous logs are just the output produced by the task execution. But before execution, he may also report an error, but the user cannot view it on the front end, and can only find this error in the log file afterwards. so we should do this
> 
> Yes, and the workflow may execute failed due to some other reason, we didn't display workflow log on the ui.

I suggest not just logging error messages, we should log the execution flow。eg:(start_process(success)->buildDAG (success)-> put into task queue (success)->handleCommon(failed)). this allows users to more clearly understand what went wrong in the execution.

**Comment by ruanwenjun** [comment]
> > > @ruanwenjun Can I understand it this way, our previous logs are just the output produced by the task execution. But before execution, he may also report an error, but the user cannot view it on the front end, and can only find this error in the log file afterwards. so we should do this
> > 
> > 
> > Yes, and the workflow may execute failed due to some other reason, we didn't display workflow log on the ui.
> 
> I suggest not just logging error messages, we should log the execution flow。eg:(start_process(success)->buildDAG (success)-> put into task queue (success)->handleCommon(failed)). this allows users to more clearly understand what went wrong in the execution.

The problem is that we still need to login the master machine and query the log...

**Comment by ruanwenjun** [comment]
> > > @ruanwenjun Can I understand it this way, our previous logs are just the output produced by the task execution. But before execution, he may also report an error, but the user cannot view it on the front end, and can only find this error in the log file afterwards. so we should do this
> > 
> > 
> > Yes, and the workflow may execute failed due to some other reason, we didn't display workflow log on the ui.
> 
> I suggest not just logging error messages, we should log the execution flow。eg:(start_process(success)->buildDAG (success)-> put into task queue (success)->handleCommon(failed)). this allows users to more clearly understand what went wrong in the execution.

The `error message ` will be user friendly.

**Comment by caishunfeng** [comment]
Good idea. 
I found that ds workflow instance loss some message, such as stop reason, maybe it's stopped by workflow execute strategy or others, but we have to spend time searching and locating the cause from logs. 
So we need this failed reason to help users locate problems.

**Comment by caishunfeng** [comment]
Here is my design of state history:

- Add a new column of status description to the workflow instance list, the format is as follows:

RUNNING → READY_PAUSE → PAUSE → RUNNING → STOP

- Hover or click to display the specific historical status description, as follows:

![image](https://user-images.githubusercontent.com/11962619/187885913-14614d2a-8bcc-4cd1-913f-026831e799d1.png)

**Comment by fuchanghai** [comment]
> Here is my design of state history:
> 
> * Add a new column of status description to the workflow instance list, the format is as follows:
> 
> RUNNING → READY_PAUSE → PAUSE → RUNNING → STOP
> 
> * Hover or click to display the specific historical status description, as follows:
> 
> ![image](https://user-images.githubusercontent.com/11962619/187885913-14614d2a-8bcc-4cd1-913f-026831e799d1.png)

Can you list all the states you can think of，This might give me an idea of ​​where you'd add the logic to add these states

**Comment by caishunfeng** [comment]
> Can you list all the states you can think of，This might give me an idea of ​​where you'd add the logic to add these states

The state of `WorkflowExecutionStatus` enum when use. I just add the state history and state desc for it.
