### ISSUE TITLE
[Question] [python] run python task,Permission denied

### ISSUE THREAD

**Issue by ryuunami** [apache/dolphinscheduler#11544]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

dolphinscheduler run with docker-compose。
python task： print("This is a demo of python task")

error with:

[LOG-PATH]: /opt/dolphinscheduler/logs/20220818/6577088940288_6-23-32.log, [HOST]:  Host{address='172.18.0.8:1234', ip='172.18.0.8', port=1234}

[INFO] 2022-08-18 17:20:47.195 +0000 [taskAppId=TASK-20220818-6577088940288_6-23-32] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.python.PythonTask:[83] - python task params {"localParams":[],"rawScript":"print(\"This is a demo of python task\")","resourceList":[]}

[INFO] 2022-08-18 17:20:47.198 +0000 [taskAppId=TASK-20220818-6577088940288_6-23-32] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.python.PythonTask:[225] - raw python script : print("This is a demo of python task")

[INFO] 2022-08-18 17:20:47.199 +0000 [taskAppId=TASK-20220818-6577088940288_6-23-32] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.python.PythonTask:[178] - tenantCode :liu, task dir:/tmp/dolphinscheduler/exec/process/6388981034080/6577088940288_6/23/32

[INFO] 2022-08-18 17:20:47.200 +0000 [taskAppId=TASK-20220818-6577088940288_6-23-32] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.python.PythonTask:[181] - generate python script file:/tmp/dolphinscheduler/exec/process/6388981034080/6577088940288_6/23/32/py_23_32.py

[INFO] 2022-08-18 17:20:47.200 +0000 [taskAppId=TASK-20220818-6577088940288_6-23-32] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.python.PythonTask:[188] - #-*- encoding=utf8 -*-

print("This is a demo of python task")

[INFO] 2022-08-18 17:20:47.201 +0000 [taskAppId=TASK-20220818-6577088940288_6-23-32] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.python.PythonTask:[85] - tenantCode user:liu, task dir:23_32

[INFO] 2022-08-18 17:20:47.202 +0000 [taskAppId=TASK-20220818-6577088940288_6-23-32] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.python.PythonTask:[90] - create command file:/tmp/dolphinscheduler/exec/process/6388981034080/6577088940288_6/23/32/23_32.command

[INFO] 2022-08-18 17:20:47.202 +0000 [taskAppId=TASK-20220818-6577088940288_6-23-32] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.python.PythonTask:[116] - command : #!/bin/sh

BASEDIR=$(cd `dirname $0`; pwd)

cd $BASEDIR

source /opt/dolphinscheduler/conf/dolphinscheduler_env.sh

${PYTHON_HOME} /tmp/dolphinscheduler/exec/process/6388981034080/6577088940288_6/23/32/py_23_32.py

[INFO] 2022-08-18 17:20:47.205 +0000 [taskAppId=TASK-20220818-6577088940288_6-23-32] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.python.PythonTask:[290] - task run command: sudo -u liu sh /tmp/dolphinscheduler/exec/process/6388981034080/6577088940288_6/23/32/23_32.command

[INFO] 2022-08-18 17:20:47.206 +0000 [taskAppId=TASK-20220818-6577088940288_6-23-32] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.python.PythonTask:[181] - process start, process id is: 5354

[INFO] 2022-08-18 17:20:47.221 +0000 [taskAppId=TASK-20220818-6577088940288_6-23-32] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.python.PythonTask:[205] - process has exited, execute path:/tmp/dolphinscheduler/exec/process/6388981034080/6577088940288_6/23/32, processId:5354 ,exitStatusCode:126 ,processWaitForStatus:true ,processExitValue:126

[INFO] 2022-08-18 17:20:48.207 +0000 [taskAppId=TASK-20220818-6577088940288_6-23-32] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.python.PythonTask:[63] -  -> /tmp/dolphinscheduler/exec/process/6388981034080/6577088940288_6/23/32/23_32.command: 4: /tmp/dolphinscheduler/exec/process/6388981034080/6577088940288_6/23/32/23_32.command: source: not found

	/tmp/dolphinscheduler/exec/process/6388981034080/6577088940288_6/23/32/23_32.command: 5: /tmp/dolphinscheduler/exec/process/6388981034080/6577088940288_6/23/32/23_32.command: /tmp/dolphinscheduler/exec/process/6388981034080/6577088940288_6/23/32/py_23_32.py: Permission denied

[INFO] 2022-08-18 17:20:48.209 +0000 [taskAppId=TASK-20220818-6577088940288_6-23-32] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.python.PythonTask:[57] - FINALIZE_SESSION

### What you expected to happen

print This is a demo of python task

### How to reproduce

docker-compose.yaml in source code example

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please check the permissions of the executing user.

BTW, it's not a bug.But a question.

**Comment by ryuunami** [comment]
I think is my mistake with docker-compose version

**Comment by dyyTT** [comment]
I also encountered the same problem. Have you solved this problem？

**Comment by qqamao** [comment]
> I think is my mistake with docker-compose version

Did you solve it?
