### ISSUE TITLE
[Bug] [UI] Edit datasource port show error

### ISSUE THREAD

**Issue by stalary** [apache/dolphinscheduler#11553]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Edit datasource port show error
![截屏2022-08-19 09 49 58](https://user-images.githubusercontent.com/24592373/185525346-ab35d2c4-755a-45af-a7c9-3158146703ff.png)

### What you expected to happen

show correct, as backend return.

### How to reproduce

use 3.0.0-release and create datasource, refresh page, and edit it.

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.
