### ISSUE TITLE
[Feature]airflow task migration to dolphinscheduler migration script

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/dolphinscheduler#11557]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

airflow task migration to dolphinscheduler migration script

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ghostbody** [comment]
+1.

And I am curious what advantages does dolphinescheduler have comprare to Apache Airflow? Performance?
