### ISSUE TITLE
[Improvement][API] Improvement the error message when delete a online workflow

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#11554]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When I delete an online workflow, it failed, and I get the below error message. 
This is not friendly. 
- We should display the workflow name rather then code
- We should display the reason why it delete failed
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/22415594/185528222-b89d19cf-4591-44a0-b14f-528a095fd361.png">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HomminLee** [comment]
I can take this issue.
