### ISSUE TITLE
[Improvement] [Doc] Document content update

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/dolphinscheduler#11550]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

<img width="1569" alt="图片" src="https://user-images.githubusercontent.com/60029759/185409888-d25569f0-9281-4d6c-8fd2-17c7d7aecc77.png">
Change process to workflow, change old image to new image

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
Hi @MonsterChenzhuo May I ask whether you are still working on it?

**Comment by zhongjiajie** [comment]
the picture already to the latest one, we only need to change process definition to workflow
