### ISSUE TITLE
[Feature]dolphinscheduler3 supports Ambari plugin

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/dolphinscheduler#11558]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

dolphinscheduler3 supports Ambari plugin

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sunnydoudou** [comment]
同样在寻找dolphinscheduler3的ambari插件配置，想问下什么时候会提供？
