### ISSUE TITLE
[Improvement] [sql task] Dynamic table name causes SQL parsing error. Because Postgres does not support single quotation marks for table names

### ISSUE THREAD

**Issue by zhuyt1090** [apache/dolphinscheduler#11566]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Define SQL tasks as follows:

![image](https://user-images.githubusercontent.com/108874436/185571825-a1305f55-dfbc-4f0c-9f1e-6389ecf2d787.png)

Execute the SQL task, and the error is as follows:

![image](https://user-images.githubusercontent.com/108874436/185572706-8661ba24-fa66-4369-b7b2-d68a4de24269.png)

### What you expected to happen

The Postgres data source supports the table name as a parameter

### How to reproduce

1. Create an SQL task and select the Postgres data source;

2. Define the query statement, and the table name is a parameter;

3. Add parameters and transfer table name

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
i suggest that should add a TEXTPLAIN param type.
