### ISSUE TITLE
[Doc][Metrics] Metrics of Chinese page link errors

### ISSUE THREAD

**Issue by QuakeWang** [apache/dolphinscheduler#11575]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The Chinese page for metrics on the official website is incorrectly linked and cannot be accessed properly.

### Documentation Links

https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/guide/metrics/metrics.html

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
fix in https://github.com/apache/dolphinscheduler/commit/9badb2d2fbc6b79efca96247dbc49a39ca6868f7,the link https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/guide/metrics/metrics.html work correctly. thank for your feedback @QuakeWang

**Comment by zhongjiajie** [comment]
for release manager, I directly add a new commit to branch 3.0.0-release, so we can checkout new branch from 3.0.0-release and not cherry pick this commit
