### ISSUE TITLE
[Bug] [Script] Cannot check the applications status.

### ISSUE THREAD

**Issue by DarkAssassinator** [apache/dolphinscheduler#11579]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When we check the application status by using ./bin/status-all.sh, it cannot show the correct status.

For example:
If just only one Alert Application running, this script will show that all application running.

Because the script use the following command to check the status:
serverCount=`ps -ef | grep "$DOLPHINSCHEDULER_HOME" | grep "$CLASS" | grep -v "grep" | wc -l`

this command has some issues:
1. do not define the @CLASS, just a install path home, cannot make sure which applicaiton is running.
2. If some guy using absolute path to open a file or other process runing on this install path home, this command will show application is running, but in fact no.

We must ensure that this process ID is unique and accurate.

### What you expected to happen

When we run the ./bin/status-all.sh, it can show the status correct. Not just a wrong result. 

### How to reproduce

There are many ways to reproduce this case, for example:

1. Deploy a cluster service on sigle server, and keep only one application such as Alert, then run ./bin/status-all.sh
2. use this command to open a log file "tail -500f $DOLPHINSCHEDULER_HOME//master-server/logs/***.log", then run it. 

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
Please check the following screenshot：
![Image](https://user-images.githubusercontent.com/20518339/185780459-12f4a135-a692-40ae-9d21-d69a3758854d.png)

**Comment by ruanwenjun** [comment]
duplicated with #11176
