### ISSUE TITLE
[Feature] [DataSource] Could  we add MQ and memory db datasource?

### ISSUE THREAD

**Issue by DarkAssassinator** [apache/dolphinscheduler#11581]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Now just contain jdbc drived database, not any mq such as kafka cluser.
Do we have any plan to add MQ、Redis and ES datasource, or named other module.

### Use case

We can configure some MQ, redis and ES cluster services. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
can i do this case? i am interest in this, i want to add kafka cluster first.
or we can dicuss it.

**Comment by HSPCode** [comment]
i meet the same case,such as Ftp、Es、OSS、OTS...
