### ISSUE TITLE
[Bug] [UI] Gantt chart does not show

### ISSUE THREAD

**Issue by luoxiqiang** [apache/dolphinscheduler#11583]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

**task.status** is expected to get a status string value such as ' SUCCESS ' but the backend returns an object like ' TaskExecutionStatus{code=7, desc=' success'} ' where a mapping is required
![image](https://user-images.githubusercontent.com/32994527/185825811-366bb01c-8214-42e9-9c61-62360f484bcd.png)

### What you expected to happen

Open the Gantt chart

### How to reproduce

Open the Gantt chart

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
Can you provide the data returned by the backend?
Normal, the back-end data should be similar to the following
<img width="783" alt="image" src="https://user-images.githubusercontent.com/8847400/186361169-ae3b426e-aea1-470d-8090-24585564bd5e.png">

**Comment by luoxiqiang** [comment]
![image](https://user-images.githubusercontent.com/32994527/186580317-c79189e7-0031-417e-a101-ed8289908b13.png)

**Comment by hezean** [comment]
@luoxiqiang thanks for finding this bug, may I submit a pr if you're not going to fix it?

**Comment by luoxiqiang** [comment]
ok, thank you for your contribution

**Comment by mhsccd** [comment]
i look for the v3.1.1 code ,find the task instance get this state used toString function...... but the state is a enmu class,we should use getDesc function right!

**Comment by mhsccd** [comment]
![Uploading 企业微信截图_16700511027142.png…]()

**Comment by mhsccd** [comment]
![Uploading 企业微信截图_16700510842490.png…]()

**Comment by lxorc** [comment]
@luoxiqiang  thanks for finding this bug, may I submit a pr if you're not going to fix it? 

Currently this issue is not fully fixed and there are problems .
