### ISSUE TITLE
[Question] [UI] Can not start dolphinscheduler-ui locally

### ISSUE THREAD

**Issue by MkkOF** [apache/dolphinscheduler#11584]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. npm/pnpm install
2. npm/pnpm run dev
errorr:
node_modules/.pnpm/vite@2.9.13_sass@1.53.0/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:38572:7: ERROR: [plugin: vite:dep-scan] Missing "./es/_mixins" export in "naive-ui" package
node_modules/.pnpm/vite@2.9.13_sass@1.53.0/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:38572:7: ERROR: [plugin: vite:dep-scan] Missing "./es/_mixins" export in "naive-ui" package
node_modules/.pnpm/vite@2.9.13_sass@1.53.0/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:38572:7: ERROR: [plugin: vite:dep-scan] Missing "./es/_mixins" export in "naive-ui" package
node_modules/.pnpm/vite@2.9.13_sass@1.53.0/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:38572:7: ERROR: [plugin: vite:dep-scan] Missing "./es/_mixins/" export in "naive-ui" package
node_modules/.pnpm/vite@2.9.13_sass@1.53.0/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:38572:7: ERROR: [plugin: vite:dep-scan] Missing "./es/_utils" export in "naive-ui" package

### What you expected to happen

start dolphinscheduler-ui

### How to reproduce

1. npm/pnpm install
2. npm/pnpm run dev

npm version 16.16.0
npmp version 6.32.11

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
I faced the same issue, whether to consider providing some front-end develop and extend documents, the current version of the documents on the front-end has expired, and it is still difficult for back-end development. thx

**Comment by labbomb** [comment]
Are you referencing es /_mixins directly in some of the source code? If so, it should be introduced from the unified entrance as much as possible

**Comment by MkkOF** [comment]
> 

errors happened in the source code of dolphinsheduler-ui，custom-parameters.ts and some other .ts files 
![image](https://user-images.githubusercontent.com/18656889/186086727-f9f3a674-7112-4ff5-9680-154eb3c3f24e.png)

**Comment by songjianet** [comment]
Naive has been upgraded, pnpm7+ may be required, and I will update the corresponding README in the future.

**Comment by zhoufanglu** [comment]
> Naive has been upgraded, pnpm7+ may be required, and I will update the corresponding README in the future.

now how to resolve this question?

**Comment by DarkAssassinator** [comment]
it's fix after i update pnpm to 7.9.5.

**Comment by DarkAssassinator** [comment]
it's fix after i update pnpm to 7.9.5.

**Comment by jinfengyan** [comment]
When I shipped this problem, I said that the version of pnpm was updated to the latest version, and the bug was still not solved, but after I updated vite to the latest version, the problem was solved.

For example: pnpm install vite@3.1.0
