### ISSUE TITLE
The workflow defines that both data sources are mysql

### ISSUE THREAD

**Issue by luojinhao** [apache/dolphinscheduler#11587]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

datax plugin, The workflow defines that both data sources are mysql

### What you expected to happen

Displays the data type I specified

### How to reproduce

The workflow defines that both data sources are mysql

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Could you please provide more detail?
