### ISSUE TITLE
[Bug] [SparkSQL] the task can not be stopped.

### ISSUE THREAD

**Issue by xiaohei88** [apache/dolphinscheduler#11597]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

the task command type is RECOVER_TOLERANCE_FAULT_PROCESS. the runTimes is 28. 
I want to stop the task, but it's fail.

### What you expected to happen

I want to stop the task

### How to reproduce

I don't know.

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Could you provide more detail infomation about this issue? @xiaohei88
