### ISSUE TITLE
Cannot support custom data transfer between nodes （不能支持节点间的自定义数据传输）

### ISSUE THREAD

**Issue by sancong** [apache/dolphinscheduler#116]

**Comment by lyf198972** [comment]
比如第一节点的输出参数，可以作为下一节点的输入

**Comment by lidongdai** [comment]
good idea!

Could you give us more detail requirement，such as “how to transfer data ？ key/value or other method”

or Could you submit a pull request to solve this question？

we will add this as feature ideas!  if anybody else has the same requirement, please reply "+1"

**Comment by yangjiajun2014** [comment]
Just for u reference.

According to my understanding,there is no output define for a  task node of easyscheduler.

In some of our user cases,some task nodes need to use data produced by pre nodes.We mostly solve such cases by storing   data to a temp place.Other nodes only need to know where is the data  or what the pattern of the data.

In cases of microservice orchestration,we exactly need to pass data generated by some http apis to others.But I don't think  easyscheduler is good for such cases now.

**Comment by aixiaoai81** [comment]
Node A,B,C,D;

```
if(A execute result=='1')  flows  int to next node B;
if(A execute result=='2)  flows  int to next node C;
if(A execute result=='3')  flows  int to next node D;
```

can support this feature and above condition edited by ognl or dynamic sql language?

**Comment by lianjie1229** [comment]
+1

**Comment by E10814090** [comment]
+1

**Comment by jonny-gg** [comment]
+1

**Comment by wybaby168** [comment]
+1

**Comment by davidzollo** [comment]
3.0 has support the result of prior task to the next task as input param

**Comment by CharleyXu** [comment]
> 3.0 has support the result of prior task to the next task as input param

how to do
