### ISSUE TITLE
[Bug] [Workflow - Resource] Workflow failure due to inclusion of secondary directory files

### ISSUE THREAD

**Issue by yu-ang-zhang** [apache/dolphinscheduler#11607]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I tried to run the shell script file in the folder, I selected the corresponding footer in the resource bar, when I tried to call the script using sh the workflow failed to run and only a log of the log address showed up in the log. I tried some possible solutions until I removed the call method but still had the footer selected in the resource bar, then tried the simplest echo to print a paragraph and found that it still failed to run, it worked fine after I removed the selection in the resource bar. I have tried both the official version of 3.0 and beta 2 of 3.0 with the same problem.

我尝试运行在文件夹中的shell脚本文件，我在资源栏选择了对应的脚步，当我尝试使用sh去调用脚本时，工作流运行失败，日志中只有一条日志地址的日志显示。我尝试了一些可能的解决方案，直至我把调用方法删除，但仍然在资源栏中选择了脚步，然后尝试了最简单的echo打印一段话，发现依然运行失败，我将资源栏中的选定删除之后可以正常运行。我尝试了3.0的正式版和3.0的beta2都有同样的问题。

### What you expected to happen

I think there may be a problem where the address of the resource bar is being read.

我认为是在读取资源栏地址的地方可能有问题。

### How to reproduce

Create a folder, create a shell script in the folder, then create a workflow, introduce a shell task in the workflow and read this created shell script in the shell task.

创建一个文件夹，在文件夹中创建一个shell脚本，然后创建一个工作流，在工作流中引入一个shell任务，在shell任务中读取这个创建的shell脚本。

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
What resource type did you use? HDFS or S3? @yu-ang-zhang

**Comment by yu-ang-zhang** [comment]
> What resource type did you use? HDFS or S3? @yu-ang-zhang

Is HDFS, thx

**Comment by yu-ang-zhang** [comment]
> Thank you for your feedback, we have received your issue, Please wait patiently for a reply.
> 
> * In order for us to understand your request as soon as possible, please provide detailed information、version or pictures.
> * If you haven't received a reply for a long time, you can [join our slack](https://s.apache.org/dolphinscheduler-slack) and send your question to channel `#troubleshooting`

![WeChat Screenshot_20220823103514](https://user-images.githubusercontent.com/88067782/186058013-16073030-b1ef-4023-8fca-6703329d9751.png)
![WeChat Screenshot_20220823103637](https://user-images.githubusercontent.com/88067782/186058019-f8dfe4ae-05d1-4a2f-96b5-eaebe6935c18.png)
![WeChat Screenshot_20220823103831](https://user-images.githubusercontent.com/88067782/186058032-1307b940-0085-4ca0-9387-9c892ec2fd94.png)
![WeChat Screenshot_20220823103540](https://user-images.githubusercontent.com/88067782/186058058-838100eb-5071-4346-8086-5ae695b91310.png)

**Comment by SbloodyS** [comment]
It seems there are another error in your `api-server` since your task log cannot be displayed normally. Please check the error log and paste it here. @yu-ang-zhang

**Comment by yu-ang-zhang** [comment]
> It seems there are another error in your `api-server` since your task log cannot be displayed normally. Please check the error log and paste it here. @yu-ang-zhang

I did try to look at the logs at this address, but I didn't find it under this path

**Comment by yu-ang-zhang** [comment]
> It seems there are another error in your `api-server` since your task log cannot be displayed normally. Please check the error log and paste it here. @yu-ang-zhang

I did try to look at the logs at this address, but I didn't find it under this path. I just tried again and couldn't find log, but found the following log file in the address two levels above the address

![WeChat Screenshot_20220823112226](https://user-images.githubusercontent.com/88067782/186062533-ace133b5-9924-41bd-8b14-2c8c027c7462.png)
![WeChat Screenshot_20220823112146](https://user-images.githubusercontent.com/88067782/186062546-27f89e57-e1e3-4c9c-b244-30c24f9eb180.png)
![WeChat Screenshot_20220823112205](https://user-images.githubusercontent.com/88067782/186062555-81db2b40-d55b-4e73-9eee-5c3fe5b18b4e.png)

**Comment by SbloodyS** [comment]
The log shows that you are using S3 instead of HDFS. The s3 download issue has been fixed in #10433. And will be release in the next version.

**Comment by yu-ang-zhang** [comment]
> 
Thank you very much, I didn't realize we had changed to using S3. Very next release, thanks again!

**Comment by SbloodyS** [comment]
You're welcome. I'll close this issue.
