### ISSUE TITLE
[Bug] [Resources center] bucket name error in s3 while create tenant folder

### ISSUE THREAD

**Issue by 8431** [apache/dolphinscheduler#11601]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

`private void
    createFolder( String folderName) {
        if (!s3Client.doesObjectExist(BUCKET_NAME, folderName + FOLDER_SEPARATOR)) {
            ObjectMetadata metadata = new ObjectMetadata();
            metadata.setContentLength(0);
            InputStream emptyContent = new ByteArrayInputStream(new byte[0]);
            PutObjectRequest putObjectRequest = new PutObjectRequest(BUCKET_NAME, folderName + FOLDER_SEPARATOR, emptyContent, metadata);
            s3Client.putObject(putObjectRequest);
        }
    }`
我在创建租户的时候，会调用这个方法。但是BUCKET_NAME是Constants定义死的常量
`    public static final String BUCKET_NAME = "dolphinscheduler-test";
`
这将限制我必须提前创建一个BUCKET_NAME为dolphinscheduler-test的名称，才能使用s3的功能.
建议官方，讲这个变量配置话提供出来。

### What you expected to happen

这将限制我必须提前创建一个BUCKET_NAME为dolphinscheduler-test的名称，才能使用s3的功能.
建议官方，讲这个变量配置话提供出来。

### How to reproduce

按官方文档配置s3参数

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
Maybe hit the ```improvements``` tag instead of the ```bug``` tag，The title may be modified to 'Allow manual configuration of S3's BUCKET_NAME'

**Comment by SbloodyS** [comment]
I'll fix it.

BTW, it's better to use english to describe it.

**Comment by SbloodyS** [comment]
This issue has been fixed in #10433. Will be release in the next version.
