### ISSUE TITLE
[Question] [UI] router base dev env Refresh fail

### ISSUE THREAD

**Issue by hqzh** [apache/dolphinscheduler#11609]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

i want in dev env append a router pre
![image](https://user-images.githubusercontent.com/26128706/186063212-636459ef-a3c3-49ba-a1cd-302f7e7f73b0.png)
![image](https://user-images.githubusercontent.com/26128706/186063244-616aac06-e77f-4a0a-9800-d0eea7460b9a.png)

### What you expected to happen

```js
const router = createRouter({
  history: createWebHistory(
    import.meta.env.MODE === 'production' ? '/dolphinscheduler/ui/' : '/dolphinscheduler-ui/'
  ),
  routes
})
```

### How to reproduce

yarn run dev .  visit http://localhost:3000/dolphinscheduler-ui/home . first render normal，but refresh 404

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hqzh** [comment]
![image](https://user-images.githubusercontent.com/26128706/186084118-563e2baf-0d1f-4f9f-be7c-3303e08930c5.png)
**为什么加了前缀跑到2.x的界面了**
@SbloodyS

**Comment by hqzh** [comment]
**version 3.0.0 prod  `yarn build:prod`  is render 2.x version UI **  @SbloodyS 
![image](https://user-images.githubusercontent.com/26128706/186092824-b21b9759-b210-4efe-af44-122d6a4d07b7.png)

**Comment by SbloodyS** [comment]
Please use english to describe it. @hqzh

**Comment by hqzh** [comment]
@SbloodyS  Isn't this bug?

**Comment by SbloodyS** [comment]
Please operate according to the environmental requirements and steps of the document.
`https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/contribute/development-environment-setup.html`

**Comment by hqzh** [comment]
I follow the document steps ,but not expected results

**Comment by SbloodyS** [comment]
Can you describe the steps you operate? @hqzh

**Comment by hqzh** [comment]
1. git branch checkout 3.0.0-realease
2. yarn run dev --mode production
@SbloodyS 
**render result is  2.x UI，I expected  3.x UI** 
![image](https://user-images.githubusercontent.com/26128706/186104410-73a17192-ae02-43e5-b32c-46e3d0aec78f.png)

<br /><br /><br />



**normal view，this is docker build.**
![image](https://user-images.githubusercontent.com/26128706/186104636-9434cb12-f0c6-49cd-87cf-6233e520047f.png)

**Comment by SbloodyS** [comment]
Please read the document carefully. We don't support yarn right now. And pull the latest 3.0.0-release branch after checkout.

**Comment by hqzh** [comment]
let me try pnpm, i will feedback

**Comment by hqzh** [comment]
> 1. git branch checkout 3.0.0-realease
> 2. yarn run dev --mode production
>    @SbloodyS
>    **render result is  2.x UI，I expected  3.x UI**
>    ![image](https://user-images.githubusercontent.com/26128706/186104410-73a17192-ae02-43e5-b32c-46e3d0aec78f.png)
> 
> **normal view，this is docker build.** ![image](https://user-images.githubusercontent.com/26128706/186104636-9434cb12-f0c6-49cd-87cf-6233e520047f.png)

pnpm it's works . thanks man.

**Comment by hqzh** [comment]
> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.
> 
> ### What happened
> i want in dev env append a router pre ![image](https://user-images.githubusercontent.com/26128706/186063212-636459ef-a3c3-49ba-a1cd-302f7e7f73b0.png) ![image](https://user-images.githubusercontent.com/26128706/186063244-616aac06-e77f-4a0a-9800-d0eea7460b9a.png)
> 
> ### What you expected to happen
> ```js
> const router = createRouter({
>   history: createWebHistory(
>     import.meta.env.MODE === 'production' ? '/dolphinscheduler/ui/' : '/dolphinscheduler-ui/'
>   ),
>   routes
> })
> ```
> 
> ### How to reproduce
> yarn run dev . visit http://localhost:3000/dolphinscheduler-ui/home . first render normal，but refresh 404
> 
> ### Anything else
> _No response_
> 
> ### Version
> 3.0.0
> 
> ### Are you willing to submit PR?
> * [ ]  Yes I am willing to submit a PR!
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**This problem still exists**

**Comment by hqzh** [comment]
it like's not support  ```-```，why  design it like this？

**Comment by devosend** [comment]
You need to change vite.config.ts ```server: {
    proxy: {
      '/dolphinscheduler': {
        target: loadEnv('development', './').VITE_APP_DEV_WEB_URL,
        changeOrigin: true
      }
    }
  }``` to ```server: {
    proxy: {
      '/dolphinscheduler/': {
        target: loadEnv('development', './').VITE_APP_DEV_WEB_URL,
        changeOrigin: true
      }
    }
  }```. add `/` after `/dolphinscheduler`
