### ISSUE TITLE
[Improvement][task-plugin] New time variables are added to facilitate business development

### ISSUE THREAD

**Issue by fengjian1129** [apache/dolphinscheduler#11608]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In the process of data development, the original time variable provided by the dolphin scheduler needs to do many secondary calculations to obtain the available business time. I want to provide more convenient time variables for business development. for example:
**First day of the month**： $[month_first_day(yyyy-MM-dd,offset)]  offset = month ,such as  $[month_first_day(yyyy-MM-dd,-1)]
**Last day of the month**： $[month_last_day(yyyy-MM-dd,offset)] offset = month ,such as $[month_last_day(yyyy-MM-dd,-1)]
**First day of the week**： $[week_first_day(yyyy-MM-dd, offset)]  offset = week, such as  $[week_first_day(yyyy-MM-dd,-1)]
 **Last day of the week**: $[week_last_day(yyyy-MM-dd, offset)]  offset = week, such as  $[week_last_day(yyyy-MM-dd,-1)] 
I will also provide more time variables with business attributes

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fengjian1129** [comment]
@EricGao888 This issue is about to expire. Does the PR I submitted have any impact ?

**Comment by EricGao888** [comment]
> @EricGao888 This issue is about to expire. Does the PR I submitted have any impact ?

I've removed the `Stale` label. It will not expire.

**Comment by fengjian1129** [comment]
> > @EricGao888 This issue is about to expire. Does the PR I submitted have any impact ?
> 
> I've removed the `Stale` label. It will not expire.

By the way, see if the PR I submitted meets expectations
