### ISSUE TITLE
[Improvement][dolphinscheduler-python] Does not support the callback function when the task is executed like airflow

### ISSUE THREAD

**Issue by woshiwuxiaofei** [apache/dolphinscheduler#11604]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

At present, most of pydolphinscheduler uses python to call JAVA to create certain objects. Only a few methods can obtain JAVA objects. Tasks or workflow running states are missing on the Python side, so callback functions like airflow are not supported.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dijiekstra** [comment]
Perhaps you can customize an alarm plugin such as Rabbit MQ to listen to the success or failure status of a task
