### ISSUE TITLE
[Feature][New Module] using DQL to generate a DAG containing some SQL tasks

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/dolphinscheduler#11615]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The current dolphinscheduler is still too complicated to configure, and often requires pointing and clicking, which is a pain in the ass.
I was wondering if we could just parse a sql into a DAG for scheduling. This becomes a task similar to flinksql, source->map->sink.
Then source corresponds to: probe dependent partition [select from table partition] whether to generate +select operation, sink corresponds to insert operation.

<img width="1135" alt="图片" src="https://user-images.githubusercontent.com/60029759/186134686-a769465e-8f71-4112-990a-d665f749adc6.png">

Production practice articles：
https://dolphinscheduler.apache.org/zh-cn/blog/How_Does_Ziru_Build_A_Job_Scheduling_System_Popular_Among_Data_Analysts.html

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
So this issue is about using DQL to generate a DAG containing some SQL tasks? Please change the issue title.

**Comment by zhongjiajie** [comment]
I think we prefer add this feature to our ecosystem(although is not exists currently)

**Comment by MonsterChenzhuo** [comment]
@zhongjiajie  Can you open a new project for me under dolphinscheduler and give me permission to write or I can contribute the project directly to dolphinscheduler after writing it.

**Comment by MonsterChenzhuo** [comment]
@ruanwenjun Yes, use the sql statement to generate the DAG scheduling task for dolphinscheduler
