### ISSUE TITLE
[Improvement] [Node Execution] 3.0.0 version cannot execute only the current node task

### ISSUE THREAD

**Issue by l838224553** [apache/dolphinscheduler#11612]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In version 3.0.0,  I cannot execute only the current node task. This is because node execution selection is not performed on the operable interface. But version 2.0.6 does.
As shown below, the first picture is the node task operation interface of version 3.0.0, and the second picture is version 2.0.6. It can be seen that version 2.0.6 has the option of executing node, but version 3.0.0 does not.
![image](https://user-images.githubusercontent.com/36987867/186123968-2aeeb2ab-1ed2-4061-8bfd-e9988c42377f.png)
![image](https://user-images.githubusercontent.com/36987867/186124772-d5a5344b-8cef-4db6-987c-c7438b7f001d.png)

### What you expected to happen

Hopefully, version 3.0.0 will also have node execution options, you can select Backward execution and Forward execution and Execute only the current node.

### How to reproduce

You can try using version 3.0.0 to execute only the current node task.

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sketchmind** [comment]
relate #10117
