### ISSUE TITLE
[Bug] [dolphinscheduler-common] When an application is deployed on the EC2 machine on AWS and S3 is operated, it will be rejected

### ISSUE THREAD

**Issue by 8431** [apache/dolphinscheduler#11627]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When you deploy an application on the EC2 machine of AWS to operate S3, it will be rejected

AWS EC2 machine will not use key access because of security policy
![Screenshot2022_08_24_154117](https://user-images.githubusercontent.com/22486827/186360070-3ec8ac39-a9b4-4f46-a55a-c77ccba96425.jpg)
![Screenshot2022_08_24_154232](https://user-images.githubusercontent.com/22486827/186360352-cc6dccb1-5e29-4920-a3c4-ff33a6c8eb15.jpg)

### What you expected to happen

When you deploy an application on the EC2 machine of AWS to operate S3, it will be rejected

AWS EC2 machine will not use key access because of security policy

Therefore, this problem can be compatible when building S3 client objects, so that EC2 machines in AWS can access S3
Whether the code can be compatible with the above scenario
`AWSCredentialsProvider provider = new AWSCredentialsProviderChain(
                    new EC2ContainerCredentialsProviderWrapper(),
                    new AWSStaticCredentialsProvider(new BasicAWSCredentials(ACCESS_KEY_ID, SECRET_KEY_ID)));`

`private S3Utils() {
        if (PropertyUtils.getString(RESOURCE_STORAGE_TYPE).equals(STORAGE_S3)) {
            AWSCredentialsProvider provider = new AWSCredentialsProviderChain(
                    new EC2ContainerCredentialsProviderWrapper(),
                    new AWSStaticCredentialsProvider(new BasicAWSCredentials(ACCESS_KEY_ID, SECRET_KEY_ID)));
            if (!StringUtils.isEmpty(PropertyUtils.getString(AWS_END_POINT))) {
                s3Client = AmazonS3ClientBuilder
                        .standard()
                        .withPathStyleAccessEnabled(true)
                        .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(PropertyUtils.getString(AWS_END_POINT), Regions.fromName(REGION).getName()))
                        .withCredentials(provider)
                        .build();
            } else {
                s3Client = AmazonS3ClientBuilder
                        .standard()
                        .withCredentials(provider)
                        .withRegion(Regions.fromName(REGION))
                        .build();
            }
            checkBucketNameIfNotPresent(BUCKET_NAME);
        }
    }`

### How to reproduce

Deploy the dolphin scheduler project to the EC2 machine of AWS and configure S3 information. Then go to the resource management interface to create a folder

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 8431** [comment]
`private S3Utils() {
        if (PropertyUtils.getString(RESOURCE_STORAGE_TYPE).equals(STORAGE_S3)) {
            AWSCredentialsProvider provider = new AWSCredentialsProviderChain(
                    new EC2ContainerCredentialsProviderWrapper(),
                    new AWSStaticCredentialsProvider(new BasicAWSCredentials(ACCESS_KEY_ID, SECRET_KEY_ID)));
            if (!StringUtils.isEmpty(PropertyUtils.getString(AWS_END_POINT))) {
                s3Client = AmazonS3ClientBuilder
                        .standard()
                        .withPathStyleAccessEnabled(true)
                        .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(PropertyUtils.getString(AWS_END_POINT), Regions.fromName(REGION).getName()))
                        .withCredentials(provider)
                        .build();
            } else {
                s3Client = AmazonS3ClientBuilder
                        .standard()
                        .withCredentials(provider)
                        .withRegion(Regions.fromName(REGION))
                        .build();
            }
            checkBucketNameIfNotPresent(BUCKET_NAME);
        }
    }`

**Comment by 8431** [comment]
Can I submit code? assign to me

**Comment by 8431** [comment]
please assigned me again .thanks

**Comment by caishunfeng** [comment]
Hi @8431 I had assigned you. Looking forward to your pr.

**Comment by EricGao888** [comment]
@8431 Hi, may I ask whether you are still working on it? Thanks
