### ISSUE TITLE
[Feature][worker] select ip based on network displayName

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#11630]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

<img width="669" alt="image" src="https://user-images.githubusercontent.com/33984497/186388948-18d468e4-715b-489d-9208-99ef53f9782f.png">

this machine have two inner ip address.i want to use the second.but ds select the first.(The ip of my local computer is not on the same switch as the first ip on the server, so I have to use the second ip)

i want to config the displayName ```eth1```  for  select which one  i want to use.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
We have already supported this in
https://github.com/apache/dolphinscheduler/blob/878989579150aebe34a8f19e5af7589d74cfebaa/dolphinscheduler-common/src/main/resources/common.properties#L89-L93

However, I found that there is no introduction to this in the document. Would you like to fix it?

**Comment by fuchanghai** [comment]
> We have already support this in
> 
> https://github.com/apache/dolphinscheduler/blob/878989579150aebe34a8f19e5af7589d74cfebaa/dolphinscheduler-common/src/main/resources/common.properties#L89-L93
> 
> However, I found that there is no introduction to this in the document. Would you like to fix it?

OK , There used to be a feature in front of me, but now it's gone
