### ISSUE TITLE
 3.00 version of the scheduled task is invalid

### ISSUE THREAD

**Issue by MFeng1027** [apache/dolphinscheduler#11639]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

   The scheduled task of task flow in version 3.00 cannot select the time below the hour level. When selecting the time, the drop-down box is invalid, and the scheduled task is invalid, and there is no scheduling on the arrival point

### What you expected to happen

its  a bug

### How to reproduce

just  set  a  task

### Anything else

every time

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @MFeng1027 how is this going?

**Comment by caishunfeng** [comment]
I found that it's OK in dev.

**Comment by caishunfeng** [comment]
![image](https://user-images.githubusercontent.com/11962619/190292810-7af99e35-6bdf-4330-8d87-8bb7df35102d.png)

@MFeng1027 I check 3.0.0-release and 3.0.1-prepare, they can set and schedule normally.

So I will close this issue, feel free to reopen it or reply comment, thanks.
