### ISSUE TITLE
[Improvement][Task]  Dependent task nodes support setting dependencies based on offsets

### ISSUE THREAD

**Issue by sketchmind** [apache/dolphinscheduler#11631]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The current dependence task node can support very limited scenarios, if it is changed to offset, it will be more flexible to support more scenarios.

Volcengine has a very good implementation, like the following, which can achieve more dependency scenarios:

># Dependency settings
>
>## Task dependencies
>
>The essence of timed tasks is data processing. In the process of data processing, two processes of data input and data output may be involved. When tasks read data, they will form dependencies between tasks, which are essentially dependencies between tables. Data development uses task dependencies to form the upstream and downstream relationships of data workflows.
>
>## Cross-Cycle Self-Dependence
>
>* Monthly tasks: The execution of this month's tasks depends on the running results of the previous month.
>
>* Weekly tasks: The execution of this week's tasks depends on the results of the previous week.
>
>* Day tasks: The execution of today's tasks depends on the results of yesterday's operation.
>
>* Hourly task: The task execution of the current hour depends on the running result of the previous hour.
>
>* Minute task: The execution of the task instance in the current minute depends on the running result of the previous minute task instance.
>
>## Dependency configuration between tasks
>
>Description: M-month execution frequency, W-week execution frequency, D-day execution frequency, H-hour execution frequency

| type           | actual case                                                                                                         | offset settings (interval/collection offset offset units) |
|----------------|---------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------|
| D depends on D | Depends on the instance of the current day of the upstream task                                                     | Collection 0 days                                         |
| D depends on D | Depends on the instance from the day before the upstream task                                                       | Collection - 1 day                                        |
| D depends on D | Instances that depend on the upstream task in the last 3 days                                                       | interval [-2, 0] days                                     |
| D depends on H | Instances that depend on upstream tasks for the same business date for 24 hours                                     | interval [-23, 0] hours                                   |
| D depends on H | Instances that depend on the same business date of the upstream task and the business date is 0:00, 8:00, and 16:00 | set [-23, -15, -7] hours                                  |
| D depends on W | Depends on the instance of the upstream task last week                                                              | Collection - 1 week                                       |
| D depends on M | Depends on the instance of the upstream task last month                                                             | Collection - 1 month                                      |

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hxssssss** [comment]
I want to participate in the development of this piece of content.

**Comment by sketchmind** [comment]
keep-alive

**Comment by YuanGunGunO** [comment]
it seems like  self dependencies can solve your probleam  but can deal with cross cycle dependencies problems
