### ISSUE TITLE
[Bug] [Workflow] workflow in serial waiting state can not be stopped

### ISSUE THREAD

**Issue by chenhaonan313** [apache/dolphinscheduler#11647]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/79635793/186633899-6c6ff690-11ef-47a1-8cd1-644c329becde.png)

The nodes in the workflow are forbidden execution and serial waiting.
How can this status be suspended? Neither delete nor suspend is available
The action buttons are all unenable

### What you expected to happen

Workflow can be stopped

### How to reproduce

Create shell node in workflow set to disable execution and serial wait, execute workflow

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhaoyu810373097** [comment]
我也遇见了
