### ISSUE TITLE
[Bug] [dolphinscheduler-api] Task type spark, delay time execution, start time in task instance table is empty

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [apache/dolphinscheduler#11657]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Version 2.0.5, task type spark, delay time execution, start time in task instance table is empty

### What you expected to happen

Task type spark, delay time execution, start time in task instance table is not empty

### How to reproduce

Perform tasks of spark type

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hstdream** [comment]
How to reproduce this issue?
