### ISSUE TITLE
[Bug] [worker] In SQL type, hive SQL and spark SQL cannot stop the task

### ISSUE THREAD

**Issue by fengjian1129** [apache/dolphinscheduler#11650]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="795" alt="image" src="https://user-images.githubusercontent.com/35831367/186653701-7c718e76-c64b-40d8-b4c2-d0e62cabcd76.png">

### What you expected to happen

<img width="795" alt="image" src="https://user-images.githubusercontent.com/35831367/186653788-a2710314-0a2b-4905-887f-891fadeb9342.png">

### How to reproduce

First, you can run a hive SQL, then go to the task instance interface and click stop. The status of the task will change from ready to stop to stop, but the task will run successfully

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
Good catch! Looking forward to a fix.

**Comment by caishunfeng** [comment]
Hi @fengjian1129 How is this issue going?

**Comment by zhuangchong** [comment]
@fengjian1129  Please submit it to the 3.0.1-prepare branch, thanks.

**Comment by fengjian1129** [comment]
@caishunfeng PR has been merged

**Comment by fengjian1129** [comment]
@zhuangchong ok
