### ISSUE TITLE
[Improvement][Dev Mailbox] It is recommended to filter non-discussion emails

### ISSUE THREAD

**Issue by wen-hemin** [apache/dolphinscheduler#11656]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Hi, community members!

At present, many people subscribe to the community mailbox, and there are many emails every day, including discussion emails and github emails. Many github emails do not need to be synchronized to the community mailbox.

Too many useless emails will cause many people to stop looking at their mailboxes and miss key emails. The value of mailboxes is to discuss issues and vote, not to synchronize information

It is recommended to keep the following message types:
github issue type:
     [Feature request]
     [Improvement request]
     [Report a security vulnerability]

Others:
     [VOTE]
     [DISCUSS]

what do you think?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good suggestion
