### ISSUE TITLE
[DSIP-17][Studio] Dolphinscheduler Studio, a debug platform.

### ISSUE THREAD

**Issue by Amy0104** [apache/dolphinscheduler#11673]
## Purpose

In order to debug the scripts in dolphinscheduler. 

## How

We're going to support this by a studio project which will be completed step by step. For the first step is to support three types of scripts, shell, sql and python. And we will support more types in the future.

### For the project

There are three modules in this project, and these three modules are File, Editor and Log. We will support setting module or other modules in the future. The UI of the entire project is shown in Design 1.

![the design of the entire project](https://user-images.githubusercontent.com/97265214/187017476-dd052c90-7b1e-474a-87bb-846e61cc51fb.png)

#### File module

In this module, you can create and delete a file or a folder, as well as filter files.  

For creating files or folders, we'll use the same way as Visual Code. The UI is shown in Design 2.

![the design of creating files or folders](https://user-images.githubusercontent.com/97265214/187017915-3f45faf9-27a4-4158-8ba2-f3f79622ef11.png)
##### Design 2: the design of creating files or folders.

There are the UIs of some special scenes shown in Design 3 and Design 4.

![the design of the project without any files.](https://user-images.githubusercontent.com/97265214/187017791-ce5b6599-78e8-42ed-9fcc-394f166ff3cd.png)

##### Design 3: the design of the project without any files.

![the design of the project without any opening files](https://user-images.githubusercontent.com/97265214/187017727-04971883-aa3f-44bc-8cb0-5ebb8d5a48b2.png)

#### Editor module

In this module, you can edit, save and run a file. The editor module can be separately in the browser.

#### Log module

In this module, you can check the log after the file has been run. The log module can be displayed separately in the browser as well as the editor module, and it also can be zoom in and out. The UI of the zoom in effect is shown in Design 5.

![the design of the zoom in effect](https://user-images.githubusercontent.com/97265214/187017613-da388ada-7dce-47e8-8758-67022dad68ff.png)

**Comment by EricGao888** [comment]
Hi @Amy0104, this design looks cool to me. May I ask how users could install this studio? If they have been using the DS 3.0.0, is there a way to plugin it into their existing DS deployment? Thanks!

**Comment by EricGao888** [comment]
BTW, will we have some features like `highlight`, `auto-complete` and `auto-formatting`? I think those are important especially for long SQL scripts.

**Comment by EricGao888** [comment]
In the future, we might have it combined with git features for task code review. related: #10387 cc @complone @xtr1993

**Comment by Amy0104** [comment]
We will support those features like `highlight`,`auto-complete` and `auto-formatting` by monaco-editor. Later we'll provide an example to tell users how to use it.

**Comment by Amy0104** [comment]
The repository of this issue is [here](https://github.com/apache/dolphinscheduler-studio) .

**Comment by simon824** [comment]
Hi, how is the progress of `dolphinscheduler-studio`, is there a release plan, can't wait to use it
