### ISSUE TITLE
[Feature][datasource-plugin]datasource jdbc common configuration

### ISSUE THREAD

**Issue by daodol** [apache/dolphinscheduler#11671]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

所有支持jdbc连接的数据源支持通用配置功能，url和driver手动填写，不需要ds后台去处理，这样可以支持更多的数据库，driver能上传那就更好了

### Use case

想支持更多可以基于JDBC去连接的数据库

### Related issues

无

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @daodol Please use English description, which can make more developer understand, thanks.

**Comment by caishunfeng** [comment]
Can you add the detail design or demo?

**Comment by daodol** [comment]
@caishunfeng hi,The data source connected by connection pool and JDBC can be designed to be fully dynamic The required parameters, such as URL, driver, username, password, connection pool size, timeout, time zone, etc., can be filled in instead of the fixed data source options that you provide to the user in the form of a data source plug-in
