### ISSUE TITLE
[Doc][Task Plugin] Put default task parameters in a new file

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#11687]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Currently we have the description for default task parameters in every task plugin, which is hard to maintain and could result in inconsistency. We may put it in one file for better maintainability.
* Besides, we could polish the description for default task parameters for better readability.
![image](https://user-images.githubusercontent.com/34905992/187121870-dbf9828a-b737-4258-87ac-59d1ba1d7331.png)

### Documentation Links

https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/task/shell.html

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@zhongjiajie WDYT?

**Comment by SbloodyS** [comment]
Tha's great. But I think there are several issues that need to be discussed. 

For example, not all task types use resource centers and have memory (CPU) limitations. What should we deal with it?

**Comment by EricGao888** [comment]
> Tha's great. But I think there are several issues that need to be discussed.
> 
> For example, not all task types use resource centers and have memory (CPU) limitations. What should we deal with it?

We could write it in the following way:

Here is a cheatsheet for default parameters of task plugins, each task plugin may have all or only ***SOME*** of those default parameters: blah blah blah blah

Then we put a link in each task plugin instruction doc to it.

**Comment by SbloodyS** [comment]
> > Tha's great. But I think there are several issues that need to be discussed.
> > For example, not all task types use resource centers and have memory (CPU) limitations. What should we deal with it?
> 
> We could write it in the following way:
> 
> Here is a cheatsheet for default parameters of task plugins, each task plugin may have all or only _**SOME**_ of those default parameters: blah blah blah blah
> 
> Then we put a link in each task plugin instruction doc to it.

+1 👍

**Comment by davidzollo** [comment]
+1
