### ISSUE TITLE
[Feature][DataSource] Add GuassDB Datasource

### ISSUE THREAD

**Issue by DarkAssassinator** [apache/dolphinscheduler#11684]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The current DS does not support the GuassDB database, could we add GuassDB plugin?

### Use case

Add GuassDB datasource plugin.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Do you have any investigation?

**Comment by DarkAssassinator** [comment]
It's just that many of our current businesses use this database. I will add this database on my products first, and if more guys need it later, I can submit it to DS.
