### ISSUE TITLE
[Feature][Style] Configure Spotless to format YAML file in DS 

### ISSUE THREAD

**Issue by jieguangzhou** [apache/dolphinscheduler#11699]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Configure Spotless to format YAML file code in DS.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@jieguangzhou Just for confirmation. Would you like to take this issue? Or you want me to do it? Thanks.

**Comment by jieguangzhou** [comment]
> @jieguangzhou Just for confirmation. Would you like to take this issue? Or you want me to do it? Thanks.

I just saw this message, I have submitted a PR #11700 , If possible, please help review

**Comment by caishunfeng** [comment]
Is this issue should be closed? @jieguangzhou @EricGao888
