### ISSUE TITLE
[Improvement][Standalone] Initialize a demo project in standalone

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#11717]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When I start DS in standalone mode, I hope there exists a demo project with some demo workflow, and I can directly run the demo workflow.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
related issue: #6586
