### ISSUE TITLE
[Improvement][email] email support i18n

### ISSUE THREAD

**Issue by user-GitHub-user** [apache/dolphinscheduler#11724]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

now email just support English

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
We have no plan to support translating emails to Chinese. If you want to communicate in Chinese, you could do it in `WeChat` group or `Slack` `users-china` channel. Thanks!
