### ISSUE TITLE
[Bug][Dependent][2.0.6-2.0.7] Dependent node logical conflict with task's startTime and scheduleTime

### ISSUE THREAD

**Issue by reele** [apache/dolphinscheduler#11725]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

https://github.com/apache/dolphinscheduler/blob/2746f6851d90cbdda04b6dc099847454ede09550/dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.xml#L174-L198

Now v2.0.6 and v2.0.7 dependent task changed to use `startTime` to find the target task directly above.
That changed the rules that how `dependent node` to find the task, dependent node still use `scheduleTime` to find, but use task's `startTime` to match `scheduleTime` will made some logical conflict, this can lead to some logic bugs, such as:

1. Run process in `complement` command with a different date, `taskInstance`.`startTime` will never match `scheduleTime`.

2. Run process in `complement` command with `a passed day`, dependent node will `always success` if there is a succeed task at `a passed day` with another `scheduleTime` which depended by dependent node.

3. Tasks that need to be performed continuously every day and not sensitive to date delays, when the task blocked until the next days, dependent node will never succeed, also the downstream processes will all need manual set `force success`, that's a big problem.

PR:#11677

### What you expected to happen

task_instance's date check in dependent task should use the same rule as process_instance.

### How to reproduce

blocked a task by preview tasks and started in after days, the dependent task will never succeed.
or run complement with future date.

### Version

2.0.6

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by KEN-LJQ** [comment]
Any progress about this issue, cause we facing same problem with version 2.0.7, kind of confuse

**Comment by reele** [comment]
> Any progress about this issue, cause we facing same problem with version 2.0.7, kind of confuse

2.0.6+ is more like a personal release, so my suggestion is create a own version to merge my repository.
