### ISSUE TITLE
[Bug] [spark-sql]  In spark-sql, select both SPARK1 and SPARK2 versions and execute ${SPARK_HOME2}/bin/spark-sql

### ISSUE THREAD

**Issue by limaiwang** [apache/dolphinscheduler#11720]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 In spark-sql, select both SPARK1 and SPARK2 versions and execute ${SPARK_HOME2}/bin/spark-sql

### What you expected to happen

In spark-sql, selecting SPARK1 should execute ${SPARK_HOME1}/bin/spark-sql and selecting SPARK2 should execute ${SPARK_HOME1}/bin/spark-sql

### How to reproduce

![spark_sql](https://user-images.githubusercontent.com/23052750/187668276-54092bbc-f4b7-4ea9-819d-f3cc682922b0.jpg)

[INFO] 2022-08-31 09:57:14.923 +0000 [taskAppId=TASK-20220831-6710611439552_3-40-44] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.spark.SparkTask:[69] - spark task params {"localParams":[],"rawScript":"SELECT * from ods.ods_pigeon_day LIMIT 1","resourceList":[],"programType":"SQL","mainClass":"","deployMode":"client","appName":"SparkSQLDemo","sparkVersion":"SPARK1","driverCores":1,"driverMemory":"512M","numExecutors":2,"executorMemory":"2G","executorCores":2}
[INFO] 2022-08-31 09:57:14.933 +0000 [taskAppId=TASK-20220831-6710611439552_3-40-44] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.spark.SparkTask:[240] - raw script : SELECT * from ods.ods_pigeon_day LIMIT 1
[INFO] 2022-08-31 09:57:14.934 +0000 [taskAppId=TASK-20220831-6710611439552_3-40-44] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.spark.SparkTask:[241] - task execute path : /tmp/dolphinscheduler/exec/process/6710440832960/6710611439552_3/40/44
[INFO] 2022-08-31 09:57:14.937 +0000 [taskAppId=TASK-20220831-6710611439552_3-40-44] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.spark.SparkTask:[130] - spark task command: ${SPARK_HOME2}/bin/spark-sql --master yarn --deploy-mode client --driver-cores 1 --driver-memory 512M --num-executors 2 --executor-cores 2 --executor-memory 2G --name SparkSQLDemo --queue haodf -f /tmp/dolphinscheduler/exec/process/6710440832960/6710611439552_3/40/44/40_44_node.sql
[INFO] 2022-08-31 09:57:14.937 +0000 [taskAppId=TASK-20220831-6710611439552_3-40-44] TaskLogLogger-class 

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @limaiwang What about using the env management?

**Comment by limaiwang** [comment]
> Hi @limaiwang What about using the env management?

Hi @caishunfeng  Are you trying to say that the spark-sql or spark-submit directories use the env mananget?
