### ISSUE TITLE
ds-1.3.6   duplicate tasks submit  to worker 

### ISSUE THREAD

**Issue by ruanbinbin** [apache/dolphinscheduler#11733]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/7637924/187859338-41195d37-f7bb-40f9-80d8-3d33be83e52b.png)

### What you expected to happen

ds的master节点向worker提交两次任务

### How to reproduce

2个master和两个worker
1、master.exec.task.num=20
2、单独工作流最多出现150任务同时运行
3、队列中存在未运行完的任务

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
Just a kindly reminder, version 1.3.6 is very old and no more under the maintenance of the community. We strongly suggest u upgrade it to v 3.0.0-stable

**Comment by davidzollo** [comment]
if you're using 1.3.x, you can try to find out if the 1.3.8 and 1.3.9 versions solve the problem, https://github.com/apache/dolphinscheduler/releases/tag/1.3.8   

as @EricGao888 said, 1.3.x is not maintained by the community, 2.0.6 or 3.0.0 will be better choice
