### ISSUE TITLE
[Feature][Dependent] Dependent support schedule all downstream recursively

### ISSUE THREAD

**Issue by stalary** [apache/dolphinscheduler#11736]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Dependent support schedule all downstream recursively.

a -> b -> c -> d
Currently only rerun b when I rerun a, I want to support rerun b,c,d

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
> a -> b -> c -> d
> Currently only rerun b when I rerun a, I want to support rerun b,c,d

Hi @stalary May I ask in this case, a b c d in ds are workflows or tasks?

**Comment by stalary** [comment]
> > a -> b -> c -> d
> > Currently only rerun b when I rerun a, I want to support rerun b,c,d
> 
> Hi @stalary May I ask in this case, a b c d in ds are workflows or tasks?

As workflows, Each of these contains multi tasks.

**Comment by caishunfeng** [comment]
Related issue: #8373

**Comment by caishunfeng** [comment]
> > > a -> b -> c -> d
> > > Currently only rerun b when I rerun a, I want to support rerun b,c,d
> > 
> > 
> > Hi @stalary May I ask in this case, a b c d in ds are workflows or tasks?
> 
> As workflows, Each of these contains multi tasks.

Look good to me if we can provide an optional option for the user to choose.

**Comment by stalary** [comment]
> Look good to me if we can provide an optional option for the user to choose.

At present, we need to go to task_params to find the dependent task, which cannot be queried in batches. Do i need to optimize the performance of this piece？Such as separate dependent task relation infomation into other table.

**Comment by caishunfeng** [comment]
> > Look good to me if we can provide an optional option for the user to choose.
> 
> At present, we need to go to task_params to find the dependent task, which cannot be queried in batches. Do i need to optimize the performance of this piece？Such as separate dependent task relation infomation into other table.

I think it would better to make an another issue to discuss, because it is an incompatible change, involving a lot of places, such as lineage relationship, import and export, etc.
