### ISSUE TITLE
Can you provide configuration documents for the integration of Hadoop and Flink tasks by the dolphin scheduler

### ISSUE THREAD

**Issue by XW512** [apache/dolphinscheduler#11738]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I'm a novice. At present, I want to schedule Flink tasks through the dolphin scheduler. After querying the data, I can't integrate the scheduling of Hadoop, Flink and other tasks. Can you provide a complete installation configuration document on the official website? Thank you

### Use case

not

### Related issues

not

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
We have detailed instructions on how to connect resource center to HDFS and how to use flink task plugin.
https://dolphinscheduler.apache.org/en-us/docs/dev/user_doc/guide/resource/configuration.html
https://dolphinscheduler.apache.org/en-us/docs/dev/user_doc/guide/task/flink.html
What docs do you need exactly?

**Comment by XW512** [comment]
> We have detailed instructions on how to connect resource center to HDFS and how to use flink task plugin. https://dolphinscheduler.apache.org/en-us/docs/dev/user_doc/guide/resource/configuration.html https://dolphinscheduler.apache.org/en-us/docs/dev/user_doc/guide/task/flink.html What docs do you need exactly?

thank you very much,I will try it

**Comment by EricGao888** [comment]
@XW512 I'm going to close this issue at this moment, if you have more questions when you try the instructions docs I posted above. Please feel free to reopen this issue. Thanks!
