### ISSUE TITLE
[Bug] [Dependent] For accounts other than admin, add dependent cannot discover the projects it created.

### ISSUE THREAD

**Issue by limaiwang** [apache/dolphinscheduler#11742]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

For accounts other than admin, add dependent cannot discover the projects it created.

### What you expected to happen

For accounts other than administrators, add dependent should discover the items it created.

### How to reproduce

The dev account created projects dev01 and dev02, and an admin-authorized test project. When adding Dependent to the dev02 project, only the test project can be found, not the dev01 project.
![dev_project](https://user-images.githubusercontent.com/23052750/188041786-40952b46-672a-4565-a8ef-5e440427bd33.jpg)
![dev_dep](https://user-images.githubusercontent.com/23052750/188042056-0e1716b8-d335-41fd-9a6f-79c99ef79f9c.jpg)

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
related issue: #11517

**Comment by caishunfeng** [comment]
> related issue: #11517

close due to same issue.
