### ISSUE TITLE
[Bug] [Module Name] Bug title 

### ISSUE THREAD

**Issue by huanhuande** [apache/dolphinscheduler#11744]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After the job flow is configured with timing management, there are many scheduling jobs that are configured to trigger, and some scheduling jobs are not triggered

### What you expected to happen

After the job flow is configured with timing management, there are many scheduling jobs that are configured to trigger, and some scheduling jobs are not triggered

### How to reproduce

After the job flow is configured with timing management, there are many scheduling jobs that are configured to trigger, and some scheduling jobs are not triggered

### Anything else

After the job flow is configured with timing management, there are many scheduling jobs that are configured to trigger, and some scheduling jobs are not triggered

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
please add detail info for title, thx      ` [Bug] [Module Name] Bug title ` is not clear

**Comment by caishunfeng** [comment]
Hi @huanhuande I will close this issue due to the unclear title and description.

Please use the correct title and add more details on description next time.
see https://dolphinscheduler.apache.org/en-us/docs/dev/user_doc/contribute/join/issue.html
