### ISSUE TITLE
[Bug] [Alert Server] send alert error alert data id

### ISSUE THREAD

**Issue by RUIzg** [apache/dolphinscheduler#11753]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when I want to test Email send when a task finish  , I get a error :

[INFO] 2022-09-02 08:00:11.268 +0000 org.apache.dolphinscheduler.alert.AlertRequestProcessor:[52] - Received command : AlertSendRequestCommand{groupId=0, title='sql_hive query result sets', content='[{"_c0":36816}]', warnType=1}
[ERROR] 2022-09-02 08:00:11.270 +0000 org.apache.dolphinscheduler.alert.AlertSenderService:[148] - Alert GroupId 0 send error : not found alert instance
[ERROR] 2022-09-02 08:00:14.699 +0000 org.apache.dolphinscheduler.alert.AlertSenderService:[244] - send alert error alert data id :57,
java.lang.NullPointerException: User must not be null
        at java.util.Objects.requireNonNull(Objects.java:228)
        at org.apache.dolphinscheduler.plugin.alert.email.MailSender.<init>(MailSender.java:109)
        at org.apache.dolphinscheduler.plugin.alert.email.EmailAlertChannel.process(EmailAlertChannel.java:41)
        at org.apache.dolphinscheduler.alert.AlertSenderService.alertResultHandler(AlertSenderService.java:232)
        at org.apache.dolphinscheduler.alert.AlertSenderService.send(AlertSenderService.java:105)
        at org.apache.dolphinscheduler.alert.AlertSenderService.run(AlertSenderService.java:76)
[INFO] 2022-09-02 08:00:14.699 +0000 org.apache.dolphinscheduler.alert.AlertSenderService:[255] - Alert Plugin Email-Alert send error : User must not be null

### What you expected to happen

I should got a Email when a task finish 

### How to reproduce

create a Email group  ,  smtp   then I create a test task ,  run It  with a Email group ,then will get the same error 

### Anything else

dolphin 3.0 pseudo-cluster  install 

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
may can check `t_ds_alert_plugin_instance` table

**Comment by fuchanghai** [comment]
may can check ```t_ds_alertgroup``` , can you see the record which id equals 0?

**Comment by fuchanghai** [comment]
@Amy 
first , in class of ProcessDefinition . the type of warningGroupId is int .so when search ProcessDefinition ，The default value of warningGroupId is returned as 0.
<img width="633" alt="image" src="https://user-images.githubusercontent.com/33984497/188262619-d9f2fdc1-3eeb-4477-b947-24119986a72f.png">

second , If you call the interface that starts the process instance，The default value of warningGroupId is returned as 0
<img width="996" alt="image" src="https://user-images.githubusercontent.com/33984497/188262781-516dbc30-5f45-4827-9834-aa39cd7c0db2.png">
finally , there are not record which id equals 0 in table of ```t_ds_alertgroup```

**Comment by fuchanghai** [comment]
@Amy0104  i will fix it ,can you assignees me?
