### ISSUE TITLE
[Improvement][Monitor] Support monitor h2 database in monitor page

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#11768]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Right now, we only support monitor mysql/pgsql in monitor page, when we start at standalone mode, we cannot get the db health in monitor page, it's better to support h2.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
I'm interested in this part, can i assign this case?

**Comment by DarkAssassinator** [comment]
Dear @ruanwenjun there is a small question, H2 memory database does not have indicators such as the maximum number of connections, just session numbers. do we need check the JDBC connection pool?

**Comment by ruanwenjun** [comment]
> Dear @ruanwenjun there is a small question, H2 memory database does not have indicators such as the maximum number of connections, just session numbers. do we need check the JDBC connection pool?

Yes, we can query the session number to represent the connection number.
```
select * from information_schema.sessions;
```

**Comment by DarkAssassinator** [comment]
yes, but cannot determine the MAX_CONNECTION, becasue H2 do not have this setting. so we just can check the cur active connection number.
