### ISSUE TITLE
[Bug] [Workflow] Workflow failure strategy does not work as expected

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#11781]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

* Failure strategy `continue` does not work for serial tasks. Although the doc doesn't say it could work for serial tasks, it should work for it instead of only for parallel tasks.
* In many scenarios, we need a `clean-up` task at the end of a workflow. Without failure strategy working as expected, we could never achieve this.
* This bug exists in both `3.0.0-release` and `dev`.
![image](https://user-images.githubusercontent.com/34905992/188475648-d4bb56e7-6cff-46a8-baa7-f349b17823ae.png)
![image](https://user-images.githubusercontent.com/34905992/188783182-bea38081-6e0d-45bc-b397-b0e9740384c0.png)

### What you expected to happen

* Failure strategy `continue` is supposed to work for all kinds of workflows.
* We need to fix the bug and change the docs.

### How to reproduce

* Already described above.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
@EricGao888 so this issue should update as improvement?

**Comment by EricGao888** [comment]
> @EricGao888 so this issue should update as improvement?

I think so. I will give a design and send it to mail list later.

**Comment by EricGao888** [comment]
WIP, no stale
