### ISSUE TITLE
[Improvement] [dolphinscheduler-ui] The axios timeout time of 15s is too short, and uploading large files will trigger nginx 400

### ISSUE THREAD

**Issue by 8431** [apache/dolphinscheduler#11785]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The axios timeout time of 15s is too short, and uploading large files will trigger nginx 400
![Screenshot2022_09_06_105936](https://user-images.githubusercontent.com/22486827/188537900-fbfae5ff-97b9-48f1-9518-dcc0f9544a5e.jpg)
![Screenshot2022_09_06_110020](https://user-images.githubusercontent.com/22486827/188537991-30df7bdf-d165-4f75-a9fc-31dadaae57d3.jpg)

### What you expected to happen

When uploading files, set the API timeout time for uploading files to be longer.

### How to reproduce

Uploading a relatively large file will take more than 15s to 400

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I think we should make this configurable and provide it to the user for configuration instead of unlimited increase. cc @songjianet @devosend

**Comment by SbloodyS** [comment]
Duplicated with #11694.

**Comment by LiJie20190102** [comment]
It seems that I have encountered the same problem. When there are a large number of taskInstances (for example, 1715952 records), the interface request will report an error. Is this the same question? If yes, can this time parameter be changed to configurable。
![image](https://user-images.githubusercontent.com/53458004/208600155-03d51804-f9b3-4bec-9cbb-4c47faf191b8.png)
