### ISSUE TITLE
[Bug] [Workflow Relationship] The workflow relationship is not color-marked correctly for the upline status

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#11786]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/188541293-88bf2301-93dc-4791-b87c-7a5d64adb60e.png)

### What you expected to happen

The go-live is marked in blue

### How to reproduce

1. Enter the workflow relationship page; 
2. View the workflow relationship of the online status

### Version

dev: ds3.1.0-prepare

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
This workflow is online, while its scheduling state is offline. So the node shows the color of scheduling offline.

**Comment by welsh-wen** [comment]
Thanks for the reminder, I closed this issue right away
