### ISSUE TITLE
[Bug] [ApiServer] Workflow definition page batch deletion of "online" status workflow, prompt suggestions for optimization

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#11788]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/191763800-8dd835b2-e2c8-4d22-8d97-a3c0ca7a6d84.png)
![image](https://user-images.githubusercontent.com/59044203/191763243-d5366cc6-5473-4659-b342-1868b62f8d9b.png)

### What you expected to happen

Optimization tips

### How to reproduce

1. Online workflow; 
2. Batch deletion workflow

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
@SbloodyS  i wil fix it

**Comment by SbloodyS** [comment]
> @SbloodyS i wil fix it

Great! Already assigned to you.

**Comment by fuchanghai** [comment]
@welsh-wen Although I have added a judgment on the online status, I don't think the above issue can be fixed, because it is necessary to judge whether it exists before it can judge whether the status is online. My initial suspicion is that he deletes the process definition after someone else has already deleted it。can you give me more informations?

**Comment by fuchanghai** [comment]
@SbloodyS If the process definition is online, can it still be selected and deleted in the front end?

**Comment by welsh-wen** [comment]
@caishunfeng Can you help to solve the same type of prompt problem in the commercial version before?

https://github.com/WhaleOps/dolphinscheduler/pull/99
