### ISSUE TITLE
[Bug] [UI] Workflow definition page text overlaps

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#11787]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/188541654-39c6f98b-a7ad-447a-89f4-aa8ec8d265cc.png)

### What you expected to happen

The copy shows normal

### How to reproduce

Go to the workflow definition

### Version

[dev](dev: ds3.1.0-prepare)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
