### ISSUE TITLE
[Bug] [Mysql_init Script] The mysql init script is not available

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#11784]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. Refer to the official documentation
2. sh /opt/release/0906_ds/tools/bin/upgrade-schema.sh
3. An error occurred

![image](https://user-images.githubusercontent.com/59044203/188533688-562240a5-07e6-446d-a7ff-9ccf7a42a70b.png)
![image](https://user-images.githubusercontent.com/59044203/188533499-ce69deb8-9581-4784-9b61-d06d4d908a99.png)

### What you expected to happen

The init script works fine

### How to reproduce

1. Refer to the official documentation
2. sh /opt/release/0906_ds/tools/bin/upgrade-schema.sh
3. An error occurred

### Version

dev: ds3.1.0-prepare

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
@SbloodyS  i will fix it

**Comment by SbloodyS** [comment]
> @SbloodyS i will fix it

I've assigned to you.
