### ISSUE TITLE
[Bug] [Alert] The Alarm Failure policy does not trigger sending an alarm

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#11799]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/188573969-55245821-cf9b-485a-b6cc-853d32e5aded.png)
![image](https://user-images.githubusercontent.com/59044203/188574288-7cb20a2a-53c9-4c2e-aee0-711f9ac103f8.png)

### What you expected to happen

Timeout failures can trigger an alarm

### How to reproduce

1. Configure timeout failure alarms 
2. Check whether the alert table is logged

### Version

[dev](dev: ds3.1.0-prepare)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
@SbloodyS @welsh-wen  first , Have you configured an alert group? second , is duplicate with  #11751  ?

**Comment by EricGao888** [comment]
> @SbloodyS @welsh-wen first , Have you configured an alert group? second , is duplicate with #11751 ?

Not actually. #11751 targets the implementation of parameter passing across tasks. See `Pass Parameter From Upstream Task to Downstream` section: https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/parameter/context.html

**Comment by EricGao888** [comment]
@welsh-wen Could you please provide a screenshot of how your set the alert for your workflow? As well as the log of your alert server. Thanks : )
