### ISSUE TITLE
[Bug] [Workflow] After the workflow is deleted, the corresponding task should also be deleted

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#11791]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/188546799-fd27934f-209f-4d37-9496-b64bf753b3a0.png)
![image](https://user-images.githubusercontent.com/59044203/188546980-cafa43f4-2b3f-47e2-ad49-f91d5e39a3e9.png)
![image](https://user-images.githubusercontent.com/59044203/188546844-eccf3414-a5fd-4ddb-95b6-860114010ada.png)
![image](https://user-images.githubusercontent.com/59044203/188546901-bc52101c-56e2-44b9-80bc-b12802af8eff.png)

### What you expected to happen

After the workflow is deleted, the corresponding task should also be deleted

### How to reproduce

1. Create a workflow shell; 
2. Create task 123
3. Delete the shell

### Version

[dev](dev: ds3.1.0-prepare)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Dupliated with #9029
