### ISSUE TITLE
[Bug] [Log] The log time should be synchronized with the natural day time

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#11790]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/188544646-4bb91fce-8384-4713-b5e7-4e5179c19594.png)

### What you expected to happen

The log time should be synchronized with the natural day time

### How to reproduce

1. View the background log
2. Compare the natural day time

### Version

[dev](dev: ds3.1.0-prepare)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
because default time zone is UTC. u can change it by refer to doc FAQ General Setting

**Comment by caishunfeng** [comment]
> because default time zone is UTC. u can change it by refer to doc FAQ General Setting

Yes, user can change the config when deploy.
