### ISSUE TITLE
[Bug] [WorkFlow] The failed retry configuration does not take effect

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#11797]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/188563534-714005b6-9731-45de-b74f-eca4851a9f8d.png)
![image](https://user-images.githubusercontent.com/59044203/188564206-061f1245-d701-4640-a519-6ecd8f9c8c1e.png)

### What you expected to happen

The configuration takes effect

### How to reproduce

1.Create a shell workflow 
2.Configure the failure policy
3.Run the workflow and wait for it to fail 
4.Observe if it retries

### Version

[dev](dev: ds3.1.0-prepare)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Duplicated with #11790
