### ISSUE TITLE
[Bug] [Worker]  Before deleting a worker group, check whether there are other resources that reference the worker group

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#11805]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/188588906-50f7f868-c28f-4744-9e21-187978c5eb9d.png)
![image](https://user-images.githubusercontent.com/59044203/188589665-c548d629-1741-493b-a65c-996dcbca7cf2.png)

### What you expected to happen

Before deleting a worker group, check whether there are other resources that reference the worker group

### How to reproduce

1. Create a worker group 
2. Workflow reference worker group 
3. Delete the worker group

### Version

[dev](dev: ds3.1.0-prepare)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by seedscoder** [comment]
I am interested in this issue. I see that t_ ds_ task_ definition. worker_ group stores the name of the worker group. If the worker group modifies the name, The relevant information in definition will not change. Is it better to use ID? This involves the change of front-end input parameters

**Comment by seedscoder** [comment]
Current, t_ds_task_definition.worker_group stores the name of the worker group 
- the name of the worker group will not be modified synchronously. Is it inaccurate to directly verify the name of the worker group?
-  if the worker group ID is stored，How to handle the work group value of historical data

@SbloodyS

**Comment by hstdream** [comment]
[Bug] [API]After we delete the worker group, but this task group still keep in the task setting. #12207
