### ISSUE TITLE
[Bug] [Permission] Resource permissions cannot be authorized

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#11803]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/188585191-7d7ccd3b-e8bc-4cad-bcc3-a86849615446.png)

### What you expected to happen

Resource permissions are available

### How to reproduce

1. Enter the user management page 
2. Select the user for authorization
3. Select the resource permission

### Version

[dev](dev: ds3.1.0-prepare)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
![image](https://user-images.githubusercontent.com/20518339/189527225-5afe147a-431d-464b-9bac-60b2e8bf5799.png)
![image](https://user-images.githubusercontent.com/20518339/189527258-fe32cea0-fb57-4841-9e99-d5fb4f645154.png)

**Comment by zhuangchong** [comment]
repaired pr: #12467

**Comment by zhuangchong** [comment]
done.
