### ISSUE TITLE
[Bug] [UserManager] After you create a user, you can't modify the password again

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#11801]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened
![image](https://user-images.githubusercontent.com/59044203/188583831-30aa01db-0a61-473d-83e1-037ff8955d41.png)

![image](https://user-images.githubusercontent.com/59044203/188583999-b34e0348-c74c-489f-9a64-8179306016ff.png)

### What you expected to happen

It is recommended that you can change the password when editing a user

### How to reproduce

1. Create a user
2. Edit user
3. Try to change the user password

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
You can modify it in password instead of account.

**Comment by caishunfeng** [comment]
Maybe it's not a bug.

**Comment by QJG666** [comment]
> You can modify it in password instead of account.

So, what version are you using that I can't change when I'm using version 3.0.0
