### ISSUE TITLE
ui, cannot select the workload scheduling time Front end, timing cannot be selected

### ISSUE THREAD

**Issue by SunFenging** [apache/dolphinscheduler#11820]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened
When using Pseudo-Cluster mode of version 3.0,cannot select the workload scheduling time Front end, timing cannot be selected ,but this problem does not occur in Standalone mode of version 3.0.
This is the screen recording information of the abnormal situation:
https://user-images.githubusercontent.com/39881066/188785397-e956a821-fb20-459b-bc62-f2d6c5cd24d4.mp4

### What you expected to happen

none

### How to reproduce

none

### Anything else

The installation package is obtained from the official website:
https://www.apache.org/dyn/closer.lua/dolphinscheduler/3.0.0/apache-dolphinscheduler-3.0.0-bin.tar.gz
 computer system version：Windows 10
Google browser version： 104.0.5112.81
A similar bug has been raised before https://github.com/apache/dolphinscheduler/pull/9762

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please use english to describe for others to understand.

**Comment by SunFenging** [comment]
ok,thank u




孙峰然
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月7日(星期三) 下午2:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] ui, cannot select the workload scheduling time Front end, timing cannot be selected (Issue #11820)





 
Please use english to describe for others to understand.
