### ISSUE TITLE
task definition reference deleted resource files

### ISSUE THREAD

**Issue by hushubudu** [apache/dolphinscheduler#11827]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1、Create a process  definiiton（flow001)  and add a shell task. The shell task references two rosource files (file1.sql and file2.sql）
2、Make flow001 offline 
3、From resource center, delete file1.sql
4、 Make flow001 online again
5、 The flow001 can not be scheduled  normally

### What you expected to happen

After delete file1.sql, I expected the flow001 can be scheduled normally

### How to reproduce

1、Create a process  definiiton（flow001)  and add a shell task. The shell task references two rosource files (file1.sql and file2.sql）
2、Make flow001 offline 
3、From resource center, delete file1.sql
4、 Make flow001 online again
5、 The flow001 can not be scheduled 

### Anything else

The resouce center reupload file is a very useful function . I suggest this function can be added back again

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hushubudu** [comment]
After delete file01.sql， from the process definition page, the referenced file01.sql disappear
![image](https://user-images.githubusercontent.com/112859809/188817370-6a1e42af-860d-4f34-b1d0-1c3f79c4c256.png)

However, in table t_ds_task_definition, the referenced file id still remain
![image](https://user-images.githubusercontent.com/112859809/188817710-29d18ae3-7028-476e-9597-968e9c0cd9a4.png)

**Comment by hushubudu** [comment]
> Thank you for your feedback, we have received your issue, Please wait patiently for a reply.
> 
> * In order for us to understand your request as soon as possible, please provide detailed information、version or pictures.
> * If you haven't received a reply for a long time, you can [join our slack](https://s.apache.org/dolphinscheduler-slack) and send your question to channel `#troubleshooting`

The version is 3.0.0 
Pictures are already uploaded.
Thanks

**Comment by DarkAssassinator** [comment]
so just need remove the resource from the task_param and resource_ids?

**Comment by hushubudu** [comment]
yes, if a file is deleted all the task definitions should remove the resource from the task_param and resource_ids automatically

**Comment by DarkAssassinator** [comment]
> yes, if a file is deleted all the task definitions should remove the resource from the task_param and resource_ids automatical

i think that we can delete all related resource when the user delete the resources.
@SbloodyS could i get this case?

**Comment by hushubudu** [comment]
Still, I think the reupload resource file is a very import function .Will you consider adding back this function?

**Comment by hstdream** [comment]
I think that when deleting the file resource, it should be judged whether the file is referenced or not

**Comment by caishunfeng** [comment]
> I think that when deleting the file resource, it should be judged whether the file is referenced or not

+1, agree with @hstdream

**Comment by SbloodyS** [comment]
> I think that when deleting the file resource, it should be judged whether the file is referenced or not

+1

**Comment by SbloodyS** [comment]
> > yes, if a file is deleted all the task definitions should remove the resource from the task_param and resource_ids automatical
> 
> i think that we can delete all related resource when the user delete the resources. @SbloodyS could i get this case?

Sure.

**Comment by hstdream** [comment]
I will try to submit pr.  @caishunfeng @SbloodyS

**Comment by caishunfeng** [comment]
> I will try to submit pr. @caishunfeng @SbloodyS

Hi @DarkAssassinator do you work for this issue? If no, I will change the assignee.

**Comment by DarkAssassinator** [comment]
> > I will try to submit pr. @caishunfeng @SbloodyS
> 
> Hi @DarkAssassinator do you work for this issue? If no, I will change the assignee.

hi @caishunfeng, just @hstdream comment that he will submit PR, please assign to him, thx

**Comment by ruanwenjun** [comment]
> I think that when deleting the file resource, it should be judged whether the file is referenced or not

In fact, if you want to do this check, you need to scan all version workflow definitions, we don't need to do this check when there are Concurrent operations, this check is not safe.

**Comment by zhongjiajie** [comment]
> > I think that when deleting the file resource, it should be judged whether the file is referenced or not
> 
> In fact, if you want to do this check, you need to scan all version workflow definitions, we don't need to do this check when there are Concurrent operations, this check is not safe.

close due to this
