### ISSUE TITLE
[Bug] [service] save warningGroupId which not exist 

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#11824]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/33984497/188799349-aae3e3b0-6922-45b9-8f68-e52d4894c170.png)
- when i  init database ,not find init a alertGroup which id equal 1
- According to codes logic if warningGroup equal null, we will send message to alertGroup which id equal 1.  id equal to 1 may not exist

### What you expected to happen

i want to disscussion above question

### How to reproduce

ATT

### Anything else

@ruanwenjun i want you help,If you are sure that there is a problem with the above code, I will modify it

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
@ruanwenjun i want you help,If you are sure that there is a problem with the above code, I will modify it

**Comment by SbloodyS** [comment]
The `id=1` exists only after the user manually creates the alarm plugin. If the user does not create it, there will be no sending channel to send alarm information.

**Comment by ruanwenjun** [comment]
> The `id=1` exists only after the user manually creates the alarm plugin. If the user does not create it, there will be no sending channel to send alarm information.

In my knowledge, we don't need to set the alertGroupId here? we can keep it null?

**Comment by fuchanghai** [comment]
@ruanwenjun @SbloodyS if id not exists.The log will report an error，you can see #11753

**Comment by fuchanghai** [comment]
> > The `id=1` exists only after the user manually creates the alarm plugin. If the user does not create it, there will be no sending channel to send alarm information.
> 
> In my knowledge, we don't need to set the alertGroupId here? we can keep it null?

yes. if alertGroupId is null，this pr #11774 while pledge  that alert information don't need insert
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/33984497/195485482-29092741-44a2-4cac-aa78-ff0f0acfdac3.png">
