### ISSUE TITLE
dolphinscheduler-daemon.sh does not take effect

### ISSUE THREAD

**Issue by hushubudu** [apache/dolphinscheduler#11841]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1) start worker-server on a node
2) on the same node ,run "sh dolphinscheduler-daemon.sh status api-server ", get the wrong result
![image](https://user-images.githubusercontent.com/112859809/189015561-02f98de5-65bd-4d6f-969d-947df4c6950d.png)

### What you expected to happen

when run "sh dolphinscheduler-daemon.sh status api-server ", the result should be "api-server is not running"

### How to reproduce

1) start worker-server on a node
2) on the same node ,run "sh dolphinscheduler-daemon.sh status api-server ", get the wrong result

### Anything else

I find the "CLASS" variable in dolphinscheduler-daemon.sh  is not assigned the corrent value when running then shell script. CLASS is always null

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This has been fixed in #11580. Will be released in the 3.0.1-release.
