### ISSUE TITLE
[Feature] [UI] About the redesign of the homepage

### ISSUE THREAD

**Issue by jiangtaoNuc** [apache/dolphinscheduler#11849]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The indicators on the home page should be instructive in the operation and maintenance operation.(首页的指标要在运维操作中有一定的指导性)

### Use case

This part needs in-depth discussion and redesign. Different roles care about different dimension indicators.
1. Number of projects, number of online workflows/number of offline workflows, number of tasks to be scheduled/number of tasks that have been successfully scheduled
2. Count the number of task successes, failures, stops, and other statuses by hour (the statuses need to be combined into a design)
3. Statistics of running failures (by workflow dimension, count the number of times the schedule fails to execute on the date)
4. Running time statistics (according to the workflow dimension, the average duration of scheduled execution on a statistical date)
5. CPU, memory, load, number of tasks executed by sub-workers, etc. that the operation and maintenance personnel care about

这部分需要深入讨论和重新设计下，不同的角色关心不同的维度指标。
1. 项目数、上线的工作流数/ 下线的工作流数、应调度任务数/已经成功调度任务数
2. 分小时统计任务成功、失败、停止、和其他状态的数量（需要把状态做一个合并设计）
3. 运行失败的统计 （按工作流维度，统计日期调度执行失败的次数）
4. 运行时长统计（按工作流维度，统计日期调度执行的平均时长）
5. 运维人员关心的cpu、内存、负载、分worker执行任务数等

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jiangtaoNuc** [comment]
![image](https://user-images.githubusercontent.com/31644893/189041162-90373116-fdeb-4f79-abdb-e6ca599f711f.png)

**Comment by jiangtaoNuc** [comment]
![image](https://user-images.githubusercontent.com/31644893/189041235-3aeb8ea4-f7c8-4c24-8422-58b5b9de9795.png)

**Comment by caishunfeng** [comment]
> ![image](https://user-images.githubusercontent.com/31644893/189041235-3aeb8ea4-f7c8-4c24-8422-58b5b9de9795.png)

Looks cool!

**Comment by pandong2011** [comment]
when do this, if do , can give this pr to me？define the metrics and dimensions first
