### ISSUE TITLE
[Feature][User Experience] Workflows go online and offline quickly

### ISSUE THREAD

**Issue by jiangtaoNuc** [apache/dolphinscheduler#11844]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We use version 2.0.2，When I open an online workflow, I need to make some adjustments. I need to close the workflow canvas, click offline, and then I can edit it, which is very inconvenient。
当我打开一个已经上线的工作流，我需要做一些调整，需要关闭工作流画布，点击下线，然后才能编辑，这十分的不方便。

### Use case

We want to display an offline button when we open the canvas, click the offline button, and then we can operate the workflow。This adjustment is very simple, just add a button on the front end and call the existing offline interface.
我们希望在打开画布的时候，展示一个下线的按钮，点击下线，然后就可以操作工作流。这个调整非常简单，前端加个按钮，调用已经存在的下线接口就好了。
![image](https://user-images.githubusercontent.com/31644893/189035505-349a04bf-2b51-4075-95fc-daff34c86794.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hdygxsj** [comment]
@SbloodyS  It seems that this function has not been added yet, and I found that the download workflow picture button on the workflow definition page and the offline button on the workflow list page use the same icon, whether it needs to be adjusted,  I'd be willing to commit a pr to close this issue 
![5d77c44715b253ec7ef26fa01b5b98b](https://user-images.githubusercontent.com/35210666/202460845-a22fead4-eeb2-4aea-b84e-36193e87389f.png)
![c27349de4cbc9082324504ee949d943](https://user-images.githubusercontent.com/35210666/202460852-10971a2c-9fdf-47a2-8298-b1edd6afaef8.png)
