### ISSUE TITLE
[Improvement][Unit Test] Fix flaky unit test in org.apache.dolphinscheduler.plugin.alert.http.HttpSenderTest

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#11856]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

https://github.com/apache/dolphinscheduler/runs/8226755468?check_suite_focus=true

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
We need to decouple the external system in UT, e.g. connection to ''www.baidu.com'' here:
https://github.com/apache/dolphinscheduler/blob/e101a5cb2c1a273eb4f2b29230c769f69f698148/dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/test/java/org/apache/dolphinscheduler/plugin/alert/http/HttpSenderTest.java#L30-L41

**Comment by SbloodyS** [comment]
> We need to decouple the external system in UT, e.g. connection to ''www.baidu.com'' here:
> 
> https://github.com/apache/dolphinscheduler/blob/e101a5cb2c1a273eb4f2b29230c769f69f698148/dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/test/java/org/apache/dolphinscheduler/plugin/alert/http/HttpSenderTest.java#L30-L41

That's right.

**Comment by huahuacheng** [comment]
I'm interested. May I take this one? QAQ

**Comment by SbloodyS** [comment]
> I'm interested. May I take this one? QAQ

Sure. I've assigned to you. Looking forward to your contribution.

**Comment by EricGao888** [comment]
> > I'm interested. May I take this one? QAQ
> 
> Sure. I've assigned to you. Looking forward to your contribution.

`+ 1`

**Comment by EricGao888** [comment]
closed by: #12017
