### ISSUE TITLE
[Improvement][Dao] Optimize table fields using SQL keywords

### ISSUE THREAD

**Issue by zhuangchong** [apache/dolphinscheduler#11867]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The database table fields of DolphinScheduler contain many SQL keywords. Normally, the field name is forbidden to use keywords. This is also clearly specified on the official website of the database. 
https://www.postgresql.org/docs/9.6/sql-keywords-appendix.html#KEYWORDS-TABLE

At present, the DolphinScheduler system can use this field and need to add quotation marks, such as `type` , I suggest that we can optimize these and make DolphinScheduler more standard and standardized.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ROTBOR** [comment]
Is it correct way to replace keywords table fields used

**Comment by yakami129** [comment]
I'm at your service.

**Comment by forrest1g** [comment]
This looks fine and not necessary to change.
