### ISSUE TITLE
[Improvement] [dolphinscheduler-tools] upgrade process can be made directly after init process

### ISSUE THREAD

**Issue by wendongdi** [apache/dolphinscheduler#11876]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

i think the runner function can be optimized:
upgrade process can be made directly after init process:
```JAVA
        @Override
        public void run(String... args) throws Exception {
            if (!dolphinSchedulerManager.schemaIsInitialized()) {
                dolphinSchedulerManager.initDolphinScheduler();
                logger.info("init DolphinScheduler finished");
            }
            dolphinSchedulerManager.upgradeDolphinScheduler();
            logger.info("upgrade DolphinScheduler finished");
        }
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Can you give an example?

**Comment by wendongdi** [comment]
> Can you give an example?

In current UpgradeDolphinScheduler code：
```JAVA
        @Override
        public void run(String... args) throws Exception {
            if (dolphinSchedulerManager.schemaIsInitialized()) {
                dolphinSchedulerManager.upgradeDolphinScheduler();
                logger.info("upgrade DolphinScheduler finished");
            } else {
                dolphinSchedulerManager.initDolphinScheduler();
                logger.info("init DolphinScheduler finished");
            }
        }
```
it has been judged whether the schema has been initialized. If not, it will be initialized, but it will not upgrade after that. I don't think this is reasonable.
The initDolphinScheduler function only update the schema to version 3.0.0（not the latest version），so i have to run this function again to upgrade the schema.

I don't understand why not init&update to the latest version all at once？
