### ISSUE TITLE
[Bug] [dolphinscheduler-tools] [mysql] bugs are thrown when init&upgrade meta-schema

### ISSUE THREAD

**Issue by wendongdi** [apache/dolphinscheduler#11875]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

exceptions is thrown while running UpgradeDolphinScheduler with profle 'upgrade':
- Duplicate key exceptions are thrown when upgrading mysql-meta-data by executing ver. 2.0.3~ver. 2.0.4 dolphinscheduler_ddl.sql
,like this:
![图片](https://user-images.githubusercontent.com/49931055/189272645-cd628602-738c-4e6b-98f8-72f081255031.png)

- An exception occurred while dropping an index that does not exist by executing ver. 3.1.0 dolphinscheduler_ddl.sql 
![图片](https://user-images.githubusercontent.com/49931055/189273321-86f12dfc-9ff2-48a3-a08c-83ab228c9fe8.png)

- Duplicate column exceptions are thrown when upgrading mysql-meta-data by executing ver. 3.1.1 dolphinscheduler_ddl.sql
,such as :
![图片](https://user-images.githubusercontent.com/49931055/189273593-7bea2180-3c70-4f87-944f-902218cef518.png)

### What you expected to happen

I think the upgrade process is important and shouldn't have any exceptions, and appended upgrade processes must take into account the case of duplicates of indexes or columns or tables

### How to reproduce

I recommend defining mysql procedures to determine whether an index or column already exists, and if it exists, delete it and then create a new one;

then exception dropping an index that does not exist occurs because of a sql logic error and easy to fix it;
![图片](https://user-images.githubusercontent.com/49931055/189274463-b8dd4159-bcb2-4023-87fc-1a792aa4ab80.png)

### Anything else

I recommend that subsequent versions of the mysql sql script also need to avoid these exceptions

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
>I think the upgrade process is important and shouldn't have any exceptions, and appended upgrade processes must take into account the case of duplicates of indexes or columns or tables

Yes, agree with you.
