### ISSUE TITLE
[Improvement][All Modules] Keyword Search Improvement

### ISSUE THREAD

**Issue by Chris-playground** [apache/dolphinscheduler#11879]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

For DolphinScheduler V3.0.0, all the search actions can only  be triggered by pressing the search button in project list page, process list page and etc.
Mostly, users will press `Enter` after they finish typing the things they want to search, it is not user-friendly to press the search button again by hand.
Therefore, maybe it's better to allow `Enter` to trigger the search action.
![image](https://user-images.githubusercontent.com/48941586/189871907-5e54084b-2925-4658-9c27-fd8ddff7b35e.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
@SbloodyS  @Amy0104  I'm interested this issue

**Comment by pinkfloyds** [comment]
I hope all search boxes can use the Enter key to submit requests, providing a better experience
