### ISSUE TITLE
[Feature][ALL Modules] The feeling after use dolphin scheduler3.0 

### ISSUE THREAD

**Issue by Yougetadad** [apache/dolphinscheduler#11883]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1、建议“工作流定义”页面调整创建时间、更新时间、创建&修改用户等列的宽度，给任务名等留足空间
2、建议操作按钮出可以调整一下色系，目前看着清朗却不清晰
3、在界面进行上线或定时上线调整等功能后不要直接返回初始页面
4、环境名称在手动调度的时候可以默认,避免每次都要点选
5、保存界面中：串行抛弃和串行优先不能顺利执行
6、手动调度的时候单独执行本节点的功能建议回归
7、时区调整并不是全局的，参数没有跟着调整

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please use english to describe for others to understand.
