### ISSUE TITLE
[Bug] [UI] allow-input check on some input element are unnecessary

### ISSUE THREAD

**Issue by LiuBodong** [apache/dolphinscheduler#11884]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

User could not type `WHITESPACE` into `environment config` and password.

## Why this happends
`allow-input` attribute was added to NInput tag element in this issue #10845. and was merged by #10984 and #10975.
This causes some `textarea` and `password ` input element could not add whitespace at the end of content. But normally, users are able to add whitespace to those content.

## What should we do
In my opinion, we should remove those verification on textaera and password element.

### What you expected to happen

User can write what they want into textarea and password

#### TextArea
* Start api service and ui
* Click security -> environment manage
* Click `add environment ` button and type `export JAVA_HOME=xxx` into the `Environment Config` slot

then you will see that you cant type ` ` (whitespace) after `export`

#### Password
* Click Security -> User Manage
* Click `Add User` button
* Type ` `(whitespace) into password field, 

You can't type whitespace into password

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
I don't think it's a bug and we should not make the input element allow whitespace at the end of content.

PTAL @Amy0104 @songjianet

**Comment by Amy0104** [comment]
I think so. This's not a bug. Removing whitespace from both ends of a string is to prevent user misuse.

**Comment by LiuBodong** [comment]
I'm not meaning to remove `all` the verification on input, But I think some  unnecessary verification could be removed.
For example: `Envrionment Config`, the verification prevent typing such shell command: `export JAVA_HOME=/usr/lib/jvm/default`.

By the way, should `password` contains whitespace?
