### ISSUE TITLE
[Improvement][dolphinscheduler-api] When deleting a workflow definition, the task definition information should be deleted?

### ISSUE THREAD

**Issue by seedscoder** [apache/dolphinscheduler#11895]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- When deleting a workflow definition (t_ds_process_definition), whether the task definition information should be deleted (physical deletion or logical deletion) (t_ds_task_definition)

```java
        int delete = processDefinitionMapper.deleteById(processDefinition.getId());
        if (delete == 0) {
            putMsg(result, Status.DELETE_PROCESS_DEFINE_BY_CODE_ERROR);
            throw new ServiceException(Status.DELETE_PROCESS_DEFINE_BY_CODE_ERROR);
        }
        int deleteRelation = processTaskRelationMapper.deleteByCode(project.getCode(), processDefinition.getCode());
        if (deleteRelation == 0) {
            logger.warn("The process definition has not relation, it will be delete successfully");
        }
        deleteOtherRelation(project, result, processDefinition);
```

#

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
https://github.com/apache/dolphinscheduler/pull/11490
