### ISSUE TITLE
how to define  flink command line

### ISSUE THREAD

**Issue by zixiao144** [apache/dolphinscheduler#11892]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I want to use *.zip or *.pyz  in flink task,it can not do.
select  flink >1.10,and  again edit ,it become  flink<1.10.
flink run \
      --pyModule table.word_count \
      --pyFiles examples/python/table
flink run-application -t yarn-application
like this command,how to  do it
I use pyflink 1.15 

### What you expected to happen

I want to use *.zip or *.pyz  in flink task,it can not do.
select  flink >1.10,and  again edit ,it become  flink<1.10.
flink run \
      --pyModule table.word_count \
      --pyFiles examples/python/table
flink run-application -t yarn-application
like this command,how to  do it.
I use pyflink 1.15 

### How to reproduce

I want to use *.zip or *.pyz  in flink task,it can not do.
select  flink >1.10,and  again edit ,it become  flink<1.10.
flink run \
      --pyModule table.word_count \
      --pyFiles examples/python/table
flink run-application -t yarn-application
like this command,how to  do it
I use pyflink 1.15 

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
It may need to refactor the Flink task plugin to support this or you can use shell task plugin.
