### ISSUE TITLE
[Bug] [task-plugin] run python task, source: not found

### ISSUE THREAD

**Issue by hiSandog** [apache/dolphinscheduler#11900]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/24449799/189535015-d528080d-6a33-4437-b369-8def3197c5e2.png)

When a Python task is run, "sudo -u qilin_ci sh" is first executed.
At line 123 of [AbstractCommandExecutor](https://github.com/apache/dolphinscheduler/blob/dev/dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java)

But the command line that needs to be executed like "source /opt/dolphinscheduler/conf/dolphinscheduler_env.sh" .
At line 111 of [ShellCommandExecutor](https://github.com/apache/dolphinscheduler/blob/dev/dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/ShellCommandExecutor.java)

Bash is the one that can execute the source command. Sh doesn't seem to be able to execute the source command.

I'm not sure if this is a bug or a problem with my configuration.

### What you expected to happen

...

### How to reproduce

...

### Anything else

...

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Duplicated with #10938.
