### ISSUE TITLE
[Improvement][Dependent] The project list in dependent node's permissions should not be restricted. 

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#11902]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The project list in dependent node's permissions should not be restricted. Suggesting create a new API without project permission restrictions and provide it to dependent nodes in UI.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by limaiwang** [comment]
I want to accept it, please assign to me

**Comment by SbloodyS** [comment]
> I want to accept it, please assign to me

I've assigned to you. Looking forward to your contribution.
