### ISSUE TITLE
[Improvement] [Alert] should mask the password of email password

### ISSUE THREAD

**Issue by fhygh** [apache/dolphinscheduler#11913]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when create alert instance, email password display in plaintext, should mask password
![image](https://user-images.githubusercontent.com/25889738/189900622-300ebbaf-a8cc-4c9d-b13f-8b02f2620c55.png)

### What you expected to happen

mask the email password when create or update alert instance

### How to reproduce

create or update new alert instance

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pandong2011** [comment]
已经提交了pr，未来应该能fix
![email](https://user-images.githubusercontent.com/100667564/190340342-6f24643a-991d-4efd-83ab-6bc4d2f8e01f.jpg)

**Comment by fhygh** [comment]
@pandong2011  great, thank you

**Comment by fhygh** [comment]
@pandong2011 我本地修改你提的那个pr的四个文件，打包后部署上，密码还是明文的，请问下大概是什么原因呢？

**Comment by pandong2011** [comment]
> @pandong2011 我本地修改你提的那个pr的四个文件，打包后部署上，密码还是明文的，请问下大概是什么原因呢？

你修改完了文件后，先在本地跑起来，然后再去部署到生产，本地到生产部署中间有很长的链路，你具体问题出现在哪个环节我也不清楚，当然，如果遇到问题你可以把详细日志信息发出来，看我能不能帮助到你

**Comment by fhygh** [comment]
> > @pandong2011 我本地修改你提的那个pr的四个文件，打包后部署上，密码还是明文的，请问下大概是什么原因呢？
> 
> 你修改完了文件后，先在本地跑起来，然后再去部署到生产，本地到生产部署中间有很长的链路，你具体问题出现在哪个环节我也不清楚，当然，如果遇到问题你可以把详细日志信息发出来，看我能不能帮助到你

没报错，就是不生效，还是明文显示 @pandong2011

**Comment by EricGao888** [comment]
![image](https://github.com/apache/dolphinscheduler/assets/34905992/55987b0d-26b6-4c8c-ba3a-f6da0f9f03b8)
Seems this issue not fixed yet.

**Comment by c3Vu** [comment]
i am willing to fix this issue

**Comment by EricGao888** [comment]
> i am willing to fix this issue

Thanks : ) 
I've assigned it to u, enjoy coding!
