### ISSUE TITLE
[Bug] [UI] missing some fields value in edit DataX node

### ISSUE THREAD

**Issue by hqzh** [apache/dolphinscheduler#11927]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/26128706/190096708-5a2ce0c1-867d-4307-aded-45dfc875201e.png)

### What you expected to happen

fulfill missing fields

### How to reproduce

edit DataX node

### Version

3.0.0

**Comment by hqzh** [comment]
please check, I am willing to submit a PR!

**Comment by hqzh** [comment]
@SbloodyS can you help me 
![image](https://user-images.githubusercontent.com/26128706/190328725-47b6a382-3312-437c-94b1-0bc6e3990d94.png)

**Comment by hqzh** [comment]
please check, i will pr

**Comment by zhongjiajie** [comment]
duplicate to https://github.com/apache/dolphinscheduler/issues/11201
