### ISSUE TITLE
[Bug] [Dependent] Start process instance error when enable dependent mode

### ISSUE THREAD

**Issue by stalary** [apache/dolphinscheduler#11928]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Start process instance error when enable dependent mode, 
I find in `dependentCommand = (Command) BeanUtils.cloneBean(command)` the command id not modified due to Duplicate entry 'xxx' for key 't_ds_command.PRIMARY', I suspect it relation https://github.com/apache/dolphinscheduler/pull/11765

### What you expected to happen

Start process success.

### How to reproduce

Use dev code, create two process, one parent, one child dependent parent and start parent process use dependent mode.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
This is due to we copy the command to dependentCommand, but didn't set the id to null, I will fix this.
