### ISSUE TITLE
[Bug] [Task Definition] The predecessor task is lost when the task definition function modifies the task

### ISSUE THREAD

**Issue by jinyanhui2008** [apache/dolphinscheduler#11952]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. After creating a new workflow through the workflow definition, modify one of the task nodes in the task definition, and the pre-task node in the open window is lost.

2. When adding a new task through task definition, you must select a predecessor task, and the workflow name and workflow status of other tasks in the current workflow will be lost.

3. When modifying a task through task definition, the content must be changed, otherwise the workflow name and workflow status of the current task will be lost.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
I have assigned to you, please remember one PR only solve one issue, if you have more than one issue, please split it to different issues

**Comment by jinyanhui2008** [comment]
现在问题是任务定义功能有点复杂，有没有小伙伴能协助讲解一下流程，现在问题修复起来有点头大。
