### ISSUE TITLE
[Bug]  The two [sub_process] tasks are the parent task and the child task. The task cannot be stopped

### ISSUE THREAD

**Issue by Zephyrcf** [apache/dolphinscheduler#11955]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The two [sub_process] tasks are the parent task and the child task. The task cannot be stopped.
.

### What you expected to happen

The two [sub_process] tasks are the parent task and the child task. The task can be stopped.

### How to reproduce

The two [sub_process] tasks are the parent task and the child task, run the parent task. 

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Could you please provide more information? e.g. your workflow picture
