### ISSUE TITLE
[Bug] [dolphinscheduler-service] datasource field note length more than 255 response a error

### ISSUE THREAD

**Issue by hqzh** [apache/dolphinscheduler#11960]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/26128706/190341871-4412871b-4ddc-423c-a6ff-9bb161987ed8.png)
![image](https://user-images.githubusercontent.com/26128706/190341994-12c9555f-8937-477b-bbb5-fa96d8099af7.png)

### What you expected to happen

response 200

### How to reproduce

any case

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fengjian1129** [comment]
@hqzh I think this error is actually the maximum allowable field length of 255 in the table structure. You can manually modify the table structure.

For example, the following figure:
<img width="894" alt="image" src="https://user-images.githubusercontent.com/35831367/190378703-267f0a1f-d427-44cb-9d0f-2e99180f92ff.png">

**Comment by hqzh** [comment]
@fengjian1129 got it , if table keep it 255, ui need validate.

**Comment by davidzollo** [comment]
> ### What happened
> ![image](https://user-images.githubusercontent.com/26128706/190341871-4412871b-4ddc-423c-a6ff-9bb161987ed8.png) ![image](https://user-images.githubusercontent.com/26128706/190341994-12c9555f-8937-477b-bbb5-fa96d8099af7.png)

good job, please use the picture in English environment, thx

**Comment by hqzh** [comment]
![image](https://user-images.githubusercontent.com/26128706/190541201-1a0074b7-294e-49d3-9880-3d6cc42819d3.png)
![image](https://user-images.githubusercontent.com/26128706/190541273-a5768c10-fad1-4c22-8efa-c0ca6468e539.png)
@davidzollo plan is fix table or ui？
