### ISSUE TITLE
[Bug] [Master] task failed when shell node assign a worker group an then change worker group

### ISSUE THREAD

**Issue by darrkz** [apache/dolphinscheduler#11964]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I run a old and simple workflow, but it hung on a node and status shows submit success and hold the status for minutes.
all new task instance hang.

So I have to stop the workflow to let the ds system workfine

server log shows :

[ERROR] 2022-09-15 16:12:29.917 org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer:[144] - ExecuteException dispatch error: fail to execute : Command [type=TASK_EXECUTE_REQUEST, opaque=22407363, bodyLen=1800] due to no suitable worker, current task needs worker group 测试组-master-138 to execute
org.apache.dolphinscheduler.server.master.dispatch.exceptions.ExecuteException: fail to execute : Command [type=TASK_EXECUTE_REQUEST, opaque=22407363, bodyLen=1800] due to no suitable worker, current task needs worker group 测试组-master-138 to execute
        at org.apache.dolphinscheduler.server.master.dispatch.ExecutorDispatcher.dispatch(ExecutorDispatcher.java:89)
        at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.dispatch(TaskPriorityQueueConsumer.java:138)
        at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.run(TaskPriorityQueueConsumer.java:101)
[ERROR] 2022-09-15 16:12:29.917 org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer:[146] - dispatch error: java.lang.NullPointerException
java.lang.NullPointerException: null

### What you expected to happen

It work fine

### How to reproduce

made a workflow and asign a worker group on a node
then change the worker group name
then the node hang

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by darrkz** [comment]
I had select data from the ds metadata, and the t_ds_task_definition.worker_group column store the name of worker group but not id of the worker group
So afer change the name of worker group , it go wrong...

And I see this bug still in version 2.0.6

**Comment by darrkz** [comment]
I think the task should faild instead of block all new following task instaces

**Comment by fengjian1129** [comment]
@darkz1984 I have also encountered this problem, which may be caused by the deletion of the workgroup used to run the task before. Add this workgroup('测试组-master-138') back manually.

**Comment by DarkAssassinator** [comment]
dev branch also has this issue. but just will reproduced after master restart and failover. I will check it

**Comment by brave-lee** [comment]
I think this is a feature, not bug, threre are not added new feature in 2.0.7. Please pay attention #12000 in dev version

**Comment by darrkz** [comment]
> Thank you for your feedback, we have received your issue, Please wait patiently for a reply.

I think this is a system design but , tables relationship should use a key of row in different table but not name.

It's  a basic database desgin rule

**Comment by darrkz** [comment]
> @darkz1984 I have also encountered this problem, which may be caused by the deletion of the workgroup used to run the task before. Add this workgroup('测试组-master-138') back manually.

The group was renamed.
and you delete the group , and re-add it back, the worker relationship in group will be wrong...
