### ISSUE TITLE
[Feature][Dependence] Reform dependence mode

### ISSUE THREAD

**Issue by brave-lee** [apache/dolphinscheduler#11970]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Present situation: The current dependency is on a single task and All. In fact, All depends on workflow, not all tasks
Planned reform:
1. The mode of relying on a single task remains unchanged. All is changed to rely on all tasks in the workflow, and a new type of workflow dependency is added.
2. The front end adds a radio box in the dependency area to select dependent tasks or workflows. If you select dependent tasks, the task selection box will be displayed. If you now rely on workflows, the task selection box will be hidden
3. For the backend, All is still 0 for the task code. When workflow is relied on, the corresponding task code can be represented by - 1 or other
----------
当前状况：当前的依赖是依赖单个任务和All，这里的All其实是依赖工作流，并不是依赖所有的任务
计划改造：
1、依赖单个任务的方式不变，All改造成依赖工作流中所有任务，新增一种类型依赖工作流。
2、前端在依赖的地方增加个单选框，选择依赖任务或者工作流，如果选择依赖任务，任务的选择框显示出来，如果现在依赖工作流，任务的选择框隐藏
3、对于后端，All对于的任务code还是0，依赖工作流时，对应的任务code可使用-1或其他表示

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by guowei-su** [comment]
Hi, I will contribute this feature.
The dependency mode for dependent node in dev branches will be modified. 

- The logic of **Dependent on ALL** will be changed from **checking the workflow state** to **checking the state of all task instances in the workflow**. 
- A new **Dependent on workflow** is added that is responsible for **checking the workflow state**. 
- For compatibility with user history data, Constants.DEPENDENT_WORKFLOW_CODE will be assigned a value of 0, replacing the original Constants.DEPENDENT_ALL_TASK_CODE, and Constants.DEPENDENT_ALL_TASK_CODE will be assigned a value of -1. 

I'll add a drop-down select box that controls the type of dependency to the front-end code to support this feature. The select box options include **Dependent on workflow** and **Dependent on task**. When Dependent on workflow is selected, it looks like the following image:
![image](https://github.com/apache/dolphinscheduler/assets/56352018/e38f8bbc-4114-4710-a7e7-1973db443b66)
When Dependent on task is selected, as shown below:
![image](https://github.com/apache/dolphinscheduler/assets/56352018/a4b50060-b0b1-490b-a123-88cf002bca4a)

**Comment by brave-lee** [comment]
closed by #14824
