### ISSUE TITLE
[Bug] [UI] After we delete the worker group, but this task group still keep in the task setting.

### ISSUE THREAD

**Issue by DarkAssassinator** [apache/dolphinscheduler#12002]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

in #12000, after deleted the worker group, then edit the task setting, the `app01` still show in the setting.
![image](https://user-images.githubusercontent.com/20518339/190637476-1605f33e-cae6-4b0e-8eff-0165663a8794.png)

### What you expected to happen

the worker group should be null 

### How to reproduce

delete a worker group and then edit the task setting.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
It seems that the worker group can not be deleted. @DarkAssassinator

**Comment by DarkAssassinator** [comment]
> It seems that the worker group can not be deleted. @DarkAssassinator

but after i fix this deleted bug, this case still do not resolve.

**Comment by hstdream** [comment]
I think that when deleting the workgroup, it is necessary to verify whether the use.
