### ISSUE TITLE
[Bug] [dolphinscheduler-api] there is not any tenant suitable, please choose a tenant available

### ISSUE THREAD

**Issue by pandong2011** [apache/dolphinscheduler#12004]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I create the workflow as the admin user, then select the default tenant and execute it, I get the following exception
![admindefault](https://user-images.githubusercontent.com/100667564/190670966-88f8407c-e44c-4988-80e2-f66bbea3e357.jpg)
![notvalidtenant](https://user-images.githubusercontent.com/100667564/190671062-ad703bac-55b9-482f-983b-32b1ef2f0d78.jpg)

When I create a workflow with a regular user and select the default tenant, it works
![pddefault](https://user-images.githubusercontent.com/100667564/190671537-424789fb-a630-4198-8c6f-b2174e9cfe16.jpg)
![exesuccess](https://user-images.githubusercontent.com/100667564/190674417-a167c04b-f868-41ac-b044-17d88529457a.jpg)

### What you expected to happen

When I create a common user as the admin user, a tenant is bound
![createreguleruser](https://user-images.githubusercontent.com/100667564/190676206-b357339a-9ac8-4610-b75f-25893c80a899.jpg)

However, the admin user exists from the beginning, so there is no default tenant binding
when user admin is used, the following code tenant returns a null value
![requirefix](https://user-images.githubusercontent.com/100667564/190677553-3c44adf6-11df-4fb0-b931-013a4c777131.jpg)

### How to reproduce

As I mentioned above

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fengjian1129** [comment]
First, I think u should create a default tenant.
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/35831367/191934329-846ebc2d-af2b-4423-9294-4805e62c2e07.png">
Secondly, u should create users in Linux or Mac systems, for example: user add xxxx

**Comment by pandong2011** [comment]
> First, I think u should create a default tenant. <img alt="image" width="1078" src="https://user-images.githubusercontent.com/35831367/191934329-846ebc2d-af2b-4423-9294-4805e62c2e07.png"> Secondly, u should create users in Linux or Mac systems, for example: user add xxxx


This is because the back-end program has relevant checks. When the workflow is created and executed, the back-end program will be executed as shown in Figure 1, Figure 2, Figure 3 and Figure 4. In Figure 4, when the admin user is used and the default tenant is selected, the check cannot pass

![0](https://user-images.githubusercontent.com/100667564/192000447-217c7b28-338c-4ec0-a231-c48afdf329fb.jpg)
![1](https://user-images.githubusercontent.com/100667564/192000476-e6b833bb-0ec8-41ba-bfaf-c331b5f112c5.jpg)
![2](https://user-images.githubusercontent.com/100667564/192000509-f1e3f975-9eac-4b0e-a236-4c5733fc9eee.jpg)
![3](https://user-images.githubusercontent.com/100667564/192000541-d894eef2-dd0e-4fb6-9d96-95fd48ff1811.jpg)

**Comment by pandong2011** [comment]
Rerouting workflow instances will also have relevant checks, The final solution is that if the current user is admin, there is no default option for the front-end save workflow when selecting a tenant, and if the user is a normal user, there is a default option

![4](https://user-images.githubusercontent.com/100667564/192001905-9c89889a-e947-4108-9ee3-11195ec2bb6c.jpg)
![5](https://user-images.githubusercontent.com/100667564/192001944-6737a1d8-7d75-43d8-a56c-baf35fb7428a.jpg)
![6](https://user-images.githubusercontent.com/100667564/192001978-33197109-cd47-4d9b-a9ff-c249fe513a13.jpg)
![7](https://user-images.githubusercontent.com/100667564/192002011-4cdc175e-3b7d-4950-952b-7295ad63cc2d.jpg)

**Comment by yaoquanxin** [comment]
i solve this problem ,  step 1: which python3  for search your python lujin, step 2: ctrl c for it and ctrl v to ds enviroment variable. step 3 run you program.  keng: maybe  your enviroment in linux its error, "which python3"  command can search good lujin, good luck for you ,my good bro.    
![image](https://github.com/apache/dolphinscheduler/assets/153439496/6fc161f9-b711-4c6a-9156-b5416e3f07f2)
