### ISSUE TITLE
[Improvement][UI] Notebook task plugins UI optimization

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#12028]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Optimize UI for notebook task plugins, which include `Zeppelin` task plugin and `Jupyter` task plugin for better user experience.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rickchengx** [comment]
Hi, @EricGao888 , I'm interested.
