### ISSUE TITLE
[Improvement][dolpinschedulrer-ui-next] task component extend with backend config

### ISSUE THREAD

**Issue by woshiwuxiaofei** [apache/dolphinscheduler#12047]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When adding a task component type, the status quo is:
1. Add a plug-in to the back-end, and change the form of the code on the front-end
It is hoped that the back-end will configure which plugins the front-end can display through the interface in the future, and then the front-end does not need to write dead code;

![image](https://user-images.githubusercontent.com/17974050/190990591-3d0846b1-9837-4967-9937-5221744ebabf.png)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Good idea, in fact, the workflow status enum/ task instance status enum, plugin type... are all hard code in the front-end.
But this is not a new feature, it's more like am improvement.

**Comment by davidzollo** [comment]
> Good idea, in fact, the workflow status enum/ task instance status enum, plugin type... are all hard code in the front-end. But this is not a new feature, it's more like am improvement.

this is a big feature, many backend contributors are not familiar with front-end code,  this is a good job if completed

**Comment by DarkAssassinator** [comment]
awesome, this idea is a boon for backend programmers like me...
and it is possible to control the permissions that users can view tasks in the future?
User A can use SHELL/PYTHON/SQL
User B can use Flink/Spark
...

**Comment by ruanwenjun** [comment]
@woshiwuxiaofei Could you please provide a detail design, in my knowledge, your description in the issue is want to add an interface to control how many plugins will display in the front-end, or you want to refactor the task-plugin, control the UI like alert-plugin?
