### ISSUE TITLE
[Bug] [sql-plugin] the log prossiblely mislead the users

### ISSUE THREAD

**Issue by CriysHot** [apache/dolphinscheduler#12043]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

i only got the error is 'SQL task prepareStatementAndBind error' when i exec my sql task,
it's only a part of the complete logs.i'm sorry that i loss my picture on the ds web.
i logined my worker server and get the complete log,i found the real reason that casuse my task to fail. is 'get oneSessionDataSource Connection fail SQLException: HikariPool-3 - Connection is not available, request timed out after 30000ms.'
the fllowing is the log on the woker server
![1663568339967](https://user-images.githubusercontent.com/42238827/190959645-d5addaa5-fce0-48c5-8ef1-ed424dd48e4a.jpg)
by the way,i watch the source code about SqlTask class,whatever exception we catch,we will get the error,SQL task prepareStatementAndBind error.
the fllowing is the source code:
![1663568844419](https://user-images.githubusercontent.com/42238827/190961119-b301d03c-402f-4a41-ad52-aad65be38e68.jpg)

### What you expected to happen

i hope that  ds can tell me complete error log then i can find the real reason that casuse my task to fail.

### How to reproduce

sorry,i have no idea.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Guojcc** [comment]
Hello, I have encountered the same problem. How did you solve it ?

**Comment by ATM006** [comment]
+1
