### ISSUE TITLE
[Bug] [Master] Construct processInstance may NPE when master handling command

### ISSUE THREAD

**Issue by tracehh** [apache/dolphinscheduler#12055]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 Construct processInstance may NPE when master handling command

### What you expected to happen

commond content changed

### How to reproduce

commond content changed

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
>How to reproduce
commond content changed

Hi @tracehh can you show the detail how to reproduce? I can't get your point by `commond content changed`.

**Comment by tracehh** [comment]
Map<String, String> processCmdParam = JSONUtils.toMap(processInstance.getCommandParam());
processInstance.getCommandParam() may be change accroding to update table directory.
processCmdParam may be null. @caishunfeng

**Comment by caishunfeng** [comment]
> processInstance.getCommandParam() may be change accroding to update table directory. processCmdParam may be null. 

You mean update the data in table `t_ds_process_instance` manually?

**Comment by tracehh** [comment]
may be
