### ISSUE TITLE
[Bug] [MASTER] workflow cannot normally start version 3.1.0-prepare

### ISSUE THREAD

**Issue by Tianqi-Dotes** [apache/dolphinscheduler#12065]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when i try to start a workflow, the master print exception logs, check pics below:
![69fd6568a306cece326a69f6178dd74](https://user-images.githubusercontent.com/36755957/191196300-b6181a37-ace9-4db3-a11e-69b4c5c6a75a.jpg)
![51b6ec314318083539f450474838b76](https://user-images.githubusercontent.com/36755957/191196335-8a94b0dd-0650-4a1a-8a4d-691217335d39.jpg)
![5bb6034b863e968d28bf1f42956238a](https://user-images.githubusercontent.com/36755957/191196352-d49acdf2-706b-4e7d-9ccd-7ec7cf0a8657.jpg)

### What you expected to happen

normally start the workflow

### How to reproduce

create a new workflow and start, check the master log

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pandong2011** [comment]
@Tianqi-Dotes I have encountered this bug before, can you provide more error information

**Comment by Tianqi-Dotes** [comment]
> @Tianqi-Dotes I have encountered this bug before, can you provide more error information

this bug might be fixed by this pr, I will test it after it merge.
https://github.com/apache/dolphinscheduler/pull/12064

**Comment by pandong2011** [comment]
ok

**Comment by pandong2011** [comment]
> > @Tianqi-Dotes I have encountered this bug before, can you provide more error information
> 
> this bug might be fixed by this pr, I will test it after it merge. #12064

ok
