### ISSUE TITLE
[WIP][Feature][Api] Refactor api.controller.WorkerGroupV2Controller

### ISSUE THREAD

**Issue by lvshaokang** [apache/dolphinscheduler#12072]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Suggest refactor the backend api，WorkerGroupController

### Related issues

#10257 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @lvshaokang I assign to you now :smile:
