### ISSUE TITLE
[Bug] [Workflows] Export the json workflow, and then import the work and report an error 

### ISSUE THREAD

**Issue by Gagepmd** [apache/dolphinscheduler#12085]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/111988192/191458162-165fa819-bdfb-41ee-9121-732acc08fccf.png)

### What you expected to happen

Import succeeded

### How to reproduce

Export the json workflow, and then import the work and report an error 

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
same issue #12078
