### ISSUE TITLE
[Bug] [Workflow Instance] Create two subtasks in a workflow (these two tasks are Python type tasks), select Python 2 and Python 3 as the running environment, run the workflow, and the workflow will always be executed 

### ISSUE THREAD

**Issue by Gagepmd** [apache/dolphinscheduler#12089]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Create two subtasks in a workflow (these two tasks are Python type tasks), select Python 2 and Python 3 as the running environment, run the workflow, and the workflow will always be executed 

### What you expected to happen

Workflow executed successfully

### How to reproduce

Create two subtasks in a workflow (these two tasks are Python type tasks), select Python 2 and Python 3 as the running environment, run the workflow.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @Gagepmd can you provide more information? such as these tasks states, any error log?

**Comment by Gagepmd** [comment]
![image](https://user-images.githubusercontent.com/111988192/191676359-1fdc5f63-14f6-487a-809a-159ed785f730.png)


> Hi @Gagepmd can you provide more information? such as these tasks states, any error log?

**Comment by Gagepmd** [comment]
> ![image](https://user-images.githubusercontent.com/111988192/191676359-1fdc5f63-14f6-487a-809a-159ed785f730.png)
> 
> > Hi @Gagepmd can you provide more information? such as these tasks states, any error log?
This error is reported repeatedly in the master server log.

**Comment by Tianqi-Dotes** [comment]
this pr fixed this problem, please pull the latest code, I have tested the lastest dev is fine.
https://github.com/apache/dolphinscheduler/pull/12064

**Comment by caishunfeng** [comment]
> this pr fixed this problem, please pull the latest code, I have tested the lastest dev is fine. #12064

I will close this issue.
