### ISSUE TITLE
[Feature][API] Support to assign permissions of the tenant to users.

### ISSUE THREAD

**Issue by calvinjiang** [apache/dolphinscheduler#12086]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently the dolphinscheduler doesn't support to assign one or more tenants to a user. The user can use any tenants to execute their tasks in some workers. But tenants usually own different permissions in a worker. When users using a tenant to execute a task , they just owns permissions of the tenant. That's so unsafe. I do suggest that a user should be assigned limited permissions and tenants. 

### Use case

The system can support to assign tenants to the user.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pandong2011** [comment]
Tenants will be assigned when a common user is created using the admin user

**Comment by ruanwenjun** [comment]
This need to discuss, the tenant is better belong to project rather than user.
