### ISSUE TITLE
[Bug] [Alert-server] Alert server initialization failed 

### ISSUE THREAD

**Issue by Gagepmd** [apache/dolphinscheduler#12087]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/111988192/191465992-aeabdf23-222a-4500-b356-4ab68b26a162.png)Alert server initialization failed 

### What you expected to happen

Alert server started successfully

### How to reproduce

Redeploy the service and start the alert server

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Is this issue for branch 3.1.0-prepare?

**Comment by Gagepmd** [comment]
alert-server/conf/common.properties configuration file modifies the configuration resource. storage. type=NONE. Restarting the alert server can solve the problem
