### ISSUE TITLE
[Improvement][data_quality] [ui] 

### ISSUE THREAD

**Issue by zeaper123** [apache/dolphinscheduler#12082]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

dolphinscheduler version :3.0.0

I found data_quality is inconvenient to use ：

<img width="602" alt="image" src="https://user-images.githubusercontent.com/72915398/191444182-f60a72fa-6dc7-4434-b9ac-e40e9c2af9b1.png">
<img width="671" alt="image" src="https://user-images.githubusercontent.com/72915398/191444783-7c2c7ab0-224b-4bd8-bfcb-493bccdc6e4c.png">

I have to find target table from hundreds of tables with sliding roller,this is an inefficient thing.

I wish to enter table name to search target table 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
It's better to be filterable.
