### ISSUE TITLE
[Bug] [Master] Master count: 0 is invalid, the current slot: 0

### ISSUE THREAD

**Issue by RUIzg** [apache/dolphinscheduler#12097]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

dolphinscheduler 3.0 master  server cann't process normal task 
I can see master server log file  always print  this tips :
 Master count: 0 is invalid, the current slot: 0

### What you expected to happen

when I run a task on dolphinscheduler  web UI ,I switch to task list ,I should can see a new Task is running ,
but current I can't see anything is running .

### How to reproduce

I dot't know 

### Anything else

current cluster 
1 master 
2 worker

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
It seems the master server doesn't startup successfully, please check the master log.

**Comment by fuchanghai** [comment]
@RUIzg when you run a process instance ,will the information that ``` master does not exist  ```  or ``` 无可用master 节点``` alert on the page?

**Comment by RUIzg** [comment]
> @RUIzg when you run a process instance ,will the information that `master does not exist ` or ` 无可用master 节点` alert on the page?

@fuchanghai   not any error infomation ,  alert a  success  tip on the page
