### ISSUE TITLE
[Bug] [dolphinscheduler-dao] standalone use h2 db engine, data quality paging list get exception 

### ISSUE THREAD

**Issue by boy-xiaozhang** [apache/dolphinscheduler#12107]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

start dolphinscheduler server,use h2 db,Keyword conflict

![image](https://user-images.githubusercontent.com/60912722/191717162-210a52c6-40f5-4500-93ec-73e9315ab72e.png)

<img width="934" alt="image" src="https://user-images.githubusercontent.com/60912722/191717560-438804bc-f40d-4de0-a0e7-e92b8f70fbfc.png">

### What you expected to happen

Fix keyword conflicts

### How to reproduce

Use h2 to start and click to open the data quality rule management page to reproduce.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
closed by #12108
