### ISSUE TITLE
[Bug] [timing] Workflow configuration is timed, but it is not started regularly as required. View the log and find that the master server reports an error

### ISSUE THREAD

**Issue by Gagepmd** [apache/dolphinscheduler#12103]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Workflow configuration is timed, but it is not started regularly as required. View the log and find that the master server reports an error
![image](https://user-images.githubusercontent.com/111988192/191704957-67c9dc3a-8c63-49ca-b177-7156113d86d4.png)

### What you expected to happen

Workflow ran successfully

### How to reproduce

New workflow configuration timing, online workflow

### Version

3.1.0-prepare

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Maybe it's a failover workflow.

**Comment by caishunfeng** [comment]
same issue #12089
