### ISSUE TITLE
[Bug] [Resource] The zombie resources cannot be deleted

### ISSUE THREAD

**Issue by ErikXu** [apache/dolphinscheduler#12102]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I uploaded some resources using a user account named `test`. 
Then I deleted the user before deleting the resources by mistake.
The resources become zombie resources and cannot be deleted even using the open api: 
```
curl -X DELETE "http://www.example.com/dolphinscheduler/resources/90034" -H "Request-Origion:SwaggerBootstrapUi" -H "accept:*/*" -H "Content-Type:application/x-www-form-urlencoded;charset=UTF-8"
```

The response is:

```
{
  "code": 10010,
  "msg": "user 60,010 not exists",
  "data": null,
  "failed": true,
  "success": false
}
```

### What you expected to happen

It should be a way to force deleting the zombie resources.

### How to reproduce

1. Create a user name `test`
2. Use `test` to create directories or upload some files
3. Delete the `test` user
4. The resources become zombie

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by boy-xiaozhang** [comment]
hello,current dolphinscheduler deleting a user does not delete the resource created by the current user, and the user is verified when deleting the resource.

**Comment by ErikXu** [comment]
Is it possile to provide an api to do a force deletion that did not verify the user?
