### ISSUE TITLE
[Bug] [Workflow Instance/Workflow Name] The display is not standard when the workflow name is too long

### ISSUE THREAD

**Issue by Gagepmd** [apache/dolphinscheduler#12110]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/111988192/191729380-4daaf468-594e-4222-b6a7-756aff4e238f.png)
The display is not standard when the workflow name is too long

### What you expected to happen

Replace the part that cannot be displayed with...

### How to reproduce

Create a new workflow with a long name.

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
<img width="975" alt="image" src="https://user-images.githubusercontent.com/97265214/191880942-b10d6a7b-4557-4227-be55-d04f22ba9261.png">
It is ok for me. Could you check it again? @Gagepmd

**Comment by caishunfeng** [comment]
same issue #11787
