### ISSUE TITLE
[Bug] [ui] build with error

### ISSUE THREAD

**Issue by zcw5116** [apache/dolphinscheduler#12119]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

version: dev
build with error，the following：

Downloading **https://nodejs.org/dist/v16.13.1/node-v16.13.1-linux-x86.tar.gz** to /home/imooc/.m2/repository/com/github/eirslett/node/16.13.1/node-16.13.1-linux-x86.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for dolphinscheduler-ui 3.0.1:
[INFO] 
[INFO] dolphinscheduler-ui ................................ FAILURE [  6.945 s]
...

[INFO] Total time:  9.211 s
[INFO] Finished at: 2022-09-23T12:11:34+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] **Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install node and pnpm) on project dolphinscheduler-ui: Could not download Node.js: Got error code 404 from the server.** -> [Help 1]
[ERROR] 

In fact， uri  https://nodejs.org/dist/v16.13.1/node-v16.13.1-linux-x86.tar.gz  does not exists

### What you expected to happen

download  uri  https://nodejs.org/dist/v16.13.1/node-v16.13.1-linux-x86.tar.gz  does not exists

### How to reproduce

./mvnw clean install -Prelease

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pandong2011** [comment]
From the log information is this version node. Js not downloaded, and https://nodejs.org/dist/v16.13.1/node-v16.13.1-linux-x86.tar.gz repository node does not, so need yourself to download from other sources, Or replace it with another version and skip the check at build time

**Comment by zcw5116** [comment]
Still don't know how to solve this problem?

Can you describe it in more detail?

> From the log information is this version node. Js not downloaded, and https://nodejs.org/dist/v16.13.1/node-v16.13.1-linux-x86.tar.gz repository node does not, so need yourself to download from other sources, Or replace it with another version and skip the check at build time

Still don't know how to solve this problem?

Can you describe it in more detail?

**Comment by pandong2011** [comment]
Dolphinscheduler-ui 3.0.1 is based on VUE3 and therefore requires Node support. During project installation, the frontend-Maven-plugin downloads node from the repository, but there are no node in the repository  https://nodejs.org/dist/v16.13.1/node-v16.13.1-linux-x86.tar.gz

**Comment by zcw5116** [comment]
Thanks， I know this, but how to solve it， could you give me some tips， thank you very much


> Dolphinscheduler-ui 3.0.1 is based on VUE3 and therefore requires Node support. During project installation, the frontend-Maven-plugin downloads node from the repository, but there are no node in the repository https://nodejs.org/dist/v16.13.1/node-v16.13.1-linux-x86.tar.gz

Thanks， I know this, but how to solve it， could you give me some tips， thank you very much

**Comment by pandong2011** [comment]
Since your Linux is a 32 system and the repository only has packages for 64-bit systems, you can download packages for 32-bit systems from other sources or change your build environment to Windows, which is available for both 32-bit and 64-bit systems
![Uploading node32位.jpg…]()

**Comment by pandong2011** [comment]
Since your Linux is a 32 system and the repository only has packages for 64-bit systems, you can download packages for 32-bit systems from other sources or change your build environment to Windows, which is available for both 32-bit and 64-bit systems
![node32位](https://user-images.githubusercontent.com/100667564/191919357-52fc94c0-38e4-4818-b962-16f3da00b47a.jpg)


> Thanks， I know this, but how to solve it， could you give me some tips， thank you very much
> 
> > Dolphinscheduler-ui 3.0.1 is based on VUE3 and therefore requires Node support. During project installation, the frontend-Maven-plugin downloads node from the repository, but there are no node in the repository https://nodejs.org/dist/v16.13.1/node-v16.13.1-linux-x86.tar.gz
> 
> Thanks， I know this, but how to solve it， could you give me some tips， thank you very much

Since your Linux is a 32 system and the repository only has packages for 64-bit systems, you can download packages for 32-bit systems from other sources or change your build environment to Windows, which is available for both 32-bit and 64-bit systems

![Uploading node32位.jpg…]()

**Comment by pandong2011** [comment]
Since your Linux is a 32 system and the repository only has packages for 64-bit systems, you can download packages for 32-bit systems from other sources or change your build environment to Windows, which is available for both 32-bit and 64-bit systems

![node32位](https://user-images.githubusercontent.com/100667564/191921868-2fd92e02-282b-4c1f-8594-113967ec4814.jpg)

**Comment by ouyangyewei429** [comment]
You can specify `<nodeDownloadRoot>` to solve

```xml
<plugin>
    <groupId>com.github.eirslett</groupId>
    <artifactId>frontend-maven-plugin</artifactId>
    <version>${frontend-maven-plugin.version}</version>
    ...
    <executions>
        <execution>
            ...
            <configuration>
                <nodeDownloadRoot>http://npm.taobao.org/mirrors/node/</nodeDownloadRoot>
                <nodeVersion>${node.version}</nodeVersion>
                <pnpmVersion>${pnpm.version}</pnpmVersion>
            </configuration>
        </execution>
        ...
    </executions>
</plugin>
```
