### ISSUE TITLE
[Bug] [FE] cannot insert space in environment config

### ISSUE THREAD

**Issue by Tianqi-Dotes** [apache/dolphinscheduler#12128]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when i create a environment config, i cannot insert space inside the form.

### What you expected to happen

i can  insert space in environment  config

### How to reproduce

type space in the environment  config

### Anything else

please check other places whether have this issue

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
check the video that i'm typing space to the form
https://user-images.githubusercontent.com/36755957/192083795-892de97a-2e97-42c8-aa7e-475e41b476b7.mp4

**Comment by LiuBodong** [comment]
This may be the same as #11884

**Comment by devosend** [comment]
Hi, guy, Do you want to fix this problem now? If not, I'll fix it, because it's in a hurry, and it's going to be published soon. @LiuBodong

**Comment by LiuBodong** [comment]
> Hi, guy, Do you want to fix this problem now? If not, I'll fix it, because it's in a hurry, and it's going to be published soon. @LiuBodong

I have fixed this issue and created the pr, but they don't think it's a bug...
