### ISSUE TITLE
[Doc][Module Name]  upload v3.0.1 Download the DolphinScheduler releases

### ISSUE THREAD

**Issue by songangweb** [apache/dolphinscheduler#12132]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

https://dolphinscheduler.apache.org/zh-cn/download/download.html

### Documentation Links

https://dolphinscheduler.apache.org/zh-cn/download/download.html

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pandong2011** [comment]
The code for v3.0.1 is not that different from the code for v3.0.0, you can pull the code for release3.0.1 and build it yourself if you want

**Comment by songangweb** [comment]
我在使用 3.0.0的时候发现,   想使用资源中心, 按照文档中的配置后   还是一直显示 存储未开启.    因为我不是java栈, 想通过升级最新版本   看能否解决这个问题
