### ISSUE TITLE
[Feature][Alert] enable users to customize email content

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#12138]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- when start  a process Instance。we can only send the default mail format.
- we can use some placeholders to allow users to customize the email format. This feature does not involve the use of rich text
- I can only complete the backend part for now
- 
I want to make the red frame on the picture
![image](https://user-images.githubusercontent.com/33984497/192182278-bd1009f5-99c1-40a1-b4e9-bc78c6da4f9a.png)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Good idea, we can provide some placeholder e.g. {projectName}, {WorkflowInstanceName}, {TaskInstanceName}...

**Comment by fuchanghai** [comment]
> Good idea, we can provide some placeholder e.g. {projectName}, {WorkflowInstanceName}, {TaskInstanceName}...

- This is what we did in our secondary development。
- However, I believe that each module does not have the same variable access, so we should provide the variables that the module can provide in each place where the content of the email is defined
- To prevent spelling errors, you should do a select variable and then add operation in the front end
