### ISSUE TITLE
[Improvement][Test] Remove Powermock in dolphinscheduler-api

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#12144]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- Remove `Powermock` in `dolphinscheduler-api`
- This is a sub-task of #11405

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
See #12143 and #11588 for examples.

**Comment by rickchengx** [comment]
i am interested

**Comment by EricGao888** [comment]
> i am interested

@rickchengx Thanks for helping out : )
