### ISSUE TITLE
[Improvement][Test] Remove Powermock in dolphinscheduler-task-plugin

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#12150]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- Remove `Powermock` in `dolphinscheduler-task-plugin`
- This is a sub-task of #11405

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
See #12143 and #11588 for examples.

**Comment by EricGao888** [comment]
@stalary

**Comment by EricGao888** [comment]
@stalary Could u plz comment here? It seems GitHub `Assignees` could not find u if u haven't commented in this issue. : )
![image](https://user-images.githubusercontent.com/34905992/192240500-a412f076-a98f-46ef-9d43-0b78ae5b90d8.png)

**Comment by stalary** [comment]
> @stalary Could u plz comment here? It seems GitHub `Assignees` could not find u if u haven't commented in this issue. : ) ![image](https://user-images.githubusercontent.com/34905992/192240500-a412f076-a98f-46ef-9d43-0b78ae5b90d8.png)

I'm here~

**Comment by EricGao888** [comment]
> > @stalary Could u plz comment here? It seems GitHub `Assignees` could not find u if u haven't commented in this issue. : ) ![image](https://user-images.githubusercontent.com/34905992/192240500-a412f076-a98f-46ef-9d43-0b78ae5b90d8.png)
> 
> I'm here~

Thanks for helping out : )
