### ISSUE TITLE
[Bug] [Resources] storage not startup

### ISSUE THREAD

**Issue by zuzuviewer** [apache/dolphinscheduler#12156]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Resources File Manage module to create directory or file is failure, the error is 'storage not startup'

### What you expected to happen

create directory and file success

### How to reproduce

deploy by docker image with 3.0.0 version, and then create directory in Resources tab, File Manage

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
Have you started up the storage? If not, maybe [this doc](https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/resource/configuration.html) is helpful for you. @zuzuviewer

**Comment by JunChaoCheng** [comment]
I am interested in implementing this task ,can you assign me

**Comment by zuzuviewer** [comment]
> Have you started up the storage? If not, maybe [this doc](https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/resource/configuration.html) is helpful for you. @zuzuviewer

Ok,thanks your reply,and I did with doc ,but here had another error,request reply is '存储操作失败', and the log is

>  [INFO] 2022-09-27 02:19:35.896 +0000 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[90] - REQUEST TRACE_ID:f70d6959-e247-4260-86a7-005c5041293d, LOGIN_USER:admin, URI:/dolphinscheduler/resources/directory, METHOD:POST, HANDLER:org.apache.dolphinscheduler.api.controller.ResourcesController.createDirectory, ARGS:{currentDir=/, alias=f, description=, pid=-1, type=FILE}
> [ERROR] 2022-09-27 02:19:36.004 +0000 org.apache.dolphinscheduler.api.service.impl.ResourcesServiceImpl:[855] - verify resource failed  and the reason is null

my api-server and worker common.properties config is : 
`resource.storage.type=HDFS
resource.hdfs.fs.defaultFS=file:///
resource.storage.upload.base.path=/dolphinscheduler
`

**Comment by JunChaoCheng** [comment]
Is there a more detailed error message.
Have you tried to test locally and it was successful

**Comment by zuzuviewer** [comment]
> Is there a more detailed error message. Have you tried to test locally and it was successful

No any other error log.
I don't test locally,just docker

**Comment by huangchenguang123** [comment]
I can use HDFS locally, you can refer to my changes.

update:
resource.storage.type=HDFS
resource.hdfs.root.user=huangchenguang
resource.hdfs.fs.defaultFS=hdfs://localhost:9000

add:
fs.defaultFS=hdfs://localhost:9000

**Comment by zuzuviewer** [comment]
> I can use HDFS locally, you can refer to my changes.
> 
> update: resource.storage.type=HDFS resource.hdfs.root.user=huangchenguang resource.hdfs.fs.defaultFS=hdfs://localhost:9000
> 
> add: fs.defaultFS=hdfs://localhost:9000

wow,thank you very much, I add 'fs.defaultFS=file:///' property and it's effective

**Comment by huangchenguang123** [comment]
You can update the code to the latest version, the problem should have been fixed.And never use 'fs.defaultFS'

see #11823

**Comment by JunChaoCheng** [comment]
I think the specific exception information and reason should be printed out, so that it is easier to find the problem and solve it

**Comment by zuzuviewer** [comment]
> I think the specific exception information and reason should be printed out, so that it is easier to find the problem and solve it

All I could find is written above

**Comment by JunChaoCheng** [comment]
> > I think the specific exception information and reason should be printed out, so that it is easier to find the problem and solve it
> 
> All I could find is written above

I mean for ds to improve

**Comment by qiangliliu** [comment]
Please confirm your profile
