### ISSUE TITLE
[Improvement][Task] Rename MR to Hadoop

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#12161]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We have MR task type.
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/22415594/192441194-9ae2d336-2f70-4f5b-925b-b937bd1127a0.png">

Sometimes, this will make confuse, MR is MapReduce, but in fact the implementation is Hadoop, but MR != Hadoop.

It's better to rename this task to Hadoop.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
It seems to need modification on both the front end and the back end.

**Comment by DarkAssassinator** [comment]
i can do this easy case

**Comment by DarkAssassinator** [comment]
> It seems to need modification on both the front end and the back end.

It will be a great experience to expect the front-end and back-end to be completely decoupled so that users can choose the components they need without installing all task plug-ins.

**Comment by fuchanghai** [comment]
> > It seems to need modification on both the front end and the back end.
> 
> It will be a great experience to expect the front-end and back-end to be completely decoupled so that users can choose the components they need without installing all task plug-ins.


If the user can customize the page, should we discuss how to design the initial page and prompt the user to add task components

**Comment by ruanwenjun** [comment]
> > It seems to need modification on both the front end and the back end.
> 
> It will be a great experience to expect the front-end and back-end to be completely decoupled so that users can choose the components they need without installing all task plug-ins.

This issue is not discuss about decoupling the task plugin.
