### ISSUE TITLE
[Bug] [Dolphin 3.0 spark sql does not support dynamic parameter transfer] Dynamic parameter transfer failure is empty

### ISSUE THREAD

**Issue by yqzdy1207** [apache/dolphinscheduler#12184]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 [Bug] [海豚3.0 spark sql不支持动态传参] 动态传参失败为空

### What you expected to happen

[海豚3.0 spark sql 支持动态传参] 

### How to reproduce

[海豚3.0 spark sql 支持动态传参] 

### Version

3.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
It's better to report an issue with english.

**Comment by yqzdy1207** [comment]
![image](https://user-images.githubusercontent.com/33902141/192764084-564d041e-6b8a-4436-bf40-d7a6f4c33ae7.png)
![image](https://user-images.githubusercontent.com/33902141/192764267-64a2fb2e-8ced-47a5-9296-1a07637b8f53.png)

show null

**Comment by yqzdy1207** [comment]
> 最好用英语报告问题。

show null ,look
