### ISSUE TITLE
[BUG] bug with hive support

### ISSUE THREAD

**Issue by DingZhengCN** [apache/dolphinscheduler#1218]
**Describe the bug**
Create a sql node, the datasource choose HIVE.  it can not work right such as
`set hivevar:name='myname';
select ${name};`
cause the esschedule resolving the variable `name` before the hive sql does

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Go to 'Process definition'
2. Click on 'create process'
3. Drag the 'sql' node into the panel
4. Choose Datasource Option 'HIVE'
5. Add Pre Statement `set hivevar:name='somevalue'`
6. Typein SQL Statement

**Expected behavior**
Normally, `select ${name}` show retrieve the variable which I'v set

**Which version of Easy Scheduler:**
 -[1.1.0]

**Requirement or improvement
- Hive Version: 2.3.4

**Comment by xingchun-chen** [comment]
Currently sql node does not support set type, it is recommended to improve in the next version.

**Comment by lgcareer** [comment]
Sql task now based on the implementation of jdbc,so support one sql in a sql task.

**Comment by DingZhengCN** [comment]
This issue submit by 2019, very glad to know if the new version supports complex HQL.

**Comment by zhongjiajie** [comment]
> 

Hi @DingZhengCN, sql task type could support complex sql, but it could not support set parameter for now. you could see answer 

> Sql task now based on the implementation of jdbc,so support one sql in a sql task.
