### ISSUE TITLE
[Bug] Passing parameters from upstream to downstream of shell node does not take effect

### ISSUE THREAD

**Issue by Leijingwen** [apache/dolphinscheduler#12185]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

A节点任务
![image](https://user-images.githubusercontent.com/88963951/192727826-963e6dd7-a010-4ba7-9278-1e7655e52e50.png)
B节点任务
![image](https://user-images.githubusercontent.com/88963951/192727918-862751fc-eb8d-4a8d-8913-21599409f562.png)

A节点输出
![image](https://user-images.githubusercontent.com/88963951/192728635-484b6694-915b-4c84-847c-4876ad97ada1.png)
B节点输出
![image](https://user-images.githubusercontent.com/88963951/192728750-1a4cfdac-c70c-447a-964b-31bd26709199.png)

### What you expected to happen

DS version are  are 3.0.0 and dev ，I want node A and node B to output '20220906'，but nothing

### How to reproduce

DS version are  are 3.0.0 and dev ，I want node A and node B to output '20220906'，but nothing

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by huangchenguang123** [comment]
For node1, setValue is not valid for itself. For node2, there is no need to set parameters. If you are the latest dev branch, please refer to my example. It may have some hidden logic to bother you.
please see https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/parameter/context.html
node1:
<img width="575" alt="image" src="https://user-images.githubusercontent.com/37766284/192934581-cf0b948f-961f-4a69-9164-bd24dc8b06f2.png">
node2:
<img width="589" alt="image" src="https://user-images.githubusercontent.com/37766284/192934964-f526a9c6-404c-433b-8fc1-97e52fe2c829.png">

DAG:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/37766284/192935016-b5e475b8-15b9-4b9b-8db6-461ee4b13419.png">
