### ISSUE TITLE
[Bug] [Log] Java Doesn't Print Log

### ISSUE THREAD

**Issue by Chris-playground** [apache/dolphinscheduler#12191]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I use shell to execute a jar file and there is no log shown on the page, only print start and end.
![image](https://user-images.githubusercontent.com/48941586/192764102-8da877df-b35e-476b-908e-4b97b070a78a.png)

### What you expected to happen

The business log should print out

### How to reproduce

use shell to execute a jar file and put some log in the code

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
this jar will print any log or not?

**Comment by Chris-playground** [comment]
> this jar will print any log or not?

yes, I put a lot of business log in the code, I can see the log when I run the code in IDEA

**Comment by DarkAssassinator** [comment]
> > this jar will print any log or not?
> 
> yes, I put a lot of business log in the code, I can see the log when I run the code in IDEA

may jar just print log to logs, but did not system out to session, so DS cannot get these logs. May u can run `java -jar your.jar`  to check if it will system out logs. thx

**Comment by Chris-Arith** [comment]
> > > this jar will print any log or not?
> > 
> > 
> > yes, I put a lot of business log in the code, I can see the log when I run the code in IDEA
> 
> may jar just print log to logs, but did not system out to session, so DS cannot get these logs. May u can run `java -jar your.jar` to check if it will system out logs. thx

pls check the snapshot below.
![image](https://user-images.githubusercontent.com/48941586/192780515-c859a9b9-de4b-4d40-8881-1160cb5027a7.png)

**Comment by Chris-playground** [comment]
> > > this jar will print any log or not?
> > 
> > 
> > yes, I put a lot of business log in the code, I can see the log when I run the code in IDEA
> 
> may jar just print log to logs, but did not system out to session, so DS cannot get these logs. May u can run `java -jar your.jar` to check if it will system out logs. thx

pls check the snapshot below, tks.
![image](https://user-images.githubusercontent.com/48941586/192780916-dd4c4263-f311-42fa-866f-b8b2a90db452.png)

**Comment by DarkAssassinator** [comment]
ok, let me check more...

**Comment by Chris-playground** [comment]
> ok, let me check more...

thanks a lot!
While I tried to use `nohup java -jar xx.jar  >./tmp.log 2>&1 &` to run the jar and use `tail -f ./tmp.log`  to tail the log.
DS will seperate this command into 2 task instances.
Goods news is that I can see the log and bad news is that the `nohup task` wouldn't stop...

**Comment by Chris-playground** [comment]
> Thank you for your feedback, we have received your issue, Please wait patiently for a reply.
> 
> * In order for us to understand your request as soon as possible, please provide detailed information、version or pictures.
> * If you haven't received a reply for a long time, you can [join our slack](https://s.apache.org/dolphinscheduler-slack) and send your question to channel `#troubleshooting`

Ok, thanks a lot. Hereby is the request infomation.
**version**: 3.0.0
**original demand**: We want to run process among different projects, so we made a jar to run processes by using http apis
**descsription**: the logs shown in IDEA but not in DS, we run the jar like this in `SHELL TYPE`
![image](https://user-images.githubusercontent.com/48941586/192786628-c9c50f1c-101e-4fe5-b8fa-666b767395af.png)

DS log like below
![image](https://user-images.githubusercontent.com/48941586/192787245-dcbb5c97-2670-40b2-b62f-7b8b7bdf0aef.png)

**Comment by DarkAssassinator** [comment]
Hi @Chris-Arith, it is working fine for me, please check the following screenshots, could u share me more worker logs?
![image](https://user-images.githubusercontent.com/20518339/192798800-defb1774-0a83-4b2f-9445-400865d2ad6f.png)
 
![image](https://user-images.githubusercontent.com/20518339/192799026-ee15621f-be24-4619-9b62-5923c574f9e5.png)

![image](https://user-images.githubusercontent.com/20518339/192799199-dd92319d-e2f7-411d-ac02-31037281333b.png)

**Comment by Chris-playground** [comment]
> Hi @Chris-Arith, it is working fine for me, please check the following screenshots, could u share me more worker logs? ![image](https://user-images.githubusercontent.com/20518339/192798800-defb1774-0a83-4b2f-9445-400865d2ad6f.png)
> 
> ![image](https://user-images.githubusercontent.com/20518339/192799026-ee15621f-be24-4619-9b62-5923c574f9e5.png)
> 
> ![image](https://user-images.githubusercontent.com/20518339/192799199-dd92319d-e2f7-411d-ac02-31037281333b.png)

I am terribly sorry that I may check the wrong task, it works now...
I made myself misunderstanding that these two task have similar names, what a stupid mistake... Sorry for wasting your valuable time.
However, maybe allowing a high authoried role to manipulate processes between different projects is a good idea as we may need to run these processes together and we don't want to defined it again.

**Comment by DarkAssassinator** [comment]
> I am terribly sorry that I may check the wrong task, it works now...
> I made myself misunderstanding that these two task have similar names, what a stupid mistake... Sorry for wasting your valuable time.

hahaha, it's ok
> However, maybe allowing a high authoried role to manipulate processes between different projects is a good idea as we may need to run these processes together and we don't want to defined it again.

Just copy to other project? Because my understanding of the project is a kind of work that has been demarcated, if a person with high authority can call the task's transformation from multiple projects, it will break this project definition. WDYT

**Comment by Chris-playground** [comment]
> Just copy to other project? Because my understanding of the project is a kind of work that has been demarcated, if a person with high authority can call the task's transformation from multiple projects, it will break this project definition. WDYT

We create projects according to business purpose. For example,  firstly, we ingest data from marketing department then resulting to an ads_xxx table after transform. After that ads_xxx will be loaded into doris, and then finance department can see the report based on doris.
These two steps belongs to different projects, sometimes finance department need the latest data, so we need to run these two processes in order and that why we use java to call DS apis manually to run these processes.
I don't know wether we use it correctly, maybe there is a better way to handle it gracefully？

**Comment by Amy0104** [comment]
It does not seem to be a bug, so I removed the bug tag.

**Comment by Chris-playground** [comment]
> It does not seem to be a bug, so I removed the bug tag.

tks
