### ISSUE TITLE
[Improvement][SPI] Remove duplicate PropertyUtils

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#12190]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Currently we have two `PropertyUtils` in both `common` and `spi` modules.
* It is hard to maintain duplicate util classes. 
* Furthermore, `PropertyUtils` in `spi` module gives some kind of initialization error when we try to mock it using `Mockito.mockStatic()`. Instead of spending time finding tricky ways to  mock it, I suggest we remove `PropertyUtils` in `spi` module.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
Looks like we will have a cyclic reference if adding `common` dependency into `task-plugin` module:

```
[ERROR] [ERROR] The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='org.apache.dolphinscheduler:dolphinscheduler-common:dev-SNAPSHOT'}' and 'Vertex{label='org.apache.dolphinscheduler:dolphinscheduler-task-api:dev-SNAPSHOT'}' introduces to cycle in the graph org.apache.dolphinscheduler:dolphinscheduler-task-api:dev-SNAPSHOT --> org.apache.dolphinscheduler:dolphinscheduler-common:dev-SNAPSHOT --> org.apache.dolphinscheduler:dolphinscheduler-task-api:dev-SNAPSHOT @ 
[ERROR] The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='org.apache.dolphinscheduler:dolphinscheduler-common:dev-SNAPSHOT'}' and 'Vertex{label='org.apache.dolphinscheduler:dolphinscheduler-task-api:dev-SNAPSHOT'}' introduces to cycle in the graph org.apache.dolphinscheduler:dolphinscheduler-task-api:dev-SNAPSHOT --> org.apache.dolphinscheduler:dolphinscheduler-common:dev-SNAPSHOT --> org.apache.dolphinscheduler:dolphinscheduler-task-api:dev-SNAPSHOT -> [Help 1]

```

![image](https://user-images.githubusercontent.com/34905992/192783331-d0c9dbdf-40c3-4547-a6c3-473ce65262ff.png)

@kezhenxu94 @ruanwenjun @caishunfeng @SbloodyS May I ask whether there are any graceful solutions to this? Thanks

**Comment by kezhenxu94** [comment]
> Looks like we will have a cyclic reference if adding `common` dependency into `task-plugin` module:
> 
> ```
> [ERROR] [ERROR] The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='org.apache.dolphinscheduler:dolphinscheduler-common:dev-SNAPSHOT'}' and 'Vertex{label='org.apache.dolphinscheduler:dolphinscheduler-task-api:dev-SNAPSHOT'}' introduces to cycle in the graph org.apache.dolphinscheduler:dolphinscheduler-task-api:dev-SNAPSHOT --> org.apache.dolphinscheduler:dolphinscheduler-common:dev-SNAPSHOT --> org.apache.dolphinscheduler:dolphinscheduler-task-api:dev-SNAPSHOT @ 
> [ERROR] The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='org.apache.dolphinscheduler:dolphinscheduler-common:dev-SNAPSHOT'}' and 'Vertex{label='org.apache.dolphinscheduler:dolphinscheduler-task-api:dev-SNAPSHOT'}' introduces to cycle in the graph org.apache.dolphinscheduler:dolphinscheduler-task-api:dev-SNAPSHOT --> org.apache.dolphinscheduler:dolphinscheduler-common:dev-SNAPSHOT --> org.apache.dolphinscheduler:dolphinscheduler-task-api:dev-SNAPSHOT -> [Help 1]
> ```
> 
> ![image](https://user-images.githubusercontent.com/34905992/192783331-d0c9dbdf-40c3-4547-a6c3-473ce65262ff.png)
> 
> @kezhenxu94 @ruanwenjun @caishunfeng @SbloodyS May I ask whether there are any graceful solutions to this? Thanks

No, it's a really bad idea to work around this even if there is a solution. There is no reason the common module should depend on the task module, anything inside common module that uses task module should be moved to task-api module.

**Comment by ruanwenjun** [comment]
How about make `task-api` rely on the common module?

**Comment by EricGao888** [comment]
> How about make `task-api` rely on the common module?

FYI, here are the files of `task-api` which `common` depends on:

```text
dolphinscheduler.plugin.task.api.enums.TaskExecutionStatus;
dolphinscheduler.plugin.task.api.enums.TaskTimeoutStrategy;
dolphinscheduler.plugin.task.api.parameters.TaskTimeoutParameter;
dolphinscheduler.plugin.task.api.enums.DataType;
dolphinscheduler.plugin.task.api.enums.Direct;
dolphinscheduler.plugin.task.api.model.Property;
dolphinscheduler.plugin.task.api.TaskConstants;
dolphinscheduler.plugin.task.api.parser.PlaceholderUtils;
dolphinscheduler.plugin.task.api.parser.TimePlaceholderUtils;
```

I need more time to look into them to see whether to move those constant and utility stuff into `common` module or move the code depend on them into `task-api` module.

**Comment by kezhenxu94** [comment]
I'm working on this to move classes in common module to more suitable modules, and remove the duplicated PropertyUtils

**Comment by EricGao888** [comment]
> I'm working on this to move classes in common module to more suitable modules, and remove the duplicated PropertyUtils

@kezhenxu94 Cool! Thanks.
