### ISSUE TITLE
[Improvement][UI] Show master/worker-server version in ui

### ISSUE THREAD

**Issue by stalary** [apache/dolphinscheduler#12201]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Show master/worker-server version in ui, This will help us determine if the upgrade is correct at upgrade time.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
@stalary @Amy0104 maybe we just need show the ```dolphinscheduler-api``` version?and show the on the page of login?
