### ISSUE TITLE
[Feature][UI] Add crontab management page in Project level.

### ISSUE THREAD

**Issue by DarkAssassinator** [apache/dolphinscheduler#12221]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Now if we want to check and manage cron task, we need to click the workflow defintion one by one.
But if there are huge workflow in one project, and user want to know how many cron task will be will difficult.
![image](https://user-images.githubusercontent.com/20518339/193069329-e51b2a9d-e30d-4b14-aada-77e85a0d0cdc.png)
Could we add a cron manage page below `Task Instance` menu? Which can manage all cron task in same project.

### Use case

User all cron task in same project.

### Related issues

N/A

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
Add a cron manage page in the security center?

**Comment by DarkAssassinator** [comment]
> Add a cron manage page in the security center?

I suggest add it in the Project Management, just below Workflow Definition

**Comment by Amy0104** [comment]
How about add a  `configuration` menu  under the first level menu?

**Comment by DarkAssassinator** [comment]
> How about add a `configuration` menu under the first level menu?

That's great. But I think this is another improvement. Because i think `Cluster, Worker Group, Environment` should not belong to Security. These should belong to `Configuration Center`.
But cron tasks should same as task and workflow, same belong to a special project. WDYT
