### ISSUE TITLE
[Bug] [python] Distribute tarball and wheel error with direct dependency

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#12238]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

During the distribution tarball release process, I run `python3 -m twine upload --repository testpypi dist/*` to upload but get error with 

```log
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
         Invalid value for requires_dist. Error: Can't have direct dependency: "sphinx-multiversion @ git+https://github.com/Holzhaus/sphinx-multiversion#egg=sphinx-multiversion ; extra == 'all'"
```

we should not raise error during the release process

### What you expected to happen

should not raise error

### How to reproduce

`python3 -m twine upload --repository testpypi dist/*`

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
May I ask whether we are going to add this patch to 3.0.2? If not, I will put it to 3.0.3.

**Comment by zhongjiajie** [comment]
will be fixed in https://github.com/apache/dolphinscheduler-sdk-python
