### ISSUE TITLE
[Bug] dolphinscheduler/resources createResource method xxx.jar  No suitable resolver

### ISSUE THREAD

**Issue by yuanyunchu** [apache/dolphinscheduler#12234]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

dolphinscheduler/resources上线服务端createResourcejar包报错
```java
exceptionHandler(Exception, HandlerMethod)
java.lang.IllegalStateException: Could not resolve parameter [1] in public org.apache.dolphinscheduler.api.utils.Result org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler.exceptionHandler(java.lang.Exception,org.springframework.web.method.HandlerMethod): No suitable resolver
```
![image](https://user-images.githubusercontent.com/33806778/193227206-b01aea89-540b-4388-8d6a-5082c58eebaa.png)

本地服务上传jar是成功的
![image](https://user-images.githubusercontent.com/33806778/193227358-0342e742-f4fa-426b-aaab-5ca7df9b3095.png)

非常不理解这是什么问题造成

### What you expected to happen

createResource xxx.jar

### How to reproduce

createResource /dolphinscheduler/resources xxx.jar

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/33984497/194710773-c2ad68d2-975c-4147-8996-799b5e702551.png">
may be under current directory ```(/text0908)``` had existed same name file which named ``` testsss.jar```

**Comment by fuchanghai** [comment]
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/33984497/194710773-c2ad68d2-975c-4147-8996-799b5e702551.png">
may be under current directory ```(/text0908)``` had existed same name file which named ``` dolphinscheduler-api-3.0.0.jar```

**Comment by yuanyunchu** [comment]
> <img alt="image" width="1494" src="https://user-images.githubusercontent.com/33984497/194710773-c2ad68d2-975c-4147-8996-799b5e702551.png">
> 
> may be under current directory ```(/text0908)``` had existed same name file which named ``` testsss.jar```
这个是上传成功的。

**Comment by yuanyunchu** [comment]
上传失败是这个
![image](https://user-images.githubusercontent.com/33806778/195806946-acbc2d03-c1d7-4df5-be0a-00b841a970b4.png)

失败信息
exceptionHandler(Exception, HandlerMethod)
java.lang.IllegalStateException: Could not resolve parameter [1] in public org.apache.dolphinscheduler.api.utils.Result org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler.exceptionHandler(java.lang.Exception,org.springframework. web.method.HandlerMethod): No suitable resolver
