### ISSUE TITLE
[Feature][UI] Enables users to customize the task display list.

### ISSUE THREAD

**Issue by ChenpiDog** [apache/dolphinscheduler#12245]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Dolphinscheduler supports more and more task types. Some task types may never be used by some users. Users can group task types (such as "machine learning") and hide or display task types at will.

### Use case

This function is only implemented in the front display interface.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ChenpiDog** [comment]
This interface
![02baed43fd5d9917b8899a172f5b57d](https://user-images.githubusercontent.com/55483982/193441926-d55d9a09-dcff-41cf-b8b2-85f02e015dd0.jpg)

**Comment by Lynnhan95** [comment]
Can I take a look at this? @ChenpiDog @songjianet

**Comment by songjianet** [comment]
We have implemented the grouping function of task components, you can check the specific changes here https://github.com/apache/dolphinscheduler/pull/11965. @ChenpiDog
