### ISSUE TITLE
[Question] [Kubernetes] After deploying DolphinScheduler with kubernetes, some problems are encountered in the use process.

### ISSUE THREAD

**Issue by ChenpiDog** [apache/dolphinscheduler#12243]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Problem 1: Problem 1: I ran a very simple Python task and reported a permission error. Even if I set the tenant as root, the problem still cannot be solved. The official website documentation is too simple, and I did not find a solution to the problem.

### What you expected to happen

1) Better support and stricter testing for DolphinScheduler on Kubernetes;
2) Now the Python task version is python 2, and I hope to directly support python 3.

### How to reproduce

The problem can be found by deploying DolphinScheduler with Kubernetes, setting up tenants, binding tenants to users, and running a simple Python task.

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ChenpiDog** [comment]
I found the same problem here #11544 , but the problem seemed to be closed without being solved.

**Comment by pandong2011** [comment]
This is a bug has been fixed, you can refer to my modification, modify your local source code, and then redeploy
#11959

**Comment by pandong2011** [comment]
This is a bug has been fixed, you can refer to my modification, modify your local source code, and then redeploy
#11959
