### ISSUE TITLE
[Bug] [Task] dependent task can not predicate the status of the corresponding task correctly

### ISSUE THREAD

**Issue by ghost** [apache/dolphinscheduler#12252]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/92249031/193997729-5be1abf4-7f77-44c3-b767-7753f866a2d2.png)
![image](https://user-images.githubusercontent.com/92249031/193997922-6e7b1e22-0c92-4688-a05e-350b8b646684.png)
![image](https://user-images.githubusercontent.com/92249031/193997975-707ee733-fab6-4e9f-83bd-b25c2b30a906.png)
![image](https://user-images.githubusercontent.com/92249031/193999301-859b5fac-7635-42cb-b3f7-b21ef6c959b5.png)

Here I have 2 workflows, workflow 01 is a simple http task, workflow 02 only contains a dependent task, which depends on the workflow01, the condition is "thisMonthBegin"

After the workflow ran successfully(on 1st Oct. I changed the date of system manually), the workflow 01 should also have ran successfully(on any day of Oct. ideally), but it failed (as the last screenshot)

Deploy mode: standalone
Metadata storage: MySQL
Version: 3.1.0
OS: CentOS7 on vmware

### What you expected to happen

the workflow 02 should run successfully

### How to reproduce

run a workflow on 1st of any month, then run another workflow which has a denpendent task that depends the former workflow and set condition with "thisMonthBegin", then run the latter workflow

### Anything else

log of the workflow 02:

```
[LOG-PATH]: /tmp/apache-dolphinscheduler-3.1.0-bin/standalone-server/logs/20221001/7061320298016_4-13-13.log, [HOST]:  Host{address='192.168.27.3:5678', ip='192.168.27.3', port=5678}
[INFO] 2022-10-01 11:22:29.646 +0800 - Dependent task submit success
[INFO] 2022-10-01 11:22:29.754 +0800 - Add sub dependent check tasks, dependent relation: AND
[INFO] 2022-10-01 11:22:29.754 +0800 - Add dependent task: projectName: test-project, workflowName: 工作流01, taskName: ALL, dependentKey: 7061314418592-0-month-thisMonthBegin
[INFO] 2022-10-01 11:22:29.755 +0800 - Success initialize dependent task parameters, the dependent data is: Sat Oct 01 11:22:29 CST 2022
[INFO] 2022-10-01 11:22:30.940 +0800 - dependent item complete, dependentKey: 7061314418592-0-month-thisMonthBegin, result: FAILED, dependentDate: Sat Oct 01 11:22:29 CST 2022
[INFO] 2022-10-01 11:22:30.941 +0800 - Dependent task completed, dependent result: FAILED
```

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zephyrcf** [comment]
@710700  Hi, I'll fix it.

**Comment by fuchanghai** [comment]
> @710700 Hi, I'll fix it.

@SbloodyS  @insist777  want to fix it

**Comment by Zephyrcf** [comment]
> 

😆, It seems that everyone is busy.
