### ISSUE TITLE
[Bug] [Alert, Master] java.lang.NoClassDefFoundError: com/amazonaws/services/s3/model/AmazonS3Exception

### ISSUE THREAD

**Issue by liqiquan** [apache/dolphinscheduler#12259]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Use the code of branch  3.1.0, compile the Docker image, deploy it on the k8s, and configure RESOURCE_ STORAGE_ TYPE=S3。 After startup, the following errors are found in the alter and master pod:

java.lang.NoClassDefFoundError: com/amazonaws/services/s3/model/AmazonS3Exception

Cause analysis: The compiled jar package of the alter and master modules lacks aws-java-sdk-s3-12.160.jar.

When aws-java-sdk-s3-12.160.jar is added and the image is repackaged and deployed, the bad pod starts normally, and the dolphin scheduler can normally read and write the file resources stored on S3.

使用3.1.0分支的代码，编译docker镜像后部署在k8s上，并配置RESOURCE_STORAGE_TYPE=S3。启动后发现alter和master pod报如下错误：
java.lang.NoClassDefFoundError: com/amazonaws/services/s3/model/AmazonS3Exception

原因分析：编译出的alter和master模块的jar包中缺少aws-java-sdk-s3-1.12.160.jar。

当添加aws-java-sdk-s3-1.12.160.jar后重新打包镜像并部署后，报错的pod正常启动，且dolphin scheduler可以正常读写S3上存储的文件资源。

### What you expected to happen

The compiled jar package of the alter and master modules lacks aws-java-sdk-s3-1.12.160.jar.

编译出的alter和master模块的jar包中，应该有aws-java-sdk-s3-1.12.160.jar

### How to reproduce

Use the code of branch 3.1.0, compile the Docker image, deploy it on the k8s, and configure RESOURCE_ STORAGE_ TYPE=S3。

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
you had fixed it? so can you pull a request to fix it?@liqiquan

**Comment by liqiquan** [comment]
@fuchanghai 

> In the common module, there is init **StoreConfiguration**.

> If RESOURCE_STORAGE_TYPE=HDFS, hadoop-related packages are required: hadoop-common&hadoop-client; RESOURCE_STORAGE_TYPE=S3, the jar of aws-java-sdk-s3 is required.`

> However, in the pom of the common module, hadoop-common&hadoop-client and aws-java-sdk-s3 have scope set to provided, thus losing transitionality. Therefore, if the packages that reference the common module need the hadoop and aws-java-sdk-s3 packages, they need to be added again separately.

> May I ask which way will be used to solve this problem?
> 1. The jars of hadoops-Common&Hadoop-Client and aws-java-sdk-s3 are added separately for modules such as master and alter.
> 
> 2. common module pom, scope without provided
> 
> 3. StoreConfiguration is no longer init in the master and alter modules

----

> 在common模块中，有init StoreConfiguration的操作。
> 如果RESOURCE_STORAGE_TYPE=HDFS，需要hadoop相关的包: hadoop-common&hadoop-client；RESOURCE_STORAGE_TYPE=S3，则需要aws-java-sdk-s3的jar。
> 但是在common模块的pom中，hadoop-common&hadoop-client和aws-java-sdk-s3的scope被设置为provided，失去了传递性，所以引用common模块的包如果需要hadoop和aws-java-sdk-s3包，需要单独再次添加。

请问针此问题，后面会采用那种方式解决：
1.master和alter等模块单独添加，hadoop-common&hadoop-client和aws-java-sdk-s3的jar。
2.common模块的pom中，scope去掉provided
3.master和alter等模块中不再init StoreConfiguration

**Comment by zhuangchong** [comment]
The master and alerter services do not use resources. The default value of `resource.storage.type=NONE` in their respective common.properties can be used. api-server and worker-server need to configure `resource.storage.type=xxx`.

**Comment by xpflying** [comment]
Our dolphinscheduler is deployed inside kubernetes, and all services of dolphinscheduler share a set of configuration files. The yaml under the code path deploy/kubernetes/dolphinscheduler also mounts the same configuration file, now we see that the alert service code in the dev branch has been removed from the resources related code, please remove the resources code from the master service as well @zhuangchong

**Comment by liqiquan** [comment]
Now, after resource.storage. type=S3 is configured, if the master service is not configured separately, the master service cannot be started.

Since it may take time for the master service to remove the relevant code, can we first add the jar of aws-java-sdk-s3 in the master module, just like configuring resource.storage.type =HDFS?

**Comment by TheWindIsRising** [comment]
dockfile 把 s3的jar包打到镜像里就可以了，我也遇到过此类问题
