### ISSUE TITLE
[Bug]2.0.6 Upgrade 3.1.0 failed

### ISSUE THREAD

**Issue by Flutemr** [apache/dolphinscheduler#12268]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Our cluster is CDH, and the zk version is 3.4.5. We plan to upgrade the DS2.0.6 version to version 3.1.0, but it shows that the registration cannot be done. It may be that the zk version does not match. What is the zk version required in 3.1.0?
The following is the error message:
![1](https://user-images.githubusercontent.com/30035663/194736033-c5e7a979-4278-4a2f-b6f3-a6b9bcf10aac.jpg)
![Uploading 2.png…]()

### What you expected to happen

How can I upgrade from 2.0.6 to 3.1.0?

### How to reproduce

no

### Anything else

no

### Version

2.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @Flutemr , you can try versions above 3.8.0.

**Comment by hstdream** [comment]
ds version 2.0.6 need zookeeper  3.4.x, but  3.0.1 need zookeeper 3.8.0.

**Comment by lordk911** [comment]
https://github.com/apache/dolphinscheduler/issues/13000#issue-1464279822
