### ISSUE TITLE
[Bug] Resouce center can not create file and directories

### ISSUE THREAD

**Issue by wangsong8586** [apache/dolphinscheduler#12267]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1)On the resouce center page, create directory failed 

### What you expected to happen

1)On the resouce center page, we should create directory successfully

### How to reproduce

1) login to the web
2)click "Resouces" tab
3)click on "Create Folder"  and enter a folder name then click "confirm" button.
![image](https://user-images.githubusercontent.com/25869159/194734684-1cdf9ec4-505e-4bdd-a6c5-bde3064acf9a.png)

4) from the api-server log, it also shows errors
![image](https://user-images.githubusercontent.com/25869159/194734701-d3c15f5c-1ab2-49bb-a989-07e7474acf33.png)

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangsong8586** [comment]
The user has full privileges on hdfs root

**Comment by liusy-bd** [comment]
3.1.0  我也是这个问题 换到3.0.0 可以了

**Comment by wangsong8586** [comment]
> 3.1.0 我也是这个问题 换到3.0.0 可以了

Yes, I change back to 3.0 and everything runs normal

**Comment by EricGao888** [comment]
@wangsong8586 Could u plz post your `common.properties`?

**Comment by wangsong8586** [comment]
> @wangsong8586 Could u plz post your `common.properties`?
[common.properties.txt](https://github.com/apache/dolphinscheduler/files/9740858/common.properties.txt)

**Comment by wangsong8586** [comment]
HDFS super user is dolphinscheduler(os user) , and  the hdfs processes are started by dolphinscheduler

> > @wangsong8586 Could u plz post your `common.properties`?
> > [common.properties.txt](https://github.com/apache/dolphinscheduler/files/9740858/common.properties.txt)

HDFS super user is dolphinscheduler(os user) , and  the hdfs processes are started by dolphinscheduler

**Comment by EricGao888** [comment]
I just checked the dev branch, things worked fine. I will double-check the 3.1.0 branch later.

**Comment by wangsong8586** [comment]
I tried both upgrading from 3.0 to 3.1.0 and newly installed 3.1.0,  the same problem occurs

**Comment by wangsong8586** [comment]
Hello, any progress?

**Comment by EricGao888** [comment]
> Hello, any progress?

@rickchengx Could u plz help take a look? Thx

**Comment by rickchengx** [comment]
> > Hello, any progress?
> 
> @rickchengx Could u plz help take a look? Thx

Sure.

**Comment by rickchengx** [comment]
@EricGao888 @wangsong8586 It seems that user can not create file and directories in 3.1.0. My test results are the same.
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/38122586/195086597-f8e34cf4-3f55-4512-a9d9-979d843e19cc.png">

**Comment by EricGao888** [comment]
> @EricGao888 @wangsong8586 It seems that user can not create file and directories in 3.1.0. My test results are the same. <img alt="image" width="1358" src="https://user-images.githubusercontent.com/38122586/195086597-f8e34cf4-3f55-4512-a9d9-979d843e19cc.png">

Got it, thx

**Comment by ruanwenjun** [comment]
@wangsong8586 @rickchengx Hi, I checked the code, find the config key has changed in 3.1.x, could you please try to follow this PR to fix this?

https://github.com/apache/dolphinscheduler/pull/11823/files

**Comment by zhuangchong** [comment]
I will close this issue first, if you have questions, you can open it again.
