### ISSUE TITLE
Why delete the Resource Center repeat file upload function in version 3.0.1 ?

### ISSUE THREAD

**Issue by liusy-bd** [apache/dolphinscheduler#12269]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Why delete the Resource Center repeat file upload function in version 3.0.1 ?

The task flow that causes the jar package to go online needs to go offline before it can be uploaded. If a jar package has dozens of tasks in different task flows, how troublesome is this operation

### Use case

![image](https://user-images.githubusercontent.com/69708156/194736716-9fcb9dcb-2cfc-4a2d-b77b-22c3a9df11ac.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liusy-bd** [comment]
![8c2769d2ef21a63ee8ec6ea912e4923](https://user-images.githubusercontent.com/69708156/194736773-918918c1-8b1e-42a5-9d13-1cd0d933962d.jpg)

**Comment by EricGao888** [comment]
If u update the resource using by multiple online workflow definition, how could u know which version of the resource will be used by those workflow instances? This may cause inconsistency and unexpected issue.

**Comment by EricGao888** [comment]
If u update the resource using by multiple online workflow definition, how could u know which version of the resource will be used by those workflow instances? This may cause inconsistency and unexpected issue.

**Comment by liusy-bd** [comment]
> 如果您使用多个在线工作流定义更新资源，您怎么知道这些工作流实例将使用哪个版本的资源？这可能会导致不一致和意外问题。
There should also be a button to unify the JAR tasks. Otherwise, if I have eight tasks and a new task is added and the eight tasks are not changed, do I need to repeat the online operation to upload the JAR

**Comment by liusy-bd** [comment]
> If u update the resource using by multiple online workflow definition, how could u know which version of the resource will be used by those workflow instances? This may cause inconsistency and unexpected issue.

There should also be a button to unify the JAR tasks. Otherwise, if I have eight tasks and a new task is added and the eight tasks are not changed, do I need to repeat the online operation to upload the JAR

**Comment by EricGao888** [comment]
> > If u update the resource using by multiple online workflow definition, how could u know which version of the resource will be used by those workflow instances? This may cause inconsistency and unexpected issue.
> 
> There should also be a button to unify the JAR tasks. Otherwise, if I have eight tasks and a new task is added and the eight tasks are not changed, do I need to repeat the online operation to upload the JAR

Well, I think this is reasonable. Would you like to submit a PR for this?
