### ISSUE TITLE
[Improvement][UI] the process name or task name is not displayed completely

### ISSUE THREAD

**Issue by liqiquan** [apache/dolphinscheduler#12260]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

On the task definition page, the task name is not displayed completely. If the name is very short, it will not even be displayed.

A string of the same length should be displayed.

The font box should be larger, like the 2. x UI.

 任务定义页面，任务名称显示不全，如果名称很短的话，甚至会不显示名称。
 应该显示一样长度的字符串。
 字体框最好可以再大一些，就像2.x的版本的ui。

![企业微信截图_16641817682083](https://user-images.githubusercontent.com/22407119/194702713-af37e881-be0b-44c5-bd7e-b6947c2b7817.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/33984497/194710547-c05061d8-9911-4406-9ca6-2a908c29a297.png">
it's seem good on my computer

**Comment by Zephyrcf** [comment]
Browser problem, just change to Google Browser.

**Comment by liqiquan** [comment]
We used the 3.1.0 version of the UI to test. Because the name is too short, the problem of displaying completion no longer exists.However, when the name is greater than 22 characters, the end of the name will not be displayed completely.

Compared with version 2. x, at least 32 characters are displayed. 1. x version, displaying at least 60 characters. In addition, 1. x and 2. x will display more characters as the browser page zooms to less than 100%

At present, the characters displayed in the 3.1.0 UI are too short and cannot be displayed more characters as the page scale decreases, so it is not convenient to find tasks in the UI.

我们使用3.1.0版本的ui测试，由于名称过短而显示补全的问题已经不存在了。但是当名称大于22个字符，名称结尾的就显示不全了。

对比2.x版本，至少显示32字符。1.x版本，至少显示60个字符。而且1.x和2.x会随着浏览器页面缩放小于100%，从而显示更多的字符

目前3.1.0的ui，显示的字符过短，且不能随页面比例缩小显示更多字符，所以不方便在ui查找task。
希望ui中的名称能至少显示40个字符，且最好也能随页面缩放显示更多字符

-- version 3.1.0
![image](https://user-images.githubusercontent.com/22407119/194809229-913d5887-9de9-4c5a-b7ac-5f85d8da8404.png)
-- version 1.4.5
![image](https://user-images.githubusercontent.com/22407119/194809327-55e34fd2-f809-41b3-95b0-d9431f70fc4a.png)

**Comment by liqiquan** [comment]
> <img alt="image" width="603" src="https://user-images.githubusercontent.com/33984497/194710547-c05061d8-9911-4406-9ca6-2a908c29a297.png">
> 
> it's seem good on my computer

@fuchanghai @insist777 
We used the 3.1.0 version of the UI to test. The problem of incomplete display due to short names no longer exists. However, when the name is greater than 22 characters, the following characters will not be displayed.
Whether it is possible to optimize the display of at least 40 characters, and it is better to display more characters as the page zoomss

我们使用3.1.0版本的ui测试，由于名称过短而显示不全的问题已经不存在了。但是当名称大于22个字符，后面的字符就不显示了。
是否可以优化至少显示40个字符，且最好也能随页面缩放显示更多字符
