### ISSUE TITLE
[Doc][Installation] Wrong version of zookeeper

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#12284]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Should be 3.8.0 at least.

### Documentation Links

https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/installation/pseudo-cluster.html

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tuchg** [comment]
@EricGao888 @SbloodyS hi, i want to try

**Comment by SbloodyS** [comment]
> @EricGao888 @SbloodyS hi, i want to try

Great. I've assigned to you. Looking forward to your contribution.

**Comment by tuchg** [comment]
> > @EricGao888 @SbloodyS hi, i want to try
> 
> Great. I've assigned to you. Looking forward to your contribution.

thx. it's done
