### ISSUE TITLE
[BUG] Python task Permission denied

### ISSUE THREAD

**Issue by jianghanfen** [apache/dolphinscheduler#12283]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![30edf482014451849b4e38cfaf92509](https://user-images.githubusercontent.com/39332638/194789101-a300dc58-f1e2-4ecc-8ee4-12c80242bead.jpg)
![8543fc64d0befc7a2d2e8172249ed15](https://user-images.githubusercontent.com/39332638/194789104-77b9111f-983f-4c61-a0bf-a352bbaa8fef.jpg)
![6e610e2694f32fd49d72388d2cdb5e7](https://user-images.githubusercontent.com/39332638/194789110-ed746da9-a7e7-4f0c-afc7-0c78891459ba.jpg)
python task Permission denied

### What you expected to happen

怎么解决？

### How to reproduce

k8s上部署后，创建python任务，执行报错Permission denied

### Version

3.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wl4g** [comment]
I also encountered this problem, has it been fixed yet?

**Comment by yangle123** [comment]
I ran using k8s and also encountered this issue.
1. tenant_code is "default", and set to "root"
2. common.properties set sudo.enable=false

**Comment by Ishani-Gupta** [comment]
I have seen this simialr issue. How to fix this?
