### ISSUE TITLE
[Improvement][Test] Close static mock

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#12296]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* In some UT cases, static mocks are not closed after used. This may cause unexpected UT failure. The best practice is to handle it with `try-with-resource`, see the code below for an example:

https://github.com/apache/dolphinscheduler/blob/a973054950b3964d439597023e7f9471bbbf95fe/dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/FileUtilsTest.java#L39-L43

* related: #11405

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rickchengx** [comment]
interested

**Comment by EricGao888** [comment]
> interested

Great, thx for help.
