### ISSUE TITLE
[Improvement][UI] The global variable of process cannot be null

### ISSUE THREAD

**Issue by liqiquan** [apache/dolphinscheduler#12305]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In version 3.1.0, the global variable of process cannot be null. Is there any design consideration?

For some processes, the value of the global variable is not fixed, so we do not set the default value of the global variable when defining the process, and the determined value of the global variable will be passed in when calling the run api.

Compared with 2. x and 1. x versions, global variables can be set to null.

![image](https://user-images.githubusercontent.com/22407119/195012783-c68233ee-9389-4aa0-8b12-9fac0eb8e1a3.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Please confirm if this issue exists in 30x and dev.

**Comment by liqiquan** [comment]
I tested the dev branch (the last submission time was Oct 20 10:31:16) and still had this problem
![image](https://user-images.githubusercontent.com/22407119/197141419-090ce76c-6892-4317-854b-699647575f43.png)
