### ISSUE TITLE
[Bug] [UI]The password item always is disabled

### ISSUE THREAD

**Issue by LeanLeeOne** [apache/dolphinscheduler#12306]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/29997678/195035243-312e8e7c-f25c-4280-a0eb-d81a645c9e6a.png)
As shown in the figure above，the password item always is disabled.

### What you expected to happen

As shown in the figure below，I checked the source and find that it's disabled because the `securityConfigType` is null, and the `securityConfigType` is null because browser doesn't save it on the local after invoke the method `login()` and the method `getUserInfo()` never return `securityConfigType`.
![image](https://user-images.githubusercontent.com/29997678/195036158-bf9005c8-b0cf-4500-8fb0-b6b9635a2596.png)

### How to reproduce

100% reproduce

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lyn916** [comment]
Waiting for reply

**Comment by songjianet** [comment]
please check this https://github.com/apache/dolphinscheduler/pull/11029. When developing this function, the return of this field is not null, please provide the parameters returned by the following interface. @LeanLeeOne

**Comment by LeanLeeOne** [comment]
@songjianet Here is the parameters：
1. the interface `/dolphinscheduler/login`
![image](https://user-images.githubusercontent.com/29997678/196359880-a5fb2b00-c6d2-40f7-8f66-dd8f2d91b45f.png)
![image](https://user-images.githubusercontent.com/29997678/196361782-38719086-3d60-4d44-a759-0a5693a00745.png)
2. the interface `/dolphinscheduler/users/get-user-info`
![image](https://user-images.githubusercontent.com/29997678/196361878-9fec0055-5ef3-4f36-bde0-63ce970540ae.png)
![image](https://user-images.githubusercontent.com/29997678/196362100-c06993be-c462-46ea-b154-fb8b2d887075.png)
3. the Local Storage
![image](https://user-images.githubusercontent.com/29997678/196362382-6d4cd684-77bf-45e3-a514-9a42a7833d79.png)
