### ISSUE TITLE
[Bug] [Doc] Code Style is a Dead link 

### ISSUE THREAD

**Issue by DarkAssassinator** [apache/dolphinscheduler#12318]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when i click the `Code Style`, found it is a dead link.
![image](https://user-images.githubusercontent.com/20518339/195106426-5bb61b77-07d2-4f9d-873a-b3a88889d301.png)

![image](https://user-images.githubusercontent.com/20518339/195106325-67e088ac-ed01-47c9-ba5d-ac8b13170d3f.png)

### What you expected to happen

this should be a correct link

### How to reproduce

just click it.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
but in zh doc, it's working fine. but Official Website is not

**Comment by EricGao888** [comment]
Not only the link for `code style`, actually all the hyper links created with `.md#xxx` in docs fail, such as https://github.com/apache/dolphinscheduler/blob/04e1b88c1c423ca9216af34539cdedf1ac405e82/docs/docs/en/guide/task/chunjun.md?plain=1#L14

Need to find out why.

**Comment by EricGao888** [comment]
@DarkAssassinator One hotfix is to global search `.md#` in the `docs` folder and remove all `#xxxx`.

**Comment by DarkAssassinator** [comment]
> Not only the link for `code style`, actually all the hyper links created with `.md#xxx` in docs fail, such as
> 
> https://github.com/apache/dolphinscheduler/blob/04e1b88c1c423ca9216af34539cdedf1ac405e82/docs/docs/en/guide/task/chunjun.md?plain=1#L14
> 
> Need to find out why.

ohh right, but i don't know the reason, as i know,  this link should working fine.
