### ISSUE TITLE
[Bug] [dolphinscheduler-dao] Upgrade to 3.1.0 release version: t_ds_worker_group do not contain field 'description'

### ISSUE THREAD

**Issue by gwdgithubnom** [apache/dolphinscheduler#12314]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when save a new work group, it always alert an error.
![1](https://user-images.githubusercontent.com/13328198/195082279-f87f1486-b6cf-47a2-b9d8-5ecfb068ab69.png)

happend in the error log：
![2](https://user-images.githubusercontent.com/13328198/195082418-7e1937d5-b993-4dd7-a51c-6ce51081d854.png)

### What you expected to happen

Cannot save a new work group, we think the ds work not correct cause by upgrade system script. It was refered in issue #11765.
https://github.com/apache/dolphinscheduler/commits/dev/dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/WorkerGroup.java 
And in pull request #11542, we found it integrated with 3.1.0, but upgrade schema code [did not exist upgrade code](https://github.com/apache/dolphinscheduler/tree/dev/dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.0_schema).

In upgrade sql code, it only contain add field other_params_json. 
![image](https://user-images.githubusercontent.com/13328198/195084573-a53e05b5-ca17-4a2b-be4e-1b90dc5b4474.png)

### How to reproduce

1、dolphinscheduler version under 3.1.0
2、upgrade dolphinscheduler to 3.1.0+
3、do save a new work group in Security > Work Group Manage > Create Worker Group > Confirm.

### Anything else

Only when ds system(under 3.1.0 version) upgrade to 3.1.0+

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Please confirm if this issue exists in 30x and dev.

**Comment by gwdgithubnom** [comment]
> Please confirm if this issue exists in 30x and dev.

This is caused in 30x and dev has no upgrade code.
