### ISSUE TITLE
[Bug] workflow state is FAILURE when last task node is forbidden

### ISSUE THREAD

**Issue by zj619** [apache/dolphinscheduler#12325]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/40164590/195226631-9ec2b01a-79ad-4fb2-b67b-d40cf64bd2cc.png)
![image](https://user-images.githubusercontent.com/40164590/195226676-f7d1eca6-8555-4160-a696-0f11324fae1e.png)
![image](https://user-images.githubusercontent.com/40164590/195226697-bb5e0bc0-1721-4ef9-bfaa-1559f3eff634.png)
for example,a workflow has two nodes and the last node is forbiddened to run,the first node gets error,but the whole workflow is successful.

### What you expected to happen

the whole workflow state is FAILURE

### How to reproduce

create a workflow has two nodes,  set the first node throws exception,set the last node  forbidden ,then start the workerflow.
The first node gets FAILURE,but the whole workflow is successful.

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
yes, i can repreduce, i will check it and try to fix it.

**Comment by songjianet** [comment]
Please confirm if this issue exists in 30x and dev.

**Comment by songjianet** [comment]
> yes, i can repreduce, i will check it and try to fix it.

Thanks.

**Comment by caishunfeng** [comment]
> Please confirm if this issue exists in 30x and dev.

I found it exist in 3.0.1 too, see https://github.com/apache/dolphinscheduler/blob/0317c70496055b66e637b588ca7d0cdb674e7138/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java#L376-L388
