### ISSUE TITLE
[Bug] [dolphinscheduler-api] Optional query parameter is primitive type without default value

### ISSUE THREAD

**Issue by zuzuviewer** [apache/dolphinscheduler#12339]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

'PUT /projects/{projectCode}/schedules/{id}' and 'PUT /projects/{projectCode}/schedules/update/{code}' have optinal int query parameter 'warningGroupId' without default value, so request these without query parameter 'warningGroupId' will throw exception

### What you expected to happen

success request without query parameter 'warningGroupId'

### How to reproduce

request without query parameter 'warningGroupId'

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Please confirm if this issue exists in 30x and dev.
