### ISSUE TITLE
[Improvement][API] Use springdoc-openapi to replace springfox

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#12331]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Since springfox will not update.

related doc: https://springdoc.org

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
@ruanwenjun like following?
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/33984497/195266707-bc1e064a-88eb-43ff-8bc3-6b104cb960bb.png">
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/33984497/195266914-575d1a0c-f91d-497e-891c-4f87b194f59b.png">

**Comment by ruanwenjun** [comment]
> @ruanwenjun like following?
> <img alt="image" width="1438" src="https://user-images.githubusercontent.com/33984497/195266707-bc1e064a-88eb-43ff-8bc3-6b104cb960bb.png">
> <img alt="image" width="1186" src="https://user-images.githubusercontent.com/33984497/195266914-575d1a0c-f91d-497e-891c-4f87b194f59b.png">

Yes

**Comment by fuchanghai** [comment]
@ruanwenjun plz assign to me, i'll improvement it
