### ISSUE TITLE
[Bug] [sql task pulgin] After the oracle user password is changed, the oracle user will be locked after the synchronization change in the data source center

### ISSUE THREAD

**Issue by lugela** [apache/dolphinscheduler#12349]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After the oracle password of the database data source is updated and the data source center is changed at the same time, it is found that the used connection pool has cached the old password, which causes the database user to be locked due to multiple connections with the old password

for example
![0a3a6185cad4c37c80e554b4463bb00](https://user-images.githubusercontent.com/18652779/195514202-909f8176-4ebd-4f89-88b6-d9c521937898.jpg)

### What you expected to happen

After the oracle password of the database data source is updated and the data source center is changed at the same time, it is found that the used connection pool has cached the old password, which causes the database user to be locked due to multiple connections with the old password

### How to reproduce

no

### Anything else

no

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Good catch, when we update the password, we need to notify the worker to expire their old datasource.

**Comment by xdu-chenrj** [comment]
Does anyone want to repair this bug? If not, I want to repair this bug

**Comment by lugela** [comment]
> Does anyone want to repair this bug? If not, I want to repair this bug

I don't have a good idea at the moment

**Comment by zhongjiajie** [comment]
@xdu-chenrj Hi, I assign to you now

**Comment by xdu-chenrj** [comment]
> > Does anyone want to repair this bug? If not, I want to repair this bug
> 
> I don't have a good idea at the moment

Maybe we can do it together

**Comment by fuchanghai** [comment]
> > > Does anyone want to repair this bug? If not, I want to repair this bug
> > 
> > 
> > I don't have a good idea at the moment
> 
> Maybe we can do it together



> > Does anyone want to repair this bug? If not, I want to repair this bug
> 
> I don't have a good idea at the moment

maybe you can refer to the interface ```/projects/{projectCode}/executors/execute```
