### ISSUE TITLE
[Bug] [Python] Task python class description error in Python API

### ISSUE THREAD

**Issue by xdu-chenrj** [apache/dolphinscheduler#12359]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Error in description of task python class in Python API

### What you expected to happen

just class description error

### How to reproduce

just class description error

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Looking forward your contribution 👍

**Comment by EricGao888** [comment]
@xdu-chenrj May I ask which PR closes this issue? Seems PR not linked.

**Comment by xdu-chenrj** [comment]
> @xdu-chenrj May I ask which PR closes this issue? Seems PR not linked.

Sorry, I didn't follow the process. I didn't create an issue and chatted privately with the administrator. The problem has been solved

**Comment by EricGao888** [comment]
> > @xdu-chenrj May I ask which PR closes this issue? Seems PR not linked.
> 
> Sorry, I didn't follow the process. I didn't create an issue and chatted privately with the administrator. The problem has been solved

I'm preparing for the 3.0.2 release, and this issue is tagged with 3.0.2 milestone, which means I need to cherry-pick the related PR. Could u plz link the PR to this issue, or just simply give me the PR number?
