### ISSUE TITLE
[Bug] [master] When I complement data by serial execution, after a failed process instance, subsequent process instances are not generated

### ISSUE THREAD

**Issue by wcmolin** [apache/dolphinscheduler#12361]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I complement data by serial execution, after a failed process instance, subsequent process instances are not generated.

For example, if I choose to complement data for 3 days, it fails on the second day, and the process instance on the third day is not generated.

### What you expected to happen

Generate 3 process instances, 2 succeed and 1 fail

### How to reproduce

Create a shell task node, and add a local param: rq = ${system.biz.curdate}

this is shell content:
```
echo rq=${rq}
if [  ${rq} -eq 20221013 ]
then
    exit 113
else
    echo success
fi
```
Run complement data by serial execution, scheduled time is ``2022-10-12 00:00:00~2022-10-14 00:00:00``.

### Version

2.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by einsteinict** [comment]
Have this problem be fixed？I met probably the same problem when completment data in parallel.
