### ISSUE TITLE
[Bug] [UI] When creating a workflow, click Data Quality or Machine Learning to expand both

### ISSUE THREAD

**Issue by pandong2011** [apache/dolphinscheduler#12364]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When creating a workflow, click Data Quality or Machine Learning in the sidebar to expand both

<img width="1158" alt="dqandml" src="https://user-images.githubusercontent.com/100667564/195637121-bc6d2b3d-4aad-4931-8d14-4ef5dce2a6c4.png">

### What you expected to happen

When creating a workflow, click Data Quality or Machine Learning in the sidebar to expand the corresponding menu

### How to reproduce

as mentioned above

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Please confirm if this issue exists in 30x and 31x.

**Comment by pandong2011** [comment]
> Please confirm if this issue exists in 30x and 31x.

3.0.x and 3.1.x do not have this problem, because the previous workflow creation did not classify the tasks in the sidebar
![Uploading v3.1.1.jpg…]()

**Comment by pandong2011** [comment]
> Please confirm if this issue exists in 30x and 31x.

3.0.x and 3.1.x do not have this problem, because the previous workflow creation did not classify the tasks in the sidebar
![v3 1 1](https://user-images.githubusercontent.com/100667564/196212929-c8fcfa83-cbb7-4aa9-94ad-3303b3b70e91.jpg)
