### ISSUE TITLE
[Bug] [Failed to start dolphinscheduler service] Failed to start master server, worker server, api server.

### ISSUE THREAD

**Issue by Gagepmd** [apache/dolphinscheduler#12375]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When you start api server, master server, and worker server, you will be prompted that the registration failed. The log screenshot is as follows:
![779830ee1f8bcab6a7af0f568ae6ccb](https://user-images.githubusercontent.com/111988192/195757062-ce6e4465-7072-4b21-ad16-01e40da7c7ab.jpg)
![1a1cc9b4cf3c09fc7cec33424f04bc2](https://user-images.githubusercontent.com/111988192/195757072-16b7665c-be91-4409-ba6a-47630259e0ec.jpg)
The zookeeper service starts normally. The screenshot is as follows:
![image](https://user-images.githubusercontent.com/111988192/195757421-c46bd36a-f619-416c-89a9-0f2513be668d.png)

### What you expected to happen

Service startup is normal.

### How to reproduce

Start dolphinscheduler api server, master server, and worker server to view the running logs

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Gagepmd** [comment]
There is a problem with the version of zookeeper. Upgrading the version of zk can solve this problem

**Comment by Chris-playground** [comment]
> There is a problem with the version of zookeeper. Upgrading the version of zk can solve this problem

I also met up with this problem, it was quite a confusing problem for people who only checked the updating manual.
It would be better to mention it in updating part.
