### ISSUE TITLE
[Bug] [api-service] Tenant user run Workflow  WorkerGroups  can't find admin add  other Worker Group list

### ISSUE THREAD

**Issue by ChewJ404** [apache/dolphinscheduler#12377]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

version :3.1.0

 admin  add new  Workflow  

![image](https://user-images.githubusercontent.com/10162958/195767028-077eacf9-6f67-468e-9d18-7fa77b2edf1f.png)

tenant user  hadoop   run  Workflow  

![image](https://user-images.githubusercontent.com/10162958/195767111-983adf37-4911-4dba-9bfa-5b1635755099.png)

### What you expected to happen

 i can Read the The source code  find    use this  api 
`dolphinscheduler/worker-groups/all`

WorkerGroupServiceImpl.queryAllGroup
![image](https://user-images.githubusercontent.com/10162958/195767390-71ab1801-8c56-435f-b61e-e06f792124a7.png)

ResourceAcquisitionAndPermissionCheck.userOwnedResourceIdsAcquisition

![image](https://user-images.githubusercontent.com/10162958/195767498-3be2a538-5fb6-43d3-ac83-f29dd60c9fa2.png)

if use  tenant user   only  return ` Collections.emptySet();` why  ???  i can  find  subsequent  worker-groups add ZOOKEEPER  `/dolphinscheduler/nodes/worker/`

![image](https://user-images.githubusercontent.com/10162958/195767943-274ccb03-9a44-499a-ba8c-b21d1dced086.png)

### How to reproduce

 I used to use version 2.0   Tenant user  can find  admin add new WorkerGroups  

How can I discover newly added  WorkerGroups  

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hstdream** [comment]
Only the administrator has the corresponding information here.

**Comment by ChewJ404** [comment]
> Only the administrator has the corresponding information here.

How can I add  newly WorkerGroups   for    tenant user ????? 

i can try  add ZOOKEEPER  node information   
![image](https://user-images.githubusercontent.com/10162958/195790455-07646723-bfee-4e63-b5b7-18d1db10eb7f.png)

 Tenant user  had find  new  WorkerGroups   
![image](https://user-images.githubusercontent.com/10162958/195790679-cd665dc7-c9a2-45c5-93bf-ea7388364b8d.png)

**Comment by ChewJ404** [comment]
举个例子  比如说我指定一个租户 只能跑在 指定的 WorkerGroups  ,在后台添加  WorkerGroups  ,租户看不到指定WorkerGroups  
那不是 相当于 WorkerGroups   功能只能 管理员用了吗

**Comment by songjianet** [comment]
Please confirm if this issue exists in 30x and dev.

**Comment by songjianet** [comment]
> 举个例子 比如说我指定一个租户 只能跑在 指定的 WorkerGroups ,在后台添加 WorkerGroups ,租户看不到指定WorkerGroups 那不是 相当于 WorkerGroups 功能只能 管理员用了吗

Please use english.
