### ISSUE TITLE
[Improvement][k8s] Update the deprecated k8s api 

### ISSUE THREAD

**Issue by rickchengx** [apache/dolphinscheduler#12372]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Update the deprecated k8s api 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
Since K8S task plugin was released in 3.1.0 and no classes will use K8sUtils in 3.0.x, I think this PR might be better cherry-picked to 3.1.x or 3.2.0 instead of 3.0.2.
