### ISSUE TITLE
[Doc] [python] Not Found Error at https://dolphinscheduler.apache.org/python/tasks/shell.html#example 

### ISSUE THREAD

**Issue by highb33kay** [apache/dolphinscheduler#12378]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The Url Linked to this issue Is not responding. #8955 

### Documentation Links

https://dolphinscheduler.apache.org/python/tasks/shell.html#example

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by john8628** [comment]
can you assign me? I wiil try it ;

**Comment by highb33kay** [comment]
Correct Url is https://dolphinscheduler.apache.org/python/dev/tasks/shell.html#example . I dont think there is any need to make a Pr. #8955

**Comment by jieguangzhou** [comment]
> can you assign me? I wiil try it ;

Sorry, the issue is closed, If you want to do some quick code contributions, you can pick the issue you like in this link.

https://github.com/apache/dolphinscheduler/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by john8628** [comment]
Ok ,thanks
