### ISSUE TITLE
[Bug] [dolphinscheduler-worker] Worker registry client start up error 

### ISSUE THREAD

**Issue by lihjChina** [apache/dolphinscheduler#12380]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

use the mysql registry.found error like this

### What you expected to happen

[WARN] 2022-10-14 16:31:15.088 +0800 org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext:[591] - [WorkflowInstance-0][TaskInstance-0] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'workerServer': Invocation of init method failed; nested exception is org.apache.dolphinscheduler.registry.api.RegistryException: Worker registry client start up error
Related cause: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'taskExecuteResultMessageSender': Unsatisfied dependency expressed through field 'workerRpcClient'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workerRpcClient': Unsatisfied dependency expressed through field 'taskExecuteRunningAckProcessor'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'taskExecuteRunningAckProcessor': Unsatisfied dependency expressed through field 'messageRetryRunner'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'messageRetryRunner': Requested bean is currently in creation: Is there an unresolvable circular reference?
Related cause: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'taskExecuteRunningMessageSender': Unsatisfied dependency expressed through field 'workerRpcClient'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workerRpcClient': Unsatisfied dependency expressed through field 'taskExecuteRunningAckProcessor'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'taskExecuteRunningAckProcessor': Unsatisfied dependency expressed through field 'messageRetryRunner'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'messageRetryRunner': Requested bean is currently in creation: Is there an unresolvable circular reference?
Related cause: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'taskRejectMessageSender': Unsatisfied dependency expressed through field 'workerRpcClient'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workerRpcClient': Unsatisfied dependency expressed through field 'taskExecuteRunningAckProcessor'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'taskExecuteRunningAckProcessor': Unsatisfied dependency expressed through field 'messageRetryRunner'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'messageRetryRunner': Requested bean is currently in creation: Is there an unresolvable circular reference?
[WARN] 2022-10-14 16:31:15.089 +0800 org.apache.dolphinscheduler.common.model.BaseHeartBeatTask:[69] - [WorkflowInstance-0][TaskInstance-0] - WorkerHeartBeatTask task finished
[INFO] 2022-10-14 16:31:15.089 +0800 org.apache.dolphinscheduler.plugin.registry.mysql.MysqlRegistry:[189] - [WorkflowInstance-0][TaskInstance-0] - Closing Mysql Registry...
[INFO] 2022-10-14 16:31:15.090 +0800 com.zaxxer.hikari.HikariDataSource:[350] - [WorkflowInstance-0][TaskInstance-0] - MysqlRegistryDataSourcePool - Shutdown initiated...
[INFO] 2022-10-14 16:31:15.109 +0800 com.zaxxer.hikari.HikariDataSource:[352] - [WorkflowInstance-0][TaskInstance-0] - MysqlRegistryDataSourcePool - Shutdown completed.
[INFO] 2022-10-14 16:31:15.110 +0800 org.apache.dolphinscheduler.plugin.registry.mysql.MysqlRegistry:[199] - [WorkflowInstance-0][TaskInstance-0] - Closed Mysql Registry...
[INFO] 2022-10-14 16:31:15.111 +0800 org.apache.dolphinscheduler.server.worker.registry.WorkerRegistryClient:[113] - [WorkflowInstance-0][TaskInstance-0] - Worker registry client closed
[INFO] 2022-10-14 16:31:15.112 +0800 org.apache.dolphinscheduler.server.worker.rpc.WorkerRpcServer:[98] - [WorkflowInstance-0][TaskInstance-0] - Worker rpc server closing
[INFO] 2022-10-14 16:31:15.114 +0800 org.apache.dolphinscheduler.remote.NettyRemotingServer:[212] - [WorkflowInstance-0][TaskInstance-0] - netty server closed
[INFO] 2022-10-14 16:31:15.115 +0800 org.apache.dolphinscheduler.server.worker.rpc.WorkerRpcServer:[100] - [WorkflowInstance-0][TaskInstance-0] - Worker rpc server closed
[INFO] 2022-10-14 16:31:15.115 +0800 org.apache.dolphinscheduler.server.worker.rpc.WorkerRpcClient:[71] - [WorkflowInstance-0][TaskInstance-0] - Worker rpc client closing
[INFO] 2022-10-14 16:31:15.118 +0800 org.apache.dolphinscheduler.remote.NettyRemotingClient:[390] - [WorkflowInstance-0][TaskInstance-0] - netty client closed
[INFO] 2022-10-14 16:31:15.118 +0800 org.apache.dolphinscheduler.server.worker.rpc.WorkerRpcClient:[73] - [WorkflowInstance-0][TaskInstance-0] - Worker rpc client closed
[INFO] 2022-10-14 16:31:15.118 +0800 org.apache.dolphinscheduler.plugin.registry.mysql.MysqlRegistry:[189] - [WorkflowInstance-0][TaskInstance-0] - Closing Mysql Registry...
[INFO] 2022-10-14 16:31:15.118 +0800 org.apache.dolphinscheduler.plugin.registry.mysql.MysqlRegistry:[199] - [WorkflowInstance-0][TaskInstance-0] - Closed Mysql Registry...
[WARN] 2022-10-14 16:31:15.119 +0800 org.apache.dolphinscheduler.service.alert.AlertClientService:[76] - [WorkflowInstance-0][TaskInstance-0] - Alert client is already closed
[WARN] 2022-10-14 16:31:15.121 +0800 org.springframework.beans.factory.support.DisposableBeanAdapter:[248] - [WorkflowInstance-0][TaskInstance-0] - Invocation of close method failed on bean with name 'springApplicationContext': org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'applicationAvailability': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
[INFO] 2022-10-14 16:31:15.125 +0800 org.eclipse.jetty.server.session:[149] - [WorkflowInstance-0][TaskInstance-0] - node0 Stopped scavenging
[INFO] 2022-10-14 16:31:15.126 +0800 org.eclipse.jetty.server.handler.ContextHandler:[1159] - [WorkflowInstance-0][TaskInstance-0] - Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@685e6a68{application,/,[file:///tmp/jetty-docbase.1235.4011951258952071028/],STOPPED}
[INFO] 2022-10-14 16:31:15.143 +0800 org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener:[136] - [WorkflowInstance-0][TaskInstance-0] - 

### How to reproduce

at the Cluster mode

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lihjChina** [comment]
version is 3.1.0
this is the all error messages
[
[1.txt](https://github.com/apache/dolphinscheduler/files/9784717/1.txt)
](url)
thanks

**Comment by pandong2011** [comment]
because your registry is mysql, the worker will register with the registry when it starts, but the registration fails and an error is reported in writing, probably because you have not configured zk, and then ds will choose the current registry to register

**Comment by pandong2011** [comment]
because your registry is mysql, and the worker registers with the registry when it starts, but the registration fails and an error is reported. It is recommended that you configure the center to select zk

**Comment by lihjChina** [comment]
> because your registry is mysql, and the worker registers with the registry when it starts, but the registration fails and an error is reported. It is recommended that you configure the center to select zk

yes，the mysql registry is already release,so i want use the mysql registry.my cdh use the zk version is 3.4.15,but ds3.1.0 use the zk version is 3.8.so i want change my registry zk to mysql

**Comment by songjianet** [comment]
Please confirm if this issue exists in 30x and dev.

**Comment by lihjChina** [comment]
> Please confirm if this issue exists in 30x and dev.

The dev branch is normal, and this error is not found
