### ISSUE TITLE
[Improvement][ui] The processor usage and memory usage of the monitoring center do not vary with the font of the browser

### ISSUE THREAD

**Issue by jackfanwan** [apache/dolphinscheduler#12387]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://user-images.githubusercontent.com/61672564/196017316-ca346d5a-9222-44ff-8079-9c95b6027c60.png)
When the browser changes the font size, the page can also change

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.
