### ISSUE TITLE
[Improvement][Jupyter Task Plugin] Execute Jupyter notebook on Jupyter Lab with Idap authentication

### ISSUE THREAD

**Issue by jieguangzhou** [apache/dolphinscheduler#12394]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Use papermill to execute notebook remotely on jupyter Lab， such as jupyer lab launched on kubeflow, and use ldap authentication

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
May I ask whether you want to implement this feature by yourself or have other volunteers do this? If latter, I will add a `help wanted` label to this issue.

**Comment by jieguangzhou** [comment]
> May I ask whether you want to implement this feature by yourself or have other volunteers do this? If latter, I will add a `help wanted` label to this issue.

I'll add the tag first, and if no one takes it, I'll implement it

**Comment by jieguangzhou** [comment]
This issue said if we want to run a .ipynb script via papermill on a remote server, we have to implement CustomEngine.
https://github.com/nteract/papermill/issues/361

In DolphinScheduler, can we exec in pod directly?
Such as we start a JupyterLab with custom image in kubelow which have dolphinscheduler worker? Or other connect method?

**Comment by EricGao888** [comment]
> This issue said if we want to run a .ipynb script via papermill on a remote server, we have to implement CustomEngine. [nteract/papermill#361](https://github.com/nteract/papermill/issues/361)
> 
> In DolphinScheduler, can we exec in pod directly? Such as we start a JupyterLab with custom image in kubelow which have dolphinscheduler worker? Or other connect method?

@jieguangzhou Two ways to do so:
1. If there is `Yarn` in remote cluster, you could make papermill run in yarn containers.
2. If the remote cluster is a K8S cluster, you could build papermill, jupyter and related libs into an image and run it in K8S pod.
