### ISSUE TITLE
[Feature][Alert] AlertContent add system.biz.date

### ISSUE THREAD

**Issue by yyccww123** [apache/dolphinscheduler#12399]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

AlertContent add system.biz.date

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yyccww123** [comment]
or add scheduling time

**Comment by ruanwenjun** [comment]
@yyccww123 We need to refactor the alert content I find we have two kinds of alert content: `ProcessAlertContent`, `ProcessAlertContent`, we can create a base AlertContent interface, and all alert content implement this interface, then we can only translate the alertContent in alert plugin, the alert plugin instance can build their own content.
