### ISSUE TITLE
[Bug][Worker Server ] When the DS uses the data source to connect to the Spark Thrift server, the connection channel remains connected and will not be closed

### ISSUE THREAD

**Issue by yihao-tcf** [apache/dolphinscheduler#12409]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I found that after the server netstat spark port The worker server does not disconnect from the Sparkhrift after the connection is established I think the SQL (spark data source) task node in each workflow will remain connected after execution.Restores to normal after the DS service is stopped.
spark version:3.2.1
hive version:3.1.2

### What you expected to happen

The worker server did not provide clear error information.
tail worker log file:
![image](https://user-images.githubusercontent.com/65161474/196322155-f9aeae1f-d910-4b2c-b5a3-ccd453ee1abe.png)
netstat spark thrift server pord status:
![511285f92dd953ac6589be74e446586](https://user-images.githubusercontent.com/65161474/196324786-ed36d602-c68b-4bf1-a64b-db234ad3c85f.jpg)
The status and connect open num of the spark thrift port after the DS service is stopped:
![4b4bf2e7401b594efe30b1f2c05c7c3](https://user-images.githubusercontent.com/65161474/196325601-f918a5f9-e4ee-4236-ae6d-374ebb6898b1.jpg)

### How to reproduce

1.create spark datasource
![image](https://user-images.githubusercontent.com/65161474/196327296-2120e122-d20e-48ff-aae9-7cc955e48538.png)

2.Define workflow and create spark data source query statement in workflow
![ded04e548cfae293c53d3e16e485829](https://user-images.githubusercontent.com/65161474/196327321-710cf2db-3818-43ff-9d7b-c122f7c0ff09.jpg)

3.run workflow
![bdb67f070e45d0547a261b0c4f74f07](https://user-images.githubusercontent.com/65161474/196327342-859d2d0f-f2e5-4859-b712-4bf83149a03e.jpg)
4.Connection status of the port after execution
![e510703259130f01272a5310f7a5b62](https://user-images.githubusercontent.com/65161474/196327436-df824560-556b-49d1-8322-5f6f7c892fe5.jpg)

### Version

3.0.x

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Please confirm if the issue exists in 31x and dev.

**Comment by yihao-tcf** [comment]
> Please confirm if the issue exists in 31x and dev.

OK, I'll try it tomorrow. thank

**Comment by yihao-tcf** [comment]
The problem still exists after I upgrade DS to version 3.1x

**Comment by davidzollo** [comment]
> The problem still exists after I upgrade DS to version 3.1x

@yyh2954360585 can you fix it?

**Comment by yyh2954360585** [comment]
> 

I will try to solve this problem when I have time.

**Comment by yyh2954360585** [comment]
> > The problem still exists after I upgrade DS to version 3.1x
> 
> @yyh2954360585 can you fix it?

 will try to solve this problem when I have time.

**Comment by yihao-tcf** [comment]
> > The problem still exists after I upgrade DS to version 3.1x
> 
> @yyh2954360585 can you fix it?

I will try to solve this problem when I have time.

**Comment by wendongdi** [comment]
has this bug been fixed ?
