### ISSUE TITLE
[Bug] [Failed to schedule schedule with parameters] Schedule schedule

### ISSUE THREAD

**Issue by yqzdy1207** [apache/dolphinscheduler#12408]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

带有$[yyyyMMdd]的定时参数失败

### What you expected to happen

能执行带参shell

### How to reproduce

![52ffcc0de56e73f20f7a229fcf6fc49](https://user-images.githubusercontent.com/33902141/196319793-a2afe995-e320-467e-a415-4739fbe6b89b.jpg)
![642f5a1c99db7992171c344e3ab9eef](https://user-images.githubusercontent.com/33902141/196319832-1fac19f1-9055-44a4-9cb9-209e2bee796f.jpg)
![cbabbaf9698fc5ffe531e8d3f8d6a8c](https://user-images.githubusercontent.com/33902141/196319846-da235f29-dcd2-4e2c-99b1-a6002f76cf25.jpg)
![857ab0e38b65bcfc277136b90bce271](https://user-images.githubusercontent.com/33902141/196319859-6a265000-bcc3-4349-8e55-6b40ede19cdc.jpg)
![dd69c2c5228f308b1d3c5829567f874](https://user-images.githubusercontent.com/33902141/196319873-bfdbab97-ff30-4887-9121-50badd983bfe.jpg)

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
I got the same exception, can you make a quick fix today and submit a PR?

**Comment by zhuangchong** [comment]
I'm so sorry, I had the same problem and needed an urgent fix and go live, so I fixed it first.
