### ISSUE TITLE
[Bug] Show wrong message when click the edge button on datasource web page

### ISSUE THREAD

**Issue by ZeonHuang** [apache/dolphinscheduler#12402]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Version: 3.0
Database information have been recorded. If I click the "Edit" button again, the port which is displayed on the "EditDataSource" panel will be initialized to default port number. 

### What you expected to happen

wrong information displayed which will miss the user.

### How to reproduce

fix the issue to show the right information

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Please provide some pictures and verify if this issue exists in dev and 310 as well.

**Comment by ZeonHuang** [comment]
> Please provide some pictures and verify if this issue exists in dev and 310 as well.

Pls refer to the pic.

![image](https://user-images.githubusercontent.com/110578575/196382565-a0b0ef17-d25e-41a5-95f0-853a8cc69232.png)
