### ISSUE TITLE
[Bug] [API] The workflow definition and the tenant in the workflow instance are inconsistent

### ISSUE THREAD

**Issue by hstdream** [apache/dolphinscheduler#12429]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="680" alt="1666837161777" src="https://user-images.githubusercontent.com/33045461/198175765-4089aa91-437b-4314-8e27-7dad5fc59a3d.png">
<img width="711" alt="1666837141669" src="https://user-images.githubusercontent.com/33045461/198175773-7fee4a5a-1343-4aaf-930e-1f8859c8f268.png">

### What you expected to happen

The workflow definition is consistent with the tenant in the workflow instance.

### How to reproduce

1.create workflow definition 
2.run workflow definition 
3.click edit workflow
4.click edit wotkflow instance 

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
<img width="440" alt="image" src="https://user-images.githubusercontent.com/97265214/196585988-b32944e4-68ed-44fa-981d-7335ee5ac7a6.png">
It seems to be a bug for the back end side. @hstdream
