### ISSUE TITLE
 [Bug] [Module Name] Cron manage: no instance host

### ISSUE THREAD

**Issue by paul-yangmy** [apache/dolphinscheduler#12428]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have set a timing scheduler for a task. However, dolphinscheduler cannot dispatch this task within the set time. The status of the task is running but the log shows an error: no instance host. The magic is that I can execute this task directly by the START button and everything is normal except I cannot manage it using the time scheduler

### What you expected to happen

![image](https://user-images.githubusercontent.com/44519600/196578708-96e5d4b3-d8cc-4cac-b04a-e6c75cfbca04.png)

### How to reproduce

I doubt the time scheduling settings after upgrading from v2.0.6 are not compatible with v3.0.x. It happens in the originally v2 designed time schedule, there is no problem in recreating one with v3

### Version

3.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
can you post some more detailed logs?

**Comment by paul-yangmy** [comment]
![b3fc0bec728a16187757ed23702a94e](https://user-images.githubusercontent.com/44519600/196653144-24894dad-c410-407b-b925-4490ae710cda.jpg)
Thanks！I found that I could recreate the scheduled task to avoid this problem so I deleted the repeated error logs of dolphinscheduler master.  This task is set to be executed on zk1, and the reported error "current task needs worker group inf2 "inf2 is normal. Checked by dolphin status shell and PID on that host. There is no error in this Worker log. I also found that other people met this problem [slack users-china](https://asf-dolphinscheduler.slack.com/archives/C03U7SR73TN/p1664793080817739). This is [My slack issue](https://asf-dolphinscheduler.slack.com/archives/C03U7SR73TN/p1665737030576829)

**Comment by songjianet** [comment]
Please make sure this issue exists in dev and 31x.

**Comment by paul-yangmy** [comment]
My version is 30x. But someone said it also appears in 31x.

**Comment by zgxv** [comment]
@songjianet 3.1.0 version has the same error, hope fix because this  is important use in work. thanks a lot
file LoggerServiceImpl.java 
<img width="663" alt="image" src="https://user-images.githubusercontent.com/6904753/200826464-66733b76-e1c8-4f5f-bd99-159a7d9be000.png">
getHost() is NULL, host field in table t_ds_task_instance is NULL
