### ISSUE TITLE
[Bug] [API] If Storge exception, ds can create tenant, but show cannot.

### ISSUE THREAD

**Issue by DarkAssassinator** [apache/dolphinscheduler#12425]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When we create a new tenant, but storge has some exception such as connect refuse. The UI alert will show create tenant failed, but it will be created in DB and can show in UI. And then use cannot delete this wrong tenant, because cannot delete it in storge.
But due to my PC env, i cannot show the screenshot. But we can check the source code.
**_Create:_** 
![image](https://user-images.githubusercontent.com/20518339/196452687-dca00ae7-fa2d-43dc-b111-9e8bfae7a903.png)
 **_Delete:_**
![image](https://user-images.githubusercontent.com/20518339/196453206-10e72d3e-3327-4fd5-bc1e-1b8ee66fe6b4.png)

### What you expected to happen

If db or storge has exception, ds cannot create a tenant.

### How to reproduce

1. Config the `resource.storage.type=HDFS`
2. Create a new tenant
3. Delete this new tenant.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Please make sure this issue exists in 30x and 31x.

**Comment by DarkAssassinator** [comment]
> Please make sure this issue exists in 30x and 31x.

sure, has double checked, this issue exists in 30x and 31x
