### ISSUE TITLE
[RoadMap][Year 2022 Q4] Community RoadMap

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#12436]
### Description

* Notes of the community roadmap discussions from the Oct. 12th, 2022 bi-weekly community conference.
* For some topics which need further discussions, we temporarily note the owner as `Community`.

###  RoadMap

| Type | Description | Link | Priority | Owner |
| --- | --- | --- | --- | --- |
| Feature | Add jRaft registry plugin | #11144 | High | @zhuxt2015 |
| Feature | K8S Executor | #13316 | High | @EricGao888 |
| Feature | Configuration Center | #10283 | High | Community |
| Feature | Automated API Test | --- | High | wen |
| Feature | Remote Logging | #13017 | High | @rickchengx |
| Feature | Remote Task | #11652 | High | @DarkAssassinator |
| Feature | Dynamic Task Plugin | --- | Middle | @Amy0104 |
| Feature | Independent Release of Task Plugin | --- | Middle | @caishunfeng |
| Feature | Support Streaming Task | #11352 | Middle | @caishunfeng |
| Feature | Task Sharing Storage | --- | Middle | @jieguangzhou |
| Improvement | UT Improvement | #10573 | High  | @EricGao888 |
| Improvement | pydolphinscheduler task plugin enrichment | #11793 | High | @jieguangzhou |
| Improvement | Task Parameters Sharing Optimization | --- | Middle | @zhongjiajie |
| Improvement | K8S Operator | --- | Middle | @kezhenxu94 |
| Improvement | Workflow Failure Strategy Optimization | #11793 | Middle | @EricGao888 |

### Related issues

* WIP

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
hi @EricGao888, could we add https://github.com/apache/dolphinscheduler/issues/11652 in 2022 Q4 RoadMap?

**Comment by EricGao888** [comment]
> hi @EricGao888, could we add #11652 in 2022 Q4 RoadMap?

done

**Comment by davidzollo** [comment]
if you'd like to implement some features for DolphinScheduler, please feel free to leave a message.

**Comment by EricGao888** [comment]
Closed by #13459

For WIP tasks in 2022 Q4 roadmap, we will keep a new record in #13459. For tasks which haven't received updates for long, we will not record them in the new roadmap. Thanks.
