### ISSUE TITLE
[Improvment] [Style] API Test spotless check failed.

### ISSUE THREAD

**Issue by DarkAssassinator** [apache/dolphinscheduler#12446]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

found 
![image](https://user-images.githubusercontent.com/20518339/196694481-cc4c3168-e5d6-4207-9407-89b14ecada54.png)
![1666183144052](https://user-images.githubusercontent.com/20518339/196694552-2cd33359-c273-41f6-b360-eb1fe62eb6e2.jpg)

### What you expected to happen

CI pass

### How to reproduce

N/A

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
This is not a bug. It is expected behavior. BTW, if those so-called 'blocked' PRs not rebased on latest dev branch, it still get blocked.

**Comment by DarkAssassinator** [comment]
> This is not a bug. It is expected behavior. BTW, if those so-called 'blocked' PRs not rebased on latest dev branch, it still get blocked.

get it. thx
