### ISSUE TITLE
[Bug] [dolphinscheduler woker]  datax use mysql to hive not work 

### ISSUE THREAD

**Issue by ChewJ404** [apache/dolphinscheduler#12444]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

datax use mysql to hive not work 
![image](https://user-images.githubusercontent.com/10162958/196666358-2908f762-1e8d-40fe-8f58-1b41772297f8.png)

### What you expected to happen

i found  this will be  Translated into
![image](https://user-images.githubusercontent.com/10162958/196666615-15cf8922-d084-4de3-8f02-862c49c82a2f.png)

but data x  not support  rdbms hive writer 

and  From both hive and spark, it's not nearly as good as Hdfswirter.

### How to reproduce

so  Have you tested the feasibility of this feature

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Please make sure this issue exists in 30x and dev.

**Comment by cnfree0355** [comment]
The same to me ,when use datax to sync mysql data to apache hive!
