### ISSUE TITLE
[Bug] [API] Updating workflow instance shows success, but does not actually take effect

### ISSUE THREAD

**Issue by pandong2011** [apache/dolphinscheduler#12453]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Click to update the workflow instance, and it will appear that the modification was successful, but it is not actually updated.

Edit an workflow instance
![process_instance_edit_1](https://user-images.githubusercontent.com/100667564/196739294-f167caf5-989d-4a9e-a6f2-31f3905315b3.jpg)

After the successful update is displayed, edit again, and the result is that there is actually no update
![process_instance_2](https://user-images.githubusercontent.com/100667564/196739293-32cb65b7-a79a-4e2a-8092-4c6f4b11e13d.jpg)

### What you expected to happen

After the workflow instance is submitted, the successful update is displayed and the background can be updated to the database

### How to reproduce

as mentioned above

### Anything else

It exists on the dev branch as well as the 3.1.0-release branch

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jiangtaoNuc** [comment]
please assign to me,thx

**Comment by jiangtaoNuc** [comment]
I will submit a pr ！thx @caishunfeng
