### ISSUE TITLE
[Feature][PyDolphinScheduler] Support Kubernetes task in pyds

### ISSUE THREAD

**Issue by tuchg** [apache/dolphinscheduler#12465]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

part of  https://github.com/apache/dolphinscheduler/issues/11906

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tuchg** [comment]
@jieguangzhou hi,guys i want to try it

**Comment by jieguangzhou** [comment]
> @jieguangzhou hi,guys i want to try it

Thanks for the help!

**Comment by zhongjiajie** [comment]
close due to https://github.com/apache/dolphinscheduler-sdk-python/pull/15
