### ISSUE TITLE
[Bug] [DataX]  the data source instance is empty when edit the DataX component

### ISSUE THREAD

**Issue by woshiwuxiaofei** [apache/dolphinscheduler#12463]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Every time you open and edit the DataX component, the data source instance is empty, and you need to re-select the data source type. When selecting the data source instance, it is a headache for a large number of node editors to reselect each time.
as follows:

<img width="996" alt="image" src="https://user-images.githubusercontent.com/17974050/196906446-76cb8c38-95b1-4cbb-92fc-f54a6b58b2f7.png">

### What you expected to happen

Every time you open and edit the DataX component, the data source instance should be displayed normally instead of being reselected

### How to reproduce

you open and edit the DataX component

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hstdream** [comment]
I will fix this bug. @caishunfeng

**Comment by woshiwuxiaofei** [comment]
@hstdream how to connect with you? Are you in the WeChat contributor group? You can add me to facilitate communication

**Comment by Amy0104** [comment]
This has been fixed by #11222

**Comment by EricGao888** [comment]
fixed by #11222
