### ISSUE TITLE
[Bug] [Resource] Resource authorization is disabled

### ISSUE THREAD

**Issue by WangJPLeo** [apache/dolphinscheduler#12466]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Resource authorization is disabled

### What you expected to happen

Normal

### How to reproduce

Resource authorization

### Anything else

No

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Please confirm if this issue exists in 31x and 30x.
