### ISSUE TITLE
[Refactor] Migrate all user-related and tenant-related interface functions from ProcessServiceImpl

### ISSUE THREAD

**Issue by DarkAssassinator** [apache/dolphinscheduler#12472]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

+ This is a part of #12403 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
@DarkAssassinator @jieguangzhou i want to refactor it
