### ISSUE TITLE
[Feature][IDE] Add IDE in DS DAG to Support Python/SQL 

### ISSUE THREAD

**Issue by William-GuoWei** [apache/dolphinscheduler#12475]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Now DS has a code interface like this, I think it is not very comfortable for developers to write sql or python in text box.
![image](https://user-images.githubusercontent.com/25520639/197091165-2541b996-1859-422f-9906-e5d3247d946f.png)

Here is the solution of some other projects:

![image](https://user-images.githubusercontent.com/25520639/197090972-a7827587-9930-4a34-bafc-07ebf8e93908.png)

Here is our proposed solutions:
1. on the left we still have DAG map
2. when you click sql task, or shell task, pop up a combo box on the right. it has 2 box. one is parameter setting(such as resource, database source). the other is a IDE written box.
3. IDE can support SQL/python grammar check so far.
4. IDE try support SQL/python run and see try-run log

The design is as below. What do you think about it? 
![image](https://user-images.githubusercontent.com/25520639/197092267-37b14e07-d677-46d7-8ea1-991983a106d5.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@William-GuoWei Sounds cool to me. It will be pretty handy for users to debug / develop big data tasks and will help DS march from a `scheduling platform` to a `development + scheduling studio`. Just curious, will we have both this and #11673 ? Looks like there are some kind of overlaps.
* #11673

**Comment by William-GuoWei** [comment]
yeah~~ very similar.
but this one is combined in DS DAG not an individual IDE
