### ISSUE TITLE
[Bug] [API] After the workflow definition is deleted, the task definition cannot be edited

### ISSUE THREAD

**Issue by hstdream** [apache/dolphinscheduler#12481]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After the workflow definition is deleted, the task definition cannot be edited.
save fail
<img width="712" alt="1667349205685" src="https://user-images.githubusercontent.com/33045461/199367189-3d6e703e-b279-43dd-950d-c2c443ab49c0.png">

### What you expected to happen

After the workflow definition is deleted, the task definition can be edited.

### How to reproduce

1.create workflow 
2.run workflow
3.delete workflow
4.look up task defination 
6.edit workflow

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Please confirm if this issue exists in 31x and 30x.

**Comment by hstdream** [comment]
in 31x
