### ISSUE TITLE
[Bug] [UI] delete stream task

### ISSUE THREAD

**Issue by hyliu777** [apache/dolphinscheduler#12485]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Delete workflow definition, while stream task still exist in task definition list.
![image](https://user-images.githubusercontent.com/17961082/197160699-34adb440-65af-46ba-8c22-7014c2cbd656.png)

### What you expected to happen

delete stream task

### How to reproduce

1. create a stream workflow
2. run stream workflow
3. delete workflow
4. check whether the stream task is to exist

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Please confirm if this issue exists in dev and 30x.
