### ISSUE TITLE
[Bug] [API] Before deleting a worker group, check whether there is environment that reference the worker group 

### ISSUE THREAD

**Issue by hstdream** [apache/dolphinscheduler#12490]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 Before deleting a worker group, check whether there is environment that reference the worker group.

### What you expected to happen

When a worker group is referenced by the environment, the worker group cannot be deleted。

### How to reproduce

1.create worker group
2.create environment ,choose worker group
3.delete worker group

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
hi @hstdream, is same as https://github.com/apache/dolphinscheduler/pull/12129?

**Comment by hstdream** [comment]
no same.
