### ISSUE TITLE
3.0.1 version swagger document path error

### ISSUE THREAD

**Issue by zhonghang1993** [apache/dolphinscheduler#12515]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

There is a problem with the 3.0.1 version of the swagger document. The official website gave it to http://{{host}}: 12345/dolphinscheduler/swagger ui/index Html. After accessing, the system forcibly jumps to http://{{host}}: 12345/dolphinscheduler/ui/dolphinscheduler/swagger ui/index.html. The path/dolphinscheduler/ui/is too many, which causes the page to remain blank

### What you expected to happen

1

### How to reproduce

1

### Anything else

1

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please use english to describe it. Feel free to reopen it when you correct it.
