### ISSUE TITLE
[Bug] [worker]  dolphinscheduler hive  Default  Execution Engine  is mr

### ISSUE THREAD

**Issue by ChewJ404** [apache/dolphinscheduler#12511]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

dolphinscheduler hive  Default  Execution Engine  is mr

### What you expected to happen

i used   hive  shell to  show    `set hive.execution.engine`  
result  return
`hive.execution.engine=tez`
next i used dolphinscheduler  shell hive job   command
`hive -e " set hive.execution.engine"`
result  return

`hive.execution.engine=mr`  why???

### How to reproduce

 i It's already set   `hive-site.xml`
```
<property>
    <name>hive.execution.engine</name>
    <value>tez</value>
</property>

```

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hstdream** [comment]
I'll verify this.

**Comment by hstdream** [comment]
ds:
<img width="517" alt="1666599328556" src="https://user-images.githubusercontent.com/33045461/197479718-a7e5d7fa-d060-4824-8651-4f928b1b09f9.png">
os:
<img width="573" alt="1666599312693" src="https://user-images.githubusercontent.com/33045461/197479738-79aa1c7f-f578-49dd-a336-5fd5317f9b49.png">
It has been verified that this is no problem. It is recommended to check your hive environment and whether you have restarted hiveserver2 after modifying the configuration.

**Comment by ChewJ404** [comment]
> ds: <img alt="1666599328556" width="517" src="https://user-images.githubusercontent.com/33045461/197479718-a7e5d7fa-d060-4824-8651-4f928b1b09f9.png"> os: <img alt="1666599312693" width="573" src="https://user-images.githubusercontent.com/33045461/197479738-79aa1c7f-f578-49dd-a336-5fd5317f9b49.png"> It has been verified that this is no problem. It is recommended to check your hive environment and whether you have restarted hiveserver2 after modifying the configuration.



i  test again 

### hive shell
![image](https://user-images.githubusercontent.com/10162958/197480647-73f99525-5629-42eb-8778-ce5a475c796b.png)

###  dolphinscheduler sql task
![image](https://user-images.githubusercontent.com/10162958/197481203-40636c58-f722-4476-a0e2-100216f5cb0e.png)

### dolphinscheduler  shell hive task
![image](https://user-images.githubusercontent.com/10162958/197481821-7ea55911-9697-4251-9181-439c12f0e358.png)

The environment variable is set  and i found if used sql task  i setting  Customize the environment is not working

**Comment by ChewJ404** [comment]
The environment variable  all settig  is right  ,i  used  aliyun emr ，hive shell  is show  right  ,but on dolphinscheduler  is wrong Could you give me an idea of where to find the problem

```
export HIVE_HOME=/usr/lib/hive-current
export HIVE_CONF_DIR=/etc/ecm/hive-conf
export HCAT_HOME=/usr/lib/hive-current/hcatalog
export TEZ_HOME=/usr/lib/tez-current
export TEZ_CONF_DIR=/etc/ecm/tez-conf
```

**Comment by ChewJ404** [comment]
sorry is mine problem ,worked node  is not Unified configuration
