### ISSUE TITLE
[Improvement] [logger-server] when config log base path out of dolphinscheduler install path, can't see task log

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#12528]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

dolphinscheduler 2.0.7

I install dolphinscheduler on path : /data/dolphinscheduler , and change the logback-*.xml's log.base as /data/dolphinscheduler-log.

then when I try to view the log detail , logger-server will throw java.lang.IllegalArgumentException: Illegal path exception.

```
ERROR org.apache.dolphinscheduler.remote.handler.NettyServerHandler - process msg Command [type=ROLL_VIEW_LOG_REQUEST, opaque=2, genCommandTimeMillis=0, bodyLen=101] error
java.lang.IllegalArgumentException: Illegal path
        at org.apache.dolphinscheduler.server.log.LoggerRequestProcessor.process(LoggerRequestProcessor.java:104)
        at org.apache.dolphinscheduler.remote.handler.NettyServerHandler.lambda$processReceived$0(NettyServerHandler.java:129)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### What you expected to happen

view log detail with out error

### How to reproduce

change the logback-*.xml's log.base out of dolphinscheduler install dir

### Version

2.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lordk911** [comment]
org/apache/dolphinscheduler/server/log/LoggerRequestProcessor.java line:150 
```
if (path.startsWith(dsHome) && !path.contains("../") && path.endsWith(".log")) {
                return true;
            }
```

which force log dir can only be under dolphinscheduler install path

**Comment by LiJie20190102** [comment]
@SbloodyS 
Excuse me, if you remove this code, will it have any impact?
![image](https://user-images.githubusercontent.com/53458004/197999401-637a3c2e-9d2c-4c1a-8373-d70cc990659a.png)

**Comment by caishunfeng** [comment]
> org/apache/dolphinscheduler/server/log/LoggerRequestProcessor.java line:150
> 
> ```
> if (path.startsWith(dsHome) && !path.contains("../") && path.endsWith(".log")) {
>                 return true;
>             }
> ```
> 
> which force log dir can only be under dolphinscheduler install path

Because it will cause a security problem, and users can read any file if no limit.

**Comment by lordk911** [comment]
if task logs can only under dolphin intall path ,  each time after upgrade dolphin , it's hard to reach the history task log.

**Comment by lordk911** [comment]
if user config log path out of dolphin install path , a soft link point to the path automatically create under install path , will this ok?

**Comment by SbloodyS** [comment]
> if user config log path out of dolphin install path , a soft link point to the path automatically create under install path , will this ok?

This can be achieved.

**Comment by ruanwenjun** [comment]
Closed by https://github.com/apache/dolphinscheduler/pull/13280
