### ISSUE TITLE
[Improvement][Permission] Improve DS permission control in a more decoupled way

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#12521]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Currently in ds project, code related to permission control are strongly coupled and widely scattered. It increases the risk of introducing bugs when refactoring / changing code. 
* We could improve the permission control with AOP or other more decoupled way.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
Big +1 May annotation should be better, such as `@AuthAction`

**Comment by EricGao888** [comment]
Closed due to low priority. If anyone interested in this issue and would like to give a try, plz feel free to comment and reopen this issue.  : )
