### ISSUE TITLE
[Bug] [backend] "The current feature is disabled." when authorize resource 

### ISSUE THREAD

**Issue by EcoleKeine** [apache/dolphinscheduler#12524]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Error: "The current feature is disabled." when using Resource Authorize

### What you expected to happen

-

### How to reproduce

-

### Anything else

please check this code (1/4): https://github.com/apache/dolphinscheduler/blob/ae33ba594754425a2ac72100450adffd3b5e3971/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java#L1506-L1509

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This is not a bug. Please read the document carefully.
`https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/resource/configuration.html`

**Comment by EcoleKeine** [comment]
@SbloodyS 
Are you sure?
if not functionDisabled then FUNCTION_DISABLED Error?

and would you point out which configuration? thank.
