### ISSUE TITLE
[Feature][datasource plugin] Add new datasource plugin for apache Kyuubi 

### ISSUE THREAD

**Issue by Narcasserun** [apache/dolphinscheduler#12535]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Kyuubi is a high-performance universal JDBC and SQL execution engine. The goal of Kyuubi is to facilitate users to handle big data like ordinary data.

It provides a standardized JDBC interface with easy-to-use data access in big data scenarios. End-users can focus on developing their business systems and mining data value without being aware of the underlying big data platform (compute engines, storage services, metadata management, etc.).

the product's official website is https://kyuubi.apache.org, we should add new datasource plugin to support apache kyuubi,There should be only a small difference from Hive's

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Narcasserun** [comment]
If possible, I am  willing submit  a pr

**Comment by Narcasserun** [comment]
If possible, I am  willing submit  a PR

**Comment by jieguangzhou** [comment]
Hi @Narcasserun  , I have assigned you and look forward to your code

**Comment by EricGao888** [comment]
> If possible, I am willing submit a PR

@Narcasserun This is a good feature. May I ask whether there will be any follow-ups?
