### ISSUE TITLE
[Bug] [Module Name] datax task nodes, custom parameters are required

### ISSUE THREAD

**Issue by Sky-Gu** [apache/dolphinscheduler#12544]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After upgrading from 3.0.0 to 3.1.0, the datax task node must be populated with user-defined parameters or an error will occur

### What you expected to happen

Custom parameters are not typed and do not force parsing

### How to reproduce

Add a datax task in custom script mode with no custom parameters in custom parameters.

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
hi @Sky-Gu , it will throw a NPE?

**Comment by liuzx8888** [comment]
`sbr.append(addCustomParameters(paramsMap));`  这个代码导致的，我也遇到了这个问题，如果不设置就会报NULL错误，他这个强制加上自定义参数的逻辑并没有对自定义参数是否为空做判断，也不是每个datax的job 都需要自定义参数。

**Comment by Sky-Gu** [comment]
@DarkAssassinator ,The situation is as described by @liuzx8888 , the task node throw a NPE

**Comment by zhuangchong** [comment]
I think the problem you reported and the problem fixed by this pr #12388 are the same, please confirm.

**Comment by Sky-Gu** [comment]
@zhuangchong    It's the same question

**Comment by zhuangchong** [comment]
I closed this issue first.
