### ISSUE TITLE
[Feature][gitOps] Integration github for better CICD

### ISSUE THREAD

**Issue by mengfeiMonica** [apache/dolphinscheduler#12551]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/15820530/198019391-7e901a90-b8cf-40e5-9f5f-119b6936c8fb.png">

#### precondition

* Separation of production and development environments
* Covert workflow(including task and task relation) as yaml file, add parse yaml into workflow
* Integration dolphinscheduler-studio in the dolphinscheduler
* API entry point to fetch latest GitHub content and import to database via API Server

#### How it run

* Clone code into API server 

#### How it run

* Clone code into API server
* Change it as before does
* Sync changes to GitHub and creates pull requests
* Merge(github) or solve conflict(dolphinscheduler-studio)
* Github CD

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bm001** [comment]
How Integration github for better CI/CD?
