### ISSUE TITLE
[Bug] [dolphinscheduler-server] dependent task faild when the be depended on work flow have conditions task

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#12556]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

dolphin version 2.0.7 

work flow fA have condition task cA, it have two conditions when true run task c , when false run task d, and c、d all point to e, so fA should always success.
work flow fB depended on fA of all. 
then work flow fB will fail, the reason is it can't find task c or task d instance.

![image](https://user-images.githubusercontent.com/19989300/198176999-2a741ceb-835e-4b96-98d5-39012c2b2936.png)

### What you expected to happen

fB success when fA is success.  this is right on version 2.0.5

### How to reproduce

as description above

### Version

2.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lordk911** [comment]
cc @JinyLeeChina

**Comment by jieguangzhou** [comment]
Hi, can you change the name of the task in the description? It looks a bit confusing

**Comment by lordk911** [comment]
> Hi, can you change the name of the task in the description? It looks a bit confusin

 if description looks confusin, just look the picture, I think it is clear enough, and easy to reproduce enough.

**Comment by brave-lee** [comment]
In version 2.0.6 and 2.0.7, depending on the workflow, all tasks in the workflow are required to be completed by default rather than some tasks. If the workflow is only successful, other types are required, refer #11970

**Comment by lordk911** [comment]
broken of backward compatibility shoud not apply on a 2.0.x (thirdly part change) version .

**Comment by brave-lee** [comment]
We won't support this feature in 2.0.x, refer #11970
