### ISSUE TITLE
[Bug] [BUILD]  Docker image construction failure

### ISSUE THREAD

**Issue by madaima** [apache/dolphinscheduler#12575]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

An error occurs when I run the following command：
.`/mvnw -B clean package \
       -Dmaven.test.skip \
       -Dmaven.javadoc.skip \
       -Dmaven.checkstyle.skip \
       -Ddocker.tag=3.2.0 \
       -Pdocker,release`

![Uploading image.png…]()

`[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  27.162 s
[INFO] Finished at: 2022-10-27T22:45:06+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.23.0:check (default) on project dolphinscheduler: The following files had format violations:
[ERROR]     dolphinscheduler-ui/node_modules/.pnpm/supports-preserve-symlinks-flag@1.0.0/node_modules/supports-preserve-symlinks-flag/CHANGELOG.md
[ERROR]         @@ -20,3 +20,4 @@
[ERROR]          -·Only·apps·should·have·lockfiles·[`ab318ed`](https://github.com/inspect-js/node-supports-preserve-symlinks-flag/commit/ab318ed7ae62f6c2c0e80a50398d40912afd8f69)
[ERROR]          -·[meta]·add·`safe-publish-latest`·[`2bb23b3`](https://github.com/inspect-js/node-supports-preserve-symlinks-flag/commit/2bb23b3ebab02dc4135c4cdf0217db82835b9fca)
[ERROR]          -·[meta]·add·`sideEffects`·flag·[`600223b`](https://github.com/inspect-js/node-supports-preserve-symlinks-flag/commit/600223ba24f30779f209d9097721eff35ed62741)
[ERROR]         +
[ERROR]     dolphinscheduler-ui/node_modules/.pnpm/@typescript-eslint+eslint-plugin@5.37.0_d685d2b5ce593055662a5186c22faa62/node_modules/@typescript-eslint/eslint-plugin/docs/rules/no-misused-new.md
[ERROR]         @@ -1,6 +1,7 @@
[ERROR]          ---
[ERROR]         +
[ERROR]          description:·'Enforce·valid·definition·of·`new`·and·`constructor`.'
[ERROR]         ----
`

### What you expected to happen

 BUILD SUCCESS

### How to reproduce

run ./mvnw -B clean package \
       -Dmaven.test.skip \
       -Dmaven.javadoc.skip \
       -Dmaven.checkstyle.skip \
       -Ddocker.tag=<TAG> \
       -Pdocker,release

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
The 3.2.0 has not been released yet.
