### ISSUE TITLE
[Bug] [UI] Chinese appeared in English environment.

### ISSUE THREAD

**Issue by hstdream** [apache/dolphinscheduler#12574]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Chinese appeared in English environment.

![1666882268128](https://user-images.githubusercontent.com/33045461/198322976-03edcd3c-8b90-4b79-8d96-32392f7cbdcb.png)

### What you expected to happen

English appeared in English environment.

### How to reproduce

click workflow Instance.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Please provide your version~

**Comment by hstdream** [comment]
dev

**Comment by songjianet** [comment]
Does this problem exist in 30x and 310. @hstdream

**Comment by hstdream** [comment]
dev
