### ISSUE TITLE
[Bug][script] When starting the service, should determine whether the service exists.

### ISSUE THREAD

**Issue by hstdream** [apache/dolphinscheduler#12585]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="289" alt="0c5fe5b2e0413612feb7ea5ccd114eb" src="https://user-images.githubusercontent.com/33045461/198513901-e06875dc-b560-495d-91b3-37cf96585d27.png">

### What you expected to happen

sh dolphinscheduler-daemon.sh start the service multiple times.

### How to reproduce

sh dolphinscheduler-daemon.sh start api-server 
sh dolphinscheduler-daemon.sh start master-server 
sh dolphinscheduler-daemon.sh start alert-server 
sh dolphinscheduler-daemon.sh start worker-server 
sh dolphinscheduler-daemon.sh start  standaloneServer

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
hi @hstdream, this issue same as https://github.com/apache/dolphinscheduler/issues/12109
