### ISSUE TITLE
[Bug] [Master] Repeat running the complement process instance will generate redundant complement instances

### ISSUE THREAD

**Issue by wcmolin** [apache/dolphinscheduler#12586]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I perform a repeat running operation on a complement instance, redundant complement instances are generated.

### What you expected to happen

I selected the complement date from the 25th to the 28th, a total of 4 days, and then repeat running the instance of the 27th, and the result was an additional instance of the 28th complement.

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/11606262/198514338-750fccaa-4040-43d6-afe3-fcb6427a3a4d.png">

### How to reproduce

Complement like this:
<img width="866" alt="111" src="https://user-images.githubusercontent.com/11606262/198514369-e33c449c-973c-4f33-b660-4eb16fe515ef.png">

### Version

2.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcmolin** [comment]
cc @JinyLeeChina

**Comment by hstdream** [comment]
which version.

**Comment by wcmolin** [comment]
> which version.

2.0.6

**Comment by hstdream** [comment]
Do you want to submit a PR?

**Comment by wcmolin** [comment]
> Do you want to submit a PR?

I will try to fix it

**Comment by SbloodyS** [comment]
I think the workflow of rerunning the complement will trigger the next complement workflow is a feature. Not a bug. cc @caishunfeng @zhongjiajie @EricGao888 @ruanwenjun @JinyLeeChina

**Comment by wcmolin** [comment]
> I think the workflow of rerunning the complement will trigger the next complement workflow is a feature. Not a bug. cc @caishunfeng @zhongjiajie @EricGao888 @ruanwenjun @JinyLeeChina

Any discussion results?

**Comment by brave-lee** [comment]
I like rerunning one day, and the instance after this day should not be executed. What do you think? cc @caishunfeng @zhongjiajie @EricGao888 @ruanwenjun

**Comment by caishunfeng** [comment]
> I think the workflow of rerunning the complement will trigger the next complement workflow is a feature. Not a bug. cc @caishunfeng @zhongjiajie @EricGao888 @ruanwenjun @JinyLeeChina

Yes, agree with @SbloodyS , it is not a bug, we should not put this feature into 2.0.x, it will change the origin feature of complement data.

**Comment by caishunfeng** [comment]
> I like rerunning one day, and the instance after this day should not be executed. What do you think? cc @caishunfeng @zhongjiajie @EricGao888 @ruanwenjun

+1, I think it should not auto rerun the next complement data, if user want to rerun, they can do it manually (rerun the 28th too or complement data again)

**Comment by lenboo** [comment]
This is a feature, not bug.
Rerun workflow instance would reproduce the instance using the parameters at that time: 
type=complement &  mode=sequential & start = 27th & end = 28th

**Comment by wcmolin** [comment]
> > I like rerunning one day, and the instance after this day should not be executed. What do you think? cc @caishunfeng @zhongjiajie @EricGao888 @ruanwenjun
> 
> +1, I think it should not auto rerun the next complement data, if user want to rerun, they can do it manually (rerun the 28th too or complement data again)

So do you think that auto rerun the next complement data is now an existing feature on 2.x versions? not a bug @caishunfeng

**Comment by EricGao888** [comment]
> I like rerunning one day, and the instance after this day should not be executed. What do you think? cc @caishunfeng @zhongjiajie @EricGao888 @ruanwenjun

My opinion is we give user a choice (or at least a notice) whether to complement the data after the specific date the user chooses to do data complement. But no matter what, I suggest we keep the original behavior on 2.0.x in case the change causes confusions. We could do the improvement on dev branch if it has not been implemented yet : ) So, basically I agree with this comment https://github.com/apache/dolphinscheduler/issues/12586#issuecomment-1313434554

**Comment by brave-lee** [comment]
> > I like rerunning one day, and the instance after this day should not be executed. What do you think? cc @caishunfeng @zhongjiajie @EricGao888 @ruanwenjun
> 
> My opinion is we give user a choice (or at least a notice) whether to complement the data after the specific date the user chooses to do data complement. But no matter what, I suggest we keep the original behavior on 2.0.x in case the change causes confusions. We could do the improvement on dev branch if it has not been implemented yet : ) So, basically I agree with this comment [#12586 (comment)](https://github.com/apache/dolphinscheduler/issues/12586#issuecomment-1313434554)

I think we should focus on the discussion point. This is a heavy rerunning behavior rather than a complement behavior
