### ISSUE TITLE
sql component garbled

### ISSUE THREAD

**Issue by ljl0303** [apache/dolphinscheduler#12581]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

ds2.0.6 mysql5.7 使用sql组件,查询带有例如select "中文";结果乱码,更换mysql8不乱码

### What you expected to happen

乱码肯定是不对的

### How to reproduce

mysql5.7使用sql组件,select内直接使用中文常量

### Anything else

每次

### Version

2.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
I tested that this function is OK. Please check your data source configuration and see if you haven't added jdbc parameters, such as `{"useUnicode":"true","characterEncoding":"UTF-8"}`
