### ISSUE TITLE
[Bug] [API] when i on-line  process definition,the  associated schedule is still offline.

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#12589]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

- when i off-line  process definition,the  associated schedule will be taken offline,but when i on-line  process definition,the  associated schedule is still offline.

### What you expected to happen

 when i on-line  process definition,the  associated schedule will be taken online

### How to reproduce

above

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
It's a new feature. Why this is a bug? 

BTW, This also involves user interaction process in the UI. Please provide design documents.
