### ISSUE TITLE
[Bug] [Log] query task instance detail log anomaly

### ISSUE THREAD

**Issue by fourSheep8X** [apache/dolphinscheduler#12582]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I view task instance logs，this modal dialog displays the exception information。
And then it kept repeating the same request：

![ds_3 1 0_bug](https://user-images.githubusercontent.com/10162605/198465640-ba36c568-f207-4dff-a6a5-54ddf6d8780f.png)

### What you expected to happen

According to the normal logging information

### How to reproduce

前几天还是好好的，我不知道怎么复现。在社区群里反馈过了，大佬说要重构接口，让我先提issues。

### Anything else

Nothing

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hstdream** [comment]
Please provide the steps to reproduce.

**Comment by flyysoul** [comment]
> Please provide the steps to reproduce.

I`m sorry I can`t reproduce that now .I will close it.

**Comment by fourSheep8X** [comment]
> Please provide the steps to reproduce.

I'm sorry I can't reproduce it now. I will close it.
