### ISSUE TITLE
[Bug] [datax task error] datax cannot run tasks on version 3.1.0

### ISSUE THREAD

**Issue by myyangdongyang** [apache/dolphinscheduler#12602]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="781" alt="image" src="https://user-images.githubusercontent.com/102777139/198735765-634d9b99-25e6-473e-9fcf-14532656d748.png">
<img width="788" alt="image" src="https://user-images.githubusercontent.com/102777139/198735836-e5aa8285-5664-4dda-8fe3-a22bd7ea5b09.png">

I failed to run the Python2-compatible datax task, and the Python3-compatible datax task still failed

### What you expected to happen

The latest version of the dolphinscheduler uses datax, whereas in previous versions datax was available.

### How to reproduce

written

### Anything else

The test team needs to be rigorous

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pandong2011** [comment]
This issue was fixed in 3.1.1-prepare branch and dev branch, associated with pr #12407 and pr #12388

**Comment by myyangdongyang** [comment]
I was in the dev branch to recompile the packaging for the latest package: dolphinscheduler-dev/dolphinscheduler-task-plugin/dolphinscheduler-task-datax/target/dolphinscheduler-task-datax-dev-SNAPSHOT.jar. I replaced the dolphinscheduler-task-datax-3.01.jar package from version 3.1.0 with another issue

<img width="811" alt="image" src="https://user-images.githubusercontent.com/102777139/198858222-228d6f2a-3d75-46ba-ba9a-b31df86133e3.png">
<img width="814" alt="image" src="https://user-images.githubusercontent.com/102777139/198858232-d8d24ac3-4621-4ca4-b170-897c5ffde7f4.png">

In addition to updating DolphinScheduler-Task-Datax-3.01.jar, do I need to update any other jar packages?

**Comment by pandong2011** [comment]
> In addition to updating DolphinScheduler-Task-Datax-3.01.jar, do I need to update any other jar packages?

yes, you need to manually build 3.1.1-prepare branch or dev branch, in other words build the entire jar

**Comment by myyangdongyang** [comment]
dolphinscheduler-worker services were unable to start after all jar replacement. Could you please tell us which jar packages were fixed? I only replace the specified jar package

**Comment by zhuangchong** [comment]
This issue has been fixed in pr #12388 and the community will release version 3.1.1 in early November. I will close this issue first, if you still have questions, you can open this issue again.

**Comment by zhuangchong** [comment]
> dolphinscheduler-worker services were unable to start after all jar replacement. Could you please tell us which jar packages were fixed? I only replace the specified jar package

dolphinscheduler-task-datax-${version}.jar
