### ISSUE TITLE
[Improvement]Flink task lacks common functions

### ISSUE THREAD

**Issue by xujiaqiang** [apache/dolphinscheduler#12605]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In the actual development process, our developers found that the Flink type tasks lacked some common functions.
   
For example, you can view the status of the Yarn task, kill the process of Yarn, cheachpoint, savepoint, and restore savepoint. These functions are often used in practical work.
    
You need to switch back and forth between different professional platforms. It increases the development cost and operation and maintenance cost of developers, making the actual development process of developers become cumbersome.
    
In order to effectively avoid appeals, improve development efficiency and reduce tedious operations. Our team has added these functions on the basis of 3.0.0 beta 2.
    
If you are interested in this idea, we can discuss function optimization in detail
   

---
在实际的开发过程中，我们的开发人员发现Flink类型的任务缺少一些常见的功能。

例如，您可以查看Yarn任务的状态，终止Yarn、cheachpoint、savepoint和restore savepoint。这些功能经常用于实际工作中。

你需要在不同的专业平台之间来回切换。它增加了开发者的开发成本和运维成本，使得开发者的实际开发过程变得繁琐。

为了有效避免上诉，提高开发效率，减少繁琐的操作。我们的团队在3.0.0 beta 2的基础上添加了这些功能。

如果你对这个想法感兴趣，我们可以详细讨论功能的优化

   My Email：xujiaqiangwz@163.com

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Good feature, I add discussion lable.
