### ISSUE TITLE
[Bug] [api-server] Ordinary users can only access the 'default' worker group

### ISSUE THREAD

**Issue by ztyoung86** [apache/dolphinscheduler#12615]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

An ordinary user can only choose the default worker group when he starts a workflow, even though there're several worker groups created in "Worker Group Manage" page.

this problem happened when I upgrade from 3.0.1 to 3.1.0

### What you expected to happen

Non-default worker group can be selected when an ordinary user starts a workflow.

### How to reproduce

1. Add a new worker group as an Admin;
2. Login as an ordinary user;
3. Start a workflow and change its worker group;

### Anything else

I went through the source code and found the root cause (maybe):

in Class `org.apache.dolphinscheduler.api.permission.ResourcePermissionCheckServiceImpl.WorkerGroupResourceList`

the function `listAuthorizedResource` just return an empty set whatever the argument `userid` is:
![image](https://user-images.githubusercontent.com/5070976/198924315-dd728e64-65e6-4f39-8a39-f71ab6f70f40.png)

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
This issue has been fixed in pr #12411 and the community is ready to release version 3.1.1 in early November.

I will close this issue first, if you still have questions, you can open this issue.
