### ISSUE TITLE
[Improvement] [ApiServer] Task defination list paging sorted by updateTime not effect

### ISSUE THREAD

**Issue by tracehh** [apache/dolphinscheduler#12621]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

List task defination and sorted  by update time not effect

### What you expected to happen

List task defination and sorted by update time

### How to reproduce

List task defination and look

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
It's a improvement. Why this is a bug?
