### ISSUE TITLE
ds3.0.0 ,why worker-server register zkserver using hostname,rather than ip？ [Bug] [Module Name] Bug title 

### ISSUE THREAD

**Issue by hkun0120** [apache/dolphinscheduler#12629]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

ds3.0.0 ,why worker-server register zkserver using hostname,rather than ip？

### What you expected to happen

registry ip，not hostname

### How to reproduce

i don't exactly describe 

### Version

3.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hkun0120** [comment]
<img width="1295" alt="WechatIMG12" src="https://user-images.githubusercontent.com/3326406/199151684-e957d74b-426f-47ec-97a5-f15754479722.png">
this is the configure

**Comment by hkun0120** [comment]
zookeeper verison is 3.4.14

**Comment by ruanwenjun** [comment]
Which environment you deployed? k8s or docker or physical machine?

**Comment by hkun0120** [comment]
> 

k8s

**Comment by hkun0120** [comment]
> Which environment you deployed? k8s or docker or physical machine?

k8s

**Comment by hkun0120** [comment]
My devlelop enviroment is correct ,registed worker-server by ip .but when the code running on the product Env,it changes to hostname.

**Comment by hkun0120** [comment]
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/3326406/199164666-b7db1a02-373b-434b-bbad-476b62319005.png">
like this

**Comment by hkun0120** [comment]
不明白为什么K8S要做成hostname。已解决。

**Comment by wllzhang** [comment]
Use `export HOSTNAME=\`hostname -I\``  to get ip.  but it does work. 
UnknownHostException: dolphinscheduler-worker-0

**Comment by farmer-it-1024** [comment]
> 不明白为什么K8S要做成hostname。已解决。

@hkun0120 ：请问如何解决的？
