### ISSUE TITLE
[Feature][UI] suggest add workflow monitor page

### ISSUE THREAD

**Issue by yyccww123** [apache/dolphinscheduler#12649]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

suggest add workflow monitor page.
The current workflow instance shows all logs, It is not easy to monitor daily performance.
Displays the latest workflow running status by workflow monitor page, Displays the number of tasks a workflow contains,Number of tasks that have been executed.
A list of all tasks is displayed through the triangle button to the left of the workflow name ,because dag page  is not Compact enough.

### Use case

add workflow monitor page

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Good suggestion, I add discussion lable.
