### ISSUE TITLE
[BUG] [HTTP TASK] Http parameter with placeholder not work

### ISSUE THREAD

**Issue by jscene** [apache/dolphinscheduler#12659]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Save Process Definition
Add Http Task Node，and add Http parameter with placeholder
(添加Http任务节点，并且添加占位符参数)

![image](https://user-images.githubusercontent.com/13428489/199390518-a60370ba-67e8-4707-b8a1-997c8a4bf0f8.png)
![image](https://user-images.githubusercontent.com/13428489/199390605-9f2f953b-0d26-462c-9b19-31769fe50031.png)

Task run with manual was successed, but failed if scheduled
手动执行任务可以成功，定时执行失败，任务实例只显示提交成功
![image](https://user-images.githubusercontent.com/13428489/199390766-5d439209-3aeb-493d-8b8d-2cb23cfb0ed8.png)
![image](https://user-images.githubusercontent.com/13428489/199391455-cb6a3f7a-9688-4dff-888e-7ce325a76f4a.png)

### What you expected to happen

Http job is allow to run with placeholder parameter
Http任务可以通过占位符传参

### How to reproduce

See [What happened]

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jackfanwan** [comment]
@Amy0104 please assign to me

**Comment by SbloodyS** [comment]
> @Amy0104 please assign to me

Done.
