### ISSUE TITLE
[Feature][Shell task] Add task info

### ISSUE THREAD

**Issue by darrkz** [apache/dolphinscheduler#12677]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I use shell task frequently
But I found I need to know some info of the task instance execute info, Such as

task project info
task follow info
task name info
task call type info,  scheduler or user execute

can add this info to task node

I think can add this info to   xxx.command

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
hi @darkz1984 , could you please describe the usage scenario in detail?

**Comment by darrkz** [comment]
> hi @darkz1984 , could you please describe the usage scenario in detail?

I use these information in alter message and can help me detect task instance information more clearly
