### ISSUE TITLE
[Bug] [dolphinscheduler-ui] where task define, workflow name not same

### ISSUE THREAD

**Issue by jackfanwan** [apache/dolphinscheduler#12672]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

this is null
![image](https://user-images.githubusercontent.com/61672564/199550974-f1564e56-99eb-48f9-b87a-50378eadb989.png)

but i click edit
![image](https://user-images.githubusercontent.com/61672564/199551118-61314e54-0bb6-477b-a6ea-c1b794e27aea.png)

### What you expected to happen

should is same

### How to reproduce

delete related workflow, look task list

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hstdream** [comment]
This problem is the same as #12481.
