### ISSUE TITLE
[Bug] [dolphinscheduler-dao] deleted related workflow, but task's processDefinition related not null

### ISSUE THREAD

**Issue by jackfanwan** [apache/dolphinscheduler#12673]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

deleted related workflow, but task's processDefinition related not null
![image](https://user-images.githubusercontent.com/61672564/199616138-b8068a14-6115-4409-b8c6-33f0e05b450f.png)

### What you expected to happen

task's processDefinition related is null

### How to reproduce

1. create workflow and related task
2. delete workflow
3. look task list

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Does this issue exist in 3.0.x or 3.1.x?

**Comment by jackfanwan** [comment]
> Does this issue exist in 3.0.x or 3.1.x?

i use’s dev branch
