### ISSUE TITLE
[Bug] [dolphinscheduler-service] Workflow with any parameters failed to dispatch task for scheduling execution

### ISSUE THREAD

**Issue by yxwyoyoyo** [apache/dolphinscheduler#12688]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Workflow with any parameters failed to submit task when scheduling execution.

### What you expected to happen

Workflow with any parameters succeed to submit task when scheduling execution.

### How to reproduce

Version: 3.1.0
1. Create a workflow with any parameters
2. Create a cron job
3. Just wait for execution

### Anything else

process instance generated from schedule is not assigned commandParam, so it will throw NPE here.
https://github.com/apache/dolphinscheduler/blob/6766ec04df8bed87425174609e21752844a9ca34/dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringGlobalParams.java#L158

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
as i know, this case has been fixed

**Comment by yxwyoyoyo** [comment]
> as i know, this case has been fixed

In the upcoming version?

**Comment by yxwyoyoyo** [comment]
> as i know, this case has been fixed

Looks like it was fixed by the code in 3.1.1-prepare branch. Thank you for replying.
https://github.com/apache/dolphinscheduler/blob/43650bf72113bc48d121bea2cb325c5264918f52/dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java#L411
