### ISSUE TITLE
[Improvement] [Yarn Queue] Config of Queue Doesn't Work.

### ISSUE THREAD

**Issue by Apotato98** [apache/dolphinscheduler#12683]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 I have set up queues (non-default queues) for both tenants and users according to similar settings, but whether the user runs tasks or other users run tasks, the final queue used on yarn is still default.
Besides, the version is 3.0.
The queue name on dolphinscheduler is the same as the queue name on yarn.

### What you expected to happen

Tenant queue settings and user queue settings take effect.

### How to reproduce

![企业微信截图_06ce118a-dc26-424c-9937-e6639499b39b](https://user-images.githubusercontent.com/60845098/199665822-f287b278-bf9d-42d8-bcce-29d8cb959d1c.png)
![image](https://user-images.githubusercontent.com/60845098/199665985-d09e8878-ee9c-4bb9-8cf3-4133d53c346a.png)
I created a test user, mounted it under the mask tenant, set the test user as the flink queue, the mask tenant as the flink queue, and used the shell node to perform the hive -e "sql" task, but the task was run in the default queue .

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hstdream** [comment]
After testing: found that this problem exists in 3.1.x  too

**Comment by SbloodyS** [comment]
The queue does not take effect in the shell task node. It's not a bug.

However, I think we can provide the queue variable in the shell node for users to use.

**Comment by hstdream** [comment]
I don't think so. Since there is a queue configuration, it can definitely be used, otherwise the queue is of little significance.

**Comment by Apotato98** [comment]
Thanks for the reply, will this feature be fixed in the near future?

**Comment by hstdream** [comment]
> Thanks for the reply, will this feature be fixed in the near future?
This needs to be reproduced, and then the problem can be solved in a targeted manner.
