### ISSUE TITLE
[Bug] [worker] In cluster mode, the worker cannot work and does not execute tasks

### ISSUE THREAD

**Issue by guoxu0514** [apache/dolphinscheduler#12715]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Production environment: 2 masters, 2 workers

In version 2.0.6, the worker failed to work after the production environment was running for a period of time. The problem persisted after upgrading to 2.0.7. It is normal to stop a group of workers and masters and run only a group of masters and workers.

The records of the two tables t_ds_process_instance/t_ds_task_instance do not increase, and the t_ds_command keeps adding new records but does not execute.

Check the dolphinscheduler-master and dolphinscheduler-worker logs, no error or warn is found

Version
2.0.6
2.0.7

Both the above versions have problems

### What you expected to happen

The worker executes normally, and the two tables t_ds_process_instance/t_ds_task_instance add records

### How to reproduce

2.0.6 restarts multiple times and it doesn't work, even after upgrading to 2.0.7.

### Version

2.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
hi @guoxu0514, could u please show more log details?

**Comment by SbloodyS** [comment]
Please use english to describe the issue. Thanks. @guoxu0514

**Comment by guoxu0514** [comment]
> 

No any exception information in the log

**Comment by guoxu0514** [comment]
> hi @guoxu0514, could u please show more log details?

No any exception information in the log

**Comment by guoxu0514** [comment]
> hi @guoxu0514, could u please show more log details?

@DarkAssassinator No any exception information in the log

**Comment by guoxu0514** [comment]
> Please use english to describe the issue. Thanks. @guoxu0514

@SbloodyS already updated
