### ISSUE TITLE
[Bug] [Api] Queue too long queue create fail

### ISSUE THREAD

**Issue by hstdream** [apache/dolphinscheduler#12711]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="720" alt="1667555904718" src="https://user-images.githubusercontent.com/33045461/199945524-de256951-0e4d-4c75-bacb-f1707ac1c899.png">

queue name too long cause create fail

### What you expected to happen

create queue 

### How to reproduce

create queue
queue name too long 

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Personally, I don't think it's necessary since the queue name will not be so long in the production environment.

**Comment by davidzollo** [comment]
> Personally, I don't think it's necessary since the queue name will not be so long in the production environment.

+1 
@hstdream I will close this issue, this is not a problem, can you help to answer some issues? there are many issues that need to response
