### ISSUE TITLE
[Bug] [workflow] 3.0.0-alpha vesion After the task is retried, the task reports an error, and the workflow card owner

### ISSUE THREAD

**Issue by TheOldOne-SU** [apache/dolphinscheduler#12718]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/52726630/200093161-9061c892-79dc-4930-8f7d-a0b9be0dfc89.png)
`After the task is retried, the task reports an error, and the workflow card owner.  As shown below`
![image](https://user-images.githubusercontent.com/52726630/200093160-3894111b-6a3f-493c-86b1-ab08b0559882.png)
`If you do not set the task to retry, the workflow will exit normally after the task reports an error`

### What you expected to happen

In this case, the workflow should exit normally

### How to reproduce

参考 
reference resources What happened

### Version

3.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Steppenwolf1900** [comment]
I also encountered this problem, how did you solve it?

**Comment by TheOldOne-SU** [comment]
还没解决
