### ISSUE TITLE
[Bug] [dolphinscheduler-api] code logistic have conflict

### ISSUE THREAD

**Issue by jackfanwan** [apache/dolphinscheduler#12721]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/61672564/200097553-95f7e83e-c366-4858-945e-c610107c5b84.png)

### What you expected to happen

resolve code conflict

### How to reproduce

no

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
I will close this PR, you need to provide the detail if there exist a bug.

We don't plan to change the code in this class, this class should be refactored.
