### ISSUE TITLE
[Improvement][dolphinscheduler-api] Check valid file parameter when defining process

### ISSUE THREAD

**Issue by Radeity** [apache/dolphinscheduler#12723]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When users want to transfer files between tasks and define `file` parameters(support in https://github.com/apache/dolphinscheduler/pull/12552), sometimes parameters are invalid for the sake of wrong file parameter name or even file parameter undefined. In current version, these errors can only be found during executing the process, thus, i think a check when defining process(before executing) is strongly needed.

I'll add function checkValidFileParams which will be called in the following methods in ProcessDefinitionServiceImpl:

```java
public Map<String, Object> createProcessDefinition(User loginUser, ...)

public Map<String, Object> updateProcessDefinition(User loginUser, ...)
```

********

This issue is only for file type parameters, checking logic is different from other primitive types parameter, so i separate two issues.

 `file` parameters have explicit declaration, can be directly fetched in `taskParamList`.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
@SbloodyS Please assign me and label `3.2.0` which is as same as https://github.com/apache/dolphinscheduler/pull/12552

**Comment by SbloodyS** [comment]
> @SbloodyS Please assign me and label `3.2.0` which is as same as #12552

I've labeled it as `3.1.2`.
