### ISSUE TITLE
[Improvement][dolphinscheduler-tools] whether it is necessary to perform updates after initialization

### ISSUE THREAD

**Issue by seedscoder** [apache/dolphinscheduler#12720]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When executing `org.apache.dolphinscheduler.tools.datasource.UpgradeDolphinScheduler#main` method , If it is a blank database， This method only performs initialization operations, not DS upgrade.
- Is this inconsistent with the method semantics ?Therefore, whether it is necessary to perform updates after initialization .

> This operation is similar to the following

```java
        public void run(String... args) throws Exception {
            if (dolphinSchedulerManager.schemaIsInitialized()) {
                dolphinSchedulerManager.upgradeDolphinScheduler();
                logger.info("upgrade DolphinScheduler finished");
            } else {
                dolphinSchedulerManager.initDolphinScheduler();
                dolphinSchedulerManager.upgradeDolphinScheduler();
                logger.info("init DolphinScheduler finished");
            }
        }
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Currently, the latest table schema will be initialized during initialization. The update logic is used to upgrade from a lower version to a higher version. @seedscoder
