### ISSUE TITLE
[Feature][Scheduling batch] Each batch judges whether the previous batch is successfully executed

### ISSUE THREAD

**Issue by luckes-yang** [apache/dolphinscheduler#12746]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

我的调度任务，依赖于上一个批次，需要判断上一批次是否执行成功。

### Use case

例如：
每小时执行的批次，11点的批次需要判断10点的批次是否执行成功，若未执行成功，则继续等待

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please use english to describe. Thanks. @luckes-yang

**Comment by luckes-yang** [comment]
> Please use english to describe. Thanks. @luckes-yang
For batches executed every hour, the batch at 11 o'clock needs to judge whether the batch at 10 o'clock is successfully executed. If it is not executed successfully, continue to wait.
