### ISSUE TITLE
[Feature][ui] suggest put  status and schedule publish status together in workflow definition list page.

### ISSUE THREAD

**Issue by yyccww123** [apache/dolphinscheduler#12834]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

suggest put  status and schedule publish status together in workflow definition list page.
It is difficult to use, because need drag the progress bar to see schedule publish status.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zyy1161623489** [comment]
@SbloodyS Has anyone implemented this feature? I'd be willing to submit a pr to close this issue

**Comment by hdygxsj** [comment]
@SbloodyS  Has anyone implemented this feature? I'd be willing to submit a pr to close this issue

**Comment by SbloodyS** [comment]
> @SbloodyS Has anyone implemented this feature? I'd be willing to submit a pr to close this issue

No. I've assigned to you. Looking forward to your contribution.

**Comment by hdygxsj** [comment]
It seems that this function has not been added yet, and I found that the download workflow picture button on the workflow definition page and the offline button on the workflow list page use the same icon, whether it needs to be adjusted,  I'd be willing to commit a pr to close this issue
![5d77c44715b253ec7ef26fa01b5b98b](https://user-images.githubusercontent.com/35210666/202460845-a22fead4-eeb2-4aea-b84e-36193e87389f.png)
![c27349de4cbc9082324504ee949d943](https://user-images.githubusercontent.com/35210666/202460852-10971a2c-9fdf-47a2-8298-b1edd6afaef8.png)
