### ISSUE TITLE
[Bug] [api]  cannot delete yarn queue

### ISSUE THREAD

**Issue by yyccww123** [apache/dolphinscheduler#12833]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 cannot delete yarn queue  in yarn queue manage page. have Not delete button.

### What you expected to happen

Want to delete yarn queue 

### How to reproduce

 in yarn queue manage 

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
can you implement this?

**Comment by amaoisnb** [comment]
I wanna have a try, can you please assign to me?

**Comment by davidzollo** [comment]
> I wanna have a try, can you please assign to me?

have assigned to you

**Comment by amaoisnb** [comment]
#13046
