### ISSUE TITLE
Large logs cause frequent gc of worker nodes, which leads to the loss of connection between zk and worke

### ISSUE THREAD

**Issue by multiLJT** [apache/dolphinscheduler#12852]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Our production environment will generate a large number of logs, and the log files may reach hundreds of gigabytes. At this time, the worker service will be frequently fgc. fgc takes a long time and cannot be recycled in the old age. Finally, the worker loses contact with zk and the service is killed
![1668053535795](https://user-images.githubusercontent.com/103870918/200999814-fba0fb9c-0e71-43af-9bd8-823081487ee2.png)
![image](https://user-images.githubusercontent.com/103870918/201000009-4422c53a-aaac-4ae6-9578-65a999201102.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by multiLJT** [comment]
Please help me. I want to know how you modified this vulnerability. I didn't understand your solution when I looked at the source code

**Comment by Mickey-bst** [comment]
+1

**Comment by multiLJT** [comment]
@caishunfeng ,大文件的问题，我看3.3版本做了一些优化，但是获取文件size的时候还是会全部加载日志，能否使用flies.line流来解决呢，还有请求整个日志的处理，是否可以加上一些大小限制，防止oom。或者有什么其他的处理方案，我水平有限，还请告知。
