### ISSUE TITLE
[Bug] [spark sql] set user defined parameters in spark sql can not pass to sql script

### ISSUE THREAD

**Issue by Alxe1** [apache/dolphinscheduler#12863]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

set user defined parameters in spark sql can not pass to sql script,
i write a sql in script:

```
select * from game.ods_dpzj_reg_log_di where data_date=${dt} limit 10
```

and set parameter in user defined parameters, and i set dt $[yyyyMMdd-30], it can not pass to the sql script

### What you expected to happen

can pass user defined parameter in spark sql

### How to reproduce

use spark sql script and pass user defined parameter

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi @Alxe1, I've tested your scene and found noting wrong. Please check whether you set the parameter in a wrong way. 

**local parameter setting:**
<img width="545" alt="image" src="https://user-images.githubusercontent.com/45198818/202359240-de078144-43e5-43a7-a3cb-e1d0d76daf25.png">

**log**

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/45198818/202359300-f5cadb7f-72ef-4f4b-9f1a-2be8f2eecefb.png">

<br>
BTW, Please close the issue when you figure out where the problem is.

**Comment by Alxe1** [comment]
> Hi @Alxe1, I've tested your scene and found noting wrong. Please check whether you set the parameter in a wrong way.
> 
> **local parameter setting:** <img alt="image" width="545" src="https://user-images.githubusercontent.com/45198818/202359240-de078144-43e5-43a7-a3cb-e1d0d76daf25.png">
> 
> **log**
> 
> <img alt="image" width="1104" src="https://user-images.githubusercontent.com/45198818/202359300-f5cadb7f-72ef-4f4b-9f1a-2be8f2eecefb.png">
> 
> 
> BTW, Please close the issue when you figure out where the problem is.

In below picture, the parameter type frame is gray, I can not select other parameters and it can not pass parameters in sql script. Is there anything miss configurations resulting to  this problem?

![image](https://user-images.githubusercontent.com/15032072/202398847-f8f2f75f-db34-41ce-9ed0-05f26f6a18e3.png)

**Comment by Alxe1** [comment]
> Hi @Alxe1, I've tested your scene and found noting wrong. Please check whether you set the parameter in a wrong way.
> 
> **local parameter setting:** <img alt="image" width="545" src="https://user-images.githubusercontent.com/45198818/202359240-de078144-43e5-43a7-a3cb-e1d0d76daf25.png">
> 
> **log**
> 
> <img alt="image" width="1104" src="https://user-images.githubusercontent.com/45198818/202359300-f5cadb7f-72ef-4f4b-9f1a-2be8f2eecefb.png">
> 
> 
> BTW, Please close the issue when you figure out where the problem is.

my procedure is: add spark node -> select sql type -> select spark2 version -> write sql script with parameters -> add user defined parameters (which can not select parameter type) -> end. dolphonescheduler version: 3.0.1

![image](https://user-images.githubusercontent.com/15032072/202410272-05cd26f7-8672-4ee9-be59-cd208cef84ff.png)

![image](https://user-images.githubusercontent.com/15032072/202409868-9766742e-c7fd-4607-8af3-68b82e4ddf3c.png)

![image](https://user-images.githubusercontent.com/15032072/202409992-8ec655ba-266d-4f47-a197-a3971b242028.png)


Is there anything miss configurations resulting to this problem?

**Comment by Radeity** [comment]
> my procedure is: add spark node -> select sql type -> select spark2 version -> write sql script with parameters -> add user defined parameters (which can not select parameter type) -> end. dolphonescheduler version: 3.0.1


It seems no problem with this procedure, however, it looks weird that you can not select parameter type. I don't have the environment of version 3.0.1, maybe you can ask someone else to help. @ruanwenjun @SbloodyS

**Comment by ChunChunWeb** [comment]
@Radeity which version u use? also appear in 3.0.2.  
![image](https://user-images.githubusercontent.com/32215562/207562948-7abe2093-2e07-4054-ba66-7515c7739fdb.png)

**Comment by ChunChunWeb** [comment]
choose version 3.1.2, its okey
