### ISSUE TITLE
[Refactor] Migrate environment and system resources limitations to task params

### ISSUE THREAD

**Issue by DarkAssassinator** [apache/dolphinscheduler#12873]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

now `TaskInstance` and `TaskDefinition` contain `environment` and `cpuQuota` and `memoryMax`, but these shoud be just task params, not task fields. Because just shell related task plugin need these params. Not all task need it. So i think that these fields should be task params.
I want to migrate `environment` and `cpuQuota` and `memoryMax` to a new Parameter entity named `ShellAdvanceParameters`

**What's the negative impact?**
It will drop these columns in db tables, it will impact version update. WDYT.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
cc @ruanwenjun, @caishunfeng @SbloodyS @EricGao888

**Comment by caishunfeng** [comment]
>now TaskInstance and TaskDefinition contain environment and cpuQuota and memoryMax, but these shoud be just task params, not task fields.

LGTM, and now ds has many tasks will run by shell, like spark-cli, flink-cli and so on. They should change together.

BTW, when delete environment config, it may check whether some tasks use it, so if we remove this field, will it affect query performance?

**Comment by DarkAssassinator** [comment]
> > now TaskInstance and TaskDefinition contain environment and cpuQuota and memoryMax, but these shoud be just task params, not task fields.
> 
> LGTM, and now ds has many tasks will run by shell, like spark-cli, flink-cli and so on. They should change together.
> 
> BTW, when delete environment config, it may check whether some tasks use it, so if we remove this field, will it affect query performance?

hi @caishunfeng, I understand your concern, but I think this part of the impact is limited for several reasons:
1. These configuration deletion actions are not a frequent operation.
2. We will simplify the deletion logic, check whether the task parameters of the unfinished task instance contain parameters when deleting
3. If query performance bad, we can conside to add index in `task_params` column.

**Comment by DarkAssassinator** [comment]
may can review PR:https://github.com/apache/dolphinscheduler/pull/12736, i add a `BashTaskEexectionContext`, we can migrate these configurations to this context, no need add it to TaskInstance and TaskDefinition. This ensures that the semantics of TaskInstance are clear

**Comment by SbloodyS** [comment]
> now TaskInstance and TaskDefinition contain environment and cpuQuota and memoryMax, but these shoud be just task params, not task fields.

Currently, the json of our task params is huge, which already affects query performance. If we add more content to it, it is bound to aggravate the problem. I think we should split this json into different tables. @caishunfeng @DarkAssassinator

**Comment by DarkAssassinator** [comment]
> > now TaskInstance and TaskDefinition contain environment and cpuQuota and memoryMax, but these shoud be just task params, not task fields.
> 
> Currently, the json of our task params is huge, which already affects query performance. If we add more content to it, it is bound to aggravate the problem. I think we should split this json into different tables. @caishunfeng @DarkAssassinator

+1 i think that this is a good idea, we can add a table named `t_ds_task_params`, then drop the `task_params` column in `t_ds_task_instance`, add `task_params_code` column? WDYT. cc @SbloodyS @caishunfeng

**Comment by Radeity** [comment]
> > now TaskInstance and TaskDefinition contain environment and cpuQuota and memoryMax, but these shoud be just task params, not task fields.
> 
> LGTM, and now ds has many tasks will run by shell, like spark-cli, flink-cli and so on. They should change together.
> 
> BTW, when delete environment config, it may check whether some tasks use it, so if we remove this field, will it affect query performance?

Hi, @caishunfeng @DarkAssassinator 
BTW, i think current table structure of `t_ds_environment` is not elegant, as far as I know, environment just configure some environment variables which may be used in tasks. Why not record a variable in one row, rather use `config` field? Only query this table once during task execution, so query performance is not a big deal.

Also, i have an environment-related question, in https://github.com/apache/dolphinscheduler/issues/12713#issuecomment-1317967932, wish you could give some suggestions!

**Comment by Radeity** [comment]
> Hi, @caishunfeng @DarkAssassinator BTW, i think current table structure of `t_ds_environment` is not elegant, as far as I know, environment just configure some environment variables which may be used in tasks. Why not record a variable in one row, rather use `config` field? Only query this table once during task execution, so query performance is not a big deal.
> 
> Also, i have an environment-related question, in [#12713 (comment)](https://github.com/apache/dolphinscheduler/issues/12713#issuecomment-1317967932), wish you could give some suggestions!

Oh, i just find that config is directly written into command file, if so, save it as String is more convenient.

**Comment by DarkAssassinator** [comment]
> > Hi, @caishunfeng @DarkAssassinator BTW, i think current table structure of `t_ds_environment` is not elegant, as far as I know, environment just configure some environment variables which may be used in tasks. Why not record a variable in one row, rather use `config` field? Only query this table once during task execution, so query performance is not a big deal.
> > Also, i have an environment-related question, in [#12713 (comment)](https://github.com/apache/dolphinscheduler/issues/12713#issuecomment-1317967932), wish you could give some suggestions!
> 
> Oh, i just find that config is directly written into command file, if so, save it as String is more convenient.

hi @Radeity because many task may use the same environment, so DS add `t_ds_environment` to manage. So u mean that we should add a environment string column in task_instance? But I think the environemt field is only useful for some tasks that use bash, not all task types, so I think the environemt  field does not belong to the taskInstance, but should be a custom parameter of the task plugins. So we should abstract task custom parameter to a other db table to inrease query performance. WDYT.

**Comment by Radeity** [comment]
> hi @Radeity because many task may use the same environment, so DS add `t_ds_environment` to manage. So u mean that we should add a environment string column in task_instance? But I think the environemt field is only useful for some tasks that use bash, not all task types, so I think the environemt field does not belong to the taskInstance, but should be a custom parameter of the task plugins. So we should abstract task custom parameter to a other db table to inrease query performance. WDYT.

Hi, @DarkAssassinator. I just find out i misunderstand in the first comment, so correct myself in the second comment, which i mean is saving field `config` as String is reasonable in DS. Actually i have no doubts about the current implementation and agree with your idea, thanks for your reply!
