### ISSUE TITLE
[3.0.2-prepare] Test core functions manually before release

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#12888]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- [x] Deployment in Cluster mode
- [x] Deployment in K8S mode - failed to create tenant, has been fixed by #12906, now ok.
- [x] Metadata create / upgrade, create - ok, upgrade - not tested yet
- [x] Docker image: standalone image - ok, create tenant / user - ok, run shell task / workflow - ok, scheduling - ok, docker-compose - ok.
- [x] Resource Center
- [x] Alert
- [x] Workflow / Task
- [x] Task Plugin - shell - simple echo command - ok
- [ ] Task Plugin - SQL (hive)
- [ ] Task Plugin - Spark
 
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lugela** [comment]
[12727](https://github.com/apache/dolphinscheduler/issues/12727) 3.0.x has bug , 2.0.x、3.1.x has no bugs.
Is it possible to cherry-pick [pr11919](https://github.com/apache/dolphinscheduler/pull/11919)

**Comment by EricGao888** [comment]
> [12727](https://github.com/apache/dolphinscheduler/issues/12727) 3.0.x has bug , 2.0.x、3.1.x has no bugs. Is it possible to cherry-pick [pr11919](https://github.com/apache/dolphinscheduler/pull/11919)

@lugela cherry-picked by https://github.com/apache/dolphinscheduler/pull/12894 , thanks for letting us know this.

**Comment by caishunfeng** [comment]
I test DateSource: MySQL and PGSQL,  Alert Plugin: Email,  FeiShu, Script,  they can work normally.

**Comment by EricGao888** [comment]
3.0.2 has been released on Nov. 22nd, 2022
