### ISSUE TITLE
[Improvement][Datasource]It is unnecessary to check the validity when saving the data source

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#12896]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

It is unnecessary to check the validity when saving the data source.  

Eg:   
The datasource is only open to the specified worker, but we cannot connect it from API-SERVER. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
+1 i will improve it.

**Comment by caishunfeng** [comment]
> +1 i will improve it.

@DarkAssassinator I had merged the pr :smiling_face_with_tear: 
@insist777 next time please leave the comment before submitting pr.

**Comment by DarkAssassinator** [comment]
> > +1 i will improve it.
> 
> @DarkAssassinator I had merged the pr 🥲 @insist777 next time please leave the comment before submitting pr.

@caishunfeng , sure, welcome anyone to help fix issues. 
@insist777 thx bro
