### ISSUE TITLE
[Bug] [Resource] Create resource by online-create API return null data

### ISSUE THREAD

**Issue by zuzuviewer** [apache/dolphinscheduler#12898]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Create resource by online-create API return null data, expect return created Resource data

### What you expected to happen

return Resource data created by online-create api

### How to reproduce

request create resource by dolphinscheduler/resources/online-create

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hstdream** [comment]
Please provide detailed reproduction steps and error log, thank you.

**Comment by zuzuviewer** [comment]
> equest create resource by dolphinscheduler/resources/online-create

Request create resource by dolphinscheduler/resources/online-create API, and it response with null data, expect created resource data

**Comment by zuzuviewer** [comment]
> Please provide detailed reproduction steps and error log, thank you.

Request create resource by dolphinscheduler/resources/online-create API, and it response with null data, expect created resource data, no error

**Comment by Zzihh** [comment]
Please provide request parameters and related logs.
