### ISSUE TITLE
[Improvement][Resource Center] Return empty list instead of throwing errors when detecting no path existed for a tenant resource path

### ISSUE THREAD

**Issue by EricPyZhou** [apache/dolphinscheduler#12901]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In the current implementation, we throw a general error when a tenant resource path is not found in a file system. Based on suggestions from @SbloodyS , Returning empty lists for tenants that don't have resource path is a better implementation and will give users a smoother experience. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricPyZhou** [comment]
Based on opinions in the community, we actually have 2 options regarding this issue:
1. Do NOT throw an error. Instead, we return empty data lists.
2. Improve error messages for circumstances including:
    a. Resource Storage does not start up
    b. A tenant resource path is not found in Resource Storage.

Which option is more preferable? @SbloodyS @hstdream @calvinjiang @davidzollo

**Comment by SbloodyS** [comment]
I think simply just return an empty data list is ok since this is only the task definition, not the resource center.

**Comment by Radeity** [comment]
> I think simply just return an empty data list is ok since this is only the task instance definition, not the resource center.

+1

**Comment by EricPyZhou** [comment]
> 

so the plan for now is to return empty data list when fetching resource list in task definition (task modal). What about landing on the resource center? which one would you prefer @SbloodyS @Radeity?

I personally think behaviours for such cases should be same, in other words, empty list should be returned when landing on resource center without having a tenant resource path created.

**Comment by SbloodyS** [comment]
I think we should return the message like https://github.com/apache/dolphinscheduler/pull/12664#discussion_r1022548800 when landing on resource center without having a tenant resource path created. @EricPyZhou

**Comment by EricPyZhou** [comment]
> I think we should return the message like [#12664 (comment)](https://github.com/apache/dolphinscheduler/pull/12664#discussion_r1022548800) when landing on resource center without having a tenant resource path created. @EricPyZhou

ah okay, so the behaviours are different.
