### ISSUE TITLE
[Bug] [datax] grammatical analysis sql column [*] failed

### ISSUE THREAD

**Issue by hkun0120** [apache/dolphinscheduler#12919]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="827" alt="image" src="https://user-images.githubusercontent.com/3326406/202122164-9141acab-900c-462e-87b6-c6e12f2bf04e.png">

### What you expected to happen

[Bug] [datax] grammatical analysis sql column [*] failed

### How to reproduce

export datax_home?/?

### Version

3.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
AFAIK,it just a warn log.which don't   affect the use

**Comment by fuchanghai** [comment]
maybe we just need print message ?

**Comment by hkun0120** [comment]
this is because we lack the postgresqlreader and postrgresqlwriter.jar

**Comment by hkun0120** [comment]
> AFAIK,it just a warn log.which don't affect the use

yes,this is not the problem, I will print the error message
