### ISSUE TITLE
[Bug] [dolphinscheduler-tools] Mysql configurations not work for tools

### ISSUE THREAD

**Issue by chaclus** [apache/dolphinscheduler#12914]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

- If we set database to mysql in dolphinscheduler_env.sh, when running upgrade-schema.sh in tools, will get errors like Caused by: java.sql.SQLException: Access denied for user 'root'@'127.0.0.1' (using password: YES)

when mysql set in dolphinscheduler_env.sh
![image](https://user-images.githubusercontent.com/6264879/202091856-d264402b-ebc3-4b5a-b262-88dc0090e6c7.png)

the error when running upgrade-schema.sh in tools.
![image](https://user-images.githubusercontent.com/6264879/202092139-587292d7-3e1e-49e0-8ef2-649e8a198e06.png)

36.27.xx.xx  is my local external ip address.

- If we set database to postgresql in dolphinscheduler_env.sh, when running upgrade-schema.sh in tools, will get the the right address database url from dolphinscheduler_env.sh.

when postgresql set in dolphinscheduler_env.sh
![image](https://user-images.githubusercontent.com/6264879/202092651-5d92db18-99f8-4a12-a661-7b25691e85c8.png)

the error when running upgrade-schema.sh in tools.
![image](https://user-images.githubusercontent.com/6264879/202092571-6e900fe3-40ee-41dd-99ac-8d0c4afc3e1f.png)

By this I mean why the upgrade-schema.sh script recognizes the configured database url when postgresql is set up, but when mysql is set up, the database itself gets the local extranet ip address as the url. Rather than getting the database url from dolphinscheduler_env.sh

### What you expected to happen

Already described above.

### How to reproduce

Already described above.

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chaclus** [comment]
I am so sorry, it not a bug, just mysql password is wrong.  I apologize for the indiscreet report.

**Comment by DarkAssassinator** [comment]
> I am so sorry, it not a bug, just mysql password is wrong. I apologize for the indiscreet report.

it's ok, and please close this issue. thx
