### ISSUE TITLE
Flink SQL  org.apache.dolphinscheduler.plugin.task.flink/flink_stream   The jar for the task is required

### ISSUE THREAD

**Issue by tangbing2014** [apache/dolphinscheduler#12925]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when use Flink & Flink Stream sql type , the problem "The jar for the task is required" is disappear

### What you expected to happen

sql do not need jar

### How to reproduce

 use Flink & Flink Stream module  sql type 

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pandong2011** [comment]
Hello, can you provide more details on bug reappearance? thx

**Comment by tangbing2014** [comment]
` public void init() {
        logger.info("flink task params {}", taskExecutionContext.getTaskParams());

        flinkParameters = JSONUtils.parseObject(taskExecutionContext.getTaskParams(), FlinkParameters.class);

       if (flinkParameters == null || !flinkParameters.checkParameters()) {
            throw new RuntimeException("flink task params is not valid");
        }
        flinkParameters.setQueue(taskExecutionContext.getQueue());
        _setMainJarName();_

        FileUtils.generateScriptFile(taskExecutionContext, flinkParameters);
    }`


**if i use sql type , 'setMainJarName()' how to get? Code with the following judgment is ok.**

 if (flinkParameters.getProgramType() != ProgramType.SQL) {
       setMainJarName();
   }

**Comment by pandong2011** [comment]
> if i use sql type , 'setMainJarName()' how to get? Code with the following judgment is ok.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/100667564/202420994-2c1fc89e-8bf4-4a45-8804-128f332dd300.png">




> ` public void init() { logger.info("flink task params {}", taskExecutionContext.getTaskParams());
> 
> ```
>     flinkParameters = JSONUtils.parseObject(taskExecutionContext.getTaskParams(), FlinkParameters.class);
> 
>    if (flinkParameters == null || !flinkParameters.checkParameters()) {
>         throw new RuntimeException("flink task params is not valid");
>     }
>     flinkParameters.setQueue(taskExecutionContext.getQueue());
>     _setMainJarName();_
> 
>     FileUtils.generateScriptFile(taskExecutionContext, flinkParameters);
> }`
> ```
> 
> **if i use sql type , 'setMainJarName()' how to get? Code with the following judgment is ok.**
> 
> if (flinkParameters.getProgramType() != ProgramType.SQL) { setMainJarName(); }



> ` public void init() { logger.info("flink task params {}", taskExecutionContext.getTaskParams());
> 
> ```
>     flinkParameters = JSONUtils.parseObject(taskExecutionContext.getTaskParams(), FlinkParameters.class);
> 
>    if (flinkParameters == null || !flinkParameters.checkParameters()) {
>         throw new RuntimeException("flink task params is not valid");
>     }
>     flinkParameters.setQueue(taskExecutionContext.getQueue());
>     _setMainJarName();_
> 
>     FileUtils.generateScriptFile(taskExecutionContext, flinkParameters);
> }`
> ```
> 
> **if i use sql type , 'setMainJarName()' how to get? Code with the following judgment is ok.**
> 
> if (flinkParameters.getProgramType() != ProgramType.SQL) { setMainJarName(); }


You do not need to upload jars to use flink sql
<img width="808" alt="image" src="https://user-images.githubusercontent.com/100667564/202421823-ef1a4ac7-ef77-45f8-8176-ae0d42451e3c.png">

But you need to use yarn-per-job to submit your flink job
![image](https://user-images.githubusercontent.com/100667564/202421893-13733e3b-8871-41c7-ac40-63620ba1d891.png)

**Comment by pandong2011** [comment]
> ` public void init() { logger.info("flink task params {}", taskExecutionContext.getTaskParams());
> 
> ```
>     flinkParameters = JSONUtils.parseObject(taskExecutionContext.getTaskParams(), FlinkParameters.class);
> 
>    if (flinkParameters == null || !flinkParameters.checkParameters()) {
>         throw new RuntimeException("flink task params is not valid");
>     }
>     flinkParameters.setQueue(taskExecutionContext.getQueue());
>     _setMainJarName();_
> 
>     FileUtils.generateScriptFile(taskExecutionContext, flinkParameters);
> }`
> ```
> 
> **if i use sql type , 'setMainJarName()' how to get? Code with the following judgment is ok.**
> 
> if (flinkParameters.getProgramType() != ProgramType.SQL) { setMainJarName(); }


You do not need to upload jar to use flink sql

<img width="808" alt="image" src="https://user-images.githubusercontent.com/100667564/202422990-f325e812-a0ab-4656-8932-bc969ba9dcfe.png">


But you need to use yarn-per-job to submit your flink job

![image](https://user-images.githubusercontent.com/100667564/202423009-363b6b4d-60f6-4c3b-bf74-d563b043beb3.png)

**Comment by tangbing2014** [comment]
sry, I just saw the bug has been fixed in version 3.1.1 release .
thank you for your help.
