### ISSUE TITLE
[Bug] [resource] storage not startup

### ISSUE THREAD

**Issue by Pdsmsf** [apache/dolphinscheduler#12920]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Ver:3.1.1 
Standalone
request: serverIP/dolphinscheduler/resources
response:{"code":60002,"msg":"storage not startup","data":null,"failed":true,"success":false}

### What you expected to happen

create success

### How to reproduce

Ver:3.1.1 
Standalone
request: serverIP/dolphinscheduler/resources
response:{"code":60002,"msg":"storage not startup","data":null,"failed":true,"success":false}

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
hi @Pdsmsf , as i know, this is not a bug. Please check the `resource.storage.type` configuration. U should config it to HDFS, S3, OSS.
