### ISSUE TITLE
[Bug] [dolphinscheduler-task-sql] sql task error！！！！

### ISSUE THREAD

**Issue by hkun0120** [apache/dolphinscheduler#12924]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/3326406/202340535-5e657ea2-4b94-460a-ae91-b45f3b6c8a06.png)

### What you expected to happen

try to  connect postgresql ,sometimes we got the error,what can i do ,the connection param is right . Version is 3.0.0

### How to reproduce

..

### Version

3.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
hi @hkun0120 , may u should check your sql and params.

**Comment by hkun0120** [comment]
> hi @hkun0120 , may u should check your sql and params.

yes ,after check.SQL is oK. and the null is from connection.not THE EXECUTE SQL.
<img width="863" alt="image" src="https://user-images.githubusercontent.com/3326406/202350131-d8b24bbb-6642-42e8-92b1-b461b4920099.png">
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/3326406/202350179-c8e065cd-0044-4235-8c12-aae375d70957.png">

**Comment by hkun0120** [comment]
connection is null ,why this happens

**Comment by DarkAssassinator** [comment]
> connection is null ,why this happens

this is 3.0.x source code?

**Comment by hkun0120** [comment]
> > connection is null ,why this happens
> 
> this is 3.0.x source code?

logger.info is I add later

**Comment by hkun0120** [comment]
@ruanwenjun 大神帮忙，看看能不能给点思路

**Comment by hkun0120** [comment]
今天不报错了，估计是我们积压的task太多，导致占据了连接数
