### ISSUE TITLE
[Improvement][Task] dolphinscheduler    Whether crontab is supported for supplementary data entry ?

### ISSUE THREAD

**Issue by qiangzai201611** [apache/dolphinscheduler#12936]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Select a time range and filter out the matching time using the crontab rule. Then supplement the data according to these times。

Because the current tasks are scheduled using the crontab

That's a good idea

例如：我的任务，需要在每月的5号，进行调度执行，然后我要补之前的一年的数据，现在 需要在  2022年的1月1号，到 2022年的11月18号这个范围内，设置crontab 的规则，每月的五号进行调度，然后他在这个时间范围内执行crontab 跑出来的这些时间
          还有周任务，小时任务，等，如果支持了  时间范围内的crontab 调度，海豚的数据补充，将会更加完美

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qiangzai201611** [comment]
dolphinscheduler&nbsp; version&nbsp; 2.7.0

















夜孤行
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月18日(星期五) 下午4:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] dolphinscheduler   Whether crontab is supported for supplementary data entry ? (Issue #12936)





 
Thank you for your feedback, we have received your issue, Please wait patiently for a reply.
  
In order for us to understand your request as soon as possible, please provide detailed information、version or pictures.
 
If you haven't received a reply for a long time, you can join our slack and send your question to channel #troubleshooting

**Comment by shangeyao** [comment]
Good idea！It's a nice feature. Please assign to me.

**Comment by shangeyao** [comment]
This function has been implemented in dev branch.

**Comment by EricGao888** [comment]
Closed by https://github.com/apache/dolphinscheduler/issues/12936#issuecomment-1321372383
