### ISSUE TITLE
mvn package bug

### ISSUE THREAD

**Issue by zhangxn8** [apache/dolphinscheduler#12941]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

use build command >mvn clean install -Prelease -Dmaven.test.skip=true -Dcheckstyle.skip=true

path dolphinscheduler\dolphinscheduler-dist\target bin package 

![image](https://user-images.githubusercontent.com/22562144/202835790-dadbb4f2-ad4b-4164-8e60-3d4520c43978.png)

### What you expected to happen

jar name incomplete

### How to reproduce

![image](https://user-images.githubusercontent.com/22562144/202835829-e6fb9efb-e562-4788-94f3-c7d2f8580951.png)

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
hi @zhangxn8 , i do not think this is a DS bug, should be a PC maven env issue.
