### ISSUE TITLE
[Improvement][UI] Suggest to add a feature that users can drag the column of workflow name to resize its width.

### ISSUE THREAD

**Issue by calvinjiang** [apache/dolphinscheduler#12943]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The workflow name on the page of workflow definition could be too long to see its name at times. Although providing the tooltip to see the whole name, it's still kind of less convenient. So I'd suggest to add a feature that users can drag the column of workflow name to resize its width.

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/4928204/202849833-c932f86e-c4f6-4ee8-ad56-0be144b7760d.png">

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
a good improvement
