### ISSUE TITLE
[Improvement][Task Plugin] Make task plugin loading configurable

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#12959]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Many users does not need all of DS task plugins. It would be handy if they could configure what to pick through configurations.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jieguangzhou** [comment]
Good idea, can we config that in the Web server?

**Comment by EricGao888** [comment]
> Good idea, can we config that in the Web server?

No, currently we can't. It is easy to choose what not to load from the backend part. But I have no idea how to make it work for the front-end part. May I ask whether you have any ideas? @songjianet @Amy0104 @devosend

**Comment by fuchanghai** [comment]
> > Good idea, can we config that in the Web server?
> 
> No, currently we can't. It is easy to choose what not to load from the backend part. But I have no idea how to make it work for the front-end part. May I ask whether you have any ideas? @songjianet @Amy0104 @devosend

can  we storage plugin name in  DB that user does not need?  ,when we start the application  filter that
<img width="939" alt="image" src="https://user-images.githubusercontent.com/33984497/203474398-524d7816-1f09-4450-859f-97022fa77ce2.png">

**Comment by EricGao888** [comment]
> > > Good idea, can we config that in the Web server?
> > 
> > 
> > No, currently we can't. It is easy to choose what not to load from the backend part. But I have no idea how to make it work for the front-end part. May I ask whether you have any ideas? @songjianet @Amy0104 @devosend
> 
> can we storage plugin name in DB that user does not need? ,when we start the application filter that <img alt="image" width="939" src="https://user-images.githubusercontent.com/33984497/203474398-524d7816-1f09-4450-859f-97022fa77ce2.png">

I was planning to do it with configurations instead of adding more interactions with DB. For example, users could provide a list of plugins they want to use in `common.properties` or `application.yaml`, and `TaskPluginManager` will only load these types.
