### ISSUE TITLE
[Bug] [zookeeper] the node IP in the worker group connet be updated automatically

### ISSUE THREAD

**Issue by wtttt123456** [apache/dolphinscheduler#12950]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After the worker restarts, the IP changes, but the custom node IP in the worker group cannot be automatically updated along with the default node. Later, it was found that the custom node was not successfully created in zookeeper

### What you expected to happen

The original version 1.0 is automatically updated normally, and the current version 3.0 cannot be automatically updated

### How to reproduce

Recurrence method: customize the worker node, restart the worker container, the IP changes, but the IP of the custom node does not change

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
hi @wtttt123456, please describe this issue in English. And u mean that cannot update the worker IP in zk?

**Comment by hkun0120** [comment]
> 

yes, when I create new worker group, name "newG " for example,and restart the container in k8s cluster ,and the IP address is updated in default worker group,but the newG worker group's container ip is not updated at the same time,the ip is the old container's,which is not exists now.

**Comment by DarkAssassinator** [comment]
hi @hkun0120 , as i know, this is not a bug, this is a feature, now DS will not update the worker group by monitor other worker group in zk. So u should update it in the UI manually. Because DS 3.0.x+ just mantain Worker group in DB.

**Comment by hkun0120** [comment]
> hi @hkun0120 , as i know, this is not a bug, this is a feature, now DS will not update the worker group by monitor other worker group in zk. So u should update it in the UI manually. Because DS 3.0.x+ just mantain Worker group in DB.

@DarkAssassinator thank you very much. there is another question, the Default worker-group has all IP,and other workergroup has serveral ip, does this mean DS recommand us to use default worker-group?

**Comment by DarkAssassinator** [comment]
> > hi @hkun0120 , as i know, this is not a bug, this is a feature, now DS will not update the worker group by monitor other worker group in zk. So u should update it in the UI manually. Because DS 3.0.x+ just mantain Worker group in DB.
> 
> @DarkAssassinator thank you very much. there is another question, the Default worker-group has all IP,and other workergroup has serveral ip, does this mean DS recommand us to use default worker-group?

hi @DarkAssassinator, DS does not recommend which Worker group to use, because the decision depends on the user's own real demands. The default Worker group just includes all worker nodes, but if you need to specify tasks to run on a specific server or list of servers, you need to specify a workgroup.
