### ISSUE TITLE
[Bug] [deploy]  java path is incorrect

### ISSUE THREAD

**Issue by zhangfane** [apache/dolphinscheduler#12956]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I deployed dolphinscheduler version 3.1.1 based on kubernetes, unfortunately, it does not work properly and reports the following error.
`./bin/start.sh: line 30: /usr/local/openjdk-8/bin/java: No such file or directory`

### What you expected to happen

I noticed that in this issue   #12334 , the base image of dolphinscheduler is adjusted to 「eclipse-temurin:8-jre 」and the path of java is changed to 「/opt/java/openjdk」, we need to synchronize the default values of value in the helm package 。

### How to reproduce

refer to deploy document to deploy dolphinscheduler:v3.1.1

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lifehacking** [comment]
dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler-xxx  not  update java path？
