### ISSUE TITLE
[BUG] process can not be modify after the user deleted

### ISSUE THREAD

**Issue by KEN-LJQ** [apache/dolphinscheduler#1296]
**Describe the bug**
After admin delete an user, which has create a lot process. Those process and process instance still can view and run by other user, but no one can modify this process because it is empty when you open the process editor.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Create an user like 'testUser' by admin
2. Login in with user 'testUser'
3. Create a process 'processA'
4. Admin delete this 'testUser' user
5. Login with other user, and view the process 'processA' which we just create in ProcessDefinition
6. Click the edit button open the process editor
7. You will find out the editor is empty

**Expected behavior**
Current authorization strategy, each user can modify any process under same project, no matter they create this process or not. So I think it is reasonable that the process still can be modify, even though the create user has deleted.

**Screenshots**
![image](https://user-images.githubusercontent.com/16650282/69134984-56ee2600-0af3-11ea-9c9b-dc9a5b5d9edd.png)
if you open the process which user has deleted, you will get this, the task not show

**Which version of Dolphin Scheduler:**
 -[1.1.0]

**Additional context**
We make each developer has their own account, and develop their the process for same project, and one process may depend the other one, that's what I think the user design for. But we may delete a user if they quit, a this time, it mean we lost and can not modify the process any more.

**Requirement or improvement**
- I think the process belong to project and some one who has authorized permission can delete or modify them is better

**Comment by xingchun-chen** [comment]
Thanks for the feedback, we will fix it in the new version

**Comment by lgcareer** [comment]
you can use administrator to update

**Comment by zhongjiajie** [comment]
For now, you have to transfer the user's projects before you delete them, otherwise would get an error as below.
![image](https://user-images.githubusercontent.com/15820530/148037589-301a917d-56de-40bf-ac10-192f3c5e7052.png)
