### ISSUE TITLE
[Bug] [complement] Startup parameters cannot update global variables

### ISSUE THREAD

**Issue by ShawshankLin** [apache/dolphinscheduler#12960]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Startup parameters cannot update global variables

![1669099816815](https://user-images.githubusercontent.com/16248686/203244623-bc9b7355-370d-4354-bae2-b2b642de9617.png)

3. x Version is normal

### What you expected to happen

Startup configuration parameters can override the update global variables, otherwise a workflow cannot start multiple instances with different global variables

### How to reproduce

The boot parameter setting of the complement updates the global variable

### Version

2.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
@ShawshankLin Actually, start parameters can override global parameters in version 3.x, do you mean that's a bug in 2.x version and have to be solved in next 2.x version?

**Comment by Radeity** [comment]
@SbloodyS You can assign me. Can i ask that if i should develop base on the latest branch of 2.x for maintaining 2.x version?

**Comment by SbloodyS** [comment]
> @SbloodyS You can assign me. Can i ask that if i should develop base on the latest branch of 2.x for maintaining 2.x version?

Yes.

**Comment by ShawshankLin** [comment]
> @ShawshankLin Actually, start parameters can override global parameters in version 3.x, do you mean that's a bug in 2.x version and have to be solved in next 2.x version?

yes
