### ISSUE TITLE
[Bug] startParams  Not in effect

### ISSUE THREAD

**Issue by CRUDKanade** [apache/dolphinscheduler#12967]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/71861187/203256068-bbf06d93-61b0-4aa9-a28e-d43f6ba67164.png)

![image](https://user-images.githubusercontent.com/71861187/203256530-88f667a6-229a-4b96-9610-511242900278.png)

![image](https://user-images.githubusercontent.com/71861187/203256179-528427ad-6268-44ec-8ba3-ac329007d13f.png)

设置了启动参数 , 但是没生效

### What you expected to happen

启动参数生效

### How to reproduce

添加spark工作流 , 主程序参数定义${}变量 , 执行一次时启动参数设置该变量的值

### Version

2.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
English is needed
