### ISSUE TITLE
[Bug] Failed to export and then import the project.

### ISSUE THREAD

**Issue by ShawshankLin** [apache/dolphinscheduler#12966]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Failed to export and then import the project. The id of the branch flow does not correspond

![image](https://user-images.githubusercontent.com/16248686/203253008-d8752ed7-6f2d-4d34-a655-a33a51b8e613.png)

### What you expected to happen

Normal import and export 

### How to reproduce

import and export project with condition task

### Version

2.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
@SbloodyS I'll check and fix it.

**Comment by gnailJC** [comment]
```    
public void setNextNode(Object nextNode) {
        if (nextNode instanceof Long) {
            this.nextNode = (Long) nextNode;
        } else {
            List<String> nextNodes = (ArrayList) nextNode; // CaseError
            if (CollectionUtils.isNotEmpty(nextNodes)) {
                this.nextNode = Long.parseLong(nextNodes.get(0));
            }
        }
    }
````
<img width="749" alt="image" src="https://user-images.githubusercontent.com/31072303/218965398-a007d573-3e62-4d1d-99f6-5c251d60fea0.png">

An CaseError will occur if the nextNode is empty when `branch flow` is not set.
