### ISSUE TITLE
[PROPOSAL] dolphinscheduler-warehouse

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/dolphinscheduler#12971]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

With dolphinscheduler landing on ziroom, we have experienced nearly a year of use and secondary development, summarizing many interesting experiences.
1. dolphinscheduler main use scenario: offline number warehouse field

2. dolphinscheduler's webui provides to create DAG by dragging and dropping, which is not friendly in the face of business scenarios with complex correlations.

3. There will be some unique problems for the offline data warehouse vertical. We developed a more suitable development platform for offline data warehouse based on dolphinscheduler, a scheduling engine.

4. Based on the above, we have developed a new platform to achieve: complex Hql automated generation scheduling, data dependency support, more powerful periodic replenishment, more convenient alerts, clearer log display, and realized the support of data pedigree and data insight. Currently, we are also developing the ability to generate and schedule FlinkSQL pedigree analysis with one click

5.The newly developed platform is designed at the beginning to be compatible with multiple versions, so it is completely decoupled from dolphinscheduler, only the packaged jar, put into the lib directory of dolphinscheduler, and it is done ready.

6.I would like to contribute it as a sub-project of dolphinscheduler, positioning: the offline data warehouse vertical, to achieve a common offline data warehouse solution in the industry, to meet the needs of users to build offline data warehouses.

### Use case
For an offline number warehouse task, it is often ods->dwd->rds layer by layer dependency, which requires the number warehouse development worker to use scheduling, and the current development task can be executed only when all the upstream tables are output.
The following 👇 is a standard inline task.
sql="INSERT overwrite TABLE bl_ugc.sr_living_expenses_group_table partition(dt='$[yyyyMMdd-1]')
select 
case_code,
classfication_type_name,
classfication_one_name,
classfication_two_name,
classfication_three_name,
classfication_four_name,
a_type_name,
b_type_name,
create_time,
case_end_time,
process_name,
process_start_time,
process_end_time,
handler_city_name,
handler_warzone_name,
handler_region_name,
handler_big_group_name,
handler_group_name,
handler_sgroup_name,
handler_minigourp_name,
handler_name,
handler_code,
evaluation,
sum(process_urge) as process_urge,
sum(transfer) as transfer,
city_name,
warzone_name,
region_name,
gourp_name,
rating_address,
resblock_name,
resblock_id,
house_source_code,
product_line_name,
product_version_name,
summary_case,
income_identity,
living_expenses_item,
payment_method,
finish_duration,
t_evaluate_date

from 
(select 
a.case_code,
a.classfication_type_name,
a.classfication_one_name,
a.classfication_two_name,
a.classfication_three_name,
a.classfication_four_name,
b.a_type_name,
b.b_type_name,
a.create_time,
a.case_end_time,
a.process_name,
a.process_start_time,
a.process_end_time,
a.handler_city_name,
a.handler_warzone_name,
a.handler_region_name,
a.handler_big_group_name,
a.handler_group_name,
a.handler_sgroup_name,
a.handler_minigourp_name,
a.handler_name,
a.handler_code,
null as evaluation,
count(DISTINCT if((a.agent_process_urge_times+a.user_process_urge_times)>0,a.case_code,NULL)) AS process_urge,
count(DISTINCT if(a.handler_name<>a.the_next_handler_name and a.the_next_process_name not regexp'评价|结束',a.case_code,NULL)) AS transfer,
b.city_name,
b.warzone_name,
b.region_name,
b.gourp_name,
b.rating_address,
b.resblock_name,
b.resblock_id,
b.house_source_code,
b.product_line_name,
b.product_version_name,
b.summary_case,
b.income_identity,
b.living_expenses_item,
b.payment_method,
b.finish_duration,
b.t_evaluate_date

from bl_ugc.sr_case_process_info as a
left join bl_ugc.sr_living_expenses_table as b on a.case_code=b.sr_case_code
and b.dt='$[yyyyMMdd-1]'
where a.dt='$[yyyyMMdd-1]'
and a.process_name not regexp'x|x'
AND a.classfication_one_name IN ('xxxx',
                                   'xxxx')
  AND a.classfication_two_name='xx'
  AND a.classfication_four_name IN('xxxx/x',
                                   'x/xx',
                                   'x/x',
                                   'xx/x',
                                   'x/x',
                                   'x',
                                   'x')
group by a.case_code,
a.classfication_type_name,
a.classfication_one_name,
a.classfication_two_name,
a.classfication_three_name,
a.classfication_four_name,
b.a_type_name,
b.b_type_name,
a.create_time,
a.case_end_time,
a.process_name,
a.process_start_time,
a.process_end_time,
a.handler_city_name,
a.handler_warzone_name,
a.handler_region_name,
a.handler_big_group_name,
a.handler_group_name,
a.handler_sgroup_name,
a.handler_minigourp_name,
a.handler_name,
a.handler_code,
b.city_name,
b.warzone_name,
b.region_name,
b.gourp_name,
b.rating_address,
b.resblock_name,
b.resblock_id,
b.house_source_code,
b.product_line_name,
b.product_version_name,
b.summary_case,
b.income_identity,
b.living_expenses_item,
b.payment_method,
b.finish_duration,
b.t_evaluate_date
union all

select 
sr_case_code as case_code,
type_name as classfication_type_name,
classfication_one_name,
classfication_two_name,
classfication_three_name,
classfication_four_name,
a_type_name,
b_type_name,
create_time,
case_finish_time as case_end_time,
null as process_name,
null as process_start_time,
null as process_end_time,

evaluate_city_name as handler_city_name,
evaluator_warzonename as handler_warzone_name,
evaluator_region_name as handler_region_name,
evaluator_branch_department as handler_big_group_name,
evaluator_area_name as handler_group_name,
evaluator_group_name as handler_sgroup_name,
evaluator_small_group_name as handler_minigourp_name,
staff_name as handler_name,
t_be_evaluator_id as handler_code,
evaluation,
0 as process_urge,
0 as transfer,
city_name,
warzone_name,
region_name,
gourp_name,
rating_address,
resblock_name,
resblock_id,
house_source_code,
product_line_name,
product_version_name,
summary_case,
income_identity,
living_expenses_item,
payment_method,
finish_duration,
t_evaluate_date
from bl_ugc.sr_living_expenses_table as t
where t.dt='$[yyyyMMdd-1]'
and t.data_type='明细维度') as z
group by 
case_code,
classfication_type_name,
classfication_one_name,
classfication_two_name,
classfication_three_name,
classfication_four_name,
a_type_name,
b_type_name,
create_time,
case_end_time,
process_name,
process_start_time,
process_end_time,
handler_city_name,
handler_warzone_name,
handler_region_name,
handler_big_group_name,
handler_group_name,
handler_sgroup_name,
handler_minigourp_name,
handler_name,
handler_code,
process_urge,
transfer,
city_name,
warzone_name,
region_name,
gourp_name,
rating_address,
resblock_name,
resblock_id,
house_source_code,
product_line_name,
product_version_name,
summary_case,
income_identity,
living_expenses_item,
payment_method,
finish_duration,
t_evaluate_date,evaluation
"
)
Here if you use the native dolphinscheduler platform, you need to sort out the complex dependencies between tables and fill them in manually, and you also need to learn a lot of pre-knowledge that is not related to offline data warehouse development, and you need to face a lot of irrelevant components, which can cause a lot of trouble for developers.

But when you use our customized `dolphinscheduler-warehouse` for offline data warehouse development, it will be much different:
Automatically determine whether the dependency is a task of ds [task dependency] or a data partition of hive [data dependency] by parsing the relevant input and output tables of the Hql syntax based on the maintained lineage
<img width="1366" alt="图片" src="https://user-images.githubusercontent.com/60029759/205741111-683e0b79-3076-4467-a298-44f72ff01d3f.png">

<img width="1085" alt="图片" src="https://user-images.githubusercontent.com/60029759/205744967-41183ba4-827b-4d35-a5f5-9a4eded6d0e0.png">

Bloodlines and scheduling go hand in hand, so we can make very clear insights into the data
<img width="1228" alt="图片" src="https://user-images.githubusercontent.com/60029759/205744656-f66a3c74-ed30-4d28-9f02-073f3fc15202.png">

Of course if you use this even sql can not write but want to implement business logic, while configuring scheduling, we also provide the following way. Dynamically generate a sql by simply filling in the fields and automatically parse the scheduling.
<img width="1273" alt="图片" src="https://user-images.githubusercontent.com/60029759/206167564-3e2e9563-e6b1-4816-bda9-543941c37635.png">
<img width="1263" alt="图片" src="https://user-images.githubusercontent.com/60029759/206167662-934b1d97-4a9a-4247-97d6-ec87c76b054d.png">
<img width="1360" alt="图片" src="https://user-images.githubusercontent.com/60029759/206167708-99e06fa2-f52c-4fd0-b05c-b81d32e618c7.png">
<img width="1203" alt="图片" src="https://user-images.githubusercontent.com/60029759/206167796-a91c44c2-4a65-4dc9-8e07-4b952db29b21.png">

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Is similar to https://github.com/apache/dolphinscheduler/issues/7156, we have discuss before

**Comment by zhongjiajie** [comment]
Hi @MonsterChenzhuo we should correct the issue describe to the right one, to let others understand our mean. Then we will send an email to discuss the feature, and we may probably create a new repository to keep its codebase

**Comment by MonsterChenzhuo** [comment]
hi @zhongjiajie I have reworked my proposal. Please take a look, are there any other problems?

**Comment by zhongjiajie** [comment]
Hi @MonsterChenzhuo thank for you update the proposal, and know you use the keyword "complex Hql automated generation scheduling". and as we show the demo in our latest meeting, I think is more likely to be auto dependence maker or some thing like https://github.com/apache/dolphinscheduler/issues/7156. WDYT?

**Comment by wenqihui** [comment]
Is there any progress on this feature
