### ISSUE TITLE
[Feature][Module Name] dolphinscheduler2.x, 3.x support Apache Ambari deployment

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/dolphinscheduler#12970]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

At present, there are still a large number of companies in China using Apache Ambari for the deployment of big data services, and for the characteristics of dolphinscheduler services with many configuration parameters, Apache Ambari is a good management tool for dolphinscheduler

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Hi @MonsterChenzhuo support the latest version of dolphinscheduler deploy to Ambari, you can add PR to repo https://github.com/apache/dolphinscheduler-ambari

**Comment by zhongjiajie** [comment]
Hi @MonsterChenzhuo I migrate this into https://github.com/apache/dolphinscheduler-ambari/issues/2, close it
