### ISSUE TITLE
[Feature][Master] Run single task in workflow instance

### ISSUE THREAD

**Issue by jieguangzhou** [apache/dolphinscheduler#12978]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/31528124/205628027-3ff52cd8-96b3-49ad-82bf-4e0601a9858b.png">

### UI
- In the `Workflow Instance` page, add three buttons if we Right-click the task
- In the `Workflow Instance` page, if we save the workflow instance, will refresh instead of returning the` workflow instance list` page. (Because we can execute the task after editing the task definition directly)

### Backend
- Add an interface `executeTask` to execute the task
- add a new function to clear data of existing task instance
- fix the bug of inserting double same TaskDefinitionLogs in saveTaskDefine. (This will make some errors if we add and edit a new task definition in the workflow instance page)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi, @jieguangzhou, i just find that in current implementation, DS doesn't have input parameter check when running single task in workflow definition. I think whether run single task in workflow definition or workflow instance, it should be taken into account. Whether or not we should create another PR to handle it?

**Comment by jieguangzhou** [comment]
> Hi, @jieguangzhou, i just find that in current implementation, DS doesn't have input parameter check when running single task in workflow definition. I think whether run single task in workflow definition or workflow instance, it should be taken into account. Whether or not we should create another PR to handle it?

It is good to do parameter checking to help the user use the parameters correctly. Can we handle checking for global parameters because some tasks refer to parameters in other fields rather than custom parameters?

WDYT @zhongjiajie @Radeity

**Comment by Radeity** [comment]
> It is good to do parameter checking to help the user use the parameters correctly. Can we handle checking for global parameters because some tasks refer to parameters in other fields rather than custom parameters?

Hi, @jieguangzhou, i've mentioned in https://github.com/apache/dolphinscheduler/issues/12713 that we can not judge upstream output parameters without explicitly declaration. Are there any other good suggestions?

**Comment by jieguangzhou** [comment]
> > It is good to do parameter checking to help the user use the parameters correctly. Can we handle checking for global parameters because some tasks refer to parameters in other fields rather than custom parameters?
> 
> Hi, @jieguangzhou, i've mentioned in #12713 that we can not judge upstream output parameters without explicitly declaration. Are there any other good suggestions?

I don't see a better way to do it than an explicit definition.
