### ISSUE TITLE
[Improvement][Alert] Remove default alert group

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#12986]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* https://github.com/apache/dolphinscheduler/blob/db615ba284de8ab2782ef41ab412286357d77cb6/dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql#L1013-L1015
* Currently DS binds alert plugin instances with id 1 and 2 to `default alert group`, which may cause unexpected behavior.
* We might remove the initialization for default alert group, or find a more appropriate way. WDYT? @caishunfeng @ruanwenjun 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
+1 

This is a bad design, and it seems ds will use this alert group(id = 0) to send server up/down alert, we need to remove this alert group and use admin alert group to replace this.
