### ISSUE TITLE
[Bug] [Worker Group] Default Worker Group contain history and wrong records.

### ISSUE THREAD

**Issue by DarkAssassinator** [apache/dolphinscheduler#12981]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Default Worker group contain `default`、`XXXX:1234`、`worker`, all these 3 nodes were wrong.
+ `default` and `worker` not worker nodes.
+ `XXXX:1234` has stopped. Default worker group should not be contain this record.
![Image](https://user-images.githubusercontent.com/20518339/203567253-b0944986-1945-4cef-9dad-69457816c0fd.png)

And default worker group come from `workerNodeInfo`.
![image](https://user-images.githubusercontent.com/20518339/203567592-46d728a5-e508-4b2d-9081-34eeb23eb9a6.png)
But never remove the wrong and expired record from `workerNodeInfo`.
![image](https://user-images.githubusercontent.com/20518339/203567908-391e71a8-bd38-40b3-ac4e-503a223fc154.png)

### What you expected to happen

Default worker group should be correct.

### How to reproduce

Step 1: Start a Master service.
Step 2: Start a Worker service and then stop it.
Step 3: Check master log and u can find the following screenshot:
![Image](https://user-images.githubusercontent.com/20518339/203568180-fd5820c7-c9b1-48f6-817f-a2a2386aac8e.png)

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
we should remove `default` node in registry center, because now DS has removed WorkerGroup in registry, so i think that we do not need `woeker/default` node. WDYT. cc @ruanwenjun @caishunfeng @SbloodyS

**Comment by ruanwenjun** [comment]
> we should remove `default` node in registry center, because now DS has removed WorkerGroup in registry, so i think that we do not need `woeker/default` node. WDYT. cc @ruanwenjun @caishunfeng @SbloodyS

Yes, the correct way is to announce this in doc, or we clear the data in startup.

But I don't think this is a bug, this will not affect the other worker.
