### ISSUE TITLE
[Bug] [Flink Task] If the -t parameter is used in flink on yarn mode, some parameters become invalid   

### ISSUE THREAD

**Issue by Sky-Gu** [apache/dolphinscheduler#12989]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

flink task  command:
flink run -t yarn-per-job -ys 3 -ynm test-job -yjm 2G -ytm 4G -yqu default -p 3 -sae xxxx.jar

The -ynm parameter is invalid when using the -t boot mode.

Correct submit command: 
flink run -t yarn-per-job -ys 3-yjm 2G-ytm 4G-yqu default -p 3 - sae  -Dyarn.application. name=test-job

You need to boot with the -D parameter

### What you expected to happen

Normal yarn parameters are configured

### How to reproduce
flink version :1.14.X
Use yarn-per-job mode for any flink task
 

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by XiaoZhiSnow** [comment]
when use  run-application on flink 1.17.2 , the -ys 1 -yjm 1G -ytm 2G does not work.
