### ISSUE TITLE
no "source /usr/local/software/ds3.0.2/worker-server/conf/dolphinscheduler_env.sh"  

### ISSUE THREAD

**Issue by wangsong8586** [apache/dolphinscheduler#12996]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1、I create a workflow called testemv , it  contains a shell task onlly.
2、I create a environment called testenv01, it defines some os environment vairables
3、 If I run the workflow with the testenv01 , then it will not execute "source /usr/local/software/ds3.0.2/worker-server/conf/dolphinscheduler_env.sh" .  So some command will not be found properly
![image](https://user-images.githubusercontent.com/25869159/203925815-98eb9c1f-e21a-4528-9a0c-d326ac3cd78a.png)

4、If I run the workflow without testenv01, then it will execute "source /usr/local/software/ds3.0.2/worker-server/conf/dolphinscheduler_env.sh" . 
![image](https://user-images.githubusercontent.com/25869159/203925594-7b64538f-e1a4-4c14-a728-1fb11a7d7e76.png)

### What you expected to happen

Even If I run the workflow with a defined environment, it should execute 
"source /usr/local/software/ds3.0.2/worker-server/conf/dolphinscheduler_env.sh"

### How to reproduce

1、defines a workflow with a shell task
2、defines a environment 
3、run the workflow with the defined environment

### Anything else

3.0.2 version

### Version

3.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi, @wangsong8586 

If you specify a self-defined environment, DS will not source default env file `dolphinscheduler_env.sh`, instead, add your env config(highlight in blue box) into command file.
<img width="900" alt="image" src="https://user-images.githubusercontent.com/45198818/203936691-bdc47b66-cbc3-4e1b-992f-eae148799e3b.png">

**Comment by wangsong8586** [comment]
OK, I understand. Thank you for your reply.
