### ISSUE TITLE
 dolphinscheduler 1.3.1  User permission problem

### ISSUE THREAD

**Issue by zhangxinjian123** [apache/dolphinscheduler#12991]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, the DolphinScheduler is relatively simple in controlling permissions. It hopes to add operation permission control when authorizing projects and resource centers to separate read and write permissions.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @zhangxinjian123 , 1.3.1 is no longer in the maintenance list. You can try a new version.
