### ISSUE TITLE
[Doc][pseudo-cluster.html] Preparation of zookeeper should up to 3.5.0+

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#13000]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

because of  dolphin use curator 5.x as zookeeper client library , [it is no longer support zk 3.4.x ](https://curator.apache.org/zk-compatibility-34.html).

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
hi @lordk911 , this case has been fixed, please check https://github.com/apache/dolphinscheduler/issues/12284

**Comment by kk467415728** [comment]
Hi， out cluster zk version is 3.5.7 . We plan to upgrade the DS2.0.5 version to version 3.1.3, Do I have to upgrade the version of zk to 3.8 ？Will there be any problems with zk 3.5?
