### ISSUE TITLE
[Bug] [worker-server] wrong permission setting of worker-server's config dir

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#13027]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have a linux user , when I use it as tenant to run task , he has no Permission to access {dolphin_home}/worker-server/conf/dolphinscheduler_env.sh

<img width="772" alt="企业微信截图_965ec947-d4e5-4886-9a04-7634e52b7107" src="https://user-images.githubusercontent.com/19989300/204249229-26c36e50-6a55-4894-afb1-d79a4bab30ad.png">

<img width="786" alt="企业微信截图_e70bf0c4-eb43-4bdd-a63f-9869c56d7d36" src="https://user-images.githubusercontent.com/19989300/204249346-fd53c01b-de0c-4b2c-826f-d86d82a29873.png">

<img width="623" alt="企业微信截图_0b1d64b9-991d-48b0-82a3-07f2befae577" src="https://user-images.githubusercontent.com/19989300/204249589-a868792e-4ca2-4217-ba6d-73e25b5bac6b.png">

### What you expected to happen

why the conf dir permission is 700 ? even I change it to 755 , after restart it will go back to 700

### How to reproduce

centos7
create a user and use it as a tenant

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
hi @lordk911 , this issue has been fix in #12909

**Comment by lordk911** [comment]
> hi @lordk911 , this issue has been fix in #12909
will the PR merge to 3.0.x ?
