### ISSUE TITLE
[Bug] wrong timezone used when logback write log

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#13026]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

the master-server or worker-server log didn't use the local time zone

<img width="623" alt="企业微信截图_0e8eafba-81c2-4fff-8e58-18cab543a74e" src="https://user-images.githubusercontent.com/19989300/204246896-d53ace12-92d4-46e9-9bfd-9abe36118d2e.png">

### What you expected to happen

use the right timezone to show log

### How to reproduce

it a bug

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
hi @lordk911 , this is not a bug, because log use UTC time. Please check the doc: https://dolphinscheduler.apache.org/en-us/docs/3.0.0/user_doc/guide/howto/general-setting.html

**Comment by lordk911** [comment]
> hi @lordk911 , this is not a bug, because log use UTC time. Please check the doc: https://dolphinscheduler.apache.org/en-us/docs/3.0.0/user_doc/guide/howto/general-setting.html

thanks ，my mistake , I give the wrong timezone
