### ISSUE TITLE
[Bug] [data-quality] data-quality write error_data to hdfs faild

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#13025]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

as https://github.com/apache/dolphinscheduler/issues/11449#issue-1336822412 , I got the same error.

after config master-server/conf/common.properties: resource.hdfs.fs.defaultFS  and restart , data-quality can use the right hdfs cluster name.  but after I modify the data-quality task and run again , the task faild again with the same error about used wrong hdfs cluster name.

### What you expected to happen

data-quality can use the right hdfs cluster name , how to config it exactly？

### How to reproduce

as https://github.com/apache/dolphinscheduler/issues/11449#issue-1336822412

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lordk911** [comment]
@zixi0825 do you know about this?

**Comment by lordk911** [comment]
need to config master-server/conf/common.properties is not mentioned in document.

**Comment by sincere0104** [comment]
你好，问题解决了吗，我也遇到了同样的问题

**Comment by sincere0104** [comment]
> @zixi0825 do you know about this?

你好，可以加个vx么？zheng765218939
