### ISSUE TITLE
[Bug] [data-quality & master-server] wrong logic when master-server check data-quality result

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#13035]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I'm using 3.0.3-SNAPSHOT , I made a data-quality task for test , the wrong data have been write to hdfs , but at last the task was in success state.
I find that the master-server code : DataQualityResultOperator.java line 98 ：
https://github.com/apache/dolphinscheduler/blob/a28e206166a10010d36a5dc0d9e2fd54f799678b/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/utils/DataQualityResultOperator.java#L98

the isFailure method directly return the compare result 

https://github.com/apache/dolphinscheduler/blob/a28e206166a10010d36a5dc0d9e2fd54f799678b/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/utils/DataQualityResultOperator.java#L142

https://github.com/apache/dolphinscheduler/blob/a28e206166a10010d36a5dc0d9e2fd54f799678b/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/utils/DataQualityResultOperator.java#L176

there need a "!" operater in the isFailure method.

this task should be faild in process :

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/19989300/204428710-6a42fbb3-83b9-471d-9cfd-a9426b25cab0.png">

### What you expected to happen

correct the logic of the master when handle the data-quality result.

### How to reproduce

just have a test of data-quality task in process.

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lordk911** [comment]
@zixi0825

**Comment by jieguangzhou** [comment]
Hey @lordk911 , can you help to fix
