### ISSUE TITLE
[Bug] [Resource Center] can not get resource list

### ISSUE THREAD

**Issue by zhangfane** [apache/dolphinscheduler#13033]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The refactoring of the Resource Center to use a third-party storage interface to manage resources was completed in this PR. But it seems that the refactoring is not all done?
I uploaded the Jar package in the resource center and the flink task only gets an empty list of resources

### What you expected to happen

The flink task can get the list of resources normally

### How to reproduce

upload jar package and crate flink task

### Anything else

In ResourceMapper, it is found that there are still many objects checking resources through the t_ds_resources table

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangfane** [comment]
@EricPyZhou

**Comment by EricPyZhou** [comment]
> @EricPyZhou

Thanks for pinging.  Let me check

**Comment by zhangfane** [comment]
Do we no longer need `t_ds_resources` when considering version compatibility? @EricPyZhou @SbloodyS

**Comment by EricPyZhou** [comment]
> 

we still need it FOR NOW because there's still usages of `resourceMapper` in functions used in PyDolphinscheduler.

**Comment by EricPyZhou** [comment]
> Do we no longer need `t_ds_resources` when considering version compatibility? @EricPyZhou @SbloodyS

we still need it FOR NOW because there's still usages of resourceMapper in functions used in PyDolphinscheduler.

**Comment by huage1994** [comment]
Hi all,
I found Resource Center cannot work  when using  Alibaba Cloud OSS too. 
It seems that new interface methods are not implemented in `OssOperator.java`
![image](https://user-images.githubusercontent.com/8039295/205811518-e2824dfe-8000-4328-9ae4-e2286ff229de.png)

**Comment by huage1994** [comment]
I don't know if it's the same issue, if not, I can open another issue。
hi @zhangfane , do you use alibaba oss storage?

**Comment by zhangfane** [comment]
@huage1994 hdfs
