### ISSUE TITLE
[Bug] [UI] task's worker group display is wrong 

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#13038]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I've changed the task's worker group to not use 'default' , the database record is right but the ui always show 'default'

<img width="595" alt="image" src="https://user-images.githubusercontent.com/19989300/204449317-428f95e0-bc21-495a-8da0-f0630a178e15.png">

<img width="525" alt="企业微信截图_0b24c115-0f8b-43c5-9a25-b5124d2c9e19" src="https://user-images.githubusercontent.com/19989300/204449448-4f56b5f5-2347-45af-9dde-29aba7c85e67.png">

### What you expected to happen

UI should show the right worker group name

### How to reproduce

I'm using 3.0.3-SNAPSHOT , I think it'a bug

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hstdream** [comment]
Please provide the specific operation steps, thank you.
