### ISSUE TITLE
[Bug] [api-server] application.yaml about ldap is wrong

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#13040]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

https://github.com/apache/dolphinscheduler/blob/a28e206166a10010d36a5dc0d9e2fd54f799678b/dolphinscheduler-api/src/main/resources/application.yaml#L150

https://github.com/apache/dolphinscheduler/blob/a28e206166a10010d36a5dc0d9e2fd54f799678b/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/impl/ldap/LdapService.java#L53

**application.yaml is `base.dn` but in LdapService.java use `base-dn`**

### What you expected to happen

use same property.

### How to reproduce

3.0.x's bug

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tracehh** [comment]
` @Value("${security.authentication.ldap.base.dn:null}")
    private String ldapBaseDn;`
It had been resolved.
