### ISSUE TITLE
[Bug] [data-quality] data-quality document is wrong

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#13041]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/guide/data-quality.md

<img width="1052" alt="企业微信截图_cf41b4b4-e64e-4fad-86ba-9ba76990cca8" src="https://user-images.githubusercontent.com/19989300/204458147-d3eb1080-2612-4d4c-92c3-592e8f45f15d.png">

**_CheckFormula：Expected-Actual
result should be 9-10 < 0_**

### What you expected to happen

correct the document

### How to reproduce

doc is wrong

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
can you submit a PR  to solve this?
