### ISSUE TITLE
[Bug] zk3.4.6+dolphinscheduler3.1.1 deployment error

### ISSUE THREAD

**Issue by mccbing** [apache/dolphinscheduler#13054]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

官网文档说是zk3.4.6+即可 但是zk3.4.6+dolphinscheduler3.1.1部署报错

原因是dolphinscheduler 3.0.2 和 3.1.0 以上的zk 驱动都是 3.8.0 的，所有安装时候需要zk 新版本 才能解决此问题 

### What you expected to happen

![image](https://user-images.githubusercontent.com/59444438/204732487-2996153f-bfd2-4bc3-be43-46065dfdb840.png)

### How to reproduce

zk3.4.6+dolphinscheduler3.1.1部署 启动时会直接报错 

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hstdream** [comment]
Need to upgrade zk to 3.8.x.
