### ISSUE TITLE
[Bug] [dolphinscheduler-api] in the task definition list,  can't just modify upstream task list

### ISSUE THREAD

**Issue by jackfanwan** [apache/dolphinscheduler#13066]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 in the task definition list,  can't just modify upstream task list

### What you expected to happen

can modify

### How to reproduce

in the task definition list,  select edit, just modify upstream task list

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
It happens when modify upstream task list and task definition together, either. Maybe lack of logic to update task relations. You can check and fix it.

**Comment by jackfanwan** [comment]
> It happens when modify upstream task list and task definition together, either. Maybe lack of logic to update task relations. You can check and fix it.

yes, for when modify upstream task list and task definition together problem, you can see  https://github.com/apache/dolphinscheduler/pull/12722
