### ISSUE TITLE
调度flinksql 出现缺少jar包错误

### ISSUE THREAD

**Issue by JanuaryFM** [apache/dolphinscheduler#13068]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

利用dolphinscheduler调度flinksql，flink环境已经配置完全，运行查看报错The jar for the task is required.不去清楚少了什么jar包。
![image](https://user-images.githubusercontent.com/89951181/204980659-3336171b-ebc8-4a56-9e52-0439beb2ae38.png)
![image](https://user-images.githubusercontent.com/89951181/204980877-dd07a6b5-e3f3-429a-af7c-691ffcf3e0e8.png)

### What you expected to happen

任务执行报错缺少jar包，不清楚缺少什么jar包

### How to reproduce

无

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please describe in english.
