### ISSUE TITLE
[Improvement][Module Name] ldap more powerful support

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/dolphinscheduler#13062]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I can't do this configuration when I want to restrict the users to be synchronized (e.g., a specified group of related users, not individuals with access to my dolphinscheduler scheduling system).
![图片](https://user-images.githubusercontent.com/60029759/204945722-9b993b7f-9866-4165-8742-96594fdcf7d1.png)
You can refer to the above parameters to modify the logic accordingly

<img width="494" alt="图片" src="https://user-images.githubusercontent.com/60029759/204947114-5ae67a7e-b367-49c4-b494-f46d00e24ee7.png">
The front end change suggestion is to refer to the rancher design
I can have a switch through the front-end button 🔘 key, instead of going through the configuration to decide whether to go ldap or local user
This way the backend writes two interfaces directly and removes the historical pattern of dynamically loading implemented classes

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good suggestion, looking forward to your PR

**Comment by davidzollo** [comment]
any progress?
