### ISSUE TITLE
[Bug] [Server] Once click online schedule time, task will be automatically scheduled

### ISSUE THREAD

**Issue by simon824** [apache/dolphinscheduler#13089]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

v3.0.2
For a workflow with a schedule time, on the `Cron management` page, when we click offline and then click online, and the task will be automatically scheduled once.

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/18065113/205472202-3131a018-14bf-4016-8e55-bbae9be1ca8e.png">

### What you expected to happen

Expected  workflow won't be schedule when just  click online

### How to reproduce

we click offline and then click online on the `Cron management` page

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
@SbloodyS I'll fix it.

**Comment by Radeity** [comment]
Actually , pr https://github.com/apache/dolphinscheduler/pull/12233 changes mis-fire strategy to `withMisfireHandlingInstructionFireAndProceed`, if setting start date too early, `CronTrigger` will recognize that there's a mis-fire and proceed immediately, so i'll set start time no earlier than current time and this bug will be fixed.

**Comment by simon824** [comment]
> Actually , pr #12233 changes mis-fire strategy to `withMisfireHandlingInstructionFireAndProceed`, if setting start date too early, `CronTrigger` will recognize that there's a mis-fire and proceed immediately, so i'll set start time no earlier than current time and this bug will be fixed.

Nice catch!

**Comment by SbloodyS** [comment]
> @SbloodyS I'll fix it.

Sure. :)
