### ISSUE TITLE
Stack of tasks

### ISSUE THREAD

**Issue by 9527zk** [apache/dolphinscheduler#13095]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After half a month or so of normal operation, there is always a time when there is a backlog of tasks and all the tasks cannot run properly

### What you expected to happen

The task is running properly

### How to reproduce

The task is running properly

### Anything else
The task dependencies are consistently in a waiting state and will attempt many times, although no retry policy is configured

### Version

2.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Could you please provide more details? any log? any metrics of memory? can the system recovery?

**Comment by 9527zk** [comment]
If tasks are not executed, the cpu usage of mysql is quite high, which is always stable at 800%. Then the backlog of task instances is stopped, mysql is restored, and the task scheduling is restored




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月5日(星期一) 下午4:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] Stack of tasks (Issue #13095)





 
Could you please provide more details? can the system recovery?

**Comment by davidzollo** [comment]
How to reproduce the problem? there aren't have enough message to solve this issue
