### ISSUE TITLE
[bug] [task-chunjun] can not submit successfully cause check err

### ISSUE THREAD

**Issue by conghe2402** [apache/dolphinscheduler#13108]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In version 3.1.1 branch, When I save a chunjun task , the api-server checks the parameters invalid because  customConfig is 0 

### What you expected to happen

can save and submit chunjun task successfully

### How to reproduce

create a  chunjun task and save , using branch release-3.1.1 code.

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tracehh** [comment]
The front param should update. @jkhhuse

**Comment by Yinyuhang123** [comment]
I also want to ask the same question

**Comment by VII-S** [comment]
我也想问同样的问题

**Comment by goomhow** [comment]
我也碰到了这个问题，用sh任务在代替，但这样也不是长久之计
