### ISSUE TITLE
[Bug] [UI] The Gantt chart for the workflow instance is not available  

### ISSUE THREAD

**Issue by Sky-Gu** [apache/dolphinscheduler#13109]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

As the title

![image](https://user-images.githubusercontent.com/5527811/205788128-36fd96bf-099e-48a1-8ef3-496c7deba9e9.png)

### What you expected to happen

Restore Function
 

### How to reproduce

Version 3.1.1, view the Gantt chart of the workflow instance
 

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
Sorry to say that I couldn't reproduce the issue. Could you give me more details about the issue?

**Comment by Sky-Gu** [comment]
chrome version 108.0.5359.124 shows an error in the console.

I also tried using firefox and safari,and the problem was the same.
 
![WX20221226-103839](https://user-images.githubusercontent.com/5527811/209492615-9e1c0a17-23e7-49a7-a66a-df5b3c7fd415.png)

**Comment by woxiangwoshi123** [comment]
> Sorry to say that I couldn't reproduce the issue. Could you give me more details about the issue?

I also have the same problem, the Gantt chart shows a blank page, and opening F12 shows the same error. My version is 3.1.2.Hope you can fix it soon, thanks.
<img width="1678" alt="Snipaste_2022-12-28_15-38-50" src="https://user-images.githubusercontent.com/32809232/209776359-d719a4ad-8fea-4dcc-bd85-0697c68e70ba.png">

**Comment by mer2** [comment]
> I also have the same problem, the Gantt chart shows a blank page, and opening F12 shows the same error. My version is 3.1.2.Hope you can fix it soon, thanks.

+1, version=3.1.2
upgrade from 3.0.0

**Comment by klboke** [comment]
> Sorry to say that I couldn't reproduce the issue. Could you give me more details about the issue?

@calvinjiang  I also had a problem with Gantt not displaying, the version is v3.1.2 , The key code is as follows：
```ts
    props.seriesData.forEach(function (task, index) {
      const start = Math.floor(task.startDate[0] / 1000) * 1000
      const end = Math.floor(task.endDate[0] / 1000) * 1000
      minTime = minTime < start ? minTime : start
      maxTime = maxTime > end ? maxTime : end
      // debug print
      console.log(data)
      console.log(task)
      data[task.status].push({
        name: task.name,
        value: [index, start, end, end - start],
        itemStyle: {
          color: state[task.status as ITaskState].color
        }
      })
    })

```
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/18591662/210762260-cc44f417-c76b-4348-bc58-39a883bcff59.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/18591662/210762435-ab7b2e43-b938-49b1-a12b-674fd1339760.png">

**Comment by ChPi** [comment]
duplicate of #11583 ?

**Comment by fw19940314** [comment]
v3.1.3-release  issue still exists.

**Comment by GHxiaotan** [comment]
v3.1.4-release issue still exists.

**Comment by woxiangwoshi123** [comment]
> v3.1.4-release issue still exists.
yes
