### ISSUE TITLE
[Improvement][dolphinscheduler-api] optimization task definition & fix in the task definition list, if one task have more pre task, the task list can't show all task

### ISSUE THREAD

**Issue by jackfanwan** [apache/dolphinscheduler#13105]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

in the task definition, delete search workflow name filter, and  fix in the task definition list, if one task have more pre task, the task list can't show all task

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
relative issue: 
- #13087
