### ISSUE TITLE
[Bug] worker-server/conf/olphinscheduler_env.sh read permission problem

### ISSUE THREAD

**Issue by cleverpig** [apache/dolphinscheduler#13116]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

dolphinscheduler在每次重启后都会做一些属性重置：
1、worker-server/conf目录属性为drwx------.
2、worker-server/conf/dolphinscheduler_env.sh属性为rwx------.
这样当使用hadoop或其他用户运行flinksql-shell脚本时，海豚会先执行worker-server/conf/dolphinscheduler_env.sh，此时发生权限拒绝的错误。
临时解决方法：将flink目录的权限设置为dolphinscheduler:root，然后使用dolphinscheduler用户来执行flinksql-shell脚本任务，避免执行dolphinscheduler_env.sh时出错。

### What you expected to happen

在每次重启后dolphinscheduler保持现有worker-server的conf目录和dolphinscheduler_env.sh的读取属性。.

### How to reproduce

使用其他非root系统用户执行一个flinksql脚本即可。
例如：sql-client.sh -f /app/software/flink-1.16.0/test-all.sql

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
as i know, DS has remove the `chmod -R 700`

**Comment by cleverpig** [comment]
> as i know, DS has remove the `chmod -R 700`

what's i did is changing the top level env.sh

**Comment by FinallyFinancialFreedom** [comment]
> as i know, DS has remove the `chmod -R 700`

on which version ? i use 3.0.2 and the problem is not fixed

**Comment by finviman** [comment]
as i know , `chmod -R 700 ` is removed in 3.1.4, I don't know why there is such a odd command.
