### ISSUE TITLE
[Feature][Metrics] task fail metrics

### ISSUE THREAD

**Issue by a327919006** [apache/dolphinscheduler#13111]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I want to know which task failed by metrics。
At present, I collect metrics through prometheus and 'ds_task_failure_count_total' knows that a task has failed, but I don't know which task has failed.  I hope that specific task information can be added to the metrics label.Or add other metrics to obtain task failure information.

我想通过指标知道具体哪个任务失败。
目前我通过prometheus采集metrics，通过ds_task_failure_count_total知道有任务失败，但是我不知道具体哪个任务失败，希望ds_task_failure_count_total的标签中可以增加具体task信息。或者新增其他指标来获取任务失败信息。

### Use case

metrics of which task failed
可以知道具体哪个任务失败的指标

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
Can you implement it? it's not difficult

**Comment by ixiaoyi93** [comment]
这个需求不是挺好的呀，为啥没做呢。自带的告警，不是很好呀。
