### ISSUE TITLE
[Bug] [Resource Center] Use resource ERROR

### ISSUE THREAD

**Issue by xumingJustDoIt** [apache/dolphinscheduler#13132]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/63526456/206375550-4c220915-8f89-4033-b712-971d3ad929c4.png)
if I use the resource,then run error
![image](https://user-images.githubusercontent.com/63526456/206375748-9af5615c-9a40-48c3-8789-b03ce093e67b.png)
do not use the resource,then run normal
![image](https://user-images.githubusercontent.com/63526456/206375967-d999cd8a-1aa4-4c49-b337-546e3ebd537b.png)

### What you expected to happen

I can use the resources normally

### How to reproduce

use apache-dolphinscheduler-3.0.2-bin 

### Version

3.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
it's not a bug, you can refer to the doc, https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/resource/file-manage.html
![image](https://user-images.githubusercontent.com/15833811/206485597-c2dc9801-9a00-440e-912b-c1d68c23b496.png)
