### ISSUE TITLE
[Bug] [Master] Pause and stop processInstance failed after restarting DS

### ISSUE THREAD

**Issue by Radeity** [apache/dolphinscheduler#13149]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

If there are running processes before restarting, pause and stop process instance will fail because when restarting DS, `processInstanceExecCache` will lost. Status of process instance can be updated only if it's `WorkflowExecuteRunnable` remains in cache. The logic can be seen in `StateEventResponseService`. 

### What you expected to happen

Status update can be successful.

### How to reproduce

You can simply debug DS in standalone mode, run a workflow and exit debugging before running complete. Restart it and you can find that the status of the workflow is running and you can't pause or stop it successfully. Status will keep in `ready stop` or `ready pause`, you can do nothing to change it.

<img width="1581" alt="image" src="https://user-images.githubusercontent.com/45198818/206863144-2f7d7c7d-6b38-4eaf-8b96-201c8d312ebe.png">

### Anything else

It's possible that the same problem exists when using waiting disconnect strategy which will clear the cache when master disconnect. I don't test it, just a speculation.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi @ruanwenjun, i find that you were in charge of this part of code, do you think it's a bug and have to be fixed?

**Comment by ruanwenjun** [comment]
@Radeity When the master restart the `processInstanceExecCache` will be fit again, after failover.

**Comment by Radeity** [comment]
> You can simply debug DS in standalone mode, run a workflow and exit debugging before running complete. Restart it and you can find that the status of the workflow is running and you can't pause or stop it successfully. Status will keep in ready stop or ready pause, you can do nothing to change it.

Can you find out why it behaves like this?

**Comment by Radeity** [comment]
> @Radeity When the master restart the `processInstanceExecCache` will be fit again, after failover.

Ohh, the described scenario happens because there's no failover strategy in standalone mode. Thanks, @ruanwenjun!
