### ISSUE TITLE
[Bug] [Master node] org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer: [146] - dispatch error:java.lang.NullPointerException will appear when using http scheduling

### ISSUE THREAD

**Issue by 997759790** [apache/dolphinscheduler#13147]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

当我们http请求超时或者响应码不为200时，会出现上述错误，并在一段时间后，整个master节点日志只会打印该错误，不做任务调度。然后将磁盘空间打满，直到触发容灾

### What you expected to happen

希望可以修复

### How to reproduce

当我们http请求超时或者响应码不为200时，会出现上述错误，并在一段时间后，整个master节点日志只会打印该错误，不做任务调度。然后将磁盘空间打满，直到触发容灾

### Anything else

无

### Version

2.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good job, but English is needed

**Comment by 997759790** [comment]
> good job, but English is needed

ok，When the response code of the http request is not 200, there will be an error, and the above errors will appear one after another, and the whole period will be one by one. time one one one one one one one

**Comment by 997759790** [comment]
ok，When our http request times out or the response code is not 200, the above error will appear, and after a period of time, the entire master node log will only print the error, and no task scheduling will be performed. Then fill up the disk space until disaster recovery is triggered

**Comment by brave-lee** [comment]
Which version ?

**Comment by 997759790** [comment]
2.0.5，
We now find that it is set
The default tenant-oriented

**Comment by brave-lee** [comment]
> 2.0.5， We now find that it is set The default tenant-oriented

What does it mean?

**Comment by 997759790** [comment]
sorry，We find that it is set
tenant is  default

**Comment by brave-lee** [comment]
So, this is not a bug. Can this issue be closed ?

**Comment by 997759790** [comment]
It is a bug, because only one task that sets the tenant as the default, and eventually it will continue to accumulate, and eventually no task scheduling will be performed, and error messages will continue to be printed, occupying the disk

**Comment by brave-lee** [comment]
Are you sure it is the tenant of the workflow or the task worker group ?

**Comment by 997759790** [comment]
yes, is the tenant selected when executing the task

**Comment by brave-lee** [comment]
Can you upload some pictures and describe the reproduction process ?

**Comment by sc769** [comment]
I have also encountered the same problem, but I cannot find out what is causing it. Unable to execute any tasks and constantly writing this type of log.

The following is the log:
org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer:[146] - dispatch error:  ava.lang.NullPointerException java.lang.NullPointerException: null

**Comment by 997759790** [comment]
只能做规避，调整租户即可。观察日志的是提示租户找不到，紧接着就开始一直打印dispatch error: ava.lang.NullPointerException java.lang.NullPointerException: null日志。
