### ISSUE TITLE
[Bug] [API] Failed when querying based on workflow status

### ISSUE THREAD

**Issue by woxiangwoshi123** [apache/dolphinscheduler#13144]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I query a workflow based on its state the query fails, I figure out it's a missing enum value in the code.
<img width="1652" alt="企业微信截图_33ed92af-871c-4892-9a87-f49fe9cca9d6" src="https://user-images.githubusercontent.com/32809232/206623657-50a08206-6dca-455f-9460-b96204083277.png">
<img width="1680" alt="企业微信截图_aabe923b-1004-4093-94fd-5dbdb28df08b" src="https://user-images.githubusercontent.com/32809232/206623753-e06e70c2-87fc-4bb4-8725-cabfbd7bf63c.png">

### What you expected to happen

xx

### How to reproduce

When the workflow filter type is kill, waiting for thread, waiting for dependency, delay execution, etc., the query will fail

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jieguangzhou** [comment]
I see you are willing to submit a PR, so I assign you. Thanks for fixing the bug. Look forward to your code

**Comment by woxiangwoshi123** [comment]
Thank you for assigning this problem to others, my ability is limited.

**Comment by woxiangwoshi123** [comment]
> [街广州](https://github.com/jieguangzhou) 评论了 [last week](https://github.com/apache/dolphinscheduler/issues/13144#issuecomment-1345554116)
我看你愿意提交 PR，所以我分配给你。感谢您修复错误。期待你的代码

> Thank you for your feedback, we have received your issue, Please wait patiently for a reply.
> 
> * In order for us to understand your request as soon as possible, please provide detailed information、version or pictures.
> * If you haven't received a reply for a long time, you can [join our slack](https://s.apache.org/dolphinscheduler-slack) and send your question to channel `#troubleshooting`

Please assign this problem to others, as my ability is limited and I cannot solve it.

**Comment by calvinjiang** [comment]
> > [街广州](https://github.com/jieguangzhou) 评论了 [last week](https://github.com/apache/dolphinscheduler/issues/13144#issuecomment-1345554116)
> > 我看你愿意提交 PR，所以我分配给你。感谢您修复错误。期待你的代码
> 
> > Thank you for your feedback, we have received your issue, Please wait patiently for a reply.
> > 
> > * In order for us to understand your request as soon as possible, please provide detailed information、version or pictures.
> > * If you haven't received a reply for a long time, you can [join our slack](https://s.apache.org/dolphinscheduler-slack) and send your question to channel `#troubleshooting`
> 
> Please assign this problem to others, as my ability is limited and I cannot solve it.

All right. I'll fix this issue.
