### ISSUE TITLE
[Feature][API] How to make the interface wait for the end of the process instance to return information after the third-party system calls the API to start the process instance, instead of directly returning information after the successful call?

### ISSUE THREAD

**Issue by JoshuaZhuCN** [apache/dolphinscheduler#13153]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

How to make the interface wait for the end of the process instance to return information after the third-party system calls the API to start the process instance, instead of directly returning information after the successful call?

### Related issues

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Duplicated with #9505.
