### ISSUE TITLE
[Doc][Installation Docs] Documentation could not be reached

### ISSUE THREAD

**Issue by Comie** [apache/dolphinscheduler#13166]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

All docs could not be reached and returned 404.

### Documentation Links

https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/start/docker.html

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
pls try https://dolphinscheduler.apache.org/#/en-us/docs/3.1.2/guide/start/docker

**Comment by Comie** [comment]
thanks, got it

**Comment by zhongjiajie** [comment]
I would like to close this issue because already fix, you can still replied if you still with other issue
