### ISSUE TITLE
[Bug] [UI] After modifying a few of fields on a dependent task form and canceling the task modal, these values of fields wouldn't be reset.

### ISSUE THREAD

**Issue by calvinjiang** [apache/dolphinscheduler#13160]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After modifying a few of fields on a dependent task form and canceling the task modal, these values of fields wouldn't be reset. When opening this modal one more time, you can also see those modified values.

Open a dependent task modal and choose a new project name for the dependent task:
![image](https://user-images.githubusercontent.com/4928204/207027377-fb5527ee-d2ac-426a-bb1d-f5a8a55ccea4.png)

![image](https://user-images.githubusercontent.com/4928204/207027395-4f06e324-290d-4484-8d26-32ef581303a7.png)

Then cancel the modal and open the task again:
![image](https://user-images.githubusercontent.com/4928204/207027407-e056f2d0-fb87-477e-b072-30b329f8ea37.png)

### What you expected to happen

When canceling the task modal all modified values should be restored.

### How to reproduce

Open a dependent task modal and choose a new project name for the dependent task. And then cancel the modal and open the task again. You'll see this issue.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good job @calvinjiang , please add a title for this issue, thx
