### ISSUE TITLE
[Improvement][dolphinschedule-api]  fine-grained authority management

### ISSUE THREAD

**Issue by mxq-151** [apache/dolphinscheduler#13165]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

now in ds,the granularity of rights management is too coarse,it is difficult to meet real needs.it is nice to have feature below
1. tenent belong to project,
2. tenant has project admin(one:many)
3. warning group belong to tenant(many:one)
4. worker group belong to tenant(many:one)
5. only admin user and the project admin can edit the resource that belong to project 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
That's great! Looking forward to your contribution. @mxq-151

**Comment by mxq-151** [comment]
will you guys accept this  pull request?

**Comment by SbloodyS** [comment]
> will you guys accept this pull request?

I did not see your PR. Would you please link the PR to this issue?

**Comment by zhongjiajie** [comment]
Hi @mxq-151 according to your description, I find there are many new feature like `project has a admin role(one:many)`

and some incompatibe change for current including `warning group belong to project(many:one)` and `worker group belong to project(many:one)` when I assign a warning group to project, can I use them to other project?

**Comment by mxq-151** [comment]
> Hi @mxq-151 according to your description, I find there are many new feature like `project has a admin role(one:many)`
> 
> and some incompatibe change for current including `warning group belong to project(many:one)` and `worker group belong to project(many:one)` when I assign a warning group to project, can I use them to other project?

your description need to change:when I assign a warning group to tenant(not the project), can I use them to other project?

the pre-view in the pr(https://github.com/apache/dolphinscheduler/pull/13327),you can take a look if it can meet your demand

no,warning group only can use in project that both belong to the same tenant
