### ISSUE TITLE
[Bug] [Task group]  Task group resources are not released when task fails

### ISSUE THREAD

**Issue by chao5go** [apache/dolphinscheduler#13178]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Task group resources are not released when task fails
<img width="946" alt="image" src="https://user-images.githubusercontent.com/49749946/207242905-af7343a0-779e-4767-a666-b4fdd9dba5d5.png">

### What you expected to happen

Task group resources can be released when task fails.

### How to reproduce

<img width="532" alt="image" src="https://user-images.githubusercontent.com/49749946/207243161-2bb281ea-f4d1-4b22-99e3-63b71467d000.png">

then 

<img width="588" alt="image" src="https://user-images.githubusercontent.com/49749946/207243290-cd079789-4be5-4cdb-affa-932874d70b4c.png">

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Duplicated with #13107
