### ISSUE TITLE
[Improvement][Master] Optimize master failover logic 

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#13185]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently we have two parts to deal with master failover: 

1. FailoverExecuteThread - loops through process instances and find those need to be failed over. 
2. MasterRegistryDataListener - receives events from ZK and trigger masters to do failover.

Actually we could do some optimization so that we no more need FailoverExecuteThread to keep looping.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
@EricGao888 Could you show your optimization idea?
