### ISSUE TITLE
[Bug] [Website] An error occurred at the site link hop

### ISSUE THREAD

**Issue by jieguangzhou** [apache/dolphinscheduler#13189]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

https://dolphinscheduler.apache.org/#/en-us/docs/3.1.2/guide/installation/standalone
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/31528124/207529856-89fc2c96-5b43-454a-b842-18e02e0d7bd0.png">

### What you expected to happen

empty

### How to reproduce

empty

### Anything else

empty

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
solved by this [#858](https://github.com/apache/dolphinscheduler-website/pull/858)
