### ISSUE TITLE
[Workflow][Dag] Can dolphinscheduler support spark dag immediately?

### ISSUE THREAD

**Issue by xiaoshengaimm** [apache/dolphinscheduler#13199]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Dolphinscheduler can support spark dag on workflow console and generate python script to spark cluster.

Now if we want to create spark complicated DAG we only can write python script and submit to dolphinscheduler one dag node. It's hard to spark newer.

As I know AWS Glue can do it. Can Dolphinscheduler support it?
![image](https://user-images.githubusercontent.com/1866149/207811229-49e6f2b1-2667-443b-a582-617fff4456ee.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi, @xiaoshengaimm, thanks for your suggestion! Some personal view, DS should focus on **scheduling** different types of tasks. Rather, AWS Glue provides a data integration service, one ETL job can be seen as a specific task in DS. Maybe Seatunnel can integrate this feature in the future. WDYT?

Welcome to discuss about it ~~
