### ISSUE TITLE
[Improvement][worker] task instance's pid need to be insert to DB during running

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#13201]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
Could u plz give any explanation on why `task instance's pid need to be insert to DB during running` ? Thanks : )

**Comment by fuchanghai** [comment]
now pid will be inserted after end of run。which was no meaning&nbsp;



---Original---
From: "Eric ***@***.***&gt;
Date: Sat, Dec 17, 2022 23:20 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/dolphinscheduler] [Improvement][worker] task instance'spid need to be insert to DB during running (Issue #13201)




 
Could u plz give any explanation on why task instance's pid need to be insert to DB during running ? Thanks : )
