### ISSUE TITLE
[Bug] [dolphinschedule-api] start-process-instance not work properly

### ISSUE THREAD

**Issue by Chris-playground** [apache/dolphinscheduler#13205]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I use the this api `/dolphinscheduler/projects/{projectCode}/executors/start-process-instance` to run process in my own client, and i want it to run from the failed task, so i set `execType=START_FAILURE_TASK_PROCESS`, but it will always run from the first task.
I tried all the enums in `CommandType` and it had no different, it seems this param have no effect?

### What you expected to happen

the process start from the failed task

### How to reproduce

follow my description

### Anything else

I think it would be better to return a `processInstanceId `after process successfully started, so that we have no need to check the list by processDefinitonCode and get the latest one.

### Version

3.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jieguangzhou** [comment]
You can use this interface to rerun the failed task.
<img width="606" alt="image" src="https://user-images.githubusercontent.com/31528124/209496776-f0ebfac4-29e3-4677-9456-db925f623522.png">

and set the executeType=START_FAILURE_TASK_PROCESS

**Comment by Chris-playground** [comment]
> You can use this interface to rerun the failed task. <img alt="image" width="606" src="https://user-images.githubusercontent.com/31528124/209496776-f0ebfac4-29e3-4677-9456-db925f623522.png">
> 
> and set the executeType=START_FAILURE_TASK_PROCESS

this api works, but you have to get the correct  `processInstanceId` first, it is not as convenient as the `/start-process-instance` api.
So, the `execType=START_FAILURE_TASK_PROCESS` param doesn't work, right?
