### ISSUE TITLE
[BUG] Serial complement data generate only one process instance

### ISSUE THREAD

**Issue by KEN-LJQ** [apache/dolphinscheduler#1320]
**Describe the bug**
When the process need complement data with n days, complete in parallel execution mode will generate n process instance, but complete in serial execution generate only one process instance.
Which may cause some problem with dependence check, because it have only one process instance, but other process depend m days of this process, and it can't not be satisfy.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Create process A
2. Create process B, and depend last week of process A
3. Process A do data complement in serial mode for last week
4. Process B do data complement of today
5. Process B failed with dependence not satisfy

**Expected behavior**
When complement data in serial mode with n days, it should generate all process instance.

**Which version of Dolphin Scheduler:**
 - [1.1.0]

**Additional context**
The problem is relate to the dependence check implement, dependence check is base on the scheduler_time field of process instance, when complement data in serial mode, there's only one record of process instance in database, and scheduler_time is the last day of complement date range, so that is failed

**Comment by lenboo** [comment]
yes, you got it!
the dependent result for dependence node would be error in serial complement mode, we would fix it in the next version.

**Comment by zhongjiajie** [comment]
According to @lenboo said, it is fix for current version, I would like to close this issue, you could reopen it if you have further question
