### ISSUE TITLE
[Improvement][all] Field injection is not recommended Inspection info: Spring Team recommends: "Always use constructor based dependency injection in your beans. Always use assertions for mandatory dependencies".

### ISSUE THREAD

**Issue by liugddx** [apache/dolphinscheduler#13210]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I found out that our project uses @Autowired, spring Team recommends: "Always use constructor based dependency injection in your beans. Always use assertions for mandatory dependencies".
https://blog.marcnuri.com/field-injection-is-not-recommended.
So I think this is a needed optimization point.

- [ ]  dolphinscheduler-api https://github.com/apache/dolphinscheduler/pull/13214
- [ ]  dolphinscheduler-dao https://github.com/apache/dolphinscheduler/pull/13215
- [ ]  dolphinscheduler-master https://github.com/apache/dolphinscheduler/pull/13216
- [ ] dolphinscheduler-scheduler-plugin https://github.com/apache/dolphinscheduler/pull/13217
- [ ] dolphinscheduler-service https://github.com/apache/dolphinscheduler/pull/13218
- [ ] dolphinscheduler-tools https://github.com/apache/dolphinscheduler/pull/13219
- [ ] dolphinscheduler-woker https://github.com/apache/dolphinscheduler/pull/13220

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
This pr has changed a lot, so I split the task, and friends who need to participate can also claim it.

**Comment by liugddx** [comment]
> This pr has changed a lot, so I split the task, and friends who need to participate can also claim it.

@EricGao888 @SbloodyS do you have any suggestions?

**Comment by EricGao888** [comment]
Hi @liugddx , may I ask whether you plan to wipe out all the `@Automwired` annotations in this project, or just part of them?

**Comment by liugddx** [comment]
> Hi @liugddx , may I ask whether you plan to wipe out all the `@Automwired` annotations in this project, or just part of them?

I am going to replace all `@Automwired` annotations in this project.

**Comment by liugddx** [comment]
Another good `good first issue` that I think I can contribute to is to replace logging with @Slf4j.You can contribute and don't need to be very familiar with the system. I think this is very friendly.I would also like to contribute in this way.

**Comment by DarkAssassinator** [comment]
this is just a IDEA warnning, but i do think that construct will better than`@Autowired`, In terms of readability, `@Autowired` is better, and if we will inject many beans, o huge constuct may not be a good idea. WDYT

**Comment by liugddx** [comment]
> this is just a IDEA warnning, but i do think that construct will better than`@Autowired`, In terms of readability, `@Autowired` is better, and if we will inject many beans, o huge constuct may not be a good idea. WDYT

Thanks for the reply, if you write the constructor directly, it will make the code poorly readable, but we use lombok to solve this problem. In addition, this is not just a warning from IDEA, you can see https://blog.marcnuri.com/field-injection-is-not-recommended for details. Of course, the purpose of my mentioning this PR is to lower my contribution threshold, and I am happy to contribute my strength to dolphinscheduler.

**Comment by liugddx** [comment]
> Hi @liugddx , may I ask whether you plan to wipe out all the `@Automwired` annotations in this project, or just part of them?

Please tell me if this is a meaningful issue? If not, I will close the issue and related pr, thanks.

**Comment by EricGao888** [comment]
> > Hi @liugddx , may I ask whether you plan to wipe out all the `@Automwired` annotations in this project, or just part of them?
> 
> Please tell me if this is a meaningful issue? If not, I will close the issue and related pr, thanks.

I'm +1 to this.

**Comment by zhongjiajie** [comment]
not stale
