### ISSUE TITLE
[Feature][Module Name] workflow instance

### ISSUE THREAD

**Issue by hwfbest** [apache/dolphinscheduler#13225]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Workflow instances add layers

### Use case

The name of the workflow and the tasks that run at different times are divided into two layers, so that it is easy to browse and find logs. The following is a comparison of the differences between the two graphs:
![image](https://user-images.githubusercontent.com/16427578/208426039-c273ba54-80f8-4cd2-be8e-baace9de024e.png)

![image](https://user-images.githubusercontent.com/16427578/208427719-ef31583e-c747-4002-bb9a-23b008cc3a2d.png)

The latter refers to the design of other systems. This design is more hierarchical and easier to find logs. I hope the community will adopt it.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
hi, I still can't get the point.

for China users, I think you can join the local weekly meeting through https://docs.qq.com/doc/DQ3BGVHZ1bXp5R2FZ , please register your topic first in the notes, then we can discuss it in the meeting, thx

**Comment by hwfbest** [comment]
任务工作实例分两层查看：
1、第一层显示每个任务的最新一次执行实例情况
2、点击第一层对应任务，进去显示该任务的历史执行实例情况。

好处：可以对执行的多个任务多个实例分类更清楚，更容易查阅，比输入关键字搜索更便捷
望采纳
