### ISSUE TITLE
[Improvement][Master] Validate same content of input file when using task cache

### ISSUE THREAD

**Issue by Radeity** [apache/dolphinscheduler#13223]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Task cache mechanism is introduced in https://github.com/apache/dolphinscheduler/pull/13194. Cache key can make sure tasks have the same value of property (store resource path in file paramter), but the same resource path doesn't mean the same file contents. Also, the different resource path may have same content. 

For other types of parameter, the same value of property means the same input, keep logic consistency for file parameter, we should check the same content in resourcePath.

Maybe we can add checksum of input file when generating cache key. In addition, i think it's improper to download the whole file in master, we can save checksum in another file when uploading output file, download checksum file when generating cache key.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
@jieguangzhou PTAL.

**Comment by jieguangzhou** [comment]
> @jieguangzhou PTAL.

The file output using `file parameter` will not change if the user does not manually modify the resource center. 

Users should not modify the task output files in the file parameter feature, It's the mechanism inside ds.

But if we use the files parameters from SCP or s3 (If we support them in the future), I think testing is better
