### ISSUE TITLE
[Bug] [UI] Failed to enable DEPENDENT node timeout alarm

### ISSUE THREAD

**Issue by woxiangwoshi123** [apache/dolphinscheduler#13226]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Create a dependent node, turn on the timeout alarm and click OK, reopen the node and find that the timeout alarm has not been turned on。
<img width="659" alt="Snipaste_2022-12-20_10-13-27" src="https://user-images.githubusercontent.com/32809232/208564986-7934f30f-eb62-4d7b-a049-605503d34acd.png">
<img width="667" alt="Snipaste_2022-12-20_10-14-05" src="https://user-images.githubusercontent.com/32809232/208565024-11188b7c-2f46-45f4-85a1-ef701e5c0cbf.png">

### What you expected to happen

I hope the timeout alarm can be fixed

### How to reproduce

Create a dependent node, and then turn on the timeout alarm。

### Anything else

no

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I'd like to fix this issue.

**Comment by woxiangwoshi123** [comment]
Thank you for fixing this, but I just tried your code and the problem persists.

**Comment by woxiangwoshi123** [comment]
> Thank you for fixing this, but I just tried your code and the problem persists.


Thank you for fixing this, but I just tried your code and the problem persists.

**Comment by woxiangwoshi123** [comment]
> I'd like to fix this issue.
Thank you for fixing this, but I just tried your code and the problem persists.

**Comment by woxiangwoshi123** [comment]
> I'd like to fix this issue.


Thank you for fixing this, but I just tried your code and the problem persists.
