### ISSUE TITLE
[Improvement][pre-commit] Add `codespell` for spell checking

### ISSUE THREAD

**Issue by jbampton** [apache/dolphinscheduler#13238]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Spell check the code with `codespell` and run with `pre-commit`.

So this will include creating a custom dictionary and maybe some file/folder ignores.

https://github.com/codespell-project/codespell

refs #13237

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jbampton** [comment]
Ping @EricGao888

**Comment by EricGao888** [comment]
@jbampton Cool. cc @zhongjiajie

**Comment by zhongjiajie** [comment]
Hi @jbampton  looking cool, we try to find some tool the previous time, but also busy for some thing else, you can search in https://github.com/apache/dolphinscheduler/issues/6535, keyword `spelling` and we have other idea about our CI too
