### ISSUE TITLE
[Doc][Module Name] I can't find the developer's guide in the new documentation

### ISSUE THREAD

**Issue by mengyu822** [apache/dolphinscheduler#13236]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I can't find the developer's guide in the new documentation.
[https://files.slack.com/files-pri/T01L3LB96V7-F04GNMCV8D6/image.png](url)

我在新的官方页面中无法找到开发者指南相关内容，这个在之前的页面中是有的

### Documentation Links

[dolphinscheduler.apache.org/en-us/development/development-environment-setup.html](http://dolphinscheduler.apache.org/en-us/development/development-environment-setup.html)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
cc @Amy0104

**Comment by caishunfeng** [comment]
Hi @mengyu822 you can find it in https://dolphinscheduler.apache.org/#/en-us/community

**Comment by EricGao888** [comment]
@caishunfeng @SbloodyS I couldn't find this link https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/development-environment-setup.md on the new website. Do u know where it is? Thx

**Comment by SbloodyS** [comment]
> @caishunfeng @SbloodyS I couldn't find this link https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/development-environment-setup.md on the new website. Do u know where it is? Thx

I'm not sure...
