### ISSUE TITLE
[Feature][task-plugin] Can zeppelin tasks be more flexible with dynamic parameter passing?

### ISSUE THREAD

**Issue by LucasClt** [apache/dolphinscheduler#13230]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Define Parameters in [Zeppelin Parameters] of zeppelin task, can only write fixed parameter values, cannot set $[yyyy-MM-dd] to generate dynamic date, or is it possible to reference parameters defined in [Custom Parameters] in [Zeppelin Parameters]? 

### Use case

Define Parameters in [Zeppelin Parameters] of zeppelin task, can only write fixed parameter values, cannot set $[yyyy-MM-dd] to generate dynamic date, or is it possible to reference parameters defined in [Custom Parameters] in [Zeppelin Parameters]? 
![image](https://user-images.githubusercontent.com/120378101/208624794-9df9166b-a39c-46bd-b9d6-68439d7207cc.png)
![image](https://user-images.githubusercontent.com/120378101/208625295-06695b2f-32ee-4a58-a295-d6dbdb680ba7.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wjn0918** [comment]
you can see this
[https://github.com/apache/dolphinscheduler/pull/16427](url)
