### ISSUE TITLE
[Bug] Always report null pointer when using hive udf

### ISSUE THREAD

**Issue by xumingJustDoIt** [apache/dolphinscheduler#13249]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when i use hive udf(hive_length is my hive udf,i had test it),then run error:
![image](https://user-images.githubusercontent.com/63526456/209042348-55564234-6b1f-4257-b71b-25854a314e3c.png)

### What you expected to happen

use hive udf ok

### How to reproduce

use hive udf

### Version

3.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
@xumingJustDoIt but it seems that you do not add your udf resource in your sql task, do you add the udf during the hive server startup? BTW, do you willing to create a PR to fix it?

**Comment by Aidon-lyd** [comment]
i meet the same problem，cloud you share the solution?   thanks ！！！

**Comment by zhongjiajie** [comment]
> i meet the same problem，cloud you share the solution? thanks ！！！

do you add your udf to your sql task?

**Comment by zhongjiajie** [comment]
It is seem because our datasource connection pool, am I right @ruanwenjun ?
