### ISSUE TITLE
[Feature][security]Users can choose Dolphinscheduler 's encryption algorithm

### ISSUE THREAD

**Issue by hdygxsj** [apache/dolphinscheduler#13245]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Because each company may have its own encryption standards, for example, some companies may use rsa or aes, Chinese banks or state-owned enterprises may require the use of sm4, otherwise they will be audited, and some companies may have their own encryption algorithms, so I suggest that Dolphin Dispatch can support users to choose the encryption standard they need, or put their own encryption plug-in when deploying.
The encryption algorithm will be used in the following scenarios:
1.  Encrypt spring configuration
2.  Encrypt the password stored in the database
3.  Encrypt the configuration information in the task
4.  Encrypt passwords when transmitting them to the front and back ends

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
can you show more detail about how in config the security method, especially custom plugin from user define

**Comment by hdygxsj** [comment]
> can you show more detail about how in config the security method, especially custom plugin from user define

I have time to do this now, can we use spi and define some interfaces and provide default implementations. As for how to allow users to customize, my idea is to add a plugin directory and let Dolphin Scheduler go to the plugin directory to load the jar in the plugin directory at startup.
