### ISSUE TITLE
[Improvement] [API] The downstream workflow is started, although it is not online

### ISSUE THREAD

**Issue by xuchunlai** [apache/dolphinscheduler#13253]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When performed complement operation, the downstream workflow is started, although it is not online.

### What you expected to happen

Start the downstream workflow  when it is online

### How to reproduce

Performs the complement operation when set complementDependentMode=ALL_DEPENDENT,downstream workflow is offline.

### Version

3.1.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @xuchunlai Is this issue also exist in 3.0.x or 3.1.x? Can you take a check?

**Comment by xuchunlai** [comment]
> Hi @xuchunlai Is this issue also exist in 3.0.x or 3.1.x? Can you take a check?

version is 3.1.2
