### ISSUE TITLE
[Bug] [UI] The version 3.1.1 Canvas connection confusion！！！

### ISSUE THREAD

**Issue by Sdreamery** [apache/dolphinscheduler#13277]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The version 3.1.1 Canvas connection confusion，but 3.1.0 is natural. 
[https://asf-dolphinscheduler.slack.com/archives/C03U7SR73TN/p1672021319522189](url)

**Comment by Sdreamery** [comment]
![image (1)](https://user-images.githubusercontent.com/38490969/209507751-6492deff-2cae-47e6-b605-2e8a4d8b9af6.png)

**Comment by Sdreamery** [comment]
![1b17e46f048240ae0a5f819fe107e99](https://user-images.githubusercontent.com/38490969/209507838-1c748253-fb41-4193-b7c8-fb6a76cbbd5e.jpg)

**Comment by Sdreamery** [comment]
@Tianqi-Dotes #13278 This also proposed by me and has been closed

**Comment by jieguangzhou** [comment]
This is not a bug, #12725 hopes to make the dag beautiful.

If someone like the original style types of dag, we can discuss this in the mailing list or in the weekly meeting (2022.01.04 20:00)

@Sdreamery , cc: @calvinjiang
