### ISSUE TITLE
[Bug] [Master] resume failure processInstance state remain failure

### ISSUE THREAD

**Issue by KEN-LJQ** [apache/dolphinscheduler#13272]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Workflow process instance resume from failure state, and all task run success actully, but task instance and process intance remain failure. And when you click resume again, all switch to success.

Checking task log, the task has submit and run success when resume.

Checking database table `t_ds_task_instance`. There two record, old one state is failure, and new one is success. Which make sense.
![企业微信截图_20221224173844](https://user-images.githubusercontent.com/16650282/209430139-7495d810-8556-4512-beab-06d8f8ae01ac.png)

Since task is success, why ds judge it faliure and show failure on ui. Digging the ui http query, we found that it query both two record and return it, because of the `flag`.
![企业微信截图_20221224174251](https://user-images.githubusercontent.com/16650282/209430314-3a1d54d8-7c03-4c70-be63-74032a4dacbc.png)
![企业微信截图_20221224174335](https://user-images.githubusercontent.com/16650282/209430346-d6336206-ea39-456b-9c99-3ee61692d489.png)
![企业微信截图_20221224174406](https://user-images.githubusercontent.com/16650282/209430350-028703aa-f4ed-49a0-97a4-53f1a4a5ad28.png)
![企业微信截图_20221224174501](https://user-images.githubusercontent.com/16650282/209430373-7ea10350-d4e6-4715-a3db-964a56e80bd5.png)

And I don't know what happen, thx for help.

### What you expected to happen

both task instance and process instance should change to success

### How to reproduce

1. create a workflow with task which suppose to run fail, and configure retry 3 times
2. run workflow. task instance state should be failure and waiting to retry, and process instance stay running
3. click stop. task instance state should be failure and process instance state should be stoped
4. modify task make it will run success
5. click resume
6. task has submit and run. but when it finish, both task and process instance state change to failure
7. click resume again
8. both task and process change to success

### Anything else

we are on v2.0.7

### Version

2.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by KEN-LJQ** [comment]
kind of associate with this issue https://github.com/apache/dolphinscheduler/issues/10673

**Comment by brave-lee** [comment]
Hi @KEN-LJQ , modify the task in step 4, the task version add 1, and then click resume, the running task is not initial task. I think task_instance has two record, old one state is failure, and new one is success, that is normal

**Comment by brave-lee** [comment]
<img width="775" alt="image" src="https://user-images.githubusercontent.com/42576980/212797237-3a73d07a-7f14-4e7a-a118-925fb5e46b53.png">

**Comment by KEN-LJQ** [comment]
Hi, @JinyLeeChina thanks for your replay. And yes, two record is right, but I has a question about is that normal this task and process judge as failure just because there's a failure record?  But the truth is new one is success, should we judge this task as success?

**Comment by SbloodyS** [comment]
Hi @KEN-LJQ , In step 4 `modify task make it will run success`, did you update the definition of process instance 33? If not, then resume the process instance will result in the same failure.

**Comment by KEN-LJQ** [comment]
@SbloodyS , yes, I modify it

**Comment by SbloodyS** [comment]
I can not reproduce this issue according to your steps with shell task in the 2.0.5-release. Are there any important steps missing? @KEN-LJQ

**Comment by brave-lee** [comment]
Hi @KEN-LJQ , I tested according to your steps, but the result of step 6 is different from yours. My result is task instance success and process instance  fail, and task and process instance should be success

**Comment by KEN-LJQ** [comment]
@SbloodyS @JinyLeeChina let me test it according my step again, what is your version?

**Comment by brave-lee** [comment]
I tested it use 2.0.7 and 2.0.8-prepare, I suggest you use the 2.0.8-prepare to test

**Comment by KEN-LJQ** [comment]
@JinyLeeChina I try with 2.0.8-prepare, still can reproduce, may be you missing config retry?
![企业微信截图_20230117135952](https://user-images.githubusercontent.com/16650282/212821912-bc031801-cc3d-44cb-b870-27bc74f43040.png)

**Comment by brave-lee** [comment]
No, I config retry, however, it cannot reproduce the failure of process and task instances. The result is that the process instance fails and the task instance succeeds
![image](https://user-images.githubusercontent.com/42576980/212904233-0bbc0bba-38d7-41e0-bdb2-0a85a82abf33.png)
![image](https://user-images.githubusercontent.com/42576980/212904325-8338665d-a2b2-4555-9a36-afee1952d0a6.png)
![image](https://user-images.githubusercontent.com/42576980/212904401-83f67d09-f9eb-431a-8990-00ee54465ff7.png)

**Comment by KEN-LJQ** [comment]
Maybe I missing some steps, I will test it again later to figure out why. But as your results,process instance becomes failures suppose to be wrong result?

**Comment by brave-lee** [comment]
> Maybe I missing some steps, I will test it again later to figure out why. But as your results,process instance becomes failures suppose to be wrong result?

Yes, I will confirm why it happen

**Comment by brave-lee** [comment]
> Maybe I missing some steps, I will test it again later to figure out why. But as your results,process instance becomes failures suppose to be wrong result?

I submit a PR to fix it, @KEN-LJQ @SbloodyS please review
