### ISSUE TITLE
The version 3.1.1 Canvas connection confusion

### ISSUE THREAD

**Issue by Sdreamery** [apache/dolphinscheduler#13278]
The version 3.1.1 Canvas connection confusion，but 3.1.0 is natural.

**Comment by Sdreamery** [comment]
![3 1 1异常画布连线](https://user-images.githubusercontent.com/38490969/209507938-afaf9595-3cde-4d18-9392-e3e90cc1157f.png)

**Comment by Sdreamery** [comment]
![3 1 0正常画布连线](https://user-images.githubusercontent.com/38490969/209507969-287d89cf-2670-4f1f-b2c9-3c01a6cc8dbb.jpg)

**Comment by Tianqi-Dotes** [comment]
seems the same issue :https://github.com/apache/dolphinscheduler/issues/13277
