### ISSUE TITLE
[Doc][Seatunnel] version 3.0.2 has Seatunnel task but no related documentation

### ISSUE THREAD

**Issue by Tianqi-Dotes** [apache/dolphinscheduler#13289]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

version 3.0.2 has the Seatunnel task but no related documentation, need to migrate ST doc to version 3.0.2
https://dolphinscheduler.apache.org/en-us/docs/3.0.2

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HudsonShi** [comment]
I am interested!

**Comment by zhongjiajie** [comment]
@HudsonShi  I had assigned to you, please try to make our document wonderful
