### ISSUE TITLE
[Bug] [Api] When serial complement is a process configured with timing scheduling, an error will occur when selecting a time that is not within the timing range

### ISSUE THREAD

**Issue by wcmolin** [apache/dolphinscheduler#13292]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When serial complement is a process configured with timing scheduling, an error will occur when selecting a time that is not within the timing range. The schedule time field of the complement process instance is empty

![222](https://user-images.githubusercontent.com/11606262/209778497-ef5159fe-eab7-46e6-980e-08dfcad36ef7.png)

### What you expected to happen

Needs at least an error message like parallel complement

![012](https://user-images.githubusercontent.com/11606262/209778981-1e0ba18e-d32a-4e51-b52e-caa41fc9d39f.png)

### How to reproduce

Refer to the figure below to configure a shell task for printing time, configure the timing schedule at 8:00 on the 1st of each month, choose `Complement Data`, select the time access as December 27 to December 28, and select `Serial execution` as the mode of execution

![000](https://user-images.githubusercontent.com/11606262/209779060-9e865fa8-72d3-4d52-aebf-95d6ab3aec95.png)
![010](https://user-images.githubusercontent.com/11606262/209779066-c4ed028d-8e42-44b2-895c-bb8ed42cc40e.png)
![111](https://user-images.githubusercontent.com/11606262/209779082-e1ed9003-2166-4c78-9ee0-00a3a3015e3e.png)

this is log:
```
[INFO] 2022-12-28 15:51:19.039 org.apache.dolphinscheduler.server.worker.processor.TaskExecuteProcessor:[110] - received command : TaskExecuteRequestCommand{taskExecutionContext='{"taskInstanceId":20,"taskName":"print_date","firstSubmitTime":"2022-12-28 15:51:19","startTime":null,"endTime":null,"taskType":"SHELL","host":null,"executePath":null,"logPath":null,"taskJson":null,"processId":0,"processDefineCode":8036254112960,"processDefineVersion":1,"appIds":null,"processInstanceId":19,"scheduleTime":null,"globalParams":null,"executorId":1,"cmdTypeIfComplement":5,"tenantCode":"molin","queue":"default","projectCode":7960944102080,"taskParams":"{\"resourceList\":[],\"localParams\":[{\"prop\":\"rq\",\"direct\":\"IN\",\"type\":\"VARCHAR\",\"value\":\"${system.biz.curdate}\"}],\"rawScript\":\"echo \\\"rq--->\\\"\\necho ${rq}\\necho \\\"end--->\\\"\",\"dependence\":{},\"conditionResult\":{\"successNode\":[],\"failedNode\":[]},\"waitStartTimeout\":{},\"switchResult\":{}}","envFile":null,"environmentConfig":null,"definedParams":null,"taskAppId":null,"taskTimeoutStrategy":null,"taskTimeout":2147483647,"workerGroup":"default","delayTime":0,"currentExecutionStatus":null,"resources":{},"sqlTaskExecutionContext":{"warningGroupId":0,"connectionParams":null,"udfFuncTenantCodeMap":null,"defaultFS":null},"dataxTaskExecutionContext":{"dataSourceId":0,"sourcetype":0,"sourceConnectionParams":null,"dataTargetId":0,"targetType":0,"targetConnectionParams":null},"dependenceTaskExecutionContext":null,"sqoopTaskExecutionContext":{"dataSourceId":0,"sourcetype":0,"sourceConnectionParams":null,"dataTargetId":0,"targetType":0,"targetConnectionParams":null},"varPool":null,"dryRun":0,"paramsMap":null,"procedureTaskExecutionContext":{"connectionParams":null}}'}
[INFO] 2022-12-28 15:51:19.054 org.apache.dolphinscheduler.common.utils.FileUtils:[121] - create dir success /tmp/dolphinscheduler/exec/process/7960944102080/8036254112960_1/19/20
[INFO] 2022-12-28 15:51:19.054 org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread:[128] - task instance local execute path : /tmp/dolphinscheduler/exec/process/7960944102080/8036254112960_1/19/20
[INFO] 2022-12-28 15:51:19.144 org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread:[146] - the task begins to execute. task instance id: 20
[INFO] 2022-12-28 15:51:19.155 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[83] - shell task params {"resourceList":[],"localParams":[{"prop":"rq","direct":"IN","type":"VARCHAR","value":"${system.biz.curdate}"}],"rawScript":"echo \"rq--->\"\necho ${rq}\necho \"end--->\"","dependence":{},"conditionResult":{"successNode":[],"failedNode":[]},"waitStartTimeout":{},"switchResult":{}}
[ERROR] 2022-12-28 15:51:19.165 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[103] - shell task error
java.lang.IllegalArgumentException: The date must not be null
	at org.apache.dolphinscheduler.spi.utils.DateUtils.add(DateUtils.java:282)
	at org.apache.dolphinscheduler.spi.utils.DateUtils.addDays(DateUtils.java:265)
	at org.apache.dolphinscheduler.spi.task.paramparser.BusinessTimeUtils.getBusinessTime(BusinessTimeUtils.java:54)
	at org.apache.dolphinscheduler.spi.task.paramparser.ParamUtils.convert(ParamUtils.java:79)
	at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.parseScript(ShellTask.java:161)
	at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.buildCommand(ShellTask.java:134)
	at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.handle(ShellTask.java:96)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:191)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 2022-12-28 15:51:19.166 org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread:[208] - task scheduler failure
java.lang.IllegalArgumentException: The date must not be null
	at org.apache.dolphinscheduler.spi.utils.DateUtils.add(DateUtils.java:282)
	at org.apache.dolphinscheduler.spi.utils.DateUtils.addDays(DateUtils.java:265)
	at org.apache.dolphinscheduler.spi.task.paramparser.BusinessTimeUtils.getBusinessTime(BusinessTimeUtils.java:54)
	at org.apache.dolphinscheduler.spi.task.paramparser.ParamUtils.convert(ParamUtils.java:79)
	at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.parseScript(ShellTask.java:161)
	at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.buildCommand(ShellTask.java:134)
	at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.handle(ShellTask.java:96)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:191)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2022-12-28 15:51:20.172 org.apache.dolphinscheduler.service.log.LogClientService:[117] - view log path /Users/molin/dev/github/dolphinscheduler/logs/8036254112960_1/19/20.log
[INFO] 2022-12-28 15:51:20.176 org.apache.dolphinscheduler.remote.NettyRemotingClient:[390] - netty client closed
[INFO] 2022-12-28 15:51:20.176 org.apache.dolphinscheduler.service.log.LogClientService:[74] - logger client closed
[INFO] 2022-12-28 15:51:20.190 org.apache.dolphinscheduler.common.utils.FileUtils:[121] - create dir success /tmp/dolphinscheduler/exec/process/7960944102080/8036254112960_1/19/20
[INFO] 2022-12-28 15:51:20.191 org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread:[264] - develop mode is: false
[INFO] 2022-12-28 15:51:20.192 org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread:[282] - exec local path: /tmp/dolphinscheduler/exec/process/7960944102080/8036254112960_1/19/20 cleared.
```

### Version

2.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Sky-Gu** [comment]
I had a similar problem.
dolphinscheduler version:3.1.1

Set the timing for the task. crontab: 0 0 10,22 * * ? *
Operation Task To perform the supplementary number. The supplementary number time is 2022-12-20——2022-12-22

The work flow of the complement is executed like this:
2022-12-20 10:00:00
2022-12-20 22:00:00
2022-12-21 10:00:00
2022-12-21 22:00:00
Will use crontab time to execute, not the complement time. And complementEndDate also has no trigger complement
 

The expected effect should be:
2022-12-20 00:00:00
2022-12-21 00:00:00
2022-12-22 00:00:00

**Comment by wcmolin** [comment]
> I had a similar problem. dolphinscheduler version:3.1.1
> 
> Set the timing for the task. crontab: 0 0 10,22 * * ? * Operation Task To perform the supplementary number. The supplementary number time is 2022-12-20——2022-12-22
> 
> The work flow of the complement is executed like this: 2022-12-20 10:00:00 2022-12-20 22:00:00 2022-12-21 10:00:00 2022-12-21 22:00:00 Will use crontab time to execute, not the complement time. And complementEndDate also has no trigger complement
> 
> The expected effect should be: 2022-12-20 00:00:00 2022-12-21 00:00:00 2022-12-22 00:00:00

The problem you describe is not a bug, it is the function

**Comment by Sky-Gu** [comment]
> > I had a similar problem. dolphinscheduler version:3.1.1
> > Set the timing for the task. crontab: 0 0 10,22 * * ? * Operation Task To perform the supplementary number. The supplementary number time is 2022-12-20——2022-12-22
> > The work flow of the complement is executed like this: 2022-12-20 10:00:00 2022-12-20 22:00:00 2022-12-21 10:00:00 2022-12-21 22:00:00 Will use crontab time to execute, not the complement time. And complementEndDate also has no trigger complement
> > The expected effect should be: 2022-12-20 00:00:00 2022-12-21 00:00:00 2022-12-22 00:00:00
> 
> The problem you describe is not a bug, it is the function

If the time range of the complement is a single day, for example:2022-12-24——2022-12-24, this effect does not occur

**Comment by wcmolin** [comment]
> > > I had a similar problem. dolphinscheduler version:3.1.1
> > > Set the timing for the task. crontab: 0 0 10,22 * * ? * Operation Task To perform the supplementary number. The supplementary number time is 2022-12-20——2022-12-22
> > > The work flow of the complement is executed like this: 2022-12-20 10:00:00 2022-12-20 22:00:00 2022-12-21 10:00:00 2022-12-21 22:00:00 Will use crontab time to execute, not the complement time. And complementEndDate also has no trigger complement
> > > The expected effect should be: 2022-12-20 00:00:00 2022-12-21 00:00:00 2022-12-22 00:00:00
> > 
> > 
> > The problem you describe is not a bug, it is the function
> 
> If the time range of the complement is a single day, for example:2022-12-24——2022-12-24, this effect does not occur

This is true when the start time and end time are exactly the same, e.g. 2022-12-24 00:00:00 and 2022-12-24 00:00:00
