### ISSUE TITLE
[Bug] [Module Name] query page error 

### ISSUE THREAD

**Issue by jamescheng16** [apache/dolphinscheduler#13299]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

分页查询出错

![Screenshot 2022-12-29 at 13 57 21](https://user-images.githubusercontent.com/4263914/209909540-0fc3fcfa-d04f-4bcf-9c98-4bf8ec615b33.png)
![Screenshot 2022-12-29 at 13 57 19](https://user-images.githubusercontent.com/4263914/209909554-155ae715-744b-4798-976b-a7b331ed85c0.png)
![Screenshot 2022-12-29 at 13 56 16](https://user-images.githubusercontent.com/4263914/209909579-50eba4e2-b00d-4bbf-bcbf-49b370f4e978.png)

### What you expected to happen

can't see definition

### How to reproduce

delete a definition

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
it seems we have data corruption here, the records repeated.

**Comment by jamescheng16** [comment]
> it seems we have data corruption here, the records repeated.

how to fix this problem

**Comment by yjunsun** [comment]
we have same issue

**Comment by yjunsun** [comment]
Position: 23
; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: relation "t_ds_worker_group" does not exist
  Position: 23
[INFO] 2022-12-29 16:14:03.876 +0800 org.apache.dolphinscheduler.remote.NettyRemotingClient:[334] - [WorkflowInstance-0][TaskInstance-0] - netty client closed
[INFO] 2022-12-29 16:14:03.876 +0800 org.apache.dolphinscheduler.service.log.LogClient:[229] - [WorkflowInstance-0][TaskInstance-0] - LogClientService closed
[INFO] 2022-12-29 16:14:03.879 +0800 org.apache.curator.framework.imps.CuratorFrameworkImpl:[998] - [WorkflowInstance-0][TaskInstance-0] - backgroundOperationsLoop exiting
[WARN] 2022-12-29 16:14:03.887 +0800 org.apache.zookeeper.ClientCnxn:[1286] - [WorkflowInstance-0][TaskInstance-0] - An exception was thrown while closing send thread for session 0x1000000b7c20a41.
org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x1000000b7c20a41, likely server has closed socket
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1282)
[INFO] 2022-12-29 16:14:03.988 +0800 org.apache.zookeeper.ClientCnxn:[568] - [WorkflowInstance-0][TaskInstance-0] - EventThread shut down for session: 0x1000000b7c20a41
[INFO] 2022-12-29 16:14:03.988 +0800 org.apache.zookeeper.ZooKeeper:[1232] - [WorkflowInstance-0][TaskInstance-0] - Session: 0x1000000b7c20a41 closed
[WARN] 2022-12-29 16:14:03.990 +0800 org.springframework.beans.factory.support.DisposableBeanAdapter:[248] - [WorkflowInstance-0][TaskInstance-0] - Invocation of close method failed on bean with name 'springApplicationContext': org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'applicationAvailability': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
[INFO] 2022-12-29 16:14:03.990 +0800 com.zaxxer.hikari.HikariDataSource:[350] - [WorkflowInstance-0][TaskInstance-0] - DolphinScheduler - Shutdown initiated...
[INFO] 2022-12-29 16:14:03.994 +0800 com.zaxxer.hikari.HikariDataSource:[352] - [WorkflowInstance-0][TaskInstance-0] - DolphinScheduler - Shutdown completed.
[INFO] 2022-12-29 16:14:03.996 +0800 org.eclipse.jetty.server.session:[149] - [WorkflowInstance-0][TaskInstance-0] - node0 Stopped scavenging
[INFO] 2022-12-29 16:14:03.997 +0800 org.eclipse.jetty.server.handler.ContextHandler:[1159] - [WorkflowInstance-0][TaskInstance-0] - Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@117fb9ba{application,/,[file:///tmp/jetty-docbase.5679.565947093484085428/],STOPPED}
[INFO] 2022-12-29 16:14:04.011 +0800 org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener:[136] - [WorkflowInstance-0][TaskInstance-0] -

**Comment by yjunsun** [comment]
![image](https://user-images.githubusercontent.com/7857748/209923809-2ec735d0-ca8e-4753-b324-04130ca20a14.png)

**Comment by woxiangwoshi123** [comment]
> ![图片](https://user-images.githubusercontent.com/7857748/209923809-2ec735d0-ca8e-4753-b324-04130ca20a14.png)

You can use binary code to generate a database, then compare which fields are missing, and complete these fields.

**Comment by yjunsun** [comment]
> 

ok, i will try it. tks.
