### ISSUE TITLE
[Bug] [UI] The project name cannot be searched when a dependency node is added

### ISSUE THREAD

**Issue by ypplikebluesky** [apache/dolphinscheduler#13293]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![Snipaste_2022-12-28_16-34-35](https://user-images.githubusercontent.com/121544068/209783275-1cb90f1a-eb29-4968-9fab-38c88d49c0d1.png)

### What you expected to happen

I hope it will be recover quikly

### How to reproduce

null

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I'll check out this issue.
