### ISSUE TITLE
[Bug] [UI] Dependencies in workflow instances show failures，version 3.1.2

### ISSUE THREAD

**Issue by woxiangwoshi123** [apache/dolphinscheduler#13302]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

This dependency is configured in my workflow definition and it is displayed normally.
<img width="1326" alt="Snipaste_2022-12-29_17-29-48" src="https://user-images.githubusercontent.com/32809232/209931905-c59890b8-486a-47b4-9433-46ccd0eb2b71.png">
But when I run the workflow, the dependency display fails in the workflow instance, as shown in the screenshot below.
<img width="1455" alt="Snipaste_2022-12-29_17-31-23" src="https://user-images.githubusercontent.com/32809232/209932035-8b086620-e808-4dab-a94e-77c1520db2fe.png">

### What you expected to happen

I want to see the correct dependencies also in the workflow instance

### How to reproduce

none

### Anything else

none

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I'll check out this issue.

**Comment by woxiangwoshi123** [comment]
> 此问题已自动标记为陈旧，因为它已经 30 天没有最近的活动。如果没有进一步的活动，它将在接下来的 7 天内关闭。

this question is import, please repaire it.
