### ISSUE TITLE
DolphinScheduler3.1.1 Upgrade

### ISSUE THREAD

**Issue by hetianliang** [apache/dolphinscheduler#13308]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The upgrade service item in the document, let me make changes according to the "modify configuration" in the cluster part, but the link in the cluster part is not data, and it is impossible to refer to the modification of the cluster mode service upgrade.

### Documentation Links

https://dolphinscheduler.apache.org/en-us/docs/3.1.2/guide/upgrade/upgrade

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
looking forward your contribution

**Comment by zhongjiajie** [comment]
remove stale
