### ISSUE TITLE
[Doc][Cluster] Documentation is too sloppy

### ISSUE THREAD

**Issue by geekyouth** [apache/dolphinscheduler#13311]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

**The cluster mode should be the focus, but the author tells readers to refer to the pseudo-cluster document, which will only increase the difficulty of deployment for developers and affect the robustness of the main program**

### Documentation Links

https://dolphinscheduler.apache.org/zh-cn/docs/3.1.2/guide/installation/cluster
![image](https://user-images.githubusercontent.com/12899262/210190504-774d0bfb-303d-403c-b5c5-14decd51f177.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
Is there anybody else who has the same question? please leave a message
