### ISSUE TITLE
[Bug] [server] the out param not be replaced when rerun the sql task

### ISSUE THREAD

**Issue by ChPi** [apache/dolphinscheduler#13320]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

the out param not be replaced when rerun a workflow 

### What you expected to happen

the out param should be replaced

### How to reproduce

the sql task
<img width="571" alt="image" src="https://user-images.githubusercontent.com/20807051/210311809-ae617011-5ce1-4e9c-83e8-1fe4fad2c98e.png">
the shell task which get the `dt` from the sql task
<img width="561" alt="image" src="https://user-images.githubusercontent.com/20807051/210311391-654d3353-0f5c-4c83-a72c-86792ca4dfd9.png">
run the workflow, shell task log
```
[INFO] 2023-01-03 06:46:42.916 +0000 - Success clear the task execute file: /tmp/dolphinscheduler/exec/process/jie/8102121698688/8102143663872_1/1/2
[INFO] 2023-01-03 06:46:43.735 +0000 -  -> 2023-01-03 14:46:42
[INFO] 2023-01-03 06:46:43.751 +0000 - FINALIZE_SESSION
```
then rerun the instance after a few minutes, shell task log
```
[INFO] 2023-01-03 06:53:41.300 +0000 - Success clear the task execute file: /tmp/dolphinscheduler/exec/process/jie/8102121698688/8102143663872_1/1/4
[INFO] 2023-01-03 06:53:42.230 +0000 -  -> 2023-01-03 14:46:42
[INFO] 2023-01-03 06:53:42.236 +0000 - FINALIZE_SESSION
```
still print `2023-01-03 14:46:42`, not be replaced

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Yinyuhang123** [comment]
![image](https://user-images.githubusercontent.com/116626639/223666469-ad399755-801f-45c3-a910-1f29bbf862ef.png)
Why close this problem? It still exists

**Comment by Yinyuhang123** [comment]
I am using version 3.1.4
