### ISSUE TITLE
[discussion] how to redesign Permission

### ISSUE THREAD

**Issue by davidzollo** [apache/dolphinscheduler#1333]
We want to redesign the permission about DS, if you have some ideas ,please leave message.

**Comment by dailidong** [comment]
#1321

**Comment by MiaoSO** [comment]
After tested version 1.1, the following is my advice.

1. Tenant
In my opinion, tenants need to be empowered. Some administrator tenants(such as HDFS and Hive) are at risk if they are exposed to ordinary users.
Suggest  change "Tenant Name" could not non-repeatable

2. Resources
(1) I personally think that there is no need to involve the tenant. 
I don't agree with the design that the user tenant will copy the files to the directory of the new tenant, which will cause file redundancy(From the results of testing on HDFS, other file centers have not tested).

(2) Enter "Resources-> FIle Manage"
Suggest change "Name and FileName" to "FileName, MD5Name (FileName+owner+createtime to unique identifier), Owner, LastModifyUser".
The FileName of the same user cannot be duplicated, and the HDFS storage file name is MD5Name. The files are placed in one directory.
File permissions can be designed to make the files visible to team members in the project or to themselves

3. Project 
The project created by the administrator, the administrator has the highest authority of the project.
Ordinary users can only in the project development for workflow

4. Process definitions
The user of the workflow is recommended to bind to the project ID, not the user. 
If the user is deleted, the workflow invalidation is an unreasonable design.

**Comment by HanadaLee** [comment]
Suggestions for improvements to permission control from others were redirected to this issue, but no progress has been seen in four years. Currently, permissions for all functions need to be explicitly granted to everyone, which is very complicated for a multi-person collaboration platform. I recommend introducing RBAC to solve the existing problem.
