### ISSUE TITLE
[Bug] inconsistency between meta database and ui

### ISSUE THREAD

**Issue by irisah9** [apache/dolphinscheduler#13344]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

3.0.0 cluster
I change the detail _t_ds_task_definition.task_params_ , but, the detail shown on ui not changed. And it runs according to ui not meta database.

### What you expected to happen

They two should be same.

### How to reproduce

change the _t_ds_task_definition.task_params_, then see it on ui and run.

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
It is not recommended to modify metadata directly. Using open-api or page is recommended.

If you insist on revising metadata. You can try to modify `t_ds_task_definition ` and `t_ds_task_definition_log` together. Only one modification is not enough.
