### ISSUE TITLE
[Bug] [Master] Failover may never succeed if master crashes during failover

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#13355]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

* When master performs failover, it would set the host of process instances which need failover to `NULL`. If master crashes after this step but the failover of process instances hasn't ended yet, those process instances will never get failover again.

https://github.com/apache/dolphinscheduler/blob/2a44a7f36a4be85221703bc3d8d70a650860b31e/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/MasterFailoverService.java#L197-L202

https://github.com/apache/dolphinscheduler/blob/2a44a7f36a4be85221703bc3d8d70a650860b31e/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/MasterFailoverService.java#L291-L298

### What you expected to happen

* Failover should succeed eventually, even if master crashes during failover.

### How to reproduce

1. Kill workers.
2. Kill masters.
3. Start masters, now masters will perform failover, but there are current no workers, so failover will not succeed.
4. Restart masters and start workers, masters will perform failover again. However, in step 3, the hosts of process instances need failover are set to NULL, they will never really get failover successfully.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
I'm not sure whether it is a bug or it is designed to act like this? May I ask whether we need to fix it? @ruanwenjun @caishunfeng

**Comment by EricGao888** [comment]
No close

**Comment by skytt** [comment]
I have the same issue. Is there any progress?
