### ISSUE TITLE
[Bug] [master] Handling 4 trigger(s) that missed their scheduled fire-time. Scheduled tasks missed during peak hours

### ISSUE THREAD

**Issue by CRUDKanade** [apache/dolphinscheduler#13364]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

调度高峰时存在某些任务到执行时刻后没有启动
![image](https://user-images.githubusercontent.com/71861187/211458759-3d790f84-2c71-4be1-b81b-9f41685905fc.png)

### What you expected to happen

高峰期时任务能正常按时启动 , 可能是quartz线程配置不足以同时处理太多任务的问题 ? 我无法确定

### How to reproduce

两个master , 4C8G 
同一时刻调度任务超300个

### Version

2.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Which version are you using? @CRUDKanade

**Comment by CRUDKanade** [comment]
> 

2.0.6

**Comment by CRUDKanade** [comment]
> Which version are you using? @CRUDKanade

2.0.6

**Comment by SbloodyS** [comment]
Is the performance of the metabase db sufficient?
