### ISSUE TITLE
[Bug] [Module Name] 

### ISSUE THREAD

**Issue by hkun0120** [apache/dolphinscheduler#13366]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

3.0.0版本，上传到Hadoop资源中心中的文件，在工作流中执行，下载后归属于root用户而不是当前用户，导致无法执行。

### What you expected to happen

从资源中心下载的文件别的用户也有权限执行，或者下载的文件归属于当前登陆用户。

### How to reproduce

1、上传文件
2、在工作流中执行。

### Version

3.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This problem is about the permissions of Linux. Please use the correct title. I'll close this issue.

**Comment by hkun0120** [comment]
> This problem is about the permissions of Linux. Please use the correct title. I'll close this issue.

how can I fix this question?

**Comment by SbloodyS** [comment]
> how can I fix this question?

You can ask it in stackoverflow.
