### ISSUE TITLE
[BUG] Scheduled execution error

### ISSUE THREAD

**Issue by kinggrind-yanxuelin** [apache/dolphinscheduler#13371]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

my dolphinscheduler version is 3.1.0
i have a shell task, it has a in param.....
it works success when Manual execution，，but when Scheduled execution  it don't work.

### What you expected to happen

see  What happened 

### How to reproduce

see What happened

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Can you provide some detailed logs?

**Comment by kinggrind-yanxuelin** [comment]
this is the error stack, i think any task script will reproduce this bug

[ERROR] 2023-01-11 10:02:01.149 +0800 TaskLogLogger-class org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor:[125] - [WorkflowInstance-89352][TaskInstance-0] - submit task error
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.service.expand.CuringGlobalParams.paramParsingPreparation(CuringGlobalParams.java:154)
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.getTaskExecutionContext(BaseTaskProcessor.java:336)
	at org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor.dispatchTask(CommonTaskProcessor.java:113)
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.dispatch(BaseTaskProcessor.java:241)
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.action(BaseTaskProcessor.java:212)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitTaskExec(WorkflowExecuteRunnable.java:976)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitStandByTask(WorkflowExecuteRunnable.java:1816)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitPostNode(WorkflowExecuteRunnable.java:1349)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.call(WorkflowExecuteRunnable.java:695)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by kinggrind-yanxuelin** [comment]
if a task have a param, it will not work in Scheduled mode

**Comment by kinggrind-yanxuelin** [comment]
our test task script in table t_ds_task_definition_log is  below,,,if we remove the prop 'ds_param_month' it works fine!!

{"localParams":[{"prop":"ds_param_month","direct":"IN","type":"VARCHAR","value":"202301"}],"rawScript":"echo 11","resourceList":[]}

**Comment by Radeity** [comment]
@kinggrind-yanxuelin Can you check what's the value of field `timezone_id` in table `t_ds_schedules`, also `command_param` in `t_ds_process_instance`?

**Comment by kinggrind-yanxuelin** [comment]
thanks very match for your help, our timezone_id is Asia/Shanghai...

the bug dosn't care what params.
you can reproduce this bug on any task when the task hase a param and run the task on Scheduled  mode.

maybe The bug description is not clear.  i repeat the bug in chinese.
1: 在 dolphinscheduler 中随意创建一个 process 
2: 在 process中增加一个shell 任务，shell 任务的脚本 写 简单的  echo 1 
3：给shell任务随意增加一个 自定义参数，然后保存process
4：手动运行这个process，可以正常运行
5：设置定时运行这个process，会产生 task instance host is null 的报错

**Comment by Radeity** [comment]
I'm sry that i can not reproduce your bug, you can check logs that whether it prints correct master config info. Your bug seems that task instance can not get the master address.

**Comment by Radeity** [comment]
I'm sry that i can not reproduce your bug, based on your trace log, if your version is 3.1.0, CuringGlobalParams.java:154 is as following: `String timeZone = cmdParam.get(Constants.SCHEDULE_TIMEZONE);` That's why i think you should check `command_param`. It's may not be a bug in DS, you can further check by yourself or you can upgrade your DS version and find whether the bug still exists.

**Comment by kinggrind-yanxuelin** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月12日(星期四) 上午10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] [BUG] Scheduled execution error (Issue #13371)





 
I'm sry that i can not reproduce your bug, you can check logs that whether it prints correct master config info. Your bug seems that task instance can not get the master address.

**Comment by kinggrind-yanxuelin** [comment]
Last message&nbsp; show the bug pics
this i remove the param, it works success!!

Stages of BUG generation maybe is parsing the param (scheduler mode)&nbsp;&nbsp;

can you&nbsp;reproduce&nbsp;this bug? if not ,which config i shoud to change?






























------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月12日(星期四) 中午11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] [BUG] Scheduled execution error (Issue #13371)





 
I'm sry that i can not reproduce your bug, based on your trace log, if your version is 3.1.0, CuringGlobalParams.java:154 is as following: String timeZone = cmdParam.get(Constants.SCHEDULE_TIMEZONE); That's why i think you should check command_param. It's may not be a bug in DS, you can further check by yourself.

**Comment by Radeity** [comment]
I can't reproduce it, please upgrade the version and try again. : )

**Comment by kinggrind-yanxuelin** [comment]
thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月12日(星期四) 下午2:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] [BUG] Scheduled execution error (Issue #13371)





 
I can't reproduce it, please upgrade the version and try again. : )

**Comment by jizhanjia** [comment]
你好，
我也出现添加参数，主机为null的情况，你那边解决了吗

**Comment by jizhanjia** [comment]
> @kinggrind-yanxuelin Can you check what's the value of field `timezone_id` in table `t_ds_schedules`, also `command_param` in `t_ds_process_instance`?

我这边出现相似问题，经过查看，timezone_id为：Asia/Shanghai ，t_ds_process_instance 的command_param为null

**Comment by kinggrind-yanxuelin** [comment]
升级到 3.1.3 就可以了，，它在 3.1.1的版本里面 专门处理了这个BUG


这个升级也很简单




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月19日(星期四) 下午3:05
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] [BUG] Scheduled execution error (Issue #13371)





 
你好，
 我也出现添加参数，主机为null的情况，你那边解决了吗
