### ISSUE TITLE
[Improvement][pydolphinscheduler] workflow's DAG nodes looks overlap when created by pydolphinscheduler 

### ISSUE THREAD

**Issue by finviman** [apache/dolphinscheduler#13370]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I create workflow with pydolphinscheduler version 3.0.1 , after created, I find all the nodes overlap in workflow DAG view page, I must format it manually to see the whole graph clearly.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by finviman** [comment]
I dig into the pydolphinscheduler source code, all tasks are put to (0,0) position in 3.0.1,  in the latest version i find that task locations param is null. 
and , also pydolphinscheduler , work_group is always default no matter i put any value in config.yaml file or process_definition construct parameters.

**Comment by FinallyFinancialFreedom** [comment]
reopen it then

**Comment by humbinal** [comment]
这个缺陷貌似没有解决，怎么就被关闭了？
This issue seems not to be solved, why is it closed?

**Comment by HurleyWu** [comment]
is there any solution for this problems
