### ISSUE TITLE
[Bug] [complete data] process instance stuck when we use serial complete data

### ISSUE THREAD

**Issue by eric0323-hub** [apache/dolphinscheduler#13384]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

A BUG with the complement function. When we used the serial complement function for a period of time, we found that there was an exception. 

### What you expected to happen

For example, if the complement time was three days, only the first instance was displayed as complete, while the second instance was always displayed as running, and the corresponding task under the instance had already been completed, that is, the status of the second instance had not been updated. The subsequent run instance will not appear again. 

### How to reproduce

processes: Workflow definition -> Click Online, Run -> Select Serial Complement -> Select Time Span -> Click Run. It shows that except the first instance is successfully completed, all the subsequent instances are stuck. 
When there are at least 100,000 entries in the t_ds_task_definition_log table, the question will reappear

### Version

2.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Could you provide more details about this? I can't reproduce this issue in 2.0.5-release.

**Comment by eric0323-hub** [comment]
> Could you provide more details about this? I can't reproduce this issue in 2.0.5-release.

we use 2.0.0-alpha,you can reproduce in this version.

**Comment by SbloodyS** [comment]
> we use 2.0.0-alpha,you can reproduce in this version.

This version is no longer in the maintaining list. You can try to upgrade to the latest version.
