### ISSUE TITLE
[Bug] [Master] Stop the workflow then alway in READY_STOP

### ISSUE THREAD

**Issue by liangkiller** [apache/dolphinscheduler#13389]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Stop the workflow instance, and the instance state is READY_STOP and cannot change state to  stop. The master log print:

[INFO] 2023-01-12 14:25:55.341 +0800 org.apache.dolphinscheduler.server.master.processor.StateEventProcessor:[73] - [WorkflowInstance-94289][TaskInstance-0] - Received state change command, event: StateEvent(key=94289-0-94289-0, type=PROCESS_STATE_CHANGE, executionStatus=READY_STOP, taskInstanceId=0, taskCode=0, processInstanceId=94289, context=null, channel=null)

[WARN] 2023-01-12 14:25:55.341 +0800 org.apache.dolphinscheduler.server.master.processor.queue.StateEventResponseService:[147] - [WorkflowInstance-94289][TaskInstance-0] - Persist event into workflow execute thread error, cannot find the workflow instance from cache manager, event: StateEvent(key=94289-0-94289-0, type=PROCESS_STATE_CHANGE, executionStatus=READY_STOP, taskInstanceId=0, taskCode=0, processInstanceId=94289, context=null, channel=null)

### What you expected to happen

the workflow instance can stop

### How to reproduce

stop the workflow

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liangkiller** [comment]
![image](https://user-images.githubusercontent.com/10623650/212012719-64466f59-511f-480e-be14-ea70d53366d5.png)

**Comment by SbloodyS** [comment]
Could you provide more detail infomation about it?

**Comment by liangkiller** [comment]
I have 3 master nodes and 5 worker nodes， run 70 workflows.  this problem occurs when I want to stop the workflow, it state is READ STOP and never change to STOPPED.  I searchs master logs and finds:  Persist event into workflow execute thread error, cannot find the workflow instance from cache manager; the worker logs has no related jobs run.

**Comment by SbloodyS** [comment]
Have you manually modified the metadata of DS?

**Comment by liangkiller** [comment]
> Have you manually modified the metadata of DS?

no

**Comment by SbloodyS** [comment]
> [WARN] 2023-01-12 14:25:55.341 +0800 org.apache.dolphinscheduler.server.master.processor.queue.StateEventResponseService:[147] - [WorkflowInstance-94289][TaskInstance-0] - Persist event into workflow execute thread error, cannot find the workflow instance from cache manager

This error indicates that the workflow information cannot be found in the cache. Could you check if it can be found in the metadata's db?

**Comment by liangkiller** [comment]
> > [WARN] 2023-01-12 14:25:55.341 +0800 org.apache.dolphinscheduler.server.master.processor.queue.StateEventResponseService:[147] - [WorkflowInstance-94289][TaskInstance-0] - Persist event into workflow execute thread error, cannot find the workflow instance from cache manager
> 
> This error indicates that the workflow information cannot be found in the cache. Could you check if it can be found in the metadata's db?

thanks for response.   pls tell me  the table name ?

**Comment by SbloodyS** [comment]
> thanks for response. pls tell me the table name ?

Try to use `select * from t_ds_process_instance where id = {The workflow instance id you can find on the web ui}`
