### ISSUE TITLE
[Bug] [Master] Workflow instance start event will dead loop.

### ISSUE THREAD

**Issue by YOMO-Lee** [apache/dolphinscheduler#13390]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

最近公司再调研dolphinscheduler，我在使用的时候，经常遇到开始的任务一直不能结束，然后手动停止，就会在工作流实例上显示准备停止，但是一直停不下来。

### What you expected to happen

查询后台master的日志，日志在重复如下
![image](https://user-images.githubusercontent.com/46471288/212018998-e19f73ff-40d7-4de5-9fcf-5089506f6ff4.png)
并且日志体积在频繁增长，重复的日志造成磁盘使用率飙升
![image](https://user-images.githubusercontent.com/46471288/212018750-c002250d-078a-47ba-b257-14b131188da1.png)
这个我之前在使用3.1.1的时候遇到过，现在升级到3.1.3了，还是有这个问题

### How to reproduce

我需要去手动更新 t_ds_process_instance 表的状态字段到停止，
![image](https://user-images.githubusercontent.com/46471288/212019271-054a9b57-ccf0-41cf-8f9b-5242bf3be2e6.png)
然后再手动重启集群，才能解决这个问题.这个给我们上线dolphinscheduler带来了严重的挑战

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by YOMO-Lee** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by YOMO-Lee** [comment]
另外问下，dolphinscheduler 有社区微信群么，githup沟通有点不太方便

**Comment by ruanwenjun** [comment]
This is due to the workflow DAG is Incomplete, and the start event dead loop. Can you help to fix this @caishunfeng .

**Comment by ruanwenjun** [comment]
> 另外问下，dolphinscheduler 有社区微信群么，githup沟通有点不太方便

You can join the slack channel.
https://github.com/apache/dolphinscheduler#community

**Comment by YOMO-Lee** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by fuchanghai** [comment]
@caishunfeng @ruanwenjun #13045  can resolve this issue?

**Comment by caishunfeng** [comment]
It seems submit task exception from the log. The taskInstance.id is null when save db fail, so please check the real exception, which can often be seen in the log that the error is reported at the beginning.

**Comment by caishunfeng** [comment]
> @caishunfeng @ruanwenjun #13045 can resolve this issue?

Maybe the retry max submit time is no a good way, I tend to keep the logic simpler, to set the workflow instance fail when do submit fail.

**Comment by YOMO-Lee** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by YOMO-Lee** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by YOMO-Lee** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
