### ISSUE TITLE
The workflow is started, but there are no task instances

### ISSUE THREAD

**Issue by tfzq007** [apache/dolphinscheduler#13391]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The workflow is started, but there are no task instances

### What you expected to happen

Start the workflow to start the task instance

### How to reproduce

1

### Version

2.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Could you provide more detail? how to reproduce?
