### ISSUE TITLE
[Improvement][Resource Center] Remove permission management of resource in user management

### ISSUE THREAD

**Issue by Radeity** [apache/dolphinscheduler#13395]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We have refactored resource center https://github.com/apache/dolphinscheduler/pull/12076 in which remove the resource table. Also, change the resource permission authority from `user granularity` to `tenant granularity`. 

However, authorize resource in user management is `user granularity`, which should be removed, cuz it will not pass the user tenant check in `isUserTenantValid`. In a word, two things we can do:

- Support authorize resources in tenant management.
- Provide a script to migrate outdated resources to new resource path of admin's corresponding tenant.

<br>

Welcome to discuss about how to ensure a smooth transition.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
cc @SbloodyS @EricPyZhou

**Comment by SbloodyS** [comment]
> cc @SbloodyS @EricPyZhou

Good catch! 👍🏻

**Comment by Radeity** [comment]
> > cc @SbloodyS @EricPyZhou
> 
> Good catch! 👍🏻

Hi @SbloodyS, after further consideration, i think it's inappropriate to support authorize resources in tenant management, for following reasons:

- Resource binds with tenant by `fullName`, which means after creating resource, it belongs to a specific tenant.
- It doesn't exist the conception of `authorization` any more. One resource can only belong to one tenant.


Thus, i will make other **changes** when log in as ADMIN:

- First, remove resources authorization in user management.
- Second, support data migration in resource management, admin can choose the destination tenant, then it simply copies datas from `baseDir` of one tenant to another. 

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/45198818/213612902-084fdb8b-2508-49fd-a0d0-88c6f0fa9625.png">

- Third, admin can see all resources from deprecated resource table and resources belong to all tenants. **HOWEVER**,  `t_ds_relation_resources_user` and `t_ds_relation_udfs_user` will no longer in use, users have to migrate old resources to new tenant for using them. About this point, we may have to send a email to notify all users. 

<br>
Keep the old resources and remove old authority, it's a more smooth transition. If you agree with that, i'll work on this from now on.

**Comment by Radeity** [comment]
> 
> Hi @SbloodyS, after further consideration, i think it's inappropriate to support authorize resources in tenant management, for following reasons:
> 
> * Resource binds with tenant by `fullName`, which means after creating resource, it belongs to a specific tenant.
> * It doesn't exist the conception of `authorization` any more. One resource can only belong to one tenant.
> 
> Thus, i will make other **changes** when log in as ADMIN:
> 
> * First, remove resources authorization in user management.
> * Second, support data migration in resource management, admin can choose the destination tenant, then it simply copies datas from `baseDir` of one tenant to another.
> 
> <img alt="image" width="1432" src="https://user-images.githubusercontent.com/45198818/213612902-084fdb8b-2508-49fd-a0d0-88c6f0fa9625.png">
> 
> * Third, admin can see all resources from deprecated resource table and resources belong to all tenants. **HOWEVER**,  `t_ds_relation_resources_user` and `t_ds_relation_udfs_user` will no longer in use, users have to migrate old resources to new tenant for using them. About this point, we may have to send a email to notify all users.
> 
> 
> Keep the old resources and remove old authority, it's a more smooth transition. If you agree with that, i'll work on this from now on.

Hi, @SbloodyS , what do you think of this proposal?

**Comment by SbloodyS** [comment]
Sorry for late reply.

I'm totally agree with you. As for the third point, I think we can provide a one-time upgrade tool for users to migrate existing permissions in `t_ds_relation_resources_user` and `t_ds_relation_udfs_user` to the new tenant. So that greatly reduces the complexity of upgrading for users. WDYT? @Radeity

**Comment by Radeity** [comment]
> As for the third point, I think we can provide a one-time upgrade tool for users to migrate existing permissions in `t_ds_relation_resources_user` and `t_ds_relation_udfs_user` to the new tenant.

Hi, @SbloodyS, good suggestion! Like our schema update tool, one-time tool is more convenient, one thing i want to make sure, do we have to provide an interactive script in which user can assign the target tenant for each resource, or just move old resources to one tenant together? I prefer the latter way, WDYT.

**Comment by SbloodyS** [comment]
> Hi, @SbloodyS, good suggestion! Like our schema update tool, one-time tool is more convenient, one thing i want to make sure, do we have to provide an interactive script in which user can assign the target tenant for each resource, or just move old resources to one tenant together? I prefer the latter way, WDYT.

The latter way sounds good to me.

**Comment by Radeity** [comment]
> The latter way sounds good to me.

Thanks, i'll work on this. Also, after doing this, i'll create another pr to totally remove outdated codes in resource center, cuz when user upgrade to the new version and follow the upgrade doc to execute the script, deprecated logic will never be in used.

**Comment by Radeity** [comment]
H, @zhongjiajie, do we have to discuss more about migrate way? If use symlink or other mapper ways, we should consider tenant isolation, there's no problem with only read, but one tenant write resource, is should keep unchanged in other tenants' view. Maintain different resource version may help, cons are its complexity, and we have to design it carefully.

Any suggestion are welcome!
