### ISSUE TITLE
[Improvement][data-quality] Support dynamic parameters

### ISSUE THREAD

**Issue by xiaofan2022** [apache/dolphinscheduler#13393]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Tables, fields and other information support dynamic parameter Settings, otherwise it cannot be encapsulated. For example, I need to do a pre-task before quality management to determine whether to perform this task, I need to keep adding judgment

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
Can you give an example about dynamic parameters?

**Comment by xiaofan2022** [comment]
![image](https://user-images.githubusercontent.com/41982310/212589644-4c0128e3-0d0a-4c86-90cb-b32ab342ccbb.png)
This is the reason why I added a pre-check to my task is because I need to pre-check that the number of items is >0 otherwise the data-quality task gets an error. Now I think maybe we need to solve the problem that task result 0 error is better
