### ISSUE TITLE
[Feature] How to pass a token to my http API job?

### ISSUE THREAD

**Issue by gclsoft** [apache/dolphinscheduler#13414]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

How to pass a token to my http API job?
The token of my java application API needs a token, expired every ten minutes, how to pass it to the api? I was using xxljob, it has java SDK, so it's easy to just call the java service, is it available in Ds?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
The current HTTP node does not support it. You can try to use shell/java/python node to achieve it.

**Comment by gclsoft** [comment]
@SbloodyS the java node seems had removed from the latest version, I can't find it now. The shell node I have to generate the token by shell code, right? The python or java node is the same, using python or java code to create my token every time and give to my java application API, right?
Thanks very much

**Comment by SbloodyS** [comment]
> the java node seems had removed from the latest version, I can't find it now.

It will be released in the version 3.2.0.

> The shell node I have to generate the token by shell code, right? The python or java node is the same, using python or java code to create my token every time and give to my java application API, right?

Yes.

**Comment by gclsoft** [comment]
@SbloodyS when will version 3.2 release? Is the current dev git branch contains the java task?

**Comment by SbloodyS** [comment]
> when will version 3.2 release?

We may release version 3.2.0 in May.

> Is the current dev git branch contains the java task?

Yes.

**Comment by zhongjiajie** [comment]
Currently we release version 3.2.0, maybe you can try whether it work or not @gclsoft
