### ISSUE TITLE
[Bug] [ui] moving a task definition gets http code 405

### ISSUE THREAD

**Issue by ChPi** [apache/dolphinscheduler#13418]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

moving a task definition gets 405 code, the api is be removed #8190

### What you expected to happen

no error

### How to reproduce

move a task definition
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/20807051/212833480-f3be736d-1276-4ccb-b21a-271fb5f4fc9a.png">

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Fixed.
