### ISSUE TITLE
[Improvement] [Master] Empty dependency operation causes Master null pointer exception

### ISSUE THREAD

**Issue by lsy1072915121** [apache/dolphinscheduler#13413]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

创建一个空的依赖，运行后工作流一直处于"正在执行"状态

### What you expected to happen

空的依赖应该运行成功

### How to reproduce

<img width="725" alt="image" src="https://user-images.githubusercontent.com/20608690/212801513-f5b0279a-0655-478c-b528-b782c672b3ee.png">
创建一个依赖节点，但是不添加依赖，点击保存
<img width="917" alt="image" src="https://user-images.githubusercontent.com/20608690/212801657-64f3bb7b-cf8a-453c-9b5a-6fd97a85a878.png">
点击运行，依赖节点一直处于”正在执行“状态。

### Anything else

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/20608690/212801810-0be22c0c-9750-442d-a3a8-69676d198ea3.png">
MasterServer报空指针异常

### Version

2.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I don't think it's a bug. It needs to be discussed.

**Comment by lsy1072915121** [comment]
> I don't think it's a bug. It needs to be discussed.

However, the operation caused an exception, and the workflow was stuck and could not run. If you do not want users to create empty dependencies, you should verify them when submitting and saving; If empty dependencies are allowed, they should be given default values when saving.

**Comment by SbloodyS** [comment]
Ordinary users will not operate this way, and the probability is extremely low. I'll mark it as an improvement.

**Comment by brave-lee** [comment]
Hi @lsy1072915121 , I reviewed the pr, please take a look
