### ISSUE TITLE
[Bug] [dolphinscheduler-tools] Access denied for user 'dolphinscheduler'@'xxx' (using password: YES)

### ISSUE THREAD

**Issue by yangweifeng2017** [apache/dolphinscheduler#13424]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when run upgrade-schema.sh, happen Access denied for user 'dolphinscheduler'@'xxx' (using password: YES)。
but，if I use mysql client to connect  is no problem。I use myself java code use jdbc is still no problem。
![Uploading problem.png…]()

### What you expected to happen

Already described above.

### How to reproduce

Already described above.

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @yangweifeng2017 , your picture is down.

**Comment by yangweifeng2017** [comment]
<img width="956" alt="problem" src="https://user-images.githubusercontent.com/25970056/213127908-1a0bf550-8d34-4bd4-8563-d1bedc0ecadd.png">

**Comment by yangweifeng2017** [comment]
> Hi @yangweifeng2017 , your picture is down.

<img width="956" alt="problem" src="https://user-images.githubusercontent.com/25970056/213128076-3fe55730-a294-4317-97a5-171255c0e6b3.png">

**Comment by SbloodyS** [comment]
Try adding `useSSL=false` at the end of your jdbc connection url. @yangweifeng2017

**Comment by yangweifeng2017** [comment]
> Try adding `useSSL=false` at the end of your jdbc connection url. @yangweifeng2017

I find some Special characters (copy from website,but eye can't see)，Now，It is ok. 
thanks
