### ISSUE TITLE
3.1.0 version timing scheduling error

### ISSUE THREAD

**Issue by jizhanjia** [apache/dolphinscheduler#13431]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

ds 3.1.0
添加全局参数定时调度失败，手动执行可以成功， 报错：任务实例host为空

### What you expected to happen

版本3.0 
添加变量参数，手动执行可以成功，加入定时任务报错：任务实例host为空

### How to reproduce

随意新建工作流，拖拉shell组件，脚本写echo "111",保存工作流添加全局参数，上线，设置调度时间，报错：任务实例host为空

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
This is caused by the parameter replace error? could your please provide more log?
