### ISSUE TITLE
[Bug] [Docker] Docker compose up doesn't work

### ISSUE THREAD

**Issue by vladaman** [apache/dolphinscheduler#13443]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Running `docker compose up` leads to an error `no service selected`

### What you expected to happen

Docker should start

### How to reproduce

Steps to reproduce:

1. `wget https://raw.githubusercontent.com/apache/dolphinscheduler/dev/deploy/docker/docker-compose.yml`
2. `wget https://raw.githubusercontent.com/apache/dolphinscheduler/dev/deploy/docker/.env`
3. docker compose up

### Anything else

- Docker version 20.10.12, build 20.10.12-0ubuntu4
- Docker Compose version v2.15.1

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by grzegorz-aniol** [comment]
@vladaman You have profile defined for every service in `docker-compose.yml`. You should start it with `--profile` parameter, e.g. `docker-compose --profile all up -d`.
