### ISSUE TITLE
LDAP configuration with dolphin scheduler on K8s cluster

### ISSUE THREAD

**Issue by suraj7212** [apache/dolphinscheduler#13454]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I don't found any document for configuring ldap with dolphin scheduler.
Please provide it or let us know from whare we can have it?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Hi @surajlavhale , you can see our configuration in https://dolphinscheduler.apache.org/en-us/docs/3.1.3/architecture/configuration, the keyword is `ldap`
And detail tutorial we still do not have, and @liqingwang do you have time to and some detail docs about how to config and use ldap?

<img width="890" alt="image" src="https://user-images.githubusercontent.com/15820530/215637332-5de528f6-5028-419a-a8ec-34f1aa079601.png">

**Comment by qingwli** [comment]
Sure, I will add some doc about LDAP when I have time.

**Comment by zhongjiajie** [comment]
Hi @surajlavhale in #13507 we just recover the missing doc, but we should ask whether it work in released version

**Comment by suraj7212** [comment]
Thanks for providing this information.
Since we are using dolphin scheduler with k8s, so could you please let us know how we can integrate LDAP with dolphin on k8s cluster?

**Comment by Elijah3927** [comment]
> Thanks for providing this information. Since we are using dolphin scheduler with k8s, so could you please let us know how we can integrate LDAP with dolphin on k8s cluster?

Hi @suraj7212 can you integrate LDAP with dolphin on k8s now ?

**Comment by Elijah3927** [comment]
Hi @suraj7212 can you integrate LDAP with dolphin on k8s now ?

**Comment by qingwli** [comment]
Hi @suraj7212 , you can have a try, and any question you can let me know

**Comment by Elijah3927** [comment]
Hi @qingwli,  i have the same question, how to config ladp when doploy ds on k8s?

**Comment by qingwli** [comment]
@Elijah3927 Hi you can see this [pr](https://github.com/apache/dolphinscheduler/pull/13507/files) and will be released in version 3.2.0

**Comment by Elijah3927** [comment]
@qingwli  ok, thanks
