### ISSUE TITLE
The dolphin running task deployed by docker reports an error

### ISSUE THREAD

**Issue by luoluo2001108** [apache/dolphinscheduler#13453]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1、docker-compose方式，按照文档部署 dolphin
2、修改.env配置文件，
     增加两个环境变量：
   FLINK_HOME=/mnt/flink-1.13.6
   SEATUNNEL_HOME=/mnt/seatunnel
3 、修改docker-compose文件，将服务器上着两个路径映射到docker内部
4、重启后运行任务，查看日志报错，进入容器内部发现java命令是能运行的
${SEATUNNEL_HOME}/bin/start-seatunnel-flink.sh --config /tmp/dolphinscheduler/exec/process/root/8378201744128/8380143812960_1/2/49/seatunnel_2_49.conf --run-mode run
[INFO] 2023-01-29 08:23:12.841 +0000 - task run command: sudo -u root -E bash /tmp/dolphinscheduler/exec/process/root/8378201744128/8380143812960_1/2/49/2_49.command
[INFO] 2023-01-29 08:23:12.844 +0000 - process start, process id is: 85
[INFO] 2023-01-29 08:23:12.859 +0000 - process has exited. execute path:/tmp/dolphinscheduler/exec/process/root/8378201744128/8380143812960_1/2/49, processId:85 ,exitStatusCode:127 ,processWaitForStatus:true ,processExitValue:127
[INFO] 2023-01-29 08:23:12.871 +0000 - Send task execute result to master, the current task status: TaskExecutionStatus{code=6, desc='failure'}
[INFO] 2023-01-29 08:23:12.871 +0000 - Remove the current task execute context from worker cache
[INFO] 2023-01-29 08:23:12.871 +0000 - The current execute mode isn't develop mode, will clear the task execute file: /tmp/dolphinscheduler/exec/process/root/8378201744128/8380143812960_1/2/49
[INFO] 2023-01-29 08:23:12.877 +0000 - Success clear the task execute file: /tmp/dolphinscheduler/exec/process/root/8378201744128/8380143812960_1/2/49
_[INFO] 2023-01-29 08:23:13.844 +0000 -  -> /mnt/seatunnel/bin/start-seatunnel-flink.sh: line 63: java: command not found_
	
[INFO] 2023-01-29 08:23:13.846 +0000 - FINALIZE_SESSION

### What you expected to happen

运行任务成功

### How to reproduce

按照上述步骤必现

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
which SeaTunnel version do you used?

**Comment by luoluo2001108** [comment]
> which SeaTunnel version do you used?

2.3

**Comment by luoluo2001108** [comment]
2.3



---Original---
From: "Jay ***@***.***&gt;
Date: Tue, Jan 31, 2023 09:40 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/dolphinscheduler] The dolphin running task deployed bydocker reports an error (Issue #13453)




 
which SeaTunnel version do you used?

**Comment by luoluo2001108** [comment]
resolved

**Comment by k8slight** [comment]
how to reslove

**Comment by Light-Towers** [comment]
how to reslove
