### ISSUE TITLE
[Feature][api-server] process instance cannot be renamed

### ISSUE THREAD

**Issue by xiaofan2022** [apache/dolphinscheduler#13463]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Let's say I want to use a workflow as a template and then copy it and find that the name of the new workflow cannot be changed

### Use case

![Snipaste_2023-01-31_11-50-02](https://user-images.githubusercontent.com/41982310/215658530-7d49598d-6dae-427c-b977-2ced0c5ceb56.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi, @xiaofan2022, you can edit and then save with the new name.

**Comment by xiaofan2022** [comment]
👍
