### ISSUE TITLE
[Improvement][Style] Use lombok @Log annotation to generate loggers

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#13491]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* DS uses several `lombok` annotations such as `@data` to make code look neat. We could also use `lombok` `@Log`, `@Slf4j` etc. to generate logger.
* https://projectlombok.org/features/log

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by seedscoder** [comment]
If no one else does, I want to deal with this issue @EricGao888

**Comment by EricGao888** [comment]
> If no one else does, I want to deal with this issue @EricGao888

@seedscoder Thanks for reaching out. I've assigned this task to you. Enjoy coding : )
