### ISSUE TITLE
[Improvement][task node] task node includes shell、proceduce、sql、spark、datax、sqoop、flink_stream and so on，those can not select resource file by seraching resources tree

### ISSUE THREAD

**Issue by zhutong6688** [apache/dolphinscheduler#13498]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

**Current Problems**
 
![图片](https://user-images.githubusercontent.com/28818582/216946004-9348b211-4493-4fcf-be18-2692bbbaa75f.png)
There are thousands of resource files and many subdirectories, there are many files in the subdirectory also. When using nodes, we cannot quickly select the resource files we upload through search, and it is more difficult to select the files in the subdirectory. It wastes a lot of time every time you choose.

**My Expectations For This Feature**

![图片](https://user-images.githubusercontent.com/28818582/216946627-70614cb1-6a05-45a7-a368-3be17200d4be.png)
My goal is to filter out resource files and resource files in the secondary directory through search.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good job, please make the picture in the English environment.

**Comment by zhutong6688** [comment]
@davidzollo Hello, I have re-uploaded the screenshots of the areas to be improved, and I have also submitted the code. Please take a review。

**Comment by zhutong6688** [comment]
@davidzollo I accidentally clicked the “unsigned me” link, I was unintentional, now it's like this，
![图片](https://user-images.githubusercontent.com/28818582/217731655-aa6142c4-0a38-4eea-8b76-c4e4d2c2b9e2.png)
Can you reassign me as the responsible person? Thanks very much. My improvement code is submitted.
