### ISSUE TITLE
[Bug] [API]V3.1.3 of workflow instance list page, gantt chart page jump failed 

### ISSUE THREAD

**Issue by fw19940314** [apache/dolphinscheduler#13499]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

gantt page console error.
![image](https://user-images.githubusercontent.com/21071875/216274006-8dfe8d75-5e40-4685-87ff-fbaff33d117c.png)
![image](https://user-images.githubusercontent.com/21071875/216274348-3f2681f0-2712-4ac3-8a6e-8825aa3ea459.png)

Backend response
![image](https://user-images.githubusercontent.com/21071875/216274619-db9061a6-b48f-4d0f-b788-df2cad4f9e46.png)

read the ui code, The reason for this bug is task status the type returned by the task status should be a specified enumeration string, not an enumeration object 

### What you expected to happen

read the ui code, The reason for this bug is task status the type returned by the task status should be a specified enumeration string, not an enumeration object .

API module bug fix detail:
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/21071875/216275892-6f3158b8-791e-4875-87e9-74b24c49d2d6.png">

### How to reproduce

workflow instance list page, gantt chart page jump failed .

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LyricsYo** [comment]
Is there any one anyone solve this problem? @SbloodyS @davidzollo @songjianet

**Comment by fw19940314** [comment]
> Is there any one anyone solve this problem? @SbloodyS @davidzollo @songjianet

other version has commited，but no merge.
