### ISSUE TITLE
[Bug] [Worker] When the task request has not set the current execution status, an error will cause an NPE exception

### ISSUE THREAD

**Issue by wcmolin** [apache/dolphinscheduler#13496]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When the task request has not set the current execution status, an error will cause an NPE exception.
This causes the task to run all the time

### What you expected to happen

The task is to be stopped regardless of success or failure

### How to reproduce

Submit a long-time task, stop the worker, delete or modify the tenant name, restart the worker, and an NPE exception will occur during fault tolerance

### Version

2.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Currently the task instance and workflow instance uses tenant name to bind. Maybe we should use tenan's id instead of tenant's name to avoid this. cc @JinyLeeChina @ruanwenjun @caishunfeng

**Comment by brave-lee** [comment]
Hi @SbloodyS , I have confirmed that this is due to the bug caused by # 13244 modification, and pr has been submitted. Please verify.
