### ISSUE TITLE
[Bug] [datax task] datax task error  on version 3.1.0

### ISSUE THREAD

**Issue by dxiyang** [apache/dolphinscheduler#13492]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/33177848/216209929-ea006fb2-bec3-46bf-8731-e2fb48d3631e.png)
As shown in the figure above, an error occurred while calling a datax task with the parameter $[yyyy-MM-dd HH:mm:ss]

![image](https://user-images.githubusercontent.com/33177848/216210868-04142bdf-4661-4efe-94d5-7a376843e8d4.png)

![image](https://user-images.githubusercontent.com/33177848/216211066-bd3ffaa2-e2d9-48be-883a-05db38523ccf.png)

Failed to call with parameter   $[yyyy-MM-dd HH:MM:ss].

Successful call with parameter $[yyyy-MM-ddHH:MM:ss].

The guess is that the argument is passed to the datax without single quotes.

### What you expected to happen

It can be called normally with $[yyyy-MM-dd HH:mm:ss]  

### How to reproduce

The guess is that the argument is passed to the datax without single quotes.

##### Operating steps:
1. Run the command. The parameter contains Spaces. Without a single quotes . /usr/bin/python /home/tools/datax/bin/datax.py -p "-Dlast=2021-1-1 00:00:00" /home/tools/datax/bin/stream2stream.json
Error!!
![image](https://user-images.githubusercontent.com/33177848/216210473-006edcc7-c5ec-4584-981b-84e8801d4443.png)

2. Run the command without Spaces. Without a single quotes.  /usr/bin/python /home/tools/datax/bin/datax.py -p "-Dlast=2021-1-100:00:00" /home/tools/datax/bin/stream2stream.json
Success!!
![image](https://user-images.githubusercontent.com/33177848/216210038-1c9d0662-16c5-47e3-87ce-c64c240d3e33.png)

3. Run the command. The parameter contains Spaces. With single quotes . /usr/bin/python /home/tools/datax/bin/datax.py -p "-Dlast='2021-1-1 00:00:00'" /home/tools/datax/bin/stream2stream.json
Success ！！！！
![image](https://user-images.githubusercontent.com/33177848/216210037-2f8855fa-0b3e-445e-93d5-918fe8f1f4d2.png)
### Conclusion
Compare 1 and 3 to check whether $[yyyy-MM-dd HH:mm:ss] is not supported or there is an error in my operation.
I am currently using dolphinscheduler version 3.1.0

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
@SbloodyS    if nobody interested  this issue, i  want to fix it

**Comment by SbloodyS** [comment]
> @SbloodyS if nobody interested this issue, i want to fix it

Sure.

**Comment by fuchanghai** [comment]
@SbloodyS  plz close this issue
