### ISSUE TITLE
[Improvement][Module Name] Display the current project name on the project overview page and workflow page

### ISSUE THREAD

**Issue by Length-Width-Height** [apache/dolphinscheduler#13504]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://user-images.githubusercontent.com/117889161/216549438-448e9d02-ad13-4c21-9750-2817ebfee848.png)
![image](https://user-images.githubusercontent.com/117889161/216549579-7a6c0d57-883f-4d78-8c7e-a2da781191f6.png)
When using Dolphin Scheduler, workflow is mainly used. However, when users manage multiple projects at the same time, they cannot see which project they are currently under on the workflow page.  Must click project management again, and then enter the corresponding project.

I hope that developers can display the current project name on the project overview page and workflow page.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
@Amy0104 @SbloodyS  plz close this issue
