### ISSUE TITLE
[Discussion][User Support] Make a chatbot to answer users' newbie-questions 

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#13503]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Every day the community receives tons of newbie questions from users and actually they could find the answers easily by reading the official docs. Furthermore, DS assigns unique exception / error codes to most of the error / exceptions. 
* We could build a trivial chatbot to answer those newbie questions and put the chatbot in wechat groups / slack channel, etc. or make a wechat mini program for users to interact with the chatbot.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
+1

**Comment by jieguangzhou** [comment]
Hi, @EricGao888 , I think I can help if needed. I've done Chatbot-related work for a long time

**Comment by EricGao888** [comment]
> Hi, @EricGao888 , I think I can help if needed. I've done Chatbot-related work for a long time

Cool, we could have some discussions sometime next week, WDYT?

**Comment by jieguangzhou** [comment]
Ok

**Comment by EricGao888** [comment]
@jieguangzhou Hello, may I ask whether there is any progress for this issue?
