### ISSUE TITLE
[Feature][Module Name] Multi-network card binding problem

### ISSUE THREAD

**Issue by JohnYuu** [apache/dolphinscheduler#13500]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

There are multiple network cards in the actual production environment. Due to security and permissions issues, not all network cards are connected. Therefore, we can access the network cards specified by the configuration settings

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You can set `dolphin.scheduler.network.interface.preferred` in `common.properties`.
