### ISSUE TITLE
[Bug] [DAO] error pgsql sql syntax `ON DUPLICATE KEY` causes the process to execute failed

### ISSUE THREAD

**Issue by xxjingcd** [apache/dolphinscheduler#13517]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When DS's DB is PostgreSQL, I execute the process, it executes fail and throws the exception as follows:

![企业微信截图_16756660922619](https://user-images.githubusercontent.com/68894048/216902234-121cb442-325a-4e5a-a10c-4d8b7d45d145.png)

### What you expected to happen

DS executes the process successfully without any errors.

### How to reproduce

- DS uses PostgreSQL DB;
- execute process;

### Anything else

-  `ON DUPLICATE KEY`  is MySQL syntax，and in PostgreSQL is `ON CONFLICT`. **Similar incompatible syntax should be avoided**.
- I am very confused about this SQL that cause the issue -  **It seems to cause another bug** because it will update the recorder as long as the `updateTime` is same; In my view, when two recorders insert at the same time, there will only be one recorder insert. Is this reasonable?

```sql
INSERT INTO t_ds_trigger_relation (trigger_code, trigger_type, job_id, create_time, update_time) VALUES(
            #{triggerRelation.triggerCode},#{triggerRelation.triggerType},#{triggerRelation.jobId},#{triggerRelation.createTime},#{triggerRelation.updateTime})
        ON DUPLICATE KEY UPDATE update_time = #{triggerRelation.updateTime};
```

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xxjingcd** [comment]
This Issue requires the participation of @qianli2022

**Comment by eupaphios** [comment]
[](https://github.com/apache/dolphinscheduler/pull/13874)

**Comment by epuaphios** [comment]
https://github.com/apache/dolphinscheduler/pull/13874
