### ISSUE TITLE
[Feature][Task] Implement Task Template Feature

### ISSUE THREAD

**Issue by wendongdi** [apache/dolphinscheduler#13513]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I'd like to propose the implementation of a Task Template feature,it would allow users to save an existing task node as a template and reuse it when creating new tasks.

The Task Template would include all the configuration and execution parameters of a task node, except for the scheduling parameters and custom variables. This feature would enable users to quickly create tasks based on a pre-defined template, abstracting the logic of the desired business code.

I believe that the implementation of this feature would enhance the user experience and increase the efficiency of task creation in Apache DolphinScheduler.

Thanks for considering this proposal.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi, @wendongdi , any updates?

**Comment by ruanwenjun** [comment]
I don't think this is a needed feature, right now if you use UI to create workflow, when you drag a task, there is already a task `template`, you only need to inject parameters in the form.
