### ISSUE TITLE
[Feature][Data Quality] Data Quality Job Support Multiple Rules 

### ISSUE THREAD

**Issue by qingwli** [apache/dolphinscheduler#13524]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

For now, data quality only supports a single rule for one job, and for our real scenes to be used, one job needs to check a lot of fields. So we want to support multiple rules for one data quality job.

### Use case

We will change the data quality task definition page to a table and then can add a lot of rules and crud, below are the demo design:
<img width="1727" alt="定义任务" src="https://user-images.githubusercontent.com/20885366/217137636-91757449-8fd3-45c8-86fd-ff343fe1479b.png">
![新建规则](https://user-images.githubusercontent.com/20885366/217137647-1dfa1ab7-c75c-4bea-b9ed-78bfc8bac449.jpeg)
![组合页面](https://user-images.githubusercontent.com/20885366/217137826-94f62fa1-15c0-48a2-9643-d87c2671eb3a.png)

And we will change the data quality result page to support a result with multiple rules, below is the demo design:

<img width="1727" alt="任务结果" src="https://user-images.githubusercontent.com/20885366/217137869-3943ac25-379c-46f7-80ec-2ea8302363e4.png">
<img width="1727" alt="任务明细" src="https://user-images.githubusercontent.com/20885366/217137873-9ba5d1f7-6978-4801-890b-cac742ef5cf8.png">

### Related issues

Enhance https://github.com/apache/dolphinscheduler/issues/4283

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Good idea, it is a sweet feature and I like it. looking forward your contribution

**Comment by liujinhui1994** [comment]
@liqingwang hi，where is this going？

**Comment by liujinhui1994** [comment]
@liqingwang Is there a PR for this now?

**Comment by qingwli** [comment]
Hi @liujinhui1994 , Sorry for the later reply,  It's still working, some work things have higher priority, will take 1-2 months
