### ISSUE TITLE
datax task failed while sql task is fine

### ISSUE THREAD

**Issue by amy108** [apache/dolphinscheduler#13521]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

sql tasks are fine, but datax task failed. msg:
[taskAppId=TASK-4-20151-182956]:[138] - -> Sorry, user iot is not allowed to execute '/bin/sh /opt/applications/iot/data/dolphinscheduler/exec/process/1/4/20151/182956/4_20151_182956.command' as iot on XXX.

already set datax path user to iot

### What you expected to happen

1

### How to reproduce

1

### Version

2.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
Can shell nodes execute ?
