### ISSUE TITLE
workflow is always running: state in t_ds_task_instance is always 0 and the task instance waits to be executed for a long time , it seems to be not over time.

### ISSUE THREAD

**Issue by epitomizelu** [apache/dolphinscheduler#13525]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

it looks same as the bug 7441, but i think it's anther problem.

the version is 2.0.6, and the cluster have 2 masters, 4 workers, and it's random but with a large probability and always occurs on the same master.  

### What you expected to happen

if i remove the master, the problem will not occurs. and it's random

### How to reproduce

a complex process with subprocess, then start it

### Version

2.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
Have you checked the master load ?
