### ISSUE TITLE
[Bug] [alert-server] When configuring an alarm instance, no parameter verification is performed.

### ISSUE THREAD

**Issue by Zzihh** [apache/dolphinscheduler#13532]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When configuring an alarm instance, no parameter verification is performed.exception occurred when sending an alarm message.
<img width="640" alt="image" src="https://user-images.githubusercontent.com/33439363/217459200-4622f028-f4f0-45d3-9bf9-f0901f741769.png">
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/33439363/217459309-6bcc966d-f74a-43a1-b1b8-5bc52dfb1ebb.png">
<img width="942" alt="image" src="https://user-images.githubusercontent.com/33439363/217458553-4c19e87d-c686-4683-acbb-c9ea3ba099f6.png">

### What you expected to happen

Nothing

### How to reproduce

Nothing

### Version

3.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
will fix in 3.2.0 instead of 3.0.x
