### ISSUE TITLE
关于实时计算任务的建议 Recommendations for real-time computing tasks

### ISSUE THREAD

**Issue by wuyang0809** [apache/dolphinscheduler#1353]
**Is your feature request related to a problem? Please describe.**

我们现在大部分的任务使用的是Flink实时计算，在一个工作流中，任务间没有顺序依赖

Most of our current tasks use Flink real-time calculations. In a workflow, there is no order dependency between tasks.

![image](https://user-images.githubusercontent.com/32353326/69849552-06778500-12b8-11ea-98c8-260537a52a0e.png)

像图中展示的这样，在当前系统中，箭头代表任务执行的先后顺序，由于我们是实时计算，任务间是并行运行的关系，箭头仅仅代表数据流转方向，并不代表任务执行顺序。所以我们现在，在执行工作流时，会把箭头去除，让所有任务并行执行。

As shown in the figure, in the current system, the arrows represent the order of task execution. Since we are calculating in real time and the tasks are running in parallel, the arrows only represent the direction of data flow and do not represent the task execution order.
So we now remove the arrow when executing the workflow and let all tasks execute in parallel.

但是，当前系统的异常通知，如果设置为失败继续，那么某一个任务的失败并不会发送通知。如果设置为失败停止，那么某一个任务的失败会导致整个工作流实例的停止。这并不是我们想要的。

However, if the abnormal notification of the current system is set to continue to fail, a notification of the failure of a task will not be sent.
If set to fail stop, the failure of one task will cause the entire workflow instance to stop.
This is not what we want.

**Describe the solution you'd like**
1、我们期望可以管理的更加细致。某一个任务的停止，异常，恢复，通知都是独立的。而不是会影响整个工作流。

We want to be able to manage it in more detail.
The stop, exception, resume and notification of tasks are independent.
Rather than affecting the entire workflow.

2、希望可以增加数据流转方向的连线。连线只是为了标识数据流转方向，而不是任务执行顺序

It is hoped that the connection of the data flow direction can be increased.
The wiring is only to identify the direction of data flow, not the task execution order

**Describe alternatives you've considered**

目前我们只能把每一个任务放在单独的工作流中，也就是一个工作流实例中只有一个任务

**Additional context**

**Comment by xingchun-chen** [comment]
像图中展示的这样，在当前系统中，箭头代表任务执行的先后顺序，缺一张任务连接图Missing a task connection diagram

**Comment by lamber-ken** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> 我们现在大部分的任务使用的是Flink实时计算，在一个工作流中，任务间没有顺序依赖
> 
> Most of our current tasks use Flink real-time calculations. In a workflow, there is no order dependency between tasks.
> 
> ![image](https://user-images.githubusercontent.com/32353326/69849552-06778500-12b8-11ea-98c8-260537a52a0e.png)
> 
> 像图中展示的这样，在当前系统中，箭头代表任务执行的先后顺序，由于我们是实时计算，任务间是并行运行的关系，箭头仅仅代表数据流转方向，并不代表任务执行顺序。所以我们现在，在执行工作流时，会把箭头去除，让所有任务并行执行。
> 
> As shown in the figure, in the current system, the arrows represent the order of task execution. Since we are calculating in real time and the tasks are running in parallel, the arrows only represent the direction of data flow and do not represent the task execution order.
> So we now remove the arrow when executing the workflow and let all tasks execute in parallel.
> 
> 但是，当前系统的异常通知，如果设置为失败继续，那么某一个任务的失败并不会发送通知。如果设置为失败停止，那么某一个任务的失败会导致整个工作流实例的停止。这并不是我们想要的。
> 
> However, if the abnormal notification of the current system is set to continue to fail, a notification of the failure of a task will not be sent.
> If set to fail stop, the failure of one task will cause the entire workflow instance to stop.
> This is not what we want.
> 
> **Describe the solution you'd like**
> 1、我们期望可以管理的更加细致。某一个任务的停止，异常，恢复，通知都是独立的。而不是会影响整个工作流。
> 
> We want to be able to manage it in more detail.
> The stop, exception, resume and notification of tasks are independent.
> Rather than affecting the entire workflow.
> 
> 2、希望可以增加数据流转方向的连线。连线只是为了标识数据流转方向，而不是任务执行顺序
> 
> It is hoped that the connection of the data flow direction can be increased.
> The wiring is only to identify the direction of data flow, not the task execution order
> 
> **Describe alternatives you've considered**
> 
> 目前我们只能把每一个任务放在单独的工作流中，也就是一个工作流实例中只有一个任务
> 
> **Additional context**

个人拙见:
Flink实时计算任务，我们已经部署运行上千任务，任务之间不应该存在依赖关系，因为流计算是7*24*365天运行的。不存在所谓的上下游，真实意义的上下游只是MQ中的数据而已。

**Comment by Right-ydd** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > 我们现在大部分的任务使用的是Flink实时计算，在一个工作流中，任务间没有顺序依赖
> > Most of our current tasks use Flink real-time calculations. In a workflow, there is no order dependency between tasks.
> > ![image](https://user-images.githubusercontent.com/32353326/69849552-06778500-12b8-11ea-98c8-260537a52a0e.png)
> > 像图中展示的这样，在当前系统中，箭头代表任务执行的先后顺序，由于我们是实时计算，任务间是并行运行的关系，箭头仅仅代表数据流转方向，并不代表任务执行顺序。所以我们现在，在执行工作流时，会把箭头去除，让所有任务并行执行。
> > As shown in the figure, in the current system, the arrows represent the order of task execution. Since we are calculating in real time and the tasks are running in parallel, the arrows only represent the direction of data flow and do not represent the task execution order.
> > So we now remove the arrow when executing the workflow and let all tasks execute in parallel.
> > 但是，当前系统的异常通知，如果设置为失败继续，那么某一个任务的失败并不会发送通知。如果设置为失败停止，那么某一个任务的失败会导致整个工作流实例的停止。这并不是我们想要的。
> > However, if the abnormal notification of the current system is set to continue to fail, a notification of the failure of a task will not be sent.
> > If set to fail stop, the failure of one task will cause the entire workflow instance to stop.
> > This is not what we want.
> > **Describe the solution you'd like**
> > 1、我们期望可以管理的更加细致。某一个任务的停止，异常，恢复，通知都是独立的。而不是会影响整个工作流。
> > We want to be able to manage it in more detail.
> > The stop, exception, resume and notification of tasks are independent.
> > Rather than affecting the entire workflow.
> > 2、希望可以增加数据流转方向的连线。连线只是为了标识数据流转方向，而不是任务执行顺序
> > It is hoped that the connection of the data flow direction can be increased.
> > The wiring is only to identify the direction of data flow, not the task execution order
> > **Describe alternatives you've considered**
> > 目前我们只能把每一个任务放在单独的工作流中，也就是一个工作流实例中只有一个任务
> > **Additional context**
> 
> 个人拙见:
> Flink实时计算任务，我们已经部署运行线上任务，任务之间不应该存在依赖关系，因为流计算是7_24_365天运行的。不存在所谓的上下游，真实意义的上下游只是MQ中的数据而已。

是的 我同意你说的 上下游只是MQ中的数据 所以希望可以有一个数据流转方向的连接线 这样可以清晰的看到数据的走向。可以加VX 聊一下吗？ 可以的话请加我 17602145065

**Comment by dailidong** [comment]
good idea，we will strengthen the support for real-time computing task later

**Comment by Ylisen** [comment]
同意+1.
I need tasks to have no dependent order, but the execution is serial
