### ISSUE TITLE
[Doc][Module Name] Documentation bug or improvement

### ISSUE THREAD

**Issue by zhangzijun** [apache/dolphinscheduler#13542]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://user-images.githubusercontent.com/8895818/218033361-5cf1617c-5439-4558-8203-4f5f6ab91c25.png)看文档上的解释，这个并行和串行等待好像没什么区别啊？

### Documentation Links

https://dolphinscheduler.apache.org/zh-cn/docs/3.1.3/guide/project/workflow-definition

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jackfanwan** [comment]
please assign to me
