### ISSUE TITLE
[Improvement][Resources Project] The details page does not return to the previous list page after returning to the list page

### ISSUE THREAD

**Issue by zhutong6688** [apache/dolphinscheduler#13558]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description
version 3.x
**Current Problems**
![图片](https://user-images.githubusercontent.com/28818582/218413521-99baed57-cccc-45c3-ac89-da1a1370a95b.png)
![图片](https://user-images.githubusercontent.com/28818582/218413558-8b4dca75-65e8-42ff-a986-cef49195d122.png)
![图片](https://user-images.githubusercontent.com/28818582/218413584-b71a9cc6-65c5-4701-9c82-0d8463667fe7.png)
When you come to the task or workflow list interface(Figure 1), click the task edit button on the specified page to enter the task details page(Figure 2). When you return, you will jump to the first page instead of the page where the original task is located(Figure 3). Very unfriendly to the user's experience.

![图片](https://user-images.githubusercontent.com/28818582/218433850-153250c0-ccb0-48c0-9ffd-b2791dcc69a9.png)
![图片](https://user-images.githubusercontent.com/28818582/218433879-4cce44dd-3929-483d-834e-105f350146e6.png)
![图片](https://user-images.githubusercontent.com/28818582/218433902-13e59546-e54b-41ff-be4d-77e0ed3f080a.png)
When you come to the list interface of the resource file, click the edit button of the resource file on the specified page to enter the details page of the resource file. When you return or save, you will jump to the first page instead of the page where the original resource file is located. It is also very unfriendly to the user's experience.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhutong6688** [comment]
Our company has been using dolphinscheduler. After such a long time of use, we found that if we optimize the resource paging part like me, the development efficiency will increase by an order of magnitude, because it saves a lot of repeated searches and page jumps, especially when modifying the same type of resource files in large quantities.

**Comment by qinping416** [comment]
this improment is great for the user experience and greatly improves development efficiency

**Comment by pinkfloyds** [comment]
Yes, if it can be achieved, it would be a significant improvement in the experience

**Comment by zhutong6688** [comment]
@pinkfloyds my submittd code is here https://github.com/apache/dolphinscheduler/pull/13731

**Comment by zhutong6688** [comment]
this problem will reopen

**Comment by zhutong6688** [comment]
I cannot reopen this issue, I already submit a new issue similarly like this issue
