### ISSUE TITLE
[Bug] [DataQuality]DataQuality use clickhouse db,runtime error ClassNotFoundException: com.clickhouse.jdbc.ClickHouseDriver

### ISSUE THREAD

**Issue by superbaicai** [apache/dolphinscheduler#13553]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

3.1.3版本中使用数据质量组件中引用了clickhouse 的数据源，执行时提示：
 java.lang.ClassNotFoundException: com.clickhouse.jdbc.ClickHouseDriver 

### What you expected to happen

报错信息：
https://files.slack.com/files-pri/T01L3LB96V7-F04NAJJ26J1/image.png

### How to reproduce

部署海豚3.1.3单节点服务后，配置clickhouse ，使用local 和 cluster 模式，无其他特殊参数，执行后报错
[https://files.slack.com/files-pri/T01L3LB96V7-F04NAJJ26J1/image.png](url)

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwhj** [comment]
把 Clickhouse 驱动放到 spark 的jars目录下面
或者 执行参数 添加 --jar Clickhouse.jar
