### ISSUE TITLE
[Improvement][RPC] Rename RPC command to request

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#13559]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

<img width="564" alt="image" src="https://user-images.githubusercontent.com/22415594/218622026-02884f5a-efff-4541-9e6e-81b4c3b579c5.png">

The class name XXcommand will be confused with the command stored in the database.

It's better rename to XXRequest

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by alextinng** [comment]
I'm glad to do this task!

**Comment by alextinng** [comment]
I thinks it's better rename package name from org.apache.dolphinscheduler.remote.command to org.apache.dolphinscheduler.remote.request too, otherwise, class name xxxRequest and package name command is still confused!
@ruanwenjun
