### ISSUE TITLE
[Bug] [ 3.1.3version-dolphinscheduler-api] Dockerfile baseimage cannot exec apt-get update

### ISSUE THREAD

**Issue by guoyy** [apache/dolphinscheduler#13567]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/11882864/218926341-0992263e-96b4-4449-b3ee-da5143edc338.png)
The base image cannot exec apt-get update，apt-key add.This is a dead loop!!
![image](https://user-images.githubusercontent.com/11882864/218926736-d2888539-1fa4-4e8c-82f6-359b1fc6bb7f.png)

### What you expected to happen

replace the correct base image.

### How to reproduce

replace the correct base image.

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qindongliang** [comment]
1，Modify /etc/apt/sources.list file
2，change proxy source
3，Make sure the docker environment can connect to the external network

Reference: https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/

**Comment by guoyy** [comment]
i replaced sources.list, same problem ocuured.
