### ISSUE TITLE
[Improvement][Resource Center] Code clean up and replace the usage of Resource

### ISSUE THREAD

**Issue by Radeity** [apache/dolphinscheduler#13570]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

After providing a one-time migration script in https://github.com/apache/dolphinscheduler/pull/13512. We don't have to consider about compatibility for the new resource center, such as:
https://github.com/apache/dolphinscheduler/blob/6a0f48e5335207a2545fb0a1a05080e24c96833c/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java#L958-L961

In addition, i'll check the usage of deprecated `Resource` in the whole project and replace them, also find out if there are some missing work in previous refactor.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
reopen

**Comment by zhongjiajie** [comment]
reopen it
