### ISSUE TITLE
[Bug] [dolphinscheduler-master] Master can't release the tast to worker

### ISSUE THREAD

**Issue by ziqiang-wang** [apache/dolphinscheduler#13583]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I created a new workflow definition with a single shell task and a single file resource. There is no problem when the new creation is completed and brought online and then executed manually.

I then offline the workflow definition, deleted the file resource, and re-uploaded the file resource with the same name. At this point, I enter the workflow definition, before entering the specific task definition, again

When I selected the file resource and finally brought it back online and ran it manually again, I found that only the workflow instance was being generated, and the instance display was running, but the task instance was not being generated.

By checking the logs of two master nodes in real time, I found many logs of NullPointerException, as follows

```
[ERROR] 2023-02-19 11:30:50.640 +0000 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[1005] - [WorkflowInstance-65012][TaskInstance-0] - Submit standby task 太原运营订单实时看板-0点初始化 error, taskCode: 8601895756928
java.lang.NullPointerException: null
[INFO] 2023-02-19 11:30:50.640 +0000 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[1719] - [WorkflowInstance-65214][TaskInstance-0] - Add task to stand by list, task name:太原运营订单实时看板-0点初始化, task id:null, task code:8623733006592
[ERROR] 2023-02-19 11:30:50.640 +0000 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[694] - [WorkflowInstance-0][TaskInstance-0] - Start workflow error
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitStandByTask(WorkflowExecuteRunnable.java:1832)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitPostNode(WorkflowExecuteRunnable.java:1352)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.call(WorkflowExecuteRunnable.java:688)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[INFO] 2023-02-19 11:30:50.640 +0000 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[1821] - [WorkflowInstance-65214][TaskInstance-0] - The dependResult of task 太原运营订单实时看板-0点初始化 is success, so ready to submit to execute
[ERROR] 2023-02-19 11:30:50.640 +0000 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[694] - [WorkflowInstance-0][TaskInstance-0] - Start workflow error
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitStandByTask(WorkflowExecuteRunnable.java:1832)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitPostNode(WorkflowExecuteRunnable.java:1352)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.call(WorkflowExecuteRunnable.java:688)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[ERROR] 2023-02-19 11:30:50.640 +0000 org.apache.dolphinscheduler.server.master.event.WorkflowStartEventHandler:[72] - [WorkflowInstance-0][TaskInstance-0] - Failed to submit the workflow instance, will resend the workflow start event: WorkflowEvent(workflowEventType=START_WORKFLOW, workflowInstanceId=65012)
```

I copied the previous workflow definition, then re-selected the resource file in the task in the new workflow definition, and went online again, and the same phenomenon occurred.
This would not happen if I created a new workflow definition.

### What you expected to happen

The uploaded resource file is referenced in the task. After the resource file is deleted, and the file with the same name is uploaded again, the workflow definition can be directly put back online, or I select the resource file again in the task definition. After the workflow definition is put online, the workflow instance and task instance can be correctly generated and started to run.

### How to reproduce

First create a task, such as a shell type, which directly outputs the contents of a txt resource file, and then execute the task manually to ensure that this simple task is OK.
Then offline workflow definition, delete the txt resource file, then re-upload the same name resource file, and modify the previous task, re-select the resource file, the rest are not moving, finally on-line workflow definition, and then re-execute the workflow. Check whether only workflow instances are generated but task instances cannot be generated. In addition, NullPointerException logs continue to be generated in the master log.

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
method of buildDAG error

**Comment by QuantumXiecao** [comment]
@ziqiang-wang  Hi, According to what you instructed, I have got one error which is task instance running error instead of logging NullPointerException. Could you please upload more detailed screenshots about your steps?

**Comment by QuantumXiecao** [comment]
@ziqiang-wang 
This problem is due to that deleting resource files did not remove resource info located in the fields(task_params and resourceIds) of t_ds_task_definition table which could cause the task running exception.
Currently you could refresh task_params and resourceIds of t_ds_task_definition table by removing deleting file id and restart master-server. Of course I am trying to solve this issue. Actually the branch dev has already solved this(But exists other bug). I would try to solve this.

**Comment by ziqiang-wang** [comment]
@QuantumXiecao 
I've developed another solution:
Delete the original file directly in the hdfs location, and then upload the file to the hdfs. It should be OK. This operation does not delete the data in the table, and the association conditions are still in place. You can use this method temporarily without restarting the service.

**Comment by ziqiang-wang** [comment]
> @ziqiang-wang This problem is due to that deleting resource files did not remove resource info located in the fields(task_params and resourceIds) of t_ds_task_definition table which could cause the task running exception. Currently you could refresh task_params and resourceIds of t_ds_task_definition table by removing deleting file id and restart master-server. Of course I am trying to solve this issue. Actually the branch dev has already solved this(But exists other bug). I would try to solve this.
