### ISSUE TITLE
dolphinscheduler A problem occurred when I tried the last 200M file in the Content Center

### ISSUE THREAD

**Issue by TheWindIsRising** [apache/dolphinscheduler#13580]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I am the dolphinscheduler deployed by Kubernetes
The last time I tried to create a file of more than 200 megabytes in the resource center, the page did not respond after more than ten seconds. When I went to check the log, I found an error message
![1676686913268](https://user-images.githubusercontent.com/124865830/219826786-99d642fb-af6f-467a-8c5b-1f8fe9c018c3.png)
[WARN] 2023-02-18 10:15:41.073 +0800 org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver:[434] - Failure in @ExceptionHandler org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler#exceptionHandler(Exception, HandlerMethod)
java.lang.IllegalStateException: Could not resolve parameter [1] in public org.apache.dolphinscheduler.api.utils.Result org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler.exceptionHandler(java.lang.Exception,org.springframework.web.method.HandlerMethod): No suitable resolver

### What you expected to happen

I checked the relevant configuration file api-server/conf/application.yaml. The default value is to meet my upload requirements

### How to reproduce

The last time I tried to create a file of more than 200 megabytes in the resource center, the page did not respond after more than ten seconds. When I went to check the log, I found an error message
![1676686913268](https://user-images.githubusercontent.com/124865830/219826786-99d642fb-af6f-467a-8c5b-1f8fe9c018c3.png)
[WARN] 2023-02-18 10:15:41.073 +0800 org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver:[434] - Failure in @ExceptionHandler org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler#exceptionHandler(Exception, HandlerMethod)
java.lang.IllegalStateException: Could not resolve parameter [1] in public org.apache.dolphinscheduler.api.utils.Result org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler.exceptionHandler(java.lang.Exception,org.springframework.web.method.HandlerMethod): No suitable resolver

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TheWindIsRising** [comment]
我的存储机制是MinIO

**Comment by SbloodyS** [comment]
Related issue #10340

**Comment by TheWindIsRising** [comment]
> 相关问题#10340

我的版本是3.1.2并不是3.0.0，请问你们后续并没有修复吗
