### ISSUE TITLE
[Improvement][UI][2.0.x] Speed up refreshing of task status in process instance 

### ISSUE THREAD

**Issue by reele** [apache/dolphinscheduler#13581]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

now process instance details's page auto refresh in 90 seconds, when there's hundreds tasks, refresh may takes more than 90 seconds, then the page will goes into a dead loop. and i found that x6's cell.removeMarkup() and cell.setMarkup() takes the most time, so there are some points can speed up the refreshing:

1. there can add a buffer to compare which task need to be updated.
https://github.com/apache/dolphinscheduler/blob/a10483fb5acd53323130c70006607ae996e32759/dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue#L561-L590

2. `statusTimer` should be set after the refreshTaskStatus() first called and finished. 
https://github.com/apache/dolphinscheduler/blob/a10483fb5acd53323130c70006607ae996e32759/dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue#L184-L190

...my mistake...removeMarkup() won't takes much time.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
Does dev branch have this problem?

**Comment by reele** [comment]
> Does dev branch have this problem?

yes, looks same.
https://github.com/apache/dolphinscheduler/blob/e8b20def544a203bb9c927e19dae531b6f98d512/dolphinscheduler-ui/src/views/projects/workflow/components/dag/index.tsx#L334-L342
