### ISSUE TITLE
Need help in load balance

### ISSUE THREAD

**Issue by FlameFeather** [apache/dolphinscheduler#13582]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I want to study your load balancing algorithm. What should I do? I want to rewrite your code and run it to see the effect.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlameFeather** [comment]
I'm a college student. I want to take the load balancing of your project as the subject of my graduation thesis, but I don't know how to modify the code conveniently and quickly and then package and run it.

**Comment by fuchanghai** [comment]
<img width="687" alt="image" src="https://user-images.githubusercontent.com/33984497/220038094-a50969f5-6882-44e1-9b6c-219d5809a0ae.png">

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/33984497/220038044-92d7b3a5-a778-469b-818f-d034a56d6d98.png">

**Comment by fuchanghai** [comment]
@FlameFeather

**Comment by FlameFeather** [comment]
I know where this module is implemented, thanks
