### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment:

### ISSUE THREAD

**Issue by dragonhuihui** [apache/dolphinscheduler#13598]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

23/02/22 09:48:14 INFO [main] NativeClient: JindoTable put 1 records.
	#
	# A fatal error has been detected by the Java Runtime Environment:
	#
	#  SIGSEGV (0xb) at pc=0x00007f1a2dfe8a10, pid=1901, tid=0x00007f1b6320d700
	#
	# JRE version: Java(TM) SE Runtime Environment (8.0_291-b10) (build 1.8.0_291-b10)
	# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.291-b10 mixed mode linux-amd64 compressed oops)
	# Problematic frame:
	# C  [libjboot-c2b2f9d9b9e54fac_20201120_143827.so+0x2d6a10]  NamespaceConnector::getNamespaceRpcClient() const+0x0
	#
	# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
	#
	# An error report file with more information is saved as:
	# /data/dolphinscheduler/exec/process/27/8522/191425/847669/hs_err_pid1901.log
	#
	# If you would like to submit a bug report, please visit:
	#   http://bugreport.java.com/bugreport/crash.jsp
	#
	xxxx.sh: line 121:  1901 Aborted  

### What you expected to happen

23/02/22 09:48:14 INFO [main] NativeClient: JindoTable put 1 records.
	#
	# A fatal error has been detected by the Java Runtime Environment:
	#
	#  SIGSEGV (0xb) at pc=0x00007f1a2dfe8a10, pid=1901, tid=0x00007f1b6320d700
	#
	# JRE version: Java(TM) SE Runtime Environment (8.0_291-b10) (build 1.8.0_291-b10)
	# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.291-b10 mixed mode linux-amd64 compressed oops)
	# Problematic frame:
	# C  [libjboot-c2b2f9d9b9e54fac_20201120_143827.so+0x2d6a10]  NamespaceConnector::getNamespaceRpcClient() const+0x0
	#
	# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
	#
	# An error report file with more information is saved as:
	# /data/dolphinscheduler/exec/process/27/8522/191425/847669/hs_err_pid1901.log
	#
	# If you would like to submit a bug report, please visit:
	#   http://bugreport.java.com/bugreport/crash.jsp
	#
	smartbi_demo/ods_ware/ods_dts_ware_extend_info_f_demo.sh: line 121:  1901 Aborted  

### How to reproduce

23/02/22 09:48:14 INFO [main] NativeClient: JindoTable put 1 records.
	#
	# A fatal error has been detected by the Java Runtime Environment:
	#
	#  SIGSEGV (0xb) at pc=0x00007f1a2dfe8a10, pid=1901, tid=0x00007f1b6320d700
	#
	# JRE version: Java(TM) SE Runtime Environment (8.0_291-b10) (build 1.8.0_291-b10)
	# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.291-b10 mixed mode linux-amd64 compressed oops)
	# Problematic frame:
	# C  [libjboot-c2b2f9d9b9e54fac_20201120_143827.so+0x2d6a10]  NamespaceConnector::getNamespaceRpcClient() const+0x0
	#
	# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
	#
	# An error report file with more information is saved as:
	# /data/dolphinscheduler/exec/process/27/8522/191425/847669/hs_err_pid1901.log
	#
	# If you would like to submit a bug report, please visit:
	#   http://bugreport.java.com/bugreport/crash.jsp
	#
	smartbi_demo/ods_ware/ods_dts_ware_extend_info_f_demo.sh: line 121:  1901 Aborted  

### Version

2.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by QuantumXiecao** [comment]
@dragonhuihui Please first check your server's available port range using syscatl -a | grep -i port_range to check whether or not this port_range is not enough. From my own experience, jindo sdk's errors always relate to that. You can also set ulimit -c unlimited to enable the coredump which could refer to jindo team for debugging.
