### ISSUE TITLE
[Bug] [complement]  The complement task failed without pause

### ISSUE THREAD

**Issue by ShawshankLin** [apache/dolphinscheduler#13595]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The complement task failed without pause.

### What you expected to happen

The complement task fails to pause, and then click restart to continue.

### How to reproduce

create the complement task , run fail.

### Version

2.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xdu-chenrj** [comment]
I would like to try

**Comment by xdu-chenrj** [comment]
I want to try, but I may need some time

**Comment by ShawshankLin** [comment]
https://github.com/apache/dolphinscheduler/pull/12488
![image](https://user-images.githubusercontent.com/16248686/222717448-a5a1d25e-f53a-4381-bfa4-08c10ed2a7f7.png)
Is version 208 fixed?

**Comment by brave-lee** [comment]
Fixed by #13723
