### ISSUE TITLE
[Improvement][Task Instance] Throw an error message to tell the user that the file cannot be found instead of NPE during task execution

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#13596]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

https://github.com/apache/dolphinscheduler/pull/13593#issuecomment-1438045083

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LiJie20190102** [comment]
@SbloodyS 
I have found a solution. The solution is that when the task runs, it will re-detect whether the resource still exists. If it does not exist, it will prompt. Can I submit code

**Comment by SbloodyS** [comment]
> @SbloodyS I have found a solution. The solution is that when the task runs, it will re-detect whether the resource still exists. If it does not exist, it will prompt. Can I submit code

Sure. Assigned to you. Looking forward to your contribution.

**Comment by LiJie20190102** [comment]
@SbloodyS 
We all have this problem in 3.1. x. Do we need to submit it to 3.1.5-prepare as a bug

https://github.com/apache/dolphinscheduler/issues/13656

**Comment by Radeity** [comment]
> @SbloodyS We all have this problem in 3.1. x. Do we need to submit it to 3.1.5-prepare as a bug
> 
> #13656

Hi, @LiJie20190102 , if it's irrelevant to new resource center, you can directly submit to dev, and community will decide whether to merge it into release 3.1.5 or 3.2.0.

**Comment by LiJie20190102** [comment]
> > @SbloodyS We all have this problem in 3.1. x. Do we need to submit it to 3.1.5-prepare as a bug
> > #13656
> 
> Hi, @LiJie20190102 , if it's irrelevant to new resource center, you can directly submit to dev, and community will decide whether to merge it into release 3.1.5 or 3.2.0.

@SbloodyS @Radeity  After I read the relevant code carefully, I found that 3.1. x is not the same as the 3.2 version code. 3.2 will not have a NPE  error, and 3.1. x will have a NPE problem. The dev branch does not need to submit the corresponding code to deal with this problem. Can I only submit the code to 3.1.5 to fix this problem?

**Comment by Radeity** [comment]
That's okay, you can submit to 3.1.5-prepare.
