### ISSUE TITLE
[Bug] The sub_process task cannot be stopped (occasionally)

### ISSUE THREAD

**Issue by ChinaYiGuan** [apache/dolphinscheduler#13601]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When the main process includes sub-processes:
Sub-process processing is completed, and the main process cannot be synchronized
#The main process cannot perceive the success or failure of sub-process execution. The main process node can never be stopped.
eg:
![step1](https://user-images.githubusercontent.com/91529181/220549294-8af7e543-2aca-4ba2-a40b-2da0c5be9083.png)
![step2](https://user-images.githubusercontent.com/91529181/220549310-eb8eaab5-f0c1-477a-84ec-75ac217dfd59.png)
![step3](https://user-images.githubusercontent.com/91529181/220549321-d8da4254-538e-4f80-9bd3-b2d8f9ad3763.png)

### What you expected to happen

When the sub-process status is updated, the main process cannot perceive/change

### How to reproduce

Multiple process tasks containing subprocesses are scheduled concurrently. Occasionally！

### Anything else

Currently, there are 20000+processes and 50000+ task instances every day, and every 2-3 days, there will be tasks that cannot be stopped (the status cannot be synchronized after the factor process is completed)

### Version

3.0.2 and 3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ChinaYiGuan** [comment]
The problem occurs in version: 3.0.0 and 3.0.2

**Comment by fuchanghai** [comment]
@ChinaYiGuan bro , this pr  #12933   can resolve you question?

@caishunfeng

**Comment by caishunfeng** [comment]
Please check the master log of this workflow instance.
