### ISSUE TITLE
[Feature][Datasource] Support Kyuubi datasource

### ISSUE THREAD

**Issue by zhaohehuhu** [apache/dolphinscheduler#13600]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Kyuubi is a powerful sql gataway, so we should make it available in DS

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
@zhaohehuhu just use datasource that type of hive  ,which can connect kyuubi

@DarkAssassinator @SbloodyS

**Comment by zhaohehuhu** [comment]
> 

could we enable kyuubi datasource using Kyuubi JDBC instead of Hive. I'm willing to contribute it now.

**Comment by SbloodyS** [comment]
> just use datasource that type of hive ,which can connect kyuubi

Yes. It can be compatible right now. In the future, I personally think it is better to support it just like the way we do for Trino and Presto. @fuchanghai 

> could we enable kyuubi datasource using Kyuubi JDBC instead of Hive. I'm willing to contribute it now.

Sure. @zhaohehuhu

**Comment by zhaohehuhu** [comment]
> > just use datasource that type of hive ,which can connect kyuubi
> 
> Yes. It can be compatible right now. In the future, I personally think it is better to support it just like the way we do for Trino and Presto. @fuchanghai
> 
> > could we enable kyuubi datasource using Kyuubi JDBC instead of Hive. I'm willing to contribute it now.
> 
> Sure. @zhaohehuhu

Let me work on this one. Thanks.

**Comment by pan3793** [comment]
It would be nice to use Kyuubi JDBC driver instead of Hive JDBC driver, to fix some issues like https://github.com/apache/kyuubi/discussions/4408

**Comment by SbloodyS** [comment]
> It would be nice to use Kyuubi JDBC driver instead of Hive JDBC driver, to fix some issues like [apache/kyuubi#4408](https://github.com/apache/kyuubi/discussions/4408)

That would be nice.
