### ISSUE TITLE
Parameter sent downstream cannot carry "=" (Python)

### ISSUE THREAD

**Issue by SnJForever** [apache/dolphinscheduler#13606]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Parameter sent downstream cannot carry "="

### What you expected to happen

Support passing "="

### docker standalone
`print('${setValue(key=%s)}' % value)`
> Parameter sent downstream cannot carry "="

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by minlywang** [comment]
Python Version: 3.6.8

DolphinSheduler version: 3.2.0 Standalone mode


Pass parameter from Python task to downstream
Use print('${setValue(key=%s)}' % value), DolphinScheduler will capture the ${setValue(key=value} in the output to capture the parameters and pass them downstream.

print('${setValue(key=%s)}' % value)

Didn't work!!!!


Any suggestions???
