### ISSUE TITLE
[upload][api] upload resource in parallel

### ISSUE THREAD

**Issue by litiliu** [apache/dolphinscheduler#13618]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Some times the resources can be as large as 200+M,  uploading will take a long time. Support uploading in parallel will help reducing time.   We have implemented this and willing to contribute.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sqxinquan** [comment]
I think this is a restricted upload.
