### ISSUE TITLE
Use sql query result from upstream sql task in downstream sql task

### ISSUE THREAD

**Issue by KINGGUOKUN** [apache/dolphinscheduler#13619]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Upstream sql task is somethine like  select query and set the result as output list parameters.
But I can't use it in downstream sql task, eg, insert the result from upstream sql task into a table in downstream sql task.

### Use case

I can use the output list parameters from upstream sql task in downstream sql task.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
how about directly making the upstream task as subquery and combining two sql into one? separate sql result is not a good way which may cause parameter context too large
