### ISSUE TITLE
[Bug] [master-server] master & work die quickly 

### ISSUE THREAD

**Issue by zui01** [apache/dolphinscheduler#13611]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Install the dolphin cluster. Then start-all.sh. jps found that work and server hang just after starting. Checked maser's logs and found that it could not register with zk. And the following error was reported.

Caused by: org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /dolphinscheduler/nodes/master

i checked the version. zk:3.4.14.   ds:3.1.3

### What you expected to happen

the master and work shuold be start right

### How to reproduce

let it start

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
The 3.1.X version requires at least 3.5.X zookeeper version.

**Comment by zui01** [comment]
> The 3.1.X version requires at least 3.5.X zookeeper version.

注册中心：[ZooKeeper](https://zookeeper.apache.org/releases.html) (3.4.6+)，[下载地址](https://zookeeper.apache.org/releases.html)
??plz updatad the doc
