### ISSUE TITLE
[Bug] [] Built-in parameters are written in sql and cannot be executed.

### ISSUE THREAD

**Issue by aaronwenbo** [apache/dolphinscheduler#13615]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

insert into table2 
select * from table1 from dt >= $[yyyyyMMdd-1] and dt <$[yyyyMMdd]
;

无法在3.1.3中执行，但在之前版本是ok的

### What you expected to happen

兼容前版本

### How to reproduce

rt

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by batmanneverdie** [comment]
我在 ds 3.1.3 中也遇到了这个问题，我的解决方案是替换 3.1.3 中 `org.apache.dolphinscheduler.plugin.task.sql.SqlTask#getSqlAndSqlParamsMap` 的`Map<String, Property> paramsMap = taskExecutionContext.getPrepareParamsMap();`代码为 ds 2.0.7-release 版本的同方法的下的 
```
// combining local and global parameters
Map<String, Property> paramsMap = ParamUtils.convert(taskExecutionContext, getParameters());
```

**Comment by zhongjiajie** [comment]
> 我在 ds 3.1.3 中也遇到了这个问题，我的解决方案是替换 3.1.3 中 `org.apache.dolphinscheduler.plugin.task.sql.SqlTask#getSqlAndSqlParamsMap` 的`Map<String, Property> paramsMap = taskExecutionContext.getPrepareParamsMap();`代码为 ds 2.0.7-release 版本的同方法的下的
> 
> ```
> // combining local and global parameters
> Map<String, Property> paramsMap = ParamUtils.convert(taskExecutionContext, getParameters());
> ```

do you want to submit a pr in dev branch to fix it? @batmanneverdie

**Comment by batmanneverdie** [comment]
@zhongjiajie yes, I'm willing to do

**Comment by zhongjiajie** [comment]
I assigned to you, looking forward your contributors
