### ISSUE TITLE
[Bug] [Module Name] installation error: Command not found: Command not found rmr

### ISSUE THREAD

**Issue by ZhangZangQian** [apache/dolphinscheduler#13629]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

安装报错，3.1.3版本，Zookeeper 3.8.1 版本

### What you expected to happen

15:09:38.567 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.library.path=/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
15:09:38.567 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.io.tmpdir=/tmp
15:09:38.567 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.compiler=
15:09:38.567 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.name=Linux
15:09:38.567 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.arch=amd64
15:09:38.567 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.version=3.10.0-1160.el7.x86_64
15:09:38.567 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.name=dolphinscheduler
15:09:38.567 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.home=/home/dolphinscheduler
15:09:38.567 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.dir=/opt/apache-dolphinscheduler-3.1.3-bin
15:09:38.567 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.memory.free=939MB
15:09:38.567 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.memory.max=989MB
15:09:38.567 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.memory.total=989MB
15:09:38.571 [main] INFO org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=org.apache.zookeeper.ZooKeeperMain$MyWatcher@7ec7ffd3
15:09:38.577 [main] INFO org.apache.zookeeper.common.X509Util - Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
15:09:38.582 [main] INFO org.apache.zookeeper.ClientCnxnSocket - jute.maxbuffer value is 1048575 Bytes
15:09:38.593 [main] INFO org.apache.zookeeper.ClientCnxn - zookeeper.request.timeout value is 0. feature enabled=false
ZooKeeper -server host:port -client-configuration properties-file cmd args
addWatch [-m mode] path # optional mode is one of [PERSISTENT, PERSISTENT_RECURSIVE] - default is PERSISTENT_RECURSIVE
addauth scheme auth
close
config [-c] [-w] [-s]
connect host:port
create [-s] [-e] [-c] [-t ttl] path [data] [acl]
delete [-v version] path
deleteall path [-b batch size]
delquota [-n|-b|-N|-B] path
get [-s] [-w] path
getAcl [-s] path
getAllChildrenNumber path
getEphemerals path
history
listquota path
ls [-s] [-w] [-R] path
printwatches on|off
quit
reconfig [-s] [-v version] [[-file path] | [-members serverID=host:port1:port2;port3[,...]]] | [-add serverId=host:port1:port2;port3[,...]] [-remove serverId[,...]*]
redo cmdno
removewatches path [-c|-d|-a] [-l]
set [-s] [-v version] path data
setAcl [-s] [-v version] [-R] path acl
setquota -n|-b|-N|-B val path
stat [-w] path
sync path
version
whoami
Command not found: Command not found rmr
15:09:38.599 [main] ERROR org.apache.zookeeper.util.ServiceUtils - Exiting JVM with code 127
5.startup

### How to reproduce

zookeeper 3.8.1 版本，然后执行 install.sh 脚本即可复现

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
should we change ``` rmr``` to``` deleteall``` @SbloodyS

**Comment by fuchanghai** [comment]
@ZhangZangQian do you use the  lastest script files,? i find in lastest file that name of remove-zk-node.sh  we use the deleteall command instead of rmr

**Comment by fuchanghai** [comment]
@ZhangZangQian do you use the  lastest script files,? i find in lastest file that name of remove-zk-node.sh  we use the deleteall command instead of rmr

**Comment by ZhangZangQian** [comment]
> @ZhangZangQian do you use the lastest script files,? i find in lastest file that name of remove-zk-node.sh we use the deleteall command instead of rmr

I downloaded the package from the official website, the script file uses rmr command

<img width="1650" alt="image" src="https://user-images.githubusercontent.com/113660447/221454924-f5719801-62ef-46b6-9c31-da3a8b869b53.png">
