### ISSUE TITLE
[Improvement][Resource] Resource‘s full name is too short(only 128), And this limit is unknown to user

### ISSUE THREAD

**Issue by zuzuviewer** [apache/dolphinscheduler#13624]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

resource’s full_name in table t_ds_resources is only 128 byte, too short for use and this limit is opaque

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi, @zuzuviewer, we have refactored resource center in dev, and do not have the limit now.

**Comment by zuzuviewer** [comment]
Which release version has this change @Radeity

**Comment by Radeity** [comment]
> Which release version has this change @Radeity

Hi, @zuzuviewer , the earliest released version will be 3.2.0.
