### ISSUE TITLE
[Bug] [Task] Java task get wrong mainJarName when have dot in fullName

### ISSUE THREAD

**Issue by Radeity** [apache/dolphinscheduler#13638]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

https://github.com/apache/dolphinscheduler/blob/9668c84d30b2c885cbf20ccf9e76f64a41f77096/dolphinscheduler-task-plugin/dolphinscheduler-task-java/src/main/java/org/apache/dolphinscheduler/plugin/task/java/JavaTask.java#L201-L203

Provide main jar with the full name `aaaa_3.3.0.jar`, finally, get main jar name `0.jar`.

### What you expected to happen

Get right main jar name `aaaa_3.3.0.jar`.

### How to reproduce

Run a java task with main jar which contains dot in name.

### Anything else

In addition, may i ask why codes in line 202 and 203 are needed?

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
cc @zhuangchong , @106umao

**Comment by zhuangchong** [comment]
Lines 202-203 are redundant operations and can be used directly `javaParameters.getMainJar().getResourceName()`.

**Comment by Radeity** [comment]
Hi, @zhuangchong , thanks for your feedback, i'll fix it together in https://github.com/apache/dolphinscheduler/pull/13536 and close this issue, welcome to help review that pr when you're available : )
