### ISSUE TITLE
[Bug] [UI]  Failed to load module script: 

### ISSUE THREAD

**Issue by georgehu0815** [apache/dolphinscheduler#13630]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

unable to load http://localhost:12345/dolphinscheduler/ui when running docker instance.

Following is the error:

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/116222457/221423878-98f6de59-baf7-4610-8a35-f745d3463cd9.png">

### What you expected to happen

should load the ADMIN UI, but only get the empty page with errors in the Chrome console

### How to reproduce

DOLPHINSCHEDULER_VERSION=3.1.4
docker run   -p 12345:12345 -p 25333:25333 \
 apache/dolphinscheduler-standalone-server:"${DOLPHINSCHEDULER_VERSION}"

#  curl localhost:12345/dolphinscheduler/ui

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ThisisWyatt** [comment]
**use image created by local source code**, this bug will appear， but use official image like apache/dolphinscheduler-standalone-server:3.1.4, everything is ok. 

this bug will appear when use dolphinscheduler-master, dolphinscheduler-worker, dolphinscheduler-worker-api created by local.

**Comment by pq-dong** [comment]
i change the dolphinscheduler-ui  source code, build docker image, this bug will appear

**Comment by maikouliujian** [comment]
i also has the bug,how to solve it?????

**Comment by YJLau91** [comment]
Hi,

I am experiencing the same issue. When I run the UI separately using pnpm run dev, I am able to view the page without any problems. However, when I run it using the Docker image, I encounter the same error in the console. Could you please advise on how to resolve this? Thank you!
