### ISSUE TITLE
This kind of a large number of tasks are waiting in series, but not executed, how to solve it?

### ISSUE THREAD

**Issue by jianghanfen** [apache/dolphinscheduler#13647]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://user-images.githubusercontent.com/39332638/221814980-de1b2151-f59b-42c0-a234-0c9438fcd110.png)
![image](https://user-images.githubusercontent.com/39332638/221815261-6123ef02-e714-4fe3-8ec6-efe318798123.png)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JaayYoung** [comment]
@jianghanfen  assign to me!
