### ISSUE TITLE
[Bug] [UI] The data source center edit data source pop-up form cannot display the underline

### ISSUE THREAD

**Issue by batmanneverdie** [apache/dolphinscheduler#13646]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

# version
os: windows 11
ds: 3.1.3-release

# 问题描述
**数据源中心 -> 创建/编辑数据源**，弹窗表单无法展示下划线，如下图的`数据源名称`和`用户名`均包含下划线：
![image](https://user-images.githubusercontent.com/41139080/221808978-1c6cc832-4149-46b8-8d01-b988fd7bbed6.png)

### What you expected to happen

正确完整地展示用户输入的字符。

### How to reproduce

**数据源中心 -> 创建/编辑数据源**，在**任意字段输入包含下划线的内容**

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hkun0120** [comment]
I want to contribute this

**Comment by hkun0120** [comment]
@SbloodyS Can I fix this bug and then commit to the code repo?

**Comment by SbloodyS** [comment]
> @SbloodyS Can I fix this bug and then commit to the code repo?

After my test, I found that `dev` had fixed this problem.
