### ISSUE TITLE
[Bug] [dolphinscheduler-ui] Flink version >=1.12 can‘t save when programType is JAVA or PYTHON

### ISSUE THREAD

**Issue by luoyize** [apache/dolphinscheduler#13644]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when use filnk task , assign the version >=1.12 , but the instance can't start with a error can't find jar file  -yn .
so I find  Flink version >=1.12 can‘t save when programType is JAVA or PYTHON ,the version always is <1.10.

### What you expected to happen

when use filnk task , assign the version >=1.12 , but the instance can't start with a error can't find jar file  -yn .
so I find  Flink version >=1.12 can‘t save when programType is JAVA or PYTHON ,the version always is <1.10.

### How to reproduce

when use filnk task , assign the version >=1.12 , but the instance can't start with a error can't find jar file  -yn .
so I find  Flink version >=1.12 can‘t save when programType is JAVA or PYTHON ,the version always is <1.10.

### Anything else

I had find the solution to fix this .
update us-flinx.ts code follow :  
`  watchEffect(() => {
    if(model.programType === 'SQL'){
      model.flinkVersion = '>=1.13'
    }else {
      if(model.flinkVersion === '>=1.13'){
        model.flinkVersion = '<1.10'
      }
    }
    // model.flinkVersion = model.programType === 'SQL' ? '>=1.13' : '<1.10'
  })`

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi, @chenss-1 , this ui bug is duplicated with https://github.com/apache/dolphinscheduler/pull/13628

**Comment by luoyize** [comment]
> Hi, @chenss-1 , this ui bug is duplicated with #13628

ok
