### ISSUE TITLE
[Improvement][Resource Center] Remove useless table t_ds_relation_resources_task

### ISSUE THREAD

**Issue by Radeity** [apache/dolphinscheduler#13651]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In new resource center, task can download resources directly by `fullName`, also, according to discussion before (https://github.com/apache/dolphinscheduler/pull/13593#issuecomment-1438045083), when delete or update resource, we don't have to check online status of the related task. In this way, `t_ds_relation_resources_task` is useless, DS doesn't have to keep the relation of task and resource.

Can we remove table `t_ds_relation_resources_task` and correlative entity, which can simplify code logic in resource center?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Welcome to discuss about it!  cc @SbloodyS @EricPyZhou

**Comment by SbloodyS** [comment]
cc @ruanwenjun @zhongjiajie @caishunfeng @EricGao888

**Comment by ruanwenjun** [comment]
We can delete this table and make the code clearer.

**Comment by Radeity** [comment]
> We can delete this table and make the code clearer.

Thanks for your comment, i'll work on this.

**Comment by Radeity** [comment]
Hi, @SbloodyS , what's your suggestion about removing that online status check?
