### ISSUE TITLE
[Bug]Datax synchronizes mysql data, The task fails after about 2 hours each time

### ISSUE THREAD

**Issue by Flutemr** [apache/dolphinscheduler#13658]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

datax synchronizes mysql data. The task fails after about 2 hours each time. However, I used a dolphinscheduler version 2.0.7 that did not fail and ran for over 3 hours, using the same datax version.
3.1.4 and 3.1.3 version fail log and run times:
![1677722338830](https://user-images.githubusercontent.com/30035663/222312109-509e748d-58d7-43f8-992a-65f3dce182a2.jpg)
![1677722362891](https://user-images.githubusercontent.com/30035663/222312135-10720ddf-1bdf-4004-8165-9de207044e11.jpg)
![1677722383272](https://user-images.githubusercontent.com/30035663/222312146-3f5062bc-7dea-401f-9b90-f24d8391c78c.jpg)

this 2.0.7 version,and  can run succeed:
![1677722401301](https://user-images.githubusercontent.com/30035663/222312240-dba82ba7-2913-4845-a7c1-1be8b5563f53.jpg)

### What you expected to happen

How to solve

### How to reproduce

no

### Anything else

no

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
@Flutemr Can you show the contents of the datax script

**Comment by Flutemr** [comment]
> @Flutemr Can you show the contents of the datax script
The following is my script, the table data volume is relatively large, synchronization time is long:
{
	"job": {
	"setting": {
		"speed": {
				"byte": 5242880
		},
		"errorLimit": {
		"record": 0,
		"percentage": 0.02
		}
	},
	"content": [
		{
		"reader": {
		  "name": "mysqlreader",
		  "parameter": {
			"username": "name",
			"password": "pass", 
			"column": [
				"id",
				"capture_type",
				"capture_time",
				"create_time",
				"image_path",
				"community_id",
				"data_id",
				"point_id",
				"del_flag",
				"file_size",
				"big_img"
				],
			"splitPk": "",
			"where":"str_to_date(capture_time,'%Y-%m-%d')='${bizdate}'",
			"connection": [
			  {
				"table": [
				  "tb_zaxq_capture"
				],
				"jdbcUrl": [
				  "jdbc:mysql://ip:3306/databases?useSSL=false&serverTimezone=GMT%2B8"
				]
			  }
			]
		  }
		},
		"writer": {
		  "name": "hdfswriter",
		  "parameter": {
			"defaultFS": "hdfs://ns1",
			"fileType": "orc",
			"path": "/user/hive/warehouse/za_ods.db/ods_za_tb_zaxq_capture/dt=${bizdate1}",
			"fileName":"ods_za_tb_zaxq_capture",
			"writeMode": "append",
			"fieldDelimiter": "\u0001",
			"column": [
				{"name":"id","type":"string"},
				{"name":"capture_type","type":"string"},
				{"name":"capture_time","type":"string"},
				{"name":"create_time","type":"string"},
				{"name":"image_path","type":"string"},
				{"name":"community_id","type":"string"},
				{"name":"data_id","type":"string"},
				{"name":"point_id","type":"string"},
				{"name":"del_flag","type":"string"},
				{"name":"file_size","type":"string"}
				{"name":"big_img","type":"string"}
			]
		  }
		}
	  }
	]
  },
  "core":{
	"transport": {
	  "channel": {
		"speed": {
		  "byte": 1048576
		}
	  }
	}
  }
}
