### ISSUE TITLE
[Bug] [Master] NPE caused by stop and restart flow whenProhibit execution execution task has child node

### ISSUE THREAD

**Issue by liuxzy** [apache/dolphinscheduler#13657]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Node relations as:
Node1 --> Node3; Node2 -->Node3;  Node1 is Prohibited
When flow is running, or the Node2  instance is runing,  Stop this flow, and restart;  it thows NPE.

It maybe caused by :master rebuild Dag not include Node1. and submit Node2, when Node2 is finished,  will check Node3  upstrem  task(Node1 and Node2) state, but Node1 is not found in DAG,  NPE  

### What you expected to happen

 rebuild Dag  include Node1

### How to reproduce

Node relations as:
Node1 --> Node3; Node2 -->Node3;  Node1 is Prohibited
When flow is running, or the Node2  instance is runing,  Stop this flow, and restart;  it thows NPE.

It maybe caused by :master rebuild Dag not include Node1. and submit Node2, when Node2 is finished,  will check Node3  upstrem  task(Node1 and Node2) state, but Node1 is not found in DAG,  NPE  

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
@liuxzy AFAK,when start the workflow, the generated DAG contains  Node1, Node1 will be put in forbiddenMap， so that Node1's state will be ignored. 
finally,the action that start and restart use the same interface.can you show the log? 

cc @ruanwenjun @caishunfeng

**Comment by liuxzy** [comment]
3xk,  done!  AS: when get TaskNode form dag,  add if(null == taskNode) { get taskNode from forbiddenMap)

**Comment by HomminLee** [comment]
If you start a workflow by directly executing Node2, the same problem will occur. 

If there is startNode or recoveryNode, DAG will recursively find node from startNode or recoveryNode, so DAG not include Node1.
"Node1 will be put in forbiddenMap" is right, but the method which throw the exception is to find the dependent nodes. It is precisely because the forbiddenMap contains Node1, the method will try to find the dependency of Node1. #7538

Based on the above analysis, I think it is only necessary to check the existence of node. If you agree with me, I can take this issue. @fuchanghai

**Comment by fuchanghai** [comment]
> If you start a workflow by directly executing Node2, the same problem will occur.
> 
> If there is startNode or recoveryNode, DAG will recursively find node from startNode or recoveryNode, so DAG not include Node1. "Node1 will be put in forbiddenMap" is right, but the method which throw the exception is to find the dependent nodes. It is precisely because the forbiddenMap contains Node1, the method will try to find the dependency of Node1. #7538
> 
> Based on the above analysis, I think it is only necessary to check the existence of node. If you agree with me, I can take this issue. @fuchanghai

Thank you for your help，i can't agree more
