### ISSUE TITLE
[Bug] [Master] NullPointerException caused by deleting resource 

### ISSUE THREAD

**Issue by LiJie20190102** [apache/dolphinscheduler#13656]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

version :3.1.2
When I delete the resources of a Spark task and start it, the job will fail with NullPointerException 

![aa](https://user-images.githubusercontent.com/53458004/222134066-88c3ac46-5863-404a-b398-fdb736cf6c9e.png)

I have found the problem code, please allow me to submit the code.

### What you expected to happen

When I delete the resources of a Spark task and start it, the job will fail with NullPointerException ,

![aa](https://user-images.githubusercontent.com/53458004/222134066-88c3ac46-5863-404a-b398-fdb736cf6c9e.png)

I don't think there should be any exception. It should prompt that the resource does not exist. I have found the problem code, please allow me to submit the code.

### How to reproduce

1. Create a Spark-type workflow definition, reference a resource (such as jar), and then execute the workflow normally;

2. Offline the workflow, delete the resource, go online the workflow, and finally execute the workflow.

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JaayYoung** [comment]
guys, I hava same probloms in 3.0 , put file overwrite in hdfs can be useful.

**Comment by LiJie20190102** [comment]
> guys, I hava same probloms in 3.0 , put file overwrite in hdfs can be useful.

The method you said can indeed replace resources, but I think that after deleting resources from the web page and running the task, we should still prompt that resources no longer exist, because not everyone knows that resources can be replaced from hdfs

**Comment by Radeity** [comment]
Hi, @LiJie20190102 , this issue duplicates with https://github.com/apache/dolphinscheduler/issues/13596, you can leave message to work on this under that issue.

**Comment by Radeity** [comment]
Hi, @JaayYoung , in dev, resource center has been refactored, and support re-upload operation in ds now, maybe release at version 3.2.0. Also, delete and upload resource with same name again in ds ui page should better not affect task execution, it's still under discussion, you can follow https://github.com/apache/dolphinscheduler/issues/13651.
