### ISSUE TITLE
[Bug] [WorkerGroup] When deploying through 3.1.4 helm, setting WORKER_GROUPS and WORKER_GROUPS_0 in work env in values.yaml has no effect

### ISSUE THREAD

**Issue by qin-sy** [apache/dolphinscheduler#13666]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

当我在k8s中部署worker时不能将worker注册到指定的workergroup中。

### What you expected to happen

期望当我修改WORKER_GROUPS中的分组时可以在启动时注册到我指定的workergroup中。
当我在k8s中部署多个worker 的 StatefulSet 时，希望可以将不同的 StatefulSet 中的 POD 使用不同的分组管理。

现在启动时只能注册到默认的default中。
当我创建新的workergroup时，只能选择已经注册到default中的woker，
当 StatefulSet 中的POD增加或者减少时，需要人工修改workergroup中的设置。

### How to reproduce

使用[3.1.4版本](https://github.com/apache/dolphinscheduler/tree/3.1.4-release)的 helm 配置文件
修改WORKER_GROUPS、WORKER_GROUPS_0中的分组后部署到k8s中后在画面中查看workgroup

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@qin-sy Hello, if u deploy DS through helm, the environment variable `WORKER_GROUPS` will take effect for you workers. Could u explain in details how you add more different `statefulsets`? Have u injected the environment variables defined in `values.yaml`?

https://github.com/apache/dolphinscheduler/blob/30fd43e32ba2b156e0c68d8ce15cfbd56263ad62/deploy/kubernetes/dolphinscheduler/values.yaml#L384-L392

https://github.com/apache/dolphinscheduler/blob/30fd43e32ba2b156e0c68d8ce15cfbd56263ad62/deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml#L72

BTW, could u plz use English for issue description in the future? Thx.

**Comment by qin-sy** [comment]
@EricGao888
在3.1.0的版本中修改WORKER_GROUPS内容可以自动创建指定分组。
3.1.4版本不行。3.1.4版本只会在default分组中添加worker。

google translate：
Modifying the content of WORKER_GROUPS in version 3.1.0 can automatically create specified groups. Version 3.1.4 does not work. Version 3.1.4 will only add workers to the default group。

```diff
 env: 
-  WORKER_GROUPS_0: default 
   WORKER_MAX_CPU_LOAD_AVG: "-1" 
   WORKER_RESERVED_MEMORY: "0.3" 
   WORKER_EXEC_THREADS: "100" 
   WORKER_HEARTBEAT_INTERVAL: "10s" 
   WORKER_HEART_ERROR_THRESHOLD: "5" 
   WORKER_HOST_WEIGHT: "100" 
-  WORKER_GROUPS: "default" 
+  WORKER_GROUPS: "another-works" 
```

3.1.0: 
![image](https://user-images.githubusercontent.com/126856011/223644675-6095637d-0e04-47b4-875a-deecae1b3090.png)

**Comment by Radeity** [comment]
Hi, @qin-sy , we don't maintain worker group in registry since 3.1.4 (related issue: https://github.com/apache/dolphinscheduler/issues/12157), you can config them in UI page by yourself and worker group info will be stored in db.

**Comment by Radeity** [comment]
> @qin-sy Hello, if u deploy DS through helm, the environment variable `WORKER_GROUPS` will take effect for you workers. Could u explain in details how you add more different `statefulsets`? Have u injected the environment variables defined in `values.yaml`?
> 
> https://github.com/apache/dolphinscheduler/blob/30fd43e32ba2b156e0c68d8ce15cfbd56263ad62/deploy/kubernetes/dolphinscheduler/values.yaml#L384-L392
> 
> https://github.com/apache/dolphinscheduler/blob/30fd43e32ba2b156e0c68d8ce15cfbd56263ad62/deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml#L72
> 
> BTW, could u plz use English for issue description in the future? Thx.

Hi, @EricGao888 , this configuration in values.yaml may be outdated, environment variable WORKER_GROUP is useless in the latest version, i can create a PR to remove them.
