### ISSUE TITLE
[Bug] [Source Center] can not use my py file 

### ISSUE THREAD

**Issue by zui01** [apache/dolphinscheduler#13672]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

i upload py file in source center.then i try to use it in my workflow .
but the log said 'can not find py file '
nohup python hdfs:/dolphinscheduler/root/resources/datasource.py 5 &. (this is my worknode shell)
![image](https://user-images.githubusercontent.com/54675044/222951139-5895195f-5e9c-4eec-b66b-a9287f03d806.png)
![image](https://user-images.githubusercontent.com/54675044/222951188-5ac07795-5073-461f-a02e-d5d7fd3b3eb8.png)

### What you expected to happen

it shuold run normaly,and find the file

### How to reproduce

just plz updata the doc. plzzzzz ,and give some example 

### Anything else

the doc should not like this .

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi, @Anubisxcw , the doc is clear, firstly, you have to select resource `datasource.py`, then the right command should be `nohup python datasource.py`

**Comment by zui01** [comment]
> 

tks。but not work

**Comment by Radeity** [comment]
Can you show me your script (`16_18_node.sh`)?

**Comment by zui01** [comment]
> Can you show me your script (`16_18_node.sh`)?

https://github.com/Anubisxcw/pybigdata/blob/master/flink/flink-sql/datagen.py

**Comment by zui01** [comment]
i changed the file to LF endings .but now the task just run and not show logs.meantime ,the task cannot stop.

**Comment by Radeity** [comment]
> Can you show me your script (`16_18_node.sh`)?

I mean the shell script generated by ds.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/45198818/223025463-d320d3b2-7c85-441a-85b7-aa3cf0494554.png">

**Comment by zui01** [comment]
> > Can you show me your script (`16_18_node.sh`)?
> 
> I mean the shell script generated by ds.
> 
> <img alt="image" width="843" src="https://user-images.githubusercontent.com/45198818/223025463-d320d3b2-7c85-441a-85b7-aa3cf0494554.png">

ok let me check check

**Comment by zui01** [comment]
> > Can you show me your script (`16_18_node.sh`)?
> 
> I mean the shell script generated by ds.
> 
> <img alt="image" width="843" src="https://user-images.githubusercontent.com/45198818/223025463-d320d3b2-7c85-441a-85b7-aa3cf0494554.png">

oh ,just forget tell u.the task node doed not generated logs

**Comment by zui01** [comment]
![image](https://user-images.githubusercontent.com/54675044/223036115-94b78817-3735-47f7-804a-e5b153ec237d.png)
![image](https://user-images.githubusercontent.com/54675044/223036137-e42e0250-6d6b-4cd2-9a4d-79b0d229527b.png)

**Comment by zui01** [comment]
![image](https://user-images.githubusercontent.com/54675044/223036608-0e922d68-ddc5-433c-923a-c2d3ff7b8e09.png)
