### ISSUE TITLE
[Bug] [flink sql] flink sql  "The jar for the task is required."

### ISSUE THREAD

**Issue by xizhimen** [apache/dolphinscheduler#13678]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

env:
    dolphinscheduler 3.1.4
    flink 1.14.2
problem:
    cannot run flink sql task
    
![image](https://user-images.githubusercontent.com/19748550/223035050-2b0a60a5-d4ad-4978-82bb-d71699297b92.png)
![image](https://user-images.githubusercontent.com/19748550/223035148-51e96703-1232-439b-bf90-b7447e188cc9.png)
error log :
![image](https://user-images.githubusercontent.com/19748550/223035218-a728e92c-e342-460a-82d7-0fb0335b707d.png)
some body can help me?

### What you expected to happen

sql tasks should not prompt for jar package issues

### How to reproduce

See the picture above (What happened)

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
@xizhimen may be you lost parameter
![image](https://user-images.githubusercontent.com/33984497/223042069-95a295b0-ccea-499d-966e-42b2d7101128.png)

**Comment by xizhimen** [comment]
@fuchanghai  sql方式没有您图中的参数项

**Comment by fuchanghai** [comment]
@xizhimen  i'm not good at flink ,but if you have no idea, you can rerun after change the codes as following:
<img width="968" alt="image" src="https://user-images.githubusercontent.com/33984497/223055465-f6dbdabc-aca6-4287-83e3-2f7e4d74a29f.png">

**Comment by fuchanghai** [comment]
> @xizhimen i'm not good at flink ,but if you have not idea, you can rerun after change the codes as following: <img alt="image" width="968" src="https://user-images.githubusercontent.com/33984497/223055465-f6dbdabc-aca6-4287-83e3-2f7e4d74a29f.png">

i ignore the parameter ```mainjar ```,if the program type is ```SQL```

**Comment by Radeity** [comment]
> i ignore the parameter `mainjar `,if the program type is `SQL`

Hi, @fuchanghai , good catch, it should work. However, `setMainJarName()` in useless (relative pr https://github.com/apache/dolphinscheduler/pull/13536) in dev, so if you want to submit a PR, can you submit to 3.1.5-prepare?

**Comment by fuchanghai** [comment]
> > i ignore the parameter `mainjar `,if the program type is `SQL`
> 
> Hi, @fuchanghai , good catch, it should work. However, `setMainJarName()` in useless (relative pr #13536) in dev, so if you want to submit a PR, can you submit to 3.1.5-prepare?

thanks for you remind, i'll fix it

**Comment by zhuangchong** [comment]
Has been fixed in version 3.1.5.
