### ISSUE TITLE
It is not possible to switch the workflow for a task that has already been stopped.

### ISSUE THREAD

**Issue by xqhxxx** [apache/dolphinscheduler#13679]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

It is not possible to switch the workflow for a task that has already been stopped.
![微信截图_20230306161929](https://user-images.githubusercontent.com/89012608/223055067-23c1dc47-24d3-4dcd-a492-8263bc6f09da.png)
The drop-down box is disabled

### What you expected to happen

A profile is not configured to be enabled

### How to reproduce

Tell me how to change in that configuration file that has the relevant parameters involved

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
I think this question is more related to design. If we enable users to switch the workflow one task belongs to, how should we deal with the previous workflow? Simply remove the task node? What about those connections to it?
