### ISSUE TITLE
[Bug] [Master] MASTER server failover failed！

### ISSUE THREAD

**Issue by Sdreamery** [apache/dolphinscheduler#13686]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[master报错日志.txt](https://github.com/apache/dolphinscheduler/files/10906004/master.txt)

### What you expected to happen

don't know

### How to reproduce

don't know

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
<img width="1714" alt="image" src="https://user-images.githubusercontent.com/22415594/223418159-873ceb35-b1cd-4759-a23e-7d46eec1eeee.png">
Your master start failed.
