### ISSUE TITLE
Saving workflow definition leads to status code 413 - request entity too large

### ISSUE THREAD

**Issue by Quinto0** [apache/dolphinscheduler#13685]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Unable to save workflow Status Code: 413 Request Entity Too Large

### What you expected to happen

It's actually a problem with nginx forwarding

### How to reproduce

![image](https://user-images.githubusercontent.com/50733080/223315998-73a2f5e5-1e5b-43e7-9e5b-53cc6a4822c4.png)

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
1,edit the conf file of nginx:
vi /etc/nginx/nginx.conf
add a line in the http, server or location section:

`client_max_body_size 100M;`

2, Doen't use MB it will not work, only the M!

3, Also do not forget to restart nginx
systemctl restart nginx

for detail messages, you can refer to the stackoverflow[1]

1, https://stackoverflow.com/questions/24306335/413-request-entity-too-large-file-upload-issue
