### ISSUE TITLE
[Doc][contribute] How to configure docs.js of docsite to generate dolphinscheduler's document structure

### ISSUE THREAD

**Issue by qindongliang** [apache/dolphinscheduler#13690]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I have followed the documentation [https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/document.md](url) to generate a static site using docsite，But the content of docs.js in the site_config directory is not the site structure of dolphinscheduler, but a demonstration example of docsite itself. How can we quickly generate the configuration structure of dolphinscheduler?

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/7587994/223613078-212a6e77-5f77-4330-8076-7b25dd4e7973.png">

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/7587994/223613173-3151f493-4b3f-4084-ab21-f4dcfcc23288.png">

The page opened by default is not a dolphinscheduler document. How to open it by default is a dolphinscheduler doc, which is very helpful for novices to contribute documents

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@qindongliang May I ask why do u need to generate a static site? What is it for?

**Comment by zhongjiajie** [comment]
Seem https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/document.md  is out of date, you can see the readme in https://github.com/apache/dolphinscheduler-website, when you run command `./scripts/prepare_docs.sh`, the doc config will copy it from https://github.com/apache/dolphinscheduler/tree/dev/docs/configs to your local, you should never create a new file by yourself

**Comment by qindongliang** [comment]
> 

After modifying the dolphinscheduler document, you can see the changes in real time in the browser. The default format of dolphinscheduler is json format, which is not directly edited. It can only be converted to a static site and then use markdown to contribute to the modification

**Comment by qindongliang** [comment]
@EricGao888 After modifying the dolphinscheduler document, you can see the changes in real time in the browser. The default format of dolphinscheduler is json format, which is not directly edited. It can only be converted to a static site and then use markdown to contribute to the modification

**Comment by qindongliang** [comment]
@zhongjiajie Thanks, I'm trying and will close this issue if it works

**Comment by qindongliang** [comment]
@zhongjiajie hi，I executed the ./scripts/prepare_docs.sh script, but the files in https://github.com/apache/dolphinscheduler/tree/dev/docs/configs did not replace the files in site_config, so after executing npm run start , did not achieve the desired effect, I added you on WeChat, please pass

**Comment by qindongliang** [comment]
In the end, I changed the way to add new content directly in dolphinscheduler, which is not practical for website. Note: website is generally used to debug website styles, and the configuration is more complicated, so I suggest you not to use it lightly. thanks @zhongjiajie  for the help
