### ISSUE TITLE
[Improvement][dolphinscheduler-api] Add Unit Test For DynamicTaskTypeController

### ISSUE THREAD

**Issue by jiangyq7** [apache/dolphinscheduler#13701]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jiangyq7** [comment]
3.0.x




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月8日(星期三) 下午3:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/dolphinscheduler] [Improvement][dolphinscheduler-api] Add Unit Test For DynamicTaskTypeController (Issue #13701)






感谢您的反馈，我们已经收到您的问题，请耐心等待回复。

为了让我们尽快了解您的要求，请提供详细的信息、版本或图片。

如果你很久没有收到回复，你可以在加入我们的休闲并将您的问题发送到频道#故障排除

—
直接回复此邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by jiangyq7** [comment]
version is 3.2.0

**Comment by jiangyq7** [comment]
@EricGao888 Could you help me assigne this issue to me and create an Lable or version number?

**Comment by EricGao888** [comment]
> @EricGao888 Could you help me assigne this issue to me and create an Lable or version number?

done

**Comment by jiangyq7** [comment]
Thanks,verr much
