### ISSUE TITLE
[Bug] [api] Run the process directly, and the process instance directly displays stop

### ISSUE THREAD

**Issue by huanzui** [apache/dolphinscheduler#13706]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

上线一个流程，然后直接点击运行流程，查看日志，流程实例直接显示停止，没有进行调度
![image](https://user-images.githubusercontent.com/7300261/223664268-65e6ca95-d67a-48c0-932a-f2f8c95ff7dc.png)
重启master和worker还有api服务后再次点击运行，还是不调度直接显示停止

### What you expected to happen

点击运行流程进行调度

### How to reproduce

直接点击运行流程，查看日志，流程实例直接显示停止，没有进行调度

### Anything else

版本3.0.0

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by huanzui** [comment]
> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.
> 
> ### What happened
> 上线一个流程，然后直接点击运行流程，查看日志，流程实例直接显示停止，没有进行调度 ![image](https://user-images.githubusercontent.com/7300261/223664268-65e6ca95-d67a-48c0-932a-f2f8c95ff7dc.png) 重启master和worker还有api服务后再次点击运行，还是不调度直接显示停止
> 
> ### What you expected to happen
> 点击运行流程进行调度
> 
> ### How to reproduce
> 直接点击运行流程，查看日志，流程实例直接显示停止，没有进行调度
> 
> ### Anything else
> 版本3.0.0
> 
> ### Version
> 3.0.x
> 
> ### Are you willing to submit PR?
> * [ ]  Yes I am willing to submit a PR!
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

发现一个问题，执行策略选择并发 突然就好了，选择其它策略就会出现不执行或直接STOP

**Comment by EricGao888** [comment]
@huanzui Which specific version did u find this issue? I see u wrote the version as `3.0.0` and `3.0.x`. Does it still exist in version `3.0.4`?

**Comment by EricGao888** [comment]
@huanzui BTW, could u plz use English for issue description next time?

**Comment by huanzui** [comment]
> 

v3.0.0

**Comment by EricGao888** [comment]
> > 
> 
> v3.0.0

@huanzui Could u plz give a try in version 3.0.4?

**Comment by huanzui** [comment]
> > > 
> > 
> > 
> > v3.0.0
> 
> @huanzui Could u plz give a try in version 3.0.4?

3.1.6  is ok
