### ISSUE TITLE
[Bug] [api] After the process definition is exported and then imported to another project, the process list displays abnormally

### ISSUE THREAD

**Issue by huanzui** [apache/dolphinscheduler#13711]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

流程定义导出再导入到另一个项目后流程列表显示异常显示不出来

### What you expected to happen

流程定义导出再导入到另一个项目后流程列表显示正常

### How to reproduce

查看了代码，发现导入后流程的version字段未更新到1，导致与之前重复，页面查询到2条相同的两条历史版本

### Version

3.0.0
The problem still exists in 3.1.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@huanzui Would u like to submit a PR to fix it? Could u plz use English for PR description?
