### ISSUE TITLE
[Feature][parameter] Add workflow_instance_id/workflow_id/URI parameter

### ISSUE THREAD

**Issue by piscesvivian** [apache/dolphinscheduler#13710]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add workflow_instance_id or workflow_id or URI as global parameter

### Use case

We use Dolphin Scheduler as task schduler for data process, and develop a additional bussiness data management system and a lightly task record manager。
we'd like to relate [ouer task] to [Dolphin Scheduler Task] by URI。
assume Add workflow_instance_id or workflow_id or URI as global parameter, on each workfow instance create by crontab, in workflow instance we persist it toOUER database

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@piscesvivian Could u plz give a more detailed explanation, better with examples, where u want this workflow_instance_id/workflow_id/URI? BTW, if it is only for ur company's commercial feature, the community is likely to decline this request.

**Comment by piscesvivian** [comment]
Can I set a global paramter like `${workflow_instance_id}` or Custom param `${task_id}`/`${task_instance_id}`  in workflow?
After crontab Task online, is there a way to get instance every time?

can you add more parameters?
All built-in parameter in docs here:
https://dolphinscheduler.apache.org/zh-cn/docs/3.1.4/guide/parameter/built-in
That's 3 in total.
