### ISSUE TITLE
[Bug] [UI] Gantt chart does not display

### ISSUE THREAD

**Issue by meta-ease** [apache/dolphinscheduler#13722]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Workflow ---> Workflow instance, click on the Gantt chart, nothing is displayed on the interface.

### What you expected to happen

Workflow ---> Workflow instance, click on the Gantt chart, there is no display on the interface
![image](https://user-images.githubusercontent.com/12610839/224275139-480c5daf-d6aa-49f3-9fad-d1790decde42.png)
The browser js error is as follows
![image](https://user-images.githubusercontent.com/12610839/224275286-976b1551-87c9-406a-917c-a823e219e907.png)

### How to reproduce

Workflow ---> Workflow instance, click on the Gantt chart
![image](https://user-images.githubusercontent.com/12610839/224275805-fb671b88-3ea8-4efd-b4a7-39a5cfb51e0c.png)

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good job, please describe the issue in English next time
By the way,  I have assigned this issue to you

**Comment by piscesvivian** [comment]
The same problem

**Comment by lxorc** [comment]
@davidzollo Please assign this to me and I will submit a PR today.

**Comment by davidzollo** [comment]
good job

**Comment by davidzollo** [comment]
> @davidzollo Please assign this to me and I will submit a PR today.
Good job 
you can submit a pr, usually we will wait one week if assigned

**Comment by cnfree0355** [comment]
> The same problem

me too !

**Comment by kk467415728** [comment]
Is there a plan to fix this bug in version 3.1.5？

**Comment by lxorc** [comment]
@piscesvivian @kk467415728 @cnfree0355 [[Fix-11583][UI] Fix the API usage of gantt graph by lxorc · Pull Request #13778 · apache/dolphinscheduler](https://github.com/apache/dolphinscheduler/pull/13778)

If you are in a hurry, you can fix this line of code in version 3.1.4. The main problem is that there is a problem with this line of code, although a user submitted a pr, but it is not fully fixed. This link is the pr I submitted and recompiled in 3.1.4 to work well.

**Comment by lxorc** [comment]
> Is there a plan to fix this bug in version 3.1.5？



> > @davidzollo Please assign this to me and I will submit a PR today.
> > Good job
> > you can submit a pr, usually we will wait one week if assigned

[[Fix-11583][UI] Fix the API usage of gantt graph by lxorc · Pull Request #13778 · apache/dolphinscheduler](https://github.com/apache/dolphinscheduler/pull/13778)

Thanks a lot, hope to fix this bug in 3.1.5, Gantt charts are a very useful and important feature.

**Comment by woxiangwoshi123** [comment]
> @piscesvivian @kk467415728 @cnfree0355 [[Fix-11583][UI] 修复 lxorc 对甘特图的 API 使用 · Pull Request #13778 · apache/dolphinscheduler](https://github.com/apache/dolphinscheduler/pull/13778)
> 
> 3.1.4版本版本版本修复这。主要这行代码代码有代码后运行良。

I tried it, but it failed. I did not find the corresponding code in 3.1.4, please check again

> @piscesvivian @kk467415728 @cnfree0355 [[Fix-11583][UI] Fix the API usage of gantt graph by lxorc · Pull Request #13778 · apache/dolphinscheduler](https://github.com/apache/dolphinscheduler/pull/13778)
> 
> If you are in a hurry, you can fix this line of code in version 3.1.4. The main problem is that there is a problem with this line of code, although a user submitted a pr, but it is not fully fixed. This link is the pr I submitted and recompiled in 3.1.4 to work well.

I tried it, but it failed. I did not find the corresponding code in 3.1.4, please check again

**Comment by WilliamChen-luckbob** [comment]
just meet the same problem in version 3.1.4 for a simple test dag.

**Comment by lxorc** [comment]
> [Fix-11583][UI] Fix the API usage of gantt graph by lxorc · Pull Request #13778 · apache/dolphinscheduler

#13778
