### ISSUE TITLE
[Improvement][components]manaco-editor support SQL format and prompt

### ISSUE THREAD

**Issue by huangyx001** [apache/dolphinscheduler#13755]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I know dolphinscheduler support many language editor and also support SQL，but can't support SQL format and prompt, I hope support SQL format(use sql-formatter) and prompt

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
Good idea. But currently the community does not have enough hands for front-end stuff. Would u like to give a shot?

**Comment by huangyx001** [comment]
I can try it, but it's  too big，I am worried about problems

**Comment by huangyx001** [comment]
> Good idea. But currently the community does not have enough hands for front-end stuff. Would u like to give a shot?

I can try it, but it's too big，I am worried about problems

**Comment by EricGao888** [comment]
> > Good idea. But currently the community does not have enough hands for front-end stuff. Would u like to give a shot?
> 
> I can try it, but it's too big，I am worried about problems

You may divide it in to several sub issues and complete them step by step : )
