### ISSUE TITLE
[Bug] [Module Name] worker.registry-disconnect-strategy.max-waiting-time is set to 0 and will not wait infinitely.

### ISSUE THREAD

**Issue by cscsyiku123** [apache/dolphinscheduler#13753]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/43720485/225322992-3d7dc2a7-27b3-4928-910b-eff9a3d1430c.png">
<img width="827" alt="image" src="https://user-images.githubusercontent.com/43720485/225319509-1c7d8830-c5d9-4982-8428-cd8aa050c60a.png"> 这个设置成0 并不会 无限等待，因为 这个 不是null,
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/43720485/225322484-0de91009-694f-408a-b6ec-3d6a82372510.png">
。或者 这是 一个curator 框架的bug，因为 他的 注释里没有提到单位为null才会无限等待。

### What you expected to happen

如题如题如题如题如题如题如题如题

### How to reproduce

如题如题如题如题如题如题如题如题

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@cscsyiku123 Could u plz write issue in English next time? 
![image](https://user-images.githubusercontent.com/34905992/225325153-0c0ba6d6-ae2e-469b-b27b-f0aa0cdb0b00.png)

**Comment by caishunfeng** [comment]
> @cscsyiku123 Could u plz write issue in English next time? ![image](https://user-images.githubusercontent.com/34905992/225325153-0c0ba6d6-ae2e-469b-b27b-f0aa0cdb0b00.png)

+1, I will close this issue.
