### ISSUE TITLE
[Bug] Dependent components cannot be justified and viewed (dependent components cannot be edited and viewed)

### ISSUE THREAD

**Issue by shengxiagit** [apache/dolphinscheduler#13756]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### 从2.0.5升级到3.1.4之后，原有的"dependent"组件无法查看和编辑，但是新建流程不受影响
<img width="818" alt="依赖组件无法编辑" src="https://user-images.githubusercontent.com/41880771/225487447-6d2e62c5-db24-4436-9a62-03c13b2dcc5c.png">

### What you expected to happen

原有的"dependent"组件可以查看和编辑

### How to reproduce

从2.0.5升级到3.1.4后即可复现

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by woxiangwoshi123** [comment]
> .0.5升级到3.1.4后即可恢复

I have the same problem, please fix it ASAP.

**Comment by AmriStrong** [comment]
我也有3.1.7版本

**Comment by shengxiagit** [comment]
可以通过 下线工作流 -> 编辑工作流 看到依赖
