### ISSUE TITLE
[Bug] [Module Name] Master and Worker nodes often hang up without reason!

### ISSUE THREAD

**Issue by Sdreamery** [apache/dolphinscheduler#13772]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Version 3.1.2. Recently, master and worker hang up frequently. The log shows that the master/worker hangs up and needs to be recovered. However, during the recovery process, master/worker seems to be good again, resulting in the port being occupied and unable to restart. Please help us to have a look. I'm worried, please!
[master_error_log.txt](https://github.com/apache/dolphinscheduler/files/11024039/master_error_log.txt)
[woker_error_log.txt](https://github.com/apache/dolphinscheduler/files/11024040/woker_error_log.txt)

### What you expected to happen

I think it may be a problem with Zookeeper.

### How to reproduce

DS-3.1.2伪集群，zookeeper-3.8.0

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by eye-gu** [comment]
Can you find the "netty server close" in the log? Post the log before the error is reported

**Comment by Sdreamery** [comment]
yes I can. But what should I do next?
![ccffc4cb4c11afe463addce035f9c07](https://user-images.githubusercontent.com/38490969/226772168-fa1f1228-9540-46ce-a1f4-b7e31fcf0de6.png)

**Comment by eye-gu** [comment]
> yes I can. But what should I do next? ![ccffc4cb4c11afe463addce035f9c07](https://user-images.githubusercontent.com/38490969/226772168-fa1f1228-9540-46ce-a1f4-b7e31fcf0de6.png)

Can you post  complete log?

**Comment by EricGao888** [comment]
@Sdreamery How many workers / masters did u start in one machine as you deployed DS in pseudo-cluster mode?

**Comment by k9flame** [comment]
I have the same problem，Is there a way to solve？
