### ISSUE TITLE
[Bug] [server] task instance host is null

### ISSUE THREAD

**Issue by Chris-playground** [apache/dolphinscheduler#13776]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

dolphinscheduler version 3.0.0.
We have a workflow that made up with serval child workflows and it scheduled to execute at 5am.
![image](https://user-images.githubusercontent.com/48941586/226777987-a7b539ac-1e43-4690-b8f9-15abec336cd0.png)

However it stuck by one child workflow which status is always `Submitted successfully`
![image](https://user-images.githubusercontent.com/48941586/226777935-df36bc01-3d7f-4915-b53d-486f3308a6e3.png)
While we enter this child node, all the tasks were executed successfully.
![image](https://user-images.githubusercontent.com/48941586/226778499-43ee2e98-e27a-4722-be5b-bd8440803e20.png)

![image](https://user-images.githubusercontent.com/48941586/226778408-574791ec-484b-49a9-b3fb-70ba9d30d22d.png)

Then, we click the link `view log` and it shows no log with an error message like `task instance host is null`.
![image](https://user-images.githubusercontent.com/48941586/226778675-6851f86d-569f-4887-8678-6f335e2a632f.png)

After that, we click the link `view history` it shows like this
![image](https://user-images.githubusercontent.com/48941586/226778905-68bdd1f2-fba8-44f0-aae5-9fad47fcc6c0.png)

This problem happens time to time, it is really annoying that it will stuck the workflow and we need to check one by one.

### What you expected to happen

this sub workflow should success or fail instead of submit success

### How to reproduce

can't be reproduced 100%

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
hi@Chris-Arith Can you find the following statement in the log？：
![image](https://user-images.githubusercontent.com/33984497/226789278-8ebb048e-2653-4817-b8f1-c0f6434a97e4.png)

**Comment by fuchanghai** [comment]
hi @caishunfeng
![image](https://user-images.githubusercontent.com/33984497/226789461-571ce75f-9cb8-4605-8b42-e3f9bd18d301.png)

If it fails, will the timed task work?

**Comment by Chris-playground** [comment]
> hi@Chris-Arith Can you find the following statement in the log？： ![image](https://user-images.githubusercontent.com/33984497/226789278-8ebb048e-2653-4817-b8f1-c0f6434a97e4.png)

hi, thanks for your kindly replay.
I have checked all the logs in master and api nodes, there was no site of this error message.
However, I found a statement like `org.apache.dolphinscheduler.server.master.event.StateEventHandleException: Task state event handle error, due to the task is not in activeTaskProcessorMaps`

**Comment by Chris-playground** [comment]
@EricGao888 Hi, good day. Can you help us with this problem please.

**Comment by EricGao888** [comment]
> @EricGao888 Hi, good day. Can you help us with this problem please.

For those tasks which had no hosts, could u check what had happened to the previous hosts they assigned with? Had there been any events like worker failover?

**Comment by Chris-playground** [comment]
> > @EricGao888 Hi, good day. Can you help us with this problem please.
> 
> For those tasks which had no hosts, could u check what had happened to the previous hosts they assigned with? Had there been any events like worker failover?

@EricGao888 hi, the previous hosts are all working normally with no errors.

**Comment by Chris-playground** [comment]
help, please

**Comment by chenshuai1995** [comment]
mark

**Comment by WYPOWLS** [comment]
mark

**Comment by WYPOWLS** [comment]
I'm using version 3.2 and I'm having the same problem, it's amazing that it hasn't been fixed yet!
