### ISSUE TITLE
[Bug] [Master-Server cpu always  over 60%] Bug title 

### ISSUE THREAD

**Issue by ZiaZiaZiaZia** [apache/dolphinscheduler#13774]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

master-server节点cpu常驻在60%以上，master日志频繁更新报错，master日志量巨大。

[ERROR] 2023-03-21 14:30:14.655 +0800 org.apache.dolphinscheduler.server.master.event.WorkflowStartEventHandler:[74] - [WorkflowInstance-0][TaskInstance-0] - Failed to submit the workflow instance, will resend the workflow start event: WorkflowEvent(workflowEventType=START_WORKFLOW, workflowInstanceId=97)
[ERROR] 2023-03-21 14:30:14.655 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[685] - [WorkflowInstance-100][TaskInstance-0] - Start workflow error
[ERROR] 2023-03-21 14:30:14.655 +0800 org.apache.dolphinscheduler.server.master.event.WorkflowStartEventHandler:[74] - [WorkflowInstance-0][TaskInstance-0] - Failed to submit the workflow instance, will resend the workflow start event: WorkflowEvent(workflowEventType=START_WORKFLOW, workflowInstanceId=100)
[ERROR] 2023-03-21 14:30:14.655 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[685] - [WorkflowInstance-97][TaskInstance-0] - Start workflow error
[ERROR] 2023-03-21 14:30:14.655 +0800 org.apache.dolphinscheduler.server.master.event.WorkflowStartEventHandler:[74] - [WorkflowInstance-0][TaskInstance-0] - Failed to submit the workflow instance, will resend the workflow start event: WorkflowEvent(workflowEventType=START_WORKFLOW, workflowInstanceId=97)

### What you expected to happen

不知道是不是workflow配置的有问题

### How to reproduce

如果是BUG的话请告诉我升级到哪一个版本可以解决。或者可以做哪些参数优化或操作上规避

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ZiaZiaZiaZia** [comment]
sloved

**Comment by ZiaZiaZiaZia** [comment]
参考另一个issue
https://github.com/apache/dolphinscheduler/discussions/11918

**Comment by EricGao888** [comment]
Closed due to https://github.com/apache/dolphinscheduler/issues/13774#issuecomment-1477428266
