### ISSUE TITLE
[Bug] [Master] Data-Complement Fail strategy CONTINUE not working

### ISSUE THREAD

**Issue by piscesvivian** [apache/dolphinscheduler#13783]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When crontab set to:

0 20 8,20 * * ? *

Data-Complement ENABLE
Fail strategy Continue
Schedule for one month tasks

when TASK in some day failed, it won't continue.

Version: apache-dolphinscheduler-3.1.3

### What you expected to happen

Data-Complement Continue run when Fail strategy set to CONTINUE 

### How to reproduce

0 20 8,20 * * ? *

Data-Complement ENABLE
Fail strategy Continue
Schedule for one month tasks

Try Fail task

simplely like a shell task

```
[[ $(date +%H) -eq 20 ]] && exit 1
```

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
>when TASK in some day failed, it won't continue.

Do you use serial complement or parallel degree complement? It seems some workflow instance fail, and it will not to add the next complement command.

**Comment by piscesvivian** [comment]
> Do you use serial complement or parallel degree complement?

I use parallel degree complement, parallel set to 5, 3 of them success, but two of them were blocked by a failed workflow instance(i.e.: 2022-02-06, this day original data is loss, it won't success) . I need to re-config schedule time to skip the failed one.



I read the document again, and realized the Fail Strategy is not for Data-Complement，just for workflow instance. Can this be a feature for Data-Complement? It will be useful for no data relation workflow, when a lots of task need to be complete.
