### ISSUE TITLE
[Bug] [API] when param contain ')'  ,is wiill lost

### ISSUE THREAD

**Issue by QiuMingJie** [apache/dolphinscheduler#13782]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I try to send a param ，
the command output string like this :
${setValue(sqls=" INSERT INTO zf_adas_data_upload_log  (finish_time, file_path, costs) VALUES  ('2023-03-22 21:42','/home/dolphinscheduler/Data/zzz/Vinfast BEV/azure/CompressedFile/EU/LS185/2023-03-21/0001/VF_PR59175_E35_LS185_CAM07A00_MRR06A05_2022_12_01_095835#CANape20_log_297_mf4.7z','16.61552381515503s');")}

but I can not work

### What you expected to happen

No parenthesis recursion check is done

### How to reproduce

use param include ”()”

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi, @QiuMingJie, thanks for your feedback, i'll fix it.

**Comment by QiuMingJie** [comment]
thanks



---- Replied Message ----
| From | Aaron ***@***.***> |
| Date | 03/23/2023 09:46 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [apache/dolphinscheduler] [Bug] [API] when param contain ')' ,is wiill lost (Issue #13782) |

Hi, @QiuMingJie, thanks for your feedback, i'll fix it.
