### ISSUE TITLE
[Bug] [scheduled task] Once the scheduled task goes online, it will run without authorization

### ISSUE THREAD

**Issue by Menffy** [apache/dolphinscheduler#13786]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

f*ck, I am so sorry to say that, but it make me so angry. Once the scheduled task goes online, it will run without authorization, it bothers me, this is not what i expected.

定时任务设置后一旦点击定时任务上线，就擅自运行了。我仅仅只是为了上线而不是要运行, 这令我十分困扰。

### What you expected to happen

Do not run the scheduled task without authorization after it goes online

定时任务上线后，不要运行。

### How to reproduce

Set a timed task, then click Go Online, and after a while you will find that the task runs without authorization

随意设置一个定时任务，然后点击上线，稍等一会即可发现任务擅自运行。

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@Menffy May I ask which specific version or versions of 3.0.x you found this bug?

**Comment by Menffy** [comment]
@EricGao888，version of 3.0.3

**Comment by Radeity** [comment]
Hi, @Menffy , this bug has already been fixed, maybe will release in next 3.0.x version (related issue https://github.com/apache/dolphinscheduler/issues/13089, https://github.com/apache/dolphinscheduler/issues/13286)

**Comment by Menffy** [comment]
@Radeity Thanks you.
