### ISSUE TITLE
[Bug] [API] Process instance DAG can't show dependent task

### ISSUE THREAD

**Issue by ralphgj** [apache/dolphinscheduler#13780]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Hi，I found that the dependent tasks in the DAG of the process instance cannot be displayed. 
<img width="1642" alt="image" src="https://user-images.githubusercontent.com/7887053/226829498-c5a965e2-6e2e-42fd-8da8-418bfff4bc64.png">

<img width="1625" alt="image" src="https://user-images.githubusercontent.com/7887053/226829465-1a259110-3ca4-4880-87f2-f01ca74e8c1a.png">

I think it should be caused by the modification of the log format in this [PR](https://github.com/apache/dolphinscheduler/pull/10593/files). 
<img width="1725" alt="image" src="https://user-images.githubusercontent.com/7887053/226829272-8b1b5c14-4ef1-4459-81e8-db49e105a88e.png">
In the `ProcessInstanceServiceImpl#parseLogForDependentResult` method, it appears to attempt parsing the running result of the dependent task using the `DEPENDENT_SPLIT` constant. Additionally, the running result in the log has been modified. So the parse method will not work too.

### What you expected to happen

The process instance DAG displays dependent tasks in the same way as the process definition DAG.

### How to reproduce

Create two process definitions like the following screenshots.
<img width="1618" alt="image" src="https://user-images.githubusercontent.com/7887053/226830695-548ccdec-64e0-4328-b339-d4aba67401f0.png">
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/7887053/226830775-b6983bf6-7f51-4382-bd52-8f5d8c8f137d.png">
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/7887053/226830819-a8ec1726-a96b-4a70-833e-083c5985f568.png">

### Version

3.1.4

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by woxiangwoshi123** [comment]
> 感谢您的反馈，我们已收到您的问题，请耐心等待回复。
> 
> * 为便于我们尽快了解您的需求，请提供详细信息、版本或图片。
> * 如果你很久没有收到回复，你可以[加入我们的slack](https://s.apache.org/dolphinscheduler-slack)，把你的问题发到channel`#troubleshooting`

I have the same problem, please fix it ASAP.

**Comment by Cocytus316** [comment]
hi，gugs.My dolphinscheduler version is 3.1.7.But I still have the same problem.
![image](https://github.com/apache/dolphinscheduler/assets/65262824/c2328cb4-183e-4d7f-bf23-00cc9cafaf61)
![image](https://github.com/apache/dolphinscheduler/assets/65262824/591e2560-a30e-49e7-8b21-9913a87d537c)

**Comment by woxiangwoshi123** [comment]
> hi，gugs.我的dolphinscheduler版本是3.1.7.但是我还是有同样的问题。 ![图像](https://user-images.githubusercontent.com/65262824/242509874-c2328cb4-183e-4d7f-bf23-00cc9cafaf61.png) ![图像](https://user-images.githubusercontent.com/65262824/242509941-591e2560-a30e-49e7-8b21-9913a87d537c.png)

me too
