### ISSUE TITLE
[Bug] [task dependency] dependency task can't retry

### ISSUE THREAD

**Issue by ziqiang-wang** [apache/dolphinscheduler#13797]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The workflow definition contains a task of a dependency type. Set Retry Times to 3 and Retry Interval to 1 minute. Enable Timeout Alarm, enable Wait for Dependency Completion, set Timeout to 1 minute, and select Timeout Policy to Timeout Failure, as shown in the following figure:

![image](https://user-images.githubusercontent.com/107013241/227882237-5c31de77-3271-4d4a-b876-799ddaf7a2cc.png)

I then manually execute the workflow and select "Failure Policy" as "Continue" and execute the workflow as shown below:

<img width="660" alt="image" src="https://user-images.githubusercontent.com/107013241/227925760-9062c9d1-545d-4d5e-9e1d-3dd9b729be1c.png">

During execution, it was found that the dependent task did fail after a 1 minute timeout, but after another 1 minute, it was not retried (3 failed retries have been set up above), and the workflow instance was always running. After manually stopping a workflow instance, the workflow instance remains in the ready to stop state.

I also tried to change the number of failed retries to 0 and then run it again manually, and found that the workflow instance was still running after the dependent task failed to time out the first time.

### What you expected to happen

1. A workflow has a dependency task. If the dependency task fails to time out during workflow execution, you can retry the workflow based on the set retry times and interval.
2. If a dependent task fails to run eventually, the entire workflow can continue to run subsequent tasks or stop running directly according to the set running policy.

### How to reproduce

Create a workflow definition where the first task type is a dependent task, which is dependent on any task that is not executed today, so that when the dependent task runs, it can time out and fail. Then enable the timeout alarm for the dependent task and wait for the dependency to complete, and set the timeout failure to the timeout policy.
Followed by any other type of task, such as a shell.
After saving the work definition and executing the workflow manually, you should see that the dependency failed to time out, but was not retried, and the corresponding workflow instance was always running. Manually stopping a workflow instance does not stop the workflow completely, but is always in a state of ready to stop.

### Version

3.1.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Is anyone interested in this issue? can try to fix

**Comment by fuchanghai** [comment]
@ziqiang-wang I see that your final results are the same. Is your log the same as this issue? #13956

**Comment by ziqiang-wang** [comment]
> @ziqiang-wang I see that your final results are the same. Is your log the same as this issue? #13956

I don't understand what you're asking

**Comment by ziqiang-wang** [comment]
> @ziqiang-wang I see that your final results are the same. Is your log the same as this issue? #13956

It's not the same question.
My problem with dependent tasks is that a failed task does not trigger a retry, and the workflow instance is always running.
