### ISSUE TITLE
[Doc][Task Plugin] Update DS ST task plugin docs

### ISSUE THREAD

**Issue by HudsonShi** [apache/dolphinscheduler#13795]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

[link](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/guide/task/seatunnel.md)
and
[link](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/zh/guide/task/seatunnel.md)
is already outdated. Let me update them into a new version.

### Documentation Links

https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/guide/task/seatunnel.md
https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/zh/guide/task/seatunnel.md

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@HudsonShi Great. Looking forward to your contributions : )
