### ISSUE TITLE
[Feature][dolphinscheduler-api] Add IDE online debugging function, and can output logs in real time

### ISSUE THREAD

**Issue by magic20191** [apache/dolphinscheduler#13790]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add WEB IDE online debugging function, and can output logs in real time, like navicat

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
We have https://github.com/apache/dolphinscheduler-studio repo WIP for online debugging / task development. If you are interested, you could contribute to that repo.
