### ISSUE TITLE
[Feature][Task Plugin] RemoteShell Task Plugin

### ISSUE THREAD

**Issue by jieguangzhou** [apache/dolphinscheduler#13794]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

A new task plugin, this allows us to run tasks on machines that do not have worker installed

### Use case

![](https://user-images.githubusercontent.com/31528124/226569941-c9a36718-ef5c-4175-a6d0-5c0dad3ab647.png)

![](https://user-images.githubusercontent.com/31528124/226570059-de326368-267c-4368-840b-2089d405e185.png)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jieguangzhou** [comment]
It's similar to this, but here it runs as a component https://github.com/apache/dolphinscheduler/pull/12736

**Comment by EricGao888** [comment]
@jieguangzhou Great! Looking forward to this feature. 

Also I have a couple of questions:
1. How to monitor the status of tasks after DS submits them to remote machine?
2. How to stop / kill / restart ssh tasks?
3. How to manage resource files of ssh tasks?

BTW, I see you label this feature with 4.0.0-alpha, why not 3.2.0?

**Comment by jieguangzhou** [comment]
> @jieguangzhou Great! Looking forward to this feature.
> 
> Also I have a couple of questions:
> 
> 1. How to monitor the status of tasks after DS submits them to remote machine?
> 2. How to stop / kill / restart ssh tasks?
> 3. How to manage resource files of ssh tasks?
> 
> BTW, I see you label this feature with 4.0.0-alpha, why not 3.2.0?

I want to use [Apache MINA SSHD](https://github.com/apache/mina-sshd) to run commands on the remote machine.
1.  I plan to give a special identifier to the program when it runs, such as "dolphinscheduler-remoteshell". Later, to monitor the program, we just need to check if there are processes with this identifier (for example, using the command "ps -ef | grep dolphinscheduler-remoteshell-taskid"). Additionally, the program's logs will be stored in a specific path on the remote machine, and the task status will be monitored by combining the process status with the logs.
2. For process management, we can use Mina-sshd to send the corresponding commands to the server, such as "kill -9".
3. I haven't dealt with resource files yet because I assumed from the beginning that the program would be running on a remote server that already has all the required resources, such as environment, data, and resource files.

**Comment by jieguangzhou** [comment]
> @jieguangzhou Great! Looking forward to this feature.
> 
> Also I have a couple of questions:
> 
> 1. How to monitor the status of tasks after DS submits them to remote machine?
> 2. How to stop / kill / restart ssh tasks?
> 3. How to manage resource files of ssh tasks?
> 
> BTW, I see you label this feature with 4.0.0-alpha, why not 3.2.0?

 I  have already updated the label to 3.2.

**Comment by Radeity** [comment]
> 3. I haven't dealt with resource files yet because I assumed from the beginning that the program would be running on a remote server that already has all the required resources, such as environment, data, and resource files.

It seems like we can also use [sshd-scp](https://github.com/apache/mina-sshd/blob/master/docs/scp.md) provided by [Apache MINA SSHD](https://github.com/apache/mina-sshd) to send resources files managed by DS to remote machine.
