### ISSUE TITLE
[Bug] [task-api]The shell cannot be executed under Windows 10

### ISSUE THREAD

**Issue by klaokai** [apache/dolphinscheduler#13807]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I deployed Standalone Server on Windows 10 for testing, I found that the shell task node would fail to execute. The process will stay at the task node.

log:
[INFO] 2023-03-28 19:59:06.154 +0800 - 
***********************************************************************************************
*********************************  Initialize task context  ***********************************
***********************************************************************************************

[INFO] 2023-03-28 19:59:06.171 +0800 - Begin to initialize task
[INFO] 2023-03-28 19:59:06.171 +0800 - Set task startTime: 1680004746171
[INFO] 2023-03-28 19:59:06.171 +0800 - Set task appId: 1_1
[INFO] 2023-03-28 19:59:06.171 +0800 - End initialize task {
  "taskInstanceId" : 1,
  "taskName" : "214142141",
  "firstSubmitTime" : 1680004746045,
  "startTime" : 1680004746171,
  "taskType" : "SHELL",
  "host" : "193.168.199.220:1234",
  "logPath" : "E:\\gitpro\\DolphinScheduler\\logs\\20230328\\9033515602688\\1\\1\\1.log",
  "processId" : 0,
  "processDefineCode" : 9033515602688,
  "processDefineVersion" : 1,
  "processInstanceId" : 1,
  "scheduleTime" : 0,
  "executorId" : 2,
  "cmdTypeIfComplement" : 0,
  "tenantCode" : "KKKK",
  "queue" : "default",
  "processDefineId" : 0,
  "projectId" : 0,
  "projectCode" : 9033513615488,
  "taskParams" : "{\"localParams\":[],\"rawScript\":\"echo A\",\"resourceList\":[]}",
  "taskAppId" : "1_1",
  "taskTimeout" : 2147483647,
  "workerGroup" : "default",
  "delayTime" : 0,
  "currentExecutionStatus" : "SUBMITTED_SUCCESS",
  "endTime" : 0,
  "resources" : { },
  "dryRun" : 0,
  "paramsMap" : { },
  "cpuQuota" : -1,
  "memoryMax" : -1,
  "testFlag" : 0,
  "logBufferEnable" : false
}
[INFO] 2023-03-28 19:59:06.172 +0800 - 
***********************************************************************************************
*********************************  Load task instance plugin  *********************************
***********************************************************************************************

[INFO] 2023-03-28 19:59:06.178 +0800 - Set task status to TaskExecutionStatus{code=1, desc='running'}
[INFO] 2023-03-28 19:59:06.264 +0800 - TenantCode:KKKK check success
[INFO] 2023-03-28 19:59:06.270 +0800 - ProcessExecDir:/tmp/dolphinscheduler/exec/process/KKKK/9033513615488/9033515602688_1/1/1 check success
[INFO] 2023-03-28 19:59:06.270 +0800 - Resources:{} check success
[INFO] 2023-03-28 19:59:06.278 +0800 - Task plugin: SHELL create success
[INFO] 2023-03-28 19:59:06.280 +0800 - Initialize shell task params {
  "localParams" : [ ],
  "varPool" : null,
  "rawScript" : "echo A",
  "resourceList" : [ ]
}
[INFO] 2023-03-28 19:59:06.280 +0800 - Success initialized task plugin instance success
[INFO] 2023-03-28 19:59:06.280 +0800 - Success set taskVarPool: null
[INFO] 2023-03-28 19:59:06.285 +0800 - 
***********************************************************************************************
*********************************  Execute task instance  *************************************
***********************************************************************************************

[INFO] 2023-03-28 19:59:06.288 +0800 - raw script : echo A
[INFO] 2023-03-28 19:59:06.289 +0800 - task execute path : /tmp/dolphinscheduler/exec/process/KKKK/9033513615488/9033515602688_1/1/1
[INFO] 2023-03-28 19:59:06.293 +0800 - Begin to create command file:/tmp/dolphinscheduler/exec/process/KKKK/9033513615488/9033515602688_1/1/1/1_1.bat
[INFO] 2023-03-28 19:59:06.295 +0800 - Success create command file, command: @echo off
cd /d %~dp0
/tmp/dolphinscheduler/exec/process/KKKK/9033513615488/9033515602688_1/1/1/1_1_node.bat
[INFO] 2023-03-28 19:59:06.347 +0800 - task run command: cmd.exe /tmp/dolphinscheduler/exec/process/KKKK/9033513615488/9033515602688_1/1/1/1_1.bat
[ERROR] 2023-03-28 19:59:06.349 +0800 - Get task pid failed
java.lang.NoSuchFieldException: pid
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.getProcessId(AbstractCommandExecutor.java:386)
	at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.run(AbstractCommandExecutor.java:216)
	at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.handle(ShellTask.java:93)
	at org.apache.dolphinscheduler.server.worker.runner.DefaultWorkerDelayTaskExecuteRunnable.executeTask(DefaultWorkerDelayTaskExecuteRunnable.java:56)
	at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecuteRunnable.run(WorkerTaskExecuteRunnable.java:168)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
[INFO] 2023-03-28 19:59:06.349 +0800 - process start, process id is: 0
[INFO] 2023-03-28 19:59:07.349 +0800 -  -> 'yle' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
	���������ļ���
	

### What you expected to happen

shell can be execute.

### How to reproduce

Create a process for a shell task node and initiate a run.

### Anything else

There are two errors, one of which is a cmd error

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@klaokai Thanks for submitting this issue. However, currently we don't have a plan to support running DS on windows. Therefore, I will close it temporarily.

**Comment by klaokai** [comment]
> @klaokai Thanks for submitting this issue. However, currently we don't have a plan to support running DS on windows. Therefore, I will close it temporarily.

ok
