### ISSUE TITLE
The task execution parameters depList and preTasks in the t_ds_task_instance table are duplicated

### ISSUE THREAD

**Issue by JackIllkid** [apache/dolphinscheduler#1380]
参数测试中发现task_instance表中的参数depList和preTasks是重复参数，保留其一就可以了
![07ddff34f01887b5fb15acb1ce4870e](https://user-images.githubusercontent.com/38174237/70019602-c3bdf180-15c4-11ea-8f95-22d38cc7a83e.png)

**Comment by lenboo** [comment]
@JackIllkid 
for english only, please update the title and content to english.

**Comment by JackIllkid** [comment]
OK,I'll revise it later.

发自我的 iPhone

在 2019年12月4日，下午7:53，bao liang <notifications@github.com<mailto:notifications@github.com>> 写道：


@JackIllkid<https://github.com/JackIllkid>
for english only, please update the title and content to english.
