### ISSUE TITLE
[Improvement][storage-hdfs]  first getDefaultFS  change FS_DEFAULT_FS to HDFS_DEFAULT_FS

### ISSUE THREAD

**Issue by zhaifb** [apache/dolphinscheduler#13804]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I think  ' getConfiguration().get(Constants.FS_DEFAULT_FS)'  is try to get  'fs.defaultFS' from  core-site.xml/hdfs-site.xml

the  FS_DEFAULT_FS = "resource.hdfs.fs.defaultFS" ,  **but   core-site.xml/hdfs-site.xml has none 'resource.hdfs.fs.defaultFS'.**

so i think ,it  can be change to  'getConfiguration().get(Constants.HDFS_DEFAULT_FS)'

HDFS_DEFAULT_FS = "fs.defaultFS";

```java
# org/apache/dolphinscheduler/plugin/storage/hdfs/HdfsStorageOperator.java:183

public String getDefaultFS() {
        String defaultFS = getConfiguration().get(Constants.FS_DEFAULT_FS);
        if (StringUtils.isBlank(defaultFS)) {
            defaultFS = hdfsProperties.getDefaultFS();
        }
        return defaultFS;
    }
````

i thiank it can be change to the folloing.

```
public String getDefaultFS() {
        String defaultFS = getConfiguration().get(Constants.HDFS_DEFAULT_FS);
        if (StringUtils.isBlank(defaultFS)) {
            defaultFS = hdfsProperties.getDefaultFS();
        }
        return defaultFS;
    }

```
  

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Good catch.
