### ISSUE TITLE
[Bug] [complement task] complement task can not continue

### ISSUE THREAD

**Issue by ShawshankLin** [apache/dolphinscheduler#13817]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

the complement task is fail, after a successful re-run, won't run the rest of the day.

### What you expected to happen

continue run the rest of day

### How to reproduce

rare case...

### Version

2.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
Please check,  I think you should use Recovery Failed in this situation, re-run is only valid for one process instance.
