### ISSUE TITLE
[Bug] [Master] worker worker have not received the heartbeat

### ISSUE THREAD

**Issue by lxorc** [apache/dolphinscheduler#13837]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The `worker` worker Is inconsistent with the ip addr requirement.

```
2023-03-31 00:40:51 | [WARN] 2023-03-31 00:40:51.139 org.apache.dolphinscheduler.server.master.dispatch.host.LowerWeightHostManager:[132] - [WorkflowInstance-0][TaskInstance-0] - worker worker in work group default have not received the heartbeat
```
and a another key log like this  
```
[INFO] 2023-03-27 19:47:47.186 org.apache.dolphinscheduler.server.master.registry.ServerNodeManager:[197] - [WorkflowInstance-0][TaskInstance-0] - Worker: /nodes/worker added, currentNode : worker
```

### What you expected to happen

There are no invalid WARN logs

### How to reproduce

A started standalone cluster.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zui01** [comment]
i meet the same problem

**Comment by niunan2019** [comment]
me too  , same problem, how to deal with it ?
