### ISSUE TITLE
[Bug] [Module Name] Bug title 

### ISSUE THREAD

**Issue by wuxiangdong** [apache/dolphinscheduler#13879]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

第一次安装ds,修改zkRoot变量不起作用
install_env.sh
zkRoot="/dstest"

启动后还是注册到zookeeper中的/dolphinscheduler

### What you expected to happen

安装的时候可以注册到zkRoot指定的目录上

### How to reproduce

安装部署的时候

### Anything else

没有

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
Could u plz add a brief description in issue title and use English only for issue description? Thx
