### ISSUE TITLE
[Bug] [Workflow] Import workflow failed

### ISSUE THREAD

**Issue by N1ghtw15h** [apache/dolphinscheduler#13904]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Exported a workflow in one project and encountered an error while importing another project.
在一个项目导出了一个工作流，在导入另一个项目时报错。
![9d66438f8dc1a0c40c2ae460361c886](https://user-images.githubusercontent.com/44601037/231042003-3d556ce9-e81f-4793-af8a-ca0f323ece98.png)

### What you expected to happen

Ability to import workflows correctly.
能够正确导入工作流。

### How to reproduce

Export a workflow in one project, and then import the JSON file from the previously exported workflow in another project.
在一个项目导出一个工作流，然后在另一个项目里将之前导出工作流的json文件导入。

### Anything else

The workflow exported in the same project can be successfully imported. Is it because there is a projectCode in the JSON file of the exported workflow that it cannot be imported into another project?
在同一个项目中导出的工作流，可以成功导入。是不是因为导出工作流的json文件里有projectCode，所以不能导入到另一个项目中？

The error message prompt is t_ ds_ The id field in the schedules table is duplicated, but importing in the same project does not have this issue.
报错信息提示是t_ds_schedules表的id字段重复，但是在同一项目中导入没有这个问题。
![image](https://user-images.githubusercontent.com/44601037/231335859-16dcb955-df94-4813-897f-ec35404c13f0.png)

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rickchengx** [comment]
* the `projectCode` will be overridden when importing the workflow
* and the primary_key `id` of `t_ds_schedules` is AUTO_INCREMENT
