### ISSUE TITLE
[Improvement][WEBSITE] update homepage image

### ISSUE THREAD

**Issue by iris20210628** [apache/dolphinscheduler#13908]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add an image about 'creating dags by Python' on the homepage to stress this function like this:
![image](https://user-images.githubusercontent.com/86594831/231067691-fba35fa2-6232-4fba-8357-f6d0e113d768.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
fix in https://github.com/apache/dolphinscheduler-website/pull/895
