### ISSUE TITLE
[Bug] [DataX] sqlserverwriter Escape symbol problem

### ISSUE THREAD

**Issue by GHxiaotan** [apache/dolphinscheduler#13916]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When using the DataX module，Sqlserverwriter used the wrong transfer symbol，Make it impossible for the work to continue。
![Snipaste_2023-04-12_15-35-59](https://user-images.githubusercontent.com/38999030/231385994-be724304-4474-4e1f-8788-8b8efdc72fcb.png)

### What you expected to happen

Remove the wrong escape symbol

### How to reproduce

Using the Datax module, any data source is written to SQLServer
![Snipaste_2023-04-12_15-38-31](https://user-images.githubusercontent.com/38999030/231386736-7b0a0ca8-c86b-4fe3-86b1-8d23a90eedcf.png)

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
https://github.com/apache/dolphinscheduler/pull/13604/files

it had been fixed,plz close this issue
@SbloodyS @EricGao888

**Comment by SbloodyS** [comment]
> https://github.com/apache/dolphinscheduler/pull/13604/files
> 
> it had been fixed,plz close this issue @SbloodyS @EricGao888

Thanks.
