### ISSUE TITLE
[Bug] [datax] A custom template in datax, The user-defined parameter input box is abnormal

### ISSUE THREAD

**Issue by duhanmin** [apache/dolphinscheduler#13928]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Custom templates in datax
The custom parameter input box displays abnormally

![image](https://user-images.githubusercontent.com/28647031/231982194-d660cb38-edec-43bf-86c3-702bf59e66c5.png)

![image](https://user-images.githubusercontent.com/28647031/231982273-1fb4f53c-5e9f-4682-a94e-b5512d24ec4a.png)

### What you expected to happen

The custom parameter input box displays abnormally

### How to reproduce

The custom parameter input box displays abnormally

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by imp2002** [comment]
@davidzollo Interested in it, could you assign it to me?

**Comment by davidzollo** [comment]
> @davidzollo Interested in it, could you assign it to me?

has assigned to you!

**Comment by davidzollo** [comment]
@duhanmin thank you for submitting this issue, please in English next time.
