### ISSUE TITLE
[Improvement][Module Name] when to support seatunnel engine mode

### ISSUE THREAD

**Issue by SeanZhang2021** [apache/dolphinscheduler#13934]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I find that seatunnel  only support spark、hive mode，but now seatunnel2  have engine mode, it's an exciting feature to use with out spark or hive, is there a plan to support engine mode?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
cc @TyrantLucifer

**Comment by zhuangchong** [comment]
#13086  Already done.

**Comment by zhongjiajie** [comment]
will release in version 3.2.0 or 3.1.6
