### ISSUE TITLE
[Bug] [Master] Scheduling time output failed when complementing numbers, reporting null pointer  version: 3.1.4

### ISSUE THREAD

**Issue by woxiangwoshi123** [apache/dolphinscheduler#13938]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I make up the schedule time is not generated, not all workflows are like this.
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/32809232/232420508-e2237c20-7195-448d-a237-8928ddeefb4a.png">
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/32809232/232421128-b2ace5bd-1e3c-4000-ac31-1bc22b9b3b33.png">
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/32809232/232421208-20487e36-ceb7-4328-a8e2-0fa83aadcac5.png">

### What you expected to happen

The scheduling time display is normal when complementing the number, and the null pointer error is no longer reported

### How to reproduce

Manually click the workflow run button, click the complement number, and select the complement date according to the time control to execute.

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by woxiangwoshi123** [comment]
> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.
> 
> ### What happened
> When I make up the schedule time is not generated, not all workflows are like this. <img alt="image" width="1333" src="https://user-images.githubusercontent.com/32809232/232420508-e2237c20-7195-448d-a237-8928ddeefb4a.png"> <img alt="image" width="1372" src="https://user-images.githubusercontent.com/32809232/232421128-b2ace5bd-1e3c-4000-ac31-1bc22b9b3b33.png"> <img alt="image" width="1053" src="https://user-images.githubusercontent.com/32809232/232421208-20487e36-ceb7-4328-a8e2-0fa83aadcac5.png">
> 
> ### What you expected to happen
> The scheduling time display is normal when complementing the number, and the null pointer error is no longer reported
> 
> ### How to reproduce
> Manually click the workflow run button, click the complement number, and select the complement date according to the time control to execute.
> 
> ### Anything else
> _No response_
> 
> ### Version
> 3.1.x
> 
> ### Are you willing to submit PR?
> * [ ]  Yes I am willing to submit a PR!
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

https://test1.unicompayment.com/ito-bdp-web/auth/appl

> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.
> 
> ### What happened
> When I make up the schedule time is not generated, not all workflows are like this. <img alt="image" width="1333" src="https://user-images.githubusercontent.com/32809232/232420508-e2237c20-7195-448d-a237-8928ddeefb4a.png"> <img alt="image" width="1372" src="https://user-images.githubusercontent.com/32809232/232421128-b2ace5bd-1e3c-4000-ac31-1bc22b9b3b33.png"> <img alt="image" width="1053" src="https://user-images.githubusercontent.com/32809232/232421208-20487e36-ceb7-4328-a8e2-0fa83aadcac5.png">
> 
> ### What you expected to happen
> The scheduling time display is normal when complementing the number, and the null pointer error is no longer reported
> 
> ### How to reproduce
> Manually click the workflow run button, click the complement number, and select the complement date according to the time control to execute.
> 
> ### Anything else
> _No response_
> 
> ### Version
> 3.1.x
> 
> ### Are you willing to submit PR?
> * [ ]  Yes I am willing to submit a PR!
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

<img width="1450" alt="image" src="https://user-images.githubusercontent.com/32809232/232422801-c573f8fd-bcf0-4d29-9b5b-6a17607e0008.png">

**Comment by SbloodyS** [comment]
Fixed.
