### ISSUE TITLE
[Question] When scheduling a springboot jar through a shell, the default dolphinscheduler's profile active is: export DATABASE=${DATABASE:-mysql} export SPRING_PROFILES_ACTIVE=${DATABASE}

### ISSUE THREAD

**Issue by gubinjie** [apache/dolphinscheduler#13946]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When scheduling a springboot jar through a shell, the default dolphinscheduler's profile active is:
export DATABASE=${DATABASE:-mysql}
export SPRING_PROFILES_ACTIVE=${DATABASE}

But my jar is using default, which causes my jar to read the dolphinscheduler's profiles active
Even if I add java -Dspring.profiles.active=default when executing jar, it doesn't work, is there any solution?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
Hi @gubinjie AFAIK ``` export SPRING_PROFILES_ACTIVE=${DATABASE}```   used by ```  master ,alert ,worker, api``` . i have a idea that delete ```export SPRING_PROFILES_ACTIVE=${DATABASE}  ``` in ```dolphinscheduler_env.sh```
and update file ``` start.sh```
![image](https://user-images.githubusercontent.com/33984497/232977966-dcf1c72b-6fca-4d3d-84f0-34ce8f4014b4.png)

**Comment by fuchanghai** [comment]
> Hi @gubinjie AFAIK ` export SPRING_PROFILES_ACTIVE=${DATABASE}` used by ` master ,alert ,worker, api` . i have a idea that delete `export SPRING_PROFILES_ACTIVE=${DATABASE} ` in `dolphinscheduler_env.sh` and update file ` start.sh` ![image](https://user-images.githubusercontent.com/33984497/232977966-dcf1c72b-6fca-4d3d-84f0-34ce8f4014b4.png)

BTW , i had not delete ```export SPRING_PROFILES_ACTIVE=${DATABASE} ``` in ```dolphinscheduler_env.sh```,just  update file ``` start.sh``` .  finally , the configuration of ``` start.sh ``` worked.It seems to me that arguments on the command line take precedence over system variables @SbloodyS WDYT?

**Comment by SbloodyS** [comment]
Every time a shell script is executed, it will also execute the `source dolphinscheduler_env.sh`. You can try to config your own environment config in the task definition page if you want to overwrite the default env settings. @fuchanghai @gubinjie 

https://github.com/apache/dolphinscheduler/blob/047fa2f65e58b86e2f03a89ce5ac2db264ee5e0f/dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/ShellCommandExecutor.java#L108-L118

**Comment by fuchanghai** [comment]
> Every time a shell script is executed, it will also execute the `source dolphinscheduler_env.sh`. You can try to config your own environment config in the task definition page if you want to overwrite the default env settings. @fuchanghai @gubinjie
> 
> https://github.com/apache/dolphinscheduler/blob/047fa2f65e58b86e2f03a89ce5ac2db264ee5e0f/dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/ShellCommandExecutor.java#L108-L118

i agree with you ,but there is no need to put ```spring.profile.active``` and ```database``` in the dolphinscheduler_env file., my personal opinion is that these two parameters should be put into the application.yaml file

**Comment by gubinjie** [comment]
I changed all components of DolphinScheduler in conf/application.yaml for database connections to dolphinscheduler_env.sh
export SPRING_DATASOURCE_URL="***"
export SPRING_DATASOURCE_USERNAME=root
export SPRING_DATASOURCE_PASSWORD=****
, and set #export DATABASE=${DATABASE:-mysql}
#export SPRING_PROFILES_ACTIVE=${DATABASE}
These two parameters are commented out so that when I call java -jar test.jar using the shell, he uses the default profile=default, as shown in Figure 1.

![1681891054256](https://user-images.githubusercontent.com/37869445/233008171-485472a7-ace5-4182-a5f9-2b88b58cc2eb.jpg)

But even with profile=default, my own project (test.jar) will still use the dolphinscheduler metadata storage library (dolphinscheduler), as shown in Figure 2
![1681890962797](https://user-images.githubusercontent.com/37869445/233007641-489c7dd7-ebd1-4be6-a4d0-2a1881762b1d.jpg)

**Comment by SbloodyS** [comment]
> i agree with you ,but there is no need to put `spring.profile.active` and `database` in the dolphinscheduler_env file., my personal opinion is that these two parameters should be put into the application.yaml file

We use tag `spring.profile.active=docker` to build docker images so that we can not hard code it in the `application.yaml`. But I found there is no `SPRING_PROFILES_ACTIVE` in the latest dev branch.

https://github.com/apache/dolphinscheduler/blob/32a8241ef2c89ab286727eb393a8ac6bc19fd2ae/script/env/dolphinscheduler_env.sh#L23-L27

**Comment by gubinjie** [comment]
I feel that this is a bug, all SpringBoot+jdbc type Jars, when using native data source connections, will give preference to the dataSource of the dolphinscheduler project itself.
Therefore, for our own projects we should use custom data sources or multiple data sources instead of using the dataSource provided by Springboot
