### ISSUE TITLE
Task Failure Policy

### ISSUE THREAD

**Issue by qddlggg** [apache/dolphinscheduler#13954]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

能否给加任务加一个失败忽略功能

### Use case

我发现任务失败之后，下游的任务全部都不执行了。能否加一个忽略失败的配置，即使任务失败了，下游的任务依旧能够正常秩序

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You can try to use continue strategy in workflow definition.
