### ISSUE TITLE
[Bug] [master] java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by gubinjie** [apache/dolphinscheduler#13956]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When shutdown is executed all the time in a workflow instance

### What you expected to happen

[ERROR] 2023-04-19 10:42:21.195 +0000 org.apache.dolphinscheduler.server.master.event.WorkflowStartEventHandler:[72] - [WorkflowInstance-0][TaskInstance-0] - Failed to submit the workflow instance, will resend the workflow start event: WorkflowEvent(workflowEventType=START_WORKFLOW, workflowInstanceId=21)
[INFO] 2023-04-19 10:42:21.195 +0000 org.apache.dolphinscheduler.server.master.event.WorkflowEventQueue:[38] - [WorkflowInstance-0][TaskInstance-0] - Added workflow event to workflowEvent queue, event: WorkflowEvent(workflowEventType=START_WORKFLOW, workflowInstanceId=21)
[INFO] 2023-04-19 10:42:21.195 +0000 org.apache.dolphinscheduler.server.master.runner.WorkflowEventLooper:[78] - [WorkflowInstance-21][TaskInstance-0] - Workflow event looper receive a workflow event: WorkflowEvent(workflowEventType=START_WORKFLOW, workflowInstanceId=21), will handle this
[ERROR] 2023-04-19 10:42:21.195 +0000 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[1015] - [WorkflowInstance-20][TaskInstance-0] - Submit standby task test error, taskCode: 9274561518464
java.lang.NullPointerException: null
[ERROR] 2023-04-19 10:42:21.195 +0000 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[1015] - [WorkflowInstance-23][TaskInstance-0] - Submit standby task test error, taskCode: 9274561518464
java.lang.NullPointerException: null
[INFO] 2023-04-19 10:42:21.195 +0000 org.apache.dolphinscheduler.server.master.event.WorkflowStartEventHandler:[54] - [WorkflowInstance-21][TaskInstance-0] - Handle workflow start event, begin to start a workflow, event: WorkflowEvent(workflowEventType=START_WORKFLOW, workflowInstanceId=21)
[ERROR] 2023-04-19 10:42:21.195 +0000 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[704] - [WorkflowInstance-0][TaskInstance-0] - Start workflow error
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitStandByTask(WorkflowExecuteRunnable.java:1847)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitPostNode(WorkflowExecuteRunnable.java:1362)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.call(WorkflowExecuteRunnable.java:698)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[ERROR] 2023-04-19 10:42:21.195 +0000 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[704] - [WorkflowInstance-0][TaskInstance-0] - Start workflow error
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitStandByTask(WorkflowExecuteRunnable.java:1847)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitPostNode(WorkflowExecuteRunnable.java:1362)
        at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.call(WorkflowExecuteRunnable.java:698)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[ERROR] 2023-04-19 10:42:21.195 +0000 org.apache.dolphinscheduler.server.master.event.WorkflowStartEventHandler:[72] - [WorkflowInstance-0][TaskInstance-0] - Failed to submit the workflow instance, will resend the workflow start event: WorkflowEvent(workflowEventType=START_WORKFLOW, workflowInstanceId=20)
[ERROR] 2023-04-19 10:42:21.195 +0000 org.apache.dolphinscheduler.server.master.event.WorkflowStartEventHandler:[72] - [WorkflowInstance-0][TaskInstance-0] - Failed to submit the workflow instance, will resend the workflow start event: WorkflowEvent(workflowEventType=START_WORKFLOW, workflowInstanceId=23)
[ERROR] 2023-04-19 10:42:21.195 +0000 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[1015] - [WorkflowInstance-25][TaskInstance-0] - Submit standby task test error, taskCode: 9274561518464
java.lang.NullPointerException: null
[INFO] 2023-04-19 10:42:21.195 +0000 org.apache.dolphinscheduler.server.master.runner.WorkflowEventLooper:[78] - [WorkflowInstance-20][TaskInstance-0] - Workflow event looper receive a workflow event: WorkflowEvent(workflowEventType=START_WORKFLOW, workflowInstanceId=20), will handle this
[INFO] 2023-04-19 10:42:21.195 +0000 org.apache.dolphinscheduler.server.master.event.WorkflowEventQueue:[38] - [WorkflowInstance-0][TaskInstance-0] - Added workflow event to workflowEvent queue, event: WorkflowEvent(workflowEventType=START_WORKFLOW, workflowInstanceId=20)
[INFO] 2023-04-19 10:42:21.195 +0000 org.apache.dolphinscheduler.server.master.event.WorkflowEventQueue:[38] - [WorkflowInstance-0][TaskInstance-0] - Added workflow event to workflowEvent queue, event: WorkflowEvent(workflowEventType=START_WORKFLOW, workflowInstanceId=23)
[ERROR] 2023-04-19 10:42:21.195 +0000 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[1015] - [WorkflowInstance-24][TaskInstance-0] - Submit standby task test error, taskCode: 9274561518464

### How to reproduce

When shutdown is executed all the time in a workflow instance

### Anything else

This error log keeps triggering, causing the log file to grow dramatically

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gubinjie** [comment]
![image](https://user-images.githubusercontent.com/37869445/233057622-ce18289e-6580-44cc-aa11-f4fd2911be99.png)

**Comment by SbloodyS** [comment]
@gubinjie Which version are you using?

**Comment by gubinjie** [comment]
@SbloodyS 3.1.4

**Comment by SbloodyS** [comment]
Can you provide more information about the steps to reproduce this issue and workflow's definitions?

**Comment by gubinjie** [comment]
![111](https://user-images.githubusercontent.com/37869445/233284592-731650a1-42cf-479d-8f45-92c262978874.jpg)
![image](https://user-images.githubusercontent.com/37869445/233284777-67913432-28b5-49a5-a999-27a77e89cb5e.png)
Now the log has been increasing, I want to delete the workflow he shows that it cannot be deleted, as shown in Figure 2, is there a way to let him delete first, I will reproduce the specific details later.

**Comment by gubinjie** [comment]
@SbloodyS

**Comment by fuchanghai** [comment]
hi @gubinjie  it seems like id is null @SbloodyS WDYT?
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/33984497/233296554-e5731815-dff0-41d1-b138-2bbb0c489638.png">
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/33984497/233296810-e4fd0820-4965-4ad4-a7c7-a14f70e81e3c.png">
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/33984497/233296880-6e2fc8ac-fa17-46bb-8c18-8a0d0bc3958a.png">
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/33984497/233297072-b7f2567f-5598-4022-8d9a-9b2082e53de1.png">

**Comment by fuchanghai** [comment]
@gubinjie can you search the log for this sentence
<img width="907" alt="image" src="https://user-images.githubusercontent.com/33984497/233297641-e6a19ca6-8b70-4c5d-bb80-379726e002e5.png">

**Comment by gubinjie** [comment]
![image](https://user-images.githubusercontent.com/37869445/233298482-67593085-3e2b-4be9-8476-d248cc4f00b1.png)
Yes, I can see

**Comment by gubinjie** [comment]
@fuchanghai

**Comment by fuchanghai** [comment]
@gubinjie @SbloodyS  This judgment seems to be on the surface if taskInstacne is null, only to enter, so there will be NPE, do you agree with me?
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/33984497/233303410-2c7d5736-61e5-4fa3-a6b7-8a2febc73efe.png">

**Comment by fuchanghai** [comment]
can we set 0 instead of ```task.getId()``` @SbloodyS

**Comment by fuchanghai** [comment]
@SbloodyS I remember that id used to be of type int, but it was later changed to type Integer. My personal opinion is that the above reason caused the exception. Can we set a fixed value of 0 here?

**Comment by fuchanghai** [comment]
@SbloodyS @EricGao888  @caishunfeng  i'll try to fix it

**Comment by gubinjie** [comment]
Anyway, this NPE causes the log to grow indefinitely, I have put the entries in the workflow instance that cannot be deleted in the database modification status to 7, then delete them on the page, and then restart the dolphinscheduler service, after which the log will not grow.

**Comment by fuchanghai** [comment]
> Anyway, this NPE causes the log to grow indefinitely, I have put the entries in the workflow instance that cannot be deleted in the database modification status to 7, then delete them on the page, and then restart the dolphinscheduler service, after which the log will not grow.


@gubinjie Does version 3.1.4 have this PR?#13051

**Comment by gubinjie** [comment]
@fuchanghai I haven't encountered this problem for the time being.

**Comment by fuchanghai** [comment]
> @fuchanghai我暂时没有遇到这个问题。

@gubinjie 
#13051 This PR fixes the problem that infinite retries cause the log to print continuously after the creation of the workflow fails

**Comment by caishunfeng** [comment]
> @gubinjie @SbloodyS This judgment seems to be on the surface if taskInstacne is null, only to enter, so there will be NPE, do you agree with me? <img alt="image" width="1317" src="https://user-images.githubusercontent.com/33984497/233303410-2c7d5736-61e5-4fa3-a6b7-8a2febc73efe.png">

Good catch.

**Comment by gubinjie** [comment]
Maybe this problem is not fixed, I see that many people on issues have encountered this problem,THY
