### ISSUE TITLE
[Bug] [Master] set task force success then recovery failed process instance, but the task run again

### ISSUE THREAD

**Issue by eye-gu** [apache/dolphinscheduler#13976]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

dag : a -> b -> c
Task b failed, and set force success. Then recovery failed then process instance. Task b run again.

### What you expected to happen

I think the task has been set to force success, and when recovery fails, it should start downstream. Starting from task c in the example.

### How to reproduce

refer to what happended

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by llphxd** [comment]
I had the same problem that prevented me from launching downstream tasks

**Comment by eye-gu** [comment]
> I had the same problem that prevented me from launching downstream tasks

DS community did not reply to me. You can try modifying the `isTaskComplete` method and adding the condition of `isForceSuccess`.
