### ISSUE TITLE
[Bug] [resource] resource center 

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#13989]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="2090" alt="image" src="https://user-images.githubusercontent.com/15820530/233613636-ba02370d-2638-46ac-93a4-00f15aaaa5ff.png">

click resource center and the error message will show

```log
Internal Server Error: The path does not exist. make sure resource path: 
```

### What you expected to happen

should not raise error.

### How to reproduce

start and click resources center

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ly109974** [comment]
repaired completed

**Comment by ly109974** [comment]
![image](https://user-images.githubusercontent.com/103415610/235032117-15f3b870-d14a-4f79-b6b3-e576ef000907.png)
![image](https://user-images.githubusercontent.com/103415610/235032191-825072d7-97cf-443a-af63-d6a15e053305.png)
@zhongjiajie
