### ISSUE TITLE
[Discussion][Data Complement] Data complement and workflow execution type combos make users confused 

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#13983]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Currently in DolphinScheduler, there are four different  `process execution types` and two different `data complement mode`. Therefore, there will be 4 * 2 = 8 different combos when it comes to workflow data complement, which could be confusing for users.
* We could remove useless combos and elaborate the different behaviors of each combo in docs.

![image](https://user-images.githubusercontent.com/34905992/233564154-a9204a67-aae0-4656-8bf3-937b94b222d1.png)

![image](https://user-images.githubusercontent.com/34905992/233564257-929b06b6-1a50-487c-bc84-5aaff9010596.png)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
haha, good catch for you
