### ISSUE TITLE
[Feature][SQL] Adding [from script] option for SQL plugin just like HIVE CLI plugin

### ISSUE THREAD

**Issue by batmanneverdie** [apache/dolphinscheduler#13995]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

希望可以**为 SQL 插件添加一个类似 HIVE CLI 插件的 `[FROM_SCRIPT]` 选项**，用户可以选择编写 sql 脚本或者**直接选择执行资源中心的某个文件。**
这个功能带来的**好处是**用户可以集成 CICD 将 sql 脚本开发自动上传到 DS 资源中心，**不需要频繁的修改任务中的 sql 节点脚本**。
![image](https://user-images.githubusercontent.com/41139080/233818557-e649342e-08dd-4ebe-8ea7-ebe2e98d5638.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
it is a good idea, but the reason why hive cli can use resource files and execute them, is `hive cli` use `hive -f ` shell command  to the task. it can download the resource file from the resource center, and run the command with `hive -f <resource-file>`.

But for SQL tasks, we directly post sql scripts to jdbc connection, if we want to make resource file work, should change code frame in https://github.com/apache/dolphinscheduler/blob/34f5b009e18dbeeda20c5befb0dc44ed74b826da/dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java#L155-L158 by reading resource file content

**Comment by alextinng** [comment]
I'm glad to take the charge of backend development

**Comment by zhongjiajie** [comment]
looking forward your contribution @alextinng

**Comment by yan-yunfeng** [comment]
Was this issue closed？
if not ,i am glade to  make my first contribution
and if someone is willing to guide me, it will help me a lot
