### ISSUE TITLE
[Improvement][Log] Make the regular expressions of the logs that need to be hidden configurable

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#13993]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description
Make the regular expressions of the logs that need to be hidden configurable
<img width="690" alt="image" src="https://user-images.githubusercontent.com/33984497/233815859-f78337af-96f7-4cb6-a37d-00ebcb7b1455.png">

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
hi @rickchengx Although this expression is added in sqoopTask, once added, it will take effect for all tasks, not just sqoop tasks. WDYT?

<img width="1349" alt="image" src="https://user-images.githubusercontent.com/33984497/233815961-b8e52400-c11d-49dc-b9a1-1115dbff1df5.png">

**Comment by rickchengx** [comment]
> hi @rickchengx Although this expression is added in sqoopTask, once added, it will take effect for all tasks, not just sqoop tasks. WDYT?
> 
> <img alt="image" width="1349" src="https://user-images.githubusercontent.com/33984497/233815961-b8e52400-c11d-49dc-b9a1-1115dbff1df5.png">

Yes, it will take effect for all tasks (The premise is that the user performs the sqoop task)

You mean you want to only take effect in the sqoop task type ?

**Comment by fuchanghai** [comment]
> > hi @rickchengx Although this expression is added in sqoopTask, once added, it will take effect for all tasks, not just sqoop tasks. WDYT?
> > <img alt="image" width="1349" src="https://user-images.githubusercontent.com/33984497/233815961-b8e52400-c11d-49dc-b9a1-1115dbff1df5.png">
> 
> Yes, it will take effect for all tasks (The premise is that the user performs the sqoop task)
> 
> You mean you want to only take effect in the sqoop task type ?
yes, i'll add a new issue to disscussion about this

**Comment by zhongjiajie** [comment]
> > hi @rickchengx Although this expression is added in sqoopTask, once added, it will take effect for all tasks, not just sqoop tasks. WDYT?
> > <img alt="image" width="1349" src="https://user-images.githubusercontent.com/33984497/233815961-b8e52400-c11d-49dc-b9a1-1115dbff1df5.png">
> 
> Yes, it will take effect for all tasks (The premise is that the user performs the sqoop task)
> 
> You mean you want to only take effect in the sqoop task type ? yes, i'll add a new issue to disscussion about this

It is better for apply run for one single task, but it is ok for all task for me. I had half remember we discuss before for all task is ok template, am I right? @rickchengx

**Comment by rickchengx** [comment]
> > > hi @rickchengx Although this expression is added in sqoopTask, once added, it will take effect for all tasks, not just sqoop tasks. WDYT?
> > > <img alt="image" width="1349" src="https://user-images.githubusercontent.com/33984497/233815961-b8e52400-c11d-49dc-b9a1-1115dbff1df5.png">
> > 
> > 
> > Yes, it will take effect for all tasks (The premise is that the user performs the sqoop task)
> > You mean you want to only take effect in the sqoop task type ? yes, i'll add a new issue to disscussion about this
> 
> It is better for apply run for one single task, but it is ok for all task for me. I had half remember we discuss before for all task is ok template, am I right? @rickchengx

Because the masking of sensitive data will not affect the execution of tasks, it is also an acceptable solution to take effect for all tasks. But I also agree that it is a better solution to only take effect in the current task type.

Looking forward to @fuchanghai's PR

**Comment by fuchanghai** [comment]
> > > > hi @rickchengx Although this expression is added in sqoopTask, once added, it will take effect for all tasks, not just sqoop tasks. WDYT?
> > > > <img alt="image" width="1349" src="https://user-images.githubusercontent.com/33984497/233815961-b8e52400-c11d-49dc-b9a1-1115dbff1df5.png">
> > > 
> > > 
> > > Yes, it will take effect for all tasks (The premise is that the user performs the sqoop task)
> > > You mean you want to only take effect in the sqoop task type ? yes, i'll add a new issue to disscussion about this
> > 
> > 
> > It is better for apply run for one single task, but it is ok for all task for me. I had half remember we discuss before for all task is ok template, am I right? @rickchengx
> 
> Because the masking of sensitive data will not affect the execution of tasks, it is also an acceptable solution to take effect for all tasks. But I also agree that it is a better solution to only take effect in the current task type.
> 
> Looking forward to @fuchanghai's PR

I want to match specific task types through event.getLoggerName @rickchengx WDYT?
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/33984497/234161664-81b8ea86-88a0-445d-894c-aee42b295461.png">
