### ISSUE TITLE
[Improvement][Log] Use RollingFileAppender to set the task instance log max size

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#13997]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
do you want to fix it by yourself or want to volunteer?

**Comment by ruanwenjun** [comment]
> do you want to fix it by yourself or want to volunteer?

This can be a good first issue.

**Comment by zyrate** [comment]
I want to have a try, plz assign it to me.

**Comment by zyrate** [comment]
Should we use the `SizeAndTimeBasedRollingPolicy` to set the maximum log file size? If so, what is the recommended name pattern and expected max file size? And when querying the log of a task instance, should we only query on the latest log file? @ruanwenjun

**Comment by ruanwenjun** [comment]
> Should we use the `SizeAndTimeBasedRollingPolicy` to set the maximum log file size? If so, what is the recommended name pattern and expected max file size? And when querying the log of a task instance, should we only query on the latest log file? @ruanwenjun

Yes, we can use `SizeAndTimeBasedRollingPolicy ` and set the maxFileSize

**Comment by zyrate** [comment]
So, that means we need to change the log full path pattern from `{log.base}/{taskSubmitTime}/{workflowDefinitionCode}/{workflowDefinitionVersion}/{workflowInstance}/{taskInstance}.log` to `{log.base}/{taskSubmitTime}/{workflowDefinitionCode}/{workflowDefinitionVersion}/{workflowInstance}/{taskInstance}/`，and under this path we have `latest.log` and other history log files named after time and sequence, right? @ruanwenjun

**Comment by zyrate** [comment]
Am I understanding correctly? @ruanwenjun

**Comment by ruanwenjun** [comment]
> So, that means we need to change the log full path pattern from `{log.base}/{taskSubmitTime}/{workflowDefinitionCode}/{workflowDefinitionVersion}/{workflowInstance}/{taskInstance}.log` to `{log.base}/{taskSubmitTime}/{workflowDefinitionCode}/{workflowDefinitionVersion}/{workflowInstance}/{taskInstance}/`，and under this path we have `latest.log` and other history log files named after time and sequence, right? @ruanwenjun

This seems more complicated than I thought, I hope we have a way to keep the log in one file, by the file has max size.
Maybe we need to write our own appender?

**Comment by zyrate** [comment]
> This seems more complicated than I thought, I hope we have a way to keep the log in one file, by the file has max size. Maybe we need to write our own appender?

What is supposed to do when the file reach the max size? Just let the file rewritten by new content? @ruanwenjun

**Comment by ruanwenjun** [comment]
> > This seems more complicated than I thought, I hope we have a way to keep the log in one file, by the file has max size. Maybe we need to write our own appender?
> 
> What is supposed to do when the file reach the max size? Just let the file rewritten by new content? @ruanwenjun

We can stop writing when reach the max size.
