### ISSUE TITLE
[Improvement][Bom] In the ```pom file``` of the ```bom module```, the ```scala version``` is best also configured in the properties tag

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#14005]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

hi @zhuangchong Please tag good first issue

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/33984497/233962560-31327f8b-2a0e-49f7-ae4b-a2a4deaa195a.png">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mashangyuanmeng** [comment]
@zhuangchong @caishunfeng i will fix it, plz assign this issue to me

**Comment by zhongjiajie** [comment]
> @zhuangchong @caishunfeng i will fix it, plz assign this issue to me

assigned to you, looking forward your contribution
