### ISSUE TITLE
[Feature] Add project id/workflow definition id/instance id to the built-in variables

### ISSUE THREAD

**Issue by TCGOGOGO** [apache/dolphinscheduler#14007]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

These Ids are useful things that can be used as part of path (or something like that) to record temporary result generated by each modules

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by haibingtown** [comment]
@SbloodyS  i will fix it, plz assign this issue to me

**Comment by calvinjiang** [comment]
@haibingtown I've assigned this issue to you. If you add other variables like workflow definition name and task name, that would be great. By the way the variable of task instance id already exists. You can take a look at the class of TaskConstants.

![image](https://github.com/apache/dolphinscheduler/assets/4928204/729c06b9-acbd-47d9-a31c-982dc3e55edf)

**Comment by haibingtown** [comment]
@calvinjiang  Thank you very much, the information you provided is very useful, I will submit the PR as soon as possible, and then help me review it

**Comment by haibingtown** [comment]
@TCGOGOGO 
<img width="695" alt="image" src="https://github.com/apache/dolphinscheduler/assets/7615949/098036e4-3612-43df-bfd9-4ad422b85a8c">

@TCGOGOGO hi，based on the information you provided, do you mean we need to put the informations ( project Code 、workflow definintion id and instance id ) into this path ?

**Comment by calvinjiang** [comment]
> @TCGOGOGO <img alt="image" width="695" src="https://user-images.githubusercontent.com/7615949/238145098-098036e4-3612-43df-bfd9-4ad422b85a8c.png">
> 
> @TCGOGOGO hi，based on the information you provided, do you mean we need to put the informations ( project Code 、workflow definintion id and instance id ) into this path ?

No. You can just provide some more built-in variables like 'workflow definition name' and 'task name' . Because these variables will be very common for others.

**Comment by TCGOGOGO** [comment]
> @TCGOGOGO <img alt="image" width="695" src="https://user-images.githubusercontent.com/7615949/238145098-098036e4-3612-43df-bfd9-4ad422b85a8c.png">
> 
> @TCGOGOGO hi，based on the information you provided, do you mean we need to put the informations ( project Code 、workflow definintion id and instance id ) into this path ?

Hi Haibing, just like calvin said, hope these IDs could be something like the ${system.biz.date} as built-in variables :-)

**Comment by haibingtown** [comment]
@TCGOGOGO @calvinjiang  Got it! I have submitted pr, please help me to review it => https://github.com/apache/dolphinscheduler/pull/14099 , Thx！
