### ISSUE TITLE
The k8s deployment failed to use the external datax on the dolphinscheduler

### ISSUE THREAD

**Issue by 1205823696** [apache/dolphinscheduler#14017]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

ds, cdh6, hadoop, flink, spark, python datax and other services deployed in k8s mode are all outside the k8s cluster. How to configure ds in k8s to use external services

![image](https://user-images.githubusercontent.com/52704749/234500090-fdb8f821-0621-4281-b460-a8b5b3882415.png)

### What you expected to happen

cdh6, hadoop, flink, spark, python datax and other services are outside the k8s cluster. How to configure ds in k8s to use external services? Do you support external services now

### How to reproduce

Every time

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Theocsx** [comment]
大佬 k8s部署，如何单独部署worker pod和 datax pod。并保证 worker能调用到datax
