### ISSUE TITLE
[Improvement][Module Name] Improvement the scheduler date parameter

### ISSUE THREAD

**Issue by starrella** [apache/dolphinscheduler#14019]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

在业务的实际场景中，调度的作业任务面临的参数传递可能不止于日常调度实例定时的定时时间，而是基于系统时间或者定时时间计算得到的更加复杂的日期。例如：
- 月末
- 旬末
- 季度初
- 季度末
- 当前季度是本年度的第几个季度
- 更多....

在Java或者Python等编码中，这些参数是很容易获取到的，但是在执行SQL时，计算这类参数会需要嵌套几层函数才能够得到，且效率低下、维护困难、可读性差。

我希望在DS中能内置更丰富的全局参数或者SQL Task Plugin任务级的参数，在不依赖外部工具的情况下能够支持更复杂的业务场景。

我的构想是，能够给予DS设计一套参数语法，该语法包括了如下几个部分：
1. 标识头【必选】：判断是否替换该变量
2. 日期跨度【必选】：基于调度定时时间计算跨度开始时间和结束时间时可以使用，例如月初、月末、年末等
3. 参数格式化标识【必选】：根据标识输出日期的格式化方式，例如20230426、2023-01-01等
4. 步长【可选】
5. 单位【可选】
6. 标识符【可选】：增加或减少。步长、单位、标识符三个组合在一起可以进行一次简单的日期加减，例如我要计算10天前所在日期的月初
7. 跨度时间节点【可选】：调度定时时间所在日期跨度的开始日期或者结束日期

上文提到的功能，我以前使用python实现过，作为HiveSQL执行预处理的一个插件，支撑了一家金融公司数仓业务逻辑中90%以上日期参数使用场景

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
good idea, I wonder whether Java have some dependence already done this feature? maybe we could find and use them instead of maintain this utils in dolphinscheduler

**Comment by zhongjiajie** [comment]
https://dolphinscheduler.apache.org/en-us/docs/3.1.5/guide/parameter/built-in  seem @EricGao888 have different view about this feature

**Comment by zhongjiajie** [comment]
BTW @starrella Should use English to proposal the issue
