### ISSUE TITLE
k8s Deployment dolphinscheduler integrates external cdh6 data python...

### ISSUE THREAD

**Issue by 1205823696** [apache/dolphinscheduler#14015]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

k8s Deployment dolphinscheduler integrates external cdh6.2, datax,  python...   
![image](https://user-images.githubusercontent.com/52704749/234299327-768927df-126e-4ca8-b246-3e0e9c8f610c.png)

Error message：
./bin/start.sh: line 30: /usr/java/jdk1.8.0_181-cloudera/bin/java: No such file or directory
![image](https://user-images.githubusercontent.com/52704749/234299541-e87d9543-4afa-454a-81cf-95931bc47517.png)

My configuration file is as follows： vim  bigdata/dolphinscheduler-1.yaml 

![image](https://user-images.githubusercontent.com/52704749/234298920-c8e965fa-cec3-40fb-a781-fa4cbc191565.png)

Services such as cdh6 data python are deployed on other machines without mirroring in k8s

### What you expected to happen

cdh6 datax python and other services deployed on other machines and the current k8s cluster are connected to the network, how should I configure to take effect, thank you very much

### How to reproduce

![image](https://user-images.githubusercontent.com/52704749/234300493-251d1245-aa4e-46a0-8a7f-e7a05d53e2ec.png)

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This is a Java environment issue, not a bug.

**Comment by 1205823696** [comment]
> 这是一个 Java 环境问题，而不是一个错误。

The problem has been fixed thanks
