### ISSUE TITLE
[Bug] [resource center] The resource center module fails to upload jar files.

### ISSUE THREAD

**Issue by lixuey** [apache/dolphinscheduler#14027]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The resource center module fails to upload jar files. Small jar files can be uploaded successfully, but large jar package resources cannot be uploaded. For example, jar packages larger than 28M cannot be uploaded as resources.We are using **version 3.0.0**.

### What you expected to happen

I think it should be a bug of upload function interface, because a small jar resource package can be uploaded, and a jar package larger than 28M will fail to be uploaded. I adjusted the upload size setting in application.yml and it did not work. Only resource bundle uploads of the jar type will have problems, other types will have problems. So I guess the bug must be in the code.

### How to reproduce

The resource center can replicate this problem by uploading a jar package with a longer name that is larger than 28M. I used the admin account.

### Version

3.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
duplicated to https://github.com/apache/dolphinscheduler/issues/10340

**Comment by zhongjiajie** [comment]
we already have a WIP PR https://github.com/apache/dolphinscheduler/pull/11694
