### ISSUE TITLE
[Bug] [registry-jdbc] Error caused by using Mysql keyword' key' field in SQL.

### ISSUE THREAD

**Issue by balajinima** [apache/dolphinscheduler#14025]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Error caused by using Mysql keyword 'key' field in SQL.  related table t_ds_jdbc_registry_lock and t_ds_jdbc_registry_data。
![image_720](https://user-images.githubusercontent.com/6326356/234745714-52936bc7-8c4a-4757-a8b4-251de6a8eb4f.png)
![image_720 (1)](https://user-images.githubusercontent.com/6326356/234745719-abf0b66a-6044-4097-9968-4bc9268a3a68.png)
![image_720 (2)](https://user-images.githubusercontent.com/6326356/234745722-bd172da1-ac27-4b9b-ab09-63288f9fc449.png)

### What you expected to happen

none

### How to reproduce

Avoid using common database keywords as object attributes.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
cc @ruanwenjun

**Comment by ruanwenjun** [comment]
Good catch, I will rename these field at #14032
