### ISSUE TITLE
[Bug] [workflow instance] workflow instance status error

### ISSUE THREAD

**Issue by xiangtao** [apache/dolphinscheduler#14026]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

workflow instance status failed , but task instance status success  in this workflow instance 

eg : 
<img width="561" alt="image" src="https://user-images.githubusercontent.com/2025439/234753051-3d031aba-9af3-4419-aa2e-d20abf32a60b.png">

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/2025439/234753114-1740ec6d-1b97-45a3-963d-00c1565b1552.png">

### What you expected to happen

expect :  workflow instance is success

### How to reproduce

i has not reproduce , mybye this is a concurent bug

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Could you please provide the workflow log?

**Comment by xiangtao** [comment]
> Could you please provide the workflow log?

i have not reproduce , i view code , i found WorkflowExecuteRunnable.getProcessInstanceState 
>  
`

 // process failure 
  if (processFailed()) {
      logger.info("The workflowInstance is failed, the workflow status is {}", WorkflowExecutionStatus.FAILURE);
      return WorkflowExecutionStatus.FAILURE;
  } 
`
processFailed() method return true.

> bellow
i find workflow_instance_id = 693038  to attach log . 

[20230416223400604_instance_id_693038.log](https://github.com/apache/dolphinscheduler/files/11560610/20230416223400604_instance_id_693038.log)

> key log : 

<img width="1439" alt="image" src="https://github.com/apache/dolphinscheduler/assets/2025439/8449e746-42a8-4dab-a94f-11fb916a7639">

**Comment by xiangtao** [comment]
> 
that workflow  run every minute , if there's any problem

**Comment by xiangtao** [comment]
@ruanwenjun

it may be when submitTaskExec() failed , it set taskFailedSubmit = true , it will cause processInstance restart ,but taskFailedSubmit is still true not to reset ,  when taskInstanc status report to master ,
and update processInstance state in `updateProcessInstanceState` ,  it will  judge the status of the workflow instance as failed .  as  hasFailedTask . 
`
private boolean hasFailedTask() {

        if (this.taskFailedSubmit) {
            return true;
        }
        if (this.errorTaskMap.size() > 0) {
            return true;
        }
        return this.dependFailedTaskSet.size() > 0;
    }

`

`

       DependResult dependResult = getDependResultForTask(task);
            if (DependResult.SUCCESS == dependResult) {
                logger.info("The dependResult of task {} is success, so ready to submit to execute", task.getName());
                Optional<TaskInstance> taskInstanceOptional = submitTaskExec(task);
                if (!taskInstanceOptional.isPresent()) {
                    this.taskFailedSubmit = true;
                    // Remove and add to complete map and error map
                    if (!removeTaskFromStandbyList(task)) {
                        logger.error(
                                "Task submit failed, remove from standby list failed, workflowInstanceId: {}, taskCode: {}",
                                processInstance.getId(),
                                task.getTaskCode());
                    }
                    completeTaskMap.put(task.getTaskCode(), task.getId());
                    taskInstanceMap.put(task.getId(), task);
                    errorTaskMap.put(task.getTaskCode(), task.getId());
                    activeTaskProcessorMaps.remove(task.getTaskCode());
                    logger.error("Task submitted failed, workflowInstanceId: {}, taskInstanceId: {}, taskCode: {}",
                            task.getProcessInstanceId(),
                            task.getId(),
                            task.getTaskCode());
                } else {
                    removeTaskFromStandbyList(task);
                }
            }
`

**Comment by xiangtao** [comment]
@ruanwenjun

it may be when submitTaskExec failed , so this taskFailedSubmit val = true ,  when taskInstanc status report to master ,
and update processInstance state in `updateProcessInstanceState` ,  it will  judge the status of the workflow instance as failed .  as  hasFailedTask . 
`
private boolean hasFailedTask() {

        if (this.taskFailedSubmit) {
            return true;
        }
        if (this.errorTaskMap.size() > 0) {
            return true;
        }
        return this.dependFailedTaskSet.size() > 0;
    }

`

`
DependResult dependResult = getDependResultForTask(task);
            if (DependResult.SUCCESS == dependResult) {
                logger.info("The dependResult of task {} is success, so ready to submit to execute", task.getName());
                Optional<TaskInstance> taskInstanceOptional = submitTaskExec(task);
                if (!taskInstanceOptional.isPresent()) {
                    this.taskFailedSubmit = true;
                    // Remove and add to complete map and error map
                    if (!removeTaskFromStandbyList(task)) {
                        logger.error(
                                "Task submit failed, remove from standby list failed, workflowInstanceId: {}, taskCode: {}",
                                processInstance.getId(),
                                task.getTaskCode());
                    }
                    completeTaskMap.put(task.getTaskCode(), task.getId());
                    taskInstanceMap.put(task.getId(), task);
                    errorTaskMap.put(task.getTaskCode(), task.getId());
                    activeTaskProcessorMaps.remove(task.getTaskCode());
                    logger.error("Task submitted failed, workflowInstanceId: {}, taskInstanceId: {}, taskCode: {}",
                            task.getProcessInstanceId(),
                            task.getId(),
                            task.getTaskCode());
                } else {
                    removeTaskFromStandbyList(task);
                }
            }
`

**Comment by xiangtao** [comment]
@ruanwenjun can you assign this to me ?

**Comment by Mortal-dx** [comment]
@xiangtao How to fix it, I had some issue.

**Comment by ruanwenjun** [comment]
> [@xiangtao](https://github.com/xiangtao) How to fix it, I had some issue.

Since the workflow lifecycle has been refactored in the 3.3.0, so we have no plan to fixed this in 3.1.x.
