### ISSUE TITLE
[Bug] [run shell script] 

### ISSUE THREAD

**Issue by HongYangZheng** [apache/dolphinscheduler#14030]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

i have a shell command, it can run on my linux machine, but when i deploy DS,the shell cant run on DS,and i can only get few information

myshell:

hive -e 'insert into test.td_phone_test select * from test.td_phone limit 10'

here is the log:

[LOG-PATH]: /cloud/data1/apache-dolphinscheduler-3.1.5-bin/standalone-server/logs/20230427/9364246845920_1-1-1.log, [HOST]:  Host{address='192.168.120.200:1234', ip='192.168.120.200', port=1234}
[INFO] 2023-04-27 09:43:12.582 +0000 - Begin to pulling task
[INFO] 2023-04-27 09:43:12.592 +0000 - Begin to initialize task
[INFO] 2023-04-27 09:43:12.592 +0000 - Set task startTime: Thu Apr 27 09:43:12 UTC 2023
[INFO] 2023-04-27 09:43:12.593 +0000 - Set task envFile: /cloud/data1/apache-dolphinscheduler-3.1.5-bin/standalone-server/conf/dolphinscheduler_env.sh
[INFO] 2023-04-27 09:43:12.593 +0000 - Set task appId: 1_1
[INFO] 2023-04-27 09:43:12.593 +0000 - End initialize task
[INFO] 2023-04-27 09:43:12.604 +0000 - Set task status to TaskExecutionStatus{code=1, desc='running'}
[INFO] 2023-04-27 09:43:12.609 +0000 - TenantCode:hive check success
[INFO] 2023-04-27 09:43:12.614 +0000 - ProcessExecDir:/tmp/dolphinscheduler/exec/process/hive/9364241561184/9364246845920_1/1/1 check success
[INFO] 2023-04-27 09:43:12.614 +0000 - Resources:{} check success
[INFO] 2023-04-27 09:43:12.619 +0000 - Task plugin: SHELL create success
[INFO] 2023-04-27 09:43:12.619 +0000 - shell task params {"localParams":[],"rawScript":"hive -e 'insert into test.td_phone_test select * from test.td_phone limit 10'","resourceList":[]}
[INFO] 2023-04-27 09:43:12.620 +0000 - Success initialized task plugin instance success
[INFO] 2023-04-27 09:43:12.620 +0000 - Success set taskVarPool: null
[INFO] 2023-04-27 09:43:12.624 +0000 - raw script : hive -e 'insert into test.td_phone_test select * from test.td_phone limit 10'
[INFO] 2023-04-27 09:43:12.625 +0000 - task execute path : /tmp/dolphinscheduler/exec/process/hive/9364241561184/9364246845920_1/1/1
[INFO] 2023-04-27 09:43:12.628 +0000 - Begin to create command file:/tmp/dolphinscheduler/exec/process/hive/9364241561184/9364246845920_1/1/1/1_1.command
[INFO] 2023-04-27 09:43:12.629 +0000 - Success create command file, command: #!/bin/bash
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
source /cloud/data1/apache-dolphinscheduler-3.1.5-bin/standalone-server/conf/dolphinscheduler_env.sh
/tmp/dolphinscheduler/exec/process/hive/9364241561184/9364246845920_1/1/1/1_1_node.sh
[INFO] 2023-04-27 09:43:12.634 +0000 - task run command: sudo -u hive -E bash /tmp/dolphinscheduler/exec/process/hive/9364241561184/9364246845920_1/1/1/1_1.command
[INFO] 2023-04-27 09:43:12.642 +0000 - process start, process id is: 5638
[INFO] 2023-04-27 09:43:12.667 +0000 - process has exited. execute path:/tmp/dolphinscheduler/exec/process/hive/9364241561184/9364246845920_1/1/1, processId:5638 ,exitStatusCode:127 ,processWaitForStatus:true ,processExitValue:127
[INFO] 2023-04-27 09:43:12.672 +0000 - Send task execute result to master, the current task status: TaskExecutionStatus{code=6, desc='failure'}
[INFO] 2023-04-27 09:43:12.672 +0000 - Remove the current task execute context from worker cache
[INFO] 2023-04-27 09:43:12.673 +0000 - The current execute mode isn't develop mode, will clear the task execute file: /tmp/dolphinscheduler/exec/process/hive/9364241561184/9364246845920_1/1/1
[INFO] 2023-04-27 09:43:12.693 +0000 - Success clear the task execute file: /tmp/dolphinscheduler/exec/process/hive/9364241561184/9364246845920_1/1/1
[INFO] 2023-04-27 09:43:13.643 +0000 -  -> /bin/hive: line 27: /opt/soft/hive/bin/hive.distro: No such file or directory
[INFO] 2023-04-27 09:43:13.645 +0000 - FINALIZE_SESSION

### What you expected to happen

i want the shell script run normally on DS like it did on my machine

### How to reproduce

create a shell script then do  hive commands on DS

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
```
[INFO] 2023-04-27 09:43:13.643 +0000 - -> /bin/hive: line 27: /opt/soft/hive/bin/hive.distro: No such file or directory
```

Please check your environment configuration.

**Comment by HongYangZheng** [comment]
> ```
> [INFO] 2023-04-27 09:43:13.643 +0000 - -> /bin/hive: line 27: /opt/soft/hive/bin/hive.distro: No such file or directory
> ```
> 
> Please check your environment configuration.


after i change the HIVE_HOME in dolphinscheduler_env.sh，it works.
but i still confuse why outside this service it could run normally ,however inside the service it failed.They both on the same machine.
