### ISSUE TITLE
[Bug] [worker] When killing tasks in Worker, the thread executing the task is not actually closed

### ISSUE THREAD

**Issue by balajinima** [apache/dolphinscheduler#14032]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When killing tasks in Worker, the thread executing the task is not actually closed, so the task status is "kill" but it is still running in practice. This indirectly affects the ability to rerun the task. 

![image](https://user-images.githubusercontent.com/6326356/234825553-a539b619-6118-4e6d-a343-a16da9c0e87d.png)
![image](https://user-images.githubusercontent.com/6326356/234825841-bdd2ebfb-77fb-43ab-9ad0-2a32f31c614c.png)

### What you expected to happen

I believe that when closing a task, at least the task execution thread should be closed . This is because not all tasks will start a process, but all tasks must execute commands through a thread.

### How to reproduce

Based on the current implementation, I came up with a method to close the thread. Here are the steps for reference:

1. In the WorkerExecService, maintain a futureMap for each task.
2. When closing a task, retrieve the future object from the futureMap and call the cancel() method.

![image](https://user-images.githubusercontent.com/6326356/234831830-cc3cae12-387d-472e-8aea-965c622f5c35.png)

![image](https://user-images.githubusercontent.com/6326356/234832894-410d1de7-44db-4621-a2ed-7b688b18cd64.png)

![image](https://user-images.githubusercontent.com/6326356/234833092-4998c7b4-73e9-4b86-8b78-1220c4e3b700.png)

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
The killing method is implemented by task plugins, when we kill a task the task will close its resource and the thread will be used by the next task, ds uses a thread pool to execute the task, why you think this is a bug?

**Comment by balajinima** [comment]
I simulated the scenario of a time-consuming SQL execution being killed, but after the task instance is stopped, the background task thread is still running without interruption and release of resources from the database session, which can be verified on the monitoring page. Upon checking the code, I found that the cancel() method of sqltask does not perform any operation and is empty. 
In this situation, there is a certain probability that it will affect the task's re-do. 
I think that interrupting the thread may be a good solution, and doing future.cancel operations on the threads in the thread pool. What do you think?
