### ISSUE TITLE
[Doc][deploy] How to edit application.yaml and common.properties

### ISSUE THREAD

**Issue by xyzhh** [apache/dolphinscheduler#14044]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I can't find how to edit application.yaml and common.properties in the deploy guide! They cant be configured by install.sh automatically? 
Or it is not necessary？

### Documentation Links

https://dolphinscheduler.apache.org/zh-cn/docs/3.1.5/%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97_menu

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by IanLianet** [comment]
@xyzhh By going into the internel logic of install.sh and scp-hosts.sh, application.yaml and common.properties for each service is copied from the original one in  ./bin/${ServerName}-server/conf  by scp.

piece of code in install.sh:
`
bash ${workDir}/scp-hosts.sh
`

piece of code in scp-hosts.sh:
` 
scp -q -P $sshPort -r $workDir/../$dsDir  $host:$installPath
`

take an example:
if you want to modify the application.yaml of master server, you can modify ./bin/master-server/conf/application.yaml  before you run the install.sh.
then each application.yaml of master servers would be the modified one.

Hope this would help you.

**Comment by yanglongsheng** [comment]
> @xyzhh By going into the internel logic of install.sh and scp-hosts.sh, application.yaml and common.properties for each service is copied from the original one in ./bin/${ServerName}-server/conf by scp.
> 
> piece of code in install.sh: `bash ${workDir}/scp-hosts.sh`
> 
> piece of code in scp-hosts.sh: ` scp -q -P $sshPort -r $workDir/../$dsDir $host:$installPath`
> 
> take an example: if you want to modify the application.yaml of master server, you can modify ./bin/master-server/conf/application.yaml before you run the install.sh. then each application.yaml of master servers would be the modified one.
> 
> Hope this would help you.

i don't know which version you are talking about ,but  i think you path is not right ,the real path should be : ./master-server/conf/application.yaml

**Comment by yanglongsheng** [comment]
> 
you did not find the right way , you can find it here: 

https://dolphinscheduler.apache.org/zh-cn/docs/3.1.5/architecture/configuration

so this issue should be closed ,right?
