### ISSUE TITLE
[Bug] [Module Name] Flink job run wrong when use ParameterTool && mysql tool

### ISSUE THREAD

**Issue by Tangsonghuai** [apache/dolphinscheduler#14050]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

i run flink code in local ,i find that can run success.but when i substr job on dolphinscheduer,it going wrong
master log error:

<img width="1425" alt="截屏2023-05-05 上午10 45 48" src="https://user-images.githubusercontent.com/34538205/236367759-6388f90b-3c7d-4ea1-85d8-84d6b90185d8.png">
       
<img width="1059" alt="截屏2023-05-05 上午10 40 55" src="https://user-images.githubusercontent.com/34538205/236367297-651570fe-d207-49b5-a687-f04fc45b3ff1.png">
this 工作流实例， always running and when kill it happend to 'READY KILL'，but 任务实例， have nothing,
please help!

### What you expected to happen

mysql flink code can run in local idea,
`package com.flink.doris.demo;
import com.flink.doris.demo.utils.SourceMysql_get_data_user;
import org.apache.flink.api.java.ExecutionEnvironment;
import org.apache.flink.api.java.utils.ParameterTool;

import java.time.LocalDate;
import java.util.HashMap;

public class test {
    public static void main(String[] args) throws Exception {
//        ExecutionEnvironment env = ExecutionEnvironment.getExecutionEnvironment();
        System.out.println("------------------------");
        ParameterTool parameterTool = ParameterTool.fromArgs(args);
        System.out.println("打印参数----" + parameterTool.toString());
        System.out.println("*******3333***********" + parameterTool.getProperties());
        String cs = String.valueOf(parameterTool.getProperties());
        String cs_tool=cs.replace("{path=","").replace("}","");
        LocalDate date = LocalDate.parse(cs_tool);
        LocalDate previousDay = date.minusDays(1);
        String previousDayStr = previousDay.toString();
        System.out.println(previousDayStr+"<__>"+cs_tool);
        HashMap<String,String> value_get = SourceMysql_get_data_user.getDays(previousDayStr,cs_tool);
        System.out.println("max-id---------> " + value_get.get("id最大值") );
        System.out.println("min-id---------> " + value_get.get("id最小值") );
    }
}

### How to reproduce

help

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tangsonghuai** [comment]
besides,mysql local env,have enough cpu&&memorys,and i can run success simple flink job on dolphinscheduler.
this is my dolphinscheduler sub list
<img width="607" alt="截屏2023-05-05 上午10 52 01" src="https://user-images.githubusercontent.com/34538205/236368400-3e9e7f97-c951-42ae-b835-b4f0dc61a1a6.png">
otherwise,--path load date

**Comment by Tangsonghuai** [comment]
please help,thinks very much!

**Comment by HomminLee** [comment]
This is a duplicate issue. You can watch #13980.

**Comment by zhongjiajie** [comment]
> This is a duplicate issue. You can watch #13980.

Thanks @HomminLee  for the help

**Comment by zhongjiajie** [comment]
And @Tangsonghuai you can upgrade to version 3.1.6 when is release, and will releasing within one month
