### ISSUE TITLE
[Improvement][Release] Roadmap and release version

### ISSUE THREAD

**Issue by zuzuviewer** [apache/dolphinscheduler#14065]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We want to know dolphinscheduler roadmap and how often release a version, but we can't see anything about it.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
@zuzuviewer  The release time interval is not fixed for dolphinscheudler now, I will release it when it needs, but we may release almost 1 or 2 month a version now.

And for the roadmap, dolphinscheduler do not have yearly roadmap now, but quarter one, which you can see in https://github.com/apache/dolphinscheduler/issues/13459. BTW, you can so see https://github.com/apache/dolphinscheduler/issues/14102 which is for bug change for dolphinscheduler

**Comment by zhongjiajie** [comment]
> @zuzuviewer The release time interval is not fixed for dolphinscheudler now, I will release it when it needs, but we may release almost 1 or 2 month a version now.
> 
> And for the roadmap, dolphinscheduler do not have yearly roadmap now, but quarter one, which you can see in #13459. BTW, you can so see #14102 which is for bug change for dolphinscheduler

close due to this
