### ISSUE TITLE
[Bug] [Module Name] root pom's alert-plugin and registry-plugin dependency  maybe wrong

### ISSUE THREAD

**Issue by googlefan** [apache/dolphinscheduler#14073]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I think the root pom.xml's rows from 117 to 126 as this: 
```
 <dependency>
    <groupId>org.apache.dolphinscheduler</groupId>
    <artifactId>dolphinscheduler-alert-plugin</artifactId>
    <version>${project.version}</version>
</dependency>
<dependency>
    <groupId>org.apache.dolphinscheduler</groupId>
    <artifactId>dolphinscheduler-registry-plugin</artifactId>
    <version>${project.version}</version>
</dependency>
```
maybe wrong, cause there're not the artifactId of theirse dependency.

### What you expected to happen

maybe write wrong.

### How to reproduce

maybe the correct code is this : 
```
 <dependency>
    <groupId>org.apache.dolphinscheduler</groupId>
    <artifactId>dolphinscheduler-alert-plugins</artifactId>
    <version>${project.version}</version>
    <type>pom</type>
</dependency>
<dependency>
    <groupId>org.apache.dolphinscheduler</groupId>
    <artifactId>dolphinscheduler-registry-plugins</artifactId>
    <version>${project.version}</version>
    <type>pom</type>
</dependency>
```

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by googlefan** [comment]
version is 3.1.5 and 3.1.6 , the ide can't find the dependency ,so it will hint the error .

**Comment by Radeity** [comment]
Thanks @googlefan , can you try to submit a PR to handle that?

**Comment by googlefan** [comment]
> Thanks @googlefan , can you try to submit a PR to handle that?

No problem.

**Comment by googlefan** [comment]
@Radeity  I submit a pull requests , but I maybe forget set lables .And now I can't edit the lable,perhaps I have't the permission to set label.
Here is the PR:
https://github.com/apache/dolphinscheduler/pull/14079
Need I resubmit PR?
