### ISSUE TITLE
Failed to start standalone mode！！！！

### ISSUE THREAD

**Issue by shunkanghe** [apache/dolphinscheduler#14092]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I downloaded the extract and executed the startup script
`./dolphinscheduler-daemon.sh start standalone-server`

This is the script return value
`Begin start standalone-server......
starting standalone-server, logging to /opt/apache-dolphinscheduler-3.1.5-bin/standalone-server/logs
Overwrite standalone-server/conf/dolphinscheduler_env.sh using bin/env/dolphinscheduler_env.sh.
End start standalone-server.`

Check log error information
[ERROR] 2023-05-12 10:08:33.554 +0000 org.springframework.boot.SpringApplication:[824] - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'masterServer': Invocation of init method failed; nested exception is java.lang.UnsatisfiedLinkError: Unable to load library 'udev':
libudev.so: 无法打开共享对象文件: 没有那个文件或目录
libudev.so: 无法打开共享对象文件: 没有那个文件或目录
/lib64/libudev.so.1.6.2: 错误 ELF 类: ELFCLASS64
Native library (linux-x86/libudev.so) not found in resource path ([file:/opt/apache-dolphinscheduler-3.1.5-bin/standalone-server/conf/, file:/opt/apache-dolphinscheduler-3.1.5-bin/standalone-server/libs/standalone-server/curator-test-5.3.0.jar, file:/opt/apache-dolphinscheduler-3.1.5-bin/standalone-server/libs/standalone-server/dolphinscheduler-alert-server-3.1.5.jar, file:/opt/apache-dolphinscheduler-3.1.5-bin/standalone-server/libs/standalone-server/dolphinscheduler-api-3.1.5.jar, file:/opt/apache-dolphinscheduler-3.1.5-bin/standalone-server/libs/standalone-server/dolphinscheduler-master-3.1.5.jar, file:/opt/apache-dolphinscheduler-3.1.5-bin/standalone-server/libs/standalone-server/dolphinscheduler....``

### What you expected to happen

I expect to launch successfully like the official website

### How to reproduce

I want to know the cause of this problem and how to solve it. I tried to boot on other brand-new machines or windows, but these problems did not occur. However, this problem would occur when booting on a machine with some software installed

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shunkanghe** [comment]
The version is 3.1.5
The jdk version is 1.8.0_262
The system version  is  CentOS Linux release 7.9.2009 (Core)

**Comment by zhongjiajie** [comment]
@shunkanghe could you try again download from apache dest, change check the sha256 value for the tarball to test whether it is correct or not?

**Comment by shunkanghe** [comment]
@zhongjiajie Thank you for your answer. A solution has been found. The problem is caused by a mismatch between the jdk bits and the system
