### ISSUE TITLE
[Improvement][UI] Add a quick link to visit workflow instances of the current workflow.

### ISSUE THREAD

**Issue by calvinjiang** [apache/dolphinscheduler#14112]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When you have a lot of workflows in a project it'll be hard to find the workflow instances of the workflow. So it'll be so convenient to add a quick link to visit workflow instances of the current workflow.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rickchengx** [comment]
good idea 👍
