### ISSUE TITLE
[Bug] [datax] After completing datax, it was completed without continuing the process

### ISSUE THREAD

**Issue by san346596324** [apache/dolphinscheduler#14115]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After defining the process, after multiple tests, it did not follow the normal process
![datax](https://github.com/apache/dolphinscheduler/assets/30828520/5afd8ef6-d670-4744-8613-5cf830d3db94)

### What you expected to happen

can complete the entire process according to the process design

### How to reproduce

Design multiple datax processes and replicate them

### Anything else

no

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MyLoveZhou** [comment]
Can you provide me with more details? Is there a problem with your task?
