### ISSUE TITLE
[Feature][Resource Center] Simultaneous support multi resource components

### ISSUE THREAD

**Issue by qingwli** [apache/dolphinscheduler#14120]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We have a scene about the need to support multi-resource components simultaneously. 

### Use case

Users can upload files to s3 or hdfs. We need to change the resource center to support multiple sources and the download files logic when the job running.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
hi @liqingwang thanks for your issue, but does it a part of the function in https://github.com/apache/dolphinscheduler/issues/10283? we could add this as subtask if it is a part of 10283

**Comment by qingwli** [comment]
Hi @zhongjiajie , I have saw #10283 , It talks about the data center, but this feature we would like to change in the storage center

**Comment by zhongjiajie** [comment]
> Hi @zhongjiajie , I have saw #10283 , It talks about the data center, but this feature we would like to change in the storage center

I think its scope is not only the data center, it should contain all external connections, such as databases, file systems, machine hosts, and also the resource center. it is just a connector between dolphinscheduler and external system. As you can see we will support zeppelin in that connection center which currently only support config in `common.properties` and only for one single zeppelin cluster
