### ISSUE TITLE
[Bug] [dao] Project entity shouldn't use `!=` in `equals` function

### ISSUE THREAD

**Issue by Rianico** [apache/dolphinscheduler#14123]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

`Project.java` entity use `!=` instead of `equals` to compare id, whose type is `Integer`, which may cause a problem when id is not in the range of `-128 ~ 127`:
```java
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        Project project = (Project) o;

        if (id != project.id) {
            return false;
        }
        return name.equals(project.name);

    }
```
  
JVM only caches the `Integer` object between -128 and 127, and will create a new object for other numbers:
```java
jshell> Integer a = 127
a ==> 127

jshell> Integer b = 127
b ==> 127

jshell> a == b
$3 ==> true

jshell> Integer b = 128
b ==> 128

jshell> Integer a = 128
a ==> 128

jshell> a == b
$6 ==> false
```

### What you expected to happen

When id is not in the range of `-128 ~ 127`, the comparation of projects can get a correct result.

### How to reproduce

Create two Project entity `p1` and `p2` with the same name, set the id to the `new Integer(128)`, and call the `p1.equals(p2)`, which will get the `false`.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
due to we have `@Data` annotation in class `Project` https://github.com/apache/dolphinscheduler/blob/efedc9a53ca0704d366d1c88254bf93b4f717963/dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/Project.java#L32 and it have build-in `equals` and `hashCode`, I think we can directly remove method `equals` and `hashCode`, WDYT?

**Comment by Rianico** [comment]
> due to we have `@Data` annotation in class `Project`
> 
> https://github.com/apache/dolphinscheduler/blob/efedc9a53ca0704d366d1c88254bf93b4f717963/dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/Project.java#L32
> 
> and it have build-in `equals` and `hashCode`, I think we can directly remove method `equals` and `hashCode`, WDYT?

The original logic only compares with `id` and `name`. If we remove the `equals` and `hashCode` functions and rely on the function generated by the `@Data` annotation, I’m not sure whether this way will cause some problems elsewhere.

**Comment by zhongjiajie** [comment]
could you see where use the pojo and test whether we can directly remove the custom equals? IMO I think we can remove it, but need double-check about it

**Comment by Rianico** [comment]
Okay, I will investigate where the pojo is being used. If it's acceptable to remove the original logic, I will delete it.

**Comment by zhongjiajie** [comment]
> Okay, I will investigate where the pojo is being used. If it's acceptable to remove the original logic, I will delete it.

cool
