### ISSUE TITLE
[Bug] [Master] Save process instance to db failed caused by NullpointerException

### ISSUE THREAD

**Issue by zuzuviewer** [apache/dolphinscheduler#14137]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I don't know how to reproduce it.But it's a accidental bug, i met it sometimes.

### What you expected to happen

fix

### How to reproduce

nothing

### Anything else

![ds-null-exception](https://github.com/apache/dolphinscheduler/assets/19585711/af8df5cc-70f6-408c-9985-f0f6f97d8037)

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
>如果任务类型不是Dependent或者Swith 应该直接返回null
>If the task type is not Dependent or Switch should return null directly

<img width="905" alt="image" src="https://github.com/apache/dolphinscheduler/assets/33984497/ce2b469c-c972-4976-ae64-e90e347131a8">

**Comment by fuchanghai** [comment]
@zuzuviewer Do you want to try to fix this issue?

**Comment by zuzuviewer** [comment]
> @zuzuviewer Do you want to try to fix this issue?

That's ok, but I have questions about this bug, why is it occasional, our task is not Dependent or Swith type?

**Comment by fuchanghai** [comment]
<img width="1249" alt="image" src="https://github.com/apache/dolphinscheduler/assets/33984497/f7f16e63-fa75-4db9-9fd1-ba0ae3f401d1">
Because the copyTaskInstancce method does not judge what type of task it is. So no matter what type of task you are, it will fall into the getDependency method, and there is no judgment in the getDependency method

**Comment by zuzuviewer** [comment]
> <img alt="image" width="1249" src="https://user-images.githubusercontent.com/33984497/239416927-f7f16e63-fa75-4db9-9fd1-ba0ae3f401d1.png"> Because the copyTaskInstancce method does not judge what type of task it is. So no matter what type of task you are, it will fall into the getDependency method, and there is no judgment in the getDependency method

What I mean is why sometimes no problem with the same workflow, just a few instances triggers this problem
