### ISSUE TITLE
[Bug] [dolphinscheduler-task-conditions] Multiple conditions nodes, unable to complete the process

### ISSUE THREAD

**Issue by maketubu7** [apache/dolphinscheduler#14130]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/apache/dolphinscheduler/assets/39480244/99100053-37d1-48bd-adec-81584be231b2)
start2_cond 
![image](https://github.com/apache/dolphinscheduler/assets/39480244/c1e4a793-cb19-4534-8ecd-b946ddf8b80f)

### What you expected to happen

execute faidl task node
![image](https://github.com/apache/dolphinscheduler/assets/39480244/775aa9b1-b087-47a0-a5ee-7bb4031124be)

### How to reproduce

create more connditions node, The failed branches all point to the same node and run

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by maketubu7** [comment]
The failed node can be run if the first node fails，so I don't quite understand
![image](https://github.com/apache/dolphinscheduler/assets/39480244/3fb15d51-cd1c-4a11-aa5e-41833adf6348)

**Comment by maketubu7** [comment]
master.log
![image](https://github.com/apache/dolphinscheduler/assets/39480244/549fd9de-0d3a-409b-b12a-7580871fbdad)

`[ERROR] 2023-05-17 17:29:51.318 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[292] - [WorkflowInstance-1062][TaskInstance-3980] - State event handle error, will remove this event: TaskStateEvent(processInstanceId=1062, taskInstanceId=3980, taskCode=0, status=TaskExecutionStatus{code=1, desc='running'}, type=TASK_STATE_CHANGE, key=null, channel=null, context=null)
org.apache.dolphinscheduler.server.master.event.StateEventHandleError: The current task instance state is TaskExecutionStatus{code=7, desc='success'}, but the task state event status is TaskExecutionStatus{code=1, desc='running'}, so the task state event will be ignored
	at org.apache.dolphinscheduler.server.master.event.TaskStateEventHandler.handleStateEvent(TaskStateEventHandler.java:69)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.handleEvents(WorkflowExecuteRunnable.java:288)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2023-05-17 17:29:52.318 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[287] - [WorkflowInstance-1062][TaskInstance-3980] - Begin to handle state event, TaskStateEvent(processInstanceId=1062, taskInstanceId=3980, taskCode=0, status=TaskExecutionStatus{code=7, desc='success'}, type=TASK_STATE_CHANGE, key=null, channel=null, context=null)
[INFO] 2023-05-17 17:29:52.319 +0800 org.apache.dolphinscheduler.server.master.event.TaskStateEventHandler:[57] - [WorkflowInstance-1062][TaskInstance-3980] - Handle task instance state event, the current task instance state TaskExecutionStatus{code=7, desc='success'} will be changed to TaskExecutionStatus{code=7, desc='success'}
`

**Comment by maketubu7** [comment]
Different failed nodes can be executed
![image](https://github.com/apache/dolphinscheduler/assets/39480244/ffea34a6-4ab8-432b-ae2b-ee83597e5a05)

**Comment by zhangke-zhangke** [comment]
请问如何解决？

**Comment by zhangke-zhangke** [comment]
> Different failed nodes can be executed ![image](https://user-images.githubusercontent.com/39480244/238906587-ffea34a6-4ab8-432b-ae2b-ee83597e5a05.png)

ds版本：3.1.8 ，也出现了如图上一样的问题。
