### ISSUE TITLE
[Bug] [UI] sql node function group_concat don't save define

### ISSUE THREAD

**Issue by xfworld** [apache/dolphinscheduler#14132]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/apache/dolphinscheduler/assets/5020771/2ae62fe4-b0c4-4d8e-89ff-e1d7ae0bbf36)

Unable to recognize this system function, save submit and report an error
Track commit information before the UI initiates the axios request

![image](https://github.com/apache/dolphinscheduler/assets/5020771/b03a96e7-f75f-434d-8f23-77d75b8cb910)

### What you expected to happen

Ability to save, modify and then submit data

### How to reproduce

Referring to the description in the figure, the replication can be completed

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
OMG, we should not block the user's save when we can not recognize the sql token in the custom sql define, do you make sure the error is due to the token recognize error? @xfworld

**Comment by zhongjiajie** [comment]
BTW, @devosend do we will block users' saving?

**Comment by devosend** [comment]
Will there be an error if you don't use `group_concat `? There should be an error in the server. You can check the back-end log.

**Comment by zhongjiajie** [comment]
Hi @xfworld I test in version 3.0.5 function do not support will not block the workflow definition save and running
<img width="625" alt="image" src="https://github.com/apache/dolphinscheduler/assets/15820530/694a925f-663a-4daa-b563-48cf751be452">

**Comment by xfworld** [comment]
If the function group_concat is present in the submitted data, it reports an error directly when saving.
If this function is not present, but only the standard concat function, it is possible to save

The final error is returned by axios, and it is not known what the error is, because there is no logging on the back end

You can use sql node to reproduce this problem by creating a query...

The operation steps are as follows:
1. Edit the node data and click OK
2. Click the button of process saving, then there is no response.

***
说中文是不是更能帮助你，更快的理解我到底想说什么...
@zhongjiajie 这个Node 的编辑框中，你加上 group_concat () 这个函数，然后确认
接着在提交整个流程的定义...  看看有没有响应...

***
```
SELECT
 a.truck_task_id,
 a.sequence,
 a.station_id,
 a.create_date,
 a.create_by,
 a.modify_date,
 a.modify_by,
 max( b.sequence ) max_seq,
 GROUP_CONCAT( cast ( b.station_id AS string ) ) stations 
FROM
 task_station a
 JOIN def_station b ON a.truck_task_id = b.truck_task_id 
 AND b.sequence <> 2 
WHERE
 1 = 1 
 AND a.sequence = 2 
 AND a.create_date >= '2023-03-01' 
 AND a.create_date < '2023-04-01' 
GROUP BY
 a.truck_task_id,
 a.sequence,
 a.station_id,
 a.create_date,
 a.create_by,
 a.modify_date,
 a.modify_by
```
try it ~~

**Comment by xfworld** [comment]
at last , we make a view replace this sql to jump this step
but, I want to fix this problem
so , please help me
