### ISSUE TITLE
[Improvement][Task node] It takes a long time to schedule two task nodes

### ISSUE THREAD

**Issue by herryhw** [apache/dolphinscheduler#14154]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

两个简单的任务节点之间调度要花1秒钟的时间，这样导致如果一个流程里面有很多
个节点，比如7个左右，一个流程下来就要10几秒左右，甚至更长。如果一个节点里面返回的数据很大，用循环节点去跑就会更慢。请问有没有什么优化的地方，或者对于这种接口返回大批量的列表数据，该如何处理？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Batch processing tasks are acceptable for second level timeliness, and it is recommended to use real-time tasks for those with high timeliness requirements.

**Comment by herryhw** [comment]
我使用最简单的两个SQL节点测试，通过查看日志，测试下来第一个SQL节点输出结果到第二个SQL节点接收第一个节点的结果之间花费1秒钟，请问这个机制就是这样吗？有优化的地方吗？查看了下DolphinScheduler是要去和Master,Worker通讯，时间是花在这里了？

**Comment by herryhw** [comment]
> 
我使用最简单的两个SQL节点测试，通过查看日志，测试下来第一个SQL节点输出结果到第二个SQL节点接收第一个节点的结果之间花费1秒钟，请问这个机制就是这样吗？有优化的地方吗？查看了下DolphinScheduler是要去和Master,Worker通讯，时间是花在这里了？

**Comment by zhongjiajie** [comment]
> Batch processing tasks are acceptable for second level timeliness, and it is recommended to use real-time tasks for those with high timeliness requirements.

just as ZiHao said, if you use sql task is in batch process mode. you can use flink steam task if you need more short interval
