### ISSUE TITLE
[Bug] [DataQuality] ’There is an issue with the JSON generated by the 'two table value comparison rule', missing 'transformers'

### ISSUE THREAD

**Issue by sincere0104** [apache/dolphinscheduler#14158]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

’There is an issue with the JSON generated by the 'two table value comparison rule', missing 'transformers',But the task can be executed normally, possibly due to an issue when outputting to the log.

### What you expected to happen

missing 'transformers',But the task can be executed normally, possibly due to an issue when outputting to the log.

### How to reproduce

Executing tasks can reproduce

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
could you share more detail about it, like which version do you used, and then screen capture for your task definition?

**Comment by sincere0104** [comment]
> could you share more detail about it, like which version do you used, and then screen capture for your task definition?
3.1.2版本
![image](https://github.com/apache/dolphinscheduler/assets/47923097/d16f3ce1-2eab-4d1d-8b28-83d97695f4d6)
