### ISSUE TITLE
[Improvement][Task node] The scheduling of two task nodes is slow

### ISSUE THREAD

**Issue by herryhw** [apache/dolphinscheduler#14159]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

两个简单的任务节点之间调度要花1秒钟的时间，这样导致如果一个流程里面有很多
个节点，比如7个左右，一个流程下来就要10几秒左右，甚至更长。如果一个节点里面返回的数据很大，用循环节点去跑就会更慢。请问有没有什么优化的地方，或者对于这种接口返回大批量的列表数据，该如何处理？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Duplicated with #14154.
