### ISSUE TITLE
[Bug] [DataQuality] Unable to correctly select the operator for 'Field Length Verification Rule'

### ISSUE THREAD

**Issue by sincere0104** [apache/dolphinscheduler#14155]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The operator for 'field length verification' has selected other symbols(<、>、<=), but when saved and opened again, it still shows '='
[字段长度校验的操作符，选了其他符号，但是保存后再打开看依然是=号]

### What you expected to happen

I think operators should be selected correctly！

### How to reproduce

Creating this task directly can reproduce the problem

### Anything else

I am using version ds3.1.1

### Version

3.1.x

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Hi @sincere0104 are you will to to submit pr to fix it?

**Comment by sincere0104** [comment]
等我们修复了，会把代码贡献出来，但是我们不确定什么时候能解决这个问题
Once we fix it, we will contribute the code, but we are not sure when we will be able to solve this problem

**Comment by sincere0104** [comment]
> 等我们修复了，会把代码贡献出来，但是我们不确定什么时候能解决这个问题
> Once we fix it, we will contribute the code, but we are not sure when we will be able to solve this problem

**Comment by sincere0104** [comment]
> Hi @sincere0104 are you will to to submit pr to fix it?

等我们修复了，会把代码贡献出来，但是我们不确定什么时候能解决这个问题
Once we fix it, we will contribute the code, but we are not sure when we will be able to solve this problem

**Comment by codegit10001** [comment]
> 会把代码贡献出来，但是我们不确定什么时候能解决这个问题

大佬，我们也遇到了这个问题，你修复了这个了吗？
