### ISSUE TITLE
[BUG] Performance problems

### ISSUE THREAD

**Issue by henliqi** [apache/dolphinscheduler#1416]
**Describe the bug**
when i start a process with Once per second，and try to start another process ，but the other process delayed Several minutes to start,if i Enlarge Once per second to Once per 5 seconds Problem elimination,how can i improve the Performance of dolphinscheduler?

**Which version of Dolphin Scheduler:**
 -[1.1.0-release]

**Comment by qiaozhanwei** [comment]
现在master和worker都是扫表，可能不能满足秒级的任务调度，偏离线，不过在讨论架构的改进，欢迎订阅 dev@dolphinscheduler.apache.org，查看ds的进度

Now both the master and the workers are scanning the table, which may not meet the second-level task scheduling and deviate from the line. However, when discussing the improvement of the architecture, please subscribe to dev@dolphinscheduler.apache.org to see the progress of ds

**Comment by dailidong** [comment]
> 现在master和worker都是扫表，可能不能满足秒级的任务调度，偏离线，不过在讨论架构的改进，欢迎订阅 [dev@dolphinscheduler.apache.org](mailto:dev@dolphinscheduler.apache.org)，查看ds的进度
> 
> Now both the master and the workers are scanning the table, which may not meet the second-level task scheduling and deviate from the line. However, when discussing the improvement of the architecture, please subscribe to [dev@dolphinscheduler.apache.org](mailto:dev@dolphinscheduler.apache.org) to see the progress of ds

called 'scan table ' is not properly,  the new architecture master will make communication with worker, so the worker will only do task , not to do the database operation , so it will reduce the db pressure

**Comment by zhongjiajie** [comment]
I think supporting second tasks or stream job is a big change of DolphinScheduler. So I add DSIP labels for it
