### ISSUE TITLE
[Bug] [docker install] Installation of arm64 systems is not supported

### ISSUE THREAD

**Issue by MrChenDong** [apache/dolphinscheduler#14166]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I was using Docker Compose for installation, I found that DolphinScheduler does not support the installation of the arm64 system
(1) dolphinscheduler-master pulling exception
(2) dolphinscheduler-postgresql pulling exception
(3) dolphinscheduler-zookeeper pulling exception

### What you expected to happen

I hope DolphinScheduler can support the installation of the arm64 system.

### How to reproduce

You can try installing dolphins in a docker compose mode on the arm64 system.

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
which version do you use? I find master server arm image is exists. https://hub.docker.com/repository/docker/apache/dolphinscheduler-master/tags?page=1&ordering=last_updated

**Comment by zhongjiajie** [comment]
and for dolphinscheduler-postgresql and dolphinscheduler-zookeeper are the third part docker images, we forget to check it. do you want to submit a pr to support it?

**Comment by zhongjiajie** [comment]
BTW, it seems can be solve by upgrade the version https://github.com/apache/dolphinscheduler/pull/13789 and we already merged it

**Comment by zhongjiajie** [comment]
@MrChenDong  I am going to close this issue, you can fix it with, if you still have issue you can comment here and I will reopen it

> BTW, it seems can be solve by upgrade the version #13789 and we already merged it
