### ISSUE TITLE
[Bug] [DataQuality] create `DataQuality` workflow get rule name form error

### ISSUE THREAD

**Issue by imp2002** [apache/dolphinscheduler#14165]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/apache/dolphinscheduler/assets/41513919/1be682c5-1c9a-4303-9c2f-f84db7021437)

When create a `Data Quality` workflow get the error.

Seems cause by the symbol \` `PostgreSQL` is not support.
![image](https://github.com/apache/dolphinscheduler/assets/41513919/22fdbc58-af91-4c2b-ab0f-0b39f76bc756)

I'll try fix.

### What you expected to happen

No error show, query data rightly.

### How to reproduce

Create a `Data Quality` workflow.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
I assigned to you @imp2002 , and could you also check whether other Postgres sql in data quality work or not?

**Comment by imp2002** [comment]
OK

**Comment by Radeity** [comment]
Hi, @imp2002 , i've fixed a bug about replacing resource name of main jar in dev before, ref https://github.com/apache/dolphinscheduler/pull/13536, I have not checked the correctness here in `DataQuality` task. Would like to help check it? :D
https://github.com/apache/dolphinscheduler/blob/1011852ab25c7536a0a64448be310bb9c3619d25/dolphinscheduler-task-plugin/dolphinscheduler-task-dataquality/src/main/java/org/apache/dolphinscheduler/plugin/task/dq/DataQualityTask.java#L183-L189
