### ISSUE TITLE
[Bug] [datax task and python task] The command used by datax task and python task is not a location

### ISSUE THREAD

**Issue by wangcong19901212** [apache/dolphinscheduler#14173]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

datax默认是/opt/soft/python/bin/python2.7
python 默认是/opt/soft/python 
因为依赖同意${PYTHON_HOME}
导致这个两个节点同时需要时，只有一个能成功运行。

### What you expected to happen

ee

### How to reproduce

eee

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jieguangzhou** [comment]
You can set ${DATAX_HOME} to run the datax task. https://dolphinscheduler.apache.org/en-us/docs/3.1.6/guide/task/datax

In addition, we can use `Environmental Management` to set up a defined environment for each task. https://dolphinscheduler.apache.org/en-us/docs/3.1.6/guide/security

**Comment by wangcong19901212** [comment]
不是${DATAX_HOME} ，比如现在默认PYTHON_HOME=/opt/soft/python。当运行python任务时,会将/opt/soft/python当命令来运行脚本。当运行datax任务是，/opt/soft/python/bin/python2.7当成命令 运行json脚本。这时/opt/soft下的python不可能既是命令也是目录。

**Comment by xfoobar** [comment]
@jieguangzhou 
Just like this
```
python3 -m venv $HOME/py_env
```
ds config
```
export PYTHON_HOME="$HOME/py_env"
export DATAX_HOME="$HOME/datax/bin/datax.py"
```
datax task logs
```
/tmp/dolphinscheduler/exec/process/vbn/9816683486976/9817453555328_2/30/42/30_42_node.sh: line 1: /home/foobar/py_env/bin/python2.7: No such file or directory
[INFO] 2023-06-07 17:24:42.565 +0800 - FINALIZE_SESSION
```
When running datax task, the python binary file path will be modified to python2.7, even PYTHON_HOME is python3

**Comment by nianhua99** [comment]
最后怎么处理的？

**Comment by guanyuaxin** [comment]
最后如何处理解决该类问题啊？

**Comment by ketingli1** [comment]
ln -s /usr/bin/python3 /usr/bin/python2.7
或者自己安装一个python2.7

**Comment by MrWhyWu** [comment]
ds界面-安全中心-环境配置，貌似根本就不生效。
去配置 dolphinscheduler_env.sh 文件的 PYTHON_HOME 也会加上了/bin/python2.7 这一段，好鸡儿奇怪。

最后实在没办法，直接 dolphinscheduler_env.sh 配置如下，改为了PYTHON_LAUNCHER。PATH也改了，再把 /bin 去掉。
export PYTHON_LAUNCHER=/usr/bin/python3
export DATAX_LAUNCHER=/opt/datax/bin/datax.py

export PATH=$HADOOP_HOME/bin:$SPARK_HOME1/bin:$SPARK_HOME2/bin:$PYTHON_LAUNCHER:$JAVA_HOME/bin:$HIVE_HOME/bin:$FLINK_HOME/bin:$DATAX_LAUNCHER:$SEATUNNEL_HOME/bin:$CHUNJUN_HOME/bin:$PATH
