### ISSUE TITLE
[Bug] [UI] The cpu and memory dashboard displays abnormally on a 15.6-inch screen with a 1080P resolution.

### ISSUE THREAD

**Issue by timyuer** [apache/dolphinscheduler#14171]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The cpu and memory dashboard displays abnormally on a 15.6-inch screen with a 1080P resolution.

![1684734259471](https://github.com/apache/dolphinscheduler/assets/16263438/4c9020fd-bc15-4ab8-9054-8bf9dbfdc013)

### What you expected to happen

I hope someone fixes it.

### How to reproduce

DolphinScheduler-3.1.6

Please open dolphinscheduler UI on a 15.6-inch screen with a 1080P resolution.

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pppppjcc** [comment]
I'm willing to do it

**Comment by zhongjiajie** [comment]
> I'm willing to do it

I had assigned to you, looking forward your contribution @pppppjcc
