### ISSUE TITLE
Driver does not support get/set network timeout for connections. (Method not supported)

### ISSUE THREAD

**Issue by xuhui1231** [apache/dolphinscheduler#14179]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I I updated Dolphin 3.1.6 and tested the Hive data source connection and found 5 more long links in the HiveServer2 service that did not close。
Dolphin：
![image](https://github.com/apache/dolphinscheduler/assets/51685494/162fd4c0-2526-4fb3-8587-3d80209a59d3)

hiveservice2：
![image](https://github.com/apache/dolphinscheduler/assets/51685494/df1c299a-b927-409e-acf9-55cc11f6e6e9)

api-log：
![image](https://github.com/apache/dolphinscheduler/assets/51685494/1fd32834-8c0b-41bf-88d7-a0ebd07900b3)

### What you expected to happen

I expected hive datasource wiil be close

### How to reproduce

you just test hive datasource

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
hi @xuhui1231 we should remove the datasource connection for sql task, and create new connection for each sql task before execute the code

**Comment by xuhui1231** [comment]
>thx ， I will attention 3.1.8

**Comment by zhongjiajie** [comment]
pr is https://github.com/apache/dolphinscheduler/pull/14193
