### ISSUE TITLE
[Bug] [Master] when processDefinition processExecutionType is  serial_wait or serial_priority  processInstance  always 'ready stop' 

### ISSUE THREAD

**Issue by fw19940314** [apache/dolphinscheduler#14182]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I configure processDefinition executionExecutionType is serial_wait or serial_priority ,  After starting the processDefinition generate processInstance.  

Perform the STOP action on the page, processInstance state always 'ready stop' .

### What you expected to happen

When the process instance state is set to 'ready  stop'  , master in WorkflowStateEventHandler Can judge processDefinition  processExecutionType, if  type is  serial_wait or serial_priority ,  return directly.

code:
<img width="932" alt="image" src="https://github.com/apache/dolphinscheduler/assets/21071875/36b36601-80dc-4073-9f12-c80ee010d858">

![image](https://github.com/apache/dolphinscheduler/assets/21071875/019c97bd-7231-4e49-a67d-175d7024ece5)

### How to reproduce

processDefiniton  executionExecutionType is  serial_wait or serial_priority.

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xiangtao** [comment]
are there any errors in log ?

**Comment by fw19940314** [comment]
> 
No exception log.  I have tried to modify the code and the problem has been solved, but I am not sure if it is feasible

**Comment by fw19940314** [comment]
> are there any errors in log ?


No exception log. I have tried to modify the code and the problem has been solved, but I am not sure if it is feasible

**Comment by stephenking30** [comment]
> > are there any errors in log ?
> 
> No exception log. I have tried to modify the code and the problem has been solved, but I am not sure if it is feasible

hi,bro,How did you solve the problem？can you tell me？
