### ISSUE TITLE
[Improvement][Module Name] Improvement title

### ISSUE THREAD

**Issue by ztl214096602** [apache/dolphinscheduler#14181]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

一个网卡，绑定多个IP时，增加work节点，识别出来的IP，不是我要用的IP，可以增加个指定ip的功能么？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please use english to describe and use the correct title.
