### ISSUE TITLE
[Bug] [Datax] `getReaderPluginName` may return null

### ISSUE THREAD

**Issue by hantmac** [apache/dolphinscheduler#14180]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Because of the datasouce `databend` now does not support datax reader mode so the code here will return `null` when user select `databend` as datax reader:

```java
 public static String getReaderPluginName(DbType dbType) {
        switch (dbType) {
            case MYSQL:
                return DATAX_READER_PLUGIN_MYSQL;
            case POSTGRESQL:
                return DATAX_READER_PLUGIN_POSTGRESQL;
            case ORACLE:
                return DATAX_READER_PLUGIN_ORACLE;
            case SQLSERVER:
                return DATAX_READER_PLUGIN_SQLSERVER;
            case CLICKHOUSE:
                return DATAX_READER_PLUGIN_CLICKHOUSE;
            case HIVE:
                return DATAX_READER_PLUGIN_RDBMS;
            case PRESTO:
                return DATAX_READER_PLUGIN_RDBMS;
            default:
                return null;
        }
    }
```

IMO, datax component of DS should separate the enumeration of the datasource and datatarget. And now it is enum together here:

```
type IDataBase =
  | 'MYSQL'
  | 'POSTGRESQL'
  | 'HIVE'
  | 'SPARK'
  | 'CLICKHOUSE'
  | 'ORACLE'
  | 'SQLSERVER'
  | 'DB2'
  | 'PRESTO'
  | 'REDSHIFT'
  | 'ATHENA'
  | 'TRINO'
  | 'AZURESQL'
  | 'STARROCKS'
  | 'DAMENG'
  | 'OCEANBASE'
  | 'SSH'
  | 'DATABEND'
  | 'SNOWFLAKE'
```

### What you expected to happen

The datax reader show available reader plugin instead of return `null`

### How to reproduce

In DS UI using datax reader.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
hi @hantmac I suggest using rdbms by default, and modify the front-end datax components to divide data sources according to readable and writable

**Comment by hantmac** [comment]
> hi @hantmac I suggest using rdbms by default, and modify the front-end datax components to divide data sources according to readable and writable

I fixed it by using the rdbms plugin as default temporarily. But I am not good at front end 😄 .
