### ISSUE TITLE
[Bug] [Document] 调用 open-api错误

### ISSUE THREAD

**Issue by dwf0317** [apache/dolphinscheduler#14191]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

调用 projects/list-paging 接口报错，返回参数如下：
{
    "code": 10047,
    "msg": "query project details by code error",
    "data": null,
    "failed": true,
    "success": false
}

### What you expected to happen

返回参数有问题

### How to reproduce

直接调用http://xxx.xxx.xxx.xx:12345/dolphinscheduler/projects/list-paging?searchVal=xx&pageNo=1&pageSize=20

### Anything else

![2](https://github.com/apache/dolphinscheduler/assets/58978407/4cea304b-d53b-45a3-97e4-fbd300780932)

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please use english to describe. Closing this issue.
