### ISSUE TITLE
[Bug] When I terminated the seatunnel cdc task, it wasn't really terminated  

### ISSUE THREAD

**Issue by liuxu2630** [apache/dolphinscheduler#14222]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

first, this is a seatunnel mysqlcdc to doris task.
the runtime is ok, when click "终止" on "工作流实例", seatunnel node process(pid) not terminated, task is still runing.

### What you expected to happen

ds version: 3.1.7
seatunnel version: 2.3.1

### How to reproduce

first, this is a seatunnel mysqlcdc to doris task.
the runtime is ok, when click "终止" on "工作流实例", seatunnel node process(pid) not terminated, task is still runing.
<img width="403" alt="image" src="https://github.com/apache/dolphinscheduler/assets/8241065/bdb30e7b-0019-4699-8e22-c5bcc77089d4">

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cjhnbls** [comment]
请问你的问题解决了吗，我也遇到了相同的情况

**Comment by liuxu2630** [comment]
> 请问你的问题解决了吗，我也遇到了相同的情况

没有

**Comment by dzygoon** [comment]
你知不知道最新版本的ds解决这个问题没有？
