### ISSUE TITLE
/dolphinscheduler/projects/{projectCode}/executors/start-process-instance responsed null of the "data" item

### ISSUE THREAD

**Issue by ptrjeffrey** [apache/dolphinscheduler#14224]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I use postman to call the process
```js
var axios = require('axios');
var data = '';

var config = {
   method: 'post',
   url: 'http://192.168.88.100:12345/dolphinscheduler/projects/9683443218016/executors/start-process-instance?failureStrategy=CONTINUE&processDefinitionCode=9683451224416&processInstancePriority=MEDIUM&scheduleTime=empty&warningType=ALL&projectCode=9683443218016',
   headers: { 
      'Accept': 'application/json', 
      'token': '{{token}}', 
      'User-Agent': 'Apifox/1.0.0 (https://www.apifox.cn)', 
      'Content-Type': 'application/json'
   },
   data : data
};

axios(config)
.then(function (response) {
   console.log(JSON.stringify(response.data));
})
.catch(function (error) {
   console.log(error);
});
```
and got the result
```json
{
    "code": 0,
    "msg": "success",
    "data": null,
    "success": true,
    "failed": false
}
```

### What you expected to happen

i wnat the detials of the process-instance
such as
name,
code
version
...
because i can't track into the new process-instance after it has been created.
i don't know how to check the staus of the process-instance

### How to reproduce

it always happen.

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SerenityDwc** [comment]
do you know how to send startParams?  i use this interface send startParams ，but do not work, do not get params in dolphinscheduler node
兄弟，你知道start-process-instance这个接口怎么传startParams 参数么，我试了下传json字符传，但是在dolphinscheduler流程节点中没有接收到
![image](https://github.com/apache/dolphinscheduler/assets/42405633/24fe6b9e-839b-47a7-8fff-13db4e85cc7b)
![image](https://github.com/apache/dolphinscheduler/assets/42405633/9929d507-3325-445b-a5d3-3188ab1d412e)
![image](https://github.com/apache/dolphinscheduler/assets/42405633/ea037075-adee-451b-a4b3-30ee70d574fe)

**Comment by ptrjeffrey** [comment]
没有试过

**Comment by ptrjeffrey** [comment]
我这边传是可以显示的
![image](https://github.com/apache/dolphinscheduler/assets/13477121/8b2b1b4b-38f4-4b7f-a54f-4606e0ff1421)
执行结果
![image](https://github.com/apache/dolphinscheduler/assets/13477121/96f72d82-a3e6-485e-9d07-2d224dccd4c6)
你试试把body换成params

**Comment by SerenityDwc** [comment]
你用的哪个版本，我试了仍然不行，不确定是不是版本的原因，我是直接在shell节点中接收
![image](https://github.com/apache/dolphinscheduler/assets/42405633/235c76cb-0a43-49cc-b539-55799a4314ba)
![image](https://github.com/apache/dolphinscheduler/assets/42405633/93ecd714-22ef-4d55-914a-fdc6322721f5)
![image](https://github.com/apache/dolphinscheduler/assets/42405633/fab85a34-8e8b-4267-8452-266e184996c4)

**Comment by ptrjeffrey** [comment]
3.1.6 
我这边没问题，现在就是返回的data是null，参数可以在shell中正常传递

**Comment by SerenityDwc** [comment]
好的  那可能是版本的问题  我用的还是2.0.6，我换个版本试试，非常感谢~

**Comment by SbloodyS** [comment]
Fixed.
