### ISSUE TITLE
[feature][master] foreach feature

### ISSUE THREAD

**Issue by QiuMingJie** [apache/dolphinscheduler#14223]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

when i use dolphinschedule to build a pipeline 
 i use a Python script but it output params is a list  , i want to foreach the list to trigger the next step Python script.
but i found that dolphinschedule is not support 

### Use case

i want a foreach feature that can foreach my list and one by one to trigger next step feature

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by haibingtown** [comment]
@SbloodyS I’m grateful for your detailed issue report. Could you please assign it to me so that I can begin investigating and addressing it promptly.

**Comment by SbloodyS** [comment]
> @SbloodyS I’m grateful for your detailed issue report. Could you please assign it to me so that I can begin investigating and addressing it promptly.

I've assigned to you. Looking forward to your contribution.
