### ISSUE TITLE
[Feature][Task] Support yarn queue definition in yarn task

### ISSUE THREAD

**Issue by Radeity** [apache/dolphinscheduler#14251]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Yarn queue is deprecated in version 3.x. We should remove queue in `Tenant`, and support to define yarn queue in task definition page for Spark/Flink/MR/etc tasks which can run on Yarn.

### Related issues

https://github.com/apache/dolphinscheduler/issues/14240
https://github.com/apache/dolphinscheduler/issues/14236

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ORuteMa** [comment]
In fact, I believe that specifying queues for users or tenants instead of defining them in specific task definitions is a good design. This allows Dolphin administrators within an organization to have control over YARN resources.
However, the current simultaneous definition of queues at both the user and tenant levels may be a bit confusing. We should have detailed documentation to illustrate this design through some examples.
Please let me know what do you think about this? @Radeity @EricGao888 @zhongjiajie

**Comment by Radeity** [comment]
Hi, @ORuteMa , actually, in current version (3.x), queue is already deprecated. Then, I think queue is task-related, DS has supported many types of tasks now, not all types of task use yarn queue. Thus, I don't recommend to keep user-level or tenant-level queue, WDYT? 

Feel free to discuss about it :D

**Comment by ORuteMa** [comment]
Let's align an understanding, by `queue is already deprecated` you mean that the queue is deprecated at the `task level`, right? Queue at user/tenant level actually take affect as my practice shows in https://github.com/apache/dolphinscheduler/pull/14237.  Keep queue in task-level can lead to arbitrary use of YARN resources and I think it's the reason for its deprecation.

User/tenant level queue needs to be used by the specific task type such as Flink, and tasks not related to YARN can just ignore it.

**Comment by Radeity** [comment]
> Queue at user/tenant level actually take affect as my practice shows in https://github.com/apache/dolphinscheduler/pull/14237.

It's weird, do you mean queue of user/tenant can be set to your Flink/Spark task? I don't find where the evaluation takes effect in codes. Would you like to help locate it?

> Keep queue in task-level can lead to arbitrary use of YARN resources and I think it's the reason for its deprecation.

You said it inconvenient for user to define queue in task definition page, and we can not avoid this arbitrary usage, cuz user can still define the yarn queue option by themselves.

**Comment by ORuteMa** [comment]
> > Queue at user/tenant level actually take affect as my practice shows in #14237.
> 
> It's weird, do you mean queue of user/tenant can be set to your Flink/Spark task? I don't find where the evaluation takes effect in codes. Would you like to help locate it?
> 
> > Keep queue in task-level can lead to arbitrary use of YARN resources and I think it's the reason for its deprecation.
> 
> You said it inconvenient for user to define queue in task definition page, and we can not avoid this arbitrary usage, cuz user can still define the yarn queue option by themselves.

Sorry for my late reply. For example, in FlinkArgsUtils class, you can find the queue is in FlinkParameters, FlinkParameters obtain the queue from ProcessInstance in 3.1.7 branch (User queues have priority over tenant queues). But I find it is miss in dev, so weird! Regrading queue option from task form, maybe we can just ignore them and give a tip.

**Comment by ORuteMa** [comment]
We should add the logic back in dev. you can find it in BaseTaskProcessor line 314 on 3.1.7

**Comment by Radeity** [comment]
> you can find it in BaseTaskProcessor line 314 on 3.1.7

Get it, thanks, however, we should find in which PR it's removed and for what reason first. cc @zhongjiajie

**Comment by Radeity** [comment]
Hi, @ORuteMa , it's removed in https://github.com/apache/dolphinscheduler/pull/13825, cuz we can not get the queue of default tenant.

`Queue` is deprecated because it's just a logical management, not associated with remote yarn queue. If you want to keep this queue parameter for one tenant or one project and use this parameter to write your options, you can set project-level parameters instead, related issue(https://github.com/apache/dolphinscheduler/issues/14241, https://github.com/apache/dolphinscheduler/issues/14076)

Also, there's no way to avoid arbitrary use of YARN resources in original or current way, maybe you can configure this role control on Yarn side :D
