### ISSUE TITLE
[Bug] [Seatunnel] Run Mode defaults to run, and you cannot select a null value

### ISSUE THREAD

**Issue by zyfjrx** [apache/dolphinscheduler#14250]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When Dolphinscheduler creates a seattunnel task, if the Flink startup script is used, the Run Mode defaults to run, and a null value cannot be selected. As a result of this operation, when seatunnel invokes the Flink service to perform tasks, --run-mode run will be spliced by default in the execution command, but the run-mode parameter is not supported in multiple flink versions (tested 1.13 1.14 1.15 1.16 1.17), and finally Task execution failed.
![image](https://github.com/apache/dolphinscheduler/assets/134594723/81668802-28c7-48c2-b39d-f627b8d800f2)

### What you expected to happen

It is expected that a none option can be added, and the backend logic judges whether to splice the default parameters based on this field.
![image](https://github.com/apache/dolphinscheduler/assets/134594723/410a1757-40ea-45fb-8a35-a1c2d522e988)

### How to reproduce

Create a seatunnel task and select the flink engine RunMode as run by default. When executing the task, the --run-mode run parameter will be spliced, but the run-mode parameter is not supported in multiple flink versions (tested 1.13 1.14 1.15 1.16 1.17), and the final task Execution failed.
![image](https://github.com/apache/dolphinscheduler/assets/134594723/572c64f9-f07d-4f4d-bb2c-97f6692f01cb)
![image](https://github.com/apache/dolphinscheduler/assets/134594723/f0860b21-aee5-4f4f-92b9-bd4556c54861)

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Miracle-wcg** [comment]
抄袭的可以 https://www.ithere.net/article/1648958805961310210

**Comment by zyfjrx** [comment]
是参考前辈实现思路 但是我提交pr前并未发现有相关pr提交 ，所以我及时提交pr为社区用户带来更好使用体验有什么问题吗 @Miracle-wcg
