### ISSUE TITLE
[Bug] [Task Group] no matter whether user is admin or non-admin, they can only use the task group created by themselves

### ISSUE THREAD

**Issue by hc-leo** [apache/dolphinscheduler#14269]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Task group is at user level so that cannot be shared among multiple users. 

~~An non-admin user cannot select the task group created by others/admin when creating a task~~

~~In another word, non-admin user can only see the task group created by himself, which makes the task group an useless function.~~

### What you expected to happen

~~After a task group being created, the admin should have the option to authorize this task group to an ordinary user in User Manage page. (Now there are only file resource and udf resource can be authorized)~~

Task group should be project level or an option should be given so that this group can be shared among users.

### How to reproduce

1. Login as User A and create a project and a task group related to this project.
2. Authorize the project to user B.
3. Login in as user B and create a Task. Click "Task group name" and the drop-down box shows nothing.

### Anything else

There is no option to allow normal users to access this resource in Security management page or Resources.

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Good catch, technically, no matter whether user is admin or non-admin, they can only use the task group created by themselves, you can change to a clearer issue title :D
https://github.com/apache/dolphinscheduler/blob/85b581b232f22cbb382b0f133bd9aa041edd0178/dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskGroupMapper.xml#L125-L133

I think task group should be project level, and in this way, we don't have to add task group authorization, WDYT?

**Comment by hc-leo** [comment]
> Good catch, technically, no matter whether user is admin or non-admin, they can only use the task group created by themselves, you can change to a clearer issue title :D
> 
> https://github.com/apache/dolphinscheduler/blob/85b581b232f22cbb382b0f133bd9aa041edd0178/dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskGroupMapper.xml#L125-L133
> 
> I think task group should be project level, and in this way, we don't have to add task group authorization, WDYT?

Thanks for your paraphrase, that's definitely what I want to say

**Comment by Radeity** [comment]
Current design is unreasonable, I will help to improve this.

**Comment by Radeity** [comment]
Hi, @hc-leo , welcome to join the discussion https://github.com/apache/dolphinscheduler/pull/14392#discussion_r1244743244 :D
