### ISSUE TITLE
[Bug] [Task] Workflow task offline deletion of resource center jar package issue

### ISSUE THREAD

**Issue by StandByLin** [apache/dolphinscheduler#14266]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

If the Spark program in the workflow is offline and the jar package in the resource is deleted, and a new jar is replaced, the workflow cannot be run again, and the workflow log viewed on the web page is empty.

### What you expected to happen

I think it's a cache issue, but I checked the configuration of the dolphinscheduler and found that the cache is not enabled

### How to reproduce

Need to offline spark scala tasks.
Delete the task main package in the Resource Center.
Upload the jar package again.
Re select the main package in the workflow task and run it online.

### Anything else

After the problem occurs, I need to create a new task flow, and copying the task flow will also cause an error

### Version

3.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi, @StandByLin , there are some related bug report and fix: https://github.com/apache/dolphinscheduler/issues/13656, https://github.com/apache/dolphinscheduler/pull/13878

**Comment by StandByLin** [comment]
Thank you. I saw that this bug was fixed in version 3.2.0, so I need to upgrade to version 3.2.0 before trying again.
