### ISSUE TITLE
When can I support Kettle scheduling

### ISSUE THREAD

**Issue by 172151295** [apache/dolphinscheduler#14277]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

什么时候能够支持Kettle调度

### Use case

可以支持调度Kettle的数据资源库、文件资源库、本地KTR、KJB、的调度

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sxiongzhang** [comment]
I'm looking forward to this feature ！

**Comment by lightnear** [comment]
I'm looking forward to this feature ！

**Comment by 172151295** [comment]
I'm looking forward to this feature ！

**Comment by ahuljh** [comment]
I am willing to submit a PR.

**Comment by ahuljh** [comment]
I am willing to submit a PR!
