### ISSUE TITLE
[Bug] [workflow] workflow instance status error #14026

### ISSUE THREAD

**Issue by xiangtao** [apache/dolphinscheduler#14276]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

workflow instance status failed , but task instance status success in this workflow instance

![image](https://github.com/apache/dolphinscheduler/assets/2025439/9ec9eb89-1905-44f8-8927-d4eccb5910fc)
![image](https://github.com/apache/dolphinscheduler/assets/2025439/4cdd841b-77d3-41bf-a3be-5353418512b5)

### What you expected to happen

 workflow instance status is success

### How to reproduce

i has reproduce ,  it cause for  a db connection error 

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ORuteMa** [comment]
Any logs?
