### ISSUE TITLE
[Bug] [Module Name] Bug title 

### ISSUE THREAD

**Issue by comgoal** [apache/dolphinscheduler#14308]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

dolphinscheduler3.1.x api server start error, org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.apache.dolphinscheduler.common.enums.WarningType

### What you expected to happen

dolphinscheduler3.1.x api server start successful!

### How to reproduce

dolphinscheduler3.1.x api server start error, org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.apache.dolphinscheduler.common.enums.WarningType

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
Please change the Bug title
