### ISSUE TITLE
[Bug] [Deploy]The modified common.properties didn't work in k8s dockerfile with copy command!

### ISSUE THREAD

**Issue by XQFHNB** [apache/dolphinscheduler#14302]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After deployed the dolphhinscheduler by k8s, I wanted to create a tenant, but it happend '创建租户错误'

![image](https://github.com/apache/dolphinscheduler/assets/16623698/86078054-db84-41d5-8a37-cbd1e05e3fa5)

From then pod,I got the log 
```sql
[INFO] 2023-06-07 17:55:58.708 +0800 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[91] - REQUEST TRACE_ID:7e600b79-4d4f-4b49-9a1d-f188226fd135, LOGIN_USER:admin, URI:/dolphinscheduler/tenants/verify-code, METHOD:GET, HANDLER:org.apache.dolphinscheduler.api.controller.TenantController.verifyTenantCode, ARGS:{tenantCode=ddd}
[INFO] 2023-06-07 17:55:59.019 +0800 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[91] - REQUEST TRACE_ID:7e5884fb-bfff-43e1-b68a-3d4a7db708b3, LOGIN_USER:admin, URI:/dolphinscheduler/tenants, METHOD:POST, HANDLER:org.apache.dolphinscheduler.api.controller.TenantController.createTenant, ARGS:{queueId=1, description=, tenantCode=ddd}
[ERROR] 2023-06-07 17:55:59.027 +0800 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[53] - 创建租户错误
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.service.storage.impl.HadoopUtils.mkdir(HadoopUtils.java:293)
	at org.apache.dolphinscheduler.service.storage.impl.HadoopUtils.createTenantDirIfNotExists(HadoopUtils.java:268)
	at org.apache.dolphinscheduler.api.service.impl.TenantServiceImpl.createTenant(TenantServiceImpl.java:160)
	at org.apache.dolphinscheduler.api.service.impl.TenantServiceImpl$$FastClassBySpringCGLIB$$fcc8d845.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
```
maybe it depended on hadoop, then I read the source code 

![image](https://github.com/apache/dolphinscheduler/assets/16623698/d35a9f3c-c252-4ec3-99f5-465ac616cc33)

I changes the common.properties  from `resource.storage.type=HDFS`  to `resource.storage.type=NONE` ,and then built then image by `COPY common.properties /opt/dolphinscheduler/conf` in dockerfile. but it did'nt work. 
In then pod ,the file didn't change 
![image](https://github.com/apache/dolphinscheduler/assets/16623698/14c21cdf-261d-4a71-bff1-611e0c3526ae)

I had tried a lot !!!

### What you expected to happen

the file  common.properties   changed  and created tenants successfully!

### How to reproduce

deploy by  k8s ,then create tenant

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by XQFHNB** [comment]
你好，你的邮件已经收到，谢谢！~

**Comment by rickchengx** [comment]
Hi, @XQFHNB Whether files can be copied into the image should be a problem limited to `docker`, and has nothing to do with ds itself. Could you please provide more information on how you built the image.

**Comment by XQFHNB** [comment]
I found the point, changed vaules.yaml from   `resource.storage.type=HDFS`  to `resource.storage.type=NONE`

**Comment by SoWhat-ET** [comment]
> 我找到了重点，将 vaules.yaml 从 更改 `resource.storage.type=HDFS` 为`resource.storage.type=NONE`

Did you solve the problem, I solved the same problem：

[ERROR] 2023-07-10 12:11:46.810 +0800 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[53] - 创建租户错误
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.service.storage.impl.HadoopUtils.mkdir(HadoopUtils.java:293)
        at org.apache.dolphinscheduler.service.storage.impl.HadoopUtils.createTenantDirIfNotExists(HadoopUtils.java:268)
        at org.apache.dolphinscheduler.api.service.impl.TenantServiceImpl.createTenant(TenantServiceImpl.java:160)
        at org.apache.dolphinscheduler.api.service.impl.TenantServiceImpl$$FastClassBySpringCGLIB$$fcc8d845.invoke(<generated>)

**Comment by XQFHNB** [comment]
你好，你的邮件已经收到，谢谢！~

**Comment by ATM006** [comment]
May I ask if anyone has repaired it？

**Comment by XQFHNB** [comment]
你好，你的邮件已经收到，谢谢！~

**Comment by XQFHNB** [comment]
你好，你的邮件已经收到，谢谢！~

**Comment by XQFHNB** [comment]
你好，你的邮件已经收到，谢谢！~

**Comment by tuoluzhe8521** [comment]
需要将value.yaml中的配置修改为hdfs
common:
  ## Configmap
  configmap:
    RESOURCE_STORAGE_TYPE: "HDFS"
    FS_DEFAULT_FS: "file:///"
    DOLPHINSCHEDULER_OPTS: ""
    DATA_BASEDIR_PATH: "/tmp/dolphinscheduler"
    RESOURCE_UPLOAD_PATH: "/dolphinscheduler"
# resource storage type: HDFS, S3, OSS, GCS, ABS, NONE
    resource.storage.type: HDFS

**Comment by XQFHNB** [comment]
你好，你的邮件已经收到，谢谢！~

**Comment by XQFHNB** [comment]
你好，你的邮件已经收到，谢谢！~

**Comment by XQFHNB** [comment]
你好，你的邮件已经收到，谢谢！~

**Comment by XQFHNB** [comment]
你好，你的邮件已经收到，谢谢！~

**Comment by XQFHNB** [comment]
你好，你的邮件已经收到，谢谢！~

**Comment by XQFHNB** [comment]
你好，你的邮件已经收到，谢谢！~

**Comment by XQFHNB** [comment]
你好，你的邮件已经收到，谢谢！~

**Comment by XQFHNB** [comment]
你好，你的邮件已经收到，谢谢！~

**Comment by ZacharyBacon** [comment]
> > 我找到了重点，将 vaules.yaml 从更改`resource.storage.type=HDFS`为`resource.storage.type=NONE`
> 
> 你的问题解决了吗，我也遇到了同样的问题：
> 
> [错误] 2023-07-10 12:11:46.810 +0800 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[53] - 创建租户错误 java.lang.NullPointerException: null at org.apache.dolphinscheduler.service.storage.impl.HadoopUtils.mkdir(HadoopUtils.java:293) at org.apache.dolphinscheduler.service.storage.impl.HadoopUtils.createTenantDirIfNotExists(HadoopUtils.java:268) at org.apache.dolphinscheduler.api.service.impl.TenantServiceImpl.createTenant(TenantServiceImpl.java:160) at org.apache.dolphinscheduler.api.service.impl.TenantServiceImpl$$FastClassBySpringCGLIB$$fcc8d845.invoke()

这个问题我解决了，我是用的本地存储的，把resource.hdfs.fs.defaultFS改成file:/// 这样就可以了，你可以试下
![image](https://github.com/user-attachments/assets/5503470e-52b7-4448-8b78-10b867674fa1)

**Comment by XQFHNB** [comment]
你好，你的邮件已经收到，谢谢！~
