### ISSUE TITLE
[Bug] [DataQuality] After the task is finished running, when the data quality result is ready to be inserted, the deserialization of connectionJson reports an error

### ISSUE THREAD

**Issue by PZh101** [apache/dolphinscheduler#14327]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

在dev分支下业务数据库使用mysql，数据库连接为：jdbc:mysql://127.0.0.1:3306/dolphinscheduler?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai，在运行数据质量检测任务时，url反序列化报错

### What you expected to happen

任务正常运行

### How to reproduce

使用mysql作为dolphinscheduler的数据库时，正常创建一个数据质量任务，并运行，出现connectionJson反序列化异常
debug截图：
第一次读取界面上配置数据源信息中读取数据库信息，正确，other字段为json
![image](https://github.com/apache/dolphinscheduler/assets/110721876/c5d2ba72-31e8-4efd-b43d-cd640288adc7)
第二次从datasource中读取数据源信息，other字段变为了string类型
![image](https://github.com/apache/dolphinscheduler/assets/110721876/487304bc-343d-4328-949b-fc540f71aaf0)

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TFE-HardView** [comment]
3.2的版本这个问题没有修复

**Comment by TFE-HardView** [comment]
<img width="1079" alt="image" src="https://github.com/apache/dolphinscheduler/assets/52032039/27f77efd-6448-4454-a30b-a1796d4a3cfb">

**Comment by viosay** [comment]
I also encountered this problem.
