### ISSUE TITLE
[Bug] [Seatunnel] flink task executed failure

### ISSUE THREAD

**Issue by k8slight** [apache/dolphinscheduler#14323]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when used start-seatunnel-flink-15-connector-v2.sh with "run" mode, the task executed failure!

### What you expected to happen

The task was executed successfully

### How to reproduce

using seatunnel run flink task with run mode

### Anything else

flink version：1.16.1
seatunnel：2.3.1
logs
![image](https://github.com/apache/dolphinscheduler/assets/56961637/8ed8e679-7e02-4ff9-b432-3cefaf165379)
The task was executed in local server with --run-mode
![image](https://github.com/apache/dolphinscheduler/assets/56961637/7bfff944-96d1-4454-84d5-ce4aab939ee1)
The task was executed in local server without --run-mode,
![image](https://github.com/apache/dolphinscheduler/assets/56961637/023c43d5-0266-4bf8-bde3-c660cb74e2a7)

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zyfjrx** [comment]
https://github.com/apache/dolphinscheduler/pull/14267

**Comment by zyfjrx** [comment]
@k8slight

**Comment by k8slight** [comment]
> #14267

THX

**Comment by k8slight** [comment]
closed
