### ISSUE TITLE
[Bug] [MASTER SERVER] task run failed，master server prompt NPE(3.1.7)

### ISSUE THREAD

**Issue by zui01** [apache/dolphinscheduler#14322]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

My workflow defines a shell task that will use many custom parameters, many resource center files.
When I run the workflow, no task instance is generated, and also when I click in the workflow instance screen to see the log of the shell task, there is no log button.
When I click on stop workflow, it keeps getting stuck in the ready to stop state.
At the same time master's logs are growing fast

<img width="800" alt="image" src="https://github.com/apache/dolphinscheduler/assets/54675044/b1f84303-ced5-4748-9ee3-cccb04d49e64">
<img width="808" alt="image" src="https://github.com/apache/dolphinscheduler/assets/54675044/83ddb373-8e5f-4348-aa09-9fa08c8eea25">
<img width="814" alt="image" src="https://github.com/apache/dolphinscheduler/assets/54675044/841d71f2-f7f1-4e8f-a5c3-aba33467b825">
<img width="807" alt="image" src="https://github.com/apache/dolphinscheduler/assets/54675044/61b1fd7e-a90c-45cc-bea6-18a209292004">

### What you expected to happen

i do not care the log or the workflow bug.i just want the task can run .
Same shell task. This problem does not occur when I create new projects, workflows and tasks.
But it does it a few more times I run it, as soon as it appears the first time. After that, it keeps happening when I run the task. This causes my shell task to not run and blocks my core workflow.
I just wish I could get a quick way around this bug, like modifying the database etc.

### How to reproduce

1.run the work flow
2.then you can see the there is not a taskinstance.
3.the log will flash

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zui01** [comment]
我绕过了这个bug。首先在任务节点里把资源中心引入的文件删了，然后资源中心重新上传更改后的，在重新引用。
这个bug我估计是有人没更改任务节点，只在资源中心重新上查了同名文件。但是文件ID变了。所以执行任务时当然空指针了。

**Comment by HomminLee** [comment]
@Anubisxcw  This issue is very similar to https://github.com/apache/dolphinscheduler/pull/13980#issuecomment-1537112956, but it was fixed at 3.1.6. Maybe can provide you with some ideas.
