### ISSUE TITLE
[Feature][API] Support to complement data in descending or ascending order of date.

### ISSUE THREAD

**Issue by calvinjiang** [apache/dolphinscheduler#14321]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently the DolphinScheduler doesn't support to complement data in descending or ascending order of date. If I'd like to complement data for 365 days I have to wait for all 365 parallel workflows to be done. That's really inconvenient.  So I expect that the system can support to complement data in descending or ascending order of date.

![image](https://github.com/apache/dolphinscheduler/assets/4928204/e216c054-3621-411f-ae69-f9a4ed7b3b05)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good job
Using screenshot in English environment will be better!
