### ISSUE TITLE
[Feature] Organize workflows and tasks with directories

### ISSUE THREAD

**Issue by rickchengx** [apache/dolphinscheduler#14333]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, it is not possible to create a directory in the workflow definition list to customize the organization of the workflow. When there are a large number of workflows, it will appear very messy. 

This pr hopes to organize workflows through directories, and since tasks belong to a certain workflow, task definitions will naturally be organized by directories.

# UI
## Process Definition Page
<img width="1792" alt="截屏2023-07-12 16 12 08" src="https://github.com/apache/dolphinscheduler/assets/38122586/87462f8d-f890-42fe-9ef4-3f337371e030">

* Show subcategories and subprocesses
* Support to create directories
* The operations supported by the directory include modification and deletion

## Task Definition Page
![image](https://github.com/apache/dolphinscheduler/assets/38122586/e02c8384-509c-4020-bd03-fdfd27030e60)

* Show subcategories and subtasks
* Directory does not support any operations

# Metadata
* Add column of `t_ds_process_definition`
  * `parent_directory_code`: the code of the parent directory or 0 if the parent directory is the root of the project
* Add `t_ds_process_definition_directory` 
  * id
  * name
  * code
  * parent_directory_code:  the code of the parent directory or 0 if the parent directory is the root of the project
  * project_code
  * user_id
  * ...

The current solution is to add a new table `t_ds_process_definition_directory`  for storing directoy entities, and add a column in `t_ds_process_definition` to store directory codes.

If we do not add a new table (for example, just add a tag in the process definition), we cannot save the directory created by the user. And it will also become very complicated when querying workflows and subdirectories under a certain directory.

# RESTful API
### createProcessDefinitionDirectory
<img width="1119" alt="image" src="https://github.com/apache/dolphinscheduler/assets/38122586/e695a547-a5d7-46ef-a60c-36dc2ec281d4">

### updateProcessDefinitionDirectory
<img width="1107" alt="image" src="https://github.com/apache/dolphinscheduler/assets/38122586/2385480b-c899-4ac7-8700-7e498f728d05">

### deleteProcessDefinitionDirectory
<img width="1112" alt="image" src="https://github.com/apache/dolphinscheduler/assets/38122586/cdd05b62-821c-4b6f-b490-83cd277ee40e">

### createProcessDefinition
* Add `parent_directory_code`, which means creating a workflow in a certain directory
### queryProcessDefinitionListPaging
* Add `parent_directory_code` to return all process definition and subdirectories under a certain directory
* Add an `isDirectory` field to the returned result entity, indicating whether it is a directory
### queryTaskDefinitionListPaging
* A directory of a task is consistent with the workflow it belongs to
* Add `parent_directory_code` to return all task definition and subdirectories under a certain directory

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by c3Vu** [comment]
I am interested in working on the ui part
