### ISSUE TITLE
There is no sqoop part in the official website document

### ISSUE THREAD

**Issue by 464473310** [apache/dolphinscheduler#14375]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

There is no sqoop part in the official website document

### Documentation Links

https://dolphinscheduler.apache.org/zh-cn/docs/3.1.7

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by QuakeWang** [comment]
Please assign it to me, I will fix it : )
