### ISSUE TITLE
Could not find any factory for identifier 'jdbc'

### ISSUE THREAD

**Issue by misszhangss** [apache/dolphinscheduler#14380]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

创建了一个flink 工作流，日志提示：lib包下加入了如下依赖：

![image](https://github.com/apache/dolphinscheduler/assets/84503545/5a24f804-dc52-4ec9-b533-3c69b2a9f2d9)

![image](https://github.com/apache/dolphinscheduler/assets/84503545/e816323d-db1d-4a0d-b8d9-df04774fb7d3)

![image](https://github.com/apache/dolphinscheduler/assets/84503545/04df641a-1847-4c42-8265-ea72c34292e4)

![image](https://github.com/apache/dolphinscheduler/assets/84503545/80c516a0-8d6c-4975-80e8-381d1366790d)

### What you expected to happen

能正常执行flink工作流

### How to reproduce

创建一个flink工作流

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by misszhangss** [comment]
flink 1.17

**Comment by ligenhw** [comment]
@misszhangss you should add the   flink-connector-jdbc-xxx.jar   to $FLINK_HOME/lib,  but not your dolphinscheduler lib package
