### ISSUE TITLE
[Feature][Improvement] reset user password

### ISSUE THREAD

**Issue by QiuMingJie** [apache/dolphinscheduler#14387]
### Description

sometime some user had forgot their password , the ask me to reset their password .
althought i have admin account ,but i found that i can not reset other user password.
maybe you can add this feature in account edit dialog

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sqxinquan** [comment]
1. Change the password in the database 2. Administrators can reset the password of other users

**Comment by QiuMingJie** [comment]
> 1. Change the password in the database 2. Administrators can reset the password of other users

how can i reset the password by using the Administrators account , i can not found reset password button .

![image](https://github.com/apache/dolphinscheduler/assets/31579433/208834c8-4a6c-4119-b94a-73ffca332b58)

**Comment by pppppjcc** [comment]
The user administration does not have a reset password button and can only change it from the database

**Comment by davidzollo** [comment]
Administrator can reset the password for users in the UI.
If anybody who'd like to submit a PR to let user change his password in the UI, please leave a msg

**Comment by calvinjiang** [comment]
I'll deal with this feature.
