### ISSUE TITLE
mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'

### ISSUE THREAD

**Issue by hongxiaa** [apache/dolphinscheduler#14383]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

docker pull dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler-master:3.1.7
3.1.7: Pulling from apache/dolphinscheduler-master
mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'

docker 拉镜像报这个错，从3.1.5开始都拉不下来

### What you expected to happen

镜像问题

### How to reproduce

docker 拉镜像报这个错，从3.1.5开始都拉不下来

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ken-elsheezy** [comment]
Having this exact same issue

**Comment by SbloodyS** [comment]
cc @zhuangchong @zhongjiajie

**Comment by zhongjiajie** [comment]
It works for me just now.

<img width="757" alt="image" src="https://github.com/apache/dolphinscheduler/assets/15820530/6bb9ec23-5ae2-4d31-bc55-9c7018b635e6">

if you can not pull from this registry please try `apache/dolphinscheduler-master:3.1.7` directly @hongxiaa  @ken-elsheezy 

```diff
- docker pull dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler-master:3.1.7
+ docker pull apache/dolphinscheduler-master:3.1.7 
```

**Comment by zhongjiajie** [comment]
close due to no response
