### ISSUE TITLE
[Improvement][Resource Center] Remove deprecated resource description in api and UI page

### ISSUE THREAD

**Issue by Radeity** [apache/dolphinscheduler#14393]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In new resource center, description of resource is deprecated.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
good catch, I had add it to 3.2.0 checklist https://github.com/apache/dolphinscheduler/issues/14372
