### ISSUE TITLE
[Feature][DataLake] FAdd the dispatching function of Data lakeeature title

### ISSUE THREAD

**Issue by sqxinquan** [apache/dolphinscheduler#14399]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

At present, there is only data warehouse scheduling, and Data lake scheduling can be considered，hudi   and iceberg  paimon

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @sqxinquan , can you provide more details?
