### ISSUE TITLE
[Bug] [api] After the workflow is exported and imported again, no newly imported task definition appears on the workflow definition page

### ISSUE THREAD

**Issue by penggeyuanlishe** [apache/dolphinscheduler#14397]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Create a workflow "testImport":
![image-20230622145541802](https://github.com/apache/dolphinscheduler/assets/109343165/b51ab5a5-f8a1-4c80-8b0c-d6b7e6739c85)

The workflow has a task definition "testShell": 
![image-20230622145656524](https://github.com/apache/dolphinscheduler/assets/109343165/8044d6e6-bf21-46f7-9dd7-88cd11ae7cb1)

Export the workflow and import it again: 
![image-20230622145840607](https://github.com/apache/dolphinscheduler/assets/109343165/77b964ad-2273-4c9a-8b22-ec4af1bca913)

No task definition related to the imported workflow "testImport(1)_import_20230622145806508" was found in the task definition page: 
![image-20230622145928440](https://github.com/apache/dolphinscheduler/assets/109343165/23fea5e9-7080-4374-96b8-46e645233fe2)

### What you expected to happen

On the task definition page, you should list the newly imported workflow "testImport(1)_import_20230622145806508" and the associated task definition "testShell".

### How to reproduce

Refer to "What happened"

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by penggeyuanlishe** [comment]
https://github.com/apache/dolphinscheduler/pull/14398
上述方案思路如下：
查看任务定义页面的接口：
![image-20230622175406766](https://github.com/apache/dolphinscheduler/assets/109343165/ba3a41ad-d379-4c2b-93cc-d3c258d3d9e2)

找到对应源码，发现该接口的 taskExecuteType 有默认值，为 "BATCH"：
![image-20230622180920272](https://github.com/apache/dolphinscheduler/assets/109343165/8f65f3a3-17c2-4e16-8c4c-37d447541ae9)

继续跟踪源码，找到对应的SQL语句：
![image-20230622181035358](https://github.com/apache/dolphinscheduler/assets/109343165/5da06da5-3ff2-4dae-a21c-67e86f4f2d55)

由于 taskExecuteType 有默认值"BATCH"，不会为空，所以`and td.task_execute_type = #{taskExecuteType.code}`该代码将会执行。到数据库一看，刚才导入的工作流对应的 task_execute_type 果然为空：
![image-20230622181336899](https://github.com/apache/dolphinscheduler/assets/109343165/144d0c46-18c6-4e46-a78c-a7163e8982f1)

排查原因，发现在 org.apache.dolphinscheduler.api.service.impl.ProcessDefinitionServiceImpl#checkAndImport 方法中，
org.apache.dolphinscheduler.dao.entity.TaskDefinitionLog 类的构造方法，未将该值赋值进去，所以导致 TaskDefinitionLog 对象中的 taskExecuteType 并未赋值，因此存入数据库中即为 null 。
![image-20230622181647773](https://github.com/apache/dolphinscheduler/assets/109343165/031b1041-3522-4559-987e-58e151e0ec8a)

于是，解决方案便是修改该构造方法：
![image-20230622181943695](https://github.com/apache/dolphinscheduler/assets/109343165/6a316c00-c596-4bee-8d9c-21ef96cbd14d)

**Comment by rickchengx** [comment]
@penggeyuanlishe thanks for your excellent work
