### ISSUE TITLE
[Bug] [Resource Center] Resource need to reselect in workflow after replace jar file

### ISSUE THREAD

**Issue by Chris-playground** [apache/dolphinscheduler#14416]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I developed a jar plugin to cooperate with workflow to finished some task, after i make some changes in this jar, i replace the jar file in the resource center with the same name(delete the old one and upload a new one).
Then i select the new resource file in task shell.
However, i rerun the workflow and it failed at start workflow.
![image](https://github.com/apache/dolphinscheduler/assets/48941586/149d260e-277f-49ea-a44c-9af5fec5710f)
I need to delete the workflow and create a new one, then it will run normally.

### What you expected to happen

I think it would be better that there is a replace button in resource center to replace files without any other operations.

### How to reproduce

change the resource jar file and select it in task and run workflow

### Anything else

version: 3.0.0

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This issue will be fix in 3.2.0.

**Comment by lrkkevin** [comment]
@Chris-Arith 你好，dolphinscheduler 跑java jar类型节点是怎么配置，可以给一个参考吗？我配置如图一直报错。
版本：3.2.0
配置图：
<img width="626" alt="image" src="https://github.com/apache/dolphinscheduler/assets/28940867/2d88e063-7dba-4b42-aaf7-1dbae3f0177a">

错误日志：
`[LOG-PATH]: /opt/dolphinscheduler/logs/20231213/11909357344768/2/404/936.log, [HOST]:  Host(ip=172.26.0.5, port=1234)
[INFO] 2023-12-13 21:29:51.361 +0800 - ***********************************************************************************************
[INFO] 2023-12-13 21:29:51.363 +0800 - *********************************  Initialize task context  ***********************************
[INFO] 2023-12-13 21:29:51.363 +0800 - ***********************************************************************************************
[INFO] 2023-12-13 21:29:51.363 +0800 - Begin to initialize task
[INFO] 2023-12-13 21:29:51.363 +0800 - Set task startTime: 1702474191363
[INFO] 2023-12-13 21:29:51.363 +0800 - Set task appId: 404_936
[INFO] 2023-12-13 21:29:51.363 +0800 - End initialize task {
  "taskInstanceId" : 936,
  "taskName" : "java任务",
  "firstSubmitTime" : 1702474177413,
  "startTime" : 1702474191363,
  "taskType" : "JAVA",
  "workflowInstanceHost" : "172.26.0.6:5678",
  "host" : "172.26.0.5:1234",
  "logPath" : "/opt/dolphinscheduler/logs/20231213/11909357344768/2/404/936.log",
  "processId" : 0,
  "processDefineCode" : 11909357344768,
  "processDefineVersion" : 2,
  "processInstanceId" : 404,
  "scheduleTime" : 0,
  "executorId" : 1,
  "cmdTypeIfComplement" : 0,
  "tenantCode" : "default",
  "processDefineId" : 0,
  "projectId" : 0,
  "projectCode" : 11378479582976,
  "taskParams" : "{\"localParams\":[],\"rawScript\":\"\",\"resourceList\":[],\"runType\":\"JAR\",\"mainArgs\":\"\",\"jvmArgs\":\"-Dspring.profiles.active=prod -Dloader.main=com.jdyx.demo.starter.CcTask\",\"isModulePath\":false,\"mainJar\":{\"id\":-1,\"resourceName\":\"file:/opt/soft/upload/dolphinscheduler/default/resources/module/task-dolphin-demo.jar\",\"res\":null}}",
  "prepareParamsMap" : {
    "system.task.definition.name" : {
      "prop" : "system.task.definition.name",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "java任务"
    },
    "system.project.name" : {
      "prop" : "system.project.name",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : null
    },
    "system.project.code" : {
      "prop" : "system.project.code",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "11378479582976"
    },
    "system.workflow.instance.id" : {
      "prop" : "system.workflow.instance.id",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "404"
    },
    "in_val_month" : {
      "prop" : "in_val_month",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "2022-12-31"
    },
    "system.biz.curdate" : {
      "prop" : "system.biz.curdate",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "20231213"
    },
    "system.biz.date" : {
      "prop" : "system.biz.date",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "20231212"
    },
    "system.task.instance.id" : {
      "prop" : "system.task.instance.id",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "936"
    },
    "system.workflow.definition.name" : {
      "prop" : "system.workflow.definition.name",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "java任务工作流"
    },
    "system.task.definition.code" : {
      "prop" : "system.task.definition.code",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "11909350591617"
    },
    "system.workflow.definition.code" : {
      "prop" : "system.workflow.definition.code",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "11909357344768"
    },
    "system.datetime" : {
      "prop" : "system.datetime",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "20231213212937"
    }
  },
  "taskAppId" : "404_936",
  "taskTimeout" : 2147483647,
  "workerGroup" : "default",
  "delayTime" : 0,
  "currentExecutionStatus" : "SUBMITTED_SUCCESS",
  "endTime" : 0,
  "resources" : { },
  "dryRun" : 0,
  "paramsMap" : { },
  "cpuQuota" : -1,
  "memoryMax" : -1,
  "testFlag" : 0,
  "logBufferEnable" : false,
  "dispatchFailTimes" : 0
}
[INFO] 2023-12-13 21:29:51.364 +0800 - ***********************************************************************************************
[INFO] 2023-12-13 21:29:51.364 +0800 - *********************************  Load task instance plugin  *********************************
[INFO] 2023-12-13 21:29:51.364 +0800 - ***********************************************************************************************
[INFO] 2023-12-13 21:29:51.364 +0800 - Send task status RUNNING_EXECUTION master: 172.26.0.5:1234
[WARN] 2023-12-13 21:29:51.364 +0800 - Current tenant is default tenant, will use root to execute the task
[INFO] 2023-12-13 21:29:51.364 +0800 - TenantCode: default check successfully
[INFO] 2023-12-13 21:29:51.365 +0800 - WorkflowInstanceExecDir: /opt/soft/upload/tmp/dolphinscheduler/exec/process/default/11378479582976/11909357344768_2/404/936 check successfully
[INFO] 2023-12-13 21:29:51.365 +0800 - Download resources: {} successfully
[INFO] 2023-12-13 21:29:51.365 +0800 - Download upstream files: [] successfully
[INFO] 2023-12-13 21:29:51.365 +0800 - Task plugin instance: JAVA create successfully
[INFO] 2023-12-13 21:29:51.365 +0800 - Initialize java task params {
  "localParams" : [ ],
  "varPool" : null,
  "rawScript" : "",
  "mainJar" : {
    "id" : -1,
    "resourceName" : "file:/opt/soft/upload/dolphinscheduler/default/resources/module/task-dolphin-demo.jar",
    "res" : null
  },
  "runType" : "JAR",
  "mainArgs" : "",
  "jvmArgs" : "-Dspring.profiles.active=prod -Dloader.main=com.jdyx.demo.starter.CcTask",
  "resourceList" : [ ],
  "modulePath" : false
}
[INFO] 2023-12-13 21:29:51.365 +0800 - Success initialized task plugin instance successfully
[INFO] 2023-12-13 21:29:51.365 +0800 - Set taskVarPool: null successfully
[INFO] 2023-12-13 21:29:51.365 +0800 - ***********************************************************************************************
[INFO] 2023-12-13 21:29:51.365 +0800 - *********************************  Execute task instance  *************************************
[INFO] 2023-12-13 21:29:51.365 +0800 - ***********************************************************************************************
[INFO] 2023-12-13 21:29:51.366 +0800 - Final Shell file is : 
#!/bin/bash
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
${JAVA_HOME}/bin/java --class-path .:/opt/soft/upload/tmp/dolphinscheduler/exec/process/default/11378479582976/11909357344768_2/404/936 -jar /opt/soft/upload/tmp/dolphinscheduler/exec/process/default/11378479582976/11909357344768_2/404/936/null  -Dspring.profiles.active=prod -Dloader.main=com.jdyx.demo.starter.CcTask
[INFO] 2023-12-13 21:29:51.366 +0800 - Executing shell command : sudo -u root -i /opt/soft/upload/tmp/dolphinscheduler/exec/process/default/11378479582976/11909357344768_2/404/936/404_936.sh
[INFO] 2023-12-13 21:29:51.368 +0800 - process start, process id is: 20294
[INFO] 2023-12-13 21:29:52.368 +0800 -  -> 
	/opt/soft/upload/tmp/dolphinscheduler/exec/process/default/11378479582976/11909357344768_2/404/936/404_936.sh: line 4: /bin/java: No such file or directory
[INFO] 2023-12-13 21:29:52.370 +0800 - process has exited. execute path:/opt/soft/upload/tmp/dolphinscheduler/exec/process/default/11378479582976/11909357344768_2/404/936, processId:20294 ,exitStatusCode:127 ,processWaitForStatus:true ,processExitValue:127
[INFO] 2023-12-13 21:29:52.371 +0800 - java task run result: TaskResponse(varPool=null, processId=20294, resultString=null, appIds=null, process=null, cancel=false, exitStatusCode=127, status=null)
[INFO] 2023-12-13 21:29:52.371 +0800 - ***********************************************************************************************
[INFO] 2023-12-13 21:29:52.371 +0800 - *********************************  Finalize task instance  ************************************
[INFO] 2023-12-13 21:29:52.371 +0800 - ***********************************************************************************************
[INFO] 2023-12-13 21:29:52.371 +0800 - Upload output files: [] successfully
[INFO] 2023-12-13 21:29:52.371 +0800 - Send task execute status: FAILURE to master : 172.26.0.5:1234
[INFO] 2023-12-13 21:29:52.372 +0800 - Remove the current task execute context from worker cache
[INFO] 2023-12-13 21:29:52.372 +0800 - The current execute mode isn't develop mode, will clear the task execute file: /opt/soft/upload/tmp/dolphinscheduler/exec/process/default/11378479582976/11909357344768_2/404/936
[INFO] 2023-12-13 21:29:52.372 +0800 - Success clear the task execute file: /opt/soft/upload/tmp/dolphinscheduler/exec/process/default/11378479582976/11909357344768_2/404/936
[INFO] 2023-12-13 21:29:52.372 +0800 - FINALIZE_SESSION
`
