### ISSUE TITLE
[Question] [Worker] Process won't kill

### ISSUE THREAD

**Issue by gjzhappy** [apache/dolphinscheduler#14411]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I ran a java command in the shell task, I set the max memory of the task to 30M, I expected the java process will be killed when it reaches the max memory, but it won't, can you give me some tips, thanks.
![image](https://github.com/apache/dolphinscheduler/assets/13010517/5141b8c7-6f9d-476e-ac44-445c0c96062e)

### What you expected to happen

I expected the java process will be killed when it reaches the max memory

### How to reproduce

please see the pic above.

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Did you turn on the switch of `task.resource.limit.state`?

https://dolphinscheduler.apache.org/zh-cn/docs/3.1.7/guide/task/appendix

**Comment by gjzhappy** [comment]
@SbloodyS , Hello, I refer to the link you mentioned above, then it directed me to this URL:  https://dolphinscheduler.apache.org/zh-cn/docs/3.1.7/architecture/configuration, but I didn't find where to configure. Thanks.
