### ISSUE TITLE
[Improvement][CI] CI of unmerged PRs should rerun if a new PR gets merged

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#14412]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Suppose we have two PR A and B. A or B could pass CI but A and B together cause bugs and fail CI.

If the CI of A and B both had passed on 8 a.m. and A got merged on 9 a.m., in current settings, CI of B still looked good and could be merged. As a result, A and B together cause new bugs and PRs after them will fail the CI.

Therefore, we need to force the CI of unmerged PRs to rerun once a new PR gets merged.

Personally I have seen this kind of bugs happen in DS repo several times.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
BTW, this issue may happen during we release a new version, which is highly risky.

**Comment by zhongjiajie** [comment]
We can do that by turn on `update to date` for each PR ref https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch but it will take our maintainer much time and ci workflow more crowded
