### ISSUE TITLE
[Bug] [DataQuality]Rule management search bar don't support Chinese

### ISSUE THREAD

**Issue by Sakura-2019** [apache/dolphinscheduler#14420]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Click Data Quality top menu and enter the Rule management, input some Englinsh character like 'null', 'check' in the search bar and click search, it can show a right list. But when input Chinese character like '空值', '校验', it will show an empty list.
![QQ截图20230628143410](https://github.com/apache/dolphinscheduler/assets/53844242/b56e524c-ddbc-463a-a368-75621bc1ea5c)
![QQ截图20230628145323](https://github.com/apache/dolphinscheduler/assets/53844242/c3b029c3-0be3-4b6e-a955-2eeb79dd2435)

### What you expected to happen

When input Chinese character, it can also show a right result list, not empty.

### How to reproduce

1、Click Data Quality top menu and enter the Rule management.
2、Input some character that the rules list contained, like '校验', '多表', then click search.

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
@Sakura-2019 are you interested fixing this issue? It seems like a easy query.

**Comment by Sakura-2019** [comment]
> @Sakura-2019 are you interested fixing this issue? It seems like a easy query.

Thanks, I think the easiest way is fixing by front-end, but I don't know Vue 3.0 grammar.
So I hope you official can fix it.
