### ISSUE TITLE
[Bug] [Remot] In NettyClientHandler.class why call method future.executeInvokeCallback directly, but not method future.putResponse

### ISSUE THREAD

**Issue by fatcarter** [apache/dolphinscheduler#14422]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

in `NettyClientHandler` class , has this code: 

```java
    /**
     * process received logic
     *
     * @param message command
     */
    private void processReceived(final Channel channel, final Message message) {
        ResponseFuture future = ResponseFuture.getFuture(message.getOpaque());
        if (future != null) {
            future.setResponseCommand(message);
            future.release();
            if (future.getInvokeCallback() != null) {
                future.removeFuture();
                this.callbackExecutor.submit(future::executeInvokeCallback);
            } else {
                future.putResponse(message);
            }
        } else {
            processByCommandType(channel, message);
        }
    }
```
Call method executeInvokeCallback when `getInvokeCallback != null`

in ResponseFuture: 
```java 

    /**
     * put response
     *
     * @param responseMessage responseCommand
     */
    public void putResponse(final Message responseMessage) {
        this.responseMessage = responseMessage;
        this.latch.countDown();
        FUTURE_TABLE.remove(opaque);
    }
```

`this.latch.countDown()` is called in ResponseFuture, why does future.getInvokeCallback()! = null does not need to be called

### What you expected to happen

nothings

### How to reproduce

nothings

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fatcarter** [comment]
If I use the `responseFuture.waitResponse()` method, do I have to wait until the timeout to get the result?

**Comment by caishunfeng** [comment]
> If I use the `responseFuture.waitResponse()` method, do I have to wait until the timeout to get the result?

Yes, when you want to send sync, it will wait until timeout or return result.
