### ISSUE TITLE
[Bug] [Alarm Instance Manage] Search result list error

### ISSUE THREAD

**Issue by Sakura-2019** [apache/dolphinscheduler#14441]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![errorlist](https://github.com/apache/dolphinscheduler/assets/53844242/2d67e6fb-c23d-460a-93ae-e18f5c29fc99)
In Alarm Instance Manage, input some special characters list '#、%、&' and click search, the back-end interface return empty result, that's right. But the front shows a list that contains result, it should show an empty  list. Whether it's a front bug?

### What you expected to happen

Input some special characters list '#、%、&' and click search, the front will show an empty list.

### How to reproduce

In Alarm Instance Manage, input some special characters list '#、%、&' and click search.

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ligenhw** [comment]
i reference the queryProcessDefinitionListPaging api ,if no data, it will response an empty list, but not null.
the alarm instance list response totalList should also be empty list , but not null.
like that :
"totalList": []

I am willing to submit a PR , to fix it.
