### ISSUE TITLE
[DISCUSS] How to merge the two modules - `dolphinscheduler-task-plugin` and `dolphinscheduler-datasource-plugin`?

### ISSUE THREAD

**Issue by xdu-chenrj** [apache/dolphinscheduler#14451]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

How to merge the two modules - `dolphinscheduler-task-plugin` and `dolphinscheduler-datasource-plugin`?

### Related issues

[#13448](https://github.com/apache/dolphinscheduler/issues/14338)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xdu-chenrj** [comment]
First question: After merging `datasource-plugin` and `task-plugin`, what should the name be? I feel like it can't be the name of a single party anymore, because there are both connected tasks and tasks running inside.

Second question: How to merge? Taking zeppelin as an example, I moved the `zeppelin` from `datasource-plugin` to `task-plugin`, and I feel that the code is already very streamlined, unable to remove redundant code. What's your suggestion?


![image](https://github.com/apache/dolphinscheduler/assets/102030622/a78b86e2-8e59-4a40-a602-f566b99e5723)

**Comment by caishunfeng** [comment]
Why you want to merge the task module and datasource module?

**Comment by AmriStrong** [comment]
because they are all plugin.

**Comment by xdu-chenrj** [comment]
> Why you want to merge the task module and datasource module?

Because the data source center will be changed to a connection center https://github.com/apache/dolphinscheduler/issues/14338, which will support non SQL connections such as zeppelin, it is necessary to merge the data source center module and task module. You can ask him for other details: @EricGao888.
