### ISSUE TITLE
[Feature][stop task] Killing yarn application task when stopping a task on the workflow instance page

### ISSUE THREAD

**Issue by AnemoneIndicum** [apache/dolphinscheduler#14458]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

task type: hive-cli  script
version: 3.1.7

 I killed a task( hive-cli script) on the workflow instance page, but the job can not be killed on Yarn Cluster yet.
 So I have to kill it using Yarn Command, it's inconvenient.  Can you support this feature?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please refer to docs in https://dolphinscheduler.apache.org/zh-cn/docs/3.1.7/architecture/configuration

**Comment by AnemoneIndicum** [comment]
Thanks, our  DS cluster's common "Properties" may have some problems.

**Comment by AnemoneIndicum** [comment]
Sorry， I have viewed our DS cluster's common "Properties", which is right.  Such as follows:
![image](https://github.com/apache/dolphinscheduler/assets/24583579/c315354c-df5e-48bc-affd-c756e9ffd76a)
The problem I submitted earlier still exists.
