### ISSUE TITLE
[Bug] [chunjun-Task] could not run the chunjun task in dolphinscheduler, report " Could not determine current working directory."

### ISSUE THREAD

**Issue by caoyl2015** [apache/dolphinscheduler#14466]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

chunjun version 1.12
flink version 1.12.7
dolphinscheduler 3.1.3

when i create a chunjun task and run it, the log report "Could not determine current working directory."

### What you expected to happen

i hope chunjun  task  run correctly

### How to reproduce

1. init env, inistall chunjun 1.12, flink 1.12 and dolphinscheduler 3.1.3, refer to [https://dolphinscheduler.apache.org/zh-cn/docs/3.1.7/guide/task/chunjun](url)
2.  create a task of chunjun, and  click "run" in "Workflow Definition" page, check log in "Task Instance"

> 

### Anything else

solution: I change the chunjun start file "start-chunjun" in $CHUNJUN_HOME/bin,  

the last line: " nohup $JAVA_RUN -cp $JAR_DIR $CLASS_NAME $@ & "

change to 

" $JAVA_RUN -cp $JAR_DIR $CLASS_NAME $@ "

and then dolphinscheduler can run chunjun task correctly, so the install guide of dolphinscheduler for chunjun task should ask  
 to change it 

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
I found the page which describe the chunjun task, but there is nothing for the "nohup java xxx.....". Could you post it's url?

**Comment by caoyl2015** [comment]
> I found the page which describe the chunjun task, but there is nothing for the "nohup java xxx.....". Could you post it's url?

Thank you for your attention. I think you just misunderstand my means,  the "nohup java xxx.....". is come from chunjun install dir [CHUNJUN_HOME]/bin/start-chunjun, the shell last line you can find it

**Comment by qiaozhanwei2023** [comment]
Two points need to be modified :
1、start-chunjun script，remove nohup(otherwise the task is successful directly) and specify $CHUNJUN_HOME/lib/chunjun-clients.jar:$CHUNJUN_HOME/lib/*，refer https://segmentfault.com/a/1190000045090142

2、yarn status need trace(even though per-job mod， shell status cannot represent the yarn status)，refer https://segmentfault.com/a/1190000045058893
