### ISSUE TITLE
[Improvement][Module Name] Improvement title

### ISSUE THREAD

**Issue by cooldwind** [apache/dolphinscheduler#14474]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

[Bug] [data quality ]3.1.X version.Tasks with a running result of true type can be completed, while tasks with a failure type are constantly running and cannot be ended.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cooldwind** [comment]
3.1.X version.Tasks with a running result of true type can be completed, while tasks with a failure type are constantly running and cannot be ended.

**Comment by rickchengx** [comment]
Hi @cooldwind please fulfill the title of this issue
