### ISSUE TITLE
[Feature][Data Quality] Support MySQL type tasks

### ISSUE THREAD

**Issue by cooldwind** [apache/dolphinscheduler#14477]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Now it is a Spark type task, supporting MySQL type tasks

### Use case

[Data Quality

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
https://github.com/apache/dolphinscheduler/issues/14476
