### ISSUE TITLE
[Bug] [DolphinScheduler Standalone-Server] MasterServer remove registry path exception

### ISSUE THREAD

**Issue by ghost** [apache/dolphinscheduler#14495]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After downloading DolphinScheduler and Java 11 from OpenJDK on an Ubuntu LTS VirtualBox VM I executed the following command to start the standalone DolphinScheduler server:
`./bin/dolphinscheduler-daemon.sh start standalone-server`

The server starts fine and I am able to access DolphinScheduler at `http://localhost:12345/dolphinscheduler/ui`.

The issue occurs when I stop the server and try to start it again. After starting the server again I find the following error in a log in the standalone-server/logs directory:

[ERROR] 2023-07-10 08:20:04.254 +0000 org.apache.dolphinscheduler.server.master.registry.MasterRegistryClient:[182] - MasterServer remove registry path exception 
org.apache.dolphinscheduler.registry.api.RegistryException: Failed to delete registry key: /nodes/master/10.0.2.15:5678
	at org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperRegistry.delete(ZookeeperRegistry.java:210)
	at org.apache.dolphinscheduler.service.registry.RegistryClient.remove(RegistryClient.java:191)
	at org.apache.dolphinscheduler.server.master.registry.MasterRegistryClient.deregister(MasterRegistryClient.java:175)
	at org.apache.dolphinscheduler.server.master.registry.MasterRegistryClient.close(MasterRegistryClient.java:82)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:239)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1161)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1154)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1106)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1075)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:174)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021)
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:823)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkState(CuratorFrameworkImpl.java:457)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.delete(CuratorFrameworkImpl.java:477)
	at org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperRegistry.delete(ZookeeperRegistry.java:204)
	... 17 common frames omitted

I attached the full log to this message.

[dolphinscheduler-standalone.log](https://github.com/apache/dolphinscheduler/files/11999653/dolphinscheduler-standalone.log)

### What you expected to happen

After stopping the standalone-server and restarting it again I expect DolphinScheduler to work as expected: no error messages and I can access the application at `http://localhost:12345/dolphinscheduler/ui`

### How to reproduce

(I followed this guide when installing DolphinScheduler: https://dolphinscheduler.apache.org/en-us/docs/3.1.5/guide/installation/standalone)

Download DolphinScheduler
Install Java 11 from OpenJDK
Start DolphinScheduler standalone-server
Stop DolphinScheduler standalone-server
Start DolphinScheduler standalone-server again

### Anything else

Linux 5.19.0-46-generic # 47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

A similar issue (same error message) was mentioned in a Discussion started on the 15h of September 2022:
https://github.com/apache/dolphinscheduler/discussions/11948

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
![image](https://github.com/apache/dolphinscheduler/assets/42668765/a84904eb-9e39-4433-a59a-65a80b225d6d)
When you stop the standalone-server, program try to remove master node in zookeeper.At this point zookeeper's state is **stopped** .   So, the program throw the exception. @fincentxyz 

Considering that the master node was created by EPHEMERAL mode, should we remove this line in the deregister() method 
 (MasterRegistryClient.java)? 
`registryClient.remove(masterConfig.getMasterRegistryPath());`  
@ruanwenjun

**Comment by ruanwenjun** [comment]
> ![image](https://user-images.githubusercontent.com/42668765/256127400-a84904eb-9e39-4433-a59a-65a80b225d6d.png) When you stop the standalone-server, program try to remove master node in zookeeper.At this point zookeeper's state is **stopped** . So, the program throw the exception. @fincentxyz
> 
> Considering that the master node was created by EPHEMERAL mode, should we remove this line in the deregister() method (MasterRegistryClient.java)? `registryClient.remove(masterConfig.getMasterRegistryPath());` @ruanwenjun

Yes, it's off to remove this code, but not all registry plugin is implemented as EPHEMERAL, so keep the remove logic is ok.
We can close the zkserver after SpringContext closed

This should only exist in standalone mode?

**Comment by CallMeKingsley97** [comment]
> > ![image](https://user-images.githubusercontent.com/42668765/256127400-a84904eb-9e39-4433-a59a-65a80b225d6d.png) When you stop the standalone-server, program try to remove master node in zookeeper.At this point zookeeper's state is **stopped** . So, the program throw the exception. @fincentxyz
> > Considering that the master node was created by EPHEMERAL mode, should we remove this line in the deregister() method (MasterRegistryClient.java)? `registryClient.remove(masterConfig.getMasterRegistryPath());` @ruanwenjun
> 
> Yes, it's off to remove this code, but not all registry plugin is implemented as EPHEMERAL, so keep the remove logic is ok. We can close the zkserver after SpringContext closed
> 
> This should only exist in standalone mode?

Yep, i think it only exist in standalone mode. The independently deployed zookeeper will not have such problems

**Comment by ruanwenjun** [comment]
> > > ![image](https://user-images.githubusercontent.com/42668765/256127400-a84904eb-9e39-4433-a59a-65a80b225d6d.png) When you stop the standalone-server, program try to remove master node in zookeeper.At this point zookeeper's state is **stopped** . So, the program throw the exception. @fincentxyz
> > > Considering that the master node was created by EPHEMERAL mode, should we remove this line in the deregister() method (MasterRegistryClient.java)? `registryClient.remove(masterConfig.getMasterRegistryPath());` @ruanwenjun
> > 
> > 
> > Yes, it's off to remove this code, but not all registry plugin is implemented as EPHEMERAL, so keep the remove logic is ok. We can close the zkserver after SpringContext closed
> > This should only exist in standalone mode?
> 
> Yep, i think it only exist in standalone mode. The independently deployed zookeeper will not have such problems

Do you want to fix this? otherwise I will close this, since this is not a really `bug`.

**Comment by CallMeKingsley97** [comment]
> > > > ![image](https://user-images.githubusercontent.com/42668765/256127400-a84904eb-9e39-4433-a59a-65a80b225d6d.png) When you stop the standalone-server, program try to remove master node in zookeeper.At this point zookeeper's state is **stopped** . So, the program throw the exception. @fincentxyz
> > > > Considering that the master node was created by EPHEMERAL mode, should we remove this line in the deregister() method (MasterRegistryClient.java)? `registryClient.remove(masterConfig.getMasterRegistryPath());` @ruanwenjun
> > > 
> > > 
> > > Yes, it's off to remove this code, but not all registry plugin is implemented as EPHEMERAL, so keep the remove logic is ok. We can close the zkserver after SpringContext closed
> > > This should only exist in standalone mode?
> > 
> > 
> > Yep, i think it only exist in standalone mode. The independently deployed zookeeper will not have such problems
> 
> Do you want to fix this? otherwise I will close this, since this is not a really `bug`.
I agree with you. Do it close. 😀

**Comment by ghost** [comment]
Huh, this is not a bug? This doesn't look like expected behaviour to me. Why can't I stop the program and start it again afterwards?

**Comment by AJiangs** [comment]
I also had this issue with my dolphinscheduler's standalone mode after I restarted the server: org.apache.dolphinscheduler.server.master.registry.MasterRegistryClient:[182] - MasterServer remove registry path exception
org.apache.dolphinscheduler.registry.api.RegistryException: Failed to delete registry key: /nodes/master/172.16.134.10:5678

What can I do to guarantee that the reboot is available. Is it OK to use cluster mode?
