### ISSUE TITLE
[RPC] Refactor the remote module.

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#14509]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Right now, we have implemented a RPC service based on netty.

But this is not convenient, it's hard to expose these service APIs, I hope we can use GRPC to refactor these.
https://grpc.io/docs/languages/java/basics/

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi, @ruanwenjun , you can assign me :D

**Comment by ruanwenjun** [comment]
> Hi, @ruanwenjun , you can assign me :D

If you begin to do this, you need to list the interface will exposed by  Master/Worker.

**Comment by Radeity** [comment]
> If you begin to do this, you need to list the interface will exposed by Master/Worker.

Get it.

**Comment by ruanwenjun** [comment]
After surveying the GRPC, I found if we want to refactor to GRPC, we will need to refactor the request/response to proto file, it's will cause us to do a lot of work, since our request/response might contains a lot of nested object.

So I will work base on current remote module to refactor this.
<img width="711" alt="image" src="https://github.com/apache/dolphinscheduler/assets/22415594/e6370140-3bd5-4ffe-8765-30c0bf3c6884">
