### ISSUE TITLE
[Bug] [Scheduler] Can't Create Cron Schedule In Standalone

### ISSUE THREAD

**Issue by ak99372** [apache/dolphinscheduler#14511]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In new standalone instance there's no way to create a cron schedule for a workflow.
![image](https://github.com/apache/dolphinscheduler/assets/9924769/ed25d874-e764-4f83-8d12-f2d0ebf06bf2)
Open [Cron Manage]
![image](https://github.com/apache/dolphinscheduler/assets/9924769/28ca5645-531e-4656-a371-4b4db38dbad2)

### What you expected to happen

- option/button to create [Cron] schedule

(alternatively)
- option/button to be disabled (if it is not possible to create one) + info why it can't be created right now

### How to reproduce

1. install standalone version
2. Create Project-> Workflow->Task
3. Open Workflow Definition -> push it Online (to enable [Cron Manage] button)
4. Click [Cron Manage]

### Version

3.1.7

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please refer to the docs in https://dolphinscheduler.apache.org/en-us/docs/3.1.7/guide/project/workflow-definition
