### ISSUE TITLE
[Bug] [K8S] kubernetes-client-api-6.0.0 and spring-cloud-kubernetes-fabric8-config-2.1.3 version conflicts

### ISSUE THREAD

**Issue by Gallardot** [apache/dolphinscheduler#14512]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Build an image from the latest dev branch and deploy to k8s. All components failed to start with the following error.

```
[INFO] 2023-07-12 09:43:17.819 +0800 com.zaxxer.hikari.HikariDataSource:[352] - DolphinScheduler - Shutdown completed.
[INFO] 2023-07-12 09:43:17.831 +0800 org.eclipse.jetty.server.session:[149] - node0 Stopped scavenging
[INFO] 2023-07-12 09:43:17.838 +0800 org.eclipse.jetty.server.handler.ContextHandler:[1159] - Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@301e5d23{application,/dolphinscheduler,[file:///tmp/jetty-docbase.12345.1379246485250171406/, jar:file:/opt/dolphinscheduler/libs/swagger-ui-4.11.1.jar!/META-INF/resources],STOPPED}
[INFO] 2023-07-12 09:43:17.865 +0800 org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener:[136] - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[ERROR] 2023-07-12 09:43:17.933 +0800 org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter:[40] - 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.cloud.kubernetes.fabric8.config.reload.EventBasedConfigMapChangeDetector.watch(EventBasedConfigMapChangeDetector.java:81)

The following method did not exist:

    io.fabric8.kubernetes.client.dsl.MixedOperation.watch(Ljava/lang/Object;)Lio/fabric8/kubernetes/client/Watch;

The calling method's class, org.springframework.cloud.kubernetes.fabric8.config.reload.EventBasedConfigMapChangeDetector, was loaded from the following location:

    jar:file:/opt/dolphinscheduler/libs/spring-cloud-kubernetes-fabric8-config-2.1.3.jar!/org/springframework/cloud/kubernetes/fabric8/config/reload/EventBasedConfigMapChangeDetector.class

The called method's class, io.fabric8.kubernetes.client.dsl.MixedOperation, is available from the following locations:

    jar:file:/opt/dolphinscheduler/libs/kubernetes-client-api-6.0.0.jar!/io/fabric8/kubernetes/client/dsl/MixedOperation.class

The called method's class hierarchy was loaded from the following locations:

    io.fabric8.kubernetes.client.dsl.MixedOperation: file:/opt/dolphinscheduler/libs/kubernetes-client-api-6.0.0.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes org.springframework.cloud.kubernetes.fabric8.config.reload.EventBasedConfigMapChangeDetector and io.fabric8.kubernetes.client.dsl.MixedOperation
2023-07-12T01:43:17.933762469Z
```

### What you expected to happen

All components are running normally in k8s

##### build docker image 
```
./mvnw -B clean package  -Dmaven.test.skip  -Dmaven.javadoc.skip  -Dmaven.checkstyle.skip  -Dmaven.deploy.skip -Ddocker.push.skip=true -Ddocker.tag=3.2.0-RC1  -Ddocker.hub=xxx.com/yyy  -Pdocker,release
```
##### deploy by helm
```
helm upgrade --install --create-namespace --namespace dolphinscheduler  dolphinscheduler dolphinscheduler -f helm/values-local.yaml
```

```
cat values-local.yaml
image:
  registry: xxx.com/yyy
  tag: 3.2.0-RC1

minio:
  enabled: false

conf:
  common:
    # resource storage type: HDFS, S3, OSS, GCS, ABS, NONE
    resource.storage.type: NONE
    # The Azure client ID (Azure Application (client) ID)
    resource.azure.client.id: minioadmin
    # The Azure client secret in the Azure application
    resource.azure.client.secret: minioadmin
    # The Azure data factory subscription ID
    resource.azure.subId: minioadmin
    # The Azure tenant id in the Azure Active Directory
    resource.azure.tenant.id: minioadmin
```

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Gallardot** [comment]
@Radeity please take a look.  It's possible that this PR #13891 introduced this issue.

**Comment by Radeity** [comment]
Hi @Gallardot , thanks for bring this up, I'll find a compatible version ASAP.

**Comment by Radeity** [comment]
It's a bit tricky... cc @ruanwenjun

 SpringBoot 2.x is only compatible with SpringCloud 2021.x which integrated kubernetes-client 5.10.2, however, the bug mentioned in PR https://github.com/apache/dolphinscheduler/pull/13891 is fixed in kuberente-client 6.0.0.

SpringCloud 2022.x upgrade its kubernetes-client version to 6.2.0,  but it's only compatible with SpringBoot 3.x.

**Comment by Radeity** [comment]
Hi, @Gallardot , for your local test, you can temporarily downgrade the version of kubernetes-client to 5.10.2 in `bom/pom.xml` , the problem will happen if K8S task meet errors and we will miss some error logs.

**Comment by Gallardot** [comment]
> Hi, @Gallardot , for your local test, you can temporarily downgrade the version of kubernetes-client to 5.10.2 in `bom/pom.xml` , the problem will happen if K8S task meet errors and we will miss some error logs.

Thanks @Radeity .
We are currently in the local pre-research testing phase, and we can continue testing by temporarily downgrading the version. Will this be fixed before the 3.2.0 release? We want to use the latest version for the 3.2.0 release, as there are many cloud-native features we need.

**Comment by Radeity** [comment]
Hi @Gallardot, 

> Will this be fixed before the 3.2.0 release?

Yes, it will, I've already added it to 3.2.0 milestone.

> We want to use the latest version for the 3.2.0 release, as there are many cloud-native features we need.

Glad to hear that! Welcome to test and contribute about it :D

**Comment by Gallardot** [comment]
> you can temporarily downgrade the version of kubernetes-client to 5.10.2 in `bom/pom.xml`

@Radeity. kubernetes-client from 6.0.0 to 5.10.2. After tested, this doesn't work. Because it's a breaking change. Compiler was not successful.

**Comment by Radeity** [comment]
Oh, you're right... there are some incompatible API.

**Comment by Radeity** [comment]
Hi, @Gallardot , sorry for the inconvenience, maybe you have to revert related parts of codes manually until it's fixed.
