### ISSUE TITLE
[Feature][E2E-Test] Set up Minikube-Kubernetes to improve e2e test

### ISSUE THREAD

**Issue by Radeity** [apache/dolphinscheduler#14525]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, we don't test Kubernetes deployment and Kubernetes executor. 

- For the first point, sometimes we will miss some potential bugs, see https://github.com/apache/dolphinscheduler/issues/14512
- For the second point, we often get low UT coverage, see https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=14379&metric=new_coverage&view=list

Thus, I think we should set up Minikube Kubernetes and make some improvement about these.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Gallardot** [comment]
I couldn't agree more. Let's first confirm the current range of k8s versions we need to support and set up a base environment for k8s cluster creation, project compilation, image build, and helm deployment. And can e2e test cases reuse the current e2e test cases?

**Comment by Radeity** [comment]
> And can e2e test cases reuse the current e2e test cases?

Yes, it can. Any interest to help with that?

**Comment by Gallardot** [comment]
> Yes, it can. Any interest to help with that?

Yes, I will have a try.

**Comment by Gallardot** [comment]
An execution plan, divided into two phases
The first stage, build and deploy, verify the docker image and helm charts, k8s deployment is successful.
1. Build docker images of each component
2. Create a kind of k8s cluster
3. helm charts deploys ds on k8s

In the second stage, the E2E use case is executed to verify the k8s related test cases.
Execute the E2E test case of the k8s task
1. Execute the E2E test case of the k8s task

**Comment by Radeity** [comment]
That sounds good to me, PTAL when available :D

cc @SbloodyS @EricGao888

**Comment by EricGao888** [comment]
> That sounds good to me, PTAL when available :D
> 
> cc @SbloodyS @EricGao888

+1. I'm glad that there are more people start to get interested in helping improve DS CI / CD.

**Comment by SbloodyS** [comment]
> > That sounds good to me, PTAL when available :D
> > cc @SbloodyS @EricGao888
> 
> +1. I'm glad that there are more people start to get interested in helping improve DS CI / CD.

+1
