### ISSUE TITLE
[Bug] [dolphinscheduler-ui] Page echo dependency exception

### ISSUE THREAD

**Issue by moxtong2** [apache/dolphinscheduler#14535]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

标题：插件依赖功能显示异常 
内容 ：DEPENDENT 模块添加依赖公共任务A ，A未执行，在流的实例查看依赖显示空。

### What you expected to happen

原因：在t_ds_task_instance 未生成任务实例，所以
`
ProcessInstanceServiceImpl 中359行如下添加依赖为空导致前端回显异常
List<TaskInstance> taskInstanceList = processService.findValidTaskListByProcessId(processId);
addDependResultForTaskList(taskInstanceList);
`

### How to reproduce

src\views\projects\task\components\node\fields\use-dependent.ts
233 行
`
let state: ITaskState = dependentResult[key]
state = state ? state : 'RUNNING_EXECUTION'
`

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @moxtong2 , would you like to fix it?

**Comment by moxtong2** [comment]
yeah ， Can I have a slot invitation connection? I am currently unable to communicate with everyone.

**Comment by SbloodyS** [comment]
What do you mean by slot invitation connection? @moxtong2

**Comment by moxtong2** [comment]
slack，I don't know how to join slack.

**Comment by SbloodyS** [comment]
You can try this link.
`https://join.slack.com/t/asf-dolphinscheduler/shared_invite/zt-1zvp0z89s-ydF2SThoQNFeAwXiP~RTyw`

**Comment by moxtong2** [comment]
thank you ，Thank you very much

**Comment by SbloodyS** [comment]
I've assigned this issue to you. Looking forward to your contribution. @moxtong2

**Comment by moxtong2** [comment]
ok .Once I have tested it, I will submit it.I want to ask, is there anyone doing the integration of graphic plugins? I am doing it. It's like neo4j
