### ISSUE TITLE
[Feature][Master][UI] Cross-workflow parameter passing

### ISSUE THREAD

**Issue by Orange-Summer** [apache/dolphinscheduler#14545]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In the subprocess task, the subworkflow can choose its own output parameters to output to the downstream tasks in the parent workflow.
This is a [DolphinScheduler project of OSPP-2023.](https://summer-ospp.ac.cn/org/prodetail/232290357)

### Use case

Example:
This is the output parameter of the task in the subworkflow
![image](https://github.com/apache/dolphinscheduler/assets/61171207/336ed038-1353-496a-8016-1b13722bab81)
This is the output parameter defined in the subworkflow
![image](https://github.com/apache/dolphinscheduler/assets/61171207/b1dff352-8628-4014-b021-6a8c70ee2b1b)
Output parameter1 and parameter2 in the downstream task of the subworkflow task, and finally output parameter1 successfully
![image](https://github.com/apache/dolphinscheduler/assets/61171207/6a97f435-e9a9-434b-8312-44dc9db82674)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Orange-Summer** [comment]
Design doc:

Modify the `submitPostNode` method in the `WorkflowExecuteRunnable` class so that the last node in the subworkflow outputs the correct parameters to the varpool of the workflow, which is finally passed to the subworkflow task in the parent workflow.

In the `WorkflowExecuteThreadPool` class, the `notifyProcessChanged` method is used to change the subworkflow to the parent workflow, and obtains all the parent workflows and corresponding subworkflow tasks. Add a method here to assign the varpool of the subworkflow to the varpool in the `SubProcessParameters` of the subworkflow task, and the code for passing parameters to downstream tasks has been implemented.

**Comment by wxibm333** [comment]
<img width="598" alt="image" src="https://github.com/user-attachments/assets/876fc8d8-04e5-4a72-b4a9-c3b36cf453b9">
<img width="584" alt="image" src="https://github.com/user-attachments/assets/024c68ea-8328-45ad-8415-23351a8a44c0">
<img width="993" alt="image" src="https://github.com/user-attachments/assets/8060c499-3a8b-49d4-a07d-b342ca09e141">
I have tried to pass parameters across workflows several times, but the parameters of the main process are lost. I don't know if this is a re-occurrence of the bug or if I have misconfigured it.
