### ISSUE TITLE
[Feature][UI] shows supported task types on the front-end UI

### ISSUE THREAD

**Issue by Gallardot** [apache/dolphinscheduler#14556]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

At present, dolphinscheduler supports 30+ task types, but in fact, to use specific types of tasks, the administrator needs to configure the corresponding environment, such as hadoop spark and so on. However, it is often not possible to use all types in a real-world scenario. So is there a configuration item that shows supported task types on the `create task` page? This is more user friendly and does not incorrectly use unsupported task types.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
@Gallardot  Could you offer some more details about what you want. You'd better post several screenshots to clarify your need.

**Comment by Gallardot** [comment]
@calvinjiang 
I am sorry for the late reply. As a cluster administrator, I want users to only be able to view k8s task and not be able to view flink or hive tasks. The tasks of flink or hive types should not be displayed on the UI. Note that our cluster does not support flink or hive, only k8s task.

**Comment by Gallardot** [comment]
This functionality can be achieved by modifying the `task-type-config.yaml` file. However, if deployed through Helm, this file cannot be changed. Therefore, I will create a PR to support this feature in Helm deployments as well.
