### ISSUE TITLE
[Feature][Flink] Flink on k8s

### ISSUE THREAD

**Issue by xiaohei88** [apache/dolphinscheduler#14560]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I need the Flink on k8s function. Do you have any documentation

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi @xiaohei88 , we don't support flink on k8s now😢

**Comment by xiaohei88** [comment]
hello, When is it expected to be supported?

**Comment by Radeity** [comment]
Hi, @xiaohei88 , there are some technical challenge, I can not promise that. Anyway, we hope we can support it ASAP, you can search the key world to track relative issues. I'll close this one because it's duplicated, and you can ping me anytime if you are willing to contribute.

**Comment by ssquan** [comment]
@Radeity Could you share some insight into the key technical challenges? as well as the real advantages, of setting up a Flink cluster on-premise using Kubernetes when doing ETL jobs?
