### ISSUE TITLE
[Bug] [dolphinscheduler-master] master didn't work and process didn't scheduler

### ISSUE THREAD

**Issue by Allen-Cao** [apache/dolphinscheduler#14572]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="1085" alt="image" src="https://github.com/apache/dolphinscheduler/assets/59598656/69799b15-28f4-46a5-9f3b-4d0ac32b49ac">
At 8:30, the master of all machines did not schedule the workflow on time. The scheduling began at 8:31, but some workflows were still not scheduled and no error messages were reported, resulting in a major accident

### What you expected to happen

最开始以为quartz策略问题，但是修改之后仍然发生，而且发现所有master此时间段均未调度日志，因此怀疑master调度权限[bugfix](https://github.com/apache/dolphinscheduler/pull/12233)

### How to reproduce

无法确认

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Caribbeanz** [comment]
I had the same problem.It may be a problem with the master service.Check whether there are waiting tasks.It works after the cluster is restarted.
