### ISSUE TITLE
[Bug] [Docker install 3.0.0 run job pop] Prompt no suitable tenant

### ISSUE THREAD

**Issue by baobao2016** [apache/dolphinscheduler#14579]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/apache/dolphinscheduler/assets/17892202/05aa99b7-c6d4-4849-9e08-813c912ff7bd)
然后我创建了租户，用户，给他们授权项目的权限，问题没有解决，无法测试。

### What you expected to happen

1

### How to reproduce

2

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by edenpan** [comment]
我今天 也碰到了，刚刚摸索了下，是要在工作流设计那里选择下自己新创建的用户，它默认是default 所以就没有，就报错了。
<img width="1431" alt="截屏2023-09-20 22 08 33" src="https://github.com/apache/dolphinscheduler/assets/12774563/63fe7704-95cd-44c1-a978-d516ba73f0b1">
