### ISSUE TITLE
[Improvement][Task] Mask configYaml in task log for non-admin users

### ISSUE THREAD

**Issue by Radeity** [apache/dolphinscheduler#14570]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Kubernetes cluster's configYaml should better not visible in log.

<img width="645" alt="image" src="https://github.com/apache/dolphinscheduler/assets/45198818/5025ae9d-21e3-404a-9ac0-7b792801c213">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
We have to find a way to mask these information, or simply do not print `k8sTaskExecutionContext`. cc @ruanwenjun @EricGao888 @rickchengx

**Comment by Gallardot** [comment]
https://github.com/apache/dolphinscheduler/blob/6af361a7d6ae604cf0df0b8e10b63b76c752ce31/dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerTaskExecuteRunnable.java#L199


~~To control log printing, I think use `Jackson Filter` to control the serialization process is OK. I will have a try.~~


~~ref: https://www.baeldung.com/jackson-serialize-field-custom-criteria~~

Find a more simple and elegant way #14571
