### ISSUE TITLE
[Bug][Dinky] Documentation bug or improvement

### ISSUE THREAD

**Issue by wangjc0216** [apache/dolphinscheduler#14598]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

**dinky plugin should be added specific version**

I recently used dolphin scheduler with dinky v0.7.3, but failed. log below:

```
[LOG-PATH]: /opt/dolphinscheduler/logs/20230720/10280823947712_10-53-59.log, [HOST]:  Host{address='dolphinscheduler-worker-0.dolphinscheduler-worker-headless:1234', ip='dolphinscheduler-worker-0.dolphinscheduler-worker-headless', port=1234}
...
[INFO] 2023-07-20 14:48:59.012 +0800 - access url: http://172.16.97.197:8888/openapi/getJobInstance?id=null
[INFO] 2023-07-20 14:48:59.018 +0800 - dinky task succeed with results: {"datas":null,"code":1,"msg":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: \"null\"","time":"2023-07-20 14:48:59"}
...
``` 
I  found dinky has changed its api uri

curl http://127.0.0.1:8888/openapi/getJobInstanceByTaskId?id=5
**uri be changed from `/openapi/getJobInstance` to `/openapi/getJobInstanceByTaskId`**

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
Why the jobInstanceId  is null

**Comment by wangjc0216** [comment]
> Why the jobInstanceId is null
I use mysql as datasource in dinky not flink ,I don't know if it's related @CallMeKingsley97

**Comment by CallMeKingsley97** [comment]
Anyway, jobInstanceId should't be "null". Could you post more logs ?
By the way, i found nothing from dinky(v0.7.3) about "/openapi/getJobInstanceByTaskId" .😂

**Comment by wangjc0216** [comment]
I found /openapi/getJobInstanceByTaskId in dinky :
![image](https://github.com/apache/dolphinscheduler/assets/37376634/3722c4f8-61fd-498b-abfb-c7ffb6c52391)

But I notice `/openapi/getJobInstance` and `/openapi/getJobInstanceByTaskId` both exist.

I submit task in dinky and log is below , it doesn't contain JobId 

![image](https://github.com/apache/dolphinscheduler/assets/37376634/0c06c40c-cfed-499a-a3da-f5b2757c0c46)

**Comment by CallMeKingsley97** [comment]
Could you submit a new task for using different sql?,  and watch the return data, take a closer look at the fields called "jobInstanceId".  
After you submit a task, the program will try to get jobInstanceInfo. 
![image](https://github.com/apache/dolphinscheduler/assets/42668765/be837bca-1a71-4122-8b13-8a68a97f0629)

**Comment by CallMeKingsley97** [comment]
Are there any questions?   @wangjc0216

**Comment by wangjc0216** [comment]
> Are there any questions? @wangjc0216

@CallMeKingsley97  I use flink as dinky param , and I will get expected value(different from dinky-mysql):
![image](https://github.com/apache/dolphinscheduler/assets/37376634/fee3dcc3-8c59-4421-99cb-760b39667de7)
I think there should be something wrong in dinky plugin.  I am not familiar about Java and Dolphin Scheduler, so I may spend some times to find out  what is the real reason.

**Comment by CallMeKingsley97** [comment]
What's the meaning of "get expected value(different from dinky-mysql)",I think the data returned from dinky which in your screenshot is right. I‘m not familiar about dinky, Can you describe it in detail?
