### ISSUE TITLE
[Bug] [ui] The move task button is missing in the task definition. 

### ISSUE THREAD

**Issue by luker629** [apache/dolphinscheduler#14607]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The move task button is missing in the task definition. After upgrading to 3.1.7, I noticed that the move task button is gone. 

Version: 3.1.7

### What you expected to happen

Add move task button.

### How to reproduce

The move task button is missing in the task definition. 

![企业微信截图_16898443485490](https://github.com/apache/dolphinscheduler/assets/12725613/c805b175-eea5-48e0-89bf-b834c4ee9d9f)

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hdygxsj** [comment]
this button remove by pr #13441

**Comment by luker629** [comment]
I understand. But how can I move tasks now? Is there an API for it?

**Comment by Radeity** [comment]
> I understand. But how can I move tasks now? Is there an API for it?

Hi, @luker629 , task moving api is now deprecated (ref https://github.com/apache/dolphinscheduler/pull/8190#discussion_r791559980).

BTW, if you think feature of reusing task definition is really helpful, you can leave some comments in https://github.com/apache/dolphinscheduler/issues/13513
