### ISSUE TITLE
[Bug] [dolphinscheduler-master] "Serial Wait Workflow" may not execute as expected when launched concurrently

### ISSUE THREAD

**Issue by 1205747671** [apache/dolphinscheduler#14618]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I am using the API projects/{projectCode}/executors/start-process-instance to run multiple instances of the same serial waiting workflow in a rapid manner, such as in a for loop. Theoretically, these instances should execute in order. However, I've observed that some instances are executing concurrently, not following the expected waiting order. 

### What you expected to happen

I have previously reported this issue but it doesn't appear to have been resolved yet. 

### How to reproduce

Using a for loop to call the interface to start the same workflow 10 times may result in multiple direct runs.

### Anything else

I suspect the issue might be related to transactions. I temporarily resolved this by appending 'for update' at the end of 'queryByProcessDefineCodeAndProcessDefinitionVersionAndStatusAndNextId' SQL. Is there a better solution?

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 1205747671** [comment]
I am using a standalone deployment

**Comment by CallMeKingsley97** [comment]
I haven't figure out a better way to reslove this issue.  
Maybe you can submit a pr with your solution, commiters will review your code

**Comment by 1205747671** [comment]
> I haven't figure out a better way to reslove this issue. Maybe you can submit a pr with your solution, commiters will review your code

I think adding a lock to this method when running a workflow can solve this problem. I haven't carefully read the code related to the Zookeeper lock in this project, I don't know what to do.
