### ISSUE TITLE
[Feature][dolphinscheduler-master] Add loop task

### ISSUE THREAD

**Issue by 1205747671** [apache/dolphinscheduler#14619]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add a loop task, such as executing the subsequent process multiple times in a loop. By using the loop task node, can conveniently call it multiple times. Currently, in order to implement this function, a new task script has to be added, which is implemented by calling the interface multiple times. This is very cumbersome.

### Use case

Create a loop task, increase the number of loops, this number can be obtained from the previous task, and execute the subsequent process multiple times according to the number of loops.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jiaoew1991** [comment]
We have the same requirement, any progress ?

**Comment by zhongjiajie** [comment]
is this same or like dynamic task? https://dolphinscheduler.apache.org/en-us/docs/3.2.0/guide/task/dynamic

**Comment by sunVII** [comment]
> 这是相同还是相似的动态任务？https://dolphinscheduler.apache.org/en-us/docs/3.2.0/guide/task/dynamic

希望可以前置任务生成参数列表，然后进入循环任务节点，选择
需要循环的工作流。中间设置生成子工作流实例并行个数
![0 jpg](https://github.com/apache/dolphinscheduler/assets/67156035/a049d826-ce1b-4a4f-893c-13cd4f8e96be)

**Comment by sunVII** [comment]
> 这是相同还是相似的动态任务？https://dolphinscheduler.apache.org/en-us/docs/3.2.0/guide/task/dynamic

希望可以前置任务生成参数列表，然后进入循环任务节点，选择
需要循环的工作流。中间设置生成子工作流实例并行个数
![0 jpg](https://github.com/apache/dolphinscheduler/assets/67156035/638918c9-d9cb-45dc-bd53-54420362df72)

**Comment by sunVII** [comment]
> is this same or like dynamic task? https://dolphinscheduler.apache.org/en-us/docs/3.2.0/guide/task/dynamic

I hope to generate a parameter list in a preprocessing task, then enter a loop task node to select the workflow that needs to be looped. During this process, choose to generate sub-workflow instances, either in serial or parallel, and determine the number of instances.
![0 jpg](https://github.com/apache/dolphinscheduler/assets/67156035/1f6abf85-f8b5-49cd-84e5-c9012d274b2f)
