### ISSUE TITLE
[Bug] [dolphinscheduler-master] In special cases, the conditions task cannot be triggered to execute

### ISSUE THREAD

**Issue by shilei-ly** [apache/dolphinscheduler#14625]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In special cases, the conditions task cannot be triggered to execute. As shown in the following figure, when s7 finish before s1, task c2 cannot be triggered, resulting in task s5 or s6 cannot be triggered. The condition for task c2 is or. 

(当任务s7先于任务s1完成且c2的条件定义为or时，s4被跳过导致condition类型任务c2无法被触发，导致后续的s5或者s6任务无法执行。s1至s6均为sleep 20s，s7为sleep 10s)

The workflow is shown below. Tasks s1 to s6 are shell tasks with sleep 20s. Task s7 is a shell type task and is sleep 10s. 
![image](https://github.com/apache/dolphinscheduler/assets/97011595/10919855-62fa-4a14-9c3e-31c784224282)
Condition task c1 is defined as shown in the following figure:
![image](https://github.com/apache/dolphinscheduler/assets/97011595/991215a8-6ea9-40d0-9f91-d382e95db40b)
Condition task c2 is defined as shown in the following figure:
![image](https://github.com/apache/dolphinscheduler/assets/97011595/a2a39b25-ec7a-4fed-ba6b-36d2db91006f)

### What you expected to happen

Condition type task c2 is defined as OR, then it should be executed as long as one of the preceding tasks is completed.
（Condition类型任务c2被定义为OR，则只要前置任务有一个完成就应该被触发。）

### How to reproduce

Build the workflow shown above. As long as task s7 finishes before task s1, and the c2 task condition is or, the problem can be repeated
（如上文所示构建工作流，只要任务s7先于任务s1执行结束，且c2任务条件为or，就能复现c2无法被执行问题）

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shilei-ly** [comment]
In the dev version, this problem also exists. If this is a bug that needs to be solved, I want to submit pr to deal with this issue

**Comment by SbloodyS** [comment]
@alei1206 I've assigned to you. Looking forward to your contribution.
