### ISSUE TITLE
[Improvement] [UI] There are too many child node in sub_process, it cannot to filter by keywords

### ISSUE THREAD

**Issue by chenshuai1995** [apache/dolphinscheduler#14627]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When i create a sub_process task, there are too many child node in sub_process, it cannot to filter by keywords. My ds version is 3.1.7

### What you expected to happen

Child node can filter by keywords

### How to reproduce

When i create a sub_process task, there are too many child node in sub_process, it cannot to filter by keywords. My ds version is 3.1.7

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
In my opinion, this is not a bug, this could be a new front-end feature.😂

**Comment by fuchanghai** [comment]
> In my opinion, this is not a bug, this could be a new front-end feature.😂

+1,i think this could be a improvement

**Comment by chenshuai1995** [comment]
please assign me, please.

**Comment by davidzollo** [comment]
> please assign me, please.

done
