### ISSUE TITLE
[Bug] [Process Instance] task_instance time and process_instance time is different

### ISSUE THREAD

**Issue by milton4code** [apache/dolphinscheduler#14632]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The time difference between the task t_ds_task_instance and t_ds_process_instance in the database is 13 hours, and it is indeed the same in the ui.

### What you expected to happen

the task t_ds_task_instance and t_ds_process_instance in the database will be the same 

### How to reproduce

My server is in China, the time zone is set to Asia/Shanghai, and the related configuration of ds is also the same

![image](https://github.com/apache/dolphinscheduler/assets/13265817/3cc208ee-15f5-418a-a83c-c43cb93ba27f)

![image](https://github.com/apache/dolphinscheduler/assets/13265817/7686eae6-0892-496a-8b0f-f28ab05ee443)

![a2e6a4e3ee4eab962b5f60ade3d3243](https://github.com/apache/dolphinscheduler/assets/13265817/4b7d79ed-3e85-4bb7-bbf7-0b7bb7a29643)

### Anything else

version 2.0.9

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
Could you change the sql that in your second screenshot, in order to show the process instance start_time, end_time

**Comment by milton4code** [comment]
![image](https://github.com/apache/dolphinscheduler/assets/13265817/d8219276-f49c-4817-848f-35871aa02270)

**Comment by CallMeKingsley97** [comment]
> ![image](https://user-images.githubusercontent.com/13265817/255864431-d8219276-f49c-4817-848f-35871aa02270.png)

Got it. But I can't reproduce it.
Maybe you can check your mysql's timezone. Sometimes this problem caused by it

**Comment by milton4code** [comment]
SELECT
u.id,
u.start_time task_start_time,u.end_time as task_end_time,
t.start_time process_start_time,t.end_time as process_end_time,
t.name process_name,
SUBSTRING(t.name, 17, 14) as prcoss_name_time
from t_ds_task_instance u
INNER JOIN t_ds_process_instance t
on  u.process_instance_id = t.id
ORDER BY u.id desc

**Comment by CallMeKingsley97** [comment]
> SELECT u.id, u.start_time task_start_time,u.end_time as task_end_time, t.start_time process_start_time,t.end_time as process_end_time, t.name process_name, SUBSTRING(t.name, 17, 14) as prcoss_name_time from t_ds_task_instance u INNER JOIN t_ds_process_instance t on u.process_instance_id = t.id ORDER BY u.id desc

SQL is right. Have you check your mysql's timezone?

**Comment by milton4code** [comment]
i use sql&nbsp; " SHOW GLOBAL VARIABLES LIKE 'time_zone'&nbsp; &nbsp;" to&nbsp; check mysql's timezone,the result is&nbsp; "system"


No time zone configuration found in my.conf file&nbsp;
Using the date +%Z command returns CST.









------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月26日(星期三) 上午9:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/dolphinscheduler] [Bug] [Process Instance] task_instance time and process_instance time is different (Issue #14632)





  
SELECT u.id, u.start_time task_start_time,u.end_time as task_end_time, t.start_time process_start_time,t.end_time as process_end_time, t.name process_name, SUBSTRING(t.name, 17, 14) as prcoss_name_time from t_ds_task_instance u INNER JOIN t_ds_process_instance t on u.process_instance_id = t.id ORDER BY u.id desc
  
SQL is right. Have you check your mysql's timezone?
 
&mdash;

**Comment by milton4code** [comment]
![image](https://github.com/apache/dolphinscheduler/assets/13265817/18c112d8-2c9c-46e1-8d86-cb876d673332)

**Comment by CallMeKingsley97** [comment]
> i use sql&nbsp; " SHOW GLOBAL VARIABLES LIKE 'time_zone'&nbsp; &nbsp;" to&nbsp; check mysql's timezone,the result is&nbsp; "system" No time zone configuration found in my.conf file&nbsp; Using the date +%Z command returns CST.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年7月26日(星期三) 上午9:03 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [apache/dolphinscheduler] [Bug] [Process Instance] task_instance time and process_instance time is different (Issue #14632) SELECT u.id, u.start_time task_start_time,u.end_time as task_end_time, t.start_time process_start_time,t.end_time as process_end_time, t.name process_name, SUBSTRING(t.name, 17, 14) as prcoss_name_time from t_ds_task_instance u INNER JOIN t_ds_process_instance t on u.process_instance_id = t.id ORDER BY u.id desc SQL is right. Have you check your mysql's timezone? &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
![image](https://github.com/apache/dolphinscheduler/assets/42668765/01ea9ba8-7809-4452-a517-48f262ccdd34)

In this website. [https://www.jb51.net/article/271660.htm](url).  I think your timezone config is simliar to the screenshot.
Maybe you can resolve your problem by using his solution.

**Comment by milton4code** [comment]
thanks ,the problem is resolved.

**Comment by CallMeKingsley97** [comment]
> thanks ,the problem is resolved.
Nice! 😁
