### ISSUE TITLE
[Feature][Module Name] Dolphinscheduler integrates OpenAI

### ISSUE THREAD

**Issue by sqxinquan** [apache/dolphinscheduler#14640]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Integrating openai into Dolphinscheduler, I only need to configure my openai token in the configuration file to achieve intelligent optimization of SQL on Dolphinscheduler scheduling and provide intelligent recommendations for optimization.

### Use case

Intelligent optimization of SQL, providing optimization suggestions

### Related issues

No other issues

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xinxingi** [comment]
I hope to achieve something more meaningful through AI, for DolphinScheduler. Regarding the step of optimizing SQL, it can be completed through external media.
