### ISSUE TITLE
[Bug] [UI] Can not update process definition for some specific command format

### ISSUE THREAD

**Issue by Radeity** [apache/dolphinscheduler#14647]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

If set command like this, and confirm to update process definition, put request can not be sent to backend and will get an error from website console
<img width="579" alt="image" src="https://github.com/apache/dolphinscheduler/assets/45198818/20f58a53-9bac-4719-b06e-a45e88fb5c5f">
<img width="849" alt="image" src="https://github.com/apache/dolphinscheduler/assets/45198818/aa535d45-67d3-42a4-b37c-6e8644d162fe">

There's no problem if set command to `["/bin/sh", "-c", "echo 123;"]`

### What you expected to happen

No error.

### How to reproduce

Ditto.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
Maybe add a label named "front-end"

**Comment by Radeity** [comment]
> Maybe add a label named "front-end"

Do you have interest to fix that?

**Comment by CallMeKingsley97** [comment]
> > Maybe add a label named "front-end"
> 
> Do you have interest to fix that?

I can't help, I focus on backend 😂

**Comment by hdygxsj** [comment]
what type of task does it happen?

**Comment by Radeity** [comment]
> what type of task does it happen?

K8S task, you can see the above screenshot. However, someone tells me he can not reproduce this bug, maybe you can have a try :D

**Comment by pppppjcc** [comment]
里面填写别的命令有问题吗，可以检查下网络配置相关，这个和网络有关，err_connection_reset这个问题是因为网站服务器被关闭或者是你的网络提供商将这个网站IP屏蔽。这个应该不是前端的问题

**Comment by Radeity** [comment]
> 里面填写别的命令有问题吗，可以检查下网络配置相关，这个和网络有关，err_connection_reset这个问题是因为网站服务器被关闭或者是你的网络提供商将这个网站IP屏蔽。这个应该不是前端的问题

Thanks, I will double check it later this week :D
