### ISSUE TITLE
[Improvement][UI] Need a easy way to know which project have faild tasks

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#14642]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

On dolphinscheduler home page we can know how many tasks were faild , But we can't know they belong to which project. We have to go into each project's home page to check, when there are a lot of project it will be a hard work. So is there a way to quickly know which project have faild tasks?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lordk911** [comment]
Maybe add a column to show the faild tasks number on the project list page will be fine.

**Comment by fuchanghai** [comment]
> Maybe add a column to show the faild tasks number on the project list page will be fine.

I think it’s better to put it on the homepage. I think there will be some problems in the project list. For example, if I want to check the number of failures in yesterday’s operation, will the Workflow Define Count also show the number of past time?
<img width="414" alt="image" src="https://github.com/apache/dolphinscheduler/assets/33984497/5a85369d-02f4-4104-9ef1-5d0801a39377">

**Comment by lordk911** [comment]
> I think it’s better to put it on the homepage. I think there will be some problems in the project list. For example, if I want to check the number of failures in yesterday’s operation, will the Workflow Define Count also show the number of past time?

Yes, it is better to have it on the homepage, but I think it is more difficult to implement than having it on the project list page. My scenario is that I received a phone alarm, but I don't know which project the error occurred in. If on the project list page could show the faild tasks number about today, it will be helpfully enough to quickly know what happen.

**Comment by fuchanghai** [comment]
hi @lordk911  When the process instance ends, you can add the parameters you need to the alarm message
<img width="1123" alt="image" src="https://github.com/apache/dolphinscheduler/assets/33984497/192a1970-7578-468b-b969-5b0f101beac0">

**Comment by lordk911** [comment]
> hi @lordk911 When the process instance ends, you can add the parameters you need to the alarm message

Thanks. We use a third-party API for phone alerts, but it can only play pre-recorded audio and cannot play content by passing text. In this case, the alert module of Dolphin will not be called.

**Comment by lordk911** [comment]
![企业微信截图_06f669b1-631a-4fcb-848c-d97cd367c934](https://github.com/apache/dolphinscheduler/assets/19989300/b660948e-0087-460c-b7c0-9c14847421d4)

I am not familiar with VUE, so I can only make simple modifications.
