### ISSUE TITLE
[Bug] [Worker] Match wrong pid on linux server

### ISSUE THREAD

**Issue by Radeity** [apache/dolphinscheduler#14646]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

If you deploy DS on linux server, cancel process instance, then it's possible to get error log:
```
[ERROR] 2023-07-27 23:14:54.887 +0800 org.apache.dolphinscheduler.server.worker.processor.WorkerTaskKillProcessor:[196] - kill task error
org.apache.dolphinscheduler.common.shell.AbstractShell$ExitCodeException: kill: (26483): Operation not permitted
kill: (558): No such process
kill: (1493): No such process
```

### What you expected to happen

No error log.

### How to reproduce

Ditto.

### Anything else

That is because in `ProcessUtils.getPidsStr`, only match pids on macos and windows.

```java
        if (SystemUtils.IS_OS_MAC) {
            String pids = OSUtils.exeCmd(String.format("%s -sp %d", TaskConstants.PSTREE, processId));
            if (null != pids) {
                mat = MACPATTERN.matcher(pids);
            }
        } else {
            String pids = OSUtils.exeCmd(String.format("%s -p %d", TaskConstants.PSTREE, processId));
            mat = WINDOWSATTERN.matcher(pids);
        }
```

If run on linux server, will get pids string like: `sudo(6279)---558_1497.sh(6282)---sleep(6354)`, but if use windows matcher,  it will match "6279 558 1497 6282 6354", expected matching results is "6279 6282 6354".

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
I'll fix it
