### ISSUE TITLE
[Feature][Alert] Add prometheus's Alertmanager 

### ISSUE THREAD

**Issue by Gallardot** [apache/dolphinscheduler#14654]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Prometheus is the most popular cloud-native monitoring and alerting system.
We hope to support sending alerts directly to prometheus's [Alertmanager](https://prometheus.io/docs/alerting/latest/alertmanager/).

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xjlgod** [comment]
Is this issue still to finish？

**Comment by Gallardot** [comment]
> Is this issue still to finish？

@xjlgod Yes. Would you like to help the community to explore this? Welcome pr

**Comment by xjlgod** [comment]
> > Is this issue still to finish？
> 
> @xjlgod Yes. Would you like to help the community to explore this? Welcome pr

ok, please assign to me.
