### ISSUE TITLE
[Bug] [Task Instance] view log is empty

### ISSUE THREAD

**Issue by q4q5q6qw** [apache/dolphinscheduler#14663]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After the shell workflow is executed, check logs. If the workflow is executed successfully, result logs are generated in normal cases. However, no logs are generated occasionally, and only the log generation path is displayed.

### What you expected to happen

After the shell workflow is executed, check logs

### How to reproduce

no idea

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MyLoveZhou** [comment]
我认为可能是上线的时候日志清空，以至于UI无法显示日志。你需要在上线的时候保证日志文件在logs中存在。（I think it may be that the log is cleared when going online, so that the UI cannot display the log. You need to ensure that the log file exists in logs when you go online.）
