### ISSUE TITLE
[Bug] [dolphinscheduler-tools] The MigrateResourceService class failed to compile in the zookeeper 3.4.14 version

### ISSUE THREAD

**Issue by shilei-ly** [apache/dolphinscheduler#14668]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The **MigrateResourceService.java** failed to compile with the zookeeper 3.4.14 version.  </br> </br>**Error Log**: /dolphinscheduler-tools/src/main/java/org/apache/dolphinscheduler/tools/resource/MigrateResourceService.java:[30,35] 找不到符号. </br>The reason is zk doesn't have `StringUtils.java` in zookeeper3.4.14.  An incorrect jar package was imported.
![image](https://github.com/apache/dolphinscheduler/assets/97011595/cabcb80b-d9f0-4302-bcd3-9d3f969b12fe)

### What you expected to happen

dolphinscheduler should build successful with zookeeper 3.4.14 version.

### How to reproduce

build dolphinscheduler with zk3.4.14

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Thanks for correcting this import, please use `org.apache.commons.lang3.StringUtils` instead.
