### ISSUE TITLE
[Bug] [task definition] page break

### ISSUE THREAD

**Issue by sdhzwc** [apache/dolphinscheduler#14673]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/apache/dolphinscheduler/assets/46134044/e4520d0e-1dcf-4b62-83f8-b44333094274)
![image](https://github.com/apache/dolphinscheduler/assets/46134044/58af1ca8-b617-466e-b8a9-b060251a0448)
![image](https://github.com/apache/dolphinscheduler/assets/46134044/a65a2c5a-3b43-4b1c-a952-2eeb7e6d82b1)
前两页显示不对 第三页开始才正确

### What you expected to happen

显示正常分页

### How to reproduce

1

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
Please post a screenshot with the api param

**Comment by sdhzwc** [comment]
> Please post a screenshot with the api param
![image](https://github.com/apache/dolphinscheduler/assets/46134044/602c3f48-e28e-47fc-8121-e35e5c3987fa)

![image](https://github.com/apache/dolphinscheduler/assets/46134044/28e86f04-c771-4734-b9b1-bac9c25cba66)

**Comment by CallMeKingsley97** [comment]
Sorry, I can't reproduce it. Can you give us some other information which you guess can produce it?

**Comment by sdhzwc** [comment]
> Sorry, I can't reproduce it. Can you give us some other information which you guess can produce it?
我研究一天 发现3.2.0版本已经修复，但是3.1.8以下还是存在此问题的，如下
3.2.0版本
![image](https://github.com/apache/dolphinscheduler/assets/46134044/44e572d4-bb9c-45e8-b8a3-e883274725a4)
3.1.8
![image](https://github.com/apache/dolphinscheduler/assets/46134044/19c93f0f-954c-44d6-97c2-c79ebfe34f40)

**Comment by sdhzwc** [comment]
#13106

**Comment by CallMeKingsley97** [comment]
Now that it has been fixed, the issue could be closed？

**Comment by sdhzwc** [comment]
> Now that it has been fixed, the issue could be closed？

ok
