### ISSUE TITLE
[Feature] SqlTask support #{} that only replace parameter,Do not check data types and convert it.

### ISSUE THREAD

**Issue by coding-now** [apache/dolphinscheduler#1467]
SqlTask,support ${} currently ,want support# {} too ,an example as follows:
```
select a,b,c,${param1}
from #{param2}
where #{param3}=${param4}
```
,where **param2,param3 may be setted through preSql.**

**preSql support return value,support Query SQL. and return key is paramer name.**

**Comment by lgcareer** [comment]
Thanks for your suggest,Now preSql and postSql support NonQuery sql,This feature has not been added to the development plan.If you are interested in this,You can also contribute the code.

**Comment by coding-now** [comment]
ok,I will impl this issue later ,Please assign it to me

**Comment by CalvinKirs** [comment]
What needs to be determined is whether this kind of symbol may conflict
