### ISSUE TITLE
[Feature][Master][UI] Dependent task parameter passing

### ISSUE THREAD

**Issue by Orange-Summer** [apache/dolphinscheduler#14678]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Dependent tasks can choose to inherit the output parameters of the dependent item and output them to downstream tasks.
This is a [DolphinScheduler project of OSPP-2023.](https://summer-ospp.ac.cn/org/prodetail/232290357)

### Use case

Add an option, when the dependent result is success, the dependent task will inherit the output parameters of the dependent item that runs successfully and this option is true
![image](https://github.com/apache/dolphinscheduler/assets/61171207/cb494401-6467-42fb-8a94-a02e9cafc4d0)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
Nice,Do you working for it?

**Comment by Orange-Summer** [comment]
Yes, I'm ready to submit a PR.
