### ISSUE TITLE
After reporting an error in the batch on the same day, the batch on the second day needs to be stuck. Currently, there is no relevant configuration and the batch starts normally on the second day. After reporting an error in the batch on the same day, the batch on the second day needs to be stuck. Currently, there is no relevant configuration and the batch is started normally on the second day.

### ISSUE THREAD

**Issue by zhangjun-zh** [apache/dolphinscheduler#14681]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

当日批量报错后，周末相关人员不在公司，再没处理之前，次日批量不允许自动执行； 需要增加可配置项；

### Use case

当日批量报错后，周末相关人员不在公司，再没处理之前，次日批量不允许自动执行； 需要增加可配置项；

### Related issues

当日批量报错后，周末相关人员不在公司，再没处理之前，次日批量不允许自动执行； 需要增加可配置项；

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please use the correct title and description in English. Closing this issue now.
