### ISSUE TITLE
[Bug] [Resource Center] Can not upload resource successfully

### ISSUE THREAD

**Issue by Radeity** [apache/dolphinscheduler#14705]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="1084" alt="image" src="https://github.com/apache/dolphinscheduler/assets/45198818/e7941254-9296-4b95-bf62-add21478faf1">

### What you expected to happen

Upload successfully.

### How to reproduce

Upload a resource.

### Anything else

Maybe forgot to update upload api in new resource center. 

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi @SbloodyS , would you like to test it?

**Comment by SbloodyS** [comment]
The current file-manage-e2e-test includes operations for uploading and downloading using Minios3. Can you provide more detail of reproduce this? @Radeity

**Comment by Radeity** [comment]
I test it in standalone mode, and use HDFS storage plugin, download has no problem.

**Comment by zhongjiajie** [comment]
maybe #14826 had fix this issue
