### ISSUE TITLE
spark task parameters show row number

### ISSUE THREAD

**Issue by lazybird23** [apache/dolphinscheduler#14708]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://github.com/apache/dolphinscheduler/assets/20657712/dd24cdcc-4b95-48cd-8c6f-8fb8f582afb9)
![image](https://github.com/apache/dolphinscheduler/assets/20657712/beee930b-9576-42af-8e3a-ba6a4f3df892)

eg:
line1:journey.split.version=XXXX journey.split.time.threshold.min=120 start.day=2022-11-01 end.day=2022-11-30 input.repartition.num=500 sink.repartition.num=500 appName=XXXX master=yarn-cluster stay.time.threshold.min=5 invalid.speed.low.threshold.kmh=5  invalid.speed.high.threshold.kmh=120 input.table.name=XXXXX
line2:journey.split.schedule.type=month autoBroadcast=false
edit page display line number，if parameters has line break shell will execute more command。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
You can try add "  \\" before each line break.

**Comment by lazybird23** [comment]
> You can try add " \" before each line break.

you are right, but in fact people ignore this, edit view not to show line break.
