### ISSUE TITLE
[Bug] [flink task] problem with the command generated by the flink task 

### ISSUE THREAD

**Issue by LiuCanWu** [apache/dolphinscheduler#14729]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. The determinedYarnQueue method in the FlinkArgsUtils class and the switch statement of the doAddQueue method lack a break, resulting in problems with the generated flink commands
2. The result of my experiment is that if you want to submit to the specified queue, you need to put the -Dyarn or -yqu parameter before -c, so you need to put the determinedYarnQueue method on line 284 before line 261

### What you expected to happen

Generate the correct flink submission task command and submit it to the specified yarn queue

### How to reproduce

Try to submit the flink task to the specified yarn queue under version 3.1.8

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
From the above description, I think it's a **good first issue** , Are you willing to submit a pr？

**Comment by LiuCanWu** [comment]
>

**Comment by LiuCanWu** [comment]
> From the above description, I think it's a **good first issue** , Are you willing to submit a pr？

of course，i will submit a pr to fix this issue

**Comment by LiuCanWu** [comment]
> From the above description, I think it's a **good first issue** , Are you willing to submit a pr？

of course，I will submit a pr to fix this issue.
