### ISSUE TITLE
[Feature][TaskType] Support `for` task type

### ISSUE THREAD

**Issue by icefery** [apache/dolphinscheduler#14737]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

If I want to process some thing in batch, suck as sql batch insert, there is no out-of-the-box task type to use.

There are two alternative ways:

- Pack a program with batch processing code, then upload to dolphinscheduler context, use `Shell` task to execute it.

- Use additional external context to store batch task progress informations (such as `for (i : range)`), task need to update these external context informations.

But neither of them is easy-to-use, hope that dolphinscheduler would provide a `for`/`loop` task type to wrap existing tasks, or get existing tasks `for`/`loop` supported natively.

### Use case

Loop execute task like following codes:

```js
// before task
exec(`truncate table t_target`)

// range task
for(let key of ['a', 'b', 'c', 'd']) {
    exec(`
        insert into t_target
        select *
        from t_some_complex_from_expression
        where key = ${key}
    `)
}

// after task
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
There are currently no plans for that
