### ISSUE TITLE
[Feature][Process Instance] Adding folder for process instance list

### ISSUE THREAD

**Issue by batmanneverdie** [apache/dolphinscheduler#14732]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Now, DS place all process instances in one list. In some scenarios, one project could have many process instances even exceed one hundred. In this case, user want to find some specific process is very inconvenience even have search and paging.

![image](https://github.com/apache/dolphinscheduler/assets/41139080/2c313760-3346-45ae-87b5-b4baedc79c83)

I think DS cloud add a `FOLDER` feature to manage process instances, just like windows file system, for prevent user create many deep folders, we could restrict the `FOLDER` depth.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
There are currently no plans for that
