### ISSUE TITLE
[Bug] [Task Dependency] Abnormal duplication of predecessor tasks

### ISSUE THREAD

**Issue by JensonZou** [apache/dolphinscheduler#14733]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

我在工作流中提交任务时发现前置任务会出现异常重复的情况

### What you expected to happen

修复异常重复的问题

### How to reproduce

从2.7版本中导出工作流文件在导入到3.1.7版本中会出现前置任务重复情况

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JensonZou** [comment]
![tO6Fw1j8gz](https://github.com/apache/dolphinscheduler/assets/109135801/c77e95e8-5aea-4f5f-bd83-0a1af7da774e)

![sJctnn6kSn](https://github.com/apache/dolphinscheduler/assets/109135801/d10ccce1-66ed-429a-ac0e-d17786d0efea)

**Comment by SbloodyS** [comment]
Fixed.
