### ISSUE TITLE
[Bug] [Master] modify the upper and lower limits of the thread pool

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#14744]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The number of core threads in the thread pool is the same parameter as the maximum number of threads

### What you expected to happen

The number of core threads in the thread pool is the same parameter as the maximum number of threads

### How to reproduce

Modify the parameters used by the number of core threads

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
This is not a bug.
