### ISSUE TITLE
[Bug] [Data Quality] path is null

### ISSUE THREAD

**Issue by Meek777** [apache/dolphinscheduler#14747]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.DS Version: 3.1.x
2.path is null

the following logs:
[WARN] 2023-08-15 13:04:32.854 +0800 org.apache.dolphinscheduler.service.log.LoggerRequestProcessor:[189] - [WorkflowInstance-0][TaskInstance-0] - path is null
[ERROR] 2023-08-15 13:04:32.854 +0800 org.apache.dolphinscheduler.remote.handler.NettyServerHandler:[131] - [WorkflowInstance-0][TaskInstance-0] - process msg Command [type=ROLL_VIEW_LOG_REQUEST, opaque=195, bodyLen=41] error
java.lang.IllegalArgumentException: Illegal path: 
	at org.apache.dolphinscheduler.service.log.LoggerRequestProcessor.process(LoggerRequestProcessor.java:112)
	at org.apache.dolphinscheduler.remote.handler.NettyServerHandler.lambda$processReceived$0(NettyServerHandler.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### What you expected to happen

[Data Quality] Path is null generate Illegal path(IllegalArgumentException)

### How to reproduce

[Data Quality] Path is null generate Illegal path(IllegalArgumentException)

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Meek777** [comment]
why path is null
![image](https://github.com/apache/dolphinscheduler/assets/49811719/e6a7f7e6-2013-44fe-aaf7-a54c6e28be5f)

**Comment by Meek777** [comment]
why path is null
![image](https://github.com/apache/dolphinscheduler/assets/49811719/96d87fed-9ffc-49a1-a432-77fc603797bb)

**Comment by hanpi14** [comment]
I also encountered the same problem. Have you solved it here?

**Comment by hanpi14** [comment]
I also encountered the same problem. Have you solved it here?
