### ISSUE TITLE
[Bug] [S3 Resource]  Files not uploaded to s3 through dolphinscheduler web console cannot be displayed on dolphinscheduler web console

### ISSUE THREAD

**Issue by ahululu** [apache/dolphinscheduler#14757]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Files not uploaded to s3 through dolphinscheduler web console cannot be displayed on dolphinscheduler web console.That is to say, the files I uploaded through the aws console are not displayed in the dolphinscheduler web console

### What you expected to happen

should show any resource in s3 no only upload by dolphinscheduler web console

### How to reproduce

just try that must reproduce

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
You can try 3.2.0-prepare, we have refactored resource center to solve this problem.
