### ISSUE TITLE
[Bug] [Api] If delete task definition, can't delete workflow

### ISSUE THREAD

**Issue by HomminLee** [apache/dolphinscheduler#14753]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

If delete task definition, can't delete workflow.

<img width="1375" alt="image" src="https://github.com/apache/dolphinscheduler/assets/25881185/67a44bbd-3ef4-4cfb-8ba8-c85e3e6f70cf">

Api.log:
<img width="1343" alt="image" src="https://github.com/apache/dolphinscheduler/assets/25881185/aeb4e5cf-f8a5-427e-b3ca-8af1e627f89b">

### What you expected to happen

delete workflow

### How to reproduce

1. create a workflow contain a task
2. delete task in 'Task Definition' page
3. delete workflow

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
Looking forward to your pr

**Comment by MyLoveZhou** [comment]
Just make a judgment.I will fix this issue.
