### ISSUE TITLE
[Bug] [dolphinscheduler-master] node disable issue

### ISSUE THREAD

**Issue by skywalker2256** [apache/dolphinscheduler#14758]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

节点禁用后工作流卡住不继续执行，如下图test456节点会不运行！
dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
1873行，else if (DependResult.NON_EXEC == dependResult) 
状态判断没有WAITING 状态，这里是否可以添加？

### What you expected to happen

![图片](https://github.com/apache/dolphinscheduler/assets/41573491/49a6f422-5f3d-4ebf-8690-96074211f792)

### How to reproduce

![图片](https://github.com/apache/dolphinscheduler/assets/41573491/49a6f422-5f3d-4ebf-8690-96074211f792)

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @skywalker2256 , would you like to fix it?
