### ISSUE TITLE
The http tool is really difficult to use

### ISSUE THREAD

**Issue by clearcodecn** [apache/dolphinscheduler#14759]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

http工具做的真难用

### Use case

http工具做的真难用

### Related issues

http工具做的真难用

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tracehh** [comment]
What is the specific embodiment？
By the way，you don't need to use it.
