### ISSUE TITLE
[Bug] [ dolphin scheduler-alert] Create http request error

### ISSUE THREAD

**Issue by hunter-cloud09** [apache/dolphinscheduler#14777]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When using the http alarm plug-in, the request method passed in by the front end is lowercase, while the backend uses uppercase when judging

### What you expected to happen

user equalsIgnoreCase

### How to reproduce

use equalsIgnoreCase

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
A good first issue. Looking forward to your pr

**Comment by hunter-cloud09** [comment]
> A good first issue. Looking forward to your pr

please review it when you are free. thx.

**Comment by CallMeKingsley97** [comment]
> > A good first issue. Looking forward to your pr
> 
> please review it when you are free. thx.

LGTM, You can @ one of the member to assign the issue for you

**Comment by brave-lee** [comment]
closed by #14793
