### ISSUE TITLE
[Bug] [资源中心-UDF管理-资源管理] 上传文件偶现报错，频次较高

### ISSUE THREAD

**Issue by mengmengxinwanttobeabiggod** [apache/dolphinscheduler#14779]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

海豚3.1.6版本，在海豚的UDF管理的文件上传中上传文件，偶尔可以成功上传,有时候会出现这个报错，当出现这报错的时候会持续失败，但是当强制清理缓存后，有时候会好一段时间之后可能又会报错， 换了不同机器，不同的人也是反馈有时候是好的 有时候报错，当报错的时候，经过日志定位分析：nginx日志和海豚api的日志都没内容，请问各位大大有没遇到这问题?
<img width="861" alt="1692604445190" src="https://github.com/apache/dolphinscheduler/assets/31102116/65324fb4-842f-4392-8613-e97aa707c622">

<img width="937" alt="1692603932913" src="https://github.com/apache/dolphinscheduler/assets/31102116/ba232333-0773-4b75-949e-f63691b17b19">
<img width="960" alt="1692603945106" src="https://github.com/apache/dolphinscheduler/assets/31102116/eda1a29f-c1c1-475c-9c5c-996e2fb71c77">

### What you expected to happen

期望每次都可以上传文件。

### How to reproduce

希望多测试下这路径下上传文件，多上传多次就会重新，目前我使用的海豚3.1.6版本

### Anything else

最初我的浏览器是google版本，上传的时候一直会报错，而别的伙伴有时候是正常的（有时候也会失败），但是我们的谷歌浏览器版本不一致，他们是较新的，我就升级了浏览器版本后，也会成功了，我以为问题解决了，但是多测试几次上传后，有时候又会出现这报错问题，一旦出现这报错后，在不清理浏览器缓存的情况下，会持续报错，但是清理缓存后，又会好一段时间可以成功上传，但是多次上传后又可能会报错。

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by boy-xiaozhang** [comment]
hi Are you using hdfs or something in your resource center outlet，Can you post the api-server log when the error was reported
