### ISSUE TITLE
Scheduling business code What if the business code is called through dolphin

### ISSUE THREAD

**Issue by czetao** [apache/dolphinscheduler#14772]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

以前项目使用xxljob 进行业务代码调用,海豚还是有任务组件,进行业务代码的任务调度呢(java 程序)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
Please make the description a little more clearly
