### ISSUE TITLE
[Bug] [Environment Management] When there are multiple environments, the environment change switch in the task does not take effect

### ISSUE THREAD

**Issue by himper** [apache/dolphinscheduler#14784]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

存在多个环境时，任务中的环境变更切换不生效

### What you expected to happen

存在多个环境时，任务中的环境变更切换不生效

### How to reproduce

存在多个环境时，任务中的环境变更切换不生效

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Fixed.
