### ISSUE TITLE
[Feature][task type] It is recommended to add a loop container to support cyclically calling other components in the workflow for task processing.

### ISSUE THREAD

**Issue by himper** [apache/dolphinscheduler#14785]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

建议增加循环容器，以支持在工作流中循环调用其他组件进行任务处理。

### Use case

建议增加循环容器，以支持在工作流中循环调用其他组件进行任务处理。

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sunVII** [comment]
赞同

**Comment by SbloodyS** [comment]
There are currently no plans for that

**Comment by Fortytwoo** [comment]
I need this, which is very important to my work.
