### ISSUE TITLE
[Bug] [ dolphinscheduler-alert] Fix send http request error

### ISSUE THREAD

**Issue by hunter-cloud09** [apache/dolphinscheduler#14781]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

send http request should add port and setMsgInUrl should add URLEncoder.encode for msg

### What you expected to happen

send http request should add port and setMsgInUrl should add URLEncoder.encode for msg

### How to reproduce

send http request should add port and setMsgInUrl should add URLEncoder.encode for msg

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
closed by https://github.com/apache/dolphinscheduler/pull/14793
