### ISSUE TITLE
[sql syntax][dolphinscheduler-dao] DqRuleInputEntryMapper.xml exists postgresql does not support `

### ISSUE THREAD

**Issue by GaoHu1997** [apache/dolphinscheduler#14806]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![企业微信截图_16928561733863](https://github.com/apache/dolphinscheduler/assets/124873767/5895bc90-6310-4a33-a365-c554079f9c2e)

### What you expected to happen

sql syntax error

### How to reproduce

connect postgresql

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
Good first issue,  Looking forward to your pr

**Comment by luugh** [comment]
I also encountered this problem
