### ISSUE TITLE
[Improvement] Add task instance Archive Policy

### ISSUE THREAD

**Issue by impactCn** [apache/dolphinscheduler#14834]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Instances of scheduled tasks are executed every day, and there will be thousands of them after a few days. Since there is no save strategy, it seems that the delete operation can only be done in the database, which will be inconvenient. I think you can add a save strategy when saving the instance.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xjlgod** [comment]
Hi, I would like to contribute to the community. I am currently interested in this issue. Can you give me more hints or tell me where to look at the code details ? a save strategy means to save the instance in the memory?

**Comment by liunaijie** [comment]
now the task instance will keep full history, want apply a save strategy(like 30 days), when the instance log is out of date, delete them. is this right? @impactCn

**Comment by xjlgod** [comment]
> now the task instance will keep full history, want apply a save strategy(like 30 days), when the instance log is out of date, delete them. is this right? @impactCn

Is it similar to turning on a timer to scan instances created more than 30 days ago every day?

**Comment by xjlgod** [comment]
> > now the task instance will keep full history, want apply a save strategy(like 30 days), when the instance log is out of date, delete them. is this right? @impactCn
> 
> Is it similar to turning on a timer to scan instances created more than 30 days ago every day?

Is this issue still to finish?
