### ISSUE TITLE
[Feature][Alert]Enterprise WeChat support send notifications by robot

### ISSUE THREAD

**Issue by ahuljh** [apache/dolphinscheduler#14839]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Chinese：经与企业微信论坛和官方客服确认，企业微信无法发送告警信息到已有的内部群，原因是无法获取到已经创建内部群的chatid，只能通过接口创建，必须要单独创建群聊，不满足实际需求。论坛上有许多人反映此问题，且经受困扰。同时，DolphinScheduler的贡献者群内也有相同的诉求。该问题亟待解决。
English: After confirmation with the enterprise WeChat forum and official customer service, it was found that enterprise WeChat cannot send alarm information to existing internal groups because it cannot obtain the chatid of the already created internal group. It can only be created through the interface and must be created separately, which does not meet actual needs. Many people on the forum have reported this issue and are experiencing difficulties. At the same time, there are similar demands within the contributor group of DolphinScheduler. This problem urgently needs to be solved.

### Use case

经调研，可以通过在群内增加机器人的方式解决。我会新增加一种告警插件，以满足这个需求。
After research, it can be solved by adding robots to the group. I will add a new alarm plugin to meet this requirement.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ahuljh** [comment]
![image](https://github.com/apache/dolphinscheduler/assets/57029745/543e3ec6-0f79-41fc-bf24-651b009bdfed)

![image](https://github.com/apache/dolphinscheduler/assets/57029745/92f40527-1661-423d-aac2-10d421cdf51b)

**Comment by imp2002** [comment]
It looks like just use webhook? DS alert has support it.
https://developer.work.weixin.qq.com/document/path/91770

**Comment by ahuljh** [comment]
> It looks like just use webhook? DS alert has support it. https://developer.work.weixin.qq.com/document/path/91770

Yes, I will use webhook to meet this demand. But DS don't have WebHook Alert Plugin. I will supply this plugin.
![image](https://github.com/apache/dolphinscheduler/assets/57029745/e39b818a-aef1-4295-b273-fa998084b932)

**Comment by ahuljh** [comment]
![image](https://github.com/apache/dolphinscheduler/assets/57029745/14c919ee-7be8-4e8c-a3d9-d7427fe8384e)

**Comment by qingwli** [comment]
Could we use HTTP plugin for this feature?

**Comment by ahuljh** [comment]
> Could we use HTTP plugin for this feature?

Yes, perhaps this is an indirect way of implementation. However, this increases the difficulty of use and requires offering many unnecessary parameters such as header and body. In fact, it is necessary to provide a simpler webhook plugin, which only requires a simple URL to provide.
