### ISSUE TITLE
[Feature][Task-Plugin]Could DS add kettle related task plugin?

### ISSUE THREAD

**Issue by ahuljh** [apache/dolphinscheduler#14848]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Many tranditional factory have kettle retaled demand, such as job, transformation, database repository. So, it is necessary to supply the kettle task plugin.

### Use case

I want to use DS support the schedule way of kettle.

### Related issues

Yes. For example, #14277 #12367 #2032 etc

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by suqingyang** [comment]
Hi ~ how is the progress?Could DS add kettle related task plugin?
