### ISSUE TITLE
Flink executes sql and cannot customize the incoming local parameters

### ISSUE THREAD

**Issue by Aitongong** [apache/dolphinscheduler#14849]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[INFO] 2023-09-01 17:16:41.174 +0800 - flink task params {"localParams":[{"prop":"exe_date","direct":"IN","type":"VARCHAR","value":"2023-06-14"}],"initScript":"","rawScript":"SET sql-client.execution.result-mode=TABLEAU;\r\nset execution.runtime-mode = batch;\r\nCREATE CATALOG iceberg_catalog WITH (\r\n'type'='iceberg',\r\n'catalog-type'='hadoop',\r\n'warehouse'='hdfs://xxx:8020/user/hive/warehouse/hadoop_catalog',\r\n'property-version'='2',\r\n'cache-enable'='true'\r\n);\r\nuse catalog iceberg_catalog;\r\n\r\nselect ms_id,machine_code from iceberg_catalog.database.table\r\nwhere date_id='${exe_date}' limit 10;\r\n\r\n\r\n\r\n","resourceList":[],"programType":"SQL","mainClass":"","deployMode":"cluster","flinkVersion":">=1.13","jobManagerMemory":"1G","taskManagerMemory":"1G","slot":1,"taskManager":2,"parallelism":1}

实际执行参数没有替换 以下日志
	[32mFlink SQL[0m> CREATE CATALOG iceberg_catalog WITH (
	'type'='iceberg',
	'catalog-type'='hadoop',
	'warehouse'='hdfs://xxx:8020/user/hive/warehouse/hadoop_catalog',
	'property-version'='2',
	'cache-enable'='true'
	);
	[34;1m[INFO] Execute statement succeed.[0m
	[32mFlink SQL[0m> use catalog iceberg_catalog;
	[34;1m[INFO] Execute statement succeed.[0m
	[32mFlink SQL[0m> 
	select ms_id,machine_code from iceberg_catalog.database.table
	where date_id=**'${exe_date}'** limit 10;

### What you expected to happen

flink版本:1.15.3
ds版本：3.1.7
传入的局部参数代码中解析后没有使用

### How to reproduce

1.自定义工作流->选择flink->程序类型选择SQL  执行任意连接语句
2.使用如以下表查询 `select ms_id,machine_code from iceberg_catalog.database.table
	where date_id='${exe_date}' limit 10`
3.自定义参数 `key = exe_date`，  `value = 2023-06-14`

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
There is no function to replace local parameters for flink task（sql mode).
Looking forward to your pr
