### ISSUE TITLE
[Bug] [数据质量] class org.apache.dolphinscheduler.plugin.datasource.mysql.param.MySQLConnectionParam com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot coerce empty String ("")

### ISSUE THREAD

**Issue by skywalker2256** [apache/dolphinscheduler#14858]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

版本3.2.0执行数据质量模块报错
[ERROR] 2023-09-05 13:25:28.676 +0800 - Parse object exception, jsonStr: {"other":"","address":"jdbc:mysql://:3306","user":"cdh","password":"********","database":"ds_dev","jdbcUrl":"jdbc:mysql://172.24.1.9:3306/ds_dev"}, class: class org.apache.dolphinscheduler.plugin.datasource.mysql.param.MySQLConnectionParam
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot coerce empty String ("") to element of java.util.LinkedHashMap<java.lang.String,java.lang.String> (but could if coercion was enabled using CoercionConfig)
at [Source: (String)"{"other":"","address":"jdbc:mysql://:3306","user":"","password":"","database":"ds_dev","jdbcUrl":"jdbc:mysql://172.24.1.9:3306/ds_dev"}"; line: 1, column: 10] (through reference chain: org.apache.dolphinscheduler.plugin.datasource.mysql.param.MySQLConnectionParam["other"])
at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
at com.fasterxml.jackson.databind.DeserializationContext.reportBadCoercion(DeserializationContext.java:1806)
at com.fasterxml.jackson.databind.deser.std.StdDeserializer._checkCoercionFail(StdDeserializer.java:1477)

解析配置文件中的mysql时报other是字符串，配置文件中的mysql改怎么配置

### What you expected to happen

class org.apache.dolphinscheduler.plugin.datasource.mysql.param.MySQLConnectionParam
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot coerce empty String ("") to element of java.util.LinkedHashMap<java.lang.String,java.lang.String> (but could if coercion was enabled using CoercionConfig)
at [Source: (String)"

### How to reproduce

正常运行

### Version

3.2.0-prepare

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
You can remove the **other**  field, and try again

**Comment by AmriStrong** [comment]
jdbc连接参数
先不要填写试试

**Comment by niyanchun** [comment]
@CallMeKingsley97 @AmriStrong  the `other` string seems generated by ds automatically，and is jdbc url to ds's own meta mysql, not user's datasource,  I got this problem too.

**Comment by code-dm** [comment]
+1 相同的报错

**Comment by 13137218758** [comment]
你好，怎么解决的？改源码？

**Comment by skywalker2256** [comment]
是的，改了下他这个连接，这个版本和之前用的2.7连接类定义不一样，然后不知道是他们没改完还是配置不对，我们是把类改了，不报错。。。继续用发自我的手机-------- 原始邮件 --------发件人： 13137218758 ***@***.***>日期： 2024年1月17日周三 中午12:18收件人： apache/dolphinscheduler ***@***.***>抄送： skywalker2256 ***@***.***>, Author ***@***.***>主    题： Re: [apache/dolphinscheduler] [Bug] [数据质量] class org.apache.dolphinscheduler.plugin.datasource.mysql.param.MySQLConnectionParam com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot coerce empty String ("") (Issue #14858)
你好，怎么解决的？改源码？

**Comment by zhongjiajie** [comment]
close by https://github.com/apache/dolphinscheduler/pull/15551

**Comment by williamlin88** [comment]
我也出现这样的问题怎么处理的呢？
