### ISSUE TITLE
[Bug] Dependent components cannot be justified and viewed (dependent components cannot be edited and viewed)

### ISSUE THREAD

**Issue by AmriStrong** [apache/dolphinscheduler#14865]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

What happened
从3.0.0升级到3.1.7之后，原有的"dependent"组件，在工作流实例中，有些dependent无法查看和编辑，但是新建流程不受影响。
我们通过调整源码已经解决这个问题
 #![image](https://github.com/apache/dolphinscheduler/assets/24251573/8c31f12c-5ae1-49d7-a60e-b8069504f150)

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qingwli** [comment]
Hi @AmriStrong  Have you tested in dev branch?

**Comment by guowei-su** [comment]
> Hi @AmriStrong Have you tested in dev branch?

This problem also exists in dev, and is caused by a logic error in the UI module's handling of the state of dependent nodes (when there are multiple dependent nodes in the workflow).

**Comment by qingwli** [comment]
Ok, look forward your pr

**Comment by AmriStrong** [comment]
> 你好@AmriStrong 你在dev分支测试过吗？

测试过的，我们已经部署上生产使用了。我们调整UI 代码，把use-node-status.ts
![image](https://github.com/apache/dolphinscheduler/assets/24251573/2ef9f05e-ebbf-4cd0-96ef-45953e672317)
