### ISSUE TITLE
Jetcd will drop java 8

### ISSUE THREAD

**Issue by liangyuanpeng** [apache/dolphinscheduler#14867]
### Description

Hi dolphinscheduler community, just for note that Jetcd will drop java 8, please check https://github.com/etcd-io/jetcd/issues/1218

**Comment by ruanwenjun** [comment]
DS can work well at jdk11, so this will not affect ds.

But some projects drop jdk11 too, I think we need to discuss adapting the higher JDK e.g. jdk17.

But before adopting jdk17, we need to provide a stable version.

**Comment by liangyuanpeng** [comment]
Thanks for your confirm that!
