### ISSUE TITLE
Global variables cannot be used in sql using insert into ${dwd_db}.table_name  error

### ISSUE THREAD

**Issue by liusy-bd** [apache/dolphinscheduler#14882]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I define a global variable of dwd_db=lht_dwd_test

You can't use it in downstream sql

insert into ${dwd_db}.base_product  select * from lht_oibp_fmds_tbls_dev.base_product limit 5 ;

Global variables can be applied to where,May I ask what the problem is,Looking forward to your reply!!!!

### What you expected to happen

Global variables can be applied to where,May I ask what the problem is

### How to reproduce

I define a global variable of dwd_db=lht_dwd_test

You can't use it in downstream sql

insert into ${dwd_db}.base_product  select * from lht_oibp_fmds_tbls_dev.base_product limit 5 ;

Global variables can be applied to where,May I ask what the problem is,Looking forward to your reply!!!!

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liusy-bd** [comment]
![Uploading 5f4dff6791e9950f93cfd682b02ff8f.png…]()

**Comment by liusy-bd** [comment]
![Uploading 5f4dff6791e9950f93cfd682b02ff8f.png…]()

**Comment by AmriStrong** [comment]
你要在每个子流程里面，加上对应的参数才可以

**Comment by AmriStrong** [comment]
![image](https://github.com/apache/dolphinscheduler/assets/24251573/c621bc10-c048-4294-8c1c-27383769b1e7)
例如这样

**Comment by liusy-bd** [comment]
> ![图像](https://user-images.githubusercontent.com/24251573/267041484-c621bc10-c048-4294-8c1c-27383769b1e7.png) 例如这样

能贴个完整的例子吗 我按照这样操作不行哎  clickhousesql
![image](https://github.com/apache/dolphinscheduler/assets/69708156/653e861a-e3cd-4065-a764-072a0dd7b2c9)

**Comment by liusy-bd** [comment]
> ![image](https://user-images.githubusercontent.com/24251573/267041484-c621bc10-c048-4294-8c1c-27383769b1e7.png) 例如这样

我在上游设置全局参数 在下游是可以直接读到的 不用另外加参数
![image](https://github.com/apache/dolphinscheduler/assets/69708156/efed6734-93fd-4797-a910-71e203105be0)
但是如图，是带引号的 应用不到db位置上

**Comment by liusy-bd** [comment]
> > ![image](https://user-images.githubusercontent.com/24251573/267041484-c621bc10-c048-4294-8c1c-27383769b1e7.png) 例如这样
> 
> 我在上游设置全局参数 在下游是可以直接读到的 不用另外加参数 ![image](https://user-images.githubusercontent.com/69708156/267289637-efed6734-93fd-4797-a910-71e203105be0.png) 但是如图，是带引号的 应用不到db位置上

并且我用$[dwd_db] 取参数 会卡住，换成${dwd_db}则不会出现host实例为空的报错
![image](https://github.com/apache/dolphinscheduler/assets/69708156/7783a856-d1ee-46ab-929a-b09b2f3db959)
