### ISSUE TITLE
[Improvement][Master] Master overload will delay scheduling of high priority process

### ISSUE THREAD

**Issue by Radeity** [apache/dolphinscheduler#14884]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We have the conception `Process priority`:
> Process priority: The priority of process operation, divide into five levels: highest (HIGHEST), high (HIGH), medium (MEDIUM), low (LOW), and lowest (LOWEST). When the number of master threads is insufficient, high priority processes will execute first in the execution queue, and processes with the same priority will execute in the order of first in, first out.

However, in cluster mode, when we have multi-master nodes, it's possible that one master node becomes overload and do not consume new command (including some process with the highest priority). Some processes with low priority handled by other Master may run earlier. **Thus, the actual behavior may not be same with priority order.**

#### Three ideas about this:
- The first one is directly declare in doc about this scenario (not recommend).
- The second one is when we judge overload for five(configurable) consecutive rounds, current master should fetch commands and send those commands with higher priority to other Master nodes. In a word, after introducing this mechanism, we combine **push-based** with **pull-based** way to consume commands in Master.
- The third one is to introduce a coordinator, each master can fetch commands from coordinator, and replace current slot-based consuming logic.

#### And there's an existed solution proposed in https://github.com/apache/dolphinscheduler/issues/14271
However, on my side, scale-down is a little inappropriate, slot changes is a relatively heavy step, in DS current design, getting aware of slot changes can only guarantee eventual consistency, which means that several master may consume same commands, although we declare some transaction to make sure command will not be re-consumed, it still cause a waste of resource.

#### Some other related work
In addition, maybe auto-scaling Master nodes can also help, I think we can do it in later PR cuz it's a cloud-native feature. Although scale-up will also cause slot changes, we have more Master nodes and increase the computing capacity to share the pressure, which means it will bring more advantage than negative effect. 

Anyway, we do have to figure out some way for current design flaws (for those deploy in cluster mode and do not have any scalable ability). And I think the solution for this issue and feature of auto-scaling Master nodes can **CO-EXIST**.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
cc @ruanwenjun

**Comment by Radeity** [comment]
After some discussion, I will add overload states in master heartbeat first (slot change solution) which makes the minimal change.

**Comment by ruanwenjun** [comment]
> After some discussion, I will add overload states in master heartbeat first (slot change solution) which makes the minimal change.

Yes, we need redesign the master heartbeat info, and add server status in master heartbeat.
