### ISSUE TITLE
[Bug] task can't find resource file when upgrade ds 2.0.5 to 3.2.0

### ISSUE THREAD

**Issue by mchcz** [apache/dolphinscheduler#14891]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1、Version 2.0.5：create process test0911 && add shell components "sh test.sh" && choose "test.sh" file at Resource District
2、upgrade ds version from 2.0.5 to 3.2.0
3、login ds from version 3.2.0 && run process "test0911" 
4、got error lost resource file
5、open process "test0911" && View SHELL Component Resource Radio Box => find it empty

### What you expected to happen

The resource radio box can display resource files normally.

### How to reproduce

Version 2.0.5：
![image](https://github.com/apache/dolphinscheduler/assets/18095523/461ea287-b36b-4b2b-abf7-cc216435641e)

Version 3.2.0：
![image](https://github.com/apache/dolphinscheduler/assets/18095523/2aa7eb09-83bf-4f9a-9330-b6afd02da957)

In 3.2.0，Resource radio box is empty，It is necessary to choose again to execute normally, but we have a lot of such tasks, and it seems unrealistic to choose all in the PRD environment once.

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
There is a migration tools for it. You can take a look at https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/zh/guide/upgrade/upgrade.md#%E8%B5%84%E6%BA%90%E8%BF%81%E7%A7%BB.

**Comment by mchcz** [comment]
> There is a migration tools for it. You can take a look at https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/zh/guide/upgrade/upgrade.md#%E8%B5%84%E6%BA%90%E8%BF%81%E7%A7%BB.

Thanks,Brother Xiang! My mistake.

**Comment by mchcz** [comment]
> There is a migration tools for it. You can take a look at https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/zh/guide/upgrade/upgrade.md#%E8%B5%84%E6%BA%90%E8%BF%81%E7%A7%BB.

That's not what I meant. After upgrading, you can see the resource files in the resource center, but in the task, the files in the resource options are missing and you need to reselect them. This is not a problem, it's just a bug

**Comment by nbeeee** [comment]
I also encountered the same problem, where the resource ID in the task definition was changed to a name, but the migration script did not have any related operations
