### ISSUE TITLE
[Bug] [API] Keep printing null if task log file not exist

### ISSUE THREAD

**Issue by Radeity** [apache/dolphinscheduler#14895]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

If we manually delete log file on Worker server, then we query logs and it will keep printing null log in UI page. And it will also print thousands of rows backend logs in a moment. 

The reason is response of queryLog contains `data.message` "null" (String value), and will send another request to rolling view logs . It should directly return null to represent no more logs.

<img width="782" alt="image" src="https://github.com/apache/dolphinscheduler/assets/45198818/6447cb22-1488-494b-ad80-34fa468e667e">

### What you expected to happen

Do not send requests continuously.

### How to reproduce

Easy to reproduce, just delete a task log file and then query it.

### Anything else

Test in dev, not sure if the bug exists in release version.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
I'll check and fix it later today.

**Comment by zhangxiuyan** [comment]
> 今天我会检查并修复它。

The queryLog method of the batch task page is called in a loop when the worker loses connection

**Comment by Radeity** [comment]
> The queryLog method of the batch task page is called in a loop when the worker loses connection

Hi @zhangxiuyan , you can open a new issue to track this problem and give more detailed description about this, thx.
