### ISSUE TITLE
After dolphinscheduler schedules the spark task on yarn, the show part cannot be seen in the task instance log.

### ISSUE THREAD

**Issue by TheWindIsRising** [apache/dolphinscheduler#14903]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

使用helm部署了一套dolphinscheduler3.1.2
后续写了一个spark测试模型通过dolphinscheduler调度到了yarn上，模型中用到了df.show函数打印数据，方便查看数据的准确性与测试数据，但是当我执行完任务 在任务日志实例中，并没有看到show的部分，是否可以增加一个全局变量参数设置一个日志的权限或者等级或者页面上增加一个选项

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
It's not a ds issue. `spark-submit` would not print any log of `df.show()`.
