### ISSUE TITLE
[Bug] [dolphinscheduler-API] Delete workflow error

### ISSUE THREAD

**Issue by jwm156** [apache/dolphinscheduler#14917]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

如果工作流中仅有一个任务，在页面上先删除该任务之后，再去删除相应的工作流，页面会报错，不让删除。
但是如果此时去修改工作流，添加一个任务，保存成功之后，再次删除的话即可成功。

### Use case

能正常删除工作流。

### Related issues

3.1.8

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
Please check if your situation is simliar to this issue  #14753

**Comment by jwm156** [comment]
> Please check if your situation is simliar to this issue #14753

Yes, it is simliar to this issue #14753.

**Comment by CallMeKingsley97** [comment]
> > Please check if your situation is simliar to this issue #14753
> 
> Yes, it is simliar to this issue #14753.
Can we close this issue?  Just focus on that issue  #14753. I see someone has already submit a pr

**Comment by jwm156** [comment]
> > > Please check if your situation is simliar to this issue #14753
> > 
> > 
> > Yes, it is simliar to this issue #14753.
> > Can we close this issue?  Just focus on that issue  #14753. I see someone has already submit a pr

ok ok
