### ISSUE TITLE
[Question][SPARK] Can Spark nodes support running in Spark Standalone mode?

### ISSUE THREAD

**Issue by weilai201** [apache/dolphinscheduler#14914]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

目前，在国内项目中，spark使用standalone方式部署的也不少。那么，我们的Spark节点是否可以支持此种模式。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AmriStrong** [comment]
dolphinsheduler support spark to deploy on standalone mode . You need to add a master in the parameter, too
