### ISSUE TITLE
[Bug] [master server] retry task not work

### ISSUE THREAD

**Issue by 997759790** [apache/dolphinscheduler#14928]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After configuring retry, when it fails, the retry task will not be executed occasionally.

### What you expected to happen

After configuring retry, when it fails, the retry task will be executed.

### How to reproduce

occasionally

### Anything else

my version is 2.0.5

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
Please give more information. 
1. What kind of task 
2. The configuration of this task.

**Comment by 997759790** [comment]
replied as below:
1.http task
2.
![RTX截图未命名](https://github.com/apache/dolphinscheduler/assets/9440510/6dc2b4b4-efa9-47af-8547-9d75398f3488)


Currently I use delayed execution, but it doesn't work either. Our scheduling platform has been running fine for more than half a year, but it started to have this kind of problem recently.

![RTX截图未命名2](https://github.com/apache/dolphinscheduler/assets/9440510/a146d4bf-bbb0-4b84-b6e6-58a642225211)

**Comment by SbloodyS** [comment]
This issue will be fix in #15014.

**Comment by 997759790** [comment]
> This issue will be fix in #15014.
I checked the bug of 15014. If only retryInterval is not used, it will only cause the retry to not take effect. However, our current problem is that it does not take effect occasionally.

**Comment by 997759790** [comment]
> This issue will be fix in #15014.

I checked the bug of 15014. If only retryInterval is not used, it will only cause the retry to not take effect. However, our current problem is that it does not take effect occasionally.

**Comment by aikuyun** [comment]
In version 2.0.5 , kill workflow will clear taskRetryCheckList，so task will not retry , it is fixed in version 2.0.6.

Kill workflow will affect retry tasks in all workflows running on the same master server in version 2.0.5.

you can look this pr in  https://github.com/apache/dolphinscheduler/pull/9678/files.

**Comment by 997759790** [comment]
But we did not kill the task manually
