### ISSUE TITLE
[Bug] [dolphinscheduler master] After the workflow contains a sub-process and performs the "Stop" operation, the workflow instance will always display "Ready to Stop"

### ISSUE THREAD

**Issue by xujie0120** [apache/dolphinscheduler#14938]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened
After stopping a workflow with sub-processes, the workflow status in the workflow instance list always displays "Ready to Stop" and the workflow instance cannot be ended.

Create a workflow with sub-processes.
Submit workflow
Workflow instance list execution "Stop"
The workflow instance cannot be ended and "Ready to Stop" is always displayed.

对一个带子流程的工作流执行停止操作后，工作流流实例列表的工作流状态一直显示“准备停止”，该工作流实例无法结束。
dolphinscheduler 版本：3.1.8
1、创建一个带子流程的工作流。
2、提交工作流
3、工作流实例列表执行“停止”
4、查看工作流实例无法结束，一直显示“准备停止”

### What you expected to happen
Problem description: After stopping a workflow with sub-processes, the workflow status in the workflow instance list always displays "Ready to Stop", and the workflow instance cannot be ended.
Expected results: The workflow instance ends normally with a status of Stopped.

问题描述：对一个带子流程的工作流执行停止操作后，工作流流实例列表的工作流状态一直显示“准备停止”，该工作流实例无法结束。
预期结果：该工作流实例正常结束，并且状态为“停止”。

### How to reproduce
After stopping a workflow with sub-processes, the workflow status in the workflow instance list always displays "Ready to Stop" and the workflow instance cannot be ended.

Create a workflow with sub-processes.
Submit workflow
Workflow instance list execution "Stop"
The workflow instance cannot be ended and "Ready to Stop" is always displayed.

对一个带子流程的工作流执行停止操作后，工作流流实例列表的工作流状态一直显示“准备停止”，该工作流实例无法结束。
1、创建一个带子流程的工作流。
2、提交工作流
3、工作流实例列表执行“停止”
4、查看工作流实例无法结束，一直显示“准备停止”

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please use english to describe your issue.

**Comment by gongzexin** [comment]
> 请用英语描述您的问题。



> Please use english to describe your issue.

Click the "Stop" button of a certain workflow in the workflow list, and the workflow status is always displayed as "Ready Stop"

**Comment by gongzexin** [comment]
> Please use english to describe your issue.

Click the "Stop" button of a certain workflow in the workflow list, and the workflow status is always displayed as "Ready Stop"

**Comment by stephenking30** [comment]
> > Please use english to describe your issue.
> 
> Click the "Stop" button of a certain workflow in the workflow list, and the workflow status is always displayed as "Ready Stop"

hi,bro,Has the problem been solved?

**Comment by qiudonglin** [comment]
3.1.7版本还是有这个问题，请问怎么解决呢

**Comment by charming33333** [comment]
> 3.1.7版本还是有这个问题，请问怎么解决呢

兄弟解决了吗

**Comment by charming33333** [comment]
> > > Please use english to describe your issue.
> > 
> > 
> > Click the "Stop" button of a certain workflow in the workflow list, and the workflow status is always displayed as "Ready Stop"
> 
> hi,bro,Has the problem been solved?

hi,bro,Has the problem been solved? +1
