### ISSUE TITLE
[Improvement][Task SQL] There is no need to send an email when the sql result is empty

### ISSUE THREAD

**Issue by chenshuai1995** [apache/dolphinscheduler#14958]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When the sql result is empty, it still keeps sending the email, and the content of the email is empty. 

The expectation is that if the query result is not empty, it is normal to send an alert email, but if the query result is empty, there is no need to send the email.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liukunyuan** [comment]
It is a good idea! But add  a new monito sql node would be better

**Comment by qingwli** [comment]
I am +0 about this. Some users can use this function to monitor, an empty value is the result at some time. For this function , we can use two ds tasks to achieve this function, It's more flexible
