### ISSUE TITLE
[Improvement][project] projects-management page query interface timeout

### ISSUE THREAD

**Issue by cooldwind** [apache/dolphinscheduler#14959]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

add index:
ALTER TABLE t_ds_process_definition ADD INDEX idx_project_code(project_code),
                                         ADD INDEX idx_version (version);
ALTER TABLE t_ds_process_definition_log ADD INDEX idx_code(code), 
                                        ADD INDEX idx_version(version),
                                        ADD INDEX idx_project_code(project_code);
ALTER TABLE t_ds_process_instance ADD INDEX idx_process_definition_version(process_definition_version), 
                                  ADD INDEX idx_state(state);
                                  
                                  

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cooldwind** [comment]
Hope to adopt.

**Comment by freeradius-xx** [comment]
Thank you, index of t_ds_process_instance helps me!
ALTER TABLE t_ds_process_instance ADD INDEX idx_process_definition_version(process_definition_version),
ADD INDEX idx_state(state);
