### ISSUE TITLE
[Doc][StarRocks] I see the StarRocks commit in repo but I don't see the document on the website

### ISSUE THREAD

**Issue by alberttwong** [apache/dolphinscheduler#14952]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I see https://github.com/apache/dolphinscheduler/pull/13204 and it was accepted but I can't find the page on the website.  https://dolphinscheduler.apache.org/en-us/docs/3.1.8/introduction-to-functions_menu/data-source_menu

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by alberttwong** [comment]
@ruanwenjun FYI

**Comment by SbloodyS** [comment]
It will be released in version 3.2.0-release.
