### ISSUE TITLE
[Feature][project] Guest function

### ISSUE THREAD

**Issue by wangzijian121** [apache/dolphinscheduler#14961]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Application scenarios:
-  【Access Rights Control】 By creating guest users, you can limit their access rights to the system. Guest users may only be able to view certain tasks, processes, or reports in the system but not be able to modify or delete them. This ensures system security and data integrity. For example, new members of the company who are familiar with the business environment need a read-only environment to ensure security.
-  【Demonstration and Learning】 Provide a demonstration environment for third parties.
-  【Temporary access】 When troubleshooting problems, you can assign read-only users for operation and maintenance to collaborate on problem troubleshooting.

### Use case

A function will be implemented: read-only permissions can be given to projects that have been assigned to users.

### Related issues

I don’t know if this idea is feasible, everyone is welcome to discuss it

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
There are currently no plans for that
