### ISSUE TITLE
[Improvement][K8S TASK] get namespace's information until execute

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#14995]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- store ```namespaceId``` when  save process definition
- before run process instance ,according ``` namespaceId ``` get ``` namespace name``` and other information

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi @fuchanghai , I don't get your point, would you like to give some further explanation of this issue?

**Comment by fuchanghai** [comment]
> Hi @fuchanghai , I don't get your point, would you like to give some further explanation of this issue?

hi @Radeity 

Currently, the k8s node stores the namespace name. If you want to modify the name, the process definition associated with the namespace needs to be modified

**Comment by Radeity** [comment]
> > Hi @fuchanghai , I don't get your point, would you like to give some further explanation of this issue?
> 
> hi @Radeity
> 
> Currently, the k8s node stores the namespace name. If you want to modify the name, the process definition associated with the namespace needs to be modified

Oh, you mean namespace in k8s task's parameter. How about directly remove `t_ds_k8s_namespace`? cc @Gallardot

**Comment by Gallardot** [comment]
> Oh, you mean namespace in k8s task's parameter. How about directly remove `t_ds_k8s_namespace`? cc @Gallardot

I think the solution described by @fuchanghai  would be helpful in resolving this issue.

What does `directly remove t_ds_k8s_namespace` means ? @Radeity

**Comment by Radeity** [comment]
> > Oh, you mean namespace in k8s task's parameter. How about directly remove `t_ds_k8s_namespace`? cc @Gallardot
> 
> I think the solution described by @fuchanghai would be helpful in resolving this issue.
> 
> What does `directly remove t_ds_k8s_namespace` means ? @Radeity

I think we don't have to maintain this table and we can remove namespace management, since now we don't have the ability to manage namespace in k8s cluster. Thus, `namespace` is same with `image` in k8s task's parameters. Considering user-friendliness, maybe we can use project-level parameter to define these task parameter.

**Comment by Gallardot** [comment]
> I think we don't have to maintain this table and we can remove namespace management, since now we don't have the ability to manage namespace in k8s cluster. Thus, `namespace` is same with `image` in k8s task's parameters. Considering user-friendliness, maybe we can use project-level parameter to define these task parameter.

But currently, the dolphinscheduler has the authority to manage namespaces, and specific dolphinscheduler users can use the namespace permissions of specific clusters, which is beneficial for both permission management and ease of use.
