### ISSUE TITLE
[Bug] [tranform] Fields out of order after field mapper

### ISSUE THREAD

**Issue by Tomccat3** [apache/dolphinscheduler#15001]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

i have a task source from mysql, sink to maxcompute, with field mapper, i find sink columns in maxcompute is out of order
env {
job.mode = BATCH
}

source {
Jdbc{
password = "***"
driver = "com.mysql.cj.jdbc.Driver"
query = "SELECT id,uid,user_name,job_name,params,created_at,updated_at FROM lakeservice_task"
partition_column = "id"
user = "***"
url = "***"
partition_num = "4"
}
}
transform {
  FieldMapper {
    field_mapper = {
        id = id
        uid = uid
        user_name = user_name
        job_name = job_name
        params = params
        created_at = created_at
        updated_at = updated_at
    }
  }
}
sink {
Maxcompute{
accessId = "***"
endpoint = "***"
accesskey = "***"
project = "dp_ads_app_ecube_sec_sit_dev"
table_name = "lake_service_07"
}
}

### What you expected to happen

![image](https://github.com/apache/dolphinscheduler/assets/29647455/6f2e11ac-3548-446e-959d-e400ada89856)
1. The uid column writes the value of the params column。
2. The updated_at column writes the value of the id column...
All column values are written incorrectly

### How to reproduce

1. create a task with mysql source and maxcompute sink
2. add fieldmapper
3. select records from maxcompute, column value is out of order。

### Version

3.1.x

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tomccat3** [comment]
by the way, i also find bigdecimal cannot be written from mysql to maxcompute,  '\N' is wroten when sink a bigdecimal field from mysql to maxcompute

**Comment by SbloodyS** [comment]
Which task you are using? @Tomccat3

**Comment by Tomccat3** [comment]
> by the way, i also find bigdecimal cannot be written from mysql to maxcompute, '\N' is wroten when sink a bigdecimal field from mysql to maxcompute
it's a seatunnel task

**Comment by Tomccat3** [comment]
> Which task you are using? @Tomccat3

seatunnel

**Comment by SbloodyS** [comment]
> seatunnel

You should open issue in seatunnel project.

**Comment by Tomccat3** [comment]
sry
