### ISSUE TITLE
[Doc][file-manage] content text error

### ISSUE THREAD

**Issue by bysking** [apache/dolphinscheduler#15026]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

<img width="1438" alt="image" src="https://github.com/apache/dolphinscheduler/assets/29291456/d0b5585d-4ac0-4197-841a-c9260d45214a">

### Documentation Links

https://dolphinscheduler.apache.org/zh-cn/docs/3.1.8/guide/resource/file-manage

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
i want take this task, can you assign to me, thanks.
