### ISSUE TITLE
Dolphin Scheduler - 3.1.8 in RedHat Linux 9.0 X86_64 - Not opening Login page from web browser

### ISSUE THREAD

**Issue by rkkrishnan** [apache/dolphinscheduler#15021]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Dolphin Scheduler - 3.1.8 version
RedHat Linux ver - 9.0 (x86_64 architecture)
After installing JDK, Zookeeper, mysql, Dolphin scheduler in Linux server and successfully able to start up dolphin services(API, Master, Worker, Alert).
Also able to check api service is running by issuing the curl command like below:
curl -Lv http://APIServiceIP:12345/dolphinscheduler/ui

But when trying to access the service from web-browser (Chrome or Edge or IE) in the Jump server or external desktop not able to get the webpage and throwing error as 'can't reach this page' & no logs also got updated for api service.
It seems web server(Jetty web server by Dolphin Scheduler) is not able to reach/ping from other linux boxes as well.
There is no firewall rule or proxy setup for the Dolphin scheduler server.

http://localhost:12345/dolphinscheduler/ui - Verification point is getting failure. How to login and is there any setup/configuration changes are required in the Dolpin scheduler config files or Linux server?

http://APIServiceIP:12345/dolphinscheduler/ui - used this link

![image](https://github.com/apache/dolphinscheduler/assets/20638293/2105c7aa-b4e0-4333-94da-98971a9cde2c)

### What you expected to happen

But when trying to access the service from web-browser (Chrome or Edge or IE) in the Jump server or external desktop not able to get the webpage and throwing error as 'can't reach this page' & no logs also got updated for api service.
It seems web server(Jetty web server by Dolphin Scheduler) is not able to reach/ping from other linux boxes as well.
There is no firewall rule or proxy setup for the Dolphin scheduler server.

http://localhost:12345/dolphinscheduler/ui - Verification point is getting failure. How to login and is there any setup/configuration changes are required in the Dolpin scheduler config files or Linux server?

http://APIServiceIP:12345/dolphinscheduler/ui - used this link

### How to reproduce

Installation steps as mentioned has been followed and successfully able to start up dolphin scheduler service(s) as well:

https://dolphinscheduler.apache.org/en-us/docs/3.1.8/guide/installation/pseudo-cluster

![image](https://github.com/apache/dolphinscheduler/assets/20638293/28f6cded-6baa-47ae-8313-9e9797e8acc6)

### Anything else

Every time accessing dolphin scheduler link from web browser:

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Could you please provide more logs of api-server? @rkkrishnan

**Comment by rkkrishnan** [comment]
Hi Team,

Kindly find the attached API log file for your reference.

Thanks & Regards,
RK.
[api-server-LSVCHN-JBSAP01_out.txt](https://github.com/apache/dolphinscheduler/files/12916878/api-server-LSVCHN-JBSAP01_out.txt)
[dolphinscheduler-api.log](https://github.com/apache/dolphinscheduler/files/12916881/dolphinscheduler-api.log)

**Comment by ruanwenjun** [comment]
It seems the api doesn't start finish.

**Comment by ruanwenjun** [comment]
it seems the api server has been start successfully, could you please double check your ip, port and the ui directory under api-server is correct.

**Comment by rkkrishnan** [comment]
Thanks for your reply. Already we have checked the firewall and port were no rules setup. Also we have checked with curl command in the dolphin server were it gives http success code 200. Is there any other way to check?Also pseudo cluster deployment steps have been followed and still wondering?
Thanks & Regards,RK
Sent from Yahoo Mail on Android 
 
  On Mon, 23 Oct 2023 at 9:29 am, Wenjun ***@***.***> wrote:   


it seems the api server has been start successfully, could you please double check your ip, port and is there any firewall.

**Comment by rkkrishnan** [comment]
Is there any input which I can try out - Login UI page to appear in browser?

How to use the local browser in Red Linux server to open the Login UI page?

Kindly provide the details?

**Comment by ruanwenjun** [comment]
@rkkrishnan Does this problem has been solved? The issue has been closed by GitHub-bot, I reopen this.

**Comment by rkkrishnan** [comment]
Hi Team - This issue was related to Linux 9 OS has default firewall for the server and so need to whatever ports needs to be accessed. In Linux 7 version does not have default firewall for the server ie by default ports running particualar service can be accessed by external systems unless otherwise if we set the firewall. Thanks a lot for your support & help offered.

**Comment by rkkrishnan** [comment]
Hi Team - This issue was related to Linux 9 OS has default firewall for the server and so need to whatever ports needs to be accessed. In Linux 7 version does not have default firewall for the server ie by default ports running particualar service can be accessed by external systems unless otherwise if we set the firewall. Thanks a lot for your support & help offered.
