### ISSUE TITLE
[Bug] [Master]  Dependent task result detection has some problems

### ISSUE THREAD

**Issue by shilei-ly** [apache/dolphinscheduler#15038]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

- two dag：a -> b -> c，dependent _1 -> d -> e
- Retry after failure is configured for task b. 
- dependent _1 is Dependent task and depends on task b.
- When task b fails but the maximum number of retries is not reached, dependent _1 task fails. 

中文：
- 两个工作流：a -> b -> c，dependent _1 -> d -> e
- 其中任务b配置了失败重试，比如最大重试次数为3，重试间隔为3min
- 任务dependent _1是一个Dependent类型的任务，依赖任务b，依赖定义如下图
- 结果：当任务b失败一次后，就会触发dependent _1任务失败。

![image](https://github.com/apache/dolphinscheduler/assets/97011595/2bc793ce-c850-4eba-9695-ded0f51ef9f1)

### What you expected to happen

In my opinion, after failed retry is configured for task b, dependent tasks need to wait for the retry to complete before their execution results can be calculated

中文：
我认为，如果任务b配置了失败重试，依赖任务b的Dependent任务需要等待其**执行成功或者执行失败且达到最大重试次数**后才能计算Dependent任务的依赖结果，而不是在任务b失败一次后就触发dependent _1任务失败，因为任务b处于失败重试阶段，此任务并未结束。

### How to reproduce

I think that when calculating the dependency result of a dependent task, it is necessary to additionally determine whether the dependent task has a failed retry stage to prevent the dependent task from failing due to a single failure of the dependent task.

中文：
我认为，在计算Dependent类型任务的依赖结果时，需要额外判断被依赖任务是否处于失败重试阶段，防止因为被依赖任务单次失败造成Dependent类型任务失败。

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by whmnoe4j** [comment]
大佬太厉害了，我感觉dependent模块确实还有待完善

**Comment by SbloodyS** [comment]
Fixed.
