### ISSUE TITLE
[Bug] [Module Name] Bug title 

### ISSUE THREAD

**Issue by PofuLiangbai** [apache/dolphinscheduler#15030]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

我使用的版本是3.1.7，我发现我对任务进行编辑操作后，任务流中的任务数据版本与任务中的任务数据版本并不一致

### What you expected to happen

任务流中任务定义数据与任务模块任务定义数据不一致

### How to reproduce

创建任务流，然后创建任务，在任务定义模块找到该任务，对这个任务进行编辑，编辑完成后，会发现任务定义模块中任务数据进行了更新，但是，对应任务流中的这个任务数据并没有变化，还是停留在之前的版本

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please use english to describe and use the correct title.
