### ISSUE TITLE
[Bug] [dolphinscheduler-datasource] there is no kyuubi datasource

### ISSUE THREAD

**Issue by wxd5146** [apache/dolphinscheduler#15040]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when I deploy ds3.2 ,I can not found kyuubi datasource

### What you expected to happen

there is a kyuubi datasource

### How to reproduce

add kyuubi datasource

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This has been fixed #15051.

**Comment by wxd5146** [comment]
i change the code,but the sql task do not hive kyuubi
![image](https://github.com/apache/dolphinscheduler/assets/39934213/3b26db2e-340a-492d-93ad-83d5d8d00264)
![image](https://github.com/apache/dolphinscheduler/assets/39934213/89041f64-9f13-49a1-baac-138d754b09f3)

**Comment by pan3793** [comment]
Seems resolved by https://github.com/apache/dolphinscheduler/pull/15140, which is scheduled for v3.2.1
