### ISSUE TITLE
When accessing the homepage on port 12345, a blank page is displayed

### ISSUE THREAD

**Issue by xuweiyuaaaa** [apache/dolphinscheduler#15042]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Deployment was successful, and there were no errors in the backend logs. When accessing the homepage, I can see requests to the page's JavaScript and other assets in the browser's console. However, the interface isn't displaying anything

### What you expected to happen

![cf80a3893b66c6df96277300583296f](https://github.com/apache/dolphinscheduler/assets/148331297/6c7fec7f-5398-4e89-88ec-7ca39fddd4d2)
![f040c6e248f2a81680540c75aaddc68](https://github.com/apache/dolphinscheduler/assets/148331297/673d20ff-4bfe-4c35-8d42-ccc5b5ea69b3)
![微信图片_20231018174429](https://github.com/apache/dolphinscheduler/assets/148331297/3b1df8b7-7229-4490-935f-8e7da26cf45d)
![微信图片_20231018174419](https://github.com/apache/dolphinscheduler/assets/148331297/f0a32d3b-af0f-4688-825c-23a71f3316e6)
![微信图片_20231018175140](https://github.com/apache/dolphinscheduler/assets/148331297/aed5578d-e3a7-4766-8c84-2df54ae01578)

I'm not sure what went wrong in this case

### How to reproduce

The problem arises right after a successful deployment

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xuweiyuaaaa** [comment]
it must be centos7

**Comment by zhongjiajie** [comment]
which version do you use?
