### ISSUE TITLE
[Bug] [API] sql default separator is ;\n , but save sql content to ds database, it display ;\r\n

### ISSUE THREAD

**Issue by dufeng1010** [apache/dolphinscheduler#15048]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I create sql task in 3.2.0 version. write two sql command in one sql task. use ;\n to separate it. but it execute fail.
i view database in ds. it save ;\r\n, not ;\n. cause not correctly separate it.

我安装了一个3.2.0版本的dolphinscheduler，创建了一个Sql任务，任务里面编写了两个SQL，然后执行执行失败。

### What you expected to happen

because ;\n is default sql separator, write more sql command in one sql task, it should separate it correctly.

因为3.2.0版本的dophinscheduler中sql任务的默认分隔符是;\n，正常来说应该能够正常执行。

### How to reproduce

1. create a sql task.
2. write two sql command in created sql task. for example
```
select current_date();
select current_date()
```
3. execute online
4. start execute

1. 创建一个Sql任务
2. 在创建的Sql任务里面添加两个sql命令，例如
```
select current_date();
select current_date();
```
3. 上线工作流
4. 执行工作流

### Anything else

跟踪代码发现，存储到数据库中的sql分隔符是;\r\n,导致代码无法正常分割多个SQL，最终sql任务执行失败。

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
This might caused by the browser environment? Are you use windows? `\r\n` is used in windows.

**Comment by dufeng1010** [comment]
> This might caused by the browser environment? Are you use windows? `\r\n` is used in windows.

yes, i use brower in windows. @ruanwenjun

**Comment by ruanwenjun** [comment]
> > This might caused by the browser environment? Are you use windows? `\r\n` is used in windows.
> 
> yes, i use brower in windows. @ruanwenjun

I submit https://github.com/apache/dolphinscheduler/pull/15062 to fix this.
