### ISSUE TITLE
[Bug] [upgrade ] upgrade 3.2.0, IP ERROR

### ISSUE THREAD

**Issue by yyccww123** [apache/dolphinscheduler#15059]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

upgrade 3.2.0, workers does not work. I set eth0's ip in install_env.sh , but get eth1's ip and monitor page dispay  eth1's ip.

### What you expected to happen

use eth0's ip

### How to reproduce

upgrade 3.2.0 and Have multiple network cards.

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Could you please provide your env config?

**Comment by zhangzizhong2020** [comment]
实际上没有任何配置文件是用来配置worker与master节点的，在env文件中配置的host只是scp资源时才用到的，同时需要注意zk注册目录的IP与zookeeper配置的IP没有关系。官网文档并没有给出配置的详情（文档较不友好），只有相关问题（FAQs）中提及《Q：zk 中注册的 master 信息 ip 地址是 127.0.0.1，而不是配置的域名所对应或者解析的 ip 地址，可能导致不能查看任务日志》
回答者回复：ds是根据hostname去/etc/hosts中找对应主机名称的host

刚开始我也这么认为，于是我将hosts中IP的域名映射改成主机名，重启之后依旧没有作用
于是，我想应该是跟配置文件和系统配置是无关的，很有可能是代码层面进行限制的

无奈下，download了DS的源码，通过排查发现，worker与master等组件节点都调用common模块下NetUtils类的getHost(args)有参静态方法，下游调用getHost()方法，最后通过JavaAPI，获取网卡的IP，并存入集合，最终get(0)取第一个IP作为使用IP

因此，DS目前而言是无法手动通过配置文件去更改节点Host的，只能通过修改上述类方法，打包为dolphinscheduler-common-3.2.0.jar替换掉所有节点lib文件夹下的同名文件，来达到指定IP的目的。（当然也可以进行更深入的二次开发，支持读取外部文件来指定IP）

注：不要修改worker，master或其它模块（会很麻烦），只需要修改common包下的NetUtils.getHost()方法即可作用全局。

**Comment by yyccww123** [comment]
3.1.8版本都没问题，3.2.0版本改过NetUtils.getHost()方法？环境是没变化过的，本来我想是不是可以改hosts指定下IP，那估计不行啊。env文件中配置的host只是scp资源时才用可以理解，但还指定master和worker，这也不行那就理解不了了。

**Comment by zhangzizhong2020** [comment]
实际上代码底层自动获取的服务器内网进行的通信，假如你的不同节点的内网互相ping不通，那么由NetUtils.getHost()方法获取到的本机内网IP是相互通信不了的，如果想要进行通信，只能指定公网IP，所以只能更改源代码，把NetUtils.getHost()自动获取本机内网的机制换成从外部读取IP

**Comment by niyanchun** [comment]
这个问题其实在一些场景下（比如机器上面部署了Docker）还挺难处理的，从代码层面解决也不是什么难事，好奇官方为什么不解决一下
