### ISSUE TITLE
[Improvement][K8S] Remove overload protection when deploying on k8s

### ISSUE THREAD

**Issue by Gallardot** [apache/dolphinscheduler#15066]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

During the discussion with @ruanwenjun on WeChat, we have come to the following conclusion: when deploying dolphinscheduler on k8s, the overload protection feature should be removed.

The reasons are as follows:
1.  The judgment of obtaining overload is not very accurate, whether it is deployed on k8s or on the host.
2.  When deployed on k8s, if we want to obtain the CPU usage or remaining memory of the container, there will be some ambiguity in the calculation.  Should we use request or limit?  Workers also execute scripts such as bash and python, should these be considered in the calculation?
3.  K8S itself has resource limitation mechanisms, as well as KEDA, HPA and other capabilities, so this feature is not necessary.
4.  To implement overload protection, controlling the number of workflows or tasks may be more appropriate.

WDYT? @EricGao888 @SbloodyS @Radeity @qingwli 

We also found a few related issues:
#15049 #14968

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi @Gallardot 

Good catch, the calculation of memory and cpu usage are all wrong in PR #14968. However, I think we should correct this calculation if possible, cuz we have to show correct metrics in monitor page. Maybe use **LIMIT** and consider all processes running on the worker/master pod sounds good to me.

> K8S itself has resource limitation mechanisms, as well as KEDA, HPA and other capabilities, so this feature is not necessary.

Agree with you that we can fully utilize these capabilities when deployed in K8S, but we have to enable KEDA/HPA by default, otherwise, we have to use overload protection strategy with correct metrics to avoid OOM.

**Comment by hdygxsj** [comment]
Any progress？ @Radeity

**Comment by Radeity** [comment]
> Any progress？ @Radeity

Seems like no one works on it currently, do you have any idea about it?

**Comment by qingwli** [comment]
I agree when deploying dolphinscheduler on k8s, the overload protection feature should be removed.

K8s also have limit on namespace, we can use defalut resoure for all service in ds.
https://github.com/apache/dolphinscheduler/blob/e5a512803ec6f8728fe05f4a5433231ab1d13c7e/deploy/kubernetes/dolphinscheduler/values.yaml#L711-L718

**Comment by hdygxsj** [comment]
> > Any progress？ @Radeity
> 
> Seems like no one works on it currently, do you have any idea about it?

Our company is currently running on version 3.2.0, it resulted in the inability to schedule workflow normally and our implemented solution is modifying the source code to remove the overload protection feature, as well as utilizing the hpa.

**Comment by Gallardot** [comment]
Close this issue, because #15439 has been merged, providing a switch for enabling or disabling overload protection. Thanks to @ruanwenjun .
