### ISSUE TITLE
When a non-admin account uploads files in the resource center, the workflow definition Spark type task main package cannot be referenced.

### ISSUE THREAD

**Issue by gitrenliping** [apache/dolphinscheduler#15072]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When a non-admin account uploads files in the resource center, the workflow definition Spark type task main package cannot be referenced.
And no records are inserted into the metadata table, and the api-server does not report an error.

### What you expected to happen

The upload resource interface is abnormal, resulting in no records being inserted into the metadata.

### How to reproduce

Upload files and create spark type tasks

### Anything else

1

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

-------------

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

非admin账号在资源中心上传文件，工作流定义Spark类型任务主程序包无法引用
且元数据表中没有插入记录，api-server也没有报错

### What you expected to happen

上传资源接口异常，导致没有在元数据中插入记录

### How to reproduce

上传文件，并创建spark类型任务

### Anything else

1

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
In 3.2.x, we don't insert any new record when uploading resource into resource center, which meta data do you mean?

**Comment by jfifth** [comment]
I have a similar issue to the current Issue in 3.2.x.
In a same Spark Task, folders can be displayed in the "Resources dropdown list". but folders cannot be displayed in the "main package", "main package" list just displayed files in the root directory

--------------------------------------------------------------
在3.2.0中我有一个和当前Issue相似的问题，在同一个Spark Task中，Resources下拉列表中可以显示文件夹，但main package中不能显示文件夹，只能显示根目录中的文件。

**Comment by gitrenliping** [comment]
> In 3.2.x, we don't insert any new record when uploading resource into resource center, which meta data do you mean?

In 3.2. x, after uploading the file in the resource center, the metadata table t_ Ds_ Resources did not insert any records

**Comment by gitrenliping** [comment]
> ## I have a similar issue to the current Issue in 3.2.x.
> In a same Spark Task, folders can be displayed in the "Resources dropdown list". but folders cannot be displayed in the "main package", "main package" list just displayed files in the root directory
> 在3.2.0中我有一个和当前Issue相似的问题，在同一个Spark Task中，Resources下拉列表中可以显示文件夹，但main package中不能显示文件夹，只能显示根目录中的文件。

看下你的元数据表t_ds_resources中有记录吗

**Comment by jfifth** [comment]
> > ## I have a similar issue to the current Issue in 3.2.x.
> > In a same Spark Task, folders can be displayed in the "Resources dropdown list". but folders cannot be displayed in the "main package", "main package" list just displayed files in the root directory
> > 在3.2.0中我有一个和当前Issue相似的问题，在同一个Spark Task中，Resources下拉列表中可以显示文件夹，但main package中不能显示文件夹，只能显示根目录中的文件。
> 
> 看下你的元数据表t_ds_resources中有记录吗

t_ds_resources表中是空的，没有任何记录

**Comment by Radeity** [comment]
Hi @jfifth @gitrenliping , table `t_ds_resources` is deprecated in 3.2.x, we do not maintain these metadata in database.

**Comment by Radeity** [comment]
> ## I have a similar issue to the current Issue in 3.2.x.
> In a same Spark Task, folders can be displayed in the "Resources dropdown list". but folders cannot be displayed in the "main package", "main package" list just displayed files in the root directory
> 在3.2.0中我有一个和当前Issue相似的问题，在同一个Spark Task中，Resources下拉列表中可以显示文件夹，但main package中不能显示文件夹，只能显示根目录中的文件。

Can you provide some screenshot about it?

**Comment by gitrenliping** [comment]
@Radeity
![spark任务](https://github.com/apache/dolphinscheduler/assets/148838028/53f9d501-c7d9-4d76-9a8d-51ea73c84514)
![资源中心](https://github.com/apache/dolphinscheduler/assets/148838028/859ac50a-7453-4277-9102-7c8dc2e58f65)

**Comment by gitrenliping** [comment]
@Radeity 
Can the main program package of Spark task only reference jar packages in the root directory, and cannot reference jar packages in folders? The figure is as follows:
![1698301760345](https://github.com/apache/dolphinscheduler/assets/148838028/c49e5851-670b-4756-be2b-cccf6e70889d)
![1698301596422](https://github.com/apache/dolphinscheduler/assets/148838028/6185fa7f-838d-432e-8e4e-45f3f2050cda)

**Comment by Radeity** [comment]
I've tested branch 3.2.0-release, and do not reproduce this bug, here's my resource list.

<img width="516" alt="image" src="https://github.com/apache/dolphinscheduler/assets/45198818/19ff67ba-42de-43e9-ab29-3af9ae6448df">

**Comment by jfifth** [comment]
> > ## I have a similar issue to the current Issue in 3.2.x.
> > In a same Spark Task, folders can be displayed in the "Resources dropdown list". but folders cannot be displayed in the "main package", "main package" list just displayed files in the root directory
> > 在3.2.0中我有一个和当前Issue相似的问题，在同一个Spark Task中，Resources下拉列表中可以显示文件夹，但main package中不能显示文件夹，只能显示根目录中的文件。
> 
> Can you provide some screenshot about it?

@Radeity 

### Resources：

![resources](https://github.com/apache/dolphinscheduler/assets/3906745/30f800ae-b223-4a0d-b390-0487f0f6c314)

### Main Package in Spark Task：

![Main Package](https://github.com/apache/dolphinscheduler/assets/3906745/2e13cf76-c339-45ff-8409-154a83dc7494)

### Resources in same Spark Task as “Main Package”

![task_resources](https://github.com/apache/dolphinscheduler/assets/3906745/b4f65f3b-3436-4970-bc5c-4f519a35b30c)

**Comment by gitrenliping** [comment]
> I've tested branch 3.2.0-release, and do not reproduce this bug, here's my resource list.
> 
> <img alt="image" width="516" src="https://user-images.githubusercontent.com/45198818/278251736-19ff67ba-42de-43e9-ab29-3af9ae6448df.png">


@Radeity The administrator does not have this problem. You can try creating a regular user

![1698647547494](https://github.com/apache/dolphinscheduler/assets/148838028/cfca5398-ed80-43ee-a32e-934ed54f9ef2)
![1698648048948](https://github.com/apache/dolphinscheduler/assets/148838028/ef957450-f1e3-425a-b4e7-d5d59a88fab1)
![1698648360304](https://github.com/apache/dolphinscheduler/assets/148838028/dbac05e0-9c43-4b71-9e59-b163d7056fda)

**Comment by Radeity** [comment]
> @Radeity The administrator does not have this problem. You can try creating a regular user
> 
> ![1698647547494](https://user-images.githubusercontent.com/148838028/278961041-cfca5398-ed80-43ee-a32e-934ed54f9ef2.jpg) ![1698648048948](https://user-images.githubusercontent.com/148838028/278961076-ef957450-f1e3-425a-b4e7-d5d59a88fab1.jpg) ![1698648360304](https://user-images.githubusercontent.com/148838028/278961129-dbac05e0-9c43-4b71-9e59-b163d7056fda.jpg)

According to your screenshot, it seems like you can select the main jar uploaded by user `dolphinscheduler`?

**Comment by gitrenliping** [comment]
> > @Radeity The administrator does not have this problem. You can try creating a regular user
> > ![1698647547494](https://user-images.githubusercontent.com/148838028/278961041-cfca5398-ed80-43ee-a32e-934ed54f9ef2.jpg) ![1698648048948](https://user-images.githubusercontent.com/148838028/278961076-ef957450-f1e3-425a-b4e7-d5d59a88fab1.jpg) ![1698648360304](https://user-images.githubusercontent.com/148838028/278961129-dbac05e0-9c43-4b71-9e59-b163d7056fda.jpg)
> 
> According to your screenshot, it seems like you can select the main jar uploaded by user `dolphinscheduler`?

yes

**Comment by Radeity** [comment]
> yes

So what's your problem?

**Comment by gitrenliping** [comment]
> dolphinscheduler

> > yes
> 
> So what's your problem?

‘dolphinscheduler’ users create spark tasks, and the main program package can only reference files in the root directory, not files in the folder

**Comment by Radeity** [comment]
> ‘dolphinscheduler’ users create spark tasks, and the main program package can only reference files in the root directory, not files in the folder

Thanks, I'll fix it.
