### ISSUE TITLE
[Bug] execute sql error: datasource plugin 'doris' is not found

### ISSUE THREAD

**Issue by echobigdata** [apache/dolphinscheduler#15075]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

dolphinscheduler-3.2.0
使用dolphinscheduler调度doris，运行报错，提示没有找到doris数据源
![image](https://github.com/apache/dolphinscheduler/assets/97231854/ebcbcbfc-0c7e-4732-9be0-357e19580421)
![image](https://github.com/apache/dolphinscheduler/assets/97231854/cf86372f-8658-4ef4-8115-898419c8d647)

### What you expected to happen

[INFO] 2023-10-25 15:56:18.438 +0800 - can't find udf function resource
[ERROR] 2023-10-25 15:56:18.439 +0800 - execute sql error: datasource plugin 'doris' is not found
[ERROR] 2023-10-25 15:56:18.439 +0800 - sql task error
java.lang.RuntimeException: datasource plugin 'doris' is not found

### How to reproduce

![image](https://github.com/apache/dolphinscheduler/assets/97231854/dd13d1dc-4483-437f-8b88-d821124ebb12)
使用sql组件执行
insert into xf_ods_so_somain_copy1 select * from xf_ods_so_somain;

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zqyangchn** [comment]
Is this problem not a bug? How to solve it?

**Comment by xinxingi** [comment]
This is a code problem, I will submit the fix code later

**Comment by mezhangremoterepository** [comment]
It works without fixing it: Change your Doris data source to MYSQL, your IP, port write your Doris configuration, so you can use mysql jdbc connection Doris

**Comment by zqyangchn** [comment]
This is how it is used now, but the doris data source is not easy to use.
