### ISSUE TITLE
[Bug] [dolphinscheduler-worker] Flink stream task cannot be stopped and savepointed after completion

### ISSUE THREAD

**Issue by xiaohui2009** [apache/dolphinscheduler#15089]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

flink stream任务执行完成后无法停止和savepoint

### What you expected to happen

flink stream任务执行完成可以停止和savepoint

### How to reproduce

新建flink stream 任务启动，然后执行停止操作

主要原因是WorkerTaskExecuteRunnable执行任务后，从TaskExecutionContextCacheManager清理了taskInstanceId，导致停止任务执行时无法从TaskExecutionContextCacheManager通过taskInstanceId获取任务信息

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by maikouliujian** [comment]
I also encountered this problem. Moreover,is the command of flink stream task cancel and savepoint  wrong？
In dolphinscheduler, flink savepoint/cancel  appid, it should be flink savepoint/cancel  jobid？
