### ISSUE TITLE
[Improvement][DataQualityTask] Find DataQualityTask jar in class path.

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#15086]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We use a property to set the data quality tasks jar.
```
data-quality.jar.name=dolphinscheduler-data-quality-dev-SNAPSHOT.jar
```
This can be removed, we can directly find the data quality by prefix at class path.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhengkezhou1** [comment]
hi, @ruanwenjun. I noticed that the following configuration file contains this jar package.
<img width="1060" alt="sc" src="https://github.com/apache/dolphinscheduler/assets/36791902/faca6245-b12a-4a2e-bea3-bc41f3195398">
Does this task require me to delete the following code in the configuration file?

```properties
# data quality option
data-quality.jar.name=dolphinscheduler-data-quality-dev-SNAPSHOT.jar
```

**Comment by ruanwenjun** [comment]
> hi, @ruanwenjun. I noticed that the following configuration file contains this jar package. <img alt="sc" width="1060" src="https://private-user-images.githubusercontent.com/36791902/286271324-faca6245-b12a-4a2e-bea3-bc41f3195398.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNTU2NzcsIm5iZiI6MTcwMTI1NTM3NywicGF0aCI6Ii8zNjc5MTkwMi8yODYyNzEzMjQtZmFjYTYyNDUtYjEyYS00YTJlLWJlYTMtYmM0MWYzMTk1Mzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEwNTYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMmMyMDJjMTU2NWViN2FhOWM1NmIyMWUzMGE2YmE0YTMwODYzNzU0YzhjZTJhMmM5ZDc0MWVjODI5NGEzZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z-f9FbD0AUjl9h6OrFcbP2gmhwhSZ5R7dd_uefSZrOg"> Does this task require me to delete the following code in the configuration file?
> 
> ```ini
> # data quality option
> data-quality.jar.name=dolphinscheduler-data-quality-dev-SNAPSHOT.jar
> ```

Yes, but you need to make the application can find this jar first.
