### ISSUE TITLE
[Improvement][easyscheduler] Remove easy scheduler code

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#15081]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Right now, there exist some code related to easy scheduler. e.g. in tools/initialize sql, it's better to remove this kind of code.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
I want take this task

**Comment by ruanwenjun** [comment]
> I want take this task

Assigned to you.

**Comment by liunaijie** [comment]
now i am working on this, but i can't find the file you mentioned like  `tools/initialize sql`.
And when i search the project with `easyscheduler` word, 
part of them are in `upgrade/1.2.0_schema` folder, that's looks like the upgrade sql when user upgrade version.  
others are in the md file. some picture link like `https://analysys.github.io/easyscheduler_docs_cn/images/decentralization.png`.

So I'm not sure if I still need to do this task.

**Comment by ruanwenjun** [comment]
> now i am working on this, but i can't find the file you mentioned like `tools/initialize sql`. And when i search the project with `easyscheduler` word, part of them are in `upgrade/1.2.0_schema` folder, that's looks like the upgrade sql when user upgrade version. others are in the md file. some picture link like `https://analysys.github.io/easyscheduler_docs_cn/images/decentralization.png`.
> 
> So I'm not sure if I still need to do this task.

Some code also exist in https://github.com/apache/dolphinscheduler/blob/9c8d1dc6d82f8c3f6db57c1a8a2f1ff6d2b7e00d/dolphinscheduler-tools/src/main/java/org/apache/dolphinscheduler/tools/datasource/DolphinSchedulerManager.java#L91
