### ISSUE TITLE
[Improvement][UserManagement] Allow admin to modify or reset the password of other users

### ISSUE THREAD

**Issue by NJCrazyRen** [apache/dolphinscheduler#15087]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Imagine a situation where a user forgets their login password, how will they log in?
So I think it's necessary to allow administrators to modify or reset the passwords of other users.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Sound good to me.

**Comment by zhengkezhou1** [comment]
@ruanwenjun  hi, I'd like to try that

**Comment by xinxingi** [comment]
https://github.com/xinxingi/MyPrivateWarehouse/blob/main/PictureBed/main/507CF3D4-B87D-4BD3-80CA-DC9178AC78B0.png

**Comment by xinxingi** [comment]
I verified that this feature has been developed and pushed to the development branch

**Comment by shamonhashmi148** [comment]
Is this issue resolved ? 
If not could you please assign me with this issue.

**Comment by Kinsonx** [comment]
Is this issue resolved now ?

**Comment by sdhzwc** [comment]
![image](https://github.com/user-attachments/assets/8fe2ff36-d8df-48f1-9ee5-3ee270a31968)
@ruanwenjun I see that dev has completed it

**Comment by ruanwenjun** [comment]
@sdhzwc Thanks for verify this, I will close this issue.
