### ISSUE TITLE
[Bug] [server] suddenly shutdown of server caused by zookeeper being closed

### ISSUE THREAD

**Issue by YutongGong** [apache/dolphinscheduler#15090]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I start the standalone-server normally. But for a while, it shutdown. The log says that it receives spring context close event and close the zookeeper server. How to solve it?
![企业微信截图_16983775526866](https://github.com/apache/dolphinscheduler/assets/128340632/c0b40c0e-d574-41c0-9dba-86eafc97a3ec)

### What you expected to happen

Maybe it is caused by the zookeeper, but I didn't changed the settings of zookeeper.

### How to reproduce

Just start it...

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Does this happen in staring stage or after a while? In standalone mode, we use a memory zk, this might be affect by the process load.

**Comment by jfifth** [comment]
Check out issue #2601, it looks similar to your problem:

> zookeeper session timeout only 4 seconds, it's too short. so change the config item in zookeeper.properties:
> 
> zookeeper.session.timeout=60000
> zookeeper.connection.timeout=30000

**Comment by YutongGong** [comment]
> Does this happen in staring stage or after a while? In standalone mode, we use a memory zk, this might be affect by the process load.

I think it happens after a while, sometimes it happens after nearly half an hour.

**Comment by YutongGong** [comment]
> Check out issue #2601, it looks similar to your problem:
> 
> > zookeeper session timeout only 4 seconds, it's too short. so change the config item in zookeeper.properties:
> > zookeeper.session.timeout=60000
> > zookeeper.connection.timeout=30000

I'm sorry but I have modified it to try, and it didn't work. It seems that the server will be alive longer after the modify but still goes to be dead.
