### ISSUE TITLE
[Bug] [dolphinscheduler-datasource-hive] Hive HiveAdHocDataSourceClient not support hadoop Kerberos env.

### ISSUE THREAD

**Issue by userkdg** [apache/dolphinscheduler#15109]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![1698909570394](https://github.com/apache/dolphinscheduler/assets/21057449/36dd2f7d-e629-456f-8c26-677af4290ab3)
![image](https://github.com/apache/dolphinscheduler/assets/21057449/9c1285c0-7a4a-4e96-9317-0608ada98219)

#14631 SqlTask 获取数据源连接已默认改为getAdHocConnection但是Hive的HiveAdHocDataSourceClient应该是开发者遗漏了HivePooledDataSourceClient（历史类HiveDataSourceClient）中的Kerberos认证相关代码。

### What you expected to happen

新增的`HiveAdHocDataSourceClient` 支持Kerberos相关认证。

### How to reproduce

代码分支3.2.0-release的`dolphinscheduler-datasource-hive` 模块

### Anything else

无。

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please use hive task plugin instead of sql task plugin connecting to hive.
