### ISSUE TITLE
[Bug] [Alter] alter group is selected by default

### ISSUE THREAD

**Issue by xiaofan2022** [apache/dolphinscheduler#15107]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In the workflow, notification strategies are configured, but alarm notifications won't be sent if the alert group is not set up

### What you expected to happen

The workflow is in an active state with configured alarm notification policies. If no alarm group is set, the default group will be used.

### How to reproduce

![ds](https://github.com/apache/dolphinscheduler/assets/41982310/6ee51c71-6152-4e76-b372-8bce484f08a2)

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
hi @xiaofan2022 can you help to fix it ? you can refer this PR #12200   cc @Radeity can you add ```good first issue```

**Comment by fuchanghai** [comment]
hi @xiaofan2022   i think #12200 has fix this issue ,and i had test in my local  cc @EricGao888 @Radeity @Amy0104

**Comment by EricGao888** [comment]
> hi @xiaofan2022 i think #12200 has fix this issue ,and i had test in my local cc @EricGao888 @Radeity @Amy0104

@xiaofan2022 Looks like this one has been fixed in 3.2.0. Could u plz cp this fix or upgrade to 3.2.0?

**Comment by xiaofan2022** [comment]
How can I modify an existing task? Do you want to change the back end too?
