### ISSUE TITLE
The build module of pom.xml file seems too complicated

### ISSUE THREAD

**Issue by polluxll** [apache/dolphinscheduler#15117]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The build module of pom.xml file seems too complicated,as an newcomer,there was too many errors when I imported project into my IDEA.
such as "<excludes>com/github/dreamhead/moco/*</excludes>",“maven.multiModuleProjectDirectory”  "jacoco-maven-plugin error"
I just want build a jar package which could runing.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xinxingi** [comment]
dolphinscheduler is a very good project for novices to get started with the front and back ends. When you solve these errors bit by bit, you will be successful. Good luck

**Comment by polluxll** [comment]
> dolphinscheduler is a very good project for novices to get started with the front and back ends. When you solve these errors bit by bit, you will be successful. Good luck

I don't want jenkins plugin,I don't want jacoco report,I don't want docker-build,but they were all wirtten in build module of pom.xml file .Maybe a simple pom.xml file for newcomer is needed.
