### ISSUE TITLE
[Improvement][DataSource] Support multi-host jdbc url

### ISSUE THREAD

**Issue by NJCrazyRen** [apache/dolphinscheduler#15119]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Some distributed databases such as MPP or OLAP may have multi-host jdbc connection urls like "jdbc: xxx://ip1:port1,ip2:port2,ip3:port3/db?params". Therefore, it is recommended to improve the data source configuration to support such multiple hosts jdbc url.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xinxingi** [comment]
The multi-host URL configuration of different data sources may be different. Which types of data sources do you expect to implement this feature? Currently, the doris data source supports the use of multiple IP methods to link to the database to achieve functions similar to automatic load balancing.


![](https://p.sda1.dev/13/e1e5db3cf5856b59aa9b80a9db744134/961E3BAA-B274-4D09-8A28-AB80149D7BFF.png)

**Comment by NJCrazyRen** [comment]
We are using GaussDB(DWS) as datawarehouse on Huawei Cloud, which has a port number after each host in its URL, even if the port number is actually the same.
For example, "jdbc:gaussdb://10.x.x.1:8000,10.x.x.2:8000,10.x.x.3:8000/db"

**Comment by xinxingi** [comment]
@NJCrazyRen 
Since I don’t have Huawei Cloud’s data warehouse for verification, please help me verify it. `jdbc: gaussdb:loadbalance://[host1][:port],[host2][:port][,[host3][:port]]...[/[database]] ` Is it possible to connect to the database using jdbc?

https://dev.mysql.com/doc/connector-j/en/connector-j-usagenotes-j2ee-concepts-managing-load-balanced-connections.html

**Comment by xinxingi** [comment]
You can use a temporary solution first and include a layer of nginx to temporarily accomplish what you want.

**Comment by NJCrazyRen** [comment]
> Since I don’t have Huawei Cloud’s data warehouse for verification, please help me verify it. jdbc: gaussdb:loadbalance://[host1][:port],[host2][:port][,[host3][:port]]...[/[database]]  Is it possible to connect to the database using jdbc?

Unfortunately there's no text about this url format in GaussDB offical documents.
