### ISSUE TITLE
[Bug] K8sTaskExecutionContext incorrectly set configYaml

### ISSUE THREAD

**Issue by xdu-chenrj** [apache/dolphinscheduler#15114]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```java

private KubernetesClient getClient(KubernetesApplicationManagerContext kubernetesApplicationManagerContext) {
        K8sTaskExecutionContext k8sTaskExecutionContext =
                kubernetesApplicationManagerContext.getK8sTaskExecutionContext();
        k8sTaskExecutionContext
                .setConfigYaml(JSONUtils.getNodeString(k8sTaskExecutionContext.getConnectionParams(), "kubeConfig"));
        return cacheClientMap.computeIfAbsent(kubernetesApplicationManagerContext.getLabelValue(),
                key -> new KubernetesClientBuilder()
                        .withConfig(Config.fromKubeconfig(k8sTaskExecutionContext.getConfigYaml())).build());
    }
```

```java
 k8sTaskExecutionContext
                .setConfigYaml(JSONUtils.getNodeString(k8sTaskExecutionContext.getConnectionParams(), "kubeConfig"));
```

We can not directly change this. For normal task, like `spark` on k8s, `k8sTaskExecutionContext` is constructed by `TaskExecutionContextFactory`, when they call `getClient`, `connectionParams` is `null`.

### What you expected to happen

set configYaml during K8S task initialization

### How to reproduce

run `spark` task

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
Keep it open till  #15116 merged.
