### ISSUE TITLE
[Bug] [DataSource] java.lang.RuntimeException: datasource plugin doris' is not found

### ISSUE THREAD

**Issue by soltex** [apache/dolphinscheduler#15111]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. Version 3.2.0
2. Start in standalone mode, plug-in mysql as data element storage
3. The data source configuration is successfully connected to doris.
4. Create a new workflow and select the SQL task, select the doris data source, and perform the insert operation. A java.lang.RuntimeException: datasource plugin doris' is not found exception is reported, and the task execution fails.
![426d4056a5bc49a587ffd02470b6711](https://github.com/apache/dolphinscheduler/assets/900307/3a3075f3-4015-43ce-a2e9-6f675d0e91bc)
![e4c917d5173d940adbb31625fee1da2](https://github.com/apache/dolphinscheduler/assets/900307/38fff7a5-348c-401a-9473-c23748ebdf9b)
[1698979170482.log](https://github.com/apache/dolphinscheduler/files/13246312/1698979170482.log)

### What you expected to happen

The original doris data corresponding to the sql task was executed successfully.

### How to reproduce

After reinstalling ds, the problem still occurs

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

---------

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. 版本 3.2.0
2. 启动方式standalone，外挂mysql作为数据元存储
3. 数据源配置doris联通成功
4. 新建工作流并选择sql任务，选择doris数据源，并执行insert操作报java.lang.RuntimeException: datasource plugin doris' is not found异常，任务执行失败
![426d4056a5bc49a587ffd02470b6711](https://github.com/apache/dolphinscheduler/assets/900307/3a3075f3-4015-43ce-a2e9-6f675d0e91bc)
![e4c917d5173d940adbb31625fee1da2](https://github.com/apache/dolphinscheduler/assets/900307/38fff7a5-348c-401a-9473-c23748ebdf9b)
[1698979170482.log](https://github.com/apache/dolphinscheduler/files/13246312/1698979170482.log)

### What you expected to happen

sql任务对应的doris数据原执行成功

### How to reproduce

重新安装ds后，仍旧出现这个问题

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
the same issue with https://github.com/apache/dolphinscheduler/issues/14547, I will close this issue
