### ISSUE TITLE
[Feature][Dependent] Ignore failed instances that are not scheduled normally during job instance dependency check

### ISSUE THREAD

**Issue by NJCrazyRen** [apache/dolphinscheduler#15121]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Sometimes developers will manually run workflows, such as trial runs after editing workflow definitions. These failed workflow instances that are not generated by scheduled scheduling should not affect dependency checks in normal scheduled workflow instances.

In addition, it is recommended to add a button to force success or ignore failure in the workflow instance list, indicating that it is considered successful during dependency checking. Instead of the existing delete button, as users may need to be able to audit each workflow instance. Regarding this, you can refer to the design of Huawei Cloud DGC.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xinxingi** [comment]
Currently, you can first force all the workflow jobs to execute successfully in Task Instance. If you rely on the entire workflow, a single failed recovery of the workflow instance is sufficient.
![](https://p.sda1.dev/13/e1406aed9b978b11b76fa74146899576/image.png)
