### ISSUE TITLE
[Bug] [flink] When executing the flink task, the flink command cannot be found.

### ISSUE THREAD

**Issue by NCUZK** [apache/dolphinscheduler#15138]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

执行flink 任务出现无法找到flink 命令
```
[INFO] 2023-11-08 11:26:17.735 +0800 -  -> 
	/tmp/dolphinscheduler/exec/process/default/11453119241792/11508352599616_1/1159/1164/1159_1164.sh: line 4: flink: command not found
```

### What you expected to happen

可以正常运行flink 任务

### How to reproduce

自定义flink 任务然后运行

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by NCUZK** [comment]
1. 版本：FROM apache/dolphinscheduler-worker:3.2.0
2. 将flink安装在/opt/soft/flink/路径
3. dockerfile如下
`FROM xxxx as flink
FROM apache/dolphinscheduler-alert-server:3.2.0

ADD ./*.jar /opt/dolphinscheduler/libs/

COPY --from=flink --chown=root:root /opt/flink /opt/soft/flink

ENV PATH="/opt/soft/flink/bin:${PATH}"`
4. 手动执行flink命令可以，但是UI界面上点击运行flink自定义任务会提示找不到flink

**Comment by SbloodyS** [comment]
Please use english to describe.

**Comment by NCUZK** [comment]
问题定位与解决：
1. 打开开发者模式设置development.state为true
2. 执行临时文件发现，不进行sudo可以找到flink
3. 关闭sudo设置sudo.enable为false
