### ISSUE TITLE
[Feature][Module Name] Integration of Keycloak with Apache DolphinScheduler

### ISSUE THREAD

**Issue by vegaskyo** [apache/dolphinscheduler#15134]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I have been researching but haven't found anything on the subject. I've considered modifying the code and setting up the configuration, but it seems frustrating to do so. Is there an easier way to integrate with Keycloak through configuration settings?

### Use case

Integrate with Keycloak through configuration settings

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
There are currently no plans for that.
