### ISSUE TITLE
[Improvement][Resource Center] Display brief file name in file-details page

### ISSUE THREAD

**Issue by zhangjiwei** [apache/dolphinscheduler#15137]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

hadoop集群与dolphin是分开部署的，不知道这个需要怎么配置，才能显示不是全路径的，只显示文件名称
![image](https://github.com/apache/dolphinscheduler/assets/859782/6f9d1f18-6485-4cb8-9891-20f54c86eda1)

### What you expected to happen

hadoop集群与dolphin是分开部署的，不知道这个需要怎么配置，才能显示不是全路径的，只显示文件名称

### How to reproduce

hadoop集群与dolphin是分开部署的，不知道这个需要怎么配置，才能显示不是全路径的，只显示文件名称

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi @zhangjiwei , you can submit a PR to modify UI part.

**Comment by arlendp** [comment]
If no one is working on this, i'd like to submit a PR

**Comment by Radeity** [comment]
> If no one is working on this, i'd like to submit a PR

Okay, assign to you :D
