### ISSUE TITLE
[Bug] [setValue] if "\n" in variable, then setValue function will work bad

### ISSUE THREAD

**Issue by kevinkelin** [apache/dolphinscheduler#15136]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In python task , if a variable has "\n"， then use setValue to make a Parameter for next node,  the variable will not work well 

node_one 
```python
s = "hello \n world"
print("${setValue(message=%s)}"%s)
```

node_two
```shell
echo "${message}"

echo "hi"
```

check runtime log 

node_one 
```
[INFO] 2023-11-08 10:51:02.588 +0800 - process start, process id is: 10376
[INFO] 2023-11-08 10:51:03.588 +0800 -  -> 
	 world)}
[INFO] 2023-11-08 10:51:03.590 +0800 - process has exited. execute 
```

node_two
```
[INFO] 2023-11-08 10:51:04.374 +0800 - process start, process id is: 30190
[INFO] 2023-11-08 10:51:05.374 +0800 -  -> 
	
	hi
[INFO] 2023-11-08 10:51:05.375 +0800 - process has exited. execute
```

### What you expected to happen

In node_two, when `echo "${message}"`  will show the  Parameter set in pre task,  in this case, want show “hello \n world"

### How to reproduce

create a workflow, the first task use python task, make a variable include "\n", then use setValue to make a  Parameter

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi @kevinkelin , according to the above logs of `node_one`, seems like it doesn't print `${setValue(key=value}`.

**Comment by kevinkelin** [comment]
> Hi @kevinkelin , according to the above logs of `node_one`, seems like it doesn't print `${setValue(key=value}`.

if setValue work well,  there will not print any thing, but in this case, it print `world)}`

**Comment by Radeity** [comment]
> > Hi @kevinkelin , according to the above logs of `node_one`, seems like it doesn't print `${setValue(key=value}`.
> 
> if setValue work well, there will not print any thing, but in this case, it print `world)}`

You should make sure `${setValue(key=value}`  exists in stdout of `node_one`.

**Comment by kevinkelin** [comment]
> > > Hi @kevinkelin , according to the above logs of `node_one`, seems like it doesn't print `${setValue(key=value}`.
> > 
> > 
> > if setValue work well, there will not print any thing, but in this case, it print `world)}`
> 
> You should make sure `${setValue(key=value}` exists in stdout of `node_one`.

I resolve this issue

node_one
```python
s = "hello \n world"
print("${setValue(message=%s)}"%repr(s))
```


node_two

```shell
echo "${message}"

echo "hi"
```

In node_onw, python task must use `repr(s)` for formating string

so consider about how to optimize this Issue.

**Comment by Radeity** [comment]
You're right, actually, the cause of the issue is that we find output parameter in a single line, so in your resolution, use `repr` to read `\n`, then in stdout, this line will be `${setValue(message=hello \n world)}`.
```java
if (line.startsWith("${setValue(") || line.startsWith("#{setValue(")) {
    varPool.append(findVarPool(line));
    varPool.append("$VarPool$");
}
```

I think we don't have to fix it, instead, we can declare more clearly in our doc, WDYT?

**Comment by kevinkelin** [comment]
> You're right, actually, the cause of the issue is that we find output parameter in a single line, so in your resolution, use `repr` to read `\n`, then in stdout, this line will be `${setValue(message=hello \n world)}`.
> 
> ```java
> if (line.startsWith("${setValue(") || line.startsWith("#{setValue(")) {
>     varPool.append(findVarPool(line));
>     varPool.append("$VarPool$");
> }
> ```
> 
> I think we don't have to fix it, instead, we can declare more clearly in our doc, WDYT?

I think is OK, make doc clearly, so that users can avoid this problem.

**Comment by Radeity** [comment]
Would you like to help enhance the doc? @kevinkelin

**Comment by kevinkelin** [comment]
> Would you like to help enhance the doc? @kevinkelin

OK， how to enhance the doc?

**Comment by Radeity** [comment]
You can submit PR to this repo, ref https://github.com/apache/dolphinscheduler/pull/15028
