### ISSUE TITLE
[Bug] [master server]  2.0.5 version，i dont kill task，but retry task not work occasionally

### ISSUE THREAD

**Issue by 997759790** [apache/dolphinscheduler#15135]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

2.0.5 version，i dont kill task，but retry task not work occasionally

### What you expected to happen

normal work

### How to reproduce

occasionally

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 997759790** [comment]
Currently I use delayed execution, but it doesn't work either. Our scheduling platform has been running fine for more than half a year, but it started to have this kind of problem recently.
Please refer to the following pictures for specific problem explanations。

![RTX截图未命名](https://github.com/apache/dolphinscheduler/assets/9440510/6dc2b4b4-efa9-47af-8547-9d75398f3488)
![RTX截图未命名2](https://github.com/apache/dolphinscheduler/assets/9440510/a146d4bf-bbb0-4b84-b6e6-58a642225211)

**Comment by SbloodyS** [comment]
You can try upgrade to version 2.0.8. @997759790

**Comment by 997759790** [comment]
> You can try upgrade to version 2.0.8. @997759790

Is there a solution in 2.0.5? Currently, it is found that other workflow instances will block retry tasks.
