### ISSUE TITLE
[Bug] [Task instance] Forced success, running time does not stop

### ISSUE THREAD

**Issue by sdhzwc** [apache/dolphinscheduler#15142]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The task instance is forced successfully and the running time does not stop

### What you expected to happen

The task has ended and the running time has stopped

### How to reproduce

The task is scheduled to machine A, and then KILLs the worker directly, and another machine will be retried. At this time, the task is successfully executed, and then the previous task performs a forced success operation, but the running time does not stop.

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@sdhzwc Could u plz use English only for issue description? Thx : )

**Comment by sdhzwc** [comment]
> @sdhzwc Could u plz use English only for issue description? Thx : )

ok

**Comment by EricGao888** [comment]
` At this time, the task is successfully executed, and then the previous task performs a forced success operation, but the running time does not stop.` 

This is confusing. What does `the running time doses not stop` mean? Not sure what not stop.

**Comment by sdhzwc** [comment]
> ` At this time, the task is successfully executed, and then the previous task performs a forced success operation, but the running time does not stop.` 
> 
> 
> 
> This is confusing. What does `the running time doses not stop` mean? Not sure what not stop. 

It can be understood as a successful click, but the backend does not set an end time for successful execution, which leads to the front-end mistakenly believing that the task is still running. In fact, this task has already ended
