### ISSUE TITLE
[Bug] Pod startup error

### ISSUE THREAD

**Issue by TheWindIsRising** [apache/dolphinscheduler#15143]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

使用heml部署dolphinscheduler3.1.2 worker节点出现错误
![image](https://github.com/apache/dolphinscheduler/assets/124865830/ea9848da-ec4e-4b24-9b2c-4355f1fbb4d5)

### What you expected to happen

疑似后端代码错误？或者我的配置文件有问题吗？

### How to reproduce

使用helm部署dolphinscheduler3.1.2 查看woker Pod日志

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@TheWindIsRising 
![image](https://github.com/apache/dolphinscheduler/assets/34905992/47dc133e-19e2-4f7e-b2e9-415c6d5be265)
