### ISSUE TITLE
[Improvement][All] Better help users solve usage problems

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#15158]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

```
我希望我们按照每月一个的频率新建一个issue收集各种用户产生的问题。committer 可以自己判断这个是否是bug,如果是则新开一个issue描述这个问题，社区运营每月可以整理这个issue ，贡献者也可以在这个issue下留下自己的意见，这将会产生如下好处
1.使得用户提出的一些问题能够在指定的期限前的到回复（大家群很多，有时候会忽略掉用户的问题，比如微信和slack 实际上回复的很少）
2.鼓励更广泛的群体参与进来，能够产生更多的非代码贡献者
3.如果再加一个issue作为历史目录，将各月份的issue串联起来，能够将大家解决问题的经验组织起来。避免各位使用者各自独立解决
4.对于新用户更加友好。更容易发现问题。
5.在统一的Issue下处理讨论，运营收集的问题更全面，查找问题的用户也能够更清晰的查看整个讨论流程
```

```
I hope we can create a new issue once a month to collect issues raised by various users. The committer can judge by himself whether this is a bug. If so, he will open a new issue to describe the problem. Community operations can organize this issue every month. Contributors can also leave their own opinions under this issue, which will produce the following benefits.
1. Enable some questions raised by users to be answered before the specified deadline
2. Encourage a wider group to participate, which can generate more non-code contributors
3. If you add another issue as a directory and connect the issues in each month, you can organize everyone's experience in solving problems. Prevent each user from solving the problem independently
4. More friendly to new users. It's easier to spot problems.
5. Process discussions under a unified Issue, the issues collected by operations are more comprehensive, and users looking for issues can also view the entire discussion process more clearly.

```

cc @EricGao888 @davidzollo @Niko-Zeng @Radeity @ruanwenjun @zhongjiajie @caishunfeng @Gallardot 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
I think the root cause to the situation that we have so many pending issues is that we do not have enough active maintainers with time to handle them. Changing the way to manage those issues might not be helpful. BTW, you do not need to describe the issue bilingually, using only English is ok.

**Comment by kezhenxu94** [comment]
> 1. Enable some questions raised by users to be answered before the specified deadline

There is no such thing called "deadline" in open source community, all contributions are done on the basis of voluntary, no one is expected to answer others' questions before a specific time, so please don't set this kind of rules.

> 2. Encourage a wider group to participate, which can generate more non-code contributors

Why do you think this can encourage a wider group of contributors? From what I know, there are hundreds of WeChat groups that gathered thousands of potential contributors, which still leads to the current situation, creating such issues doesn't help to improve the situation but only to increase the workload of maintainers and produce many spams in my opinion.

> 4. If you add another issue as a directory and connect the issues in each month, you can organize everyone's experience in solving problems. Prevent each user from solving the problem independently.

Users can search issues on GitHub. As I said, creating duplicate issues only produces spams and duplicate search results, which in turn increases the efforts to identify the real issue that actually solves the problem.

**Comment by fuchanghai** [comment]
> There is no such thing called "deadline" in open source community, all contributions are done on the basis of voluntary, no one is expected to answer others' questions before a specific time, so please don't set this kind of rules.

I saw that the official would regularly collect some questions to answer, so I was thinking why not collect them through a unified channel, and many channels are indeed too inactive, with no one to answer them.

>Why do you think this can encourage a wider group of contributors? From what I know, there are hundreds of WeChat groups that gathered thousands of potential contributors, which still leads to the current situation, creating such issues doesn't help to improve the situation but only to increase the workload of maintainers and produce many spams in my opinion.

Answering the problem-solving question here, I think the contribution of the person who solves the problem is visible and quantifiable, and can be used as a basis for promoting non-code contributors, so I think it can encourage other people to solve the problem. I feel that if something cannot be quantified, it cannot be optimized and evaluated.

**Comment by Niko-Zeng** [comment]
I think we have to find contributors who are interested in this, or contributors who are keen to solve the issue. With enthusiasm, this matter can continue to advance. The problem is that this is very difficult. Within the scope of my knowledge, it may Gain less sense of accomplishment

**Comment by kezhenxu94** [comment]
> I saw that the official would regularly collect some questions to answer, so I was thinking why not collect them through a unified channel, and many channels are indeed too inactive, with no one to answer them.
> 

What do you mean by "the official would regularly collect some questions to answer", from what I know, there is no one from the PMC team doing this. If you mean some vendors are doing this, that's not "official". 



> Answering the problem-solving question here, I think the contribution of the person who solves the problem is visible and quantifiable, and can be used as a basis for promoting non-code contributors, so I think it can encourage other people to solve the problem. I feel that if something cannot be quantified, it cannot be optimized and evaluated.
> 
> 

Contributors can reply in issues to answer questions, there is no need to create issues serving as table of contents, you can label the issues and potential contributors can filter issues by those labels. Learn how to leverage existing GitHub features instead of making things too complex.

**Comment by fuchanghai** [comment]
> Contributors can reply in issues to answer questions, there is no need to create issues serving as table of contents, you can label the issues and potential contributors can filter issues by those labels. Learn how to leverage existing GitHub features instead of making things too complex.

I can probably understand what you mean. I should encourage them to open a new issue to describe the problem instead of leaving the problem in an independent WeChat group. PMCs are not obliged to solve user problems within a certain period of time. My original intention is to have a unified place where everyone’s experience can be gathered to facilitate users to solve problems (not just how to solve bugs). Maybe the core problem is that it is not active enough.
