### ISSUE TITLE
[Feature][SQL] Can support #{} similar to mybatis

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#15171]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://github.com/apache/dolphinscheduler/assets/33984497/f448caac-1044-4582-b189-5f224601acb2)
![image](https://github.com/apache/dolphinscheduler/assets/33984497/0d1495f4-ca75-4c17-92df-361293a61732)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Is there any advantage to use # rather than $? I don't think we need to deal with `SQL injection`in sql task

**Comment by fuchanghai** [comment]
hi @ruanwenjun We now have a use case where the sql type node in the current process definition needs an output type variable declared by the subprocess definition that depends on the subprocess type node. This subprocess definition is referenced by many parent canvases. The advantage is that when we need to change, we only need to change the variable values in the subprocess definition, instead of changing all the canvases

**Comment by fuchanghai** [comment]
> hi @ruanwenjun We now have a use case where the sql type node in the current process definition needs an output type variable declared by the subprocess definition that depends on the subprocess type node. This subprocess definition is referenced by many parent canvases. The advantage is that when we need to change, we only need to change the variable values in the subprocess definition, instead of changing all the canvases

We need to concatenate this sql statement using variables of the output type of the upstream node

**Comment by fuchanghai** [comment]
This function has been implemented，i will close this issue ,and add some documents
<img width="1044" alt="image" src="https://github.com/apache/dolphinscheduler/assets/33984497/b630e95d-0d7e-469d-bd95-f532eacc06de">
