### ISSUE TITLE
[Feature][dolphinscheduler-task-sqoop] add sqoop source/target type

### ISSUE THREAD

**Issue by xujiaqiang** [apache/dolphinscheduler#15178]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

 add sqoop source/target type

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xiaominyuan** [comment]
if there is somebody working on this issue? I‘m willing to undertake it!
