### ISSUE TITLE
[Bug] [Master] MasterHeartBeat failed to parse json

### ISSUE THREAD

**Issue by windyund** [apache/dolphinscheduler#15180]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Version 3.2.0 cluster deployment, after the Linux service deployment is completed, check the service status, master, worker, api server, alert are all running. When logging in to the web page, check the master node menu in the service management, it is prompted that the master node does not exist, open the master The log view error message is as follows: 
[ERROR] 2023-11-17 17:50:55.271 +0800 org.apache.dolphinscheduler.common.utils.JSONUtils:[146] - [WorkflowInstance-0][TaskInstance-0] - Parse object exception, jsonStr: 0.0, 0.11,0.01,112.17,64.0,0.3,1697613709943,1700214651099,0,26455,0,0,0, class: class org.apache.dolphinscheduler.common.model.MasterHeartBeat
com.fasterxml.jackson.core.JsonParseException: Unexpected character (',' (code 44)): Expected space separating root-level values
  at [Source: (String)"0.0,0.11,0.01,112.17,64.0,0.3,1697613709943,1700214651099,0,26455,0,0,0"; line: 1, column: 5]

<img width="1401" alt="image" src="https://github.com/apache/dolphinscheduler/assets/37654647/b097bdc1-120a-457d-a75f-790673622175">

### What you expected to happen

master normal viewing

### How to reproduce

![image](https://github.com/apache/dolphinscheduler/assets/37654647/5e6f2cb8-0cf0-45c9-8ff8-2beaf7132ce7)

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
It seems the master heartbeat is not json format.

**Comment by caishunfeng** [comment]
> It seems the master heartbeat is not json format.

+1, it seems like historical heartbeat info.

**Comment by freedata2022** [comment]
请教下这个问题怎么解决得呢
