### ISSUE TITLE
[Improvement][API] Split Status in to sub status.

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#15183]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We maintain all module status in one class, it's very large, we need to split this by submodule.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhengkezhou1** [comment]
Hello, I want to participate in this project

**Comment by ruanwenjun** [comment]
> Hello, I want to participate in this project

Assigned to you, this is not a hard work but will need to change a lot of code, can you provide some demo code first?

**Comment by zhengkezhou1** [comment]
here are my thoughts, please give me some advice?@ruanwenjun 
1. Split status according to different services

    ```java
    /*enum TaskStatus.java*/
    TASK_TIMEOUT_PARAMS_ERROR(10002, "task timeout parameter is not valid", "任务超时参数无效")
    
    /*enum UserStatus.java*/
    USER_NAME_EXIST(10003, "user name already exists", "用户名已存在")
        
    /**enum DataSourceStatus.java*/    
    DATASOURCE_EXIST(10015, "data source name already exists", "数据源名称已存在")
    ```

2. Abandon the putMsg() method in **BaseService** and implement the **putMsg()** method according to the status split by different services.

```java
/*ExecutorServiceImpl.java*/

/**
     * put message to map
     *
     * @param result result code
     * @param taskStatus status
     * @param statusParams status message
     */
    private void putMsg(Map<String, Object> result, TaskStatus taskStatus, Object... statusParams) {
        result.put(Constants.STATUS, taskStatus);
        if (statusParams != null && statusParams.length > 0) {
            result.put(Constants.MSG, MessageFormat.format(taskStatus.getMsg(), statusParams));
        } else {
            result.put(Constants.MSG, taskStatus.getMsg());
        }
    }

```
This method is intuitive, but requires changing a lot of code

**Comment by ruanwenjun** [comment]
> here are my thoughts, please give me some advice?@ruanwenjun
> 
> 1. Split status according to different services
>    ```java
>    /*enum TaskStatus.java*/
>    TASK_TIMEOUT_PARAMS_ERROR(10002, "task timeout parameter is not valid", "任务超时参数无效")
>    
>    /*enum UserStatus.java*/
>    USER_NAME_EXIST(10003, "user name already exists", "用户名已存在")
>        
>    /**enum DataSourceStatus.java*/    
>    DATASOURCE_EXIST(10015, "data source name already exists", "数据源名称已存在")
>    ```
> 2. Abandon the putMsg() method in **BaseService** and implement the **putMsg()** method according to the status split by different services.
> 
> ```java
> /*ExecutorServiceImpl.java*/
> 
> /**
>      * put message to map
>      *
>      * @param result result code
>      * @param taskStatus status
>      * @param statusParams status message
>      */
>     private void putMsg(Map<String, Object> result, TaskStatus taskStatus, Object... statusParams) {
>         result.put(Constants.STATUS, taskStatus);
>         if (statusParams != null && statusParams.length > 0) {
>             result.put(Constants.MSG, MessageFormat.format(taskStatus.getMsg(), statusParams));
>         } else {
>             result.put(Constants.MSG, taskStatus.getMsg());
>         }
>     }
> ```
> 
> This method is intuitive, but requires changing a lot of code

A better way is change Status into a interface, keep the method getMsg and getCode, only splite the enum into sub Enum which need to implement the `Status `, then you don't need to change the code in the service in this pr.

**Comment by zhengkezhou1** [comment]
@ruanwenjun , I have submitted PR, my thoughts are as follows:
1. As you said, create status interface and create enumeration class **BaseStatus**, **UserStatus**, more...
2. Migrate the status in status enum to **baseStatus**
3. No longer use status enum in all codes
4. Use **BaseStatus** enum in Status interface
5. Refactor and split the baseStatus enum into a new one

**Comment by zhengkezhou1** [comment]
I encountered a new problem. If I want to divide Status, how should the **Status value()** at this annotation be handled?
```java
@Retention(RUNTIME)
@Target(METHOD)
public @interface ApiException {
	Status value();
}
```
```java
@Parameter(hidden = true)
@PostMapping(value = "/generate")
@ResponseStatus(HttpStatus.CREATED)
@ApiException(GENERATE_TOKEN_ERROR)
public Result<String> generateToken(@RequestAttribute(value = Constants.SESSION_USER) User loginUser,
									@RequestParam(value = "userId") int userId,
									@RequestParam(value = "expireTime") String expireTime) {
	String token = accessTokenService.generateToken(loginUser, userId, expireTime);
	return Result.success(token);
}
```
It is easy to think of defining a new enumeration class in the interface
```java
@Retention(RUNTIME)
@Target(METHOD)
public @interface ApiException {
	Status.ApiStatus value();
}
```
But doing so will result in a lot of duplicate code

**Comment by ruanwenjun** [comment]
@zzzk1 
```
public interface Status {
    String getCode();
    String getMsg();
}

public enum UserStatus implements Status {
     xx("USER-001", ""),
     ...
}

public enum ProjectStatus implements Status {
     xx("PROJECT-001", ""),
     ...
}
```

**Comment by zhengkezhou1** [comment]
![图片](https://github.com/apache/dolphinscheduler/assets/36791902/9a802aaf-7d4c-4be0-9eb6-fe5e847d0f6b)

hi @ruanwenjun, How to deal with status in this place? The interface cannot be used here. Should I create an annotation for each newly separated status enumeration?

```java
public @interface UserException {
	UserStatus value();
}

public @interface TaskException {
    TaskStatus value();
}
```

**Comment by ruanwenjun** [comment]
> ![图片](https://private-user-images.githubusercontent.com/36791902/287628491-9a802aaf-7d4c-4be0-9eb6-fe5e847d0f6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NDE0NzgsIm5iZiI6MTcwMTc0MTE3OCwicGF0aCI6Ii8zNjc5MTkwMi8yODc2Mjg0OTEtOWE4MDJhYWYtN2Q0Yy00YmUwLTllYjYtZmU1ZTg0N2QwZjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDAxNTI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmODBmOTk0YzM3OTQ0YWYyNGNlYTQ1MTRiYTJkNTYyMGJjY2VmM2U5NDM4MGU5Mjk3OTU1YTI0NjJkNmVhZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n3yEx3fpEh99U3TvrRDKnk6HCpEGdGDPWzStzf8jXpA)
> 
> hi @ruanwenjun, How to deal with status in this place? The interface cannot be used here. Should I create an annotation for each newly separated status enumeration?
> 
> ```java
> public @interface UserException {
> 	UserStatus value();
> }
> 
> public @interface TaskException {
>     TaskStatus value();
> }
> ```

There is no needed to add annotation for each api, `@ApiException` can be removed, this is used to deal with unknown exception, this is not convenient, since it will hide the exception message.
