### ISSUE TITLE
[Improvement][CI] Remove rebase check in pr.

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#15187]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Right now, we need to rebase the pr to latest dev branch before merged.
<img width="1148" alt="image" src="https://github.com/apache/dolphinscheduler/assets/22415594/b68b8e12-70ae-42b4-85b6-007ab29f07cc">
If we have 10 pr need to merge, we need to rebase one by one, if there is not conflict, this is not needed.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xjlgod** [comment]
please assign to me.

**Comment by ruanwenjun** [comment]
> please assign to me.

Assigned

**Comment by xjlgod** [comment]
> > please assign to me.
> 
> Assigned

I tried using GitHub Action [cirrus-actions/rebase@1.8](https://github.com/cirrus-actions/rebase) for implementation. But we can't use the built-in `secrets.GITHUB_TOKEN`  because of this [limitation](https://docs.github.com/zh/actions/security-guides/automatic-token-authentication),  So we need personal token from forked repo(it's difficult to get), and I don't think this is not a good implementation method. Do you have any other suggestions?

**Comment by ruanwenjun** [comment]
> > > please assign to me.
> > 
> > 
> > Assigned
> 
> I tried using GitHub Action [cirrus-actions/rebase@1.8](https://github.com/cirrus-actions/rebase) for implementation. But we can't use the built-in `secrets.GITHUB_TOKEN` because of this [limitation](https://docs.github.com/zh/actions/security-guides/automatic-token-authentication), So we need personal token from forked repo(it's difficult to get), and I don't think this is not a good implementation method. Do you have any other suggestions?

We might not need to add action, I find in other projects there is no rebase check, so we might only need to close some setting.

**Comment by xjlgod** [comment]
<img width="406" alt="1701231906341" src="https://github.com/apache/dolphinscheduler/assets/42763775/2c0caa2b-6970-4b7e-a5dd-6a64e7b53f87">

I think we can use  `squash and merge` for merging, and if there are no conflicts, it can automatically squash the commits. If we choose `rebase merging`, it can not squash.

**Comment by ruanwenjun** [comment]
> <img alt="1701231906341" width="406" src="https://private-user-images.githubusercontent.com/42763775/286476322-2c0caa2b-6970-4b7e-a5dd-6a64e7b53f87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDIzMDAsIm5iZiI6MTcwMTI0MjAwMCwicGF0aCI6Ii80Mjc2Mzc3NS8yODY0NzYzMjItMmMwY2FhMmItNjk3MC00YjdlLWE1ZGQtNmE2NGU3YjUzZjg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA3MTMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwOGNmNDI1Y2M3NTk1NDNkMzE2NDFiMWRhMGRkZTczMjllZmMyNzcwODlkZmZjZDMxM2FlNDBlYTY1MjYwMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mobz61bGr4isI0HB6KMlxnvcdaqAQ6XtRiKqnwnBY8s">
> I think we can use `squash and merge` for merging, and if there are no conflicts, it can automatically squash the commits. If we choose `rebase merging`, it can not squash.

cc @zhongjiajie Can we change the setting?

**Comment by zhongjiajie** [comment]
hi @ruanwenjun the reason we add this is due to this https://github.com/apache/dolphinscheduler/pull/14530. because we meet some unexpected ci error  when we merge multi pr without rebase the latest code

**Comment by xjlgod** [comment]
maybe we can update branch then use squash？

**Comment by ruanwenjun** [comment]
> hi @ruanwenjun the reason we add this is due to this #14530. because we meet some unexpected ci error when we merge multi pr without rebase the latest code

OK, make sense.

**Comment by ruanwenjun** [comment]
> maybe we can update branch then use squash？

As @zhongjiajie said, we need to make the pr updated before  trigger the ci, then we need to keep, thanks, I will close this issue.
