### ISSUE TITLE
[Improvement][Module Name] Disabling Shell Script Colors Issue

### ISSUE THREAD

**Issue by AVeryHandsomePerson** [apache/dolphinscheduler#15208]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The color display in the shell script becomes less prominent after disabling its execution.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @AVeryHandsomePerson  Please add more detail description for this issue.
