### ISSUE TITLE
[Bug] [kubeneters] Node Selector not work 

### ISSUE THREAD

**Issue by QuanhanSun** [apache/dolphinscheduler#15202]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When i fill node selector in kubeneters task ,it seems not work in the cluster
![image](https://github.com/apache/dolphinscheduler/assets/46819919/656860fd-5f82-4e15-8b38-f827038123e3)
after i run describo pod command, see the information below
![image](https://github.com/apache/dolphinscheduler/assets/46819919/234d3ea5-6c8d-4e86-9463-5b3780734ab9)

### What you expected to happen

The node selector should work

### How to reproduce

just fill in the node selector and execute it, the pod will not dispatch to the sepecific node and the information show Node-Seletors is None

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi, @QuanhanSun , are there any error logs?

**Comment by QuanhanSun** [comment]
Which log do you mean? worker or master , i can repeoduce to take a look ,the pod which patched by worker is working functional except the node selector is none

**Comment by Radeity** [comment]
If you define node selector in UI but find it's not set for the pod, there might be some error logs in worker, please help check it.

**Comment by QuanhanSun** [comment]
You can see the log in the file,
[logs.txt](https://github.com/apache/dolphinscheduler/files/13472405/logs.txt)
And here is the defination of the task
![928f8e89d02642408014b55e2f68c47f](https://github.com/apache/dolphinscheduler/assets/46819919/181acc23-958a-4b09-b8b5-9d8086d773ed)
![e5030dc058404c84a3cbdc2f8965096e](https://github.com/apache/dolphinscheduler/assets/46819919/c07165f0-978d-4014-9b40-10c063e0b1b4)


> If you define node selector in UI but find it's not set for the pod, there might be some error logs in worker, please help check it.

**Comment by Gallardot** [comment]
Please check the created pod for the following configuration:
```yaml
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
```
The dolphinscheduler does not directly use nodeSelector, but uses nodeAffinity instead.

**Comment by QuanhanSun** [comment]
> nodeAffinity

Thanks, l see that in the nodeAffinity
