### ISSUE TITLE
Dolphinscheduler Run Seatunnel job but report "java: command not found"

### ISSUE THREAD

**Issue by ArtistRuan** [apache/dolphinscheduler#15201]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Dolphinscheduler Run Seatunnel job but report "java: command not found" even if the dolphinscheduler-env.sh was set with below setting
![image](https://github.com/apache/dolphinscheduler/assets/58499910/750c1dd1-8119-45b2-b070-5200e1e15c32)

### What you expected to happen

run seatunnel job with dolphinscheduler please

### How to reproduce

up the containner of dolphinscheduler and install seatunnel after enter the dolphinscheduler-work,then setting the seatunnel example with dolphinscheduler

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ArtistRuan** [comment]
by the way,I deployed the dolphinscheduler with docker-desktop,and the seatunnel was downloaded and installed in the container of dolphinscheduler-work

**Comment by ArtistRuan** [comment]
the error pic as follow,please let me know what should I do to fix it:
![image](https://github.com/apache/dolphinscheduler/assets/58499910/6cf19e23-0576-4bee-b0d3-f02f7b4777b3)

**Comment by YuriyGavrilov** [comment]
@ArtistRuan Try to set up environment variable in task property "Environment" ( before choosing it should be set up in Dolphin settings.  

<img width="790" alt="Снимок экрана 2023-12-21 в 20 59 04" src="https://github.com/apache/dolphinscheduler/assets/44679014/3df3d803-9d6e-4579-8296-68c9046e7627">
<img width="754" alt="Снимок экрана 2023-12-21 в 20 58 23" src="https://github.com/apache/dolphinscheduler/assets/44679014/835c01b0-5845-4178-a9d8-0ce36f63cde8">
