### ISSUE TITLE
[Bug] [WorkerServer] Referencing child nodes in workflow definition, tenant cannot pass in child nodes during runtime

### ISSUE THREAD

**Issue by gitrenliping** [apache/dolphinscheduler#15203]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

工作流定义中引用子节点，运行是租户无法传入子节点

### What you expected to happen

主工作流执行选择的租户，应用到子任务

### How to reproduce

![1700636923064](https://github.com/apache/dolphinscheduler/assets/148838028/460b7248-ecd1-47e5-a0a1-a7c6e1d34383)
![1700636812697](https://github.com/apache/dolphinscheduler/assets/148838028/caaf3c3c-2e61-4978-8209-931f11a2d348)

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Fixed.
