### ISSUE TITLE
[Improvement][Front] Optimize the default query for task instances

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#15213]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Change the query at the task instance from the default query of the entire amount of data to the default query of the last day's data.  

The default data volume is too large and may cause timeout

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
hi @ruanwenjun  i think this is a good first issue

**Comment by ruanwenjun** [comment]
> hi @ruanwenjun i think this is a good first issue

Which interface? The old query SQL will join the project table and workflow table, we can remove this kind of join.

**Comment by fuchanghai** [comment]
> > hi @ruanwenjun i think this is a good first issue
> 
> Which interface? The old query SQL will join the project table and workflow table, we can remove this kind of join.

> get
> /dolphinscheduler/projects/{projectCode}/task-instances
