### ISSUE TITLE
[Bug] [API] Users are not allowed to modify the default tenant and queue through the update API

### ISSUE THREAD

**Issue by brave-lee** [apache/dolphinscheduler#15215]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Users can modify the default tenant and queue through the update api. I think this should not be allowed because it cannot be modified through the UI. This should be consistent.

### What you expected to happen

Users are not allowed to modify the default tenant and queue through the update API

### How to reproduce

https://lists.apache.org/thread/89tkm3lmqlzbtm86kx3xnk8cc1smfm83

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhanqian0609** [comment]
I'll fix it
