### ISSUE TITLE
[Improvement][E2E] Add dolphinscheduler-e2e into root pom

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#15224]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Right now, if we want to add e2e case or run the e2e case locally, it's not convenient, can we add dolphinscheduler-e2e into root pom?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pegasas** [comment]
I create a PR for fixing this.
feel free to comments if any concern.

**Comment by pegasas** [comment]
still working on it. pending approve & merge

**Comment by pegasas** [comment]
> still working on it. pending approve & merge

As sync in meeting with @zhongjiajie & @EricGao888 ,
It seems expected and won't fix this issue.

Request to close this issue.
