### ISSUE TITLE
[Bug] worker]  The task submission is always in the dispatch state

### ISSUE THREAD

**Issue by hanpi14** [apache/dolphinscheduler#15221]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I was running a task using Dolphinscheduler3.1.7, I was DolphinScheduler3.1.7. After the task was created, it was still being dispatched when it was online, and an error was reported in the background

The error is as follows:
[INFO] 2023-11-24 16:19:20.057 +0800 org.apache.zookeeper.ClientCnxn:[1025] - [WorkflowInstance-0][TaskInstance-0] - Opening socket connection to server dolphinscheduler-master-0.dolphinscheduler-master-headless/10.20.235.1:8116. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2023-11-24 16:19:20.073 +0800 org.apache.zookeeper.ClientCnxn:[879] - [WorkflowInstance-0][TaskInstance-0] - Socket connection established to dolphinscheduler-master-0.dolphinscheduler-master-headless/10.20.235.1:8116, initiating session
[INFO] 2023-11-24 16:19:20.091 +0800 org.apache.zookeeper.ClientCnxn:[1299] - [WorkflowInstance-0][TaskInstance-0] - Session establishment complete on server dolphinscheduler-master-0.dolphinscheduler-master-headless/10.20.235.1:8116, sessionid = 0x30097c18ee20003, negotiated timeout = 30000
[INFO] 2023-11-24 16:19:20.091 +0800 org.apache.curator.framework.state.ConnectionStateManager:[251] - [WorkflowInstance-0][TaskInstance-0] - State change: RECONNECTED
[INFO] 2023-11-24 16:19:20.091 +0800 org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperConnectionStateListener:[48] - [WorkflowInstance-0][TaskInstance-0] - Registry reconnected
[INFO] 2023-11-24 16:19:20.091 +0800 org.apache.dolphinscheduler.server.worker.registry.WorkerConnectionStateListener:[46] - [WorkflowInstance-0][TaskInstance-0] - Worker received a RECONNECTED event from registry, the current server state is RUNNING
[INFO] 2023-11-24 16:19:20.091 +0800 org.apache.dolphinscheduler.server.worker.registry.WorkerWaitingStrategy:[96] - [WorkflowInstance-0][TaskInstance-0] - no need to reconnect, as the current server status is running
[INFO] 2023-11-24 16:19:22.811 +0800 org.apache.dolphinscheduler.server.worker.task.WorkerHeartBeatTask:[89] - [WorkflowInstance-0][TaskInstance-0] - Success write worker group heartBeatInfo into registry, workerRegistryPath: /nodes/worker/10.11.52.195:1234 workerHeartBeatInfo: {"startupTime":1700809944198,"reportTime":1700813962771,"cpuUsage":0.0,"memoryUsage":0.15,"loadAverage":0.12,"availablePhysicalMemorySize":13.25,"maxCpuloadAvg":16.0,"reservedMemory":0.3,"diskAvailable":26.68,"serverStatus":0,"processId":102707,"workerHostWeight":100,"workerWaitingTaskCount":0,"workerExecThreadCount":100}
[INFO] 2023-11-24 16:19:25.808 +0800 org.apache.dolphinscheduler.service.log.LoggerRequestProcessor:[79] - [WorkflowInstance-0][TaskInstance-0] - received command : Command [type=ROLL_VIEW_LOG_REQUEST, opaque=767900, bodyLen=42,body={"path":null,"skipLineNum":0,"limit":1000}]
[WARN] 2023-11-24 16:19:25.809 +0800 org.apache.dolphinscheduler.service.log.LoggerRequestProcessor:[189] - [WorkflowInstance-0][TaskInstance-0] - path is null
[ERROR] 2023-11-24 16:19:25.809 +0800 org.apache.dolphinscheduler.remote.handler.NettyServerHandler:[131] - [WorkflowInstance-0][TaskInstance-0] - process msg Command [type=ROLL_VIEW_LOG_REQUEST, opaque=767900, bodyLen=42,body={"path":null,"skipLineNum":0,"limit":1000}] error
java.lang.IllegalArgumentException: Illegal path: null
	at org.apache.dolphinscheduler.service.log.LoggerRequestProcessor.process(LoggerRequestProcessor.java:112)
	at org.apache.dolphinscheduler.remote.handler.NettyServerHandler.lambda$processReceived$0(NettyServerHandler.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2023-11-24 16:19:28.787 +0800 org.apache.zookeeper.ClientCnxn:[1158] - [WorkflowInstance-0][TaskInstance-0] - Unable to read additional data from server sessionid 0x30097c18ee20003, likely server has closed socket, closing socket connection and attempting reconnect
[INFO] 2023-11-24 16:19:28.888 +0800 org.apache.curator.framework.state.ConnectionStateManager:[251] - [WorkflowInstance-0][TaskInstance-0] - State change: SUSPENDED
[WARN] 2023-11-24 16:19:28.888 +0800 org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperConnectionStateListener:[52] - [WorkflowInstance-0][TaskInstance-0] - Registry suspended
[INFO] 2023-11-24 16:19:28.888 +0800 org.apache.dolphinscheduler.server.worker.registry.WorkerConnectionStateListener:[46] - [WorkflowInstance-0][TaskInstance-0] - Worker received a SUSPENDED event from registry, the current server state is RUNNING
[INFO] 2023-11-24 16:19:30.677 +0800 org.apache.zookeeper.ClientCnxn:[1025] - [WorkflowInstance-0][TaskInstance-0] - Opening socket connection to server dolphinscheduler-master-0.dolphinscheduler-master-headless/10.20.235.1:8116. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2023-11-24 16:19:30.694 +0800 org.apache.zookeeper.ClientCnxn:[879] - [WorkflowInstance-0][TaskInstance-0] - Socket connection established to dolphinscheduler-master-0.dolphinscheduler-master-headless/10.20.235.1:8116, initiating session
[INFO] 2023-11-24 16:19:30.712 +0800 org.apache.zookeeper.ClientCnxn:[1299] - [WorkflowInstance-0][TaskInstance-0] - Session establishment complete on server dolphinscheduler-master-0.dolphinscheduler-master-headless/10.20.235.1:8116, sessionid = 0x30097c18ee20003, negotiated timeout = 30000
[INFO] 2023-11-24 16:19:30.712 +0800 org.apache.curator.framework.state.ConnectionStateManager:[251] - [WorkflowInstance-0][TaskInstance-0] - State change: RECONNECTED
[INFO] 2023-11-24 16:19:30.713 +0800 org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperConnectionStateListener:[48] - [WorkflowInstance-0][TaskInstance-0] - Registry reconnected
[INFO] 2023-11-24 16:19:30.713 +0800 org.apache.dolphinscheduler.server.worker.registry.WorkerConnectionStateListener:[46] - [WorkflowInstance-0][TaskInstance-0] - Worker received a RECONNECTED event from registry, the current server state is RUNNING
[INFO] 2023-11-24 16:19:30.713 +0800 org.apache.dolphinscheduler.server.worker.registry.WorkerWaitingStrategy:[96] - [WorkflowInstance-0][TaskInstance-0] - no need to reconnect, as the current server status is running
[INFO] 2023-11-24 16:19:31.810 +0800 org.apache.dolphinscheduler.service.log.LoggerRequestProcessor:[79] - [WorkflowInstance-0][TaskInstance-0] - received command : Command [type=ROLL_VIEW_LOG_REQUEST, opaque=767905, bodyLen=42,body={"path":null,"skipLineNum":0,"limit":1000}]
[WARN] 2023-11-24 16:19:31.810 +0800 org.apache.dolphinscheduler.service.log.LoggerRequestProcessor:[189] - [WorkflowInstance-0][TaskInstance-0] - path is null
[ERROR] 2023-11-24 16:19:31.810 +0800 org.apache.dolphinscheduler.remote.handler.NettyServerHandler:[131] - [WorkflowInstance-0][TaskInstance-0] - process msg Command [type=ROLL_VIEW_LOG_REQUEST, opaque=767905, bodyLen=42,body={"path":null,"skipLineNum":0,"limit":1000}] error
java.lang.IllegalArgumentException: Illegal path: null
	at org.apache.dolphinscheduler.service.log.LoggerRequestProcessor.process(LoggerRequestProcessor.java:112)
	at org.apache.dolphinscheduler.remote.handler.NettyServerHandler.lambda$processReceived$0(NettyServerHandler.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### What you expected to happen

Normal task submission

### How to reproduce

I deployed the Dolphinscheduler using k8s. The error occurred when the task was submitted to the worker node outside the container. Communication has been resolved, but the above problems often occur when the task submission is running

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
```
[INFO] 2023-11-24 16:19:28.787 +0800 org.apache.zookeeper.ClientCnxn:[1158] - [WorkflowInstance-0][TaskInstance-0] - Unable to read additional data from server sessionid 0x30097c18ee20003, likely server has closed socket, closing socket connection and attempting reconnect
[INFO] 2023-11-24 16:19:28.888 +0800 org.apache.curator.framework.state.ConnectionStateManager:[251] - [WorkflowInstance-0][TaskInstance-0] - State change: SUSPENDED
[WARN] 2023-11-24 16:19:28.888 +0800 org.apache.dolphinscheduler.plugin.registry.zookeeper.ZookeeperConnectionStateListener:[52] - [WorkflowInstance-0][TaskInstance-0] - Registry suspended
```

It seems the registry connection was closed or expired, please check the network for it.

**Comment by hanpi14** [comment]
In fact, the network communication between the worker node and zookeeper is normal

**Comment by gitfortian** [comment]
+1  i meet the same problem,and the network communication between the worker node and zookeeper is normal,my version is 3.1.8

**Comment by Theocsx** [comment]
+1 我将master，zk，api部署在k8s，worker部署在大数据环境的主机上并且worker节点和zookeeper之间的网络通信正常。执行任务的时候任务状态为派发，但是work日志显示延时执行并且可以执行成功，打印到logs目录下。我的版本是3.1.8

**Comment by Theocsx** [comment]
已解决，将k8s中master服务的listen-port暴露出来，存入zk。
