### ISSUE TITLE
[Bug] [DataSource] can not load datasource of ``` HANA```

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#15241]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="686" alt="image" src="https://github.com/apache/dolphinscheduler/assets/33984497/e1eaa4f6-715c-40b3-88b6-386f20148f16">

### What you expected to happen

att

### How to reproduce

att

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
close by https://github.com/apache/dolphinscheduler/pull/15260
