### ISSUE TITLE
[Bug] [java task]  When Java obtains the Local Parameter, ${Parameter} is of type list and keeps reporting errors 

### ISSUE THREAD

**Issue by san346596324** [apache/dolphinscheduler#15252]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 Java can obtain Local Parameters normally 

### What you expected to happen

 Format error when obtaining Parameters for Java task 

### How to reproduce

 I obtained a list from SQL and passed it to the Java task. The ${Parameters} data is in the format of ["111", "222", "333"] and cannot be used by Java 

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by san346596324** [comment]
@106umao 这个问题有办法解决吗

**Comment by woshiwuxiaofei** [comment]
@san346596324 报错截图可以贴下吗？然后我来帮忙看下如何解决，暂时我来跟进可否？

**Comment by san346596324** [comment]
> @san346596324 报错截图可以贴下吗？然后我来帮忙看下如何解决，暂时我来跟进可否？

好的，感谢！
1.获取SQL的数据 
![图片](https://github.com/apache/dolphinscheduler/assets/30828520/207ee646-75ab-4c18-ab69-6ee53246b7df)
2.进行java的编写
![图片](https://github.com/apache/dolphinscheduler/assets/30828520/9ab68d82-a9a6-4c68-b096-9596b4ec5367)
3.bug报错
![图片](https://github.com/apache/dolphinscheduler/assets/30828520/81c47ff7-eac0-49cc-82fa-58f81c4cf148)

**Comment by woshiwuxiaofei** [comment]
OK, 我立马来解决它

**Comment by woshiwuxiaofei** [comment]
![20231210174433](https://github.com/apache/dolphinscheduler/assets/17974050/228c0d70-86fb-44f2-87ce-5e3e35eaba29)
![20231210174649](https://github.com/apache/dolphinscheduler/assets/17974050/91910ab1-e5e3-4d32-9d4c-15cbdeb1a5d7)

**Comment by woshiwuxiaofei** [comment]
我本地测试了一下，是没问题的，你这边方便跟我快速私下交流下吗？ @san346596324

**Comment by san346596324** [comment]
> 我本地测试了一下，是没问题的，你这边方便跟我快速私下交流下吗？ @san346596324

ok，你加下我QQ 346596324

**Comment by san346596324** [comment]
> 我本地测试了一下，是没问题的，你这边方便跟我快速私下交流下吗？ @san346596324

![图片](https://github.com/apache/dolphinscheduler/assets/30828520/1fe8293b-2246-4776-8287-010cf66374d3)
@woshiwuxiaofei 这个写法应该是错的才对,java正常这样写才是正确的写法
![图片](https://github.com/apache/dolphinscheduler/assets/30828520/ee9b5b64-3f8a-47e9-833f-ddb645923e48)

**Comment by woshiwuxiaofei** [comment]
@san346596324 已经加你微信，你通过下

**Comment by zhongjiajie** [comment]
Hi @woshiwuxiaofei @san346596324 , so.it is a bug or wrong usage?

**Comment by san346596324** [comment]
> Hi @woshiwuxiaofei @san346596324 , so.it is a bug or wrong usage?嗨，so.it 错误或用法错误？

Yes, I am under center7 and do not have permission to create the java folder when running this method, so the jar is not actually generated and cannot be run. I now use java -cp to replace it
