### ISSUE TITLE
[Feature][E2E] Setup E2E under JDK 11

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#15267]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pegasas** [comment]
I am interested in this issue and create a PR for fixing it.
feel free to comments if any concern.
