### ISSUE TITLE
[Feature][Failover]Add fault tolerance strategy 

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#15271]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- background:
```
When the master or worker is shut down and started again, the unfinished process instances will be executed from the beginning. but some time i just want that begin from need tolerance

```

- method

```
- restart
- start execution from the task that need tolerance

```

- question

```
Do I need to set this fault tolerance policy parameter to a service level, or do I need to set it to belong to each process definition? I prefer the second one

```

cc  @ruanwenjun @EricGao888 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@fuchanghai 
"When the master or worker is shut down and started again, the unfinished process instances will be executed from the beginning."

Is it how things work on dev branch? I remember that in 3.0.X, when dolphin performs failover for a process instance, it will check whether those task instances need to be failed over or not.

**Comment by EricGao888** [comment]
If as you says, when dolphin performs failover for a process instance, it starts from the very beginning no matter whether some task instances succeeded. It should be a BUG.

**Comment by fuchanghai** [comment]
hi @EricGao888 when restart server ,process instance will be set ```RECOVER_TOLERANCE_FAULT_PROCESS ```
<img width="1368" alt="image" src="https://github.com/apache/dolphinscheduler/assets/33984497/9ecd993a-6a7c-43a2-9c86-d768532d2948">

> The following is the logic of starting from the failure and restoring fault tolerance. The startNodeList is not set for restoring fault tolerance. Is there anything I haven't noticed? Please help me correct it.

<img width="904" alt="image" src="https://github.com/apache/dolphinscheduler/assets/33984497/5340caba-b720-42fa-959b-dead89a2a275">

<img width="1029" alt="image" src="https://github.com/apache/dolphinscheduler/assets/33984497/241ff7f5-c857-4481-9074-6d39dde6818b">
