### ISSUE TITLE
Instance not showing 

### ISSUE THREAD

**Issue by Magale** [apache/dolphinscheduler#15275]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Good day,

I  am new to DolphinScheduler. I created a small workflow that has a simple task in DolphinScheduler 3.2.0. I can run the workflow but the workflow instance does not start after running the workflow. Please help.

Regards 
Magale

### What you expected to happen

The workflow instance should start after running the workflow.

### How to reproduce

Run a workflow to see if the instance starts.

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
Please provide more detail info, something like the master runtime log and worker runtime log
