### ISSUE TITLE
[Bug] [Task] rename task name in task def page, workflow doesn't take effect but duplicate the task.

### ISSUE THREAD

**Issue by alanredsheep** [apache/dolphinscheduler#15285]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

version-3.2.0

Rename task name in task def page, workflow doesn't take effect but duplicate the task.

### What you expected to happen

Rename task name in task def page, workflow should rename this task.

### How to reproduce

1. Rename task name in task def page
2. Open its workflow and find by task name.
3. The original task doesn't rename and a new task with the new name is created.

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by woshiwuxiaofei** [comment]
Can you communicate with me privately?

**Comment by woshiwuxiaofei** [comment]
I'm going to help solve it immediately if this bug does exist.
