### ISSUE TITLE
[Bug] [API] The main package is not available to ordinary users

### ISSUE THREAD

**Issue by Jrebel-i** [apache/dolphinscheduler#15281]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I'm in tag file management, creating a folder for normal users, and uploading the jars, but when I create the project, and try to reference the jars, via /dolphinscheduler/resources/query-by-type?Type = FILE&programType=SCALA 
Return result: {"code":0,"MSG":"success","data":[],"failed": false,"success": true}
![image](https://github.com/apache/dolphinscheduler/assets/62320242/8eea77d0-8e78-4c6f-b921-0e9c05e25f40)
![image](https://github.com/apache/dolphinscheduler/assets/62320242/8d6af608-071c-4b21-bb92-a4f194630b0a)

### What you expected to happen

jar packages of ordinary users can also be displayed normally

### How to reproduce

File management uses s3 as storage, uses a common user to log in, and creates a folder to upload the jar package. When creating a project, the jar package cannot be obtained when invoked

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhaowanpeng** [comment]
这个问题解决了吗
