### ISSUE TITLE
[Bug] [Worker Group] If  All worker is crash In one worker group is crash, then the master submit task Keep trying again, so tasks of the others worker group is in prepare state.

### ISSUE THREAD

**Issue by whitelowrie** [apache/dolphinscheduler#15294]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

If  All worker is crash In one worker group is crash, then the master submit task Keep trying again, so tasks of the others worker group is in prepare state.

### What you expected to happen

 then the master submit task Keep trying again, Other tasks will not be performed

### How to reproduce

just create more than two worker group, and all worker is close in one group, the issue is will be happend

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
I can't understand what you said, can you provide a gif or some pictures to desc the process
