### ISSUE TITLE
[Bug] [api-server] rest api task-definition create task does not bind process

### ISSUE THREAD

**Issue by 344970961** [apache/dolphinscheduler#15296]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

create task via task-definition/save-single api and response is success,but task is not bind with process

### What you expected to happen

process task relation log is created with task code 0,i found this bug in api-server code

### How to reproduce

1. create a new project
2. create a new process with a test task,this step is necessary
3. create another task via rest api task-definition/save-single bind with the process created above step
4. task is created,but not bind with the process

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by woshiwuxiaofei** [comment]
Can you communicate with me privately?

**Comment by 344970961** [comment]
> Can you communicate with me privately?
do you meet the same problem? my email is 344970961@qq.com,you can communicate via email
