### ISSUE TITLE
[Feature][k8s] k8s tasks support allowing users to directly fill in yaml in text format

### ISSUE THREAD

**Issue by fuchanghai** [apache/dolphinscheduler#15301]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Mighten** [comment]
Hello everyone,

I am currently working on this feature to support user-customized Kubernetes YAML tasks. 

This feature is due by September 30, 2024 (the "deadline").

Thank you.
