### ISSUE TITLE
[Question] [Redshift] ClassNotFoundException: com.amazon.redshift.jdbc42.Driver

### ISSUE THREAD

**Issue by onion1984** [apache/dolphinscheduler#15311]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have installed the latest Dolphin scheduler version 3.2 as standalone mode. And I was trying to add AWS redshift as datasource. However, when I test the connection, the test failed. I was able to identify the errors from the log files
<img width="1120" alt="Screenshot 2023-12-13 at 1 06 11 AM" src="https://github.com/apache/dolphinscheduler/assets/16892845/86de34e5-f860-4037-be08-330d0d4e85f6">

### What you expected to happen

The software should be able to support Redshift natively without installing the redshift jdbc driver

### How to reproduce

Install the dolphin scheduler or use the image in AWS marketplace and connect to a redshift cluster

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
You need to download the driver jar and put it into libs dir, the details info you can refer the doc: https://github.com/apache/dolphinscheduler/blob/3.2.0-release/docs/docs/en/guide/howto/datasource-setting.md
