### ISSUE TITLE
How to pass the parameters finally output by the sub-process to the main process

### ISSUE THREAD

**Issue by zhihangv2** [apache/dolphinscheduler#15319]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

子流程最后输出的参数怎么传递到主流程上

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
hi @zhihangv2  you can see https://github.com/apache/dolphinscheduler/pull/15277
