### ISSUE TITLE
[Question]spark sql supports cluster mode

### ISSUE THREAD

**Issue by qiudonglin** [apache/dolphinscheduler#15337]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In version 3.1.7 of Dolphin scheduler, spark task type
What is the reason why spark sql currently does not support cluster mode?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
Would you like to submit a PR to implement it?
