### ISSUE TITLE
Failed to add k8s namespace. k8s operation error [Operation: [list] for kind: [Namespace] with name: [null] in namespace: [null] failed.]

### ISSUE THREAD

**Issue by wangchao732** [apache/dolphinscheduler#15338]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

ds UI 上添加k8s命名空间报错 k8s操作报错[Operation: [list] for kind:    [Namespace] with name: [null] in namespace: [null] failed.]

本地客户端（ds 本地服务器）可以通过kubectl 添加。

### What you expected to happen

k8s操作报错[Operation: [list] for kind:    [Namespace] with name: [null] in namespace: [null] failed.]

### How to reproduce

不太了解哪里问题，你们可以添加测试看看能否复现

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by QuanhanSun** [comment]
I have met the similar problem , you can restart api server after add the cluster info to aviod it.

**Comment by wangchao732** [comment]
I'm glad to hear from you, it's okay to create a namespace in advance after the restart. I'm running into a new issue, Error: Master must start with yarn,spark,mesos, or localRun with --help for usage help or --verbose for debug output 
![Uploading e713f6a16fde1cbd2231659219d82e2.png…]()

**Comment by QuanhanSun** [comment]
During my deployment in k8s, i had not met this problem, you may provide more information for others to help

**Comment by wangchao732** [comment]
> 在我部署 k8s 的过程中，我没有遇到这个问题，您可以提供更多信息供其他人帮助

Thanks
