### ISSUE TITLE
[Bug] [Workflow Definition] [UI] Non-existent resource front ends cannot be culled

### ISSUE THREAD

**Issue by ly109974** [apache/dolphinscheduler#15349]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After a resource is deleted or its name is changed, the resource referenced by the current task node cannot be displayed or deleted. As a result, a message indicating that the resource does not exist is displayed during task running

### What you expected to happen

It should be possible to remove non-existent resource options

### How to reproduce

Select the resource, save the workflow, and go to the resource center to change the reference resource name

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ly109974** [comment]
![image](https://github.com/apache/dolphinscheduler/assets/103415610/1a323613-5fc3-4185-8a37-56055578f45f)
The interface return value existed, because the resource name has been changed, resulting in no content in the selection box; And resources cannot be selected by selecting overlays

**Comment by ly109974** [comment]
The interface return existed value, because the resource name has been changed, resulting in no content in the selection box; And resources cannot be selected by selecting overlays

**Comment by ruanwenjun** [comment]
This is caused the resource metadata doesn't store in database, we can only parse the resource file from task param and display the error message.

**Comment by ly109974** [comment]
But a resource method that can remove incorrect references should be provided
