### ISSUE TITLE
[Bug] [task-hivecli] Unable to read resource files in Hive CLI

### ISSUE THREAD

**Issue by wangbowen1024** [apache/dolphinscheduler#15343]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I get a error, when i use HiveCLI and read SQL from File:
> Caused by: java.io.FileNotFoundException: /tmp/dolphinscheduler320/exec/process/***/11975691665664/11975844729729_4/17/22/hdfs:/***/user/dolphinscheduler320/***/resources/测试/HIVECLI.hql (No such file or directory)

so, i debug the code in IDEA. and then i find some issues from the file path: 
![image](https://github.com/apache/dolphinscheduler/assets/48642743/81c7b3aa-f9d3-4942-aefb-7f214b999a6f)
and then i find a filed:
![image](https://github.com/apache/dolphinscheduler/assets/48642743/b15079d0-1c06-4d2d-a480-181ff79470c4)
so i change the code
![image](https://github.com/apache/dolphinscheduler/assets/48642743/ebf5cabf-9028-4361-aff9-ccee29819170)
and return right path
![image](https://github.com/apache/dolphinscheduler/assets/48642743/96dbbd81-fcb9-4f04-9f82-20c46e0d2d5e)

### What you expected to happen

return right path, just like issue describe

### How to reproduce

every time when use hiveCLI read SQL from file

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
This bug is imported by #12076, right now we will not store data in t_ds_resource, so the resource feature have bug.
