### ISSUE TITLE
[Improvement][Module Name] Improvement title

### ISSUE THREAD

**Issue by q4q5q6qw** [apache/dolphinscheduler#15353]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

关于common.properties中的配置项是否可以使用加密的方式存储，防止敏感信息泄露

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
There is no need to encrypted the properties, if we want to encrypt the properties, we still need to store the encryption key.

**Comment by q4q5q6qw** [comment]
> There is no need to encrypted the properties, if we want to encrypt the properties, we still need to store the encryption key.

那请问下在3.2.0版本我是否可以使用某种类型的加密方式，将密码等密文填写在配置文件中？
