### ISSUE TITLE
[Bug] [Data Quality] JDBC urls with parameters cannot be parsed correctly

### ISSUE THREAD

**Issue by wangbowen1024** [apache/dolphinscheduler#15363]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

i get error when i use DQ task:

> [ERROR] 2023-12-24 01:10:50.748 +0800 - Parse object exception, jsonStr: {"other":"characterEncoding=UTF-8&allowMultiQueries=true&currentSchema=dolphinscheduler320","address":"jdbc:postgresql://IP:PORT","user":"user","password":"***********","database":"db_bigdata","jdbcUrl":"jdbc:postgresql://IP:PORT/db_bigdata"}, class: class org.apache.dolphinscheduler.plugin.datasource.postgresql.param.PostgreSQLConnectionParam
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.LinkedHashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('characterEncoding=UTF-8&allowMultiQueries=true&currentSchema=dolphinscheduler320')
 at [Source: (String)"{"other":"characterEncoding=UTF-8&allowMultiQueries=true&currentSchema=dolphinscheduler320","address":"jdbc:postgresql://IP:PORT","user":"user","password":"*******","database":"db_bigdata","jdbcUrl":"jdbc:postgresql://IP:PORT/db_bigdata"}"; line: 1, column: 10] (through reference chain: org.apache.dolphinscheduler.plugin.datasource.postgresql.param.PostgreSQLConnectionParam["other"])

my ds datasource url is : `jdbc:postgresql://IP:PORT/db_bigdata?characterEncoding=UTF-8&allowMultiQueries=true&currentSchema=dolphinscheduler320`

When the code runs to this position，the 'orher'  value in config is 'characterEncoding=UTF-8&allowMultiQueries=true&currentSchema=dolphinscheduler320' and cannot convert to MAP structure:
![image](https://github.com/apache/dolphinscheduler/assets/48642743/0268b7b4-cd15-4ffb-89d7-8bd69eb9e7db)

### What you expected to happen

no error

### How to reproduce

just like url in 'What happened'

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ChangbinLiu** [comment]
I has the same problem,and how to fix it ?

**Comment by wangbowen1024** [comment]
> I has the same problem,and how to fix it ?

I don't know if that makes sense, you can try temporary handling:
![image](https://github.com/apache/dolphinscheduler/assets/48642743/60464f3a-ff9f-401a-bf36-fd11ab06e600)

**Comment by williamlin88** [comment]
i have the same problem,how to fix it 
![image](https://github.com/user-attachments/assets/6287f589-5ad5-4a82-ab12-c1de0e559966)
