### ISSUE TITLE
[Bug] [SQL Task]Hive jdbc implementation does not support multi SQL sentences within a single PreparedStatement.

### ISSUE THREAD

**Issue by iamcaoxudong** [apache/dolphinscheduler#15373]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Hive jdbc implementation does not support multi SQL sentences within a single PreparedStatement. So if a Hive SQL task contains multiple SQL statement, it will just lead to a syntax error onHive Server2 side.

I also verified the multi-sql-statement with a bare hive jdbc demo, with maven dependency org.apache.hive:hive-jdbc-3.1.3. It produces the same syntax error. So I concluded that the Hive JDBC implementation has not the capability to support multi SQL sentences in one PreparedStatement.

### What you expected to happen

DbType#isSupportMultipleStatement should return false when db type is HIVE.

### How to reproduce

1. Create a simple Hive SQL Task. for example:
![image](https://github.com/apache/dolphinscheduler/assets/50730962/1cb4234f-5137-464f-872c-450b4841a01a)

2. Run this task, then we'll get a syntax error from HiveServer2 side:
![image](https://github.com/apache/dolphinscheduler/assets/50730962/28779833-92c4-495f-a6b1-8bece647a838)

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good job

**Comment by iamcaoxudong** [comment]
I have noticed that in latest dev branch, #15367  has refactored the SQL split function by directly using Alibaba Druid. Therefore DbType#isSupportMultipleStatement has become a no-usages API, should we remove this function now?
