### ISSUE TITLE
[Feature][Module Name] Security: All 0 port listening

### ISSUE THREAD

**Issue by q4q5q6qw** [apache/dolphinscheduler#15372]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

我在start.sh脚本中加入了-Dserver.address=IP
netstat -ntlp查看仅5679加上ip监听端口，5678还是没有，请问这个有配置项可以支撑端口监听吗

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please describe in english.
