### ISSUE TITLE
[Bug] [Python] Getting permission denied when runing python tasks

### ISSUE THREAD

**Issue by syedaqeel** [apache/dolphinscheduler#15387]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Hi, 

We are using dolphin 3.2.0 and python version is 3.10.4 when we run a python task it gives permission denied error. 

![dolphin permission denied on python task ](https://github.com/apache/dolphinscheduler/assets/16229721/b1438a3c-a737-49fd-a42d-dfbc058a1a23)

### What you expected to happen

Python task should be completed

### How to reproduce

Get the same version and run sample python task.

### Anything else

there is a discussion on it as well https://github.com/apache/dolphinscheduler/discussions/15085#discussioncomment-7954036

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liuhen11** [comment]
hi! did you solve it?

**Comment by syedaqeel** [comment]
No, nothing works, still finding solution.

**Comment by liuhen11** [comment]
> No, nothing works, still finding solution.

okay! thanks!

**Comment by ArkURL** [comment]
save problem.

**Comment by liuhen11** [comment]
> save problem.

你好。你指的是？

**Comment by ArkURL** [comment]
> > save problem.
> 
> 你好。你指的是？

以root用户和默认租户运行python节点时同样存在permission deny问题，无法调度python节点。

**Comment by SbloodyS** [comment]
Duplicated with #15085

**Comment by jeanleen** [comment]
PYTHON_HOME is not set.
