### ISSUE TITLE
[Bug] [SQL Task] Clickhouse SQL Task, Caused by: java.sql.SQLException: Prepared statement only supports one query but we got

### ISSUE THREAD

**Issue by luciyu** [apache/dolphinscheduler#15386]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I created a clickhouse SQL task on version 3.2.0 to execute multiple DDL statements, Return error "Prepared statement only supports one query but we got 21" but I did support it on version 3.0.0. Is this feature removed now in version 3.2.0?

### What you expected to happen

I want to execute multiple DDL statements in a clickhouse SQL task.

### How to reproduce

Create clickhouse SQL Task on version 3.2.0 to execute multiple DDL statements.

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
could you share your sql in sql task?

**Comment by sqlboylove** [comment]
我也遇到这个问题了，是还没有修复吗
