### ISSUE TITLE
[Feature][Module Name] Listening on all 0 ports

### ISSUE THREAD

**Issue by q4q5q6qw** [apache/dolphinscheduler#15397]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

After the master server is started, two ports 5678 and 5679 exist. -Dserver.address= is added to the start script, but only the listening IP address of port 5679 is affected. Run the netstat command to check port is still:::5678, and no listening IP address is bound. Is there any configuration that can add port 5678 to listen on?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JueLance** [comment]
Maybe your deployment had some problems. You can change configuration file change another listen port to double check whether master service can listen on that port.
