### ISSUE TITLE
[Bug] [Python Task] task run for a long time without error!

### ISSUE THREAD

**Issue by chyanwu** [apache/dolphinscheduler#15431]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

create python task and execute, but not end!
![0057a992d1816d0713830ebf81b99f1](https://github.com/apache/dolphinscheduler/assets/11313534/8ed0369c-fd8c-482f-aa85-4f7fb23d67c3)

### What you expected to happen

task execute end！

### How to reproduce

detail see image！

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JueLance** [comment]
Base on the log you point out, your python task is starting running. You should check your python task if it takes a long time to execute.
