### ISSUE TITLE
[Feature][Module Name] restfulAPI  connetor as task trigger

### ISSUE THREAD

**Issue by detongz** [apache/dolphinscheduler#15437]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

With all ds connectors, there is not a type that can be triggerd from other http callbacks.
In activepieces, an open source no-code business automation and alternative to Zapier, it supports a http callback connector that can receive http callbacks from other systems. 

https://www.activepieces.com/pieces/http

Dolphinscheduler has good yaml support and api systems, adding a http callback connector is nice.

### Use case

Receive http callbacks and trigger tasks with it.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pegasas** [comment]
it seems part of http trigger the proposal which I am currently work on https://github.com/apache/dolphinscheduler/issues/15330

feel free to correct me if I am wrong.

**Comment by fuchanghai** [comment]
> it seems part of http trigger the proposal which I am currently work on #15330
> 
> feel free to correct me if I am wrong.

hi @pegasas  it seem like , ```detongz``` want add a new task plugin which blocks in the workflow and waits for the third-party's callback  cc @detongz If I've got anything wrong with my explanation, please correct me when you have time.

**Comment by detongz** [comment]
> > it seems part of http trigger the proposal which I am currently work on #15330
> > feel free to correct me if I am wrong.
> 
> hi @pegasas it seem like , `detongz` want add a new task plugin which blocks in the workflow and waits for the third-party's callback cc @detongz If I've got anything wrong with my explanation, please correct me when you have time.

Your explan is what I need.
