### ISSUE TITLE
[Improvement] Slow project list query issue

### ISSUE THREAD

**Issue by chen877511127** [apache/dolphinscheduler#15448]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When t_ds_process_instance table data reaches 300000，Project management list query takes 10 seconds

### What you expected to happen

        select
        <include refid="baseSqlV2">
            <property name="alias" value="p"/>
        </include>
        ,
        u.user_name as user_name,
        (SELECT COUNT(*) FROM t_ds_process_definition AS def WHERE def.project_code = p.code) AS def_count,
        (SELECT COUNT(*) FROM t_ds_process_definition_log def, t_ds_process_instance inst WHERE def.code =
        inst.process_definition_code and def.version = inst.process_definition_version AND def.project_code = p.code
        AND inst.state=1 ) as inst_running_count
        from t_ds_project p
        left join t_ds_user u on u.id=p.user_id
        where 1=1

### How to reproduce

When t_ds_process_instance table data reaches 300000

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chen877511127** [comment]
Version 3.2.0 has been fixed

**Comment by chen877511127** [comment]
3.2.0 version query performance still has issues

**Comment by CallMeKingsley97** [comment]
It looks like the subquery is taking too long. Maybe you could rewrite the sub query. 
For example: change "count (*)" --->  "count(1)"
