### ISSUE TITLE
[Bug] File upload and tenant creation failed

### ISSUE THREAD

**Issue by wllppoo** [apache/dolphinscheduler#15441]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

开启资源上传功能到hdfs，修改common.properties对应参数后报错。
创建租户报错：org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[52] - 创建租户错误 Client cannot authenticate via:[TOKEN, KERBEROS]，
上传文件：to hdfs://**/** 失败,
将resource.hdfs.root.user=hdfs 置空后一切正常使用。发现在之前也有这个问题并提到后续会修复，但我目前遇到的问题应该是没修复

### What you expected to happen

I hope this issue can be fixed. Or tell me if it's my own problem that caused it

### How to reproduce

For a CDH cluster with KRB authentication, after enabling the resource upload function, when resource. hdfs. root. user=hdfs. There were errors in both uploading and creating tenant functions

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lunaelf** [comment]
I am using DolphinScheduler 3.1.9 and it has the same problem.

## api-server logs

```log
[ERROR] 2024-07-15 08:12:18.949 +0000 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[53] - 创建租户错误
java.io.IOException: DestHost:destPort hadoop102:8020 , LocalHost:localPort hadoop102/172.16.96.1:0. Failed on local exception: java.io.IOException: Couldn't set up IO streams: java.lang.IllegalArgumentException: Failed to specify server's Kerberos principal name
        ......
        at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:2304)
        at org.apache.dolphinscheduler.service.storage.impl.HadoopUtils.mkdir(HadoopUtils.java:293)
        at org.apache.dolphinscheduler.service.storage.impl.HadoopUtils.createTenantDirIfNotExists(HadoopUtils.java:268)
        at org.apache.dolphinscheduler.api.service.impl.TenantServiceImpl.createTenant(TenantServiceImpl.java:160)
        at org.apache.dolphinscheduler.api.service.impl.TenantServiceImpl$$FastClassBySpringCGLIB$$fcc8d845.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        .......
```

## common.properties configuration

```properties
# resource storage type: HDFS, S3, OSS, NONE
resource.storage.type=HDFS
# whether to startup kerberos
hadoop.security.authentication.startup.state=true
# java.security.krb5.conf path
java.security.krb5.conf.path=/etc/krb5.conf
# login user from keytab username
login.user.keytab.username=hdfs/hadoop@EXAMPLE.COM
# login user from keytab path
login.user.keytab.path=/etc/security/keytab/hdfs.keytab
# kerberos expire time, the unit is hour
kerberos.expire.time=2
```

## Running environment

DolphinScheduler version: 3.1.9
Hadoop version: 3.3.4
OS: Ubuntu 22.04
