### ISSUE TITLE
[Bug] [Module Name] get wrong ip  

### ISSUE THREAD

**Issue by dulred** [apache/dolphinscheduler#15444]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/apache/dolphinscheduler/assets/89889387/0cfe4ece-507a-41a4-a24d-857f495c2351)
![image](https://github.com/apache/dolphinscheduler/assets/89889387/13f888ed-9ad9-4835-8059-1a9a3bd35eae)
i can ping 192.168.1.222 successlly ，but this application get the last ip 172.31.0.1 , i can't work 
![image](https://github.com/apache/dolphinscheduler/assets/89889387/2bdb7cea-3f45-4b2d-895c-e5eb1106759f)

### What you expected to happen

i want see the content  show 192.168.1.222
![image](https://github.com/apache/dolphinscheduler/assets/89889387/e47aa6a3-58bf-4c09-8f9f-07b104769df4)

### How to reproduce

all operations are deployed according to the official website

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
hi @dulred  you can try to specify network  ``` dolphin.scheduler.network.interface.preferred```
