### ISSUE TITLE
Data source[Doc][Module Name] Documentation bug or improvement

### ISSUE THREAD

**Issue by chineseliu32** [apache/dolphinscheduler#15455]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

dolphinscheduler连接doris数据源时，需要的数据源插件是什么，怎么在dolphinscheduler中使用，为什么直接在可视化界面配置报错。

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
hi @chineseliu32  Please provide error information
