### ISSUE TITLE
[Bug] [sql] Error replacing the clickhousesql task parameter

### ISSUE THREAD

**Issue by liusy-bd** [apache/dolphinscheduler#15457]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Version 3.1.8

Define a global parameter, env=test; Downstream node use replacement; The replacement was unsuccessful at the db position

sql: create database if not exists lht_ods_${env};
![image](https://github.com/apache/dolphinscheduler/assets/69708156/8715f407-7af5-4434-9891-d58ef42ba428)
![image](https://github.com/apache/dolphinscheduler/assets/69708156/197c0de8-3536-488c-98c9-a4ce15336b35)

### What you expected to happen

Parameter replacement out of the problem

### How to reproduce

Set a global parameter and execute a clickhouse sql task. sql is as follows
sql: create database if not exists lht_ods_${env};

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
hi @liusy-bd  i think this not bug , maybe you can replace ```${env} ``` with ``` !{env}```  ,If you need explanation documentation, you can check this pr #15238 ，UT of #15177 can cover this situation cc @zhongjiajie

**Comment by zhongjiajie** [comment]
> hi @liusy-bd i think this not bug , maybe you can replace `${env} ` with ` !{env}` ,If you need explanation documentation, you can check this pr #15238 ，UT of #15177 can cover this situation cc @zhongjiajie

@liusy-bd could you test whether it work or not?

**Comment by liusy-bd** [comment]
> 你好@liusy-bd 我认为这不是 bug，也许你可以替换`${env} `为` !{env}` ，如果你需要解释文档，你可以查看这个 pr #15238，#15177的 UT可以覆盖这种情况 cc@zhongjiajie

Thank you very much! Testing is possible, but there is no explanation and application in the official documentation @zhongjiajie     I searched for a long time。。。

**Comment by fuchanghai** [comment]
> > 你好@liusy-bd 我认为这不是 bug，也许你可以替换`${env} `为` !{env}` ，如果你需要解释文档，你可以查看这个 pr #15238，#15177的 UT可以覆盖这种情况 cc@zhongjiajie
> 
> Thank you very much! Testing is possible, but there is no explanation and application in the official documentation @zhongjiajie I searched for a long time。。。

hi @liusy-bd #15238  will supplement the missing documentation

**Comment by liusy-bd** [comment]
> > > 你好@liusy-bd我认为这不是bug，也许你可以替换`${env} `为` !{env}`，如果你需要解释文档，你可以查看这个 pr #15238，#15177 的 UT 可以覆盖这种情况 cc@zhongjiajie
> > 
> > 
> > 非常感谢！测试是可以的，但是官方文档没有说明和应用@zhongjiajie找了好久。。。
> 
> 你好@liusy-bd #15238 将补充缺失的文档

Well, thanks again
