### ISSUE TITLE
[Bug] [Module Name] task instance host is null

### ISSUE THREAD

**Issue by matianhe3** [apache/dolphinscheduler#15451]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when i run a workflow all task failed. click logs. alert `task instance host is null`

### What you expected to happen

[WARN] 2024-01-10 09:07:09.832 +0800 org.apache.dolphinscheduler.server.worker.task.WorkerHeartBeatTask:[101] - [WorkflowInstance-0][TaskInstance-0] - current cpu load average 0.01 is higher than 1.0 or available memory 0.21994615238246484 is lower than 0.3
[WARN] 2024-01-10 09:07:19.835 +0800 org.apache.dolphinscheduler.server.worker.task.WorkerHeartBeatTask:[101] - [WorkflowInstance-0][TaskInstance-0] - current cpu load average 0.01 is higher than 1.0 or available memory 0.21994615238246484 is lower than 0.3

[WARN] 2024-01-10 09:08:09.870 +0800 org.apache.dolphinscheduler.server.master.dispatch.host.LowerWeightHostManager:[139] - [WorkflowInstance-0][TaskInstance-0] - worker 192.168.16.210:1234 current cpu load average 0.0 is too high or available memory 2.02G is too low
[WARN] 2024-01-10 09:08:09.870 +0800 org.apache.dolphinscheduler.server.master.dispatch.host.LowerWeightHostManager:[139] - [WorkflowInstance-0][TaskInstance-0] - worker 192.168.16.50:1234 current cpu load average 0.0 is too high or available memory 1.68G is too low
[WARN] 2024-01-10 09:08:09.870 +0800 org.apache.dolphinscheduler.server.master.dispatch.host.LowerWeightHostManager:[139] - [WorkflowInstance-0][TaskInstance-0] - worker 192.168.16.212:1234 current cpu load average 0.0 is too high or available memory 2.09G is too low

### How to reproduce

i need ./stop-all.sh and ./start-all.sh everyday. it can works.

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
hi @matianhe3 Did you get an error when you clicked on the log query interface? If this is the case above, an error may have been reported before executing the task. Please check the master's log to see if there is an error.

**Comment by matianhe3** [comment]
I upgraded the memory from 8G to 16G, it seems work.

**Comment by fuchanghai** [comment]
hi @matianhe3 I guess you are using a locally executed task similar to datax. This kind of task consumes the resources of the worker. If the resources are not enough, it will wait for execution. If it is the above problem, you can also solve it by reducing the concurrency of the worker.

**Comment by matianhe3** [comment]
> hi @matianhe3 I guess you are using a locally executed task similar to datax. This kind of task consumes the resources of the worker. If the resources are not enough, it will wait for execution. If it is the above problem, you can also solve it by reducing the concurrency of the worker.

yes, i use seatunnel, thanks.
