### ISSUE TITLE
Is there a problem with the oauth2 configuration document?

### ISSUE THREAD

**Issue by MargeDog** [apache/dolphinscheduler#15454]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

          redirectUri: "http://127.0.0.1:12345/dolphinscheduler/redirect/login/oauth2"
          clientId: ""
          clientSecret: ""
          tokenUri: "https://gitee.com/oauth/token?grant_type=authorization_code"
          userInfoUri: "https://gitee.com/api/v5/user"
          callbackUrl: "http://127.0.0.1:5173/login"
这里的redirectUri是dolphinscheduler的地址，callbackUrl登陆地址配置的是哪里的啊

### Documentation Links

https://dolphinscheduler.apache.org/zh-cn/docs/3.2.0/guide/security/authentication-type

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ghost** [comment]
callbackUrl =  http://127.0.0.1:12345/dolphinscheduler/ui/login

**Comment by hdygxsj** [comment]
> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.
> 
> ### Description
> ```
>       redirectUri: "http://127.0.0.1:12345/dolphinscheduler/redirect/login/oauth2"
>       clientId: ""
>       clientSecret: ""
>       tokenUri: "https://gitee.com/oauth/token?grant_type=authorization_code"
>       userInfoUri: "https://gitee.com/api/v5/user"
>       callbackUrl: "http://127.0.0.1:5173/login"
> ```
> 
> 这里的redirectUri是dolphinscheduler的地址，callbackUrl登陆地址配置的是哪里的啊
> 
> ### Documentation Links
> https://dolphinscheduler.apache.org/zh-cn/docs/3.2.0/guide/security/authentication-type
> 
> ### Are you willing to submit a PR?
> * [ ]  Yes I am willing to submit a PR!
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

How did you configure it？

**Comment by hdygxsj** [comment]
Could you please send me your configuration file to have a look?

**Comment by MargeDog** [comment]
@hdygxsj 这是我的配置，但是跳转登录的时候一直失败，请问配置有问题么，我的迷糊点主要在redirectUri，callbackUrl
          authorizationUri: "http://login.YYY.XXXXX.net/oauth/authorize"
          redirectUri: "http://dolphinscheduler.bi.XXXXX.net/dolphinscheduler/redirect/login/oauth2"
          clientId: "154"
          clientSecret: "xxxxxxxx"
          tokenUri: "http://login..XXX.YYYY.net/api/oauth/token"
          userInfoUri: "http://login.XXX.YYYY.net/api/oauth/userinfo"
          callbackUrl: "http://dolphinscheduler.bi.XXXXXXX.net/dolphinscheduler/ui/login"

**Comment by hdygxsj** [comment]
> @hdygxsj 这是我的配置，但是跳转登录的时候一直失败，请问配置有问题么，我的迷糊点主要在redirectUri，callbackUrl authorizationUri: "http://login.YYY.XXXXX.net/oauth/authorize" redirectUri: "http://dolphinscheduler.bi.XXXXX.net/dolphinscheduler/redirect/login/oauth2" clientId: "154" clientSecret: "xxxxxxxx" tokenUri: "http://login..XXX.YYYY.net/api/oauth/token" userInfoUri: "http://login.XXX.YYYY.net/api/oauth/userinfo" callbackUrl: "http://dolphinscheduler.bi.XXXXXXX.net/dolphinscheduler/ui/login"

Please provide the HTTP request methods required for each OAuth2 API and the corresponding response message formats.

**Comment by ghost** [comment]
Please provide me with your error log

**Comment by yonghen1** [comment]
dolphinscheduler/ui/login?authType=oauth2&error=oauth2%20auth%20error,跳转过程中有没有遇到这个问题？

**Comment by jasgok** [comment]
> dolphinscheduler/ui/login?authType=oauth2&error=oauth2%20auth%20error,跳转过程中有没有遇到这个问题？

可能是取token的请求不兼容，ds取token的post请求secret放在body，其他放到param。而有些认证系统所有请求信息都从body取的


code link: https://github.com/apache/dolphinscheduler/blob/5e2abd7442b8aaf50e7f76e150ab12732c32e362/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/LoginController.java#L232
