### ISSUE TITLE
[Feature][workflow definition] the inter-column spacing for workflow names is not sufficient, leading to cramped and less readable representations.le Name] Feature title

### ISSUE THREAD

**Issue by himper** [apache/dolphinscheduler#15465]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In the current implementation of workflow definition in the system, the inter-column spacing for workflow names is not sufficient, leading to cramped and less readable representations. This issue becomes more apparent when workflows have longer names or when there are numerous workflows defined.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xinxingi** [comment]
It is expected that the column width spacing can be manually adjusted and the displayed field list can be checked by oneself
