### ISSUE TITLE
[Bug] [FLINK STREAM] FLINK STREAM job start failure

### ISSUE THREAD

**Issue by HejiaHo** [apache/dolphinscheduler#15462]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I try to start a flink stream job, but failure."View log" button is disable. And when i use flink task set the same params, it work, but flink stream task not.
![image](https://github.com/apache/dolphinscheduler/assets/1995958/0fdf7add-d4e5-4ce6-b623-8fefd9bdf744)

flink stream task config
![image](https://github.com/apache/dolphinscheduler/assets/1995958/3a7c0146-222a-4670-82b8-0e10bc172642)

Console log:
```
java.lang.NullPointerException: Cannot invoke "org.apache.dolphinscheduler.server.master.runner.execute.DefaultTaskExecuteRunnableFactory.createTaskExecuteRunnable(org.apache.dolphinscheduler.dao.entity.TaskInstance)" because "this.defaultTaskExecuteRunnableFactory" is null
```
![image](https://github.com/apache/dolphinscheduler/assets/1995958/b81dc45f-2f8d-4b73-8cf5-cd1935062c76)

### What you expected to happen

Flink stream task can run.

### How to reproduce

use flink stream task node

### Version

3.2.x

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xbyang18** [comment]
hi,I have encountered the same issue; it appears from looking at the source code that the object 'defaultTaskExecuteRunnableFactory' is not set, could this be a bug in the code? Is anyone aware of this?
