### ISSUE TITLE
[Question][Workflow Definition ]  Could I have a DAG Group function that categories will be  set between different tasks on Workflow Definition ?

### ISSUE THREAD

**Issue by himper** [apache/dolphinscheduler#15464]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Can you expand on the description of the problem?
