### ISSUE TITLE
[Doc][Module Name] The official website blog contributed two articles

### ISSUE THREAD

**Issue by pinkfloyds** [apache/dolphinscheduler#15474]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Documentation Links

 official website blog: https://dolphinscheduler.apache.org/zh-cn/blog
 Issue documentation and resolution of the Apache DolphinScheduler upgrade from 1.3.4 to 3.1.2: https://mp.weixin.qq.com/s/PWo5EC0Alf2tA5oxzr_gdA

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good job, can you submit an PR to `dolphinscheduler-website` repository , you can refer the PR like this https://github.com/apache/dolphinscheduler-website/pull/942

**Comment by pinkfloyds** [comment]
very thank you,this is PR https://github.com/apache/dolphinscheduler-website/pull/943
