### ISSUE TITLE
[Improvement]–[Api]Rename the vo object suffix to VO

### ISSUE THREAD

**Issue by silenceland** [apache/dolphinscheduler#15489]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

hi, I found that some vo object naming suffixes under the api module end with Vo, such as ScheduleVo, TaskDefinitionVo, and so on, which is not in line with the specification. I want to submit this issue to unify the naming methods of these objects, end with VO.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
+1.
Look forward to your PR.

**Comment by silenceland** [comment]
> +1. Look forward to your PR.

thx, the pr #15504 submitted
