### ISSUE TITLE
[Bug] [upgrade] I have no data on the task instance page after upgrading from 1.3.4 to 3.1.x

### ISSUE THREAD

**Issue by pinkfloyds** [apache/dolphinscheduler#15497]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have no data on the task instance page after upgrading from 1.3.4 to 3.1.x

### What you expected to happen

after debugging, t_ds_task_instance. task_definition_version=0 and t_ds_task_definition_log. version=1 cannot be joined.

### How to reproduce

After executing the task, upgrade from 1.3.x to 3.1.x according to the official documentation.

### Anything else

I have resolved this issue and need to modify the update script to change t_ds_task_instance.task_definition_version default to 1 .

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
We may need to set the version in t_ds_task_definition_log begin at '0'?

**Comment by pinkfloyds** [comment]
set the version in t_ds_task_definition_log begin at '0' also works , but the data version=0 in the table is not reasonable，the version should begin at '1'.

**Comment by ruanwenjun** [comment]
> set the version in t_ds_task_definition_log begin at '0' also works , but the data version=0 in the table is not reasonable，the version should begin at '1'.

`t_ds_task_definition_log` contains all data in `t_ds_task_definition`, so it should contain version `0`.

**Comment by ruanwenjun** [comment]
closed by #15498
