### ISSUE TITLE
[Bug] [dolphinscheduler-api-->K8sNamespaceController-->createK8sNamespace] create namespace, if not exist on k8s,will don't create

### ISSUE THREAD

**Issue by hugh018** [apache/dolphinscheduler#15491]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

k8s操作报错[namespace dev_now does not exist in k8s cluster, please create namespace in k8s cluster first].
method createK8sNamespace notes： create namespace,if not exist on k8s,will create,if exist only register in db，but this method **don't** create on k8s when not exist on k8s.

### What you expected to happen

create namespace,if not exist on k8s,**will create on k8s**,if exist only register in db

### How to reproduce

ui create namespace dev-xx when  not exist on k8s

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Gallardot** [comment]
This is not a bug, it's designed this way, dolphinscheduler should not take on too much of the work managing k8s cluster.Users need to create namespaces on the k8s cluster themselves.You can browse previous issues and PRs.

**Comment by fuchanghai** [comment]
> This is not a bug, it's designed this way, dolphinscheduler should not take on too much of the work managing k8s cluster.Users need to create namespaces on the k8s cluster themselves.You can browse previous issues and PRs.

agree with @Gallardot

**Comment by hugh018** [comment]
@fuchanghai 3.2 version change code logic, but annotation no change. 【create namespace,if not exist on k8s,will create,if exist only register in db】. if not exist on k8s,will create?
    /**
     * create namespace,if not exist on k8s,will create,if exist only register in db
     *
     * @param loginUser
     * @param namespace    k8s namespace
     * @param clusterCode  clusterCode
     * @param limitsCpu    max cpu
     * @param limitsMemory max memory
     * @return
     */
    @Operation(summary = "createK8sNamespace", description = "CREATE_NAMESPACE_NOTES")

**Comment by Gallardot** [comment]
> @fuchanghai 3.2 version change code logic, but annotation no change. 【create namespace,if not exist on k8s,will create,if exist only register in db】. if not exist on k8s,will create?
> /**
> * create namespace,if not exist on k8s,will create,if exist only register in db
> *
> * @param loginUser
> * @param namespace k8s namespace
> * @param clusterCode clusterCode
> * @param limitsCpu max cpu
> * @param limitsMemory max memory
> * @return
> */
> @operation(summary = "createK8sNamespace", description = "CREATE_NAMESPACE_NOTES")


@hugh018 
Good catch! Welcome to create a PR to fix it.
