### ISSUE TITLE
[Bug] [Master] The subworkflow is executed twice

### ISSUE THREAD

**Issue by stephenking30** [apache/dolphinscheduler#15495]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The sub-workflows were executed twice. The query log found that two identical workflows were created, commandId and processInstanceId were different, resulting in the task instances being executed repeatedly

### What you expected to happen

I want to do it only once

### How to reproduce

This is an accidental occurrence, not easy to reappear

### Anything else

the version is 3.1.0

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Could you provide the master log? And how to reproduce this bug.

**Comment by stephenking30** [comment]
> Could you provide the master log? And how to reproduce this bug.

sorry, because this happened accidentally, it cannot be repeated at present. Due to a long period of time, the detail log of this master has been cleared, and I can provide some previous materials，The log shows two commands that create the same content
![子任务工作流重复生成](https://github.com/apache/dolphinscheduler/assets/49178724/b3376a36-927b-434b-827f-09993078bc20)

**Comment by LinYuHeng-Con** [comment]
https://github.com/apache/dolphinscheduler/issues/15323  
Can you confirm if it's a similar issue?

**Comment by stephenking30** [comment]
> #15323
> Can you confirm if it's a similar issue?

Thank you for your comments.I have read your description of the problem, because I am using mysql now, and this problem still occurs occasionally. I think it has nothing to do with the database. As for the transaction problem, I cannot verify it yet.If you have any new progress, I hope you will let me know.
