### ISSUE TITLE
After I upgraded from 3.1.8 to 3.2.0, I could not find the workflow instance after creating tasks in the workflow definition and clicking Run.

### ISSUE THREAD

**Issue by 1498658503** [apache/dolphinscheduler#15494]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After I upgraded from 3.1.8 to 3.2.0, I could not find the workflow instance after creating tasks in the workflow definition and clicking "run". I checked the database table, and found that a data was inserted into the t_ds_process_instance table, but the project_code was null. Moreover, the task instance of the task I created in 3.1.8 had the same project_code, which could not be found.
![Snipaste_2024-01-16_16-57-14](https://github.com/apache/dolphinscheduler/assets/52768629/e4df03b1-7def-4bdb-85f9-9c887101da42)
![Snipaste_2024-01-16_16-57-42](https://github.com/apache/dolphinscheduler/assets/52768629/ef49b952-2326-4eea-91f5-490392d2e714)

### What you expected to happen

Clicking Run will show that the foreground is successful, and the background will not report an error. When I upgraded, I executed the upgraded ddl and dml sql scripts, and also tried to rebuild the database, but this situation still exists

### How to reproduce

1

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 1498658503** [comment]
![image](https://github.com/apache/dolphinscheduler/assets/52768629/4a81616a-74d8-4901-a1cb-5147bafa34c1)

**Comment by ruanwenjun** [comment]
Have you execute the upgrade tools? In 3.2.0 we add a new column `project_code` in `t_ds_process_instance`.

**Comment by samael0119** [comment]
类似的问题，我用helm安装了全新的3.2.0版本后，运行一个工作流提示成功，但是实例列表没内容
![image](https://github.com/apache/dolphinscheduler/assets/55143424/4ddf76fe-cc96-4729-ab09-b785f4798123)
![image](https://github.com/apache/dolphinscheduler/assets/55143424/28de35e5-87a5-4b00-aeae-ab0b545b798d)

**Comment by 1498658503** [comment]
> Have you execute the upgrade tools? In 3.2.0 we add a new column `project_code` in `t_ds_process_instance`.

t_ds_process_instance already has a `project_code` field, but there is no new instance data in the table.

**Comment by truonglac2603** [comment]
> 类似的问题，我用helm安装了全新的3.2.0版本后，运行一个工作流提示成功，但是实例列表没内容 ![image](https://private-user-images.githubusercontent.com/55143424/297680892-4ddf76fe-cc96-4729-ab09-b785f4798123.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTQyMDQsIm5iZiI6MTcwNTY1MzkwNCwicGF0aCI6Ii81NTE0MzQyNC8yOTc2ODA4OTItNGRkZjc2ZmUtY2M5Ni00NzI5LWFiMDktYjc4NWY0Nzk4MTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA4NDUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMDA4ZGU4OGU5MjJhNWZjZWZjZTA1OGJhMzI3MTI1NGRiODA0ZGVjNTlhMjM0OWY2Njc4ZTFmMDIwNDcwMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R9f_pEhM6wgU5Uvj59pprl43IKAkaKnJuwvrDY2TW2g) ![image](https://private-user-images.githubusercontent.com/55143424/297680941-28de35e5-87a5-4b00-aeae-ab0b545b798d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTQyMDQsIm5iZiI6MTcwNTY1MzkwNCwicGF0aCI6Ii81NTE0MzQyNC8yOTc2ODA5NDEtMjhkZTM1ZTUtODdhNS00YjAwLWFlYWUtYWIwYjU0NWI3OThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA4NDUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhOTY3MDUyNDVjYzVhZDUyM2MyN2U1NTMzN2E4Y2RkNzU5YmQzN2U0OTMwNmIyOGRjNGNhMDYxMzBiNDA5ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SHjcW81Go3fvyIA2cxxWf0_CjtVu90jgA1Nz_5YdQkE)

facing the same issue, if you check the log of workers, there may be errors indicate that current cpu load average is overload or available memory is insufficient. Related to this discussion: [https://github.com/apache/dolphinscheduler/discussions/15047#discussion-5752268](url)

**Comment by Smilewh888** [comment]
Why can't I find the execution result in the task instance?
![image](https://github.com/apache/dolphinscheduler/assets/75770940/e5e24a94-f7b1-4b2f-bbeb-77ef48b6defc)

![image](https://github.com/apache/dolphinscheduler/assets/75770940/1d3f0a56-3621-48e8-99e2-24428d0e977b)

Is this the root of the problem? How to solve it?

<img width="1416" alt="image" src="https://github.com/apache/dolphinscheduler/assets/75770940/9b193590-715e-48bd-ae57-90bad4d15d49">

<img width="1455" alt="image" src="https://github.com/apache/dolphinscheduler/assets/75770940/f5e48f8b-9355-4a1f-b9e6-e9b62dc0be22">

**Comment by Smilewh888** [comment]
> > 类似的问题，我用helm安装了全新的3.2.0版本后，运行一个工作流提示成功，但是实例列表没内容 ![image](https://private-user-images.githubusercontent.com/55143424/297680892-4ddf76fe-cc96-4729-ab09-b785f4798123.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTQyMDQsIm5iZiI6MTcwNTY1MzkwNCwicGF0aCI6Ii81NTE0MzQyNC8yOTc2ODA4OTItNGRkZjc2ZmUtY2M5Ni00NzI5LWFiMDktYjc4NWY0Nzk4MTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA4NDUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMDA4ZGU4OGU5MjJhNWZjZWZjZTA1OGJhMzI3MTI1NGRiODA0ZGVjNTlhMjM0OWY2Njc4ZTFmMDIwNDcwMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R9f_pEhM6wgU5Uvj59pprl43IKAkaKnJuwvrDY2TW2g) ![image](https://private-user-images.githubusercontent.com/55143424/297680941-28de35e5-87a5-4b00-aeae-ab0b545b798d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTQyMDQsIm5iZiI6MTcwNTY1MzkwNCwicGF0aCI6Ii81NTE0MzQyNC8yOTc2ODA5NDEtMjhkZTM1ZTUtODdhNS00YjAwLWFlYWUtYWIwYjU0NWI3OThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA4NDUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhOTY3MDUyNDVjYzVhZDUyM2MyN2U1NTMzN2E4Y2RkNzU5YmQzN2U0OTMwNmIyOGRjNGNhMDYxMzBiNDA5ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SHjcW81Go3fvyIA2cxxWf0_CjtVu90jgA1Nz_5YdQkE)
> 
> facing the same issue, if you check the log of workers, there may be errors indicate that current cpu load average is overload or available memory is insufficient. Related to this discussion: [https://github.com/apache/dolphinscheduler/discussions/15047#discussion-5752268](url)

https://github.com/apache/dolphinscheduler/issues/15494#issuecomment-1992100746
