### ISSUE TITLE
[Doc][Version Release Document]Why is there no version release documentation?

### ISSUE THREAD

**Issue by dzygoon** [apache/dolphinscheduler#15502]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

How do I know what issues are fixed with each release? To decide whether I want to upgrade the ds version or not?

### Documentation Links

none

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You can find it in https://github.com/apache/dolphinscheduler/releases.

**Comment by dzygoon** [comment]
> You can find it in https://github.com/apache/dolphinscheduler/releases.

thanks.

**Comment by dzygoon** [comment]
> You can find it in https://github.com/apache/dolphinscheduler/releases.

Hi.I see that version 3.2.0 has been released, but there is no description of version 3.2.0 in this link.When will it be updated?
