### ISSUE TITLE
[Bug] [Seatunnel cdc]Can not really stop seatunnel cdc job

### ISSUE THREAD

**Issue by dzygoon** [apache/dolphinscheduler#15503]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I configure a seatunnel mysqlcdc task using ds, I can't really stop the task on the task instance page. Although the ds page shows that the task has stopped.
I see the same question：https://github.com/apache/dolphinscheduler/issues/14222
I wonder when this problem can be solved?At present, I can only find the version 3.1.9 release document, has the 3.2.0 version solved this problem?

### What you expected to happen

fix it.

### How to reproduce

build seatunnel cdc task.used seatunnel zeta engine.

### Anything else

ds version = 3.1.7
st version = 2.3.3
st zeta engine

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
3.2.0 didn't solve this.

**Comment by dzygoon** [comment]
> 3.2.0 didn't solve this.

When plan to fix it? This Bug is important!
