### ISSUE TITLE
ASF website checks error

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#15505]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Some of the dolphinscheduler website checks is failed because we do not have specific text or links in our homepage, the check rule and result as this link https://whimsy.apache.org/site/project/dolphinscheduler. Our homepage source code is simple and does not have too much content, which we can see below.

We should find some way and expose all the needs for the ASF check

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <link rel="icon" href="/favicon.ico"/>
    <meta name="viewport" content="width=device-width,initial-scale=1"/>
    <meta name="theme-color" content="#000000"/>
    <meta name="description" content="Apache DolphinScheduler is a distributed and extensible open-source workflow orchestration platform with powerful DAG visual interfaces."/>
    <meta name="keywords" content="apache dolphinscheduler,dolphinscheduler,document,community,workflow scheduler,data orchestration,workflow orchestration,drag and drop workflow,DAG"/>
    <link rel="apple-touch-icon" href="/logo192.png"/>
    <link rel="manifest" href="/manifest.json"/>
    <link rel="stylesheet" href="/highlight.min.css"/>
    <title>Apache DolphinScheduler</title>
    <script defer="defer" src="/static/js/main.0e8e475b.js"></script>
    <link href="/static/css/main.3611ca99.css" rel="stylesheet">
</head>
<body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
    <script>
    var _hmt = _hmt || [];
    !function() {
        var e = document.createElement("script");
        e.src = "https://hm.baidu.com/hm.js?d6bc736fd9885d9a5dc938425ac062ad";
        var t = document.getElementsByTagName("script")[0];
        t.parentNode.insertBefore(e, t)
    }()
    </script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-899J8PYKJZ"></script>
    <script>
    function gtag() {
        dataLayer.push(arguments)
    }
    window.dataLayer = window.dataLayer || [],
    gtag("js", new Date),
    gtag("config", "G-899J8PYKJZ")
    </script>
</body>
</html>
```

We find that seatunnel website is good, which we can see in https://whimsy.apache.org/site/project/seatunnel, and all the keywords of is exist in they page source code https://seatunnel.apache.org

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Resources issue for https://whimsy.apache.org/site/project/dolphinscheduler is solved

**Comment by ruanwenjun** [comment]
Closed by https://github.com/apache/dolphinscheduler-website/pull/944

**Comment by zhongjiajie** [comment]
This issue still not complete fix yet, @devosend would do the others work ❤️
