### ISSUE TITLE
[Improvement][Workflow Defintion] Workflow classification

### ISSUE THREAD

**Issue by hwfbest** [apache/dolphinscheduler#15518]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

同一个项目下任务分类问题：
1、任务比较多时任务不容易查找，是否可以增加文件夹路径，对任务做自定义分类；
2、hera调度系统中按照树的方式来定义大小文件夹，大文件夹下只能是目录，小文件夹下只能是工作流；
参照网址：https://scx-white.blog.csdn.net/article/details/102571798
![20191030172436777](https://github.com/apache/dolphinscheduler/assets/16427578/6e40b074-e932-48e0-a4f7-54c1791e8546)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rickchengx** [comment]
@hwfbest please describe your issue in English. Using directory organization for workflow is a relatively big change. It is recommended to give your design on the mailing list.
