### ISSUE TITLE
[Bug] [datax] Dolphinscheduler3.2.0 version, datax component failed when using global variables

### ISSUE THREAD

**Issue by zhouyun0242** [apache/dolphinscheduler#15519]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

First, create a workflow and create a datax task within the workflow. The SQL defined in the datax task is as follows:

`Select * from table where to_ Char (create-time, 'yyyy MM dd hh24: MI')>='${biz_start_time}' and to_ Char (create-time,'yyyy MM dd hh24: MI ')<='${biz_end_time}'`

Finally, save the workflow and add biz_ Start_ Time and Biz_ End_ Time is the global variable for this workflow.

Run this workflow for biz_ Start_ Time and Biz_ End_ Time assignment. The workflow failed to run as a result, and the log indicates that there is an issue with the datax running statement. The log is as follows:

> ${PYTHON_LAUNCHER} ${DATAX_LAUNCHER} --jvm="-Xms1G -Xmx1G" -p "-Dsystem.task.definition.name='datax-test' -Dsystem.project.name='null' -Dsystem.biz.curdate='20240122' -Dsystem.task.instance.id='1' -DStartParams='{"biz_start_time":"2024-01-03 18:56","biz_end_time":"2024-01-03 18:57"}' -Dsystem.task.definition.code='12350595021984' -Dsystem.datetime='20240122183205' -Dbiz_end_time='2024-01-03 18:57' -Dbiz_start_time='2024-01-03 18:56' -Dsystem.project.code='12350591796128' -Dsystem.workflow.instance.id='1' -Dsystem.biz.date='20240121' -Dsystem.workflow.definition.name='test工作流' -Dsystem.workflow.definition.code='12350605116448'" /tmp/dolphinscheduler/exec/process/default/12350591796128/12350605116448_2/1/1/1_1_job.json
[INFO] 2024-01-22 18:32:05.696 +0800 - Executing shell command : sudo -u root -i /tmp/dolphinscheduler/exec/process/default/12350591796128/12350605116448_2/1/1/1_1.sh
[INFO] 2024-01-22 18:32:05.701 +0800 - process start, process id is: 14195
[INFO] 2024-01-22 18:32:06.701 +0800 -  -> 
	
	DataX (DATAX-OPENSOURCE-3.0), From Alibaba !
	Copyright (C) 2010-2017, Alibaba Group. All Rights Reserved.
	
	
	Usage: datax.py [options] job-url-or-path
	
	Options:
	  -h, --help            show this help message and exit
	
	  Product Env Options:
	    Normal user use these options to set jvm parameters, job runtime mode
	    etc. Make sure these options can be used in Product Env.
	
	    -j <jvm parameters>, --jvm=<jvm parameters>
	                        Set jvm parameters if necessary.
	    --jobid=<job unique id>
	                        Set job unique id when running by Distribute/Local
	                        Mode.
	    -m <job runtime mode>, --mode=<job runtime mode>
	                        Set job runtime mode such as: standalone, local,
	                        distribute. Default mode is standalone.
	    -p <parameter used in job config>, --params=<parameter used in job config>
	                        Set job parameter, eg: the source tableName you want
	                        to set it by command, then you can use like this:
	                        -p"-DtableName=your-table-name", if you have mutiple
	                        parameters: -p"-DtableName=your-table-name
	                        -DcolumnName=your-column-name".Note: you should config
	                        in you job tableName with ${tableName}.
	    -r <parameter used in view job config[reader] template>, --reader=<parameter used in view job config[reader] template>
	                        View job config[reader] template, eg:
	                        mysqlreader,streamreader
	    -w <parameter used in view job config[writer] template>, --writer=<parameter used in view job config[writer] template>
	                        View job config[writer] template, eg:
	                        mysqlwriter,streamwriter
	
	  Develop/Debug Options:
	    Developer use these options to trace more details of DataX.
	
	    -d, --debug         Set to remote debug mode.
	    --loglevel=<log level>
	                        Set log level such as: debug, info, all etc.
[INFO] 2024-01-22 18:32:06.703 +0800 - process has exited. execute path:/tmp/dolphinscheduler/exec/process/default/12350591796128/12350605116448_2/1/1, 
processId:14195 ,exitStatusCode:255 ,processWaitForStatus:true ,processExitValue:255

### What you expected to happen

I hope this workflow can run successfully and datax can extract data normally.

Important note: After testing, the stable version of v3.1.9 does not have this issue.

### How to reproduce

Deploy Dolphinscheduler 3.2.0 standalone version, create a new workflow, add a datax component under the workflow, define global variables for the workflow, and then run the workflow to reproduce the problem.

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhouyun0242** [comment]
I personally suspect that the reason is due to compatibility issues with the following datax runtime statements generated by dolphinscheduler3.2.0:

`${PYTHON_LAUNCHER} ${DATAX_LAUNCHER} --jvm="-Xms1G -Xmx1G" -p "-Dsystem.task.definition.name='datax-test' -Dsystem.project.name='null' -Dsystem.biz.curdate='20240122' -Dsystem.task.instance.id='1' -DStartParams='{"biz_start_time":"2024-01-03 18:56","biz_end_time":"2024-01-03 18:57"}' -Dsystem.task.definition.code='12350595021984' -Dsystem.datetime='20240122183205' -Dbiz_end_time='2024-01-03 18:57' -Dbiz_start_time='2024-01-03 18:56' -Dsystem.project.code='12350591796128' -Dsystem.workflow.instance.id='1' -Dsystem.biz.date='20240121' -Dsystem.workflow.definition.name='test工作流' -Dsystem.workflow.definition.code='12350605116448'" /tmp/dolphinscheduler/exec/process/default/12350591796128/12350605116448_2/1/1/1_1_job.json`

After testing, removing the parameter - DStartParams={"biz_starttime": "2024-01-03 18:56", "biz_end_time": "2024-01-03 18:57"} ', datax can run successfully. Is it possible that datax does not support parameter values for JSON strings?

**Comment by jnfJNF** [comment]
我也遇到过，好像要配置${PYTHON_LAUNCHER} ${DATAX_LAUNCHER}就好了

**Comment by zhouyun0242** [comment]
> 我也遇到过，好像要配置${PYTHON_LAUNCHER} ${DATAX_LAUNCHER}就好了

3.2.0版本中，在dolphinscheduler_env.sh中配置PYTHON_LAUNCHER和DATAX_LAUNCHER会导致datax组件无法运行。issue里有大佬试出了解决办法：就是dolphinscheduler_env.sh中不配置PYTHON_LAUNCHER和DATAX_LAUNCHER，在/etc/profile中配置PYTHON_LAUNCHER和DATAX_LAUNCHER
另外，我也尝试过使用dolphinscheduler的环境变量功能，把PYTHON_LAUNCHER和DATAX_LAUNCHER配置到环境变量里。但是好像也没啥用。

**Comment by GaoXSen** [comment]
I have also encountered similar problems. Just configure ${PYTHON_LAUNCHER} ${DATAX_LAUNCHER} in the project environment variables. But why do we need to configure these two default variables in 3.2.0?

**Comment by GaoXSen** [comment]
我也遇到过类似问题，将${PYTHON_LAUNCHER} ${DATAX_LAUNCHER}配置在项目环境变量里就可以了。但是为什么在3.2.0中需要配置这两个默认变量呢？

**Comment by zhouyun0242** [comment]
> 我也遇到过类似问题，将${PYTHON_LAUNCHER} ${DATAX_LAUNCHER}配置在项目环境变量里就可以了。但是为什么在3.2.0中需要配置这两个默认变量呢？

好的，我用环境变量配置${PYTHON_LAUNCHER} ${DATAX_LAUNCHER}试试！

**Comment by Guohao1020** [comment]
- Sure enough, the variable `${PYTHON_LAUNCHER}` `${DATAX_LAUNCHER}` is configured to /etc/profile to run Datax

- 果然，将变量`${PYTHON_LAUNCHER} ${DATAX_LAUNCHER}`配置到/etc/profile就可以正常运行Datax了

**Comment by xiaomi-box** [comment]
dolphinscheduler 3.2.1
Global parameters do not take effect, and the time of each task instance is different. Is it a bug
