### ISSUE TITLE
[Bug] [CI] 3.1.8 download failed

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#15524]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The link of https://dlcdn.apache.org/dolphinscheduler/3.1.8/apache-dolphinscheduler-3.1.8-bin.tar.gz is 404.
<img width="1110" alt="image" src="https://github.com/apache/dolphinscheduler/assets/22415594/abf6b557-e957-4f12-8cfa-f5dc1808844e">

<img width="1088" alt="image" src="https://github.com/apache/dolphinscheduler/assets/22415594/da219928-55ab-462b-839a-b6ee72e2b3db">

### What you expected to happen

xx

### How to reproduce

xx

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pegasas** [comment]
Hi, @ruanwenjun , 
Hope you are well.
I would like to fix this bug and open a PR for fixing this based on my limit knowledge.

**Comment by fuchanghai** [comment]
> Hi, @ruanwenjun , Hope you are well. I would like to fix this bug and open a PR for fixing this based on my limit knowledge.

hi @pegasas  This is a high priority bug that blocks some CI operations, so someone made a hot fix

**Comment by pegasas** [comment]
> > Hi, @ruanwenjun , Hope you are well. I would like to fix this bug and open a PR for fixing this based on my limit knowledge.
> 
> hi @pegasas This is a high priority bug that blocks some CI operations, so someone made a hot fix

sure.
Also thanks for clarification
