### ISSUE TITLE
[Bug] [Module Name] Bug title 3.2.0 When starting the workflow instance, an error is reported: The task instance host is empty

### ISSUE THREAD

**Issue by liubo988** [apache/dolphinscheduler#15527]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![企业微信截图_17062616355661](https://github.com/apache/dolphinscheduler/assets/17637421/541e5822-6272-44ac-bb66-1f991b12e92c)
![企业微信截图_17062616593426](https://github.com/apache/dolphinscheduler/assets/17637421/c4c759f2-0409-42ba-9500-1bc67d0400fa)

### What you expected to happen

跑着跑着就这样了，希望给出具体说明，为什么host实例为空，说明问题造成的，怎么解决？

### How to reproduce

222

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
could you share more detail log for master server?
