### ISSUE TITLE
[Bug] [Metrics] the api server metrics do not work 

### ISSUE THREAD

**Issue by zui01** [apache/dolphinscheduler#15542]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

i fllow the doc from https://dolphinscheduler.apache.org/zh-cn/docs/3.2.0/guide/metrics/metrics#%E9%85%8D%E7%BD%AE
and  test all the metrics,the master and worker，alter server ‘s metrics are fine，but api return 404
i deploy 3.2.0 in cluster modle
<img width="901" alt="image" src="https://github.com/apache/dolphinscheduler/assets/54675044/75c93ec5-9f5e-43cb-b0a0-7877248d0bcb">

### What you expected to happen

i think the api server metrics should work as other server as well

### How to reproduce

just curl api server port and add some url path like 
curl http://localhost:12345/actuator/prometheus

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Gallardot** [comment]
api-server prometheus path is `/dolphinscheduler/actuator/prometheus`
