### ISSUE TITLE
[Bug] [API&MASTER]  3.2.0 The restart of MySQL 5.7 can cause an Auto Increment ID reset, potentially resulting in the inability to execute command.

### ISSUE THREAD

**Issue by Zzih** [apache/dolphinscheduler#15543]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When calling the`startProcessInstance` API `(/executors/start-process-instance)`, no workflow instance is generated. Upon checking the dolphinscheduler-master log, I found the following Exception:
<img width="1906" alt="image" src="https://github.com/apache/dolphinscheduler/assets/158246610/4addbba7-0097-4f95-a937-90fa9585b020">

I found that https://github.com/apache/dolphinscheduler/pull/13184 added the method `queryByTypeAndJobId` and the table` t_ds_trigger_relation`. In the `t_ds_trigger_relation` table, the `job_id` corresponds to the `id` in the `t_ds_command` table.

When MySQL 5.7 is restarted, it will reset the auto-increment ID of the`t_ds_command` table. This will lead to duplicated`job_id` entries in the`t_ds_trigger_relation` table. Subsequently, when querying using the`queryByTypeAndJobId` method, an error message may occur:` 'Expected one result (or null) to be returned by selectOne(), but found: 2'`.
<img width="1750" alt="image" src="https://github.com/apache/dolphinscheduler/assets/158246610/a8fd0969-ba87-430a-88dc-435561f9b589">

The job_id in the `t_ds_trigger_relation` table has already exceeded 7000.
<img width="1017" alt="image" src="https://github.com/apache/dolphinscheduler/assets/158246610/9e4f5084-17d4-4299-b279-a862de5dfa29">
the auto-increment ID of the`t_ds_command` table has become 418.
<img width="475" alt="image" src="https://github.com/apache/dolphinscheduler/assets/158246610/c49cd7ec-8efa-4379-af8e-fa35f35293ca">

Similarly,`t_ds_error_command` cannot be inserted.

### What you expected to happen

I think I can add a 'code' field to the 't_ds_command' table, and then establish associations with other tables using this 'code' field.is there any other better way?

### How to reproduce

restart mysql.exec process.

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liukunyuan** [comment]
I think add a code field would be better

**Comment by Zzih** [comment]
> I think add a code field would be better

I noticed that the `job_id` field in the `t_ds_trigger_relation` table also holds the `id` field from the `t_ds_process_instance` table. If I add a `code` field to the `t_ds_command` table, should I also add a `code` field to the `t_ds_process_instance` table for association? This change may have significant implications, so I believe it warrants further discussion.
<img width="762" alt="image" src="https://github.com/apache/dolphinscheduler/assets/158246610/e9c8c802-7d7e-4678-9961-e10f96bd54eb">
