### ISSUE TITLE
[Bug] [V3.2.0] Scheduling tasks using "local" files uploaded from the Resource Center

### ISSUE THREAD

**Issue by VENSCC** [apache/dolphinscheduler#15547]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![c41c091b9dc198ff9195c6aae086b69](https://github.com/apache/dolphinscheduler/assets/16875150/9de5edc4-e4d4-4c7b-bdcc-fad39c3f367c)
![579226eb9e7681a8f9688fa8f52864b](https://github.com/apache/dolphinscheduler/assets/16875150/e20b3c39-de04-434c-ac47-edae64d07251)

when copy the target resource file to exec path, create the error subpath! just like that

### What you expected to happen

use "resource.storage.type=LOCAL"

download the resource file to the exec path without the "absolute file path"

### How to reproduce

1、"resource.storage.type=LOCAL"
2、shell task
3、use the resource file

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by VENSCC** [comment]
![image](https://github.com/apache/dolphinscheduler/assets/16875150/d97bd7a0-803e-4570-89fb-2d6570febfc1)

**Comment by git-blame** [comment]
This is probably same problem as #15236 See comment (https://github.com/apache/dolphinscheduler/issues/15236#issuecomment-1919171845)
