### ISSUE TITLE
[Doc][guide/task] [BUG]The images in the official website document cannot display large images

### ISSUE THREAD

**Issue by wjcwin** [apache/dolphinscheduler#15555]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The images in the official website document cannot display large images

### Documentation Links

https://dolphinscheduler.apache.org/zh-cn/docs/3.2.0/guide/task/spark

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rickchengx** [comment]
The doc link seems to be fine, the images could be loaded.

**Comment by wjcwin** [comment]
> The doc link seems to be fine, the images could be loaded.

cannot double click the mouse to enlarge the image
