### ISSUE TITLE
The format of the sql statement prevents the workflow from being saved

### ISSUE THREAD

**Issue by Best1055** [apache/dolphinscheduler#15559]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

在集群模式下，我的sql格式的空格，导致工作流无法保存，但是standalone模式却可以

### What you expected to happen

在集群模式下，我的sql格式的空格，导致工作流无法保存，但是standalone模式却可以

### How to reproduce

在集群模式下，我的sql格式的空格，导致工作流无法保存，但是standalone模式却可以

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Best1055** [comment]
<img width="1096" alt="企业微信截图_17070371803051" src="https://github.com/apache/dolphinscheduler/assets/134610552/5a28bfe4-c310-4d2a-befb-416a09b9f2a6">
这个是不可以保存的

**Comment by Best1055** [comment]
<img width="685" alt="企业微信截图_17070374395323" src="https://github.com/apache/dolphinscheduler/assets/134610552/8f21b283-0ba3-4055-8e93-dad9814d64f4">
这个是可以保存的

**Comment by ruanwenjun** [comment]
This is a front-end bug?
