### ISSUE TITLE
[Bug] After the service is restarted, new tasks are not scheduled and old tasks are scheduled normally.

### ISSUE THREAD

**Issue by q4q5q6qw** [apache/dolphinscheduler#15557]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I changed the exec_threads of the master and worker services. After the restart, the newly created tasks do not generate new process instances, but the old tasks can continue to be executed. There is no obvious error in the logs of the master and worker. The qrtz_cron_triggers and qrtz_triggers tables contain the data of the new task. NEXT_FIRE_TIME is the time when the task should be executed for the first time. However, the task is not invoked. The t_ds_process_instance and t_ds_task_instance tables do not contain the new task instance. Now the exec_threads before the restore is not able to execute the new task.  How can I locate the fault?

### What you expected to happen

The new task can be executed properly.

### How to reproduce

modified the exec_threads of the master and worker services. and restart

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by q4q5q6qw** [comment]
Complement:
In the t_ds_process_definition_log table, the value of release_state of the new task is 0. However, in the t_ds_process_definition table, the value of release_state is 1.

**Comment by q4q5q6qw** [comment]
[INFO] 2024-02-03 17:50:49.460 +0800 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[107] - REQUEST TRACE_ID:12483001530752, LOGIN_USER:csb_soc_user, URI:/dolphinscheduler/projects/7848358598592/process-definition/12483001532224/release, METHOD:POST, HANDLER:org.apache.dolphinscheduler.api.controller.ProcessDefinitionController.releaseProcessDefinition, ARGS:{code=12483001532224, projectCode=7848358598592, releaseState=ONLINE}
[INFO] 2024-02-03 17:50:49.641 +0800 org.apache.dolphinscheduler.service.cache.impl.CacheNotifyServiceImpl:[115] - send result, command:Command [type=CACHE_EXPIRE, opaque=3295, bodyLen=62]
[INFO] 2024-02-03 17:50:49.644 +0800 org.apache.dolphinscheduler.api.service.impl.ProcessDefinitionServiceImpl:[1120] - Set process definition online, projectCode:7848358598592, processDefinitionCode:12483001532224.
[INFO] 2024-02-03 17:50:49.671 +0800 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[122] - Call POST:/dolphinscheduler/projects/7848358598592/process-definition/12483001532224/release success, cost: 211ms

**Comment by q4q5q6qw** [comment]
After the machine specifications of the master and worker services are expanded and the system is restarted, new tasks can be executed properly. Why are all old tasks executed properly before the capacity expansion but new tasks cannot be executed?

**Comment by ruanwenjun** [comment]
Do you mean the quartz doesn't work?

**Comment by q4q5q6qw** [comment]
> Do you mean the quartz doesn't work?

Not completely out of work.The workflow created before the configuration modification and restart is still scheduled properly. After the restart, the newly created workflow does not work.
