### ISSUE TITLE
Workflow instance is not getting generated on DolphinScheduler v3.2.0

### ISSUE THREAD

**Issue by PVelagambeti** [apache/dolphinscheduler#15587]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Hi, i have created a Workflow Definition under the project and made it online and started it. But i don't see "Workflow instance" got created. My workflow instance list is empty. And also, i see Task definition as well but no task instance got created. i checked the logs on worker & master. No errors reported.

Due to this, in monitor section, under "Statistical Manager -> Statistics" section, i see "Command Number Of Waiting For Running" is showing 1 and getting completed.

It would be very helpful if you could take a look at it.

### What you expected to happen

I expect, workflow instance and task instance should get created and command should run.

### How to reproduce

I just followed the documentation to create a workflow definition and run a shell script.

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
hi @PVelagambeti  can you show me the master's log?

**Comment by vshallc** [comment]
Same problem occurs on mine, and no master & worker log reported.
Only one log in api-server:
```
[INFO] 2025-01-13 18:49:18.478 +0800 o.a.d.a.s.i.ExecutorServiceImpl:[279] - Create command complete, processDefinitionCode:130389850845344, commandCount:1.
```

**Comment by rogerpanlego** [comment]
the same problem occasionally occurs on 3.2.1 version. and need to reboot worker-server
