### ISSUE TITLE
[Bug] [Quartz] Incorrect NextFireTime in high-concurrency scenarios

### ISSUE THREAD

**Issue by rupeng1208** [apache/dolphinscheduler#15590]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have around 800 tasks with cron expressions set to '0 0 5 * * ?', which means they should execute at 05:00:00 every day. I'm using MySQL as the database for Quartz. In the recent days, after approximately 200 tasks have been executed, the value of NEXT_FIRE_TIME in QUARTZ_TRIGGERS is set to 48 hours ahead. For example, after a task is executed at 05:00:00 on 2024-02-11, the NEXT_FIRE_TIME is set to 2024-02-13 05:00:00. What could be causing this? 
My dolphinschedulerVersion is 3.1.3.

Here are the related configurations that I am currently using：
org.quartz.threadPool.threadPriority: 5
org.quartz.jobStore.isClustered: true
org.quartz.jobStore.class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
org.quartz.scheduler.instanceId: AUTO
org.quartz.jobStore.tablePrefix: QRTZ_
org.quartz.jobStore.acquireTriggersWithinLock: true
org.quartz.scheduler.instanceName: DolphinScheduler
org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
org.quartz.jobStore.useProperties: false
org.quartz.threadPool.makeThreadsDaemons: true
org.quartz.threadPool.threadCount: 25
org.quartz.jobStore.misfireThreshold: 60000
org.quartz.scheduler.batchTriggerAcquisitionMaxCount: 1
org.quartz.scheduler.makeSchedulerThreadDaemon: true
org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
org.quartz.jobStore.clusterCheckinInterval: 5000

### What you expected to happen

Can adjusting some concurrency-related configurations resolve this issue?

### How to reproduce

schedule task in  high-concurrency scenarios

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rickchengx** [comment]
@rupeng1208 could you please provide more information about this issue, I dont think a daily scheduled task is high-concurrency.
