### ISSUE TITLE
[Improvement] Refactoring Code For Better Comprehension

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#15599]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently some parts of code are poorly constructed, leading to difficult comprehension, trouble of testing and maintenance.

With an IntelliJ plugin, `metrics reloaded`, we could get the complexity of methods in this project.

![image](https://github.com/apache/dolphinscheduler/assets/34905992/e28180d1-01b1-40f3-b235-8a808a32e4e7)

If the cognitive complexity of a method is more than 30, basically we treat it as incomprehensible, untestable and unmaintainable. We would like to have these methods refactored and achieve a significant decrease in complexity, maybe 50% or more.

Any help will be appreciated : ) 

https://plugins.jetbrains.com/plugin/93-metricsreloaded

https://www.hatica.io/blog/code-complexity/

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stonelion** [comment]
Is it only for a specific package, or all of them?

**Comment by pinkfloyds** [comment]
I can't agree more with your advice ,really need refactoring code.

**Comment by EricGao888** [comment]
> Is it only for a specific package, or all of them?

We could do it iteratively, with priority.

**Comment by akshitk20** [comment]
@EricGao888 seems like i do not have write access to this repo. Due to this I am unable to push my feature branch for this issue. Could you help here

**Comment by EricGao888** [comment]
> @EricGao888 seems like i do not have write access to this repo. Due to this I am unable to push my feature branch for this issue. Could you help here

Hi @akshitk20 , you don't need direct write access to this repo to contribute. You could submit a PR and maintainers will review it and then help merge it.

FYI:
https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/Development-workflow-with-Git:-Fork,-Branching,-Commits,-and-Pull-Request
