### ISSUE TITLE
How use ETCD as externalRegistry in k8s

### ISSUE THREAD

**Issue by bulolo** [apache/dolphinscheduler#15591]
How use ETCD as externalRegistry in k8s?

can not find any docs

**Comment by pegasas** [comment]
It seems related to https://github.com/apache/dolphinscheduler/blob/dev/dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-etcd/README.md?plain=1#L5-L29, 
I've create PR trying to add link into docs.

**Comment by pegasas** [comment]
still working

**Comment by pegasas** [comment]
kick
