### ISSUE TITLE
[Bug] No Master Nodes Exist

### ISSUE THREAD

**Issue by cristianCesanaIvolution** [apache/dolphinscheduler#15593]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I deployed the last version of DolphinScheduler 3.2.1 through docker-compose procedure described here: https://dolphinscheduler.apache.org/en-us/docs/3.2.1/guide/start/docker#using-docker-compose-to-start-server

Running the monitor I can see that no master node exists
![image](https://github.com/apache/dolphinscheduler/assets/146731324/9b8c316d-98f6-47ee-87eb-9d3a17614d88)

Tring to run a workflow or task I get the error "master does not exists" (as expected)
![image](https://github.com/apache/dolphinscheduler/assets/146731324/a8feab2a-f073-4cc3-bc6f-b42fdc4f8e21)

Looking at the logs contained in master container folder I can see this
![image](https://github.com/apache/dolphinscheduler/assets/146731324/37e08765-9ed2-4b3f-a95e-da15a223fe69)

Any idea of what is causing the master instance to not start correctly?

### What you expected to happen

Worker instance is properly started and visible for dolphinscheduler-api container and tasks are executed correctly

### How to reproduce

Deploy with docker-compose as described in: https://dolphinscheduler.apache.org/en-us/docs/3.2.1/guide/start/docker#using-docker-compose-to-start-server

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
hi @cristianCesanaIvolution  It may be because the registered zk addresses of api-server and master-server are different, or the master is not registered on zk.

**Comment by bococ** [comment]
I also have this problem. After starting dolphinscheduler in version 3.2.0, the ports monitored by the master are 5678 and 5679. These two ports are also included in the configuration file. The configuration of 3.2.1 is the same, but the monitored port is only 5678.
![dolphin-master-port](https://github.com/apache/dolphinscheduler/assets/69111572/b3077f9b-ec4a-4c6f-a33c-f45200041ad8)

![image](https://github.com/apache/dolphinscheduler/assets/69111572/9190a034-9100-4433-923a-d4ba7544d34e)

**Comment by malinos88** [comment]
Bonjour, 
J'ai installé DolphinScheduler (docker/windows) et j'ai la même pb que vous (même msg d'erreur).
Par contre je ne trouve pas de répertoire 'master-server'.
L'avez-vous ajouté, se trouve t-il à la racine, ...?
a+
fd

**Comment by zhixiangjoy** [comment]
meet the same problem, sos

**Comment by zane-lin-7** [comment]
Cause the master node has an overload protection mechanism. And if the load surpasses the threshold, it won't be registered with ZooKeeper. 
Solutions(choose any one):

    Modify dolphinscheduler-master/src/main/resources/application.yaml
    1. Disable the protection mechanism
    master.server-load-protection.enabled: false
    2. Increase the load threshold
    master.server-load-protection.*-thresholds: 0.95
    
    The same holds true for the worker node.
