### ISSUE TITLE
[Bug] Version 3.2.1 [Instance list paging is incorrect, the monitored disk capacity is displayed as 0]

### ISSUE THREAD

**Issue by liubo988** [apache/dolphinscheduler#15606]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

刚升级到3.2.1，发现实例列表分页失败，还有监控的磁盘容量显示错误 全是0 
![bug1](https://github.com/apache/dolphinscheduler/assets/17637421/01ae3583-3618-4a35-90a1-3d0e8cbcb30c)
![bug2](https://github.com/apache/dolphinscheduler/assets/17637421/85bfa7c6-0eab-48f1-9957-7cfe0ac9960a)
![bug3](https://github.com/apache/dolphinscheduler/assets/17637421/2d73bf76-6d48-45a4-a0a9-a1fe1bb59cda)

### What you expected to happen

解决实例列表无法分页问题

### How to reproduce

如上图，3.2.1版本

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RedHatKai** [comment]
When to modify this bug
