### ISSUE TITLE
[Bug] [dolphinscheduler-task-api]  The getProcessId function returns a pid error

### ISSUE THREAD

**Issue by cqutwangyu** [apache/dolphinscheduler#15605]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

https://github.com/apache/dolphinscheduler/issues/14222
https://github.com/apache/dolphinscheduler/issues/15503
------------------------------------------------------

我在dolphinscheduler中配置了seatunnel任务，并运行了实例，但我无法通过dolphinscheduler停止对应的seatunnel任务进程。尽管dolphinscheduler中显示任务状态为Kill，但服务器上的seatunnel任务还在运行。
这个问题非常严重，希望能尽快解决。

-------------------------------------------------------
I configured the seatunnel task in dolphinscheduler and ran the instance, but I was unable to stop the seatunnel task process using dolphinscheduler. The seatunnel task is running on the server despite the task status being shown as Kill in dolphinscheduler.

This problem is very serious and I hope it can be solved soon.

### What you expected to happen

pass

### How to reproduce

pass

### Anything else

pass

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cqutwangyu** [comment]
@ruanwenjun @zhongjiajie please see

**Comment by cqutwangyu** [comment]
以下是我的测试代码 Demo.java
Here's my test code demo.java


```java
import java.io.File;
import java.io.IOException;
import java.lang.reflect.Field;

public class Demo {
    public static void main(String[] args) throws IOException {
        ProcessBuilder processBuilder = new ProcessBuilder();
        processBuilder.directory(new File("/opt/test"));
        processBuilder.redirectErrorStream(true);
        processBuilder.command(args);
        Process p = processBuilder.start();
        int processId = getProcessId(p);
        System.out.println("pid:"+processId);
        System.out.println("isAlive:"+p.isAlive());
    }
    private static int getProcessId(Process process) {
        int processId = 0;

        try {
            Field f = process.getClass().getDeclaredField("pid");
            f.setAccessible(true);

            processId = f.getInt(process);
        } catch (Exception e) {
            System.out.println("Get task pid failed"+e.getMessage());
        }

        return processId;
    }
}
```

先编译java文件，并创建一个sh脚本文件
Compile the Java file first and create an sh script file
```
javac Demo.java
echo "java -jar server-0.0.1-SNAPSHOT.jar" > server-start.sh
```

执行sh脚本启动java程序，则获取到的pid是错误的。
Executing the sh script starts the Java program, and the pid is wrong.
```
java Demo sh server-start.sh
pid:35054
isAlive:true

jps
35080 Jps
35055 jar
```

直接执行java命令启动java程序，则能获取到正确的pid。
The direct execution of the Java command starts the Java program and gets the correct pid.
```
kill -9 35055
java Demo java -jar server-0.0.1-SNAPSHOT.jar
pid:35641
isAlive:true

jps
35669 Jps
35641 jar
```
以下是运行环境
The following is the operating environment
```
java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

uname -a
Linux urc-esb-server2 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cqutwangyu** [comment]
我看到 [#14652](https://github.com/apache/dolphinscheduler/pull/14652) 解决了这个问题。
但我依然出现了异常，原因是我的Linux没有安装pstree。
将pstree安装之后问题得到解决。

I saw [#14652](https://github.com/apache/dolphinscheduler/pull/14652) to solve the problem.

But I still get an exception, because my Linux doesn't have pstree installed.

Once pstree is installed, the issue is resolved.

**Comment by jalousiex** [comment]
这好像只是local模式的处理，cluster模式下，worker上只是client，杀进程并不能停止掉集群上的任务
