### ISSUE TITLE
[Improvement] [sub_process] the subprocess's tenant is always default and cann't run

### ISSUE THREAD

**Issue by tuoluzhe8521** [apache/dolphinscheduler#15637]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When i run sub_process task and set tenant hadoop, but i click to enter the sub_process node, the subprocess's tenant is always default.
the error is as follows:
[main] ERROR org.apache.spark.SparkContext - Error initializing SparkContext.
	org.apache.hadoop.security.AccessControlException: Permission denied: user=default, access=WRITE, inode="/user":hadoop:supergroup:drwxr-xr-x

### What you expected to happen

he subprocess's tenant changes with settings

### How to reproduce

run sub_process task and set tenant hadoop

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Does this happen in the spark task? Isn't the spark task executed by `hadoop` user?
I just test sub_process task, this work well.

**Comment by bajiaolong** [comment]
> Does this happen in the spark task? Isn't the spark task executed by `hadoop` user? I just test sub_process task, this work well.

I have encountered a problem and need to modify this tenant every time. the default tenant is default.
1.  There is only one tenant in my tenant management: appuser;
![图片](https://github.com/apache/dolphinscheduler/assets/49988122/e1453a9d-7ebe-48f5-a5f6-6dea65f353c6)

2.  When the process is to run, this tenant must be set up every time, changing the default tenant default to the tenant appuser in my system.
![图片](https://github.com/apache/dolphinscheduler/assets/49988122/5624b5b0-7b22-4564-9960-64ba723113af)
![图片](https://github.com/apache/dolphinscheduler/assets/49988122/405e94ad-4af9-43ec-a2fd-16d4ada0327f)

**Comment by tuoluzhe8521** [comment]
> Does this happen in the spark task? Isn't the spark task executed by `hadoop` user? I just test sub_process task, this work well.
my task is shell，the shell task call the spark task and the spark task executed by `hadoop` user. 
how can i solve this problem?

**Comment by tuoluzhe8521** [comment]
> Does this happen in the spark task? Isn't the spark task executed by `hadoop` user? I just test sub_process task, this work well.
this my main task page:
![image](https://github.com/apache/dolphinscheduler/assets/114386921/84091809-b03a-4108-825b-563de4fe6476)
this my sub_process page:
![image2](https://github.com/apache/dolphinscheduler/assets/114386921/7ee16e8b-402b-4aaa-8e17-5a2b31dc55ed)

**Comment by tuoluzhe8521** [comment]
> > Does this happen in the spark task? Isn't the spark task executed by `hadoop` user? I just test sub_process task, this work well.
> 
> I have encountered a problem and need to modify this tenant every time. the default tenant is default.
> 
> 1. There is only one tenant in my tenant management: appuser;
>    ![图片](https://private-user-images.githubusercontent.com/49988122/308031840-e1453a9d-7ebe-48f5-a5f6-6dea65f353c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTY0NjIsIm5iZiI6MTcwOTAxNjE2MiwicGF0aCI6Ii80OTk4ODEyMi8zMDgwMzE4NDAtZTE0NTNhOWQtN2ViZS00OGY1LWE1ZjYtNmRlYTY1ZjM1M2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA2NDI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMTgxMDllMzZiNmM5MGIxNjg0N2JkZDIxZmYxOGZmODhiNzJkZjg5NGU3YWY5YjM3Yjc2ODJhMDRiMTMxYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GZnr2FUx2o6wPnSCCdulSlJx82tSHrmZr0jDjBQb89U)
> 2. When the process is to run, this tenant must be set up every time, changing the default tenant default to the tenant appuser in my system.
>    ![图片](https://private-user-images.githubusercontent.com/49988122/308031938-5624b5b0-7b22-4564-9960-64ba723113af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTY0NjIsIm5iZiI6MTcwOTAxNjE2MiwicGF0aCI6Ii80OTk4ODEyMi8zMDgwMzE5MzgtNTYyNGI1YjAtN2IyMi00NTY0LTk5NjAtNjRiYTcyMzExM2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA2NDI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MDYwMTczNTI0ZjYxYzJjM2VhZTY1OTMwZDI0YWUxMDJmNjkwYTBhNWFkMWJjNWRjYzE5OTRhNjlkY2E2N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.biFU5wggDdjjTS2oTMlHBVnChp_R1wxti7Z4dMtMoss)
>    ![图片](https://private-user-images.githubusercontent.com/49988122/308031998-405e94ad-4af9-43ec-a2fd-16d4ada0327f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTY0NjIsIm5iZiI6MTcwOTAxNjE2MiwicGF0aCI6Ii80OTk4ODEyMi8zMDgwMzE5OTgtNDA1ZTk0YWQtNGFmOS00M2VjLWEyZmQtMTZkNGFkYTAzMjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA2NDI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlOTMzM2EwMzJmODYwZDBhZjMzOTI5ZTdiYWI0MjQwOGNiN2FiZGYyZjZkOTZjMTU0NGJlNTM2Y2U0NTc4ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3VuFtSlJ2F1xo5pu__E1LhUAm6gTB6WDk_mE6MAkQls)

i delete the default tenant, and also encounter this problem

**Comment by zui01** [comment]
> > Does this happen in the spark task? Isn't the spark task executed by `hadoop` user? I just test sub_process task, this work well.
> 
> I have encountered a problem and need to modify this tenant every time. the default tenant is default.
> 
> 1. There is only one tenant in my tenant management: appuser;
>    ![图片](https://private-user-images.githubusercontent.com/49988122/308031840-e1453a9d-7ebe-48f5-a5f6-6dea65f353c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTk4MzksIm5iZiI6MTcwOTExOTUzOSwicGF0aCI6Ii80OTk4ODEyMi8zMDgwMzE4NDAtZTE0NTNhOWQtN2ViZS00OGY1LWE1ZjYtNmRlYTY1ZjM1M2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDExMjUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhODQ2ZDZmMDAwOTAzM2ZmMzA0OTFmMWRkYjBiNTEyZmMwNzAzNWEzYTE4MmMxZGEzYTRkYzZmZmQ2MWYzMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F3XhS7NafWlw9dzbRCJCktlRj5DbNJ7YD4PxL6cLeVI)
> 2. When the process is to run, this tenant must be set up every time, changing the default tenant default to the tenant appuser in my system.
>    ![图片](https://private-user-images.githubusercontent.com/49988122/308031938-5624b5b0-7b22-4564-9960-64ba723113af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTk4MzksIm5iZiI6MTcwOTExOTUzOSwicGF0aCI6Ii80OTk4ODEyMi8zMDgwMzE5MzgtNTYyNGI1YjAtN2IyMi00NTY0LTk5NjAtNjRiYTcyMzExM2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDExMjUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4Y2E3ZjBiNmJjNzk5MTA5ZjRmNDgxZDA1NDhmNzAyYmI3Y2NjZmM2NWRiNmRiOTg0OGMxYmI1ZTk4Y2I0NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HqThzzENx6P8eB13evnh2PE8IHVfmmnVw6MaN9AwKck)
>    ![图片](https://private-user-images.githubusercontent.com/49988122/308031998-405e94ad-4af9-43ec-a2fd-16d4ada0327f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTk4MzksIm5iZiI6MTcwOTExOTUzOSwicGF0aCI6Ii80OTk4ODEyMi8zMDgwMzE5OTgtNDA1ZTk0YWQtNGFmOS00M2VjLWEyZmQtMTZkNGFkYTAzMjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDExMjUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZmY2ODdkZTNiOWRiOWE2OWRhYzE1YjkxYTBiMDViYjkxZGNkMzE3ZTA4MmQxMmVjZDU2OTlhNGE0NjkwMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oir-O2wT7UBdCKlTIIu5F6-PqTNd0vcRbMewwXwVux0)

same as u,and i found in lsat version ds ,process defination table has tenant,so you do not nedd to change tenant every time,bug 3.2.1 cancle this coulme in table.terrible

**Comment by zui01** [comment]
just delete the default tenant plz.nobody use it in product env,it's useless   @rickchengx @SbloodyS

**Comment by tuoluzhe8521** [comment]
Do you have time to help me take a look @ruanwenjun

**Comment by SbloodyS** [comment]
This issue can be avoided by manually selecting tenants. So I think this is an improvement rather than a bug. Anyone who wants to fix it can leave a message under this issue, and I will assign it to it.

**Comment by bajiaolong** [comment]
> This issue can be avoided by manually selecting tenants. So I think this is an improvement rather than a bug. Anyone who wants to fix it can leave a message under this issue, and I will assign it to it.

I found that I enabled it in the project preferences, but it didn't take effect.
![图片](https://github.com/apache/dolphinscheduler/assets/49988122/896b43e5-8d7e-45c6-aec4-e7fe3f268168)

I started the process without setting it according to my project preferences,I don't know if it's my project or if everyone has this problem.
![图片](https://github.com/apache/dolphinscheduler/assets/49988122/711e228d-5e5b-40a5-bcb9-e8b95875d876)

If everyone has this problem, can we improve it like this.
The settings for the tenant are as follows:
* 1. If a project preference is set, the priority is the highest.
* 2. Then the tenant that currently starts the user is the second priority.
* 3. The last priority is the default tenant.

Other configurations are set according to project preferences, and default values are used if project preferences are not enabled.

**Comment by zui01** [comment]
> This issue can be avoided by manually selecting tenants. So I think this is an improvement rather than a bug. Anyone who wants to fix it can leave a message under this issue, and I will assign it to it.

the point is you need manual set it every time ,because the fronted is stack in 'default' tenant

**Comment by bajiaolong** [comment]
> > This issue can be avoided by manually selecting tenants. So I think this is an improvement rather than a bug. Anyone who wants to fix it can leave a message under this issue, and I will assign it to it.
> 
> the point is you need manual set it every time ,because the fronted is stack in 'default' tenant

Therefore, the optimization of priority should start from the front end.

**Comment by lucaswanlinz** [comment]
@bajiaolong Just FYI, I encountered the same problem and resolved it by adding an execution environment for the task and configuring "export HADOOP_USER_NAME=your spark user".

**Comment by zui01** [comment]
> @bajiaolong Just FYI, I encountered the same problem and resolved it by adding an execution environment for the task and configuring "export HADOOP_USER_NAME=your spark user".

good tirk,i chang some conf make ds use worker's deploy user to avoid this problem

**Comment by Pluto201** [comment]
> > @bajiaolong Just FYI, I encountered the same problem and resolved it by adding an execution environment for the task and configuring "export HADOOP_USER_NAME=your spark user".
> 
> good tirk,i chang some conf make ds use worker's deploy user to avoid this problem

 I encountered the same problem in FLINK task,  could u share what conf u changed? thank you!

**Comment by bajiaolong** [comment]
> > > @bajiaolong Just FYI, I encountered the same problem and resolved it by adding an execution environment for the task and configuring "export HADOOP_USER_NAME=your spark user".
> > 
> > 
> > good tirk,i chang some conf make ds use worker's deploy user to avoid this problem
> 
> I encountered the same problem in FLINK task, could u share what conf u changed? thank you!

There is a tenant option in the task running page, where you can specify a specific tenant. Please ensure that the tenant's environment variables are correct

**Comment by Pluto201** [comment]
> > > > @bajiaolong Just FYI, I encountered the same problem and resolved it by adding an execution environment for the task and configuring "export HADOOP_USER_NAME=your spark user".
> > > 
> > > 
> > > good tirk,i chang some conf make ds use worker's deploy user to avoid this problem
> > 
> > 
> > I encountered the same problem in FLINK task, could u share what conf u changed? thank you!
> 
> There is a tenant option in the task running page, where you can specify a specific tenant. Please ensure that the tenant's environment variables are correct

I'm using version 3.2.1, and when the workflow contains subtasks, after I specify the workflow's tenant in the task running page, the subtasks still run with `default` instead of the specified tenant.

**Comment by bajiaolong** [comment]
> I'm using version 3.2.1, and when the workflow contains subtasks, after I specify the workflow's tenant in the task running page, the subtasks still run with `default` instead of the specified tenant.

I'll run the test locally and reply to you later.

**Comment by bajiaolong** [comment]
> > > > > @bajiaolong Just FYI, I encountered the same problem and resolved it by adding an execution environment for the task and configuring "export HADOOP_USER_NAME=your spark user".
> > > > 
> > > > 
> > > > good tirk,i chang some conf make ds use worker's deploy user to avoid this problem
> > > 
> > > 
> > > I encountered the same problem in FLINK task, could u share what conf u changed? thank you!
> > 
> > 
> > There is a tenant option in the task running page, where you can specify a specific tenant. Please ensure that the tenant's environment variables are correct
> 
> I'm using version 3.2.1, and when the workflow contains subtasks, after I specify the workflow's tenant in the task running page, the subtasks still run with `default` instead of the specified tenant.

Is it convenient to tell me your task type and subtask type

**Comment by Pluto201** [comment]
> > > > > > @bajiaolong Just FYI, I encountered the same problem and resolved it by adding an execution environment for the task and configuring "export HADOOP_USER_NAME=your spark user".
> > > > > 
> > > > > 
> > > > > good tirk,i chang some conf make ds use worker's deploy user to avoid this problem
> > > > 
> > > > 
> > > > I encountered the same problem in FLINK task, could u share what conf u changed? thank you!
> > > 
> > > 
> > > There is a tenant option in the task running page, where you can specify a specific tenant. Please ensure that the tenant's environment variables are correct
> > 
> > 
> > I'm using version 3.2.1, and when the workflow contains subtasks, after I specify the workflow's tenant in the task running page, the subtasks still run with `default` instead of the specified tenant.
> 
> Is it convenient to tell me your task type and subtask type

It's all flink-sql.

**Comment by bajiaolong** [comment]
> > > > > > > @bajiaolong Just FYI, I encountered the same problem and resolved it by adding an execution environment for the task and configuring "export HADOOP_USER_NAME=your spark user".
> > > > > > 
> > > > > > 
> > > > > > good tirk,i chang some conf make ds use worker's deploy user to avoid this problem
> > > > > 
> > > > > 
> > > > > I encountered the same problem in FLINK task, could u share what conf u changed? thank you!
> > > > 
> > > > 
> > > > There is a tenant option in the task running page, where you can specify a specific tenant. Please ensure that the tenant's environment variables are correct
> > > 
> > > 
> > > I'm using version 3.2.1, and when the workflow contains subtasks, after I specify the workflow's tenant in the task running page, the subtasks still run with `default` instead of the specified tenant.
> > 
> > 
> > Is it convenient to tell me your task type and subtask type
> 
> It's all flink-sql.

The preliminary judgment is the parameter problem of flink, please see my other PR. #15708

**Comment by Pluto201** [comment]
So this problem can not be solved in the current version (3.2.1)?

**Comment by Pluto201** [comment]
> > > > > > > > @bajiaolong Just FYI, I encountered the same problem and resolved it by adding an execution environment for the task and configuring "export HADOOP_USER_NAME=your spark user".
> > > > > > > 
> > > > > > > 
> > > > > > > good tirk,i chang some conf make ds use worker's deploy user to avoid this problem
> > > > > > 
> > > > > > 
> > > > > > I encountered the same problem in FLINK task, could u share what conf u changed? thank you!
> > > > > 
> > > > > 
> > > > > There is a tenant option in the task running page, where you can specify a specific tenant. Please ensure that the tenant's environment variables are correct
> > > > 
> > > > 
> > > > I'm using version 3.2.1, and when the workflow contains subtasks, after I specify the workflow's tenant in the task running page, the subtasks still run with `default` instead of the specified tenant.
> > > 
> > > 
> > > Is it convenient to tell me your task type and subtask type
> > 
> > 
> > It's all flink-sql.
> 
> The preliminary judgment is the parameter problem of flink, please see my other PR. #15708

  :(   So this problem can not be solved in the current version (3.2.1)?

**Comment by bajiaolong** [comment]
> > > > > > > > > @bajiaolong Just FYI, I encountered the same problem and resolved it by adding an execution environment for the task and configuring "export HADOOP_USER_NAME=your spark user".
> > > > > > > > 
> > > > > > > > 
> > > > > > > > good tirk,i chang some conf make ds use worker's deploy user to avoid this problem
> > > > > > > 
> > > > > > > 
> > > > > > > I encountered the same problem in FLINK task, could u share what conf u changed? thank you!
> > > > > > 
> > > > > > 
> > > > > > There is a tenant option in the task running page, where you can specify a specific tenant. Please ensure that the tenant's environment variables are correct
> > > > > 
> > > > > 
> > > > > I'm using version 3.2.1, and when the workflow contains subtasks, after I specify the workflow's tenant in the task running page, the subtasks still run with `default` instead of the specified tenant.
> > > > 
> > > > 
> > > > Is it convenient to tell me your task type and subtask type
> > > 
> > > 
> > > It's all flink-sql.
> > 
> > 
> > The preliminary judgment is the parameter problem of flink, please see my other PR. #15708
> 
> :( So this problem can not be solved in the current version (3.2.1)?

I also found this problem when I used version 3.2.0. I can execute it correctly by modifying the code. This PR is not merged now.

**Comment by FireFreedomK** [comment]
version:3.2.2
![image](https://github.com/user-attachments/assets/0b04ea12-3b83-46bb-9c22-3419850d1712)
I have created A workflow A with multiple subworkflow, each subworkflow has A sqlTask in it, now start A, subworkflow in A will report an error,as shown in the following figure
![image](https://github.com/user-attachments/assets/0c88b06f-1beb-486f-8170-16d9d3217496)
How do I follow the error message? enable TenantConfig#isDefaultTenantEnabled

**Comment by FireFreedomK** [comment]
> version:3.2.2 ![image](https://private-user-images.githubusercontent.com/43286778/396732055-0b04ea12-3b83-46bb-9c22-3419850d1712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0OTAxNzYsIm5iZiI6MTczNDQ4OTg3NiwicGF0aCI6Ii80MzI4Njc3OC8zOTY3MzIwNTUtMGIwNGVhMTItM2I4My00NmJiLTljMjItMzQxOTg1MGQxNzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDAyNDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZThlZWM2YzZkYjFlZTk1MWRjNmU1ZTNkOGYxODZhMGEyZGNiZTc4MGVlZWZmYzA2NDhiNDFmN2JlNWZkMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cnA5UyHzWWp_yGgvmawEWIZt0UUfPgC9xyGFkSAFm34) I have created A workflow A with multiple subworkflow, each subworkflow has A sqlTask in it, now start A, subworkflow in A will report an error,as shown in the following figure ![image](https://private-user-images.githubusercontent.com/43286778/396732444-0c88b06f-1beb-486f-8170-16d9d3217496.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0OTAxNzYsIm5iZiI6MTczNDQ4OTg3NiwicGF0aCI6Ii80MzI4Njc3OC8zOTY3MzI0NDQtMGM4OGIwNmYtMWJlYi00ODZmLTgxNzAtMTZkOWQzMjE3NDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDAyNDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NzMyN2YyYTg5NWMwZGI1MjM5NDhmY2Q5ZmI0MTlmNGRmZjA4YTMxY2FjYjlmZGYxZTU2YWNkZmI3ZjJhNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.T6jufvGlN_pMCAvjDq0S1lJlIGVz-FkurFZ7B-fEI5U) How do I follow the error message? enable TenantConfig#isDefaultTenantEnabled


set this parameter to true and restart the job without error
![image](https://github.com/user-attachments/assets/a10988f2-7d74-4680-bed3-509292b3a583)

**Comment by melon1010** [comment]
也是报错enable TenantConfig#isDefaultTenantEnabled   docker启动的怎么解决？

**Comment by cyrusmaster** [comment]
@melon1010   怎么样了   compose也是这个问题   使用自建的租户就正常 看报错是需要配置 

<img width="1122" height="201" alt="Image" src="https://github.com/user-attachments/assets/b3299a93-83be-4be8-869b-d78360078a65" />

**Comment by cyrusmaster** [comment]
> > version:3.2.2 ![image](https://private-user-images.githubusercontent.com/43286778/396732055-0b04ea12-3b83-46bb-9c22-3419850d1712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0OTAxNzYsIm5iZiI6MTczNDQ4OTg3NiwicGF0aCI6Ii80MzI4Njc3OC8zOTY3MzIwNTUtMGIwNGVhMTItM2I4My00NmJiLTljMjItMzQxOTg1MGQxNzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDAyNDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZThlZWM2YzZkYjFlZTk1MWRjNmU1ZTNkOGYxODZhMGEyZGNiZTc4MGVlZWZmYzA2NDhiNDFmN2JlNWZkMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cnA5UyHzWWp_yGgvmawEWIZt0UUfPgC9xyGFkSAFm34) I have created A workflow A with multiple subworkflow, each subworkflow has A sqlTask in it, now start A, subworkflow in A will report an error,as shown in the following figure ![image](https://private-user-images.githubusercontent.com/43286778/396732444-0c88b06f-1beb-486f-8170-16d9d3217496.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0OTAxNzYsIm5iZiI6MTczNDQ4OTg3NiwicGF0aCI6Ii80MzI4Njc3OC8zOTY3MzI0NDQtMGM4OGIwNmYtMWJlYi00ODZmLTgxNzAtMTZkOWQzMjE3NDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDAyNDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NzMyN2YyYTg5NWMwZGI1MjM5NDhmY2Q5ZmI0MTlmNGRmZjA4YTMxY2FjYjlmZGYxZTU2YWNkZmI3ZjJhNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.T6jufvGlN_pMCAvjDq0S1lJlIGVz-FkurFZ7B-fEI5U) How do I follow the error message? enable TenantConfig#isDefaultTenantEnabled
> 
> set this parameter to true and restart the job without error ![image](https://github.com/user-attachments/assets/a10988f2-7d74-4680-bed3-509292b3a583)

Docker must ah mount configuration file method? Is it possible to set the environment 
``` yml
environment:
  - TENANT_ENABLE_DEFAULT_TENANT=true
```

**Comment by ruanwenjun** [comment]
@cyrusmaster Yes, all config in DS can be overwritten by environment.
