### ISSUE TITLE
task is waiting to excecuted for more than 12 hours and seems not to be overtimed

### ISSUE THREAD

**Issue by epitomizelu** [apache/dolphinscheduler#15633]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

it looks same as the bug 7441.
the version is 3.1.8, and the cluster have 2 masters, 4 workers.
 I found a workflow instance running for more than 12 hours and it is abnormal. Then I found a task of the sub workflow is waiting  to be executed for more than 10 hours.
When I ended the workflow and restart it, the problem usually does not reproduce.

### What you expected to happen

 if a task waits for more than 5 minuts and can not be executed, the task should be failed. 

### How to reproduce

It is hard to reproduce, the workflow works normally for most of the time.  And When I ended the workflow and restart it, the problem usually does not reproduce.

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Please provide the master log related to the parent workflow and sub-workflow instances.

**Comment by fuchanghai** [comment]
hi @epitomizelu #14986 maybe can fix you problem, It may have actually been executed, but it has been running because of the message backlog of the subprocess type task. cc @ruanwenjun WDYT?

**Comment by ruanwenjun** [comment]
> hi @epitomizelu #14986 maybe can fix you problem, It may have actually been executed, but it has been running because of the message backlog of the subprocess type task. cc @ruanwenjun WDYT?

We may need to add metrics to record the size of `xxCheckList` in `StateWheelExecuteThread`.

**Comment by fuchanghai** [comment]
> > hi @epitomizelu #14986 maybe can fix you problem, It may have actually been executed, but it has been running because of the message backlog of the subprocess type task. cc @ruanwenjun WDYT?
> 
> We may need to add metrics to record the size of `xxCheckList` in `StateWheelExecuteThread`.

+1

**Comment by leachli** [comment]
@ruanwenjun 你好，在使用带有subprocess的任务时，主流程到达 subprocess一直处于等待状态，实际上子节点已完成，看了主任务状态还是运行中，下图是任务执行状态和集群部署情况，期待你的回复
<img width="371" alt="image" src="https://github.com/apache/dolphinscheduler/assets/30209856/8d6d3b95-d4c3-425a-be96-34a7851ab98f">
<img width="603" alt="image" src="https://github.com/apache/dolphinscheduler/assets/30209856/f5f868de-d2fa-4b3b-bda3-8febfcbdaec0">

**Comment by ruanwenjun** [comment]
> @ruanwenjun 你好，在使用带有subprocess的任务时，主流程到达 subprocess一直处于等待状态，实际上子节点已完成，看了主任务状态还是运行中，下图是任务执行状态和集群部署情况，期待你的回复
> <img alt="image" width="371" src="https://private-user-images.githubusercontent.com/30209856/308089711-8d6d3b95-d4c3-425a-be96-34a7851ab98f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTc5NDIsIm5iZiI6MTcwOTExNzY0MiwicGF0aCI6Ii8zMDIwOTg1Ni8zMDgwODk3MTEtOGQ2ZDNiOTUtZDRjMy00MjVhLWJlOTYtMzRhNzg1MWFiOThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDEwNTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiM2Y4YmQwN2Q5MzgyMjUxMDA5YmU0ZjUxZWUzYjE5NzgwNzc5MTUzYzE4YTMwNTM4NmFlMDdmM2IzNmZjNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7BE65HrdVzEEfqmNdpE3jEvzmECWCauH2sxx9s_z2lA">
> <img alt="image" width="603" src="https://private-user-images.githubusercontent.com/30209856/308090401-f5f868de-d2fa-4b3b-bda3-8febfcbdaec0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTc5NDIsIm5iZiI6MTcwOTExNzY0MiwicGF0aCI6Ii8zMDIwOTg1Ni8zMDgwOTA0MDEtZjVmODY4ZGUtZDJmYS00YjNiLWJkYTMtOGZlYmZjYmRhZWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDEwNTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiM2JkNDZmNDJkZDI3MDE4YmRhZWFkNGUwOTQ4YzMwZTUyZTI4Mjk3OGIyOWFhMTliNDU2NjI3NDczNTJjMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3feQZxBbY5_XxOxBd0_uh5CgsGgIECKeu_pHoYdm4Y0">

看这个图，子工作流逻辑节点已经成功了？这个是哪个版本？如果是目前3.2.x应该没有这类问题了，在3.2.x子工作流节点采用拉的方式去查状态，可以避免之前由于推的方式推失败导致任务状态不更新的问题

**Comment by maxiangmin** [comment]
@ruanwenjun 你好，3.2x中包含子工作流时，如果子工作流中有任务失败，点击从失败节点重跑，子工作流中成功的任务也会全部被拉起来，你们又遇到类似的问题吗
