### ISSUE TITLE
[Bug] [frontend] page only show 10 cases

### ISSUE THREAD

**Issue by zui01** [apache/dolphinscheduler#15632]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

i have 38 task instance(as same the flow instance) has done,but the page only show 10case,and can not chose next page
(3.2.1)
![企业微信截图_d9057555-c6d8-48d9-b679-69cf8f9f5111](https://github.com/apache/dolphinscheduler/assets/54675044/e76baa26-c552-452e-8a1b-39f4664d3a4b)

### What you expected to happen

i need the next page button  ,at least pass the bug,it's product env

### How to reproduce

just produce more than 10 task isntace,and go to task instance show page ,and you will find the button can not press

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zui01** [comment]
![image](https://github.com/apache/dolphinscheduler/assets/54675044/da65f12d-4ca3-4e4b-aa0d-bb8f202fa5e7)

**Comment by Gallardot** [comment]
@Anubisxcw 
#15619 fixed it

**Comment by zui01** [comment]
> @Anubisxcw #15619 fixed it

so how to fix it in a deployed cluster? thx

**Comment by Gallardot** [comment]
> so how to fix it in a deployed cluster? thx

You can cherry-pick this PR, compile it, and deploy it to your cluster.

**Comment by zui01** [comment]
> @Anubisxcw #15619 fixed it

so how to fix it in a deployed cluster? thx

> > so how to fix it in a deployed cluster? thx
> 
> You can cherry-pick this PR, compile it, and deploy it to your cluster.

oh NO.if so,i only roll back to 3.2.0

**Comment by ruanwenjun** [comment]
I will close this issue if there are no more problems.

**Comment by ruanwenjun** [comment]
> > @Anubisxcw #15619 fixed it
> 
> so how to fix it in a deployed cluster? thx
> 
> > > so how to fix it in a deployed cluster? thx
> > 
> > 
> > You can cherry-pick this PR, compile it, and deploy it to your cluster.
> 
> oh NO.if so,i only roll back to 3.2.0

As @Gallardot said, you can clone the source code and cp #15619.

**Comment by zui01** [comment]
> > > @Anubisxcw #15619 fixed it
> > 
> > 
> > so how to fix it in a deployed cluster? thx
> > > > so how to fix it in a deployed cluster? thx
> > > 
> > > 
> > > You can cherry-pick this PR, compile it, and deploy it to your cluster.
> > 
> > 
> > oh NO.if so,i only roll back to 3.2.0
> 
> As @Gallardot said, you can clone the source code and cp #15619.

ok i'm on it,thx
