### ISSUE TITLE
[idea][Process Definition] Execute strategy for serial discard with oldest task

### ISSUE THREAD

**Issue by liunanting** [apache/dolphinscheduler#15646]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

在执行策略里面，新增一种执行策略，如果对于同一个工作流定义，同时有多个工作流实例，则抛弃后->新生成的工作流实例并杀掉正在跑的实例。(现在策略是杀掉新生成的实例，能够新增一个杀掉后生成的实例，以最新的为主)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please describe in English.
