### ISSUE TITLE
[Bug] [Api] project prefrence do not work

### ISSUE THREAD

**Issue by zui01** [apache/dolphinscheduler#15648]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

i set a tenant for my project ,and i just run the workflow.
but when i run a task,like shell task ,run commond "whoami"
but the result is ds's default tenant,named 'default' ,not my prefrence value 

### What you expected to happen

workflow should run as my prefrence value

### How to reproduce

just replay 

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zui01** [comment]
![企业微信截图_8b7e5c1e-3298-4b49-b0fa-f1d28a458b5e](https://github.com/apache/dolphinscheduler/assets/54675044/dd146009-eb9b-4c27-9d67-6e7d1118cf37)

**Comment by ruanwenjun** [comment]
It seems the `Project Preferences` is not working...... for tenant.

**Comment by ruanwenjun** [comment]
We need to inject these configurations from project preference.
<img width="1443" alt="image" src="https://github.com/apache/dolphinscheduler/assets/22415594/62ebafd2-0def-4841-9ff5-e84cfede5b82">

**Comment by zui01** [comment]
all conf is default value ,just tetnant is work

**Comment by bajiaolong** [comment]
I would like to try this issues and assign it to me.

**Comment by devosend** [comment]
close by pr: https://github.com/apache/dolphinscheduler/pull/15724
