### ISSUE TITLE
多依赖任务bug

### ISSUE THREAD

**Issue by banbsyip** [apache/dolphinscheduler#15657]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![1](https://github.com/apache/dolphinscheduler/assets/18277076/65f90059-3f46-4bfb-9f46-b68538bd8801)
![2](https://github.com/apache/dolphinscheduler/assets/18277076/d3e2de04-5ec7-4c35-9c29-fa3e431f32a8)
我的任务流中有一个任务C依赖两个任务B，C，可是其中一个被依赖的任务A结束后，没有等另外一个任务B之行结束，任务C就开始执行了，这是怎么回事？

### What you expected to happen

多依赖任务有问题

### How to reproduce

帮助解决多依赖问题

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please describe your issue in English. Thanks. @banbsyip
