### ISSUE TITLE
depend DAG bug

### ISSUE THREAD

**Issue by banbsyip** [apache/dolphinscheduler#15658]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![1](https://github.com/apache/dolphinscheduler/assets/18277076/2787b40b-1e4e-43a9-8a6c-a13158af88d4)
![2](https://github.com/apache/dolphinscheduler/assets/18277076/e1e7d51c-fca6-439b-84b3-b5f5bf527317)
There is a task C in my task flow that depends on two tasks B and C. However, after one of the dependent tasks A ends, task C starts executing without waiting for the other task B to end. What is going on? ?

### What you expected to happen

Problem with multiple dependent tasks

### How to reproduce

Help resolve multiple dependency issues

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
hi @banbsyip  can you show me the process Instance defintition?

**Comment by banbsyip** [comment]
> hi @banbsyip can you show me the process Instance defintition?

the yip_cs_f_tmp14_test1 process create table yip_cs_f_tmp14_test1 and the yip_cs_f_tmp14_test2 process create table yip_cs_f_tmp14_test2, the process of yip_feature19_tmp should run after both of the two processes dnoe . but when the yip_cs_f_tmp14_test2 done and yip_cs_f_tmp14_test1 not done, the process of yip_feature19_tmp run !
![problem](https://github.com/apache/dolphinscheduler/assets/18277076/ad14a055-db5e-4583-a57b-9eb41bdd8268)
