### ISSUE TITLE
[Bug] [Workflow Definition] run Workflow, default Tenant incorrect

### ISSUE THREAD

**Issue by ylq5126** [apache/dolphinscheduler#15667]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1：config Tenant in  Project Preference Management
2：starting workflow in Operation 
3：Workflow Tenant display default

### What you expected to happen

1：config Tenant in  Project Preference Management
2：starting workflow in Operation 
3：Workflow Tenant display “Project Preference Management” configed Tenant

### How to reproduce

1：config Tenant in  Project Preference Management
2：starting workflow in Operation 

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ylq5126** [comment]
#15648

**Comment by zui01** [comment]
#15637
