### ISSUE TITLE
[Bug] [worker] Worker's automatic user creation on linux is not fully correct

### ISSUE THREAD

**Issue by zero-element** [apache/dolphinscheduler#15669]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.363 +0800 o.a.d.s.w.r.WorkerTaskExecutor:[209] - Send task status RUNNING_EXECUTION master: 172.20.0.4:1234
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.363 +0800 o.a.d.s.w.r.WorkerTaskExecutor:[217] - TenantCode: default check successfully
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.364 +0800 o.a.d.s.w.r.WorkerTaskExecutor:[220] - WorkflowInstanceExecDir: /tmp/dolphinscheduler/exec/process/default/12796470742656/12807950360608_3/5/5 check successfully
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.364 +0800 o.a.d.s.w.r.WorkerTaskExecutor:[227] - Create TaskChannel: org.apache.dolphinscheduler.plugin.task.python.PythonTaskChannel successfully
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.364 +0800 o.a.d.s.w.r.WorkerTaskExecutor:[232] - Download resources successfully: 
ResourceContext(resourceItemMap={})
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.364 +0800 o.a.d.s.w.r.WorkerTaskExecutor:[235] - Download upstream files: [] successfully
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.364 +0800 o.a.d.s.w.r.WorkerTaskExecutor:[239] - Task plugin instance: PYTHON create successfully
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.364 +0800 o.a.d.p.t.p.PythonTask:[75] - Initialize python task params {
  "localParams" : [ ],
  "varPool" : [ ],
  "rawScript" : "print(\"test\")",
  "resourceList" : [ ]
}
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.364 +0800 o.a.d.s.w.r.WorkerTaskExecutor:[243] - Success initialized task plugin instance successfully
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.364 +0800 o.a.d.s.w.r.WorkerTaskExecutor:[246] - Set taskVarPool: null successfully
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.364 +0800 o.a.d.p.t.a.l.TaskInstanceLogHeader:[1259] - ***********************************************************************************************
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.365 +0800 o.a.d.p.t.a.l.TaskInstanceLogHeader:[1259] - *********************************  Execute task instance  *************************************
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.365 +0800 o.a.d.p.t.a.l.TaskInstanceLogHeader:[1259] - ***********************************************************************************************
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.365 +0800 o.a.d.p.t.p.PythonTask:[165] - raw python script : print("test")
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.365 +0800 o.a.d.p.t.p.PythonTask:[131] - tenantCode :default, task dir:/tmp/dolphinscheduler/exec/process/default/12796470742656/12807950360608_3/5/5
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.365 +0800 o.a.d.p.t.p.PythonTask:[134] - generate python script file:/tmp/dolphinscheduler/exec/process/default/12796470742656/12807950360608_3/5/5/py_5_5.py
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.365 +0800 o.a.d.p.t.p.PythonTask:[141] - #-*- encoding=utf8 -*-

print("test")
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.365 +0800 o.a.d.p.t.a.s.BaseLinuxShellInterceptorBuilder:[64] - Final Shell file is: 
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.366 +0800 o.a.d.p.t.a.s.BaseLinuxShellInterceptorBuilder:[65] - ****************************** Script Content *****************************************************************
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.366 +0800 o.a.d.p.t.a.s.BaseLinuxShellInterceptorBuilder:[67] - #!/bin/bash
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
${PYTHON_LAUNCHER} /tmp/dolphinscheduler/exec/process/default/12796470742656/12807950360608_3/5/5/py_5_5.py
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.366 +0800 o.a.d.p.t.a.s.BaseLinuxShellInterceptorBuilder:[68] - ****************************** Script Content *****************************************************************
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.366 +0800 o.a.d.p.t.a.s.BaseShellInterceptor:[46] - Executing shell command : sudo -u default -i /tmp/dolphinscheduler/exec/process/default/12796470742656/12807950360608_3/5/5/5_5.sh
[WI-5][TI-5] - [INFO] 2024-03-04 21:47:37.368 +0800 o.a.d.p.t.a.AbstractCommandExecutor:[154] - process start, process id is: 14597
[WI-0][TI-5] - [INFO] 2024-03-04 21:47:37.702 +0800 o.a.d.s.w.r.l.TaskInstanceExecutionRunningEventAckListenFunction:[44] - Receive TaskInstanceExecutionRunningEventAck: TaskInstanceExecutionRunningEventAck(taskInstanceId=5, success=true)
[WI-0][TI-5] - [INFO] 2024-03-04 21:47:37.706 +0800 o.a.d.s.w.r.l.TaskInstanceExecutionInfoEventAckListenFunction:[45] - Receive TaskInstanceExecutionInfoEventAck: TaskInstanceExecutionInfoEventAck(success=true, taskInstanceId=5)
[WI-0][TI-0] - [INFO] 2024-03-04 21:47:38.368 +0800 o.a.d.p.t.a.AbstractTask:[169] -  -> 
	sudo: unable to change directory to /home/default: No such file or directory
	/tmp/dolphinscheduler/exec/process/default/12796470742656/12807950360608_3/5/5/5_5.sh: line 4: /tmp/dolphinscheduler/exec/process/default/12796470742656/12807950360608_3/5/5/py_5_5.py: Permission denied
```

`default check successfully` but `unable to change directory to /home/default`, though it seems this error doesn't affect the task's execution (if so, why is `sudo` present here?)
actually it's the same issue with #844, the root cause appears to be [OSUtils.java#L232](https://github.com/apache/dolphinscheduler/blame/04a6b0d2814c69b056639f65546ffd62ead22321/dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java#L232) using 'useradd' without '-m' flag so `default` user created by the worker has no home dir.
By the way, the "permission denied" issue caused by #15085 should also be fixed reasonably. It's frustrating and confusing not being able to run 'hello world' out of the box. Perhaps we should improve the Docker image for the worker? Providing optional runtime via .env or some other form could be a solution.

### What you expected to happen

no error msg `unable to change directory to /home/default`

### How to reproduce

just install ds in docker compose following the tutorial and create a hello world python task

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi, Would you like to fix it? @zero-element

**Comment by zero-element** [comment]
> Hi, Would you like to fix it? @zero-element

yes, i'm submitting a pr

**Comment by Smilewh888** [comment]
你好我也是在docker环境这个问题，但这个3.2.2版本不知道什么时候发布？ 我现在能在本地解决嘛，好像大概理解你的意思。
![image](https://github.com/apache/dolphinscheduler/assets/75770940/e6db647e-2a0c-4b06-bab9-fa0555c03cc6)

然后我进入worker容器创建这个 /home/default 后报错
![image](https://github.com/apache/dolphinscheduler/assets/75770940/11ae6e57-b026-42c1-a86d-58165e139eb0)

我使用的admin账号，默认租户是default 
我是不是应该进入到容器  执行 你提交的代码，我不太清楚
sudo useradd -m -g default default ？

**Comment by Smilewh888** [comment]
@zero-element [#](https://github.com/apache/dolphinscheduler/issues/15669#issuecomment-1980542907)

**Comment by zui01** [comment]
> 你好我也是在docker环境这个问题，但这个3.2.2版本不知道什么时候发布？ 我现在能在本地解决嘛，好像大概理解你的意思。 ![image](https://private-user-images.githubusercontent.com/75770940/310454127-e6db647e-2a0c-4b06-bab9-fa0555c03cc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODQ4MjUsIm5iZiI6MTcxMDM4NDUyNSwicGF0aCI6Ii83NTc3MDk0MC8zMTA0NTQxMjctZTZkYjY0N2UtMmEwYy00YjA2LWJhYjktZmEwNTU1YzAzY2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAyNDg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNTY1N2Y2OTc0MGZmNWFmYTk2OGE2MWMwMzcxNDJkOTcxZGJjNTA5MzkzOTJiMjlkOGZmZjE3MTUzNDk2OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4br28VFfK0CCyfgrrn_MCjHXABXeNJnFbj0dIeFzjY4)
> 
> 然后我进入worker容器创建这个 /home/default 后报错 ![image](https://private-user-images.githubusercontent.com/75770940/310454259-11ae6e57-b026-42c1-a86d-58165e139eb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODQ4MjUsIm5iZiI6MTcxMDM4NDUyNSwicGF0aCI6Ii83NTc3MDk0MC8zMTA0NTQyNTktMTFhZTZlNTctYjAyNi00MmMxLWE4NmQtNTgxNjVlMTM5ZWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAyNDg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MmYwMGUwOWMzMzljZjFmMWYzYjlkN2ZiNzFiOWMyOWY1OWQ0MzhjNWM0OGI2ZjZlZGVhZGU5ZDYwYTVjOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Ng_1T4aBMGO7eExy1MXQmzYyecq7x6ThYE44gYrYxc)
> 
> 我使用的admin账号，默认租户是default 我是不是应该进入到容器 执行 你提交的代码，我不太清楚 sudo useradd -m -g default default ？

ds在3.1.X的文档里提过一嘴，如果ds中的租户在系统里没有对应的账户他会自己创建，但是该功能从3.1.7开始就不好用，所以只能你手工修复，添加该linux用户即可，同时创建对应用户，还有，不建议容器环境使用ds

**Comment by z201** [comment]
我在docker环境在使用；在自定义的启动脚本中默认给容器创建了default用户解决这个问题。

     # 为 worker 容器创建 default 用户
        if [ "$container" = "dolphinscheduler-worker" ]; then
            echo "为 $container 创建 default 用户..."
            docker exec $container groupadd -g 1000 default || true
            docker exec $container useradd -u 1000 -g default -m -s /bin/bash default || true
        fi
