### ISSUE TITLE
[Bug] [Workflow task does not execute] Workflow task does not execute

### ISSUE THREAD

**Issue by 1183176816** [apache/dolphinscheduler#15685]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

某个任务中的配置变量，变量值不是ds内置值，则在执行工作流时，此任务一直是提交成功状态
比如A任务 配置变量 param 值设置为$[testStr]，则在执行工作流时，执行到A任务就一直时提交成功状态

### What you expected to happen

比如A任务 配置变量 param 值设置为$[testStr]，则在执行工作流时，执行到A任务就一直时提交成功状态

### How to reproduce

比如A任务 配置变量 param 值设置为$[testStr]，则在执行工作流时，执行到A任务就一直时提交成功状态

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please use English to describe.
