### ISSUE TITLE
Is it completely impossible to work now? Whether it's fat jar or classpath

### ISSUE THREAD

**Issue by Smilewh888** [apache/dolphinscheduler#15682]
> It seems that -jar cannot work with -cp together,-jar cannot get -cp's libraries,Is your shell worked success？have you test your shell script?

Yes, -jar can not work with -cp.

Once we use -jar then the jar should be a fat jar, the better way is to add ext jar by set Class-Path at `MANIFEST.MF`.

So Can we add entry class in UI and use -cp to refactor this.

_Originally posted by @ruanwenjun in https://github.com/apache/dolphinscheduler/pull/15645#discussion_r1515596966_

**Comment by Smilewh888** [comment]
Can both classpath and fat jar be supported?

Is it completely impossible to work now? Whether it's fat jar or classpath

![image](https://github.com/apache/dolphinscheduler/assets/75770940/9e7f819a-3df3-436f-bf5d-b62ebad6cbe6)

Can you explain this Java command?

${JAVA_HOME}/bin/java -classpath .:/tmp~~/285:/tmp/~~~/285//tmp/~~~/285/deploy/SSHPing-3.2.0.jar -jar /tmp/~~~/285//tmp/~~~/285/deploy/SSHPing-3.2.0.jar

**Comment by SbloodyS** [comment]
Please use issue template.
