### ISSUE TITLE
[Bug] [dolphinscheduler-scheduler-plugin] Scheduling state exception

### ISSUE THREAD

**Issue by cqutwangyu** [apache/dolphinscheduler#15697]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/apache/dolphinscheduler/assets/26395835/9723cb52-900e-4596-afe6-4bccc7aa11de)
![image](https://github.com/apache/dolphinscheduler/assets/26395835/c150aa32-f315-4e82-9706-dae8bee3e3f9)
A large number of submitted tasks are not executing properly, and the status is wrong, and the task cannot be closed.

### What you expected to happen

pass

### How to reproduce

pass

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You should check the status of master. @cqutwangyu

**Comment by zui01** [comment]
the master server is down

**Comment by CallMeKingsley97** [comment]
Have you figure out what's wrong with your master server?

**Comment by cqutwangyu** [comment]
@SbloodyS @Anubisxcw @CallMeKingsley97 
这个问题发生在：手动执行sh脚本停止Seatunnel的集群及任务后，并且重启DS的standalone-server无法解决。任务状态始终保持在运行中，实际上任务早已经被杀死。
