### ISSUE TITLE
[Bug] [UI] The 'Close' button is unresponsive in the new tab opened by clicking on the workflow name.

### ISSUE THREAD

**Issue by jiangwwwei** [apache/dolphinscheduler#15698]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.Opens in a new tab by clicking on the workflow name;
2. The 'Close' button is unresponsive;
![image](https://github.com/apache/dolphinscheduler/assets/52434907/64678d44-eaae-4ce9-8173-7075b2e3e7ee)
![image](https://github.com/apache/dolphinscheduler/assets/52434907/6329fb9d-a5fc-4468-9d1b-457ac6c55e46)

### What you expected to happen

After clicking the 'Close' button, 
return to the  workflow definition/instance list page.

### How to reproduce

version:3.2.1
1.Opens in a new tab by clicking on the workflow name;
2. The 'Close' button is unresponsive;

Editing the workflow through the 'Edit' button doesn't open a new tab, and the 'Close' button works correctly.

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by arlendp** [comment]
I'd like to submit a pr to resolve this issue
