### ISSUE TITLE
[Bug][dolphinScheduler-task-seatunnel] Script suffixes can be .conf or .json

### ISSUE THREAD

**Issue by xi-xi-jun** [apache/dolphinscheduler#15706]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Dear DolphinScheduler  Development Team,

First and foremost, I would like to express my gratitude for the exceptional tool you have provided. The flexibility and efficiency of SeaTunnel in data processing are immensely valuable to our projects.

During my experience with SeaTunnel, I noticed that when users opt for the HOCON format for scriptwriting, the generated script files have a .conf extension. Conversely, when scripts are written in JSON format, the logical expectation is for the file extension to be .json. However, it seems that the current implementation defaults to a .conf extension through hardcoding, which could lead to execution failures when JSON format scripts are used.

To enhance user experience and increase flexibility in script format support, I suggest adding an option button in the UI's task definition section that allows users to flexibly choose the file type extension (either .conf or .json) based on the script format they are using. Such an improvement would not only prevent potential execution errors but also provide a more intuitive recognition of script formats, making the use of SeaTunnel more user-friendly and efficient.

I believe this minor enhancement could significantly improve the usability and accuracy of SeaTunnel. Thank you for considering my suggestion; I look forward to your response.

![image](https://github.com/apache/dolphinscheduler/assets/113566654/ba01856b-e801-4747-b5a1-6452c33b702c)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xi-xi-jun** [comment]
If you currently want to use json scripts instead of HOCON scripts, you can change the .conf in the dolphinscheduler-task-seatunnel project to .json and repackage and compile it.
![image](https://github.com/apache/dolphinscheduler/assets/113566654/231b9f80-5209-4e1b-ab83-06111df35623)

**Comment by CallMeKingsley97** [comment]
Do you want to contribute for this improvement? This is a good first issue

**Comment by xinxingi** [comment]
@ruanwenjun please assign to me

**Comment by caishunfeng** [comment]
This issue looks more like a bug, so I change the label for it.
