### ISSUE TITLE
[Feature]suggest to configure the IP address in the configuration file

### ISSUE THREAD

**Issue by yyccww123** [apache/dolphinscheduler#15703]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When multiple network adapters are used, the IP address is incorrectly obtained. As a result, the worker cannot work.
so suggest to configure the IP address in the configuration file

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yyccww123** [comment]
or get the IP address through hosts

**Comment by fuchanghai** [comment]
hi @yyccww123  #11660  this PR maybe can fix you issue

**Comment by fuchanghai** [comment]
@ruanwenjun @EricGao888 do we need this feature?

**Comment by ruanwenjun** [comment]
Do you mean you have multiple network interfaces and want to choose the specific one to expose as the worker RPC address?
We can use `dolphin.scheduler.network.interface.preferred=` to specify which network interface will be used.

**Comment by yyccww123** [comment]
> Do you mean you have multiple network interfaces and want to choose the specific one to expose as the worker RPC address? We can use `dolphin.scheduler.network.interface.preferred=` to specify which network interface will be used.

In my production environment, there are two IP addresses, one is the service IP address, the other is the management IP address, I can only use the service IP address, and I cannot modify the network adapter configuration. The service IP address can be obtained normally when DS 3.1.8 is available, but after I update to 3.2.1, I cannot obtain this address. As a result, the management IP address obtained cannot run all my tasks. I am currently unable to use the 3.2.1 version, if you can fix the problem would be appreciated.

**Comment by yyccww123** [comment]
> Do you mean you have multiple network interfaces and want to choose the specific one to expose as the worker RPC address? We can use `dolphin.scheduler.network.interface.preferred=` to specify which network interface will be used.

In my production environment, there are two IP addresses, one is the service IP address, the other is the management IP address, I can only use the service IP address, and I cannot modify the network adapter configuration. The service IP address can be obtained normally when DS 3.1.8 is available, but after I update to 3.2.1, I cannot obtain this address. As a result, the management IP address obtained cannot run all my tasks. I am currently unable to use the 3.2.1 version, if you can fix the problem would be appreciated.

**Comment by yyccww123** [comment]
dolphin.scheduler.network.interface.preferred= 
is working. thanks.

**Comment by ruanwenjun** [comment]
> dolphin.scheduler.network.interface.preferred=
> is working. thanks.

OK, I will close this issue.
