### ISSUE TITLE
[Bug] [service] built-in parameters like '$[yyyy-MM-dd]' defined in shell task scripts do not work when the task does not set any parameters

### ISSUE THREAD

**Issue by songwenyong** [apache/dolphinscheduler#15711]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When we start a job in a Complement Data situation, extended built-in parameters like '$[yyyy-MM-dd]' defined in shell task scripts do not work when the task does not set any parameters.

![1](https://github.com/apache/dolphinscheduler/assets/119404633/078d1c82-33fd-4772-9876-9e5f832faba9)
![2](https://github.com/apache/dolphinscheduler/assets/119404633/1ceb5caa-2c08-4f2c-b3df-bf0ff830c214)
![3](https://github.com/apache/dolphinscheduler/assets/119404633/8a810ac1-b413-433b-967a-991bbc8bc61f)

### What you expected to happen

We expect to return the scheduling time2024-02-01, but the result is the system time2024-03-14.

### How to reproduce

In version 3.1.9, the CuringGlobalParams class in the master node returns null when building task parameters, as globalParams, localParams, and varParams are all empty. This results in the system.datetime variable not being populated into the context.
![4](https://github.com/apache/dolphinscheduler/assets/119404633/1b789f21-7a8a-4eb2-8093-6ba33d16b175)

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songwenyong** [comment]
Due to code refactoring, CuringGlobalParams has been renamed to CuringParamsServiceImpl in the latest dev branch. This will prevent the latest changes from being merged into the 3.1.x version. Can someone tell me what to do?

**Comment by fuchanghai** [comment]
hi @songwenyong  ```yyyy-MM-dd ``` which is a built-in parameter of DS. It uses the current system time. Perhaps during the complement operation, we should get the complement event. cc @ruanwenjun WDYT?

**Comment by yyccww123** [comment]
${system.biz.date} is working.

**Comment by songwenyong** [comment]
> hi @songwenyong `yyyy-MM-dd ` which is a built-in parameter of DS. It uses the current system time. Perhaps during the complement operation, we should get the complement event. cc @ruanwenjun WDYT?

This bug has already been fixed in the latest version 3.2.1

**Comment by LiJie20190102** [comment]
@songwenyong  @fuchanghai  Can you tell me the corresponding PR or how I can fix this issue
