### ISSUE TITLE
[Improvement][UI] Improve the procedure of setting the scheduler by some shortcuts.

### ISSUE THREAD

**Issue by calvinjiang** [apache/dolphinscheduler#15728]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We usually set the scheduler that runs the workflow periodically most of the time, like 12:00:00 each day. But now we just need six steps to set the value. So I suppose to add some shortcuts that must be really convenient.

![image](https://github.com/apache/dolphinscheduler/assets/4928204/b79f91a8-a655-425a-84fe-81cbeef5c9ae)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Please provide more details about the shortcuts.
