### ISSUE TITLE
[Bug] [Woker] org.apache.dolphinscheduler.plugin.task.api.TaskException: TenantCode: default doesn't exist

### ISSUE THREAD

**Issue by NCUZK** [apache/dolphinscheduler#15734]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

***********************************************************************************************
[INFO] 2024-03-18 18:18:50.817 +0800 - *********************************  Load task instance plugin  *********************************
[INFO] 2024-03-18 18:18:50.817 +0800 - ***********************************************************************************************
[INFO] 2024-03-18 18:18:50.879 +0800 - Send task status RUNNING_EXECUTION master: dolphinscheduler-worker-2.dolphinscheduler-worker-headless:1234
[ERROR] 2024-03-18 18:18:50.886 +0800 - Task execute failed, due to meet an exception
org.apache.dolphinscheduler.plugin.task.api.TaskException: TenantCode: default doesn't exist
	at org.apache.dolphinscheduler.server.worker.utils.TaskExecutionContextUtils.getOrCreateTenant(TaskExecutionContextUtils.java:74)
	at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecutor.beforeExecute(WorkerTaskExecutor.java:215)
	at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecutor.run(WorkerTaskExecutor.java:167)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
[INFO] 2024-03-18 18:18:50.886 +0800 - Cancel the task successfully
[INFO] 2024-03-18 18:18:50.891 +0800 - Get a exception when execute the task, will send the task status: FAILURE to master: dolphinscheduler-worker-2.dolphinscheduler-worker-headless:1234
[INFO] 2024-03-18 18:18:50.894 +0800 - FINALIZE_SESSION

### What you expected to happen

可以正常运行工作流实例

### How to reproduce

3.2.1 版本运行工作流实例

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Duplicated with #15637.
