### ISSUE TITLE
[Bug] [preferences] Project Preferences is enabled, but when manual  start workflow, worker group and tenant still is default.

### ISSUE THREAD

**Issue by yyccww123** [apache/dolphinscheduler#15731]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.Project Preferences is enabled, but when manual  start workflow, worker group and tenant still is default.
2.I modify worker group and tenant to the correct value, choice completment data and serial execution, select multiple days at a time, the workflow succeeds on the first day, but the tenant is restored to the default value later, resulting in a failure.

### What you expected to happen

when manual  start workflow, get project Preferences.

### How to reproduce

when manual  start workflow.

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Duplicated with https://github.com/apache/dolphinscheduler/issues/15648, this bug should already be fixed.

**Comment by ruanwenjun** [comment]
I will close this issue.
