### ISSUE TITLE
Resource file authorization issues

### ISSUE THREAD

**Issue by yangsir8888** [apache/dolphinscheduler#15748]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

dolphinscheduler version:3.2.1
管理员在用户管理中给其他用户授权资源文件的时候下拉列表什么都不显示,显示无数据,我的资源中心是有文件列表的，但是授权的时候没有授权文件列表
![image](https://github.com/apache/dolphinscheduler/assets/26586301/248a26b2-7c5b-4420-b93d-ff86ea09c5d4)
![image](https://github.com/apache/dolphinscheduler/assets/26586301/efbe4c7f-5edb-4db0-baa8-5b284edc7ac1)
资源中心目录如下:
![image](https://github.com/apache/dolphinscheduler/assets/26586301/8d284dd2-9c8b-4134-9677-3615e437edef)

### What you expected to happen

资源授权的时候管理员无法给其他用户授权，就会导致项目授权之后，资源无法授权，任务工作流里面无法引用这些数据文件

### How to reproduce

修复这个bug

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ly109974** [comment]
version 3.2.1 , I'm test already , No separate authorization is required. I forgot which version started with.

**Comment by SbloodyS** [comment]
This feature is deprecated.

**Comment by liunaijie** [comment]
> This feature is deprecated.

@SbloodyS 
Hi, after this feature deprecated, how can we grant the file access to other user?
Like we have some file created by admin that need share to all user, but other user's tenant is different, so they can access those files.
If all user use same tenant, it can see those files, but it will let the user see some file not belong to him, so i think it's not a good option.
