### ISSUE TITLE
[Bug] When using the SQL component, an error is reported when executing the workflow instance. The database address reported in the error is different from the database address configured in the SQL component.

### ISSUE THREAD

**Issue by xiaotan1** [apache/dolphinscheduler#15746]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

版本：使用版本3.21

问题：创建工作流-SQL组件，执行工作流报错。

报错内容：
[执行报错日志文件.log](https://github.com/apache/dolphinscheduler/files/14664494/default.log)
![image](https://github.com/apache/dolphinscheduler/assets/22851494/d4c776f0-e612-4c4f-917e-355e8752379a)

问题详细描述：
我在创建SQL组件时，使用的数据源实例，不是报错的数据库ip。而是下图中的ip。
我使用的10.56.20.29，但是报错确实10.1.17.201（17.201是dolphinscheduler的部署机器，也是dolphinscheduler初始化mysql数据库的机器）
![image](https://github.com/apache/dolphinscheduler/assets/22851494/aa1fdc72-3551-4c49-81e0-be1cea2a4f4a)
![image](https://github.com/apache/dolphinscheduler/assets/22851494/ea41fde4-c6ef-493c-918d-373a577ace48)

请教大家，是否遇到过上述问题，请问改如何解决

### What you expected to happen

我在创建SQL组件时，使用的数据源实例，不是报错的数据库ip。而是下图中的ip。
我使用的10.56.20.29，但是报错确实10.1.17.201

### How to reproduce

1. 新建数据源
2. 新建工作流-sql组件
3. 执行工作流

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shangeyao** [comment]
I am unable to reproduce the bug through the steps you described. Please check if the connection information in t_ds_datasource table is correct.

**Comment by xiaotan1** [comment]
> 我无法通过您描述的步骤重现该错误。请检查t_ds_datasource表中的连接信息是否正确。

非常感谢，我刚刚解决了上面的问题。当我的数据源名称，配置中文的时候。 就会出现上述错误。当数据源名称为英文时，可以正常执行工作流。
