### ISSUE TITLE
[Bug] [Master] fail when submit workflow instance

### ISSUE THREAD

**Issue by HSLife1991** [apache/dolphinscheduler#15753]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Caused by: org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 2
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:80)

18:18
 at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:650)
        at org.apache.dolphinscheduler.server.master.runner.MasterSchedulerBootstrap.run(MasterSchedulerBootstrap.java:134)
Caused by: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.TooManyResultsException: Expected one result
(or
null) to be returned by selectOne(), but found: 2
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
        at com.sun.proxy.$Proxy134.selectOne(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:160)
        at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:89)
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
        at com.sun.proxy.$Proxy175.queryByTypeAndJobId(Unknown Source)
        at org.apache.dolphinscheduler.service.process.TriggerRelationServiceImpl.queryByTypeAndJobId(TriggerRelationServiceImpl.java:50)
        at org.apache.dolphinscheduler.service.process.TriggerRelationServiceImpl.saveProcessInstanceTrigger(TriggerRelationServiceImpl.java:65)
        at org.apache.dolphinscheduler.service.process.ProcessServiceImpl.handleCommand(ProcessServiceImpl.java:342)
        at org.apache.dolphinscheduler.service.process.ProcessServiceImpl$$FastClassBySpringCGLIB$$9d3e18f9.invoke(<generated>)

### What you expected to happen

correct create workflow instance

### How to reproduce

1.create a workflow with no scheduler
2.run the workflow

### Anything else

no

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by KevinLvLight** [comment]
We met the same problem, and we found the SQL according log:
[TriggerRelationMapper.xml](https://github.com/apache/dolphinscheduler/blob/dev/dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TriggerRelationMapper.xml)

`<sql id="baseSql">
        id, trigger_code, trigger_type, job_id, create_time, update_time
    </sql>

    <select id="queryByTypeAndJobId" resultType="org.apache.dolphinscheduler.dao.entity.TriggerRelation">
        select
        <include refid="baseSql"/>
        from t_ds_trigger_relation
        WHERE trigger_type = #{triggerType} and job_id =  #{jobId}
    </select>
`
But we donot known how this occured and how to solve it.

**Comment by peak-xu** [comment]
I encountered the same problem

**Comment by xuet0ng** [comment]
meet the same problem. I take following 3 steps  to temporarily avoid this issue:
1. backup t_ds_trigger_relation
2. delete from t_ds_trigger_relation
3. restart dolphinscheduler

**Comment by xuet0ng** [comment]
the job_id of t_ds_trigger_relation based on id of t_ds_command which is auto incr by mysql
but the auto incr is reset by some way (maybe truncate in a dev env.)

**Comment by peak-xu** [comment]
> the job_id of t_ds_trigger_relation based on id of t_ds_command which is auto incr by mysql but the auto incr is reset by some way (maybe truncate in a dev env.)

It seems like a serious bug, but why haven't others encountered it?

**Comment by SbloodyS** [comment]
Did you upgrade from the lower version to this version?

**Comment by originxiong** [comment]
> Did you upgrade from the lower version to this version?

this problem have nothing to do with version.
ealier issue has pointed that t_ds_command auto incre id cause this problem
https://github.com/apache/dolphinscheduler/issues/15543

**Comment by sad-nickname** [comment]
将t_ds_command表的自增id记录改为t_ds_trigger_relation表的job_id字段的最大数值加1似乎可以暂时解决这个问题，奇特的bug（It seems that temporarily solving the issue by changing the auto-increment id value in the t_ds_command table to be the maximum value of the job_id field in the t_ds_trigger_relation table plus 1 can work. A rather peculiar bug.）

**Comment by dwave** [comment]
我也遇到了类似的问题，gemini给出的方法如下，

这是一个 DolphinScheduler Master 报错，核心问题在于 org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 2。

分析可能原因：

这个错误表明在使用 MyBatis-Plus 的 selectOne() 方法进行数据库查询时，期望只返回一个结果（或不返回），但实际返回了两个或更多的结果。这通常发生在以下几种情况：

数据重复或脏数据： 在 t_ds_trigger_relation 表中，根据 queryByTypeAndJobId 方法的查询条件，存在多条满足条件的记录。

queryByTypeAndJobId 方法很可能根据 type (触发器类型) 和 job_id (任务或流程实例ID) 进行查询。
在某些场景下，例如：
同一个任务/流程实例被重复触发，并且每次触发都创建了新的 t_ds_trigger_relation 记录，但旧记录没有被正确清理或更新。
数据导入或手动修改数据库时，不小心插入了重复数据。
DolphinScheduler 在处理某些异常情况时，未能正确维护 t_ds_trigger_relation 表的数据一致性。
SQL 查询逻辑错误： queryByTypeAndJobId 方法对应的 Mapper XML 或注解中的 SQL 语句编写有误，导致在正常情况下也会返回多条数据。例如，查询条件不够精确，或者没有使用 LIMIT 1。

并发问题： 尽管不太可能直接导致 TooManyResultsException，但在极端并发场景下，如果涉及到数据插入和查询的竞态条件，理论上也有可能发生。但更直接的原因还是数据本身的重复。

DolphinScheduler Bug： 这是一个可能存在的缺陷，即在某些特定操作下，DolphinScheduler 会错误地创建或不清理 t_ds_trigger_relation 表中的重复数据。

修改建议：

1. 诊断和数据清理（首要任务）：

识别重复数据：
登录到 DolphinScheduler 数据库。
执行类似以下的 SQL 查询，查看 t_ds_trigger_relation 表中是否存在 type 和 job_id 组合重复的记录。请根据实际情况调整 type 和 job_id 的值，这些值通常可以从 DolphinScheduler 的任务或工作流执行日志中找到，或者结合报错信息中的 command 42 (这通常是流程实例ID)。
SQL

SELECT type, job_id, COUNT(*)
FROM t_ds_trigger_relation
GROUP BY type, job_id
HAVING COUNT(*) > 1;
如果查询结果显示有重复，进一步查看这些重复记录的详细信息，例如 id, create_time, update_time 等，以判断哪些是“正确”的，哪些是“错误”的。
SQL

SELECT *
FROM t_ds_trigger_relation
WHERE type = 'your_type' AND job_id = 'your_job_id'; -- 替换为实际的type和job_id
清理重复数据：
在确定重复数据且了解哪些是需要保留的情况下，务必在操作前备份数据库。
可以选择删除多余的重复记录，只保留一条。通常，可以保留 create_time 最新或 id 最大的那一条。
SQL

DELETE FROM t_ds_trigger_relation
WHERE id NOT IN (
    SELECT MAX(id)
    FROM t_ds_trigger_relation
    GROUP BY type, job_id
) AND (type, job_id) IN (
    SELECT type, job_id
    FROM t_ds_trigger_relation
    GROUP BY type, job_id
    HAVING COUNT(*) > 1
);
注意： 上述 SQL 是一个通用示例，请根据实际情况，特别是根据您对哪条记录应该被保留的判断，谨慎修改。
2. 应用程序代码层面（如果诊断发现不是数据问题）：

如果清理数据后问题依然存在，或者您怀疑是代码逻辑问题，则需要深入到 DolphinScheduler 源代码：

审查 TriggerRelationServiceImpl.queryByTypeAndJobId 方法：
定位到 org.apache.dolphinscheduler.service.process.TriggerRelationServiceImpl 类中的 queryByTypeAndJobId 方法。
检查该方法内部调用的 Mapper 方法（很可能是 TriggerRelationMapper 中的 queryByTypeAndJobId）。
检查对应的 Mapper XML 文件（或注解）中的 SQL 语句，确保它的查询条件是精确的，并且在正常情况下只会返回一条记录。如果业务逻辑允许返回多条，那么就不应该使用 selectOne()，而应该使用 selectList()，并在业务逻辑中处理多条结果。
考虑添加唯一索引：
如果 type 和 job_id 的组合在业务上应该是唯一的，可以在 t_ds_trigger_relation 表上为 (type, job_id) 添加唯一索引。这将从数据库层面强制保证不会出现重复数据，从而避免 TooManyResultsException。
在添加唯一索引前，必须先清理掉所有重复数据，否则添加索引会失败。
添加唯一索引的 SQL 示例：
SQL

ALTER TABLE t_ds_trigger_relation ADD UNIQUE INDEX uk_type_job_id (type, job_id);
请根据实际的列名和索引命名规范调整。
3. DolphinScheduler 版本升级：

检查您当前使用的 DolphinScheduler 版本。
查阅 DolphinScheduler 的官方文档或 Release Notes，看是否有类似 Bug 的修复。
如果存在相关 Bug 并已在新版本中修复，考虑升级 DolphinScheduler 到最新稳定版本。
总结：

这个错误最常见的根源是数据库中存在重复数据。因此，第一步也是最重要的一步是诊断并清理 t_ds_trigger_relation 表中的重复记录。如果数据层面没有问题，再考虑代码逻辑或版本升级。在进行任何数据库操作之前，请务必进行数据备份。
