### ISSUE TITLE
Retry on failure, set the retry interval on failure > 0, and the workflow task will not be retried.

### ISSUE THREAD

**Issue by 772510387** [apache/dolphinscheduler#15763]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![03](https://github.com/apache/dolphinscheduler/assets/137851143/96fc10f8-d465-4883-bab5-3ab95bc0ad16)
![04](https://github.com/apache/dolphinscheduler/assets/137851143/bfdb2467-c35c-4c15-9bc3-a232dc764b91)
![01](https://github.com/apache/dolphinscheduler/assets/137851143/2a66c7f1-d30f-493d-91de-ba97dd4aecf8)
![02](https://github.com/apache/dolphinscheduler/assets/137851143/2363eecf-042d-49e5-93a7-a7c125aa75ff)
![05](https://github.com/apache/dolphinscheduler/assets/137851143/71d00217-84be-454b-8486-ef320b1340ff)
遇到一个情况，对于工作流中的任务设置失败重试，当我设置失败重试间隔>0后，在工作流中的任务并不会重试，但是我的失败重试间隔=0的情况下，工作流中的任务会重试；很多工作流不会停止，是因为我设置了重跑，而且我设置了重跑间隔，但是在工作流中，不会重跑，导致工作流一直在等待任务的重跑结束

### What you expected to happen

存在解决方法吗，或者新版本中会出现这个问题吗，老版本中是否其他人遇到过这个问题，他们怎么解决的

### How to reproduce

![03](https://github.com/apache/dolphinscheduler/assets/137851143/d50bc05f-ec09-4d18-8dde-ba36e8afcac9)
![04](https://github.com/apache/dolphinscheduler/assets/137851143/00c504b6-f3c0-46a2-86b8-3c3f4f82f368)
![01](https://github.com/apache/dolphinscheduler/assets/137851143/5f63efb7-c1e6-464e-bf12-0b541ae7acfb)
![02](https://github.com/apache/dolphinscheduler/assets/137851143/d0c4f0d2-87ec-41ff-a3c0-e277375e5006)
![05](https://github.com/apache/dolphinscheduler/assets/137851143/41c2c6b3-b14a-4f91-a689-99d52c8279e8)

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ly109974** [comment]
![image](https://github.com/apache/dolphinscheduler/assets/103415610/05ce6eba-2d15-466b-8772-8fa1f0c4f0cd)
version 3.1.9 , no such thing happened
