### ISSUE TITLE
[Improvement][workflow] Isn’t this gantt and alter alarm good?

### ISSUE THREAD

**Issue by stevqin** [apache/dolphinscheduler#15779]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

甘特图就应该要有甘特图所该有的样子
分类清晰, 双击左边的任务名，可以弹出任务日志；
![dolphinScheduler甘特图](https://github.com/apache/dolphinscheduler/assets/57753404/4873543e-ed86-48ef-b453-3972dd7a7a29)

消息告警，就应该简洁明了， 去除一些无所谓的字段
![dolphinScheduler告警提醒](https://github.com/apache/dolphinscheduler/assets/57753404/fe9411d2-ac0c-4b56-a17e-ec8c5967a834)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please use english to describe. @stevqin
