### ISSUE TITLE
[Bug] [Module Name] Bug title 

### ISSUE THREAD

**Issue by fafasfdaw** [apache/dolphinscheduler#15782]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

我把dolphinscheduler和ruoyi集成casdoor后，没法在ruoyi登录后直接访问dolphinscheduler的页面

### What you expected to happen

在文档里面甚至没有任何解释

### How to reproduce

希望能帮忙解释下

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please use english to describe and use the correct title.
