### ISSUE TITLE
[Improvement][Task Log] Adding color display for log levels and time in task log.

### ISSUE THREAD

**Issue by batmanneverdie** [apache/dolphinscheduler#15785]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, DolphinScheduler does not add color display for log level and log time in Task instance log, which is not effective when locating key content when there is a lot of log content.

It is recommended to refer to the log file color display function of vscode to improve the user experience when viewing task logs.

DS 3.1.x task instance log:
![image](https://github.com/apache/dolphinscheduler/assets/41139080/4c23b553-e793-4b19-b953-4a439e60418b)

Color display effect of vscode log file for reference:
![image](https://github.com/apache/dolphinscheduler/assets/41139080/74311bef-f81f-457a-a209-65091cdc6992)
_In order to make the display more beautiful, I modified the some log printing format in SQL task._

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by arlendp** [comment]
if no one is working on this, i'd like to deal with it.
