### ISSUE TITLE
[Bug] [Module Name] Local Address all-zero monitoring

### ISSUE THREAD

**Issue by q4q5q6qw** [apache/dolphinscheduler#15784]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I modified jvm_args_env.sh, and added -Dserver.address startup parameter to the local IP, but only one port is bound to the local IP after the master, worker, alert, and api are started. For example, port 1235 of the worker service is bound, but port 1234 is not bound.

> [service@soc-job-service-0003 bin]$ netstat -ntlp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:50056           0.0.0.0:*               LISTEN      3727850/java        
tcp        0      0 192.168.0.1:2888     0.0.0.0:*               LISTEN      1373202/java        
tcp        0      0 192.168.0.1:9898     0.0.0.0:*               LISTEN      3498069/python3     
tcp        0      0 192.168.0.1:3888     0.0.0.0:*               LISTEN      1373202/java        
tcp        0      0 0.0.0.0:1234            0.0.0.0:*               LISTEN      3533851/java        
tcp        0      0 192.168.0.1:1235     0.0.0.0:*               LISTEN      3533851/java        
tcp        0      0 192.168.0.1:22       0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:39607         0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:38338         0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:38339         0.0.0.0:*               LISTEN      -                   
tcp        0      0 192.168.0.1:50053    0.0.0.0:*               LISTEN      3727850/java        
tcp        0      0 192.168.0.1:2181     0.0.0.0:*               LISTEN      1373202/java

### What you expected to happen

Port 1234 can also be bound to an IP address.

### How to reproduce

Run the vi command to open the jvm_args_env.sh file and add -Dserver.address=192.168.0.1 to the file.
Start the service.

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Did you want to modify the port of the worker-server?

**Comment by q4q5q6qw** [comment]
> Did you want to modify the port of the worker-server?

No, Now after starting, the output of using netstat -ntlp is:
tcp 0 0 0.0.0.0:1234 0.0.0.0:* LISTEN 3533851/java
tcp 0 0 192.168.0.1:1235 0.0.0.0:* LISTEN 3533851/java
I would like to be able to output:
tcp 0 0 192.168.0.1:1234 0.0.0.0:* LISTEN 3533851/java
tcp 0 0 192.168.0.1:1235 0.0.0.0:* LISTEN 3533851/java
