### ISSUE TITLE
[Bug] [process-instances] dolphinscheduler3.2.1 workflow instance query , resulted in a null return value for totalPage, which prevented pagination and only allowed querying of the first page

### ISSUE THREAD

**Issue by ucoypu** [apache/dolphinscheduler#15797]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

工作流实例没有分页，只能查询当前页，无法选择下一页
![1712109328069](https://github.com/apache/dolphinscheduler/assets/69502888/0506f8ee-7d90-40df-8409-37e5f13a7ad7)
![1712109369081](https://github.com/apache/dolphinscheduler/assets/69502888/1e4c9833-a8db-4182-9e11-30c4f3711b68)

### What you expected to happen

![1712109328069](https://github.com/apache/dolphinscheduler/assets/69502888/0506f8ee-7d90-40df-8409-37e5f13a7ad7)
![1712109369081](https://github.com/apache/dolphinscheduler/assets/69502888/1e4c9833-a8db-4182-9e11-30c4f3711b68)

### How to reproduce

![1712109328069](https://github.com/apache/dolphinscheduler/assets/69502888/0506f8ee-7d90-40df-8409-37e5f13a7ad7)
![1712109369081](https://github.com/apache/dolphinscheduler/assets/69502888/1e4c9833-a8db-4182-9e11-30c4f3711b68)

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by viosay** [comment]
同样问题，为什么关闭了呢

**Comment by Wdtu** [comment]
同遇到这个问题

**Comment by eyesmoons** [comment]
The PageInfo class is missing getter methods. Adding a getTotalPage method should suffice. You can refer to the previous version for guidance. just like this：
```java
public Integer getTotalPage() {
        if (pageSize == null || pageSize == 0) {
            pageSize = 7;
        }
        if (this.total % this.pageSize == 0) {
            return (this.total / this.pageSize) == 0 ? 1 : (this.total / this.pageSize);
        }
        return (this.total / this.pageSize + 1);
    }
```
