### ISSUE TITLE
[Bug] Global parameters of the workflow task do not take effect

### ISSUE THREAD

**Issue by xiaomi-box** [apache/dolphinscheduler#15792]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Global parameters of the workflow task do not take effect

### What you expected to happen

The time for obtaining global parameters is the same for each task node

### How to reproduce

The verification steps are as follows:
1. Create shell nodes 1 and 2
2. Set global parameters
3. Run the task node and find that the time obtained on the two nodes is inconsistent
![image](https://github.com/apache/dolphinscheduler/assets/45023902/db1df253-2c0f-4f05-81e0-981e747ea783)

![image](https://github.com/apache/dolphinscheduler/assets/45023902/1932a934-ed3e-47aa-8966-600ed06dfa02)

![image](https://github.com/apache/dolphinscheduler/assets/45023902/151aa7be-1ad3-430f-be41-9c2826c639de)

![image](https://github.com/apache/dolphinscheduler/assets/45023902/96d70011-1503-4e71-a4e3-d9531ca5bd96)

![image](https://github.com/apache/dolphinscheduler/assets/45023902/32b3dd1b-1ab7-4495-b34d-55e5c6bb8fd2)

![image](https://github.com/apache/dolphinscheduler/assets/45023902/5bcef300-550d-4230-ba3b-8f7906e02019)

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rickchengx** [comment]
The running time of these two tasks is different, so the output time is also different, follow the format `yyyyMMddHHmmss`

I'm not sure what you mean by the two outputs being inconsistent.

**Comment by ly109974** [comment]
> The running time of these two tasks is different, so the output time is also different, follow the format `yyyyMMddHHmmss`
> 
> I'm not sure what you mean by the two outputs being inconsistent.

What he wants is that the time in the two tasks is the same. 
I tested the time parameter which is a reference to the scheduling time. Since it is manually operated, there is no scheduling time, so it refers to the current system time. If it is normally scheduled, the time will be the same.  @xiaomi-box  You can test the online scheduling.

**Comment by xiaomi-box** [comment]
> > 这两个任务的运行时间不同，所以输出时间也不同，遵循格式`yyyyMMddHHmmss`
> > 我不确定你所说的两个输出不一致是什么意思。
> 
> 他想要的是两个任务中的时间是相同的。 我测试了时间参数，它是调度时间的参考。由于是手动操作，没有调度时间，所以指的是当前系统时间。如果正常安排的话，时间是一样的。 @xiaomi-box 您可以测试在线调度。

Version 3.1.8 does not have this problem, workflows are not configured for timed execution, the workflow is executed manually, and the time obtained by multiple task instances is the same

**Comment by ly109974** [comment]
Indeed, the version I tested in the morning was 3.1.9.
I just tested it in the development environment and found that there was indeed this problem.😂

**Comment by xiaomi-box** [comment]
@rickchengx @ly109974 
Hello, the current test shows that the global parameters take effect only when the schedule is executed, and the time obtained by manually executing the global parameters is inconsistent. Would you consider fixing this problem

**Comment by Squidyu** [comment]
Even if ${system. datatime} is referenced in the same task, it is not the same after a sleep because it itself references a variable rather than a constant

**Comment by xiaomi-box** [comment]
> 即使 ${system. datatime} 在同一个任务中被引用，在睡眠后它不一样，因为它本身引用的是变量而不是常量

I think this has nothing to do with variables, if it can only be used in timing, then how to use the complement
