### ISSUE TITLE
The issue of non pagination in the front-end interface

### ISSUE THREAD

**Issue by wangchuang07** [apache/dolphinscheduler#15796]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I am using version 3.2.1, and the number of front-end interface lists has exceeded the limit of this page, but it has not been paginated. For example, there are a total of 43 workflows on the interface, with 10 displayed on each page but only 1 page. Is there a configuration issue?
<img width="434" alt="bugpage" src="https://github.com/apache/dolphinscheduler/assets/38686005/c4006d17-ee2a-432c-bdd8-325d6f3e7537">

### What you expected to happen

The pagination of the interface is available。

### How to reproduce

We downloaded version 3.2.1 from the official website and followed the installation process on the website.

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Gallardot** [comment]
Fixed on https://github.com/apache/dolphinscheduler/pull/15619
