### ISSUE TITLE
[Bug] [DEPENDENT node] DAY DEPENDENT  BUG

### ISSUE THREAD

**Issue by LYL41011** [apache/dolphinscheduler#15807]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Production Issue: Both Workflow A and Workflow B run multiple times a day, once in the morning and once in the afternoon, pushing the latest data to production. Workflow B relies on Workflow A.

The situation for Workflow A is as follows:
The run at 2 o'clock succeeded at 4:08.
The run at 4 o'clock failed at 4:02.

The downstream process, Workflow B, is scheduled for 2:10 and 4:10.
When the downstream is scheduled at 4:10, the dependencies can pass, leading to data quality issues. (Because the 4 o'clock run of Workflow B should not be allowed to pass because of the successful 2 o'clock run, as it is intended to have the latest data from the 4 o'clock run)

After testing and reproduction, as shown in the diagram, Dolphin Scheduler considers the end time.

![dep1](https://github.com/apache/dolphinscheduler/assets/28033837/a611e610-2a5d-4f85-844a-51411a2b63da)

![dep](https://github.com/apache/dolphinscheduler/assets/28033837/f9067e33-1e93-46db-b04a-aaaee9d0760e)

### What you expected to happen

When the downstream is scheduled at 4:10, the dependencies can not pass,should faild

### How to reproduce

启动一个A工作流，shell脚本如下，制造成功实例，并且结束时间会晚于后面将要启动的那个失败工作流
sleep 1000
echo "success"
更改A工作流定义，shell脚本改成如下，目的是为了制造失败实例，再启动
sleep 10
exit -1
启动B工作流，该工作流依赖A工作流，可以看到B工作流会成功

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Currently the dependency judgment logic is to take the latest one within the same dependency cycle for judgment. Multiple calls per day should not rely on cycle configuration days. I think this is a usage issue rather than a bug.
