### ISSUE TITLE
[Bug] [K8S] Deploying version 3.2.1 with Helm, unable to pull the image.

### ISSUE THREAD

**Issue by NeufHuang** [apache/dolphinscheduler#15804]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```shell
helm install dolphinscheduler . --set image.tag=3.2.1 
coalesce.go:223: warning: destination for minio.ingress.tls is a table. Ignoring non-table value (false)
Error: INSTALLATION FAILED: failed post-install: timed out waiting for the condition
```
The image repository is incorrect and the image cannot be pulled.
```shell
 Failed to pull image "apache/dolphinscheduler/dolphinscheduler-api:3.2.1": failed to pull and unpack image "docker.io/apache/dolphinscheduler/dolphinscheduler-api:3.2.1": failed to resolve reference "docker.io/apache/dolphinscheduler/dolphinscheduler-api:3.2.1": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed 
```
```shell
ctr i pull apache/dolphinscheduler/dolphinscheduler-master:3.2.1
apache/dolphinscheduler/dolphinscheduler-master:3.2.1: resolving      |--------------------------------------| 
elapsed: 1.0 s                                         total:   0.0 B (0.0 B/s)                                         
apache/dolphinscheduler/dolphinscheduler-master:3.2.1: resolving      |--------------------------------------| 
elapsed: 1.2 s                                         total:   0.0 B (0.0 B/s)                                         
ctr: failed to resolve reference "apache/dolphinscheduler/dolphinscheduler-master:3.2.1": failed to do request: Head "https://apache/v2/dolphinscheduler/dolphinscheduler-master/manifests/3.2.1": EOF
```
Images cannot be found in the apache/dolphinscheduler repository.

The [values.yaml](https://github.com/apache/dolphinscheduler/blob/dev/deploy/kubernetes/dolphinscheduler/values.yaml) line 34, remove **/dolphinscheduler** can be deployed successfully.
```yaml
  # -- Docker image repository for the DolphinScheduler
  registry: apache
```

### What you expected to happen

deploy successfully.

### How to reproduce

helm install dolphinscheduler . --set image.tag=3.2.1 

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pegasas** [comment]
it seems this could be solved by change image to https://hub.docker.com/r/apache/dolphinscheduler-master/tags
