### ISSUE TITLE
The suggestion to add @Override to the run method in org.apache.dolphinscheduler.server.master.runner.WorkflowEventLooper class.

### ISSUE THREAD

**Issue by xjz-H** [apache/dolphinscheduler#15800]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The suggestion to add @Override to the run method in org.apache.dolphinscheduler.server.master.runner.WorkflowEventLooper class.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Squidyu** [comment]
yes 
you can submit a pr to fix

**Comment by SbloodyS** [comment]
Please provide a full detail design instead of a suggestion.
