### ISSUE TITLE
The continuous increase of workerserver processes, is this normal?

### ISSUE THREAD

**Issue by peak-xu** [apache/dolphinscheduler#15812]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

exccute commond `ps -eLf | grep WorkerServer | wc -l`,result is increase,until the service is down

### What you expected to happen

I dont know what the reason is, Perhaps we have a lot of scheduled tasks.

### How to reproduce

standalone env and a lot of scheduled tasks,you will see the workerServer process is increase

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
What kind of task, this might be sub process created by the worker.

**Comment by peak-xu** [comment]
> What kind of task, this might be sub process created by the worker.

Scheduled Task ,Why does the number of processes continue to increase? My understanding is that once a process finishes running, it should disappear.

**Comment by ruanwenjun** [comment]
> Scheduled Task ,Why does the number of processes continue to increase? My understanding is that once a process finishes running, it should disappear.

pf -eLf will print the thread in the process, since we use a fixed thread pool, so the thread num will increase until exceed `exec-threads` then it will not increase, and it will not release.

**Comment by peak-xu** [comment]
> > Scheduled Task ,Why does the number of processes continue to increase? My understanding is that once a process finishes running, it should disappear.
> 
> pf -eLf will print the thread in the process, since we use a fixed thread pool, so the thread num will increase until exceed `exec-threads` then it will not increase, and it will not release.

<img width="887" alt="image" src="https://github.com/apache/dolphinscheduler/assets/49389493/55514dc0-e630-43cd-b57f-b74d1912a547">

I found that a task occupied more than 7,000 threads.

**Comment by wangxj3** [comment]
check the path of /proc/${worker-server pid}/task/ ,you can get the detail about the sub threads of the worker-server.Check the task to see if there is a scheduled thread pool or other logic for creating threads. The thread pool is still creating threads regularly after the daemon thread ends.Hope it helps

**Comment by peak-xu** [comment]
> check the path of /proc/${worker-server pid}/task/ ,you can get the detail about the sub threads of the worker-server.Check the task to see if there is a scheduled thread pool or other logic for creating threads. The thread pool is still creating threads regularly after the daemon thread ends.Hope it helps

I don’t know if I used ps -eLf | grep workerServer to count the number of threads correctly. It does not match /proc/pid/task. By observing the results of the ps -eLf command, I guess that some task threads are not destroyed after execution. Once the number of threads reaches a certain If the quantity is too high, the service will be down. I don’t know how to analyze it next.

**Comment by ruanwenjun** [comment]
> > check the path of /proc/${worker-server pid}/task/ ,you can get the detail about the sub threads of the worker-server.Check the task to see if there is a scheduled thread pool or other logic for creating threads. The thread pool is still creating threads regularly after the daemon thread ends.Hope it helps
> 
> I don’t know if I used ps -eLf | grep workerServer to count the number of threads correctly. It does not match /proc/pid/task. By observing the results of the ps -eLf command, I guess that some task threads are not destroyed after execution. Once the number of threads reaches a certain If the quantity is too high, the service will be down. I don’t know how to analyze it next.

Can you print the thread name?

**Comment by peak-xu** [comment]
<img width="692" alt="image" src="https://github.com/apache/dolphinscheduler/assets/49389493/577b40d0-b19d-407e-be53-e730bb9b6fe9">

**Comment by peak-xu** [comment]
<img width="745" alt="image" src="https://github.com/apache/dolphinscheduler/assets/49389493/c093739b-f3a1-4845-abf7-5e54d4e8a7d0">
Is the thread status sleeping normal?

**Comment by czxin788** [comment]
This is my dolphinscheduler workserver thread nums monitor:
```
ps -eLf | grep 'WorkerServer' | wc -l
```
and the result is :
![image](https://github.com/apache/dolphinscheduler/assets/13861904/f007c84f-31f2-4640-b636-092d897d3e1c)

When the value reaches 20000+, the all task in dolphinscheduler will hung,all task  alway in running state and not end up.

Are there a solution methods?
