### ISSUE TITLE
[Improvement][ui] Unable to find current version identifier

### ISSUE THREAD

**Issue by StarGods** [apache/dolphinscheduler#15815]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The version identifier of dolphinscheduler cannot be found on the UI. Please add the current version identifier on the UI.

在WEB 的UI界面上 无法找到当前运行的 dolphinscheduler  版本信息，无法确定当前运行的版本。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangxj3** [comment]
I will fix it
