### ISSUE TITLE
[Bug] Parameter replace with ? will cause NPE

### ISSUE THREAD

**Issue by longlongagos** [apache/dolphinscheduler#15828]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I want to pass parameters and "?" appears inside the SQL statement, the scheduler will report a null pointer error to me.

### What you expected to happen

I think that when passing parameters, during the escaping process, the parameters will be replaced with "?" first. At this time, it conflicts with the "?" inside the SQL statement.

### How to reproduce

There is no such problem in older versions

### Anything else

my demo like this
select concat('(?i)', (select name from namelist where tag = '${tag}'))

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xxzuo** [comment]
@ruanwenjun please assign to me
