### ISSUE TITLE
[Bug] [process instances] can not stop spark task

### ISSUE THREAD

**Issue by eyesmoons** [apache/dolphinscheduler#15822]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

while using the spark plugin，when click the stop button in the process instances list，the yarn application of spark task is still running.

### What you expected to happen

when stop the spark process instance，I hope the yarn application of spark task is also be killed.

### How to reproduce

<img width="1479" alt="image" src="https://github.com/apache/dolphinscheduler/assets/14860877/f0f47ac3-3ba3-4b55-8e42-b920ab568bd1">

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Does the task be killed at ds? Seems the workflow status is ready kill

**Comment by eyesmoons** [comment]
yes, the task has been killed at ds.
