### ISSUE TITLE
[Feature][API] REST API

### ISSUE THREAD

**Issue by pradip-allwyn** [apache/dolphinscheduler#15831]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Is there a roadmap for supporting REST API?

### Use case

I would like to use an external workflow automator in conjunction with Dolphin to initiate work on a specific usecase and then return the result to the workflow for further processing.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangxj3** [comment]
Do you mean integrating workflow related pages into other systems?

**Comment by Gallardot** [comment]
May [PyDolphinScheduler](https://dolphinscheduler.apache.org/python/main/) will help you.
