### ISSUE TITLE
[Bug] [Module Name] Pagination issue. only show 1 page。 分页器只显示1页。

### ISSUE THREAD

**Issue by ScalaFirst** [apache/dolphinscheduler#15839]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![1713080318242](https://github.com/apache/dolphinscheduler/assets/97863434/3430a575-8fe7-48d6-b45c-ba1a0eae9b3a)
my task instances have more then 10 , but only show 10.
my server is deploy by standalone.
version 3.2.1

我的任务实例数量远超10个，但是只显示10个。没有下一页。
我的部署方式是 standalone。
我的版本是 3.2.1

### What you expected to happen

rest api return total : 89 , and I can change pageSize to show more then 10. but pageNum only have 1.

api显示总共有89条，我也可以通过调整分页大小看到超过10条。但是不管怎么调，都只有1页。

![1713080490646](https://github.com/apache/dolphinscheduler/assets/97863434/73c40274-9083-4bae-89ac-9d4f841c1b15)

### How to reproduce

deploy by standalone.
version 3.2.1

3.2.1版本单机部署应该都有这个问题。

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Duplicate with https://github.com/apache/dolphinscheduler/issues/15606.
