### ISSUE TITLE
[Bug] [master] When I complement data by parallel execution, after a failed process instance, subsequent process instances are not generated

### ISSUE THREAD

**Issue by einsteinict** [apache/dolphinscheduler#15835]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I complement data by parallel execution, after a failed process instance, subsequent process instances are not generated

### What you expected to happen

All subsequent process instances should be generated and executed.

### How to reproduce

When complement data by parallel execution，kill some tasks，and the subsequent tasks follow the failed task will not be generated.

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by einsteinict** [comment]
To be accurate, the dolphinscheduler version is 3.1.8

**Comment by ruanwenjun** [comment]
This is not a bug, right now, when the workflow instance is failed when you backfill, the post workflow instance will not be triggered.

If you are interested in this, you can create a DSIP issue to improve this, it is reasonable for me we should create all backfill workflow instances in parallel mode.

**Comment by lucky-fellow** [comment]
我也遇到了同样的问题，当补数大量数据时，其中有一个分区失败了。后续的分区也不会执行了。能否跳过失败的分区天数，继续执行其他天数呢？

**Comment by lucky-fellow** [comment]
> 这不是一个bug，现在，当你回填时工作流实例失败时，后续工作流实例将不会被触发。
> 
> 如果您对此感兴趣，可以创建 DSIP 问题来改进这一点，对我来说，我们应该以玩具模式创建所有回填工作流实例是合理的。

我也遇到了同样的问题，当补大量数据时，其中有一个分区失败了。后续的分区也无法执行了。能否删除失败的分区天数，继续执行其他天数呢？
