### ISSUE TITLE
[Bug] [Worker] duplicate execution shell script

### ISSUE THREAD

**Issue by RaymondFishWang** [apache/dolphinscheduler#15856]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

version 3.2.0 ,when I execute shell script, sometimes shell will run twice, from ds log, we can find the evidence.
![image](https://github.com/apache/dolphinscheduler/assets/152674254/d685fe9f-ddf5-4fca-aa69-13e5877147a9)

### What you expected to happen

execute one time

### How to reproduce

sometimes

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
How to reproduce this, please provide your cluster deployment info.

**Comment by RaymondFishWang** [comment]
this result happen accidentally ,not it must happen，so i don'know how to repproduce, 
I deploy it with k8s helm, 2 master， 3 worker, 1 api.     version is 3.2.0
i just create shell script to run datax program.

**Comment by RaymondFishWang** [comment]
It seems ds run the script twice in one task.

**Comment by RaymondFishWang** [comment]
> How to reproduce this, please provide your cluster deployment info.

this result happen accidentally ,not it must happen，so i don'know how to reproduce,
I deploy it with k8s helm, 2 master， 3 worker, 1 api. version is 3.2.0
i just create shell script to run datax program.
It seems ds run the script twice in one task.

**Comment by RaymondFishWang** [comment]
![image](https://github.com/apache/dolphinscheduler/assets/152674254/c6685ae1-abcf-4705-90b4-570a11bfe9d7)
I find these three tasks have this problem , I suspect dependent task logic have bugs, ans these three tasks were invoked  at the same time nearly.
