### ISSUE TITLE
[Improvement][Task] supporting parameter replacement in SeaTunnel task type

### ISSUE THREAD

**Issue by davidzollo** [apache/dolphinscheduler#15859]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

As you can see, there is a simple SeaTunnel task config, like this
```
env {
  parallelism =4
  job.mode = "BATCH"
}
source {
  Jdbc {
    url ="jdbc:mysql://localhost/test?serverTimezone=GMT%2b8"
    driver ="com.mysql.cj.jdbc.Driver"connection check timeout sec = 100
    user ="root"
    password ="123456"
    table path = "testdb.table1"
    guery ="select * from ${tableName}'
    split.size = 10000
  }
}
sink {
Console {}
}
```

Some users want to replace the param `${tableName}` to the actual value when task runs 
<img width="588" alt="image" src="https://github.com/apache/dolphinscheduler/assets/15833811/a522bfc8-9bfd-4871-8988-95cde0f68253">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
It's better to support parameters passed from upstream tasks, such as shell task.

you can refer the doc, https://dolphinscheduler.apache.org/en-us/docs/3.2.1/guide/parameter/context

**Comment by ruanwenjun** [comment]
This should already supported.
