### ISSUE TITLE
[Improvement][Deployment] deployment tutorial has security risks, and I have been implanted into the background program

### ISSUE THREAD

**Issue by ScalaFirst** [apache/dolphinscheduler#15869]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://github.com/apache/dolphinscheduler/assets/97863434/ada9c408-338f-4cb4-a259-a62eadd2d2ba)
我按这个教程无脑部署了调度程序，结果在晚上被人用 dolphinscheduler 用户远程登录服务器，植入了挖矿(?)程序。
建议将教程的固定密码设置为随机生成密码，并打印到控制台即可。
(该sudo 配置可以切换到root用户，其实风险很大)

### Documentation Links

https://dolphinscheduler.apache.org/zh-cn/docs/3.2.1/guide/installation/pseudo-cluster

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
Would you like to implement this feature? it's not difficult

**Comment by xinxingi** [comment]
Good advice, would be even better if added. I will submit the code later to improve it

**Comment by SbloodyS** [comment]
I don't think this is a problem. Making services public on the public network requires careful consideration of various security risks.

**Comment by ruanwenjun** [comment]
> I don't think this is a problem. Making services public on the public network requires careful consideration of various security risks.

+1

**Comment by ScalaFirst** [comment]
> I don't think this is a problem. Making services public on the public network requires careful consideration of various security risks.

+1 , 你说的对 , 但是我复制的时候没有仔细想。

**Comment by ScalaFirst** [comment]
> I don't think this is a problem. Making services public on the public network requires careful consideration of various security risks.

you are right , but I miss
