### ISSUE TITLE
[DSIP-30][UI] Add a page "about Dolphinscheduler"

### ISSUE THREAD

**Issue by pinkfloyds** [apache/dolphinscheduler#15875]
### Search before asking

- [X] I had searched in the [DSIP](https://github.com/apache/dolphinscheduler/issues/14102) and found no similar DSIP.

### Motivation
Complete display of project information.

### Design Detail
Add a "About Dolphinscheduler" item to the username menu on the homepage, and displays the current version number,homepage,GitHub page,open source license,dolphinscheduler logo and other information on the opened page,Require neat arrangement and concise pages.
![微信图片_20240420195557](https://github.com/apache/dolphinscheduler/assets/24634414/8cc427c1-6d3a-4faf-9c87-9a08a6a6aa82)

### Compatibility, Deprecation, and Migration Plan
No impact.

### Test Plan
Check if it can be displayed normally on the website.

**Comment by ruanwenjun** [comment]
Since this is a new feature, please change this to `DSIP`, you need to follow https://github.com/apache/dolphinscheduler/issues/14102

**Comment by pinkfloyds** [comment]
> Since this is a new feature, please change this to `DSIP`, you need to follow #14102

I have made the modifications according to the DSIP format. What do I need to do next?

**Comment by ruanwenjun** [comment]
> > Since this is a new feature, please change this to `DSIP`, you need to follow #14102
> 
> I have made the modifications according to the DSIP format. What do I need to do next?

Great, I will add this to DSIP list, this feature LGTM. BTW, why we didn't display this under the bottom.
