### ISSUE TITLE
[Bug] [Pytorch] There is no security check for GitProjectManager.getGitUrl, which could cause command injection

### ISSUE THREAD

**Issue by Liyw979** [apache/dolphinscheduler#15873]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

https://github.com/apache/dolphinscheduler/blob/8fc204940f7be5cf356f63dd223bc599f857fe69/dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/main/java/org/apache/dolphinscheduler/plugin/task/pytorch/GitProjectManager.java#L47-L50
There is no input validation for `getGitUrl` and users could put shell commands here.

### What you expected to happen

ensure the  `getGitUrl` is a valid url

### How to reproduce

![image](https://github.com/apache/dolphinscheduler/assets/16919236/aa4f8a6f-0149-434f-9e23-bf6a61abb469)
![image](https://github.com/apache/dolphinscheduler/assets/16919236/bee1668a-154e-4241-b49d-6a5f01034f7f)

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cntigers** [comment]
I will  solve this problem
