### ISSUE TITLE
[ERROR] Some problems were encountered while processing the POMs:

### ISSUE THREAD

**Issue by nizpxox** [apache/dolphinscheduler#15893]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

"C:\Program Files\Java\jdk1.8.0_91\bin\java.exe" -Dmaven.multiModuleProjectDirectory=D:\product\dolphinscheduler-3.2.0-release -Djansi.passthrough=true -Dmaven.home=D:\development\apache-maven-3.9.3 -Dclassworlds.conf=D:\development\apache-maven-3.9.3\bin\m2.conf "-Dmaven.ext.class.path=D:\IDEA2023\idea\IntelliJ IDEA 2023.1.2\plugins\maven\lib\maven-event-listener.jar" "-javaagent:D:\IDEA2023\idea\IntelliJ IDEA 2023.1.2\lib\idea_rt.jar=57539:D:\IDEA2023\idea\IntelliJ IDEA 2023.1.2\bin" -Dfile.encoding=UTF-8 -classpath D:\development\apache-maven-3.9.3\boot\plexus-classworlds-2.7.0.jar;D:\development\apache-maven-3.9.3\boot\plexus-classworlds.license org.codehaus.classworlds.Launcher -Didea.version=2023.1.2 -s D:\development\apache-maven-3.9.3\conf\settings.xml -Dmaven.repo.local=D:\m2\repository -DskipTests=true clean
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: The following artifacts could not be resolved: org.apache.dolphinscheduler:dolphinscheduler-bom:pom:3.2.1-SNAPSHOT (absent): org.apache.dolphinscheduler:dolphinscheduler-bom:pom:3.2.1-SNAPSHOT was not found in https://repository.apache.org/snapshots during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of apache.snapshots has elapsed or updates are forced @ line 30, column 25
[ERROR] 'dependencies.dependency.version' for org.codehaus.janino:janino:jar is missing. @ line 84, column 21
[ERROR] 'dependencies.dependency.version' for com.amazonaws:aws-java-sdk-s3:jar is missing. @ line 88, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-web:jar is missing. @ line 93, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-jetty:jar is missing. @ line 109, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-aop:jar is missing. @ line 124, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework:spring-context:jar is missing. @ line 135, column 21
[ERROR] 'dependencies.dependency.version' for org.hibernate.validator:hibernate-validator:jar is missing. @ line 140, column 21
[ERROR] 'dependencies.dependency.version' for io.fabric8:kubernetes-client:jar is missing. @ line 145, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @ line 151, column 21
[ERROR] 'dependencies.dependency.version' for org.apache.curator:curator-test:jar is missing. @ line 157, column 21
[ERROR] 'dependencies.dependency.version' for net.sf.py4j:py4j:jar is missing. @ line 170, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.ldap:spring-ldap-core:jar is missing. @ line 175, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-kubernetes-client-config:jar is missing. @ line 180, column 21
[ERROR] 'dependencies.dependency.version' for org.apache.hbase.thirdparty:hbase-noop-htrace:jar is missing. @ line 185, column 21
[ERROR] 'dependencies.dependency.version' for com.h2database:h2:jar is missing. @ line 190, column 21
[ERROR] 'dependencies.dependency.version' for org.casbin:casdoor-spring-boot-starter:jar is missing. @ line 196, column 21
[ERROR] 'dependencies.dependency.version' for org.springdoc:springdoc-openapi-ui:jar is missing. @ line 201, column 21
[ERROR] 'dependencies.dependency.version' for com.azure.resourcemanager:azure-resourcemanager:jar is missing. @ line 205, column 21
[ERROR] 'dependencies.dependency.version' for com.azure.resourcemanager:azure-resourcemanager-datafactory:jar is missing. @ line 209, column 21
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.apache.dolphinscheduler:dolphinscheduler-api:3.2.1-SNAPSHOT (D:\product\dolphinscheduler-3.2.0-release\dolphinscheduler-api\pom.xml) has 20 errors
[ERROR]     Non-resolvable import POM: The following artifacts could not be resolved: org.apache.dolphinscheduler:dolphinscheduler-bom:pom:3.2.1-SNAPSHOT (absent): org.apache.dolphinscheduler:dolphinscheduler-bom:pom:3.2.1-SNAPSHOT was not found in https://repository.apache.org/snapshots during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of apache.snapshots has elapsed or updates are forced @ line 30, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.codehaus.janino:janino:jar is missing. @ line 84, column 21
[ERROR]     'dependencies.dependency.version' for com.amazonaws:aws-java-sdk-s3:jar is missing. @ line 88, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-web:jar is missing. @ line 93, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-jetty:jar is missing. @ line 109, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-aop:jar is missing. @ line 124, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework:spring-context:jar is missing. @ line 135, column 21
[ERROR]     'dependencies.dependency.version' for org.hibernate.validator:hibernate-validator:jar is missing. @ line 140, column 21
[ERROR]     'dependencies.dependency.version' for io.fabric8:kubernetes-client:jar is missing. @ line 145, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @ line 151, column 21
[ERROR]     'dependencies.dependency.version' for org.apache.curator:curator-test:jar is missing. @ line 157, column 21
[ERROR]     'dependencies.dependency.version' for net.sf.py4j:py4j:jar is missing. @ line 170, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.ldap:spring-ldap-core:jar is missing. @ line 175, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-kubernetes-client-config:jar is missing. @ line 180, column 21
[ERROR]     'dependencies.dependency.version' for org.apache.hbase.thirdparty:hbase-noop-htrace:jar is missing. @ line 185, column 21
[ERROR]     'dependencies.dependency.version' for com.h2database:h2:jar is missing. @ line 190, column 21
[ERROR]     'dependencies.dependency.version' for org.casbin:casdoor-spring-boot-starter:jar is missing. @ line 196, column 21
[ERROR]     'dependencies.dependency.version' for org.springdoc:springdoc-openapi-ui:jar is missing. @ line 201, column 21
[ERROR]     'dependencies.dependency.version' for com.azure.resourcemanager:azure-resourcemanager:jar is missing. @ line 205, column 21
[ERROR]     'dependencies.dependency.version' for com.azure.resourcemanager:azure-resourcemanager-datafactory:jar is missing. @ line 209, column 21
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

Process finished with exit code 1

### What you expected to happen

this pom is red  <artifactId>maven-assembly-plugin</artifactId> 

### How to reproduce

I down this and I want update  this:processDefinition.setName(getNewName(processDefinition.getName(), COPY_SUFFIX));
When I update finish ,I clean and I want to package the file to .jar. I clean is failed ,and package is failed

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nizpxox** [comment]
How can I do to .jar success

**Comment by ruanwenjun** [comment]
Please describe your problem clear.

**Comment by nizpxox** [comment]
When I made changes to the code and tried to convert this file into a. jar file through the package in Maven, I first cleared it without any issues, and then I clicked on the package and reported an error

**Comment by nizpxox** [comment]
![image](https://github.com/apache/dolphinscheduler/assets/141626156/6708733e-c665-40f9-b90f-6470ab333fe5)


> 请清楚描述您的问题。

When I made changes to the code and tried to convert this file into a. jar file through the package in Maven, I first cleared it without any issues, and then I clicked on the package and reported an error

**Comment by ruanwenjun** [comment]
> ![image](https://private-user-images.githubusercontent.com/141626156/325063566-6708733e-c665-40f9-b90f-6470ab333fe5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTc0MzcsIm5iZiI6MTcxNDA1NzEzNywicGF0aCI6Ii8xNDE2MjYxNTYvMzI1MDYzNTY2LTY3MDg3MzNlLWM2NjUtNDBmOS1iOTBmLTY0NzBhYjMzM2ZlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxNDU4NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzZhNTczMTU2MzYyNjQ2NzM0YWQzMDI5MGNjMDhhNDQ2NGZiZWVmYjIzYzQ5YTAxYWQ5YTZkZWU1YzkzMGZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jxbNUk9u8K8BMG7ZjqTjUIcIk8mJI0bTB1sXAecHTnA)
> 
> > 请清楚描述您的问题。
> 
> When I made changes to the code and tried to convert this file into a. jar file through the package in Maven, I first cleared it without any issues, and then I clicked on the package and reported an error

Can you able to compile the source code successfully?
