### ISSUE TITLE
[Bug] [UI] [Helm] could not access UI with deploying helm

### ISSUE THREAD

**Issue by pegasas** [apache/dolphinscheduler#15904]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I build my custom image using 
https://github.com/apache/dolphinscheduler/blob/dev/.github/workflows/e2e-k8s.yml#L55-L69
and modifies following image settings
https://github.com/apache/dolphinscheduler/blob/dev/deploy/kubernetes/dolphinscheduler/values.yaml#L32-L50

it seems work well while getting status.
![image](https://github.com/apache/dolphinscheduler/assets/13224827/75cecbef-7f9d-47a4-96d3-d55de954d20a)

when i using
```
kubectl port-forward --address 0.0.0.0 svc/dolphinscheduler-api 12345:12345
```

it shows nothing on browser

dev tools shows OK and pod logs also OK.

![image](https://github.com/apache/dolphinscheduler/assets/13224827/788d6edd-b9bf-4bf8-897e-64320789c82d)

![image](https://github.com/apache/dolphinscheduler/assets/13224827/c2348fa3-f19c-4e74-8b0e-36020219dc61)

when switching back to 3.2.1 official image, it works well.
so i consider it as bug

it shows error on console, see
![image](https://github.com/apache/dolphinscheduler/assets/13224827/7b2811ff-ab66-45a6-89d0-b134290e90d9)

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

not sure if it related to this bug.

### What you expected to happen

see above

### How to reproduce

see above

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pegasas** [comment]
After sync with Gallardot , the issue is done.

**Comment by YJLau91** [comment]
Hi,

I am experiencing the same issue. When I run the UI separately using pnpm run dev, I am able to view the page without any problems. However, when I run it using the Docker image, I encounter the same error in the console. Could you please advise on how to resolve this? Thank you!

**Comment by lbzss** [comment]
Any one can help? I also met the same issue. Can't visit ui through dolphinscheduler-api:12345

**Comment by lbzss** [comment]
> After sync with Gallardot , the issue is done.

Hi, can you share how to resolve this problem?
