### ISSUE TITLE
[Bug] [JAVA TASK] Unable to access jarfile

### ISSUE THREAD

**Issue by 1032851561** [apache/dolphinscheduler#15902]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[INFO] 2024-04-24 15:40:09.119 +0800 - #!/bin/bash
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
export JAVA_HOME=/opt/java/openjdk
${JAVA_HOME}/bin/java -classpath .:/tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74:/tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74//tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74/Test-1.0-SNAPSHOT.jar -jar /tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74//tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74/Test-1.0-SNAPSHOT.jar arg1 arg2 
[INFO] 2024-04-24 15:40:09.119 +0800 - ****************************** Script Content *****************************************************************
[INFO] 2024-04-24 15:40:09.119 +0800 - Executing shell command : sudo -u root -i /tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74/58_74.sh
[INFO] 2024-04-24 15:40:09.126 +0800 - process start, process id is: 369
[INFO] 2024-04-24 15:40:10.126 +0800 -  -> 
	Error: Unable to access jarfile /tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74//tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74/Test-1.0-SNAPSHOT.jar
[INFO] 2024-04-24 15:40:10.127 +0800 - process has exited. execute path:/tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74, processId:369 ,exitStatusCode:1 ,processWaitForStatus:true ,processExitValue:1

### What you expected to happen

the jar path contains twice `execute path` , it should be once.
- wrong:
/tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74//tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74/Test-1.0-SNAPSHOT.jar -jar 
- expect:
/tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74/Test-1.0-SNAPSHOT.jar -jar 

### How to reproduce

1. upload jar to resource center(hfds)
2. create java task (jar type) and select the jar 
3. run task and log error

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Should be fixed by #15906

**Comment by 1032851561** [comment]
> Should be fixed by #15906

whitch version will fix.

**Comment by ruanwenjun** [comment]
> > Should be fixed by #15906
> 
> whitch version will fix.

3.2.2
