### ISSUE TITLE
[Bug] [dolphinscheduler-api] pagination queries are not supported

### ISSUE THREAD

**Issue by xiongbl526** [apache/dolphinscheduler#15916]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In version 3.2.1, almost all pagination queries do not support pagination. A maximum of 10 records can be displayed per page. However, the search box is capable of locating the target information. It was discovered through F12 inspection that the data is indeed being returned. The issue lies with the frontend parsing.

### What you expected to happen

The pagination query is able to display multiple page numbers correctly.

### How to reproduce

To upgrade from version 3.1.8 to 3.2.1 and deploy using Kubernetes (k8s) with Helm

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Klinenator** [comment]
I would like to confirm this is also happening on 3.2.1 on the standalone build

**Comment by SbloodyS** [comment]
This will be fixed in `3.2.2-release`.
