### ISSUE TITLE
[Improvement][datasource] improvement datasource get name

### ISSUE THREAD

**Issue by sdhzwc** [apache/dolphinscheduler#15919]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

found through the code, the database to get the name of the time part is written dead, but I see spi's DbType enumeration in the unified maintenance, so in order to code style consistency, as well as the later maintenance of convenience, it is a unified optimization of values

### What you expected to happen

Optimize it.

### How to reproduce

In the code logic

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Since this is not a bug, so I remove the bug label.
