### ISSUE TITLE
[Bug] [Task] HiveCli SQL execution failed, but the task node shows success. 

### ISSUE THREAD

**Issue by adonis-lau** [apache/dolphinscheduler#15918]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In the shell node, multiple SQL files are called using hive -f, and each file contains multiple SQL statements. When one of the SQL statements fails, the subsequent SQL statements continue to execute, and the status of the shell node is marked as successful.
![任务日志截图](https://github.com/apache/dolphinscheduler/assets/14901776/4eef6311-fdf6-40fe-bd16-665d3853630b)
![任务状态截图](https://github.com/apache/dolphinscheduler/assets/14901776/085cb296-fd4b-40d9-84be-bdf91915f766)

### What you expected to happen

In the shell node, after invoking SQL via hive -f, if there are failures in the SQL execution, the subsequent SQLs should not continue to execute, and the status of the shell node should be marked as failed.

### How to reproduce

If there are 5 SQL commands in a Hive SQL file and the second command fails, the third, fourth, and fifth commands will still be executed. If these commands are executed successfully, the node will be marked as having executed successfully.

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Yes, this should be a bug happens when the script contains multiple sqls, we might need to split the sql, and check each sql status after finished.

**Comment by wangxj3** [comment]
> Yes, this should be a bug happens when the script contains multiple sqls, we might need to split the sql, and check each sql status after finished.

The HiveCli SQL run base on shell, When build the shell ,use set -e ,could fix this ?

**Comment by ruanwenjun** [comment]
> > Yes, this should be a bug happens when the script contains multiple sqls, we might need to split the sql, and check each sql status after finished.
> 
> The HiveCli SQL run base on shell, When build the shell ,use set -e ,could fix this ?

I have not test this, but it might not fix this due to the multiple SQLS are been executed by one command, rather than multiple commands.

**Comment by wangxj3** [comment]
> > > Yes, this should be a bug happens when the script contains multiple sqls, we might need to split the sql, and check each sql status after finished.
> > 
> > 
> > The HiveCli SQL run base on shell, When build the shell ,use set -e ,could fix this ?
> 
> I have not test this, but it might not fix this due to the multiple SQLS are been executed by one command, rather than multiple commands.

Oh,This doesn't look like a very good solution for one command .I will check it .

**Comment by chengcxy** [comment]
> Yes, this should be a bug happens when the script contains multiple sqls, we might need to split the sql, and check each sql status after finished.


use multi shell command also need check each command status,we produced bugs in prod env
