### ISSUE TITLE
[DSIP-][api-server] dispath the resource to worker-server

### ISSUE THREAD

**Issue by wangxj3** [apache/dolphinscheduler#15938]
### Search before asking

- [X] I had searched in the [DSIP](https://github.com/apache/dolphinscheduler/issues/14102) and found no similar DSIP.

### Motivation

The file upload by the page of resource ,the file will save by the api-server on server,if there is no worker-server in this server ,and the DS group has no share file system ,it's hard for user to use this file .
通过资源页面上传文件，该文件将通过api服务保存到api所在的服务器，如果该服务器中没有worker-server，并且DS组没有共享文件系统，用户将很难使用该文件。
对于简单实用的用户，应该间可能减少部署成本。
对于核心使用场景，要保证系统的稳定性（包括依赖插件稳定性原因导致的DS集群稳定性）。

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
I am -1 to this DSIP.

In standalone mode, users can directly use the local file system. In cluster mode, users can use distribution file system or some shared file system like NFS, the distribution file system is very commonly, this is not an expensive technology.

Back to the implementation, do you understand the complexity of implementing a file system? The only thing I can think of as an implemenration is we broadcast the file to all workers, but this means the cluster will be hard to scaled.

In additional, DS is not must rely on a distribution file system, this is different with spark/flink which is stronge rely on a distribution file system to store the checkpoint data, these systems still don't have plan to implement a file system.

**Comment by caishunfeng** [comment]
> In cluster mode, users can use distribution file system or some shared file system like NFS, the distribution file system is very commonly, this is not an expensive technology.

+1, DS should pay more attention to its own schedule business, and do not need to add more logic of the basic file system. 
This will introduce more unnecessary complexity and maintenance costs.
