### ISSUE TITLE
Add data lineage plug-in

### ISSUE THREAD

**Issue by smileyboy2019** [apache/dolphinscheduler#15948]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

将sql，脚本，spark，flink 等这些，添加血缘插件，支持血缘输出
https://github.com/melin/sqlflow

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by smileyboy2019** [comment]
同时将血缘数据推送到apache atals

**Comment by SbloodyS** [comment]
Project `melin/sqlflow` is not under the apache license. This feature would not be accepted.
