### ISSUE TITLE
[Bug] [dolphinscheduler-ui] This display is incomplete

### ISSUE THREAD

**Issue by lanss315425** [apache/dolphinscheduler#15951]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

导航栏显示不完整
<img width="1505" alt="image" src="https://github.com/apache/dolphinscheduler/assets/19217018/89281b62-ec1a-46a6-a073-4ea90005be86">

### What you expected to happen

建议把主题、语言、时间放到页面设置中

### How to reproduce

在MacBook Pro中显示不完整

### Anything else

另外期望系统标题和logo可以自定义

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
+1, are you interested to fix this?

**Comment by caizhiqiangzeyuan** [comment]
I will fix it @ruanwenjun
