### ISSUE TITLE
flink task failed ,but dolphinscheduler task status display is running

### ISSUE THREAD

**Issue by Aitongong** [apache/dolphinscheduler#15952]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

`[INFO] 2024-05-07 09:34:46.213 +0800 org.apache.dolphinscheduler.server.master.processor.TaskExecuteResponseProcessor:[68] - [WorkflowInstance-254778][TaskInstance-712617] - Received task execute result, event: TaskEvent(taskInstanceId=712617, workerAddress=*******:1234, state=TaskExecutionStatus{code=7, desc='success'}, startTime=Thu Mar 28 00:36:49 CST 2024, endTime=Wed Apr 17 19:04:55 CST 2024, executePath=/apply/software/dolphinscheduler317/exec/process/hdfs/7007919231168/7008207783360_16/254778/712617, logPath=/apply/software/dolphinscheduler317/worker-server/logs/20240328/7008207783360_16-254778-712617.log, processId=25980, appIds=, event=RESULT, varPool=[], channel=[id: 0x02bf36f8, L:/*******:5678 - R:/*******:36730], processInstanceId=254778)
[WARN] 2024-05-07 09:34:46.213 +0800 org.apache.dolphinscheduler.server.master.processor.queue.TaskExecuteThreadPool:[84] - [WorkflowInstance-0][TaskInstance-0] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=712617, workerAddress=*******:1234, state=TaskExecutionStatus{code=7, desc='success'}, startTime=Thu Mar 28 00:36:49 CST 2024, endTime=Wed Apr 17 19:04:55 CST 2024, executePath=/apply/software/dolphinscheduler317/exec/process/hdfs/7007919231168/7008207783360_16/254778/712617, logPath=/apply/software/dolphinscheduler317/worker-server/logs/20240328/7008207783360_16-254778-712617.log, processId=25980, appIds=, event=RESULT, varPool=[], channel=[id: 0x02bf36f8, L:/*******:5678 - R:/*******:36730], processInstanceId=254778)`

### What you expected to happen

flink任务失败后，dolphinscheduler界面任务状态还是running

### How to reproduce

集群架构存在两个master
1.先启动一个flink实时任务
2.杀掉一个master
3.通过yarn杀掉flink实时任务

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rickchengx** [comment]
So is the status inconsistent due to stopping a master?

**Comment by Pluto201** [comment]
I encountered the same problem in dolphinscheduler 3.2.1, ds can't track the status of flink. How can I solve this problem?
