### ISSUE TITLE
[Improvement][Doc] Resource configuration exist typo

### ISSUE THREAD

**Issue by chennest** [apache/dolphinscheduler#15957]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In the official Chinese document, there is an error in the description of the last sentence in the feature introduction, resource center, and configuration details. The original text was "非 NameNode HA 跳过次步骤" ,It should be changed to "非 NameNode HA 跳过此步骤"

### Documentation Links

https://dolphinscheduler.apache.org/zh-cn/docs/3.1.9/guide/resource/configuration

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chennest** [comment]
At the same time, both 3.1.0 to 3.2.1 and 3.0.0 to 3.0.4 have this issue, while 3.0.5 and 3.0.6 do not have this "配置详情，文件管理，UDF管理，任务组管理" document

**Comment by ruanwenjun** [comment]
Are you willing to fix this?

**Comment by chennest** [comment]
I can solve it
