### ISSUE TITLE
How to implement insertOrUpdate

### ISSUE THREAD

**Issue by jnfJNF** [apache/dolphinscheduler#15973]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

当我想同步两个数据源的数据时，如何实现根据ID进行新增或插入，即insertOrUpdate。请问有相应的组件吗？如何实现？

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Is this related to ds? There are two ways
1. Directly use DB upsert SQL, different databases provide different grammar, some may doesn's support.
2. Query the data in the database, if it does not exist then insert, others update. You may need to use lastUpdateTime to do  optimistic concurrency control.
