### ISSUE TITLE
[Bug] Insufficient permissions after version 3.1.8 upgrade to 3.2.0

### ISSUE THREAD

**Issue by Johp-t** [apache/dolphinscheduler#15976]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After upgrading from version 3.1.8 to 3.2.0, an error is encountered in the execution of the Datax workflow:

/tmp/dolphinscheduler/exec/process/dolphinscheduler/12899597581952/13432672120965_2/2121/14362/2121_14362_job.json
[INFO] 2024-05-10 14:24:08.541 +0800 - Executing shell command : sudo -u dolphinscheduler -i /tmp/dolphinscheduler/exec/process/dolphinscheduler/12899597581952/13432672120965_2/2121/14362/2121_14362.sh
[INFO] 2024-05-10 14:24:08.543 +0800 - process start, process id is: 10664
[INFO] 2024-05-10 14:24:09.548 +0800 -  -> 
	
	DataX (DATAX-OPENSOURCE-3.0), From Alibaba !
	Copyright (C) 2010-2017, Alibaba Group. All Rights Reserved.
	
	
	Usage: datax.py [options] job-url-or-path
	
	Options:
	  -h, --help            show this help message and exit
	
	  Product Env Options:
	    Normal user use these options to set jvm parameters, job runtime mode
	    etc. Make sure these options can be used in Product Env.
	
	    -j <jvm parameters>, --jvm=<jvm parameters>
	                        Set jvm parameters if necessary.
	    --jobid=<job unique id>
	                        Set job unique id when running by Distribute/Local
	                        Mode.
	    -m <job runtime mode>, --mode=<job runtime mode>
	                        Set job runtime mode such as: standalone, local,
	                        distribute. Default mode is standalone.
	    -p <parameter used in job config>, --params=<parameter used in job config>
	                        Set job parameter, eg: the source tableName you want
	                        to set it by command, then you can use like this:
	                        -p"-DtableName=your-table-name", if you have mutiple
	                        parameters: -p"-DtableName=your-table-name
	                        -DcolumnName=your-column-name".Note: you should config
	                        in you job tableName with ${tableName}.
	    -r <parameter used in view job config[reader] template>, --reader=<parameter used in view job config[reader] template>
	                        View job config[reader] template, eg:
	                        mysqlreader,streamreader
	    -w <parameter used in view job config[writer] template>, --writer=<parameter used in view job config[writer] template>
	                        View job config[writer] template, eg:
	                        mysqlwriter,streamwriter
	
	  Develop/Debug Options:
	    Developer use these options to trace more details of DataX.
	
	    -d, --debug         Set to remote debug mode.
	    --loglevel=<log level>
	                        Set log level such as: debug, info, all etc.
	/tmp/dolphinscheduler/exec/process/dolphinscheduler/12899597581952/13432672120965_2/2121/14362/2121_14362.sh:行4: /tmp/dolphinscheduler/exec/process/dolphinscheduler/12899597581952/13432672120965_2/2121/14362/2121_14362_job.json: 权限不够

### What you expected to happen

I hope it works out.

### How to reproduce

version 3.1.8 upgrade to 3.2.0

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
This may be a file permission bug, please try 3.2.1.

**Comment by Johp-t** [comment]
@ruanwenjun 3.2.1 There's a problem turning the pages. Any ideas?

**Comment by ruanwenjun** [comment]
> @ruanwenjun 3.2.1 There's a problem turning the pages. Any ideas?

Or you can manually fix this by following the dev branch, this should already be fixed.
