### ISSUE TITLE
[Feature]Ds supports global resources?

### ISSUE THREAD

**Issue by windAworld** [apache/dolphinscheduler#1597]
Can ds support global resources instead of introducing resources into every process node?

**Comment by break60** [comment]
Did you mean the introduction of front-end resources?

**Comment by ly2325yj** [comment]
> 您的意思是引入前端资源吗？

在工作流中多个节点可能同时使用一个资源，如shell脚本，目前得在每个节点中单独引入该脚本资源才能使用，能否像在保存时设置全局参数一样设置资源

In the workflow, multiple nodes may use a resource at the same time, such as shell script, which currently has to be introduced into each node separately to be used. Can you set the resource as if you set global parameters when saving

**Comment by break60** [comment]
+1
Can consider increasing the setting of global resources
