### ISSUE TITLE
[PageInfo BUG] [Api-Service] task-instances interface page search totalPage is null

### ISSUE THREAD

**Issue by 1029135136** [apache/dolphinscheduler#15999]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

many page interface response totalPage is null
<img width="157" alt="image" src="https://github.com/apache/dolphinscheduler/assets/17538690/02f21eba-d78f-4656-b259-d15766809e34">

### What you expected to happen

i edit the code and set the filed like this 
<img width="887" alt="image" src="https://github.com/apache/dolphinscheduler/assets/17538690/7c458d78-d662-4e29-a389-2c635fc3d6b1">
than the ui is ok  
<img width="387" alt="image" src="https://github.com/apache/dolphinscheduler/assets/17538690/49d8c2d7-cd2c-42ae-9f16-e81b240b9154">
<img width="1014" alt="image" src="https://github.com/apache/dolphinscheduler/assets/17538690/88922e48-5a38-4676-8cbf-343601789f5c">

### How to reproduce

input more than 10 items data to the page, you can see this bug

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This issue will be fixed in #15619.
