### ISSUE TITLE
ds_process_definition show happen 

### ISSUE THREAD

**Issue by RedHatKai** [apache/dolphinscheduler#16017]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

ds_process_definition show happen ,i not can see all my process ds

### What you expected to happen

ds_process_definition show happen ,i not can see all my process ds

### How to reproduce

ds_process_definition show happen ,i not can see all my process ds

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Please provide more details, I am not clear what's your problem, do you means you cannot find your workflow instance?
