### ISSUE TITLE
[Bug] [sql task] The SQL task is stuck in 'Running' status after executing the insert-sql successfully

### ISSUE THREAD

**Issue by TurboWay** [apache/dolphinscheduler#16015]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

## 【doris version 2.0.6 】doris-sql success
![image](https://github.com/apache/dolphinscheduler/assets/23210408/aeda20bc-3ef5-459a-8119-614bbee36c2c)
## 【dolphinscheduler version 3.1.9 】dolphinscheduler task stuck
![image](https://github.com/apache/dolphinscheduler/assets/23210408/3f138c6d-c053-4923-a248-52dca0416439)

### What you expected to happen

The SQL task is completed successfully after executing

### How to reproduce

It happened accidentally, and I don't know how to reproduce it

### Version

3.1.9

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Seems the task status has not reported to master, could you please provide the worker task?
