### ISSUE TITLE
[Doc][UI] Command error in front-end development in some versions of the guidance document

### ISSUE THREAD

**Issue by wangxj3** [apache/dolphinscheduler#16026]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Command error in front-end development in some versions of the guidance document,I'm not sure which version started with errors, but in recent versions, [npm run build] should be changed to [pnpm run build: prod]
![Uploading 图片.png…]()

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
The photo is not uploaded, this change seems imported after 3.0.0, we need to update the doc.
