### ISSUE TITLE
[Improvement][Module Name]Workflow definition implements custom workflow grouping, making it convenient for data developers to find corresponding workflows and maintain workflows by domain during the process Improvement title

### ISSUE THREAD

**Issue by ikaijian** [apache/dolphinscheduler#16047]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please provide detailed design. This is more of a vision than a feature.
