### ISSUE TITLE
[Bug] Incorrect display of workflow instance running status

### ISSUE THREAD

**Issue by TurboWay** [apache/dolphinscheduler#16053]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When the last task of the workflow instance is disabled and the final normal task fails to execute, the running status of the workflow instance should display as failed, but it shows success instead

![image](https://github.com/apache/dolphinscheduler/assets/23210408/4338f2a7-81f9-4140-b5f7-4b012ba71d1c)

### What you expected to happen

The workflow status should be consistent with the actual state

### How to reproduce

Reproduce as above, you can see the issue

### Version

3.1.9

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You should check `failure strategy`.
