### ISSUE TITLE
[Improvement][Master] Password stored in system table without encryption

### ISSUE THREAD

**Issue by choupijiang** [apache/dolphinscheduler#16056]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Password stored in system table `t_ds_datasource` without encryption . 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
There is no plan to do these unless you want to submit a DSIP to support.

**Comment by hdygxsj** [comment]
I tried reslove it in issue-#16473
