### ISSUE TITLE
[Bug] [resource center] edit json which more than 3000 line will cut off 

### ISSUE THREAD

**Issue by zui01** [apache/dolphinscheduler#16072]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

if u upload a json to resource center,and the json more than 3000 line,the web page will only show 3000 line ,and if u click save button,the file in resource center will be 3000 line .

### What you expected to happen

the file should not be cut off to 3000 line when i edit it.

### How to reproduce

1.upload a json whiche is more than 3000 line like 6000 line
2.edit it in resource center
3.save it
4.download the josn and check it,the file will be 3000 line

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Yes, this is a bug, are you interested to fix this?
