### ISSUE TITLE
[Bug] [UI] pagination query cannot be used

### ISSUE THREAD

**Issue by 614230213** [apache/dolphinscheduler#16070]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Version 3.2.1 pagination query cannot be used

### What you expected to happen

Can system bugs be fixed

### How to reproduce

Open the workflow list and click the previous or next page buttons

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This will be fixed in #15619.
