### ISSUE TITLE
[Bug] [Build] Fix build

### ISSUE THREAD

**Issue by pegasas** [apache/dolphinscheduler#16074]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

fix build by add authenticate module introduced by https://github.com/apache/dolphinscheduler/pull/16043
https://github.com/apache/dolphinscheduler/actions/runs/9218984987/job/25363434865

### What you expected to happen

fix build by add authenticate module introduced by https://github.com/apache/dolphinscheduler/pull/16043
https://github.com/apache/dolphinscheduler/actions/runs/9218984987/job/25363434865

### How to reproduce

fix build by add authenticate module introduced by https://github.com/apache/dolphinscheduler/pull/16043
https://github.com/apache/dolphinscheduler/actions/runs/9218984987/job/25363434865

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
This is not a bug, the dolphinscheduler-aws-authentication is imported by `dolphinscheduler-common`

**Comment by pegasas** [comment]
it seems related to https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/zh/guide/resource/configuration.md?plain=1, done.
