### ISSUE TITLE
[Bug] [UI] Success message toast not works well

### ISSUE THREAD

**Issue by rockfang** [apache/dolphinscheduler#16087]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Success message toast not works well:
- [ ] click `Test Connect` button when create a datasource
- [ ] click `Test Send` button in alarm-instance-manage page
![image](https://github.com/apache/dolphinscheduler/assets/16065427/fa61ab3e-560e-43f4-a6a9-05d776f4306d)
![image](https://github.com/apache/dolphinscheduler/assets/16065427/30a42595-8922-4e04-af24-0583552feb1c)

### What you expected to happen

hope to show messages

### How to reproduce

1. Navigate to `DataSource` Menu
2. Create one available datasource
3. Click `Test Click` button

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rockfang** [comment]
I found the older version works well. but the latest `dev` has this problem.
Here is the reason:
1. backend response different `data` when connect successfuly
- older resonse    `{"code":0,"msg":"成功","data":null,"failed":false,"success":true}`
- latest response `{"code":0,"msg":"成功","data":true,"failed":false,"success":true}`
You see the `data` changed from `null` to `true`
2. frontend toast message depends on this `data`
![image](https://github.com/apache/dolphinscheduler/assets/16065427/a7ba39b1-0b26-4a96-b2fa-4d696f2bb445)

Suggest solution:
`window.$message.success(res && res.msg ? res.msg : 'fronted message..')`

**Comment by Gallardot** [comment]
LGTM, can you create a PR to fix this?

**Comment by rockfang** [comment]
@Gallardot I created a PR to fix it.
