### ISSUE TITLE
OceanBase Support

### ISSUE THREAD

**Issue by liuzheyi-1988** [apache/dolphinscheduler#16081]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

     In sql task nodes views，I can not select “OceanBase source” in  data source combobox . It means I could not use OceanBase sql in task nodes. But in data source views, I can create OceanBase data source.  
    Could the community solve my question just by  improving ui model adding “OceanBase source”  or  carrying out more improvements?
    OceanBase support is  important to us and my company.We  will look forward to your help

 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
@liuzheyi-1988 Which version? this problem should already been fixed at https://github.com/apache/dolphinscheduler/pull/15776.

**Comment by liuzheyi-1988** [comment]
Thanks for your helps
