### ISSUE TITLE
[Bug] [UI] Task instance list download log error 401

### ISSUE THREAD

**Issue by 614230213** [apache/dolphinscheduler#16080]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Task instance list download log error 401

### What you expected to happen

Confirm and fix system bugs

### How to reproduce

Task instance list download log error 401

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Please provide more details.
