### ISSUE TITLE
Can dolphinscheduler support calling remote flink?

### ISSUE THREAD

**Issue by wolfewf** [apache/dolphinscheduler#16090]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

dolphinscheduler能不能支持调用远程的flink

### What you expected to happen

dolphinscheduler能不能支持调用远程的flink

### How to reproduce

dolphinscheduler能不能支持调用远程的flink

### Anything else

dolphinscheduler能不能支持调用远程的flink

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
DS only support trigger remote shell. We have no plan to support remote trigger all tasks.

**Comment by wolfewf** [comment]
@ruanwenjun 不支持远程的flink 配置flink流程就没什么意义了
