### ISSUE TITLE
[Bug] [Task] Spark Task resources not exist

### ISSUE THREAD

**Issue by a1281069907** [apache/dolphinscheduler#16100]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After the spark jars(including main jar and config files) are submitted, spark task can not find the config file but the spark jar can be found... 
<img width="353" alt="bug1" src="https://github.com/apache/dolphinscheduler/assets/26783062/edfbc485-4afa-4a6e-83d9-8513135003d9">
<img width="629" alt="bug2" src="https://github.com/apache/dolphinscheduler/assets/26783062/65958170-f937-4e22-9229-ce4ea935db27">

### What you expected to happen

spark task can find the config file, the task can finish well.

### How to reproduce

if your spark task need a config file as a parameter, then the issue will be reproduced

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
@a1281069907 Can you find out these con files under the task instance working directory? I am not clear if this is caused by your code is incorrect, the conf file is not under classpath, please test you code locally.
