### ISSUE TITLE
[Bug] [Python Task] Execute python task failed with java error 

### ISSUE THREAD

**Issue by ArkURL** [apache/dolphinscheduler#16101]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

just create a workflow with only one python task node, which simply execute command `print("hello m")` and when execute this workflow an error happened.
execute log below
[1717146925671.log](https://github.com/user-attachments/files/15511387/1717146925671.log)

env:
os: centos7
database: postgresql-15
java: jdk1.8
python: python 3.6
zookeeper: zookeeper 3.7.x
dolphinscheduler: 3.2.1

deploy way: cluster deploy

I use new user `dolphinscheduler` to deploy and set dolphinschedueler's tenant is dolphinscheduler too.

### What you expected to happen

execute python node successfully

### How to reproduce

create a simple workflow with python node, execute command `print("hello m")` and execute the workflow.

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
I didn't meet this problem, you can have a try to use JDK 11 instead

**Comment by ArkURL** [comment]
solved it by change enviroment `PYTHON_LAUNCHER` and `PYTHON_HOME` to actual python path in `~/.bashrc`.
this error info occured again but can scheduler python node now.
