### ISSUE TITLE
SqlServer connection error

### ISSUE THREAD

**Issue by jnfJNF** [apache/dolphinscheduler#16112]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

连接SqlServer时报错：The server selected protocol version TLS10 is not accepted by client preferences [TLS12]

### What you expected to happen

连接SqlServer时报错：The server selected protocol version TLS10 is not accepted by client preferences [TLS12]

### How to reproduce

连接SqlServer时报错：The server selected protocol version TLS10 is not accepted by client preferences [TLS12]

### Anything else

连接SqlServer时报错：The server selected protocol version TLS10 is not accepted by client preferences [TLS12]

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Squidyu** [comment]
TLS10 is disabled in higher versions of JDK

**Comment by Squidyu** [comment]
https://cloud.tencent.com/developer/article/2127522 
You can refer to this article
