### ISSUE TITLE
[Bug] [DataSource] An error occurred in the connection to the MySQL data source

### ISSUE THREAD

**Issue by xunfeng224** [apache/dolphinscheduler#16114]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In version 3.2.1，When I successfully create a mysql data source and test the connection is successful. Click Edit Data Source, and then click Test Connection again. An error message is displayed: The test data source connection failed.At this time, the password on the page is "******", when I delete "******" and enter the correct password, the connection is successful.

### What you expected to happen

In the parameters passed from the frontend to the backend, the value of password becomes "******".
url:/dolphinscheduler/datasources/connect
![Uploading 1717467678663.png…]()

### How to reproduce

In version 3.2.1,using docker-compose to Start Server in windows environment.Create a MySQL data source that is successfully connected, and then test the connection again on the edit page

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xunfeng224** [comment]
![1717467678663](https://github.com/apache/dolphinscheduler/assets/76527787/f16c1107-5858-4e97-ac7c-c4cafdf7529c)

**Comment by Squidyu** [comment]
Suggest checking if the password information saved in db is correct

**Comment by xunfeng224** [comment]
I have checked the password in the database, and it is correct. This bug occurs after the test connection is successful and the data source is created, and then when you click "Edit" and "Test Connection" again. After briefly looking at the source code, it seems that it directly takes the "******" passed from the front-end as the password.

**Comment by SbloodyS** [comment]
Each edit requires the password to be re-entered, which is not a bug.
