### ISSUE TITLE
[Improvement][dolphinscheduler-dist] Reduce binary distribution file size

### ISSUE THREAD

**Issue by zhuxt2015** [apache/dolphinscheduler#16125]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Now the binary compressed package has exceeded 1GB, and it is no longer possible to release the version, and the file size is too large to be convenient for transmission and deployment.

My solution is to extract the jar files in the libs directory of all submodules to the libs directory of the common project root, and then the submodules use the soft links of the jar files.
After testing, the binary compressed package can be reduced from the original 1.2GB to 380MB

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Duplicated with #15960.

**Comment by zhuxt2015** [comment]
> Duplicated with #15960.

@SbloodyS Is the community decide to use the #15960 solution?

**Comment by SbloodyS** [comment]
> > Duplicated with #15960.
> 
> @SbloodyS Is the community decide to use the #15960 solution?

Feel free to discuss it in #15960 if you have any other opinions.
