### ISSUE TITLE
[Doc][Module Name] Documentation bug or improvement

### ISSUE THREAD

**Issue by listenLearning** [apache/dolphinscheduler#16124]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When using Docker Compose to install and deploy Dolphinscheduler in the reference document, when executing the `docker Compose -- profile schema up - d` command, the pull fails continuously, and the IP printed from the error log cannot be pinged properly
![image](https://github.com/apache/dolphinscheduler/assets/25893114/b13f7b11-7cd4-4b37-8707-57cd960a5daf)

### Documentation Links

https://dolphinscheduler.apache.org/zh-cn/docs/3.2.1/guide/start/docker

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You should check your network issue.
