### ISSUE TITLE
[Bug] [plugin] can not load env/dolphinscheduler_env.sh

### ISSUE THREAD

**Issue by sdvdxl** [apache/dolphinscheduler#16133]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

set `export SEATUNNEL_HOME="${SEATUNNEL_HOME:-/opt/seatunnel-2.3.5}"` in `bin/env/dolphinscheduler_env.sh` task log report ：
> /tmp/dolphinscheduler/exec/process/default/13865082550688/13865121489568_4/21/23/21_23.sh:行4: /bin/seatunnel.sh: 没有那个文件或目录

1. 

### What you expected to happen

should execute correct exec seatunnel command

### How to reproduce

1. set `export SEATUNNEL_HOME="${SEATUNNEL_HOME:-/opt/seatunnel-2.3.5}"` in `bin/env/dolphinscheduler_env.sh` 
2. start server `bin/dolphinscheduler-daemon.sh start standalone-server`
3. create project and seatunnel task 
4. run the job

### Anything else

I found the pr [Add source env list in common.properties](https://github.com/apache/dolphinscheduler/pull/13317)，but not auto load dolphinscheduler_env.sh file, only load the  specify explicitly  env files

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by blueflower1** [comment]
这里我直接配置了seatunnel的全局环境变量，这样配置文件在读取到${SEATUNNEL_HOME}时就正常了

**Comment by sdvdxl** [comment]
> 这里我直接配置了seatunnel的全局环境变量，这样配置文件在读取到${SEATUNNEL_HOME}时就正常了

@blueflower1 你这是什么版本，我用的3.2.0和3.2.1都需要手动在common配置中配置。 以前3.1.x版本，没有这个配置，可以直接使用环境变量

**Comment by blueflower1** [comment]
我使用的是3.2.1，我是直接在/etc/profile.d/env.sh中配置了seatunnel的环境变量

**Comment by blueflower1** [comment]
seatunnel和你一样也是2.3.5

**Comment by sdvdxl** [comment]
你这样配置应该是使用了默认的系统环境变量。 按照文档说在 dolphinscheduler_env.sh 中配置，没有被配置到系统环境变量中，没有读取到

**Comment by SbloodyS** [comment]
You need to use absolute paths instead of relative paths.

**Comment by sdvdxl** [comment]
> You need to use absolute paths instead of relative paths.

怎么配置？在哪配置绝对路径？ 
怎么这么快关闭了？

**Comment by zui01** [comment]
> You need to use absolute paths instead of relative paths.

are u creazy ,this is seatunnel task node,you tell me use absolute paths?

**Comment by Octivian** [comment]
Same issue : the bin/env/dolphinscheduler_env.sh is not working.

**Comment by qbmiller** [comment]
配了系统的，它自己的dolphinscheduler_env.sh，都不管用。

**Comment by daixixidai** [comment]
yes，the  official document is wrong，I met the same problem，tried every  solution。only the Environment Manage Setting can work。This is a mistake?

<img width="1326" height="288" alt="Image" src="https://github.com/user-attachments/assets/03070c57-8cec-4a05-8825-ae4477338a04" />
