### ISSUE TITLE
It is recommended to add instructions for building binary packages in version 3.2.1

### ISSUE THREAD

**Issue by jnfJNF** [apache/dolphinscheduler#16147]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

在3.2.1的Docker 快速使用教程中，未找到可以使用二进制构建的方法，在版本2.x中是有的。建议在新版本中新增该构建方式。
<img width="548" alt="0db279c38b14c7fa90d4ca11d045b22" src="https://github.com/apache/dolphinscheduler/assets/25213350/38147354-bc15-4ab5-b624-5b6453514b29">

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You can refer to https://dolphinscheduler.apache.org/zh-cn/docs/3.2.1/contribute/development-environment-setup

**Comment by jnfJNF** [comment]
我在https://hub.docker.com/search?q=DolphinScheduler看到有很多关于DolphinScheduler的镜像，其中apache/dolphinscheduler、apache/dolphinscheduler-operator无最新3.2.1的镜像，但是apache/dolphinscheduler-worker、apache/dolphinscheduler-standalone-server、apache/dolphinscheduler-api、apache/dolphinscheduler-master、apache/dolphinscheduler-alert-server、apache/dolphinscheduler-tools、apache/dolphinscheduler-helm 7个镜像有3.2.1的版本，如果我要进行docker部署DolphinScheduler应该怎么选择镜像部署？
![image](https://github.com/apache/dolphinscheduler/assets/25213350/71dca63b-d17f-4126-9081-dbb7f9a38ed9)
