### ISSUE TITLE
SQL task hive type sql parameters does not work

### ISSUE THREAD

**Issue by wangshubing1** [apache/dolphinscheduler#16143]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/apache/dolphinscheduler/assets/35355246/fc51b0b2-62c7-4cc8-bfc5-da86b8684646)
如图我使用的是 spark on hive,在SQL任务中配置了一些spark sql的参数
![image](https://github.com/apache/dolphinscheduler/assets/35355246/4b2fef21-bea3-4a20-a9c7-0f4852ac8b2e)
在任务运行日志中发现我配置的参数并未生效

### What you expected to happen

![image](https://github.com/apache/dolphinscheduler/assets/35355246/f5136915-578e-442d-98b4-1422fd3cff80)
我期望该参数可以生效，或者在SQL语句层面能 set 该参数

### How to reproduce

SQL 任务中 选择hive 类型；配置SQL参数，运行该任务可以从日志中看到结果

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Jzzzz24K** [comment]
解决了吗,我也遇到了这个问题
