### ISSUE TITLE
[Bug] [Module Name] The dependent task is stuck and cannot be executed

### ISSUE THREAD

**Issue by ahululu** [apache/dolphinscheduler#16156]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I created two tasks A,B, and A dependent on the execution of B (execute B first and then execute A). I manually executed task B and then proceeded to execute A. And then A is pending, and the log looks like this:

[INFO] 2024-06-14 02:58:57.073 +0000 - Send task status RUNNING_EXECUTION to master dolphinscheduler-master-0.dolphinscheduler-master-headless:5678
[INFO] 2024-06-14 02:58:57.074 +0000 - Success initialize task parameters:
{
"localParams" : null,
"varPool" : null,
"dependTaskList" : [ {
"dependItemList" : [ {
"projectCode" : xxxx,
"definitionCode" : xxxxx,
"depTaskCode" : 0,
"cycle" : "day",
"dateValue" : "today",
"dependResult" : null,
"status" : null,
"parameterPassing" : false
}],
"relation" : "AND"
}],
"relation" : "AND",
"checkInterval" : 10,
"failurePolicy" : "DEPENDENT_FAILURE_FAILURE",
"failureWaitingTime" : null
}
[INFO] 2024-06-14 02:58:57.074 +0000 - Initialized task plugin instance: DEPENDENT successfully
[INFO] 2024-06-14 02:58:57.074 + 0000-Initialize taskVarPool: null successfully
[INFO] 2024-06-14 02:58:57.074 +0000 - * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
[the INFO] 2024-06-14 02:58:57. 074 + 0000 - * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * the Execute a task instance * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
[INFO] 2024-06-14 02:58:57.074 +0000 - * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
[INFO] 2024-06-14 02:58:57.075 +0000 - Begin to initialize dependent task list
[INFO] 2024-06-14 02:58:57.078 +0000 - Add dependent task:
[INFO] 2024-06-14 02:58:57.078 +0000 - DependentRelation: AND
[INFO] 2024-06-14 02:58:57.079 + 0000-ProjectName: data-sync
[INFO] 2024-06-14 02:58:57.079 + 0000-WorkflowName: A-data-sync
[INFO] 2024-06-14 02:58:57.079 + 0000-DependentKey: xxxxxxx-0-day-today
[INFO] 2024-06-14 02:58:57.079 +0000 - Initialized dependent task list
[INFO] 2024-06-14 02:58:57.079 +0000 - Initialized dependent task list successfully

This is where it ends. There's no log

### What you expected to happen

I look forward to the completion of this task, not pending.

### How to reproduce

just create a depent task

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Is there any log in master?

**Comment by qazjiangchuan** [comment]
> Is there any log in master?

I found error logs on the master server.
<img width="1454" alt="image" src="https://github.com/apache/dolphinscheduler/assets/18412718/1daea057-358d-427e-85b1-a8bddebad672">

**Comment by ruanwenjun** [comment]
> > Is there any log in master?
> 
> I found error logs on the master server. <img alt="image" width="1454" src="https://private-user-images.githubusercontent.com/18412718/343096823-1daea057-358d-427e-85b1-a8bddebad672.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MTY4NjksIm5iZiI6MTcxOTQxNjU2OSwicGF0aCI6Ii8xODQxMjcxOC8zNDMwOTY4MjMtMWRhZWEwNTctMzU4ZC00MjdlLTg1YjEtYThiZGRlYmFkNjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDE1NDI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxZTIwODY3MmQ5OWIwMzRjMjdhMTk4ZWM5NTQ1NTc5ZTEyM2Q5ZTE4ZWEwMThlMDE2Yjc4YjU1ZTM5ZjM2ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sKJ6bYXQfEl-mERGY5qO_Dg8Y2qFcOrgDT5mzCR8ay0">

which version are you use, is this can reproduce? seems your  miss some libs.

**Comment by qazjiangchuan** [comment]
> > > Is there any log in master?
> > 
> > 
> > I found error logs on the master server. <img alt="image" width="1454" src="https://private-user-images.githubusercontent.com/18412718/343096823-1daea057-358d-427e-85b1-a8bddebad672.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MTY4NjksIm5iZiI6MTcxOTQxNjU2OSwicGF0aCI6Ii8xODQxMjcxOC8zNDMwOTY4MjMtMWRhZWEwNTctMzU4ZC00MjdlLTg1YjEtYThiZGRlYmFkNjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDE1NDI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxZTIwODY3MmQ5OWIwMzRjMjdhMTk4ZWM5NTQ1NTc5ZTEyM2Q5ZTE4ZWEwMThlMDE2Yjc4YjU1ZTM5ZjM2ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sKJ6bYXQfEl-mERGY5qO_Dg8Y2qFcOrgDT5mzCR8ay0">
> 
> which version are you use, is this can reproduce? seems your miss some libs.

used v3.2.1 ,and It is deployed in Pseudo-Cluster mode.

**Comment by ruanwenjun** [comment]
I am not sure if you package is correct, please check if permission of lib is correct.
