### ISSUE TITLE
[DSIP-46] Unify the logic task params data structure between front-end and back-end

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#16153]
### Search before asking

- [X] I had searched in the [DSIP](https://github.com/apache/dolphinscheduler/issues/14102) and found no similar DSIP.

### Motivation

The logic task params in backend is not structure, we need to parse the logic params from some fields. 
This make us to use some extra JSON deserialize code, and make the logic is very hard to maintain.

https://github.com/apache/dolphinscheduler/blob/f0e0395b36bba5977135a3b7b4472b91ec388e50/dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskInstance.java#L313-L385

### Design Detail

Directly parse the logic task params from task params.

### Compatibility, Deprecation, and Migration Plan

compatibility

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cncws** [comment]
Hope this DSIP can solve the problem I had：[Bug] [PyTorch] pythonCommand is not used at runtime, it's always using ${PYTHON_LAUNCHER} #15961

**Comment by ruanwenjun** [comment]
> Hope this DSIP can solve the problem I had：[Bug] [PyTorch] pythonCommand is not used at runtime, it's always using ${PYTHON_LAUNCHER} #15961

This DSIP will not fixed this problem, you need to define a PYTHON_LAUNCHER at your environment
