### ISSUE TITLE
Add rename and other buttons

### ISSUE THREAD

**Issue by xqg1316** [apache/dolphinscheduler#16173]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Want to add rename, batch online, batch offline button in the workflow definition 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
It's better to split this into 3 issues, this is three feature.
