### ISSUE TITLE
[Bug] [service down] service down and stop when use `bash bin/start-all.sh` a few seconds 

### ISSUE THREAD

**Issue by ArkURL** [apache/dolphinscheduler#16174]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I use cluster deploy to deploy dolphinscheduler service to 2 server.
server and service running env below:
os: centos7
db: postgresql-15.7
zookeeper: 3.7.2
python: python3.6
java: java-11

I deploy the service dolphinscheduler to 2 server and make them both be master-server and worker-server.
when use `bash bin/start-all.sh`, every service work well and run perfect, but a few second later, some master-server and worker-server went down, but some workflow still can run.

at the first time every server work well.
![image](https://github.com/apache/dolphinscheduler/assets/56484166/f78a3e87-2671-482c-90a0-c27bc1c1ee3e)

few seconds later, some server down but some workflow can still run.
![image](https://github.com/apache/dolphinscheduler/assets/56484166/d4dd5a38-f24b-41a5-aca7-1e404bbff89f)

how to solve it?  here is two server's master-server log file.
[dolphinscheduler-master.log](https://github.com/user-attachments/files/15883737/dolphinscheduler-master.log)
[dolphinscheduler-master_2.log](https://github.com/user-attachments/files/15883738/dolphinscheduler-master_2.log)

### What you expected to happen

service work well and not down.
[dolphinscheduler-master_2.log](https://github.com/user-attachments/files/15883753/dolphinscheduler-master_2.log)
[dolphinscheduler-master.log](https://github.com/user-attachments/files/15883754/dolphinscheduler-master.log)

### How to reproduce

use cluster deploy and make them all master-server and worker-server.then start the service.

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
It's better to deprecated below six scripts, these scripts is not settled and I've rarely seen a project that offers a distributed deployment.  @SbloodyS 

<img width="401" alt="image" src="https://github.com/apache/dolphinscheduler/assets/22415594/056395c0-a0e9-476a-855c-081082d60d05">

**Comment by SbloodyS** [comment]
> It's better to deprecated below six scripts, these scripts is not settled and I've rarely seen a project that offers a distributed deployment. @SbloodyS
> 
> <img alt="image" width="401" src="https://private-user-images.githubusercontent.com/22415594/340740207-056395c0-a0e9-476a-855c-081082d60d05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODM4ODgsIm5iZiI6MTcxODc4MzU4OCwicGF0aCI6Ii8yMjQxNTU5NC8zNDA3NDAyMDctMDU2Mzk1YzAtYTBlOS00NzZhLTg1NWMtMDgxMDgyZDYwZDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA3NTMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4Mjc1ZTM2MzY0ZjVjYTFmMTQzNjdlYzU5YzNhN2FiM2UzMjNjYmIwNWZmYTQ5NzNiZDRkY2EwZjFlNzZmMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IvID7TDZCAg09ZNGpJYjsNeBLBJnQEnxEXgbN07CTDQ">

+1

I'll remove it in a few days.

**Comment by ruanwenjun** [comment]
> > It's better to deprecated below six scripts, these scripts is not settled and I've rarely seen a project that offers a distributed deployment. @SbloodyS
> > <img alt="image" width="401" src="https://private-user-images.githubusercontent.com/22415594/340740207-056395c0-a0e9-476a-855c-081082d60d05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODM4ODgsIm5iZiI6MTcxODc4MzU4OCwicGF0aCI6Ii8yMjQxNTU5NC8zNDA3NDAyMDctMDU2Mzk1YzAtYTBlOS00NzZhLTg1NWMtMDgxMDgyZDYwZDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA3NTMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4Mjc1ZTM2MzY0ZjVjYTFmMTQzNjdlYzU5YzNhN2FiM2UzMjNjYmIwNWZmYTQ5NzNiZDRkY2EwZjFlNzZmMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IvID7TDZCAg09ZNGpJYjsNeBLBJnQEnxEXgbN07CTDQ">
> 
> +1
> 
> I'll remove it in a few days.

Thanks.

**Comment by ruanwenjun** [comment]
@ArkURL Thanks for your report this problem, we plan to remove these kind of script, this means you should start the server in remote server after ssh login.
