### ISSUE TITLE
dolphinscheduler-ui  build

### ISSUE THREAD

**Issue by xiaoqufengdi** [apache/dolphinscheduler#16181]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I open dolphinscheduler-ui by webstorm, then run build, the project reported a large number of  type errors.
version:3.2.2

### What you expected to happen

Package successfully

### How to reproduce

`npm run build:prod`

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please consult the documentation before asking questions.
https://dolphinscheduler.apache.org/en-us/docs/3.2.1/contribute/development-environment-setup
