### ISSUE TITLE
[Bug] Timed task not trigger

### ISSUE THREAD

**Issue by 1032851561** [apache/dolphinscheduler#16197]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/apache/dolphinscheduler/assets/15909510/4aaa4b74-570c-4c9d-b69e-db6e0bc0646d)

![image](https://github.com/apache/dolphinscheduler/assets/15909510/496dca06-cbc4-44d4-abef-4c1bb29587c3)

```
[INFO] 2024-06-21 16:57:01.556 +0800 o.a.d.s.q.QuartzScheduler:[104] - Add job, job name: job_39, group name: jobgroup_1
[INFO] 2024-06-21 16:57:01.606 +0800 o.a.d.s.q.QuartzScheduler:[137] - schedule job trigger, triggerName: job_39, triggerGroupName: jobgroup_1, cronExpression: 10 * * * * ? *, startDate: Fri Jun 21 16:57:01 CST 2024, endDate: Wed Jun 21 00:00:00 CST 2124
```

My timed task add success but never trigger

### What you expected to happen

The task should be triggered every minute.

### How to reproduce

Just create a 'shell' task , print some message , online this timed task.

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
The start time is `Fri Jun 21 16:57:01 CST 2024`

**Comment by ruanwenjun** [comment]
Is there any error log in master? or error command in t_ds_error_command?
You can get the scheduler count metrics by `ds_master_quartz_job_executed`

**Comment by 1032851561** [comment]
> Is there any error log in master? or error command in t_ds_error_command? You can get the scheduler count metrics by `ds_master_quartz_job_executed`

1. no error log in master and api service
2. two records in t_ds_error_command
3. how can i get the metrics of `ds_master_quartz_job_executed` ?
4. `ProcessScheduleTask#executeInternal` is not running yet. Is it running in dolphinscheduler-api server?

**Comment by 1032851561** [comment]
> > Is there any error log in master? or error command in t_ds_error_command? You can get the scheduler count metrics by `ds_master_quartz_job_executed`
> 
> 1. no error log in master and api service
> 2. two records in t_ds_error_command, I had deleted, but not work.
> 3. not found metrics of `ds_master_quartz_job_executed` , just found `ds_master_consume_command_count_total{application="master-server",} 0.0`
> 4. `ProcessScheduleTask#executeInternal` is not running yet. Is it running in dolphinscheduler-api server?
> 5. after many cycles have passed, there is not new record generated in table 't_ds_process_instance' .

**Comment by ruanwenjun** [comment]
`ProcessScheduleTask#executeInternal` is running on master. You need to provide more information, e.g. your cluster information, is this bug can reproduce?

**Comment by 1032851561** [comment]
> `ProcessScheduleTask#executeInternal` is running on master. You need to provide more information, e.g. your cluster information, is this bug can reproduce?

The bug is alway exist. All timed job not trigger. 
My cluster: docker deployment , 1 master ,1 worker ,1 apiserver , postgresql database

The process goes like this:
1. All timed tasks are normal for a long time.
2. Dorck exception , master,worker,api server down.
3. Start cluster, all task not trigger.
4. found error in master , some log like 'Master handle command xxx error '
5. Manually changing the record xxx in the tds_process_instance table : state -> 7
6. Delete all records in t_ds_error_command
7. Restart master , have not error log any more.


I can't see the log of ProcessScheduleTask in master: `scheduled fire time :{}, fire time......`, so is quartz something wrong?

![image](https://github.com/apache/dolphinscheduler/assets/15909510/2e90f5d5-d3bb-428d-9278-527c55b0dd5c)
![image](https://github.com/apache/dolphinscheduler/assets/15909510/fe191703-aab5-4b63-a462-e8a319cf7785)

[master.log](https://github.com/user-attachments/files/15942397/master.log)

**Comment by 1032851561** [comment]
> `ProcessScheduleTask#executeInternal` is running on master. You need to provide more information, e.g. your cluster information, is this bug can reproduce?

I try to debug master:
![image](https://github.com/apache/dolphinscheduler/assets/15909510/c76a9dd0-87d1-469c-bd28-3ab06b3b7db7)

run the sql directly:
![image](https://github.com/apache/dolphinscheduler/assets/15909510/3d90fdbc-2f3f-451f-96f5-ca32d6b250af)

**Comment by ruanwenjun** [comment]
> 4\. found error in master , some log like 'Master handle command xxx error '

This is caused by master handle command failed, you can find the reason from t_ds_error_command or master error log

**Comment by 1032851561** [comment]
> > 4. found error in master , some log like 'Master handle command xxx error '
> 
> This is caused by master handle command failed, you can find the reason from t_ds_error_command or master error log

![image](https://github.com/apache/dolphinscheduler/assets/15909510/497a0d09-edce-43c0-add5-286bc2a15479)

https://github.com/apache/dolphinscheduler/issues/16197#issuecomment-2184493186

**Comment by ruanwenjun** [comment]
> > > 4. found error in master , some log like 'Master handle command xxx error '
> > 
> > 
> > This is caused by master handle command failed, you can find the reason from t_ds_error_command or master error log
> 
> ![image](https://private-user-images.githubusercontent.com/15909510/342195940-497a0d09-edce-43c0-add5-286bc2a15479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTY1NjUsIm5iZiI6MTcxOTQ5NjI2NSwicGF0aCI6Ii8xNTkwOTUxMC8zNDIxOTU5NDAtNDk3YTBkMDktZWRjZS00M2MwLWFkZDUtMjg2YmMyYTE1NDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEzNTEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMDMyZjUwYjY3NDE2NzhkMDBjNjI1MzBiY2MxNjBjZGJmNDNmMGU1NGIzNGEzOWM4ZDljMjJkMjE1YzNkZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PBplLoOPFyIA7CAZsEmpYo6Ta1jbdXZPcyE2RKHB-J4)
> 
> [#16197 (comment)](https://github.com/apache/dolphinscheduler/issues/16197#issuecomment-2184493186)

If you delete the records from t_ds_error_command, then you cannot find out the reason why the command handle failed. I am not clear why you delete these, these will not affect the system.

**Comment by 1032851561** [comment]
> > > > 4. found error in master , some log like 'Master handle command xxx error '
> > > 
> > > 
> > > This is caused by master handle command failed, you can find the reason from t_ds_error_command or master error log
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/15909510/342195940-497a0d09-edce-43c0-add5-286bc2a15479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTY1NjUsIm5iZiI6MTcxOTQ5NjI2NSwicGF0aCI6Ii8xNTkwOTUxMC8zNDIxOTU5NDAtNDk3YTBkMDktZWRjZS00M2MwLWFkZDUtMjg2YmMyYTE1NDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEzNTEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMDMyZjUwYjY3NDE2NzhkMDBjNjI1MzBiY2MxNjBjZGJmNDNmMGU1NGIzNGEzOWM4ZDljMjJkMjE1YzNkZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PBplLoOPFyIA7CAZsEmpYo6Ta1jbdXZPcyE2RKHB-J4)
> > [#16197 (comment)](https://github.com/apache/dolphinscheduler/issues/16197#issuecomment-2184493186)
> 
> If you delete the records from t_ds_error_command, then you cannot find out the reason why the command handle failed. I am not clear why you delete these, these will not affect the system.

My problem is not why the command handler failed . Instead, `ProcessScheduleTask` why doesn't  execute, this is a quratz job ,it not trigger.

please see this : https://github.com/apache/dolphinscheduler/issues/16197#issuecomment-2184493186

**Comment by ruanwenjun** [comment]
> > > > > 4. found error in master , some log like 'Master handle command xxx error '
> > > > 
> > > > 
> > > > This is caused by master handle command failed, you can find the reason from t_ds_error_command or master error log
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/15909510/342195940-497a0d09-edce-43c0-add5-286bc2a15479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTY1NjUsIm5iZiI6MTcxOTQ5NjI2NSwicGF0aCI6Ii8xNTkwOTUxMC8zNDIxOTU5NDAtNDk3YTBkMDktZWRjZS00M2MwLWFkZDUtMjg2YmMyYTE1NDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEzNTEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMDMyZjUwYjY3NDE2NzhkMDBjNjI1MzBiY2MxNjBjZGJmNDNmMGU1NGIzNGEzOWM4ZDljMjJkMjE1YzNkZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PBplLoOPFyIA7CAZsEmpYo6Ta1jbdXZPcyE2RKHB-J4)
> > > [#16197 (comment)](https://github.com/apache/dolphinscheduler/issues/16197#issuecomment-2184493186)
> > 
> > 
> > If you delete the records from t_ds_error_command, then you cannot find out the reason why the command handle failed. I am not clear why you delete these, these will not affect the system.
> 
> My problem is not why the command handler failed . Instead, `ProcessScheduleTask` why doesn't execute, this is a quratz job ,it not trigger.
> 
> please see this : [#16197 (comment)](https://github.com/apache/dolphinscheduler/issues/16197#issuecomment-2184493186)

I'm still not sure what your problem is at the moment, right now ds process timing task will have two steps:
1. Generate command by quartz task
2. Execute the command.

You means the step one is wrong? There are many reason may cause the step one not execute.
e.g. quartz metadata is incorrect, quartz main thread is block, db lock.
You can find some detail from the log and check if there exist dead lock in db.

**Comment by 1032851561** [comment]
> > > > > > 4. found error in master , some log like 'Master handle command xxx error '
> > > > > 
> > > > > 
> > > > > This is caused by master handle command failed, you can find the reason from t_ds_error_command or master error log
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/15909510/342195940-497a0d09-edce-43c0-add5-286bc2a15479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTY1NjUsIm5iZiI6MTcxOTQ5NjI2NSwicGF0aCI6Ii8xNTkwOTUxMC8zNDIxOTU5NDAtNDk3YTBkMDktZWRjZS00M2MwLWFkZDUtMjg2YmMyYTE1NDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEzNTEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMDMyZjUwYjY3NDE2NzhkMDBjNjI1MzBiY2MxNjBjZGJmNDNmMGU1NGIzNGEzOWM4ZDljMjJkMjE1YzNkZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PBplLoOPFyIA7CAZsEmpYo6Ta1jbdXZPcyE2RKHB-J4)
> > > > [#16197 (comment)](https://github.com/apache/dolphinscheduler/issues/16197#issuecomment-2184493186)
> > > 
> > > 
> > > If you delete the records from t_ds_error_command, then you cannot find out the reason why the command handle failed. I am not clear why you delete these, these will not affect the system.
> > 
> > 
> > My problem is not why the command handler failed . Instead, `ProcessScheduleTask` why doesn't execute, this is a quratz job ,it not trigger.
> > please see this : [#16197 (comment)](https://github.com/apache/dolphinscheduler/issues/16197#issuecomment-2184493186)
> 
> I'm still not sure what your problem is at the moment, right now ds process timing task will have two steps:
> 
> 1. Generate command by quartz task
> 2. Execute the command.
> 
> You means the step one is wrong? There are many reason may cause the step one not execute. e.g. quartz metadata is incorrect, quartz main thread is block, db lock. You can find some detail from the log and check if there exist dead lock in db.

Yes， step one is wrong , it is never tigger. Quartz main thread is running , it query the table `qrtz_triggers` to find some timed job has triggered. When I debug the master service remotely, the code shows 0 records, but running the sql directly in the database shows 3 records.

**Comment by ruanwenjun** [comment]
> > > > > > > 4. found error in master , some log like 'Master handle command xxx error '
> > > > > > 
> > > > > > 
> > > > > > This is caused by master handle command failed, you can find the reason from t_ds_error_command or master error log
> > > > > 
> > > > > 
> > > > > ![image](https://private-user-images.githubusercontent.com/15909510/342195940-497a0d09-edce-43c0-add5-286bc2a15479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTY1NjUsIm5iZiI6MTcxOTQ5NjI2NSwicGF0aCI6Ii8xNTkwOTUxMC8zNDIxOTU5NDAtNDk3YTBkMDktZWRjZS00M2MwLWFkZDUtMjg2YmMyYTE1NDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEzNTEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMDMyZjUwYjY3NDE2NzhkMDBjNjI1MzBiY2MxNjBjZGJmNDNmMGU1NGIzNGEzOWM4ZDljMjJkMjE1YzNkZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PBplLoOPFyIA7CAZsEmpYo6Ta1jbdXZPcyE2RKHB-J4)
> > > > > [#16197 (comment)](https://github.com/apache/dolphinscheduler/issues/16197#issuecomment-2184493186)
> > > > 
> > > > 
> > > > If you delete the records from t_ds_error_command, then you cannot find out the reason why the command handle failed. I am not clear why you delete these, these will not affect the system.
> > > 
> > > 
> > > My problem is not why the command handler failed . Instead, `ProcessScheduleTask` why doesn't execute, this is a quratz job ,it not trigger.
> > > please see this : [#16197 (comment)](https://github.com/apache/dolphinscheduler/issues/16197#issuecomment-2184493186)
> > 
> > 
> > I'm still not sure what your problem is at the moment, right now ds process timing task will have two steps:
> > 
> > 1. Generate command by quartz task
> > 2. Execute the command.
> > 
> > You means the step one is wrong? There are many reason may cause the step one not execute. e.g. quartz metadata is incorrect, quartz main thread is block, db lock. You can find some detail from the log and check if there exist dead lock in db.
> 
> Yes， step one is wrong , it is never tigger. Quartz main thread is running , it query the table `qrtz_triggers` to find some timed job has triggered. When I debug the master service remotely, the code shows 0 records, but running the sql directly in the database shows 3 records.

Is the date is correct of the master machine?

**Comment by 1032851561** [comment]
> > > > > > > > 4. found error in master , some log like 'Master handle command xxx error '
> > > > > > > 
> > > > > > > 
> > > > > > > This is caused by master handle command failed, you can find the reason from t_ds_error_command or master error log
> > > > > > 
> > > > > > 
> > > > > > ![image](https://private-user-images.githubusercontent.com/15909510/342195940-497a0d09-edce-43c0-add5-286bc2a15479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTY1NjUsIm5iZiI6MTcxOTQ5NjI2NSwicGF0aCI6Ii8xNTkwOTUxMC8zNDIxOTU5NDAtNDk3YTBkMDktZWRjZS00M2MwLWFkZDUtMjg2YmMyYTE1NDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEzNTEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMDMyZjUwYjY3NDE2NzhkMDBjNjI1MzBiY2MxNjBjZGJmNDNmMGU1NGIzNGEzOWM4ZDljMjJkMjE1YzNkZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PBplLoOPFyIA7CAZsEmpYo6Ta1jbdXZPcyE2RKHB-J4)
> > > > > > [#16197 (comment)](https://github.com/apache/dolphinscheduler/issues/16197#issuecomment-2184493186)
> > > > > 
> > > > > 
> > > > > If you delete the records from t_ds_error_command, then you cannot find out the reason why the command handle failed. I am not clear why you delete these, these will not affect the system.
> > > > 
> > > > 
> > > > My problem is not why the command handler failed . Instead, `ProcessScheduleTask` why doesn't execute, this is a quratz job ,it not trigger.
> > > > please see this : [#16197 (comment)](https://github.com/apache/dolphinscheduler/issues/16197#issuecomment-2184493186)
> > > 
> > > 
> > > I'm still not sure what your problem is at the moment, right now ds process timing task will have two steps:
> > > 
> > > 1. Generate command by quartz task
> > > 2. Execute the command.
> > > 
> > > You means the step one is wrong? There are many reason may cause the step one not execute. e.g. quartz metadata is incorrect, quartz main thread is block, db lock. You can find some detail from the log and check if there exist dead lock in db.
> > 
> > 
> > Yes， step one is wrong , it is never tigger. Quartz main thread is running , it query the table `qrtz_triggers` to find some timed job has triggered. When I debug the master service remotely, the code shows 0 records, but running the sql directly in the database shows 3 records.
> 
> Is the date is correct of the master machine?

The date is correct.

**Comment by ruanwenjun** [comment]
@1032851561 If this occurs next time, please provide the whole log of your masters. I have no idea now.
