### ISSUE TITLE
[Bug] [WEB] Workflow instance page forms cannot be paginated

### ISSUE THREAD

**Issue by 1032851561** [apache/dolphinscheduler#16201]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Workflow instance page forms cannot be paginated

![image](https://github.com/apache/dolphinscheduler/assets/15909510/628753c4-d1a4-4377-b10e-ecda49c179ff)

### What you expected to happen

normal paging.

### How to reproduce

alway

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Fixed in #15619
