### ISSUE TITLE
[Bug] [Api] Using the TaskDefinitionController-save-single interface can lead to duplicate predecessor tasks.

### ISSUE THREAD

**Issue by xiaoqisu777** [apache/dolphinscheduler#16202]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Use this API
![image](https://github.com/apache/dolphinscheduler/assets/60653240/d921e99d-ee34-4969-8b34-6de7dfb15a15)
 Adding a task adds an additional front-end node,
![image](https://github.com/apache/dolphinscheduler/assets/60653240/4187d8b7-9241-43fa-81ac-2899b4e39ae7)
![image](https://github.com/apache/dolphinscheduler/assets/60653240/00e35cc6-4be8-490d-9079-ddb69c571179)
 If too many tasks are added, it can cause the workflow details to get stuck when opening.

### What you expected to happen

I expect each task to have only one predecessor node,
like this
![image](https://github.com/apache/dolphinscheduler/assets/60653240/2b45e376-dd6e-4e61-bf39-d15ab9283ee5)

### How to reproduce

use this api >1 time  ,you can  reproduce the problem
![image](https://github.com/apache/dolphinscheduler/assets/60653240/c193ca4c-045b-4f4a-aed7-7ad3b67c69d9)

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Please don't use the task page to create new task, there is a lot of bugs here, we don't want to change the code here, unless you want to refactor the whole process.
