### ISSUE TITLE
[DSIP-51][Task] Remove unused pigeon task plugin

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#16218]
### Search before asking

- [X] I had searched in the [DSIP](https://github.com/apache/dolphinscheduler/issues/14102) and found no similar DSIP.

### Motivation

Remove udf manage function since this feature has almost no users and many bugs and cves.

### Design Detail

1. Remove backend part.
2. Remove frontend part.
3. Remove e2e part.
4. Remove UT part.
5. Remove docs part.

### Compatibility, Deprecation, and Migration Plan

Add to imcompatble doc.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
+1, this plugin looks like a demo, and seems there is no user use it.
