### ISSUE TITLE
[Bug] [3.2.1] upload jar  

### ISSUE THREAD

**Issue by taincheng** [apache/dolphinscheduler#16235]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Relatively small jar files can be uploaded, such as jar packages without dependencies
![Xnip2024-06-28_17-27-22](https://github.com/apache/dolphinscheduler/assets/39717320/a349fc2c-e902-4771-8356-89eb0ca896bb)

When uploading a jar file of size 46mb, there is an error
![Xnip2024-06-28_17-20-54](https://github.com/apache/dolphinscheduler/assets/39717320/88f498bf-85b8-4e8a-a853-816878374b2f)
![Xnip2024-06-28_17-21-29](https://github.com/apache/dolphinscheduler/assets/39717320/35b72ee7-2d0f-489b-b22d-b574d2760ac3)

### What you expected to happen

Able to upload files normally

### How to reproduce

version：3.2.1
jar file size：46mb

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You should check your network.

**Comment by taincheng** [comment]
> You should check your network.
It won't be a network issue, the spark/shell tasks can be executed as well as scheduled online normally.
I've looked at the error reporting details for the front-end code, but I'm not good at this and would like to give a more detailed localization of the issue:
I am going to roll back the version to 3.1.8
![Xnip2024-07-01_10-51-58](https://github.com/apache/dolphinscheduler/assets/39717320/d3f2c770-8eab-4f47-9760-b7b4e7b34e81)

**Comment by SbloodyS** [comment]
Base on the image you upload, there is multiple `ERR_CONNECTION_RESET` errors in your console ouput.

**Comment by taincheng** [comment]
> Base on the image you upload, there is multiple `ERR_CONNECTION_RESET` errors in your console ouput.

Thank you very much for your help, I just checked my local network and found that http was proxied by other software, after closing the proxy in question, I can use the upload function normally!
