### ISSUE TITLE
[Bug] [dolphinscheduler-dao][3.1.9] FLINK_STREAM task。in  Stream Task list Page , If the process version corresponding to the task instance is different from the current process version 

### ISSUE THREAD

**Issue by qinxiang01** [apache/dolphinscheduler#16230]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

`version 3.1.9`
In the `TaskInstanceMapper `file `queryStreamTaskInstanceListPaging ` method, sql  should be join `t_ds_process_task_relation_log `table

### What you expected to happen

Page missing information

### How to reproduce

After running a `Flink_Stream `and updating the process, the `Workflow Name` field  in the Stream Task is missing

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
The Flink Stream task is about to be deprecated.
