### ISSUE TITLE
[Bug] [worker-server] Users of the complement type task are switched to default

### ISSUE THREAD

**Issue by taincheng** [apache/dolphinscheduler#16249]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

While executing the make-up task, the user I choose is hive, when executing the first day's make-up task, the scheduling is using the hive user to execute, but in the second day's make-up task, the scheduling will default to using the default user to execute the task, which leads to the issue of privilege failure.
![Xnip2024-07-01_15-29-20](https://github.com/apache/dolphinscheduler/assets/39717320/53442260-9fab-4785-9819-3d8de4edacd7)

The first day's make up task:
![Xnip2024-07-01_15-30-42](https://github.com/apache/dolphinscheduler/assets/39717320/db41654b-1c92-46cd-96a4-1fae5215a605)

The second day's make-up count task uses the default user:
![Xnip2024-07-01_15-32-04](https://github.com/apache/dolphinscheduler/assets/39717320/4ea42024-f950-4a75-bd01-0b0d3418f91e)

### What you expected to happen

I'd like to be able to use the user of my choice for all my tasks, instead of switching to the default user.

### How to reproduce

In version 3.2.1
When submitting a spark complement task it happens that the

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This have been fixed in #16092. Will be released in 3.3.0.
