### ISSUE TITLE
Too many task instance queries

### ISSUE THREAD

**Issue by freedata2022** [apache/dolphinscheduler#16243]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![1719800877994](https://github.com/apache/dolphinscheduler/assets/109134839/1d1c4767-0030-494c-82d2-2866ff2f5409)

### What you expected to happen

![1719800877994](https://github.com/apache/dolphinscheduler/assets/109134839/702b5525-d3c7-40a4-9bac-867087cddbb0)

### How to reproduce

![1719800877994](https://github.com/apache/dolphinscheduler/assets/109134839/08c06196-6bfd-4ebe-a9e5-ae92de24edce)

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please describe your problem clearly.
