### ISSUE TITLE
[Doc][TaskParams] The incorrect document screenshot of the task parmas passing

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#16257]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

https://dolphinscheduler.apache.org/zh-cn/docs/3.2.1/guide/parameter/priority

![图片](https://github.com/apache/dolphinscheduler/assets/11962619/e879cd1f-0eca-485d-a615-09b8347f7ec8)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by QuakeWang** [comment]
Please assign it to me, I will fix it later :)

**Comment by SbloodyS** [comment]
> Please assign it to me, I will fix it later :)

Done.
