### ISSUE TITLE
[Bug] [Master] Dependent nodes failed when the upstream rerun without the task relied on

### ISSUE THREAD

**Issue by starrysxy** [apache/dolphinscheduler#16285]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

First of all, I'm not sure if this is a code bug. I checked the code and the phenomenon is consistent with the current code logic, but for the business logic, I don't think it is very reasonable. If necessary, please help to modify the tag.

Suppose there are two workflows A and B. Workflow A has tasks A-1, A-2, and A-3. Workflow B depends on task A-3 in workflow A. When the A workflow is finished, if the A-1 task in the A workflow is re-executed separately and the B workflow instance in the same cycle has not been executed, the dependent node in the B workflow will fail, which will cause the B workflow instance to fail.

The logic in the code is to find the workflow instance with the latest endTime in each cycle, so the workflow instance where the A-1 task is executed alone will be found, but this workflow instance does not have the A-3 task that the downstream B workflow depends on. Therefore, after getting the A workflow instance, the A-3 task instance cannot be found when traversing the task instances. At the same time, the A workflow instance is in the completed state, so the dependent node is marked as failed, and then the B workflow is marked as failed.

In my opinion, the logic of this part of the code is to facilitate the selection of 'ALL' for dependent tasks, without having to check the status of each task in the upstream workflow, but directly check the status of the entire upstream workflow. However, I think that in actual work, it is inevitable to modify the workflow, and it is also inevitable to re-execute the task after modifying the workflow. At the same time, re-executing the entire workflow may lead to problems such as late result output and waste of machine resources. Therefore, the logic here may be optimized.

### What you expected to happen

If a dependent task in an upstream workflow has ever succeeded, the node status of the dependent task in the downstream workflow of the same cycle should be marked as successful.

### How to reproduce

Suppose there are two workflows A and B. Workflow A has tasks A-1, A-2, and A-3. Workflow B depends on task A-3 in workflow A. When the A workflow is finished, if the A-1 task in the A workflow is re-executed separately and the B workflow instance in the same cycle has not been executed, the dependent node in the B workflow will fail, which will cause the B workflow instance to fail.

### Version

3.1.x

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by starrysxy** [comment]
I saw you commented in another question(https://github.com/apache/dolphinscheduler/issues/15807#issuecomment-2041720428), please take some time to look at this one, thanks @SbloodyS

**Comment by SbloodyS** [comment]
The `ALL` in a dependency means that all tasks in the workflow need to be executed successfully. If you want to re-execute a node in the workflow without affecting the results of the dependent nodes, you should choose tasks in the dependency workflow or reorganize your workflow. @starrysxy

**Comment by starrysxy** [comment]
> The `ALL` in a dependency means that all tasks in the workflow need to be executed successfully. If you want to re-execute a node in the workflow without affecting the results of the dependent nodes, you should choose tasks in the dependency workflow or reorganize your workflow. @starrysxy

Thanks for your comment, I know the `ALL` in a dependency means that all tasks in the workflow need to be executed successfully. But my downstream only depends on 1 task in the upstream, not all tasks. 

When I re-execute a node in the upstream, the dependent node in the downstream will fail if the downstream is executed after the upstream is successfully re-executed.

e.g: Upstream dispatch at 1 a.m. Meanwhile, downstream dispatch at 10 a.m. If I re-execute one task in the upstream, that is not dependent on the dependent node in the downstream, in the upstream at 7 a.m. And it will be successful in 1 hour. The downstream will fail in few seconds when it's dispatched at 10 a.m.

I hope I made myself clear. This may not be a code bug, but it is a very common requirement. Is there any good way to avoid this situation?

**Comment by SbloodyS** [comment]
> The `ALL` in a dependency means that all tasks in the workflow need to be executed successfully. If you want to re-execute a node in the workflow without affecting the results of the dependent nodes, you should choose tasks in the dependency workflow or reorganize your workflow. @starrysxy

Like I said. The `ALL` in a dependency means that all tasks in the workflow need to be executed successfully. In particular, it prevents you from manually re-executing a node like this. If the downstream execution continues only after all upstream nodes are executed, manually executing a single node is an illegal operation, which may cause downstream data exceptions.

**Comment by starrysxy** [comment]
> > The `ALL` in a dependency means that all tasks in the workflow need to be executed successfully. If you want to re-execute a node in the workflow without affecting the results of the dependent nodes, you should choose tasks in the dependency workflow or reorganize your workflow. @starrysxy
> 
> Like I said. The `ALL` in a dependency means that all tasks in the workflow need to be executed successfully. In particular, it prevents you from manually re-executing a node like this. If the downstream execution continues only after all upstream nodes are executed, manually executing a single node is an illegal operation, which may cause downstream data exceptions.

I'm sure I get you. But my downstream don't depend on all tasks in the upstream, but only one task. I'll show you some screenshots.

e.g: Upstream dispatch at 1 a.m. Meanwhile, downstream dispatch at 10 a.m. If I re-execute one task in the upstream, that is not dependent on the dependent node in the downstream, in the upstream at 7 a.m. And it will be successful in 1 hour. The downstream will fail in few seconds when it's dispatched at 10 a.m.

**This is my upstream:**
<img width="1128" alt="daa236d776e100056fe3b606d919e9e" src="https://github.com/apache/dolphinscheduler/assets/167744606/32ccd318-b7f7-42c6-aafa-a7ea05ab0bc6">

**This is my downstream:**
<img width="1128" alt="3e0fce1054ad27666a66260dc5845e3" src="https://github.com/apache/dolphinscheduler/assets/167744606/ba397e28-6e2a-48d1-8842-b758993131f3">

**This is the dependent node:**
<img width="1128" alt="0aafe2fd40c157bd64c53963b678852" src="https://github.com/apache/dolphinscheduler/assets/167744606/3782ff36-550c-4024-8a40-d2f0e9c28b1b">

**This is how I re-excute only one task in the upstream:**
(Right-click on the task node and type the 'excute' button)
<img width="1128" alt="e6cbc3bd6740c99b33bd99e2544aedb" src="https://github.com/apache/dolphinscheduler/assets/167744606/51c1378f-9ab4-4b21-be9c-f0847056b14f">

**Comment by SbloodyS** [comment]
I think I know what your problem is. The current dependency node check will get the latest workflow instance to verify that the task instance in it meets the configuration conditions. However, this judgment does not take into account the case of manually starting individual tasks, which can only execute some of the nodes. This scenario calls for a solution discussion.

cc @caishunfeng @ruanwenjun @EricGao888 @rickchengx

**Comment by starrysxy** [comment]
> I think I know what your problem is. The current dependency node check will get the latest workflow instance to verify that the task instance in it meets the configuration conditions. However, this judgment does not take into account the case of manually starting individual tasks, which can only execute some of the nodes. This scenario calls for a solution discussion.
> 
> cc @caishunfeng @ruanwenjun @EricGao888 @rickchengx

Yes, that's what I mean. Btw, my version is 3.1.8.(The logic of this part is still the same in later versions). I have checked the code, and I think this scenario is common, especially if you've just switched to DS from another dispatch system. Because tasks will not be migrated all at once, but will be migrated one by one, which means the process definition will be modified frequently.

**Maybe we can start with these two places in the code:**
1. `org.apache.dolphinscheduler.server.master.utils.DependentExecute#calculateResultForTasks`
![image](https://github.com/apache/dolphinscheduler/assets/167744606/400537b5-5c17-47a7-a164-afbc999eabf1)

2. `org.apache.dolphinscheduler.server.master.utils.DependentExecute#getDependTaskResult`
![image](https://github.com/apache/dolphinscheduler/assets/167744606/22958c94-93c5-43e5-9438-aea3bdaff7d6)

**Comment by ruanwenjun** [comment]
> I think I know what your problem is. The current dependency node check will get the latest workflow instance to verify that the task instance in it meets the configuration conditions. However, this judgment does not take into account the case of manually starting individual tasks, which can only execute some of the nodes. This scenario calls for a solution discussion.
> 
> cc @caishunfeng @ruanwenjun @EricGao888 @rickchengx

In my opinion, this is a bug, the task instance status should not bind with workflow instance status.

**Comment by starrysxy** [comment]
> I think I know what your problem is. The current dependency node check will get the latest workflow instance to verify that the task instance in it meets the configuration conditions. However, this judgment does not take into account the case of manually starting individual tasks, which can only execute some of the nodes. This scenario calls for a solution discussion.
> 
> cc @caishunfeng @ruanwenjun @EricGao888 @rickchengx

Looking forward to others' opinions.

**Comment by SbloodyS** [comment]
> In my opinion, this is a bug, the task instance status should not bind with workflow instance status.

+1

**Comment by starrysxy** [comment]
@SbloodyS When I try to fix this bug, using the dev branch, I found it has been fixed in https://github.com/apache/dolphinscheduler/pull/15795. But the bug is still there in version 3.1.x. I'm not sure if I should commit to fix this bug in version 3.1.x. If yes, which brach should I use to commit a PR.

**Comment by SbloodyS** [comment]
> @SbloodyS When I try to fix this bug, using the dev branch, I found it has been fixed in #15795. But the bug is still there in version 3.1.x. I'm not sure if I should commit to fix this bug in version 3.1.x. If yes, which brach should I use to commit a PR.

After take a deep look at it, I found the task instance status still bind with workflow instance status in the `dev` branch.

**Comment by starrysxy** [comment]
> > @SbloodyS When I try to fix this bug, using the dev branch, I found it has been fixed in #15795. But the bug is still there in version 3.1.x. I'm not sure if I should commit to fix this bug in version 3.1.x. If yes, which brach should I use to commit a PR.
> 
> After take a deep look at it, I found the task instance status still bind with workflow instance status in the `dev` branch.

You mean current fix is not good enough, right? BTW, I found a new scenario which could cause the same problem.

Both workflows are the same as https://github.com/apache/dolphinscheduler/issues/16285#issuecomment-2216171367

I set the failure retry time for A-3 to 5 minutes. Assume that A workflow failed at 7:00 am, because A-3 is failed. Then B workflow failed at 7:03, because at that time, A-3's status is failure. At 7:05, A-3 retried and succeeded. So, when I check the result of the both workflows, I found the status of A is success and B is failure.

So, I think if a task like A-3 is depended by other tasks and a retry policy has been set, the status of the downstream task should be waiting until the upstream task has no more retries.

**Comment by SbloodyS** [comment]
This PR #15795 fixes a different issue.

**Comment by starrysxy** [comment]
> This PR #15795 fixes a different issue.

I think this PR fixes the same issue. The defference between #15795 and #15707 is that the instance is triggered by scheduler or manually. Both will get the same result.

**Comment by SbloodyS** [comment]
#15795 has nothing to do with `the task instance status should not bind with workflow instance status`

**Comment by starrysxy** [comment]
> #15795 has nothing to do with `the task instance status should not bind with workflow instance status`

ok, I get you. I mean #15795 worked. I'll find a new way to fix this issue.

BTW, please take a look at this scenario(https://github.com/apache/dolphinscheduler/issues/16285#issuecomment-2290629944) again.

Do you think the status of the downstream task should be waiting until the upstream task has no more retries?

**Comment by SbloodyS** [comment]
> Do you think the status of the downstream task should be waiting until the upstream task has no more retries?

Yes. However, it is not easy to implement under the existing architecture. We can optimze it after this refatoring is merged. #16423

**Comment by starrysxy** [comment]
OK, I'll find a new way to fix this issue first, which will make the task instance not bind with the workflow instance status. And I'll take a look at the new architecture later.

**Comment by SbloodyS** [comment]
> OK, I'll find a new way to fix this issue first, which will make the task instance not bind with the workflow instance status. And I'll take a look at the new architecture later.

You can start from here `org.apache.dolphinscheduler.server.master.utils.DependentExecute#dependResultByAllTaskOfProcessInstance`

**Comment by EricGao888** [comment]
@starrysxy It is a bug. However, I don't think it still exists in 3.2.2-release or dev. You could cherry-pick related stuff to patch your local code.

As you could see in the below code fragments, in the latest logic, the query joins the task instances table to make sure the upstream task included when querying last workflow instance.

https://github.com/apache/dolphinscheduler/blob/57c80f2af5d1f29417fdbea09b27221f54987655/dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml#L192-L234

But this logic was added only in and after 3.2.2-release:

https://github.com/apache/dolphinscheduler/blob/15d356b79d4dc14fa187f618107bc50e824061ac/dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml#L209-L236

cc @SbloodyS @ruanwenjun

**Comment by starrysxy** [comment]
@EricGao888 Yes, like I said, https://github.com/apache/dolphinscheduler/pull/15795 and https://github.com/apache/dolphinscheduler/pull/15712 worked. But I think @SbloodyS wants to find a new way to fix this bug, which will make the task instance not bind with the workflow instance status. Am I right?

> But this logic was added only in and after 3.2.2-release:
<select id="queryLastRunningProcess"...>
    ...

My dev branch is the lastest version, and I have also checked 3.2.2-release branch, but I can't find `<select id="queryLastRunningProcess"...>`.
