### ISSUE TITLE
[Question] [package]  After modifying the source code，maven packaged the code ,cannot find the tar.gz package in the dir "target"

### ISSUE THREAD

**Issue by eelnomel** [apache/dolphinscheduler#16283]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After modifying the source code，maven packaged the code ,cannot find the tar.gz package in the dir "target", there is no 'apache-dolphinscheduler-"${VERSION}"-bin.tar.gz' file, source code version:3.1.9

### What you expected to happen

after maven packaging, i can have 'apache-dolphinscheduler-"${VERSION}"-bin.tar.gz' file

### How to reproduce

just pull the code in local,and maven package

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xxzuo** [comment]
Is there no  `apache-dolphinscheduler-"${VERSION}"-bin.tar.gz`  file in the  `dolphinscheduler-dist/target` directory ?

**Comment by ruanwenjun** [comment]
Please provide the full package command and the full path of `target`.
