### ISSUE TITLE
[ERROR]  org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[47] - Meet en unknown exception:  org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): org.apache.dolphinscheduler.dao.mapper.DqRuleExecuteSqlMapper.getExecuteSqlList[Bug] [Module Name] Bug title 

### ISSUE THREAD

**Issue by shenhaitao010** [apache/dolphinscheduler#16282]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

选择数据质量菜单，规则管理时报的错误：获取规则分页列表错误。
使用的版本：3.2.1
后台日志如下：
[ERROR] 2024-07-05 17:59:13.243 +0800 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[47] - Meet en unknown exception: 
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): org.apache.dolphinscheduler.dao.mapper.DqRuleExecuteSqlMapper.getExecuteSqlList

### What you expected to happen

无

### How to reproduce

无

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please using english and ask questions according to the issue template.

**Comment by caojcm** [comment]
我碰到了同样的问题，请问解决了没
