### ISSUE TITLE
[QUESTION] There seems to be a problem with the the ftp command

### ISSUE THREAD

**Issue by antti8** [apache/dolphinscheduler#1630]
we use the dolphinscheduler 1.05 now. and sometime we need to use ftp in the shell script,  the ftp commond keep runniing and don't exit in most of the time. When we try to run the same shell in the machine which dolphinscheduler  installed ,the script get the result we want. So I think if there is something wrong with the ftp support in dolphinscheduler ?
  our ftp like this:
`lftp -u username,password  sftp://172.1.1.1:22 << EOF`
`cd /`
`put cnt.dat`
`close`
`bye`
`EOF`

In 100 times, the problem happened about 30 times.

**Comment by xingchun-chen** [comment]
who can look the problem?
