### ISSUE TITLE
[Bug] [Doc] query resources list paging&UDF management not displayed

### ISSUE THREAD

**Issue by zhang-dz** [apache/dolphinscheduler#16308]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

这是我在开发环境 3.2.2-prepared 中遇到的问题，相关服务启动时没有报错，但进入 DS 系统后却不显示 UDF 管理，并报错资源列表查询错误，也无法进行创建文件夹、上传文件等相关操作。
This is the problem I encountered in the development environment 3.2.2-prepared, the relevant services start without any reported error, but after I enter the DS system does not show the UDF management, and reported an error resource list query error, also can not create folders, upload files and other related operations.

### What you expected to happen

我看到配置文件中提到要有\tmp\dolphinscheduler\读写权限，但我第一次完美运行 DS 系统时并没有在意这一点，但后来运行时也没有发现任何错误。
I see that the configuration file says to have \tmp\dolphinscheduler\ read and write permissions, but I didn't care about that the first time I ran the DS system perfectly, but I didn't find any errors on subsequent runs.

### How to reproduce

我是按照官方教程进行开发环境的部署
https://dolphinscheduler.apache.org/zh-cn/docs/3.2.1/contribute/development-environment-setup
I followed the official tutorial to deploy the development environment

### Anything else

However, the first time I Git down DS-3.2.2 and compile and run it there was no such error (no UDF management and folder creation failures), but since I didn't start the alert node successfully the first time, after I re-git it down and compile and run it, I started getting the above problem

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
By default, DS will use `/tmp/dolphinscheduler` as resource directory but we can change this at common.properties, are you willing to announce this in doc?
