### ISSUE TITLE
[Bug] [Module Name] Bug title 

### ISSUE THREAD

**Issue by guigui20** [apache/dolphinscheduler#16302]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="689" alt="image" src="https://github.com/apache/dolphinscheduler/assets/137984888/84ad2ab0-eaac-4530-a3a7-5b6db176c62d">
i want to delete a process,it tells me
'the status of process instance 龟龟-2-20240711030817066 is READY_PAUSE,Cannot perform delete operation.'
but i write a 'while True' without ending.So,it is always in ready_pause,i cannot pause it so i can not delete it.

### What you expected to happen

help me pause or delete this process

### How to reproduce

i dont know

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please using the correct title.

**Comment by wangxj3** [comment]
The pause will wait the running task to end,i think you already know this. you want to delete this process instance ,so you don't care about this task .you shoud stop instead of pause ;

**Comment by ruanwenjun** [comment]
Not all kind of task support pause opearation, most task doenot support pause, this means you need to wait the task finish, then will pause the next task
