### ISSUE TITLE
[Bug] [Standalone Server] Showing Connection Spring Boot-MySql : Public Key Retrieval is not allowed while trying to init the database

### ISSUE THREAD

**Issue by aaryan-purohit** [apache/dolphinscheduler#16313]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

While trying to follow steps mentioned in https://github.com/apache/dolphinscheduler/blob/3.1.3-release/docs/docs/en/guide/howto/datasource-setting.md, I tried to init the database using script : bash tools/bin/upgrade-schema.sh. It showed the error - [Connection Spring Boot-MySql : Public Key Retrieval is not allowed

### What you expected to happen

I expected that it would initialize the database and created all the sql tables needed so that all metadata will be stored even after dolphinscheduler server is stopped.

### How to reproduce

Follow the commands mentioned in https://github.com/apache/dolphinscheduler/blob/3.1.3-release/docs/docs/en/guide/howto/datasource-setting.md for mysql and init the database.

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please provide more error logs. @aaryan-purohit

**Comment by aaryan-purohit** [comment]
Here are the logs after running bash tools/bin/upgrade-schema.sh script - 
![image](https://github.com/user-attachments/assets/f2130791-4ad8-42bc-9e25-2896b7d36094)

**Comment by xxzuo** [comment]
This might be a configuration issue. You can try the JDBC settings mentioned here: https://stackoverflow.com/questions/50379839/connection-java-mysql-public-key-retrieval-is-not-allowed 
to see if it resolves the problem.

**Comment by aaryan-purohit** [comment]
Yes, this fixes the issue. But shouldn't this be mentioned in the https://github.com/apache/dolphinscheduler/blob/3.1.3-release/docs/docs/en/guide/howto/datasource-setting.md also?

**Comment by SbloodyS** [comment]
JDBC has a lot of parameters, and we won't document all of the third-party parameters. Please refer to the relevant documentation if necessary.

**Comment by aaryan-purohit** [comment]
Thanks for helping.
