### ISSUE TITLE
[Bug] [Resource] Failed to upload file

### ISSUE THREAD

**Issue by JohnZp** [apache/dolphinscheduler#16346]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The bug is that when re uploading files, it will prompt **file extension cannot not change**
![image](https://github.com/user-attachments/assets/a031816a-b778-48ad-a15c-148d540f9b98)

### What you expected to happen

work well

### How to reproduce

![image](https://github.com/user-attachments/assets/42b671c7-c226-48cd-ba0d-9965e2b11f53)

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please provide reproduce steps and deployment environment. I can not reproduce this issue locally.

**Comment by JohnZp** [comment]
> Please provide reproduce steps and deployment environment. I can not reproduce this issue locally.

The second bug is a security interception issue, not a problem with the dolphinscheduler. I have already removed it.
The first bug occurred when the wrong method was used to retrieve the file name when re uploading the problem code. Maybe it should like this
``` java
        if (!Objects.equals(
                Files.getFileExtension(
                        file.getOriginalFilename() == null ? file.getName() : file.getOriginalFilename()),
                Files.getFileExtension(updateFileDto.getFileAbsolutePath()))) {
            throw new ServiceException("file extension cannot not change");
        }
```

**Comment by SbloodyS** [comment]
Did you mean reupload function error? @JohnZp

**Comment by JohnZp** [comment]
> Did you mean reupload function error? @JohnZp

yes

**Comment by SbloodyS** [comment]
> The second bug is a security interception issue, not a problem with the dolphinscheduler. I have already removed it. The first bug occurred when the wrong method was used to retrieve the file name when re uploading the problem code. Maybe it should like this
> 
> ```java
>         if (!Objects.equals(
>                 Files.getFileExtension(
>                         file.getOriginalFilename() == null ? file.getName() : file.getOriginalFilename()),
>                 Files.getFileExtension(updateFileDto.getFileAbsolutePath()))) {
>             throw new ServiceException("file extension cannot not change");
>         }
> ```

I've reproduce this error successfully. You got it. Would you like to fix it? @JohnZp
