### ISSUE TITLE
I custom the WorkerHeartBeat send every 100 seconds,but the zookeeper session didn't expired?

### ISSUE THREAD

**Issue by Musknine** [apache/dolphinscheduler#16350]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

i send hearbeart every 100 seconds, but the session wasn't expired.

### What you expected to happen

![4164d9df3d54ff54513f9897029f3f5](https://github.com/user-attachments/assets/d333899e-26c4-4aaf-9b15-19e8b7f325ef)
accoding to the configuration,the session should expired after 30 seconds when there is not any request using the session.

### How to reproduce

![90b892a2bdbd0b552866c41e5df5160](https://github.com/user-attachments/assets/00dd31d6-f27b-401f-8efe-d02df603d005)
![355fe7769a9006465a39cdfbe21d2e4](https://github.com/user-attachments/assets/c06f5102-094f-4458-83a5-b7ebf4d8a1a9)
![ebdaf0a909eace49eb3c571b281868b](https://github.com/user-attachments/assets/14ef3c79-4267-4fb3-9ff1-7fdd72017a6c)

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
ZK session will not affected by heartbeat here, since heartbeat is business data. Zk session is maintained by its own heartbeat.

**Comment by Musknine** [comment]
@ruanwenjun     ok,thank you very much for your help.
