### ISSUE TITLE
[Doc][Pseudo-Cluster Deployment] 3.2.2 version, Missing files install.sh and install_env.sh

### ISSUE THREAD

**Issue by hxw8187** [apache/dolphinscheduler#16358]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://github.com/user-attachments/assets/cdb4f8b2-3a33-4622-97b5-68d658e6b302)
![image](https://github.com/user-attachments/assets/5affc0c8-15c0-4eef-83ed-7413610aae6d)

### Documentation Links

https://dolphinscheduler.apache.org/zh-cn/docs/3.2.1/guide/installation/pseudo-cluster
https://dolphinscheduler.apache.org/zh-cn/docs/3.2.2/guide/installation/pseudo-cluster

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This has been removed.

**Comment by sharfy** [comment]
没看到为啥删掉

**Comment by ljs033** [comment]
> This has been removed.

那怎么启动？

**Comment by antliu2012** [comment]
我检查了install.sh install_env.sh 这两个文件，他们的作用只是将应用包进行分发部署。所以在3.2.2版本可以直接在多个机器中部署，并指向同一个zookeeper和db即可。
I checked the two files install.sh install_env.sh. Their function is only to distribute and deploy application packages, so in version 3.2.2, they can be directly deployed on multiple machines and point to the same zookeeper and db.
@ljs033 @hxw8187
