### ISSUE TITLE
[Feature][Master] Allows updating workflows and restarting failed Tasks while the workflow is running

### ISSUE THREAD

**Issue by lizc9** [apache/dolphinscheduler#16368]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Allows updating workflows and restarting failed Tasks while the workflow is running

### Use case

Scenario 1: In the running workflow instance, there is a still running Task1 and a failed Task2, but Task1 needs to run for 2 hours. I either have to kill the entire workflow or wait for the workflow to finish running for 2 hours before resuming Task2. If Task1 has been executed 
halfway, it will take another 2 hours to kill the workflow and rerun it, but the best solution is to directly allow the failed Task2 to be rerun.
Scenario 2: Maybe you can set the number of retries for Task2, but sometimes you need to modify the parameters of Task2 to rerun successfully, so you also need to allow the parameters of Task2 to be modified in the running workflow.
![screenshot-20240725-131834](https://github.com/user-attachments/assets/4d6939d9-c618-4690-9da7-4062db9d180a)
![screenshot-20240725-131957](https://github.com/user-attachments/assets/443524b2-ab41-4a52-88da-5b8942742e28)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I don't think this is part of the normal workflow. A running workflow that is modified at the same time will cause a running disorder.

**Comment by lizc9** [comment]
> I don't think this is part of the normal workflow. A running workflow that is modified at the same time will cause a running disorder.

Recovery of failed tasks on running workflows is supported even if it is not allowed to modify workflows
