### ISSUE TITLE
[Bug] Worker works fine and link to zookeeper works fine, but ui can't display worker

### ISSUE THREAD

**Issue by Johp-t** [apache/dolphinscheduler#16364]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/user-attachments/assets/939c02aa-ce7b-45eb-bbda-8d11cd65b8be)
![image](https://github.com/user-attachments/assets/30fd6a19-d59e-4955-97b8-64939d26e1a6)

### What you expected to happen

I want the worker to display properly in the ui.

### How to reproduce

I've done iptables -F and restarted Dolphinscheduler.

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
This may caused by the API/Alert doesn't handle the zk reconnect event, does the zk has been restarted?

**Comment by Johp-t** [comment]
> 这可能是由于 API/Alert 没有处理 zk 重新连接事件导致的，zk 是否已重新启动？

zookeeper has been restarted and reinstalled. So far Alert doesn't see an error either
