### ISSUE TITLE
[Feature] Add Javascript Support for DolphinScheduler

### ISSUE THREAD

**Issue by bingyun84** [apache/dolphinscheduler#16362]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add Javascript Support for DolphinScheduler

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
What do you mean by add javascript support? Can you elaborate it? @bingyun84

**Comment by davidzollo** [comment]
I'm also confused about this feature request. Why should we add JS support?

**Comment by bingyun84** [comment]
> What do you mean by add javascript support? Can you elaborate it? @bingyun84

JavaScript is a flexible scripting language that does not need to be compiled into an executable file. At the same time, JavaScript supports dynamic typing, allowing variables to be changed to any type as needed, making programming more flexible.
Thank you！

**Comment by SbloodyS** [comment]
Do you mean you want to add a javascript task plugin? @bingyun84
