### ISSUE TITLE
[Bug] [3.2.2] New worker group not available

### ISSUE THREAD

**Issue by howardhhm** [apache/dolphinscheduler#16381]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I've been using DolphinScheduler for a long time, and recently I want to upgrade from version 3.2.0 to 3.2.2. I'm deploying the cluster using Docker Compose, but I'm encountering an issue where, when I create a new Worker Group in the Worker Group Manage, the only option available in the Worker Group for the Shell task in Create Workflow is "default". It should show the new Worker Group I just created.

### What you expected to happen

 It should show the new Worker Group I just created.

### How to reproduce

1. Version 3.2.2
2. Create a new Worker Group in the Worker Group Manage
3. The only option available in the Worker Group for the Shell task in Create Workflow is "default"

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please refer to the doc in https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/guide/project/project-list.md#project-worker-group-authorization

**Comment by jalousiex** [comment]
仍然发现一个新问题：
旧的存量项目升级后默认有default分组权限，但新建项目，无法分配default分组，此时具体任务的分组默认是default，但选择列表是空的；
如果新建分组并分配给新项目，然后在分组下拉框选择了新分组，列表里就再也选不到default了
![image](https://github.com/user-attachments/assets/412ddfcd-f9fc-4ba2-a7fe-adcf2812c76a)

不好意思，过了一会儿default又显示勾选了，是浏览器或什么缓存导致的？
