### ISSUE TITLE
Dolphin Scheduler with Podman/Docker Image not executable ? 

### ISSUE THREAD

**Issue by Mer0winger** [apache/dolphinscheduler#16383]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

i installed on my host a Podman and a Postgres Server inside.  Images are from  docker.io/apache/dolphinscheduler used. 
inside there is a Network "pgNetwork" created within the i range  10.*. because i installed pgAdmin as well in Podman and want access to database per Name "pgPostgresServer" . Both Applications working well together i can use pgAdmin to work in postgres. 

So i tried now to install the dolphin scheduler also within podman and want to reuse this db i already have. 
Until a very long conversiation with ChatGPT it was not very helpfull i found ot that i have to set the DATABASE_ parameters by my selfe and the mapping of application.yaml ( code next ) has no effect because the start scripts overwriting the SPRING_ parameters with that. :( 

So far so good it looked like dolphin useing the Database now and i also found tables created inside there. I used this podman command below to debug and start the scheduler but it run into some springframework errors which i cant mitigate.  ( debug log is in the attachment !) 

Any idea how i can solve this issue ? Is it a Bug or simple do i miss a konfiguration to solve it . 

thanks br thomas 

cat /usr/share/scripts/postgres/application.yaml 
-----------
spring:
  datasource:
    url: jdbc:postgresql://pgPostgresServer:5432/dolphinscheduler
    username: postgres
    password: 62686400
    driver-class-name: org.postgresql.Driver
-----------

Podman Start Container 
-----------
podman run -d --name dolphinscheduler --network pgNetwork \
  -v /usr/share/scripts/postgres/application.yaml:/opt/apache-dolphinscheduler-2.0.5-bin/conf/application-postgresql.yaml \
  -e DATABASE_HOST=pgPostgresServer \
  -e DATABASE_PORT=5432 \
  -e DATABASE_USERNAME=postgres \
  -e DATABASE_PASSWORD=62686400 \
  -e SPRING_DATASOURCE_URL=jdbc:postgresql://pgPostgresServer:5432/dolphinscheduler \
  -e SPRING_DATASOURCE_USERNAME=postgres \
  -e SPRING_DATASOURCE_PASSWORD=123456789 \
  -p 12345:12345 \
  apache/dolphinscheduler:latest all

[dolphin_log.log](https://github.com/user-attachments/files/16404023/dolphin_log.log)

### What you expected to happen

dolphin scheduler could be reached by  localhost:12345 from my host 

### How to reproduce

1) install podman 
2) install images for postgres , pgAdmin and dolphin scheduler 
3) create a network interface for all oth them 
4) create container with this network interface 
5) try to create a dolphin container fails with comman in the problem under what happend.  

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You should rebuild images if you want to use podman.
