### ISSUE TITLE
Front-end packaging error

### ISSUE THREAD

**Issue by liusy-bd** [apache/dolphinscheduler#16387]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Front-end packaging error

![image](https://github.com/user-attachments/assets/d2467228-4da0-4a5d-a1bf-330a3f7834cc)

### What you expected to happen

Added code review mechanism?

### How to reproduce

[root@LAPTOP-KAHM10NT dolphinscheduler-ui]# npm run build:prod

> dolphinscheduler-ui@0.0.0 build:prod
> vue-tsc --noEmit && vite build --mode production

src/App.tsx:74:33 - error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

74           {this.isRouterAlive ? <router-view /> : ''}
                                   ~~~~~~~~~~~~~~~

src/components/chart/modules/Bar.tsx:90:7 - error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

 90       <div
          ~~~~
 91         ref='barChartRef'
    ~~~~~~~~~~~~~~~~~~~~~~~~~
...
 95         }}
    ~~~~~~~~~~
 96       />
    ~~~~~~~~

src/components/chart/modules/Gauge.tsx:132:7 - error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

### Anything else

_No response_

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please correct the title and describe the issue clearly. I don't quite understand what your question is. @liusy-bd

**Comment by liusy-bd** [comment]
> 请更正标题并清楚描述问题。我不太明白你的问题是什么。@liusy-bd

![image](https://github.com/user-attachments/assets/2a58c9e3-2eee-400b-aabe-aa334ffc9103)


dolphinscheduler-ui    run 【npm run build:prod】 error

**Comment by Gallardot** [comment]
please have a try like this
```
pnpm run build:prod
```

It is OK on my environment.

**Comment by liusy-bd** [comment]
> 请尝试一下
> 
> ```
> pnpm run build:prod
> ```
> 
> 在我的环境中这是正常的。

![image](https://github.com/user-attachments/assets/0d425cf1-d775-49e4-a269-f5a51f23375c)
Same error

**Comment by liusy-bd** [comment]
> 请尝试一下
> 
> ```
> pnpm run build:prod
> ```
> 
> 在我的环境中这是正常的。

![image](https://github.com/user-attachments/assets/f401cceb-9ea4-4679-94fe-6770e09f19f0)
It's okay that I removed the type check,  That seems to be the problem

**Comment by vshallc** [comment]
Add these lines to your `tsconfig.json` if not existed:
```
{
  "compilerOptions": {
    "jsx": "preserve",
    "jsxImportSource": "vue"
  }
}
```
