### ISSUE TITLE
[DSIP-59] Suggest remove single task definition code and ui

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#16394]
### Search before asking

- [X] I had searched in the [DSIP](https://github.com/apache/dolphinscheduler/issues/14102) and found no similar DSIP.

### Motivation

There are a lot of bugs in the current single task definition, and no one continues to maintain it. And there is additional work involved in creating and updating the relevant code for workflow maintenance. So I suggest remove it.

![LMPkbAnTRe5lym7.png](https://cdn.sa.net/2024/07/30/LMPkbAnTRe5lym7.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Gallardot** [comment]
LGTM

**Comment by ruanwenjun** [comment]
+1

**Comment by caishunfeng** [comment]
+1

**Comment by someorz** [comment]
Deleting these APIs will have a great impact on ds integration through APIs.

**Comment by SbloodyS** [comment]
> Deleting these APIs will have a great impact on ds integration through APIs.

These apis will be deprecated and no longer supported in the new version.
