### ISSUE TITLE
docker compose deploy the dolphinscheduler how to enable gateway address

### ISSUE THREAD

**Issue by lgb861213** [apache/dolphinscheduler#16392]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

docker compose deploy the dolphinscheduler how to enable gateway address

### What you expected to happen

docker compose deploy the dolphinscheduler how to enable gateway address

### How to reproduce

docker compose deploy the dolphinscheduler how to enable gateway address

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
What do you mean by gateway address? @lgb861213

**Comment by lgb861213** [comment]
> �What do you mean by gateway address? @lgb861213

it means how to change the docker compose yaml file and enable the python gateway ; You can refer to the following link for instructions
https://dolphinscheduler.apache.org/python/main/start.html#start-python-gateway-service

#################
Please make sure you already started Python gateway service along with api-server. You can enabled it via

Environment: export API_PYTHON_GATEWAY_ENABLED=”true”

Configuration File: Set python-gateway.enabled : true in api-server/conf/application.yaml

**Comment by SbloodyS** [comment]
> > �What do you mean by gateway address? @lgb861213
> 
> it means how to change the docker compose yaml file and enable the python gateway ; You can refer to the following link for instructions https://dolphinscheduler.apache.org/python/main/start.html#start-python-gateway-service
> 
> ################# Please make sure you already started Python gateway service along with api-server. You can enabled it via
> 
> Environment: export API_PYTHON_GATEWAY_ENABLED=”true”
> 
> Configuration File: Set python-gateway.enabled : true in api-server/conf/application.yaml

This document has a very clear description of the startup method.
