### ISSUE TITLE
[Feature][resource center] Can the resource center support Tencent Cloud COS

### ISSUE THREAD

**Issue by kiwi-field** [apache/dolphinscheduler#16396]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I am currently using HDFS in the resource center and I want to migrate to Tencent Cloud COS uniformly. What changes do I need to make? Tencent Cloud's bucket is public read

### Use case

After switching to Tencent Cloud COS, you can perform upload, download, and preview operations in the resource center

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Currently there are no plans to support it.

**Comment by kiwi-field** [comment]
Can I connect to Tencent Cloud COS through the dependency of S3Utils and AWS Java SDK S3

**Comment by SbloodyS** [comment]
You can try it, but cos doesn't work well with S3.

**Comment by kiwi-field** [comment]
![image](https://github.com/user-attachments/assets/794639ec-1065-40fd-96bd-026f7dfeecf6)
The above picture shows our program configuration, and when downloading from the resource center, the following error occurred。
![image](https://github.com/user-attachments/assets/13e13be7-4be8-4f27-af53-af069730ecbc)

**Comment by kiwi-field** [comment]
It is obvious that AWS Java SDK S3 is designed for Amazon S3 cloud services, not the S3 protocol

**Comment by kiwi-field** [comment]
![image](https://github.com/user-attachments/assets/14a49e5c-f855-402f-ab70-13b9090dc6c8)
The optional regions are shown in the above figure

**Comment by kiwi-field** [comment]
@SbloodyS

**Comment by fuchanghai** [comment]
for me ,it work

**Comment by Mighten** [comment]
Hi, I am currently working on this feature (#16396) to support Tencent Cloud COS as a storage plugin in DS.

Could you please assign this issue to me?

This work is due by September 30, 2024.

**Comment by fuchanghai** [comment]
> Hi, I am currently working on this feature (#16396) to support Tencent Cloud COS as a storage plugin in DS.
> 
> Could you please assign this issue to me?
> 
> This work is due by September 30, 2024.

done
