### ISSUE TITLE
[Bug] [Alert Server] The alarm mode of the http request failed

### ISSUE THREAD

**Issue by lvyaj** [apache/dolphinscheduler#16401]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/user-attachments/assets/0cc7f33e-e2b2-496f-8f0f-c36619c07c21)
![image](https://github.com/user-attachments/assets/16231201-63c7-4429-a103-f7755df18e82)
Parsing failure

### What you expected to happen

The http alarm is sent normally

### How to reproduce

![image](https://github.com/user-attachments/assets/671f6815-5873-4af2-af51-bca194a64fb2)
According to this configuration

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Would you like to fix it? @lvyaj

**Comment by lvyaj** [comment]
> Would you like to fix it? @lvyaj

So,Is there a problem with my operation or a code error?

**Comment by SbloodyS** [comment]
> So,Is there a problem with my operation or a code error?

It's more like a bug.

**Comment by lvyaj** [comment]
> > So,Is there a problem with my operation or a code error?
> 
> It's more like a bug.
This problem has been modified by someone on the dev branch, how do I need to type jar packages?
