### ISSUE TITLE
The email alarm is configured but not sent

### ISSUE THREAD

**Issue by gaotong521** [apache/dolphinscheduler#16406]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After the email alarm instance is successfully configured, the alarm type is all, and the test can be sent normally. Then create an alarm group and specify email alarm instances. When the workflow is running, an alarm group is specified and an email is sent after the workflow is successfully executed. However, no email is sent after the workflow is successfully executed, and errors are reported in the background log
![2568debd2c34b3b15c27365f37f63cb](https://github.com/user-attachments/assets/62eacc99-e04b-4f58-9860-8953026ab498)
![2](https://github.com/user-attachments/assets/98f77aa6-c118-4b8c-9e9a-672e95dcf3fb)

### What you expected to happen

An email is expected to be sent after the workflow is successfully executed, but no email is sent after the workflow is successfully executed, and an error is reported in the background log

### How to reproduce

Configure an email alarm instance whose alarm type is all, add it to the alarm group, specify the alarm group in the workflow, run the workflow, and the problem occurs again

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaotong521** [comment]
[log.txt](https://github.com/user-attachments/files/16452658/log.txt)

**Comment by gaotong521** [comment]
Error log

**Comment by xxzuo** [comment]
#16275  already fix it
