### ISSUE TITLE
[Bug] [dolphinscheduler-api] dependent instance cannot  display  process、task info 

### ISSUE THREAD

**Issue by eelnomel** [apache/dolphinscheduler#16414]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![iwEdAqNwbmcDAQTRBLMF0QPGBrDt4_fqKjVHIQaWPHQj-90AB9MAAAAAkurehQgACaJpbQoAC9IAAZCW png_720x720q90](https://github.com/user-attachments/assets/301d471a-5ed4-44cf-8840-39a2e94c8424)
![iwEcAqNwbmcDAQTRBPgF0QOfBrBMQH-VwPTSXAaWPHQj-90BB9MAAAAAkurehQgACaJpbQoAC9IAAXIG png_720x720q90](https://github.com/user-attachments/assets/ed08d0e8-9873-45c7-ba4d-028a0915e4c8)
version 3.1.9

### What you expected to happen

process、task info can be displayed directly

### How to reproduce

This situation is not reproducible stably in version 3.1.9， maybe create a few more

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Kinsonx** [comment]
The same issue
https://github.com/apache/dolphinscheduler/issues/14865

**Comment by Kinsonx** [comment]
> The same issue #14865

fixed by https://github.com/apache/dolphinscheduler/pull/14868

**Comment by eelnomel** [comment]
I change the code in version 3.1.9, but still has the bug, 
i use maven package the ui jar, and change dolphinscheduler-ui-3.1.9.jar, restart api-server

**Comment by eelnomel** [comment]
> > 同样的问题 #14865
> 
> 由 #14868 修复

我改了代码，重新打包还是一样的问题，然后在生产环境替换了dolphinscheduler-ui-3.1.9.jar，还是没有解决

**Comment by Kinsonx** [comment]
> I change the code in version 3.1.9, but still has the bug, i use maven package the ui jar, and change dolphinscheduler-ui-3.1.9.jar, restart api-server

replacing dolphinscheduler-ui-3.1.9.jar is useless,
repackage dolphinscheduler-ui module,  then replace ./api-server/ui with dolphinscheduler-ui/dist

**Comment by Kinsonx** [comment]
修改代码，mvn clean package ui 模块， 在 dolphinscheduler-ui 下得到 dist 目录，重命名成ui，替换部署目录 api-server 下的 ui 目录即可（无需重启api-server）

> > > 同样的问题 #14865
> > 
> > 
> > 由 #14868 修复
> 
> 我改了代码，重新打包还是一样的问题，然后在生产环境替换了dolphinscheduler-ui-3.1.9.jar，还是没有解决

**Comment by SbloodyS** [comment]
Please using english to describe. Closing this issue for now.
