### ISSUE TITLE
[Improvement] Optimizing the OAuth2 login functionality to support users integrating with their own authentication centers.

### ISSUE THREAD

**Issue by hdygxsj** [apache/dolphinscheduler#16446]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Optimizing the OAuth2 login functionality to support users integrating with their own authentication centers.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by a3sroot** [comment]
Same problem, most self-built oauth2's take username or name fields. Login is rare. @SbloodyS

**Comment by ruanwenjun** [comment]
Could you please change this issue to DSIP, and provide detail design first.
Since this is a big refactor, we need to discuss first.

**Comment by SbloodyS** [comment]
Like @ruanwenjun said, you should create a `DSIP` fist, and provide full detail designs to discuss. 

I also have some doubts that have been answered in
https://github.com/apache/dolphinscheduler/pull/16465#pullrequestreview-2239410355

**Comment by hdygxsj** [comment]
This issue will be discussed further in #16472.
