### ISSUE TITLE
[Improvement][Workflow Timing] need for additional operators

### ISSUE THREAD

**Issue by sdhzwc** [apache/dolphinscheduler#16443]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://github.com/user-attachments/assets/2a9e9cba-ab98-4c6a-b307-71efd6f242bd)
Currently the timer management does not show who created the timer task, so without executing the task it is not known who created it, is it necessary to show the creator and modifier options?
cc @SbloodyS 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
That's great. I've assigned to you. @sdhzwc
