### ISSUE TITLE
[Bug] [base] Unable to disable postgresql deployment in cluster mode

### ISSUE THREAD

**Issue by a3sroot** [apache/dolphinscheduler#16452]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. Unable to disable postgresql deployment in cluster mode.
2. zookeeper The pull-up is too slow, causing all subsequent containers to go into reboot.

### What you expected to happen

dolphinscheduler/values.yaml 
[postgresql.enabled = false](enabled: false)

Still pulls up that mirror image.

### How to reproduce

rt

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You should check your network.

**Comment by a3sroot** [comment]
Deployment has nothing to do with the network, does it?
