### ISSUE TITLE
[Bug][UI] Fix logic_operator not passed to backend and not echoed in UI

### ISSUE THREAD

**Issue by newbiename** [apache/dolphinscheduler#16466]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The logic_operator parameter in the quality operator is not being correctly passed to the backend, nor is it properly echoed back in the UI. This issue affects the proper handling and display of the logical operators.

This is my first time contributing, and I am a beginner. Any guidance or feedback would be greatly appreciated.

### What you expected to happen

The system should correctly parse and process the logic_operator parameter to ensure that all relevant logical operators work properly.

### How to reproduce

Currently, the logic_operator parameter is not handled correctly, causing some functions to not work properly.

### Anything else

every time

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
What do you mean by `The logic_operator parameter in the quality operator`? I don't quite understand what this function is. @newbiename

**Comment by newbiename** [comment]
![image](https://github.com/user-attachments/assets/55482f29-f667-4d9f-a89c-236909f36766)
Hi @SbloodyS,

The  parameter is used to specify the logical operation (such as AND, OR) that should be applied within the quality operator in our system. It helps determine how different conditions are combined or evaluated.logic_operator

What it should do:

The  parameter is meant to define the logical relationship between conditions. For instance, if you have multiple conditions, the  determines whether they are combined using AND or OR.logic_operatorlogic_operator
Issue Details:

Currently, this parameter is not being correctly passed to the backend, which means the server-side logic may not be executed as expected.
Additionally, it’s not properly displayed in the UI, so users might not see the correct logical operations being applied.
Example:

If the  is set to "AND", the backend should process the conditions such that all conditions must be true for the overall logic to be true.logic_operator
If it’s set to "OR", then only one of the conditions needs to be true.
I hope this clarifies the issue. Please let me know if you need more details or if there are any specific parts of the code that you need help with.

**Comment by SbloodyS** [comment]
I see. The data-quality module is no longer maintained and will be deprecated in the future. @newbiename

**Comment by newbiename** [comment]
Hi @SbloodyS,

Thank you for the information. Given that the data-quality module is being deprecated, I wanted to confirm if my PR to fix this issue will be accepted or if there is a more appropriate alternative module where this issue should be addressed.

Should I proceed with submitting the PR for this module, or would it be more appropriate to close this issue and redirect my efforts to another module?

Thanks for your guidance!

Best regards,
newbiename

**Comment by SbloodyS** [comment]
Bug fix for data-quality module is welcome currently. I've assigned to you. Looking forward to your contribution. @newbiename
