### ISSUE TITLE
[Bug] [UI] Can't  SET Timing successful in Workflow Definition grid

### ISSUE THREAD

**Issue by topsli** [apache/dolphinscheduler#16475]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

On the workflow definition page, it is not possible to set a timer for two processes consecutively.

### What you expected to happen

On the workflow definition page, it is desired to be able to set a timer for two processes consecutively.

### How to reproduce

1. create two processes in Workflow Definition page
2. choose one process to set Timing, its successful
3. choose another process to set Timing, its failed. Response message like: schedule 42 does not exist.

Another method:
1.Open the page of  Workflow Definition, then choose two processes,  one of these have set Timing and another isn't set timing
![timing0](https://github.com/user-attachments/assets/f05487f4-a0fc-4f70-8253-37a25bc0291a)
2. Check the Timing of a process which have set timing
![timing1](https://github.com/user-attachments/assets/8e98b9d9-8e4b-42e3-acb5-662e0fd9769c)
3. Choose another process which no timing, try to set it's Timing. And then it response message: schedule 42 does not exist.
![timing2](https://github.com/user-attachments/assets/123e0472-d023-4b5d-bc50-ccee8725492b)

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I can not reproduce this issue locally. 

> schedule 42 does not exist.

From your error message, it seems that you manually deleted a certain timing data in the database, but did not delete it all.

**Comment by topsli** [comment]
Did you create the process Timing after open another process Timing first? Our customer find this issue, I have reproduce it every time.

**Comment by topsli** [comment]
![47AF0495-FF0C-4af9-BC66-0896EEB0529B](https://github.com/user-attachments/assets/a0b5e548-4c70-421e-b645-d2e3cc4f1550)

**Comment by topsli** [comment]
1. The first process had set its Timing
2. The second process haven't set its Timing
3. Open the first process Timing to view
4. To add the second process Timing,  try to save it,  you can get this issue.

**Comment by SbloodyS** [comment]
> 1. The first process had set its Timing
> 2. The second process haven't set its Timing
> 3. Open the first process Timing to view
> 4. To add the second process Timing,  try to save it,  you can get this issue.

I can reproduce this issue base on the steps you provided. Thanks for your clarification.
