### ISSUE TITLE
resource.storage.type: NONE worker start error

### ISSUE THREAD

**Issue by heartneo** [apache/dolphinscheduler#16483]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

version3.2.2 helm set conf common resource.storage.type: NONE
worker start error

### What you expected to happen

worker error
No qualifying bean of type 'org.apache.dolphinscheduler.plugin.storage.api.StorageOperator' available: expected at least 1

### How to reproduce

version3.2.2 helm set conf common resource.storage.type: NONE
worker start error

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You can refer to https://github.com/apache/dolphinscheduler/blob/225e969d2dd47f46d53d29cd4246752f2b175a33/dolphinscheduler-common/src/main/resources/common.properties#L24-L27

**Comment by heartneo** [comment]
thanks
