### ISSUE TITLE
[Improvement][Master] Optimize the dependent result for workflow dependency tasks

### ISSUE THREAD

**Issue by shouwangyw** [apache/dolphinscheduler#16487]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The reason is that within the maximum number of retries, the dependent task may start a new instance and run successfully.
If a failure result is returned directly, then the subsequent DAG of that dependent task node will not execute, and manual intervention in operations will be required

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I've assigned to you. Looking forward to your contribution. @shouwangyw
