### ISSUE TITLE
[ERROR] 2024-08-21 16:36:57.120 +0800 o.a.d.a.s.i.ResourcesServiceImpl:[496] - current user does not have permission

### ISSUE THREAD

**Issue by IplLL** [apache/dolphinscheduler#16499]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

我在文件管理里创建了文件夹，在点击文件夹后报错：[ERROR] 2024-08-21 16:36:57.120 +0800 o.a.d.a.s.i.ResourcesServiceImpl:[496] - current user does not have permission
![image](https://github.com/user-attachments/assets/0bc0dd86-7619-49c1-bddd-869ecaee4288)

### What you expected to happen

能够正常在文件夹里上传脚本文件

### How to reproduce

无

### Version

3.2.x

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by IplLL** [comment]
补充说明：
![image](https://github.com/user-attachments/assets/1765f804-1327-4066-996c-ea70646e4cc1)

**Comment by IplLL** [comment]
api-server日志：
![image](https://github.com/user-attachments/assets/a27f7479-2704-41eb-b87f-b186bd31ee2c)

**Comment by IplLL** [comment]
在文件管理根目录创建文件和文件夹都不会报错，但是在进入下一级文件夹，包括在下一级文件里上传，创建文件，都会报错：
![image](https://github.com/user-attachments/assets/8419df20-8043-4280-99ce-1b1f84b1a553)
上传的文件会自动的上传到根目录里面

**Comment by IplLL** [comment]
![image](https://github.com/user-attachments/assets/2687dcb6-c1a2-48d3-b9af-b1ab232e6619)
除了第一个是创建文件夹，后面的几个文件和文件夹都是在第一个子文件夹里创建的，会自动创建到根目录上

**Comment by SbloodyS** [comment]
Please use english to describe your issue.
