### ISSUE TITLE
FLINK_STREAM   sql-client.sh: command not found

### ISSUE THREAD

**Issue by visiontk** [apache/dolphinscheduler#16494]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

[INFO] 2024-08-21 08:49:28.925 +0800 - Success initialized task plugin instance success

[INFO] 2024-08-21 08:49:28.925 +0800 - Success set taskVarPool: null

[INFO] 2024-08-21 08:49:28.925 +0800 - flink task command : sql-client.sh -i /tmp/dolphinscheduler/exec/process/clickhouse/14536815297472/14590973130176_4/0/22080/0_22080_init.sql -f /tmp/dolphinscheduler/exec/process/clickhouse/14536815297472/14590973130176_4/0/22080/0_22080_node.sql

[INFO] 2024-08-21 08:49:28.926 +0800 - Begin to create command file:/tmp/dolphinscheduler/exec/process/clickhouse/14536815297472/14590973130176_4/0/22080/0_22080.command

[INFO] 2024-08-21 08:49:28.926 +0800 - Success create command file, command: #!/bin/bash

BASEDIR=$(cd `dirname $0`; pwd)

cd $BASEDIR

source /tmp/clickhouse/worker-server/conf/dolphinscheduler_env.sh

sql-client.sh -i /tmp/dolphinscheduler/exec/process/clickhouse/14536815297472/14590973130176_4/0/22080/0_22080_init.sql -f /tmp/dolphinscheduler/exec/process/clickhouse/14536815297472/14590973130176_4/0/22080/0_22080_node.sql

[INFO] 2024-08-21 08:49:28.931 +0800 - task run command: sudo -u clickhouse -i bash /tmp/dolphinscheduler/exec/process/clickhouse/14536815297472/14590973130176_4/0/22080/0_22080.command

[INFO] 2024-08-21 08:49:28.932 +0800 - process start, process id is: 411107

[INFO] 2024-08-21 08:49:28.967 +0800 - process has exited. execute path:/tmp/dolphinscheduler/exec/process/clickhouse/14536815297472/14590973130176_4/0/22080, processId:411107 ,exitStatusCode:127 ,processWaitForStatus:true ,processExitValue:127

[INFO] 2024-08-21 08:49:28.968 +0800 - Send task execute result to master, the current task status: TaskExecutionStatus{code=6, desc='failure'}

[INFO] 2024-08-21 08:49:28.969 +0800 - Remove the current task execute context from worker cache

[INFO] 2024-08-21 08:49:28.969 +0800 - The current execute mode isn't develop mode, will clear the task execute file: /tmp/dolphinscheduler/exec/process/clickhouse/14536815297472/14590973130176_4/0/22080

[INFO] 2024-08-21 08:49:28.970 +0800 - Success clear the task execute file: /tmp/dolphinscheduler/exec/process/clickhouse/14536815297472/14590973130176_4/0/22080

[INFO] 2024-08-21 08:49:29.933 +0800 -  -> /tmp/dolphinscheduler/exec/process/clickhouse/14536815297472/14590973130176_4/0/22080/0_22080.command: line 5: sql-client.sh: command not found

[INFO] 2024-08-21 08:49:29.934 +0800 - FINALIZE_SESSION

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
`Flink Stream` feature is deprecated and will be removed in the future.
