### ISSUE TITLE
[Doc][GUIDE] Changed some notes about python gateway service

### ISSUE THREAD

**Issue by BruceWong96** [apache/dolphinscheduler#16490]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Hi,
I found that the default value of python-gateway.enabled in the config file is false, which means it won't start with the server by default. So the description in the documentation is wrong.

[config of python-gateway](https://github.com/apache/dolphinscheduler/blob/dev/dolphinscheduler-api/src/main/resources/application.yaml#L145-L147)

And I found this note was missing from the Chinese documentation.

### Documentation Links

[en doc](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/guide/installation/standalone.md?plain=1#L37-L52)
[zh doc](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/zh/guide/installation/standalone.md?plain=1)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
> So the description in the documentation is wrong.

There is no description of this in the deployment documentation you listed. Where did you see the wrong description? @BruceWong96

**Comment by BruceWong96** [comment]
> > So the description in the documentation is wrong.
> 
> There is no description of this in the deployment documentation you listed. Where did you see the wrong description? @BruceWong96

<img width="1412" alt="image" src="https://github.com/user-attachments/assets/ae81ad4c-5cb7-4632-8ff0-18df90f22145">
It won't be started by default, because python-gateway.enabled is false by default.

**Comment by SbloodyS** [comment]
I see. Would you like to fix it? @BruceWong96

**Comment by BruceWong96** [comment]
> I see. Would you like to fix it? @BruceWong96

Yeah, I will submit a pr later.

Do Chinese documents need to add this note ? The Chinese document seems to have been missed.

**Comment by SbloodyS** [comment]
> Yeah, I will submit a pr later.
> 
> Do Chinese documents need to add this note ? The Chinese document seems to have been missed.

Yes. I've assigned to you. Looking forward to your contribution.

**Comment by BruceWong96** [comment]
> > Yeah, I will submit a pr later.
> > Do Chinese documents need to add this note ? The Chinese document seems to have been missed.
> 
> Yes. I've assigned to you. Looking forward to your contribution.

I just submitted a PR.  Please review it when you have time.
Thanks.
