### ISSUE TITLE
Suggestions for task flow configuration and dependencies(任务流配置和依赖的几点需求建议)

### ISSUE THREAD

**Issue by yyl861** [apache/dolphinscheduler#165]
1. Directed line connection between nodes in the task flow. It is expected to increase the execution of the next node according to the execution status of the previous node. The configuration rules are as follows:
- Success: The previous node succeeds, then the next point is executed;
- Failed: The previous node failed to execute, the next node executed, and if the previous node executed successfully, it will not execute.
- Failed skip: the previous node failed to execute, the next node is not executed, skipped directly
- Ignore: After the last node is executed, the next node is executed regardless of the final state.
2. Task flow definition In addition to the tree diagram, I hope to add a hierarchical structure diagram.
3. It is recommended to increase the project global parameters.
4. In the Dependent node configuration, add the dependent time setting, it is recommended to increase the self-configuring time period, for example, configurable to minutes. The time period strategy of the time can be selected as follows: 1. According to the timing time, 2: according to the current execution time of the task.

---
1.任务流中的 节点之间的 有向线条连接，希望可增加 根据上一个节点的 执行状态 判断下个节点执行策略的配置，配置规则为： 
-  成功 ：上一个节点成功，则下一个几点执行；
-  失败 ：上一个节点执行失败，下一个节点执行，如果上一个节点执行成功 ，则不执行
-失败跳过：上一个节点执行失败，下个节点不执行，直接跳过 
-忽略：上个节点执行后，不论最终状态，下个节点执行。 
2.任务流定义  除了树状图，希望增加 层级 结构图 
3.建议增加 项目全局参数
4.Dependent 节点配置中的添加依赖中 时 设置，建议增加自主配置时间段，例如可配置到分钟等。且时的时间段策略  可选择为：1.根据定时时间，2：依据任务当前执行时间。

**Comment by lidongdai** [comment]
thx!  we will split these ideas to detail feature,

"3.建议增加 项目全局参数"   please add detail description! 

"4.Dependent 节点配置中的添加依赖中 时 设置，建议增加自主配置时间段，例如可配置到分钟等。且时的时间段策略 可选择为：1.根据定时时间，2：依据任务当前执行时间。"   没看懂？加我微信:510570367

**Comment by davidzollo** [comment]
has implemented
