### ISSUE TITLE
[Bug] [dolphinscheduler-api] Subprocess The associated process is offline. Run the subprocess, and the process will run

### ISSUE THREAD

**Issue by lyyprean** [apache/dolphinscheduler#16500]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Subprocess The associated process is offline. Run the subprocess, and the process will run

### What you expected to happen

If the process associated with a subprocess is offline and the subprocess is run, the process will not run

### How to reproduce

After the subprocess goes online, the associated process changes from online to offline.

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
cc @ruanwenjun

**Comment by BrijeshPatra** [comment]
Summary:
The issue with the subprocess showing as offline has been addressed. The bug report #16500 indicated that the subprocess status was not properly checked, causing the error.

Solution:

Added a check for the process status to determine if it is OFFLINE.
Updated the error handling to ensure the process lineage is correctly managed when a subprocess is offline.
Verified the fix with relevant test cases.
Details:

Implemented the getStatus() method to return the process status.
Correctly handled the offline status to prevent the issue.
Next Steps:

Test the updated code to ensure that subprocesses are correctly managed.
Review any additional logs or cases related to process lineage.
![bug fix](https://github.com/user-attachments/assets/ea427f3d-c3da-4c2f-8fec-f46b3f792d31)

**Comment by lyyprean** [comment]
After the sub-process of periodic scheduling goes online, the associated process changes from online to offline, and the associated process is executed periodically

In this case, I think that the process associated with the subprocess cannot be executed. Is this a bug

**Comment by ruanwenjun** [comment]
I don't think this is a bug, the sub-process task is only used to trigger a workflow, it doesn't care about whether the sub workflow is online or offline.

**Comment by lyyprean** [comment]
ok
