### ISSUE TITLE
[ERROR] 2024-08-21 16:36:57.120 +0800 o.a.d.a.s.i.ResourcesServiceImpl:[496] - current user does not have permission

### ISSUE THREAD

**Issue by IplLL** [apache/dolphinscheduler#16502]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![1](https://github.com/user-attachments/assets/9e514a8c-bc0a-41bb-a127-8d333422041b)
![2](https://github.com/user-attachments/assets/400d5411-5f3f-4e72-939d-cf99db3736ff)
I created a folder named A in the file management, and when I entered the folder, I encountered an error: [ERROR] 2024-08-21 16:36:57.120+0800 o.a.d.a.s.i.ResourcesService Impl: [496] - current user does not have permission. Any operation to upload files or create a folder in the folder will result in an error similar to the one above. Assuming I create folder B in folder A, it can still be successfully created, but the created folder B will automatically be placed outside at the same level as folder A
![3](https://github.com/user-attachments/assets/3a084e48-f7fc-4401-8fe1-f5820f85864b)
![4](https://github.com/user-attachments/assets/3fe80a17-ff5b-4e09-b67d-202655ea64a7)
![5](https://github.com/user-attachments/assets/261b679a-6e97-49ed-939f-7d817250bba0)

### What you expected to happen

I hope to be able to create files and folders in folder A, which means that sub files can be created in the folder

### How to reproduce

nothing

### Version

3.2.x

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by IplLL** [comment]
![image](https://github.com/user-attachments/assets/06cf0664-a1ec-4146-95f0-de1efcdfccc5)
api-server/logs/dolphinsche-api.log message

**Comment by SbloodyS** [comment]
Which version and which resource type you are using? @IplLL

**Comment by IplLL** [comment]
> 您使用的是哪个版本和哪种资源类型？
HDFS. @SbloodyS 


![757c0fc2605c58f54652e521f3fec50](https://github.com/user-attachments/assets/b9ca2af4-c0e1-4b0e-a67c-3221b178b648)

**Comment by IplLL** [comment]
> 您使用的是哪个版本和哪种资源类型？@IplLL
@SbloodyS apache-dolphinscheduler-3.2.1-bin 
HDFS
