### ISSUE TITLE
[DSIP-68] Uniformly name process in code as workflow

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#16515]
### Search before asking

- [X] I had searched in the [DSIP](https://github.com/apache/dolphinscheduler/issues/14102) and found no similar DSIP.

### Motivation

Uniformly name process in code as workflow for better maintenance

1. First modify the backend code uniformly #16516
3. Then unify the table structure and table fields in backend #16525
4. Unify the backend controller and frontend ui sections #16525

### Design Detail

Incompatible changes
- Rename tables and fields from `process` to `workflow`. eg, from `t_ds_process_definition` to `t_ds_workflow_definition`.
- Rename api request/response params from `process` to `workflow`. eg, from `processDefinitionCode` to `WorkflowDefinitionCode`.

These incompatible changes may affect users of secondary development based on API and Database.

### Test Plan

Test it with ut, it, e2e, api-test

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Maybe we should find out whether another column name should change, related to this issue to avoid too many incompatible upgrades. checking ourselves or collecting from the community

**Comment by SbloodyS** [comment]
> Maybe we should find out whether another column name should change, related to this issue to avoid too many incompatible upgrades. checking ourselves or collecting from the community

Only the upgrade version will be affected.
