### ISSUE TITLE
The udf management function is disabled

### ISSUE THREAD

**Issue by gaotong521** [apache/dolphinscheduler#16521]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The new version removes the udf management feature, but it is required in hive type workflow definitions

### Use case

When creating hive SQL workflows, UDFs are required in many scenarios. Therefore, udf management functions are required

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This function is no longer maintained.
