### ISSUE TITLE
[Bug] [dolphinscheduler-task-api] can't getpid and bat unresponsive under Windows 

### ISSUE THREAD

**Issue by soxueren** [apache/dolphinscheduler#16530]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.unresponsive execution of bat in CMD.exe under window
2.the issue of not being able to obtain PID under the window

### What you expected to happen

can run python script under window10

### How to reproduce

run dolphinscheduler-worker.jar under window10 with envs:
SET JAVA_HOME=C:\Java\jdk1.8
SET PATH=%PATH%;%JAVA_HOME%\bin
SET METRICS_ENABLED=true
SET REGISTRY_ENDPOINTS=http://127.0.0.1:2379
SET REGISTRY_NAMESPACE=dolphinscheduler
SET REGISTRY_TYPE=etcd
SET PYTHON_LAUNCHER=python3
java -Xms4g -Xmx4g -Xmn2g -XX:+IgnoreUnrecognizedVMOptions -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:gc.log -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=dump.hprof -Duser.timezone=Asia/Shanghai -jar ./dolphinscheduler-worker-3.2.2.jar

### Anything else

run dolphinscheduler-worker.jar under window10

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
We don't support windows right now.
