### ISSUE TITLE
[Bug] [Module Name] I updated to 3.2.2 but every time I make up data for more than two days, it goes to rerun using the default user, can you fix this

### ISSUE THREAD

**Issue by WYPOWLS** [apache/dolphinscheduler#16554]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I deleted default tenant in tenant management, but it often appears when replenishing data, can this be fixed ？？？？？？？

### What you expected to happen

![image](https://github.com/user-attachments/assets/c
![image](https://github.com/user-attachments/assets/29dd1c42-7437-48e0-baa1-13074cf6151c)
854eff9-678b-45cb-a5e6-b4f29b64769e)

### How to reproduce

i don't konw

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by WYPOWLS** [comment]
![image](https://github.com/user-attachments/assets/da1e89c5-3263-439f-9d6b-8786ee66533a)
![image](https://github.com/user-attachments/assets/de1baad6-a1f4-4d2d-8da7-ffe1d69dbfa2)
I really don't get this. Why is this a problem?

**Comment by SbloodyS** [comment]
Already fixed in dev.

**Comment by WYPOWLS** [comment]
> 已在开发中修复。
 I updated to 3.2.2 but every time I make up data for more than two days, it goes to rerun using the default user, can you fix this
![image](https://github.com/user-attachments/assets/72c8375e-82f5-4b91-b299-1586a7e00a87)

**Comment by WYPOWLS** [comment]
I really don't know how to fix this
