### ISSUE TITLE
[Bug] [Worker] Worker alway BUSY after increase memory

### ISSUE THREAD

**Issue by 1032851561** [apache/dolphinscheduler#16559]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

版本：3.2.1，使用docker部署

1. 一开始worker给了4G内存（JAVA_OPTS=-server -Xms4g -Xmx4g -Xmn2g），运行一段时间后因内存保护一直不执行任务，日志以下：
`Worker node is BUSY: WorkerHeartBeat(startupTime=1725065068089, reportTime=1725065701918, cpuUsage=0.2319117335030766, jvmMemoryUsage=0.028848838806152344, memoryUsage=0.7248535082157362, diskUsage=0.0, serverStatus=BUSY, processId=8, host=172.26.22.7, port=1234, workerHostWeight=100, threadPoolUsage=0)`

2. 后来给到8G内存（JAVA_OPTS=-server -Xms8g -Xmx8g -Xmn4g），但是一重启还上马上报上面的错
3. 观察实际使用内存和dolphinschdueler显示不一致
![图片](https://github.com/user-attachments/assets/cd217fb1-cc3b-4b9a-b669-2533dfef8d09)
![图片](https://github.com/user-attachments/assets/319b6169-ebb2-47b0-b077-be98bf04801b)

### What you expected to happen

1. 增加了一倍内存，为什么memoryUsage的值不变（当前没任何任务在跑）
2. 系统内存使用率memoryUsage是不是基于整个jvm进程计算的？（我知道可以提高max-system-memory-usage-percentage-thresholds参数，但是现在的现象不合理）
3. 刚启动为什么就显示使用超过了0.7内存（一直持续）

### How to reproduce

版本：3.2.1

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please using english to describe.

**Comment by mingge1124** [comment]
I encountered the same error.How should I solve it?
