### ISSUE TITLE
[Doc] add node for doc of scrip alert  

### ISSUE THREAD

**Issue by wangxj3** [apache/dolphinscheduler#16555]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The official website contains multiple inaccuracies and location errors

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Gallardot** [comment]
closed by #16556
