### ISSUE TITLE
[Bug] [server] failed start stream task based on FLINK_STREAM task type

### ISSUE THREAD

**Issue by hanhanzhang** [apache/dolphinscheduler#16557]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

failed start flink stream task in dolphin-3.2.2 
![Uploading exception.jpg…]()

### What you expected to happen

Looked at the code, method of TaskPluginManager has been redefined to static methods, in earlier version is registered as a Spring bean into SpringContext, StreamTaskExecuteRunnable can get the object through SpringContext, SpringContext was not registered in 3.2.2, so StreamTaskExecuteRunable is unable to get the object through SpringContext.

### How to reproduce

In StreamTaskExecuteRunable, We can call TaskPluginManager method directly without having to retrieve the TaskPluginManager object from SpringContext.

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hanhanzhang** [comment]
![Uploading exception.jpg…]()

**Comment by hanhanzhang** [comment]
![Uploading image.png…]()

**Comment by hanhanzhang** [comment]
![Uploading exception.jpg…]()

**Comment by hanhanzhang** [comment]
error message: No qualifying bean of type "org.apache.dolphinscheduler.plugin.task.api.TaskPluginManager" available

**Comment by SbloodyS** [comment]
This function is deprecated and will be remove in the future release.

**Comment by hanhanzhang** [comment]
> This function is deprecated and will be remove in the future release.

StreamTaskExecuteRunnable will be removed?

**Comment by hanhanzhang** [comment]
> > This function is deprecated and will be remove in the future release.
> 
> StreamTaskExecuteRunnable will be removed?

How does community support flink stream task in future?

**Comment by SbloodyS** [comment]
> How does community support flink stream task in future?

There are no plans for now.

**Comment by hanhanzhang** [comment]
> > How does community support flink stream task in future?
> 
> There are no plans for now.

got，So the FLINK_STREAM task in 3.2.2 is actually not recommended?

**Comment by SbloodyS** [comment]
It's better to use other ways in production environment.

**Comment by hanhanzhang** [comment]
> It's better to use other ways in production environment.

Got，One more question: Does FLINK task type refer to flink batch task?
