### ISSUE TITLE
[Bug] Unable to delete copied nodes in unsaved workflow

### ISSUE THREAD

**Issue by Xuxiaotuan** [apache/dolphinscheduler#16567]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

If a node is copied in an existing workflow, it cannot be deleted without being saved

<img width="1091" alt="image" src="https://github.com/user-attachments/assets/4dce30a9-dc37-4033-9cf6-7513587dc715">

### What you expected to happen

Copy a workflow node

### How to reproduce

1. Create a workflow with nodes
2. Copy the node without saving it
3. Delete a node (cannot be deleted)

### Version

3.2.x

use  docker image: apache/dolphinscheduler-standalone-server:3.2.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This is a known issue. Both imported and copied workflow have the same problems.

**Comment by Xuxiaotuan** [comment]
i want to try fix

**Comment by SbloodyS** [comment]
I've assigned to you. Looking forward to your contribution.

**Comment by Xuxiaotuan** [comment]
1.  the back-end interface may report errors
2. When the back end returns normal, but returns an empty array, the front end cannot proceed to the next step

```
use-dependencies.ts:152 Uncaught (in promise) TypeError: res.filter is not a function
    at use-dependencies.ts:152:14
    at async getDependentTaskLinksByTask (use-dependencies.ts:149:7)
    at async handleDelete (dag-context-menu.tsx:150:19)
```
For example:
```js
await queryDependentTasks(projectCode, dependentTaskReq).then(
        (res: any) => {
          res
            .filter((item: any) => item.processDefinitionCode !== workflowCode)
            .forEach((item: any) => {
              dependentTaskLinks.push({
                text:
                  item.processDefinitionName + '->' + item.taskDefinitionName,
                show: true,
                action: () => {
                  const url = `/projects/${item.projectCode}/workflow/definitions/${item.processDefinitionCode}`
                  window.open(url, '_blank')
                }
              })
            })
        }
      )
```
Let me verify that again
