### ISSUE TITLE
[Bug] [API] The task instance log may be lost while fetching through api when the task is executed multiple times on different workers

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#16560]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The task instance log may be lost while fetching through api when the task is executed multiple times on different workers.

### What you expected to happen

Works fine.

### How to reproduce

aboved.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Each times, we execute a task, will generate a new task instance, so the log will not lost, unless sub workflow task pause/recover.
