### ISSUE TITLE
[Bug] Version 3.2.2 [Instance list paging is incorrect]

### ISSUE THREAD

**Issue by VanYue** [apache/dolphinscheduler#16562]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I discovered this pagination issue from 3.2.1 and upgraded to 3.2.2 today, but found that the problem has not been resolved. How should we handle it?

### What you expected to happen

解决实例列表无法分页问题

### How to reproduce

![微信图片_20240902161937](https://github.com/user-attachments/assets/794302bc-60c3-436b-98f0-c3ad534f1798)

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by VanYue** [comment]
Sorry! This Bug Fixed in 3.2.2

**Comment by Ashal** [comment]
3.2.2的bug还没有解决分页问题，所有的分页都失效了
