### ISSUE TITLE
[Bug] [dolphinscheduler-master]  Sometimes process instances cannot be generated

### ISSUE THREAD

**Issue by LiJie20190102** [apache/dolphinscheduler#16572]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I call the api('executors/start-process-instance') to generate process instances, sometimes I cannot generate them

### What you expected to happen

Every time I call 'executors/start process instance', I should be able to generate a process instance

### How to reproduce

1、ds version ：3.1.9
2、call 'executors/start process instance'

### Anything else

1、Can not generate logs when workflow instances are generated：
![image](https://github.com/user-attachments/assets/481bfa85-33aa-416c-954b-e1647decf601)

2、Can generate logs when workflow instances are generated：
api:
![image](https://github.com/user-attachments/assets/ba385ca6-cbc2-4993-93f8-3e81f5aff0d3)

master:
![image](https://github.com/user-attachments/assets/9bd0b67e-8003-4717-902a-0cd1e43f0eea)
![image](https://github.com/user-attachments/assets/63853e86-68d7-4d18-8e25-1c35b9c2bc7d)
![image](https://github.com/user-attachments/assets/db0c367e-7740-4bd4-a4f6-c788d593d0e5)

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This have been fixed in `dev`. Will be release in 3.3.0-release.

**Comment by LiJie20190102** [comment]
> This have been fixed in `dev`. Will be release in 3.3.0-release.

Can you tell me the PR

**Comment by SbloodyS** [comment]
> Can you tell me the PR

#16523

**Comment by LiJie20190102** [comment]
@SbloodyS Will version 3.1.9 fix this issue？

> This have been fixed in `dev`. Will be release in 3.3.0-release.
