### ISSUE TITLE
[Bug] [Api] WorkflowTaskLineage Param Passing Error

### ISSUE THREAD

**Issue by shangeyao** [apache/dolphinscheduler#16570]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

An error occurs when I attempt to create a workflow with a dependent node.
`Caused by: org.apache.ibatis.binding.BindingException: Parameter 'workflowTaskLineages' not found. Available parameters are [param1, processTaskLineages]`
Inconsistency in parameter names in the WorkflowTaskLineageMapper.

### What you expected to happen

None

### How to reproduce

None

### Anything else

None

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This will be fix in #16544
