### ISSUE TITLE
3.2.2 version, Missing files install_env.sh，but start-all.sh still using it

### ISSUE THREAD

**Issue by zdf321** [apache/dolphinscheduler#16571]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I configured everything and was ready to run start-all.sh to start the service, it reported that the file install_env.sh was not found

### What you expected to happen

Start the service normally

### How to reproduce

Execute the start-all.sh script to reproduce it!

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
`start-all.sh` and `stop-all.sh` will be removed in the 3.3.0-release
