### ISSUE TITLE
[Feature][alert] alert plugin HTTP cannot  adapt to the webhook of enterprise wechat at present.

### ISSUE THREAD

**Issue by ChiangHaosion** [apache/dolphinscheduler#16589]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The current webhook is essentially an HTTP POST request, but when ds parses and splices the body, it can't adapt to the requirements of WeChat. This can be converted in format. Enables ds to send alert via webhook api.
![image](https://github.com/user-attachments/assets/6066cced-bbd5-4c52-83de-e08b5ba683ce)

![image](https://github.com/user-attachments/assets/d3fb8afd-8547-4a81-97e1-56e1b3953238)

### Use case

Modify the setMsgInRequestBody method to adapt to the webhook request body parameters of enterprise WeChat.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Would you like to implement it? @ChiangHaosion

**Comment by ChiangHaosion** [comment]
Ok, please assign it to me.

**Comment by SbloodyS** [comment]
I've assigned to you. Looking forward to your contribution. @ChiangHaosion

**Comment by ChiangHaosion** [comment]
I am a newcomer.After fork the branch of dev, I saw the latest refactored http plugin. I found that it was not an elegant way to add calls to handle webhook api in http plugin. Although I have implemented it, it is just an emergency use within the personal company. The elegant way is to implement a webhook plugin. So, I searched and saw this Feature-14839, but it was PR last year, and there is no merge so far.   Finally, I'm sorry I can't contribute. thank you! @SbloodyS

**Comment by SbloodyS** [comment]
> I am a newcomer.After fork the branch of dev, I saw the latest refactored http plugin. I found that it was not an elegant way to add calls to handle webhook api in http plugin. Although I have implemented it, it is just an emergency use within the personal company. The elegant way is to implement a webhook plugin. So, I searched and saw this Feature-14839, but it was PR last year, and there is no merge so far. Finally, I'm sorry I can't contribute. thank you! @SbloodyS

It's okay. I've unassigned you now.

**Comment by SbloodyS** [comment]
Duplicated with #14839
