### ISSUE TITLE
I recommend combining timing and timing management, Display timed expressions in the workflow definition list

### ISSUE THREAD

**Issue by xingchun-chen** [apache/dolphinscheduler#1659]
1. In the current version, after adding a timer, you need to enter the timing management page to go online . 
2. The  timing expression for the online timing  that needs to be viewed again on the timing management page. If there are multiple timings, you need to enter the timing management page one by one. This is not intuitive

I recommend combining timing and timing management into one, and the workflow definition list shows timing expressions.

Do you have any comments or ideas to discuss!

1.当前版本，新增定时后，需要再次进入定时管理页面上线定时，操作比较繁琐
2.上线的定时表达式需要再次进入定时管理页面查看，如果有多个定时，每个都需要进入定时管理页面查看，感觉不是很直观。
 
我建议将定时和定时管理合并成一个，且工作流定义列表显示定时表达式。

大家有什么意见或想法都可以提出来探讨一下！

**Comment by dailidong** [comment]
very good, I have the same idea.  

@break60 can do this as xingchun said.

**Comment by break60** [comment]
This has been discussed with Xingchun earlier. Personally, I recommend clicking the timing management button to display the timing edit box, adding a run cancel timing button, and adding a crontab field to the list.


@qiaozhanwei&nbsp;Please confirm this function




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"dailidong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月1日(星期三) 晚上9:21
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"数码港"<790061044@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] I recommend combining timing and timing management, Display timed expressions in the workflow definition list (#1659)




very good, I have the same idea.
 
@break60 can do this as xingchun said.

**Comment by lenboo** [comment]
my suggestion:
1.  i think the timing button should be shown on every definitions, user can operate timing easily.
2. there should have online/offline function on the scheduler edit page.
3. the scheduler management button display on the process definition page independently, such as after the import/export buttons, or somewhere else.

**Comment by qiaozhanwei** [comment]
+1

**Comment by xingchun-chen** [comment]
1. In each workflow definition, show timing button when adding, show timing editing button when editing
2. Click the timing button to pop up a new timing pop-up box, save the timing and directly jump to the timing editing page, you can go online / offline, edit, delete. At the same time, the timing button on the workflow definition page becomes a timing edit button
3. Click the timer edit button to enter the timer edit page

**Comment by xingchun-chen** [comment]
![image](https://user-images.githubusercontent.com/55787491/71710438-34139900-2e37-11ea-97a9-c0d0c21b1d3e.png)

1. The timing management page only displays the "timing" information of all workflows that have "timing added" under "this item", adding a selection box before each row of data and adding a full selection in the header
2. Timing management page can search timing information according to "workflow name";
2. Only when the workflow status is online and the timing status is offline, can the batches be scheduled online.
3. Only when the workflow status is online or offline and the timing status is online, can the batch be scheduled offline.
4. The timing status is offline, so you can delete timings in batches.

1.定时管理页面只显示“该项目”下“已添加定时”的所有工作流的“定时”信息，每行数据前增加选择框，表头增加全选；
2.定时管理页面可以根据"工作流名称"搜索定时信息;
2.工作流状态是上线且定时状态为下线，才能批量定时上线；
3.工作流状态为上线或下线且定时状态为上线，才能批量定时下线；
4.定时状态为下线，才可批量删除定时。

**Comment by break60** [comment]
+1

**Comment by nauu** [comment]
+1

**Comment by elonlo** [comment]
+++++1

**Comment by Yeleights** [comment]
+1

**Comment by BoYiZhang** [comment]
+1

**Comment by xingchun-chen** [comment]
![image](https://user-images.githubusercontent.com/55787491/78096882-653b3f80-740d-11ea-953f-d4490e874087.png)
定时管理页面建议加上定时的“上线时间”/"下线时间"，清晰管理定时上线/下线记录
