### ISSUE TITLE
[DSIP-72][Dynamic Task] Suggest remove dynamic task type

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#16591]
### Search before asking

- [X] I had searched in the [DSIP](https://github.com/apache/dolphinscheduler/issues/14102) and found no similar DSIP.

### Motivation

The dynamic task type is currently supported in a user-configured manner. The user executes a while like loop to determine the exit condition. After the exit, specify multiple times of sub-workflows based on exit conditions.

The current task type has a lot of bugs, and I think the operation of executing multiple times of sub-workflows is not universal, and it is too customized for a certain business scenario. And at the same time, I search in the issue list found that only a single digit of users were using it.

So I suggest remove this dynamic task type.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
+1

**Comment by EricGao888** [comment]
+1

**Comment by zhongjiajie** [comment]
+1, and because of this issue try to remove an existing plugin for our product, and as I remember we do not remove anyone before. can we add some docs and guide someone who wants to remove other plugins? Such as we have to discuss in issue or mail thread, or we only remove plugin in major or minor version?

**Comment by SbloodyS** [comment]
> +1, and because of this issue try to remove an existing plugin for our product, and as I remember we do not remove anyone before. can we add some docs and guide someone who wants to remove other plugins? Such as we have to discuss in issue or mail thread, or we only remove plugin in major or minor version?

I think we should remove plugin only in major version.

**Comment by zhongjiajie** [comment]
> > +1, and because of this issue try to remove an existing plugin for our product, and as I remember we do not remove anyone before. can we add some docs and guide someone who wants to remove other plugins? Such as we have to discuss in issue or mail thread, or we only remove plugin in major or minor version?
> 
> I think we should remove plugin only in major version.

Agree with that, and we can add some deprecated notice for those task we remove in dev branch but still not released, WDYT

**Comment by SbloodyS** [comment]
> Agree with that, and we can add some deprecated notice for those task we remove in dev branch but still not released, WDYT

Yes, we've already add it to the docs in `https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/guide/upgrade/incompatible.md`

**Comment by ruanwenjun** [comment]
+1

**Comment by lenboo** [comment]
@SbloodyS 
Hi SbloodyS.
Can I understand that if a feature is found to have some bugs and has few users, then it can be removed?

**Comment by SbloodyS** [comment]
> @SbloodyS Hi SbloodyS. Can I understand that if a feature is found to have some bugs and has few users, then it can be removed?

I think no PMC/Committer is willing to continue to maintain, and at the same time, there are bugs that are not fixed and rarely used. Then we will remove it. The situation is similar to that of #16093.

**Comment by lenboo** [comment]
That means if someone is willing to fix these bugs and the fixes pass verification, then the feature can be retained and not removed.

**Comment by SbloodyS** [comment]
> That means if someone is willing to fix these bugs and the fixes pass verification, then the feature can be retained and not removed.

Yes.

**Comment by lenboo** [comment]
I will look for someone in the community who is willing to fix these bugs.
