### ISSUE TITLE
[Feature] Security Model

### ISSUE THREAD

**Issue by wangxj3** [apache/dolphinscheduler#16608]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add document to describes the Apache DolphinScheduler security model from the perspective of the user.  It is intended to help users understand the security model and make informed decisions about how to deploy and manage Apache DolphinScheduler. This document also describes the scope of security vulnerabilities for Apache DolphinScheduler. Developers are advised to read this article before reporting security vulnerabilities.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
Great job!
