### ISSUE TITLE
[Bug] [resources] minio can't find file path

### ISSUE THREAD

**Issue by ldboyghg** [apache/dolphinscheduler#16610]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/user-attachments/assets/ba66ee4c-d2b6-4bec-b17b-4864a1dd320c)
V3.19 ， minio作为文件资源存储中心，上传一个测试sh到minio， ds中shell组件调用的时候，报错找不到文件。

### What you expected to happen

看起来minio的 桶的名字  "dolphinscheduler " 没有拼接到ds 的文件下载目录里面。

### How to reproduce

看起来minio的 桶的名字  "dolphinscheduler " 没有拼接到ds 的文件下载目录里面。

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ldboyghg** [comment]
my config is error.

**Comment by wenchaoh997** [comment]
Hi @ldboyghg 我碰到了一样的问题，不知能否告诉我一下您最终是怎样修改配置的吗？感谢！
I meet same issue, could you give me some tips of your config? Many thanks!
