### ISSUE TITLE
[Improvement][Master] For logical tasks on the Master, there should be support for dry run

### ISSUE THREAD

**Issue by shouwangyw** [apache/dolphinscheduler#16612]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When I run the workflow and select 'Dry Run', other non-logic tasks will succeed directly, but the logic tasks will not succeed immediately
<img width="187" alt="image" src="https://github.com/user-attachments/assets/607f79fb-cc99-47a5-a06b-07611f59da48">

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please describe your issue in more detail

**Comment by shouwangyw** [comment]
> Please describe your issue in more detail
When I run the workflow and select 'Dry Run', other non-logic tasks will succeed directly, but the logic tasks will run normally and will not succeed immediately

**Comment by SbloodyS** [comment]
Which version you are using?

**Comment by shouwangyw** [comment]
> Which version you are using?

I am using version 3.1.3, but I see that the latest version does not support dry running for logic tasks either


In the latest version, dry runs are only effective for non-logical tasks submitted to the Worker
<img width="851" alt="image" src="https://github.com/user-attachments/assets/243d6b13-14a0-4938-846c-71efea952852">

**Comment by SbloodyS** [comment]
After checking it out, I found that this feature was missing in version 3, it was there in version 2. We will add it back in dev. Thanks for pointing out. @shouwangyw

**Comment by shouwangyw** [comment]
> After checking it out, I found that this feature was missing in version 3, it was there in version 2. We will add it back in dev. Thanks for pointing out. @shouwangyw

I attempted to solve this issue by submitting pr, please check it.

Recently, our project needs to support debugging DAGs in development mode, where logic tasks are skipped by default. Considering using a dry run is more suitable, hence we discovered this issue.
