### ISSUE TITLE
After creating a job of type FLINK-STREAM, there is currently no entry to start the job, which was previously started in the Task definition page, which now does not exist

### ISSUE THREAD

**Issue by gaotong521** [apache/dolphinscheduler#16618]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

创建入口:
![image](https://github.com/user-attachments/assets/fb0fcd87-0160-4df3-bc25-a160786cf2a0)
原启动入口：
![image](https://github.com/user-attachments/assets/4bf1049b-cb3c-4f4a-a799-abaafa386bd3)
现在页面：
![image](https://github.com/user-attachments/assets/a38b8b16-b09d-43b4-ba2b-93ee95f807b6)
缺少了该入口

### What you expected to happen

Page not found

### How to reproduce

Page not found

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This feature has been deprecated
