### ISSUE TITLE
[Bug]  3.2.2 version can't use complient data

### ISSUE THREAD

**Issue by renlixing** [apache/dolphinscheduler#16615]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I download a 3.2.2 version and test its function，including shell,python,switch and complient data.
I create a user and a tenant, I set rerun times 2. Structure like following.
<img width="1037" alt="Snipaste_2024-09-13_13-23-38" src="https://github.com/user-attachments/assets/9008895e-245e-4661-8e38-5ff875ce378e">
I use complient data like following.
<img width="904" alt="bs" src="https://github.com/user-attachments/assets/4c09bdfc-00a6-4627-aa0e-c494053c4f7c">
Obvisously I have set tenant instead of using "default"
Task Results  as follows.It ran successfully for the first date but failed for the next.
<img width="1064" alt="Snipaste_2024-09-13_13-23-10" src="https://github.com/user-attachments/assets/04e729f4-62a2-44f9-ad53-6aa48daf929c">
test_shell 's log as follows.
<img width="1053" alt="Snipaste_2024-09-13_13-21-35" src="https://github.com/user-attachments/assets/67dcf253-e57b-48b4-bc98-3c38bf406a70">

### What you expected to happen

I use version like 3.1.9 and it won't happen.Can anyone tell me what' wrong.I expect complient data can run successfully.

### How to reproduce

just do like what i show in pictures

### Anything else

none

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Fixed in #16092

**Comment by renlixing** [comment]
but there's not a file named workflowexecuterunnable.java in version3.2.2



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 13, 2024 14:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/dolphinscheduler] [Bug]  3.2.2 version can't usecomplient data (Issue #16615)




 
Closed #16615 as completed.

**Comment by SbloodyS** [comment]
Yes. This have been refactored in #16423

**Comment by renlixing** [comment]
sorry,it's too complex. can you tell me which flies i need to fix in detail.In blog you refer i didn't find info about complementData



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 13, 2024 15:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/dolphinscheduler] [Bug]  3.2.2 version can't usecomplient data (Issue #16615)




 
Yes. This have been refactored in #16423

**Comment by liuhai5516** [comment]
最后咋解决的啊 @renlixing

**Comment by renlixing** [comment]
换版本，我用的3.1.9



---Original---
From: ***@***.***&gt;
Date: Wed, Nov 6, 2024 12:28 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/dolphinscheduler] [Bug]  3.2.2 version can't usecomplient data (Issue #16615)




 
最后咋解决的啊 @renlixing

**Comment by liuhai5516** [comment]
> 换版本，我用的3.1.9
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Wed, Nov 6, 2024 12:28 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [apache/dolphinscheduler] [Bug] 3.2.2 version can't usecomplient data (Issue #16615) 最后咋解决的啊 @renlixing — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

多谢，多谢
