### ISSUE TITLE
[Bug] [Workflow Instance] Status display error

### ISSUE THREAD

**Issue by sdhzwc** [apache/dolphinscheduler#16629]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="806" alt="1" src="https://github.com/user-attachments/assets/6948091e-ac52-47e8-9b00-f399991085b9">
<img width="658" alt="2" src="https://github.com/user-attachments/assets/e03b3481-ec8c-42bd-a4e8-d0e020a3b3c8">

### What you expected to happen

Not displayed correctly

### How to reproduce

Look at the illustration above

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Would you like to fix it? @sdhzwc

**Comment by sdhzwc** [comment]
> 是否要修复它



> Would you like to fix it? @sdhzwc

yes
