### ISSUE TITLE
[Feature][dolphinscheduler ui] Add a default time interval to the workflow/task instance list in the project

### ISSUE THREAD

**Issue by iouAkira** [apache/dolphinscheduler#16626]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

项目里面工作流/任务实例列表对应数据库表单个项目内的任务实例超500W的时候，任务实例页面打开就超时，因为默认没有fillter  只有项目code，要做全量排序分页，接口请求都会超时，建议增加 默认的任务实例查询区间，例如：默认时间区间就是近一周，整体查询效率就会比较高

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please use english to describe.

**Comment by iouAkira** [comment]
😂原来dolphinscheduler 限制中文issue，没事啦，我自己本地调整编译解决自己需求啦
