### ISSUE TITLE
An error occurred while creating the alarm instance？

### ISSUE THREAD

**Issue by chenhuping** [apache/dolphinscheduler#16632]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

当我创建告警实例的时候发生了以下错误
![image](https://github.com/user-attachments/assets/f015ae26-8d20-43b0-b94e-0bee4b81c436)
![image](https://github.com/user-attachments/assets/161133eb-3cb6-422e-97b2-b0cee3693f49)

### What you expected to happen

Maybe my configuration was not filled out properly，Or you need additional plug-ins？

### How to reproduce

![image](https://github.com/user-attachments/assets/d9f5c655-0ac4-40af-8286-bdfb305cb517)

### Anything else

![image](https://github.com/user-attachments/assets/3c5da0b8-1abb-4d97-8c0c-3005a1ea4dbe)

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please using english to describe.

**Comment by chenhuping** [comment]
When I tried to create an alarm instance, an error occurred. I added an HTTP type alarm, configured the information, and when I clicked on the test, an error dialog popped up
![image](https://github.com/user-attachments/assets/e7d84213-4c45-4084-b324-9e0406f84628)

**Comment by chenhuping** [comment]
> When I tried to create an alarm instance, an error occurred. I added an HTTP type alarm, configured the information, and when I clicked on the test, an error dialog popped up
![image](https://github.com/user-attachments/assets/2f49ee0c-496e-470b-b8e1-394c83126afa)
