### ISSUE TITLE
[Bug] [plugin] Memory leakage occurs in k8s task

### ISSUE THREAD

**Issue by ChaoquanTao** [apache/dolphinscheduler#16650]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

`KubernetesApplicationManager` is used to hold the k8s client when k8s task is running, but the cache is only removed in `KubernetesApplicationManager#killApplication` method, which is invoked when k8s task is killed or throw an exception, or failover happens. But when k8s task is finished successfully, the method is not invoked, caused the cached is not removed.

### What you expected to happen

The cached should be removed when k8s task finished successfully

### How to reproduce

create and execute a k8s task, and periodically print the content of `KubernetesApplicationManager` in the meantime. When k8s task succeeded, the cache of this task still exists.

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @ChaoquanTao , would you like to fix it?

**Comment by ChaoquanTao** [comment]
I'd be happy to work on fixing it
