### ISSUE TITLE
[Question] [Worker] The sub workflow instance doesn't created#16651

### ISSUE THREAD

**Issue by LuxSun** [apache/dolphinscheduler#16671]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[Bug] [Worker] The sub workflow instance doesn't created #16651
<img width="978" alt="image" src="https://github.com/user-attachments/assets/c3fe592f-b30e-4ad8-a777-586a8adbcb05">

### What you expected to happen

找到具体的commit

### How to reproduce

找到具体的commit

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
We refactored all the logic of these in `dev`, not just in a single PR.

**Comment by LuxSun** [comment]
临时应急方案有吗，我看之前修过一次，但我们代码也是那次修复之后的代码。还是出现了。  3.2.1   能不能有啥应急措施。我们在生产环境  有点急~

> We refactored all the logic of these in `dev, not just in a single PR.

**Comment by SbloodyS** [comment]
Unfortunately not at present. We don't recommand using 3.2.x version in production environment.
