### ISSUE TITLE
[Bug] [Module Name] Bug title Complementary data issues

### ISSUE THREAD

**Issue by WYPOWLS** [apache/dolphinscheduler#16697]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I deleted the default user, but when patching data it still runs sudo -u default -i 
![image](https://github.com/user-attachments/assets/d9f9aabb-f311-4fd4-a661-7255dfeac51c)

### What you expected to happen

use 3.2.1 or 3.2.2 If you're using supplemental data, you're going to have this problem, and it's a little confusing whether the default user can't be deleted or not.

### How to reproduce

![image](https://github.com/user-attachments/assets/9a3f0d8c-19e5-4533-8022-0199eae03cd3)
![image](https://github.com/user-attachments/assets/bf8c08f3-ebd7-4c2a-b2f4-703c0cd1f19b)
It's an error if you want to use this function，Do not want any special settings, no need to set any environment variables, directly all with the default, link a mysql data source, create a task, the use of supplemental data is bound to appear this problem, without exception, upgrade to the latest is also the same!

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by WYPOWLS** [comment]
I need some help

**Comment by SbloodyS** [comment]
This issue have been fixed in `dev`

**Comment by WYPOWLS** [comment]
Please make it quick. Thank you.
