### ISSUE TITLE
Script execution, does not support ssh secret login

### ISSUE THREAD

**Issue by fanguanqun** [apache/dolphinscheduler#167]
echo 'send the file and push it to hdfs - start'
Scp etluser@172.168.27.32:/data/data/etl/user.txt /data/data/esc
echo 'acquires files and pushes them to hdfs - end'

The content of the script is as above, configured into the process, the server has been configured with a secret login, and the script can be executed manually. But the process runs, the log reports:
[INFO] 2019-04-26 11:36:42.146 cn.escheduler.server.worker.log.TaskLogger:[178] - [taskAppId=TASK_1_5_5] -> Collect files and push them to hdfs - start
Host key verification failed.
Capture files and push them to hdfs - end

---
echo  '采集文件并推送到hdfs - start'
scp etluser@172.168.27.32:/data/data/etl/user.txt /data/data/esc
echo  '采集文件并推送到hdfs - end'

脚本内容如上，配置到流程中，服务器已经配置免密登入，手工执行该脚本可以执行。但流程运行，日志报：
[INFO] 2019-04-26 11:36:42.146 cn.escheduler.server.worker.log.TaskLogger:[178] - [taskAppId=TASK_1_5_5]  -> 采集文件并推送到hdfs - start
	Host key verification failed.
	采集文件并推送到hdfs - end

**Comment by lidongdai** [comment]
是互相免密登录的么？
