### ISSUE TITLE
Adding the ssh source and clicking on the test connection can succeed, but then clicking on edit to test the connection fails, and it also fails when executing the task. This is the second bug raised about ssh.

### ISSUE THREAD

**Issue by FN20200222** [apache/dolphinscheduler#16709]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

添加ssh源，点击测试连接可以成功，但是再点击编辑测试连接就是失败的，并且执行任务的时候也是失败，这是有关于ssh提的第二个bug，版本3.2.2，使用docker搭建，docker run -d -p 12345:12345 -p 25333:25333 --name dolphinscheduler-standalone-server apache/dolphinscheduler-standalone-server:3.2.2
![0](https://github.com/user-attachments/assets/524af022-162e-45ae-9e8f-6097b7f3b678)
![1](https://github.com/user-attachments/assets/928f7ff8-ccf5-4b77-9acc-402e29d37cf3)

### What you expected to happen

添加ssh源，点击测试连接可以成功，但是再点击编辑测试连接就是失败的，并且执行任务的时候也是失败，这是有关于ssh提的第二个bug，版本3.2.2，使用docker搭建

### How to reproduce

添加ssh源，点击测试连接可以成功，但是再点击编辑测试连接就是失败的，并且执行任务的时候也是失败，这是有关于ssh提的第二个bug，版本3.2.2，使用docker搭建

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please using english to describe.

**Comment by FN20200222** [comment]
> Please using english to describe.

底下不是有自动翻译吗，还有你把我的issues关了干嘛
