### ISSUE TITLE
[Feature][task-api] Add cycle time types that depend on task types and improve the cycle time documentation to fully explain the meaning of each cycle time

### ISSUE THREAD

**Issue by fengjian1129** [apache/dolphinscheduler#16704]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The dependency cycle and frequency of the dependent task type are not very consistent with the actual dependency scenarios in data production. For example, multiple monthly scheduled tasks only need to rely on the task instance that was executed once in the previous month, but the existing functionality lacks this logic.
Similar problems as described above still exist in: last2Hours, last3Hours, last2Days, last3Days, thisMonth, lastMonth, thisw_week, etc. These `cycle time` are only suitable for day level scheduling that depends on hour level scheduling, month level scheduling that depends on day level scheduling, week level scheduling that depends on day level scheduling, etc. In other words, task dependencies of the same cycle type lack corresponding `cycle time`
This feature lacks documentation, which can easily lead to confusion among beginners regarding the selection of `cycle time`. Only by personally reading the source code can we understand the meaning of each `cycle time`
If possible, I can provide the code and complete the documentation

![image](https://github.com/user-attachments/assets/8e6e9916-694a-425d-93fd-08aa2164f7b9)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fengjian1129** [comment]
Is it necessary to turn the `cycle time` of dependent tasks in the same cycle into a variable that can be parsed, for example: taking 1 from last1date and performing the operation of date-1 directly, taking 1 from last1month and performing the operation of month-1 directly, and so on.Or should we only give a few fixed `cycle time`

**Comment by SbloodyS** [comment]
Duplicated with #16706
