### ISSUE TITLE
Adding the ssh source and clicking on the test connection can succeed, but then clicking on edit to test the connection fails, and it also fails when executing the task. This is the second bug raised about ssh, version 3.2.2, built using docker, docker run -d -p 12345:12345 -p 25333:25333 --name dolphinscheduler-standalone-server apache/dolphinscheduler-standalone-server:3.2.2

### ISSUE THREAD

**Issue by FN20200222** [apache/dolphinscheduler#16718]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Adding the ssh source and clicking on the test connection can succeed, but then clicking on edit to test the connection fails, and it also fails when executing the task. This is the second bug raised about ssh, version 3.2.2, built using docker, docker run -d -p 12345:12345 -p 25333:25333 --name dolphinscheduler-standalone-server apache/dolphinscheduler-standalone-server:3.2.2
![1](https://github.com/user-attachments/assets/484143a6-182f-47a9-9a13-7908b32e79a2)
![2](https://github.com/user-attachments/assets/04e8d61e-9e8f-4f31-8d03-8fe36499d887)

### What you expected to happen

Adding the ssh source and clicking on the test connection can succeed, but then clicking on edit to test the connection fails, and it also fails when executing the task. This is the second bug raised about ssh, version 3.2.2, built using docker, docker run -d -p 12345:12345 -p 25333:25333 --name dolphinscheduler-standalone-server apache/dolphinscheduler-standalone-server:3.2.2

### How to reproduce

Adding the ssh source and clicking on the test connection can succeed, but then clicking on edit to test the connection fails, and it also fails when executing the task. This is the second bug raised about ssh, version 3.2.2, built using docker, docker run -d -p 12345:12345 -p 25333:25333 --name dolphinscheduler-standalone-server apache/dolphinscheduler-standalone-server:3.2.2

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This issue have been fixed in `dev`
