### ISSUE TITLE
[Bug] [Module Name] ends a spark instance, and multiple instances unrelated to it are stopped.

### ISSUE THREAD

**Issue by super-02** [apache/dolphinscheduler#16719]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

我的spark程序称为程序1，中初始化了session，我使用了yarnclient并关闭，同时我还执行着别的spark程序称为程序2，当我运行了程序2并且没有运行完毕，且无bug，当我运行程序1的实例，程序1的状态一直为运行中，在cdh的yarn上面却已经结束了，当我点击实例的dolphin停止按钮，未完成的程序2也报错了，是报错Java。nio的错误，我记不清了，而且两个程序的状态同时变成失败。同时这个问题还有时候发生有时候不发生，我不知道其中发生了什么

### What you expected to happen

只停止当前实例

### How to reproduce

抱歉，我不知道

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please using english to describe.
