### ISSUE TITLE
[Question] [Stream] Streaming tasks don't work

### ISSUE THREAD

**Issue by maerman13** [apache/dolphinscheduler#16723]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

It's not possible to start streaming task. For example, Flink Streaming Task. After start there isn't any streaming task instance.

### What you expected to happen

There are some problem of execution streaming task at DolphinScheduler at backend.

### How to reproduce

Create workflow with Flink Streaming Task and start it.

### Anything else

1) Does DolphinScheduler support Streaming Tasks or it isn't implemented yet?
2) Is any workaround to start streaming task, for example for Seatunnel or Flink?
3) Does community have plans to develop new features for streaming at 2025 Roadmap? 

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
> Does DolphinScheduler support Streaming Tasks or it isn't implemented yet?

The support for flink streaming task is not very good for now.

> Is any workaround to start streaming task, for example for Seatunnel or Flink?

Using shell task.

> Does community have plans to develop new features for streaming at 2025 Roadmap?

There is no plans for now.
