### ISSUE TITLE
[Bug] [Official website] Error reported on the front-end page of the download page

### ISSUE THREAD

**Issue by ketingli1** [apache/dolphinscheduler#16721]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

官网下载二进制包页面 https://dolphinscheduler.apache.org/zh-cn/download/dev 报错：
![image](https://github.com/user-attachments/assets/4830e4c3-6431-4d12-bcbf-c41da809df55)

### What you expected to happen

不能下载二进制包

### How to reproduce

官网下载二进制包页面 https://dolphinscheduler.apache.org/zh-cn/download/dev 

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
We don't support download version `dev` package. Please using english to describe.
