### ISSUE TITLE
The remote shell task was successful, but the log shows a failure

### ISSUE THREAD

**Issue by FN20200222** [apache/dolphinscheduler#16729]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The remote shell task was successful, but the log shows a failure
![b](https://github.com/user-attachments/assets/5af0df24-9198-4482-b4c0-8c42e7c87611)
![b1](https://github.com/user-attachments/assets/3dc19031-4ab2-4480-8dc3-d89123188749)

### What you expected to happen

The remote shell task was successful, but the log shows a failure

### How to reproduce

The remote shell task was successful, but the log shows a failure

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FN20200222** [comment]
docker dolphinscheduler-standalone-server:3.2.2

**Comment by SbloodyS** [comment]
Duplicated.
