### ISSUE TITLE
docker dolphinscheduler-standalone-server:3.2.2 remoteshell Caused by: java.lang.NumberFormatException: For input string: "0

### ISSUE THREAD

**Issue by FN20200222** [apache/dolphinscheduler#16730]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![c](https://github.com/user-attachments/assets/d9bd1226-6b3d-4e03-b353-fd6015f46c0a)
![d](https://github.com/user-attachments/assets/eb23784d-7ebe-4940-b616-6d31ef81e66f)

### What you expected to happen

docker dolphinscheduler-standalone-server:3.2.2 remoteshell Caused by: java.lang.NumberFormatException: For input string: "0

### How to reproduce

docker dolphinscheduler-standalone-server:3.2.2 remoteshell Caused by: java.lang.NumberFormatException: For input string: "0

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Duplicated with #16295
