### ISSUE TITLE
[Bug] [TASK_K8S] Unable to select k8s namespace

### ISSUE THREAD

**Issue by youzif** [apache/dolphinscheduler#16745]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened
Hi bro.
When I want to use k8s as a workflow, I find that there is no namespace to choose from. Does this mean that I cannot choose which k8s cluster or namespace to run this task in?

The picture below is a screenshot of my ds
![image](https://github.com/user-attachments/assets/4c8816c5-1c6d-4a93-81c1-cf45c4f82971)

The picture below is a screenshot of the ds official document
![image](https://github.com/user-attachments/assets/8e05cce9-d42d-4bf8-8b22-ad7e1415817f)

and Here are some error reports for tasks:
![image](https://github.com/user-attachments/assets/9ce7c0e9-8d8a-4d89-bc44-ad52116f089e)

### Version

3.2.2

### Replenish
Cluster and namespace have been configured in DS
![image](https://github.com/user-attachments/assets/f7c65f11-a7e1-4e52-8c15-c1e1dde94a8c)
![image](https://github.com/user-attachments/assets/8e05cce9-d42d-4bf8-8b22-ad7e1415817f)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
PTAL, Thanks. @Gallardot

**Comment by e7868a** [comment]
I encountered the same issue while setting up a test environment with version 3.2.2. Initially, when I had not created any clusters or namespaces in DS, there was an option to select a namespace when creating a new workflow. However, after creating clusters and namespaces in DS, the namespace option disappeared when creating a new workflow.

**Comment by youzif** [comment]
> I encountered the same issue while setting up a test environment with version 3.2.2. Initially, when I had not created any clusters or namespaces in DS, there was an option to select a namespace when creating a new workflow. However, after creating clusters and namespaces in DS, the namespace option disappeared when creating a new workflow.

did you find any solution?

**Comment by youzif** [comment]
According to the task execution, in fact, the namespace is not obtained.
![image](https://github.com/user-attachments/assets/641b372a-9f5c-477d-b89b-3877df0dbea8)

![image](https://github.com/user-attachments/assets/63249ed0-26c6-4d01-9bb9-4e43b05635c6)

**Comment by youzif** [comment]
@Gallardot could  you provide some help？

**Comment by e7868a** [comment]
I discovered the reason in the code. To create a K8S-type task, you need to create a K8S-type data source within the "Datasource" section, rather than using the "K8S Namespace manage" option under "Security". However, in the UI code for version 3.2.2 (#16214), the K8S-type data source option has been removed, so it's not possible to create a K8S-type data source in this version.

**Comment by youzif** [comment]
> I discovered the reason in the code. To create a K8S-type task, you need to create a K8S-type data source within the "Datasource" section, rather than using the "K8S Namespace manage" option under "Security". However, in the UI code for version 3.2.2 (#16214), the K8S-type data source option has been removed, so it's not possible to create a K8S-type data source in this version.

I think you are right, looking forward to fixing this in the new version

**Comment by SbloodyS** [comment]
Fixed in `dev` branch.

**Comment by kawsyd** [comment]
Do you have a fixed binary package？

**Comment by kawsyd** [comment]
> 已修复 `dev` 分支。

Do you have a fixed binary package？
