### ISSUE TITLE
[Bug] [SeaTunnel-Task] can't append variables to seatunnel shell command

### ISSUE THREAD

**Issue by liunaijie** [apache/dolphinscheduler#16746]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In my seatunnel config, there has some variables need replace on run time by parameter.

<img width="513" alt="image" src="https://github.com/user-attachments/assets/77726665-5ddd-4036-8949-dce44a40c56a">

I defined the parameter in custom parameter setting.

<img width="586" alt="image" src="https://github.com/user-attachments/assets/28e9dafc-371b-4dc3-8017-aba1ed99578b">

But this parameter not append to the shell command.

```
SeaTunnel task command: /Users/jarvis/Downloads/apache-seatunnel-2.3.8/bin/seatunnel.sh --config /tmp/dolphinscheduler/exec/process/default/15454113618464/15454122106144_1/1/1/seatunnel_1_1.conf --deploy-mode local
```

I check the code, it can get the user defined parameter from localParameters

<img width="787" alt="image" src="https://github.com/user-attachments/assets/be168d41-663f-4f48-a122-4528d6c9eb2b">

So we need check if localParameters not empty, then append `-i key='value'` parameter to the shell command.

### What you expected to happen

fix seatunnel task submit issue

### How to reproduce

run a seatunnel task

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good job
