### ISSUE TITLE
Workflow edit delete button cannot be deleted

### ISSUE THREAD

**Issue by Sj-g** [apache/dolphinscheduler#16743]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

我采用的docker部署的伪分布式
如下图点击删除按钮，无反应
![image](https://github.com/user-attachments/assets/39f3b1f0-89bf-4c73-ae79-1497d52c2bcd)
api的服务能正常发送请求
![image](https://github.com/user-attachments/assets/836ec99c-33f8-4846-bebf-515fbebf5c5f)

### What you expected to happen

能正常删除流程图节点。

### How to reproduce

使用docker项目中docker部署方式可以复现

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please using english to describe.
