### ISSUE TITLE
[Bug] [Alarm Instance Manage] Does not change with language switching

### ISSUE THREAD

**Issue by sdhzwc** [apache/dolphinscheduler#16748]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/user-attachments/assets/ef413ba1-dd42-4261-b2f2-012a48722d1b)
![image](https://github.com/user-attachments/assets/a0bd6d53-3622-4195-af9c-a2d81888a550)
In Chinese and English modes, the prompts are the same
I see that the code is curing during registration, so I feel like it needs to be fixed

### What you expected to happen

Normal display

### How to reproduce

as shown above

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Duplicated with #16517
