### ISSUE TITLE
[Bug] [Module Name] Data flow definition Delete node button is invalid

### ISSUE THREAD

**Issue by Sj-g** [apache/dolphinscheduler#16744]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Use docker compose to deploy. After the deployment is complete, define the workflow. After the definition is complete, click Save. Then open the workflow definition editing interface again and click the Delete button. The Delete button does not respond.![image](https://github.com/user-attachments/assets/9a39389f-5197-4274-836e-806aaa17100f)
dolphinscheduler-api The log is as follows：
![image](https://github.com/user-attachments/assets/d456f968-905f-475a-b36e-d95e2b3527b5)
I don't know what caused it.

### What you expected to happen

Can delete nodes normally

### How to reproduce

Installed according to the official website documentation
DOLPHINSCHEDULER_VERSION=3.2.2
tar -zxf apache-dolphinscheduler-"${DOLPHINSCHEDULER_VERSION}"-src.tar.gz
docker compose --profile schema up -d
docker-compose --profile all up -d

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This issue have been fixed in `dev`
