### ISSUE TITLE
[Improvement][Deploy] Avoid overwrite gc log

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#16757]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We need to add time format at the gc log path, right now the gc log will be overwritten once the server startup.
https://github.com/apache/dolphinscheduler/blob/071994933b05850e7dd5f7bccbf45d867640e244/dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/bin/jvm_args_env.sh#L25

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by deng-jeffer** [comment]
I want to complete this Improvement，please assign this task to me

**Comment by aadvik93** [comment]
Hi, I'd like to work on this issue. Could you please assign it to me?

**Comment by ruanwenjun** [comment]
> I want to complete this Improvement，please assign this task to me

assigned.

**Comment by ruanwenjun** [comment]
@aadvik93 Hi, this issue has assigned, you can try https://github.com/apache/dolphinscheduler/issues/16758 if you are interested.

**Comment by aadvik93** [comment]
> @aadvik93 Hi, this issue has assigned, you can try #16758 if you are interested.

Thank you for assigning me this issue! I'll start working on it right away.
