### ISSUE TITLE
[Improvement][Deploy] Record the fatal error Log

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#16758]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

https://docs.oracle.com/en/java/javase/21/troubleshoot/location-fatal-error-log.html#GUID-2AE5EE08-A68F-4514-9618-A581C0EDFB1B

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhu3pang** [comment]
Please assign this to me.
