### ISSUE TITLE
[DSIP-80][Parameter Parser] Improvement the parameter parser

### ISSUE THREAD

**Issue by liunaijie** [apache/dolphinscheduler#16766]
### Search before asking

- [X] I had searched in the [DSIP](https://github.com/apache/dolphinscheduler/issues/14102) and found no similar DSIP.

### Motivation

Now we support 2 kinds of parameter definition.
1. System variable
use `${}`
2. Time related variable
use `$[]`, and in this variable we also support data calculate, like `$[add_months(yyyyMMdd,N)]`

But now we can't support the case that we need concat a fixed value with a dynamic value.
like  `/tmp/${system.workflow.instance.id}`

Do we need improve the parser to support more flexible definition.
like `/tmp/$[yyyy-MM-dd]/${system.workflow.instance.id}`

### Design Detail

![image](https://github.com/user-attachments/assets/4939958d-1774-4af5-8082-d6abb8cd7494)

refactor the current class, make each class's function clear
create 3 parser implemention
- InnerSystemParser  find the `${}` variable, and replace with parameterMap's value
- TimeParser    find the `$[]` variable, calculate and replace time related placeholder
- StringParser   find the `$<>` variable, and for loop to find other placeholder,  `${}`, `$[]`. replace the response with placeholder.

### Test Plan

Create new test and update/check exist test

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
cc @ruanwenjun @Radeity @Gallardot @caishunfeng @EricGao888

**Comment by SbloodyS** [comment]
> But now we can't support the case that we need concat a fixed value with a dynamic value.
like /tmp/${system.workflow.instance.id}

I think this is currently supported. Can you give an example?

**Comment by liunaijie** [comment]
> > But now we can't support the case that we need concat a fixed value with a dynamic value.
> > like /tmp/${system.workflow.instance.id}
> 
> I think this is currently supported. Can you give an example?

Sorry, My bad, I try to use `${/tmp/${system.workflow.instance.id}`  before, It not work.

When i use `/tmp/${system.workflow.instance.id}`, it's work
