### ISSUE TITLE
[Question][API] Is there a plan to develop and use the audit log module under the monitoring center module?

### ISSUE THREAD

**Issue by xiongbl526** [apache/dolphinscheduler#16760]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Is there a plan to develop and use the audit log module under the monitoring center module?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xiongbl526** [comment]
If there are plans to develop it, when is it expected to be launched?

**Comment by SbloodyS** [comment]
I don't quite understand what the audit log module is. Please describe your issue more clearly. @xiongbl526

**Comment by xiongbl526** [comment]
> I don't quite understand what the audit log module is. Please describe your issue more clearly. @xiongbl526
Under the Statistics module in the Management module, there is a section for Audit Logs.

**Comment by SbloodyS** [comment]
I still don't know it. Can you take a screenshot of it?

**Comment by ruanwenjun** [comment]
Has been finished by https://github.com/apache/dolphinscheduler/issues/15423
