### ISSUE TITLE
[Improvement][Parameter Parser] Improvement the parameter parser

### ISSUE THREAD

**Issue by liunaijie** [apache/dolphinscheduler#16765]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Now we support 2 kinds of parameter definition.
1. System variable
use `${}`
2. Time related variable
use `$[]`, and in this variable we also support data calculate, like `$[add_months(yyyyMMdd,N)]`

But now we can't support the case that we need concat a fixed value with a dynamic value.
like  `/tmp/${system.workflow.instance.id}`

Do we need improve the parser to support more flexible definition.
like `/tmp/$[yyyy-MM-dd]/${system.workflow.instance.id}`

I has write some simple code and test, the design is like this.

![image](https://github.com/user-attachments/assets/4939958d-1774-4af5-8082-d6abb8cd7494)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please create an DSIP first. @liunaijie

**Comment by liunaijie** [comment]
close as created DSIP https://github.com/apache/dolphinscheduler/issues/16766
