### ISSUE TITLE
[Improvement][UI] add project version to UI

### ISSUE THREAD

**Issue by liunaijie** [apache/dolphinscheduler#16778]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

From the UI, we can't get which version we are using.
But in Azkaban or Airflow, They can see the current version from UI.
<img width="170" alt="image" src="https://github.com/user-attachments/assets/90be085a-a8c8-403c-855c-71b16ed8d6cd">
<img width="515" alt="image" src="https://github.com/user-attachments/assets/d1e317cb-b501-4257-b6b8-a6235880b9ae">

We can generate version when maven package, replace version with real maven version. 
And copy this file to ui module, in some ui page , import this js file, and show the version.

Here are some screenshot about this.

Define a file with maven variable, it will be replace with real version when maven package
![image](https://github.com/user-attachments/assets/7a090a05-0b08-4934-81c5-ff23bb2258f6)

The replaced js file
![image](https://github.com/user-attachments/assets/f15b58fb-46dc-4cf1-a6ba-319239827e9e)

In some page, import this js file and show in ui (in my case , console print it)
![image](https://github.com/user-attachments/assets/63305155-624e-4ea3-8ef4-78ff9addebed)

<img width="626" alt="image" src="https://github.com/user-attachments/assets/2306710d-98ac-44f4-b7a7-51c140174b4f">

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This feature already exists. You can check `about` function.

**Comment by liunaijie** [comment]
Ok, I find the related pr, I find It add a backend api and ui call this api to get the version from db.

In my implemention, it's more easy. We don't need the backend api, the config js file is generate on maven package phase.

**Comment by SbloodyS** [comment]
> In my implemention, it's more easy. We don't need the backend api, the config js file is generate on maven package phase.

We don't need to refactor it for now since this function will hardly change and has no impact on users and developers.
