### ISSUE TITLE
Version 3.2.2 warning sends an error message via email

### ISSUE THREAD

**Issue by wenxuanzhen666** [apache/dolphinscheduler#16798]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After adding a warning instance to the warning group and configuring it, "Test Send" was successful and the email could be sent successfully. However, after selecting the created warning when starting the process, the email could not be received after the process was executed. The warning troubleshooting log found that an error was reported when sending the email.
![image](https://github.com/user-attachments/assets/dfcace0c-aaa6-41df-8924-b248b1a7c85d)

### What you expected to happen

The process has ended normally, but the alert email cannot be sent

### How to reproduce

The version used is 3.2.2, configured to use email for alerts, and then create a simple process instance that triggers both successful and failed rotations. After executing the process, problems may occur

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Fixed in `dev`.

**Comment by wenxuanzhen666** [comment]
> Fixed in `dev`.

How to fix this issue in version 3.2.2 ？

**Comment by SbloodyS** [comment]
> How to fix this issue in version 3.2.2 ？

You can task a look at this pr #16275
