### ISSUE TITLE
[Improvement][UI] use relative width for task editor

### ISSUE THREAD

**Issue by kevinjmh** [apache/dolphinscheduler#16802]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Current task editor style is fixed width: 600px, it is too narrow for wide screen.  Suggest to use relative width instead.

https://github.com/apache/dolphinscheduler/pull/16769

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
cc @Gallardot @zhongjiajie @ruanwenjun

**Comment by leeoo** [comment]
A good task editor UI with good UE should be like below.
![图片](https://github.com/user-attachments/assets/5baa15af-e67d-4400-82b0-d78aece06f7d)

**Comment by zhongjiajie** [comment]
idea sound good to me
