### ISSUE TITLE
[DSIP-][Alert Instance] Improvement alert plugin instance i18n Informational tips 

### ISSUE THREAD

**Issue by sdhzwc** [apache/dolphinscheduler#16815]
### Search before asking

- [X] I had searched in the [DSIP](https://github.com/apache/dolphinscheduler/issues/14102) and found no similar DSIP.

### Motivation

Further optimization of the issuse #16517 
The prompt information is currently hardcoded in the backend, and it needs to be moved to the frontend to avoid interaction with the database.
Backend hardcoding affects internationalization operations

### Design Detail

1、Configure all prompt information in the frontend ts and remove the related prompts from the backend
2、Backend set the placeholder field to the retrieved key
3、Front-end adjustment of the retrieval key

### Test Plan

Test by UT.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
> 1、Configure all prompt information in the frontend ts and remove the related prompts from the backend

The current backend creates a frontend alarm plugin in a low-code way, which is to decouple from the frontend. This way is to drive backwards, please don't do this.

**Comment by sdhzwc** [comment]
The removal here is just expressed by replacing hints with keys 
The front-end and back-end judgment methods are all hardcoded, which is not conducive to multilingual expansion
If more languages are introduced later, the enum AlertInputTips will become very bulky

**Comment by SbloodyS** [comment]
> The removal here is just expressed by replacing hints with keys The front-end and back-end judgment methods are all hardcoded, which is not conducive to multilingual expansion If more languages are introduced later, the enum AlertInputTips will become very bulky

We don't need to consider the support of other languages, English and Chinese are enough.
