### ISSUE TITLE
[Improvement][Alert Instance] Improvement alert plugin instance i18n  Informational tips

### ISSUE THREAD

**Issue by sdhzwc** [apache/dolphinscheduler#16812]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Further optimization of the issuse #16517 
The prompt information is currently hardcoded in the backend, and it needs to be moved to the frontend to avoid interaction with the database.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please create an DSIP first and provide full design details.
