### ISSUE TITLE
[bug] The time zone of ${yyyyMMddHHmmss} will change, sometimes UTC, sometimes CST, the server is the time zone of Asia/Shanghai

### ISSUE THREAD

**Issue by yueminghai** [apache/dolphinscheduler#16822]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/user-attachments/assets/89f38220-22c9-4778-a81e-64622bba9c14)
1120100000 执行输出${yyyyMMddHHmmss} 就是正常的Asia/Shanghai时区的时间。
![image](https://github.com/user-attachments/assets/4e129153-81bc-4a90-a902-f55f4c2f577e)

但是1120100200执行的时候就变了 
![image](https://github.com/user-attachments/assets/95e51e25-7dba-49e7-8f62-abfdf55d60ed)
变成UTC的时间了？ 这是为何？ 

### What you expected to happen

如何统一时区？ 定时任务执行的为什么会变化时区？ 

### How to reproduce

如上图

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
All your master have the same timezone?

**Comment by yueminghai** [comment]
是的，都是Asia/Shanghai
