### ISSUE TITLE
[Bug] [dolphinscheduler - master]switch task type Endless loop

### ISSUE THREAD

**Issue by trexguojc** [apache/dolphinscheduler#16827]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![20241120-162228](https://github.com/user-attachments/assets/b5265c86-b063-46a5-b393-5c656ac07b83)
When using the switch function, if the judgment condition is defalut, it will enter a dead loop, causing the task to get stuck, as shown in the log.

Next log: “Format condition sentence****” cannot be printed
**DS version：3.1.9**

### What you expected to happen

How to avoid this condition？

### How to reproduce

I have tried many times without reproducing this situation, but it does exist。

### Anything else

No response

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Fixed in `dev`.

**Comment by trexguojc** [comment]
> Fixed in `dev`.

I would like to consult with you, which code modification solved this problem? Is there a repair link available? I want to learn how to solve it.

**Comment by SbloodyS** [comment]
> I would like to consult with you, which code modification solved this problem? Is there a repair link available? I want to learn how to solve it.

We refactored the whole logic in #16327
