### ISSUE TITLE
[Bug] [Alert] AlertSendStatus doesn't make any sense.

### ISSUE THREAD

**Issue by toujours33** [apache/dolphinscheduler#16820]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After alert sent, the `AlertStatus` keep `PartialSuccess` whenever the alert behavior was.

`long failureCount = alertSendStatuses.stream()`
`     .map(alertSendStatus -> alertSendStatus.getSendStatus() == AlertStatus.EXECUTION_FAILURE)`
`     .count();`
`long successCount = alertSendStatuses.stream()`
`    .map(alertSendStatus -> alertSendStatus.getSendStatus() == AlertStatus.EXECUTION_SUCCESS)`
`    .count();`

failureCount or successCount are consistent for `map` function change `AlertSendStatus` stream to `Boolean` stream.

### What you expected to happen

The `failureCount` and `successCount` must count correctly

### How to reproduce

1. Configure a alert instance and alert group
2. Create a process
3. Trigger the process by set Notification Strategy with `All` and Alarm Group in 1st step 
4. Fetch records in table `t_ds_alert`, you can see `alert_status` column all in value 3, which means PartialSuccess.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
We should use filter here

**Comment by toujours33** [comment]
> We should use filter here

Yes, I will fix this issue, and will also consider adding some unit tests to cover this issue

**Comment by ruanwenjun** [comment]
> > We should use filter here
> 
> Yes, I will fix this issue, and will also consider adding some unit tests to cover this issue

Thanks, assigned to you, it's better to add integration test case for `AlertServer`, I create a new issue to track https://github.com/apache/dolphinscheduler/issues/16823
