### ISSUE TITLE
[Feature][Worker Group] Start worker node with worker group label

### ISSUE THREAD

**Issue by WhatAKitty** [apache/dolphinscheduler#16834]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Auto start worker with specific role such as 'xxxx-business' while the ds worker cluster is being overload.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Please provide more description, are you means bind the worker group by worker config? Right now, we can only set the worker group at ui, since we don't want to store this mapping in two places, so this worker group label has been removed from worker's config.

**Comment by SbloodyS** [comment]
I'll add this.
