### ISSUE TITLE
[Feature][Datasource] Added Caché database support

### ISSUE THREAD

**Issue by edclol** [apache/dolphinscheduler#16831]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We are currently working on a project that requires seamless integration with various databases for data access and processing. Among them, we intended to connect to Caché database to retrieve and work with its data. However, we have encountered persistent issues when attempting to establish a connection to the Caché database, which is severely hindering our progress.

### Use case

We expect to be able to successfully establish a connection to the Caché database . This will allow us to access and work with the data stored in the Caché database as needed for our project, enabling us to complete our tasks efficiently and on time.

### Related issues

We have searched through the existing issues in this project's repository and have not found any issues that are directly related to the problem we are currently experiencing with connecting to the Caché database. We believe this is a unique situation that requires specific attention and investigation.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please create an DSIP first. Just like #16818
