### ISSUE TITLE
[Bug] [Alert] Unable to serialize alert  pulgin parameters

### ISSUE THREAD

**Issue by hanhanzhang** [apache/dolphinscheduler#16841]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Two problems were occured（version-3.2.2）:
1. Use pg database: t_ds_listener_event's primary key column type is incorrect，failed insert
2. Plugin alarm instance: failed to deserialize plugin alarm parameters

### What you expected to happen

1. modify pg sql file，change t_ds_listener_event primary key column type
2.  structure of AlertPluginInstance#pluginInstanceParams is map, not list，so cant use PluginParamsTransfer#getPluginParamsMap

### How to reproduce

1.  append commands: 
- DROP SEQUENCE IF EXISTS t_ds_listener_event_id_sequence;
- CREATE SEQUENCE t_ds_listener_event_id_sequence;
- ALTER TABLE t_ds_listener_event ALTER COLUMN id SET DEFAULT NEXTVAL('t_ds_listener_event_id_sequence');
2. append method to deserialize parameters

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This have been fixed in `dev`.
