### ISSUE TITLE
[Bug] [API]In Security,User-manage When allocating resources to users, the resource list is empty

### ISSUE THREAD

**Issue by ediconss** [apache/dolphinscheduler#16840]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened
version: 3.2.2
When assign resources to users, the resource list is empty。
I found that two interfaces will be requested, but these two interfaces are not returned, and these two interfaces are not found in the code。
<img width="848" alt="image" src="https://github.com/user-attachments/assets/50e3c077-a027-4e60-a8a0-ec812e1828d6">

### What you expected to happen

list resource list

### How to reproduce

assign resources to users

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
These function is removed in the version 3.2.X. I'll remove it in the next release.

**Comment by ediconss** [comment]
> These function is removed in the version 3.2.X. I'll remove it in the next release.

OK, thanks

**Comment by SbloodyS** [comment]
Please don't close unfixed issue. It'll be close when completed.

**Comment by SbloodyS** [comment]
Fixed in `dev`.

**Comment by xujiang1** [comment]
why remove it in the next release. I think this is very useful.

**Comment by SbloodyS** [comment]
> why remove it in the next release. I think this is very useful.

You can take a look at #12076 for more info.
