### ISSUE TITLE
[Bug] [UI] the dolphischeduler-ui page error cause the ui-setting has been added

### ISSUE THREAD

**Issue by doc-laowu** [apache/dolphinscheduler#16853]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![ui-setting-error](https://github.com/user-attachments/assets/484651a6-fc29-4532-96c8-ee1a43c790e3)

### What you expected to happen

![image](https://github.com/user-attachments/assets/c16a8a56-f664-42fe-9e3f-ad22d00bcfdf)

### How to reproduce

This bug is inevitable on the dev branch

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Can you provide the reproducing steps? I can not reproduce it.

**Comment by ralopo** [comment]
I also had this problem when debugging locally in version 3.2.2

**Comment by ralopo** [comment]
![image](https://github.com/user-attachments/assets/c01403c3-d90c-4b52-a98b-8e845cd003a1)
When I changed the name attribute, the page worked

**Comment by ChikenBro** [comment]
> I also had this problem when debugging locally in version 3.2.2

+1

**Comment by SbloodyS** [comment]
Fixed in `dev`.

**Comment by devbiu** [comment]
In which commit of dev was this fixed? Now 3.2.2-release will have this problem when starting the UI. Thanks for your answer
