### ISSUE TITLE
Tenant issues

### ISSUE THREAD

**Issue by risennnnnb** [apache/dolphinscheduler#16868]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/user-attachments/assets/7c0aa9ea-c158-4329-a3d7-1229d1d6e3a1)
![image](https://github.com/user-attachments/assets/f36ee11f-fa9f-44c4-8e51-e7ca722742ee)
默认租户删除后工作流还是首选默认租户

### What you expected to happen

默认租户删除后工作流还是首选默认租户

### How to reproduce

默认租户删除后工作流还是首选默认租户

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Please using english to descirbe.

**Comment by risennnnnb** [comment]
After the default tenant is deleted, the default tenant will still be displayed on the page where the workflow is executed.

**Comment by SbloodyS** [comment]
Fixed in `dev`.

**Comment by Yinyuhang123** [comment]
> Fixed in `dev`.

which push please？
