### ISSUE TITLE
Pagination problem, unable to click next page

### ISSUE THREAD

**Issue by risennnnnb** [apache/dolphinscheduler#16866]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/user-attachments/assets/1f47ead9-508f-492d-9421-76f3844fb5f6)
分页灰置，无法点击

### What you expected to happen

分页灰置，无法点击

### How to reproduce

分页灰置，无法点击

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Fixed in dev. Please using english to describe.
