### ISSUE TITLE
[Improvement][uploadResource] RESOURCE_FULL_NAME_MAX_LENGTH limit is too short!

### ISSUE THREAD

**Issue by welsonzhang** [apache/dolphinscheduler#16897]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

`
public static final int RESOURCE_FULL_NAME_MAX_LENGTH = 128;  
`

**RESOURCE_FULL_NAME_MAX_LENGTH limit is too short!**

In scenarios where Hadoop is used as the file system, the base path already occupies a significant portion of the length. 

**Could this RESOURCE_FULL_NAME_MAX_LENGTH  limit be extended to 256?** 

For example, in our use case, the base path such as hdfs://cluster02/hive_warehouse/client.db/dolphinscheduler/root/resources/ already takes up more than half of the length, leaving very limited space for user-defined content.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Which version are you using? @welsonzhang

**Comment by welsonzhang** [comment]
apache-dolphinscheduler-3.2.2-bin

**Comment by welsonzhang** [comment]
[ERROR] 2024-12-16 11:40:46.315 +0800 o.a.d.a.s.i.ResourcesServiceImpl:[197] - Resource file's name is longer than max full name length, fullName:batch_train_local.yaml, fullNameSize:130, maxFullNameSize:128

**Comment by SbloodyS** [comment]
This have been fixed in `dev`.

**Comment by welsonzhang** [comment]
how to use dev?

**Comment by SbloodyS** [comment]
`dev` is a branch of development. It hasn't been released yet. Not recommended for use in a production environment.
