### ISSUE TITLE
[Bug] [dolphinscheduler-master] Master logic task kill operation will never take effect. Although the TaskInstance state is set to KILL, the logic task will actually continue running in memory.

### ISSUE THREAD

**Issue by tasier** [apache/dolphinscheduler#16895]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Although the kill master logic task operation is successful, the TaskInstance state is set to KILL, and there are no exceptions in the KILL operation, the logic task is actually still running and has not been truly killed.

### What you expected to happen

Kill the master logic operation is successful and the logic task does not run again at the same time.

### step 1 create a logic task

- Create a logic task such as a DEPENDENT task. The task content which is not important can be anything else. Following image is the task definition.
<img width="597" alt="image" src="https://github.com/user-attachments/assets/49ce3b30-c2a8-49f4-b2b7-05c852b4680f" />

### step 2 save and online the workflow definition

- Save the workflow definition.  After publishing the workflow definition, make the scheduler online. At last, manual start the workflow.
<img width="2480" alt="image" src="https://github.com/user-attachments/assets/10c64804-085a-43f5-b3a2-8c0a920d631b" />

### step3 stop the workflow

- After the workflow is running, stop the workflow.

<img width="2500" alt="image" src="https://github.com/user-attachments/assets/464ba393-17d3-42f2-99fa-a02308e6c7b4" />
<img width="2215" alt="image" src="https://github.com/user-attachments/assets/dc479621-d49b-4924-9769-a0e08fcaa286" />

### step4 logic task is still running

- Make a debug breakpoint at method org.apache.dolphinscheduler.server.master.runner.execute.AsyncMasterTaskDelayQueue#pollAsyncTask.
- We can see that asyncTaskCheckDelayQueue still contains the stopped task. It will be running forever unless we redeploy the Dolphin-master service.

<img width="2503" alt="image" src="https://github.com/user-attachments/assets/3495a5e1-ac71-4a4b-9627-defe24327955" />

### Version

 3.2.2-release 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Fixed in `dev`.
