### ISSUE TITLE
[Bug] [task api] stop spark job on yarn failed

### ISSUE THREAD

**Issue by lbrowny** [apache/dolphinscheduler#16906]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I try to stop spark job on yarn but failed.
Logs show that kill yarn application failed with ExitCodeException.  The exit code is 137. Thouth dolphin task instance is set to terminated, spark job is still running.
I then set dolphinscheduler to develop mode, reserve the .kill file and execute command 'sh /xxx/xxx/xxx.kill' manually with user dolphinscheduler. It works, spark job is terminated as expected. 
Is there any difference between dolphinscheduler and execute .kill file manually?
there's logs: 
![dolpin_log1](https://github.com/user-attachments/assets/6d3b8fb7-279d-4fc2-8c3b-99f105b61982)
![dolpin_log2](https://github.com/user-attachments/assets/aaeea854-de2b-40d8-9b08-4ca08d22aa95)

### What you expected to happen

dolphinscheduler terminate spark job successfully.  

### How to reproduce

Any attemp to stop spark job failed  in my env. 
I don't know what env config should I provide to help solve the problem. 

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
The only one different is the `.kill` file will be executed by tenant, please check if the tenant has permission to execute the file

**Comment by lbrowny** [comment]
> The only one different is the `.kill` file will be executed by tenant, please check if the tenant has permission to execute the file

Yes. 
Through the permission of the file is not 755, execute .kill file by user tenantName1,  the output indicates tenantName1 has permission to execute the file.
![1734663128577](https://github.com/user-attachments/assets/82ca9d98-6016-40d5-bb4b-9ebb3b1b7d12)

**Comment by ruanwenjun** [comment]
> > The only one different is the `.kill` file will be executed by tenant, please check if the tenant has permission to execute the file
> 
> Yes. Through the permission of the file is not 755, execute .kill file by user tenantName1, the output indicates tenantName1 has permission to execute the file. ![1734663128577](https://private-user-images.githubusercontent.com/24472111/397603831-82ca9d98-6016-40d5-bb4b-9ebb3b1b7d12.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODQyMTcsIm5iZiI6MTczNDY4MzkxNywicGF0aCI6Ii8yNDQ3MjExMS8zOTc2MDM4MzEtODJjYTlkOTgtNjAxNi00MGQ1LWJiNGItOWViYjNiMWI3ZDEyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA4MzgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMDgyNmU0MDhkNWZiZTc4NzBiZmQ0ZGE1YzZjMGVkYjQxMzAyYjA2N2U1MWIzNTVjYTliNjBlNTMzYzczMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Jy5pvr9OqRXR4aJ8zJ9jQncPTpCEFUa-aQey-5uSGps)

@lbrowny I submit #16909 to fix this problem.

**Comment by lbrowny** [comment]
> > > The only one different is the `.kill` file will be executed by tenant, please check if the tenant has permission to execute the file
> > 
> > 
> > Yes. Through the permission of the file is not 755, execute .kill file by user tenantName1, the output indicates tenantName1 has permission to execute the file. ![1734663128577](https://private-user-images.githubusercontent.com/24472111/397603831-82ca9d98-6016-40d5-bb4b-9ebb3b1b7d12.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODQyMTcsIm5iZiI6MTczNDY4MzkxNywicGF0aCI6Ii8yNDQ3MjExMS8zOTc2MDM4MzEtODJjYTlkOTgtNjAxNi00MGQ1LWJiNGItOWViYjNiMWI3ZDEyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA4MzgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMDgyNmU0MDhkNWZiZTc4NzBiZmQ0ZGE1YzZjMGVkYjQxMzAyYjA2N2U1MWIzNTVjYTliNjBlNTMzYzczMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Jy5pvr9OqRXR4aJ8zJ9jQncPTpCEFUa-aQey-5uSGps)
> 
> @lbrowny I submit #16909 to fix this problem.

Sorry for spelling 'Through', I mean though `.kill` file without x permission, the file can be successfully executed using `sh` command.
I also tried to make `.kill` file myself, chmod it to 777 , and then stop the task instance. 
In this way, org.apache.dolphinscheduler.plugin.task.api.am.YarnApplicationManager#execYarnKillCommand could use the  exists `.kill` file with `rwx` permission, but still failed to stop spak job with the exactly same output. It seems nothing to do with the permission of the `.kill` file.
I notice that similar issues with ExitCodeException usually have additional infomation about fail reason, but showed nothing in my case. Is it because of exit code? 137 means shell execution was interrupted‌.

**Comment by ruanwenjun** [comment]
@lbrowny Please check the Linux log, is the kill process has been killed by system?

**Comment by lbrowny** [comment]
> @lbrowny Please check the Linux log, is the kill process has been killed by system?

I checked Linux log this afternoon, and found that it didn't contain any record related to killing processes. 
I will recheck the logs to ensure that there are no omissions from the previous check.
Have a nice weekend~: )

**Comment by ruanwenjun** [comment]
@lbrowny And please check if the bootstrap user has the permission to use `sudo -u`.

**Comment by lbrowny** [comment]
> @lbrowny And please check if the bootstrap user has the permission to use `sudo -u`.

There is no record of the process being killed in the system logs.

The user has the permission to use `sudo -u`.
Outputs are as follows: 
```
[root@xxx logs]# su - dolphinscheduler
Last login: Mon Dec 23 17:06:02 CST 2024 on pts/0
-bash-4.2$ sudo -u tenantName1 sh /tmp/dolphinscheduler/exec/process/tenantName1/14481755113696/16064940440032_1/2853/3286/application_1734659792626_0039.kill
24/12/23 17:08:55 INFO impl.TimelineReaderClientImpl: Initialized TimelineReader URI=http://host/ws/v2/timeline/, clusterId=yarn_cluster
24/12/23 17:08:55 INFO client.DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at hzspark32/192.168.110.32:8050
24/12/23 17:08:55 INFO client.AHSProxy: Connecting to Application History server at host
Application application_1734659792626_0039 has already finished 
```

**Comment by lbrowny** [comment]
@ruanwenjun 
I may have found the reason.

While debugging using Arthas, I encountered the following error output: `Cannot execute /usr/hdp/current/hadoop/libexec/yarn-config.sh.`

It appears that executing the command `sh /tmp/dolphinscheduler/exec/process/tenantName1/14481755113696/16066089682784_1/2862/3313/application_1734659792626_0066.kill` depends on an additional file `/usr/hdp/current/hadoop/libexec/yarn-config.sh`, which does not exist on the system.

```
method=org.apache.dolphinscheduler.common.shell.AbstractShell.runCommand location=AtExceptionExit
ts=2024-12-23 17:40:32.066; [cost=21.092938ms] result=@ArrayList[
    @Object[][isEmpty=true;size=0],
    @ShellExecutor[
        command=@String[][isEmpty=false;size=2],
        output=@StringBuffer[ERROR: Cannot execute /usr/hdp/current/hadoop/libexec/yarn-config.sh.
],
        log=@Logger[Logger[org.apache.dolphinscheduler.common.shell.AbstractShell]],
        timeOutInterval=@Long[0],
        timedOut=@AtomicBoolean[false],
        interval=@Long[0],
        lastTime=@Long[1734946832064],
        environment=null,
        dir=null,
        process=@UNIXProcess[java.lang.UNIXProcess@2caa5a9f],
        exitCode=@Integer[1],
        completed=@AtomicBoolean[true],
    ],
    @String[][
        @String[sh],
        @String[/tmp/dolphinscheduler/exec/process/tenantName1/14481755113696/16066089682784_1/2862/3313/application_1734659792626_0066.kill],
    ],
    org.apache.dolphinscheduler.common.shell.AbstractShell$ExitCodeException: 
```

**Comment by ruanwenjun** [comment]
> @ruanwenjun I may have found the reason.
> 
> While debugging using Arthas, I encountered the following error output: `Cannot execute /usr/hdp/current/hadoop/libexec/yarn-config.sh.`
> 
> It appears that executing the command `sh /tmp/dolphinscheduler/exec/process/tenantName1/14481755113696/16066089682784_1/2862/3313/application_1734659792626_0066.kill` depends on an additional file `/usr/hdp/current/hadoop/libexec/yarn-config.sh`, which does not exist on the system.
> 
> ```
> method=org.apache.dolphinscheduler.common.shell.AbstractShell.runCommand location=AtExceptionExit
> ts=2024-12-23 17:40:32.066; [cost=21.092938ms] result=@ArrayList[
>     @Object[][isEmpty=true;size=0],
>     @ShellExecutor[
>         command=@String[][isEmpty=false;size=2],
>         output=@StringBuffer[ERROR: Cannot execute /usr/hdp/current/hadoop/libexec/yarn-config.sh.
> ],
>         log=@Logger[Logger[org.apache.dolphinscheduler.common.shell.AbstractShell]],
>         timeOutInterval=@Long[0],
>         timedOut=@AtomicBoolean[false],
>         interval=@Long[0],
>         lastTime=@Long[1734946832064],
>         environment=null,
>         dir=null,
>         process=@UNIXProcess[java.lang.UNIXProcess@2caa5a9f],
>         exitCode=@Integer[1],
>         completed=@AtomicBoolean[true],
>     ],
>     @String[][
>         @String[sh],
>         @String[/tmp/dolphinscheduler/exec/process/tenantName1/14481755113696/16066089682784_1/2862/3313/application_1734659792626_0066.kill],
>     ],
>     org.apache.dolphinscheduler.common.shell.AbstractShell$ExitCodeException: 
> ```

But you said when you manual execute the xx.kill, there is no error?

**Comment by lbrowny** [comment]
> But you said when you manual execute the xx.kill, there is no error?


I executed the xx.kill file manually with no error, without executing /usr/hdp/current/hadoop/libexec/yarn-config.sh.
The `.kill` file only cd to a directory and yarn application -kill applicationId.
The root cause for `Cannot execute /usr/hdp/current/hadoop/libexec/yarn-config.sh` is error config of the `haddoop_home` variable in my environment. I fixed it and then the stop job function works perfectly.
The `yarn-config.sh` contains various environment variables. Is it necessary for dolphinscheduler to stop a Spark job?

**Comment by ruanwenjun** [comment]
> > But you said when you manual execute the xx.kill, there is no error?
> 
> I executed the xx.kill file manually with no error, without executing /usr/hdp/current/hadoop/libexec/yarn-config.sh. The `.kill` file only cd to a directory and yarn application -kill applicationId. The root cause for `Cannot execute /usr/hdp/current/hadoop/libexec/yarn-config.sh` is error config of the `haddoop_home` variable in my environment. I fixed it and then the stop job function works perfectly. The `yarn-config.sh` contains various environment variables. Is it necessary for dolphinscheduler to stop a Spark job?

This is strange, ds will not lode this file `yarn-config.sh`, is this file is in `dolphinscheduler_env.sh`?
