### ISSUE TITLE
[Bug] [Workflow] Workflow recover from pause will cause workflow fail and state unexpected 

### ISSUE THREAD

**Issue by toujours33** [apache/dolphinscheduler#16937]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Dolphinscheduler with env:
1. DS 3.2.2
2. Mysql Datasource with mysql server 8.0.18
3. Mysql connector java 8.0.33

When i create a workflow with multi tasks, pause task while middle task running, and waiting for pause happen, then trigger recover from suspend, the workflow state will change to SUCCESS, but task state not finished.

Error log
```
[ERROR] 2024-12-31 10:54:12.259 +0800 [WorkflowExecuteThread-10] org.apache.dolphinscheduler.service.process.ProcessServiceImpl:[1082] - [WorkflowInstance-0][TaskInstance-0] - Save taskInstance to db error, task name:shell-3, process id:11 state: WorkflowExecutionStatus{code=1, desc='running'} 
[ERROR] 2024-12-31 10:54:12.320 +0800 [WorkflowExecuteThread-10] org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[911] - [WorkflowInstance-0][TaskInstance-0] - Submit standby task: shell-3 failed
```

### What you expected to happen

The workflow recover from suspend should trigger task running and change to RUNNING state.

### How to reproduce

1. Dolphinscheduler with env:
* DS 3.2.2
* Mysql Datasource with mysql server 8.0.18
* Mysql connector java 8.0.33
2. Create Workflow:
shell-0: echo "shell-0"
shell-1: sleep 1m
shell-2: sleep 1m
shell0 <- shell-1 <- shell 2 (  A <-  B means B depend on A)
3. trigger workflow online & trigger workflow run
4. after shell-0 finished and shell-1 is running, trigger workflow instance pause
5. waiting for workflow instance change to paused
6. trigger workflow instance recover from suspend

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Fixed in `dev`.
