### ISSUE TITLE
The installation documentation is very unfriendly

### ISSUE THREAD

**Issue by charlessws** [apache/dolphinscheduler#16931]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

对于想试用的新人来说，安装文档非常不友好，特别是对于ubuntu环境不熟悉的人来说，简直处处是坑。我按照https://dolphinscheduler.apache.org/zh-cn/docs/3.1.5/guide/installation/pseudo-cluster说明文档进行安装，发现几乎每1-2步都会遇到问题，在一步一步询问chatgpt 4o的情况下艰难求索，已经2天了，才进行到三分之二。我承认自己是ubuntu小白，为了安装试验项目临时学了一些ubuntu命令，但是对于想推动社区发展的广大用户来说，文档的重要性远远超过项目本身，希望大家能够共同努力，让这个开源项目真正造福大众，这样大众才能更有动力去反馈和改进。现把我发现的几个文档问题简单描述如下：
1. “准备 DolphinScheduler 启动环境”这一部分应该放在文档最顶部。原因：如果直接按照“前置准备工作”操作，会所有需要前置安装的工具安装在目前登录的账户，但实际上应该安装在一个新的账户里。比如后续文档描述的：创建 dolphinscheduler 用户。
2. # 创建用户需使用 root 登录：useradd dolphinscheduler，这个指令前面应该加上sudo，或者告诉用户如何首先进入root账户。
3. # 修改目录权限，使得部署用户对二进制包解压后的 apache-dolphinscheduler-*-bin 目录有操作权限。chown -R dolphinscheduler:dolphinscheduler apache-dolphinscheduler-*-bin。这里的描述非常不清楚，应该说明把apache-dolphinscheduler-*-bin替换为二进制安装包解压后的文件名。
4. 进入 zookeeper 的安装目录，将 zoo_sample.cfg 配置文件复制到 conf/zoo.cfg，并将 conf/zoo.cfg 中 dataDir 中的值改成 dataDir=./tmp/zookeeper。这里 zoo_sample.cfg配置文件在新版本中已经改变了。
5. 修改 install_env.sh 文件。这个文件在哪？至今没找到
以上只是一小部分，真的没法全列出来，太多了……

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
The use of third-party tools such as Linux does not belong to the scope of Dolphinscheduler, and should not be elaborated in the documentation.
