### ISSUE TITLE
[Bug] [Workflow] Intermittent Workflow Scheduling and Execution Failures in Dolphin v3.2.0

### ISSUE THREAD

**Issue by ydgpaysit** [apache/dolphinscheduler#16930]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

We are encountering issues with workflows in Dolphin v3.2.0. Specifically:

1. Workflows intermittently stop responding, and their schedules appear to stop randomly.
2. In some cases, we are unable to execute them manually as well.

Note: After reset it is resolving. We cannot see any logs about it.

We would greatly appreciate your insights or guidance on resolving this matter.

### What you expected to happen

Resume the execution of time schedules

### How to reproduce

Unable to reproduce consistently; the issue occurs intermittently.

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Fixed in `dev`.

**Comment by pirimoglu** [comment]
> Fixed in `dev`.

@SbloodyS do you have any release plan?

**Comment by SbloodyS** [comment]
> > Fixed in `dev`.
> 
> @SbloodyS do you have any release plan?

There is no specific plan date.

**Comment by pirimoglu** [comment]
@SbloodyS can you share the commit that fix this issue?

**Comment by ydgpaysit** [comment]
@SbloodyS  Is this problem fixed in 3.3.0-alpha ?
