### ISSUE TITLE
about resource usage visualization

### ISSUE THREAD

**Issue by mht-xyt** [apache/dolphinscheduler#1728]
The scheduling platform I used did not allow me to see the resource usage, so I needed to check it on the server, as well as the convenient tuning strategy. The parameters in the current configuration file are still vague, so the effect is not clear.
I want to know how to get my many workflows to take full advantage of server resources.
would you add some convenient and dynamic control of resources?

**Comment by dailidong** [comment]
sorry for reply late.
which resource do you want to see ?  cpu、memory or something else?

please give more information
