### ISSUE TITLE
high concurrency scenario

### ISSUE THREAD

**Issue by mht-xyt** [apache/dolphinscheduler#1730]
Scheduling too many tasks at the same time will result in the loss of some tasks, about 1%.
Individual tasks are small and fast. The average single execution time is about 10 seconds, with about 20+ task commits per second.
Is this a platform exception? How to optimize it?
Server resource utilization is less than 50% and there are no resource issues.

**Comment by dailidong** [comment]
At present, DS can't support such high concurrency tasks friendly

**Comment by gabrywu** [comment]
+1 
The Below Architecture may be perfect
[taskOnYarn](https://gitee.com/gabry_wu/publicImages/raw/b3a1d5abfa981c9f558e841c30ea144e4a3ef92d/%E6%9C%89%E9%81%93%E7%AC%94%E8%AE%B0/dolphinScheduler/taskOnYarn.png)

**Comment by davidzollo** [comment]
you can try the newest version. has support your scenario
