### ISSUE TITLE
[Feature]Some suggestions for workflow definition (工作流定义的一些建议)

### ISSUE THREAD

**Issue by jollygrass** [apache/dolphinscheduler#1839]
It's normal to have thousands of tasks in a workflow. At present, the definition of workflow is added and configured in the form of drag and drop in the sketchpad. When there are more tasks, it is difficult to find a specific task to modify and edit, and it is not convenient to configure task dependency by connecting.

1. It is recommended that the tasks of the workflow be presented in the form of a list.

2. There are separate menus or buttons for adding tasks, modifying tasks, and deleting tasks.

3. You can find tasks.

4. Task dependency should select the dependent task in the attribute of the task, rather than the form of connection.

5. Dag can be generated automatically according to the dependency, and then displayed in the drawing board. You do not need to specify the coordinates of the task.

6. The task editing page is suggested to be divided into two parts: SQL or script editor on the left and other attributes of the task on the right.

You can refer to the following layout:

[layout](https://bbs.dtwave.com/storage/article-editor/2019-06-27/5d14b207b1f0f.png)

--------------------------------------------------------

工作流中任务数上千是很正常的事情。目前工作流的定义是在画板里面通过拖拉拽的形式添加和配置的，当任务数一多，就很难找到指定任务进行修改编辑了，也不方便通过连线的方式配置任务依赖。

1、建议工作流的任务以列表的形式展示。
2、有单独的添加任务、修改任务、删除任务的菜单或按钮。
3、可以查找任务。
4、任务依赖应该在任务的属性里面选择所依赖的任务，而不是连线的形式。
5、能根据依赖自动生成DAG图，然后在画板里面直观展示。不需要人为指定任务的坐标。
6、任务编辑页面，建议分成左右两部分，左边是sql或脚本编辑器，右边是任务的其他属性。

可以参考下图的布局：

[参考界面布局](https://bbs.dtwave.com/storage/article-editor/2019-06-27/5d14b207b1f0f.png)

**Comment by dailidong** [comment]
> 1. It is recommended that the tasks of the workflow be presented in the form of a list.
> 2. There are separate menus or buttons for adding tasks, modifying tasks, and deleting tasks.
> 4. Task dependency should select the dependent task in the attribute of the task, rather than the form of connection.
---

At present, it is designed to be visual and draggable，Tasks can be added, modified and deleted on the UI

> 3. You can find tasks.
this is a very very good idea.  
 
> 5. Dag can be generated automatically according to the dependency, and then displayed in the drawing board. You do not need to specify the coordinates of the task.
It has been supported through API in version 1.2.0

> 6. The task editing page is suggested to be divided into two parts: SQL or script editor on the left and other attributes of the task on the right.
good idea.

> You can refer to the following layout:
>
> [layout](https://bbs.dtwave.com/storage/article-editor/2019-06-27/5d14b207b1f0f.png)
very good design, I think it's another design, different from the current design of DS

**Comment by dailidong** [comment]
thank you for your good suggesion.

**Comment by gabrywu** [comment]
+1

**Comment by kylozw** [comment]
find tasks +1

**Comment by gk0916** [comment]
@jollygrass  @dailidong 据我所知，图中的平台既提供了列表配置方式，也提供了DAG拖拉拽方式

**Comment by gk0916** [comment]
> @jollygrass @dailidong 据我所知，图中的平台既提供了列表配置方式，也提供了DAG拖拉拽方式

其前端DAG是通过前端控件来做的，会自动排版，易用性挺高。据我了解咱们的DAG是保存了固定的页面坐标，如果有精力的话，建议优化下。当然，我们的功能上是强大的，操作性，易用性是锦上添花。笔芯~
