### ISSUE TITLE
Java Annotation/Interface Task Support

### ISSUE THREAD

**Issue by Technoboy-** [apache/dolphinscheduler#1859]
Background:
  As some other scheduling system support Java annotation/interface task, and many users have discussed the demand in out last meet up, so DS is going to support this function in the future .  

General idea:
  1. Users only need to add annotation/implement a interface to register a task, using web for managing task(like start, stop, suspend)
```
@DolphinSchedulerTask("demo-task")
public void demoTask(){
    //User logic
}
```
  2. Single node, shard, all nodes, failover and etc will support.
  3. We need to support pure Java, Spring framework.

**Comment by clay4444** [comment]
+1, I will be involved in this work
