### ISSUE TITLE
[Feature]  Add task trigger to start up its depended on processes immediately

### ISSUE THREAD

**Issue by cconlyou** [apache/dolphinscheduler#1903]
As far as I know, every DAG auto run is initiated by a time trigger.
If the relationship between jobs is very complex and cannot be easily implemented in one DAG.
Although we can split into multiple DAGs through "dependency", these splited DAG can only be started by time trigger and failed retry policy. If the time setting is early, the polling takes up resources. If the time setting is late, there will be some time wasted.

----
据我所知，每个DAG自动运行都是由时间触发器启动的。如果作业之间的关系非常复杂，不能轻易在一个DAG中实现时，虽然可以通过"依赖"拆解为多个DAG，但是拆解后的DAG只能通过时间触发以及失败重试策略来启动。如果时间设置早了，就挂起轮询占用资源。如果设置晚了，中间会存在空档期。
能否考虑在每个任务完成时主动扫描其依赖项，如果其下游依赖项均满足，会立刻触发。

**Comment by wendyshusband** [comment]
I think this is a nice feature. In my opinion, every node in the DAG that dependent on other node is trigger by a event, and the node without dependency is trigger by time (crontab) or manual start. This is not a nice design. maybe we can made all node support event-driven and time-driven.

**Comment by zixi0825** [comment]
+1

**Comment by mpmiles** [comment]
I think this should be a necessary point. As a scheduling tool, if it cannot be triggered actively or manually, it will bring great difficulties to development, operation and maintenance
