### ISSUE TITLE
[Feature] Enhancement for Sql task

### ISSUE THREAD

**Issue by Jave-Chen** [apache/dolphinscheduler#1911]
**Is your feature request related to a problem? Please describe.**
For now, there are 2 limitations of Sql task:
1. can't use variable for other part of sql command, because the limitation of PreparedStatement .
2. can't execute multiple sql command in task content.

**Describe the solution you'd like**
1. Replace variable firstly and then execute sql command with PreparedStatement .
2. Split multiple sql command one by one , and then execute them.

**Comment by chengshiwen** [comment]
Related issue: #3799 #4563 #4465
Related pr: #4879 #4788
