### ISSUE TITLE
[Feature] Alert server run some script or subprocess

### ISSUE THREAD

**Issue by Jave-Chen** [apache/dolphinscheduler#1913]
**Is your feature request related to a problem? Please describe.**
Now, alert server just can send mail. But in some cases , alsert server is not allowed to connect Internet, which make users can't get alert.
So, I think adding more alert type can make it more easier.

**Describe the solution you'd like**
1. Alert server can run some script, such as shell or python .
2. Or alert server can call a created subprocess .

**Comment by gaojun2048** [comment]
Yes ,We done it at https://github.com/apache/incubator-dolphinscheduler/issues/3049
Email, wechat, dingtalk, script ant http(https) have been completed so far.
You can see the code at https://github.com/apache/incubator-dolphinscheduler/tree/alert_plugin_design/dolphinscheduler-alert-plugin.
