### ISSUE TITLE
[Feature][discussion] this is new feature that resource manager take charge of monitoring task.

### ISSUE THREAD

**Issue by woshiwuxiaofei** [apache/dolphinscheduler#1920]
No matter how submitting state or running state it is, the **resource manager** take charge of task start and monitor progress. 
I think task need to be monitoring, so put forward this suggestion . @gabrywu @wenhemin @Jave-Chen

**Comment by woshiwuxiaofei** [comment]
For exmaple, Runner in Master module can add BaseTaskMonitorThread. this function I have finished.

**Comment by dailidong** [comment]
please refer: https://dolphinscheduler.apache.org/zh-cn/docs/1.2.0/user_doc/architecture-design.html
