### ISSUE TITLE
[Feature]Settings on the workflow execution output arrow

### ISSUE THREAD

**Issue by chengcxy** [apache/dolphinscheduler#1924]
Suppose I have a workflow a
Workflow b depends on a, then after a is set to fail and stop, b will not start when a fails
I also have a task flow c which also requires to be executed after a but does not depend on a (execute c regardless of whether a is successful)

**Comment by chengcxy** [comment]
这时候在a的运行选项上设置失败策略后 只能满足b或c 
如果能对从a出来的箭头设置失败策略 更好

**Comment by chengcxy** [comment]
a -->(箭头失败策略：失败停止)b任务

**Comment by chengcxy** [comment]
假如我有一个工作流a
工作流b依赖a,那么对a设置为失败停止后,当a失败后b不会启动 这是正确逻辑
我还有一个任务流c 同样要求是在a之后执行但是不依赖a(不管a是否成功 都执行c)
这时候在a的运行选项上设置失败策略后 只能满足b或c

如果能对从a出来的箭头设置失败策略 更好
a -->(箭头失败策略：失败停止)b任务
a -->(箭头失败策略：失败继续)c任务
![image](https://user-images.githubusercontent.com/25173362/74124324-daa84200-4c0c-11ea-86d5-a7c1031116ef.png)

**Comment by dailidong** [comment]
good

could you add title/desc in English?

**Comment by dengc367** [comment]
is this feature stopped or in progress?
