### ISSUE TITLE
[BUG] The timing logic bug of the sub workflow sub_process causes the sub workflow to execute repeatedly

### ISSUE THREAD

**Issue by chengcxy** [apache/dolphinscheduler#1940]
![image](https://user-images.githubusercontent.com/25173362/74263501-ed6c6500-4d39-11ea-9dd6-508a12daa87b.png)

Here I have 3 workflows, a, b, all
Where all is the total dispatch flow, use a sub_process component to serialize a and b (a> b)
Set timing for all 00:15
Set timing 00:40 for b (data 00:30 will be written into the table to be read by b, so you need to set a time greater than 00:30)
At this point there will be an extreme bug
The a in all workflows is executed from 00:15 but the end time of a is> 00:40. Assuming it is 00:50, then the scheduled scheduling of b is started and waited until 00 at 00:40 : B in 50 minutes all workflow will be started again causing b to repeat

**Comment by Yeleights** [comment]
please desc using english!
