### ISSUE TITLE
[Feature] See service log on monitor page

### ISSUE THREAD

**Issue by Jave-Chen** [apache/dolphinscheduler#1959]
When users execute workflows, sometimes it will be stucked. And users need open a terminal and login to a server, then roll logs for DS services.

If there is a way to see services log on web page, it would be easy for uses to get the status of workflows.
For example, on monitor page, users can see latest 100 lines of Master/Worker/Api/Alert service log.

**Comment by dailidong** [comment]
good idea

**Comment by dailidong** [comment]
how to implement it need to consider more things ,  for now, I just think why so many projects not provide this feature?
