### ISSUE TITLE
[BUG] When logging into the system, cookie path not specified

### ISSUE THREAD

**Issue by yh2388** [apache/dolphinscheduler#1972]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
登录后设置的cookie未指定path，当我修改了/login接口的路径时，例如改为/ds/login，导致其他非/ds路径下的接口都无法获取到登录后的cookie中的sessionId。

[The cookie set after login does not specify the path. When I modify the path of the /login interface, such as changing it to '/ds/login', the other interfaces under the non '/ds' path cannot get the sessionId in the cookie after login]

**Which version of Dolphin Scheduler:**
 -[1.2.1-release]

**Requirement or improvement
- Whether to specify the Cookie path as "/"?

**Comment by dailidong** [comment]
good idea

could you submit a pr to solve this bug?

**Comment by yh2388** [comment]
Ok! I will do that.

**Comment by yh2388** [comment]
> good idea
> 
> could you submit a pr to solve this bug?

Ok! I will do that.

**Comment by zhongjiajie** [comment]
Is there any reason you want to change URL path?

**Comment by lenboo** [comment]
Closed because no response in a long time
