### ISSUE TITLE
[Feature] Increase the recycle bin to restore jobs in seconds

### ISSUE THREAD

**Issue by yangjf2019** [apache/dolphinscheduler#1977]
When I delete a workflow by mistake, I can't resume it immediately, I can only recreate it!

Can I add the function of the recycle bin for fast recovery?
@dailidong Thank you.

**Comment by dailidong** [comment]
version control will solve this issue，and someone from community is doing this feature

**Comment by yangjf2019** [comment]
Well ,thanks for your response!
