### ISSUE TITLE
easyscheduler Shell node catch exception

### ISSUE THREAD

**Issue by henliqi** [apache/dolphinscheduler#2010]
how easyscheduler Shell node catch exception?I wrote a Shell with exception in easyscheduler Shell node but it can‘t catch exception

**Comment by dailidong** [comment]
exception will show task log on the web page, at the same time you also should see worker server runtime log to find out the problem

![image](https://user-images.githubusercontent.com/15833811/75407226-6fb97380-594d-11ea-9640-f479a2d4d2b1.png)

**Comment by henliqi** [comment]
ok i know ,but how can i alert the problem,when exception was happened









At 2020-02-27 10:40:57, "dailidong" <notifications@github.com> wrote:

exception will show task log on the web page, at the same time you also should see worker server runtime log to find out the problem

**Comment by dailidong** [comment]
usually，use ELK to monitor log 
may be you can try add mail  configuration in the worker server logback xml file to set ERROR level send alert mail.

BTW  in the future I think DS should consider this situation ,make it more easier to troubleshoot

**Comment by dailidong** [comment]
if the shell node runs not right, will give the failure result, I want to know why not catch exception.
could you paste the shell content？

**Comment by dailidong** [comment]
> usually，use ELK to monitor log
> may be you can try add mail configuration in the worker server logback xml file to set ERROR level send alert mail.
> 
> BTW in the future I think DS should consider this situation ,make it more easier to troubleshoot

very sorry, this answer is not right way to solve this problem, ELK usually used to monitor server log, but not to solve business problem

**Comment by dailidong** [comment]
BTW, which version are you using ?
