### ISSUE TITLE
Suggest to support the Kettle job/transformation

### ISSUE THREAD

**Issue by icchux** [apache/dolphinscheduler#2032]
Use Shell dispatching a kettle component for a large number of kettle jobs can cause a memory explosion. Can you support this aspect of scheduling optimization

**Comment by dailidong** [comment]
@zhaxiaodong9860 is doing this feature

**Comment by zhaxiaodong9860** [comment]
Each call to kettle with a shell script will Initialize a JVM environment, which is the reason of memory overload.Calling the kettle API with Java can solve the memory overload problem, and I'm currently planning to support kettle job/transformation in the DS.

**Comment by dailidong** [comment]
> Each call to kettle with a shell script will Initialize a JVM environment, which is the reason of memory overload.Calling the kettle API with Java can solve the memory overload problem, and I'm currently planning to support kettle job/transformation in the DS.

good job, if you have some progress for this feature, please add to the comment

**Comment by lzy305** [comment]
@zhaxiaodong9860 this feature is done? I ask a question. where  the ktr/kjb save?  file or db?

**Comment by zhaxiaodong9860** [comment]
Not yet,I plan to achieve both. It's planned to be finished by the end of May.

**Comment by zhaxiaodong9860** [comment]
@lzy305 Not yet,I plan to achieve both. It's planned to be finished by the end of May.

**Comment by Mryst** [comment]
> @lzy305 Not yet,I plan to achieve both. It's planned to be finished by the end of May.

Hi~ how is the progress

**Comment by Mryst** [comment]
@zhaxiaodong9860 Hi ~ how is the progress

**Comment by jinyabin111** [comment]
what kettle vision is supported and how is the progress?

**Comment by dailidong** [comment]
@zhaxiaodong9860  hi ,how is the progress?

**Comment by Wang-Jun-Chao** [comment]
Hi ~ how is the progress

**Comment by JinsYin** [comment]
Hi ~ how is the progress?

**Comment by fqhaier** [comment]
@zhaxiaodong9860 请问现在DS支持kettle吗？

**Comment by fqhaier** [comment]
@davidzollo 请问现在DS支持kettle吗？

**Comment by sxiongzhang** [comment]
@zhaxiaodong9860  这个kettle 的支持没有后续了吗

**Comment by sxiongzhang** [comment]
so sad

**Comment by leehaut** [comment]
What apache hop vision is supported and how is the progress?
