### ISSUE TITLE
There is only one scheduling time for a workflow, but the workflow will be scheduled and executed multiple times

### ISSUE THREAD

**Issue by Cock001** [apache/dolphinscheduler#2122]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:

**Expected behavior**

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by Eights-Li** [comment]
Please provide more information, such as ds version, several masters, can check if the clocks of the following machines are synchronized

**Comment by Cock001** [comment]
At present, the version of dolphin scheduler is 1.1.0, with two masters and three slaves, the clock difference of each server will not exceed 1 minute

**Comment by zhongjiajie** [comment]
Cause no more adding information here, I would close this issue. You could reopen it if you have further question @Cock001 .
