### ISSUE TITLE
[Feature] Click on the column	Process Name, sort by name, otherwise out of order.

### ISSUE THREAD

**Issue by Hackeruncle** [apache/dolphinscheduler#2131]
**Is your feature request related to a problem? Please describe.**
 Click on the column	Process Name, sort by name, otherwise out of order.

![WX20200309-225406.png](https://i.loli.net/2020/03/09/Y8y1PRDftFNZzkQ.png)

**Comment by break60** [comment]
Do you want to add a sort function to the list?

**Comment by dailidong** [comment]
> Do you want to add a sort function to the list?
@Hackeruncle ，just sort by name?
