### ISSUE TITLE
According to folder dependency support?

### ISSUE THREAD

**Issue by ghost** [apache/dolphinscheduler#216]
The scripts for different projects are placed under different hierarchical directories. For example, as follows, there may be script dependencies in folder 2, and whether folders and script dependencies can be supported at present.
                Folder 2.1
File 1--"Box 2.2-------" File 3
               Folder 2.3

---
         不同的项目的脚本放在不同的分层目录下面，举个例子 如下，可能文件夹2中还有脚本的依赖，目前能否支持文件夹和脚本的依赖。
               文件夹2.1
文件1--》文件夹2.2-------》文件3
              文件夹2.3

**Comment by dailidong** [comment]
not supoort for now, we will consider this feature if more users need it, so we will keep this issue open.
if anyone else need this featue, please reply "+1"

**Comment by zongyaoou** [comment]
+1

**Comment by amorynan** [comment]
I have my version of  the granularity as  resource mapping project ，means that resource is related a project 
1. current version ： all resources are put into current tenant root dir
2. my changed version ： resources can be put into a project dir which can choose or u also can not choose like this picture shows

![image](https://user-images.githubusercontent.com/18551114/70803228-8809ff80-1dee-11ea-866a-570e0a926ab6.png)
