### ISSUE TITLE
[Feature] Provide batch operations for workflow instances with workflow dimensions

### ISSUE THREAD

**Issue by oceanos** [apache/dolphinscheduler#2164]
Q:
Higher frequency tasks will quickly generate a large number of workflow instances, which will cause the node load to soar; currently [v1.2.0] cannot quickly stop a large number of running workflow instances; even low frequency tasks will generate a large number of instance records over time. You will also encounter scenarios of batch operations later.
S:
So can you provide the batch operation function on the workflow instance page?
For example, to query workflow instances of the same workflow according to the association relationship, and perform batch operations.

**Comment by dailidong** [comment]
good idea

English is needed
