### ISSUE TITLE
[Feature] To support logic control, variable assignment and sharing of DAG internal task flow

### ISSUE THREAD

**Issue by JoshuaZhuCN** [apache/dolphinscheduler#2191]
目前有有一些调度场景存在一个DAG内基于前面的Task结果（可能会有一些出参之类），进行逻辑分支来调度不同的后续Task（即 类似于 IF tass01.out parameter == SUCCESS  Do task02 ELSE DO task03 ，并且task01的出参需要传递给后续task进行使用），目前airflow对这块支持的比较完善
他
[Machine translation]
there are some scheduling scenarios in which a DAG performs logical branches to schedule different subsequent tasks based on the previous task results (there may be some outgoing parameters, etc.) (i.e., similar to if task01.out parameter = = success do task02 else do task03, and the outgoing parameters of task01 need to be passed to the subsequent tasks for use). Currently, airflow supports this function perfectly

**Comment by stud2008** [comment]
同意楼上，调度系统最重要的两个功能：依赖和触发，dolphinscheduler的依赖这点做的还不够好。
依赖任务：需要前一个task的结果控制标志及数据位置传递给下一个task（现在只能放在数据库里，或者产生标志文件），我需要通过控制标志去决定走后续的哪个子分支，而不是一个DAG图傻傻的从左到右的执行。

**Comment by dailidong** [comment]
good idea

Please update/add title and description in English, thx

**Comment by xingchun-chen** [comment]
+1

**Comment by lianjie1229** [comment]
+1

**Comment by xied75** [comment]
所以请问一下这个issue的后续如何了？目前在1.3.6版本的解决方案是什么？多谢

**Comment by JoshuaZhuCN** [comment]
DEV分支有支持了通过全局参数进行传递的功能，还没合并到主线上，据说是至少要等到2.0版本才会并入，1.3系不会支持，其他方案么有，要么通过数据库自己临时实现下



在 2021-07-07 22:26:13，"Dong Xie" ***@***.***> 写道：

所以请问一下这个issue的后续如何了？目前在1.3.6版本的解决方案是什么？多谢
