### ISSUE TITLE
export work flow is xxx.png  i think change pdf is good??? 

### ISSUE THREAD

**Issue by feiyalun** [apache/dolphinscheduler#2194]
我建议 在工作流中导出当前工作流的时候，png格式改成pdf格式。 更方便，因为pdf可以搜索，  png没法搜索，尤其是工作流中有很多节点的时候

**Comment by dailidong** [comment]
good idea

are you interesting in implementing this feature?

**Comment by elitecodegroovy** [comment]
I will fixed this new feature.
