### ISSUE TITLE
There is a bug in the production alart  instance

### ISSUE THREAD

**Issue by feiyalun** [apache/dolphinscheduler#2230]
I found a problem, I think is should be a bug, I will mention issues, send alarm time is in the workflow, if choose the alarm set, should be in the maintenance of the alarm instance, check on choosing the type of alarm set corresponding alarm is given priority to, the insert will be subject to the type of alarm group, if have no choice, alarm set the default to system default admin warning is the type of group, in a word, I can't write a default email type, logic is when new instances of the alarm,Be sure to check the warning type of the corresponding alarm group.Because the recipient and cc are still supported at present, there is a situation that I choose a message Alert group, and at the same time, I maintain the mailer, I personally suggest that as long as you write an email, send, and text message, in fact, is to change the Alert module.

class AlertManager

**Comment by feiyalun** [comment]
我发现个问题，我认为是个应该算是个bug，我会提issues的，就是在工作流发送告警时候，如果选择告警组，应当在维护告警实例时，查下选择的告警组对应的告警类型为主，insert的时候 以告警组的类型为准，如果没选择，默认以系统告警组default admin warning group的类型为准，总之一句话，不能一上来就写默认的邮件类型，  逻辑就是在新增告警实例的时候，一定要去查对应告警组的告警类型。因为目前还支持收件人和抄送人，存在一种情况是我选个短信告警组，同时，我又维护邮件人了，我个人建议只要写了邮件，就发，同时短信也要发，其实就是改Alert模块。 
--------------------------------------------------------------------------
我只是实现了sms的那块的逻辑，  如果不改，永远会走email的，   我不改生成告警的实体类，只能在这上边判断告警组。。 默认系统告警组 就是邮件，只要选了不是系统告警组的，  而且是alert类型不是邮件的才能往下走我开发的sms逻辑

**Comment by zhongjiajie** [comment]
I would like to close this issue, if you have further information, you could reopen it @feiyalun
