### ISSUE TITLE
[Feature]support test task（支持任务调试）

### ISSUE THREAD

**Issue by simon824** [apache/dolphinscheduler#2239]
support testing the task before saving it,  and return  the result and log. This can make us more efficiently to determine whether the task is correct.

-----------------------------------------------------------

支持编辑完工作流保存之前可以对任务做试运行调试，可查看任务的运行结果和日志。这样我们能更高效判断任务是否正确

**Comment by simon824** [comment]
i will implement this feature

**Comment by huzekang** [comment]
> i will implement this feature

What's going on?
