### ISSUE TITLE
Log information display

### ISSUE THREAD

**Issue by khadgarmage** [apache/dolphinscheduler#226]
The log information should be displayed closer to the user, do not prompt java related debugging information, tell the user, the progress of the implementation, the specific steps, and the specific reasons for the failure. If you need to locate the problem, you can add a switch, DEBUG log mode is fine.

---
日志信息显示应该更贴近用户，不要提示java相关的调试信息，告诉用户，执行进度，具体步骤，以及失败具体原因等信息。如果需要定位问题，可以增加一个开关，DEBUG日志模式就可以了。

**Comment by dailidong** [comment]
very good!
we will implement it later！

**Comment by EricGao888** [comment]
Temporarily closed due to inactivity. If you could provide a detailed example, we will reopen this issue.
