### ISSUE TITLE
[QUESTION] Does this framework support custom java program tasks

### ISSUE THREAD

**Issue by hzq001** [apache/dolphinscheduler#2298]
*For better global communication, please give priority to using English description, thx! *
就是使用编写一个连接数据库的程序，Java来处理数据，都是这种任务，然后对这些任务进行依赖管理。
**Describe the question**
A clear and concise description of what the question is.

**Which version of DolphinScheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by simon824** [comment]
Please describe your problem in English.
You can package your java program into jar and run java task by shell.

你可以把你的java文件打成jar包然后创建并运行shell类型的任务。

**Comment by dailidong** [comment]
> Please describe your problem in English.
> You can package your java program into jar and run java task by shell.
> 

can this method solve your problem ? , or you can describe what function do you need

By the way, English is needed

**Comment by hzq001** [comment]
No, I want to have something like an XXL-JOB executor, and I implement the logic of this class

**Comment by dailidong** [comment]
> No, I want to have something like an XXL-JOB executor, and I implement the logic of this class

could you give more information ? 
I'm not familiar with xxl-job, please give some more  information about how to use , you can give some screenshot or someting

**Comment by hzq001** [comment]
> > No, I want to have something like an XXL-JOB executor, and I implement the logic of this class
> 
> could you give more information ?
> I'm not familiar with xxl-job, please give some more information about how to use , you can give some screenshot or someting

like this , through the RPC invoke the job executor in the other system.
<img width="878" alt="image" src="https://user-images.githubusercontent.com/12715885/77818326-7a158b80-710c-11ea-9a7d-96f164ac62d7.png">

**Comment by dailidong** [comment]
> > > No, I want to have something like an XXL-JOB executor, and I implement the logic of this class
> > 
> > 
> > could you give more information ?
> > I'm not familiar with xxl-job, please give some more information about how to use , you can give some screenshot or someting
> 
> like this , through the RPC invoke the job executor in the other system.
> <img alt="image" width="878" src="https://user-images.githubusercontent.com/12715885/77818326-7a158b80-710c-11ea-9a7d-96f164ac62d7.png">

very good , could you give this document url?  it seems like task plugin, maybe I can study how to implement it better, thx

**Comment by hzq001** [comment]
Thanks,I hope you can finish it, this is the url .
[xxljob-BEAN](https://www.xuxueli.com/xxl-job/#3.1%20BEAN%E6%A8%A1%E5%BC%8F%EF%BC%88%E7%B1%BB%E5%BD%A2%E5%BC%8F%EF%BC%89)

**Comment by keepmeup** [comment]
现在这个需求已经实现了吗？有同样的诉求
