### ISSUE TITLE
Add adhoc module增加adhoc模块）

### ISSUE THREAD

**Issue by ronyang1985** [apache/dolphinscheduler#232]
Amnesty, whether to consider adding an adhoc module, for hive, sparksql, mysql data source can be ad hoc query, after the query results are confirmed. Can be directly converted to a scheduling task. Similar to hue to turn the query into a mode of oozie workflow

---
大佬,是否考虑增加一个adhoc模块,针对hive,sparksql,mysql能数据源进行即席查询,查询结果确认后.可直接转为调度任务.类似hue将查询转为oozie工作流的模式

**Comment by dailidong** [comment]
We will add this new feature later this year. or could you contribute this feature ？
