### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by cainiaoxiaoshen** [apache/dolphinscheduler#2336]
At present, task triggering is timed. Can later versions support user-defined triggering, such as executing a section of SQL,  procedure, or Java program to trigger

**Comment by dailidong** [comment]
I'm sorry I can't unstand what you said exactly, does it means that you can execute java source code on the DolphinScheduler UI ?   could you give some screenshots  to help me unstand your idea, thx

**Comment by mpmiles** [comment]
I understand that this LZ should say that in addition to timing triggering, it should also support the active triggering mechanism of pre dependency. @dailidong
