### ISSUE TITLE
[Feature]Add key management

### ISSUE THREAD

**Issue by ChunMengLu** [apache/dolphinscheduler#2367]
**Is your feature request related to a problem? Please describe.**
dolphinscheduler run datax，datax json database name and key use a clear text account。
In addition, it is more inconvenient when migrating the environment.。

目前我们在用 dolphinscheduler 跑 datax，数据库的账号密码都采用的明文，这样环境迁移的时候每次都得修改导出的 datax json 或者 dolphinscheduler 的流程文件。

**Describe the solution you'd like**
Add key management or can choose the database key of the data source center when defining the workflow。

希望添加一个密钥管理或者可以在工作流定义的地方选择数据源中心的账号作为变量。

**Comment by dailidong** [comment]
good idea
next version will supprot datax task type
By the way, which vesion do you use ?

**Comment by ChunMengLu** [comment]
> good idea
> next version will supprot datax task type
> By the way, which vesion do you use ?

dev dolphinscheduler-1.2.0，production 1.2.1
