### ISSUE TITLE
I recommend supporting data support across workflows（跨工作流的血缘关系建议）

### ISSUE THREAD

**Issue by feiyalun** [apache/dolphinscheduler#2388]
We have a total of 650 script sources and endpoints, namely, STG and app layer have the most scripts. The middle layer is ods, DWD, dwa and DWR. According to the hierarchical construction flow, we rely on nodes to determine whether to go down or not.If one of the STG tables at the source is broken, or there is a problem with one of the mid-level tables.The upstream and downstream data to be replenishment can not be realized by cross-workflow, this scheduling framework can only be executed in this workflow forward, backward, and only execute itself.Once you cross the workflow, nothing is impossible.
In theory, the parent-child dependencies in each workflow can be connected to form a total blood map.In this way, the subsequent complement, relatively convenient.

**Comment by feiyalun** [comment]
我们一共650个脚本 源头和终点 也就是stg、 app层脚本量最多， 中间层 ods、dwd、dwa、dwr啊， 按照分层建流， 依靠节点来当天成功失败来是否往下走。如果源头的一张stg表数据坏了， 或者中层某个表数据有问题。上下游要补数据 靠跨工作流能无法实现重跑， 这个调度框架 只能在本工作流里往前执行、往后执行、仅执行本身。你一旦跨工作流了 ，就无没法实现。
  理论上是可以根据各自工作流里面的父子依赖串联起来，形成一个总的血缘图。这样后续要补数，就相对方便了。

**Comment by dailidong** [comment]
good suggestion，already add to Requirement Card

if anybody who like this feature, please reply "+1" or anything you want to reply, like how  to do implement it and so on, please feel free

**Comment by swxchappy** [comment]
+1

**Comment by zixi0825** [comment]
+1

**Comment by lgcareer** [comment]
Great!+1

**Comment by MyColorfulDays** [comment]
+1

**Comment by aikuyun** [comment]
+1

**Comment by Rubik-W** [comment]
I am implementing.

**Comment by jetaime-chen** [comment]
+1

**Comment by atai-555** [comment]
waiting!  +1

**Comment by atai-555** [comment]
Is there any progress on this requirement?

**Comment by Level1Accelerator** [comment]
+1

**Comment by JamesBonddu** [comment]
+1

**Comment by zhencang** [comment]
+1

**Comment by zhencang** [comment]
<img width="704" alt="image" src="https://github.com/apache/dolphinscheduler/assets/26265177/4cae91ed-9661-4eb1-95ae-a5766e762052">
<img width="1280" alt="image" src="https://github.com/apache/dolphinscheduler/assets/26265177/751bda19-cc70-437b-9c8b-7f9775fefef1">
Select the current job and its upstream and downstream recursion , then Complement data

**Comment by Ronin-man** [comment]
+1
