### ISSUE TITLE
[Feature] Sql check count function

### ISSUE THREAD

**Issue by wen-hemin** [apache/dolphinscheduler#2418]
The sql check count function is implemented locally, do you need this function.

![image](https://user-images.githubusercontent.com/39549317/79183190-5f008680-7e43-11ea-8402-51d167b86804.png)

**Comment by xingchun-chen** [comment]
+1

**Comment by ntupapaya** [comment]
support+1  如果按我理解这是个质量检查步骤？当查询结果为空则报错阻塞流程？

**Comment by chj4315** [comment]
support+1，这个业务场景还是挺重要的。
