### ISSUE TITLE
Lineage data kinship

### ISSUE THREAD

**Issue by boandai** [apache/dolphinscheduler#249]

**Comment by lidongdai** [comment]
if anybody else also need this feature , please reply "+1", thx

finally, we will decide which version to implement this feature based on the level of attention.

**Comment by liuminyt** [comment]
+1

**Comment by liuGangBestSkip** [comment]
+1

**Comment by thisnew** [comment]
+1

**Comment by zhanghuidouble** [comment]
+1

> if anybody else also need this feature , please reply "+1", thx
> 
> finally, we will decide which version to implement this feature based on the level of attention.

**Comment by wuchch** [comment]
+1

**Comment by moranrr** [comment]
+1

**Comment by ITriangle** [comment]
+1

**Comment by WangyanxuFp** [comment]
+1111111111

**Comment by coding-now** [comment]
+1

**Comment by lianayu** [comment]
+1

**Comment by lipengyu** [comment]
+1

**Comment by wangsvip** [comment]
+1

**Comment by zsmdata** [comment]
+1

**Comment by yh2388** [comment]
+1

**Comment by 7eng** [comment]
+1

**Comment by feiyalun** [comment]
+1

**Comment by Rubik-W** [comment]
I plan to implement data lineage function (Table level).

- The sql node and etl node automatically parse the dependency table and target table.
- The frontend controls whether to enable dependency detection through switch.
- The master server automatically injects dependent nodes, create dependent nodes based on dependencies.
- Rely on the node to set the default number of retries.
- Open the node that dependent detection function, no longer need to manually connect.

Already start a discussion in mail list.

E.g.
![image](https://user-images.githubusercontent.com/39549317/79307246-305cdb80-7f29-11ea-9c55-96ede9778a5e.png)
![image](https://user-images.githubusercontent.com/39549317/79307253-3488f900-7f29-11ea-8342-df7a52fac39e.png)
![image](https://user-images.githubusercontent.com/39549317/79307266-381c8000-7f29-11ea-9258-1572e6997215.png)

**Comment by simon824** [comment]
Will this design cause of loops？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Rubik-W"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月15日(星期三) 下午2:58
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"simon"<3656562@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] Lineage data kinship（Lineage数据血缘关系） (#249)





 
I plan to implement data lineage function (Table level).
  
The sql node and etl node automatically parse the dependency table and target table.
 
The frontend controls whether to enable dependency detection through switch.
 
The master server automatically injects dependent nodes, create dependent nodes based on dependencies.
 
Rely on the node to set the default number of retries.
 
Open the node that dependent detection function, no longer need to manually connect.
  
Already start a discussion in mail list.
 
E.g.

**Comment by Rubik-W** [comment]
Won't loops, Current workflow does not support circular relationships.
Checked when saving workflow.

**Comment by s751167520** [comment]
+1    Can the blood relationship of the table field be resolved ?

**Comment by Rubik-W** [comment]
The current design is to solve the blood relationship between the tables.

**Comment by gzvince** [comment]
+1

**Comment by wacr2008** [comment]
+1

**Comment by kangjunxiang** [comment]
+1

**Comment by yeyudefeng** [comment]
+111111111111111

**Comment by jetaime-chen** [comment]
+1

**Comment by geosmart** [comment]
+1

**Comment by geosmart** [comment]
> if anybody else also need this feature , please reply "+1", thx
> 
> finally, we will decide which version to implement this feature based on the level of attention.

+1

**Comment by geosmart** [comment]
just like airflow ,task have inlets and outlets attribute, user can define the inlets and outlets manualy;

how can I impl this in dolphinscheduler?
@dailidong

**Comment by dream009** [comment]
It has the necessary functions

**Comment by dengc367** [comment]
+1

**Comment by shitoubiao** [comment]
+1

**Comment by yh2388** [comment]
> I plan to implement data lineage function (Table level).
> 
> * The sql node and etl node automatically parse the dependency table and target table.
> * The frontend controls whether to enable dependency detection through switch.
> * The master server automatically injects dependent nodes, create dependent nodes based on dependencies.
> * Rely on the node to set the default number of retries.
> * Open the node that dependent detection function, no longer need to manually connect.
> 
> Already start a discussion in mail list.
> 
> * 支持sql节点和etl节点自动分析表之间的依赖关系，通过解析sql的select表和insert表实现，其他节点可以手工维护insert表（如果存在这种需求）
> * 前端通过依赖检测开关控制master在任务调度时是否进行依赖解析
> * master server自动注入依赖节点，运行时根据依赖关系生成虚拟依赖节点，不修改工作流定义数据，仅针对定时调度上线的工作流进行依赖分析
> * 生成的依赖节点设置默认失败重试次数，比如每5分钟检测一下
> * 打开依赖解析开关后，节点间不再需要手工连线，master根据依赖关系的顺序进行节点的调度
> 
> E.g.
> ![image](https://user-images.githubusercontent.com/39549317/79307246-305cdb80-7f29-11ea-9c55-96ede9778a5e.png)
> ![image](https://user-images.githubusercontent.com/39549317/79307253-3488f900-7f29-11ea-8342-df7a52fac39e.png)
> ![image](https://user-images.githubusercontent.com/39549317/79307266-381c8000-7f29-11ea-9258-1572e6997215.png)

Hi @Rubik-W , I am testing your implement, How to set process_definition_json from frontend, Should you show me a sample?

**Comment by Rubik-W** [comment]
> > I plan to implement data lineage function (Table level).
> > 
> > * The sql node and etl node automatically parse the dependency table and target table.
> > * The frontend controls whether to enable dependency detection through switch.
> > * The master server automatically injects dependent nodes, create dependent nodes based on dependencies.
> > * Rely on the node to set the default number of retries.
> > * Open the node that dependent detection function, no longer need to manually connect.
> > 
> > Already start a discussion in mail list.
> > 
> > * 支持sql节点和etl节点自动分析表之间的依赖关系，通过解析sql的select表和insert表实现，其他节点可以手工维护insert表（如果存在这种需求）
> > * 前端通过依赖检测开关控制master在任务调度时是否进行依赖解析
> > * master server自动注入依赖节点，运行时根据依赖关系生成虚拟依赖节点，不修改工作流定义数据，仅针对定时调度上线的工作流进行依赖分析
> > * 生成的依赖节点设置默认失败重试次数，比如每5分钟检测一下
> > * 打开依赖解析开关后，节点间不再需要手工连线，master根据依赖关系的顺序进行节点的调度
> > 
> > E.g.
> > ![image](https://user-images.githubusercontent.com/39549317/79307246-305cdb80-7f29-11ea-9c55-96ede9778a5e.png)
> > ![image](https://user-images.githubusercontent.com/39549317/79307253-3488f900-7f29-11ea-8342-df7a52fac39e.png)
> > ![image](https://user-images.githubusercontent.com/39549317/79307266-381c8000-7f29-11ea-9258-1572e6997215.png)
> 
> Hi @Rubik-W , I am testing your implement, How to set process_definition_json from frontend, Should you show me a sample?

When the front-end creates a workflow and clicks save, it is automatically generated according to the task configuration information.

**Comment by BobbySun** [comment]
+1, 这个功能很需要，我们还准备开发这样的功能呢

**Comment by ljp510016132** [comment]
+1 急需

**Comment by WilliamsZhang** [comment]
+1急需此功能

**Comment by jiakai908** [comment]
+1急需此功能

**Comment by lyyprean** [comment]
> _No description provided._

+1 +1 +1 急需此功能

**Comment by ricemouse** [comment]
+1

**Comment by glxfeng** [comment]
+1

**Comment by ntupapaya** [comment]
support +1

**Comment by brucemen711** [comment]
+1 I think we should not embedded with dolphin system. We could intro new module/plugin, so we could gen and put standard data lineage to other systems like apache atlas, marquez(Wework), ...
@dailidong @boandai

**Comment by irhawks** [comment]
+1

**Comment by dashenstone** [comment]
+1

**Comment by zhujian86** [comment]
+1

**Comment by yimaixinchen** [comment]
+1

**Comment by jon-qj** [comment]
+1

**Comment by huanzui** [comment]
+1

**Comment by Level1Accelerator** [comment]
这个需求很重要，+1

**Comment by chaclus** [comment]
+1

**Comment by gaogao110** [comment]
+1

**Comment by JVincerW** [comment]
II have done a similar function before, can you leave this task to me?

**Comment by zhongjiajie** [comment]
> II have done a similar function before, can you leave this task to me?

Hi @JVincerW  , we create a discussions to discuss how we implement it, if you interested on it, maybe you could add some comment on it

**Comment by davidzollo** [comment]
@JVincerW , I saw @zhongjiajie had created an discussion for this feature, can you show you idea about how to implement it in the Discussion: https://github.com/apache/dolphinscheduler/discussions/6596

**Comment by cxy-java** [comment]
+1

**Comment by ChenpiDog** [comment]
+1，海豚3.X版本似乎还没有实现数据血缘功能，这个功能对数据仓库来讲很重要。

**Comment by whmnoe4j** [comment]
+1 ， +10086 ，非常需要

**Comment by mayi295940** [comment]
> if anybody else also need this feature , please reply "+1", thx
> 
> finally, we will decide which version to implement this feature based on the level of attention.

**Comment by mayi295940** [comment]
+1

**Comment by yangtzelsl** [comment]
+1

**Comment by LoverAndrew** [comment]
+1

**Comment by Desugun** [comment]
+1

**Comment by 597365581** [comment]
+1

**Comment by kissycn** [comment]
+1
