### ISSUE TITLE
上线和定时任务应该做成递进

### ISSUE THREAD

**Issue by hebin-swxc** [apache/dolphinscheduler#2510]
已有【流程定义】下线编辑后，同时【定时】也会下线，进行再次上线时很容易忘记上线【定时】。

##建议##
上线【流程定义】和【定时】做成递进
如：做成 [下一步] -> [下一步] -> [...]. ->  [完成] ，这样就不容易忘记上线定时任务

**Comment by xingchun-chen** [comment]
good suggestion

**Comment by lenboo** [comment]
@hebin-swxc english is official language, please change the title and content to english.
