### ISSUE TITLE
[BUG] The data source control in the workflow instance will print the clear text password

### ISSUE THREAD

**Issue by StephenLau007** [apache/dolphinscheduler#2525]
点击工作流实例，选择数据源控件，填写连接，用户和密码，运行该组建，发现log信息是使用明文打印。
```
[INFO] 2020-04-23 14:06:13.838  - [taskAppId=TASK-16-123-164]:[127] - datasource name : ip , type : MYSQL , desc : 本地测试MySQL  , user_id : 2 , parameter : {"address":"明文jdbc连接","database":"数据库名","jdbcUrl":"明文jdbc连接","user":"用户名","password":"明文密码"}
```

**Comment by break60** [comment]
Méi kàn dǒng nǐ de miáoshù, néng fù shàng nǐ cāozuò de jiétú me
18/5000
Did not understand your description, can you attach a screenshot of your operation?

**Comment by zixi0825** [comment]
In the dev branch, this log will not be printed, but the password will still be printed  in another place, and I will fix this problem

**Comment by lenboo** [comment]
@StephenLU0422 english is official language, please change the title and content to english.

**Comment by StephenLU0422** [comment]
> In the dev branch, this log will not be printed, but the password will still be printed in another place, and I will fix this problem

thanks

**Comment by StephenLU0422** [comment]
> @StephenLU0422 english is official language, please change the title and content to english.

fine

**Comment by xingchun-chen** [comment]
@zixi0825 Has the issue been resolved

**Comment by gabrywu** [comment]
@StephenLU0422 I don't think it's a bug, just feature, right? which version of  your current DS?

**Comment by zixi0825** [comment]
> @zixi0825 Has the issue been resolved

Not solved yet, if it is confirmed as a bug, I can mention a pr to solve it.
@gabrywu 
@StephenLU0422 What do you think?

**Comment by rinkydevi** [comment]
hey @zixi0825 did u solved this issue or can i work on it?
