### ISSUE TITLE
[Feature]Correspondence between tasks in “Workflow instance” and “task instance”

### ISSUE THREAD

**Issue by ZhangchengHu0923** [apache/dolphinscheduler#2536]
**Is your feature request related to a problem? Please describe.**
Through the "Workflow Instance" Tab, we can quickly know from which task the problem started. At this time, I want to view the log of this task or perform some necessary operations on it, but it is difficult to do now. From the web interface There is no connection between the task in the "workflow instance" Tab and the task in the "task instance" Tab. From the workflow instance, I cannot even find the ID of the task instance.

通过"工作流实例" Tab，我们可以快速知道从哪任务开始出问题，这时我就想查看这个任务的日志，或对其进行一些必要操作，但现在很难做到. 从web界面上看，"工作流实例"Tab中的 task 和 "任务实例" Tab中的Task没有任何联系，从工作流实例中我甚至找不到任务实例的ID。

**Describe the solution you'd like**
1. Tasks in the workflow instance show the task instance id
2. In the "Workflow Instance" Tab, click to open the Detail Tab of a task instance, or jump to the "Task Instance" Tab and identify the task

**Describe the solution you'd like**
1、工作流实例中Task显示一下任务实例id
2、在"工作流实例"Tab，通过点击能打开某个任务实例的 Detail Tab，或者跳转到"任务实例"Tab并标识出该任务

**Describe alternatives you've considered**

**Additional context**

**Comment by break60** [comment]
+1

**Comment by ZhangchengHu0923** [comment]
what u mean 'you have this function dag'

**Comment by kyle-cx91** [comment]
...
