### ISSUE TITLE
[Feature]Serial also ignores errors and can continue to perform subsequent tasks

### ISSUE THREAD

**Issue by lizhuigit** [apache/dolphinscheduler#2543]
When I perform multiple serial tasks, I don't care whether there is an error or not.Can it be implemented that when a node encounters an error, the other nodes can continue to perform subsequent tasks?

**Comment by dailidong** [comment]
of course you can ,  when start the workflow, you can set the task failure strategy: contine or failure

![image](https://user-images.githubusercontent.com/15833811/80368215-ee378080-88be-11ea-9074-01a33d012b23.png)

**Comment by lizhuigit** [comment]
![image](https://user-images.githubusercontent.com/55183238/80369697-47a0af00-88c1-11ea-8625-a13737a36cd2.png)
That's not what I'm saying. Like this, if c makes a mistake, B should keep going.Existing functions can only achieve parallel tasks do not terminate, serial can not。
I want to realize that serial tasks can also ignore the state of the front node.The business scenario is that both A and C need to be executed, but eventually B must be executed, and only once.
我想实现，串行任务也可以忽略前置节点状态。业务场景是A和C都需要执行，但最终一定要执行B，且只执行一次。

**Comment by dailidong** [comment]
which version do you use? 

as I know , DolphinScheduler should support this operation

**Comment by longfeizhou2016** [comment]
As far as I know, it should be a new feature requirement, because I didn't find a setting corresponding to ignore failure in dolphinscheduler. By the way, we have implemented this feature based on the open source version of 1.3.4.

**Comment by walkenjoying** [comment]
I have such a need too,  and I wonder if any plan of this feature? 
Similar request of this issue #4115
Or I have to use the condition node to implement it?
