### ISSUE TITLE
Datax controll the num of split task have no effects

### ISSUE THREAD

**Issue by alexcd90** [apache/dolphinscheduler#2569]
the channel setting of core and job both get the dataXParameters. i think this lead to the number of channel is usually 1.it does't have any effect of the split task. 
`
/**
     * build datax setting config
     * 
     * @return datax setting config JSONObject
     */
    private JSONObject buildDataxJobSettingJson() {
        JSONObject speed = new JSONObject();
        speed.put("channel", DATAX_CHANNEL_COUNT);

        if (dataXParameters.getJobSpeedByte() > 0) {
            speed.put("byte", dataXParameters.getJobSpeedByte());
        }

        if (dataXParameters.getJobSpeedRecord() > 0) {
            speed.put("record", dataXParameters.getJobSpeedRecord());
        }

        JSONObject errorLimit = new JSONObject();
        errorLimit.put("record", 0);
        errorLimit.put("percentage", 0);

        JSONObject setting = new JSONObject();
        setting.put("speed", speed);
        setting.put("errorLimit", errorLimit);

        return setting;
    }

    private JSONObject buildDataxCoreJson() {
        JSONObject speed = new JSONObject();
        speed.put("channel", DATAX_CHANNEL_COUNT);

        if (dataXParameters.getJobSpeedByte() > 0) {
            speed.put("byte", dataXParameters.getJobSpeedByte());
        }

        if (dataXParameters.getJobSpeedRecord() > 0) {
            speed.put("record", dataXParameters.getJobSpeedRecord());
        }

        JSONObject channel = new JSONObject();
        channel.put("speed", speed);

        JSONObject transport = new JSONObject();
        transport.put("channel", channel);

        JSONObject core = new JSONObject();
        core.put("transport", transport);

        return core;
    }
`

**Comment by Rubik-W** [comment]
DATAX_CHANNEL_COUNT is 1 by default.
UI configuration does not support split table.
You can use custom config datax json.

**Comment by jiakai908** [comment]
> DATAX_CHANNEL_COUNT is 1 by default.
> UI configuration does not support split table.
> You can use custom config datax json.

i have done some feature modify so that we can pass the addtional datax json param through the local param . mabye this way is not graceful. 
`
![image](https://user-images.githubusercontent.com/32918492/80570507-7cca1000-8a2d-11ea-8eed-deed26ece87f.png)

if (otherDataxParamMap.size() > 0){
                Configuration conf = Configuration.from(json);
                for (Map.Entry<String,Object> el: otherDataxParamMap.entrySet()){
                    conf.set(el.getKey(),el.getValue());
                }
                json = conf.toJSON();
            }
`

**Comment by Rubik-W** [comment]
Good job.
Welcome to submit a PR.
