### ISSUE TITLE
[feature]File Manage support batch upload files

### ISSUE THREAD

**Issue by huyaoban** [apache/dolphinscheduler#2570]
Version: 1.2.0

File Manage support batch upload files
文件管理支持批量上传

![image](https://user-images.githubusercontent.com/24906133/80557323-1c28dc00-8a09-11ea-98ec-bd8e2fa68e21.png)

**Comment by dailidong** [comment]
good idea

btw， next version will support multi directory

**Comment by wuchunfu** [comment]
expect

**Comment by chengshiwen** [comment]
Related issue: #5201
