### ISSUE TITLE
[Add More EventTrigger]

### ISSUE THREAD

**Issue by Zhangwusheng** [apache/dolphinscheduler#2583]
For Now,flows are triggered by cron.

If I have a long running tasks and generate outputs at a nonuniform time slice,cron may not be suitable. The output may be a hdfs file, may be a zk node, or a kafka message which  indicates one batch has finished. So more event trigger source may be appreciated.

thanks.

**Comment by ja3per** [comment]
any updates for this new feature? 
looking forward this feature too.
