### ISSUE TITLE
[Feature] API  post requests do not support json format

### ISSUE THREAD

**Issue by lizhuigit** [apache/dolphinscheduler#2597]
Starting the task stream through the API, the contentType does not support json format.I could only do x-www-form-urlencoded, which forced me to manually stitch the parameters together.

通过API启动任务流，contentType不支持json格式。只能执行x-www-form-urlencoded格式的，这让我不得不把参数手动拼接起来。

**Comment by tlhhup** [comment]
could you paste your request screenshots?

**Comment by xingchun-chen** [comment]
@dailidong  Please confirm whether the problem needs to add json format

**Comment by gabrywu** [comment]
@lizhuigit Could  you give more infos, such version?

**Comment by hunnuxiaobo** [comment]
I recently came across the same issue in my application, the source code shows that only supports simple json format（json with flat structure）.

file: DolphinScheduler\dolphinscheduler-server\src\main\java\org\apache\dolphinscheduler\server\task\http\HttTask.java
line: 256
code:

`    protected void addRequestParams(RequestBuilder builder,List<HttpProperty> httpPropertyList) {
        if(CollectionUtils.isNotEmpty(httpPropertyList)){
            JSONObject jsonParam = new JSONObject();
            for (HttpProperty property: httpPropertyList){
                if(property.getHttpParametersType() != null){
                    if (property.getHttpParametersType().equals(HttpParametersType.PARAMETER)){
                        builder.addParameter(property.getProp(), property.getValue());
                    }else if(property.getHttpParametersType().equals(HttpParametersType.BODY)){
                        jsonParam.put(property.getProp(), property.getValue());
                    }
                }
            }
            StringEntity postingString = new StringEntity(jsonParam.toString(), Charsets.UTF_8);
            postingString.setContentEncoding(StandardCharsets.UTF_8.name());
            postingString.setContentType(APPLICATION_JSON);
            builder.setEntity(postingString);
        }
    }`

it means you can't post deeply nested json format like {"key1": {"key2": "value"}}

**Comment by CalvinKirs** [comment]
TBD

**Comment by HeChuanXUPT** [comment]
How to config complex json parameters on HTTP node?

![image](https://user-images.githubusercontent.com/5425689/125010426-0f862600-e099-11eb-93f9-8c4bc28a24f1.png)
Above configurations will be transfer to 
```
{
    "text":"{\"content\":\"test content\"}",
    "type":"text"
}
```

But what I want is: 
```
{
    "text":{
        "content":"test content"
    },
    "type":"text"
}
```

**Comment by davidzollo** [comment]
> How to config complex json parameters on HTTP node?
> 
> ![image](https://user-images.githubusercontent.com/5425689/125010426-0f862600-e099-11eb-93f9-8c4bc28a24f1.png)
> Above configurations will be transfer to
> 
> ```
> {
>     "text":"{\"content\":\"test content\"}",
>     "type":"text"
> }
> ```
> 
> But what I want is:
> 
> ```
> {
>     "text":{
>         "content":"test content"
>     },
>     "type":"text"
> }
> ```

sorry for reply late, you can covert the content of text to json on the back-end or do you have any suggestions?

**Comment by HeChuanXUPT** [comment]
> > How to config complex json parameters on HTTP node?
> > ![image](https://user-images.githubusercontent.com/5425689/125010426-0f862600-e099-11eb-93f9-8c4bc28a24f1.png)
> > Above configurations will be transfer to
> > ```
> > {
> >     "text":"{\"content\":\"test content\"}",
> >     "type":"text"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But what I want is:
> > ```
> > {
> >     "text":{
> >         "content":"test content"
> >     },
> >     "type":"text"
> > }
> > ```
> 
> sorry for reply late, you can covert the content of text to json on the back-end or do you have any suggestions?


like Postman ? separate header and body parameters, and support several types for parameters.
![image](https://user-images.githubusercontent.com/5425689/126940871-f2f5d675-4ee9-48fc-9a4f-97dfb6b3ac8c.png)

**Comment by zhongjiajie** [comment]
I think this is a feature instead of bug

**Comment by william-xu** [comment]
"API post request do not support json format" also means not support list properties like ["abc","xyz"] in current version(2.0.3) ?

**Comment by simsicon** [comment]
> I think this is a feature instead of bug

How can this be a feature? Please do not abuse "this is a feature not a bug" statement.
It would be a feature if the docs explicitly state it does not accept `application/json` as content-type.
