### ISSUE TITLE
[Feature] Workflow template(工作流模板)

### ISSUE THREAD

**Issue by wa-ooo** [apache/dolphinscheduler#2665]
希望提供工作流模板功能，可以便捷的通过模板去创建一类工作流任务。模板可以跨项目引用

**Comment by zixi0825** [comment]
Workflow templates can be implemented through sub-workflows

Attachment: The title and content need to be changed to English, please modify it

**Comment by qiaozhanwei** [comment]
@wa-ooo  please use english describle you problem

**Comment by dailidong** [comment]
good idea
