### ISSUE TITLE
[Feature] ds visual deployment

### ISSUE THREAD

**Issue by break60** [apache/dolphinscheduler#2675]
1.At present, the front end has completed the development of three module pages, namely cluster management, configuration management and host configuration.
2.The specific page is as follows：
![image](https://user-images.githubusercontent.com/55787491/81537810-59de1b00-93a0-11ea-9ef5-d0ffe7f077af.png)
![image](https://user-images.githubusercontent.com/55787491/81537822-5d71a200-93a0-11ea-81f6-9f99cbeb9367.png)
![image](https://user-images.githubusercontent.com/55787491/81537835-62365600-93a0-11ea-8417-a27359548c17.png)
![image](https://user-images.githubusercontent.com/55787491/81537851-68c4cd80-93a0-11ea-94bd-11994553a12d.png)
![image](https://user-images.githubusercontent.com/55787491/81537867-6e221800-93a0-11ea-8aff-782cddf4aa9a.png)
![image](https://user-images.githubusercontent.com/55787491/81537879-71b59f00-93a0-11ea-9ca4-7b7636ec3790.png)
3.At present, the back-end partners are required to complete the development of the corresponding interfaces, and the front-end can fully cooperate
4.If you are interested in ds visual deployment, you can join in and complete

**Comment by wuchunfu** [comment]
I want to join in, but where should I start? Where can I get the front-end and back-end code.

**Comment by break60** [comment]
There is currently no code in the backend, and framework and development interfaces need to be rebuilt

**Comment by wuchunfu** [comment]
Is there a developed program in the front end now? Where do I get it? Do you have any plans now, such as what development language is selected for the backend.

**Comment by break60** [comment]
> Is there a developed program in the front end now? Where do I get it? Do you have any plans now, such as what development language is selected for the backend.

The front end wrote some pages and simulated data, and the back end considered using Java https://github.com/break60/ds-deploy
