### ISSUE TITLE
[Feature]Processing relationship between two schedules of the same workflow

### ISSUE THREAD

**Issue by JoshuaZhuCN** [apache/dolphinscheduler#2678]
一个工作流定时调度，不可避免会出现两次调度重叠的情况（即本次调度发起时前一次调度还未结束），这种情况下根据不同的业务需求，需要不同的处理方式。比如本次处理高度依赖于前一次处理的结果则本次必须要进行排队等候不能立即执行，又或者完全数据和资源无关则可以两次调度并行执行...
建议在定时调度维护界面增加轮巡机制：
1、排队等候
2、立即执行
3、忽略本次

当然针对（1）可以增加附加属性  最大等待数

PS：可能需要考虑手动任务加入的情况

When a workflow is scheduled, it is inevitable that two scheduling overlaps (that is, the previous scheduling is not finished when the current scheduling is initiated). In this case, different processing methods are required according to different business requirements. For example, if the current processing is highly dependent on the results of the previous processing, it needs to be queued, or if the data is completely independent of resources, it can be scheduled and executed in parallel twice.....
It is recommended to add a patrol mechanism in the scheduled scheduling maintenance interface:
1. Wait in line
2. Immediate execution
3. Ignore this time

Of course, for (1) you can increase the maximum number of additional attribute waits, and for (2) you can increase the maximum number of additional attribute parallel tasks

PS: it may be necessary to consider the situation of manual task joining

**Comment by break60** [comment]
agree

**Comment by gjh9557** [comment]
有什么替代方法么现在

**Comment by chetaofeng** [comment]
现在这个问题有好的解决方法吗
