### ISSUE TITLE
[QUESTION] Dependent task check rules

### ISSUE THREAD

**Issue by wen-hemin** [apache/dolphinscheduler#2722]
Hello!

Abort dependent task check rules, I think the current implementation is problematic.

E.g. check logic: this week
The current implementation:
1.get this Monday
2.the date list of this Monday to current date（asc order）
3.Iterate through the list of dates in sequence to check the status of all process instances. There is a failure, the ultimate is failure state.

I think, the check logic should be:
1.get date range, start date and end date
2.if type is DEPENDENT_ALL
	query the first process instance in reverse order, check this instance state.
3.if type is non DEPENDENT_ALL
	query the first task instance in reverse order, check this instance state.

**Comment by Rubik-W** [comment]
mail list:
https://lists.apache.org/thread.html/rf1b2c374c30da8c2266d21bb308b738e6a3530234ffc42ce25e0b811%40%3Cdev.dolphinscheduler.apache.org%3E
