### ISSUE TITLE
[Feature] 工作流A依赖工作流B

### ISSUE THREAD

**Issue by SeaLeveGuo** [apache/dolphinscheduler#2862]
**目前在工作流定义模块不支持工作流A依赖工作流B（如下图所示 A 工作流 依赖B工作流）,在日常的使用场景中非常需要有这个功能，添加该功能是否可行呢？
![image](https://user-images.githubusercontent.com/25569324/83394862-e8880a00-a42b-11ea-90e1-6f9e840c9d37.png)

**Comment by Rubik-W** [comment]
Please change the title and description to English.
Currently supports dependent nodes, do not know whether it meets your needs.

**Comment by dailidong** [comment]
> Please change the title and description to English.
> Currently supports dependent nodes, do not know whether it meets your needs.

yes, you also can consider the sub process

**Comment by davidzollo** [comment]
you also can use dependent task type
