### ISSUE TITLE
[feature] hadoop-aliyun oss存储

### ISSUE THREAD

**Issue by ghost** [apache/dolphinscheduler#2864]
加入hadoop-aliyun模块，使用oss存储文件资源

**Comment by CalvinKirs** [comment]
This is not very recommended. These functions can be expanded by the enterprise itself.

**Comment by dailidong** [comment]
is it open source?

**Comment by fjbreeze** [comment]
[hadoop-aliyun](https://github.com/apache/hadoop/tree/2b2399d623539ab68e71a38fa9fbfc9a405bddb8/hadoop-tools/hadoop-aliyun) is a module belong to hadoop project

**Comment by chengshiwen** [comment]
Related pr: #3424

**Comment by EricGao888** [comment]
May I ask is there any update on this issue? https://github.com/apache/dolphinscheduler/pull/3424#issuecomment-683747588 Looks like PR #3424 was blocked because of hadoop version conflicts. I'd like to give another try if currently there is nobody working on this.

**Comment by EricGao888** [comment]
`OSSFS` is no more under maintenance. To support `Alibaba Cloud OSS` as the storage of `resource center`, there are two methods:

1. Use `OSS SDK`, see: https://github.com/apache/dolphinscheduler/pull/11708
2. Use `jindofs` to mount `OSS` bucket to local machines. I've already added the related instructions in `resource center` docs, see: https://dolphinscheduler.apache.org/en-us/docs/dev/user_doc/guide/resource/configuration.html

Above all, I'm closing this issue.
