### ISSUE TITLE
Mongodb data source support（支持Mongodb数据源）

### ISSUE THREAD

**Issue by fangniude** [apache/dolphinscheduler#2942]

**Comment by dailidong** [comment]
> Can we discuss about the datasource pluginable in mail-list?
> I think it's better to make the access of data source pluginable.
> What's your opinion? @dailidong

good idea, could you make a start on the dev@dolphinscheduler.apache.org mail list

**Comment by liukunyuan** [comment]
i will fix it

**Comment by yangyichao-mango** [comment]
> i will fix it

Glad to hear your want implement it.
But we plan to make the data source pluginable, so this issue should be supported after the pluginable is completed. Can you complete other issues first?

**Comment by liukunyuan** [comment]
ok

**Comment by liukunyuan** [comment]
> > i will fix it
> 
> Glad to hear your want implement it.
> But we plan to make the data source pluginable, so this issue should be supported after the pluginable is completed. Can you complete other issues first?

ok
