### ISSUE TITLE
Subthread cannot write to log file

### ISSUE THREAD

**Issue by hujiang75277381** [apache/dolphinscheduler#2956]
Problem Description:
In the main thread, use the sub thread or thread pool, and use the logger.info Unable to write log to worker log file.

Problem analysis:
The threadname is used in the class tasklogappender to split and get the log file, but it cannot be set in the sub thread, so it cannot be written to the log file.

Suggestions:
"[taskappid =% s]" is set in MSG in tasklogger. You can start cutting from this string.

**Comment by dailidong** [comment]
good job
could you submit a PR to solve this problem?
