### ISSUE TITLE
[Feature] In the workflow definition, it is recommended to add the function of creating folders.

### ISSUE THREAD

**Issue by SeaLeveGuo** [apache/dolphinscheduler#2980]
** In the workflow definition, it is recommended to add the function of creating folders to facilitate the classification management of workflow, such as: ods layer, dwd layer, dwb layer, dws layer.

**Comment by gabrywu** [comment]
> ** In the workflow definition, it is recommended to add the function of creating folders to facilitate the classification management of workflow, such as: ods layer, dwd layer, dwb layer, dws layer.

I think we'd better add some tags or labels to workflow ,through which we can do a lot of things. And we already have plans to do this , welcome to contribute. 
@guogithut We can talk about this with @Jave-Chen
