### ISSUE TITLE
How to do benchmark for DS?

### ISSUE THREAD

**Issue by rockxsj** [apache/dolphinscheduler#2986]
We have a lot of jobs to schedule every day, some of them should scheduled every five minutes, so in our usage scenario, the scheduling efficiency is the most important consideration.

For now, we use Airflow as our job scheduler, but along with the job and job instance increase, the pull up time of every job instance increase too, especially for the job should schedule in minutes are unbearable.

This is why we need do benchmark for DS. But I think one complete benchmark design is the first thing we should do, so can we discuss this?

---
我们每天有大量的任务需要调度，其中有些任务是每五分钟就要调度一次的，所以在我们的应用场景中，调度效率是最重要的考虑点。

当前我们使用Airflow作为我们的任务调度器，但是随着任务配置和任务实例的增长，单个任务被拉起的时长也随着增长，尤其对于那种几分钟就要执行一次的准实时任务，这是拉起时长是无法接受的。

这就是为什么我们需要针对DS做性能测试，但是我想在进行测试之前应当设计一个完备的性能测试方案，所以我们能一块讨论一下吗？

**Comment by BoYiZhang** [comment]
I'm also more interested in this

I am familiar with the code part and can communicate with each other

**Comment by CalvinKirs** [comment]
At present, ds is still strongly dependent on the database, so in the process of testing, should we use the form of a simulated database for benchmark testing?

**Comment by cwr31** [comment]
跟你需求基本一致，请教一下最终选了哪个？

**Comment by RedemptionC** [comment]
same question,has anyone done any benchmark for DS?
@CalvinKirs @zhongjiajie

**Comment by zhongjiajie** [comment]
I think it still do not have benchmark test for DolphinScheduler, Am I right? @caishunfeng

**Comment by caishunfeng** [comment]
> I think it still do not have benchmark test for DolphinScheduler, Am I right? @caishunfeng

Yes, we haven't done. And I think the stress test results have a lot to do with your tasks, but if you only want to test the main scheduler, you can try dry run.

**Comment by zhongjiajie** [comment]
cc: @RedemptionC  and @rockxsj
