### ISSUE TITLE
[Feature] It's take too long waiting for dependent node

### ISSUE THREAD

**Issue by kylozw** [apache/dolphinscheduler#3010]
It's take too much time when the whole project is huge and you use the dependent node. Now the dependent item requests `/queryProccessDefinitionAllByProjectId` for options, and one item requests one time. Take me for instance, I have about 2000 tasks and the data transfered is about 20M.

It's not necessary to query all data in definition(maybe just ids and names), or query for everytime. I reccommend shorten the data transfered to front and cache it in front.

![image](https://user-images.githubusercontent.com/5001813/84972517-97795500-b151-11ea-8ba2-eb159d3b2c2f.png)

---

当项目任务变多的时候，如果使用了依赖结点会变得很慢。现在依赖结点会请求`/queryProccessDefinitionAllByProjectId`以准备依赖项配置，而且是每个 dependent item 请求一次。我大概有 2000 个任务，然后每次请求都传输 20M 的数据，这太慢了。

如果只是为了准备依赖结点，我认为是不是没必要传输所有的定义数据（也许只要 id 和名称），还有不需要每个 dependent item 请求。我建议减少传输的数据字段，并将其在前端做一个缓存。

**Comment by xingchun-chen** [comment]
good suggestion

**Comment by yangyichao-mango** [comment]
Good idea.
I think pagination maybe a common way to implement that.
