### ISSUE TITLE
Logstash publishes elasticsearch data. When it is executing, click stop, and the workerserver service will also stop

### ISSUE THREAD

**Issue by glz-java** [apache/dolphinscheduler#3019]
**Describe the question**

When we execute the shell task, during the process of publishing the index through logstash (Note: make sure that the logstash shell node is already running), click stop in the workflow instance, and the workeService service will be stop too

**System**

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"

**Which version of DolphinScheduler:**
 -[1.2.0] OR [1.2.1]

**Additional context**

![img1](https://user-images.githubusercontent.com/67086511/85107036-d7b70100-b23f-11ea-85ba-60ff95e81d73.png)
![BRTYBJ~P6`~68(FA6%YY$UG](https://user-images.githubusercontent.com/67086511/85109404-dbe51d80-b243-11ea-9834-5d795625b8fc.png)
![img3](https://user-images.githubusercontent.com/67086511/85107048-db4a8800-b23f-11ea-990d-92e3a5dc39e7.png)

**Requirement or improvement
Expectation: the workers server service will not stop after clicking stop

**Logfile**
[dolphinscheduler-worker.log](https://github.com/apache/incubator-dolphinscheduler/files/4803037/dolphinscheduler-worker.log)

**Comment by dailidong** [comment]
this situation is abnormal, you can try set config items in the zookeeper.properties:

zookeeper.session.timeout=60000
zookeeper.connection.timeout=30000

**Comment by dailidong** [comment]
1、are you sure that your linux user jiawei can execute `/home/fuming/software/logstash-7.1.1/bin/logstash -f /home/fuming/software/logstash-7.1.1/config_db_indexer/sql.indexer_es.conf` ?
2、does a simple shell task like `echo 111` runs normally, and is this simple shell task also lead to Worker server stop?

**Comment by glz-java** [comment]
> 1、are you sure that your linux user jiawei can execute `/home/fuming/software/logstash-7.1.1/bin/logstash -f /home/fuming/software/logstash-7.1.1/config_db_indexer/sql.indexer_es.conf` ?
> 2、does a simple shell task like `echo 111` runs normally, and is this simple shell task also lead to Worker server stop?

1、It can be confirmed that normal conditions can be executed successfully
2、Simple shell tasks are OK

At present, the problem only occurs when the logstash task is executed. If you do not click stop manually, the problem will not occur. You can execute the process normally

**Comment by glz-java** [comment]
> this situation is abnormal, you can try set config items in the zookeeper.properties:
> 
> zookeeper.session.timeout=60000
> zookeeper.connection.timeout=30000

After these two parameters are modified, they still appear
