### ISSUE TITLE
[Feature] Which part of the document do you want？

### ISSUE THREAD

**Issue by davidzollo** [apache/dolphinscheduler#3021]
we want to write some documents about the DolphinScheduler.
now, Which part do you think is most needed？

**Comment by heyzeng** [comment]
about ambari-plugins ，thanks.

**Comment by lpbest** [comment]
Fault Tolerance. Although the fault tolerance design is already described in the official document, it is a little corseness. I think it is better to list more failover scenarios (such as, fail over will be triggered when a master starts and only one active master is found). 
If possible, the authors should describe the cases for failover or other critical exception handling as many as possible.

**Comment by BoYiZhang** [comment]
I am more concerned about the stability of operation

For example:

1. In the 1.3.0 architecture, the worker is not making persistent storage

Suppose that after the worker or master hangs up,

How to ensure the normal operation of the task without data problems

2. Fault tolerance mechanism, when will it lead to fault tolerance??

**Comment by glxfeng** [comment]
How to upgrade from version 1.2 to version 1.3

**Comment by Ashal** [comment]
how to deploy to k8s

**Comment by BoYiZhang** [comment]
How to configure alarm on wechat

This has been asked a lot recently

**Comment by enoughwell** [comment]
How to configure alert on wechat??

**Comment by Slowfever-star** [comment]
hi,detail and tune the configuration of Dolphinscheduler

**Comment by BoYiZhang** [comment]
> hi,detail and tune the configuration of Dolphinscheduler

If you look at this, is it meeting the demand

https://github.com/apache/incubator-dolphinscheduler-website/blob/master/docs/zh-cn/1.3.2/user_doc/configuration-file.md

**Comment by BoYiZhang** [comment]
> How to configure alert on wechat??

![image](https://user-images.githubusercontent.com/39816903/94501690-ffe9cf00-0234-11eb-8503-97a439332e3d.png)


https://dolphinscheduler.apache.org/zh-cn/docs/1.3.2/user_doc/cluster-deployment.html

**Comment by AhahaGe** [comment]
1. 微信告警 用户可能配置上了，但用户不知道怎么用这个告警，何时触发告警  微信告警我看ds如何企业token这些写了，就是配置告警这块可能还没有文档，让后我把这块整理到一起，写个中英文的文档
2. datax里有自定义，如果发现DS里的参数不能满足，他可以选择自定义模板

**Comment by BoYiZhang** [comment]
Sqoop is required to use documentation. Recently, many people have asked sqoop.
