### ISSUE TITLE
[QUESTION] Can't set dependency check

### ISSUE THREAD

**Issue by jxzdoing** [apache/dolphinscheduler#3066]
HI everyone，
we have a lot of workflow in one project，those workflow was created by time order。when i need to set dependency check in 
a workflow（it depends on a node in another workflow ），It's really strange，in the second select box，I can select the destination workflow，but in the third select box，the nodes display are not belong to the workflow which was selected in the second select box， its' belong to the workflow which was created last time，It's anyone has the same problem?
the second select box：
![image](https://user-images.githubusercontent.com/16585537/85942844-92d94b80-b95e-11ea-827e-a9185d648c70.png)

the third select box:
![image](https://user-images.githubusercontent.com/16585537/85943089-50187300-b960-11ea-953c-de1d15afa76f.png)

**Comment by super-sponge** [comment]
> HI everyone，
> we have a lot of workflow in one project，those workflow was created by time order。when i need to set dependency check in
> a workflow（it depends on a node in another workflow ），It's really strange，in the second select box，I can select the destination workflow，but in the third select box，the nodes display are not belong to the workflow which was selected in the second select box， its' belong to the workflow which was created last time，It's anyone has the same problem?
> the second select box：
> ![image](https://user-images.githubusercontent.com/16585537/85942844-92d94b80-b95e-11ea-827e-a9185d648c70.png)
> 
> the third select box:
> ![image](https://user-images.githubusercontent.com/16585537/85943089-50187300-b960-11ea-953c-de1d15afa76f.png)

sometime the dependency does not work!

**Comment by xingchun-chen** [comment]
Which version？
Can you describe the steps to reproduce

**Comment by jxzdoing** [comment]
> > HI everyone，
> > we have a lot of workflow in one project，those workflow was created by time order。when i need to set dependency check in
> > a workflow（it depends on a node in another workflow ），It's really strange，in the second select box，I can select the destination workflow，but in the third select box，the nodes display are not belong to the workflow which was selected in the second select box， its' belong to the workflow which was created last time，It's anyone has the same problem?
> > the second select box：
> > ![image](https://user-images.githubusercontent.com/16585537/85942844-92d94b80-b95e-11ea-827e-a9185d648c70.png)
> > the third select box:
> > ![image](https://user-images.githubusercontent.com/16585537/85943089-50187300-b960-11ea-953c-de1d15afa76f.png)
> 
> sometime the dependency does not work!

did you mean It's a bug for DS？

**Comment by jxzdoing** [comment]
> Which version？
> Can you describe the steps to reproduce

Hi，
   The DS version is：1.2.1

**Comment by jxzdoing** [comment]
When i upgrade DS to the latest version 1.3.0，the problem is no more appeared!

**Comment by super-sponge** [comment]
> Which version？
> Can you describe the steps to reproduce

DS version is : 1.3.0 .  
always lost dependence when  add some new node to the flow .   especially when add resouce file .

**Comment by zhongjiajie** [comment]
> When i upgrade DS to the latest version 1.3.0，the problem is no more appeared!

I would like to close this issue, if you have further information, you could reopen it @jxzdoing
