### ISSUE TITLE
[QUESTION] does DS support rerun across workflow or project with dependency automatically ?

### ISSUE THREAD

**Issue by jxzdoing** [apache/dolphinscheduler#3082]
DS version:1.3.0
There are three workflow in the one project ,such as ods,dwd,dws. in workflow ods, it include two nodes A,B. in workflow dwd,it include two nodes C,D. in workflow dws ,it include one node E.  one of the dependency relationship  describe as follow:
A->C->E
my question is: if node A failed, is there any button or method i can rerun node A and all the nodes which depend A automatically  ,
such as C,E . but not rerun them one by one ,it's not smart and will take us a lot of time. As i konw , Alibaba has a silimar tool named Dataworks can impelement his function. does DS has plan or already this function?

**Comment by Rubik-W** [comment]
When process instance is fail, The process instance list page has retry button.

**Comment by yangyichao-mango** [comment]
Hi, Good idea.
This function is actually dependent on lineage, and if there are multiple downstream, the situation will be more complex.
If you have some good suggestion about this feature, please put forward.
Thx a lot.
