### ISSUE TITLE
I hope to support the script task of java syntax

### ISSUE THREAD

**Issue by leiruiqi** [apache/dolphinscheduler#309]
When offline tasks run simple tasks, the programmer may be a java stack, and is better at java processing logic. When the task is not complicated, I also hope to use java to write a job task class to take effect in real time.
Using Groovy to generate classes, I see that other scheduling platforms have support for such features.
```
  Class<T> clazz = groovyClassLoader.parseClass(codeSource);
```
think about it.

---
离线作业跑简单任务的时候，程序员可能是java栈的，更擅长java处理逻辑。在任务不复杂的时候也希望用java写一段job任务类实时生效。
用Groovy生成class，我看到别的调度平台有支持这样的特性,
```
 Class<T> clazz = groovyClassLoader.parseClass(codeSource);
```
考虑一下。

**Comment by lidongdai** [comment]
good idea, we will keep this issue open , if anybody else also want to add this feature, please repley "+1" !

**Comment by moonhunter1986** [comment]
+1

**Comment by ouyanghuangzheng** [comment]
+1

**Comment by DingZhengCN** [comment]
+1

**Comment by yangyichao-mango** [comment]
+1，and I'm interesting in this issue, I think i can implement that issue.

**Comment by kangjunxiang** [comment]
+1

**Comment by dairui2** [comment]
+1, and it may be designed to be abstract enough

**Comment by yangyichao-mango** [comment]
> +1，and I'm interesting in this issue, I think i can implement that issue.

In my opinion and understanding, I think about it again and I think we need to deeply think about whether it's necessary to add java script. 

1.Python and shell script can do anything that java script can do.
2.If user familiar with Java, they also can use some simple python or shell scripts to call java jar or java class, they just need maintain the jar lib.
3.It will make DS complicated before achieve the pluggable DS, it will make the DS modules will be clearer.

--------------
我自己又思考了了下，个人理解我们应该再考虑下是否有必要添加java脚本的支持，原因如下：

1.Python 和 shell 脚本其实已经可以实现任何 java 脚本可以做的东西。
2.如果用户对java更加熟悉，也可以使用简单的 Python 或者 shell 脚本去调用 java jar 包 或者 class 文件，只需要维护这写jar包就可以了。
3.个人理解如果这个诉求很多人都有的话，其实我们完全可以在将DS插件化这个issue实现之后再做这个，这样的话模块之间会更加清晰。
