### ISSUE TITLE
[Feature]upload file to resource one file at a time very inefficient, can upload more at a time?

### ISSUE THREAD

**Issue by primoshen** [apache/dolphinscheduler#3092]
**Describe the solution you'd like**
upload file to resource one file at a time very inefficient, can upload more at a time?
资源上传，一次只能上传一个文件，效率太低了，如果文件多，耗时就会比较久，此外如果文件上传到错误的文件夹，则又需要重新上传；

在此也可以通过后台把文件一次上传到hdfs，然后文件信息插入到表t_ds_resources中，但效率还是有点...

**Comment by xingchun-chen** [comment]
good idea

**Comment by yangyichao-mango** [comment]
Hi,
Good idea, would it be better to include the following two functions:
1. DS directly binds a certain HDFS path, the files can be uploaded from the background to HDFS by user.
2. The front end uploads multiple files at a time.

**Comment by liuxuedongcn** [comment]
> Hi,
> Good idea, would it be better to include the following two functions:
> 
> 1. DS directly binds a certain HDFS path, the files can be uploaded from the background to HDFS by user.
> 2. The front end uploads multiple files at a time.

A node type can be extended to upload local files to hdfs, which can be run in multiple threads, I can complete this

**Comment by chengshiwen** [comment]
Related issue: #5201
