### ISSUE TITLE
[Feature]The list page displays sortable

### ISSUE THREAD

**Issue by yoreyuan** [apache/dolphinscheduler#3170]
Now, the list pages can only be sorted in reverse chronological order. When **SUB_PROCESS** is used, the **Child Node** of the subprocess a lot of, all **Child Node** processes need to be online when **Process** online. If a **Child Node** process is **offline**, it is difficult to find it.

![Process definition Page](https://cdn.nlark.com/yuque/0/2020/png/649951/1594269384693-48ab0bbb-4571-4c83-a191-83ab4d895fbd.png)

<br/>

If we can choose to sort `State` , processes with **offline** state will be easy to find, similar to this function of the Hadoop YARN page.

![Hadoop YARN Page](https://cdn.nlark.com/yuque/0/2020/png/649951/1594271765562-d1dd3b25-1de0-487e-b602-2a198e6002ad.png)

**Comment by wuchunfu** [comment]
I'll fix it.

**Comment by yoreyuan** [comment]
> I'll fix it.

Much obliged! I think this is a very useful function.

**Comment by yangyichao-mango** [comment]
> I'll fix it.

Glad to hear you will implement this feature.
Would it be better to support search for all columns?

**Comment by wuchunfu** [comment]
I think it's a good idea to add status search.

**Comment by yoreyuan** [comment]
> I think it's a good idea to add status search.

**Comment by yoreyuan** [comment]
If DS add like `Create Time` or `Update Time`, users can query **Process** for certain dates

**Comment by yoreyuan** [comment]
> I think it's a good idea to add status search.

If DS add like `Create Time` or `Update Time`, users can query **Process** for certain dates

**Comment by yangyichao-mango** [comment]
> > I think it's a good idea to add status search.
> 
> If DS add like `Create Time` or `Update Time`, users can query **Process** for certain dates

Hi,
I think it is a good feature. Welcome to contribute~
