### ISSUE TITLE
One workflow execute with multiple groups of parameters

### ISSUE THREAD

**Issue by muruhanjiang** [apache/dolphinscheduler#3193]
In many scenarios, because the database sub-organization deploys multiple sets, a procedure or workflow needs to be executed on several or even dozens of databases, and there are thousands of procedures or workflows. If you just copy the workflow reconfiguration parameters operation, the maintenance costs can be very high. Therefore, it is recommended that a development-state workflow is executed in parallel with multiple sets of parameters in the operational state.

One implementation that can be considered is to group parameters and execute instances of a workflow based on the number of groups.

**Comment by gabrywu** [comment]
"copy the workflow reconfiguration parameters operation" is just a onetime job, right? Maintenance costs will not so high

**Comment by muruhanjiang** [comment]
No.If we need to upgrade some parts of workflows, we should do this copy thing everytime.

**Comment by muruhanjiang** [comment]
> "copy the workflow reconfiguration parameters operation" is just a onetime job, right? Maintenance costs will not so high

No.If we need to upgrade some parts of workflows, we should do this copy thing everytime.
