### ISSUE TITLE
[Feature][ui]Admin users can click to view doc.html or swagger-ui.html

### ISSUE THREAD

**Issue by yoreyuan** [apache/dolphinscheduler#3247]
Admin users can click here to view the api document after logging in to DS. As shown below

![API doc](https://cdn.nlark.com/yuque/0/2020/png/649951/1595214220711-e41f30c2-2ef5-420c-8bd8-a61141c370e4.png)

After clicking, it can jump to [http://hostname:port/dolphinscheduler/doc.html]() or [http://hostname:port/dolphinscheduler/swagger-ui.html]().

**Comment by yangyichao-mango** [comment]
Hi,
I think it is a good feature to add `http://hostname:port/dolphinscheduler/doc.html` for admin and it is easy to implement.

Anyone who want to implement it , please leave a message.

**Comment by yoreyuan** [comment]
> Hi,
> I think it is a good feature to add `http://hostname:port/dolphinscheduler/doc.html` for admin and it is easy to implement.
> 
> **Anyone who want to implement it , please leave a message.**
> 
> `Noted`: What's the important is that the authority, and we should pay attention to the authority. For dev branch, I test and find anyone who have not logged in can reach the `http://xxx/dolphinscheduler/doc.html`.
> Suggest to control the permissions of the `swagger doc interface` although there is already has the permission check when user call the api.

I have implemented the UI part. As you said, `doc.html` or `swagger-ui.html` without user authentication, everyone can access if they know the connection, I am considering how to implement this part of authentication.

**Comment by dailidong** [comment]
> > Hi,
> > I think it is a good feature to add `http://hostname:port/dolphinscheduler/doc.html` for admin and it is easy to implement.
> > **Anyone who want to implement it , please leave a message.**
> > `Noted`: What's the important is that the authority, and we should pay attention to the authority. For dev branch, I test and find anyone who have not logged in can reach the `http://xxx/dolphinscheduler/doc.html`.
> > Suggest to control the permissions of the `swagger doc interface` although there is already has the permission check when user call the api.
> 
> I have implemented the UI part. As you said, `doc.html` or `swagger-ui.html` without user authentication, everyone can access if they know the connection, I am considering how to implement this part of authentication.

I don't think API interface need user authentication, it's open API for everyone to use

**Comment by chengshiwen** [comment]
Related issue: #4499
