### ISSUE TITLE
[To optimize the install DS ][install] Develop DS installer

### ISSUE THREAD

**Issue by felix-thinkingdata** [apache/dolphinscheduler#3297]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the feature**
1.One-click installation function ，One-key installation features, including user Settings, non-secret through, ZK installation and DS installation.
2.Single service start, stop, restart
3.Single node all services, start, stop, restart
4.Ds upgrade
5.Ds node expansion
6.DS installer update

**Comment by yangyichao-mango** [comment]
Good idea.
