### ISSUE TITLE
[Improvement][*] Improvement the code reported by sonar

### ISSUE THREAD

**Issue by yangyichao-mango** [apache/dolphinscheduler#3325]
**Describe the improvement**

#3321 is for bug reported by sonar.
This issue is for `code smell` and `VULNERABILITY` part reported by sonar, and is the sub-task of #3321

**Comment by yangyichao-mango** [comment]
It is suggested that we should analyze which ones need to be modified according to sonar's suggestions, which do not need to be modified according to sonar's suggestions, and which need to be modified to implement the code.

For example: some bugs don't exist originally, but they will be recognized as bugs by sonar due to an extra keyword written in the code. However, sonar's suggestions sometimes suggest us to adapt these changes rather than revert them.

------------
建议我们应该分析一遍哪些是需要根据sonar的建议修改，哪些不需要根据sonar的建议修改，哪些需要去改实现代码。

举例：有些bug是原本不存在的，但是由于编写代码时多写了一个关键字，就会被sonar识别成为bug。但是sonar的修改建议有时候会让我们去适配这些改动，而不是revert这些改动。

If you are interested in these, welcome to submit a pr and fix them~

**Comment by yangyichao-mango** [comment]
Tag: Easy to improvement @yangyichao-mango , if you are interested in this, please leave a message.

**Comment by Segun-Ogundipe** [comment]
Hi @dailidong, is this issue still available? I'll like to work on it. Thank you.

**Comment by Segun-Ogundipe** [comment]
Hi @CalvinKirs, can you suggest another issue for me if this one is not available?

**Comment by CalvinKirs** [comment]
> Hi @CalvinKirs, can you suggest another issue for me if this one is not available?

Sorry to reply to you so late, I have already passed @yangyichao-mango , this issue is recommended for you to complete, thank you very much for your participation
