### ISSUE TITLE
[Bug][Display status bug after task running] 

### ISSUE THREAD

**Issue by chengcxy** [apache/dolphinscheduler#3380]
the status of task as a subprocess, display in Web was success,But in fact double click the subprocess and inner the next page ,the status of task is raised an exception,task instance is not exists.Next 3 pictures runing on 2020-08-02 03:4*:**(china beijing time).

it will caused an exception of task scheduler  if the task which have next waited running tasks, we expect when  it failed and next tasks could not run...

however it's display success and make the next tasks also enqueue the queue of waiting runing .

the picture of one
![image](https://user-images.githubusercontent.com/25173362/89112106-df99d000-d490-11ea-801b-8b25acbd23eb.png)

the picture of two
![image](https://user-images.githubusercontent.com/25173362/89112169-65b61680-d491-11ea-8d32-ab259dbe6754.png)

the picture of three
![image](https://user-images.githubusercontent.com/25173362/89112171-7797b980-d491-11ea-85c5-11bee4e57874.png)

on  2020-08-01 09:4*:**(china beijing time),the task failed but in web displayd success

the picture of failed in fact
![image](https://user-images.githubusercontent.com/25173362/89112223-16bcb100-d492-11ea-8e12-12900a0f18a4.png)

the picture of display success
![image](https://user-images.githubusercontent.com/25173362/89112276-107b0480-d493-11ea-94fb-f1e0949fdb70.png)

**Comment by lenboo** [comment]
which version you used ?

**Comment by chengcxy** [comment]
1.2.1

**Comment by lenboo** [comment]
Closed because it have been fixed in new version.
