### ISSUE TITLE
[Improvement][项目管理] 工作流定义页面是否可以添加"全部下线"、"全部运行"功能？

### ISSUE THREAD

**Issue by XiaoMiSum** [apache/dolphinscheduler#3400]
[*For](url) better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
工作流定义页面是否可以添加"全部下线"、"全部运行"功能？
当前我们定义的工作流使用的资源每次更新后，需要将任务重启，而目前并没有"全部下线"、"全部运行"的功能，导致每次更新都需要一个个任务重启一遍，工作量巨大，是否可以添加"全部下线"、"全部运行"功能？

**What are the current deficiencies and the benefits of improvement**
不足：当有大量的任务流需要重启时，目前得一个个点击下线再点击运行，工作量巨大
好处：减少重启大量任务流需要消耗的时间

**Which version of DolphinScheduler:**
 -[1.1.0-preview]

**Describe alternatives you've considered**
在工作流页面增加 "全部下线"、"全部运行"功能，只对选中的工作流生效，当用户没有选中工作流时，按钮无法点击或者点击后不触发任何动作

**Comment by yangyichao-mango** [comment]
Good feature, anyone who want to implement this feature, welcome leave a message.

**Comment by liujianhuanzz** [comment]
@yangyichao-mango 
#9239
