### ISSUE TITLE
[Improvement] Is it possible to add a method to automatically delete the process definition after the timing task ends

### ISSUE THREAD

**Issue by opcooc** [apache/dolphinscheduler#3404]
**Describe the question**
When the meeting notification created by calling the api is executed, I need to call the query all interfaces and find the scheduled meeting task that has ended and delete it

**What are the current deficiencies and the benefits of improvement**
- What are the current deficiencies: Third-party users need to periodically delete expired process definitions
- the benefits of improvement: more friendly to the created one-time process tasks

**Describe alternatives you've considered**
- Add corresponding fields in the creation process definition interface, add corresponding radio buttons on the page, and delete the backend after the last task is executed
- The third-party business storage process defines the id, and regularly deletes expired tasks (I am now)

**Comment by yangyichao-mango** [comment]
Please describe the detail and the benefit of this issue. Thx a lot~

**Comment by shenqicheng100** [comment]
> 请描述更多细节以及此问题的好处。非常感谢〜@ yangyichao-mango

OK, wait ！！

**Comment by shenqicheng100** [comment]
> Please describe more detail and the benefit of this issue. Thx a lot~ @yangyichao-mango



> Please describe more detail and the benefit of this issue. Thx a lot~ @yangyichao-mango

corrected

**Comment by hsupu** [comment]
Could you achieve this by existing HTTP APIs?

**Comment by shenqicheng100** [comment]
> 您可以通过现有的HTTP API实现此目标吗？

Realized by using http api now

**Comment by shenqicheng100** [comment]
> 您可以通过现有的HTTP API实现此目标吗？

But I want to have a quick way

**Comment by lenboo** [comment]
I think it's more reasonable to mark the expired process definitions than to delete them automatically. 
that deletion maybe cause some catastrophic errors.

**Comment by shenqicheng100** [comment]
> 我认为标记过期的流程定义比自动删除它们更合理。
> 该删除操作可能会导致一些灾难性的错误。



> 我认为标记过期的流程定义比自动删除它们更合理。
> 该删除操作可能会导致一些灾难性的错误。

It seems feasible to add an expired logo. Is it possible to add a button to filter when the page is displayed to facilitate the distinction
