### ISSUE TITLE
[Improvement][dao] Judge the result status of DDL related operations

### ISSUE THREAD

**Issue by CalvinKirs** [apache/dolphinscheduler#3435]
I noticed that many of our codes do not judge the success status of the execution result (affecting the number of rows) when performing DDL-related operations. In some cases, we should care about its execution status instead of defaulting to its successful execution.
We may want to discuss those situations where we must pay attention, and those situations where we don’t need to pay attention.
Related mail discussion:https://lists.apache.org/thread.html/r24a5adfc43f173493d780c19c4d64788e3069856e4cc82aa0f9ff117%40%3Cdev.dolphinscheduler.apache.org%3E

- [1 ] Summarize to do list
- [2]Finish it
If you are interested, please leave a message

**Comment by yangyichao-mango** [comment]
+1.
