### ISSUE TITLE
[Feature][Server] About deploy Flink task on Yarn-Session deployed flink

### ISSUE THREAD

**Issue by wbxsos** [apache/dolphinscheduler#3441]
When I tried to deploy a flink task on the yarn-session deployed flink ,I got a problem. The command is the same as deploy using local mode(all like 'yarn -c XXXX.class XXX.jar') so I can use the local deploy mode. But when I tried to stop the workflow instance, not the flink job got canceled but the flink on yarn got killed. The reason is that the local deploy mode uses 'yarn -kill application_XXXX' command to stop the job, it works in local deploy mod but not the yarn-session mode. In yarn-session mode, the command should be 'flink stop ${job id} '. In my project the yarn is only deployed in yarn-session mode so I fixed the code to solve the problem for me, but could you add a more 'yarn-session' deploy mode?
What I have done includes finding the yarn job id from the log file and stop the flink job successfully not the yarn application. But the deploy mode para can be read in org.apache.dolphinscheduler.server.utils.ProcessUtils, but cannot be read in org.apache.dolphinscheduler.server.worker.processor.TaskKillProcessor.  In TaskKillProcessor.class , it stops yarn application for all task including flink task, no matter the deploy mode. I still get no idea on how to archive the deploy mode para in 
TaskKillProcessor.class and stop the flink job only for yarn-session mode.

**Comment by yangyichao-mango** [comment]
Yarn session mode flink job actually is a common need, anyone who are interested in implementing this feature, welcome to leave a message.
