### ISSUE TITLE
[Feature][api] Integration with existing platforms(SSO)

### ISSUE THREAD

**Issue by yy0812** [apache/dolphinscheduler#3451]
Integration with existing platforms.

Whenever you commit a task to Dolphinscheduler via the API from a third-party platform, you have to log in to dolphinscheduler to view the task log and status. This can be very cumbersome.

Expect dolphinScheduler to provide SSO to facilitate seamless integration with existing platforms.

**Comment by yangyichao-mango** [comment]
Hi,
I personally think this is a good feature to implement sso, it is a very common need in a lot of companies, but at present, if we want to implement this feature, ds's file privilege, datasource privilege, and tenant mode will have a big changes, so if anyone want to design this feature, welcome to leave a message or send a mail to mailing list.

**Comment by chengshiwen** [comment]
Related issue: #4531

**Comment by Abingcbc** [comment]
I would like to integrate [Casdoor](https://github.com/casdoor/casdoor) which is a powerful SSO platform into DolphinSchduler :)

As mentioned above, integration may make breaking changes. So is there any advice for this work?

**Comment by wuni1010831107** [comment]
Can we consider integrating with knox sso

**Comment by zhongjiajie** [comment]
close by https://github.com/apache/dolphinscheduler/pull/8706
