### ISSUE TITLE
Feature Request: workflow diagram display

### ISSUE THREAD

**Issue by feloxx** [apache/dolphinscheduler#346]
**Is your feature request related to a problem? Please describe.**

-  The problem is that there is no friendly display of dependencies between workflows.

- When the number of workflows increases and the dependency increases, it is inconvenient to debug.

> If a project now has 4/5 dependencies, if one of the nodes fails, the cause of the failure is not because of it, but by other nodes, such as calculation errors, or lost numbers, dirty data or something.
> If you debug it by `list`, it will be very troublesome.

- I think there should be a dependency graph.

---

**Describe the solution you'd like**

- Add dependency diagram page.

- Get dependencies and cycle between workflows, or other information that needs to be displayed.

- Draw a diagram (see neo4j).

---

**Additional context**

The prototype I drew, for your reference.

The views are as follows:

- All points are drawn on the canvas.

- Connect points with dependencies.

- Tile without dependencies.

![gx](https://user-images.githubusercontent.com/8359848/58262537-077da600-7dad-11e9-83d2-8ea1c0d91f10.jpg)

**Comment by dailidong** [comment]
very great idea!

thank you !
