### ISSUE TITLE
[Improvement] [Workflow definition list] Top or sort

### ISSUE THREAD

**Issue by Ylisen** [apache/dolphinscheduler#3489]
**Describe the question**
工作流定义面板中的工作流，能否加个置顶，或排序呢，避免任务太多，老是要翻页。

**Comment by xingchun-chen** [comment]
Thanks for your suggestion, please update the title in English

**Comment by Ylisen** [comment]
Can the workflow in the workflow definition list panel be added to the top or sorted to avoid too many tasks and page turning?
