### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [apache/dolphinscheduler#3546]
https://github.com/apache/incubator-dolphinscheduler/blob/00e0003aed207adc33d1c4068977b172fa21d3f0/dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/upgrade/UpgradeDao.java#L143

https://github.com/apache/incubator-dolphinscheduler/blob/00e0003aed207adc33d1c4068977b172fa21d3f0/dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/upgrade/UpgradeDao.java#L187

https://github.com/apache/incubator-dolphinscheduler/blob/00e0003aed207adc33d1c4068977b172fa21d3f0/dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/upgrade/UpgradeDao.java#L333

https://github.com/apache/incubator-dolphinscheduler/blob/00e0003aed207adc33d1c4068977b172fa21d3f0/dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/upgrade/UpgradeDao.java#L409

The program can potentially fail to release a system resource.

**Comment by dailidong** [comment]
Please submit a PR to solve this problem
