### ISSUE TITLE
[Improvement][alert ] Multiple instances of alert service

### ISSUE THREAD

**Issue by felix-thinkingdata** [apache/dolphinscheduler#3592]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
When two more alert services are started, the alert is repeated

在启动两个alert服务的时候，告警会重复发送

**Comment by zhuangchong** [comment]
Alter Server only supports one node deployment.

---

Alter Server 只支持一个节点部署

**Comment by felix-thinkingdata** [comment]
> Alter server only supports one node deployment. In the source code, the knowledge base database table is queried circularly, and updated after success. At present, this mode does not support multiple alter server instances
> 
> Idea: you can add a status identifier to each record in the database table to be queried, alerted, etc., so that multiple alter server instances can be started
> 
> Alter server只支持一个节点部署,源码里面是循环查询知识库数据库表，成功之后更新。这种模式目前是不支持多个Alter server实例.
> 
> 想法：可以在数据库表里面每条记录增加一个状态标识，被查询、被告警...，这样可以启动多个Alter server实例.

Or if a distributed lock is added during rotation, the two Alert Servers will not read the same record to send

或者在轮训的时候加一个分布式锁，两个alert server就不会读取到相同的记录去发送了

**Comment by gaojun2048** [comment]
What is the final conclusion of this issue?

**Comment by felix-thinkingdata** [comment]
> What is the final conclusion of this issue?

I'd like to take the time to implement this, but some people think that the Alert service is overdesigned.

我想抽时间实现掉，但是有些人认为alert服务多活是过度设计。

**Comment by gaojun2048** [comment]
If the community has reached an agreement, we should respect the community's opinion as much as possible.

如果社区大家达成了一致，我觉得咱还是按最终的结论来，如果没有达成一致咱就继续讨论。

**Comment by felix-thinkingdata** [comment]
> If the community has reached an agreement, we should respect the community's opinion as much as possible.
> 
> 如果社区大家达成了一致，我觉得咱还是按最终的结论来，如果没有达成一致咱就继续讨论。

Ok, so let me cluster boot discussion at National Day.
