### ISSUE TITLE
[Feature] When will flink sql be supported

### ISSUE THREAD

**Issue by Level1Accelerator** [apache/dolphinscheduler#3649]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the feature**
A clear and concise description of what the feature is.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dailidong** [comment]
1.3.x has supported flink， do you mean flink sql? 
By the way, as a global project, English is needed, please update/add title and desc in English.

**Comment by yangyichao-mango** [comment]
I think this can be done as 啊 new feature, anyone who are interested in this feature， welcome leave a message.

**Comment by zhuangchong** [comment]
+1

**Comment by shuitao** [comment]
+1

**Comment by shuitao** [comment]
+1

**Comment by wangqinghuan** [comment]
+1

**Comment by davidzollo** [comment]
is there anybody who can describe this feature?  what do you want to do with flink sql ?

**Comment by wangqinghuan** [comment]
@dailidong  we are using Flink sql to build streaming etl job. It's very convenient if we can write flink sql in DS.

**Comment by nikshe** [comment]
> 

exactly
