### ISSUE TITLE
[Feature]补数时日期填写，建议可文本编辑、日期选择多种填写方式

### ISSUE THREAD

**Issue by wuliulw** [apache/dolphinscheduler#3660]
当补数时间超过多个月时，日期选择空间不方便操作
![image](https://user-images.githubusercontent.com/14256084/92188207-85749c00-ee8e-11ea-9eef-43d1461bf97a.png)

**Comment by break60** [comment]
Currently ui does not support custom editing, we will change the new ui to support this function later

**Comment by wuliulw** [comment]
thanks
