### ISSUE TITLE
In version 1.2.1，The task is killed, but the workflow status shows success

### ISSUE THREAD

**Issue by dataHunterAssassi** [apache/dolphinscheduler#3663]
*For better global communication, please give priority to using English description, thx! *
*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the bug**
I have 30 tasks in a workflow, two of them are killed after the scheduling is completed, but the workflow state is set for success, in this case, the entire workflow state should be the failure state.

**Expected behavior**
when the task is killed，the workflow state is set to failure。

**Screenshots**
![bug1-1](https://user-images.githubusercontent.com/70734374/92194950-6bdb5080-ee9e-11ea-80d8-96cfe3cdc786.png)
![bug1-2](https://user-images.githubusercontent.com/70734374/92194961-71d13180-ee9e-11ea-9996-7c47f550cad1.png)

**Which version of Dolphin Scheduler:**
version：1.2.1

-----------------------------中文描述------------
在1.2.1版本，我一个工作流里有30个任务，调度运行完毕后，其中有两个任务被杀了，但这个工作流的状态却置为了成功，这种情况整个工作流状态应该是失败状态才对的呀。

**Comment by xingchun-chen** [comment]
The workflow should be the kill state, can you describe the operation steps in detail

**Comment by itbasketplayer** [comment]
you should check the code of MasterExecThread#getProcessInstanceState
I encounter the bug in 1.2.1 when I kill the process instance,there are some retry tasks
![image](https://user-images.githubusercontent.com/8638021/93580589-936c0600-f9d2-11ea-8867-161ed11b3f7d.png)

**Comment by caishunfeng** [comment]
This issue will be closed because no update for a long time. You can reopen it if need.
