### ISSUE TITLE
[Feature][datasource] Simply create a new type of data source

### ISSUE THREAD

**Issue by zhuangchong** [apache/dolphinscheduler#3723]
**Describe the feature**
Create a data source, add a new type of data source, directly add the driver class on the page, and store the data source driver package in the lib directory. It is more convenient and flexible to deal with new types of data sources.

**Is your feature request related to a problem? Please describe.**
At present, a new type of data source is newly added, which will involve the modification, compilation, and release of the front-end VUE and the back-end JAVA. There will be many problems and difficulties in this process.

**Describe the solution you'd like**
DS can support new types of data sources. You can add a data source driver class on the page, and store the corresponding data source driver package in the lib directory to use the new data source.

**Additional context**
1. Commonly used data sources, select the data source type, you can bring out the driver class, connect to url information
2. Customize the data source, the user fills in the corresponding driver class, and puts the data source driver package in the lib directory
3. Fill in the data source ip, port and other information to automatically bind the variables on the connection url in both directions
4. Relevant parameter information can be added after connecting to the url

---
**描述功能**
创建数据源，新增一种新类型的数据源，直接在页面添加driver class,lib目录下存放数据源驱动包。在面对新类型的数据源处理起来更方便，灵活。

**您的功能请求与问题有关吗？ 请描述。**
目前新增加一种新的类型数据源，会涉及前端VUE，后端JAVA的修改，编译，发布版本。这过程中会存在很多问题难点。

**描述您想要的解决方案**
DS 可以支持新的类型数据源，可以在页面添加数据源driver class，lib目录下存放相应的数据源驱动包，即可使用新的数据源。

**其他内容**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
1.常用数据源，选择数据源类型，可以带出driver class，连接url 信息
2.自定义数据源，用户填写相应driver class，将数据源驱动包放在lib目录下
3.填写数据源ip,端口等信息可自动在连接url 上变量双向绑定
4.连接url后可以追加相关参数信息

---
选择常用数据源
![Snipaste_2020-09-11_20-16-47](https://user-images.githubusercontent.com/37063904/92925309-e7279e00-f46c-11ea-8de5-a7c516b537e4.png)

填写数据源信息
![Snipaste_2020-09-11_20-18-24](https://user-images.githubusercontent.com/37063904/92925337-f1499c80-f46c-11ea-801f-03bbc75aedba.png)

选择自定义数据源或新类型数据源，数据源信息需要自行填写
![Snipaste_2020-09-11_20-20-36](https://user-images.githubusercontent.com/37063904/92925421-09b9b700-f46d-11ea-9748-4bd24631534f.png)

**Comment by zhuangchong** [comment]
＃1390

**Comment by zhuangchong** [comment]
I will finish it

**Comment by yangyichao-mango** [comment]
+1，any design doc about this feature? It maybe need dynamic load class, if there is design doc, it will be better.
