### ISSUE TITLE
[Question] Is there a way to pass parameters between 2 tasks

### ISSUE THREAD

**Issue by opcooc** [apache/dolphinscheduler#3769]
![image](https://user-images.githubusercontent.com/34977303/93660650-a38fee00-fa83-11ea-96ef-da7019b14435.png)

我想在datax 任务前面加一个获取上次任务执行成功后的时间放在我的where条件上，不知道有大佬知道解决方案吗！！！

**Comment by MiracleTanC** [comment]
有解决方案了吗

**Comment by sirs05** [comment]
建一张表记录任务执行成功时间，在datax任务前面加个sql任务select xxx limit 1，把select出来的东西放进输出参数里面
