### ISSUE TITLE
[Improvement] Conditional judgment node default rules

### ISSUE THREAD

**Issue by break60** [apache/dolphinscheduler#3775]
ds current conditions determine the default rules of the node, regardless of whether the pre-node succeeds or fails, the default is to go successfully
It is recommended that the default rule be judged based on the status of the front node:
1. The conditional judgment node has only one pre-node. If the pre-node status is successful, it will default to the successful branch; if it fails, it will default to the failed branch.
2. The conditional judgment node has multiple pre-nodes. If the pre-node status is all successful, it will take the successful branch by default. If one of the pre-nodes fails, it will take the failed branch.

If you have better suggestions, you can also put them forward, thank you！

ds目前条件判断节点默认规则，不管前置节点成功还是失败默认都是走成功
建议默认规则根据前置节点状态来判断：
1.条件判断节点只有一个前置节点，如果前置节点状态成功，默认走成功分支，如果失败默认走失败分支
2.条件判断节点有多个前置节点，如果前置节点状态全成功，默认走成功分支，如果前置节点有一个失败，则走失败分支

如果您有更好的建议，也可以提出来，谢谢！

**Comment by zhuangchong** [comment]
+1
