### ISSUE TITLE
[Feature][API][backend]  Query all upstream and downstream dependencies of the task

### ISSUE THREAD

**Issue by lgcareer** [apache/dolphinscheduler#3797]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the feature**
In order to view the dependency realations of one task node clearly,It's necessary to query the upstream and downstream dependencies of this task.

1.According to the process definition id and task name, you can get its direct upstream and downstream dependencies.
2.Only need to get the direct dependencies here, instead of recursively querying all the dependencies.
3.Query the dependencies can support three query types.
 - Upstream dependency
 - Downstream dependency
 - Upstream and downstream dependency.

**Design detail**

There is  `process_definiton_json` field in the process definition table. The `tasks` field is a task array that records all tasks. This json needs to be parsed to get the upstream and downstream dependencies of tasks.

![image](https://user-images.githubusercontent.com/15651066/94285812-c5f3a100-ff86-11ea-9dd3-83f071c180b8.png)

**The json structure of tasks**
For the json structure of tasks, you can see the picture below.
![image](https://user-images.githubusercontent.com/15651066/94253467-f112cc00-ff57-11ea-9c31-a98bdfef48a7.png)

**Comment by Somaru-chan** [comment]
Hi. I'm an Outreachy applicant. Is this a good first issue to contribute to? 
Thanks!

**Comment by lgcareer** [comment]
@Somaru-chan Hi,it is the describe about the  "Extend Backend API to Query all up and downstream dependencies of the task - Apache Dolphinscheduler".

**Comment by lgcareer** [comment]
@Somaru-chan #3993 is easy to fix,but it need to fixed today.If you can fixed it today,I think you can do it.If not,you can see the issues #3081

**Comment by lgcareer** [comment]
@iamMujuziMoses Congratulations to you and welcome you selected this feature,if you have any question,you can feel free to ask and discuss here.

**Comment by IamMujuziMoses** [comment]
Thank you @lgcareer @djkevincr, I am looking forward to working on this and accomplishing with your help

**Comment by IamMujuziMoses** [comment]
@lgcareer @djkevincr since this is the describe about the "Extend Backend API to Query all up and downstream dependencies of the task - Apache Dolphinscheduler" are there small tasks I am going to start with for example  [#3801] as am working my way to fixing this?!

[#3801] : https://github.com/apache/incubator-dolphinscheduler/issues/3801

**Comment by lgcareer** [comment]
@IamMujuziMoses So nice,I saw you have submitted the pr.
