### ISSUE TITLE
[Feature][dao] Version upgrade extention, execute the sql from the latest image version not earliest version  to the current version

### ISSUE THREAD

**Issue by lgcareer** [apache/dolphinscheduler#3801]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Background**
If the database is changed in a certain version, the changes will be recorded in this version, and the database will be automatically upgraded when upgrading from a lower version to a higher version.

It also supports the function of initializing the database. Executing create-dolphinscheduler.sh will automatically initialize the database.

Abstracted the database changes into two parts, one is ddl and the other is dml. The changes in dml support transaction rollback; the changes in ddl do not support transaction rollback.

Executing create-dolphinscheduler.sh will first execute the sql in sql/create, and then execute the sql in sql/upgrade one by one,finally database will be initialized.

Now if it's the first time to install dolphinscheduler,execute `script/create-dolphinschduler.sh` will execute the sql from the 
earliest version to the current version step by step.

**Describe the feature**
Now the sql/create is only one,But It has released so many releases,So the sql/create need support multiple mirrors.
Such as if need install the version 1.3.2,The latest image is 1.3.0,so only execute the sql form the version 1.3.0 not the earliest version 1.2.0 to the 1.3.2 version.

- Design Detail
![image](https://user-images.githubusercontent.com/15651066/94281773-a148fa80-ff81-11ea-93ab-c5d6e2da908c.png)

**Comment by IamMujuziMoses** [comment]
@lgcareer can you please explain this in more details, I think I didn't get it very well, thanks

**Comment by IamMujuziMoses** [comment]
@lgcareer @djkevincr This is what am getting, the sql/create needs to support multiple mirrors such that when installing version 1.4.0, iterate through the sql/create and get the mirror closest to 1.4.0 which is 1.3.3 and execute ddl and dml for that version and then update from 1.3.3 to 1.4.0, am I on the right path?!


![Outreachy (2)](https://user-images.githubusercontent.com/49279842/101531044-c60b1680-39a3-11eb-8f9b-719cd049b612.png)

**Comment by lgcareer** [comment]
Yes,you said right.I saw the picture you sent,I want to know if it is only example? or you moved sql/upgrade to sql/create?

**Comment by IamMujuziMoses** [comment]
```quote
Welcome to Gboard clipboard, any text you copy will be saved here.
```

This is an example
