### ISSUE TITLE
[Feature][install] DolphinScheduler Cloudera Manager parcel 

### ISSUE THREAD

**Issue by EricJoy2048** [apache/dolphinscheduler#3804]
At present, most companies use Ambari or Cloudera Manager to manage their big data platform, We already have the ambari plug-in for dolphinscheduler, We need to make a cloudera manager parcel for dolphinscheduler now. Which will help companies that use CDH to better install, deploy and manage Dolphinscheduler clusters.

**Comment by dailidong** [comment]
I like this Feature

**Comment by Fortytwoo** [comment]
I can't find it where parcel is?
