### ISSUE TITLE
定时器模块-定时调度时每7秒|每7分钟|每2天这种定时，不能够跨分钟，跨小时，跨月

### ISSUE THREAD

**Issue by lishiyucn** [apache/dolphinscheduler#3807]
定时器模块-定时调度时每7秒|每7分钟|每2天这种定时，不能够跨分钟，跨小时，跨月

定时调度中
0/59 * * * *  ? *
接下来五次执行时间
2020-09-24 03:58:59
2020-09-24 03:59:00
2020-09-24 03:59:59
2020-09-24 04:00:00
2020-09-24 04:00:59
这不是我想要的调度时间
我想要的是能够跨分钟的状态连续的
2020-09-24 03:58:59
2020-09-24 03:59:58
2020-09-24 04:00:57

同样的问题还出现在小时  天的问题上，每7个小时的调度不能跨越当天的14小时，每9天的调度，不能跨越当月的天数而在下个月继续之前的状态

**Comment by xingchun-chen** [comment]
please update the title in English

**Comment by break60** [comment]
> 定时器模块-定时调度时每7秒|每7分钟|每2天这种定时，不能够跨分钟，跨小时，跨月
> 
> 定时调度中
> 0/59 * * * * ? *
> 接下来五次执行时间
> 2020-09-24 03:58:59
> 2020-09-24 03:59:00
> 2020-09-24 03:59:59
> 2020-09-24 04:00:00
> 2020-09-24 04:00:59
> 这不是我想要的调度时间
> 我想要的是能够跨分钟的状态连续的
> 2020-09-24 03:58:59
> 2020-09-24 03:59:58
> 2020-09-24 04:00:57
> 
> 同样的问题还出现在小时 天的问题上，每7个小时的调度不能跨越当天的14小时，每9天的调度，不能跨越当月的天数而在下个月继续之前的状态

> 2020-09-24 03:58:59
> 2020-09-24 03:59:58
> 2020-09-24 04:00:57
Don't you want this every minute

**Comment by when520** [comment]
> > 定时器模块-定时调度时每7秒|每7分钟|每2天这种定时，不能够跨分钟，跨小时，跨月
> > 定时调度中
> > 0/59 * * * * ? *
> > 接下来五次执行时间
> > 2020-09-24 03:58:59
> > 2020-09-24 03:59:00
> > 2020-09-24 03:59:59
> > 2020-09-24 04:00:00
> > 2020-09-24 04:00:59
> > 这不是我想要的调度时间
> > 我想要的是能够跨分钟的状态连续的
> > 2020-09-24 03:58:59
> > 2020-09-24 03:59:58
> > 2020-09-24 04:00:57
> > 同样的问题还出现在小时 天的问题上，每7个小时的调度不能跨越当天的14小时，每9天的调度，不能跨越当月的天数而在下个月继续之前的状态
> 
> > 2020-09-24 03:58:59
> > 2020-09-24 03:59:58
> > 2020-09-24 04:00:57
> > Don't you want this every minute

Yes, the timer should continue the last scheduler time status.

**Comment by break60** [comment]
> > 定时器模块-定时调度时每7秒|每7分钟|每2天这种定时，不能够跨分钟，跨小时，跨月
> > 定时调度中
> > 0/59 * * * * ? *
> > 接下来五次执行时间
> > 2020-09-24 03:58:59
> > 2020-09-24 03:59:00
> > 2020-09-24 03:59:59
> > 2020-09-24 04:00:00
> > 2020-09-24 04:00:59
> > 这不是我想要的调度时间
> > 我想要的是能够跨分钟的状态连续的
> > 2020-09-24 03:58:59
> > 2020-09-24 03:59:58
> > 2020-09-24 04:00:57
> > 同样的问题还出现在小时 天的问题上，每7个小时的调度不能跨越当天的14小时，每9天的调度，不能跨越当月的天数而在下个月继续之前的状态
> 
> > 2020-09-24 03:58:59
> > 2020-09-24 03:59:58
> > 2020-09-24 04:00:57
> > Don't you want this every minute



> > > 定时器模块-定时调度时每7秒|每7分钟|每2天这种定时，不能够跨分钟，跨小时，跨月
> > > 定时调度中
> > > 0/59 * * * * ? *
> > > 接下来五次执行时间
> > > 2020-09-24 03:58:59
> > > 2020-09-24 03:59:00
> > > 2020-09-24 03:59:59
> > > 2020-09-24 04:00:00
> > > 2020-09-24 04:00:59
> > > 这不是我想要的调度时间
> > > 我想要的是能够跨分钟的状态连续的
> > > 2020-09-24 03:58:59
> > > 2020-09-24 03:59:58
> > > 2020-09-24 04:00:57
> > > 同样的问题还出现在小时 天的问题上，每7个小时的调度不能跨越当天的14小时，每9天的调度，不能跨越当月的天数而在下个月继续之前的状态
> > 
> > 
> > > 2020-09-24 03:58:59
> > > 2020-09-24 03:59:58
> > > 2020-09-24 04:00:57
> > > Don't you want this every minute
> 
> Yes, the timer should continue the last scheduler time status.

You can set the time rule by yourself. The default time rule is to execute every second. You can set it to every minute, every hour, every week, every month..., the first few days of the month are fine.

**Comment by when520** [comment]
> > > 定时器模块-定时调度时每7秒|每7分钟|每2天这种定时，不能够跨分钟，跨小时，跨月
> > > 定时调度中
> > > 0/59 * * * * ? *
> > > 接下来五次执行时间
> > > 2020-09-24 03:58:59
> > > 2020-09-24 03:59:00
> > > 2020-09-24 03:59:59
> > > 2020-09-24 04:00:00
> > > 2020-09-24 04:00:59
> > > 这不是我想要的调度时间
> > > 我想要的是能够跨分钟的状态连续的
> > > 2020-09-24 03:58:59
> > > 2020-09-24 03:59:58
> > > 2020-09-24 04:00:57
> > > 同样的问题还出现在小时 天的问题上，每7个小时的调度不能跨越当天的14小时，每9天的调度，不能跨越当月的天数而在下个月继续之前的状态
> > 
> > 
> > > 2020-09-24 03:58:59
> > > 2020-09-24 03:59:58
> > > 2020-09-24 04:00:57
> > > Don't you want this every minute
> 
> > > > 定时器模块-定时调度时每7秒|每7分钟|每2天这种定时，不能够跨分钟，跨小时，跨月
> > > > 定时调度中
> > > > 0/59 * * * * ? *
> > > > 接下来五次执行时间
> > > > 2020-09-24 03:58:59
> > > > 2020-09-24 03:59:00
> > > > 2020-09-24 03:59:59
> > > > 2020-09-24 04:00:00
> > > > 2020-09-24 04:00:59
> > > > 这不是我想要的调度时间
> > > > 我想要的是能够跨分钟的状态连续的
> > > > 2020-09-24 03:58:59
> > > > 2020-09-24 03:59:58
> > > > 2020-09-24 04:00:57
> > > > 同样的问题还出现在小时 天的问题上，每7个小时的调度不能跨越当天的14小时，每9天的调度，不能跨越当月的天数而在下个月继续之前的状态
> > > 
> > > 
> > > > 2020-09-24 03:58:59
> > > > 2020-09-24 03:59:58
> > > > 2020-09-24 04:00:57
> > > > Don't you want this every minute
> > 
> > 
> > Yes, the timer should continue the last scheduler time status.
> 
> You can set the time rule by yourself. The default time rule is to execute every second. You can set it to every minute, every hour, every week, every month..., the first few days of the month are fine.

我想你可能没明白我的意思，我是想继续上次的调度状态，比如我想每59分钟执行一次，在10点59分执行一次，下次执行是在11点58分，再下一次是在12点的57分

**Comment by break60** [comment]
> > > > 定时器模块-定时调度时每7秒|每7分钟|每2天这种定时，不能够跨分钟，跨小时，跨月
> > > > 定时调度中
> > > > 0/59 * * * * ? *
> > > > 接下来五次执行时间
> > > > 2020-09-24 03:58:59
> > > > 2020-09-24 03:59:00
> > > > 2020-09-24 03:59:59
> > > > 2020-09-24 04:00:00
> > > > 2020-09-24 04:00:59
> > > > 这不是我想要的调度时间
> > > > 我想要的是能够跨分钟的状态连续的
> > > > 2020-09-24 03:58:59
> > > > 2020-09-24 03:59:58
> > > > 2020-09-24 04:00:57
> > > > 同样的问题还出现在小时 天的问题上，每7个小时的调度不能跨越当天的14小时，每9天的调度，不能跨越当月的天数而在下个月继续之前的状态
> > > 
> > > 
> > > > 2020-09-24 03:58:59
> > > > 2020-09-24 03:59:58
> > > > 2020-09-24 04:00:57
> > > > Don't you want this every minute
> > 
> > 
> > > > > 定时器模块-定时调度时每7秒|每7分钟|每2天这种定时，不能够跨分钟，跨小时，跨月
> > > > > 定时调度中
> > > > > 0/59 * * * * ? *
> > > > > 接下来五次执行时间
> > > > > 2020-09-24 03:58:59
> > > > > 2020-09-24 03:59:00
> > > > > 2020-09-24 03:59:59
> > > > > 2020-09-24 04:00:00
> > > > > 2020-09-24 04:00:59
> > > > > 这不是我想要的调度时间
> > > > > 我想要的是能够跨分钟的状态连续的
> > > > > 2020-09-24 03:58:59
> > > > > 2020-09-24 03:59:58
> > > > > 2020-09-24 04:00:57
> > > > > 同样的问题还出现在小时 天的问题上，每7个小时的调度不能跨越当天的14小时，每9天的调度，不能跨越当月的天数而在下个月继续之前的状态
> > > > 
> > > > 
> > > > > 2020-09-24 03:58:59
> > > > > 2020-09-24 03:59:58
> > > > > 2020-09-24 04:00:57
> > > > > Don't you want this every minute
> > > 
> > > 
> > > Yes, the timer should continue the last scheduler time status.
> > 
> > 
> > You can set the time rule by yourself. The default time rule is to execute every second. You can set it to every minute, every hour, every week, every month..., the first few days of the month are fine.
> 
> 我想你可能没明白我的意思，我是想继续上次的调度状态，比如我想每59分钟执行一次，在10点59分执行一次，下次执行是在11点58分，再下一次是在12点的57分

If you change the minutes to execute every 59 minutes, will it meet your needs?
改成每隔59分钟执行不就满足你的需求了么

**Comment by when520** [comment]
我尝试使用dolphinscheduler框架现在实现的cron表达式无法实现状态的继续，您知道怎么利用现在的机制去实现我上边的描述吗？

**Comment by break60** [comment]
> 我尝试使用dolphinscheduler框架现在实现的cron表达式无法实现状态的继续，您知道怎么利用现在的机制去实现我上边的描述吗？
The logic of cron is that if it exceeds 60, it will be reset. At the beginning of the time you set, every 59 will cause the next execution to exceed 60. You can set it to execute every 2 minutes. Starting from 30 minutes, you probably know cron Logic
cron的逻辑是如果超过60就会重置，重你设置的时间的开始，每隔59都会导致下次执行超过60，你可以设置每隔2分钟执行，从30分钟开始，你就大概知道cron的逻辑

**Comment by break60** [comment]
> > 我尝试使用dolphinscheduler框架现在实现的cron表达式无法实现状态的继续，您知道怎么利用现在的机制去实现我上边的描述吗？
> > The logic of cron is that if it exceeds 60, it will be reset. At the beginning of the time you set, every 59 will cause the next execution to exceed 60. You can set it to execute every 2 minutes. Starting from 30 minutes, you probably know cron Logic
> > cron的逻辑是如果超过60就会重置，下个周期从你设置的时间的开始，每隔59都会导致下次执行超过60，你可以设置每隔2分钟执行，从30分钟开始，你就大概知道cron的逻辑

In addition, I want to know what kind of business needs you need to implement in this way
另外，我想知道你们哪种业务场景，需要采用这种方式执行

**Comment by when520** [comment]
> > 我尝试使用dolphinscheduler框架现在实现的cron表达式无法实现状态的继续，您知道怎么利用现在的机制去实现我上边的描述吗？
> > The logic of cron is that if it exceeds 60, it will be reset. At the beginning of the time you set, every 59 will cause the next execution to exceed 60. You can set it to execute every 2 minutes. Starting from 30 minutes, you probably know cron Logic
> > cron的逻辑是如果超过60就会重置，下个周期从你设置的时间的开始，每隔59都会导致下次执行超过60，你可以设置每隔2分钟执行，从30分钟开始，你就大概知道cron的逻辑

问题时我需要每7分钟执行，每13分钟执行这种周期，而且是需要能够跨小时持续状态的，dolphinscheduler可以实现吗？
感觉很多场景的调度周期都无法实现

**Comment by when520** [comment]
> > > 我尝试使用dolphinscheduler框架现在实现的cron表达式无法实现状态的继续，您知道怎么利用现在的机制去实现我上边的描述吗？
> > > The logic of cron is that if it exceeds 60, it will be reset. At the beginning of the time you set, every 59 will cause the next execution to exceed 60. You can set it to execute every 2 minutes. Starting from 30 minutes, you probably know cron Logic
> > > cron的逻辑是如果超过60就会重置，下个周期从你设置的时间的开始，每隔59都会导致下次执行超过60，你可以设置每隔2分钟执行，从30分钟开始，你就大概知道cron的逻辑
> 
> In addition, I want to know what kind of business needs you need to implement in this way
> 另外，我想知道你们哪种业务场景，需要采用这种方式执行

1.比如我们需要程序调起来的时候用当前的时间戳，往前倒20分钟，来确定读取的时间范围。
2.调度的程序就是需要持续之前的调度状态，但我们的dolphinscheduler就是不支持这样，很多调度平台都支持俩种定时器，一个是cron表达式，另外一种是可以持续状态的调度。

**Comment by break60** [comment]
> > > > 我尝试使用dolphinscheduler框架现在实现的cron表达式无法实现状态的继续，您知道怎么利用现在的机制去实现我上边的描述吗？
> > > > The logic of cron is that if it exceeds 60, it will be reset. At the beginning of the time you set, every 59 will cause the next execution to exceed 60. You can set it to execute every 2 minutes. Starting from 30 minutes, you probably know cron Logic
> > > > cron的逻辑是如果超过60就会重置，下个周期从你设置的时间的开始，每隔59都会导致下次执行超过60，你可以设置每隔2分钟执行，从30分钟开始，你就大概知道cron的逻辑
> > 
> > 
> > In addition, I want to know what kind of business needs you need to implement in this way
> > 另外，我想知道你们哪种业务场景，需要采用这种方式执行
> 
> 1.比如我们需要程序调起来的时候用当前的时间戳，往前倒20分钟，来确定读取的时间范围。
> 2.调度的程序就是需要持续之前的调度状态，但我们的dolphinscheduler就是不支持这样，很多调度平台都支持俩种定时器，一个是cron表达式，另外一种是可以持续状态的调度。

At present, the ds you mentioned is really not supported. I think the question you raised is very good. In addition, do you have any good implementation plans and suggestions for supporting the continuous state? We will improve this function in the future
目前，你说的这个ds确实是不支持，我觉的你提的这个问题非常好，另外，你对支持持续状态有什么好的实现方案和建议么，后续我们将对这个功能进行改进

**Comment by Ylisen** [comment]
使用动态时间变量和定时结合，说不定可以呢
