### ISSUE TITLE
[Feature][Module Name] 任务管理添加任务分层管理功能

### ISSUE THREAD

**Issue by jon-qj** [apache/dolphinscheduler#3811]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the feature**
A clear and concise description of what the feature is.
![image](https://user-images.githubusercontent.com/39773194/94111043-1b8c5880-fe76-11ea-9127-5295111313e6.png)
任务管理item下可以添加子item ，便于用来分层管理任务所属
类似于 数仓分层 ods->dwd 这样数仓ods的任务创建在ods目录中 数仓dwd的任务创建在dwd目录中，阔以添加dwd某个任务依赖,依赖于ods中的某个任务 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yangyichao-mango** [comment]
We are doing the tag feature. Will this feature help you?

**Comment by jon-qj** [comment]
Actually, I’m used to use the file folders to manage my scripts clearly,it makes me look for some file directly.
 
 
 
 
 
 
 
 
 

  -- 
 
 
 发自新浪邮箱客户端 
 
 
  
  在 9月26日 18:54，Yichao Yang <notifications@github.com> 写道： 
   
  We are doing the tag feature. Will this feature help you?

**Comment by mrhaoqi** [comment]
@yangyichao-mango Is this feature complete? the tag feature
