### ISSUE TITLE
[Feature]global parameters can support adding configuration based on the project

### ISSUE THREAD

**Issue by acongfly** [apache/dolphinscheduler#3814]
The current variable parameters can only be added in DAG tasks. If I have multiple DAG sequences in a project, all of them need to be configured.
If I have multiple production machines, I have a lot of tasks, and I don't want to concentrate all tasks on one IP. For example: now our system does not seem to know HTTP load balancing.
Expectation: At this time, I hope I can configure an ip for the project, so that when I switch from the development environment to the production environment, I can greatly reduce the number of modifications I have, and if someone goes offline, I can quickly change the ip . Of course, if you support dynamic IP replacement later, it is of course the best to download the broken machine.

现在的全局参数只在DAG任务中可以添加，如果我一个项目有多个DAG序列，这样都需要配置。
举个例子：现在咱们这个系统好像也不知道HTTP的负载均衡。如果我有多台生产机器，我任务也蛮多的，我不想把所有的任务都集中到一个ip上。
期望：这个时候我希望我可以针对项目可以配置一个全局ip，这样我后面可以从开发环境切换到生产环境的时候可以大大减少我修改的次数，而且如果某台机器下线，我可以快速的更换ip.当然如果后面支持动态更换ip,下掉坏掉的机器当然是最好的。

**Comment by CalvinKirs** [comment]
For better communication, please use English, thx

**Comment by ntupapaya** [comment]
hope this feature+1
