### ISSUE TITLE
Can DolphinScheduler support PRC and restful task?

### ISSUE THREAD

**Issue by wy-coder** [apache/dolphinscheduler#384]
If the task supports RPC, such as Dubbo, restful and other remote calls, it can become an excellent batch task scheduling framework, which is exactly what we need.

Plus timed tasks. . perfect

---
如果任务支持RPC，如Dubbo，restful等远程调用，就可以变成一个优秀的批量任务调度框架，这正是我们所需要的。

再加上定时任务。。完美

**Comment by dailidong** [comment]
good idea!

Are you interested in implementing this, and contributing code?

**Comment by dailidong** [comment]
the similar issue  #204  support the task type of http
