### ISSUE TITLE
When the dolphinscheduler connects with spark thriftserver to execute SQL, the dynamic partition is not successful, and the data does not enter the target partition table. No error is prompted. The task is completed in an instant and is shown to be successful

### ISSUE THREAD

**Issue by Zosimer** [apache/dolphinscheduler#3855]
### **sql:**
set hive.exec.dynamic.partition=true;
set hive.exec.dynamic.partition.mode=nonstrict;
set hive.exec.max.dynamic.partitions.pernode=600000;
set hive.exec.max.dynamic.partitions=6000000;
set hive.exec.max.created.files=6000000;
set spark.sql.adaptive.enabled=true;
set spark.sql.adaptive.shuffle.targetPostShuffleInputSize=134217728;
set spark.sql.adaptive.join.enabled=true;
set spark.sql.autoBroadcastJoinThreshold=20971520;
set spark.sql.hive.mergeFiles=true; 
INSERT overwrite TABLE ods.ods_app_report_vo PARTITION(month,day)
    select 
    `_id` ,
    `hid` ,
    `coid`,
    `csid`,
    `eqid`,
    `type`,
    `timestamp`,
    `date`,
    `status`,
    `roomid`,
    `errmsg`,
    `_class`,
    substr(a.`date`,1,7) as month,
    a.`day`
    from ods.ods_app_report_vo_day as a  
  where a.`day` = '2020-09-29' distribute by rand();

### ** all-worker-log：**
[INFO] 2020-09-30 22:10:11.946  - [taskAppId=TASK-9-33-196]:[104] - Full sql parameters: SqlParameters{type='SPARK', datasource=1, sql='set hive.exec.dynamic.partition=true;
set hive.exec.dynamic.partition.mode=nonstrict;
set hive.exec.max.dynamic.partitions.pernode=600000;
set hive.exec.max.dynamic.partitions=6000000;
set hive.exec.max.created.files=6000000;
set spark.sql.adaptive.enabled=true;
set spark.sql.adaptive.shuffle.targetPostShuffleInputSize=134217728;
set spark.sql.adaptive.join.enabled=true;
set spark.sql.autoBroadcastJoinThreshold=20971520;
set spark.sql.hive.mergeFiles=true; 
INSERT overwrite TABLE ods.ods_app_report_vo PARTITION(month,day)
    select 
    `_id` ,
    `hid` ,
    `coid`,
    `csid`,
    `eqid`,
    `type`,
    `timestamp`,
    `date`,
    `status`,
    `roomid`,
    `errmsg`,
    `_class`,
    substr(a.`date`,1,7) as month,
    a.`day`
    from ods.ods_app_report_vo_day as a  
  where a.`day` = '2020-09-29' distribute by rand();
', sqlType=1, udfs='', showType='TABLE', connParams='', title='', receivers='', receiversCc='', preStatements=[], postStatements=[]}
[INFO] 2020-09-30 22:10:11.948  - [taskAppId=TASK-9-33-196]:[105] - sql type : SPARK, datasource : 1, sql : set hive.exec.dynamic.partition=true;
set hive.exec.dynamic.partition.mode=nonstrict;
set hive.exec.max.dynamic.partitions.pernode=600000;
set hive.exec.max.dynamic.partitions=6000000;
set hive.exec.max.created.files=6000000;
set spark.sql.adaptive.enabled=true;
set spark.sql.adaptive.shuffle.targetPostShuffleInputSize=134217728;
set spark.sql.adaptive.join.enabled=true;
set spark.sql.autoBroadcastJoinThreshold=20971520;
set spark.sql.hive.mergeFiles=true; 
INSERT overwrite TABLE ods.ods_app_report_vo PARTITION(month,day)
    select 
    `_id` ,
    `hid` ,
    `coid`,
    `csid`,
    `eqid`,
    `type`,
    `timestamp`,
    `date`,
    `status`,
    `roomid`,
    `errmsg`,
    `_class`,
    substr(a.`date`,1,7) as month,
    a.`day`
    from ods.ods_app_report_vo_day as a  
  where a.`day` = '2020-09-29' distribute by rand();
 , localParams : [],udfs : ,showType : TABLE,connParams : 
[INFO] 2020-09-30 22:10:11.949  - [taskAppId=TASK-9-33-196]:[499] - after replace sql , preparing : set hive.exec.dynamic.partition=true;
set hive.exec.dynamic.partition.mode=nonstrict;
set hive.exec.max.dynamic.partitions.pernode=600000;
set hive.exec.max.dynamic.partitions=6000000;
set hive.exec.max.created.files=6000000;
set spark.sql.adaptive.enabled=true;
set spark.sql.adaptive.shuffle.targetPostShuffleInputSize=134217728;
set spark.sql.adaptive.join.enabled=true;
set spark.sql.autoBroadcastJoinThreshold=20971520;
set spark.sql.hive.mergeFiles=true; 
INSERT overwrite TABLE ods.ods_app_report_vo PARTITION(month,day)
    select 
    `_id` ,
    `hid` ,
    `coid`,
    `csid`,
    `eqid`,
    `type`,
    `timestamp`,
    `date`,
    `status`,
    `roomid`,
    `errmsg`,
    `_class`,
    substr(a.`date`,1,7) as month,
    a.`day`
    from ods.ods_app_report_vo_day as a  
  where a.`day` = '2020-09-29' distribute by rand();

[INFO] 2020-09-30 22:10:11.950  - [taskAppId=TASK-9-33-196]:[504] - Sql Params are replaced sql , parameters:
[INFO] 2020-09-30 22:10:11.950  - [taskAppId=TASK-9-33-196]:[52] - can't find udf function resource
[INFO] 2020-09-30 22:10:12.010  - [taskAppId=TASK-9-33-196]:[418] - prepare statement replace sql : org.apache.hive.jdbc.HivePreparedStatement@6fa8ce01

**Comment by geosmart** [comment]
please check the worker log, you may find same error message

**Comment by xingchun-chen** [comment]
please update the title in English

**Comment by zosimer** [comment]
Using the spark SQL client to execute the SQL is successful

**Comment by zosimer** [comment]
dolphinscheduler1.3.2

**Comment by zosimer** [comment]
The same is true of hivesql

**Comment by QQhuxuhui** [comment]
Because you have enabled the file merging configuration, once the calculation task is completed in HSQL or SparkSQL, the client assumes that the task has finished, and the scheduling platform also considers the task as completed. However, due to the file merging being enabled, the server will start a new task to merge the files, and data cannot be queried until the file merging task is completed. If your computation workload is large, the time taken for file merging will be longer.
