### ISSUE TITLE
[Feature][DataX] Incrementally synchronize data 

### ISSUE THREAD

**Issue by Jerry-lin** [apache/dolphinscheduler#3886]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the feature**
A clear and concise description of what the feature is.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BoYiZhang** [comment]
Incrementally synchronize data .

This depends on the specific configuration of dataX

Scheduling just executes the dataX command to start the task [Python datax.py {YOUR_ JOB.json }] ,
