### ISSUE TITLE
[工作流][datax节点] ，datax的json配置动态传参建议

### ISSUE THREAD

**Issue by 939598604** [apache/dolphinscheduler#3916]
在datax节点使用自定义模板的json方式，按照shell的传参方式定义了参数值，datax的json配置文件似乎接收不到用户自定义的参数
![image](https://user-images.githubusercontent.com/18730596/96077306-07220580-0ee2-11eb-9b00-e5f43356dff7.png)
运行日志
![image](https://user-images.githubusercontent.com/18730596/96077357-2751c480-0ee2-11eb-9078-56ce9515fbc1.png)
期望：符合datax官方的动态传参方式，用户自定义的参数可以传递到json中

**Comment by dailidong** [comment]
please first English, then you can append description in Chinese

please referer https://github.com/apache/incubator-dolphinscheduler/issues/3914

**Comment by you10906** [comment]
@939598604  you should  use { } to enclose parameter, eg: ${dt}

**Comment by CalvinKirs** [comment]
Hi, has this issue been resolved?

**Comment by wangshubing1** [comment]
![image](https://user-images.githubusercontent.com/35355246/169001694-b2f39e73-2273-439d-8138-23887391956c.png)
我想的是这些参数，是不是可以统一的去配置中心读取，这样加假如数据库连接发生变化，我们只需要更改配置中心的数据连接配置；而不是手动的进入每一个任务流里去改相关的数据库连接参数

**Comment by davidzollo** [comment]
English is needed
