### ISSUE TITLE
[Feature][Server]depend task wait all the time when the dependent tasks have not been start 

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#3973]
now the depend task would failed when  dependent tasks have not been started. in this case, the execution time of the dependent task needs to be calculated manually.
so I suggest that it should be changed to wait for the execution of the dependent task to finish, it does not matter whether the dependent tasks have been started or not. 
On the other hand, we can use the timeout feature to provide it to people who need to limit the dependent task waiting time.

目前当被依赖的任务没有启动的时候，依赖任务会直接失败，这种情况需要人为计算被依赖任务的执行时间。
所以我建议修改为一直等待被依赖任务执行结束，被依赖任务有没有启动就不重要了。
另一方面，我们可以提供超时时间这个功能给有需要限制等待时间的人们

**Comment by liukunyuan** [comment]
very good

**Comment by wushubo916** [comment]
现在我也遇到这个问题了，正常来说应该是依赖任务等待被依赖的任务，而不是直接就失败了

**Comment by dataHunterAssassi** [comment]
+1，When a dependent task is waiting for a dependent task, it should wait all the time instead of failing directly。
