### ISSUE TITLE
[Feature][FLINK-SQL] The support of the big data scheduling system for flink sql is an important feature.

### ISSUE THREAD

**Issue by hermeshephaestus** [apache/dolphinscheduler#3983]
As a stream computing framework with excellent performance, flink is used more and more in business. DS's support for flink sql can improve its capabilities.

For the support of flink sql, I will give the design first, and discuss it in the email, and then implement it.

**Comment by yangyichao-mango** [comment]
good job，if you design it，you can put your design in this issue comment.

**Comment by hermeshephaestus** [comment]
the main design below:
![DS-FLINK-DESIGN](https://user-images.githubusercontent.com/42707541/97470184-3759b180-1982-11eb-9753-a317fe7c918e.png)
