### ISSUE TITLE
[Question][MASTER]Subtasks are nested and cannot be executed correctly when scheduled

### ISSUE THREAD

**Issue by hujiang75277381** [apache/dolphinscheduler#3991]
问题重现：
1.流程设计 A流程(子任务节点,关联B流程) 、B流程（子任务节点,关联C流程）、C流程（包含shell节点）
2.在流程A [调度执行] 产生的实例上点击重跑,无法执行B流程以及C流程

**Comment by yangyichao-mango** [comment]
At present，the cascaded rerun is not supported， If you are interested in this feature，you can create an issue about this feature and describe what the feature you needed. Thx a lot～

**Comment by xingchun-chen** [comment]
which version?

**Comment by caishunfeng** [comment]
This issue will be closed because no update for a long time.
