### ISSUE TITLE
[Bug][export] after importing an export-json which process contained a sub_process from another environment,the link for sub_process in process is wrong

### ISSUE THREAD

**Issue by ElapsedSoul** [apache/dolphinscheduler#4002]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the bug**
after importing an export-json which process contained a sub_process from another environment,the link for sub_process in process is wrong

**To Reproduce**
1. Go to 'process definition'
2. Export a process who contained a sub_process and all its sub processes
3. Login in  another environment
4. Import the export-json

**Expected behavior**
Right sub process link in right node typed sub_process 

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[1.3.2]

**Additional context**
I think the reason for this is that the identifiers used to link sub process to their master process are different when import the json

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by caishunfeng** [comment]
This issue will be closed because no update for a long time. You can check it again in latest version and reopen it if need.
