### ISSUE TITLE
[Bug][Server] The master does not perform fault tolerance the running process instance 

### ISSUE THREAD

**Issue by zixi0825** [apache/dolphinscheduler#4018]
**Describe the bug**
When the process1 is running on master1, and master1 goes down, and master2 monitors that master1 was down, but the process1 is not fault-tolerant.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. startup master1 and master2
2. start one process
3. find the master who is manager the running process
4. shutdown the master

**Expected behavior**
Another master monitor the master was downed ，find the processes that the master is managing，do the fault tolerance

**Screenshots**
When the master1 goes down，process is always stay running state
![image](https://user-images.githubusercontent.com/10829956/97963165-90e23600-1df1-11eb-97c4-fbfa47a78d5a.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by xingchun-chen** [comment]
It can be verified in version 1.3.3, or after 1.3.3 merged into the dev branch to verify

**Comment by xingchun-chen** [comment]
Have you tested the latest dev code?

**Comment by caishunfeng** [comment]
This issue will be closed because no update for a long time.
