### ISSUE TITLE
[Feature][ProcessDefinition] Support  Visual drag and drop fields when using Datax. 

### ISSUE THREAD

**Issue by github24518** [apache/dolphinscheduler#4028]
module： ProcessDefinition 
Feature request： Support  Visual drag and drop fields when using Datax. 
It is like Alibaba dataworks data integration visualization operation。
![image](https://user-images.githubusercontent.com/40057497/98200520-bf365180-1f68-11eb-9dc7-cacb0199ee52.png)

**Comment by zhuangchong** [comment]
Good idea. Welcome to submit PR.

**Comment by github24518** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
