### ISSUE TITLE
A task that is killed cannot fail to retry

### ISSUE THREAD

**Issue by HaoRanCang** [apache/dolphinscheduler#4039]
*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the bug**
如果一个task被系统kill掉或者手动kill掉,该任务不会进行失败重试,此时task的状态是kill而不是失败

If a task is killed by the system or killed manually, the task will not fail to retry. At this time, the state of the task is kill instead of failure

**To Reproduce**
Steps to reproduce the behavior, for example:
1. 启动工作流，对task设置失败重试次数
    Start the workflow and set the number of failed retries for the Task
2. kill掉其中的一个task进程
    Kill one of the task processes
3.工作流状态显示失败，task状态显示kill，没有重试
   Workflow status display failed,task status display kill, no retry

**Expected behavior**
对于kill掉的task执行失败重试
Try again for kill off task execution failure

**Which version of Dolphin Scheduler:**
 -[1.3.2-release]

**Comment by xingchun-chen** [comment]
Failure retry is for tasks rather than process instances. Killing tasks will not retry. Only tasks that fail to run will be retried.

**Comment by HaoRanCang** [comment]
> Failure retry is for tasks rather than process instances. Killing tasks will not retry. Only tasks that fail to run will be retried.
因为某些原因被系统kill掉的任务不算执行失败么？应该被kill掉的任务也要重试。
Does a task that is killed by the system for some reason not count as a failure? Tasks that should be killed should also be retried.

**Comment by xingchun-chen** [comment]
lKill state is not good to distinguish between human and system kill

**Comment by HaoRanCang** [comment]
> lKill state is not good to distinguish between human and system kil

**Comment by HaoRanCang** [comment]
> lKill state is not good to distinguish between human and system kill

应该让手动kill和系统kill的task状态设置为失败，但是在UI上手动停止的task设置为停止状态而不是kill状态。
The task status of manual kill and system kill should be set to failed, but the task manually stopped on the UI should be set to the stopped state instead of the kill state.

**Comment by caishunfeng** [comment]
This issue will be closed. The kill task state had changed and you can check it in latest version. Thanks.
