### ISSUE TITLE
[Question] Can I use DolphinScheduler to view the logs of Flink or Spark cluster tasks?

### ISSUE THREAD

**Issue by luohy15** [apache/dolphinscheduler#4062]
**Describe the question**
I use DolphinScheduler to submit Spark and Flink tasks, found that the following task view log has task running output:
- Spark on local
- Spark on yarn(client)
![ds-spark-local](https://user-images.githubusercontent.com/15189961/98921820-adc2eb80-250c-11eb-8454-28cfa18744fe.png)

The following task view logs only have JobID (or ApplicationID or no running output):
- Flink on local
- Spark on yarn (cluster)
![ds-flink-local](https://user-images.githubusercontent.com/15189961/98921829-b1567280-250c-11eb-9b89-3a23e1cd984f.png)

So I can only manually open the page of Flink or Yarn to view the logs. I hope to view the output of these tasks more conveniently.

---

我使用 DolphinScheduler 提交 Spark 和 Flink 任务，发现以下任务查看日志有任务运行输出：
- Spark on local
- Spark on yarn(client)

以下任务查看日志仅有 JobID （或ApplicationID或无运行输出），
- Flink on local
- Spark on yarn（cluster）

所以我只能手动打开 Flink 或 Yarn 的页面查看日志，我希望能更方便地查看这些任务的运行输出。

**Versions**
- DolphinScheduler: 1.3.2
- Spark: 2.3.2
- Flink: 1.11.2

**Requirement or improvement**
Does DolphinScheduler (v1.3.2 or dev) support log viewing of these tasks? If not, is there a plan for implementation?
If it is to be implemented, the implementation strategy is to configure the front-end jump (such as #851, #853), or grab the log and save it in the DolphinScheduler system?

---

DolphinScheduler（v1.3.2或dev）是否支持这些任务的日志查看?  如果不支持，是否有实现计划？
如果要实现，实现策略是配置前端跳转（如#851，#853），还是抓取日志存到 DolphinScheduler 系统里？

**Comment by chengshiwen** [comment]
There is currently no better way to solve this problem

**Comment by stukid** [comment]
Has dolphin solved this problem?

**Comment by TheWindIsRising** [comment]
调度spark任务的时候怎么在任务实例日志中查看到更详细的日志，show的代码部分不显示

**Comment by davidzollo** [comment]
Is there any guys who‘d like to implement the feature of showing yarn task log? A simple solution is to add a task link that jumps to yarn, and it feels like there is no need to capture yarn logs to DS.
