### ISSUE TITLE
[DOCS][SPI] SPI-DOCS

### ISSUE THREAD

**Issue by CalvinKirs** [apache/dolphinscheduler#4068]
Hi, everybody.
The design and development of SPI in the DolphinScheduler community has already begun, and the development of Alert spi is about to be completed. Therefore, we need relevant documents to tell users how to develop spi. We hope that interested friends in the community can participate in this work. If you are interesting this research, you can leave a comment below. thank you very much.

You can take Alert spi as an example to write an article about the implementation of alert spi.

Please note: This is an article for users, so we don’t need to tell users too many implementation details, just tell users how to customize the plug-in development.

Related code reference:
https://github.com/apache/incubator-dolphinscheduler/tree/alert_plugin_design

https://github.com/apache/incubator-dolphinscheduler/blob/alert_plugin_design/dolphinscheduler-alert/src/main/resources/alert.properties

https://github.com/apache/incubator-dolphinscheduler/tree/alert_plugin_design/dolphinscheduler-alert-plugin

https://github.com/apache/incubator-dolphinscheduler/tree/alert_plugin_design/dolphinscheduler-spi

To-do list

- [ ] Chinese document

- [ ] English document

**Comment by CalvinKirs** [comment]
I will complete the work on the Chinese document

**Comment by Tianqi-Dotes** [comment]
will do the English doc
