### ISSUE TITLE
[Feature][DataX] When configuring the dataX task, it is recommended to customize the template user password encryption

### ISSUE THREAD

**Issue by iyeeku** [apache/dolphinscheduler#4074]
When configuring the dataX task, it is recommended to customize the template user password encryption
[配置dataX任务时，建议自定义模板用户密码可以加密处理。
![datax](https://user-images.githubusercontent.com/28862440/99356686-7fb32200-28e5-11eb-80ed-4986c49ffdfa.png)

**Comment by CalvinKirs** [comment]
Is the encryption algorithm customized by the user?

**Comment by zhuangchong** [comment]
The Datax custom template itself does not support the password encryption operation of plug-ins. When I used it on other scheduling platforms, I introduced the reader/ Writer variable on the custom template, and the reader/ Writer variable was defined in the data source management interface. What ideas do you have? Welcome to discuss and implement.

---
datax 自定义模版本身是不支持插件的密码加密操作，我在其他调度平台上，使用的时候是在自定义模版上引入reader/writer变量，reader/writer变量在数据源管理界面定义。您有什么想法，欢迎进行讨论，实现。

**Comment by snycc15** [comment]
在shell脚本或SQL脚本中，连接串需要给出密码且都是明文方式，建议增加自定义变量密文处理变量值，如此SHELL等脚本中可直接引用变量。

**Comment by felix-thinkingdata** [comment]
> 在shell脚本或SQL脚本中，连接串需要给出密码且都是明文方式，建议增加自定义变量密文处理变量值，如此SHELL等脚本中可直接引用变量。

The password is encrypted in the run log

**Comment by felix-thinkingdata** [comment]
> 在shell脚本或SQL脚本中，连接串需要给出密码且都是明文方式，建议增加自定义变量密文处理变量值，如此SHELL等脚本中可直接引用变量。

I am doing automatic configuration generation. The generated template will associate data source information. This part of user name and password can be obtained from the associated data source during the execution of task.

我在做配置自动生成，生成的模板，会关联数据源信息，这部分用户名密码可以在task执行过程中，通过关联的数据源拿到。

**Comment by snycc15** [comment]
下一个版本会包含这项特性吗？
