### ISSUE TITLE
FAILED: ParseException line 20:22 cannot recognize input near ''20201123'' '+' '.' in expression specification

### ISSUE THREAD

**Issue by ximengyun** [apache/dolphinscheduler#4099]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
A clear and concise description of what the question is.
When I use SELECT  `(order_id_rn)?+.+`,have a exception
FAILED: ParseException line 20:22 cannot recognize input near ''20201123'' '+' '.' in expression specification

**Which version of DolphinScheduler:**
 -[2.1.3]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by CalvinKirs** [comment]
Hi, please confirm your version is 1.3.3? In addition, can you provide more detailed log information and complete sql.
