### ISSUE TITLE
The previous step mysql query the list data as the input of the next step（前步骤mysql查询出的列表数据作为后一步的输入）

### ISSUE THREAD

**Issue by huanzui** [apache/dolphinscheduler#410]
The previous step mysql query the list data as the input of the next step

If two parallel mysql query two sets of results, the next step is to receive the two sets of data operations and save them to another mysql, or save them to hdfs through spark processing. Now the 1.0.3 version does not see this feature, I don't know Not realized, now I can only judge whether the previous step is successful.

---
前步骤mysql查询出的列表数据作为后一步的输入 

如2个并行mysql查询两组结果，下一步就是接收这两组数据操作后保存到另外一个mysql中，或者经过spark处理保存到hdfs，现在的1.0.3版本没看到这个特性，不知道有没实现，现在只能判断上一步是否成功吧。

**Comment by lidongdai** [comment]
good issue! thx!

not implement for now！ we will consider it later!
