### ISSUE TITLE
Parallel tasks Failed policy selection continue，but the last task is not executed

### ISSUE THREAD

**Issue by xiahejun** [apache/dolphinscheduler#4115]
**Describe the question**
Parallel tasks Failed policy selection continue，but the last task is not executed

**Which version of DolphinScheduler:**
 -[1.3.3]

![image](https://user-images.githubusercontent.com/54968493/100422190-c8789100-30c4-11eb-9145-cd75d054b41f.png)

**Comment by xingchun-chen** [comment]
Failure to continue is effective for parallel tasks, because your D task also depends on C task, so failure will not execute D
![image](https://user-images.githubusercontent.com/55787491/100565187-f98fd600-32fd-11eb-98cd-e051aaf34dc5.png)

**Comment by xiahejun** [comment]
If I just want to finish the previous task, I will carry out the next task, whether or not the previous task was successful. I would like to ask how I should modify it, because we have some business scenarios that require such functions, such as isdone of zakaban.
---------------------------------------------------------------------------------------------------------------------------------------------
假如我只是想上一个任务完成就执行下一个任务，不管上一个任务是否成功。请问我应该怎么修改，因为我们有一些业务场景需要此类功能,类似zakaban的isDone.

**Comment by xingchun-chen** [comment]
You can use condition node
 
![image](https://user-images.githubusercontent.com/55787491/100566949-51c8d700-3302-11eb-9902-d84960450228.png)

**Comment by Ylisen** [comment]
Add a judgment flag to each task node. After failure, whether to continue to the next task?

**Comment by xiahejun** [comment]
I understand that “**failure continues**”, whether parallel or serial. Follow up tasks continue. I changed the source code, and now it is shown in the figure below, and the final task status is also failed.
--------------------------------------------------------------------------------------------------------------------------------------------
我理解的  “**失败继续**”，是不管并行还是串行。后续任务都继续执行。我修改了一下源码，现在变成如下图所示，并且最终任务状态也是失败。


![image](https://user-images.githubusercontent.com/54968493/100686624-a9764980-33b9-11eb-88f1-c1ca2bcc646c.png)
