### ISSUE TITLE
[Question] dolphinscheduler Integration datax task execution monitoring issues

### ISSUE THREAD

**Issue by 207992** [apache/dolphinscheduler#4131]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
A clear and concise description of what the question is.

When I used the DolphinScheduler integration Datax, I used a custom template for file import. If the dolphinScheduler task was imported to report a primary key conflict, the DolphinScheduler task still showed success, but looked at the task log and found that it reported an error message

**Which version of DolphinScheduler:**
 -[1.1.0-preview]
dolphinscheduler1.3.3
**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by Rubik-W** [comment]
It should be a problem with datax, DS is to execute the datax.py command through the shell,
So, You can test datax separately and view the returned code.
