### ISSUE TITLE
sqoop write to hive hcatalog orc

### ISSUE THREAD

**Issue by snycc15** [apache/dolphinscheduler#4146]
建议同步写方式方式多一种选择，可考虑写到hive orc 表，性能方面会有所提升，现在是直接写到文本，例如：
sqoop import --connect jdbc:oracle --username xxx --password xxx --table xxx.xxx --hcatalog-databse xxx  --hcatalog-table xx  --drop-and-create-hcatalog-table --hcatalog-storage-stanza 'stored as orc tblproperties ("orc.compress"="SNAPPY","transactional"="false")' --m 1

**Comment by Eights-Li** [comment]
using hcatalog to import RMDBS have some limits ：
http://sqoop.apache.org/docs/1.4.7/SqoopUserGuide.html#_unsupported_sqoop_options
if you need custom sqoop task, you can use sqoop custom job in ds-dev-branch

**Comment by snycc15** [comment]
The problem of "no support" does not exist. Import to Orc is a way to promote high performance at present.
