### ISSUE TITLE
[Bug][Task] Custom parameter return error

### ISSUE THREAD

**Issue by liuliu957** [apache/dolphinscheduler#4155]
When using parameters
${yyyyMMdd}
Scheduling with complement on the 31st returns the 1st of the next month.
The same ${yyyyMM}
Return to the next month

**Comment by CalvinKirs** [comment]
Please provide a specific version and describe your problem, environment, and specific steps on how to reproduce it.

**Comment by liuliu957** [comment]
The version I'm using is V1.3.2
Configuration parameters
![image](https://user-images.githubusercontent.com/75417939/100986635-6dddaa00-3588-11eb-899a-b59caa9329dd.png)
Using shell nodes
echo '${parameters_test}'
![image](https://user-images.githubusercontent.com/75417939/100986908-c57c1580-3588-11eb-907a-bab1c3106080.png)
result is  '20201101'

**Comment by caishunfeng** [comment]
This issue will be closed because no update for a long time.
BTW, it seems no a bug, see https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/guide/parameter/built-in.html
You can reopen it if need.
