### ISSUE TITLE
[Bug][server] tast param lost when use varpool in dev branch

### ISSUE THREAD

**Issue by hei12138** [apache/dolphinscheduler#4156]
**Describe the bug**
TaskNode's param will be replaced by TaskParams  when use varpool

**To Reproduce**
1. run a task and set some param to varpool when worker response
2. masterExecThread submitPostNode
3. varPoolUtils.convertVarPoolToMap will change the origin params to TaskParam which is not fetch all the task type
4. the worker will get the wrong params

**Expected behavior**
task params be completely pass to the worker 

**Screenshots**
![image](https://user-images.githubusercontent.com/14744212/100996627-3d037200-3594-11eb-880f-639efa1a463b.png)

![image](https://user-images.githubusercontent.com/14744212/100996738-615f4e80-3594-11eb-92fc-084b1ce68b0f.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by CalvinKirs** [comment]
hi, can you provide data on how to reproduce this problem

**Comment by hei12138** [comment]
Node a1 python task:
	Script:
		value = 600 + 60
		${setShareVar("shareVar1",value+6)}
		
Node a2 sql task:
	sql: anysql
the task2 will lose all the params because JSONUtils.parseObject(taskParamJson,TaskParams.Class) will case the param json to TaskParams which didn't handle the difference of each task

**Comment by hei12138** [comment]
@CalvinKirs

**Comment by caishunfeng** [comment]
Hi @hei12138 This issue will be closed because no update for a long time.
You can check it again in latest version and reopen this issue if need.
