### ISSUE TITLE
[Improve][ut]Refactor SqlExecutorTest

### ISSUE THREAD

**Issue by bingexxx** [apache/dolphinscheduler#4175]
运行 SqlExecutorTest 测试类的时候报错，应该是没有拉起spring 服务，请问是缺少了什么注解吗？
![WechatIMG1260](https://user-images.githubusercontent.com/22575306/101434901-60d50800-3946-11eb-9e1e-14a25e1ba5d8.png)

**Comment by CalvinKirs** [comment]
This UT is marked with @Ignore. If you are interested, you can refactor it. It is recommended to use the mock form and only test the SqlExecutor method.

**Comment by whitelowrie** [comment]
Please use english!!!
and you can write the test like this before you configured correctly

`@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes={DependencyConfig.class, SpringApplicationContext.class, SpringZKServer.class,
        NettyExecutorManager.class, ExecutorDispatcher.class, ZookeeperRegistryCenter.class, TaskPriorityQueueConsumer.class,
        ZookeeperNodeManager.class, ZookeeperCachedOperator.class, ZookeeperConfig.class, MasterConfig.class})
public class MyTest {

    @Autowired
    private ProcessService processService = null;

    @Test
    public void test01(){
        System.out.println(processService);
    }
}`

**Comment by CalvinKirs** [comment]
> Please use english!!!
> and you can write the test like this before you configured correctly
> 
> ```java
> @RunWith(SpringJUnit4ClassRunner.class)
> @ContextConfiguration(classes={DependencyConfig.class, SpringApplicationContext.class, SpringZKServer.class,
>         NettyExecutorManager.class, ExecutorDispatcher.class, ZookeeperRegistryCenter.class, TaskPriorityQueueConsumer.class,
>         ZookeeperNodeManager.class, ZookeeperCachedOperator.class, ZookeeperConfig.class, MasterConfig.class})
> public class MyTest {
> 
>     @Autowired
>     private ProcessService processService = null;
> 
>     @Test
>     public void test01(){
>         System.out.println(processService);
>     }
> }
> ```

We hope to adopt the mock form, because ut should remain relatively independent. Are you interested in refactoring this UT?

**Comment by bingexxx** [comment]
OK, thanks

**Comment by whitelowrie** [comment]
@CalvinKirs 
Sure，I can do this.
