### ISSUE TITLE
[Question] Time segmentation problem of workflow definition depending on nodes

### ISSUE THREAD

**Issue by kigang** [apache/dolphinscheduler#4196]
您好， @gaojun2048 ,依赖任务，会对选择的时间做分段，在依次获取分段内工作流实例对应的任务的结果，进行结果合并作为依赖节点结果；
想问问，这个时间分段有没有什么特殊的含义，因为我发现时间不分段好像也没什么问题，直接获取界面配置的时间内最新的工作流实例的结果作为依赖节点的结果，也是可以的。

**Comment by dailidong** [comment]
Please update or add title/description in English, thx

**Comment by kigang** [comment]
Depending on the task, the selected time will be segmented, and the corresponding task results of the workflow instance within the segmentation will be obtained in turn, and the results will be merged as the dependent node results.
I would like to ask if this time segment has any special meaning, since I find it seems to be ok that the time is not segmented, and it is also possible to get the result of the latest workflow instance directly within the time of the interface configuration as the result of the dependent node.
