### ISSUE TITLE
[Bug][Dao] The automatically generated json file in the DataX task cannot correctly parse the fields of the target table in the sqlserver DB.

### ISSUE THREAD

**Issue by Cryuu0614** [apache/dolphinscheduler#4253]
1.  Adding dataX task nodes to the workflow.
2. Using SQL statements instead of custom templates to create tasks, selecting Sqlserver as the target library type.
3. Error occurred when running this dataX task.
4. Checking the log, the error message is that the target table field cannot be parsed correctly. Moreover, checking the automatically generated json file, there is a "～" symbol before and after every parsed target table field.

<img width="495" alt="截屏2020-12-17 下午1 41 41" src="https://user-images.githubusercontent.com/76145178/102457122-31787680-407d-11eb-9348-0671cc3abcf3.png">

![image](https://user-images.githubusercontent.com/76145178/102457253-6389d880-407d-11eb-8220-1aaadd2ae78d.png)

Dolphinscheduler Version：1.3.3

**Comment by caishunfeng** [comment]
This issue will be closed because no update for a long time.
