### ISSUE TITLE
[Improvement][API] Optimize the open API for dolphinScheduler

### ISSUE THREAD

**Issue by yy0812** [apache/dolphinscheduler#4257]
version-[1.3.3-release]
Optimize the open API for dolphinScheduler，for example：
1.Returns the process definition ID on success of the imported process definition。
2.add interfaces similar to saveorUpdate logic.
3.add interfaces similar to queryResourceByFullName logic.
4.add interfaces similar to queryprocessDefinitionByName logic.
Other waiting to comb after completion of the supplement, also welcome everyone to add

**Comment by CalvinKirs** [comment]
Hi, I suggest creating different to-do lists for UI tasks and server code tasks

**Comment by ruanwenjun** [comment]
I suggest giving a more explicit type of data in `Result`. It is difficult to guess the return structure according to the code in the controller package. This affects secondary development. This has been mentioned in #5015.
