### ISSUE TITLE
Workflow list - can you increase the classification function?

### ISSUE THREAD

**Issue by lipengbo2018** [apache/dolphinscheduler#429]
All workflow definitions, different levels and different levels of different levels are mixed together, and the management is particularly messy, and it is also prone to misuse and affect online scheduling.
It is recommended to add a custom classification, and the workflow can change the classification.
E.g:
We can divide these categories into categories (online, development, testing) or (schedule main tasks, subtasks, temporary tasks, test tasks) or according to business (dimension related, business topic 1, business topic 2)

Of course, if you are based on development difficulty, you can also fix several categories.

---
所有的工作流定义，不同类别不同层级不同状态的，都混杂在一起，感觉管理起来特别乱，同时也容易出现误操作而影响线上的调度。
建议增加自定义分类，且工作流可以变更所属分类。
例如：
我们可以根据需要分成这几个分类（线上，开发，测试）或（调度主任务，子任务，临时任务，测试任务）或者根据业务划分（维度相关，业务主题1，业务主题2）

当然，如果基于开发难度考虑，也可以固定好几个分类。

**Comment by dailidong** [comment]
very good idea！thx！

and do you have interesting to implement this feature ？

**Comment by Ylisen** [comment]
can you Add sorting or sticking function？
