### ISSUE TITLE
How to install ambari 2.7 + dolphin scheduler 1.3.3

### ISSUE THREAD

**Issue by Zosimer** [apache/dolphinscheduler#4297]
How to install ambari 2.7 + dolphin scheduler 1.3.3? At present, the official documents support ambari 2.5, and only ambari 2.7 + dolphin scheduler 1.3.0 is used to query other information. However, the two versions of dolphin scheduler ambari interface are inconsistent

1.3.0
![image](https://user-images.githubusercontent.com/19589632/102988772-6ab65800-454f-11eb-8b51-a767f70312b4.png)

1.3.3 there is no above step

**Comment by CalvinKirs** [comment]
you can refer the README doc: https://github.com/apache/incubator-dolphinscheduler/tree/1.3.3-release/ambari_plugin
