### ISSUE TITLE
[Workflow] Use sqoop to import data to hive, the data source is sql server

### ISSUE THREAD

**Issue by masterable** [apache/dolphinscheduler#4298]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
A clear and concise description of what the question is.
I created a sqoop import data workflow from sqlserver to hive
I have configured and connected the sqlserver data source, no problem
Then I encountered the following error
The error log reminds me that I may have used the wrong import configuration item。The other one prompts me that there is no --username item in my configuration item 。This confuses me, because my sqlserver data source has been verified。This should not happen。Below is a screenshot of my error log and workflow configuration
![image](https://user-images.githubusercontent.com/41288492/102990517-73f4f400-4552-11eb-85c6-78b519189c87.png)

![image](https://user-images.githubusercontent.com/41288492/102990665-bdddda00-4552-11eb-8abb-59f56ca8be3d.png)

**Which version of DolphinScheduler:**
 -[1.3.3-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by zhuangchong** [comment]
Currently the configuration does not support SQL SERVER, so you can use a custom template.

**Comment by masterable** [comment]
> 当前配置不支持SQL SERVER，因此您可以使用自定义模板。

But sqoop workflow currently does not have a custom template, and I am not familiar with datax...
Anyway, thanks a lot

**Comment by zhuangchong** [comment]
Consider using shell task nodes instead
