### ISSUE TITLE
[Feature][API] Automatically pull resource files from Git

### ISSUE THREAD

**Issue by JinyLeeChina** [apache/dolphinscheduler#4327]
We have a scenario where developers will submit hive SQL files to git locally, and then configure scheduling tasks on DS. Currently, we have been using this for several months, and we find that some users have similar requirements. I will contribute our code here

**Comment by enoughwell** [comment]
> We have a scenario where developers will submit hive SQL files to git locally, and then configure scheduling tasks on DS. Currently, we have been using this for several months, and we find that some users have similar requirements. I will contribute our code here


In which version will this function be implemented?

**Comment by JinyLeeChina** [comment]
Maybe in the next version, it will be implemented by SPI
