### ISSUE TITLE
[Improvement][Datasource] Propose for DEV refactor : Add dataSource for kudu

### ISSUE THREAD

**Issue by mumuCode** [apache/dolphinscheduler#4330]
Impala可以集成Hive、Kudu，系统数据源默认的Impala集成的就是Hive，所以使用的是HiveJDBC，Impala集成Kudu的情况没有考虑进来，所以建议将Impala跟hive数据源区分开，新增独立的Impala数据可以支持kudu，Hive数据源可以支持hive 或 impala连接参数

**Comment by felix-thinkingdata** [comment]
> Impala可以集成Hive、Kudu，系统数据源默认的Impala集成的就是Hive，所以使用的是HiveJDBC，Impala集成Kudu的情况没有考虑进来，所以建议将Impala跟hive数据源区分开，新增独立的Impala数据可以支持kudu，Hive数据源可以支持hive 或 impala连接参数

The same problem exists with Presto, and you can connect to his own supported Connector, which needs to be considered
