### ISSUE TITLE
[BUG] yarn resource management page parsing json error version:1.3.3

### ISSUE THREAD

**Issue by suncf1985** [apache/dolphinscheduler#4333]
![image](https://user-images.githubusercontent.com/16234399/103273259-d1c58800-49f9-11eb-88ea-0cb7341aa0c0.png)

1. Execute the hive command through the shell, the result can be normal success, but the process shows that the execution failed
2. After investigation, it is found that the shell can return 0 normally. When verifying the yarn resource, the json parsing error occurred
1.通过shell方式执行hive命令,结果可正常成功,但流程上显示为执行失败
2.经排查发现shell 可正常是返回 0,在验证yarn资源时,解析json出错
![image](https://user-images.githubusercontent.com/16234399/103273413-37b20f80-49fa-11eb-90a5-5e2c72669c75.png)

**Comment by lenboo** [comment]
@suncf1985 We need more details logs about this issue.
