### ISSUE TITLE
[Question] some questions about spark datasource

### ISSUE THREAD

**Issue by zhaorongsheng** [apache/dolphinscheduler#4365]
**Describe the question**
DS supports running sql in spark datasource. Is there any document about the detail mechanism of scheduling sql running in spark.
As we know, sparkSql only support yarn-client mode and in this mode the client server need to be well configured. How does DS handle this problem?

Looking forward to your reply~ thanks~

**Comment by zhuangchong** [comment]
Dolphin's spark datasource refers to SparkThriftServer, SparkThriftServer is offered by the spark, the user can through the JDBC/ODBC connection ThriftServer to access SparkSQL data, similar HiveServer2.

**Comment by zhaorongsheng** [comment]
@zhuangchong I think the spark thrift server is not stable. Is there any other way to schedule sql by spark, e.g. `sparkSql -f sql.txt`

**Comment by zhuangchong** [comment]
Yes, And Spark Thrift Server doesn't do as well as Hive in terms of permissions. I developed a toolkit that uses shell calls .it create context and read SQL statements in files to execute using code.

**Comment by zhaorongsheng** [comment]
Has your toolkit merge into master?
As we know spark driver needs more resource. If we use `sparkSql -f xx` the spark driver will run in `WorkerServer `. In this way the `WorkerServer` needs more resource. How should you handle this?
