### ISSUE TITLE
[Improvement][api] Queues can only be created and edited, not deleted

### ISSUE THREAD

**Issue by SunnyZ-L** [apache/dolphinscheduler#4375]
**Describe the question**
Queues can only be created and edited, not deleted
Looking at the current Dev development branch, there is no API for deleting queues

**What are the current deficiencies and the benefits of improvement**
-  Consider adding the ability and API to delete queues？

**Which version of DolphinScheduler:**
 - [1.2.1]

**Comment by zhuangchong** [comment]
It is recommended to upgrade to version 1.3.x

**Comment by chuyang-zl** [comment]
> 
> 
> It is recommended to upgrade to version 1.3.x

By looking at the 1.3 x branch code (org.apache.dolphinscheduler.api.controller.QueueController), did not provide delete queue interface, you said to upgrade to 1.3. X
通过查看1.3.x分支的代码（org.apache.dolphinscheduler.api.controller.QueueController），并未提供删除队列的接口呀，您说的升级到1.3.x指什么

**Comment by zhuangchong** [comment]
sorry, there is no delete function in the queue management interface

**Comment by chuyang-zl** [comment]
> 
> 
> sorry, there is no delete function in the queue management interface

@zhuangchong 
Whether officials plan to add the ability to delete queues?
官方是否要计划增加删除队列的功能？

**Comment by zhuangchong** [comment]
So far, there is none. We are very welcome to submit the PR implementation

**Comment by amaoisnb** [comment]
I wanna have a try, can you please assign to me?

**Comment by amaoisnb** [comment]
#12833

**Comment by amaoisnb** [comment]
#13046
