### ISSUE TITLE
并行流程设置失败继续还是失败

### ISSUE THREAD

**Issue by daizc1** [apache/dolphinscheduler#4378]
例如我有一个流程 a和b节点并行，c是结束节点，a和b跑完就跑c，现在出现情况是如果有一个节点失败了，c就不跑了，我设置
失败策略为： 继续 ，也不行。

**Comment by liqiquan** [comment]
使用condition task，可以指定失败走哪个task，成功走哪个task

**Comment by xingchun-chen** [comment]
English is global, please change the title in English
