### ISSUE TITLE
[Feature][doc] Modify the document markdown display style

### ISSUE THREAD

**Issue by BoYiZhang** [apache/dolphinscheduler#4380]
Modify the document Display style is abnormal

![image](https://user-images.githubusercontent.com/39816903/103662906-740dde80-4fab-11eb-9443-302c00b882c8.png)

link address:
https://github.com/apache/incubator-dolphinscheduler-website/blob/master/docs/zh-cn/1.3.1/user_doc/configuration-file.md
https://github.com/apache/incubator-dolphinscheduler-website/blob/master/docs/zh-cn/1.3.2/user_doc/configuration-file.md
https://github.com/apache/incubator-dolphinscheduler-website/blob/master/docs/zh-cn/1.3.3/user_doc/configuration-file.md
https://github.com/apache/incubator-dolphinscheduler-website/blob/master/docs/zh-cn/1.3.4/user_doc/configuration-file.md

**Comment by aNotBadCoder** [comment]
@CalvinKirs  You can assigned me.

**Comment by Lucaszlei** [comment]
Assign it to me so I can familiarize myself with the PR process
