### ISSUE TITLE
[website][doc] Translation of Chinese docs into English docs

### ISSUE THREAD

**Issue by CalvinKirs** [apache/dolphinscheduler#4381]
We need to translate these Chinese documents into English documents.and link it to the user documentation

https://github.com/apache/incubator-dolphinscheduler-website/blob/master/docs/zh-cn/1.3.1/user_doc/configuration-file.md
https://github.com/apache/incubator-dolphinscheduler-website/blob/master/docs/zh-cn/1.3.2/user_doc/configuration-file.md
https://github.com/apache/incubator-dolphinscheduler-website/blob/master/docs/zh-cn/1.3.3/user_doc/configuration-file.md
https://github.com/apache/incubator-dolphinscheduler-website/blob/master/docs/zh-cn/1.3.4/user_doc/configuration-file.md

If you want to complete it, please leave a comment under issue

**Comment by JacobZheng0927** [comment]
I can do this.
