### ISSUE TITLE
[Improvement][recording data] Manually configure the parallelism of supplementary when recording data

### ISSUE THREAD

**Issue by hhj970815** [apache/dolphinscheduler#4385]
*i met a situation that the memory fulls and the dolphinscheduler server down when i start the recording data(补数)  tasks, if there is a feature that we can configure the parallelism of supplementary recording data manually *

**Describe the question**
The memory fulls and the dolphinscheduler server down when i start the recording data(补数)  tasks.

**What are the current deficiencies and the benefits of improvement**
We can configure the parallelism of supplementary recording data manually so that the machine resource will not be occupied too much.

**Which version of DolphinScheduler:**
 -[1.3.3-preview]

**Describe alternatives you've considered**
Changing the model to "Serial"(串行) but this model will take too much time.

**Comment by xingchun-chen** [comment]
good idea, is anyone willing to implement it?
