### ISSUE TITLE
Timed task self dependence | 定时任务自我依赖

### ISSUE THREAD

**Issue by RunningHu** [apache/dolphinscheduler#4388]
When DS starts a scheduled task, if the last task is not finished, how can it be set not to start it again, or to kill the task that was not finished in the last schedule.

For example: the task started yesterday, the task has been running without ending, and today it's time again. If you didn't finish the last time, you shouldn't get up this time, or you should get rid of what you didn't finish last time.

ds定时调度启动任务的时候，如果上一次的任务没有执行完，怎么设置不让他再次启动，或者干掉上次调度没有运行完的任务。
比如：昨天起了任务，这个任务一直跑着没有结束，今天又到时间了，上次没跑完，这次就不该起来，或者应该应该把上次没跑完的干掉。

**Comment by CalvinKirs** [comment]
You can choose the timeout failure strategy.

By the way, for better communication, please use English,

**Comment by hujiang75277381** [comment]
这个地方可以改造 worker。给task添加一个阻塞策略：并行执行 丢弃后续调度
改造方案:在worker初始化 AbstractTask 的时候，判断下相同工作流、task_type、task_name 是否有运行的task实例。如果存在 ，判断是否是自己，否则 中断执行，将task实例的状态标记为失败返回。

**Comment by zhanguohao** [comment]
It’s best to leave this strategy to the user to decide, such as
-Start a new task (regardless of the previous task)
-End the previous task and start a new task
-Wait for the completion of the previous task and start a new task (the next scheduling time point)

----
最好这个策略交给用户决定，比如
- 启动新任务（不管上一个任务）
- 结束上一个任务，启动新任务
- 等待上一个任务结束后，启动新任务（下一个调度时间点）

**Comment by dailidong** [comment]
> You can choose the timeout failure strategy.
> 
> By the way, for better communication, please use English,

English +1，please add title and desc in English

**Comment by JinyLeeChina** [comment]
> It’s best to leave this strategy to the user to decide, such as
> -Start a new task (regardless of the previous task)
> -End the previous task and start a new task
> -Wait for the completion of the previous task and start a new task (the next scheduling time point)
> 
> 最好这个策略交给用户决定，比如
> 
> * 启动新任务（不管上一个任务）
> * 结束上一个任务，启动新任务
> * 等待上一个任务结束后，启动新任务（下一个调度时间点）

+1,  I agree

**Comment by RunningHu** [comment]
> It’s best to leave this strategy to the user to decide, such as
> -Start a new task (regardless of the previous task)
> -End the previous task and start a new task
> -Wait for the completion of the previous task and start a new task (the next scheduling time point)
> 
> 最好这个策略交给用户决定，比如
> 
> * 启动新任务（不管上一个任务）
> * 结束上一个任务，启动新任务
> * 等待上一个任务结束后，启动新任务（下一个调度时间点）

这样是最好的方案

**Comment by hujiang75277381** [comment]
![English](https://user-images.githubusercontent.com/15833811/103764530-96106b00-5056-11eb-8af8-50de9544177c.png)

![chinese](https://user-images.githubusercontent.com/15833811/103764775-0c14d200-5057-11eb-81bb-b2878ae6adf6.png)

**Comment by brucemen711** [comment]
> It’s best to leave this strategy to the user to decide, such as
> -Start a new task (regardless of the previous task)
> -End the previous task and start a new task
> -Wait for the completion of the previous task and start a new task (the next scheduling time point)
> 
> 最好这个策略交给用户决定，比如
> 
> * 启动新任务（不管上一个任务）
> * 结束上一个任务，启动新任务
> * 等待上一个任务结束后，启动新任务（下一个调度时间点）

I think this is aceptable but user need to handle checking if job had proccess instances running or not, is this right ?

**Comment by brucemen711** [comment]
![image](https://user-images.githubusercontent.com/54098579/106119567-eecfb100-6187-11eb-882b-77de2ac08979.png)
I create this flow to make job run every hour, hope it helps.
You can even run every 10 minutes just in case previous schudule not done and next schedule not run cause checkpoint exists.

**Comment by leeseven1211** [comment]
When can this function be realized

**Comment by davidzollo** [comment]
dev branch has implemented this feature, please check
