### ISSUE TITLE
[Improvement][dolphinscheduler-alert] DS alter mail service cannot escaped the specail characters about mail.passwd like %$..

### ISSUE THREAD

**Issue by zjw-zjw** [apache/dolphinscheduler#4395]
When I configure my mail server's passwd, Password contains special characters like %$, and DS could not escape successfully, so that the message failed

**What are the current deficiencies and the benefits of improvement**
I think DS alert service can escape the special characters like %$ for passwd.

**Which version of DolphinScheduler:**
 -[1.3.3]

**Comment by xingchun-chen** [comment]
Try to change the password directly in ./conf/alert.properties ,Or escape the character with \
