### ISSUE TITLE
[Question] Does the worker need to support the user's own access method

### ISSUE THREAD

**Issue by wwh2156** [apache/dolphinscheduler#4400]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
A clear and concise description of what the question is.

**Which version of DolphinScheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by xingchun-chen** [comment]
English is global and necessary, please update the title in English,Thanks

**Comment by CalvinKirs** [comment]
We wanted to be as lightweight as possible, so we chose netty. Akka is very good, but it may not be suitable for us.

Does the worker need to support the user's own access method? I don't quite understand this sentence, can you describe it in more detail.
