### ISSUE TITLE
Custom parameters need to filter empty key

### ISSUE THREAD

**Issue by daizc1** [apache/dolphinscheduler#4402]
现在遇到一个问题，在1.3.2中我自定义参数写成$[]ddd_${last_month}，可以替换为ddd_202012的，在1.3.4中不能替换，还是$[]ddd_${last_month}的，其中${last_month}我是定义成全局参数的。
现在问题是我是一个固定字符串和一个变的字符串，怎么能实现我的需求，谢谢！

**Comment by daizc1** [comment]
说错，1.3.2是ddd_202012，1.3.4是$[]ddd_202012

**Comment by daizc1** [comment]
在shell节点中可以替换，我echo ddd_${last_month}会变成 ddd_202012,但存储过程节点中，自定义参数，写成ddd_${last_month}和$[]ddd${last_month}都不行。

**Comment by xingchun-chen** [comment]
English is global, please change the title in English

**Comment by CalvinKirs** [comment]
Hi, I want to ask you a little bit, what is the function of $[] in the expression $[]ddd_${last_month}?
