### ISSUE TITLE
[Bug][WORKER] Transaction problem, different workers get the same task to execute, execute it twice, causing data duplication

### ISSUE THREAD

**Issue by superxiaojie** [apache/dolphinscheduler#4405]
**Describe the bug**
Transaction problem, different workers get the same task to execute, execute it twice, causing data duplication

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Set timing execution time
2. To trigger the task regularly
3. Different workers get the same task

**Expected behavior**
Different workers will only take different tasks

**Screenshots**
![image](https://user-images.githubusercontent.com/18513424/103962006-c5c38e00-5190-11eb-8996-cc20ae28b6b5.png)
![image](https://user-images.githubusercontent.com/18513424/103962021-d247e680-5190-11eb-8990-67d6ea086572.png)

**Which version of Dolphin Scheduler:**
 -[1.2.0-preview]

**Requirement or improvement**
 How to solve this problem
**中文描述
同一个工作流任务分别被2个worker获取到，并且在俩个worker同时执行，造成数据重复。
Thank Yous

**Comment by dailidong** [comment]
has this worker which named scheduler03 worked fine all the time ?  

By the way, 1.2.0 version is very old version, may be you can try to upgrade to 1.3.4 stable version

**Comment by dailidong** [comment]
please paste detail log info at that moment, it will help to determine why this issue happened

**Comment by caishunfeng** [comment]
This issue will be closed because no update for a long time.
