### ISSUE TITLE
[Feature][Scheduler] Avoid locking for self-dependent Process

### ISSUE THREAD

**Issue by ntupapaya** [apache/dolphinscheduler#4422]
**Describe the feature**
问题：目前想定义依赖自身的（例如前一日执行）流程时，导致自身死锁。第一次无法运行起来。
解决：1. 希望增加某种判断，当第一次调度执行时，忽略这种依赖。
2. 至少是定时界面上增加一个可选的选项、由人为判断，是否希望阻塞第一次执行。

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ntupapaya** [comment]
目前如果要驱动一个自依赖的流程，对于本身测试开发好的一个流程、上生产导入后只能先禁用依赖组件、手动补数执行被依赖的前一个时段的任务、再启用依赖组件、再上线，非常繁琐笨拙。对于生产使用来说不现实。
这个过程反正也是需要、即使是需要人为选择，还是想一个方便的方式来触发呗

**Comment by leeseven1211** [comment]
I ran into the same problem @ke4qqq @gmcdonald @jbampton @Humbedooh

**Comment by lian773596423** [comment]
I quite agree with the proposal

**Comment by davidzollo** [comment]
this feature has implemented in dev branch
