### ISSUE TITLE
[sqoop] sqoop import mysql into hdfs,use sql to conditionally export exceptions? condition auto add 1=0

### ISSUE THREAD

**Issue by zheng-zy** [apache/dolphinscheduler#4425]
原sql：`select * from tbl_onlineorder WHERE OrderDatetime BETWEEN "2021-01-10 00:00:00" AND "2021-01-11 00:00:00" `

执行日志上的sql：`select * from tbl_onlineorder WHERE OrderDatetime BETWEEN "2021-01-10 00:00:00" AND "2021-01-11 00:00:00" AND  (1 = 0) `

导出sql上会添加1=0条件，导致没有数据导出来，这个是官方自己加的，该如何去除？

**Comment by dailidong** [comment]
please paste the screenshot about the sql ? which verison ? 

Please add/update the title and desc in English, thx

**Comment by zheng-zy** [comment]
> please paste the screenshot about the sql ? which verison ?
> 
> Please add/update the title and desc in English, thx

dolphinscheduler version 1.3.3，sql picture see https://imgchr.com/i/sYETgK，help

**Comment by SuperHeroBigData** [comment]
i also meet this problem ,how can we solve it?

**Comment by SuperHeroBigData** [comment]
have you solve this problem ?
