### ISSUE TITLE
Can I increase the context information of a workflow instance?（能否增加工作流实例的上下文信息）

### ISSUE THREAD

**Issue by zhongchongfang** [apache/dolphinscheduler#443]
The current job can get the execution result of the job executed in the previous step; support the execution condition of the current job, and the execution condition can use the execution result of the job executed in the previous step.

---
当前的job可以拿到前面步骤已执行job的执行结果；支持配置当前job的执行条件，并且执行条件可以使用前面步骤已执行job的执行结果

**Comment by lgcareer** [comment]
good idea!

Could you give us more detail requirement，such as “how to transfer data ？ key/value or other method”

or Could you submit a pull request to solve this question？
