### ISSUE TITLE
Kerberos expired

### ISSUE THREAD

**Issue by zongqiren** [apache/dolphinscheduler#4430]
The team uses the dolphinscheduler to schedule the spark2 task. Because the Kerberos environment is enabled in the cluster environment, the spark task cannot be executed after a period of time. It is found in the worker log that the authentication has expired. If you try to restart the dolphinscheduler, you can resume normal execution. It is not a solution to restart all the time. Do you want to know what can be solved?

**Comment by zongqiren** [comment]
I've revised it common.properties , put kerberos.expire.time Parameter modification, restart, can unlimited modification is very big, because to find a way to solve the problem of expiration, always can't old restart to solve

**Comment by zhuangchong** [comment]
Set up a timed task to refresh the keytab. You can also try this method.

**Comment by zongqiren** [comment]
Do you want to refresh the KeyTab of DS authentication or the KeyTab of the user executing the program on DS regularly? Do you have any examples? If you are not familiar with this part, please write a method to refresh the KeyTab. Thank you

**Comment by zhuangchong** [comment]
Dolphin sets up a timed task that uses the shell task node to call the script kinit-kt/XXX /xxx.keytab xxx@xxx.xxx.com to swipe the keytab of a specific user

**Comment by shiliquan** [comment]
@zongqiren  
 I suggest you upgrade to version 1.3.4. I've had the same problem as you before, upgrade to 1.3.4 and modify krb 5. After a week of testing, nothing like this has happened.
![image](https://user-images.githubusercontent.com/42087586/104456104-29abe380-55e3-11eb-982d-313114001e1c.png)

**Comment by ZhaoXin-JIN** [comment]
> @zongqiren
> 我建议您升级到1.3.4版。我遇到了与您之前相同的问题，升级到1.3.4并修改krb5。经过一周的测试，没有发生任何类似的事情。
> ![图像](https://user-images.githubusercontent.com/42087586/104456104-29abe380-55e3-11eb-982d-313114001e1c.png)

I have the same problem. Excuse me, have you solved it? How to solve the problem

**Comment by shiliquan** [comment]
好像解决了！

**Comment by shiliquan** [comment]
你把common.properties里的kerberos.expire.time这个参数改一下试试。
![image](https://user-images.githubusercontent.com/42087586/109476446-e71a6980-7ab1-11eb-8e2f-2c99e760b0c4.png)

**Comment by ZhaoXin-JIN** [comment]
> 你把common.properties里的kerberos.expire.time这个参数改一下试试。
> ![image](https://user-images.githubusercontent.com/42087586/109476446-e71a6980-7ab1-11eb-8e2f-2c99e760b0c4.png)

好，我等今晚过期后修改一下，然后重启worker。目前配置的是24

**Comment by zongqiren** [comment]
emmm,我测试过，没有用
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-dolphinscheduler"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月1日(星期一) 下午5:22
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"470096567"<470096567@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] Kerberos expired (#4430)





  
你把common.properties里的kerberos.expire.time这个参数改一下试试。
 
  
好，我等今晚过期后修改一下，然后重启worker。目前配置的是24

**Comment by ZhaoXin-JIN** [comment]
> emmm,我测试过，没有用 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apache/incubator-dolphinscheduler" <notifications@github.com&gt;; 发送时间:&nbsp;2021年3月1日(星期一) 下午5:22 收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;; 抄送:&nbsp;"470096567"<470096567@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [apache/incubator-dolphinscheduler] Kerberos expired (#4430) 你把common.properties里的kerberos.expire.time这个参数改一下试试。 好，我等今晚过期后修改一下，然后重启worker。目前配置的是24 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

你现在情况怎么样。解决了么？

**Comment by shiliquan** [comment]
那不知道啊，反正我是可以了！

**Comment by ZhaoXin-JIN** [comment]
魔幻的问题啊啊啊啊

**Comment by shiliquan** [comment]
一、我用的是1.3.4版本
二、我的krb5认证文件如下：（这个文件建议把本机认证的krb5文件统一，所有work都要改）
![image](https://user-images.githubusercontent.com/42087586/109478066-be936f00-7ab3-11eb-9407-775d0f7de79c.png)
三、修改了kerberos.expire.time=1（如果不行，这个参数建议你可以修改小一点，可以用0.2、0.5.....试一下）
然后install重装了一下。
其他的我也没改啥了。
希望可以帮到你。

**Comment by shiliquan** [comment]
@JinLin6564 问题解决了么？

**Comment by ZhaoXin-JIN** [comment]
> @ JinLin6564问题解决了么？

没有。哎。。
