### ISSUE TITLE
[bug][server][master]if TaskPriorityQueueConsumer.run() throw exception，Nothing is done in catch

### ISSUE THREAD

**Issue by baiyibo** [apache/dolphinscheduler#4445]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **

**Describe the bug**
if TaskPriorityQueueConsumer.run() throw exception，Nothing is done in catch，Because there is no error callback method，
then MasterTaskExecThread.waitTaskQuit() Can't jump out of the loop.
This will trigger  masterExecThreads reached max value.
中文：流程实例在master被切分为任务实例后，放入TaskPriorityQueue后就默认发送成功了，在TaskPriorityQueue消费是如果抛出异常，catch中没有做错误处理，那么MasterTaskExecThread中是一直在等待该任务typeIsFinished（）,无法跳出循环等待，后续任务一直来分发等待，会造成Master执行线程数达到最大，无法继续工作。

**To Reproduce**
Steps to reproduce the behavior, for example:
1. TaskPriorityQueueConsumer.run() throw exception，Nothing is done in catch
2. MasterTaskExecThread.waitTaskQuit() Can't jump out of the loop --->thread blocking.
3. masterExecThreads reached max value.
4.  The state of subsequent tasks is waiting thread

**Expected behavior**
My understanding is that if  TaskPriorityQueueConsumer.run() throw exception，In catch, you should modify the status of the task, or call back other failed operations。bring MasterTaskExecThread.waitTaskQuit () is not blocked all the time, waiting for the thread to finish

**Screenshots**
![image](https://user-images.githubusercontent.com/42854971/104532262-cb1a5000-564a-11eb-94a2-49867ec741e9.png)
![image](https://user-images.githubusercontent.com/42854971/104532353-fd2bb200-564a-11eb-925a-6dea5af14857.png)

**Which version of Dolphin Scheduler:**
 -[1.3.2-SNAPSHOT]

**Additional context**

**Requirement or improvement**
My understanding is that if  TaskPriorityQueueConsumer.run() throw exception，In catch, you should modify the status of the task, or call back other failed operations。bring MasterTaskExecThread.waitTaskQuit () is not blocked all the time, waiting for the thread to finish

**Comment by baiyibo** [comment]
hello?

**Comment by baiyibo** [comment]
111

**Comment by caishunfeng** [comment]
Hi @baiyibo This issue will be closed because no update for a long time.
BTW, the latest version had changed and you can check it again, thanks.
