### ISSUE TITLE
Workflow task ends ahead of time

### ISSUE THREAD

**Issue by wangchuang07** [apache/dolphinscheduler#4448]
**bugs desc**
The node is an SH script. The content is to use the SH script to call the SQL script. When the SQL script reports an error, this node reports an error normally, but other nodes are killed at the same time.

**Expected behavior**
We hope that only this node will report an error, and other nodes that have no dependency on this node will continue to execute.

**Screenshots**
![Uploading image.png…]()

**Comment by zhuangchong** [comment]
Does it meet your needs?

![image](https://user-images.githubusercontent.com/37063904/104570314-ba8ac980-568c-11eb-9704-313f34223049.png)

**Comment by wangchuang07** [comment]
> Does it meet your needs?
> 
> ![image](https://user-images.githubusercontent.com/37063904/104570314-ba8ac980-568c-11eb-9704-313f34223049.png)


Sorry, I can't open this picture. Can you send this picture to my email as an attachment，tianyuanxiaoxin@sina.com.cn，thx

**Comment by zhuangchong** [comment]
@wangchuang07 

ok, the email has been sent, hope can help you.

**Comment by wangchuang07** [comment]
> Does it meet your needs?
> 
> ![image](https://user-images.githubusercontent.com/37063904/104570314-ba8ac980-568c-11eb-9704-313f34223049.png)

Click "continue" here to decide whether there is a failed node in the workflow, the whole workflow will run again, or other nodes will continue to execute. If it is the latter, I will try again.

**Comment by wangchuang07** [comment]
> Does it meet your needs?
> 
> ![image](https://user-images.githubusercontent.com/37063904/104570314-ba8ac980-568c-11eb-9704-313f34223049.png)

Workflow automatic timing failed to set failure policy. In addition, when the breakpoint rerun (the whole workflow rerun a day's data from a node), why can't it be started? Can you help me？
![Uploading image.png…]()

**Comment by wangchuang07** [comment]
> Does it meet your needs?
> 
> ![image](https://user-images.githubusercontent.com/37063904/104570314-ba8ac980-568c-11eb-9704-313f34223049.png)

After setting the timing task, the node failure policy cannot be selected. How to deal with this situation？

**Comment by wangchuang07** [comment]
> @wangchuang07
> 
> ok, the email has been sent, hope can help you.

Workflow automatic timing failed to set failure policy. In addition, when the breakpoint rerun (the whole workflow rerun a day's data from a node), why can't it be started? Can you help me？
Uploading image.png…

**Comment by wangchuang07** [comment]
> Does it meet your needs?
> 
> ![image](https://user-images.githubusercontent.com/37063904/104570314-ba8ac980-568c-11eb-9704-313f34223049.png)

Workflow automatic timing failed to set failure policy. In addition, when the breakpoint rerun (the whole workflow rerun a day's data from a node), why can't it be started? Can you help me？
![image](https://user-images.githubusercontent.com/38686005/105453183-a4978d00-5cba-11eb-89bc-d079113ba1ea.png)

**Comment by caishunfeng** [comment]
Hi @wangchuang07 This issue will be closed because no update for a long time. You can check it again in latest version and reopen it if need.
