### ISSUE TITLE
[Question][server] The workflow instance containing the SQL task could not be stopped properly

### ISSUE THREAD

**Issue by Lucaszlei** [apache/dolphinscheduler#4454]
**Describe the bug**
1. Execute the stop command on the workflow instance, and the workflow instance will be in the state of "ready to stop".
If the workflow contains SQL task nodes, the SQL task instance cannot be stopped and can only wait for the SQL task to end on its own before the workflow instance changes state
2. TASKS_KILL queue stop message is normally added to tasks_kill queue master
3. The worker also gets the information from the queue normally and executes the stop command, but because the pid value of the task instance of SQL type is 0, it fails to stop the task

---

1. 对工作流实例执行停止命令，工作流实例状态会处于“准备停止”状态，
如果工作流中包含SQL任务节点，SQL任务实例无法被停止，只能等待SQL任务自己结束，然后工作流实例才会改变状态
1. 查看日志，master中正常给tasks_kill队列汇中加入了停止信息
![图片](https://user-images.githubusercontent.com/56599784/104568287-e016d380-568a-11eb-82b8-aac01c2eb96d.png)
1. worker中也正常从队列中获取了信息，并且执行了停止命令，但是由于SQL类型的任务实例pid值为0，导致停止任务时失败
![图片](https://user-images.githubusercontent.com/56599784/104569945-4a7c4380-568c-11eb-9bd3-4a30adc225b6.png)

**Which version of Dolphin Scheduler:**
 -[1.2.1]

**Requirement or improvement**
- Through phenomenon and source analysis, it is found that only shell tasks have PID value and can be stopped in time with the stop of workflow instance, while SQL tasks cannot be stopped in time with the stop of workflow instance because they do not have PID value
- For SQL type tasks, how do you stop?
- Has this problem been fixed?

---

- 通过现象和源码分析，只有像shell类型的任务才有pid值，可以随着工作流实例的停止被及时停止，而sql类型的任务由于没有pid值，无法随着工作流实例的停止而及时停止
- 对于SQL类型的任务，如何停止？
- 此问题是否已经被修复？

**Comment by linghengzhu** [comment]
It's true, hivesql task count be stuck forever if yarn is running out of resource, so how count it be fixed?

**Comment by SunnyZ-L** [comment]
> It's true, hivesql task count be stuck forever if yarn is running out of resource, so how count it be fixed?

What do 'count' and 'fixed' mean?
If it is convenient, please add the Chinese description

**Comment by Lucaszlei** [comment]
> It's true, hivesql task count be stuck forever if yarn is running out of resource, so how count it be fixed?

Up to now, this problem cannot be fixed, and the corresponding app on yarn can only be manually stopped
