### ISSUE TITLE
[Bug][woker] Work feigned death after stop the workflow instance

### ISSUE THREAD

**Issue by baijun** [apache/dolphinscheduler#4461]
1. The workflow instance contains Spark tasks, which are submitted to YARN for execution via cluster mode.
2. Stop the workflow instance through DS interface.
![image](https://user-images.githubusercontent.com/7664170/104675225-03d82900-5720-11eb-8b15-836d7ad63892.png)

3. At this time, DS will send kill instruction on the work host to terminate the submitted task.
![image](https://user-images.githubusercontent.com/7664170/104674954-81e80000-571f-11eb-90a1-4caf83cabb60.png)

4. When JPS looks at the work node, it will see the application-kill directive.
![image](https://user-images.githubusercontent.com/7664170/104675024-a04dfb80-571f-11eb-84a4-a065311f677c.png)
![image](https://user-images.githubusercontent.com/7664170/104675094-c07dba80-571f-11eb-9b5a-25fb96ab39da.png)

5. At this time, WORK is unable to respond to other requests. Work is stuck, and all tasks in DS are waiting for execution.
6. After you kill applicaiton manually, the task is normal.
7. version 1.3.4

1、工作流实例中包含spark任务，通过cluster模式提交到yarn上执行。
2、通过ds界面停止工作流实例。
3、此时ds会在work主机上发送kill指令终止提交的任务。
4、jps查看work节点会看到application -kill指令。
5、此时work处于无法响应其他请求的状态，work卡死，DS中所有任务处于等待执行状态。
6、手动kill掉applicaiton后，任务正常。

**Comment by baijun** [comment]
@xingchun-chen Please help to confirm this bug thx.

**Comment by baijun** [comment]
@BoYiZhang  Please help to confirm this bug thx.

**Comment by BoYiZhang** [comment]
If your version is lower than 1.3.4, please refer to PR:

https://github.com/apache/incubator-dolphinscheduler/pull/2965

**Comment by baijun** [comment]
@BoYiZhang my version is 1.3.4

**Comment by caishunfeng** [comment]
Hi @baijun This issue will be closed because no update for a long time. You can check it again in latest version and reopen this issue if need.
