### ISSUE TITLE
[Improvement][API] Reduce the size of returned data for list interfaces

### ISSUE THREAD

**Issue by chengshiwen** [apache/dolphinscheduler#4466]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
The returned data contains detailed information, and its size is very large, resulting in slow response speed.

**What are the current deficiencies and the benefits of improvement**
- Improve access speed of the list interfaces

**Which version of DolphinScheduler:**
 -[1.3.4]

**Describe alternatives you've considered**
Reduce the redundant fields in returned data for the list interfaces

**Comment by qmengss** [comment]
I will fix it. please assign it to me!

**Comment by chengshiwen** [comment]
@CalvinKirs Please assign it to @qmengss, thx!

**Comment by CalvinKirs** [comment]
Some query list interfaces return data that is too large. In fact, this is not necessary. We should split it into two interfaces, one query list (data content is often determined by the interface display content, do not return too much), when users need When inquiring details, go to the request details interface.

**Comment by qmengss** [comment]
> Some query list interfaces return data that is too large. In fact, this is not necessary. We should split it into two interfaces, one query list (data content is often determined by the interface display content, do not return too much), when users need When inquiring details, go to the request details interface.

hi, I'm not familiar with the project yet, the issue was not specified which query interface has the problem that return redundant fields, so I try to find out the query list interface by reading code, and I found this two suspicious interfaces:

- instance/list-paging
- task-instance/list-paging

I want to confirm with you, is this two interface need to improve ?

**Comment by CalvinKirs** [comment]
> > Some query list interfaces return data that is too large. In fact, this is not necessary. We should split it into two interfaces, one query list (data content is often determined by the interface display content, do not return too much), when users need When inquiring details, go to the request details interface.
> 
> hi, I'm not familiar with the project yet, the issue was not specified which query interface has the problem that return redundant fields, so I try to find out the query list interface by reading code, and I found this two suspicious interfaces:
> 
> * instance/list-paging
> * task-instance/list-paging
> 
> I want to confirm with you, is this two interface need to improve ?

Yes, you are welcome to submit pr

**Comment by CalvinKirs** [comment]
You can create sub-issues for specific sub-issues
