### ISSUE TITLE
[Improvement][UI] Improve ui render speed, especially in the first screen

### ISSUE THREAD

**Issue by chengshiwen** [apache/dolphinscheduler#4467]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
The access speed is slow, especially in the first screen

**What are the current deficiencies and the benefits of improvement**
- Improve access speed and user experience

**Which version of DolphinScheduler:**
 -[1.3.4]

**Describe alternatives you've considered**
- Dynamic & Async Components
- Lazy Loading Routes
- Use Library and Component on Demand (especially in the first screen)
- Multi Page Entry Points in Webpack
- Code Splitting in Webpack
- Split Chunks in Webpack
- Use Tool: webpack-bundle-analyzer and coverage
- Image Compression
- Combine small js and css files

**Comment by dailidong** [comment]
good idea
