### ISSUE TITLE
It is recommended to edit the UDF resource file when creating the process. You can upload UDF resources.（建议创建流程时，可以编辑除UDF资源文件. 可上传UDF资源）

### ISSUE THREAD

**Issue by mnloveyx** [apache/dolphinscheduler#447]
It is recommended to edit the UDF resource file when creating the process. It is convenient for users to operate.

---
建议创建流程时，可以编辑除UDF资源文件. 方便用户操作。

**Comment by lgcareer** [comment]
Thank you for your advice! At present, it needs to be uploaded first,you can only select when you create the process again!If more users also raise this question, we will consider adding them later!

**Comment by lidongdai** [comment]
good idea,  could you submit a pull request to implement this ?
