### ISSUE TITLE
Back up the export process and reimport the bug

### ISSUE THREAD

**Issue by yang227** [apache/dolphinscheduler#4485]
\* * * * Description error

Copy all workflows from different projects in the same server to the new project, change the sub-workflows, and the information viewed by the main workflow remains unchanged

In different servers, the main process can be copied, other sub-processes cannot be imported directly, it needs to import all nodes, change the sub-workflow, the information viewed by the main workflow does not change

\* * Copy * *

Steps to reproduce the behavior, such as:

Three design workflow, a workflow, two child workflow, the workflow orchestration son the working state of the workflow, the workflow is copied to the other three machines, or copied to a new project in the new project change within the workflow task scheduling, into the main stream, and then click the workflow, there are any changes in the task of view changes.

** Which version of the Dolphin Scheduler :**

——(1.3.3-preview)

\* * * * Require or improve

You want to replicate the main workflow in different servers, so you can copy all the information of the sub-workflow into it.Change the child workflow, the main workflow can update the changes normally.

**Comment by lenboo** [comment]
@yang227  We have the new copy and export in 2.x, please check it.
