### ISSUE TITLE
[Bug][projects instance] When a running instance is stopped in the workflow instance boundary, the operation is successful, but the instance is always in the ready to stop state.

### ISSUE THREAD

**Issue by quanzhian** [apache/dolphinscheduler#4487]
operation steps:
1. openthe workflow instance page  "xxxx/#/projects/instance/list"
2. found running workflow instance, the workflow instances are real-time synchronization tasks.
3. click the stop button under the operation column
4. the workflow instance state becomes ready to stop, and then it's always ready to stop...

tracking source code discovery:

dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/processor/TaskKillResponseProcessor.java

when the work node kills the workflow instance and responds to the parent node, no logical data processing is done.

my solution is as follows:

![image](https://user-images.githubusercontent.com/8474821/104978433-ca176300-5a3c-11eb-95a5-58ab8bcab8ed.png)

**Comment by xingchun-chen** [comment]
which version?

**Comment by quanzhian** [comment]
version 1.3.2

**Comment by quanzhian** [comment]
> which version?

version 1.3.2

**Comment by lenboo** [comment]
@quanzhian is this issue refer to #4172

**Comment by quanzhian** [comment]
> @quanzhian is this issue refer to #4172

No, It's not a problem. This is a real-time data synchronization task. The tracking log found that kill was executed, but after responding to the parent node, the data status was not processed, just the instance information was printed

**Comment by lenboo** [comment]
Already fixed in 2.x
