### ISSUE TITLE
Resource files have permissions or simple permissions such as public resources private resources or private resources can be delegated to others, etc.（资源文件有权限或简单权限如公有资源私有资源或私有资源可授权给其它人等）

### ISSUE THREAD

**Issue by mnloveyx** [apache/dolphinscheduler#449]
Resource files have permissions or simple permissions such as public resources private resources or private resources can be delegated to others, etc.

---
资源文件有权限或简单权限如公有资源私有资源或私有资源可授权给其它人等

**Comment by lidongdai** [comment]
#404

**Comment by lgcareer** [comment]
Currently,administrator can authorize resource files to other users

**Comment by mnloveyx** [comment]
Which version of escheduler  can authorize resource files to other users

**Comment by lgcareer** [comment]
You need to log in as an administrator and then authorize
