### ISSUE TITLE
[Feature][ui] Add 'About' menu to top-right dropdown menu

### ISSUE THREAD

**Issue by arvin0810** [apache/dolphinscheduler#4499]
*Add 'About' menu to top-right dropdown menu*

**Description**
Currently if a regular DS user want to know the core version of DS, there's no entry for him to get this information, unless he ask the system administrator to log on the server to lookup the jars, which is quite inconvenient.

**Possible Solution**
We can simply add an 'About' menu to top-right dropdown menu, after clicking on it, there will be a popup window or a new page which contains version info and others if necessary.

*添加‘关于’菜单到右上角下拉菜单*

**描述**
在当前版本的DS中,如果普通用户想获取当前DS的版本号,系统中没有相应的入口去获取这些信息,只能通过寻找系统管理员登陆服务器,查看jar版本得知,较为不便.

**解决方案**
在右上角下拉菜单中添加‘关于’菜单,点击后通过弹出狂或新页面展示版本信息,和其他必要信息如API文档地址、帮助文档等.

**Comment by chengshiwen** [comment]
Related issue: #3247

**Comment by hezean** [comment]
[WeOpen Star] I'd like to work on it
