### ISSUE TITLE
spark-sql jdbc driver error

### ISSUE THREAD

**Issue by snycc15** [apache/dolphinscheduler#4514]
建议将sparksql驱动包独立出来，不与hive共用驱动资源，避开后台hive和spark之间版本兼容问题，因为后端平台中组件经常存在兼容问题。我目前环境是HDP 3.1.5，HIV是3.1.1，spark是2.3，即spark 2.3不能使用hive 3.1的驱动资源，spark2.3可直接使用hive-jdbc-uber-2.6.5.jar的包。

**Comment by dailidong** [comment]
good idea, by the way, please add description in English, thx
is there anyone who want to do this feature, please leave message ?
