### ISSUE TITLE
[Feature][API] Support SSO: Single Sign On

### ISSUE THREAD

**Issue by ruancheng77** [apache/dolphinscheduler#4531]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the feature**
A system jump to this for free login.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I want use a hyperlink  jump to this system without login

**Describe alternatives you've considered**

**Additional context**

**Comment by dailidong** [comment]
Do you mean LDAP integration ?  you can refer this PR : https://github.com/apache/incubator-dolphinscheduler/pull/3743

**Comment by ruancheng77** [comment]
Not LDAP! I want a feature for anayone like single sign on .

**Comment by chengshiwen** [comment]
@ruancheng77 
SSO is generally based on CAS or OAuth2, which solution do you want?

**Comment by ruancheng77** [comment]
Oauth2 is the best, but CAS is also OK

**Comment by chengshiwen** [comment]
@ruancheng77 
SSO based on CAS or OAuth2 is not difficult, I will consider this work and notify you in the next period of time, so please keep attention.

**Comment by ruancheng77** [comment]
Thank's!

**Comment by chengshiwen** [comment]
Related issue: #3451

**Comment by Aer1208** [comment]
Is there a plan to support single sign on through integrated CAS in the future

**Comment by zhongjiajie** [comment]
close by https://github.com/apache/dolphinscheduler/pull/8706
