### ISSUE TITLE
Breakpoint rerun cannot be automatically executed backward

### ISSUE THREAD

**Issue by wangchuang07** [apache/dolphinscheduler#4538]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
Workflow automatic timing failed to set failure policy. In addition, when the breakpoint rerun (the whole workflow rerun a day's data from a node), why can't it be started?

**Expected behavior**
The breakpoint is expected to execute normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/38686005/105474150-ed5e3e80-5cd8-11eb-956f-ab00b13db6aa.png)

**Comment by caishunfeng** [comment]
Hi @wangchuang07 This issue will be closed because no update for a long time. You can reopen it if need.
BTW, it's better to provide more info in a issue, like version, how to reproduce.
