### ISSUE TITLE
Workflow cannot select multi-node startup（工作流无法选择多节点启动）

### ISSUE THREAD

**Issue by Balro** [apache/dolphinscheduler#454]
The process definition details do not support the selection of multi-node startup. Only single nodes can be selected to execute forward or backward.
When a node is executed backwards, if the subsequent node depends on other non-selected upstream nodes, the workflow instance cannot be exited normally.

Example:
a -> c
b -> c
Click a to execute backwards, even if a is successful, c will not execute, and the workflow cannot exit automatically. You must manually click Stop.
Is it possible to support both nodes a and c, and then start in order of dependency.

---
流程定义详情不支持选择多节点启动，只能选择单节点向前或向后执行。
当节点向后执行时，如果后续节点依赖其他非选择的上游节点，还会导致工作流实例无法正常退出。

示例：
a -> c
b -> c
点击 a 向后执行，即使 a 成功，c 也不会执行，并且工作流不能自动退出，必须手动点击停止。
是否可以支持同时选择 a 与 c 两个节点，之后按依赖顺序依次启动。

**Comment by lidongdai** [comment]
![image](https://user-images.githubusercontent.com/48329107/59439710-53f65780-8e28-11e9-9e2c-bfefb8bb9604.png)

**Comment by lidongdai** [comment]
thx, very good!
