### ISSUE TITLE
[Question] execute processinstance  "sqoop import data to  Hive",have a error "hive exited status 1"

### ISSUE THREAD

**Issue by SuperHeroBigData** [apache/dolphinscheduler#4561]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
"sqoop import data to  Hive",have a error "hive exited status 1"
But using shell scripts to import Hive is perfectly fine.

**Which version of DolphinScheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by xingchun-chen** [comment]
Your version is too old. You'd better update to version 1.3.4 when using sqoop
