### ISSUE TITLE
It is recommended that the toolbar in the work definition flow be changed to authorizable

### ISSUE THREAD

**Issue by shiliquan** [apache/dolphinscheduler#4562]
It is recommended that the toolbar in the work definition flow be changed to authorizable to use or display, and that the tools available be licensed to use in user authorization.
271/5000 
The reason: 1. In a production environment, when we create accounts for different users, maybe I just want different users to use one of the features, but not the other features, which is more conducive to security management and risk reduction. 2, can use the function to authorize, can not use the function does not give the customer to reflect on the page, can enhance the customer experience, solve some unnecessary explanation and trouble.
![image](https://user-images.githubusercontent.com/42087586/105690216-abcacf00-5f36-11eb-806f-d59c1478541c.png)
![image](https://user-images.githubusercontent.com/42087586/105690470-019f7700-5f37-11eb-9e2e-e76b653766a5.png)

**Comment by xingchun-chen** [comment]
+1

**Comment by shiliquan** [comment]
哪位大神来搞一下这个功能啊，我觉得还是很重要得啊！

**Comment by felix-thinkingdata** [comment]
> 哪位大神来搞一下这个功能啊，我觉得还是很重要得啊！

So let me do that.
