### ISSUE TITLE
[Feature][SqlTask] Make main sql on sqltask with multi statement

### ISSUE THREAD

**Issue by brucemen711** [apache/dolphinscheduler#4563]
**Describe the feature**
Currently, i saw dolphinscheduler sqltask have presql, mainsql and postsql. But only presql and postsql have multi choice and it not convenient and easy to use. 

**Describe the solution you'd like**
For example, we using pentaho and familar with sql step, it support multi statement with ";" delimeter. It makes we easily copy and paste bunch of sql code to sql step and run it all in once, maybe sqltask can be the same.

**Additional context**
![image](https://user-images.githubusercontent.com/54098579/105693159-fdbd2600-5f31-11eb-91b0-4d6a36f05b43.png)

**Comment by brucemen711** [comment]
I already implement this feature for internal usecase, if needed i will create a pull request.

**Comment by lgcareer** [comment]
@brucemen711 Great,you can leave the message in the issue [1],now this feature is applyed by a Overseas Contributors,I think you can give hime some help.

[1] https://github.com/apache/incubator-dolphinscheduler/issues/3799

**Comment by xingchun-chen** [comment]
Thank you for your feedback,   look forward to your contribution

**Comment by dailidong** [comment]
@brucemen711,  you also can submit a PR to solve this issue

**Comment by dailidong** [comment]
> I already implement this feature for internal usecase, if needed i will create a pull request.

@brucemen711,  good job, you also can submit a PR to solve this issue

**Comment by brucemen711** [comment]
Ok, i will create a pull request.

**Comment by Segun-Ogundipe** [comment]
> > I already implement this feature for internal usecase, if needed i will create a pull request.
> 
> @brucemen711, good job, you also can submit a PR to solve this issue

@dailidong, I'm working on this as my task during the outreachy internship period. Can the Implementation by @brucemen711 hold off from the PR until I submit mine?

This is so I can work on this without wanting to check his solution to this. This would help me learn.
His PR can be accepted afterwards as the solution
