### ISSUE TITLE
On the flow definition details page, you cannot automatically typeset, and you cannot directly expand the subprocess.

### ISSUE THREAD

**Issue by Balro** [apache/dolphinscheduler#457]
After comparing azkaban, make some suggestions.
1. On the stream definition details page, you cannot automatically typeset. Manual drag and drop, facing a large number of dependencies and nested streams, is not easy to maintain. It is not easy to visually find the dependencies of each job. It is recommended to add an automatic layout switch to manually select whether automatic typesetting is required.
2. In the flow definition, the sub-flowchart cannot be expanded directly, and you must click to enter the sub-process and then return. Not conducive to the operation of the sub-process. It is recommended to add the "Expand Sub-Process" and "Enter Sub-Process" buttons to the sub-process icon.

---
对比了azkaban后，提一些建议。
1. 在流定义详情页面，不能自动排版。手动拖拽的方式，面对有大量依赖和嵌套的流，不易维护。且不易直观发现各作业的依赖关系。建议增加自动排版开关，手动选择是否需要自动排版。
2. 流定义中，无法直接展开子流程图，必须点击进入子流程之后再返回。不利于子流程的操作。建议在子流程图标上，右键增加“展开子流程”和“进入子流程”按钮。

**Comment by lidongdai** [comment]
great advice！ thx!
we will implement it later!

**Comment by swxchappy** [comment]
![image](https://user-images.githubusercontent.com/36871730/60324725-1a8d2280-99b8-11e9-9160-c7b04feb9a5e.png)
确实可以增加一个 “点击父流程可以查看子流程任务执行时间甘特图”
