### ISSUE TITLE
[Bug][service]  task success but node status  failed 

### ISSUE THREAD

**Issue by dickson-bit** [apache/dolphinscheduler#4578]
## node 
machine: **host1**
type:  shell
content:   
`
ssh -t  user@host2  -i ~/private_key   " bash /home/vastdb/code/script/test.sh"
echo $?
`

### reason
test.sh file contains   hive  query command,   which will be executed on host2,   host2  has an isolated  hadoop  system,  **host1** can't direct  visit the system.

>worker_log

`
 org.apache.dolphinscheduler.common.utils.HadoopUtils:[206] - application url : http://yarnIp1:8088/ws/v1/cluster/apps/%s
[ERROR] 2021-01-26 19:39:49.371 org.apache.dolphinscheduler.common.utils.HttpUtils:[73] - yarnIp1: Name or service not known
java.net.UnknownHostException: yarnIp1: Name or service not known
` 

> console log

`
[INFO] 2021-01-26 19:39:49.332  - [taskAppId=TASK-5-50-70]:[127] -  -> MapReduce Jobs Launched: 
	Stage-Stage-1: Map: 34   Cumulative CPU: 608.01 sec   HDFS Read: 4108290122 HDFS Write: 93488199 SUCCESS
	Stage-Stage-2: Map: 1   Cumulative CPU: 46.29 sec   HDFS Read: 93527219 HDFS Write: 93091919 SUCCESS
	Total MapReduce CPU Time Spent: 10 minutes 54 seconds 300 msec
	OK
	Time taken: 130.29 seconds
`

**Expected behavior**
supply a option to stop tracking  hive sql status  in shell type node

**Screenshots**
work log and  console log  above

**Which version of Dolphin Scheduler:**
 -[1.3.4]

**Requirement or improvement**
-  current tracking logic has some bug,  exec script on  ssh remote host  is an example.

**Comment by dailidong** [comment]
> org.apache.dolphinscheduler.common.utils.HadoopUtils:[206] - application url : http://yarnIp1:8088/ws/v1/cluster/apps/%s [ERROR] 2021-01-26 19:39:49.371 org.apache.dolphinscheduler.common.utils.HttpUtils:[73] - yarnIp1: Name or service not known java.net.UnknownHostException: yarnIp1: Name or service not known

here is the root cause, could host1 visit the http://{host2}:8088/ ?

**Comment by dickson-bit** [comment]
> > org.apache.dolphinscheduler.common.utils.HadoopUtils:[206] - application url : http://yarnIp1:8088/ws/v1/cluster/apps/%s [ERROR] 2021-01-26 19:39:49.371 org.apache.dolphinscheduler.common.utils.HttpUtils:[73] - yarnIp1: Name or service not known java.net.UnknownHostException: yarnIp1: Name or service not known
> 
> here is the root cause, could host1 visit the http://{host2}:8088/ ? if application id shows in the shell task, DS will to get the yarn run result through restful api provided by the yarn resource manager. obivously, DS worker server can't get the result because your common.properties configuration is wrong

host1 can't directly visit the   http://{host2}:8088/ ?,   host1  can login to  host2  by ssh method, 
so I can't  modify  the file  common.properties.

**Comment by dickson-bit** [comment]
the  sh script file content : for example  
sh "ssh -tt xxx@10.xx.xx.xx -p 10022 -i  ./conf/private.key   < vip_video_meta_info_base.sh"
I can  login any host in  script file,  which is isolated by the  ssh gateway,   DS can  get the child  process, 
but the  restful api url can't visit on  ds  system

**Comment by dickson-bit** [comment]
![image](https://user-images.githubusercontent.com/2010095/110453236-ebbdce00-8100-11eb-84a2-5462c8510d9f.png)
