### ISSUE TITLE
There is no loop detection when configuring the job.（配置作业时没有循环检测。）

### ISSUE THREAD

**Issue by Balro** [apache/dolphinscheduler#458]
When configuring a job stream, if a circular dependency occurs, it can be saved normally.
Once the job is executed, it will cause the schedule to be stuck, and all subsequent jobs cannot be submitted.
![image](https://user-images.githubusercontent.com/47242371/59494183-36280180-8ebf-11e9-97ea-42efeec9e771.png)
![image](https://user-images.githubusercontent.com/47242371/59494189-3c1de280-8ebf-11e9-9689-1ccac74ccc10.png)

---
配置作业流时，如果出现循环依赖，可以正常保存。
一旦对执行该作业，会导致调度卡死，后续所有作业均无法提交。
![image](https://user-images.githubusercontent.com/47242371/59494183-36280180-8ebf-11e9-97ea-42efeec9e771.png)
![image](https://user-images.githubusercontent.com/47242371/59494189-3c1de280-8ebf-11e9-9689-1ccac74ccc10.png)

**Comment by lidongdai** [comment]
please add picture, thx!

**Comment by lidongdai** [comment]
very good! thx!
we will fix it after version 1.1.0!
