### ISSUE TITLE
[Improvement][scheduler]When configuring the Cron Manage, I think that Start and stop time is not necessary.

### ISSUE THREAD

**Issue by wssmao** [apache/dolphinscheduler#4581]
**Describe the question**
When configuring the Cron Manage, I think that Start and stop time is not necessary.
I only config the cron expression，and the Start and stop time is Optional.
![image](https://user-images.githubusercontent.com/39487209/105927940-f3a93d80-607f-11eb-8d78-52d696123099.png)

**Which version of DolphinScheduler:**
 -[1.3.4-release]

**Comment by xingchun-chen** [comment]
In my opinion, the start and stop times do not affect the performance. The default time is used for tasks that need to run all the time, and the time can be selected according to your own needs

**Comment by wssmao** [comment]
I think the start and stop times and the cron expression position exchange are more friendly, and the start and stop times is made into optional configuration (default is no end time). The current design is ambiguous.

**Comment by xingchun-chen** [comment]
The current end time is 100 years after the current time, which is also equivalent to an infinite end time. 
Of course, you can also wait for feedback from other users. If everyone thinks it's not good, it can be optimized

**Comment by finviman** [comment]
I think the start time is important, since the task will run at once after cron manage online , i think it's a bug, but can be avoid by set the start time.
