### ISSUE TITLE
[Discussion][Dolphin-dao] The workflow instance ID is of the int type. One day, the number of workflow instances reaches the upper limit.

### ISSUE THREAD

**Issue by keepmeup** [apache/dolphinscheduler#4588]
**Describe the bug**
如果有1000000个工作流定义，每天每小时跑一次，那么超过90天，工作流实例id自增就会把int用完，第91天会发生什么If there are 1 million workflow definitions and the workflow is executed every hour, the workflow instance ID increases automatically for more than 90 days and the int is used up. What happens on the 91st day?

**Expected behavior**
We expected the workflow can continuous running in the whole year

**Which version of Dolphin Scheduler:**
 -1.3.3

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by felix-thinkingdata** [comment]
What is the size of your cluster?Or did you mention a common problem with self-incrementing IDs

**Comment by keepmeup** [comment]
> a common problem with self-incrementing IDs



> What is the size of your cluster?Or did you mention a common problem with self-incrementing IDs

thanks.
i mean a common problem with self-incrementing IDs. how it works in ds? @felix-thinkingdata

**Comment by keepmeup** [comment]
> What is the size of your cluster?Or did you mention a common problem with self-incrementing IDs

are u still there ,brother
