### ISSUE TITLE
Welcome to join the Slack channel

### ISSUE THREAD

**Issue by dailidong** [apache/dolphinscheduler#4609]
hi,  
   for better instant communication, welcome to join the Slack workspace of Apache DolphinScheduler Community,  the workspace URL:  http://asf-dolphinscheduler.slack.com/

you can join through invitation url:  https://s.apache.org/dolphinscheduler-slack

in one word , welcome to join Apache DolphinScheduler Community

**Comment by dailidong** [comment]
> hi,
> for better instant communication, welcome to join the Slack workspace of Apache DolphinScheduler Community, the workspace URL: http://asf-dolphinscheduler.slack.com/
> 
> you can join through invitation url: https://join.slack.com/t/asf-dolphinscheduler/shared_invite/zt-l8k90ceu-wwUfobaDkJxjzMfZp4y1Ag , this url expires after 30 days.
> 
> in one word , welcome to join Apache DolphinScheduler Community

Slack workspace: https://asf-dolphinscheduler.slack.com , if you want to join , you also can leave your mail address, our contributors will invite you to slack

**Comment by dailidong** [comment]
some mail suffix like qq.com、163.com can't join slack directly, please leave your mail address, I will invite you manually

**Comment by davidzollo** [comment]
If you want to get faster response, please join slack when you have any question.

Welcome to join DolphinSheduler Slack WorkSpace: https://s.apache.org/dolphinscheduler-slack

**Comment by mohamedawnallah** [comment]
@davidzollo This slack workspace link is no longer active
