### ISSUE TITLE
[Feature] dolphinscheduler has no branch features to route jobs 

### ISSUE THREAD

**Issue by babogd** [apache/dolphinscheduler#4628]
在实际工作中，使用ds
调度设计时，经常有分支需求：根据输入参数的不同走不同的分支处理，但DS中并没有这样的分支组件支持（只有根据成功和失败走不同流程的方式，满足不了要求）
不知为何？
[English] When design the job flow, I want branch function support, but in ds, has no this features. 
I don't know why?

**Comment by shiliquan** [comment]
![image](https://user-images.githubusercontent.com/42087586/106255175-a7632680-6254-11eb-8ec4-301fabe63d27.png)

**Comment by xingchun-chen** [comment]
Good idea, anyone can realize it
English is global and necessary. Please update the title in English

**Comment by babogd** [comment]
when add this feature? @CalvinKirs

**Comment by CalvinKirs** [comment]
> when add this feature? @CalvinKirs

if you urgently need this function，You can complete it first and then contribute to the community
