### ISSUE TITLE
[Question] Process/task priority setting does not take effect

### ISSUE THREAD

**Issue by nightxing** [apache/dolphinscheduler#4653]
I have a process definition of 64 datax nodes. There are no dependencies between tasks.I want to specify the priority of certain tasks so that it can be executed first.I know that the priority tasks can be executed first through the connection method, but there will be many non-dependent tasks in the future. If they can be solved by priority setting, it can reduce a lot of manpower operations.

 -[1.3.4]
My environment: 
single-node master, master and worker with default settings

I tried to set the priority of 6 of the tasks as the highest, but when I checked the Gantt chart, I found that the HIGHEST priority task was not executed first, but the MEDIUM priority task was executed first.

I checked the official website document and the priority task will only take effect when there are not enough threads. Can you explain which parameter can determine whether this priority takes effect?

I tried to adjust the master.exec.task.num in master.properties to 6, because the number of my HIGHEST tasks is also 6, so that I can ensure that the HIGHEST tasks run earlier than the MEDIUM tasks. However, it is impossible for me to adjust the value of master.exec.task.num according to the priority number of tasks. This is impossible because tasks will continue to increase and adjust.

I want to know the execution process of task priority and process priority. How can I ensure that the priority information is used to set the task sequence without connecting?

---------------------------------------------------------------------

我有一个64个datax节点的流程定义，任务之间没有依赖关系，所以不需要连线。在这种情况下，我希望指定某些任务的优先级，让它能够优先执行。我知道可以通过连线的方式让优先执行的任务放在最前面执行，但是后续会有很多的无依赖任务，如果可以通过优先级设定将其解决，能够降低很多的人力操作。

 -[1.3.4]

我的环境：
单节点的master，保持默认设置的master和worker

我尝试设定了其中的6个任务的优先级为最高，但是我查看甘特图时发现，HIGHEST优先级的任务并没有最先执行，反而是MEDIUM优先级的任务先执行了。

我查看了官网文档，优先级任务在线程不够时才会生效。能否说明具体哪个参数可以决定这个优先级是否生效吗？
我试过调整master.properties中的master.exec.task.num为6，因为我的HIGHEST task的个数也为6，这样就可以保证HIGHEST的任务早于MEDIUM的任务运行。但是，我不可能根据任务的优先级个数来调整master.exec.task.num的值，这是不可能的，因为任务会不断的增加和调整。

我想知道任务优先级和流程优先级的执行过程，我该如何保证在不连线的情况下通过优先级信息进行任务先后的设置呢？

**Comment by nightxing** [comment]
![海豚调度器-优先级问题](https://user-images.githubusercontent.com/38346297/106472611-ce805900-64dd-11eb-81f8-4a8323866ce6.jpg)

I sorted out a picture through code. I am not sure if it is accurate. If it is true, the priority function does not seem to be useful?
-----
我通过代码整理了一张图片，我不确定是否为准确的，如果真的是这样，优先级的功能感觉并没有什么作用？

**Comment by chengshiwen** [comment]
Related issue: #5218
