### ISSUE TITLE
[Question]What does field `location.nodenumber ` do in the request form while saving or updating dag definition?

### ISSUE THREAD

**Issue by WilliamChen-luckbob** [apache/dolphinscheduler#4655]
coding with feature 1.3.4 release
there might be something wrong with property "location.nodenumber" which is shown in this screenshot.
In the very beginning, I have created several nodes(5 nodes) behind node "company". Property "nodenumber " in request form is 5 after I called the save api (/dolphinscheduler/projects/{projectName}/process/save).
However, I changed those nodes after node "company" and suddenly found that property "nodenumber" will not change after I called the update api (/dolphinscheduler/projects/{projectName}/process/update).
The fact is , no matter how I change the dag definition and call update api, property "nodenumber" wont't change to an expected value.  
Although I have found nothing wrong while running tasks after those changes.
I still wondering if that may lead to something wrong.

我在封装DAG自动生成的功能时，发现了一个问题：
当为节点（如company节点，如下图所示）添加后续节点并保存后，location属性中，会有一个nodenumber字段，这个字段我理解成该节点之后有多少个向下的分支（如果理解不当的话请指出）。
但我在1.3.4 release版的实操中发现，如图所示，我先给company节点添加了很多后续节点，nodenomber会增加相应的数量，但是在删除这些后续节点并更新后，nodenumber并不会因此而变成新的数量，这里company节点不再有任何后续节点，但nodenumber并没有因此而变成期望值0，这可能是个bug，不知是否会因此影响DAG的运行。
![image](https://user-images.githubusercontent.com/58684828/106540119-411f2200-653a-11eb-8e39-fccb61ba4451.png)

**Comment by lenboo** [comment]
@WilliamChen-luckbob  thank you for your feedback on dolphinscheduler.
For better communication, please change the title to english.
