### ISSUE TITLE
[Bug][UI] #4555pr changed the successNode and failedNode fields to strings, resulting in abnormal reading on the front-end

### ISSUE THREAD

**Issue by break60** [apache/dolphinscheduler#4671]
**Describe the bug**
pr #4555
Front-end error log
![image](https://user-images.githubusercontent.com/28628088/106731148-1cb26b00-664a-11eb-9478-5079ceeeef12.png)
Front end influence code
![image](https://user-images.githubusercontent.com/28628088/106731271-423f7480-664a-11eb-8a75-9d71d27931dd.png)
![image](https://user-images.githubusercontent.com/28628088/106731330-52575400-664a-11eb-8865-1606fb14a9e9.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by caishunfeng** [comment]
This issue will be closed because no update for a long time.
