### ISSUE TITLE
Workflow stop but task does not stop

### ISSUE THREAD

**Issue by gaozhenfeng1** [apache/dolphinscheduler#4687]
I stopped the workflow, but the task in the workflow didn't stop, it kept going in circles
![image](https://user-images.githubusercontent.com/62798940/106978017-5f815980-6796-11eb-9df0-b0b2563cdb6c.png)

**Comment by chengshiwen** [comment]
@gaozhenfeng1 Could you show us the worker logs about the issue? Thans so much!
