### ISSUE TITLE
[Feature][User Manage] User password supports multiple encryption methods

### ISSUE THREAD

**Issue by HanWu2** [apache/dolphinscheduler#4698]
目前看到的程序中使用的是MD5进行加密的，是否可以做成加密方式配置化，多重选择加密方式

**Comment by dailidong** [comment]
please describe title and desc in English, thx

**Comment by CalvinKirs** [comment]
hi, is there any flaw in the current encryption method?

**Comment by HanWu2** [comment]
> hi, is there any flaw in the current encryption method?

No problem, the DS is using MD5 encryption, hope to be able to to configure the encryption type, I can use for example SM3
