### ISSUE TITLE
[Feature] deployment support without root or sudo user

### ISSUE THREAD

**Issue by Anilople** [apache/dolphinscheduler#4706]
**Describe the feature**

Let user can deploy dolphinscheduler without root or sudo user.

**Is your feature request related to a problem? Please describe.**

In some companies, like bank, root and sudo user is very troublesome to obtain. 

So users are hard to deploy dolphinscheduler by themself.

**Describe the solution you'd like**

Support an option(maybe from config file) that user can deploy dolphinscheduler without root or sudo user.

Without sudo user, dolphinscheduler may be lose some function, like multi-tenant.

But in some scenarios, user didn't need multi-tenant.

Lose multi-tenant, gain more convinent in some companies.

**Comment by CalvinKirs** [comment]
close by #5129
