### ISSUE TITLE
[Bug][SQL] SQL task do not execute and sending mail failed RuntimeException occurs

### ISSUE THREAD

**Issue by chengshiwen** [apache/dolphinscheduler#4710]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Start docker by `docker-compose up -d`
2. Execute PostgreSQL SQL Task
3. View the log

**Expected behavior**
Bug fixed.

**Screenshots**
![image](https://user-images.githubusercontent.com/4902714/107119603-bfc1e980-68c3-11eb-829a-82ebf34d5310.png)
![image](https://user-images.githubusercontent.com/4902714/107119606-c3557080-68c3-11eb-9931-52afbe82e010.png)
![image](https://user-images.githubusercontent.com/4902714/107119608-c5b7ca80-68c3-11eb-9dbf-b929b972f80c.png)
![image](https://user-images.githubusercontent.com/4902714/107119623-d9fbc780-68c3-11eb-8883-4470594d2526.png)

**Which version of Dolphin Scheduler:**
 -[1.3.x]
 -[dev]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by chengshiwen** [comment]
@chenxingchun This pr can be closed

**Comment by chengshiwen** [comment]
@CalvinKirs This pr can be closed

**Comment by CalvinKirs** [comment]
Fixed in 1.3.5
