### ISSUE TITLE
[Question] How to cancel a task which was submitted to yarn

### ISSUE THREAD

**Issue by banboosgithub** [apache/dolphinscheduler#4712]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
A clear and concise description of what the question is.

If a task was submitted to yarn, such as spark, how to cancel the app when cancel the task by UI ?

org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor#cancelApplication dose not implement this logic.

**Which version of DolphinScheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by davidzollo** [comment]
stop the workflow instance will kill the running yarn task
![image](https://user-images.githubusercontent.com/15833811/107225095-5670e080-6a53-11eb-9c17-0c9c67283a70.png)

**Comment by chengshiwen** [comment]
Close this issue since the question has been replied
