### ISSUE TITLE
[Bug][UI] On the task instance page, when the host is empty, an error will be reported in the access list

### ISSUE THREAD

**Issue by xingchun-chen** [apache/dolphinscheduler#4719]
![image](https://user-images.githubusercontent.com/55787491/107140556-bf762c80-695d-11eb-8863-412709e7d596.png)

**Which version of Dolphin Scheduler:**
 -[1.3.5-prepare]

**Comment by chengshiwen** [comment]
@chenxingchun This pr can be closed
