### ISSUE TITLE
[Feature] Smooth release(平滑发布)

### ISSUE THREAD

**Issue by boandai** [apache/dolphinscheduler#472]
When the Worker node is version upgraded, the running task is self-healing

---
当 Worker 节点进行版本升级时，运行中的任务进行自我修复

**Comment by jxauwxj** [comment]
最简单的办法：
1.限制老版本的worker，不能再分配到任务
2.在worker所在机器，用新版本启动一个新进程
3.老版本的worker,任务运行完后自己退出

**Comment by wuchunfu** [comment]
Good idea
