### ISSUE TITLE
[Question] How to solve the problem of using source mode docker to build project and create Oracle data source failure

### ISSUE THREAD

**Issue by wistwill** [apache/dolphinscheduler#4732]
**Describe the question：**
use source mode docker to build project and create Oracle data source failure.

**Which version of DolphinScheduler:**
-[apache-dolphinscheduler-incubating-1.3.4]

**Additional context**
Using official documents https://dolphinscheduler.apache.org/zh-cn/docs/1.3.4/user_ doc/docker- deployment.html After the build project is started (recommended) in docker compose mode, the creation of Oracle11g data source will fail.

**Comment by chengshiwen** [comment]
@wistwill Because of the commercial license, we cannot directly use the driver and client of MySQL and Oracle. If you want to use Oracle, you can build a new image based on our `apache/dolphinscheduler` image.

by the way , please update/add title and description in English

**Comment by chengshiwen** [comment]
As for MySQL, you need to download [mysql-connector-java-5.1.49.jar](https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.49/mysql-connector-java-5.1.49.jar)

1. Create your `Dockerfile`
```
FROM apache/dolphinscheduler:latest
COPY mysql-connector-java-5.1.49.jar /opt/dolphinscheduler/lib
RUN apk add --update --no-cache mysql-client
```
2. Build the image

**Comment by chengshiwen** [comment]
As for Oracle in Datasource, you only need to download the Oracle driver and put it in the `/opt/dolphinscheduler/lib` directory

**Comment by dailidong** [comment]
> @wistwill Because of the commercial license, we cannot directly use the driver and client of MySQL and Orcal. If you want to use Oracle, you can build a new image based on our `apache/dolphinscheduler` image.
> 
> by the way , please update/add title and description in English
+1
please update/add title and description in English, thx

**Comment by davidzollo** [comment]
+1
please update/add title and description in English, thx

**Comment by dogloster** [comment]
> As for Oracle in Datasource, you only need to download the Oracle driver and put it in the `/opt/dolphinscheduler/lib` directory

I copy the oracle drive ojdbc6.jar to /opt/dolphinscheduler/lib.
then stop-all.sh and start-all.sh.
create a oracle database source still report error:
org.apache.dolphinscheduler.api.service.DataSourceService:[446] - oracle.jdbc.driver.OracleDriver
java.lang.ClassNotFoundException: oracle.jdbc.driver.OracleDriver

I can connect oracle by Dbvisualizer with the oracle oracle drive.
what's wrong with me?
dolphinscheduler is 1.3.6.

**Comment by chengshiwen** [comment]
@dogloster You can refer to https://dolphinscheduler.apache.org/en-us/docs/1.3.6/user_doc/docker-deployment.html, and see `How to support Oracle datasource in Datasource manage?`

**Comment by davidzollo** [comment]
> > As for Oracle in Datasource, you only need to download the Oracle driver and put it in the `/opt/dolphinscheduler/lib` directory
> 
> I copy the oracle drive ojdbc6.jar to /opt/dolphinscheduler/lib.
> then stop-all.sh and start-all.sh.
> create a oracle database source still report error:
> org.apache.dolphinscheduler.api.service.DataSourceService:[446] - oracle.jdbc.driver.OracleDriver
> java.lang.ClassNotFoundException: oracle.jdbc.driver.OracleDriver
> 
> I can connect oracle by Dbvisualizer with the oracle oracle drive.
> what's wrong with me?
> dolphinscheduler is 1.3.6.

if you still have any questions, please 
Chat rooms are great for quick questions or discussions on specialized topics. The following chat rooms are officially part of Apache DolphinScheduler; welcome to join the Slack workspace, the workspace URL: http://asf-dolphinscheduler.slack.com/
you can join through invitation url: [https://s.apache.org/dolphinscheduler-slack](https://s.apache.org/dolphinscheduler-slack)
this chat room is used for questions and discussions related to using DolphinScheduler.
