### ISSUE TITLE
[Bug][Alert] Alert instance edit page partial parameter values are not displayed

### ISSUE THREAD

**Issue by zhuangchong** [apache/dolphinscheduler#4776]
**Describe the bug**
Alert instance edit page partial parameter values are not displayed

![image](https://user-images.githubusercontent.com/37063904/107958152-90eef600-6fdc-11eb-9e95-bab265999605.png)

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Go to 'Alert instance management'
2. Click on 'Edit button for an alert instance'
3. See error

**Which version of Dolphin Scheduler:**
 -[dev]

I will fix it

**Comment by WilliamChen-luckbob** [comment]
@CalvinKirs 
There may be some bugs in vue code in the module of ui. 

There are the same problems in email alert instance edit page too.

At the same time, while updating the alert instance, some necessary colums were missing so after updated alert instance, some columns were missing and that lead to some runtime exceptions.

e.g. while using email plugin, show type will missing after updating the alert instance.

I've got no such ablilities to develop vue code, so,I just suggest some bug tips.

**Comment by zhuangchong** [comment]
> @CalvinKirs
> There may be some bugs in vue code in the module of ui.
> 
> There are the same problems in email alert instance edit page too.
> 
> At the same time, while updating the alert instance, some necessary colums were missing so after updated alert instance, some columns were missing and that lead to some runtime exceptions.
> 
> e.g. while using email plugin, show type will missing after updating the alert instance.
> 
> I've got no such ablilities to develop vue code, so,I just suggest some bug tips.

I think what you said is the same as what I reported above
