### ISSUE TITLE
[Feature][SQL]  SQL task enhanced verification

### ISSUE THREAD

**Issue by BoYiZhang** [apache/dolphinscheduler#4789]
In the current version, when writing SQL statements, the SQL task type cannot contain semicolon ";". Otherwise, an error will be reported when executing

It is recommended to enhance the verification in the front end. If there is a semicolon ';' in the SQL, you will be prompted

Note: just give prompt, don't fail verification. For example, the comment contains semicolon, which makes it impossible to save

---------------------------------------------

目前版本, sql任务类型 写sql语句的时候,不能包含分号";" . 否则执行的时候报错.
建议在前端增强校验, 如果sql中存在 分号";"  给与提示.
注意: 只给与提示就行不要校验不通过, 比如注释中包含分号,导致不能保存这是不合理的.

**Comment by wanghong1314** [comment]
please assign me,  i'll try

**Comment by Rishav-Saw** [comment]
where do I have to fix the error ?
I have just created an account on GitHub and just know basic details of it but i have knowledge of Java!
