### ISSUE TITLE
[Question] Is spark datasource the same as hive datasource?

### ISSUE THREAD

**Issue by lexiLiu** [apache/dolphinscheduler#4791]
Analysis of source code，In the dolphin scheduler, spark datasource and hive datasource are ultimately connected to hive datasource. Why should we distinguish them? 

![image](https://user-images.githubusercontent.com/9802421/108300654-af6f1000-71db-11eb-9dcc-6576944615fe.png)
![image](https://user-images.githubusercontent.com/9802421/108300573-8b133380-71db-11eb-890b-4676f888043b.png)

**Comment by zhuangchong** [comment]
@lexiLiu 
Dolphin's Spark Datasoure is connected to the Spark Thrift Server; Spark Thrift Server is essentially the same as HiveServer2 and Spark Thrift Server is encapsulated on HiveServer2 and can use Hive JDBC connections. The Spark DataSource and Hive DataSoure backend source code is the same, This part of the code duplication in this section, welcome to submit PR optimization.
