### ISSUE TITLE
[Bug][Module Name] the same workflow  in the ui

### ISSUE THREAD

**Issue by SuperHeroBigData** [apache/dolphinscheduler#4800]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:

**Expected behavior**

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by chengshiwen** [comment]
@SuperHeroBigData This issue is duplicated with #4801, please close this issue and rename the **title** and update the **version of Dolphin Scheduler** in #4801.

**Comment by chengshiwen** [comment]
Close this issue since duplicated with #4801
