### ISSUE TITLE
[Bug][Workflow] The same workflow problem in ui after importing workflow using excelTools

### ISSUE THREAD

**Issue by SuperHeroBigData** [apache/dolphinscheduler#4801]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
I import workflow using excelTools,but the ui view the bug.The same workflow on the ui.

**To Reproduce**
Steps to reproduce the behavior, for example:

**Expected behavior**

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by SuperHeroBigData** [comment]
![image](https://user-images.githubusercontent.com/73939396/108446904-e7d52380-7299-11eb-96f9-19401b85c57d.png)
like this . But  click the offline ,the same one was disapeared.

**Comment by chengshiwen** [comment]
@SuperHeroBigData Please rename the **title** and update the **version of Dolphin Scheduler**.

**Comment by caishunfeng** [comment]
This issue will be closed because no update for a long time. You can reopen it if need.
