### ISSUE TITLE
[Bug][dolphinscheduler-common] when Kerberos authentication is enabled and hadoop.http.authentication.type is set to kerberos and ResourceManager HA is enabled，you cannot get application status 

### ISSUE THREAD

**Issue by daipeng1104** [apache/dolphinscheduler#4809]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
when Kerberos authentication is enabled and hadoop.http.authentication.type is set to kerberos and ResourceManager HA is enabled，you cannot get application status 

**To Reproduce**
Steps to reproduce the behavior, for example:
1. ResourceManager HA enable
2. Kerberos authentication  yarn cluster
3.  http authentication  enable ,hadoop.http.authentication.type is set to kerberos . see detail https://hadoop.apache.org/docs/r2.7.6/hadoop-project-dist/hadoop-common/HttpAuthentication.html
4. run a application on yarn by dolphinscheduler
![image](https://user-images.githubusercontent.com/57783329/108483678-f4776d00-72d5-11eb-9aaf-e575f25fd364.png)

**Expected behavior**
application success on yarn ,but dolphinscheduler get failed status 

**Screenshots**
status on yarn 
![image](https://user-images.githubusercontent.com/57783329/108484255-9bf49f80-72d6-11eb-86fe-dc24c668e84a.png)

log
![image](https://user-images.githubusercontent.com/57783329/108484485-d0685b80-72d6-11eb-985a-5c0ec5c225f0.png)

**Which version of Dolphin Scheduler:**
1.3.5

** improvement**
- when kerberos enable，use  KerberosHttpClient   in YarnHAAdminUtils.getRMState method

**Comment by zhuangchong** [comment]
What are the following two property configurations in the common.properties file

```
yarn.resourcemanager.ha.rm.ids=192.168.xx.xx,192.168.xx.xx
yarn.application.status.address=http://ds1:8088/ws/v1/cluster/apps/%s
```

**Comment by daipeng1104** [comment]
> What are the following two property configurations in the common.properties file
> 
> ```
> yarn.resourcemanager.ha.rm.ids=192.168.xx.xx,192.168.xx.xx
> yarn.application.status.address=http://ds1:8088/ws/v1/cluster/apps/%s
> ```


yarn.resourcemanager.ha.rm.ids=192.168.1.55,192.168.1.56
yarn.application.status.address=http://yarnIp1:8088/ws/v1/cluster/apps/%s

**Comment by zhuangchong** [comment]
@daipeng1104 
Check that YARN IP (192.168.1.55,192.168.1.56) is valid

Application by accessing http://192.168.1.55:8088/ws/v1/cluster/info and http://192.168.1.56:8088/ws/v1/cluster/info to detect the state determine the survival of the ResourceManager
Look through you provide log, 192.168.1.55, 192.168.1.56 invalid IP, to active the ResourceManager

**Comment by daipeng1104** [comment]
> @daipeng1104
> Check that YARN IP (192.168.1.55,192.168.1.56) is valid
> 
> Application by accessing http://192.168.1.55:8088/ws/v1/cluster/info and http://192.168.1.56:8088/ws/v1/cluster/info to detect the state determine the survival of the ResourceManager
> Look through you provide log, 192.168.1.55, 192.168.1.56 invalid IP, to active the ResourceManager

I found the reason in the source code. In Ha mode,  YarnHAAdminUtils.getAcitveRMName  called to detect the active RM  .     but  when kerberos http authentication enabled  (core-site.xml),  the method will always return null . The reason is because the HttpUtils.get(url) can not get result when kerberos http authentication enabled .    

in the dev branch, the KerberosHttpClient can solve the problem.  but  YarnHAAdminUtils.getRMState methods need to be modified to adapt  kerberos http authentication by call KerberosHttpClient.get() .

**Comment by zhuangchong** [comment]
@daipeng1104 

You are welcome to submit a PR to fix this.
