### ISSUE TITLE
[Bug][API] The API calls the workflow instance query interface and queries all the data when the time parameter is wrong

### ISSUE THREAD

**Issue by zhuangchong** [apache/dolphinscheduler#4816]
**Describe the bug**
The API calls the workflow instance query interface and queries all the data when the time parameter is wrong

**To Reproduce**
1. API calls the workflow instance list-paging method directly
2. Set parameter startTime='20200101',endTime='20200102'
3. Query return result is all workflow instance data

**Which version of Dolphin Scheduler:**
 -[1.3.4-release,dev]

**Comment by davidzollo** [comment]
good job
