### ISSUE TITLE
[Question] There is only mysql in  "type menu" and "datasource menu" of  sqoop node?

### ISSUE THREAD

**Issue by xyzhh** [apache/dolphinscheduler#4819]
I draw a sqoop node in the DAG,These is only one mysql option in the drop menu of source or target section;I copied ojdbc to sqoop lib dir and dolphinscheduler lib dir,I can import list-tables in oracle with sqoop; I can create  oracle datasource in dolphinscheduler and import data with the  oracle datasource  in datax node; But still I can not see a "oracle" or "postgresql"
options to select in sqoop node ,just only mysql。What could I do ? Thanks!

I meet the trouble in 1.3.4 and 1.3.5

**Additional context**

**Requirement or improvement**
Centos 7.2 or Centos 7.4

**Comment by xingchun-chen** [comment]
Currently, sqoop only supports mysql
