### ISSUE TITLE
[Feature][Server] Add support version control (git support)

### ISSUE THREAD

**Issue by brucemen711** [apache/dolphinscheduler#4820]
**Describe the feature**
Currently dolphinscheduler doesn't have the way to choose which version of workflow to work with. I think we should support this feature to make users safer.

**Describe the solution you'd like**
I saw process instance seems have this function but it not visible to users.

**Describe alternatives you've considered**
Alternatives, i think if integrated with git would be great, some tools like dbt, dataform does. 
How do you think @dailidong @CalvinKirs  ?

**Comment by xingchun-chen** [comment]
The dev branch supports version switching
