### ISSUE TITLE
[Improvement][readme] fix readme.md broken link

### ISSUE THREAD

**Issue by CalvinKirs** [apache/dolphinscheduler#4822]
Subscribe to the mail list: https://dolphinscheduler.apache.org/en-us/docs/development/subscribe.html,

It should be modified to Subscribe to the mail list: https://dolphinscheduler.apache.org/en-us/community/development/subscribe.html

Add slack channel link: https://join.slack.com/t/asf-dolphinscheduler/

Add Twitter link:https://twitter.com/dolphinschedule

**Comment by ptyp** [comment]
Assign to me PLEAZZZZZ.
