### ISSUE TITLE
[Improvement][Api] Support zookeeper 3.6.x

### ISSUE THREAD

**Issue by dddyszy** [apache/dolphinscheduler#4823]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
The current version is not friendly to zookeeper 3.6+

**What are the current deficiencies and the benefits of improvement**
- zookeeper 3.6.2

![image](https://user-images.githubusercontent.com/20266837/108589679-7b8e1900-739a-11eb-90a5-de5ba8ed6aa9.png)
![image](https://user-images.githubusercontent.com/20266837/108589747-e3dcfa80-739a-11eb-8609-f40559816f54.png)
![image](https://user-images.githubusercontent.com/20266837/108589755-ed666280-739a-11eb-861e-53b146dd464e.png)

**Which version of DolphinScheduler:**
 -[dev]

**Describe alternatives you've considered**
A clear and concise description of any alternative improvement solutions you've considered.

**Comment by vimacro** [comment]
i'll do this part @zhanguohao

**Comment by chengshiwen** [comment]
@dddyszy @zhanguohao Maybe this issue and the solved issue #4757 are related. The fixed pr #4799 has been merged into the dev, so could you please check whether this problem does still exist in the latest dev branch? Thanks sincerely!

**Comment by vimacro** [comment]
> @dddyszy @zhanguohao Maybe this issue and the solved issue #4757 are related. The fixed pr #4799 has been merged into the dev, so could you please check whether this problem does still exist in the latest dev branch? Thanks sincerely!

![image](https://user-images.githubusercontent.com/11975398/108651776-78f80480-74fd-11eb-974d-7e95dc31295f.png)
![image](https://user-images.githubusercontent.com/11975398/108651807-890fe400-74fd-11eb-83f6-12c545b86541.png)
It is not a compatibility issue, it has been fixed in the dev branch @xingchun-chen @dddyszy

**Comment by dddyszy** [comment]
@zhanguohao @chengshiwen  ok i'll try it, and another question is whether monitor - Zookeeper Manage show right values?

**Comment by vimacro** [comment]
> @zhanguohao @chengshiwen ok i'll try it, and another question is whether monitor - Zookeeper Manage show right values?

mod the zookeeper config 

`4lw.commands.whitelist=*`
of just `srvr,ruok,wchs,cons`

**Comment by dddyszy** [comment]
> > @zhanguohao @chengshiwen ok i'll try it, and another question is whether monitor - Zookeeper Manage show right values?
> 
> mod the zookeeper config
> 
> `4lw.commands.whitelist=*`
> of just `srvr,ruok,wchs,cons`

ok it works
