### ISSUE TITLE
what is the difference between stop and pause？

### ISSUE THREAD

**Issue by wengieeee** [apache/dolphinscheduler#4824]
when a parocess instance is running ,

I click the stop button,

then the current running task  will be kill or it will wait for the end of the task being executed?

version:1.3.4

-------------------
请问process运行中的停止和暂停有什么区别？
一个正在运行的process，按了停止，是会直接kill掉在运行的task还是说会等待运行中的task执行完毕

我自己的测试是会等待执行中的task执行完毕？是这样么？

**Comment by davidzollo** [comment]
yes, you are right.
stop will kill the running tasks, while pause not stop the runnting task , it will wait the finish of the running tasks

**Comment by wengieeee** [comment]
> yes, you are right.
> stop will kill the running tasks, while pause not stop the runnting task , it will wait the finish of the running tasks

but ,when i click stop button ,my running task still running?why?

**Comment by wushuang3625** [comment]
I have the same question,  can anyone  answer it?
