### ISSUE TITLE
[Bug][Module Name] Process using the dependence component cannot migrate between test and prod environment

### ISSUE THREAD

**Issue by ntupapaya** [apache/dolphinscheduler#4826]
**Describe the bug**
Process using the dependence component cannot migrate between test and prod environment. 
Because in exported json it uses definitionId to refer to the dpendent target, which will be different between test and prod env.
With this problem, I would say the dependence component is not ready for prodtion use. Strongly suggest to fix it.

----
包含依赖组件的流程不能在测试和生产环境间迁移。
因为在导出的json中用了definitionId来指向被依赖的目标, 而id在不同的环境之间导出和导入时是会变的。
由于这个问题的存在，依赖组件实际上不适合生产系统使用。强烈建议修复。

**To Reproduce**
As stated

**Expected behavior**

The process name, task name, etc. should be used when exporting and importing dependent components in the process. Or other field combinations that can guarantee portability and uniqueness.

---
流程中的依赖组件导出和导入时时应当使用流程名称、任务名称等。或其他能保证可迁移性和唯一性的字段组合。

**Screenshots**

**Which version of Dolphin Scheduler:**
1.3.4

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by davidzollo** [comment]
good suggestion
for now ,  the Community is doing workflow definition DAG json splitting, when json splitting done, welcome to join

**Comment by caishunfeng** [comment]
Hi @ntupapaya, this issue had been fixed, please check it again in latest version.
This issue will be closed and you can reopen it if need.
