### ISSUE TITLE
[Feature]Sqoop task should support more database,especially oracle.

### ISSUE THREAD

**Issue by xyzhh** [apache/dolphinscheduler#4827]
In big data project ,as data source ,oracle is usually used, not mysql.I need a way to import data from oracle to hive or hdfs,Why oracle is not supported by sqoop?Or could I  do it by datax without editing custom json?

需要一个方便的办法从oracle向hive采数据啊，hbase应该也有需求吧

**Comment by davidzollo** [comment]
anybody else who also need this feature , please leave a message

**Comment by xxh2000** [comment]
> In big data project ,as data source ,oracle is usually used, not mysql.I need a way to import data from oracle to hive or hdfs,Why oracle is not supported by sqoop?Or could I do it by datax without editing custom json?
> 
> 需要一个方便的办法从oracle向hive采数据啊，hbase应该也有需求吧

你这个需求应该去跟spoop社区提吧。

**Comment by xyzhh** [comment]
> > In big data project ,as data source ,oracle is usually used, not mysql.I need a way to import data from oracle to hive or hdfs,Why oracle is not supported by sqoop?Or could I do it by datax without editing custom json?
> > 需要一个方便的办法从oracle向hive采数据啊，hbase应该也有需求吧
> 
> 你这个需求应该去跟spoop社区提吧。

sqoop支持Oracle啊，不知道为啥DS里没有界面入口。

**Comment by zhenkunlin** [comment]
我也有需求

**Comment by 1220985305** [comment]
I have the same problem, please

**Comment by XufengXufengXufeng** [comment]
Oracle is a widely used database, it should be supported. Please add this feature to DolphineSchedular.

**Comment by Cocytus316** [comment]
I have the same problem, please

**Comment by xucx** [comment]
same problem, please

**Comment by k9flame** [comment]
I think SQOOP should be able to select all the databases that SQOOP itself can support when DS creates the data source，for example Oracle or pg
