### ISSUE TITLE
[Feature][Data Quality] DataQualityApplication Design

### ISSUE THREAD

**Issue by zixi0825** [apache/dolphinscheduler#4829]
- Function
DataQualityApplication uses spark as execution engine and parse the input parameter to generate Connector、Executor and Writer .Read data from different data source through different Connector and use the sql in executor to operate data. Finally write the result into storage engine through the Writer
- Architecture
    - Parameter design
Parse input parameter to generate ConnectorParamters、ExecutorParameters and WriterParameters
    - Flow and DataQualityTask
        - DataQualityTask is a interface, all the connectors、executors and writers must implement the DataQualityTask  
        - A Flow consist of a list of DataQualityTask
        - The DataQualityApplication is to execute all DataQualityTask in Flow to complete the execution logic

**Comment by Geek-Joey** [comment]
Hello, the data quality data we are testing will be written to the local or hdfs. I want to write the result to the database, but I have no idea of implementation. Can you give me some suggestions for key steps? Looking forward to your reply.

**Comment by Geek-Joey** [comment]
Hello, the data quality data we are testing will be written to the local or hdfs. I want to write the result to the database, but I have no idea of implementation. Can you give me some suggestions for key steps? Looking forward to your reply.
