### ISSUE TITLE
[Feature][Document] How to use open api of Apache DolphinScheduler ?

### ISSUE THREAD

**Issue by davidzollo** [apache/dolphinscheduler#4831]
How to use open api of Apache DolphinScheduler ? 

official website github url: https://github.com/apache/incubator-dolphinscheduler-website/tree/master/docs/en-us/1.3.5/user_doc

and the position of api doc is here:
![image](https://user-images.githubusercontent.com/15833811/108622292-bfece800-7472-11eb-866f-08eade20cd9e.png)
 

---

文档需求：怎样使用 DolphinScheduler 的 open api , 可以参考：https://blog.csdn.net/samz5906/article/details/106825655/

**Comment by davidzollo** [comment]
if anybody who is interesting in this task, please leave a message

**Comment by Narenderadonis** [comment]
Yes, I am interested. I want to work on this.

**Comment by davidzollo** [comment]
> Yes, I am interested. I want to work on this.

glad to see you want to do this task, I assigned this issue to you just now. 
if you meet any problem, please leave message.

BTW, we also create slack workspace some days ago, welcome to join the workspace URL: http://asf-dolphinscheduler.slack.com/

you can join through invitation url: https://join.slack.com/t/asf-dolphinscheduler/shared_invite/zt-l8k90ceu-wwUfobaDkJxjzMfZp4y1Ag

**Comment by davidzollo** [comment]
this feature has been opened for a long time, I will find new contributor to finish it
