### ISSUE TITLE
[Bug][worker-config] Worker group is not correct in conf/ worker.properties 

### ISSUE THREAD

**Issue by xingchun-chen** [apache/dolphinscheduler#4833]
1. to configure workers="ark0:cxc1,ark0:worker1" in conf/config/install_config.conf
2. Execute command sh install.sh
3. Worker group is not correct in conf/ worker.properties, display as worker.groups=cxc1worker1 , should be displayed as worker.groups=cxc1,Worker1, zookeeper register two worker nodes 'cxc1' and ’Worker1‘

![image](https://user-images.githubusercontent.com/55787491/108647140-dcc90000-74f2-11eb-834f-7077913a28e5.png)

![image](https://user-images.githubusercontent.com/55787491/108647109-c9b63000-74f2-11eb-9882-9253cd9a6b15.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by woshiwuxiaofei** [comment]
I will try it, please assign it to me.

**Comment by xingchun-chen** [comment]
The issue has been repaired and I will turn it off. Thank you for your feedback @woshiwuxiaofei
