### ISSUE TITLE
[Question] Process definition response data is missing

### ISSUE THREAD

**Issue by ruancheng77** [apache/dolphinscheduler#4836]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
/dolphinscheduler/projects/default/process/save interface response msg is missing org.apache.dolphinscheduler.api.service.ProcessDefinitionService#PROCESSDEFINITIONID

**Which version of DolphinScheduler:**
 -[1.3.3-release]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by chengshiwen** [comment]
@ruancheng77 Hi, could you give us more details to reproduce this issue? Thanks so much!

**Comment by ruancheng77** [comment]
Example's response data for interface /dolphinscheduler/projects/{projectName}/process/save.

{
code: 0
data: null
msg: "成功"
}

Data is null.
