### ISSUE TITLE
[Bug]worker has been in the running state 

### ISSUE THREAD

**Issue by gaoyu2016** [apache/dolphinscheduler#4838]
The master has been in a state of being ready to stop，and worker has been in the running state。
worker log:
[INFO] 2021-02-21 07:50:15.328  - [taskAppId=TASK-37-970238-989024]:[375] - appId:application_1613842645240_14172, final state:RUNNING_EXEUTION
[INFO] 2021-02-21 07:50:16.333  - [taskAppId=TASK-37-970238-989024]:[375] - appId:application_1613842645240_14172, final state:RUNNING_EXEUTION
[INFO] 2021-02-21 07:50:17.339  - [taskAppId=TASK-37-970238-989024]:[375] - appId:application_1613842645240_14172, final state:RUNNING_EXEUTION
[INFO] 2021-02-21 07:50:18.345  - [taskAppId=TASK-37-970238-989024]:[375] - appId:application_1613842645240_14172, final state:RUNNING_EXEUTION
[INFO] 2021-02-21 07:50:19.351  - [taskAppId=TASK-37-970238-989024]:[375] - **appId:application_1613842645240_14172**, final state:RUNNING_EXEUTION
[INFO] 2021-02-21 07:50:20.357  - [taskAppId=TASK-37-970238-989024]:[375] - appId:application_1613842645240_14172, final state:RUNNING_EXEUTION
[INFO] 2021-02-21 07:50:21.362  - [taskAppId=TASK-37-970238-989024]:[375] - appId:application_1613842645240_14172, final state:SUCCESS
[INFO] 2021-02-21 07:50:21.365  - [taskAppId=TASK-37-970238-989024]:[375] - appId:application_1613842645240_15274, final state:SUCCESS
[INFO] 2021-02-21 07:50:21.369  - [taskAppId=TASK-37-970238-989024]:[375] - **appId:application_1613842645240_14932, final state:KILL**

**Comment by zhuangchong** [comment]
Is there a worker log

**Comment by jepsonzhang** [comment]
这个是和目前海豚的停止机制有关，当Api-server接受到外部的命令的时候，会像数据库插入一条command用于停止，master抢到锁之后，从数据库拿到这个command，会将任务流的状态改成准备停止，然后找到任务流对应的运行的任务列表，下发命令给对应的worker，由worker去关闭对应的task的进程，关闭完了再通知master，master再去修改对应的taskInstance的状态，然后master会不停的查看所有运行中的task的状态变成结束的状态，是的话，最终才会把任务流的状态改成停止状态，海豚里面用了大量的异步+状态机来处理这些状态的变迁问题。

**Comment by gaozhenfeng1** [comment]
我碰到的问题一模一样，请问后来怎么解决的呢

**Comment by caishunfeng** [comment]
Hi @gaoyu2016   This issue will be closed because no update for a long time. You can check the latest code and reopen it if need.
BTW, this issue need to provide the DS version and how to reproduce.
