### ISSUE TITLE
[Bug][Docker] 1.3.5 release compose file config error WORKER_GROUP

### ISSUE THREAD

**Issue by wangdazhong001** [apache/dolphinscheduler#4843]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
The configuration item of compose startup file worker service is wrong, WORKER_GROUP here should be WORKER_GROUPS

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Lā qǔ 1.3.5-Release huòzhě zuìxīn jìngxiàng 2. Dǎkāi xiāngguān de docker-compose wénjiàn 3. Zhǎodào róngqì míng wèi dolphinscheduler-worker 4. Qízhōng de environment zhōng WORKER_GROUP, cǐ chù rúguǒ shì WORKER_GROUP bù qǐ zuòyòng, huì yòng mòrèn zhí. Yīng gǎi wèi WORKER_GROUPS
展开
161 / 5000
翻译结果
1. Pull 1.3.5-release or the latest image
2. Open the relevant docker-compose file
3. Find the container named dolphinscheduler-worker
4. WORKER_GROUP in the environment, if WORKER_GROUP does not work here, the default value will be used. Should be changed to WORKER_GROUPS 

**Expected behavior**

**Screenshots**

<img width="376" alt="358411DB-C676-49bc-BBB2-F9BD89EE60A1" src="https://user-images.githubusercontent.com/49627839/108803048-acf22900-75d4-11eb-8c14-20cff10cdc65.png">

**Which version of Dolphin Scheduler:**
 -[1.3.5-release]

**Additional context**

**Requirement or improvement**
- Here to adjust to WORKER_GROUPS

**Comment by chengshiwen** [comment]
@wangdazhong001 Good suggestion! This has been added into [Docker & K8s Improvement Plan](https://github.com/apache/incubator-dolphinscheduler/issues/4837)
