### ISSUE TITLE
[Bug][feature] cannot Save/Update the process including more than one node in Ubuntu

### ISSUE THREAD

**Issue by ptyp** [apache/dolphinscheduler#4846]
**  Describe the bug
The process with two or more nodes can not be saved or updated. The problem does not only occur in the website, but also occur when using API.

** To Reproduce
I am now using Ubuntu 20.04 and Chrome 88. It does not work under FireFox as well. 

** Bug information
There is no error showing in the server side. It only presents a timeout warning. 
![2021-02-03 17-54-43屏幕截图](https://user-images.githubusercontent.com/30622951/108812809-bab2a900-75ea-11eb-858e-0d2267cdee3e.png)

Besides, the front end error is as the screenshot.
![微信图片_20210223151425](https://user-images.githubusercontent.com/30622951/108812441-16306700-75ea-11eb-8d44-7d6b08eb597a.jpg)

**Comment by CalvinKirs** [comment]
Can you provide detailed server logs?

**Comment by ptyp** [comment]
> Can you provide detailed server logs?

The log in the first screenshoot is the only log I got.

**Comment by caishunfeng** [comment]
This issue will be closed because no update for a lone time.
