### ISSUE TITLE
[Bug] Call hadoop job list in php function，process has exited,exitStatusCode:0,but hadoop job list Been running

### ISSUE THREAD

**Issue by gaoyu2016** [apache/dolphinscheduler#4847]
Call hadoop job list in php function，process has exited,exitStatusCode:0,but hadoop job list Been running, worker Been running。
也就是：
php主方法run，调用了get_job_list（hadoop job -list）。
[taskAppId=TASK-37-989222-1008351]:[202] - process has exited, execute path:/home/shared/opt/soft/ds/tmp/dolphinscheduler/exec/process/12/37/989222/1008351, processId:30574 ,exitStatusCode:0 正常退出，
但是：后面还在执行php中的方法中的命令：$cmd = "hadoop job -list ";
[INFO] 2021-02-23 16:35:30.780  - [taskAppId=TASK-37-989222-1008351]:[415] - find app id: application_1613943087944_61608
[INFO] 2021-02-23 16:35:30.780  - [taskAppId=TASK-37-989222-1008351]:[415] - find app id: application_1613943087944_61791

导致worker进程一直在running。

**Comment by zhuangchong** [comment]
Which version? Because the Hadoop task is still running in YARN, all the task pages show that it is running.

**Comment by gaoyu2016** [comment]
1.3.1。
![image](https://user-images.githubusercontent.com/29685418/108824639-eb9bd980-75fc-11eb-8c4c-68f4d8326b77.png)
hadoop job -list 是php主方法调用的函数里面的命令。

**Comment by zhuangchong** [comment]
Look at the 'find app id: application_1613943087944_61791' in your log,It should be your task that starts a yarn task and then starts the PHP monitoring script. The current task display is actually running because the previous yarn task is running

---
看你的日志上记录‘ find app id: application_1613943087944_61791’ ，应该是你这个任务启动了一个yarn任务，之后启动了php 的监控脚本。目前任务显示真正运行就是因为前面的yarn任务是正在运行状态

**Comment by gaoyu2016** [comment]
hadoop job -list

**Comment by davidzollo** [comment]
> hadoop job -list
you'd better not to use this command.

this command will list all the running yarn tasks to the task instance log, these yarn tasks will generate many application ids, DolphinScheduler will monitor all these yarn task until to finish, this operation will cost too  much time

**Comment by gaoyu2016** [comment]
完美解决！
