### ISSUE TITLE
[Feature][dolphinscheduler-server] ds worker wild occupies many jdbc connection

### ISSUE THREAD

**Issue by execdf** [apache/dolphinscheduler#4848]
I install  multiple ds worker on cluster,and then i find  each worker will  occupy a part of  db connection.
 When i try to login at fore-end ,but fail,and then i  fould a exception throws a back-end about jdbc connect fail .
 May be you  should seek  a plan to  replace it 。
![image](https://user-images.githubusercontent.com/42157825/108825082-8a283a80-75fd-11eb-8920-d08a82d1b803.png)

**Comment by davidzollo** [comment]
which verison?

**Comment by chengshiwen** [comment]
@execdf Hi, could you give us more logs about this issue? Thanks so much!

**Comment by chengshiwen** [comment]
Close since the 1.3.6 release has fixed this issue
