### ISSUE TITLE
The maximum number of task nodes that can be placed in a workflow definition

### ISSUE THREAD

**Issue by SuperHeroBigData** [apache/dolphinscheduler#4849]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
A clear and concise description of what the question is.
Create a process with a POST request. After 500 nodes, it will not be able to create a process.
**Which version of DolphinScheduler:**
 -[1.1.0-preview]
1.3.4
**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by xingchun-chen** [comment]
Is there any error message in API log？

**Comment by SuperHeroBigData** [comment]
columns connects 、jsonlocations 
![image](https://user-images.githubusercontent.com/73939396/109111836-997dc400-7774-11eb-9186-3481b1a26cc7.png)，i modify the metadata，it works
