### ISSUE TITLE
[Feature] Support for setting global parameters before running a workflow

### ISSUE THREAD

**Issue by jenna25** [apache/dolphinscheduler#4854]
当测试运行工作流时，一些全局参数可能需要替换为具体的值（如某些时间参数）；现在只能在保存工作流时去设置，使用起来较为不便。希望在运行工作流时，可以动态修改这些全局参数的值。
![image](https://user-images.githubusercontent.com/20807588/108933975-07e45880-7687-11eb-9491-f41789852132.png)

**Comment by davidzollo** [comment]
good idea,  are you interesting in implementing it ?

BTW, please add/update the description in English, thx

**Comment by CalvinKirs** [comment]
There are startup parameters on the dev code, which can be set when the workflow is running. Only for this workflow, you can see if it meets your needs.
