### ISSUE TITLE
[Improvement][API] Status code should one category one interval

### ISSUE THREAD

**Issue by CalvinKirs** [apache/dolphinscheduler#4855]
A category code should be in an interval, we set according to the number of bits
For example, 1-2 digits are a large category range, 3-4 digits are a small category range, and 5-8 digits are specific business codes. Don't keep adding from the 10000, which is not convenient for maintenance.

**Comment by yakcy** [comment]
Assigned to me

**Comment by yakcy** [comment]
@CalvinKirs category code design as :  First category(2 digits)-Secondary category(2 digits)-Three-level category(3 digits)
like PROJECT_NOT_FOUNT(0100004, "project {0} not found ", "项目[{0}]不存在")
![image](https://user-images.githubusercontent.com/10624010/110208831-5a621800-7ec4-11eb-9193-0761302ca068.png)

**Comment by CalvinKirs** [comment]
looks good to me.

**Comment by yakcy** [comment]
update :

![image](https://user-images.githubusercontent.com/10624010/111069590-bfdb8780-8508-11eb-8095-434ae6458128.png)

**Comment by yakcy** [comment]
update:
![image](https://user-images.githubusercontent.com/10624010/111069699-38dadf00-8509-11eb-958d-71d8af418de0.png)
