### ISSUE TITLE
use s3 resource got error

### ISSUE THREAD

**Issue by yaofengchn** [apache/dolphinscheduler#4858]
When using S3, i can't create tenants or files, use hdfs is ok
The configuration is as follows. How to modify it 

![图片](https://user-images.githubusercontent.com/31480221/108939483-bdfe7100-768c-11eb-8669-59d5c329306a.png)
api-server.log
![图片](https://user-images.githubusercontent.com/31480221/108939498-c3f45200-768c-11eb-8189-239554ceee7d.png)

当使用s3的时候，创建租户和创建文件都不行，换成hdfs就可以了

**Comment by chengshiwen** [comment]
In 1.3.x version, the configuration in practice is like as follows:
```
resource.storage.type=S3
resource.upload.path=/dolphinscheduler
fs.defaultFS=s3a://dolphinscheduler
fs.s3a.endpoint=http://xxxxxx
fs.s3a.access.key=xxxxxx
fs.s3a.secret.key=xxxxxx
```
As for your configuration, `defautFS` should be updated to `s3a://dolphinscheduler`, and make sure the directory `/dolphinscheduler` in s3 has been created

**Comment by yaofengchn** [comment]
must be  s3a://dolphinscheduler ？
fs.defaultFS = s3a://dolphinscheduler

can not use  s3a://dolphinscheduler2 even if i had create the bucket s3a://dolphinscheduler2?

必须是s3a://dolphinscheduler这个桶吗？
我现在是创建了s3a://dolphinscheduler2 桶，然后使用这个，报了上面的错

**Comment by chengshiwen** [comment]
@yaofengchn Sorry, I made a mistake. You are right, `dolphinscheduler` in `s3a://dolphinscheduler` stands for bucket. So make sure the bucket `dolphinscheduler2` and the directory `/dolphinscheduler` in s3 has been created, and the tenant associated with the current user has permission to read/write the the bucket `dolphinscheduler2` and the directory `/dolphinscheduler`.
- Check whether the current user is associated with a tenant?
- Check the tenant's read/write permission for the bucket `dolphinscheduler2` in s3

**Comment by yaofengchn** [comment]
@chengshiwen 
thank you
