### ISSUE TITLE
[Bug][Server] Kill yarn application command won't be execute when kill error

### ISSUE THREAD

**Issue by dddyszy** [apache/dolphinscheduler#4862]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
There are two places used 'yarn application -kill',and both of them are in try catch.So if these is some exception in OSUtils.exeCmd(cmd), kill yarn application command won't be execute

**To Reproduce**
Steps to reproduce the behavior, for example:

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/20266837/108960027-3d516c00-76b0-11eb-98e5-096fd27a04af.png)
![image](https://user-images.githubusercontent.com/20266837/108960049-43dfe380-76b0-11eb-92bb-78ef29007ab6.png)
![image](https://user-images.githubusercontent.com/20266837/108960100-59eda400-76b0-11eb-819e-e7c50ed48ab9.png)

**Which version of Dolphin Scheduler:**
 -[dev][release-1.3.5]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by zhuangchong** [comment]
If no contributor claims it, I'll fix it.

**Comment by dddyszy** [comment]
> If no contributor claims it, I'll fix it.

just move it out of try catch.And i think we can do something to prevent kill error,improve pstree or other methods
