### ISSUE TITLE
Dolphinscheduler Complete the installation Unable to initialize login

### ISSUE THREAD

**Issue by ZJ577624359** [apache/dolphinscheduler#4863]
初始用户：admin  
初始密码：dolphinscheduler123  
![image](https://user-images.githubusercontent.com/79566794/108964924-18142c00-76b7-11eb-98d6-9cefb11b5eb1.png)

**Comment by xingchun-chen** [comment]
please update the title in English

**Comment by xingchun-chen** [comment]
please check the api log

**Comment by ZJ577624359** [comment]
问题已解决
