### ISSUE TITLE
[Bug][s3a] There is a problem when the OSS certificate is updated

### ISSUE THREAD

**Issue by xiangffsuper** [apache/dolphinscheduler#4868]
`[ERROR] 2021-02-25 02:01:39.651 org.apache.dolphinscheduler.common.utils.HadoopUtils:[172] - Unable to execute HTTP request: Certificate for <jqops.s3.cn-north-1.jdcloud-oss.com> doesn't match any of the subject alternative names: [*.jdcloud.com, *.cn-east-1.jcloudcs.com, *.cn-east-2.jcloudcs.com, *.cn-north-1.jcloudcs.com, *.cn-south-1.jcloudcs.com, *.jcloud.com, *.jcloudcache.com, *.jcloudcs.com, *.jcr.service.jdcloud.com, *.jdcloud-api.com, *.jdcloudcs.com, *.oss.cn-east-1.jcloudcs.com, *.oss.cn-east-2.jcloudcs.com, *.oss.cn-north-1.jcloudcs.com, *.oss.cn-south-1.jcloudcs.com, *.s3.cn-east-1.jcloudcs.com, *.s3.cn-east-2.jcloudcs.com, *.s3.cn-north-1.jcloudcs.com, *.s3.cn-south-1.jcloudcs.com, jcloud.com, jcloudcache.com, jcloudcs.com, jdcloud-api.com, jdcloudcs.com, jdcloud.com]`

1. the dolphinscheduler version is 1.3.3
2. the bug began to appear yesterday
3. I have tested OSS, and it is OK

**Comment by chengshiwen** [comment]
@xiangffsuper Is it normal today?

**Comment by xiangffsuper** [comment]
@chengshiwen  Because there are some production tasks, I'm already using a local disk to replace OSS. 
from the error log, It looks like there's SSL cache

**Comment by chengshiwen** [comment]
Close since no updates for long time
