### ISSUE TITLE
[Question] Unable to Connect to MySQL datasource

### ISSUE THREAD

**Issue by JIANCHUJUN** [apache/dolphinscheduler#4871]
**Describe the question**
Hi, I am using docker-compose to deploy Dolphinscheduler (1.3.5, official release), but I can't connect to MySQL datasource. I tried to use "docker cp" and copy "mysql-connector-java-5.1.34.jar" into /opt/dolphinscheduler/lib, but the connection still failed. Do I need to change configuration file elsewhere? 

**Which version of DolphinScheduler:**
 -[1.3.5, Docker-Compose]

**Comment by chengshiwen** [comment]
@JIANCHUJUN Please see #4732
If you just want to connect to a mysql datasource, not only you need to execute `docker cp mysql-connector-java-5.1.49.jar /opt/dolphinscheduler/lib` into `api` and `worker` container, you also need to restart all containers by `docker-compose restart`.
**Attention**: The driver `mysql-connector-java-5.1.49.jar` must be required with `>=5.1.47`
```
docker cp mysql-connector-java-5.1.49.jar dolphinscheduler-api:/opt/dolphinscheduler/lib
docker cp mysql-connector-java-5.1.49.jar dolphinscheduler-worker:/opt/dolphinscheduler/lib
docker-compose restart
```

**Comment by JIANCHUJUN** [comment]
Thanks for your Help! It solves the issue.
