### ISSUE TITLE
[Bug][AIP]  Create DIR ALREADY EXIST ERROR

### ISSUE THREAD

**Issue by Zzm0809** [apache/dolphinscheduler#4872]
Resources uploaded on HDFS 
I just used frame file management - >Create a folder and then delete the HDFS just created directory 
and go back to file management - >;Enter the same folder name to report that the resource directory already exists. 

config is

`
resource.storage.type=HDFS

resource.upload.path=/dolphinscheduler/upload

`

See API Log

`
[INFO] 2021-02-25 13:46:45.148 org.apache.dolphinscheduler.api.controller.ResourcesController:[92] - login user vision-bigdata, create resource, type: FILE, resource alias: scripts, desc: , file: -1,/
[ERROR] 2021-02-25 13:46:45.205 org.apache.dolphinscheduler.api.service.ResourcesService:[787] - resource type:FILE name:/scripts has exist, can't create again.
[INFO] 2021-02-25 13:46:58.881 org.apache.dolphinscheduler.api.controller.ResourcesController:[92] - login user vision-bigdata, create resource, type: FILE, resource alias: scripts, desc: , file: -1,/
[ERROR] 2021-02-25 13:46:58.886 org.apache.dolphinscheduler.api.service.ResourcesService:[787] - resource type:FILE name:/scripts has exist, can't create again.
[INFO] 2021-02-25 13:51:11.060 org.apache.dolphinscheduler.api.controller.ResourcesController:[210] - query resource list, login user:vision-bigdata, resource type:FILE, search value:
[INFO] 2021-02-25 13:52:05.042 org.apache.dolphinscheduler.api.controller.ResourcesController:[92] - login user vision-bigdata, create resource, type: FILE, resource alias: scripts, desc: , file: -1,/
[ERROR] 2021-02-25 13:52:05.048 org.apache.dolphinscheduler.api.service.ResourcesService:[787] - resource type:FILE name:/scripts has exist, can't create again.

`

the vision is 1.3.5

**Comment by davidzollo** [comment]
if you directly delete the file on the HDFS, you can upload a file with same name to HDFS 

usually, it is not recommend to directly operate on the hdfs

**Comment by chengshiwen** [comment]
Close since no updates for long time
