### ISSUE TITLE
[Bug]1.3.4 version,Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'history_cmd' at row 1 

### ISSUE THREAD

**Issue by gaoyu2016** [apache/dolphinscheduler#4874]
org.springframework.dao.DataIntegrityViolationException: ### Error updating database. Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'history_cmd' at row 1 ### The error may exist in org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.java (best guess) ### The error may involve org.apache.dolphinscheduler.dao.mapper.ProcessInstanceMapper.updateById-Inline ### The error occurred while setting parameters ### SQL: UPDATE t_ds_process_instance SET process_instance_json=?, command_type=?, warning_group_id=?, recovery=?, timeout=?, history_cmd=?, connects=?, command_start_time=?, failure_strategy=?, host=?, start_time=?, worker_group=?, state=?, process_instance_priority=?, process_definition_id=?, warning_type=?, executor_id=?, task_depend_type=?, is_sub_process=?, max_try_times=?, tenant_id=?, name=?, locations=?, command_param=?, run_times=? WHERE id=? ### Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'history_cmd' at row 1 ; Data truncation: Data too long for column 'history_cmd' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'history_cmd' at row 1
--

**Comment by gaoyu2016** [comment]
`history_cmd` text COMMENT 'history commands of process instance operation'
已经是text了，为什么？

**Comment by zhuangchong** [comment]
Change the field type to longtext

**Comment by xyzhh** [comment]
It's a error message of mysql，nothing about DS.

**Comment by caishunfeng** [comment]
This issue will be closed because no update for a long time.
