### ISSUE TITLE
[Improvement][Docker] Add default login username and password in readme

### ISSUE THREAD

**Issue by alphabet5** [apache/dolphinscheduler#4881]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
Documentation for the docker-compose instructions is missing the default login credentials. (https://github.com/apache/incubator-dolphinscheduler/tree/dev/docker/build)

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Go to https://github.com/apache/incubator-dolphinscheduler/tree/dev/docker/build

**Expected behavior**

The default login username and password (admin / dolphinscheduler123) should be in the readme for the above location.

**Which version of Dolphin Scheduler:**
 -[dev]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by chengshiwen** [comment]
@alphabet5 Thanks for your feedback!
By the way, please rename the title to `[Improvement][Docker] Add default login username and password in readme`

**Comment by CalvinKirs** [comment]
close by #4882
