### ISSUE TITLE
Increase manual labeling task failure function

### ISSUE THREAD

**Issue by hebin-swxc** [apache/dolphinscheduler#492]
Some tasks show success in scheduling, but they are not necessarily true success. I hope to increase the manual labeling task failure function to better realize the recovery failure function.

---
部分任务在调度中显示成功，其实未必是真正的成功。希望增加手动标注任务失败功能，来更好的实现恢复失败功能。

**Comment by dailidong** [comment]
very good idea！we will consider this feature later！

**Comment by dailidong** [comment]
could you submit a pull request to complete this feature?

**Comment by lenboo** [comment]
we can change the task and the process instance state at the back end for that feature , and there are  also some work to be done at the front end.
we need some guys join us.

**Comment by xuchangqun** [comment]
Is this the same as ‘stop’ ?

**Comment by davidzollo** [comment]
has implemented
