### ISSUE TITLE
[Bug][log] download log get return  404

### ISSUE THREAD

**Issue by lijufeng2016** [apache/dolphinscheduler#4921]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Go to task instance page
2. Click on view log btn
3. Click download log btn,then get 404 code

**Expected behavior**
It can download log normally 

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by lijufeng2016** [comment]
fix download log 404 #4922

**Comment by xingchun-chen** [comment]
good job！

**Comment by chengshiwen** [comment]
@CalvinKirs This issue should be closed
