### ISSUE TITLE
[Improvement][server] need to remove unused comments in ZKMasterClient.java

### ISSUE THREAD

**Issue by davidzollo** [apache/dolphinscheduler#4925]
the comments  which marked in red block should be deleted, as follows:

![image](https://user-images.githubusercontent.com/15833811/109612128-358b3f00-7b6a-11eb-87d9-087e70710b17.png)

**Which version of DolphinScheduler:**
 -[dev]

**Comment by ruanwenjun** [comment]
assign to me
