### ISSUE TITLE
A user is slow to open a defined workflow

### ISSUE THREAD

**Issue by zongqiren** [apache/dolphinscheduler#4948]
We encountered a rather confusing problem. The workflow of a user accessing DS on the interface is super slow, and it may take ten minutes. Part of the workflow tasks of a user is very fast, not that the workflow execution is slow. It is because the speed of opening a certain workflow interface of this user is very slow, and it cannot be opened for more than ten minutes. What is the reason? How to troubleshoot the reason for the slow access, or how to solve it

**Comment by xingchun-chen** [comment]
Which version?

Open the browser console to see which interface is slow and what is the JSON value of the workflow

**Comment by zongqiren** [comment]
version 1.3.2&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-dolphinscheduler"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月4日(星期四) 晚上6:15
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"470096567"<470096567@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] A user is slow to open a defined workflow (#4948)





 
Which version?
 
Open the browser console to see which interface is slow and what is the JSON value of the workflow

**Comment by xingchun-chen** [comment]
Check whether the interface /projects/${projects}/process/list-paging returns the processdefinitionjson value

![image](https://user-images.githubusercontent.com/55787491/110303309-340fba00-8035-11eb-9d23-d328dd091f9d.png)

**Comment by CalvinKirs** [comment]
There are many reasons for it. At present, we have released some interface optimization work. Are you willing to complete it?
