### ISSUE TITLE
[Question] create folder or upload file failed?

### ISSUE THREAD

**Issue by HeChuanXUPT** [apache/dolphinscheduler#4950]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
Standalone deployment
resource->file nameger->create folder or upload file get error: hdfs not startup

I have configed:
- conf/env/dolphinscheduler_env.sh: 
  - HADOOP_HOME
  - HADOOP_CONF_DIR
- conf/config/install_config.conf: 
  - deployUser="dolphinscheduler"
  - defaultFS="hdfs://xxx:8020"
  - resourceUploadPath="/dolphinscheduler"
  - hdfsRootUser="dolphinscheduler"
- conf/common.properties
  - resource.upload.path=/dolphinscheduler
  - hdfs.root.user=dolphinscheduler
  - fs.defaultFS=hdfs://xxx:8020

**Which version of DolphinScheduler:**
 -[1.3.5-dolphinscheduler-bin]]

**Additional context**
![image](https://user-images.githubusercontent.com/5425689/109924552-6a7acb80-7cfb-11eb-9256-8fe4d0f2dca8.png)

show hdfs not startup when create Folder

logs:
[INFO] 2021-03-04 15:29:53.991 org.apache.dolphinscheduler.api.controller.ResourcesController:[92] - login user dolphinscheduler, create resource, type: FILE, resource alias: test1, desc: , file: -1,/
[ERROR] 2021-03-04 15:29:53.997 org.apache.dolphinscheduler.api.service.ResourcesService:[102] - resource upload startup state: false

$hdfs dfs -ls /
drwxr-xr-x   - dolphinscheduler supergroup          0 2021-03-04 14:51 /dolphinscheduler (dolphinscheduler create manually)
drwx-wx-wx   - hadoop           supergroup          0 2020-12-31 11:49 /tmp
$ hdfs dfs -ls /dolphinscheduler
drwxr-xr-x   - dolphinscheduler supergroup          0 2021-03-04 14:51 /dolphinscheduler/tmp (tmp create manually)

**Requirement or improvement**
- how to config to use resource ?

**Comment by chengshiwen** [comment]
@HeChuanXUPT Have you set `resource.storage.type=HDFS`?

**Comment by HeChuanXUPT** [comment]
thanks, upload success after set resourceStorageType="HDFS
