### ISSUE TITLE
[Bug][Master] When kill process instance bug it always in READ_STOP state

### ISSUE THREAD

**Issue by lijufeng2016** [apache/dolphinscheduler#4951]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Create a process definition,create a shell node and named BBB,edit shell as follows
```
#!/bin/sh
sleep 3m
echo "i am super man"
```
2. Create a dependency node named AAA,set retry times as more as you can,I set 120 times,then add dependency process,and 
do not run the dependency process today
3. Connect BBB with AAA,BBB dependent on AAA
4. Run the process definition,then kill the process instance on ui page
5. You can see  process instance always in READ_STOP state

1.创建一个工作流定义，创建一个shell节点取名BBB,编辑shell如下
```
#!/bin/sh
sleep 3m
echo "i am super man"
```
2.创建一个依赖节点名叫AAA,尽可能多的设置重试次数，我通过修改源码设置了120次，添加依赖到这个节点，并且依赖的这个节点当天没跑过
3.连接BBB和AAA，BBB依赖AAA
4.手动运行工作流实例，然后在页面上杀掉这个工作流实例
5.你可以看到这个工作流一直处于准备停止状态

**Expected behavior**
User  kill process instance,then change the state to fail

**Screenshots**
![微信图片_20210304160226.png](http://ww1.sinaimg.cn/large/005Cc2n2gy1go7xmdyrb7j31a90gdtb2.jpg)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by dddyszy** [comment]
see #4839 if these is the same log in dolphinscheduler-master.log
