### ISSUE TITLE
[Bug][Sqoop ] Sqoop Query 

### ISSUE THREAD

**Issue by Tsd-217** [apache/dolphinscheduler#4979]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
When I use sqoop query to write SQL statements with single quotation marks, sqoop cannot recognize it

**To Reproduce**
Steps to reproduce the behavior, for example:
step1：
Configure the sqoop query statement, such as select * from table where date ='2021-03-06 '
step2: 
 View the generated script as      --query 'select * from table where date='2021-03-05' AND $CONDITIONS'
Run the log and View generated files  find that the single quotation mark after where is not recognized
step3：
The query statement expected to be generated is  --query  "select * from table where date='2021-03-05' AND /$CONDITIONS"

**Expected behavior**

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[1.1.0-preview]
version of dolphin scheduler  :1.3.1-cdh5.16
version of sqoop 1.4.6-cdh5.14.0 

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by Tsd-217** [comment]
> 
> 
> **For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
> **Describe the bug**
> When I use sqoop query to write SQL statements with single quotation marks, sqoop cannot recognize it
> 
> **To Reproduce**
> Steps to reproduce the behavior, for example:
> step1：
> Configure the sqoop query statement, such as select * from table where date ='2021-03-05 '
> step2:
> View the generated script as --query 'select * from table where date='2021-03-05' AND $CONDITIONS'
> Run the log and View generated files find that the single quotation mark after where is not recognized
> step3：
> The query statement expected to be generated is --query "select * from table where date='2021-03-05' AND /$CONDITIONS"
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Which version of Dolphin Scheduler:**
> -[1.1.0-preview]
> version of dolphin scheduler :1.3.1-cdh5.16
> version of sqoop 1.4.6-cdh5.14.0
> 
> **Additional context**
> Add any other context about the problem here.
> 
> **Requirement or improvement**
> 
>     * Please describe about your requirements or improvement suggestions.

**Comment by Eights-Li** [comment]
ds-1.3.4 fixed this bug
