### ISSUE TITLE
The spark submitted task runs successfully, but the UI interface icon shows failure, ds version 1.3.4

### ISSUE THREAD

**Issue by BryantYYDS** [apache/dolphinscheduler#4981]
The spark submitted task runs successfully, but the UI interface icon shows failure, ds version 1.3.4

**Comment by zhuangchong** [comment]
Check if there are any exception logs in the worker log file

**Comment by chengshiwen** [comment]
> The spark submitted task runs successfully, but the UI interface icon shows failure, ds version 1.3.4

@MrZhangZetao Could you give us more details for the spark task? such as spark-submit command, exception.

**Comment by Eights-Li** [comment]
check the yarn conf for ds
path: /conf/config/install_config.conf 
config: yarnHaIps or singleYarnIp
