### ISSUE TITLE
Do not replace the contents of variables when executing shell script tasks

### ISSUE THREAD

**Issue by zhaolun7** [apache/dolphinscheduler#4985]
最好改为在父shell中export foo=bar，而不是直接将脚本的内容进行替换
```
echo '----------TEST1-------------'
echo 'test1: ${f_date}'  ${f_date}
echo 'test2: $f_date' $f_date

echo '----------TEST2-------------'
f_date2=${f_date:0:4}-${f_date:4:2}-${f_date:6:2}
echo $f_date2
echo '----------TEST3-------------'
f_date=${f_date:0:4}-${f_date:4:2}-${f_date:6:2}
echo $f_date
```
![image](https://user-images.githubusercontent.com/16096787/110206956-e58ae000-7ebb-11eb-8392-36f493788764.png)

![image](https://user-images.githubusercontent.com/16096787/110206973-f8051980-7ebb-11eb-8b18-0c47b276cf4f.png)

**Comment by davidzollo** [comment]
English is needed
