### ISSUE TITLE
[Improvement][Master] Remove master delete task execution script file operations and ProcessInstance processDefinition null pointer.

### ISSUE THREAD

**Issue by zhuangchong** [apache/dolphinscheduler#4986]
**Describe the question**
1.Remove master delete task execution script file operations
2.ProcessInstance processDefinition null pointer.

**Which version of DolphinScheduler:**
 -[dev]

![iShot2021-03-03 13 01 32](https://user-images.githubusercontent.com/37063904/110207986-744e2b80-7ec1-11eb-88d6-514f1ad3e5c7.png)

**Comment by chengshiwen** [comment]
@zhuangchong  This is not a problem. Please set `-Dlogging.config=classpath:logback-master.xml`.
