### ISSUE TITLE
[Improvement][Worker] Rename worker.weight to worker.host.weight

### ISSUE THREAD

**Issue by chengshiwen** [apache/dolphinscheduler#4997]
**Describe the question**

The semantics of the configuration `worker.weight` in worker is not clear, it is recommended to rename the item to `worker.host.weight`

**What are the current deficiencies and the benefits of improvement**

- Cleaner and more understandable semantics

**Which version of DolphinScheduler:**
 -[dev]

**Describe alternatives you've considered**

Alternatives:

- `worker.exec.weight`
- `worker.task.weight`
- `worker.select.weight`
- `worker.dispatch.weight`

**Comment by ruanwenjun** [comment]
I understand your idea, and I can submit a pull request if you are sure to make this change.

**Comment by chengshiwen** [comment]
Not sure yet

**Comment by CalvinKirs** [comment]
worker.host.weight? how do you think?

**Comment by chengshiwen** [comment]
> worker.host.weight? how do you think?

It's better than the alternatives!

**Comment by chengshiwen** [comment]
@ruanwenjun Are you considering solving this issue? thx a lot~

**Comment by ruanwenjun** [comment]
> @ruanwenjun Are you considering solving this issue? thx a lot~

OK，I will finish it as soon as possible

**Comment by chengshiwen** [comment]
@ruanwenjun 
Pay attention to search and replace globally:
-`worker.weight`
-`WORKER_WEIGHT`
-`worker weight`
-`private int weight;`

**Comment by CalvinKirs** [comment]
close by #5014
