### ISSUE TITLE
[Bug][MasterServer] MasterServer Process stuck

### ISSUE THREAD

**Issue by jepsonzhang** [apache/dolphinscheduler#4999]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:
1、集群由3个节点组成，正常运行的情况下

2、执行了一个失败的任务流实例故障恢复
3、重复点击了两次

**Expected behavior**
正常情况下应该是任务流故障恢复

**Screenshots**
但是发现任务流实例并没有处于恢复状态，查看master日志
图片: https://uploader.shimo.im/f/LirBNspsvgZgCv6U.png
图片: https://uploader.shimo.im/f/R7KW1JYGjyd1M92z.png
图片: https://uploader.shimo.im/f/oQhDhQX5sHzcPI1I.png
三个节点的master几乎同一个时间点内抢到了ZK的锁，然后拿到了任务流实例重跑的命令，日志无下文了

**Which version of Dolphin Scheduler:**
 -[1.3.5-release]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.
[MasterServer_thread_3.txt](https://github.com/apache/incubator-dolphinscheduler/files/6098650/MasterServer_thread_3.txt)
[MasterServer_thread_1.txt](https://github.com/apache/incubator-dolphinscheduler/files/6098651/MasterServer_thread_1.txt)
[MasterServer_thread_2.txt](https://github.com/apache/incubator-dolphinscheduler/files/6098652/MasterServer_thread_2.txt)

**Comment by jepsonzhang** [comment]
日志截图我重新上传上来
![13](https://user-images.githubusercontent.com/18161585/110268963-964cc880-7ffd-11eb-9617-6bf91e222f7b.png)
![14](https://user-images.githubusercontent.com/18161585/110268968-98168c00-7ffd-11eb-91db-09c0dfeec96f.png)
![15](https://user-images.githubusercontent.com/18161585/110268972-9baa1300-7ffd-11eb-80c4-b5a7ffd3f860.png)

**Comment by caishunfeng** [comment]
Hi @jepsonzhang Please check the latest code again. This issue will be closed and you can reopen it if need.
