### ISSUE TITLE
Unable to execute shell

### ISSUE THREAD

**Issue by ZJ577624359** [apache/dolphinscheduler#5004]
![image](https://user-images.githubusercontent.com/79566794/110295296-e9d60b00-802b-11eb-8c34-1a9ad155c64a.png)

**Comment by ZJ577624359** [comment]
环境变量没问题，在命令行是可以执行的。

**Comment by chengshiwen** [comment]
@ZJ577624359 Could you give us more details about the shell task? What is the shell command?

**Comment by ZJ577624359** [comment]
@chengshiwen 
#!/bin/sh
#日期参数
CURRENT_DATE=`date +%Y%m%d`
echo '当前日期参数:CURRENT_DATE'
最基础的打印日期
想问下dolphinscheduler 登录linux是用什么用户。

**Comment by ZJ577624359** [comment]
问题已解决，非常感谢，主要问题是dolphinscheduler_env.sh环境变量，官网文档配置写的不太清晰，导致没有加入自己主机老的$PATH

**Comment by chengshiwen** [comment]
@ZJ577624359 Welcome to submit pr to participate in the DolphinScheduler open source community

**Comment by chengshiwen** [comment]
@ZJ577624359 Hi, since this issue has been solved, so could you close it? thx~

**Comment by ZJ577624359** [comment]
@chengshiwen OK

**Comment by bestchenwu** [comment]
@ZJ577624359  dolphinscheduler_env.sh环境变量，官网文档配置写的不太清晰，导致没有加入自己主机老的$PATH ,请问下这个问题到底是怎么解决的
