### ISSUE TITLE
[Improvement][Script] Remove the duplicated $PATH in script/env/dolphinscheduler_env.sh

### ISSUE THREAD

**Issue by chengshiwen** [apache/dolphinscheduler#5011]
**Describe the question**

Remove the duplicated`$PATH` in `script/env/dolphinscheduler_env.sh` and `docker/build/conf/dolphinscheduler/env/dolphinscheduler_env.sh.tpl`

**Which version of DolphinScheduler:**
 -[1.3.x]
 -[dev]

**Comment by Lucaszlei** [comment]
Has this problem been solved?

**Comment by chengshiwen** [comment]
> Has this problem been solved?

Yes

**Comment by Lucaszlei** [comment]
> 
> 
> > Has this problem been solved?
> 
> Yes

Please remove this item from [4124](https://github.com/apache/incubator-dolphinscheduler/issues/4124)
