### ISSUE TITLE
[Improvement][API] Make the return value clearer

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#5015]
**Describe the question**
The return value of some interfaces is not clear, such as you see in xxController.

**What are the current deficiencies and the benefits of improvement**
Clarifying the type of the method's return value can make the code read better.

**Which version of DolphinScheduler:**
 -[1.3.x]
 -[dev]

**Comment by CalvinKirs** [comment]
It is usually recommended that the service return a specific object and be packaged by the controller. This is more intuitive, at least through the controller calling service, we can intuitively see what his specific data return object is. The return interface of service Map<String,Object> is difficult to intuitively understand what it returns.
