### ISSUE TITLE
[Improvement][Worker] Python Command 

### ISSUE THREAD

**Issue by wa-ooo** [apache/dolphinscheduler#5024]
In general, the home is the directory where the software is installed，but the commandInterpreter method use the Python home directory in PythonCommandExecutor.java, which is in the environment variable configuration file needs to be configured PYTHON_HOME to PYTHON_HOME/bin/Python. Obviously, this is unreasonable and misleading

**Describe alternatives you've considered**

```java 
   /**
     * get python home
     *
     * @return python home
     */
    @Override
    protected String commandInterpreter() {
        String pythonHome = getPythonHome(taskExecutionContext.getEnvFile());
        if (StringUtils.isEmpty(pythonHome)) {
            return PYTHON;
        }
        --  return pythonHome
        ++ return pythonHome + "/bin/python";  
    }
```

[dev]

**Comment by chengshiwen** [comment]
@wa-ooo Hi, would you like to submit a pr to fix this issue?
