### ISSUE TITLE
[Improvement][common]When I run a spark task, the webui observation in yarn is successful, but the response result in dolphinscheduler fails.

### ISSUE THREAD

**Issue by didiaode18** [apache/dolphinscheduler#5026]
1. Describe the question

    When I run a spark task, the webui observation in yarn is successful, but the response result in dolphinscheduler fails.

2. What are the current deficiencies and the benefits of improvement

Our default attribute value  yarn.application.status.address=http://ds1:8088/ws/v1/cluster/apps/%s  in common.properties   is not reasonable   and   our  default common.properties No configuration resource.manager.httpaddress.port .
So the reason why we report the error is because of our company's configuration  resource.manager.httpaddress.port  is 23188  
NOT 8088 .
We should  Flexible configuration yarn properties.

3. Which version of DolphinScheduler:

-[1.3.x]
-[dev]

4. Describe alternatives you've considered
We need to  modify resource.manager.httpaddress.port  and yarn.application.status.address  in the code，
In common.properties we only need to modify resource.manager.httpaddress.port，
The yarn task can respond successfully

**Comment by chengshiwen** [comment]
@didiaode18 Could you show us the content of `common.properties`?

**Comment by chengshiwen** [comment]
This issue seems to be similar to #5081

**Comment by didiaode18** [comment]
@chengshiwen
This is my  common.properties,spark task is success, And  dolphinschedule can show success.
# if resourcemanager HA enable, please type the HA ips ; if resourcemanager is single, make this value empty
yarn.resourcemanager.ha.rm.ids=10.172.xx.x,10.172.3xx.x

# if resourcemanager HA enable or not use resourcemanager, please keep the default value; If resourcemanager is single, you only need to replace ds1 to actual resourcemanager hostname.
yarn.application.status.address=http://yarnIp1:23188/ws/v1/cluster/apps/%s
resource.manager.httpaddress.port=23188

    Because of our company's configuration resource.manager.httpaddress.port is 23188 NOT 8088。
    So I found by reading the source code  ,our default common.properties No configuration resource.manager.httpaddress.port
And yarn.application.status.address's port is default 8088.So if our yarn.application.status.address's port is not 8088，
We must modify  yarn.application.status.address and resource.manager.httpaddress.port，dolphinschedule can show success.
   Finally, We can extract these two resource ports into one ,I can solve this issue .

**Comment by didiaode18** [comment]
In class  HadoopUtils

<img width="685" alt="微信图片_20210322172147" src="https://user-images.githubusercontent.com/22792154/111967586-2ed16580-8b33-11eb-85f8-a2c7ec7664b5.png">
<img width="485" alt="微信图片_20210322172203" src="https://user-images.githubusercontent.com/22792154/111967611-35f87380-8b33-11eb-9842-876a2531edfc.png">

**Comment by chengshiwen** [comment]
@didiaode18 Would you like to contribute the pr and join the open source community?

**Comment by didiaode18** [comment]
@chengshiwen  ok，how to join

**Comment by chengshiwen** [comment]
> @chengshiwen ok，how to join

After submiting a pr and merging the pr, you will be invited to our opensource community. Please refer to https://dolphinscheduler.apache.org/en-us/community/development/submit-code.html

**Comment by CalvinKirs** [comment]
close by #5256
