### ISSUE TITLE
Idle timeout expired: 30001/30000 ms

### ISSUE THREAD

**Issue by itonway** [apache/dolphinscheduler#5040]
process/save    java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms

**Comment by chengshiwen** [comment]
@itonway Hi, could you give us more details? such as **the steps to reproduce**, **the DolphinScheduler version** and **the detailed exception stack log**? Thx a lot!

**Comment by CalvinKirs** [comment]
hi, please provide detailed stack information and version,I can't confirm where the heartbeat detection is.thx

**Comment by alanredsheep** [comment]
I met the same issue on 1.3.8 & 1.3.9 (I install 1.3.8 with docker-compose and 1.3.9 with standalone-server) when I tried to save a workflow which containes any datax jobs or any sql jobs. But it works well on shell job. 

What is more confusing, it works perfectly on 1.3.8 at first. Then it suddenly throw exception a few days later when i tried to save my change. 
It seems like I mess up by change the datax job frequently on workflow-instance page. But it doesn't work when i re-install dolphinscheduler with new docker environment. 

system : aliyun cloud linux
(ps: It works well on my vmware machine)

Here is the log in dolphinscheduler-api.log.
```
[INFO] 2021-10-22 15:13:23.919 org.apache.dolphinscheduler.api.controller.ProcessDefinitionController:[139] - verify process definition name unique, user:admin, project name:xxxxx, process definition name:xxxxx
[WARN] 2021-10-22 15:13:53.976 org.eclipse.jetty.server.HttpChannel:[596] - handleException /dolphinscheduler/projects/xxxxx/process/save java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
[WARN] 2021-10-22 15:14:12.987 org.eclipse.jetty.server.HttpChannel:[596] - handleException /dolphinscheduler/projects/xxxxx/process/save java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
[WARN] 2021-10-22 15:14:32.037 org.eclipse.jetty.server.HttpChannel:[596] - handleException /dolphinscheduler/projects/xxxxx/process/save java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
```

pls tell me what message more do you want to know. @chengshiwen @CalvinKirs

**Comment by alanredsheep** [comment]
Now it seems to be related to some network problem. T_T
https://serverfault.com/questions/210408/cannot-ssh-debug1-expecting-ssh2-msg-kex-dh-gex-reply
