### ISSUE TITLE
[Improvement][API] remove the "sql join" for data list interfaces

### ISSUE THREAD

**Issue by qmengss** [apache/dolphinscheduler#5041]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/community/development/issue.html when describe an issue.*
The returned data contains detailed information, some of interfaces get the detailed information by join Sql, that made adverse effect  on performance, resulting in slow response speed.

**Describe the question**

- Improve access speed of the list interfaces

**What are the current deficiencies and the benefits of improvement**
It is better not to write all kinds of join SQL, it may be better to leave it to the business layer to do the association.

**Which version of DolphinScheduler:**
 -[dev]

**Describe alternatives you've considered**
Move the logic to the business layer.

**Comment by qmengss** [comment]
this issue is connected to #4466 ,the following two interfaces can be optimized first:

1. instance/list-paging
2. task-instance/list-paging

**Comment by CalvinKirs** [comment]
I think this is a very necessary job. Can you complete it?

**Comment by qmengss** [comment]
> I think this is a very necessary job. Can you complete it?

ok, I will complete it.
