### ISSUE TITLE
[Feature][Alert-Plugin] [WeChat]Group chat bots alert

### ISSUE THREAD

**Issue by CalvinKirs** [apache/dolphinscheduler#5042]
Our current default enterprise WeChat alert plug-in: only supports message sending from custom applications 

(https://work.weixin.qq.com/api/doc/90001/90143/90371), which is usually complicated to configure and even requires 

Sufficient permissions, therefore, we need to provide another kind of support, that is, group chat robot sending support, it 

usually only needs a simple http request + token, which is similar to the DingTalk plug-in that we implement by default, you 

can refer to the DIngTalk plug-in To achieve (docs: https://work.weixin.qq.com/help?person_id=1&doc_id=13376).

**Comment by EricJoy2048** [comment]
I want to work for this issue.

**Comment by CalvinKirs** [comment]
This may be achieved with http-alert, I will confirm later, if possible, we can write a tutorial.

**Comment by EricJoy2048** [comment]
> This may be achieved with http-alert, I will confirm later, if possible, we can write a tutorial.

Ok.
