### ISSUE TITLE
[Bug][Api] Delete the stopped workflow without deleting the corresponding sub process, the workflow instance name is not displayed in the sub process 

### ISSUE THREAD

**Issue by xingchun-chen** [apache/dolphinscheduler#5048]
1.stop workflow，Workflow contains sub_process
2.delete the workflow, No sub_process were deleted, the workflow instance name is not displayed in the sub process

![image](https://user-images.githubusercontent.com/55787491/111032444-40d24a80-8447-11eb-9bc9-963c9914a06a.png)
**Expected results**
delete the workflow,  need to delete all tasks under the workflow, including sub_process

**Which version of Dolphin Scheduler:**
 -[1.3.6-prepare]

**Comment by CalvinKirs** [comment]
This problem only occurs for users who use postgresql.

The reason is that the t_ds_task_instance table does not add a foreign key delete constraint.
