### ISSUE TITLE
[Bug][master] After failure retry, the task status of successful operation after Condition node is not cleared

### ISSUE THREAD

**Issue by xingchun-chen** [apache/dolphinscheduler#5053]
1. The workflow failed to run

2. workflow instance page, click failed to retry

3. View workflow instance DAG and task instance, shell_ 4 task is always in the successful state. failed to retry again, the shell_ 4 not implemented
![image](https://user-images.githubusercontent.com/55787491/111113436-bf8ccc00-859c-11eb-9832-d2086fe4db5b.png)
![image](https://user-images.githubusercontent.com/55787491/111113474-cfa4ab80-859c-11eb-9a8d-debd87eeac16.png)

**Which version of Dolphin Scheduler:**
 -[1.3.6-prepare]

**Comment by CalvinKirs** [comment]
When the recovery fails, because the shell4 node has already succeeded, it will not be executed again.
