### ISSUE TITLE
[Bug][UI] Can not upload file to correct dir

### ISSUE THREAD

**Issue by lijufeng2016** [apache/dolphinscheduler#5055]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Create 2 file resources dir on UI,named dirA and dirB
2. upload a file  to dirA
3. upload another file to dirB,but this file appear at  dirA but not dirB

**Expected behavior**
Upload file to correct dir

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by chengshiwen** [comment]
close by #5056
