### ISSUE TITLE
start process,FailureStrategy.CONTINUE is not work 

### ISSUE THREAD

**Issue by cyx-code** [apache/dolphinscheduler#5057]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
A clear and concise description of what the question is.

Start the process define, select the failure strategy to continue, but it does not take effect. When the execution of my task node fails, the subsequent nodes are not executed.

**Which version of DolphinScheduler:**
 -[1.3.5.release-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by xingchun-chen** [comment]
At present, the failure strategy is only valid for parallel tasks

**Comment by cyx-code** [comment]
> At present, the failure strategy is only valid for parallel tasks
ok,thanks for your answer
