### ISSUE TITLE
[Improvement][SQL]SQL optimization

### ISSUE THREAD

**Issue by CalvinKirs** [apache/dolphinscheduler#5061]
We should write SQL more granularly, eg, some queries only need to return true or false, but for general purpose, the actual sql statement we write is like this,
```
   select *
         from t_ds_datasource
         where name=#{name}
```

A lot of unnecessary fields were queried, and at the same time, there was no paging.

This is a real business application，As you can see, he only needs one piece of data, but he queried the entire list.
```
List<DataSource> dataSources = dataSourceMapper.queryDataSourceByName(sqlParameters.getString("datasourceName"));
         if (!dataSources.isEmpty()) {
             DataSource dataSource = dataSources.get(0);
             sqlParameters.put("datasource", dataSource.getId());
         }
```

He only needs to know whether there is such a piece of data, but he queried the entire field of the entire list
```
 List<DataSource> queryDataSource = dataSourceMapper.queryDataSourceByName(name.trim());
        if (queryDataSource != null && queryDataSource.size() > 0) {
            return true;
        }
        return false;
```

Of course there are advantages to doing so, but at the same time it also brings many disadvantages, such as what I mentioned above, besides. In most cases, select needs to add a limit limit (maybe the current situation will not be a problem, but the disaster often does not happen in the present).

**Comment by CalvinKirs** [comment]
I just give you an example, you can check our code to optimize for such use. Everyone is welcome to submit PR

**Comment by ruanwenjun** [comment]
I can try this task.

**Comment by CalvinKirs** [comment]
> I can try this task.

This is a big feature, You can create sub-issues

**Comment by allen1128** [comment]
created sub-issue #5930 to fix the same. Please review [5931](https://github.com/apache/dolphinscheduler/pull/5931)
