### ISSUE TITLE
[Spark] resource list use problem

### ISSUE THREAD

**Issue by masterable** [apache/dolphinscheduler#5064]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
A clear and concise description of what the question is.
When I select a resource in the resource list,then run the spark task
It will prompt me that the resource does not exist,but when I log in to the server to check, I find that there is a resource in the path.
Why is there such a situation where resources are available but not quoted?

**Which version of DolphinScheduler:**
 -[1.3.3-preview]

**Additional context**
picture1：
![image](https://user-images.githubusercontent.com/41288492/111277115-0a791300-8673-11eb-8bd7-af51c64f1fb4.png)
picture2:
![image](https://user-images.githubusercontent.com/41288492/111277373-588e1680-8673-11eb-929c-01e63b02a7f1.png)
picture3:
![image](https://user-images.githubusercontent.com/41288492/111277560-8e32ff80-8673-11eb-81e2-3d1229724018.png)

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by chengshiwen** [comment]
@masterable Could you show the content of the file `45_45_48.command`? And is there a leading space in the `spark-work` directory in the resource center?

**Comment by masterable** [comment]
> @masterable Could you show the content of the file `45_45_48.command`? And is there a leading space in the `spark-work` directory in the resource center?

None of this is a problem, the problem lies in the parameter settings

![image](https://user-images.githubusercontent.com/41288492/111285433-1ae1bb80-867c-11eb-9bbe-5477c0d30198.png)
