### ISSUE TITLE
[Improvement][Dao] SQL optimization - check exist

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#5069]
**Describe the question**
As report by #5061, we need to optimize the sql.

**What are the current deficiencies and the benefits of improvement**
Improve the performance about check some exist with cleaner method

**Which version of DolphinScheduler:**
 -[dev]
 -[1.3.6]

**Comment by CalvinKirs** [comment]
Looking forward to your next contribution, btw, is there any remaining to be revised?
