### ISSUE TITLE
[Bug][Module server worker] reboot zk dead node won't delete?

### ISSUE THREAD

**Issue by pifuguoshi** [apache/dolphinscheduler#5075]
**Which version of Dolphin Scheduler:**
 -[1.3.6-dev]

**Additional context**
![image](https://user-images.githubusercontent.com/10048440/111428001-e4ff0e80-8731-11eb-8cb0-3d272c05ffe9.png)

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.
get zkpath not append timestamp
![image](https://user-images.githubusercontent.com/10048440/111428308-47580f00-8732-11eb-8016-fe0fce4c0b50.png)

**Comment by chengshiwen** [comment]
@pifuguoshi This issue is fixed by pr #4996, please see the related issue #4984
