### ISSUE TITLE
spark task is success, but dolphinschedule show fail

### ISSUE THREAD

**Issue by daxiongll** [apache/dolphinscheduler#5081]
the spark demo
![image](https://user-images.githubusercontent.com/29703785/111460123-8dbf6500-8756-11eb-9563-6b626506e380.png)

dolphin show 
![image](https://user-images.githubusercontent.com/29703785/111460189-a3cd2580-8756-11eb-9ddc-45d0da34d04d.png)

yarn history show

![image](https://user-images.githubusercontent.com/29703785/111460238-b182ab00-8756-11eb-880c-a13b3117eae7.png)

**Comment by chengshiwen** [comment]
@daxiongll Could you show us the content of `common.properties`?

**Comment by chengshiwen** [comment]
This issue seems to be similar to #5026

**Comment by 597365581** [comment]
config  yarn address

**Comment by davidzollo** [comment]
> config yarn address

yes.   usually user should check the following the parameters config in the conf/common.properties:
```
yarn.resourcemanager.ha.rm.ids
yarn.application.status.address
```
you should notice the comments on these two parameters

besides, you also should check the worker server runtime log to find the detail exception

**Comment by daxiongll** [comment]
The reason:Depends on the tasks executed by yarn. As a result, it is necessary to determine the success information in the script and the yarn ui at the same time. If the yarn ip is not configured, tasks such as spark will be executed successfully, but dolphinscheduler shows this task failed.
