### ISSUE TITLE
[Question] What new features will be released in version 1.3.6?

### ISSUE THREAD

**Issue by JoshuaZhuCN** [apache/dolphinscheduler#5082]
有哪些新功能会在1.3.6版本中发布？个人比较关注开发分支中的参数传递和流程实例串行这两项功能。它是否会在1.3.6中发布？

What new features will be released in version 1.3.6? I am concerned with the development branch of parameter passing and process instance serialization. Will it be released in 1.3.6？

**Comment by CalvinKirs** [comment]
please refer https://github.com/apache/incubator-dolphinscheduler/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.3.6-release.

This version is temporarily not supported  parameter passing and process instance serialization

btw, 1.3.6 We have suppoort to skywalking monitor , and at the same time, we have made better optimizations for K8s.

**Comment by zhangb0120** [comment]
很期待 流程实例串行 这个功能

**Comment by tercel53** [comment]
是工作流串行吗？期待

**Comment by chengshiwen** [comment]
Brief Release Notes: 
- Skywalking monitor
- Docker & K8s optimization
- Worker group management on UI
- Spark/Flink/MR name feature
- Master/Worker loopback address bug fixed
- Master fault tolerance bug fixed
- Distributed trace feature
- ZK dead server remove
- Kerberos bug fixed

**Comment by zhangb0120** [comment]
1.3.7 这个版本会把串行执行功能加上去吗

**Comment by chengshiwen** [comment]
@zhangb0120 Not sure. Welcome to contribute code
