### ISSUE TITLE
[Improvement][API] Refactored data source creation

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#5083]
**Describe the question**
If we add a new datasource type in the future, we need to make a lot of changes to the code.
For example in `DataSourceController.createDataSource()`. 
We may need to add parameters like `javaSecurityKrb5Conf` and add `required = false`, because other datasource doesn't need the parameter.(This make the method need to receive a large number of parameters and reduce readability).
And in `DataSourceServiceImpl.buildParameter`
We may need to make the same modification. But for any type of datasource, we do the same logic for adding operation.
```
1. check params
2. transform params
3. insert to mysql
```
We need not change the core code

**What are the current deficiencies and the benefits of improvement**
Use a target class to wrap parameters of datasource, and add subclass for each datasource, for example:
```
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, property = "type")
@JsonSubTypes({
        @JsonSubTypes.Type(value = MysqlDatasourceParams.class, name = "1"),
        @JsonSubTypes.Type(value = OracleDatasourceParams.class, name = "2"),
})
public abstract class AbstractDataDourceParams {
    
    public abstract Integer getType();
}
```
The request from the front can be automatically bound to the subclass through jackson deserialization, and the specific data source can be known through the type.
And add check processor or transform processor for each datasource to transform the params to metadata stored in mysql. After that, we needn't change any code when add a new kind of datasource, we just add a new subclass of datasource and add a new transform processor.

**Which version of DolphinScheduler:**
 -[dev]
 -[1.3.6]

**Comment by CalvinKirs** [comment]
SGTM, can you do this job

**Comment by ruanwenjun** [comment]
Sure, I will finish it as soon as possible.

**Comment by ruanwenjun** [comment]
By the way, except for the oracle data source, other data sources do not have the connectType parameter. The back-end does not need to store connectType for all datasource, and the front-end does not need to display null, which will cause confusing.

![image](https://user-images.githubusercontent.com/22415594/112720617-6593eb00-8f3a-11eb-9c50-859c8edbe163.png)

In this pr, we will not store the connectType for other datasource besides oracle.

**Comment by zhuangchong** [comment]
@ruanwenjun @CalvinKirs 

Very good idea, I have a little idea, create a data source, the page provides a customizable data source, users do not need to change the code, similar to the idea data source plug-in.

**Comment by ruanwenjun** [comment]
@zhuangchong Cool, in fact when a user creates a new datasource, he only needs to provide the `Driver` and tell us how to get the `connection`. But we now have some task coupling with datasource it is difficult to achieve this goal. I think we can try to make some plugin specification on the future.

**Comment by Narcasserun** [comment]
> @zhuangchong Cool，其实当用户创建一个新的数据源时，他只需要提供`Driver`并告诉我们如何获取`connection`. 但是我们现在有一些与数据源耦合的任务很难实现这个目标。我认为我们可以尝试在未来制定一些插件规范。

It seems that I have implemented what you said. Users only need to provide driver and connection. And it already supports hive, mysql, CK, PG, sqlserver, etc. How can I continue to communicate with you

**Comment by Narcasserun** [comment]
> @zhuangchong Cool，其实当用户创建一个新的数据源时，他只需要提供`Driver`并告诉我们如何获取`connection`. 但是我们现在有一些与数据源耦合的任务很难实现这个目标。我认为我们可以尝试在未来制定一些插件规范。

It seems that I have implemented what you said. Users only need to provide driver and connection. And it already supports hive, mysql, CK, PG, sqlserver, etc. How can I continue to communicate with you

**Comment by zhuangchong** [comment]
@Narcasserun 

You can open a new issue to express your ideas, design plan.
Finally associated with this issue.

**Comment by Narcasserun** [comment]
#5954 

> @Narcasserun
> 
> You can open a new issue to express your ideas, design plan.
> Finally associated with this issue.

#5954 This issue includes the idea of data source creation and metadata. I will give detailed design documents and ideas later

**Comment by Narcasserun** [comment]
> @Narcasserun
> 
> You can open a new issue to express your ideas, design plan.
> Finally associated with this issue.

#5954 This issue includes the idea of data source creation and metadata. I will give detailed design documents and ideas later
