### ISSUE TITLE
[Bug][Server-Depedent] If a workflow depends on the previous workflow, but for some reasons, the previous workflow has not arrived and started to run, then the current workflow will directly consider the dependency failed when judging.

### ISSUE THREAD

**Issue by 597365581** [apache/dolphinscheduler#5084]
If a workflow depends on the previous workflow, but for some reasons, the previous workflow has not arrived and started to run, then the current workflow will directly consider the dependency failed when judging.
如果一个工作流依赖于上一个工作流，但是因为一些原因，上一个工作流还没来的及开始运行，那么在判断的时候，当前工作流直接就认为依赖失败了。version  .is  1.3.2

**Comment by CalvinKirs** [comment]
please provide you version

**Comment by 597365581** [comment]
version:1.3.2

**Comment by 597365581** [comment]
I will fix it

**Comment by caishunfeng** [comment]
This issue will be closed because no update for a long time, you can reopen it if need.
