### ISSUE TITLE
[Feature][data sources] Add Sap data source

### ISSUE THREAD

**Issue by Join1339822899** [apache/dolphinscheduler#5086]
I want to use sqoop to extract data in Hana, but I cannot create this type of data source. Is there any way to create it, or will I provide a custom data source function in subsequent functions?

**Comment by davidzollo** [comment]
Please update/add title and description in English, thx

**Comment by CalvinKirs** [comment]
Maybe we should consider the SPI for datasource as soon as possible

**Comment by dogloster** [comment]
> I want to use sqoop to extract data in Hana, but I cannot create this type of data source. Is there any way to create it, or will I provide a custom data source function in subsequent functions?

I want ,too

**Comment by Sdreamery** [comment]
> I want to use sqoop to extract data in Hana, but I cannot create this type of data source. Is there any way to create it, or will I provide a custom data source function in subsequent functions?

I really want to！！！
