### ISSUE TITLE
[Question] how to config exchange email

### ISSUE THREAD

**Issue by clp007** [apache/dolphinscheduler#5096]
i can't config alert email with exchange email ,how to config it?

**Comment by CalvinKirs** [comment]
you need change alert.properties

**Comment by clp007** [comment]
can you show me alter.properties paramters,like:protocol ,port, enable of TSL,SSL ,etc.  i can't config it successful anyway

**Comment by ZJ577624359** [comment]
# mail server configuration
mail.protocol=SMTP
mail.server.host=smtp.exmail.qq.com
mail.server.port=465
mail.sender=邮箱地址
mail.user=邮箱地址
mail.passwd=邮箱密码
# TLS
mail.smtp.starttls.enable=false
# SSL
mail.smtp.ssl.enable=true
mail.smtp.ssl.trust=smtp.exmail.qq.com
这是QQ企业邮箱的配置

**Comment by chengshiwen** [comment]
Close this isuue since no updates for long time
