### ISSUE TITLE
[Question] resource manage don't support local filesystem?

### ISSUE THREAD

**Issue by haydenzhourepo** [apache/dolphinscheduler#5099]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
A clear and concise description of what the question is.
resource managment doesn't support the local filesystem?
![image](https://user-images.githubusercontent.com/21101605/111601133-0aad1600-880d-11eb-9645-5c3df358a6cb.png)

**Which version of DolphinScheduler:**
 -[1.3.6]

**Additional context**

**Requirement or improvement**
- local filesystem is convenient for local development or test

**Comment by chengshiwen** [comment]
@haydenzhourepo You can set `resource.storage.type=HDFS` and `fs.defaultFS=file:///`, because `HDFS` is a superset of the local file system

**Comment by haydenzhourepo** [comment]
ok, thanks for your response.
