### ISSUE TITLE
[Bug][Resource] The file name of File and UDF resource not changed and cannot re-upload after renaming name

### ISSUE THREAD

**Issue by chengshiwen** [apache/dolphinscheduler#5103]
**To Reproduce**
Steps to reproduce the behavior, for example:
1. Go to 'File Manage'
2. Upload a file
3. Rename the file
4. See error (picture 1)
5. The same error also occurs in 'UDF Resources' (picture 2)
6. In 1.3.x version, if the renamed file is re-uploaded, 'resource already exists' error occurs (picture 3)

**Expected behavior**
Bug fixed.

**Screenshots**

In **File Manage**: (picture 1)
![image](https://user-images.githubusercontent.com/4902714/111659876-85dfed80-8848-11eb-8fa1-83dc95e816c8.png)

In *UDF Resources*: (picture 2)
![image](https://user-images.githubusercontent.com/4902714/111659982-9e500800-8848-11eb-8718-3b9fc4b4660d.png)

In **File Manage** to **Re-upload**: (picture 3)
![image](https://user-images.githubusercontent.com/4902714/111734181-8f06a400-88b4-11eb-8340-ed4ead79c97c.png)

**Which version of Dolphin Scheduler:**
 -[1.3.x]
 -[dev]

**Comment by vimacro** [comment]
I'll fix.
