### ISSUE TITLE
[Improvement][*] Rename RUNNING_EXEUTION to RUNNING_EXECUTION

### ISSUE THREAD

**Issue by chengshiwen** [apache/dolphinscheduler#5108]
**Describe the question**

*Rename `RUNNING_EXEUTION` to `RUNNING_EXECUTION`*

**What are the current deficiencies and the benefits of improvement**

- Fix `RUNNING_EXEUTION` spell error
- More friendly and readable code

**Which version of DolphinScheduler:**
 -[1.3.5]

**Comment by CalvinKirs** [comment]
close by #5109
