### ISSUE TITLE
[Bug][Server] The registered address of a server is the loopback address 127.0.0.1

### ISSUE THREAD

**Issue by chengshiwen** [apache/dolphinscheduler#5115]
**Bug description**

The registered address of a server is the loopback address 127.0.0.1

**Expected behavior**
Bug fixed.

**Screenshots**
![image](https://user-images.githubusercontent.com/4902714/111858391-8c1eb880-8973-11eb-9e67-953fb6a4bd76.png)
![image](https://user-images.githubusercontent.com/4902714/111858401-9b9e0180-8973-11eb-9d6e-479509f9a8d8.png)
![image](https://user-images.githubusercontent.com/4902714/111858406-9fca1f00-8973-11eb-8a9b-31ca699a08bc.png)

**Which version of Dolphin Scheduler:**
 -[1.3.x]

**Additional context**

**Comment by CalvinKirs** [comment]
close by #5117. release 1.3.6
