### ISSUE TITLE
[Question] In Dev branch，When run  ApiApplicationServer#main，the Application will be blocking。Can you help me to solve it?

### ISSUE THREAD

**Issue by cha1Yi** [apache/dolphinscheduler#5120]
I was run in my PC，The IDEA console print：
```text
Connected to the target VM, address: '127.0.0.1:59176', transport: 'socket'

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v2.1.17.RELEASE)

 _ _   |_  _ _|_. ___ _ |    _ 
| | |\/|_)(_| | |_\  |_)||_|_\ 
     /               |         
                        3.2.0 


```

Just print this logo.
Help me， thank you！

**Comment by cha1Yi** [comment]
Sorry, it is not blocking,That's the problem with `logback-api.xml`,Someone commented `<appender-ref ref="STDOUT"/>` in 58 lines。can you change it？

**Comment by ruanwenjun** [comment]
> Sorry, it is not blocking,That's the problem with `logback-api.xml`,Someone commented `<appender-ref ref="STDOUT"/>` in 58 lines。can you change it？

You can find the log content in logs/dolphinscheduler-api.log, this is the default behavior. 
If you want to print the log on the console, you can replace the `appender-ref` in the `logback-api.xml` like below
```
<root level="INFO">
        <appender-ref ref="STDOUT"/>
</root>
```

**Comment by cha1Yi** [comment]
Thank you for your reply，I have started and enjoy it.
