### ISSUE TITLE
[Question] When encountering tasks with long execution time, the tasks have unlimited delay。遇到执行时间长的task，任务无限delay

### ISSUE THREAD

**Issue by liqiquan** [apache/dolphinscheduler#5121]
Dolphin Scheduler, some Task execution time is too long, which will cause Task assigned to the same work, and you can do it after you need it. And in one work, there have been hundreds of hundreds of waiting to be executed in line (other Work because they only want to be fast, Maser will still allocate Task to this Work. What is the optimization method? Or have it possible to change the allocation policy?

dolphin scheduler 中,有的task执行时间过长，这样会导致后面分配到同一work的task，需要等前面的执行完后才能执行。而且一个work中，已经有上百个在排队等待执行（其他work由于只想快，基本没有排队等待），maser仍然还会分配task到这个work上。这种情况有什么优化方法？或则有可以更改的分配策略？

**Comment by ruanwenjun** [comment]
> Dolphin Scheduler, some Task execution time is too long, which will cause Task assigned to the same work, and you can do it after you need it. And in one work, there have been hundreds of hundreds of waiting to be executed in line (other Work because they only want to be fast, Maser will still allocate Task to this Work. What is the optimization method? Or have it possible to change the allocation policy?
> 
> dolphin scheduler 中,有的task执行时间过长，这样会导致后面分配到同一work的task，需要等前面的执行完后才能执行。而且一个work中，已经有上百个在排队等待执行（其他work由于只想快，基本没有排队等待），maser仍然还会分配task到这个work上。这种情况有什么优化方法？或则有可以更改的分配策略？

The default dispatch strategy considers the worker's cpu, memory, loadAverage, it can work well with task priority on most time. And it is suggested to use special work groups for the task which needing long time. 
Additional we can consider to adding work's waiting task to the dispatch strategy, this feature needs ds supports.
