### ISSUE TITLE
[Bug][installing ds] I have configured the ssh without passwd and ssh localhost and ssh hostname is ok but when i exec"sh install.sh" appear "Connection refused"

### ISSUE THREAD

**Issue by hhj970815** [apache/dolphinscheduler#5127]
**Describe the bug**
 I have configured the ssh without passwd and ssh localhost and ssh hostname is ok but when i exec"sh install.sh" appear "Connection refused".

**Screenshots**
i exec "ssh localhost" and ssh ip and ssh hostname is ok
![image](https://user-images.githubusercontent.com/41581357/111972295-465f1d00-8b38-11eb-8982-cdd3f5fee60f.png)

the question:
![image](https://user-images.githubusercontent.com/41581357/111972049-f2543880-8b37-11eb-8a89-b83b7f831889.png)

**Which version of Dolphin Scheduler:**
 -[1.3.5-preview]

**Comment by vimacro** [comment]
do not use sudo command 
![image](https://user-images.githubusercontent.com/11975398/111973437-72c76900-8b39-11eb-9812-316dff75aefa.png)

**Comment by hhj970815** [comment]
> do not use sudo command
> ![image](https://user-images.githubusercontent.com/11975398/111973437-72c76900-8b39-11eb-9812-316dff75aefa.png)

i tried, but it still doesnt work

**Comment by hhj970815** [comment]
> > do not use sudo command
> > ![image](https://user-images.githubusercontent.com/11975398/111973437-72c76900-8b39-11eb-9812-316dff75aefa.png)
> 
> i tried, but it still doesnt work

![image](https://user-images.githubusercontent.com/41581357/111974002-08fb8f00-8b3a-11eb-933c-3159e8146568.png)

**Comment by vimacro** [comment]
Does the user  have sudo privileges? （sudo with no password）

**Comment by hhj970815** [comment]
> Does the user have sudo privileges?
Do u mean this:
![image](https://user-images.githubusercontent.com/41581357/111976659-d30bda00-8b3c-11eb-98b3-e74dd7cc5536.png)

**Comment by vimacro** [comment]
remote user  ,  host1 with user ds1, host2 with ds2 ,ds1 and ds2 need sudo with no password

**Comment by hhj970815** [comment]
> remote user , host1 with user ds1, host2 with ds2 ,ds1 and ds2 need sudo with no password

the model is standalone, seems like i dont need to configure the remote, brain broken..

**Comment by hhj970815** [comment]
> remote user , host1 with user ds1, host2 with ds2 ,ds1 and ds2 need sudo with no password

thanks bro! the reason is that the server ssh 's default port had changed, i changed the ds's configuration and it works.
