### ISSUE TITLE
[Feature][Worker] Support turning off sudo permissions

### ISSUE THREAD

**Issue by vimacro** [apache/dolphinscheduler#5128]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/community/development/issue.html when describe an issue.*

**Describe the feature**

The current version of multi-tenant implementation requires sudo permission. Most of the time the deployment execution user does not have sudo permission and does not need to be executed by the tenant account. At this time, the sudo permission dependency can be turned off, and the task execution is executed by the deployment user.

当前版本多租户的实现，需要sudo权限，大多数时候部署执行用户没有sudo权限，并且不需要利用租户账户执行，这时候可以关掉sudo权限依赖，任务执行采用部署用户执行

sudo stands for privilege escalation. If privilege escalation is not configured, multi-tenant is only used to isolate resources and users. After privilege escalation is configured, task execution will be performed by tenants, and deployment users will not be configured; and if privilege escalation is not configured, tenants cannot be automatically created.

sudo 代表提权，如果不配置提权，多租户仅用来隔离资源与用户，配置提权以后，任务执行使用租户执行，不配置使用部署用户执行；并且不配置提权不允许自动创建租户

**Comment by chengshiwen** [comment]
The related issues: #4515 #4706
