### ISSUE TITLE
failureStrategy: CONTINUE is not effective

### ISSUE THREAD

**Issue by getixin** [apache/dolphinscheduler#5131]
![image](https://user-images.githubusercontent.com/20057322/112117187-0a8a8d00-8bf6-11eb-880b-4a8184acd515.png)

the task 2 is not execute
dolphinscheduler v1.3.5

**Comment by xxjingcd** [comment]
You got it wrong. FailureStrategy refers to whether the process instance continues to run in event of a task failure.The default is to continue. If the current task fails, the post-task cannot be executed.

---

你搞错了，FailureStrategy 是指在出现失败任务时，工作流实例是否继续运行。默认是继续的。如果当前任务失败，其后置任务是无法运行的。
