### ISSUE TITLE
[Bug][server] when an exception occurs in the taskExecuteThread, task cannot stop immediately

### ISSUE THREAD

**Issue by xxjingcd** [apache/dolphinscheduler#5132]
**Describe the bug**

When an exception occurs in the taskExecuteThread, task will  be called the  `cancelApplication()` method to stop the task immediately。Howerver，the task whose` cancelApplication()` method  base on the `AbstractCommandExecutor.cancelApplication()` cannot be killed immediately,because `AbstractCommandExecutor.cancelApplication()` would not call `hardKill()` method when soft kill process fail;

**To Reproduce**

**Expected behavior**
In order to make the error task stop immediately ，It should call the `hardKill()` method when soft kill process fails；

**Screenshots**
![image](https://user-images.githubusercontent.com/68894048/112130011-f600c180-8c02-11eb-934c-e490f63c0d73.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Additional context**
It is a very simple Bug, the `softKill()` method returns the opposite state, so just modify the return value can fix this bug. I will fix this Bug.
 
**Requirement or improvement**

**Comment by xxjingcd** [comment]
the PR： https://github.com/apache/incubator-dolphinscheduler/pull/5133

**Comment by CalvinKirs** [comment]
close by #5133
