### ISSUE TITLE
[Bug][Master] Typo in  MasterConfig

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#5141]
**Describe the bug**
Can't use `MasterConfig` to parse `masterDispatchTaskNumber` from `master.properties`, cause of typo.

**To Reproduce**
Steps to reproduce the behavior, for example:

Edit `master.dispatch.task.num` in `master.properties` and Start master by debug mode and see `masterConfig`.

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[1.3.6]
 -[dev]

**Comment by CalvinKirs** [comment]
close by #5142
