### ISSUE TITLE
[Improvement][Master] this expression which always evaluates "true"

### ISSUE THREAD

**Issue by lyyprean** [apache/dolphinscheduler#5147]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/community/development/issue.html when describe an issue.*

**Describe the question**
this expression which always evaluates "true"

**What are the current deficiencies and the benefits of improvement**
this expression which always evaluates "true" ，removeTaskLogFile  method of org.apache.dolphinscheduler.service.process

**Which version of DolphinScheduler:**
 -[1.3.5]

**Describe alternatives you've considered**
public void removeTaskLogFile(Integer processInstanceId) {

        LogClientService logClient = null;

        try {
            logClient = new LogClientService();
            List<TaskInstance> taskInstanceList = findValidTaskListByProcessId(processInstanceId);

            if (CollectionUtils.isEmpty(taskInstanceList)) {
                return;
            }

            for (TaskInstance taskInstance : taskInstanceList) {
                String taskLogPath = taskInstance.getLogPath();
                if (StringUtils.isEmpty(taskInstance.getHost())) {
                    continue;
                }
                int port = Constants.RPC_PORT;
                String ip = "";
                try {
                    ip = Host.of(taskInstance.getHost()).getIp();
                } catch (Exception e) {
                    // compatible old version
                    ip = taskInstance.getHost();
                }

                // remove task log from loggerserver
                logClient.removeTaskLog(ip, port, taskLogPath);
            }
        } finally {
 
                logClient.close();
            
        }
    }

**Comment by zhuangchong** [comment]
I'm sorry that I didn't understand what you wanted to express. Could you please explain it in detail?

**Comment by lyyprean** [comment]
> I'm sorry that I didn't understand what you wanted to express. Could you please explain it in detail?

         if (logClient != null) {
                logClient.close();
            }
This judgment always comes back true, it is unnecessary

**Comment by zhuangchong** [comment]
@lyyprean 
I suggest to change it like this

```
LogClientService logClient = null;

  
       
        List<TaskInstance> taskInstanceList = findValidTaskListByProcessId(processInstanceId);

        if (CollectionUtils.isEmpty(taskInstanceList)) {
            return;
        }

  try {
     logClient = new LogClientService();
        for (TaskInstance taskInstance : taskInstanceList) {
            String taskLogPath = taskInstance.getLogPath();
            if (StringUtils.isEmpty(taskInstance.getHost())) {
                continue;
            }
            int port = Constants.RPC_PORT;
            String ip = "";
            try {
                ip = Host.of(taskInstance.getHost()).getIp();
            } catch (Exception e) {
                // compatible old version
                ip = taskInstance.getHost();
            }

            // remove task log from loggerserver
            logClient.removeTaskLog(ip, port, taskLogPath);
        }
    } finally {

           if (logClient != null) {
            logClient.close();
        }
        
    }
}
```

**Comment by zhuangchong** [comment]
@lyyprean Welcome to submit a PR for code optimization.

**Comment by lyyprean** [comment]
> @lyyprean Welcome to submit a PR for code optimization.

I have submitted it, thank you

> @lyyprean Welcome to submit a PR for code optimization.
