### ISSUE TITLE
Log permission error

### ISSUE THREAD

**Issue by ZJ577624359** [apache/dolphinscheduler#5148]
执行任务出现
[INFO] 2021-03-25 16:27:00.619  - [taskAppId=TASK-4-531-2571]:[127] -  -> log4j:ERROR setFile(null,true) call failed.
	java.io.FileNotFoundException: logs/pdi.log (权限不够)
在linux服务器上，安装路径的权限已完全打开，用户的分组也是root
不知为何还是报权限不够

**Comment by xingchun-chen** [comment]
Which user is used to deploy DS？
The user permissions of the log path should be the same as the DS deployment user

**Comment by ZJ577624359** [comment]
@xingchun-chen 使用dolphinscheduler用户部署
![image](https://user-images.githubusercontent.com/79566794/112565899-f5417880-8e18-11eb-81c5-9279291e6889.png)
![image](https://user-images.githubusercontent.com/79566794/112565939-07231b80-8e19-11eb-9e26-305114f3e7c1.png)
部署路径权限是全部打开的。

**Comment by xingchun-chen** [comment]
You need to check whether the permissions of logs directory are dolphinscheduler

**Comment by ZJ577624359** [comment]
@xingchun-chen 
![image](https://user-images.githubusercontent.com/79566794/112567260-7f8adc00-8e1b-11eb-97c7-5985aa3c5fe6.png)
![image](https://user-images.githubusercontent.com/79566794/112567282-87e31700-8e1b-11eb-8d16-5c194a877d53.png)
确认是dolphinscheduler用户

**Comment by ZJ577624359** [comment]
问题已解决，实际错误是由调用其它的软件反馈至日志，非海豚的错误。
