### ISSUE TITLE
"Timeout" logic error in the complement process(“超时时间”在补数流程中逻辑错误)

### ISSUE THREAD

**Issue by xianhu** [apache/dolphinscheduler#515]
For example, setting the timeout time 60S, the single-day task needs about 30S, the complement needs to fill 10 days of data, serial execution, then the total duration of the complement task is about 300S, exceeding the "timeout time", an alarm mail will be sent at this time. But in fact, the "timeout" here should be a single-day task, not the entire complement task.

---
比如设置超时时间60S，单天任务大概需要30S，补数需要补10天数据，串行执行，那么补数任务的总时长大概在300S左右，超过“超时时间”，此时会发出报警邮件。但其实这里的“超时时间"应该是针对的单天的任务，而不是整个补数任务。

**Comment by boandai** [comment]
very good,thx!

we will discuss this issue later!
