### ISSUE TITLE
[Improvement][api] the restful api: "copyProcessDefinition->/dolphinscheduler/projects/{projectName}/process/copy" reponse data not contains the id of copyed process

### ISSUE THREAD

**Issue by babogd** [apache/dolphinscheduler#5154]
the restful api:
 "copyProcessDefinition->/dolphinscheduler/projects/{projectName}/process/copy" reponse data not contains the id of copyed rocess

When using this interface in a self-built system, there is no way to know which processDefinition copyed

I changed the code in my computer, but I receive  "remote: Permission to "  when push to github

**Comment by chengshiwen** [comment]
@babogd Thanks for your contribution! If you want to contribute the code, please refer to https://dolphinscheduler.apache.org/en-us/community/development/submit-code.html at first. Looking forward to joining the DolphinScheduler open source community
