### ISSUE TITLE
[Bug][website] update the archtiecture picture

### ISSUE THREAD

**Issue by davidzollo** [apache/dolphinscheduler#5157]
**Describe the bug**
the architecture picture in the officail website is wrong, please correct it

website github address: https://github.com/apache/incubator-dolphinscheduler-website

in addition, please also update the English version

the right picture are as follows:
[architecture picture.pptx](https://github.com/apache/incubator-dolphinscheduler/files/6211152/architecture.picture.pptx)

**Which version of Dolphin Scheduler:**
 -[official website]

**Comment by heyzeng** [comment]
can i fix it？

**Comment by davidzollo** [comment]
> can i fix it？

has assigned to you, looking forward to your PR
