### ISSUE TITLE
[Bug][Module Name] Effective environment variable

### ISSUE THREAD

**Issue by pengge00** [apache/dolphinscheduler#5166]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
when  i write the shell, test function of ds. when  i  add  Two effective environment variable statements
1、source /etc/profile
2、source ~/.bash_profile
after the service and my colony are breakdown 
but need to wait 30min, we can restart the colony and the ds service

**To Reproduce**
Steps to reproduce the behavior, for example:
1. create a project 
2. create a shell task 
3. input   
    3.1 source /etc/profile  or   3.2 source ~/.bash_profile
4. save the dag

**Expected behavior**
ds and colony service breakdown and can not open, wait 1h or more long, you can restart all service

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[1.3.5-preview]

**Additional context**
 when i add tenant, my tenant code is not map the user of  installment
but i think is not a key factor in this problem 

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by ruanwenjun** [comment]
@pengge00
I can't reproduce this problem by following the steps below.
1. Create a new project
2. Create a shell task
3. input source ~/.bash_profile
4. Save the dag
5. Run the workflow

This work find on my computer, there maybe another reason, you need to provide more information. :grinning:

**Comment by caishunfeng** [comment]
This issue will be closed because no update for a long time.
