### ISSUE TITLE
[Improvement][API] Improvement  query all project list (easy to implement)

### ISSUE THREAD

**Issue by zhuangchong** [apache/dolphinscheduler#5169]
**Describe the question**

The premise of query all project list is have one or more process definitions, I think it should be changed to query all project list.

**What are the current deficiencies and the benefits of improvement**
an interface to query all project list

**Which version of DolphinScheduler:**
 -[1.3.4-release]

* easy to implement

**Comment by ruanwenjun** [comment]
I can do it

**Comment by CalvinKirs** [comment]
close by #5192
