### ISSUE TITLE
[Improvement][API] the QueryAuthorizedProject interface adds permission judgment (easy to implement)

### ISSUE THREAD

**Issue by zhuangchong** [apache/dolphinscheduler#5170]
**Describe the question**

The QueryAuthorizedProject interface has query authority only for administrators,the project scenario where a user queries the user's own authorization cannot be satisfied.

**What are the current deficiencies and the benefits of improvement**
 
The QueryAuthorizedProject interface adds permission judgment ,the user itself can query the user's own authorized project

**Which version of DolphinScheduler:**
 -[1.3.4-release]

**Comment by ruanwenjun** [comment]
Maybe I can solve this issue.
But the way, this interface just used for OpenAPI ?

**Comment by zhuangchong** [comment]
> Maybe I can solve this issue.
> But the way, this interface just used for OpenAPI ?

yes

**Comment by ruanwenjun** [comment]
> > Maybe I can solve this issue.
> > But the way, this interface just used for OpenAPI ?
> 
> yes

Ok, please assign to me
