### ISSUE TITLE
[Improvement][Module Name] Integrated spring boot actuator

### ISSUE THREAD

**Issue by riverlee2014** [apache/dolphinscheduler#5181]
Can it's java application provide Prometheus endpoint by integrated spring boot actuator?
It's all spring boot projects should be easy to integrate actuator to  expose as prometheus format?

**Comment by davidzollo** [comment]
could you show a demo, not familiar with actuator

**Comment by CalvinKirs** [comment]
Spring boot actuator can only provide some simple indicators, which are usually of little significance. We support SkyWalking for link monitoring in the upcoming version 1.3.6. I don't know if it can meet your needs. Of course, if you want to contribute to the integration of Prometheus and DS, it is very welcome.

**Comment by riverlee2014** [comment]
Thanks, Our requirements is to simply monitor the health and JVM indicators of the master cluster services.
Instead, We can use the blackbox_exporter or jmx_exporter to solve the problem. Supporting skywalking is also a good way.
