### ISSUE TITLE
[Bug][WorkerGroup] The worker group before starting doesn't seem to override the worker group in the task node

### ISSUE THREAD

**Issue by chengshiwen** [apache/dolphinscheduler#5183]
**To Reproduce**
Steps to reproduce the behavior, for example:
1. Create a task with a worker group named `worker0`
2. Run the process definition with another worker group named `worker2`
3. Go to task instance list
4. See the task instance is executed on the worker group named `worker0`

![image](https://user-images.githubusercontent.com/4902714/112980902-0f6ab600-918d-11eb-98f0-88f45620c194.png)

**Expected behavior**
Bug fixed.

**Which version of Dolphin Scheduler:**
 -[1.3.5]
 -[dev]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by ruanwenjun** [comment]
Yeah, this does happen.
But I think this is reasonable, the task's workgroup can override the workflow's workgroup setting.
If a user has 10 tasks in his workflow, and he wants most of the task run at workgroup1 and only taskB run at workgroup2, then he only needs to set taskB works on workgroup2 and the workflow works on workgroup1.

The detail code you can see at MasterExecThread.java line 514.

Unfortunately, I find another front bug.
![image](https://user-images.githubusercontent.com/22415594/113289199-7f5e7500-9322-11eb-9c18-ac02473425be.png)

**Comment by chengshiwen** [comment]
Close since it has been replied
