### ISSUE TITLE
[Feature][WORKER] Spark task support the Spark3 version

### ISSUE THREAD

**Issue by lyyprean** [apache/dolphinscheduler#5189]
**Describe the feature**
I want to develop a feature that Spark tasks support for the Spark3 version

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I am using Hudi, which requires Spark3.0

**Comment by chengshiwen** [comment]
@lyyprean In fact, the way to submit applications with `spark-submit` is the same, regardless of Spark 1, Spark 2 or Spark 3.
In other words, you can set `SPARK_HOME2=/path/to/spark-3.1.1-bin-hadoop2.7` in `env/dolphinscheduler_env.sh`

Note: `SPARK_HOME2` instead of `SPARK2_HOME`

**Comment by chengshiwen** [comment]
Close this issue since no updates for long time
