### ISSUE TITLE
[Question] Stop the workflow, But can‘t Stop yarn application

### ISSUE THREAD

**Issue by zjw-zjw** [apache/dolphinscheduler#5194]
I run a shell command waht is run sqoop to load data into hive. And it is running with mapreduce, when I stop the workflow，I think this MR application will be kill， but was not. The Mr applicaiton is still RUNNING. And I dont know why. 

**Which version of DolphinScheduler:**
 -[1.3.5]

**This is the log**
![image](https://user-images.githubusercontent.com/48348786/113254137-c9cafc00-92f8-11eb-851b-5f44d776fe4b.png)

**Comment by xingchun-chen** [comment]
It is the same as #4862

**Comment by CalvinKirs** [comment]
fix by #4936
