### ISSUE TITLE
[Question] SyntaxError: Non-ASCII character '\xe4' in file xxxx

### ISSUE THREAD

**Issue by ChenCarlos** [apache/dolphinscheduler#5197]
在资源中心->文件管理中，上传一个python文件（例如，文件名叫include.py），且文件里包含中文。
那么用Python组件运行Python代码，代码里import include

运行流程会报以下错误：
SyntaxError: Non-ASCII character '\xe4' in file xxxx

如果把include.py里的中文改为英文，就不会报错。

请问如何让include.py支持中文？

**Comment by chengshiwen** [comment]
@ChenCarlos You should add the following lines at the beginning of the file `include.py`:
```
#!/usr/bin/env python
# -*- coding=utf-8 -*-
```

By the way, please update the title in English, thx

**Comment by CalvinKirs** [comment]
Python's default encoding file is ASCII code, you should try it according to the @chengshiwen  method. btw, please use English. Thx
