### ISSUE TITLE
[Bug][api] When sleep is included in a shell task, cannot kill the task

### ISSUE THREAD

**Issue by xingchun-chen** [apache/dolphinscheduler#5199]
![image](https://user-images.githubusercontent.com/55787491/113400980-429f8600-93d5-11eb-8002-7684d36d6ed1.png)
![image](https://user-images.githubusercontent.com/55787491/113401140-81cdd700-93d5-11eb-89dd-a259284e5dae.png)

**Which version of Dolphin Scheduler:**
 -[1.3.6-prepare]

**Comment by ruanwenjun** [comment]
I can kill the task, after install the `pstree` on my environment.
And the task can be killed successfully.
![image](https://user-images.githubusercontent.com/22415594/113478959-9fc33680-94be-11eb-82cc-11294d960ebf.png)


But there is still an error, that I don't have permission to kill the parent process, but I can kill the subprocess, so the task is still be killed.
```
-+- 20788 root sudo -u ruanwenjun sh /tmp/dolphinscheduler/exec/process/1/4/73/76/4_73_76.command
 \-+- 20789 ruanwenjun sh /tmp/dolphinscheduler/exec/process/1/4/73/76/4_73_76.command
   \-+- 20795 ruanwenjun sh /tmp/dolphinscheduler/exec/process/1/4/73/76/4_73_76.command
     \--- 20796 ruanwenjun sleep 20
```
```java
org.apache.dolphinscheduler.server.worker.processor.TaskKillProcessor:[131] - process id:20788, cmd:sudo -u ruanwenjun kill -9 20788 20789 20795 20796
org.apache.dolphinscheduler.common.shell.AbstractShell$ExitCodeException: kill: 20788: Operation not permitted
```
