### ISSUE TITLE
[Question] Does DS support task resource islation, like using docker to execute task

### ISSUE THREAD

**Issue by lisirrx** [apache/dolphinscheduler#5207]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**

**Which version of DolphinScheduler:**
 -[1.3.5]

**Additional context**

**Requirement or improvement**

**Comment by CalvinKirs** [comment]
Please describe your problem in English, Thx

**Comment by chengshiwen** [comment]
@lisirrx Tasks do not support resource isolation. Similar to it, worker groups can be used to isolate tasks. Currently DS does not support starting tasks through docker, but you can deploy DS through docker or k8s

**Comment by lisirrx** [comment]
> Please describe your problem in English, Thx

sry, I will edit the issue title

**Comment by lisirrx** [comment]
> @lisirrx Tasks do not support resource isolation. Similar to it, worker groups can be used to isolate tasks. Currently DS does not support starting tasks through docker, but you can deploy DS through docker or k8s

thanks for your reply!
is there any planning to support task level resource isolation, or integrate with k8s/yarn?

**Comment by chengshiwen** [comment]
> thanks for your reply!
> is there any planning to support task level resource isolation, or integrate with k8s/yarn?

In future, we will consider cloud native based on docker/k8s, so you will see the task level resource isolation through docker or k8s

**Comment by chengshiwen** [comment]
Close since it has been replied.

**Comment by tocjava** [comment]
Airflow version 1.10 introduces Kubernetes Executor and Kubernetes Operator, allowing new Pods to be created for each task to process, and the newly created Pod will be cleaned up after execution, and each task can be specified with a different Docker image for processing
Airflow 1.10 版本引入了 Kubernetes Executor 和 Kubernetes Operator 允许为每一个任务创建新的 Pod 来处理，而执行完之后新创建的 Pod 会被清理掉，并且每一个任务都可以指定不同的 Docker image 来处理

Should DolphinScheduler also support this way to perform tasks?
DolphinScheduler 是否应该也支持这种方式来执行任务?

@chengshiwen  Thankyou
