### ISSUE TITLE
[Improvement][Server] Must restart master if Zk reconnect

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#5210]
**Describe the question**
If zookeeper is disconnect, the master server stop work, and when the zookeeper reconnect, we need to restart the master server, the master server can't automatic recovery. 
Because when the zookeeper reconnect, treeCache will produce NODE_REMOVED event, `ZKMasterClient` receive this event and add the server to deadNode. When the `HeartBeatTask` check the master is on dead path, it will stop the MasterServer.

**What are the current deficiencies and the benefits of improvement**
Improving the server availability.

**Which version of DolphinScheduler:**
 -[1.3.6-preview]

**Comment by CalvinKirs** [comment]
+1,sonuds good to me.
