### ISSUE TITLE
[Question] Prevent duplicate instance running

### ISSUE THREAD

**Issue by roamerop** [apache/dolphinscheduler#5215]
**Describe the question**
I define a process and attach `schedule management` which run every ten minutes.  But sometimes the prcess takes more than ten minutes to finish and I don't want the process to start "stacking up" over each other. 

**Which version of DolphinScheduler:**
 -[1.3.2]

**Comment by chengshiwen** [comment]
@roamerop Hi, could you show us more steps to reproduce this issue? Thanks so much

**Comment by roamerop** [comment]
> @chengshiwen  
1 Define a python script, such as `time.sleep(30)`.
2 Define schedule run every 1 second.
3 you will see duplicate instance running on `processInstance` tab.
---
Chinese
1 定义一个python工作流，在里面休眠十秒（为了演示阻塞）
2 为工作流增加定时任务，每秒运行一次
3 在工作流实例看板上，会看到很多重复的工作流，因为上一个工作流没结束，下一个又开始了（我希望这个工作流串行执行）

**Comment by roamerop** [comment]
@chengshiwen

**Comment by chengshiwen** [comment]
I will try to reproduce it, thanks for your feedback
