### ISSUE TITLE
[Bug][Master] The task instance priority is incorrectly set.

### ISSUE THREAD

**Issue by sincere2018** [apache/dolphinscheduler#5218]
Describe the question：
  When I set the priority of the task instance, it does not take effect. So I found the source code.Line 221 of MasterBaseTaskExecThread in the server module，The code is as follows:
  /**
     *  taskPriority
     */
    TaskPriority taskPriority = buildTaskPriority(processInstance.getProcessInstancePriority().getCode(),
            processInstance.getId(),
            taskInstance.getProcessInstancePriority().getCode(),
            taskInstance.getId(),
            org.apache.dolphinscheduler.common.Constants.DEFAULT_WORKER_GROUP);
    taskUpdateQueue.put(taskPriority);
    logger.info(String.format("master submit success, task : %s", taskInstance.getName()) );
    return true;
The third parameter in buildTaskPriorityInfo is the task instance priority，However, the process instance priority is still used in the code.

**Comment by sincere2018** [comment]
So I think it should be rewritten this way.
/*
* taskPriority
*/
TaskPriority taskPriority = buildTaskPriority(processInstance.getProcessInstancePriority().getCode(),
processInstance.getId(),
taskInstance.getTaskInstancePriority().getCode(), // modify here
taskInstance.getId(),
org.apache.dolphinscheduler.common.Constants.DEFAULT_WORKER_GROUP);

**Comment by chengshiwen** [comment]
Related issue: #4653

**Comment by lenboo** [comment]
Duplicate issue, close this.
