### ISSUE TITLE
[Question] How to make the new queue and tenant work well？

### ISSUE THREAD

**Issue by OliverBai** [apache/dolphinscheduler#5221]
**Describe the question**
steps:
1.Set a new queue and tenant on hadoop and DS, named 'query'.
2.Change an user's property of queue from 'default' to 'query'
3.Start the task of the user, but it's still running in the 'default' queue. It's excepted running in the new 'query' queue.
Q: How to make the new 'query' queue working ?

**Which version of DolphinScheduler:**
1.3.2

**Additional context**
在hadoop上新建了一个队列query，然后在DS里面建立了相应的队列query和租户query，随后更改了对应用户的租户和队列属性，启动该用户建立的任务，在YARN上发现这个任务依然运行在default队列上，没有在新的query队列上，在数据表t_ds_user中该用户所对应的queue已经是query了，所以如何让该用户所提交的任务都运行在query队列上呢？

**Comment by chengshiwen** [comment]
@OliverBai Could you give us more details about he task?

**Comment by OliverBai** [comment]
> @OliverBai Could you give us more details about he task?
here are some details:
![image](https://user-images.githubusercontent.com/14051824/113808283-485fe780-9798-11eb-998b-acb1e3f1966e.png)
![image](https://user-images.githubusercontent.com/14051824/113808342-662d4c80-9798-11eb-8107-d13ba3fcceea.png)
![image](https://user-images.githubusercontent.com/14051824/113808353-6a596a00-9798-11eb-8840-345d9da5a918.png)
![image](https://user-images.githubusercontent.com/14051824/113808365-6f1e1e00-9798-11eb-8739-70bd3ef7a788.png)
![image](https://user-images.githubusercontent.com/14051824/113808367-70e7e180-9798-11eb-915b-3d545c36b7c3.png)
![image](https://user-images.githubusercontent.com/14051824/113808373-734a3b80-9798-11eb-94a1-9a3f506f124a.png)

The task is supported to run in the 'bi' queue, but it is still running in the 'default' queue.

**Comment by chengshiwen** [comment]
@OliverBai Could you show us the command about the task in worker log like follow?

![image](https://user-images.githubusercontent.com/4902714/113809433-aab9e780-979a-11eb-830d-6c44c7bb1956.png)

**Comment by OliverBai** [comment]
> @OliverBai Could you show us the command about the task in worker log like follow?
> 
sorry，i don't know how to get the log like what you show。。。。
but in another way i make the task working on 'bi' queue with setting sql parameters:  **mapreduce.job.queuename=bi** 

![image](https://user-images.githubusercontent.com/14051824/113819369-ca0d4080-97ab-11eb-9aaa-91edceb6ff38.png)
![image](https://user-images.githubusercontent.com/14051824/113819569-12c4f980-97ac-11eb-9c6d-3075748676b0.png)


but。。。。i can't ask all of users to add this kind of sql parameters, so i still want to find it out why it doesn't work with the user property modified way

**Comment by OliverBai** [comment]
Find a better way to make it right.
just modify the data resource and add the parameters.  
![image](https://user-images.githubusercontent.com/14051824/113824944-f4163100-97b2-11eb-9bac-9d65dbb0f52b.png)
 it works too

**Comment by zhuangchong** [comment]
@OliverBai 

Because you are using Hive SQL, the SQL task currently does not support the use of tenant queues.

**Comment by chengshiwen** [comment]
Close the issue since it has been solved
