### ISSUE TITLE
[Question]how to use alert plugin?

### ISSUE THREAD

**Issue by CriysHot** [apache/dolphinscheduler#5225]
how to use alert plugin?
i want to send message to myself  when the alarm goes off

**Comment by ruanwenjun** [comment]
You need to start up AlertServer

**Comment by CalvinKirs** [comment]
What version are you talking about?

**Comment by CalvinKirs** [comment]
please refer https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/alert_spi.html
