### ISSUE TITLE
[Bug][dolphin_scheduler-dev.tar.gz]some .sh have \r

### ISSUE THREAD

**Issue by fyydnz53** [apache/dolphinscheduler#5231]
![image](https://user-images.githubusercontent.com/51303106/113960857-aef80a80-9857-11eb-9aba-5c68fd403285.png)
in the script/ and bin/ ,some file have \r ;
20210408

**Comment by chengshiwen** [comment]
@fyydnz53 Could you give us more details about the ds dev commit info and your os info?

**Comment by fyydnz53** [comment]
myos is ubuntu16.04;
I fix it by use sed -i 's/\r//g' ./*

**Comment by chengshiwen** [comment]
@fyydnz53 The shell scrips don't contain `\r` in dev branch, so could you check if the shell scripts have been edited on Windows?

**Comment by chengshiwen** [comment]
Close since no updates for long time
