### ISSUE TITLE
dolp调度sqoop执行没问题，但是任务一直显示执行中，不往下走，任务已经执行成功，但是一直显示正在执行，导致后面任务链无法继续

### ISSUE THREAD

**Issue by ycfn97** [apache/dolphinscheduler#5232]
[1617844414113.log](https://github.com/apache/incubator-dolphinscheduler/files/6276417/1617844414113.log)
![image](https://user-images.githubusercontent.com/44201208/113976394-aad9e600-9873-11eb-8715-bd060d7a4672.png)

**Comment by CalvinKirs** [comment]
please use english.thx

**Comment by xingchun-chen** [comment]
English is official and necessary. As it has not been revised for a long time, it will be closed temporarily. If you have any questions, please change the title to English and submit again
