### ISSUE TITLE
[Improvement][ApiServer] Traffic limit

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#5235]
**Describe the question**
After support OpenAPI, it is necessary to control the traffic, otherwise the service may be  breakdown.

**What are the current deficiencies and the benefits of improvement**
- Maybe we can add global request rate limit. And in the future, we can consider to support tenant-level rate control

**Which version of DolphinScheduler:**
 -[1.3.6-preview]

**Comment by CalvinKirs** [comment]
Can you state your specific design plan.

**Comment by ruanwenjun** [comment]
> Can you state your specific design plan.

Setting request limit is mainly to protect the system. 
The simple way is to set the global request limit, this can prevent users from sending numerous requests by mistake. When the system receives the maximum number of request, it fast returns 429 for new requests. 
But this also affect other tenant, so we need to set alone request limit for each tenant. The specific implementation is to create `RateLimit` for each user and store in memory. When the user reaches his maximum request quota in one seconds, the system will reject his new request. This can isolate different tenants. Furthermore we can set the read-write level rate control.
Cooperate with global rate limit and tenant-level rate limit can protect the system.

**Comment by wen-hemin** [comment]
I think, this should be the responsibility of the gateway component.

**Comment by BoYiZhang** [comment]
I don't think it is necessary for the time being.
If the request is very high, you can consider a gateway such as nginx to do the load.

**Comment by CalvinKirs** [comment]
At present, what he is doing can be done by Nginx and the like, but this is just the beginning. As the API design is complete later, I believe there will be more users using the API, and they will have more business features. For flow requirements, the gateway level cannot afford too many complex business current limits. Therefore, often the business side will also have its own current limiting components. Maybe they can complete it after a simple transformation based on this.
