### ISSUE TITLE
Bug: create dataX job json error

### ISSUE THREAD

**Issue by shuimuziyang** [apache/dolphinscheduler#5241]
[https://github.com/apache/incubator-dolphinscheduler/blob/dev/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/datax/DataxTask.java](url)
line:313-314
Reader and Writer in datax job json file is json string. DataX parse job json file failed.

**Comment by wen-hemin** [comment]
Please describe the version、operation and exception log

**Comment by shuimuziyang** [comment]
您好，英文实在拿不出手，请见谅。我用海豚调度器dev分支的源码编译了一个安装包，安装之后执行datax任务时失败。
海豚调度器报错如下：





1. 直接用datax运行自定义的datax job json正常，运行海豚调度器生成的job json文件，报同样的错。
2. 查看海豚调度器生成job json文件，发现生成的reader和writer插件配置是字符串格式，datax无法解析。
3. 查看历史版本和最新版本的海豚调度器生成datax task的源码发现，最新的源码中生成reader和writer直接转成了json字符串。

最新源码： 

incubator-dolphinscheduler/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/datax/DataxTask.java
对应的hash：1cd62b4a5e6d5e8ac3adf8b7e2ffd61a8e87f71b

历史版本： 1.3.5-release



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "apache/incubator-dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月9日(星期五) 下午5:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] Bug: create dataX job json error (#5241)





 
Please describe the operation and exception log.

**Comment by ruanwenjun** [comment]
Yeal, this problem does happen in the dev branch. This may be due to the job.json file created by `dolphinscheduler` can't deserialize by `datax`, but I am not sure if it's because of the version.

The job.json created by ds is look like below:
```json
{"job":{"content":[{"reader":"{\"name\":\"clickhousereader\",\"parameter\":{\"username\":\"default\",\"password\":\"123456\",\"connection\":[{\"querySql\":[\"select user_name from ds_user\"],\"jdbcUrl\":[\"jdbc:clickhouse://localhost:8123/default\"]}]}}","writer":"{\"name\":\"mysqlwriter\",\"parameter\":{\"username\":\"root\",\"password\":\"123456\",\"column\":[\"`user_name`\"],\"connection\":[{\"table\":[\"t_ds_user\"],\"jdbcUrl\":\"jdbc:mysql://localhost:3308/dolphinscheduler?allowLoadLocalInfile=false&autoDeserialize=false&allowLocalInfile=false&allowUrlInLocalInfile=false\"}]}}"}],"setting":{"speed":"{\"channel\":1,\"record\":1000}","errorLimit":"{\"record\":0,\"percentage\":0}"}},"core":{"transport":{"channel":{"speed":{"channel":1,"record":1000}}}}}
```
format
```json
{
    "job":{
        "content":[
            {
                "reader":"{"name":"clickhousereader","parameter":{"username":"default","password":"123456","connection":[{"querySql":["select user_name from ds_user"],"jdbcUrl":["jdbc:clickhouse://localhost:8123/default"]}]}}",
                "writer":"{"name":"mysqlwriter","parameter":{"username":"root","password":"123456","column":["`user_name`"],"connection":[{"table":["t_ds_user"],"jdbcUrl":"jdbc:mysql://localhost:3308/dolphinscheduler?allowLoadLocalInfile=false&autoDeserialize=false&allowLocalInfile=false&allowUrlInLocalInfile=false"}]}}"
            }
        ],
        "setting":{
            "speed":"{"channel":1,"record":1000}",
            "errorLimit":"{"record":0,"percentage":0}"
        }
    },
    "core":{
        "transport":{
            "channel":{
                "speed":{
                    "channel":1,
                    "record":1000
                }
            }
        }
    }
}

```
The value of reader、writer and setting is a string, this may not be parsed by `datax`. So we may get error such as `ConfigParser-plugin load  failed` etc.
The simple way to solve is remove toString() in line 313、314、344、345 like `content.put("reader", reader);` Furthermore, I suggest to use a class DataXJob to store the config of datax job setting instead of using ObjectNode.

**Comment by wen-hemin** [comment]
> Yeal, this problem does happen in the dev branch. This may be due to the job.json file created by `dolphinscheduler` can't deserialize by `datax`, but I am not sure if it's because of the version.
> 
> The job.json created by ds is look like below:
> 
> ```json
> {"job":{"content":[{"reader":"{\"name\":\"clickhousereader\",\"parameter\":{\"username\":\"default\",\"password\":\"123456\",\"connection\":[{\"querySql\":[\"select user_name from ds_user\"],\"jdbcUrl\":[\"jdbc:clickhouse://localhost:8123/default\"]}]}}","writer":"{\"name\":\"mysqlwriter\",\"parameter\":{\"username\":\"root\",\"password\":\"123456\",\"column\":[\"`user_name`\"],\"connection\":[{\"table\":[\"t_ds_user\"],\"jdbcUrl\":\"jdbc:mysql://localhost:3308/dolphinscheduler?allowLoadLocalInfile=false&autoDeserialize=false&allowLocalInfile=false&allowUrlInLocalInfile=false\"}]}}"}],"setting":{"speed":"{\"channel\":1,\"record\":1000}","errorLimit":"{\"record\":0,\"percentage\":0}"}},"core":{"transport":{"channel":{"speed":{"channel":1,"record":1000}}}}}
> ```
> 
> format
> 
> ```json
> {
>     "job":{
>         "content":[
>             {
>                 "reader":"{"name":"clickhousereader","parameter":{"username":"default","password":"123456","connection":[{"querySql":["select user_name from ds_user"],"jdbcUrl":["jdbc:clickhouse://localhost:8123/default"]}]}}",
>                 "writer":"{"name":"mysqlwriter","parameter":{"username":"root","password":"123456","column":["`user_name`"],"connection":[{"table":["t_ds_user"],"jdbcUrl":"jdbc:mysql://localhost:3308/dolphinscheduler?allowLoadLocalInfile=false&autoDeserialize=false&allowLocalInfile=false&allowUrlInLocalInfile=false"}]}}"
>             }
>         ],
>         "setting":{
>             "speed":"{"channel":1,"record":1000}",
>             "errorLimit":"{"record":0,"percentage":0}"
>         }
>     },
>     "core":{
>         "transport":{
>             "channel":{
>                 "speed":{
>                     "channel":1,
>                     "record":1000
>                 }
>             }
>         }
>     }
> }
> ```
> 
> The value of reader、writer and setting is a string, this may not be parsed by `datax`. So we may get error such as `ConfigParser-plugin load failed` etc.
> The simple way to solve is remove toString() in line 313、314、344、345 like `content.put("reader", reader);` Furthermore, I suggest to use a class DataXJob to store the config of datax job setting instead of using ObjectNode.

**Comment by wen-hemin** [comment]
Yes, there is a problem with the current code.
I look at git change history, it's because of the problem introduced when replacing fastjason with Jackson.

Just remove the ".ToString()" in the process of building JSON
Interested in contributing a PR ?
@ruanwenjun @shuimuziyang

**Comment by ruanwenjun** [comment]
> Yes, there is a problem with the current code.
> I look at git change history, it's because of the problem introduced when replacing fastjason with Jackson.
> 
> Just remove the ".ToString()" in the process of building JSON
> Interested in contributing a PR ?
> @ruanwenjun @shuimuziyang

#5243 will solve this issue.
