### ISSUE TITLE
[Bug][master] High load on workgroup A can cause workgroup B can‘t run task（work组A的机器负载高会影响work组B上作业的执行）

### ISSUE THREAD

**Issue by glxfeng** [apache/dolphinscheduler#5242]
1.Our DS cluster has 3 masters, 3 workgroups, each workgroup has several worker nodes, and each task specifies one of the workgroup.
2.When masterA distributes the tasks of workgroup1, if all nodes of workgroup1 are full load.
![image](https://user-images.githubusercontent.com/57620584/114156557-4bec9d80-9955-11eb-8a96-677179cbc951.png)
At this time, the tasks of workgroup1 will not be distributed any more, and will wait for the nodes in workgroup1 to have the load reduced.
3.At this time, if masterA starts to distribute the tasks of workgroup2, the log will show that the task has been submitted successfully.
![image](https://user-images.githubusercontent.com/57620584/114156447-2c557500-9955-11eb-8353-58e1c007c92d.png)
4.However, the tasks of workgroup2 are not actually distributed to workers for execution, but must wait until the node load of workgroup1 reduced.
![image](https://user-images.githubusercontent.com/57620584/114156866-9a9a3780-9955-11eb-81b3-57247c0d26d8.png)
5. if the task of workgroup2  is distributed at this time is idle masterB or masterC, the task can be distributed normally
-----------------------------------------------中文----------------------------------------------------------------------------
1.我们的DS集群有3个master，3个worker组，每个worker组各有若干个worker节点，每个任务都会指定其中的1个worker组。
2.当masterA分发worker组1的任务时，如果worker组1所有节点都满负载，日志里会提示
![image](https://user-images.githubusercontent.com/57620584/114156557-4bec9d80-9955-11eb-8a96-677179cbc951.png)
此时worker组1的任务不会再分发，会等待worker组1中有负载降下来的节点。
3.此时如果masterA又开始分发worker组2的任务，日志里会显示任务提交成功，
![image](https://user-images.githubusercontent.com/57620584/114156447-2c557500-9955-11eb-8353-58e1c007c92d.png)
4.但是，worker组2的任务实际上并不会被分发到worker上执行，而必须等待worker组1的节点负载降下来之后才会执行
![image](https://user-images.githubusercontent.com/57620584/114156866-9a9a3780-9955-11eb-81b3-57247c0d26d8.png)
5.而如果此时负责分发worker组2任务的是空闲的masterB或者masterC，任务是能正常分发的

**Which version of Dolphin Scheduler:**
 -[1.3.4]

**Comment by CalvinKirs** [comment]
taskPriorityQueue.size() <= failedDispatchTasks.size()
It seems that the problem here should be caused by too many tasks of failedDispatchTasks.

**Comment by glxfeng** [comment]
> taskPriorityQueue.size（）<= failedDispatchTasks.size（）
> 这里的问题似乎应该是由FailureDispatchTasks的太多任务引起的。

日志里确实有很多dispatch error的报错信息，请问这是怎么产生的呢？
There are a lot of error messages about dispatch error in the log. How did this happen?
![image](https://user-images.githubusercontent.com/57620584/114169214-da681b80-9963-11eb-9ea5-3f48fd10dffd.png)

**Comment by CalvinKirs** [comment]
> > taskPriorityQueue.size（）<= failedDispatchTasks.size（）
> > 这里的问题似乎应该是由FailureDispatchTasks的太多任务引起的。
> 
> 日志里确实有很多dispatch error的报错信息，请问这是怎么产生的呢？
> There are a lot of error messages about dispatch error in the log. How did this happen?
> ![image](https://user-images.githubusercontent.com/57620584/114169214-da681b80-9963-11eb-9ea5-3f48fd10dffd.png)

When the worker load is too high, the task will not be accepted, so when the master sends the task to the worker, no suitable worker can work.

**Comment by glxfeng** [comment]
> > > taskPriorityQueue.size（）<= failedDispatchTasks.size（）
> > > 这里的问题似乎应该是由FailureDispatchTasks的太多任务引起的。
> > 
> > 
> > 日志里确实有很多dispatch error的报错信息，请问这是怎么产生的呢？
> > There are a lot of error messages about dispatch error in the log. How did this happen?
> > ![image](https://user-images.githubusercontent.com/57620584/114169214-da681b80-9963-11eb-9ea5-3f48fd10dffd.png)
> 
> When the worker load is too high, the task will not be accepted, so when the master sends the task to the worker, no suitable worker can work.

So is this a bug? Work groups should not influence each other.
所以这算是bug吗？工作组之间不应该互相影响吧。

**Comment by caishunfeng** [comment]
Hi @glxfeng This issue had been fixed and you can check the latest code. This issue will be closed, you can reopen it if need.
