### ISSUE TITLE
[Bug][API] Click to view the data source parameters in the data source list, and the type attribute is null

### ISSUE THREAD

**Issue by Jonathan-Wei** [apache/dolphinscheduler#5250]
**Describe the bug**
Click to view the data source parameters in the data source list, and the type attribute is null

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Go to 'DataSource Center'
2. Click on 'Create DataSource'
3. Create a data source of type MySQL
4. Return the list of data sources,click to view the data source parameters in the data source list, and the type attribute is null

**Expected behavior**
Data sources other than Oracle do not display the type attribute

**Screenshots**
![image](https://user-images.githubusercontent.com/3073018/114275585-b7b62f80-9a55-11eb-83f7-ed4403d71297.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Additional context**

**Requirement or improvement**
- The DataSourceServiceImpl buildParameter() method adds a type determination, and does not set the type attribute except for the Oracle type data source

**Comment by Jonathan-Wei** [comment]
![image](https://user-images.githubusercontent.com/3073018/114276021-6dce4900-9a57-11eb-99c6-17842f40e217.png)
From a code point of view, whether type should be displayed here is the corresponding data type. @dailidong

**Comment by Jonathan-Wei** [comment]
`public static final String ORACLE_DB_CONNECT_TYPE = "connectType";`

**Comment by ruanwenjun** [comment]
@Jonathan-Wei The type is connectType, it is only used by Oracle. This has been mentioned in #5083, this make confusion, and will be solved.

**Comment by Jonathan-Wei** [comment]
I know that the type attribute here should be the corresponding data source type, and here the connectType value is assigned to the type attribute @ruanwenjun

**Comment by Jonathan-Wei** [comment]
I will fix it. please assign it to me!

**Comment by ruanwenjun** [comment]
@Jonathan-Wei No, the type is not data source type there :）

**Comment by Jonathan-Wei** [comment]
Type and ConnectType have the same value? @ruanwenjun

**Comment by ruanwenjun** [comment]
@Jonathan-Wei Yeah, you are right, we need to distinguish the type and connectType here, and I think the type does not need to be stored in paramMap.

**Comment by Jonathan-Wei** [comment]
It's OK not to display the type, except that the buildParameter() method splits the null value into the connectionParams parameter during processing, causing the type to be displayed as null @ruanwenjun

**Comment by Jonathan-Wei** [comment]
It's OK not to display the type at all. For now, the buildParameter() method splits the null value into the connectionParams parameter during processing, causing the type to be displayed as null @ruanwenjun

**Comment by ruanwenjun** [comment]
@Jonathan-Wei We can remove line 491.

**Comment by Jonathan-Wei** [comment]
Yes. Let me change this. I submitted it for the first time; Ha ha。 @ruanwenjun

**Comment by zhuangchong** [comment]
Merged.
