### ISSUE TITLE
[Improvement][Common] Use JMX to expose configuration and metrics

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#5255]
**Describe the question** 
In the future the configuration might be coverage as mentioned in #5164, sometimes we need to know the actual configuration at runtime, we can use [JMX](https://docs.oracle.com/javase/tutorial/jmx/overview/index.html.) to expose configuration.
And we also expose some stander metrics like running task number, system load... by JMX, this makes it easy to intergrate with monitoring system like prometheus, of course this is optional.

**Which version of DolphinScheduler:**
 -[1.3.6-preview]

**Comment by davidzollo** [comment]
greate idea.
Did you have any plan to implement this feature? or do we need to talk about how many metrics should we expose?

**Comment by CalvinKirs** [comment]
Very good advice, if you're going to do it, it's best to wait until #5164  is done.

**Comment by davidzollo** [comment]
> Very good advice, if you're going to do it, it's best to wait until #5164 is done.

I think we can talk about which metrics should be exposed first,  it doesn‘t affect the issue #5164

**Comment by ruanwenjun** [comment]
closed, since we already have a dolphinscheduler-meter module to do this.
