### ISSUE TITLE
[Meetup] Apache DolphinScheduler & Apache ShardingSphere Global Online co-Meetup on Saturday, May 15, 2021 

### ISSUE THREAD

**Issue by davidzollo** [apache/dolphinscheduler#5262]
![默认文件1617963344672](https://user-images.githubusercontent.com/15833811/114401051-2372d680-9bd5-11eb-8c00-d3f05f2f12d1.png)

### Details
This is a co-meetup for users of DolphinScheduler and ShardingSphere communities,

Apache DolphinScheduler is a distributed and extensible workflow scheduler platform with powerful DAG visual interfaces, dedicated to solving complex job dependencies in the data pipeline and providing various types of jobs available `out of the box`.

Apache ShardingSphere is an open-source ecosystem consisted of a set of distributed database solutions, including 3 independent products, JDBC, Proxy & Sidecar (Planning). They all provide functions of data scale out, distributed transaction and distributed governance, applicable in a variety of situations such as Java isomorphism, heterogeneous language and cloud native.

![co_meetup](https://user-images.githubusercontent.com/15833811/118018144-02df9d00-b38a-11eb-9964-d68b8796fbba.png)

**Comment by wen-hemin** [comment]
+1

**Comment by davidzollo** [comment]
![co_meetup](https://user-images.githubusercontent.com/15833811/118018039-dcb9fd00-b389-11eb-85f7-5c6026357c0a.png)

**Comment by davidzollo** [comment]
A Cloud native, Smart and Easy Job Scheduler  https://youtu.be/ja451R9_lX0  

Sharing from William Guo, apache Member、Apache DolphinScheduler PMC and Analysys CTO

Shared from Apache DolphinScheduler & ShardingSphere  co-meetup
