### ISSUE TITLE
[Question] Useless property in the `Command` and `ErrorCommand` table

### ISSUE THREAD

**Issue by mrproliu** [apache/dolphinscheduler#5269]
**Useless property in the `Command` and `ErrorCommand` table**
I'm working on adopting the table field to our company database specification: all the fields could not be `null`. 
So I found the `Command` and `ErrorCommand` table has `dependence` in the database, but I cannot found [the bean property in java bean](https://github.com/apache/incubator-dolphinscheduler/blob/5d264c9f208a089bc1f23be5f3077d2dab2b0f40/dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/Command.java). I found the [t_ds_command](https://github.com/apache/incubator-dolphinscheduler/blob/5d264c9f208a089bc1f23be5f3077d2dab2b0f40/sql/dolphinscheduler_mysql.sql#L330) and [t_ds_error_command](https://github.com/apache/incubator-dolphinscheduler/blob/5d264c9f208a089bc1f23be5f3077d2dab2b0f40/sql/dolphinscheduler_mysql.sql#L378) DDL file defined this field. 

**Which version of DolphinScheduler:**
 - dev branch

**Requirement or improvement**
- I think it should be removed, Does I miss anything?

**Comment by BoYiZhang** [comment]
It cannot be removed .

t_ds_Command is the core table. It is used to trigger tasks

t_ds_error_command is used to record wrong command information
It can be used in the monitoring page of Web UI

**Comment by mrproliu** [comment]
> It cannot be removed .
> 
> t_ds_Command is the core table. It is used to trigger tasks
> 
> t_ds_error_command is used to record wrong command information
> It can be used in the monitoring page of Web UI

Hi, Thanks for the reply.

I mean should remove the `dependence ` field, not remove the table. On my tests,  It running well after remove the `dependence` field.

**Comment by wen-hemin** [comment]
Yes, The field "dependence" is not used, can remove it.
Welcome create a PR.
