### ISSUE TITLE
[Feature][master-server] After the task has been executed in the workflow and retried, it cannot be manually pulled up

### ISSUE THREAD

**Issue by hutao1990** [apache/dolphinscheduler#5272]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/community/development/issue.html when describe an issue.*

**Describe the feature**
When a task fails to execute in the process of workflow execution, it can be manually pulled up on the workflow instance page instead of waiting until the workflow is finished

**Describe the solution you'd like**
Now ，I have a 1400-node workflow, which takes 6-8 hours to execute. Sometimes, the check node fails to retry, but it cannot be pulled up manually. 

**Describe alternatives you've considered**
The workflow must be killed before it can be executed again, which will seriously affect the overall execution time of the workflow，now I am trying to increase the intermediate state to deal with this problem

**Additional context**
At present, when the workflow is executed, there are tasks that fail, and the status is still RUNNING_EXEUTION. It is suggested to add a status that can describe the current workflow, such as RUNNING_FAILED, which can be perceived on the page and can be pulled up manually

**Comment by xingchun-chen** [comment]
Good idea， look forward to your contribution
