### ISSUE TITLE
how can i skip a failed task and continue to execute the follow tasks?请问是否有办法在流程某一步报错后跳过该步继续执行后面的步骤呢

### ISSUE THREAD

**Issue by praynise** [apache/dolphinscheduler#5281]
how can i skip a failed task and continue to execute the follow tasks？thanks a lot
请问是否有办法在流程图中某一个任务报错后，手动跳过该任务（或强制该任务为成功），继续执行该任务后面的任务呢？非常感谢
**Which version of DolphinScheduler:**
 -[1.3.5]

**Comment by chengshiwen** [comment]
@praynise Since **Force Task Success** has introduced in dev branch in #4267. So in the near future, we will see this feature in the official release version.

**Comment by praynise** [comment]
great news,thanks a lot.I am looking forward it
太棒了，非常感谢，我很期待该功能的上线
