### ISSUE TITLE
[Question] The condition node is not working.

### ISSUE THREAD

**Issue by mrproliu** [apache/dolphinscheduler#5282]
**The condition node is not working.**
I have created a condition task but always run the success task. I'm not sure it's a bug or setting problem, please give some help.
![image](https://user-images.githubusercontent.com/3417650/114839236-1e499d80-9e08-11eb-9b0d-3a0461ab3e78.png)
There is a workflow instance, after condition node, it should running `前置处理认定不可以继续执行后的后置处理` node. 

Here is the condition node configure.
![image](https://user-images.githubusercontent.com/3417650/114839697-a7f96b00-9e08-11eb-8075-844c3add38f9.png)

After I deep into the code level, I found condition task node configure is not has the `dependence` content. 
```JSON
{
      "id": "tasks-31996",
      "name": "判定前置判断是否执行成功",
      "type": "CONDITIONS",
      "runFlag": "NORMAL",
      "maxRetryTimes": 0,
      "retryInterval": 1,
      "params": {},
      "preTasks": [
        "前置判断"
      ],
      "depList": [
        "前置判断"
      ],
      "dependence": {
        "relation": "AND",
        "dependTaskList": []
      },
      "conditionResult": {
        "successNode": [
          "启动业务任务"
        ],
        "failedNode": [
          "前置处理认定不可以继续执行后的后置处理"
        ]
      },
      "taskInstancePriority": "MEDIUM",
      "workerGroup": "default",
      "timeout": {
        "strategy": "",
        "enable": false
      },
      "delayTime": 0
    },
```

**Which version of DolphinScheduler:**
 - dev branch

**Comment by xingchun-chen** [comment]
You need to set custom parameters. The Condition node determines which branch to take according to the success or failure status of the front node

![image](https://user-images.githubusercontent.com/55787491/114842006-04f62080-9e0b-11eb-84b3-d7898fc27a1e.png)

**Comment by mrproliu** [comment]
> You need to set custom parameters. The Condition node determines which branch to take according to the success or failure status of the front node
> 
> ![image](https://user-images.githubusercontent.com/55787491/114842006-04f62080-9e0b-11eb-84b3-d7898fc27a1e.png)

Hi, Thanks for your quick response. It's working.
