### ISSUE TITLE
can not find log info in package org.apache.dolphinscheduler.server.worker.processor

### ISSUE THREAD

**Issue by wengieeee** [apache/dolphinscheduler#5283]
Can not find log info in package org.apache.dolphinscheduler.server.worker.processor .

This problem occurs in my macbook and online worker

but log of other package like org.apache.dolphinscheduler.server.worker.runner will be printed to the dolphinscheduler-worker.log.

我的本机和我们线上的worker，org.apache.dolphinscheduler.server.worker.processor 目录下的日志基本都不打印的。这个日志应该是输出到dolphinscheduler-worker.log 这个日志文件下是吗？也是今天我们排查问题的时候发现没有日志输出才发现的

**Comment by zhuangchong** [comment]
@Yanwenjingcn 

Which version? In version 1.3.5, a repair was made to the missing part of the worker log.

**Comment by wengieeee** [comment]
> @Yanwenjingcn
> 
> Which version? In version 1.3.5, a repair was made to the missing part of the worker log.

yes，1.3.5 ，We edit org.apache.dolphinscheduler.server.log.MasterLogFilter ，it ifx

**Comment by chengshiwen** [comment]
Close this issue since it has been resolved
