### ISSUE TITLE
[Improvement][ApiServer] Better Entity Restains when Creating

### ISSUE THREAD

**Issue by huangwei2013** [apache/dolphinscheduler#5288]
**Describe the question**

数据上下文约束不足
    - 创建租户：需关联queue，但未对输入的queueId做校验
    - 更新租户：上层无体现，最底层却隐含了对queue所在表的关联查询
        - 触发场景：创建租户-随意选择queue(成功)-->更新租户(失败，提示租户不存在)

As title，
    - When creating a Tenant by API，queue/queueId can be anything input，no check here.
    - While try to update this Tenant,  TenantMapper.xml use  _where t.queue_id = q.id_  , different data restains resulted in _[no tenant found ]_

**What are the current deficiencies and the benefits of improvement**

Stricter and consistently API and behavior

**Which version of DolphinScheduler:**
 -[1.3.5.rc]

**Describe alternatives you've considered**

Check when creating

**Comment by zhuangchong** [comment]
@huangwei2013 

Welcome to submit a PR to implement this feature.

**Comment by huangwei2013** [comment]
> @huangwei2013
> 
> Welcome to submit a PR to implement this feature.


提交这个submit很简单，但需要确定一个代码风格：
- 这种隐含的联表操作，是保持在 xml 的 mapper中（对上层隐藏）  or  方法定义的时候表现出这是个联表操作？

This submit is easy，but a consensus  of coding style is required.
- Keeping the implicatio _where t.queue_id = q.id_ in a deafness method， OR ， make it more clarify by better name？

**Comment by zhuangchong** [comment]
Using the second method, the representation of the association within the method.
