### ISSUE TITLE
[WebSite]Information correction after graduation

### ISSUE THREAD

**Issue by CalvinKirs** [apache/dolphinscheduler#5295]
Since DolphinScheduler has graduated, the warehouse address and other incubation-related information on the official website need to be corrected. Anyone interested in this can choose to complete it.

webiste git address:https://github.com/apache/dolphinscheduler-website

**Comment by CalvinKirs** [comment]
- [x] https://dolphinscheduler.apache.org/zh-cn/community/team.html 
- [x] https://dolphinscheduler.apache.org/en-us/community/team.html
The mentors was moved to the PMC list, and PPMC was changed to PMC

- [x] https://dolphinscheduler.apache.org/
The bottom disclaimer needs to be deleted

- [x] https://dolphinscheduler.apache.org/en-us/community/release.html
- [x] https://dolphinscheduler.apache.org/en-us/community/release.html
The related svn address and git address need to be modified

- [x] https://dolphinscheduler.apache.org/en-us/development/development-environment-setup.html
- [x] https://dolphinscheduler.apache.org/zh_cn/development/development-environment-setup.html
git address need to be modified

There are still some scattered git addresses that need to be modified.

**Comment by QuakeWang** [comment]
I am glad to try it :)

**Comment by CalvinKirs** [comment]
> I am glad to try it :)

Looking foward you submit PR

**Comment by davidzollo** [comment]
> I am glad to try it :)

I have assigned to you, thx

**Comment by QuakeWang** [comment]
Hi, I have the following points of doubt when making changes:

-  Is this [page](https://dolphinscheduler.apache.org) a file in md format or index.html?
-  I found that some places in the file use Github while others use github, should it be unified?
- In the [release page](https://dolphinscheduler.apache.org/en-us/community/release.html), should I remove all information about the mentors and incubators?

**Comment by chengshiwen** [comment]
Close this issue since website information correction has finished
