### ISSUE TITLE
[Feature][kubernetes] yarn resourcemanager address should be flexible in configuration

### ISSUE THREAD

**Issue by KW-night** [apache/dolphinscheduler#5306]
In version 1.3.5 of the kubernetes image，The configuration item (_yarn.resourcemanager.ha.rm.ids_ & _yarn.application.status.address_) in _common.properties.tpl_ is a fixed constant.

> -- if resourcemanager HA enable, please type the HA ips ; if resourcemanager is single, make this value empty
> yarn.resourcemanager.ha.rm.ids=192.168.xx.xx,192.168.xx.xx
> 
> -- if resourcemanager HA enable or not use resourcemanager, please keep the default value; If resourcemanager is single, you only need to replace ds1 to actual resourcemanager hostname.
> yarn.application.status.address=http://ds1:8088/ws/v1/cluster/apps/%s

If the task type is YARN task，Work node will retrieve the execution result of the task based on the above two configurations.
That means I need to manually change it to a valid value in the container, or rebuild the image.

So I suggest：
Put them in the form of ${variable}, and pass the value through the ConfigMap.
Just like the configuration of _fs.s3a.***_.

**Comment by chengshiwen** [comment]
@KW-night The configurations has added into `1.3.6-release` which will be released in a few days. Refer to https://github.com/apache/dolphinscheduler/blob/1.3.6-release/docker/kubernetes/dolphinscheduler/values.yaml

![image](https://user-images.githubusercontent.com/4902714/115015476-49a2ba00-9ee6-11eb-9d75-4bb9a7fc0f5f.png)
