### ISSUE TITLE
[Bug][worker] when shell task raw script has $[${day} - 1]，throw java.lang.IllegalArgumentException::Pattern includes reserved character:'{'

### ISSUE THREAD

**Issue by cyx-code** [apache/dolphinscheduler#5316]
for example, shell task content is 
#!/bin/bash
set -x
Yesterday=$(date -d "1 day ago" +"%Y-%m-%d")
Today=$(date +"%Y-%m-%d")
whichday=`date -d $Today +"%w"`
monday=`date -d "$today -$[${whichday}-1] days" +"%Y-%m-%d 00:00:00"`
when execute task ,log is 
![image](https://user-images.githubusercontent.com/39180064/115172245-70840a80-a0f7-11eb-9b0b-f5f3247b8946.png)

**Comment by cyx-code** [comment]
I think the regular expression need modify.And the pull request is https://github.com/apache/dolphinscheduler/pull/5313

**Comment by zhuangchong** [comment]
done.
