### ISSUE TITLE
How can I force the assignment of tasks to be assigned to workers in turn?

### ISSUE THREAD

**Issue by praynise** [apache/dolphinscheduler#5320]
How can I force the assignment of tasks to be assigned to workers in turn?
嗯…英文是用谷歌翻译的，请问如何使任务分配方式强制为worker轮流分配。在我的使用场景，我不太希望master在分配任务的时候考虑当前资源，因为我的设备运行情况比较复杂，有很多混合部署，非常感谢！
**Which version of DolphinScheduler:**
 -[1.3.5]

**Comment by chengshiwen** [comment]
@praynise In 1.3.x, `RoundRobin` can meet your need, so just configure the following line in `master.properties`:
```
master.host.selector=RoundRobin
```

**Comment by chengshiwen** [comment]
Close this issue sine no updates for several days
