### ISSUE TITLE
[Bug][api-server] delete the user ,when query the project by join the table of t_ds_user will return null.

### ISSUE THREAD

**Issue by wangxj3** [apache/dolphinscheduler#5326]
delete the user ,when query the project by join the table of t_ds_user will return null.
Suggested that  [
from t_ds_project p
        join t_ds_user u on p.user_id = u.id
]changed  to  [
from t_ds_project p
       left  join t_ds_user u on p.user_id = u.id
]

**Comment by fanwq** [comment]
i have fixed this bug in pr #5327, please review that.

**Comment by ruanwenjun** [comment]
I think the best solution is to prevent deleting the user if the user owns a project until the user deletes the project he owns or change the owner. Otherwise, we will find out that a project does not have an owner, this also cause confusion.

**Comment by wangxj3** [comment]
The user_id of t_ds_project is the create user id. If we want to delete this user which create this project ,we should delete this project first,but this project may be visible and used by other users.May be functions that can be replaced by project owners is a choice.

**Comment by ruanwenjun** [comment]
> The user_id of t_ds_project is the create user id. If we want to delete this user which create this project ,we should delete this project first,but this project may be visible and used by other users.May be functions that can be replaced by project owners is a choice.

Yeal, currently the `user_id` in `t_ds_project` table represents project creator, but I think it might be better to change its meaning to project owner, so that we can provide a method to update the project owner. Otherwise, once we delete the user, the project creator will be null.

**Comment by ruanwenjun** [comment]
@fanwq What do you think?

**Comment by fanwq** [comment]
a project can be owned by more than one user, so i think it's better to define user_id as project creator other than owner. Project owners are defined in `t_ds_relation_project_user`.

**Comment by ruanwenjun** [comment]
> a project can be owned by more than one user, so i think it's better to define user_id as project creator other than owner. Project owners are defined in `t_ds_relation_project_user`.

I think the project owner should be only one, others just have the permission for the project, the relation is defined in `t_ds_relation_project_user `, and they should not be defined as owner. Or do you have other ways to solve the problem of user being null if we delete the user in the `t_ds_project`.

**Comment by wangxj3** [comment]
when delete the user  ,if he is a  the owner,  chose a new owner form the t_ds_relation_project_user .What do you think of this plan?

**Comment by ruanwenjun** [comment]
> when delete the user ,if he is a the owner, chose a new owner form the t_ds_relation_project_user .What do you think of this plan?

Agree, but I think you should let user choose a new owner from `t_ds_user`, because there may not relation in `t_ds_relation_project_user `. And how to interact if there are multiple project belongs to the delete user. 

This kind of problem also exists for `resource` and `processdefinition`, cause by store the `user_id`. This seems to be a large-scale issue.

**Comment by wangxj3** [comment]
> 
> 
> > when delete the user ,if he is a the owner, chose a new owner form the t_ds_relation_project_user .What do you think of this plan?
> 
> Agree, but I think you should let user choose a new owner from `t_ds_user`, because there may not relation in `t_ds_relation_project_user `. And how to interact if there are multiple project belongs to the delete user.
> 
> This kind of problem also exists for `resource` and `processdefinition`, cause by store the `user_id`. This seems to be a large-scale issue.
