### ISSUE TITLE
[Bug][MasterServer] process contain depend task is always running

### ISSUE THREAD

**Issue by wanghong1314** [apache/dolphinscheduler#5328]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Will the process scheduling up regularly, and must be "failed policies" to "end"
2. The first mission there is no corresponding directory file (for the first time this failure) (namely the execution of the catalog file to a certain consensus ikkkk and fb both task execution of the same file)
3. Then retry the second time, in the corresponding directory to create executable files, so that it was successful
4. Observe the state of the process

**Comment by CalvinKirs** [comment]
hi, is there any progress?

**Comment by wanghong1314** [comment]
> hi, is there any progress?

Has been resolved, I to submit to the dev branch

**Comment by wanghong1314** [comment]
Fix the bug
merge Link https://github.com/apache/dolphinscheduler/pull/5338/commits
