### ISSUE TITLE
Issues with changing Docker configuration

### ISSUE THREAD

**Issue by wqxs** [apache/dolphinscheduler#5332]
I modified the docker-compose.yml file, but it failed to boot
![~MFLB FHII72H TEQAAPBY3](https://user-images.githubusercontent.com/69672009/115490723-38b0ca80-a291-11eb-8d71-270d98ea4c0e.png)
![S~4S1R3 F%(JIRIM%{YQDYA](https://user-images.githubusercontent.com/69672009/115490757-4fefb800-a291-11eb-8979-4974ebb9237e.png)
![8XF$P_U8I(H%Y R4_`LEHUS](https://user-images.githubusercontent.com/69672009/115490794-6269f180-a291-11eb-9646-3044ec58a348.png)

**Comment by chengshiwen** [comment]
@wqxs Have the database and zookeeper been started first? Have all the `DATABASE` and `ZOOKEEPER` environment variables been modified in the `docker-compose.yaml` file?

**Comment by wqxs** [comment]
It has been resolved. The postgresql-client in the Dockerfile should be modified to mysql-client, because I am using the mysql library

**Comment by wqxs** [comment]
It has been resolved. The postgresql-client in the Dockerfile should be modified to mysql-client, because I am using the mysql library

**Comment by chengshiwen** [comment]
Please refer to **How to use MySQL as the DolphinScheduler's database instead of PostgreSQL?**
in **FAQ** in https://dolphinscheduler.apache.org/en-us/docs/1.3.5/user_doc/docker-deployment.html

**Comment by chengshiwen** [comment]
Close the issue since it has been resolved
