### ISSUE TITLE
[Bug][login] Unable to sign in

### ISSUE THREAD

**Issue by djhexe** [apache/dolphinscheduler#5337]
1、database:mysql-5.7.28
2、Login report the following error
[dolphinscheduler-api-server.log](https://github.com/apache/dolphinscheduler/files/6349857/dolphinscheduler-api-server.log)
[dolphinscheduler-master.log](https://github.com/apache/dolphinscheduler/files/6349858/dolphinscheduler-master.log)

**Comment by ruanwenjun** [comment]
@djhexe It seems that the mysql driver is missing, you can check the scope of mysql-connector-java in pom.xml.
https://dolphinscheduler.apache.org/en-us/docs/release/faq.html

**Comment by Jonathan-Wei** [comment]
```
            <dependency>
                <groupId>mysql</groupId>
                <artifactId>mysql-connector-java</artifactId>
                <version>${mysql.connector.version}</version>
                <scope>compile</scope>
            </dependency>
```

Modify the POM file in mysql-connector-java's scope for complie and try again. @djhexe

**Comment by chengshiwen** [comment]
Close it since it has replied
