### ISSUE TITLE
[Improvement][API] Zookeeper dependence

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#5350]
**Describe the question**
Currently, the `dolphinscheduler-api` module relies on `zookeeper` to do some operations about the worker group. The problem is that if the `api` cannot connect with zookeeper, then `api` will not start successfully, this caused by `ZookeeperOperator` init block.

I think the dependence of `api` to `zookeeper` should be a weak dependence, it shouldn't affect the core function of `api`.

**Which version of DolphinScheduler:**
 -[1.3.6]
 -[dev]

**Describe alternatives you've considered**

**Comment by davidzollo** [comment]
Yes, weak dependence will be a good choice
