### ISSUE TITLE
[Improvement][DAO] CreateDolphinScheduler

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#5357]
**Describe the question**
When we run `sh script/create-dolphinscheduler.sh` to init the dolphinscheduler database environment, it will execute the old script in `sql/create` and upgrade to latest. It is better to execute the new sql script.

**Which version of DolphinScheduler:**
 -[1.3.6]
 -[dev]

**Describe alternatives you've considered**
Change the sql init file to `sql/dolphinscheduler_mysql.sql`

**Comment by davidzollo** [comment]
good job
