### ISSUE TITLE
[Bug][MasterServer] The Command queue was blocked due to the thread 'MasterSchedulerService' terminated

### ISSUE THREAD

**Issue by xiashao1980** [apache/dolphinscheduler#5364]
**Describe the bug**
When I add thousands of process instances to DS by API, sometimes the newest process could not be found in the process instance list. I had researched the tables in the ds database, and I found that all new instance requests were saved in 'ds_command'. I dumped the stack of the ds master service process, but the information of the 'MasterSchedulerService' thread did not exist in the log file.
It seemed that the core thread 'MasterSchedulerService' has been terminated accidentally.
Then, I had to restart the ds master service, and all blocked commands had been executed soon.

Please download the 'jstack' log file by the following URL:
URL：https://pan.baidu.com/s/1NL2mM2s9ud7rqMM0It3pOw 
code：ttn5 

Thanks.

**To Reproduce**
1. Set 'worker.exec.threads' to 1
2. Set 'master.exec.threads' to 4000
3. Add two thousand process instances to DS by API in 1 minute.
4. If it is not blocked, add more instances and try again.

**Expected behavior**
Anyway, the 'MasterSchedulerService' thread should not be terminated accidentally.

**Screenshots**
No.

**Which version of Dolphin [Scheduler:**]
1.3.4

**Comment by xiashao1980** [comment]
Version:
DolphinScheduler 1.3.4

Find follow log in 'dolphinscheduler-master-server-centerserver.out':
Exception in thread "Master-Exec-Thread" java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1018)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wangxj3** [comment]
> 
> 
> Version:
> DolphinScheduler 1.3.4
> 
> Find follow log in 'dolphinscheduler-master-server-centerserver.out':
> Exception in thread "Master-Exec-Thread" java.lang.OutOfMemoryError: unable to create new native thread
> at java.lang.Thread.start0(Native Method)
> at java.lang.Thread.start(Thread.java:714)
> at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
> at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1018)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> at java.lang.Thread.run(Thread.java:745)

Suggest decrease the master.exec.threads or add master-server.

**Comment by xiashao1980** [comment]
After decreased 'master.exec.threads' to 1400, this issue disappeared.
