### ISSUE TITLE
how can i get log in real time

### ISSUE THREAD

**Issue by praynise** [apache/dolphinscheduler#5365]
A simple example is, i create a shell task,with script as below:
echo "hello"
sleep 60
echo "hello again"
when i run this task,i can not read first "hello" in the log until the whole task finish.is there a way to get log text in real time?

by the way,another question is,can i change the curve in the DAG into straight line?
many thanks
举个栗子，例如我建了一个shell节点，里面是echo "hello";sleep 60;echo "hello again"，在sleep的时候我无法从日志中看到第一个hello，请问是否有办法实时获取到日志呢？

另外还想问一个问题，有没有办法把DAG图里面的连线从曲线换成直线呢…在我们的应用场景中，曲线会显得DAG图很乱…
非常感谢
**Which version of DolphinScheduler:**
 -[1.3.5]

**Comment by ruanwenjun** [comment]
I think it can get the log content in real time, have you tried refresh?

**Comment by praynise** [comment]
@ruanwenjun  i tried,but it does not work.
i found out that when i use a script like echo "hello";sleep 60;echo "hello again",it refreshed after echo "hello again".the first "hello" will not be showed in the log while the script sleeping
我试过刷新，但是不好用。我发现只有在第二个hello again执行完之后，第一个hello才会被展示。当脚本执行sleep 60的时候，第一个echo "hello"的结果是不会被展示在log内容中的

**Comment by ruanwenjun** [comment]
@praynise Are you sure your `ds` version is 1.3.5? I can get the first "hello" during the sleep in 1.3.5.

**Comment by praynise** [comment]
@ruanwenjun i am sure...my bin pkg name is apache-dolphinscheduler-incubating-1.3.5-dolphinscheduler-bin.i am using adoptjdk1.8.0_282-b08，is it possible caused by my jdk?
是的，我的包的确是1.3.5，我是从官网下载的二进制包，我目前用的jdk是adoptjdk1.8.0_282-b08，这个问题有没有可能是我使用的jdk造成的呢

**Comment by ruanwenjun** [comment]
@praynise Can you find the log information from the task log file while it is running? The task log file is at logs/xx/yy/zz.log
