### ISSUE TITLE
Toolbox SQL  "select result" as a excel error attach file in mail

### ISSUE THREAD

**Issue by lauliu** [apache/dolphinscheduler#5366]
**Describe the bug**
Toolbox SQL when I use "select SQL  result" s a excel attach file in mail,but email received,the attach excel file is error，which name is “=UTF-8BRFPosIPluqbmtYvor5XvvJrov5DooYxzcWzmn6Xor6I== =UTF-8B57uT5p6c55u05o6l5a+85Ye66YKu5Lu25Y+R6YCBLnhscw===”

**Which version of Dolphin Scheduler:**
 -[1.3.5-preview]

<img width="497" alt="微信图片_20210423173825" src="https://user-images.githubusercontent.com/48465807/115852545-c7247800-a45a-11eb-944e-b0b9147eb410.png">
<img width="651" alt="微信图片_20210423173831" src="https://user-images.githubusercontent.com/48465807/115852548-c855a500-a45a-11eb-9093-55b7bb59a0f5.png">

**Comment by ruanwenjun** [comment]
Does this issue appear in other task? It works well on my machine.

**Comment by lauliu** [comment]
hey,in new project is well!
