### ISSUE TITLE
[Improvement][Plugin] Add Permissions check for plugin instance

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#5370]
**Describe the question**
Currently, there is no permission check for the plugin instance, when I create a plugin instance, it can be used by everyone. Sometimes this is dangerous.

And the front-end displays the security information e.g. password directly is also very dangerous. It is better to encode the security information or return `*****` in the api response. 

**Which version of DolphinScheduler:**
 -[1.3.6-preview]
 -[dev]

**Comment by BoYiZhang** [comment]
Thanks for the feedback, this is a problem.
At present, the security aspect of DS is still very weak, welcome to join us to build together.
