### ISSUE TITLE
[Feature][Support Processes Depand dependance] Processes A Must Run before  Processes B

### ISSUE THREAD

**Issue by lauliu** [apache/dolphinscheduler#5374]
**Describe the feature**
In a Proceess,these nodes DAG is very good,but why not support the DAG or dependance between two Processes ?

**Describe the solution you'd like**
1. We can design a node named `Procees`,whice s suppert quote or link to an exists proceess A,when when we running the  `Procees` node is the same as running A;
2. We also can design an new subject,such as name Job,It‘s function was to add many dependance steps,and one step is the same as one exists proccess;

**Comment by ruanwenjun** [comment]
At present, the dependence between multiple processes has been supported, you can add a dependent type node to declare the relation. https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/task-structure.html
Have I answered your question?

**Comment by lauliu** [comment]
It‘s work as your follow，thanks very much！
