### ISSUE TITLE
Increase global variables similar to airflow, not in DAG

### ISSUE THREAD

**Issue by zhbdesign** [apache/dolphinscheduler#5375]
Increase global variables similar to airflow, not in DAG

**Comment by dailidong** [comment]
> Increase global variables similar to airflow, not in DAG
good idea!
Can you describe this feature in more detail? or do you have some docs about this?

**Comment by davidzollo** [comment]
Could you describe this feature in more detail? or do you have some docs about this feature?

**Comment by zhbdesign** [comment]
> Could you describe this feature in more detail? or do you have some docs about this feature?

![image](https://user-images.githubusercontent.com/50901800/120572418-7a1ac500-c44e-11eb-90f5-dfc9880aafa5.png)

Set global variable, independent of DAG, make a global variable module
