### ISSUE TITLE
[Improvement][api] can set email list for each task

### ISSUE THREAD

**Issue by machimedes** [apache/dolphinscheduler#5376]
**Describe the question**
Version1.3.5 is using.
![image](https://user-images.githubusercontent.com/49675726/115984452-b64e4080-a5d9-11eb-86e3-79cad6962865.png)
When editing a task, no place  to set the alert email list.

**What are the current deficiencies and the benefits of improvement**
Can set email alert list for each task.

**Which version of DolphinScheduler:**
 -[1.3.5]

**Comment by ruanwenjun** [comment]
At present, the alert group config is process instance level, it is a good idea to implement the task level config.

**Comment by machimedes** [comment]
This modification is not necessary. May close it.
