### ISSUE TITLE
Use docker to test big data cluster

### ISSUE THREAD

**Issue by gaozhenfeng1** [apache/dolphinscheduler#5378]
Now,I want to use docker to quickly deploy a dolphinscheduler ,then test whether to schedule my big data platform。
Do you modify this configuration file before starting the ds service, and then log in to the previous page and run the flow task to test the connectivity with the big data component?
/script/env/dolphinscheduler_env.sh

**Comment by chengshiwen** [comment]
In 1.3.5 release, you need do additional things:
- Prepare the client binary of the big data platform, such as `hadoop-2.8.3`, `spark-2.4.3-bin-hadoop2.7` or `flink-1.11.3`. And put them into the directory like `/host/path/to/bigdata`
- Add volume `- /host/path/to/bigdata:/opt/soft/bigdata` for `dolphinscheduler-worker` in `docker/docker-swarm/docker-compose.yml`
- Modify the environment variables in `docker/docker-swarm/dolphinscheduler_env.sh`, such as `HADOOP_HOME`, `SPARK_HOME` or `FLINK_HOME`. For example, modify `HADOOP_HOME` to `/opt/soft/bigdata/hadoop-2.8.3` and `HADOOP_CONF_DIR` to `/opt/soft/bigdata/hadoop-2.8.3/etc/hadoop`

**Comment by chengshiwen** [comment]
In next 1.3.6 release, you can refer to the readme https://github.com/apache/dolphinscheduler/blob/3f47bd8425/docker/build/README.md#how-to-support-hadoop-spark-flink-hive-or-datax. The essential principles of these two methods are the same.

**Comment by gaozhenfeng1** [comment]
Ok thanks!
