### ISSUE TITLE
[Bug] `ProcessUtils` seems to contain OpenJDK code

### ISSUE THREAD

**Issue by Marcono1234** [apache/dolphinscheduler#5388]
**Describe the bug**
It appears `org.apache.dolphinscheduler.server.utils.ProcessUtils` contains code from the OpenJDK without mentioning it, and without retaining the copyright header.
(It might also be problematic from a security standpoint since the upstream OpenJDK code has received security patches in the meanwhile.)

If you compare the [initial version of `ProcessUtils`](https://github.com/apache/dolphinscheduler/blob/5c45f92f463b5d6c4b811df1058cc712da67dd7e/escheduler-server/src/main/java/cn/escheduler/server/utils/ProcessUtils.java) with OpenJDKs [`ProcessImpl`](https://github.com/openjdk/jdk/blob/270fe13182e284f3f5d5ae116fb43e591535c2c6/jdk/src/java.base/windows/classes/java/lang/ProcessImpl.java) from a few years ago, you will notice that they in parts contain the same code (with some reformatting applied and comments removed or changed), mainly the `buildCommandStr` method and the private methods it is using.

(Though it could of course also be the case that the same author created this code for this project and for OpenJDK.)

**Comment by CalvinKirs** [comment]
Thx for your feedback,I will deal with this issue
