### ISSUE TITLE
[Question] The custom parameter pass problem

### ISSUE THREAD

**Issue by jiang-zilong** [apache/dolphinscheduler#5389]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
A clear and concise description of what the question is.

**Which version of DolphinScheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

调度shell脚本的时候，脚本是使用的是占位符传参，但是使用自定义变量出啊餐一直不成功，单独测试某一个环节是可以的，求解

**Comment by ruanwenjun** [comment]
Please describe your operation in detail.
