### ISSUE TITLE
 when I run a task using Standalone, Its looger server reports  tenantCode: xxx does not exist.

### ISSUE THREAD

**Issue by yingliwuli** [apache/dolphinscheduler#5401]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
A clear and concise description of what the question is.

**Which version of DolphinScheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by ruanwenjun** [comment]
Does the tenant user is a linux user?
You can find more detail about tenant at this site. https://dolphinscheduler.apache.org/en-us/docs/release/faq.html

**Comment by yingliwuli** [comment]
> Does the tenant user is a linux user?
> You can find more detail about tenant at this site. https://dolphinscheduler.apache.org/en-us/docs/release/faq.html

Thanks a lot. I didn't use system user as the tenant, but now I get it.

**Comment by chengshiwen** [comment]
@yingliwuli Which version? And has the problem been solved?

**Comment by davidzollo** [comment]
> @yingliwuli Which version? And has the problem been solved?

if this issue has been solved, please close this issue, thx

**Comment by dik111** [comment]
我在1.3.6版本中(standalone)遇到相同的问题，查找源码后发现是有这么一个判断
`if (!OSUtils.getUserList().contains(taskExecutionContext.getTenantCode())) {
                String errorLog = String.format("tenantCode: %s does not exist", taskExecutionContext.getTenantCode());`
然后我添加了租户对应的os用户，任务可以执行。

----
I encountered the same problem in version 1.3.6 (standalone). After searching the source code, I found that there was such a judgment
`if (!OSUtils.getUserList().contains(taskExecutionContext.getTenantCode())) {
                String errorLog = String.format("tenantCode: %s does not exist", taskExecutionContext.getTenantCode());`
Then I added the os user corresponding to the tenant, and the task can be executed.
