### ISSUE TITLE
Homepage design of official website

### ISSUE THREAD

**Issue by GaoTianDuo** [apache/dolphinscheduler#5402]
####Design Ideas
     There are three designs.In the first design, the overall feeling is dark blue, as if exploring
 in the sea, with a sense of mystery.Compared with the first design, the second design adds
 light projection, which means hope.The third design is that the dolphin jumps out of the sea, 
 which means success.
      In the three designs, dolphins step by step from the deep sea to shallow sea and finally 
jump out of the sea！
<img width="699" alt="homepage" src="https://user-images.githubusercontent.com/19991611/116268770-33cba980-a7b0-11eb-91e3-e52fc105b84c.png">

**Comment by xingchun-chen** [comment]
I think the three concepts are all very good. They represent different stages of dolphin development. 
I prefer the second one. I like the feeling of light and The color is brighter

**Comment by ruanwenjun** [comment]
Cool, I prefer the third one, this picture brings a good feeling.

**Comment by davidzollo** [comment]
Wow, I like the second style
good job!

**Comment by CalvinKirs** [comment]
done
