### ISSUE TITLE
[Question] fail to submit flink Job

### ISSUE THREAD

**Issue by Chaunceyctx** [apache/dolphinscheduler#5404]
**Which version of DolphinScheduler:**
 -[1.3.4-release]
flink:1.12.0

**Additional context**
![image](https://user-images.githubusercontent.com/29896262/116503789-7f35a300-a8e9-11eb-87ea-fcb6d1467a3f.png)
使用海豚调度器提交flink出现以上问题，之后我修改了海豚的源码重新打包server.jar，把命令改成
flink run **-m yarn-cluster -c 类名 jar包** -ys 1 -yn 2 -yjm 1G -ytm 2G -d --qu default 就能运行，
![image](https://user-images.githubusercontent.com/29896262/116503803-86f54780-a8e9-11eb-83ad-2d397c419f6b.png)
flink使用的版本是1.12.0，请问这是什么问题？

**Comment by chengshiwen** [comment]
@Chaunceyctx This problem has been resolved in 1.3.5, and the related issue is #3457, so please use 1.3.5 or the latest 1.3.6

**Comment by Chaunceyctx** [comment]
> @Chaunceyctx This problem has been resolved in 1.3.5, and the related issue is #3457, so please use 1.3.5 or the latest 1.3.6

Thx!
