### ISSUE TITLE
[Question]The master automatically hangs up when there are too many tasks

### ISSUE THREAD

**Issue by Tandoy** [apache/dolphinscheduler#5407]
**Steps to reproduce the behavior:**
Use the shell node to execute the hive -f command

**Expected behavior:**
Normal ETL

**Environment Description:**
dolphinscheduler：1.3.2
Hadoop version : 2.6.0-cdh5.13.3
Hive version : 1.1.0-cdh5.13.3
Storage (HDFS/S3/GCS..) : HDFS
Running on Docker? (yes/no) :no

**Configuration:**
master.properties
       master.reserved.memory=0.6

**Stacktrace:**
dolphinscheduler-master.log:
![Snipaste_2021-04-29_11-22-47](https://user-images.githubusercontent.com/56899730/116515664-2d981300-a8ff-11eb-96c2-57135eb67201.PNG)

**Comment by ruanwenjun** [comment]
@Tandoy Which version are you using? Maybe you need to reduce this value `master.reserved.memory `.

**Comment by Tandoy** [comment]
> @Tandoy Which version are you using? Maybe you need to reduce this value `master.reserved.memory `.
I am using dolphinscheduler-1.3.2 and tried to reduce `master.reserved.memory` to 0.3, but the master still hangs.Is there an optimal calculation method for the parameter `master.reserved.memory` based on the cluster configuration?

**Comment by Tandoy** [comment]
A worker node has been added to reduce the pressure on the master, and the master has been running stably.
