### ISSUE TITLE
[Question] How to deal with such an error in k8s ？

### ISSUE THREAD

**Issue by ghost** [apache/dolphinscheduler#5410]
**init env variables 
generate dolphinscheduler config 
/root/startup-init-conf.sh: line 150: /opt/dolphinscheduler/conf/env/dolphinscheduler_env.sh: Read-only file system**

**Comment by chengshiwen** [comment]
@zhangfeng114 It seems that your DolphinScheduler chart's appVersion is 1.3.5, but the used docker image is the latest (1.3.6). So either modify the `image.tag` in values.yaml to `1.3.5` (Or run `helm install dolphinscheduler . --set image.tag=1.3.5`), or just use the latest `1.3.6` DolphinScheduler chart.
There are a lot of optimizations related to docker and k8s in 1.3.6. Please refer to https://github.com/apache/dolphinscheduler/releases/tag/1.3.6
The official documentation: https://dolphinscheduler.apache.org/en-us/docs/1.3.6/user_doc/kubernetes-deployment.html

**Comment by chengshiwen** [comment]
Close since it has been resolved
