### ISSUE TITLE
[Bug][SQL] The generated attachment suffix name is dat

### ISSUE THREAD

**Issue by syb853553110** [apache/dolphinscheduler#5411]
**Describe the bug**
The generated attachment suffix name is dat, which should be xls。
The format of the generated attachment name is "ATT_XXXX.dat". It is recommended to be configurable
创建的SQL任务生成的附件后缀名称为dat, 应该为xls，不然无法打开。
另外，生成的附件名称为"ATT_XXXX.dat", 建议附件名称可以通过UI界面修改

**Screenshots**
![image](https://user-images.githubusercontent.com/24668410/116679422-129bd080-a9dd-11eb-90e7-a5f8f4328747.png)
![image](https://user-images.githubusercontent.com/24668410/116679459-1e879280-a9dd-11eb-8065-c8d534710357.png)
![image](https://user-images.githubusercontent.com/24668410/116679506-2cd5ae80-a9dd-11eb-88e3-fec37344919d.png)

**Which version of Dolphin Scheduler:**
 -[1.3.6 Release]

**Comment by ruanwenjun** [comment]
What version are you using? This seems already been fixed.

**Comment by syb853553110** [comment]
> What version are you using? This seems already been fixed.

1.3.6 Release

**Comment by ruanwenjun** [comment]
@syb853553110 Are you sure it is 1.3.6-release? Is there a title in your input box? 
![image](https://user-images.githubusercontent.com/22415594/117251220-eff33700-ae76-11eb-8a8f-4d7f03cfd801.png)

I just test the 1.3.6-release, it can works well.

![image](https://user-images.githubusercontent.com/22415594/117251323-1022f600-ae77-11eb-8ae5-64375e3d3979.png)

**Comment by syb853553110** [comment]
@ruanwenjunAre you sure it is 1.3.6-release? Is there a title in your input box?
Yes, I'm sure.

![image](https://user-images.githubusercontent.com/24668410/119073845-8ea79800-ba20-11eb-8b33-baba74324d37.png)

**Comment by syb853553110** [comment]
![image](https://user-images.githubusercontent.com/24668410/119077898-bf3f0000-ba27-11eb-91c8-0df2747bdf08.png)

**Comment by syb853553110** [comment]
刚试了，主题用英文正常，中文不行

**Comment by syb853553110** [comment]
刚试了，主题用英文正常，中文太长不行，短一些可以

**Comment by syb853553110** [comment]
> @syb853553110 Are you sure it is 1.3.6-release? Is there a title in your input box?
> ![image](https://user-images.githubusercontent.com/22415594/117251220-eff33700-ae76-11eb-8a8f-4d7f03cfd801.png)
> 
> I just test the 1.3.6-release, it can works well.
> 
> ![image](https://user-images.githubusercontent.com/22415594/117251323-1022f600-ae77-11eb-8ae5-64375e3d3979.png)

I am sure

**Comment by syb853553110** [comment]
> What version are you using? This seems already been fixed.

The Chinese in the title cannot be too long，English is Ok.

In addition, it is recommended that the email body be made configurable。

邮件主题中的中文不能太长，大概五六个字就不行了，两三个汉字是正常的。
另外，邮件主题使用全英文，没有问题。

还有一个建议，邮件正文，希望也可以输入。

**Comment by caishunfeng** [comment]
Hi @syb853553110 this issue will be closed because no update for a long time. You can reopen it if need.
