### ISSUE TITLE
[Question] How to connect dolphinscheduler to minio

### ISSUE THREAD

**Issue by zainal-abidin-assegaf** [apache/dolphinscheduler#5416]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
How to connect dolphinscheduler to minio

**Which version of DolphinScheduler:**
1.3.6

**Additional context**
How to connect dolphinscheduler to minio

**Requirement or improvement**
How to connect dolphinscheduler to minio

Please help, thank you

**Comment by chengshiwen** [comment]
Please refer to FAQ and search minio
1.3.6 : https://dolphinscheduler.apache.org/en-us/docs/1.3.6/user_doc/docker-deployment.html

**Comment by chengshiwen** [comment]
Close since it has been resolved
