### ISSUE TITLE
[Feature][Worker] Add support for Ray

### ISSUE THREAD

**Issue by liuyihan** [apache/dolphinscheduler#5419]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/community/development/issue.html when describe an issue.*

**Describe the feature**
Will dolphinscheduler add support for [Ray](https://github.com/ray-project/ray)?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by davidzollo** [comment]
good idea,  Ray is also a good project!  I noticed Ray some time ago.

By the way , would you like to implement this Feature for supporting Ray?
