### ISSUE TITLE
[Bug][Master] execute ComplementProcess  exception

### ISSUE THREAD

**Issue by felix-thinkingdata** [apache/dolphinscheduler#5423]
![image](https://user-images.githubusercontent.com/59079269/117258521-a529ed00-ae7f-11eb-9088-4dab10081e91.png)
![image](https://user-images.githubusercontent.com/59079269/117258601-b70b9000-ae7f-11eb-9ec0-3864f35904b5.png)
This will cause the process definition to be empty，An error is reported later when the process definition is retrieved

**Comment by caishunfeng** [comment]
This issue had been fixed.
