### ISSUE TITLE
[Feature][Plugin-Email] Numeric data type support in email attachment

### ISSUE THREAD

**Issue by blacktea-latte** [apache/dolphinscheduler#5424]
Status Quo
Dolphinscheduler currently supports executing SQL and send result as email table/attachment, however the .xls attachment is forcing all columns to be "text" type and creates difficulty in data manipulation down the line (not sure this is a bug or expected behavior).

Suggestion
Hoping to see support for automatic data type in .xls, and/or additional support for other attachment format such as csv, txt or xlsx

**Comment by ruanwenjun** [comment]
@blacktea-latte At present, all data is formatted as string before being written in `xls`, I will try to submit a pr to solve the data type issue. `xlsx` will be supported in this pr #5400, and most excel tools have the function of converting to other formats such as `csv`, I am not sure if it is still necessary to provide `csv` format.

**Comment by blacktea-latte** [comment]
@ruanwenjun That would be so much appreciated! And yes, there's no obvious use cases for `csv` format, especially given that xlsx will be supported.
