### ISSUE TITLE
[Bug][K8s] Master and worker cannot get the right address with custom DNS in 1.3.6

### ISSUE THREAD

**Issue by cczz12345** [apache/dolphinscheduler#5431]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
(I found a bug when I test v1.3.6, which did not happen in v1.3.5.I need to used host network dns policy on k8s, so I add config in templates/statefulset-dolphinscheduler-worker.yaml)
我在测试刚发布的v1.3.6的时候，发现一个关于worker的命名的bug，在之前的1.3.5中并未出现。
起因：因为spark的一些特性，我需要在k8s的worker上使用本地网络，因此我在templates/statefulset-dolphinscheduler-worker.yaml添加了：
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
于是我发现1.3.6在worker中命名规则与1.3.5并不一致，可以看到1.3.5中：
(but I found there is a different behavior between 1.3.5 and 1.3.6, we can see in v1.3.5:)
![image](https://user-images.githubusercontent.com/4319851/117541498-be30ca80-b046-11eb-92d2-33bd254d9a79.png)
而在1.3.6中:
(but in v1.3.6:)
![image](https://user-images.githubusercontent.com/4319851/117541521-d7397b80-b046-11eb-87a0-90cd8a363edd.png)
可以看出1.3.6里worker的hostname把后面的.local截掉了。导致工作流运作起来的时候，master找不到对应的worker主机。
(we can see v1.3.6 the hostname of workers is cut, which makes the workflow doesn't work. because the Master can't find the correct worker dns address.)
![image](https://user-images.githubusercontent.com/4319851/117541685-870ee900-b047-11eb-80f3-e05a49ab19e0.png)

**Expected behavior**
roll back to v1.3.5，make full hostname of the worker。

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[v1.3.6]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by chengshiwen** [comment]
@cczz12345 Thanks for your feedback! This bug will be fixed in next release 1.3.7
