### ISSUE TITLE
[Question] How to use dolphinscheduler ??

### ISSUE THREAD

**Issue by zainal-abidin-assegaf** [apache/dolphinscheduler#5437]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
I can not find any good documentation how to use dolphinscheduler

**Which version of DolphinScheduler:**
 v1.3.6

**Additional context**
I can not find any good documentation how to use dolphinscheduler

**Requirement or improvement**
Can you please privide how to use dolphinscheduler, thank you.

**Comment by ruanwenjun** [comment]
@4ss3g4f I am not sure what your question is about, maybe you need to provide a more specific description.
For example, did you encounter any problems during deployment or use?

You can find more helpful documents on this website.https://dolphinscheduler.apache.org

**Comment by 4ss3g4f** [comment]
![image](https://user-images.githubusercontent.com/22811935/117734055-d8240600-b21c-11eb-9b7b-cd00de46e0e2.png)

**Comment by zainal-abidin-assegaf** [comment]
Our quistions:
- How to use dolphinscheduler to do ETL from postgres to apache HIVE ??
- is dolphinscheduler has prebuild driver for mysql,hive/impala,spark,clickhouse,oracle,sqlsever and DB2 ?? (or dolphinscheduler only has default postgres driver only)
- How to add driver for mysql,hive/impala,spark,clickhouse,oracle,sqlsever and DB2 in the docker image, if dolphinscheduler only provide postgres driver as default

Thank you

**Comment by chengshiwen** [comment]
@4ss3g4f 
For 1, I'm not sure.
For 2, it is sure that dolphinscheduler only has the default postgres driver.
For 3, you can refer to FAQ in https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/docker-deployment.html like How to support MySQL datasource in Datasource manage?

**Comment by chengshiwen** [comment]
Close since it has been replied
