### ISSUE TITLE
Can data transmission be carried out between nodes in the task flow?

### ISSUE THREAD

**Issue by ZhaoJianchangA** [apache/dolphinscheduler#5438]
有个应用场景，需要将上一个节点处理完成的数据，插入到数据库中，需要如何操作？

**Comment by davidzollo** [comment]
how many data do you need to sync?

**Comment by ZhaoJianchangA** [comment]
> how many data do you need to sync?

我想把流程中上一个节点产生的数据，比如通过读取文件，或者读取数据库获取到的数据，在下一个节点插入到指定的数据库中
