### ISSUE TITLE
[Feature][FileSystem] support Tencent COS in hadoopUtils

### ISSUE THREAD

**Issue by haydenzhourepo** [apache/dolphinscheduler#5439]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/community/development/issue.html when describe an issue.*

**Describe the feature**
Tencent's COS is widely used among China's cloud users, and Hadoop supports Tencent COS since 3.3.0.
some companies don't have Hadoop hdfs, so use cos or oss as alternate storage backend.
**Describe the solution you'd like**
add hadoop-cos  or upgrade hadoop version above 3.3.0

**Comment by davidzollo** [comment]
> *For better global communication, please give priority to using English description, thx! *
> 
> _Please review https://dolphinscheduler.apache.org/en-us/community/development/issue.html when describe an issue._
> 
> **Describe the feature**
> Tencent's COS is widely used among China's cloud users, and Hadoop supports Tencent COS since 3.3.0.
> some companies don't have Hadoop hdfs, so use cos or oss as alternate storage backend.
> **Describe the solution you'd like**
> add hadoop-cos or upgrade hadoop version above 3.3.0

considering many users don't use hadoop 3.3 for now, maybe add hadoop-cos jar will be better?

**Comment by haydenzhourepo** [comment]
ok, I'll submit a pr to add support cos

**Comment by Littlehhao** [comment]
请问支持cos了吗？

**Comment by kiwi-field** [comment]
支持了吗，兄弟
