### ISSUE TITLE
[Improvement][Maven] Project module maven dependency optimization

### ISSUE THREAD

**Issue by zhuangchong** [apache/dolphinscheduler#5440]
**Describe the question**
Currently, the dolphinscheduler project modules have api, server, service, alert, remote, dao, common, spi, alert-plugin, but there are redundant references for dependencies between projects.

**What are the current deficiencies and the benefits of improvement**
Project module maven dependency optimization

dependency relationship before：

![image](https://user-images.githubusercontent.com/37063904/117785447-2bc33d80-b277-11eb-9b53-44cef0d22855.png)

dependency relationship compared：(The red dotted line represents deletion)

![image](https://user-images.githubusercontent.com/37063904/117785774-7a70d780-b277-11eb-9037-83bc7f3b2c71.png)

dependency relationship after：

![image](https://user-images.githubusercontent.com/37063904/117786100-c15ecd00-b277-11eb-8157-5b1181fb049b.png)

**Which version of DolphinScheduler:**
 -[dev]

**Comment by CalvinKirs** [comment]
Sounds good, it would be better if it could provide a dependency relationship before and after.
