### ISSUE TITLE
In version 1.3.6, Kerbos-related errors were reported when MySQL queries were executed using SQL tasks

### ISSUE THREAD

**Issue by shiliquan** [apache/dolphinscheduler#5443]
1.3.6版本中通过sql任务去执行mysql查询时会报kerbos相关的错误，如下：
![image](https://user-images.githubusercontent.com/42087586/117772407-b866ff00-b269-11eb-8e3e-dc218b0b9bec.png)
![image](https://user-images.githubusercontent.com/42087586/117772476-cddc2900-b269-11eb-83fd-ef7bf045baa0.png)
请问下该怎么解决？谢谢！

**Comment by ruanwenjun** [comment]
@shiliquan It seems that you have set the Kerberos open. 
You can check if the config value of `hadoop.security.authentication.startup.state` is true. In this version,  if you open the Kerberos, ds will still load KerberosConf even if you just execute a mysql task.

And this problem has been fixed at pr #4593.

BTW, It is suggested you change the question to English.
