### ISSUE TITLE
[Bug][worker]  worker log stops scrolling

### ISSUE THREAD

**Issue by gaoyu2016** [apache/dolphinscheduler#5444]
worker log停止滚动。
Apr  3 10:18 dolphinscheduler-worker.2021-04-03_10.0.log
中间缺失。
May 10 18:43 dolphinscheduler-worker.log

**Comment by chengshiwen** [comment]
@gaoyu2016 Could you give us more information like ds version, deployment way?

**Comment by gaoyu2016** [comment]
ds-1.3.4

**Comment by gaoyu2016** [comment]
dolphinscheduler-logger-server-dx-pipe-sata663-pm.out日志提示：
10:04:11.207 [NettyServerWorkerThread_43] WARN org.apache.dolphinscheduler.remote.handler.NettyServerHandler - [id: 0xc7ee97cd, L:/10.11.56.141:50051 - R:/10.11.55.30:46713] is not writable, over high water level : 65536

**Comment by gaoyu2016** [comment]
先关了，重新建一个。

**Comment by chengshiwen** [comment]
Redirect #5585
