### ISSUE TITLE
[Question] In a shell script, use an existing data source

### ISSUE THREAD

**Issue by Sky-Gu** [apache/dolphinscheduler#5447]
**Describe the question**
The project is doing content migration, there are a large number of script files, these script files want to use the data source has added data source information, may I ask how to use the content.

项目中有不少的脚本文件，需要使用数据源的账号密码，如何在脚本中用通过参数的方式来使用数据源中的链接信息。

**Comment by felix-thinkingdata** [comment]
Can you give an example of a scenario you would like to use ？
