### ISSUE TITLE
[Question] Cann't get task instance log detail 

### ISSUE THREAD

**Issue by usretyn** [apache/dolphinscheduler#5451]
**Describe the question**
My cluster has 2 worker nodes named ds1,ds2.  
After run process, ds1 can get   the task instance log on UI ，but ds2 cann't get log detail  .
I queried the table t_ds_task_instance by the task instance id ,  the file  path to  field log_path  exists on the host . 

**Which version of DolphinScheduler:**
 -[1.3.6]

**Additional context**

**Comment by xingchun-chen** [comment]
Is the logger service started in ds2?

**Comment by usretyn** [comment]
The logger server is running on ds2  , listen port 50051

**Comment by wordhardqi** [comment]
@usretyn you can check that whether there is firewall or iptalbe rules to stop you accept the connection on 50051 on ds2.
you can check by this:
1. go the api server's machine
2. telnet ip_of_ds2 50051.
