### ISSUE TITLE
BindingException:Invalid bound statement(not found)

### ISSUE THREAD

**Issue by JunjianS** [apache/dolphinscheduler#5454]
version:1.3.2
I try to add a new mapper (sql),  get this exception when call the new api, but others is ok. i checked that interface method name is same as mapper id.
org.apache.ibatis.binding.BindingException:Invalid bound statement(not found)

**Comment by chengshiwen** [comment]
@JunjianS It's better to show all your changes about the new mapper

**Comment by JunjianS** [comment]
> @JunjianS It's better to show all your changes about the new mapper
@chengshiwen thanks for your reply.
I add a new method in ProcessDefinitionMapper.java, a select in ProcessDefinitionMapper.xml, and corresponding method in service and controller.

    @ApiOperation(value = "queryProcessDefinitionListByState", notes = "QUERY_PROCESS_DEFINITION_LIST_BY_STATE_NOTES")
    @GetMapping(value = "/list-state")
    @ResponseStatus(HttpStatus.OK)
    @ApiException(QUERY_PROCESS_DEFINITION_LIST)
    public Result queryProcessDefinitionListByState(@ApiIgnore @RequestAttribute(value = Constants.SESSION_USER) User loginUser,
                                                    @RequestParam("releaseState") Integer releaseState
    ) {
        logger.info("query process definition list by release state, login user:{}",
                loginUser.getUserName());
        Map<String, Object> result = processDefinitionService.queryProcessDefinitionListByState(releaseState);
        return returnDataList(result);
    }

    /**
     * list process definition by release state
     * @param releaseState release state
     * @return map
     */
    public Map<String, Object>  queryProcessDefinitionListByState(Integer releaseState){
        HashMap<String, Object> result = new HashMap<>(5);

        List<ProcessDefinition> processDefinitionList = processDefineMapper.queryDefinitionListByState(releaseState);
        result.put(Constants.DATA_LIST, processDefinitionList);
        putMsg(result, Status.SUCCESS);

        return result;
    }

    /**
     * list all process definition by release state
     * @param releaseState release state
     * @return process definition list
     */
    List<ProcessDefinition> queryDefinitionListByState(@Param("releaseState") int releaseState);

    <select id="queryDefinitionListByState" resultType="org.apache.dolphinscheduler.dao.entity.ProcessDefinition">
        select * from t_ds_process_definition where release_state = #{releaseState}
    </select>

**Comment by JunjianS** [comment]
> @JunjianS It's better to show all your changes about the new mapper

thanks for you reply, I found the cause of the problem. I made a mistake in config dir.
