### ISSUE TITLE
[Question] When using the Sqoop tool in the workflow, how to configure the Hive connection information when the Hive type is selected in the "Data Purpose"?

### ISSUE THREAD

**Issue by waconde** [apache/dolphinscheduler#5455]
版本信息：dolphinscheduler 1.3.6 release
问题说明：如图，拖入了 Sqoop 节点，配置“数据目的”时，选择“HIVE”，但没有看到如何配置 Hive 所在服务器的IP、端口等连接信息呀？是写在哪个配置文件里了么？
![微信图片_20210512174838](https://user-images.githubusercontent.com/28390161/117955641-d5273380-b34a-11eb-8046-2c20c06bde81.jpg)

**Comment by ruanwenjun** [comment]
@waconde You can try to configure in DataSource.
![image](https://user-images.githubusercontent.com/22415594/117996374-b047b600-b374-11eb-9c13-ee5d5fae0033.png)
