### ISSUE TITLE
[Question] When using the Sqoop tool in the workflow, can I only choose MySQL as the "data source"?

### ISSUE THREAD

**Issue by waconde** [apache/dolphinscheduler#5456]
版本信息：dolphinscheduler 1.3.6 release
问题说明：如图，拖入 Sqoop 节点后，“数据来源”只能选择 MySQL，可选项只有这一个值。是需要配置什么文件，才能选择其他数据库类型么？
![微信图片_20210512175602](https://user-images.githubusercontent.com/28390161/117956135-567ec600-b34b-11eb-8550-0bc81c1540d2.jpg)

**Comment by xingchun-chen** [comment]
Currently, sqoop only supports mysql.
If you have other needs, welcome to contribute pr

**Comment by waconde** [comment]
> Currently, sqoop only supports mysql.
> If you have other needs, welcome to contribute pr

OK...
