### ISSUE TITLE
[Bug][ui] 360 browser version 12.2.1172.0 chromium core version 78.0.3904.108 can't open dolphin ui

### ISSUE THREAD

**Issue by lishiyucn** [apache/dolphinscheduler#5457]
backgroud: dolphin1.3.1 upgrade to dolphin1.3.5
dolphinscheduler 1.3.5
360 browser version 12.2.1172.0 chromium core version 78.0.3904.108

open url http://ip:12345/dolphinscheduler/ui/#/home, all time show loading...

**Comment by chengshiwen** [comment]
Thanks for your feedback! The pr #4336 has tried to fix the browser compatibility on dev branch. We will try to test on the 360 browser you mentioned.

**Comment by chengshiwen** [comment]
The pr #4336 has fixed this issue so close
