### ISSUE TITLE
EasyScheduler supports LDAP authentication, and Hive supports LDAP authentication.(EasyScheduler支持LDAP认证， Hive等连接支持LDAP认证)

### ISSUE THREAD

**Issue by meijies** [apache/dolphinscheduler#546]
- EasyScheduler supports LDAP authentication
- Hive and other connections support LDAP authentication
- Support for Group Mapping via LDAP

---
- EasyScheduler支持LDAP认证
- Hive等连接支持LDAP认证
- 支持通过LDAP做Group Mapping

**Comment by boandai** [comment]
good idea！thx！

and welcome to sumit pull request to implement these features!

**Comment by xuzong** [comment]
增加基于消息驱动的流程调度模式

**Comment by lynchlee** [comment]
+1 mark

**Comment by lianayu** [comment]
+1

**Comment by elonlo** [comment]
+1

**Comment by silvermissile** [comment]
ladp is deeply depended in my bigdata ecosystem

**Comment by elonlo** [comment]
I will implement ldap login authentication later

**Comment by ARunningPig** [comment]
> later
Hi, how is it going?

**Comment by ARunningPig** [comment]
> I will implement ldap login authentication later

Hi, how is it going?

**Comment by elonlo** [comment]
> > I will implement ldap login authentication later
> 
> Hi, how is it going?

sorry，I gave up.....

**Comment by kocham** [comment]
这个需求2年了，还没考虑支持啊，LDAP在大数据验证领域用的还是非常广泛的，大部分组件都支持，感觉还挺重要的

**Comment by kocham** [comment]
this issue is closed  in #3743

**Comment by HwiLu** [comment]
> > > I will implement ldap login authentication later
> > 
> > 
> > Hi, how is it going?
> 
> sorry，I gave up.....

haha, me too
