### ISSUE TITLE
The shell execution is successful, and the status shows failed

### ISSUE THREAD

**Issue by kayJiang** [apache/dolphinscheduler#5460]
![image](https://user-images.githubusercontent.com/10612212/117963282-be84da80-b352-11eb-96fe-cb910a9a328e.png)

shell 日志

![image](https://user-images.githubusercontent.com/10612212/117963326-d0667d80-b352-11eb-9abe-278cdd0a5c43.png)

实际已经执行成功了

但是状态一直显示失败

![image](https://user-images.githubusercontent.com/10612212/117963442-f8ee7780-b352-11eb-95e3-1f01fcdf29a2.png)

**Comment by zhuangchong** [comment]
Which version? Can you provide more logs to analyze this problem?

**Comment by kayJiang** [comment]
> Which version? Can you provide more logs to analyze this problem?

![image](https://user-images.githubusercontent.com/10612212/118067380-03505600-b3d3-11eb-96af-fa0097dd1c4d.png)

compete,  but state is failure

**Comment by zhuangchong** [comment]
@kayJiang 
Please send me the context of the worker-server log here.

**Comment by ruanwenjun** [comment]
@kayJiang I think you may misunderstand the meaning of `complete` status, this status just mean the task is complete, but not necessarily success.
BYW, the above two logs do not seem to be the same task instance.

**Comment by kayJiang** [comment]
> @kayJiang
> Please send me the context of the worker-server log here.

org.apache.dolphinscheduler.common.utils.HttpUtils:[70] - http get:404 response

**Comment by kayJiang** [comment]
> Which version? Can you provide more logs to analyze this problem?

org.apache.dolphinscheduler.common.utils.HttpUtils:[70] - http get:404 response

yarn log copy to historyjob

**Comment by kayJiang** [comment]
[INFO] 2021-05-17 20:02:05.797 org.apache.dolphinscheduler.common.utils.HadoopUtils:[206] - application url : http://****/ws/v1/cluster/apps/%s
[ERROR] 2021-05-17 20:02:05.800 org.apache.dolphinscheduler.common.utils.HttpUtils:[70] - http get:404 response status code is not 200!

**Comment by zhuangchong** [comment]
@kayJiang 
Looking at your feedback, it is that the yarn api is called to check the task status. The http request is abnormal, and your task does not execute the yarn task. This is very strange. Is it convenient to send the overall worker-log?

**Comment by sqxinquan** [comment]
If the request is returned, the task status is not obtained on yarn.

**Comment by kayJiang** [comment]
您好，邮件已经收到。

**Comment by kayJiang** [comment]
您好，邮件已经收到。
