### ISSUE TITLE
[Improvement][Shell] kill shell command when using shell to run flume would cause flume exit not gracefully

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#5466]
/usr/local/service/flume/bin/flume-ng agent -c /usr/local/service/flume/conf/ -f /data/dolphinscheduler/data/hadoop/resources/appsflyer/appsflyer_flume.properties -n agent -Dflume.root.logger=INFO,console

![image](https://user-images.githubusercontent.com/17822915/118210194-b46ef300-b49c-11eb-9355-80c3242a370a.png)

Start the Flume agent with above shell command. After it has written a few files to HDFS, kill it using webui kill command. Check the hdfs dir. There will be a .tmp file. If we restart the Flume agent, it will resume writing data to HDFS, but it will not close/cleanup the .tmp file.

I think the correct scenario is that use kill -15 instead of of kill -9, so that flume agent can exit gracefully and it can perform these tasks before stopping the agent.

**Which version of DolphinScheduler:**
 -[1.3.6]

**Comment by ruanwenjun** [comment]
I think it would be better to provide the two-way, let users choose the kill way when they need to stop the workflow. Because sometimes we need force kill.
