### ISSUE TITLE
[Improvement][Task] Improved shell task execution result log information

### ISSUE THREAD

**Issue by zhuangchong** [apache/dolphinscheduler#5469]
**Describe the question**
Improved shell task execution result log information, adding process.waitFor() and process.exitValue() information to the original log

```
 logger.info("process has exited, execute path:{}, processId:{} ,exitStatusCode:{}",
            taskExecutionContext.getExecutePath(), processId, result.getExitStatusCode());
```

```
logger.error("process has failure , exitStatusCode : {} , ready to kill ...", result.getExitStatusCode());
```

**Which version of DolphinScheduler:**
 -[dev]

easy to improvement

#4124

**Comment by ji04xiaogang** [comment]
I would like to contribute to this.
