### ISSUE TITLE
[Feature][kubernetes] support ds HA by k8s configMap 

### ISSUE THREAD

**Issue by haydenzhourepo** [apache/dolphinscheduler#5479]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/community/development/issue.html when describe an issue.*

**Describe the feature**
DS has a Zookeeper HA service currently, but managing a Zookeeper cluster on Kubernetes for HA would require an additional operational cost that will increase the complexity of deployment。 for Kubernetes， it provides ConfigMap for leader election native. so we can remove the Zookeeper cluster in Kubernetes deployment mode。

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
use ConfigMap for leader election and configuration storage in DS Kubernetes native mode。

**Comment by davidzollo** [comment]
@chengshiwen What do you think ?

**Comment by chengshiwen** [comment]
> @chengshiwen What do you think ?

@dailidong @haydenzhourepo I will consider this feature and give its feasibility after the docker&k8s Improvement round 2

**Comment by davidzollo** [comment]
good job

Best Regards
---------------
DolphinScheduler PMC
Lidong Dai
***@***.***
---------------
