### ISSUE TITLE
[Bug][server] The master suddenly hangs but no error is found in the log

### ISSUE THREAD

**Issue by didiaode18** [apache/dolphinscheduler#5481]
**Describe the bug**
The master suddenly hangs but no error is found in the log,After restarting the master, the task can be run again, and the master will stop again after a while.

**To Reproduce**
Always exist

**Expected behavior**
master don't hang up
**Screenshots**
<img width="845" alt="微信图片_20210517124319" src="https://user-images.githubusercontent.com/22792154/118434349-79c0c100-b70f-11eb-9608-53f68fa26804.png">
<img width="956" alt="微信图片_20210517125027" src="https://user-images.githubusercontent.com/22792154/118434364-83e2bf80-b70f-11eb-8eef-ee4ce57d09e9.png">
<img width="624" alt="微信图片_20210517125117" src="https://user-images.githubusercontent.com/22792154/118434369-86ddb000-b70f-11eb-9b46-c73df4fd79e0.png">
<img width="928" alt="微信图片_20210517125059" src="https://user-images.githubusercontent.com/22792154/118434370-88a77380-b70f-11eb-9c85-23916a591efe.png">

**Which version of Dolphin Scheduler:**
 -[1.3.4]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by didiaode18** [comment]
Only the worker will have an error record
![image](https://user-images.githubusercontent.com/22792154/118434836-577b7300-b710-11eb-8cee-64a58bc25f1d.png)

**Comment by didiaode18** [comment]
I use the container as a physical host

**Comment by chengshiwen** [comment]
@didiaode18 How did you deploy it? And how to reproduce this issue?

**Comment by didiaode18** [comment]
I deployed through a single machine. The scheduler was running steadily before. I don’t know when the master stopped. The problem cannot be reproduced at present.

**Comment by didiaode18** [comment]
![Uploading image.png…]()

**Comment by didiaode18** [comment]
After restarting all services, the scheduling has been normal for the past few days. It is a magical error.
