### ISSUE TITLE
[Improvement][monitor]job monitoring

### ISSUE THREAD

**Issue by mengfeiMonica** [apache/dolphinscheduler#5485]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/community/development/issue.html when describe an issue.*

**Describe the question**

**What are the current deficiencies and the benefits of improvement**
- 新增任务时长top10
- 新增任务执行状态走势图

**Which version of DolphinScheduler:**
 -[1.3.6]

**Comment by Tandoy** [comment]
I will try to achieve it.
