### ISSUE TITLE
[Bug][api] Querying the task Gantt chart,we  find isoStart is greater than  isoEnd

### ISSUE THREAD

**Issue by guofeijia** [apache/dolphinscheduler#5489]
在master分支中，查看taskinstance甘特图时，发现某些taskinstance无法渲染，
![image](https://user-images.githubusercontent.com/13915251/118485533-23717380-b74b-11eb-9d0b-328f3414424f.png)
查询后台数据发现此时isoEnd小于isoStart，而数据库的start_time为null
查看后台代码发现当start_time为null时，会默认赋值为当前时间
![image](https://user-images.githubusercontent.com/13915251/118485891-8bc05500-b74b-11eb-9ea0-b0ec50a10514.png)

**Comment by zhuangchong** [comment]
In what scenario is the startTime parameter null?

**Comment by guofeijia** [comment]
> In what scenario is the startTime parameter null?

是的

**Comment by zhuangchong** [comment]
@guofeijia 

In what scenario is the startTime parameter null?

---
在哪种情况下，startTime参数值是null?

**Comment by guofeijia** [comment]
> In what scenario is the startTime parameter null?



> @guofeijia
> 
> In what scenario is the startTime parameter null?
> 
> 在哪种情况下，startTime参数值是null?

出现null的情况，暂时还没有找到原因

**Comment by caishunfeng** [comment]
This issue will be closed because no update for a long time. You can reopen it if need.
