### ISSUE TITLE
[Improvement][UE] Improve the user experience of high-frequency problems, especially for new users

### ISSUE THREAD

**Issue by chengshiwen** [apache/dolphinscheduler#5494]
**Describe the question**

When users deploy DolphinScheduler, especially new users, they will always encounter some common high-frequency problems. They bring a very bad user experience to users. At the same time, we will also spend a lot of time explaining the answers. These issues are as follows:

- [ ] Tenant not exists when uploading resources
- [ ] Home environment variable problem like `/opt/soft/python: command not found`, more details please refer to #5035
- [ ] Default useless `resource.storage.type=NONE` in the `common.properties` file causes the HDFS to be inaccessible #5600
- [ ] Local file system and S3a like MinIO configuration problem in the `common.properties` file for resource storage
- [ ] YARN configuration problem in the `common.properties` file causes the task status to be out of sync
- [ ] HDFS/YARN high availability configuration problem in the `common.properties` file
- [ ] Alert mail configuration problem in `alert.properties` lacks of quick verification method
- [ ] Lack user guide for beginner in UI to guide users to click on a several pre-set steps to learn the quick use of DolphinScheduler

**What are the current deficiencies and the benefits of improvement**

- Improve the user experience of high-frequency problems, especially for new users
- Increase ease of use and reduce interpretation costs

**Which version of DolphinScheduler:**
 -[1.3.x]
 -[dev]

**Comment by caoping6** [comment]
Verify that the tenant option is better when it's online or saved than when it's running. What do you think？

**Comment by 597365581** [comment]
In the workflow definition list, add a shortcut button, and you can jump directly to the specified workflow instance with one click. When you jump, you can take the workflow name as the search criteria to automatically query the specified list

**Comment by 597365581** [comment]
In the workflow instance list, add a shortcut button, and click to jump directly to the task instance list under the specified workflow instance. When you jump, you can automatically query the specified list with the name or ID of the workflow instance as the search criteria在工作流实例列表中，增加快捷按钮，点击一下就能直接跳转到指定的工作流实例下的任务实例列表中，跳转时，能带上工作流实例名称或者id作为搜索条件自动查询出指定的列表

**Comment by 597365581** [comment]
The user search input box (such as user name) is added to the front page of the project to query the running statistics of their own users项目首页增加用户搜索输入框（比如输入用户名），可以查询自己用户的运行统计数据

**Comment by 597365581** [comment]
In the task dependency view page, add a shortcut button to jump to the dependent workflow instance page and task instance page, which is convenient to click to view the operation of the dependent task.任务依赖查看页面中，增加快捷按钮，可以跳转到依赖的工作流实例页面和任务实例页面，方便点击查看被依赖的任务的运行情况。

**Comment by 597365581** [comment]
In the workflow definition page, you can retrieve the workflow according to its online status and scheduled online status.工作流定义页面中，可以按照工作流上线状态和定时上线状态进行检索。

**Comment by 597365581** [comment]
complement：

1、In the workflow definition list, add a shortcut button, and you can jump directly to the specified workflow instance with one click. When you jump, you can take the workflow name as the search criteria to automatically query the specified list

2、In the workflow instance list, add a shortcut button, and click to jump directly to the task instance list under the specified workflow instance. When you jump, you can automatically query the specified list with the name or ID of the workflow instance as the search criteria
3、The user search input box (such as user name) is added to the front page of the project to query the running statistics of their own users
4、In the task dependency view page, add a shortcut button to jump to the dependent workflow instance page and task instance page, which is convenient to click to view the operation of the dependent task.
5、In the workflow definition page, you can retrieve the workflow according to its online status and scheduled online status.

---
1、在工作流定义列表中上，增加快捷按钮，点击一下就能直接跳转到指定的工作流实例下，跳转时，能带上工作流名称作为搜索条件自动查询出指定的列表
2、在工作流实例列表中，增加快捷按钮，点击一下就能直接跳转到指定的工作流实例下的任务实例列表中，跳转时，能带上工作流实例名称或者id作为搜索条件自动查询出指定的列表
3、项目首页增加用户搜索输入框（比如输入用户名），可以查询自己用户的运行统计数据
4、任务依赖查看页面中，增加快捷按钮，可以跳转到依赖的工作流实例页面和任务实例页面，方便点击查看被依赖的任务的运行情况。
5、工作流定义页面中，可以按照工作流上线状态和定时上线状态进行检索。

**Comment by BoYiZhang** [comment]
Yarn gets the task status through the URL. If Kerberos is enabled, the URL needs to support Kerberos
-------------------
Yarn 通过 的url 获取任务状态 , 如果开启Kerberos , 该url需要支持kerberos

**Comment by BoYiZhang** [comment]
restful api 支持SDK, 通过引用封装好的SDK,就可以远程操作DS[创建,执行工作流等操作.]
-------------
Restful API supports SDK. By referring to the encapsulated SDK, you can remotely operate DS [create, execute workflow, etc.]

**Comment by BoYiZhang** [comment]
1. Shut down the cluster gracefully #5470
2. Task execution is completed / hung up, resulting in the task instance or task state being executed all the time (1.3.6 fixed?)
3. Yarn gets the task status through the URL. If Kerberos is enabled, the URL needs to support Kerberos
4. The alarm plug-in of dev branch needs to have an instruction. At present, there is only  (informal version)[https://note.youdao.com/ynoteshare1/index.html?id=e40e83a50bf338500872aedeb7ebfa4d&type=note]
5. The date function of complement function is ambiguous, which requires a document or optimization
6. Restful API supports SDK. By referring to the encapsulated SDK, you can remotely operate DS [create, execute workflow, etc.]
7. DataX visualization function extension. Support hive/ HDFS ha visualization configuration
-----------------
1. 优雅的停止服务,以便于升级获取停止服务 #5470
2. 任务执行完成/挂掉, 导致任务实例或者任务状态一直处于执行中(1.3.6已经修复 ?)
3. Yarn 通过 的url 获取任务状态 , 如果开启Kerberos , 该url需要支持kerberos
4. Dev分支的告警插件需要有一份使用说明.目前只有 (非正式版本)[https://note.youdao.com/ynoteshare1/index.html?id=e40e83a50bf338500872aedeb7ebfa4d&type=note]
5. 补数功能的日期函数有歧义,这个需要出一份文档或者进行优化
6. Restful api 支持SDK, 项目通过引用封装好的jar包,就可以远程操作DS[创建,执行工作流等操作.]
7. DataX可视化功能扩展. 支持Hive/ hdfs HA 可视化配置.

**Comment by wenyuanLv** [comment]
Click on the histogram of the process definition statistics on the homepage or other places, can you view all the timed tasks currently online or created by the user?
There are more tasks afterwards, and I don't pay attention to which timed tasks I have started, and I need to check them one by one.
azkaban seems to have a similar page, I think this user experience is pretty good

---

在首页流程定义统计的柱状图 或者 其他地方点进去，能否查看用户当前 上线或者创建的所有定时任务啊。
不然后续任务多起来了，都没注意自己起了哪些定时任务，需要一个一个区查看。
azkaban好像有类似的页面，我觉得这个用户体验蛮好的

**Comment by zhangb0120** [comment]
process instance serialization
流程串行，不知道有没有那个大神实现了，这个版本能加上去吗

**Comment by chengshiwen** [comment]
> process instance serialization
> 流程串行，不知道有没有那个大神实现了，这个版本能加上去吗

There are plans for serial tasks, but the amount of changes is large, and the recent version will not be released yet

**Comment by davidzollo** [comment]
Great job!
