### ISSUE TITLE
[Improvement][Worker] Simplify the delivery of AlertClientService object and support multiple alert server

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#5538]
**Describe the question**
This issue want to talk about two things:

1. We don't need to transport the `AlertClientService` by parameter, only `SqlTask` need to send result by `AlertClientService`. We can register the `AlertClientService` to Spring container like other object.

https://github.com/apache/dolphinscheduler/blob/8a1d849701671544327a1d4e7852575af6872017/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/runner/TaskExecuteThread.java#L108-L110
https://github.com/apache/dolphinscheduler/blob/8a1d849701671544327a1d4e7852575af6872017/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/TaskManager.java#L47
https://github.com/apache/dolphinscheduler/blob/8a1d849701671544327a1d4e7852575af6872017/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/TaskManager.java#L60
https://github.com/apache/dolphinscheduler/blob/8a1d849701671544327a1d4e7852575af6872017/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java#L97-L110

2. Currently, the worker only supports to config one address of `AlertServer`, in the production environment, we may start multiple `AlertServer`, although we can set up a gateway on `AlertServer`, but can we have a better way?  Such as store the total addresses of `AlertServer` in worker, and use round-robin to select.

**Which version of DolphinScheduler:**
 -[dev]

**Comment by CalvinKirs** [comment]
This is just a simple implementation, we considered accessing the registry before. But due to time reasons, it is not completed, you can look the previous issue.
