### ISSUE TITLE
[Improvement][Master] Check status of taskInstance from cache

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#5539]
**Describe the question**
After the master submit a task, the master will wait for the task execution to end, and it will loop to query the task status from database.
https://github.com/apache/dolphinscheduler/blob/8a1d849701671544327a1d4e7852575af6872017/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterTaskExecThread.java#L123-L164

Why doesn't it query the status from the taskInstanceCacheManager？
When the master receive the response from worker, it will also update the cache.

https://github.com/apache/dolphinscheduler/blob/8a1d849701671544327a1d4e7852575af6872017/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/processor/TaskResponseProcessor.java#L68-L87

I think if we query the status from cache, we can reduce the pressure of the database.
The main risk is that after the worker crashed, we need to send a response to the master when doing worker tolerance.
So as a compromise, can we query the cache 9 times and then query the database once? Or we get task status from cache, and the cache query the task status from database periodically(the schedule interval can be longer).

**Which version of DolphinScheduler:**
 -[dev]

**Comment by CalvinKirs** [comment]
I agree with you, usually, the cache has been able to obtain data to a large extent, so we will reduce a large number of DB queries.

**Comment by blackberrier** [comment]
@CalvinKirs Can I try to make this improvement? First time to claim issue here, getting bit of nervous, hah :)
My idea is as follows:
In `MasterTaskExecThread.java` just get status from `taskInstanceCacheManager`.
In case of worker failure and doing worker tolerance, `ZKMasterClient.java` # `failoverWorker()` method set task status to `ExecutionStatus.NEED_FAULT_TOLERANCE`, and then send `CommandType.TASK_EXECUTE_RESPONSE` command containing the newest task status to master . After master process the command , `MasterTaskExecThread.java` can handle task state rightly. 
Maybe my thought is naive, looking forward to your correction.

**Comment by ruanwenjun** [comment]
@blackberrier Hi, I get you point. 
In your plan, there might be one thing need to consider, when a master do worker tolerance, if it cannot connect to the master that is executing this worker, how to handle this situation. 
There may two possible reason for this case:
1. They may be deployed in different network centers, in the current architecture we don't require the masters to be able to communicate with each other.
2. The Master1 is crashed too.
![image](https://user-images.githubusercontent.com/22415594/120090088-67dd1600-c132-11eb-9f40-b195e3b1d17f.png)

If you want to modify the worker tolerance, it may be complicated.
I think in this case, you can schedule a time rotation in the cache to query `ExecutionStatus.NEED_FAULT_TOLERANCE ` tasks from database and replace the cache.
What do you think?

**Comment by blackberrier** [comment]
@ruanwenjun 
Hi, the diagram is great, and I get the point.
It seems that we have to compromise on period of getting the right task status if we want to reduce the access to database.
Then, maybe the possible way is just as you said, In `MasterTaskExecThread.java` get status from `taskInstanceCacheManager` 9 times and then query database using `processService.findTaskInstanceById(taskInstance.getId())` 1 time. That is query database once every about 10 second?
Is this method ok?

**Comment by ruanwenjun** [comment]
> @ruanwenjun
> Hi, the diagram is great, and I get the point.
> It seems that we have to compromise on period of getting the right task status if we want to reduce the access to database.
> Then, maybe the possible way is just as you said, In `MasterTaskExecThread.java` get status from `taskInstanceCacheManager` 9 times and then query database using `processService.findTaskInstanceById(taskInstance.getId())` 1 time. That is query database once every about 10 second?
> Is this method ok?

I think in `MasterTaskExecThread ` you can get status from `taskInstanceCacheManager ` directly, and in `taskInstanceCacheManager ` schedule a timing thread to query `NEED_FAULT_TOLERANCE ` task from the database and update the cache, this might be better, the `taskInstanceCacheManager` can be used by many components.

The interval of querying `NEED_FAULT_TOLERANCE` task from database can be longer, for example, 10 seconds or longer?

**Comment by blackberrier** [comment]
> > @ruanwenjun
> > Hi, the diagram is great, and I get the point.
> > It seems that we have to compromise on period of getting the right task status if we want to reduce the access to database.
> > Then, maybe the possible way is just as you said, In `MasterTaskExecThread.java` get status from `taskInstanceCacheManager` 9 times and then query database using `processService.findTaskInstanceById(taskInstance.getId())` 1 time. That is query database once every about 10 second?
> > Is this method ok?
> 
> I think in `MasterTaskExecThread ` you can get status from `taskInstanceCacheManager ` directly, and in `taskInstanceCacheManager ` schedule a timing thread to query `NEED_FAULT_TOLERANCE ` task from the database and update the cache, this might be better, the `taskInstanceCacheManager` can be used by many components.
> 
> The interval of querying `NEED_FAULT_TOLERANCE` task from database can be longer, for example, 10 seconds or longer?

ok, I'd like to accomplish this improvement in this way.

**Comment by ruanwenjun** [comment]
@blackberrier Looking forward to your pr. 
And one additional thing you may need to be considered here is that there are no indexes of `state`  in the `t_ds_task_instance` table. If you want to filter by state it may scan the whole table, which can be very slow, and I think you can just query the task existing in cache by id 😄
