### ISSUE TITLE
[Bug][JSON Split] Project created failure and unknown column p.code in field list

### ISSUE THREAD

**Issue by chengshiwen** [apache/dolphinscheduler#5540]
**To Reproduce**

Refer to https://dolphinscheduler.apache.org/zh-cn/development/development-environment-setup.html
And run `org.apache.dolphinscheduler.dao.upgrade.shell.CreateDolphinScheduler`

**Expected behavior**
Bug fixed

**Screenshots**

![image](https://user-images.githubusercontent.com/4902714/119256897-76d53d00-bbf5-11eb-9a1e-aa82c3948d2e.png)
![image](https://user-images.githubusercontent.com/4902714/119256898-79d02d80-bbf5-11eb-99ae-08cf47a95976.png)

**Which version of Dolphin Scheduler:**
 -[dev]

@JinyLeeChina

**Comment by brave-lee** [comment]
Thank you for your feedback, I checked the code and found no problems，please make sure your database is latest tables

**Comment by gk0916** [comment]
I have the same problem. I think there are loss some ddl in sql/1.4.0_schema/mysql and postgresql when update to version 1.4.0
