### ISSUE TITLE
[Improvement][Project]  Project Permission control

### ISSUE THREAD

**Issue by kocham** [apache/dolphinscheduler#5542]
Project Permission control  seems too simple，sugguesting to consider the way azkaban do, eg:
if i create a project ,i can authorizate it to any members, not only admin can do this.
admin user can be any members, not only the "amdin" user

**Comment by CalvinKirs** [comment]
Sounds good, is there a specific design?

**Comment by Squidyu** [comment]
> Sounds good, is there a specific design?

Remove the "isAdmin" of authorization verification, and be more rigorous. You need to add a lot of operation logs
