### ISSUE TITLE
[Feature][api] Quoting the queue list of yarn

### ISSUE THREAD

**Issue by muzhongjiang** [apache/dolphinscheduler#5545]
[Feature][api] Quoting the queue list of yarn
**Quoting the queue list of yarn**
1、Get the yarn queue list through the api
2、Specify yarn queue for these components when creating a new workflow: hive, MapReduce, spark, flink

As shown：
![image](https://user-images.githubusercontent.com/7700151/119459481-4bc32880-bd70-11eb-8497-9b5120c9e53a.png)

**Comment by CalvinKirs** [comment]
Sounds good, We will complete this function when doing the Task plug-in. BTW, are you interested in joining in and contributing together?

**Comment by muzhongjiang** [comment]
> Sounds good, We will complete this function when doing the Task plug-in. BTW, are you interested in joining in and contributing together?

Of course, but I can only complete back - end code
