### ISSUE TITLE
[Improvement][Api] Adding transaction when update process definition

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#5546]
**Describe the question**
When we update a process definition, we need to perform multiple DML operations, it is needed to add transaction to ensure the data is consistent when an exception occurs.
https://github.com/apache/dolphinscheduler/blob/842c5400e605a8b8eb0d8fdc78701f10222063fd/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java#L375

https://github.com/apache/dolphinscheduler/blob/842c5400e605a8b8eb0d8fdc78701f10222063fd/dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java#L2228

There are also some other method need to check, such as:
https://github.com/apache/dolphinscheduler/blob/842c5400e605a8b8eb0d8fdc78701f10222063fd/dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java#L2367

https://github.com/apache/dolphinscheduler/blob/842c5400e605a8b8eb0d8fdc78701f10222063fd/dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java#L2376

**Which version of DolphinScheduler:**
 -[dev]

**Describe alternatives you've considered**
Add transaction, and it is recommended to split ProcessService into CommandService、ProcessDefinitionService、ProcessInstanceService、TaskService

**Comment by ji04xiaogang** [comment]
I would like to contribute to this.

**Comment by HomminLee** [comment]
I want to take this issue.

**Comment by brave-lee** [comment]
@ruanwenjun    Please confirm that the current interface already supports transactions

**Comment by HomminLee** [comment]
@ruanwenjun  I have a question. Class ProcessService exists in project [dolphinscheduler-service], and there are already exists ProcessDefinitionService、ProcessInstanceService、TaskInstanceService in project [dolphinscheduler-api]. In my previous thoughts, I want split ProcessService to those service class. But I found ProcessService also be used by project [dolphinscheduler-server]. If I follow the previous ideas to complete, the project [dolphinscheduler-api] cannot use those service, this is unacceptable.
So, do you have any suggestions? Should I just create 4 new class in project [dolphinscheduler-service]  with  other names?

**Comment by ruanwenjun** [comment]
@HomminLee You can create a new issue to track your idea.
