### ISSUE TITLE
The flink job is running on yarn, but failed on DS

### ISSUE THREAD

**Issue by Dipsy-chen** [apache/dolphinscheduler#5548]
When I start  a  flink job on DS,  the task always  fail in a few seconds ,however   It's still running on yarn.
Why?  

![image](https://user-images.githubusercontent.com/38179695/119596021-102c6b00-be11-11eb-8d13-cd3578a8bf46.png)

![image](https://user-images.githubusercontent.com/38179695/119595988-030f7c00-be11-11eb-947f-20f9baed074b.png)

**Comment by ruanwenjun** [comment]
@Dipsy-chen Which version? dev branch?

**Comment by Dipsy-chen** [comment]
> @Dipsy-chen Which version? dev branch?

V1.3.4  .

**Comment by Dipsy-chen** [comment]
I get it.  DS  "yarnHaIps"  parame  is invalid ,because my yarn HA Backup master node  was down . 
 After configuring the "singleYarnIp" parameter, DS return to normal
