### ISSUE TITLE
[Bug][WorkerServer] SqlTask NullPointerException

### ISSUE THREAD

**Issue by wen-hemin** [apache/dolphinscheduler#5549]
**Describe the bug**

The "printReplacedSql" method, before sqlParamsMap iterates, check null,
and sqlParamsMap.get(i) check null.

**Expected behavior**
When sqlParamsMap is null, no NullPointerException should be thrown.

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by didiaode18** [comment]
I will fix it

**Comment by CalvinKirs** [comment]
close by #5549
