### ISSUE TITLE
Front-end interaction: workflow task configuration is complete, it is recommended to do page jump(前端交互：工作流任务配置完成，建议做页面跳转)

### ISSUE THREAD

**Issue by xubin8558** [apache/dolphinscheduler#555]
On the workflow task configuration page, it is recommended to add a save and exit button, or automatically jump to the workflow list page, now every time you save it, still in the task modification interface, you have to manually click back to the workflow page, operation Don't worry about it

---
在工作流任务配置页面，建议再加一个保存并退出按钮，或者自动跳转到工作流列表页面，现在是每次保存完了，还在任务修改界面，还得手动点击回到工作流页面， 操作上别扭麻烦

**Comment by boandai** [comment]
very good idea!  thx!
