### ISSUE TITLE
[wroker tolerance] master can't kill yarn job

### ISSUE THREAD

**Issue by geosmart** [apache/dolphinscheduler#5550]
when worker is down, a master trigger worker tolerance,
when handle a yarn task tolerance, it first kill the yarn job by yarn rest api and make the task state to NEED_FAULT_TOLERANCE,
so the task can scheduler by master.

but now when kill the yarn job , the master build a taskExecutionContext and check the `executePath`.
but in my debug session, the `executePath` is always null ,and the yarn job just can't kill 

the code in 
https://github.com/apache/dolphinscheduler/blob/842c5400e605a8b8eb0d8fdc78701f10222063fd/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ProcessUtils.java#L454

**Comment by geosmart** [comment]
just wan't to know why we have to check the `executePath` not null?

**Comment by chengshiwen** [comment]
Close by #5552
