### ISSUE TITLE
[Feature][YARN] different job uses different yarn-cluster

### ISSUE THREAD

**Issue by bo8888** [apache/dolphinscheduler#5560]
i want config two yarn-cluster, a job use yarn-cluster at USA run the flink pre-job,b job use yarn-cluster at CHINA run the flink pre-job,use a same hdfs

**Comment by Squidyu** [comment]
Can you solve your problem by deploying two jobs to different yarn clusters, grouping workers according to yarn clusters, and assigning different tasks to different workers groups
