### ISSUE TITLE
[Improvement][Worker] Do not verify the status of yarn in ShellCommandExecutor

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#5564]
**Describe the question**
Currently, there are multiple task use `ShellCommandExecutor` to run task, such as `DataxTask`、`ShellTask`、`FlinkTask`, `SparkTask` etc. 

In the `ShellCommandExecutor`, after executing the task, it will query the task status from yarn(if it can find applicationId from log),  and check the status. It is not reasonable, sometimes this will cause task failure.
https://github.com/apache/dolphinscheduler/blob/f8ecb536b71d6f33b71c73930832b62890b84ea1/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java#L214-L224

We should move the check logic to `AbstractYarnTask`.

BYW, use `ExecutionStatus.FAILURE.equals(applicationStatus)` to avoid NPE.
https://github.com/apache/dolphinscheduler/blob/f8ecb536b71d6f33b71c73930832b62890b84ea1/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java#L415-L420

**Which version of DolphinScheduler:**
 -[1.3.6]
 -[dev]

**Comment by kevinjmh** [comment]
FYI:
PR #5996  already removed the yarn state check;
If stop a task, application id will be obtained from log and killed.

**Comment by ruanwenjun** [comment]
> FYI: PR #5996 already removed the yarn state check; If stop a task, application id will be obtained from log and killed.

OK
