### ISSUE TITLE
[Feature][Master Worker-Server] Global Param passed by sense dependencies

### ISSUE THREAD

**Issue by wangxj3** [apache/dolphinscheduler#5565]
the param of task requires optimization,Need according to the dependency relationship between the nodes pass a variable's value, different depend on the chain of nodes before there is the same but different meanings, parameters can be distinguished from processInstance. GlobalParam, taskInstance. LocalParam

**Comment by ruanwenjun** [comment]
1. Can we determine the value of param1 in Task2's varpool ? It may come from Task1 or generate by Task2
![image](https://user-images.githubusercontent.com/22415594/120899415-38626800-c662-11eb-9f73-9d387fbb1812.png)
2. Can we determine the value of param1 in Task4's varpool?
![image](https://user-images.githubusercontent.com/22415594/120899242-4c599a00-c661-11eb-89ae-d2885d869b4a.png)
3. The varpool might be huge in the back task, and they save the same data.
![image](https://user-images.githubusercontent.com/22415594/120899390-14068b80-c662-11eb-9792-f76900d7f49e.png)

Suggestion
![image](https://user-images.githubusercontent.com/22415594/120900269-91cc9600-c666-11eb-8382-6374d843c9ca.png)

This is my personal opinion, for reference only.

**Comment by wangxj3** [comment]
thanks for you suggestion.
1.The Direct of the params that  generate in the Task2 is OUT,and the Direct the params that get form the Task1 is IN.So we can  determine the source of this value by the Direct of the params.I think this is the same way with your suggestion.
2.When the previous tasks have the same param name,we will use the value which is't null.If more than two values are non-null,we will use the value that the earliest task's varpool.
3.This is the question of this plan ,We will optimize this issue in the future
So far I have finished coding,and will It will be submitted in a few days

**Comment by CalvinKirs** [comment]
close by #5603
