### ISSUE TITLE
[Bug][SQL] Only 10,000 data in the attachment

### ISSUE THREAD

**Issue by syb853553110** [apache/dolphinscheduler#5566]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
（1）Only 10,000 data in the attachment。
In fact, there are 170,000 records in mysql。
（2）In addition, when the subject of the email is too long, the suffix of the attachment is incorrect.

**To Reproduce**
Steps to reproduce the behavior, for example:
![image](https://user-images.githubusercontent.com/24668410/120281585-b1bd2c00-c2eb-11eb-8b1f-26e7a517f510.png)

![image](https://user-images.githubusercontent.com/24668410/120281629-bd105780-c2eb-11eb-9eae-6903df9f7477.png)

![image](https://user-images.githubusercontent.com/24668410/120282050-4889e880-c2ec-11eb-8d3c-af0b58106052.png)

![image](https://user-images.githubusercontent.com/24668410/120281522-a10cb600-c2eb-11eb-9cbf-99638917c92d.png)

**Expected behavior**
（1）The number of data in the attachment is the same as in mysql
（2）The file name and suffix in the attachment are correct. It is recommended that the name of the attachment can be customized

**Which version of Dolphin Scheduler:**
 -[1.3.6 Release]

**Comment by ruanwenjun** [comment]
@syb853553110 Only 10000 rows of results will be sent 😄 
https://github.com/apache/dolphinscheduler/blob/f8ecb536b71d6f33b71c73930832b62890b84ea1/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java#L89-L93

**Comment by syb853553110** [comment]
> @syb853553110 Only 10000 rows of results will be sent 😄
> https://github.com/apache/dolphinscheduler/blob/f8ecb536b71d6f33b71c73930832b62890b84ea1/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java#L89-L93

有参数可以修改嘛

**Comment by ruanwenjun** [comment]
@syb853553110 It's hard code, you can submit a pr to improve.

**Comment by syb853553110** [comment]
> @syb853553110 It's hard code, you can submit a pr to improve.
I looked at the source code and found the attachment name problem。

我看了下源码，找到了附件名称不对的问题，主要是这行代码的问题
org.apache.dolphinscheduler.alert.utils.MailUtils
part2.setFileName(MimeUtility.encodeText(title + Constants.EXCEL_SUFFIX_XLS,Constants.UTF_8,"B"));
改成
part2.setFileName(title + Constants.EXCEL_SUFFIX_XLS);
附件名称就不会出问题

**Comment by syb853553110** [comment]
> @syb853553110 It's hard code, you can submit a pr to improve.

In addition, I think the way the attachment is generated can be optimized. The current plan is to put all into a JSONArray, and then generate files. I think it is possible to write 10,000 files at a time, which can solve the problem of excessive memory usage caused by putting all the files in the memory at one time. Is the limit of 10,000 also considered the problem of excessive memory usage when the amount of data is too large?

**Comment by ruanwenjun** [comment]
> > @syb853553110 It's hard code, you can submit a pr to improve.
> > I looked at the source code and found the attachment name problem。
> 
> 我看了下源码，找到了附件名称不对的问题，主要是这行代码的问题
> org.apache.dolphinscheduler.alert.utils.MailUtils
> part2.setFileName(MimeUtility.encodeText(title + Constants.EXCEL_SUFFIX_XLS,Constants.UTF_8,"B"));
> 改成
> part2.setFileName(title + Constants.EXCEL_SUFFIX_XLS);
> 附件名称就不会出问题

Is the title in the database displayed correctly?

Query return number need to have a restriction, but I think it should be configurable, you can submit a pr to improve.

**Comment by syb853553110** [comment]
> > > @syb853553110 It's hard code, you can submit a pr to improve.
> > > I looked at the source code and found the attachment name problem。
> > 
> > 
> > 我看了下源码，找到了附件名称不对的问题，主要是这行代码的问题
> > org.apache.dolphinscheduler.alert.utils.MailUtils
> > part2.setFileName(MimeUtility.encodeText(title + Constants.EXCEL_SUFFIX_XLS,Constants.UTF_8,"B"));
> > 改成
> > part2.setFileName(title + Constants.EXCEL_SUFFIX_XLS);
> > 附件名称就不会出问题
> 
> Is the title in the database displayed correctly?
> Yes， is correct。 Only the name of attachment is incorrect when the titile is too long。
For example, "2021-05月某某公司通话数据明细"


> Query return number need to have a restriction, but I think it should be configurable, you can submit a pr to improve.

**Comment by caishunfeng** [comment]
This issue will be closed because no update for a long time. You can reopen it if need.
