### ISSUE TITLE
[Bug][dolphinscheduler-api] verify proccess definition name fail

### ISSUE THREAD

**Issue by Squidyu** [apache/dolphinscheduler#5569]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
when use spaces in proccess definition name, it will check fail!

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Go to create a process, edit a simple task;
2. Save process definition name as “new_process”;
3. Go to create a new process, edit a simple task;
4. Save process definition name as “    new_process”. This time, the name verification will also succeed;
5. Then two process definitions with the same name are generated.

**Which version of Dolphin Scheduler:**
 -[1.3.5]

**Requirement or improvement**
- Name verification can be solved by adding and removing the first and last spaces.

**Comment by Squidyu** [comment]
I'm working on it as my first PR

**Comment by chengshiwen** [comment]
@Squidyu Welcome to contribute code and look forward to your pr!

**Comment by ruanwenjun** [comment]
In fact, there are problems with concurrent modification in many places.
