### ISSUE TITLE
I encountered a problem here. When using api to authorize grantUser, the parameters are alertgroupId id and userIds

### ISSUE THREAD

**Issue by TobyXi1997** [apache/dolphinscheduler#5584]
我在填写api的时候alertgroupId   填写的是这个告警组的ID
id这个选项里面我填写的也是告警组ID
userIds填写的是用户ID
请问为什么我添加了告警组管理成功以后但是我的管理用户里面还没有用户。

**Comment by xingchun-chen** [comment]
Which version?

I've tried API to create alarm group. It's OK. Please make sure your userids are correct
![image](https://user-images.githubusercontent.com/55787491/121475683-529c9d00-c9f8-11eb-86c3-c8b0d92d9a12.png)
![image](https://user-images.githubusercontent.com/55787491/121475710-5d573200-c9f8-11eb-9e0a-e1a59107c733.png)
