### ISSUE TITLE
[Bug][worker] worker log stops scrolling

### ISSUE THREAD

**Issue by gaoyu2016** [apache/dolphinscheduler#5585]
一、问题如下
1.master、worker、logger进程都在，测试一个简单的shell任务。任务被调度到了10.11.56.141 这台worker机上。界面上，点击查看日志，可以看到执行 日志。
![image](https://user-images.githubusercontent.com/29685418/120464862-fb7f4280-c3cf-11eb-977c-88024292c783.png)

2.但是登录到10.11.56.141 这台调度机上：查看dolphinscheduler-worker.log，没有看到执行日志。
该调度机上的worker-server和logger-server进程从5.17重启，worker.log 从May 27 23:16之后，就没有滚动产生新的日志。
![image](https://user-images.githubusercontent.com/29685418/120466021-2f0e9c80-c3d1-11eb-99f4-1a7889bcb52b.png)

3.查看dolphinscheduler-logger-server-dx-pipe-sata663-pm.out 有如下日志提示：
20:37:59.608 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328)
        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306)
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
        at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:198)
        at io.netty.channel.epoll.Native.<clinit>(Native.java:61)
        at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:38)
        at org.apache.dolphinscheduler.remote.utils.NettyUtils.useEpoll(NettyUtils.java:41)
        at org.apache.dolphinscheduler.remote.NettyRemotingServer.<init>(NettyRemotingServer.java:102)
        at org.apache.dolphinscheduler.server.log.LoggerServer.<init>(LoggerServer.java:53)
        at org.apache.dolphinscheduler.server.log.LoggerServer.main(LogerServer.java:66)

**Comment by gaoyu2016** [comment]
dolphinscheduler-logger-server-dx-pipe-sata663-pm.out 提示：
19:35:33.107 [NettyServerWorkerThread_43] WARN org.apache.dolphinscheduler.remote.handler.NettyServerHandler - [id: 0x1bcc238a, L:/10.11.56.141:50051 - R:/10.11.55.30:31269] is not writable, over high water level : 65536
19:35:33.107 [NettyServerWorkerThread_43] WARN org.apache.dolphinscheduler.remote.handler.NettyServerHandler - [id: 0x1bcc238a, L:/10.11.56.141:50051 - R:/10.11.55.30:31269] is writable, to low water : 32768

**Comment by chengshiwen** [comment]
This debug information `DEBUG io.netty.util.internal.NativeLibraryLoader-Unable to load the library'netty_transport_native_epoll_x86_64' trying other loading mechanism` does not affect

**Comment by CalvinKirs** [comment]
> 一、问题如下
> 1.master、worker、logger进程都在，测试一个简单的shell任务。任务被调度到了10.11.56.141 这台worker机上。界面上，点击查看日志，可以看到执行 日志。
> ![image](https://user-images.githubusercontent.com/29685418/120464862-fb7f4280-c3cf-11eb-977c-88024292c783.png)
> 
> 2.但是登录到10.11.56.141 这台调度机上：查看dolphinscheduler-worker.log，没有看到执行日志。
> 该调度机上的worker-server和logger-server进程从5.17重启，worker.log 从May 27 23:16之后，就没有滚动产生新的日志。
> ![image](https://user-images.githubusercontent.com/29685418/120466021-2f0e9c80-c3d1-11eb-99f4-1a7889bcb52b.png)
> 
> 3.查看dolphinscheduler-logger-server-dx-pipe-sata663-pm.out 有如下日志提示：
> 20:37:59.608 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.
> java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
> at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
> at java.lang.Runtime.loadLibrary0(Runtime.java:870)
> at java.lang.System.loadLibrary(System.java:1122)
> at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336)
> at java.security.AccessController.doPrivileged(Native Method)
> at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328)
> at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306)
> at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
> at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:198)
> at io.netty.channel.epoll.Native.(Native.java:61)
> at io.netty.channel.epoll.Epoll.(Epoll.java:38)
> at org.apache.dolphinscheduler.remote.utils.NettyUtils.useEpoll(NettyUtils.java:41)
> at org.apache.dolphinscheduler.remote.NettyRemotingServer.(NettyRemotingServer.java:102)
> at org.apache.dolphinscheduler.server.log.LoggerServer.(LoggerServer.java:53)
> at org.apache.dolphinscheduler.server.log.LoggerServer.main(LogerServer.java:66)

3 is not a problem. This is a DEBUG level log. You can search for relevant information in Netty's issue.

**Comment by CalvinKirs** [comment]
> dolphinscheduler-logger-server-dx-pipe-sata663-pm.out 提示：
> 19:35:33.107 [NettyServerWorkerThread_43] WARN org.apache.dolphinscheduler.remote.handler.NettyServerHandler - [id: 0x1bcc238a, L:/10.11.56.141:50051 - R:/10.11.55.30:31269] is not writable, over high water level : 65536
> 19:35:33.107 [NettyServerWorkerThread_43] WARN org.apache.dolphinscheduler.remote.handler.NettyServerHandler - [id: 0x1bcc238a, L:/10.11.56.141:50051 - R:/10.11.55.30:31269] is writable, to low water : 32768

This is overload protection, but it can also be optimized. What we need to understand is why accumulation occurs. Can you provide a version and more information?

**Comment by gaoyu2016** [comment]
使用的是ds 1.3.4版本。

**Comment by gaoyu2016** [comment]
重启worker和logger服务进程后，恢复。

**Comment by CalvinKirs** [comment]
Sorry, I am a little confused.

Do you mean that the log can be seen on the UI interface? But can’t see it when I log in to the server?

This is somewhat strange. The log on the UI interface is also by viewing the local log.

**Comment by gaoyu2016** [comment]
yes。非常奇怪。

**Comment by CalvinKirs** [comment]
> Sorry, I am a little confused.
> 
> Do you mean that the log can be seen on the UI interface? But can’t see it when I log in to the server?
> 
> This is somewhat strange. The log on the UI interface is also by viewing the local log.

You are referring to the worker's own running log. do you mean this? What you see on the UI is the task log.

**Comment by gaoyu2016** [comment]
ui看到的：
![image](https://user-images.githubusercontent.com/29685418/120584959-78a7c780-c463-11eb-9af6-7af63f7273e0.png)

**Comment by gaoyu2016** [comment]
![image](https://user-images.githubusercontent.com/29685418/120585037-a1c85800-c463-11eb-9c40-c60c40d7867a.png)

**Comment by gaoyu2016** [comment]
但是，在10.11.56.141这台调度机上是看不到dolphinscheduler-worker.log 2021-06-02 最近几天的日志。

**Comment by gaoyu2016** [comment]
![image](https://user-images.githubusercontent.com/29685418/120585159-da683180-c463-11eb-84e5-9c180f6e0526.png)

**Comment by gaoyu2016** [comment]
谁能解决呢？

**Comment by gaoyu2016** [comment]
who can help me ?

**Comment by zhuangchong** [comment]
@gaoyu2016 

1. Viewed on the UI interface, the log belongs to a specific task log. The log path is in $DOLPHINSCHEDULER_HOME/logs/folder/folder/*.log

2. dolphinscheduler-worker.log can view detailed task logs in version 1.3.5+, it is recommended to upgrade

**Comment by gaoyu2016** [comment]
i know, 了解。为何worker.log 停止滚动呢？

**Comment by zhuangchong** [comment]
@gaoyu2016 
The problem you describe has been optimized in version 1.3.5

**Comment by gaoyu2016** [comment]
1.3.5？这个是1个bug？

**Comment by gaoyu2016** [comment]
可以具体说下吗?

**Comment by gaoyu2016** [comment]
我没找到1.3.5里面的milestone

**Comment by zhuangchong** [comment]
@gaoyu2016 
https://github.com/apache/dolphinscheduler/pull/4665

**Comment by caishunfeng** [comment]
This issue had been fixed, so it wiil be closed.
