### ISSUE TITLE
[Bug][API] Tenant validation failure under Windows

### ISSUE THREAD

**Issue by chengshiwen** [apache/dolphinscheduler#5587]
**To Reproduce**

In Windows, there are some characters like uppercase or space in some tenants. And the following code only judges Linux, it will cause tenant validation failure under Windows

https://github.com/apache/dolphinscheduler/blob/cc9e5d5d34fcf2279b267cca7df37a9e80eeba07/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TenantServiceImpl.java#L93-L96

**Expected behavior**
Bug fixed

**Which version of Dolphin Scheduler:**
 -[dev]

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by QuakeWang** [comment]
I will fix it.
