### ISSUE TITLE
Create workflow error

### ISSUE THREAD

**Issue by oryjk** [apache/dolphinscheduler#5592]
### bug日志
A[ERROR] 2021-06-05 16:53:42.921 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[45] - 创建工作流错误
2021/6/5 下午4:53:42org.springframework.jdbc.BadSqlGrammarException:
2021/6/5 下午4:53:42### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: column "modify_by" of relation "t_ds_process_definition" does not exist
2021/6/5 下午4:53:42  Position: 40
2021/6/5 下午4:53:42### The error may exist in org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.java (best guess)
2021/6/5 下午4:53:42### The error may involve org.apache.dolphinscheduler.dao.mapper.ProcessDefinitionMapper.insert-Inline
2021/6/5 下午4:53:42### The error occurred while setting parameters
2021/6/5 下午4:53:42### SQL: INSERT INTO t_ds_process_definition  ( modify_by, flag,  description, update_time,  process_definition_json, user_id, version, timeout, connects,  create_time, tenant_id, name, locations, release_state, project_id, resource_ids )  VALUES  ( ?, ?,  ?, ?,  ?, ?, ?, ?, ?,  ?, ?, ?, ?, ?, ?, ? )
2021/6/5 下午4:53:42### Cause: org.postgresql.util.PSQLException: ERROR: column "modify_by" of relation "t_ds_process_definition" does not exist
2021/6/5 下午4:53:42  Position: 40
2021/6/5 下午4:53:42; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: column "modify_by" of relation "t_ds_process_definition" does not exist
2021/6/5 下午4:53:42  Position: 40

**Comment by chengshiwen** [comment]
@oryjk Did you import the `sql/dolphinscheduler_postgre.sql` or `sql/dolphinscheduler_mysql.sql`?

**Comment by oryjk** [comment]
Yeah, I’ve done this before, and many tables have been created, it looks like some fields of some tables are missing

**Comment by chengshiwen** [comment]
@oryjk Could you show us more information like ds version and the steps of deployment?

**Comment by oryjk** [comment]
I re-imported dolphinscheduler_postgre.sql, the problem was solved, I think it should be like this, when I started the docker of ds, I thought that dolphinscheduler_postgre.sql has been compiled into docker and imported automatically, so I suggest that you can indicate it in the document The address of sql, another small problem, the document says dolphinscheduler-postgre.sql, but the actual name is dolphinscheduler_postgre.sql

**Comment by oryjk** [comment]
solved
