### ISSUE TITLE
[Bug][Build] Compile error on Apple Silicon M1

### ISSUE THREAD

**Issue by oryjk** [apache/dolphinscheduler#5595]
When I execute mvn clean install -Prelease, an error is reported, as shown below
![image](https://user-images.githubusercontent.com/6252789/120968163-17516280-c79b-11eb-99af-ab2ed124bbda.png)

**Comment by chengshiwen** [comment]
@oryjk In new mac with apple silicon m1, there are some problems like that the nodejs v12 do not support m1 until v16. So you can modify `node.version` to `v16.3.0` and `npm.version` to `7.15.1` in `dolphinscheduler-ui/pom.xml` and try it again

**Comment by oryjk** [comment]
ok, thank you, I'll try it right away

**Comment by oryjk** [comment]
I check my node and npm version, the version as you said
![image](https://user-images.githubusercontent.com/6252789/121034715-cfa0fa00-c7df-11eb-9f4b-6fd88521d9e6.png)

**Comment by oryjk** [comment]
I change the node and npm version, but also
![image](https://user-images.githubusercontent.com/6252789/121130193-a2e0f700-c860-11eb-9b4d-19e3b42ba0fd.png)

**Comment by chengshiwen** [comment]
@oryjk Modidy `frontend-maven-plugin.version` to `1.11.3` in root `pom.xml` and try it again. Sometimes caused by network problems

**Comment by oryjk** [comment]
@chengshiwen 
also

![Uploading image.png…]()

**Comment by oryjk** [comment]
I switch to a computer with a non-m1 and it can be compiled successfully

**Comment by caishunfeng** [comment]
This issue will be closed because no update for a long time. You can reopne it if need.
