### ISSUE TITLE
[Bug][Python] Conflict between python_home and datax_home configuration in dolphinscheduler_env.sh

### ISSUE THREAD

**Issue by flyDragon-Y** [apache/dolphinscheduler#5596]
Environment configuration of dataX and python
dolphinscheduler_ Env.sh configuration
To configure dataX python, you need to configure it in the root directory of Python
To execute a python script, you need to configure the python executable file in the python directory

- [dev]
- [1.3.6]

**Comment by chengshiwen** [comment]
@flyDragon-Y Which version of ds? And what's your problem?

**Comment by flyDragon-Y** [comment]
用的1.3.6
问题
就是当我的dolphinscheduler_ Env.sh 配置文件的PYTHON_HOME 配置成 /xxxxx/xxx/Python(解压包文件夹) 的时候，datax正常运行但是python运行会报错找不到命令 ，当我配置成/xxxxx/xxx/Python(解压包文件夹)/python 的时候 python正常运行，datax运行会报错找不到命令

**Comment by chengshiwen** [comment]
@flyDragon-Y `PYTHON_HOME` is the absolute path of python binary like `/xxxxx/xxx/Python/bin/python`, while `DATAX_HOME` is the absolute path of datax home like `/xxxxx/xxx/datax` (`/xxxxx/xxx/datax/bin/datax.py` is the path of `datax.py`)

**Comment by geosmart** [comment]
this `PYTHON_HOME` also confused me when I startup with ds,

as we know `XXX_HOME` should be a path , rather than a file.

shuold we improve this environment variable to a path?

**Comment by chengshiwen** [comment]
> this `PYTHON_HOME` also confused me when I startup with ds,
> 
> as we know `XXX_HOME` should be a path , rather than a file

@geosmart Issues left over from history. We have improved this problem in dev branch, so in the next release the Improvement will be released

**Comment by flyDragon-Y** [comment]
I mean PYTHON_HOME is configured as /xxxx/xxx/python/bin/python, datax.py of dataX will not be able to execute

**Comment by chengshiwen** [comment]
> I mean PYTHON_HOME is configured as /xxxx/xxx/python/bin/python, datax.py of dataX will not be able to execute

There may be a problem, I will troubleshoot and fix it as soon as possible

**Comment by flyDragon-Y** [comment]
ok，If you have the latest situation，remember tell me，thanks

**Comment by chengshiwen** [comment]
@flyDragon-Y The related fixed pr are #5393 (https://github.com/apache/dolphinscheduler/pull/5393/commits/98567b7bc9239011bd951ecd4773633264719977) and #5612
Thanks for your feedback!

**Comment by mrchang2017** [comment]
I still have this problem in version 3.1.2 docker image: apache/dolphinscheduler-worker. 

the related source path:
```
dolphinscheduler-task-plugin/dolphinscheduler-task-python/src/main/java/org/apache/dolphinscheduler/plugin/task/python/PythonTask.java
```

function
```java
    protected String buildPythonExecuteCommand(String pythonFile) {
        Preconditions.checkNotNull(pythonFile, "Python file cannot be null");

        String pythonHome = String.format("${%s}", PYTHON_HOME);

        return pythonHome + " " + pythonFile;
    }
```

This issue should be resolve in version 1.3.8 but still appears in version 3.1.2.

----

the enviroment variable `PYTHON_HOME` should be a `directory` contains a python interpreter. But it was refered to `interpreter` itself instead of a directory in here. It is confusing, maybe we can add more variables like `PYTHON_EXE`.

**Comment by cnfree0355** [comment]
> 

The same problem occurs in version 3.1.3. The configured key is the python path, but what actually needs to be set is the python execution file, which is confusing
