### ISSUE TITLE
[Bug][conditions component] conditions component go success way but the previous task was failed

### ISSUE THREAD

**Issue by NeverLanded** [apache/dolphinscheduler#5601]
![image](https://user-images.githubusercontent.com/28940909/121142309-6d430a80-c86e-11eb-9d32-d968a262d935.png)

**Comment by NeverLanded** [comment]
does the success and failure status in the condition component  refer to the previous task or the task of condition itself?

**Comment by xingchun-chen** [comment]
The Condition node can refer to the figure below. The Custom parameters need to configure whether the front node succeeds or fails

![image](https://user-images.githubusercontent.com/55787491/121474085-27b14980-c9f6-11eb-8bbc-266feaa39132.png)

**Comment by NeverLanded** [comment]
that's make sense,thanks for the reply!
