### ISSUE TITLE
[Feature][Module Name] Feature title

### ISSUE THREAD

**Issue by pingyuan001** [apache/dolphinscheduler#5604]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/community/development/issue.html when describe an issue.*

**Describe the feature**
A clear and concise description of what the feature is.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pingyuan001** [comment]
select结果达到多少的时候才会继续走下面的流程，否则一直等待，等待超时一定时间，任务就失败
![1111111](https://user-images.githubusercontent.com/26142295/121179945-d89ed380-c892-11eb-8de8-89f6171049b4.png)

**Comment by davidzollo** [comment]
please update the feature title
