### ISSUE TITLE
[Question] Failed to run main method of CreateDolphinScheduler

### ISSUE THREAD

**Issue by wangmingzhiJohn** [apache/dolphinscheduler#5607]
**Describe the question**

I cannot start the DS system by following the Developer Guide/Development Environment Setup. Particularly I got stuck when I tried setting up the backend. I didn't import the project to IDEA but just use cmd. When I finally made it run (i mean the main method of CreateDolphinScheduler), it told me that some files do not exist like dolphinscheduler_dml.sql or dolphinscheduler_ddl.sql. So I manually created these empty files. And then another error.

**Which version of DolphinScheduler:**
 -[1.3.6]

**Additional context**

Pictures of these errors:
![image](https://user-images.githubusercontent.com/84900511/121284290-35d86a80-c90f-11eb-9ba8-e3b0d9596f7c.png)
![image](https://user-images.githubusercontent.com/84900511/121284317-3ec93c00-c90f-11eb-8db5-e54388b8a602.png)
And I am not sure if i follow the right way to run the main method of CreateDolphinScheduler. My way is modify the pom.xml under dolphinscheduler-dao, generate the apache-dolphinscheduler-1.3.6-SNAPSHOT.jar which has main-class, use "java -jar apache-dolphinscheduler-1.3.6-SNAPSHOT.jar" cmd to run. Is that right?

**Comment by chengshiwen** [comment]
@wangmingzhiJohn Click the run icon, or run `create-dolphinscheduler.sh`

![image](https://user-images.githubusercontent.com/4902714/121285384-e7c46680-c910-11eb-8c3f-7e115947f86a.png)

**Comment by wangmingzhiJohn** [comment]
@chengshiwen I have another question. My code is on the company's server. How to import the project from remote server to intellij idea? I didn't see anything in IDEA like Vscode's remote explorer that can let me develop on remote server directly.

**Comment by wangmingzhiJohn** [comment]
![image](https://user-images.githubusercontent.com/84900511/121315943-6504d100-c93b-11eb-90cd-e97fb58422b8.png)
When I ran the CreateDolphinScheduler, I got errors like "lack ddl file". That file should be created in this segment but it wasn't.

**Comment by chengshiwen** [comment]
> @wangmingzhiJohn Click the run icon, or run `create-dolphinscheduler.sh`

You can consider the script `create-dolphinscheduler.sh` on the server

**Comment by echohlne** [comment]
@wangmingzhiJohn,  if you just want to have a local environment for debugging, pls just follow this:
[development-environment-setup](https://dolphinscheduler.apache.org/zh-cn/development/development-environment-setup.html), the official documentation is comprehensive

**Comment by wangmingzhiJohn** [comment]
@kyoty But I'd like to debug the remote project with local IDEA, it can't be achieved.
