### ISSUE TITLE
[Feature] move the Doc of Ambari Integration to official website repository

### ISSUE THREAD

**Issue by davidzollo** [apache/dolphinscheduler#5608]
Please move the Doc of [Ambari Integration](https://github.com/apache/dolphinscheduler/blob/1.3.6-release/ambari_plugin/README.md)  to here, the position is as follows:
![image](https://user-images.githubusercontent.com/15833811/121296000-860cf800-c922-11eb-912e-12dfd821541f.png)

official website git repository :  https://github.com/apache/dolphinscheduler-website

**Comment by althafpj** [comment]
I would like to contribute to this.

**Comment by davidzollo** [comment]
> I would like to contribute to this.

glad to see you want to solve this issue, if you need any help, please leave a message.

**Comment by ji04xiaogang** [comment]
I would like to contribute to this.

**Comment by ji04xiaogang** [comment]
I would like to contribute to this and I will solve this issue in 3days.

**Comment by QuakeWang** [comment]
> I would like to contribute to this and I will solve this issue in 3days.

First of all thank you for wanting to participate, but this [task](https://github.com/apache/dolphinscheduler-website/pull/389) has already been done, feel free to pick up a new task, you can refer to this [issue](https://github.com/apache/dolphinscheduler/issues/5689)

**Comment by ji04xiaogang** [comment]
OK. I see the issuse has been repopen . I pick up a new task .

**Comment by davidzollo** [comment]
@ji04xiaogang , please update the content of this picture in English
![image](https://user-images.githubusercontent.com/15833811/123738856-334aae80-d8d8-11eb-8c75-d9da862b7f25.png)
and only keep the last two items, thank you.
the result pic looks like the following pic
![image](https://user-images.githubusercontent.com/15833811/123738944-64c37a00-d8d8-11eb-9481-abdc6e17ad50.png)

talking about the description of DolphinScheduler, please use the following expression: a distributed and extensible workflow scheduler platform with powerful visual interfaces.
