### ISSUE TITLE
[Question] Expansion

### ISSUE THREAD

**Issue by Tandoy** [apache/dolphinscheduler#5609]
**Steps to reproduce the behavior:**
sh start-all.sh

**Expected behavior:**
Add a master/worker node to an existing cluster

**Environment Description::**
 dolphinscheduler：1.3.2
Hadoop version : 2.6.0-cdh5.13.3
Hive version : 1.1.0-cdh5.13.3
Storage (HDFS/S3/GCS..) : HDFS
Running on Docker? (yes/no) :no

**Configuration**
../conf/config/install_config.conf
masters="dxbigdata101,dxbigdata103"
workers="dxbigdata103:default,dxbigdata101:default"

**Stacktrace**
Cannot find the target file path, unable to start. . .

**Additional context:**
I am expanding the capacity to add a new node, but the installation directory is inconsistent with the existing one in the cluster. I can't find the new node directory when I execute bin/start-all.sh and I can only start the worker on the new node separately.So if I want to use start-all.sh, does the installation path of the new node have to be the same?

**Comment by xingchun-chen** [comment]
The installation directory of the extension node should be consistent with that of the cluster

**Comment by Tandoy** [comment]
> The installation directory of the extension node should be consistent with that of the cluster

Ok thank you!
