### ISSUE TITLE
[Question] Something wrong with build docker image from source

### ISSUE THREAD

**Issue by wangmingzhiJohn** [apache/dolphinscheduler#5610]
**Describe the question**

I tried building a image by clean source code. 
![image](https://user-images.githubusercontent.com/84900511/121340374-20386480-c952-11eb-81d8-c201586a47c0.png)
and then setup in this way. 
![image](https://user-images.githubusercontent.com/84900511/121340450-3514f800-c952-11eb-8042-4bdd56df2d7b.png)
But when I tried to create a project, it failed.
![image](https://user-images.githubusercontent.com/84900511/121341733-896ca780-c953-11eb-8f3c-d494bddea536.png)

**Which version of DolphinScheduler:**
 -[1.3.6]

**Additional context**
And also I found that the image I pull does not has the same size as the image I build, Does anyone know the reason?
![image](https://user-images.githubusercontent.com/84900511/121340737-84f3bf00-c952-11eb-8dec-10f6c4d28b7f.png)

**Comment by chengshiwen** [comment]
@wangmingzhiJohn It seems that you are building with the dev branch, in the dev branch the `create project error` does exist, related issue: #5540. It’s not a problem with the docker image. As for the image size, it’s caused by the addition of a plugin to the dev branch

**Comment by wangmingzhiJohn** [comment]
@chengshiwen the latest dev branch has solved this issue?

**Comment by chengshiwen** [comment]
waiting to merge the pr #5611

**Comment by wangmingzhiJohn** [comment]
Fine, I was excited to update and try again, but still failed to create project -_-!!

**Comment by chengshiwen** [comment]
Close by #5611
