### ISSUE TITLE
[Bug][Module Name] DruidDataSource exception:  physical connection to pool failed

### ISSUE THREAD

**Issue by github24518** [apache/dolphinscheduler#5617]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:

**Expected behavior**

**Screenshots**
   DruidDataSourceput exception:  physical connection to pool failed

**Which version of Dolphin Scheduler:**
 -[1.1.0-preview]
  Dolphin Scheduler 1.3.2

**Additional context**
   master-worker error  log:
[INFO] 2021-06-10 18:15:07.818 com.alibaba.druid.pool.DruidDataSource:[2615] - put physical connection to pool failed.
[INFO] 2021-06-10 18:15:07.826 com.alibaba.druid.pool.DruidDataSource:[2615] - put physical connection to pool failed.
[INFO] 2021-06-10 18:15:07.834 com.alibaba.druid.pool.DruidDataSource:[2615] - put physical connection to pool failed.
[INFO] 2021-06-10 18:15:07.841 com.alibaba.druid.pool.DruidDataSource:[2615] - put physical connection to pool failed.
[INFO] 2021-06-10 18:15:07.850 com.alibaba.druid.pool.DruidDataSource:[2615] - put physical connection to pool failed.
[INFO] 2021-06-10 18:15:07.858 com.alibaba.druid.pool.DruidDataSource:[2615] - put physical connection to pool failed.
[INFO] 2021-06-10 18:15:07.865 com.alibaba.druid.pool.DruidDataSource:[2615] - put physical connection to pool failed.
[INFO] 2021-06-10 18:15:07.875 com.alibaba.druid.pool.DruidDataSource:[1823] - connection recyle failed.
[INFO] 2021-06-10 18:15:07.881 com.alibaba.druid.pool.DruidDataSource:[2615] - put physical connection to pool failed.
[INFO] 2021-06-10 18:15:07.890 com.alibaba.druid.pool.DruidDataSource:[2615] - put physical connection to pool failed.

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by CalvinKirs** [comment]
Can you provide more information about the stack?

**Comment by caishunfeng** [comment]
The issue will be closed because no update for a long time. You can reopen it if need.

**Comment by github24518** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
