### ISSUE TITLE
[Bug][Release] tar.gz tarball decompression error and some files are missing on Windows

### ISSUE THREAD

**Issue by chengshiwen** [apache/dolphinscheduler#5619]
**To Reproduce**

1. Go to https://dolphinscheduler.apache.org/en-us/download/download.html
2. Download tar.gz tarball
3. Decompress the tarball by WinRAR or 7-Zip
4. See decompression error and some files are missing

**Expected behavior**
Bug fixed

**Which version of Dolphin Scheduler:**
 -[1.3.x]
 -[dev]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by chengshiwen** [comment]
https://www.apache.org/dyn/closer.lua/dolphinscheduler/1.3.6/apache-dolphinscheduler-1.3.6-src.tar.gz

![image](https://user-images.githubusercontent.com/4902714/127814022-1d26bbc0-5cd4-470e-ab10-2eaeb3df20cd.png)
![image](https://user-images.githubusercontent.com/4902714/127814127-43380ea6-25f1-42a0-985d-37fbe0323278.png)
![image](https://user-images.githubusercontent.com/4902714/127814192-d9eada67-e9b8-40a1-a64d-e060d99a4517.png)

**Comment by chengshiwen** [comment]
https://www.apache.org/dyn/closer.lua/dolphinscheduler/1.3.4/apache-dolphinscheduler-incubating-1.3.4-dolphinscheduler-bin.tar.gz

![image](https://user-images.githubusercontent.com/4902714/127814309-f5b163ee-a9d1-43b2-9868-042df7a67027.png)
![image](https://user-images.githubusercontent.com/4902714/127814343-fa74078b-bf9d-43de-a730-4618307780c3.png)
![image](https://user-images.githubusercontent.com/4902714/127814390-77af8cb5-3526-4b7f-9d4e-f7a9b891c6e6.png)

**Comment by chengshiwen** [comment]
While everything goes well in https://github.com/apache/dolphinscheduler/releases: https://github.com/apache/dolphinscheduler/archive/refs/tags/1.3.6.tar.gz

**Comment by CalvinKirs** [comment]
Considering that this is not an urgent question, we will release it in 1.3.8.
