### ISSUE TITLE
[Improvement][job  instance]start-time and end-time

### ISSUE THREAD

**Issue by mengfeiMonica** [apache/dolphinscheduler#5621]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/community/development/issue.html when describe an issue.*

**Describe the question**
工作流实例列表中，如果多个工作流存在依赖关系，最后的工作流任务时长是累计时长，还有，这个排序好像只是按照开始时间排序的，希望能做成开始时间一样，按照结束时间再排一下.

**What are the current deficiencies and the benefits of improvement**
- A clear and concise description of the current deficiencies and the benefits of this improvement.

**Which version of DolphinScheduler:**
 -[1.3.6]

**Describe alternatives you've considered**
A clear and concise description of any alternative improvement solutions you've considered.

**Comment by Tandoy** [comment]
I want to try to solve this issue
