### ISSUE TITLE
[Improvement][project management] Modify the title

### ISSUE THREAD

**Issue by mengfeiMonica** [apache/dolphinscheduler#5622]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/community/development/issue.html when describe an issue.*

**Describe the question**
“项目管理”功能模块中“项目首页”菜单与页面内容关系不大。.

**What are the current deficiencies and the benefits of improvement**
- “项目首页”文字，修改成“工作流监控”.

**Which version of DolphinScheduler:**
 -[1.3.7]

**Describe alternatives you've considered**
A clear and concise description of any alternative improvement solutions you've considered.

**Comment by tinyking** [comment]
Hi, i will take this issue. Thanks.
