### ISSUE TITLE
[Question] How to import third-party module conveniently in a Python task from the perspective of a normal user

### ISSUE THREAD

**Issue by wangmingzhiJohn** [apache/dolphinscheduler#5636]
**Describe the question**
If I am a normal user to use this product, I want to create a python task which needs to import like tensorflow or sth else. As there is  not any third-party module in the environment of worker's container, it will fail to import those modules.
So. my question is, how can I achieve my goal in a simple way?

**Comment by wangmingzhiJohn** [comment]
One more word, I don't think it is a wise or efficient way to use Resources to provide the needed module. And also, we cannot provide all modules in docker which will make the image too big.

**Comment by chengshiwen** [comment]
@wangdazhong001 Please refer to https://dolphinscheduler.apache.org/en-us/docs/1.3.6/user_doc/docker-deployment.html, and you can choose
- Build a new image like **How to support Python 2 pip and custom requirements.txt** or **How to support Python 3**
- Mount and share a volume like **How to support Hadoop, Spark, Flink, Hive or DataX**

**Comment by chengshiwen** [comment]
Close since it has been replied
