### ISSUE TITLE
[Question] Cannot visit the official website https://dolphinscheduler.apache.org/zh-cn/

### ISSUE THREAD

**Issue by wuhongyuwhy** [apache/dolphinscheduler#5637]
不能访问官网 https://dolphinscheduler.apache.org/zh-cn/

**Comment by CalvinKirs** [comment]
I checked all is fine, can you check your own network?

**Comment by zhuangchong** [comment]
I can access normally.

![Uploading image.png…]()

**Comment by wuhongyuwhy** [comment]
湖北电信dns解析的问题。 文件解决了。
