### ISSUE TITLE
[Question][NetUtils] Registered ip

### ISSUE THREAD

**Issue by lyn916** [apache/dolphinscheduler#5644]
**To Reproduce**
Steps to reproduce the behavior, for example:
1. When I use keepalived to bind the virtual ip, the registered ip will be bound to vip 

**Which version of Dolphin Scheduler:**
 -[1.3.6-latest]

**Requirement or improvement**
- Specify the interface name and ip when deploying,

**Comment by CalvinKirs** [comment]
Maybe you can try to use this parameter to specify the NIC.    
dolphin.scheduler.network.interface.preferred

**Comment by CalvinKirs** [comment]
Currently this parameter is only supported for jvm startup parameter injection.

**Comment by lyn916** [comment]
> Maybe you can try to use this parameter to specify the NIC.
> dolphin.scheduler.network.interface.preferred

2. solved

**Comment by lyn916** [comment]
-Dvip=192.168.168.190
`
package org.apache.dolphinscheduler.common.utils;
public class NetUtils {

    private static Optional<InetAddress> toValidAddress(InetAddress address) {
          String vip = System.getProperty(VIP);  
          if (address instanceof Inet6Address) {
              Inet6Address v6Address = (Inet6Address) address;
              if (isPreferIPV6Address()) {
                  return Optional.ofNullable(normalizeV6Address(v6Address));
              }
          }
          if (isValidV4Address(address)){
              if (vip == null){
                  return Optional.of(address);
              }else if(!address.getHostAddress().equals(vip)) {
                  return Optional.of(address);
              }
          }
          return Optional.empty();
      }
}
`
I solve this problem by adding VIP parameter and skipping VIP when registering IP

dolphinscheduler-daemon.sh
export DOLPHINSCHEDULER_OPTS="
-server 
-Ddolphin.scheduler.network.interface.preferred=ens33 
**-Dvip=192.168.168.190**
-XX:MetaspaceSize=128m 
-XX:MaxMetaspaceSize=128m 
-Xss512k 
-XX:+UseParNewGC 
-XX:+UseConcMarkSweepGC 
-XX:+CMSParallelRemarkEnabled 
-XX:LargePageSizeInBytes=128m 
-XX:+UseCMSInitiatingOccupancyOnly 
-XX:CMSInitiatingOccupancyFraction=70 
-XX:+PrintGCDetails 
-Xloggc:$DOLPHINSCHEDULER_LOG_DIR/gc.log 
-XX:+HeapDumpOnOutOfMemoryError 
-XX:HeapDumpPath=dump.hprof 
-XshowSettings:vm $DOLPHINSCHEDULER_OPTS
"

**Comment by CalvinKirs** [comment]
This is usually not recommended (although it is also a solution), if the cluster deployment, the parameters are usually set by the operations staff unified.
For IP issues, it can't just be the framework that is doing the hard work, the user side needs to do the processing as well.
