### ISSUE TITLE
[Question] How to access the web without the path "/dolphinscheduler/"?Just only IP and port?

### ISSUE THREAD

**Issue by xyzhh** [apache/dolphinscheduler#5645]
Everytime ,when I access DS, I need input the full path , e.g. "http://192.168.100.99:12345/dolphinscheduler".It is too long,and hardly to remmeber. How can I modify the access url to "http://192.168.100.99:12345" ? Thanks!
**Which version of DolphinScheduler:**
 -[1.3.5]

**Comment by chengshiwen** [comment]
@xyzhh Two solutions:
1. You can refer to #4944 by using nginx
2. You need to modify `server.servlet.context-path` to `/` in `application-api.properties`, and modify all `/dolphinscheduler` to `/` in `dolphinscheduler-ui`, but this solution needs professional development experience
