### ISSUE TITLE
【IMP】[Master Server] Optimization of thread sleep

### ISSUE THREAD

**Issue by chakench** [apache/dolphinscheduler#5646]
The class involved：
1. MasterExecThread.runProcess
2. MasterTaskExecThread.waitTaskQuit
Can Thread.sleep(Constants.SLEEP_TIME_MILLIS) be changed to wait/notify mode in the methods of the above two classes

**Comment by ruanwenjun** [comment]
@chakench Do you mean using an event-driven model? I think it's  a good idea, and you can provide your detail design.

**Comment by CalvinKirs** [comment]
In fact, we had several discussions before that, but still don't have a good plan, so if you have a good idea, feel free to share it.
