### ISSUE TITLE
[Bug][UI]condition node NPE

### ISSUE THREAD

**Issue by pingyuan001** [apache/dolphinscheduler#5657]
Operation steps
1、when i has created  condition's node and linked the other nodes, i modify the link nodes name and save the process_definition. 

2、excute the process_definition

3、 There is an error message in the log :
      org.apache.dolphinscheduler.server.master.runner.MasterExecThread:[189] - master exec thread exception
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.dao.utils.DagHelper.isTaskNodeNeedSkip(DagHelper.java:317)

![9999](https://user-images.githubusercontent.com/26142295/122412902-8d827000-cfb8-11eb-8d08-8ba8da490844.png)

**Comment by CalvinKirs** [comment]
hi, which version?

**Comment by pingyuan001** [comment]
the dev and 1.3.6 has the bug ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月30日(星期三) 凌晨0:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] condition node bug (#5657)

**Comment by CalvinKirs** [comment]
close by #5724
