### ISSUE TITLE
[Feature][ui] user can monitor dolphinscheduler's log by Web UI

### ISSUE THREAD

**Issue by Anilople** [apache/dolphinscheduler#5658]
**Describe the feature**

User can view dolphinscheduler self's *.log file under folder logs by UI without login to Linux server.

i.e those files
```
dolphinscheduler-alert.log
dolphinscheduler-alert-server-localhost.localdomain.out
dolphinscheduler-api.2021-06-17_05.0.log
dolphinscheduler-api.log
dolphinscheduler-api-server-localhost.localdomain.out
dolphinscheduler-logger-server-localhost.localdomain.out
dolphinscheduler-master.log
dolphinscheduler-master-server-localhost.localdomain.out
dolphinscheduler-worker.log
dolphinscheduler-worker-server-localhost.localdomain.out
gc.log
```

**Is your feature request related to a problem? Please describe.**

Some company have no ELK platform to analysis log. Everytime if people want to view log, they need to login Linux server.

**Describe the solution you'd like**

User can view log by UI.

**Describe alternatives you've considered**

In navbar `Monitor`, add a item `Log manage` to sidebar.

在导航栏`监控`中，添加`日志管理`到侧边栏.

In `Log manage`, user can choose master, worker, or alert etc. Then view their log

**Additional context**

![image](https://user-images.githubusercontent.com/15523186/122414737-f28a9580-cfb9-11eb-8417-8a555502cf5d.png)

**Comment by xingchun-chen** [comment]
Good idea, can you contribute a PR

**Comment by lyn916** [comment]
5台40C 256G 物理机做大数据集群，混合部署，数据库使用keeplaived漂移psql，避免不了worker绑定到vip，vip切换后不知道Dolphin有没有问题

**Comment by CalvinKirs** [comment]
> 5台40C 256G 物理机做大数据集群，混合部署，数据库使用keeplaived漂移psql，避免不了worker绑定到vip，vip切换后不知道Dolphin有没有问题

hi,are you replying to the wrong one? By the way, for better communication, please use English, deeply thanks

**Comment by davidzollo** [comment]
@lyn916
no problem, worker doesn't communicate with Database, only Master and API server does. 
By the way,  you can join our Slack space: https://s.apache.org/dolphinscheduler-slack , any language will be OK in Slack.
