### ISSUE TITLE
the dev1.4.0-how to use email alert

### ISSUE THREAD

**Issue by qulibibg** [apache/dolphinscheduler#5662]
t_ds_alert_plugin_instance，this table have no data，the alert change so much compare to 1.3.6

**Comment by qulibibg** [comment]
hi：


First, during the packaging and deployment of the DEV branch, I configured an alarm to be sent by QQ mailbox. This error is sent by WeChat plugin, which is an email alarm. It's hard to understand!


Second: Deployment documentation with no dev alerts.






Thank you very much！



[ERROR] 2021-06-21 11:46:12.376 org.apache.dolphinscheduler.alert.runner.AlertSender:[165] - send alert error alert data id :11,
java.lang.NullPointerException: null
	at java.lang.String.replace(String.java:2240)
	at org.apache.dolphinscheduler.plugin.alert.wechat.WeChatSender.<init&gt;(WeChatSender.java:91)
	at org.apache.dolphinscheduler.plugin.alert.wechat.WeChatAlertChannel.process(WeChatAlertChannel.java:39)
	at org.apache.dolphinscheduler.alert.runner.AlertSender.alertResultHandler(AlertSender.java:162)
	at org.apache.dolphinscheduler.alert.runner.AlertSender.run(AlertSender.java:87)
	at org.apache.dolphinscheduler.alert.AlertServer.runSender(AlertServer.java:147)
	at org.apache.dolphinscheduler.alert.AlertServer.start(AlertServer.java:161)
	at org.apache.dolphinscheduler.alert.AlertServer.main(AlertServer.java:174)
[INFO] 2021-06-21 11:46:12.377 org.apache.dolphinscheduler.alert.runner.AlertSender:[177] - Alert Plugin jlfmail send error : null





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月18日(星期五) 下午4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] the dev1.4.0-how to use email alert (#5662)





 
Hi:
  
Thank you for your feedback, we have received your issue, Please wait patiently for a reply.
 
In order for us to understand your request as soon as possible, please provide detailed information、version or pictures.
 
If you haven't received a reply for a long time, you can subscribe to the developer's email，Mail subscription steps reference https://dolphinscheduler.apache.org/zh-cn/community/development/subscribe.html ,Then write the issue URL in the email content and send question to ***@***.***

**Comment by CalvinKirs** [comment]
you can refer this doc:https://note.youdao.com/s/TC3Q0hDI

**Comment by CalvinKirs** [comment]
please refer https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/alert_spi.html
