### ISSUE TITLE
DataX achieves incremental synchronization,

### ISSUE THREAD

**Issue by zhbdesign** [apache/dolphinscheduler#5667]
DataX achieves incremental synchronization, there are many kinds of data sources and targets. How to quickly synchronize all data sources of dataX

**Comment by CalvinKirs** [comment]
I'm working on plugin the data source. You can quickly extend it later by customizing the plugin.

**Comment by zhbdesign** [comment]
> I'm working on plugin the data source. You can quickly extend it later by customizing the plugin.

https://github.com/apache/dolphinscheduler/issues/5667#issuecomment-864828218

**Comment by zhbdesign** [comment]
> I'm working on plugin the data source. You can quickly extend it later by customizing the plugin.

Is there a prototype to see? When will the work be finished
