### ISSUE TITLE
[Feature][UI] Data source selection drop-down box optimization

### ISSUE THREAD

**Issue by Zzm0809** [apache/dolphinscheduler#5668]
![图片](https://user-images.githubusercontent.com/58576849/122723939-109c1280-d2a6-11eb-8005-22fe09f3e872.png)

![图片](https://user-images.githubusercontent.com/58576849/122724209-4b9e4600-d2a6-11eb-9d4e-8c8b8a419adf.png)

这个下拉框去修改的时候 没有默认展示当前选中的  每次都是从第一条开始往下滑动 
能否优化为 点击下拉框时 就定位在回显的那条数据上

或者

优化修改此类下拉框支持 搜索

**Comment by Zzm0809** [comment]
![图片](https://user-images.githubusercontent.com/58576849/122724322-653f8d80-d2a6-11eb-89ad-09b29b632312.png)

**Comment by CalvinKirs** [comment]
Are you willing to finish it? BTW, please use english.
