### ISSUE TITLE
[Bug][Module Name] Bug title 

### ISSUE THREAD

**Issue by ViceneLee** [apache/dolphinscheduler#5669]
in install_config.conf
the property is 
# run alert machine
# note: list of machine hostnames for deploying alert server
alertServer="node13"

it cant deploy mutil mechine,for example alertServer="node13,node14"
when config alertServer="node13,node14",the alertServer cant start

**Comment by CalvinKirs** [comment]
please refer #5538. Focus on #5538 discussions.

Please fill in the issue title correctly.
