### ISSUE TITLE
The task did not really stop after the task was deleted.（任务删除后任务没有真正停止）

### ISSUE THREAD

**Issue by wuchunfu** [apache/dolphinscheduler#568]
The task task that is running in `Workflow` can still be deleted. The deletion seems to be just deleting on the page. There is no real deletion of the task in the background, and the task does not really terminate after the deletion succeeds. The task on `yarn` is still running.

---
`工作流程` 中正在运行的任务任务仍可以删除，删除好像是只是在页面上删除没有真正的在后台删除任务，并且删除成功后任务没有真正终止，`yarn`  上的任务仍在运行。

**Comment by qiaozhanwei** [comment]
In theory, the final process should be deleted. However, it may happen that the task has been dropped, but the process instance is still running. Now all pauses and stops have no effect. This process requires manual intervention or deletion. We will find ways to optimize this problem, and we welcome the contribution code.

理论上，应该是终态的流程才能被删除。但是可能会遇到任务已经掉了，但是流程实例还在运行的状态，现在所有暂停、停止都已经不起作用。这个流程需要手工干预或者删除。我们会想办法优化这个问题，也非常欢迎贡献代码。
