### ISSUE TITLE
[Feature][SPI-DataSource] DataSources SPI

### ISSUE THREAD

**Issue by CalvinKirs** [apache/dolphinscheduler#5680]
DataSources SPI

**Comment by zhuangchong** [comment]
+1

**Comment by didiaode18** [comment]
+1

**Comment by echohlne** [comment]
+1

**Comment by Narcasserun** [comment]
#5954 There is a data source SPI in my design, which has been verified in production. I wonder if we can communicate

**Comment by Narcasserun** [comment]
@CalvinKirs I have given the design of the data source SPI. #5954   Can I submit this function

**Comment by didiaode18** [comment]
How far has this progressed under the consultation?
