### ISSUE TITLE
[Question] execute task

### ISSUE THREAD

**Issue by oryjk** [apache/dolphinscheduler#5683]
I use mvn build a dolphinscheduler.tar.gz, and run it in docker container, when I execute a task, the instants log error occur

![Uploading image.png…]()

**Comment by oryjk** [comment]
![image](https://user-images.githubusercontent.com/6252789/122957468-8d1d1700-d3b4-11eb-940c-ca1facc0f351.png)

**Comment by oryjk** [comment]
I don’t know where this user 1038850000 comes from, I haven’t created him

**Comment by chengshiwen** [comment]
@oryjk Could you give us more details? It seems that you are doing secondary development on DS.

**Comment by chengshiwen** [comment]
Close the question since no updates for long time
