### ISSUE TITLE
[Bug][Docs] Correct the content for plugin development document

### ISSUE THREAD

**Issue by davidzollo** [apache/dolphinscheduler#5688]
I found that the package name still start with cn. , the package name was wrong, this doc need to be updated
![image](https://user-images.githubusercontent.com/15833811/123195248-71ac2c00-d4da-11eb-95ed-01cf0cffca45.png)

the website doc repository url:
https://github.com/apache/dolphinscheduler-website/blob/master/development/zh-cn/plugin-development.md

By the way, please check other content in plugin-development.md

**Comment by ji04xiaogang** [comment]
I would like to contribute to this.
