### ISSUE TITLE
[Improvement][MasterServer] Start fail fast

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#5690]
**Describe the question**
When a master start up, there might some reasons lead the master start up failure. 
Such as the netty listen address is already in used, the QuartzExecutors starts failure, the masterRegistryClient starts failure. 
Some of these error may cause the master cannot work, so the master need to close.
Currently, the master process will still exist, this is not friendly to ops.

**Which version of DolphinScheduler:**
 -[1.3.6-release]
 -[dev]

**Describe alternatives you've considered**
A clear and concise description of any alternative improvement solutions you've considered.

**Comment by Squidyu** [comment]
Can we try again several times in the startup script

**Comment by CalvinKirs** [comment]
> Can we try again several times in the startup script

Before you start developing, it's best to talk about your solution

**Comment by Squidyu** [comment]
> > Can we try again several times in the startup script
> 
> Before you start developing, it's best to talk about your solution
After we execute start all, we check the actual status of the master. If it fails, we start it again and set a number of retries. If the number does not exceed this number, we can continue to restart

我们执行start-all之后检测一下master实际状态，如果失败了，那就再次启动它，设置一个重试次数，未超过这个次数可以继续重启

**Comment by ruanwenjun** [comment]
> > > Can we try again several times in the startup script
> > 
> > 
> > Before you start developing, it's best to talk about your solution
> > After we execute start all, we check the actual status of the master. If it fails, we start it again and set a number of retries. If the number does not exceed this number, we can continue to restart
> 
> 我们执行start-all之后检测一下master实际状态，如果失败了，那就再次启动它，设置一个重试次数，未超过这个次数可以继续重启

@Squidyu Thanks for your plan, do you mean we check the master state by using a script?
How to check the master's state?

**Comment by oryjk** [comment]
> > > > Can we try again several times in the startup script
> > > 
> > > 
> > > Before you start developing, it's best to talk about your solution
> > > After we execute start all, we check the actual status of the master. If it fails, we start it again and set a number of retries. If the number does not exceed this number, we can continue to restart
> > 
> > 
> > 我们执行start-all之后检测一下master实际状态，如果失败了，那就再次启动它，设置一个重试次数，未超过这个次数可以继续重启
> 
> @Squidyu Thanks for your plan, do you mean we check the master state by using a script?
> How to check the master's state?

add a probe?

**Comment by Squidyu** [comment]
> > > > Can we try again several times in the startup script
> > > 
> > > 
> > > Before you start developing, it's best to talk about your solution
> > > After we execute start all, we check the actual status of the master. If it fails, we start it again and set a number of retries. If the number does not exceed this number, we can continue to restart
> > 
> > 
> > 我们执行start-all之后检测一下master实际状态，如果失败了，那就再次启动它，设置一个重试次数，未超过这个次数可以继续重启
> 
> @Squidyu Thanks for your plan, do you mean we check the master state by using a script?
> How to check the master's state?

In a simpler way, we can directly judge whether the master process exists or not

**Comment by ruanwenjun** [comment]
@oryjk Does this way need to expose some additional metrics?

**Comment by ruanwenjun** [comment]
> > > > > Can we try again several times in the startup script
> > > > 
> > > > 
> > > > Before you start developing, it's best to talk about your solution
> > > > After we execute start all, we check the actual status of the master. If it fails, we start it again and set a number of retries. If the number does not exceed this number, we can continue to restart
> > > 
> > > 
> > > 我们执行start-all之后检测一下master实际状态，如果失败了，那就再次启动它，设置一个重试次数，未超过这个次数可以继续重启
> > 
> > 
> > @Squidyu Thanks for your plan, do you mean we check the master state by using a script?
> > How to check the master's state?
> 
> In a simpler way, we can directly judge whether the master process exists or not

This may not work weel, right now when we start MasterServer, if there are some configuration errors, the master process will still start successfully, but cannot work well.

**Comment by ruanwenjun** [comment]
Closed since the master code has been updated.
