### ISSUE TITLE
[Bug][Spark] When completing data, the time template replacement is not correct.

### ISSUE THREAD

**Issue by wordhardqi** [apache/dolphinscheduler#5692]
![image](https://user-images.githubusercontent.com/13628428/123367328-56a9ec80-d5ac-11eb-9e42-b0135f3c8a13.png)

When building the command for spark task, we use  `ParameterUtils.convertParameterPlaceholders` which is 
```
        if (parameterMap != null && null != parameterMap.get(Constants.PARAMETER_DATETIME)) {
            //Get current time, schedule execute time
            String cronTimeStr = parameterMap.get(Constants.PARAMETER_DATETIME);
            cronTime = DateUtils.parse(cronTimeStr, Constants.PARAMETER_FORMAT_TIME);
        } else {
            cronTime = new Date();
        }
```
This function didn't replace $[yyyy-MM-dd] using schedule time as what we did in shell task. 
I notice this is a function  `ParameterUtils.convertParameterPlaceholders2` which takes `        String cronTimeStr = parameterMap.get(Constants.PARAMETER_SHECDULE_TIME);` into consideration, shall we change to that?

**Comment by wordhardqi** [comment]
The behavior is that if we completing data for spark job, all instances will use the current date time.

**Comment by CalvinKirs** [comment]
good job, we should be consistent.

**Comment by wordhardqi** [comment]
the pr is https://github.com/apache/dolphinscheduler/pull/5695/commits
