### ISSUE TITLE
[show the task instance list][task instance list] improve list task instances

### ISSUE THREAD

**Issue by KingdomTaoF** [apache/dolphinscheduler#5693]
version：1.3.2
question：when doplin run for a long time, there are more and more task instances information store in the mysql. When i click
 the to show task instance list，the api server take a long time to get the information of all task instances (sometimes may take more than 1 minute). How can i improve this?

**Comment by xingchun-chen** [comment]
The problem of slow page access of workflow instance in version 1.3.2，which has been solved in version 1.3.3. https://github.com/apache/dolphinscheduler/pull/4201 ,
Are you sure you have slow page access of task instance?

**Comment by Squidyu** [comment]
What is the order of magnitude of your task instance?

If the number of task instances is too large and the task content is very complex, the task list will be a little slow

**Comment by CalvinKirs** [comment]
There is a lot of related work being done to optimize the API interface. the possibility of revamping this piece is great. You can check the history of the issue, I have mentioned the relevant optimization.
