### ISSUE TITLE
[Bug][UI][DAO]When deleting a user, the accessToken associated with the user should also be deleted 

### ISSUE THREAD

**Issue by echohlne** [apache/dolphinscheduler#5701]
When deleting a user, the accessToken associated with the user should be also deleted
1. create a normal user
![image](https://user-images.githubusercontent.com/52202080/123464117-0029c600-d61f-11eb-84ba-bd4717ca5ada.png)

2. add an accesstoken associated with the user created in the step 1.
 ![image (1)](https://user-images.githubusercontent.com/52202080/123464155-0c158800-d61f-11eb-8c4a-f41c58f7a441.png)  

3. delete the user created in the step 1, then have a look at the accessToken:
![image (2)](https://user-images.githubusercontent.com/52202080/123464249-2c454700-d61f-11eb-8790-2c21ef2fccbb.png)

**Which version of Dolphin Scheduler:**
 1.3.7-release

**Comment by echohlne** [comment]
PR #5697 try to fix this.

**Comment by CalvinKirs** [comment]
close by #5697
