### ISSUE TITLE
[Bug][dev][Root] maven  dependency required version information is missing

### ISSUE THREAD

**Issue by Hermesfuxi** [apache/dolphinscheduler#5704]
**Which version of Dolphin Scheduler:**  [dev]
**Describe the bug**
![image](https://user-images.githubusercontent.com/18678070/123543387-ae00b600-d780-11eb-9b84-af64fd900b31.png)
![image](https://user-images.githubusercontent.com/18678070/123543412-d983a080-d780-11eb-8e61-da4ee24a2c44.png)

**Comment by ruanwenjun** [comment]
@Hermesfuxi Can you try to refresh the dependencies? This doesn't seem to be an issue.

**Comment by CalvinKirs** [comment]
hi,deeply thanks for your contribution, but this is not a problem, you should check if there is a problem with your mvn download (it may need an accelerated download address).

As you can see, we have introduced spring-boot-starter-parent, so there is no need to declare each child dependency.
