### ISSUE TITLE
[Feature][Process node] add sql task in flink process node 

### ISSUE THREAD

**Issue by shuitao** [apache/dolphinscheduler#5713]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/community/development/issue.html when describe an issue.*

**Describe the feature**
since we have lot of data engineer usually work with sql, and we need to use flink to do data collect and process.
we only have 3 ways(java,scala,python) to submit flink job current version(1.3.6), 
a Flink sql development interface will be appreciated.

**Is your feature request related to a problem? Please describe.**
can not submit flink job via sql

**Describe the solution you'd like**
 add flink sql interface.

**Describe alternatives you've considered**
 integrated with flink platform(such as ververica platform)

**Additional context**

**Comment by Xingyeqin** [comment]
We also want to know how to adapt FLINK SQL. If there is a way, please synchronize it with me, thank you very much.
