### ISSUE TITLE
[Question] when i specify two worker,just one success

### ISSUE THREAD

**Issue by zhanggengengen** [apache/dolphinscheduler#5720]
i create a workflow and specify one wokerGroup,this workerGrroup include two wokers,when i running this instance,just one worker run,another no logs and DB just has one task instance record,what's wrong with it

**Comment by chengshiwen** [comment]
@zhanggengengen Once one woker group is specified, only one of workers in the worker group will be chosen to dispatch task. So the description you mentioned is just right

**Comment by zhanggengengen** [comment]
it means that no way to make two workers perform together.my nees are like that when i create a workflow and specify two workers,when i execute it, i want two wokers perform together

**Comment by chengshiwen** [comment]
As for task in the workflow, you can specify the worker group for the task respectively. But for workflow, at least not currently supported
