### ISSUE TITLE
[Bug][CheckStyle] Import checkstyle config file in idea's checkstyle plugin, get a CheckStyleException

### ISSUE THREAD

**Issue by tinyking** [apache/dolphinscheduler#5725]
Import checkstyle config file(https://github.com/apache/dolphinscheduler/blob/dev/style/checkstyle.xml), IDEA throw a CheckStyleException. The information is as follows:

**Which version of Dolphin Scheduler:**
 -[dev]

**Idea info:**
![image](https://user-images.githubusercontent.com/4127712/123929326-50a77780-d9c1-11eb-9252-a9ca268bde74.png)

**Exception info:**
![微信截图_20210630141057](https://user-images.githubusercontent.com/4127712/123929490-716fcd00-d9c1-11eb-9d97-3de6228be1f3.png)

**Comment by ruanwenjun** [comment]
You can use checkstyle version 8.23 in IDEA, it can work well. https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html
![image](https://user-images.githubusercontent.com/22415594/123933950-6ae35480-d9c5-11eb-81ea-da28abfd7c7d.png)

I think we can fix that, the `LineLength ` is not supported under `TreeWalker`. https://github.com/jshiell/checkstyle-idea/issues/458

https://github.com/checkstyle/checkstyle/blob/dc26d0f7597c3ce76e7acbd53fbd4f9651e94c9a/config/checkstyle_checks.xml
