### ISSUE TITLE
Global task flow configuration（全局任务流配置）

### ISSUE THREAD

**Issue by ITriangle** [apache/dolphinscheduler#573]
Tasks within the same task flow have dependencies. How do you configure dependencies between tasks in different task flows? Use priority management for task flow?

---
相同任务流内的任务有依赖关系，那不同任务流之间的任务存在依赖关系怎么配置？使用任务流的优先级管理吗？

**Comment by qiaozhanwei** [comment]
I don't quite understand what you said about the global task flow.
1, there are several tasks in our process (SHELL, MR, Spark, Python, etc.), tasks are directly connected through DAG, a single task can pass local delivery parameters, or global parameters can be passed to local parameters
2, in the same project, if you want to rely on multiple processes, you can rely on the task dependent node

不太明白你说的全局任务流
1，我们的一个流程中有若干个任务（SHELL、MR、Spark、Python等等），任务直接是通过DAG连接起来的，单个任务可以传递局部传递参数，也可以全局参数往局部参数中传递
2，同一个项目中，多个流程之间如果想依赖的话，可以通过任务依赖节点

**Comment by zhuxt2015** [comment]
You should be referring to workflow dependencies. Please look up https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/task/dependent.html
