### ISSUE TITLE
[Feature][service] Submit actions to YARN like Oozie

### ISSUE THREAD

**Issue by Jiezhi** [apache/dolphinscheduler#5731]
**Describe the feature**
DS submit job to YARN like Oozie.

**Describe the solution you'd like**
> Oozie workflow actions start jobs in remote systems (i.e. Hadoop, Pig). Upon action completion, the remote systems callback Oozie to notify the action completion, at this point Oozie proceeds to the next action in the workflow.

Besides Sqoop or other MR jobs,  Oozie would start jobs like normal Java program (not MR job) directly to YARN. Oozie supplys a Yarn ApplicationMaster layer to its jobs. In other words, any jobs running on Oozie would be a YARN application.

But DS run jobs just in local way (please correct me if I'm wrong)，a normal Java program would run in DS worker node, and the node resource is hard to manage like YARN.

May be DS can provide this option when start a job.

**Comment by CalvinKirs** [comment]
The worker just calls the task client to trigger the task, you can search for AbstractYarnTask, which is usually submitted to yarn. k8s will be supported later.

Or, did I misunderstand what you meant?

**Comment by Jiezhi** [comment]
> The worker just calls the task client to trigger the task, you can search for AbstractYarnTask, which is usually submitted to yarn. k8s will be supported later.
> 
> Or, did I misunderstand what you meant?

Maybe AbstractYarnTask can solve my problem, does that mean I need to develop the plugin myself according to [plugin-development](https://dolphinscheduler.apache.org/en-us/development/plugin-development.html).

If there's no official plugin(which is this issue request), I can spend some time on this plugin development.

**Comment by CalvinKirs** [comment]
> > The worker just calls the task client to trigger the task, you can search for AbstractYarnTask, which is usually submitted to yarn. k8s will be supported later.
> > Or, did I misunderstand what you meant?
> 
> Maybe AbstractYarnTask can solve my problem, does that mean I need to develop the plugin myself according to [plugin-development](https://dolphinscheduler.apache.org/en-us/development/plugin-development.html).
> 
> If there's no official plugin(which is this issue request), I can spend some time on this plugin development.

What type of tasks do you need to submit to yarn?
Can't the existing task types fit?

**Comment by Jiezhi** [comment]
> > > The worker just calls the task client to trigger the task, you can search for AbstractYarnTask, which is usually submitted to yarn. k8s will be supported later.
> > > Or, did I misunderstand what you meant?
> > 
> > 
> > Maybe AbstractYarnTask can solve my problem, does that mean I need to develop the plugin myself according to [plugin-development](https://dolphinscheduler.apache.org/en-us/development/plugin-development.html).
> > If there's no official plugin(which is this issue request), I can spend some time on this plugin development.
> 
> What type of tasks do you need to submit to yarn?
> Can't the existing task types fit?

Just a normal Java task, say a helloworld program.

Because we used to deploy tasks to oozie, and some of our jobs are pure Java programs. And we are migrating Oozie workflow to DS now, while  awkwardly found DS cannot submit those jobs to YARN directly like Oozie.

**Comment by CalvinKirs** [comment]
This you need to implement yourself, there is currently no Java type of task.
Later we will change to SPI form, so that it is easier to extend.

**Comment by Jiezhi** [comment]
Ok, thanks.
