### ISSUE TITLE
[Improvement][Doc] update the content of the architecture document 

### ISSUE THREAD

**Issue by davidzollo** [apache/dolphinscheduler#5732]
**Describe the question**
the architecture document is old, please update the content of the architecture document 

Architecture introduction: https://dolphinscheduler.apache.org/en-us/development/architecture-design.html

the doc repository: https://github.com/apache/dolphinscheduler-website/blob/master/blog/en-us/architecture-design.md

**Which version of DolphinScheduler:**
 -[1.3.x]

**Comment by jj551** [comment]
Describe the question
the architecture document is old, I will update the content of the architecture document

Architecture introduction: https://dolphinscheduler.apache.org/en-us/development/architecture-design.html

the doc repository: https://github.com/apache/dolphinscheduler-website/blob/master/blog/en-us/architecture-design.md

Which version of DolphinScheduler:
-[1.3.x]

**Comment by create2world** [comment]
Hello, I think I can do the job. Could you please assign it to me
