### ISSUE TITLE
[Question] Maybe bug in scheduler, run task too slow

### ISSUE THREAD

**Issue by darrkz** [apache/dolphinscheduler#5734]
**Which version of DolphinScheduler:**
 -[1.3.6-binary release]

**Additional context**
centos-release-7-6.1810.2.el7  64bit
openjdk version "1.8.0_275"
Zookeeper version: 3.7.0-e3704b390a6697bfdf4b0bef79e3da7a4f6bac4b, built on 2021-03-17 09:46 UTC
postgresql 11
aliyun

**Requirement or improvement**
I start use dolphinscheduler recently, but I found that , some process is too slow.
I add a shell  task node content a curl test http url.
I found that the time running the task some time too slow , the task log not show the progress very clear

the really shell conten is 

```
curl --connect-timeout 5 -s -I -X HEAD http://xxxxx
```

log:
```
[INFO] 2021-07-01 11:00:02.055  - [taskAppId=TASK-2-5149-5383]:[129] -  -> [/bin/bash]
	2021-07-01 11:00:01
[INFO] 2021-07-01 11:17:47.935  - [taskAppId=TASK-2-5149-5383]:[217] - process has exited, execute path:/data/tmp/dolphinscheduler/exec/process/5/2/5149/5383, processId:26210 ,exitStatusCode:0
```
it cost about 17 minutes to run this task.

How to detect where the time is spend  ??
and reduce the cost of task time  ??

**Comment by darrkz** [comment]
Sorry, I add a rand number generate cost too long time.
but when I use sql node and connect mysql user jdbc, the sql command runnind in shell cli cost 1.9s, in dolphinscheduler cost about 6s...

**Comment by CalvinKirs** [comment]
Can you provide more detailed info?

**Comment by darrkz** [comment]
> Can you provide more detailed info?

Just the log above
MySQL cli run the sql just cost 1.9s and I run the sql for times
in dolphinscheduler, cost 5-6s

**Comment by caishunfeng** [comment]
Hi @darkz1984 this issue will be closed because no update for a long time. You can reopen it and provide more details if need.
