### ISSUE TITLE
[Bug][Datasource] datsource other param check error

### ISSUE THREAD

**Issue by geosmart** [apache/dolphinscheduler#5737]
when add a mysql datasource, I wan't to set connec param with `serverTimezone=Asia/Shanghai`

so add other param with json format `{"serverTimezone":"Asia/Shanghai"}`

but the check rule make the param not working.

the `Pattern PARAMS_PATTER = Pattern.compile("^[a-zA-Z0-9]+$");` make '/' illegal.

**Comment by CalvinKirs** [comment]
Can you submit a PR? The scope of regular filtering can be appropriately relaxed.

**Comment by zhuangchong** [comment]
@geosmart 
Can you submit a PR?

**Comment by geosmart** [comment]
ok,I will fix it in this week
