### ISSUE TITLE
[Improvement][Worker] Improve task process status log

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#5741]
**Describe the question**
In the AbstractCommandExecutor, after the task process executed, it will log the status.
We need to move the log from line 206 to line 227, the `result.getExitStatusCode()` is always 0, because we did not assign value.
https://github.com/apache/dolphinscheduler/blob/2ba569acd028c00c22f4853de7c58251ac72816c/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java#L157-L206

**Which version of DolphinScheduler:**
 -[1.3.6]
 -[dev]

**Comment by tanvimoharir** [comment]
Hi,
I would like to work on this.
Thanks

**Comment by tanvimoharir** [comment]
Hi @ruanwenjun , 
    I am very new to this, I saw your description above but I don't see any logging done on line 256/257 .
    Could you please elaborate a bit more ?
Thanks

**Comment by ruanwenjun** [comment]
@tanvimoharir Sorry, there is something wrong with my description, the log is on line 206.

**Comment by tanvimoharir** [comment]
PR #5776
