### ISSUE TITLE
[Question] Why not sqoop in dolphinscheduler support postgresql

### ISSUE THREAD

**Issue by darrkz** [apache/dolphinscheduler#5742]
**Which version of DolphinScheduler:**
 -[1.3.6-binary]

**Additional context**
I use dolphin to scheduler some job,
But I found that sqoop in dolphinscheduler not support export data to postgresql, but support MySQL.
I found someone mention that not support Oracle because it is an commercial software. But postgresql is!
So why? and how to support it ??

**Comment by davidzollo** [comment]
sorry for reply late, do you solve your problem?

**Comment by robert-guangzhou** [comment]
I also can't understand dolphi why not support pg, but dolphi almost complete 99% code of sqoop pg  .

I have complete pg support in one day after  read all code of dolphi's sqoop task

**Comment by davidzollo** [comment]
> I also can't understand dolphi why not support pg, but dolphi almost complete 99% code of sqoop pg .
> 
> I have complete pg support in one day after read all code of dolphi's sqoop task

good job, can you submit a PR  to the community as a contributor?

**Comment by robert-guangzhou** [comment]
Ok, I will read the contributing guidelines and try to do it

**Comment by robert-guangzhou** [comment]
https://github.com/apache/dolphinscheduler/pull/5963 , it is the first commit of me in github. if something is wrong please tell me
