### ISSUE TITLE
[Feature][Docs] Add link to go to the corresponding github address

### ISSUE THREAD

**Issue by davidzollo** [apache/dolphinscheduler#5745]
Please add this feature for DolphinScheduler official website, the repository : [https://github.com/apache/dolphinscheduler-website](https://github.com/apache/dolphinscheduler-website)

This feature is as pointed by the arrow on the [apache dubbo](https://dubbo.apache.org/en/docs/) in the picture below
![image](https://user-images.githubusercontent.com/15833811/124413611-95e1f580-dd83-11eb-8e1f-8884eb09943e.png)

**Comment by Patil2099** [comment]
I would love to pick this up

**Comment by davidzollo** [comment]
> I would love to pick this up

good, looking forward to your PR

**Comment by songyuequan** [comment]
hello ,   It's been two weeks since last comment, Can I  take it ?

**Comment by davidzollo** [comment]
> hello , It's been two weeks since last comment, Can I take it ?

yes, please submit a PR if you are interested in this issue, thanks

**Comment by RedemptionC** [comment]
![image](https://user-images.githubusercontent.com/17563754/142012799-c7e02ce2-8ecd-4526-af43-b0381a9f27c8.png)
the screenshot above shows that dubbo's website has removed the link?
does  "edit this page"  just link to its website repo?
