### ISSUE TITLE
[Question] datax task not support select hive connection

### ISSUE THREAD

**Issue by darrkz** [apache/dolphinscheduler#5746]
**Which version of DolphinScheduler:**
 -[1.3.6-binary]

**Requirement or improvement**
- not support hive in datax?
I know datax itself support hive and hdfs, but when I use it in dolphinscheduler, I found that, it just support normal jdbc database , not include Hive. So why? and how to support??

**Comment by davidzollo** [comment]
> **Which version of DolphinScheduler:**
> -[1.3.6-binary]
> 
> **Requirement or improvement**
> 
> * not support hive in datax?
>   I know datax itself support hive and hdfs, but when I use it in dolphinscheduler, I found that, it just support normal jdbc database , not include Hive. So why? and how to support??

no special cause, just because contributors not need to use hive. you can use custom template
![image](https://user-images.githubusercontent.com/15833811/125984333-ac6fe395-78b7-4a8f-8cb9-7c54ce28ab24.png)

if you want to implement and contribute it , please leave a message
