### ISSUE TITLE
[Improvement][Monitor] ZookeeperMonitor

### ISSUE THREAD

**Issue by jon-qj** [apache/dolphinscheduler#5748]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/community/development/issue.html when describe an issue.*

**Describe the question**

![image](https://user-images.githubusercontent.com/39773194/124447042-95f9e980-ddb3-11eb-8a70-b18c9d044c42.png)
I think the judgement of this value is not reasonable,   some nodes disconnect from the cluster of zk, but I still get the value of the node's states
all nodes are running well and all the values of  ruok are false
![image](https://user-images.githubusercontent.com/39773194/124449587-30f3c300-ddb6-11eb-920b-6129a8e311ff.png)
stop the zoo1 node  and all the values of  ruok are false
![image](https://user-images.githubusercontent.com/39773194/124449821-68626f80-ddb6-11eb-9969-07563ac945ef.png)

**What are the current deficiencies and the benefits of improvement**
I think  we can catch the java.net.ConnectException, if it is thrown, we can return the init value. 

**Which version of DolphinScheduler:**
 -[1.3.6-preview]

**Describe alternatives you've considered**
Could someone please explain it  for me clearly?,Maybe the value of ruok has other  
meanings

**Comment by davidzollo** [comment]
Will we show a  message like “can't connect to zookeeper server” on the front-end be better?

**Comment by jon-qj** [comment]
> Will we show a message like “can't connect to zookeeper server” on the front-end be better?

That will be great.In my opinion,I don't care if the running state of each node of the zk cluster is 'imok',as long as some nodes don't disconnect from the cluster,I will get to know that all of the monitoring indexes.

**Comment by davidzollo** [comment]
> > Will we show a message like “can't connect to zookeeper server” on the front-end be better?
> 
> That will be great.In my opinion,I don't care if the running state of each node of the zk cluster is 'imok',as long as some nodes don't disconnect from the cluster,I will get to know that all of the monitoring indexes.

good, are you interested in trying to implement it?

**Comment by jon-qj** [comment]
> > > Will we show a message like “can't connect to zookeeper server” on the front-end be better?
> > 
> > 
> > That will be great.In my opinion,I don't care if the running state of each node of the zk cluster is 'imok',as long as some nodes don't disconnect from the cluster,I will get to know that all of the monitoring indexes.
> 
> good, are you interested in trying to implement it?

My pleasure,I try to implement it.

**Comment by CalvinKirs** [comment]
close by #5766
