### ISSUE TITLE
udf resources dir error

### ISSUE THREAD

**Issue by SuperHeroBigData** [apache/dolphinscheduler#5751]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
my conf/common.properties is this.
![image](https://user-images.githubusercontent.com/73939396/124475353-34964280-ddd4-11eb-8f94-7170b04a2c0f.png)
![image](https://user-images.githubusercontent.com/73939396/124475374-3b24ba00-ddd4-11eb-955d-7de8877e1b44.png)
but when  i use this udf resource。error happened
![image](https://user-images.githubusercontent.com/73939396/124475483-5a234c00-ddd4-11eb-83f1-a0ca38af1351.png)
dir locate adds the defaultFs。
how to solve this error。
thank you 

**To Reproduce**
Steps to reproduce the behavior, for example:

**Expected behavior**

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by zhuangchong** [comment]
@SuperHeroBigData 

![image](https://user-images.githubusercontent.com/37063904/125293216-c9111f80-e355-11eb-98b0-21012dce1369.png)

Check through the log that there are two dolphinscheduler directories in the hdfs path. Is there any problem in this part?

Try fs.defaultFs=hdfs://hadoop-slave-1:8020

**Comment by CalvinKirs** [comment]
No response, I will close it. If you still have problems, you can reopen it.
