### ISSUE TITLE
[Improvement][TaskKillProcessor] command 'pstree'

### ISSUE THREAD

**Issue by jon-qj** [apache/dolphinscheduler#5753]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/community/development/issue.html when describe an issue.*

**Describe the question**

when I killed the task,I found some problems.
![image](https://user-images.githubusercontent.com/39773194/124534406-c9d21f00-de46-11eb-912d-2ca9fa92da4a.png)
my centos system has no command 'pstree' because of minimize installing.However I coundn't find out the introduction shown on the deployment document.

![image](https://user-images.githubusercontent.com/39773194/124534189-4f090400-de46-11eb-8802-f92ae8d837ac.png)

**What are the current deficiencies and the benefits of improvement**

**Which version of DolphinScheduler:**
 -[1.3.6]

**Describe alternatives you've considered**
I continue to find out the reason why the logs show ' Cannot run program "pstree": error=2, No such file or directory'

**Comment by davidzollo** [comment]
if your machine didn't have the pstree command,  you should install `pstree` through the following  ways:
1. on Mac OS:
      brew install pstree
2. on Fedora/Red Hat/CentOS
      yum -y install psmisc
3. on Ubuntu/Debian
     apt-get install psmisc

**Comment by jon-qj** [comment]
Ok,I have completed it.Thanks for replying back.
 
 
 
 
 
 
 
 
 

  -- 
 
 
 发自新浪邮箱客户端 
 
 
  
  在 7月7日 20:21，dailidong ***@***.***> 写道： 
   
  if your machine didn't have the pstree command, you should install pstree through the following ways: 
   
   on Mac OS:
 brew install pstree 
   on Fedora/Red Hat/CentOS
 yum -y install psmisc 
   on Ubuntu/Debian
 apt-get install psmisc
