### ISSUE TITLE
[Question] Sqoop  is  sucess  ,but  dolphinscheduler   returned failure

### ISSUE THREAD

**Issue by yangshiza** [apache/dolphinscheduler#5767]
**Describe the question A clear and concise description of what the question is.**when I use  shell  tool  to run the  sqoop ,  the shell log doesn't see  any  failure,but  the   DAG said that   the sqoop   was  failed.
And dolphinscheduler-worker.log   say the yarn job  of  sqoop     is  failed.but  the yarn controller  say   this  job  is   success.
How can I fix  this   problem  ?   THX 
![yarnjob](https://user-images.githubusercontent.com/85532472/124848957-7095f700-dfd0-11eb-941c-6661ae897a31.png)

**Which version of DolphinScheduler**: -[1.
![微信图片_20210708093228](https://user-images.githubusercontent.com/85532472/124848521-9c64ad00-dfcf-11eb-9885-18d3ce1d3dbd.png)
3.2]

**Comment by yangshiza** [comment]
dolphinscheduler-worker.log

**Comment by yangshiza** [comment]
![Uploading 20210708.png…]()
dolphinscheduler-worker.log

**Comment by xingchun-chen** [comment]
Unable to view your worker log

**Comment by yangshiza** [comment]
> Unable to view your worker log

![20210708](https://user-images.githubusercontent.com/85532472/125006035-c1205980-e08f-11eb-98b7-52292df9dfc6.png)

**Comment by yangshiza** [comment]
> Unable to view your worker log
full worker log  ,all the sqoop return   failed
[dolphinscheduler-worker.log](https://github.com/apache/dolphinscheduler/files/6787944/dolphinscheduler-worker.log)

**Comment by zhuangchong** [comment]
@yangshiza 

Viewing through the log, the worker reports an error when obtaining the task yarn status, please check whether the yarn address configuration is correct in the common.properties file.

**Comment by yangshiza** [comment]
I change  the yarn  config   of  common.properties ,but not all sqoop jobs  sucesss,only one  job failed  without  any log 
![1626858582(1)](https://user-images.githubusercontent.com/85532472/126463293-7ec04991-695a-47ec-9bb6-51e62fde2e38.png)
![1626858542(1)](https://user-images.githubusercontent.com/85532472/126463304-772b5f0a-6ebb-4102-9031-20bccbabc2b0.png)
![1626858372(1)](https://user-images.githubusercontent.com/85532472/126463307-71c2a599-f3a2-4dbd-b656-40558175758c.png)
![1626858338(1)](https://user-images.githubusercontent.com/85532472/126463311-e96b8432-3354-4ac6-bf7e-26f2ef0b490c.png)
![1626858268(1)](https://user-images.githubusercontent.com/85532472/126463314-fd487d9a-1de1-4178-b84b-a5d529ddf8ea.png)

**Comment by zhuangchong** [comment]
Your exception is related to the hadoop version;
The task has no logs. Which version of dolphin does the problem occur in?
Fixed the problem of the first version of the task log in version 1.3.5.

**Comment by yangshiza** [comment]
The hadoop  version used  CDH 6.3.2;
the dolphinscheduler  version  is 1.3.6;
