### ISSUE TITLE
[Question][Process import] import process with resources got some exception

### ISSUE THREAD

**Issue by zhujian86** [apache/dolphinscheduler#5772]
I imported processes with resources from another DS, but an exception occured.
The exception caused by the differences between the IDs in the table "t_ds_resources" on the two environment.
![图片](https://user-images.githubusercontent.com/57431994/124878675-f29d1480-dffe-11eb-857e-a6c6ed623959.png)

**Comment by xingchun-chen** [comment]
The resource id referenced by workflow needs to exist in  t_ds_resource table

**Comment by zhujian86** [comment]
> 
> 
> The resource id referenced by workflow needs to exist in t_ds_resource table

Export / Import does not support by the resource manager, the only method is add new resources manually.
Then, the ids are not same.
