### ISSUE TITLE
[Bug][SQL] Log missing

### ISSUE THREAD

**Issue by gaoyu2016** [apache/dolphinscheduler#5777]
ds 1.3.4版本，
sql节点，操作hive数据源，语句：
insert overwrite table xxx partition(dt='2021-07-08')
select ...

查看task日志，日志缺失，只有开始日志，没有结束日志，且在日志中看不到applicationid，无法在yarn web ui查看。
![image](https://user-images.githubusercontent.com/29685418/125046158-55aaac00-e0d0-11eb-8011-4ee6059c0106.png)

**Comment by Tandoy** [comment]
可以看dolphinscheduler-worker.log下这个taskAppId的日志

**Comment by CalvinKirs** [comment]
PR #5783 has been submitted so far, we will release it in 1.3.7, you can verify it first.

**Comment by gaoyu2016** [comment]
意思是在1.3.7修复了是吗？

**Comment by davidzollo** [comment]
yes, you can cherry pick this PR #5783 and test it
