### ISSUE TITLE
[Feature][Task Instance List] Add yarn applicationID To list  And  UI layout optimization

### ISSUE THREAD

**Issue by Zzm0809** [apache/dolphinscheduler#5784]
1. Add the field of applicationid in the list of task instances
example:
![image](https://user-images.githubusercontent.com/58576849/125098247-72afa100-e109-11eb-9f3c-31ccf0b63fac.png)

2.[UI]
 When modifying and selecting datasource, it supports searching and locating keywords quickly
example:
![image](https://user-images.githubusercontent.com/58576849/125098499-a5f23000-e109-11eb-9619-57637af509ea.png)
![image](https://user-images.githubusercontent.com/58576849/125098538-ae4a6b00-e109-11eb-803a-c0c893fa2584.png)

**Comment by ruanwenjun** [comment]
I think the first issue might need some discussion about how we should present if the task is not running on yarn, or if the task might run on another platform.

**Comment by CalvinKirs** [comment]
> I think the first issue might need some discussion about how we should present if the task is not running on yarn, or if the task might run on another platform.

Maybe we should specify a field, its meaning is like the applicationId on yarn, which represents the task id of the resource scheduler. In addition, we may need to make relevant distinctions, representing what kind of scheduling platform is submitted to, such as yarn, or it in the future K8s and so on. What do you think?

**Comment by CalvinKirs** [comment]
A great topic, but it is best to submit a PR after the discussion. In addition, this task can be split into two PRs.

**Comment by ruanwenjun** [comment]
> > I think the first issue might need some discussion about how we should present if the task is not running on yarn, or if the task might run on another platform.
> 
> Maybe we should specify a field, its meaning is like the applicationId on yarn, which represents the task id of the resource scheduler. In addition, we may need to make relevant distinctions, representing what kind of scheduling platform is submitted to, such as yarn, or it in the future K8s and so on. What do you think?

Agree with you, we can use a compound struct to store.

**Comment by Zzm0809** [comment]
Now there is a corresponding field to store appid ,

in table t_ds_task_instance ;   field : app_link


Now it stores, for example :   application_12131_121212
