### ISSUE TITLE
[Improvement][Code Style] Fix code format

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#5785]
**Describe the question**
You can find the DolphinScheduler's code style related configuration [here](https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html).
Currently, there is a lot of old code that doesn't follow this rule, you can try to format them. 
This is an easy work, you can use IDEA to do this.

**Which version of DolphinScheduler:**
 -[dev]

**Comment by MonsterChenzhuo** [comment]
@ruanwenjun Hello, I think I can do the job. Could you please assign it to me

**Comment by ruanwenjun** [comment]
@MonsterChenzhuo Hi, I assign this issue to you, look forward to your contribution.

**Comment by ruanwenjun** [comment]
@MonsterChenzhuo Hi, is there any progress, here are already other people working on this issue.

**Comment by lvshaokang** [comment]
I can try this issue，could you assign it to me?

**Comment by JYInMyHeart** [comment]
Does this issue fixed?

**Comment by ruanwenjun** [comment]
> Does this issue fixed?

I execute the checkstyle maven plugin, it executes success, I will close this issue.
