### ISSUE TITLE
[Feature][New task node] Loop node that specifies the sleeping time

### ISSUE THREAD

**Issue by huyaro** [apache/dolphinscheduler#5791]
**Describe the feature**
The scenario is as follows: the system automatically runs the batch process, the processing time of each node is not fixed every day, you need to go to the database to query the status of a node regularly, and after the node is completed, it will flow to "successful execution" according to the [condition node] configured by the DAG, and then The DAG instance ends. If the state is not the state I defined, then go to the "failure execution" of [condition node], and check again after the end of the sleep.
场景如下：系统自动跑批流程，每个节点每天的处理时间不固定，需要去数据库定时查询某个节点状态，并且在节点完成后按DAG配置的[条件节点]流转到“成功执行”，然后DAG实例结束。 如果状态不是我定义的状态，那么就走向[条件节点]的“失败执行”，沉睡结束后再次检测。

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
- Create a new sleeping node, which can point to an existing status check node
- 新建一个沉睡结点，可指向当前已存在的状态检查节点

**Describe alternatives you've considered**

**Additional context**
I don’t know much about the system yet. Is there a way to combine this function with existing nodes?

**Comment by davidzollo** [comment]
I think you can read the source code about the `how did the task node works`, in my opinion, this feature is not very common
