### ISSUE TITLE
[Bug][Master] auto create a same process

### ISSUE THREAD

**Issue by HeChuanXUPT** [apache/dolphinscheduler#5799]
**Describe the bug**
find same auto-created processes in system.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. manual create some processes.
2. use API to create schedule with processDefinitionId=5
3. auto create one more process, the same process
4. Click on process(3 and 4) Cron manage, find the same url, display the same infomation.
  http://127.0.0.1:12345/dolphinscheduler/ui/#/projects/definition/list/timing/5
5. Click on process(3 and 4) name, find the same url, 
http://127.0.0.1:12345/dolphinscheduler/ui/#/projects/definition/list/5

尝试调用API创建定时任务, 调用返回成功之后, 发现多了一个任务出来, 之前只有一个的, 
点击任务配置或者点击任务的定时任务, 2个任务进入的是相同的url, 是一模一样的. 感觉哪里重复了

**Screenshots**
![image](https://user-images.githubusercontent.com/5425689/125219905-532a9b00-e2f8-11eb-9f82-b6b508d5ef01.png)
![image](https://user-images.githubusercontent.com/5425689/125220140-c7fdd500-e2f8-11eb-81f9-d01fc88db2a4.png)

**Which version of Dolphin Scheduler:**
docker deploy, apache/dolphinscheduler:latest

docker images:
apache/dolphinscheduler latest 971ed8486b5d 2 months ago 393MB

**Comment by caishunfeng** [comment]
Hi @HeChuanXUPT, I think it had been fixed in the latest version, you can check it again and reopen this issue if need.
