### ISSUE TITLE
[Question]  Shell start job shut down after 1 min, but without reason

### ISSUE THREAD

**Issue by Dipsy-chen** [apache/dolphinscheduler#5806]
The  shell job starts and run normally,but shut down after 1 min without reason, not error log or other msg, just fault .
when I use the same command to execute on Linux, everything is normal , 
Why ? 
< java -cp  xxx  xx.jar>

**Comment by zhuangchong** [comment]
Is there more detailed exception information in the worker log?
You can issue task log context.

**Comment by davidzollo** [comment]
has this issue been solved or not? I will close this issue, please reopen it if not resolved
