### ISSUE TITLE
[Improvement][Dao UT] Use h2 in UT

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#5807]
**Describe the question**
Currently, we use database configured at `datasource.properties`  in unit test.
This is inconvenient and against the principles of unit test, unit test should run successfully at every environment. 
We can use h2 datasource in unit test(https://www.linkedin.com/pulse/unit-testing-using-h2-in-memory-db-raghunandan-gupta).

**Which version of DolphinScheduler:**
 -[dev]

**Comment by CalvinKirs** [comment]
Sounds good to me .

**Comment by SivaTharun** [comment]
@CalvinKirs can i work on this issue.

**Comment by CalvinKirs** [comment]
> @CalvinKirs can i work on this issue.

Of course you are welcome to contribute. You can design first, and then we discuss and start development

**Comment by davidzollo** [comment]
> @CalvinKirs can i work on this issue.

hi, do you have any idea about how to implement it? thx

**Comment by SivaTharun** [comment]
@CalvinKirs @dailidong we can use he embedded in memory database for integration tests, we can follow this [document](https://www.baeldung.com/spring-boot-h2-database), which shows on how to setup h2 database integration.

Also we can construct the tables by including the DDL in `schema.sql` in `src/test/resources` folder.
we can preload the data too , inside the h2 tables, by including the `data.sql` file in `src/test/resources` folder.

This would help us to create, load and drop tables inside h2 database, and this execution will takes place for every integration test as well as mapper/repository test.

**Comment by davidzollo** [comment]
> @CalvinKirs @dailidong we can use he embedded in memory database for integration tests, we can follow this [document](https://www.baeldung.com/spring-boot-h2-database), which shows on how to setup h2 database integration.
> 
> Also we can construct the tables by including the DDL in `schema.sql` in `src/test/resources` folder.
> we can preload the data too , inside the h2 tables, by including the `data.sql` file in `src/test/resources` folder.
> 
> This would help us to create, load and drop tables inside h2 database, and this execution will takes place for every integration test as well as mapper/repository test.

good job, I have read this document,  I think we don't need the spring-boot-starter-data-jpa dependencies, you can have a try, welcome to join Slack workspace through invitation url: https://s.apache.org/dolphinscheduler-slack,  and you also can send mail to dev@dolphinscheduler.apache.org if you meet any problem.  
I'm looking forward to your good news!

**Comment by davidzollo** [comment]
BTW, I have tried h2's embedded method some months ago in my local environment and it works, I'm so glad to see you want to implement it, good luck!

**Comment by davidzollo** [comment]
@SivaTharun hi guys, any progress? or do you meet any problem?

**Comment by SivaTharun** [comment]
@dailidong i have started working on this issue, and the PR would be ready in a few days.

**Comment by ruanwenjun** [comment]
@SivaTharun Hi, since this issue is taking too long, I have submitted a pr #6500
