### ISSUE TITLE
[Question] How to rolling upgrade the system while not perceptible to task

### ISSUE THREAD

**Issue by wangmingzhiJohn** [apache/dolphinscheduler#5812]
**Describe the question**
The DS system is deployed in cluster way. When I update the code and prepare to apply it on the current deployment, I should stop all services and then restart them by using new packages. Although the time gap of update is short, the system is still unavailable during the process.

So, I have two questions. First, if a task is not finished when I start to do stop-restart system, what will happen to this task.? Second, if there is any solution to make the system always available even if during the update or upgrade time? Maybe we can start a new whole system and change route to the new system, then shutdown the old system

**Which version of DolphinScheduler:**
 -[1.3.6-release]

**Comment by davidzollo** [comment]
Rolling upgrade is a problem to be considered in the future, and there is no energy to implement it now

**Comment by davidzollo** [comment]
>First, if a task is not finished when I start to do stop-restart system, what will happen to this task

this task will re-run
