### ISSUE TITLE
[Question] Can I change global params while task executing?

### ISSUE THREAD

**Issue by wangmingzhiJohn** [apache/dolphinscheduler#5819]
**Describe the question**
There is a demand in my project that I need to add a new global parameter during the task execution so that the successor can get the new global parameter. That demand is in order to make successor be able to obtain the output of pretask as its input. I had a try, but the change of global parameter couldn't influence the successor.
So, how to achieve this goal?

**Which version of DolphinScheduler:**
 -[1.3.6-release]

**Comment by wangmingzhiJohn** [comment]
Emm, I found another way to transmit data between from one to another which does not use global-parameter

**Comment by davidzollo** [comment]
Changing params is not supported , but dev branch has implemented the pretask params been delivered to the next task

**Comment by wangmingzhiJohn** [comment]
@dailidong Could you show me which commit implements this feature?

**Comment by davidzollo** [comment]
> @dailidong Could you show me which commit implements this feature?

you can search through 'global param', not only one PR 
https://github.com/apache/dolphinscheduler/pulls?q=is%3Apr+global+param
