### ISSUE TITLE
incompatible decode and encode between 1.3.6  and 1.3.3

### ISSUE THREAD

**Issue by szwxw** [apache/dolphinscheduler#5823]
Well, in 1.3.6 version and conext added to NettyEncoder & NettyDecoder class。but i got some proplem when upgrade master to 1.3.6 but left worker server in 1.3.3.

when master-sever and worker-server runs  in different env. we got the fellow error.

[ERROR] 2021-07-14 16:00:22.022 org.apache.dolphinscheduler.remote.handler.NettyServerHandler:[153] - exceptionCaught : java.lang.IllegalArgumentException: illegal packet [magic]69
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: illegal packet [magic]69

please help us to fixed this. thank you

**Comment by szwxw** [comment]
and this is  another error .

[ERROR] 2021-07-14 16:44:32.302 org.apache.dolphinscheduler.remote.handler.NettyServerHandler:[153] - exceptionCaught : java.lang.IllegalArgumentException: illegal protocol [version]10
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: illegal protocol [version]10

**Comment by ruanwenjun** [comment]
@szwxw It seems that the protocol between 1.3.3 with 1.3.6 has changed. You can check with the `Command`.
