### ISSUE TITLE
[Improvement][Web] Improve the selection style in dag edit dialog

### ISSUE THREAD

**Issue by echohlne** [apache/dolphinscheduler#5830]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
When we want to select all or part of the text in the input box, because the selected background color is too similar to the original background color, users often think that the text cannot be selected

![db6deb90d479ae54c0a0f89a0c8a1c838bc149d4](https://user-images.githubusercontent.com/52202080/125908608-abec7fec-2c45-47f4-a8ba-a23a4a60abbf.gif)

**Which version of DolphinScheduler:**
latest dev branch

**Describe alternatives you've considered**
A clear and concise description of any alternative improvement solutions you've considered.

**Comment by ruanwenjun** [comment]
Can this be considered as user experience issue?
You can add this issue to #5494
