### ISSUE TITLE
[Improvement][server]  Support two parameters related to task  for the rest of type of tasks.

### ISSUE THREAD

**Issue by calvinjiang** [apache/dolphinscheduler#5852]
**Describe the question**

Next issue is:https://github.com/apache/dolphinscheduler/issues/5773
In that issue ,I've implemented the function for the shell task, but the other type of tasks doesn't still support this function.

Now  need to provide these two system parameters  to support  the rest of type of tasks..

**What are the current deficiencies and the benefits of improvement**

**Which version of DolphinScheduler:**
-[dev]

**Describe alternatives you've considered**

**Comment by CalvinKirs** [comment]
good,looking forward you submit PR.
