### ISSUE TITLE
[Question] Create Hive data source. Connection failed using HiveServer2 HA ZooKeeper  

### ISSUE THREAD

**Issue by gaohan0524** [apache/dolphinscheduler#5855]
I used DolphinScheduler1.3.6 to create a Hive data source. I used HiveServer2 HA ZooKeeper to connect to it and failed   

**Which version of DolphinScheduler:**
 -[1.3.6]

**Additional context**
Failure error display：
![image](https://user-images.githubusercontent.com/52993946/126254828-06d60df8-f70a-46ec-8a8c-4ac5e4b60620.png)

error log：
![image](https://user-images.githubusercontent.com/52993946/126254895-750eeacf-a501-418d-b7db-ed55a7bef808.png)

Which parameter did I fill in incorrectly? help~~ thanks！

**Comment by CalvinKirs** [comment]
Sorry. Here is because of the other parameter verification rules, we have modified this problem. You can refer to #5785. We will release it in 1.3.7.
