### ISSUE TITLE
[Bug][dao] Unreachable logic exists in the code that generates the workflow instance 

### ISSUE THREAD

**Issue by Lucaszlei** [apache/dolphinscheduler#5856]
**Describe the bug**
org.apache.dolphinscheduler.dao.ProcessDao#constructProcessInstance
Constants.CMDPARAM_SUB_PROCESS、Constants.CMDPARAM_RECOVER_PROCESS_ID_STRING，The two Constants actually represent the same value, so the logical branch of cmdParam.containsKey(Constants.cmdParam_Sub_Process) is not reacheable

**Screenshots**
![图片](https://user-images.githubusercontent.com/56599784/126255109-ff7a0dc9-68b8-4f14-b57b-8c35144c16a1.png)

**Which version of Dolphin Scheduler:**
 -[1.2.1]

**Comment by ruanwenjun** [comment]
@SunnyZ-L The first alphabet of the two constants words should be different, you can check again.

**Comment by SunnyZ-L** [comment]
> 
> 
> @SunnyZ-L The first alphabet of the two constants words should be different, you can check again.

In version 1.2.1 of Branch, the values of the two constants are the same
![图片](https://user-images.githubusercontent.com/56599784/126437513-5b36ccec-6f14-4640-aeb0-a0344d31e253.png)

**Comment by Lucaszlei** [comment]
> 
> 
> @SunnyZ-L The first alphabet of the two constants words should be different, you can check again.

Sorry, I ignored case yesterday

**Comment by SunnyZ-L** [comment]
Not a problem
