### ISSUE TITLE
The query can not echo the content just checked

### ISSUE THREAD

**Issue by wangsvip** [apache/dolphinscheduler#5857]
1.我经常会查询某个时间点杀掉的一批任务，方便我重跑数据，查完之后，点进去查看某个任务，然后点击浏览器后退按钮，之前的查询记录都没有了，为什么没有回显的功能？？？？现在是1.2的版本，之前1.0的版本是有这个功能的，为什么要做的这么烂？？？我从1.0就开始提bug了。这种基本的交互功能做不好？我按条件查询的是一批任务，每次查看当中的某个任务后，就没了？？？

2.还有分页每次都是默认10条，你为什么一点要限死10条？？？我选了50条之后，点击查看某个任务后，再点击浏览器后退按钮，又还原到了10条，假如我是在第2分页查看的，后退后就变成从第一页了，这什么功能啊？？能不能优化下体验？？起码要做一个用户设置功能，我当前用户设置为50条，最大不超过200条，每次我登陆后都是50条，而不是我还要去选！！！！我选了第2页，为什么后退会变为第一页？？？

3.架构设计上写的如果任务变为”需要容错“后面资源充足了调度会自己提交任务， 现在遇到的是任务变为”需要容错“就卡死了，调度资源充足的情况下也不会自己提交了，这种BUG要赶紧修复！一批任务需要容错就挂起了，每次都要记下任务名字手动杀了在重新手动提交， 你不觉得很累吗？

1. I often query a batch of tasks that were killed at a certain point in time, so that I can rerun the data. After checking, click in to view a task, and then click the browser back button. The previous query records are gone, why not return Significant function? ? ? ? It is now version 1.2. The previous version 1.0 had this function. Why is it so bad? ? ? I have been mentioning bugs since 1.0. Is this basic interactive function not doing well? What I am querying is a batch of tasks according to the conditions. Every time I check a certain task, it disappears? ? ?

2. There are also 10 default pages each time, why do you have to limit 10 entries at one point? ? ? After I selected 50 items, I clicked to view a certain task, and then clicked the browser back button to restore to 10 items. If I view it on the second page, it will be from the first page after backing up. What is this? Function? ? Can you optimize the experience? ? At least one user setting function is required. My current user setting is 50, and the maximum is not more than 200. Every time I log in, it is 50, not I have to choose! ! ! ! I chose page 2, why does the back turn to the first page? ? ?

3. It is written in the architecture design that if the task becomes "need to be fault-tolerant" and the resources are sufficient, the scheduling will submit the task by itself. Now what is encountered is that the task becomes "needed to be fault-tolerant" and it will be stuck, and the scheduling resource will not be sufficient. I will submit it by myself, this kind of BUG needs to be fixed quickly! A batch of tasks need to be fault-tolerant and hang up. You have to write down the task name and manually kill it and submit it again. Don't you feel tired?

**Comment by CalvinKirs** [comment]
What you said is a point worth optimizing, which is very good. But all functions are constantly iterating. Participating in open source requires everyone's efforts. If you feel that it is not good enough, you are welcome to submit a PR. Not just being a Talker.

**Comment by davidzollo** [comment]
@wangsvip, could you submit PRs to solve these issues?

**Comment by wangsvip** [comment]
> @wangsvip, could you submit PRs to solve these issues?

No, there are so many bugs, I can give you three right now

**Comment by davidzollo** [comment]
Can you paste the master and worker runtime log when the task shows "need to be fault-tolerant" ?  which version?

**Comment by caishunfeng** [comment]
This issue was long time to update, so it will be closed. You can reopen it if need.
