### ISSUE TITLE
[Feature][FlinkX Plugin] Add FlinkX plugin (based on flinkx local mode)

### ISSUE THREAD

**Issue by jon-qj** [apache/dolphinscheduler#5864]
*For better global communication, please give priority to using English description, thx! *

**Describe the feature**
This issue shows the discussion on the feasibility of using flinkx plugin.
I have implemented the basic function up to now.And I'm not sure if it is an effective measure by using DS to manage the real-time task.

**Describe alternatives you've considered**

**Additional context**
1、flinkx plugin's icon
![image](https://user-images.githubusercontent.com/39773194/126271361-1e042e4f-eadb-46b5-af6e-7d1ff62cdd3c.png)
2、add columns of source table
![image](https://user-images.githubusercontent.com/39773194/126272444-b95bead4-92f3-43a1-94d2-c548e80d950e.png)
![image](https://user-images.githubusercontent.com/39773194/126272795-862cc527-8bbc-4a5b-a01b-8af7874c9f72.png)
3、or add columns by using sql statement 
![image](https://user-images.githubusercontent.com/39773194/126273678-9a4ad3bb-b787-47d1-8e51-61f849f9fdba.png)

4、other config
![image](https://user-images.githubusercontent.com/39773194/126273581-b0cf5124-c00d-456a-988d-dca7863dd619.png)

here is a brief explaining.

**Comment by davidzollo** [comment]
I have a question about why only support local mode?
![image](https://user-images.githubusercontent.com/15833811/126374518-6625bdf4-24aa-4d22-a049-79f22893c474.png)

**Comment by geosmart** [comment]
> I have a question about why only support local mode?
> ![image](https://user-images.githubusercontent.com/15833811/126374518-6625bdf4-24aa-4d22-a049-79f22893c474.png)

flinkx support local mode for debug , just run flinkx in worker node

**Comment by geosmart** [comment]
@jon-qj  waiting your flinkx pr!!
I have impl a FlinkXTask in the dolphinscheduler-api, but no front-end impl, we use api to create and run a flinkx task

**Comment by jon-qj** [comment]
> I have a question about why only support local mode?
> ![image](https://user-images.githubusercontent.com/15833811/126374518-6625bdf4-24aa-4d22-a049-79f22893c474.png)

Because when I start using standalone or other modes,I'm not sure if it is necessary to get the execution logs of Flink cluster's tasks,and it can be shown on the DS's web.Becides,DS can not monitor the status of task we submit when using standalone mode.

**Comment by jon-qj** [comment]
> @jon-qj waiting your flinkx pr!!
> I have impl a FlinkXTask in the dolphinscheduler-api, but no front-end impl, we use api to create and run a flinkx task

My pleasure.

**Comment by geosmart** [comment]
related pr  #5870

**Comment by didiaode18** [comment]
I think the cluster mode is better to hand over to yarn management

**Comment by jon-qj** [comment]
> I think the cluster mode is better to hand over to yarn management

Yep.The real-time tasks differ from the offline tasks on yarn mode,we can get the running states of offline tasks correctly,even easily,but we can't be sure if the real-time tasks' running states are STOP or RUNNING.
