### ISSUE TITLE
[Question] Does DS support dynamic expansion/reduction?

### ISSUE THREAD

**Issue by wangmingzhiJohn** [apache/dolphinscheduler#5866]
On the index of DS website, I found this instruction called "Support dynamic expansion and reduction of master and worker".
However, in document of Expansion/Reduction, the method of achieving  the goal needs to restart all services which seems like not dynamic at all.
So, my question is whether DS support dynamic way to expand or reduce nodes?
![image](https://user-images.githubusercontent.com/84900511/126304481-11457e87-54c8-4df7-b415-64d65d049cfc.png)

**Which version of DolphinScheduler:**
 -[1.3.6]

**Comment by ruanwenjun** [comment]
@wangmingzhiJohn When you add worker or master to the exist cluster, you don't need to restart the cluster.

**Comment by davidzollo** [comment]
> @wangmingzhiJohn When you add worker or master to the exist cluster, you don't need to restart the cluster.

Yes, when adding, only need to start the service on the new server, and only need to stop the service of the server to be stopped

**Comment by wangmingzhiJohn** [comment]
@dailidong  @ruanwenjun  So, according to documents, why we need to execute stop-all.sh/start-all.sh which may influence services on other nodes
![image](https://user-images.githubusercontent.com/84900511/126422957-50b0c3f9-2c43-4586-9d6c-467eadb5b7a4.png)

**Comment by ruanwenjun** [comment]
@wangmingzhiJohn The docs means you can use the stop-all.sh or start-all.sh to scaled-up or scaled-down the cluster.
In most case, we don't deploy all service on one machine, so you can directly use the shell. If you deploy multiple instances on one machine, you can manual start or stop the instance.

**Comment by wangmingzhiJohn** [comment]
@ruanwenjun I can't get the point. You mean these scripts can scaled-up the cluster. For example, there is 2 workers in cluster and I need to add 1. In order to let the system know that a new worker is added, I need to add a new ip to install_config.conf. And the new config file should be consistent with that on other nodes(according to doc).
As I understand it, indeed, you just need to operate on the new server to add the node into cluster and restart service. But in the start-all.sh/stop-all.sh, it will ssh to every node to restart the service whatever master or worker. I think this behavior can not be called 'dynamic scaling' because it make all services perceptive to the expansion. They all will be restart not only the service on new node

**Comment by ruanwenjun** [comment]
@wangmingzhiJohn When you add a new worker or master, the new instance will register in registry center automatic, and to exist masters will receive the added event. The script just is a normal start, stop script.

**Comment by wangmingzhiJohn** [comment]
@ruanwenjun  So, actually, the exists node's service don't need to update their install_config.conf as they can know the new node by zookeeper automaticly, is that correct?

**Comment by ruanwenjun** [comment]
@wangmingzhiJohn Yes, and other registry center will be supported in the future, currently only zookeeper.

**Comment by wangmingzhiJohn** [comment]
@ruanwenjun  In another way, these specific ips in install_config.conf is not necessary if I setup every service on every node manually by dolphinscheduler-daemon.sh?

**Comment by wangmingzhiJohn** [comment]
Or except zookeeper's ip:port which is necessary.
