### ISSUE TITLE
MacOS big sur : run datax task failed

### ISSUE THREAD

**Issue by Atom-me** [apache/dolphinscheduler#5871]
execute command :  
    sudo -u atom sh /tmp/dolphinscheduler/exec/process/1/7/8/21/7_8_21.command

error message : 
    /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/bin/datax.py': [Errno 2] No such file or directory

![image](https://user-images.githubusercontent.com/58026677/126427376-090e7a00-2e01-4a9d-b1c3-5e2f9e10c5b8.png)

version: 1.3.6-release
plateform: macos big sur
env:
  ~/.zshrc file content:
         export DATAX_HOME=/Users/atom/work/datax
         export PATH=$PATH:$DATAX_HOME/bin
         export PYTHON_HOME=/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
         export PATH=$PATH:$PYTHON_HOME

ps: delete the 'sudo -u atom' prefix ,only execute 'sh /tmp/dolphinscheduler/exec/process/1/7/8/21/7_8_21.command' can successfully execute

**Comment by chengshiwen** [comment]
@Atom-me Related issue: #5596, pr: #5612

**Comment by Xenos3811** [comment]
> @Atom-me Related issue: #5596, pr: #5612

It's not the same problem.
How did you solve it @Atom-me
