### ISSUE TITLE
[bug][server]  The worker group selected during workflow execution does not take effect

### ISSUE THREAD

**Issue by Lucaszlei** [apache/dolphinscheduler#5873]
**Describe the bug**
Selecting Worker grouping while executing a workflow does not take effect
- case 1
1. Create a worker group where the IP does not actually exist.
2. Create a new process definition and the task specifies the worker group created in the first step.
3. Execute the workflow and select the worker group with the name default.
4. After the porcess is started, observe that the value of the WORKER_GROUP_ID field of the T_DS_PROCESS_INSTANCE table is the worker group ID selected when the process is executed.
5. Observe that the value of the WORKER_GROUP_ID field of the T_DS_TASK_INSTANCE table is not equal to the worker group ID selected when the process is executed, but to the worker group ID selected when the task is created.
6. Task is always committed successfully and will not execute.
- case 2
1. Create a worker group where the IP does not actually exist.
2. Create a new process definition and the task specifies the worker group with the name default.
3. Execute the workflow and select the worker group created in the first step.
4. After the porcess is started, observe that the value of the WORKER_GROUP_ID field of the T_DS_PROCESS_INSTANCE table is the worker group ID selected when the process is executed(-1).
5. Observe that the value of the WORKER_GROUP_ID field of the T_DS_TASK_INSTANCE table is not equal to the worker group ID selected when the process is executed, but to the worker group ID selected when the task is created(-1).
6. In this case, the worker selection is correct because the following `org.apache.dolphinscheduler.dao.ProcessDao#getTaskWorkerGroupId` code judges `taskWorkerGroupId> 0`, which takes the value of the WORKER_GROUP_ID field of the T_DS_PROCESS_INSTANCE
![图片](https://user-images.githubusercontent.com/56599784/126489659-347a08ad-89ed-4065-94b9-b45c9cb2e835.png)

**Which version of Dolphin Scheduler:**
 - [1.2.1]

**Comment by CalvinKirs** [comment]
I'm so sorry, I don't understand what your mean, when the worker group is no valid, the task shouldn't process. you think should we do？ check IP when a user adds a worker group? or another method?Can you describe it in detail？

**Comment by Lucaszlei** [comment]
> I'm so sorry, I don't understand what your mean, when the worker group is no valid, the task shouldn't process. you think should we do？ check IP when a user adds a worker group? or another method?Can you describe it in detail？

First of all, I agree that tasks should not be processed when worker grouping is invalid.
I mean, selecting worker grouping during execution is invalid in some cases.
The task is not executed on the worker group selected when executing, but on the worker group selected when creating the task

**Comment by Lucaszlei** [comment]
> 
> 
> I'm so sorry, I don't understand what your mean, when the worker group is no valid, the task shouldn't process. you think should we do？ check IP when a user adds a worker group? or another method?Can you describe it in detail？

该问题主要是：
发现在1.2.1版本中，在执行工作流时选择worker分组不生效，直接执行时还是按照创建任务时选择的worker分组在执行。
如果创建任务时选择默认的worker分组，执行时选择其他worker分组，任务执行时会分发到指定的worker上执行，但是如果创建时选择非默认的worker分组，执行时选择默认的worker分组，任务执行时并不在默认的worker分组上。
1.3.x版本未验证

---

The main problems are:
It is found that in version 1.2.1, selecting worker grouping does not take effect when executing the workflow, and it is still executed according to the worker grouping selected when the task is created when it is executed directly.
If the default worker group is selected when creating a task, and other worker groups are selected when executing, the task will be distributed to the specified workers for execution when the task is executed, but if a non-default worker group is selected when creating a task, the default worker group is selected when executing, and the task is executed Time is not on the default worker group.
1.3.x version is not verified

**Comment by caishunfeng** [comment]
It had been fixed and this issue will be closed. You can reopen it if need.
