### ISSUE TITLE
how to config ds when yarn ha cluster modify the default 8088 port

### ISSUE THREAD

**Issue by ghost** [apache/dolphinscheduler#5874]
I'm using emr cluster and I want to deploy ds on the emr cluster, 
however, for the safety, the emr modify the default webUI port 8088.

how do I config the yarnHaIps in  DS_HOME/conf/config/install_config.conf，the description for this config is 
# if resourceStorageType is S3, the following three configuration is required, otherwise please ignore

I try to set the yarnHaIps = ”master1,master2“，the master1,master2 is the hosts that deploy yarn HA，but encount the problem "java.net.UnknownHostException: null: Name or service not known" when I submit a job in ds。

then I try to modify  yarnHaIps = ”master1:5004,master2:5004“，but when I schedule a shell node that define  a multi process program, another problem occurs, the follow is the Error picture
![image](https://user-images.githubusercontent.com/87113955/126490063-b4670dbc-cb95-497a-87ad-3c513a6cb84d.png)
the content in the shell node is as follow
```
#!/bin/bash
# 并发运行的最佳实践

# 并发数,并发数过大可能造成系统崩溃
Qp=3
# 存放进程的队列
Qarr=()
# 运行进程数
run=0
# 将进程的添加到队列里的函数
function push() {
  Qarr=(${Qarr[@]} $1)
  run=${#Qarr[@]}
}
# 检测队列里的进程是否运行完毕
function check() {
  oldQ=(${Qarr[@]})
  Qarr=()
  for p in "${oldQ[@]}"; do
    if [[ -d "/proc/$p" ]]; then
      Qarr=(${Qarr[@]} $p)
    fi
  done
  run=${#Qarr[@]}
}

start_day=2021-07-01
end_day=2021-07-20
do_date=${start_day}
while [[ ${do_date} < $(date -d "+1 day $end_day" +%F) ]];
do
  echo ${do_date}
  sh dws_to_ads_dev.sh all ${do_date} &

  push $!
  while [[ $run -gt $Qp ]]; do
    check
    sleep 0.1
  done

  do_date=$(date -d "+1 day ${do_date}" +%F)
done

echo -e "time-consuming: $SECONDS seconds" # 显示脚本执行耗时
```

now I don't know how should I config the ds, and if I have deployed the ds, what should I config the config files in DS_HOME/conf/ directory besides DS_HOME/conf/config/install_config.conf to avoiding reinstall ds via the "sh DS_HOME/install.sh" command，because if I reinstall the ds，the log in ds cluster will be deleted！

hope someone with experience could provide some help !!!

**Comment by CalvinKirs** [comment]
I'm so sorry,we will suppoort it for 1.3.7 release,if you are anxious，you can refer this #5862  update

**Comment by ghost** [comment]
> I'm so sorry,we will suppoort it for 1.3.7 release,if you are anxious，you can refer this #5862 update

so it means we can confing customer yarn port for yarn HA cluster in ds's config file?

**Comment by chengshiwen** [comment]
In dev branch, the yarn port has been configured in `common.properties`, we'll support this feature in 1.3.7

https://github.com/apache/dolphinscheduler/blob/8571461fe8c0eea9cdb9738be87e43f827f8e00f/dolphinscheduler-common/src/main/resources/common.properties#L61

**Comment by CalvinKirs** [comment]
closed. will release on 1.3.7
