### ISSUE TITLE
cross-database how to config the datasource and sql

### ISSUE THREAD

**Issue by final-smile** [apache/dolphinscheduler#5877]
as the title，how to config the datasource and sql when the sql neet to query from two or more databses

**Comment by final-smile** [comment]
version:1.3.6

**Comment by ruanwenjun** [comment]
:joy:

**Comment by final-smile** [comment]
"Cross-database support is currently supported!Specify that the database is just a test connection! "，qiaozhanwei closed this on 29 May 2019 ,but I can not found how to config,I must input the database name when add datasource
