### ISSUE TITLE
[Question] sql hive  load data inpath '/ods/ods_xx/${db_date}'  error  

### ISSUE THREAD

**Issue by zhengshubin** [apache/dolphinscheduler#5885]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
A clear and concise description of what the question is.
 it happen [ERROR] 2021-07-26 16:00:29.007  - [taskAppId=TASK-8-79-125]:[167] - sql task error: org.apache.hive.service.cli.HiveSQLException: Error while compiling statement: FAILED: SemanticException Line 1:18 Invalid path ''/fake/origin_data/db/ldr_proc/?/'': No files matching path hdfs://cluster01/fake/origin_data/db/ldr_proc/%3F

**Which version of DolphinScheduler:**
 -[1.1.0-preview]
1.3.6

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by Tandoy** [comment]
Can your load data script be executed successfully in the Linux environment? Perhaps the tenant executing the command does not have permission to this directory in HDFS

**Comment by zhengshubin** [comment]
> Can your load data script be executed successfully in the Linux environment? Perhaps the tenant executing the command does not have permission to this directory in HDFS

 I used  '/ods/ods_xx/$[yyyy-MM-dd-1]/'   instead of  /ods/ods_xx/${db_date} ,and it executed successsfully

**Comment by CalvinKirs** [comment]
hi,Is your problem solved?

**Comment by zhengshubin** [comment]
> hi,Is your problem solved?

yes, but  I want to use  a global paramater

**Comment by CalvinKirs** [comment]
> > hi,Is your problem solved?
> 
> yes, but I want to use a global paramater

This feature will be released in 2.0, and the 1.3.X series will not release this content for the time being, you can view it on the dev branch now. this is doc https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/globalParams.html
