### ISSUE TITLE
[Bug][dolphinscheduler-server]  There is a problem with the judgment condition for deleting a scheduled job

### ISSUE THREAD

**Issue by Squidyu** [apache/dolphinscheduler#5886]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
There is a problem with the judgment condition for deleting a scheduled job.
It's not rigorous enough
**To Reproduce**
![image](https://user-images.githubusercontent.com/22636614/126955216-9465f40d-b09b-4cad-bb2c-a7d70a40eef8.png)
If I manually offline the schedule in the database, then the schedule will still run. 
**Expected behavior**
I think if manually offline the schedule,the quartz should be deleted!

**Which version of Dolphin Scheduler:**
 -[ALL]

**Additional context**

**Requirement or improvement**
- It cannot be judged by whether the 'schedule' is empty, but by whether the online 'schedule' is empty

**Comment by Squidyu** [comment]
If you agree, I will add a PR

**Comment by davidzollo** [comment]
good, please submit a PR, thx

**Comment by Squidyu** [comment]
#5936
