### ISSUE TITLE
[Feature][Doc] Collect previous shared PPT Slides link to a document

### ISSUE THREAD

**Issue by davidzollo** [apache/dolphinscheduler#5888]
The download link of the PPT Slides that has been shared below is the following document(md format), and then put it on the download page of the official website
https://github.com/apache/dolphinscheduler-website/tree/master/file

| Time | Download link |
| ---------- | -------------------------------------- ---------------------- |
| 2021-06-26 | [Apache DolphinScheduler Architecture Evolution-Ruan Wenjun eBay](https://github.com/apache/dolphinscheduler-website/blob/master/file/2021-06-26/Apache%20DolphinScheduler%20architecture% 20evolution%20-%20eBay%20ruanwenjun.key) |

----

将下面历次分享的 PPT Slides 下载链接为如下 md 格式的文档, 后续放到官网下载页面
https://github.com/apache/dolphinscheduler-website/tree/master/file

| 时间       | 下载链接                                                     |
| ---------- | ------------------------------------------------------------ |
| 2021-06-26 | [Apache  DolphinScheduler 架构演进 - 阮文俊 eBay](https://github.com/apache/dolphinscheduler-website/blob/master/file/2021-06-26/Apache%20DolphinScheduler%20architecture%20evolution%20-%20eBay%20ruanwenjun.key) |

**Comment by fs3085** [comment]
I want to try to solve this issue

**Comment by fs3085** [comment]
@dailidong 
I need to confirm the following questions:
1. Whether to organize the Apache DolphinScheduler architecture evolution document into md files
2. Do you need to organize all pptx in the https://github.com/apache/dolphinscheduler-website/tree/master/file directory into md files
3. Where to put it on the official website

**Comment by davidzollo** [comment]
> 1. Whether to organize the Apache DolphinScheduler architecture evolution document into md files

yes

> 2. Do you need to organize all pptx in the https://github.com/apache/dolphinscheduler-website/tree/master/file directory into md files

no need to convert these PPTs to md files which are very hard work

> 3. Where to put it on the official website

the website github repository: https://github.com/apache/dolphinscheduler-website
![image](https://user-images.githubusercontent.com/15833811/127096723-1224db25-7d86-4782-aded-77b29a5b4d9d.png)

**Comment by davidzollo** [comment]
related PR: https://github.com/apache/dolphinscheduler-website/pull/410
