### ISSUE TITLE
[WebSite][Doc] add release note to download page

### ISSUE THREAD

**Issue by CalvinKirs** [apache/dolphinscheduler#5889]
Add a specific release-note to the page https://dolphinscheduler.apache.org/zh-cn/download/download.html. The English version is available at github/apache/dolphinscheduler/ release-note. note. (You will need to create release-notes for each version.) Chinese version reference (https://www.oschina.net/search?identification=1627314582095&scope=news&q=dolphinscheduler+release)

**Comment by RedemptionC** [comment]
I don't really get it: what should be done for this issue?

**Comment by CalvinKirs** [comment]
done
