### ISSUE TITLE
[SOC 2021][DISCUSS] Build CI/CD pipeline with ds 

### ISSUE THREAD

**Issue by zhenmm** [apache/dolphinscheduler#5891]
The current pipeline for spring-boot-vuejs is below. There are 6 nodes in total, and all of them are shell nodes.
目前的spring-boot-vuejs工作流如下，共有6个节点，全部为shell node.
spring-boot-vuejs：https://github.com/jonashackt/spring-boot-vuejs

![43D8CD4A-0AA5-46DE-A071-FDF62A1E0836](https://user-images.githubusercontent.com/85644941/127075639-74a4e75d-8e12-45db-87bb-36227767247c.jpeg)

**Node 1: check_node**

Check if spring-boot-vuejs directory is under /opt/repo/. If available, pull the latest version, if not, clone
检查本地/opt/repo/下是否有spring-boot-vuejs仓库，若有就pull最新版本，没有则clone

> cd /opt/repo
> 
> DIR="/opt/repo/spring-boot-vuejs"
> if [ -d "$DIR" ]; then
>   echo "Pass: ${DIR} exist"
>   cd /opt/repo/spring-boot-vuejs
>   git pull origin master
>   echo "Update: ${DIR} directory"
> else
>   echo "Error: ${DIR} not found. Clone repo"
>   git clone https://github.com/jonashackt/spring-boot-vuejs
>   cd spring-boot-vuejs
> fi
> 

**Node 2: build java8**

Check if java 8 is being used, then run mvn install for building
检查java版本是否为指定版本（version8），执行mvn install命令进行构建

> pwd 
> cd /opt/repo/spring-boot-vuejs
> 
> java -version
> echo $JAVA_HOME
> 
> npm config set registry http://registry.npmjs.org   
> mvn -B install --no-transfer-progress

**Node 3: test java8**

Run mvn verify for testing
运行mvn verify来测试

> cd /opt/repo/spring-boot-vuejs
> 
> mvn -B verify --no-transfer-progress 
> 

**Node 4: build java16**

Check if java 16 is being used, then run mvn install for building
检查java版本是否为指定版本（version16），执行mvn install命令进行构建

> cd /opt/repo/spring-boot-vuejs
> 
> java -version
> echo $JAVA_HOME
> 
> JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-16.0.2.jdk/Contents/Home
> export JAVA_HOME;
> echo $JAVA_HOME
> 
> npm config set registry http://registry.npmjs.org   
> mvn -B install --no-transfer-progress 

**Node 5: test java16**

Run mvn verify for testing
运行mvn verify来测试

> cd /opt/repo/spring-boot-vuejs
> 
> mvn -B verify --no-transfer-progress

**Node 6: deploy**

Use java 8 for deployment. Run the application in the background
变更为java8版本,后台执行启动命令

> cd /opt/repo/spring-boot-vuejs
> 
> JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_291.jdk/Contents/Home
> export JAVA_HOME;
> echo $JAVA_HOME
> 
> echo START
> nohup java -Djava.security.egd=file:/dev/./urandom -jar ./backend/target/backend-0.0.1-SNAPSHOT.jar > buildres.txt 2>&1 &
> echo END
> sudo lsof -i tcp:8098

please let me know your questions and suggestions!

BR
Zhen

**Comment by davidzollo** [comment]
good job
