### ISSUE TITLE
When the process definition starts, you can specify the Worker group 001, but you also specify a different Worker group 002 on the task node configuration. May I ask that the process will be executed under that worker?

### ISSUE THREAD

**Issue by git1071440198** [apache/dolphinscheduler#5892]
When the process definition starts, you can specify the Worker group 001, but you also specify a different Worker group 002 on the task node configuration. May I ask that the process will be executed under that worker.

---

 流程定义启动的时候可指定Worker分组001，但是在任务节点配置上也指定l不同的Worker分组002，请问流程会在那个worker下执行，启动指定worker分组 和 节点配置worker分组那个优先级高？

**Comment by CalvinKirs** [comment]
We require an English discussion on Github. 
Please use English.thx

**Comment by davidzollo** [comment]
the task will execute on worker group 002, you can have a try
