### ISSUE TITLE
[BUG]application-api.properties config item  default value server.port=1.3.6 can't start api server

### ISSUE THREAD

**Issue by lishiyucn** [apache/dolphinscheduler#5893]
[BUG]application-api.properties config item  default value server.port=1.3.6 can't start api server

**Comment by CalvinKirs** [comment]
can you provide any detailed informaction?
version? log?

**Comment by lishiyucn** [comment]
dolphinscheduler1.3.6

**Comment by caishunfeng** [comment]
There're too little message of this issue. It will be closed and you can reopen it if you need.
