### ISSUE TITLE
[Improvement][CI] Maven connection sometimes times out

### ISSUE THREAD

**Issue by shink** [apache/dolphinscheduler#5921]
## Describe the question

I notice a lot of connection timeout errors in the CI build.
For example: https://github.com/apache/dolphinscheduler/runs/3192300302?check_suite_focus=true

![image](https://user-images.githubusercontent.com/49934421/127519775-c5a97ba0-1790-4aec-8538-cdaa47af44f7.png)

## Describe alternatives you've considered

Please see: https://github.com/actions/virtual-environments/issues/1499#issuecomment-689467080
We can add `-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120` to the build command.

**Comment by chengshiwen** [comment]
@shink Thanks for your feedback! Welcome to contribute the code!
