### ISSUE TITLE
[Feature] Parameter value transfer between tasks

### ISSUE THREAD

**Issue by gaoyu2016** [apache/dolphinscheduler#5926]
需要一个feature，可以在task之间进行参数值传递。搜了下，貌似有实现python节点的，但远远不满足需要。需要能满足所有
节点。

**Comment by gaoyu2016** [comment]
有知道的发我下future链接，找了几个没找到。

**Comment by ruanwenjun** [comment]
@gaoyu2016 The related issue about global param is #5565, you can find some docs at https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/globalParams.html. Currently, only Chinese docs is available.

And for better communication, please use English.
