### ISSUE TITLE
[Question] [website] [doc] /development/architecture-design.html

### ISSUE THREAD

**Issue by Tandoy** [apache/dolphinscheduler#5927]
**Describe the question**
Is the zk node in the framework design module distributed_lock.png of the developer guide wrong? The node path in the actual environment[version-1.3.2] is: /dolphinscheduler/lock/masters
![distributed_lock](https://user-images.githubusercontent.com/56899730/127731484-77911c8d-b600-4c33-a7a8-4df183a3123f.png)

**Comment by ruanwenjun** [comment]
@Tandoy Yes, this is a typo, you can submit a pr to fix it.
Furthermore, there exist some Chinese words at the picture of the English docs, do you want to fix this together?

**Comment by Tandoy** [comment]
@ruanwenjun ok, I will try to fix them.

**Comment by Tandoy** [comment]
related PR: apache/dolphinscheduler-website#415
