### ISSUE TITLE
[Improvement][Scheduler] Scheduler adds calendar configuration options

### ISSUE THREAD

**Issue by huyaro** [apache/dolphinscheduler#5932]
**Describe the question**
There are discrepancies between holidays in some industries and national holidays, such as finance. With the scheduling options provided by the current DS, it is necessary to determine whether it is a working day in each task node before performing related operations. Whether to consider adding a customizable calendar configuration, specify it during task configuration.

**What are the current deficiencies and the benefits of improvement**
A set of natural day calendar is provided by default, compatible with current tasks. If a custom calendar is configured, the schedule will be performed according to the custom calendar. Avoid making relevant judgments in all task nodes.

**Which version of DolphinScheduler:**
 -[1.3.6]

**Describe alternatives you've considered**
A clear and concise description of any alternative improvement solutions you've considered.

**问题描述**：
有一些行业的节假日与国定节假日存在出入，例如金融。以当前DS提供的调度选项，需要在每个任务节点中去判断是否为工作日再执行相关操作。 是否考虑增加可自定义的日历配置，在任务配置时指定。

**改进建议**：
默认提供一套自然日日历，兼容当前已有任务。如果配置自定义日历，则按自定义的日历来进行调度。避免在所有任务节点中进行相关判断。

刚搜索了一下issues, 发现 #193 就是与我这个一致的需求。

**Comment by CalvinKirs** [comment]
good idea,Can you contribute to this feature？
