### ISSUE TITLE
[Bug][server] default worker group nodes may not sync

### ISSUE THREAD

**Issue by linghengzhu** [apache/dolphinscheduler#5940]
**Describe the bug**
This bug is also reported in [https://github.com/apache/dolphinscheduler/issues/5528](https://github.com/apache/dolphinscheduler/issues/5528) which is not resolved yet though already closed. I ran into this bug when I deployed dolphinscheduler on k8s. I may have found the real cause of this bug, and give detailed reproduce steps as followed.
The bug is described as below.
After clicking run button and choose default worker group, tasks can not be dispatched forever.
Master node print error log which says fail to execute : %s due to no suitable worker.

**To Reproduce**
To reproduce, you can add Thread.sleep(60000) after line "load();" in method ServerNodeManager.afterPropertiesSet() to enlarge the timespan and increase the probability that this bug happens. And start master node first till it falls asleep, then start worker node.

**Which version of Dolphin Scheduler:**
 -[1.3.6-release]

**Requirement or improvement**
From the reproduce steps, you can see the cause of this bug. It's because the map workerGroupNodes fail to sync with zookeeper. And that is because the listener registered too late. So maybe the solution is to switch the execute order of load() and listener registration.

**Comment by CalvinKirs** [comment]
After the Master/Worker is started, it will subscribe to the registry listener, and then pull information from the registry. Can you help me confirm that the current process is like this?

**Comment by linghengzhu** [comment]
> After the Master/Worker is started, it will subscribe to the registry listener, and then pull information from the registry. Can you help me confirm that the current process is like this?

Yes.
