### ISSUE TITLE
[Bug] "Tenant does not exist" is reported when adding a directory to the Resource Center

### ISSUE THREAD

**Issue by luojieio** [apache/dolphinscheduler#5943]
创建目录命名：test
查看API的日志：
[INFO] 2021-08-03 18:59:22.954 org.apache.dolphinscheduler.api.controller.ResourcesController:[92] - login user admin, create resource, type: FILE, resource alias: test, desc: , file: -1,/

使用的是k8s部署
value配置文件使用minio，配置如下：
 RESOURCE_STORAGE_TYPE: "S3"
    RESOURCE_UPLOAD_PATH: "/dolphinscheduler"
    FS_DEFAULT_FS: "s3a://tmp"
    FS_S3A_ENDPOINT: "http://192.168.0.1:5000"
    FS_S3A_ACCESS_KEY: "xxxxx"
    FS_S3A_SECRET_KEY: "xxxxx"

网络可通，Minio可访问，求解答

**Comment by chengshiwen** [comment]
@luojieio Make sure the bucket name `tmp` exists, and make sure the upload directory `RESOURCE_UPLOAD_PATH` `/dolphinscheduler` exists

**Comment by luojieio** [comment]
> @luojieio Make sure the bucket name `tmp` exists, and make sure the upload directory `RESOURCE_UPLOAD_PATH` `/dolphinscheduler` exists

![image](https://user-images.githubusercontent.com/25678606/128111922-7f3403de-866a-4e76-9465-db70a032e977.png)

![image](https://user-images.githubusercontent.com/25678606/128111964-a0228b94-2762-419c-8173-8b0dcc8ad5c8.png)

api进程日志：
[INFO] 2021-08-04 10:25:02.444 org.apache.dolphinscheduler.api.controller.ResourcesController:[92] - login user admin, create resource, type: FILE, resource alias: test, desc: , file: -1,/

bucket修改为这样了：
![image](https://user-images.githubusercontent.com/25678606/128112081-73c6b481-cd36-4c61-9e7c-88195d0bec59.png)

 RESOURCE_UPLOAD_PATH: "/dolphinscheduler"
    FS_DEFAULT_FS: "s3a://nginx/tmp"
    FS_S3A_ENDPOINT: "http://xxx.xxx.xxxx.xxx:1234"
    FS_S3A_ACCESS_KEY: "xxxxx"
    FS_S3A_SECRET_KEY: "xxxx"

**Comment by Squidyu** [comment]
You need to switch a non admin user operation and associate this user with an existing tenant. It should be OK
--你需要切换一个非admin用户操作，并且将这个用户关联到一个存在的租户上，应该就可以了

**Comment by luojieio** [comment]
> You need to switch a non admin user operation and associate this user with an existing tenant. It should be OK
> --你需要切换一个非admin用户操作，并且将这个用户关联到一个存在的租户上，应该就可以了

换了用户就可以了，为何不能使用admin呢？
最终value配置如下：
 RESOURCE_STORAGE_TYPE: "S3"
    RESOURCE_UPLOAD_PATH: "/dolphinscheduler"
    FS_DEFAULT_FS: "s3a://tmp"
    FS_S3A_ENDPOINT: "http://xxxxxxxx:8888"
    FS_S3A_ACCESS_KEY: "xxxxxxx"
    FS_S3A_SECRET_KEY: "xxxxx"

**Comment by Squidyu** [comment]
> > You need to switch a non admin user operation and associate this user with an existing tenant. It should be OK
> > --你需要切换一个非admin用户操作，并且将这个用户关联到一个存在的租户上，应该就可以了
> 
> 换了用户就可以了，为何不能使用admin呢？
> 最终value配置如下：
> RESOURCE_STORAGE_TYPE: "S3"
> RESOURCE_UPLOAD_PATH: "/dolphinscheduler"
> FS_DEFAULT_FS: "s3a://tmp"
> FS_S3A_ENDPOINT: "http://xxxxxxxx:8888"
> FS_S3A_ACCESS_KEY: "xxxxxxx"
> FS_S3A_SECRET_KEY: "xxxxx"

Admin is not associated with a tenant. If a tenant does not operate when creating a directory, an error will be reported
-- admin没有关联到租户，创建目录的时候没有操作的租户，就会报错

**Comment by chengshiwen** [comment]
Close since it has been resolved
