### ISSUE TITLE
How to add new nodes in worker group

### ISSUE THREAD

**Issue by luojieio** [apache/dolphinscheduler#5945]
![image](https://user-images.githubusercontent.com/25678606/128119001-4bc9088e-7b06-44ed-a30c-281114dd3948.png)

我是使用K8s进行部署的，如果增加新的worker节点，比如：我想增加物理机或虚拟机作为工作节点

**Comment by chengshiwen** [comment]
@luojieio You can deploy a worker-server on a physical machine or virtual machine, and configure the `conf`, especially the `worker.groups` in worker.properties, to support manual configuration of worker groups

**Comment by CalvinKirs** [comment]
No response, I will close it. If you still have problems, you can reopen it.
