### ISSUE TITLE
[Improvement][Service]Optimize the service module

### ISSUE THREAD

**Issue by CalvinKirs** [apache/dolphinscheduler#5949]
The service model should only contain specific data, Result is generally the encapsulated carrier of external interaction data, should not be reflected in the service. Related errors can be directly thrown exceptions, API unified exception capture interception.

**Comment by soreak** [comment]
I will complete this issue

**Comment by CalvinKirs** [comment]
This is a big task, if you want to complete it, you can create a sub-issue.

**Comment by soreak** [comment]
> This is a big task, if you want to complete it, you can create a sub-issue.

Yeah, I know. But I haven’t had time to complete this issue recently

**Comment by RedemptionC** [comment]
the description of this issue is quite confusing🧐

**Comment by soreak** [comment]
> the description of this issue is quite confusing🧐

This is the meaning of this issue that the service model needs to define a new type without using map

**Comment by soreak** [comment]
I think this is beyond my reach
