### ISSUE TITLE
[Feature] Support metadata management

### ISSUE THREAD

**Issue by Narcasserun** [apache/dolphinscheduler#5954]
### 1. Summary

Metadata provides necessary data support for data governance because supporting metadata is very important. It can not only enable users to understand data more clearly when using DS development, such as table fields and field types. It solves the "data search demand" of retrieving and understanding data, and can provide better services for data quality and data security in the later stage. It can also improve the efficiency of data development，I have implemented it and run stably in production. After discussion, I will submit pr

### 2. Key design points**

-Provide unified interface

-Get metadata in real time without external storage

-Insert metadata and run independently

-Add different data sources and put jars into the Lib directory without restarting the dolphin API server and work server

![image](https://user-images.githubusercontent.com/39329477/128869172-66e030f8-1ac1-43d0-a1c6-e9ec1e6113d6.png)

**2.1.Installation and deployment directory structure**

├──   Lib lib directory

│     ├──   Meta common -- spring public dependency package directory

│     ├──   Hadoop client -- lib directory on which Hadoop depends

│     ├──   JDBC -- jar package directory necessary for connecting data source with Java

│     ├──   ├---── hive -- jar package necessary to connect hive with Java

│     ├──   ├---──pg

│     ├──   ├---──mysql

│     ├──   Plugin -- get the jar package directory of the corresponding datasourcecilent from the data source and metadata

│     ├──   ├---──hive

│     ├──   ├---──pg

│     ├──   ├---──mysql

**2.2.Source directory structure**

├──   Data source plug-in directory supported by meta plugin

│     ├──   Hive plugin -- hiveclien connection acquisition, metadata function

│     ├── ├──lib - jar package necessary for connecting hive with Java

│     ├──    postgresql-plugin

│     ├── ├──lib

│     ├──    mysql-plugin

│     ├── ├──lib

│     ├──    oracle-plugin

│     ├── ├──lib

│     └──    sqlserver-plugin

│     ├── ├──lib

│     └──    clickhouse-plugin

│     ├── ├──lib

│     └──    db2-plugin

│     ├── ├──lib

├──   meta-api   --provides data source management and its metadata query restful service, and plug-in datasourceclient is created

**2.3.Create data source flowchart**

![image](https://user-images.githubusercontent.com/39329477/128687288-4dee4077-58cb-44c9-80b2-fc2078a32c46.png)

### 3. Demand analysis

For metadata, we must pay attention to scalability and support multiple data sources. Therefore, the integrated design method should be adopted. The following functions need to be met to realize it

##### 3.1.1 create data source

**The current shortcomings and the benefits of improvement are**

Now to add different data sources, you need to put jars into the Lib directory, and then restart dolphin API server and work server. After the expansion is realized, you will no longer need to restart. Later, it is also very helpful for the plug-in of metadata

```

{

"Connhdfs": true, -- hive, etc. need to connect metadata,

"Connmetastore": true, -- hive, etc. need to connect metadata

"Dbtype": "hive", -- data source type

"driverLocation": "/home/bigdata/meta/jdbc/hive/hive-jdbc-2.2.2-standalone.jar",

"Hadoop configurationresources": "/ home / bigdata / apps / hadoop-2.7.2/etc/hadoop/core-site.xml, / home / bigdata / apps / hadoop-2.7.2/etc/hadoop/hdfs-site.xml, / home / bigdata / apps / apache-hive-1.2.1-bin/conf/hive-site.xml", -- get from the configuration file

"id": 1,

"Kerberos KeyTab": "", --- get from configuration file

"Kerberos krb5conf": "", --- get from configuration file

"Principal": "",

"password": 123456,

"URL": "JDBC: hive2: / / zbg-bg-01:10000 / default", -- assembled according to the input parameters, or filled in manually by the user

"username": "root",

"Other": null --- other parameters

}



```

### **4. Data source SPI to do list**

- [x] basic code for SPI implementation of data source and metadata, loading of data source driver and plugin, and unified management of data source connection

- [x] load and transform the existing supported data source SPI, and add the data source client check and SQL execution functions
- [x] Replace the data source connection loaded by SPI where the original connection method is used in DS

###5. metadata acquisition

**Comment by ruanwenjun** [comment]
Great, maybe you can provide a detail design plan or some demo code.
And it seems that metadata management is a sub function of datasource SPI.

**Comment by Narcasserun** [comment]
> Great, maybe you can provide a detail design plan or some demo code.
> And it seems that metadata management is a sub function of datasource SPI.

Yes, I updated the design. You can take a look first. The demo code will be updated tomorrow

**Comment by Narcasserun** [comment]
> Great, maybe you can provide a detail design plan or some demo code.
> And it seems that metadata management is a sub function of datasource SPI.

I have given the design plan or some demonstration code, and look forward to communicating with you

**Comment by ruanwenjun** [comment]
@Narcasserun So we first need to implement the datasource plugin, am I right? Then we can do a lot of functions such like metadata management.

The datasource SPI has been mentioned at #5680, what may need to attention is how to adapt to the front-end. You can refer to the alert-plugin.

**Comment by Narcasserun** [comment]
> @Narcasserun So we first need to implement the datasource plugin, am I right? Then we can do a lot of functions such like metadata management.
> 
> The datasource SPI has been mentioned at #5680, what may need to attention is how to adapt to the front-end. You can refer to the alert-plugin.

You're right. The metadata management I implemented includes data source creation and metadata acquisition, but now there are only restful services. I think metadata services can be called for data quality and workflow development. How to adapt the front end needs to be discussed together. I have updated the document, and the implementation is very similar to alert plugin

**Comment by Narcasserun** [comment]
@ruanwenjun This is the result of my local test of hive metadata. Of course, this is one of them obtained through JDBC, and there are more detailed metadata
![image](https://user-images.githubusercontent.com/39329477/128958368-8a80127b-6127-4e1c-a72b-58707bbe3175.png)

**Comment by jon-qj** [comment]
how about datahub architecture ( https://github.com/linkedin/datahub)?
![image](https://user-images.githubusercontent.com/39773194/128958490-c837f786-ef86-4c4a-a89f-fb11dd539f1f.png)
or metacat  architecture (https://github.com/Netflix/metacat)
![image](https://user-images.githubusercontent.com/39773194/128960002-88a26d62-1fe8-42a5-b250-469270630122.png)

**Comment by Narcasserun** [comment]
> how about datahub architecture ( https://github.com/linkedin/datahub)?
> ![image](https://user-images.githubusercontent.com/39773194/128958490-c837f786-ef86-4c4a-a89f-fb11dd539f1f.png)
> or metacat architecture (https://github.com/Netflix/metacat)
> ![image](https://user-images.githubusercontent.com/39773194/128960002-88a26d62-1fe8-42a5-b250-469270630122.png)

Hello, both datahub and metacat are very good metadata management frameworks, but their architecture is a little heavy for DS or big data platform, which will increase the external complexity and deployment cost of DS / big data platform. This should not be accepted

**Comment by jon-qj** [comment]
> > how about datahub architecture ( https://github.com/linkedin/datahub)?
> > ![image](https://user-images.githubusercontent.com/39773194/128958490-c837f786-ef86-4c4a-a89f-fb11dd539f1f.png)
> > or metacat architecture (https://github.com/Netflix/metacat)
> > ![image](https://user-images.githubusercontent.com/39773194/128960002-88a26d62-1fe8-42a5-b250-469270630122.png)
> 
> Hello, both datahub and metacat are very good metadata management frameworks, but their architecture is a little heavy for DS or big data platform, which will increase the external complexity and deployment cost of DS / big data platform. This should not be accepted

Yes,you are right.I mean we can reduce the difficulty of our own implementation by borrowing their ideas or codes.

**Comment by Narcasserun** [comment]
@jon-qj Yes, the method is right. You can look at the document above

**Comment by davidzollo** [comment]
big feature!
I like this plugin design

**Comment by CalvinKirs** [comment]
+1，Great design！

**Comment by caishunfeng** [comment]
+1，Great design！

**Comment by daviddone** [comment]
+1, Meta Data is important, also as Data Quality !

**Comment by yangtzelsl** [comment]
+1, Meta Data is important, also as Data Quality !

**Comment by viosay** [comment]
+1 +1 +1 Strongly Agree
