### ISSUE TITLE
[Improvement] ResultFul API Design documents

### ISSUE THREAD

**Issue by marin-man** [apache/dolphinscheduler#5962]
## URI Design
Rest：representative state transfer. It describes the functions of the API by combining URI and Method. Uri is used to represent resources, and method is used to represent operations on resources.  Resources are divided into single and single categories, which are expressed in singular and plural respectively, such as `groups/{groupId}` and `groups`.

### 1. Query
Get is used to query, and the resources of the query are limited by URI.
+ Query a class of resources
```
Method: GET
/api/dolphinscheduler/v1/alert-groups
```
+ Query a resource
```
Method: GET
/api/dolphinscheduler/v1/alter-groups/{id}
```
+ Query sub resources
```
Method: GET
/api/dolphinscheduler/v1/projects/{projectId}/tasks
```
All the above query methods correspond to paging query. If we need to query all data, we need to add / list after the URI to distinguish. **Do not mix paging queries and queries with one API.**
```
Method: GET
/api/dolphinscheduler/v1/alert-groups/list
```

### 2. Create
Post is used to create , and the resources of the create are limited by URI.
+ Create a alter-group
```
Method: POST
/api/dolphinscheduler/v1/alter-groups
```
+ Create a sub resources
```
Method: POST
/api/dolphinscheduler/v1/alter-groups/{alterGroupId}/tasks
```

### 3. Update
PUT or PATCH is use to update. Their differences are as follows：
+ PUT means full update, the requester needs to provide a complete resource instance in `JSON`, and the receiver generally receives uses `body` to receive it.
+ Patch means incremental update. The requester provides parameters on demand without providing a complete resource instance. The receiver generally receives it with `param`.
And URI is used to locate the resource to be updated.
```
Method: Patch
/api/dolphinscheduler/v1/alter-groups/{alterGroupId}
```

### 4. Delete
DELETE is use to update and URI is used to locate the resource to be deleted.
```
Method: DELETE
/api/dolphinscheduler/v1/alter-groups/{alterGroupId}
```
However, for batch delete (delete resource array), it must use Post. Because the body of the delete request has no semantic meaning, and some gateways, agents and firewalls may directly peel off the body of the request after receiving the delete request.
```
Method: POST
/api/dolphinscheduler/v1/alter-groups/batch-delete
param: [...alterGroupIds]
```

#### Describe
For the description of resources, we generally use `GET`. URI is used to locate the resource, and the description is represented by a noun or adjective at the end
```
/api/dolphinscheduler/v1/tasks/health   # Query healthy tasks
/api/dolphinscheduler/v1/users/authed   # Query authorized users
/api/dolphinscheduler/v1/processes/gantt-chart  # Use Gantt chart to represent process
```

#### Action
For the action of resources, we generally use `POST`. URI is used to locate the resource, and the action is represented by a verb at the end.
```
/api/dolphinscheduler/v1/alter-groups/verify-name   # Verify the name of the alter group
```

## Parameter Design
There are two kinds of parameters: one is the request parameter and the other is the path parameter.
Parameter variables must be represented by small humps.  In addition, in the paging scenario, if the parameter entered by the user is less than 1, the front end needs to return it to the back end. 1 indicates that the first page is requested; When the backend finds that the parameter entered by the user is greater than the total number of pages, it will directly return to the last page.

### Base URL
The base of project URL need to prefix with `/api/dolphinscheduler/v1`.

### API Version
For better compatibility, some API interfaces may have different versions in use. So there is the concept of identifying versions.
In order to let users know the version clearly, we put the version on the URL

[This is the document for standardizing the project API](https://kdocs.cn/l/spOjvEzstRLk)

**Comment by marin-man** [comment]
In order to more intuitively display the changes, I put the changed interface code on the server. The following is the corresponding swagger document. [change-api](http://121.5.0.60:6543/api/dolphinscheduler/v1/doc.html)

**Comment by brave-lee** [comment]
Good job. Please put the content into the issue, not external links.

**Comment by marin-man** [comment]
> Good job. Please put the content into the issue, not external links.

Thank you for your correction. I have updated it as required.
