### ISSUE TITLE
[Question] Why scheduleTime was added by one day when run complement data?

### ISSUE THREAD

**Issue by atai-555** [apache/dolphinscheduler#5969]
I created workflow named "dwD_01" with shell node, and the shell is configured with variable [YYYY-MM-DD-1], which is the day before the current scheduleTime. When dwD_01 is executed,ScheduleTime is 2021-08-10 03:01:00, but I find that [YYYY-MM-DD-1] is also 20210810(not 20210809).And then I saw this line in the code ShellTask.java (L147):

if (CommandType.COMPLEMENT_DATA.getCode() == taskExecutionContext.getCmdTypeIfComplement()) {
    date = DateUtils. Add (taskExecutionContext getScheduleTime (), DAY_OF_MONTH, 1);
}

Why does it take an extra day here to fill data type operations?

the version of DolphinScheduler is 1.3.4

**Comment by Tandoy** [comment]
1. When you choose to supplement the data and run the workflow, dolphinscheduler will default the date +1, you can find the relevant date configuration instructions here：https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/system-manual.html
2. If you are not supplementing data, you can try $[yyyyMMdd-1]

**Comment by atai-555** [comment]
> 1. When you choose to supplement the data and run the workflow, dolphinscheduler will default the date +1, you can find the relevant date configuration instructions here：https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/system-manual.html
> 2. If you are not supplementing data, you can try $[yyyyMMdd-1]

Thanks for your reply, I found the configuration instructions now after your help. 
The configuration instructions said: The day before the scheduled time of the daily scheduling instance, the format is yyyyMMdd, when the data is supplemented, the date is +1.

I have a specific problem, I have two workflows ODS_01 and DWD_01,Dwd_01 depends on ODS_01. Today, ODS_01 was executed through the daily scheduling instance(scheduleTime is 2021-08-12 03:00:00), but DWD_01 was not executed. I started DWD_01 through the data complement task(scheduleTime is 2021-08-11 03:00:00), but because their dates were inconsistent, DWD_01 could not find the successful ODS_01 instance when checking whether the pre-dependent was completed.So it's been impossible to execute. 
Any reply would be appreciated.

**Comment by davidzollo** [comment]
> > 1. When you choose to supplement the data and run the workflow, dolphinscheduler will default the date +1, you can find the relevant date configuration instructions here：https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/system-manual.html
> > 2. If you are not supplementing data, you can try $[yyyyMMdd-1]
> 
> Thanks for your reply, I found the configuration instructions now after your help.
> The configuration instructions said: The day before the scheduled time of the daily scheduling instance, the format is yyyyMMdd, when the data is supplemented, the date is +1.
> 
> I have a specific problem, I have two workflows ODS_01 and DWD_01,Dwd_01 depends on ODS_01. Today, ODS_01 was executed through the daily scheduling instance(scheduleTime is 2021-08-12 03:00:00), but DWD_01 was not executed. I started DWD_01 through the data complement task(scheduleTime is 2021-08-11 03:00:00), but because their dates were inconsistent, DWD_01 could not find the successful ODS_01 instance when checking whether the pre-dependent was completed.So it's been impossible to execute.
> Any reply would be appreciated.

as I know, except the shell task type, other task types have bugs in the complement.  and 1.3.8 solved this issue, and 1.3.8 is in publishing process

**Comment by CalvinKirs** [comment]
fixed
