### ISSUE TITLE
Oracle DataSource Connection Failed

### ISSUE THREAD

**Issue by afandago** [apache/dolphinscheduler#5970]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
A clear and concise description of what the question is.

All configuration is done, according to the document of Official Site. But still can't connect to my Oracle data source, version of Oracle is  _11.2.0.4.0_ 

I've tried use different versions of ojdbc-jar,  ojdbc6-11.2.0.4.jar, ojdbc8-21.1.0.0.jar and ojdbc8-12.2.0.1.jar, but none of them worked.

**Which version of DolphinScheduler:**
 latest

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

![image](https://user-images.githubusercontent.com/16183552/128889691-29699154-7c19-4d73-9a1d-0103e683f60f.png)

**Comment by Tandoy** [comment]
After you put the different OJDBC jars in the lib folder of the Dolphin installation directory, did you restart the dolphin api-server and worker-server? If not, you can try it.

**Comment by afandago** [comment]
> After you put the different OJDBC jars in the lib folder of the Dolphin installation directory, did you restart the dolphin api-server and worker-server? If not, you can try it.

I've restart servers, I've also try to restart dockers, but still not work.

**Comment by chengshiwen** [comment]
@juha1995 There are two solutions:
1. Refer to the *How to support Oracle datasource in Datasource manage* in https://dolphinscheduler.apache.org/en-us/docs/1.3.6/user_doc/docker-deployment.html
2. Temporarily, if you just want to connect to a oracle datasource using `ojdbc8-19.9.0.0.jar`, not only you need to execute `docker cp ojdbc8-19.9.0.0.jar /opt/dolphinscheduler/lib` into `api`, `master` and `worker` container, you also need to restart all containers by `docker-compose restart`.
```
docker cp ojdbc8-19.9.0.0.jar docker-swarm_dolphinscheduler-api_1:/opt/dolphinscheduler/lib
docker cp ojdbc8-19.9.0.0.jar docker-swarm_dolphinscheduler-master_1:/opt/dolphinscheduler/lib
docker cp ojdbc8-19.9.0.0.jar docker-swarm_dolphinscheduler-worker_1:/opt/dolphinscheduler/lib
docker-compose restart
```

**Comment by afandago** [comment]
> @juha1995 There are two solutions:
> 
> 1. Refer to the _How to support Oracle datasource in Datasource manage_ in https://dolphinscheduler.apache.org/en-us/docs/1.3.6/user_doc/docker-deployment.html
> 2. Temporarily, if you just want to connect to a oracle datasource using `ojdbc8-19.9.0.0.jar`, not only you need to execute `docker cp ojdbc8-19.9.0.0.jar /opt/dolphinscheduler/lib` into `api`, `master` and `worker` container, you also need to restart all containers by `docker-compose restart`.
> 
> ```
> docker cp ojdbc8-19.9.0.0.jar docker-swarm_dolphinscheduler-api_1:/opt/dolphinscheduler/lib
> docker cp ojdbc8-19.9.0.0.jar docker-swarm_dolphinscheduler-master_1:/opt/dolphinscheduler/lib
> docker cp ojdbc8-19.9.0.0.jar docker-swarm_dolphinscheduler-worker_1r:/opt/dolphinscheduler/lib
> docker-compose restart
> ```

I've already did that, and I did that just now, not work...
![ds_bug](https://user-images.githubusercontent.com/16183552/129573887-8cf0f3de-1f25-4f9e-a39f-25edc1c96031.png)

**Comment by chengshiwen** [comment]
Have you checked that `ojdbc8-19.9.0.0.jar` exists in `/opt/dolphinscheduler/lib` and restart the containers?

**Comment by chengshiwen** [comment]
Close since no updates for long time

**Comment by afandago** [comment]
> Have you checked that `ojdbc8-19.9.0.0.jar` exists in `/opt/dolphinscheduler/lib` and restart the containers?

yes, all things done, but still not work
