### ISSUE TITLE
[Bug][dolphinscheduler-dao] queryLastRunningProcess sql in ProcessInstanceMapper.xml

### ISSUE THREAD

**Issue by atai-555** [apache/dolphinscheduler#5975]
**Describe the bug**
In method queryLastRunningProcess of ProcessInstanceMapper.xml, when judging the start time and the end time, the parentheses should be less.The version is latest.
**Code**
    <select id="queryLastRunningProcess" resultType="org.apache.dolphinscheduler.dao.entity.ProcessInstance">
        select
        <include refid="baseSql"/>
        from t_ds_process_instance
        where process_definition_code=#{processDefinitionCode}
        <if test="states !=null and states.length != 0">
            and state in
            <foreach collection="states" item="i" index="index" open="(" separator="," close=")">
                #{i}
            </foreach>
        </if>
        _<if test="startTime!=null and endTime != null ">
            and (schedule_time <![CDATA[ >= ]]> #{startTime} and schedule_time <![CDATA[ <= ]]> #{endTime}
            or start_time <![CDATA[ >= ]]> #{startTime} and start_time <![CDATA[ <= ]]> #{endTime})
        </if>_
        order by start_time desc limit 1
    </select>
   **It should look like this in the slash**
        _<if test="startTime!=null and endTime != null ">
            and ((schedule_time <![CDATA[ >= ]]> #{startTime} and schedule_time <![CDATA[ <= ]]> #{endTime})
            or (start_time <![CDATA[ >= ]]> #{startTime} and start_time <![CDATA[ <= ]]> #{endTime}))
        </if>_

Pls check it, thank you.

**Comment by zhuangchong** [comment]
@atai-555 
Can you submit a PR to fix this problem?

**Comment by atai-555** [comment]
> @atai-555
> Can you submit a PR to fix this problem?

Yes, but I don't know how to 

> @atai-555
> Can you submit a PR to fix this problem?

I'd love to do it, but I don't know how to qualify to submit PR.

**Comment by atai-555** [comment]
> @atai-555
> Can you submit a PR to fix this problem?

I'd love to do it, but I don't know how to qualify to submit PR.

**Comment by zhuangchong** [comment]
@atai-555 

https://dolphinscheduler.apache.org/zh-cn/community/development/pull-request.html

I think we can get deep communiction, you can contact me through mail or add wechat(KerwinZhuang), when mail or added, please tell me who you are, I think I can help to familiar with the DolphinScheduler if you meet with problems.

**Comment by atai-555** [comment]
> @atai-555
> 
> https://dolphinscheduler.apache.org/zh-cn/community/development/pull-request.html
> 
> I think we can get deep communiction, you can contact me through mail or add wechat(KerwinZhuang), when mail or added, please tell me who you are, I think I can help to familiar with the DolphinScheduler if you meet with problems.

Thank you @zhuangchong , I will contact you with wechat.
