### ISSUE TITLE
Since DataX is particularly inefficient to write greenplum, how do I switch DataX to addax plugin

### ISSUE THREAD

**Issue by cxin-william** [apache/dolphinscheduler#5978]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/community/development/issue.html when describe an issue.*

**Describe the feature**
A clear and concise description of what the feature is.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gaogen123** [comment]
can you support gpdbwriter in datax? You know Datax synchronizes data through gpdbwriter  much faster than JDBC in greenplum。You can refer to this link 
https://github.com/HashDataInc/DataX/blob/master/gpdbwriter/src/main/java/cn/hashdata/datax/plugin/writer/gpdbwriter/CopyProcessor.java  。
