### ISSUE TITLE
The front-end page cannot be accessed

### ISSUE THREAD

**Issue by asheswang** [apache/dolphinscheduler#5981]
按照官方文档安装了最新版1.3.6，所有进程正常启动，但是前端web页面（端口12345）无法访问，查看端口监听情况，发现端口12345没有起来。想问一下这是什么情况？要怎么解决

**Comment by zhuangchong** [comment]
@asheswang 
Please check the detailed log of the API module.

**Comment by caoyj1991** [comment]
1. telnet to check the port
2. ```ps -ef | grep java``` check the backend process 
3. check the logs dolphinscheduler-dir/logs

**Comment by davidzollo** [comment]
no feedback for two weeks, I will close this issue temporarily, you can reopen it if you have any question
