### ISSUE TITLE
[Bug][master and worker] After the workflow instance is stopped, the task task will not be killed

### ISSUE THREAD

**Issue by gaoyu2016** [apache/dolphinscheduler#5982]
是工作流kill掉后，已经在跑的任务不会被kill掉，后续的任务确实不会启动了。

**Comment by gaoyu2016** [comment]
是工作流kill掉后，已经在跑的任务不会被kill掉，后续的任务确实不会启动了。

**Comment by gaoyu2016** [comment]
[INFO] 2021-08-12 22:19:17.056  - [taskAppId=TASK-447-108656-85708]:[127] -  -> Query ID = maintain_20210812221910_c1590613-28f2-429e-a8b1-3e1780ef3116
        Total jobs = 1
        Launching Job 1 out of 1
        Number of reduce tasks determined at compile time: 1
        In order to change the average load for a reducer (in bytes):
          set hive.exec.reducers.bytes.per.reducer=<number>
        In order to limit the maximum number of reducers:
          set hive.exec.reducers.max=<number>
        In order to set a constant number of reducers:
          set mapreduce.job.reduces=<number>
        Starting Job = job_1627376795139_3623, Tracking URL = http://soho-pipe-sata1-pm:8080/proxy/application_1627376795139_3623/
[INFO] 2021-08-12 22:19:25.239  - [taskAppId=TASK-447-108656-85708]:[127] -  -> Kill Command = /home/maintain/hadoop/hadoop/curr_hadoop/bin/hadoop job  -kill job_1627376795139_3623
        Hadoop job information for Stage-1: number of mappers: 0; number of reducers: 1
[INFO] 2021-08-12 22:19:27.271  - [taskAppId=TASK-447-108656-85708]:[127] -  -> 2021-08-12 22:19:25,291 Stage-1 map = 0%,  reduce = 0%
        /home/maintain/ds-1.3.4.2/tmp/dolphinscheduler/exec/process/21/447/108656/85708/447_108656_85708_node.sh: line 2: 28758 Killed                  hive -e 'select count(1) from dw_ads.ads_eng_user_profile_basic_di where dt='2021-07-21';
[INFO] 2021-08-12 22:19:27.273  - [taskAppId=TASK-447-108656-85708]:[127] -  -> '

**Comment by gaoyu2016** [comment]
![image](https://user-images.githubusercontent.com/29685418/129213953-e2d470d1-bd4a-4dc8-925a-218d538032a3.png)

**Comment by gaoyu2016** [comment]
who can help me ?

**Comment by CalvinKirs** [comment]
Can you provide complete contextual information? Also, please use English.

**Comment by gaoyu2016** [comment]
1.3.4版本。提交一个hive任务。

**Comment by gaoyu2016** [comment]
描述的很清楚不了。

**Comment by CalvinKirs** [comment]
Sorry,for better communication, please use English.




On 08/16/2021 ***@***.***> wrote：

描述的很清楚不了。

**Comment by gaoyu2016** [comment]
![image](https://user-images.githubusercontent.com/29685418/129695489-36526a75-27e0-4d37-bcd1-94beefa505a9.png)

**Comment by gaoyu2016** [comment]
![image](https://user-images.githubusercontent.com/29685418/129695598-8c41d22e-25f9-4da9-b958-0d7eefeb21eb.png)
