### ISSUE TITLE
[Feature][Server] Support to set multiple environment configs for a certain worker.

### ISSUE THREAD

**Issue by calvinjiang** [apache/dolphinscheduler#5987]
**Describe the feature**

Now we can set an environment config in the file 'dolphinscheduler_env.sh' , but probably you need to modify this file in many servers. And a worker can't support to switch environment from one to another.So I expect that I can choose an environment config for different tasks.

**Describe the solution you'd like**
1.Add a web page to manage environments and create multiple environments in this page.
2.You can set some config like 'dolphinscheduler_env.sh' in a new environment and save it.
3.A certain worker group can have multiple environments, so need to link them together.
4.When set the config of a task, you may choose an environment to run this task.
5.Before running a task, the system will make up the file 'dolphinscheduler_env.sh' for this task.

**Comment by zhuangchong** [comment]
+1
good idea

**Comment by CalvinKirs** [comment]
Very good advice, but what we need to consider is the priority and permissions of the parameters of these different environments.

**Comment by calvinjiang** [comment]
> Very good advice, but what we need to consider is the priority and permissions of the parameters of these different environments.

Yup, I will consider this. It's important and serious to  set an environment. So It should be done by the administrator.

**Comment by CalvinKirs** [comment]
@calvinjiang hi, can you add this doc to the website?
