### ISSUE TITLE
[Question] why not worker update task instance status after task completes

### ISSUE THREAD

**Issue by lightning-L** [apache/dolphinscheduler#5993]
I know that the current design is: 

- worker will execute the task (TaskExecuteThread.java#run)
- after task is finished, call back service will send TaskExecuteResponseCommand to master
- then master will update the cache, and save the task status into db. (TaskResponseService.java#persist)

I wonder why not worker update task instance status after task completes. And I noticed that master is checking task instance table to update the process instance status (MasterExecThread.java#runProcess).
After worker updates the task status, it can still send rpc request to master to update the cache.

And what is the benefit the current design(master update the task instance status)?

**Comment by CalvinKirs** [comment]
The worker is responsible for the execution of tasks, does not interact with the database, and is managed by the master to maintain the execution of subsequent tasks

**Comment by geosmart** [comment]
the master responsible to interact with database,  package the db data with command and send it by netty.
so the worker just need to run the task and return the result. 

this is more simple than both master and worker need to interact with db.
