### ISSUE TITLE
[Bug][ShellTask] use ShellTask to start a java job, but can not stop task

### ISSUE THREAD

**Issue by HomminLee** [apache/dolphinscheduler#5999]
**Describe the bug**
I use SHELL task to start a java job. I try to stop this task, but shell task not stop and java process still running.

**To Reproduce**

1. I have some java code to run, so create a jar and put it to dolphinscheduler resource center. Java code is simple: print a num every 5 seconds with an infinite loop.
2. I definition a process, and create a SHELL task to run the jar whit cmd `java -cp print-1.0-SNAPSHOT.jar com.hommin.demo.tmp.PrintPer5S`.
3. I run the process definition, and there appear  a process instance and a task instance. Also, java job works perfectly, print num continuously.
4. I Click  the STOP button to stop the task in process instance page. Then process instance state becomes stopped. Very good so far.
5. But I turn to task instance page, find the SHELL task still running and java job still running( print num continue in log).
6. Can not find another way to stop this SHELL task in dolphin webUi.

**Expected behavior**
When I click the button to stop process instance, shell task will be killed and jar job will stop.

**Screenshots**
![image](https://user-images.githubusercontent.com/25881185/129834044-bced989c-4a4b-4cf4-93e1-19c39df51681.png)

![image](https://user-images.githubusercontent.com/25881185/129830560-d656321e-0d98-4d88-bbd9-00c147cf29c1.png)

![image](https://user-images.githubusercontent.com/25881185/129830599-09915520-c06b-49a2-b4db-5f1236549301.png)

![image](https://user-images.githubusercontent.com/25881185/129830628-a33c7602-8912-4fe2-b721-19249269815b.png)

**Which version of Dolphin Scheduler:**
 -[1.3.6-RELEASE]

**Comment by CalvinKirs** [comment]
hi, can you provide the log of stopped tasks?

**Comment by HomminLee** [comment]
Sorry for reply too late. It's not a bug, stop task will use linux command 'pstree', but my linux server not found this command. After I install it by "yum -y install psmisc", stop was successed.
