### ISSUE TITLE
[Bug] No master node is available relation to https://github.com/apache/dolphinscheduler/issues/5491

### ISSUE THREAD

**Issue by lishiyucn** [apache/dolphinscheduler#6001]
dolphinscheduler version: 1.3.6
before I submit the issue https://github.com/apache/dolphinscheduler/issues/5491,
and I update the dolphin1.3.6 code to https://github.com/apache/dolphinscheduler/pull/5919/files,
**### there already exist the problem No master node is available**

@
dolphinscheduler-worker.log

`
[INFO] 2021-08-18 11:05:55.787 org.apache.zookeeper.ZooKeeper:[442] - Initiating client connection, connectString=bigdata:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@46394f65
[INFO] 2021-08-18 11:05:55.788 org.apache.curator.framework.state.ConnectionStateManager:[251] - State change: LOST
[INFO] 2021-08-18 11:05:55.790 org.apache.zookeeper.ClientCnxn:[1025] - Opening socket connection to server bigdata/10.6.10.59:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2021-08-18 11:05:55.790 org.apache.zookeeper.ClientCnxn:[522] - EventThread shut down for session: 0x17abd281ce138cc
[ERROR] 2021-08-18 11:05:55.790 org.apache.dolphinscheduler.service.zk.ZookeeperOperator:[83] - connection lost from zookeeper
[INFO] 2021-08-18 11:05:55.790 org.apache.zookeeper.ClientCnxn:[879] - Socket connection established to bigdata/10.6.10.59:2181, initiating session
[INFO] 2021-08-18 11:05:55.791 org.apache.zookeeper.ClientCnxn:[1299] - Session establishment complete on server bigdata/10.6.10.59:2181, sessionid = 0x17abd281ce45b7d, negotiated timeout = 60000
[INFO] 2021-08-18 11:05:55.792 org.apache.curator.framework.state.ConnectionStateManager:[251] - State change: RECONNECTED
[INFO] 2021-08-18 11:05:55.795 org.apache.dolphinscheduler.service.zk.ZookeeperOperator:[85] - reconnected to zookeeper
[INFO] 2021-08-18 11:06:12.736 org.apache.dolphinscheduler.server.worker.WorkerServer:[151] - worker server is stopping ..., cause : i was judged to death, release resources and stop myself
[INFO] 2021-08-18 11:06:15.781 org.apache.dolphinscheduler.remote.NettyRemotingServer:[237] - netty server closed
[INFO] 2021-08-18 11:06:15.813 org.apache.dolphinscheduler.server.worker.registry.WorkerRegistry:[141] - worker node : 10.6.10.59:1234 unRegistry from ZK /dolphinscheduler/nodes/worker/default/10.6.10.59:1234.
[INFO] 2021-08-18 11:06:15.813 org.apache.dolphinscheduler.server.worker.registry.WorkerRegistry:[144] - heartbeat executor shutdown
[WARN] 2021-08-18 11:07:03.867 org.apache.dolphinscheduler.server.worker.runner.RetryReportTaskStatusThread:[90] - retry report task status error
java.lang.IllegalStateException: all available master nodes : null are not reachable for task: {}
        at org.apache.dolphinscheduler.server.worker.processor.TaskCallbackService.getRemoteChannel(TaskCallbackService.java:131)
        at org.apache.dolphinscheduler.server.worker.processor.TaskCallbackService.sendResult(TaskCallbackService.java:177)
        at org.apache.dolphinscheduler.server.worker.runner.RetryReportTaskStatusThread.run(RetryReportTaskStatusThread.java:86)
        at java.lang.Thread.run(Thread.java:748)

`

dolphinscheduler-master.log

`
[INFO] 2021-08-18 11:06:23.530 org.apache.dolphinscheduler.server.master.runner.MasterTaskExecThread:[102] - task :DwdIdsDns id:10061, process id:8337, exec thread completed
[INFO] 2021-08-18 11:06:23.587 org.apache.dolphinscheduler.server.master.runner.MasterExecThread:[925] - process:9832 end, state :RUNNING_EXECUTION
[INFO] 2021-08-18 11:06:23.604 org.apache.dolphinscheduler.server.master.runner.MasterTaskExecThread:[102] - task :task-19142 id:10062, process id:9832, exec thread completed
[INFO] 2021-08-18 11:06:25.933 org.apache.dolphinscheduler.remote.NettyRemotingClient:[403] - netty client closed
[INFO] 2021-08-18 11:06:25.933 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[111] - master schedule service stopped...
[INFO] 2021-08-18 11:06:25.967 org.apache.dolphinscheduler.remote.NettyRemotingServer:[237] - netty server closed
[INFO] 2021-08-18 11:06:25.968 org.apache.dolphinscheduler.server.master.registry.MasterRegistry:[118] - master node : 10.6.10.59:5678 unRegistry to ZK.
[INFO] 2021-08-18 11:06:25.968 org.apache.dolphinscheduler.server.master.registry.MasterRegistry:[120] - heartbeat executor shutdown
[INFO] 2021-08-18 11:06:26.475 org.apache.curator.framework.imps.CuratorFrameworkImpl:[955] - backgroundOperationsLoop exiting
[INFO] 2021-08-18 11:06:26.478 org.apache.zookeeper.ZooKeeper:[693] - Session: 0x17abd281ce45b6d closed
[INFO] 2021-08-18 11:06:26.478 org.apache.zookeeper.ClientCnxn:[522] - EventThread shut down for session: 0x17abd281ce45b6d
[INFO] 2021-08-18 11:06:26.482 org.quartz.core.QuartzScheduler:[666] - Scheduler DolphinScheduler_$_bigdata1627920426344 shutting down.
[INFO] 2021-08-18 11:06:26.483 org.quartz.core.QuartzScheduler:[585] - Scheduler DolphinScheduler_$_bigdata1627920426344 paused.
[INFO] 2021-08-18 11:06:26.516 com.alibaba.druid.pool.DruidDataSource:[1928] - {dataSource-1} closed
[INFO] 2021-08-18 11:06:26.521 org.quartz.core.QuartzScheduler:[740] - Scheduler DolphinScheduler_$_bigdata1627920426344 shutdown complete.
[INFO] 2021-08-18 11:06:26.521 org.apache.dolphinscheduler.service.quartz.QuartzExecutors:[171] - Quartz service stopped, and halt all tasks
[INFO] 2021-08-18 11:06:26.521 org.apache.dolphinscheduler.server.master.MasterServer:[182] - Quartz service stopped

`

**Comment by lishiyucn** [comment]
@ruanwenjun Please pay attentiom to the question.

**Comment by ruanwenjun** [comment]
@lishiyucn Have you also update the code in this pr,  this pr has fixed the reconnected issue.
https://github.com/apache/dolphinscheduler/pull/5211
