### ISSUE TITLE
[Improvement][official website] pstree should be listed in the documentation as an application that must be installed

### ISSUE THREAD

**Issue by Squidyu** [apache/dolphinscheduler#6006]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/community/development/issue.html when describe an issue.*

**Describe the question**
If pstree does not exist on the DS installation machine, the kill operation to stop the process will fail, and the task will continue to run

--pstree 在ds安装机器不存在的话会导致停止进程的kill操作执行失败，任务会继续运行

**What are the current deficiencies and the benefits of improvement**
 The mandatory software on the official website indicates the need for pstree, which can avoid many users stepping on the pit
--在官网的必装软件中提示需要pstree能够避免很多用户踩坑

**Which version of DolphinScheduler:**
 -[all]

**Describe alternatives you've considered**
Specify the need for pstree in the mandatory software on the official website
--在官网的必装软件中写明需要pstree

**Comment by Squidyu** [comment]
I will bring a PR to the official website document

**Comment by Squidyu** [comment]
> I will bring a PR to the official website document

I've already mentioned a [pr ](https://github.com/apache/dolphinscheduler-website/pull/425)

**Comment by davidzollo** [comment]
good job
