### ISSUE TITLE
[Feature][service] Better support for dependent task scheduling

### ISSUE THREAD

**Issue by DylanMao1996** [apache/dolphinscheduler#6008]
1.In a Python project, calling a Python file separately, but relying on other Python files in the project, is not a good experience at the moment
2.For some commonly used exception alert, can you provide more detailed questions when explaining

**Comment by CalvinKirs** [comment]
Great suggestion, can you be more specific.

**Comment by DylanMao1996** [comment]
I am currently trying to migrate my company's schedule Airflow to DolphinScheduler. The company's projects are Python projects, and each file in the project has dependencies, so we want to call a separate Python file to perform the task. However, in the current dolphinScheduler, there is no straightforward way to configure Python projects, and the file explorer has to be created one by one. The sensory experience is not very good.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月20日(星期五) 下午4:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/dolphinscheduler] [Feature][service] Better support for dependent task scheduling (#6008)





 
Great suggestion, can you be more specific.
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
