### ISSUE TITLE
[Improvement][dist] Remove useless packaging commands

### ISSUE THREAD

**Issue by Narcasserun** [apache/dolphinscheduler#6024]
**Describe the question**

Remove useless packaging commands

**What are the current deficiencies and the benefits of improvement**

In the common module, there is no Src / main / resources / bin directory, but the dist module will still execute relevant commands when packaging, which is unreasonable

**Which version of DolphinScheduler:**

-[1.3.7-release]

**Describe alternatives you've considered**

Remove the dolphinscheduler-common / src / main / resources / bin  directory packaging command in dolphinscheduler -bin.xml in dist module

**Comment by CalvinKirs** [comment]
thx for your feedback, welcome you submit Pull Request:)

**Comment by Narcasserun** [comment]
> thx for your feedback, welcome you submit Pull Request:)

I have submitted pr. this is my first PR in DS. It's great
