### ISSUE TITLE
[Bug][Datax] Rerun data-patch workflow instance trigger the entire data-patch dispatch

### ISSUE THREAD

**Issue by simsicon** [apache/dolphinscheduler#6032]
When running a data-patch workflow, for example from date 2021-08-01 to 2021-08-20, if one instance failed, let's say 2021-08-10 instance failed, click rerun, the the entire data-patch (from 2021-08-01 to 2021-08-20) triggered again.

My expectation should just rerun 2021-08-10 workflow instance

**Which version of Dolphin Scheduler:**
 -[1.3.6]

**Comment by Tandoy** [comment]
Maybe you can try to set the complement workflow to end after failure, and then click the restore failure button after processing to continue the complement from the failed workflow.

**Comment by simsicon** [comment]
> Maybe you can try to set the complement workflow to end after failure, and then click the restore failure button after processing to continue the complement from the failed workflow.

Thanks, I will test it next time, this issue is closed for now.
