### ISSUE TITLE
[Question] Task dependency

### ISSUE THREAD

**Issue by Tandoy** [apache/dolphinscheduler#6033]
**Describe the question**
The three tasks are dependent. When I choose to prohibit execution of the intermediate task, the last task will still be executed. Does this not conform to the logic of dependence?

**Which version of DolphinScheduler:**
 -[1.3.2]

**Additional context**
![企业微信截图_16298836622715](https://user-images.githubusercontent.com/56899730/130766887-e7050ac9-0f4b-4f8c-a2c5-8f5ae74d552a.png)

When I choose to prohibit execution of a task in the middle, and subsequent tasks that depend on it are not executed, is it more in line with dependence?

**Comment by davidzollo** [comment]
It only can stop the task itself for now. 
I think you can submit a new [Feature] issue to describe what you wanted,

IMO, I think we can design this feature to different choices for users, some users like current feature, and some other users like you need to stop the subsequent tasks, I think you can give better choices, please go on

**Comment by Tandoy** [comment]
Thanks for your reply, I will submit a new [Feature] issue.
