### ISSUE TITLE
why my shell task never finish?

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#6034]
**Which version of DolphinScheduler:**
1.3.6

**log of the task:**

![image](https://user-images.githubusercontent.com/19989300/130799090-bcc805da-9ea4-48b0-97ec-a66f31ede1b5.png)

**all sql have run sucess ,but the task never finished.**

**shell:**

```
#!/bin/sh

exec /data/soft/spark3/bin/beeline -n name -p 123456 -u  'jdbc:hive2://worker-10-0-161-21:2181,worker-10-0-161-22:2181,worker-10-0-161-20:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=kyuubi' -f '/data/scripts/datax/hdp-doc/scripts/sk/test.sql'

exit;

```

**Comment by davidzollo** [comment]
I want to know the final status about this task on hadoop Yarn cluster, please view the final status on the yarn web ui first

**Comment by davidzollo** [comment]
The principle of judging whether the task is successful or not:
1. the shell task exit code, and code equals 0 means it exits successfully
2. If this task is running on the yarn, DS will also try to get the final status of this yarn application through the yarn rest API which was been configured in the conf/common.properties ``

you also can check the worker server runtime log, maybe some exceptions throw out in the log

**Comment by lordk911** [comment]
Thank you for your reply. 
Yes the reason is my yarn application not finsh after all sql task finsh.
