### ISSUE TITLE
version:1.3.6,start API, see the console log  apiServerApplicaiton's port is 8080. but the properties server.port is 12345, why it doesn't work?

### ISSUE THREAD

**Issue by meyp** [apache/dolphinscheduler#6036]
**Describe the question**
 Run the masterServer,workerServer,apiServerApplication successful,and install the dolphinscheduler-ui is ok, but i cannot visit the views. i see the console log  apiServerApplicaiton's port is 8080. but the properties server.port is 12345, why it doesn't work?

2021-08-26 08:31:25.400  INFO 100672 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
2021-08-26 08:31:25.443  INFO 100672 --- [           main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
2021-08-26 08:31:25.761  INFO 100672 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: viewTreeUsingGET_1
2021-08-26 08:31:25.912  INFO 100672 --- [           main] o.e.j.s.h.ContextHandler.application     : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-08-26 08:31:25.930  INFO 100672 --- [           main] org.mortbay.log                          : Logging to Logger[org.mortbay.log] via org.mortbay.log.Slf4jLog
2021-08-26 08:31:26.188  INFO 100672 --- [           main] o.e.jetty.server.AbstractConnector       : Started ServerConnector@29a98d9f{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}

**Which version of DolphinScheduler:**
 -[release1.3.6]

**Comment by ljmiaoo** [comment]
> **Describe the question**
> Run the masterServer,workerServer,apiServerApplication successful,and install the dolphinscheduler-ui is ok, but i cannot visit the views. i see the console log apiServerApplicaiton's port is 8080. but the properties server.port is 12345, why it doesn't work?
> 
> 2021-08-26 08:31:25.400 INFO 100672 --- [ main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
> 2021-08-26 08:31:25.443 INFO 100672 --- [ main] s.d.s.w.s.ApiListingReferenceScanner : Scanning for api listing references
> 2021-08-26 08:31:25.761 INFO 100672 --- [ main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: viewTreeUsingGET_1
> 2021-08-26 08:31:25.912 INFO 100672 --- [ main] o.e.j.s.h.ContextHandler.application : Initializing Spring DispatcherServlet 'dispatcherServlet'
> 2021-08-26 08:31:25.930 INFO 100672 --- [ main] org.mortbay.log : Logging to Logger[org.mortbay.log] via org.mortbay.log.Slf4jLog
> 2021-08-26 08:31:26.188 INFO 100672 --- [ main] o.e.jetty.server.AbstractConnector : Started ServerConnector@29a98d9f{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
> 
> **Which version of DolphinScheduler:**
> -[release1.3.6]

add `@PropertySource(ignoreResourceNotFound = false, value = "classpath:application-api.properties")` to ApiApplicationServer Class and restart apiServer

**Comment by chengshiwen** [comment]
@meyp Please set VM options like

![image](https://user-images.githubusercontent.com/4902714/131208936-7902e6ec-744d-47f2-bf8e-46aa1e13cd2a.png)

**Comment by meyp** [comment]
> > **Describe the question**
> > Run the masterServer,workerServer,apiServerApplication successful,and install the dolphinscheduler-ui is ok, but i cannot visit the views. i see the console log apiServerApplicaiton's port is 8080. but the properties server.port is 12345, why it doesn't work?
> > 2021-08-26 08:31:25.400 INFO 100672 --- [ main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
> > 2021-08-26 08:31:25.443 INFO 100672 --- [ main] s.d.s.w.s.ApiListingReferenceScanner : Scanning for api listing references
> > 2021-08-26 08:31:25.761 INFO 100672 --- [ main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: viewTreeUsingGET_1
> > 2021-08-26 08:31:25.912 INFO 100672 --- [ main] o.e.j.s.h.ContextHandler.application : Initializing Spring DispatcherServlet 'dispatcherServlet'
> > 2021-08-26 08:31:25.930 INFO 100672 --- [ main] org.mortbay.log : Logging to Logger[org.mortbay.log] via org.mortbay.log.Slf4jLog
> > 2021-08-26 08:31:26.188 INFO 100672 --- [ main] o.e.jetty.server.AbstractConnector : Started ServerConnector@29a98d9f{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
> > **Which version of DolphinScheduler:**
> > -[release1.3.6]
> 
> add `@PropertySource(ignoreResourceNotFound = false, value = "classpath:application-api.properties")` to ApiApplicationServer Class and restart apiServer

ok, thanks
