### ISSUE TITLE
[Feature] Task dependency

### ISSUE THREAD

**Issue by Tandoy** [apache/dolphinscheduler#6039]
**Describe the feature**
Now after selecting a task to prohibit execution in the workflow, the downstream tasks that depend on it will still be executed. 
Sometimes it is necessary to prohibit the execution of the current task, and subsequent tasks will not be executed. This will also help shorten the complement time.

**Describe the solution you'd like**
Maybe we can add an option for prohibiting execution and its downstream tasks next to the prohibiting execution button

**Additional context**
![企业微信截图_1629947371878](https://user-images.githubusercontent.com/56899730/130894326-30ca9a70-c4f4-49bc-be26-412562352380.png)

**Comment by CalvinKirs** [comment]
Does anyone else have any thoughts on this?
