### ISSUE TITLE
 Badly formatted multipart request  by jar file

### ISSUE THREAD

**Issue by testteam001** [apache/dolphinscheduler#6043]
![image](https://user-images.githubusercontent.com/18347994/130942717-9acc37fb-1a85-42bc-9a20-7ff75dbef79f.png)
![image](https://user-images.githubusercontent.com/18347994/130942783-686b2557-99d9-4d6a-8674-6fe3cb00baf6.png)

**Comment by chengshiwen** [comment]
@testteam001 Which version of ds?

**Comment by testteam001** [comment]
> @testteam001 Which version of ds?

1.3.6
