### ISSUE TITLE
[Bug][api] createProcessDefinition return error

### ISSUE THREAD

**Issue by MrTaozui** [apache/dolphinscheduler#6047]
**[BUG][Critical] 创建流程api 返回数据错误** 

**DolphinScheduler版本** 
 -[master]

**问题描述**
ProcessDefinitionService.createProcessDefinition()
方法中预计返回流程id 
代码处：result.put(PROCESSDEFINITIONID,processDefine.getId());
但是上层ProcessDefinitionController.createProcessDefinition()中 把值过滤掉了并没有返回。

**期望的表现:**
调用创建流程接口 返回流程id

**Comment by zhuangchong** [comment]
@MrTaozui 
The master branch has not been maintained for a while, the latest code is on the dev branch, and this part of the dev branch has been modified.

```
result.put(Constants.DATA_LIST, processDefinition.getId());
```
