### ISSUE TITLE
Several issues or requirements from a product perspective（从产品角度的提供的若干问题或需求）

### ISSUE THREAD

**Issue by jet2007** [apache/dolphinscheduler#605]
1. Workflow instance page: Add a running time instance of the workflow instance: for example, the workflow is defined as the 20th minute hourly scheduling, the running time = 2019-07-01 01:20:00, 2019-07- 01 02:20:00, 2019-07-01 03:20:00; Reference value t_escheduler_process_instance.schedule_time field (consider "run type" for scheduling execution, complement, start workflow value)
2. Workflow instance page: "Pause and stop" icon meaning - "opposite", "rerun" icon: suggested to change one (currently refreshed)
3. Workflow instance page: GANT diagram - show all tasks, increase the unexecuted state of the task (such as gray)
4. Workflow definition page: The project level (higher than the workflow) defines global variables; the workflow under the project, the task inherits the relevant variables;
5. View log optimization: print log line feed is wrong, some print [INFO], some do not print
6. Search for task instance: increase searchable workflow instance name
7. Task Dependency: Support cross-project workflow dependencies, even across users; currently supports dependencies under the same project
8. Project privilege: Cross-user project privilege: First, the currently editable privilege (manager), add another-read privilege (viewer)---1. Can only view, not editable; 2. Can Set dependencies; second, the permission level can be refined to the workflow, not an entire project

---
1. 工作流实例页面：增加一个工作流实例的跑数时间列：比如工作流定义为每小时第20分钟调度时，跑数时间=2019-07-01 01:20:00, 2019-07-01 02:20:00, 2019-07-01 03:20:00; 参考取值t_escheduler_process_instance.schedule_time字段(考虑“运行类型”为 调度执行,补数,启动工作流 的取值)
2. 工作流实例页面：“暂停与停止”的图标含义--“相反”，“重跑”图标：建议换一个(当前为刷新)
3. 工作流实例页面：GANT图-展示所有task的，增加未执行状态的task（比如灰色）
4. 工作流定义页面：项目级（比工作流高一级）定义全局变量；项目下的工作流，任务继承相关变量；
5. 查看日志优化:打印日志换行不对,有的打印[INFO],有的不打印
6. 任务实例的search: 增加可搜索工作流实例名
7. 任务依赖： 支持跨项目的工作流依赖，甚至跨用户；当前支持同项目下的依赖
8. 项目权限：跨用户的项目权限：一、当前为可编辑的权限（管理者），增加另一种-读权限（查看者）---1.只能查看，不可编辑；2.可设置依赖；二、权限级别可细化到工作流，而不是一整个项目

**Comment by boandai** [comment]
great advice！

**Comment by qq389401879** [comment]
这个需求提得非常好，希望团队把优先级放到最高！

**Comment by zhuxt2015** [comment]
great advice！
