### ISSUE TITLE
[Question] How to use alarm

### ISSUE THREAD

**Issue by Tsd-217** [apache/dolphinscheduler#6064]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
A clear and concise description of what the question is.

**Which version of DolphinScheduler:**
 -data_quality_design

**Additional context**
When I configured the alarm service on dolphinschedulerUI, I couldn't find the plug-in instance

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.
<img width="1175" alt="ds_question" src="https://user-images.githubusercontent.com/69764229/131306016-f36bc702-1770-44cd-a620-52555eec0260.png">

**Comment by CalvinKirs** [comment]
There is currently no official release, you can check this document.
#3049
http://dolphinscheduler.apache.org/en-us/docs/dev/user_doc/alert_spi.html
