### ISSUE TITLE
The password in the json generated by the DataX task is *****, causing the connection to the data source to fail

### ISSUE THREAD

**Issue by Xenos3811** [apache/dolphinscheduler#6066]
![image](https://user-images.githubusercontent.com/34369858/131339064-c1af857b-55ee-42c6-9e43-c2c945ce97a9.png)
![image](https://user-images.githubusercontent.com/34369858/131339151-d033ae38-c660-4c88-b7ef-b78d90a3dc9c.png)

**Comment by CalvinKirs** [comment]
which version?

**Comment by zhuangchong** [comment]
@Xenos3811 

It has been verified in the dev branch and this issue has not been reproduced. I will close this issue first. If there are still issues, you can open this issue here.
