### ISSUE TITLE
hive on spark cannot run on dolphinscheduler

### ISSUE THREAD

**Issue by wangfeigithub** [apache/dolphinscheduler#6069]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
A clear and concise description of what the question is.

**Which version of DolphinScheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by CalvinKirs** [comment]
Can you provide more detailed information

**Comment by wangfeigithub** [comment]
> Can you provide more detailed information
Please wait a moment. I'm rebuilding dolphinScheduler and watching

**Comment by wangfeigithub** [comment]
![image](https://user-images.githubusercontent.com/29723968/131470629-60f587e9-88d4-4b70-90f7-bc1e8ed0ba76.png)

Please help to check the error log, I can execute HQL in other places. But dolphinScheduler reported an error

**Comment by Narcasserun** [comment]
UDF resources have not been loaded. You can check the resource configuration of the task

**Comment by wangfeigithub** [comment]
I did not configure udF, just hive SQL
