### ISSUE TITLE
Product Features - Package Job Type（产品功能-封装作业类型）

### ISSUE THREAD

**Issue by jet2007** [apache/dolphinscheduler#607]
**Process Edit Page: Toolbar - Package Job Type**
- Status: Currently only supports general-purpose languages ​​such as shell, python, sql, procedure, etc.;
- Example: Import and export data requirements such as data warehouse; business content xxxxxx in the example is where each configuration is not required, and other content is unchanged.
- Purpose:
    1. Manager of the scheduling system ---- define a certain type of task script content for packaging
    1. Make the developers of the scheduling system only need to configure [the most core business script + scheduling options, without the need to configure technical scripts]
    1. Business script----xxxxxxx part of setttings
    1. Technical script ---- this task is python implementation, call a certain method, etc.
- Benefits: 1. The scalability is greatly enhanced; 2. The workload of the developer of the scheduling system is greatly reduced.
- Idea:
     1. Open only shell, python two types of package jobs
     1. Add a product page to define the [package job type]; take python as an example, schedule the system administrator, pre-configure the [technical implementation details] of the script, and open the [business] to the developer.
    1. The developer of the scheduling system can configure [the most core business script + scheduling option] after selecting a certain [package job type] in the toolbar of the process editing page.
   

```
######################## A task script: /path/func.py

#业务内容
Setttings=r'''
Xxxxxx
Xxxxxx
Xxxxxx
'''

#Technical realization
...
...
...
Call(setttings)


#####################################################################################
#业务内容
Setttings=r'''
${1}
'''

#Technical realization
...
...
...
Call(setttings)

    
```

---
**流程编辑页面：工具栏-封装作业类型**
- 现状：当前只支持如shell,python,sql,procedure等这种语言性质的通用型；
- 示例：如数据仓库的导入导出数据需求;示例中的业务内容xxxxxx是每次需要配置不的地方，其他内容都是不变的
- 目的：
    1. 调度系统的管理者----定义某一类任务脚本内容进行封装
    1. 使得调度系统的开发者只需要配置【最核心的业务脚本+调度选项，而不需要配置技术脚本】
    1. 业务脚本----setttings中的xxxxxxx部分
    1. 技术脚本----该任务是python实现，调用某某方法等
- 好处：1.扩展性大大增强；2.调度系统的开发者的工作量大大减轻
- 思路：
     1. 只开放shell,python两种的封装作业类型
     1. 增加一个产品的页面，来定义【封装作业类型】；以python为例，调度系统的管理者，预先配置好脚本的【技术实现细节】，把【业务】开放给开发者
    1. 调度系统的开发者，可在流程编辑页面的工具栏，选择某个【封装作业类型】后，配置【最核心的业务脚本+调度选项】
   

```
########################某个任务脚本：/path/func.py 

#业务内容
setttings=r'''
xxxxxx
xxxxxx
xxxxxx
'''

#技术实现
...
...
...
call(setttings)


######################## 【封装作业类型】后的python作业,其中${1}是让开发填写[业务]
#业务内容
setttings=r'''
${1}
'''

#技术实现
...
...
...
call(setttings)

    
```

**Comment by zhuxt2015** [comment]
great advice！
