### ISSUE TITLE
can i complement data by calling api?

### ISSUE THREAD

**Issue by praynise** [apache/dolphinscheduler#6070]
can i complement data by calling api?i found start-process-instance api but i can not complement data with this api,i set parameter scheduleTime with 2021-08-01 00:00:00,2021-08-31 00:00:00,but still the job just run once.
请问我可以通过调用http请求利用API来追数吗？我试了一下用start-process-instance来追数，将scheduleTime参数设置为2021-08-01 00:00:00,2021-08-31 00:00:00，但是却还是仅调起了最新一天，请指导，非常感谢~
**Which version of DolphinScheduler:**
 -[1.3.6]

**Comment by Squidyu** [comment]
Are you parallel complement or serial？
Parallel complement generates multiple process instances and then runs down;
The serial complement produces only one process instance, but multiple task instances running down
并行补数会产生多个流程实例 然后向下运行；
串行补数只产生一个流程实例，但是产生多个任务实例向下运行

**Comment by praynise** [comment]
@Squidyu serial,i must run my job day by day.and before next day,and i use system.biz.date as my batch date
我一般使用串行补数，并使用system.biz.date作为我的跑批输入参数

**Comment by Squidyu** [comment]
The serial replenishment will only generate one process instance, but the task instances inside will run according to the replenishment date. For example, the same task, 2021-08-01 00:00:00,2021-08-31 00:00:00 should run 30 times and generate 30 task instances with the same name

串行补数只会产生一个流程实例，但是里面的任务实例会根据补数日期进行补数运行，比如说同一个任务，2021-08-01 00:00:00,2021-08-31 00:00:00应该是会运行30次，产生30个同名任务实例

**Comment by Squidyu** [comment]
#6007 Maybe it will help you

**Comment by praynise** [comment]
@Squidyu Hi，i have upgrade dolphinscheduler to 1.3.8，but i can still not complement data by calling http request. here is my code
```
package dolphinAPI

import org.apache.http.client.methods.HttpPost
import org.apache.http.client.utils.URIBuilder
import org.apache.http.impl.client.HttpClients

fun main() {
    val IP="110.128.1.133"
    val Port="12345"
    val apiBody="/dolphinscheduler/projects/CWJS/executors/start-process-instance"
    val urlBuilder = URIBuilder("http://${IP}:${Port}/${apiBody}")
    urlBuilder.addParameter("failureStrategy","CONTINUE")
    urlBuilder.addParameter("processDefinitionId","3")
    urlBuilder.addParameter("processInstancePriority","MEDIUM")
    urlBuilder.addParameter("projectName","CWJS")
    urlBuilder.addParameter("scheduleTime","2021-08-01 00:00:00,2021-08-31 00:00:00")
    urlBuilder.addParameter("warningGroupId","1")
    urlBuilder.addParameter("warningType","NONE")
    val post = HttpPost(urlBuilder.build())
    post.addHeader("token","c05003d12097700fa4dd0302164da8bb")
    val httpClient = HttpClients.createDefault()
    val response = httpClient.execute(post)
    val returnCode = response.statusLine.statusCode
    println(response.entity.content.bufferedReader().readText())
    println(returnCode)
    response.close()
    httpClient.close()
}
```
i want to complement data from 20210801 to 20210831,but when i run my code,i just start up one process,and the run type is 'Start Process',not 'complement data'
do i call the wrong api or something wrong with my parameters?thanks a lot
您好，我已经升级了1.3.8，但是我还是不能通过调用api的方式来补数。请见我的代码
我想从20210801开始补数，到20210831结束，但是当我运行代码时，我还是只能调起一个作业，而且作业的运行类型是'启动工作流',而不是'补数',请问是否是我调用了错误的API，或者是我的参数有问题吗？请指点，非常感谢

**Comment by Squidyu** [comment]
The way you start is to run, not complement. Note that you are missing the commandtype parameter, and the parameter value should be 'COMPLEMENT_DATA'
你启动的方式是运行不是补数哦 注意你少了CommandType参数，参数值应该为COMPLEMENT_DATA

**Comment by praynise** [comment]
@Squidyu woo,thank you very very much,it worked!
哇偶，一句话点醒梦中人，实在是太感谢了~
