### ISSUE TITLE
[Feature] Add support of greenplum

### ISSUE THREAD

**Issue by cxin-william** [apache/dolphinscheduler#6076]
Since writing greenplum using datax is very slow with a PostgresQL writer, you can write GP using GreenplumWriter, which is about five times faster

**Comment by zhuangchong** [comment]
@cxin-william 
Good idea, can you submit a PR to contribute to this feature?

**Comment by cxin-william** [comment]
I think just add greenplum to the data source,right?

**Comment by zhuangchong** [comment]
> I think just add greenplum to the data source,right?

1. Need to add Greenplum Writer and Reader to the datax task class
2. Data source supports Greenplum

**Comment by cxin-william** [comment]
Our datax is installed under /opt/datax, which already has greenplum Writer and greenplum Reader

**Comment by zhongjiajie** [comment]
Remove stale

**Comment by zhongjiajie** [comment]
Hi, @cxin-william  are you interested in this issue? If so I could assigned to you

**Comment by gaogen123** [comment]
You can refer to this link 
https://github.com/HashDataInc/DataX/blob/master/gpdbwriter/src/main/java/cn/hashdata/datax/plugin/writer/gpdbwriter/CopyProcessor.java  。

**Comment by zhongjiajie** [comment]
> You can refer to this link https://github.com/HashDataInc/DataX/blob/master/gpdbwriter/src/main/java/cn/hashdata/datax/plugin/writer/gpdbwriter/CopyProcessor.java 。

I seem this link is for datax but not for any fork of DolphinScheduler, if here we only need to add datax writer, you possibility just need to submit PR to datax, not DolphinScheduler @gaogen123

**Comment by zhongjiajie** [comment]
Close this issue due to https://github.com/apache/dolphinscheduler/issues/6076#issuecomment-1005317427. Private advice, since datax seem not to upgrade for a long time, you could possibility use https://github.com/apache/incubator-seatunnel instead

**Comment by gaogen123** [comment]
ok, could you will add support for greenplum? This very import for most of greenplum users. Although Postgresql  also can connect. However, we ran into a lot of problems when running Greenplum  procedures and dataX tasks concurrently with the postgresql driver in DS.

**Comment by gaogen123** [comment]
ok, could you will add support for greenplum? This very import for most of greenplum users.

**Comment by zhongjiajie** [comment]
> 

Hi @gaogen123 , we should not and can not add grenplum support is DS, it is not dolphinscheduler scope, it belong to datax, we can not change datax source code, I think it better create an issue for datax, but not for dolphinscheduler

**Comment by gaogen123** [comment]
I mean  add greenplum datasource  ,not datax

**Comment by zhongjiajie** [comment]
> I mean add greenplum datasource ,not datax

@gaogen123 Then you could create new issue to about support greenplum datasource, cause this issue is about

> Since writing greenplum using datax is very slow with a PostgresQL writer, you can write GP using GreenplumWriter, which is about five times faster
