### ISSUE TITLE
When will variable context transfer be supported? That is, the output of the previous object is used as the input of the next object

### ISSUE THREAD

**Issue by luojieio** [apache/dolphinscheduler#6078]
什么时候支持变量上下文传递呢？即前一个对象的输出作为后一个对象的输入

**Comment by CalvinKirs** [comment]
please use english.thx

**Comment by CalvinKirs** [comment]
you can refer this https://dolphinscheduler.apache.org/en-us/docs/dev/user_doc/globalParams.html

**Comment by luojieio** [comment]
I read the document you provided, but the document says that only sql and shell are currently supported. When can python be supported? thx

**Comment by luojieio** [comment]
Can you provide APIs for creating variables (global varialbes) in the future? This feature is very much needed, currently only supports query

**Comment by luojieio** [comment]
![image](https://user-images.githubusercontent.com/25678606/133886234-ea257811-6da0-4b41-871c-733715cdc4fd.png)

why my version no this 
my version is 1.3.8 
deploy k8s

**Comment by luojieio** [comment]
maybe 1.4 can use
