### ISSUE TITLE
Is there an interface for setting global variables?

### ISSUE THREAD

**Issue by luojieio** [apache/dolphinscheduler#6079]

**Comment by CalvinKirs** [comment]
please refer this https://dolphinscheduler.apache.org/en-us/docs/dev/user_doc/globalParams.html

**Comment by luojieio** [comment]
What I need is the api call interface, not the user interface manual setting，thanks

**Comment by luojieio** [comment]
![image](https://user-images.githubusercontent.com/25678606/133917072-9a3a49b0-a2ba-46f5-a245-f705e251a3fd.png)
 
why my latest release version 1.3.8 no this ? please help me !!! urgent
