### ISSUE TITLE
can i change the line in DAG into straight line？

### ISSUE THREAD

**Issue by praynise** [apache/dolphinscheduler#6081]
can i change the line in DAG into  straight line？in our project,curve looks messy,Thank you very much for the advice
请问如何可以将DAG图中的连线变成直线呢？在我们的项目中，曲线连线会显得很乱，直线效果会好很多，非常感谢指点

**Which version of DolphinScheduler:**
 -[1.3.6]

**Comment by Narcasserun** [comment]
The implementation of straight lines is relatively simple, but it is still acceptable when there are few nodes. If there are too many nodes and the lines are complex, there is basically no way to see it, and the effect is not very good
