### ISSUE TITLE
[Question] send alert email failed ,how to check

### ISSUE THREAD

**Issue by yangshiza** [apache/dolphinscheduler#6083]
**Describe the question**
I have configured   the alert.properties .but when  the  task run failed  I didn't   receive  any emails. How can  I  fix this problem?
![alert_log](https://user-images.githubusercontent.com/85532472/131656655-6d378ae7-7d50-481d-a921-40a858206966.png)
![alert_properties](https://user-images.githubusercontent.com/85532472/131656337-118ebe32-145f-4ea0-98b3-b1f8355569c2.png)

**Which version of DolphinScheduler:**
 -[1.3.6-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by ruanwenjun** [comment]
You can try to use `MailUtilsTest` to test.

**Comment by yangshiza** [comment]
![1630561234(1)](https://user-images.githubusercontent.com/85532472/131788199-2a0ede57-1d54-4f01-a603-e24f3e083b89.png)

**Comment by yangshiza** [comment]
maybe  sth wrong  with the port 25

![1630567792(1)](https://user-images.githubusercontent.com/85532472/131801750-68fa246b-63a8-4e5a-a100-fafd694b070e.png)

**Comment by yangshiza** [comment]
This problem  caused by   the network limitation . I change the e-mail address  which can telnet  success   .and  then the problem is solved.
