### ISSUE TITLE
Is it possible to directly display the time point of the specific execution in the workflow interface?（工作流界面中是否可以直接显示 当天具体执行的时间点 更直观）

### ISSUE THREAD

**Issue by allantaylor81** [apache/dolphinscheduler#609]
Whether the workflow interface can directly display the time point of the specific execution of the day is more intuitive. Otherwise, after entering the time management, the crontab expression is not intuitive.

---
工作流界面中是否可以直接显示 当天具体执行的时间点 更直观 。否则需进入定时管理后，显示crontab 表达式不直观

**Comment by qiaozhanwei** [comment]
Because timing can be arbitrary, every minute, every hour, do you mean to express the specific time of the next trigger if there is timing?


因为定时可能是任意情况，每分钟，每小时，你的意思是不是想表达如果存在定时，下一次触发的具体时间
