### ISSUE TITLE
Hive on Spark problem

### ISSUE THREAD

**Issue by wangfeigithub** [apache/dolphinscheduler#6092]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:

**Expected behavior**

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by wangfeigithub** [comment]
When I run a hive on Spark scheduling task, yarn tasks will not stop after the execution is complete. When I perform this scheduling task, an error occurs.

**Comment by wangfeigithub** [comment]
Do not close the connection after executing SQL？

**Comment by wangfeigithub** [comment]
![image](https://user-images.githubusercontent.com/29723968/131830426-2a72d604-413c-409d-95f7-86b66c7194cc.png)
Each time hive SQL is scheduled, a job is left in the background and does not disappear.
Only the first dispatch will be executed, and the second dispatch will fail！！！

**Comment by ruanwenjun** [comment]
closed by #14631
