### ISSUE TITLE
[Question] skywalking does not apply with ambairy install

### ISSUE THREAD

**Issue by echomyecho** [apache/dolphinscheduler#6099]
i installed ds (1.3.6) with ambari ,and find that  skywalking does not apply with ambairy install.

i made some change as flows

1、 dolphin-daemon.sh.j2
![1](https://user-images.githubusercontent.com/10241833/131958469-dff6be54-23ce-4b46-b40a-a966b423f113.png)

i also add this on dolphin-daemon.sh.j2
 export SKYWALKING_ENABLE=true
export SW_AGENT_COLLECTOR_BACKEND_SERVICES=XXXX:11800
export SW_GRPC_LOG_SERVER_HOST=XXXX
export SW_GRPC_LOG_SERVER_PORT=11800

2 、i flowed this guide to install ds with amabri https://github.com/apache/dolphinscheduler/tree/1.3.3-release/ambari_plugin 
![image](https://user-images.githubusercontent.com/10241833/131959616-10d27975-c2b3-4fc8-816c-e39dfee2a4ff.png)

i find that apache-dolphinscheduler-incubating-xxx.noarch.rpm does not contains /ext/skywalking-agent and ,i copyed  
/ext/skywalking-agent from Binary Distribution  of ds (1.3.6)

after i do this ,if found that ,skywalking works same part 
![apm](https://user-images.githubusercontent.com/10241833/131959268-24cb6a43-0004-4fee-b1f6-b8e284ab471a.png)
![ds](https://user-images.githubusercontent.com/10241833/131959282-e3d3d2a8-f00e-41f4-8548-2c043fe1fcfb.png)
![ds1](https://user-images.githubusercontent.com/10241833/131959292-47e2a6d2-9037-4890-99bd-5cfc3d487397.png)
![2](https://user-images.githubusercontent.com/10241833/131959309-62c737bb-75ff-454b-a19b-8c5978dd65cf.png)

as we can see,except the log ,other part of sky works well, i just dont kow how to make logs well

**Which version of DolphinScheduler:**
 -[1.3.6-preview]

@Kingsley

**Comment by CalvinKirs** [comment]
This is an optional plugin, we should discuss whether we need Ambairy install support
