### ISSUE TITLE
[Improvement][community] Add bot to congrats user first contribution

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#6114]
**Describe the question**

I think we should add some bot to encourage and congrats user first contribution.
"Community Over Code", one of Apache way, besides some IM software(slack, wechat) we should also add a bot for congrating user first contribution, encourage user further contribution.

For example, we have PR https://github.com/apache/dolphinscheduler/pull/6109

**Comment by ruanwenjun** [comment]
Right now, after a new user's first contribution has been merged, the community will contact him and congrats he. I think DolphinScheduler community is doing well to encourage new user in the past.

Adding bot can reduce the community work, but I actually don't want to see bot messages, if I am a new user.

**Comment by CalvinKirs** [comment]
Agree with wenjun, we prefer the PR merger to do this, the community needs to maintain these contributors to achieve the purpose of motivating them to actively contribute, for me, the bot's words do not seem to have any emotional color, I will not be patient to read through what it says.

**Comment by Narcasserun** [comment]
+1

**Comment by cxin-william** [comment]
+1

**Comment by zhongjiajie** [comment]
I got the point and I don't have strong opinion here. But if manually do that rather than by bot, should we add some doc in such as [committer](https://dolphinscheduler.apache.org/en-us/community/development/become-a-committer.html) to describe committer "duties" here?

**Comment by CalvinKirs** [comment]
> I got the point and I don't have strong opinion here. But if manually do that rather than by bot, should we add some doc in such as [committer](https://dolphinscheduler.apache.org/en-us/community/development/become-a-committer.html) to describe committer "duties" here?

That's a good suggestion.

**Comment by zhongjiajie** [comment]
I would create PR and add some docs to describe it this week.
