### ISSUE TITLE
[Question] Install ds based on k8s, how to set ssh to avoid password

### ISSUE THREAD

**Issue by listenLearning** [apache/dolphinscheduler#6120]
Q1: 我是基于k8s安装的ds，现在有个问题，就是我的cdh是安装在其他服务器上的，那么我如何到其他的机器上去调度我的hive脚本呢？我是基于公共的shell模板脚本进行hive sql调度的，所以我实际上需要的是到其他机器上去调度我这个公共的脚本，所以我想知道该如何在k8s内部去做免密，并且如何在k8s重启后，依然生效

Q2：我创建了一个租户，但是执行ssh的时候，出现了如下问题，请问这个又该怎么解决呢？
![image](https://user-images.githubusercontent.com/25893114/132339988-9a14cde1-a545-42bc-aea2-30d1ee720514.png)

**Comment by chengshiwen** [comment]
@listenLearning You should use [ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/) or [Secret](https://kubernetes.io/docs/concepts/configuration/secret/) (recommended) to solve the problem. Specifically,

1. Create a public and private key pair
2. Create a secret containing the pair in k8s (refer to https://kubernetes.io/docs/concepts/configuration/secret/#use-case-pod-with-ssh-keys)
3. Mount the secret onto `/home/someTenant/.ssh` by volume (refer to https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod)

**Comment by listenLearning** [comment]
> @listenLearning您应该使用[ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/)或[Secret](https://kubernetes.io/docs/concepts/configuration/secret/)（推荐）来解决问题。具体来说，
> 
> 1. 创建公钥和私钥对
> 2. 在 k8s 中创建一个包含该对的 secret（参考https://kubernetes.io/docs/concepts/configuration/secret/#use-case-pod-with-ssh-keys）
> 3. `/home/someTenant/.ssh`按卷挂载机密（请参阅https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod）

好的，我先去尝试一下，🙏

**Comment by listenLearning** [comment]
> @listenLearning You should use [ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/) or [Secret](https://kubernetes.io/docs/concepts/configuration/secret/) (recommended) to solve the problem. Specifically,
> 
> 1. Create a public and private key pair
> 2. Create a secret containing the pair in k8s (refer to https://kubernetes.io/docs/concepts/configuration/secret/#use-case-pod-with-ssh-keys)
> 3. Mount the secret onto `/home/someTenant/.ssh` by volume (refer to https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod)

不好意思，在执行的过程中遇到过一个问题，就是我现在是3个node，其中worker分布在node-01和node-02这两台机器上，那么如果我要通过secret来进行免密的，就有一个问题了，就是根据提示，在创建secret的时候需要指定私钥和公钥，公钥的话放在一起就好了，但是私钥呢？两个节点的私钥也放在一起吗？
![ebdfbd1546ba62eec8bfd5eecf7f90f](https://user-images.githubusercontent.com/25893114/132448799-9ed1fb33-a729-4ecd-bfa7-a895158cb011.png)

**Comment by listenLearning** [comment]
我重新用原生的方式安装了
