### ISSUE TITLE
[Discuss][JsonSplit] Remove code field

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#6125]
**Describe the question**
During the past moths, the community spent a lot of time to complete the JSON split.
I am not involved in this job, but I can see this task is very difficult.

Now the feature seems to be finished, and I have read some code and have a question about the `code` field in the database.

We add a code field in many tables, and this field seems just used to maintain the relationship between the data models.
For example, in `t_ds_task_definition` table we have a code, and in `t_ds_process_definition` we have a code, then we can maintain the relation of task and process_definition in `t_ds_process_task_relation` by these two codes.

The design is OK, and I guess the reason for using `code` instead of `id` is that we cannot get the `id` in program, since we use AUTO_INCREMENT to generate the `id`, so we cannot get the`id` if the data has not been inserted.

If my suspicions are correct, I think we can generate the `id` in program instead of using AUTO_INCREMENT, then we can get the `id` before insert data. We can implement this like segment mode(https://github.com/Meituan-Dianping/Leaf)
Then we don't need the `code` field.

The advantage of remove `code` field is that this make DolphinScheduler easier to migrate with other systems, since other systems may don't have `code`. On the other hand, we needn't add a new index of `code` and the data model will be clearer.

**Which version of DolphinScheduler:**
 -[dev]

**Comment by brave-lee** [comment]
I don't think we need to discuss too much. Code was decided after a long discussion. It can solve many problems, such as import and export, optimizing task memory queue, and moving between projects to ensure uniqueness

**Comment by ruanwenjun** [comment]
> I don't think we need to discuss too much. Code was decided after a long discussion. It can solve many problems, such as import and export, optimizing task memory queue, and moving between projects to ensure uniqueness

Maybe you are right, I just think the `id` can do the same thing.

**Comment by ruanwenjun** [comment]
Cloed, if someone wants to discuss, we can reopen.
