### ISSUE TITLE
[Question][dev] Local dev environment error: plugin dir not exists ! lib/plugin/registry

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#6129]
**Describe the question**

I want to setup dev env in my laptop but failed with some error.
I following the [Development Environment Setup][1], everything find until sections **Start the project**, When I run `MasterServer` in idea, it got error as below

```log
...
Caused by: java.lang.IllegalArgumentException: plugin dir not exists ! lib/plugin/registry
	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginManagerConfig.setInstalledPluginsDir(DolphinPluginManagerConfig.java:63)
	at org.apache.dolphinscheduler.service.registry.RegistryCenter.installRegistryPlugin(RegistryCenter.java:121)
	at org.apache.dolphinscheduler.service.registry.RegistryCenter.init(RegistryCenter.java:95)
	at org.apache.dolphinscheduler.service.registry.RegistryClient.<init>(RegistryClient.java:58)
	at org.apache.dolphinscheduler.service.registry.RegistryClient.<clinit>(RegistryClient.java:55)
	... 37 more
```

After that I try running `StandaloneServer` in idea, both backend and frontend work find, which mean machine and dependent are satisfy.

**Which version of DolphinScheduler:**
 -[dev]

**Additional context**

OS: macOS 10.15.7
maven: 10.15.7
git branch: dev

Before run `MasterServer` in idea, I run `mvn -U clean package -Prelease -Dmaven.test.skip=true` but seem `lib` folder did not created?(not sure about that)
![image](https://user-images.githubusercontent.com/15820530/132446307-ec42ee94-e543-48ac-956e-8a2855ce5301.png)

[1]: https://dolphinscheduler.apache.org/en-us/development/development-environment-setup.html

**Comment by ruanwenjun** [comment]
@zhongjiajie FYI https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/registry_spi.html
Maybe we need to update the doc.

**Comment by zhongjiajie** [comment]
@ruanwenjun Did you mean I should follow [registry-spi][1] to fix this error?

[1]: https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/registry_spi.html

**Comment by ruanwenjun** [comment]
@zhongjiajie Yes, one easy way is to modify the registry.properties like below
```
#registry.plugin.dir config the Registry Plugin dir.
#registry.plugin.dir=lib/plugin/registry

registry.plugin.name=zookeeper
registry.servers=127.0.0.1:2181

#maven.local.repository=/usr/local/localRepository

#registry.plugin.binding config the Registry Plugin need be load when development and run in IDE
registry.plugin.binding=./dolphinscheduler-registry-plugin/dolphinscheduler-registry-zookeeper/pom.xml
```
Another way is following the [registry-spi](https://dolphinscheduler.apache.org/en-us/docs/dev/user_doc/registry_spi.html) to install the registry plugin to registry.plugin.dir

**Comment by davidzollo** [comment]
> @zhongjiajie FYI https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/registry_spi.html
> Maybe we need to update the doc.

Yes, the documentation needs to be updated, and more than one contributor encountered problems here, including me

**Comment by zhongjiajie** [comment]
I create a new issue for updating our development doc
