### ISSUE TITLE
[Question] No appropriate protocol (protocol is disabled or cipher suites are inappropriate)

### ISSUE THREAD

**Issue by listenLearning** [apache/dolphinscheduler#6131]
![image](https://user-images.githubusercontent.com/25893114/132471973-5b54dcba-8b42-45e9-bd65-32b91f3d3ba0.png)
![image](https://user-images.githubusercontent.com/25893114/132472068-0a06b77a-8cbb-471c-96ac-10db1d552620.png)

**Comment by listenLearning** [comment]
目前安装完成之后，无法登录dolphinscheduler，
![image](https://user-images.githubusercontent.com/25893114/132473269-b29d4d62-8147-4c5c-85c9-9cea5e1abe7a.png)
去查看api和alert日志，都发现了这个错误

**Comment by limoru** [comment]
请问解决了吗？ 是什么原因呢？
