### ISSUE TITLE
[Bug][Master] worker cannot be found if worker start earlier than master.

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#6137]
branch : dev
phenomenon：
1 start worker
2 start master
3 start a process instance
4 master cannot find the worker

![image](https://user-images.githubusercontent.com/29528966/132493045-689ed026-b1ae-474e-9479-b71ce4220671.png)

then i restart the master, this problem disappeared！

**Comment by ruanwenjun** [comment]
I have met this before, but now I cannot reproduce this issue.

**Comment by CalvinKirs** [comment]
I’m not sure, we need to determine the current process,

The first step: Master starts to pull worker information from the registration center in full
Step 2: Master subscribes to worker node monitoring information.
I'm not sure， if it was completed in the first step, but the second step has not yet started. During this process, the worker went online，There will be a problem at this time.

**Comment by Narcasserun** [comment]
+1

**Comment by Narcasserun** [comment]
My phenomenon is that I started it for the first time, and then stop-all.sh and start-all.sh. The problem remains
-dev
