### ISSUE TITLE
[Question] 关于dependent

### ISSUE THREAD

**Issue by listenLearning** [apache/dolphinscheduler#6145]
我有一个使用上的问题，就是，我之前使用的是airflow，然后我的项目是每2小时运行一次，假设现在有两个项目a和b，b项目需要依赖a项目中的某个任务完成之后才会继续执行，比如这是我的主题A，其中export_middle_task是我主题b的依赖
![image](https://user-images.githubusercontent.com/25893114/132611979-47b9fdc3-3fd4-4a0b-b966-ca37cbfc3376.png)
这个是主题b，他会依赖主题a，都是在同一个小时内的任务
![image](https://user-images.githubusercontent.com/25893114/132612057-7e8ddb5e-0aa4-4843-9ade-a1b6d5d4cd1b.png)
我尝试这用ds去实现类似的功能，
![image](https://user-images.githubusercontent.com/25893114/132612154-72a5c7aa-dcce-418b-9bc3-835e5aeac7d3.png)
但是，从昨晚，到今天，我的任务一直在执行中，并没有执行成功
![image](https://user-images.githubusercontent.com/25893114/132612224-b683b1e0-c4f9-46ee-a467-972c7082dc8c.png)
所以我想问一下，我该怎么去实现这个功能？或者ds是否能实现这样的功能？

**Comment by yang227** [comment]
![image](https://user-images.githubusercontent.com/65292562/132618359-913edd04-49d1-4c69-81ed-769e073c7d55.png)
你设置配置失败的原因是由于可能出现没有检测成功，没有进行重试，你可以参考一下设置

**Comment by listenLearning** [comment]
这个地方有一个从失败节点开始，那如果是我的dag里的配置错误了，我重新修改了我的配置，按理说这个应该是根据我修改后的任务配置去运行，但是刚才试了下，这个是按修改前的配置去运行任务的，这个是否合理？
![image](https://user-images.githubusercontent.com/25893114/132649919-ee1a39cb-5867-4d81-9faa-fa242afec455.png)

**Comment by yang227** [comment]
如果你的任务失败，你应该在工作流实例中，直接去更改，保存时选择 ' 是否更新工作流程定义'，这样恢复运行就会变成最新的。

**Comment by CalvinKirs** [comment]
hi, for better communication, please use English. thx
