### ISSUE TITLE
[Bug] Save workflow error

### ISSUE THREAD

**Issue by wangyizhi1** [apache/dolphinscheduler#6146]
I created a workflow as follows: 
![image](https://user-images.githubusercontent.com/87303815/132616260-4e0be953-ecfe-497a-86ed-a5c0fe8ba404.png)

I got an error when i clicked the save btn:
![image](https://user-images.githubusercontent.com/87303815/132616620-89a34a31-f6e4-4bab-9c5f-168c10b92907.png)

**Which version of Dolphin Scheduler:**
version: 2.0.0 
branch: dev

**Additional context**
The request params: 
[request.txt](https://github.com/apache/dolphinscheduler/files/7133138/request.txt)

**Comment by Narcasserun** [comment]
You can use the latest stable version 1.3.8 first. The dev branch has not been officially released

**Comment by brave-lee** [comment]
I will fix it
