### ISSUE TITLE
[Improvement][Dependent Node UI] dependent node loaded multiple times

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#6151]
![1631178237(1)](https://user-images.githubusercontent.com/17822915/132656752-366d2909-75ce-49c8-8782-448396b3c616.jpg)
When a dependent node has multiple dependencies, it will be loaded multiple times.When the public network speed is limited, the loading speed is very slow.

It is recommended to load only once when there are multiple dependencies,and also t_ds_process_definition.process_definition_json is too big to load.

**Which version of DolphinScheduler:**
 -[1.3.8]

**Comment by CalvinKirs** [comment]
hi, great suggestion, can you submit PR for this?

**Comment by SbloodyS** [comment]
sorry, front end is not my field.

**Comment by CalvinKirs** [comment]
> sorry, front end is not my field.



> sorry, front end is not my field.

If you are interested in other modules, you are also welcome to contribute.：）

**Comment by SbloodyS** [comment]
> > sorry, front end is not my field.
> If you are interested in other modules, you are also welcome to contribute.：）

OK, I'll see what I can do. ：）

**Comment by lenboo** [comment]
open it for the questioner 
@SbloodyS

**Comment by zhongjiajie** [comment]
Fix in #7725
