### ISSUE TITLE
[Bug] [task-plugin] Python Task execute error

### ISSUE THREAD

**Issue by mgsky1** [apache/dolphinscheduler#6166]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In the newest dev version, python task is not migrated complete. When I execute python task in workflow, ds throws NullPointerException.

### What you expected to happen

Python task execute correctly.

### How to reproduce

- Add a python task into work flow.
- Type simple script, just like`print('Hello')`
- Then execute the work flow

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by geosmart** [comment]
make sure PYTHON_HOME is config corrently,
you can just ssh to the worker and run python to test your script

**Comment by mgsky1** [comment]
> make sure PYTHON_HOME is config corrently,
> you can just ssh to the worker and run python to test your script

In `org.apache.dolphinscheduler.plugin.task.python.PythonTask `, there is no `buildCommand` method, but old version, like 1.3.x has it. This will make command null and then throw NullPointerException.
