### ISSUE TITLE
[Improve] [scheduler] configure skip a period  scheduler task when the last time task is running

### ISSUE THREAD

**Issue by beeflyme** [apache/dolphinscheduler#6178]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1. such as I have a task with period with one hour;
2. in some case the task can't finish in one hour;
    the the task will runing twice at the same time. 
3. in azkaban ,user can set whether  skip a task (can choose skip/ run ).
    
![image](https://user-images.githubusercontent.com/5909981/132941210-98b5aac8-8d77-407c-971c-a00e61fd034d.png)

### Use case

1.  period  scheduler  task  can configure to skip/ continue  when scheduler  period   comming when not finish.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by beeflyme** [comment]
maybe we can add a configure at the position near "failure strategy"
![image](https://user-images.githubusercontent.com/5909981/132941577-45fc9852-5ff2-4ad9-9543-25796b33d4d7.png)

**Comment by zhongjiajie** [comment]
remove stale

**Comment by zhongjiajie** [comment]
I remove stale label, cause I think this is a good feature for DolphinScheduler

**Comment by zhijunn** [comment]
How is this problem going? Why is there no follow-up?
I think this is a good feature for DolphinScheduler as well! Especially for users who were formerly Azkaban!

这个问题的进展如何了？为什么没有后续了？
我认为这是个非常有用的特性，特别是对于之前是Azkaban的用户

**Comment by zhijunn** [comment]
> How is this problem going? Why is there no follow-up? I think this is a good feature for DolphinScheduler as well! Especially for users who were formerly Azkaban!
> 
> 这个问题的进展如何了？为什么没有后续了？ 我认为这是个非常有用的特性，特别是对于之前是Azkaban的用户

@zhongjiajie
