### ISSUE TITLE
[Bug] [ui] cannot edit process definition name

### ISSUE THREAD

**Issue by eye-gu** [apache/dolphinscheduler#6193]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

on dev, It cannot be modified process definition name on the page

在dev分支上,页面不能修改工作流定义的名字

### What you expected to happen

above

### How to reproduce

open process definition editing page

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tandoy** [comment]
I will fix it

**Comment by Tandoy** [comment]
@ououtt I can't reproduce this problem in the online environment of dev branch (upcoming 2.0). Can you tell me your operation process?
![企业微信截图_16317591213564](https://user-images.githubusercontent.com/56899730/133539561-94247d47-84f8-43c4-a489-dd5566f88aaa.png)

![企业微信截图_16317592139429](https://user-images.githubusercontent.com/56899730/133539569-db797f9a-f3a4-4d96-bcd9-642133fc8c8e.png)

**Comment by eye-gu** [comment]
![image](https://user-images.githubusercontent.com/20450037/133619714-a2cf36b9-a61e-4764-a029-31dbac7ed47d.png)

i cannot edit this name

**Comment by Tandoy** [comment]
@ououtt 
![Snipaste_2021-09-16_22-35-09](https://user-images.githubusercontent.com/56899730/133631770-e1457caa-c9ba-4d56-b6bd-41c2a106cb9a.PNG)

Maybe this is not a bug, you can try to click the save button in the picture to modify the workflow name. In the future follow-up optimization can make the interaction more elegant.

**Comment by eye-gu** [comment]
sry.This is my fault.
