### ISSUE TITLE
Resource Center - File Management fields that want to increase the file path are displayed（资源中心-文件管理希望能增加文件路径的字段显示出来）

### ISSUE THREAD

**Issue by chongchongzi** [apache/dolphinscheduler#620]
Resource Center - File Management fields that want to increase the file path are displayed

---
资源中心-文件管理希望能增加文件路径的字段显示出来

**Comment by boandai** [comment]
good idea，thx!

and could you submit a pull request to complete this feature?

**Comment by echohlne** [comment]
I have implemented this feature.
I will submit a pr  ASAP. Please assign the task to me, Thanks a lot.
