### ISSUE TITLE
[Bug] [Master/Worker] The ZooKeeper can be directly connected without authentication.

### ISSUE THREAD

**Issue by keepmeup** [apache/dolphinscheduler#6202]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The ZooKeeper can be directly connected without authentication.

When connecting to the ZooKeeper, the user name and password must be provided for authentication to improve security.

### DolphinScheduler Version

1.3.4

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chengqiZ** [comment]
I have the same question , how does the worker connect to a zookeeper server that requires an account and password ?

**Comment by chengqiZ** [comment]
You can modify the script "dolphinscheduler-daemon. sh" for starting the master and worker processes, add the start parameter "- Djava. security. auth. login. config = / xxx / zk_client_jaas. conf", and add configuration information in the configuration file.

**Comment by keepmeup** [comment]
> I have the same question , how does the worker connect to a zookeeper server that requires an account and password ?
Thanks.
Do you know the code is used about the config file of zk_client_jaas. conf  ? I want to know how it works.

Now, if i dont config the file ,the worker and master just can connect the zk with zk quraom without username and password

**Comment by chengqiZ** [comment]
This is my configuration file. I don't know if this class is what you _need："org.apache.zookeeper.server.auth.DigestLoginModule".
`
Client{
    org.apache.zookeeper.server.auth.DigestLoginModule required
    username="xxx"
    password="xxx"
    user_kafkacluster="xxx"
};
`
