### ISSUE TITLE
[Bug] [task.plugin.dir ] the parameter task.plugin.dir has no default value when worker node is going to be started.

### ISSUE THREAD

**Issue by jon-qj** [apache/dolphinscheduler#6204]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when I  start the worker node,the parameter task.plugin.dir has no default value so that it starts failed.

### What you expected to happen

it is unnecessary.

### How to reproduce

it is unnecessary. we can remove the # symbol which is front of the parameter task.plugin.dir.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by alanredsheep** [comment]
It seems that it still lacks task.plugin.dir on Docker Images.
Here is the ds-worker.log when I use docker-compose to start ds.
```
[ERROR] 2021-11-17 09:48:51.989 org.springframework.boot.SpringApplication:[823] - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'workerServer': Invocation of init method failed; nested exception is org.apache.dolphinscheduler.spi.exception.PluginNotFoundException: Task Plugin Not Found,Please Check Config File
```
Should we add `task.plugin.dir=${TASK_PLUGIN_DIR}` to  worker.properties.tpl and add `export TASK_PLUGIN_DIR=${TASK_PLUGIN_DIR:-"lib/plugin/task"}` to  startup-init-conf.sh ?
