### ISSUE TITLE
[Bug] [API] Zookeeper info cannot generated in monitor center

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#6216]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

branch : dev
Zookeeper info cannot generated in monitor center

![image](https://user-images.githubusercontent.com/29528966/133372285-2305ec67-12ec-4877-8e4a-1f0ace66fd13.png)

### What you expected to happen

the zookeeper info can be display normally

### How to reproduce

Monitor center --> zookeeper

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jon-qj** [comment]
This function has not been implemented yet.
![image](https://user-images.githubusercontent.com/39773194/133379927-cee5baac-aec1-4fb5-bdb2-30f4a12eee51.png)
Becides,the return value is not verified.
![image](https://user-images.githubusercontent.com/39773194/133381293-60012975-f1eb-4487-ae83-cae0376b05c0.png)
