### ISSUE TITLE
[Bug] [User]  modify user's information and DS's page shows wrong information at the frond-end

### ISSUE THREAD

**Issue by jon-qj** [apache/dolphinscheduler#6219]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

branch:dev
when I modify some users' information and ds's page shows wrong information at the frond-end which is strange .

### What you expected to happen

the user admin who logs on don't change to other users when he modify some users' information

### How to reproduce

1、create two new users
![image](https://user-images.githubusercontent.com/39773194/133393258-c1549b4d-7161-4694-8e03-9e307b6a07f5.png)
2、modify the information of one of them
![image](https://user-images.githubusercontent.com/39773194/133393204-3644ddbd-9f17-4ca3-b7da-72299b701b8e.png)
3、click the Edit button and the problem goes on.
![image](https://user-images.githubusercontent.com/39773194/133393375-bd2a3308-5d58-4152-9189-3c2ff6d20c63.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tandoy** [comment]
From the recurring pictures you provided, it looks like it’s normal, but it’s sorted in descending order according to the update time.

**Comment by jon-qj** [comment]
> From the recurring pictures you provided, it looks like it’s normal, but it’s sorted in descending order according to the update time.

Why is it normal? As admin, I can modify other user's info. However it is strange to set some user's info to current user's info. 
Besides, it will make me confused. I log on as admin, but the current page shows other user's info when I modify other user's info.

**Comment by Tandoy** [comment]
> > From the recurring pictures you provided, it looks like it’s normal, but it’s sorted in descending order according to the update time.
> 
> Why is it normal? As admin, I can modify other user's info. However it is strange to set some user's info to current user's info.
> Besides, it will make me confused. I log on as admin, but the current page shows other user's info when I modify other user's info.

Got it, this is indeed a bug. After modifying the user information, refresh the page to display normally.
