### ISSUE TITLE
[Bug] [ui] subProcess page is empty

### ISSUE THREAD

**Issue by vickyi** [apache/dolphinscheduler#6221]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Since version 1.3.7，we foud subProcess page is empty, and afrer we upgrade to 1.3.8, this problem still exists。
![image](https://user-images.githubusercontent.com/1571275/133398218-7b699fc3-1f5e-417e-a5c7-fe2071b430ed.png)

At subProcess page , the url missing project id 「2」:
![image](https://user-images.githubusercontent.com/1571275/133398955-f1b949bb-767c-410a-bfa6-52c8140378b4.png)

### What you expected to happen

subprocesses are exist, subprocess page shouldn't be empty page。 This problem is caused by url error.

### How to reproduce

1. create two workflow, eg. workflow1 and workflow2
2. make workflow2 as workflow1's  subprocess

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
This issue is the same as the description of issue https://github.com/apache/dolphinscheduler/issues/6429. Close this issue first. If you have any issues, you can open it again.
