### ISSUE TITLE
[Bug] [ui] resources create request method is not found 

### ISSUE THREAD

**Issue by lichengkun** [apache/dolphinscheduler#6223]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when I want to upload file in resource menu :
![微信图片_20210915170330](https://user-images.githubusercontent.com/16420393/133404754-9d597b9f-0f0b-441a-b089-c13ca81c4dd1.png)
the create request response 405 error

### What you expected to happen

response 200

### How to reproduce

dev branch :
资源中心/文件管理/上传文件

### Anything else

i find the source of the bug,because ResourcesController  in api module do not have create mapping
but i compare whth git histroy found that old version is right

![微信图片_20210915171202](https://user-images.githubusercontent.com/16420393/133406244-379e54b2-510e-4684-b424-6744a228bb64.png)
I think the purpose of deleting it is to be more consistent with restful style
so  modifying ui is more reasonable

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Narcasserun** [comment]
@ruanwenjun Are some front-end codes not integrated? The same problem as above. The interface of the alarm module is 404
{"timestamp":"2021-09-16T09:43:16.380+0800","status":404,"error":"Not Found","message":"Not Found","path":"/dolphinscheduler/alert-plugin-instance/list"}

**Comment by ruanwenjun** [comment]
@Narcasserun This is a bug !!!!
https://github.com/apache/dolphinscheduler/blob/fa0b86ac824fe88acecb64178de87529ad9f2627/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/AlertPluginInstanceController.java#L61-L64
