### ISSUE TITLE
[Question] Memory keeps growing

### ISSUE THREAD

**Issue by listenLearning** [apache/dolphinscheduler#6235]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

At present, my DS cluster has three nodes, two master nodes and three working nodes. Among them, the master node is 7g memory. However, I found that the memory has been high after starting the relevant processes of DS. What methods can I use to control the memory growth of the DS master node or how to clean up the memory of DS

### DolphinScheduler Version

1.3.8

### Additional context

![image](https://user-images.githubusercontent.com/25893114/133593192-5ed295cd-b133-4545-b73a-87c934d9fe25.png)
<img width="694" alt="0273401b84e6d90a68af6e86af36bd1" src="https://user-images.githubusercontent.com/25893114/133593200-0be08eb9-3886-471b-bd40-ec5cf482a24a.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
I didn’t find any abnormalities. Under normal circumstances, growth is normal.
You can check the master server and worker server runtime log to find more information, especially pay attention to warning/exception/error level messages
