### ISSUE TITLE
[Bug] [ALL] No install.sh for deploy

### ISSUE THREAD

**Issue by RichardStark** [apache/dolphinscheduler#6256]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

There seems no install.sh for deploying in dev branch

### What you expected to happen

Added install.sh

### How to reproduce

No need, we can not find install.sh after mvn install.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Does someone could close this issue? It's fix in https://github.com/apache/dolphinscheduler/pull/6257

**Comment by ruanwenjun** [comment]
> Does someone could close this issue? It's fix in #6257

I will close this issue.
