### ISSUE TITLE
[Question] Question title

### ISSUE THREAD

**Issue by WoodenTiger000** [apache/dolphinscheduler#6270]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

连接hive时报 据源其他参数不合法
![image](https://user-images.githubusercontent.com/5031620/133882640-80e0b5b5-80db-4fd5-91d2-df356b04dc76.png)

### DolphinScheduler Version

最新版

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Narcasserun** [comment]
Kerberos related configurations can be configured in common.properties
