### ISSUE TITLE
[Improvement][Common] Read file with UTF-8

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#6276]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

You can find the code in org.apache.dolphinscheduler.common.utils.FileUtils
https://github.com/apache/dolphinscheduler/blob/69a153c5f5c9d91b4eececbcfbf9e2fb407f89c4/dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java#L234-L254

The `output.toString()` method will use the system' default charset to deserialize the byte to string.
This may cause a problem if we use UTF-8 to write a string to a file and use this method to read the file in some environments. 
related issue #6273, fix FileUtilsTest#testWriteContent2File

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinit** [comment]
Hi, you can assign this issue to me and I will fix it. @dailidong

**Comment by ruanwenjun** [comment]
@calvinit Great, I have assigned to you.
