### ISSUE TITLE
[Bug] [Task] Spark task execute failed due to NPE

### ISSUE THREAD

**Issue by LiuBodong** [apache/dolphinscheduler#6292]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

branch: dev

when execute spark task, a NullPointerException occurs due to `mainJar ` has no `resourceName` field.

it is because the master only saves `resourceId` of `mainJar` in the database, when the worker fetch task data from database, it does not query resource information, so the `mainJar ` field of `SparkParameters` is like this:
```json
{"id": 1}
```
`res` and `resourceName` are lost, and became `null` value in the object. this causes NPE when execute `mainJar.getResourceName()` method

### What you expected to happen

spark task execute successfully

### How to reproduce

create a new spark task, and run it

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
hi,Since we are going to release 2.0 in the near future, this issue is rather important, can you provide PR as soon as possible, if you are busy, it's okay, I can come to do this, see if your time allows.

**Comment by LiuBodong** [comment]
> 
> 
> hi,Since we are going to release 2.0 in the near future, this issue is rather important, can you provide PR as soon as possible, if you are busy, it's okay, I can come to do this, see if your time allows.

I will do it as soon as possible
