### ISSUE TITLE
[Question] Worker memory keeps growing

### ISSUE THREAD

**Issue by sangetang** [apache/dolphinscheduler#6296]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

At present, my DS cluster has four nodes:
2 master, 2 worker.
Worker memory is 32g, running spark stream task  24.
Possible causes, i guess is task log，but can't sure.

### DolphinScheduler Version

1.3.6

### Additional context

![image](https://user-images.githubusercontent.com/75775441/134443770-56676c66-f010-400b-8e46-269bf7984e99.png)
![image](https://user-images.githubusercontent.com/75775441/134443811-0aa4e3e6-6991-4d3d-aa48-28ad8e17f593.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sangetang** [comment]
Second img is top details

**Comment by davidzollo** [comment]
Duplicate of https://github.com/apache/dolphinscheduler/issues/6235 , this issue will be closed
