### ISSUE TITLE
[Bug] [Server] Task plugin dir should be included in install and config file

### ISSUE THREAD

**Issue by RichardStark** [apache/dolphinscheduler#6298]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

If we followed the doc to deploy cluster, we will find the worker cannot find the task plugin because the task plugin dir is empty by default

### What you expected to happen

Related info should be added in the install file

### How to reproduce

just follow the doc to deploy a cluster DS 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
close by #6299
