### ISSUE TITLE
[Bug] [UI] The task instance successfully enforces the failed task and reports an error

### ISSUE THREAD

**Issue by brave-lee** [apache/dolphinscheduler#6301]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/42576980/134448048-bc16a578-e513-437d-b15e-756379dfcb04.png)

### What you expected to happen

Forced success will succeed

### How to reproduce

Force successful operation for failed tasks

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tandoy** [comment]
@JinyLeeChina I will try to fix it.
