### ISSUE TITLE
[Bug] [UI]  When creating an alarm instance, the alarm plug-in does not render

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#6319]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

branch : dev

i have read the proposal(#3049 ), and i found the problem,
When creating an alarm instance, the alarm plug-in does not render
### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
i have read the proposal(#3049 ), and i found the problem, 
When creating an alarm instance, the alarm plug-in does not render.

**Comment by wangyizhi1** [comment]
#6325

There is a null pointer exception in the front end. I fixed it. However, the specific causes are not clear, which may be one of the following reasons: 
1. The back end of the ``pluginParams`` field of the ``/ui-plugins/{id}`` interface has been modified. The ``props`` field in ``pluginParams`` may have a ``not-null`` value before, but now it is ``null``.
2. There may be a problem with the ``@form-create/ element-UI`` front-end plug-in itself.
