### ISSUE TITLE
[Bug] [MasterServer] make CPU 100% even without task

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#6323]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

branch: dev

master-server make CPU high even without task.

because EventExecuteService run loop without sleep.

### What you expected to happen

low CPU usage when idle

### How to reproduce

run master-server and observe CPU usage.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good job
if this issue has been solved, please close this issue, thx
