### ISSUE TITLE
[Question] Question title The correct YARN status cannot be obtained

### ISSUE THREAD

**Issue by k9flame** [apache/dolphinscheduler#6326]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

My task was successfully executed in YARN, but failed in the WORKFLOW instance of DS

### DolphinScheduler Version

1.3.5

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tandoy** [comment]
1.You may need to check 
path: /conf/common.properties
config: yarn.resourcemanager.ha.rm.ids or yarn.application.status.address

2.check the yarn conf for ds
path: /conf/config/install_config.conf
config: yarnHaIps or singleYarnIp
[https://dolphinscheduler.apache.org/zh-cn/docs/1.3.5/user_doc/configuration-file.html](url)

**Comment by kamisangk** [comment]
How many Resource Manager nodes？I guess you have more than 2

**Comment by k9flame** [comment]
> How many Resource Manager nodes？I guess you have more than 2
Yes, there are three

**Comment by kamisangk** [comment]
I think you can modify this piece of code 
Like "https://github.com/apache/dolphinscheduler/pull/4344"
dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HadoopUtils.java 
![image](https://user-images.githubusercontent.com/25461086/134613692-ec394885-4888-4f4a-b243-fc5cc55cec06.png)

**Comment by k9flame** [comment]
> I think you can modify this piece of code
> Like "#4344"
> dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HadoopUtils.java
> ![image](https://user-images.githubusercontent.com/25461086/134613692-ec394885-4888-4f4a-b243-fc5cc55cec06.png)

Thank you mogul, the code has been changed and the problem has been resolved
