### ISSUE TITLE
[Bug] [UI] Process instance view variables bug

### ISSUE THREAD

**Issue by brave-lee** [apache/dolphinscheduler#6328]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/42576980/134615581-72c8c369-2dae-4a07-b7ab-79286127f074.png)

### What you expected to happen

view variables normally

### How to reproduce

Click the view Variables button of processInstance

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangyizhi1** [comment]
i will fix it
