### ISSUE TITLE
[Question] 工作流实例一直不执行，workflow instance don't running

### ISSUE THREAD

**Issue by luojieio** [apache/dolphinscheduler#6329]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://user-images.githubusercontent.com/25678606/134627142-895545e3-fe60-4325-8aca-324bd5e813cb.png)
![image](https://user-images.githubusercontent.com/25678606/134627202-4a9092f0-0802-4f0a-a0fe-7c12b60b6068.png)

### DolphinScheduler Version

1.3.6

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
any log show on master-server?

**Comment by kevinjmh** [comment]
you can check log of master. maybe out of worker to run task
