### ISSUE TITLE
[Question] 如何自建系统集成？通过api调用触发执行实例，但是参数无法传递过来怎么办？How to integrate with third-party platforms? The execution instance is triggered by api call, but the parameters cannot be passed, what should I do?

### ISSUE THREAD

**Issue by luojieio** [apache/dolphinscheduler#6330]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

如何自建系统集成？通过api调用触发执行实例，但是参数无法传递过来怎么办？How to integrate with third-party platforms? The execution instance is triggered by api call, but the parameters cannot be passed, what should I do?
比如：我想实例监控告警的时候触发，告警会传递一些告警信息，比如业务，项目，阈值，通知人，这些信息如何传递到工作流？
For example: I want to trigger when an instance monitoring alarm is triggered. The alarm will transmit some alarm information, such as business, project, threshold, and informant. How can this information be transmitted to the workflow?
### DolphinScheduler Version

1.3.6

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by crazycarry** [comment]
自己构建那个json模板，然后通过变量生成运行的json，目前那个json 是定死的，不能动态扩展
