### ISSUE TITLE
[Feature][api] Are there other default global variables like ${system.datetime}?是否还有其它全局变量，类似于${system.datetime}？

### ISSUE THREAD

**Issue by luojieio** [apache/dolphinscheduler#6333]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Are there other default global variables like ${system.datetime}?
是否还有其它全局变量，类似于${system.datetime}？

for example:
current task id ...
比如：
当前工作流的ID，可以方便的直接在脚本中引用

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DylanMao1996** [comment]
It is supported now. For example, ${aaa} can be directly referenced by using'${aaa}' in the code. The global variable acts on the entire dag. 

hope this helps.
