### ISSUE TITLE
[Bug] [UI] sql task run no result because sql limit param is lost

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#6337]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

branch: dev

When I run the pgsql task, sql can query success and get some rows, but no result display.

Because sqlParameters.limit is 0, so the result will be filtered.

### What you expected to happen

sql query rows can display normally

### How to reproduce

create a sql task like `select * from t_ds_task_instance limit 5;` and run it.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Issue close by https://github.com/apache/dolphinscheduler/pull/6387, but PR target to wrong issue. @caishunfeng @CalvinKirs  could you close this issue？
