### ISSUE TITLE
[Bug] [UI] File Manage -> Upload Files，create resource error

### ISSUE THREAD

**Issue by longhuihy** [apache/dolphinscheduler#6339]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

INSERT INTO t_ds_resources  ( file_name, size, create_time, description, full_name, alias, update_time, pid, type, user_id, is_directory )  VALUES  ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )
### Cause: org.postgresql.util.PSQLException: ERROR: column "is_directory" is of type bit but expression is of type boolean
  Hint: You will need to rewrite or cast the expression.
  Position: 192
; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: column "is_directory" is of type bit but expression is of type boolean
  Hint: You will need to rewrite or cast the expression.
  Position: 192

### What you expected to happen

ok

### How to reproduce

ok

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
For the convenience of communication, please use English titles

**Comment by wangyizhi1** [comment]
Is this the same problem? #6223

**Comment by longhuihy** [comment]
> Is this the same problem? #6223

No, my error is reported during SQL execution. The error in #6223 is due to the interface request format

**Comment by longhuihy** [comment]
> Is this the same problem? #6223

No, my error is reported during SQL execution. The error in #6223 is due to the interface request format
