### ISSUE TITLE
[Feature] Reconstruction of the timing management page

### ISSUE THREAD

**Issue by zekirin70** [apache/dolphinscheduler#6345]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Transform the timing management into a timing management list page defined by all workflows and add a search function to the timing management list page.

### Use case

# Description
a. Transform the timing management into a timing management list page defined by all workflows 
b. Add a search function to the timing management list page
# Personal idea about feature
Add a timer management button on the workflow definition page, click to enter the management page of all the timer tasks list of the current project. Add a return button on the timing management page, click to return to the workflow definition page. Record the paging parameter information, so that the page remains in the previous paging state after the page is refreshed. Add new search criteria for the search function, such as name, time, status, failure strategy,etc.

# Outline
1. Familiar with DolphinScheduler
I will spend some time to become familiar with DolphinScheduler and understand the functions of each module, especially the module involved in the project I will be responsible for.
2. Learn web development
I will learn to use the framework and component library used in the project, and conceive the project implementation plan.
3. Development
After thinking about how to implement the function, I will start coding. I will followed the principles of Clean Code and the requirements about codes, qualities, comments, etc.
4. Check Implementation
When the coding is completed, it will be checked and tested to ensure the complete realization of the function.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
@zekirin70 Could you please provide photos to display the changes before and after this changes?

**Comment by zekirin70** [comment]
# Before changes:
<img width="1173" alt="Screen Shot 2021-09-26 at 14 07 52" src="https://user-images.githubusercontent.com/27210479/134795881-688e6910-4998-48a4-b560-c6ecabc923ff.png">
# after changes:
<img width="1167" alt="Screen Shot 2021-09-26 at 14 00 42" src="https://user-images.githubusercontent.com/27210479/134795913-2ea60229-fdcf-4dfb-83e0-bba0ddefd167.png">
Add a timinglist button, which could be used to go to a list of schedulers:
<img width="1168" alt="Screen Shot 2021-09-26 at 14 00 57" src="https://user-images.githubusercontent.com/27210479/134795955-6d71da69-dcc1-4c10-bfc4-d491cd98dc6f.png">
In this page, you can edit, delete or search(by process name, status or start time) a particular scheduler:
Search by process name:
<img width="1171" alt="Screen Shot 2021-09-26 at 14 02 14" src="https://user-images.githubusercontent.com/27210479/134796015-be9c0a38-db0d-4a34-bd8a-c00d1df8b487.png">
Search by status:
<img width="1163" alt="Screen Shot 2021-09-26 at 14 01 14" src="https://user-images.githubusercontent.com/27210479/134796021-421a90b6-4ffc-406d-ae13-7047a9ccaa7e.png">
<img width="1170" alt="Screen Shot 2021-09-26 at 14 01 25" src="https://user-images.githubusercontent.com/27210479/134796046-6e8ae735-0ee0-4bca-912b-073276f2e184.png">
Search by start time:
<img width="1174" alt="Screen Shot 2021-09-26 at 14 01 49" src="https://user-images.githubusercontent.com/27210479/134796058-598da13b-4f06-426b-be25-ce5bb3052c4f.png">
<img width="1174" alt="Screen Shot 2021-09-26 at 14 01 58" src="https://user-images.githubusercontent.com/27210479/134796064-67c256ee-7e4a-4d2b-97a5-e37a0de560b2.png">
