### ISSUE TITLE
[Bug] [API] Project created failure and unknown column p.code in field list

### ISSUE THREAD

**Issue by aaronlinv** [apache/dolphinscheduler#6348]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Refer to https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/dev_run.html
And run org.apache.dolphinscheduler.dao.upgrade.shell.CreateDolphinScheduler

The code is the latest dev branch. This issue is similar to this one: #5540  ,but this one has been solved.

Run `dolphinscheduler\sql\dolphinscheduler_mysql.sql` to reproduce the database structure and the project is successfully created.

![image_293](https://user-images.githubusercontent.com/11210385/134778354-55fa250a-3a6d-4e8c-97e8-12a48453ee86.png)

![image_294](https://user-images.githubusercontent.com/11210385/134778359-3bcb479e-adcf-4b42-9dd3-8af544450006.png)

### What you expected to happen

Create project successfully

### How to reproduce

Run the latest dev and create a new project

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
Please confirm that the database used is up-to-date
