### ISSUE TITLE
[Question]自己集成任务成功失败的预警通知，求大佬指导

### ISSUE THREAD

**Issue by Level1Accelerator** [apache/dolphinscheduler#6349]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

看了一会儿源码，没找到工作流触发成功失败，邮件是怎么发出通知的，如果能找到是怎么触发的，就好改了，有大佬知道在哪个位置么

### DolphinScheduler Version

1.3.8

### Additional context

1

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kevinjmh** [comment]
please see `AlertServer`  , it will query backend DB and call `AlertSender` to send msg
