### ISSUE TITLE
woker group permissions 

### ISSUE THREAD

**Issue by 865357384** [apache/dolphinscheduler#6350]
I've been using version 1.3.2 for a long time, but I haven't paid much attention to the subsequent versions, so I'd like to ask whether the permissions of the subsequent versions can authorize the function module for worker grouping?

**Comment by Tandoy** [comment]
As far as I know, authorization management of worker groups is not supported for the time being. But you can use the following 2.0 demo environment to explore.

[http://8.142.34.29:12345/dolphinscheduler](url)
