### ISSUE TITLE
[Bug] [ApiServer] override the old process definition when I use the copy workflow feature

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#6352]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

branch: dev

When I try to copy workflow form process definition `python001`, it doesn't create a new process definition but update the old one with name like `python001_copy_20210926112401233`.

### What you expected to happen

create a new process definition instead of an override.

### How to reproduce

just create a process definition and copy it.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
Thank you for your feedback. I will fix it
