### ISSUE TITLE
[Bug] [Master]  dispatch task to worker very slowly

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#6353]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

branch: dev
i find master dispatch tasks to worker slowly .

mysql> select count(*),state from t_ds_task_instance group by state;
+----------+-------+
| count(*) | state |
+----------+-------+
|    15347 |     7 |
|       12 |     1 |
+----------+-------+
2 rows in set (0.01 sec)

mysql> select count(*),state from t_ds_process_instance group by state;
+----------+-------+
| count(*) | state |
+----------+-------+
|      892 |     7 |
|    12109 |     1 |
+----------+-------+

### What you expected to happen

Optimize the speed of dispatch task

### How to reproduce

create a dag 

![image](https://user-images.githubusercontent.com/29528966/134792830-967b6674-52c8-4241-a02e-c4c23b593904.png)

schedule the dag '0 * * * * ? *'
run the dag with 'complement data'
you will find the process_instance count: 12109
but the task (state=1) number is 12
This phenomenon is not normal

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
When I reproduce in local env, I found that task instance is complete quickly, but process instance slowly, 
and log show that EventExecuteService.eventHandler only deal with one workflowExecuteThread each loop.
That's why the event handle slowly.
