### ISSUE TITLE
[Bug] 资源使用问题

### ISSUE THREAD

**Issue by caiyt2001** [apache/dolphinscheduler#6371]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

分支：data_quality_design

资源使用模块，设计到shell，python等控件
选择多个控件，前端只显示1个，但是数据库里面是有多个，如果下次编辑忘记选择，就会变成只有一个
![image](https://user-images.githubusercontent.com/35490928/134850503-e3f7e13e-57d4-4a60-88c6-fcd80e5654d7.png)

### What you expected to happen

前端Bug

### How to reproduce

前端Bug

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
@caiyt2001 
For the convenience of communication, please use English
