### ISSUE TITLE
[Bug][SPI] The  spi plugin support work in windows os.

### ISSUE THREAD

**Issue by echohlne** [apache/dolphinscheduler#6380]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In #5652, I've fixed the filePath bug between different os
but in the latest dev branch, the modification has been overwritten, it would cause the project cannot run in the windows.

### What you expected to happen

To ensure the bug can be fixed.

### How to reproduce

just clone the latest dev branch and try to run `MasterServer` in windows.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
done
