### ISSUE TITLE
[Feature][Doc] Add registry spi to our development doc

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#6390]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

According to the https://github.com/apache/dolphinscheduler/issues/6129#issuecomment-914956773, we found out our [development doc][1] missing part of [registry spi][2]. Make we should update doc and add it

[1]: https://dolphinscheduler.apache.org/en-us/development/development-environment-setup.html
[2]: https://dolphinscheduler.apache.org/en-us/docs/dev/user_doc/registry_spi.html

### Use case

A simple and runnable doc for beginner.

### Related issues

https://github.com/apache/dolphinscheduler/issues/6129

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Could anyone tag labels `good-first-issue` for this issue?

**Comment by didiaode18** [comment]
+1 @CalvinKirs

**Comment by zhongjiajie** [comment]
remove stale

**Comment by zhongjiajie** [comment]
remove stale
