### ISSUE TITLE
[Bug] [Web] 进入子节点后页面一片空白

### ISSUE THREAD

**Issue by xiaoyangdeve** [apache/dolphinscheduler#6396]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

在工作流或工作流实例中进入该子节点时，跳转的URL漏掉了project_id 

跳转的url如下：
http://xxx.com/dolphinscheduler/ui/#/projects/instance/list/47752?subProcessIds=47751
正确的应该是：
http://xxx.com/dolphinscheduler/ui/#/projects/****12*****/instance/list/47752?subProcessIds=47751

### What you expected to happen

应该在跳转的时候带上project_id

### How to reproduce

在url中添加相应ID

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
To facilitate communication, please use English titles and content.
When you modify it, you can reopen it.
