### ISSUE TITLE
[support Oracle as datasource][dolphinscheduler-dao] we can do something  to use Oracle as datasource.

### ISSUE THREAD

**Issue by grunt1024** [apache/dolphinscheduler#6397]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

There is a lot of sql  in dao layer which can not support Oracle grammer ，such as "limit 1".

Can these sql  be replaced ? I can fix it by modifying dao layer and service layer.

### Use case

I hope  the sql in dao layer don't binding one kind of DB，but some general  syntax.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
@grunt1024 
good idea, are you willing to put forward your idea to realize this part?
