### ISSUE TITLE
[Bug] [Worker] 数据补数时日期计算错误

### ISSUE THREAD

**Issue by xiaoyangdeve** [apache/dolphinscheduler#6400]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

${system.biz.date} | 日常调度实例定时的定时时间前一天，格式为 yyyyMMdd，补数据时，该日期 +1
-- | --

以上内容拷贝自官方文档

没太搞明白为啥补数要+1的操作

在补数据时对日期+1的操作，会导致传入脚本的日期+1，从而无法获取正常结果，特别调度任务是在周调度、月调度等不适连续天调度执行的情况下，在此情况我只能通过修改调度时间或者用其他方式实现补数

### What you expected to happen

在补数时，该变量应该遵循定义的值，不应该+1

### How to reproduce

在补数时，该变量应该遵循定义的值，不应该+1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
@lenboo Could you please take a look is this issue related to PR https://github.com/apache/dolphinscheduler/pull/6389

**Comment by lenboo** [comment]
@XiaoYoungk 
  For the convenience of communication, please use English title and content.

**Comment by CalvinKirs** [comment]
To facilitate communication, please use English titles and content.
When you modify it, you can reopen it.
