### ISSUE TITLE
[Bug] [issue bot] Translation bot only translate title without content

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#6405]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When PR https://github.com/apache/dolphinscheduler/pull/6394 merged, our issue bot work again so as translation bot. But translation bot only translated issue title without content. You could find example issue in https://github.com/apache/dolphinscheduler/issues/6404

![image](https://user-images.githubusercontent.com/15820530/135096982-a5e98092-dac1-4ccb-9c75-20b9102ffbf3.png)

### What you expected to happen

Translation both title and content

### How to reproduce

Create a new issue

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Please do not make your hand dirty until we discuss if we should only support English for issue and PR in mailing-list

**Comment by zhongjiajie** [comment]
We have a discuss in the mailing-list in https://lists.apache.org/thread.html/r0c2e9f9fa8968936884191371592791616bcc609375b9f84a4ec1155%40%3Cdev.dolphinscheduler.apache.org%3E

And if this discuss pass, we should remove translation bot instead of fix it.

**Comment by davidzollo** [comment]
any conclusion?

**Comment by zhongjiajie** [comment]
> any conclusion?

Yeah, discuss in https://lists.apache.org/thread.html/r0c2e9f9fa8968936884191371592791616bcc609375b9f84a4ec1155%40%3Cdev.dolphinscheduler.apache.org%3E draw a conclusion that we should support Chinese issue. Seem we have to fix our translate bot instead of remove it.

I would take a look in this week after other thing done.

**Comment by zhongjiajie** [comment]
@dailidong  I submit new issue and find out our translator bot work again, meaning it is no problem for now. see in  https://github.com/apache/dolphinscheduler/issues/6709#issuecomment-961823893

**Comment by zhongjiajie** [comment]
Close it now, see above for detail information
