### ISSUE TITLE
[Feature][TIS] rename tis to pigeon

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#6423]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

in order to 
1 rename the tis task to pigeon task 
2 change the tis logo to pigeon

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jixiang155** [comment]
I will resolve it

**Comment by zhongjiajie** [comment]
@lenboo I seem we should close this issues

**Comment by zhuangchong** [comment]
This issue has been resolved, close this issue.
