### ISSUE TITLE
[Bug] [dev] Code style different between review dog and Intellij configure

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#6428]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Following the [submit guide][1], I run formatter by using `Ctrl+L` in Intellij and push to upsteam, the commit is https://github.com/apache/dolphinscheduler/pull/6269/commits/bb9f050fdf87c91f1dfe8ad6d9e91f3875475abe, but it failed in our reviewdog CI, see [ci run][2].

It means that our auto formatter and reviewdog checker have different rule. what reivewdog accept format is 

```java
@ComponentScan(value = "org.apache.dolphinscheduler", excludeFilters = {
    @ComponentScan.Filter(type = FilterType.REGEX, pattern = {
        "org.apache.dolphinscheduler.server.master.*",
        "org.apache.dolphinscheduler.server.worker.*",
        "org.apache.dolphinscheduler.server.monitor.*",
        "org.apache.dolphinscheduler.server.log.*"
    })
})
```

but our auto formatter is

```java
@ComponentScan(value = "org.apache.dolphinscheduler", excludeFilters = {
        @ComponentScan.Filter(type = FilterType.REGEX, pattern = {
                "org.apache.dolphinscheduler.server.master.*",
                "org.apache.dolphinscheduler.server.worker.*",
                "org.apache.dolphinscheduler.server.monitor.*",
                "org.apache.dolphinscheduler.server.log.*"
        })
})
```

[1]: https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html
[2]: https://github.com/apache/dolphinscheduler/actions/runs/1287112918

### What you expected to happen

Auto formatter and reviewdog should in the same rule

### How to reproduce

Create new java code contain `@ComponentScan(value = "org.apache.dolphinscheduler"` and create new PR

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
Hi @zhongjiajie , review dog uses the results of `checkstyle` plugin, so this to me is the gap between `check style` rules and IntelliJ IDEA rules, I'd suggest we remove the IDEA code style settings and have our contributors to install IntelliJ `checkstyle` plugin, and then import the check style settings directly, it might be troublesome to align the rules between IntelliJ one and check style one

**Comment by zhongjiajie** [comment]
I got your point, it's means our rules from IntelliJ plugin `checkstyle` and IntelliJ code style conflict. I would try it in my laptop. And send email to discuss remove IntelliJ code style if could success in my env. Thanks @kezhenxu94
