### ISSUE TITLE
[Bug] [ui] sub_process node open sub_task show empty page

### ISSUE THREAD

**Issue by zousss** [apache/dolphinscheduler#6429]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

version:1.3.8
problem:when i use sub_process node,it works ok,but when i click enter sub_task,it shows empty page.

### What you expected to happen

I see the url is http://localhost:12345/dolphinscheduler/ui/#/projects/definition/list/31?subProcessIds=35,i guess the url lost project_id,then i use http://localhost:12345/dolphinscheduler/ui/#/projects/4/definition/list/31?subProcessIds=35,it opens ok.

### How to reproduce

use 1.3.8,just create sub_process node ,then click the enter sub_task button

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zousss** [comment]
![e1bc9aa2fe624a1f7877ac663e41553](https://user-images.githubusercontent.com/19742536/135418889-2340c2d7-4793-43ab-9de1-edbadd3d817f.png)

**Comment by zhuangchong** [comment]
This bug has been fixed in the dev branch, if there is any problem, please open this issue again.
