### ISSUE TITLE
[Feature] Can support setting up holidays

### ISSUE THREAD

**Issue by robin253** [apache/dolphinscheduler#643]
Can you support holiday settings? Or other alternatives?

---
能否支持节假日设置？或者其他变通的办法？

**Comment by dailidong** [comment]
good idea, not support holidays setting for now!

**Comment by jxauwxj** [comment]
增加个日历功能即可。

**Comment by moonhunter1986** [comment]
good idea..如果可以在日执行计划中选择设定排除日即可

**Comment by BoYiZhang** [comment]
I implemented one, but the interface was ugly


![image](https://user-images.githubusercontent.com/39816903/84732638-c61af280-afce-11ea-8c80-092acdcf3d6d.png)

**Comment by gabrywu** [comment]
@BoYiZhang wich PR?
