### ISSUE TITLE
[Improvement] [MasterServer] find one command optimize without mybatis-plus

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#6433]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

branch: dev
When I open debug log on local, queryCommandPage use mybatis-plus will execute select count(1) first, but it is needless in this case.

So I did a comparison with command 2w+,  execute findOneCommand 10000 times and watch avg use time:

- mybatis-plus page:  avg use time more than 3ms

- native sql query: avg use time about 1.5 ms

### What you expected to happen

findOneCommand more quickly

### How to reproduce

just run it

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
if the issue was been solved , please close this issue in time
