### ISSUE TITLE
[Improvement][Standalone] Run h2 in daemon mode

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#6445]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In standalone, we use h2 as the database.
If the creation table sql is wrong, it will throw an exception, but the server will keep running.
It's better to stop.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good job
