### ISSUE TITLE
[Bug] [DataX] Read data from mysql and write to SqlServer 2012 database (DS version: 1.3.6)

### ISSUE THREAD

**Issue by sakinsun** [apache/dolphinscheduler#6451]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

我在DS 1.3.6版本中，使用datax插件，数据源为mysql，目标源为sqlserver，使用的是 "非自定义模板"的方式，就是 mysql的地方写sql语句，目标sqlserver地方直接填写表名，然后运行这个节点。结果运行报错，报错内容如下：
”Description:[获取表字段相关信息失败.].  - 获取表:test_tmp_20211001 的字段的元信息时失败. 请联系 DBA 核查该库、表信息. - com.microsoft.sqlserver.jdbc.SQLServerException: “`”附近有语法错误。”

DataX在DS下运行后，日志中可以看到在获取sqlserver元数据字段的时候是这样的：
"writer":{
					"name":"sqlserverwriter",
					"parameter":{
						"column":[
							"`suppid`"
						]

sqlserver表字段是用 ` 这个号引起来的，导致在sqlserver里面查询元数据报错，DS源码如下：
switch (dbType) {
            case MYSQL:
                return String.format("`%s`", column);
            case POSTGRESQL:
                return String.format("\"%s\"", column);
            case ORACLE:
                return String.format("\"%s\"", column);
            case SQLSERVER:
                return String.format("`%s`", column);   --------- 就是这里！！！！
            default:
                return column;
        }
    }

源码所在github位置：dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxUtils.java

### What you expected to happen

如上述，在DS中同样使用datax插件 且使用"自定义模板"的方式，贴好配置信息及表字段，并且字段 无 ` 引号的情况下，mysql数据顺利写入sqlserver中，写入成功。

### How to reproduce

改用"自定义模板"，但是使用了这个，那界面图形化就失去了意义，而且通过贴配置信息很不方便，每次都要贴账号密码及链接。

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sakinsun** [comment]
https://github.com/sakinsun/pic/blob/main/sqlserverwriter-column.png

github上的 ` 间隔号无法正常显示，所以我把ds上的日志截图了

**Comment by davidzollo** [comment]
good job, please submit a PR

**Comment by davidzollo** [comment]
by the way, as a global project, English is needed, please describe the question in English

**Comment by sakinsun** [comment]
First,I am sorry because I am chinese,so my english is not very good.But I am very interested to DS.


My suggestion is to remove the symbol  "`"   in the code processing SQL server module  from this code file :DataxUtils.java。

source code
case SQLSERVER:
                return String.format("`%s`", column);

suggest code
case SQLSERVER:
                return String.format("%s", column);   -- no symbol `
