### ISSUE TITLE
[Bug] [UI] The front-end verification task name already exists

### ISSUE THREAD

**Issue by zhuangchong** [apache/dolphinscheduler#6463]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The front-end verification task name already exists

### What you expected to happen

The task name can have the same

### How to reproduce

remove front-end verification in the formModel.vue

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I'll fix this issue.
