### ISSUE TITLE
[Bug] [api updateProcessDefinition error ] /dolphinscheduler/projects/{projectName}/process/update error

### ISSUE THREAD

**Issue by gglinux** [apache/dolphinscheduler#6475]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I use '/dolphinscheduler/projects/{projectName}/process/update', report a error. I don't know what happened.

I only need to update part of the content, this parameter of id(94) exists.

![image](https://user-images.githubusercontent.com/7273957/136654436-ddf83c21-fad9-407f-a822-f99d7f8ab970.png)

### What you expected to happen

1. You'd better tell me why failed
2. I can choose to update some values

### How to reproduce

1.3.5

curl -X POST "http://{host}/dolphinscheduler/projects/{project_name}/process/update" -H  "Request-Origion:SwaggerBootstrapUi" -H  "accept:*/*" -H  "Content-Type:application/x-www-form-urlencoded;charset=UTF-8" -d "id=94" -d "name=aaaa"

### Are you willing to submit PR?

- [] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
The error context will be recorded in the dolphinscheduler-api.log log file, please check the detailed error information.

**Comment by gglinux** [comment]
thx,I get.

I must update all fields,  this dolphinscheduler api will be succeed.
