### ISSUE TITLE
[Bug] [ui] ZooKeeper ui cannot display

### ISSUE THREAD

**Issue by shangeyao** [apache/dolphinscheduler#6492]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/42203474/136738930-02a42693-d004-4b72-9c2a-5ba3658a4bc7.png)

### What you expected to happen

zookeeper ui can display

### How to reproduce

maven build version **dev**, just see it.

### Anything else

My environment is the cluster of zookeeper, three machine, i don't know if this is the reson.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
@shangeyao Thanks for your report, this seems a duplicate issue #6216.
If there are no other concerns, this issue can be closed, please go to #6216 to discuss.
