### ISSUE TITLE
[Bug] [Task] Shell task can not use user defined environment correctly

### ISSUE THREAD

**Issue by LiuBodong** [apache/dolphinscheduler#6497]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

branch:dev

When submitting a Shell task, the task cannot correctly obtain and set user-defined environment variables

### What you expected to happen

Shell task could obtain user-defined when created and could wite the user-defined env config to the `command file` correctly

### How to reproduce

* create a new env
* create a task with the newly created env
* execute the task
* see task log, the env is not used correctly

### Anything else

# How often does problem occur?
always
# Why this problem occur ?
* When submit a task, the work obtain a `Command` from DB and get `TaskExecutionContext` from the command.
* Then transform `TaskExecutionContext` to `TaskRequest`, TaskExecutionContext` contains a field named `environmentConfig` * to stored user-defined env, but `TaskRequest` **NOT** contains the field, so the user-defined env lost.
* When a `ShellCommandExecutor` created, it only get the dolphinscheduler's system env file and execute `source` command to set the env, but **DO NOT**  set the user-defined env.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
LGTM.
