### ISSUE TITLE
support to execute tasks on k8s pods

### ISSUE THREAD

**Issue by tocjava** [apache/dolphinscheduler#6503]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Airflow version 1.10 introduces Kubernetes Executor and Kubernetes Operator, allowing new Pods to be created for each task to process, and the newly created Pod will be cleaned up after execution, and each task can be specified with a different Docker image for processing
Airflow 1.10 版本引入了 Kubernetes Executor 和 Kubernetes Operator 允许为每一个任务创建新的 Pod 来处理，而执行完之后新创建的 Pod 会被清理掉，并且每一个任务都可以指定不同的 Docker image 来处理

Should DolphinScheduler also support this way to perform tasks?
DolphinScheduler 是否应该也支持这种方式来执行任务?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chengshiwen** [comment]
Duplicated with #5648

**Comment by ruanwenjun** [comment]
@chengshiwen @zhongjiajie Should this issue be closed? Since duplicate with #5648.
