### ISSUE TITLE
[Feature][Dao] Upgrade com.mysql.jdbc.Driver

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#6505]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Since we have upgraded the mysql connector to 8.0.15 #6484, it's necessary to use `com.mysql.cj.jdbc.Driver` the `com.mysql.jdbc.Driver` has been deprecated.

Also note if we need to modify the current connection parameters, e.g. `useSSL=false`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Well done, I just want to create this new issue 😄

**Comment by ruanwenjun** [comment]
@zhongjiajie I can assign to you:smirk:

**Comment by zhongjiajie** [comment]
For sure about that

**Comment by zhongjiajie** [comment]
Test no stale

**Comment by yangzi1104** [comment]
Has that part been solved

**Comment by ruanwenjun** [comment]
> Has that part been solved

Not yet, welcome to submit pr.

**Comment by yangzi1104** [comment]
Ok, let me try

**Comment by zhongjiajie** [comment]
@lyggyhmm Great! feel free to take it, I even forgot about it, looking forward your contribution.
And so sorry about @ruanwenjun for no response for such a long time.

**Comment by yangzi1104** [comment]
I have submitted pr, hope it is useful

**Comment by yangzi1104** [comment]
Please give pointers if there is an error，Thanks！

**Comment by yangzi1104** [comment]
> @lyggyhmm太棒了！随意拿走，我什至忘记了，期待你的贡献。 很抱歉@ruanwenjun这么长时间没有回复。

I also ask seniors for your advice

**Comment by RedemptionC** [comment]
> I have submitted pr, hope it is useful

it seems that your PR isn't linked to this issue

**Comment by zhongjiajie** [comment]
> > I have submitted pr, hope it is useful
> 
> it seems that your PR isn't linked to this issue

Could you please point PR out and we could connect it to this issue.

**Comment by RedemptionC** [comment]
> > > I have submitted pr, hope it is useful
> > 
> > 
> > it seems that your PR isn't linked to this issue
> 
> Could you please point PR out and we could connect it to this issue.

😂  I mean, where is his PR?

**Comment by ruanwenjun** [comment]
@zhongjiajie @RedemptionC I have linked the pr, please review.

**Comment by zhongjiajie** [comment]
> @zhongjiajie @RedemptionC I have linked the pr, please review.

Thanks @ruanwenjun and I add some suggest to PR.
