### ISSUE TITLE
[Question] [Plugin-APM] SkyWalking Plugin is missing

### ISSUE THREAD

**Issue by CalvinKirs** [apache/dolphinscheduler#6515]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

We can find the SkyWalking plug-in in 1.3.8（https://github.com/apache/dolphinscheduler/tree/1.3.8-release/ext/skywalking）, 

but the dev branch does not seem to have it.

### What you expected to happen

SkyWalking Plugin is missing in DEV branch

### How to reproduce

no

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
@hailin0 hi, can you help me take a look?

**Comment by zhuangchong** [comment]
@hailin0 hi, can you help me take a look?

**Comment by kezhenxu94** [comment]
No stale
