### ISSUE TITLE
[Feature]  configration of grafana

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#6520]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In order to observe the operation of the DS system, I think it is very necessary to use the grafana plug-in.
we can see the jvm running state on grafana, and i think some indicators can also display on grafana.
eg:
count of task in a period time (10 mins): 
"select count(*) from t_ds_task_instance where start_time between $startDate and $endDate";

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
Let me take a look at this
