### ISSUE TITLE
[Bug] [Task] task log using error

### ISSUE THREAD

**Issue by CalvinKirs** [apache/dolphinscheduler#6537]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/16631152/137439540-4594a679-f489-4b76-bab6-da562e8035bd.png)

### What you expected to happen

Business logs should not be handed over to task-logger

### How to reproduce

no

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
i notice that we can set the error log to worker-log.

also there would be a total solution:  we can detect the rationality of tenants on the API side.

so please keep this issue open until we finish all the work.
