### ISSUE TITLE
[Bug] [Dist] The main class org.apache.dolphinscheduler.server.StandaloneServer could not be found or loaded

### ISSUE THREAD

**Issue by zhuangchong** [apache/dolphinscheduler#6539]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The dolphinscheduler project is packaged into a binary package, the Standalone-Server service is started, and the log reports an error: the main class org.apache.dolphinscheduler.server.StandaloneServer cannot be found or cannot be loaded.

### What you expected to happen

The Standalone-Server service started successfully.

### How to reproduce

the Standalone-Server service is started, and the log reports an error: the main class org.apache.dolphinscheduler.server.StandaloneServer cannot be found or cannot be loaded.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
How did you start the standalone server? Did you use the shell script to start?

**Comment by kezhenxu94** [comment]
I mean this https://github.com/apache/dolphinscheduler/blob/ba4cb9d22ad02ba4927fd23ea811c82639261e69/script/dolphinscheduler-daemon.sh#L91

**Comment by zhuangchong** [comment]
> How did you start the standalone server? Did you use the shell script to start?

Sorry, I found this problem in the test on 1.3.9-prelease, the dev branch does not have this problem, I will submit a PR to 1.3.9-prelease to fix this problem.

**Comment by zhuangchong** [comment]
done.
