### ISSUE TITLE
[Bug] [Schedule] Task  Incorrect duplicate scheduling

### ISSUE THREAD

**Issue by geosmart** [apache/dolphinscheduler#6555]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

version: v1.3.6

### What happened

process instance
![image](https://user-images.githubusercontent.com/3156608/137657828-b1328daa-0869-49bd-a42c-d95db8ac1553.png)

![image](https://user-images.githubusercontent.com/3156608/137657631-76c177d9-a7c6-4cc1-8fa1-40c32f99a35e.png)

task instance
![image](https://user-images.githubusercontent.com/3156608/137657602-bfb0a537-9911-4ebb-ada7-8975a2b233c9.png)

the sqoop task is scheduled mutilple times (5 times) , what does this happen?

### What you expected to happen

the sqoop task should just schedule 1 time

### How to reproduce

don't konw why this happen

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
hi,which version?
