### ISSUE TITLE
[Bug] Delay execute  When I didn't set it up

### ISSUE THREAD

**Issue by shangeyao** [apache/dolphinscheduler#6558]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/42203474/137701127-f069fe0e-55be-4ce5-9580-b45640388efa.png)
I click the button of run, then I found out that it delayed the execution.
![image](https://user-images.githubusercontent.com/42203474/137701696-db309b82-9373-49be-b4cc-c3a2a72453c9.png)

### What you expected to happen

Execute immediately.

### How to reproduce

As shown in the figure above.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
Can you provide specific information, such as version and delay? The scheduling itself is not executed immediately, and it takes a certain amount of time for the task to be called up.

**Comment by shangeyao** [comment]
> 您能否提供具体信息，例如版本和延迟？调度本身并不是立即执行的，需要一定的时间才能调用任务。

version:dev
delay:about 10 minutes
description:If I set up the worker group, not using default, then will delay execute.
