### ISSUE TITLE
[Bug] [TASK] sql task udf resource not loaded

### ISSUE THREAD

**Issue by Narcasserun** [apache/dolphinscheduler#6570]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.sql task udf resource not loaded
2.Inconsistent serialization resulted in type conversion exception

### What you expected to happen

--

### How to reproduce

--

### Anything else

--

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
Has been completed.
