### ISSUE TITLE
[Bug] [dolphinscheduler-common] when task type is COMPLEMENT_DATA , the parameter datetime will one more day

### ISSUE THREAD

**Issue by choucmei** [apache/dolphinscheduler#6575]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 when task type is COMPLEMENT_DATA , the parameter datetime will one more day;
for example:
scheduler time : 2019-12-20 00:00:00
but get systime is :
{system.biz.curdate=20191221, system.biz.date=20191220, system.datetime=20191221000000}

### What you expected to happen

example:
scheduler time : 2019-12-20 00:00:00
but get systime is :
{system.biz.curdate=20191220, system.biz.date=20191219, system.datetime=20191220000000}

### How to reproduce

I found key code:  org.apache.dolphinscheduler.common.utils.placeholder.BusinessTimeUtils#getBusinessTime

i can't understand

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by choucmei** [comment]
i found same issue 
https://github.com/apache/dolphinscheduler/issues/5979

**Comment by choucmei** [comment]
@Test
    public void systemParamsTest01() throws Exception {
        Date scheduleTime = DateUtils.stringToDate("2019-12-20 00:00:00");
        System.out.println(BusinessTimeUtils.getBusinessTime(CommandType.START_CURRENT_TASK_PROCESS,scheduleTime));

        Date scheduleTime1 = DateUtils.stringToDate("2019-12-20 00:00:00");
        System.out.println(BusinessTimeUtils.getBusinessTime(CommandType.COMPLEMENT_DATA,scheduleTime1));
    }

**Comment by CalvinKirs** [comment]
The day before the scheduled time of the daily scheduling instance, the format is yyyyMMdd, when the data is supplemented, the date is +1.

**Comment by CalvinKirs** [comment]
Repeated question #5979
