### ISSUE TITLE
[Bug] [master] process scheduler and some process jobs are not triggered normally  

### ISSUE THREAD

**Issue by MarlboroBoy** [apache/dolphinscheduler#6588]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I used dolphinscheduler on version 1.3.5 and configured some scheduled jobs. About 100 of them were triggered at the same time, but I found that some scheduled jobs were not triggered, and there were no errors in the master log. Record of field pre_fired_time in table QRAZ_TRIGGERS  is -1.that means is doesn't triger. 
I hope get your help,thanks.

### What you expected to happen

a

### How to reproduce

scheduler the same time on 1000 process 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Thank you for your issue.
But can you provide more message like:
which version you use?
any warn log in ProcessScheduleJob?
is there any misfire message in table QRAZ_TRIGGERS?

And I think two parts will affect quartz:
1、the org.quartz.threadPool.threadCount, default 25, maybe you can large it and have a try.
2、the logic of ProcessScheduleJob execute, will create a command, which is a db operation and it will take some times.
