### ISSUE TITLE
[Proposal] DolphinScheduler plugin loading and packaging Design

### ISSUE THREAD

**Issue by Narcasserun** [apache/dolphinscheduler#6589]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Hello everyone
      The subject of this email is to initiate a discussion on DS plugin loading and packaging Design. DS plugin related load adjustment is very important,so I will use Chinese and English to describe.
### 1.aims
      
- The core purpose of s plugin is to decouple the upper core logic of DS from the specific implementation. Some design concepts help DS become a very easy to expand project. Recently, I have been doing secondary development based on ds2.0, but I found that the packaged directory of each DS plug-in has the same dependent jar, and the transformation made by Presto on SPI loading results in nearly 1g compressed packages after packaging. I think the DS community doesn't want to see this.

-  We hope that DS can not only improve its scalability, but also improve its maintainability through class loading sharing and directory sharing. DS plug-ins only need to maintain the implementation of plug-ins, which will be very friendly to new developers who want to participate in the DS community.

### 2. The following is my analysis of the disadvantages of DS plug-in packaging
The transformation of ds2.0 has come to an end, and the scalability has been greatly improved. By using java SPI to realize the design of plugin, the upper core logic of DS is decoupled from the specific implementation

​ DS and presto define the same rule * * plugins should not have access to the system (application) class loader * *. Although this avoids a certain waste of resources, the disadvantage is that there will be duplicate jars in each plug-in packaging directory, resulting in an increase of nearly 50% from about 130M to about 200M

### 3. Shared directory design

   In recent research, it was found that Trino, which also has the disadvantage of duplicate plug-in packaging, solves the problem of duplicate jars in each plug-in packaging directory by sharing directories. So I'm going to learn from Trino's solution，We expect has a script to run on top of the unpacked  tarball ，which contains hard links for any duplicate named JAR files. All of the JARs are moved to a top level shared directory and replaced with symlinks.
  
-  When packaging, package the project itself and all dependencies of the plug-in into the same directory
- Write a script that can be run during packaging to create soft connections that depend on the project and each plug-in

The following is an example of Trino packaging
<img width="387" alt="72f749d461f5be87a3ad8f2d86e2b38" src="https://user-images.githubusercontent.com/39329477/138893410-31f3a175-414f-48e3-a33d-11c8025069ca.png">
<img width="567" alt="2bc004a102e3d91d22beb13a83e8f2f" src="https://user-images.githubusercontent.com/39329477/138893527-90256aa1-70c2-4ce5-9340-dab0cb216a5c.png">
<img width="696" alt="75fc279b3a9196c694d890359b01097" src="https://user-images.githubusercontent.com/39329477/138893562-ca1f0fc8-bbd4-44b2-a1a9-635f05e5759e.png">

**Comment by CalvinKirs** [comment]
Sounds good to me.

**Comment by EricJoy2048** [comment]
Good idea. 
Trino has done a good job in this respect, it is worth our study, and we look forward to someone can realize it.
