### ISSUE TITLE
[improvements][Performance] performance improvements 

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#6599]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

performance improvements
we have some target:
schedule work flow:  10000 / 10s
task delay:                  1000 tasks / 5s

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
I will close this issue due to longtime no update. Feel free to reopen it.
