### ISSUE TITLE
[Feature][Worker] Task waiting caused by incomplete pre dependency

### ISSUE THREAD

**Issue by shangeyao** [apache/dolphinscheduler#6604]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Now, due to the bottleneck of cluster resources, we set the number of master and worker processes to 35, and the number of three processes is 105, which just won't impact Hadoop. However, after running for a period of time, a large number of dependencies will fill the threads, but their pre dependencies don't start or finish executing, resulting in waiting.

### Use case

When I want to submit for execution, can I make the pre dependency unfinished workflow not enter the queue of 
the execution?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Yes, it will make some WorkflowExecuteThread exist in master which is waiting a worker's long task, and check state every 5s.
Maybe check state from DB and release current thread is better.  Anyone have good idea?

**Comment by codexun** [comment]
I suggest removing dependent tasks, because I really want to control the number of actually running tasks, but dependent tasks in running status occupy concurrency resources. After generating a task instance, the task instance is in the initial state first. At this time, the pre dependency of the task is checked regularly. If it is completed, the task state is changed to ready and queued into the executable queue. Use a separate service to check dependencies, not as a task!

**Comment by caishunfeng** [comment]
cc @lenboo @CalvinKirs

**Comment by zhongjiajie** [comment]
I think I am not get the point, did you mean that our worker processes full but no task going to run, because all tasks in worker processes can not be run due to pre dependency not satisfy?

**Comment by lenboo** [comment]
there have a status checking loop for dependent task, if the dependent tasks number is larger than master threads number, there would be lots of checking piled up. we can check it and make some improvements

**Comment by caishunfeng** [comment]
> there have a status checking loop for dependent task, if the dependent tasks number is larger than master threads number, there would be lots of checking piled up. we can check it and make some improvements

@shangeyao you can watch the dependent tasks number and check if there is same event in  WorkflowExecuteThread. If exist repeat event, that's the optimize point.

**Comment by zhongjiajie** [comment]
@caishunfeng Could we mock this situation in our local env in the further?

**Comment by shangeyao** [comment]
I found that the 2.0 version of the DS service has solved this problem.Thanks for your helping!

**Comment by zhongjiajie** [comment]
@lenboo @caishunfeng Does we solve this issue, or just we optimization other part which make DS could run more task than 1.3.x?

If it is the second situation, I think we still need to inspect and improve it

**Comment by caishunfeng** [comment]
> @lenboo @caishunfeng Does we solve this issue, or just we optimization other part which make DS could run more task than 1.3.x?
> 
> If it is the second situation, I think we still need to inspect and improve it

The problem is occur in 1.3.6, it already optimize by 2.0, which is use `StateWheelExecuteThread` to manage active tasks and check task state.

**Comment by zhongjiajie** [comment]
Great and thanks @caishunfeng
