### ISSUE TITLE
[Bug] [common] JSONUtils#getNodeString get a value of type string with quotes

### ISSUE THREAD

**Issue by ghost** [apache/dolphinscheduler#6606]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

in JSONUtils:
`
public static String getNodeString(String json, String nodeName) {
    try {
        JsonNode rootNode = objectMapper.readTree(json);
        return rootNode.has(nodeName) ? rootNode.get(nodeName).toString() : "";
    } catch (IOException e) {
        return "";
    }
}
`

If the field value is a string, the result will be quoted.

So far it's just "localParams" using this function,
I think, JsonNodeType judgment is missing from JSONUtils#getNodeString,
String type can consider using JsonNode#asText instead of JsonNode#toString.

### What you expected to happen

If this is a function that is likely to be widely used, maybe some changes are needed
### How to reproduce

HashMap<String, Object> map = new HashMap<>();
map.put("localParams", "123");
map.put("test", 123);

// {"test":123,"localParams":"123"}
String json = JSONUtils.toJsonString(map);

String localParams = JSONUtils.getNodeString(json, "localParams");
System.out.println(localParams);  //  "123"

System.out.println("123".equals(localParams));   // false

String localParams1 = objectMapper.readTree(json).get("localParams").asText();
System.out.println("123".equals(localParams1));  // true

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Yes, `objectMapper.readTree(json).get("localParams") ` will get the json string.
In this case, `"\"123\"".equals(localParams) ` will return true. this might cause problem in some case.

And I haven't seen this method has been used in project, so it might be better to remove this method. Are you interested in submit a pr?

**Comment by ghost** [comment]
this method is only used to get "localParams" or "dependence" from taskParams in TaskDefinition, the values of both fields are collections in the dev branch,so should i try modifying it instead of deleting it?
@ruanwenjun 
If you decide to modify or delete it, I would be happy to submit one pr.
