### ISSUE TITLE
[Bug] [Master] upgrade to 2.0.0-alpha error

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#6608]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```
[ERROR] 2021-10-27 11:02:06.120 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[46] - 查询各状态流程实例数错误
org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 't.process_definition_code' in 'on clause'
### The error may exist in class path resource [org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select t.state, count(0) as count         from t_ds_process_instance t         join t_ds_process_definition d on d.code=t.process_definition_code         join t_ds_project p on p.code=d.project_code         where 1 = 1         and t.is_sub_process = 0                       and t.start_time   >=   ? and t.start_time   <=   ?                                 and p.code in              (                   ?              )                    group by t.state
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 't.process_definition_code' in 'on clause'
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 't.process_definition_code' in 'on clause'
```

### What you expected to happen

no error

### How to reproduce

I got the following error when upgrade from 1.3.8 to 2.0.0-alpha using ./script/upgrade-dolphinscheduler.sh.

How can I solve this problem?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
@SbloodyS For now we do not have an out of box way to upgrade 1.3.x to 2.x, until issue https://github.com/apache/dolphinscheduler/issues/6597 close. Maybe you could track issue process, and we will close it and release DS 2.0 later

**Comment by zhongjiajie** [comment]
Maybe we should add `duplicate` label for this issue?

**Comment by SbloodyS** [comment]
Thanks.I will retry upgrade until issue  #6597 close.

**Comment by lenboo** [comment]
i will close it because of duplicate issue.
