### ISSUE TITLE
[Feature][SPI] Optimize the SPI mechanism to make it more convenient for users to extend the plug-in

### ISSUE THREAD

**Issue by CalvinKirs** [apache/dolphinscheduler#6612]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

At present, DolphinScheduler has customized a set of ClassLoader mechanism. This flexible mechanism can solve many problems, such as class conflicts and multi-version isolation. (These loaders are parallel and have no dependency relationship. A plug-in can use version 1.0 of a.jar, and plug-in B can use version 2.0 of a.jar, because of the fully qualified name of a class and the loading of the class The two loader together form the unique identification of this class in the JVM)

The flexible definition of the loading mechanism of the classloader allows us to do plug-in extension related work better and more assured, which is more suitable for task plug-ins such as complex plug-in development.

As for the registration center and alarm center, which are relatively independent and simple to rely on, we hope to provide a simpler way. Using Java's native SPI extension method, users do not need to do too many plug-in related configurations, including packaging configuration, plug-in directory configuration, etc. , Just implement the plug-in API (we can extract a layer of API, all plug-ins need to implement each interface of the API)
What do you think?

### Use case

no

### Related issues

no

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @CalvinKirs 
I'm a little confused about that is it going to be the same problem for the registration center and alarm center if we use Java native SPI, such as class conflicts and multi-version isolation?

**Comment by CalvinKirs** [comment]
> Hi @CalvinKirs I'm a little confused about that is it going to be the same problem for the registration center and alarm center if we use Java native SPI, such as class conflicts and multi-version isolation?

This kind of situation usually occurs in complex plugs-in, and it is mandatory to rely on two versions of the same jar. Such as our task module.

But for simple modules, this is controllable. I see that other projects do not have any major problems in the registry, but the alarm is actually simpler, nothing more than HTTP or other more complicated communication methods, but the dependence is usually stable.

What do you think?

**Comment by caishunfeng** [comment]
> > Hi @CalvinKirs I'm a little confused about that is it going to be the same problem for the registration center and alarm center if we use Java native SPI, such as class conflicts and multi-version isolation?
> 
> This kind of situation usually occurs in complex plugs-in, and it is mandatory to rely on two versions of the same jar. Such as our task module.
> 
> But for simple modules, this is controllable. I see that other projects do not have any major problems in the registry, but the alarm is actually simpler, nothing more than HTTP or other more complicated communication methods, but the dependence is usually stable.
> 
> What do you think?

I think it's OK, and is it easy to swith another SPI way if we want it?

**Comment by CalvinKirs** [comment]
> > > Hi @CalvinKirs I'm a little confused about that is it going to be the same problem for the registration center and alarm center if we use Java native SPI, such as class conflicts and multi-version isolation?
> > 
> > 
> > This kind of situation usually occurs in complex plugs-in, and it is mandatory to rely on two versions of the same jar. Such as our task module.
> > But for simple modules, this is controllable. I see that other projects do not have any major problems in the registry, but the alarm is actually simpler, nothing more than HTTP or other more complicated communication methods, but the dependence is usually stable.
> > What do you think?
> 
> I think it's OK, and is it easy to swith another SPI way if we want it?

Of course, this is just a modification of the plug-in loading method, and user extension plug-ins do not need to care.:)

**Comment by ruanwenjun** [comment]
This issue might be separate to three sub-task
- Add SPI extension loader
- Change registry plugin module use SPI extension loader
- Change alert plugin module use SPI extension loader
