### ISSUE TITLE
[Bug] [Master] A bug on task retry mechanism

### ISSUE THREAD

**Issue by yangqiyu0306** [apache/dolphinscheduler#6613]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

There are process nodes at the same level in the process, a failed error retry "node1_fail_retry" node (the actual task scenario may fail for the first time, and the task runs successfully after retry), and a failed "node2_fail" node; 

The current phenomenon is that after the "node2_fail" node fails, the process is in the failure state, and the "node1_fail_retry" node will not retry the task (the retry state may be successful) and the subsequent tasks will not run; 

Because the "node2_fail" node fails and the "errorTaskList" in the "MasterExecThread" is not empty, in the "processFailed()" method, "hasFailedTask()" returns true. When the FailureStrategy is CONTINUE, "activetasknode = 0", "processFailed()" returns false, causing the process instance state to change to failed.

![8](https://user-images.githubusercontent.com/39785282/139018718-881ecc96-010f-4e95-9844-2f75fa8cb4bb.png)

### What you expected to happen

I think it is wrong not to retry the process node at the same level if it fails, because the actual task scenario may fail for the first time, run successfully after retrying, and then continue to run the downstream node.

### How to reproduce

1. Create a new process
2. Create a process node relationship as shown in the figure. The node "node1_fail_retry" is set error retry. The node "node2_fail" fails directly. Nodes "node3", "node4" and "node5 "can be created arbitrarily
3. Online process and runprocess
![11](https://user-images.githubusercontent.com/39785282/139022256-6b54c0c7-948c-4319-bf1a-c072754ce912.png)
<img width="878" alt="22" src="https://user-images.githubusercontent.com/39785282/139022278-1eae4ae2-d935-429a-b861-3232733f73f1.png">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
which version?

**Comment by yangqiyu0306** [comment]
I use 1.2.1， but this logic is the same as other version

**Comment by zhongjiajie** [comment]
> which version?

I think we have to add version selection for our bug template.

**Comment by yangqiyu0306** [comment]
> > 哪个版本？
> 
> 我认为我们必须为我们的错误模板添加版本选择。



> which version?

I use 1.2.1， but this logic is the same as other version
