### ISSUE TITLE
[Feature][dolphinscheduler-api] Problems encountered by the second open

### ISSUE THREAD

**Issue by DylanMao1996** [apache/dolphinscheduler#6615]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1. User switchover failed to load environment variables
 For example, 
a）：Dolphin will run python tasks sudo -u root python xxx.py. Dolphin will not load Python if I configure Python environment variables on Linux and not dolphin_env. 
b）：The dolphin loading Python environment simply loads Python by default, but if python3 or something else, there will be problems and you need to copy and rename it to Python

2.Encapsulation of global exception modules
There are currently issues with exception encapsulation in the API. Some primary key collisions will be played directly in the console. Bad for troubleshooting

3.API issues
For example, 
a）：For some automated tasks. The current API returns null data and cannot concatenate each phase of the process.
b）：For update operations, if you need to return a long processDefinitionjson(the string of processDefinitionjson that was saved), it is recommended to split the processDefinition apart and update the values as the user changes them.

4.System application problems

a）：When the system is running without tasks, the memory footprint is significant.
b）：Master is under too much pressure and has too many tasks to do. Can we split the tasks

### Use case

We are currently considering moving Airflow to DolphinScheduler where we receive hundreds of millions of dispatchers per day. I am currently working on dolphin.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
@lenboo hi, Can you help look at this problem?

**Comment by caishunfeng** [comment]
Wow, it's a big issue with many different point. Should it split?

**Comment by lenboo** [comment]
There seems to be a lot to do. We'll consider it.

-   about the python path in environment variables, we can set the default python path to '/usr/bin/python', and you can use the function of environment configuration in version 2.0 to set environment config for different  workers. 

-  'There are currently issues with exception encapsulation in the API. Some primary key collisions will be played directly in the console. Bad for troubleshooting' 
We have optimized the API in version 2.0. Our purpose is to make it easier for users to use API calls. If you find some problems, submit  issues and let's fix them together

- b）：For update operations, if you need to return a long processDefinitionjson(the string of processDefinitionjson that was saved), it is recommended to split the processDefinition apart and update the values as the user changes them.
we have split the json in 2.0.0-alpha

- System application problems

a）：When the system is running without tasks, the memory footprint is significant.
b）：Master is under too much pressure and has too many tasks to do. Can we split the tasks

do you use the 1.3.x ？ you can try the 2.0.0-alpha, we make some improvements in the 2.0.

very appreciate you can submit these issues, it's useful for dolphinscheduler  ability improvement. 
Your follow-up feedback is welcome.

**Comment by DylanMao1996** [comment]
ok。thx
