### ISSUE TITLE
[Feature][unittest] Recover UT in AlertPluginManagerTest.java

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#6619]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In we merge PR https://github.com/apache/dolphinscheduler/pull/6182 by accident, in https://github.com/apache/dolphinscheduler/pull/6182#issuecomment-918220975 we know that we should make this unittest work instead of remove it, this issue aim to make unittest work again in `dolphinscheduler-alert/src/test/java/org/apache/dolphinscheduler/alert/plugin/AlertPluginManagerTest.java`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Please add label `good first issue` to this issue, thanks

**Comment by Linkaiup** [comment]
I want to take this issue.

**Comment by zhongjiajie** [comment]
Hi @Linkaiup Thanks for your feedback, and yeah for sure you could task it! looking forward your contribution.

**Comment by Linkaiup** [comment]
@zhongjiajie I had submit a PR,looking forward to your merge.

**Comment by zhongjiajie** [comment]
> @zhongjiajie I had submit a PR,looking forward to your merge.

@Linkaiup  So sorry that I have not permission to merge PR, but I mention someone who have to start CI and review the code

**Comment by EricGao888** [comment]
I just saw this when browsing issues labeled with `good first issue`. Seems this one is no more valid? https://github.com/apache/dolphinscheduler/pull/6674#issuecomment-973657840 Maybe we could close this issue?

**Comment by zhongjiajie** [comment]
> 

closed due to this
