### ISSUE TITLE
[Feature][community] Add version selection button for our bug template

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#6620]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I find out we do not have version selection bottom in our bug report template. It will save maintainer time to have version selection, unless their have to ask reporter, such as https://github.com/apache/dolphinscheduler/issues/6613#issuecomment-952944539

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Great! So we don't have to ask about the version anymore
