### ISSUE TITLE
[Bug] [process definition] workflow save error

### ISSUE THREAD

**Issue by mchcz** [apache/dolphinscheduler#6630]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### Dolphinscheduler version：2.0.0

1.use user A to create a workflow named test, there are two SQL nodes named step1 and Step2.

2.delete workflow test.

3.switch to user B and perform the same operation. An error is reported when saving the workflow, indicating that the node name already exists.

**java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'step1-828077078200320' for key 't_ds_task_definition.task_unique'**

4.query table t_ ds_ process_definition, there is no record in it, but the task definition table t_ds_task_definition,  there are records in it.

### What you expected to happen

It can be saved normally.

### How to reproduce

Reference “What happened”

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DingPengfei** [comment]
Can't reproduce this in my local env. Can you confirm this and provide more details ?

**Comment by SwltSs** [comment]
> 无法在我的本地环境中重现此内容。你能证实这一点并提供更多细节吗？

在同一个项目下新建一个工作流，流里的节点名称定义为task1，创建完流后把这个流删掉，再新建工作流，节点名称再次命名为task1，保存工作流时保存出错。就算流删除了，但是新建流时，节点名称还是不能用之前删除的流的节点名称，t_ds_task_definition表中的数据没有删除

**Comment by DingPengfei** [comment]
> > 无法在我的本地环境中重现此内容。你能证实这一点并提供更多细节吗？
> 
> 在同一个项目下新建一个工作流，流里的节点名称定义为task1，创建完流后把这个流删掉，再新建工作流，节点名称再次命名为task1，保存工作流时保存出错。就算流删除了，但是新建流时，节点名称还是不能用之前删除的流的节点名称，t_ds_task_definition表中的数据没有删除

The DDL has been updated. see #5875
