### ISSUE TITLE
[Bug] [server-zkmonitor] zkmonitor can't show for normal

### ISSUE THREAD

**Issue by linxin4wtl** [apache/dolphinscheduler#6655]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when i use the newst version(v2.0)，find a question as follow：
the zk monitor in the monitor center can not show

### What you expected to happen

zk monitor show list normal
![1](https://user-images.githubusercontent.com/33943960/139616985-d53c9920-ffc0-41d4-8f1a-0c9ad2e580ed.png)

### How to reproduce

1、 deploy  V2.0
2、start
3、open zk monitor

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Yes, I found it's a todo for registry-spi and the implement of `RegistryCenterUtils.zookeeperInfoList()`  is null.
Should it hide this menu if it is unimplemented?

**Comment by 981433814** [comment]
I am willing to submit a PR，please assign the task to me.

**Comment by zhuangchong** [comment]
@981433814 
OK, it has been assigned, please link this issue to submit a PR
