### ISSUE TITLE
[Improvement][Log]  optimize task log path to reduce task running time

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#6665]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

the task log path : 

**/logs/definition-code_definition_version/processInstanceId/taskInstanceId.log**

Every task would create a new directory at least.
It would cost too much if there are lots of task instances.

We can set the log path to 

**'/logs/YYYYMMDD/defintion-code_defintion_version-processInstanceId-taskInstanceId.log'**

to reduce the task running time.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by choucmei** [comment]
Can you assign this feature to me?

**Comment by lenboo** [comment]
> Can you assign this feature to me?

of course! @choucmei Looking forward to your code.

**Comment by caishunfeng** [comment]
https://github.com/apache/dolphinscheduler/discussions/6675
I found that getLogger may take more than 1s sometimes.
@choucmei @lenboo you can have a look, I  think it's related to this issue.

**Comment by choucmei** [comment]
> > Can you assign this feature to me?
> 
> of course! @choucmei Looking forward to your code.

thank you, this is a bit complicated,I need to look at this question again.

**Comment by choucmei** [comment]
> #6675
> I found that getLogger may take more than 1s sometimes.
> @choucmei @lenboo you can have a look, I think it's related to this issue.

thank you, this is a bit complicated,I need to look at this question again.
