### ISSUE TITLE
[DSIP-3][Performance Improvement] Performance improvement for ds 2.0

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#6666]
### Description
As we know, the performance optimization is a long-term challenge that needs to be done consistenly, and we hope DS is more stable and high performance.
So this is a parent issue to track and summarize the optimization issue for ds 2.0 performance.
If you have some performance test and suggestion for ds, welcome to comment it.
if you are interested in performance optimization, welcome to do it together.

### Functional

- Master
  - [x]  https://github.com/apache/dolphinscheduler/pull/6695
  - [x] https://github.com/apache/dolphinscheduler/issues/6849
  - [x] https://github.com/apache/dolphinscheduler/issues/6891
  - [x] https://github.com/apache/dolphinscheduler/issues/6963
- Worker
  - [X] https://github.com/apache/dolphinscheduler/issues/6616
  - [x] https://github.com/apache/dolphinscheduler/issues/6665
  - [ ] https://github.com/apache/dolphinscheduler/discussions/6675
- Zookeeper
  - [x] https://github.com/apache/dolphinscheduler/issues/6660
- DB
  - [X] https://github.com/apache/dolphinscheduler/issues/6483
- Netty
  - [X] https://github.com/apache/dolphinscheduler/issues/6653
- Performance Test
  - [ ] https://github.com/apache/dolphinscheduler/discussions/6678

**Comment by zhongjiajie** [comment]
@caishunfeng Please change title from `DSIP` to `DSIP-3` cause we already have two DSIP issue for now. cc: @CalvinKirs @lenboo could you please add labels `DSIP` to this issue?

**Comment by zhongjiajie** [comment]
Hi, @caishunfeng I thinks we should not only add some related PR/close issue for DSIP,  but also add what we do and what we latest idea to DSIP. Wanted who would interested on it, looking forward this DSIP 🎉

**Comment by caishunfeng** [comment]
> Hi, @caishunfeng I thinks we should not only add some related PR/close issue for DSIP, but also add what we do and what we latest idea to DSIP. Wanted who would interested on it, looking forward this DSIP tada

OK, I will add the latest plan to it.

**Comment by lenboo** [comment]
@caishunfeng  Thank you very much for your contribution. 
I created an issue about optimizing log path. 
I think it is also a part of performance optimization and can be associated with this issue
#6665 optimize task log path to reduce task running time

**Comment by caishunfeng** [comment]
> @caishunfeng Thank you very much for your contribution. I created an issue about optimizing log path. I think it is also a part of performance optimization and can be associated with this issue #6665 optimize task log path to reduce task running time

OK, added.
