### ISSUE TITLE
[Bug] [MasterServer] Run complete data at same schedule time without end

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#6671]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

version: 2.0-alpha
When I run with complete data model, I found some process is always running, with same name、schedule time、command_start_time, but different id、start_time、end_time. 

![bfb1b8610930af8995e9be5cac82432](https://user-images.githubusercontent.com/11962619/139876654-e74bcf35-eef0-45f7-94ad-1272498582fc.png)
![7e87da70c47406f7cd2abed07953488](https://user-images.githubusercontent.com/11962619/139876700-c62d58b1-100d-4ca6-98b3-7b7366b43b84.png)
![af052d4d70da5f7231d49cdf4a8d6af](https://user-images.githubusercontent.com/11962619/139876828-948c27ea-896f-4bbc-9873-fb1d469972cd.png)
![b14a75e7431d9a2faf2e9322d8f5cdb](https://user-images.githubusercontent.com/11962619/139876897-377eb3fd-d598-4489-9e90-fb84c1da6b02.png)

### What you expected to happen

Complete data normally.

### How to reproduce

It seems occasional.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DingPengfei** [comment]
Can't reproduce your issue. ?Could you please provide more details about this?

**Comment by caishunfeng** [comment]
> Can't reproduce your issue. ?Could you please provide more details about this?

Yes, it seems occasional. Just 60 completment process instances like that, and other more than 1000 process instances is normal. I was strange too.
Sorry about that I had clean up the logs and data because the less disk.
