### ISSUE TITLE
[Feature][Server] Discard ZooKeeper using raft

### ISSUE THREAD

**Issue by DylanMao1996** [apache/dolphinscheduler#6680]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1.Dolphinscheduler is too heavy to have a ZooKeeper external. For lighter use and easier deployment, is it possible to do something like Kafka? Ditching ZooKeeper and using raft protocol for lighter weight?

2.The DolphinScheduler metadata store is now PG and mysql. Both require external installation. Can you integrate with Rocksdb? It has a rocksdb embedded in it. Data is stored in the HDFS to ensure metadata security (HDFS multi-version replication).

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Good idea. Can you provide some specific design for `using raft replace zk`?

**Comment by DylanMao1996** [comment]
Dolphinscheduler currently has distributed locks removed, allowing multiple masters to process them in parallel, but intermediate operations still involve locks. Is there a way to leverage raft's idea? The State event event is listened for as long as the command is generated and then thrown to the master thread pool for distribution.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月4日(星期四) 下午4:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/dolphinscheduler] [Feature][Server] Discard ZooKeeper using raft (Issue #6680)





 
Good idea. Can you provide some specific design for using raft replace zk?
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caishunfeng** [comment]
> Dolphinscheduler currently has distributed locks removed, allowing multiple masters to process them in parallel, but intermediate operations still involve locks. Is there a way to leverage raft's idea? The State event event is listened for as long as the command is generated and then thrown to the master thread pool for distribution.

I think this is just a part of schedule optimization,  but the main function of zk is registry center.

**Comment by DylanMao1996** [comment]
If it is just the same as the registry, I can understand that zK's Watch is used. Can it be like Kafka? What about Controller Quorum? You can cancel ZK and add a DolphinScheduler JPS process.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月4日(星期四) 下午4:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] [Feature][Server] Discard ZooKeeper using raft (Issue #6680)





  
Dolphinscheduler currently has distributed locks removed, allowing multiple masters to process them in parallel, but intermediate operations still involve locks. Is there a way to leverage raft's idea? The State event event is listened for as long as the command is generated and then thrown to the master thread pool for distribution.
  
I think this is just a part of schedule optimization,  but the main function of zk is registry center.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
