### ISSUE TITLE
[Bug] [UI/Master] The task of dependent should use taskCode 

### ISSUE THREAD

**Issue by brave-lee** [apache/dolphinscheduler#6682]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The task of dependent is using taskName, duplicate names can lead to dependency errors. 

### What you expected to happen

Please use taskCode to replace taskName.

### How to reproduce

![image](https://user-images.githubusercontent.com/42576980/140069440-dc8c293e-9e02-4c71-8cee-8d79ff27f21c.png)

![image](https://user-images.githubusercontent.com/42576980/140069580-6315dbc0-5761-43bc-ae6f-88fab6a98043.png)

![image](https://user-images.githubusercontent.com/42576980/140069677-dbcb1837-1776-4bde-a16e-39da985a7914.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DingPengfei** [comment]
You can't input a node name that alread exists in the same process.

**Comment by brave-lee** [comment]
> You can't input a node name that alread exists in the same process.

I will fix it, that should be allowed.

**Comment by DingPengfei** [comment]
> > You can't input a node name that alread exists in the same process.
> 
> I will fix it, that should be allowed.

Same node names in one process may bring misunderstandings, I think you should be careful about adding this

**Comment by wangyizhi1** [comment]
@lenboo @JinyLeeChina 
In addition to the DEPENDENT task, the CONDITIONS and SWITCH tasks also had this problem. I fixed the UI part(#6719):

![image](https://user-images.githubusercontent.com/87303815/140616569-98b7a041-9724-4ce2-97f0-7485afc9a747.png)

![image](https://user-images.githubusercontent.com/87303815/140616578-a3d7bb4b-753e-49fb-8357-ca54344cb994.png)

![image](https://user-images.githubusercontent.com/87303815/140616584-829e743a-9d53-457b-bbf0-258de35ad937.png)

**Comment by lenboo** [comment]
> @lenboo @JinyLeeChina In addition to the DEPENDENT task, the CONDITIONS and SWITCH tasks also had this problem. I fixed the UI part(#6719):
> 
> ![image](https://user-images.githubusercontent.com/87303815/140616569-98b7a041-9724-4ce2-97f0-7485afc9a747.png)
> 
> ![image](https://user-images.githubusercontent.com/87303815/140616578-a3d7bb4b-753e-49fb-8357-ca54344cb994.png)
> 
> ![image](https://user-images.githubusercontent.com/87303815/140616584-829e743a-9d53-457b-bbf0-258de35ad937.png)

well done! i  will test it.
