### ISSUE TITLE
[Feature][log] clean up task logs

### ISSUE THREAD

**Issue by sw2011** [apache/dolphinscheduler#6686]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The ds cluster started 20 timed tasks and executed an sql statement every 2 seconds, but the task failed after 1 day with error: java.sql.SQLException: Error writing file'/tmp/MLObcxS3' (errno: 28-No space left on device). At the same time, it is found that opt/dolphinscheduler/logs has more than ten gigabytes of files in the background.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @sw2011 , is it better to use shell clean up logs order by file's update date? Because DS doesn't know which log file should be clean up actually.
BTW, you can put the check shell task into DS.
