### ISSUE TITLE
The master does not send task to the worker

### ISSUE THREAD

**Issue by mhsccd** [apache/dolphinscheduler#6692]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I wrote a work process that was timed to execute and there are some tasks there. I run the process，but I found that my work process was running without tasks being executed.The tasks that are not executed are simply submitted to the master.So I restarted the master,The previous work process is still in the wait state, while the subsequent work  process has completed execution.I can only end these waiting work process, otherwise they will be waiting forever.I guess you have a problem with the queue that receives tasks on your master and The master also fails to deliver tasks to workers.

### What you expected to happen

The master can receive and deliver tasks to the workers.

### How to reproduce

You can write a timed work process and there are tasks in the work process.Keep the timer time short and The master has small resources.Execute this work process regularly and you can see my phenomenon.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi, @mhsccd , which version you use? Is the worker run normally? And can you get any log for this task in the worker?

**Comment by mhsccd** [comment]
dolphinScheduler version:1.3.6
zookeeper version:3.4.x

**Comment by mhsccd** [comment]
After the workers and master are restarted, the previous logs cannot be retrieved

**Comment by mhsccd** [comment]
After the workers and master are restarted, the previous logs cannot be retrieved

**Comment by Bulls1986** [comment]
This seems to be a logical hole
