### ISSUE TITLE
[Bug] [master-server] the dispatch Priority of taskInstance is inoperative

### ISSUE THREAD

**Issue by wangxj3** [apache/dolphinscheduler#6711]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The function of dispatch only consider the Priority of processInstance ，and the second Priority of processInstance should change to the  Priority of taskInstance。

### What you expected to happen

when the master dispatch the taskInstance ，this error will make taskInstance inoperative

### How to reproduce

change the third param of TaskPriority to taskInstancePriority

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
@wangxj3 I think this feature have been implemented in the 2.x
