### ISSUE TITLE
[Feature][StandaloneServer] Ensure that the Standalone Server restarts using the same data file

### ISSUE THREAD

**Issue by echohlne** [apache/dolphinscheduler#6713]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Standalone Server is a great idea, but is has two problems can be imporved: 
+ Each time when you start a StandaloneServer, a random temporary directory would be created, which actually has no meaning
llike below, standaloneserver create a directory： dolphinscheduler_1109196593964124306, but the db data file: dolphinscheduler_11091965939641243069.mv.db was not in directory dolphinscheduler_1109196593964124306 
```shell
16:51:05.054 [Standalone-Server] INFO org.apache.dolphinscheduler.server.StandaloneServer - H2 database directory: C:\Users\echoh\AppData\Local\Temp\dolphinscheduler_11091965939641243069
```
![image](https://user-images.githubusercontent.com/52202080/140603926-881c279c-f682-4564-b876-64352b63cbc1.png)
+ After each time restart, it would import the init-sql script again. As a result, the previously configured data would be loss.
![image](https://user-images.githubusercontent.com/52202080/140604005-95758f15-1663-4757-9bba-b7de193622e5.png)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
I did intentionally do this when I add the standalone server because I want to start a brand new database when restarting the development.

**Comment by kezhenxu94** [comment]
H2 is memory database and the reason why I have to store the data file on disk is that I have to start it in daemon mode, which is not allowed in our current codes. If you want to reuse the data, you'd better use a local MySQL / PostgreSQL database.

**Comment by kezhenxu94** [comment]
When we can avoid storing data on disk, we will start H2 in memory mode so this is intended.

**Comment by echohlne** [comment]
as discussed in #6697 
I would try to use the traditional way to continue my work.
This issue  would be closed.
