### ISSUE TITLE
[Improvement][Schedule] set timing schedule when save process definition

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#6715]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

at 1.3.x version, we set process definition timing schedule   :
1.  save process definition
2.  set process online
3.  add timing of process definition
4. set timing schedule status to online

To simplify operation， we can set the timing schedule  (include online/offline) on the process definition save page. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by linyanbin666** [comment]
I can contribute it, please assign to me

**Comment by brave-lee** [comment]
The dev version already has this feature, but we will not add new feature in 2.0.7, please note that
