### ISSUE TITLE
[Feature][Install-sql]  supplement Postgre procedure sql file  

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#6716]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

relate to this issue #6597 (Upgrade dolphinscheduler version 1. X to version 2.0)

we have added the mysql procedure in pr(#6648 ),  we also need a postgre procedure sql in upgrading process.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GaoTianDuo** [comment]
I will try to do it。

**Comment by lenboo** [comment]
> I will try to do it。

very good ! i will assign it to you.

**Comment by brave-lee** [comment]
The current upgrade program has passed the MySQL test and is OK. You can sort out PG DDL according to MySQL DDL.
![image](https://user-images.githubusercontent.com/42576980/140679582-14d41f30-d039-4260-9682-a106d953446f.png)

**Comment by GaoTianDuo** [comment]
Has been done！，please review！ @lenboo @JinyLeeChina
