### ISSUE TITLE
docker-compose dolphinscheduler/2.0.0-SNAPSHOT  erro

### ISSUE THREAD

**Issue by yang227** [apache/dolphinscheduler#6720]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When using docker compose to install the 2.0 source code provided on the official website, the image file cannot be found

### What you expected to happen

The image not found error occurs because image is Apache / Dolphin scheduler: 2.0.0-snapshot in docker-compose.yml and docker-stack.yml_ hub image is apache/dolphinscheduler:2.0.0-alpha

### How to reproduce

When using docker compose to install the 2.0 source code provided on the official website, the image file cannot be found

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
it can be used now.
