### ISSUE TITLE
[issue][dolphinscheduler-common] When three nodes yarnhaips are configured, but the active node port is 8080standby node 8088, an error will be returned, when three nodes yarnhaips are configured but the active node port is 8080standby node 8088 mistake

### ISSUE THREAD

**Issue by gmstudy** [apache/dolphinscheduler#6735]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Hello, I want to feed back the usage. The yarnhaips I configured are ha three nodes,

The resourcemanagerhttpaddressport is configured with port 8080,

The active node port of the company cluster is 8080, but the standby node is 8088,

I can only configure one port number when I use http://yarnIp1:%s/ws/v1/cluster/apps/%s time

If the requested node is a standby node, the function httputils.get (URL) returns a null string,

It will directly lead to the success of the task call, but the task status in DS will return failure,

Is this reasonable?

Should we loop through yarnhaips in all three until the correct node address and port number are returned

你好，我想反馈个使用情况，我配置的yarnHaIps 是ha 三个节点，
resourceManagerHttpAddressPort 配置的是8080端口，
公司集群的active节点端口是8080，但是standby的节点是8088，
我只能配置一个端口号，当我用http://yarnIp1:%s/ws/v1/cluster/apps/%s时候
如果请求的是个standby的节点，函数HttpUtils.get(url) 返回的是null字符串，
会直接导致任务调用成功，但是ds里任务状态会返回失败，
这个情况是否合理呢？
是不是应该当循环遍历yarnHaIps在三个都遍历完直到返回正确的节点地址和端口号的地址

### Use case

通过配置的yarnHaIps节点数量一直循环到配置的节点返回正确结果
Cycle through the number of configured yarnhaips nodes until the configured nodes return the correct results

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Yao-MR-zz** [comment]
@bjzhougm why not config the url of nameservice rather than the detail url
