### ISSUE TITLE
[Bug] [dolphinscheduler-registry-zookeeper]  Can't modify zookeeper znode

### ISSUE THREAD

**Issue by 981433814** [apache/dolphinscheduler#6736]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I want to run DS 1.3.x and DS 2.0.0 in parallel

I modified install_config.conf  , but it didn't work

zkRoot="/dolphinschedulerNew"

It seems the code is hard-coded

NAME_SPACE("namespace", "dolphinscheduler", value -> value),

### What you expected to happen

Zookeeper ZNode can be configured

### How to reproduce

vi /opt/soft/dolphinscheduler/conf/config/install_config.conf

zkRoot="/dolphinschedulerNew"

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
In 2.0, you need to configure registry.namespace=XXXXX

**Comment by 981433814** [comment]
> In 2.0, you need to configure registry.namespace=XXXXX

Thank you~,I've taken care of it

**Comment by 981433814** [comment]
> In 2.0, you need to configure registry.namespace=XXXXX

Thank you~,I've taken care of it
