### ISSUE TITLE
[Bug] [ProcessDefinition] delete a process definition without deleting task definitions in it

### ISSUE THREAD

**Issue by jon-qj** [apache/dolphinscheduler#6748]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

branch:2.0.0-alpha
when I delete a process definition, I find that task definitions are not deleted.

### What you expected to happen

delete task definitions

### How to reproduce

you can try to delete a process definition and have a look.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
@jon-qj  It this similar to to https://github.com/apache/dolphinscheduler/issues/6418

**Comment by jon-qj** [comment]
> @jon-qj It this similar to to #6418

Get it.

**Comment by jon-qj** [comment]
It this similar to to #6418

**Comment by zhongjiajie** [comment]
> It this similar to to #6418

@jon-qj  Please keep this issue open, cause I am not really sure is this except behavior or not. Did you have time to take a look? @lenboo @JinyLeeChina

**Comment by lenboo** [comment]
We support use task definitions by reference(eg: one task can be referenced by multiple workflows), so some tasks cannot be deleted when delete process definition.
We will add a task list display later to allow users to delete task definitions.

**Comment by zhongjiajie** [comment]
Thanks Liang, cc: @jon-qj
