### ISSUE TITLE
[Bug] [Dao] The format of dependent tasks is task name

### ISSUE THREAD

**Issue by shangeyao** [apache/dolphinscheduler#6760]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Now I set up a definition of process below.
![image](https://user-images.githubusercontent.com/42203474/140896474-b07f8ef1-1a38-4d38-b071-054bd48b14ae.png)
![image](https://user-images.githubusercontent.com/42203474/140896534-ac52af07-91df-4d91-abca-1d8254ee3f24.png)
Then I found that the data store by the column **task_params** (json format) below into the table **t_ds_task_definition**.
{
   "relation": "AND",
   "dependItemList": [{
    "depTasks": "job_a",
    "cycle": "day",
    "dateValue": "today",
    "projectCode": 851275532173312,
    "definitionCode": 851275583815680
}
When I change the name of task definition such as job_a into job_b, then column **task_params** remain the same.
It may cause a error about dependent task.
Maybe we can use code instead of name.

### What you expected to happen

Above.

### How to reproduce

Above.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
This issue is the same as  #6682
