### ISSUE TITLE
[Improvements][API] Remove the detection of duplicate task names

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#6763]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Remove the detection of duplicate task names
we have changed the primary key from task name to task code,  the duplicate task name check can be removed in API.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
I can contribute it
