### ISSUE TITLE
[Bug] [API] queryAllProjectList response userName is null

### ISSUE THREAD

**Issue by hong7980** [apache/dolphinscheduler#6766]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

api ：queryAllProjectList response userName is null
![image](https://user-images.githubusercontent.com/57578320/140950148-757e3aca-b01b-4915-847e-9567b8debec2.png)

The API interface with the same condition has 
“queryAuthorizedProject”
“queryProjectCreatedAndAuthorizedByUser”
“queryUnauthorizedProject” 

### What you expected to happen

The response return from api with correct userName
![image](https://user-images.githubusercontent.com/57578320/140951922-5be0d136-1483-4b21-8630-57817202cbc7.png)

### How to reproduce

use the api to query project ：“queryAllProjectList",“queryAuthorizedProject”,“queryProjectCreatedAndAuthorizedByUser”,“queryUnauthorizedProject” 

### Anything else

Version：2.0.0-alpha-release

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
@hong7980 
Are you willing to fix this issue?

**Comment by hong7980** [comment]
> @hong7980 Are you willing to fix this issue?

Thanks for the invitation, I'm afraid I can't fix it because I didn't use Java development.

**Comment by yang100455** [comment]
> > @hong7980 Are you willing to fix this issue?
> 
> Thanks for the invitation, I'm afraid I can't fix it because I didn't use Java development.

I'd like to fix the problem,Can I try it on？

**Comment by xianweiY** [comment]
> @hong7980 Are you willing to fix this issue?

I'd like to fix the problem,Can I try it on？

**Comment by zhuangchong** [comment]
@yang100455 
ok, I will assign the task to you.

**Comment by yang100455** [comment]
> @yang100455 好的，我会把任务分配给你。

I have located the problem, but based on my observations, these interface usage scenarios do not need to use these values, and these values  just have a default value,not a real value, should I cancel these returns? Or do you assign real values to these variable queries?

**Comment by xianweiY** [comment]
> @yang100455 好的，我可能有任务给你。

I have located the problem, but based on my observations, these interface usage scenarios do not need to use these values, and these values  just have a default value,not a real value, should I cancel these returns? Or should I assign real values to these variable queries?

![image](https://user-images.githubusercontent.com/43943331/141231517-70477244-dc68-427d-9350-ba3e47a48a1c.png)

**Comment by xianweiY** [comment]
![image](https://user-images.githubusercontent.com/43943331/141231662-9a14b3e7-b52d-4824-bf14-f2e37b9156cf.png)

**Comment by yang100455** [comment]
> @yang100455 ok, I will assign the task to you.
i have create a PR for this issue, In the end I chose to assign real value to fields rather than delete the field

https://github.com/apache/dolphinscheduler/pull/6794

**Comment by xianweiY** [comment]
Sorry, this is my first time to submit the code, because some rules are not clear and the unit test did not pass,  so there are some invalid PRs, but i has been closed them,the last is valid.

**Comment by EricGao888** [comment]
Seems that this issue has been one year. Need to verify whether this bug still exists. If not, I will close it. Thanks : )
