### ISSUE TITLE
[Bug] [dolphinscheduler-dao] a small mistake about ResourceDao

### ISSUE THREAD

**Issue by dajianguo** [apache/dolphinscheduler#6770]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

org.apache.dolphinscheduler.dao.upgrade.ResourceDao
line34
public static final Logger logger = LoggerFactory.getLogger(ProcessDefinitionDao.class);

I think the "ProcessDefinitionDao.class"   should be "ResourceDao.class" ，It's a small mistake.

### What you expected to happen

Log information error

### How to reproduce

I think the "ProcessDefinitionDao.class"   should be "ResourceDao.class" ，It's a small mistake.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dajianguo** [comment]
The vertion is release-1.3.9

**Comment by lenboo** [comment]
@dajianguo 
very good! It is a bug.
I will create a branch 1.3.10.
Would you please submit a pr to fix it on branch 1.3.10?

**Comment by tracehh** [comment]
The same error in 2.0.1 version. I want to fix it. How about? @lenboo

**Comment by lenboo** [comment]
> The same error in 2.0.1 version. I want to fix it. How about? @lenboo
@tracehh 
Good work! Looking forward to your contribution!  You can submit pr to dev branch.

**Comment by tracehh** [comment]
dev branch had fixed it.

**Comment by tracehh** [comment]
You can close this issue. @lenboo
