### ISSUE TITLE
[Improvement][API] API operation optimization

### ISSUE THREAD

**Issue by brave-lee** [apache/dolphinscheduler#6772]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Dag API
1. Create offline workflows and schedules 
2. Update workflow basic information
3. Update schedule information by process definition code
4. Online or offline workflow and schedule at the same time
5. Delete the workflow and schedule at the same time
6. Online is not allowed for empty workflow
### Task API
1. Specify the online or offline status when creating  tasks
2. Online or downstream dependent tasks will not be deleted
3. Task online and offline interface
### Relation API
1. Add task to workflow
2. Remove task from workflow
3. Task moves from A workflow to B workflow
4. Task delete upstream dependency
5. Task add upstream dependency
### Execution API
1. Specify task execution interface
![image](https://user-images.githubusercontent.com/42576980/141075049-faa6c4f8-9a0a-42f3-9924-0aa4f426f6a4.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Good job! I thinks this is a huge change, and we should add label `DSIP` on it, WDYT?

**Comment by caishunfeng** [comment]
Can you add the background explanation of why to do that?

**Comment by zhongjiajie** [comment]
> Create offline workflows and schedules

Sometime we only need to create workflow without schedule, do you think we should support it or not? I thinks the schedule just an additions informations to workflow, mean that url would look like `/workflow/<workflow_code>/schedule`

> Task delete upstream dependency
Task add upstream dependency

should we also add downstream for tasks? Oh, I see that in 

> Online or downstream dependent tasks will not be deleted

why should we delete downstream tasks?

**Comment by brave-lee** [comment]
>> Create offline workflows and schedules
>
>Sometime we only need to create workflow without schedule, do you think we should support it or not? I thinks the schedule just an additions informations to workflow, mean that url would look like `/workflow/<workflow_code>/schedule`

It create a empty offline workeflow.  I think one dag should have schedule.

>>Task delete upstream dependency
>> Task add upstream dependency
>
>should we also add downstream for tasks? Oh, I see that in
>
>> Online or downstream dependent tasks will not be deleted
> 
>why should we delete downstream tasks?

You're right, here we can support add/delete downstream tasks

**Comment by JinyLeeChina** [comment]
> > > > Create offline workflows and schedules
> > > 
> > > 
> > > Sometime we only need to create workflow without schedule, do you think we should support it or not? I thinks the schedule just an additions informations to workflow, mean that url would look like `/workflow/<workflow_code>/schedule`
> 
> It create a empty offline workeflow. I think one dag should have schedule.
> 
> > > > Task delete upstream dependency
> > > > Task add upstream dependency
> > > 
> > > 
> > > should we also add downstream for tasks? Oh, I see that in
> > > > Online or downstream dependent tasks will not be deleted
> > > 
> > > 
> > > why should we delete downstream tasks?
> 
> You're right, here we can support add/delete downstream tasks

**Comment by brave-lee** [comment]
num | Interface | Interface method | Operate | Function description
-- | -- | -- | -- | -- 
 1 | ProcessDefinition | createEmptyProcessDefinition | new | Create offline empty workflow and schedule at the same time. When schedulejson is empty, only empty work will be created
2 | ProcessDefinition | updateProcessDefinitionBasicInfo | new | Modify the basic information of workflow and schedule. When schedulejson is empty, only the basic information of workflow can be modified, or the online status can be specified. An empty workflow is not allowed to go online 
3 | ProcessDefinition | releaseWorkflowAndSchedule | new | At the same time, online and offline workflows and scheduled workflows are not allowed. Empty workflows are not allowed to go online
4 | ProcessDefinition | deleteWorkflowAndSchedule | new | Workflow and timing can be deleted at the same time. Only offline workflow and timing can be deleted
5 | ProcessDefinition | deleteProcessDefinitionVersion | new | The workflow of the main table version is not allowed to be deleted.
6 | TaskDefinition | releaseTaskDefinition | new | The online and offline tasks correspond to the flag field. When online, there is a resource dependency to judge whether the resource is available.
7 | TaskDefinition | deleteTaskDefinitionVersion | update | The task of master table version cannot be deleted
8 | ProcessTaskRelation | createProcessTaskRelation | new | Adding tasks to workflow, adding upstream dependencies, and adding downstream dependencies
 9 | ProcessTaskRelation | moveTaskProcessRelation | new | The task switches the workflow, and judges that the dependency and subprocess cannot be added to their own workflow
10 | ProcessTaskRelation | deleteTaskProcessRelation | new | Tasks are removed from the workflow and deleted directly when tasks are dependence, subProcess and conditions.
11 | ProcessTaskRelation | deleteUpstreamRelation | new | Task delete upstream dependency
12 | ProcessTaskRelation | deleteDownstreamRelation | new | Task delete downstream dependency
13 | ProcessTaskRelation | queryUpstreamRelation | new | Task query upstream dependency
14 | ProcessTaskRelation | queryDownstreamRelation | new | Task query downstream dependency
15 | Schedule | updateScheduleByProcessDefinitionCode | new | Modify schedule according to workflow code
16 | Schedule | online | update | Empty workflow is not allowed to go online.

**Comment by yikeshiguang** [comment]
I'll complete the releaseTaskDefinition interface!

**Comment by edward-yang** [comment]
I will implement interface "createEmptyProcessDefinition" and "updateProcessDefinitionBasicInfo"

**Comment by zhanqian0609** [comment]
I'll complete the “deleteProcessDefinitionVersion”(num 5)

**Comment by brave-lee** [comment]
fix swagger view at #6933

**Comment by yikeshiguang** [comment]
收到。
