### ISSUE TITLE
[Bug] [dolphinscheduler-api]  "cannot deserialize from Object value" because org/apache/dolphinscheduler/api/utils/PageInfo.java has no default constructor

### ISSUE THREAD

**Issue by zwZjut** [apache/dolphinscheduler#6779]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

json string to Result<PageInfo<TaskDefinitionLog>>  using  org.apache.dolphinscheduler.common.utils.JSONUtils.parseObject(jsonStr,clazz); 

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.apache.dolphinscheduler.api.utils.PageInfo` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)

### What you expected to happen

add this to  PageInfo.java

 public PageInfo() {

 }

will solve this problem

### How to reproduce

json string to Result<PageInfo<TaskDefinitionLog>>  using  org.apache.dolphinscheduler.common.utils.JSONUtils.parseObject(jsonStr,clazz); 

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.apache.dolphinscheduler.api.utils.PageInfo` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
done.
