### ISSUE TITLE
[Feature] SQL Task should also support Cancel operation

### ISSUE THREAD

**Issue by Baoqi** [apache/dolphinscheduler#679]
**Is your feature request related to a problem? Please describe.**
In current implementation, only sub-process like Task  (MR, Shell, Python, etc.) support Cancel (by sending  'kill -9 process_id' to kill child process). 

But, for JDBC (SQL) Tasks,  some SQL can be very timeconsuming, we can also implement the Cancel support to cancel mis-written SQL to reduce warehouse database workload), we can call Statement:Cancel to cancel running statement for most DBMS, we can also stop fetch more if it already comes to Fetch ResultSet stage. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by boandai** [comment]
@Baoqi ，could you implement this feature？

**Comment by fgdsfgfdsgdsfgsdfg** [comment]
can we use the method to cancel Statement like this 
`
public static void cancel(String id) throws SQLException {
        Statement statement = ID_STATEMENT.get(id);
        // 若查询正在执行，调用 cancel() 方法进行取消
        if (statement != null) {
            statement.cancel();
        }
    }

    public static void add(String id, Statement statement) {
        ID_STATEMENT.put(id, statement);
    }

    public static void remove(String id) {
        ID_STATEMENT.remove(id);
    }
`

**Comment by fgdsfgfdsgdsfgsdfg** [comment]
Hello，我在使用2.x版本的dolphinscheduler，我发现了SQL task不支持cancel没有实现，我想请问一下，是否可以通过缓存Statement对象，然后在cancel的时候通过调用Statement的cancel方法来取消SQL？类似于下面这种
```
private static final Map<String, Statement> ID_STATEMENT = new HashMap<>();

    public static void cancel(String id) throws SQLException {
        Statement statement = ID_STATEMENT.get(id);
        // 若查询正在执行，调用 cancel() 方法进行取消
        if (statement != null&&!statement.isCloseOnCompletion()) {
            statement.cancel();
        }
    }

    public static void add(String id, Statement statement) {
        ID_STATEMENT.put(id, statement);
    }

    public static void remove(String id) {
        ID_STATEMENT.remove(id);
    }
```
