### ISSUE TITLE
[Bug] [ProcessDefinition] set TaskTimeoutStrategy parameter‘s value and an error occurred

### ISSUE THREAD

**Issue by jon-qj** [apache/dolphinscheduler#6790]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

branch: 2.0.0-alpha
when I set TaskTimeoutStrategy parameter‘s value, and its value is missing.

### What you expected to happen

as we know

### How to reproduce

1、create a task node
2、set TaskTimeoutStrategy
![image](https://user-images.githubusercontent.com/39773194/141243321-f0970e88-8cb6-4e4d-a644-4deadada2ff7.png)
3、TaskTimeoutStrategy parameter in frond-end
![image](https://user-images.githubusercontent.com/39773194/141243432-ea7cb0ad-0772-4ee1-8eb0-b914cd84b445.png)
4、TaskTimeoutStrategy parameter in back-end
![image](https://user-images.githubusercontent.com/39773194/141243535-1df9a66f-ec61-4f1f-9342-0fd2909910c8.png)
5、show this task config and data in db
![image](https://user-images.githubusercontent.com/39773194/141243654-0cf6ef7b-d207-462f-92fe-d2f73eb75384.png)
![image](https://user-images.githubusercontent.com/39773194/141243827-a5ab4cef-374b-4b3e-836f-a7388ce050dd.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
This issue has been fixed #7107
