### ISSUE TITLE
[Bug] [readme] Error link to Docker and k8s in readme 

### ISSUE THREAD

**Issue by debrachena** [apache/dolphinscheduler#6802]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Error link to Docker and k8s in readme 

### What you expected to happen

Change the right link in readme

### How to reproduce

Error link to Docker and k8s in readme 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GaoTianDuo** [comment]
I will try!
