### ISSUE TITLE
[Feature][DAG] Generate DAG workflow by sql file

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#6817]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

 There is a complete blood lineage in the SQL statement. 
We can automatically build DAG workflow through blood relationship

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
@lenboo  Does it same as https://github.com/apache/dolphinscheduler/issues/7016?

**Comment by zhongjiajie** [comment]
Same as #7016 close.
