### ISSUE TITLE
[Feature][Master] master donot failover the yarn task

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#6818]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The yarn task would run on remote cluster,  so it's not necessary to failover the yarn task when worker down.
If worker down,  other worker can continue to monitor the status of yarn task, but not kill yarn and rerun it.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Lucaszlei** [comment]
I will complete this issue，please assign to me
