### ISSUE TITLE
[Feature][API] Duplicate names of project, resource and data source are allowed

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#6819]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Duplicate names of project, resource and data source are allowed.

### Use case

User A add a resource a1, User B add a resource b1, 
the a1 name can be the same with b1.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Lucaszlei** [comment]
@lenboo I can complete this issue, please assign to me

**Comment by zhongjiajie** [comment]
@SunnyZ-L  I assigned to you, looking forward your contribution.
