### ISSUE TITLE
[BUG] The shared project does not indicate the workflow running account(共享项目未标明工作流运行账户)

### ISSUE THREAD

**Issue by chinashenkai** [apache/dolphinscheduler#682]
The shared project does not indicate the workflow running account

---
对于多账户共享的项目未标明工作流运行的用户

**Comment by chinashenkai** [comment]
可以对于每个实例注明运行账户, 利于审计
而且对于运行实例 以及工作流 希望可以在admin处,留下记录
将删除功能修改为 30天后删除,但是对与普通用户立即隐藏, 对于admin 可见. 防止误删.

**Comment by Eights-Li** [comment]
the executor name for process instance have complete in dev
