### ISSUE TITLE
[Feature][API] Ordinary users can also share resource data source projects with others

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#6820]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Ordinary users can also share resource data source projects with others

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Lucaszlei** [comment]
@lenboo I can complete the backend interface for this problem, please assign to me

**Comment by zhongjiajie** [comment]
@SunnyZ-L  I assigned to you, looking forward your contribution.

**Comment by Lucaszlei** [comment]
@zhongjiajie @lenboo Encountered a problem during the modification process：
case:
When user A authorizes resource file a to user B, is user B allowed to authorize file a to user C?

My suggestion is to not allow user B to re-authorize the files authorized by user A, authorization only allows first-level authorization.
What is your opinion?

---
我的建议是不允许用户B将用户A授权的文件再次进行授权，授权只允许一级授权。否则会产生额外的问题，如循环授权，多层级授权导致文件不可控等

**Comment by zhuangchong** [comment]
@SunnyZ-L 
I think your idea is ok, you need to consider the authorized person's operation permission, can have the update permission, can have the view permission. 
In the first phase, we can simplify the permissions part.

**Comment by zhongjiajie** [comment]
Thanks @zhuangchong for clarifications 👍
