### ISSUE TITLE
[Feature] [Flink task] repeatedly submitted on yarn

### ISSUE THREAD

**Issue by sw2011** [apache/dolphinscheduler#6825]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The ds cluster schedules real-time flink tasks. After the worker-server of the node executing the task is interrupted, the ds will automatically be fault-tolerant for execution on other nodes, but this causes the flink task to be repeatedly submitted on yarn

### What you expected to happen

flink task will be killed when worker down, and new worker should submit new flink task

### How to reproduce

 ds cluster and flink are not in the same cluster,kill worker-server of flink cluster and restart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
@sw2011 Thanks for your feedback, could you please provide more details? 
Such as which DS version do you use. When you manually cancel the flink task in DS, does this success?
