### ISSUE TITLE
[Bug] [UI] Error when edit an exist email alter instance

### ISSUE THREAD

**Issue by pk19876824** [apache/dolphinscheduler#6826]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Error happened when edit an exist email alter instance.
DolphinScheduler version: 2.0.0-release-prepare
Browser: Google Chrome 95.0.4638.69 (x86_64)

### What you expected to happen

Modify success.

### How to reproduce

![image](https://user-images.githubusercontent.com/26533223/141406266-58db67ee-322a-4504-a49f-8d3d0481d0aa.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
Already fixed in 2.0.2
