### ISSUE TITLE
[Bug] [postgresql image bug] image "bitnami/postgresql:11.11.0 "  database data not update

### ISSUE THREAD

**Issue by yangqiyu0306** [apache/dolphinscheduler#6835]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Deploying DolphinScheduler using docker, the deployment package is apache-dolphinscheduler-2.0.0-alpha-src.zip, after deployment, an error is found on the home page, the error message is that the database field is missing, the details are as follows picture
![首页](https://user-images.githubusercontent.com/39785282/141461676-bb7fc7ef-80d7-4b06-b88e-2786ed9f1358.png)
![log](https://user-images.githubusercontent.com/39785282/141461704-eb43990a-e966-49af-a9df-2d531422b0f0.png)

 after looking the error log, is "bitnami/postgresql:11.11.0" image database table not complete, the details are as follows picture
this is error database data
![42](https://user-images.githubusercontent.com/39785282/141462114-a6cba2ef-4a1f-4f2d-a404-5009b61ceeae.png)

this is apache-dolphinscheduler-2.0.0-alpha-src\sql\dolphinscheduler_postgre.sql data
![45](https://user-images.githubusercontent.com/39785282/141462130-0b12123d-614f-45e6-bc69-8db872689e9d.png)

it is recommended to rebuild "bitnami/postgresql:11.11.0" image

### What you expected to happen

no error is found on the home page

### How to reproduce

rebuild "bitnami/postgresql:11.11.0" image

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FangyangJz** [comment]
It seem like I've meeted the same problem. In my case, worker container didn't work.
I've raised a disscussion and pasted my worker container log,  here https://github.com/apache/dolphinscheduler/discussions/6837

**Comment by yangqiyu0306** [comment]
> It seem like I've meeted the same problem. In my case, worker container didn't work. I've raised a disscussion and pasted my worker container log, here #6837

I also have meet this problem
