### ISSUE TITLE
Misspelled words

### ISSUE THREAD

**Issue by pingyuan001** [apache/dolphinscheduler#6872]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

HttpTask has a word splicing error.
The word is doesn  that should be doesn't

### What you expected to happen

no

### How to reproduce

no

### Anything else

no

### Version

1.3.9

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good job, 
so glad to see you will submit a PR, please submit your PR to dev branch

**Comment by pingyuan001** [comment]
ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月17日(星期三) 下午4:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/dolphinscheduler] Misspelled words (Issue #6872)





 
good job,
 so glad to see you will submit a PR
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
