### ISSUE TITLE
AbstractTask has a piece of useless code

### ISSUE THREAD

**Issue by pingyuan001** [apache/dolphinscheduler#6873]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/26142295/141981209-9449cbf5-0b60-471a-962e-f5065e97351b.png)
this code is useless .
We can consider deleting its code

### What you expected to happen

no

### How to reproduce

no

### Anything else

no

### Version

1.3.9

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
Please fix the relevant code of the dev branch.

**Comment by pingyuan001** [comment]
ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月17日(星期三) 上午9:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] AbstractTask has a piece of useless code (Issue #6873)





 
Please fix the relevant code of the dev branch.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
