### ISSUE TITLE
[Bug] [Master] Master failover add dead-server should check zk the master node is not exist

### ISSUE THREAD

**Issue by geosmart** [apache/dolphinscheduler#6880]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 I use docker to deploy master, I have 2 master.
when I restart them by ansible:
1. master1 stop，remove zk node: `nodes/master/master1`
2. master1 start, remove zk node：`nodes/dead-servers/master1`
3. master2 watch master1 down, add zk node：`nodes/dead-servers/master1`
4. master1 watch add zk node：`nodes/dead-servers/master1`，master1 kill itself. stop quartz  will auto close jdbc connection , and every zk watch event will throw `com.alibaba.druid.pool.DataSourceClosedException: dataSource already`

so if you have multi master , and quickly restart one if them , the master just can not restart succesfully.

### What you expected to happen

anytime restart the master ,it can just restart success

### How to reproduce

when watch master down,  should check the master is not exist in `nodes/master/master1` and then add it to `nodes/dead-servers/master1`

### Version

1.3.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Yes, this may happen in some extreme cases, if the alive master add the `dead` master into dead path after the `dead` master restart, then the restart `dead` master will kill itself again.

The easy way to fix is add an atomic operation, when add an instance to dead path, check if it's in active path.

**Comment by geosmart** [comment]
and the worker has the same restart situation!
the master or worker must sleep  a while after stop ,then  start  
and the sleep time must greater than  `zookeeper.session.timeout`.

as my prod env config  `zookeeper.session.timeout=60000`.

1. stop master or worker,
2. sleep for 70 second,
3. start  master or worker

---

so ops resolve the bug. but bug is bug , we need to check the server is not exist in `nodes` path  and then add it to `dead-servers` path in atomic operation
