### ISSUE TITLE
[Bug] [Workflow Monitor] The legend text of the ring chart is not fully displayed.

### ISSUE THREAD

**Issue by songjianet** [apache/dolphinscheduler#6900]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The legend text of the ring chart is not fully displayed.

### What you expected to happen

The possible factor is the margin problem of the ring chart.

### How to reproduce

The workflow can be reproduced if there is data.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
@songjianet  It's better to have some image for this issue.

**Comment by songjianet** [comment]
There are many changes in this part, so I don't plan to reproduce some ui for processing.

**Comment by lenboo** [comment]
> There are many changes in this part, so I don't plan to reproduce some ui for processing.

Thank you very much, I will close this issue, hope your new ui.
