### ISSUE TITLE
[Bug] [menu] The content of the menu on the left is not fully displayed.

### ISSUE THREAD

**Issue by songjianet** [apache/dolphinscheduler#6902]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The Workflow Monitor menu cannot fully display the content when there is data due to its width. When other menu texts are too long, they cannot be displayed completely.

### What you expected to happen

A combination of the width of the menu and the length of the text content. It can be improved by the `tooltip` component.

### How to reproduce

The content of Workflow Monitor is too much.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good job

**Comment by DuChaoJiaYou** [comment]
I will fixed this issue

**Comment by zhongjiajie** [comment]
Did someone assign this issue to @DuChaoJiaYou , cc : @dailidong @CalvinKirs @lenboo @ruanwenjun @zhuangchong

**Comment by zhongjiajie** [comment]
Thanks

**Comment by lenboo** [comment]
close it now.
