### ISSUE TITLE
[Bug] [dolphinscheduler-api] when some datasource configuration is incorrect, "test connect" does not return results.

### ISSUE THREAD

**Issue by huangfox** [apache/dolphinscheduler#6905]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. create a mysql datasource, and some datasource configuration is incorrect, such as password is wrong.
2. click the "test connect" button, no results returned (always show "loading").
3. dolphinscheduler-api server keeps outputting error logs. The error is as follows:
`[ERROR] 2021-11-18 15:42:49.245 com.alibaba.druid.pool.DruidDataSource:[2787] - create connection SQLException, url: jdbc:mysql://localhost:3306/test, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1652)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1718)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2785)`

### What you expected to happen

1. If some datasource configuration is incorrect, "test connection" can return test result. 
2. dolphinscheduler-api server should not keep outputting error logs.

### How to reproduce

1. create a datasource, and set a wrong password .
2. click the "test connect" button.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xuchangqun** [comment]
"java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)"

you need to grant user permissions
@huangfox

**Comment by huangfox** [comment]
> "java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)"
> 
> you need to grant user permissions @huangfox

i provided the wrong password on purpose, then test the connection.
i hope to give a clear reminder, for example: connection failed.
now no clear reminder is given, and has been blocked.

**Comment by xuchangqun** [comment]
> > "java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)"
> > you need to grant user permissions @huangfox
> 
> i provided the wrong password on purpose, then test the connection. i hope to give a clear reminder, for example: connection failed. now no clear reminder is given, and has been blocked.

Ok, totally got it. 
Thank you for your feedback

**Comment by xuchangqun** [comment]
@huangfox 
Sorry to reply so late.

I have debug code in branch dev. There are following situations.
1. set incorrect password -> return JDBC connect failed.
2. set incorrect host (can't ping) -> Connection timeout(according to settings 'connection-timeout') and return JDBC connect failed.
3. correct -> return '成功'

**Comment by huangfox** [comment]
Thank you for your reply, I will confirm this issue later. 
@xuchangqun
