### ISSUE TITLE
[Bug] [dolphinscheduler-api] Edit a correct MySql datasource, "test connect" failed.

### ISSUE THREAD

**Issue by huangfox** [apache/dolphinscheduler#6916]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. Edit a **correct** MySql datasource (saved before and passed verification), and then click the "test connect" button, but can't connect the MySql datasource.
See the part of "How to reproduce" for details.

### What you expected to happen

1. Edit a correct MySql datasource, and then click the "test connect" button, return to connect successfully.

### How to reproduce

1. Create a correct MySql datasource, and save.
2. **Restart the dolphinscheduler-api server. (must do this step)**  
3. Edit the MySql datasource, and click the "test connect" button.
4. Connection failed

### Anything else

1. When edit an MySql datasource, the front-end page post a "test connect" request to the dolphinScheduler-api server. The request body that is object of BaseDataSourceParamDTO contains a null password field. 
2. The object of BaseDataSourceParam will be verified before initializing the data source client. If the password is null a default password (123456) will to set. 
The verification code is [here](https://github.com/apache/dolphinscheduler/blob/4114cb07f64950f88ffb4aa8a4ecc4815f32d76b/dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/client/CommonDataSourceClient.java#L71).

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Narcasserun** [comment]
You need to re-enter the password when editing the data source

**Comment by huangfox** [comment]
> You need to re-enter the password when editing the data source

I see, thanks for your reply. @Narcasserun 
In my personal opinion, this way will cause some confusion to users. 
In another case, if the database does not have a password, how to configure the data source? (If the password is null a default password (123456) will to set.)
