### ISSUE TITLE
[Feature] task submit policy

### ISSUE THREAD

**Issue by ldy521314** [apache/dolphinscheduler#694]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ldy521314** [comment]
说一下我的诉求，目前咱们的任务提交策略还是不够完善，我目前的任务一小时一跑，晚上运行的比较多，结果会出现任务堆积，结果相同的任务都会在队列里，就会出现，相同的任务重复提交，所以要修改提交策略，任务运行策略可以添加策略包括：单机串行（默认）、丢弃后续调度、覆盖之前调度；

**Comment by ldy521314** [comment]
建议方案：1故障转移：任务路由策略选择"故障转移"情况下，如果执行器集群中某一台机器故障，将会自动Failover切换到一台正常的执行器发送调度请求
2阻塞处理策略：调度过于密集执行器来不及处理时的处理策略，策略包括：单机串行（默认）、丢弃后续调度、覆盖之前调度
3事件触发：除了"Cron方式"和"任务依赖方式"触发任务执行之外，支持基于事件的触发任务方式。调度中心提供触发任务单次执行的API服务，可根据业务事件灵活触发
4，添加一个实时的监控任务进度 ，实时查看日志

**Comment by boandai** [comment]
One thing I don't quite understand, why do tasks appear to be submitted repeatedly when the task is stacked?

---
有一点我不太理解，任务堆积的情况下，为什么会出现任务被重复提交？
