### ISSUE TITLE
[Bug] [Dao] The data source configuration file does not take effect.

### ISSUE THREAD

**Issue by zhuangchong** [apache/dolphinscheduler#6943]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The data source configuration file does not take effect

### What you expected to happen

The data source configuration file takes effect.

### How to reproduce

Start ApiServer, you can see that the data source configuration is not effective

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
@zhuangchong is this issue already fixed？

**Comment by zhuangchong** [comment]
> @zhuangchong is this issue already fixed？

already fixed.
