### ISSUE TITLE
[Feature][Unit Tests] ds 2.0+ should remove useless uts as base class removed

### ISSUE THREAD

**Issue by tracehh** [apache/dolphinscheduler#6951]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Find some uts exist in dolphinscheduler 2.0+,  which base class not exist, such as MasterTaskExecThread.java

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tracehh** [comment]
![image](https://user-images.githubusercontent.com/58768413/148169170-c898a814-a201-467e-8fcf-29b32474c372.png)

**Comment by zhongjiajie** [comment]
Does is still exists in dev branch? @tracehh

**Comment by tracehh** [comment]
Yes, Such as MasterTaskExecThreadTest.java still exists in dev branch. @zhongjiajie

**Comment by zhongjiajie** [comment]
Am not sure about it, I if we remove some classes, we should remove the test too
