### ISSUE TITLE
[Bug] [endless loop] Workergroup have only one Worker,when this worker is down。run task job is endless loop

### ISSUE THREAD

**Issue by chinaboyll** [apache/dolphinscheduler#6959]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

My dolphinScheduler-cluster version is 1.3.3, I have double master and  many WorkerGroup,one WorkerGroup have only one Worker.
When this worker is down。run task job is endless loop.
All tasks are blocked.
------------------------------------------------------------------------------------------
我的海豚集群版本是1.3.3，我有两个master节点和很多个工作组，其中一个工作组有一个工作节点。
当我这个工作节点服务宕了。配置这个节点运行的工作task会进行死循环。
所有的任务都会等待这个死循环结束才能执行。

### What you expected to happen

When one WorkerGroup is abnormal, It doesn't affect anything else.
------------------------------------------------------------------------------------------
当我的工作组节点宕机，不会影响其他任务执行

### How to reproduce

1 set two WorkerGroup ,A and B, Each work have a Worker;
2 set two task,  one is A,other is B;
3 stop B worker-service,then run more workerGroupB job ;
4 run A task, then this task are blocked.
------------------------------------------------------------------------------------------
1、我有两个工作组，A和B。每个工作组设置一个Worker。
2、设置两个任务，一个任务使用A工作组执行，另一个使用B。
3、我在服务器里关闭workerB节点的的Worker服务，同时运行B工作组任务。多运行几个。
4、这时候再执行A，会发现A无法执行。
查看日志会发现不停的提示节点宕掉了。

### Anything else

dolphinscheduler-master.log:
[ERROR] 2021-11-18 14:42:24.568 org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer:[148] - dispatch error
org.apache.dolphinscheduler.server.master.dispatch.exceptions.ExecuteException: fail to execute : Command [type=TASK_EXECUTE_REQUEST, opaque=2867, bodyLen=1735] due to no suitable worker , current task need to bi worker group execute
        at org.apache.dolphinscheduler.server.master.dispatch.ExecutorDispatcher.dispatch(ExecutorDispatcher.java:87)
        at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.dispatch(TaskPriorityQueueConsumer.java:145)
        at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.run(TaskPriorityQueueConsumer.java:114)

### Version

1.3.3

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chinaboyll** [comment]
I changed the source code : org/apache/dolphinscheduler/server/master/runner/MasterTaskExecThread.java - waitTaskQuit()
insert into Failure count.
`Integer num = 0;
   if (num>=50 && taskInstance.getState() == ExecutionStatus.SUBMITTED_SUCCESS && !taskInstance.getState().typeIsFinished()){
                    cancelTaskInstance();
                    logger.error("worker is down,task is kill");
                }else {
                    num++;
                    logger.info("master submit job error number: "+num);
                }`
If I change the code, does it affect other implementations.

**Comment by lenboo** [comment]
@chinaboyll 
Please check this issue in 1.3.9 or 2.0.2.  
You can reopen it when you find some problems.
