### ISSUE TITLE
[Bug] [Sqoop] Sqoop export mode. When the data source mode is hive, the data destination types are hive and HDFS

### ISSUE THREAD

**Issue by lzzcj** [apache/dolphinscheduler#6960]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I use the export mode of Sqoop to export the tables in Hive to MySQL, after I select Hive as the data source on the interface, the data destination can only be HDFS or Hive, not MySQL. And when I switch the data source to HDFS, the data destination is still HDFS and Hive

### What you expected to happen

The export mode of Sqoop should be to export the data in Hive / HDFS to a relational database

### How to reproduce

The data destination type of the export mode of Sqoop should be a relational database such as MySql

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I will check this issue.
