### ISSUE TITLE
[Feature][MasterServer] Add cache manager for Master

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#6963]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Now when Master run a workflow, it will do many db select operation, such as `processDefinition`, `taskDefinition`, `processTaskRelation`, `tenant`, `user`, `workGroup`, `project`......

I think these data will not be changed easily, so if we can use cache instead of selecting from db, it will speed up the processing of workflow and improve performance.

function design:

- cache config for enable switch and other params like expire time, cache size.
- cache annotation, which can be use easily, and it's helpful to manage the unified cache logic -> use spring cache + caffeine
- cache hit rate statistics
- cache update notify, now is from api-server

sub-issue:
- [x] #6985 
- [x] #6987
- [x] #6988 

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
> Now when Master run a workflow, it will do many db select operation, such as processDefinition, taskDefinition, processTaskRelation, tenant, user, workGroup, project......

If the cache is only for DB operations, maybe we can investigate whether the ORM framework supports cache itself, I remember MyBatis supports some basic cache mechanism.

> function design:
> 
> * [ ]  add the cache switch, it can be controlled by user freely. If false, the cache will not effect
> * [ ]  cache expire config, it will decide how long the cache will last
> * [ ]  cache annotation, which can be use easily, and it's helpful to manage the unified cache logic
> * [ ]  cache hit rate statistics
> * [ ]  cache update notify, now is from api-server

All the functionalities above can be easily achieved by introducing 

```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-cache</artifactId>
</dependency>
```

@caishunfeng which cache system do we want to use?

**Comment by caishunfeng** [comment]
@kezhenxu94 yes, I found too, the spring cache maybe is suitable.

**Comment by caishunfeng** [comment]
> ```
> <dependency>
>     <groupId>org.springframework.boot</groupId>
>     <artifactId>spring-boot-starter-cache</artifactId>
> </dependency>
> ```

**Comment by zwZjut** [comment]
try to take #6987

**Comment by caishunfeng** [comment]
> try to take #6987

OK, looking forward to your PR.
