### ISSUE TITLE
[Feature]The task flow instance should be displayed as a history after the task flow definition is deleted.（任务流定义被删除后任务流实例应作为历史记录展示）

### ISSUE THREAD

**Issue by n2-cmd** [apache/dolphinscheduler#698]
**Is your feature request related to a problem? Please describe.**
When I delete the task flow definition, I find that the task flow instance related to it is not queried. This is different from what I expected. I think the task flow instance display also has the role of historical workflow display. It should not be deleted as history records.

**Describe the solution you'd like**
1. After the task flow definition is deleted, the executed task flow instance and task instance should be displayed as history.
2. When the task flow definition is deleted, the executed task flow instance should no longer be able to edit the rerun. Editing a workflow instance is convenient but not well maintained, and is only used when testing changes to the workflow. When the action flow definition is deleted, there should be no more edited rerun scenarios.
3. Assume that the editing workflow instance is used for task flow debugging. It is recommended that the modified workflow can be automatically applied to the current workflow definition, or a button can be applied to the definition without re-modification in the definition.

**Describe alternatives you've considered**
1. I modified the task flow instance edit and edited it to the task flow instance.
2. I added project_id and is_deleted to tf_process_instance. When the workflow definition is deleted, the workflow instance is marked as deleted. The deleted instance can be displayed but cannot be edited and rerun.

**Additional context**

**Comment by dailidong** [comment]
very good idea , thank you!
