### ISSUE TITLE
sudo: sorry, you must have a tty to run sudo

### ISSUE THREAD

**Issue by wan1869** [apache/dolphinscheduler#6983]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![1637746939(1)](https://user-images.githubusercontent.com/75246409/143213898-b75ca41c-9f8a-4db2-958c-4b276cee2158.png)
![1637746999(1)](https://user-images.githubusercontent.com/75246409/143214047-3d504e86-1ac9-4545-90f8-3c0d7468a184.png)
![1637747045(1)](https://user-images.githubusercontent.com/75246409/143214158-ccb111b7-f5a9-4cbb-a8e6-77e4362aa1eb.png)
I installed DolphinScheduler according to the official documentation, created the project and ran a simple shell node. The project failed and the log said "sudo: Sorry, you must have a tty to run sudo ", and also checked my /etc/sudoers file, there is no Default requiretty content, the above three pictures can see the general content of what I said. My DolphinScheduler version is 1.3.9. How can I handle this problem?

### What you expected to happen

How to solve "Sudo: Sorry, you must have a tty to run sudo"?

### How to reproduce

I had problems trying to install the DolphinScheduler on several cloud servers

### Version

1.3.9

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
you should execute the following command in the linux terminal:
sed -i 's/Defaults    requiretty/#Defaults    requiretty/g' /etc/sudoers

this command means you should comment the line like this action
 #Defaults    requiretty

**Comment by davidzollo** [comment]
![image](https://user-images.githubusercontent.com/15833811/143430370-f144d36d-35f2-4a0f-90cc-1249e2a50c32.png)

https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/installation/pseudo-cluster.html

**Comment by davidzollo** [comment]
if you're interested in this question, I think you can submit a PR to make it better.
the doc need to update for the right word,  requirett -> requiretty

```
sed -i 's/Defaults requiretty/#Defaults requiretty/g' /etc/sudoers
```
the doc repository:
https://github.com/apache/dolphinscheduler-website
