### ISSUE TITLE
[Bug] [Module Name] The conf of the rpm package lacks master.properties and worker.properties

### ISSUE THREAD

**Issue by paopjian** [apache/dolphinscheduler#6986]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

使用 mvn -U clean install -Prpmbuild -Dmaven.test.skip=true -X 生成的rpm包,使用 rpm -ivh apache-dolphinscheduler-xxx.noarch.rpm 进行安装后conf缺少master.properties和worker.properties 

### What you expected to happen

pom.xml 编译文件匹配错误

### How to reproduce

mvn -U clean install -Prpmbuild -Dmaven.test.skip=true -X

### Version

2.0.0-alpha

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
duplicate issue: #7402
