### ISSUE TITLE
[Feature][server & ui] Add dependent tips about success or failure

### ISSUE THREAD

**Issue by shangeyao** [apache/dolphinscheduler#6996]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add success and failure prompts in the ui and log, just like the old version 1.3.x
![image](https://user-images.githubusercontent.com/42203474/143410264-1692f1a4-3d26-48ea-8204-c79a3a73e8aa.png)
![image](https://user-images.githubusercontent.com/42203474/143410415-651541e8-6b44-42a6-832c-360222565c2f.png)

### Use case

above

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I have the same problem.This function is very important to me.Can this be added to 2.0.2-release?@lenboo
