### ISSUE TITLE
dolphinscheduler   Call the mysql stored procedure

### ISSUE THREAD

**Issue by zfq314** [apache/dolphinscheduler#7012]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

How to call the mysql stored procedure, how to dynamically pass in custom parameters, the passed in parameters are the results of a select statement query, whether this is the case, I did not see on the official website, similar examples, I look forward to replying, thanks
![image](https://user-images.githubusercontent.com/33599707/143548229-50c2695d-b700-4cbb-adbc-511bb55e1396.png)

The parameters in the red box want to be dynamically passed in

### Use case

![image](https://user-images.githubusercontent.com/33599707/143548354-a1d5861b-a747-42c9-bf63-515a5516081f.png)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zfq314** [comment]
mysql 8.0.20

**Comment by zfq314** [comment]
dolphinscheduler    1.3.3

**Comment by zfq314** [comment]
myself deal

**Comment by csxuyang** [comment]
what's the problem? How to deal?

> myself deal
