### ISSUE TITLE
[Bug] [dolphinscheduler-datasource-hive] Using hive jdbc requires hive-shims jars

### ISSUE THREAD

**Issue by jon-qj** [apache/dolphinscheduler#7013]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

dolphinscheduler-datasource-plugin——>dolphinscheduler-datasource-hive——>pom

 <dependency>
            <groupId>org.apache.hive</groupId>
            <artifactId>hive-jdbc</artifactId>
            <version>${hive.jdbc.version}</version>
            <exclusions>
           ....................
               <exclusion>
                    <artifactId>hive-shims</artifactId>
                    <groupId>org.apache.hive</groupId>
                </exclusion>
           .....................
            </exclusions>
        </dependency>

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/hive/thrift/TFilterTransport
....

### What you expected to happen

executing hive sql successfully requires hive-shims jars.

### How to reproduce

as shown by dev branch.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Narcasserun** [comment]
Are you willing to finish it
