### ISSUE TITLE
[Feature][Auto DAG] Auto create workflow while import sql script with specific hint

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#7016]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Expand exists import process in 

![image](https://user-images.githubusercontent.com/15820530/143562382-7d49c649-3c43-4280-856e-612c090717e3.png)

Auto create workflow while import sql script with specific hint `name` and `upstream`. would create `sql task type` task for and set dependence according setting.

### Use case

When user import sql scripts with specific hint in header, it will create sql task for each sql scripts, and then parse the hint to set sql task upstream. After parsing all sql script, we would create the same number of tasks as the number of sql scripts(files).
Beside that, we would connect tasks by sql scripts given hint and set task relation for it. if sql scripts set not exists upstream task we should pop a dialog and ask if ignore dependent or not. If user choose "yes" we should import but ignore the error, if choose "no", we should termine import without create any task or workflow.

The flow chat as below:

> source file is in https://drive.google.com/file/d/1aV4nHH9_xf8z9WiyT6_-rDlWv2fpXzEj/view?usp=sharing

![DS-AutoDAG-flow-chat drawio](https://user-images.githubusercontent.com/15820530/143552961-267ee1cf-4c9b-498e-9e9f-9a0ea4de355b.png)

## SQL scripts example

And here is an example about sql scripts. Each sql script should have two hint, `name` to specific sql task name , and `upstream` to set task upstream for this task

* `start.sql`: If both `name` and `upstream` hint is provided, we just use them to set task name and upstream task, if `upstream` set to root, mean task is the root task in the workflow
  ```sql
  -- name: start_auto_dag
  -- upstream: root
  insert into table start_auto_dag select 1;
  ```

* `child1.sql`: When task have upstream task, you could just set the value as `upstream`. And task relation would be create  after autodag parser done.
  ```sql
  -- name: branch_one
  -- upstream: start_auto_dag
  insert into table branch_one select * from start_auto_dag;
  ```

* `branch_two.sql`: If hint `name` not provide, we would use sql script filename as task name. In this case, we use `barnch_two` as task name, and set `start_auto_dag` as upstream task.
  ```sql
  -- upstream: start_auto_dag
  insert into table branch_two select * from start_auto_dag;
  ```

* `end.sql`: If task have two upstreams, you could list two task name and using specific delimiter for it, as an example we use `,` as delimiter, and set task `branch_one` and `branch_two` as upstream 
  ```sql
  -- name: end_auto_dag
  -- upstream: branch_one, branch_two
  insert into table end_auto_dag
  select * from branch_one union all
  union all
  select * from branch_two union all
  ```

* `independence.sql`: If upstream hint not set, we would use `root` as default. So it would become independence task in the workflow
  ```sql
  select 'I am the independence of this workflow'
  ```

After we submit and DS parse, would could get workflow as below

```
                   -> branch_one ->
                 /                  \
start_auto_dag ->                     -> end_auto_dag
                 \                  /
                   -> branch_two ->

independence
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
This is only the first step of this feature

## Some idea in the further

After this patch merged, we could batch load sql scripts to DS and create workflow for it. Of course he can automatically create workflow, after we add some hints in sql scripts header.

Let me think about which part we could improve, and maybe you could find it. Yeah, it called autodag base on we adding some addition information for original file. It could be simplify by using sql script name as task name, and using `sql parser` to analyze the dependences. And maybe that is the true `AutoDAG`.

But this is not the scope of this issue, cause `sql parser` is a little difficult and not urgent for this moment. we should hold this until our community finish and done their important things.

## SQL scripts example

And here is an example about sql scripts. It just contain original sql scripts, our lovely `sql parser` would parse the dependence and set tasks relations

* `start.sql`:

  ```sql
  insert into table start_auto_dag select 1;
  ```

* `child1.sql`:

  ```sql
  insert into table branch_one select * from start_auto_dag;
  ```

* `branch_two.sql`:

  ```sql
  insert into table branch_two select * from start_auto_dag;
  ```

* `end.sql`:

  ```sql
  insert into table end_auto_dag
  select * from branch_one union all
  union all
  select * from branch_two union all
  ```

* `independence.sql`: If upstream hint not set, we would use `root` as default. So it would become independence task in the workflow

  ```sql
  select 'I am the independence of this workflow'
  ```

After we submit and DS parse, would could get workflow as below

```
                   -> branch_one ->
                 /                  \
start_auto_dag ->                     -> end_auto_dag
                 \                  /
                   -> branch_two ->

independence
```

**Comment by eye-gu** [comment]
I want to try it.

**Comment by zhongjiajie** [comment]
> I want to try it.

@ououtt  Great! but as out weekly meeting said, I think you prefect to try sql parser, in https://github.com/apache/dolphinscheduler/issues/7016#issuecomment-979849314 ,  but not the hint case, in https://github.com/apache/dolphinscheduler/issues/7016#issue-1064286923. Am I right?

**Comment by zhongjiajie** [comment]
@ououtt  Great, feel free to take it, looking forward your contribution.

**Comment by zhongjiajie** [comment]
Hi @ououtt , be careful we should make our sql hint configurable which user could set keyword, WDYT?

**Comment by eye-gu** [comment]
I don't think it's necessary. Keywords are conventions, not configurations

**Comment by zhongjiajie** [comment]
> I don't think it's necessary. Keywords are conventions, not configurations

After I think deeply, I agree with you and think we should use as constant, not configuration. If we make keyword as configure it would make user feel confuse cause they would have different keyword when they change. And with different DS clusters, with different keyword configure, cluster would have different behavior.

I need another opinion here, cc @lenboo @CalvinKirs

**Comment by eye-gu** [comment]
I want to continue improving this issue, including setting up a separate import button in the front-end and making the back-end parsing pluggable to support methods such as hint and SQL parsing
