### ISSUE TITLE
[Feature][workflow list edit] Add list edit view from task definition

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#7018]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add task list view for editing a large number of tasks more easier.

## Background

For now we have to go and find task in specific workflow to edit it. But if there are a large number of tasks and workflows in single project. it hard to find and edit the task. 

## Proposal

Maybe we should find more easy way to edit a large number of tasks. Here I post my initial idea, **but if you have suggestion or other amazing idea, please let me know here**.

**List editor for a large number of tasks**

In process definitions view, add a button and link to `list view`. It provide task in list view, and allow user filter by process definition name or task name. When user typing process definition name or task name in filter component, it would recommend the exists task for user. User should select the exists task.

In the task edit, we would show task attributes and depedence. User could see wether task should edit or not, when user want to change task attributes or dependence, just click `edit` bottom and it would pop task editor dialog for editing task. If user think task do not need anymore just click `delete` bottom to delete it.

![image](https://user-images.githubusercontent.com/15820530/143574018-f8da426f-0696-41c3-8475-cd2878670fb0.png)

![image](https://user-images.githubusercontent.com/15820530/143574757-eef9da68-0b92-4c9d-895d-81dff1c7303e.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
i think we can add this feature in "TaskDefinition ListPage" like this:


![image](https://user-images.githubusercontent.com/29528966/143807495-4b429758-fb5e-40c6-9d25-bad6d8036af3.png)

**Comment by zhongjiajie** [comment]
> i think we can add this feature in "TaskDefinition ListPage" like this:
> 
> ![image](https://user-images.githubusercontent.com/29528966/143807495-4b429758-fb5e-40c6-9d25-bad6d8036af3.png)

Yeah, you are right! it would be better 👍

**Comment by zhongjiajie** [comment]
@Wangyizhi1 wants to take over this,  but we need backend developer support. @JinyLeeChina Do you inserting in this feature? is about the API change

**Comment by wangyizhi1** [comment]
If this feature is added on the task definition page, the following interfaces need to be provided by the backend:
1. Task List Interface
Return the basic information of the task and the workflow, as well as the upstream and downstream relationship of the task.
2. Delete task interface
Delete a task of a workflow
3. Modify the task interface
Modify the configuration of a task in a workflow
4. Create task interface
Add a task to a workflow

If we do not plan to modify the API, the following methods can be referred to:

1. Add a 'List Mode' switch to the workflow page toolbar:
<img width="1141" alt="taskList1" src="https://user-images.githubusercontent.com/87303815/145765875-30746eeb-d217-4fa0-911e-8be74dcc9c39.png">

2. The user can control the display mode of the workflow page through the switch:
<img width="1370" alt="taskList2" src="https://user-images.githubusercontent.com/87303815/145766067-5e34f059-0f2c-495d-aec1-659baac04133.png">

In this way, existing interfaces can be reused, and the front-end can be done alone.

**Comment by edward-yang** [comment]
This is our major operation process of using IData with DolphinScheduler in _zhengcaiyun_. These illustrate our use of the DolphinScheduler interface.
Publish task and worflow:
![image](https://user-images.githubusercontent.com/1447444/146329118-5019a7df-1e68-4711-950c-c5640870964e.png)

Remove task and worflow:
![image](https://user-images.githubusercontent.com/1447444/146329652-b2d12ebc-931f-4e49-8c5b-482df932494e.png)

**Comment by zhongjiajie** [comment]
Close due to #7443 #7772 #7829 #7852
