### ISSUE TITLE
[Improvement][MasterWorker] Self-recovery when master or worker lost connection from registry center

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#7024]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Background

Now if a master or worker lost zk connection, it doesn't disconver itself immediately until checking the dead server list.
And when it knows that it was judged to dead serve, it will stop itself, without self-recovery.

### Prosoal

![d264093da134508c29b021d9c57d440](https://user-images.githubusercontent.com/11962619/143667882-118377c2-c7d2-4e5d-9eea-05db9eb52d61.png)

When master lost zk connection:
1. update current server state to `wait reconnect`
2. send server lost connection alert
3. keep quartz working (it will ensure work normally by quartz and db)
4. stop accepting new request
4. stop handling commands and process instances, clear the local running process instances; (it will be take over by other master)
5. wait to reconnect
6. when reconnect successfully, send server recover alert, update server state to `normal` and recover working

![628345e6b1dd3cf147f8d40ee35021f](https://user-images.githubusercontent.com/11962619/143667893-da5decc9-7588-42ca-b3d9-503cb029bb27.png)

When worker lost zk connection:
1. update current server state to `wait reconnect`
2. send server lost connection alert
2. kill the running task (it will be task over by master and rerun)
3. stop accepting new request
4. wait to reconnect within a certain time
5. if reconnect timeout, stop itself
6. when reconnect successfully,  send server recover alert, update server state to `normal` and recover working;

_Originally posted by @caishunfeng in https://github.com/apache/dolphinscheduler/discussions/6643#discussioncomment-1706255_

### Related issues

#7004 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shangeyao** [comment]
please assign to me
