### ISSUE TITLE
[Bug] [API] Conflict handler in API 

### ISSUE THREAD

**Issue by kezhenxu94** [apache/dolphinscheduler#7048]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

`org.apache.dolphinscheduler.api.controller.SchedulerController#updateSchedule` has the same handler method with `org.apache.dolphinscheduler.api.controller.SchedulerController#updateScheduleByProcessDefinitionCode`, maybe both of them are not used in frontend, we'd better check and if so, remove them, this cause the test `org.apache.dolphinscheduler.api.controller.SchedulerControllerTest#testUpdateSchedule` to fail

### What you expected to happen

No test is failed 

### How to reproduce

run `org.apache.dolphinscheduler.api.controller.SchedulerControllerTest#testUpdateSchedule` and it will fail

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
The updateScheduleByProcessDefinitionCode is added for the convenience of calling through the interface. For example, if someone want to change the scheduler of the workflow, he can directly use the workflow code to change the scheduler. BTW, This bug has been fixed in #7221
