### ISSUE TITLE
[Bug] [dolphinscheduler-api] Create or edit a workflow definition, check the timeoutNotifyStrategy, the timeoutNotifyStrategy is null in the database

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#7070]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Create or edit a workflow definition, check the timeoutNotifyStrategy, the timeoutNotifyStrategy is null in the database
![image](https://user-images.githubusercontent.com/95271106/144008124-e24a57e3-59d6-40e6-b019-f9beeac8b2ed.png)

![image](https://user-images.githubusercontent.com/95271106/144007568-57b371e1-24cf-4694-8378-9529fb6351d8.png)
![image](https://user-images.githubusercontent.com/95271106/144007567-6fd24e2e-bb34-4e69-a71a-240c789d2294.png)

### What you expected to happen

The timeoutNotifyStrategywas not written to the database when saving the workflow definition

### How to reproduce

When saving the workflow definition, write the timeoutNotifyStrategywas to the database

### Version

2.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I will fix this issue.
