### ISSUE TITLE
[Bug] [dolphinscheduler-worker] worker-server start error

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#7091]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/95271106/144161991-1e201890-4033-4c29-8a39-9798421cd636.png)

### Version

2.0.1-prepare

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
@janeHe13 Could you give more detail information about this? ex, which deployment you use and which command you run?
