### ISSUE TITLE
[Bug] [Process definition] sqoop component issues

### ISSUE THREAD

**Issue by mchcz** [apache/dolphinscheduler#7103]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.sqoop component custom parameters have no checks and can add multiple empty parameters, resulting in an exception when the workflow is selected by dependent components.
2. If you add a sqoop component to a workflow and add multiple custom parameters at the same time, saving will result in data loss for the entire workflow.

### What you expected to happen

The sqoop component needs to enforce the parameter name required, and the workflow can be saved normally without losing data.

### How to reproduce

1. Create a workflow, add a component, such as SQL components or SHELL components can be saved, open normal.
2. Continue to add sqoop components, but do not add custom parameters, save, open normal.
3. Add multiple empty parameters to the sqoop component, save, open and discover that everything is gone.

### Version

2.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I will check this issue.

**Comment by calvinjiang** [comment]
@mchcz I can not reproduce this issue under my environment. Could you shed some more light on it? Give me more details about this issue.

**Comment by zhongjiajie** [comment]
> @mchcz I can not reproduce this issue under my environment. Could you shed some more light on it? Give me more details about this issue.

hi @calvinjiang , I found out you said you could not reproduce this case, but you submit  PR for this. Did you reproduce this?

**Comment by calvinjiang** [comment]
> > @mchcz I can not reproduce this issue under my environment. Could you shed some more light on it? Give me more details about this issue.
> 
> hi @calvinjiang , I found out you said you could not reproduce this case, but you submit PR for this. Did you reproduce this?

The reporter just connected with me. Through the details of this issue, I can reproduce it and figure out why the issue happened. So I just submitted a pull request to fix this issue.

**Comment by zhongjiajie** [comment]
Great! I have ask some who familiar with frontend to review your PR, thanks 👍
