### ISSUE TITLE
[Feature][Docs] How to unsubscribe the mail-list

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#7134]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We should tell the subscribers how to unsubscribe the mail-list on the docs.
"If you want to unsubscribe, just send an email to dev-unsubscribe@dolphinscheduler.apache.org , please follow the specified steps after receiving the reply"

the process should be added here:
https://dolphinscheduler.apache.org/en-us/community/development/subscribe.html
and 
https://dolphinscheduler.apache.org/zh-cn/community/development/subscribe.html

the web-site repository:
https://github.com/apache/dolphinscheduler-website/

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lukairui** [comment]
This issue seems have been fixed.
REFER TO : [PR#7419](https://github.com/apache/dolphinscheduler-website/pull/581) 

![image](https://user-images.githubusercontent.com/26786173/147021935-8aaace59-5948-4507-93d7-19def5069af1.png)
![image](https://user-images.githubusercontent.com/26786173/147021962-129a4e1e-2e60-420b-af38-4daff0621704.png)

**Comment by lukairui** [comment]
@zhongjiajie please check this issue and confirm this issue has been fixed. 
Because This issue is **waiting for reply**.

**Comment by zhongjiajie** [comment]
> @zhongjiajie please check this issue and confirm this issue has been fixed. Because This issue is **waiting for reply**.

Yeah, you're right! I going to close this issue. You did a good job.
