### ISSUE TITLE
[Feature]Can you provide multi-environment deployment capabilities?

### ISSUE THREAD

**Issue by Jedda1314Jessie** [apache/dolphinscheduler#714]
When developing a normal project, there are several environments, such as: dev (development environment), test (test environment), staging (pre-release environment), prod (production environment)

When I have developed 10 components according to one requirement in dev, easyscheduler does not currently support upgrading to other environments. It is impossible to say that when I go online, I will redo the 10 new components in each environment again.

Isn't this similar to writing a java program, and then rewriting it in other environments without a git?

I hope to provide such a function, at least like azkaban can use git to manage files, div->test directly branch and merge, and then submit the zip package. I don't know if easyscheduler can provide such a function.

---
正常项目开发的时候，都是有好几个环境的，比如：dev（开发环境），test（测试环境），staging（预发布环境），prod（生产环境）

当我在dev已经根据一项需求开发了10个组件，easyscheduler目前不支持升级到其他环境，不可能说我上线的时候再单独把本次新增的10个组件在各个环境重做一遍吧？

这不就类似我写个java程序，然后不用git，直接一个一个类在其他环境重写一遍吗

希望能提供这样的功能，起码像azkaban是可以用git来管理文件，dev->test的时候直接分支合并，然后提交zip包就可以了。不知道easyscheduler能否提供这样的功能。

**Comment by dailidong** [comment]
If the process definition has import and export functions, can you solve the problem you said?

---
如果工作流定义有导入和导出功能，是否就可以解决你说的这个问题么？

**Comment by dailidong** [comment]
?

**Comment by madfrog2047** [comment]
it's better have database backup and restore then new environment will be look like the origin
最好有数据库的备份和恢复，这样新搭建的环境直接可以原样恢复。

**Comment by dailidong** [comment]
Very good idea， is there anybody who want to implement it and contribute to community?

**Comment by dailidong** [comment]
please use English，English is needed, and you also can append Chinese description,  thx!

**Comment by dailidong** [comment]
if anybody want to implement this feature , please reply or let me know!

**Comment by dailidong** [comment]
@chongchongzi ， please review “process definition import and export functions” and check whether can support cross-cluster or not, thank you!

**Comment by chongchongzi** [comment]
The workflow import and export function can support cross environment. As long as the project name, resource name and data source name are consistent, it is OK
（工作流导入导出功能可以支持跨环境，只要项目名称，资源名称，数据源名称一致可以了）

**Comment by CalvinKirs** [comment]
If the import and export cannot meet the current needs, when we need to develop again, please pay attention to keeping the environment equivalent.
