### ISSUE TITLE
[Feature][Auto DAG NEW] Automatically implement task dependency recommendations

### ISSUE THREAD

**Issue by boy-xiaozhang** [apache/dolphinscheduler#7156]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Task dependency recommendations are automatically implemented. The data warehouse is mainly a data flow dependency, so if the user can write a HiveSQL or Spark SQL task and click Save, the pop-up box prompts the dependencies that the task may use,then implement DAG construction according to the user's select,Is a good way,users choose to rely on accuracy and stability are relatively high,  based on the auto dag proposed by jiajie brother #7016 , it is converted to automatically prompt dag dependencies to complete the dag construction,we can also do the lineage between process, task, and table based on the dependency table

### Use case

![1638528316(1)](https://user-images.githubusercontent.com/60912722/144589700-c47bd4fe-c437-434c-981e-5d898f632061.png)

When the user clicks the task to create a new task and clicks to save, we will give a prompt, the task may have dependencies, and the user will automatically rely on the dag diagram by checking it.I hope to discuss this issue with you guys. This is very needed in terms of scheduling intelligence and big data process scheduling.

``` sql 
INSERT OVERWRITE TABLE test.aaa SELECT id FROM test.bbb;
INSERT OVERWRITE TABLE test.bbb SELECT id FROM test.cccc;
INSERT OVERWRITE TABLE test.dddd SELECT id FROM test.aaa left join test.fff
```
the above sql generates the following dag

![image](https://user-images.githubusercontent.com/60912722/144733043-a0acf371-bace-497b-a4cc-9411086e1c61.png)

or For the existing dag, the sql content is parsed when the user saves the task,task content is
```sql
insert overwrite table test.yutj select * from test.dddd
```
the above sql generates the following dag

![image](https://user-images.githubusercontent.com/60912722/144733194-1ada945c-be0b-435f-aa79-574504414c9c.png)

### Related issues

based on the by #7016 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by boy-xiaozhang** [comment]
It can support Spark SQL and Hive SQL to complete smart recommendations, but we may need to add a new data table to store dependency information, and secondly, do we need to repeat the wheel to parse the SQL, or directly parse through the native jar package, I recommend using it directly jar package, instead of quoting too many miscellaneous items in ds

**Comment by zhongjiajie** [comment]
> do we need to repeat the wheel to parse the SQL, or directly parse through the native jar package

Hi @boy-xiaozhang , what does this mean? What directly jar package? did you mean we should use `Antlr` or `calcite` ?

**Comment by zhongjiajie** [comment]
Hi @boy-xiaozhang , this issue mostly look good to me. But I still have some question here, maybe you could clarification for me.
1. Your first example here is 

> INSERT OVERWRITE TABLE test.aaa SELECT id FROM test.bbb;
INSERT OVERWRITE TABLE test.bbb SELECT id FROM test.cccc;
INSERT OVERWRITE TABLE test.dddd SELECT id FROM test.aaa left join test.fff

But it seem you missing task `cccc` in the graph showed below. Did I missing some information or you missing some task graph?

2. In your second example, why we would create new workflow instead append new sql task into exists workflow?

> or For the existing dag, the sql content is parsed when the user saves the task,task content is

Did you mean when user create new workflow and create sql task which have auto match upstream task in our meta table, but task belongs to other workflow. Then we should link a workflow dependence between those two workflow?

3. BTW, I do not think we should pop a new dialog when user click "save" button after they finish sql task definition. 

>  if the user can write a HiveSQL or Spark SQL task and click Save, the pop-up box prompts the dependencies that the task may use

I found out we already have `upstream task` setting in our sql task definition as below.  So maybe we could reuse it, add suggest upstream task base on sql parser, WDYT 

![image](https://user-images.githubusercontent.com/15820530/144741938-21f499ba-3e17-4460-b3ca-b2018224a479.png)

**Comment by boy-xiaozhang** [comment]
hi @zhongjiajie , let me answer your question.

1,The one question:
>  But it seem you missing task cccc in the graph showed below. Did I missing some information or you missing some task graph?  

in this example,
```sql
INSERT OVERWRITE TABLE test.aaa SELECT id FROM test.bbb;
INSERT OVERWRITE TABLE test.bbb SELECT id FROM test.cccc;
INSERT OVERWRITE TABLE test.dddd SELECT id FROM test.aaa left join test.fff
```
The ccc table may be a table extracted by the user, such as the ods layer, but there are many types of extracted frameworks, such as seaTunnel, dataX, sqoop, flume or flinkX. This kind of task requires us to customize the blood relationship analysis. In order to perform the extraction task auto dag, but whether it is worthwhile for dolphinscheduler, this question may be worth communicating;

2,The second question:
> or For the existing dag, the sql content is parsed when the user saves the task,task content is 

this function is really good, better than I thought, we can indeed rely on it to do the analysis, and give the upstream tasks that users recommend to rely on, minus the cost of users switching back and forth to search;

3,Regarding the above antlr or calcite question:
> what does this mean? What directly jar package? did you mean we should use Antlr or calcite ? 

This means which way we should parse user SQL, spark and hive built-in parse class or antlr4 or druid
i prefer the built-in parse class, antlr 4 is also good, I don't know much about calcite

**Comment by zhongjiajie** [comment]
> The ccc table may be a table extracted by the user, such as the ods layer, but there are many types of extracted frameworks, such as seaTunnel, dataX, sqoop, flume or flinkX. This kind of task requires us to customize the blood relationship analysis. In order to perform the extraction task auto dag, but whether it is worthwhile for dolphinscheduler, this question may be worth communicating;

Ok, so you mean that this table is not a SQL task in DS, should we could not add it in auto DAG, right?

**Comment by zhongjiajie** [comment]
> This means which way we should parse user SQL, spark and hive built-in parse class or antlr4 or druid
i prefer the built-in parse class, antlr 4 is also good, I don't know much about calcite

@ououtt seems interested in sql parser too, do you have other suggestions here? Or maybe we should get a better way after we discussion?

**Comment by zhongjiajie** [comment]
@lenboo Did you ask whether sql parser could parse below sql script or not?

```sql
-- Can the following sql script parser to the following dependencies?
-- users -> target_table
-- orders -> target_table

-- last 3 months registered users
with user_cte as (
    select id, name, regist_time
    from users
    where regist_time > date_sub(current_date, 30 * 3)
)

-- last month orders
, order_cte as (
    select id, user_id, amount
    from orders
    where pay_time > date_sub(current_date, 30)
)

-- Total order amount in last 3 months registered users
insert overwrite target_table
select u.id
     , u.name
     , sum(o.amount) as total_amount
from user_cte u
join order_cte o on o.user_id = u.id
group by u.id, u.name
```

**Comment by zhongjiajie** [comment]
After I discuss with @boy-xiaozhang , I know that we could not only parse `[users, orders] -> target_table`, but also could get CTE clause name too, `[users, orders, user_cte, order_cte] -> target_table`. So I think it is better to change the default behavior by using configuration, to auto recommend CTE clause or not. WDYT @boy-xiaozhang @lenboo

**Comment by boy-xiaozhang** [comment]
> @lenboo Did you ask whether sql parser could parse below sql script or not?
> 
> ```sql
> -- Can the following sql script parser to the following dependencies?
> -- users -> target_table
> -- orders -> target_table
> 
> -- last 3 months registered users
> with user_cte as (
>     select id, name, regist_time
>     from users
>     where regist_time > date_sub(current_date, 30 * 3)
> )
> 
> -- last month orders
> , order_cte as (
>     select id, user_id, amount
>     from orders
>     where pay_time > date_sub(current_date, 30)
> )
> 
> -- Total order amount in last 3 months registered users
> insert overwrite target_table
> select u.id
>      , u.name
>      , sum(o.amount) as total_amount
> from user_cte u
> join order_cte o on o.user_id = u.id
> group by u.id, u.name
> ```

After my test, I tested all kinds of complex CTE statements, so far it can be parsed.

**Comment by boy-xiaozhang** [comment]
> After I discuss with @boy-xiaozhang , I know that we could not only parse `[users, orders] -> target_table`, but also could get CTE clause name too, `[users, orders, user_cte, order_cte] -> target_table`. So I think it is better to change the default behavior by using configuration, to auto recommend CTE clause or not. WDYT @boy-xiaozhang @lenboo

We should give the current function to that role to complete, master or worker or api server

**Comment by zhongjiajie** [comment]
Yeah, but I mean we should add some configuration to decide auto recommend should only `[users, orders]` or including CTE clause `[users, orders, user_cte, order_cte]`

**Comment by wangqinghuan** [comment]
It's better if we support extract field dependency except table dependency from SQL.

**Comment by zhongjiajie** [comment]
ping @boy-xiaozhang are you still work on this?

**Comment by boy-xiaozhang** [comment]
![image](https://user-images.githubusercontent.com/60912722/173011467-851e3c16-6891-4445-a346-94167cdd75cf.png)

Hi I also want to discuss about automated dag. I hope to name it automated dag parsing and parsing dag to help users automatically recommend and evaluate the value of tasks.

**Comment by zhongjiajie** [comment]
> ![image](https://user-images.githubusercontent.com/60912722/173011467-851e3c16-6891-4445-a346-94167cdd75cf.png)
> 
> Hi I also want to discuss about automated dag. I hope to name it automated dag parsing and parsing dag to help users automatically recommend and evaluate the value of tasks.

I wonder whether we parse all task types or only some of the types. we can only support few of them if it is difficlut to support all types

**Comment by boy-xiaozhang** [comment]
> > ![image](https://user-images.githubusercontent.com/60912722/173011467-851e3c16-6891-4445-a346-94167cdd75cf.png)
> > Hi I also want to discuss about automated dag. I hope to name it automated dag parsing and parsing dag to help users automatically recommend and evaluate the value of tasks.
> 
> I wonder whether we parse all task types or only some of the types. we can only support few of them if it is difficlut to support all types

hi @zhongjiajie I have a new idea now, but I need to discuss it in the meeting, and I will set aside an interface to expand all tasks that support source->target,if source->target is not supported, users can fill in it by themselves.,I will give default support sql task,sqoop task,seatunnel task,datax task

**Comment by zhongjiajie** [comment]
Hi @caishunfeng @SbloodyS , it seems @boy-xiaozhang has some idea about adding a dependence hook to the task plugin and want to call in api server when users save task. do you have any great idea to do that?

**Comment by boy-xiaozhang** [comment]
> Hi @caishunfeng @SbloodyS , it seems @boy-xiaozhang has some idea about adding a dependence hook to the task plugin and want to call in api server when users save task. do you have any great idea to do that?

Dear brothers, do you have any good ideas? My idea is to make the dolphinscheduler task parser into plugin and couple them into the task plugin. In this way, users can make their own extensions for those with task source and  task target. However, if they do so, the analysis of this work may have to be handed over to the worker, so they have to request the worker when the task is saved and when depend on recommendation, which is also more troublesome, do you have any good suggestions

**Comment by SbloodyS** [comment]
I do not have any good suggestions. Do any others have any good suggestions?

**Comment by EricGao888** [comment]
> > Hi @caishunfeng @SbloodyS , it seems @boy-xiaozhang has some idea about adding a dependence hook to the task plugin and want to call in api server when users save task. do you have any great idea to do that?
> 
> Dear brothers, do you have any good ideas? My idea is to make the dolphinscheduler task parser into plugin and couple them into the task plugin. In this way, users can make their own extensions for those with task source and task target. However, if they do so, the analysis of this work may have to be handed over to the worker, so they have to request the worker when the task is saved and when depend on recommendation, which is also more troublesome, do you have any good suggestions

May I ask whether this feature will be applied to all types of tasks or only sql related tasks?

**Comment by zhongjiajie** [comment]
> > > Hi @caishunfeng @SbloodyS , it seems @boy-xiaozhang has some idea about adding a dependence hook to the task plugin and want to call in api server when users save task. do you have any great idea to do that?
> > 
> > 
> > Dear brothers, do you have any good ideas? My idea is to make the dolphinscheduler task parser into plugin and couple them into the task plugin. In this way, users can make their own extensions for those with task source and task target. However, if they do so, the analysis of this work may have to be handed over to the worker, so they have to request the worker when the task is saved and when depend on recommendation, which is also more troublesome, do you have any good suggestions
> 
> May I ask whether this feature will be applied to all types of tasks or only sql related tasks?

@boy-xiaozhang want to add some hook or interface in base task class, which can beimplement tasks if they can be auto dependence. but currently will only work on SQL like task
