### ISSUE TITLE
[bug] [Alert] set timeout warnning but warnning in start！

### ISSUE THREAD

**Issue by fengzi2** [apache/dolphinscheduler#7165]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

we set timeout warnning, and use dingding robot do send message to me , but this warnning message is send to me  in start the job flow,in this time ,this flow is not timeout ,this flow is only start in few seconds
i find when we set the max minutes:999999999,the timeout message will not be send ,but when we set any minutes less then 999999999,it will be send timeout warnning message to me by dingding robot 
the version is 2.0.0

### What you expected to happen

i think when we set timeout warnning in 20 minutes ,we cannot receive the timeout warnning message when we start job flow few seconds ,we receive this timeout warnning message will be 20 minutes later 

### How to reproduce

use dingding robot ,and set timeout warnning, and start this job flow,it will happen 

### Version

2.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
this bug have fixed in 2.0.2, close it.
