### ISSUE TITLE
[Bug] [dolphinscheduler-api] Delete the running workflow instance. The task instance was not deleted

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#7171]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Delete the workflow instance that is running, ready to pause, ready to stop and resume fault tolerance. The task is not deleted

![Uploading image.png…]()

### Version

2.0.1

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
This bug had been fixed in dev. So the issue will be closed. You can check it again.
