### ISSUE TITLE
[Bug] [docs-zh] The markdown bold syntax in the document does not take effect

### ISSUE THREAD

**Issue by Lucaszlei** [apache/dolphinscheduler#7193]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The markdown bold syntax in the document does not take effect.
[文档连接](https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/architecture/designplus.html)

<img width="837" alt="图片" src="https://user-images.githubusercontent.com/56599784/144751468-b50bd07e-688a-4b99-9faa-1db1eccc3418.png">

### What you expected to happen

Should be bolded under correct circumstances

### How to reproduce

None

### Version

2.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Lucaszlei** [comment]
pr link: https://github.com/apache/dolphinscheduler-website/pull/562

**Comment by zhongjiajie** [comment]
@CalvinKirs Please close this issue , it done in apache/dolphinscheduler-website#562
