### ISSUE TITLE
[Bug] update from 1.3.8 to 2.0.0 can't show task instance and process instance list

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#7202]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

update from 1.3.8 to 2.0.0 can't show task instance and process instance list

### What you expected to happen

how to find the reason?

### How to reproduce

update from 1.3.8 to 2.0.0 

### Version

2.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lordk911** [comment]
because when get task instance list it will use table t_ds_task_instance left join the new add table t_ds_task_definition_log, but there is a where statment to filter t_ds_task_definition_log. 
to make it work , Move the WHERE condition to the JOIN

**Comment by caishunfeng** [comment]
> because when get task instance list it will use table t_ds_task_instance left join the new add table t_ds_task_definition_log, but there is a where statment to filter t_ds_task_definition_log. to make it work , Move the WHERE condition to the JOIN

The effect is the same, which may not be the reason. Can you provide more info and how to reproduce it?

**Comment by lordk911** [comment]
> > because when get task instance list it will use table t_ds_task_instance left join the new add table t_ds_task_definition_log, but there is a where statment to filter t_ds_task_definition_log. to make it work , Move the WHERE condition to the JOIN
> 
> The effect is the same, which may not be the reason. Can you provide more info and how to reproduce it?

just upgrade from 1.x to 2.0.0 , the **history** of task instance and process instance list is gone. the newly added instance list will be fine.

**Comment by lordk911** [comment]
https://stackoverflow.com/questions/2700354/left-join-not-returning-all-rows

**Comment by lenboo** [comment]
Since from 1 X to 2 X is a huge change, so the workflow instance cannot support upgrading
