### ISSUE TITLE
[Bug] [Process definition] There is a problem with the location of the import process node.

### ISSUE THREAD

**Issue by songjianet** [apache/dolphinscheduler#7203]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The import process does not render the nodes in the workflow according to the coordinate position in the file.

![image](https://user-images.githubusercontent.com/19239641/144801054-e7ff9f02-dc71-4e34-95c3-0f331c3c2660.png)

### What you expected to happen

The node position is not rendered based on coordinates.

### How to reproduce

Upload the workflow file and click on the workflow details.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I will check this issue.

**Comment by zhongjiajie** [comment]
> I will check this issue.

I assigned this issue to you @calvinjiang
