### ISSUE TITLE
[Bug] [dolphinscheduler-api] The alarm group is not displayed in the workflow instance

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#7215]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/95271106/144812551-32131411-298f-4968-995b-9a96c1853241.png)

### Version

2.0.1-prepare

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will solve

**Comment by caishunfeng** [comment]
Hi @songjianet Is this issue solved?
