### ISSUE TITLE
[Improvement] [dolphinscheduler-api] The alarm instance pages are sorted in reverse order according to the update time

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#7227]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/95271106/144959320-053fb083-290b-4e26-986a-9c9637bb57de.png)

### Version

dev

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RedemptionC** [comment]
what's the desired behavior ? sorted in descending order?

**Comment by jim-parsons** [comment]
I can try, and optimize the sql by the way

@CalvinKirs 

![image](https://user-images.githubusercontent.com/20239172/145510012-43e7c751-4ab1-42e9-99b4-f5233000c0d1.png)

**Comment by davidzollo** [comment]
> I can try, and optimize the sql by the way
> 
> @CalvinKirs
> 
> ![image](https://user-images.githubusercontent.com/20239172/145510012-43e7c751-4ab1-42e9-99b4-f5233000c0d1.png)

I have assigned to you, I am looking forward to your PR.

**Comment by lenboo** [comment]
@tangchunbo Hello, do you have any difficulties with this problem ?

**Comment by jim-parsons** [comment]
sorry i just had a vocation, now i am committing, ths

>
