### ISSUE TITLE
[Bug] [dolphinscheduler-ui] When editing the timing, the alarm group displays 0

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#7241]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/95271106/145004359-c6d4333c-3085-4738-8a84-7a1bd08332fb.png)

### Version

2.0.1-prepare

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will solve
