### ISSUE TITLE
[Bug] [UI] Why upgrade the node version 

### ISSUE THREAD

**Issue by brave-lee** [apache/dolphinscheduler#7252]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I find that many people encounter front-end compilation failure. I don't know why they upgrade the `node` version from v12.20.2 to v14.15.1, but the `npm` version remains unchanged

### What you expected to happen

I want to know why.

### How to reproduce

ui/pom.xml

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
@songjianet please task a look.
