### ISSUE TITLE
[Bug] [deploy] When starting and stopping all servers, the api service prompt information is inaccurate

### ISSUE THREAD

**Issue by Lucaszlei** [apache/dolphinscheduler#7259]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When using stop-all.sh or start-all.sh to start and stop all services, api-server prompts an error.
![Snipaste_2021-12-08_10-58-56](https://user-images.githubusercontent.com/56599784/145140615-b9eb6b0d-6006-4255-8744-7484656e644c.png)

The problem also exists in the dev branch.

### What you expected to happen

When starting and stopping the api-server service, you should print api-server is stopping/starting.

### How to reproduce

exec stop-all.sh or start-all.sh

### Version

1.3.9

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good job, I have assigned this issue to you
