### ISSUE TITLE
[Feature][task] rename task node 'PIGEON' to 'TIS'

### ISSUE THREAD

**Issue by baisui1981** [apache/dolphinscheduler#7265]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

as you konw , a new task node 'PIGEON' has been add in the taskbar in DS release version:2.0, the task node `PIGEON` is dedicated to wrapped the [TIS](http://tis.pub/) which is focuse on agile data movement .

Originally, I wanted to name the new task node TIS，but at then the open source protocol of TIS is AGLP  ，it is inconsistent with Apache2 protocol, as a result ，the name of new task node can only use a strange name with “PIGEON”.

Fortunately，TIS has changed open source protocol to [Apache2](https://github.com/qlangtech/tis/blob/master/LICENSE),so I wanted to restore the name to TIS

thanks a lot
 

### Related issues

https://github.com/apache/dolphinscheduler/issues/5992

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
hi @baisui1981 , I think the `PIGEON` is a universal websocket way for DS, and TIS is one of the remote servers.
So they are not the same thing.  What do you think?

**Comment by baisui1981** [comment]
> hi @baisui1981 , I think the `PIGEON` is a universal websocket way for DS, and TIS is one of the remote servers. So they are not the same thing. What do you think?

Thanks for your reply.Actually, I am the core developer of `PIGEON` node, When the initial PR was submitted, the node name was indeed called TIS, but it was changed to `PIGEON` because of the open source protocol of TIS is inconsist with apache2.

you can review the code [PigeonTask.java](https://github.com/apache/dolphinscheduler/blob/11844415b0d71711ecc0942c0f55651b7db6fd83/dolphinscheduler-task-plugin/dolphinscheduler-task-pigeon/src/main/java/org/apache/dolphinscheduler/plugin/task/pigeon/PigeonTask.java#L77)
,there are 3 steps to cooperate with outter system like TIS：
- trigger a new job which is predefined in TIS.
- poll the executing task status which is running in TIS. Quit once find  status is success or failure.
- collect the job executing log by WebSocket（WebSocket is just one part of PIGEON）

All interface parameters interacting with TIS are deeply coupled with TIS. To be honest, it is difficult for PIGEON to have other application scenarios except docking with TIS, so I think it is appropriate to replace the name of PIGEON with TIS
