### ISSUE TITLE
[Bug] [docker 2.0.0-release] the image in docker run fail

### ISSUE THREAD

**Issue by RedhotYuan** [apache/dolphinscheduler#7267]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

According to the description of this document: QuickStart in docker, I use the second way to deploy dolphinscheduler, but in step 5, docker run fail, My configuration does not take effect.
My command:
docker run -d --name dolphinscheduler \
-e DATABASE_HOST="172.19.223.108" -e DATABASE_PORT="5432" -e DATABASE_DATABASE="ds_db" \
-e DATABASE_USERNAME="ds" -e DATABASE_PASSWORD="123456" \
-e ZOOKEEPER_QUORUM="172.19.224.108:2181" \
-p 12345:12345 \
apache/dolphinscheduler:2.0.0 all

But the log print :
![image](https://user-images.githubusercontent.com/95666144/145179327-5a274910-07bf-4f6c-b127-3eb78b8065a6.png)

It is still the default configuration.

### What you expected to happen

Make my configuration effective.

### How to reproduce

not use  default  configure

```
docker run -d --name dolphinscheduler \
-e DATABASE_HOST="192.168.x.x" -e DATABASE_PORT="5432" -e DATABASE_DATABASE="dolphinscheduler" \
-e DATABASE_USERNAME="test" -e DATABASE_PASSWORD="test" \
-e ZOOKEEPER_QUORUM="192.168.x.x:2181" \
-p 12345:12345 \
apache/dolphinscheduler:1.3.9 all
```

database username test and password test need to be replaced with your actual PostgreSQL username and password, 192.168.x.x need to be replaced with your relate PostgreSQL and ZooKeeper host IP

### Version

2.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
@RedhotYuan 
Please check this in 2.0.2.  Reopen it if some problems are found.
