### ISSUE TITLE
[Bug] [SQL-task]Sql_task Cannot obtain the mysql driver package

### ISSUE THREAD

**Issue by nana7miAva** [apache/dolphinscheduler#7269]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

部署完成,启动测试sql_task的时候
![image](https://user-images.githubusercontent.com/88922651/145193653-b18a823a-dba1-4c54-88ac-a5cc40600839.png)

### What you expected to happen

资源注册中心可以成功连接到mysql,那么执行sql_task的时候应该也是可以的.

### How to reproduce

在解压之后的dolphinscheduler lib里面已经手动添加了mysql的驱动包,安装之后的ds2目录lib下也是有这个驱动包的,在web界面上 数据源连接mysql也可以连接成功,但是任务一配到sql节点 就报错没有jdbc驱动包.

### Version

2.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Narcasserun** [comment]
You can put the driver package in the lib/plugin/task/sql directory

**Comment by yueyinsheng** [comment]
You can put the driver package in the lib/plugin/task/sql directory      It's ok

**Comment by nana7miAva** [comment]
> 可以把驱动包放在lib/plugin/task/sql目录下

ok

**Comment by lenboo** [comment]
already fix, close it.
