### ISSUE TITLE
[Bug] [dolphinscheduler-api] In the process alarm message, projectid is 0 

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#7284]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/95271106/145352078-31533d62-de6f-4bb2-9ef5-a18fcaf6bca0.png)
The projectid should be the project id associated with the process

### Version

2.0.1-prepare

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
I will fix it.
