### ISSUE TITLE
[Bug] [dolphinscheduler-api] The task timed out and no mail was sent

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#7285]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The task timed out and no mail was sent
![image](https://user-images.githubusercontent.com/95271106/145353481-4574aadb-f47d-4e57-b38a-f0b9b78ac602.png)

### Version

2.0.1-prepare

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
done.
