### ISSUE TITLE
[Bug] [dolphinscheduler-api] Edit the workflow instance without checking “Whether to update the process definition”. The workflow instance is not updated when saving

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#7286]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Edit the workflow instance without checking “Whether to update the process definition”. The workflow instance is not updated when saving

![image](https://user-images.githubusercontent.com/95271106/145354702-00827152-05d5-497b-b4eb-47d3a071129f.png)

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
@JinyLeeChina Hi, Jiny, can you have a look at this problem?

**Comment by brave-lee** [comment]
OK, I will contribute a PR to fix it
