### ISSUE TITLE
[Bug] [dolphinscheduler-master] master.exec.threads、master.exec.task.num isn't valid  in ./conf/master.properties 

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#7287]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

master.exec.threads、master.exec.task.num isn't valid  in ./conf/master.properties 
![image](https://user-images.githubusercontent.com/95271106/145357820-e8cc8066-89c0-4102-8349-a63f0845ed22.png)

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
Could you provide more details about this issue?

**Comment by lenboo** [comment]
In 2.0.1.  DolphinScheduler is not restricted by exec.number and task.number, so we can change the description of both configurations
