### ISSUE TITLE
[Feature][dolphinscheduler-api] The default alarm group should not be deleted, and add the alarm instance field in the alarm group list

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#7288]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1.The default alarm group should not be deleted,Because the alarm notification of master and worker fault tolerance is sent by the default alarm group

2.add the alarm instance field in the alarm group list
![image](https://user-images.githubusercontent.com/95271106/145358619-2285f70a-f546-4331-9bb7-de52a108f262.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I will fix this issue.

**Comment by calvinjiang** [comment]
I found that  the usage of the default alarm group id exists in the class of ProcessAlertManager. So the default alarm group shouldn't be removed.
![image](https://user-images.githubusercontent.com/4928204/148739276-16bb33ba-1178-434a-a91c-3647e3a72a94.png)
