### ISSUE TITLE
[Bug] [Module Name] Bug title sql task error: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

### ISSUE THREAD

**Issue by Notbad1005** [apache/dolphinscheduler#7302]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Hi, Im's testing the function of dolphinscheduler2.0 and find the issue of mysql that when I execute the task of sql query from mysql, the result is that it cannot find com.mysql.jdbc.driver even though I put mysql-connector-java-8.0.27.jar into dolphinscheduler/lib. Howerver, Im's able to connect mysql by the way of datasource

### What you expected to happen

[ERROR] 2021-12-09 21:15:26.542  - [taskAppId=TASK-3797991916704_1-29-37]:[210] - execute sql error: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
[ERROR] 2021-12-09 21:15:26.543  - [taskAppId=TASK-3797991916704_1-29-37]:[161] - sql task error: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

I think it's the issue of compatibility between the version of mysql server and mysql jdbc driver

### How to reproduce

we can test a demo about sql with the statement of sql

### Version

2.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
Please put the driver package under the path lib/plugin/task/sql

**Comment by zhuangchong** [comment]
Similar problems: #7330

**Comment by Notbad1005** [comment]
Thank you, I will try it



At 2021-12-10 18:49:27, "Kerwin" ***@***.***> wrote:

Please put the driver package under the path lib/plugin/task/sql

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lenboo** [comment]
close duplicate issue
