### ISSUE TITLE
[Feature][e2e] datasource  test cases

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#7311]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

|Task status | function module | test point | priority | service |  test  steps  |  expected           results | actual results | remarks|
| ----------- | ----- | ---------------- | --- | ------- | --------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- | ---- | -- |
|<ul><li>[ ] finish</li></ul> | data source list | create MySQL data source | P1 | start API service | 1 Enter the data source center page and click "create data source" to pop up a pop-up box<br>2 Select MySQL<br>3 as the data source type Edit data source information<br>4 Click the "test connection" button to test the connection<br>5 Click "submit" | 1 The test connection failed and the data source information cannot be saved<br>2 Test connection passed, save data source information, t\_ ds\_ Add a new data item to the datasource table|
|<ul><li>[ ] finish</li></ul> | data source list | create PostgreSQL data source | P1 | start API service | 1 Enter the data source center page and click "create data source" to pop up a pop-up box<br>2 Select PostgreSQL as the data source type (database name is not verified) < br > 3 Edit data source information<br>4 Click the "test connection" button to test the connection<br>5 Click "submit" | 1 The test connection failed and the data source information cannot be saved<br>2 Test connection passed, save data source information, t\_ ds\_ Add a new data item to the datasource table|
|<ul><li>[ ] finish</li></ul> | data source list | create hive / impala data source | P1 | start API service | 1 Enter the data source center page and click "create data source" to pop up a pop-up box<br>2 Select hive / impala<br>3 as the data source type Edit data source information<br>4 Click the "test connection" button to test the connection<br>5 Click "submit" | 1 The test connection failed and the data source information cannot be saved<br>2 Test connection passed, save data source information, t\_ ds\_ Add a new data item to the datasource table|
|<ul><li>[ ] finish</li></ul> | data source list | create spark data source | P1 | start API service | 1 Enter the data source center page and click "create data source" to pop up a pop-up box<br>2 Select spark<br>3 as the data source type Edit data source information<br>4 Click the "test connection" button to test the connection<br>5 Click "submit" | 1 The test connection failed and the data source information cannot be saved<br>2 Test connection passed, save data source information, t\_ ds\_ Add a new data item to the datasource table|
|<ul><li>[ ] finish</li></ul> | data source list | create Clickhouse data source | P1 | start API service | 1 Enter the data source center page and click "create data source" to pop up a pop-up box<br>2 Select Clickhouse<br>3 as the data source type Edit data source information<br>4 Click the "test connection" button to test the connection<br>5 Click "submit" | 1 The test connection failed and the data source information cannot be saved<br>2 Test connection passed, save data source information, t\_ ds\_ Add a new data item to the datasource table|
|<ul><li>[ ] finish</li></ul> | data source list | create Oracle data source | P1 | start API service | 1 Enter the data source center page and click "create data source" to pop up a pop-up box<br>2 Select Oracle<br>3 as the data source type Edit data source information<br>4 Click the "test connection" button to test the connection<br>5 Click "submit" | 1 The test connection failed and the data source information cannot be saved<br>2 Test connection passed, save data source information, t\_ ds\_ Add a new data item to the datasource table|
|<ul><li>[ ] finish</li></ul> | data source list | create sqlserver data source | P1 | start API service | 1 Enter the data source center page and click "create data source" to pop up a pop-up box<br>2 Select sqlserver<br>3 as the data source type Edit data source information<br>4 Click the "test connection" button to test the connection<br>5 Click "submit" | 1 The test connection failed and the data source information cannot be saved<br>2 Test connection passed, save data source information, t\_ ds\_ Add a new data item to the datasource table|
|<ul><li>[ ] finish</li></ul> | data source list | create DB2 Data Source | P1 | start API service | 1 Enter the data source center page and click "create data source" to pop up a pop-up box<br>2 Select DB2 as the data source type<br>3 Edit data source information<br>4 Click the "test connection" button to test the connection<br>5 Click "submit" | 1 The test connection failed and the data source information cannot be saved<br>2 Test connection passed, save data source information, t\_ ds\_ Add a new data item to the datasource table|
|<ul><li>[ ] finish</li></ul> | data source list | cancel creating data source | P3 | start API service | 1 Enter the data source center page and click "create data source" to pop up a pop-up box<br>2 Select a data source type<br>3 Edit data source information<br>4 Click "Cancel" to cancel the creation of data source|
|<ul><li>[ ] finish</li></ul> | data source list | view data source parameters | P3 | start API service | 1 Enter the data source center page, click the "click to view" button under the data source parameters | display the database related information, and password encryption ||
|<ul><li>[ ] finish</li></ul> | data source list | edit data source | P1 | start API service | 1 Enter the data source center page and click Edit to open the edit data source pop-up box<br>2 Edit data source information<br>3 Click the "test connection" button to test the connection<br>4 Click the "Edit" button < br > | 1 If the test connection fails, the data source information will not be updated<br>2 Test connection passed, t\_ ds\_ The datasource table updates the data source information|
|<ul><li>[ ] finish</li></ul> | data source list | cancel editing data source | P3 | start API service | 1 Enter the data source center page and click Edit to open the edit data source pop-up box<br>2 Edit data source information<br>3 Click the "Cancel" button < br > | cancel the data source editing, and the data source information will not be updated ||
|<ul><li>[ ] finish</li></ul> | data source list | delete data source | P1 | start API service | enter the data source center page and click the "delete" button | delete data source ||
|<ul><li>[ ] finish</li></ul> | data source list | query data source | P1 | start API service | enter the data source center page, enter the data source name, and click the "query" button | data source name supports fuzzy query: < br > 1 Query no data, and the data source list displays no data<br>2 The query has data, and the data source list displays the data correctly|
|<ul><li>[ ] finish</li></ul> | data source list | verify paging controls, no more than 10 | P2 | start API service | 1 Select 10 pieces / page, no more than 10 pieces of data, and view the pagination display<br>2 Select 30 pieces / page, no more than 30 pieces of data, and view the pagination display<br>3 Select 50 pieces / page, no more than 50 pieces of data, and view the pagination display | 1 Select 10 pieces / page, no more than 10 pieces of data, and 1 page displays<br>2 Select 30 pieces / page, no more than 30 pieces of data, and 1 page displays<br>3 Select 50 pieces / page, no more than 50 pieces of data, and one page displays ||
|<ul><li>[ ] finish</li></ul> | data source list | verify paging controls, more than 10 | P2 | start API service | 1 Select 10 pieces / page, more than 10 pieces of data, and view the pagination display<br>2 Select 30 pieces / page and more than 30 pieces of data to view the pagination display<br>3 Select 50 pieces / page, more than 50 pieces of data, and view the pagination display | 1 Select 10 pieces / page. If there are more than 10 pieces of data, turn the page to display<br>2 Select 30 pieces / page. If more than 30 pieces of data are selected, the page will turn to display<br>3 Select 50 pieces / page, and more than 50 pieces of data will be displayed on the page|
|<ul><li>[ ] finish</li></ul> | data source list | verify the > button of paging control | P2 | start API service | click the > button to view paging display | page Jump to the next page ||
|<ul><li>[ ] finish</li></ul> | data source list | verify the < button of paging control | P2 | start API service | click the < button to view paging display | page Jump to the previous page ||
|<ul><li>[ ] finish</li></ul> | data source list | verify the input box of the paging control | P2 | start the API service | enter the number of pages, view the paging display | page Jump to the page where the page number is entered ||

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi, Create Mysql/Postgresql/SqlServer/Clickhouse data source and test connection has been done in #8085. Can you change these to completed? Thanks.

**Comment by zhuangchong** [comment]
datasource test case done.
