### ISSUE TITLE
[Feature][e2e] Resource Center test cases

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#7312]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

|Task status | number | function module | test point | priority | service |  test  steps  |  expected           results | actual results | remarks|
| -----------| -----  | ----- | ---------------- | --- | ------- | --------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- | ---- | -- |
|<ul><li>[ ] finish</li></ul> | 001 | file management | create folder | P1 | start API service, Hadoop file management service | 1 Enter the file management page and click the "create folder" button to enter the create folder page<br>2 Enter folder name and description<br>3 Click the "create" button | successfully create the folder|
|<ul><li>[ ] finish</li></ul> | 002 | file management | create multi-level folders | P1 | start the API service, Hadoop file management service | click the folder and create a folder or file under the folder < br > | 1 Successfully created folder or file under folder<br>2 Folders cannot be edited or downloaded|
|<ul><li>[ ] finish</li></ul> | 003 | file management | cancel folder creation | P2 | start API service and Hadoop file management service | 1 Click create folder and enter the folder name and description<br>2 Click the "Cancel" button | cancel the creation of the folder|
|<ul><li>[ ] finish</li></ul> | 004 | file management | folder renaming | P1 | start API service, Hadoop file management service | 1 Click the "Rename" button of the folder to pop up the rename pop-up box<br>2 Enter a name and description<br>3 Click the "Rename" button | 1 Folder renamed successfully<br>2 If the file under the folder is referenced by the workflow task, the folder name in the task is the renamed name<br>3 The folder name of authorized resources in the user center is the renamed name|
|<ul><li>[ ] finish</li></ul> | 005 | file management | cancel folder renaming | P2 | start API service and Hadoop file management service | 1 Click the "Rename" button of the folder to pop up the rename pop-up box<br>2 Enter a name and description<br>3 Click the "Cancel" button | cancel the folder renaming, and the folder name remains unchanged ||
|<ul><li>[ ] finish</li></ul> | 006 | file management | delete folder | P1 | start API service, Hadoop file management service | click the "delete" button of folder and click the "OK" button | 1 If the file under the folder is referenced by the online workflow, the folder cannot be deleted<br>2 The file under the folder is not referenced by the task or the referenced workflow has been offline. The folder has been deleted successfully|
|<ul><li>[ ] finish</li></ul> | 007 | file management | cancel deleting the folder | P2 | start the API service, Hadoop file management service | click the "delete" button of the folder and click "Cancel" Button  | don’t delete folder|
|<ul><li>[ ] finish</li></ul> | 008 | file management | create file | P1 | start API service, Hadoop file management service | 1 Enter the file management page and click the "create file" button to enter the create file page<br>2 Edit file name, description (not required), file content and select file format<br>3 Click the "create" button | 1 Successfully created file, t\_ ds\_ Add a new data item in the resources table, type = 0<br>2 Add a new file in the resource under HDFS # or S3 # distributed file systems<br>3 If the creating user is admin and there is no associated tenant, the file cannot be created; The admin user can create a file after associating with the tenant|
|<ul><li>[ ] finish</li></ul> | 009 | file management | create a file | P1 | start the API service and Hadoop file management service | 1 Enter the file management page, select a folder, and click the "create file" button to enter the create file page<br>2 Edit file name, description (not required), file content and select file format<br>3 Click the "create" button | 1 Successfully created file, t\_ ds\_ Add a new data item in the resources table, type = 0<br>2 Add a / folder / file in the resource under HDFS # or S3 # distributed file systems<br>3 If the creating user is admin and there is no associated tenant, the file cannot be created; The admin user can create a file after associating with the tenant|
|<ul><li>[ ] finish</li></ul> | 010 | file management | cancel file creation | P2 | start API service, Hadoop file management service | 1 Enter the file management page and click the "create file" button to enter the create file page<br>2 Edit file name, description (not required), file content and select file format<br>3 Click the "Cancel" button | cancel the creation of the file|
|<ul><li>[ ] finish</li></ul> | 011 | file management | ordinary users upload files, less than 1G | P1 | start API service and Hadoop file management service | 1 Ordinary users enter the file management page and click the "upload file" button to pop up a pop-up box<br>2 Upload files smaller than 1G<br>3 Click the "submit" button <br> | 1. File uploaded successfully, t_ ds_ Add a new piece of data in the resources table, type = 0<br>2. Add a new file in the resource under HDFS or S3 distributed file systems|
|<ul><li>[ ] finish</li></ul> | 012 | file management | ordinary users upload files greater than 1G | P2 | start API service and Hadoop file management service | 1 Ordinary users enter the file management page and click the "upload file" button to pop up a pop-up box<br>2 Upload files larger than 1G<br>3 Click the "submit" button < br > | file upload fails, and a prompt | ||
|<ul><li>[ ] finish</li></ul> | 013 | file management | admin users upload files, less than 1G | P1 | start API service and Hadoop file management service | 1 The administrator admin enters the file management page and clicks the "upload file" button to pop up a pop-up box<br>2 Upload files smaller than 1G<br>3 Click the "submit" button < br > | 1 If the administrator is associated with the tenant and the file is uploaded successfully, t\_ ds\_ Add a new data item in the resources table, type = 0<br>2 Add a new file in the resource under HDFS # or S3 # distributed file systems<br>3 If the administrator is not associated with a tenant and cannot upload files, a prompt will pop up | ||
|<ul><li>[ ] finish</li></ul> | 014 | file management | admin users upload files that are greater than 1G | P1 | start the API service, Hadoop file management service | ordinary users enter the file management page, select a folder, and click "upload files" |Successfully uploaded the file under this folder | ||
|<ul><li>[ ] finish</li></ul> | 015 | file management | cancel uploading files | P3 | start API service and Hadoop file management service | 1 Enter the file management page and click the "upload file" button to pop up a pop-up box<br>2 To upload a file less than 1G, click the "Cancel" button | cancel uploading the file ||
|<ul><li>[ ] finish</li></ul> | 016 | file management | edit file | P1 | start API service, Hadoop file management service | 1 Enter the file management page, click the "Edit" button or the file name link to enter the editing page<br>2 Edit file content<br>3 Click the "save" button | save the edited file content ||
|<ul><li>[ ] finish</li></ul> | 017 | file management | cancel file editing | P3 | start API service, Hadoop file management service | 1 Enter the document management page and click the "Edit" button to enter the editing page<br>2 Edit file content<br>3 Click the "back" button | do not save the edited file content ||
|<ul><li>[ ] finish</li></ul> | 018 | file management | rename | P1 | start API service, Hadoop file management service | 1 Enter the file management page and click the "Rename" button<br>2 Enter the name (required) and description (not required) in the "Rename" pop-up box<br>3 Click the "Rename" button < br > | the file is renamed successfully ||
|<ul><li>[ ] finish</li></ul> | 019 | file management | cancel renaming | P3 | start API service, Hadoop file management service | 1 Enter the file management page and click the "Rename" button<br>2 Enter the name (required) and description (not required) in the "Rename" pop-up box<br>3 Click the "Cancel" button < br > | cancel renaming ||
|<ul><li>[ ] finish</li></ul> | 020 | file management | download file | P1 | start API service, Hadoop file management service | enter the file management page and click "download" Button < br > | download file ||
|<ul><li>[ ] finish</li></ul> | 021 | file management | delete file | P1 | start API service, Hadoop file management service | enter the file management page, click "delete" button, click "OK" button < br > | 1 If the file is associated with an online task, it cannot be deleted; If the file is not associated with the online task, it will be deleted t\_ ds\_ This file of the resources table<br>2 Delete the files in the resource under HDFS | or S3 distributed file systems|
|<ul><li>[ ] finish</li></ul> | 022 | file management | cancel deleting files | P3 | start the API service, Hadoop file management service | enter the file management page, click the "delete" button and click "Cancel" Button < br > | do not delete file ||
|<ul><li>[ ] finish</li></ul> | 023 | file management | query file | P1 | start API service, Hadoop file management service | 1 Enter the file name<br>2 Click the "query" button | the file name supports fuzzy query: < br > 1 Query no data, and the file list displays no data temporarily<br>2 Query the data, and the file list displays the file data correctly|
|<ul><li>[ ] finish</li></ul> | 024 | file management | verify paging controls, no more than 10 | P2 | start API service and Hadoop file management service | 1 Select 10 pieces / page, no more than 10 pieces of data, and view the pagination display<br>2 Select 30 pieces / page, no more than 30 pieces of data, and view the pagination display<br>3 Select 50 pieces / page, no more than 50 pieces of data, and view the pagination display | 1 Select 10 pieces / page, no more than 10 pieces of data, and 1 page displays<br>2 Select 30 pieces / page, no more than 30 pieces of data, and 1 page displays<br>3 Select 50 pieces / page, no more than 50 pieces of data, and one page displays ||
|<ul><li>[ ] finish</li></ul> | 025 | file management | verify paging controls, more than 10 | P2 | start API service, Hadoop file management service | 1 Select 10 pieces / page, more than 10 pieces of data, and view the pagination display<br>2 Select 30 pieces / page and more than 30 pieces of data to view the pagination display<br>3 Select 50 pieces / page, more than 50 pieces of data, and view the pagination display | 1 Select 10 pieces / page. If there are more than 10 pieces of data, turn the page to display<br>2 Select 30 pieces / page. If more than 30 pieces of data are selected, the page will turn to display<br>3 Select 50 pieces / page, and more than 50 pieces of data will be displayed on the page|
|<ul><li>[ ] finish</li></ul> | 026 | file management | verify the > button of paging control | P2 | start API service, Hadoop file management service | click the > button, View the pagination display page and jump to the next page|
|<ul><li>[ ] finish</li></ul> | 027 | file management | verify the < button of paging control | P2 | start API service, Hadoop file management service | click the < button, View the pagination display page and jump to the previous page|
|<ul><li>[ ] finish</li></ul> | 028 | file management | verify the input box of paging control | P2 | start API service, Hadoop file management service | enter the number of pages, View pagination display | page Jump to the page where the page number is entered ||
|<ul><li>[ ] finish</li></ul> | 029 | UDF management - resource management | upload UDF resources | P1 | start API service, Hadoop file management service | 1 Enter the UDF management - resource management page, click the "upload UDF resources" button to upload files less than 1G<br>2 Click the "Upload" button to upload the file, and click the "confirm" button in the pop-up box | 1 File uploaded successfully, t\_ ds\_ Add a new data item in the resources table, type = 1<br>2 Add a new file | in the resource under HDFS | or | S3 distributed file systems|
|<ul><li>[ ] finish</li></ul> | 030 | P2 | start API service, Hadoop file management service | 1 Enter the UDF management - resource management page, click the "upload UDF resources" button to upload files larger than 1G<br>2 Click the "Upload" button to upload the file, and click the "confirm" button in the pop-up box | if the file upload fails, a prompt will pop up ||
|<ul><li>[ ] finish</li></ul> | 031 | UDF management - resource management | cancel uploading UDF files | P3 | start API service and Hadoop file management service | 1 Enter the UDF management - resource management page, click the "upload UDF resources" button to upload files less than 1G<br>2 Click the "Upload" button, click the "Cancel" button in the pop-up window | cancel uploading UDF functions ||
|<ul><li>[ ] finish</li></ul> | 032 | UDF management - resource management | create folder | P1 | start API service, Hadoop file management service | 1 Enter the UDF management - resource management page and click the "create folder" button<br>2 Enter folder name and description (not required) < br > 3 Click the "create" button to successfully create the folder|
|<ul><li>[ ] finish</li></ul> | 033 | UDF management - resource management | cancel folder creation | P3 | start API service and Hadoop file management service | 1 Enter the UDF management - resource management page and click the "create folder" button<br>2 Enter folder name and description (not required) < br > 3 Click the "Cancel" button | no folder has been created ||
|<ul><li>[ ] finish</li></ul> | 034 | UDF management - upload UDF resources | P1 | start API service and Hadoop file management service | 1 Enter the UDF management - resource management page, select a folder, upload UDF resources | successfully upload UDF resources ||
|<ul><li>[ ] finish</li></ul> | 035 | UDF management - resource management | rename | P1 | start API service, Hadoop file management service | 1 Enter UDF management - resource management page and click "Rename" button<br>2 Edit name (required), description (not required) < br > 2 Click the "Rename" button | 1 t\_ ds\_ resources. file\_ Name is updated to the new name<br>2 Change the file name in the resource under HDFS | or | S3 distributed file systems to the new name ||
|<ul><li>[ ] finish</li></ul> | 036 | UDF management - resource management | cancel renaming | P3 | start API service, Hadoop file management service | 1 Enter UDF management - resource management page and click "Rename" button<br>2 Edit name (required), description (not required) < br > 2 Click the "Cancel" button | UDF resource name will not be changed ||
|<ul><li>[ ] finish</li></ul> | 037 | UDF management - resource management | download | P1 | start the API service, Hadoop file management service | enter the UDF management - resource management page and click "download" Button | successfully download UDF resources 
|<ul><li>[ ] finish</li></ul> | 038 | UDF management - resource management | delete | P1 | start the API service and Hadoop file management service | enter the UDF management - resource management page and click "delete" Button | to delete UDF resources, you need to judge whether there are UDF functions in use. If there are UDF functions, they cannot be deleted. If not, they can be deleted|
|<ul><li>[ ] finish</li></ul> | 039 | UDF management - resource management | query | P1 | start the API service, Hadoop file management service | enter the UDF management - resource management page, enter the UDF resource name, and click the "query" button|
|<ul><li>[ ] finish</li></ul> | 040 | UDF management - resource management | verify paging controls, no more than 10 | P2 | start API service and Hadoop file management service | 1 Select 10 pieces / page, no more than 10 pieces of data, and view the pagination display<br>2 Select 30 pieces / page, no more than 30 pieces of data, and view the pagination display<br>3 Select 50 pieces / page, no more than 50 pieces of data, and view the pagination display | 1 Select 10 pieces / page, no more than 10 pieces of data, and 1 page displays<br>2 Select 30 pieces / page, no more than 30 pieces of data, and 1 page displays<br>3 Select 50 pieces / page, no more than 50 pieces of data, and one page displays ||
|<ul><li>[ ] finish</li></ul> | 041 | UDF management - resource management | verify paging controls, more than 10 | P2 | start API service and Hadoop file management service | 1 Select 10 pieces / page, more than 10 pieces of data, and view the pagination display<br>2 Select 30 pieces / page and more than 30 pieces of data to view the pagination display<br>3 Select 50 pieces / page, more than 50 pieces of data, and view the pagination display | 1 Select 10 pieces / page. If there are more than 10 pieces of data, turn the page to display<br>2 Select 30 pieces / page. If more than 30 pieces of data are selected, the page will turn to display<br>3 Select 50 pieces / page, and more than 50 pieces of data will be displayed on the page|
|<ul><li>[ ] finish</li></ul> | 042 | UDF management - resource management | verify the > button of paging control | P2 | start API service, Hadoop file management service | click the > button to view paging display | page Jump to the next page ||
|<ul><li>[ ] finish</li></ul> | 043 | UDF management - resource management | verify the < button of paging control | P2 | start API service, Hadoop file management service | click the < button to view paging display | page Jump to the previous page ||
|<ul><li>[ ] finish</li></ul> | 044 | UDF management - resource management | verify the input box of the paging control | P2 | start the API service, Hadoop file management service | enter the number of pages, view the paging display | jump to the page where the page number is entered |
|<ul><li>[ ] finish</li></ul> | 045 | UDF management - function management | create UDF function | P1 | start API service, Hadoop file management service | 1 Enter the UDF function page and click "create UDF function" to pop up a pop-up box<br>2 Edit UDF function information<br>3 Select UDF resources or upload resources<br>4 Click the "submit" button | t\_ ds\_ A new data entry is added to the UDFs table, and the UDF function is verified in the hive SQL task < br > ||
|<ul><li>[ ] finish</li></ul> | 046 | UDF management - function management | cancel the creation of UDF function | P3 | start API service and Hadoop file management service | 1 Enter the UDF function page and click "create UDF function" to pop up a pop-up box<br>2 Edit UDF function information<br>3 Select UDF resources or upload resources<br>4 Click the "submit" button | cancel the creation of UDF function ||
|<ul><li>[ ] finish</li></ul> | 047 | UDF management - function management | edit UDF function | P1 | start API service, Hadoop file management service | 1 Enter the UDF function page and click "button" to pop up a pop-up box<br>2 Edit UDF function information<br>3 Select UDF resources or upload resources<br>4 Click the "Edit" button | t\_ ds\_ UDFs table update data|
|<ul><li>[ ] finish</li></ul> | 048 | UDF management - function management | cancel editing UDF function | P3 | start API service and Hadoop file management service | 1 Enter the UDF function page and click "button" to pop up a pop-up box<br>2 Edit UDF function information<br>3 Select UDF resources or upload resources<br>4 Click "Cancel" to cancel editing UDF function|
|<ul><li>[ ] finish</li></ul> | 049 | UDF management - function management | delete UDF function | P1 | start API service, Hadoop file management service | enter UDF function page, click "button", click "delete" button | delete UDF function ||
|<ul><li>[ ] finish</li></ul> | 050 | UDF management - function management | query | P1 | start the API service, Hadoop file management service | enter the UDF function page, enter the UDF function name, and click the "query" button | UDF function name supports fuzzy query: < br > 1 Query no data, UDF function list displays no data<br>2 If the query has data, the UDF function list displays the data correctly|
|<ul><li>[ ] finish</li></ul> | 051 | UDF management - function management | verify paging controls, no more than 10 | P2 | start API service, Hadoop file management service | 1 Select 10 pieces / page, no more than 10 pieces of data, and view the pagination display<br>2 Select 30 pieces / page, no more than 30 pieces of data, and view the pagination display<br>3 Select 50 pieces / page, no more than 50 pieces of data, and view the pagination display | 1 Select 10 pieces / page, no more than 10 pieces of data, and 1 page displays<br>2 Select 30 pieces / page, no more than 30 pieces of data, and 1 page displays<br>3 Select 50 pieces / page, no more than 50 pieces of data, and one page displays ||
|<ul><li>[ ] finish</li></ul> | 052 | UDF management - function management | verify paging controls, more than 10 | P2 | start API service, Hadoop file management service | 1 Select 10 pieces / page, more than 10 pieces of data, and view the pagination display<br>2 Select 30 pieces / page and more than 30 pieces of data to view the pagination display<br>3 Select 50 pieces / page, more than 50 pieces of data, and view the pagination display | 1 Select 10 pieces / page. If there are more than 10 pieces of data, turn the page to display<br>2 Select 30 pieces / page. If more than 30 pieces of data are selected, the page will turn to display<br>3 Select 50 pieces / page, and more than 50 pieces of data will be displayed on the page|
|<ul><li>[ ] finish</li></ul> | 053 | UDF management - function management | verify the > button of paging control | P2 | start API service, Hadoop file management service | click the > button to view paging display | page Jump to the next page ||
|<ul><li>[ ] finish</li></ul> | 054 | UDF management - function management | verify the < button of paging control | P2 | start API service, Hadoop file management service | click the < button to view paging display | page Jump to the previous page ||
|<ul><li>[ ] finish</li></ul> | 055 | UDF management - function management | verify the input box of the paging control | P2 | start the API service, Hadoop file management service | enter the number of pages, view the paging display | jump to the page where the page number is entered 

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi, Create/Delete directory and create duplicated directory has been done in #7906. Can you change these to completed? Thanks.
