### ISSUE TITLE
ClassNotFoundException: org.postgresql.Driver、mysql。。。

### ISSUE THREAD

**Issue by ysfour** [apache/dolphinscheduler#7330]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

执行工作流任务报ClassNotFoundException: org.postgresql.Driver

### What you expected to happen

如何修复

### How to reproduce

运行apache/dolphinscheduler:2.0.0-alpha镜像

### Version

2.0.0-alpha

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
Please put the driver package under the path lib/plugin/task/sql
This problem has been fixed in version 2.0.1

**Comment by ysfour** [comment]
ok, thanks!
