### ISSUE TITLE
[DSIP-4][Feature][UI Next] A new version of the `UI` proposal.

### ISSUE THREAD

**Issue by songjianet** [apache/dolphinscheduler#7332]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

refactor reason
- Use the updated technology stack to solve the problem of not supporting the `m1` series chips directly from the root cause, and at the same time can improve the startup speed and build speed of the project.
- Solve the problem that some tools and dependencies used in existing projects are about to lose their maintenance.
- Standardize code writing to enhance control over code style and specifications.
- Solve the problem of style pollution caused by the styles in all `sfc` not using `scoped` in the project.
- `jquery` is no longer used in the project.
- Solve the problem of deep nesting of the directory hierarchy and irregular file storage in the project.
- Solve the problem of extensive use of absolute positioning in the project.
- Switching languages does not refresh the page.

Whether to use other methods to support `m1`

Try to upgrade the existing project by using `node16`, then you need to upgrade `node-sass7`, the new version of `node-sass7` also needs to depend on `node-gyp8`, correspondingly, you need to upgrade `sass-loader12`, and then `webpack4` does not To know these, you need to upgrade `webpack5`, and then the old version of `babel` is not supported, and then upgrade `babel`. After upgrading `babel`, it is found that the existing `element` and `vue` both use the old version of `babel`.

### Use case

use technology
- node16
- vue3
- vue-router4
- vueuse
- axios
- pinia
- vite
- scss
- naiveui
- pnpm
- data-fns
- ts+tsx

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by labbomb** [comment]
I want to be involved in this project.

**Comment by songjianet** [comment]
> I want to be involved in this project.

well done.

**Comment by calvinjiang** [comment]
Wow, This is an amazing proposal. I'd like to support.

**Comment by songjianet** [comment]
> Wow, This is an amazing proposal. I'd like to support.

thanks.

**Comment by devosend** [comment]
I am very interested in this, but I mainly use react.

**Comment by songjianet** [comment]
> I am very interested in this, but I mainly use react.

In fact, the problem is not particularly big, the refactoring of `vue3`+`tsx` is not very different.

**Comment by devosend** [comment]
ok，I hope to participate in it.

**Comment by songjianet** [comment]
> ok，I hope to participate in it.

well done.

**Comment by ljmiaoo** [comment]
I hope to participate in it

**Comment by songjianet** [comment]
> I hope to participate in it

No problem.

**Comment by zhongjiajie** [comment]
Hi @songjianet, FYI, I think this is a big change for our codebase, so I add labels `DSIP` for it.

**Comment by songjianet** [comment]
> Hi @songjianet, FYI, I think this is a big change for our codebase, so I add labels `DSIP` for it.

yeh

**Comment by shangeyao** [comment]
I hope to participate in the reactor about vue-router. There are still some problems now.

**Comment by songjianet** [comment]
> I hope to participate in the reactor about vue-router. There are still some problems now.

This is already being dealt with. You can look at other functions. Currently, it hasn't started writing for the page.

**Comment by labbomb** [comment]
> I hope to participate in the reactor about vue-router. There are still some problems now.

Welcome to participate. What problems did you find?

**Comment by devosend** [comment]
How to participate in the development of `UI Next`?

**Comment by songjianet** [comment]
> How to participate in the development of `UI Next`?

Add me WeChat 18802464247.

**Comment by zhongjiajie** [comment]
> How to participate in the development of `UI Next`?

Hi @devosend, maybe you should ping @songjianet to check if they are some task to do for next ui issue

**Comment by songjianet** [comment]
> > How to participate in the development of `UI Next`?
> 
> Hi @devosend, maybe you should ping @songjianet to check if they are some task to do for next ui issue

We have already made contact.

**Comment by devosend** [comment]
> > > How to participate in the development of `UI Next`?
> > 
> > 
> > Hi @devosend, maybe you should ping @songjianet to check if they are some task to do for next ui issue
> 
> We have already made contact.

yeah.

**Comment by zhongjiajie** [comment]
Well done, thanks everyone here
