### ISSUE TITLE
[Bug] [dolphinscheduler-api] Improve the prompt content for deleting a project that didn't exist

### ISSUE THREAD

**Issue by karen-liu01** [apache/dolphinscheduler#7340]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1、user B create a new project named "testdemo"
2、admin deleted the project successfully
3、user B delete “testdemo”，Click on the confirmation
4、page toast “project 0 not found”
<img width="665" alt="project1" src="https://user-images.githubusercontent.com/69795603/145697957-678dc41d-0cce-426e-bf9d-4739e3168d86.png">

### What you expected to happen

1、page toast “project has been deleted ”，and refresh this page

### How to reproduce

1、user B create a new project named "testdemo"
2、admin deleted the project successfully
3、user B delete “testdemo”，Click on the confirmation

### Anything else

2.0.1-prepare

### Version

2.0.1-prepare

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I will check this issue.
