### ISSUE TITLE
[Bug] [dolphinscheduler-ui] If the parameters of the query page are modified, requests are sent to the backend all time until whe number of page limit

### ISSUE THREAD

**Issue by karen-liu01** [apache/dolphinscheduler#7341]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. admin login 
2. search project  name in project page
3.  modify the pageNo parameter to any value (Is greater than 10)
eg http://ip:12345/dolphinscheduler/ui/#/projects/list?pageSize=10&pageNo=70&searchVal=
4. View page requests and log requests
![image](https://user-images.githubusercontent.com/55787491/145710663-6f891792-398e-42f9-8e31-7eaeb312993d.png)

### What you expected to happen

When the user first requests it，response contains the params  totalPage: 7 
When the user requests it a second time, the parameter pageNo should be changed to totalPage: 7 
![image](https://user-images.githubusercontent.com/55787491/145710681-6f8a4bbd-3232-42da-8c50-8360ff39a136.png)

### How to reproduce

1. admin login 
2. send a request  to this url  http://ip:12345/dolphinscheduler/ui/#/projects/list?pageSize=10&pageNo=70&searchVal=

### Anything else

2.0.1-prepare

### Version

2.0.1-prepare

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will handle.

**Comment by songjianet** [comment]
@karen-liu01 Is this the problem?
![a0d307858b7f22e805f17c40eb2e10d](https://user-images.githubusercontent.com/19239641/145820090-7cc71f07-9eab-475f-93a6-e20cd97e8197.png)

**Comment by karen-liu01** [comment]
The problem has been solved and verified
