### ISSUE TITLE
[Feature][UI] The page of task group

### ISSUE THREAD

**Issue by wangxj3** [apache/dolphinscheduler#7345]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Task group queue (TGQ) can limit the concurrency of taskInstance.TGQ also supports priority-based control, which ensures that important tasks can be executed first. Users can also execute a task compulsively, ignoring the TGQ.
This funciton of task group has two new page，one is the page of task group ,and the other is task group queue。One  modify page of task group。Has 10 interface ，7 new ，3 modify。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I'd like to develop these two pages.
