### ISSUE TITLE
[Feature][Python] Add workflow as code task type MR

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#7348]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add python api task type MR. sub task in #6407. we should cover all parameter from UI side and make it suitable for python.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
Please assign it to me if nobody do it. @zhongjiajie

**Comment by zhongjiajie** [comment]
For now, only you and me is work in Python API 😭 , and I current have to pay more attention to DolphinScheduler document and Python API document. So yes, I would assign to you and thanks.
