### ISSUE TITLE
[Feature][dev-2.0.2-prepare] cherry-pick pull requests from dev to 2.0.2-prepare

### ISSUE THREAD

**Issue by zwZjut** [apache/dolphinscheduler#7357]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

[Feature][dev-2.0.2-prepare] cherry-pick pull requests from dev to 2.0.2-prepare

### Related issues

https://github.com/apache/dolphinscheduler/pull/7238
https://github.com/apache/dolphinscheduler/pull/7192
https://github.com/apache/dolphinscheduler/pull/7158
https://github.com/apache/dolphinscheduler/pull/7109
https://github.com/apache/dolphinscheduler/pull/7082
https://github.com/apache/dolphinscheduler/pull/7080
https://github.com/apache/dolphinscheduler/pull/7072
https://github.com/apache/dolphinscheduler/pull/6808
https://github.com/apache/dolphinscheduler/pull/6780

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
It seems that all related PR are cherry-picked to 2.0.2. I would close this issue. If I'm wrong @zwZjut  could reopen it.
