### ISSUE TITLE
[Bug]  task count of Need fault tolerance is not zero while workflow count of Need fault tolerance is zero 

### ISSUE THREAD

**Issue by zwZjut** [apache/dolphinscheduler#7362]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

task count of Need fault tolerance is not zero while workflow count of Need fault tolerance is zero
![image](https://user-images.githubusercontent.com/13324943/145763119-4bb5daf3-9f09-4552-b954-11e4a7dabda9.png)

### What you expected to happen

the tasks of  state  "Need fault tolerance" is already completed ,so it should be set its real state.

### How to reproduce

 kill master node and worker node when workflow is shceduled

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zwZjut** [comment]
branch: 2.0.2-prepare

**Comment by songjianet** [comment]
I'll deal with it

**Comment by zwZjut** [comment]
> I'll deal with it

Not a front-end bug

**Comment by songjianet** [comment]
> > I'll deal with it
> 
> Not a front-end bug

ok

**Comment by lenboo** [comment]
@zwZjut Is  this issue need to be moved to branch dev?
