### ISSUE TITLE
[Bug] [dolphinscheduler-api] can not find process or task instance of the old version after upgrading to 2.0.0

### ISSUE THREAD

**Issue by Eonchpy** [apache/dolphinscheduler#7367]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I successfully upgrade dolphinscheduler from 1.3.8 to 2.0.0, however when checking the result  I found out that none process instance or task instance which submitted from the old version could be displayed, but actually they still exist in the database,  the reason seems to be because in _queryProcessInstanceListPaging_ the old version used _t_ds_process_instance.process_definition_id_ joined on _t_ds_process_definition.id_ but the new version used _t_ds_process_instance.process_definition_id_ joined on _t_ds_process_definition.code_.  Can we fix this by modifying the column 'process_definition_code' of table 't_ds_process_instance' from id to the new code or what should we do to fix this.  **BTW Is this means that the process submitted during upgrading could not been recovery after successfully upgraded.**
![3be41ce5692edb263b14efaad2af0ad](https://user-images.githubusercontent.com/26398373/145776628-1776d69f-5e00-4ea8-bbd8-eba4cdd66c9e.png)
![YOK6BVR%_ 7Q} 2IC$%C@%Q](https://user-images.githubusercontent.com/26398373/145776638-99bd1afb-68fb-4eb2-bf26-a947f04e5240.png)
.

### What you expected to happen

After upgrade we could not find any task or process that submitted from old version which really scarring me.  And we are wondering that jobs submitted from old version could be recovery or not.

### How to reproduce

upgrade to 2.0.0 when there do have jobs been submitted from old version's ds.

### Version

2.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
Since from 1 X to 2 X is a huge change, so the workflow instance cannot support upgrading

**Comment by lazybird23** [comment]
https://github.com/apache/dolphinscheduler/issues/7367#issuecomment-1004684939
so it`s mean 1.x workflow is running not transfer to 2.x?

**Comment by lazybird23** [comment]
> Since from 1 X to 2 X is a huge change, so the workflow instance cannot support upgrading
