### ISSUE TITLE
[Feature][UI Next][Create Project] Build a front-end refactoring project.

### ISSUE THREAD

**Issue by songjianet** [apache/dolphinscheduler#7380]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Build the project, install and configure the necessary dependencies. Specific dependencies can refer to [#7332](https://github.com/apache/dolphinscheduler/issues/7332).

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
@songjianet which version do we want to release this feat?
