### ISSUE TITLE
[Bug] [dolphinscheduler-ui-2.0.0] Alarm Page Exception

### ISSUE THREAD

**Issue by 981433814** [apache/dolphinscheduler#7385]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. When using alarm instance management, an error occurs on the front end
2. Edit the alarm group, but the alarm instance cannot be added

1. 使用告警实例管理时，前端报错
2. 编辑告警组，无法添加告警实例

### What you expected to happen

1. When using alarm instance management, an error occurs on the front end
2. Edit the alarm group, but the alarm instance cannot be added

1. 使用告警实例管理时，前端报错
2. 编辑告警组，无法添加告警实例

### How to reproduce

Add the alarm instance and edit it again

添加告警实例，再次编辑

### Version

2.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I can't reproduce this issue. Could you tell me more details about this issue. You'd better to provide some error messages or a few screenshots.

**Comment by 981433814** [comment]
![image](https://user-images.githubusercontent.com/45874392/146188179-fe00fd6a-a4c4-4dc7-b09a-d1f24452b84f.png)
Edit the alarm group, but the alarm instance cannot be added
![image](https://user-images.githubusercontent.com/45874392/146188417-d24c33ed-6b04-4515-a439-1065ced6a81a.png)
Add failure

**Comment by lenboo** [comment]
already fix in 2.0.2
