### ISSUE TITLE
[Bug] [docs-zh][docs] System User Manual link failure (both docs-zh and docs)

### ISSUE THREAD

**Issue by uestczhuhao** [apache/dolphinscheduler#7389]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Document https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/architecture/design.html under 
1.3 Architecture description link System User Manual return 404 Not Found. It happened  https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/architecture/design.html  at the same time.

### What you expected to happen

Link System User Manual should link to a normal page

### How to reproduce

https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/architecture/design.html
https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/architecture/design.html 
Click above link

### Version

2.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lukairui** [comment]
I don't think it is a bug. 

The url address mapping ：

VERSION 2.0.0:
https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/architecture/design.html
https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/architecture/design.html

VERSION 1.3.9:
https://dolphinscheduler.apache.org/en-us/docs/1.3.9/user_doc/architecture-design.html
https://dolphinscheduler.apache.org/zh-cn/docs/1.3.9/user_doc/architecture-design.html

**Comment by zhongjiajie** [comment]
> I don't think it is a bug.
> 
> The url address mapping ：
> 
> VERSION 2.0.0: https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/architecture/design.html https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/architecture/design.html
> 
> VERSION 1.3.9: https://dolphinscheduler.apache.org/en-us/docs/1.3.9/user_doc/architecture-design.html https://dolphinscheduler.apache.org/zh-cn/docs/1.3.9/user_doc/architecture-design.html

You‘re right, you did a good job here 👍 . FYI @lukairui you could `@` me, when you think the issue could close or you going to do any issue.

**Comment by lukairui** [comment]
Thanks a lot . @zhongjiajie

**Comment by uestczhuhao** [comment]
![image](https://user-images.githubusercontent.com/21079837/147028526-65ee1eb7-48c6-4969-89a0-170868666516.png)
![image](https://user-images.githubusercontent.com/21079837/147028788-111fc7b5-d7c2-4d66-83ad-5677739eb49e.png)

It seems i had not make it clear.
when i click the hyperlink shown above 1 in https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/architecture/design.html , i get a 404 page shown above 2, so i think something wrong

ps：I found it in VERSION 2.0.0, but VERSION 1.3.9 is ok.
@zhongjiajie @lukairui

**Comment by uestczhuhao** [comment]
May i fix this？

**Comment by zhongjiajie** [comment]
> May i fix this？

@uestczhuhao  Feel free to take and fix is, I assigned to you, looking forward your contribution. You could ping me if you need any help.

**Comment by zhongjiajie** [comment]
@uestczhuhao  FYI, I notice that we currently use html syntax for our doc `<a href="/en-us/docs/2.0.1/user_doc/system-manual.html" target="_self"> System User Manual </a>`, it better to use markdown syntax `[System User Manual](/en-us/docs/2.0.1/user_doc/system-manual.html)`

**Comment by uestczhuhao** [comment]
> @uestczhuhao FYI, I notice that we currently use html syntax for our doc `<a href="/en-us/docs/2.0.1/user_doc/system-manual.html" target="_self"> System User Manual </a>`, it better to use markdown syntax `[System User Manual](/en-us/docs/2.0.1/user_doc/system-manual.html)`

OK，get it

**Comment by uestczhuhao** [comment]
@zhongjiajie I have finished this issue, please take a look 
ps: this issue seems assigned to youself, could you change it to me?

**Comment by zhongjiajie** [comment]
> @zhongjiajie I have finished this issue, please take a look ps: this issue seems assigned to youself, could you change it to me?

Thanks for your notice, I change to you and would review your PR right now
