### ISSUE TITLE
[Feature]exec shell for remote 

### ISSUE THREAD

**Issue by jepsonXing** [apache/dolphinscheduler#739]
现有项目要部署有worker-thread的服务器，才能执行shell。那这样岂不是操作n台应用服务器，就要部署那套程序么？
        当机器在10+以上后运维不是很方便的。能不能支持远程执行shell的方式，这样我只需要在一台服务器上面部署worker-thread。就可以执行n台服务器上的shell脚本，已达到节省资源和运维管理方便的目的

**Comment by dailidong** [comment]
not support for now!   looks like a good idea!

**Comment by jxauwxj** [comment]
远程执行会有N个问题
1.ssh远程登录后执行，属于非交互式登录，环境变量可能无法加载
2.脚本执行后，无法获取它的执行状态和日志

**Comment by jepsonXing** [comment]
1、类似的secureCRT软件也是远程登录执行命令的，可以是交互模式的
2、开源库libssh2里面可以拿到执行的结果的
