### ISSUE TITLE
[Bug] [API]Update tenant failed in API

### ISSUE THREAD

**Issue by roylion** [apache/dolphinscheduler#7396]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

        /**
         * if the tenant code is modified, the original resource needs to be copied to the new tenant.
         */
        if (!tenant.getTenantCode().equals(tenantCode)) {
            if (checkTenantExists(tenantCode)) { **********************此处判断条件有误**********************
                // if hdfs startup
                省略。。。
            } else {
                putMsg(result, Status.OS_TENANT_CODE_HAS_ALREADY_EXISTS);
                return result;
            }
        }

### What you expected to happen

        /**
         * if the tenant code is modified, the original resource needs to be copied to the new tenant.
         */
        if (!tenant.getTenantCode().equals(tenantCode)) {
            if (!checkTenantExists(tenantCode)) { **********************此处判断条件改为不存在时复制资源**********************
                // if hdfs startup
                省略。。。
            } else {
                putMsg(result, Status.OS_TENANT_CODE_HAS_ALREADY_EXISTS);
                return result;
            }
        }

### How to reproduce

修改一个已存在的租户名称，且新的租户名称没有与其他租户名称重复，提交时会提示 “操作系统租户已存在”

版本号：2.0.1-release

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I will check this issue.

**Comment by calvinjiang** [comment]
Could you shed some more light on it? Give more details about this issue.

Seems like you can't modify the tenant's name:
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/4928204/145965344-37f8131e-8e27-4eba-87b2-0cf2ac90acb7.png">

**Comment by lenboo** [comment]
> Could you shed some more light on it? Give more details about this issue.
> 
> Seems like you can't modify the tenant's name: <img alt="image" width="1079" src="https://user-images.githubusercontent.com/4928204/145965344-37f8131e-8e27-4eba-87b2-0cf2ac90acb7.png">

Maybe we should remove the update interface in api.
