### ISSUE TITLE
Error creating tenant, user, resource

### ISSUE THREAD

**Issue by fujunit** [apache/dolphinscheduler#7400]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

使用ambari集成安装dolphinscheduler1.3.0和1.3.3版本之后，创建租户、用户、和资源的时候会报：创建租户、用户、资源错误 java.lang.NullPointerException:Name is null

### What you expected to happen

使用ambari集成安装dolphinscheduler1.3.0和1.3.3版本之后，创建租户、用户、和资源的时候会报：创建租户、用户、资源错误 java.lang.NullPointerException:Name is null

### How to reproduce

使用ambari集成安装dolphinscheduler1.3.0和1.3.3版本之后，创建租户、用户、和资源的时候会报：创建租户、用户、资源错误 java.lang.NullPointerException:Name is null

### Version

1.3.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
@fujunit Do you try to deploy with `install.sh` instead of ambari deploy mode?

**Comment by davidzollo** [comment]
please join the discussion, we are discussing about removing the ambari plugin [1]

1, https://lists.apache.org/thread/h4pd0kgq0pp63ro0th50f6x3pj1py0o4

**Comment by zhongjiajie** [comment]
FYI @fujunit Ambari plugin installs dolphinscheduler only support 1.3.X version, and we just split ambari plugin into the independent repo, https://github.com/apache/dolphinscheduler-ambari.

I would close this issue, you could still reopen it if you have additional information.
