### ISSUE TITLE
[Bug] Failed to build rpm

### ISSUE THREAD

**Issue by wangzheyuan** [apache/dolphinscheduler#7402]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I executed the command mvn -U clean install -Prpmbuild -Dmaven.test.skip=true -X in the project root directory and encountered the error.
[ERROR] Failed to execute goal org.codehaus.mojo:rpm-maven-plugin:2.2.0:attached-rpm (default) on project dolphinscheduler-dist: Source location /root/dolphinscheduler-2.0.1/dolphinscheduler-dist/../dolphinscheduler-alert/src/main/resources does not exist.

### What you expected to happen

In dolphinscheduler-2.0.1, the content of dolphinscheduler-alert has changed.

### How to reproduce

Executing the command mvn -U clean install -Prpmbuild -Dmaven.test.skip=true -X in the project root directory.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
We will move the rpm and ambari package to a new repository.

**Comment by zhongjiajie** [comment]
Close by #7880
