### ISSUE TITLE
[Bug] [workerServer] Text file busy

### ISSUE THREAD

**Issue by zwZjut** [apache/dolphinscheduler#7416]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[INFO] 2021-12-14 17:17:35.629  - [taskAppId=TASK-3801230838752_1-849179-3397043]:[200] - process has exited, execute path:/tmp/dolphinscheduler/exec/process/3800902342624/3801230838752_1/849179/3397043, processId:1527531 ,exitStatusCode:126 ,processWaitForStatus:true ,processExitValue:126
[INFO] 2021-12-14 17:17:36.609  - [taskAppId=TASK-3801230838752_1-849179-3397043]:[61] -  -> welcome to use bigdata scheduling system...
	/tmp/dolphinscheduler/exec/process/3800902342624/3801230838752_1/849179/3397043/849179_3397043.command: line 5: /tmp/dolphinscheduler/exec/process/3800902342624/3801230838752_1/849179/3397043/849179_3397043_node.sh: Text file busy
[INFO] 2021-12-14 17:17:36.610  - [taskAppId=TASK-3801230838752_1-849179-3397043]:[55] - FINALIZE_SESSION

### What you expected to happen

System fault tolerance

### How to reproduce

parallel execute shell task  in worker

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zwZjut** [comment]
branch: 2.0.2-prepare

**Comment by brave-lee** [comment]
This looks like shell syntax error. Please confirm. @zwZjut

**Comment by Yao-MR-zz** [comment]
@zwZjut can you share more context? just more logs
