### ISSUE TITLE
[Feature][Website] Please add unsubscribe method to website

### ISSUE THREAD

**Issue by davidzollo** [apache/dolphinscheduler#7419]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I noticed that some users didn't want to subscribe the developer mailing list, please provide solution to help them
![image](https://user-images.githubusercontent.com/15833811/146117629-3ee3a9bc-20ef-44ea-bad0-dbd379006270.png)

https://dolphinscheduler.apache.org/en-us/community/development/subscribe.html

the website repository: https://github.com/apache/dolphinscheduler-website

 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by uestczhuhao** [comment]
I am interested in implementing this task

**Comment by kezhenxu94** [comment]
> I am interested in implementing this task

Thanks. Assigned to you
