### ISSUE TITLE
[Feature][UI] display the full name of the node in DAG workflow page

### ISSUE THREAD

**Issue by mgduoduo** [apache/dolphinscheduler#7428]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

the node should expand or display the full name while the mouse is moved up.

We have many tasks with serial nodes in DS 2.0.0 now. Sometimes I want to find a certain node, but I have to double-click  them then open and view one by one to find it. It is not as convenient as the old version~
![image](https://user-images.githubusercontent.com/13417113/146139010-25f3abd2-becd-47f5-b575-03e719f033f6.png)

In the version 1.3.x, the node name can be displayed completely.
![image](https://user-images.githubusercontent.com/13417113/146139379-90d76368-2916-45bb-bf5b-c432984e0626.png)

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Hi @mgduoduo I assigned to you cause you select check box "Yes I am willing to submit a PR!"

**Comment by mgduoduo** [comment]
+1  
tks. i will try to fix it asap. @zhongjiajie

**Comment by zhongjiajie** [comment]
@mgduoduo  looking forward your contributing.

**Comment by mgduoduo** [comment]
it's done, @zhongjiajie 
pls review the PR https://github.com/apache/dolphinscheduler/pull/7477 and then merge if the integration testing is passed. tks

the final effect is as below
![image_1639750421785](https://user-images.githubusercontent.com/13417113/146559755-40155955-6daf-487d-adff-61d5bc7d0cd0.png)

**Comment by songjianet** [comment]
Thank you for your contribution, this has already been handled by others.
