### ISSUE TITLE
[Bug] [dolphinscheduler-dao] An error is reported when executing the MySQL table creation statement

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#7434]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 An error is reported when executing the MySQL table creation statement :sh script/create-dolphinscheduler.sh 
![image](https://user-images.githubusercontent.com/95271106/146193241-90125911-e3dd-49b5-903c-a33030daa401.png)
 

### What you expected to happen

.

### How to reproduce

When configuring the URL of the database, add usessl = false

### Version

2.0.2-prepare

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @janeHe13 , maybe it's not a bug, please provide more info, such as jar version, driver name, url.
