### ISSUE TITLE
[Bug] [WorkerServer] workerServer  always restart: judged to death

### ISSUE THREAD

**Issue by zwZjut** [apache/dolphinscheduler#7440]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

workerServer fake death: judged to death  but not stop myself

### What you expected to happen

workerServer fake death: judged to death  and stop myself

### How to reproduce

workerServer judged to death 

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zwZjut** [comment]
always judged to death

**Comment by geosmart** [comment]
the death mechanism is work with master/worker's  suicide.

when the zk session timeout is too short(default is 60s), 
the worker or master loss connection from the zk. remove the `nodes/master/ip:port` node.
other master/worker will watch this event and add the node to  `nodes/dead-servers/ip:port`.

so when the master/worker's network recover and reconnect to zk .
it will revieve the dead node add event, and kill itself.


---

 describe some more detail of your scenario like 
 ref issue: #6880

**Comment by zwZjut** [comment]
> the death mechanism is work with master/worker's suicide.
> 
> when the zk session timeout is too short(default is 60s), the worker or master loss connection from the zk. remove the `nodes/master/ip:port` node. other master/worker will watch this event and add the node to `nodes/dead-servers/ip:port`.
> 
> so when the master/worker's network recover and reconnect to zk . it will revieve the dead node add event, and kill itself.
> 
> describe some more detail of your scenario like ref issue: #6880

failover logic bug , fixed in 2.0.2

**Comment by geosmart** [comment]
which pr ? @zwZjut
