### ISSUE TITLE
[Bug][MasterServer]  workflow is always running: state in t_ds_process_instance is always  1   but state in t_ds_task_instance is always 0 or 8 or something else

### ISSUE THREAD

**Issue by zwZjut** [apache/dolphinscheduler#7441]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 workflow is always running: state in t_ds_process_instance is always  1   but state in t_ds_task_instance is always 0 or 8 or something else

### What you expected to happen

 workflow finished es expected

### How to reproduce

run a large batch of workflow

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zwZjut** [comment]
branch: 2.0.2-prepare

**Comment by boy-xiaozhang** [comment]
Hi, can you describe how to reproduce this problem?
