### ISSUE TITLE
[Feature][Docs] Add a back-to-top button in some long articles

### ISSUE THREAD

**Issue by lukairui** [apache/dolphinscheduler#7443]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

To improve the reading experience of our documents, we can add a back-to-top button in some long articles.
![image](https://user-images.githubusercontent.com/26786173/146319435-5eb9bb14-b66d-41ed-b8db-42dd63fdd426.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sweepingmonk123** [comment]
how this issue be solved？with Docusaurus or others？
