### ISSUE TITLE
[Feature][Doc] Change the browser tab title to Chinese when reading Chinese documents.

### ISSUE THREAD

**Issue by lukairui** [apache/dolphinscheduler#7446]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When reading Chinese documents, change the browser tab title to Chinese.
eg:
![image](https://user-images.githubusercontent.com/26786173/146322381-70511d3f-1f01-468b-b4a4-ce3bd78b9c08.png)
![image](https://user-images.githubusercontent.com/26786173/146322425-331626ab-88ba-4b0a-9592-8caea6bafa15.png)
![image](https://user-images.githubusercontent.com/26786173/146322484-1a7a0e88-e8b6-4bff-84b4-35adee439d6c.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yaoyingzhe** [comment]
hi，I'm a newcomer. I want to start here，may you assign it  to me？

**Comment by lukairui** [comment]
Sure, but this new feature has not been certified, I am the proposer of the new feature, but I am not sure if this is in line with the direction of the dolphinscheduler community. In other words, the need is being proposed, but there is no certainty that it is going to be done.

**Comment by davidzollo** [comment]
> hi，I'm a newcomer. I want to start here，may you assign it to me？

have assigned to you

**Comment by yaoyingzhe** [comment]
This featue is of little use, I think we'd better keep it as it is ;
due to the need to change the file name, it is inconvenient to translate Chinese and English documents in the later stage.
