### ISSUE TITLE
[Feature][UI] The search box can be searched by pressing enter button.

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#7457]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The search box can be searched by pressing enter button in ui.Just like the old version 1.3.X.

branch: 2.0.1-release

### Use case

search

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I will check this issue.
