### ISSUE TITLE
[Bug] Please delete old releases 

### ISSUE THREAD

**Issue by sebbASF** [apache/dolphinscheduler#7484]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Releases that are no longer developed should be removed from the mirror system, i.e. should be removed from

https://dist.apache.org/repos/dist/release/dolphinscheduler/

See:
https://www.apache.org/legal/release-policy.html#when-to-archive

### What you expected to happen

Please remove the following releases:

1.3.3/
1.3.4/
1.3.5/
1.3.6/
1.3.7/
1.3.8/
2.0.0-alpha/

Also 2.0.0, now that 2.0.1 has been announced

Please also update the release process documentation to remind the release manager to remove the previous release once the new release has been announced.

### How to reproduce

N/A

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
good idea! 
We will delete the old release branch soon.

**Comment by sebbASF** [comment]
Why was this issue closed?

The old releases are still present.
