### ISSUE TITLE
[Feature][UI]Fuzzy search and case-insensitive search should be supported in process definition details page

### ISSUE THREAD

**Issue by karen-liu01** [apache/dolphinscheduler#7493]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1、click a process and enter   the  process definition details page
eg:http://XXXXX:12345/dolphinscheduler/ui/#/projects/3880463913664/definition/list/3880470637248
2、search node with the search button in the upper right corner of the page 
3、Enter a partial name or enter it regardless of case ,and click search button
[expect]
1、search node successful
[actual]
 1、The corresponding node is not found

### Use case

Fuzzy search and case-insensitive search should be supported。
This is useful when there are many nodes

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I'd like to develop this feature.
