### ISSUE TITLE
[Bug] [dolphinscheduler-ui] The Environment Name drop-down box does not display the environment

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#7494]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/95271106/146699813-a80a3509-e67b-4c2d-8a9b-943998218552.png)

### What you expected to happen

.

### How to reproduce

.

### Version

2.0.2-prepare

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will check later

**Comment by zhongjiajie** [comment]
Hi, @janeHe13  I think is better to keep the version to `2.0.1`. Cause bug report only reports the version of your current use.

**Comment by janeHe13** [comment]
Because env is not associated with a worker group. In environment management, only when the corresponding worker group is associated, the env drop-down box will have env environment
![image](https://user-images.githubusercontent.com/95271106/146868990-679d6da9-ae4c-4d7c-845d-5eea03b1ef84.png)
![image](https://user-images.githubusercontent.com/95271106/146869031-cea49690-652b-418b-a5f3-b71e2c3ff57b.png)
