### ISSUE TITLE
[Bug] [Doc] Picture in designe EN doc have ZH content

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#7496]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Picture in designe EN doc have Chinese content. Source page https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/architecture/design.html. Sub task for https://github.com/apache/dolphinscheduler/issues/6535
![image](https://user-images.githubusercontent.com/15820530/146706965-1b448f0f-2b48-4c80-b112-b089f041967f.png)

### What you expected to happen

We should change to English picture in above doc

### How to reproduce

Go and see  https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/architecture/design.html

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yaoyingzhe** [comment]
hi，I would like to do this，can you assign it to me ？

**Comment by davidzollo** [comment]
> hi，I would like to do this，can you assign it to me ？

I have assigned this issue to you,  looking forward to your PR , thx

**Comment by yaoyingzhe** [comment]
![process_priority_en_us](https://user-images.githubusercontent.com/10797147/146744784-eb351b14-c94a-4ed6-8ba4-5132c2a3d116.png)

**Comment by yaoyingzhe** [comment]
![task_priority_en_us](https://user-images.githubusercontent.com/10797147/146744830-5eac611f-5933-4f53-a0c6-31613c283708.png)
