### ISSUE TITLE
[Bug] [Alarm Plugin] query plugins result is null

### ISSUE THREAD

**Issue by Jiezhi** [apache/dolphinscheduler#7498]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### Function
1. When clicked **Create Alarm Instance**， and get **query plugins result is null**. And  I checked the tables of `t_ds_plugin_define` and `t_ds_alert_plugin_instance`, both empty.

### UI
2.  **Warning Instance** or **Alarm Instance**?
Maybe use the same name might be better?
![image](https://user-images.githubusercontent.com/3399929/146715842-00b3686b-c3b0-49a6-9551-9b1fb01f8c7c.png)

### What you expected to happen

Able to choose alarm plugin.

### How to reproduce

I upgrade DS from 1.3.7 to 2.0-alpha, and failed because of this https://github.com/apache/dolphinscheduler/issues/6973.

And I continue upgrade to 2.0.1, while failed to select the alarm plugins now.

I don't know it's ok or not that `t_ds_plugin_define` and `t_ds_alert_plugin_instance` are empty.

### Anything else

I checked the code to find there's any code to insert into the table `t_ds_plugin_define`  but only found ddl statements.

So how can I fix this, insert plugins into table or else?

---

### Version

2.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Jiezhi** [comment]
Well, after I restart the ds cluster, the alarm plugins  all displayed.

And the table `t_ds_plugin_define` contains all the records, and the column create_time is the time I restarted.

---

重启大法好😓

**Comment by zhiguohe** [comment]
version2.0.3, the table t_ds_alert_plugin_instance is empty~~

**Comment by jiangoxford** [comment]
version 3.3.2 , table t_ds_plugin_define is null after deployed by docker compose
