### ISSUE TITLE
[Bug] [master] TASK_STATE_CHANGE executeStatus: RU NNING_EXECUTION task instance id: XXX process instance id: XXX context: null

### ISSUE THREAD

**Issue by seagle-yuan** [apache/dolphinscheduler#7501]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[INFO] 2021-12-20 15:28:44.034 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[286] - process event: State Event :key: null type: TASK_STATE_CHANGE executeStatus: RU
NNING_EXECUTION task instance id: 102 process instance id: 28 context: null
[ERROR] 2021-12-20 15:28:44.035 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[249] - state handle error:
java.lang.NullPointerException: null
[ERROR] 2021-12-20 15:28:44.035 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[249] - state handle error:
java.lang.NullPointerException: null
[INFO] 2021-12-20 15:28:44.035 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[286] - process event: State Event :key: null type: TASK_STATE_CHANGE executeStatus: RU
NNING_EXECUTION task instance id: 104 process instance id: 29 context: null
[INFO] 2021-12-20 15:28:44.035 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[286] - process event: State Event :key: null type: TASK_STATE_CHANGE executeStatus: RU
NNING_EXECUTION task instance id: 106 process instance id: 27 context: null
[ERROR] 2021-12-20 15:28:44.035 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[249] - state handle error:
java.lang.NullPointerException: null
[INFO] 2021-12-20 15:28:44.035 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[286] - process event: State Event :key: null type: TASK_STATE_CHANGE executeStatus: RU
NNING_EXECUTION task instance id: 102 process instance id: 28 context: null
[ERROR] 2021-12-20 15:28:44.035 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[249] - state handle error:
java.lang.NullPointerException: null
[ERROR] 2021-12-20 15:28:44.035 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[249] - state handle error:
java.lang.NullPointerException: null
[INFO] 2021-12-20 15:28:44.035 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[286] - process event: State Event :key: null type: TASK_STATE_CHANGE executeStatus: RU
NNING_EXECUTION task instance id: 104 process instance id: 29 context: null

### What you expected to happen

it's always write this error log

### How to reproduce

1

### Version

2.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
@seagle-yuan 
I think we need more details for this problem : 
  - When did it happened?
  - What's the state of workflow/tasks?
  - What's the task types of the workflow?
Please reopen it when you supply more details.

**Comment by kangweihao0321** [comment]
I found this problem also because I had a task executing when restarting the cluster. It doesn't happen that I restart the task I'm doing after I stop it.

**Comment by xialinlin101** [comment]
I found that this error occurs after stopping the task and deleting the process instance，The corresponding task instance is also deleted.
The error occurred in： org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread
private boolean taskStateChangeHandler(StateEvent stateEvent) {
        TaskInstance task = processService.findTaskInstanceById(stateEvent.getTaskInstanceId());
        **if (task.getState().typeIsFinished())** {
            taskFinished(task);
        } else if (activeTaskProcessorMaps.containsKey(stateEvent.getTaskInstanceId())) {
            ITaskProcessor iTaskProcessor = activeTaskProcessorMaps.get(stateEvent.getTaskInstanceId());
            iTaskProcessor.action(TaskAction.RUN);

            if (iTaskProcessor.taskState().typeIsFinished()) {
                task = processService.findTaskInstanceById(stateEvent.getTaskInstanceId());
                taskFinished(task);
            }
        } else {
            logger.error("state handler error: {}", stateEvent.toString());
        }
        return true;
    }

**Comment by Jtiag** [comment]
我使用的版本是2.0.6 ，我也遇到了这个bug 删除了实例历史记录后 master节点疯狂的报这个错误，导致很多定时任务无法执行 不到1分钟打印了200m左右的日志
