### ISSUE TITLE
[Feature][Common]Plaintext password

### ISSUE THREAD

**Issue by rwyw** [apache/dolphinscheduler#7503]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

To encrypt the password during network transmission (prevent packet capture), such as user login, datasource account information transmission and storage, etc

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
@rwyw 
good idea, would you please submit a pr for this?
