### ISSUE TITLE
[Bug] [dolphinscheduler-worker] Cannot distinguish resource files with same path & name 

### ISSUE THREAD

**Issue by huangwei2013** [apache/dolphinscheduler#7509]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

`    private void downloadResource(String execLocalPath, Map<String, String> projectRes, Logger logger) {
        ...
        for (Map.Entry<String, String> resource : resEntries) {
            ...
            File resFile = new File(execLocalPath, fullName);
            if (!resFile.exists()) {
`

That's only check by path & name, what if a revised file？or a replacement？

### Use case

1、check strictly

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yaoyingzhe** [comment]
![image](https://user-images.githubusercontent.com/10797147/147179219-cda80674-0038-4aed-a0c2-9e53254bf97f.png)
For a revised file, you may reuplod by this button;
you can close this issue if this button solves your nedd.

**Comment by lenboo** [comment]
@huangwei2013 
You can reopen it when you find some problems.
