### ISSUE TITLE
[Bug] [UI] File Manage  when return the parent folder ,ui send "undefined" to backend

### ISSUE THREAD

**Issue by BenZouxm** [apache/dolphinscheduler#7510]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

issue:can not dispaly noraml   when click the prent floder from the child folder

 create file folder （at least 2 layer），click the parent folder from the child folder ,then exception occuer

![image](https://user-images.githubusercontent.com/25214080/146863720-717c03f0-eb96-43da-9343-1d57819e4bbb.png)

### What you expected to happen

should display the parent folder content

### How to reproduce

 create file folder （at least 2 layer），click the parent folder from the child folder ,then exception occuer
version:2.0.0 release

### Version

2.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I will check this issue.
