### ISSUE TITLE
[BUG][UI] dependent node ui dislocation

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#7512]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![](https://files.catbox.moe/a88qre.png)

### What you expected to happen

above

### How to reproduce

above

### Version

2.0.1-release

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by janeHe13** [comment]
When creating and editing dependent nodes, check timeout alarm and timeout failure, and the status is not updated after saving, which is still unchecked
![image](https://user-images.githubusercontent.com/95271106/149256674-d321c26a-1147-4125-b543-3d4069e6f8a3.png)
![image](https://user-images.githubusercontent.com/95271106/149256852-9c313e9f-f418-4011-a652-ba89449938b2.png)
