### ISSUE TITLE
[Feature][UI] max retry time and max retry delay dropdown box can be edited

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#7513]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![](https://files.catbox.moe/osb1ju.png)

Max retry time and max retry delay dropdown box can be edited.Just like the old ways in 1.3.X.

### Use case

user can modified different max retry time and max retry delay.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by janeHe13** [comment]
After entering a number, the drop-down box displays 2 identical numbers
![image](https://user-images.githubusercontent.com/95271106/149255114-733155a0-f08b-497d-bd3b-4497aa38aa78.png)

**Comment by SbloodyS** [comment]
> Process definition and task definition are separated in 2.X. When the user only updates the task definition without updating the process definition,  it will be judged that the process definition has not been updated, resulting in no update of the information of the process definition.

I think this problem needs to be discussed.

**Comment by janeHe13** [comment]
When no number is entered, the drop-down list only displays 0, which should be the same as before. 1, 2, 3, 4 、5 can be selected from the drop-down list
![image](https://user-images.githubusercontent.com/95271106/149493977-4103aa41-9b27-410e-ab7d-d9ed0c0eee99.png)
