### ISSUE TITLE
[Bug] [Alarm] Http alarm plugin doesn't send task info

### ISSUE THREAD

**Issue by Jiezhi** [apache/dolphinscheduler#7522]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When send alarm via http, only get user defined body while the process/task alert info is ignored.

### What you expected to happen

Get the alert info.

### How to reproduce

Just see the code https://github.com/apache/dolphinscheduler/blob/90243f13eea046c60c55f091d1002a233ea156af/dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/main/java/org/apache/dolphinscheduler/plugin/alert/http/HttpSender.java#L150

### Version

2.0.1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
closed #7523

**Comment by lenboo** [comment]
@Jiezhi 
Thank you for your contributions. we will release this issue in version 2.1.0
