### ISSUE TITLE
[Bug] [DataSource] Add hive datasource failed 

### ISSUE THREAD

**Issue by caiiansheng** [apache/dolphinscheduler#7528]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/26760483/146926606-7e5eef51-104b-4624-95f8-139f08315ae3.png)

logs:
![image](https://user-images.githubusercontent.com/26760483/146926777-c6277842-d52b-4fed-9c77-bc721d2b1608.png)

config:
![image](https://user-images.githubusercontent.com/26760483/146926925-b6f85eff-edc1-49a3-a470-17aa5d55f12c.png)

**PS:  Kerberos is not enabled in my cluster**

### What you expected to happen

add new hive datasource success.

### How to reproduce

add new hive datasource success.

### Anything else

The bug occurred in 2.01 release, and there was no problem with 2.0 release.

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
It will be fixed in 2.0.2-release.

An alternative way to solve this problem is remove java.security.krb5.conf.path in conf/common.properties.

**Comment by zhongjiajie** [comment]
> It will be fixed in 2.0.2-release.
> 
> An alternative way to solve this problem is remove java.security.krb5.conf.path in conf/common.properties.

One more question, does it fix in dev branch ? @SbloodyS

**Comment by zhongjiajie** [comment]
If fix in dev, I would close this issue

**Comment by caiiansheng** [comment]
@SbloodyS ,hi ：
I tried to  remove "java.security.krb5.conf.path" as you said, but there was an error:
1. If  set ”{auth=noSasl}“ 
![image](https://user-images.githubusercontent.com/26760483/147026803-ed7fc215-de02-48f5-905f-fa90247ca4af.png)
logs:
![image](https://user-images.githubusercontent.com/26760483/147026963-6da30bf9-d66d-4e18-b6d5-68c3b0c69b71.png)
2. If  don't set ”{auth=noSasl}“ 
 
![image](https://user-images.githubusercontent.com/26760483/147027284-57613ec1-0312-482b-a20e-bbc316338a7a.png)
and logs:
![image](https://user-images.githubusercontent.com/26760483/147027450-a5441bef-c5ca-4004-8adf-d4d88eb0f803.png)

**Comment by SbloodyS** [comment]
@zhongjiajie Yes.It has been fixed in dev. PR: #7393

@caiiansheng Hive datasource's other params did not work. It will be fixed in 2.0.2-release. Related issue: #7485

**Comment by zhongjiajie** [comment]
Duplicate to #7392 and already fix in #7393. Will release in 2.0.2 and also fix in dev. You could reopen this issue when you have an additional problem.

BTW, thanks @SbloodyS for the clarification.
