### ISSUE TITLE
[Improvement][tools] Init DB schema from the full sql file.

### ISSUE THREAD

**Issue by lgcareer** [apache/dolphinscheduler#7529]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Now if it's the first time to install dolphinscheduler,execute script/create-schema.sh will execute the sql from the
earliest version to the current version step by step.

In order to init DB schema more convenient and faster,
suggest to init the DB from the full sql file.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
PR was merged.
