### ISSUE TITLE
[Bug] [server] when there is a forbidden node in dag, the execution flow is abnormal

### ISSUE THREAD

**Issue by vinnielhj** [apache/dolphinscheduler#7538]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In a dag, after the node is forbidden to execute, there is a problem with the judgment of the execution of the node that depends on the forbidden node.

### What you expected to happen

When a node depends on a forbidden node, it should be judged whether the parent node of the forbidden node has finished running.

### How to reproduce

![481639972312_ pic](https://user-images.githubusercontent.com/28946792/147027151-7d8cc9b9-4693-41a6-8908-f9c8a8d01746.jpg)

As shown in the figure, test1_stop and test2_stop are forbidden nodes. The test3 node depends on test1_stop and test2_stop. In my opinion, whether test3 is executed depends on whether test1 and test2 are executed. But in my test, although the test1 node has been executed, but test2 is being executed, I think test3 should not be executed at this time, but he was executed. Is this a special design? If this is a bug, I would be happy to contribute my code, thank you.

### Version

2.0.1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vinnielhj** [comment]
With a related issue after search:   https://github.com/apache/dolphinscheduler/issues/441

**Comment by lenboo** [comment]
@lhjzmn  
Yes, i think it's a bug in forbidden node. 
Welcome to submit pr for this.

**Comment by vinnielhj** [comment]
> @lhjzmn Yes, i think it's a bug in forbidden node. Welcome to submit pr for this.

I have submitted pr, please review the code, thank you
as follows:
[Bug-7538] [server] Before node execution, if the parent node is a forbidden node, continue to trace upward
https://github.com/apache/dolphinscheduler/pull/7613
