### ISSUE TITLE
[Feature][doc] Add or refactor how to contribute

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#7541]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1. Add how to contribute, we miss how contributors could review PR or issue.
2. Refactor developer and submit PR way https://dolphinscheduler.apache.org/zh-cn/community/development/submit-code.html 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good job
