### ISSUE TITLE
[ERROR] JDBC connection failed when creating hiveserver2 ha zk data source

### ISSUE THREAD

**Issue by berg-xu** [apache/dolphinscheduler#7548]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

基础环境配置:

dolphinscheduler版本为2.0.1;
mysql以及驱动包版本为8.0.19;
hive版本为3.1.2；
zookeeper版本为3.6.3;
jdk 1.8；

hiveserver基于zk完成HA部署。部署完dolphinscheduler确认未使用krb认证服务，创建hive数据源时，按照官方文档使用HiveServer2即默认端口为10000连接hive时提示创建数据源成功。 但是使用HiveServer2 HA Zookeeper创建hive数据源时出现如下错误:

![image](https://user-images.githubusercontent.com/45385723/147078902-56ae37e2-9601-49a4-9cb1-77f231bc35dd.png)

通过查询日志获取如下信息：

![image](https://user-images.githubusercontent.com/45385723/147079082-f4c3d2eb-eb1b-49f3-ad41-635d24a7514d.png)

这样的问题该如何解决？ 

### What you expected to happen

创建hive数据源的时候， 默认连接方式是什么？

### How to reproduce

基础环境配置:

dolphinscheduler版本为2.0.1;
mysql以及驱动包版本为8.0.19;
hive版本为3.1.2；
zookeeper版本为3.6.3;
jdk 1.8；

hiveserver基于zk完成HA部署。部署完dolphinscheduler确认未使用krb认证服务，创建hive数据源时，按照官方文档使用HiveServer2即默认端口为10000连接hive时提示创建数据源成功。 

但是使用HiveServer2 HA Zookeeper创建hive数据源时出现如下错误:

![image](https://user-images.githubusercontent.com/45385723/147078902-56ae37e2-9601-49a4-9cb1-77f231bc35dd.png)

通过查询日志获取如下信息：

![image](https://user-images.githubusercontent.com/45385723/147079082-f4c3d2eb-eb1b-49f3-ad41-635d24a7514d.png)

### Version

2.0.1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Narcasserun** [comment]
https://github.com/apache/dolphinscheduler/pull/7489
