### ISSUE TITLE
[Bug] [Standlone] H2 in standalone server will auto restart after several minutes

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#7554]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After starting the Standalone server several minutes, find the data in database lost.

It seems the h2 has been restart.

I guess this is related with `minimum-idle`, I will take a deep look at this.

### What you expected to happen

No.

### How to reproduce

Start Standalone server and wait, this may happen in several minutes.

If you hope to reproduce fast, you can set minimum-idle=1/2/3, then you will reproduce in less than 3 minutes.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
This is due to the connection url. Each times we create a new connection, will run the init script. In the script will drop the exist table.
```
url: jdbc:h2:mem:dolphinscheduler;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=true;INIT=runscript from 'classpath:sql/dolphinscheduler_h2.sql'
```
This solution is to remove the init script from url

**Comment by kezhenxu94** [comment]
> This is due to the connection url. Each times we create a new connection, will run the init script. In the script will drop the exist table.
> 
> ```
> url: jdbc:h2:mem:dolphinscheduler;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=true;INIT=runscript from 'classpath:sql/dolphinscheduler_h2.sql'
> ```
> 
> This solution is to remove the init script from url

We need put the initialization elsewhere, this is a good candidate👇


```yaml
spring:
  sql:
    init:
      schema-locations: classpath:sql/dolphinscheduler_h2.sql
```

**Comment by ruanwenjun** [comment]
@kezhenxu94 Yes, has submitted a pr, please take a look.

**Comment by kezhenxu94** [comment]
Reverted, reopening this issue
