### ISSUE TITLE
[Improvement][Logger]Logger server integrate into worker server

### ISSUE THREAD

**Issue by aaronlinv** [apache/dolphinscheduler#7559]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Because Logger Server is a separate process, it increases the cost of deployment and maintenance, so integrate Logger server into Worker server 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by geosmart** [comment]
Just the opposite, we need to deploy the logger server and worker seperately.

becase when the worker down,  the logger server still worke.
so the api server can  query log for the task.

---

I deploy the worker and logger in different docker container. and the log path is mount with `glusterfs(a distributed filesystem)`. 

---

beside the master machine also  need to deploy the logger, when master failover to kill the yarn task, it need to query appid by task log
