### ISSUE TITLE
[Bug] [projects] project access permission issues

### ISSUE THREAD

**Issue by ryze124** [apache/dolphinscheduler#7563]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

User can change number in the URI to access other users' project;

https://xxxx.com/dolphinscheduler/ui/#/projects/definition/list/${PROJECT_NUMBER}

### What you expected to happen

backend api do not check the access permission 

### How to reproduce

use a normal user to access administrator's project by change ${PROJECT_NUMBER} in following 
url :
`https://xxxx.com/dolphinscheduler/ui/#/projects/definition/list/${PROJECT_NUMBER}`

### Version

1.3.9

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
It has been fixed in 2.0.1-release.

**Comment by ryze124** [comment]
Thanks for your attention！
