### ISSUE TITLE
[Feature] Can you increase the entry to configure public dependency files?(能否增加配置公共依赖文件的入口)

### ISSUE THREAD

**Issue by xiej23** [apache/dolphinscheduler#759]
I mainly use easyscheduler to schedule a series of python tasks, and the py files are managed by uploading them to the resource center.
However, some py files are publicly dependent on other files.
At this stage, when configuring node resources, you must configure the dependencies together. In the later stages of the business, a lot of configuration work will be added, which will easily lead to missed allocation.

Can I add an entry to configure a public dependency file for each workflow?

---
我主要使用easyscheduler调度一系列python任务，py文件通过上传到资源中心进行管理。
然而有一些py文件是其他文件公共依赖的。
现阶段在配置节点资源时，必须要将依赖文件一起配置。在业务后期会增加不少的配置工作，也容易导致漏配。

能否针对每个workflow增加一个配置公共依赖文件的入口？

**Comment by dailidong** [comment]
good idea！
