### ISSUE TITLE
[Feature][UI] the dolphinscheduler front end page needs to add watermark

### ISSUE THREAD

**Issue by yaoyingzhe** [apache/dolphinscheduler#7595]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In order to add the company's watermark logo of the dolphinscheduler  users，maybe  the dolphinscheduler   UI needs to add watermark  function, and the content of watermark is current username and its company name.

### Use case

we can add watermark  function with js in vue project

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
This is not what an open source project should take care of. If you need please do this in your company.
