### ISSUE TITLE
[Bug] [Api] Add Dependent Node Error

### ISSUE THREAD

**Issue by shangeyao** [apache/dolphinscheduler#7599]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/42203474/147305794-d16a67de-f24b-4e5f-bb63-d270c87f299f.png)
![image](https://user-images.githubusercontent.com/42203474/147305804-e9b89223-4e67-4951-a2e0-9fede7ea78bc.png)

### What you expected to happen

Add dependencies across projects successfully.

### How to reproduce

2.0.2-Prepare, add dependent, then cause a error PROCESS_DEFINE_NOT_EXIST(50003, "process definition {0} does not exist", "工作流定义[{0}]不存在")

### Anything else

I think we can do more fine-grained permission control in user management to distinguish the permissions of query, execution and editing.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
The same issue: #7654 
Fixed in 2.0.2 .
