### ISSUE TITLE
[Bug] [Module Name]  workflow is always running when worker sendResult success but master not received

### ISSUE THREAD

**Issue by zwZjut** [apache/dolphinscheduler#7609]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[Bug] [Module Name]  workflow is always running when worker sendResult success but master not received

### What you expected to happen

[Bug] [Module Name]  workflow can be complated

### How to reproduce

[Bug] [Module Name]  workflow can be complated

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
closed by #7611
