### ISSUE TITLE
[Bug] [Remote] task submited successfully but has not been executed

### ISSUE THREAD

**Issue by yangyiforward** [apache/dolphinscheduler#7614]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

task submit is succeed but cannot be executed for a long time.

工作流被调起后，任务提交成功，master中有提交日志，数据库状态是0，但一直hang住没有被执行；集群资源充足，worker服务正常，分组正确；zk里也有worker

### What you expected to happen

sometimes the worker's logs report : io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection timed out,
possiblly the Netty channel time out

master处理完后，worker没有收到信息，可能是channel连接超时导致

### How to reproduce

execute a flow，which state is succeed; but task can not running 

运行工作流，工作流状态为运行中；task提交成功，显示灰点，一直未执行

### Anything else

[issues 3789](https://github.com/apache/dolphinscheduler/issues/3789) 该issue在1.3.3版本被合并发布，但在发布代码中没有发现以下两段代码
![8d81abfa93c95fa75989353b9460177](https://user-images.githubusercontent.com/46433871/147339952-b414d0bf-615a-491a-8b64-318f7ad9e1eb.png)
![787003dd2e7cf71ff29bebb4ae9174c](https://user-images.githubusercontent.com/46433871/147339971-c784db8e-a3a2-4eed-bfb1-5a382dd4c3d2.png)
手动添加后该问题没有再出现 

### Version

1.3.9

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
@yangyiforward Thanks for your feedback, this has been fixed in 2.x. 

@CalvinKirs Do we still need to fix this 1.3.9?

**Comment by yangyiforward** [comment]
> I'm happy to help. Actually when I user 1.3.3 version, this bug already has appeared. From 1.3.3 to 1.3.9, fix these versions if possible or necessary. Thanks a lot.
