### ISSUE TITLE
[Bug] [Doc] Website dead link checker will failed when add new picture's link

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#7642]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When we add a new picture and add a link for it, our dead link checker would fail. see https://github.com/apache/dolphinscheduler-website/pull/594#issuecomment-1001370441 for more detail. I think we should fix this edge case.

### What you expected to happen

Should not fail when I add new pic and link

### How to reproduce

Add new pic and link

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
remove stale

**Comment by rinkydevi** [comment]
hey @zhongjiajie i would like to work on this project

**Comment by zhongjiajie** [comment]
Hi @rinkydevi , thanks for your feedback, but we have already fixed this in https://github.com/apache/dolphinscheduler-website/pull/676. you could still find task in #5689 for your first PR to Dolphinscheduler
