### ISSUE TITLE
[BUG] When saving the DAG, the user can switch to any tenant state to run

### ISSUE THREAD

**Issue by pbadeager** [apache/dolphinscheduler#765]
When saving the DAG, the user can switch to the state of any tenant to run the DAG, which should be an obvious security issue.
It is recommended to modify this part:
1. Only allow users to switch to authorized tenants to run.
2. Allow one user to be authorized to multiple tenants to solve the problem of testing switch tenants.

---
在保存DAG的时候，用户可以切换到任意租户的状态运行这个DAG，这应该是一个明显的安全问题。
建议修改这部分内容：
1、只允许用户切换到授权的租户下运行
2、允许一个用户可以被授权多个租户，以解决测试切换租户的问题。

**Comment by dailidong** [comment]
very good, thanks!
we will reconsider authority system later!

**Comment by Heltman** [comment]
想到一起去了，这个租户实现的确实有问题，相当于没有限制，现在配置用户租户的唯一作用就是保存DAG的时候可以不用选择租户，Default的就是配置的租户

**Comment by pbadeager** [comment]
实际上还是建议可以选择有限租户的，因为这个对于一个同时维护多个业务账户的可能性还是有的。



yiny@typhoon.org.cn
 
发件人： Helt
发送时间： 2020-06-10 17:12
收件人： apache/incubator-dolphinscheduler
抄送： PPEAGER; Author
主题： Re: [apache/incubator-dolphinscheduler] [BUG] When saving the DAG, the user can switch to any tenant state to run(在保存DAG时，用户可以切换到任意租户状态运行) (#765)
想到一起去了，这个租户实现的确实有问题，相当于没有限制，现在配置用户租户的唯一作用就是保存DAG的时候可以不用选择租户，Default的就是配置的租户

**Comment by Heltman** [comment]
不过目前看来DS还是将重心放在功能补全方面，权限方面可能需要等之后统一做了

**Comment by dailidong** [comment]
> 不过目前看来DS还是将重心放在功能补全方面，权限方面可能需要等之后统一做了

you are right

**Comment by dailidong** [comment]
please update/add in English, thx

**Comment by zhongjiajie** [comment]
This is a security issue, maybe we should fix in next release
