### ISSUE TITLE
[Bug] [work node] SQOOP work targetType error

### ISSUE THREAD

**Issue by ruancheng77** [apache/dolphinscheduler#7653]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Create SQOOP node.
moduleType: import, sourceType: MYSQL, targetType: HDFS
Change moduleType to export and change sourceType to HIVE, targetType from MYSQL to HIVE/HDFS(MYSQL type is missing).

### What you expected to happen

It should be consistent

### How to reproduce

1.Create SQOOP node
2.Change moduleType to export
3.Change sourceType to HIVE

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
related issue: #7459

**Comment by lenboo** [comment]
Repetitive issue, close it.
