### ISSUE TITLE
[Bug] [UI] Dependent node onChangeProjectCode error

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#7654]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![](https://ftp.bmp.ovh/imgs/2021/12/c4f2603fda455092.png)

![](https://ftp.bmp.ovh/imgs/2021/12/ab12f974332d8530.png)

### What you expected to happen

change project successfully.

### How to reproduce

An error will be reported when switching items that do not belong to the current project at the dependency node.It seems like ${state}.projectCode did not change.Therefore, the tasks of other projects cannot be queried.

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
![image](https://user-images.githubusercontent.com/29528966/147535474-d6a88e28-878c-4711-ae99-8c681717531d.png)

I have checked the code.
The verification of project code can be changed to the verification of whether the user has permission to read the project
