### ISSUE TITLE
[Bug] [ci] CI is unstable and will random failure

### ISSUE THREAD

**Issue by labbomb** [apache/dolphinscheduler#7656]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

CI is unstable and will fail @zhongjiajie 

### What you expected to happen

It may be a configuration problem

### How to reproduce

Submit code to request detection when merging

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
We have some cases here PR https://github.com/apache/dolphinscheduler/pull/7651, attempts link https://github.com/apache/dolphinscheduler/actions/runs/1627150888/attempts/1 
 and it contained a long run build which in https://github.com/apache/dolphinscheduler/runs/4642401226?check_suite_focus=true.

After I restart PR https://github.com/apache/dolphinscheduler/pull/7651 CI, it just success https://github.com/apache/dolphinscheduler/actions/runs/1627150888/attempts/2

**Comment by lenboo** [comment]
Is this issue can be close?
@labbomb @zhongjiajie

**Comment by zhongjiajie** [comment]
> Is this issue can be close? @labbomb @zhongjiajie

No, we can't, we still have fake test in our CI

**Comment by zhongjiajie** [comment]
Same error in https://github.com/apache/dolphinscheduler/actions/runs/1658686292/attempts/1 for #7830
