### ISSUE TITLE
[Feature] [dolphinscheduler-api] The parameter is not passed when the shell task parameter uses a variable

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#7664]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/95271106/147527367-f480d4eb-3c05-46b9-99af-88a4c4d17ab4.png)
![image](https://user-images.githubusercontent.com/95271106/147527317-4cd86279-1ebc-4ca8-8a61-62cf9b9c7259.png)
![image](https://user-images.githubusercontent.com/95271106/147527426-13aca2e9-6ec9-48bf-99b9-f7e96420ff64.png)

### What you expected to happen

.

### How to reproduce

.

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
we already have a commit from #9586 should test it work or not
