### ISSUE TITLE
[Bug] [docs] The mysql driver version description in the deployment document is inconsistent

### ISSUE THREAD

**Issue by Lucaszlei** [apache/dolphinscheduler#7668]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In the deployment document of lastest (2.0.1), the description of the mysql driver version is inconsistent
![图片](https://user-images.githubusercontent.com/56599784/147534031-a08913cc-f6ae-4baa-8875-c849e41e331d.png)
but, 
![图片](https://user-images.githubusercontent.com/56599784/147534084-6aa3046c-4bbe-4702-be9f-de3e1bf2cf91.png)

doc link: https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/guide/installation/pseudo-cluster.html

### What you expected to happen

Confirm which version to use

### How to reproduce

Same as above

### Version

2.0.1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
I assign to you. Looking forward your contribution @SunnyZ-L

**Comment by zhongjiajie** [comment]
@SunnyZ-L Hi, are you still WIP on this issue? We looking forward your contribution.

**Comment by Lucaszlei** [comment]
> @SunnyZ-L Hi, are you still WIP on this issue? We looking forward your contribution.

I have already submitted this question to pr.
pr link: https://github.com/apache/dolphinscheduler-website/pull/617

**Comment by davidzollo** [comment]
> > @SunnyZ-L Hi, are you still WIP on this issue? We looking forward your contribution.
> 
> I have already submitted this question to pr. pr link: [apache/dolphinscheduler-website#617](https://github.com/apache/dolphinscheduler-website/pull/617)

merged
