### ISSUE TITLE
[Bug] [task-plugin-sql] hive/impala datasource can not get connection, throw NullpointerException

### ISSUE THREAD

**Issue by jonwjh94** [apache/dolphinscheduler#7671]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/38685000/147537710-ecea98b0-25d4-468f-958b-5d298c1f5241.png)
![image](https://user-images.githubusercontent.com/38685000/147537750-9a017819-d590-430d-b8f9-9c5d0fc47f6c.png)
使用JdbcDataSourceProvider.createOneSessionJdbcDataSource()方法hive/impala创建连接池设置了MaximumPoolSize=1，但是调度任务是，一般hive/impala都是多任务同时跑的话，会出现getConnection=null的情况，因此SqlTask.prepareStatementAndBind()方法会抛出空指针异常。

### What you expected to happen

为什么hive/impala连接池需要创建容量为1的连接池？

### How to reproduce

see what happened

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Narcasserun** [comment]
You can switch the connection pool creation of multi session mode. On session is to solve the problem that the executed SQL is in the same session. It doesn't seem very friendly at the moment

**Comment by Narcasserun** [comment]
#7675

**Comment by jonwjh94** [comment]
Thanks for your reply! I already switch to use multi session mode.

**Comment by jonwjh94** [comment]
> #7675



> You can switch the connection pool creation of multi session mode. On session is to solve the problem that the executed SQL is in the same session. It doesn't seem very friendly at the moment

Thanks for your reply! I already switch to use multi session mode.
