### ISSUE TITLE
[Feature][UI] Support users can enter Kerberos configuration from the UI

### ISSUE THREAD

**Issue by Narcasserun** [apache/dolphinscheduler#7679]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1. Remove the input box of hostname, port and databasename and replace it with the input box of jdbcurl parameter. Oracle servicename or Sid also needs to be removed.

2. Add Kerberos principal, Kerberos KeyTab and Kerberos krb5conf input boxes in the hive data source. If Kerberos startup state is true, it will be displayed, and false will not be displayed.

3. The following interface input format needs to be changed 

/datasources/  POST  --createDataSource
/datasources/{id}  PUT  --updateDataSource
/datasources/connect POST  --connectDataSource

This is a sample parameter
{
    "id": null,
    "name": "zbg01_mysql",
    "note": "test",
    "dbType": "MYSQL",
    "props": {
	    "user": "root",
        "password": "123456",
        "jdbcUrl": "jdbc:mysql://zbg01:3306/mydb",
        "kerberosPrincipal": "",---The type is hive. Kerberos needs to be passed
        "kerberosKeytab": "",---The type is hive. Kerberos needs to be passed
        "kerberosKrb5Conf": "",---The type is hive. Kerberos needs to be passed
        "props": {
            "autoDeserialize": "yes",
            "allowUrlInLocalInfile": "true"
        }
    }
}

**Comment by wangbowen1024** [comment]
yes,i also need it

**Comment by calvinjiang** [comment]
I'm willing to develop this feature.

**Comment by Narcasserun** [comment]
> I'm willing to develop this feature.

so perfect
