### ISSUE TITLE
[Feature][API] export workflow compatible with version 1.3.x 

### ISSUE THREAD

**Issue by glxfeng** [apache/dolphinscheduler#7699]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In 2.0.1 version, export workflow cannot be imported into 1.3.x version.
This will prevent the smooth transition from version 1.3.x to version 2.0.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
@glxfeng 
DolphinScheduler do not support to import data from different version.
