### ISSUE TITLE
[Bug] [dolphinscheduler-server] master log  user task log info 

### ISSUE THREAD

**Issue by zwZjut** [apache/dolphinscheduler#7711]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[Bug] [dolphinscheduler-server] master log  user task log info 

### What you expected to happen

[Bug] [dolphinscheduler-server] master log  user task log info 

### How to reproduce

[Bug] [dolphinscheduler-server] master log  user task log info 

### Anything else

[Bug] [dolphinscheduler-server] master log  user task log info 

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
relative issue: #7661
relative pr #7665 #7423 #7831
