### ISSUE TITLE
[Feature] [Log] The data source password in the log is not encrypted

### ISSUE THREAD

**Issue by mchcz** [apache/dolphinscheduler#7713]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The data source password in the log is not encrypted.

### What you expected to happen

It should be encrypted or replaced with "****"

### How to reproduce

See "What happened"

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I will check this issue.

**Comment by calvinjiang** [comment]
@mchcz Could you give more details about this issue. Like a few logs.

**Comment by mchcz** [comment]
@calvinjiang 
[INFO] 2021-12-29 16:55:46.487 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[81] - REQUEST TRACE_ID:e9518849-3bfe-4e0f-bf4c-1e09dc5ebfab, LOGIN_USER:dolphinscheduler, URI:/dolphinscheduler/datasources/connect, METHOD:POST, HANDLER:org.apache.dolphinscheduler.api.controller.DataSourceController.connectDataSource, ARGS:{dataSourceParam=OracleDatasourceParamDTO{name='oracle-172.16.0.82', note='', host='172.16.0.82', port=1521, database='orcl', userName='sdprpt', password='tt.123456', connectType=ORACLE_SID, other='null'}}
