### ISSUE TITLE
[Bug] [UI Next] ESLint errors

### ISSUE THREAD

**Issue by devosend** [apache/dolphinscheduler#7717]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I get some problems and errors when I run `npm run lint` in dolphinscheduler-ui-next. as follows:
![image](https://user-images.githubusercontent.com/8847400/147716431-b3e3a51a-ea77-42af-9e85-f129dc4e8612.png)

It seems to be because of the eslint rules is not effect. 
![image](https://user-images.githubusercontent.com/8847400/147716616-cda07429-72c1-42be-9e36-be9896593031.png)

### What you expected to happen

`npm run lint` not errors.

### How to reproduce

`npm run lint` in dolphinscheduler-ui-next.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
Please confirm this question if you have time. @songjianet

**Comment by songjianet** [comment]
> Please confirm this question if you have time. @songjianet

The format code can use the command `prettier`.

**Comment by devosend** [comment]
> > Please confirm this question if you have time. @songjianet
> 
> The format code can use the command `prettier`.

**Comment by devosend** [comment]
> > Please confirm this question if you have time. @songjianet
> 
> The format code can use the command `prettier`.

**Comment by devosend** [comment]
> > Please confirm this question if you have time. @songjianet
> 
> The format code can use the command `prettier`.

yes, `prettier` is used to format the code. but  the config of `.prettier.js` and `.eslintrc.js` conflict beause of `quotes` and `comma-dangle` rule is not effect in `.eslintrc.js`. by the way don't you report errors when you execute `npm run lint` locally? @songjianet

**Comment by songjianet** [comment]
> > > Please confirm this question if you have time. @songjianet
> > 
> > 
> > The format code can use the command `prettier`.
> 
> yes, `prettier` is used to format the code. but the config of `.prettier.js` and `.eslintrc.js` conflict beause of `quotes` and `comma-dangle` rule is not effect in `.eslintrc.js`. by the way don't you report errors when you execute `npm run lint` locally? @songjianet

Yes, currently we have three people developing the new `ui`, and they can run normally using `webstorm` and `vscode` respectively.

**Comment by devosend** [comment]
> > > > Please confirm this question if you have time. @songjianet
> > > 
> > > 
> > > The format code can use the command `prettier`.
> > 
> > 
> > yes, `prettier` is used to format the code. but the config of `.prettier.js` and `.eslintrc.js` conflict beause of `quotes` and `comma-dangle` rule is not effect in `.eslintrc.js`. by the way don't you report errors when you execute `npm run lint` locally? @songjianet
> 
> Yes, currently we have three people developing the new `ui`, and they can run normally using `webstorm` and `vscode` respectively.

Thans for your answer，but I find `eslint-config-prettier` can't found `pretter`'s config, bease of `.pretter.js` is not support for `pretter`. the official profile names supported are as follows:
![image](https://user-images.githubusercontent.com/8847400/147881272-bf41b4f4-a400-4ec7-b02b-1d231fb03690.png).
You can run `npm run prettier` correctly because the configuration file name is specified by the `--config` parameter.
but `eslint` can't recognize it.
In addition the code has other obvious styles for `eslint`. examples:
![image](https://user-images.githubusercontent.com/8847400/147881429-5818dee8-d0a8-4bab-8807-f6b84f0776d6.png)
this file is `veiws/home/index.tsx`.
Based on these I don't think you can run `npm run lint` without reporting errors. 
Hope your reply @songjianet
