### ISSUE TITLE
[Bug] [SQL] field ‘is_directory’ in t_ds_resources table has error type in PostgreSQL database

### ISSUE THREAD

**Issue by wangbowen1024** [apache/dolphinscheduler#7732]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/48642743/147733959-8cf0cdb9-5551-4836-ab90-80a16c3e1b41.png)

create directory error logs:
```
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: column "is_directory" is of type integer but expression is of type boolean
  Hint: You will need to rewrite or cast the expression.
  Position: 192
### The error may exist in org/apache/dolphinscheduler/dao/mapper/ResourceMapper.java (best guess)
### The error may involve org.apache.dolphinscheduler.dao.mapper.ResourceMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO t_ds_resources  ( file_name, size, create_time, description, full_name, alias, update_time, pid, type, user_id, is_directory )  VALUES  
( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )
### Cause: org.postgresql.util.PSQLException: ERROR: column "is_directory" is of type integer but expression is of type boolean
  Hint: You will need to rewrite or cast the expression.
  Position: 192
; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: column "is_directory" is of type integer but expression is of type boolean
```

### What you expected to happen

need change the field ‘is_directory’ type from int to bool,then ok

### How to reproduce

when create directory

### Version

2.0.1

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jim-parsons** [comment]
mark

**Comment by jim-parsons** [comment]
git it to me, i`ve fix it, thx!

**Comment by ruanwenjun** [comment]
@tangchunbo Hi, I think the best way is just modified the `is_directory` type from int to `boolean ` in `dolphinscheduler_postgresql.sql`. 
What do you think?

**Comment by wangbowen1024** [comment]
> @tangchunbo Hi, I think the best way is just modified the `is_directory` type from int to `boolean ` in `dolphinscheduler_postgresql.sql`. What do you think?

i think so, too. because i see 1.3.X is bool and don't have to make any code changes. 
2.0.X change to int ,Is it to unify the style?

**Comment by jim-parsons** [comment]
> 

thx, i am not familiar with PG so that this sollution didn't occure to me.
I also concern the change cost of this filed type in the users who have the older version, but as @wangbowen1024 just saied, i guess not that much.
i can try this way!
thx

**Comment by ruanwenjun** [comment]
@wangbowen1024 @tangchunbo Do you find in which version `is_directory` changed to int? I didn't find this change in postgresql ddl file. 
If no history ddl file contains this change, it's only need to change the type in dolphinscheduler_postgresql.sql.

**Comment by wangbowen1024** [comment]
> @wangbowen1024 @tangchunbo Do you find in which version `is_directory` changed to int? I didn't find this change in postgresql ddl file. If no history ddl file contains this change, it's only need to change the type in dolphinscheduler_postgresql.sql.

v2.0.X all, i change int to bool to slove it,just like my problem description
![image](https://user-images.githubusercontent.com/48642743/148544046-58b2f4d6-80ea-4210-8b29-fe1b1ea784fa.png)

```sql
CREATE TABLE t_ds_resources (
  id serial NOT NULL  ,
  alias varchar(64) DEFAULT NULL ,
  file_name varchar(64) DEFAULT NULL ,
  description varchar(255) DEFAULT NULL ,
  user_id int DEFAULT NULL ,
  type int DEFAULT NULL ,
  size bigint DEFAULT NULL ,
  create_time timestamp DEFAULT NULL ,
  update_time timestamp DEFAULT NULL ,
  pid int,
  full_name varchar(64),
  is_directory int,
  PRIMARY KEY (id),
  CONSTRAINT t_ds_resources_un UNIQUE (full_name, type)
) ;
```
Need  a PR for that? If need, I can

**Comment by ruanwenjun** [comment]
@wangbowen1024 There is already a pr, you can help to review :)
