### ISSUE TITLE
[Bug] [Module Name] Bug title The newly downloaded project cannot run

### ISSUE THREAD

**Issue by wangxil** [apache/dolphinscheduler#7735]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/45277686/147741708-85e14e9b-5a3d-47a4-8d07-fbbcd07218fc.png)

### What you expected to happen

希望配置文件提交下

### How to reproduce

是不是有什么配置文件，并没有提交

### Anything else

![image](https://user-images.githubusercontent.com/45277686/147741699-260123cc-42ab-43d3-965d-8645a52add8f.png)

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
Very welcome to use DolphinScheduler. The running log is in the logs folder of the project. It is recommended that the local IDE use standalone-server.

**Comment by yimaixinchen** [comment]
if you can not use standalone-server,this document is helpful for you.
[https://dolphinscheduler.apache.org/zh-cn/blog/DS_run_in_windows.html]
