### ISSUE TITLE
[Bug] [deploy in k8s] zookeeper connect timeout

### ISSUE THREAD

**Issue by uh001** [apache/dolphinscheduler#7745]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/96870549/147799686-09539ce0-e3cf-4402-b9ca-6a43277f51e2.png)

### What you expected to happen

deploy in k8s , use default zookeeper

### How to reproduce

doc:https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/guide/installation/kubernetes.html
deploy in k8s , use default zookeeper

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
Is ZK configuration right?

**Comment by uh001** [comment]
@lenboo 
Can you tell me how to configure in k8s cluster？
【registry.properties】
![image](https://user-images.githubusercontent.com/96870549/148040112-7f95d71d-9718-4d5d-aece-3fab89cb8d69.png)

**Comment by thisisnige** [comment]
在集群部署模式下遇到了同样的问题
![image](https://user-images.githubusercontent.com/7918588/163102267-06b98d39-07b6-425f-93c7-585f2a149631.png)

**Comment by caishunfeng** [comment]
I try the 2.0.5 version at local and it's OK, follow the doc: https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/guide/installation/kubernetes.html
![image](https://user-images.githubusercontent.com/11962619/163132469-80e555e0-8196-4cb9-b4d2-6812d83478dd.png)

**Comment by thisisnige** [comment]
我找到问题了，请不要使用jdk 18，请用jdk 1.8，因为zk跟高版本的jdk不兼容，在网络地址解析上

**Comment by Hwting** [comment]
#10379
