### ISSUE TITLE
Delete the log of ‘workflow instance’ The log of ‘task instance’ is not deleted in cascade

### ISSUE THREAD

**Issue by qinlz-1** [apache/dolphinscheduler#7767]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

删除 ‘工作流实例’的日志 ‘任务实例’的日志没有级联删除

### What you expected to happen

删除 ‘工作流实例’的日志 ‘任务实例’的日志级联删除

### How to reproduce

手工删除过 t_ds_task_instance 、t_ds_process_instance、t_ds_relation_process_instance

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I will check this issue.
