### ISSUE TITLE
[Bug] [SQL] syntax error in `dolphinscheduler_postgresql.sql` 

### ISSUE THREAD

**Issue by jim-parsons** [apache/dolphinscheduler#7779]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

there is a syntax error in `dolphinscheduler_postgresql.sql`  in table `t_ds_task_definition` and `t_ds_task_definition_log`

![image](https://user-images.githubusercontent.com/20239172/147950076-a025a286-f729-497f-828a-5544d3a836c1.png)

so when i init db with postgrepsql it comed with error 
![image](https://user-images.githubusercontent.com/20239172/147950814-67012a2b-5112-4aac-a038-a5df5fc898f5.png)

### What you expected to happen

no error when user init sql in `dolphinscheduler_postgresql.sql` 

### How to reproduce

run the init sql in `dolphinscheduler_postgresql.sql` 

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
done.
