### ISSUE TITLE
[Feature][UI Next] Resource.

### ISSUE THREAD

**Issue by songjianet** [apache/dolphinscheduler#7785]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- [x] File Manage
- [x] Resource Manage
- [ ] Function Manage
- [x] Task Group Option
- [x] Task Group Queue

### Related issues

[#7332](https://github.com/apache/dolphinscheduler/issues/7332)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will complete `File Manage`.

**Comment by calvinjiang** [comment]
I will complete both of task group option and task group queue.

**Comment by devosend** [comment]
I will complete `Resource Manage`
