### ISSUE TITLE
[Bug] [API] querySimpleList return wrong projectCode

### ISSUE THREAD

**Issue by joyatcloudfall** [apache/dolphinscheduler#7789]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

querySimpleList method return projectCode the same as processDefinitionCode.

![image](https://user-images.githubusercontent.com/87688951/148031151-26959c71-5b18-4f1d-b391-92a23e3c307c.png)

### What you expected to happen

The projectCode should be 3933957767584.

### How to reproduce

Using projectCode to querySimpleList and check if the returned projectCode is the same as it supposes to be.

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I will check this issue.
