### ISSUE TITLE
[Feature]  Support for DAG-oriented programming

### ISSUE THREAD

**Issue by ustcliao** [apache/dolphinscheduler#779]
**Is your feature request related to a problem? Please describe.**
It is easy to describe the DAG throuth web ui. But it is difficult to manage and deploy the DAG process.

**Describe the solution you'd like**
Try to program the DAG by code, such as python.

**Describe alternatives you've considered**
ariflow

**Additional context**

**Comment by gaojun2048** [comment]
we will consider it later! thanks for a lot!

**Comment by gaojun2048** [comment]
please describe or translate this issue in English, thanks!
