### ISSUE TITLE
[Bug] [dolphinscheduler-api] WorkFlow RelationShip display error

### ISSUE THREAD

**Issue by ghost** [apache/dolphinscheduler#7799]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Current version 2.0.1 release

1. Creat 4 test flow , Test_4 is dependend on Test1,Test2,Test3
![image](https://user-images.githubusercontent.com/42712553/148156813-0659ffbe-8312-4b02-a22c-5dc29d3fdbd4.png)

2. On the WorkFlow RelationShip page, query buy Process Name Test_4, Test_3 is missing.
![image](https://user-images.githubusercontent.com/42712553/148156873-9e613f75-0733-4175-b145-8f0d3fb182c8.png)

### What you expected to happen

Test_3 could show on the releation page.

### How to reproduce

This issuse is happend at function WorkFlowLineageServiceImpl.recursiveWorkFlow()

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DingPengfei** [comment]
Can you provide the deails of your dependent configuration? I can't reproduce your issue in my local env

**Comment by ghost** [comment]
This issuse has been solved at 2.0.2-Release version.
