### ISSUE TITLE
add greenplum datasource

### ISSUE THREAD

**Issue by gaogen123** [apache/dolphinscheduler#7813]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

coud you  support GreenPlum6.x  datasource  in the next release?You know Greenplum is one of the largest open source MPP databases, and it has a large number of data warehouse users.

### Use case

Although Postgresql could  connected. However, we ran into a lot of problems when running Greenplum  procedures tasks concurrently with the postgresql driver in DS.
Such as the connection is interrupted during the task running or Other driving problems and so on.

### Related issues

Although Postgresql could  connected. However, we ran into a lot of problems when running Greenplum  procedures tasks concurrently with the postgresql driver in DS.
Such as the connection is interrupted during the task running or Other driving problems and so on.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Snorlaxa** [comment]
I got problems running sql on Aliyun ADB Postgresql with pg driver.
