### ISSUE TITLE
[Improvement] [dolphinscheduler-remote] Pong.java has a mistake 

### ISSUE THREAD

**Issue by tracehh** [apache/dolphinscheduler#7819]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Pong.java has a mistake

### What you expected to happen

review code

### How to reproduce

review code

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
> Pong.java has a mistake

Could you point specific mistake in `Pong.java` ?

**Comment by tracehh** [comment]
Thanks, you can see : https://github.com/apache/dolphinscheduler/pull/7822

**Comment by zhongjiajie** [comment]
I assigned this issue to you
