### ISSUE TITLE
[Bug] [docs] Unfriendliness and errors in the 2.0.1 deployment documents

### ISSUE THREAD

**Issue by Lucaszlei** [apache/dolphinscheduler#7844]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

docs link: https://dolphinscheduler.apache.org/zh-cn/docs/2.0.1/user_doc/guide/installation/pseudo-cluster.html
In the 2.0.1 pseudo-cluster deployment document, there are the following problems：

1. The `chown -R` operation mentioned in the following steps, the document did not mention where `dolphinscheduler-bin` was created or generated before this，Not friendly here
![图片](https://user-images.githubusercontent.com/56599784/148323864-25d37fbb-76db-4e67-b6c5-aab8c7114618.png)

2. The following message is wrong, and the database cannot be initialized by the `create-dolphinscheduler.sh` script in version 2.0.1
![图片](https://user-images.githubusercontent.com/56599784/148327184-93476f41-2dd7-4eb0-92bb-b8789549aee1.png)

3. Before starting the service, it is best to add the `su dolphinscheduler` operation prompt to prevent starting operations under non-deployment users
![图片](https://user-images.githubusercontent.com/56599784/148327313-cdafc765-3841-470a-b0b1-480b5c3bc498.png)

### What you expected to happen

See "what happend"

### How to reproduce

see 2.0.1 docs
https://dolphinscheduler.apache.org/zh-cn/docs/2.0.1/user_doc/guide/installation/pseudo-cluster.html

### Version

2.0.1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
@SunnyZ-L  Thanks for your feedback, I assigned to you since you check "Yes I am willing to submit a PR!" looking forward your contributions

**Comment by zhongjiajie** [comment]
@SunnyZ-L  Do you still work on this issue? We currently want to release 2.0.3, and we help this issue could close in version 2.0.3.

**Comment by Lucaszlei** [comment]
> @SunnyZ-L Do you still work on this issue? We currently want to release 2.0.3, and we help this issue could close in version 2.0.3.

I'm still working, submit a PR at the latest by the weekend

**Comment by zhongjiajie** [comment]
> > @SunnyZ-L Do you still work on this issue? We currently want to release 2.0.3, and we help this issue could close in version 2.0.3.
> 
> I'm still working, submit a PR at the latest by the weekend

Looking forward on it

**Comment by Lucaszlei** [comment]
> > > @SunnyZ-L Do you still work on this issue? We currently want to release 2.0.3, and we help this issue could close in version 2.0.3.
> > 
> > 
> > I'm still working, submit a PR at the latest by the weekend
> 
> Looking forward on it

PR submitted, PR link: https://github.com/apache/dolphinscheduler-website/pull/652
