### ISSUE TITLE
[Bug] [Edit User Info]  Problems caused by modifying the administrator user information.

### ISSUE THREAD

**Issue by songjianet** [apache/dolphinscheduler#7857]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

- User state

When I logged in as an administrator, I modified the user information, changed the administrator's status to disabled, and modified the administrator's user name, all interfaces were unavailable.

![image](https://user-images.githubusercontent.com/19239641/148392144-5ccf129a-4aa3-4a55-a86c-a370bdbe3896.png)

The same problem exists in the user management section.

![image](https://user-images.githubusercontent.com/19239641/148484579-20de2dc2-5a15-4666-bcb0-015f79bdd4f2.png)

- Authorized operation of admin user

The administrator should have all the permissions by default, and there is no need to perform authorization related operations.

![image](https://user-images.githubusercontent.com/19239641/148484192-34750689-0bf5-4bdc-bbe1-ef23b8b56b7b.png)

### What you expected to happen

Administrators cannot modify their own status, but they can modify the status of ordinary users. Ordinary users cannot modify their own status and the status of administrators and other ordinary users. The administrator does not need to assign any permissions to himself.

### How to reproduce

Log in with any identity to modify your personal status.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I will fix this issue.

**Comment by zhongjiajie** [comment]
I assigned to you

**Comment by zhongjiajie** [comment]
> I will fix this issue.

@calvinjiang Do you have any plan about how to do it? It seems we have other permission issues like that, maybe we should consider them together. Such as https://github.com/apache/dolphinscheduler/issues/7288

**Comment by calvinjiang** [comment]
@zhongjiajie I think that the user shouldn't have permission to disable its own account. But the account's name might need to be altered in some case.
