### ISSUE TITLE
[Bug] [MasterServer] memory map use id as key does not match value when task retry

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#7865]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/11962619/148477966-9e32694d-3c09-4401-a826-fb22db7a2891.png)
When I add log of `StateWheelExecuteThread.taskInstanceRetryCheckList`, I found that `taskInstanceRetryCheckList`,  a memory map use id as key does not match value. Because the retry task use the old task object and just change id, so the reference was changed too.

### What you expected to happen

The memory map data are correct.

### How to reproduce

run task fail and retry it.

### Version

2.0.1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jim-parsons** [comment]
what is `value.getId`, the value of `taskInstanceRetryCheckList` map is Integer

**Comment by caishunfeng** [comment]
> what is `value.getId`, the value of `taskInstanceRetryCheckList` map is Integer

`taskInstanceRetryCheckList` is a map<taskInstanceId, taskInstance>, so `value.getId` means `taskInstance.getId`, and it should be equal to the key.
But in some case like retry, it may be incorrect.
