### ISSUE TITLE
[Bug] [alert server] alert plugin Email show type attachment causes the alert service to fail.

### ISSUE THREAD

**Issue by Arnu-** [apache/dolphinscheduler#7874]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

在配置alert plugin的时候，选择Email时，显示方式(show_type)不能选择 attachment(附件）。一旦选择此方式，alert server就进入假死状态，不输入任何错误日志。也不再工作。只要t_ds_alert_plugin_instance表中存有配置了attachment的plugin信息，不管怎么重启都无效。即使删除了alert-plugin配置，不重启alert server，依然不会恢复。

### What you expected to happen

在配置alert plugin的时候，选择Email时，显示方式(show_type)不能选择 attachment(附件）。一旦选择此方式，alert server就进入假死状态，不输入任何错误日志。也不再工作。只要t_ds_alert_plugin_instance表中存有配置了attachment的plugin信息，不管怎么重启都无效。即使删除了alert-plugin配置，不重启alert server，依然不会恢复。

### How to reproduce

设置告警插件Email选show type ：attachment 或者 table attachment

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I will check this issue.

**Comment by ltcaxx** [comment]
Is this bug solved?

**Comment by SbloodyS** [comment]
> Is this bug solved?

Currently you can avoid this problem without selecting attachment or table attachment.

**Comment by ltcaxx** [comment]
我要用附件这个功能




爱数据的开发狗
***@***.***

大数据开发/分析


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月17日(星期四) 下午3:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] [Bug] [alert server] alert plugin Email show type attachment causes the alert service to fail. (Issue #7874)





  
Is this bug solved?
  
Currently you can avoid this problem without selecting attachment or table attachment.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caishunfeng** [comment]
associate issue: #8691

**Comment by Tianqi-Dotes** [comment]
will check it out

**Comment by Tianqi-Dotes** [comment]
Have tested this in dev, the function is okay but failed to send excel in 2.0.5.
Will tell the code differences between 'em.

**Comment by jay-col** [comment]
I encountered the same problem. When I chose to send an attachment or attachment form, I did not send an email. When I looked at the log file, there was a timeout task, which meant that attachment sending was not supported.
I need to send an attachment. When can I fix this bug?
Now I use 
DS version: 2.0.5 release.

**Comment by AuroraV** [comment]
i deploy 2.0.3, docker also met this problem, only docker recurrent; share：

1. found hang on `Sheet sheet = wb.createSheet();`may miss font, fix:
`sudo apt-get update`
`sudo apt-get install fontconfig`
link:`https://stackoverflow.com/questions/48989348/sxssf-workbook-createsheet-fails-on-linux-environments`

2. hang on `wb.write(fos);`, have no plan to fix, maybe related to docker images

now i use plan B to fix problem : rewrite export attachment, replace XLSX with CSV, avoid use poi
this plan only rebuild and replace `dolphinscheduler-alter-email-2.0.3.jar`

**Comment by zhongjiajie** [comment]
> Have tested this in dev, the function is okay but failed to send excel in 2.0.5.
Will tell the code differences between 'em.

Got it, I will add the milestone to 2.0.6

**Comment by Wilson-BT** [comment]
> > Have tested this in dev, the function is okay but failed to send excel in 2.0.5.
> > Will tell the code differences between 'em.
> 
> Got it, I will add the milestone to 2.0.6

Its caused by common-compress-1.4.1 and common-compress-1.19 version conflict, and the project maven package just has common-compress-1.4.1.

**Comment by JinyLeeChina** [comment]
@Tianqi-Dotes Can you check pick your pr to 2.0.7 ?
