### ISSUE TITLE
[Feature][deploy] Output log should under logs/ directory

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#7885]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I test our dev dist tarball. There is a `<server_name>.out` in the wrong directory, I think it should in the `<server_name>/logs/` dir
![image](https://user-images.githubusercontent.com/15820530/148551533-27d490da-9ff5-4724-bac6-6f753809aaae.png)

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/15820530/148991818-b0bd370e-cbdd-4a46-b9f0-0d150ec52e34.png">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
If someone is interested in this issue, feel free to take it, otherwise I would take it when I have space-time.

**Comment by SbloodyS** [comment]
I want to take this issue. Can you assign this to me?
