### ISSUE TITLE
[Bug] [api] When the project is authorized, it will generate a duplicate authorized project

### ISSUE THREAD

**Issue by Lucaszlei** [apache/dolphinscheduler#7896]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

step1, Authorize more than two projects to user a
step2, Cancel some of the projects that have been authorized to user a, please do not cancel all of them
step3, When project authorization is performed again, the list of authorized projects produces duplicate project names

The problem is shown in the following gif demonstration：
![问题描速](https://user-images.githubusercontent.com/56599784/148639491-659b7b18-56c6-4803-ae7d-4d9f5c9de463.gif)

### What you expected to happen

Do not generate duplicate authorized items

### How to reproduce

see 'what happened'

### Version

2.0.1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
Hi @SunnyZ-L , is pr submitted? Please also associate this issue

**Comment by Lucaszlei** [comment]
> Hi @SunnyZ-L , is pr submitted? Please also associate this issue

Complete the PR submission this week

**Comment by Lucaszlei** [comment]
> Hi @SunnyZ-L , is pr submitted? Please also associate this issue

PR submitted
