### ISSUE TITLE
[Bug] [SQL] sql/upgrade/2.0.2_schema/mysql/dolphinscheduler_dml.sql filename with a space at the end

### ISSUE THREAD

**Issue by zhuangchong** [apache/dolphinscheduler#7900]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

sql/upgrade/2.0.2_schema/mysql/dolphinscheduler_dml.sql filename with a space at the end

### What you expected to happen
![image](https://user-images.githubusercontent.com/37063904/148647412-fb60bdf5-cbd8-4d77-914a-e416bdbd74cc.png)

### How to reproduce

sql/upgrade/2.0.2_schema/mysql/dolphinscheduler_dml.sql filename with a space at the end

### Version

2.0.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
done
