### ISSUE TITLE
[Bug] [dolphinscheduler-server]  startProcess reentrant optimization

### ISSUE THREAD

**Issue by zwZjut** [apache/dolphinscheduler#7924]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

[Bug] [dolphinscheduler-server]  startProcess reentrant optimization

### Use case

[Bug] [dolphinscheduler-server]  startProcess reentrant optimization

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zwZjut** [comment]
rebuild hashtable

**Comment by brave-lee** [comment]
Can you describe the process of the bug in detail ?
