### ISSUE TITLE
[Feature][UI Next] Project.

### ISSUE THREAD

**Issue by songjianet** [apache/dolphinscheduler#7928]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- [x] List
- [x] Project Overview
- [x] Workflow Relationship
- [x] Workflow Definition
- [x] Task Definition
- [x] Workflow Instance
- [x] Task Instance
- [x] Form Component
- [x] Dag
- [x] SHELL @Amy0104 
- [x] SUB_PROCESS @labbomb 
- [x] PROCUDURE @calvinjiang
- [x] SQL @calvinjiang 
- [x] SPARK @Amy0104 
- [x] FLINK @devosend 
- [x] MR @Amy0104 
- [x] PYTHON @calvinjiang 
- [x] DEPENDENT @Amy0104 something wrong
- [x] HTTP @Amy0104
- [x] DATAX  @calvinjiang
- [x] PIGEON @labbomb 
- [x] SQOOP @Amy0104
- [x] CONDITIONS @Amy0104
- [x] DATA_QUALITY @Amy0104
- [x] SWITCH  @calvinjiang
- [x] SEATUNNEL  @calvinjiang
- [x] Workflow Definition Tree Chart
- [x] Workflow Instance gantt Chart

### Related issues

[#7332](https://github.com/apache/dolphinscheduler/issues/7332)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I will develop the form of python task.

**Comment by devosend** [comment]
I will develop the form of `flink` task.

**Comment by labbomb** [comment]
I will develop the form of SUB_PROCESS、PIGEON task.

**Comment by calvinjiang** [comment]
I will develop the form of SQL task.

**Comment by calvinjiang** [comment]
I will develop the form of PROCEDURE task.

**Comment by songjianet** [comment]
> I will develop the form of SUB_PROCESS、 DATAX、PIGEON task.

YYDS

**Comment by Amy0104** [comment]
SPARK,MR and DEPENDENT.

**Comment by Amy0104** [comment]
HTTP,SQOOP and CONDITIONS.

**Comment by calvinjiang** [comment]
I will develop the form of seatunnel task.

**Comment by calvinjiang** [comment]
I will develop the form of the switch task.

**Comment by songjianet** [comment]
> I will develop the form of the switch task.

thanks

**Comment by calvinjiang** [comment]
I'll develop the form of the DATAX task.

**Comment by calvinjiang** [comment]
I'll develop the tree of the workflow definition.
