### ISSUE TITLE
[Bug] [Common] Close the FileOutputStream in FileUtils.java file

### ISSUE THREAD

**Issue by Ivan0626** [apache/dolphinscheduler#7938]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 Close the FileOutputStream in FileUtils.java file
![image](https://user-images.githubusercontent.com/3198813/148888940-de4c394e-3ae4-4d2f-8951-c008a93e102c.png)

### What you expected to happen

 Close the FileOutputStream in FileUtils.java file

### How to reproduce

 Close the FileOutputStream in FileUtils.java file

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
done.
