### ISSUE TITLE
[Bug] [UI] Workflow definition details page out of order

### ISSUE THREAD

**Issue by chy5632** [apache/dolphinscheduler#7940]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

工作流定义详情页乱序，导致工作流很混乱，工作流多起来后很难管理
![微信图片_20220111164205](https://user-images.githubusercontent.com/56856218/148909334-7cd3f75b-d830-4a93-9003-4337e5cf91a4.png)

### What you expected to happen

工作流定义详情页有序

### How to reproduce

点击工作流定义页面

### Version

2.0.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
The process definition list is sorted in descending order according to the update time and online status.And the number is the ```t_ds_process_definition.id```. This is a self increasing primary key.
