### ISSUE TITLE
[Bug] [dolphinscheduler] dolphinscheduler-2.0.2 run docker,NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by ryuunami** [apache/dolphinscheduler#7942]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

docker-swarm_dolphinscheduler-master_1 logs:

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[ERROR] 2022-01-12 02:14:35.514 org.springframework.boot.SpringApplication:[843] - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'masterServer': Unsatisfied dependency expressed through field 'masterConfig'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'masterConfig': Unsatisfied dependency expressed through field 'failoverInterval'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'int'; nested exception is java.lang.NumberFormatException: For input string: ""

### What you expected to happen

none

### How to reproduce

centos7.6
$ tar -zxvf apache-dolphinscheduler-2.0.2-src.tar.gz
$ cd apache-dolphinscheduler-2.0.2-src/docker/docker-swarm
$ docker pull dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler:2.0.2
$ docker tag apache/dolphinscheduler:2.0.2 apache/dolphinscheduler:latest
$ docker-compose up -d

### Version

2.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by imom0** [comment]
#7904

**Comment by zhongjiajie** [comment]
It odd, this issue do not auto close after #7975 merged
