### ISSUE TITLE
[Feature] add Java SDK

### ISSUE THREAD

**Issue by fat-wen** [apache/dolphinscheduler#7947]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

hello，大家好，请问 DS 有 java client吗，或者 有对应的 开发SDK吗，我想用java 开发一个流程，有提供一个例子吗？

### Use case

hello，大家好，请问 DS 有 java client吗，或者 有对应的 开发SDK吗，我想用java 开发一个流程，有提供一个例子吗？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Squidyu** [comment]
I'll solve this problem.Before the new year, I will write a java client to support
这个问题我来处理，年前我会写一个client项目

**Comment by zhongjiajie** [comment]
I assign this issue to you

**Comment by lenboo** [comment]
The same as #7946  @Squidyu

**Comment by icodemo** [comment]
> I'll solve this problem.Before the new year, I will write a java client to support 这个问题我来处理，年前我会写一个client项目

Has The Java Client SDK been completed?
请问java client SDK已经完成了吗？

**Comment by zhongjiajie** [comment]
@icodemo Not yet, but this issue duplicated to #7946 so we close it
