### ISSUE TITLE
How to upgrade from 1.3.6 to the latest stable version 2.0.2 based on kubernetes

### ISSUE THREAD

**Issue by gaomiup20** [apache/dolphinscheduler#7948]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

From the upgrade documents recommended by the official documents, you can only see the upgrade based on the virtual machine deployment mode, not kubernetes Therefore, refer to the previous upgrade method from the source code based on tag: 2.0.2. Dolphin scheduler / SQL / upgrade / 2.0.2 was not found_ Schema, only dolphin scheduler / SQL / upgrade / 2.0.1 schema is the latest. Is it missing?

### What you expected to happen

It is hoped that the kubernetes based deployment upgrade method will be added to the upgrade document recommended by the official document, and the dolphin scheduler / SQL / upgrade / in tag: 2.0.2 will be completed,

### How to reproduce

Try upgrading 1.3.6 to 2.0.2 based on kubernetes

### Anything else

There is nothing for the time being

### Version

2.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaomiup20** [comment]
Found out how to upgrade in kubernetes

**Comment by yzkIvory** [comment]
> Found out how to upgrade in kubernetes

hello，how to upgrade in kubernetes。I haven't found a way yet。
