### ISSUE TITLE
[Bug] [dolphinscheduler-api]  The global parameters of the sub_process node are not passed to the associated workflow task

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#7962]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. Create workflow A and the task is shell_ 1. Global parameter setting id = 1

![image](https://user-images.githubusercontent.com/95271106/149119943-2e8cd71e-8c85-446e-a0f6-a4579b58e329.png)

![image](https://user-images.githubusercontent.com/95271106/149095105-be527c91-01bf-4813-b1be-397b6de9efa3.png)
2. Sub node B is associated with workflow A
![image](https://user-images.githubusercontent.com/95271106/149119233-df76f327-9c46-4581-8cdf-f5904042febc.png)
3. set  id = 3 of the global parameter for the Sub node B , Run Sub node B, shell_1'id is 1, should be 3
 ![image](https://user-images.githubusercontent.com/95271106/149118848-4101e85b-3826-45b2-8c13-e5168374dd40.png)

### What you expected to happen

.

### How to reproduce

.

### Version

2.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
@ruanwenjun Hello wenjun, can you solve this problem?

**Comment by ruanwenjun** [comment]
@janeHe13 Thanks for your feedback, this is a bug. I have submitted a pr to fix in dev branch #7969.
And this will be released in 2.0.3.
