### ISSUE TITLE
[Bug] [DataSource] Failed to add the Hive dataSource with Kerberos authentication. 

### ISSUE THREAD

**Issue by Jiangxiaoyuan** [apache/dolphinscheduler#7964]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

根据文档2.0.2 中hive数据源下方配置信息，对  **hadoop.security.authentication.startup.state** **java.security.krb5.conf.path**
**login.user.keytab.username**和**login.user.keytab.path**进行配置，连接hive时，报错
![image](https://user-images.githubusercontent.com/35806990/149118782-ee59cc0c-0a56-402c-aaac-7e24f712a83b.png)
日志
![image](https://user-images.githubusercontent.com/35806990/149119966-45869b44-0e8f-48b3-91f8-5ddcfe06ab9d.png)
![image](https://user-images.githubusercontent.com/35806990/149120136-7754be77-c34a-4481-b3e2-894a29736dd2.png)

其中 **principal**应该配置在哪里呢
![image](https://user-images.githubusercontent.com/35806990/149109780-4b8f12ba-9ebf-492d-89fe-9fd39d3f42bb.png)

@SbloodyS 

### What you expected to happen

add new hive datasource success.

### How to reproduce

add new hive datasource success.

### Version

2.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuxt2015** [comment]
应该配置在JDBC连接参数中, 但是2.0.2同时存在另外一个bug, 连接参数中不能出现'@'字符, 我们是通过修改代码重新编译解决的, 我计划提交pr
![image](https://user-images.githubusercontent.com/13765310/150289799-7dd8d293-058a-4865-ae8a-bee6384d73fc.png)

**Comment by caishunfeng** [comment]
> 应该配置在JDBC连接参数中, 但是2.0.2同时存在另外一个bug, 连接参数中不能出现'@'字符, 我们是通过修改代码重新编译解决的, 我计划提交pr ![image](https://user-images.githubusercontent.com/13765310/150289799-7dd8d293-058a-4865-ae8a-bee6384d73fc.png)

the relative issue: #8135

**Comment by caishunfeng** [comment]
> 应该配置在JDBC连接参数中, 但是2.0.2同时存在另外一个bug, 连接参数中不能出现'@'字符, 我们是通过修改代码重新编译解决的, 我计划提交pr ![image](https://user-images.githubusercontent.com/13765310/150289799-7dd8d293-058a-4865-ae8a-bee6384d73fc.png)

Thanks for your reply. And this issue will be closed.
