### ISSUE TITLE
[Bug] [dolphinscheduler-master] After deleting the running workflow, the master keeps brushing the error log

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#7986]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/95271106/149263375-61e11064-1c79-4df5-b6a8-69cf3d311cde.png)

### What you expected to happen

.

### How to reproduce

.

### Version

2.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by janeHe13** [comment]
When deleting running and non running workflow instances at the same time, the page is not refreshed after an error is reported, resulting in the non running workflow instance has been deleted, but it can be deleted repeatedly in the UI


![image](https://user-images.githubusercontent.com/95271106/149704187-c1fbbe21-bbdd-4c58-90cc-8404097865c8.png)

**Comment by caishunfeng** [comment]
@songjianet UI need to disable deletion of running workflow too.
