### ISSUE TITLE
[Bug][Api] process update user name is wrong

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#8000]
After admin modifies the workflow of ordinary user Jane, the modified user is still Jane , should be admin

![image](https://user-images.githubusercontent.com/95271106/149276076-f232fbdf-b66a-48a3-9f76-db4315d518bb.png)

_Originally posted by @janeHe13 in https://github.com/apache/dolphinscheduler/issues/7777#issuecomment-1011830937_

**Comment by calvinjiang** [comment]
I will check this issue.

**Comment by calvinjiang** [comment]
This issue seems to be fixed in the branch of dev.

**Comment by caishunfeng** [comment]
> This issue seems to be fixed in the branch of dev.

hi @calvinjiang if this issue was fixed in dev, can you link to the original issue and submit a cherry-pick pr for 2.0.3?
