### ISSUE TITLE
[Bug] [Script]The script of install.sh can only start one work-server node

### ISSUE THREAD

**Issue by shangeyao** [apache/dolphinscheduler#8004]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/42203474/149322893-c31509c8-be96-4bee-9c52-ac20607eefe3.png)
To be exact, there is a problem with the script of start-all.sh

### What you expected to happen

Above

### How to reproduce

Above

### Anything else

None

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by paul8263** [comment]
Got the same problem.
I would like to take this.

**Comment by zhongjiajie** [comment]
assigned
