### ISSUE TITLE
[Bug] Frond-ends edit bug

### ISSUE THREAD

**Issue by Wilson-BT** [apache/dolphinscheduler#8010]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

version 2.0.2
![image](https://user-images.githubusercontent.com/40427110/149343586-5cbfb039-9ba2-490e-ad87-60b657befa31.png)
as above picture，when we click the full screen buttern，we can not edit dag.
![image](https://user-images.githubusercontent.com/40427110/149343959-044f96c0-bf26-4c19-b588-6cdebaf5b7c3.png)

### What you expected to happen

as above

### How to reproduce

as above

### Version

2.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I will fix this issue.
