### ISSUE TITLE
[Feature][Document] Add example and notice about task type SubProcess

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#8017]
Due to our tasks task description is not containing some detail, and I think we should add a new section notice and give an example to the task sub-process in the document https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/task/sub-process.html

**Comment by zhongjiajie** [comment]
I add a PR in https://github.com/apache/dolphinscheduler-website/pull/638, maybe someone who is interested in this feature could take it as an example

**Comment by AntAndfish** [comment]
I am interested in implementing this task, how do i edit the document.

**Comment by zhongjiajie** [comment]
Hi @AntAndfish , thanks and you should change both version 2.0.2 and dev directory in https://github.com/apache/dolphinscheduler-website/tree/master/docs. Please remember you should change both zh an en version here.

**Comment by zhongjiajie** [comment]
For example, you should change https://github.com/apache/dolphinscheduler-website/blob/master/docs/en-us/2.0.2/user_doc/guide/task/sub-process.md for version 2.0.2 version

**Comment by zhongjiajie** [comment]
I assigned it to you, looking forward your contribution.

**Comment by zhongjiajie** [comment]
Hi @AntAndfish , are you still work on this issue?

**Comment by QuakeWang** [comment]
> Hi @AntAndfish , are you still work on this issue?

Let me do it. Please assign to me : ) @zhongjiajie

**Comment by zhongjiajie** [comment]
> > Hi @AntAndfish , are you still work on this issue?
> 
> Let me do it. Please assign to me : ) @zhongjiajie

Done, looking forward your contribution

**Comment by zhongjiajie** [comment]
Also cc @AntAndfish , I assigned to @QuakeWang now, if you interested it the doc, you could see https://github.com/apache/dolphinscheduler/labels/document for more detail
