### ISSUE TITLE
[Feature][Document] Add example and notice about task type SQL

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#8020]
Due to our tasks task description is not containing some detail, and I think we should add a new section notice and give an example to the task sql in the document https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/task/sql.html

**Comment by zhongjiajie** [comment]
I add a PR in apache/dolphinscheduler-website#638, maybe someone who is interested in this feature could take it as an example

**Comment by hongshuboy** [comment]
can i try it

**Comment by zhongjiajie** [comment]
@hongshuboy Great! I assigned this to you, looking forward your contribution.
