### ISSUE TITLE
[Feature][Document] Add example and notice about task type MapReduce

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#8022]
Due to our tasks task description is not containing some detail, and I think we should add a new section notice and give an example to the task map-reduce in the document https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/task/map-reduce.html

**Comment by zhongjiajie** [comment]
I add a PR in apache/dolphinscheduler-website#638, maybe someone who is interested in this feature could take it as an example

**Comment by QuakeWang** [comment]
Please assign it to me, I will do it later.

**Comment by zhongjiajie** [comment]
@QuakeWang  Looking forward your contribution

**Comment by QuakeWang** [comment]
This task has been completed.

ref: https://github.com/apache/dolphinscheduler-website/pull/669

**Comment by zhongjiajie** [comment]
closed by https://github.com/apache/dolphinscheduler-website/pull/669 
FYI @QuakeWang, I add some suggestions about how to relate PR and issue in https://github.com/apache/dolphinscheduler-website/pull/669#issuecomment-1037094363
