### ISSUE TITLE
[Feature][Document] Add example and notice about task type Python

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#8023]
Due to our tasks task description is not containing some detail, and I think we should add a new section notice and give an example to the task python in the document https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/task/python.html

**Comment by zhongjiajie** [comment]
I add a PR in apache/dolphinscheduler-website#638, maybe someone who is interested in this feature could take it as an example

**Comment by EricGao888** [comment]
May I take this one? Thx!

**Comment by zhongjiajie** [comment]
@EricGao888  Of cause, I assigned to you, looking forward your contribution.

**Comment by zhongjiajie** [comment]
> I add a PR in [apache/dolphinscheduler-website#638](https://github.com/apache/dolphinscheduler-website/pull/638), maybe someone who is interested in this feature could take it as an example

FYI, I have already add an example in the shell task https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/task/shell.html

**Comment by EricGao888** [comment]
PR link: https://github.com/apache/dolphinscheduler-website/pull/713
