### ISSUE TITLE
[Feature][Document] Add example and notice about task type Flink

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#8024]
Due to our tasks task description is not containing some detail, and I think we should add a new section notice and give an example to the task flink in the document https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/task/flink.html

**Comment by zhongjiajie** [comment]
I add a PR in apache/dolphinscheduler-website#638, maybe someone who is interested in this feature could take it as an example

**Comment by QuakeWang** [comment]
Please assign it to me : )

**Comment by zhongjiajie** [comment]
@QuakeWang  Looking forward your contribution
