### ISSUE TITLE
[Feature][Document] Add example and notice about task type HTTP

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#8025]
Due to our tasks task description is not containing some detail, and I think we should add a new section notice and give an example to the task http in the document https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/task/http.html

**Comment by zhongjiajie** [comment]
I add a PR in apache/dolphinscheduler-website#638, maybe someone who is interested in this feature could take it as an example

**Comment by zhongjiajie** [comment]
Add example about how to post json data. source from slack https://asf-dolphinscheduler.slack.com/archives/C01L3LB9YMP/p1645524470672679?thread_ts=1645083434.795169&cid=C01L3LB9YMP

**Comment by QuakeWang** [comment]
I will do this task, please assign it to me. @zhongjiajie

**Comment by zhongjiajie** [comment]
I assigned it to you ❤️
