### ISSUE TITLE
[Feature][Document] Add example and notice about task type DataX

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#8026]
Due to our tasks task description is not containing some detail, and I think we should add a new section notice and give an example to the task datax in the document https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/task/datax.html

**Comment by zhongjiajie** [comment]
I add a PR in apache/dolphinscheduler-website#638, maybe someone who is interested in this feature could take it as an example

**Comment by QuakeWang** [comment]
I will do this task : )

**Comment by zhongjiajie** [comment]
I assigned it to you, looking forward your contribution
