### ISSUE TITLE
[Feature][Document] Add example and notice about task type Pigeon

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#8027]
Due to our tasks task description is not containing some detail, and I think we should add a new section notice and give an example to the task pigeon in the document https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/task/pigeon.html

**Comment by zhongjiajie** [comment]
I add a PR in apache/dolphinscheduler-website#638, maybe someone who is interested in this feature could take it as an example

**Comment by QuakeWang** [comment]
Please assign it to me, I will do this task.

**Comment by zhongjiajie** [comment]
I assigned to you now

**Comment by drriguz** [comment]
I could not found example or documents for creating a Pigeon task,
by the way the link [DolphinScheduler Task Parameters Appendix](https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/task/appendix.md#default-task-parameters) inside https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/task/pigeon.html is no longer working.

**Comment by SbloodyS** [comment]
Closing due to task have been removed.
