### ISSUE TITLE
[Feature][Document] Add example and notice about task type Switch

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#8029]
Due to our tasks task description is not containing some detail, and I think we should add a new section notice and give an example to the task switch in the document https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/task/switch.html

**Comment by zhongjiajie** [comment]
I add a PR in apache/dolphinscheduler-website#638, maybe someone who is interested in this feature could take it as an example

**Comment by huangchenguang123** [comment]
@zhongjiajie i want to fix this issues

**Comment by zhongjiajie** [comment]
Looking good, and I will assigned it to you
