### ISSUE TITLE
[Feature][Document] Add example and notice about task type seatunnel

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#8031]
We missing task seatunnel in our document, and remember should also add task description with some detail, and give an example in the document

**Comment by zhongjiajie** [comment]
I add a PR in apache/dolphinscheduler-website#638, maybe someone who is interested in this feature could take it as an example

**Comment by chincloud** [comment]
I will do this task.

**Comment by huahuacheng** [comment]
I'm interested. May I take this one? QAQ

**Comment by EricGao888** [comment]
> I'm interested. May I take this one? QAQ

@huahuacheng Great! Looking forward to your PR!

**Comment by EricGao888** [comment]
> I'm interested. May I take this one? QAQ

@huahuacheng Looks like we have already had the docs but forgot to close this issue. However, you still could polish this doc if you like to. Thanks. https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/guide/task/seatunnel.md

**Comment by EricGao888** [comment]
Closed due to inactivity.
