### ISSUE TITLE
[Bug] [dolphinscheduler-api,dolphinscheduler-worker] The timeout length and check interval of dependency check are not effective

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#8034]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.The timeout length and check interval of dependency check are not effective
2.After timeout, the task status is always running and will not fail

![image](https://user-images.githubusercontent.com/95271106/149441907-f45fe3a9-00ad-4eb5-bcf7-b164f587f89c.png)
![image](https://user-images.githubusercontent.com/95271106/149441975-193724fe-bb65-4577-aaba-a7db509d8cb4.png)

### What you expected to happen

.

### How to reproduce

.

### Version

2.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
The  feature "waiting depend node start" is currently inactive,  i suggest disable this feature on the ui, we can improve it and  open this function later.
