### ISSUE TITLE
[Bug] [dolphinscheduler] Edit the historical workflow , prompt duplicate key when saving

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#8043]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/95271106/149464151-cefd5efe-69be-4c6e-9b93-7d73f90cbbdd.png)

### What you expected to happen

.

### How to reproduce

.

### Version

2.0.3-prepare

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DHBin** [comment]
i want to solve it. pr: https://github.com/apache/dolphinscheduler/pull/8033

**Comment by zhongjiajie** [comment]
Little tips for @caishunfeng , next time when you review issue, you could remove label `waiting for reply`, accoding to https://dolphinscheduler.apache.org/en-us/community/join/review.html (search keyword `Remove label Waiting for reply after replying`)

**Comment by caishunfeng** [comment]
> Little tips for @caishunfeng , next time when you review issue, you could remove label `waiting for reply`, accoding to https://dolphinscheduler.apache.org/en-us/community/join/review.html (search keyword `Remove label Waiting for reply after replying`)

OK, thanks for your tips.
