### ISSUE TITLE
[Bug] [UI] Forbidden tasks need to be represented by a forbidden icon

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#8050]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/95271106/149500761-899fb44d-430c-402e-8f09-83fdb90290a0.png)

### What you expected to happen

。

### How to reproduce

。

### Version

2.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I will fix this issue.
