### ISSUE TITLE
[Bug] [Environment Edit Worker Group] Edit the bug of worker grouping in environment management.

### ISSUE THREAD

**Issue by songjianet** [apache/dolphinscheduler#8056]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### There are problems in Dev and 202 and 203

- Create a new environment, configure workers, and select multiple groups
![b2582efd4dee1545eabd94af875ee51](https://user-images.githubusercontent.com/19239641/149605118-16ed1371-df46-4712-8fe4-961dfc7abafc.png)
Edit this data and delete two groups.
![27efec46513e5e8e1b52a3aa3402913](https://user-images.githubusercontent.com/19239641/149605122-25d4df15-ac8a-4a97-8d6f-2760823d95fb.png)
Edit interface request succeeded.
![e68d65e7f2c0957af979d2693698a9c](https://user-images.githubusercontent.com/19239641/149605125-a51c732e-eb7a-4f7e-9e5c-568d98350347.png)
The list interface returns no group.
![ea9c89554aa1bc17194125d3cc7a627](https://user-images.githubusercontent.com/19239641/149605130-9fa8f586-29a7-4038-8c05-e8510b2e95ff.png)
![9ec424f4d71a6fc3ca139f872c38f2e](https://user-images.githubusercontent.com/19239641/149605181-1d20ac5d-604d-4d7a-8fad-165a4d7d0815.png)

### What you expected to happen

After editing the calling interface, the worker group retains a piece of data that should be returned in the list interface, but the data returned from the list interface is empty.

### How to reproduce

For the data of the new environment, the worker selects multiple data and edits the data just created. The worker keeps at least one data, and then the data returned from the list interface is empty

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I will fix this issue.
