### ISSUE TITLE
[Bug] [dolphinscheduler] Error when switching from dev to 2.0.2-release branch

### ISSUE THREAD

**Issue by miki-hmt** [apache/dolphinscheduler#8062]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/45377370/149622153-db4fd6a1-52a6-4891-aa9d-485d575ccf9e.png)
切换分支的时候，提示报错：
invalid path 'dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.2_schema/mysql/dolphinscheduler_dml.sql '

请问一下是什么原因？

### What you expected to happen

帮忙提供一下解决思路

### How to reproduce

从dev切换分支2.0.2之后的时候，提示报错，切换其他分支都是正常的

### Version

2.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
the same issue #7900
