### ISSUE TITLE
[Bug] [dolphinscheduler-worker] Timeout alarm no alarm notification sent 

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#8077]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/95271106/149695484-099b79c2-44db-40f6-a22d-b1ef96b341f9.png)
The worker log is as follows

![image](https://user-images.githubusercontent.com/95271106/149695562-944f5c1a-af8f-4565-a879-01d69d6840ce.png)

### What you expected to happen

.

### How to reproduce

.

### Version

2.0.3-prepare

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
@zhuangchong can you take a look for this issue? It seems that the worker throw exception when run timeout, and the alert flag is always false.

**Comment by zhuangchong** [comment]
The current phenomenon is that the timeout alarm is cyclically detected every 5s. When the task runs successfully or fails during the waiting period for detection, the timeout alarm will not be triggered.

If the task fails, you can select the failure alarm, and select the failure alarm in the configuration notification policy option when executing the workflow.

I understand that the current problem is not a problem that needs to be solved urgently and can be optimized in a later version.

**Comment by brave-lee** [comment]
What is the final result and whether it is related PR ? @zhuangchong

**Comment by zhuangchong** [comment]
This is not a bug, only one of the timeout alarm and failure alarm will occur. The current architecture is that the worker mainly handles the timeout failure, and the master mainly handles the timeout alarm. We can take this thing as an optimization work and put it on the master service for execution.
This is not an urgent matter, it can be done later.
