### ISSUE TITLE
Switch process definition version error

### ISSUE THREAD

**Issue by jasonliangyc** [apache/dolphinscheduler#8080]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have installed the dolphinscheduler by the steps: [https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/guide/installation/pseudo-cluster.html]
and the installation was successful. The errors occur after i did below steps:
1. created a project
2. created a process in that project
3. modified the process several times to generate different versions of that process
4. clicked the 'Version Info' of that process
5. random clicked the 'Switch this vesion' or 'Delete' buttion
<img width="750" alt="1642389639" src="https://user-images.githubusercontent.com/97863756/149703625-066b6dfc-ab4e-4780-bdbc-305bee8c8c38.png">
<img width="765" alt="1642390153" src="https://user-images.githubusercontent.com/97863756/149703768-d16abaf6-4660-4f4c-9c65-9d08d3f19432.png">

### What you expected to happen

Switch different vesion of the process successfuly

### How to reproduce

see 'What happened'

### Anything else

No

### Version

2.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
fixed in #8207
