### ISSUE TITLE
[Bug] [DataSource] Connect to DB2 error

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8095]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```
Failed to load driver class com.ibm.db2.jcc.DB2Driver in either of HikariConfig class loader or Thread context classloader
```

### What you expected to happen

connect successfully

### How to reproduce

connect successfully.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
I thinks we should fix this bug. we should support all datasource we have support before.

**Comment by SbloodyS** [comment]
Related issue: #8099 

@zhongjiajie I found that both Oracle and DB2 are paid software. Do these dependencies meet our policy? Or do we need to operate like MySQL?

**Comment by zhongjiajie** [comment]
> Related issue: #8099
> 
> @zhongjiajie I found that both Oracle and DB2 are paid software. Do these dependencies meet our policy? Or do we need to operate like MySQL?

I am not familiar with BD2, but I notice that Oracle have a XE version and it could be using in test https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance

**Comment by SbloodyS** [comment]
> I am not familiar with BD2, but I notice that Oracle have a XE version and it could be using in test 
https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance

I have test this image in ci yesterday. The size of this image is almost 7GB. It took almost 45 minutes(Building 30 min && 
Initialization 15 min). And I also test this image in my private server(16c 64GB). It still took almost 15 minutes. It seems impossible to use this image in ci.

I think the problem of oracle image is similar to hadoop related images.Just as I mentioned in #8085.

**Comment by zhongjiajie** [comment]
OMG, it take such a long time.
