### ISSUE TITLE
[Bug] [UI] After editing the workflow, the operation bar background does not cover the table content

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#8097]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/95271106/149870159-4c9ac42c-7492-4588-99d1-65f7cc8c6269.png)

### What you expected to happen

。

### How to reproduce

。

### Version

2.0.3-prepare

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your return. I will take a look at this problem and evaluate the scope of changes. If the scope of changes is large, the changes may be abandoned, but this problem will be solved in the new ui.

**Comment by songjianet** [comment]
It would take too much work to fix this issue, and it doesn't have much impact right now, so I'll close this issue.
