### ISSUE TITLE
[Bug] [Worker/Master]  Data duplication caused by worker faking death 

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#8110]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. Because of cpu load is too high, worker lost connection with Zookeeper.
2. Master failover the worker and restart the tasks, but cannot kill the tasks.
3. Then the same  task would be run twice and result data would be duplicate.

### What you expected to happen

1. Worker should check resource before submitting task to execution thread.
2. Can worker actively reduce CPU load through killing task ?

### How to reproduce

1. CPU load  is too high: 
![image](https://user-images.githubusercontent.com/29528966/149973563-b8f5c39a-9930-4ab2-8997-8416eac44430.png)
2. worker lost connection with zk:
![image](https://user-images.githubusercontent.com/29528966/149975735-5e70fd4a-0b01-4e0b-a7bf-452f3f11eefc.png)

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by delong1985** [comment]
hi i also have the similar problem

**Comment by caishunfeng** [comment]
What's the task type? Is it a yarn manage task?

**Comment by brave-lee** [comment]
Submit the yarn task through the shell. When the workload of the worker is relatively high, the shell task that has been started has not been submitted to the yarn cluster. The master has fault tolerance. When killing the yarn task, the appid is not found. The master schedules the task to other workers. When the workload of the worker is lower, the shell submits the task to yarn. At this time, the yarn cluster has two identical tasks, Data duplication will occur
