### ISSUE TITLE
[Bug] [dolphinscheduler-api] After editing the query statement of the SQL node, the SQL statement before editing is executed after the workflow is run 

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#8112]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.When creating a new SQL node, the SQL statement is ‘select * from t_ds_user’
![image](https://user-images.githubusercontent.com/95271106/150052696-23960f5d-f559-40a6-9aa5-20b5844eb1ac.png)
2.After modifying the SQL node, the SQL statement is ‘select * from t_ds_version’

![image](https://user-images.githubusercontent.com/95271106/150052868-ea24fd37-b169-47c6-a06b-5dd527b49183.png)
3.Run the workflow, and the executed SQL statement is ‘select * from t_ds_user’, should be  ‘select * from t_ds_version’

### What you expected to happen

.

### How to reproduce

.

### Version

2.0.3-prepare

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Because the version doesn't match between processTaskRelation and taskDefinition
The relative issue: #8043

**Comment by zhuangchong** [comment]
done.
