### ISSUE TITLE
[Feature][api] "Create Time" update "operate time" for "Version Info" of "process definition"

### ISSUE THREAD

**Issue by seagle-yuan** [apache/dolphinscheduler#8116]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I want to know the time when I update the "process definition"。Because there only shows their  "create time"。and all versions  have the same "create time"。so I wonder we can update this column to "operate time" 
![59646687-FF4C-4121-8F98-E7FFAC773323](https://user-images.githubusercontent.com/13429553/150067295-6994773a-87cf-4004-9a1b-87abf9ed79c2.JPG)

### Use case

I want to update "Create time" to "operate time"

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jim-parsons** [comment]
I got this

![image](https://user-images.githubusercontent.com/20239172/150099131-a99887ac-c942-4316-a3b8-f9093121e2d3.png)

**Comment by seagle-yuan** [comment]
> I got this
> 
> ![image](https://user-images.githubusercontent.com/20239172/150099131-a99887ac-c942-4316-a3b8-f9093121e2d3.png)

which version?
