### ISSUE TITLE
[Bug] [DataSource] jdbc connect parameters can not input '@'

### ISSUE THREAD

**Issue by zhuxt2015** [apache/dolphinscheduler#8135]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In 2.0.2 version, when I create hive datasource with kerberos, then need input principal to jdbc connect parameters, 
when Test connect , The error is reported below
![image](https://user-images.githubusercontent.com/13765310/150292211-af7d1fb0-51f5-4eab-990e-5bf223248577.png)

### What you expected to happen

when input correct  principal, can connect to hive
![image](https://user-images.githubusercontent.com/13765310/150292515-7f4dbd33-d91d-416e-b300-3d9db9e19500.png)

### How to reproduce

in AbstractDatasourceProcessor.java,  modify PARAMS_PATTER  field, appropriate value is  
> private static final PARAMS_PATTER = Pattern.compile("^[a-zA-Z0-9\\-\\_\\/\\@\\.]+$");

### Version

2.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JYInMyHeart** [comment]
`AbstractDataSourceProcessor.PARAMS_PATTER`  doesn't contain `@`. Is this a feature?

**Comment by zhuxt2015** [comment]
> `AbstractDataSourceProcessor.PARAMS_PATTER` doesn't contain `@`. Is this a feature?

I think it's a bug that resulted can not input '@' or '.'

**Comment by davidzollo** [comment]
> > `AbstractDataSourceProcessor.PARAMS_PATTER` doesn't contain `@`. Is this a feature?
> 
> I think it's a bug that resulted can not input '@' or '.'

you can submit a PR, thx
