### ISSUE TITLE
[Bug] [UI] The task name is not displayed completely

### ISSUE THREAD

**Issue by mchcz** [apache/dolphinscheduler#8163]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The names of the people in the workflow cannot be displayed in full and cannot be searched.
Most of our workflows have a lot of tasks, which can be cumbersome.

![image](https://user-images.githubusercontent.com/18095523/150718578-adc14a90-b860-485e-a41d-3b751491b70e.png)

### What you expected to happen

The task name can be displayed in its entirety.

### How to reproduce

see "What happened"

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I'll fix this issue.
