### ISSUE TITLE
[Bug] [UI] After you save the workflow, it jumps to the workflow list page

### ISSUE THREAD

**Issue by mchcz** [apache/dolphinscheduler#8169]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Developers generally write a task to save once, and then jump to the workflow list page, whether it can stay on the workflow editing page like version 1.3.X, wait for all tasks to be written, and then click the close button to leave the current page.

Like this：

![image](https://user-images.githubusercontent.com/18095523/150745585-a7faf0f5-142f-49df-b090-7d7f4e9b00cd.png)

### What you expected to happen

Do not leave the workflow edit page after saving.

### How to reproduce

See "What happened"

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by springmonster** [comment]
#8198

**Comment by brave-lee** [comment]
This seems to have fixed the bug. I will close the issue.
