### ISSUE TITLE
[Bug] [UI] SUB_PROCESS Clicking into the child node does not react

### ISSUE THREAD

**Issue by mchcz** [apache/dolphinscheduler#8170]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

**Workflow Definition List page**, select Workflow, Enter, Select SUB_PROCESS Component Click into child nodes without reaction.

note：There is no problem with this feature of the workflow instance page.

ERROR:

![5c49f82876d21d5a445b9c76d650622](https://user-images.githubusercontent.com/18095523/153817297-13a04d85-2aa5-4504-b13f-a4361146cade.png)

![image](https://user-images.githubusercontent.com/18095523/150746570-d688cb8e-6155-4d21-806f-ee1bce0db1fc.png)

### What you expected to happen

Child nodes can be entered.

### How to reproduce

See "What happened"

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
hi @mchcz, what's the meaning of `select Workflow, Enter`? can you support a gif for reproduce this issue?
