### ISSUE TITLE
[Bug] [UI] On the Workflow List page, enter the workflow name query, whether to query by Enter

### ISSUE THREAD

**Issue by mchcz** [apache/dolphinscheduler#8171]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

On the Workflow List page, enter the workflow name query, whether to query by Enter.

Like version 1.3.X, press Enter to submit without having to click the search button to guess the submission.

### What you expected to happen

Press Enter to search.

### How to reproduce

See "What happened"

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
I tried the interaction between 1.3 and 2.0 workflow lists. They are the same. It need to click Submit. Please confirm your question

**Comment by caishunfeng** [comment]
same issue: #7457
so this issue will be close.
