### ISSUE TITLE
[Bug] [UI] Right-clicking the workflow does not respond

### ISSUE THREAD

**Issue by mchcz** [apache/dolphinscheduler#8172]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.Select a workflow with many tasks.
2.Modify && save && online.
3.Enter the workflow, select a task, and right-click without responding.

This problem was occasional, and the video screen was shown to @lenboo at that time.

4.Format the DAG, select the "grid" layout ("dagre" layout is not OK), save, and right-click to use again.

### What you expected to happen

At any time, the right button can be used normally.

### How to reproduce

See "What happened"

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
I didn't reproduce this problem, please confirm
