### ISSUE TITLE
[Bug] [API] Save the workflow error

### ISSUE THREAD

**Issue by mchcz** [apache/dolphinscheduler#8173]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.Select a workflow with many tasks.
2.Modify && save && online.
3.Format the DAG, select the "grid" layout , save.
4.Leave the workflow editing page and open it again, save，got error，this problem is occasional.

Like this:

![image](https://user-images.githubusercontent.com/18095523/150748796-1741b73a-ace4-470f-8464-d252e359c650.png)

![image](https://user-images.githubusercontent.com/18095523/150893918-e12eeca9-3200-44bd-ab8b-82267d62f69b.png)

### What you expected to happen

Can be saved normally.

### How to reproduce

See "What happened"

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jim-parsons** [comment]
see this #8043

**Comment by mchcz** [comment]
Not the same problem.

update process from process definition list page, got this error.

**Comment by brave-lee** [comment]
related #8334
