### ISSUE TITLE
[Bug] [UI] On the workflow content page, the Search Node button can support fuzzy search

### ISSUE THREAD

**Issue by mchcz** [apache/dolphinscheduler#8175]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

On the workflow content page, the Search Node button can support fuzzy search.

Currently, only exact lookup is supported.

When there are many tasks in the workflow, only part of the task name is remembered, so you need to fuzzy search.

![image](https://user-images.githubusercontent.com/18095523/150750602-0e01bdb9-dc07-4fe2-b66b-068505ae99e0.png)

### What you expected to happen

It can support fuzzy search.

### How to reproduce

See "What happened"

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
This I need to look into, this feature doesn't seem to be a search box on dev.

**Comment by calvinjiang** [comment]
This issue seems to be fixed lately.

**Comment by calvinjiang** [comment]
Please take a look at this issue #7493.

**Comment by caishunfeng** [comment]
> Please take a look at this issue #7493.

It's the same issue, so this issue will be closed.
