### ISSUE TITLE
[Bug] [UI] There is no obvious difference between a disabled task and a normal task, and it is not easy to identify

### ISSUE THREAD

**Issue by mchcz** [apache/dolphinscheduler#8181]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

There is no obvious difference between a disabled task and a normal task, and it is not easy to identify.

Whether disabled tasks can be distinguished by adding special identifiers.

### What you expected to happen

There can be a clear difference .

### How to reproduce

See "What happened"

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
Sounds good.  I'll fix this issue.
