### ISSUE TITLE
[Bug] [plugin] python task execute error

### ISSUE THREAD

**Issue by mchcz** [apache/dolphinscheduler#8182]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

PYTHON_HOME configuration is as follows:
export PYTHON_HOME=/usr/bin/python3

When performing the task, the prompt cannot find the relevant python module:

![image](https://user-images.githubusercontent.com/18095523/150887223-b3dcd8cd-9b6e-414d-8cc0-0729d43edf34.png)

Scripts run correctly on the server.
![image](https://user-images.githubusercontent.com/18095523/150887285-22026771-966a-47bc-9556-95f4aa27ed56.png)

If I change the "python” to “python3”, the python task will run successfully.
![image](https://user-images.githubusercontent.com/18095523/150887368-811ff7d9-6acb-4d19-889d-94fa2f854980.png)

or
Delete the python soft link on the server, create a new soft link and point to python3, and the task can also run successfully.
![image](https://user-images.githubusercontent.com/18095523/150887617-5da1cc0a-fbdf-43ac-858f-f71350bb4b53.png)

![image](https://user-images.githubusercontent.com/18095523/150887651-0683d1f6-8c96-49df-a326-71da67cbc05a.png)

### What you expected to happen

Python tasks can be executed normally.

### How to reproduce

See "What happened"

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
@mchcz Right now, DS doesn't support using python hone, I think this should be supported.
