### ISSUE TITLE
[Bug] [spark]message:datasource plugin 'spark' is not found.

### ISSUE THREAD

**Issue by wxd5146** [apache/dolphinscheduler#8183]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

在属于源中，添加‘spark’数据源时报错
![image](https://user-images.githubusercontent.com/39934213/150891276-8f91db47-89b2-422c-a271-be7224066984.png)
![image](https://user-images.githubusercontent.com/39934213/150891422-0ccf8df6-65b9-4271-9d55-8b8073993111.png)
![Uploading image.png…]()

### What you expected to happen

应该连接成功

### How to reproduce

检查spark插件

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ITBOX-ITBOY** [comment]
这个问题现在要怎么解决呢，我也遇到了这个问题

**Comment by lenboo** [comment]
Fixed in dev branch and 3.0

**Comment by ltcaxx** [comment]
Now, I am also experiencing this problem. Has version 3.0 been solved?

**Comment by KeithTt** [comment]
Same  problem here. Version: 2.0.6
