### ISSUE TITLE
[param][innerparam] Add custom built-in parameters

### ISSUE THREAD

**Issue by wxd5146** [apache/dolphinscheduler#8184]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

在目前的版本中，ds的内置参数只有时间类型，建议增加全局自定义参数，可以在全部的流程中使用，而不是在一个流程中使用

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by roamerop** [comment]
+1
