### ISSUE TITLE
[Bug] [UI] the page of task group queue is empty 

### ISSUE THREAD

**Issue by wangxj3** [apache/dolphinscheduler#8186]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![图片](https://user-images.githubusercontent.com/26736756/150906562-9c71baf9-70ad-4d2f-9ea7-42d5e1c8e246.png)
when we change the language to english ,this page miss the data.

### What you expected to happen

show the data

### How to reproduce

change the language to english 

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
If there're running tasks in the queue of the task group, it will display those tasks on the page of 'Task group queue'. So I'd like to confirm whether there're running tasks in the queue of the task group. Would you like to give me more details about this issue? Look forward to your feedback.

**Comment by wangxj3** [comment]
> If there're running tasks in the queue of the task group, it will display those tasks on the page of 'Task group queue'. So I'd like to confirm whether there're running tasks in the queue of the task group. Would you like to give me more details about this issue? Look forward to your feedback.
The list is not empty。
![图片](https://user-images.githubusercontent.com/26736756/151482997-d9002540-dba3-454f-948d-a277aca4918a.png)

**Comment by calvinjiang** [comment]
I will fix this issue. Thanks for your feedback.
