### ISSUE TITLE
[Bug] [resource] Whether the re-upload function can be retained

### ISSUE THREAD

**Issue by mchcz** [apache/dolphinscheduler#8187]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In the Resource Center, the re-upload function is gone.

If you need to re-upload the file, you must delete the file before uploading it.

Can it be like version 1.3.X, there is a re-upload function, which can directly overwrite the original file.

![image](https://user-images.githubusercontent.com/18095523/150906906-511fda70-fe47-4f1e-981f-4dd0827c135f.png)

### What you expected to happen

There is a function to re-upload the file.

### How to reproduce

See "What happened"

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
Can you shed more light on this issue.

**Comment by calvinjiang** [comment]
I will fix this issue.
