### ISSUE TITLE
[Improvement][dolphinscheduler-api] QueryTaskInstanceListPaging API performance improvement

### ISSUE THREAD

**Issue by ouyangyewei429** [apache/dolphinscheduler#8218]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
Can you describe why you want to modify it ?
