### ISSUE TITLE
[Feature][python] Add add example into dist package

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#8222]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

For now, our examples are out of scope from the source package https://github.com/apache/dolphinscheduler/tree/dev/dolphinscheduler-python/pydolphinscheduler/examples. It makes our examples only work at source code. we should  add them to dist package to run it after we install from pypi

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
I simply added a `__init__.py` file into folder `examples` and moved `examples` into the folder `src/pydolphinscheduler/` folder. It works. Correct me if I'm wrong. 

Here's the pr link: https://github.com/apache/dolphinscheduler/pull/8340

Thanks.

**Comment by zhongjiajie** [comment]
> I simply added a `__init__.py` file into folder `examples` and moved `examples` into the folder `src/pydolphinscheduler/` folder. It works. Correct me if I'm wrong.
> 
> Here's the pr link: #8340
> 
> Thanks.

Sure, it could be done by this, please make sure we have some example test in `tests/example/` and `tests/test_docs.py`  which run some test about example
