### ISSUE TITLE
[Bug] [k8s deploy] k8s deploy latest version 2.0.3 use helm error report Error: ErrImagePull

### ISSUE THREAD

**Issue by luojieio** [apache/dolphinscheduler#8226]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when use helm to deploy dolphin latest version 2.0.3  error report Error: ErrImagePull

output：
Events:
  Type     Reason          Age                 From               Message
  ----     ------          ----                ----               -------
  Normal   Scheduled       12m                 default-scheduler  Successfully assigned dolphinscheduler/dolphinscheduler-worker-1 to docker-desktop
  Normal   SandboxChanged  11m                 kubelet            Pod sandbox changed, it will be killed and re-created.
  Warning  Failed          100s (x3 over 11m)  kubelet            Failed to pull image "apache/dolphinscheduler:2.0.3": rpc error: code = Unknown desc = Error response from daemon: manifest for apache/dolphinscheduler:2.0.3 not found: manifest unknown: manifest unknown
  Warning  Failed          100s (x3 over 11m)  kubelet            Error: ErrImagePull
  Normal   BackOff         71s (x6 over 11m)   kubelet            Back-off pulling image "apache/dolphinscheduler:2.0.3"
  Warning  Failed          71s (x6 over 11m)   kubelet            Error: ImagePullBackOff
  Normal   Pulling         58s (x4 over 12m)   kubelet            Pulling image "apache/dolphinscheduler:2.0.3"

command：
helm.exe search repo dolphinscheduler
output：
No results found

### What you expected to happen

why can't find image?

### How to reproduce

deploy

### Version

2.0.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
hi @luojieio thanks for your issue, the docker image of apache/dolphinscheduler:2.0.3 had already pushed. can you check it again?

**Comment by zhongjiajie** [comment]
I change  it milestone from 3.0.0-beta-1 to 206 due to its version is 2.0.3

**Comment by brave-lee** [comment]
I think this is because there was no image at that time, but it should be normal now
