### ISSUE TITLE
[Feature][python] Show test coverage badge in pydolphinscheduler readme

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#8256]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

For now, it could only show hole coverage of dolphinscheduler. It is better to show python API as separate

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Kodalien** [comment]
Hi,you can from all [Feature][python] to form a task table! @zhongjiajie  Can be assigned to me

**Comment by zhongjiajie** [comment]
@Kodalien I assigned to you.

**Comment by zhongjiajie** [comment]
> Hi,you can from all [Feature][python] to form a task table!

What's this mean?

**Comment by Kodalien** [comment]
all [Feature][python] --> [Feature][python] task collection @zhongjiajie

**Comment by jj551** [comment]
> > 您好，您可以从所有[Feature][python]中组成一个任务表！
> 
> 这是什么意思？

all [Feature][python] --> [Feature][python] 任务合集@钟家界

**Comment by zhongjiajie** [comment]
@Kodalien  We just separate python task from #6407, because we have to close DSIP-1. So I would not add another parent issue to track them

**Comment by jj551** [comment]
> @Kodalien We just separate python task from #6407, because we have to close DSIP-1. So I would not add another parent issue to track them

ok ! now I know

**Comment by zhongjiajie** [comment]
So, do you interested in this issue? @Kodalien

**Comment by jj551** [comment]
I think the problem of refactoring the documentation needs to be tackled completely first, before starting to tackle other issues at the end. brother think it is reasonable?

> So, do you interested in this issue? @Kodalien

I think the problem of refactoring the documentation needs to be tackled completely first, before starting to tackle other issues at the end. brother think it is reasonable? @zhongjiajie

**Comment by jj551** [comment]
> I think the problem of refactoring the documentation needs to be tackled completely first, before starting to tackle other issues at the end. brother think it is reasonable?
> 
> > So, do you interested in this issue? @Kodalien
> 
> I think the problem of refactoring the documentation needs to be tackled completely first, before starting to tackle other issues at the end. brother think it is reasonable? @zhongjiajie

I need my brother to collaborate to solve the document refactoring problem, so now how do I start to solve the document problem completely! ! Maybe we need to communicate more effectively.

**Comment by zhongjiajie** [comment]
Yeah, maybe document is more important than this issue, looking forward your contribution.

**Comment by zhongjiajie** [comment]
@Kodalien I just create new channel in slack https://asf-dolphinscheduler.slack.com/archives/C03293YAPAM, after 2022 we would migrate from wechat group to slack for more globalization

**Comment by jj551** [comment]
> @Kodalien我只是在 slack 中创建新频道https://asf-dolphinscheduler.slack.com/archives/C03293YAPAM，2022 年后我们将从微信群迁移到 slack 以实现更多全球化

I'm already in  slack !!! 2020
