### ISSUE TITLE
[Feature][UI Next] Data Quality.

### ISSUE THREAD

**Issue by songjianet** [apache/dolphinscheduler#8275]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- [x] Result
- [x] Rule

### Related issues

[#7332](https://github.com/apache/dolphinscheduler/issues/7332)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I'd like to develop the page of managing rules for the module of data quality.
