### ISSUE TITLE
[Bug] [DataSource] mysql 8 jdbc connect failed

### ISSUE THREAD

**Issue by fengmingxia** [apache/dolphinscheduler#8281]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I was in dev model  and using StandaloneServer
When I created a mysql 8  dataresourse,  and  clicked button "test connection" but dolphinscheduler-ui shows:
"JDBS connected failed"

### What you expected to happen

click "test connection" can return test result.
dolphinscheduler-api server should not keep outputting error logs.

### How to reproduce

In dev model and using StandaloneServer
create a datasource (mysql 8)
click the "test connect" button.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jim-parsons** [comment]
while i can not repeat this error in the standalone server ~

![image](https://user-images.githubusercontent.com/20239172/152751899-3ee3dd1f-d9c5-4943-9142-d747c3cd5d5e.png)

![image](https://user-images.githubusercontent.com/20239172/152751931-3f075ef5-30a6-469e-a22f-017f21f4f1fb.png)

**Comment by caishunfeng** [comment]
> while i can not repeat this error in the standalone server ~
> 
> ![image](https://user-images.githubusercontent.com/20239172/152751899-3ee3dd1f-d9c5-4943-9142-d747c3cd5d5e.png)
> 
> ![image](https://user-images.githubusercontent.com/20239172/152751931-3f075ef5-30a6-469e-a22f-017f21f4f1fb.png)

hi @fengmingxia please confirm it.

**Comment by huagetai** [comment]
This bug occurs when MySQL has no password。At this time, the program will set the password to 12345。

org.apache.dolphinscheduler.plugin.datasource.api.client.CommonDataSourceClient
<img width="551" alt="截屏2022-03-26 上午11 06 00" src="https://user-images.githubusercontent.com/1137341/160222506-164569c1-f973-451f-8012-b8f10f0255b9.png">
<img width="614" alt="截屏2022-03-26 上午11 06 15" src="https://user-images.githubusercontent.com/1137341/160222511-f680f94d-4e66-43c2-98e6-4ab5348dd99c.png">
