### ISSUE TITLE
[Bug] [UI] tenant always default when update process definition

### ISSUE THREAD

**Issue by hanfengcan** [apache/dolphinscheduler#8286]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

udp.vue
![image](https://user-images.githubusercontent.com/4559753/152644853-61508510-e3cf-4103-b6b0-a0ad7a4e0f0e.png)

selectTenant.vue
![image](https://user-images.githubusercontent.com/4559753/152644877-85f4acc6-50e5-467e-a100-39cdeb88af78.png)

### What you expected to happen

选择不同租户的更新的时候，租户不应该的default

### How to reproduce

如上截图

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @hanfengcan can you check this issue in 2.0.3?

**Comment by hanfengcan** [comment]
> Hi @hanfengcan can you check this issue in 2.0.3?

2.0.3 has the same problem

**Comment by wangyizhi1** [comment]
![Kapture 2022-02-17 at 16 03 12](https://user-images.githubusercontent.com/87303815/154432727-c9adb6ac-a37e-4c68-a6e3-986c59bf7d99.gif)
I did not reproduce this problem in version 2.0.3?

**Comment by SbloodyS** [comment]
@Wangyizhi1 
Entering the edit process definition page through the process instance page can reproduce this problems.
