### ISSUE TITLE
the sub process in the workflow is submitted twice

### ISSUE THREAD

**Issue by delong1985** [apache/dolphinscheduler#8291]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The workflow is terminated during execution, and the workflow is resumed after the service is restarted, the sub process in the workflow is submitted twice。but the instance id are different。
![image](https://user-images.githubusercontent.com/98446986/152709560-18dd03da-e01c-4239-b801-90a3d49f810d.png)
![151128598-fbe01e81-3e92-498b-abd6-b4a02a47c75b](https://user-images.githubusercontent.com/98446986/152709582-0b9ce592-092c-4cef-b764-3a101784278a.png)

### What you expected to happen

the workflow is resumed，The subprocess can be executed once

### How to reproduce

The workflow is terminated during execution, and the workflow is resumed after the service is restarted

### Version

1.3.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by batmanneverdie** [comment]
also appear in v3.1.3.

**Comment by stephenking30** [comment]
appear in v3.1.0
