### ISSUE TITLE
[Feature] unbuntu sh default is dash  execute install.sh error 

### ISSUE THREAD

**Issue by iamnotgay** [apache/dolphinscheduler#830]
my os is unbuntu ,the sh default is dash   but install.sh need bash

**Comment by iamnotgay** [comment]
sudo dpkg-reconfigure dash      selet no

**Comment by iamnotgay** [comment]
Hope to process automatically in the script

**Comment by qiaozhanwei** [comment]
Re-do the soft connection

重新做一下软连接

**Comment by hsupu** [comment]
Would DS fix this in the future? Or just try to avoid using bash-specific syntax?
