### ISSUE TITLE
[Feature][Document] Refactor the Resource Center Document

### ISSUE THREAD

**Issue by QuakeWang** [apache/dolphinscheduler#8301]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When I read the [Resource](https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/resource.html) find the description is not enough detail, so I decided to refactor it.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
we should add how to add udf resource, and give some ref to SQL task in #9601

**Comment by QuakeWang** [comment]
I think it is possible to split the resource center into file management, UDF functions, and task group management, as in the case of task-type documents. This would make for better documentation.

**Comment by zhongjiajie** [comment]
> I think it is possible to split the resource center into file management, UDF functions, and task group management, as in the case of task-type documents. This would make for better documentation.

Yeah, sound great!

**Comment by QuakeWang** [comment]
For the documentation in the Resource Center, I plan to divide it into the following sections.
1. Configuration notes: this section focuses on the use of the resources and how to configure the files.
2. File management: this section explains how to create and upload files, plus an additional section on how to use them in workflows.
3. UDF functions: this section explains the creation and use of UDF functions.
4. Task group management: this section explains how to use task groups.
