### ISSUE TITLE
[Bug] [Parameter Context] The problem of global parameter priority

### ISSUE THREAD

**Issue by cheneychoi** [apache/dolphinscheduler#8329]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

在kai fa we开发文档中，全局参数localParam的优先级是最低的，如图
![image](https://user-images.githubusercontent.com/23023197/153320547-378732f4-d560-4d88-97b4-6043e1cc69fb.png)
我在测试中发现，localParam会优先级更高，下图是测试结果
![image](https://user-images.githubusercontent.com/23023197/153320985-3c7d6852-101a-4b08-957e-729d5fb71d2c.png)
![image](https://user-images.githubusercontent.com/23023197/153321055-c0d8aa4a-0f8e-4b75-b98c-3fee39d5d519.png)
![image](https://user-images.githubusercontent.com/23023197/153321113-5ee3c3ea-a101-41b9-a0cf-2017bb61b228.png)

### What you expected to happen

最后打印出x的值应该为varpool中的lll，而不是localparam中的2

### How to reproduce

按照我上面的定义即可以重新复现

### Version

2.0.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jim-parsons** [comment]
i tried on latest dev code and got the same result



![image](https://user-images.githubusercontent.com/20239172/153330017-eb941e10-c578-427c-ab88-9c9d83d1b245.png)

![image](https://user-images.githubusercontent.com/20239172/153330191-fe16c6fe-9c53-4880-9bc1-08b3a3eca543.png)

![image](https://user-images.githubusercontent.com/20239172/153330238-646da8f7-7401-49aa-8b97-714784bc5b9f.png)

**Comment by cheneychoi** [comment]
> 

我已经修改了问题，提交了pr，暂时还没有得到回复！

**Comment by zhongjiajie** [comment]
I am not sure this issue is bug for code or for document, could you please take a look? @lenboo @caishunfeng . I think is it important for both codebase or document bug, so I add label `core`

**Comment by zhongjiajie** [comment]
IMO, I thinks it more like our documentation is out up date, and should be upgrade

**Comment by zhongjiajie** [comment]
Remove stale

**Comment by caishunfeng** [comment]
PTAL @Tianqi-Dotes

**Comment by Tianqi-Dotes** [comment]
the 2.0.5 and version below 2.0.5 doc illustrate the wrong priorities, please check the dev doc.
https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/parameter/priority.html

Have fixed both the doc and code,please refer to following:
doc:https://github.com/apache/dolphinscheduler-website/pull/753
code:https://github.com/apache/dolphinscheduler/pull/9379
