### ISSUE TITLE
[Bug] [API] ProcessDefinition update error

### ISSUE THREAD

**Issue by brave-lee** [apache/dolphinscheduler#8334]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![Uploading image.png…]()

### What you expected to happen

It should be updated normally

### How to reproduce

Dag contains aggregation nodes and the basic information of workflow is not changed

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by edward-yang** [comment]
I will submit a PR.
