### ISSUE TITLE
A little advice for data-quality-design

### ISSUE THREAD

**Issue by huahuaeshao** [apache/dolphinscheduler#8352]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

基于海豚调度器的数据质量分支进行基础功能调试。
1.发现告警模块的失败告警信息没有把getDataQualityAlterContent方法中的DqExecuteResult转成list，导致失败的信息和成功信息不一致
2.规则匹配的时候，源代码中对规则的判断出现成功了也会发出邮件，将checkDqExecuteResult的判断多加一个感叹号就可以
![Uploading image.png…]()

### Use case

希望第二个版本尽快出来

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
@huahuaeshao Please use English, otherwise this issue will be closed, thanks.

**Comment by ruanwenjun** [comment]
Closed by no response.
