### ISSUE TITLE
sudo.enable=false Is invalid

### ISSUE THREAD

**Issue by ShuiMu-peng** [apache/dolphinscheduler#8366]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Hello, I don't want to use 「sudo-u」 scheduling tasks

so change 「conf/common.properties」 this configuration：

```shell
# use sudo or not, if set true, executing user is tenant user and deploy user needs sudo permissions; if set false, executing user is the deploy user and doesn't need sudo permissions
sudo.enable=false
```

but is invalid

shell task still use  「sudu -u」.

log info:
…..
[INFO] 2022-02-10 08:34:18.661 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[285] - task run command: sudo -u hadoop sh /home/hadoop/dolphinscheduler/temp/exec/process/4462120816128/4465215383552_1/13/15/13_15.command
[INFO] 2022-02-10 08:34:18.664 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[176] - process start, process id is: 92386
[INFO] 2022-02-10 08:34:18.671 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[200] - process has exited, execute path:/home/hadoop/dolphinscheduler/temp/exec/process/4462120816128/4465215383552_1/13/15, processId:92386 ,exitStatusCode:1 ,processWaitForStatus:true ,processExitValue:1
[INFO] 2022-02-10 08:34:19.664 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[66] -  -> welcome to use bigdata scheduling system...
	hadoop 不在 sudoers 文件中。此事将被报告。
…...

### What you expected to happen

I think it would not use [sudo -u ] scheduling

### How to reproduce

use this config:

```shell
# use sudo or not, if set true, executing user is tenant user and deploy user needs sudo permissions; if set false, executing user is the deploy user and doesn't need sudo permissions
sudo.enable=false
```

### Anything else

**source code in class:**

Is it fixed to use [sudo-u]

org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor#buildProcess
```java
    private void buildProcess(String commandFile) throws IOException {
        // setting up user to run commands
        List<String> command = new LinkedList<>();

        //init process builder
        ProcessBuilder processBuilder = new ProcessBuilder();
        // setting up a working directory
        processBuilder.directory(new File(taskRequest.getExecutePath()));
        // merge error information to standard output stream
        processBuilder.redirectErrorStream(true);

        // setting up user to run commands
        command.add("sudo");
        command.add("-u");
        command.add(taskRequest.getTenantCode());
        command.add(commandInterpreter());
        command.addAll(Collections.emptyList());
        command.add(commandFile);

        // setting commands
        processBuilder.command(command);
        process = processBuilder.start();

        printCommand(command);
    }
```

### Version

2.0.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
@ShuiMuNianHuaLP 
What's the current progress on this issue, and have you worked on fixing the code? We hope this issue can be fixed in version 2.0.4.

**Comment by ShuiMu-peng** [comment]
@zhuangchong 


> @ShuiMuNianHuaLP What's the current progress on this issue, and have you worked on fixing the code? We hope this issue can be fixed in version 2.0.4.

I am dealing with this issue and will submit it tonight

**Comment by ShuiMu-peng** [comment]
> @ShuiMuNianHuaLP What's the current progress on this issue, and have you worked on fixing the code? We hope this issue can be fixed in version 2.0.4.

Please kindly check whether such adjustment is ok?thanks

https://github.com/ShuiMuNianHuaLP/dolphinscheduler/commit/df982aa0bae1e3987889a14d720c9c3a6670ac34?diff=unified

Because there is no dependency `dolphinscheduler-common`, that's why I did it 
If this is ok，i'm going to create the Pull Request

**Comment by zhuangchong** [comment]
You can submit a PR first, and I will conduct code review.

**Comment by ShuiMu-peng** [comment]
> You can submit a PR first, and I will conduct code review.

hello，It has been submitted PR

**Comment by ShuiMu-peng** [comment]
i'm sorry, commit message style is bad
I just saw 😥

https://dolphinscheduler.apache.org/zh-cn/community/development/commit-message.html
