### ISSUE TITLE
[Bug] [server] execute COMPLEMENT_DATA command always missing some ack event

### ISSUE THREAD

**Issue by ruancheng77** [apache/dolphinscheduler#8367]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when I execute COMPLEMENT_DATA task.
For example, 1 to 20. And then some task instances always missing field value(start_time/execute_path/log_path)
I find this is due to missing ack event, but I don't kown why missing.
![image](https://user-images.githubusercontent.com/23415499/153789768-a1021e2d-1705-4bef-b205-c138695fbef8.png)

### What you expected to happen

all task instance should to be create success.

### How to reproduce

Execute task with COMPLEMENT_DATA and date range is longer and bester.

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi, can you please describe the steps of reproduce this issue? ^_^

**Comment by ruancheng77** [comment]
1.create a work with shell task(echo some message).
2.Execute work with COMPLEMENT_DATA type(Execution mode: seria and schedule time choose 20 days)
3.Look task log When work done. Always some task is missing log but it is execute success.

**Comment by SbloodyS** [comment]
![](https://vip2.loli.io/2022/02/16/ud7a4jE9i1OhgMT.png)


Hi, I just tested the serial complement data in 2.0.3-release for 20 days, and I can't reproduce this problem. whitch version you are using?

**Comment by ruancheng77** [comment]
You need goto task detail and look task log.
Some task missing log.
You can look t_ds_task_instance table records. Some record missing start_time/log_path value, that record just like image show.
![image](https://user-images.githubusercontent.com/23415499/154186982-32db18c7-0e79-4711-892b-96c78ccced5c.png)

**Comment by SbloodyS** [comment]
@ruancheng77 I can successfully reproduce this problem. The task instance is actually executed successfully, but the log does not save in the ```t_ds_task_intance```, resulting in the failure of query on the UI. I will check this issue. Thank you for your feedback. ^_^

**Comment by caishunfeng** [comment]
I found that workflowExecuteThread use same processInstance java object to run serial complement, which will dismatch the key and value in global processInstanceMap. So when check `processInstanceMap.contain(processInstance.id)`, it will get the error result you don't want, and skip doing something.
