### ISSUE TITLE
[Bug] [Worker] when the data is supplemented still date+1

### ISSUE THREAD

**Issue by wangbowen1024** [apache/dolphinscheduler#8394]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I see the 2.0.2-release note, [Feature-7451][Worker]remove date+1 when the data is supplemented.
But i use 2.0.3, when  COMPLEMENT DATA the date still date+1:
**run the process(have one shell task, just print the date)**
<img width="716" alt="image" src="https://user-images.githubusercontent.com/48642743/154092379-98e96c05-e325-49c9-9841-647ff16d325e.png">
<img width="617" alt="image" src="https://user-images.githubusercontent.com/48642743/154092060-b68dee0d-3313-4daf-b149-3c321ef8136f.png">

**result**
```
[INFO] 2022-02-15 23:26:41.602 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[66] -  -> welcome to use bigdata scheduling system...
	20220201
	20220202
	20220202000000
[INFO] 2022-02-15 23:26:41.602 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[60] - FINALIZE_SESSION
......
[INFO] 2022-02-15 23:26:42.833 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[66] -  -> welcome to use bigdata scheduling system...
	20220202
	20220203
	20220203000000
[INFO] 2022-02-15 23:26:42.835 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[60] - FINALIZE_SESSION
```

### What you expected to happen

i think it will print like this ?
```
	20220131
	20220101
	20220201000000
```
and 
```
	20220201
	20220202
	20220202000000
```

### How to reproduce

just like pictrue to do

### Anything else

i show the change from [#7452](https://github.com/apache/dolphinscheduler/pull/7452/commits/1c2371f57be0e4b317e44c1f95d7ff4a0758d4a6)
but, i think it's not in WokerServer, i think it's in MasterServer `BusinessTimeUtils.getBusinessTime(CommandType commandType, Date runTime)`
<img width="888" alt="image" src="https://user-images.githubusercontent.com/48642743/154096291-72dd0cf4-62e2-456c-98d5-a47750b3b420.png">

### Version

2.0.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcmolin** [comment]
I also found this bug
