### ISSUE TITLE
[Bug][Server] SQL type parameters cannot be passed downstream

### ISSUE THREAD

**Issue by laonaofu** [apache/dolphinscheduler#8396]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

按照官网文档说明，SQL类型，note-b依赖note-a，应该是可以获取传递过来的参数"period_name"，但实际获取为null
note-a:
![image](https://user-images.githubusercontent.com/99780161/154192317-2855174c-be0b-42cc-8c64-f3e9e9c9cd01.png)
note-b:
![image](https://user-images.githubusercontent.com/99780161/154192368-a1340a7d-d493-4575-86f5-f150f458a985.png)
note-a log:
![image](https://user-images.githubusercontent.com/99780161/154192405-036fbe09-31ae-4b9f-a3e0-3c1350019c44.png)
note-b log:
![image](https://user-images.githubusercontent.com/99780161/154192463-d2002588-70b5-4990-8c6a-68b2122d5640.png)

### What you expected to happen

按照官网文档说明，SQL类型，note-b依赖note-a，应该是可以获取传递过来的参数"period_name"，但实际获取为null

### How to reproduce

note-a:
![image](https://user-images.githubusercontent.com/99780161/154192317-2855174c-be0b-42cc-8c64-f3e9e9c9cd01.png)
note-b:
![image](https://user-images.githubusercontent.com/99780161/154192368-a1340a7d-d493-4575-86f5-f150f458a985.png)
note-a log:
![image](https://user-images.githubusercontent.com/99780161/154192405-036fbe09-31ae-4b9f-a3e0-3c1350019c44.png)
note-b log:
![image](https://user-images.githubusercontent.com/99780161/154192463-d2002588-70b5-4990-8c6a-68b2122d5640.png)

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I will check this issue.

**Comment by laonaofu** [comment]
不好意思，版本号我搞错了，版本是2.0.2，请您知悉 谢谢

**Comment by Yao-MR-zz** [comment]
hi @laonaofu  can you share more logs of the note-b log ?

**Comment by ozh123** [comment]
同求问题解决办法
