### ISSUE TITLE
 FAILED: ParseException line 9:22 cannot recognize input near 'hbase' '.' 'columns' in table properties list

### ISSUE THREAD

**Issue by 1205823696** [apache/dolphinscheduler#8401]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Hello, I have a problem when using it. Thank you for your reply
An error occurs when creating an associated hbase table in Hive, but the execution statement runs properly in Hue and fails to run in DolphinScheduler

 FAILED: ParseException line 9:22 cannot recognize input near 'hbase' '.' 'columns' in table properties list

![22d478b5e3bae643feacb145068c8dd](https://user-images.githubusercontent.com/52704749/154221789-0a2d3005-6739-4e13-9ae3-4ea32ced3df4.png)

Dolphinscheduler executes the following script

#!/bin/bash
source /etc/profile
source  ~/.bash_profile
beeline -u "jdbc:hive2:////stgbigdata1:10000" -e" 

create table IF NOT EXISTS hbase.hbase_store_device_online_fdt(
rowkey string
,store_id  string
,online string
,offline string
,total int
)
stored by 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
with serdeproperties ("hbase.columns.mapping" = ":key,log:store_id,log:online,log:offline,log:total")
tblproperties ("hbase.table.name" = "store_device_online");

"
if [[ $? != 0 ]];then
    echo "sql error 自动退出"
    exit 1
fi
echo "运行成功"

echo "Good bye!"
exit 0

### What you expected to happen

How do I modify the create statement

### How to reproduce

Dolphinscheduler executes thescript

### Version

1.3.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ronyang1985** [comment]
<img width="808" alt="image" src="https://user-images.githubusercontent.com/13843983/154299399-27a90347-4417-4058-bb21-4ab72ff1e77a.png">

This is a quote pairing problem, not a bug with dolphinscheduler

**Comment by 1205823696** [comment]
I added the escape and it's ready to run, thank you
