### ISSUE TITLE
[Feature] [API] cannot kill task submitted on yarn with when I stop PySpark task with --deploy-mode cluster manually on Web UI

### ISSUE THREAD

**Issue by Meggie4** [apache/dolphinscheduler#8402]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when I kill  spark task with --deploy-mode client, I can see process instace stopped, and task submitted on yarn is also stopped;
but when I kill  spark task with --deploy-mode cluster , and I can see process instace stopped, but task submitted on yarn is still running;

### What you expected to happen

task(with --deploy-mode cluster) submitted on yarn is killed

### How to reproduce

create pyspark task and stop the process instance, and check application on hadoop web;

### Version

2.0.1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ronyang1985** [comment]
I think is not a bug with dolphinscheduler.
Is this spark task submitted using the shell script? Killing the shell process does not kill the spark task in cluster deploy mode. 
This is the working mechanism of spark itself

**Comment by ronyang1985** [comment]
@Meggie4 FYI
https://spark.apache.org/docs/latest/running-on-yarn.html
<img width="981" alt="image" src="https://user-images.githubusercontent.com/13843983/154483974-9c3959bb-be7f-422a-87a2-da3a8dc42c35.png">

**Comment by Meggie4** [comment]
> @Meggie4 FYI https://spark.apache.org/docs/latest/running-on-yarn.html <img alt="image" width="981" src="https://user-images.githubusercontent.com/13843983/154483974-9c3959bb-be7f-422a-87a2-da3a8dc42c35.png">

thanks for your reply! As I can see,  DolphinScheduler start a pyspark task with shell script, and kill the task with kill the shell process;

I think DolphinScheduler should using  command like "yarn application -kill application_1589533772041_777" to kill task submitted on yarn;
<img width="2521" alt="image" src="https://user-images.githubusercontent.com/32348543/154611774-f1a76c83-b4cf-48bd-bb31-12fb847c1827.png">

**Comment by ronyang1985** [comment]
@Meggie4 
I studied the code of ds,  when the task is stopped with Exception , or when stopped  manual operation , it will try to kill the yarn job. The yarn appid is found through logs. yarn job will not be killed if yarn appid is not displayed normally in logs.The related implementations are in these two classes

https://github.com/apache/dolphinscheduler/blob/6974aa3d12501a6c8a47528da7d2d6a09a6fa4ae/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/runner/TaskExecuteThread.java#L194

https://github.com/apache/dolphinscheduler/blob/6974aa3d12501a6c8a47528da7d2d6a09a6fa4ae/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessor.java#L138
