### ISSUE TITLE
[Bug] [ui] When you select Sqoop Export and data source select Hive, the data destination is only Hive and HDFS without mysql  ,There are similar but unsolved

### ISSUE THREAD

**Issue by GdHuni** [apache/dolphinscheduler#8410]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

select Sqoop Export and data source select Hive, the data destination is only Hive and HDFS without mysql.
There are similar but unsolved

### What you expected to happen

select Sqoop Export and data source select Hive, the data destination is only Hive and HDFS without mysql.

### How to reproduce

select Sqoop Export and data source select Hive, the data destination is only Hive and HDFS without mysql.
There are similar but unsolvedselect Sqoop Export and data source select Hive, the data destination is only Hive and HDFS without mysql.

### Anything else

no 

### Version

2.0.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thanks for your contribution, but we're not doing any maintenance on the old UI anymore.
