### ISSUE TITLE
[Bug] [UI] Workflow definition timing manage edit

### ISSUE THREAD

**Issue by devosend** [apache/dolphinscheduler#8412]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Environment name is not assigned when i edit timing manage in workflow define. as follows:
![image](https://user-images.githubusercontent.com/8847400/154420171-16bc26d8-c2a5-4d1b-bf14-4d0ecaa524b7.png)

### What you expected to happen

Environment Name show the correct value.

### How to reproduce

Open `Process definition` -> `Cron Manage` and click edit button.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @devosend is it the same issue in 2.0.3 too? or just in dev?

**Comment by devosend** [comment]
yes, 2.0.3 has the same bug. @caishunfeng
