### ISSUE TITLE
[Bug] [Project Management] Change the user who authorizes the project, the creator of the project will not find this project

### ISSUE THREAD

**Issue by Jiangxiaoyuan** [apache/dolphinscheduler#8425]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. 我使用用户 **测试用户1** 创建一个项目 **测试项目1**
2. 通过管理员账号创建 **测试用户2** ，并将项目 **测试项目1** 授权给 **测试用户2**
3. 登录账号 **测试用户2** ，找到项目 **测试项目1** 更改项目的所属用户
4. 登录账号 **测试用户1**，发现查不到项目 **测试项目1**
5. 在版本 **2.0.2** 与 **2.0.3** 都出现这个问题

### What you expected to happen

1. 要么 **测试用户2** 无法更改项目的所属用户，要么继续维持 **测试用户1** 对测试项目的所属关系

### How to reproduce

1. 登录管理员账号 **admin**
2. 创建用户 **测试用户1**
3. 创建用户 **测试用户2**
4. 登录账号 **测试用户1**，创建项目 **测试项目1**
5. 登录管理员账号 **admin** ，给 **测试用户2** 授权项目 **测试项目1**
6. 登录账号 **测试用户2**，进入项目界面，更改 **测试项目1** 的所属用户
7. 登录账号 **测试用户1** ，查看效果

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by A2Data** [comment]
我是 3.0.0 版本 使用同一个用户，创建了两个项目，但是在工作流中依赖项 查询不到 该项目

**Comment by A2Data** [comment]
![image](https://user-images.githubusercontent.com/39373008/184843642-dc62725f-afc3-45a7-a088-2f37732a0bf1.png)

**Comment by A2Data** [comment]
![image](https://user-images.githubusercontent.com/39373008/184843758-5b9bdbc7-4686-4c2f-932b-3ccf495c5599.png)
