### ISSUE TITLE
[Bug] [Standalone] table t_ds_worker_group not found in standalone mode

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8432]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

table t_ds_worker_group not found in standalone mode

### What you expected to happen

running successfully.

### How to reproduce

running standalone server.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by finviman** [comment]
确定这问题解决了吗，我用2.0.6，不行，又退回2.0.5，还是同样问题。
