### ISSUE TITLE
[BUG][task execute fail] shell/python script execute,report (No such file or directory) 

### ISSUE THREAD

**Issue by jiangjialiang918** [apache/dolphinscheduler#8436]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After I installed the distributed cluster without any errors, all nodes and processes can be normal, when I created a shell script as a test but found that the task always fails, it has been determined that it is not a permission problem, because the deployment user used ( dolphinscheduler) as a tenant, has all permissions under the dolphinscheduler path, and has created a task execute path: ./jobs/exec/process/4577755613088/4577887155744_2/2/28 ,
Execute the file ./jobs/exec/process/4577755613088/4577887155744_2/2/28/2_28.command but don't see it
The execute log  is as follows:
[execute_log.md](https://github.com/apache/dolphinscheduler/files/8101511/execute_log.md)

The installation configuration is as follows:

[install_config.md](https://github.com/apache/dolphinscheduler/files/8101508/install_config.md)

### What you expected to happen

Can perform tasks such as shell normally

### How to reproduce

After deploying the cluster, make sure that all processes can start normally,
Use the login ds web management page,
Create a normal test user, use the dolphinscheduler added by default (deployment user), create a token for test, submit the token, confirm the validity period,
Use the test user to log in to ds web,
Create a shell workflow, only need one node, script content: echo 'hello dolphin' ,
Save the workflow, go online, run it manually

### Anything else

Reproduces every time, restarting all processes is still the same

### Version

2.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
@jiangjialiang918 Hi, please use English, and format the description with the right markdown grammar.

**Comment by jiangjialiang918** [comment]
> @jiangjialiang918 Hi, please use English, and format the description with the right markdown grammar.
Ok,Has been modified

**Comment by jiangjialiang918** [comment]
dataBasedirPath = "./jobs" updated in ./conf/common.propertie after installed,Because no change as well as can't find the path ~ / dolphinscheduler/exec/process/XXXX

**Comment by ruanwenjun** [comment]
> dataBasedirPath = "./jobs" updated in ./conf/common.propertie after installed,Because no change as well as can't find the path ~ / dolphinscheduler/exec/process/XXXX

You mean `data.basedir.path`? Could you please change this to absolute path and restart the server? And then try again.

**Comment by jiangjialiang918** [comment]
> > dataBasedirPath = "./jobs" updated in ./conf/common.propertie after installed,Because no change as well as can't find the path ~ / dolphinscheduler/exec/process/XXXX
> 
> You mean `data.basedir.path`? Could you please change this to absolute path and restart the server? And then try again.

Thank you, the problem has been solved, I feel this problem can be written on the document as a matter of attention

**Comment by ruanwenjun** [comment]
> > > dataBasedirPath = "./jobs" updated in ./conf/common.propertie after installed,Because no change as well as can't find the path ~ / dolphinscheduler/exec/process/XXXX
> > 
> > 
> > You mean `data.basedir.path`? Could you please change this to absolute path and restart the server? And then try again.
> 
> Thank you, the problem has been solved, I feel this problem can be written on the document as a matter of attention

Hi, are you interested to optimize this in document? Welcome to submit a pr to fix the document, this might be an important.

**Comment by jiangjialiang918** [comment]
No problem, but I think this problem should be a small one, I think they will not accept my PR

**Comment by jiangjialiang918** [comment]
> > > > dataBasedirPath = "./jobs" updated in ./conf/common.propertie after installed,Because no change as well as can't find the path ~ / dolphinscheduler/exec/process/XXXX
> > > 
> > > 
> > > You mean `data.basedir.path`? Could you please change this to absolute path and restart the server? And then try again.
> > 
> > 
> > Thank you, the problem has been solved, I feel this problem can be written on the document as a matter of attention
> 
> Hi, are you interested to optimize this in document? Welcome to submit a pr to fix the document, this might be an important.

No problem, but I think this problem should be a small one, I think they will not accept my PR

**Comment by ruanwenjun** [comment]
@jiangjialiang918 Don't worry, I will help to review your pr, if you ping me.
