### ISSUE TITLE
[Feature][doc] Add how community contirbute to E2E

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#8454]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

For now, we only have to write E2E code, but without how the contributor take the E2E's task, how to check exists tasks. Maybe we have to add some doc on it 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
@QuakeWang Do you interested in this issue?

**Comment by QuakeWang** [comment]
> @QuakeWang Do you interested in this issue?

With pleasure : )

**Comment by zhongjiajie** [comment]
Maybe we have to include the following part:
* How contirbutors find issues related to wanted E2E?
* How they determine the priority of E2E issues?
* How to write the E2E code?
* How to submit pull requests?

If you find some addition part we should add to E2E, feel free to add it.

**Comment by QuakeWang** [comment]
> Maybe we have to include the following part:
> 
> * How contirbutors find issues related to wanted E2E?
> * How they determine the priority of E2E issues?
> * How to write the E2E code?
> * How to submit pull requests?
> 
> If you find some addition part we should add to E2E, feel free to add it.

The documentation on how to write E2E code can be categorized according to different pages or actions so that contributors can be better involved.

**Comment by zhongjiajie** [comment]
But it would cause our many time to write the document, I initial thought

> How to write the E2E code?

is just about this page you already add https://dolphinscheduler.apache.org/en-us/development/e2e-test.html

and

> how to submit PR

just link to https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html

So this issue we should add is:

* How contributors find issues related to wanted E2E?
* How do they determine the priority of E2E issues?

It would cause out less time, WDTY? @QuakeWang

**Comment by QuakeWang** [comment]
> But it would cause our many time to write the document, I initial thought
> 
> > How to write the E2E code?
> 
> is just about this page you already add https://dolphinscheduler.apache.org/en-us/development/e2e-test.html
> 
> and
> 
> > how to submit PR
> 
> just link to https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html
> 
> So this issue we should add is:
> 
> * How contributors find issues related to wanted E2E?
> * How do they determine the priority of E2E issues?
> 
> It would cause out less time, WDTY? @QuakeWang

Good idea! I will do it later : )
