### ISSUE TITLE
[Feature][Resource] Resource Version Control

### ISSUE THREAD

**Issue by geosmart** [apache/dolphinscheduler#8465]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

now ds support dag version control
as pr of  https://github.com/apache/dolphinscheduler/issues/3046

but the dag version related resource does not have version control  
if a dag hava a new version , and remove a resource, so  the resource can delete.  
but the old version of dag depend the resource ,this make the dag not work anymore.

### Use case

Resource add version control mechanism.
when file update, the file just add a new version.
and file version can stored like `${tenantId}/resource-history/$fileId/$version`
so the old version of dag still working 

### Related issues

 https://github.com/apache/dolphinscheduler/issues/3046

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
This is a good idea.
We have already had some discussions here: https://github.com/apache/dolphinscheduler/issues/10387#issuecomment-1166904625
BTW, would you like to give a shot and give a design for resource version control? Thanks!
