### ISSUE TITLE
[Bug][Master] Frequently query mysql for t_ds_task_instance

### ISSUE THREAD

**Issue by mht-xyt** [apache/dolphinscheduler#8476]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When workflow C is scheduled in workflow A , the MASTER node will repeatedly query the node instance ID of workflow C during execution, and the node instance ID will accumulate. When the task stops, it will not disappear until the restart, causing great pressure to mysql
![image](https://user-images.githubusercontent.com/42835997/155049472-c374c311-92a8-47d4-93ee-45a19803874b.png)

### What you expected to happen

At the end of the task, you should stop querying mysql

### How to reproduce

Create A workflow B, which contains 3 DAG nodes, schedule workflow B in workflow A, as can be seen from mysql log, the MASTER continuously queries the node instances contained in workflow B, and does not stop after the task ends, more and more, until the service stops

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @mht-xyt can you check this issue in the latest version?
