### ISSUE TITLE
[Bug] [dao] Rerun does not take effect in case of failure

### ISSUE THREAD

**Issue by FrankZhang996** [apache/dolphinscheduler#8492]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After the task fails to run, it will be rerun according to the configured **retryTimes**, **maxRetryTimes** and **retryInterval**, but the configuration does not take effect.

### What you expected to happen

Automatic rerun configuration takes effect

### How to reproduce

modify class TaskInstance:

private int retryTimes;   ---> private Integer retryTimes;
private int maxRetryTimes;  ---> private Integer maxRetryTimes;
private int retryInterval;  ---> private Integer retryInterval;

### Anything else

mybatis's  method  updateById,
if the field is null, it will not update,
So we can't use basic types，
The basic type will cause the value saved in the field in the database to be 0

### Version

1.3.9

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
>How to reproduce
modify class TaskInstance:

private int retryTimes; ---> private Integer retryTimes;
private int maxRetryTimes; ---> private Integer maxRetryTimes;
private int retryInterval; ---> private Integer retryInterval;

Hi @FrankZhang996 what your meaning about modifying class TaskInstance?
