### ISSUE TITLE
[Bug] [DolphinScheduler-e2e]  The dockerhub does not have a standalone image, which will cause the direct test case to fail

### ISSUE THREAD

**Issue by yangyunxi** [apache/dolphinscheduler#8493]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Executing E2E's case will fail.

### What you expected to happen

Pulling dolphinscheduler (apache/dolphinscheduler-standalone-server:ci)...
ERROR: pull access denied for apache/dolphinscheduler-standalone-server, repository does not exist or may require ‘docker login’

### How to reproduce

run dolphinscheduler/dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/ProjectE2ETest.java

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi, you can use the following command to build the docker image of the standalone server.

```
./mvnw -B clean install \
          -Dmaven.test.skip \
          -Dmaven.javadoc.skip \
          -Dmaven.checkstyle.skip \
          -Pdocker,release -Ddocker.tag=ci \
          -pl dolphinscheduler-standalone-server -am
```

**Comment by kezhenxu94** [comment]
> Pulling dolphinscheduler (apache/dolphinscheduler-standalone-server:ci)

These images are built before running tests, not pulling from docker hub
