### ISSUE TITLE
[Bug] [UI] The modify betten the copy taskNode and the source taskNode is linked

### ISSUE THREAD

**Issue by wangxj3** [apache/dolphinscheduler#8519]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when we copy one or more node in the page of processDefinition ,we modify the one of them ,the other will modify too.

### What you expected to happen

they are independent

### How to reproduce

copy one tasknode ,and modify it

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. I went through your description and changed the node name of the workflow, but the problem you described didn't occur. If you confirm this is a problem, try to provide more complete information or pictures.

**Comment by songjianet** [comment]
I don't know if you still have questions about this, if not, I will close this issue.

**Comment by wangxj3** [comment]
> 
Okay, I'm trying it again. Maybe page caching.Thank you
