### ISSUE TITLE
[Bug] [API] workflow release status not verified

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8520]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

path: /dolphinscheduler/projects/{projectCode}/process-definition/{code}/release

接口调用可以无限成功，后端未对工作流状态做校验

<img width="984" alt="image" src="https://user-images.githubusercontent.com/76080484/155476886-8d009d92-3c5d-418c-a6aa-08f7a8a92a7b.png">

### What you expected to happen

期望可以对状态做校验，如果状态不匹配应及时提示或报错

### How to reproduce

使用Openapi /dolphinscheduler/projects/{projectCode}/process-definition/{code}/release接口

修改工作流状态可以稳定复现

### Version

2.0.4

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
This issue is not a bug.
