### ISSUE TITLE
[Bug] [UI] Submit time and host are not displayed

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8528]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Submission time and host are not displayed

<img width="1912" alt="image" src="https://user-images.githubusercontent.com/76080484/155505065-77f9b288-1096-41ce-b3fb-6f530ff48bc6.png">

### What you expected to happen

Normal display

### How to reproduce

Click the task flow to start execution. Now the submission time and host are not displayed

### Anything else

No

### Version

2.0.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. Please check whether the submission time and Host fields in this piece of data are empty through the Network of browser F12?

**Comment by XuXuClassMate** [comment]
> 感谢您的反馈意见。请通过浏览器F12的网络检查这条数据的提交时间和Host字段是否为空？

<img width="873" alt="image" src="https://user-images.githubusercontent.com/76080484/155641849-15c7240f-955d-423e-a2d7-874b7447b446.png">

<img width="811" alt="image" src="https://user-images.githubusercontent.com/76080484/155642518-f3411f2a-5adc-48e8-b650-c1b89b177353.png">



submitTime and host is null

**Comment by songjianet** [comment]
> > 感谢您的反馈意见。请通过浏览器F12的网络检查这条数据的提交时间和Host字段是否为空？
> 
> <img alt="image" width="873" src="https://user-images.githubusercontent.com/76080484/155641849-15c7240f-955d-423e-a2d7-874b7447b446.png">
> 
> <img alt="image" width="811" src="https://user-images.githubusercontent.com/76080484/155642518-f3411f2a-5adc-48e8-b650-c1b89b177353.png">
> 
> submitTime and host is null

So it's a data problem, not a problem on the front-end page.

**Comment by songjianet** [comment]
I don't know if you still have questions about this, if not, I will close this issue.
