### ISSUE TITLE
[Feature][UI] Custom timezone

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#8530]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1. Add the timezone selete on the right header, when user change timezone info, call the updateUser interface to update.
![image](https://user-images.githubusercontent.com/11962619/155515796-3f7597ca-c694-4c08-a98f-858a8d335654.png)

2. DAG scheduler time optimization.
![e65bb495e126392dcf7a1eb594fe295](https://user-images.githubusercontent.com/11962619/155515887-adfa55a3-bad8-4a4f-864c-d5294a57eb7a.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
![image](https://user-images.githubusercontent.com/19239641/155518182-25ce8cf0-77eb-4e93-b6a5-554e2823ab75.png)

In my personal opinion, the time zone should be placed in the user's drop-down menu. After clicking, it will jump to a time zone page. There are the currently selected time zone and the editing time zone. Later, the time of all 24 time zones can be listed, which is convenient for users to view. .

**Comment by songjianet** [comment]
Thanks.

**Comment by songjianet** [comment]
> Thanks.

**Comment by songjianet** [comment]
> Thanks.

**Comment by songjianet** [comment]
Thanks. I'll deal with this later.

**Comment by caishunfeng** [comment]
> Thanks. I'll deal with this later.

@songjianet Thanks, and you can put some good ideas into it if you want.

**Comment by rusonding** [comment]
+1

**Comment by songjianet** [comment]
![image](https://user-images.githubusercontent.com/19239641/156329679-0d4acb14-5a1c-4942-b068-e5af5fec8334.png)
What kind of effect does the page after pulling down and expanding here show?

**Comment by caishunfeng** [comment]
> ![image](https://user-images.githubusercontent.com/19239641/156329679-0d4acb14-5a1c-4942-b068-e5af5fec8334.png) What kind of effect does the page after pulling down and expanding here show?

Here you can drop down to select a different time zone, the time zone list can refer to the time zone list of DAG;
