### ISSUE TITLE
[Bug] [Doc] e2e-test link 404 not found

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8535]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

https://dolphinscheduler.apache.org/en-us/community/join/e2e-guide.html

### What you expected to happen

open successfully.

### How to reproduce

open https://dolphinscheduler.apache.org/en-us/community/join/e2e-guide.html and click ```e2e-test```

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by QuakeWang** [comment]
Thanks for your feedback, I will fix it soon.
