### ISSUE TITLE
[Async task][WorkerServer] Asynchronous task Support

### ISSUE THREAD

**Issue by BabySid** [apache/dolphinscheduler#8537]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

There are lots of ETL jobs which run for a long period of time in the scheduler system. When Dolphine restarts, these ETL jobs will be failed and be dispatched to other workers for re execution.
This will mainly lead to two problems: 
one is that the execution time of tasks becomes longer (e.g. task run between 10am to 15pm, i restart the job at 14pm, the job will finish at 19pm. 4 hours more than expected.)
second the resources of the cluster are also wasted.

So, I propose a feature: asynchronous task. Asynchronous flag can be set on task.
A async  Task can run detached with the worker process, when worker restart, it can find the original appid then check the task status（running？failed? ...）

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
Could you shed more light on this issue?  I'd wonder if all of components of the dolphinscheduler was restarted or failed at the same time. Please give more details.

**Comment by BabySid** [comment]
Thanks for reply

A couple of common usage scenarios:
- Restart the Worker services after modifying the configuration by using the command `bin/dolphinedaemon.sh stop worker-server` on all the worker host.  When a worker service restart, all the tasks on the worker will be   failed and scheduled to another worker to re-execute. I want this task to run all the time, and in fact, this task is running when the worker is restarting. For example, a HQL-Task run on yarn or some custome task on localhost/another cluster. 
- Upgrade Dolphine from a old version to new version. In this scenario, almost all tasks will fail, whether the task is really running or not.

Therefore, I hope to be provided some suggested solutions to make our tasks run more smoothly, because our system has strict SLA. While in the routine maintenance of the scheduler system, we also hope to ensure the punctuality of tasks.

**Comment by EricGao888** [comment]
@BabySid This is a good suggestion. May I ask whether u have any follow-ups on this issue? Thanks.

**Comment by BabySid** [comment]
sure. thanks for remembering this issue for so long. 
I also inquired about this issue on the slack channel, and the answers I got were all solved by increasing maintenance costs and degrading services. So later we re-implemented the scheduler ourselves.

**Comment by EricGao888** [comment]
> sure. thanks for remembering this issue for so long. I also inquired about this issue on the slack channel, and the answers I got were all solved by increasing maintenance costs and degrading services. So later we re-implemented the scheduler ourselves.

@BabySid Sounds pretty cool that you re-implemented the scheduler. May I ask whether you are interested in participating in open-source activity and get more involved with the Apache DolphinScheduler community? We have WeChat groups for local users.

**Comment by BabySid** [comment]
Course but what a pity.  At present, I'm using Golang. :( I would be happy to join the open-source team If I have the opportunity to go deep into Java in the future,  :)
