### ISSUE TITLE
[Bug] [Resource Center] filename rename operation error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8541]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/76080484/155687944-566d8747-9309-4953-817c-43656fcd4933.png">

<img width="868" alt="image" src="https://user-images.githubusercontent.com/76080484/155688263-7debcb9e-a0f8-41a0-8713-682b9d1d6e30.png">

### What you expected to happen

现象：filename rename operation error

预期：修改文件名称显示当前文件名称

### How to reproduce

打开资源中心，创建文件夹，点击重命名

### Version

2.0.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi. I can not reproduce this issue. What is the error log?

**Comment by XuXuClassMate** [comment]
> 你好。我无法重现此问题。什么是错误日志？

只是页面错误，没有调接口，所以没有服务端错误日志

**Comment by Tianqi-Dotes** [comment]
I have checked this in ds1 environment (dev and new UI) and it's okay.
Will check this in version 2.0.5 lately.
