### ISSUE TITLE
[Feature][Logging] Add support for logging into remote storage

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#8543]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- Add support for remote logging so that the tasks logs could be preserved in remote storage service like AWS S3 or Alibaba-Cloud OSS.

### Use case

- Currently, it seems dolphin scheduler does not support logging into remote storage such as AWS S3, Alibaba-Cloud OSS, etc.  
- If dolphin scheduler is deployed on a remote cluster like EMR and the cluster is torn down or there's something wrong with the workers, users will probably lose the logs of previous executed tasks.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Is it necessary to add thie feature in DS?
Is it possible to use log monitoring synchronization to do it? Similar to Alibaba Cloud's SLS

**Comment by davidzollo** [comment]
good suggestion,  Can you give a design to support the remote logging system?

**Comment by EricGao888** [comment]
@caishunfeng @dailidong Another question related to this issue is how does ds deal with workers' logs? If not logging into remote storage, how do we keep large amount of logs produced by workers? Is there a best practice for this?

**Comment by caishunfeng** [comment]
> @caishunfeng @dailidong Another question related to this issue is how does ds deal with workers' logs? If not logging into remote storage, how do we keep large amount of logs produced by workers? Is there a best practice for this?

Now DS doesn't specifically dealt with task log file, and the user handles it by himself, which is unfriendly.
It is a goold idea to write the task log into remote storage when keep running large amout tasks.  And I think the two point:

1. How to write files? Specified by configuration or config in the process definition UI?
2. How to read compatible local files and remote files?

 If you have some good idea, please let me know.

**Comment by EricGao888** [comment]
> good suggestion, Can you give a design to support the remote logging system?

@dailidong I will try to give a design this week, thx : )

**Comment by EricGao888** [comment]
> > @caishunfeng @dailidong Another question related to this issue is how does ds deal with workers' logs? If not logging into remote storage, how do we keep large amount of logs produced by workers? Is there a best practice for this?
> 
> Now DS doesn't specifically dealt with task log file, and the user handles it by himself, which is unfriendly. It is a goold idea to write the task log into remote storage when keep running large amout tasks. And I think the two point:
> 
> 1. How to write files? Specified by configuration or config in the process definition UI?
> 2. How to read compatible local files and remote files?
> 
> If you have some good idea, please let me know.

Will take these points into consideration. Thx for the suggestions!

**Comment by EricJoy2048** [comment]
Yes, logging into remote storage is a good idea when worker is deploy in cloud.
We also need to consider whether the log target is global or whether different workflows can config they own log target.
If dolphin scheduler needs to run on hybrid cloud in the future, I think we should configure its own log target for each workflow.

**Comment by EricGao888** [comment]
Could anyone please help add a `discussion` label to this? Thx~

**Comment by caishunfeng** [comment]
> Could anyone please help add a `discussion` label to this? Thx~

sure, I have added.

**Comment by EricGao888** [comment]
> > Could anyone please help add a `discussion` label to this? Thx~
> 
> sure, I have added.

Thx~

**Comment by rickchengx** [comment]
Hi, @EricGao888 , I am interested in this issue.

**Comment by EricGao888** [comment]
> Hi, @EricGao888 , I am interested in this issue.

Sure, looking forward to your design : )

**Comment by hstdream** [comment]
Hi, @EricGao888 , I am interested in this issue.

**Comment by hstdream** [comment]
my thoughts:
1. Workflow completes aggregation log
2. Worker completes log aggregation
3. Local and remote check and store time by setting time interval through configuration
