### ISSUE TITLE
[Bug] [Resource Center-UDF Management/Resource Management] Folder size statistics error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8544]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/76080484/155693270-c322ed34-8867-4ba4-849c-f5bc99249fb4.png">

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/76080484/155693495-91b99fbb-1f12-495e-9643-05990651fcec.png">

### What you expected to happen

The parent folder size is the child file / folder size count

### How to reproduce

1. Create folder

2. Open folder

3. Upload jar package

4. Return to outer folder

### Version

2.0.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I will check this issue.
