### ISSUE TITLE
[Bug] [Permission] Workflow definition list error

### ISSUE THREAD

**Issue by zr9883** [apache/dolphinscheduler#8562]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

进入工作流列表，查询空，查看日志后看到报错。

### What you expected to happen

可能修改所属用户那边出了问题。

### How to reproduce

我用A账号新建了一个项目，项目下面建了一个工作流，然后这个项目的所属用户改成了admin，想删除这个项目，提示说要先删除工作流，进入工作流列表，查询空，查看日志后看到报错。

[INFO] 2022-02-28 10:40:34.041 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[90] - REQUEST TRACE_ID:93a83ffc-e36e-4f7f-939b-214f77b3a5a7, LOGIN_USER:admin, URI:/dolphinscheduler/projects/4653615416960/process-definition, METHOD:GET, HANDLER:org.apache.dolphinscheduler.api.controller.ProcessDefinitionController.queryProcessDefinitionListPaging, ARGS:{searchVal=, projectCode=4653615416960, pageNo=1, pageSize=10, userId=0}
[ERROR] 2022-02-28 10:40:34.053 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[46] - 分页查询工作流定义列表错误
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.api.service.impl.ProcessDefinitionServiceImpl.queryProcessDefinitionListPaging(ProcessDefinitionServiceImpl.java:421)

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
I have checked this issue, I followed the instructions of this issue and find it's okay,
Use a user to create a project and assign the project to admin and delete the project, It's okay,
![bdc4d38dfc15045449ffd509889b71c](https://user-images.githubusercontent.com/36755957/159512930-09b9ae67-daa8-4654-b03b-3abf2c98743e.png)
I used 2.0.6 to test.

**Comment by Tianqi-Dotes** [comment]
I have checked this in version  205 is fine.
