### ISSUE TITLE
[Feature][UI Next][V1.0.0-Alpha] Known Issues.

### ISSUE THREAD

**Issue by songjianet** [apache/dolphinscheduler#8565]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Optimization

- [x] #8589 @labbomb 
- [x] #8574 @songjianet 
- [x] #8816 @Amy0104 
- [x] #9108 @calvinjiang 
- [x] #9013 @labbomb 
- [x] #8990 @labbomb 
- [x] #8634 @labbomb 
- [x] #8812 @Amy0104 
- [x] #9109 @calvinjiang 
- [x] #9214 @labbomb 
- [x] #8673 @labbomb 
- [x] #8753 @labbomb 
- [x] #8854 @Amy0104 
- [x] #9040 @Amy0104 

### Missing Function

- [x] #8570 @calvinjiang 
- [x] #8571 @devosend 
- [x] #8572 @Amy0104 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I'll develop the tree of the workflow definition.

**Comment by Amy0104** [comment]
DATA_QUALITY.

**Comment by devosend** [comment]
I'll develop the Gantt chart of Project Manage.

**Comment by SbloodyS** [comment]
I'm trying to package ```UI -Next``` into the docker image of ```dev``` branch. I try to replace the ```dist``` folder compiled by ```UI-next``` with the previous version to the ```ui``` folder under the API module. I start the API module to access the domain/dolphinscheduler and get the following errors.
![](https://vip1.loli.io/2022/02/28/j2rmUtpwfk1sVcE.png)

And then I try to remove the absolute path ```/``` in index.html. I got another errors.
![](https://vip2.loli.io/2022/02/28/RlK7sXqxMrZQa48.png)

Is it that the compatibility of API modules has not been completed?

**Comment by songjianet** [comment]
> I'm trying to package `UI-Next` into the docker image of `dev` branch. I try to replace the `dist` folder compiled by `UI-Next` with the previous version to the `ui` folder under the API module. I start the API module to access the domain/dolphinscheduler and get the following errors. ![](https://camo.githubusercontent.com/e4c23963596425077d092fca83ccc50816317cdd8a8a911c574cce31319f3612/68747470733a2f2f766970312e6c6f6c692e696f2f323032322f30322f32382f6a32726d55747077666b31735663452e706e67)
> 
> And then I try to remove the absolute path `/` in index.html. I got another errors. ![](https://camo.githubusercontent.com/6a05791c6e3d4ff311088cfa189161300a1cc04417c866a4b4a58a9ff4ddb1a3/68747470733a2f2f766970322e6c6f6c692e696f2f323032322f30322f32382f526c4b37735871784d725a516134382e706e67)
> 
> Is it that the compatibility of API modules has not been completed?

Please open a separate issue for this issue, I will take a look at it later, but there is no problem on my side at present, and we are also trying to deploy a test environment to verify these problems.

**Comment by SbloodyS** [comment]
> > I'm trying to package `UI-Next` into the docker image of `dev` branch. I try to replace the `dist` folder compiled by `UI-Next` with the previous version to the `ui` folder under the API module. I start the API module to access the domain/dolphinscheduler and get the following errors. ![](https://camo.githubusercontent.com/e4c23963596425077d092fca83ccc50816317cdd8a8a911c574cce31319f3612/68747470733a2f2f766970312e6c6f6c692e696f2f323032322f30322f32382f6a32726d55747077666b31735663452e706e67)
> > And then I try to remove the absolute path `/` in index.html. I got another errors. ![](https://camo.githubusercontent.com/6a05791c6e3d4ff311088cfa189161300a1cc04417c866a4b4a58a9ff4ddb1a3/68747470733a2f2f766970322e6c6f6c692e696f2f323032322f30322f32382f526c4b37735871784d725a516134382e706e67)
> > Is it that the compatibility of API modules has not been completed?
> 
> Please open a separate issue for this issue, I will take a look at it later, but there is no problem on my side at present, and we are also trying to deploy a test environment to verify these problems.

Sorry. I'll open a new issue.

**Comment by labbomb** [comment]
I will deal with the new theme color field and unify it into blue

**Comment by labbomb** [comment]
I will deal with the serial number under the form should be uniformly displayed as #, and redundant multilingual configurations should be removed

**Comment by labbomb** [comment]
I will rewrite project management list page

**Comment by labbomb** [comment]
I will deal with Unified processing of the message prompts returned by the back-end interface

**Comment by Amy0104** [comment]
I will add the corresponding state for the saving action.

**Comment by labbomb** [comment]
I will deal with remove spaces from all input boxes

**Comment by labbomb** [comment]
i will deal with the label of the form in the unified project is arranged up and down

**Comment by labbomb** [comment]
i will deal with component name changed to big camel case

**Comment by calvinjiang** [comment]
I'll deal with the issue of "Misspelled search word in Resource - File Manage code" . Please assign that to me.

**Comment by calvinjiang** [comment]
I'll deal with the issue of "Workflow relationship has no data to make a prompt with empty data instead of showing a Card component with no content" . Please assign that to me .

**Comment by labbomb** [comment]
I will deal with all table interface requests increase the loading state
