### ISSUE TITLE
[Bug] [Task cannot be deleted] After creating a task in the web interface, it cannot be deleted

### ISSUE THREAD

**Issue by narrotor12** [apache/dolphinscheduler#8573]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

在web界面新建任务但是删不掉    除了修改源码还有别的解决方案嘛
![image](https://user-images.githubusercontent.com/11962619/158782487-cc683d5d-742d-4954-97dc-1cc0259fa63f.png)

这行提高前面就可以了
![image](https://user-images.githubusercontent.com/11962619/158782576-5b51720c-6d81-47c3-beac-f76981d16e89.png)

### How to reproduce

安装分布式后启动web 直接进去建新任务 然后删除就可以重现问题

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
205 don't have this issue
