### ISSUE TITLE
[update][interface] Update interface call problem

### ISSUE THREAD

**Issue by xinxingi** [apache/dolphinscheduler#8576]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Update interface call problem

### Use case

I want to use this interface to automatically add an instance to the workflow via code

How to generate taskCode in LOCATIONS?

DopinScheduler Version : 2.0.0

<img width="427" alt="1fcf1123ff60b88d7f43d0e8c0ac5f0" src="https://user-images.githubusercontent.com/49302071/155950544-140d6c2b-0ecf-49f4-b761-c81c62460e72.png">

<img width="827" alt="9ae9c53a2ccfe57e0d40a23c30055dd" src="https://user-images.githubusercontent.com/49302071/155950551-2c4e2af7-d298-418a-bfbd-ace02ec6f880.png">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangyizhi1** [comment]
You can directly set the locations to "null" and the ui will automatically format the DAG when there are no locations.
Version: 2.0.3

If you want to create taskCode, use genTaskCodeList interface.

<img width="1606" alt="image" src="https://user-images.githubusercontent.com/87303815/155961433-6c034872-7342-4306-ba59-6cf45238736a.png">
