### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] Errors that appear in standalone after packaging and compiling.

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8580]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I'm trying to package ```UI-Next``` into the docker image of ```dev``` branch. I try to replace the ```dist``` folder compiled by ```UI-Next``` with the previous version to the ```ui``` folder under the API module. I start the API module to access the domain/dolphinscheduler and get the following errors.
![](https://vip1.loli.io/2022/02/28/j2rmUtpwfk1sVcE.png)

And then I try to remove the absolute path ```/``` in index.html. I got another errors.
![](https://vip2.loli.io/2022/02/28/RlK7sXqxMrZQa48.png)

Is it that the compatibility of API modules has not been completed?

### What you expected to happen

above.

### How to reproduce

above.

### Anything else

In standalone mode.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
@songjianet Please take a look at this issue when you have spare time. Thanks.

**Comment by songjianet** [comment]
> @songjianet Please take a look at this issue when you have spare time. Thanks.

Thanks for your feedback, I'll look into it.

**Comment by SbloodyS** [comment]
The front-end solves errors in standalone by adding the `/dolphinscheduler/ui/` base path to `vite.config.ts` and `src/router/index.ts` , you can refer to the associated front-end pr.

So far. The following questions remains:
1. http://ip:12345/dolphinscheduler can not be reach. http://ip:12345/dolphinscheduler/ui/ can be reach.
2. The front end requests the back end to configure the public network IP and Port instead of private IP and Port.
3. Refresh page not in the index page ```/dolphinscheduler/ui/``` may cause 401 error.
