### ISSUE TITLE
[Feature][python] Add pre-commit to run basic test before commit

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#8591]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Some of the tests could be run locally before users submit to the remote branch. I think [pre-commit](https://pre-commit.com) is a good component to do that, it will make our workflow more easier

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jim-parsons** [comment]
assign it to me. thx~ big old!

**Comment by zhongjiajie** [comment]
Hi @tangchunbo I assigned this issue to you now. Looking forward to your contribution. BTW, do you have a plan for it? I want to add this feature in next release(within two months)

**Comment by jim-parsons** [comment]
i've install the `pre-commit` locally. I guess we can make it clear in the `DEVELOP.MD` and set some config in the `.pre-commit-config.yaml`. In my thought, i'll execute the `pre-commit` every time commits happen, what do u think

**Comment by zhongjiajie** [comment]
> I guess we can make it clear in the DEVELOP.MD

Yeah, when we add pre-commit for development, we should also add some content in `DEVELOP.md` to let user how to use it

**Comment by zhongjiajie** [comment]
BTW, we should also add existing static check in https://github.com/apache/dolphinscheduler/blob/f3d663a7eaf559e855971e83d593a827196a1aa0/.github/workflows/py-ci.yml#L51-L58
to pre-commit. Which would give user fast-fail when then try to commit some style but to python API

**Comment by jim-parsons** [comment]
sorry it's late, because this month is the kpi month ~

**Comment by zhongjiajie** [comment]
Thank, It is does not matter, I will take a look at Monday
