### ISSUE TITLE
[Bug] [API] Badly formatted multipart request when I upload jar file

### ISSUE THREAD

**Issue by shin8085** [apache/dolphinscheduler#8597]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

There is a similar issues that has not been solved
I can't upload jar file
![image](https://user-images.githubusercontent.com/45345737/156103850-c6f01413-7d2c-4ca4-997e-9f34a88ef372.png)
![image](https://user-images.githubusercontent.com/45345737/156103911-8174b9f0-41ce-44a6-a4bc-cac7ec43bce4.png)
![image](https://user-images.githubusercontent.com/45345737/156103942-4be82927-30ca-486f-aebc-6af1cb5fc804.png)

### What you expected to happen

above.

### How to reproduce

above.

### Anything else

I can upload any type of file except jar

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
I have checked this in ds1 environment (dev and new UI) and it's okay.
Will check this in version 2.0.5 lately.
