### ISSUE TITLE
[Bug] [UI]Workflow node titles are not fully displayed

### ISSUE THREAD

**Issue by zheng-zy** [apache/dolphinscheduler#8599]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![1](https://user-images.githubusercontent.com/13825054/156115233-63f90a19-964c-47a3-a551-24c586bb93ba.png)
您好，我们是海豚的重度深度用户，在使用上各方面主要功能都能够解决，目前遇到在1.3.8版本迁移到2.0.3后，工作流标题显示不全，在问题处理和定位上比较难解决，希望能够得到帮助，解决一下

### What you expected to happen

名称显示不全

### How to reproduce

工作流任务节点名字大于9个中文字符即可浮现名称被缩写

### Version

2.0.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
You can refer to issue #8163. It may be fixed in version 2.0.4

**Comment by songjianet** [comment]
> You can refer to issue #8163. It may be fixed in version 2.0.4

Thank you for your feedback. Is such that. If there are no other issues, I will close this issue.

**Comment by songjianet** [comment]
Thank for your feedback.
