### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] User field for creating project is wrong

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8605]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

所属用户应该是下拉单选或者多选框，不应为输入框

![image](https://user-images.githubusercontent.com/76080484/156121707-f476a8a0-be65-4c56-8acc-9391f2642fb3.png)

### What you expected to happen

 所属用户应该是下拉单选或者多选框，不应为输入框

### How to reproduce

创建项目时

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
![image](https://user-images.githubusercontent.com/19239641/156322702-5c90e081-6782-4e14-a0c2-1d5e6bc3c7ee.png)
When dealing with this problem, please add a message that the user does not exist. For details. Please check https://github.com/apache/dolphinscheduler/issues/8607.

**Comment by songjianet** [comment]
Thank you for your feedback. We decided to rewrite the related functions of the project list, while solving this problem, to be able to unify the code style in the project, for this, I will close this issue and link it here. https://github.com/apache/dolphinscheduler/issues/8673

**Comment by labbomb** [comment]
@XuXuClassMate I checked and the old project was an input box instead of a drop down

**Comment by XuXuClassMate** [comment]
<img width="710" alt="image" src="https://user-images.githubusercontent.com/76080484/156493185-771dcfb7-cb97-43d4-9265-453ee3817f42.png">
