### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] The backend does not verify the user group when creating a project

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8607]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

创建项目时后端未对用户组进行校验

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/76080484/156122438-fd6df41f-0254-4a08-9aec-c0768df98968.png">

### What you expected to happen

希望新建可以像修改时对用户组进行校验

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/76080484/156122628-112d3604-9343-44d0-b940-dbff250ac186.png">

### How to reproduce

创建项目

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. It's the same issue as this one, so I'll close this issue. https://github.com/apache/dolphinscheduler/issues/8605
