### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] Create project field verification problem

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8608]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

所有输入框都为一个或者连续多个空格不应该能创建成功

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/76080484/156123204-3a116a14-bb2d-4236-af51-9c67a861e541.png">

### What you expected to happen

所有输入框都为一个或者连续多个空格不应该能创建成功

### How to reproduce

所有输入框都为一个或者连续多个空格不应该能创建成功

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/76080484/156123204-3a116a14-bb2d-4236-af51-9c67a861e541.png">

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. For the space problem of the input box, we believe that the priority is not high, it is a point that can be optimized, under normal circumstances, the user will not enter a lot of space in normal use. I'm going to close this question, please see https://github.com/apache/dolphinscheduler/issues/8565.
