### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] The backend error page for creating a project does not prompt

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8609]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

新建项目报错页面为提示

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/76080484/156124567-440f67e2-e495-48cc-ab4d-8b5ffe046faf.png">

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/76080484/156124981-7bfed214-6caa-4b0a-81ea-b435f5e2a522.png">

### What you expected to happen

1、报错后页面提示。
2、新建时打开弹窗告知用户字段使用方法和校验规则

### How to reproduce

新建项目

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. This issue will be dealt with uniformly. https://github.com/apache/dolphinscheduler/issues/8565
