### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] The display of the project name is too long, causing UI confusion

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8611]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

项目名称展示超长导致UI错乱

<img+width="1429"+alt="image"+src="https://user-images.githubusercontent.com/76080484/156125508-41cc27d3-0303-4a53-810b-a7ebff15b940.png">

### What you expected to happen

显示项目名称展示字数，超出部分由省略号代替，鼠标悬浮上面时弹窗展示全量名称

### How to reproduce

新建项目

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by XuXuClassMate** [comment]
<img width="1915" alt="image" src="https://user-images.githubusercontent.com/76080484/156286861-4056e35f-06a8-41cc-8c48-ed2c71708e76.png">

**Comment by songjianet** [comment]
Thank you for your feedback. It's the same issue as this one, so I'll close this issue. https://github.com/apache/dolphinscheduler/issues/8610
