### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] Modify project name error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8613]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

修改项目名称时候错误，所有的项目名称会展示为新建前列表第一条数据项目名称

https://user-images.githubusercontent.com/76080484/156127502-94a65979-1eaa-44c4-8aaa-106834de433d.mp4

### What you expected to happen

显示当前项目的名称

### How to reproduce

新建后点击修改项目名称

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by XuXuClassMate** [comment]
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/76080484/156127974-7e9e30eb-89ff-4d19-af97-a92acfb8cfeb.png">

**Comment by songjianet** [comment]
Thank you for your feedback. We decided to rewrite the related functions of the project list, while solving this problem, to be able to unify the code style in the project, for this, I will close this issue and link it here. https://github.com/apache/dolphinscheduler/issues/8673
