### ISSUE TITLE
[Improvement][UI] It seems that a length limit is setting for the value of the global variable

### ISSUE THREAD

**Issue by hezhiming1995** [apache/dolphinscheduler#8614]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I want to set a **long global variable**, but it is truncated when filling in the UI interface. Also I didn't find a specific configuration file

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @hezhiming1995 Can you provide the UI screentshot or gif to show this issue?
