### ISSUE TITLE
[Bug] [WorkFlowLineage] work flow lineage search result missing data

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8616]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![](https://vip2.loli.io/2022/03/01/Tx7jRAFYJMp2irC.png)

![](https://vip1.loli.io/2022/03/01/gQmCFqZud38hjHi.png)

### What you expected to happen

work flow lineage's result is right.

### How to reproduce

above.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 597365581** [comment]
+1
