### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] Front-end prompt optimization suggestions

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8618]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

新建及修改时用户输入错误提示

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/76080484/156130545-9a7d0eeb-4a13-4c2e-bb64-20fd8182b197.png">

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/76080484/156130685-9ce316ea-443f-4460-a69c-6c4096675404.png">

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/76080484/156130737-e3626f1f-51e2-41b5-b957-310b166937dc.png">

### Use case

1、输入前，可以在输入框中浅色提示输入规则
2、输入中，超长不符合规则字段旁及时报错提示
3、输入后，弹窗提示*字段数据规则错误，错误原因，提交按钮置灰不可点击

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. We decided to rewrite the related functions of the project list, while solving this problem, to be able to unify the code style in the project, for this, I will close this issue and link it here. https://github.com/apache/dolphinscheduler/issues/8673
