### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] Clicking on the Logo will not jump to the homepage

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8620]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

点击Logo不会跳转到首页

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/76080484/156132075-288ee51c-0735-4348-b20d-1be80ad2f22b.png">

### What you expected to happen

和旧版本保持一致，
点击Logo可以跳转到首页

### How to reproduce

1、进入其他页面
2、点击Logo

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. I don’t think this is a necessary function. There is already a menu on the home page on the right side of the logo. Users can jump to the home page by clicking on the home page. Similar functions are located in two adjacent places, and we think that only one of them can be reserved. So I'm going to close this question.
