### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] Modified the system language, the chart text is not changed to Chinese as expected

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8621]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

修改了系统语言，图表文字未按预期更改为中文

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/76080484/156132876-e362110d-15f1-4e00-9ed0-3c8eeba197fc.png">

日期组件也应进行更改

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/76080484/156133347-57fc1d3b-72b4-4865-a4fd-dbd77321ba2b.png">

### What you expected to happen

系统文字会跟随设置设置更改

### How to reproduce

打开首页

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I'll deal with this later.

**Comment by songjianet** [comment]
As for the problem that the time picker seems to be the `Naive UI` component library, we can't fix the multi-language problem of this component for the time being, but the multi-language problem of the chart and table has been fixed, we will close this problem, and feedback the problem to `Naive UI`, After getting it out, we will deal with it as soon as possible.

**Comment by XuXuClassMate** [comment]
ok~
