### ISSUE TITLE
[Feature][UI-Next][V1.0.0-Alpha] process definition/instance operation button too small to click

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8622]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![](https://vip1.loli.io/2022/03/01/7PDMXIA8U4wtWrf.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. Will be processed later.

**Comment by songjianet** [comment]
I will fix it.
