### ISSUE TITLE
[Bug][UI-Next][V1.0.0-Alpha] click timing error in process definition page

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8624]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![](https://vip2.loli.io/2022/03/01/7cNiWD5Uyw18EFB.png)

### What you expected to happen

click successfully.

### How to reproduce

above.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. Will be processed later.

**Comment by calvinjiang** [comment]
I'll work out this issue.
