### ISSUE TITLE
[Bug][UI-Next][V1.0.0-Alpha] Missing full screan button and download button in view log

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8626]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![](https://vip2.loli.io/2022/03/01/fwdgVUJOzCZ2MSi.png)

### What you expected to happen

above.

### How to reproduce

above.

### Anything else

above.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. Will be processed later.

**Comment by songjianet** [comment]
Thank you for your feedback. The download log button has been moved to the list action. The full screen function will be placed in the optimization point to uniformly process all log functions in the project. If you have no doubts about this, I will close this question.
