### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] Click to clear, the time component fails to clear the time interval

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8627]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

点击清除，时间组件未成功清除时间区间

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/76080484/156136299-f9dfb678-8c74-4e9d-b564-eb9932569a1a.png">

### What you expected to happen

期望点击清除时，时间组件成功清除时间区间

### How to reproduce

1、选择时间区间
2、点击清除时间区间

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. Will be processed later.

**Comment by labbomb** [comment]
@XuXuClassMate I'll deal with the problem, you want to clear the button, or you want to call the interface after you clear it

**Comment by XuXuClassMate** [comment]
> @XuXuClassMate I'll deal with the problem, you want to clear the button, or you want to call the interface after you clear it

Click the button to clear the data in the time component box

**Comment by songjianet** [comment]
> > @XuXuClassMate I'll deal with the problem, you want to clear the button, or you want to call the interface after you clear it
> 
> Click the button to clear the data in the time component box

Whether to keep the current data after clearing, or request data for a default time period after clearing.

**Comment by XuXuClassMate** [comment]
> > > @XuXuClassMate I'll deal with the problem, you want to clear the button, or you want to call the interface after you clear it
> > 
> > 
> > Click the button to clear the data in the time component box
> 
> Whether to keep the current data after clearing, or request data for a default time period after clearing.

I think the default is the current time, the delete time input box is empty

**Comment by songjianet** [comment]
> > > > @XuXuClassMate I'll deal with the problem, you want to clear the button, or you want to call the interface after you clear it
> > > 
> > > 
> > > Click the button to clear the data in the time component box
> > 
> > 
> > Whether to keep the current data after clearing, or request data for a default time period after clearing.
> 
> I think the default is the current time, the delete time input box is empty

It is a concept of a time range, not a concept of the current time.
