### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] Serial number/number text (title) display error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8629]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

序号/编号文字展示错误

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/76080484/156137892-6ffb0386-001d-423e-a8c0-b0b1ad905258.png">

### What you expected to happen

与老UI展示一致

<img width="1914" alt="image" src="https://user-images.githubusercontent.com/76080484/156138051-f8a393c8-5c82-4cac-abc5-4c0d033ba901.png">

### How to reproduce

1、点击首页

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. Will be processed later.

**Comment by songjianet** [comment]
You can refer to this https://github.com/apache/dolphinscheduler/issues/8634 issue. In the new UI, all tables will be uniformly processed as #. Issues related to this do not need to be opened. I will close it.
