### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] The task instance button prompts an error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8632]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

项目管理-项目实例-任务-任务实例，执行失败任务强制成功按钮提示错误

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/76080484/156141468-b17f0e1f-e62a-4261-8c5a-a47a0748da45.png">

### What you expected to happen

按钮提示为  强制成功

### How to reproduce

项目管理-项目实例-任务-任务实例，执行失败任务强制成功按钮提示错误

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. Will be processed later.

**Comment by songjianet** [comment]
I'll deal with this later.
