### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] Workflow definition click to modify does not get the expected response

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8633]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

工作流定义点击修改未得到预期相应

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/76080484/156142995-927b79fd-ab03-4a2a-9c8a-84a9edf24851.png">

### What you expected to happen

成功跳转到工作流编辑页面

### How to reproduce

点击编辑

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. Will be processed later.

**Comment by calvinjiang** [comment]
I'll work out this issue.
