### ISSUE TITLE
[Feature][datax] DataX TargetDataBase supports clickhouse

### ISSUE THREAD

**Issue by simsicon** [apache/dolphinscheduler#8635]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently The TargetDataBase only supports [MySQL, Postgresql, Oracle and SqlServer](https://github.com/apache/dolphinscheduler/blob/3c10bbe1571573257c855667d99590c6aa87b423/dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/datax.vue#L62), While the Datasource supports Clickhouse, It should be the same.

### Use case

Calculate data from clickhouse to clichouse

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @simsicon Can you try to submit the pr of support clickhouse to clickhouse?

**Comment by simsicon** [comment]
> Hi @simsicon Can you try to submit the pr of support clickhouse to clickhouse?

The thing is I am not familiar with Java nor Vue, I don't know how to setup the dev env and how to test it. Is there any guidance to that?

**Comment by caishunfeng** [comment]
> I don't know how to setup the dev env and how to test it. Is there any guidance to that?

You can see the doc standalone: https://dolphinscheduler.apache.org/en-us/docs/dev/user_doc/guide/installation/standalone.html, which can quick start DS on your IDE. 
The doc Task SPI extension : https://dolphinscheduler.apache.org/en-us/development/backend/spi/task.html.

>The thing is I am not familiar with Java nor Vue
Can you give some suggestion or best practices? @CalvinKirs @zhuangchong
