### ISSUE TITLE
[Bug][Api] Resource Re Upload, name  duplicate

### ISSUE THREAD

**Issue by jiangleifree** [apache/dolphinscheduler#8645]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Resource Re Upload, advised to allow duplicate file names
![image](https://user-images.githubusercontent.com/35941598/156282963-ad2578b8-8bbb-4bd6-bf63-b2e4fb44134b.png)

### Use case

Re Upload Resource

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi, Which version you are using?

**Comment by jiangleifree** [comment]
> 

1.3.2

**Comment by SbloodyS** [comment]
> 1.3.2

Sorry. This version is no longer in the maintenance list.

**Comment by caishunfeng** [comment]
Hi @leileiwangqing Please check the 2.0.x version of this issue.

**Comment by zhanqian0609** [comment]
I'll fix it
