### ISSUE TITLE
[Bug] [UI-Next][V1.0.0-Alpha] owned user should use dropdown to avoid user not found error when create new project

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8647]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![](https://vip1.loli.io/2022/03/02/PFMTC95pRs2NcBg.png)

### What you expected to happen

owned user should use dropdown to avoid user not found error when create new project

### How to reproduce

owned user should use dropdown to avoid user not found error when create new project

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. This question seems to have an identical issue, so I will close this issue. https://github.com/apache/dolphinscheduler/issues/8605
