### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] create workflow definition error in standalone mode

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8648]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![](https://vip1.loli.io/2022/03/02/8sUmlo53pMhLAIX.png)

![](https://vip1.loli.io/2022/03/02/gRPzuWv7V5Mb93O.png)

No requests were sent in standalone mode.

```http://localhost:3000/dolphinscheduler/tenants/list``` request will be sent In dev mode.

### What you expected to happen

successfully.

### How to reproduce

create workflow definition in standalone mode.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it.
