### ISSUE TITLE
[Bug][UI] Click home page and logo resource error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8650]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Click home page and logo resource error

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/76080484/156293654-23774553-5fa7-4132-87e0-97c52d25c71b.png">

### What you expected to happen

Normal display

### How to reproduce

Click home page and logo resource error

### Version

2.0.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Can I jump to the home page normally after clicking on the home page?

**Comment by XuXuClassMate** [comment]
> Can I jump to the home page normally after clicking on the home page?

> Clicking the home page and logo will report an error
error number is 404

**Comment by songjianet** [comment]
> > Can I jump to the home page normally after clicking on the home page?
> 
> > Clicking the home page and logo will report an error
> > error number is 404

I checked the functionality of this part in the latest code, but did not find this error, if I can't continue to provide some error information, I will close this issue.

**Comment by XuXuClassMate** [comment]
我也无法复现了
