### ISSUE TITLE
[Bug][UI] Click Project Management / workflow relationship to report an error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8651]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Click Project Management / workflow relationship to report an error

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/76080484/156294298-ed22a303-5a1e-4062-b3d1-1de12ed2ba7a.png">

### What you expected to happen

Click normal

### How to reproduce

Click Project Management / workflow relationship

### Version

2.0.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Is it possible to jump to the page normally after clicking?

**Comment by songjianet** [comment]
I checked the functionality of this part in the latest code, but did not find this error, if I can't continue to provide some error information, I will close this issue.

**Comment by XuXuClassMate** [comment]
The display is now normal
