### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] Project module does not display project list properly in safari browser

### ISSUE THREAD

**Issue by ronyang1985** [apache/dolphinscheduler#8652]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Project module does not display project list properly in safari browser

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/13843983/156304112-39e76993-7c01-44fb-aae6-662d57c554a2.png">

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/13843983/156304121-d7d129d8-fac3-4e81-b700-a678beac2bba.png">

### What you expected to happen

display project list properly in safari browser

### How to reproduce

my computer
<img width="586" alt="image" src="https://user-images.githubusercontent.com/13843983/156305231-6e547bec-1689-4e1c-a269-26cb6e0f4933.png">

about safari version
<img width="284" alt="image" src="https://user-images.githubusercontent.com/13843983/156304283-a090934f-9c2e-4a21-a909-4c0435fc4056.png">

launch ui-next 

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. I will investigate this problem later, probably because Apple's new system has a compatibility problem with the time string separated by the middle and horizontal lines.
