### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] edit and delete button display incorrectly in security/tenant-manage and more 

### ISSUE THREAD

**Issue by ronyang1985** [apache/dolphinscheduler#8656]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

safari
<img width="1448" alt="image" src="https://user-images.githubusercontent.com/13843983/156305929-b9991c8b-4bb8-44da-9301-e9e0c727f1f5.png">
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/13843983/156305964-a78f6a24-8887-4137-8c34-bbc8ccecd896.png">

chrome
<img width="1445" alt="image" src="https://user-images.githubusercontent.com/13843983/156306241-01de1e25-359c-4f2a-ad4a-f313706e0901.png">

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/13843983/156306194-4d3a80f2-c43a-4c6e-ad47-50b0ffacaae7.png">

### What you expected to happen

display correctly when use safari browser

### How to reproduce

launch ui-next, visit security/tenant-manage and security/yarn-queue-manage

my computer
<img width="586" alt="image" src="https://user-images.githubusercontent.com/13843983/156306423-37194a34-f4cb-4b1d-ba67-44e0a11f9507.png">

about safari version
<img width="284" alt="image" src="https://user-images.githubusercontent.com/13843983/156306453-63ca6833-c982-4201-87be-5fa93b354212.png">

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by labbomb** [comment]
I will fix it
