### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] These two buttons are missing the selected status.

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8658]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

These two buttons are missing the selected status

![image](https://user-images.githubusercontent.com/76080484/156309461-c3a36425-5d63-41df-a427-b83009d4d4c9.png)

### What you expected to happen

selected status

### How to reproduce

click

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by labbomb** [comment]
Ok, I'll deal with that later
