### ISSUE TITLE
[Bug] [doc] Bug title 

### ISSUE THREAD

**Issue by kinghuisFFFF** [apache/dolphinscheduler#8663]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

表结构和文档字段不一致
https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/architecture/task-structure.html
V2.0.3版本 t_ds_process_definition 
表中17个字段，文档中20个

### What you expected to happen

表结构和文档字段一致

### How to reproduce

表结构和文档字段不一致
https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/architecture/task-structure.html
V2.0.3版本 t_ds_process_definition 
表中17个字段，文档中20个

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jim-parsons** [comment]
link #8628

**Comment by zhongjiajie** [comment]
@tangchunbo Thanks for your pointing it out 👍

**Comment by zhongjiajie** [comment]
close due to duplicate to #8628
