### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] Creating tasks configuration form can not switch  properly when task type switch

### ISSUE THREAD

**Issue by ronyang1985** [apache/dolphinscheduler#8672]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when creating task in projects/task-definition
Task configuration form does not switch properly with task type switch,and can not create task 

UI-NEXT
<img width="584" alt="image" src="https://user-images.githubusercontent.com/13843983/156486283-87164ed4-1aad-48b6-827b-734794922b19.png">

original UI

<img width="713" alt="image" src="https://user-images.githubusercontent.com/13843983/156486316-7b73b5a0-d82a-40e3-bfa6-a45e371accac.png">

### What you expected to happen

 create task works fine

### How to reproduce

the bug is obviously

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will resolve it.
