### ISSUE TITLE
[Bug] [UI-Next][v1.0.0-Alpha]  When creating a new project, the user box should not be clickable or inputable, but should only be displayed

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8674]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When creating a new project, the user box should not be clickable or inputable, but should only be displayed

<img width="1911" alt="image" src="https://user-images.githubusercontent.com/76080484/156493882-bed3777c-624f-4374-be30-3163cc1448a8.png">

<img width="829" alt="image" src="https://user-images.githubusercontent.com/76080484/156493956-a03bc288-198a-46e4-8ebc-63a58b2ce1df.png">

### What you expected to happen

should only be displayed

### How to reproduce

When creating a new project

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. We decided to rewrite the related functions of the project list, while solving this problem, to be able to unify the code style in the project, for this, I will close this issue and link it here. https://github.com/apache/dolphinscheduler/issues/8673
