### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] There is no prompt for error type and error details

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8678]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

There is no prompt for error type and error details

<img width="1912" alt="image" src="https://user-images.githubusercontent.com/76080484/156511553-d29204b6-8f6a-4556-8fa2-464c463c8b93.png">

### What you expected to happen

Prompt error type and error details

### How to reproduce

1、
<img width="559" alt="image" src="https://user-images.githubusercontent.com/76080484/156512340-a09d7265-c056-45f0-afbc-9ff1b8cf4e14.png">

2、
<img width="580" alt="image" src="https://user-images.githubusercontent.com/76080484/156512450-5881ce32-6de6-418a-b61d-ab69d146b760.png">

<img width="588" alt="image" src="https://user-images.githubusercontent.com/76080484/156512535-407fc8ff-7e79-4391-9cc8-706400288ea4.png">

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it.

**Comment by devosend** [comment]
This is not a UI bug. You can put forward a new improvement issue and optimize the front and back ends together.

**Comment by songjianet** [comment]
> This is not a UI bug. You can put forward a new improvement issue and optimize the front and back ends together.

OK, then I'll close this issue first and optimize it later.
