### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] If the drop-down box is selected, it cannot be deleted, and there is no clear button

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8680]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

If the drop-down box is selected, it cannot be deleted, and there is no clear button

![image](https://user-images.githubusercontent.com/76080484/156514799-5b6137db-ffde-40a5-80af-e29325daceb3.png)

### What you expected to happen

I think I can clear the selection box

### How to reproduce

When running a workflow

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it.
