### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] Workflow execution error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8690]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Workflow execution error

<img width="1571" alt="image" src="https://user-images.githubusercontent.com/76080484/156691383-e0cdcb28-94cf-41a2-bfad-8e5587c99dab.png">

If this ” execType“  field is not false, it will fail, otherwise it will succeed

<img width="1533" alt="image" src="https://user-images.githubusercontent.com/76080484/156691502-16627d54-1110-42da-88d9-6ba15c095f76.png">

path:/executors/start-process-instance

<img width="997" alt="image" src="https://user-images.githubusercontent.com/76080484/156691724-8089dfe4-af2b-4d4c-8b11-b914a2c21f3e.png">

### What you expected to happen

normal operation

### How to reproduce

Click Run workflow

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I'll work out this issue.

**Comment by devosend** [comment]
I will fix it.
