### ISSUE TITLE
[Bug] [alert] Email sending failed

### ISSUE THREAD

**Issue by zr9883** [apache/dolphinscheduler#8691]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

dolphinscheduler-alert 
At this time, the workflow instance runs without sending mail or log output

### What you expected to happen

email success

### How to reproduce

menu:
Security --> Warning instance manage
Create Alarm Instance --> Select plugin email

show_type choose attachment 
error
At this time, the workflow instance runs without sending mail or log output

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @zhuangchong can you take a look for this issue? I'm not sure whether the email alert plugin support attachment type.

**Comment by zhuangchong** [comment]
> Hi @zhuangchong can you take a look for this issue? I'm not sure whether the email alert plugin support attachment type.

OK, I'll check.

**Comment by caishunfeng** [comment]
I found the same issue, so this issue will be close.

**Comment by ltcaxx** [comment]
I am using the latest version and this bug is not resolved either
