### ISSUE TITLE
[Bug] [dolphinscheduler-api] grant project may be repeated

### ISSUE THREAD

**Issue by zzdwn** [apache/dolphinscheduler#8696]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

grant project may be repeated

### What you expected to happen

Before granting project ,old project list should be deleted

### How to reproduce

User A add a project a1
Admin grant a1 project to B , then b have a1 project.
But Admin grant other projects to B, a1 project will be repeated in project list.
![bug](https://user-images.githubusercontent.com/100904284/156722406-799bf37d-a2e2-4e65-8c44-e8305a266f70.png)

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. For the old UI, we will only deal with security-related issues. You can try the new UI to see if the same issue exists. You are welcome to experience the new UI. For this reason, I will close this issue.
