### ISSUE TITLE
[Feature] Task Node Reuse（任务节点复用）

### ISSUE THREAD

**Issue by wsh66660** [apache/dolphinscheduler#870]
**Is your feature request related to a problem? Please describe.**
Every time a workflow is newly defined, new nodes must be created on the spot

**Describe the solution you'd like**
1.Can you add a task node menu to build a new node in advance?
2.When defining workflow, you can create new nodes and use one of the existing nodes.

**Describe alternatives you've considered**
In this way, the node information can be reused and the definition time of flow workflow can be saved.

**Additional context**
![image](https://user-images.githubusercontent.com/30776503/65487934-8826ed00-deda-11e9-9774-fa52244e2b19.png)

---

**Is your feature request related to a problem? Please describe.**
每次新定义工作流的时候都必须当场新建节点

**Describe the solution you'd like**
1、能不能加个任务节点菜单，可以提前新建好节点
2、定义工作流的时候可新建节点和使用已有节点二选一

**Describe alternatives you've considered**
这样节点信息可复用，且节省流工作流的定义时间

**Additional context**
![image](https://user-images.githubusercontent.com/30776503/65487934-8826ed00-deda-11e9-9774-fa52244e2b19.png)

**Comment by dailidong** [comment]
for now， we have task copy like this:
![image](https://user-images.githubusercontent.com/15833811/65505509-f4661880-defb-11e9-9cc2-f343777fc328.png)

can this solve your problem? 

please update/add description in English for better global communication, thx!

**Comment by w771920097** [comment]
This is possible in the same workflow, but we hope that the new task node will take effect in all workflows.

---

这在同一个工作流里是可行的，但我们希望新建的任务节点能在所有工作流里生效

**Comment by chenhongen** [comment]
最后怎么样了。。
