### ISSUE TITLE
[bug][UI Next][V1.0.0-Alpha] An error page

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8722]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

An error page

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/76080484/156958639-10e7e382-491a-4587-9183-4d2750c65854.png">

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/76080484/156958683-59f9d8dc-60fc-4612-8c80-fcfc0629c2b1.png">

### What you expected to happen

Normal use

### How to reproduce

Open the page

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. Can you describe the steps to reproduce this problem.

**Comment by XuXuClassMate** [comment]
> 感谢您的反馈意见。您能否描述重现此问题的步骤。

The front end is dev branch, NPM runs, forwards version 2.0.5 of the back end, and then opens the page to report an error

**Comment by devosend** [comment]
I will fix it
