### ISSUE TITLE
[Bug] [server] Dolphinscheduler failed to submit tasks properly when Mariadb started late 

### ISSUE THREAD

**Issue by bigdatazhao** [apache/dolphinscheduler#8725]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Dolphinscheduler does not submit tasks when mariadb starts later than ZooKeeper during Linux startup or restart.

### What you expected to happen

I hope the task can be submitted normally.

### How to reproduce

Make the Mariadb start two minutes later than the DolphinScheduler. The DolphinScheduler screen still shows the task, but the actual task is not submitted. Dolphinscheduler does not retry reading tasks in Mariadb.

### Anything else

1. This happens only occasionally when the cluster is first started or restarted。
2. Dolphinscheduler does not have a retry mechanism when it fails to connect to Mariadb。
3. It is possible that this problem also exists in the latest version。

### Version

1.3.9

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @bigdatazhao can you check the 2.0.5 version of this issue?

**Comment by bigdatazhao** [comment]
> Hi @bigdatazhao can you check the 2.0.5 version of this issue?

I have tested and verified that the latest version still has this problem.

**Comment by caishunfeng** [comment]
I think maybe set the retry config in task definition can help you.
