### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] Missing function, import workflow, missing file drag upload window upload

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8728]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Missing function, import workflow, missing file drag upload window upload

new dev:
<img width="665" alt="image" src="https://user-images.githubusercontent.com/76080484/156964933-77d729a5-5bd4-4331-951e-0e15c4cc8327.png">

### What you expected to happen

old version:2.0.5
<img width="1599" alt="image" src="https://user-images.githubusercontent.com/76080484/156965185-52990ec8-bde5-4404-9039-1149621cfe05.png">

### How to reproduce

dev version ：Click Import Workflow

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank for your feedback.

**Comment by calvinjiang** [comment]
@XuXuClassMate Could you give more details about this issue?

**Comment by XuXuClassMate** [comment]
> @XuXuClassMate您能否提供有关此问题的更多详细信息？

The new UI lacks the ability to drag and upload files

![image](https://user-images.githubusercontent.com/76080484/156998160-eb1654b4-5ee7-4c2c-a8a7-a5c14aeff811.png)
