### ISSUE TITLE
[Bug][UI-Next][V1.0.0-Alpha] Backend locale should be consistent with ui

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8729]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![](https://vip1.loli.io/2022/03/07/5wBrp64WqRLK8d7.png)

The backend uses the cookie name ```language``` to get the locale in dolphinscheduler-ui.

### What you expected to happen

above.

### How to reproduce

above.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
