### ISSUE TITLE
[Bug][UI] The copy node function will affect the original node

### ISSUE THREAD

**Issue by jxeditor** [apache/dolphinscheduler#8746]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When using dataX tasks, the copy node function will affect the original node.

### What you expected to happen

Using the copy node function, the copied node should be independent and should not affect the original node.

### How to reproduce

1.Add a dataX task node
<img width="850" alt="image" src="https://user-images.githubusercontent.com/51101283/157145576-fb8b2f5a-56ac-4b9d-9758-6ee6991836a2.png">

2.Using the copy node feature
<img width="333" alt="image" src="https://user-images.githubusercontent.com/51101283/157145629-f567ab01-0eda-4719-a2e3-9645f596bbff.png">

<img width="285" alt="image" src="https://user-images.githubusercontent.com/51101283/157145676-920719d5-333c-4ae9-a677-b1baa484efa7.png">

3.Modify and save the copied node
<img width="809" alt="image" src="https://user-images.githubusercontent.com/51101283/157145736-b615e307-6df4-4119-abed-658ceeb47b3f.png">

4.View the original node again(The original node configuration is automatically modified)
<img width="713" alt="image" src="https://user-images.githubusercontent.com/51101283/157145815-72fef3bd-4495-4208-aeac-1ebef0e6ea7c.png">

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Old UI please don't mark UI Next.

**Comment by calvinjiang** [comment]
I'll check it out.

**Comment by calvinjiang** [comment]
I'll work it out.
