### ISSUE TITLE
[Bug][Api] Process using the dependence component cannot migrate between test and prod environment

### ISSUE THREAD

**Issue by donghaihu** [apache/dolphinscheduler#8756]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Process using the dependence component cannot migrate between test and prod environment,exmple datasource_id,resource_id etc.
This qustion had soleved in the #4826,but it opened in version 2.0.2.

### What you expected to happen

The process name, task name, etc. should be used when exporting and importing dependent components in the process. Or other field combinations that can guarantee portability and uniqueness.

### How to reproduce

![企业微信截图_16467282288862](https://user-images.githubusercontent.com/17972867/157203572-2923565c-1a13-4432-86f9-aeaf6c8fcb23.png)
![企业微信截图_16467282521478](https://user-images.githubusercontent.com/17972867/157203585-1c850bb6-48ba-4d7b-9624-241f4efa1f6d.png)

### Version

2.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @JinyLeeChina can you take a look of this issue?

**Comment by brave-lee** [comment]
I think this problem has been solved in #5910. Please check the 2.0.5 version.
