### ISSUE TITLE
[Improvement] [dolphinscheduler-worker] the object 'preTaskCache' is never used, Suggested deletion

### ISSUE THREAD

**Issue by guoshupei** [apache/dolphinscheduler#8758]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

worker received task execute request command and cache 'TaskExecutionContext'，and new  Object of 'preTaskCache', but unused. maybe it have other useful？

![image](https://user-images.githubusercontent.com/29919212/157243873-4405aa6f-9132-4f07-acaa-375f16e08aa5.png)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
It was used to transform to `TaskRequest` and keep in cache.

**Comment by guoshupei** [comment]
Yes, I understand the function of  cache, but transform to `TaskRequest ` used `taskExecutionContext ` of param  instead of `preTaskCache` of new Object（转换TaskRequest使用的是参数中的taskExecutionContext ，而不是new出来的preTaskCache对象，这里preTaskCache是不没有用到呢？）

**Comment by guoshupei** [comment]
> It was used to transform to `TaskRequest` and keep in cache.

Yes, I understand the function of  cache, but transform to `TaskRequest ` used `taskExecutionContext ` of param  instead of `preTaskCache` of new Object（转换TaskRequest使用的是参数中的taskExecutionContext ，而不是new出来的preTaskCache对象，这里preTaskCache是不没有用到呢？

**Comment by caishunfeng** [comment]
> Yes, I understand the function of cache, but transform to `TaskRequest ` used `taskExecutionContext ` of param instead of `preTaskCache` of new Object（转换TaskRequest使用的是参数中的taskExecutionContext ，而不是new出来的preTaskCache对象，这里preTaskCache是不没有用到呢？

Yes, you are right, I read it wrong before. Looking forward to your pr.

**Comment by zhongjiajie** [comment]
> > Yes, I understand the function of cache, but transform to `TaskRequest ` used `taskExecutionContext ` of param instead of `preTaskCache` of new Object（转换TaskRequest使用的是参数中的taskExecutionContext ，而不是new出来的preTaskCache对象，这里preTaskCache是不没有用到呢？
> 
> Yes, you are right, I read it wrong before. Looking forward to your pr.

Hi @caishunfeng , when issue was token by someone, should better assign issue to him/her. then we can see assigned in the issue lists
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/15820530/157789567-243374ec-0ca9-45a8-96a8-a0a4792d936e.png">
