### ISSUE TITLE
[Bug] [All  Module ] pom version should be 2.0.6-snapshot  in dev branch

### ISSUE THREAD

**Issue by zhuxt2015** [apache/dolphinscheduler#8759]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Since 2.0.5 release, in dev branch pom version should be 2.0.6-snapshot, but it still is 2.0.4-snapshot  

### What you expected to happen

pom version modified to 2.0.6-snapshot

### How to reproduce

checkout dev branch, then view the pom.xml file

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Yes, I will change the version later. Thanks your feedback.

**Comment by caishunfeng** [comment]
close by #9299
