### ISSUE TITLE
[Feature][API] Custom built-in parameters

### ISSUE THREAD

**Issue by Weipleasure** [apache/dolphinscheduler#8770]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

中文描述：
【功能】【API】自定义内置参数
所有项目当中的工作流都可以获取到自定义的内置参数。

### Use case

目前最新2.0.5版本提供内置参数都是基于T-1等相关的时间参数，但是金融行业（证券）相对特殊，定时跑批任务时间不是T-1（跑批时间参数不固定），而是交易日。由于每个工作流的时间参数都是一样的（上一个交易日），工作流之间的参数不能传递，只有在同一个工作流内部的参数才可以传递。因此，为了所有工作流的获取时间参数一样，我们在所有项目的每个工作流开始的第一个任务都是获取交易日，并设置为时间参数，作为参数传递下去。我们希望可以自定义内置参数，方便所有工作流获取。

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
@Weipleasure Good idea, can you add your design or what will you change to this issue description?

BTW, it's better to use the English first, which can make foreign developers also understand.
