### ISSUE TITLE
[block-Bug][UI Next][V1.0.0-Alpha]Account login error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8772]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The account and password are correct, the login interface works properly, and an error message is displayed on the get_user_info interface

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/76080484/157405884-912e6b71-fbf5-4108-92bf-c405fe4f288d.png">

### What you expected to happen

Login successful

### How to reproduce

Open the web page, enter the correct account password, and click login

### Anything else

No

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it.
