### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha]  The Create Time and Update Time fields returned an error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8776]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The Create Time and Update Time fields returned an error

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/76080484/157414340-d5791b15-b622-4b6a-aa9c-6649ce42e20f.png">

### What you expected to happen

Show the correct

### How to reproduce

I created the workflow at 5pm and the back end returned to create and update at 9am

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I preliminarily judged that this problem may be caused by the time zone. The back-end time has been processed, but the front-end has not yet started. This is a data incompatibility point.
