### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] An error occurred while importing workflow

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8777]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

An error occurred while importing workflow
The reason for the error is that：tenant not exists

<img width="1912" alt="image" src="https://user-images.githubusercontent.com/76080484/157416523-80ccb5fd-3750-44e0-bc33-a42ab8b20f15.png">

### What you expected to happen

The modification is saved successfully

### How to reproduce

Import workflow and modify content click Save

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will solve this.
