### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]The letters overlap with the input field

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8778]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The letters overlap with the input field

<img width="1908" alt="image" src="https://user-images.githubusercontent.com/76080484/157419190-4f8aefed-7c03-4b47-9d6a-56e84ec8bdd4.png">

### What you expected to happen

There is some space between the letters and the input field

### How to reproduce

When saving the workflow

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.
