### ISSUE TITLE
[Bug] [UI Next][V1.0.0-Alpha] Create duplicate tenent error should prompt in ui.

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8784]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![](https://vip1.loli.io/2022/03/09/N9EGpfjvzSMO6ms.png)

### What you expected to happen

above.

### How to reproduce

above.

### Anything else

above.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. We will deal with the prompt information about the interface in another question. I will close this question and link it to another question. Please check https://github.com/apache/dolphinscheduler/issues/8753.
