### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] email verification error in create new user.

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8789]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![](https://vip2.loli.io/2022/03/10/Mg3ZAG8Cn2WabS6.png)

### What you expected to happen

above.

### How to reproduce

above.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.

**Comment by songjianet** [comment]
Thank you for your feedback. For the user management module, we will rewrite, one is to ensure the consistency of the code style in the project as much as possible, and the other is to solve some corresponding bugs. So I'll close this question and link it to the question of overriding the user management module. Please check https://github.com/apache/dolphinscheduler/issues/8816.
