### ISSUE TITLE
[Bug] [Process Definition] Duplicate key TaskDefinition

### ISSUE THREAD

**Issue by CryptoColin** [apache/dolphinscheduler#8790]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I'm trying to save an process instance which was upgrade from before version(v2.0.1) and it reporting this error:
![Uploading Screen Shot 2022-03-10 at 10.41.08 AM.png…]()

### What you expected to happen

saved successfully

### How to reproduce

upgrade from v2.0.1 to v2.0.3,and try to modify process instance and save

### Version

2.0.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
Please see FAQ, that has a solution. 
https://dolphinscheduler.apache.org/en-us/docs/release/faq.html

**Comment by CryptoColin** [comment]
Hi Jiny,I tried to solve this problem by execute the SQL on database which you gave above,but the error still exist

**Comment by brave-lee** [comment]
Hi @SbloodyS , can you take a look of this issue?

**Comment by CryptoColin** [comment]
and this is the full error info:
`Duplicate key TaskDefinition{id=0, code=4720070430336, name='execute_tidb', version=1, description='', projectCode=0, userId=0, taskType=PYTHON, taskParams='{"resourceList":[{"id":7},{"id":9},{"id":19},{"id":13},{"id":21},{"id":12},{"id":22},{"id":60},{"id":72},{"id":71},{"id":77},{"id":81}],"localParams":[],"rawScript":"from utils import postgres_functions, mysql_functions, aws_functions, avro_functions, slack_functions\nimport os\n\nhostname = os.environ[\"HOSTNAME\"]\nserver = hostname.split(\"-\")[2]\n\nif server == \"staging\":\n secret_name = \"dtsta/eks/dolphinscheduler/app-credentials\"\n\nelif server == \"dev\":\n secret_name = \"dtdev/eks/dolphinscheduler/app-credentials\"\n\nelif server == \"production\":\n secret_name = \"dtpro/eks/dolphinscheduler/app-credentials\"\n\nregion_name = \"ap-southeast-1\"\naws_secrets = aws_functions.get_secrets(secret_name, region_name)\n\n# tidb connection\ntidb_host = aws_secrets[\"TIDB_BEHAVIOR_HOST\"]\ntidb_port = int(aws_secrets[\"TIDB_BEHAVIOR_PORT\"])\ntidb_user = aws_secrets[\"TIDB_BEHAVIOR_USERNAME\"]\ntidb_password = aws_secrets[\"TIDB_BEHAVIOR_PASSWORD\"]\ntidb_database = aws_secrets[\"TIDB_REPORTING_DATABASE\"]\ntidb_conn = mysql_functions.create_mysql_connection(tidb_host, tidb_port, tidb_user, tidb_password, tidb_database)\n\nsql = \"\"\"\nCREATE TABLE IF NOT EXISTS datawarehouse_reporting.dwd_crypto_fiat_payment_views_bcb_multiple_disbursement_cur\n(\n vendor_transaction_id varchar(255) not null\n\t\tprimary key,\n status varchar(255) ,\n created_at timestamp(6) NOT NULL,\n currency varchar(255) ,\n amount numeric(28,6),\n reference text NOT NULL,\n account_id text NOT NULL,\n beneficiary_id text NOT NULL,\n multiple_disbursement_found boolean,\n slack_posted_indicator integer,\n remarks text\n)\n;\n\"\"\"\n\nresults = mysql_functions.execute_mysql_sql(tidb_conn, sql)\nprint(results)","dependence":{},"conditionResult":{"successNode":[],"failedNode":[]},"waitStartTimeout":{},"switchResult":{}}', taskParamList=null, taskParamMap=null, flag=YES, taskPriority=MEDIUM, userName='null', projectName='null', workerGroup='default', failRetryTimes=1, environmentCode='-1', failRetryInterval=1, timeoutFlag=CLOSE, timeoutNotifyStrategy=WARN, timeout=0, delayTime=0, resourceIds='null', createTime=null, updateTime=null}`
and what I have looked up in my database from table t_ds_task_definition_log:
<img width="1229" alt="Screen Shot 2022-03-10 at 8 22 00 PM" src="https://user-images.githubusercontent.com/89381700/157660821-e4c76ef4-e372-44b0-8a6b-a511aee961e9.png">

it seems  have reset the version of my task to 1

**Comment by SbloodyS** [comment]
@CryptoColin Hi, can you provide a sample data of ```t_ds_task_definition_log``` and ```t_ds_process_task_relation_log```?  These two SQL can solve this problem in my 2.0.2-release to 2.0.3-release environment.

**Comment by CryptoColin** [comment]
sure，`t_ds_task_definition_log`:
```
id|code|name|version|description|project_code|user_id|task_type|task_params|flag|task_priority|worker_group|environment_code|fail_retry_times|fail_retry_interval|timeout_flag|timeout_notify_strategy|timeout|delay_time|resource_ids|operator|operate_time|create_time|update_time
1,340|4,720,070,430,336|execute_tidb|1||4,266,889,486,116|1|PYTHON|{"resourceList":[{"id":7},{"id":9},{"id":19},{"id":13},{"id":21},{"id":12},{"id":22},{"id":60},{"id":72},{"id":71},{"id":77},{"id":81}],"localParams":[],"rawScript":"from utils import postgres_functions, mysql_functions, aws_functions, avro_functions, slack_functions\nimport os\n\nhostname = os.environ[\"HOSTNAME\"]\nserver = hostname.split(\"-\")[2]\n\nif server == \"staging\":\n  secret_name = \"dtsta/eks/dolphinscheduler/app-credentials\"\n\nelif server == \"dev\":\n  secret_name = \"dtdev/eks/dolphinscheduler/app-credentials\"\n\nelif server == \"production\":\n  secret_name = \"dtpro/eks/dolphinscheduler/app-credentials\"\n\nregion_name = \"ap-southeast-1\"\naws_secrets = aws_functions.get_secrets(secret_name, region_name)\n\n# tidb connection\ntidb_host = aws_secrets[\"TIDB_BEHAVIOR_HOST\"]\ntidb_port = int(aws_secrets[\"TIDB_BEHAVIOR_PORT\"])\ntidb_user = aws_secrets[\"TIDB_BEHAVIOR_USERNAME\"]\ntidb_password = aws_secrets[\"TIDB_BEHAVIOR_PASSWORD\t\"]\ntidb_database = aws_secrets[\"TIDB_REPORTING_DATABASE\"]\ntidb_conn = mysql_functions.create_mysql_connection(tidb_host, tidb_port, tidb_user, tidb_password, tidb_database)\n\nsql = \"\"\"\nCREATE TABLE IF NOT EXISTS datawarehouse_reporting.dwd_crypto_fiat_payment_views_bcb_multiple_disbursement_cur\n(\n    vendor_transaction_id text not null\n\t\tprimary key,\n    status text ,\n    created_at timestamp(6) NOT NULL,\n    currency text ,\n    amount numeric(28,6),\n    reference text NOT NULL,\n    account_id text NOT NULL,\n    beneficiary_id text NOT NULL,\n    multiple_disbursement_found boolean,\n    slack_posted_indicator integer,\n    remarks text\n)\n;\n\"\"\"\n\nresults = mysql_functions.execute_mysql_sql(tidb_conn, sql)\nprint(results)","dependence":{},"conditionResult":{"successNode":[],"failedNode":[]},"waitStartTimeout":{},"switchResult":{}}|1|2|default|-1|0|1|0|[NULL]|0|0|81,19,21,22,7,71,72,9,12,60,13,77|1|2022-03-03 11:12:51.265|2022-03-03 11:12:51.265|2022-03-03 11:12:51.265
```
`t_ds_process_task_relation_log`:
```
id|name|project_code|process_definition_code|process_definition_version|pre_task_code|pre_task_version|post_task_code|post_task_version|condition_type|condition_params|operator|operate_time|create_time|update_time
1|[NULL]|4,266,889,486,112|4,266,889,492,900|1|0|0|4,266,889,601,568|1|0|{}|1|2022-01-21 00:00:00.000|2022-01-21 00:00:00.000|2022-01-21 00:00:00.000
```

**Comment by SbloodyS** [comment]
> and this is the full error info: `Duplicate key TaskDefinition{id=0, code=4720070430336, name='execute_tidb', version=1, description='', projectCode=0, userId=0, taskType=PYTHON, taskParams='{"resourceList":[{"id":7},{"id":9},{"id":19},{"id":13},{"id":21},{"id":12},{"id":22},{"id":60},{"id":72},{"id":71},{"id":77},{"id":81}],"localParams":[],"rawScript":"from utils import postgres_functions, mysql_functions, aws_functions, avro_functions, slack_functions\nimport os\n\nhostname = os.environ[\"HOSTNAME\"]\nserver = hostname.split(\"-\")[2]\n\nif server == \"staging\":\n secret_name = \"dtsta/eks/dolphinscheduler/app-credentials\"\n\nelif server == \"dev\":\n secret_name = \"dtdev/eks/dolphinscheduler/app-credentials\"\n\nelif server == \"production\":\n secret_name = \"dtpro/eks/dolphinscheduler/app-credentials\"\n\nregion_name = \"ap-southeast-1\"\naws_secrets = aws_functions.get_secrets(secret_name, region_name)\n\n# tidb connection\ntidb_host = aws_secrets[\"TIDB_BEHAVIOR_HOST\"]\ntidb_port = int(aws_secrets[\"TIDB_BEHAVIOR_PORT\"])\ntidb_user = aws_secrets[\"TIDB_BEHAVIOR_USERNAME\"]\ntidb_password = aws_secrets[\"TIDB_BEHAVIOR_PASSWORD\"]\ntidb_database = aws_secrets[\"TIDB_REPORTING_DATABASE\"]\ntidb_conn = mysql_functions.create_mysql_connection(tidb_host, tidb_port, tidb_user, tidb_password, tidb_database)\n\nsql = \"\"\"\nCREATE TABLE IF NOT EXISTS datawarehouse_reporting.dwd_crypto_fiat_payment_views_bcb_multiple_disbursement_cur\n(\n vendor_transaction_id varchar(255) not null\n\t\tprimary key,\n status varchar(255) ,\n created_at timestamp(6) NOT NULL,\n currency varchar(255) ,\n amount numeric(28,6),\n reference text NOT NULL,\n account_id text NOT NULL,\n beneficiary_id text NOT NULL,\n multiple_disbursement_found boolean,\n slack_posted_indicator integer,\n remarks text\n)\n;\n\"\"\"\n\nresults = mysql_functions.execute_mysql_sql(tidb_conn, sql)\nprint(results)","dependence":{},"conditionResult":{"successNode":[],"failedNode":[]},"waitStartTimeout":{},"switchResult":{}}', taskParamList=null, taskParamMap=null, flag=YES, taskPriority=MEDIUM, userName='null', projectName='null', workerGroup='default', failRetryTimes=1, environmentCode='-1', failRetryInterval=1, timeoutFlag=CLOSE, timeoutNotifyStrategy=WARN, timeout=0, delayTime=0, resourceIds='null', createTime=null, updateTime=null}` and what I have looked up in my database from table t_ds_task_definition_log: <img alt="Screen Shot 2022-03-10 at 8 22 00 PM" width="1229" src="https://user-images.githubusercontent.com/89381700/157660821-e4c76ef4-e372-44b0-8a6b-a511aee961e9.png">
> 
> it seems have reset the version of my task to 1

From the screenshot you provided. It seems there is no duplicate data in the ```t_ds_task_definition_log``` table. Can you check whether there is any duplicate data based on the following SQL.

```
SELECT
    a.process_definition_code
    ,MAX(a.id) as max_id
    ,a.pre_task_code
    ,a.pre_task_version
    ,a.post_task_code
    ,a.post_task_version
    ,a.process_definition_version
    ,COUNT(*) cnt
FROM
t_ds_process_task_relation_log a
JOIN (
    SELECT
        code
    FROM
        t_ds_process_definition
    GROUP BY code
)b ON b.code = a.process_definition_code
WHERE 1=1
GROUP BY a.pre_task_code
    ,a.post_task_code
    ,a.pre_task_version
    ,a.post_task_version
    ,a.process_definition_code
    ,a.process_definition_version
```

**Comment by CryptoColin** [comment]
just checked with this SQL and order by cnt desc, seems there have no duplicate data,but the error still exist:
<img width="1413" alt="Screen Shot 2022-03-10 at 10 20 10 PM" src="https://user-images.githubusercontent.com/89381700/157681305-9f44f0ca-ee62-4ef9-b033-a5411d681d96.png">

it's very stranger

**Comment by SbloodyS** [comment]
Sorry for my mistake. I forgot there was another SQL need to be execute. Can you please execute the following SQL to check again? @CryptoColin 
```
                   SELECT
                       code
                        ,name
                        ,version
                        ,MAX(id) AS max_id
                   FROM
                       t_ds_task_definition_log
                   GROUP BY code
                          ,name
                          ,version
                   HAVING COUNT(*) > 1
```

**Comment by CryptoColin** [comment]
sure ,no result:
<img width="1436" alt="Screen Shot 2022-03-10 at 10 32 22 PM" src="https://user-images.githubusercontent.com/89381700/157683515-5b4550a3-1baf-4d34-b2d0-71aaccfd8978.png">

**Comment by SbloodyS** [comment]
@CryptoColin It seems a different issue from #8296. Is there any error logs in ```logs/dolphinscheduler-api.log```?

**Comment by CryptoColin** [comment]
nope,just checked,no error logs in `logs/dolphinscheduler-api.log`
<img width="1525" alt="Screen Shot 2022-03-10 at 10 40 42 PM" src="https://user-images.githubusercontent.com/89381700/157685137-9817640b-d8a1-4a5b-96be-87d1e0f8ef06.png">

**Comment by SbloodyS** [comment]
> nope,just checked,no error logs in `logs/dolphinscheduler-api.log`

The error log will be cut every hours. You can try to operate the page first, and then check whether there is an error log after the error message appears in ui.

**Comment by CryptoColin** [comment]
yes，I'm taking a screenshot after operating and reproduce the error

**Comment by weeway** [comment]
I had the same problem in version 2.0.5 and reproduced it by following steps.
1. create a new process and create the first task in it, then save the process (will back to process list)
2. click into the process and create the second task, then save then process (do not click close)
3. create the third task, then save then process and click close
4. click into the process and save, the error occurs

in step 3, the process DAG looks like this:
<img width="2305" alt="image" src="https://user-images.githubusercontent.com/12637868/158401170-74fc7401-c38b-4503-9b6a-3b905758a741.png">

and the t_ds_task_definition looks like this:
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/12637868/158401503-a75074a7-b320-4db0-afc1-6936fbe6d697.png">

in t_ds_task_definition table, there are two tasks with then same code '4854144904256' and same version '1'. That seems  
to be the reason causing duplicate

**Comment by lordk911** [comment]
2.0.5 also have the same problem

**Comment by lordk911** [comment]
![image](https://user-images.githubusercontent.com/19989300/158783229-829a8af9-4b97-4309-8ec2-ad4490d162e5.png)

the error is throw on the breakpoint line @SbloodyS  @caishunfeng , and the process define in dolphin 2.0.0 or before ,edit in 2.0.5 , add a new task in the process and save, the error will throw.

also a process define in 2.0.5 with multiple task , edit and change task content  multiple time will also throw this error

Why all task version infomation will pass to here ? but code is map key.

![image](https://user-images.githubusercontent.com/19989300/158797803-d965b910-c12e-479c-8b26-ede6385e9f11.png)

**Comment by SbloodyS** [comment]
![](https://vip1.loli.io/2022/03/17/v7xmVAXJtTQ3ika.png)

Hi @lordk911 @weeway , I just clone the latest ```2.0.5-release``` from ```https://github.com/apache/dolphinscheduler``` and build it. And I tried it according to the steps you described. I couldn't reproduce this problem in chrome 99.0.4844.51. Which browser you are using? Or is there any other operation or configuration missing?

**Comment by caishunfeng** [comment]
> I had the same problem in version 2.0.5 and reproduced it by following steps.
> 
> 1. create a new process and create the first task in it, then save the process (will back to process list)
> 2. click into the process and create the second task, then save then process (do not click close)
> 3. create the third task, then save then process and click close
> 4. click into the process and save, the error occurs

![Uploading f37b6a0e73c5c145f3323678c48b581.png…]()

I found that the request param was duplicate task, @songjianet can you take a look?

**Comment by lordk911** [comment]
table ：
t_ds_task_definition_log
t_ds_task_definition

why not use id as PRIMARY KEY and code + version as unique index.

```
ALTER TABLE
    `dolphinscheduler`.`t_ds_task_definition` ADD CONSTRAINT uidx_tdef_cv UNIQUE (`code`,
    `version`)
```

@caishunfeng

**Comment by caishunfeng** [comment]
I found the reason is that:

1. when add a new task A, click save and not close, at this time task-A version is 1 at backend, but empty version in UI.
2. and click save again, at this time the backend will create a new task-definition-log with version 1 again because empty version, so the version 1 task-A were duplicate.

I had submit a pr to fix this issue, and I think the UI should refresh the data after save to keep data consistency.  PTAL @songjianet

**Comment by lordk911** [comment]
there is another scenario : 
one process with one task，the task have 4 versions. so the table t_ds_process_task_relation_log will have 4 record, 
 wich is : 
![企业微信截图_5101b10a-9c05-4b49-a565-b18f3317fa32](https://user-images.githubusercontent.com/19989300/158942198-ad91117a-3fe2-4783-b6ee-b0a88572b132.png)

and  table t_ds_process_task_relation has one record : 

![image](https://user-images.githubusercontent.com/19989300/158942312-428a0888-da8d-4bcd-a541-42c8cc6ea3b5.png)


in version 2.0.0 edit this process is ok, because ProcessService.genDagData method read from t_ds_process_task_relation , but in 2.0.5 ProcessService.genDagData read from t_ds_process_task_relation_log , so when to save the process there well be 4 record pass to ProcessService.transformTask method, which will cause Duplicate key error. @caishunfeng

**Comment by caishunfeng** [comment]
> there is another scenario : one process with one task，the task have 4 versions. so the table t_ds_process_task_relation_log will have 4 record, wich is : ![企业微信截图_5101b10a-9c05-4b49-a565-b18f3317fa32](https://user-images.githubusercontent.com/19989300/158942198-ad91117a-3fe2-4783-b6ee-b0a88572b132.png)
> 
> and table t_ds_process_task_relation has one record :
> 
> ![image](https://user-images.githubusercontent.com/19989300/158942312-428a0888-da8d-4bcd-a541-42c8cc6ea3b5.png)
> 
> in version 2.0.0 edit this process is ok, because ProcessService.genDagData method read from t_ds_process_task_relation , but in 2.0.5 ProcessService.genDagData read from t_ds_process_task_relation_log , so when to save the process there well be 4 record pass to ProcessService.transformTask method, which will cause Duplicate key error. @caishunfeng

I can't reproduce this duplicate key error on the bugfix pr.

**Comment by lordk911** [comment]
> > there is another scenario : one process with one task，the task have 4 versions. so the table t_ds_process_task_relation_log will have 4 record, wich is : ![企业微信截图_5101b10a-9c05-4b49-a565-b18f3317fa32](https://user-images.githubusercontent.com/19989300/158942198-ad91117a-3fe2-4783-b6ee-b0a88572b132.png)
> > and table t_ds_process_task_relation has one record :
> > ![image](https://user-images.githubusercontent.com/19989300/158942312-428a0888-da8d-4bcd-a541-42c8cc6ea3b5.png)
> > in version 2.0.0 edit this process is ok, because ProcessService.genDagData method read from t_ds_process_task_relation , but in 2.0.5 ProcessService.genDagData read from t_ds_process_task_relation_log , so when to save the process there well be 4 record pass to ProcessService.transformTask method, which will cause Duplicate key error. @caishunfeng
> 
> I can't reproduce this duplicate key error on the bugfix pr.

what I say is that : there is already some data in database as what I show, if I was a user of dolphin 2.0.0 , after I upgrage to 2.0.5 , as this scenario. the process could not be edited. because when I go into the process edit page , the data send to web ui is diffrent between 2.0.0 and 2.0.5 , they read diffrent metabase table, 2.0.5 will throw  Duplicate key error when going to ProcessService.transformTask method as line 2516, because 2.0.5 will send all versions of task_define infomation to web and then pass to api-server when click 'save'

**Comment by caishunfeng** [comment]
> what I say is that : there is already some data in database as what I show, if I was a user of dolphin 2.0.0 , after I upgrage to 2.0.5 , as this scenario. the process could not be edited. because when I go into the process edit page , the data send to web ui is diffrent between 2.0.0 and 2.0.5 , they read diffrent metabase table, 2.0.5 will throw Duplicate key error when going to ProcessService.transformTask method as line 2516, because 2.0.5 will send all versions of task_define infomation to web and then pass to api-server when click 'save'

The upgrade problem you can see https://dolphinscheduler.apache.org/zh-cn/docs/release/faq.html   Q：Update process definition error: Duplicate key TaskDefinition，hope it helps you.

**Comment by lordk911** [comment]
> The upgrade problem you can see https://dolphinscheduler.apache.org/zh-cn/docs/release/faq.html Q：Update process definition error: Duplicate key TaskDefinition，hope it helps you.

OK, thanks
I've try it . nothing delete from my database, so problem still not resolve.

**Comment by lordk911** [comment]
![企业微信截图_ea39ffd3-3db2-4913-9873-b435ed94f67d](https://user-images.githubusercontent.com/19989300/158978028-1809a8ba-18ed-4a3d-a6dd-311897541fa9.png)

data in table t_ds_process_task_relation_log, is this normal that 'post_task_version'  have changed but 'process_definition_version' not change?

**Comment by SbloodyS** [comment]
> ![企业微信截图_ea39ffd3-3db2-4913-9873-b435ed94f67d](https://user-images.githubusercontent.com/19989300/158978028-1809a8ba-18ed-4a3d-a6dd-311897541fa9.png)
> 
> data in table t_ds_process_task_relation_log, is this normal that 'post_task_version' have changed but 'process_definition_version' not change?

Can you check whether the ```update_time``` of table ```t_ds_process_task_relation_log ``` data is before or after the upgrade?

**Comment by lordk911** [comment]
> Can you check whether the `update_time` of table `t_ds_process_task_relation_log ` data is before or after the upgrade?

![企业微信截图_998a0564-5dc4-41c4-853e-02009c8d0c66](https://user-images.githubusercontent.com/19989300/158981121-58b1b23d-d427-4ed5-9e72-18512265855d.png)

**Comment by lordk911** [comment]
> data in table t_ds_process_task_relation_log, is this normal that 'post_task_version' have changed but 'process_definition_version' not change?

it's not normal. at least project_code + process_definition_code + process_definition_version + post_task_code + post_task_version should be unique. it's the data in my metabase , the data was generated in dolphinscheduler2.0.0

**Comment by SbloodyS** [comment]
> > data in table t_ds_process_task_relation_log, is this normal that 'post_task_version' have changed but 'process_definition_version' not change?
> 
> it's not normal. at least project_code + process_definition_code + process_definition_version + post_task_code + post_task_version should be unique. it's the data in my metabase , the data was generated in dolphinscheduler2.0.0

At present, this problem can be solved by deleting duplicated data. Due to the particularity of version 2.0.0. I can not provide specific repair SQL. You can refer to the SQL logic in the ```FAQ``` to write a new SQL for data deletion.

**Comment by lordk911** [comment]
dolphinscheduler 引入工作流版本控制后，出现工作流无法保存的问题修复：

异常信息：
Duplicate key TaskDefinition{id=0, code=3755309816211, name='zjcz_stage2', version=3, description='', projectCode=0, userId=0, taskType=DEPENDENT, 
taskParams='{"dependence":{"relation":"AND","dependTaskList":[{"relation":"AND","dependItemList":[{"projectCode":3755309710848,"definitionCode":3755309717380,"depTaskCode":0,"cycle":"day","dateValue":"today"}]}]},"conditionResult":{"successNode":[],"failedNode":[]},"waitStartTimeout":{"strategy":"FAILED","interval":null,"checkInterval":null,"enable":false},"switchResult":{}}', 
taskParamList=null, taskParamMap=null, flag=YES, taskPriority=MEDIUM, userName='null', projectName='null', workerGroup='default', failRetryTimes=0, environmentCode='-1', failRetryInterval=1, timeoutFlag=CLOSE, timeoutNotifyStrategy=WARN, timeout=0, delayTime=0, resourceIds='null', createTime=null, updateTime=null}


当时页面的URL：
http://a.b.c.d:12345/dolphinscheduler/ui/#/projects/3755309710848/definition/list/3755309717382

以上信息说明：
在保存项目3755309710848，工作流 3755309717382 时发生了主键冲突异常，注意该主键异常并非数据库主键，具体发生重复的任务是 3755309816211,版本号是3.
解决这个问题，到表t_ds_process_task_relation中查看一下当前工作流（3755309717382）的版本 以及所关联的任务（3755309816211）的版本，应该不是3，
然后到表 t_ds_process_task_relation_log 中查询一下 当前工作流（3755309717382），当前版本 ，所关联的任务（3755309816211）的信息，把版本不是3的删掉即可。

**Comment by liyanj** [comment]
1. Get the latest version of process_definition, as below:
SELECT version FROM t_ds_process_definition WHERE code = '9031660390016';

2. Get the latest version of task_definition, as below:
SELECT version FROM t_ds_task_definition WHERE code = '9031645384064';

3. The problem is that there are multiple relations in table(t_ds_process_task_relation), as below:
SELECT * FROM t_ds_process_task_relation WHERE process_definition_code = '9031660390016' AND post_task_code = '9031645384064'

4. The SOLUTION is:
4.1 In table(t_ds_process_task_relation), Find the record with both the latest process_definition_version(MAX process_definition_version) and the latest post_task_version(MAX post_task_version), 
and retain this record. Then, delete all of other relation records about this process_definition and task_definition.

 4.2 In table(t_ds_process_task_relation_log), retain records with the latest post_task_version(MAX post_task_version),
and delete all of other relation records about this process_definition and task_definition.

5. DONE.
