### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha]Set parameters before timing Next five execution times is null

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8796]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Set parameters before timing Next five execution times is null

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/76080484/157583258-743b0fb1-fadd-487d-a1b1-9438069195b7.png">

### What you expected to happen

The next five running times can be displayed to verify the correctness of the Settings

### How to reproduce

Workflow on-line, click Set timing operation, set running rules

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
I have checked this issue, the problem is no environment data in table t_ds_environment. I have copied one row data from 2.0.3database to dev env, please check again the array of the interface. Thanks!

**Comment by Tianqi-Dotes** [comment]
Currently is okay, need to try the in newest version.
