### ISSUE TITLE
[Bug-FE] [UI Next][V1.0.0-Alpha] The Workflow Relation page cannot be zoomed in or out using a scroll wheel

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8802]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The Workflow Relation page cannot be zoomed in or out using a scroll wheel

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/76080484/157601202-a42caa98-ef3b-4180-8ea4-6cb644dcbe3b.png">

### What you expected to happen

The Workflow Relation page is zoomed in or out by scrolling on a scroll wheel

### How to reproduce

The Workflow Relation page cannot be zoomed in or out using a scroll wheel

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.
