### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha]Clicking Task Definition returns an error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8804]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Clicking Task Definition returns an error

Error message:query task definition versions error

<img width="1912" alt="image" src="https://user-images.githubusercontent.com/76080484/157602036-8dd1476f-65b9-40e2-b159-77a3a9902117.png">

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/76080484/157602114-24fa54cc-52c0-4161-a69a-442f1bb44aed.png">

### What you expected to happen

Click on Task Definition to display normally

### How to reproduce

Clicking Task Definition returns an error

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
Have checked this issue, and have given the details to @songjianet bro to check if have time.

**Comment by Tianqi-Dotes** [comment]
I have checked this issue in my local env, it's fine, the Task Definition page doesn't call the version API. I guess the problem is the frontend version. I suggest updating the frontend with the dev branch and will be fine.

**Comment by Tianqi-Dotes** [comment]
Currently is okay, need to try the in newest version.
