### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] Repeat workflow import, the last import file was not cleared

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8806]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Repeat workflow import, the last import file was not cleared

<img width="1914" alt="image" src="https://user-images.githubusercontent.com/76080484/157603260-5f082bec-19ad-4745-be65-19a42e4d1552.png">

### What you expected to happen

The file check box can be cleared when repeating workflow imports

### How to reproduce

1. Click Import Workflow
2. Select the workflow to be imported
3. Click Import
4. Click Import workflow again

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
