### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha]Uniqueness verification is performed when projects and workflows are created in batches

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8807]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Projectcode and taskCode are not verified when projects and workflows are created in batches. As a result, errors are reported in subsequent operations

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/76080484/157608498-587cfa36-e185-4c99-80f7-feba9aba3843.png">

### What you expected to happen

The backend verifies the uniqueness of fields that must be unique to the new instance

### How to reproduce

Projectcode and taskCode are not verified when projects and workflows are created in batches. As a result, errors are reported in subsequent operations

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
Why do locations have the same taskcode, we need to understand what is taskcode. It is generated when you create a new task node inside the workflow definition, so when you submitting the same form data with the same task object, the result will have the same task code.

**Comment by Tianqi-Dotes** [comment]
The problem is different workflow use same task object.
