### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]Task instance logs are not automatically updated

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8808]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Task instance logs are not automatically updated

<img width="1917" alt="image" src="https://user-images.githubusercontent.com/76080484/157622048-000faeae-86d3-469c-98fd-d3ae26f4aa9c.png">

### What you expected to happen

Task instance logs can be updated automatically

### How to reproduce

1. Execute a long workflow
2. View task instance logs
3. The log is not updated. You need to close the log window and open it again to update the latest log

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it

**Comment by songjianet** [comment]
> I will fix it

I'll deal with this issue here.
