### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] DATA_QUALITY icon is null

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8809]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

DATA_QUALITY icon is null

<img width="1902" alt="image" src="https://user-images.githubusercontent.com/76080484/157627147-8fab0a8a-8854-42b1-97f5-71ad7bdd3132.png">

### What you expected to happen

DATA_QUALITY icon According to the normal

### How to reproduce

Click Create Workflow

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.
