### ISSUE TITLE
[Feature][dolphinscheduler-api] Return domain object after creating success

### ISSUE THREAD

**Issue by ouyangyewei429** [apache/dolphinscheduler#8817]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Third-party integration scenarios often need to maintain the relationship between the product business and DolphinScheduler’s Alert, AlertPluginInstance.

In the current CreateXxx API, only the status code is returned, even if the creation is successful, the entity object will not be returned.

Therefore, if you need to obtain The created object information, such as AlertGroupId and AlertPluginInstanceId, it requires multiple API calls (first call the CreateXxx API first, then call the QueryXxx), and if the entity object can be returned in the CreateXxx API, the times of API calls can be reduced.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by seedscoder** [comment]
I want to achieve it

**Comment by ouyangyewei429** [comment]
> I want to achieve it

@seedscoder Sure, practice it 👍

**Comment by seedscoder** [comment]
> er Sure, practice it 👍

@ouyangyewei 
Hey, it can be seen from the above that you have started to do it. Do you need me to see the rest

**Comment by caishunfeng** [comment]
PR was merged.
