### ISSUE TITLE
Project dolphinscheduler-python: Command execution failed (there is a problem in the local compilation and packaging process of the source package)

### ISSUE THREAD

**Issue by berg-xu** [apache/dolphinscheduler#8820]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

ds-2.0.5下载源码包尝试本地编译打包过程中，出现如下错误：

 **Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (python-api-prepare) on project dolphinscheduler-python: Command execution failed. Process exited with an error: 9009 (Exit value: 9009) -> [Help 1]**
具体如下图所示：
![image](https://user-images.githubusercontent.com/45385723/157663473-80b4c02f-a6fe-4504-b41f-e41966fd96ee.png)

我这边浏览了下Issue上的其它类似问题，我尝试更新到2.0.5版本或者参照其它类似问题的解决方法，都没有解决我的问题。请问接下来该如何操作？

### What you expected to happen

ds-2.0.5下载源码包尝试本地编译打包过程中，出现如下错误：

 **Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (python-api-prepare) on project dolphinscheduler-python: Command execution failed. Process exited with an error: 9009 (Exit value: 9009) -> [Help 1]**
具体如下图所示：
![image](https://user-images.githubusercontent.com/45385723/157663473-80b4c02f-a6fe-4504-b41f-e41966fd96ee.png)

我这边浏览了下Issue上的其它类似问题，我尝试更新到2.0.5版本或者参照其它类似问题的解决方法，都没有解决我的问题。请问接下来该如何操作？

### How to reproduce

ds-2.0.5下载源码包尝试本地编译打包

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by berg-xu** [comment]
追加信息如下图：
![image](https://user-images.githubusercontent.com/45385723/157790396-63f4df5a-09d3-4023-ae70-1ea7d3c3b7ac.png)

**Comment by kezhenxu94** [comment]
@berg-xu looks like you don't have python installed? FYI @zhongjiajie

**Comment by berg-xu** [comment]
@kezhenxu94  感谢您的回答。 请在指导一下，能否具体描述python方面环境的要求， 因为我这边已经确认了本地windows电脑安装了python3.7。 IDEA中是否需要支持安装python等环境插件？ 或者说还需要做其它哪些操作？

**Comment by JustDoItGit** [comment]
you can edit the pom.xml in dolphinscheduler-python folder.
add version 3.0.0 to the exec-maven-plugin 
```pom
<groupId>org.codehaus.mojo</groupId>
<artifactId>exec-maven-plugin</artifactId>
<version>3.0.0</version>
```
**`<version>3.0.0</version>`**

**Comment by zhongjiajie** [comment]
@berg-xu you should not install python plugin for idea. Does command `python3` work  in your terminal or not?

**Comment by cfh627** [comment]
same problem

**Comment by zhongjiajie** [comment]
Hi @berg-xu and @cfh627, after https://github.com/apache/dolphinscheduler/pull/8999 is be merged, python dist package is in `python` profile and when you run the command `mvn clean install -Prelease` will not build python dist package. Also do not need python development in your environment.

And it will release in 3.0.0-alpha, but in 2.0.5 you could fix it by add python 3.6(or above) to fix this error during your build process

**Comment by wujb315** [comment]
@berg-xu，请问你的问题解决了吗？我也是这个问题，有解决，麻烦告知一下解决方案，谢谢

**Comment by zhongjiajie** [comment]
> @berg-xu，请问你的问题解决了吗？我也是这个问题，有解决，麻烦告知一下解决方案，谢谢

@wujb315  if you using versions between 2.0.3 and 2.0.5, you should make sure to have `python3` executable in your env (type it in the bash to check it). And then run `mvn clean install` or other commands

**Comment by wujb315** [comment]
@zhongjiajie 我已经安装过了，但是依然错误
![image](https://user-images.githubusercontent.com/33825563/165050312-f4f67548-721f-4a60-8c62-be03b932ce2a.png)

**Comment by wujb315** [comment]
@zhongjiajie 我已经确认创建了python3的环境，python是3.6的版本，但是还是一样的问题，请教一下，我现在该怎么解决，实在搞不明白

**Comment by wujb315** [comment]
@zhongjiajie 我已经解决了

**Comment by berg-xu** [comment]
@wujb315  你这边是用的哪个版本？ 如何解决这个问题的?

**Comment by zhongjiajie** [comment]
@berg-xu see https://github.com/apache/dolphinscheduler/issues/8820#issuecomment-1064952664 to solve it

**Comment by Zokerman** [comment]
@wujb315 求解，如何解决这个问题的
