### ISSUE TITLE
[Bug]worker-runnig instance cant create execLocalPath

### ISSUE THREAD

**Issue by lucas666666** [apache/dolphinscheduler#8829]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

the cluster is Pseudo-Cluster ，when i create a shell job, then running the job , it produce a instance ,the instance in worker err log is "[ERROR] 2022-03-11 09:17:07.721 org.apache.dolphinscheduler.server.worker.processor.TaskExecuteProcessor:[151] - create execLocalPath: /tmp/dolphinscheduler/exec/process/4797859136768/4803964634368_2/2/4
java.io.IOException: Unable to create directory /tmp/dolphinscheduler/exec/process/4797859136768/4803964634368_2/2/4
        at org.apache.commons.io.FileUtils.forceMkdir(FileUtils.java:2384)
        at org.apache.dolphinscheduler.common.utils.FileUtils.createWorkDirIfAbsent(FileUtils.java:119)
        at org.apache.dolphinscheduler.server.worker.processor.TaskExecuteProcessor.process(TaskExecuteProcessor.java:146)
        at org.apache.dolphinscheduler.remote.handler.NettyServerHandler.lambda$processReceived$0(NettyServerHandler.java:129)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[INFO] 2022-03-11 09:17:07.722 org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread:[129] - script path : /tmp/dolphinscheduler/exec/process/4797859136768/4803964634368_2/2/4
[INFO] 2022-03-11 09:17:07.723 org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread:[145] - the task begins to execute. task instance id: 4[INFO] 2022-03-11 09:17:07.735 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[83] - shell task params {"resourceList":[],"localParams":[],"rawScript":"sh /home/bigdataadmin/alidatafee/alidatafee_detail/alibabacloud_sample/alicloudfee.sh","dependence":{},"conditionResult":{"successNode":[],"failedNode":[]},"waitStartTimeout":{},"switchResult":{}}
[INFO] 2022-03-11 09:17:07.756 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[137] - raw script : sh /home/bigdataadmin/alidatafee/alidatafee_detail/alibabacloud_sample/alicloudfee.sh
[INFO] 2022-03-11 09:17:07.756 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[138] - task execute path : /tmp/dolphinscheduler/exec/process/4797859136768/4803964634368_2/2/4
[ERROR] 2022-03-11 09:17:07.757 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[103] - shell task error
java.nio.file.NoSuchFileException: /tmp/dolphinscheduler/exec/process/4797859136768/4803964634368_2/2/4/2_4_node.sh
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)

"

### What you expected to happen

the instance is normal  

### How to reproduce

he cluster is Pseudo-Cluster ，when i create a shell job, then running the job , it produce a instance ,the instance in worker is failure

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
Please log in to the tenant that executes the job to verify create directory /tmp/dolphinscheduler/exec/process/4797859136768/4803964634368_2/2/4

**Comment by lucas666666** [comment]
Ok, in the sever ,i builded standalone ,after i  build Pseudo-Cluster , so the /tmp/dolphinscheduler/exec/process/4797859136768/4803964634368_2/2/4 owner is root, so i change the directory owner to dolphinscheduler。

but task erro log is Bellow, i can't undstand tenant cant execute the shell .

log: ''
[INFO] 2022-03-11 12:09:47.915 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[287] - task run command: sudo -u bigdataadmin sh /tmp/dolphinscheduler/exec/process/4797859136768/4803964634368_2/3/6/3_6.command
[INFO] 2022-03-11 12:09:47.917 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[178] - process start, process id is: 7740
[INFO] 2022-03-11 12:09:47.934 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[202] - process has exited, execute path:/tmp/dolphinscheduler/exec/process/4797859136768/4803964634368_2/3/6, processId:7740 ,exitStatusCode:1 ,processWaitForStatus:true ,processExitValue:1
[INFO] 2022-03-11 12:09:48.917 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[66] -  -> welcome to use bigdata scheduling system...
/tmp/dolphinscheduler/exec/process/4797859136768/4803964634368_2/3/6/3_6.command: line 4: /home/dolphinscheduler/dolphinscheduler/conf/env/dolphinscheduler_env.sh: Permission denied
[INFO] 2022-03-11 12:09:48.918 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[60] - FINALIZE_SESSION"
