### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]Language display error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8831]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Language display error

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/76080484/157797986-010601d9-55fe-48d9-aea0-ad1db096c8e5.png">

### What you expected to happen

Correct language presentation

### How to reproduce

1、Login
2、Switch Chinese
3、Click project management

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. I will fix it.

**Comment by XuXuClassMate** [comment]
At present, there are only 15 task status types in the old and new UI. The interface returns READY_BLOCK and BLOCK are not among the 15 task status types. Please help the back-end friends to confirm whether this is a bug or a new status. If it is a bug, then Just trouble the back-end partners to deal with it. If it is a new state, our front-end will support it accordingly.

![image](https://user-images.githubusercontent.com/76080484/157825840-b4cdc6f4-aaa7-4db3-93f5-5726593cb91b.png)


{"code":0,"msg":"成功","data":{"totalCount":7,"taskCountDtos":[{"count":0,"taskStateType":"SUBMITTED_SUCCESS"},{"count":0,"taskStateType":"RUNNING_EXECUTION"},{"count":0,"taskStateType":"READY_PAUSE"},{"count":0,"taskStateType":"PAUSE"},{"count":0,"taskStateType":"READY_STOP"},{"count":0,"taskStateType":"STOP"},{"count":7,"taskStateType":"FAILURE"},{"count":0,"taskStateType":"SUCCESS"},{"count":0,"taskStateType":"NEED_FAULT_TOLERANCE"},{"count":0,"taskStateType":"KILL"},{"count":0,"taskStateType":"WAITING_THREAD"},{"count":0,"taskStateType":"WAITING_DEPEND"},{"count":0,"taskStateType":"DELAY_EXECUTION"},{"count":0,"taskStateType":"SERIAL_WAIT"},{"count":0,"taskStateType":"READY_BLOCK"},{"count":0,"taskStateType":"BLOCK"}]},"failed":false,"success":true}
