### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]Predecessor node is empty, no data

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8832]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Predecessor node is empty, no data

<img width="1898" alt="image" src="https://user-images.githubusercontent.com/76080484/157819099-f6bfac90-5a77-40f3-a21e-2fe887a46786.png">

### What you expected to happen

You can get other newly completed nodes under this workflow

### How to reproduce

1、Create a workflow
2、Create a new component
3、Create a second component
The second component predecessor node is empty, can not get data

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
I have a try  at local, and found that the second component predecessor node is empty before save workflow, so I change the title and label of this issue. cc @songjianet @XuXuClassMate

**Comment by songjianet** [comment]
Please check https://github.com/apache/dolphinscheduler/issues/8869.
