### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] missing path in resources center

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8834]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 ![](https://vip1.loli.io/2022/03/11/JrcaFs6LVqyMgtH.png)

![](https://vip1.loli.io/2022/03/11/BvUyISKoxnYpRtm.png)

### What you expected to happen

above.

### How to reproduce

above.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will fix it.

**Comment by calvinjiang** [comment]
I'll deal with this issue.
