### ISSUE TITLE
[Bug(Serious)-FE][UI Next][V1.0.0-Alpha]Failed to save a workflow containing a child workflow node

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8835]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Failed to save a workflow containing a child workflow node

<img width="1900" alt="image" src="https://user-images.githubusercontent.com/76080484/157829805-2aa693cf-6096-4477-af83-b437477bc27a.png">

### What you expected to happen

Successfully saved and ready to run

### How to reproduce

1、First complete a new workflow
2、Create a new workflow that is being edited
3、Drag a sub-workflow component
4、Set the sub-workflow as the first new workflow completed
5、Click Save Workflow to report an error

The front end does not pass information about the child node to the back end

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will fix it.
