### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] create directory/file path wrong

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8836]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![](https://vip2.loli.io/2022/03/11/qdZsCHgkaFJrmY3.png)

### What you expected to happen

above.

### How to reproduce

create index folder ```test2``` in root path. And then entering the ```test2``` folder. And then create folder ```test1```. And then returning to the root path. And then create folder ```test2``` success.

In the same path can not contain two identical file/folder.

There are two issues:
1. Send request path error while creating folder
2. Folder hierarchy display error

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will fix it.

**Comment by calvinjiang** [comment]
I'll work it out.
