### ISSUE TITLE
[Feature][Dolphinscheduler-Core] Suggest dolphinscheduler supports dbt tool

### ISSUE THREAD

**Issue by ChenShuai1981** [apache/dolphinscheduler#8841]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

dbt (https://www.getdbt.com/) is a widely used transformation tool, airflow has supported it already [1,2,3,4], hope dolphinscheduler will support it soon.

[1] https://adrianleexinhan.medium.com/using-airflow-as-a-scheduler-to-orchestrate-dbt-on-snowflake-6bef760c6c7
[2] https://github.com/astronomer/airflow-dbt-demo
[3] https://analyticsmayhem.com/dbt/schedule-dbt-models-with-apache-airflow/
[4] https://quickstarts.snowflake.com/guide/data_engineering_with_apache_airflow/index.html

### Use case

DolphinScheduler helps schedule dbt models

### Related issues

None

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @ChenShuai1981 can you provide a design of dbt in DS? Is it like the Seatunnel Task?

**Comment by kartikzheng** [comment]
support，top!

**Comment by zwZjut** [comment]
video about dbt: https://www.youtube.com/watch?v=M8oi7nSaWps
useful for Data warehouse development

**Comment by davidzollo** [comment]
good suggestion

**Comment by davidzollo** [comment]
@ChenShuai1981 are you interested in designing and implementing this feature?

**Comment by zcfrank1st** [comment]
dbt is fantastic， when to support？

**Comment by leo459028** [comment]
dbt-core is popular. Can it  integrate with Dolphinscheduler？

**Comment by holmofy** [comment]
The design concept of dbt is very good, but unfortunately it is not popular in china.

**Comment by jeremyzhang866** [comment]
Are there any plans to implement this feature?

**Comment by jianchengwang** [comment]
Are there any plans to implement this feature?

**Comment by changqing** [comment]
support

**Comment by YuriyGavrilov** [comment]
+1

**Comment by kuantian-zhang** [comment]
+1

**Comment by alextinng** [comment]
support

**Comment by lulucici** [comment]
support

**Comment by ChenShuai1981** [comment]
So does dolphinscheduler support dbt now?

**Comment by capoolebugchat** [comment]
+1 Imma look into this

**Comment by XtreamData** [comment]
1. Is there any support for SNOWFLAKE in the PROCEDURE and SQL nodes? We use Snowflake extensively and are considering Dolphin Scheduler as the definitive orchestrator for our data workflows.
2. Can I trigger DBT models from Dolphin Scheduler? How?
