### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] Create duplicate user error

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8842]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![](https://vip2.loli.io/2022/03/12/aGzvPtnb7Rm5Bq9.png)

### What you expected to happen

After failed to create a duplicate user. Unable to save after entering the user editing page. 

### How to reproduce

above.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.

**Comment by Amy0104** [comment]
This bug is forwarded to me.

**Comment by songjianet** [comment]
Thank you for your feedback. I will close this question and link it to this issue while working on it https://github.com/apache/dolphinscheduler/issues/8854.
