### ISSUE TITLE
[Enhancement][API] Suggest support batch copy online process definitions.

### ISSUE THREAD

**Issue by lgcareer** [apache/dolphinscheduler#8855]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

If need to batch copy online process definitions,it should set the process definition offline,and then batch copy them.
Whether can support batch copy online process definitions?
<img width="400" alt="image" src="https://user-images.githubusercontent.com/15651066/158095998-aecc1ef8-4a1f-4e1f-8539-22a570552545.png">

### Use case

Whether can support batch copy online process definitions?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
It seems OK, What do you think?  @JinyLeeChina

**Comment by brave-lee** [comment]
For online workflows,  i think we can release single copy on the list page. Batch copy and batch delete are operations at the same level and cannot be released. What do you think? @lenboo @zhongjiajie

**Comment by zhongjiajie** [comment]
> For online workflows, i think we can release single copy on the list page. Batch copy and batch delete are operations at the same level and cannot be released. What do you think? @lenboo @zhongjiajie

Hi @JinyLeeChina, why do you think we should not allow batch copy online workflow? Do you think online workflow should be taken carefully and should not do some batch operators?

**Comment by zhongjiajie** [comment]
reopen it because i think it is necessary

**Comment by zhongjiajie** [comment]
remove stale

**Comment by zhuxt2015** [comment]
I will submit a pr for this issue
