### ISSUE TITLE
[Bug][api] Different users cannot use the same project name 

### ISSUE THREAD

**Issue by Hou-Shuaishuai** [apache/dolphinscheduler#8862]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Different users cannot use the same project name .
![image](https://user-images.githubusercontent.com/34434631/158108462-31e1304d-f7b6-4f03-9673-c1abb82a4887.png)

### What you expected to happen

The current user can't see other people's project lists and should theoretically be able to own projects that don't exist under the current user

### How to reproduce

Create two users. When user 1 creates a project named ETL, user 2 reports a project name error when creating another project named ETL

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @Hou-Shuaishuai this is a easy issue, can you try to submit a pr to fix it?

**Comment by Hou-Shuaishuai** [comment]
Yes, since I'm not familiar with the code and have work to do, it may not be that fast.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月15日(星期二) 下午5:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] [Bug][api] Different users cannot use the same project name  (Issue #8862)





 
Hi @Hou-Shuaishuai this is a easy issue, can you try to submit a pr to fix it?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caishunfeng** [comment]
> Yes, since I'm not familiar with the code and have work to do, it may not be that fast

OK, I assign this issue to you, and you can fix it at your own pace.

**Comment by Hou-Shuaishuai** [comment]
In the process of modification, I found that 'projectMapper.queryByName(projectName)' was used in 'dolphinscheduler-python/src/main/java/org/apache/dolphinscheduler/server/PythonGatewayServer.java', and I learned the concept of work flow user through 'pydolphinscheduler/src/pydolphinscheduler/core/default_config.yaml'. It was then discovered that user 1's project could be authorized to user 2.

If user 1 has an ETL project, and user 2 has an ETL project, and grants user 1's ETL project to user 2, then user 2's project list will have two ETL projects, one from user 1 and one from user 2. The problem is that the PyDolphinScheduler module queries projectCode by projectName and it may not be clear to the PydolphinScheduler user which user the project is from. It may be neither default.user.name nor default.workflow.user in 'pydolphinscheduler/src/pydolphinscheduler/core/default_config.yaml'. So it makes sense that the projectName global is unique in the PyDolphinScheduler module.

**Comment by caishunfeng** [comment]
> In the process of modification, I found that 'projectMapper.queryByName(projectName)' was used in 'dolphinscheduler-python/src/main/java/org/apache/dolphinscheduler/server/PythonGatewayServer.java', and I learned the concept of work flow user through 'pydolphinscheduler/src/pydolphinscheduler/core/default_config.yaml'. It was then discovered that user 1's project could be authorized to user 2.
> 
> If user 1 has an ETL project, and user 2 has an ETL project, and grants user 1's ETL project to user 2, then user 2's project list will have two ETL projects, one from user 1 and one from user 2. The problem is that the PyDolphinScheduler module queries projectCode by projectName and it may not be clear to the PydolphinScheduler user which user the project is from. It may be neither default.user.name nor default.workflow.user in 'pydolphinscheduler/src/pydolphinscheduler/core/default_config.yaml'. So it makes sense that the projectName global is unique in the PyDolphinScheduler module.

@zhongjiajie can you take a look?

**Comment by zhongjiajie** [comment]
Will take a look tomorrow

**Comment by Hou-Shuaishuai** [comment]
If multiple projectnames are the same when scheduling dependencies because of project authorization, it does create ambiguity, so projectName that are globally unique should not be a bug

**Comment by zhongjiajie** [comment]
> In the process of modification, I found that 'projectMapper.queryByName(projectName)' was used in 'dolphinscheduler-python/src/main/java/org/apache/dolphinscheduler/server/PythonGatewayServer.java', and I learned the concept of work flow user through 'pydolphinscheduler/src/pydolphinscheduler/core/default_config.yaml'. It was then discovered that user 1's project could be authorized to user 2.
> 
> If user 1 has an ETL project, and user 2 has an ETL project, and grants user 1's ETL project to user 2, then user 2's project list will have two ETL projects, one from user 1 and one from user 2. The problem is that the PyDolphinScheduler module queries projectCode by projectName and it may not be clear to the PydolphinScheduler user which user the project is from. It may be neither default.user.name nor default.workflow.user in 'pydolphinscheduler/src/pydolphinscheduler/core/default_config.yaml'. So it makes sense that the projectName global is unique in the PyDolphinScheduler module.

Hi @Hou-Shuaishuai, It should not be a problem for pydolphinscheduler, At least we could grant projects to a specific user in web UI. For now pydolphinscheduler will raise error when one user have more than one project with same name. But if our web UI find out how to handle this situation, pydolphinscheduler could also do it.

**Comment by zhongjiajie** [comment]
> If multiple projectnames are the same when scheduling dependencies because of project authorization, it does create ambiguity, so projectName that are globally unique should not be a bug

I think we should correct it and make it support to user-group-level but not for global. Global is odd in this situation

**Comment by zhongjiajie** [comment]
I add a label discussion for this issue. It need more discuss before we do it

**Comment by Hou-Shuaishuai** [comment]
You mean projectName is unique within the user-group and can be displayed with the same projectName from different user-groups during scheduling? I think we can confirm with Issue [#9016](https://github.com/apache/dolphinscheduler/issues/9016) how to modify

**Comment by zhongjiajie** [comment]
> You mean projectName is unique within the user-group and can be displayed with the same projectName from different user-groups during scheduling?

Yeah, that's what I mean. And it seems this issue is related to many other code we have to deal with it carefully

**Comment by zhongjiajie** [comment]
remove stale

**Comment by zhongjiajie** [comment]
remove stale

**Comment by brave-lee** [comment]
> If multiple projectnames are the same when scheduling dependencies because of project authorization, it does create ambiguity, so projectName that are globally unique should not be a bug

I agree with you, so I close this issue. If someone has other suggest, we can discuss again.
