### ISSUE TITLE
[Feature][doc] Add how to change database type in docker-compose

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#8866]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

For now, the default database in docker-compose is PostgreSQL which you could see in https://github.com/apache/dolphinscheduler/blob/df26be89ed06928f9c4a446e3c1ebc976d562cef/deploy/docker/docker-compose.yml#L20. If users want to change the database to MySQL, they have to change our configuration. we have to add some docs about how to change the databases and give a demo about it

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qinglanmei** [comment]
Please assign this to me.

**Comment by zhongjiajie** [comment]
I assigne to you now

**Comment by zhongjiajie** [comment]
Currently, we only support pg in docker-compose.yaml, so it is no need this freature, cc @qinglanmei
