### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] Environment Manage is null

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8867]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Environment Manage is null

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/76080484/158117528-51d2f36d-8cc5-4a6d-a8c5-03cbb6345ea3.png">

<img width="1905" alt="image" src="https://user-images.githubusercontent.com/76080484/158117716-29f9e72d-82b4-4827-8a11-cf9d4aef2b61.png">

### What you expected to happen

The Environment Manage field has data

### How to reproduce

1、Create a workflow
2、Select an environment

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
![image](https://user-images.githubusercontent.com/11962619/158508389-2449dad5-0662-4123-806e-6e25f049bb20.png)
Api response data but not show.

**Comment by devosend** [comment]
<img width="844" alt="image" src="https://user-images.githubusercontent.com/8847400/158513832-cd8e6436-bf40-4e6a-965f-010f330840aa.png">
This is due to you not set `worker groups`  @XuXuClassMate

**Comment by XuXuClassMate** [comment]
Sorry, I have shown normal here
