### ISSUE TITLE
[Bug] [UI Next][V1.0.0-Alpha] pre task can not be selected when creating task in dag page

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8869]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![](https://vip1.loli.io/2022/03/14/KRBmyJE87ULVWxq.png)

### What you expected to happen

above.

### How to reproduce

above.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will fix it.
