### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] Branch flown and Custom Parameters field display does not get data

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8873]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Branch flown and Custom Parameters field display does not get data

<img width="1914" alt="image" src="https://user-images.githubusercontent.com/76080484/158125841-7228a789-3eb4-4341-b48e-aba8d1fb78ae.png">

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/76080484/158125948-34dd3696-d675-436c-add0-2b5a4ba8598c.png">

### What you expected to happen

Normal data acquisition and normal presentation

### How to reproduce

1、Create workflow
2、Create two components
3、Create a CONDITIONS component

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
I have a try at local, and found that the downstream task can't show the pre-tasks before save workflow, so this is a issue of FE.

**Comment by Amy0104** [comment]
I will fix it.
