### ISSUE TITLE
[Bug] [UI Next][V1.0.0-Alpha] sqoop task node missing some type when type is export

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8875]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/17822915/158135197-50850459-e0d9-40e5-8a7a-2fd8664a1b85.png)

### What you expected to happen

above.

### How to reproduce

above.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will fix it.
