### ISSUE TITLE
[Bug] [UI-Next] Cannot update tenant individually on user info site.

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#8878]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When i want to update the tenant individually on user info site,  but the 'password' field is a required.
I think this password field should not be required, because i want to set tenant individually.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/29528966/158149934-7d95d106-2f27-488a-b73c-4e1a04bd4b91.png">

### What you expected to happen

I can update the tenant individually on user info site.

### How to reproduce

update the user info

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
This is implemented in the old ui. If it needs to be modified, it must be modified together with the interface.

**Comment by lenboo** [comment]
> This is implemented in the old ui. If it needs to be modified, it must be modified together with the interface.

Yes, but you can set the password empty,  then the password would not be changed.

**Comment by songjianet** [comment]
> > This is implemented in the old ui. If it needs to be modified, it must be modified together with the interface.
> 
> Yes, but you can set the password empty, then the password would not be changed.

If it is empty, pass it to the backend, so the password will not be changed. I don't know if the backend does this or not.

**Comment by calvinjiang** [comment]
I suppose that  it's better to set a user's password on an independent form. So when modifying a user's information you won't need to put the user's password in the password field.
I'd like to check it out.
