### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] save workflow in workflow instance detail page no response

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8882]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![](https://vip1.loli.io/2022/03/14/3m6CnApz7yaJg25.png)

### What you expected to happen

above.

### How to reproduce

above.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
