### ISSUE TITLE
[Bug] upgrade from 2.0.0 to 2.0.5 then python with default environment will not to work

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#8893]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

upgrade from 2.0.0 to 2.0.5 then python with default environment will not to work：

my ${dolphin_home}/conf/env/dolphinscheduler_env.sh had set PYTHON_HOME :
export PYTHON_HOME=/data/soft/miniconda3/envs/jupyterhub

and in dolphinscheduler 2.0.0  it works fine , but after upgrade to 2.0.5 ,I got error : 
ImportError: No module named requests

**Thant means dolphinscheduler not use the PYTHON_HOME which I set.**

### What you expected to happen

if I create a environment in dolphin .  how can I bind the environment to my python task by change the dolphinscheduler metadata in database.

### How to reproduce

create a python virtual environment ，and set PYTHON_HOME in dolphinscheduler_env.sh to point it ,create python task in 2.0.0 without create any new environment . after update to 2.0.5 ,it will not work.

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @lordk911 I think you should change the task definition from UI or API, but not update database directly.

**Comment by lordk911** [comment]
sorry, it's not a bug , my env problem
