### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha]  Remove workflow prompt error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8894]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Remove workflow prompt error

![image](https://user-images.githubusercontent.com/76080484/158314632-0c953da9-789e-497f-a6b3-11dfb98d8b59.png)

### What you expected to happen

Should show workflow name , shouldn't show workflow id

### How to reproduce

1、New workflow
2、On-line workflow
3、Delete workflow

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
>1、New workflow
>2、On-line workflow
>3、Delete workflow

The online workflow can't be deleted, so I think it's not a bug. @XuXuClassMate

**Comment by Tianqi-Dotes** [comment]
You need to get it offline and delete.

**Comment by devosend** [comment]
I will fix it
