### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha]query plugins result is null

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8900]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

query plugins result is null

![image](https://user-images.githubusercontent.com/76080484/158327996-c3385523-d27b-434d-b304-d546fd89735b.png)

### What you expected to happen

Successfully acquire data and display

### How to reproduce

1、Click  Security
2、Click  Alarm Instance Manage
3、Then it will show query plugins result is null

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
sorry, I can't reproduce at local. 
![image](https://user-images.githubusercontent.com/11962619/158504846-d4c660ef-207f-4a97-8dd9-1d36c67f5b87.png)

**Comment by caishunfeng** [comment]
@songjianet I found you had assigned yourself, so this is a bug of FE?

**Comment by Tianqi-Dotes** [comment]
This error message from '/dolphinscheduler/ui-plugins/query-by-type?pluginType=ALERT', due to no plugin defined in table 't_ds_plugin_define'. I have copy one row from ds 204 env and this error won't show again. But cause alert instance creation problem and will check soon.

**Comment by Tianqi-Dotes** [comment]
I have figured out this problem is due to no alert plugins data in table 't_ds_plugin_define'. You need to run the alert-server so that it will generate alert plugins and you move forward. I think this is not a bug.
