### ISSUE TITLE
[Bug] [UI Next][V1.0.0-Alpha] sub process child node can not be saved.

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#8906]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![](https://vip1.loli.io/2022/03/15/9cl8L2orYwZNSua.png)

### What you expected to happen

above.

### How to reproduce

sub process child node can not be saved. Causing save workflow error.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
This issue has been resolved, please check https://github.com/apache/dolphinscheduler/pull/8928.
