### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] Complementary run, end time display error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8910]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Complementary run, end time display error

![image](https://user-images.githubusercontent.com/76080484/158355387-5ba0d2aa-1efd-4eda-8e0f-a47b182adce9.png)

![image](https://user-images.githubusercontent.com/76080484/158355361-16557ac7-a408-442b-ba1e-91d742ce972a.png)

### What you expected to happen

Demonstrate correct

### How to reproduce

1、Click to make up the number
2、Select the time interval
3、Click Task Instance, the End Time field shows the error

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
I found when the time is null, it will show `1970-01-01 08:00:00`, like the default timestamp in UI. @XuXuClassMate @songjianet

**Comment by Amy0104** [comment]
I will fix it.

**Comment by Amy0104** [comment]
This bug is not reproduced.
