### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]Page display error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8911]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Page display error

![image](https://user-images.githubusercontent.com/76080484/158356242-339ba710-1518-466b-93c0-476658900589.png)

![image](https://user-images.githubusercontent.com/76080484/158356278-3f0fb6ed-542b-40e3-902d-27c11a079854.png)

### What you expected to happen

Demonstrate correct

### How to reproduce

click Task Instance，Page display error

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.

**Comment by songjianet** [comment]
Please check https://github.com/apache/dolphinscheduler/issues/8953 .
