### ISSUE TITLE
[Discussion][Worker] Get yarn application id by application tag

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#8915]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Now DS get the yarn application id from parsing task log, which is not graceful.

The idea to query application id by the giving unique tag, such as 'tag-uuid', the tag can set by user from UI, and then we can use the yarn cli to query application id directly by `./bin/yarn application --list | grep tag-uuid`.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
That's a good idea. But I think ```yarn application -list``` is not as good as parsing task log.

In yarn application, only application name can be customized by users. However, some components do not support setting application name in yarn. Such as ```hive on tez```. Which is highly recommanded by AWS.

**Comment by caishunfeng** [comment]
> That's a good idea. But I think `yarn application -list` is not as good as parsing task log.
> 
> In yarn application, only application name can be customized by users. However, some components do not support setting application name in yarn. Such as `hive on tez`. Which is highly recommanded by AWS.

@SbloodyS thanks for your feedback, so now the way to parse task log can also support `hive on tez`? If you have other good idea, please let me know, thanks~

**Comment by SbloodyS** [comment]
> > That's a good idea. But I think `yarn application -list` is not as good as parsing task log.
> > In yarn application, only application name can be customized by users. However, some components do not support setting application name in yarn. Such as `hive on tez`. Which is highly recommanded by AWS.
> 
> @SbloodyS thanks for your feedback, so now the way to parse task log can also support `hive on tez`? If you have other good idea, please let me know, thanks~

Yes. All hive programs will output the ```yarn application id``` to ```stdout```.

I haven't thought of a better way at present.
