### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha]List of projects show repeat

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8927]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

List of projects show repeat

![image](https://user-images.githubusercontent.com/76080484/158525548-8e46863e-856b-4a57-add5-2dc469ede077.png)

### What you expected to happen

1、Create a new project to save
2、Create a new user
3、Authorize->Project Authorize
4、List of projects show no duplication

### How to reproduce

1、New project save
2、Create a new user
3、Authorize->Project Authorize
4、Project Show Repeat

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
I have tried this operation but found nothing went wrong, need to re-test with newest version.
