### ISSUE TITLE
[Bug] [dao] Description Failed to upload the file because the full name was too long

### ISSUE THREAD

**Issue by Hou-Shuaishuai** [apache/dolphinscheduler#8929]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Description Failed to upload the file because the full name was too long
![Uploading image.png…]()

### What you expected to happen

I think the length of 64 is too short to include directory levels and file names and recommend 128

### How to reproduce

Create a folder named offline_stats and upload a file named statistics_job-1.0-snapshot-jar-with-dependencies.jar

### Version

2.0.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @Hou-Shuaishuai I had assign to you. But please check the 2.0.5 version of this issue, thanks.
