### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] Service Manage/Worker display error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8934]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Service Manage/Worker display error

![image](https://user-images.githubusercontent.com/76080484/158579351-47bdb69a-e975-46de-8dbe-3455d9ce7d04.png)

### What you expected to happen

Show all workers

### How to reproduce

Multiple workers, but only one worker is shown

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.

**Comment by songjianet** [comment]
Thank you for your feedback. I will close this issue. Please check https://github.com/apache/dolphinscheduler/issues/8997.
