### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]Project links are placed in other windows to enter，UI error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8948]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Project links are placed in other windows to enter，UI error

![Fil0FdChxW](https://user-images.githubusercontent.com/76080484/158728532-808c1fd1-c2eb-4b2e-93f4-5e86df2a81ac.png)

### What you expected to happen

Show the right page

### How to reproduce

Project links are placed in other windows to enter，UI error

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
How to reproduce？Can you describe it in detail？

**Comment by devosend** [comment]
I will fix it
