### ISSUE TITLE
[Feature][python] Add example about multi line shell

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#8955]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In all our examples in https://dolphinscheduler.apache.org/python/tasks/shell.html#example are single line. we should add example about how to create shell task in multiple lines

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
And also string format

**Comment by zhongjiajie** [comment]
better to add parameter for our example

**Comment by HarshitNagpal29** [comment]
@zhongjiajie sir please assign this issue to me, I will try my best to solve it, also can you just summarise what exactly I have to do as some of the links are not updated mentioned in this issue, it would be really helpful.

**Comment by HarshitNagpal29** [comment]
>  also can you just summarize what exactly I have to do as some of the links are not updated mentioned in this issue, it would be really helpful.
@zhongjiajie sir please give a little bit brief about it.

**Comment by HarshitNagpal29** [comment]
> > also can you just summarize what exactly I have to do as some of the links are not updated mentioned in this issue, it would be really helpful.
> > @zhongjiajie sir please give a little bit brief about it.

@zhongjiajie ....

**Comment by HarshitNagpal29** [comment]
@zhongjiajie Sir, as I can understand from whatever information is provided that the DolphinScheduler documentation needs to be updated to include a detailed example illustrating how to create and execute a multi-line shell task within a Python context. This goes beyond the existing single-line examples, emphasizing the need to showcase more complex scenarios where shell commands or tasks in Python might extend over multiple lines of code. Am I right in comprehending this, if not then please specify anything which needs to be rectified along with this.

**Comment by zhongjiajie** [comment]
> @zhongjiajie Sir, as I can understand from whatever information is provided that the DolphinScheduler documentation needs to be updated to include a detailed example illustrating how to create and execute a multi-line shell task within a Python context. This goes beyond the existing single-line examples, emphasizing the need to showcase more complex scenarios where shell commands or tasks in Python might extend over multiple lines of code. Am I right in comprehending this, if not then please specify anything which needs to be rectified along with this.

Hi @HarshitNagpal29, sorry for replying late, we should submit the change to https://github.com/apache/dolphinscheduler-sdk-python. for more specific line are those lines https://github.com/apache/dolphinscheduler-sdk-python/blob/e04b836e54fb7bfd96527007cfeaa0fef4444b07/src/pydolphinscheduler/examples/tutorial.py#L51-L54 we should pick one of those task and change them as multiple lines shell example

**Comment by HarshitNagpal29** [comment]
@zhongjiajie No problem Sir , I have created pull request again in https://github.com/apache/dolphinscheduler-sdk-python as you said, please check it and let me know if I have to make more changes in that.
