### ISSUE TITLE
[Feature][DATABASE] Support Oracle Database Type

### ISSUE THREAD

**Issue by chengpeng995** [apache/dolphinscheduler#8956]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Is it possible to support Oracle as a database to store DS metadata, or what configuration can I change to achieve this requirement?
At present, many enterprises do not use mysql due to security problems

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
At present, DS has no plan to support Oracle as a metabase. If others need this function, you can leave a message here and we will count the degree of attention to this requirement.

**Comment by EricJoy2048** [comment]
Anyway, if you are willing to submit a PR to solve this problem, we also welcome it.

**Comment by black-xiu** [comment]
> At present, DS has no plan to support Oracle as a metabase. If others need this function, you can leave a message here and we will count the degree of attention to this requirement.

need help
