### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] English should be displayed here

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8961]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 English should be displayed here

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/76080484/158768663-3e3fa1d1-1e98-41d6-a767-7aea5a652e1c.png">

### What you expected to happen

English should be displayed here

### How to reproduce

English should be displayed here

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
i will fix it
