### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]UI text blocking

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8962]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

”security.alarm_instance.WarningType“UI text blocking

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/76080484/158769281-d4725365-dbf1-4c16-985e-648a1d0aeca4.png">

### What you expected to happen

Show normal

### How to reproduce

”security.alarm_instance.WarningType“UI text blocking

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it

**Comment by songjianet** [comment]
> I will fix it

I'll handle this.

**Comment by songjianet** [comment]
![1647584722](https://user-images.githubusercontent.com/19239641/158948691-a7b4fe2a-665b-467b-8fde-652f4d2ecb27.png)

@caishunfeng I have fixed the problem that the language is not supported, but it seems that there is still a problem in the picture, please confirm.
