### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] Task definition page table scale imbalance problem.

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8965]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Page display ratio error

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/76080484/158771315-21023658-4d0a-4bda-b3a5-1303a24f04c9.png">

### What you expected to happen

Wrong display ratio

### How to reproduce

Task Definition click

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it
