### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] There is no floating prompt for the table operation button in the alarm instance management.

### ISSUE THREAD

**Issue by songjianet** [apache/dolphinscheduler#8967]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/19239641/158780904-efe1b120-bef9-49f4-bd54-bb51da63a627.png)

### What you expected to happen

There is no floating prompt for the table operation button in the alarm instance management.

### How to reproduce

Add hover prompt.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will fix it.
