### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] The table action button in the data source center lacks a floating prompt.

### ISSUE THREAD

**Issue by songjianet** [apache/dolphinscheduler#8971]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/19239641/158787045-8c454f01-0fca-465c-aa29-2271ef6bb48d.png)

### What you expected to happen

The table action button in the data source center lacks a floating prompt.

### How to reproduce

Data source center table operation button adds floating prompt

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will fix it.
