### ISSUE TITLE
[Feature][processdefine] use unique index

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#8976]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

because of bug https://github.com/apache/dolphinscheduler/issues/8790 , the database could be contaminated
the database constraint should be the last line of defense.
ID can be use as no business logic primary key , and  business logic primary key can be use as unique index.

something like this:

```
ALTER TABLE
    `dolphinscheduler`.`t_ds_task_definition` ADD CONSTRAINT uidx_tdef_cv UNIQUE (`code`,
    `version`)
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
It's a good idea, and I think the unique index should also add in `t_ds_task_definition_log`. 
What do you think? @JinyLeeChina @lordk911 @SbloodyS

**Comment by SbloodyS** [comment]
> It's a good idea, and I think the unique index should also add in `t_ds_task_definition_log`. What do you think? @JinyLeeChina @lordk911 @SbloodyS

I think it's a good idea too.
