### ISSUE TITLE
[Feature][UI] Add an option "thisMonthBegin" in dependency settings in dependent node

### ISSUE THREAD

**Issue by ghost** [apache/dolphinscheduler#8985]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://user-images.githubusercontent.com/92249031/158957639-0a90f4f6-581f-40af-856b-ec4baed303af.png)
add thisMonthBegin in the drop down menu here, it will be useful in some cases, for example, we have  lots of workflows which depended by other workflows, and the workflow being depended are running on 1st day of the month, if we had this option, things will be easyer.
有的工作流依赖本月初运行的工作流，如果在依赖节点中有 本月初 的选项，会很有用。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I'll deal with this feature.
