### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] Monitoring Center does not support multiple `master`.

### ISSUE THREAD

**Issue by songjianet** [apache/dolphinscheduler#8998]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Monitoring Center does not support multiple `master`.

### What you expected to happen

Monitoring Center does not support multiple `master`.

### How to reproduce

Support `master`.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.

**Comment by zhangxinruu** [comment]
I will fix it.
