### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] There is a problem with the language support of the DingTalk alarm instance.

### ISSUE THREAD

**Issue by songjianet** [apache/dolphinscheduler#9000]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/19239641/159026273-2d3a9f22-79da-4a68-b27b-fa4b54308d79.png)

### What you expected to happen

There is a problem with the language support of the DingTalk alarm instance

### How to reproduce

Support i18n.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.

**Comment by zhangxinruu** [comment]
I will fix it.
