### ISSUE TITLE
[Bug][UI Next][V1.0.0-Alpha] WebexTeams alarm instance language support has problems.

### ISSUE THREAD

**Issue by songjianet** [apache/dolphinscheduler#9002]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/19239641/159027033-31f24680-a065-4cac-aa0e-f32c16bf7129.png)

### What you expected to happen

WebexTeams alarm instance language support has problems.

### How to reproduce

Support i18n.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.

**Comment by zhangxinruu** [comment]
I will fix it.
