### ISSUE TITLE
[Improvement][API] Dependent The global project can be selected when adding dependencies

### ISSUE THREAD

**Issue by Hou-Shuaishuai** [apache/dolphinscheduler#9016]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When adding dependencies to tasks, you should be able to select the global project

### Use case

Within a company, upstream and downstream tasks may be developed by different people. If the task for Table1 belongs to User1's project1 and user2's task for table2 depends on the task for Table1, there are two ways to solve this problem:

1. User2 can choose project1 by default when adding dependencies to Table2
2. User2 needs to apply for privileges for Project1 and then configure dependencies. In this case the process is more responsible and requires more fine-grained permission control for the project. If user1 and user2 belong to different departments, user2 should not have modification and deletion permissions for Project1.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Related issue: #8922
