### ISSUE TITLE
[Bug-RD][UI NEXT] After switching the time zone, the phone number is not displayed

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#9018]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/95271106/159118819-7c904131-b6c9-48d6-9a69-1441e6762c0e.png">
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/95271106/159118897-040cbb01-926f-46f3-aea3-7a4eaa9c48e0.png">

### What you expected to happen

.

### How to reproduce

.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I'll work out this issue.

**Comment by calvinjiang** [comment]
This issue couldn't be reproduced. Seems like it has been fixed. So I'll close this issue.
