### ISSUE TITLE
[Bug][UI  Next][V1.0.0-Alpha] When creating a new project, the last created project information is not cleared

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#9024]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. Create a new project. Enter the project name and description. The project is created successfully

2. Click "create project" again, the name and description of the last created project will be displayed, which should be empty
<img width="869" alt="image" src="https://user-images.githubusercontent.com/95271106/159149588-24862cc6-53ae-44b9-99a1-b52be2df5d25.png">

### What you expected to happen

.

### How to reproduce

.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.

**Comment by zhangxinruu** [comment]
I will fix it.
