### ISSUE TITLE
[Bug] [UI Next]  An error is reported when an ordinary user creates a workflow definition

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#9025]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. Ordinary users create workflows and drag shell components
2. Picture 404, JS error
<img width="912" alt="image" src="https://user-images.githubusercontent.com/95271106/159149774-6eecc175-1059-407b-8d28-d6eadbc60c8d.png">
3. No operation permission returned by the interface

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/95271106/159149807-efe39272-a5d9-4fe6-b068-5c7a667683c6.png">

### What you expected to happen

.

### How to reproduce

.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by janeHe13** [comment]
The workflow tree picture is also 404


<img width="1265" alt="image" src="https://user-images.githubusercontent.com/95271106/159150367-7ca5c9a9-a3d5-440d-90e6-939380aa179d.png">

**Comment by songjianet** [comment]
This problem may be related to the deployment of your environment. It seems that other early adopters have not learned about this problem, and it has no problem in my local area.

**Comment by songjianet** [comment]
These three issues seem to have the same problem. Please check https://github.com/apache/dolphinscheduler/issues/9034 and https://github.com/apache/dolphinscheduler/issues/9042

**Comment by calvinjiang** [comment]
I'll work out this issue.
