### ISSUE TITLE
[Bug] [UI Next] The workflow is online, but the scheduling offline is displayed in the workflow relationship 

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#9028]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="768" alt="image" src="https://user-images.githubusercontent.com/95271106/159150509-4a52a2b3-3903-4eb9-8b29-744a022c8b57.png">
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/95271106/159150545-fa4d475f-34e9-43a1-9987-b1e92f68bd30.png">

### What you expected to happen

.

### How to reproduce

.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I don't think this is a bug, the reason for this is that scheduling and workflow are not fully separated.
