### ISSUE TITLE
[Bug] [dolphinscheduler-api] After the workflow is deleted, the task definition under the workflow is not deleted 

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#9029]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/95271106/159151868-bb8471f0-c5e1-483e-bb8d-5a80694edfd1.png">

### What you expected to happen

.

### How to reproduce

.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This logic might be missing during splitting task from workflow. Related issue: #7767

I was wondering if the process instance and its task instance should be deleted while deleting the process definition. I think the process instance and its task instance is meaningless when its workflow doesn't exist. WDYT? @caishunfeng @zhongjiajie

**Comment by caishunfeng** [comment]
> I was wondering if the process instance and its task instance should be deleted while deleting the process definition. I think the process instance and its task instance is meaningless when its workflow doesn't exist. WDYT? @caishunfeng @zhongjiajie

Agree with you, when delete process definition, it should alse delete the task definition, process_task_relation, process instances, task instances, schedule.

**Comment by SbloodyS** [comment]
> > I was wondering if the process instance and its task instance should be deleted while deleting the process definition. I think the process instance and its task instance is meaningless when its workflow doesn't exist. WDYT? @caishunfeng @zhongjiajie
> 
> Agree with you, when delete process definition, it should alse delete the task definition, process_task_relation, process instances, task instances, schedule.

I'll submit a pr to fix this issue.

**Comment by zhongjiajie** [comment]
> Agree with you, when delete process definition, it should alse delete the task definition, process_task_relation, process instances, task instances, schedule.

One more thing, I have vague memories that we have task definition related to one or muliple process definition, in that case we should not delete those task related to other process definition, am I right

**Comment by SbloodyS** [comment]
> > Agree with you, when delete process definition, it should alse delete the task definition, process_task_relation, process instances, task instances, schedule.
> 
> One more thing, I have vague memories that we have task definition related to one or muliple process definition, in that case we should not delete those task related to other process definition, am I right

In this case, If a process definition or its task definition dependented/subprocessed by other process or task. Should it able to delete or not?

**Comment by caishunfeng** [comment]
> In this case, If a process definition or its task definition dependented/subprocessed by other process or task. Should it able to delete or not?

I think if a process definition was offline, although it was dependented by other process, like dependent task or switch task, it will also take no effect.It is up to user, but it's better to give a tips, such as double confirm before delete.

**Comment by SbloodyS** [comment]
> > In this case, If a process definition or its task definition dependented/subprocessed by other process or task. Should it able to delete or not?
> 
> I think if a process definition was offline, although it was dependented by other process, like dependent task or switch task, it will also take no effect.It is up to user, but it's better to give a tips, such as double confirm before delete.

Do you mean that promt the user which tasks depend on the current task when deleting process definition?

**Comment by caishunfeng** [comment]
> > > In this case, If a process definition or its task definition dependented/subprocessed by other process or task. Should it able to delete or not?
> > 
> > 
> > I think if a process definition was offline, although it was dependented by other process, like dependent task or switch task, it will also take no effect.It is up to user, but it's better to give a tips, such as double confirm before delete.
> 
> Do you mean that promt the user which tasks depend on the current task when deleting process definition?

yes

**Comment by SbloodyS** [comment]
> > > > In this case, If a process definition or its task definition dependented/subprocessed by other process or task. Should it able to delete or not?
> > > 
> > > 
> > > I think if a process definition was offline, although it was dependented by other process, like dependent task or switch task, it will also take no effect.It is up to user, but it's better to give a tips, such as double confirm before delete.
> > 
> > 
> > Do you mean that promt the user which tasks depend on the current task when deleting process definition?
> 
> yes

This require the front-end modify the deletion logic. First, request the dependency check interface. If no dependency is returned, then request to delete the existing interface. If not, promt user which tasks depend on the current task and let user to chose action.

**Comment by caishunfeng** [comment]
remove stale

**Comment by zhongjiajie** [comment]
remove stale

**Comment by zhongjiajie** [comment]
remove stale

**Comment by ruanwenjun** [comment]
When we delete a workflow instance, it's needed to delete the related task instances.

But for task definition, I remember as the original design(split json), the task definition is designed can be used by multiple workflow, but it seems this is unfinished..... cc @caishunfeng @SbloodyS @zhongjiajie

**Comment by SbloodyS** [comment]
> When we delete a workflow instance, it's needed to delete the related task instances.
> 
> But for task definition, I remember as the original design(split json), the task definition is designed can be used by multiply workflow, but it seems this is unfinished..... cc @caishunfeng @SbloodyS @zhongjiajie

I'm not familiar with the original design...

**Comment by ruanwenjun** [comment]
> > When we delete a workflow instance, it's needed to delete the related task instances.
> > But for task definition, I remember as the original design(split json), the task definition is designed can be used by multiply workflow, but it seems this is unfinished..... cc @caishunfeng @SbloodyS @zhongjiajie
> 
> I'm not familiar with the original design...

+1

**Comment by caishunfeng** [comment]
> When we delete a workflow instance, it's needed to delete the related task instances.
> 
> But for task definition, I remember as the original design(split json), the task definition is designed can be used by multiple workflow, but it seems this is unfinished..... cc @caishunfeng @SbloodyS @zhongjiajie

Should we consider this? Because in the current design, the task can only be in one workflow.

**Comment by ruanwenjun** [comment]
> > When we delete a workflow instance, it's needed to delete the related task instances.
> > But for task definition, I remember as the original design(split json), the task definition is designed can be used by multiple workflow, but it seems this is unfinished..... cc @caishunfeng @SbloodyS @zhongjiajie
> 
> Should we consider this? Because in the current design, the task can only be in one workflow.

I agree with we can just delete the related task definition.

**Comment by stalary** [comment]
Let me solve this problem.

**Comment by SbloodyS** [comment]
> Let me solve this problem.

It seems this issue have been fixed in #10873. Could you please check if it still exists in `dev` branch? @stalary 

This pr was not merged into 3.0.0-release. Can we marked it to 3.0.1-release? cc @zhongjiajie

**Comment by stalary** [comment]
> > Let me solve this problem.
> 
> It seems this issue have been fixed in #10873. Could you please check if it still exists in `dev` branch? @stalary
> 
> This pr was not merged into 3.0.0-release. Can we marked it to 3.0.1-release? cc @zhongjiajie

All right, let me check.

**Comment by stalary** [comment]
> > Let me solve this problem.
> 
> It seems this issue have been fixed in #10873. Could you please check if it still exists in `dev` branch? @stalary
> 
> This pr was not merged into 3.0.0-release. Can we marked it to 3.0.1-release? cc @zhongjiajie

This PR seems to be different from the problem I met. When I deleted process, the task still existed.

**Comment by SbloodyS** [comment]
> > It seems this issue have been fixed in #10873. Could you please check if it still exists in `dev` branch? @stalary
> > This pr was not merged into 3.0.0-release. Can we marked it to 3.0.1-release? cc @zhongjiajie
> 
> This PR seems to be different from the problem I met. When I deleted process, the task still existed.

I've tested this PR. It is prohibited to delete the dependent task. However, it does not implement the delete of the workflow's task definition. please go ahead with your PR. Thanks @stalary

**Comment by zhongjiajie** [comment]
> 

If so, maybe we should change our metadata in some day, we should bind `process_code`, and `task_code` in table task definition, Am I right?
