### ISSUE TITLE
[Bug] [UI Next] download task log file error

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#9030]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/95271106/159152031-cba44d32-ba66-4ad2-8240-75010bfc535a.png">
<img width="898" alt="image" src="https://user-images.githubusercontent.com/95271106/159152037-46fb07d6-41a2-47b6-adf5-3a9d2f056d95.png">

### What you expected to happen

.

### How to reproduce

.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
![image](https://user-images.githubusercontent.com/19239641/159154663-47795a05-e36c-4431-a99e-ebd389afad4b.png)
![image](https://user-images.githubusercontent.com/19239641/159154675-1b5c3019-dbef-4b70-a8c4-9000608351e8.png)

I haven't been able to reproduce the issue locally, but I'm guessing it might be a backend issue.
