### ISSUE TITLE
[Bug] [UI Next] When adding a condition node, the branch flow does not display the flow node

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#9034]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="945" alt="image" src="https://user-images.githubusercontent.com/95271106/159162110-bf30838e-f183-487f-af5d-8ebb2b0e5870.png">

### What you expected to happen

.

### How to reproduce

.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by janeHe13** [comment]
When editing the Condition node, the flow branch is selected. After saving the workflow, the flow branch is empty


<img width="554" alt="image" src="https://user-images.githubusercontent.com/95271106/159162954-468bd900-b80d-422d-a0cd-50c2f9bf4136.png">

**Comment by Amy0104** [comment]
I will fix it.

**Comment by songjianet** [comment]
These three issues seem to have the same problem. Please check https://github.com/apache/dolphinscheduler/issues/9042 and https://github.com/apache/dolphinscheduler/issues/9025
