### ISSUE TITLE
[Bug] [dolphinscheduler-api] The workflow name is duplicate. The workflow name under the same project should be unique

### ISSUE THREAD

**Issue by janeHe13** [apache/dolphinscheduler#9035]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="868" alt="image" src="https://user-images.githubusercontent.com/95271106/159162457-3ec09eb2-25b3-4938-8381-d1db20f29e2d.png">

### What you expected to happen

.

### How to reproduce

.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @janeHe13 , ```test-condition``` and ```test_condition``` are two different names.

**Comment by caishunfeng** [comment]
As @SbloodyS said, they are different names, so I will close this issue.
