### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] The input box is not cleared and the last entered data is retained

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9041]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The input box is not cleared and the last entered data is retained

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/76080484/159198321-428982e1-7967-4911-97e4-b92acd3087fa.png">

### What you expected to happen

Clean up local data in time after clicking submit

### How to reproduce

1、Click New Project
2、Enter the project name, notes
3、Click submit
4、Click New Project
Input box will appear the last new content is not cleared

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. Please check this issue https://github.com/apache/dolphinscheduler/issues/9024. I will close this issue.
