### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] New create or imported workflow component image display error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9042]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

New create or imported workflow component image display error

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/76080484/159198862-29e25c89-786e-44d5-b6e9-c17dfd966391.png">

### What you expected to happen

Component display normal

### How to reproduce

New create or imported workflow component image display error

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
These three issues seem to have the same problem. Please check https://github.com/apache/dolphinscheduler/issues/9034 and https://github.com/apache/dolphinscheduler/issues/9025

**Comment by Amy0104** [comment]
I will fix it.

**Comment by QuakeWang** [comment]
> I will fix it.

How is it going?
