### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha] Fault tolerance testing：task instance not found

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9044]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Fault tolerance testing：task instance not found

The result was executed successfully

url: http://xx.xx.xx.xx:12345/dolphinscheduler/ui/projects/4915141548736/workflow/instances/9794?code=4915195971264

<img width="1917" alt="image" src="https://user-images.githubusercontent.com/76080484/159201723-2b7424b3-3212-4004-8cd8-c7ba75fea83f.png">

### What you expected to happen

Modify error report

### How to reproduce

1、Shut down all workers
2、Start workflow tasks
3、Start a worker
The error was not found, but after refreshing, it actually executed successfully

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
This looks like a back-end problem.
