### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha] A new fault-tolerant test bug 

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9045]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Run the workflow to close worker and master, restart the workflow did not continue to execute

url：http://8.142.81.15:12345/dolphinscheduler/ui/projects/4915141548736/workflow/instances/9801?code=4915682115648

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/76080484/159208421-134de269-94dc-4572-b5d8-4eea7a8c84d3.png">

### What you expected to happen

Restarting master and worker continues execution to completion and outputs logs correctly

### How to reproduce

1. Run one or more process instances and tasks
2. Hang the Master and then the Worker
3. Restart the Master and then the Worker

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
![image](https://user-images.githubusercontent.com/11962619/160242329-ba7de0bb-d4da-44e5-9987-0c229551a699.png)
I found that if taskInstance.host is null, it will show taskInstance not exist too, which should be improved.
