### ISSUE TITLE
About the failure of using keep-alive in app.vue

### ISSUE THREAD

**Issue by Caoxiongk** [apache/dolphinscheduler#9046]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

在app.vue中使用keep-alive，页面直接白屏

### What you expected to happen

能够使用keep-alive

### How to reproduce

  <template>
	  <div v-if="isRenderRouterView">
  
		  <m-layout>
			  <m-nav slot="top"></m-nav>
        <keep-alive>
          <router-view slot="bottom"></router-view>
        </keep-alive>
		  </m-layout>
	  </div>
  </template>

### Version

1.3.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. This version is no longer maintained.

**Comment by Caoxiongk** [comment]
那有什么可以解决的办法吗 我看到其他版本中也有类似的问题

**Comment by Caoxiongk** [comment]
或者给个案例解决下 可以吗

**Comment by songjianet** [comment]
I'll schedule an experiment in the new UI later.

**Comment by Caoxiongk** [comment]
好的 谢谢

**Comment by labbomb** [comment]
I have tested the problem with the blank screen for KeepAlive and it seems to work in UI-Nex,but we won't fix it for the old UI for now

**Comment by Caoxiongk** [comment]
那新版本中 如何解决这个问题呢 包括在其他文件中使用keep也是实现的 包括vue nav也失效

**Comment by labbomb** [comment]
You can refer to this
(https://router.vuejs.org/zh/guide/migration/#router-view-%E3%80%81-keep-alive-%E5%92%8C-transition)

**Comment by labbomb** [comment]
> 那新版本中 如何解决这个问题呢 包括在其他文件中使用keep也是实现的 包括vue nav也失效

You can refer to this
(https://router.vuejs.org/zh/guide/migration/#router-view-%E3%80%81-keep-alive-%E5%92%8C-transition)

<img width="393" alt="image" src="https://user-images.githubusercontent.com/15062456/159409396-29a32a07-42a5-420a-a0b9-c554479c2920.png">

**Comment by songjianet** [comment]
Is there any doubt about this question please, if not I will close it. @Caoxiongk
