### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]Display error, should display component name not id

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9047]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Display error, should display component name not id

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/76080484/159212308-6afe49ed-64f8-40f0-b356-8d13a724f522.png">

### What you expected to happen

Display error, should display component name not id

### How to reproduce

this is Importing Workflows
Display error, should display component name not id

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it

**Comment by devosend** [comment]
This problem has been fixed. close it please.
