### ISSUE TITLE
Duplicate key TaskDefinition

### ISSUE THREAD

**Issue by Osolosooo** [apache/dolphinscheduler#9058]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Add a new resource,  it throws this error when I'm saving the workflow.

Duplicate key TaskDefinition{id=0, code=4019205585792, name='TopicAudiencesList', version=1, description='', projectCode=0, userId=0, taskType=SHELL, taskParams='{"resourceList":[{"id":61},{"id":63},{"id":137}],"localParams":[],"rawScript":"sh realtime_project/live/scripts/TopicAudiencesList.sh","dependence":{},"conditionResult":{"successNode":[],"failedNode":[]},"waitStartTimeout":{},"switchResult":{}}', taskParamList=null, taskParamMap=null, flag=YES, taskPriority=MEDIUM, userName='null', projectName='null', workerGroup='default', failRetryTimes=0, environmentCode='3957102366336', failRetryInterval=1, timeoutFlag=CLOSE, timeoutNotifyStrategy=WARN, timeout=0, delayTime=0, resourceIds='null', createTime=null, updateTime=null}

![e5e40c5e0c644810a13f3cb81c2cdb0](https://user-images.githubusercontent.com/30710888/159234987-11e403d6-9821-49f2-9e9a-7ae115dbce7c.png)

### What you expected to happen

correctly save!

### How to reproduce

1. modify a workflow;
2. add a new resource;
3. save the workflow.

### Anything else

none

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @GhostGate2017 , Which version did you upgrade from?

**Comment by Osolosooo** [comment]
> Hi @GhostGate2017 , Which version did you upgrade from?

1.3.4-->2.0.0 ->2.0.1--> 2.0.3 --> 2.05
The error already exists in version 2.0.3

**Comment by SbloodyS** [comment]
> > Hi @GhostGate2017 , Which version did you upgrade from?
> 
> 1.3.4-->2.0.0 ->2.0.1--> 2.0.3 --> 2.05 The error already exists in version 2.0.3

You can refer to the reply in this issue #8790.
