### ISSUE TITLE
[Bug] [Master] When there is only one task and the submit failed, the state of Process Instance is Incorrect

### ISSUE THREAD

**Issue by guoshupei** [apache/dolphinscheduler#9065]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

BG : The Process Instance have only one task

In the method of `submitPostNode`, the task successfully added to `readyToSubmitTaskQueue`, then submit task from queue, if submit failed, such as DB error, the `taskFailedSubmit` is true and `readyToSubmitTaskQueue` size is not empty.  

when execute the method of `updateProcessInstanceState`,
case one:  FailureStrategy is END, it return state of `FAILURE`, and update state;
case two:  FailureStrategy is CONTINUE, it return state of `RUNNING_EXECUTION`, and remain the same state forever; 

More seriously, both cases will cause `processInstanceExecCacheManager` not remove `WorkflowExecuteThread`

![image](https://user-images.githubusercontent.com/29919212/159254253-7d306b96-3a26-4b40-9fd7-1875a4404dec.png)

![image](https://user-images.githubusercontent.com/29919212/159262647-67b8351f-8073-4de3-8e60-dfe9e4c53d2a.png)

### What you expected to happen

the process instance can update the state normally and can terminate normally.

I hope it will be resolved in v2.0.6

### How to reproduce

Refer to `What happened`

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by guoshupei** [comment]
I have some suggestions for modification:
- Add remove operation in method of `submitStandByTask` (Figure 1)
- Replace `processStateChangeHandler` with `stateEvents` in the method of `updateProcessInstanceState` (Figure 2), and I think this is extremely necessary.

![image](https://user-images.githubusercontent.com/29919212/159475105-631ae2c9-ecf4-42d2-a772-b4ba52ed7ece.png)


![image](https://user-images.githubusercontent.com/29919212/159474870-7e336fa7-9eeb-4f77-a560-166da17c98cc.png)

**Comment by caishunfeng** [comment]
> readyToSubmitTaskQueue

Good suggestion.

**Comment by caishunfeng** [comment]
> I have some suggestions for modification:
> 
> * Add remove operation in method of `submitStandByTask` (Figure 1)
> * Replace `processStateChangeHandler` with `stateEvents` in the method of `updateProcessInstanceState` (Figure 2), and I think this is extremely necessary.
> 
> ![image](https://user-images.githubusercontent.com/29919212/159475105-631ae2c9-ecf4-42d2-a772-b4ba52ed7ece.png)
> 
> ![image](https://user-images.githubusercontent.com/29919212/159474870-7e336fa7-9eeb-4f77-a560-166da17c98cc.png)

Good suggestion.
