### ISSUE TITLE
About adding keep-alive to the layout in version 2.0.5, resulting in a white screen on the page

### ISSUE THREAD

**Issue by Caoxiongk** [apache/dolphinscheduler#9066]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<m-layout>
    <m-nav slot="top"></m-nav>
   <keep-alive>
    <router-view slot="bottom" v-if="isRenderRouterView"></router-view>
</keep-alive>
  </m-layout>

当再app.vue中页面加入keep-alive导致页面白屏，无法缓存

### What you expected to happen

再app.vue中加入keepalivbe实现页面缓存

### How to reproduce

<m-layout>
    <m-nav slot="top"></m-nav>
   <keep-alive>
    <router-view slot="bottom" v-if="isRenderRouterView"></router-view>
</keep-alive>
  </m-layout>

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by labbomb** [comment]
I have tested the problem with the blank screen for KeepAlive and it seems to work in UI-Nex,but we won't fix it for the old UI for now

**Comment by songjianet** [comment]
Is there any doubt about this question please, if not I will close it. @Caoxiongk
