### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] Workflow Relation field display error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9069]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

url：http://8.142.81.15:12345/dolphinscheduler/ui/projects/4915141548736/workflow/relation

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/76080484/159399088-1a91fbed-b334-4c6f-80d6-81485c280503.png">

### What you expected to happen

When the back-end return field is empty, it should also be displayed as empty or "-"

### How to reproduce

click Workflow Relation

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.
