### ISSUE TITLE
[Bug FE] [UI Next] [V1.0.0-Alpha] The interface for adding DingTalk alert instance  is not fully internationalized

### ISSUE THREAD

**Issue by huagetai** [apache/dolphinscheduler#9078]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="587" alt="alert instance" src="https://user-images.githubusercontent.com/1137341/159412473-1469085c-a329-40ba-bf13-3a4e7fadad11.png">

### What you expected to happen

Fields in red boxes are displayed in chinese

### How to reproduce

above

### Anything else

No response

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Someone is doing this problem, please look for the problem carefully next time when submitting an issue and handling PR.
