### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha]Batch copy error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9082]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Batch copy error

error massage：task type [SWITCH] does not support copy

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/76080484/159418767-be3da28b-e5e6-479e-8349-83cc22dbb2f1.png">

### What you expected to happen

Successful Replication

### How to reproduce

1、Select all
2、Click Bulk Copy
3、Select the copied item instance
Batch copy error report

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
It seems like the back-end API doesn't support this feature for a few task types.

**Comment by caishunfeng** [comment]
> It seems like the back-end API doesn't support this feature for a few task types.

yes, so this is not a issue. I will close it.

**Comment by rootyu** [comment]
> > It seems like the back-end API doesn't support this feature for a few task types.
> 
> yes, so this is not a issue. I will close it.

如果不能复制，那么复制功能就没有用。
