### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] cannot set Timeout strategy

### ISSUE THREAD

**Issue by Tianqi-Dotes** [apache/dolphinscheduler#9087]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Whatever I set to the Timeout strategy, it won't save and will show the default value '30 mins and Timeout alarm checked'

### What you expected to happen

It should save the Timeout strategy value and the next time I open the task node, the value should be the value I saved last time.

### How to reproduce

Just create a new task node and set the Timeout strategy,  and open it again it won't save.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
![image](https://user-images.githubusercontent.com/36755957/159429715-edcfe653-0f69-41aa-be77-59d8ec71d6d1.png)

**Comment by CallMeKingsley97** [comment]
your ds version？ 2.0.3 seems not like this

**Comment by caishunfeng** [comment]
![image](https://user-images.githubusercontent.com/11962619/159432195-6900a7ee-0d3c-466d-bf22-4a7cacbbdc29.png)
It's a UI bug, PTAL @songjianet

**Comment by Amy0104** [comment]
I will fix it.
