### ISSUE TITLE
[Discussion] [2.0.1-release] There are some version errors in the 2.0.1-release

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#9088]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

There are some version errors in the old version database. Please check the following issue.

https://github.com/apache/dolphinscheduler/issues/9068#issuecomment-1074842224

Since 2.0.1 has been released. I suggest put this into ```FAQ```. What do you think? @caishunfeng @zhongjiajie @JinyLeeChina 

### What you expected to happen

above.

### How to reproduce

above.

### Version

2.0.1

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Good suggestion.

**Comment by zhongjiajie** [comment]
Feel free to add it and make our docs more great
