### ISSUE TITLE
[Bug] [API Server] after upgrade from 2.0.1 to 2.0.5 , could found task in the exists process

### ISSUE THREAD

**Issue by darrkz** [apache/dolphinscheduler#9089]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After I upgrade and encounter the problem and reslove it as : https://github.com/apache/dolphinscheduler/issues/9068

I found I could not found the task nod in the process definition

### What you expected to happen

All is fine ....

### How to reproduce

As what I mentiond in https://github.com/apache/dolphinscheduler/issues/9068

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by darrkz** [comment]
@SbloodyS

**Comment by SbloodyS** [comment]
Could you take a snapshot and paste it?

**Comment by darrkz** [comment]
> Could you take a snapshot and paste it?

Do you means this content???
```
select * from t_ds_task_definition;
```
```
id                      | 1
code                    | 3855560827328
name                    | curl获取文件
version                 | 2
description             | 
project_code            | 3855559831744
user_id                 | 1
task_type               | SHELL
task_params             | {"resourceList":[],"localParams":[],"rawScript":"curl -I https://dist.apache.org/repos/dist/dev/dolphinscheduler/2.0.1/apache-dolphinscheduler-2.0.1-bin.tar.gz","dependence":{},"conditionResult":{"successNode":[],"failedNode":[]},"waitStartTimeout":{},"switchResult":{}}
flag                    | 1
task_priority           | 2
worker_group            | default
environment_code        | -1
fail_retry_times        | 0
fail_retry_interval     | 1
timeout_flag            | 0
timeout_notify_strategy | 0
timeout                 | 0
delay_time              | 0
resource_ids            | 
create_time             | 2021-12-15 15:06:50.193
update_time             | 2021-12-15 15:09:01.734
```

```
select * from t_ds_process_definition;
```

```
id               | 1
code             | 3855566104640
name             | 简单任务测试
version          | 2
description      | 
project_code     | 3855559831744
release_state    | 0
user_id          | 1
global_params    | []
locations        | [{"taskCode":3855560827328,"x":68,"y":129}]
warning_group_id | 
flag             | 1
timeout          | 1
tenant_id        | 1
execution_type   | 0
create_time      | 2021-12-15 15:06:50.193
update_time      | 2021-12-15 15:09:01.752
```

**Comment by SbloodyS** [comment]
At present, I don't know what is this issue' problem. Can you describe more specifically? @darkz1984

**Comment by darrkz** [comment]
> At present, I don't know what is this issue' problem. Can you describe more specifically? @darkz1984

I upgrade as the issue:  https://github.com/apache/dolphinscheduler/issues/9068

I can find the process_definition.
**I found that I could found nothing in the process_definition from WebUI**
and the log of apiserver shows no error information...

**Comment by SbloodyS** [comment]
> > At present, I don't know what is this issue' problem. Can you describe more specifically? @darkz1984
> 
> I upgrade as the issue: #9068
> 
> I can find the process_definition. **I found that I could found nothing in the process_definition from WebUI** and the log of apiserver shows no error information...

Are you using a Chrome browser? You can try ```F12``` to see if there is any error message on the console.

**Comment by darrkz** [comment]
> > > At present, I don't know what is this issue' problem. Can you describe more specifically? @darkz1984
> > 
> > 
> > I upgrade as the issue: #9068
> > I can find the process_definition. **I found that I could found nothing in the process_definition from WebUI** and the log of apiserver shows no error information...
> 
> Are you using a Chrome browser? You can try `F12` to see if there is any error message on the console.

No errors in the chrome console , all query  status code is 200

The new added process definition is fine...
The definitions exists before upgrade have the problem

**Comment by SbloodyS** [comment]
@darkz1984 Is there an error log in the ```dolphinscheduler-master.log```?

**Comment by darrkz** [comment]
> @darkz1984 Is there an error log in the `dolphinscheduler-master.log`?

I try fresh the webUI, No errors found from the `dolphinscheduler-master.log`

**Comment by SbloodyS** [comment]
> > @darkz1984 Is there an error log in the `dolphinscheduler-master.log`?
> 
> I try fresh the webUI, No errors found from the `dolphinscheduler-master.log`

It' odd...It is difficult to locate the cause of the problem without an error log.

**Comment by darrkz** [comment]
> > > @darkz1984 Is there an error log in the `dolphinscheduler-master.log`?
> > 
> > 
> > I try fresh the webUI, No errors found from the `dolphinscheduler-master.log`
> 
> It' odd...It is difficult to locate the cause of the problem without an error log.

Is there same other ways to debug this???

**Comment by darkz1984** [comment]
I had try restor ds and re-upgrade the it
I found the database version of 2.0.1 should be 2.0.0....
And I can found tasks in procedure.
And I will watch the upgraded server  for days...

**Comment by boy-xiaozhang** [comment]
hi,Can you debug code locally,Try connecting to the production metabase locally

**Comment by boy-xiaozhang** [comment]
Or you can try to use SQL in the dolphinscheduler-dao to query the source database to see if you can query the data

**Comment by darrkz** [comment]
> hi,Can you debug code locally,Try connecting to the production metabase locally

I can connect to the database, but what's the 
```
SQL in the dolphinscheduler-dao
```
?? can you supply that to us??

**Comment by boy-xiaozhang** [comment]
> > hi,Can you debug code locally,Try connecting to the production metabase locally
> 
> I can connect to the database, but what's the
> 
> ```
> SQL in the dolphinscheduler-dao
> ```
> 
> ?? can you supply that to us??

The SQL Mapper.xml file you need is in dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper,
What I suggest is that you can combine the api-doc to find the corresponding SQL, and then query the metabase. At the same time, you can also back up the data to the local, or connect the pro database to the local Debug.

**Comment by darrkz** [comment]
> > > hi,Can you debug code locally,Try connecting to the production metabase locally
> > 
> > 
> > I can connect to the database, but what's the
> > ```
> > SQL in the dolphinscheduler-dao
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ?? can you supply that to us??
> 
> The SQL Mapper.xml file you need is in dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper, What I suggest is that you can combine the api-doc to find the corresponding SQL, and then query the metabase. At the same time, you can also back up the data to the local, or connect the pro database to the local Debug.

I foudn SQL and query in mapper xml files:
dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.xml
queryByDefineId
```
        SELECT
            pd.id, pd.code, pd.name, pd.version, pd.release_state, pd.project_code, pd.user_id, pd.description,
            pd.global_params, pd.flag, pd.locations, pd.warning_group_id, pd.create_time, pd.timeout,
            pd.tenant_id, pd.update_time, u.user_name,p.name AS project_name
        FROM
            t_ds_process_definition pd,
            t_ds_user u,
            t_ds_project p
        WHERE
            pd.user_id = u.id AND pd.project_code = p.code
        AND pd.id = 1
```
returns
```
-[ RECORD 1 ]----+--------------------------------------------
id               | 1
code             | 3855566104640
name             | 简单任务测试
version          | 2
release_state    | 1
project_code     | 3855559831744
user_id          | 1
description      | 
global_params    | []
flag             | 1
locations        | [{"taskCode":3855560827328,"x":68,"y":129}]
warning_group_id | 
create_time      | 2021-12-15 15:06:50.193
timeout          | 1
tenant_id        | 1
update_time      | 2021-12-15 15:09:01.752
user_name        | admin
project_name     | 大数据测试
```

dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationMapper.xml
queryByProcessCode
```
        select
        id, name, process_definition_version, project_code, process_definition_code, pre_task_code, pre_task_version,
        post_task_code, post_task_version, condition_type, condition_params, create_time, update_time
        from t_ds_process_task_relation
        WHERE project_code = 3855559831744
        and process_definition_code = 3855566104640
```
returns
```
-[ RECORD 1 ]--------------+------------------------
id                         | 2
name                       | 
process_definition_version | 2
project_code               | 3855559831744
process_definition_code    | 3855566104640
pre_task_code              | 0
pre_task_version           | 0
post_task_code             | 3855560827328
post_task_version          | 2
condition_type             | 0
condition_params           | {}
create_time                | 2021-12-15 15:09:01.759
update_time                | 2021-12-15 15:09:01.759
```

dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionMapper.xml
queryByCode
```
        select
        id, code, name, version, description, project_code, user_id, task_type, task_params, flag, task_priority,
        worker_group, environment_code, fail_retry_times, fail_retry_interval, timeout_flag, timeout_notify_strategy, timeout, delay_time,
        resource_ids, create_time, update_time
        from t_ds_task_definition
        where code = 3855560827328
```

returns
```
-[ RECORD 1 ]-----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
id                      | 1
code                    | 3855560827328
name                    | curl获取文件
version                 | 2
description             | 
project_code            | 3855559831744
user_id                 | 1
task_type               | SHELL
task_params             | {"resourceList":[],"localParams":[],"rawScript":"curl -I https://dist.apache.org/repos/dist/dev/dolphinscheduler/2.0.1/apache-dolphinscheduler-2.0.1-bin.tar.gz","dependence":{},"conditionResult":{"successNode":[],"failedNode":[]},"waitStartTimeout":{},"switchResult":{}}
flag                    | 1
task_priority           | 2
worker_group            | default
environment_code        | -1
fail_retry_times        | 0
fail_retry_interval     | 1
timeout_flag            | 0
timeout_notify_strategy | 0
timeout                 | 0
delay_time              | 0
resource_ids            | 
create_time             | 2021-12-15 15:06:50.193
update_time             | 2021-12-15 15:09:01.734
```

the tasks query return results is what I defined before upgrade

@boy-xiaozhang
