### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] The new label position of the data source is wrong.

### ISSUE THREAD

**Issue by EricJoy2048** [apache/dolphinscheduler#9101]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

It show a error msg `datasource plugin 'presto' is not found` when create presto datasource.
<img width="613" alt="image" src="https://user-images.githubusercontent.com/32193458/159468212-281b3e8d-034c-4d06-8649-1aa35c383f1b.png">

### What you expected to happen

DataSource Presto plugin can use.

### How to reproduce

Just create a presto datasource .

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Is this the new UI.

**Comment by songjianet** [comment]
I will fix it.
