### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] User token edit bug

### ISSUE THREAD

**Issue by devosend** [apache/dolphinscheduler#9103]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

- Token manage
Token not set null when user change
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/8847400/159478218-74fe7280-ff3c-41fa-bf24-978f59ce3586.png">

### What you expected to happen

token set null

### How to reproduce

above

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.
