### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]  Upstream Tasks field UI display extra long

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9113]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Upstream Tasks field UI display extra long

<img width="1917" alt="image" src="https://user-images.githubusercontent.com/76080484/159622481-5f5920a4-2e98-49fb-bc38-e70231a76817.png">

### What you expected to happen

Display effect can be super long hidden, mouse hover to show the details

### How to reproduce

Entering Task Definition will show

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.
