### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] id list error

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#9125]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/11962619/159648534-1f4c9e3c-a53c-4a74-aec9-42b485858383.png)

need to use the id as the first col.

### What you expected to happen

show list normally.

### How to reproduce

just run some workflow and list it.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
At present, this column refers to the index of the total number of entries in the table, not a specific piece of data. This is also implemented in the old UI. Usually, displaying an ID is not very useful.
