### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] shell task custom parameters lost IN and OUT direction

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#9126]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/11962619/159649293-33d45963-abe2-4000-88c3-c25ccd55c83c.png)

### What you expected to happen

see doc: https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/task/shell.html

### How to reproduce

create shell task

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
This issue is the same as #9073
