### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] The logging component is still the same old UI

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9136]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The logging component is still the same old UI

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/76080484/159672962-8747c37e-a0d9-4230-8d1b-329fd82b353a.png">

### What you expected to happen

Logging component switched to new UI

### How to reproduce

Workflow Instance Modules

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
A log component will be written uniformly in the future.
