### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha]Time zone display error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9137]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Time zone display error

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/76080484/159675337-0eaa1c0e-7555-41f5-ab9c-238d447b5ca4.png">

### What you expected to happen

Time zone change after the system display time, log time at the same time qie

### How to reproduce

Time zone display error

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
I can't reproduce this issue in local. @XuXuClassMate

**Comment by XuXuClassMate** [comment]
> I can't reproduce this issue in local. @XuXuClassMate

Occasional problem, I had it twice on ds2，It is usually the first time you enter the system after deployment
