### ISSUE TITLE
[Bug-RD[UI Next][V1.0.0-Alpha]task executed successfully, but no log message is displayed

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9138]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

task executed successfully, but no log message is displayed

<img width="1913" alt="image" src="https://user-images.githubusercontent.com/76080484/159676566-81b6cb36-e8e9-40d5-a591-9b011c12072d.png">

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/76080484/159676661-72bebf74-ffd3-47b0-929a-c4bfa6c58874.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/76080484/159676725-8d953b2b-448a-41dd-b0fa-8d7af8789fc8.png">

### What you expected to happen

Execution successful, log printing successful

### How to reproduce

1、Execution workflow
2、The first task of the workflow is executed successfully
3, click Task Instance to view the log, the log display is empty

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
please check log level.
