### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] Execute the workflow successfully click on the task instance to enter the page is blank

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9139]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Execute the workflow successfully click on the task instance to enter the page is blank

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/76080484/159691167-7f801292-c01a-45e4-80da-f16e9a4c13fd.png">

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/76080484/159691340-f8628639-e3ee-4783-a5de-2422bc32be6d.png">

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/76080484/159691962-d08b6db2-8605-4cd9-8eac-e71c230068e0.png">

Meanwhile, the back-end api service reports an error

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/76080484/159691478-e0962483-c0d6-484d-ba94-c162f19da6a4.png">

### What you expected to happen

Access to the task instance can be displayed normally

### How to reproduce

1、Execution workflow
2、Click on the task example
Task instance page is empty

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it

**Comment by devosend** [comment]
This issue is same as #9145
