### ISSUE TITLE
When the processInstance invoke endProcess(),not need judge the state is "WAITTING_THREAD"

### ISSUE THREAD

**Issue by zhoushuoqi22** [apache/dolphinscheduler#914]
When the process instance invoke **endProcess()**, there is no need to judge that state is **WAITTING_THREAD**. Because only construct process instance from command, the processInstance state may be set ** WAITTING_THREAD**.

当流程实例执行endProcess()时，不需要再判断它是不是**等待线程**状态。因为只有根据command生成processInstance时，才可能会将processInstance状态设置为**等待线程**。

```java
private void endProcess() {
    ...
    if(processInstance.getState().typeIsWaittingThread()){
        processDao.createRecoveryWaitingThreadCommand(null, processInstance);
    }
    ...
}
```

**Comment by dailidong** [comment]
good job!
