### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]（Important）Click to view workflow examples or edit workflow backend error reports

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9145]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Click to view workflow examples or edit workflow backend error reports

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/76080484/159836766-0519fada-518a-46a1-8af9-a6b24394dabe.png">

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/76080484/159836626-f03e4f90-39c2-44c7-abbe-861f76ec7793.png">

### What you expected to happen

Click or edit the workflow to edit or view it normally

### How to reproduce

**Click to view workflow examples or edit workflow backend error reports**

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
![image](https://user-images.githubusercontent.com/11962619/159856907-9901b1f3-a947-40a3-b5a4-571acc34a6c8.png)
I found that this issue was abot setting task params without default value, in the next-ui, value is null, but I found the 2.0.6 version, value is "". PTAL @songjianet

**Comment by devosend** [comment]
I will fix it
