### ISSUE TITLE
[Bug] [Module Name] Caused by: org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 2

### ISSUE THREAD

**Issue by momomobinx** [apache/dolphinscheduler#9150]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

tar -zxvf apache-dolphinscheduler-2.0.5-src.tar.gz
cd apache-dolphinscheduler-2.0.5-src/docker/docker-swarm
docker pull dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler:latest
docker-compose up 

loop:
dolphinscheduler-master_1      | [ERROR] 2022-03-24 14:45:49.903 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[243] - handler error:
dolphinscheduler-master_1      | org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 2
dolphinscheduler-master_1      | 	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:78)
dolphinscheduler-master_1      | 	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
dolphinscheduler-master_1      | 	at com.sun.proxy.$Proxy87.selectOne(Unknown Source)
dolphinscheduler-master_1      | 	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:159)
dolphinscheduler-master_1      | 	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:89)
dolphinscheduler-master_1      | 	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
dolphinscheduler-master_1      | 	at com.sun.proxy.$Proxy111.queryByDefinitionCodeAndVersion(Unknown Source)
dolphinscheduler-master_1      | 	at sun.reflect.GeneratedMethodAccessor221.invoke(Unknown Source)
dolphinscheduler-master_1      | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
dolphinscheduler-master_1      | 	at java.lang.reflect.Method.invoke(Method.java:498)
dolphinscheduler-master_1      | 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
dolphinscheduler-master_1      | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
dolphinscheduler-master_1      | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
dolphinscheduler-master_1      | 	at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:54)
dolphinscheduler-master_1      | 	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:366)
dolphinscheduler-master_1      | 	at org.springframework.cache.interceptor.CacheAspectSupport.lambda$handleSynchronizedGet$1(CacheAspectSupport.java:447)
dolphinscheduler-master_1      | 	at org.springframework.cache.support.NoOpCache.get(NoOpCache.java:76)
dolphinscheduler-master_1      | 	at org.springframework.cache.interceptor.CacheAspectSupport.handleSynchronizedGet(CacheAspectSupport.java:442)
dolphinscheduler-master_1      | 	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:382)
dolphinscheduler-master_1      | 	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345)
dolphinscheduler-master_1      | 	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:64)
dolphinscheduler-master_1      | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
dolphinscheduler-master_1      | 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
dolphinscheduler-master_1      | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
dolphinscheduler-master_1      | 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
dolphinscheduler-master_1      | 	at com.sun.proxy.$Proxy112.queryByDefinitionCodeAndVersion(Unknown Source)
dolphinscheduler-master_1      | 	at org.apache.dolphinscheduler.service.process.ProcessService.findTaskDefinition(ProcessService.java:2474)
dolphinscheduler-master_1      | 	at org.apache.dolphinscheduler.service.process.ProcessService.lambda$getTaskDefineLogListByRelation$4(ProcessService.java:2465)
dolphinscheduler-master_1      | 	at java.util.HashMap.forEach(HashMap.java:1290)
dolphinscheduler-master_1      | 	at org.apache.dolphinscheduler.service.process.ProcessService.getTaskDefineLogListByRelation(ProcessService.java:2464)
dolphinscheduler-master_1      | 	at org.apache.dolphinscheduler.service.process.ProcessService$$FastClassBySpringCGLIB$$ed138739.invoke(<generated>)
dolphinscheduler-master_1      | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
dolphinscheduler-master_1      | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
dolphinscheduler-master_1      | 	at org.apache.dolphinscheduler.service.process.ProcessService$$EnhancerBySpringCGLIB$$24451e9d.getTaskDefineLogListByRelation(<generated>)
dolphinscheduler-master_1      | 	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.buildFlowDag(WorkflowExecuteThread.java:554)
dolphinscheduler-master_1      | 	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.startProcess(WorkflowExecuteThread.java:518)
dolphinscheduler-master_1      | 	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread.run(WorkflowExecuteThread.java:238)
dolphinscheduler-master_1      | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
dolphinscheduler-master_1      | 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
dolphinscheduler-master_1      | 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
dolphinscheduler-master_1      | 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
dolphinscheduler-master_1      | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
dolphinscheduler-master_1      | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
dolphinscheduler-master_1      | 	at java.lang.Thread.run(Thread.java:750)
dolphinscheduler-master_1      | Caused by: org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 2
dolphinscheduler-master_1      | 	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:80)
dolphinscheduler-master_1      | 	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
dolphinscheduler-master_1      | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
dolphinscheduler-master_1      | 	at java.lang.reflect.Method.invoke(Method.java:498)
dolphinscheduler-master_1      | 	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
dolphinscheduler-master_1      | 	... 42 common frames omitted

### What you expected to happen

run job ..

### How to reproduce

tar -zxvf apache-dolphinscheduler-2.0.5-src.tar.gz
cd apache-dolphinscheduler-2.0.5-src/docker/docker-swarm
docker pull dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler:latest
docker-compose up 

### Anything else

version 2.0.3 version 2.0.5

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by momomobinx** [comment]
docker-compose down 
docker volume ls | grep 'dolphinscheduler' | awk '{print $2}' | xargs docker volume rm
docker-compose up
之前没有完全清除就部署，完全清理后重新部署就没有出现了

**Comment by momomobinx** [comment]
还是没有解决，我创建两个http节点后，又报了相同的错误
Still no solution, after I created two http nodes, the same error was reported again

**Comment by momomobinx** [comment]
> 

@songjianet

**Comment by thirdparty-core** [comment]
在线等，我也出现了这个问题

**Comment by momomobinx** [comment]
> 在线等，我也出现了这个问题

我是临时的到数据库中吧重复的删除了

**Comment by yxydde** [comment]
什么时候能好？

**Comment by momomobinx** [comment]
> 什么时候能好？

我感觉是前端的问题，点击保存工作流的时候双击了这类的保存了两次，或者数据库设定唯一值约束才行

**Comment by Flutemr** [comment]
> > 在线等，我也出现了这个问题
> 
> 我是临时的到数据库中吧重复的删除了

兄弟，删除数据库中哪个表数据，我现在就是遇到这个问题

**Comment by momomobinx** [comment]
> 



> > > 在线等，我也出现了这个问题
> > 
> > 
> > 我是临时的到数据库中吧重复的删除了
> 
> 兄弟，删除数据库中哪个表数据，我现在就是遇到这个问题

task_definxxx_log  还是啥的 ，然后你 group by code version 然后看一下数量大于 1 的就是重复的

**Comment by Flutemr** [comment]
> > 
> 
> > > > 在线等，我也出现了这个问题
> > > 
> > > 
> > > 我是临时的到数据库中吧重复的删除了
> > 
> > 
> > 兄弟，删除数据库中哪个表数据，我现在就是遇到这个问题
> 
> task_definxxx_log 还是啥的 ，然后你 group by code version 然后看一下数量大于 1 的就是重复的

好的，谢谢。。看到其他帖子知道在哪个表重复了。
