### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] shell componentTwo fields are missing

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9155]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

shell component Two fields are missing

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/76080484/159862359-0ef61b09-a38c-4c5c-b0f8-2d77e3e39f60.png">

<img width="377" alt="image" src="https://user-images.githubusercontent.com/76080484/159862049-7d35af00-a4ca-4020-91ef-edfdd7c8970a.png">

### What you expected to happen

Consistency with other components

### How to reproduce

Two fields are missing

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
This issue is the same as #9073 .
