### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha]A different type of data source is added, and the monitor returns a data source message

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9159]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

A different type of data source is added, and the monitor returns a data source message

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/76080484/159870924-cc5aae5d-1eef-425b-bc4f-4b73d78ff218.png">

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/76080484/159871306-fae867d5-a8d5-4ce9-b6f0-6d83a25c31c0.png">

### What you expected to happen

The added data source information is returned in the db monitor

### How to reproduce

A different type of data source is added, and the monitor returns a data source message

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I'd like to check it out. Please assign this issue to me.

**Comment by calvinjiang** [comment]
I've checked that out and make sure that these metrics are just all about the back-end database of the dolphinscheduler. The page of datasource management is used to manage some datasources for tasks. There are no any problems about these metrics. So I'll close this issue.
