### ISSUE TITLE
[Bug-FE] [UI Next] [V1.0.0-Alpha] Error opening home page 

### ISSUE THREAD

**Issue by aiwenmo** [apache/dolphinscheduler#9162]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Error opening home page.
![image](https://user-images.githubusercontent.com/32723967/159877451-d9677899-9537-4385-b22e-79e1244dc697.png)

### What you expected to happen

I found the reason, my google chrome timezone is not in the timezoneList.
![image](https://user-images.githubusercontent.com/32723967/159877792-4827f9fc-75c6-4896-9252-c0ef6b430d59.png)

### How to reproduce

The default value, such as' UTC ', is used when the time zone does not exist.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback. Please check https://github.com/apache/dolphinscheduler/issues/9160.
