### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] Shell task missing in and varchar option

### ISSUE THREAD

**Issue by devosend** [apache/dolphinscheduler#9164]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

- Shell task Custom Parameters missing `IN` and `VARCHAR` option
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/8847400/159882015-3f9f5ffb-d850-4377-9c6c-9264a8ce67fd.png">

### What you expected to happen

above

### How to reproduce

above

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
This issue is same as #9073
