### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]The connection line should be centered before the task

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9168]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The connection line should be centered before the task

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/76080484/159890476-de288e99-42dc-4e6c-b1a6-61e27ee975aa.png">

### What you expected to happen

The connection line should be centered before the task

### How to reproduce

The connection line should be centered before the task

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
