### ISSUE TITLE
[Bug] [UI Next] Alert instance data form issues

### ISSUE THREAD

**Issue by Tianqi-Dotes** [apache/dolphinscheduler#9172]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

2 main problems:
1. If I have created 10 instances of different types, the email username and password will display on other different types of instances' proxy username and password column.
2. If there already have on email or the same type of instance, when I create a new one, the old data will display on the new create form. If I make some changes on the new created instance, it also influences the old one when you click edit.
In conclusion, It's wired in this alert instance part. Data seems display in the wrong places they shouldn't in.

### What you expected to happen

All data display in right place.

### How to reproduce

1.create one email instance and fill in the username and password, create other types of instance and leave the proxy part in blank. The email username and password will show in others' proxy part.
2. create a type instance that already exists, the form will be the same with the old one. and if you make any changes will influence the old one.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I'll check it out.

**Comment by devosend** [comment]
I will fix it
