### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] workflow name Extra-long display

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9184]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

workflow name Extra-long display

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/76080484/160054102-837fc178-175e-4cbc-a34f-8180f3d60452.png">

### What you expected to happen

Extra long hidden or name length limit

### How to reproduce

workflow name Extra-long display

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by labbomb** [comment]
i will fix it
