### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]Time zone display error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9188]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Time zone display error

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/76080484/160079914-3b8fb5e8-d9c7-41ce-8f50-f3777929dcfa.png">

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/76080484/160079981-6c60bf72-ee64-4fac-976b-b09738c0af33.png">

### What you expected to happen

The time zone is displayed correctly

### How to reproduce

Set the time zone to be Shanghai and confirm to be UTC-4

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
>Set the time zone to be Shanghai and confirm to be UTC-4

Is this the full steps to reproduce? @XuXuClassMate

**Comment by XuXuClassMate** [comment]
> 

yes~

**Comment by devosend** [comment]
I will fix it.
