### ISSUE TITLE
[Feature][alert] add AlertStatus entity

### ISSUE THREAD

**Issue by huagetai** [apache/dolphinscheduler#9204]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Alert and AlertPluginInstance are 1:N. The alert status will be updated after the alert is sent. Sending to multiple AlertPluginInstances will cause the alarm status to overwrite each other.

Add AlertStatus entity. Each time the transmission is successful, an alarm status is added.

The status in the alert: all success, partial success, all failure.

AlertStatus is the detail. include: alertId, alertPluginInstanceId, status, statusMessage.

### Use case

the alert status is more accurate and detailed

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
Thanks @huagetai  This is a good idea.
