### ISSUE TITLE
[Bug] [ui-next] Missing function: Serial execte proces

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#9206]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

There is a missing function: Serial execte proces
https://github.com/apache/dolphinscheduler/pull/6267

### What you expected to happen

add the function in ui: 'serial execte proces'

### How to reproduce

https://github.com/apache/dolphinscheduler/pull/6267

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
