### ISSUE TITLE
[Bug] [ui-next] sqoop task cannot select datasource 

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#9209]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. I cannot select any datasources in the sqoop task(default).

![image](https://user-images.githubusercontent.com/29528966/160263944-a6fc003c-79e9-4256-866f-987182d7dee4.png)

2. data target cannot select the hdfs file path(default):

![image](https://user-images.githubusercontent.com/29528966/160263975-9d0dfa6e-04f0-4b67-885f-8555bb8b3938.png)

### What you expected to happen

1.  create sqoop task (default):
![image](https://user-images.githubusercontent.com/29528966/160264015-abb87fc2-991d-4751-9b1e-fb5d08184b7a.png)

2. data target - HDFS(default):
![image](https://user-images.githubusercontent.com/29528966/160264026-2612d201-aae0-4fa9-b955-30afe5693b34.png)
3. data target - HIVE:
![image](https://user-images.githubusercontent.com/29528966/160264056-aa522754-1913-4bc4-ad4e-bd88f86b7af6.png)

### How to reproduce

create a sqoop task

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will fix it.
