### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha] UDF upload file error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9213]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

**UDF upload file error**

error massage:create resource error

<img width="809" alt="image" src="https://user-images.githubusercontent.com/76080484/160265255-31308766-dc9d-4e7d-8549-891731f9e6c1.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/76080484/160265221-1d566a59-f0ca-4560-8aaa-a8b6c69fd9ae.png">

### What you expected to happen

Successfully uploaded

### How to reproduce

Click to upload UDF
Select file
Click on Confirm

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
