### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha] Task group instance list shows duplicates

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9216]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

**Task group instance list shows duplicates**

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/76080484/160272309-77fd5765-1214-4dd7-b766-bc8ca4ae7ee2.png">

### What you expected to happen

Task group instance list display de-duplication display

### How to reproduce

Task group instance list shows duplicates

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
![image](https://user-images.githubusercontent.com/36755957/162930054-b34a92d6-2c3d-4cea-be54-fda8f35c96b4.png)
This is not duplicated, the reason it looks duplicated is due to using the same task name.
