### ISSUE TITLE
[Bug] [dev] version in pom.xml of dev branch confusing 

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#9223]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

* `version` in pom.xml of dev branch is confusing. After building the source code, we get apache-dolphinscheduler-2.0.4-SNAPSHOT-xxx.  
* ![image](https://user-images.githubusercontent.com/34905992/160283274-0b1a345d-e144-4bb7-8334-5e08efd94c2f.png)

### What you expected to happen

* We could change `version` in pom.xml of dev branch to `dev-SNAPSHOT`

### How to reproduce

* Build the src code and `cd dolphin-scheduler/dolphinscheduler/dolphinscheduler-dist/target`, you will see related output stuff all in version `2.0.4-SNAPSHOT`.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
* After I switched `2.0.4-SNAPSHOT` to `dev-SNAPSHOT` in all pom.xml files in the project, I recompile the project with cmd `mvn -U install package -Prelease -Dmaven.test.skip=true`. 
* However, I get some error like `org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2:single (make-assembly) on project dolphinscheduler-data-quality: Failed to create assembly: Error creating assembly archive jar-with-dependencies: Problem creating jar: JAR entry log4j.properties not found in .........../dolphin-scheduler/dolphinscheduler/dolphinscheduler-data-quality/target/archive-tmp/dolphinscheduler-data-quality-dev-SNAPSHOT.jar
`
* That's really wired. I didn't changed anything else besides the version number. Any help will be appreciated. @caishunfeng

**Comment by caishunfeng** [comment]
> * After I switched `2.0.4-SNAPSHOT` to `dev-SNAPSHOT` in all pom.xml files in the project, I recompile the project with cmd `mvn -U install package -Prelease -Dmaven.test.skip=true`.
> * However, I get some error like `org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2:single (make-assembly) on project dolphinscheduler-data-quality: Failed to create assembly: Error creating assembly archive jar-with-dependencies: Problem creating jar: JAR entry log4j.properties not found in .........../dolphin-scheduler/dolphinscheduler/dolphinscheduler-data-quality/target/archive-tmp/dolphinscheduler-data-quality-dev-SNAPSHOT.jar `
> * That's really wired. I didn't changed anything else besides the version number. Any help will be appreciated. @caishunfeng

@EricGao888 can you submit a pr? and then I will have a try at local

**Comment by EricGao888** [comment]
> > * After I switched `2.0.4-SNAPSHOT` to `dev-SNAPSHOT` in all pom.xml files in the project, I recompile the project with cmd `mvn -U install package -Prelease -Dmaven.test.skip=true`.
> > * However, I get some error like `org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2:single (make-assembly) on project dolphinscheduler-data-quality: Failed to create assembly: Error creating assembly archive jar-with-dependencies: Problem creating jar: JAR entry log4j.properties not found in .........../dolphin-scheduler/dolphinscheduler/dolphinscheduler-data-quality/target/archive-tmp/dolphinscheduler-data-quality-dev-SNAPSHOT.jar `
> > * That's really wired. I didn't changed anything else besides the version number. Any help will be appreciated. @caishunfeng
> 
> @EricGao888 can you submit a pr? and then I will have a try at local

I've submitted the PR, not sure where I got things wrong, lol. @caishunfeng
