### ISSUE TITLE
[Bug] [ALERT] Wechat alert not working

### ISSUE THREAD

**Issue by Tianqi-Dotes** [apache/dolphinscheduler#9224]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Configure everything to WeChat alert but not working and the WeChat alert document part with no help at all.

### What you expected to happen

Configure the Wechat alert instance and post an alert to Wechat.

### How to reproduce

Just config and make the alert group to your workflow to send results.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
@Tianqi-Dotes please link this issue to the pr if you had submitted.
