### ISSUE TITLE
[Bug] [ui-next] The datasource cannot display after saving once.

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#9226]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I select a hive datasource, the datasource cannot display after saving once.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/29528966/160317314-b936e87e-a091-4ce1-9d9c-c23de939bb47.png">

### What you expected to happen

The data source can be displayed correctly.

### How to reproduce

1. create sql task , select one datasource (hive)
2. save the process definition
3. open the process definition, click the sql task, the datasource cannot be display.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
@lenboo seems the upload image can not show.

**Comment by github-lay** [comment]
what version do you use?
