### ISSUE TITLE
[Feature][Presto DataSource Plugin] presto datasource plugin need support trino

### ISSUE THREAD

**Issue by EricJoy2048** [apache/dolphinscheduler#9231]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Prestosql rename to trino after version 353, And the jdbc url format update to `jdbc:trino` and the driver jar need replace .
I think we the Presto DataSource Plugin need support both `Presto` and `Trino` .

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
All ```prestosql``` classes are rename to ```trino``` after ```trino 350```.

In my opinion, we should add a new ```Trino``` datasource to distinguish ```prestosql```and ```Trino```, so as to prevent the difference between them from becoming larger in the future, and then split it, resulting in higher user migration costs.

**Comment by EricJoy2048** [comment]
> All `prestosql` classes are renanme to `trino` after `trino 350`.
> 
> In my opinion, we should add a new `Trino` datasource to distinguish `prestosql`and `Trino`, so as to prevent the difference between them from becoming larger in the future, and then split it, resulting in higher user migration costs.

Ok, 100% agree.

**Comment by heyzeng** [comment]
I have implemented this feature and used it in a production environment，can i pr this feature？

**Comment by jtao3212** [comment]
> I have implemented this feature and used it in a production environment，can i pr this feature？
expect

**Comment by SbloodyS** [comment]
> I have implemented this feature and used it in a production environment，can i pr this feature？

Sure. I've assigned to you. Looking forward to your contribution. :)

**Comment by Gqyanxin** [comment]
Is there any progress？I have also implemented this function and already using it. Maybe I can pr this function.

**Comment by Gqyanxin** [comment]
I have implemented this function based on 3.x, do 2.x also need it?
