### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] Task Definition page demonstrator display error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9232]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/76080484/160316346-9dd1c455-9386-466f-bebd-f4cc7f95e189.png">

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/76080484/160316486-3206b536-ea2e-4638-9777-74b71f9f5606.png">

### What you expected to happen

Task Definition page demonstrator shows normal

### How to reproduce

click Task Definition 

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it

**Comment by devosend** [comment]
This seems to be a backend problem.

**Comment by Tianqi-Dotes** [comment]
will check it out soon

**Comment by Tianqi-Dotes** [comment]
PR have merged
refer to https://github.com/apache/dolphinscheduler/pull/9354
