### ISSUE TITLE
[Fix] [FE] need to fix frontend according to wechat changes

### ISSUE THREAD

**Issue by Tianqi-Dotes** [apache/dolphinscheduler#9235]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The wechat code and logical process are deprecated and need to change to the new process, so need to change some form columns at frontend.

### What you expected to happen

1. Delete * 群员信息,
2. Hint 'use '|' to separate userIds and '@all' to all users' at * 群员.
3. Change JSON key name to 'chatId' when select group chat.
4. Hide * 群员 when using gropu chat.

### How to reproduce

create a wechat alert instance

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
@devosend PTAL

**Comment by devosend** [comment]
I will fix it

**Comment by Amy0104** [comment]
I'll follow up on this issue.

**Comment by Amy0104** [comment]
This form is generated based on back-end data.

**Comment by Tianqi-Dotes** [comment]
will do this issue

**Comment by Tianqi-Dotes** [comment]
code check https://github.com/apache/dolphinscheduler/pull/9367
doc check https://github.com/apache/dolphinscheduler/pull/9439
