### ISSUE TITLE
[Feature] [UI-Next] [V1.0.0-Alpha] Search box confirm operation can be triger by pressing enter button.

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#9238]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![](https://vip1.loli.io/2022/03/28/O7R5yeZVg8Ew3rq.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
This function still needs to be investigated, but this function does not seem to be very urgent.

**Comment by SbloodyS** [comment]
> This function still needs to be investigated, but this function does not seem to be very urgent.

Yes, it's not very urgent.

**Comment by songjianet** [comment]
I thought about this function for a while. At this stage, we have a code editor component in the pop-up window. It is allowed to use the `enter` button in the code editor, which will cause a certain conflict with the confirmation button of the pop-up window, so this function cannot be used for the time being.
