### ISSUE TITLE
[Bug] [Breaking Observability With SkyWalking] The SkyWalking's UI template is going to be broken

### ISSUE THREAD

**Issue by wu-sheng** [apache/dolphinscheduler#9242]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

SkyWalking v9 is coming to be mainstream very soon, the plan is 2 weeks later.

https://twitter.com/ASFSkyWalking/status/1508368920935550980

You could see from this preview, there is no menu for DolphinScheduler anymore, as right now, we treat important components(k8s, mesh, function) as separate menus(k8s, mesh, serverless, etc.). But we/I don't know where to put DolphinScheduler, as it is using SkyWalking's agent, but custom metrics.

So, I am not sure what DolphinScheduler community prefers? 

### What you expected to happen

At least to update the doc to announce this break on the doc, it is only working on v8.

### How to reproduce

No

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Any update from the community?

**Comment by davidzollo** [comment]
I think DS can't use SkyWalking, we will remove the related docs later  @zhongjiajie

**Comment by wu-sheng** [comment]
OK, if you want to discuss scheduler dashboard from a standard perspective, or we could provide one dashboard for Airflow and DolphinScheduler

**Comment by zhongjiajie** [comment]
I will remove the docs later(or maybe just add some notice about the supported version for skywalking)

**Comment by zhongjiajie** [comment]
We remove the related docs and this issue is closed. cc: @wu-sheng
