### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]Data source types and data source examples  Showing errors

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9254]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Data source types and data source examples Showing errors

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/76080484/160551274-1ffd42d5-af3d-4fc0-ad1c-6af0bfc05410.png">

### What you expected to happen

Show the last time I saved database information

### How to reproduce

I edit and save the database for sqlserver, click save workflow, edit again when the component shows the default mysql database, not show the database type and database I set last time

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will fix it.
