### ISSUE TITLE
[Bug-FE][UI Next] Can't select start date and end date when COMPLEMENT_DATA

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#9255]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/11962619/160555054-3d912ec4-02d4-4cc1-acb4-c06bdd2fb095.png)

Google Chrome version 98.0.4758.80

### What you expected to happen

COMPLEMENT_DATA successfully.

### How to reproduce

create a workflow and run COMPLEMENT_DATA

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will fix it.

**Comment by Amy0104** [comment]
It seems to be a problem with the date picker component of naive ui.

**Comment by songjianet** [comment]
I've contacted the developers at NaiveUI, and we can't deal with this until they confirm and fix it.
