### ISSUE TITLE
[Bug-FE][UI Next] Can't copy the process instance name

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#9256]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Can't copy the process instance name
![image](https://user-images.githubusercontent.com/11962619/160558769-87aab1ea-b10d-4b96-8c31-ce5ba539e5c2.png)

![image](https://user-images.githubusercontent.com/11962619/160562020-a78dd8a8-3ea7-4764-9b42-8c8038334ad5.png)

### What you expected to happen

can copy instance name easily.

### How to reproduce

create a workflow and run

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
i will fix it

**Comment by songjianet** [comment]
This problem cannot be reproduced in the local environment and the nginx environment. Can you provide a reproduced environment?

**Comment by Amy0104** [comment]
This problem seems to be a browser permissions issue, I got a denied state when I printed the clipboard_read permission in the dev tools.
