### ISSUE TITLE
[Bug][UI Next] Floating full-name display needed for menu bar

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#9260]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://user-images.githubusercontent.com/34905992/160572706-8eb691d6-b6cd-498f-a86b-72aaf339cdd6.png)
* Maybe because timezone feature is added, currently there are more English letters on the menu bar, which results in some of the letters omitted. 
* However, on the menu bar below `Project List`, there's some kind of `front-end hover stuff`. When the cursor hovers around, there will be floating full-name display.
* IMHO, we should add the same feature for the menu bar on the top for consistency in UI-design.

### Use case

* Already described in the above `Description` section.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will handle this.
