### ISSUE TITLE
[Bug] [UI-Next] [V1.0.0-Alpha] Magic status display

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#9262]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![](https://vip2.loli.io/2022/03/29/ms8byfFTBXS1Jep.gif)

### What you expected to happen

above.

### How to reproduce

create a running process and task.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
hhhh

**Comment by Amy0104** [comment]
I will fix it.
