### ISSUE TITLE
[Bug] [Server] Too many open file

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#9270]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I run workflow concurrently, I found that error log `too many open file` and master-server can not work continue.
![image](https://user-images.githubusercontent.com/11962619/160625320-31eab858-68cb-4542-893e-2e44ef37fa00.png)

The reason is that too many task log file was created by master-server.

### What you expected to happen

server can work continuously.

### How to reproduce

create a workflow with a easy shell task, and then run concurrently until over the system ulimit.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by huagetai** [comment]
set open files to 65535

**Comment by caishunfeng** [comment]
> set open files to 65535

Thanks your reply. I check by `ulimit -n` and it's 65535.
