### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha]the time zone in the log is displayed incorrectly. One hour ahead of the standard time zone

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9276]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Select time zone, the time zone in the log is displayed incorrectly. One hour ahead of the standard time zone

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/76080484/160757680-7eda9752-6a15-47a5-8f63-053a715d3afe.png">

<img width="1914" alt="image" src="https://user-images.githubusercontent.com/76080484/160757998-7b8942d4-9392-4a4d-b55d-04107ddb65da.png">

### What you expected to happen

The time zone is displayed correctly in the logs

### How to reproduce

Select time zone, the time zone in the log is displayed incorrectly. One hour ahead of the standard time zone

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
@XuXuClassMate please set the timezone config in dolphinscheduler_env.sh.
