### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]Submit button is not clickable

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9278]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Password change is complete.Submit button is not clickable

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/76080484/160762237-93d67e1d-28f4-4897-aef0-93583ef21bd8.png">

### What you expected to happen

Change the password, enter the completion, you can click submit

### How to reproduce

<img width="1913" alt="image" src="https://user-images.githubusercontent.com/76080484/160762544-f72a65fa-037c-49d0-aa6a-a0b5f2a75c04.png">

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
i will fix it

**Comment by labbomb** [comment]
How did you reproduce it. @XuXuClassMate

**Comment by songjianet** [comment]
This is a problem caused by the browser remembering the password, which can be solved by clicking the input box or clicking the button twice.
