### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]personal information did not return to edit the previous state

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9280]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

personal information did not return to edit the previous state

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/76080484/160763375-254ef31c-e80b-4255-b9a0-3dec271fe35a.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/76080484/160763473-7df3ceae-6fd2-40f8-896a-3b2c637166a9.png">

### What you expected to happen

Reopen the personal information editor to revert to the previous state of editing

### How to reproduce

Click to modify personal information, modify failed, open again, personal information did not return to edit the previous state

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it
