### ISSUE TITLE
[Feature][worker] make workers completely independent of the database

### ISSUE THREAD

**Issue by huagetai** [apache/dolphinscheduler#9283]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

IMO, the worker server is independent of the database.
ATM is dependent.
Besides TaskPluginManager, are there any other functions that depend on the database?
If the specific task is not dependent, the changes will not be too much.

### Use case

make workers completely independent of the database

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
@zhuangchong can you take a look and give some suggestion?

**Comment by zhuangchong** [comment]
@huagetai 
Currently the worker server is completely independent of the database. Maybe I didn't understand what you said. Would you like to express your design plan and ideas?

**Comment by huagetai** [comment]
@zhuangchong 

ATM:
```java
public class TaskExecuteThread implements Runnable, Delayed {
    ...
     @Override
      public void run() {
           ...
           TaskChannel taskChannel = taskPluginManager.getTaskChannelMap().get(taskExecutionContext.getTaskType());
           ...
      }
}

@Component
public class TaskPluginManager {
    ....
     private final PluginDao pluginDao;
     ....
}

```

In addition, due to the dependence on the dolphinscheduler-service package, spring will automatically inject the datasource

<img width="1529" alt="截屏2022-03-30 下午6 32 32" src="https://user-images.githubusercontent.com/1137341/160812071-c6a893dd-2eb3-42cd-9c84-7d11b6556aaa.png">
