### ISSUE TITLE
[Feature][UI] add new state of DISPATCH

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#9289]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

add new task state of DISPATCH.

related pr: #8719

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will handle this.

**Comment by fhygh** [comment]
@caishunfeng what's the reason need to add dispatch state?now we uing dolphinscheduler 3.0, there are many task is DISPATCH state, while when we using dolphinscheduler 2.0.x, it's ok. can you help explain and tell how to resolve this problem? thank you.
