### ISSUE TITLE
[Bug] [t_ds_relation_project_user] Duplicate data exists

### ISSUE THREAD

**Issue by ghost** [apache/dolphinscheduler#9290]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Duplicate data exists in the database when authorizing projects to users;
There is a cache when writing, suspected to write the first project  repeatedly
![image](https://user-images.githubusercontent.com/52615903/160808415-d67ee38c-035e-412f-87ce-b244823fb9b2.png)

![image](https://user-images.githubusercontent.com/52615903/160809161-f614da97-40ec-4de4-81b4-50f69ee24230.png)

### What you expected to happen

when authorizing projects to users

### How to reproduce

authorizing projects to users，When an item is selected and then deleted and then selected again

### Anything else

nothing

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leiwingqueen** [comment]
I try to fix the problem.[PR:9536](https://github.com/apache/dolphinscheduler/pull/9536)
