### ISSUE TITLE
[Feature][Workflow Permission] Process sharing to others supports permission assignment

### ISSUE THREAD

**Issue by mextb1860** [apache/dolphinscheduler#9294]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

DolphinScheduler  跨项目依赖流程，目前是通过共享来实现的，但共享其他人以后，其他人就可以修改这个流程的权限，权限应该细化一点比如支持，依赖，查看，修改。

### Use case

比如在数据中台项目中，有专门的接入组，模型组，上层应用组，分别是有不同的分工，接入组负责ods层项目做数据的接入，模型组负责dwd，dws，dim层项目开发，上层应用组负责ads层的集市开发，ods对dwd，dws，dim进行开放共享（依赖ods），但是不允许修改的，dwd，dws，dim对ads层进行开放共享（依赖模型层），但是不允许修改的，这里就存在夸项目工作流的依赖情况了，不同组对不同层需要做到权限控制。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
@mextb1860 please use English desctiption of this issue, which can let more developers know.
BTW, I add the `discussion` label.
