### ISSUE TITLE
[Bug] [Master] repeated submit task

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#9295]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/11962619/160961599-2e83ba72-d0d3-41af-b509-2edca70747ff.png)

### What you expected to happen

every task submit once.

### How to reproduce

![image](https://user-images.githubusercontent.com/11962619/160961554-35f7cf4a-720c-4e34-96aa-09d8fb602aec.png)

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by guoshupei** [comment]
Hi, @caishunfeng , I read the code you modified, I think you solved the problem of concurrent execution of `TaskEvent`, but not solved the problem of repeated submit task, it will still repeat generate and submit, is my understanding correct?

**Comment by guoshupei** [comment]
I think the source of the problem is repeat generate task, What do you think?

**Comment by caishunfeng** [comment]
> I think the source of the problem is repeat generate task, What do you think?

It's seems that repeat generate task, but the main reason is that the upstream task event execute twice.

**Comment by guoshupei** [comment]
> > I think the source of the problem is repeat generate task, What do you think?
> 
> It's seems that repeat generate task, but the main reason is that the upstream task event execute twice.

Taking the figure as an example, do you mean that `task_child_one` and `task_child_two` are executed once each?

**Comment by caishunfeng** [comment]
> Taking the figure as an example, do you mean that `task_child_one` and `task_child_two` are executed once each?

Yes

**Comment by guoshupei** [comment]
Ok, @caishunfeng, thank you for your answer, Can two upstream task only generate one task instance of `task_union`. I think it is reasonable to generate once.^_^
