### ISSUE TITLE
[Bug] [Master] too much log printing leads to insufficient disk space

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#9297]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When master use `host-selector: lower_weight` and worker is busy because of high CPU, master will print many error log like 
`fail to execute : %s due to no suitable worker, current task needs worker group %s to execute`

### What you expected to happen

the log will not print too fast

### How to reproduce

master use `host-selector: lower_weight`  and run stress test.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I add the following configuration to ```logback-master.xml``` for temporary prevention of this problem...

```
            <maxHistory>36</maxHistory>
            <maxFileSize>200MB</maxFileSize>
            <totalSizeCap>5GB</totalSizeCap>
            <cleanHistoryOnStart>true</cleanHistoryOnStart>
```

**Comment by caishunfeng** [comment]
> I add the following configuration to `logback-master.xml` for temporary prevention of this problem...
> 
> ```
>             <maxHistory>36</maxHistory>
>             <maxFileSize>200MB</maxFileSize>
>             <totalSizeCap>5GB</totalSizeCap>
>             <cleanHistoryOnStart>true</cleanHistoryOnStart>
> ```

Thanks for your reply, I will have a try.

**Comment by caishunfeng** [comment]
remove stale
