### ISSUE TITLE
[Bug] [Alert] repeated sending of alarm message

### ISSUE THREAD

**Issue by DHBin** [apache/dolphinscheduler#9298]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

https://github.com/apache/dolphinscheduler/blob/d88656c4cef300e3360689d0d9f70523f74ac0e8/dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertServer.java#L117-L118

multiple alert nodes execute `alertDao.listPendingAlerts()` at the same time to obtain the same alert, which will cause the same Alert to be sent multiple times

### What you expected to happen

-

### How to reproduce

-

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by huagetai** [comment]
One alert server is enough

**Comment by guoshupei** [comment]
Hi, I have some insights. At present, I think `AlertServer` does not support distributed, only single point.  
- First, as you said, there will be repeated consumption problems in multiple nodes. 
- Second, `WorkerServer` is directly connected to `AlertServer` and support only one.

![image](https://user-images.githubusercontent.com/29919212/161469609-4d8c8054-0f14-40ef-81c2-aa7556a006a2.png)
