### ISSUE TITLE
[Feature][plugin] Add k8s task in task plugin

### ISSUE THREAD

**Issue by zhaohehuhu** [apache/dolphinscheduler#9310]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

To go forward to K8S, It's better to have a solution for some batch tasks which can run in K8S. 

### Use case

some java applications need to run periodically, so this plugin can easily help them run in K8S. Developers won't care much about the deployment and management once these programs run in dolphinscheduler.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @[qianli2022](https://github.com/qianli2022)  Please take a look of this issue.
BTW, DS had some k8s issue and pr, you can find out first. @luoyedeyi

**Comment by EricGao888** [comment]
> 

@caishunfeng Could we open a parent issue or add some tag to track these k8s related issues? To support popular task plugins running in k8s, I think at least we need enable related task clients to run in k8s.

**Comment by caishunfeng** [comment]
> > 
> 
> @caishunfeng Could we open a parent issue or add some tag to track these k8s related issues? To support popular task plugins running in k8s, I think at least we need enable related task clients to run in k8s.

Good suggestion! I think we can create a DSIP of k8s, see https://dolphinscheduler.apache.org/en-us/community/DSIP.html. What do you think?

**Comment by EricGao888** [comment]
> > > 
> > 
> > 
> > @caishunfeng Could we open a parent issue or add some tag to track these k8s related issues? To support popular task plugins running in k8s, I think at least we need enable related task clients to run in k8s.
> 
> Good suggestion! I think we can create a DSIP of k8s, see https://dolphinscheduler.apache.org/en-us/community/DSIP.html. What do you think?

@caishunfeng I just took a quick look at DSIP doc. It's really cool. If we create a DSIP of k8s, it will definitely help contributors to build k8s related features more effectively.
