### ISSUE TITLE
[Bug] [Alert] Enterprise wechat send message should be markdown type

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#9311]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Enterprise wechat send message should be ```markdown``` type.

https://github.com/apache/dolphinscheduler/blob/c99b33a083ceeffc89d2efdd6ebe0fdab8f8312e/dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-wechat/src/main/java/org/apache/dolphinscheduler/plugin/alert/wechat/WeChatSender.java#L248-L256

### What you expected to happen

above.

### How to reproduce

above.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
Dear SbloodyS,
Have checked this and found 'table' section not working and will replace 'table' with 'markdown' message type.
Yours

**Comment by Tianqi-Dotes** [comment]
check https://github.com/apache/dolphinscheduler/pull/9367
