### ISSUE TITLE
[DSIP-6][k8s] k8s on dolphinscheduler

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#9312]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This DSIP to collect issues about k8s on ds. 

-  #8144
-  #9462
-  #9252
-  #9310
-  #9337
-  #9544
-  #9550
-  #10629
-  k8s-operator: https://github.com/apache/dolphinscheduler-operator
-  #11402
-  #11730 
-  #11508

**Comment by fusonghe** [comment]
add spark on k8s   Receive less than log

**Comment by caishunfeng** [comment]
> add spark on k8s Receive less than log

Please create a issue and add some issue description. This DSIP just use to record k8s related features.
