### ISSUE TITLE
[Bug] [Dependent Node] Dependent node stuck in checking

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#9315]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Dependent node stuck in checking When the dependent task has two workflow instances, one succeeds and the other fails.

### What you expected to happen

dependent check success.

### How to reproduce

above.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gglinux** [comment]
We have the same problem, the version is 2.0.5.

Dependent nodes are actually successful

<img width="277" alt="image" src="https://user-images.githubusercontent.com/7273957/172120689-aa23c9dc-6948-4787-a97b-5dacaa8887f1.png">
