### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]Components that execute successfully do not display the success icon

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9318]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Components that execute successfully do not display the success icon

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/76080484/161247984-d431f171-adcf-42ee-9032-d3f11a06b34e.png">

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/76080484/161247711-0b416bfd-38bd-4214-ac92-cbed7ddcd2a4.png">

### What you expected to happen

Execution of a successful component displays the success icon

### How to reproduce

This component is created by create task

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
