### ISSUE TITLE
[Feature][CI] Add auto remove not need imgs type 

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#9321]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, we `imgs_utils.py` CI in `docs/imgs_utils.py` to check file type whether having images in directory `img` but we do not expect. But it is only the checker, we should add auto remove the not expect images base on our configuration and `img` in directory `docs`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@zhongjiajie I'd like to take this one. May I ask where can I find such `configuration` to tell which images are not needed and supposed to be removed?

**Comment by zhongjiajie** [comment]
Currently, we check weather exists not need types of img base on variable https://github.com/apache/dolphinscheduler/blob/9f84dbbda00956d5bf198ce7eb4c47f2ea335173/docs/img_utils.py#L35-L38 . But we already can find all imgs file and types base on the pattern in https://github.com/apache/dolphinscheduler/blob/9f84dbbda00956d5bf198ce7eb4c47f2ea335173/docs/img_utils.py#L41-L43 from our docs directory.

So when the img not used in the docs directory, and also have some type not in the docs directory, we should remove them. But you could also find other way to do that as your wish

**Comment by EricGao888** [comment]
> Currently, we check weather exists not need types of img base on variable
> 
> https://github.com/apache/dolphinscheduler/blob/9f84dbbda00956d5bf198ce7eb4c47f2ea335173/docs/img_utils.py#L35-L38
> 
> . But we already can find all imgs file and types base on the pattern in
> https://github.com/apache/dolphinscheduler/blob/9f84dbbda00956d5bf198ce7eb4c47f2ea335173/docs/img_utils.py#L41-L43
> 
> from our docs directory.
> So when the img not used in the docs directory, and also have some type not in the docs directory, we should remove them. But you could also find other way to do that as your wish

@zhongjiajie In summary, we need to automatically remove two types of images:
1. images with the unexpected types
2. images not referenced in the docs directory

However for the first point, if there are images of unexpected types, assertion will fail right away. Therefore, we only need to remove `images not referenced in the docs directory`. Please correct me if I get it wrong.
https://github.com/apache/dolphinscheduler/blob/9f84dbbda00956d5bf198ce7eb4c47f2ea335173/docs/img_utils.py#L128-L135

**Comment by zhongjiajie** [comment]
> However for the first point, if there are images of unexpected types, assertion will fail right away. Therefore, we only need to remove images not referenced in the docs directory. Please correct me if I get it wrong.

Good catch, you're right. Maybe we only need to dynamic get `expect_img_types` from `docs` directory https://github.com/apache/dolphinscheduler/blob/9f84dbbda00956d5bf198ce7eb4c47f2ea335173/docs/img_utils.py#L35-L38 , cause we need if for finding all docs imgs in https://github.com/apache/dolphinscheduler/blob/9f84dbbda00956d5bf198ce7eb4c47f2ea335173/docs/img_utils.py#L123-L124 but now it is hard code.

When we add new img type like `*.svg`, we can not get svg path in `docs` by https://github.com/apache/dolphinscheduler/blob/9f84dbbda00956d5bf198ce7eb4c47f2ea335173/docs/img_utils.py#L123-L124 cause our function `build_pattern` do not get it from directory `docs`, and sub command `prune` will remove `*.svg` file when I run it.
For now I have to add `svg` into `expect_img_types` to fix this
