### ISSUE TITLE
[Bug] [Task Define] can't open process define web

### ISSUE THREAD

**Issue by zhangwayne89** [apache/dolphinscheduler#9326]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

after deploy dolphinschedule(2.0.5), can't open process define web
![image](https://user-images.githubusercontent.com/34704409/161367260-d58a660e-3c6c-4b54-ba00-81264a4505e1.png)

### What you expected to happen

after deploy dolphinschedule(2.0.5), can't open process define web

### How to reproduce

after deploy dolphinschedule(2.0.5), can't open process define web

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @zhangcongwayne, you can check whether your network firewall or proxy is configured correctly.
