### ISSUE TITLE
[Bug] [UI-Next] Rename process to workflow

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#9328]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

* In `Task Definition` section, when creating a task and choosing which workflow it belongs to, the UI shows `Process Name` instead of `Workflow Name`. 

<img width="1428" alt="workflow" src="https://user-images.githubusercontent.com/34905992/161372117-32148653-a83c-41e3-ad2b-e896413c134d.png">

<img width="1412" alt="wf2" src="https://user-images.githubusercontent.com/34905992/161372131-3930be04-2822-4042-9cf3-1c58d02a3c4d.png">

### What you expected to happen

* We could consistently use `Workflow` instead of `Process` for naming.

### How to reproduce

* Already described in `What happened` section.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
