### ISSUE TITLE
[Bug-FE] [UI-Next][V1.0.0-Alpha] The name should be task not node in the task creation modal.

### ISSUE THREAD

**Issue by Amy0104** [apache/dolphinscheduler#9330]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="667" alt="image" src="https://user-images.githubusercontent.com/97265214/161373139-45f71e97-48d9-43a4-b4f4-8970d5f4f39f.png">

### What you expected to happen

Rename the name to task.

### How to reproduce

1. Open the task definition page.
2. Create a task.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
