### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha] The time columns cannot be broken in the cron manage table.

### ISSUE THREAD

**Issue by Amy0104** [apache/dolphinscheduler#9331]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/97265214/161373425-c0b82e07-57df-4435-aee3-cae343951612.png">

### What you expected to happen

The time columns cannot be broken.

### How to reproduce

1. Open the cron manage page.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.
