### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha]The pre-task parameter was passed unsuccessfully and was overridden by the global parameter

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9349]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The pre-task parameter was passed unsuccessfully and was overridden by the global parameter

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/76080484/161704475-592cd667-806e-47cf-b455-5e74f5d74228.png">

<img width="1908" alt="image" src="https://user-images.githubusercontent.com/76080484/161704919-636841b7-e801-4074-acb2-4a0681631941.png">

<img width="1889" alt="image" src="https://user-images.githubusercontent.com/76080484/161705032-d332619b-737f-4147-ba8a-79606fc21f27.png">

<img width="1911" alt="image" src="https://user-images.githubusercontent.com/76080484/161705187-e945a441-1f08-4360-811c-f12a209d5aed.png">

### What you expected to happen

The pre-task parameter priority is greater than the global parameter priority

### How to reproduce

The pre-task parameter was passed unsuccessfully and was overridden by the global parameter

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
I check in local, the Parameter Priority is: Local Parameter > Global Parameter > Parameter Context
