### ISSUE TITLE
[Bug] [rest api] /dolphinscheduler/projects/{projectCode}/executors/start-process-instance

### ISSUE THREAD

**Issue by lordk911** [apache/dolphinscheduler#9355]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

parameter scheduleTime is not required, but in page `http://{api server ip}:12345/dolphinscheduler/doc.html?language=zh_CN&lang=cn ` the start-process-instance api also show it is required, and not show what kind of value is validated, it is very confused, event if I give the wrong value, the api also respone sucess, but the process not run.

### What you expected to happen

A clear api doc with some example for commonly use api.

### How to reproduce

I'm using 2.0.5 the api doc is wrong.

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
The format of scheduleTime is ```2022-04-06 00:00:00```. The scheduleTime is ```""``` by default.

eg:
scheduleTime=''
scheduleTime='2022-04-06 00:00:00,2022-04-06 00:00:00'
scheduleTime='2022-04-06 00:00:00,2022-04-07 00:00:00'


Parameter scheduleTime is required. I will fix the doc.
