### ISSUE TITLE
[Bug] [UI-Next] Monitor gauge charts are blank

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#9356]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In dev version, UI-Next as front-end, when entering `Monitor` section, we can see the gauge charts are blank for both master and worker. Chart color is missing.
![image](https://user-images.githubusercontent.com/34905992/161886806-a17b6dc8-0abf-4416-a61b-9e9fbefdba41.png)

### What you expected to happen

Gauge charts are supposed to display with colors.

### How to reproduce

Already described in `What happened` section.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
This problem is a color matching problem, not a bug, but there is no time now, we have to wait for subsequent optimization.

**Comment by Amy0104** [comment]
I will handle this.
