### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]New feature execution policy options are not translated into Chinese

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9360]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

New feature execution policy options are not translated into Chinese

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/76080484/161909037-c7ab338c-c754-4608-95ac-80b4e25adfd7.png">

### What you expected to happen

Chinese translation and normal display

### How to reproduce

Execute policy options when saving workflows

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
