### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]Clicking on the View Variables page displays an error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9362]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Clicking on the View Variables page displays an error

The left side of the page displays beyond the screen

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/76080484/161913316-3145d440-5a90-43f9-abae-12fc278e57e7.png">

### What you expected to happen

Parameter information can be displayed more elegantly in the pop-up window

### How to reproduce

Clicking on the View Variables page displays an error

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
