### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha]The alarm group is selected during execution, but the alarm group is shown as empty in the example

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9364]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The alarm group is selected during execution, but the alarm group is shown as empty in the example

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/76080484/161916106-0e56eb89-0e85-413d-8b50-f80f915d2a42.png">

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/76080484/161916693-4a3fc89d-2d95-4601-8097-6a2e02ac0817.png">

### What you expected to happen

Execution information can be displayed correctly

### How to reproduce

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/76080484/161916106-0e56eb89-0e85-413d-8b50-f80f915d2a42.png">

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it.

**Comment by Tianqi-Dotes** [comment]
have merged
