### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Beta] Execute the complement to select two parallel, click on the previous run pop-up window to report an error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9365]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Execute the complement to select two parallel, click on the previous run pop-up window to report an error

http://ds2:12345/dolphinscheduler/ui/projects/5092091953472/workflow/instances/9929?code=5092091953472

![image](https://user-images.githubusercontent.com/76080484/161918317-48e263a3-b497-47c4-baec-4a6776b7ec6e.png)

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/76080484/161918100-b3e9ed87-4d00-4ef2-a0fd-ac7b252d6762.png">

### What you expected to happen

Successful implementation

### How to reproduce

![image](https://user-images.githubusercontent.com/76080484/161918317-48e263a3-b497-47c4-baec-4a6776b7ec6e.png)

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will fix it.

**Comment by Amy0104** [comment]
This bug seems not to be reproduced.Maybe you can provide more details on how to reproduce.
