### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha]Workflow delete error report

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9368]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Workflow delete error report

http://ds2:12345/dolphinscheduler/ui/projects/5050147778880/workflow-definition

<img width="1905" alt="image" src="https://user-images.githubusercontent.com/76080484/161922858-5073a10a-604b-4fd1-b109-855ec9108c8b.png">

### What you expected to happen

Workflow deletion is normal

### How to reproduce

Workflow delete error report

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
@XuXuClassMate Thank you very much for testing. 
Meanwhile, that would be very helpful if there are some error logs in API server.

**Comment by Tianqi-Dotes** [comment]
cannot reproduce, it works well on me
