### ISSUE TITLE
[Bug] [Data Quality] Project build failure caused by data quality module

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#9369]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

* Building project with command `mvn -U install package -Prelease -Dmaven.test.skip=true` occasionally fails with error `[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2:single (make-assembly) on project dolphinscheduler-data-quality: Failed to create assembly: Error creating assembly archive jar-with-dependencies: Problem creating jar: JAR entry log4j.properties not found in ......./dolphin-scheduler/dolphinscheduler/dolphinscheduler-data-quality/target/archive-tmp/dolphinscheduler-data-quality-2.0.4-SNAPSHOT.jar `
* It doesn't happen every time, but it does happen.
* I had run `mvn clean` before I built the project.
* I've checked the `log4j.properties` and it does existed. Not sure why error msg says it can't be found.
![image](https://user-images.githubusercontent.com/34905992/161934834-69f64280-768d-40cc-a728-797fec1944fa.png)
![image](https://user-images.githubusercontent.com/34905992/161934903-3f034389-4fb9-4216-8b77-f907577395d6.png)

### What you expected to happen

* We need to find out what causes the project build failure and how to avoid it. This issue could make developer very confused.

### How to reproduce

* Described in `What happened` section.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
BTW, I ran the build command in the terminal of `IntelliJ IDE`. But I suppose it shouldn't be the cause.

**Comment by lenboo** [comment]
`mvn clean install -Prelease -Dmaven.test.skip=true` 
It will be work 100%

**Comment by EricGao888** [comment]
> `mvn clean install -Prelease -Dmaven.test.skip=true` It will be work 100%

@lenboo Thanks for the help, I will give a try. Not sure why `mvn clean` then `mvn -U install package -Prelease -Dmaven.test.skip=true` does not work.

**Comment by EricGao888** [comment]
> `mvn clean install -Prelease -Dmaven.test.skip=true` It will be work 100%

@lenboo I just tried `mvn clean install -Prelease -Dmaven.test.skip=true`, it did work! Thx! But still, I'm wondering why `mvn clean` then `mvn -U install package -Prelease -Dmaven.test.skip=true` doesn't work. Maybe we could change the instructions in the docs. 
![image](https://user-images.githubusercontent.com/34905992/161977263-02d77f10-bc69-424c-9431-e86cb8386a66.png)

**Comment by lenboo** [comment]
> > `mvn clean install -Prelease -Dmaven.test.skip=true` It will be work 100%
> 
> @lenboo I just tried `mvn clean install -Prelease -Dmaven.test.skip=true`, it did work! Thx! But still, I'm wondering why `mvn clean` then `mvn -U install package -Prelease -Dmaven.test.skip=true` doesn't work. Maybe we could change the instructions in the docs. ![image](https://user-images.githubusercontent.com/34905992/161977263-02d77f10-bc69-424c-9431-e86cb8386a66.png)

 Yes, I think you're right about that.

**Comment by lenboo** [comment]
Fixed pr:
https://github.com/apache/dolphinscheduler-website/pull/768
