### ISSUE TITLE
[Bug] [UI] Resource is not exist

### ISSUE THREAD

**Issue by MindDeer** [apache/dolphinscheduler#9374]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I have created a multi-layer directory in the front-end resource center and entered one of the directories, the path of the current directory is displayed above the directory. However, when I click a level in the path, I should be able to jump to that directory under normal circumstances, but it does not jump, and the front-end reports an error: the resource does not exist.

### What you expected to happen

When I click a level in the path,  should be able to jump to that directory under normal circumstances.

![image](https://user-images.githubusercontent.com/48878323/162018672-ad0f3592-db3d-477b-b6a2-2bc7c6de6ad5.png)

### How to reproduce

Enter a built multi-level directory in the resource center and click any of the parent directories displayed in the path above. At this time, the jump is not realized and the resource does not exist.

### Anything else

This is a front-end bug, and the back-end does not provide the corresponding API interface.

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
May be it's related to #9059 . @songjianet Please take a look if you have spare time. Thanks.

**Comment by MindDeer** [comment]
> May be it's related to #9059 . @songjianet Please take a look if you have spare time. Thanks.

Yes, after submitting, it is found that it is indeed the same problem.
