### ISSUE TITLE
[Feature][doc] Add how to change standalone database type

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#9376]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, our standalone server doc only told us how to start the server in https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/installation/standalone.html. and we should notice user the database is in memory and standalone server also support other type of database like postgre and mysql

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
@zhongjiajie I think this issue is helpful to developers. If those who are new to dolphin know how to use mysql for standalone server, they will not lose all data after each time restarting the server. I'd like to take this one.
