### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha]Workflow execution is successful, view instance pop-up reports error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9382]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Workflow execution is successful, view instance pop-up reports error

url：http://ds2:12345/dolphinscheduler/ui/projects/5092091953472/workflow/instances/9939?code=5092095909952

<img width="1912" alt="image" src="https://user-images.githubusercontent.com/76080484/162164493-e1e1a800-247f-4f65-a67a-60063d97bb38.png">

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/76080484/162165006-ea9cc624-f89c-418a-a3a4-30b5665deecc.png">

### What you expected to happen

Expect to know the exact reason for the error report

### How to reproduce

Workflow execution is successful, view instance pop-up reports error

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
discussed and cannot reproduce
