### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha]Workflow replication error report

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9384]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Workflow replication error report

url：http://ds2:12345/dolphinscheduler/ui/projects/5092091953472/workflow-definition

<img width="1905" alt="image" src="https://user-images.githubusercontent.com/76080484/162167913-0af2f699-e439-4346-a4dd-402c0f4f08ae.png">

### What you expected to happen

Bulk replication success

### How to reproduce

Workflow replication error report

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
this one is reasonable.
