### ISSUE TITLE
[Feature][resource] Add doc about how to config local file system or and `local` type of file system

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#9385]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, our config file of the resource center only supports `s3` and `hdfs`. https://github.com/apache/dolphinscheduler/blob/0e3cafec1d0a6529c6bb5371429a9b51bd60fd5a/dolphinscheduler-common/src/main/resources/common.properties#L22
but our docs https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/resource.html said we support a local file system.
we could find some config demo in https://github.com/apache/dolphinscheduler/issues/5099. and we should add config demo about local file system by:
* Just change our doc and add the demo config according to https://github.com/apache/dolphinscheduler/issues/5099
* Add new type named `local`(a shortcut to set config `resource.storage.type=HDFS` and `fs.defaultFS=file:///`) to `resource.storage.type` and add some docs about it.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
WDYT? @caishunfeng @ruanwenjun @nobolity what is your perfer solution or do you have a better solution?

**Comment by ruanwenjun** [comment]
> WDYT? @caishunfeng @ruanwenjun @nobolity what is your perfer solution or do you have a better solution?

Both the two solutions are good to me.

**Comment by caishunfeng** [comment]
I think it's better to add a `local` type, which is easier to understand. But the complexity and difficulty of the adaptation need to evaluate.

**Comment by zhongjiajie** [comment]
> I think it's better to add a `local` type, which is easier to understand. But the complexity and difficulty of the adaptation need to evaluate.

I think so, and I will go depth next week when I have time. And learn about how to write JAVA code 🤣

**Comment by 106umao** [comment]
i will solve it @zhongjiajie

**Comment by SbloodyS** [comment]
> i will solve it @zhongjiajie

I have assigned to you. Looking forward to your contribution.

**Comment by zhongjiajie** [comment]
close in #13303
