### ISSUE TITLE
[Bug][UI Next]data quality task edit can't load before info

### ISSUE THREAD

**Issue by zengqiyan** [apache/dolphinscheduler#9394]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when edit data quality task,it can't load before form data
<img width="791" alt="8c7cd1c4-bce9-4712-8f0e-08e0b2be5678" src="https://user-images.githubusercontent.com/16408555/162347198-80c1f66a-1092-4433-a164-ef97d5b1b5d8.png">

### What you expected to happen

edit data quality task,it can load before form data

### How to reproduce

edit data quality task

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zengqiyan** [comment]
已收到，谢谢

**Comment by Amy0104** [comment]
I will fix it.This seems  to be a form data display back problem.

**Comment by paul8263** [comment]
Got the same problem. Try fixing it but still does not catch root cause. Its structure is similar to `use-http.ts` but `use-http.ts` works well. Would you please give a hand? @songjianet

**Comment by zengqiyan** [comment]
已收到，谢谢

**Comment by zengqiyan** [comment]
已收到，谢谢

**Comment by zengqiyan** [comment]
已收到，谢谢
