### ISSUE TITLE
[Bug] Add data source (mysql) error

### ISSUE THREAD

**Issue by sad-nickname** [apache/dolphinscheduler#9399]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

在数据源管理中添加mysql数据源时报错

【Failed to load driver class com.mysql.cj.jdbc.Driver in either of HikariConfig class loader or Thread context classloader】

dolphinscheduler版本2.0.5，数据源添加的mysql版本为8.0

### What you expected to happen

![image](https://user-images.githubusercontent.com/48752393/162358503-ec43dc68-9402-48f7-8e61-2e29ae065c43.png)

### How to reproduce

在数据源管理中添加一个mysql数据源

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You can refer to the relevant parts of MySQL on the official website
```https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/installation/pseudo-cluster.html```
