### ISSUE TITLE
[Bug] [Master] Master frequent print logs

### ISSUE THREAD

**Issue by brave-lee** [apache/dolphinscheduler#9401]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

**1. No worker:**
[INFO] 2022-04-08 06:14:58.688 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[309] - process event: State Event : key : null type: TASK_STATE_CHANGE executeStatus: NEED_FAULT_TOLERANCE task instance id: 8 process instance id: 7 context: null
**2. Worker high load**
fail to execute : ... due to no suitable worker,  current task needs worker group ... to execute
**3. The running task was deleted**
[INFO] 2022-04-06 11:13:46.749 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[301] - process event: State Event : key : null type: TASK_TIMEOUT executeStatus: null task instance id: 10277 process instance id: 6 context: null
[ERROR] 2022-04-06 11:13:46.749 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[264] - state handle error:
java.lang.NullPointerException: null

### What you expected to happen

Master should not print logs frequently.

### How to reproduce

Please take a look

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by czeming** [comment]
I want to try to solve this problem.

At present, after the execution of an unknown exception fails, it will actually be caught and will not execute `remove` and keep trying again. This should be the reason for the frequent output of the same log (multiple executions of the same data still fail).

It is suggested to use `poll` to ensure the deletion of data, but I am not sure whether there is any consideration of retry here.


There are two options:
1. Directly use `poll`. If it fails, execute the failure processing
2. Use `poll` and try again for a certain number of times, such as `while`. If it fails, execute the failure processing.

Failure handling can also be divided into two types:
1. Output log directly
2. Establish a failure queue globally, print the log and add the failure data to the failure queue.

If failure queue is adopted, the function of failure queue needs to be discussed.

======

I found a problem with the existing code:

`org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread#handleEvents` called `remove`
`org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread#stateEventHandler` called `remove`
In fact, when result = true, the call will be repeated and `remove` will traverse the queue once.

Using peek to read and execute time-consuming tasks may cause concurrent misreading.

For the above reasons, `poll` is recommended.

@JinyLeeChina For the specific problems you encounter, you need more detailed stack information to troubleshoot. I've seen the logic of execution. Except for `process_state_change`, there are few abnormal logic.

**Comment by czeming** [comment]
Through communication, I learned the current situation:
The task itself must be executed successfully, so it needs to be retried continuously. If there is a problem when pushing it to `worker`, the log must also be output.

But I think outputting logs actually means some kind of feedback or recording problems. I speculate that adding status to `task` itself may solve the problem.
For example, `waiting` and `pending`, `waiting` means that the `task` instance is newly created, and `pending` means that the pre execution logic is satisfied and attempts to push it to `worker`.

I suggest updating from `waiting` to `pending` and pushing the task to `worker` when preparing to push the task, so that users can realize that the task has met the execution conditions.
If the `task` in `waiting` status fails to be pushed to `worker` for the first time, the error log can be printed and updated to `pending` status. After that, try again and again. If the `task` in the `pending` state fails to push, the log will not be output. When it succeeds, switch to the current execution state and output the corresponding success log.

Of course, how the underlying method of this logic call controls the log needs to be discussed.

**Comment by SbloodyS** [comment]
> Through communication, I learned the current situation: The task itself must be executed successfully, so it needs to be retried continuously. If there is a problem when pushing it to `worker`, the log must also be output.
> 
> But I think outputting logs actually means some kind of feedback or recording problems. I speculate that adding status to `task` itself may solve the problem. For example, `waiting` and `pending`, `waiting` means that the `task` instance is newly created, and `pending` means that the pre execution logic is satisfied and attempts to push it to `worker`.
> 
> I suggest updating from `waiting` to `pending` and pushing the task to `worker` when preparing to push the task, so that users can realize that the task has met the execution conditions. If the `task` in `waiting` status fails to be pushed to `worker` for the first time, the error log can be printed and updated to `pending` status. After that, try again and again. If the `task` in the `pending` state fails to push, the log will not be output. When it succeeds, switch to the current execution state and output the corresponding success log.
> 
> Of course, how the underlying method of this logic call controls the log needs to be discussed.

I think i can make this simple to understand. The solution is to add the status of task instances to replace the log output.

1. Add ```waiting suitable worker``` state to represent no suitable worker log output.
2. Add ```waiing for the worker's load to decrease``` state to represent worker in high load.
3. Add ```stop due to the running task was deleted``` state to represent the running task was deleted.

After adding these status to the task instance. We may delete the irrelevant log to prevent frequent log printing. So that the user can understand task instance state instead of locate the problem by querying the logs. And this solution is also applicable to other places where logs are frequently printed.

WDYT? @caishunfeng @lenboo @JinyLeeChina 

Related issue: #7516

**Comment by caishunfeng** [comment]
> > Through communication, I learned the current situation: The task itself must be executed successfully, so it needs to be retried continuously. If there is a problem when pushing it to `worker`, the log must also be output.
> > But I think outputting logs actually means some kind of feedback or recording problems. I speculate that adding status to `task` itself may solve the problem. For example, `waiting` and `pending`, `waiting` means that the `task` instance is newly created, and `pending` means that the pre execution logic is satisfied and attempts to push it to `worker`.
> > I suggest updating from `waiting` to `pending` and pushing the task to `worker` when preparing to push the task, so that users can realize that the task has met the execution conditions. If the `task` in `waiting` status fails to be pushed to `worker` for the first time, the error log can be printed and updated to `pending` status. After that, try again and again. If the `task` in the `pending` state fails to push, the log will not be output. When it succeeds, switch to the current execution state and output the corresponding success log.
> > Of course, how the underlying method of this logic call controls the log needs to be discussed.
> 
> I think i can make this simple to understand. The solution is to add the status of task instances to replace the log output.
> 
> 1. Add `waiting suitable worker` state to represent no suitable worker log output.
> 2. Add `waiing for the worker's load to decrease` state to represent worker in high load.
> 3. Add `stop due to the running task was deleted` state to represent the running task was deleted.
> 
> After adding these status to the task instance. We may delete the irrelevant log to prevent frequent log printing. So that the user can understand task instance state instead of locate the problem by querying the logs. And this solution is also applicable to other places where logs are frequently printed.
> 
> WDYT? @caishunfeng @lenboo @JinyLeeChina
> 
> Related issue: #7516

Good idea, but I think just add `waitting suitable worker` state for dispatch is OK, because `fail to execute : ... due to no suitable worker, current task needs worker group ... to execute` print the most.

**Comment by SbloodyS** [comment]
> > > Through communication, I learned the current situation: The task itself must be executed successfully, so it needs to be retried continuously. If there is a problem when pushing it to `worker`, the log must also be output.
> > > But I think outputting logs actually means some kind of feedback or recording problems. I speculate that adding status to `task` itself may solve the problem. For example, `waiting` and `pending`, `waiting` means that the `task` instance is newly created, and `pending` means that the pre execution logic is satisfied and attempts to push it to `worker`.
> > > I suggest updating from `waiting` to `pending` and pushing the task to `worker` when preparing to push the task, so that users can realize that the task has met the execution conditions. If the `task` in `waiting` status fails to be pushed to `worker` for the first time, the error log can be printed and updated to `pending` status. After that, try again and again. If the `task` in the `pending` state fails to push, the log will not be output. When it succeeds, switch to the current execution state and output the corresponding success log.
> > > Of course, how the underlying method of this logic call controls the log needs to be discussed.
> > 
> > 
> > I think i can make this simple to understand. The solution is to add the status of task instances to replace the log output.
> > 
> > 1. Add `waiting suitable worker` state to represent no suitable worker log output.
> > 2. Add `waiing for the worker's load to decrease` state to represent worker in high load.
> > 3. Add `stop due to the running task was deleted` state to represent the running task was deleted.
> > 
> > After adding these status to the task instance. We may delete the irrelevant log to prevent frequent log printing. So that the user can understand task instance state instead of locate the problem by querying the logs. And this solution is also applicable to other places where logs are frequently printed.
> > WDYT? @caishunfeng @lenboo @JinyLeeChina
> > Related issue: #7516
> 
> Good idea, but I think just add `waitting suitable worker` state for dispatch is OK, because `fail to execute : ... due to no suitable worker, current task needs worker group ... to execute` print the most.

Worker high load will also be output frequently in the production environment with more workflows, such as my production environment.
