### ISSUE TITLE
[Question] Can the arm framework be used?

### ISSUE THREAD

**Issue by shangshang11** [apache/dolphinscheduler#9407]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

arm框架部署集群，能否实现

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shangshang11** [comment]
请问这是什么错误

 worker server is starting
Begin start api-server......
starting api-server, logging to /data/dolphinscheduler/bin/../logs/dolphinscheduler-api-server-0015.novalocal.out
nohup /usr/local/java/jdk/bin/java -Dlogging.config=classpath:logback-api.xml -Dspring.profiles.active=api -server -Xms1g -Xmx1g -Xmn500m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m  -Xss512k -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:LargePageSizeInBytes=128m -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:+PrintGCDetails -Xloggc:gc.log -XX:+HeapDumpOnOutOfMemoryError  -XX:HeapDumpPath=dump.hprof -classpath /data/dolphinscheduler/bin/../conf:/data/dolphinscheduler/bin/../lib/* org.apache.dolphinscheduler.api.ApiApplicationServer > /data/dolphinscheduler/bin/../logs/dolphinscheduler-api-server-0015.novalocal.out 2>&1 &
End start api-server.

**Comment by caishunfeng** [comment]
> 请问这是什么错误
> 
> worker server is starting Begin start api-server...... starting api-server, logging to /data/dolphinscheduler/bin/../logs/dolphinscheduler-api-server-0015.novalocal.out nohup /usr/local/java/jdk/bin/java -Dlogging.config=classpath:logback-api.xml -Dspring.profiles.active=api -server -Xms1g -Xmx1g -Xmn500m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xss512k -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:LargePageSizeInBytes=128m -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:+PrintGCDetails -Xloggc:gc.log -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=dump.hprof -classpath /data/dolphinscheduler/bin/../conf:/data/dolphinscheduler/bin/../lib/* org.apache.dolphinscheduler.api.ApiApplicationServer > /data/dolphinscheduler/bin/../logs/dolphinscheduler-api-server-0015.novalocal.out 2>&1 & End start api-server.

It's the start command, please provide some error log.

**Comment by paul8263** [comment]
Hi @shangshang11 ,
DolphineScheduler is able to run on servers with ARM architecture.
Please paste your error log below.
