### ISSUE TITLE
[Bug] [UI] Custom parameter types do not have LIST type

### ISSUE THREAD

**Issue by qingzhongli** [apache/dolphinscheduler#9412]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

`Custom parameter` types do not have `LIST`, as shown in the following figure:

![de7be3bbeae8e31d5036ddf620ee877](https://user-images.githubusercontent.com/13859782/162564707-11508255-2794-42f0-9600-dfe79f672aa2.png)

### What you expected to happen

According to [Parameter Context](https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/parameter/context.html), `Custom parameter` types should have `LIST`, as shown in the following figure:
![image](https://user-images.githubusercontent.com/13859782/162565164-568ca0ae-1c57-45c1-b2db-8c77ac5b0911.png)

### How to reproduce

new SQL node --> add `Custom Parameter` --> select parameter type

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
I think this is a bug.
@qingzhongli Could you please submit a pr to fix it?
