### ISSUE TITLE
[Feature][task-flink] support deploy a flink task with application mode、Per-Job Cluster Mode、session mode when deploy flink on yarn

### ISSUE THREAD

**Issue by 861752346** [apache/dolphinscheduler#9416]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

only yarn-cluster mode was supported now,when deploy a flink task on yarn.but this mode is deprecated when use flink which version is equal or greater   1.12.0.

### Use case

support deploy a flink task with application mode、Per-Job Cluster Mode、session mode when deploy flink on yarn which version is equal or greater   1.12.0.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by paul8263** [comment]
Hi @861752346 and @SbloodyS ,

Are you currently working on this issue? If you are not, I would like to take it.

My team plans to upgrate Flink to 1.14.x so that we will meet the same problem. Per-job mode will be deprecated in the future release.

**Comment by SbloodyS** [comment]
> Hi @861752346 and @SbloodyS ,
> 
> Are you currently working on this issue? If you are not, I would like to take it.
> 
> My team plans to upgrate Flink to 1.14.x so that we will meet the same problem. Per-job mode will be deprecated in the future release.

Hi @paul8263 , you are welcome to contribute it.

**Comment by paul8263** [comment]
Hi @SbloodyS ,
Thank you very much.
But I got a problem. How could I switch the UI back to legacy UI (built by Vuejs)?

**Comment by SbloodyS** [comment]
> Hi @SbloodyS , Thank you very much. But I got a problem. How could I switch the UI back to legacy UI (built by Vuejs)?

There is no need to switch UI. ```dolphinscheduler-ui-next``` is currently used in the dev branch and 3.0.X branch. ```dolphinscheduler-ui``` has been deprecated in dev branch and 3.0.X branch.
