### ISSUE TITLE
[Feature][Master] How to run multiple tasks in a task flow at the same time

### ISSUE THREAD

**Issue by Wky15163053670** [apache/dolphinscheduler#9418]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

(A、B)子任务都依赖(X、Y)父任务，我现在要同时执行(A、B)这两个子任务以及所依赖的父任务(X、Y)

该需求在业务中需求量极多，例如重新运行一部分脚本跑数据等情况

### Use case

建议
1. 在web端有可以多选页面
2. 设置各个依赖的是否运行的规则
3. 设置向前运行到第几层父依赖

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
>(A, B) child tasks all depend on (X, Y) parent task, I now want to execute (A, B) these two child tasks and the dependent parent task (X, Y) at the same time

You can use the logic task to do it. Such as `Conditions`, `Switch`, `SubProcess` and `Dependent`,  see https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/task/conditions.html.

BTW, please use English description next time, which can make more developers understand, thanks.

**Comment by Wky15163053670** [comment]
By that I mean simply running the current task without making any changes

**Comment by SbloodyS** [comment]
Dependent tasks can re-run automatically in the case of complement is now supported in #8373.

In my opinion, only the downstream dependency needs to be supplemented after the complement.

Can you describe why did you want to run pre dependency? @Wky15163053670

**Comment by lenboo** [comment]
@Wky15163053670 
English required. 
You can reopen it after updating content to english
