### ISSUE TITLE
[Bug] [Doc] Image can not display properly

### ISSUE THREAD

**Issue by QuakeWang** [apache/dolphinscheduler#9426]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Due to the migration of the documents directly from [website](https://github.com/apache/dolphinscheduler-website), some of the file paths were incorrect, thus preventing the images from being displayed properly.

### What you expected to happen

Modify the path so as to ensure that the images can be displayed properly.

### How to reproduce

You can see the problem at this [link](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/zh/guide/task/datax.md). The situation is similar to the other documents.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Could you give some examples of the bad path image?

**Comment by QuakeWang** [comment]
> Could you give some examples of the bad path image?

![1649656432(1)](https://user-images.githubusercontent.com/45645138/162673325-6aeaa885-8723-461d-8f50-ae896056d77c.png)

Like this, the picture is broken.

**Comment by zhongjiajie** [comment]
oh, I got it, you view it in the github itself do you? Although we migrate docs from dolphinscheduler-website to dolphinscheduler. we still keep the old link of the image on dolphinscheduler-website. It means that we could only view the img in https://dolphinscheduler.apache.org/ but failed in github, for now. Maybe we should find some way to fix it in the further, bu for now is do not matter because https://dolphinscheduler.apache.org/ looking good

**Comment by zhongjiajie** [comment]
We could make our image work in both GitHub and dolphinscheduler-website too. All we have to do is change img related path in dolphinschedule repo,  and add a convertor in https://github.com/apache/dolphinscheduler-website/blob/master/scripts/prepare_docs.sh to convert the image path in dolphinscheduler-website repository

**Comment by QuakeWang** [comment]
I found that using relative paths in documents such as `... /... /... /... /img/tasks/demo/`. Instead of absolute paths, e.g. `/img/tasks/demo`. The image will be displayed normally. So do we need to change the path to the image?

@zhongjiajie

**Comment by zhongjiajie** [comment]
> 

It could, but it will break the link on our website https://dolphinscheduler.apache.org/. So we also need to add some script in our website to avoid it being broken, and already have one in https://github.com/apache/dolphinscheduler-website/pull/789 by @huangchenguang123 . But it is related PR #10127 only correct conditions task type

**Comment by zhongjiajie** [comment]
after https://github.com/apache/dolphinscheduler-website/pull/789 merged, we could change all our img path from `/img` to related path

**Comment by zhongjiajie** [comment]
And I will find some easy way to batch operator them

**Comment by QuakeWang** [comment]
> after [apache/dolphinscheduler-website#789](https://github.com/apache/dolphinscheduler-website/pull/789) merged, we could change all our img path from `/img` to related path

Do you mean we can use `... /... /... /... /img/tasks/demo/` to replace `/img/tasks/demo` at now ?

**Comment by zhongjiajie** [comment]
> > after [apache/dolphinscheduler-website#789](https://github.com/apache/dolphinscheduler-website/pull/789) merged, we could change all our img path from `/img` to related path
> 
> Do you mean we can use `... /... /... /... /img/tasks/demo/` to replace `/img/tasks/demo` at now ?

Yeah, after https://github.com/apache/dolphinscheduler-website/pull/789 we can do that

**Comment by QuakeWang** [comment]
> > > after [apache/dolphinscheduler-website#789](https://github.com/apache/dolphinscheduler-website/pull/789) merged, we could change all our img path from `/img` to related path
> > 
> > 
> > Do you mean we can use `... /... /... /... /img/tasks/demo/` to replace `/img/tasks/demo` at now ?
> 
> Yeah, after [apache/dolphinscheduler-website#789](https://github.com/apache/dolphinscheduler-website/pull/789) we can do that

Ok, I will do this task.
