### ISSUE TITLE
[Bug][DataSource] delete the password and test again, it is successful without password

### ISSUE THREAD

**Issue by wqxs** [apache/dolphinscheduler#9428]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In the data source function module, I select the postgresql type data source. After the test is successful, I delete the password for the test, or it is successful.

### What you expected to happen

![Uploading image.png…]()

### How to reproduce

Fill in the correct data source connection information first, after the test is successful, delete the password, and then test

### Anything else

The reason for the problem is because: the DataSourceClient created by dbType, user and jdbcUrl as the key when getting the DatasourceUniqueId in the 55th line of the DataSourceClientProvider, so the first DataSourceClient is found in the second test, So there will be cases where the test can be successful without a password

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lenboo** [comment]
The image upload failed, please try again.

**Comment by wqxs** [comment]
![image](https://user-images.githubusercontent.com/69672009/162661663-cf221498-5ddb-42a5-9f01-13d85ce971de.png)

**Comment by wqxs** [comment]
> The image upload failed, please try again.
![162661663-cf221498-5ddb-42a5-9f01-13d85ce971de](https://user-images.githubusercontent.com/69672009/162662064-9413603e-27ed-41b0-ab79-c5fac5ad32fc.png)
