### ISSUE TITLE
[Bug] [UI Next] miss fixvalue input

### ISSUE THREAD

**Issue by zengqiyan** [apache/dolphinscheduler#9430]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

miss fixvalue input
<img width="720" alt="3246c3d1-c1ce-4b26-9241-c3eb96985301" src="https://user-images.githubusercontent.com/16408555/162660501-0136fd8f-85f4-410f-972a-d280e091faa9.png">
<img width="705" alt="9f96b2a9-6501-4259-8d2f-ae3038a886d4" src="https://user-images.githubusercontent.com/16408555/162660633-911eb823-6e65-4fe8-8998-550f70426bcd.png">

### What you expected to happen

fix miss fixvalue input

### How to reproduce

open data quality , comparison type  select fixValue

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by labbomb** [comment]
@zengqiyan Will you still submit pr

**Comment by zengqiyan** [comment]
已收到，谢谢
