### ISSUE TITLE
[Bug] [Standalone] start standalone server fail in idea

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#9433]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/11962619/162662730-8e895528-8393-4e13-a079-e64bf8412322.png)

But I can not find  the `pythonGatewayServer` in code.

### What you expected to happen

start standalone server successfully.

### How to reproduce

just run standalone in idea.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Hi @caishunfeng , I test latest dev code locally and it work. Could you make sure do you flush you maven in you IDEA?
