### ISSUE TITLE
[Bug] [APIserver] keep error of hive db not exist 

### ISSUE THREAD

**Issue by fankun895361652** [apache/dolphinscheduler#9437]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

从ds页面创建成功一个hive数据源后，到hive里面执行命令把这个ds对应的db删除，过了大概20分钟左右，apiserver就开始报连接不上db的错误，而且是一直报错，导致hive连接数被占满。从页面创建这个数据源以后，就没有在ds任何一个地方使用过这个数据源。

### What you expected to happen

只有在使用的时候报 连接不上的错误

### How to reproduce

1. 页面创建hive数据源，选择某一个hive存在的数据库 比如 testdb，添加成功
2. beeline 登录1步骤创建的db所在hive，并执行命名 drop database testdb;
3. 观察apiserver.日志，发现大约20分钟多后(或者直接去页面编辑1步骤创建的数据源，点击测试连接) 开始报此数据库不存在的错误，而且一直循环，最终导致hive连接数过大

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @fankun895361652 Thanks for your issue and looking forward to your bugfix pr.
But next time you should use Englist to describe issue, which can make more developers understand, thanks.
