### ISSUE TITLE
[Feature][Doc] Brief explanation needed for statistics

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#9441]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Currently official docs of dolphin scheduler metrics is only a screenshot. At least we need a brief explanation for what those metrics mean. 
* https://dolphinscheduler.apache.org/en-us/docs/dev/user_doc/guide/homepage.html

### Use case

* As described above.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
There is indeed a problem with this. When the official website is set to Chinese, the screenshot should correspond to the screenshot in Chinese. This eliminates the need for the meaning of the corresponding field. PTAL @zhongjiajie

**Comment by zhongjiajie** [comment]
Hi @songjianet I think we should add some short descriptions in our documents only, but only keep our screenshot in English version. Is hard to maintain when we have both English and Chinese version of screenshots, special when we change UI and some may forget to change one of the version.
BTW, Our developers seem often forget upgrade screenshots so I think it better to have less screenshots as possible

**Comment by EricGao888** [comment]
Okay...Since I'm working on #9324, I will take this one as well.

**Comment by EricGao888** [comment]
WIP. To be accurate, they are statistics instead of metrics.

**Comment by EricGao888** [comment]
@songjianet @zhongjiajie Could you please help remove the `stale` label? THX

**Comment by zhongjiajie** [comment]
> @songjianet @zhongjiajie Could you please help remove the `stale` label? THX

done

**Comment by EricGao888** [comment]
Related files:
* https://github.com/apache/dolphinscheduler/blob/dev/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DataAnalysisController.java
* https://github.com/apache/dolphinscheduler/blob/dev/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/DataAnalysisService.java
* https://github.com/apache/dolphinscheduler/blob/dev/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataAnalysisServiceImpl.java

**Comment by abzymeinsjtu** [comment]
interested in this one, better to be my first issue

**Comment by EricGao888** [comment]
> interested in this one, better to be my first issue

@abzymeinsjtu Thx for helping out~Enjoy contributing!

**Comment by zhongjiajie** [comment]
Because is a feature, so I change it to 310 milestone
