### ISSUE TITLE
[Feature][Doc] Improve the description of code inspection specification.

### ISSUE THREAD

**Issue by czeming** [apache/dolphinscheduler#9449]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

~~The code review CI contains restrictions on the order of automatic import packages. Developers who are not familiar with the configuration may turn off automatic import or ignore it.~~

~~org.apache.dolphinscheduler.spi.params.base.PluginParams~~

~~Adding the description of automatic import package sequence configuration is expected to improve the code audit CI pass rate or development efficiency.~~

~~To this page `https://dolphinscheduler.apache.org/zh-cn/community/development/pull-request.html`~~

It's the current configuration.

```
        <module name="ImportOrder">
            <property name="staticGroups" value="org.apache.dolphinscheduler,org.apache,java,javax,org,com"/>
            <property name="separatedStaticGroups" value="true"/>

            <property name="groups" value="org.apache.dolphinscheduler,org.apache,java,javax,org,com"/>
            <property name="ordered" value="true"/>
            <property name="separated" value="true"/>
            <property name="option" value="top"/>
            <property name="sortStaticImportsAlphabetically" value="true"/>
        </module>
```

After I imported `checkstyle.xml`, it looked like this.

![](https://s2.loli.net/2022/05/06/T49atsfCKgYeOlr.png)

It will lead like this. (`org.apache.dolphinscheduler.spi.params.base.PluginParams` when I used shortcut `option+command+O`)

![](https://s2.loli.net/2022/05/06/beA4VTM6xmundfL.png)

I think this's what the configuration we hope.

![](https://s2.loli.net/2022/05/06/lV8vd74Xazgu31N.png)

Before now, I've tried make it work, but it didn't work on it. So I found the source.

`https://github.com/jshiell/checkstyle-idea/blob/ac7a6b16c065848d0de9d1985e0f97fda38634c8/src/main/java/org/infernus/idea/checkstyle/importer/modules/ImportOrderImporter.java`
```
        switch (staticImportPosition) {
            case TOP:
                // remove other instances of PackageEntry.ALL_OTHER_STATIC_IMPORTS_ENTRY from the table
                // iterate from the end so we can remove elements without having to modify the index afterwards
                for (int x = settings.IMPORT_LAYOUT_TABLE.getEntryCount() - 1; x >= 0; x--) {
                    if (settings.IMPORT_LAYOUT_TABLE.getEntryAt(x) == PackageEntry.ALL_OTHER_STATIC_IMPORTS_ENTRY) {
                        settings.IMPORT_LAYOUT_TABLE.removeEntryAt(x);
                    }
                }
                settings.IMPORT_LAYOUT_TABLE.insertEntryAt(PackageEntry.ALL_OTHER_STATIC_IMPORTS_ENTRY, 0);
                break;
            case BOTTOM:
```

At present, I think there are two possible ways to deal with it.
1. make an issue for `checkstyle-idea`
2. Modify `checkstyle.xml` or accept the status quo.

Look forward to other solutions.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by thisisnige** [comment]
![image](https://user-images.githubusercontent.com/7918588/163094917-9f1342fd-5ae3-423b-9476-f43c4ef5afa7.png)
cluster deployment also has this problem

**Comment by caishunfeng** [comment]
> ![image](https://user-images.githubusercontent.com/7918588/163094917-9f1342fd-5ae3-423b-9476-f43c4ef5afa7.png) cluster deployment also has this problem

Hi @thisisnige it's not the same thing, please submit another issue, thanks.

**Comment by zhongjiajie** [comment]
@czeming could you please check whether this rule already in our `check-style.xml` or not?

**Comment by czeming** [comment]
> @czeming could you please check whether this rule already in our `check-style.xml` or not?

I compared it, and now I only see: 
1. `separatedStaticGroups` will not take effect after being imported (it will not appear in `Import Layout`)

I can try how to make it work. If there are other rules that need to be repaired, you can also tell me.

**Comment by zhongjiajie** [comment]
> I can try how to make it work

Great and looking forward to it.
> If there are other rules that need to be repaired, you can also tell me

I do not know is there any other error too 🤣

**Comment by czeming** [comment]
> > I can try how to make it work
> 
> Great and looking forward to it.
> 
> > If there are other rules that need to be repaired, you can also tell me
> 
> I do not know is there any other error too 🤣

I've tried this. It didn't work on it.

> ```https://github.com/jshiell/checkstyle-idea/blob/ac7a6b16c065848d0de9d1985e0f97fda38634c8/src/main/java/org/infernus/idea/checkstyle/importer/modules/ImportOrderImporter.java```
> 
> `org.infernus.idea.checkstyle.importer.modules.ImportOrderImporter#processOptionAttribute`

This's the source code for processing `ImportOrder`, I think it just supports `staticGroups` on `option=under`.

@zhongjiajie

**Comment by zhongjiajie** [comment]
Hi @kezhenxu94 do you have time to take a look? does check-style support `static` import sort?

**Comment by kezhenxu94** [comment]
I can see the configuration takes effect after importing the checkStyle.xml

<img width="944" alt="image" src="https://user-images.githubusercontent.com/15965696/165442137-5dece4b1-6ec4-4695-9db3-13712211d23b.png">

**Comment by zhongjiajie** [comment]
@czeming could you make a double-check about this issue?

**Comment by czeming** [comment]
> I can see the configuration takes effect after importing the checkStyle.xml
> 
> <img alt="image" width="944" src="https://user-images.githubusercontent.com/15965696/165442137-5dece4b1-6ec4-4695-9db3-13712211d23b.png">


**This reply is summarized into the issue description**


It's the current configuration.
```
<property name="staticGroups" value="org.apache.dolphinscheduler,org.apache,java,javax,org,com"/>
...
<property name="option" value="top"/>
```

You can see this code.
`https://github.com/jshiell/checkstyle-idea/blob/ac7a6b16c065848d0de9d1985e0f97fda38634c8/src/main/java/org/infernus/idea/checkstyle/importer/modules/ImportOrderImporter.java`
```
        switch (staticImportPosition) {
            case TOP:
                // remove other instances of PackageEntry.ALL_OTHER_STATIC_IMPORTS_ENTRY from the table
                // iterate from the end so we can remove elements without having to modify the index afterwards
                for (int x = settings.IMPORT_LAYOUT_TABLE.getEntryCount() - 1; x >= 0; x--) {
                    if (settings.IMPORT_LAYOUT_TABLE.getEntryAt(x) == PackageEntry.ALL_OTHER_STATIC_IMPORTS_ENTRY) {
                        settings.IMPORT_LAYOUT_TABLE.removeEntryAt(x);
                    }
                }
                settings.IMPORT_LAYOUT_TABLE.insertEntryAt(PackageEntry.ALL_OTHER_STATIC_IMPORTS_ENTRY, 0);
                break;
            case BOTTOM:
```

The question is`IntelliJ` only imports `static all other import`.

I've been a little busy recently, so I didn't update latest discussion  in the issue content.
what I expect support static import sort. (Please ignore the content of `import with '*'`, I used the screenshot from the past.)
![](https://s2.loli.net/2022/04/12/bwsKRJxYTAlEHIS.png)

Maybe I need to make an issue for `checkstyle-idea`.

@zhongjiajie @kezhenxu94

**Comment by kezhenxu94** [comment]
> Maybe I need to make an issue for checkstyle-idea.

Please do so, let's close this issue for now and if you have any further progress, let us know, thanks!
