### ISSUE TITLE
[Bug] [UI] Storage XSS 

### ISSUE THREAD

**Issue by kindragos** [apache/dolphinscheduler#9453]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Create a project, type "<img src=x onerror=alert('ye!')>" in the project description, and then confirm. Then, in the item list, when the cursor passes through the item description, a window will pop up.
![123](https://user-images.githubusercontent.com/31087454/162913350-16a36b51-b7c2-42ff-83cd-d6e0bf792d2f.png)

### What you expected to happen

Will cause storage XSS.

### How to reproduce

do WHAT HAPPENED

### Version

1.3.9

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
>type "<img src=x onerror=alert('ye!')>" in the project description

Why would you do that?

**Comment by kindragos** [comment]
> > type "<img src=x onerror=alert('ye!')>" in the project description
> 
> Why would you do that?

Company security scan

**Comment by caishunfeng** [comment]
> Company security scan

Hi @kindragos , can you check this issue of latest 2.0.5 version?

**Comment by caishunfeng** [comment]
PTAL @songjianet

**Comment by kindragos** [comment]
> > Company security scan
> 
> Hi @kindragos , can you check this issue of latest 2.0.5 version?

Your idea is right. I don't have 2.0.5 in my hand. I asked others to help measure it. There was no pop-up window.

**Comment by caishunfeng** [comment]
> Your idea is right. I don't have 2.0.5 in my hand. I asked others to help measure it. There was no pop-up window.

OK, thanks your feedback. Version 2.0.x is recommended with many improvements. 
I will close this issue.
