### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Beta] Missing feature: Enter sub workflow

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#9461]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Missing feature: enter sub workflow

<img width="981" alt="image" src="https://user-images.githubusercontent.com/29528966/162951601-2e6dd870-fa1f-43ce-b03b-70d8e9597661.png">

### What you expected to happen

add "enter sub workflow"

### How to reproduce

1. Create "sub"_ process“

2. Double click or edit "sub workflow"

3. Click "enter sub workflow" in the upper right corner of the edit box to enter the corresponding sub workflow

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by labbomb** [comment]
i will fix it
