### ISSUE TITLE
[Improvement][UI] Workflow goes online together with the timed cron

### ISSUE THREAD

**Issue by exmy** [apache/dolphinscheduler#9469]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, there are two steps when the timed cron goes online:

1. release online workflow
2. go to the cron manager page, release online timed cron

It will have a better experience if we can release online workflow together with the timed cron when it exists.

### Use case

As show below: 
when clicking online button, a prompt box pops up for the user to choose whether to release online with timed cron.

![image](https://user-images.githubusercontent.com/18643308/163118350-2b0f5323-4517-40b9-87fc-0dfef8832ae9.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Good idea. And I think we can remove the cron list page if make sure that at most one cron pre workflow.

**Comment by exmy** [comment]
yeah, if one cron per workflow, we may design more convenient operation page for workflow and cron.
