### ISSUE TITLE
[Feature][dev] Add test script or wrapper verify on our shell script

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#9474]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Ref https://github.com/apache/dolphinscheduler/issues/9471. For now, we do not have auto tests in our shell script in `bin` directory in our distribute package. Because most of the users will use those to set up DolphinScheduler cluster. And we do not have any test on this script.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I'd like to take this issue. Please assigned to me. @zhongjiajie

**Comment by zhongjiajie** [comment]
> I'd like to take this issue. Please assigned to me. @zhongjiajie

@SbloodyS  Looking forward, please notice that those scripts also could deploy DolphinScheduler in multiple machine, I am not sure wether Github action could do that
BTW, as a committer, you could assign the issue to you if you interesting in it
