### ISSUE TITLE
[Bug] [ui] Cannot select  more than one post node in condition task.

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#9479]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="872" alt="image" src="https://user-images.githubusercontent.com/29528966/163169093-c576f4bb-aeb7-42f6-8e30-c69703472651.png">

### What you expected to happen

Cannot select  more than one post node in condition task.

### How to reproduce

add a condition task

select two post node of condition 

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
This bug seems not to be reproduced.Maybe you can provide more details on how to reproduce.
