### ISSUE TITLE
[Feature][K8S] Support ingress annotations

### ISSUE THREAD

**Issue by chncaesar** [apache/dolphinscheduler#9486]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I have a DolphinScheduler instance on Azure K8S cluster. The DolphinScheduler's API service is exposed to public network through by nginx ingress. To allow certain IP ranges to access DolphinScheduler, nginx ingress white list is configured, for instance:
```text
ingress:
  enabled: true
  path: "/dolphinscheduler"
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/14
```

I'd like to contribute this to the community.

中文版：
我们使用 nginx-ingress 暴露 Azure K8S集群部署的 DolphinScheduler API service至公网，方便查看、运维DolphinScheduler。
但是，公网访问带来了安全隐患，因而使用 nginx-ingress 的 IP 白名单功能限制。例子：
```text
ingress:
  enabled: true
  path: "/dolphinscheduler"
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/14
```

我们希望贡献到 DolphinScheduler 社区

### Use case

In K8S,  setup dolphinscheduler ingress IP whitelist and enhance security .

**中文**
在k8S集群，可以为 DolphinScheduler Ingress 设置 IP 白名单

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
close by @9492
