### ISSUE TITLE
[Feature][UI Next][V1.0.0-Beta] Front-end optimization.

### ISSUE THREAD

**Issue by songjianet** [apache/dolphinscheduler#9489]
### Optimization

- [ ] [Feature][UI Next][V1.0.0-Beta] After an error message appears in the form verification, click the switch language button, the error message is not updated to the error message of the corresponding language
- [ ] [Feature][UI Next][V1.0.0-Beta] The scroll bar on the right side of the task component popup box is optimized, using the scroll bar of `Naive-UI`
- [ ] [Feature][UI Next][V1.0.0-Beta] Optimize the `code` and `id` parameter passing methods in `API` , no longer use the object form
- [ ] [Feature][UI Next][V1.0.0-Beta] Add form search component to replace all form search functions in the project
- [ ] [Feature][UI Next][V1.0.0-Beta] Unified use of `Naive-UI Card` , delete the `Card` packaged in the project
- [x] #9603
- [ ] [Feature][UI Next][V1.0.0-Beta] All processes in the project are replaced by workflow, and the concept of process no longer exists
- [ ] [Feature][UI Next][V1.0.0-Beta] Supplementary data types returned by the table interface
- [ ] [Feature][UI Next][V1.0.0-Beta] Types of supplemental table row data
- [ ] [Feature][UI Next][V1.0.0-Beta] `Security -  Tenant Manage` added blur and input for form validation
- [ ] [Feature][UI Next][V1.0.0-Beta] `Resource` provide and inject optimizations in `File Manage`
- [ ] [Feature][UI Next][V1.0.0-Beta] The `default` field in `props` uses arrow functions for arrays and objects
- [ ] [Feature][UI Next][V1.0.0-Beta] Size of table component in unity project
- [ ] [Feature][UI Next][V1.0.0-Beta] Size of form components in unity project
- [ ] [Feature][UI Next][V1.0.0-Beta] Unify the styles and icons of table action buttons in a project
- [x] #9537
- [ ] [Feature][UI Next][V1.0.0-Beta] Modify the Chinese comments in the project
- [ ] [Feature][UI Next][V1.0.0-Beta] Digital flopper font color consistency problem
- [ ] [Feature][UI Next][V1.0.0-Beta] Unified handling of the problem of positive integer input boxes in projects
- [ ] [Feature][UI Next][V1.0.0-Beta] Optimize the handling of `header-extra` in the `Modal` component, changing it to a slot
- [x] #9493 
- [x] #9510
- [x] #9520

**Comment by labbomb** [comment]
i will fix remove spaces from all input boxes

**Comment by songjianet** [comment]
I will fix change the css style usage of the blue number flopper in the alarm center to css variables

**Comment by songjianet** [comment]
i will handle `Monaco Editor` supports theme switching function.

**Comment by labbomb** [comment]
i will handle style the log component in a unified project

**Comment by labbomb** [comment]
I will remove the method of downloading files from the file in the request package and add a separate tool file
