### ISSUE TITLE
[Bug-FE] [UI Next][V1.0.0-Alpha] Repeated login problems

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9490]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

@Amy0104 

### What you expected to happen

When the page returns

### How to reproduce

Repeated login problems

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will fix it.
