### ISSUE TITLE
[Bug] 2.0.5 version compilation problem in Windows

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [apache/dolphinscheduler#9497]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![屏幕截图 2022-04-14 120437](https://user-images.githubusercontent.com/15922437/163311753-4f504482-6e56-4eee-951a-09b8985439d0.png)
基于2.0.5-release版本进行编译后的项目，在lib包中的jar格式不正常

### What you expected to happen

我期望可以打出正常格式的jar包

### How to reproduce

拉取2.0.5-release版本的代码进行下打包，就会出现打出的包不正常的情况

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Is there an error log?

**Comment by ITBOX-ITBOY** [comment]
> 



> Is there an error log?

This is not an error log, the name in the picture is the name of the jar package in the lib directory after I compiled, now I am not sure why the packaging is normal, but the jar in the lib directory in the compiled project is displayed in the wrong format

**Comment by ITBOX-ITBOY** [comment]
> Is there an error log?

I have already verified that it is in this problem

**Comment by ITBOX-ITBOY** [comment]
> Is there an error log?

How can I solve this problem now

**Comment by caishunfeng** [comment]
Please delete this error jar and try to run `mvn clean install -Prelease -Dmaven.test.skip=true` again.

**Comment by ITBOX-ITBOY** [comment]
> 请删除此错误 jar 并尝试再次运行。`mvn clean install -Prelease -Dmaven.test.skip=true`



> Please delete this error jar and try to run `mvn clean install -Prelease -Dmaven.test.skip=true` again.
The problem remains unsolved

**Comment by ITBOX-ITBOY** [comment]
> Please delete this error jar and try to run `mvn clean install -Prelease -Dmaven.test.skip=true` again.

The problem remains unsolved

**Comment by ITBOX-ITBOY** [comment]
> Please delete this error jar and try to run `mvn clean install -Prelease -Dmaven.test.skip=true` again.
The problem is not solved
Maybe there was a problem with the dolphinScheduler-dist configuration file

**Comment by ITBOX-ITBOY** [comment]
> Please delete this error jar and try to run `mvn clean install -Prelease -Dmaven.test.skip=true` again.

This problem only occurs when compiling on Windows, but works fine on Ubuntu

**Comment by caishunfeng** [comment]
Hi @ITBOX-ITBOY  it is recommended to compile and package on linux or mac. If you want to develop and test in local, you can run the standalone model, which can cover most scenarios.
