### ISSUE TITLE
[Improvement] [Api] Failed to create task group for non-root user

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#9499]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Failed to create task group for non-root user，Because there is no permission

![image](https://user-images.githubusercontent.com/11962619/163658969-f4a600a6-b8eb-45db-86bd-6effcf72f4f6.png)

### What you expected to happen

normal user can create task group too.

### How to reproduce

login a normal user and try to create task group.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by calvinjiang** [comment]
I'll check out this issue.
