### ISSUE TITLE
[Feature][server] clean up historical instances

### ISSUE THREAD

**Issue by exmy** [apache/dolphinscheduler#9500]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

As the ds system runs longer and longer, the data in the table will become larger and larger. 

It is not necessary to store long-term historical data, especially the table t_ds_task_instance.

We may have to design a reasonable mechanism to clean up historical data, like a month ago.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @exmy do you have some idea?
