### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Beta] Resource Centre dark mode display exception when create file

### ISSUE THREAD

**Issue by QuakeWang** [apache/dolphinscheduler#9507]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In the case of dark mode, use the File Manager in the Resource Centre to create the file. The display page will have extra white rectangles.

![image](https://user-images.githubusercontent.com/45645138/163385364-ef93248e-1762-4d6e-b25e-03d7f76696be.png)

### What you expected to happen

Clear the extra white box and the background color is shown in black.

### How to reproduce

1. Use of dark mode.
2. go to the Resource Center and click on File Manage
3. Choose to create a file.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by QuakeWang** [comment]
PTAL @songjianet

**Comment by songjianet** [comment]
I will fix it.
