### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Beta] Resource Center dark mode display exception when viewing the file details

### ISSUE THREAD

**Issue by QuakeWang** [apache/dolphinscheduler#9508]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In the case of dark mode, use the File Manager in the Resource Centre to view the file detail. The display page will have extra white rectangles.

![image](https://user-images.githubusercontent.com/45645138/163393057-470bd8fe-4538-42f8-a3e1-558eaa57345e.png)

### What you expected to happen

Clear the extra white box to display the file name properly.

### How to reproduce

1. Use of night mode.
2. accessing file management in the Resource Centre.
3. Select the created file to view the file details.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.
