### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Beta] log content cannot be full screen

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#9524]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![](https://vip1.loli.io/2022/04/16/UXOYRmJyhd5EqnA.png)

### What you expected to happen

above.

### How to reproduce

above.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
This problem is not unexpected and may be optimized in the Beta version. At that time, we will repackage a log component and unify all the log viewing styles in the project.

**Comment by labbomb** [comment]
i will fix it

**Comment by songjianet** [comment]
I will close this issue. Please check https://github.com/apache/dolphinscheduler/issues/9537.
