### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Beta] Environment variable options should be unselected

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#9529]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![](https://vip2.loli.io/2022/04/16/UOKm4tWEHNJTIgk.png)

### What you expected to happen

above.

### How to reproduce

above.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by labbomb** [comment]
i will fix it
