### ISSUE TITLE
[Question] [Datasource] datasource plugin 'presto' is not found

### ISSUE THREAD

**Issue by Meggie4** [apache/dolphinscheduler#9535]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

cannot create presto datasource
![1f2223a9851d472f39ae341015df7c4](https://user-images.githubusercontent.com/32348543/163705542-50b7593f-bf50-42b2-87be-f613ee245bf5.jpg)

### What you expected to happen

create presto datasource successful

### How to reproduce

when create presto datasource

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Presto datasource is not supported in 2.0.5. It will be supported in 3.0.0-alpha.

**Comment by Meggie4** [comment]
> 3.0.0-alpha

can I update to version 3.0.0-alpha now?

**Comment by SbloodyS** [comment]
3.0.0-alpha does not support upgrading from 2.0.5.

**Comment by Meggie4** [comment]
> 3.0.0-alpha does not support upgrading from 2.0.5.

so I should wait until 3.0.0-release finished?

**Comment by SbloodyS** [comment]
> > 3.0.0-alpha does not support upgrading from 2.0.5.
> 
> so I should wait until 3.0.0-release finished?

Yes. Or you can redevelop 2.0.5-release.
