### ISSUE TITLE
[Bug] upgrade httpclient due to cve

### ISSUE THREAD

**Issue by pjfanning** [apache/dolphinscheduler#9538]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

library has cve - https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient

### What you expected to happen

use security libs

### How to reproduce

n/a

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
@pjfanning PTAL at the PR, thanks!

**Comment by pjfanning** [comment]
seems that you need to update the license files too - see the CI build jobs that failed
