### ISSUE TITLE
[Bug] upgrade spring due to cves

### ISSUE THREAD

**Issue by pjfanning** [apache/dolphinscheduler#9541]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

need to use secure libs - https://mvnrepository.com/artifact/org.springframework/spring-core

### What you expected to happen

need secure libs

### How to reproduce

n/a

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pjfanning** [comment]
@songjianet I had a look at https://github.com/apache/dolphinscheduler/pull/9542 but it's getting fairly messy. There is a pre-existing circular dependency between 2 spring beans - and newer versions of spring seem to be stricter about it.

I'll probably need to leave this to someone who is more familiar with dolphinscheduler and testing it.

**Comment by Tianqi-Dotes** [comment]
suggest springcore to 5.3.18
refer to https://mvnrepository.com/artifact/org.springframework/spring-core

**Comment by zhongjiajie** [comment]
remove stale

**Comment by pjfanning** [comment]
I raised https://github.com/apache/dolphinscheduler/issues/11897
