### ISSUE TITLE
[Feature][Improvement] Support multi cluster environments - k8s type

### ISSUE THREAD

**Issue by qianli2022** [apache/dolphinscheduler#9544]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

first support k8s job to muti cluster

### Related issues

#9462 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
close due to the same issue #9462
