### ISSUE TITLE
[Feature][plug-in] Add Spark-K8s task in Spark task plug-in

### ISSUE THREAD

**Issue by qingwli** [apache/dolphinscheduler#9550]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Hi All, 

As we talked, we want to support Spark on K8s at the Spark task plug-in.

### Use case

We change the Spark task plug-in and add a button in `Deploy Mode` named K8s, and when you chose this button will show some inputs about namespace and Docker images, etc. And change the background code to support Spark on the K8s cluster.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
Hello @liqingwang, this feature is pretty cool and I'm quite looking forward to it. May I ask is there any update on this issue? Thx~

**Comment by qingwli** [comment]
Hi @EricGao888, We have finished the design and the code. But we are doing secondary development locally, version 2.0.5, with `dolphinscheduler-ui`. Also the `dolphinscheduler-ui` [will not be maintained soon](#9896 ). We will adapt and upgrade local to version 3.0.0-alpha this month, so you can see the pr of this feature next month.

**Comment by gaoyan1998** [comment]
Hello @liqingwang do you have any plans to support flink on k8s? Our project is migrating k8s recently, but dolphin has no way to detect k8s programs, thanks

**Comment by qingwli** [comment]
Hi @ikiler, we already support the Fink job on ds at the local version but have not yet pushed the code to the community. And my colleague from our team pushed the k8s task and k8s namespace to the community, you can see this pr. #8252, #9425, #9303. And at ds 3.0.0-beta1, you can see these two feature.

**Comment by gaoyan1998** [comment]
> Hi @ikiler, we already support the Fink job on ds at the local version but have not yet pushed the code to the community. And my colleague from our team pushed the k8s task and k8s namespace to the community, you can see this pr. #8252, #9425, #9303. And at ds 3.0.0-beta1, you can see these two feature.

I am using ds 3.0.0-beta1, but not found any card with k8s or like , only mesos in sea tunnel and k8s namespace  manager in Security center， Maybe I did something wrong? or next beta?

**Comment by qingwli** [comment]
The K8s task is in the `Task Definition` tab.

**Comment by gaoyan1998** [comment]
its the same with workflow, all of this, i am so sorry , i cant find
![ds1.png](https://s2.loli.net/2022/06/15/YeEJlgNCM1ZB5KO.png)
![ds2.png](https://s2.loli.net/2022/06/15/CZX7tqPulBMIYgx.png)
![ds3.png](https://s2.loli.net/2022/06/15/QdY5tuzD2UROjoG.png)

**Comment by EricGao888** [comment]
Looks like k8s task plugin was not included in 3.0.0-beta-1-release? https://github.com/apache/dolphinscheduler/tree/3.0.0-beta-1-release/dolphinscheduler-task-plugin

**Comment by qingwli** [comment]
Oh, I'm so sorry for that. I have checked the code and 3.0.0-beta-1 doesn't contain the K8s commit. If you want to try this feature, you can run the dev branch. And I don't know when to release this feature, maybe version 3.0.1?

**Comment by gaoyan1998** [comment]
> Oh, I'm so sorry for that. I have checked the code and 3.0.0-beta-1 doesn't contain the K8s commit. If you want to try this feature, you can run the dev branch. And I don't know when to release this feature, maybe version 3.0.1?

ok, thanks for the answer

**Comment by caishunfeng** [comment]
Hi, @liqingwang is there any update of this feature?

**Comment by qingwli** [comment]
Hi @caishunfeng , Yes We have finished the feature and now we are upgrading our platform to 3.1.0 and front part rewrite, after that we will plan to open a pr.

**Comment by qingwli** [comment]
Hi @caishunfeng , I remember that last meeting we talk about the spark job on k8s, and our solution is using the operation to manage the spark k8s job, and some people have some opinions about this piece, we want to know what's their attitude.

**Comment by caishunfeng** [comment]
> Hi @caishunfeng , I remember that last meeting we talk about the spark job on k8s, and our solution is using the operation to manage the spark k8s job, and some people have some opinions about this piece, we want to know what's their attitude.

@liqingwang can you add some design detail of this feature, and send a discussion email to `dev@dolphinscheduler.apache.org`?

**Comment by dpengpeng** [comment]
@liqingwang Hi, can your design about spark/flink on k8s support spark/flink Operator mode?

**Comment by qingwli** [comment]
Hi @dpengpeng , we already designed and finished spark/flink on k8s using operator mode, and we have the plan to contribute to the community about spark on k8s, and we want to know the attitude of the community how about we contribute the flink on k8s to the community? @caishunfeng

**Comment by caishunfeng** [comment]
related issue: 
- #10904

**Comment by caishunfeng** [comment]
> Hi @dpengpeng , we already designed and finished spark/flink on k8s using operator mode, and we have the plan to contribute to the community about spark on k8s, and we want to know the attitude of the community how about we contribute the flink on k8s to the community? @caishunfeng

Hi @liqingwang really good news if ds can support spark on k8s, looking forward to your pr.
And I found the issue of flink on k8s #10904, we can discuss in that issue.

**Comment by qingwli** [comment]
Hi @caishunfeng , sure, my co-workers will discuss it in that issue.
