### ISSUE TITLE
[Bug] sudo: unable to execute /bin/bash: Permission denied

### ISSUE THREAD

**Issue by fizzstrong** [apache/dolphinscheduler#9564]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

- The PRODUCTION environment dolphinscheduler has been up and running for some time with three nodes.  All tasks on the two nodes failed recently.

- The following error occurs in all tasks .
logs:
[INFO] 2022-04-18 16:29:58.728  - [taskAppId=TASK-164-1024398-1144432]:[115] - create dir success /tmp/dolphinscheduler/exec/process/5/164/1024398/1144432
[INFO] 2022-04-18 16:29:58.731  - [taskAppId=TASK-164-1024398-1144432]:[85] - shell task params {"rawScript":"echo  \"test test\"","localParams":[],"resourceList":[]}
[INFO] 2022-04-18 16:29:58.733  - [taskAppId=TASK-164-1024398-1144432]:[160] - raw script : echo  "test test"
[INFO] 2022-04-18 16:29:58.733  - [taskAppId=TASK-164-1024398-1144432]:[161] - task execute path : /tmp/dolphinscheduler/exec/process/5/164/1024398/1144432
[INFO] 2022-04-18 16:29:58.734  - [taskAppId=TASK-164-1024398-1144432]:[87] - tenantCode user:newoilcard_cpywl, task dir:164_1024398_1144432
[INFO] 2022-04-18 16:29:58.734  - [taskAppId=TASK-164-1024398-1144432]:[92] - create command file:/tmp/dolphinscheduler/exec/process/5/164/1024398/1144432/164_1024398_1144432.command
[INFO] 2022-04-18 16:29:58.734  - [taskAppId=TASK-164-1024398-1144432]:[111] - command : #!/bin/sh
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
source /opt/dolphinscheduler/conf/env/dolphinscheduler_env.sh
/tmp/dolphinscheduler/exec/process/5/164/1024398/1144432/164_1024398_1144432_node.sh
[INFO] 2022-04-18 16:29:58.737  - [taskAppId=TASK-164-1024398-1144432]:[334] - task run command:
sudo -u newoilcard_cpywl bash -x /tmp/dolphinscheduler/exec/process/5/164/1024398/1144432/164_1024398_1144432.command
[INFO] 2022-04-18 16:29:58.738  - [taskAppId=TASK-164-1024398-1144432]:[215] - process start, process id is: 18443
[INFO] 2022-04-18 16:29:58.749  - [taskAppId=TASK-164-1024398-1144432]:[224] - process has exited, execute path:/tmp/dolphinscheduler/exec/process/5/164/1024398/1144432, processId:18443 ,exitStatusCode:0
[INFO] 2022-04-18 16:29:58.750 org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread:[141] - task instance id : 1144432,task final status : FAILURE
[INFO] 2022-04-18 16:29:58.750 org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread:[161] - develop mode is: true
[INFO] 2022-04-18 16:29:59.739  - [taskAppId=TASK-164-1024398-1144432]:[129] -  -> sudo: unable to execute /bin/bash: Permission denied
[INFO] 2022-04-18 16:29:59.739  - [taskAppId=TASK-164-1024398-1144432]:[127] - FINALIZE_SESSION

- Manually running the command on the server succeeds:  sudo -u newoilcard_cpywl bash -x /tmp/dolphinscheduler/exec/process/5/164/1024398/1144432/164_1024398_1144432.command 
- Users who start DolphinScheduler have sudo permission  

### What you expected to happen

There is no solution at present

### How to reproduce

Unable to reproduce  

### Anything else

version is 1.3.6

### Version

1.3.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fizzstrong** [comment]
[Bug] sudo: unable to execute /bin/bash: Permission denied

**Comment by SbloodyS** [comment]
Sorry. 1.3.6-release is no longer in the maintaining list.

**Comment by zhongjiajie** [comment]
> Sorry. 1.3.6-release is no longer in the maintaining list.

Hi @fizzstrong, as @SbloodyS  said, we do not maintain version 1.3.6 anymore, I prefer to close this issue in this week in you do not have further information.

**Comment by zhaochenfeng** [comment]
请问dolphin在部署的时候，我的部署用户没有sudo权限，同时无法申请root权限怎么处理？

**Comment by zhongjiajie** [comment]
@zhaochenfeng  maybe you should ask your team to give you a user who has permission

**Comment by zhongjiajie** [comment]
> > Sorry. 1.3.6-release is no longer in the maintaining list.
> 
> Hi @fizzstrong, as @SbloodyS said, we do not maintain version 1.3.6 anymore, I prefer to close this issue in this week in you do not have further information.

close due to this

**Comment by fizzstrong** [comment]
> 请问dolphin在部署的时候，我的部署用户没有sudo权限，同时无法申请root权限怎么处理？
dolphin执行任务时 会使用  sudo -u执行，所以必须要有sudo权限。可以申请一个有sudo权限的用户，修改sudoer文件添加权限

**Comment by fizzstrong** [comment]
> > Sorry. 1.3.6-release is no longer in the maintaining list.
> 
> Hi @fizzstrong, as @SbloodyS said, we do not maintain version 1.3.6 anymore, I prefer to close this issue in this week in you do not have further information.

ok thanks，This problem has been solved。The reason is that the computer has been hardened by protective software
