### ISSUE TITLE
[Bug] [UI] multiple insecure npm libs used in dolphinscheduler-ui

### ISSUE THREAD

**Issue by pjfanning** [apache/dolphinscheduler#9570]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I used dependabot to check dolphinscheduler-ui/package.json

You can also use `npm audit` and `npm audit fix`

dolphinscheduler-ui-next seems not to have similar issues.

Example NPMs that need upgrades
* axios - https://github.com/advisories/GHSA-cph5-m8f7-6c5x and others
* jquery - https://github.com/advisories/GHSA-gxr4-xjj5-5px2 and others
* bootstrap
* node-sass

### What you expected to happen

secure libs

### How to reproduce

npm audit

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
At present, axios is applied to the new ui and the old ui, but the other three dependencies are currently applied to the old ui, but I don't understand what you mean by unsafe.

**Comment by pjfanning** [comment]
> At present, axios is applied to the new ui and the old ui, but the other three dependencies are currently applied to the old ui, but I don't understand what you mean by unsafe.

When I say 'unsafe', I mean there are open security advisories for all the components listed. dolphinscheduler is using old versions of these NPM libs. An example for axios is https://github.com/advisories/GHSA-cph5-m8f7-6c5x

**Comment by songjianet** [comment]
> > At present, axios is applied to the new ui and the old ui, but the other three dependencies are currently applied to the old ui, but I don't understand what you mean by unsafe.
> 
> When I say 'unsafe', I mean there are open security advisories for all the components listed. dolphinscheduler is using old versions of these NPM libs. An example for axios is [GHSA-cph5-m8f7-6c5x](https://github.com/advisories/GHSA-cph5-m8f7-6c5x)

I saw this, but this axios is a security issue less than version 21, which corresponds to our old ui. I don't know how you can deal with this problem. Is it a full upgrade of the dependency of the old ui?

**Comment by pjfanning** [comment]
So 'dolphinscheduler-ui-next' is intended to replace 'dolphinscheduler-ui' soon? If so, then I suppose old versions of NPMs in 'dolphinscheduler-ui' don't need upgrades.

**Comment by zhongjiajie** [comment]
> So 'dolphinscheduler-ui-next' is intended to replace 'dolphinscheduler-ui' soon? If so, then I suppose old versions of NPMs in 'dolphinscheduler-ui' don't need upgrades.

Actually, In our latest release, dolphinscheduler-3.0.0-alpha, our front end use module `dolphinscheduler-ui-next` instead of `dolphinscheduler-ui`. So I think we should ignore the unsafe issue, and we should discuss the day when we should totally remove the module `dolphinscheduler-ui` to make confuse of our users. (IMO, the time we release version `3.0.0` is a good date to announce it)

**Comment by zhongjiajie** [comment]
Seem we just totally remove the old `dolphinscheduler-ui` and rename `dolphinscheduler-ui-next` to  `dolphinscheduler-ui` in #9909, I think this issue could be close, cc @songjianet
