### ISSUE TITLE
[Improvement][server] varPool support "#{setValue(key=value)}"

### ISSUE THREAD

**Issue by exmy** [apache/dolphinscheduler#9576]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently var pool only support '${setValue(key=value)}', which has a limitation that value cannot reference other variables.

For example, 

```shell
d=$(date "+%F %H-%M-%S")
echo '${setValue(day=${d})}'
```
Since single quotes won't interpolate anything, we cannot use ${d} in ${setValue}, so I think we can support #{setValue(key=value)} to avoid this.

like follow:

```shell
d=$(date "+%F %H-%M-%S")
echo "#{setValue(day=${d})}"
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Will there be any changes to the front-end part here?

**Comment by exmy** [comment]
The front-end part does not need any change.

**Comment by songjianet** [comment]
> The front-end part does not need any change.

Thanks. I got it.

**Comment by zhongjiajie** [comment]
Looking great!

**Comment by zhongjiajie** [comment]
I know @jieguangzhou also thinks we should have this feature

**Comment by jieguangzhou** [comment]
good job.

**Comment by exmy** [comment]
thx, I will supplement this part of the document soon later.

**Comment by zhongjiajie** [comment]
> thx, I will supplement this part of the document soon later.

Oh, I even forget we should add the doc, you could change doc in https://github.com/apache/dolphinscheduler/tree/dev/docs/docs
