### ISSUE TITLE
[Feature][Improvement] Support the definition track URL on task

### ISSUE THREAD

**Issue by qingwli** [apache/dolphinscheduler#9582]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

As we talked, we want to support the definition track URL on task.

### Use case

We will change the task definition, and you can add a tracking URL for the task and view the button on the task instance, such as Spark UI for spark job and ELK URL for Spark Job.

We will design the website and change the database later, when we finished we will update this issue.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Whether this block is designed to modify the front-end part？

**Comment by qingwli** [comment]
@songjianet  Our team has a front-end colleague work with us to solve this issue. We will open a PR with all the code including backend and front-end later.
