### ISSUE TITLE
[Bug] [API] Deleting upstream dependencies of tasks results in duplicate data in t_ds_process_task_relation_log

### ISSUE THREAD

**Issue by brave-lee** [apache/dolphinscheduler#9584]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Deleting upstream dependencies of tasks results in duplicate data in t_ds_process_task_relation_log

### What you expected to happen

Normal data

### How to reproduce

call  /dolphinscheduler/projects/{projectCode}/process-task-relation/{taskCode}/upstream

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
Hi Jiny
Have approved the PR, could you help check the '/dolphinscheduler/projects/4928357584512/task-definition/5240600180736/with-upstream'
have similar issue.
The API function is at task instance page, first you create a new task instance, and next when you edit the task instance and submit, it will delete the related  t_ds_process_task_relation_log and the process name will missing.
Yours
