### ISSUE TITLE
[Bug] [worker] select on pg, zk lost contack

### ISSUE THREAD

**Issue by kindragos** [apache/dolphinscheduler#9587]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Task type: SQL
Data source: select the postgresql library I have added
SQL statement: select * from xxx

Run the workflow, and then see the following print in the worker.log:
![acc6897ffd664093efd5c16dca94cc6](https://user-images.githubusercontent.com/31087454/164353552-5eff7c1b-4ba0-4198-b992-658ef8c029db.png)

### What you expected to happen

I don't know.
"SELECT" works on MySQL, but not works on postgresql.

### How to reproduce

Let it work..

### Version

1.3.9

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Please complete the title of this question.

**Comment by SbloodyS** [comment]
Hi @kindragos , your picture cannot be displayed normally.

**Comment by kindragos** [comment]
> Hi @kindragos , your picture cannot be displayed normally.

There is something wrong with the uploading, I type some KEY info.

**Comment by caishunfeng** [comment]
It seems network connect error, but no sql error.

**Comment by kindragos** [comment]
> It seems network connect error, but no sql error.

Yes. It seems like that.

But I have no problem running "echo 111" on that worker.

What else can I do to find problems?

PS: The log picture was finally uploaded successfully!

**Comment by kindragos** [comment]
hello？
