### ISSUE TITLE
[Bug] [dolphinscheduler-server]  param lost when execute failed task

### ISSUE THREAD

**Issue by zwZjut** [apache/dolphinscheduler#9595]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

param lost when execute failed task  
branch 2.0.5 && dev

### What you expected to happen

param will not lost when execute failed task  

### How to reproduce

create processDefinition test
create task A set parameter a  and set  OUT
create task B dependent task A and use  parameter a; do something let task B 100% failed
run  processDefinition test and server will create processInstance test_xxxx
find test_xxxx in list and execute failed tasks,  when it is failed,  open the task log :
"setSqlParamsMap: No Property with paramName: a is found in paramsPropsMap of task instance with id"

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
@zwZjut hi, I cannot reproduce, could you provide your process definition script here? 
I passed a param from task A to task B and set task B timeout failure, but in my test, task B can reach the param value from task A.

**Comment by zwZjut** [comment]
![pic_1](https://user-images.githubusercontent.com/13324943/164200740-f3d8de64-0523-473c-9241-aca8ddaf6a5b.png)
![pic_2](https://user-images.githubusercontent.com/13324943/164200749-cb96fdb9-af99-4047-a593-1e71a98eb874.png)
![pic_3](https://user-images.githubusercontent.com/13324943/164200766-baf17141-fcce-4c35-a66d-5d6d33066b26.png)
![pic_4](https://user-images.githubusercontent.com/13324943/164200778-e5e58989-0878-4242-8971-2e3cccebcc7f.png)
![pic_5](https://user-images.githubusercontent.com/13324943/164200790-bf1d5b95-199a-48c8-ab5a-ca8ba0a630f4.png)

if you still cannot reproduce, connect me in wechat  by name of HY in ds group

**Comment by zwZjut** [comment]
you can also see difference between two tasks in meta data

**Comment by Tianqi-Dotes** [comment]
dev part code is fine， you can try dev

**Comment by zwZjut** [comment]
> dev part code is fine， you can try dev

will you cherry-pick to 2.0.6 ? is it easy to fix ?

**Comment by zwZjut** [comment]
this problem exists in 2.0.x
