### ISSUE TITLE
[Feature][UI Next][V1.0.0-Beta] Add front-end for Apache Zeppelin task plugin

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#9597]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Currently we have basic backend integration with `Apache Zeppelin` notebook in `dolphin scheduler zeppelin task plugin`. However, we need to add the front-end for this plugin.
* Related: #9201

### Use case

* Zeppelin task plugin will have corresponding front-end UI.

### Related issues

* See `Description` section.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment]
I'm not familiar with front-end, but I'd like to give a try. : )

**Comment by Amy0104** [comment]
> I'm not familiar with front-end, but I'd like to give a try. : )

If you have any problems, you can concat me or @songjianet.

**Comment by EricGao888** [comment]
> > I'm not familiar with front-end, but I'd like to give a try. : )
> 
> If you have any problems, you can concat me or @songjianet.

Cooooool! I appreciate it.
