### ISSUE TITLE
[Feature][doc] Add how to use UDF in SQL task

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#9601]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Documentation addition, should including

* the code UDF definition
* how dolphinscheduler work with UDF, and what command will be execute it
* how to use in SQL script

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by QuakeWang** [comment]
Please assign it to me : )

**Comment by QuakeWang** [comment]
This task has already been done. [UDF Manage](https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/resource/udf-manage.html)

**Comment by zhongjiajie** [comment]
Thanks and i will close it.

**Comment by zhongjiajie** [comment]
close by #9658
