### ISSUE TITLE
[BUG-FE][sql-task] Add UDF by name and show by id

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9612]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/76080484/164167867-46ce5eb1-b78d-413b-948a-82e06e967999.png)

![image](https://user-images.githubusercontent.com/76080484/164168281-6acc49b2-57e8-47ba-93f0-042eaace6d3f.png)

![image](https://user-images.githubusercontent.com/76080484/164168335-7d2a946c-da99-4a9e-9393-30336550978f.png)

### What you expected to happen

In SQL task(I use HIVE Datasource as in testing), first I add a UDF resource to the task by name, salve and exit the task definition dialog. When I reopen the SQL task, I should show UDF resource by name but it shows it by id.

### How to reproduce

in What Happened

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will fix it.
