### ISSUE TITLE
[FEATURE-FE][Task definition/Project][V1.0.0-Beta] create task title and task list title are different

### ISSUE THREAD

**Issue by SnowMoon-Dev** [apache/dolphinscheduler#9615]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

create task title and task list title is different

### What you expected to happen

create task title and task list title is same

### How to reproduce

1. create task
2. look at task list

### Anything else

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/42627702/164170118-cc9ba566-b95d-4736-805e-3831547ea361.png">

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
This does not use 300alpha, the dev environment also has this problem, I changed it to dev.
