### ISSUE TITLE
[Feature][UI-Next][V1.0.0-Beta] Refactor get dependent node information api

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#9618]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1. Using ```projects/list``` api to fetch all project list replacing ```projects/created-and-authed```
```
eg:
request:
curl -X GET "http://127.0.0.1:12345/dolphinscheduler/projects/list"

response:
{
  "code": 0,
  "msg": "success",
  "data": [
    {
      "id": 1, //project id
      "userId": 1,
      "userName": null,
      "code": 5249046055328,
      "name": "test", // project name
      "description": "",
      "createTime": "2022-04-20 15:09:32",
      "updateTime": "2022-04-20 15:09:32",
      "perm": 0,
      "defCount": 0,
      "instRunningCount": 0
    }
  ],
  "failed": false,
  "success": true
}
```

2. Using ```process-definition/query-process-definition-list``` to fetch all process definition info in a project.
```
eg:
request: 
curl -X GET "http://127.0.0.1:12345/dolphinscheduler/projects/5249046055328/process-definition/query-process-definition-list"

response:
{
  "code": 0,
  "msg": "success",
  "data": [
    {
      "code": 5249050625184, //process definition code
      "name": "workflow1", //process definition name
      "version": 1 //process definition version
    }
  ],
  "failed": false,
  "success": true
}
```

4. Using ```process-definition/query-task-definition-list``` to fetch all task definition info in a process definition.
```
eg:
request:
curl -X GET "http://127.0.0.1:12345/dolphinscheduler/projects/5249046055328/process-definition/query-task-definition-list" -d "processDefinitionCode=5249050625184"

response:
{
  "code": 0,
  "msg": "success",
  "data": [
    {
      "code": 5249047099680, //task definition code
      "name": "task1", //task definition name
      "version": 1 //task definition version
    },
    {
      "code": 5249048072864,
      "name": "task2",
      "version": 1
    },
    {
      "code": 5249049155232,
      "name": "task3",
      "version": 1
    }
  ],
  "failed": false,
  "success": true
}
```

5. Add dependent process/task status icon as we do in ```2.0.X``` version.
![](https://vip2.loli.io/2022/04/20/TSLCOHXcRwPaQgZ.png)

6. All queries are suggested to be cached in the current dependent node or current page.

### Related issues

#8922 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will follow up on this.
