### ISSUE TITLE
[Bug] [UI]Authorization display exception 

### ISSUE THREAD

**Issue by chinaboyll** [apache/dolphinscheduler#9629]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

当我在用管理员创建项目后，然后手动给项目所属用户设置普通用户。这时候再去安全中心中的用户管理查看赋值情况。会出现展示错误。

### What you expected to happen

我创建项目后，手动给项目所属用户设置普通用户，安全中心会同步赋权情况。

### How to reproduce

1、使用admin创建新项目
2、admin将所属用户更改为普通用户A
3、管理员去安全中心-用户管理-普通用户A-授权项目
发现授权项目异常。出现多个相同项目且并不是真实权限展示。

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
@chinaboyll 
English is required.
You can reopen it after updating content to english.
