### ISSUE TITLE
[Bug] [UI] Authorization display exception

### ISSUE THREAD

**Issue by chinaboyll** [apache/dolphinscheduler#9632]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I create a project with the administrator, and then manually set a normal user for the user to which the project belongs. At this time, go to the user management in the security center to check the assignment status. A display error will occur.

### What you expected to happen

After I create a project, I manually set a common user for the user to which the project belongs, and the Security Center will synchronize the authorization status.

### How to reproduce

Use admin to create a new project
admin changes the user to ordinary user A
The administrator goes to Security Center - User Management - Ordinary User A - Authorization Items
An exception was found for the authorization item. There are multiple identical items and it is not a real permission display.

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
I find out you mark you will submit pr to fix it, so i assign this issue to you now

**Comment by chinaboyll** [comment]
View version 3.0.0 introduction discovery, fixed。THX

**Comment by zhongjiajie** [comment]
It seems already fix in dev branch. do you have time to check it? @chinaboyll
