### ISSUE TITLE
[Feature][dependencies] Bump hadoop-common from 2.7.3 to 3.2.3

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#9639]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

https://github.com/apache/dolphinscheduler/pull/9464

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
Done in dev branch
