### ISSUE TITLE
[Feature][UI-Next] Add dependent process/task status icon as we do in 2.0.X version.

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#9647]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![](https://vip2.loli.io/2022/04/20/TSLCOHXcRwPaQgZ.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will follow up on this.
