### ISSUE TITLE
[BUG][UI] task group name echo exception

### ISSUE THREAD

**Issue by SnowMoon-Dev** [apache/dolphinscheduler#9655]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

task group name echo exception

### What you expected to happen

show default task group name or please select

### How to reproduce

1. create workflow
2. edit workflow

### Anything else

<img width="1968" alt="image" src="https://user-images.githubusercontent.com/42627702/164425526-cc9d0811-8bd9-4e45-8d4f-89cb9f014e25.png">

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
```dolphinscheduler-ui``` had been deprecated. Could you check whether ```dolphinscheduler-ui-next``` still has this problem? @SnowMoon-Dev

**Comment by SnowMoon-Dev** [comment]
ok, dolphinscheduler-ui-next no problem

**Comment by zhongjiajie** [comment]
I will close this issue now
