### ISSUE TITLE
[Bug] [Alert] alert-server start error

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [apache/dolphinscheduler#9660]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

`Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.apache.solr.client.solrj.impl.HttpClientUtil.createClient(HttpClientUtil.java:311)

The following method did not exist:

    org.apache.http.impl.client.HttpClientBuilder.evictIdleConnections(JLjava/util/concurrent/TimeUnit;)Lorg/apache/http/impl/client/HttpClientBuilder;

The method's class, org.apache.http.impl.client.HttpClientBuilder, is available from the following locations:

    jar:file:/opt/module/apache-dolphinscheduler-2.0.5-SNAPSHOT-bin/lib/httpclient-4.4.1.jar!/org/apache/http/impl/client/HttpClientBuilder.class

The class hierarchy was loaded from the following locations:

    org.apache.http.impl.client.HttpClientBuilder: file:/opt/module/apache-dolphinscheduler-2.0.5-SNAPSHOT-bin/lib/httpclient-4.4.1.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.apache.http.impl.client.HttpClientBuilder

2022-04-22 10:26:24.745  WARN 15043 --- [       Thread-4] c.a.n.common.http.HttpClientBeanHolder   : [HttpClientBeanHolder] Start destroying common HttpClient
2022-04-22 10:26:24.748  WARN 15043 --- [       Thread-4] c.a.n.common.http.HttpClientBeanHolder   : [HttpClientBeanHolder] Destruction of the end`

### What you expected to happen

Hope it starts properly

### How to reproduce

The alert-server can be restarted normally

### Anything else

没有

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @ITBOX-ITBOY ,Are you using the binary tar package in the official website?
