### ISSUE TITLE
[Improvement][Backend] Long precision might lost

### ISSUE THREAD

**Issue by Tianqi-Dotes** [apache/dolphinscheduler#9661]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

If the DS backend haven't deal with Long values passed to the frontend with Jackson or fastjson by default,
there might be precision issues when table id grow bigger to reach the maximum, due to the frontend `number` receiving Long values might lost precisions.

### Use case

Check whether DS needs to process Long value precision issues.
Ususally, we set fastjson settings to deal with Long precision issues. By default, change Long to String while passing,

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by paul8263** [comment]
Hi @Tianqi-Dotes ,
JavaScript `Number.MAX_SAFE_INTEGER` returns 2 to the power of 53 - 1, which is able to store int(x) in MySQL.

However not all `id` columns of the tables in DS are defined as int(x). Some of them are typed bigint(x). I don't know why we need this.

I think if there is not need to calculate or compare long value in the front end, it would be safe to convert them to strings, as configuring a global serializer for long type in Jackson.
