### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Beta] Running the same workflow, the parameter displays an error in last one 

### ISSUE THREAD

**Issue by jieguangzhou** [apache/dolphinscheduler#9674]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I run the same workflow, the parameter displays an error in the second time.The default values should actually be displayed，Not the value from the first run.

Figure 1 show the default value "123123" of key "a"
<img width="493" alt="image" src="https://user-images.githubusercontent.com/31528124/164706334-56bd62fd-4cc4-47d0-9a0c-d86f9882a31f.png">

Figure 2 is my first run
<img width="501" alt="image" src="https://user-images.githubusercontent.com/31528124/164706732-f2031e9d-8460-48c0-8fba-ebff85682aa3.png">

Figure 3 shows how I clicked on the workload again after the first run.
We can see that the value of key "a" is "asdfasdf", same as my first run.The values are self-filled, I didn't fill them in manually.
<img width="496" alt="image" src="https://user-images.githubusercontent.com/31528124/164707387-b0a0d826-eebb-4009-a995-5484e48fabfc.png">

### What you expected to happen

Restore default values (123123) quickly after I have runed the workflow 

### How to reproduce

If you can't reproduct, please run the second times quickly.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jieguangzhou** [comment]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/31528124/164707867-a37bee29-f6ec-49c2-994b-cf85997403ee.png">
Actually, the value of key "a" in the second instance is the default value of 123123" of "a"

**Comment by Amy0104** [comment]
I will follow up on this.
