### ISSUE TITLE
[Feature][Deploy] Add missing default values in dolphinscheduler_env.sh

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#9675]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* In the latest code, we have `dolphinscheduler_env.sh` to set environment variables. However, a few default values are missing. https://github.com/apache/dolphinscheduler/blob/88d2803fe1bd59b1fa719e3cddce1a9e7d1313e8/script/env/dolphinscheduler_env.sh#L33-L36
* Also, we need some examples and docs for Dolphin users about how to config `dolphinscheduler_env.sh`
* https://github.com/apache/dolphinscheduler/blob/dev/script/env/dolphinscheduler_env.sh

### Use case

* BTW, after building the project, we will have `./tools/bin/dolphinscheduler_env.sh` and `./bin/env/dolphinscheduler_env.sh`. May I ask why we need both of them?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
In fact, we can unite ```dolphinscheduler_env.sh``` into one.

**Comment by EricGao888** [comment]
> In fact, we can unite `dolphinscheduler_env.sh` into one.

Another question is, we already have https://github.com/apache/dolphinscheduler/blob/ebc4253d5020c0bf319561985c0c25bace5c283b/dolphinscheduler-tools/src/main/resources/application.yaml#L20-L24 to config db connection, why we need to config again in `dolphinscheduler_env.sh`? Could we remove duplicate db connection configuration in `dolphinscheduler_env.sh`?

**Comment by EricGao888** [comment]
> > In fact, we can unite `dolphinscheduler_env.sh` into one.
> 
> Another question is, we already have
> 
> https://github.com/apache/dolphinscheduler/blob/ebc4253d5020c0bf319561985c0c25bace5c283b/dolphinscheduler-tools/src/main/resources/application.yaml#L20-L24
> 
> to config db connection, why we need to config again in `dolphinscheduler_env.sh`? Could we remove duplicate db connection configuration in `dolphinscheduler_env.sh`?

Okay, I think I got it. DS has been refactored in micro-services fashion. Every module has its own `{module_name}/conf/application.yaml` after building the project. Therefore, it is definitely more reasonable for users to config `bin/env/dolphinscheduler_env.sh` so that the configuration will take effect globally.

**Comment by EricGao888** [comment]
After looking into other modules' start scripts, it seems even config `bin/env/dolphinscheduler_env.sh` will not take effect globally. In each module's start script except that of `worker-server`, it sources the `dolphinscheduler_env.sh` in its own `bin` folder instead of the global `bin/env/dolphinscheduler_env.sh`. Also each module's start script uses its own lib, which means if users use mysql driver, they need to add mysql-connector jar into every module's lib folder. Therefore, there are two problems:
* Why `worker-sever` uses the global `bin/env/dolphinscheduler_env.sh` but others don't? 
* Is there any way more convenient for users to config `dolphinscheduler_env.sh` or add extra jar, e.g. mysql-connector jar, into lib folder?

**Comment by SbloodyS** [comment]
> After looking into other modules' start scripts, it seems even config `bin/env/dolphinscheduler_env.sh` will not take effect globally. In each module's start script except that of `worker-server`, it sources the `dolphinscheduler_env.sh` in its own `bin` folder instead of the global `bin/env/dolphinscheduler_env.sh`. Also each module's start script uses its own lib, which means if users use mysql driver, they need to add mysql-connector jar into every module's lib folder. Therefore, there are two problems:
> 
> * Why `worker-sever` uses the global `bin/env/dolphinscheduler_env.sh` but others don't?
> * Is there any way more convenient for users to config `dolphinscheduler_env.sh` or add extra jar, e.g. mysql-connector jar, into lib folder?

For ```dolphinscheduler_env.sh```. I think it can be solved in a unified way for the following scenarios.

First of all by adding a variable like ```--envpath``` in each modules ```start.sh```.

1. For those users who want to use in ```docker``` deployment. Setting the default value of ```--envpath``` to ```source``` each module's own ```dolphinscheduler_env.sh``` when executing ```bash bin/start.sh``` in docker container's starting.
2. For those users who want to use in ```non docker and cluster``` deployment. Then specify ```--envpath  source ${DOLPHINSCHEDULER_HOME}/bin/env/dolphinscheduler_env.sh``` in ```start-all.sh/stop-all.sh/scp-hosts.sh/dolphinscheduler-daemon.sh```.
3. For thos users who want to use in ```user defined``` deployment. Then users can chose using the way of setting ```${DOLPHINSCHEDULER_HOME}/bin/env/dolphinscheduler_env.sh``` or By using ```bin/start.sh -- envpath``` to customize its own path.

If we do this. we should also modify the docs. WDYT? @EricGao888 @caishunfeng @zhongjiajie

**Comment by kezhenxu94** [comment]
> ### Description
> * In the latest code, we have `dolphinscheduler_env.sh` to set environment variables. However, a few default values are missing. https://github.com/apache/dolphinscheduler/blob/88d2803fe1bd59b1fa719e3cddce1a9e7d1313e8/script/env/dolphinscheduler_env.sh#L33-L36

Because we don't need to set these default, there default values are in `application.yaml`, we just `export` them so that they can be passed down to the start up script.

> * BTW, after building the project, we will have `./tools/bin/dolphinscheduler_env.sh` and `./bin/env/dolphinscheduler_env.sh`. May I ask why we need both of them?

`./bin/env/dolphinscheduler_env.sh` is used when you install all the components in a single machine by using `install.sh`, but mostly, in production, you will install each component in separate machine, in that case, you just copy `master-server` to the desired machine and only `./master-server/bin/dolphinscheduler_env.sh` is used, you won't be able to use `./bin/env/dolphinscheduler_env.sh` in that case

**Comment by SbloodyS** [comment]
> > ### Description
> > 
> > * In the latest code, we have `dolphinscheduler_env.sh` to set environment variables. However, a few default values are missing. https://github.com/apache/dolphinscheduler/blob/88d2803fe1bd59b1fa719e3cddce1a9e7d1313e8/script/env/dolphinscheduler_env.sh#L33-L36
> 
> Because we don't need to set these default, there default values are in `application.yaml`, we just `export` them so that they can be passed down to the start up script.
> 
> > * BTW, after building the project, we will have `./tools/bin/dolphinscheduler_env.sh` and `./bin/env/dolphinscheduler_env.sh`. May I ask why we need both of them?
> 
> `./bin/env/dolphinscheduler_env.sh` is used when you install all the components in a single machine by using `install.sh`, but mostly, in production, you will install each component in separate machine, in that case, you just copy `master-server` to the desired machine and only `./master-server/bin/dolphinscheduler_env.sh` is used, you won't be able to use `./bin/env/dolphinscheduler_env.sh` in that case

Yes. I got what you mean.

Some configurations are the same in the same cluster. Such as ```SPRING_DATASOURCE_DRIVER_CLASS_NAME``` and ```SPRING_DATASOURCE_URL```. This is a little more repetitive configuration work for users. Especially for those users who want to use ```pseudo-cluster``` deployment.

**Comment by kezhenxu94** [comment]
@SbloodyS what about, we don't `source` this https://github.com/apache/dolphinscheduler/blob/ec939fcc68a7587d4933d2e927a9f94ccff100d7/script/install.sh#L23-L24 , we just copy this file to override each component's `dolphinscheduler_env.sh`, so that users can only modify `$DS_HOME/bin/dolphinscheduler_env.sh`?

**Comment by SbloodyS** [comment]
> @SbloodyS what about, we don't `source` this
> 
> https://github.com/apache/dolphinscheduler/blob/ec939fcc68a7587d4933d2e927a9f94ccff100d7/script/install.sh#L23-L24
> 
> , we just copy this file to override each component's `dolphinscheduler_env.sh`, so that users can only modify `$DS_HOME/bin/dolphinscheduler_env.sh`?

Sounds like a good idea.

**Comment by zhongjiajie** [comment]
> Because we don't need to set these default, there default values are in application.yaml, we just export them so that they can be passed down to the start up script.

Will it change the setting when users export env before executing the bash script? ex

```sh
export SPRING_DATASOURCE_USERNAME=custom_usr
export SPRING_DATASOURCE_PASSWORD=custom_pwd
./bin/dolphinscheduler_daemon.sh start standalone-server
```

I think it will overwrite the default value in the application.yaml, Am I right?

**Comment by EricGao888** [comment]
> > Because we don't need to set these default, there default values are in application.yaml, we just export them so that they can be passed down to the start up script.
> 
> Will it change the setting when users export env before executing the bash script? ex
> 
> ```shell
> export SPRING_DATASOURCE_USERNAME=custom_usr
> export SPRING_DATASOURCE_PASSWORD=custom_pwd
> ./bin/dolphinscheduler_daemon.sh start standalone-server
> ```
> 
> I think it will overwrite the default value in the application.yaml, Am I right?

I've tried in dolphinscheduler_env.sh. It will overwrite the default username and password in the application.yaml. I will double-check whether it will work if directly export before start standalone-server.

**Comment by kezhenxu94** [comment]
> > > Because we don't need to set these default, there default values are in application.yaml, we just export them so that they can be passed down to the start up script.
> > 
> > 
> > Will it change the setting when users export env before executing the bash script? ex
> > ```shell
> > export SPRING_DATASOURCE_USERNAME=custom_usr
> > export SPRING_DATASOURCE_PASSWORD=custom_pwd
> > ./bin/dolphinscheduler_daemon.sh start standalone-server
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think it will overwrite the default value in the application.yaml, Am I right?
> 
> I've tried this. It will overwrite the default username and password in the application.yaml.

Yes, this is what we expected.

**Comment by EricGao888** [comment]
Just curious, why worker start script does not `source` `$WorkerDir/bin/dolphinscheduler_env.sh` as other module does?https://github.com/apache/dolphinscheduler/blob/ca98a4a14455210069dff0c7820c9a4fe556c6f3/dolphinscheduler-worker/src/main/bin/start.sh#L19-L33

**Comment by SbloodyS** [comment]
> Just curious, why worker start script does not `source` `$WorkerDir/bin/dolphinscheduler_env.sh` as other module does?
> 
> https://github.com/apache/dolphinscheduler/blob/ca98a4a14455210069dff0c7820c9a4fe556c6f3/dolphinscheduler-worker/src/main/bin/start.sh#L19-L33

May be it's a bug?

**Comment by kezhenxu94** [comment]
> Just curious, why worker start script does not `source` `$WorkerDir/bin/dolphinscheduler_env.sh` as other module does?
> 
> https://github.com/apache/dolphinscheduler/blob/ca98a4a14455210069dff0c7820c9a4fe556c6f3/dolphinscheduler-worker/src/main/bin/start.sh#L19-L33

It should be, I found it's modified in some PRs, can any of you @SbloodyS @zhongjiajie help to fix this?

**Comment by EricGao888** [comment]
> @SbloodyS what about, we don't `source` this
> 
> https://github.com/apache/dolphinscheduler/blob/ec939fcc68a7587d4933d2e927a9f94ccff100d7/script/install.sh#L23-L24
> 
> , we just copy this file to override each component's `dolphinscheduler_env.sh`, so that users can only modify `$DS_HOME/bin/dolphinscheduler_env.sh`?

This sounds a good idea! What about the `libs` folder? Seems not convenient for users to add mysql-java-connector-driver jar into that of all modules.

**Comment by SbloodyS** [comment]
> > Just curious, why worker start script does not `source` `$WorkerDir/bin/dolphinscheduler_env.sh` as other module does?
> > https://github.com/apache/dolphinscheduler/blob/ca98a4a14455210069dff0c7820c9a4fe556c6f3/dolphinscheduler-worker/src/main/bin/start.sh#L19-L33
> 
> It should be, I found it's modified in some PRs, can any of you @SbloodyS @zhongjiajie help to fix this?

Would you please help to do that in #9726 ? ^_^ @zhongjiajie

**Comment by SbloodyS** [comment]
> > @SbloodyS what about, we don't `source` this
> > https://github.com/apache/dolphinscheduler/blob/ec939fcc68a7587d4933d2e927a9f94ccff100d7/script/install.sh#L23-L24
> > 
> > , we just copy this file to override each component's `dolphinscheduler_env.sh`, so that users can only modify `$DS_HOME/bin/dolphinscheduler_env.sh`?
> 
> This sounds a good idea! What about the `libs` folder? Seems not convenient for users to add mysql-java-connector-driver jar into that of all modules.

I think it's more complicated than ```dolphinscheduler_env.sh``` file. So far, I have no idea about this.

**Comment by zhongjiajie** [comment]
> > Just curious, why worker start script does not `source` `$WorkerDir/bin/dolphinscheduler_env.sh` as other module does?
> > https://github.com/apache/dolphinscheduler/blob/ca98a4a14455210069dff0c7820c9a4fe556c6f3/dolphinscheduler-worker/src/main/bin/start.sh#L19-L33
> 
> It should be, I found it's modified in some PRs, can any of you @SbloodyS @zhongjiajie help to fix this?

I already add it in https://github.com/apache/dolphinscheduler/pull/9726/files#diff-73f7e68c3850aef6088318be24159ea1b59cb200dac2b883f3d4197d30c21b73

**Comment by SbloodyS** [comment]
> @SbloodyS what about, we don't `source` this
> 
> https://github.com/apache/dolphinscheduler/blob/ec939fcc68a7587d4933d2e927a9f94ccff100d7/script/install.sh#L23-L24
> 
> , we just copy this file to override each component's `dolphinscheduler_env.sh`, so that users can only modify `$DS_HOME/bin/dolphinscheduler_env.sh`?

Can this be added to #9726 ? Or I will open a new PR until #9726 is done? @zhongjiajie

**Comment by EricGao888** [comment]
> > > @SbloodyS what about, we don't `source` this
> > > https://github.com/apache/dolphinscheduler/blob/ec939fcc68a7587d4933d2e927a9f94ccff100d7/script/install.sh#L23-L24
> > > 
> > > , we just copy this file to override each component's `dolphinscheduler_env.sh`, so that users can only modify `$DS_HOME/bin/dolphinscheduler_env.sh`?
> > 
> > 
> > This sounds a good idea! What about the `libs` folder? Seems not convenient for users to add mysql-java-connector-driver jar into that of all modules.
> 
> I think it's more complicated than `dolphinscheduler_env.sh` file. So far, I have no idea about this.

Is it possible to add a `common-libs` dir, and add the dir into class path when running each module?

**Comment by zhongjiajie** [comment]
> > @SbloodyS what about, we don't `source` this
> > https://github.com/apache/dolphinscheduler/blob/ec939fcc68a7587d4933d2e927a9f94ccff100d7/script/install.sh#L23-L24
> > 
> > , we just copy this file to override each component's `dolphinscheduler_env.sh`, so that users can only modify `$DS_HOME/bin/dolphinscheduler_env.sh`?
> 
> Can this be added to #9726 ? Or I will open a new PR until #9726 is done? @zhongjiajie

Should I just add some command sync the file to each component's `dolphinscheduler_env.sh`? Are there situations we will overwrite the user's specific component setting is some time?

**Comment by SbloodyS** [comment]
> > > @SbloodyS what about, we don't `source` this
> > > https://github.com/apache/dolphinscheduler/blob/ec939fcc68a7587d4933d2e927a9f94ccff100d7/script/install.sh#L23-L24
> > > 
> > > , we just copy this file to override each component's `dolphinscheduler_env.sh`, so that users can only modify `$DS_HOME/bin/dolphinscheduler_env.sh`?
> > 
> > 
> > Can this be added to #9726 ? Or I will open a new PR until #9726 is done? @zhongjiajie
> 
> Should I just add some command sync the file to each component's `dolphinscheduler_env.sh`? Are there situations we will overwrite the user's specific component setting is some time?

When using ```start-all.sh``` or ```dolphinscheduler-daemon.sh start xxx-server``` to start cluster. We should overwrite each component's ```dolphinscheduler_env.sh```.
