### ISSUE TITLE
[Feature] Offer host name mapping of worker of Monitor page

### ISSUE THREAD

**Issue by buildupchao** [apache/dolphinscheduler#968]
Could you please offer host name mapping of worker of Monitor page?
Because we usually distinguish host usage based on business type.

Thanks & Regards,
buildupchao

------------------------------------------------------------------------------
请问是否可以在worker监控页面展示worker ip对应的主机名？
因为我们通常是根据不同的业务区分主机用途的，这样方便我们快速定位主机负载和使用情况。
![monitor_page](https://user-images.githubusercontent.com/25910406/66449913-36a96100-ea89-11e9-86a7-88f1b25f2ab0.png)

**Comment by dailidong** [comment]
good idea， we will consider it！ thx！
