### ISSUE TITLE
[Improvement][task-plugin] Add progress log during hive SQL execution

### ISSUE THREAD

**Issue by fengjian1129** [apache/dolphinscheduler#9680]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

During the execution of hive SQL task, print MapReduce progress log and obtain application_id allows developers to better track tasks

### Use case

When the hive SQL task is executed, the MapReduce progress log can be obtained through the log viewing interface

### Related issues

no

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MonsterChenzhuo** [comment]
@songjianet  Is it okay to leave this task to me to continue?

**Comment by zhuangchong** [comment]
@fengjian1129 Are you still solving this problem?

**Comment by fengjian1129** [comment]
@zhuangchong I have implemented it locally, but because the test class code detection has not been submitted, I hope you can help me solve it. If it still cannot be submitted, I can work with others to complete it

**Comment by fengjian1129** [comment]
@zhuangchong I want to pass the first submission, and then there are several codes to be submitted

**Comment by zhuangchong** [comment]
> I have implemented it locally, but because the test class code detection has not been submitted, I hope you can help me solve it. If it still cannot be submitted, I can work with others to complete it

@fengjian1129 You can submit a PR first and let us find out what the problem is before we can help you solve it. I see that the PRs associated with the above are closed

**Comment by fengjian1129** [comment]
@zhuangchong In the afternoon, I submit the code and check it for me

**Comment by MonsterChenzhuo** [comment]
@fengjian1129 No problem

**Comment by fengjian1129** [comment]
@zhuangchong @MonsterChenzhuo I have submitted the code, and hope to check it for me
