### ISSUE TITLE
[Bug-FE] [WorkFlow Instance] Workflow name copy function does not work

### ISSUE THREAD

**Issue by SnowMoon-Dev** [apache/dolphinscheduler#9682]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Workflow name copy function does not work

### What you expected to happen

The first click of the copy button does not work, the second click does

### How to reproduce

1. run workflow 
2. go to workflow instance
3. click workflow instance name
4. click the copy workflow instance name button

### Anything else

<img width="1881" alt="image" src="https://user-images.githubusercontent.com/42627702/164916029-58507c5d-6ac4-4767-8f50-579670ac5261.png">

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
