### ISSUE TITLE
[Bug][UI] Normal running workflow view instance log reports errors

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9685]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Normal running workflow view instance log reports errors

http://ds2:12345/dolphinscheduler/ui/projects/5230064904768/workflow/instances/6341?code=5291236005952

![image](https://user-images.githubusercontent.com/76080484/164955337-1c010f46-5f1a-48f8-9749-cb27f8df88d7.png)

### What you expected to happen

View logs normally

### How to reproduce

Normal running workflow view instance log reports errors

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
@XuXuClassMate next time please paste the error log but not the screenshot, we can use it directly. thanks.
