### ISSUE TITLE
[Bug] [Workflow Instance] The process definition not on line

### ISSUE THREAD

**Issue by devosend** [apache/dolphinscheduler#9686]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

- When the workflow is edited and re-run the workflow instance, it prompts the error message that the process definition is not online.

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/8847400/164955592-0a39c233-f581-434b-b78a-89e3febae7b3.png">

### What you expected to happen

Workflow instance can re-run normally.

### How to reproduce

- Create a workflow and set shell task or other sample task
- Online workflow and run it
- Offline workflow and edit it 
- Online workflow
- Open workflow instance and re-run instance

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by paul8263** [comment]
Hi @devosend ,
I cannot reproduce this. Could you please post some more details?

**Comment by chinaboyll** [comment]
I ran into the same problem.
