### ISSUE TITLE
[Bug] [WorkFlow] task group configuration does not support manual expansion

### ISSUE THREAD

**Issue by SnowMoon-Dev** [apache/dolphinscheduler#9688]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![test](https://user-images.githubusercontent.com/42627702/164957695-c7aab13a-9016-4edf-8e37-7e57b1d3cc49.gif)

### What you expected to happen

1. waiting tasks can run after manually modifying task group resources
2. task group resource cannot support scaling down

### How to reproduce

1. a task queue that runs the corresponding resource
2. manually modify task group resources
3. view task running status

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
I think you should determine the size of task group resource pool, instead of dynamically increasing or decreasing it after starting the workflow.

**Comment by SnowMoon-Dev** [comment]
> I think you should determine the size of task group resource pool, instead of dynamically increasing or decreasing it after starting the workflow.

the task queue actually belongs to the category of exclusive queues in other scheduling systems, but since it can be set, and manual adjustment should be supported when the queue is not enough
