### ISSUE TITLE
[Bug] [Next-UI][V1.0.0-Beta] Action buttons should be displayed on one line.

### ISSUE THREAD

**Issue by Amy0104** [apache/dolphinscheduler#9696]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The action buttons are displayed as two lines.
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/97265214/164960601-0c9be3d4-93ed-45fe-9392-cba25e8b0613.png">

### What you expected to happen

Action buttons should be displayed on one line.

### How to reproduce

1. Open the datasource page.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
