### ISSUE TITLE
[Bug-FE] [Workflow] Deformation of timeout alarm interface

### ISSUE THREAD

**Issue by SnowMoon-Dev** [apache/dolphinscheduler#9702]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Deformation of timeout alarm interface

### What you expected to happen

 reduce div space

### How to reproduce

1. create workflow
2. create node
3. save workflow
4. click timeout alarm button

### Anything else

<img width="1975" alt="image" src="https://user-images.githubusercontent.com/42627702/164965909-411548af-bcbc-40c0-a0c0-060dff7f8069.png">
<img width="1896" alt="image" src="https://user-images.githubusercontent.com/42627702/164967593-baba1059-47fd-49e8-9d5e-a935065e31a6.png">

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will fix it.
