### ISSUE TITLE
[Bug-RD] Workflow instance modification related fields are not saved

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9703]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Workflow instance modification related fields are not saved

### What you expected to happen

Workflow definition basic information changes saved successfully

### How to reproduce

![image](https://user-images.githubusercontent.com/76080484/164966155-17e9e8d4-a816-451d-8c7c-65fd4af85f00.png)

![image](https://user-images.githubusercontent.com/76080484/164966169-3ab77915-afaa-4b73-bd8f-09113f979904.png)

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
this one need further disscusion due to the basic information is from workflow instance.
