### ISSUE TITLE
[Bug] [Website] The Cluster doc is not update to 3.x still 2.x.x version

### ISSUE THREAD

**Issue by Tianqi-Dotes** [apache/dolphinscheduler#9704]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The Cluster doc is not update to 3.x still 2.x.x version

### What you expected to happen

The Cluster doc update to 3.x 

### How to reproduce

check https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/guide/installation/cluster.html

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
after https://github.com/apache/dolphinscheduler/pull/9726 merged, we have 3.0.0 doc in dev branch and dev docs https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/installation/cluster.html. and the docs will be released alone with 3.0.0-beta
