### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]SUB_PROCESS component execution completion display problem 

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9711]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

SUB_PROCESS component execution completion display problem

![image](https://user-images.githubusercontent.com/76080484/164968250-a2601626-dc86-40b5-8002-57c99dccb1a7.png)

### What you expected to happen

SUB_PROCESS component will not have host execution host, should be straight line logo, will not generate logs should hide the log display button, or enter the log details page prompt this component will not generate logs

### How to reproduce

SUB_PROCESS component execution

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will fix it.
