### ISSUE TITLE
[Bug-RD] Clicking Resume fails the workflow will continue to run

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9716]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Clicking Resume fails the workflow will continue to run

![image](https://user-images.githubusercontent.com/76080484/164971506-e74d9914-218a-4629-8a35-6e2f3efb5db0.png)

### What you expected to happen

Click Resume failed to stop running, or modify the click label to: Failed to retry

### How to reproduce

Running a failed workflow，Clicking Resume fails the workflow will continue to run

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
i thought this one is reasonable.

**Comment by Amy0104** [comment]
I will fix it.
