### ISSUE TITLE
[Bug] [WorkFlow] Failed to create workflow prompt parameter

### ISSUE THREAD

**Issue by SnowMoon-Dev** [apache/dolphinscheduler#9737]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Failed to create workflow prompt parameter

### What you expected to happen

1. save workflow

### How to reproduce

1. create workflow
2. save workflow

### Anything else

![Kapture 2022-04-25 at 10 13 42](https://user-images.githubusercontent.com/42627702/165009736-086901e2-19b5-4e18-903c-c9b0f69aa6e6.gif)

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
The picture is blurred, and the error message can't be seen clearly. Can you upload the picture again?

**Comment by caishunfeng** [comment]
![image](https://user-images.githubusercontent.com/11962619/165013766-5d6a1c6d-750a-4ffd-9e1e-282b255cf646.png)

**Comment by QuakeWang** [comment]
> ![image](https://user-images.githubusercontent.com/11962619/165013766-5d6a1c6d-750a-4ffd-9e1e-282b255cf646.png)

I also encountered this situation, which resulted in the workflow created not being saved properly for use.
