### ISSUE TITLE
[Bug] [ui]  Chinese Official website link error  link 

### ISSUE THREAD

**Issue by seagle-yuan** [apache/dolphinscheduler#9738]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I browsed the website of "https://dolphinscheduler.apache.org" and chose Chinese site.
then I click the botton of "quick start". then jump to the error page
 
error link : https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/guide/quick-start.html

![d1](https://user-images.githubusercontent.com/13429553/165009555-7ab95201-8ef1-43cd-9250-32035f88f8b1.JPG)

### What you expected to happen

fix error link

### How to reproduce

fix error link

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by labbomb** [comment]
i will fix it
