### ISSUE TITLE
[Bug] [task-api] ${setValue(key=value)} alyways not success

### ISSUE THREAD

**Issue by ruancheng77** [apache/dolphinscheduler#9745]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When mutli same work node exec,  always has one node exec error(setValue is not success).

### What you expected to happen

setValue should always suucess.

### How to reproduce

create a workflow with mutli same shell node.
shell script contain setValue expression.

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
hi, could you please provide specific script details to reproduce?

**Comment by ruancheng77** [comment]
![1650868536(1)](https://user-images.githubusercontent.com/23415499/165033310-8d1bc357-697f-4904-b581-d2681008966f.jpg)
![image](https://user-images.githubusercontent.com/23415499/165033382-b79a6aec-a47c-4928-bbf8-23558efb09b0.png)
![image](https://user-images.githubusercontent.com/23415499/165033443-a81cd88e-2e20-49b5-a543-12c3f9cb2c76.png)
![image](https://user-images.githubusercontent.com/23415499/165033526-ea66b9ec-5552-4838-8266-b2595b70a5de.png)
 **sub workflow num > 5**

**Comment by ruancheng77** [comment]
![image](https://user-images.githubusercontent.com/23415499/165035866-a1015a43-4077-40cb-a9fa-c2a85c331d2b.png)
![image](https://user-images.githubusercontent.com/23415499/165035922-eba92f2f-7d69-44b6-9b1a-16a63b2ee755.png)
You can create 10 group work like image. Every one exec always some node is error

**Comment by ruancheng77** [comment]
I found the bug is due to 
org.apache.dolphinscheduler.plugin.task.shell.ShellTask#handle => shellCommandExecutor.getVarPool() exec when 
org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor#parseProcessOutput => getOutputLogService is not finished.

**Comment by Tianqi-Dotes** [comment]
Dear ruancheng77,
 hi , I have tested this in version 205 and dev branch, it exactly have this issue in 2.x version but dev is fine and param can be passed to sub tasks.

**Comment by Tianqi-Dotes** [comment]
hi,
please refer to this pr changes:
https://github.com/apache/dolphinscheduler/pull/9442/files#diff-ce66488b6575537b256a7d85364c1d660aafcd4ce601e3a60a656732f18263ac
to modify the problem in 2.x version. I have tried to fix this problem refer to this pr and works.

**Comment by ruancheng77** [comment]
I think you seem to have misunderstood the root cause of the problem.
The problem I tested is that multithreading causes the shell script to use setValue syntax to set the variable value to pass out. Due to the influence of multithreading, the thread parsing setValue syntax may not parse in time, resulting in the lack of varpool.
![image](https://user-images.githubusercontent.com/23415499/167246966-867aea04-900e-4e1d-adb6-6e5ed2a9d301.png)

**Comment by zhongjiajie** [comment]
does it related to this issue? https://github.com/apache/dolphinscheduler/issues/9576

**Comment by ruancheng77** [comment]
No.
Parse setValue syntax in another thread. when workflow start multiple work at the same time, some work will finished before parse setValue thread is done.

My temp plan is waiting getLogoutputService is done then goto next.

**Comment by zhongjiajie** [comment]
remove stale

**Comment by brave-lee** [comment]
#10694
