### ISSUE TITLE
[Bug] [Module Name] The default node name and child node should not appear in the new sub component of the workflow instance

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9748]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The default node name and child node should not appear in the new sub component of the workflow instance

### What you expected to happen

The node name and child nodes should be empty by default

### How to reproduce

![image](https://user-images.githubusercontent.com/76080484/165032820-fe2a0998-8bcc-4f0a-86be-4e7c7b499ed7.png)

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will fix it.
