### ISSUE TITLE
[Bug-FE] [UI Next] Workflow instances do not support versioning, hide the version control button 

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9750]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Workflow instances do not support versioning, hide the version control button 

### What you expected to happen

hide the version control button

### How to reproduce

![image](https://user-images.githubusercontent.com/76080484/165036207-5720eca1-5bf7-4bea-8c33-40ec26ed71a3.png)

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
