### ISSUE TITLE
[Bug] [UI] cannot select the workload scheduling time

### ISSUE THREAD

**Issue by qianchutao** [apache/dolphinscheduler#9756]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

> On the front page, i cannot select the workload scheduling time

https://user-images.githubusercontent.com/72595723/165050360-34858dd7-9e0a-454e-bce1-1e9e76cdd716.mp4

### What you expected to happen

 On the front page, i cannot select the workload scheduling time

### How to reproduce

none

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
