### ISSUE TITLE
[Bug] Standalone doc do not  support alpha-3.0.0

### ISSUE THREAD

**Issue by lizhuangs** [apache/dolphinscheduler#9763]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

./bin/dolphinscheduler-daemon.sh: 38: ./bin/dolphinscheduler-daemon.sh: source: not found

### What you expected to happen

run it

### How to reproduce

download alpha-3.0.0-bin
Start DolphinScheduler Standalone Server 
`sh ./bin/dolphinscheduler-daemon.sh start standalone-server`

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This has been fixed in ```dev``` branch. Will be released in ```3.0.0-beta```.

I'll close this issue. You can reopen it if you have any other questions. @lizhuangs
