### ISSUE TITLE
[Bug] [Website] script, pagerduty, http alert plugin doc missing

### ISSUE THREAD

**Issue by Tianqi-Dotes** [apache/dolphinscheduler#9764]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

script, pagerduty, http alert plugin doc missing

### What you expected to happen

script, pagerduty, http alert plugin doc missing

### How to reproduce

script, pagerduty, http alert plugin doc missing
check website

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
close by https://github.com/apache/dolphinscheduler/pull/9765
