### ISSUE TITLE
[Bug] [dolphinscheduler-alert-email] send mail with attachment from sql task failed

### ISSUE THREAD

**Issue by Wilson-BT** [apache/dolphinscheduler#9767]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When we exec DML sql task，and send mail with attachment.it will fail with no exception.

### What you expected to happen

Send mail success.

### How to reproduce

As this image:
![image](https://user-images.githubusercontent.com/40427110/165202496-5e9273f9-9d3c-4394-961d-a2ae60b3c163.png)
the alert type is send mail like this：
![image](https://user-images.githubusercontent.com/40427110/165202733-67c7eadc-8510-40b7-84e2-3d4b54785cad.png)
it will not write a whole .xlsx file and send failed with no exception.

### Anything else

Hadoop-common and hadoop-client use common-compress-1.4.1, and  poi-ooxml use common-compress-1.19.1.
But the project maven package has only common-compress-1.4.1, it will cause ClassNotFoundError  when alert write xlsx-type file.

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Wilson-BT** [comment]
I just add  the flow exclusion code in dolphinscheduler/pom.xml to solve this problem.
But because i have no hadoop env，i can`t do some hadoop test.
```
<dependency>
                <groupId>org.apache.hadoop</groupId>
                <artifactId>hadoop-common</artifactId>
                <version>${hadoop.version}</version>
                <exclusion>
                        <groupId>org.apache.commons</groupId>
                        <artifactId>commons-compress</artifactId>
                </exclusion>
<dependency>
<dependency>
                <groupId>org.apache.hadoop</groupId>
                <artifactId>hadoop-client</artifactId>
                <version>${hadoop.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apache.commons</groupId>
                        <artifactId>commons-compress</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
<dependency>
                <groupId>org.apache.hadoop</groupId>
                <artifactId>hadoop-yarn-common</artifactId>
                <version>${hadoop.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apache.commons</groupId>
                        <artifactId>commons-compress</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
``

**Comment by Tianqi-Dotes** [comment]
@Wilson-BT hi, 205 exactly have this issue will cause function dead when you using attachments.
please refer to https://github.com/apache/dolphinscheduler/issues/7874
I will come back to the issue these days and will check the differences between dev and version 2.0.5

**Comment by Wilson-BT** [comment]
@Tianqi-Dotes The cause of the incident has been found out like my reply above. It`s caused by common-compress-1.4.1 and common-compress-1.19 version conflict, and the project maven package just has common-compress-1.4.1. Above is Just my solution.I don`t know if it suitable for hadoop project
