### ISSUE TITLE
[Bug] [Next-UI][V1.0.0-Beta] No new task group, task queue display data error

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9774]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

No new task group, task queue display data error

![image](https://user-images.githubusercontent.com/76080484/165218221-0d11dc77-4331-40de-8bdd-c5d391e1d91a.png)

### What you expected to happen

Task Group Queue Task display is empty

### How to reproduce

No new task group, task queue display data error

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by labbomb** [comment]
i will fix it
