### ISSUE TITLE
[Bug] [Next-UI][V1.0.0-Beta] Local log file cache is not cleared

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9780]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

View the first component log, when viewing the second component log, it is displayed as the first component log

![image](https://user-images.githubusercontent.com/76080484/165241868-aa9c8a62-026b-4be1-b098-d8a18f82dbcd.png)

### What you expected to happen

View the first component log, when viewing the second component log, it is displayed to see the second component log

### How to reproduce

View the first component log, when viewing the second component log, it is displayed as the first component log

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by labbomb** [comment]
i will fix it
