### ISSUE TITLE
[Bug] [DataSource] the password echo is empty

### ISSUE THREAD

**Issue by SnowMoon-Dev** [apache/dolphinscheduler#9799]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. the password echo is empty
2. search prompt information is not clear
3. the password input box should be required, according to security considerations

### What you expected to happen

1. the content of the password input box is replaced by *
2. the content of the search prompt box should be Please enter the data source name
3. password box is required

### How to reproduce

1. create datasource
2. edit datasource

### Anything else

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/42627702/165359988-722b1131-c52e-48c2-8746-5a643f171f4c.png">

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
It is not a bug that the password input box is empty. You can create another issue about search input
