### ISSUE TITLE
[Bug][Next-UI][V1.0.0-Beta] Logo disappeared when format dag.

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9806]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Logo disappeared when format dag

<img width="1881" alt="image" src="https://user-images.githubusercontent.com/76080484/165453602-ac0da123-b565-46de-b82f-45023fb506c8.png">

<img width="1645" alt="image" src="https://user-images.githubusercontent.com/76080484/165453689-cc5509c4-3ffa-463c-a626-0aae4cbf6724.png">

### What you expected to happen

Logo display normal

### How to reproduce

Open Workflow Instance and select instance into it.
Click Format button to format dag.

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
