### ISSUE TITLE
[Bug] [3.0.0-alpha Doc] path to docker does not exist and the 3.0.0-alpha image is not exist in docker hub

### ISSUE THREAD

**Issue by kurobanekid** [apache/dolphinscheduler#9807]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. ![image](https://user-images.githubusercontent.com/15232298/165457148-a41f1e1d-4b23-41b4-a8db-f3d9e1ef89b9.png)
The Chinese version has the same problem
2. Cannot pull 3.0.0-alpha image
<img width="978" alt="image" src="https://user-images.githubusercontent.com/15232298/165458765-f0045593-5263-4d81-9ae1-5eed8de49ff9.png">

### What you expected to happen

1. The path to docker folder should be `cd apache-dolphinscheduler-3.0.0-alpha-src/deploy/docker/`
2. Can pull 3.0.0-alpha image with `latest-alpha` tag from [docker hub](https://hub.docker.com/r/apache/dolphinscheduler/tags?page=1&ordering=last_updated)

### How to reproduce

Must appear

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Currently the ```3.0.0-alpha``` documentation is incomplete. We are fixing it ASAP. Thank you for your feedback. @kurobanekid

**Comment by kurobanekid** [comment]
When will the 3.0.0-alpha image be pushed? Or Are there any guidelines for building the 3.0.0-alpha environment locally?

**Comment by zhongjiajie** [comment]
@kurobanekid  in 3.0.0-alpha, we separate DolphinScheduler to multiple server, so we change the image name from `apache/dolphinscheduler` to `apache/dolphinscheduler-[standalone-server|api-server|worker-server|master-server|alert-server]` and we already update the doc in #9865
