### ISSUE TITLE
[Bug] [Next-UI][V1.0.0-Beta] Field Required Checks

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9809]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Project Name，Wrokflow Name，Task Name，Cycle Time，is a required field, otherwise the logic does not work

![image](https://user-images.githubusercontent.com/76080484/165478903-644bf267-4982-4a6c-9efb-fb47f5298a19.png)

### What you expected to happen

Project Name，Wrokflow Name，Task Name，Cycle Time，is a required field, otherwise the logic does not work

### How to reproduce

Project Name，Wrokflow Name，Task Name，Cycle Time，is a required field, otherwise the logic does not work

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
I will fix it.
