### ISSUE TITLE
[Feature][all] Remove unused dependencies

### ISSUE THREAD

**Issue by davidzollo** [apache/dolphinscheduler#9813]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

now, the modules of 3.0-alpha have many unused dependencies, and the total install package size has up to 800M,  this operation will reduce the total size, I think this is very useful 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Toms1999** [comment]
seesee
