### ISSUE TITLE
[Feature][Task Plugin] Add jupyter notebook task plugin

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#9816]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Similar as `zeppelin task plugin`, we can integrate `Dolphin Scheduler` with [Jupyter Notebook](https://jupyter.org/) through `jupyter task plugin`, providing AI scientists and engineers with some `MLOPS` features.
* We can use papermill in jupyter task plugin to execute jupyter notes. See [papermill](https://papermill.readthedocs.io/en/latest/) for details.
* related: #9201 #9814 

### Use case

* AI scientists & engineers will be able to develop ML/DL scripts interactive in `Jupyter Notebook` and schedule it from `Dolphin Scheduler` with 'one click'

### Related issues

* Already described above.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zwZjut** [comment]
jupyter notebook or jupyter hub is very easy to use

**Comment by EricGao888** [comment]
> jupyter notebook or jupyter hub is very easy to use

Exactly, that's why we need this feature : )
