### ISSUE TITLE
If the task fails after manual execution, restore the failed task, $[yyyyMMddHHmmss] will be the new time

### ISSUE THREAD

**Issue by momomobinx** [apache/dolphinscheduler#9823]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

If the task fails after manual execution, restore the failed task, $[yyyyMMddHHmmss] will be the new time，but what I need is the time of the first execution。
Note that it is executed manually, not scheduled

### What you expected to happen

If the task fails after manual execution, restore the failed task, $[yyyyMMddHHmmss] is the time of the first execution

### How to reproduce

Manually execute a task that uses the $[yyyyMMddHHmmss] variable and must fail, restore it

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @momomobinx , I think what you need is to specify complement's date when starting manually. When the process instance starting manually without complement's date it will use the current date to execute.

**Comment by momomobinx** [comment]
> Hi @momomobinx , I think what you need is to specify complement's date when starting manually. When the process instance starting manually without complement's date it will use the current date to execute.

If it is not a scheduled task ？

**Comment by momomobinx** [comment]
> Hi @momomobinx , I think what you need is to specify complement's date when starting manually. When the process instance starting manually without complement's date it will use the current date to execute.

It‘s work, but it is not very convenient. It may not be a scheduling task. The default is from the current time to the current time.
