### ISSUE TITLE
[Bug][UI-Next][V1.0.0-Beta] The workflow name spelling error.

### ISSUE THREAD

**Issue by Amy0104** [apache/dolphinscheduler#9824]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="596" alt="image" src="https://user-images.githubusercontent.com/97265214/165695878-d9c17b65-06db-4f19-b2da-9684678818b3.png">

### What you expected to happen

Should be workflow not wrokflow.

### How to reproduce

1. Open the workflow definition page.
2. Create a workflow.
3. Create a dependent task.
4. Add a dependency.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.
