### ISSUE TITLE
[Feature][standalone] Add UI to our standalone server docker images when release to docker hub

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#9841]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

currently, we released a standalone server to docker hub without including UI components, and users could not log in UI when using standalone, some of them maybe think that is a bug when they use it

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songangweb** [comment]
Is there a scheduled completion date for this?

**Comment by zhongjiajie** [comment]
will add this before we release 3.0.0-bate @songangweb

**Comment by zhongjiajie** [comment]
duplicate to #9863 and close it
