### ISSUE TITLE
[Feature][dependencies] Bump spring-core from 5.3.12 to 5.3.19

### ISSUE THREAD

**Issue by SbloodyS** [apache/dolphinscheduler#9842]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

#9676 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hezean** [comment]
Hi, I'd like to try it! Does that means my only target is passing CI?
<img width="581" alt="Screen Shot 2022-07-08 at 22 36 59" src="https://user-images.githubusercontent.com/49837965/178013870-49f5e6f8-9069-4a06-89a3-615e7bb06e56.png">

**Comment by SbloodyS** [comment]
> Hi, I'd like to try it! Does that means my only target is passing CI? <img alt="Screen Shot 2022-07-08 at 22 36 59" width="581" src="https://user-images.githubusercontent.com/49837965/178013870-49f5e6f8-9069-4a06-89a3-615e7bb06e56.png">

Yes. Would you like to take it?

**Comment by hezean** [comment]
Many thanks if there's a chance to work on it! If there's any problem I'll update the state back here

**Comment by SbloodyS** [comment]
> Many thanks if there's a chance to work on it! If there's any problem I'll update the state back here

I've assigned to you. Looking forward to your contribution.
