### ISSUE TITLE
[Feature][pkg] Slim binary distribute package

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#9843]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

After version 3.0.0-alpha, we release the dist package in a separate server, but our dependencies do not isolate well and cause our binary package to be very large. We should find some way to slim our binary distribute package

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
related PR https://github.com/apache/dolphinscheduler/pull/9435

**Comment by zhongjiajie** [comment]
related PR https://github.com/apache/dolphinscheduler/pull/9372

**Comment by zhongjiajie** [comment]
related PR #9019

**Comment by kezhenxu94** [comment]
~570MB, there is no known optimization for now
