### ISSUE TITLE
[Bug] [api] Query access token for specified user failed

### ISSUE THREAD

**Issue by AirToSupply** [apache/dolphinscheduler#9854]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

We try to pull the dev branch to try to deploy the cluster. When storing metadata through the **PostgreSQL** database, an exception occurred when calling the following interface to **query access token for specified user**. The interface method signature is as follows:

![image](https://user-images.githubusercontent.com/62897740/165958850-19673cdb-9cd6-4c8a-bbab-a6d9b73d0627.png)

The exception log is as follows:

![image](https://user-images.githubusercontent.com/62897740/165959122-309e49dd-1f1c-43ca-b3df-a4033629a378.png)

### What you expected to happen

There is a problem with the queryAccessTokenByUser method SQL in the AccessTokenMapper.xml file. The main problem is that MySQL can use the '**`**' symbol to represent the field name, but it is not supported in PostgreSQL.

### How to reproduce

This exception works with MySQL database as storage, but as PostgreSQL database will generate exception

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
close due to #9855
