### ISSUE TITLE
[Bug] [Api] Failed to upload the file because the full name was too long, but get misleading message

### ISSUE THREAD

**Issue by litiliu** [apache/dolphinscheduler#9856]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When the resource's fullname is longer than the max length of the field named "full_name" in t_ds_resources, the insert option will fail.  But the misleading message "resource already exists, can't recreate" will be returned, which is not the root cause.

### What you expected to happen

Add a validation of name length, before insert record into db.

### How to reproduce

Create a folder with a name length of 64, then upload a file with a name length longer than 64 to that folder.

### Anything else

It happens every time.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Thank you for your feedback
