### ISSUE TITLE
[Bug] [master worker] [slave worker] master and workd client session timed out caused by heart. why not try restart.

### ISSUE THREAD

**Issue by chaozwn** [apache/dolphinscheduler#9857]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The way I use is the pseudo stand-alone cluster version of dolphin, but sometimes the master and worker nodes will hang up by themselves, and will not recover by themselves after that, unless the service is stopped and restarted.
What I want to express is that this seems very unreasonable in production. I don’t know if there is an automated way to automatically restart the master and worker after they are offline.

![image](https://user-images.githubusercontent.com/51357674/166127553-7cc79b9d-f8b3-4521-bc69-e1cd783441c7.png)
![image](https://user-images.githubusercontent.com/51357674/166127555-0a6b430a-b6f5-4a0f-ae25-ee92c6820c83.png)

### What you expected to happen

When a failure occurs, it can automatically restart and recover.

### How to reproduce

no

### Anything else

no

### Version

1.3.9

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
The default ```master.heartbeat.interval``` and ```worker.heartbeat.interval``` is 10s. I think it's a very long time that there is no response in 10 seconds in the production environment. Need to find out why it can't respond.

BTW, the default ```master.heartbeat.interval``` and ```worker.heartbeat.interval``` can be changed in ```master.properties``` and ```worker.properties```
