### ISSUE TITLE
[Bug] [doc] 3.00-alpha Data quality doc link error

### ISSUE THREAD

**Issue by chens616** [apache/dolphinscheduler#9871]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

we click  data quality  menu in the 3.00-alpha doc ,there is a Not Found page.

### What you expected to happen

when we click  data quality  menu，we can sea a correct about data quality.

### How to reproduce

when you click data quality menu in the 3.00-alpha doc on the official website, you can sea this problem.

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
already add by commit https://github.com/apache/dolphinscheduler/pull/9865
