### ISSUE TITLE
[Bug] [datax -hdfsreader] java.lang.IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by 1205823696** [apache/dolphinscheduler#9885]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

   Hello!
   Datax daily scheduling hdfsreader a null value occurs, causing a task exception. The job that is configured to continue scheduling does not take effect. Procedure

The exception information is as follows:
![image](https://user-images.githubusercontent.com/52704749/166861655-7ca4b451-5658-4ec1-a389-62b040f591b8.png)

### What you expected to happen

How can I configure scheduling to allow datax to skip this exception and continue with the task when THERE is no DATA in HDFS

Looking forward to your answer. Thank you

### How to reproduce

If the table corresponding to HDFS has no data, it will appear

### Version

1.3.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @1205823696 , 1.3.8 is no longer in the maintenance list. Could you check if this exists in the latest version?

**Comment by 1205823696** [comment]
> 你好@1205823696, 1.3.8 不再在维护列表中。你能检查一下这是否存在于最新版本中？

I'm not using the latest version, the one I used before. I am not sure whether this exception will exist in the new version, according to the logic of my task configuration to continue to execute the task should continue to execute the task but it did not

**Comment by SbloodyS** [comment]
It is recommended to upgrade to the latest release version. @1205823696

**Comment by zhongjiajie** [comment]
Did we support task failed but continue workflow now?

**Comment by SbloodyS** [comment]
> Did we support task failed but continue workflow now?

Yes. We have the failure strategy.

**Comment by zhongjiajie** [comment]
I think is should work, I will close this issue template, you could reopen it if you have further issue
