### ISSUE TITLE
error throwed out when clicking the parent directory In 【Resource-File Manage】

### ISSUE THREAD

**Issue by AnchorOscarWoo** [apache/dolphinscheduler#9892]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In Resource-File Manage ,the page will throw out an error massage when clicking the parent directory in the breadcrumb.
![image](https://user-images.githubusercontent.com/21033697/166880794-b914fd98-db8b-4754-9f60-b2d82b77b7e0.png)

### What you expected to happen

the page shall jump into the URL where i click (like , parent directory).

### How to reproduce

1. use HDFS as storage type
2. build several directories (make sure at least 1 directory has  parent directory)
3. click into a dictionary with a  parent directory.
4. click the name of any parent directory in the breadcrumb.
5. the error gotta be throwed out when clicking.

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Related issue: #9374

**Comment by AnchorOscarWoo** [comment]
> Related issue: #9374

1

**Comment by devosend** [comment]
Hi @AnchorOscarWoo, Please complete the title of this question.

**Comment by hushubudu** [comment]
in 2.0.6 version , the same problem occurs

**Comment by hushubudu** [comment]
can anyone give a solution? it is very inconvenient when browse the directory structure in resouce center
