### ISSUE TITLE
(only 1 instance)the end time of a process Instance is earlier than start time.

### ISSUE THREAD

**Issue by AnchorOscarWoo** [apache/dolphinscheduler#9894]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

the end time of a process Instance is earlier than start time.

<img width="1084" alt="1651737301(1)" src="https://user-images.githubusercontent.com/21033697/166882702-dccc0117-563d-4dc2-bdb9-00ab5d0165f7.png">

### What you expected to happen

the end time should later than start time.

### How to reproduce

it's really hard to reproduce . In my project , only 1 instance shows this problem.

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @AnchorOscarWoo , can you provide the steps of reproduction?

**Comment by AnchorOscarWoo** [comment]
> Hi @AnchorOscarWoo , can you provide the steps of reproduction?

Hi @SbloodyS

I just click “start” in page “Process definition” , then in page "Process Instance" I can see a instance its END TIME is earlier than START TIME.

It's really hard to reproduce , it's not a 100% probability problem . if this problem shows again , i will record how i operate in a document and put it into this issue.
