### ISSUE TITLE
[Feature][UI] Remove old `UI` .

### ISSUE THREAD

**Issue by songjianet** [apache/dolphinscheduler#9896]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Remove the old `UI` code in the `dev` branch.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
should remove `UI` module and rename `UI-next` to `UI`

**Comment by songjianet** [comment]
> should remove `UI` module and rename `UI-next` to `UI`

yes

**Comment by zhongjiajie** [comment]
Also need to change build `pom.xml` too.

**Comment by songjianet** [comment]
> Also need to change build `pom.xml` too.

yes, I will deal with it, I will find someone to review it later.
