### ISSUE TITLE
[Feature][doc] Upgrade screenshot to latest version in dev document

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#9898]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I find out still some old UI screenshots in our document, such as https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/project/workflow-definition.html .  We should change them to the latest version screenshots

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
## about

* https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/about/glossary.html

## task

* https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/task/stored-procedure.html
* https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/task/datax.html
* https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/task/pigeon.html
* https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/task/switch.html

## parameter

* https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/parameter/local.html
* https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/parameter/context.html
* https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/parameter/priority.html

## alter

* https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/alert/alert_plugin_user_guide.html
* https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/alert/telegram.html
* https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/alert/dingtalk.html

**Comment by zhongjiajie** [comment]
@QuakeWang

**Comment by QuakeWang** [comment]
OK, I get it. This week I will refactor the document about parameters. The [local-parameter](https://github.com/apache/dolphinscheduler/pull/10119) have submitted. BTW the task of [datax](https://github.com/apache/dolphinscheduler-website/pull/723/files) I have refactored but in the website still as the old version.

**Comment by zhongjiajie** [comment]
> OK, I get it. This week I will refactor the document about parameters. The [local-parameter](https://github.com/apache/dolphinscheduler/pull/10119) have submitted. BTW the task of [datax](https://github.com/apache/dolphinscheduler-website/pull/723/files) I have refactored but in the website still as the old version.

I find out your change is to repository dolphinscheduler-website  branch master, maybe we miss something when we migrate to repository dolphinscheduler

**Comment by zhongjiajie** [comment]
I will find a way to recover it

**Comment by zhongjiajie** [comment]
> I will find a way to recover it

recover by https://github.com/apache/dolphinscheduler/pull/10218

**Comment by zhongjiajie** [comment]
Could we close this issue since #10242 merged? @QuakeWang

**Comment by QuakeWang** [comment]
> Could we close this issue since #10242 merged? @QuakeWang

OK, It can be closed. The rest of the documentation is about tasks. We can discuss this in the relevant sub-issue.
