### ISSUE TITLE
[Improvement][Next UI] Import Workflow placeholder

### ISSUE THREAD

**Issue by devosend** [apache/dolphinscheduler#9899]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Disable file name

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/8847400/166887683-335481a8-a334-4440-a55f-e2890329e1cf.png">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by labbomb** [comment]
i will fix it
