### ISSUE TITLE
[Bug] [Quartz] cron did not work as expected

### ISSUE THREAD

**Issue by qingxing7** [apache/dolphinscheduler#9905]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Environment: Single-node deployment version 2.0.5, mysql RDS 5.7, ZK 3.5.x Linux Centos7 32C64G

Procedure: After the deployment is complete, tenants and projects are created and a periodic shell task is configured to be executed every minute.

Symptom: The scheduled task is executed once when it reaches the scheduled time and will not be executed again when the time expires. In addition, the master log does not display any information, and the manual workflow starts normally. Each time the service is restarted, the timing can be executed once and will not be executed later.

I have used version 1.3.1 before and have run it for a year and a half without any problems

### What you expected to happen

cron work

### How to reproduce

cron work

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by brave-lee** [comment]
@caishunfeng Please take a look

**Comment by qingxing7** [comment]
this is dolphinscheduler-master.log

Step 1: Offline timing, and then online timing

Step 2: Observe that the task is not performed at the specified time

Step 3: If manually triggered, the operation is normal
![Uploading 799FD2E7-398B-49AA-9099-AC5EC06B31E7.jpeg…]()

**Comment by qingxing7** [comment]
![87655CEE-4BFA-4559-A06A-4860220E8159](https://user-images.githubusercontent.com/63483033/167058821-ec8a0784-84b3-4bec-9ecb-fb3c828ea145.jpeg)
![5FEFA16D-D007-44E8-A589-F204877D5D04](https://user-images.githubusercontent.com/63483033/167058824-b8cb620f-0d0c-4fb1-a73f-b5c808cf55d3.jpeg)
![0D596C0C-D22B-45B4-8F13-F12EAA443766](https://user-images.githubusercontent.com/63483033/167058827-16d6cdaa-a247-4179-9ba7-2fd485900777.jpeg)
![E313B561-0429-412C-924D-EA8B05CA001F](https://user-images.githubusercontent.com/63483033/167058831-63b0ce6a-7e83-410c-9ee3-ab524085a83c.jpeg)

**Comment by qingxing7** [comment]
![Uploading 6BF0CB8B-7BA8-4B59-9267-9F109A18AE27.jpeg…]()

**Comment by qingxing7** [comment]
thanks

**Comment by caishunfeng** [comment]
@qingxing7 it seems some img upload failed, please upload again, thanks.

**Comment by qingxing7** [comment]
![Uploading FC91445B-CFF2-4A72-8801-27C38F823FE9.jpeg…]()

**Comment by qingxing7** [comment]
Maybe there is something wrong with my phone, I will upload it later; Today, when I tried to deploy again, I changed RDS to self-built mysql, timing is normal, is it the problem of using RDS？

**Comment by caishunfeng** [comment]
> Today, when I tried to deploy again, I changed RDS to self-built mysql, timing is normal, is it the problem of using RDS？

I don't think it's a RDS problem, but you can check it again.

**Comment by zhaohehuhu** [comment]
I came cross a same problem.

**Comment by caishunfeng** [comment]
> I came cross a same problem.

Hi @luoyedeyi do you fix this issue?
