### ISSUE TITLE
[Feature] [Parameters] Take the process ID as the global parameter

### ISSUE THREAD

**Issue by chuxiangfeng** [apache/dolphinscheduler#9908]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

At present, there are too few global parameters. There are only three time parameters. I hope to use the process ID as the global parameter when starting the process

### Use case

As a scheduling tool, a complete process may be scheduled by programs in various languages. It is hoped that the process ID can be used as the global parameter to run through each process node, which is very important. Otherwise, I don't know whether each node runs in a process every time. For example, if the process ID is used as the global parameter, the processing records or logs of each node can be bound with the process ID and finally collected, The complete data can be grouped according to the process ID each time

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by selectbook** [comment]
WeOpen Star
