### ISSUE TITLE
Fix packaging method in data quality module

### ISSUE THREAD

**Issue by kezhenxu94** [apache/dolphinscheduler#9920]
That's not the only reason not to use jar with dependencies, why should this module use this package style? My question is this kind of package will duplicate the dependencies in the dist tar

_Originally posted by @kezhenxu94 in https://github.com/apache/dolphinscheduler/pull/6718#discussion_r866798911_

**Comment by kezhenxu94** [comment]
@zixi0825 please address this problem

**Comment by zixi0825** [comment]
> @zixi0825 please address this problem

ok

**Comment by kezhenxu94** [comment]
@zixi0825 see my PR https://github.com/apache/dolphinscheduler/pull/9944#discussion_r867579565
