### ISSUE TITLE
[Bug] [Server] Worker workerWaitingTaskCount has always been zero

### ISSUE THREAD

**Issue by brave-lee** [apache/dolphinscheduler#9921]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[zk: localhost:2181(CONNECTED) 25] get /dolphinscheduler/nodes/worker/default/host:1234
0.02,0.39,0.38,19.06,16.0,0.3,1651832787990,1651833001883,0,30984,100,2,0

![image](https://user-images.githubusercontent.com/42576980/167137887-4af6cafc-84d7-4256-83e4-2296ac46f261.png)

### What you expected to happen

zk data of the last parameter should have a value

The reason is that workerWaitingTaskCount cannot get variables outside the thread
Solution: It is recommended to disassemble HeartBeatTask into MasterHeartBeatTask and Worker HeartBeatTask

### How to reproduce

dev

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
close by #11232
