### ISSUE TITLE
[Bug] [Monitor/Statistics] The number of tasks to be run and the number of tasks to be killed The two modules are hidden

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9926]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The number of tasks to be run and the number of tasks to be killed The two modules are hidden

<img width="1646" alt="image" src="https://user-images.githubusercontent.com/76080484/167233787-81dab07f-7284-42f0-ba87-c32e6371eb8d.png">

### What you expected to happen

Can't get statistics because of logic change

### How to reproduce

The number of tasks to be run and the number of tasks to be killed The two modules are hidden

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
I will fix it.
