### ISSUE TITLE
[Bug] [DAO] Workflow execution time increases gradually

### ISSUE THREAD

**Issue by winskin** [apache/dolphinscheduler#9937]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

说明：耗时随着数据增加而增加，测试耗时从4s增加到20s，只有一个调度任务在跑。
Note: The time-consuming increases as the data increases, the test time increases from 4s to 20s, and only one scheduling task is running.

排查：发现是工作流执行时会查询t_ds_task_instance表，主要的耗时集中在这里，如果能减少查询时间即可降低耗时。
Troubleshooting: It is found that the t_ds_task_instance table is queried when the workflow is executed. The main time-consuming is concentrated here. If the query time can be reduced, the time-consuming can be reduced.

临时解决：t_ds_task_instance表增加索引（当前t_ds_task_instance表数据量为20万）
Temporary solution: add an index to the t_ds_task_instance table (the current data volume of the t_ds_task_instance table is 200,000)

```sql
CREATE INDEX t_ds_task_instance_process_instance_id_idx ON t_ds_task_instance (process_instance_id,task_code);
```

效果：有效提升
Effect: Effectively improve

![image](https://user-images.githubusercontent.com/11605556/167246663-1753469a-7af3-4af3-8525-9e93a91135f4.png)

### What you expected to happen

耗时降低
time-consuming reduction

### How to reproduce

t_ds_task_instance表数据量越大，耗时增加越多
The larger the amount of data in the t_ds_task_instance table, the more time-consuming

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @winskin , please use english to describe it. Feel free to reopen this issue while you change it to english.

**Comment by winskin** [comment]
> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.
> 
> ### What happened
> Note: The time-consuming increases as the data increases, the test time increases from 4s to 20s, and only one scheduling task is running.
> 
> Troubleshooting: It is found that the t_ds_task_instance table is queried when the workflow is executed. The main time-consuming is concentrated here. If the query time can be reduced, the time-consuming can be reduced.
> 
> Temporary solution: add an index to the t_ds_task_instance table (the current data volume of the t_ds_task_instance table is 200,000)
> 
> ```sql
> CREATE INDEX t_ds_task_instance_process_instance_id_idx ON t_ds_task_instance (process_instance_id,task_code);
> ```
> 
> Effect: Effectively improve
> 
> ![image](https://user-images.githubusercontent.com/11605556/167246663-1753469a-7af3-4af3-8525-9e93a91135f4.png)
> 
> ### What you expected to happen
> time-consuming reduction
> 
> ### How to reproduce
> The larger the amount of data in the t_ds_task_instance table, the more time-consuming
> 
> ### Anything else
> _No response_
> 
> ### Version
> 2.0.5
> 
> ### Are you willing to submit PR?
> * [ ]  Yes I am willing to submit a PR!
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)



> Hi @winskin , please use english to describe it. Feel free to reopen this issue while you change it to english.

Bot has helped translate it into English, here

**Comment by SbloodyS** [comment]
@winskin You can copy it to your issue's description.
