### ISSUE TITLE
[Bug] [server master] need fault tolerance task environment_config is null

### ISSUE THREAD

**Issue by someorz** [apache/dolphinscheduler#9938]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

need fault tolerance task  environment_config is null task execute failed
![image](https://user-images.githubusercontent.com/5456361/167248391-cca537f8-b68c-4ab7-8e9c-f0befb5b9e77.png)

### What you expected to happen

![image](https://user-images.githubusercontent.com/5456361/167248455-fc52cf07-cf88-4776-b289-1efe02555a79.png)

### How to reproduce

1

### Version

2.0.5

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Hi @someorz , would you like to fix it with a new PR?
