### ISSUE TITLE
[Feature][script] Bash in tools/bin is not executable

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#9960]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

<img width="700" alt="image" src="https://user-images.githubusercontent.com/15820530/167447990-4a86b954-ffe4-40f6-9a92-1cbeefa066c8.png">

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Maybe this feature is no longer needed.  What do you think?
relative pr: #9733

**Comment by zhongjiajie** [comment]
currently, our shell script in `bin` could be executed when we extract files from the tarball, but not for `tools` directory. and users have to `sh tools/bin/create-schema.sh` instead of `./tools/bin/create-schema.sh` I think if we could support the second command will be more user friendly, WDYT?

**Comment by zhongjiajie** [comment]
remove stale
