### ISSUE TITLE
[Bug-BE] [Workflow Instance] Input is not recognized

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9964]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="1913" alt="image" src="https://user-images.githubusercontent.com/76080484/167534314-0c205386-e7cf-47a8-838d-52e8fcbcc0c9.png">

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/76080484/167534354-aadef2a8-f1f1-488d-b314-bcb5b2d1a203.png">

### What you expected to happen

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/76080484/167535695-fbd379e9-f1e1-4867-a33c-c1033e1215e9.png">

### How to reproduce

Use system built-in functions, shell components, and execute workflows

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
I think it can be solved by change the system ```locale``` to ```utf-8```
