### ISSUE TITLE
[Bug] [UI] The data quality tab page cannot switch with other pages normally

### ISSUE THREAD

**Issue by zixi0825** [apache/dolphinscheduler#9969]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![SwitchToDataQuality](https://user-images.githubusercontent.com/10829956/167595110-c824603a-151b-4404-89c0-3a9907f7f891.png)

![SwitchToResource](https://user-images.githubusercontent.com/10829956/167595424-970016e1-02b6-4da5-ba84-670ce96c174a.png)

When I click the data quality tab page, I can't switch to other tabs

### What you expected to happen

The tab page can be switched normally

### How to reproduce

Click DataQuality tab page ，and click other page

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rockfang** [comment]
that's a frontend bug, i want to fix it. @caishunfeng @labbomb
