### ISSUE TITLE
[Bug] [DataQuality] Can not generate command

### ISSUE THREAD

**Issue by zixi0825** [apache/dolphinscheduler#9973]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When execute data quality task，can not generate the execute command

### What you expected to happen

Data Quality task execute success.

### How to reproduce

execute data quality task

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
Hi @zixi0825 How is this issue going? Can it be done this week? Otherwise we will move it to the next version milestone.

**Comment by zixi0825** [comment]
> Hi @zixi0825 How is this issue going? Can it be done this week? Otherwise we will move it to the next version milestone.

Has submitted PR and merged

**Comment by caishunfeng** [comment]
> Has submitted PR and merged

OK, I will close this issue.  BTW, it's better to link the PR here.
