### ISSUE TITLE
[Bug-BE] The selected task instance was recreated when the Master service failed over

### ISSUE THREAD

**Issue by WangJPLeo** [apache/dolphinscheduler#9975]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The selected task instance was recreated when the Master service failed over

### What you expected to happen

No new instances should be created.

### How to reproduce

Stop the Master service during workflow execution, and then start the Master again.

### Anything else

No Response.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
When failover, it will create a new task instance to rerun.
So I think this issue maybe is not a bug.
