### ISSUE TITLE
[Bug] [dolphinscheduler-tools]  column does not exist

### ISSUE THREAD

**Issue by andy-gezl** [apache/dolphinscheduler#9979]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

docker-compose install dolphinscheduler env, service "dolphinscheduler-schema-initializer" didn't completed successfully.
o.a.d.dao.upgrade.ProcessDefinitionDao   : ERROR: column "process_definition_json" does not exist

### What you expected to happen

I want  service "dolphinscheduler-schema-initializer"  completed successfully

### How to reproduce

DOLPHINSCHEDULER_VERSION=3.0.0-alpha
download apache-dolphinscheduler-"${DOLPHINSCHEDULER_VERSION}"-src.tar.gz
tar -zxf apache-dolphinscheduler-"${DOLPHINSCHEDULER_VERSION}"-src.tar.gz
cd apache-dolphinscheduler-"${DOLPHINSCHEDULER_VERSION}"-src/deploy/docker
docker-compose up -d

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This problem has been fixed in #9628 . I'll close this issue. Thanks for your feedback.
