### ISSUE TITLE
[Bug] [deploy on k8s by helm] Some docker image is not exist and doc has some issues

### ISSUE THREAD

**Issue by qingwli** [apache/dolphinscheduler#9984]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Some docker image does not exist and the doc has some issues.

### What you expected to happen

deploy succeeded.

### How to reproduce

# 1. Some Docker Images do not exist.

```
➜  ~ docker pull dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler-tools:3.0.0-alpha
Error response from daemon: repository dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler-tools not found: name unknown: repository name not known to registry
➜  ~ docker pull dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler-api:3.0.0-alpha
Error response from daemon: repository dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler-api not found: name unknown: repository name not known to registry
➜  ~ docker pull dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler-alert-server:3.0.0-alpha
Error response from daemon: repository dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler-alert-server not found: name unknown: repository name not known to registry
```
The 3.0.0-alpha image registry is [dolphinscheduler.docker.scarf.sh/apache](https://github.com/apache/dolphinscheduler/blob/3.0.0-alpha-release/deploy/kubernetes/dolphinscheduler/values.yaml#L25), and I see the Docker image is well at [docker hub](https://hub.docker.com/layers/dolphinscheduler-api/apache/dolphinscheduler-api/3.0.0-alpha/images/sha256-e45078529d80d146e28a979df8cf5c48d900b7cb1aa722624fb868697db811b0?context=explore)

Thanks, @kezhenxu94 , now it works.

# 2. db-init-job failed when use pg as metadata.
Same as #9963. Fixed by #9997

# 3. QuickStart in Kubernetes Doc Error

## 1. Install DolphinScheduler Part
```
$ cd apache-dolphinscheduler-3.0.0-alpha-src/docker/kubernetes/dolphinscheduler
```

The Kubernetes folder is moved to ```deploy/kubernetes/dolphinscheduler```, ~~I'll open a PR to fix this problem.~~ Fixed by #9985 

## 2. Use MySQL && Support MySQL && Support Oracle && Support Python 2 pip && Support Python 3 in FAQ Part

Dolphinscheduler has changed all services to different docker images after version 3.0.0. So when we want to Support Mysql or Oracle. Maybe needs to change the API && Master && Worker && alert-service docker images. I'm not sure because I not familiar with this part, but the doc is not correct. Fixed by #10221 

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
@liqingwang I find out you submit and PR #9994 , does it fix this issue?

**Comment by qingwli** [comment]
@zhongjiajie 
3. QuickStart in Kubernetes Doc Error  - 2. Use MySQL && Support MySQL && Support Oracle && Support Python 2 pip && Support Python 3 in FAQ Part
 
 This part not fix.
