### ISSUE TITLE
[Bug] [UI] The task results under the data quality menu can only display the latest 10 records, and the paging and jump functions are not available. F12 debugs to view the query results of the task results, and there are 31 returned results.

### ISSUE THREAD

**Issue by duspring** [apache/dolphinscheduler#9986]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/35389283/167789045-d747f0ed-f0b4-477e-ac67-20b0bbc23b2c.png)
![image](https://user-images.githubusercontent.com/35389283/167789066-5bc297d0-132f-45bd-84b3-0e9580f23f59.png)
![image](https://user-images.githubusercontent.com/35389283/167789101-98b457de-188d-4cc3-a01b-d0a90fc8c349.png)
![image](https://user-images.githubusercontent.com/35389283/167789623-b100cba0-c95f-488c-a8bf-eb365fc466e2.png)
![image](https://user-images.githubusercontent.com/35389283/167789701-04a0201d-b6da-4532-b44d-181c8e32d6ed.png)

The task results under the data quality menu can only display the latest 10 records, and the paging and jump functions are not available. F12 debugs to view the query results of the task results, and there are 31 returned results. In addition, the error data path (errorOutputPath) is not displayed, and the interface can query the data.

### What you expected to happen

The task results under the data quality module can be paged normally and jump to the specified page to display all the verification results. The error data path (errorOutputPath) can be displayed normally

### How to reproduce

Click the task result menu to query the data, and find more than 10 items, which cannot be paginated, and the displayed ones are always the latest, similar to top10.

### Anything else

No response

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
This issue is not reproduced.Could you check this again? @duspring

**Comment by Amy0104** [comment]
I checked the code. This issue has been solved by @rockfang
