### ISSUE TITLE
[Bug-BE] [sql component] sql component failed to run

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9991]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

sql component failed to run

<img width="1917" alt="image" src="https://user-images.githubusercontent.com/76080484/167818413-a43c4a22-7758-43de-97bd-50d013ed5bc9.png">

### What you expected to happen

sql component runs successfully

### How to reproduce

[ERROR] 2022-05-11 09:31:17.553 +0000 [taskAppId=TASK-20220511-5469970732736_2-22-42] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.sql.SqlTask:[213] - execute sql error: Operation not allowed after ResultSet closed
[ERROR] 2022-05-11 09:31:17.553 +0000 [taskAppId=TASK-20220511-5469970732736_2-22-42] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.sql.SqlTask:[164] - sql task error: java.sql.SQLException: Operation not allowed after ResultSet closed

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by huangchenguang123** [comment]
我在用mysql测试的时候遇到的相同的问题，查询任务无法运行，非查询可以，请问你是查询任务出现的场景吗

**Comment by huangchenguang123** [comment]
the reasion is statement is closed before resultSet.getMetaData(), see org.apache.dolphinscheduler.plugin.task.sql.SqlTask#executeQuery, executeQuery use AutoClose

can i try to fix this issus? @devosend

**Comment by SbloodyS** [comment]
> the reasion is statement is closed before resultSet.getMetaData(), see org.apache.dolphinscheduler.plugin.task.sql.SqlTask#executeQuery, executeQuery use AutoClose
> 
> can i try to fix this issus? @devosend

You are welcome to fix this issue. I'll assign to you. Looking forward to your contribution.
