### ISSUE TITLE
[Bug] [task plugin] Execute multiple HIVE SQL errors in a single session

### ISSUE THREAD

**Issue by GodWon** [apache/dolphinscheduler#9992]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

所有common.properties文件内 都配置了support.hive.oneSession=true， 但是实际情况多个hivesql任务无法执行。

### What you expected to happen

希望在同一个会话中执行多个 HIVE SQL， 结果报错。 所依更无法设置任务名称 set mapred.job.name

### How to reproduce

![image](https://user-images.githubusercontent.com/17845085/167820794-a18d9cde-9a23-4228-b25a-f7578b96b10d.png)

![image](https://user-images.githubusercontent.com/17845085/167820436-5f5b859d-5bd8-46b1-b096-e901cf31aa27.png)

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
This has been implement in #9177 . I'll close this issue.

**Comment by EricGao888** [comment]
> This has been implement in #9177 . I'll close this issue.

@SbloodyS Looks like #9177 enables users to write multiple lines of mysql but still not support users to write multiple lines of hive sql. Maybe we could reopen this issue?
