### ISSUE TITLE
[Bug-FE] [Workflow Instance-Gantt] The task name is too long and the display is incomplete

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9993]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The task name is too long and the display is incomplete

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/76080484/167821659-22367f4b-9eaa-4ecb-9d06-323a4c0059b0.png">

### What you expected to happen

The display is normal, or the super long is hidden, and the mouse hovers to display the full name

### How to reproduce

Workflow Instance Click Gantt Chart

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix it
