### ISSUE TITLE
[Bug-FE] [Resource] Under Resource Management, multiple attachments are uploaded, one attachment is expected to be displayed.

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#9996]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. uploaded multiple attachment
![image](https://user-images.githubusercontent.com/59044203/167844947-51eac7e2-cc9d-4178-b559-5e7b108f7079.png)

### What you expected to happen

one attachment is expected to be displayed.

### How to reproduce

None.

### Anything else

None.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment]
It seems better to support only one file upload.
