### ISSUE TITLE
[Feature][CI] Add Dead Link Checker

### ISSUE THREAD

**Issue by wuchunfu** [apache/dolphinscheduler#9999]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add Dead Link Checker

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
@wuchunfu does it related to #10004?

**Comment by wuchunfu** [comment]
> @wuchunfu does it related to #10004?

@zhongjiajie It's related, but #10004 doesn't seem to check out all the dead links

**Comment by zhongjiajie** [comment]
Is there any other dead link we miss? @wuchunfu

**Comment by wuchunfu** [comment]
> Is there any other dead link we miss? @wuchunfu

@zhongjiajie You can take a look at this PR #10000
